### ISSUE TITLE
Let's encrypt error

### ISSUE THREAD

**Issue by mcules** [Ylianst/MeshCentral#10]
When i try to generate an LE certificate i get an error in the logs:

> Error: options.newRegUrl must be the a new registration url

No certificate is generated.

**Comment by Ylianst** [comment]
Let me know if you still get this error. MeshCentral2 was improved a lot and I now use Let's Encrypt on one of my servers and so far, it's working perfectly.

**Comment by Ylianst** [comment]
I did some improvements to Let's Encrypt code yesterday to update from ACMEv1 to ACMEv2. Other have had success with it. I will close this issue but don't hesitate to re-open if the problem occurs again.
