### ISSUE TITLE
Timeout Error in Chrome for Intel AMT tab (Firefox OK)

### ISSUE THREAD

**Issue by gertvdijk** [Ylianst/MeshCentral#100]
Version: "2.0 beta 2"

Steps to reproduce:
1. Use Google Chrome browser.
1. Open an AMT host.
1. Navigate to the AMT tab.
1. Hit the "Connect" button.
1. See some progress, but then it fails with a timeout error:
  ![timeout](https://user-images.githubusercontent.com/1550527/52817125-3fd16200-30a3-11e9-9a06-fdfc56d97d8c.png)
1. Open Firefox.
1. Connect the same way as steps 2-4.
1. It works perfectly fine!

To me it looks like this is a browser-specific issue.

This happens with MeshCentral in a completely clean Docker environment with an AMT host freshly configured.

Other things I observe:

* Nothing in the browser Console log.
* Network traffic in the browser developer tools shows five websocket connections taking ~ 14.96-15.06 seconds, looks suspiciously precise around 15 seconds. Chrome doesn't really tell more than "Binary frame" for the contents.
* Nothing logged on the console of the MeshCentral application.

**Comment by Ylianst** [comment]
Interesting! Thank you for a well written report. I got an idea what is going on. It has to do with JavaScript buffer conversion when traffic is received. I think I fixed it at other place, but not in the Intel AMT tab. I will look into this...

**Comment by Ylianst** [comment]
I think I fixed this one about a week ago. Would appreciated confirmation that it's fixed.

**Comment by Ylianst** [comment]
I think this one is fixed. If it show up again, please re-open.
