### ISSUE TITLE
Prompt for user consent - with timeout default to "yes" or "no"

### ISSUE THREAD

**Issue by unguzov** [Ylianst/MeshCentral#1001]
I really like "Prompt for user consent" settings in TightVNC - you can set to default to "yes" or "no" after "x" seconds. This is very useful in scenarios when user just goes away from the machine (as they often do) or to have time to close sensitive information on screen.

**Comment by Ylianst** [comment]
This is a good request.

**Comment by eldadh** [comment]
I think this Is a must Feature for IT Teams.
it allows both non-interruptive suuport ( with user concent) and the ability to function if the user left 
Is This Feature still a Work In Progress, or have you decided not to implement?

**Comment by unguzov** [comment]
> I think this Is a must Feature for IT Teams.
> it allows both non-interruptive suuport ( with user concent) and the ability to function if the user left
> Is This Feature still a Work In Progress, or have you decided not to implement?

At this point I ask for access with right mouse button and after timeout I just enter on the PC.

**Comment by si458** [comment]
this feature exists now
but is sadly a domain side config and not a per group setting yet
https://github.com/Ylianst/MeshCentral/blob/dd172a2b245acd0cb6eeb4539fc1ef0b0fcfb3cf/meshcentral-config-schema.json#L1707-L1735

**Comment by si458** [comment]
Closing in favour of #547 which wants per group timeout settings
