### ISSUE TITLE
Add a MeshCmd flag to disable/re-enable AMT WiFi

### ISSUE THREAD

**Issue by nafogel** [Ylianst/MeshCentral#1003]
When using AMT CIRA and IDE-R to boot to an ISO over AMT WiFi, the operating system is unable to see the wireless NIC because AMT is using it.

I have tested and confirmed that by launching LMS and manually setting the wireless interface state under network settings to disabled releases AMT's hold on the wireless NIC allowing the operating system to utilize it.

By adding a flag to MeshCmd to do this the process could be simplified and even automated for fully automated OS installs over AMT WiFi.

**Comment by dinger1986** [comment]
seems stale @si458

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back
