### ISSUE TITLE
Removing desktop connection notifications on meshcentral.com

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#1008]
Unlike MeshCentral 1.0, MeshCentral 2.0 shows notifications when someone remotely connects. How can these be disabled so it's invisible like MeshCentral 1.0? We remotely connect to check whether someone is logged in and such notifications unnecessarily alarm users and cause unnecessary IT calls. We're using meshcentral.com.

**Comment by ryanblenis** [comment]
I can't find reference to him mentioning it, but I believe @Ylianst force-enabled that on meshcentral.com and you'd have to have your own instance running to disable it.

**Comment by FilGov** [comment]
That sucks, we unfortunately don't have resources for that. Thanks anyway for the explanation.

@Ylianst Could you please make this optional?

**Comment by Ylianst** [comment]
I remember responding to this on [Reddit](https://meshcentral.com) a few months back, I can't find the post right now. Anyway, sadly the privacy bar will not be made optional on [meshcentral.com](https://meshcentral.com). This is because people where abusing the server for not appropriate uses. It's somewhat expected that if you run a public free server like this, people will do crazy things with it that you should not do.

Can I ask why you need the notification bar disabled?

**Comment by FilGov** [comment]
Sure, like I said, because we use it to check if someone is logged in (before RDPing) and it unnecessarily alarms users and causes unnecessary IT calls, to the point we unfortunately had to stop using it.

**Comment by Ylianst** [comment]
Right, it seems like you should stop using the meshcentral.com public instance right away. If you are part of an IT department "getting unnecessary IT calls", you should be hosting your own server and not using a free public server with no service contract for business use. Also, while I do my best to host that server securely, it's likely in violation of most company security policy to use a free online server to manage your business PC's in this way.

**Comment by FilGov** [comment]
Don't understand what being part of an IT department or getting unnecessary IT calls has to do with that. It seems like you're incorrectly assuming we're a big business. We're not. I'm the only IT guy. I work remotely. We neither need nor can afford a service contract. It's not in violation of any internal company security policy. We're not using meshcentral.com to manage business PCs, only for the mentioned purpose and the occasional screen sharing. Thanks anyway for your concern.
