### ISSUE TITLE
Windows Terminal connects but does not open cmd.exe

### ISSUE THREAD

**Issue by rroseselavy42** [Ylianst/MeshCentral#1009]
I've been noticing this sporadically on a handful of windows agents and have continued to investigate. Any troubleshooting or debug steps that you suggest I would love to hear.

For some agents, especially I think laptops, Desktop connections works fine, as does files, but when connected via terminal it will "connect" but I won't get a command prompt. just a cursor with black screen.

**Comment by Ylianst** [comment]
Interesting. Note that older Windows versions have very different code for handling the terminal than latest Windows 10. So, checking on what version of Windows you see this problem will help. Also, any other hints would be of interest.

**Comment by ryanblenis** [comment]
I've seen this issue as well, however when in close proximity to the computer, I've noticed that it had just gone into sleep mode. Even though the agent was still accessible via the Console tab, any remote (desktop / terminal / files) tabs were unresponsive (while attempting to connect). This was most easily reproduced on a Surface when it is entering sleep. Looks like it keeps the network connection open for a bit, but not enough to wake it if a command is sent. Not sure if that is your case, but thought I'd mention it here.

**Comment by rroseselavy42** [comment]
I have seen that issue too but in this case I can get into desktop and files.


These are all Windows 10

**Comment by rroseselavy42** [comment]
Windows 10 Enterprise - 1809

**Comment by PathfinderNetworks** [comment]
> I've seen this issue as well, however when in close proximity to the computer, I've noticed that it had just gone into sleep mode. Even though the agent was still accessible via the Console tab, any remote (desktop / terminal / files) tabs were unresponsive (while attempting to connect). This was most easily reproduced on a Surface when it is entering sleep. Looks like it keeps the network connection open for a bit, but not enough to wake it if a command is sent. Not sure if that is your case, but thought I'd mention it here.

I've seen that exact same issue with Surface tablets as well.  It's very annoying.  It happens even if the tablet is physically connected to a Surface dock.  It will show as connected in MeshCentral but is completely inaccessible.  Essentially the same as if it's turned off.  I'm not blaming MeshCentral for that- just whatever Microsoft is doing with those things and the networking is very funky.

**Comment by unguzov** [comment]
I've seen this issue as well, terminal on some Windows machines just stops working (black screen).

**Comment by Ylianst** [comment]
Are any of you using plugin's on your servers? If so, which one. Thanks.
