### ISSUE TITLE
Permision on users

### ISSUE THREAD

**Issue by sdlopexvidri** [Ylianst/MeshCentral#101]
Hi, may I set permission to a user just to access desktop tab removing the terminal and files tab for the remote control option? I dont need the users access to this features of agents.

**Comment by Ylianst** [comment]
Ha yes. This is a good idea. Right now there is a "Remote Access" permission that does desktop/terminal/files. I need to separate that into 3 permissions. Not sure when I will get time to do that, but it's a good idea.

**Comment by sdlopexvidri** [comment]
Thanks Ylianst, we will be waiting for this feature of the software

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.9-h with support to remove the Terminal, Files and Intel AMT tabs. Let me know if it works for you.

![mc2-grouppermissions](https://user-images.githubusercontent.com/1319013/53458393-c57dd780-39ea-11e9-8931-6dd198c36723.png)

**Comment by sdlopexvidri** [comment]
HI YESSS it works for me, Thanks a lot Ylianst you are awesome

**Comment by Ylianst** [comment]
Your welcome. Thanks for posting this request, it was a good idea.

**Comment by D4V3M0NK** [comment]
I don't think this is working exactly as advertised. I've just set up a user with Remote View Only, No Terminal Access, No file Access to a group. When I log in with their account, I can connect in both **Terminal** and **Files** tabs.

**Comment by Ylianst** [comment]
Are you sure? I just re-tested and I don't see any issues. I did find and odd case that happens if the user was logged in while you remove and re-add the user with different permissions, but just fixed it. However, when you select "no terminal", I don't see the terminal show up. Any details to make the problem occur is appreciated.

**Comment by D4V3M0NK** [comment]
Not sure at all! Working like a charm (including having the user logged in as I'm changing permissions) - I will keep an eye on this though and report back if need be
