### ISSUE TITLE
Meshrouter error

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#1014]
Hello, i have installed MeshServer on Nas Synology, when i try to connect with RDP i get error from meshrouter "a call to SSPI  failed, see inner exeption" ...

any help?

thanks

**Comment by Ylianst** [comment]
Arg. Sorry, but your should have have to write up a better issue report with complete log, what Mesh Router are you using? What Windows version? What browser. As much details as you can. I will close this one. Open with more details when you can.
