### ISSUE TITLE
Miss Cira when restart meshcentral with old cira script

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1015]
Hello. Server with Lets Encrypt. I used the cira certificate of the old Lats encrypt https. After restarting the mesh center, all the cira disappeared, except for those that it added today.
How can I fix it, and also, will backup help?

Update:
After 15 minutes, at one point, Kira begins to appear.

**Comment by vyacheslav25** [comment]
If you have a "login: ?=secretkey" you can't download CIRA script.

**Comment by Ylianst** [comment]
Ok, I can fix the problem where the CIRA script is not loaded when key=??? is used. As for CIRA, one issue with Intel AMT is that if the server goes down for a while, the Intel AMT firmware will try a few times and then stop trying for a long itme. This is annoying since it may take a long time to get CIRA connections back.

**Comment by MailYouLater** [comment]
"... and then stop trying for a long time."  Like how long?

Can you set (e.g. with an mescript) how long AMT sleeps for before it wakes itself up to try for a CIRA connection again?  If not, this seems like a shortcoming of the Intel ME and/or AMT/vPro firmware which should be brought up with the appropriate team at Intel if possible.

**Comment by Ylianst** [comment]
So, the .mecscript will set the retry time to 10 seconds. In theory, Intel AMT should try to connect each 10 seconds and them stay connected, but I have noticed that it tries a few times and then gives up. I don't know the exact details, but there is no way to set the behavior in Intel AMT after the connection fails.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-f with improved 3FA support (loginkey). In this version, more page links will work and more pages are behind the lock and require the "&key=" to work.
