### ISSUE TITLE
Notification by MeshCentral after a computer comes back online

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1016]
It would be a nice feature of MC if when you have a computer selected (in other words you can see the General, Desktop, Terminal, Files, Events...) to have MC to notify you after you have rebooted it that the computer is back online again.

Not re-connect to the machine, but a notification only.

**Comment by PathfinderNetworks** [comment]
There is a feature that does this now.  If you go to My Account (where you see all your Device Groups) then click on the device group you want this to be active with.  Then click on Notifications.  The options are what you see in this image.  May nor may not do what you are wanting though.  This means all the devices in that group will alert you when they come online. I like it but it can get overwhelming at certain times of the day.  
![notifications](https://user-images.githubusercontent.com/48607498/76577292-392a3f80-649b-11ea-9c1d-d2e7d425f65c.JPG)

**Comment by CCWTech** [comment]
Thanks. That wouldn't work in our case as we may have as many as 1,000 computers in a group, but thank you for pointing that out for sure.



Please do not send a new request for help to this email, the response may be delayed. 

Need support? Please email mailto:support@ccwtech.com for a faster response.



Paying too much for phones? We now offer VOIP phone services.



Allen Crist, CEO

CCW Technology I.T. Services
Veterinary I.T. Specialists
Serving Small and Medium Business  since 2008

(801)410-0203 x5002


http://www.ccwtech.com

http://www.facebook.com/CCWTechnology




---- On Thu, 12 Mar 2020 17:54:18 -0600 Parrish Reinoehl <notifications@github.com> wrote ----




There is a feature that does this now.  If you go to My Account (where you see all your Device Groups) then click on the device group you want this to be active with.  Then click on Notifications.  The options are what you see in this image.  May nor may not do what you are wanting though.  This means all the devices in that group will alert you when they come online. I like it but it can get overwhelming at certain times of the day.
 https://user-images.githubusercontent.com/48607498/76577292-392a3f80-649b-11ea-9c1d-d2e7d425f65c.JPG

**Comment by Ylianst** [comment]
Just to be cleat about the request. You want a yellow popup (top right on the page) and "ding" sound when the computer connects and you are actively looking at it?

**Comment by si458** [comment]
this feature exists now
as displayed in the above picture you have options to display notifications in your browser PER DEVICE\PER GROUP
you can also now enable messaging notifications and get alerts by different methods (email, sms, pushover, discord, etc...)
