### ISSUE TITLE
Feature Request: Join with code

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1019]
I use MeshCentral for remote access with my MSP. It would be awesome to be able to have a join with a code feature for one time access for customers. For now I'm just using an unlimited invite link for the agent download.

**Comment by Ylianst** [comment]
Can you detail "Join with code". Is that for installing the agent or creating a new account on the server?

**Comment by asasin114** [comment]
For sure! I took this screenshot from the website of a company that uses ScreenConnect for some of their remote support and it asks you to enter a code which would be provided by an agent over the phone to allow the user to install the agent package for remote access. Hope that's enough info. I realize this is probably a pretty big task and am in no means in a rush for a solution. Just thought it would be a nice feature to have.
![Screenshot_20200314-222844](https://user-images.githubusercontent.com/417006/76695308-60237580-6643-11ea-9b5d-00918dd2a900.png)

**Comment by Ylianst** [comment]
Thanks, that is clear. For ScreenComnect, What does the code look like? Number of digits? Alpha-numeric?

**Comment by MordyT** [comment]
ScreenConnect allows you to set whatever code you want. So it could be 1, it could be 12345, abcdef, etc.

I've handled this personally by placing a mesh agent on a public webserver. Then I just tell people to go to xxx.company.com/agent.exe and open the downloaded file, click connect. The agent is in a separate group and I don't leave any perm agents installed in that group, so it's easy to see what device just connected.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.0-i with agent invite codes support. You will need update and add:

`"agentInviteCodes": true`

To the domain section of config.json and restart the server. Then, when you click on a device group, you will see an added feature to set the "agent invite codes". Let me know if that works for you.

![MC2-AgentInviteCodes](https://user-images.githubusercontent.com/1319013/76880778-69743400-6835-11ea-9015-eab7a71313ad.png)

**Comment by PathfinderNetworks** [comment]
I'm going to upgrade my server soon and give this a try.  One question, is this a one time install thing?  Meaning once I end the remote session with the user is the agent removed from their device?  In my use cases I would, most of the time, want to use this for one-off remote sessions.

**Comment by Ylianst** [comment]
It's not currently a one time code. I imagine I would need to remove the code then the agent actually connects back to the server, not just when the code is entered. Feedback on this and possibly changes are welcome.

**Comment by Ylianst** [comment]
Small hidden feature, you can add `?c=abc` to the invite URL to pre-fill the invitation code. For example: `https://server.domain.com/invite?c=abc`

**Comment by asasin114** [comment]
Fantastic! Thank you for getting this running so quickly!
