### ISSUE TITLE
How to setup the LDAP configuration in Meshcentral

### ISSUE THREAD

**Issue by praburaj1985** [Ylianst/MeshCentral#1020]
Hi,  
  This tool is good for me to use my testing environment am already tried the LDAP configuration which you mentioned the existing issue but its not work for me could you give me the steps to configure the LDAP configuration in MeshCentral

if you give me the instruction its very helpful for me.
Thanks in advance

**Comment by MordyT** [comment]
Add:
"Auth": "sspi",

in your config.json

But there is some serious 2FA issues with this. Namely, the fact that 2FA is completely bypassed. You can't see the option in the my account tab, and if you disable SSPI (which does allow you to see and setup 2FA) and then re-enable it, you never get prompted for it.

https://github.com/Ylianst/MeshCentral/issues/198 would be fantastic to resolve this.

**Comment by Ylianst** [comment]
This is connect. If MeshCentral is running on a Windows computer that is part of a domain, you can add `"Auth": "sspi"` to the domain section of the config.json. Note that this will disable user/pass login and disable all two-factor authentication. Basically, your domain authentication policies will apply. I would imagine one would add two factor authentication to the domain login, not to MeshCentral in this case. Let me know if that makes sense, feedback appreciated.

**Comment by MordyT** [comment]
@Ylianst 
But what about if you are accessing MC from outside the LAN? While the webpage does prompt for AD credentials and work correctly, the 2FA protection missing means someone could try to bruteforce it. The only way I would turn on SSPI is if it was LAN only in that case.

Which brings us back to https://github.com/Ylianst/MeshCentral/issues/198 for other types of authentication...

(regardless, I do want you to know we appreciate this tool)

**Comment by praburaj1985** [comment]
Thanks and sorry for the late reply let me try and let you know

**Comment by Ylianst** [comment]
You can configure a MeshCentral server to use an LDAP server for user authentication by adding the following to the domain section of the config.json (this is only an example):

```
      "auth": "ldap",
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "objectSid",
      "ldapOptions": {
        "url": "ldap://127.16.0.1:389",
        "bindDN": "CN=svc_meshcentral,CN=Users,DC=meshcentral,DC=local",
        "bindCredentials": "Password.1",
        "searchBase": "DC=meshcentral,DC=local",
        "searchFilter": "(sAMAccountName={{username}})"
      }
```

Since I have not used LDAP much, I would appreciate feedback on this. MeshCentral uses the "[ldapauth-fork](https://www.npmjs.com/package/ldapauth-fork)" module to do this. Look at that module for the proper options.

**Comment by gianlucaromito** [comment]
Hello. I got the LDAP auth working. Do someone know how to get the email address from LDAP? if I set it manually after anothe rlogin I get "Unset email (no more email in LDAP)" in the log.
Any help appreciated.
Gianluca

**Comment by capitangiaco** [comment]
once logged with ldap, I lost the device group.
I had to remove _"auth": "ldap",_ connect with old admin and add the (at least one time connected) ldap as admin of my device group.
