### ISSUE TITLE
Geolocation - Map doesn't show anything?

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1024]
I've enabled GeoLocation in the mesh config and now have a map button. However, my map is... just a map. I would have thought it would put dots some something for each agent that is checking in, but maybe I'm misunderstanding.

I've reviewed the documents and don't see a lot of information on this feature.

**Comment by Ylianst** [comment]
A while back, there are a different group in my organization that was very interested in geolocation of devices and had a developer work on this. But the stopped working on it a long time ago and so, I put the default to "false" on that feature. Also, there are some rules on location tracking in some countries, so you also need to be sensitive to this.

Anyway, the idea what to have up the server store up to four different locations for each device (GPS, WIFI, IP, Manual) and the map would show the best resolution and/or latest position of each device. I never implemented GPS or WIFI. There is a way to use a online service to reverse lookup the position of an IP address or manually place the device on the map. The pin would change color depending on device power state.

Right now, the entire geolocation feature is on hold. There are just too many things to work on, I can't really keep up. At some point int he future, would be fun to look at this again.

**Comment by MordyT** [comment]
Thanks, I'll disable it for now and watch the commits.

**Comment by JSuenram** [comment]
Any update on this? Would be a nice usable feature when managing multiple customers on different sites and cities or even HomeOffice users....
