### ISSUE TITLE
untranslated strings

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1025]
I found some untranslated strings.

![translation-3](https://user-images.githubusercontent.com/58996467/76711004-44d06d00-670c-11ea-8b6b-ca5b4f0639ba.jpg)
![translation-2](https://user-images.githubusercontent.com/58996467/76711005-45690380-670c-11ea-87d1-f00bda9c31eb.jpg)
![translation](https://user-images.githubusercontent.com/58996467/76711006-46019a00-670c-11ea-80c1-98f8dc5d81d1.jpg)

greets and thx for the nice software

**Comment by Ylianst** [comment]
Thanks for the report! I will fix that.

**Comment by Ylianst** [comment]
Just checked-in a fix for this. Will be published in the next release.

**Comment by petervanv** [comment]
created new merge with translation

**Comment by Ylianst** [comment]
Wow, you are so fast! Thank you.

**Comment by petervanv** [comment]
fixed
