### ISSUE TITLE
Half Cira PC is not working

### ISSUE THREAD

**Issue by trenton92** [Ylianst/MeshCentral#1026]
Hey. In one group, half of AMT stopped working. Throws an authorization error. But I definitely enter the correct password. If you select a TLS, it gives a time error.
![image](https://user-images.githubusercontent.com/61736438/76749906-f95aa500-6785-11ea-8c4e-316a3ca9dfb8.png)

**Comment by ryanblenis** [comment]
Hi @trenton92,

Before Ylian sees this, it will probably be immensely helpful to him to have a copy of the exact errors you're seeing here instead of just "a time error."

**Comment by trenton92** [comment]
When I try to connect to a non-working machine



MPSCMD: CHANNEL_OPEN_CONFIRMATION 9 5 499
WEBRELAY: Relay CIRA state change 2
MPSCMD: CHANNEL_WINDOW_ADJUST 9 499 499
MPSCMD: CHANNEL_WINDOW_ADJUST 9 499 499
MPSCMDDATA: CHANNEL_DATA 9 770
WEBRELAYDATA: Relay CIRA data 770
MPSCMDDATA: CHANNEL_DATA 9 167
WEBRELAYDATA: Relay CIRA data 167
MPSCMD: CHANNEL_CLOSE 9
WEBRELAY: Relay CIRA state change 0
WEBRELAY: Websocket relay closed.
MPSCMD: KEEPALIVE_REQUEST
MPSCMD: KEEPALIVE_REQUEST
MPS: New CIRA connection
MPSCMD: PROTOCOLVERSION 1 0 44b3d470-afdb-11e5-be66-1e7a66911400
MPSCMD: SERVICE_REQUEST auth@amt.intel.com
MPSCMD: USERAUTH_REQUEST user=iTXYo1GEaP3ryPwh, service=pfwd@amt.intel.com, method=password, password=A@xew9rt
CIRA connection for unknown node. groupid: mesh//iT$Yo1GEaP3ryPwhoUO@2G29mF3wRA02q3fpWQ@NdE9SntqlXEjiGmTQo4o2EZaG, uuid: 44b3d470-afdb-11e5-be66-1e7a66911400
MPS: CIRA connection closed
MPSCMD: KEEPALIVE_REQUEST
MPSCMD: KEEPALIVE_REQUEST
MPSCMD: KEEPALIVE_REQUEST
MPSCMD: KEEPALIVE_REQUEST

**Comment by petervanv** [comment]
please remove the password, and change it soon in your setup

**Comment by trenton92** [comment]
Done. But it didn’t help. For other PCs that also have a saved password, everything works.

**Comment by ryanblenis** [comment]
Hi @trenton92,

I believe @petervanv was referring to your password being in the log you posted. Not on the machine itself.

**Comment by trenton92** [comment]
If I understand correctly, then delete the saved password here?

![image](https://user-images.githubusercontent.com/61736438/76761035-590d7c00-6797-11ea-917c-180381314528.png)

**Comment by petervanv** [comment]
![login](https://user-images.githubusercontent.com/58996467/76761568-f2d12b00-678f-11ea-944a-143d7ba8885d.jpg)

**Comment by petervanv** [comment]
you can publish your error log, but do not expose your credentials (red circled line at screenshot above).

**Comment by trenton92** [comment]
sorry. very stupid. I just did not master amt very much. Does the password change in the config or on the PC itself?
thank you very much for your help

**Comment by petervanv** [comment]
i am not using amt, so i cant aswer your question, sorry

**Comment by vyacheslav25** [comment]
Another user has encountered this problem.

https://www.reddit.com/r/MeshCentral/comments/fddflj/intelamtconnect_authentication_error/
