### ISSUE TITLE
DB Trimming option...

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1027]
Hi @Ylianst & Team,

So I am wondering if there is a way that we can setup parameters for selecting fields that can keep the db trimmed to a smaller size... I ask this, because one of my customers just launched 400 Nodes overnight and they are all setting themselves up for the remote work kind of action... I went from soft 400 nodes to over 1500 overnight... I see this growing very quickly and my DB instance growing exponentially over the next few weeks... My user base is doing very similar... 

Some of the data I look to dump is the systems that do a power cycling of 100+ iterations over a span of 4 hours... If the system is doing that many failures a single log is all that would be needed after a continuous 20 resets...

**Comment by Ylianst** [comment]
In the settings section of config.json you can add this:

```
    "DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    }
```

This is the time in seconds to keep event records in the database. You can change this as you will, the values above are the defaults if you don't set anything. You can try settings these numbers lower is you need more space.

This said, MeshCentral.com has many times that many devices using MongoDB and as long as you have disk space, you should be fine.

**Comment by Ylianst** [comment]
Going to close this open. Please re-open if needed.
