### ISSUE TITLE
certurl settings problem: Failed to load web certificate at <...>

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1031]
Dear all,

I hope someone can help to solve my problem regarding meshcentral or at least help me to find where are my mistakes. So here is the story:

My MeschCentral is in hybrid mode, and I have an IIS reverse proxy with let's encrypt configured on it, I first tried to use MeshCentral with --TLSoffload, but even if everything looks OK (mesh server detect the agent through the IIS) they still cannot communicate each other (my last investigations conclude to a header problem in my reverse proxy but I don't know exactly how to fix it ). So after searching, reading and testing a lot, i finally give up the reverse proxy mode with mesh central.

A solution is to replace IIS by NGINX and I assume following instructions from Ylian's tuto will correct the problem but I can't replace the IIS yet (especially if I misconfigured something).

So here is my problem where i need help from the community: When i enable "certurl"setting  in the config.json, a new line appear on the console and tell me this :
Failed to load web certificate at: "https://127.0.0.1:443", host: "<mydomainname>"
From my understanding of this setting, MeshCentral will reuse the same certificate used to my reverse proxy, but i don't know why it fail.

Finally, as a workaround,  I read from the user guide, with the normal TLS supported of mesh and by replacing root certificates generated by MeshCentral i can also solve the problem? but i'm not sure about the process to do, should I just extract the .crt and .key from the .pfx file then replace all certificates in the .\MeshCentral\meshcentral-data? or it is a bit more complicated. currently windows won't let me extract the .key file.

So if someone has ideas about what am  I missed? Right now with this configuration I can use meshcentral and agents to connect well now, but if i want to use the chat function for example it will display the error.

Thank you in advance for your help and this app rocks!
Best regards,
Frederic

PS: Just in case, I'm based in china but i don't think it is relevant for the problem as it is purely internal

**Comment by Ylianst** [comment]
Hi Frederic. You are correct that MeshCentral does not connect to the Internet and so, should work anywhere in the world and should work even without Internet access (as long as you can download the files from NPM).

For IIS, we have had reports that headers would be lower cased by IIS when forwarded. This would break MeshCentral. To fix this, try to adding `"CookieEncoding": "hex"` to the settings section of the config.json.

To get started, add the following to the "settings" section of the config.json:

```
    "Cert": "myserver.domain.com",
    "CookieIpCheck": false,
    "CookieEncoding": "hex",
    "IgnoreAgentHashCheck": true
```

The "IgnoreAgentHashCheck" setting is not good for security, but it is helpful to debug. With "IgnoreAgentHashCheck", you do not need "certurl", so you can comment that out for now and see if everything else works.

Make sure you have the "cert" setting with the DNS name that will be used externally by the agents to connect to the server. Also, I do not recommend you change any of the certificates in "meshcentral-data", instead make sure you set the right "cert" name and try the settings above. Once that works, you need to try to remove "IgnoreAgentHashCheck" and replace it with "certurl"

Hope this helps,
Ylian

**Comment by Fred1984** [comment]
Hello Ylian,

I'm sorry for the late reply. About the issue, to make it simple, the added line did not solve the certurl issue mentioned above and even with the TLSoffload enabled i'm still not able to make the agent work. I think a brick is missing on my understanding of Meshcentral regarding the certificate. 

to summary the situation:

- when using Tlsoffload -> certificate working on browser but no the agents connect on the server
- when not using Tlsoffload-> certificate warning on browser but agent works.

and in both case i have the error below showing on the startup lines
Failed to load web certificate at: "https://myserver.domain.com", host: "myserver.domain.com"

hope you have another great idea? 👍

**Comment by Ylianst** [comment]
When you say "the added line did not solve the certurl issue", can you tell me what line you tried? You should add all 3 lines:

```
    "CookieIpCheck": false,
    "CookieEncoding": "hex",
    "IgnoreAgentHashCheck": true
```

Let me know what you see after you all these. Thanks.

**Comment by Fred1984** [comment]
hello Ylian, 

sorry for my bad english, i meant : After added the line**S** you suggested me, it did not solve the error message i have at the startup phase. Below is the startup report from the console (i changed the domain name as well) without the -TLSoffload anabled.

c:\Program Files\Open Source\MeshCentral\node_modules>node meshcentral --debug
WARNING: Agent hash checking is being skipped, this is unsafe.
MAIN: Core module windows-amt is 384371 bytes.
MAIN: Core module linux-amt is 355553 bytes.
MAIN: Core module linux-noamt is 263190 bytes.
MAIN: Core module windows-recovery is 44864 bytes.
MAIN: Core module linux-recovery is 26595 bytes.
MAIN: Core module windows-agentrecovery is 24634 bytes.
MAIN: Core module linux-agentrecovery is 6365 bytes.
MeshCentral HTTP redirection server running on port 81.
MeshCentral v0.5.0-h, Hybrid (LAN + WAN) mode.
Failed to load web certificate at: "https://myserver.domain.com/", host: "myserver.domain.com"
DISPATCH: DispatchEvent [ '*' ]
MAIN: Server started
MeshCentral Intel(R) AMT server running on myserver.domain.com:4433.
MeshCentral HTTPS server running on myserver.domain.com:444.

Thanks, 
Frederic

**Comment by Fred1984** [comment]
ok... so after work on it again i found the issue regarding the certurl issue... so either i'm suffering from dyslexia, either i'm dumb: I mis-typed the domain name....... 

so fixing this error did not help the problem and he can get the certificate from the IIS but it is still detecting the server certificate as unverified.

Also the -offload mode as so far i have the most secure now this feedback (with your recommendations settings enabled):

c:\Program Files\Open Source\MeshCentral\node_modules>node meshcentral
WARNING: Agent hash checking is being skipped, this is unsafe.
MeshCentral HTTP redirection server running on port 81.
MeshCentral v0.5.0-w, Hybrid (LAN + WAN) mode.
Loaded web certificate from "https://myserver.domain.com/", host: "myserver.domain.com"
  SHA384 cert hash: *hash numbers*
  SHA384 key hash: *hash numbers*
MeshCentral Intel(R) AMT server running on myserver.domain.com:4433.
MeshCentral HTTP server running on port 444, alias port 443.

But when i check the logs, i see my requests coming from ::1, but when i disable TLSOffload, i receive the correct agent IP. So it seems something wrong with the IIS Proxy server who maybe not forwarding the correct headers:
4:29:51 PM - webrequest: (::1) /agent.ashx/.websocket
4:29:55 PM - webrequest: (::1) /agent.ashx/.websocket
4:29:59 PM - webrequest: (::1) /agent.ashx/.websocket
4:30:04 PM - webrequest: (::1) /agent.ashx/.websocket
4:30:12 PM - webrequest: (::1) /agent.ashx/.websocket
4:30:22 PM - webrequest: (::1) /agent.ashx/.websocket
4:30:39 PM - webrequest: (::1) /agent.ashx/.websocket
4:31:01 PM - webrequest: (::1) /agent.ashx/.websocket
4:31:44 PM - webrequest: (::1) /agent.ashx/.websocket
4:32:51 PM - webrequest: (::1) /agent.ashx/.websocket
4:34:40 PM - webrequest: (::1) /agent.ashx/.websocket
4:37:58 PM - webrequest: (::1) /agent.ashx/.websocket
4:41:43 PM - webrequest: (::1) /agent.ashx/.websocket
4:47:20 PM - webrequest: (::1) /agent.ashx/.websocket

Except if you wish i keep it open, i think i will close this case and create another case with the clear detail.
