### ISSUE TITLE
Manage User does not allowed Password Reset / Delete

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1033]
Setting a user like so:

![image](https://user-images.githubusercontent.com/779947/76892823-478ca880-6859-11ea-9f82-cc930495caa1.png)

The user is not able to reset passwords or delete other accounts. Only create and change permissions.

![image](https://user-images.githubusercontent.com/779947/76892952-7d319180-6859-11ea-8c9b-c943603fd37b.png)
(it should be like this:)
![image](https://user-images.githubusercontent.com/779947/76893116-cd105880-6859-11ea-9c88-21c191678890.png)

I'd also ask that we be careful to not allow a manager to reset an administrator password...
![image](https://user-images.githubusercontent.com/779947/76893022-a520f500-6859-11ea-944e-2b41bf611875.png)

**Comment by Ylianst** [comment]
Ok, I can look into this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-j with a fix for this. User Manager can now change user passwords except for full administrators. Let me know if it works.

**Comment by MordyT** [comment]
Perfect. Change password now shows. What about delete user?

**Comment by Ylianst** [comment]
Oh right... Published MeshCentral v0.5.0-k with a fix for this. Should now show up the same way as "change password". Let me know if it works.

**Comment by MordyT** [comment]
Perfect!
