### ISSUE TITLE
Typo in default config.json

### ISSUE THREAD

**Issue by iserlohn** [Ylianst/MeshCentral#1039]
After installing and running MeshCentral via NPM, the auto-generated config file has the following typo -

```
    "_agentInviteCodes": true
    "_WebRTC": false,
```
A comma is missing on the "_agentInviteCodes" line as shown above (line 30).

This leads to the following error when starting MeshCentral again -

ERROR: Unable to parse /home/x/meshcentral/meshcentral-data/config.json.

**Comment by Ylianst** [comment]
Rushing a new release now!

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-m with this fixed and new Dutch translations.

**Comment by iserlohn** [comment]
Thanks, seems to be good now.
