### ISSUE TITLE
WSMAN Parsing Error AMT v9.1.41

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#104]
On version v9.1.41 in Beta 2 when trying to connect to AMT CIRA connected computer it begins to load and then gives WSMAN parsing error.

**Comment by datapharmer** [comment]
I successfully loaded this client once, but I typically get the WSMAN parsing error, "Unable to parse HTTP response header" or Timeout error. There do not appear to be any actual network issues that would prevent a connection (ping to this host is consistently 1ms or less)

**Comment by datapharmer** [comment]
Best as I can tell this appears to be a duplicate of Issue #100 so I'll close this until that is resolved at least.

**Comment by felixbouleau** [comment]
For posterity, in case someone else runs into this: The latest Docker version as of today will also report "WSMAN Parsing Error" when the wrong password is given.
