### ISSUE TITLE
MeshCentralRouter for MacOS and Linux

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1042]
Hi Ylianst and Team . MeshcentralRouter is an incredibly convenient program. Is it worth the wait on MacOS and Linux? And did someone try to open it with Wine?

**Comment by baikal** [comment]
MeshCmd can do most of it as well - on any supported platform.

- commandline + configfile instead of GUI
- therefor scriptable
- did not work with 2FA last time i checked

**Comment by Ylianst** [comment]
@baikal is correct. No graphical MeshCentral Router for Linux and MacOS, however, MeshCmd is a command line tool that can do the same on all platforms.

**Comment by uldiseihenbergs** [comment]
@baikal how about RouterPlus plugin? but i think, it must be in the base of Meshcentral web UI.

**Comment by baikal** [comment]
@uldiseihenbergs I do not understand what you ask me.
RoutePlus is a Meshcentral plugin - afaik it allows to do similar routing. As it is completely in the web UI, it is no question Windows vs Linux or Mac and I guess, any supported 2FA would work.
iirc, the port on the "local" side is assigned randomly and can not be chosen and there is no relay mapping (target is another machine than the "remote" node, but reachable from there) implemented.

**Comment by uldiseihenbergs** [comment]
@baikal it was just a suggestion. i'm at linux desktop, so win version of meshrouter is not working for me(tested with wine too). so, with all you mentioned features it must be part of web UI i think..

**Comment by baikal** [comment]
@uldiseihenbergs yes, with RoutePlus (https://github.com/ryanblenis/MeshCentral-RoutePlus) all the GUI is in the web UI of MeshCentral (MyAccount --> RoutePlus). No other software on you local machine needed other than it be a registered node (running MeshAgent) to your MeshCentral instance.

Being a commandline/scripting person, i still prefer the MeshCmd way on my Linux workstation ... especially now it support 2FA other than USB-Keys ( #1095, #479)

**Comment by ryanblenis** [comment]
> @uldiseihenbergs I do not understand what you ask me.
> RoutePlus is a Meshcentral plugin - afaik it allows to do similar routing. As it is completely in the web UI, it is no question Windows vs Linux or Mac and I guess, any supported 2FA would work.
> iirc, the port on the "local" side is assigned randomly and can not be chosen and there is no relay mapping (target is another machine than the "remote" node, but reachable from there) implemented.

Just to update anyone else reading through: RoutePlus has been updated to support static port assignments as well as remote node/network forwarding/tunneling. Cheers!
