### ISSUE TITLE
Can't change titles

### ISSUE THREAD

**Issue by BillBardon** [Ylianst/MeshCentral#1043]
Running server 0.5.0-m on a Devuan VM. No matter what I put in the title fields, MeshCentral 2.0 is what displays. The best I've been able to do is display my titlepicture _under_ the MeshCentral text (MC text overlapping the image.) 

Here is what I currently have in my config.json:

"_domains": {
    "": {
      "title": "CA-ACCESS",
      "title1": "CA-ACCESS",
      "title2": "Remote Control",
      "_titlePicture": "",

With that config, and having restarted the server and cleared my browser cache, I still see MeshCentral 2.0.

**Comment by jsastriawan** [comment]
How about changing '_domain' to 'domain'?

**Comment by BillBardon** [comment]
Ah, that affects everything within it, of course. Thanks for the tip.
