### ISSUE TITLE
2FA Help

### ISSUE THREAD

**Issue by dmacf10** [Ylianst/MeshCentral#1045]
I Lost the phone that I was using for 2FA login to MeshCental. I have backup codes but I'm not seeing any documentation on how to go about using them to login to get 2FA set up on my new phone. Any help would be appreciated.

**Comment by Ylianst** [comment]
Just login using your username and password and when prompted for a login token, enter one of the backup codes at the same place you would normally put the 6 digit code from your phone. Once logged in, you can go to "My Account" and click "Manage Authentication App" to disable it and again to re-enable it on a now phone.

Let me know if it worked.

**Comment by dmacf10** [comment]
That worked, and now I feel dumb for not trying that! Thank you so much!
