### ISSUE TITLE
One-click. RDP fails to find required files.

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1047]
Hi, 
I'm desperately trying to get One-click RDP to work.  I've installed the plugin info Chrome, but whenever I click on the link I get the following error message:
"Cannot download the application.  The application is missing required files.  Contact application vendor for assistance."

Please help!
Thanks!

**Comment by tradexsrl** [comment]
same here with latest meshcentral server installed. tried on windows 10 v1909 and windows 7

**Comment by tradexsrl** [comment]
these are the error log:
	* [20/03/2020 14:35:46] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Aree di protezione non corrispondenti per la distribuzione e l'applicazione.
		- Origine: System.Deployment
		- Analisi dello stack:
			in System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			in System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			in System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
			in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			in System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			in System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by Ylianst** [comment]
I am guessing this is because the MeshCentral click once application is not signed by an official code signing certificate since it's open source software. Your computer policy may require that the ClickOnce application be signed. If you have a code signing certificate, you could re-sign the ClickOnce application.

One alternative is you use the MeshCentral Router instead. You can also try a different browser with a add-in for ClickOnce.

**Comment by tradexsrl** [comment]
tried internet explorer 11 with www.meshcentral.com and it doesn't work also...when i click on rdp first time i need to enable popup for this domain , done , second time i click i get a quick refresh and nothing...

**Comment by tradexsrl** [comment]
tried on another pc with windows 10 v1909 but i get this:
![Cattura](https://user-images.githubusercontent.com/62424179/77208382-f94b0400-6afb-11ea-9ffb-7864756ff1b6.JPG)

**Comment by Ylianst** [comment]
I am not sure how long ClickOnce is going to be supported in the future. You should try MeshCentral Router, I just published a much better version and you don't risk running into as many issues.

![x](https://user-images.githubusercontent.com/1319013/77239705-0b2fb400-6b9b-11ea-99b2-65e851954a20.png)

**Comment by trentdavis** [comment]
My issue with mesh Router is that is doesn't save the mappings that I
setup.  It's a pain to setup the same mappings each time, and I don't want
to save my password in a script.

Does the new version fix this?

**Comment by Ylianst** [comment]
It sort of fixes that by allowing one click RDP sessions to any device. It's been [announced on Twitter](https://twitter.com/MeshCentral). Let me know what you think.

![MC2-MeshRouter](https://user-images.githubusercontent.com/1319013/77244239-13eead00-6bd0-11ea-885e-24ab9fde57fc.png)

**Comment by tradexsrl** [comment]
one question: when you say you have just published a new version of meshcentral router (or any other component like agent and so on) , automatically are pushed as a new version of meshcentral server or do we need to manually download from github and change the file in the server?

**Comment by Ylianst** [comment]
If you run your own MeshCentral server, you can login as administrator and in the "My Server" tab, click "Check server version". It will propose to auto-update if a new version is available.

**Comment by trentdavis** [comment]
This new feature works well, and now that I have SSL up & running, one-click also works perfectly!!
