### ISSUE TITLE
mesh agent delete by antivirus

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1048]
good morning , just installed meshcentral and tried to download the agent on my windows 10 v1909 but my symantec antivirus keep delete...tried to disable with no luck , even defender with disabled file and smartscreen control keeps delete it...

**Comment by tradexsrl** [comment]
found an old tread about this problem: renamed the -signed.exe in .exe and manually downloaded and installed but my pc doesn't show up in meshcentral.
if i run it again i see this:
![immagine](https://user-images.githubusercontent.com/62424179/77158917-8e221300-6aa4-11ea-805e-f2ccaf943a52.png)
with no data on server location...
also when i download the mesh agent via meshcentral i see the file name end with -portatili.exe which portatili is the name of the mesh group but if i search inside the meshcentral server i'm not able to find it...i don't understand if this is a packaged version with server info or not.

**Comment by Ylianst** [comment]
When you download the MeshAgent.exe from MeshCentral, it will modify the executable to add connection information to it. So, if you go in the /agents folder and take the agent from there, it does not have any connection information and so, you see the screen above.

Note that when you download the agent, you can run `meshagent.exe -help`, or `meshagent.exe -fullinstall`.

**Comment by tradexsrl** [comment]
i suspect the problem also arise because the meshcentral server installation do not went to end and do not appear the windows for the parameter.now with meshcentral setup correctly if i download the agent i get this:
![immagine](https://user-images.githubusercontent.com/62424179/77202449-aae33880-6aee-11ea-83a7-c575d72d80cd.png)
with all parameters

**Comment by tradexsrl** [comment]
strange...on another windows 10 with symantec disable and defender disable it keeps delete the files after allow smart screen control to exceute it
now in the agent folder in the server there is no more any meshagent.exe or the -signed x64 bit or x86 bit agent...i don't understand where meshcentral get the one i download

**Comment by trentdavis** [comment]
Is there a way to stop Windows smart screen from blocking the agent?  It's kinda tacky to tell clients to just ignore and install anyway, which is what I'm currently forced to do.

**Comment by krayon007** [comment]
I've been trying to figure that out. It's caused by their automated ai thinking it's malware. I tried signing it with an official cert, but then their automated reporting just caused our signing cert to get revoked.
