### ISSUE TITLE
communication port of meshagent

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1049]
Hi , what port use meshagent?
they are related to 80 or 81 of meshcentral server? because i need to change 80 to 82 or something elese since i have no more resource on our firewall

**Comment by krayon007** [comment]
The agent does not have any listening ports. It only makes outbound connections to the server.

**Comment by tradexsrl** [comment]
ok but what about the port for outbound connection ?



Da:     "Bryan Roe" <notifications@github.com>
Per:    "Ylianst/MeshCentral" <MeshCentral@noreply.github.com>
Cc:     "tradexsrl" <marco.zaro@tradexsrl.com>, "Author" 
<author@noreply.github.com>
Data:   20/03/2020 16:05
Oggetto:        [Marketing Mail] Re: [Ylianst/MeshCentral] communication 
port of meshagent (#1049)



The agent does not have any listening ports. It only makes outbound 
connections to the server.
?

**Comment by tradexsrl** [comment]
ok but what about the port for outbound connection ?
i mean if the server in behind a firewall and laptop are outside connected via internet ?
i know amt have 4433 port if i'm right 
but the agent in OS?

**Comment by Ylianst** [comment]
As Bryan indicated, the MeshAgent has no inbound ports. By default the MeshCentral will listen to ports 80, 443 and 4433. The usage of the ports are as follows:

- Port 80 is HTTP and mostly redirects users to HTTPS port 443. This port is also used when MeshCentral is requesting a certificate from Let's Encrypt.
- Port 443 is HTTPS. All agents and users (browsers) connect to this port. It is used for almost everything.
- Port 4433 is Intel Active Management Technology (Intel AMT) server port. This is used for Intel AMT to connect to the server, if you don't use Intel AMT, you don't need this port.

The only port you really need is port 443. Hope this helps.

**Comment by tradexsrl** [comment]
yes that is what i needed.
now i know that also agent connect on 443
one question related to AMT: implementation of this is left to the manufacturer or if i have for example intel 8th gen cpu i must have AMT?
i'm asking this because we have all Lenovo Thinkpad Txx - X-series and X1 series and in my t480 or another t490s i'm not able to enter the amt configuration by pressing CTRL+P.
in the bios there is no trace of intel AMT and when i press CTRL+P i see very quickly enter sme or smb configuration but then it start windows 10
i have tried to disable uefi bios but no luck...only in lenovo desktop m920q i'm able to enter amt configuration but as already written i cannot upload meshcommander firmware because it report back there is not enough space

**Comment by Ylianst** [comment]
As a general rule, if it has a Intel vPro sticker on it, it will have Intel AMT in it. For other models, you need the check.

**Comment by tradexsrl** [comment]
on all laptop there is no vpro sticker even they are very new...i tried to donwload meshcmd and run it via cmd with amtinfo and i see this:
![immagine](https://user-images.githubusercontent.com/62424179/77223649-d271e980-6b5e-11ea-80fd-d4f90de86e26.png)

**Comment by tradexsrl** [comment]
also there is no sticker of vpro on lenovo m920q but amt is present and activable...too bad...seems intel amt is doomed so all the beautifull stuff you can do with amt is no more possible on these laptop...on internet i found many forum that tells to disable completely amt because intel declare is bugged and add a layer of attack....https://support.lenovo.com/us/en/solutions/len-19568

**Comment by Ylianst** [comment]
Intel AMT is a hardware based management agent, like all software, please make sure to update it regularly by updating your system's firmware. Also, if you are concerned about security, I do highly recommend using CIRA (Client Initiated Remote Access) where Intel AMT connects to the server and there is no in-bound TCP ports. In that case, the attack surface is very low. Hope that helps.
