### ISSUE TITLE
windows installer problem

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1050]
hi just installed the latest meshcentral downloaded from website on a brand new windows 10 v1909 that has no antivirus.
installation went well but the installer at the end (it seems) do not show the next button or the finish button , only back and next button greyed and  a message say windows service installed.i click on the x in the upper right corner and found the service is not running,started and everythings seems well but i don't know if all other problem already written are related to this strange behaviour..please let me know

**Comment by Ylianst** [comment]
Hi. Can you provide a screen shot of the issue? Thanks.

**Comment by Ylianst** [comment]
Also note that if you are a professional and know about NodeJS and NPM, I recommend you install MeshCentral using the manual "npm install meshcentral" process. The MeshCentral Windows Installer will install NodeJS and type all the commands for you, but for most experts it's best to do it manually to have better control over the process and configuration.

**Comment by tradexsrl** [comment]
found the problem: when i rerun the installer i select reinstall but it fails , then i select unistall and now i double check to run as administrator.
now the process end , a message say service started and appear a windows enabling me to configure various option of the server
