### ISSUE TITLE
Translation chinese in Json

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1054]
was this intended to be this way, the translation out of the normal place ?
![translation-5](https://user-images.githubusercontent.com/58996467/77257710-5f5b9680-6c76-11ea-9f5d-9bc714cbcb07.jpg)

if not, i can / wil fix the location for you at th standart location, please let me know

**Comment by Ylianst** [comment]
I need to fix this. The Windows Resource Translator tool saves the file with "xloc" at the end, but translate.js does not. I will fix it and put "xloc" at the end.

**Comment by Ylianst** [comment]
Just checked in the fox for this in GitHub. Will be in the next MeshCenral release in a few hours.

**Comment by petervanv** [comment]
the translate.json seems to be to big to show online, is that file size also fixable or is it github ?

**Comment by Ylianst** [comment]
This is a GitHub thing, I can't do anything about that. You can click "view raw" and it will show you the file correctly, but not within the GitHub web page.

**Comment by petervanv** [comment]
oke, clear. looked into the file. confirmed fix (ps is there an label "confirmed fix" ?instead of fixed please confirm when its fixed ?

**Comment by Ylianst** [comment]
When you confirm it's fixed, just close the issue :) Thanks.
