### ISSUE TITLE
ref #920 let's encrypt problem

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1057]
just came across this post because i'm also facing problema getting LE cert.
i have server 0.50-s version installed on windows machine , i register my domain in dns this morning and tested yesterday port443 , unfortunately we have runout of port 80 so we need to use 8080 to redirect to 443.
i have inserted LE parameters inside the json config file and at server restart i get the same warning , so i change dns to 8.8.8.8 and restart MC server , now the warning is gone but no file inside the LE dir in thse server. the nocheck parameter is needed or the problem is in the port 8080? if it's in the port how can i solve the problem without port 80?

**Comment by Ylianst** [comment]
So, Let's Encrypt will contact your server on port 80 and there is no way to change this. You must prove to Let's Encrypt that you control port 80 on a given DNS name. If you are just using MeshCentral privately, you could just load the self-signed root certificate of your MeshCentral server into your browser. Another option is to be a reverse proxy like NGINX. - Hope that helps.

**Comment by tradexsrl** [comment]
LE server will contact my server on port 80 just the first time to prove it?
or everytime there is a renew?
because if it is one time only i can free one port 80 just for the check and then come back to 8080.
i should use a CA certificate because in my experience users will halt if they see that error and call IT support everytime

**Comment by Ylianst** [comment]
Port 80 is required each time, not just the first time. Your best solution is probably to setup a reverse proxy.

**Comment by tradexsrl** [comment]
last question: if in the future i will change port of MC back to 80 i need to redeploy the agent?

**Comment by tradexsrl** [comment]
forgot to ask also if i could use this trick: we have two internet connection handled by a firewall , one is fiber and one is wireless (way less bandwidth than fiber) , maybe on the second line i could have port 80 free.
if i setup http access of my domain on one ip of the wireless connection then i redirect to https on one ip of the fiber connection?
ip classes are completely different since the provider are different...could this trick do the work or there will be problem?

**Comment by Ylianst** [comment]
The agent connects to HTTPS port 443. That agent does not use port 80 and so, not affected.

As for any other tricks, you can look at Let's Encrypt forums for that.

**Comment by tradexsrl** [comment]
i saw in LE website they also use dns check by creating a TXT record.
if i enable LE in MC as you explained in a tutorial , LE will use dns check or not ?

**Comment by Ylianst** [comment]
MeshCentral's built-in Let's Encrypt system currently only supports HTTP port 80 validation. I could look into the DNS check. This said, if you have a reverse proxy in front of MeshCentral, you can do all sorts of things including have the reverse proxy perform getting the Let's Encrypt certificate and renewing it. MeshCentral would not perform this work anymore and just have the reverse proxy do the TLS and certificates.
