### ISSUE TITLE
Add expiration option to email invite feature

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1058]
hi would be nice to have the possibility to directly send the link inviation with link expiration from the server by mail with the possibility to add a simple note for the user.
now the link expiration needs to be copied and then mailed by creating a new mail from your pc
the email invitation haven't the link expiration feature...

**Comment by petervanv** [comment]
![invite_mail](https://user-images.githubusercontent.com/58996467/77344723-e02c9800-6d33-11ea-94d1-e46c2ddb1521.jpg)

**Comment by tradexsrl** [comment]
i know it but there is no link expiration option....

**Comment by petervanv** [comment]
oh that way, that needs to with hand at the moment, maybe an possible option to add

**Comment by Ylianst** [comment]
Good ask. The email invite system was built before the limited time invite link. I need to add that.

**Comment by Ylianst** [comment]
Looking into this, if in the operating system you select "Send invitation link", it will show the link expiration box. Let me know if this works for you.

![x](https://user-images.githubusercontent.com/1319013/78414203-df1b2680-75cf-11ea-8534-0a10c7c26e5a.png)

**Comment by tradexsrl** [comment]
yes it works.
only one question related to security from end user perspective: if i send this link invitation to a customer to help remotely (i have created a group dedicated only for this scope) , if they click on install and not on connect , i can have access to their pc all the time as long as pc is power on and connected to internet...that is not so good...will be possible , only for link expiration option , to have only the connect button in the agent downloaded?
in that group i have setup auto delete device after disconnection.

**Comment by vitko-bg** [comment]
Change installation type Interactive, so client won't have an option to install, there will be only Connect option

**Comment by tradexsrl** [comment]
ah yes , forgot it.
thank's.
