### ISSUE TITLE
problem with group rights

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1062]
hi , i have MC 0.5.0-s , i have created user and added to one group with this parameters setup:
![immagine](https://user-images.githubusercontent.com/62424179/77468668-3110bf00-6e0e-11ea-95b9-3cab9ff08e75.png)
why if i login with that user i'm able to click on add device group and create a new one?
![immagine](https://user-images.githubusercontent.com/62424179/77468912-92d12900-6e0e-11ea-9694-81f576909fbb.png)

**Comment by Ylianst** [comment]
So, there are currently no permissions for preventing adding devices to a group. I could add this if required. For creating new groups, that is a user account right. You have to go in "My Users", click a user, "server rights" and select "No New Device Groups". Hope that helps.

![x](https://user-images.githubusercontent.com/1319013/77471386-6b0ea080-6dcf-11ea-834e-4fad31643015.png)

**Comment by tradexsrl** [comment]
yes it works
