### ISSUE TITLE
how to send ALT+CTRL+CANC on windows desktop?

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1063]
Hi , how can i send ALTR+CTRL+CANC to login to my desktop?
![immagine](https://user-images.githubusercontent.com/62424179/77469380-463a1d80-6e0f-11ea-83b8-f36180547c1a.png)
in action there is not that action...

**Comment by tradexsrl** [comment]
ok found if i setup in the group rights remote view only i cannot do nothing...
what does it means "limited input only" ?
and why once the user is added to a group and setup what you can and can't do , there is no way to modify it? the only way is to delete it..

**Comment by Ylianst** [comment]
"Limited input only" restricts a user to basic keys (A to Z, 1 to 9, enter, backspace...). You can't do any CTRL, ALT, Fx keys. This is good to Kiosk usages. Normally you should have the special keys button on the bottom, but not if "Limited Input" is selected. Hope that helps.

![x](https://user-images.githubusercontent.com/1319013/77471717-0142c680-6dd0-11ea-9caf-e61f2840128a.png)

**Comment by tradexsrl** [comment]
and why once the user is added to a group and setup what you can and can't do , there is no way to modify it? the only way is to delete it..

**Comment by Ylianst** [comment]
You can change it. Click on the device group, click on the user's name and you can change the permissions. Unless you are running a very old server, should be no problem to change permissions of a user in a group.

**Comment by tradexsrl** [comment]
i tried to click on:
![immagine](https://user-images.githubusercontent.com/62424179/77520178-1592cc00-6e81-11ea-884e-5f0bb371dc19.png)
and i'm able to open the permissions:
![immagine](https://user-images.githubusercontent.com/62424179/77520226-2e02e680-6e81-11ea-9e65-fc89e84bcc51.png)
it was no user friendly because all your clickable action is underlined lie this:
![immagine](https://user-images.githubusercontent.com/62424179/77520370-6dc9ce00-6e81-11ea-86b2-f8ea7938a636.png)
so i though there is no possibility to edit.
thank's

**Comment by Ylianst** [comment]
Latest version of MeshCentral now has link icons and improved permission descriptions on these screens. I will close this issue, but do open a new one if there are any issues.
