### ISSUE TITLE
Gmail SMTP send issues

### ISSUE THREAD

**Issue by thalhammermax** [Ylianst/MeshCentral#1065]
For some reason, I can't get the SMTP send to work with a Gmail Account. Any ideas? Heres the SMTP portion of my config.json file. 

```
 "smtp": {
      "host": "smtp.gmail.com", 
      "port": 587, 
      "from": "email@domain.org",
      "user": "email@domain.org", 
      "pass": "passwordhere", 
      "tls": true
   }
```

**Comment by thalhammermax** [comment]
Also, Less secure app access has been enabled

**Comment by ryanblenis** [comment]
Less Secure Apps functionality is slated to be removed in Feb of 2021, might be good to support their more current mechanisms as well.

**Comment by Ylianst** [comment]
Try changing your port number to 465. This is what I use:

```
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 465,
    "from": "xxx@gmail.com",
    "user": "xxx@gmail.com",
    "pass": "xxxxx",
    "tls": true
  }
```

Thanks @ryanblenis for that notice, I will need to take a look into this.
