### ISSUE TITLE
MeshAgent32 on Windows 2003 Server in not a Win32 App

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#1066]
Hi
I try install meshagent32 on Windows 2003 Server and I can't.
When I run it I get information that meshagent is not a Win32 App.
I know that this is historical system, but our client use it.

P.S. Compatibility mode with Windows XP get this same error.
I run meshagent as Admin.

**Comment by GusevVictor** [comment]
meshagent don't work with Windows 2003/XP. You need Windows 7/2008R2 and above to work with mesh agent. There is big problem with an old OS like Win2003 because it has very bad arch.
