### ISSUE TITLE
reconnect agent to other mesh server

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#1067]
Is it possible to change agent config to connect to other mesh server without reinstall the agent ?
For example by editing MeshAgent.msh file and restart MeshAgent service ?
How I can do it.
I need move only few computers to new mesh server.

**Comment by Ylianst** [comment]
You got two options. You can just download the agent from the new server and re-install it on top of the old one. The other option is to install the new agent on a different computer, grab the meshagent.msh file, replace the old .msh with the new one and restart the agent. Hope that makes sense.

**Comment by motapek** [comment]
OK
I will try second option.
