### ISSUE TITLE
Invite Unauthorized

### ISSUE THREAD

**Issue by sdm216** [Ylianst/MeshCentral#1069]
When you have UserAllowedIPs enabled, the invite does not work when sending to end users. The link will bring the user to the download page, but when they try to download it says unauthorized. This is the case for Mac, and both 64/32bit windows.

**Comment by Ylianst** [comment]
Thanks for the report. I will fix this today.

**Comment by Ylianst** [comment]
Just pushed the fix to GitHub, will be in MeshCentral v0.5.0-v when I published it later today.

**Comment by uldiseihenbergs** [comment]
@Ylianst i'm on v0.5.1-c now, and i'm seeing something similar:
- i'm using UserAllowedIP to allow from LAN side only.
- i'm trying to add Linux agent outside my network, browsing to /meshagents says "Unauthorized", but /meshagents?script=1, it downloads meshinstall.sh and runs it, but fails in some next download with "Unauthorized" again. IMHO, /meshagents?script=1 should not work too in such configuration..

may i suggest:
- when you open Add mesh agent window, avoid checking for UserAllowedIP for some time to allow add agents outside UserAllowedIPs?
- add support for DNS names under UserAllowedIP. it would be useful when dynamic DNS is used and i want to allow user from outside my LAN, but agents still connect from anywhere.
