### ISSUE TITLE
Agent Disconnect When Getting Clipboard

### ISSUE THREAD

**Issue by sourcex** [Ylianst/MeshCentral#1070]
OS: Windows 10 Enterprise LTSC 2019 - 1809 [Version 10.0.17763.1098] - x64
MeshCentral: 0.5.0-l

The system is configured with a UWP app with [Assigned Access](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app).  If "Get Clipboard" is clicked once, it does not get the text.  If "Get Clipboard" is clicked multiple times, the agent disconnects and the content doesn't hit the clipboard.  The agent takes ~30 seconds to come back.

**Comment by krayon007** [comment]
Are you able to generate a core dump file for me? If you go to the agent installed path, edit the .msh file, and add:
coreDumpEnabled=1

to the end of the file, and then restart the agent. Then try the clipboard thing again... It should put a dump file in that folder.

**Comment by krayon007** [comment]
Also, I'm a bit confused about your description of AssignedAccess... Are you saying you are running the agent with Assigned Access? Or is the agent installed with the normal installer?

**Comment by krayon007** [comment]
I'm guessing you meant the agent is installed normally, and you are trying to get clipboard data from a single UWP app that is running with Assigned Access?

**Comment by sourcex** [comment]
That is correct- I mentioned the assigned access because the operating environment is a bit different then.  I'm pretty sure explorer.exe isn't started, for example.  The agent is installed normally.  I will work on getting a core dump this evening.

**Comment by sourcex** [comment]
Dump is attached.
[MeshAgent.zip](https://github.com/Ylianst/MeshCentral/files/4389488/MeshAgent.zip)

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
