### ISSUE TITLE
Filter Devices by Active User

### ISSUE THREAD

**Issue by zacmanamn** [Ylianst/MeshCentral#1071]
Currently there is no way to filter devices based on the active user. Currently we're tagging devices with users as we are using the software. Seems like this wouldn't be too difficult to implement.

**Comment by zacmanamn** [comment]
Yilan,

Yes, this works. Thanks for informing me. Works just as expected.

**Comment by hellofaduck** [comment]
"u:[username]" or "user:[username]" not working on 0.7.28, testen on linux and win servers, ip:[ip] works great, but we need username filter too )

**Comment by angelexe** [comment]
Confirm bug too.
u:[username]" or "user:[username]" not working
