### ISSUE TITLE
Server Version on Login Screen 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1072]
Hi @Ylianst and Team,

Any chance that the server version could be implemented on the login screen as a footer or similar lower portion of the page to show the server revision that is running?  Just a thought, as a lot of times its hard to tell which server is running the latest code in a cluster of them. :)

Thank you,
SomeGuru

**Comment by ryanblenis** [comment]
I disagree with this. Exposing a version number to a non-logged in interface could be a security concern. It lets potential attackers know exactly what version you're using, making it easier to try and find a vulnerability. It would be a disservice to those who don't update as frequently as others.

**Comment by Ylianst** [comment]
@ryanblenis is correct. Not going to be doing this because it's a security risk. If you are administrator of a server, you can go to "My Server" / "Console" tab and type "info".

![x](https://user-images.githubusercontent.com/1319013/77686782-b0aba480-6f5a-11ea-9b44-cc4ad36b03e5.png)

**Comment by SomeGuru** [comment]
Interesting, ok I can see semi valid points... I would assume that regardless of version number if the malice intent is there, the hacker would just attempt the same attack regardless of knowing the version number... However from a user perspective if there was a logo or seal or validation that the server is within several iterations of the latest, then it would get the seal of approval for latest security patches/features.  I find in the corporate sandboxes that a lot of these servers are deployed and not maintained which then leads me to believe that they are not run efficiently enough to be most secure in a large company scale, and could be deemed as security threats to the regards of non-patching. 

Just trying to come up with a solution that allows the end users to know they are connecting to the most secure solution with the latest patches. 

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
All I can say is that's not how that works. Large organizations have specific policies preventing this type of disclosure and changing MeshCentral to add the version on the login screen would break compliance. So, not going to happen.
