### ISSUE TITLE
how to shutdown a pc when i'm connected via rdp with meshcmd ?

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1073]
Hi i was trying the meshcmd + meshaction.txt for rdping to a computer , everything went well except how can i correclty shutdown the windows pc ?
on rdp i found only disconnect , if i login into meshcentral with the same user i see action like wake up - power off and reset.
reset is like pushing the reset button on the pc so is not the good one , power off means shutdown OS or means pull the plug?
or maybe i need to create an .rdp file from a mstsc - console command ?

**Comment by PathfinderNetworks** [comment]
The shutdown command in MeshCentral is a graceful shutdown of the device.  Meaning it's the same as clicking Start then Shutdown.  But you can also do it from the RDP session by going to a command prompt and entering 'shutdown /s' (or shutdown /r if you just want to restart it).

**Comment by Ylianst** [comment]
nothing much I can add, except maybe that is you want to experiment. You can try the "power" command in the agent console.

![x](https://user-images.githubusercontent.com/1319013/77708499-7d323f80-6f85-11ea-982c-a846c95351f6.png)

**Comment by tradexsrl** [comment]
@PathfinderNetworks : thank's for the clarification.
@Ylianst : question arise from a perspective of the end users for semplicity.shutting down from MC or via shutdown /s is viable since i have disable agent console to avoid any problem

**Comment by Ylianst** [comment]
I just tried the "Power Off" action on the device for a Windows 10 computer and it worked for me (It did have a 10 seconds delay). Did that not work for you? Agreed that the agent console is more for developers and testing.

![x](https://user-images.githubusercontent.com/1319013/77791488-f2545200-7023-11ea-80c3-933cdf8dd8ba.png)

**Comment by tradexsrl** [comment]
yes it worked. there is a bit of delay , at least 20-30 seconds

**Comment by Ylianst** [comment]
Right. Not sure why there is a delay, the command is sent to the OS immediately.
