### ISSUE TITLE
"plugins enabled false" not working as expected

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#1074]
When specified in the config 
`        "plugins": {
            "enabled": false
        },`
I expect plugins to be disabled on the server, but this is not the case.

**Comment by Ylianst** [comment]
The way this work is that if you don't specify anything, plugin's are disabled. If you specify:

```
"plugins": {
    // Anything at all
}
```

This enables the plugins and passes any parameters to the plugin system. This said, I just looked at the sample "config.json" and indeed, there is a `"enable": true`, so, I will fix this so your example disabled plugins on the next release.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-v that includes this fix.
