### ISSUE TITLE
Clipboard does not work in full screen with shift key

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#1075]
When I open full-screen mode with the shift key held down, the clipboard window does not open. When exiting full-screen mode, the clipboard window opens normally.

**Comment by Ylianst** [comment]
Indeed, I see the same. Looking into it.

**Comment by Ylianst** [comment]
Just fixed it. Will be in MeshCentral v0.5.0-w when I next publish it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.0-w, let me know if it works.
