### ISSUE TITLE
agents are not automatically added to MeshCentral

### ISSUE THREAD

**Issue by rau-alvin** [Ylianst/MeshCentral#1076]
Hello!

Thanks for your great software!

I have a problem. When I install an agent on any platform, my agents are not automatically added to MeshCentral.
But when I start Mesh with root - everything is fine. If I restart the agent with the usual user, the agent will appear.

What is the problem?

Thanks for the help!

**Comment by Ylianst** [comment]
One wild guess is that in meshcentral-data, the file meshcentral.db is read only when not running root. The first time you ran MeshCentral, if you did it as root, all of the files in "meshcentral-data" are owned by root and so, the other user does not have write access.

Check the ownership of the meshcentral-data folder and all files in it. Use 'chown' to change them to the user if they are root.

Hope that helps. This is just a guess with little to go on.

**Comment by rau-alvin** [comment]
The file "meshcentral.db" has the following permissions:

When I first saw this problem, I checked the grid of all files and made the user owner.

File "meshcentral.db" have next permissions now:
-rw-r--r--  1 rtadmin rtadmin    869 Oct 10 11:00 meshcentral.db

But the problem remains.

**Comment by Ylianst** [comment]
Can you check if `meshcentral-data/mesherrors.txt` exists?
I imagine that even running as `rtadmin` MeshCentral can bind to ports 80 and 443? (Not the root <1024 problem)?
When running as `rtadmin`, if you change the name of a device for example and restart the server, does the name revert back?

**Comment by rau-alvin** [comment]
- Yes, folder have file mesherrors.txt.
               -rw-r--r--  1 rtadmin rtadmin 947818 Mar 27 08:53 mesherrors.txt
- I using Nginx on 443 port, he is proxy for Mesh, which work on 4430 port.
- If I change the device name, after rebooting the new name remains
- Start "node node_modules/meshcentral --debug web,webrequest,agent,cert" with rtadmin:
[rtadmin@mymeshserver ~]$ node node_modules/meshcentral --debug web,we
MeshCentral HTTP redirection server running on port 800.
MeshCentral v0.5.0-w, WAN mode.
Loaded web certificate from "https://mymeshserver:443/", host: "mymeshserver"
  SHA384 cert hash: 2be74eec538f86b0f4d7f6b8c6e37e41b320da95016ea15202017286bf634bf5c0666bb368de599c0e45a88a5dd8751c
  SHA384 key hash: f149c4d13b6f74046fa079c65683bf41877c6be50b4a89ebd6f96481d736a3b718efd46e63eaf6cffe82172129f45b54
MeshCentral Intel(R) AMT server running on mymeshserver:4433.
MeshCentral HTTP server running on port 4430, alias port 443.
SMTP mail server mysmtpsite working as expected.
Agent connected with bad signature, holding connection (hostdevice1:45220).
Agent connected with bad signature, holding connection (hostdevice2:45312).
Agent connected with bad signature, holding connection (hostdevice3:45372).
Agent connected with bad signature, holding connection (hostdevice4:45396).
WEB: handleRootRequestLogin()
WEB: handleRootRequestLogin()
Agent connected with bad signature, holding connection (hostdevice5:45546).
WEB: handleRootRequestLogin()
WEB: handleRootRequestLogin()
....
- When start "node node_modules/meshcentral --debug web,webrequest,agent,cert" with root i don't see problems.
- If I change the title after rebooting, I see a new title and both rtadmin and root
- Yes, my TLS certificate on port 443 work via NGINX
- I do not see the server running twice:

[rtadmin @ rt-mc1 sites-enabled.d] $ systemctl | grep meshcentral
   meshcentral.service loaded active running MeshCentral Server

**Comment by Ylianst** [comment]
This is the problem right here:

`Agent connected with bad signature, holding connection`

It's not that agents are not automatically added the first time, it's that they don't ever connect at all when not root. Can you confirm this?

**Comment by rau-alvin** [comment]
This is strange, but sometimes, when I install the agent after restarting the service as an rtadmin, I see my agents. But often, you're right, the agent is not automatically added to the Mesh.

**Comment by rau-alvin** [comment]
My problem remains. Can you tell me what else could be the problem?

**Comment by rau-alvin** [comment]
@Ylianst I fixed my problem.

I think the problem was the permissions. I need to add permission to run (maybe, some operations need this)

Previously, files had such accesses:
-rw-r--r-- 1 rtadmin rtadmin

I made a resolution of 771 for the folders meshcentral-backup, meshcentral-data, meshcentral-files and the folders and files included in them. Agents are added automatically to my MeshCetnral now.

Please tell me if I am wrong.

Thank you for the help and health to you!

**Comment by decyphertek-io** [comment]
MeshCentral Agents not checking in? UNUSABLE
======================================

I am having the same issue. The agents never check in? I tried the suggestions here. Why hasnt this been fixed in over two years and the documentation is not very good either. I disabled all firewalls to rule that out , I also ran it via pm2 as well as node, both do not work. Here are my install instructions:

Install
--------

     $ sudo apt update
     $ sudo su -c "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
     $ curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
     $ sudo apt-get install -y nodejs 
     $ mkdir ~/.npm
     $ npm config set prefix ~/.npm
     $ export PATH="$PATH:$HOME/.npm/bin"
     $ source ~/.bashrc
     $ npm install -g npm@latest
     $ sudo setcap cap_net_bind_service=+ep /usr/bin/node
     $ mkdir meshcentral && cd meshcentral
     $ npm install meshcentral
     $ node /home/$USER/meshcentral/node_modules/meshcentral --install
     $ sudo systemctl status meshcentral
     #https://ip-of-server
     #Login > Create a new account 
     > Add a device Group > Download agent
     #Linux - run generated script as root.
     $ sudo systemctl status meshagent
     #Verify the agent checks into the console

     #Ports & Protocols
     #Meshagent - Linux listeners
     * 16990
     * 33020
     * 48063
     * 54229
     * 53358
     #Meshcentral - Linux Listeners
     * 80
     * 443
     * 4433 
     * 16990
     
References
----------

     https://meshcentral.com/info/
     https://github.com/Ylianst/MeshCentral/issues/1076
     https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf
