### ISSUE TITLE
problem with agent on windows7

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1077]
hi i'm seeing agent not connected even the pc W7 x86 pro is power on
![immagine](https://user-images.githubusercontent.com/62424179/77735956-bf9e5f80-700b-11ea-9b0f-2e0f0c930a51.png)
all of these pc except service33 and service27 are powered on.
these pc are on the same lan as MC and this situation is random because sometimes the greyed became connected and the connected became greyed even if powered on
this is a big problem the user and admin cannot do nothing remotely

**Comment by tradexsrl** [comment]
found the problem: meshagente.exe was deleted by AV...is there a way to avoid this? we can have many different AV brand and is not possible to make exclusion for each...

**Comment by Ylianst** [comment]
- You should file an false positive report with that AV vendor. Which one is it in this case?
- You can try the 64bit agent instead of the 32bit one.
- You could also try code signing the agent if you happen to have a code signing certificate and wish to do this.

**Comment by tradexsrl** [comment]
Symantec Antivirus , i apply an urgent exclusion for folder \mesh agent\ and i was able to get back meshagent.exe on all pc so i do not lost days of work...
64 bit on 32 OS i think is not possible.
i haven't a code sign certificate...

**Comment by Ylianst** [comment]
Make sure to file a false positive report with Symantec.

**Comment by tradexsrl** [comment]
ok done it for meshagent x86 - x64 and meshcmd x86 - x64

**Comment by Ylianst** [comment]
Thanks!
