### ISSUE TITLE
Suggestion: make doc screenshot/video on the agent install

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1082]
Hi,

While trying to convince colleagues to look at MeshCentral as an alternative to proprietary software I didn't find in the documentation (screenshots) and videos what the client/agent installation process looks like on a windows/macos/linux machine. For example you want to help your mom (or a student) fix her computer and you have a running Meshcentral server on meshcentral.example.org, what should your mom do on her computer to install an agent and connect it to your server so you can remote assist her?

May be I missed something :)

Thanks for this great open source software!

**Comment by Ylianst** [comment]
That is a good request. There are many [tutorial video here](https://www.meshcommander.com/meshcentral2/tutorials), but I don't think any of them cover agent installation.

**Comment by tradexsrl** [comment]
you can use send link invitation by mail so your mom or student will receive a mail with a link to download the agent , then he run the agent (no installation) and automatically you can help them by connecting to their desktop

**Comment by si458** [comment]
the is loads of youtube videos here - https://www.youtube.com/meshcentral
the is also a community member who made a whole video about it including setting it up - https://www.youtube.com/watch?v=-Jz73ZSmxuM
the is also the documenation (i know it needs updating) - https://ylianst.github.io/MeshCentral
