### ISSUE TITLE
Bulk user deletion option?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1083]
Hi @Ylianst,

I love the bulk add users, but didn't see an option to delete multiple users at once.... I added 30 people that need to be removed. Can this be done with a selection of users and then delete option?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Yes, I can work on that. I got items to work on before this, but certainly possible.

**Comment by Ylianst** [comment]
This feature was shipped around MeshCentral v0.5.2.
