### ISSUE TITLE
Unable to add AMT devices in WanOnly mode, but able to use the prompt

### ISSUE THREAD

**Issue by nroach44** [Ylianst/MeshCentral#1084]
We're able to open the Add Device on AMT groups in WanOnly mode, and click OK, but it won't actually add the device. Can we get the "add device" prompt updated to disable the OK button, and possibly a note added, when in WanOnly?

Original issue:

I'm trying to add an an AMT device. It's on the same subnet, and I'm not seeing any traffic going to the device when I add it (it doesn't end up showing in the list either). I've tried via hostname and IP, and TLS on and off on the device. I can browse to both the device web page and the MPS port fine.

Running the daemon with -debug and turning full tracing on doesn't show anything.

I'm running the web interface and agent interface behind Apache, but :4433 is set to go straight through:

```json
{ "settings": {
    "cert": "PROXYHOSTNAME",
    "TLSOffload": "PROXYIP",
    "Port": 8081,
    "RedirPort": 8082,
    "AliasPort": 443,
    "AgentPong": 300,
    "MpsPort": 4433,
    "MpsCert": "SERVERHOSTNAME",
    "MpsAliasHost": "SERVERHOSTNAME",
    "_MpsAliasPort": 4433,
    "MpsTLSOffload": false,
    "Minify": 1,
    "Wanonly": true
  },
  "domains": {
    "": {
      "_AmtAcmActivation": {
        "log": "amtactivation.log"
      },
        "newAccounts" : 0,
        "certUrl": "https://PROXYHOSTNAME",
        "agentInviteCodes": true
    }
  }
}
```

Is there more debugging options available?

**Comment by jsastriawan** [comment]
Wanonly: true means you can only add CIRA based connection. Set it to false to make it hybrid mode (WAN and LAN).

**Comment by nroach44** [comment]
Aha, I thought that LAN meant AMT was turned off completely, and that there was no middle ground, thank you!

In this case, I'll change this to a request to remark it in the web portal

**Comment by tradexsrl** [comment]
my server running in hybrid mode but if add an amt device it will not show in the group setup to be used with amt...

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
