### ISSUE TITLE
Keyboard: special characters Mac-Browser to Windows-PC

### ISSUE THREAD

**Issue by fernsehmuell** [Ylianst/MeshCentral#1087]
Hello,

if I connect to a windows machine from a Mac Browser and try to type special characters like German umlauts (öäü or a backslash \ and others) the wrong keys are pressed on the windows client. Both German keyboard layouts.

If I can help debugging this, tell me what I can do to help.

regards,
Udo Sauer

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back

**Comment by MiRei777** [comment]
Same issue with Version 1.1.38.
Brave-Browser [Version 1.73.105 Chromium: 131.0.6778.265 (Offizieller Build) (arm64)](https://brave.com/latest/)
Unable to send special characters like "@\[]{}" to the Windows-Client from OSX 15.2.
Keyboardmapping doesn't change anything.

Thanks a lot!
