### ISSUE TITLE
Device power history seems not working

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1088]
Dear Ylian, 

just to mention i notice the power history seems not working with my configuration. I'm running with v0.5.0-h, and I didn't check with the latest release, but seems like this since several versions already.

added a pic for showing you the case
![image](https://user-images.githubusercontent.com/62277469/77992310-69595580-7358-11ea-801c-b2713bad8064.png)

**Comment by Ylianst** [comment]
Thanks, I have been wanted to take a look at this issue for a long time.

**Comment by olivier37520** [comment]
It seems power off event(or ws close event) is not stored properly. 
I use mongodb and only power on events are stored. 
On my tests, I see this bug on machine with agent installed, no bug on agentless machine. I hope it can help

**Comment by Ylianst** [comment]
@olivier37520 I think you are correct. Working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-y with a fix for this. Let me know if it works.

**Comment by Fred1984** [comment]
Hello Ylian, 

i confirm the problem is now solved. i will close this case. But if you want to strengthen this part, it could be very useful to update the history table according the uptime of the device . For example in the below picture the computer was on but not connected to the network. Displaying a gray area could be helpful to track network issue than computer issue.
![image](https://user-images.githubusercontent.com/62277469/78214595-3a71e980-74e8-11ea-8fcd-ebe38cdae0c0.png)

Best regards
Frederic
