### ISSUE TITLE
meshcmd to power on pc problem

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1089]
hi to power on pc i'm using meshcmd with this command in bat file;
meshcmd amtpower --poweron --host PCNAME --user admin --pass PASSWORD
there are many of this command , separated by a 10 seconds pause 
sometimes not all pc powerup , but if i execute again they start...
is it better to use --host PCNAME.DOMAIN.LOCAL instead of only PCNAME?

**Comment by tradexsrl** [comment]
any news?
i had to disable intel amt because meshcmd with power on command is not reliable and i'm not able to power on 90% of our pc's
meshcmd will use heavily check on dhcp or dns ? i have checked and dhcp ip record are the same as in dns...so i don't understand why it does not power up...

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
