### ISSUE TITLE
 Windows7 64-bit Meshagent2 issu

### ISSUE THREAD

**Issue by yavuzyz** [Ylianst/MeshCentral#109]
Hi.
window7 The meshagen1 version does not work in the 64-bit version.
I would appreciate if you could

**Comment by Ylianst** [comment]
I happen to have a Windows7 64bit computers that is not part of the testing and the agent does seem to work. Any details about that does not work would be appreciated. Does the agent connect to the server? What if you launch "meshagent.exe run", does it work? Thanks.

**Comment by yavuzyz** [comment]
Thank you Meshagent2 64 bits working.

Best Regards.

________________________________
Gönderen: Ylian Saint-Hilaire <notifications@github.com>
Gönderildi: 24 Şubat 2019 Pazar 19:27
Kime: Ylianst/MeshCentral
Bilgi: yavuzyz; Author
Konu: Re: [Ylianst/MeshCentral] Windows7 64-bit Meshagent2 issu (#109)


I happen to have a Windows7 64bit computers that is not part of the testing and the agent does seem to work. Any details about that does not work would be appreciated. Does the agent connect to the server? What if you launch "meshagent.exe run", does it work? Thanks.

**Comment by Ylianst** [comment]
Not sure what was the issue here or what changed, but I will close this issue. Feel free to reopen if this happens again. Also, if the agent does not work, please post as much details as possible.
