### ISSUE TITLE
Unable to see the remote pointer

### ISSUE THREAD

**Issue by cp1797** [Ylianst/MeshCentral#1093]
Just published MeshCentral v0.4.9-m with Bryan's all new MeshAgents including on Windows his work on displaying the remote cursor. I give it a try and it works nicely.

_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/968#issuecomment-592225548_

**Comment by cp1797** [comment]
Hi! Am currently running 0.5.0-s and I still can't see the remote PCs (Windows and Mac) cursor. Is there a flag I need to enable this functionality? And just to clarify, will this also fix the cursor flicker issue?

**Comment by Ylianst** [comment]
Bryan will probably correct me, but my understanding is that your can't see the remote cursor on MacOS. For Windows and Linux, you only see the remote cursor when it is moved by the remote user. Let me know if that is what you see.

**Comment by cp1797** [comment]
I have tried on 2 Windows client machines and can confirm that I cannot see the cursor.

**Comment by Ylianst** [comment]
Even when the remote user moves the mouse? Humm, I just tried it on MeshCentral v0.5.0-x with Windows 10 Home (1903 [Version 10.0.18362.720]) and it worked for me.

**Comment by cp1797** [comment]
Will update the server to the latest and get back. Do the agents need an update as well?

**Comment by cp1797** [comment]
Have updated the server and tried but there's no improvement. Just to clarify the issue I'm facing, if the remote user (client) wants to show me something using his cursor, I am unable to see the same. If he clicks something, lets say a folder, then I can see the folder get selected, but his cursor is not visible to me at any point. Even if the same is moved by him.

**Comment by Ylianst** [comment]
That is weird. I wonder what is going on. Having the remote user show you something is exactly why this feature is interesting. Will need to investigate.

**Comment by krayon007** [comment]
I'll setup a Windows 10 Enterprise build, and see if I can reproduce it...

**Comment by cp1797** [comment]
Great! Let me know if there's anything I can do.

**Comment by krayon007** [comment]
Can you type "version" in the console tab, without the quotes, and report back what it says?

I just tested with Windows 10 Enterprise - 1703, and the remote cursor seems to work fine.. I'm running Windows Update on it right now, to update to the latest build to verify it still works...

**Comment by cp1797** [comment]
Here's what I see:

`Mesh Agent Version: 2020-02-28 03:22:56.000+05:30`

**Comment by krayon007** [comment]
I updated my Windows 10 Enterprise, to build 1903, and the remote cursor still works... Are you able to update your Windows 10 Enterprise to the same build?

**Comment by cp1797** [comment]
I can update it to Build 1909 (November 2019). Will that do?

**Comment by cp1797** [comment]
I setup Build 1903 on a laptop and tested it. It didn't work. Will update to 1909 on another laptop, test and get back

**Comment by cp1797** [comment]
Build 1909 setup and it still doesn't work. Let me know if there's anything you'd like me to try

**Comment by krayon007** [comment]
Are you running 32 bit or 64 bit windows?

**Comment by krayon007** [comment]
I just tested both the 32 bit and 64 bit agent running on 64 bit Windows 10 Enterprise - 1903, and remote cursor rendering appears to work fine.

**Comment by krayon007** [comment]
Are you able to see the cursor change shape on the browser? (ie, can you see the cursor change shape from pointer to resize arrow, etc?) I ask, becuase it uses the same code underneath to grab the cursor image.

**Comment by hwood2108** [comment]
Hi I have started to look at MeshCentral to remote manager VDI desktops, we are experiencing the cursor flicker when connected also a black square appears when you move the mouse pointer to the URL bar in Google chrome, is anyone else experiencing this problem or is there anything I can try to fix, I have already tried the video drivers of the guest VM which is Windows 10  Enterprise edition 1909 (OS Build 18363.1016), any help pointers would be appreciated.

**Comment by krayon007** [comment]
> Hi I have started to look at MeshCentral to remote manager VDI desktops, we are experiencing the cursor flicker when connected also a black square appears when you move the mouse pointer to the URL bar in Google chrome, is anyone else experiencing this problem or is there anything I can try to fix, I have already tried the video drivers of the guest VM which is Windows 10 Enterprise edition 1909 (OS Build 18363.1016), any help pointers would be appreciated.

Are you experiencing this problem when you move the local cursor of the browser on the Host OS, or are you talking about moving the cursor inside the VM itself? What VM software are you using? I tested with VMWare, running the same build of Windows 10 Enterprise in a VM, and the cursor rendering appears to work properly.

Also, are you using KVM to the guest VM or the host VM? I ask becuase I have seen VM software will do tricks with the mouse cursor when controlling the guest, such that if you remote into the host OS, the cursor image is not correct when you control a guest VM.

**Comment by hwood2108** [comment]
> > Hi I have started to look at MeshCentral to remote manager VDI desktops, we are experiencing the cursor flicker when connected also a black square appears when you move the mouse pointer to the URL bar in Google chrome, is anyone else experiencing this problem or is there anything I can try to fix, I have already tried the video drivers of the guest VM which is Windows 10 Enterprise edition 1909 (OS Build 18363.1016), any help pointers would be appreciated.
> 
> Are you experiencing this problem when you move the local cursor of the browser on the Host OS, or are you talking about moving the cursor inside the VM itself? What VM software are you using? I tested with VMWare, running the same build of Windows 10 Enterprise in a VM, and the cursor rendering appears to work properly.
> 
> Also, are you using KVM to the guest VM or the host VM? I ask becuase I have seen VM software will do tricks with the mouse cursor when controlling the guest, such that if you remote into the host OS, the cursor image is not correct when you control a guest VM.

**Comment by hwood2108** [comment]
krayon007, thanks for the quick response, my hypervisor is based on KVM and ubuntu server 18.04 (HiveIO), when a user is accessing the VDI VM they are using the Window RDP client, and when I use the  meshcentral server running on linux with a chrome(also tried IE and Edge), the mouse pointer looks ok but the end user on the VDI VM sees the pointer flickering and a black box appears when you hover over the URL bar on chrome, I have found if you increase the scale on the browser window of the VDI desktop to 100% in meshcentral and only shadow (input un ticked) pointer only flickers a very small amount, and the black box doesn't appear, I have upgraded to the latest version of MeshCentral as well, still the same
