### ISSUE TITLE
Missing strings 0.5.0-X

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1096]
![translation-10](https://user-images.githubusercontent.com/58996467/78065963-6714ec80-7394-11ea-9144-63bc01910b6e.jpg)
![translation-9](https://user-images.githubusercontent.com/58996467/78065966-67ad8300-7394-11ea-8e06-7df7c1297e47.jpg)
![translation-8](https://user-images.githubusercontent.com/58996467/78065967-67ad8300-7394-11ea-8a7e-5c150f03f0f7.jpg)
![translation-7](https://user-images.githubusercontent.com/58996467/78065968-67ad8300-7394-11ea-95a9-49842fb0bcd4.jpg)

**Comment by Ylianst** [comment]
Thanks! I will work on that.

**Comment by petervanv** [comment]
These items are not to find and also not translated, can you fix that also.
Thx for the quick respons and fixing of the bugs/translation

![translation-11](https://user-images.githubusercontent.com/58996467/78067627-544fe700-7397-11ea-96e5-de3d7d05693f.jpg)
![translation-14](https://user-images.githubusercontent.com/58996467/78067629-54e87d80-7397-11ea-81a7-61ee342cc690.jpg)
![translation-13](https://user-images.githubusercontent.com/58996467/78067630-54e87d80-7397-11ea-8a72-239a2af988dd.jpg)
![translation-12](https://user-images.githubusercontent.com/58996467/78067631-54e87d80-7397-11ea-8734-5ebc19fb6e72.jpg)

**Comment by Ylianst** [comment]
Thanks. Just check in a lot of fixes for the "title=" in the web application, did a search and found many more that where not translated correctly. For the emails, I will have to work on adding internalization support for these.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-y with the missing strings fixed. Email translation is going to be a bunch more work.

**Comment by petervanv** [comment]
oke, cant wait to translate it. goodnight for now.

**Comment by Ylianst** [comment]
Now that MeshCentral v0.5.1-g includes the email templates in many languages, I think this closes this issue. However, I do expect a bit of bug fixing to go on with the latest email system.
