### ISSUE TITLE
Android agent?

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1098]
Hi , i saw a bunch of post about having Android agent dated beginning of 2019 , are there any news about that?
we will implement a fleet of android device for warehouse and salesman and having a unified solution for management will be helpfull

**Comment by Ylianst** [comment]
You probably saw some blogs about the Android agent for MeshCentral v1 from 2009 or in any case, many years ago. We did have a prototype Android agent then, but it's not in development now and so, MeshCentral v2 has no Android agent. If someone wanted to work on developing it, it would be great, but no plans from myself and Bryan for it currently. We are sort of overloaded as it is.

**Comment by krayon007** [comment]
Just to add, the main reason development stopped in the Android agent was due to API and policy changes by Google, regarding APIs that we used for KVM. Under the new APIs and policy, it is not possible to provide KVM with remote input without OEM/device specific APIs.

**Comment by tradexsrl** [comment]
:-( ok understand

**Comment by vitko-bg** [comment]
As I know Anydesk Agent work perfect on Android. Are they using different mechanism to control Android devices?

**Comment by krayon007** [comment]
In order for remote control on Android, you need OEM support with phone/device specific drivers.
