### ISSUE TITLE
download server backup: unauthorized

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1099]
with latest version of MC if i click on download server backup , i get a new page with url like https://domainmeshcentral.com/backup.zip and the word unauthorized in the body..... and no file downloaded

**Comment by trenton92** [comment]
Hello. If you using loginkey you need add to your link ?key=secretword

**Comment by tradexsrl** [comment]
now i've tried to login again into the MC server and immediately go to download server backup and without doing nothing i get the zip downloaded.
my server admin login is protected with 2fa , i suspect if i'm logged in from some minutes when you go to that link the token or something else is expired and i get that error...
i suspect this also because i setup in json config a session expire of 30 minutes but i never get logged out automatically at the end of that timer...

**Comment by Ylianst** [comment]
You could try adding this line to the domain session of the config.json:

`"UserSessionIdleTimeout": 25`

This will detect is you are idle for 25 minutes and auto-logout. This said, it's probably not going to fix this because just doing some activity on the web page is not going to review the 30 minute web server session.

Maybe is you click on backup and you get access denied, I should redirect to the login screen.

**Comment by tradexsrl** [comment]
with that parameter at least the logout automatically was done correctly.
i think is better to redirect to login screen not only in this case but on each click done in the interface when the timeout is reached because otherwise i'm in doubt the modifications i could make are not saved

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back

**Comment by hide-afk** [comment]
hi @si458 , I have scanned vulnerable endpoints of my meshcentral, and there is this backup zip folder https://domainmeshcentral.com/backup.zip. I would like to know where is this file located, to change the permissions. Thanks a lot.

**Comment by si458** [comment]
@hide-afk the file is auto generated, you shouldnt be able to access it unless you are logged in to the meshcentral ui
