### ISSUE TITLE
No Connection to powered off AMT-Device possible

### ISSUE THREAD

**Issue by narwahls** [Ylianst/MeshCentral#11]
We are Using Meshcentral primarily for managing AMT-Devices.
Since some Versions, if I remember correctly Version 0.1.2 before the Mesh Agent Integration, it is not possible to establish a connection to powered off Devices. Is this designed as wanted?
As it was in the beginning, we could always Hit Connect and Meshcentral would try to establish a connection to a designated Device. 
To regain this feature would be quite awesome.

Best regards,
Narwahls

**Comment by jsastriawan** [comment]
Hi Narwahls,

Meshcentral will still be able to contact an AMT machine if it is:
- located on the same network as Meshcentral server
- also connected through CIRA (firmware managed TLS ports forwarding)

So here is what I recommend. If you have a machine that is joined to a Mesh Agent based Mesh, you could also add CIRA to that machine. The CIRA activation link for your agent based mesh is located on the right hand side (besides Add Agent, now you see Add CIRA, Add Agent).

Once you add CIRA to the AMT machine, you will always have permanent AMT link.
This feature has been added on late 0.1.6 version and it should be still available now. :)

Let us know if you still need help. If you have any other feature requests or suggestions, please feel free to contribute too. 
Regards,


Joko

**Comment by whalehub** [comment]
@Ylianst I think this issue can be closed since OP hasn't responded in almost a year.

**Comment by Ylianst** [comment]
Closing this issue. Feel free to open a new issue on this topic if needed.
