### ISSUE TITLE
Multiple displays are not working to selected display

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#1100]
Last update are not allowing to change to a selected display, it just appear with all displays at same time.  Have any experienced/solved that?

**Comment by tradexsrl** [comment]
in my case i get  the two side by side , first screen ok , the second one is completely black

**Comment by krayon007** [comment]
Can you go into the windows device manager, and list all the display adapters that are enabled on your system for me?

**Comment by tradexsrl** [comment]
in my case please see the image attached.
but i've got to say it works. yesterday i just look at the pc desktop without doing the login and that why i see side by side , first one ok and second one black.
this morning , i do login and i see correctly the two desktop.
![immagine](https://user-images.githubusercontent.com/62424179/78217791-fe755f00-74bc-11ea-9e4d-d651060f8c05.png)

**Comment by MC-PM** [comment]
solved with last MC update... also keep on mind that you may need to update remote video drivers in case you may have similar issues.
