### ISSUE TITLE
Mac OS Agent Problem with FileVault

### ISSUE THREAD

**Issue by trenton92** [Ylianst/MeshCentral#1101]
Hi Bryan and Team. I wrote to you about the problem with agents on mac os. Before quarantine, I added your agent for 15 macbooks. At the moment, during the entire periods a couple of times some were active.
Today I upgraded meshcentral to the y version. Everything worked, and then I encrypted the macbook using FileVault. After which I restarted it and the agent immediately stopped working.
All our macbooks are encrypted using FileVault. Perhaps the problem lies precisely in it. 
Thank you and the whole team for this project.

I think as a solution to write a script in which the agent will restart when the macbook is turned on. But I wanted without it.

**Comment by krayon007** [comment]
Are the agents on these encrypted Macs, not installed as launchd daemons?

**Comment by trenton92** [comment]
![Screenshot 2020-04-02 at 09 22 37](https://user-images.githubusercontent.com/61736438/78217045-de956980-74c3-11ea-8459-10694914b137.png)

**Comment by krayon007** [comment]
Might take some time, but I'm going to create a new Catalina system with FileVault enabled, so I can see if I can reproduce what is going on.

**Comment by krayon007** [comment]
Which version of macOS are you running? I just built a Catalina System, and enabled FileVault... The agent seems to function correctly...

I did read, that on other versions of macOS, the launchdaemons do not run until the first user logs in... Not sure if that's still an issue or not, but on my Catalina system, I rebooted the system, and the agent connected to the server while it was booting just fine...

**Comment by trenton92** [comment]
We use Catalina, Mojave, High Sierra.
At Meshcentral, 12 macbooks were never online for a week. Macbooks are used every day. I took one with me (Catalina) and installed the agent, it worked fine until I did FileVault. Perhaps the problem lies in the server, but Windows and Linux work like clockwork.

**Comment by krayon007** [comment]
Did you try uninstalling and reinstalling the agent? When enabled FileVault, the agent didn't work correctly, but I wasn't sure what version I had installed on this machine, so I uninstalled and reinstalled the agent, and it seemed to work fine...

**Comment by trenton92** [comment]
Yes. Before quarantine, we installed the latest version of the installer for everyone from the latest Meshcentral at that time.

**Comment by trenton92** [comment]
Reinstalled for the test on your MacBook.
Meshcentral Version: 0.5.0-y
I'll see how it will be

**Comment by trenton92** [comment]
After 4 days, that test laptop stopped seeing. Now he is in the office, so I can’t throw you the logs. But there was an employee macbook on the net. I went into the Console, and there it is

uncaughtException1: Error: timers.onElapsed() callback handler on 'sendNetworkUpdate()'  => TypeError: cannot read property 'toString' of undefined

Maybe this will help you somehow.

**Comment by si458** [comment]
closing as stale,
but please try the latest version from the master branch or wait for a new release as we made a few installer fixes for mac
`ghcr.io/ylianst/meshcentral:master` or `npm install Ylianst/MeshCentral`
