### ISSUE TITLE
0.5.1-a : Special device permissions - No Keyboard typing 

### ISSUE THREAD

**Issue by alyatis85** [Ylianst/MeshCentral#1103]
Hi,
I tried to use the new functionality of giving special device permissions to a specific user.
The user can see its own mahine, connect on it but can't type anything with the keyboard whereas the mouse is working.
The user is only provisionned on the machine, not on the computer group.
The settings are  the following (work good when set on the comuter group): 
- Control (No terminal, No file, No AMT), Limit Events, Instant Discuss

**Comment by vedran-dobos** [comment]
Hello,

I noticed the same problem, and just wanted to submit an issue.
Sending special key combinations from the drop-menu also works.
Just the keyboard is the problem.

**Comment by Ylianst** [comment]
OH DEAR! I can't believe I did not notice that before. I see the same problem and working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-b with a fix for this! Thanks for reporting it. That was a big miss on my part.

**Comment by vedran-dobos** [comment]
Seems to work now. I've set it up for a bunch of users... should have feedback in a day or two if there are problems.

Thanks very much!

**Comment by Ylianst** [comment]
Thanks. Let me know as soon as possible if you see any issues.

**Comment by alyatis85** [comment]
I confirm it works.
Thanks very much Ylian.
