### ISSUE TITLE
Conferma su connessione al desktop

### ISSUE THREAD

**Issue by ccarcano** [Ylianst/MeshCentral#1104]
Hello, 
I'd like to use Mesch Central in the firm where I work, since it could solve lots of problems we currently have and it seems a really good product.
I installed it both in Windows and Ubuntu (wan and lan). They both work but they have the same problem.
When I remotely connect to a desktop that has your agent installed, the PC user is not aware that I have made a connection because there is no message
Would it be possible for the user to receive a warning message to tell him that someone is going to connect to his PC? If the user gives no answer in 5 seconds, the connection should be automatically accepted but the PC user should receive a message telling him that someone was connected to his pc.
I read in some forums that a label is visible on users' PC, but I didn't find any label when I connected to my users' pc.
Best regards

Claudio

**Comment by ryanblenis** [comment]
Hi @ccarcano,

This option is already available when you click on the Group Name -> User Consent options.

**Comment by Ylianst** [comment]
Correct. Click on a device group and go in "User Consent" to setup the consent options for that group.

![x](https://user-images.githubusercontent.com/1319013/78283830-43a48b80-74d3-11ea-835e-9e07f6b7c480.png)

You can also force your server to require user notification and the connection bar by adding the following line in the domain section of the config.json:

`"UserConsentFlags": 71`

Hope that helps,
Ylian

**Comment by ccarcano** [comment]
Wonderful!!
Thanks a lot
Bye
