### ISSUE TITLE
possible bug in terminal with latest MC version

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1106]
hi , i was connected with the terminal on one of our pc via MC and then i type exit like i do when i was in normal cmd and in console i see this error message:
![immagine](https://user-images.githubusercontent.com/62424179/78360644-690ac580-75b7-11ea-89f3-fdbac1e02145.png)
now if i try to reconnect to terminal nothing show up anymore...

**Comment by krayon007** [comment]
Which OS are you referring? If windows, what version and build? No changes have been made to terminal in quite a while.

**Comment by ryanblenis** [comment]
In addition to Brian's questions, are you using any plugins?

**Comment by krayon007** [comment]
I'll take a look at this and see if I can reproduce this on Windows 7.

**Comment by Ylianst** [comment]
I think Bryan has a fix for this one, it will be an updated MeshAgent later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-h with Bryan's updated Windows MeshAgent that should fix this. Let us know if it works.

**Comment by tradexsrl** [comment]
yes now with the exit command i get a correct disconnection and no error message on the console.
thank's

**Comment by Ylianst** [comment]
Thanks to Bryan for the fix!
