### ISSUE TITLE
Feature Request: Search by Group

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#1109]
We are starting to add a lot of computers on Mesh Central with a lot of groups. It would be awesome to have the filter at the top to allow to search by group and be able to select the group and only display the computers in the group. Or even better a separate select form box with a search form next to filter would do Fantastic!! Thanks for your hard work!!

**Comment by Ylianst** [comment]
Try typing "g:(groupname)" or "group:(groupname)" in the search box. Let me know if that works.

**Comment by johnnyq** [comment]
that works great!! Thank you!! although I think there should be a separate select box that allow you to choose group to make it more pronounced

**Comment by OutbackMatt** [comment]
If there were a separate box to choose groups, I'd also like a 'clear all filters button'

**Comment by Ylianst** [comment]
To clear filters, you can hit the `escape` key.

**Comment by OutbackMatt** [comment]
Awesome. Thanks for the tip
