### ISSUE TITLE
MeshAgent get NodeID when running as a console agent

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshCentral#111]
The way im using Meshcentral, is that another application will be make a cmd call to run MeshAgent in console mode with either "MeshAgent run" or "MeshAgent connect".

As far as i understood, when run in console mode, the NodeID will be saved to registry under HKEY_CURRENT_USER. It doesnt do that though. If i install as a service i can see the nodeid under HKEY_LOCAL_MACHINE but unfortunately i dont want to run it as a service.

Im not sure if this is a bug? Anyway, is there any way for me to run the MeshAgent with "MeshAgent connect" and somehow retrieve the nodeid after that?

EDIT: Another observation. If i do "MeshAgent connect" and start it as admin, the nodeId gets written to HKEY_LOCAL_MACHINE. I dont understand why though, "connect" is console mode and should therefore be written to HKEY_CURRENT_USER, right?
You dont need admin rights to read/write to HKEY_CURRENT_USER so it should be possible to do this when run in console mode even without admin rights.

EDIT 2: I compiled MeshAgent from source (MeshConsole) and it worked as intended. So i figure when i download the MeshAgent from my MeshCentral server, i download "MeshService". Can i somehow download "MeshConsole" from my server as well?

**Comment by marco-vogt** [comment]
Another possible fix for this would be to have "MeshService" create registry values in both HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER. This way, when ran as admin, it will create both keys and if run without admin, it will only create keys in HKEY_CURRENT_USER.

Do you think its possible to add this? I somehow need to be able to run MeshAgent without admin rights and have a way to retrieve the nodeId

**Comment by Ylianst** [comment]
I will check that again. When running the MeshAgent as a user, it should create the CURRENT_USER registry keys. If running as a service, it should create the LOCAL_MACHINE ones. I can't remember looking into the "Connect" button case. In any case, next time I get a chance, I will take a look.

**Comment by marco-vogt** [comment]
https://github.com/Ylianst/MeshAgent/blob/master/meshcore/agentcore.c#L3695

This is the line thats deciding wheter to add to LOCAL_MACHINE or CURRENT_USER. It doesnt add to CURRENT_USER on the "connect" button because "_WINSERVICE" is always defined with the MeshAgent.exe that i download from my MC server

**Comment by krayon007** [comment]
I can fix this when I get back in the office.

**Comment by marco-vogt** [comment]
@krayon007 Perfect, thanks!

**Comment by khaleong** [comment]
Hi,

Under Linux machine, how can we get node id from meshagent?

**Comment by Ylianst** [comment]
I think Bryan is working on a way to get the NodeID on Linux... but I will let him post that when it's ready.
