### ISSUE TITLE
Can't access My Files or Group Files from Device File Manager

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1110]
Hi folks,
I'm sure I'm missing something basic, but I can't for the life of me figure out how to access files that I've placed in the My Files are or Device Group Files area from the actual device file manager.  So I keep having to upload the same files repeatedly.

Can someone tell me what I'm doing wrong?

**Comment by krayon007** [comment]
The My Files is a folder on the server, not the client. The files tab, refers to the client file system.

**Comment by amenolo** [comment]
@trentdavis if you want share file between server and client directly (which is your matter here, I guess), you can use the public links to files under Public folder.

**Comment by ryanblenis** [comment]
Not sure your use-case, but I wrote the [FileDistribution](https://github.com/ryanblenis/MeshCentral-FileDistribution) plugin to have the server push files to clients and keep them up to date on endpoints.

**Comment by trentdavis** [comment]
> @trentdavis if you want share file between server and client directly (which is your matter here, I guess), you can use the public links to files under Public folder.

Thanks for your input everyone!  But where is this Public Folder?  I'm not seeing it anywhere, and certainly not seeing it from the clients's file manager.

**Comment by Ylianst** [comment]
For the public folder, for in "My Files" tab, then "My Files" and "Public". As a regular user, you will not see this unless your user account is administrator or was given server file space. Let us know if this helps.

![x](https://user-images.githubusercontent.com/1319013/78462423-8fe3fd00-7686-11ea-9adf-306d7e1478cd.png)

**Comment by trentdavis** [comment]
Ok, will try this.  Thank you!  
Are there any potential security issues with the public folder that I need to know?

**Comment by Ylianst** [comment]
For security: obviously, anyone that knows the URL or can scan for lots of URL's on your server could download a file in the public folder without any server credentials.

**Comment by amenolo** [comment]
@Ylianst BTW how about...replacing the `display link` link with a copy link command?
It seems smarter to me and also more global consistent :innocent:

**Comment by amenolo** [comment]
@Ylianst BTW how about...adding a `copy link to clipboard` link (i.e. link with `?download=1` suffix, of course) besides current `display link` link?

**Comment by Ylianst** [comment]
@amenolo Good idea! I will add that.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-h with updated icons for the public folder, let me know if that works.

![x](https://user-images.githubusercontent.com/1319013/78629269-5f00f500-784b-11ea-9789-1c2af2a50bd2.png)

**Comment by amenolo** [comment]
As highlighted above, IMHO the `copy link to clipboard` link should include trailing "?download=1" in order to be actually direct, otherwise it would be just a shortcut to the classic link (the courtesy web page) and ultimately a merely duplicated command (altough "more" direct)...do you agree?

**Comment by trentdavis** [comment]
Forgive me if this is a silly question, but what would be the possibility
of making this list (the public list) available from within the File
Manager of the client device, so that a file could be downloaded directly
to the client device from File Manager?

**Comment by Ylianst** [comment]
@amenolo I added the "?download=1" in the link on MeshCentral v0.5.1-i. Let me know if that works.
@trentdavis No way to make files show up on the client right now using the MeshAgent. That could be an ask as a different issue, but not something we would likely do in the next year or more. Of course, if someone where to work on it, I would accept the code.

**Comment by amenolo** [comment]
Works as a charm, thanks!

**Comment by amenolo** [comment]
Works like a charm, thanks!

**Comment by Ylianst** [comment]
Ok, going to close this one since it's going off topic a bit. Please feel free to create a new issue.
