### ISSUE TITLE
Desktop connection timeout using consent screen in Windows client

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1111]
Today I upgraded my personal MC server to last stable release and now after client side confirmation the desktop connection goes time out.

It only happens with consent screen on, and in Windows client only (not in Linux client, at least...I'm unable to test under MacOS).

Thanks guys!

**Comment by krayon007** [comment]
ok, I see the issue now... I'll work on it, and get Ylian to push an update...

**Comment by krayon007** [comment]
Ok, I found and fixed the issue. When I added support for alerts, which re-used the code for user consent, I added the ability to change the button layout... When I did that, I accidentally screwed up the windows specific switch statement that handled the button press. I fixed and tested it... I'll let @Ylianst  know to rebuild the windows agent, and update.

**Comment by Ylianst** [comment]
Working on it!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.1-d with updated Windows MeshAgent. Let us know if it works.

**Comment by amenolo** [comment]
Working great again, guys you're always on top!
