### ISSUE TITLE
No send mail / reset mail 

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1115]
I have created an new account for an support engineer, the email is not send to that emailadres. i tested it with an already existeng account (forgot its password) it says it ill send the reset mail, but it is not found in the "send email" from gmail. When i send it from gmail its delivered in my mailbox.

1. creating account wil not send mail, but account is created and useable
2. reset email not send, so unusable

it has always worked, tried the other settings, same result. possible connection with internationizing the emails ???

server: Ubuntu 18.04.4 LTS hosted on qnap
Meshcentral version: 0.5.1-E
NodeJS: 12.15
Node: 10.19
DataBase: NeDB

**Comment by Ylianst** [comment]
Looking into this right away. The email system has changed a lot, certainly has to do with internalization.

**Comment by Ylianst** [comment]
Ok, looks like this is only a problem on Linux servers. Working on it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-g with a fix for this. I forgot to include the new "emails" folder in the package.json, so it was not being published on NPM. The new folder contains all of the email templates and translations.

**Comment by petervanv** [comment]
confirmed fix, thx
