### ISSUE TITLE
Add Download Agent Button

### ISSUE THREAD

**Issue by tiny6996** [Ylianst/MeshCentral#1117]
Create an Option to have an agent download button appear on the homepage without logging in. It would be nice if it pulled the user agent of the browser, and presented them with the agent download for their OS.

**Comment by tradexsrl** [comment]
mmm...if you download mesh agent without login , MC will not "recompile" it to add all the server info , so you get no connection.
i have checked it when i had problem with antivirus that keeps deleting the meshagent downloaded from the add user link into a group.

**Comment by Ylianst** [comment]
The way to get this done is to click the "Invite" link on a device group, select an unlimited time link and make a button out of that link. If you are asking for MeshCentral to serve a real graphical button, can you send a prototype of what it would look like?

<img width="732" alt="x" src="https://user-images.githubusercontent.com/1319013/78588765-094d2e00-77f4-11ea-8ff6-88f89e71304a.png">

**Comment by tiny6996** [comment]
I was not aware you could make a perminent invite thank you
