### ISSUE TITLE
Authorization is required for download meshaction.txt

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#1118]
First, thank you for the useful and multifunctional program!
Secondly, I use meshcentral as an alternative to VPN. The script downloads the meshcmd and the meshaction.txt, and then started the rdp connection to the device. But in the new version of the meshcentral server authorization is required to download the meshaction. I ask you to explain how to log in via curl (and curl for windows). [This ](https://curl.haxx.se/docs/httpscripting.html#User_name_and_password) method does not work.

**Comment by Ylianst** [comment]
Oh, this is a bug (For my own notes, the bug is [located here](https://github.com/Ylianst/MeshCentral/blob/f5c5ebaf5e9b2b50bdef201a04d9eb47bf77675d/webserver.js#L3357)). I will get this fixed later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-h with a fix for this. Let me know if is it works.

**Comment by Ilia1** [comment]
Yes, it works again without authorization. Thanks.
