### ISSUE TITLE
2FA "remember 30 days" checkbox not working

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1120]
A small hiccup with 2FA for me: i checked "remember 30 days" checkbox, but looks like it's not working - it asks again for 2FA code every time i login. Are there any config i'm missing? no "Passwordrequirements" in my config.json.

i'm using Ubuntu with Chrome browser.

**Comment by Ylianst** [comment]
When you select the "Remember for 30 days", MeshCentral should place some encrypted information in your browser that will be retrieved each time you log back into your server. Because I go into this too deeply, can you check if your privacy settings in your browser clear all cookies/cache on each close. If so, that feature will not work.

**Comment by uldiseihenbergs** [comment]
Hello!
but i won't close browser, i simple click on log out, and then try to login back immediately - it asks again for user/password, and then 2FA too. i have very similar 2FA authentication on Roundcube webmail for example and it works just fine - on first login it asks for login/password and 2FA code, but when i log out, on next login it asks for user/password only..

**Comment by Ylianst** [comment]
Ok, I will test this again.

**Comment by uldiseihenbergs** [comment]
maybe it's something with my reverse proxy? see pic, i'm using https.
![image](https://user-images.githubusercontent.com/60253253/78591296-e64e6880-784b-11ea-8afc-2eefd7dc39e9.png)

**Comment by Ylianst** [comment]
I just re-tested it on my server and the 30 day feature work correctly. It does add a site cookie to the browser. Not sure I can help much debugging your specific situation.

**Comment by uldiseihenbergs** [comment]
as you see in my previous post, i have this cookie in my browser.
so, i just tested it on my LAN side without proxy, then it works.
if someone have a suggestion for Apache reverse proxy and cookies, let me know..

**Comment by uldiseihenbergs** [comment]
and i just got it working. I had to add the following line to my Apache reverse proxy:
`ProxyPassReverseCookiePath / https://<MC-lan-ip>:<MC-https-port>/`
so, closing this issue now.
