### ISSUE TITLE
Meshcentral server autobackup problem

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1121]
Hi , if i look inside the path \meshcentral-backup\ on a windows 10 machine where is installed the server , i will only find autobackup file of 8 days ago and beyhond.
when does autobackup runs? 
i have MC version 0.5.1-g

**Comment by Ylianst** [comment]
MeshCentral stopped doing backups 8 days ago? That is not good, I will check.

**Comment by Ylianst** [comment]
Can you try the `backupconfig` and `autobackup` commands in the server console? Let me know if `autobackup` command generates a new backup in "meshcentral-backups". Any hints or added information as to what is going on would be appreciated.

![x](https://user-images.githubusercontent.com/1319013/78626204-e8f89000-7842-11ea-9c19-968667a97dad.png)

**Comment by tradexsrl** [comment]
ok done , before the autobackup and backupconfig there were 4 old backup files , now with these command i get 3 backup files and one is dated april 7th:
![immagine](https://user-images.githubusercontent.com/62424179/78637056-e54c2400-78a9-11ea-9266-7fefdcb1abc3.png)
it seems manually backup works , scheduled not

**Comment by tradexsrl** [comment]
in the mean time i see you have published 0.5.1-h , i will update to this and see if tomorrow i will get autobackup

**Comment by Ylianst** [comment]
Thanks for the report, 0.5.1-h does not have any auto-backup changes, but I will investigate and see what I can do about this.

**Comment by tradexsrl** [comment]
just to report with 0.5.1-i autobackup doesn't work.
i have upgraded to j and tomorrow i will see ho it goes

**Comment by petervanv** [comment]
My autobackup is working im om ubuntu 18.04

**Comment by tradexsrl** [comment]
are there any news ? i'm on 0.5.1-v but the autobackup still don't run

**Comment by Ylianst** [comment]
Looking at the code, the auto-backup timer starts at the moment you run the server and after 24 hours, do a backup. Problem is, if you update or restart the server frequently, it will restart the timer each time and you never get a backup. I need to change this. Is it possible that would explain the problem?

**Comment by Ylianst** [comment]
Just checked in a fix for the auto-backup system, it will now save in the database the last time a backup was made and make a new backup if last backup is older than "backupintervalhours". The check is done every hour, if a server does an auto-update (if enabled) then the backup will occur one hour later.

**Comment by Ylianst** [comment]
MeshCentral v0.5.3 is out. Should fix this problem.

**Comment by tradexsrl** [comment]
ah ok , i have setup a restart each day a 10 pm....
i'll try the 0.5.3
thank's

**Comment by Ylianst** [comment]
That makes sense if there is an automatic server restart. 0.5.3 should fix this.

**Comment by tradexsrl** [comment]
yes seems it works.
at the moment i have only 3 backup dated 17th - 18th -19th of april

**Comment by Ylianst** [comment]
Thanks. I will close this. Please open a new issue if you spot anything wrong.
