### ISSUE TITLE
Feature Request - Remote Printing

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1123]
Remote printing from the computer you are logged into and able to print locally

**Comment by ryanblenis** [comment]
Are you referring to a RDP session via MeshRouter or MeshCMD, or from the browser session's "Remote Desktop" printing to the admin's controlling computer?

**Comment by CCWTech** [comment]
While in a desktop remote session using Mesh Central. Similar as you can with Team-viewer, Remote desktop, Splashtop, etc.

**Comment by ryanblenis** [comment]
While it wouldn't be impossible, given the session is in a browser I would think the MeshAgent would need to create some sort of psuedo-printer that, when printed to, appeared as a download or attachment in the MC user's browser to download/print. I would assume it's just easier for an admin to grab the file off the "Files" tab and print it from there. But I'll let @Ylianst comment on the possibility of that happening or if he has a better implementation idea.

**Comment by Ylianst** [comment]
So, even if it is possible using native software, it's not going to be a priority given how many items have already on the todo list. You can RDP using MeshCentral Router and then print using that. If someone want to contribute this feature to the project, that would be great, but I don't plan to work on this anytime soon.

**Comment by PathfinderNetworks** [comment]
It might not be too difficult to do it a similar way Splasthop does it. All they do is install a 'printer' on the remote device (the device you are remoting in to).  When anything is sent to that printer it converts it to a XPS file.  That file is then sent, via file transfer, to the viewing PC where it's opened as a print job and sent to whatever printer the user chooses.  Obviously that will all only work in a Windows environment.  But the idea is fairly straightforward- just print the document to a file, send the file via file transfer to the viewing PC, where the viewing PC then opens it and prints it to a local printer.

**Comment by CCWTech** [comment]
That would be great!

**Comment by si458** [comment]
closing this as this wont be implemented, this is a very advanced request!
