### ISSUE TITLE
Feature request - MC agent/router proxy support

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1124]
Never mind, already asked and answered here #321 

I'm getting too old...sorry!

**Comment by Ylianst** [comment]
So, the MeshAgent and MeshCentral Router both support HTTP proxies. In the case of the MeshAgent, when installing it will create a "meshagent.proxy" file at the same place as the MeshAgent executable with the location of the HTTP proxy. The MeshCentral Router just uses the currently setup system proxy. Hope that works.
