### ISSUE TITLE
Regarding Mesh agent not showing on dashboard even after successfully installed on remote desktop

### ISSUE THREAD

**Issue by yogesh2312-more** [Ylianst/MeshCentral#1128]
Hello
I have made setup for own meashcentral server with AWS Linux 2 platform. 
Installation part has done, meshcentral accessible with web server with my domain name, I am able to create device group but having some difficulty at the time of see agent at dashboard. 
As i installed mesh agent exe in remote desktop, it can installed smoothly but i am not able see agent on dashboard. 
I tried on windows as well as on Linux.
Please suggest me for same.

**Comment by krayon007** [comment]
How did you install the agent? It sounds like it may have been installed without a configuration.

**Comment by yogesh2312-more** [comment]
I just made some  changes In config.json like Servername under domain section.Can you please  share here what more  changes i should need to do?On 8 Apr 2020 20:16, Bryan Roe <notifications@github.com> wrote:
How did you install the agent? It sounds like it may have been installed without a configuration.

**Comment by yogesh2312-more** [comment]
I have downloaded exe.  from device group under which i want to add agent.Then this exe has been installed in remote system.Further as i have checked in remote system where i installed exe there is file meshcentral.msh in that i found  meshserver = local Which seems unexpected.On 8 Apr 2020 20:16, Bryan Roe <notifications@github.com> wrote:
How did you install the agent? It sounds like it may have been installed without a configuration.

**Comment by yogesh2312-more** [comment]
MeshName=xxxxx
MeshType=x
MeshID=xxxxxxxxxxxxxxxxxxxxx494B28B46DADD4C0973407D035B853B9809664CED88CA314C973Bxxxxxxxxxxxxx
ServerID=xxxxxxxxxxxxxxxxxxxxx33853352E70FAA9CB4057455462593817876FC0F094E857D71C3BD115E1Cxxxxxxxxxxxxxxxxxxxxx
MeshServer=**local**
ignoreProxyFile=1


Here in meshagent.msh file  i found MeshServer= local

**Comment by Ylianst** [comment]
So, your MeshCentral server is in "LAN mode", in this mode, the MeshAgent will multicast on the local network to find the server. If your agent is on a different network, this will not work. To move the server to "Hybrid mode" or "WAN mode" where the agent will connect to a known server DNS, you need to add the following line in the settings section of config.json, for example:

`"cert": "mesh.server.example.com"`

When you next run MeshCentral, it will regenerate it's certificate and have agent connect to `https://mesh.server.example.com:443` to connect to the server. If you need more help, please indicate that config.json you are using and xxx out any private information.

Hope that helps,
Ylian

**Comment by yogesh2312-more** [comment]
My meshcentral server is in WAN mode only but i have addeed line under setting section at first line  in config.json is:
  
"cert": "abc.example.com"  but you given line is "cert": "mesh.server.example.com"

Keeping here my config.json file:

{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "_Cert": **"xxx.xxx.com",**
    "_MongoDb": "mongodb://127.0.0.1:27017",
    "_MongoDbName": "meshcentral",
    "_MongoDbChangeStream": true,
    "_MongoDumpPath": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongodump.exe",
    "WANonly": true,
    "_LANonly": true,
    "_Minify": 1,
    "_SessionTime": 30,
    "_SessionKey": "MyReallySecretPassword1",
    "_SessionSameSite": "strict",
    "_DbEncryptKey": "MyReallySecretPassword2",
    "_DbRecordsEncryptKey": "MyReallySecretPassword",
    "_DbRecordsDecryptKey": "MyReallySecretPassword",
    "__DbExpire": "Amount of time to keep various events in the database, in seconds. Below are the default values.",
    "_DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    },
    "_Port": 443,
    "_AliasPort": 444,
    "_RedirPort": 80,
    "_ExactPorts": true,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "_AgentInviteCodes": true,
    "_WebRTC": false,
    "_Nice404": false,
    "_ClickOnce": false,
    "_SelfUpdate": true,
    "_AgentPing": 60,
    "_AgentPong": 60,
    "_AgentIdleTimeout": 150,
    "_MeshErrorLogPath": **"/var/log/",**
    "_NpmPath": "c:\\npm.exe",
    "_NpmProxy": "http://1.2.3.4:80",
    "_AllowHighQualityDesktop": true,
    "_UserAllowedIP": "127.0.0.1,0.0.0.0/0",
    "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
    "_AgentAllowedIP": "106.210.205.282",
    "_AgentBlockedIP": "127.0.0.1,::1",  
    "_AuthLog": **"/var/log/",**
    "_LocalDiscovery": {
      "name": **"xxx.xxx.com"**,
      "info": "Information about this server"
    },
    "_TlsOffload": "127.0.0.1",
    "_TrustedProxy": "127.0.0.1",
    "_MpsPort": 44330,
    "_MpsAliasPort": 4433,
    "_MpsAliasHost": "mps.mydomain.com",
    "_MpsTlsOffload": true,
    "_No2FactorAuth": true,
    "_Log": "main,web,webrequest,cert",
    "_WebRtConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    },
    "_AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "zipPassword": "MyReallySecretPassword3",
      "_backupPath": "C:\\backups"
    },
    "_Redirects": {
      "meshcommander": "https://www.meshcommander.com/"
    },
    "__MaxInvalidLogin": "Time in minutes, max amount of bad logins from a source IP in the time before logins are rejected.",
    "MaxInvalidLogin": { "time": 10, "count": 10, "coolofftime": 10 },
    "Plugins": {
        "enabled": true
    }
  },
  "_domains": {
    "": {
      "Title": "MyServer",
      "Title2": "xxx.xxx.com",
      "_TitlePicture": "title-sample.png",
      "_UserQuota": 1048576,
      "_MeshQuota": 248576,
      "_NewAccounts": 1,
      "_UserNameIsEmail": true,
      "_NewAccountEmailDomains": [ "sample.com" ],
      "_NewAccountsRights": [ "nonewgroups", "notools" ],
      "_ManageAllDeviceGroups": [ "admin" ],
      "_WelcomeText": "Sample Text on Login Page.",
      "_WelcomePicture": "mainwelcome.jpg",
      "_Footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
      "_CertUrl": "https://192.168.2.106:443/",
      "_PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true, "skip2factor": "127.0.0.1,192.168.2.0/24" },
      "_AgentNoProxy": true,
      "_GeoLocation": true,
      "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
      "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
      "_AgentAllowedIP": "0.0.0.0/0,106.210.205.181,192.168.0.100/24",
      "_AgentBlockedIP": "127.0.0.1,::1",
      "___UserSessionIdleTimeout__" : "Number of user idle minutes before auto-disconnect",
      "_UserSessionIdleTimeout" : 30,
      "__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
      "_UserConsentFlags" : 7,
      "_Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      },
      "_AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
      "_Redirects": {
        "meshcommander": "https://www.meshcommander.com/"
      },
      "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
      "_httpheaders": {
        "Strict-Transport-Security": "max-age=360000",
        "x-frame-options": "SAMEORIGIN",
        "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
      },
      "_agentConfig": [ "webSocketMaskOverride=1" ],
      "_SessionRecording": {
        "_filepath": "C:\\temp",
        "_index": true,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
      }
    },
    "_customer1": {
      "_DNS": "customer1.myserver.com",
      "_Title": "Customer1",
      "_Title2": "TestServer",
      "_NewAccounts": 1,
      "_Auth": "sspi",
      "_Footer": "Test",
      "_CertUrl": "https://192.168.2.106:443/"
    },
    "_info": {
      "_share": "C:\\ExtraWebSite"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 10.12 or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@myserver.com",
    "names": "myserver.com,customer1.myserver.com",
    "rsaKeySize": 3072,
    "production": false
  },
  "_peers": {
    "serverId": "server1",
    "servers": {
      "server1": { "url": "**wss://xxx.xxx.com:443**/" },
      "server2": { "url": "wss://192.168.1.106:443/" }
    }
  },
  "_smtp": {
    "host": "smtp.myserver.com",
    "port": 25,
    "from": "myemail@myserver.com",
    "__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
    "tls": false,
    "___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
    "_tlscertcheck": false,
    "__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
    "_tlsstrict": true
  }
}

**Comment by yogesh2312-more** [comment]
Please let me know what more change i should need to do at server side

**Comment by Ylianst** [comment]
If I remove all the lines are start with _ and so, are ignored, your config.json looks like this:

```
{
  "settings": {
    "WANonly": true
  }
}
```

This is not going to work as your server has no name specified by "cert". Again, all lines and sections that start with a underscore (_) are ignored.

**Comment by yogesh2312-more** [comment]
> My meshcentral server is in WAN mode only but i have addeed line under setting section at first line in config.json is:
> 
> "cert": "abc.example.com" but you given line is "cert": "mesh.server.example.com"
> 
> Keeping here my config.json file:
> 
> {
> "**comment**" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
> "settings": {
> "_Cert": **"xxx.xxx.com",**
> "_MongoDb": "mongodb://127.0.0.1:27017",
> "_MongoDbName": "meshcentral",
> "_MongoDbChangeStream": true,
> "_MongoDumpPath": "C:\Program Files\MongoDB\Server\4.2\bin\mongodump.exe",
> "WANonly": true,
> "_LANonly": true,
> "_Minify": 1,
> "_SessionTime": 30,
> "_SessionKey": "MyReallySecretPassword1",
> "_SessionSameSite": "strict",
> "_DbEncryptKey": "MyReallySecretPassword2",
> "_DbRecordsEncryptKey": "MyReallySecretPassword",
> "_DbRecordsDecryptKey": "MyReallySecretPassword",
> "__DbExpire": "Amount of time to keep various events in the database, in seconds. Below are the default values.",
> "_DbExpire": {
> "events": 1728000,
> "powerevents": 864000,
> "statsevents": 2592000
> },
> "_Port": 443,
> "_AliasPort": 444,
> "_RedirPort": 80,
> "_ExactPorts": true,
> "_AllowLoginToken": true,
> "_AllowFraming": true,
> "_AgentInviteCodes": true,
> "_WebRTC": false,
> "_Nice404": false,
> "_ClickOnce": false,
> "_SelfUpdate": true,
> "_AgentPing": 60,
> "_AgentPong": 60,
> "_AgentIdleTimeout": 150,
> "_MeshErrorLogPath": **"/var/log/",**
> "_NpmPath": "c:\npm.exe",
> "_NpmProxy": "http://1.2.3.4:80",
> "_AllowHighQualityDesktop": true,
> "_UserAllowedIP": "127.0.0.1,0.0.0.0/0",
> "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
> "_AgentAllowedIP": "106.210.205.282",
> "_AgentBlockedIP": "127.0.0.1,::1",
> "_AuthLog": **"/var/log/",**
> "_LocalDiscovery": {
> "name": **"xxx.xxx.com"**,
> "info": "Information about this server"
> },
> "_TlsOffload": "127.0.0.1",
> "_TrustedProxy": "127.0.0.1",
> "_MpsPort": 44330,
> "_MpsAliasPort": 4433,
> "_MpsAliasHost": "mps.mydomain.com",
> "_MpsTlsOffload": true,
> "_No2FactorAuth": true,
> "_Log": "main,web,webrequest,cert",
> "_WebRtConfig": {
> "iceServers": [
> { "urls": "stun:stun.services.mozilla.com" },
> { "urls": "stun:stun.l.google.com:19302" }
> ]
> },
> "_AutoBackup": {
> "backupIntervalHours": 24,
> "keepLastDaysBackup": 10,
> "zipPassword": "MyReallySecretPassword3",
> "_backupPath": "C:\backups"
> },
> "_Redirects": {
> "meshcommander": "https://www.meshcommander.com/"
> },
> "__MaxInvalidLogin": "Time in minutes, max amount of bad logins from a source IP in the time before logins are rejected.",
> "MaxInvalidLogin": { "time": 10, "count": 10, "coolofftime": 10 },
> "Plugins": {
> "enabled": true
> }
> },
> "_domains": {
> "": {
> "Title": "MyServer",
> "Title2": "xxx.xxx.com",
> "_TitlePicture": "title-sample.png",
> "_UserQuota": 1048576,
> "_MeshQuota": 248576,
> "_NewAccounts": 1,
> "_UserNameIsEmail": true,
> "_NewAccountEmailDomains": [ "sample.com" ],
> "_NewAccountsRights": [ "nonewgroups", "notools" ],
> "_ManageAllDeviceGroups": [ "admin" ],
> "_WelcomeText": "Sample Text on Login Page.",
> "_WelcomePicture": "mainwelcome.jpg",
> "_Footer": "[Twitter](https://twitter.com/mytwitter)",
> "_CertUrl": "https://192.168.2.106:443/",
> "_PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true, "skip2factor": "127.0.0.1,192.168.2.0/24" },
> "_AgentNoProxy": true,
> "_GeoLocation": true,
> "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
> "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
> "_AgentAllowedIP": "0.0.0.0/0,106.210.205.181,192.168.0.100/24",
> "_AgentBlockedIP": "127.0.0.1,::1",
> "_**UserSessionIdleTimeout**" : "Number of user idle minutes before auto-disconnect",
> "_UserSessionIdleTimeout" : 30,
> "**UserConsentFlags**" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
> "_UserConsentFlags" : 7,
> "_Limits": {
> "_MaxDevices": 100,
> "_MaxUserAccounts": 100,
> "_MaxUserSessions": 100,
> "_MaxAgentSessions": 100,
> "MaxSingleUserSessions": 10
> },
> "_AmtAcmActivation": {
> "log": "amtactivation.log",
> "certs": {
> "mycertname": {
> "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
> "keyfile": "amtacm-leafcert.key"
> }
> }
> },
> "_Redirects": {
> "meshcommander": "https://www.meshcommander.com/"
> },
> "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
> "_httpheaders": {
> "Strict-Transport-Security": "max-age=360000",
> "x-frame-options": "SAMEORIGIN",
> "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
> },
> "_agentConfig": [ "webSocketMaskOverride=1" ],
> "_SessionRecording": {
> "_filepath": "C:\temp",
> "_index": true,
> "**protocols**": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
> "protocols": [ 1, 2, 101 ]
> }
> },
> "_customer1": {
> "_DNS": "customer1.myserver.com",
> "_Title": "Customer1",
> "_Title2": "TestServer",
> "_NewAccounts": 1,
> "_Auth": "sspi",
> "_Footer": "Test",
> "_CertUrl": "https://192.168.2.106:443/"
> },
> "_info": {
> "_share": "C:\ExtraWebSite"
> }
> },
> "_letsencrypt": {
> "**comment**": "Requires NodeJS 10.12 or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
> "email": "[myemail@myserver.com](mailto:myemail@myserver.com)",
> "names": "myserver.com,customer1.myserver.com",
> "rsaKeySize": 3072,
> "production": false
> },
> "_peers": {
> "serverId": "server1",
> "servers": {
> "server1": { "url": "**wss://xxx.xxx.com:443**/" },
> "server2": { "url": "wss://192.168.1.106:443/" }
> }
> },
> "_smtp": {
> "host": "smtp.myserver.com",
> "port": 25,
> "from": "[myemail@myserver.com](mailto:myemail@myserver.com)",
> "**tls**": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
> "tls": false,
> "_**tlscertcheck**": "When set to false, the TLS certificate of the SMTP server is not checked.",
> "_tlscertcheck": false,
> "**tlsstrict**": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
> "_tlsstrict": true
> }
> }

**Comment by yogesh2312-more** [comment]
> If I remove all the lines and sections that start with _ and so, are ignored, your config.json looks like this:
> 
> ```
> {
>   "settings": {
>     "WANonly": true
>   }
> }
> ```
> 
> This is not going to work as your server has no name specified by "cert". Again, all lines and sections that start with a underscore (_) are ignored. When you start MeshCentral, it will tell you the mode like this:
> 
> ```
> MeshCentral HTTP redirection server running on port 80.
> MeshCentral v0.5.1-k, Hybrid (LAN + WAN) mode.
> MeshCentral Intel(R) AMT server running on xxx.meshcentral.com:4433.
> MeshCentral HTTPS server running on xxx.meshcentral.com:443.
> ```
> 
> For a quick overview of how to install MeshCentral, [take a look here](https://www.npmjs.com/package/meshcentral).

Can you look here for minute for confirming below config.json file is correct or not?


{
        "settings": {
            "Cert": "mesh.xxx.xxx.com",
            "WANonly": true,
            "port": 443,    
        },
        "domains": {
            "": {
                "title": "MyServer",
                "title2": "xxx.xxx.com",
                "userQuota": 1048576,
                "meshQuota": 248576,
                "newAccounts" : 1
            }
        }
  }

**Comment by Ylianst** [comment]
This config.json looks a lot better, but you have an extra comma at the end of the `"port":443` line that must be removed. This should work:

```
{
  "settings": {
    "Cert": "mesh.xxx.xxx.com",
    "WANonly": true,
    "port": 443
  },
  "domains": {
    "": {
      "title": "MyServer",
      "title2": "xxx.xxx.com",
      "userQuota": 1048576,
      "meshQuota": 248576,
      "newAccounts": 1
    }
  }
}
```
