### ISSUE TITLE
Cursor displays as question mark

### ISSUE THREAD

**Issue by PTR-inc** [Ylianst/MeshCentral#1131]
Hi,
Don't know since which specific update this is happening, but recently in both my meshcentral installs, windows server at 0.5.1-k and linuxserver at 0.5.1-j, the cursor is a question mark instead of the arrow in the desktop view and doesn't change.
And it's not the arrow with questionmark, but only the question mark, so it's quite difficult to resize windows.

Tested it in different browsers on different platforms (macos & windows), but all show the same issue. Sometimes if I click in a textbox or mouseover the startmenu, it changes and it works fine from then on, but this does not happen much.
Success rate seems higher on the windows platform. All agents are windows, mostly windows 10 LTSC 1809 64-bit. But is also happens with server 2016 and windows 10 pro 1909.

**Comment by Ylianst** [comment]
I am seeing this too, on the desktop I see the mouse cursor a little like this below. Let me know if you see the same.

![x](https://user-images.githubusercontent.com/1319013/78873791-4128c100-7a00-11ea-94a9-e1c4a5a0108b.png)

**Comment by krayon007** [comment]
The macOS agent does not support mouse cursor tracking, so it would never send a cursor update to the browser. I'll see if I can figure out what would cause this, as I have never seen that specific cursor. @Ylianst he said he was seeing a question mark cursor, not the arrow with question mark.

**Comment by Ylianst** [comment]
Investigating this now... I see the same on all remote desktops, Windows and Linux.

**Comment by krayon007** [comment]
Just to clarify, the issue we are seeing is the arrow/question pointer that ylian posted above, showing when you first connect. I know the cause of that specific issue, and will fix that tomorrow. Not sure about the OP's issue. I'll have to keep thinking about that one.

**Comment by PTR-inc** [comment]
<img width="317" alt="curs" src="https://user-images.githubusercontent.com/47147771/78881011-811a9300-7a56-11ea-92a1-d30b35a24141.png">


This is the cursor on macos with vivaldi on a windows agent desktop.

**Comment by krayon007** [comment]
So if I'm understanding you correctly, you are using Vivaldi Browser on macOS, and connecting to a windows agent? What other browsers have you tried? Have you tried Safari? What it sounds like might be going on, is that the web app is asking the browser to set the local cursor, but vivaldi doesn't know what that cursor is, and gives you a question mark.  I just tried Safari on Catalina, and connected to my various agents, and the cursor shows correctly in the browser.

After I fix the issue I mentioned earlier, I can see if I can install Vivaldi, and see if I can reproduce your issue.

**Comment by PTR-inc** [comment]
Tried it with safari and firefox, both the same. I'm still on mojave btw. Hopefully your fix will fix this

**Comment by uldiseihenbergs** [comment]
i'm seeing this as well.
i'm on Ubuntu desktop, and connecting to Windows/Ubuntu agents.
for me, it shows Asterisk symbol, but upside down :) sometimes it repaints immediately after a sec. to normal arrow after connection, sometimes stay.

**Comment by krayon007** [comment]
Can you try with server version 0.5.1-m? I fixed the behavior so that it queries the cursor on connection (previously it only queries the cursor on system cursor change events).

**Comment by PTR-inc** [comment]
Yes! It is fixed :-)
Thank for the quick response, fix and a great tool!
