### ISSUE TITLE
How to take RDP Access of the system using meshctrl.js?

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1132]
I have tried below command to take Remote Control
node ./node_modules/meshcentral/meshctrl remotecontrol  -id YHyh5f$0BwVk4ZBr1Xckb4CqK0WRqCycim1pScMajGN6o2@aAPdbeg84EMOvcd7A --url wss://localhost/ 
--loginuser "admin" --loginpass "admin"

and getting  the following Msg

Invalid command. Possible commands are: listusers, listdevicegroups, listdevices like that.

**Comment by Ylianst** [comment]
MeshCtrl.js is not a routing tool, it's a tool to manage a MeshCentral server. For routing, you need to use MeshCMD or MeshCentral Router. It's available for download at the bottom of the devices page or click on a device and look for "Router" at the bottom.

**Comment by aimdharma1990** [comment]
> MeshCentral Router

Hi, 

Thanks for quick update. But i couldn't to take terminal of the target system where the mesh agent is installed. This tools are using for port mapping alone.. Anything Am i missing on this?
