### ISSUE TITLE
Config Password criteria/complexity to match exiting organization passwords   

### ISSUE THREAD

**Issue by aa-london** [Ylianst/MeshCentral#1133]
Hi 
As first time users, More likely testing the ability to use Mash commander to work with Intel AMT in similar way to iDRAC. we fail on the first step of adding computers due to Password complexity not complied with Mash criteria. 
1- Is it possible to amend the criteria to work with out existing passwords?
2- Can Mash work with Intel AMT to give us enter to Computer BIOS screen and make changes in it?

Kind Regards.
Guy Michaelov

**Comment by jsastriawan** [comment]
1. Meshcommander password complexity is the standard requirement of AMT password requirement. Most likely if you cannot apply your password to Meshcommander you also cannot apply the same password to AMT itself.
2. Yes. There are two options. You can use Remote Desktop and Reboot to BIOS power command or Serial over LAN and Reboot to BIOS. The difference is Serial over LAN use text mode BIOS which is preferable for low bandwidth situation.

**Comment by aa-london** [comment]
Many thanks.
Probably easer to go and setup AMT credentials upon rebuilding a PC, without any connection to the users that use it. Avoiding disruption to existing staff.

At this time (before knowing the full potential of Mash) we like to focus on remote access to workstation BIOS either way.
One case we have the remote PC ON and like to reboot to BIOS. (RDT to BIOS)
Second case PC is Off (with WOL able)or worth PC that not starting properly and got stuck before Win loading. (Serial over LAN and Reboot to BIOS)

PS: what the best way to configure AMT and can we have these sating in cfg file to copy over different PCs?

Regards

Guy Michaelov

**Comment by Ylianst** [comment]
@jsastriawan is correct. For configuring Intel AMT, it depends on the number of computers you have and that software you plan to use to manage them.

I did not realize it at the time, but since the question is MeshCommander related, please use the [MeshCommander GitHub](https://github.com/Ylianst/MeshCommander/issues) in the future.
