### ISSUE TITLE
how to connect to client through internet ?

### ISSUE THREAD

**Issue by changchichung** [Ylianst/MeshCentral#114]
I want to connect many clients from different sites without VPN , 
should I config NAT rule on firewall for each client I want to connect ?
or I just open a port forwarding to my meshcentral server , and use server`s public ip on client ? if so , which port should I mapping ?

**Comment by Ylianst** [comment]
Hi. MeshCentral uses normal web server ports 80 (HTTP) and 443 (HTTPS). The agents will connect to port 443 on the server just like browsers. Put your server on a public IP address and allow ports 80 and 443 to reach the server. Agent's will connect to the server, so generally, no firewalls/NAT rules are needed on the clients. Hope it helps.

**Comment by changchichung** [comment]
I will try that , thanks for quick reply !
