### ISSUE TITLE
Readabilty translated text (and original)

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1141]
as stated in the translation files:
the above line of text (txt1) has an space in the text after 3. , that is better readable than the text (txt2) 

That has more lines of text, is it possible to merge that kind off lines into 1 instead of 2? it cleans up the translate.json 

(txt1)
"en": "3. Neither the name of CodePlex Foundation nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.",

(txt2)
    {
      "en": "3.Neither the name of CodePlex Foundation nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.",
      "xloc": [
        "terms-mobile.handlebars->container->page_content->column_l->19->1",
        "terms.handlebars->container->column_l->19->1"

example of possible double text ?
![Screenshot_8](https://user-images.githubusercontent.com/58996467/79042928-0b502c00-7bfc-11ea-8b73-8d80fbf3ff70.jpg)

**Comment by Ylianst** [comment]
Oh, you are correct. I want to get remove all "{1} = s" situations in the code. I will do this later today.

**Comment by petervanv** [comment]
nice, but did you understand what i meant with the other line's ? if nessary i can screeshot that too

**Comment by Ylianst** [comment]
For txt1, what do you think if I did not translate the "Terms of use" page? Maybe this is not necessary? I can still add the missing space to the English page.

**Comment by petervanv** [comment]
my idea is to still use the terms page, but wit an space next to the dot en the next letter (3. abcd) in all the lines of the text

**Comment by Ylianst** [comment]
Just checked in improvements in GitHub. Note that if translation text does not have a "xloc" enter, that indicated that it's not used. If there is no plan to use that string in the future, we can remove it. Let me know if this is ok. Thanks.

**Comment by petervanv** [comment]
#1145 added latest untranslated string refering to in this issue
