### ISSUE TITLE
Delete devices not working

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1143]
![delete](https://user-images.githubusercontent.com/29974944/79052290-a0234b80-7c35-11ea-83be-ce7fa1446fd0.gif)

MC 0.5.1-m

It's just my installation?
Other group actions seem to be ok tough.
Thanks

**Comment by Ylianst** [comment]
Your right, fixed in MeshCentral v0.5.1-n. Thanks for reporting this!

**Comment by amenolo** [comment]
Working again, now 👍
