### ISSUE TITLE
Error After Upgrade - Blank Page

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#1144]
MC Version: 0.5.1-n
SO: Ubuntu 18.04

Attach Vídeo and Logs
![Meshcentral Version](https://user-images.githubusercontent.com/8115433/79058714-fa70dc00-7c36-11ea-8829-65f74950cdc4.png)
![Login Log](https://user-images.githubusercontent.com/8115433/79058715-fba20900-7c36-11ea-9017-b04141a67f3a.png)
![Login Log 2](https://user-images.githubusercontent.com/8115433/79058716-fc3a9f80-7c36-11ea-84b8-f16974e8441c.png)
![Service Status](https://user-images.githubusercontent.com/8115433/79058717-fc3a9f80-7c36-11ea-95f8-c577a565aaa9.png)

**Comment by FrankSanabria** [comment]
![2020-04-11_20-48-40](https://user-images.githubusercontent.com/8115433/79058819-407a6f80-7c38-11ea-83f0-4d52b7694cec.gif)

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-o with a fix for this. The Spanish translation had a problem. You can add "?lang=en" to the URL to switch to English, then update and go back to Spanish. Let me know if it works.

**Comment by FrankSanabria** [comment]
Hi, Thank you, yes this fixed with new update.

**Comment by nroach44** [comment]
@FrankSanabria Can I ask how you got the "Accepted password for..." to show in the journal/syslog for Meshcentral? I've just done a bit of a deep dive and can't see how you did it
