### ISSUE TITLE
[Question] WebUI: nodes object properties

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1148]
Hi @Ylianst,

In the UI, the nodes object contains 3 separate IP related properties: `ip`, `host`, and in some cases, `publicip`

`ip` and `host` are always the same, and if `publicip` exists, it is undefined.

1. Assuming the null and duplicate values aren't intended, what are the intended values of each?

Side note: I came across this while working on custom column layouts and trying to get the LAN IP easily, which I assumed might be here. I've found them in the `if[nodeid].netif` entries, but figured I'd ask the intended use of these for future consideration.

2. On some nodes, the `agct` variable exists with the last connection time, sometimes it does not. I'm currently using the `lc[nodeid]` types for this info, but wanted to make sure this was preferred, or what rules define when `agct` is available or not.

Thank you in advance!

**Comment by Ylianst** [comment]
`node.host` should contain the name or IP address to use to connect to that device on the local network. If the server is in WAN-only mode, I hide this value. In LAN or Hybrid, I show it in the web app and allow users to set it. This value is not really useful except for Intel AMT, when the server needs to connect to the device (not typical).

`node.name` is the server side name and `node.rname` is the remote computer name. At first, the `node.name` is set to the computer name, but the administrator can change it.

`node.ip` is the last IP address that the agent had when connecting to the server. 

'node.publicip` and `node.iploc` are used for device IP location. I have not used this feature much and need to do some clean up. In theory, you can ask a service where a public ip is on a map and record that location for that device.

**Comment by Ylianst** [comment]
`lc[nodeid]` is probably the right way to go, I am not sure I use `node.agct` anymore.

**Comment by Ylianst** [comment]
FYI. I have been working on allowing user groups to be attached the individual devices. I think that will be the last big access control feature that affects how the core of the server works and grants permissions.

**Comment by ryanblenis** [comment]
Thank you very much for the info!
