### ISSUE TITLE
Black Screen remote desktop

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#115]
Black screen on windows 10 Pro Clients when remote viewing. The server is ubuntu 18.04 with stock database with about 25 clients. When I hit connect all and view all desktop they all black out after some random amount of minutes and i have to refresh browser this same thing happens with a single desktop connection. I'm using the latest version of chrome on ubuntu 19.04. Is this normal or a known bug. Thanks

**Comment by krayon007** [comment]
Can you provide some more details about your setup? Do the other aspects of the client work, such as terminal and files? (This is to see if the client is able to initiate websocket data channel to the server) 
Is Microsoft RDP Session active on the client. If you click on the 'console' tab of the client, and type "info", what is the full windows version reported?

**Comment by johnnyq** [comment]
I see so this is not normal. I thought it was some timeout. But I do not use a reverse proxy. Ill do some more research on my end and post back

**Comment by Ylianst** [comment]
Next time the screen goes black, if you can go in the browser console and see if there are any error messages. In FireFox Ctrl-Shift-K, in Chrome "Developer Tools" and "Console". The console may be blank, but if there are any error messages, that would be great to know.

Also, when it goes black, does the "Connect" button shows "Disconnect" or it returns to "Connect".

Thanks,
Ylian

**Comment by johnnyq** [comment]
It happened again, ill record the debug console next time. It looks like its happening on ubuntu linux desktop 18.04 with latest google chrome. I have a windows 10 computer with chrome and it did not black screen. It does show the connect button but when pressed it doesn't do anything so I have to refresh the page. Ill do some more testing, im going to test with firefox on linux to see if it does the same thing.

**Comment by krayon007** [comment]
Are you remoting  to Ubuntu 18.04 or from Ubuntu 18.04? If it's the former, are any users currently logged in? There is a known issue where starting with Ubuntu 18.04, XWayland does not allow connections to X when no user is logged in.

I should be displaying an error dialog in that case, but I can double check that...

**Comment by volchanskyi** [comment]
A similar issue(black screen) but with HW connect. Server Ubuntu 18.04. 10 clients. AMT host Windows 10 pro x64, client Windows 7 pro x64. The developer console doesn't have any error messages. HW connect for terminal doesn't work either. The connect button returns to HW connect in 5 to 7 seconds.   HW connect works fine on other amt hosts.

agent info:
> info
Current Core: MeshCore v6.
Agent Time: 2019-03-05 22:22:48.527-08:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://x.x.x.x:443/agent.ashx.
Built-in LMS: Connected.
OS: Microsoft Windows [Version 10.0.17134.590].
Modules: amt-lme, amt-mei, amt-scanner, amt-wsman-duk, amt-wsman, amt-xml, amt, clipboard, monitor-border, monitor-info, power-monitor, process-manager, service-manager, smbios, toaster, user-sessions, wifi-scanner-windows, wifi-scanner, win-console, win-message-pump, win-registry, win-terminal.
Server Connection: true, State: 1.
lastMeInfo: {"ver":"11.8.50","state":2,"flags":4,"uuid":"4c4c4544-0037-5110-8056-c7c04f305432"}.

**Comment by GusevVictor** [comment]
Dear all, I have the same problem with version 0.4.9-o. Please fix that. Please please please.

Mesh agent is v 0.2.1.3 (Win7/Win10)

**Comment by GusevVictor** [comment]
I suppose there is problem with Apache proxy. I have tune it and wait for that problem again.

**Comment by CCWTech** [comment]
Same thing here. Terminal, files, etc. all work. I can use tools to restart the mesh service and that fixes the issue.

**Comment by SomeGuru** [comment]
This should be fixed in the current version of the server... Can this be checked and closed if the issue is resolved?

**Comment by JSuenram** [comment]
@johnnyq 
please close as I can confirm this is fixed....

**Comment by johnnyq** [comment]
Closing this as this has been fixed
