### ISSUE TITLE
GUI minor suggestions

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1150]
- Add confirm checkbox in delete user pop-up (as triggered from inside General user tab)

![immagine](https://user-images.githubusercontent.com/29974944/79141727-a7279680-7dba-11ea-9f9b-95c2291827bf.png)

- Add user groups bulk actions (maybe in to-do list already?)
- Change name of `router` download link inside device tab since leads to meshcmd download and besides make pop-ups' title/description consistent

![immagine](https://user-images.githubusercontent.com/29974944/79145470-01c3f100-7dc1-11ea-8295-821f56ab08e7.png)

![immagine](https://user-images.githubusercontent.com/29974944/79143776-1b176e00-7dbe-11ea-9560-8d6a71c05285.png)

- Change name of `install` link inside group tab in order to match the one used in My Devices tab (i.e. `Add Agent`)

![immagine](https://user-images.githubusercontent.com/29974944/79144586-801f9380-7dbf-11ea-918e-49a8d11e1ca6.png)

- Add the option to edit username too (even if I assume you would have implemented time ago if feasible with ease...)

Thanks as usual!

**Comment by Ylianst** [comment]
Wow, I just came here to post that I published MeshCentral v0.5.1-s that includes all your suggestions except the last one. You beat me to it. I can do that last one, it's just going to take a some work, it's never been requested before.

![MC2-DeviceUserGroups](https://user-images.githubusercontent.com/1319013/79169269-d3361e00-7da0-11ea-84dc-a9d1d4e02ff4.png)

**Comment by Ylianst** [comment]
For the "edit username", this is going to be problematic since it would change the user's key in the database and a lot of records that have this key would also need to change. This could be risky as the database could end up in an inconsistent state. It's that ok, I would like to not allow use account name change unless it's really important.

I could have the username and userid mismatch, but then your get into a bunch of other issues.

**Comment by amenolo** [comment]
More or less what I supposed, copy that!

BTW I would point out some other minor issues:

1. lack of confirm checkbox in delete `user`/`device group`/`device` pop-up under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79266580-13c49300-7e98-11ea-932d-24c38eb53c9d.png)

 and under device tab also

![immagine](https://user-images.githubusercontent.com/29974944/79281913-146b2280-7eb4-11ea-9c2f-466060e9308c.png)

![immagine](https://user-images.githubusercontent.com/29974944/79281947-2baa1000-7eb4-11ea-80d8-13cd11950991.png)


2. lack of permissions' editing command for `common device groups` sections under the user tab
![immagine](https://user-images.githubusercontent.com/29974944/79268107-85054580-7e9a-11ea-9b66-d0237c88fc29.png)

3. lack of permissions' editing command for sections `common device groups`/`common devices` under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79267132-ea583700-7e98-11ea-87ce-a93ea19ea7dd.png)

(Also I would suggest to swap `common device groups` and `common devices` sections in order to match the listing used under the user tab)

4. the behavior of user/user groups authorizations/permissions management isn't consistent (or maybe It's simply me missing the logic of choice!): under device groups tab I can add both a user and a user group with no rights, under user/user groups tab I can add device group only with no rights, and neither under device tab.

I know when it comes to consistency matters I can be a little nitpicky, sorry... :sweat_smile:

**Comment by amenolo** [comment]
More or less what I supposed, copy that!

BTW I would point out some other minor issues:

1. lack of confirm checkbox in delete `user`/`device group`/`device` pop-up under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79266580-13c49300-7e98-11ea-932d-24c38eb53c9d.png)

 and under device tab also

![immagine](https://user-images.githubusercontent.com/29974944/79281913-146b2280-7eb4-11ea-9c2f-466060e9308c.png)

![immagine](https://user-images.githubusercontent.com/29974944/79281947-2baa1000-7eb4-11ea-80d8-13cd11950991.png)


2. lack of permissions' editing command for `common device groups` sections under the user tab
![immagine](https://user-images.githubusercontent.com/29974944/79268107-85054580-7e9a-11ea-9b66-d0237c88fc29.png)

3. lack of permissions' editing command for sections `common device groups`/`common devices` under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79267132-ea583700-7e98-11ea-87ce-a93ea19ea7dd.png)

(Also I would suggest to swap `common device groups` and `common devices` sections in order to match the listing used under the user tab)

4. the behavior of user/user groups authorizations/permissions management isn't consistent (or maybe It's simply me missing the logic of choice!): under device groups tab I can add both a user and a user group with no rights, under user/user groups tab I can add device group only with no rights, and neither under device tab.

5. the server rights policy No Tools (MeshCmd/Router) seems to be partially ineffective since MeshCmd link remains available inside device tab

![immagine](https://user-images.githubusercontent.com/29974944/79287786-2e613100-7ec5-11ea-8aa3-d9d33e89ee8d.png)

![immagine](https://user-images.githubusercontent.com/29974944/79287928-9152c800-7ec5-11ea-9872-cf9ce6b57aac.png)

Maybe it's the way it's meant to be?

I know when it comes to consistency matters I can be a little nitpicky, sorry... :sweat_smile:

Thanks.

**Comment by Ylianst** [comment]
Thanks for the new reports, all valid. I was hoping you would create a new issue on GitHub so that my "score" at closing issues would increase a bit :)

**Comment by amenolo** [comment]
I wasn't aware of it...sure thing! :+1:

**Comment by Ylianst** [comment]
No worries, otherwise we end up with infinity long issue threads. Thanks for posting a new issue!
