### ISSUE TITLE
Authlog to syslog

### ISSUE THREAD

**Issue by nroach44** [Ylianst/MeshCentral#1157]
Per my super-well-thought out comment on #1144 , can we pretty please have the Authlog's verbosity available to syslog? Rather than just "Account login"

e.g.:
denied password for $user from $ip
accepted password for $user from $ip

Could probably just have a 'auth' option for the syslog setting.

Also if possible, when a user or group is created, can we have the user that created it logged too?

**Comment by Ylianst** [comment]
Yes, I can do this. For user and group creation, can your send the exact syntax you want? Also if you want user and group deletion, the exact syntax for that? Thanks.

**Comment by nroach44** [comment]
Hi Yilan,

Exact syntax doesn't bother me, so something to the effect of
$User $Verb $Group/user
E.g. "NRoach44 deleted the group $User"

I primarily want it logged so that we can go through and audit activities if we need to.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.9 with improved authlog support. Here is a sample...

```
Apr 20 02:24:54 meshcentral http[9660]: Server listening on 0.0.0.0 port 80.
Apr 20 02:24:55 meshcentral mps[9660]: Server listening on 0.0.0.0 port 4433.
Apr 20 02:24:55 meshcentral https[9660]: Server listening on 0.0.0.0 port 443.
Apr 20 02:29:33 meshcentral https[9660]: User admin removed device group xx
Apr 20 02:29:47 meshcentral https[9660]: User admin removed user group Test Group 3
Apr 20 02:29:50 meshcentral https[9660]: User admin created user group aaa
Apr 20 02:29:54 meshcentral https[9660]: User admin removed user group aaa
Apr 20 02:30:37 meshcentral https[10364]: Accepted password for admin from 192.168.2.147 port 62716
Apr 20 02:40:0 meshcentral https[792]: User admin removed user account zz
Apr 20 02:40:12 meshcentral https[792]: User admin created user account zz
```

MeshCentral can generate a file with this content by adding the following in the settings section of config.json:

```
"authlog": "c:\\temp\\auth.log",
```

Or, on Linux, you can get these sent to the syslog by adding this line to the settings section of config.json:

```
"syslogauth": "meshcentral-auth"
```

The name "meshcentral-auth" is up to you, it's the name used when sending data to the syslog.

Hope that helps,
Ylian

**Comment by nroach44** [comment]
Hi Yilan, thanks for the feature!

One slight issue, on Linux at least, this requires authlog to be set to a file - if I set it to /tmp/something, I'll get the login notice:

`Apr 20 18:40:39 debmshc mesh-01[1994]: Accepted password for NRoach44 from <host>  port <port>
`
If I don't set authlog,

`Apr 20 18:41:48 debmshc mesh-01[2026]: Account login`

meshcentral.js tries to open the setting of authlog (meshcentral.js:2324 ), but meshuser.js uses this setting to determine if the extra verbosity is needed:
webserver.js:824:                            if (obj.parent.authlog)

Unfortunately I don't know JS well enough to bodge in a fix

**Comment by nroach44** [comment]
Something that's like (and probably a bit safer) this:

```
947,949c947
<         if (obj.config.settings.authlog === true){
<           obj.authlog = true;
<         } else if (obj.config.settings.authlog != null) {
---
>         if (obj.config.settings.authlog != null) {
2326c2324
<         if ((obj.authlog != null) && (obj.authlog != true)) { // Write authlog to file
---
>         if (obj.authlog != null) { // Write authlog to file
```

**Comment by Ylianst** [comment]
Oh yes, your right, I messed up that feature. I just pushed a fix for this in GitHub, will be in MeshCentral v0.5.10 later today.

**Comment by Ylianst** [comment]
MeshCentral v0.5.10 is published. Should fix this.

**Comment by nroach44** [comment]
Yup, all working! Thanks!
