### ISSUE TITLE
Links to documentation gives 404

### ISSUE THREAD

**Issue by kewi69** [Ylianst/MeshCentral#116]
Links to user and installation guide are dead and only gives 404 as response

**Comment by Ylianst** [comment]
The links works for me, but if anyone else can confirm the links are broken from [this page](https://www.meshcommander.com/meshcentral2) and [this page](https://www.meshcommander.com/). Please state where in the world you are accessing the links from.

Current documents are here: [User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.2.pdf), [Installer's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.6.pdf), [Design & Architecture](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2DesignArchitecture.pdf).

**Comment by Ylianst** [comment]
I am going to close this one. Please reopen if you see a problem.
