### ISSUE TITLE
GUI minor suggestions (2)

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1161]
I would point out some other minor issues:

1. lack of confirm checkbox in delete `user`/`device group`/`device` pop-up under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79266580-13c49300-7e98-11ea-932d-24c38eb53c9d.png)

 and under device tab also

![immagine](https://user-images.githubusercontent.com/29974944/79281913-146b2280-7eb4-11ea-9c2f-466060e9308c.png)

![immagine](https://user-images.githubusercontent.com/29974944/79281947-2baa1000-7eb4-11ea-80d8-13cd11950991.png)

2. lack of permissions' editing command for `common device groups` sections under the user tab
![immagine](https://user-images.githubusercontent.com/29974944/79268107-85054580-7e9a-11ea-9b66-d0237c88fc29.png)

3. lack of permissions' editing command for sections `common device groups`/`common devices` under the user group tab
![immagine](https://user-images.githubusercontent.com/29974944/79267132-ea583700-7e98-11ea-87ce-a93ea19ea7dd.png)

(Also I would suggest to swap `common device groups` and `common devices` sections in order to match the listing used under the user tab)

4. the behavior of user/user groups authorizations/permissions management isn't consistent (or maybe It's simply me missing the logic of choice!): under device groups tab I can add both a user and a user group with no rights, under user/user groups tab I can add device group only with no rights, and neither under device tab.

5. the server rights policy No Tools (MeshCmd/Router) seems to be partially ineffective since MeshCmd link remains available inside device tab

![immagine](https://user-images.githubusercontent.com/29974944/79287786-2e613100-7ec5-11ea-8aa3-d9d33e89ee8d.png)

![immagine](https://user-images.githubusercontent.com/29974944/79287928-9152c800-7ec5-11ea-9872-cf9ce6b57aac.png)

6. user groups and device groups are being ordered by date of creation, not by alphabetical order

![immagine](https://user-images.githubusercontent.com/29974944/79342167-16bd9300-7f2d-11ea-9f1f-da745b5c14d8.png)
![immagine](https://user-images.githubusercontent.com/29974944/79343107-47ea9300-7f2e-11ea-9891-124ff718b322.png)

7. the permissions' editing link layout "extends" till deletion link
![8cVtuHDkig](https://user-images.githubusercontent.com/29974944/79343872-466d9a80-7f2f-11ea-94ad-399bd2e2dcfc.gif)

8. under device tab you have to modify user consent policy every time from scratch in order to apply changes
![5itZBbip5m](https://user-images.githubusercontent.com/29974944/79346740-00b2d100-7f33-11ea-9870-6233676825ba.gif)

As far as I can recall never noticed 6. 7. and 8. before...maybe depends on v0.5.1-u?

Well I know...when it comes to consistency matters I can be a little nitpicky, sorry... :sweat_smile:

Thanks.

_Originally posted by @amenolo in https://github.com/Ylianst/MeshCentral/issues/1150#issuecomment-613757281_

**Comment by Ylianst** [comment]
All excellent requests, working on it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.1-w with a lot of UI fixes. For the first set of confirmation boxes, I changes the text since your are not removing the user/device/group, just removing the permissions and it's reversible. Let me know if that works.

**Comment by amenolo** [comment]
(1.) you're right, my misunderstanding...well done!

(2. 3. & 4.) at first glance issues unchanged, let me try a recap for the sake of clarity:

- inside device tab I can't add user nor user group with no rights/permissions

![RgSPilhu9R](https://user-images.githubusercontent.com/29974944/79458438-1935f080-7ff2-11ea-8e40-4bf1656fa861.gif)

- inside device group tab I can add both user and user group with no rights/permissions, also I can modify rights and remove objects

![PM7gsHsFA7](https://user-images.githubusercontent.com/29974944/79458911-ce68a880-7ff2-11ea-8bef-32b6a67e7e4a.gif)

- inside user/user group tab I can add a device group with no rights/permissions but I can't modify them nor remove object, on the other hand I can't add a device with no rights/permissions, also the deletion of device group is available and effective inside device group link only

![36YUdylGDO](https://user-images.githubusercontent.com/29974944/79460545-43d57880-7ff5-11ea-9dc7-e70c90ffdbd9.gif)

![CwUvrwUG67](https://user-images.githubusercontent.com/29974944/79461818-f5c17480-7ff6-11ea-945e-462464af6a91.gif)

Besides I'm afraid now it popped a bug out: adding an user group to an user results in an `Unknown User Group` object and moreover its deletion is working inside the user groups tab only

![EJN8XlBIuf](https://user-images.githubusercontent.com/29974944/79456884-90b65080-7fef-11ea-92d4-230d0de410a8.gif)

(5. 6. 7. & 8.) now fixed! :+1:

Thanks

**Comment by Ylianst** [comment]
Thanks for reporting, I got more work to do.

**Comment by amenolo** [comment]
In opposite to device name and device groups name, I just noticed that isn't allowed to set user group name with spaces in it:

![immagine](https://user-images.githubusercontent.com/29974944/79614733-7076b680-8101-11ea-9239-c5c38aa30c3a.png)
![immagine](https://user-images.githubusercontent.com/29974944/79615772-c9dfe500-8103-11ea-8eb1-66770d392df7.png)

It seems to me appropriate reporting in here, otherwise I'm gonna open specific issue.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.4 with a bunch of fixes for access control. Should fix all issues reported here. For the group name having a space, could you file a different issue for this? I want to try to avoid having issues embedded within other issues, I can't track them anymore :)

**Comment by amenolo** [comment]
You already warned me about...and everytime it seems to me better to group similar issues than to "spam" a new one every time...sorry!

Going to check new release, thanks!

**Comment by Ylianst** [comment]
It's ok, no worries. You can group many similar issues in one issue, but it's hard to keep up if the issues are added afterwards. I am pretty happy with the latest release, did a lot of access control and UI fixing.

**Comment by amenolo** [comment]
BTW all issues fixed, awesome! 👍

**Comment by Ylianst** [comment]
Nice, thanks! Feel free to close we it's fixed :)
