### ISSUE TITLE
Cannot add agents - broken link....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1162]
Strange issue. I updated server version 2 days ago to 0.5.1-t - BTW there is no trace when exactly I updated it and from which version to which..... (however, it was one of the recent ones.)
Today I connected to Ubuntu 18 using MC to desktop, installed updates, and restarted Ubuntu client machine - after restart no Desktop tab on MC for Ubuntu machine........ 

Another issue - tried to add agent to WS2019 via Add Agent link in one of the groups - installed it, but it never appeared on MC. After closer checking MeshAgent have some strange link - see below:
![image](https://user-images.githubusercontent.com/59362521/79322580-f083fd00-7f04-11ea-85d5-cdb69342f3c3.png)
First port in link 444 is the correct one, as I running MC on port 444, but the second one .......
Please advise.

**Comment by amenolo** [comment]
Why don't u give a try to v0.5.1-u meanwhile?

Just for the record I just replicated your scenarios with MC v0.5.1-t and at first sight none of that issues have been encountered.

**Comment by amenolo** [comment]
Out of curiosity tried briefly second scenario too: seems all right in my case...

![immagine](https://user-images.githubusercontent.com/29974944/79331122-fe447d00-7f1a-11ea-8e87-4a2d40c8c250.png)

**Comment by vitko-bg** [comment]
My MC Config has not been changes since last 6 months at least, and I never had problems with adding agents - Linux, Windows or Mac. However, will update MC to latest to see if any better.

**Comment by vitko-bg** [comment]
In regards to missing desktop tab - after update to latest MC is fine.
In regards to adding agent - same issue. Also I have tried to add agent by invitation link, and it is not possible anymore to open invitation page, as link in address bar is:
**https://https//mc.mysite.com:444/:444/agentinvite?c=**<code here>
No changes are done in MC conf file. and it was working fine a week ago .......

**Comment by vitko-bg** [comment]
If I manually edit link for invitation and make it looking https://mc.mysite.com:444/agentinvite?c=**randomcodehere - invitation page working ..................

**Comment by vitko-bg** [comment]
Rolling back at least couple of versions lower - to see how it goes

**Comment by vitko-bg** [comment]
Thanks for advise - found the issue ............ 
So looks like I provided incorrect info - conf file was changed some how.
Restored from backup. 
Closing issue now.
