### ISSUE TITLE
Add virtual machine device icon

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1169]
How about adding an icon dedicated to VMs? Something like:

- transparent color PNG

![vm](https://user-images.githubusercontent.com/29974944/79502110-71d7ae80-802f-11ea-96c3-da5b97ad0501.png)

- transparent B/W PNG

![vm1](https://user-images.githubusercontent.com/29974944/79502295-acd9e200-802f-11ea-90c1-ffe04249f47d.png)

Super iper very extra low priority, of course.
Thanks

**Comment by krayon007** [comment]
Seems doable, but requires an accurate way to detect the local agent is running on a VM. I normally sue VMWare, so I can probably figure that out for that. But I'll need help with other hypervisor's as I won't be able to work/test on all of them...

**Comment by uldiseihenbergs** [comment]
i have all my VMs on Proxmox know. if i can help with something, just let me know.

**Comment by amenolo** [comment]
To be honest I wasn't thinking about self-detection in this case too...but if in some way feasible, why not...

I'm using PVE and ESXi, along with uldiseihenbergs I'm at your disposal for possible checks/tests.

**Comment by krayon007** [comment]
If you guys go into the details tab, under bios and motherboard, do any of the strings look like it can be used to identify your hypervisor? On mine, windows and most of my Linux distros list VMware as the bios manufacturer. Is this the case with your hypervisors as well?

**Comment by uldiseihenbergs** [comment]
not sure what mean motherboard identifier, vendor is a BIOS type(Seabios or OMVF). on PVE i have this for example no my Ubuntu VM:
![image](https://user-images.githubusercontent.com/60253253/79494849-5d45e700-802c-11ea-9592-b1c984be6453.png)
and Windows VM:
![image](https://user-images.githubusercontent.com/60253253/79495529-671c1a00-802d-11ea-9fdc-bab3ed863819.png)
so looks like Bios version is the right field to identify PVE VMs

**Comment by krayon007** [comment]
YEah, I'll have to play around with my VMWare settings... Not sure if this will be usefull... I just rechecked my VMs... Most of my VM's show Phoenix Bios, but many of my ArchLinux based VM's show VMWare... I wonder if VMWare is changing the BIOS virtualization based on what OS/Kernel type you select.

**Comment by jsastriawan** [comment]
I think you can detect this using dmidecode -t system and see what manufacturer or the product name. Anyway, we already have smbios.js.

**Comment by Ylianst** [comment]
Anything to get the image above in PNG format without the white background?

**Comment by krayon007** [comment]
The details page actually uses dmidecode to fetch those fields already, on Linux.

**Comment by krayon007** [comment]
I currently only show items that can be gathered from all platforms... But it looks like on my VM's where the BIOS is listed at Phoenix, if I fetch the System Manufacturer name from dmidecode, I still get VMWare, Inc.

**Comment by amenolo** [comment]
Types of BIOS available under PVE:

![immagine](https://user-images.githubusercontent.com/29974944/79497441-fcb4ab00-8027-11ea-8b35-2ad8a30d6288.png)

For the record under ESXi 7.0 is the same as under VMware Workstation Pro (of course...)

![immagine](https://user-images.githubusercontent.com/29974944/79498946-7483d500-802a-11ea-9926-7a7393e6a4fa.png)

**Comment by krayon007** [comment]
if you type 'sysinfo' on the console tab, you'll see the raw dump (parsed) I got from dmidecode.

**Comment by amenolo** [comment]
- VM Linux under ESXi

{
 "hardware": {
  "identifiers": {
   "bios_date": "12/09/2019",
   "bios_vendor": "Phoenix Technologies LTD",
   "bios_version": "6.00",
   "board_name": "440BX Desktop Reference Platform",
   "board_vendor": "Intel Corporation",
   "product_uuid": "a9eb4d56-2b48-c7c7-150f-0eb140358a89"
  },
  "linux": {
   "bios_date": "12/09/2019",
   "uevent": "MODALIAS=dmi:bvnPhoenixTechnologiesLTD:bvr6.00:bd12/09/2019:svnVMware,Inc.:pnVMwareVirtualPlatform:pvrNone:rvnIntelCorporation:rn440BXDesktopReferencePlatform:rvrNone:cvnNoEnclosure:ct1:cvrN/A:",
   "product_serial": "VMware-56 4d eb a9 48 2b c7 c7-15 0f 0e b1 40 35 8a 89",
   "product_name": "VMware Virtual Platform",
   "chassis_vendor": "No Enclosure",
   "chassis_asset_tag": "No Asset Tag",
   "sys_vendor": "VMware, Inc.",
   "bios_version": "6.00",
   "board_vendor": "Intel Corporation",
   "chassis_version": "N/A",
   "product_sku": "",
   "chassis_type": "1",
   "product_family": "",
   "product_uuid": "a9eb4d56-2b48-c7c7-150f-0eb140358a89",
   "bios_vendor": "Phoenix Technologies LTD",
   "board_asset_tag": "",
   "modalias": "dmi:bvnPhoenixTechnologiesLTD:bvr6.00:bd12/09/2019:svnVMware,Inc.:pnVMwareVirtualPlatform:pvrNone:rvnIntelCorporation:rn440BXDesktopReferencePlatform:rvrNone:cvnNoEnclosure:ct1:cvrN/A:",
   "board_name": "440BX Desktop Reference Platform"
  }
 },
 "hash": "459917C0608B306FB47B4E3F3532492E580B3548349AB22B3CBB11A27877721CD566BCA18129ADF1060477F5767683D9"
}

- VM linux under PVE

{
 "hardware": {
  "identifiers": {
   "bios_date": "04/01/2014",
   "bios_vendor": "SeaBIOS",
   "bios_version": "rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org",
   "product_uuid": "272ae463-24fa-4ae3-9249-9f6432c6eb59"
  },
  "linux": {
   "bios_date": "04/01/2014",
   "uevent": "MODALIAS=dmi:bvnSeaBIOS:bvrrel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org:bd04/01/2014:svnQEMU:pnStandardPC(i440FX+PIIX,1996):pvrpc-i440fx-4.1:cvnQEMU:ct1:cvrpc-i440fx-4.1:",
   "product_serial": "",
   "product_name": "Standard PC (i440FX + PIIX, 1996)",
   "chassis_vendor": "QEMU",
   "chassis_asset_tag": "",
   "sys_vendor": "QEMU",
   "bios_version": "rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org",
   "product_version": "pc-i440fx-4.1",
   "chassis_version": "pc-i440fx-4.1",
   "product_sku": "",
   "chassis_type": "1",
   "chassis_serial": "",
   "product_family": "",
   "product_uuid": "272ae463-24fa-4ae3-9249-9f6432c6eb59",
   "bios_vendor": "SeaBIOS",
   "modalias": "dmi:bvnSeaBIOS:bvrrel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org:bd04/01/2014:svnQEMU:pnStandardPC(i440FX+PIIX,1996):pvrpc-i440fx-4.1:cvnQEMU:ct1:cvrpc-i440fx-4.1:"
  }
 },
 "hash": "CD062671684799665564B0633F8CAE5DD84EF6A49596D30E2FF75828DBF1034EE453745983EBBC7A14C6F2B7F9A03F82"

**Comment by amenolo** [comment]
Updated OP with transparent PNGs.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.1-y that includes the new icon. Note that the mobile web app and MeshCentral router where also updated with the new icon. The new icon is not auto-selected right now, you have to select it yourself. (On top of this, latest release works much better on IE11)

![MC2-VirtualMachineIcon](https://user-images.githubusercontent.com/1319013/79503036-5cd62d80-7fe5-11ea-8d95-39ca2b50f746.png)

**Comment by D4V3M0NK** [comment]
The majority of my systems are deployed either in AWS, VirtualBox or on VMware. Does it help to have additional feed back from the first two?

**Comment by D4V3M0NK** [comment]
sysinfo VM linux under AWS
https://pastebin.com/PVb6UP99

**Comment by Ylianst** [comment]
Going to have to discuss this with Bryan. Currently the icon number is passed to the server in binary command #3, int at position 14, 7 = Raspberry Pi, 8 = Virtual Machine. Problem is, the MeshCore.js is not loaded at this point.

```
                obj.agentInfo.infoVersion = common.ReadInt(msg, 2);
                obj.agentInfo.agentId = common.ReadInt(msg, 6);
                obj.agentInfo.agentVersion = common.ReadInt(msg, 10);
                obj.agentInfo.platformType = common.ReadInt(msg, 14);
```

**Comment by krayon007** [comment]
Does anyone have any VMs under Microsoft HyperV? If I can get that, then I should have all the common ones...

**Comment by tradexsrl** [comment]
our company pc are using openxt whihch is a local hypervisor installed on pc and on top of this there is the windows vm.
it look like this :
![immagine](https://user-images.githubusercontent.com/62424179/79541306-e3dce180-8089-11ea-8069-49c9576b6384.png)

**Comment by vitko-bg** [comment]
I am running VMs on HyperV with meshagents installed on them - what needs to be done?

**Comment by vedran-dobos** [comment]
> Does anyone have any VMs under Microsoft HyperV? If I can get that, then I should have all the common ones...

Here's one:
Windows 2012 R2 VM under Windows 2012 R2 Hyper-V

> sysinfo
{
 "hardware": {
  "identifiers": {
   "bios_date": "20120523000000.000000+000",
   "bios_vendor": "American Megatrends Inc.",
   "bios_version": "090006 ",
   "board_name": "Virtual Machine",
   "board_serial": "6377-7596-2252-9745-6491-1993-22",
   "board_vendor": "Microsoft Corporation",
   "board_version": "7.0",
   "product_uuid": "C7E2B7B2-62E5-4991-BA18-8D2CCBA4C8F1"
  }
 }
}

**Comment by amenolo** [comment]
> 
> 
> Does anyone have any VMs under Microsoft HyperV? If I can get that, then I should have all the common ones...

See my post...or the last ones.

**Comment by krayon007** [comment]
This is now live in Mesh Central v0.5.14
I used the data you guys posted above, to detect if its running inside a VM. I tested it with Windows, Linux, and macOS, running inside VMware. It should work with zen, hyper-V, etc, based on the data posted above...

I'm adding support for detecting if it's inside a docker container as well... I just got that working, but it didn't make it in time for v0.5.14

As a side note, if the agent has already connected to the server, the icon will not change. You'll need to either do a fresh install, or you just need to delete the device from the group, before the agent connects. But you can test if the detection logic works, separately, as I added a console command, called 'vm'... If you type 'vm' from the console tab, it will tell you if it thinks the agent is running inside a VM or not.

**Comment by D4V3M0NK** [comment]
Bryan,
When in AWS, "vm" reports false. 
sysinfo:
> sysinfo
{
 "hardware": {
  "identifiers": {
   "bios_date": "08/24/2006",
   "bios_vendor": "Xen",
   "bios_version": "4.2.amazon",
   "product_uuid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "linux": {
   "bios_date": "08/24/2006",
   "uevent": "MODALIAS=dmi:bvnXen:bvr4.2.amazon:bd08/24/2006:svnXen:pnHVMdomU:pvr4.2.amazon:cvnXen:ct1:cvr:",
   "product_serial": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "product_name": "HVM domU",
   "chassis_vendor": "Xen",
   "chassis_asset_tag": "",
   "sys_vendor": "Xen",
   "bios_version": "4.2.amazon",
   "product_version": "4.2.amazon",
   "chassis_version": "",
   "chassis_type": "1",
   "chassis_serial": "",
   "product_family": "",
   "product_uuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "bios_vendor": "Xen",
   "modalias": "dmi:bvnXen:bvr4.2.amazon:bd08/24/2006:svnXen:pnHVMdomU:pvr4.2.amazon:cvnXen:ct1:cvr:"
  }
 },
 "hash": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
}


Just added a test system in my development VirtualBox environment, and the icon come up just fine. Nicely done sir.

**Comment by krayon007** [comment]
Oops, sorry. I was looking in the wrong field for 'Xen'... I just fixed it. It'll get picked up in the next update.

**Comment by amenolo** [comment]
`Virtual Machine = false` in Proxmox Windows guest too (agent reinstalled).

Sysinfo

https://pastebin.com/931XHzZG

**Comment by krayon007** [comment]
Ok, I just fixed it, and let @Ylianst  know... Should get picked up in the next update...

**Comment by amenolo** [comment]
> I tested it with Windows, Linux, and macOS, running inside VMware

Oddly enough in my case `vm `command still reports `false` in Windows 7 both x86 and x64 client (fresh installations) under VMware, sysinfo outputs:

https://pastebin.com/as24y0nQ x86
https://pastebin.com/aKy0ib20 x64

**Comment by amenolo** [comment]
> I tested it with Windows, Linux, and macOS, running inside VMware

Oddly enough in my case `vm` command still reports `false` in Windows 7 both x86 and x64 clients (fresh installations) under VMware, sysinfo outputs:

https://pastebin.com/as24y0nQ x86
https://pastebin.com/aKy0ib20 x64

**Comment by amenolo** [comment]
> I tested it with Windows, Linux, and macOS, running inside VMware

Oddly enough in my case `vm` command still reeturns `false` in Windows 7 both x86 and x64 clients (fresh installations) under VMware, sysinfo outputs:

https://pastebin.com/as24y0nQ x86
https://pastebin.com/aKy0ib20 x64

**Comment by amenolo** [comment]
> I tested it with Windows, Linux, and macOS, running inside VMware

Oddly enough in my case `vm` command still returns `false` in Windows 7 both x86 and x64 clients (fresh installations) under VMware, sysinfo outputs:

https://pastebin.com/as24y0nQ x86
https://pastebin.com/aKy0ib20 x64

**Comment by krayon007** [comment]
@amenolo , on your VMware configuration, what version do you have your hardware compatibility set to? Mine is currently set to 15.x

According to that dump you posted, none of the fields indicate that it is running on a VM, particularly your bios_vendor, shows Phoenix, while mine says "VMware, Inc"

It's not a windows 7 issue, as I checked my Windows 7 VM... I think its your hardware compatibility setting. It looks like your configuration is not populating any hardware fields with anything indicating it's a VM.... 

On your Windows guest, can you open a command prompt, and type the following command:
wmic path Win32_VideoController GET Name

And let me know what it says...
That is what I use (in the next version) to fetch the GPU names. If this shows VMmware SVGA, or something similar, I can use that as a fallback...

**Comment by amenolo** [comment]
> Mine is currently set to 15.x

Mine too (the one I set by default)

![immagine](https://user-images.githubusercontent.com/29974944/80320178-2a160b80-8815-11ea-8a0e-331e193a9167.png)

![immagine](https://user-images.githubusercontent.com/29974944/80320185-326e4680-8815-11ea-8cd2-5ca2d86d6cc5.png)

BTW I just noticed vmx file says `virtualHW.version = "16"` but I can only assume it's the regular string in VMware 15.x (really never happened to take a look at that field).

Overall I used (as usually) default machine options (except for CPU numbers, RAM amount, HDD size and stuff).

> And let me know what it says...

```
C:\Users\Walter>wmic path Win32_VideoController GET Name
Name
VMware SVGA 3D
```

**Comment by krayon007** [comment]
Wierd... I can definitely use the VideoController as a fallback...
Do you mind posting the contents of your .vmx file, (or emailing it to me), so I can compare all the fields? I'm really curious why my abstraction is different than yours...

**Comment by amenolo** [comment]
https://pastebin.com/d87iUUGu x86
https://pastebin.com/beGL6frA x64

BTW same thing in ESXi 7.0 both with 

![immagine](https://user-images.githubusercontent.com/29974944/80322140-343f0680-8823-11ea-8ae8-ce1e4f179e70.png)

and

![immagine](https://user-images.githubusercontent.com/29974944/80322244-22119800-8824-11ea-83ee-730bdacd8fec.png)

For the record in the latter case come out string `virtualHW.version = "17"` inside vmf file.

(`wmic path Win32_VideoController GET Name `returns the same result as well)

**Comment by krayon007** [comment]
I updated the detection logic, so it will also look at the GPU name as well, so it should at least workaround whatever is causing your machines to have a different BIOS abstraction... Ylian is working on the agent update as we speak...

**Comment by krayon007** [comment]
The latest changes are live in MeshCentral_v0.5.15, give it a whirl, and let me know if the VM detection works for you now.

**Comment by tradexsrl** [comment]
tried the command vm to a virtual machine running into openxt but i get false
MC version = 0.5.14

**Comment by amenolo** [comment]
> let me know if the VM detection works for you now.

Affirmative +1

**Comment by krayon007** [comment]
@tradexsrl , try v0.5.15. 

version 14 was looking in the wrong field for openxt.

**Comment by tradexsrl** [comment]
yes it works now

**Comment by D4V3M0NK** [comment]
AWS confirmed as working too - nice one Mr Roe, sir
