### ISSUE TITLE
AMT 4k Resolution Issue

### ISSUE THREAD

**Issue by sourcex** [Ylianst/MeshCentral#117]
I have a number of clients up on two different installations.  Devices connected to 4k display (at 4k resolution) usually fail to connect via the Desktop | HW Connect action.  I'd estimate the rate of success to be 1/100 attempts.

The console sometimes shows (but not consistently, so I'm not sure it is related)-
>  amt-manager: LMS error
> uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'heci.session' threw an exception: TypeError: cannot read property 'type' of null in method 'G()'

For the most part the clients are NUC7i5DNKE devices connected over CIRA.  The servers are Ubuntu 18.04 hosted on Digital Ocean and Microsoft Azure.

**Comment by sourcex** [comment]
I can replicate the issue on Chrome and Firefox and no messages are output to the developer console on either browser.

**Comment by jsastriawan** [comment]
AMT doesn't support 4K yet. See: https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/kvmandintelamt.htm

It is firmware limitation and hopefully higher resolution will be supported soon on the next iteration.

**Comment by sourcex** [comment]
Thank you for the clarification.
