### ISSUE TITLE
Latest update 0.5.1-y server console not useable

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1170]
After the latest update (0.5.1-y) my servertab --) console is not working anymore.
things i have done, rebooted my vm (Ubuntu 18.04.4 lts) restarted the mc server 

I tested it with: ie11, chrome, firefox and the new edge(chromium)

nodejs : 10.20.1
node : 12.15.0
![Screenshot_9](https://user-images.githubusercontent.com/58996467/79508096-2d511080-8039-11ea-9260-d18505c6de7c.jpg)

**Comment by Ylianst** [comment]
Weird, I am trying and it works for me. Can you open the browser console and see if there are any error messages? Thanks.

**Comment by petervanv** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/58996467/79511210-21684d00-803f-11ea-9ec2-6bec2f647e26.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/58996467/79511211-2200e380-803f-11ea-80fe-79d36e43a357.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/58996467/79511213-22997a00-803f-11ea-9940-810eb9dce3e9.jpg)

**Comment by Ylianst** [comment]
Interesting, does your server statistics tab work correctly?

![x](https://user-images.githubusercontent.com/1319013/79511492-408dbd00-7ff4-11ea-9584-6baf4dffbd46.png)

**Comment by petervanv** [comment]
yes that is working fine

**Comment by petervanv** [comment]
Played with some setting, and at the fixed with is working !!!!

![Screenshot_14](https://user-images.githubusercontent.com/58996467/79512378-976db380-8041-11ea-8b0f-183cb11e2469.jpg)

**Comment by Ylianst** [comment]
OOoohhhhhhhhhhhhh!!!! ?!??!?! Very interesting!

**Comment by Ylianst** [comment]
I removed the chat animation in the next version, we will see if that changes anything.

**Comment by petervanv** [comment]
oke, i wil see over about 9 hours (going to sleep now), i will report back the result after the update.

**Comment by Ylianst** [comment]
On more thing to try, check if text is not black on black by selecting the text to see if it will because visible.

![x](https://user-images.githubusercontent.com/1319013/79514177-73d34a80-7ffa-11ea-83ad-39d16ec90e98.png)

**Comment by petervanv** [comment]
no the text is not black, as you can see in my screenshot the command bar is missing, and the fixed width it is there.

i did an upgrade to the latest 0.5.3 and it is working again. thx
