### ISSUE TITLE
hide is broken in 0.5.1-y

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#1171]
the hide embed parameter is broken for all viewmodes when upgrading from 0.5.1-x to 0.5.1-y
the url im using in my iframe is in this format:
mesh.example.com/?login=LOGINTOKEN&node=NODEIDHEX&viewmode=12&hide=31

screenshots (tested in chrome and firefox):

0.5.1-x

![0 5 1-x-terminal](https://user-images.githubusercontent.com/7434746/79513414-9fedcc00-7ff8-11ea-89d1-058c137fa48e.PNG)

0.5.1-y

![0 5 1-y-terminal](https://user-images.githubusercontent.com/7434746/79513425-a4b28000-7ff8-11ea-9df6-a9c3c9d7336f.PNG)

**Comment by Ylianst** [comment]
Oh! Thanks for the report. I have been fixing support for IE11 and broke this, working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.2 with a fix for this. Let me know if it works.
(Note that MeshCentral versions are now going to be v0.5.xxx with no more letters).

**Comment by wh1te909** [comment]
You're the best, yes it's working. Thank you!
