### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1172]
[servererrors.txt](https://github.com/Ylianst/MeshCentral/files/4490204/servererrors.txt)
Haven't been around for a while, but today updated my server to 0.5.1-y and wanted to delete an old user account. When I selected the account > group action > delete > confirm, the server appears to log me out. When I log back in again, the account is still visible.

server.log attached

**Comment by Ylianst** [comment]
Doh! Working on it now.

**Comment by amenolo** [comment]
Just to know, no problem here...

![Q4fs1Pdaj0](https://user-images.githubusercontent.com/29974944/79517686-32b95580-804f-11ea-8570-13916cbe7755.gif)

Last MC release.

**Comment by Ylianst** [comment]
@D4V3M0NK Nice to hear form you again. Thanks for reporting this, published MeshCentral v0.5.3 with a fix for this. Problem only occurred if the user had rights to one or more device groups, this is why it did not happen all the time. Thanks!

**Comment by D4V3M0NK** [comment]
It's nice to be back :smiley: 
Confirmed and closing. Thanks @Ylianst
