### ISSUE TITLE
Agent invite link broken?

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1173]
I tried sending through an invite link to someone today (using an older version) and when I clicked on the generated link, the link didn't go anywhere - it used to show a page where someone could select Windows, Mac, Linux etc. So I upgraded (now at 0.5.3) and the link still isn't working: as in, the browser opens a new tab showing a blank page. Checking DevTools in Chrome for that page shows:
> Uncaught SyntaxError: missing ) after argument list
> agentinvite?c=XXXXXXXXXXX:145

"@D4V3M0NK Nice to hear form you again"
You sure about that @Ylianst ??  :wink:

**Comment by Ylianst** [comment]
Are you talking about this link?

![image](https://user-images.githubusercontent.com/1319013/79519035-7c7e4d80-8007-11ea-8cac-708b553bf233.png)

**Comment by D4V3M0NK** [comment]
Yes - apologies if it wasn't clear - and it only appears to happen on groups that have no current clients in them (groups with clients appear to work just fine)

**Comment by D4V3M0NK** [comment]
Ok - I **think** it only happens if there's an apostrophe in the group name...

**Comment by Ylianst** [comment]
Got it!!! I will fix.

**Comment by Ylianst** [comment]
Just checked in a fix for this. This problem has been there from the start, thanks for reporting it. Fix will be in 0.5.4 when I next publish it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.4 that should fix this.

**Comment by D4V3M0NK** [comment]
lovely jubbly, thanks @Ylianst
