### ISSUE TITLE
2 branches of updates meshcentral

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1176]
Hey. It would be very cool if meshcentral introduced two update branches.
First: stable release.
Second: With the latest updates.
You add functionality very actively - this is very cool, but I would like to update meshcentral a little more confidently.
I mean that having version 0.5.0 it was possible to confidently upgrade to 0.5.3 stable knowing that most of the bugs were fixed there.

Thank you for what you are doing, especially for the MeshRouter.

**Comment by uldiseihenbergs** [comment]
+1 for that. 
you can do it manually know with setting exact version you want in packages.json file in dependencies section or edit startmeshcentral.sh(if in Linux) and append version tag, for example npm install meshcentral@0.5.3.
the biggest problem is to know version which is considered stable :)

**Comment by Ylianst** [comment]
Agreed. I will need to tag in NPM a version as "stable" and have the MeshCentral user interface look for it. Of course, the problem is that there is a chance many less people will test the latest version and so, there is a risk of bug reports slowing down.

**Comment by Ylianst** [comment]
This is in the latest MeshCentral, update box will be a little different. Let me know what you think.

![MC2-ServerUpgrade](https://user-images.githubusercontent.com/1319013/79664104-ea428a80-8169-11ea-9398-5d34cff56463.png)

**Comment by uldiseihenbergs** [comment]
@Ylianst looks like very well. how it corresponds to command-line? i'm running MC on Docker environment, so on every MC restart it grabs latest version now..

**Comment by Ylianst** [comment]
You can run `npm install meshcentral@0.5.1` to get a specific version and `npm dist-tag ls meshcentral` to get the current list of tags and versions.

**Comment by uldiseihenbergs** [comment]
ok, i edited my startmeshcentral.sh, with
`npm install meshcentral@stable`
