### ISSUE TITLE
Setting up 2FA

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1178]
I've just configured my account with 2FA (Google Authenticator) and it was successful, but now I have a notification message stating 
> Two factor authentication: Please add two-factor backup codes. If the current factor is lost, there is not way to recover this account.

I'm a little nervous about logging out now just in case I lose any access - but what do I need to do about these backup codes, and where do I put them?

**Comment by D4V3M0NK** [comment]
Ok, I think I see it now - in the My Account tab, there's a link to "Manage Backup Codes" which, when generated, allows you to download a set of codes should 2FA fail. Apologies - got a little too nervous and started writing before RTFS (screen)  :computer: :scream:

**Comment by PathfinderNetworks** [comment]
It's very easy.  Just go to the My Account tab in MeshCentral (the second tab down on the left).  You'll see a 'Manage Backup Codes' link.  Just click that link and the backup codes will be generated and displayed.  Just save those codes to something like a text file in a secure location.

**Comment by D4V3M0NK** [comment]
(Thanks @PathfinderNetworks)
