### ISSUE TITLE
Spaces in user groups name

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1180]
In opposite to device name and device groups name, I just noticed that isn't allowed to set user group name with spaces in it:

![immagine](https://user-images.githubusercontent.com/29974944/79614733-7076b680-8101-11ea-9239-c5c38aa30c3a.png)
![immagine](https://user-images.githubusercontent.com/29974944/79615772-c9dfe500-8103-11ea-8eb1-66770d392df7.png)

**Comment by Ylianst** [comment]
Made the fix for this, will be in MeshCentral v0.5.5 when next published.

**Comment by amenolo** [comment]
Maybe you wanna consider #1181 too! Thanks

**Comment by amenolo** [comment]
Solved with 0.5.7! 👍
