### ISSUE TITLE
Groups column under My Users tab

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1181]
Currently it reports the number of common device groups: how about changing its name in Device groups and moreover adding (user) groups column and devices column too (along the lines of user groups tab)?

**Comment by amenolo** [comment]
Solved with 0.5.7! 👍

**Comment by Ylianst** [comment]
On the screen below, I am not going to add more columns, not sufficient space. If you have a different suggestion, that is ok.

![image](https://user-images.githubusercontent.com/1319013/79677895-94da9d80-81aa-11ea-8128-de03d100c45a.png)

**Comment by amenolo** [comment]
Right...I'm not used to the fixed width layout...issue closed! Thanks
