### ISSUE TITLE
Device Group Permissions Issues

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#1182]
Hi Yilan, great work on MeshCentral! Just updated to the latest version and really loving the new features, particularly the new MeshRouter stuff.

However, I was playing around with the user group permissions for device groups, to find out what exactly they controlled access to, and in doing so discovered that enabling "Manage Device Group Users" allows deletion of any users/user groups within the device group, no matter their permissions. I was able to delete my "Full Administrator" admin account from the device group with a user account in the test group which only had "Manage Device Group Users", "Manage Device Group Computers", and "Remote Control" enabled. 

It would be nice if there was a hierarchy of sorts to prevent users without "Full Administrator" rights from deleting users who have them. Management of users and user groups for individual devices for those with the "Manage Device Group Computers" permission would also be beneficial. Perhaps this was intended, as I noticed the "Add User" and "Add User Group" options are shown or hidden with "Manage Device Group Computers", however attempting to add a user or group fails unless "Manage Device Group Users" is also enabled.

I also discovered that removing all important permissions from a device group is possible. Following the deletion of my admin user from the aforementioned device group, I removed all permissions for the test group. This resulted in a device group with a single user group added, with no rights, and so cannot be deleted. The only way I was able to remove this device group was to delete the test user group, which also crashed MeshCentral somehow. Upon rebooting my server I found the device group gone, and the test user group still there. Very odd.

**Comment by Ylianst** [comment]
Excellent request.

**Comment by Ylianst** [comment]
MeshCentral v0.5.8 has a bunch of fixes for this. Let me know if it works. Users with limited rights on a device group now have more limited right on what rights they can assign to others.

**Comment by MatinatorX** [comment]
Seems to work! The edit permissions and delete user/group icons are still present and clickable, but the edit permissions dialogue has nothing available to edit when it pops up. Clicking the delete button brings up the confirmation dialog, but clicking "OK" no longer deletes a "Full Rights" user. Awesome!

**Comment by Ylianst** [comment]
Oh, the delete button should not be present on the web interface. I will take a look at this. The server enforces the rules, but the user interface should match.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.9 that removed the trash/delete button when your not allowed to remove an administrator from a device group. Please confirm and close this issue. Thanks for the report.

**Comment by Ylianst** [comment]
Closing this since it's probably fixed. Please open a new issue if needed.

**Comment by MatinatorX** [comment]
Confirmed fixed, thanks Ylianst!
