### ISSUE TITLE
Right Click to Open Device in New Tab - Enhancement Request

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1184]
Add the ability to open numerous devices at the same time in their own tabs.
If you have several devices, the ability to right click on the device and have that device open in a different tab would be very nice. If you need to work with multiple devices at once, it's much faster.
Or, alternatively the ability to do a group action in order to have multiple devices in their own tab would work as well. 

Also for the tab label instead of having MeshCentral-Device name, change to devicename first. That way if you do have multiple tabs open with different devices, it's easy to go back and forth between them.

![2020-04-18_09-34](https://user-images.githubusercontent.com/5482919/79641939-d1c97480-8157-11ea-9128-a5faaffa4a49.png)

**Comment by CCWTech** [comment]
Showing example of why MeshCental first is less efficient.

file:///home/acrist/Downloads/2020-04-18_09-40.png

**Comment by Ylianst** [comment]
Try holding the shift key when clicking on a device, or right click on device, hold shift and select and option. Let me know what you think.

**Comment by CCWTech** [comment]
Holding the shift key opens in a new window, but a new tab would be more efficient. Easier to go from tab to tab, vs between different windows.

I may not be doing something right as right clicking the device then holding the shift key down (or) holding the shift key down and right clicking I don't see Option. I see Information, Desktop, Terminal Files and Console.

**Comment by amenolo** [comment]
Truth to be told, holding shift key when clicking on device results in a new tab under FireFox only if following option checked

![image](https://user-images.githubusercontent.com/29974944/79644200-9fdffe80-81a7-11ea-850c-635bbbc358d3.png)

Option which isn't available in other known browsers except dear old I.E., if I recall right...

![image](https://user-images.githubusercontent.com/29974944/79644463-7b852180-81a9-11ea-91ab-dbd5969aeddc.png)

**Comment by CCWTech** [comment]
Let me check Chrome to see if there is a setting for that.

**Comment by CCWTech** [comment]
Not sure how to set it by default, but it looks like CTRL-SHIFT+Left Mouse Click does it.
Thank you!

**Comment by amenolo** [comment]
Ouch, never tried that combo, good to know!

**Comment by Ylianst** [comment]
It looks like the behavior of new tab vs new window is browser defined by the spec. By default, in FireFox it will open in a new tab, in Chrome in a new Window. There is nothing I can do about that, user must configure it.

**Comment by CCWTech** [comment]
Sounds like a good workaround. Should I create a different feature request for the TAB labels?

**Comment by Ylianst** [comment]
If you hold shift and hit any of the tabs, it should open in a new window/tab now. If it's something I missed, yes, open a new issue for it. Thanks.

**Comment by CCWTech** [comment]
Ok, I'm closing this one and putting in a new one for the Tabs request.
