### ISSUE TITLE
Change label that show up on the Tabs of the browser.

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#1185]
Instead of displaying MeshCentral-Device name, please put the device name first.

![79642122-02f67480-8159-11ea-8f55-31010e2805df](https://user-images.githubusercontent.com/5482919/79668668-c08e6100-8173-11ea-953d-b6f2442369ce.png)

In this example I have several different devices in different tabs, but because MeshCentral comes first the device name is hidden due to the amount of space the tab has to display. You can hover over and it displays more or you can click on the tab to make it active and it displays more as well. 

If the device name came first it would allow for ease in seeing which tab was open for which device much more efficiently than is the current view.

**Comment by Ylianst** [comment]
Fixed this, it will be in MeshCentral v0.5.8 when it's next published.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.8 with this fix. Close this issue when you confirm the fix.
