### ISSUE TITLE
Download server backup - Not found

### ISSUE THREAD

**Issue by FDrebin** [Ylianst/MeshCentral#1186]
Recently updated to 0.5.7 and went to take a server backup using the "Download server backup" and was met with "Not Found". Not sure if this is intention or due to the update I just did from the web portal.

**Comment by amenolo** [comment]
Just for the record: same version here, file https://mesh.domain.ext/backup.zip is OK.

**Comment by FDrebin** [comment]
> Just for the record: same version here, file https://mesh.domain.ext/backup.zip is OK.

Interesting....maybe it needs time to generate the file or something? Maybe I will wait and see and try again in a few hours or tomorrow. Could it be because I have it setup to use key= for the website? I guess we'll wait and see lol. I don't know enough about it to make a informed call...

**Comment by amenolo** [comment]
If I'm not mistaken, the `download server backup` link works in real time (as opposite to pre-scheduled auto-backup) so the behavior of yours sounds kind of odd to me...wait for code guys :wink:

**Comment by Ylianst** [comment]
Probably has to do with how long ago since the last login. The session cookie probably expired and so, clicking on this option will fail. Try logging out and back in an trying again, if it work, let me know. I need to find a way to fix this.

**Comment by FDrebin** [comment]
> 
> 
> Probably has to do with how long ago since the last login. The session cookie probably expired and so, clicking on this option will fail. Try logging out and back in an trying again, if it work, let me know. I need to find a way to fix this.

Hey thanks for the reply! So I just cleared my browser cache and cookies, and tried a different browser where I have never logged into my Mesh Central instance and both still returned not found.

**Comment by Ylianst** [comment]
Ok, I will check this next time I get a chance. However, I am thinking I may change this feature to download the last automatic backup nthat was created since the automatic backup includes mongodb.

**Comment by FDrebin** [comment]
Just a quick update from me, tried again today and cleared the cookies and cache kit and still was met with “Not Found”. 

Any way to take a manual backup of the folder? Can I just use the Ubuntu zip utility and zip the whole mesh central dir with all sub directories?

**Comment by 2b-mike** [comment]
Have you by any chance activated the LoginKey option?
Then every URL to your server needs to be ammended with ?key=[loginkey]
Try again with (server):(port)/backup.zip?key=(loginkey)
Works for me.
Have a nice day...

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
