### ISSUE TITLE
Server Crash on agent connect

### ISSUE THREAD

**Issue by oprican1987** [Ylianst/MeshCentral#119]
Mar  8 12:33:15 remote2 node[13326]: { Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch
Mar  8 12:33:15 remote2 node[13326]: /opt/meshcentral/node_modules/meshcentral/meshagent.js:362
Mar  8 12:33:15 remote2 node[13326]:                             obj2.send(common.ShortToStr(2) + common.ShortToStr(obj2.parent.agentCertificateAsn1.length) + obj2.parent.agentCertificateAsn1 + signature); // Command 2, certificate + signature
Mar  8 12:33:15 remote2 node[13326]:                                                                                            ^
Mar  8 12:33:15 remote2 node[13326]: TypeError: Cannot read property 'agentCertificateAsn1' of undefined
Mar  8 12:33:15 remote2 node[13326]:     at ChildProcess.func (/opt/meshcentral/node_modules/meshcentral/meshagent.js:362:92)
Mar  8 12:33:15 remote2 node[13326]:     at ChildProcess.<anonymous> (/opt/meshcentral/node_modules/meshcentral/certoperations.js:499:22)
Mar  8 12:33:15 remote2 node[13326]:     at emitTwo (events.js:126:13)
Mar  8 12:33:15 remote2 node[13326]:     at ChildProcess.emit (events.js:214:7)
Mar  8 12:33:15 remote2 node[13326]:     at emit (internal/child_process.js:772:12)
Mar  8 12:33:15 remote2 node[13326]:     at _combinedTickCallback (internal/process/next_tick.js:141:11)
Mar  8 12:33:15 remote2 node[13326]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Mar  8 12:33:15 remote2 node[13326]:     at ChildProcess.exithandler (child_process.js:275:12)
Mar  8 12:33:15 remote2 node[13326]:     at emitTwo (events.js:131:20)
Mar  8 12:33:15 remote2 node[13326]:     at ChildProcess.emit (events.js:214:7)
Mar  8 12:33:15 remote2 node[13326]:     at maybeClose (internal/child_process.js:925:16)
Mar  8 12:33:15 remote2 node[13326]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Mar  8 12:33:15 remote2 node[13326]:   killed: false,
Mar  8 12:33:15 remote2 node[13326]:   code: 1,
Mar  8 12:33:15 remote2 node[13326]:   signal: null,
Mar  8 12:33:15 remote2 node[13326]:   cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch' }
Mar  8 12:33:15 remote2 node[13326]: ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Comment by Ylianst** [comment]
Thanks for the report. Getting this one fixed right away, as soon as I get in the office.

**Comment by scottalanmiller** [comment]
Getting something similar, details on ML.  This is 0.2.9-x

https://mangolassi.it/topic/19068/meshcentral-0-2-9-x-crashing-on-start

**Comment by Ylianst** [comment]
Published 0.2.9-y with a fix for this.

**Comment by Ylianst** [comment]
There is another problem, going to patch ASAP. The remote desktop/terminal/files does not work.

**Comment by Ylianst** [comment]
Published 0.2.9-z, everything seems to be working again.

**Comment by scottalanmiller** [comment]
Seems to be working again here now.

**Comment by Ylianst** [comment]
Closing this one as I am pretty sure it's fixed.
