### ISSUE TITLE
Multi-Tenants - subdomains and SSL Wildcard Cert

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1190]
So, we have a Linux 2 AWS instance and issued an SSL cert to "www.end-support.com" and all works fine. However,  we created another wildcard cert but after applying it, Meshcentral fails to load and states that we have to change the 'Cert' value in settings when using SSL wildcard certs. We did it and tried "end-support.com", "end-support.com" and "www.end-support.com" and none worked. 

Kindly provide some guidance on setting up the multi-tenant environment on the same box using sub-domains.
THANKS

**Comment by Ylianst** [comment]
To confirm, the "cert" setting is set to `www.end-support.com` and the wildcard certificate is `*.end-support.com` when you get the error?

**Comment by jfp2** [comment]
Yes to the first question, and we did overwrite the same certs that are in the meshcentral-data folder.

The error is:

MeshCentral HTTP redirection server running on port 81.
ERROR: Must specify a server full domain name in Config.json->Settings->Cert when using a wildcard certificate.

**Comment by Ylianst** [comment]
There are two situations where this error can occur. You have a wildcard certificate setup that starts with "*.", but the "cert" is not set, or set to a name with no dot (.) in the name. In both cases, the server does not have the real name of the server and can't continue.

Are you sure you put a valid name for "cert" in the "settings" section of config.json? Another hint is the it says:

```
MeshCentral HTTP redirection server running on port 81.
```

It should be saying:

```
MeshCentral HTTP redirection server running on port SERVER.DOMAIN.COM:81.
```

This is more evidence that the cert value is not set.

**Comment by Ylianst** [comment]
Closing this, please re-open if needed.
