### ISSUE TITLE
MPS Server Locked to "example.servername.com", Including Scripts

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#1192]
Got my hands on a device supporting AMT finally and set about adding it to MeshCentral, but was surprised to see that after the CIRA script ran successfully from MeshCommander, nothing popped up under the device group. After some investigating I saw that the auto-generated script was using "example.servername.com" everywhere. Also noticed this was the URL listed as the MPS Server under both manual CIRA options, and was not editable. The client computer has internet and can be connected to via MeshCommander by other computers on my network, provided I have run the cleaning script first.

Proceeded to run the cleaning script, then manually modified the 6 URL occurrences in the CIRA script to point to my server and double-checked I'd opened port 4433. Re-ran CIRA script - still no dice. I saw a reference to an "MpsCert" config.json option in the documentation, but my understanding is this shouldn't be needed for most setups.

I checked this with both agent and AMT only device groups and the generated scripts look identical. Hopefully I'm just doing something wrong, but from your video tutorials I can't identify what that might be.

**Comment by Ylianst** [comment]
This is weird. Your server is in WAN mode and you get a CIRA script with an incorrect DNS name? This is a bug, but how did it get that name? It should use the one specified in "cert" of your config.json.

Once you setup CIRA, Intel AMT will turn off it's connection ports and just attempt connect to the server. I would not attempt to edit the script, something is off. Next time I get a change, I will search for "example.servername.com" and see.

**Comment by MatinatorX** [comment]
Definitely in WAN mode. I see "example.servername.com" in the script 6 times, and it's shown on the two manual options to add a CIRA device as well, which cannot be changed.

I'm using Let'sEncrypt, so in my config.json I have "_Cert": "myserver.mydomain.com",

I just downloaded the whole MeshCentral repo and scanned it for "example.servername.com" using Notepad++ and it couldn't find any results, so I have no idea where that's coming from. I would suspect it has something to do with Let'sEncrypt.

**Comment by Ylianst** [comment]
I see the problem. First, anything in the config.json that starts with an underscore (_) is ignored, this should be mentioned as the first line of the config.json. If you have a section header with a name that starts with "_" the entire section is ignored. I encourage everyone to clean up their config.json and remove all ignored portions. Changing the value of a setting that starts with "_" will do nothing at all.

Next, remove the "_" in front of "_Cert" and put the correct name you want agents and browser to use to connect to your server. Do this even if you are using Let's Encrypt or using a wildcard certificate. The only servers that should not have a "Cert" is LAN mode servers that don't have a DNS name. Hope that helps.

**Comment by Ylianst** [comment]
Even if you are using Let's Encrypt, do remove the underscore before "_Cert" and set it to the correct DNS name that should be used to contact your server. Let me know if that helps.

**Comment by MatinatorX** [comment]
That did the trick. Enabled the Cert field and entered my FQDN, then rebooted MeshCentral. After this, the sciprt worked great, and I can now see my machine listed in the device group. Thanks!
