### ISSUE TITLE
Best practice  for 2020 raspberry pi 4 4gb meshcentral installation

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#1193]
Hi,
after using meshcentral with great appreciation,  managing 1.000+ client with a VMWare Virtual Server 2016 in my company, now I'm trying to create smaller one for a little company without any kind of IT infrastructure, just a plain LAN.
The cheap-but-honest RPi 4 with 4Gb RAM (less than 80 Euros with all i need to start) is the chosen candidate
Now, my purpose is starting in right way...

For example:
pre installation tips and required modules
best node and npm version 
right config for best performance and reliability

I know I am asking a lot, thanks for all support, everybody is welcome
Sure I will publish all my experience, hoping to give help to community

Cheers
Merlinweb

**Comment by Ylianst** [comment]
I own a bunch of Raspberry Pi's myself, I use them mostly for compiling and testing the agent however I have installed the server of them and even ordered cases and printed MeshCentral stickers to put on them.

![MC2-IoT-Lab](https://user-images.githubusercontent.com/1319013/79692705-719c0680-821b-11ea-9b3c-de8b836ff67a.png)

The [MeshCentral User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf) has a full section on installation of MeshCentral on a Raspberry Pi. But here are a few of my own notes:

- The latest 4G/4Core Pi is really powerful, probably more than the AWS instance I run MeshCentral.com on (except it may not have CPU acceleration for TLS/AES, not sure). For the most part, this is a real Linux server. I never tried, but you can likely manage 10k+ devices on that thing.
- If you run the Raspberry Pi on an SD card and unplug it without proper shutdown first, you may corrupt the memory card. For reliability, you probably want to run on a proper SSD drive and keep the SD card read only. I have not done this myself, but if you use it for any real application, I think this is a must. I have one running "Pi-Hole" at home and broke it a few times, I now have it set to write as little as possible to the SD card.
- You get a lot more of the system available if you don't run X-Windows on the Pi. I have run Raspbian Light and you have plenty of space and RAM.

Ylian

**Comment by Ylianst** [comment]
If your going to keep the Raspberry Pi in "LAN-mode", take a look at this [little guide for your users](http://info.meshcentral.com/downloads/MeshCentral2/MeshApplianceGuide.pdf).

**Comment by merlinweb** [comment]
Wow, thanks for the tips Ylian !
I am in Alpha phase now, but I'm planning to add a POE hat and a SSD for OS, keeping SD only for first boot, totally agree.
I'm using Raspbian Buster Lite, without gui, in headless mode and with 16Mb video mem; everything is for network and computing, reserved for MC2 and a couple of other useful tool
I've studied Raspberry section in the guide, but with newest ARMv8 chip,  for example, the recommended nodeJS installation is Node 13.13.0
$ curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
I don't know if newer is better or i will run into trouble...
I think is my only true doubt, other instructions are very clear and replicable without an hassle

Thanks in advance for your amazing support Ylian

Cheers
Merlinweb

**Comment by Ylianst** [comment]
The nice thing with the latest NodeJS is that you get TLS 1.3 support which is a nice checkbox for added security. You are way ahead of me with Raspberry PI installation, I have just installed an older default NodeJS that easily installs on Raspbian Lite. I can't imagine it would not work.

**Comment by Ylianst** [comment]
Fun trick, take the following image and save it as "server.png" in "meshcentral-data".

![server](https://user-images.githubusercontent.com/1319013/79694181-a4e29380-8223-11ea-9c04-daac65d2487e.png)

Then, when you go in "My Server" tab, you will see this.

![x](https://user-images.githubusercontent.com/1319013/79694194-b3c94600-8223-11ea-80cc-7491e7d9ba9d.png)

**Comment by Ylianst** [comment]
Also, if you have not noticed in my small guide above, if you keep your Raspberry Pi in LAN-mode, there is a Windows tool to discover MeshCentral server on the LAN located here: [http://info.meshcentral.com/mcdiscovery.exe](http://info.meshcentral.com/mcdiscovery.exe)

You can edit the strings that show up in the discovery tool for your MeshCentral server using the following in the settings section of config.json:

```
    "LocalDiscovery": {
      "name": "My Pi Server",
      "info": "For local management of the computer lab."
    }
```

**Comment by merlinweb** [comment]
Amazing! both pic and Custom discovery messages

Bad news for Crypto... Rpi4 has no ARMv8 Crypto Extensions / AES instructions enabled
This might be critical for Rpi based VPN server projects, for example, very disappointing...

Merlinweb

**Comment by Ylianst** [comment]
This is why there is CHACHA TLS cypher suite. Should work faster on the Pi than AES.

**Comment by merlinweb** [comment]
> This is why there is CHACHA TLS cypher suite. Should work faster on the Pi than AES.

uhm I don't know, my fault... is something like google Adiantum ? Have to check in the future, if Rpi can support them...

**Comment by Ylianst** [comment]
Oh no, CHACHA20 is an encryption algorithm like AES that is works well when you don't have AES acceleration. It's supported in TLS 1.3.

**Comment by Ylianst** [comment]
Ok closing this one. Please feel free to open a new issue with more questions.
