### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by dev72** [Ylianst/MeshCentral#1196]
Is there some doc about mqtt configuration?
I can't see anything in config file and I don't know where to start to connect mqtt devices...

Thank you.

**Comment by Ylianst** [comment]
There is a blog on [MeshCentral MQTT support here](https://meshcentral2.blogspot.com/2019/10/meshcentral2-added-mqtt-support.html). To enable MQTT support, add the following in the settings section of config.json:

```
mqtt: {
  auth: {
    keyid: "Key1",
    key: "MySecretKey"
  }
}
```

In the blog there is a link to sample NodeJS code that will connect to MeshCentral along with screen shots of how to get the device login information and the MQTT console.

**Comment by dev72** [comment]
ok, thank you.
