### ISSUE TITLE
Audio routing of the Remote machine

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#1197]
Hi Ylian,

wondering if there is any possibility of routing of Audio from the Remote machine to the local laptop/device ? 

if No - can it be supported ?? 

regards
arun

**Comment by Ylianst** [comment]
You can use RDP over MeshCentral to do this, otherwise with the remote desktop solution built into MeshCentral, this is not possible and not something I will work on. If someone wanted to do a pull request with such a feature, of course I would review it.

**Comment by Arun0711** [comment]
Sure thanks Ylian

**Comment by N0vaSky** [comment]
Hey Ylian, I'm actually very interested in this feature. Would you be willing to work on it still? Happy New Years!
