### ISSUE TITLE
Database support and migration to Postgres

### ISSUE THREAD

**Issue by HLneoh** [Ylianst/MeshCentral#1198]
The default database for Mesh Central is NeDB. Plus, it supports the migration from NeDB to MongoDB. Here are the questions:
 
1. Is it possible to migrate from NeDB to Postgres?
2. If yes, how much effort would be approximately needed?

**Comment by Ylianst** [comment]
Currently, only NeDB (default), MongoDB and MariaDB and MySQL are supported. It's not currently possible to migrate to Postgres. Would need to add Postgres support first which would be a big effort.

**Comment by HLneoh** [comment]
Thanks for your reply. 
Could you give a few tips on adding Postgres support? _e.g. other than db.js, what files should I modify?_

**Comment by ryanblenis** [comment]
@HLneoh, if you're doing it right, no other files should need to be modified other than db.js.

**Comment by Ylianst** [comment]
Oh, if you are a developer and can help with adding PostgreSQL support, that would be wonderful! Yes, the only file that needs changing is db.js that is here: [https://github.com/Ylianst/MeshCentral](https://github.com/Ylianst/MeshCentral). If you make it work, I would really like to include it as part of the MeshCentral distribution.
