### ISSUE TITLE
Intel AMT network scan should display DNS name instead of IP address

### ISSUE THREAD

**Issue by Zveroloff** [Ylianst/MeshCentral#1199]
When I'm using the Network Scan feature, all devices appear in the list with their IP addresses. It would be better if the addresses be resolved to hostnames. Or there would be a batch operation to update names

**Comment by Ylianst** [comment]
Is the title correct for this issue? You want IP addresses?

**Comment by Zveroloff** [comment]
Changed. Previous title was to describe the current situation

**Comment by Ylianst** [comment]
Checked in a fix for this. Please be more specific in your title and issue in the future. It will be in MeshCentral v0.5.10 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.5.10 is published. Let me know if it works.

**Comment by Zveroloff** [comment]
Thanks you for fast implementation. Some remarks: it gets FQDNs (with domain suffix), but suffix is the same for almost all computers in the network. It becomes worse readable, especially with long domain names. For my case (and most others in large enterprises) the best solution would be to have just hostname (without suffix) for object name and additional field for domain suffix

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.11 with improvements. Let me know if it works.

**Comment by Zveroloff** [comment]
Works great! Thank you a lot
