### ISSUE TITLE
Possible add localisation with mesh type "Intel AMT Agent-less Policy"

### ISSUE THREAD

**Issue by LinkPhoenix** [Ylianst/MeshCentral#12]
hello,

is there a way to put a location devices that use only INTEL AMT to see them in the map?

**Comment by jsastriawan** [comment]
Unfortunatelly for Agentless AMT, it is slightly complicated. We can probe the location from the reported connection source address.  However you can always place the node manually on the map.

**Comment by LinkPhoenix** [comment]
Okay, but how can I put a node manually on the map?

**Comment by LinkPhoenix** [comment]
I just saw that we can add nodes with a right click on the map view but I can not add certain node

**Comment by LinkPhoenix** [comment]
Strange, I have no longer had a problem with another browser, I was first with EDGE then with Google Chrome, I no longer had this problem
