### ISSUE TITLE
Keyboard layout is ignored in Remote Desktop

### ISSUE THREAD

**Issue by francisru** [Ylianst/MeshCentral#120]
The keyboard layout is ignored for input in Remote Desktop.

**Steps to reproduce:**
Type the letter "Z" with the German Keyboard Layout ("QWERTZ") 

**Expected Result:**
Letter "Z"

**Actual Result:**
Letter "Y"

(Of course this also applies to all other keys that are mapped differently, this is just the most prominent example 🙂)

Let me know if i can help debug / test anything

**Comment by Ylianst** [comment]
I have a fix for this in the next version.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.0-a with keyboard fix. Please confirm it works.

**Comment by francisru** [comment]
works perfectly, thanks a buch!

**Comment by bostich83** [comment]
I do some related issue i guess.
The german umlaute such as äöü are working fine, but i can't get the backslash-key to get working.
On a german keyboard you have to press "alt-gr + ß" to get a backslash.

The only thing i get on the remote computer is the german letter ß .
It looks like the alt-gr key is completly ignored. Any ideas on that?

Thank you!
