### ISSUE TITLE
Batch user input with CSV

### ISSUE THREAD

**Issue by Zveroloff** [Ylianst/MeshCentral#1200]
I want to have an option to batch create users with CSV file. JSON is a bit complex for this task. Also, it's very straightforward to export users from any source in CSV format

**Comment by ryanblenis** [comment]
Not sure if you're waiting on a new feature for this to happen so you can continue setting up accounts or anything, but FYI, a simple conversion should do the trick for you once you've got your CSV.

https://csvjson.com/csv2json can do that for you.

**Comment by Zveroloff** [comment]
Thank you, I'll check the tool

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/da436275-401c-4aaa-8036-70072d3e369d)
all done!
please dont forget to donate ❤️ or have a look at my amazon wish list! https://www.si458.co.uk/2024/01/05/donation/
