### ISSUE TITLE
enhancement: add information when you manually upgrade MC server

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1201]
Hi , will be possible to add a clickable action on 
these "buttons" so before doing the upgrade process we can read what is changed/solved and take an informed decision?
![immagine](https://user-images.githubusercontent.com/62424179/79740492-0aa44d80-8300-11ea-9cca-784ef3bbfaea.png)

**Comment by Ylianst** [comment]
Not going to be doing that anytime soon. Feel free to take a look at the [GitHub commit log here](https://github.com/Ylianst/MeshCentral/commits/master).

**Comment by tradexsrl** [comment]
that link would be quite enough...if you can add it to that screen would be very userfull
