### ISSUE TITLE
Wildcard Cert Crashing Meshcentral

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1205]
Good day.

Environment: Linux 2 AWS RH 7 instance

I have copied the SSL wildcard cert issued to "*.domain.com" as opposed to "master.domain.com" (matching the hostname of the server), and when I start MeshC, I get the following which appears to be related to the cert and MongdoDB:

**sudo systemctl status -l  meshcentral.service**:

● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-04-20 17:55:43 UTC; 7min ago
 Main PID: 31805 (node)
   CGroup: /system.slice/meshcentral.service
           └─31805 /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec-user/node_modules/meshcentral

Apr 20 18:03:03 master.domain.com node[31805]: at ChildProcess.exithandler(child_process.js:294:12)
Apr 20 18:03:03 master.domain.com node[31805]: at ChildProcess.emit (events.js:194:15)
Apr 20 18:03:03 master.domain.com node[31805]: at maybeClose (internal/child_process.js:970:16)
Apr 20 18:03:03 master.domain.com node[31805]: at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Apr 20 18:03:03 master.domain.com node[31805]: killed: false,
Apr 20 18:03:03 master.domain.com node[31805]: code: 1,
Apr 20 18:03:03 master.domain.com node[31805]: signal: null,
Apr 20 18:03:03 master.domain.com node[31805]: cmd:
Apr 20 18:03:03 master.domain.com node[31805]: '/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 31805'                        }
Apr 20 18:03:03 master.domain.com node[31805]: ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Mesherrors.txt:**
-------- 4/20/2020, 5:55:45 PM ---- 0.5.9 --------

/home/ec2-user/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at serverStart (/home/ec2-user/node_modules/meshcentral/webserver.js:3630:46)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:267:17
    at /home/ec2-user/node_modules/meshcentral/db.js:976:115
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/home/ec2-user/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/ec2-user/node_modules/mongodb/lib/cursor.js:841:66)

-------- 4/20/2020, 5:55:51 PM ---- 0.5.9 --------

/home/ec2-user/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at serverStart (/home/ec2-user/node_modules/meshcentral/webserver.js:3630:46)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:267:17
    at /home/ec2-user/node_modules/meshcentral/db.js:976:115
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/home/ec2-user/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/ec2-user/node_modules/mongodb/lib/cursor.js:841:66)

-------- 4/20/2020, 5:55:57 PM ---- 0.5.9 --------

/home/ec2-user/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at serverStart (/home/ec2-user/node_modules/meshcentral/webserver.js:3630:46)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:267:17
    at /home/ec2-user/node_modules/meshcentral/db.js:976:115
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/home/ec2-user/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/ec2-user/node_modules/mongodb/lib/cursor.js:841:66)

-------- 4/20/2020, 5:56:04 PM ---- 0.5.9 --------

/home/ec2-user/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at serverStart (/home/ec2-user/node_modules/meshcentral/webserver.js:3630:46)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:267:17
    at /home/ec2-user/node_modules/meshcentral/db.js:976:115
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/home/ec2-user/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/ec2-user/node_modules/mongodb/lib/cursor.js:841:66)

**Comment by Ylianst** [comment]
When you say "I have copied the SSL wildcard cert", what did you do exactly? What file name did you copy where?

**Comment by jfp2** [comment]
The ones generated by SSL provider were copied over existing ones: "webserver-cert-private.key" and "webserver-cert-public.crt" using the same names. Note, this worked with a single domain SSL cert, but breaks with the wildcard cert.

thanks!

**Comment by jfp2** [comment]
It seems like a cert and key mismatch so I checked the hashes and sure enough, they don't match BUT, the single domain cert and key don't match yet don't kill the server.

**Comment by jfp2** [comment]
Neither do the default ones created after the initial install. Am I on the wrong trail?

**Comment by Ylianst** [comment]
Form the error, it looks like the .crt and .key files you have don't match. However, not sure how your are checking if they match using a hash? .crt and .key files can be edited using a standard text editor and so, you should be able to the the original files and cut & paste your certificate and key between the existing "---HEADER---" / "---FOOTER---" values.

Also, many providers don't directly give you the certificate private key, they have a system to load the private key into your computer certificate store.

I am not sure I can help much more, in general certificate and keys in PEM format are pretty simple. But the details are going to be with how your provider gave you the data. I had many cases in the past where people told me they got a new certificate and would show me a bundle of files only for me to point out the private key was not in the bundle.

**Comment by jfp2** [comment]
Sorry Y...got it fixed...cert assignment wasn't complete

**Comment by Ylianst** [comment]
Excellent! Thanks for reporting the success.
