### ISSUE TITLE
Create the admin user from the command line

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#1206]
## Problem Description
I was hoping to use meshctrl.js (or something else?) to create the first admin user. For our organization, this is the only piece of the puzzle that requires manual user intervention, everything else (Creating users, creating device groups etc) seems to be achievable via meshctrl.js

## Workaround
Perhaps using something like Selenium might work, but that could break later if the UI changes.

**Comment by Ylianst** [comment]
If you lost the admin account on a server, even MeshCtrl may not save you. However, you can run MeshCentral like this:

```
node node_modules/meshcentral --showusers
node node_modules/meshcentral --resetaccount [userid]
node node_modules/meshcentral --adminaccount [userid]
```

"ResetAccount" will unlock and remove 2FA from the account. "AdminAccount" will promote the account to admin. For example:

```
node node_modules/meshcentral --adminaccount user//admin
```

This requires server access as your going to directly run MeshCentral to do this.

If you want to create a new user with site administrator rights and you already have and existing user that is site admin, you can use `MeshCtrl AddUser --siteadmin` to create a new account.

Hope that helps,
Ylian

**Comment by Ylianst** [comment]
Checked in improvements to the account reset, admin and new create commands that are directly built into MeshCentral.

```
--createaccount [username] --pass [password] --domain (domain) --email (email)
--resetaccount [username] --pass [password] --domain (domain)
--adminaccount [username] --domain (domain)
```

If you create an account and call "adminaccount" right after, you should be good to go. This will be in MeshCentral v0.5.11 when it's next published.

**Comment by darryl-h** [comment]
Thanks Ylian!! You are a scholar and a gentleman! Will test when the 0.5.11 comes out.

If I understand correctly, then this would be the workflow to create a new Domain (domain4), a new device group (DeviceGroupName), and get the associated RemoteID:

```
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain4
# service meshcentral restart
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --createaccount admin --pass admin123 --domain domain4 --email admin@company.com
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --adminaccount admin --domain domain4
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js --url wss://server/domain4 --loginuser admin --loginpassword admin123 AddDeviceGroup --name DeviceGroupName
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js ListDeviceGroups
```

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.11 with the new commands. Yes, your flow looks correct. Let me know if it works.

**Comment by darryl-h** [comment]
After upgrading to MeshCentral v0.5.12, the `--createaccount` doesn't seem to be working as expected, here's my output:

```
root@ubuntu1804:/opt/meshcentral#/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain4
Done.

root@ubuntu1804:/opt/meshcentral# service meshcentral restart

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --createaccount admin --pass admin123 --domain domain4 --email admin@company.com
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
Done.

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --adminaccount admin --domain domain4
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
ERR: Warning: no saslprep library specified. Passwords will not be sanitized
Done.

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js --url wss://192.168.1.102/domain4 --loginuser admin --loginpassword admin123 AddDeviceGroup --name DeviceGroupName
Invalid login.
```
If I try and login to the server (https://192.168.1.102/domain4/) using the admin:admin123 credentials, it reports **"Login failed, check username and password."**

**Comment by Ylianst** [comment]
Looks this this error is MongoDB related. MeshCentral is trying to access MongoDB to create the account and it can't. [Example solution here](https://stackoverflow.com/questions/53266471/saslprep-warning-when-using-mongoclient-connect/57234317#57234317).

**Comment by darryl-h** [comment]
Unfortunately this does not resolve the issue, but the warnings have been removed :) Tested with **domain5** this time.

```
root@ubuntu1804:/opt/meshcentral# npm install saslprep
/opt/meshcentral
├── meshcentral@0.5.12
├── otplib@10.2.3
└─┬ saslprep@1.0.3
  └─┬ sparse-bitfield@3.0.3
    └── memory-pager@1.5.0

npm WARN enoent ENOENT: no such file or directory, open '/opt/meshcentral/package.json'
npm WARN meshcentral No description
npm WARN meshcentral No repository field.
npm WARN meshcentral No README data
npm WARN meshcentral No license field.

root@ubuntu1804:/opt/meshcentral# service meshcentral restart

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain5
Done.

root@ubuntu1804:/opt/meshcentral# service meshcentral restart

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --createaccount admin --pass admin123 --domain domain5 --email admin@company.com
Done.

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --adminaccount admin --domain domain5
Done.

root@ubuntu1804:/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js --url wss://192.168.1.102/domain5 --loginuser admin --loginpassword admin123 AddDeviceGroup --name DeviceGroupName
Invalid login.
``` 
Also, tested the login through the webpage (https://192.168.1.102/domain5/) using the admin:admin123 credentials, it reports "**Login failed, check username and password.**"

**Comment by darryl-h** [comment]
So some good news, and some bad news... 

When running MeshCentral v0.5.57, I get `Unable to find config.json.` so I re-installed both MeshCentral and MongoDB on brand new VMs. Unfortunately, same error, `Unable to find config.json.`

So I downgraded back to v0.5.12 (on the new VMs) and I got a bit further:

```
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain4
Done.

# service meshcentral stop

# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --createaccount admin --pass admin123 --domain domain4 --email admin@company.com
Done.

# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --adminaccount admin --domain domain4
Done.

# service meshcentral start

# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js --url wss://server/domain4 --loginuser admin --loginpassword admin123 AddDeviceGroup --name DeviceGroupName
{ Error: getaddrinfo EAI_AGAIN server:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'server',
  host: 'server',
  port: 443 }
```

In the above case, domain4 AND the admin user ARE created as expected, so technically, **this works**, however I'm unable to create the device group (syntax error?) and then list said device group, however, in the newest version (v0.5.57) this does not work, b/c of the error `Unable to find config.json.`

**Comment by Ylianst** [comment]
Ok, I will take a look at this. I will fix the original problem first of why it can't find the config.json.

**Comment by Ylianst** [comment]
When you get the `Unable to find config.json` error, can you tell me in what path your running `node`, what command you run and in what path the `config.json` is at? I am probably missing a path I should be looking at. Thanks.

**Comment by darryl-h** [comment]
I'm not sure exactly what you mean by the path, if I understand correctly, you are asking the full path to node, if so, it's `/usr/bin/node`. 

The full path to the config.json file is `/opt/meshcentral/meshcentral-data/config.json` 

I should have put the command I ran when I got the `Unable to find config.json` in my report, sorry about that. If I've misintrepreted your request all together, let me know!

Upgraded to v0.5.58, this is what I get when trying to add a domain (domain5) OS is Ubuntu 18.04.4 LTS.

```
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain5
Unable to find config.json.
```

**Comment by Ylianst** [comment]
Thanks for the detailed reports.

For `node meshctrl.js config`, I looked at the code and the MeshCtrl will basically look for config.json in the following paths:

```
./meshcentral-data/config.json
../meshcentral-data/config.json
```

I don't think this has changed in a long time. So, if you are in the folder just above "meshcentral-data" and run `node meshctrl config --show`, it should find it. I just added a line so if you run from meshctrl.js from within "meshcentral-data" it will also work. That will be in v0.5.59.

For adding a domain, when you add a domain your the meshctrl config command, all it does is edit the config.js and adds a domain section. You will need to restart the server to make the domain active before you can login and do things. For `wss://192.168.1.130/domain4/` will not be active until a server reset. This said, if you can login to the domain but it still does not work, let me know.

For the time sync, that is only required if you use 2FA tokens. In this case your not using them so, that would not be the source of the problem.

Let me try creating a domain called "domain4" and see if I get any issues on my development machine...

**Comment by Ylianst** [comment]
Ok, I did a full test run on my development server:

- Stopped the server.

`node meshctrl config --adddomain domain4`
`Done.`

`node meshcentral --createaccount adminx --pass adminx --domain domain4`
`Done.`

`node meshcentral --adminaccount adminx --domain domain4`
`Done.`

- Started the server
- Browsed to https://myserver/domain4
- Logged using "adminx"/"adminx", that worked.

`node meshctrl serverinfo --url wss://127.0.0.1/domain4 --loginuser adminx --loginpass adminx`
Got the information correctly.

`node meshctrl listusers --url wss://127.0.0.1/domain4 --loginuser adminx --loginpass adminx`
For list of users for that domain correctly.

I did notice that if you ask for a list of users with meshctrl.js and don't have the right to get the list, it will just hang waiting until you hut ctrl-c. I just fixed that, it will be in v0.5.59 and will now display "Access Denied".

I do want to note that any 'meshctrl config' operation needs to occur on the server itself since it will find and edit the config.json. For other operations, you can do them from a different computer. Let me know if that helps.

**Comment by darryl-h** [comment]
> So, if you are in the folder just above "meshcentral-data" and run node meshctrl config --show, it should find it.

ah hah! OK, so in Linux, I generally just specify the full path to something, and run it from whatever directory I'm in. In this case you **MUST** run meshctrl from the meshcentral installation directory. 

```
# cd /opt/meshcentral/
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --show
{
  "settings": {
    "Port": 443,
    "RedirPort": 80,
...}
```

```
# cd /
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --show
Unable to find config.json.


```

As a feature request (I can file a new one if needed, just let me know!) can meshctrl somehow use the installation directory instead of the relative directory from where the user ran the command from? If not, perhaps instead of returning "Unable to find config.json" some additional help like "Are you sure your running the command from the installation directory?" would be a fine work around, as always, thanks for all your hard work!

**Comment by darryl-h** [comment]
Technically, this feature request is complete, the admin user is created as expected. Here is the full sequence of commands, to create a new domain (domain10) and add the admin user.

```
# service meshcentral stop
# cd /opt/meshcentral/
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js Config --adddomain domain10
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --createaccount admin --pass admin123 --domain domain10 --email admin@company.com
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --adminaccount admin --domain domain10
# service meshcentral start
```

After doing this, I'm able to navigate to the subdomain for domain10 and login using the username `admin` and password `admin123` as expected. Checking in the UI within `My Users`, I'm able to observe that under the `Permissions` column, this user is listed as `administrator`

This PR has been ongoing for a while, and the issues I'm currently experiencing are not related to this feature request. I'm going to close this one out, and open 2 new ones, one for the problem with creating the device group (Invalid login), and one for the meshctrl for the config.js so it can be run from anywhere.

**As always, thanks for your all your hard work!**
