### ISSUE TITLE
Muitl-Tenants with DNS (subdomain)

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1212]
Hello,

us: Linux 2 AWS RH 7 instance

I've setup one tenant and it loads the main page but when I try to create the first account, it returns a black page with "not found." See config file below.

Wish there was more detailed documentation on setting up multi-tenants.

Thanks as always

Config.json:

{
  "__comment__" : "This is a sample configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "master.DOMAIN.com",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_MongoDbName": "meshcentral",
    "_MongoDbChangeStream": true,
    "_MongoDumpPath": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongodump.exe",
    "WANonly": true,
    "_LANonly": true,
    "_Minify": 1,
    "_SessionTime": 30,
    "_SessionKey": "MyReallySecretPassword1",
    "_SessionSameSite": "strict",
    "_DbEncryptKey": "MyReallySecretPassword2",
    "DbRecordsEncryptKey": "XXXXXXX",
    "DbRecordsDecryptKey": "XXXXXX",
    "__DbExpire": "Amount of time to keep various events in the database, in seconds. Below are the default values.",
    "_DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
.
.
.
.
.

    },
    "customer1": {
      "DNS": "customer1.DOMAIN.com",
      "Title": "Customer1",
      "Title2": "TestServer",
      "NewAccounts": 1,
      "Auth": "sspi",
      "Footer": "Test",
      "CertUrl": "https://customer1.DOMAIN:443/"
    },

**Comment by uldiseihenbergs** [comment]
did you remove default site(without any name) from config.json on purpose or just hide?

**Comment by petervanv** [comment]
maybe remove the the dashat  _mongodb name ? and did you set up an mongodb at your site ?

**Comment by jfp2** [comment]
> did you remove default site(without any name) from config.json on purpose or just hide?

to hide

**Comment by jfp2** [comment]
> maybe remove the the dash at _mongodb name ? and did you set up an mongodb at your site ?

I'll try...and I did setup MongoDB

**Comment by jfp2** [comment]
> > maybe remove the the dash at _mongodb name ? and did you set up an mongodb at your site ?
> 
> I'll try...and I did setup MongoDB

Didn't work.

**Comment by petervanv** [comment]
> > > maybe remove the the dash at _mongodb name ? and did you set up an mongodb at your site ?
> > 
> > 
> > I'll try...and I did setup MongoDB
> 
> Didn't work.

did you restart your meshcentral instance after changing the config.json ?

**Comment by jfp2** [comment]
> > > > maybe remove the the dash at _mongodb name ? and did you set up an mongodb at your site ?
> > > 
> > > 
> > > I'll try...and I did setup MongoDB
> > 
> > 
> > Didn't work.
> 
> did you restart your meshcentral instance after changing the config.json ?

yes...but it works now that I commented out Auth=sspi. What is ssspi?

THANKS!!!

**Comment by petervanv** [comment]
i dont know, but nice to hear its working

**Comment by jfp2** [comment]
> i dont know, but nice to hear its working

Thanks again.

**Comment by Ylianst** [comment]
"auth":"sspi" is for domain controller authentication, it only works when running on a Windows computer that is joined to a domain. Users will not see the login page anymore, instead will be automatically logged into the web site using their domain identity.
