### ISSUE TITLE
Server Stats Showing User Count for other Instances

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1213]
Linux 2 AWS RH 7

So I created an admin in a second instance (main and one tenant) and there is a single user (admin) in the tenant, but while logged into the tenant, the Server Stats shows the count of all users in both instances.

Thanks in advance!

**Comment by Ylianst** [comment]
Will answer this anyway for everyone else. The "My Server" tab shows information about the entire server, not per-domain.
