### ISSUE TITLE
Nodemailer Slow

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1214]
I'm seeing very slow emailing . Sometimes it goes out within a minute but about 2/3 of the time it takes 15 to 20 minutes.

Thanks

**Comment by Ylianst** [comment]
In "MyServer" / "Trace" tab, you can enable the "Email traffic" tracing and see in real-time what your server is doing and the response from the SMTP server. I just tried it myself below, in my case the SMTP server responded in 2 seconds. Let me know what you see.

![x](https://user-images.githubusercontent.com/1319013/79899787-1bb59300-83c2-11ea-8fea-ee8ca882488d.png)

**Comment by Ylianst** [comment]
Will close this as I am not sure there is anything I can do. If there is more data or something to be changed in MeshCentral, please re-open.
