### ISSUE TITLE
Translation support for notification events

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1215]
I found an other untranslated string

![Screenshot_17](https://user-images.githubusercontent.com/58996467/79909504-6284a680-841d-11ea-9763-4c5f481dfd96.jpg)

**Comment by Ylianst** [comment]
This will be more work since this is a server-side string. Same problem for the event log.

**Comment by petervanv** [comment]
No hurry, was just to inform you. i'll wait for it....

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
