### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1216]
in the documentation, there's an link about production setting in nodejs, that link produces an 404 not found! (http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf)

![Screenshot_18](https://user-images.githubusercontent.com/58996467/79909986-29006b00-841e-11ea-84fe-71b010ae2766.jpg)

**Comment by si458** [comment]
the documentation has moved online now instead of the PDF https://ylianst.github.io/MeshCentral/
