### ISSUE TITLE
MeshAgent fully utilising one CPU core

### ISSUE THREAD

**Issue by nroach44** [Ylianst/MeshCentral#1218]
As of 11:30 local time yesterday, all of my Windows agents started using one full thread of CPU:
![image](https://user-images.githubusercontent.com/518487/79986619-e94d8800-84de-11ea-9302-14b42178f06b.png)
(Host server^)

![Screenshot from 2020-04-22 21-19-25](https://user-images.githubusercontent.com/518487/79986660-ff5b4880-84de-11ea-90c5-1b2ab4287b75.png)
(VM with 6 cores^)

If I restart the service, or log into the computer via the display, the CPU usage comes back after ~30 seconds. Same result with a re-install of the agent.
![Screenshot from 2020-04-22 21-14-46](https://user-images.githubusercontent.com/518487/79986390-8d82ff00-84de-11ea-9593-49aa8bfa1352.png)

I don't have any sessions open, but connecting, changing the detail settings and disconnecting has no effect.

This doesn't seem to effect my Linux hosts, and there's no constant stream of traffic to the server, and there's no change if the server is stopped.

Also to note, the server upgrade, according to the logs, was started at 1AM the following morning, from 0.5.10 to 0.5.11.

**Comment by krayon007** [comment]
Is this a 32bit agent or a 64bit agent?

**Comment by krayon007** [comment]
And which version of windows are running on your agent machines?

**Comment by Ylianst** [comment]
Ok, I just marked MeshCentral v0.5.11 as latest in NPM so I have more time to look into this.

**Comment by Ylianst** [comment]
I just noticed it was an upgrade to 0.5.11. Can you try 0.5.12? That one has new MeshAgents with a lot of bug fixes.

**Comment by Ylianst** [comment]
This is super weird since 0.5.10 to 0.5.11 has almost no agent changes at all, it's all mostly server fixes. There are new MeshAgents in v0.5.12 (latest OpenSSL) I would have expected issues with 0.5.12.

**Comment by nroach44** [comment]
@Ylianst The 0.5.11 upgrade happened at 1AM the following morning, so it wasn't that, the issue started at 2330 the night before. The server has automatically updated to 0.5.12, and the problem is still present.

@krayon007 Windows Server 2012 R2 (win 8.1), 2016, 2019, and Windows 10s. All 64 bit. I only run these versions so I can't tell you if it's happening on older versions.

**Comment by nroach44** [comment]
Is there some kind of verbose log I can turn on or a way to start the agent where it'll dump out into?

**Comment by Ylianst** [comment]
This is really odd, if we could make the same thing happen on your computers, it would be super easy to debug and fix. Can you open a command prompt and run `meshagent.exe -info`? You should see this:

```
Compiled on: 18:14:14, Apr 21 2020
   Commit Hash: 8777d32d06ee2655a7b022f1b5900145d860b1cf
   Commit Date: 2020-Apr-21 16:37:30-0700
Using OpenSSL 1.1.1g  21 Apr 2020
```

Then, stop the MeshCentral service and run the agent in console mode with 'meshagent.exe -run`. Let us know if you get the same problem. Thanks.

**Comment by nroach44** [comment]
```
Compiled on: 18:14:14, Apr 21 2020
   Commit Hash: 8777d32d06ee2655a7b022f1b5900145d860b1cf
   Commit Date: 2020-Apr-21 16:37:30-0700
Using OpenSSL 1.1.1g  21 Apr 2020
```

```
C:\Program Files\Mesh Agent>MeshAgent.exe run
MeshCentral2 Agent
Connecting to: wss://meshcentral.haven:443/agent.ashx
Connected.
Server verified meshcore... Launching meshcore...
```

No console output after that, and after a handful of seconds, CPU usage starts back up.

**Comment by Ylianst** [comment]
Ok, go in the agent console for that agent and push the "recovery core". Let us know if the CPU is better after you do this.

![x](https://user-images.githubusercontent.com/1319013/80043984-0589fe80-84b8-11ea-8bde-005886af3b57.png)

**Comment by nroach44** [comment]
I've left it two minutes and it seems to have settled down - no extra terminal info though.

**Comment by Ylianst** [comment]
The MeshAgent has a JavaScript engine that runs a "core" sent by the server. The recovery core is really minimal, it's good news that it settled down, but the agent can't do much in this mode. I think just remote files will work. Now, I got to find a way to debug this...

**Comment by nroach44** [comment]
@Ylianst If you're up for it I could probably spin up a VM for you?

**Comment by Ylianst** [comment]
Yes, that would be wonderful! A throw away VM would be great. My Email address is on my [contact page](https://www.meshcommander.com/contact-information).

**Comment by nroach44** [comment]
Sweet, It'll take a bit of time so I'll send it through when it's done, but since I'm in GMT+8 it'll probably be tomorrow for you. Cheers for your help so far.

**Comment by Ylianst** [comment]
Ok, thank you SOO much. Certainly a top priority issue. Much appreciated.

**Comment by nroach44** [comment]
Okay, email sent at 9:17 local time (one hour ago) - let me know when you receive/see it

**Comment by Ylianst** [comment]
I double checked, I don't see anything. You used gmail?

**Comment by Ylianst** [comment]
Many thanks. If the agent is connected to my MeshCentral server it works well, but not on yours. I now realize I should have asked if your server has plugin's, I imagine it does. Let me know if this is the case that was plugins you are using. Plug-in's sort of "void the warranty" because I do no testing on them and they do change the agent's behavior.

**Comment by nroach44** [comment]
Yup, I do have four plugins in use:
Event Log
File Distribution
Last Page
Script Task

When they're all turned off the CPU usage drops. I'll go through and identify which one/combination is causing it.

Cheers for the help and sorry for the wild goose chase!
