### ISSUE TITLE
[Question] Stable / Latest Releases

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1220]
I was recently [asked](https://github.com/ryanblenis/MeshCentral-RoutePlus/issues/9) about having you bump up a stable version for the plugins version checking being broken before the patch (e.g. 0.5.7 "stable" users can no longer upgrade any plugins without feeling like they're on the bleeding edge in the "latest" channel)

I like having the two channels, but is there any plan to separate the features/functionality in the branches, where only "fixes" go into stable and "new" functionality is separated off into the latest channel until such a testing period has passed that the new functionality is then released to stable?

Thank you.

**Comment by Ylianst** [comment]
I now realize that your fix is in 0.5.10 and stable is marked as 0.5.7. I will move the "stable" to 0.5.11 since so far, it's seem ok. There is no plan for two branches, I just mark a version a "stable" in NPM and let the "latest" version run forward. Of course, there will be plenty of debate as to what version should be the "stable" one.

**Comment by Ylianst** [comment]
Ok, moved stable to 0.5.11.

**Comment by ryanblenis** [comment]
I'm sure there will be debate. Thanks for the bump. I understand the nuances of rapid-release and maintaining a "stable" version. If MC is going to have it I would suggest forking 0.5.11 to a "stable" branch, utilizing feature branches for new functionality that get merged to master/latest, and for each issue you work on, branch the issue, then it could be merged to the appropriate channel depending on new functionality vs a fix for something that exists in stable.

Thank you!
