### ISSUE TITLE
Agents won't come back after certificate changes 

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1221]
Hello!
i changed my Apache reverse proxy LetsEncrypt certificate and i noticed that my local Windows agents won't come back in devices. Linux agents is fine.
in Docker log i see the following line right after certificate change:
`Agent connected with bad signature, holding connection (undefined).`

after MC restart there is no more line in log, but Agents still are offline. 
Then i switched on Server trace, and manually restarted Agent Windows service, but Agent still won't appear in MC.
![image](https://user-images.githubusercontent.com/60253253/80061205-4b3adb80-8539-11ea-9cb8-e5642c411808.png)

how to diagnose next?

**Comment by Ylianst** [comment]
As a temporary fix, try adding the following line to the settings section of config.json:

`"ignoreagenthashcheck": true`

This will skip the Let's Encrypt certificate check. Can you specify what MeshCentral server version you are running? Are you running the server on Windows or Linux? Thanks.

**Comment by uldiseihenbergs** [comment]
i'm on MC 0.5.11 - stable channel, MC is running on Docker, but in base on Debian Linux.
when i add `"ignoreagenthashcheck": true`, restarted MC twice, then all agents are gone, none comes back, here is a server trace:
![image](https://user-images.githubusercontent.com/60253253/80065142-50e8ef00-8542-11ea-819a-366098dc8c4f.png)

then i removed `"ignoreagenthashcheck": true`, restarted MC, and all agents are back up except LAN Windows agents..

**Comment by uldiseihenbergs** [comment]
i tried commands suggested in #1218 
@krayon007 are there something with Agents?
![image](https://user-images.githubusercontent.com/60253253/80129432-b7e8c100-859f-11ea-927f-e1caa56eed05.png)

**Comment by Ylianst** [comment]
Hi. Sorry for the delay (I am swamped). First, the "unable to open database" error occurs when you have two agents trying to use the same "meshagent.db" file. The first agent will get an exclusive lock on this file, this is by design. When the second agent tries to open the file, it will fail like this. Stop the "MeshAgent" service and try again.

As for the original problem, there is something I am really missing because we change the TLS certificate in front of MeshCentral all the time with reverse proxies and MeshCentral is designed to handle this.

Are you saying that you change the TLS certificate in Apache, but nothing what changed in "meshcentral-data"? I also have to investigate why there is an "undefined" in this line:

```
Agent connected with bad signature, holding connection (undefined).
```

It's as if the remote IP address or port of the socket does not exist. What version of NodeJS are you using?

I can add more debugging in the next version so that when you enable tracing on `agent`, it will show more details of the problem.

**Comment by uldiseihenbergs** [comment]
Hi,
about "unable to open database" - i stopped Agent service, looked in Windows Task Manager, and there are no meshagent running. then i run it manually as in picture above, and still the same error. interesting, what a process then is locking this DB file. i tried on two of my windows and error are the same. 
What i did next: I reinstalled agent on one of my windows, and it then connects to MC just fine. so no problem with connection to MC - all my three windows are on the same LAN.
on second windows after a restart, i stopped Agent service, run it manually again, and there is error with certificate.
![image](https://user-images.githubusercontent.com/60253253/80247585-f7cea780-8676-11ea-9b5c-a910835cc273.png)
so a question is - how agent knows that certificate on server side was changed, and how agent updates itself with new certificate?

and yes, i'm changed certificate only on Apache reverse proxy, MC all stays the same. 

according node version:
![image](https://user-images.githubusercontent.com/60253253/80248028-cf937880-8677-11ea-8f4b-20af769908ec.png)

**Comment by Ylianst** [comment]
The agent has a `meshagent.msh` file that includes the server connection information, it will look something like this:

```
MeshName=Home Computers
MeshType=2
MeshID=0xXXXXXXXXXXXXXXXXXXX
ServerID=XXXXXXXXXXXXXXXXXXXX
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx
```

The serverID is the hash of the `agentserver-cert-public.crt` certificate that is located in `meshcentral-data`. So when the agent connects, it will see the certificate of the reverse proxy, then continue to connect to MeshCentral and ask MeshCentral for a proof that it's the right server. MeshCentral will use the `agentserver-cert-public.crt` to validate itself and will also tell the agent what TLS certificate it should have seen.

Hope that helps,
Ylian

**Comment by uldiseihenbergs** [comment]
thanks for clarifying, but looks like something is wrong here. i don't change my `agentserver-cert-public.crt`, but certificate is loaded from Apache every time MC starts.
interesting that all Linux Agents are working just fine, i have one Remote Windows agent, and it works too.
of course, i can reinstall affected windows agents without problem, but then i can't test this bug any further..

**Comment by Ylianst** [comment]
So to clarify, if you reinstall the agent, it starts working again? Also, your using "certurl" in your config.json to have MeshCentral load the Apache TLS cert each time MeshCentral starts?

**Comment by Ylianst** [comment]
Since you have a computer you can test with, can you just stop the Windows agent, rename `meshagent.db` to `meshagent-backup.db` and start the agent again? Let me know if it magically connects. Thanks.

**Comment by uldiseihenbergs** [comment]
> So to clarify, if you reinstall the agent, it starts working again? Also, your using "certurl" in your config.json to have MeshCentral load the Apache TLS cert each time MeshCentral starts?

Yes to both questions.

> Since you have a computer you can test with, can you just stop the Windows agent, rename `meshagent.db` to `meshagent-backup.db` and start the agent again? Let me know if it magically connects. Thanks.

i can copy database, then i tried to run agent again, but still "Unable to open database" error.

**Comment by uldiseihenbergs** [comment]
> i can copy database, then i tried to run agent again, but still "Unable to open database" error.

@Ylianst i just trying to get attention to this. about "Unable to open database" - looks like it's windows 10 permission issue - when i run `meshcentral.exe -run` as admin, then no more error about database, but original certificate error still persist - i get the same `Server certificate mismatch`

**Comment by uldiseihenbergs** [comment]
I just tried to run MC with `node node_modules/meshcentral/meshcentral.js --debug agents`, and then started Agent manually with trace running, got this:
![image](https://user-images.githubusercontent.com/60253253/80797804-76fa3900-8bab-11ea-8ab6-524978a2c0bb.png)
on Agent side i still see `Server certificate mismatch`
if anyone have idea what else to try to debug this issue, just let me know.

**Comment by Ylianst** [comment]
If you server public? If it's ok, first run "meshagent.exe -info" and get this information:

![image](https://user-images.githubusercontent.com/1319013/80892285-ab3e2a00-8c7d-11ea-8cf5-10cdfb25a0c5.png)

Then, take the meshagent.db, meshagent.msh and meshagent.log, zip them and send them to me privately using [my contact information here](https://www.meshcommander.com/contact-information). Feel free to use my PGP key.

This is probably the only way to debug this and I am very curious to see what the problem is.

**Comment by Ylianst** [comment]
@uldiseihenbergs send them the right information requested and I looked into this. This is not a MeshCentral problem, but rather how the server was setup.

In the .msh file of the Windows agents, the "ServerID" is not correct and so, the agents correctly refuse to connect. Note that agents will do the server check once then cache the TLS certificate they saw. When re-connecting, if they see the same TLS certificate, they skip the "ServerID" check. So, it's possible to setup a MeshCentral server, deploy a .msh file, then reset the server certificate and still have agents connect until the TLS cert changes.

My guess here is that two MeshCentral servers may have been setup at some point to the same database somehow with two different "meshcentral-data" folders.

In any case, this is nothing I can fix in MeshCentral. All windows agents will need to have their .msh file fixed.

**Comment by uldiseihenbergs** [comment]
Thanks @Ylianst  for a help, i will close this issue now, and will open a new one with question about a move to now server, as it seems this was my "mistake" with this issue
