### ISSUE TITLE
Notification remote device

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1225]
Hey Ylian,

after upgrading to version 0.5.12 the notification don't reach the remote computer.  The shutdown of the firewall does not help, so downgraded to version 0.5.11 (stable) the notification is working again as it should be, even with the firewall activated.

logging message ents of that device (pic 1)
![Screenshot_19](https://user-images.githubusercontent.com/58996467/80101199-632e5180-8571-11ea-909d-dcf5a18184cd.jpg)

servertracing (pic 2)
![Screenshot_20](https://user-images.githubusercontent.com/58996467/80101229-6cb7b980-8571-11ea-80ac-57e3dff0bd00.jpg)

Greets Peter

**Comment by krayon007** [comment]
This issue is actually caused by the same bug as #1219 which I fixed yesterday. It will be in the next agent update which should be imminent.

**Comment by Ylianst** [comment]
Should be fixed in 0.5.13.

**Comment by petervanv** [comment]
fixed, thx
