### ISSUE TITLE
RasPi Device Image

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1228]
Just happened to add a pi for testing and noticed the rasPi device icon is no longer selectable (from what I can tell this occurred when the virtual machine device icon was added).

Just thought I'd note it here as I didn't have the time to find and the issue and submit a PR until later tonight.

**Comment by Ylianst** [comment]
!!! How did I not notice this... Your right. Fixing now.

**Comment by Ylianst** [comment]
Check in the fix, will be in 0.5.14. For now, you can search for "p10setIcon(7)" in default.handlebars and fix it, or use the mobile web app which works.

**Comment by ryanblenis** [comment]
Thank you as always.
