### ISSUE TITLE
How to query the System Details using API

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1229]
How to query the nodes id and its host name details using API call or Database query in the mesh central?

**Comment by ryanblenis** [comment]
Oddly enough, just a couple hours ago I tossing up the idea of opening a ticket requesting a formal API, which would help with everything from plugins to front-end redesigns, as well as normalize some of the calls that are going on in the front end, making it easier for others to contribute to the project- so your timing is great.

As far as your question, where in the app are you attempting to query them, because you need to find the right object if you're on the back end. If you're doing it on the front end (javascript in the web portal) then all the node details are right there in the "nodes" variable.

Feel free to add more details about what you're attempting to accomplish and how so someone can supply the best info.

**Comment by aimdharma1990** [comment]
I am using back-end app to open the database . Right now i am using the Database dump  "node meshcentral --dbexport" and reading the data from the that. Its because very complex.

**Comment by aimdharma1990** [comment]
> Oddly enough, just a couple hours ago I tossing up the idea of opening a ticket requesting a formal API, which would help with everything from plugins to front-end redesigns, as well as normalize some of the calls that are going on in the front end, making it easier for others to contribute to the project- so your timing is great.
> 
> As far as your question, where in the app are you attempting to query them, because you need to find the right object if you're on the back end. If you're doing it on the front end (javascript in the web portal) then all the node details are right there in the "nodes" variable.
> 
> Feel free to add more details about what you're attempting to accomplish and how so someone can supply the best info.

I am using back-end app to open the database . Right now i am using the Database dump "node meshcentral --dbexport" and reading the data from the that. Its because very complex.

**Comment by ryanblenis** [comment]
Looking directly at the dumped database, assuming you're querying it with something I can tell you the following:

- type: 'node' is for general node info (hostname / display name / OS / logged in user / etc.). the node id is the _id here
- type: 'lastconnect' is for last connect time / info, it is matched to the node in that the _id is 'lc' + node id
- type: 'ifinfo' is for network info, it is matched to the node in that the _id is 'if' + node id
- type: 'sysinfo' is for os / hardware info, it is matched to the node in that the _id is 'si' + node id

Hope that helps.

**Comment by Ylianst** [comment]
A new notes on the topic of a MeshCentral API. There is certainly an API but currently not documented, the best way to see it in action is to add `&trace=1` to the URL and open the browser console. You will see everything the web application sends and receives.

![image](https://user-images.githubusercontent.com/1319013/80244547-f0c77b00-861d-11ea-8f82-57e0d2b32c4c.png)

So, you need to connect a websocket to `https://myserver/control.ashx`, authenticate and you get to send and receive JSON. Lucky, there is a sample of NodeJS code that does this, it's `MeshCtrl.js`, it's a tool that comes with MeshCentral, you run it like this `node node_modules/meshcentral/meshctrl`.

![image](https://user-images.githubusercontent.com/1319013/80244817-7e0acf80-861e-11ea-827d-019c8ef7a1ac.png)

It's a command line tool that allows you to perform operations on MeshCentral. Some people I know just script this tool to get stuff done like creating accounts, listing devices, etc. You can use it as sample code or use it as-is.

Finally, if you want to, for example, get all the devices hardware details. You can request that I add a command to MeshCtrl to do this. I can add it in and you can scrip MeshCtrl. Hope that helps.

**Comment by guerby** [comment]
Easy in CLI using : https://github.com/vi/websocat

binaries and package : https://github.com/vi/websocat/releases

On my debian 10 (buster):

```
LOGIN=xxx
PASS=yyy
FQDN=my.site
/some/where/websocat_amd64-linux --header="x-meshauth: $(echo -n $LOGIN|base64),$(echo -n $PASS|base64)"  wss://$FQDN/control.ashx
```

Works

**Comment by Ylianst** [comment]
Coming up in MeshCentral v0.5.21, there is a new "deviceinfo" command in MeshCtrl that allows you to get all the same data as the details page in text form. You can also add --json to get a JSON output. This will be published later today.

![MC2-MeshCtrl-DeviceInfo](https://user-images.githubusercontent.com/1319013/80891929-1b4bb080-8c7c-11ea-9855-20f7c8ba6cba.png)

**Comment by Ylianst** [comment]
MeshCentral v0.5.21 is published. Feedback appreciated.

**Comment by aimdharma1990** [comment]
> MeshCentral v0.5.21 is published. Feedback appreciated.

Do we have any release notes for this version. So that it will help what are new enhancements are delivered ?

**Comment by Ylianst** [comment]
There is no release notes, but you can look at the [GitHub commit log](https://github.com/Ylianst/MeshCentral/commits/master). Would be nice to have a release notes, but with only two full time people working on it, it's already too much work as it is.
