### ISSUE TITLE
CAD doesn't not work on Hyper-V Server

### ISSUE THREAD

**Issue by sorvani** [Ylianst/MeshCentral#123]
When running Hyper-V server 2012 R2 and 2016, the CTRL-ALT-DEL button does nothing.
![image](https://user-images.githubusercontent.com/3302372/54078759-79a51b00-4293-11e9-8d9d-ab8b508c808e.png)

**Comment by krayon007** [comment]
Can you check this setting on your Hyper-V system? I ran across this in the documentation from MSFT, that says the local policy on the system must be configured to allow software simulation of Ctrl-Alt-Del... I've personally not run into this issue, so maybe Hyper-V is configured differently by default?
Here's the except:

The local security policy of a computer must be configured to allow services and applications to simulate a SAS. To configure the policy, modify settings in the Group Policy Editor (GPE) Microsoft Management Console (MMC) snap-in. The GPE settings that control delegation are in the following location:
Computer Configuration | Administrative Templates | Windows Components | Windows Logon Options | Disable or enable software Secure Attention Sequence

**Comment by krayon007** [comment]
If this is indeed an issue, and setting this resolves it, I can look into setting this policy on agent installation or something...

**Comment by sorvani** [comment]
I will check, but as a point of note, I also have ScreenConnect installed on these systems and it can send Ctl-Alt-Del, just fine.

**Comment by sorvani** [comment]
The related registry key does not exist on the Hyper-V servers.
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsLogon2::SoftwareSASGeneration

**Comment by sorvani** [comment]
Adding that setting and rebooting the server for good measure, does not make it work.
![image](https://user-images.githubusercontent.com/3302372/54080023-58e9bf00-42ad-11e9-83c8-f9ec9ff0bf56.png)

**Comment by krayon007** [comment]
I haven't really used Hyper-V Server much, so can you share some more details? I was under the impression that Hyper-V Server didn't actually have a user interface, ie: it was a headless system?  Are you connecting the Remote KVM into the Hyper-V Server, or one of it's VM's?

I will probably need to recreate your environment to see what is going on. I tested it with Server 2019, with the Hyper-V role, and it seems to work, so I'll probably need to setup an actual Hyper-V Server. Can you share some details on your environment, so I can try to reproduce what is going on?

Thanks

**Comment by sorvani** [comment]
2 hyper-v server 2016. 1 hyper-v sererect 2012R2. All 3 domain joined on the same network. Nothing special.

**Comment by sorvani** [comment]
Note, I use Hyper-V Server. This is not the same as Server Standard with the Hyper-V role added.
