### ISSUE TITLE
Return problem: agents are not automatically added to MeshCentral

### ISSUE THREAD

**Issue by rau-alvin** [Ylianst/MeshCentral#1230]
Hello!

My problem form #1076 has been returned (it may not have been completely resolved).

 When I install an agent on any platform, my agents are not automatically added to MeshCentral.
But when I start Mesh with root - everything is fine. If I restart the agent with the usual user, the agent will appear.

This is strange, but sometimes, when I install the agent after restarting the service as an rtadmin, I see my new agents. But after few time the agent is not automatically added to the Mesh after install.

Other functions without root work without problems (desktop, console)

Permissions for db:
-rwxrwx--x  1 rtadmin rtadmin    869 Oct 10  2019 meshcentral.db

I have old version MongoDB for my Linux release (ALTLinux). It's latest release for my OS.
 Current stable release is 4.2.

mongo-3.6.14-alt1
mongo-server-mongod-3.6.14-alt1

Starting with version 0.5.12, I have errors in the log file:

-------- 2020-4-23 10:23:22 ---- 0.5.12 --------

(node:31236) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: meshcentral.smbios index: _id_ dup key: { : "node//SBdyBXU6CZYMvWFziouFKhVytPS6EP23GgYNRZ2Bt0V@zchjW1Lz91s3$kdaYArS" }
    at Function.create (/home/rtadmin/node_modules/mongodb/lib/core/error.js:44:12)
    at toError (/home/rtadmin/node_modules/mongodb/lib/utils.js:150:22)
    at coll.s.topology.update (/home/rtadmin/node_modules/mongodb/lib/operations/common_functions.js:373:39)
    at handler (/home/rtadmin/node_modules/mongodb/lib/core/sdam/topology.js:973:24)
    at wireProtocol.(anonymous function) (/home/rtadmin/node_modules/mongodb/lib/core/sdam/server.js:437:5)
    at /home/rtadmin/node_modules/mongodb/lib/core/connection/pool.js:420:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

-------- 2020-4-23 10:23:22 ---- 0.5.12 --------

(node:31236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------- 2020-4-23 10:23:23 ---- 0.5.12 --------

(node:31236) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: meshcentral.smbios index: _id_ dup key: { : "node//QcicdolGSrm1$ZthO8cFh@9TSoKpzoJ$6ySG2qkz1XtEAWvKBSNSV$i7oAbf@rpv" }
    at Function.create (/home/rtadmin/node_modules/mongodb/lib/core/error.js:44:12)
    at toError (/home/rtadmin/node_modules/mongodb/lib/utils.js:150:22)
    at coll.s.topology.update (/home/rtadmin/node_modules/mongodb/lib/operations/common_functions.js:373:39)
    at handler (/home/rtadmin/node_modules/mongodb/lib/core/sdam/topology.js:973:24)
    at wireProtocol.(anonymous function) (/home/rtadmin/node_modules/mongodb/lib/core/sdam/server.js:437:5)
    at /home/rtadmin/node_modules/mongodb/lib/core/connection/pool.js:420:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

-------- 2020-4-23 10:23:23 ---- 0.5.12 --------

(node:31236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Most likely that’s why I don’t have an automatic backup (in one of the topics I read that the commands are different for older versions). Maybe this is also associated with the automatic addition of agents?

What is the problem?

Thanks for the help!

**Comment by Ylianst** [comment]
Interesting. I will try to replicate this.

**Comment by Ylianst** [comment]
I realize that I use MongoDB 4.x on my servers. One thing you can do is safely delete the SMBIOS table from MongoDB and start the server again. It will fill back up, it does not contain any critical data.

**Comment by Ylianst** [comment]
Ok, in the next version of MeshCentral v0.5.14, you can add:

```
"smbios": false
```

To the domain section of config.json and it will not save SMBIOS information in the database anymore. This is just a temporary workaround until I can do more testing.

**Comment by rau-alvin** [comment]
Thank you @Ylianst for your help!

I configured a new setting. Now I do not see a problem in the log file. After a few hours, I check the automatic addition of the agent, because this error does not appear immediately after the reboot.

**Comment by rau-alvin** [comment]
@Ylianst I checked the addition automatically agent. Unfortunately, this problem has not been resolved. What do you recommend?

**Comment by rau-alvin** [comment]
I will create a separate question on adding agents, the problem with the database is resolved.
