### ISSUE TITLE
Untranslated string (email)

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1234]
![Screenshot_21](https://user-images.githubusercontent.com/58996467/80210022-5114e780-8633-11ea-8c79-fa8f121e10ed.jpg)

**Comment by Ylianst** [comment]
You are right, I have to fix that.

**Comment by Ylianst** [comment]
Fixed this, it will be in MeshCentral v0.5.20.

**Comment by petervanv** [comment]
yet translated in the translation file #1274
