### ISSUE TITLE
Keys to Toggle Between Displays?

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1235]
Feature request:

keys to toggle between displays.

thank you
JP

**Comment by Ylianst** [comment]
Well, the problem is, if I have keys for this... it's keys that will not be sent to the remote computer. Let me know if you have an example of what keys you would use. Thanks.

**Comment by jfp2** [comment]
Maybe keys won't work but perhaps adding large buttons to avoid pull down, eg:

![image](https://user-images.githubusercontent.com/9053454/80247852-c638ea80-863c-11ea-832d-25910cb9001b.png)

**Comment by Ylianst** [comment]
Buttons or icons would be interesting. I can take a look at this.

**Comment by jfp2** [comment]
Thanks in advance!

**Comment by p-m-tech** [comment]
I would love buttons to make switching between displays fast!

**Comment by si458** [comment]
You now see little screen icons instead which should be helpful
