### ISSUE TITLE
Letsencrypt generation error Upgrade version 5.13

### ISSUE THREAD

**Issue by sicutdeux** [Ylianst/MeshCentral#1236]
Hi, i had installed version 4.9 i think, then go to the web panel hit the upgrade button an it came back but letsencrypt cert was not installed.

trying to run the server manually i this this error:

MeshCentral HTTP redirection server running on port 80.
WARNING: Invalid Let's Encrypt host names.
MeshCentral v0.5.13, WAN mode.

It was working before, domain still good, but don't know what could be the problem.

Thanks.

**Comment by ryanblenis** [comment]
I think this was an issue with an update somewhere around ~4.9.x. If you ignore the cert warning (or ho in via http) and go to Server -> Console and run `lecheck` I think that was the fix, assuming you've got all the right info in your config.json.

**Comment by sicutdeux** [comment]
My config as not changed, i deleted the letsencrypt directory and it cannot generate a new cert
no idea why

**Comment by Ylianst** [comment]
Probably an easy fix. In your config.json, just add "names" and set it to your domain name, for example:

```
  "letsencrypt": {
    "email": "xxx@hotmail.com",
    "names": "meshcentral.com",
    "production": false
  }
```

I think in the past, if you did not put "names", it would default to the name in "cert". That should fix it. I can add the default if "names" is not specified in a future version.

**Comment by sicutdeux** [comment]
That fixed it, back online, thanks.

**Comment by Ylianst** [comment]
Nice! Just pushed a fix in GitHub for this, it will default correctly again starting with v0.5.14.
