### ISSUE TITLE
Screen Quality vs ScreenConnect 

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1237]
I notice that compared to ScreenConnect's highest quality setting, MC's highest quality screen settings (90% quality & fastest frame rate) don't compare. ScreenConnect's highest quality is crisp and clear, and the medium setting is more comparable to MC's (blurry).

Also, up and down scrolling in browser/explorer windows is jerky in MC and smooth in ScreenConnect.

Any insight?

Thank you

**Comment by Ylianst** [comment]
MeshCentral uses JPEG encoding because it needs to be decoded in the browser. Could look into going all the way to 100% or using PNG.

**Comment by jfp2** [comment]
100% or PNG? how would I go about that? Thanks

**Comment by jfp2** [comment]
Thx... where can I obtain the entire settings variables for config.json?

Which one is it: AllowQualityDesktop or AllowHighQualityDesktop?

Thank you!

Jesus F. Peña, CCFT
e-forensics
6262 Bird Rd. Suite 2B<x-apple-data-detectors://3/0>
Miami, Florida 33155<x-apple-data-detectors://3/0>
P (305)667-4603, ext 401<tel:(305)667-4603;401>, (800)967-7697<tel:(800)967-7697>
F (305)667-4472<tel:(305)667-4472>
M (305)788-9626<tel:(305)788-9626>
jpena@e-forensicsinc.com<mailto:jpena@e-forensicsinc.com>
www.e-forensicsinc.com<http://www.e-forensicsinc.com/>

MIAMI | ATLANTA | CHICAGO | HOUSTON | DALLAS | DENVER | TUCSON | PHOENIX | PHILADELPHIA | PROVIDENCE | INDIANAPOLIS

This message and any attachments to it contain information which may be confidential and privileged.  Unless you are the addressee (or are authorized to receive for the addressee), you may not use, copy or disclose to anyone the message or any information contained in or attached to the message.  If you have received the message in error, please advise the sender by reply e-mail and delete the message.  Thank you.

On Apr 24, 2020, at 10:53 PM, Ylian Saint-Hilaire <notifications@github.com> wrote:

﻿

MeshCentral uses JPEG encoding because it needs to be decoded in the browser. Could look into going all the way to 100% or using PNG.

**Comment by Ylianst** [comment]
There is no way to do PNG right now. For the settings, this is the exact line that goes in the settings section of config.json:

```
"AllowHighQualityDesktop": true
```
