### ISSUE TITLE
Missing My Devices Column View with Sort

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1238]
Please see image below. One of my domains is missing the My Devices column view with sort option but the main site is fine.

THANKS!!

![image](https://user-images.githubusercontent.com/9053454/80270561-35d3c780-8687-11ea-91b5-bf5f2b07b60b.png)

**Comment by Ylianst** [comment]
Interesting! Should be a quick fix.

**Comment by jfp2** [comment]
silly me - doesn't appear unless a device is added.

sorry!

**Comment by Ylianst** [comment]
Yes! I just figured this out myself :) Thanks for closing.
