### ISSUE TITLE
Meshcmd/router with Microsoft Remote Desktop for Windows.

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1239]
Hey. I am using meshcmd in a macbook. I add a port, and then connect through the Microsoft Remote Desktop utility. On mac os, this works great. I wanted to do the same in Windows. I tried it first in meshrouter - it does not work. Then I tried it in meshcmd - it also does not work. Despite the fact that if you use a regular rdp client, then everything works.
Sorry for the extra crap. Just Microsoft Remote Desktop is very convenient for a large number of RDP.

https://www.microsoft.com/en-us/p/microsoft-remote-desktop/9wzdncrfj3ps?activetab=pivot:overviewtab

Thanks for help

**Comment by amenolo** [comment]
Just to know, RDP via meshrouter/meshcmd still working as usual along with Windows client/agent, here...
MC 0.5.14

**Comment by vyacheslav25** [comment]
I am using 0.5.13. With the standard rdp client, everything is fine.

**Comment by krayon007** [comment]
So are you saying it only doesn't work with that particular rdp client you linked above, but it works with the standard client?

From what I can tell based in the system requirements of that app, it looks like a windows universal app. From what I remember about windows universal app/API, it does not allow connections to localhost or loopback, which would explain why it doesn't work with meshcmd or meshrouter.

**Comment by amenolo** [comment]
> With the standard rdp client, everything is fine.

Now I got it...standard vs. universal app...didn't really gotcha before...my bad :flushed:

> From what I remember about windows universal app/API, it does not allow connections to localhost or loopback

Good to know.

**Comment by vyacheslav25** [comment]
Yes. Exactly.
It just works fine with meshcmd for mac os.
In my experience, it works better than the standard rdp app.
thanks for the answer
