### ISSUE TITLE
Wrong port in email verification link when using aliasport

### ISSUE THREAD

**Issue by caviarbag** [Ylianst/MeshCentral#124]
Dockerbased installation with reverse proxy, "MeshCentral v0.3.0-b, WAN mode.".
`{
  "settings": {
    "Cert": "xxxx.xxxx.xxxx",
    "WANOnly": true,
    "Minify": 1,
    "Port": 4443,
    "RedirPort": 800,
    "AliasPort": 443",
    "TlsOffload": true,
    "MplsTlsOffload": true
  }
.....
`
Email verification link points to https://xxxx.xxxx.xxxx:4443.

**Comment by Ylianst** [comment]
Nice catch. Published MeshCentral v0.3.0-c that includes the fix for this.

**Comment by caviarbag** [comment]
Tested OK in v0.3.0-d!
