### ISSUE TITLE
Consent not working on Deepin

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1241]
Desktop (both by default and on demand)/Terminal/Files consent not working, I could provide any useful logs.

![SSl6Vh88BY](https://user-images.githubusercontent.com/29974944/80285575-49823b00-8726-11ea-9ea0-58ee07b41438.gif)

Tested on Deepin 15.11/20 with MC 0.5.14

BTW I know it's a sort of niche distro (despite being debian-derivative and having a long history of service so far) but maybe could worth spending a little time over this issue, just as a case study...low priority of course.

**Comment by Ylianst** [comment]
With MeshCentral hitting record download rates, we are swimming in GitHub requests, so may need some time. I never used Deepin, first time I hear about it.

**Comment by amenolo** [comment]
> With MeshCentral hitting record download rates

Well deserved popularity 👍 

> we are swimming in GitHub requests

...on the other hand more work, I can see...

Take your time, I'm at your disposal for any further feedbacks/tests.

> I never used Deepin, first time I hear about it.

I may add it runs on custom Desktop Environment (Deepin Desktop Environment...) which uses Qt/C++ and Golang.

Thanks!

**Comment by krayon007** [comment]
@amenolo do you happen to have a link to where Incan download an iso for that? It'll be much easier to diagnose if I can make a VM for that distro.

**Comment by krayon007** [comment]
By the way, what window manager does that use? On Linux, i use kdialog for kde and xfce, and zenity for others, if I can't find kdialog.

I'm guessing neither are present on what you are using.

**Comment by petervanv** [comment]
https://www.deepin.org/en/download/

**Comment by amenolo** [comment]
> I'm guessing neither are present on what you are using.

Bingo.
As far as I can tell Deepin used KWin till v.15.11 and switched on Mutter-based WM in latest v.20.

**Comment by krayon007** [comment]
OK, I just fixed the notifications and user consent for Deepin.  I added support for xmessage, which will be used if zenity and kdialog are not found. It's not pretty looking, but it's the only thing I found that was available by default.... This should be released the next time the linux agents are updated.

**Comment by krayon007** [comment]
Ok, the changes are live in MeshCentral_v0.5.15, give it a whirl, and let me know if it works for you.

**Comment by Ylianst** [comment]
All Bryan's work!

![MC2-Deepin](https://user-images.githubusercontent.com/1319013/80326113-929cc280-87ec-11ea-839e-e0b1bcf3c83a.png)

**Comment by amenolo** [comment]
Fixed for sure!
You guys are unstoppable, thanks 👍
