### ISSUE TITLE
MeshCentral GUI update and nologin user

### ISSUE THREAD

**Issue by unguzov** [Ylianst/MeshCentral#1242]
Hi,

I'm running MeshCentral with nologin user. I have a problem with "Check server version" - it displays "Loading" for a few seconds and then "unknown" on both versions.

Is there a way to use nologin user and GUI update?

EDIT: MeshCentral running on Debian 10.

**Comment by Ylianst** [comment]
What is "nologin" user? Are you using the "nousers" option in config.json? Or are you using "nologin" as using name?

**Comment by dnutan** [comment]
I think it is using a secured install with a restricted user without shell access. As explained in the manual, on that kind of setup MeshCentral has no permission to use npm and the updates have to be done manually.

**Comment by Ylianst** [comment]
This is exactly correct. If the server does not has rights to write it's own files, it can't self-update.
