### ISSUE TITLE
problem showing windows 7 os in details-operative system

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1243]
with the MC version 0.5.14 i see in the events :
![immagine](https://user-images.githubusercontent.com/62424179/80305037-8ef04800-87ba-11ea-9095-d2660fe7f689.png)

and if i look inside a windows 7 machine now it looks like this:
![immagine](https://user-images.githubusercontent.com/62424179/80304967-096c9800-87ba-11ea-9987-cb413e986c9e.png)

instead with windows 10 everythings is ok and looks like this:
![immagine](https://user-images.githubusercontent.com/62424179/80304995-4769bc00-87ba-11ea-8160-ab1bd0733f12.png)

**Comment by krayon007** [comment]
That's because the regsitry value I was obtaining the version and build doesn't exist in windows 7. However, I found a different place to get that information (without the build number) on windows 7.. I'm fixing that now...

**Comment by krayon007** [comment]
Actually, it was the build number that doesn't exist, but that caused it to not populate the other field, on Windows 7.... So the fix is even simpler :)

**Comment by krayon007** [comment]
Ok it's fixed now. I just tested it with the oldest version of Windows we support. (Windows 7 SP1). It'll get picked up in the next agent update

**Comment by krayon007** [comment]
Changes are live in MeshCentral_v0.5.15

**Comment by tradexsrl** [comment]
yes it works now
