### ISSUE TITLE
Invite Codes Not Unique Per Server

### ISSUE THREAD

**Issue by jfp2** [Ylianst/MeshCentral#1244]
It appears invite codes have a global scope on the server. If I try to add the same invite code in another tenant it won't allow it. Is that by design?

**Comment by Ylianst** [comment]
I need to look into this, domains should be completely separate so this is likely a bug.

**Comment by Ylianst** [comment]
Just check in the fix for this, it will be in v0.5.20.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.20 that should fix this.

**Comment by Ylianst** [comment]
Will close since it should be fixed, please open again if needed.

**Comment by jfp2** [comment]
Thank you
