### ISSUE TITLE
New checkbox "Online" in My Devices?

### ISSUE THREAD

**Issue by unguzov** [Ylianst/MeshCentral#1248]
I'm using many groups and list sort by groups doing a good job. If there is a checkbox "Online" to filter only online devices (while still showing devices by groups) it will be perfect.

**Comment by Ylianst** [comment]
Ok, new "Online" checkbox will remove all devices with unknown state. This will be in MeshCentral v0.5.27 when it's next published.

![image](https://user-images.githubusercontent.com/1319013/81362014-c1405600-9094-11ea-88fb-0b1ca56f4b76.png)

**Comment by Ylianst** [comment]
MeshCentral v0.5.27 is now published, let me know if it works.

**Comment by unguzov** [comment]
Thank you @Ylianst ! I will test this in production when 0.5.27 goes to stable version.

**Comment by Ylianst** [comment]
Ok. I will close this and you can re-open if needed.
