### ISSUE TITLE
BUG: AVG removes 32 bit meshagent32.exe on 0.5.11

### ISSUE THREAD

**Issue by unguzov** [Ylianst/MeshCentral#1249]
I have a problem with AVG and meshagent32.exe - it is deleted and marked as "Win32:Malware-gen" by AVG Business. The 64 bits version is fine.

**Comment by petervanv** [comment]
You can submit a request to AVG to investigate this false report, then the exe can be regarded as an order.

**Comment by unguzov** [comment]
Thank you @petervanv - the file is submitted, but now all my 32 bit workstations are down. I hope that the file will be fixed soon.

**Comment by FrankSanabria** [comment]
Add meshagent in exclution files in your AV. Same in Kaspersky, Avast, Nod32, and others.

**Comment by unguzov** [comment]
This is done @FrankSanabria, but developers must be aware of this issue.

**Comment by Ylianst** [comment]
There is little that can be done about this except to file a false positive on this. If you have any ideas as to what should be done, let me know.

**Comment by unguzov** [comment]
AVG are doing only automated tests of false positive reports and do not answer back. I hope that they will fix this @Ylianst . It is curious why only 32 bit version is affected.

**Comment by Ylianst** [comment]
Yes, I hope they fix it too. Please continue reporting it to them.
