### ISSUE TITLE
Anybody working with customersites?

### ISSUE THREAD

**Issue by rightvision** [Ylianst/MeshCentral#125]
Tried to setup domain with customer. 
https://cust1.domain.com/ shows login/signup
but https://cust1.domain.com/createaccount does not work - direct access = "Cannot GET /createaccount"

**Comment by Ylianst** [comment]
This should work, I will check this again this morning. I may have broken something.

**Comment by Ubivis** [comment]
Just adding to this: 
When tracking the registration ajax call with DevTools you can see, that the connection is "stalled" and does not receive any response from the server when using a customersite Domain, the main Domain does work normally

**Comment by rightvision** [comment]
Maybe this helps. Try to register a new account at company1 - timeout. If I hit F5 to reload the page
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at handleRootRequestEx (/data/meshcentral/node_modules/meshcentral/webserver.js:1105:629)
    at handleRootRequest (/data/meshcentral/node_modules/meshcentral/webserver.js:963:13)
    at Layer.handle [as handle_request] (/data/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /data/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/data/meshcentral/node_modules/express/lib/router/index.js:335:12)

**Comment by Ylianst** [comment]
I will take a look at this today. Note that if you create a new domain like Customer1 in the config.json file, the new domain is accessed by https://serve.com/customer1/... unless the domain is configured with the dns name like "customer1.server.com", then the domain is accessed using the dns name.

This said, looks like a bug here.

**Comment by rightvision** [comment]
Mybe this helps:

"settings": {
    "Cert": "meshcentral.xxx.de",
    "MongoDb": "mongodb://127.0.0...",
"domains": {
    "": {
      "Title": "a",
      "Title2": "b",
      "NewAccounts": 0,
   },
    "customer1": {
      "DNS": "customer1.xxx.de",
      "Title": "c",
      "Title2": "d",
      "NewAccounts": 1,

xxx.de uses wildcard certificate, 
meshcentral/customer1 DNS a record same ip

**Comment by Ylianst** [comment]
Fixed this in MeshCentral v0.3.0-j. Let me know if it works for you.

**Comment by rightvision** [comment]
I was able to add one admin, but there's no "new account..." button to create additional users. Maybe I messed it up, as I was using the same user/mail from the toplevel account. Trying to set "NewAccounts": 1, and register another account, but this does not work again...

Also Logout does not work - on customer1, main site is ok.

**Comment by rightvision** [comment]
Tried a complete new database (changed mongo name) and can create a user in toplevel, but not in customer.

**Comment by Ylianst** [comment]
Hi. So, if you have NewAccounts set to 0 for that domain, you will not see the "New Account" button on the login screen. However, I am re-checking everything now. I have not testing multi-domains in a while.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.0-o with a few fixes for multi-domain servers. During my testing I found some event messages where leaking from one domain to another, now fixed. If there still is a problem, please send over the step to re-create it. Thanks.

**Comment by rightvision** [comment]
![Unbenannt](https://user-images.githubusercontent.com/6069253/54516263-ad043b80-495e-11e9-8f74-9d49605a1e0b.PNG)

There's still no chance to create other users - button is missing.

**Comment by Ylianst** [comment]
This picture does not help much. As I asked above, I need full steps to re-create the problem. The create user button will not show if the server is in single user mode (nousers=1) or the server is in domain authentication more (auth=sspi). If this is not correct. Create a new temp folder, install MeshCentral and explain step by step how to make this problem happen. Thanks.

**Comment by rightvision** [comment]
OK, my mistake - disabled sspi and works fine now, as we do not use any ms domain....

**Comment by Ylianst** [comment]
Oh good. Thanks for confirming.
