### ISSUE TITLE
Setting Own Node ID while installing /Running the Mesh Agent

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1250]
I am running the mesh agent by application. To integrate with my application i don't want mesh agent to generate a random Node Id. instead of that i can generate random and unique id. 

How to set the Id for that particular Mesh Agent. Is there any command line option available ?

**Comment by Ylianst** [comment]
The NodeId is not random, it's the hash of the agent certificate and it a provable identifier required for security. So, you can't change the NodeId. There is another option. Create a "meshagent.tag" file in the same folder as the "meshagent.exe" and "meshagent.msh" files. Put a short text identifier in that file and restart the agent.

You will see your string as an "Agent Tab" in the device view. This should allow you to match the MeshCentral NodeId with the identifier of a different application.

Hope that helps,
Ylian
