### ISSUE TITLE
Is there any option to record the Remote control activities from the mesh central server

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1251]
Is there any option to record the Remote control activities from the mesh central server

**Comment by FrankSanabria** [comment]
Add this in your config file (config.json)

"domains": {
        "": {
            "sessionrecording": {
                "filepath": "DEFINE YOUR PATH",
                "index": true,
                "protocols": [ 1, 2, 100, 101 ]
            },
...

**Comment by amenolo** [comment]
FYI original notice here:

https://meshcentral2.blogspot.com/2019/08/meshcentral2-500k-downloads-session.html

**Comment by asasin114** [comment]
Is there a way to limit how much space the recordings are allowed to take up?

**Comment by aimdharma1990** [comment]
> "sessionrecording": {
> "filepath": "DEFINE YOUR PATH",
> "index": true,
> "protocols": [ 1, 2, 100, 101 ]
> },

Thanks. but this will record the session always. But can we keep as on on-demand to run this. When required we can do the recording instead of recording all the time?

**Comment by aimdharma1990** [comment]
> FYI original notice here:
> 
> https://meshcentral2.blogspot.com/2019/08/meshcentral2-500k-downloads-session.html

Thanks. but this will record the session always. But can we keep as on on-demand to run this. When required we can do the recording instead of recording all the time?

**Comment by Ylianst** [comment]
There is no way to record on demand right now. If you setup the server to record, it will record all sessions. I will need to add a on-demand feature.

**Comment by aimdharma1990** [comment]
Thanks Ylianst for your quick response

**Comment by Ylianst** [comment]
FYI. Just published MeshCentral v0.5.21 with local remote desktop recording option. It records to memory and saves when you stop recording. Currently no limit on recording size but I may need to add one. Testing and feedback appreciated.

![MC2-DeskLocalRecord](https://user-images.githubusercontent.com/1319013/80896695-fff59b00-8ca5-11ea-8296-50a16b1e67f6.png)
