### ISSUE TITLE
MeshRouter RDP button disabled when using user groups

### ISSUE THREAD

**Issue by trenton92** [Ylianst/MeshCentral#1253]
Hi.
Users created before the update do not have the opportunity to use meshcentral. But new ones can use.
This is all provided if you add a device to the user, not a group.
Everything works with the group.
MeshCentral 0.5.13
![image](https://user-images.githubusercontent.com/61736438/80380727-a0b01900-88a8-11ea-813c-af444a905547.png)

**Comment by Ylianst** [comment]
I will take a look when I get a chance.

**Comment by Ylianst** [comment]
Ok, updated MeshCentral Router to handle user group permissions. You can get the [new version here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Or it will be in MeshCentral v0.5.18 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.5.18 is published and should fix this. Let me know if it works.

**Comment by Ylianst** [comment]
Closing as this should be fixed. Please open again if needed.
