### ISSUE TITLE
Feature Request: Quota for Recordings

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1254]
Could we have a way to set a quota for the amount of recording data that can be stored with the ability to have Mesh Central automatically delete the oldest recordings as the quota fills up?

**Comment by Ylianst** [comment]
Ok, should not be too difficult. However, I got a lot to catch up on.

**Comment by asasin114** [comment]
@Ylianst, for sure! Again, really appreciate everything you're doing with this project! The updates are fast, the features are great and you are super involved and listening to the community. Really can't ask for anything more than that!

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v0.5.19 when next published. You can specify the number and max size of recordings like this:

```
      "SessionRecording": {
        "filepath": "C:\\temp",
        "index": true,
        "maxRecordings": 10000,
        "maxRecordingSizeMegabytes": 300,
        "protocols": [ 2 ],
      }
```

You don't have to specify both, just size if you like. The "sweep" will occur each time a recording ends, any old files over the count or size limit will be removed. Only .mcrec files in the folder count against this quota.

Once you give it a try, let me know if it works.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.19 with support for this. Let me know if it works.

**Comment by asasin114** [comment]
For whatever reason, I can't get a session to record at all. This is what I have for my session recording section:
	    "sessionrecordings": {
		    "filepath": "path to foler",
			"index": true,
			"maxrecordings": 256,
			"maxRecordingSizeMegabytes": 300,
			"protocols": [ 1, 2 ]
		}

**Comment by Ylianst** [comment]
@asasin114 Check that "sessionrecordings" section is in the "domain" section of the config.json. Also, start by removing the "filepath", by default it should record into the "meshcentral-recordings" folder that will be created next to the "meshcentral-data" folder. Let me know if that helps.

**Comment by Ylianst** [comment]
FYI. In upcoming MeshCentral v0.5.21, if you do tracing on web socket relay, you will now see if it started recording or failed.

![x](https://user-images.githubusercontent.com/1319013/80857980-231f3c80-8c0b-11ea-9771-087baccf027b.png)

**Comment by Ylianst** [comment]
Ok, closing this one since the new quota system was added and seems to work for me. Please open a new bug if it does not work with details. Thanks.
