### ISSUE TITLE
Feature request: group action for users to add to existing or new group

### ISSUE THREAD

**Issue by Zveroloff** [Ylianst/MeshCentral#1255]
On users list page, a button for group action is available. There are only three actions: Block account, Unlock account, Delete account. Please, add options to **add selected users to existing user group** and **add selected users to a new user group**. Thank you!

**Comment by dinger1986** [comment]
@si458 maybe simple enough to add? bulk actions really group actions is slightly confusing

**Comment by si458** [comment]
this is already possible just a different way around

you go into the user groups, select a user group, then click add users,
you can then start typing the users and it will list them for you to click,
you add multiple users by seperating them with `,`
