### ISSUE TITLE
Trying to install commercial webserver cert

### ISSUE THREAD

**Issue by rogalskij13** [Ylianst/MeshCentral#1256]
I am attempting to install a commercial certificate we pay for on meshcentral.  The documentation is sparse on how to do this.  I am not even sure what webserver this runs on.  Any chance someone could walk me through this?  The product works amazing but my supervisor won't allow this in production until I get our commercial certificate on it.

**Comment by Ylianst** [comment]
MeshCentral run ExpressJS, but take a look at the two following files in "meshcentral-data"

```
webserver-cert-public.crt
webserver-cert-private.key
```

They are text files you can edit. You can replace them with your own certificate and restart the server. Use a text editor to look at the format and cut & paste your own certificate in these files.

Hope that helps,
Ylian

**Comment by rogalskij13** [comment]
Thank you.  I found that I had to edit the config.json file and add my fqdn entry to "Cert" at the top.  Once I did that it worked perfectly.  

For anyone else trying to add their own commercial SSL cert I used openssl to generate the CSR + private key (had to make it a 3072 bit cert. I then submitted the CSR to my certificate authority as a "tomcat" certificate as I didn't know what type of webserver Mesh runs on. Downloaded the .crt cert from the authority, renamed them to the "webserver-cert-public.crt" and "webserver-cert-private.key" names and overwrote the files in "/meshcentral-data" directory.  I stopped the services and started them again, checked the /meshcentral-data/serverstate.txt file and saw it was running.  Checked the URL for mesh and it was working with the new cert.

**Comment by Ylianst** [comment]
Right, even if you are using a commercial certificate, you still need to put the "cert" value in the config.json to indicate that DNS name you want the server to use. Sometimes certificates are wildcard of have many names and so, using cert is needed.

Also, thank you for mailing back your results!
