### ISSUE TITLE
Default Config File

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1264]
With updates happening rapidly (which is awesome to see!) and new config options being added in many of them, I'd like to suggest creating (and overwriting with each update) a default config file - something along the lines of config.default.json - that would list out all possible configuration options and display their default values. Obviously, overwriting a config file that's in use would be bad but having a reference for all options and what their defaults are alongside the active config file would be very helpful for keeping up with new features. Thanks!

**Comment by Ylianst** [comment]
There is a sample configuration file at "node_modules/meshcentral/sample-config.json" you can always look at and it's updated when you update the server. However, if you looking for more, let me know.

**Comment by PetieM** [comment]
I missed that entirely, thanks! That's exactly what I was looking for. It seems to be missing the newest config option (desktopmultiplexor) though - is that all that's missing from it at the moment? Also, just as a point of clarification, are the values there showing what they default to (e.g. if you leave an option commented out, the value shown in the sample file is used)?

**Comment by Ylianst** [comment]
I just published MeshCentral v0.5.19 and added the "desktopmultiplexor" and new "domaindefaults" to the sample config.json file. At some point it would be nice to have a config.json editor, but plenty to do already.

**Comment by PetieM** [comment]
Awesome, thanks for the quick fix! Agreed that a browser-based config editor would be awesome but that there are definitely higher-priority things to tackle first.
