### ISSUE TITLE
Remote connexion info

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#1267]
would it be possible to have an option which signals if a remote connection is already active ?

**Comment by krayon007** [comment]
Are you talking about the server/browser side, or the agent side?

**Comment by Ylianst** [comment]
So, I am going to close this issue as it's too low quality. Please open a new issue and provide much more details as to what is desired and why it would be useful. Thanks.

**Comment by Fredoberti11** [comment]
I am talking about server side
