### ISSUE TITLE
[Question] Desktop Multiplexor

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1272]
From the description of the new desktopmultiplexor, the slowest client will get the tiles to "replay" what has happened. If one user is on a much slower connection than another user, wouldn't they just be "watching" the session? I would think that older tiles should be discarded so that the slowest user can see the screen as close to real-time as possible, even if it's a choppy experience, I would think the most up-to-date desktop image would be more useful than everything that has happened since.

Thank you.

**Comment by Ylianst** [comment]
I may not have described it correctly. The Desktop Multiplexor works as your would expect to split the remote desktop stream to many browser so each can watch the screen in as near real-time as possible. While fast browsers will see all of the intermediate images, slower browsers will skip some images to keep up. The latency should be as small as possible for each viewer regardless of the connection speed.

About the "replay", when a new viewer joins an existing session, the server will get the new viewer caught up without the need for the existing viewers to see any change in traffic.

I do have a hidden trick if you want to test all this. There is a new URL argument "&slowrelay=40" that will add 40 milliseconds pause before sending each image to the browser with this option. This allows you to open FireFox and Chrome for example, connect to the same remote desktop and have one of the browsers be artificially much slower than the other. I have used this for my own testing to make sure flow control was correct.

Hope that helps,
Ylian

**Comment by ryanblenis** [comment]
Awesome. Thank you for the explanation!
