### ISSUE TITLE
Remote connexion information

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#1273]
We are several people likely to work on PCs with a remote connection. It would be interesting to know if one of our employees is already connected to a remote computer. This information could appear on the PC icon, in the web server interface. (Sorry about my english, I am french)

**Comment by PathfinderNetworks** [comment]
I agree, this would be a useful feature to know if another MeshCentral user has an active session open with a device.

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.5.25, you can now see who else is watching a remote desktop when you connect. Let me know if this works.

![MC2-MultiViewerIndication](https://user-images.githubusercontent.com/1319013/81359697-ba164980-908e-11ea-944a-a7f1d97a59ea.png)

**Comment by Fredoberti11** [comment]
It works, but would it be possible to display this information on the main screen, without having to connect to the remote machine (under the name of the PC for example) ?

![Capture](https://user-images.githubusercontent.com/40867059/81396164-2fccf480-9125-11ea-9f66-b5b99507e64a.JPG)
?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.30 with new device session indicators. Let me know if it works.

![MC2-DeviceSessionIndicator](https://user-images.githubusercontent.com/1319013/81631961-f19e3200-93bd-11ea-8ecf-26f1d291d8fa.png)

**Comment by Fredoberti11** [comment]
It's OK. It works. It's a very good information for ma, thank you.
