### ISSUE TITLE
active filter in 'Desktops' view of 'My Devices'

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#1275]
On the 'My Devices' Tab, the filter field is only visible if the view is either 'Columns' or 'List' but not if the view is 'Desktops'.
This can be confusing, if there is a filter active - also in 'Desktops' view, that is very useful.
But one can not remove it. Other than switching to 'Columns' and back - once one figured that out.

**Comment by Ylianst** [comment]
Thanks for the report. I checked in the fix in GitHub and will be in v0.5.20 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.5.20 is published and should fix this.

**Comment by baikal** [comment]
Thanks for the fix. Confirm that it is fix in 0.5.20.
