### ISSUE TITLE
Losing agent connection through VPN

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#1276]
Hi everybody,
I'm playing with my RPI 4 and meshcentral, Ylian was right, seems to work very good

I am up and running with MC, added a couple of pc in my lan, perfect
changed main port on 30xxx to avoid conflict with other software (see below) 
I installed a VPN Server (softether) on rpi, to get rpi reachable from outside and, after some tweaking, i get to achieve this.

Now, the strange thing:
when a pc with agent is in LAN, everything is ok, I reaching MC portal on specified port and agent is marked online, but when I go out of home and I establish a vpn connection, everything seems to work, open MC portal on rpi with chrome, I reach my NAS, My router web management is reachable....
BUT
Meshcentral agent is disconnected....greyed out (another fact is agents always display ipv6 address, don't know it can help)
I don't understand why, as far as i know, it use the same port of website (changed on 30xxx)

can you help me to identify if my search have to go to MC or VPN to solve this ?

I know is a not common configuration, thanks for any consideration

Cheers

Merlinweb

**Comment by krayon007** [comment]
What mode is your MC server configured to run, LAN, WAN, or Hybrid?
If you look at the contents of the MSH file on your agent, what URL does it show for MeshServer=
Does it show an IP address, as hostname, or does it say local?

**Comment by merlinweb** [comment]
ACH !!!
It's in default mode, wanonly and lanonly commented
In msh file there is local (!!!!)

MeshName=MainGroup
MeshType=2
MeshID=
ServerID=
MeshServer=local
ignoreProxyFile=1

It's up from a couple of days, my windows production installation is with host and let's encrypt
Which setup is best ? I think IP address solve the problem

Thanks a lot

Merlinweb

**Comment by merlinweb** [comment]
I can't find a way to push ip address in msh file. guessing it's only way to reach server from LAN and VPN when outside LAB network...
Try several configuration but with no luck

Cheers

Merlinweb

**Comment by krayon007** [comment]
@Ylianst can chime in...
But I remember when I ran a test server on the local lan, (assuming you are just using a self signed cert) I had to add the following command line switch when starting the server:
--cert XXXX
where xxx was the hostname of the server. (I don't know where this setting is in the config)
If I started the server with this option, when I added an agent on the local network, it would use the hostname instead of "local".
It was a really long time ago that I changed the settings on my server, so @Ylianst can chime in...

**Comment by Ylianst** [comment]
Just put your server's IP address in the config.json like this:

```
{
  "settings": {
    "Cert": "192.168.1.100"
  }
}
```

Restart your server and re-install the agent, it will have a .msh file with the IP address in the URL.

**Comment by merlinweb** [comment]
That's right...
now in msh I have MeshServer=wss://192.168.0.2:30443/agent.ashx
If I go outside my lan with a computer and enable VPN client, I see agent up and running in MC portal
It's perfect
wan_only e lan_only remain commented. 

Thanks for help

Merlinweb
