### ISSUE TITLE
Support VNC clients

### ISSUE THREAD

**Issue by luckydonald** [Ylianst/MeshCentral#128]
Hey, I'd like to replace teamviewer, but a big stopper is the lack of iOS app,
and the web browser is just too limited to do anything, really.

I recently got thinking, if mesh central would support translating a vnc connection to one of the connected computer, we could use any vnc client to get the best out of the device at hand.

Otherwise If I miss something, or there is an app, please advise me :D

**Comment by jsastriawan** [comment]
Do you want to tunnel VNC traffic within MeshAgent connection?

Yes, that's possible.

I wrote a small node webkit application to tunnel RDP, SSH and SFTP to MeshCentral-connected device.

See https://github.com/jsastriawan/mc2router

Feel free to modify to your liking. 

Regards,


Joko

**Comment by luckydonald** [comment]
@jsastriawan so I launch mesh central 2 on a server, 
Download your tool and let it run on the same server (or a different server, but not locally)?

To clarify, I don't need to run an vnc server on the machines, just the regular mash central client?

**Comment by jsastriawan** [comment]
You run mc2router on your own PC to launch SSH, RDP utilities. This is basically generic TCP tunnel tool.

MC2 desktop (agent) is based on JPEG tiles, the hw desktop is based on VNC. So MeshAgent desktop will not work with VNC client but HW/AMT desktop could work. Some work will be required to tunnel that.

Regards,


Joko

**Comment by luckydonald** [comment]
Yeah, I'd be looking for that VNC -> JPEG connector.
Wouldn't need to be VNC but could be or any other protocol which has a similar wealth of native clients to choose from.

Again, I think it would be easier to build and later maintain to have mash central offer VNC and let users connect via existing 3rd party VNC clients, then to create native mobile clients for mesh central.

That way those clients could provide  the best functionality across all those different platforms and handle stuff which is difficult for the webapp (e.g. input via touchscreens) in the best possible way which only a native app can achieve.

**Comment by Ylianst** [comment]
Curious... what is your favorite VNC viewer app for IOS? For Android (if any)? MeshCentral uses JPEG for image encoding. If a VNC viewer where to accept JPEG an an encoding format, the translation would not be super difficult. The protocol would still need to be adapted.

**Comment by luckydonald** [comment]
I actually haven't looked into it, I still use TeamViewer as it allows connections without known ip addresses and punches though all firewalls.
On my mac I kept it simple by either using the build in VNC viewer `/System/Library/CoreServices/Screen Sharing.app` (or: Finder > Connect to server > `vnc://...`), 
or the simple but good _Chicken of the VNC_.
<table><tr><td>

[![Chicken of the VNC](https://upload.wikimedia.org/wikipedia/commons/9/99/Chicken_of_the_VNC.png)<br>Chicken of the VNC](https://sourceforge.net/projects/chicken/)

</td></tr></table>

I just tried the free VNC viewer from RealVNC, and am pretty happy with it it, as the mouse and scrolling etc works reallz good. Onlz problem seems to be a mix of qwertz vs qwerty kezboard.

**Comment by luckydonald** [comment]
Apparently vnc uses jpeg squares, too. 
https://www.hep.phy.cam.ac.uk/vnc_docs/howitworks.html

Quick google brought up a node js vnc server, maybe that can be of use , directly or as implementation reference.
https://github.com/megamsys/vnc_server

**Comment by Ylianst** [comment]
The original [RFC6143](https://tools.ietf.org/html/rfc6143) does not have JPEG support, however some viewers have added JPEG support. I wrote the RFC6143 viewer for Intel AMT that is part of the [MeshCommander](https://www.meshcommander.com/meshcommander) and [MeshCentral](https://www.meshcommander.com/meshcentral2), so it's possible that such a feature be added in the future. However, there is quite a big todo list right now, so don't expect to jump on this anytime soon.

It would be nice to login to MeshCentral using a client app, select a device on screen and see it in the app.

**Comment by luckydonald** [comment]
So you would have it display a menu screen first, and you can next select a client?
I saw that chicken has a port/screen selector, and assumes display 0 to be at port 5900, up to screen 49 to be at 5949. That could also be a approach, and also allow for connecting with one less click.

I think for the first version it wouldn't hurt to have to log in in the web interface and select the "active" connection to use. That menu would be a nice stage 2 though.

**Comment by Ylianst** [comment]
MeshCentral can't be listening to 1000's of ports, one for each connected device. On some server's that would just run out of ports. Instead, probably to connect to one port with your account username/password and select a target computer to view. It would also require TLS connect, etc. Not sure if just any client could do this. Would be nice to join up with a different open source client project.

**Comment by luckydonald** [comment]
Thinking about it, maybe having a username like `<user>:<client-id>`, e.g. `luckydonald:12` could be used to indicate the client to connect so we can skip menu implementation for now, and have our favorite computer in the bookmarks of the ssh client.

**Comment by Ylianst** [comment]
As far as VNC viewer support is concerned, MeshCentral now has a really nice [MeshCentral Router tool for Windows](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) along with "MeshCmd route" that allows VNC clients to tunnel thru the server. So, I think I am going to close this one.

I don't expect VNC connections to the server to happen because: It would break MeshCentral reverse-proxy support, would expose more external ports, would be difficult to encrypt & secure correctly and difficult to get working behind corporate firewalls. MeshCentral Router is a much better solution because it solves all these problems and does so with 2-factor auth support.

Certainly willing to hear out other views on this, but I think any VNC solution will be supported by some local "Mesh Routing" tool that does proper security and network traversal.

**Comment by luckydonald** [comment]
Could you outline how I would use that with a) a connected mac machine and b) a windows machine?
My goal is to replace Teamviewer which has an iPhone app.
