### ISSUE TITLE
agent and router download links seems broken in chrome

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#1281]
Hi,
I'm facing something similar to issue #1036 
Everything is ok with FIREFOX, but with Chrome, clicking on a link result in a "meshagents" download, same for all links

hope this helps

Cheers

Merlinweb

**Comment by Ylianst** [comment]
I just tested a bunch of download links with Chrome and it works for me. When you say this:

> clicking on a link result in a "meshagents" download, same for all links

I have no idea what this is and what to test. I will close this bug. Please open a new issue and provide much more information. Where exactly to click, server version and OS, are you using plug-ins? Are you using a reverse proxy. Thanks.
