### ISSUE TITLE
Disable input on password fields when randomize password is used

### ISSUE THREAD

**Issue by dnutan** [Ylianst/MeshCentral#1288]
Hi, just a small visual tweak with low priority. Tested on MeshCentral v0.5.21.

When SMTP section on config.json is enabled, password fields in the create account dialog form are not disabled when the "Randomize the password" checkbox is selected.
![meshcentral - create account - password fields not disabled when randomized](https://user-images.githubusercontent.com/15559754/80921492-00aa3200-8d77-11ea-8e05-6d4e12fd35f9.png)

To keep consistency, it would make sense to make it behave as with the default settings:
![password fields disabled when randomized](https://user-images.githubusercontent.com/15559754/80921494-0142c880-8d77-11ea-8b17-f33b93de7ebb.png)

Kind regards.

_PS: was about to ask what happens when same email address is registered to many users but tested it and works as expected (account reset mail sent as many times as users having the same email address, but user can ignore undesired email requests, guess some corporate environments could use a catch-all mail with filters or something similar)._
Ah! Now I see `UserNameIsEmail` option.

**Comment by Ylianst** [comment]
Your right. Looking at the browser console you can see the code is throwing an error and stops before it can gray out the passwords. Working on it.

![image](https://user-images.githubusercontent.com/1319013/80925916-8367c880-8d48-11ea-95ed-52d1e11f63a3.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.22 with a fix for this.

**Comment by dnutan** [comment]
That was so quick, even more on a Sunday.
Sorry I didn't though to look at the browser console.
With the new version it is working but the "Send invitation email" checkbox is disabled (even with a filled email field).

**Comment by Ylianst** [comment]
To enable "Send invitation email", you need to have "Email is verified" and "Force password reset on next login" checked. I just changed the order of the checkboxes in the latest version.

![image](https://user-images.githubusercontent.com/1319013/81362540-f4371980-9095-11ea-936b-f6e3f8d8a6a3.png)

**Comment by Ylianst** [comment]
I will close this one, but please open a new issue for any suggestions.
