### ISSUE TITLE
AESGCM Cookie Auth Potential Issue

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1289]
Prefacing Disclaimer: I've been staring at this code so long it's starting to make me question my sanity.

I was looking into [this issue](https://github.com/Ylianst/MeshCentral/issues/1257) and decided to play around with PHP to see if I could make the cookie generation work, where I spotted [this](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral.js#L2239) line indicating it is decrypting using a 4 bit authentication tag whereas the encode function [returns and uses a 16 bit tag ](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral.js#L2193). 

I'm not sure if there was a purpose for this or in error, but if I change the decode function from:
`decipher.setAuthTag(cookie.slice(12, 16));`
to
`decipher.setAuthTag(cookie.slice(12, 28));`

to use the full auth tag data it still works as expected, but it is currently using a smaller chunk of the authentication tag. Not sure if that is really a security concern, but threw me for a loop when trying to replicate the functionality, as I assumed they would need to be identical... but admittedly I am not extremely well versed in AESGCM methodologies, so perhaps this is some sort of backward compatibility to use a smaller subset of the tag?

**Comment by Ylianst** [comment]
Nice catch! The same problem is also in db.js. Playing around with it, it seems it's acceptable to truncate the tag, but any invalid tags will fail. I just published MeshCentral v0.5.22 with a fix for this.
