### ISSUE TITLE
Consent dialog box in background

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1293]
![8xGWbPMAqV](https://user-images.githubusercontent.com/29974944/80927636-5a265700-8d9f-11ea-9378-48721b743dea.gif)

MC v0.5.22
Noticed on Windows 10 so far, on Linux seems fine.

Thanks

**Comment by krayon007** [comment]
I'm rewriting how dispatching works for user-consent on windows. (Part of my fixes other fixes related to a bug where the agent will not start if it resides in a path that contains non-english characters).

Anyways, while doing this, I think I root caused why the dialog box was sometimes in the background when it was painted, despite setting the ALWAYS_ON_TOP and TOP_MOST flags. I need to also set the flag indicating that it is SYSTEM_MODAL dialog, which the documentation says should be set, if it is imperative to grab the users attention to respond.. When I set this flag, the dialog seems to always pop front and center... It'll be included when I release the rest of the fixes for the agent I'm working on.

**Comment by Ylianst** [comment]
This has been a long standing issue, I am glad Bryan found a fix for it!

**Comment by si458** [comment]
this should now be fixed, please use the latest version 1.1.24
