### ISSUE TITLE
DOCS as ODT instead of DOCX

### ISSUE THREAD

**Issue by Hemmingen** [Ylianst/MeshCentral#1294]
Please use the Open Document Format (ISO/IEC 26300) instead of Microsoft's OOXML for the manuals and other documents.

**Comment by Ylianst** [comment]
Good idea, just checked into GitHub all documents in [open document format](https://github.com/Ylianst/MeshCentral/tree/master/docs). Let me know if this works.

**Comment by Hemmingen** [comment]
Wow, that was quick. Works like a charm. Thank you 👍 :)
