### ISSUE TITLE
Agent invite link broken when using non-standard port

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1296]
I'm using my MC on non-standard port(1234 for example), and it seems Agent Invite link is generated without this port:
![image](https://user-images.githubusercontent.com/60253253/80962299-7bc22580-8e15-11ea-9013-8ef9de542001.png)

Add Agent window looks correctly to me:
![image](https://user-images.githubusercontent.com/60253253/80961896-95af3880-8e14-11ea-889e-8347d46a168a.png)

**Comment by Ylianst** [comment]
Can you share what your config.json looks like? Please blank out any private information. Thanks.

**Comment by uldiseihenbergs** [comment]
See below, i tried to filter out only defined items. note, that this MC is also behind Apache reverse proxy - reversed port 448. 

{
  "settings": {
    "Cert": "mesh.mysite.com",
    "WANonly": true,
    "Minify": 1,
    "CookieEncoding": "hex",
    "Port": 448,
    "AliasPort": 443,
    "RedirPort": 80,
    "WebRTC": false,
    "ClickOnce": true,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "TrustedProxy": "192.168.50.248",
    "MpsPort": 0,
    "Plugins": {
        "enabled": true
    }
  },
  "domains": {
    "": {
      "Title": "mesh title",
      "Title2": "",
      "NewAccounts": false,
      "CertUrl": "https://192.168.50.248:443/",
    }
  }
}

**Comment by Ylianst** [comment]
Ok, I will check on this. Just a side note that I will be posting on Twitter later today, as of MeshCentral v0.5.22, the "minify" setting is moved to the domain section, put `"minify":true`. You can also override this setting with &minify=1 or &minify=0 in the URL and minification is much more effective now, saving over 1 megabyte of downloads on the main web app.

**Comment by Ylianst** [comment]
Your right, I see the same problem. Working on it.

**Comment by Ylianst** [comment]
After a bit of testing, i don't see the problem. The invitation link should be using the `aliasport`, in your case it's 443 which is the default for HTTPS and so, the link will not show any port and should work.

Without the `AliasPort`, the link will be built with port 448 used in the link. Also, if the `AliasPort` is not 443, the non-default port will be added to the link.

So, I am not seeing a problem. Let me know what I am missing. Thanks.

**Comment by Ylianst** [comment]
Ok, I see that the agent link uses the current browser URL since it's intended to give you a link you can download right now. The invitation link is built so you can share the link and so, it uses the full URL construction of your server name, port, etc.

I could make the invitation link construction the same as the agent, but if your browse using `https://127.0.0.1:448`, the invitation link will not be valid for anyone else. The full URL construction is used for the agent Linux install scripts for example since you expect these scripts to be run on other machines.

Let me know if that makes sense.

**Comment by uldiseihenbergs** [comment]
huh, thanks for clarification. i'm just trying to add more security to my MC server. i want may agents  connect to port 443(i limit this connection to wss only in Apache reverse proxy), but MC should work on port 448. what port settings can you suggest? AgentPort 443 and Port 448, without AliasPort?

**Comment by amenolo** [comment]
@uldiseihenbergs sorry for my OT: could you please provide me with your running Apache reverse proxy config (maybe via pastebin link)? Just for the sake of comparison with mine, thanks

**Comment by uldiseihenbergs** [comment]
@amenolo there is nothing to do with reverse proxy, i tried with my LAN side address, and same problem. but sure, i can share my Apache config

```
<VirtualHost *:80>
    ServerName mesh.example.com
    ServerAlias mesh.example.com
    DocumentRoot /var/www/mesh

    Redirect permanent / https://mesh.example.com/
</VirtualHost>
    
<VirtualHost *:443>
    ServerName mesh.example.com
    ServerAdmin uldis@example.com
    DocumentRoot /var/www/mesh

    SSLCertificateFile    /etc/letsencrypt/live/example.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem

    SSLEngine on
    SSLProxyEngine On
   
    SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    SSLHonorCipherOrder on
        
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule . "wss://192.168.85.202:448%{REQUEST_URI}" [P]

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<VirtualHost *:448>
    ServerName mesh.example.com
    ServerAdmin uldis@example.com
    DocumentRoot /var/www/mesh

    SSLCertificateFile    /etc/letsencrypt/live/example.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem

    SSLEngine on
    SSLProxyEngine On

    SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    SSLHonorCipherOrder on

    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule . "wss://192.168.85.202:448%{REQUEST_URI}" [P]

    ProxyPass / https://192.168.85.202:448/ connectiontimeout=86400 timeout=30
    ProxyPassReverse / https://192.168.85.202:448/
    ProxyPreserveHost On
    ProxyPassReverseCookiePath / https://192.168.85.202:448/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
 ```

**Comment by uldiseihenbergs** [comment]
i finally got it working with my suggested config above: AgentPort 443 and Port 448, without AliasPort
but according to `"minify":true` - when i add them to domains section, i get blank page after login window.

**Comment by Ylianst** [comment]
Ok, I will check minify again.

**Comment by Ylianst** [comment]
I can't find any problem with "minifiy":true. I am going to close this issue, if you can open a new issue and give details for the minify problem, that would be great. If there is any errors in the browser console, that would also be excellent. Thanks.
