### ISSUE TITLE
Workstation Bandwidth Monitoring

### ISSUE THREAD

**Issue by itpilot** [Ylianst/MeshCentral#1298]
firstly let me say thank you for an excellent, excellent application.

there is monitoring of 7 day power usage 

i am trying to monitor Bandwidth Usage of all my Remote Workstations and Laptops.

i need to have a daily, weekly and monthly usage report emailed if at all possible

any ideas how i can do this with MeshCentral?

any help greatly appreciated

**Comment by Ylianst** [comment]
This is not currently available on MeshCentral. Bryan would have to figure out a way for the agent to fetch this information on the agent.

**Comment by si458** [comment]
this is more of a rmm feature than a remote support feature
please look at https://github.com/amidaware/tacticalrmm
closing as not planned
