### ISSUE TITLE
Hide

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#1299]
When Hide = 13
Display is as expected, except for a couple of small issue

When I right click and select 'multiple desktops' this works as expected, but there is no way back to columns

Also with hide = 13, I can't edit the machine name

Changing back to hide = 5 fixes these issues, so having hide = 8

**Comment by OutbackMatt** [comment]
Thinking about the missing 'columns|list|desktop' icons when hide = 8 is selected, perhaps they could be added under left 'tabs' if that panel is NOT hidden

**Comment by Ylianst** [comment]
just checked in a bunch of fixes for "hide=8". Added names in the attribute list for Device, Device Group, Users and User Groups. Also fixed some panels where the title bar was not removed. Not sure what to do with the multi-desktop thing yet.

**Comment by Ylianst** [comment]
MeshCentral v0.5.25 is published. Let me know if it improves things.
