### ISSUE TITLE
Right Click options from 'colums view'

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#1300]
When I right click on an active agent, I can select 'Information, desktop, terminal, files, console'

Can we also get 'Events, Details, plugins' like we can get from the device

**Comment by OutbackMatt** [comment]
It'd would also be useful to have a right click 'Open desktop in new tab'

**Comment by Ylianst** [comment]
Events was already present, just published MeshCentral v0.5.24 wtih new "Details" and for "Plugins" I added the option in the menu, but since I don't test plugin's @ryanblenis will have to look into it.

**Comment by OutbackMatt** [comment]
Thanks Ylianst
Love your work
