### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#1301]
It would be good to able to start a CHAT session without a desktop having started
a new browser window, at a set size would also be useful

**Comment by cgb** [comment]
Another thing to compliement any chat changes would be if the user could somehow initiate a chat / send a message to the admin console / request remote support, via a taskbar icon? Yilan: have you ever considred that or hard requests for it?

**Comment by Ylianst** [comment]
Just so I understand the original request, your looking for a chat window that is not in a browser? If you have an example screenshot, can you sent it? I just hate to spend many days on a new feature based on a single sentence.

As for having the user initiate a notification and/or chat to MeshCentral, certainly a possibility. However, that seems like a bad idea given that you have no idea if someone is logged in to MeshCentral at the time. Maybe a better alternative would to be have the user be able to file a ticket and have the chat open as a result of this. In any case, this would have to be a separate issue and have may more details.

**Comment by OutbackMatt** [comment]
Fair enough
I'll try and be more specific in the future

Thinking a bit more about this, and what I want to achieve, I think I'll run up a XMMP (Jabber) server instead, so I'll close this thread
