### ISSUE TITLE
What will be minimum configuration to support 5k agents to support Remote Control

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1302]
What will be minimum configuration to support 5k agents to support Remote Control with Mango DB

**Comment by Ylianst** [comment]
For reference, [MeshCentral.com](https://www.meshcentral.com) run on a [AWS t3.medium](https://aws.amazon.com/ec2/pricing/on-demand/) running AWS Linux2 EC2 instance and can support 14k devices for about 30$/month. The is 2 CPU cores with 4 Gigs of RAM. So, I expect any small servers with MongoDB will support that and much more.

Hope that helps,
Ylian
