### ISSUE TITLE
MAC not allowing run directly as its showing popup as unknown developer ?

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1303]
MAC not allowing run directly as its showing popup as unknown developer ?

**Comment by Ylianst** [comment]
The macOS installer is not signed and not going to be signed by us, but you are free to sign it yourself. Without signature, you can install it by right clicking or hold "control" and click on the file and select "Open". Hope that helps.

![image](https://user-images.githubusercontent.com/1319013/81093724-571e8a00-8eb7-11ea-8f10-565a0c40ce47.png)

**Comment by aimdharma1990** [comment]
> e that helps.

I am getting below during installation. Can you please help on this. 

![image](https://user-images.githubusercontent.com/9078295/85923419-78449b00-b8a8-11ea-8d79-df6d406658ec.png)
