### ISSUE TITLE
Move MC to new server

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1305]
This is a followed question on #1221 about, what should i keep (and backup), if i choose to move MC to new server. main goal is not to loose any agents as it was in #1221 when ServerID changed after a MC reinstall.  

_Originally posted by @uldiseihenbergs in https://github.com/Ylianst/MeshCentral/issues/1221#issuecomment-623957530_

**Comment by Ylianst** [comment]
I have moved servers many times and it's not a problem. Just setup the new server and copy the "meshcentral-data" folder from the old server to the new one. If you are using MongoDB, you need to make sure you copy or give the new server access to the same MongoDB as the old one.

Optionally, you can copy "meshcentral-files", "meshcentral-recordings" and "meshcentral-web" into the new server if you use any of these folders.

Personally, I get the new server setup correctly, make sure I can login and everything looks good. I then switch the DNS name to the new server's IP address and depending on your DNS TTL, it will take a bit more than an hour for all the agents to reconnect.

You can also do a test by setting up a new server and editing the .msh file of one of the agents to just change the connect URL to the new server's IP address to make sure everything is ok.

In general, it should not be a problem. Hope it helps.

**Comment by uldiseihenbergs** [comment]
ok, thanks for detailed clarifying, as usual :)

**Comment by Ylianst** [comment]
As always, when running a MeshCentral server, please backup your "meshcentral-data" folder and put it in a safe place.
