### ISSUE TITLE
Change Meshagent icon and details

### ISSUE THREAD

**Issue by BlackRouter** [Ylianst/MeshCentral#1308]
hi

i want change MeshAgent icon via resource changer but after change icon MeshAgent automatic update to Previous mode .

how to stop auto update MeshAgent?

**Comment by vitko-bg** [comment]
Why do you use resource changer?!?!
All source is here:
[https://github.com/Ylianst/MeshAgent](url)

**Comment by BlackRouter** [comment]
> Why do you use resource changer?!?!
> All source is here:
> [https://github.com/Ylianst/MeshAgent](url)

i want change icon mesh agent for my customers
after change run Meshagent file , automatic download file with update name and replace it on original file.

**Comment by Ylianst** [comment]
In the settings section of config.json, you can add the following:

```
"noagentupdate" : 1
```

After this, it's probably not a good idea to update the MeshCentral server as sometimes new agents are required to support change in the server or new features.

The real solution would be to make the agent more customizable in the .msh file. This has been required before.

**Comment by BlackRouter** [comment]
> In the settings section of config.json, you can add the following:
> 
> ```
> "noagentupdate" : 1
> ```
> 
> After this, it's probably not a good idea to update the MeshCentral server as sometimes new agents are required to support change in the server or new features.
> 
> The real solution would be to make the agent more customizable in the .msh file. This has been required before.

thank you bro , it's useful
