### ISSUE TITLE
"ManageAllDeviceGroups" does not work for more that one user

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1309]
Initially I wanted to rename my admin account username, just not to have an "Admin" username as Full Administrator - very easy to guess that name. But since I have not found an option to rename it via GUI, decided to create another account with Full Right on the server and after tests delete my current "Admin" account. However, during test looks like it is not bad idea to have 2 or more Full Administrators on MC.
So i tried to add 2 users in "ManageAllDeviceGroups" section in config.json - the second user does not work as expected.
My line in config.json looks like this:
"ManageAllDeviceGroups": [ "admin","admin2" ],
admin2 can see all devices, have all right on the server as user1, but by some reason, cannot connect to any devices via Desktop(does not react on Connect click), or Terminal(stays in Setup... mode) or Files(stays in Setup... mode) .....
Could you look into this please:
 - possibly to be able to rename a main Admin account by itself
 - ability to have more than one users in "ManageAllDeviceGroups" section in config.json
Thanks.
Edit: current latest version 0.5.24

**Comment by Ylianst** [comment]
Interesting, checking now.

**Comment by Ylianst** [comment]
The way "ManageAllDeviceGroups" works, you also need the account to have "full server rights" otherwise it does not do anything. Can you check that both "admin" and "admin2" have full server rights?

Also, I did just test this feature and noticed that you could not perform remote desktop/terminal/files until this mode. I just fixed that, it will be in v0.5.25 when it's out later today.

**Comment by vitko-bg** [comment]
Hi Ylianst,
I can confirm that admin2 is with Full Admin Right on the server:
![image](https://user-images.githubusercontent.com/59362521/81217126-fdf84880-8fd3-11ea-8e04-25bb4bc8cc2a.png)
I checked it twice before uploading the issue :)

**Comment by Ylianst** [comment]
Oh sorry, after reading your report again I realize I fixed the desktop/terminal/files exactly as you reported it. So, it will be in v0.5.25 later today.

**Comment by vitko-bg** [comment]
Thanks a lot for quick response!!!
Shall I open another issue in regards to renaming users? No possibility to do this at the moment.....

**Comment by Ylianst** [comment]
Someone did ask for account renaming in the past and because the username is the primary key in many tables in the database, it's difficult to do. If done in real time, it could mess the database up. It could be done by shutting down the server and getting exclusive access to the database and changing all the keys, but it's a lot of work. I don't think it's worth the effort.

**Comment by vitko-bg** [comment]
OK, understood. However - it is not very essential.
Once new version is released - will test to confirm if "ManageAllDeviceGroups" for more than one user is fixed or not.
Thanks.

**Comment by vitko-bg** [comment]
Fixed in 0.5.25
Thanks!

**Comment by vitko-bg** [comment]
Reopening:
Scenario same as above, but some issues with admin2:
 - Users -> click on Admin2 -> Common device groups - **Not all groups are listed**
 - Users -> click on Admin2 -> Common device groups - **Add device group** with full admin rights **does not work**
 - In Users group "Administrators" - Admin2 is added - all agent group are listed as common Device Groups -  but Users -> click on Admin2 -> Common device groups - Not all groups are listed - same as above.
P.S. May option be added for All groups to be selected on assigning to a User?
Thanks.

**Comment by vitko-bg** [comment]
On MeshCentral Router issue when using Admin2 with the above settings:
All buttons are greyed out ...
![image](https://user-images.githubusercontent.com/59362521/83276338-59c78300-a1c8-11ea-84f9-b7bc09d2d5bc.png)

Normal behaviour with Admin account...

![image](https://user-images.githubusercontent.com/59362521/83276410-76fc5180-a1c8-11ea-93be-1cc6477cba13.png)
