### ISSUE TITLE
Add running powershell script on remote computers.

### ISSUE THREAD

**Issue by openmoto** [Ylianst/MeshCentral#131]
Hi,
Hoping this can be done.
I've used the "terminal" tab on MeshCentral, it's not great especially when you type "powershell" to enter powershell console, then it gets all messed up when you backspace.
Can some improvement be made to the "terminal" or even introduce powershell console (something that would work like powershell web access).

Would also be great to be able to store powershell scripts on the server that can be selected and ran per computer or per mesh.

Thanks

**Comment by Ylianst** [comment]
We are a bit overloaded with requests, but making Powershell work well in the terminal seems very reasonable. I am not much of a powershell user myself, but I will take a look at this when I can.

**Comment by MRCode010101** [comment]
It would be nice to be able to pass powershell scripts to remote PCs via MeshCentral, to further automate remote builds/reimages of devices

**Comment by Ylianst** [comment]
FYI. Somewhat related, Bryan just added PowerShell support in the Terminal. See #369.

**Comment by vitko-bg** [comment]
Not sure - but I think it has been resolved in last couple of weeks by adding a powershell option on right click on terminal button. Fix me if I am wrong.

**Comment by Ylianst** [comment]
I think you are right. I also added the same options to XTerm yesterday. I am going to close this one, but fell free to re-open if needed.
