### ISSUE TITLE
Security issue in web link ...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1311]
Just now realised that a username is clearly visible in link when selecting user in users tab.
![image](https://user-images.githubusercontent.com/59362521/81164618-8b15b000-8f88-11ea-894f-aff451d7d8e7.png)
![image](https://user-images.githubusercontent.com/59362521/81164705-b0a2b980-8f88-11ea-906e-fb1b84b79ff3.png)
In my personal opinion user name should not be visible in the link, will be very easy to find usernames which will make much easier to brute force into the system.
Thanks.

**Comment by Ylianst** [comment]
So, note that the list of users is only sent to administrators and that URL is only sent to the server if you make a request for it. One most take case of not having the user's password in the HTTP logs of the server, but usernames are common in that log.

If you had a better defined attack vector for this, let me know. I can also add a switch to disable the URL switching so each time you hit "reload" on the browser, you will get back to the main "devices" page. Let me know if you want this.

**Comment by vitko-bg** [comment]
I think it will be better let's say to have ID or some other info of the user in the link, if that is very necessary, but full user name ..... do not think it is a good idea.

**Comment by Ylianst** [comment]
The userid is the primary key for an account, if you have a specific suggestion for a replacement, let me know... or are you ok with having an option to remove the URL switching completely?

**Comment by vitko-bg** [comment]
I think it will be the best resolution (security reasons) not to display in the address bar any usernames.
If that can be done, please - will be the perfect scenario :)

**Comment by Ylianst** [comment]
Ok, added a new option that will be in v0.5.25 later today. You will add this to the domain section of config.json:

```
"urlSwitching": false
```

It will no longer display anything in the URL.

**Comment by Ylianst** [comment]
MeshCentral v0.5.25 is published. Let me know if it works.

**Comment by vitko-bg** [comment]
Working fine with "urlSwitching": false in domain section.
Thanks!
