### ISSUE TITLE
meshcentral may log cleartext passwords

### ISSUE THREAD

**Issue by mherrb** [Ylianst/MeshCentral#1313]
Hi,
While trying to figure out how to setup LDAP authentification with OpenLDAP, I stumbled upon this bit of code in webserver.js (iine 345), where pass is the password entered on the login page: 
```
if (!module.parent) console.log('authenticating %s:%s:%s', domain.id, name, pass);
```
This really looks like the user passwords may be logged in clear text under some circumstances. 
I would rather not do that...

**Comment by Ylianst** [comment]
Oh, thanks for the report. Not sure how this line would ever run, but still, I just removed that line completely and it's check in GitHub now. Will be in MeshCentral v0.5.25 later today.

**Comment by Ylianst** [comment]
MeshCentral v0.5.25 is published.

**Comment by Ylianst** [comment]
Closing this one as it's fixed. Please re-open if needed.
