### ISSUE TITLE
MeshRouter not working after 0.5.25 update

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1318]
Hi guys,
I had an older version of MeshRouter working using command line to start the application, login, and create an RDP mapping.  However after the last updates it no longer allows me to login and create an RDP map using command line.  The mapping is created, but cannot be opened for some unknown reason.  I've tried downloading the latest MeshRouter.exe from the 0.5.25 update, but this only made things worse.  Now I can't even log in manually.  The application just closes and disappears after login.  Please let me know of any solution available.

Thanks!

**Comment by Ylianst** [comment]
Thanks for the report. Working on it. Will publish a fix shortly.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.26 that should hopefully fix it. I noticed that is session recording is enabled, the server would crash when trying to perform a relay session. I also fixed things in MeshCentral Router.

**Comment by trentdavis** [comment]
So now I am able to login manually, Thanks!  But unfortunately the command line no longer works.  When I use it, the app just disappears.  I am using the following command:
MeshRouter.exe -mydomain.com -user:username -pass:password -map:tcp:1234:ServerSystem:tcp:3389

What I am trying to accomplish is to get the MeshRouter window with just the machine that has been specified in the command line, instead of all the machines in the group.  I've tried creating a user group for just that user and that machine, but If I log in manually I still see all the machines in the group.

**Comment by Ylianst** [comment]
Ok, I am taking a look at the command line version now.

**Comment by Ylianst** [comment]
I just tried `MeshCmd route` and it works fine, where did you get this "MeshRouter.exe"??

**Comment by trentdavis** [comment]
I downloaded from my server after updating.

**Comment by Ylianst** [comment]
So, is this "MeshCentralRouter.exe"? Did you re-download from the latest server and try again?

**Comment by trentdavis** [comment]
Yes, that's what I did.

**Comment by Ylianst** [comment]
Did what? Going to close this bug since the information is not accurate. If you want, open a new one with correct information including the exact command line you used. Thanks.
