### ISSUE TITLE
DesktopMultiplex blank screen

### ISSUE THREAD

**Issue by infineonnetworks** [Ylianst/MeshCentral#1326]
There seems to be a problem with the later versions of Meshcentral when enabling the DesktopMultiplex option. 

When enabled, one can't connect to the machines desktop any more, with just receiving a blank screen. 
After when having this DesktopMultiplex disabled (removed from config.json) it won't connect any more either, but giving the error "Received invalid network data" error instead and on the Console showing significant errors:

```
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
```

Any suggestions?

Running version 0.5.28

**Comment by infineonnetworks** [comment]
From another system a added error: 
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'userid' of undefined in method 'onTunnelData()'

**Comment by Ylianst** [comment]
I tried a bunch of things and can't replicate this on my servers. I did add some code to handle errors better than will come in v0.5.29, but that may not help. Can you give a lot more details about your server, what OS the MeshAgent is running, are you using plug-ins? Reverse proxy? Any customization of the server or agent? Any hint of anything that can help make this problem happen on my machine would be appreciated. Thanks.

**Comment by Ylianst** [comment]
MeshCentral v0.5.29 is published, if you can try again in addition to providing more details, that would be great. Thanks.

**Comment by Ylianst** [comment]
I think this is solved. Please open again if needed.
