### ISSUE TITLE
How to generate authendication token using API not with meshcentral.js

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1329]
How to generate authentication token using API not with meshcentral.js

I have aware to generate the token using MeshCentral using below command. but I want to generate the token using the my web application to invoke the MeshCentral UI. 

`--logintoken`

How can i achieve this.

**Comment by ryanblenis** [comment]
A little hard to tell given the information supplied, but [this](https://github.com/Ylianst/MeshCentral/issues/1257) thread regarding token creation might be of interest to you.

**Comment by Ylianst** [comment]
I just uploaded [meshgentoken.js](http://info.meshcentral.com/downloads/MeshCentral2/meshgentoken.js), take a look at it. It has instructions on how to get the login key from your server and generate login tokens. Let me know if this helps.

**Comment by aimdharma1990** [comment]
Thanks, Its working perfect now. I can able to understand the logic better.
One more thing on this, is that logintokenkey of the server will get
changed ? or will it static for an server ?

The generated token will get expires in what time ? is there any
configuration to change the default time ?

**Comment by Ylianst** [comment]
Hi. The "LoginTokenKey" is static and will not change, however it's probably a good idea to rotate this key occasionally and so, you can run this to generate a key login key:

```
node node_module/meshcentral --logintokengen
```

Also, the token is valid for 1 hour, but you should generate a new token each time a user needs to login. Hope that helps.

**Comment by aimdharma1990** [comment]
Thanks its helps lot. Is there any option to change the 1hour time
interval ?

**Comment by Ylianst** [comment]
Yes, you can encode the expire time in the cookie like this:

```
console.log(encodeCookie({ u: userid, a: 3, expire: 120 }, loginCookieEncryptionKey));
```

Change the sample code to add `expire:102`. This will expire the cookie after 120 minutes. However, you should make the cookie expire faster and generate more of them when needed.

Assume that malware is going to steal the cookie, so if you put a long time, your account will be easier to hack.

**Comment by aimdharma1990** [comment]
Thanks for the quick response.
