### ISSUE TITLE
Suggestion: logging of latency for AgentPing

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#1332]
I've got a unique situation where a user is moving between varying quality Internet links and am wondering whether it would be a good idea to log the ping/ping round trip time for monitoring purposes.

I've hacked it into meshagent.js and see the following for every endpoint:
```
2020-05-12T03:57:39.227794+00:00 localhost node: Agent ping NodeId=[xx], IP=1.2.3.4:48446, Agent=4.
2020-05-12T03:57:39.303997+00:00 localhost node: Agent pong NodeId=[xx], IP=1.2.3.4:48446, Agent=4.
```

This is enough to calculate a metric for response time although it does get noisy with lots of endpoints :)

Wondering if this desirable for others and could be put intot he code somehow?  I'm not a nodejs developer so what I've whipped up is strictly a copy and paste of console.log in the right points of code :)

Thanks!

**Comment by dinger1986** [comment]
@si458 thoughts on this?

**Comment by si458** [comment]
i was literally just looking at this and toying it up!
im just trying to work out how to calculate the latency?

browsers asks meshcentral whats latency for this agent, meshcentral asks agent for latency, agent replying going you tell me, meshcentral goes oh well that took 50ms, meshcentral tells browser took 50ms

that sound about right? i was only going to put it in as a command in Console tab per device, something like `latency`

**Comment by si458** [comment]
yeh but im not wasting time trying to record the latency into the DB, this isnt a full remote management software but remote support, so latency at that time seems ok to me

**Comment by silversword411** [comment]
That, and you're going to kill your SSDs with so much DB writing.

I recently noticed I'm at +60% of life on 2 year old SSDs in my proxmox.

**Comment by si458** [comment]
turns out the code was already on there for this!
it was just missing the timer interval! ive set it to get it on first connect, and then update every 10 seconds, wasnt sure if i should set the timer to a smaller interval?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/c225a8fe-a185-4e3c-ad3b-3f94a31b6381)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/00cafe2b-d6cb-40b1-bba6-606c0b20e7d7)

**Comment by silversword411** [comment]
> wasnt sure if i should set the timer to a smaller interval?

Nope, 10 seconds is plenty.

Might move that and connect time to the left of the monitor icons though. So monitor icons don't move around

**Comment by si458** [comment]
Oh yeh I see what u mean haha if u suddenly get a high ms haha
I'll set the div area for the timer to a fixed width! T

**Comment by si458** [comment]
better? i just cant the monitors to move, so i added spacing instead
![latency](https://github.com/Ylianst/MeshCentral/assets/765314/ded9241b-defc-423f-b497-965b4d81c306)
