### ISSUE TITLE
Why no 2FA when domainauth ?

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1335]
Is there a reason why 2FA is disabled when domainauth is set (LDAP & SSPI)?

In views/default.handlebars:

```
QV('p2AccountSecurity', ((features & 4) == 0) && (serverinfo.domainauth == false) && ((features & 4096) != 0)); // Hide Account Security if in single user mode, domain authentication to 2 factor a\
uth not supported.
```

I replaced it by `QV('p2AccountSecurity',true)` then added a hardware security key and all seemed to work.

For example Nextcloud and gitlab both can use LDAP and allow users to add hardware security key.

**Comment by Ylianst** [comment]
I have not tried LDAP and it should probably work with it. For SSPI the login screen is skipped completely and so, the assumption is that if your using a second factor, you would do it to perform user domain login. At some point, I should try to install OpenLDAP and experiment with it more. This said, if you want to open a request to enable 2FA with LDAP, that would be great if you can also test it and make sure it works ok.

**Comment by guerby** [comment]
Done for LDAP and 2FA : https://github.com/Ylianst/MeshCentral/issues/1340
