### ISSUE TITLE
BUG: Faulty minifying renders v0.5.22+ unusable if "Minify" is set to true (v0.5.31)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#1336]
Hi!

A faulty minifying (if enabled using "Minify": true for the settings or a domain) renders MC unusable for any version newer than 0.5.21, including the current 0.5.31:

When the placeholder `{{{pluginHandler}}}` (which also remains unminified even if minifying is active) is expanded, the substitute ends with ";", resulting for default-min.handlebars in this construct:

        ... var ...,pluginHandlerBuilder=function() {
        ...
        return obj; };,pluginHandler=null; ...

The `;` appended to `function{}` within the declaration list causes a syntax error. As a result, anything beyond the login page appears just as a blank white page.

Best regards,
// Veit

**Comment by veitw** [comment]
PR #1337 fixes this.

Noice number :D

**Comment by Ylianst** [comment]
Nice. Thanks for the PR!! It will be in MeshCentral v0.5.32 when next published later today. Note that I don't do any testing with plug-in's and leave it up to @ryanblenis.

**Comment by veitw** [comment]
Great, will update tomorrow. :)

I need to add that I also tried with all plugins in MC being disabled, resulting in the same problem. But the plugins were not completely removed, so they still showed up in the Plugins tab.

Unfortunately I did not have time to try with a completely fresh instance with empty meshcentral-data/ dir.

**Comment by ryanblenis** [comment]
I hadn't usually tried with minification in my dev env, I'll have to add that to my test list. As for testing with plugins disabled, you can just change "plugins" to "_plugins" in the config and it will disable them all in one swoop while testing. Thanks for the find & PR!

**Comment by veitw** [comment]
v0.5.32 runs fine ootb with plugins and minifying enabled. Thanks!
