### ISSUE TITLE
Raspberry pi notify disconnect and connected many times

### ISSUE THREAD

**Issue by khuyenht** [Ylianst/MeshCentral#1339]
Hi all, i am using linux agent for 3 raspberry pi device. When i log in to mesh central, raspberry pi device always pop up disconnected and connected many times.
Operating System Version Raspbian GNU/Linux 10 (buster)
Mesh Agent: ARMv6l / ARMv7l

Could you please support to fix this issue.
Thanks so much

**Comment by Ylianst** [comment]
I am not sure what you are requesting. You can go in the device group and turn off Connect/Disconnect notification. Otherwise, are you saying the notifications are not correct or should be displayed differently?

**Comment by khuyenht** [comment]
Hi Ylianst,
i think the connection form linux agent to mesh central not stable.
what i observe connection form agent to mesh central :
i run script on raspberry pi ( script has command sleep 60 ), sometime the connection from agent disconnected before my script completed i have to reconnect and run script again.

i am not sure agent disconnected cause by network connection or others reason.
Could you please help. i have just used mesh central so i don;t have much knowledge about it.
Thank you so much.

**Comment by Ylianst** [comment]
On the raspberry Pi device can you go to /usr/local/mesh and see if a "meshagent.log" file is present? If so, can you post the last 20 to 30 lines of that file and also give us the total size? Thanks.

**Comment by khuyenht** [comment]
Hi Ylianst,
There is no meshagent.log in /usr/local/mesh
Thanks & Best Regards,

**Comment by Ylianst** [comment]
Is your server using plug-ins?

**Comment by khuyenht** [comment]
Hi Ylianst, 
i don't use plug-ins .
i have haproxy in front of Mesh Central. do you think this issue cause by haproxy timeout ?
could you please advise me.
Thank you
