### ISSUE TITLE
Question: MeshAgent update behaviour

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshCentral#134]
Hey,

just a quick question on how the MeshAgent works. If i deploy the current MeshAgent.exe which i download from my server to lets say 100 machines. The MeshAgent on these machines will only be ran with MeshAgent /connect, not as a service.

Will be Agents on the remote machines update itself? I have my server on auto-update and i dont want to update the MeshAgents on all my remote machines manually.

For now, i think it works that way but i just wanted to have a confirmation that it will always work that way and i never have to update MeshAgents on remote machines manually when only using MeshAgent /connect.

Thanks for your great work!

**Comment by Ylianst** [comment]
Hi. Yes, all agents self-update so you should never have to worry about this.

However, if MeshCentral where to update the agents incorrectly, it could lead to a big issue and people having to fix all agents manually. So, Bryan and I are working on a way for a second agent on each machine to periodically call home every 2 days or so to make sure everything is alright. We would get a second chance to fix any bad update.

Hope it helps,
Ylian

**Comment by marco-vogt** [comment]
Hi Ylian,

thanks for your response - glad to hear.
I guess youre todo list is quite big right now, so ill wait for the second agent - no hurries.

When you come around to make this though, just a little note: I think once every 2 days or so is way too infrequent because when the agent isnt working, you have no way of remotely fixing the issue and having to wait 2 days would be quite the pain.

**Comment by krayon007** [comment]
2 days was just for background checks to make sure everything is ok. I was actually thinking of making it so when an agent attempts a self update it would set a cron job for the diagnostic agent to kickoff like 15 minutes later or something to make sure the update went smoothly. It would be able to revert the update for example, if something failed, etc...

**Comment by Ylianst** [comment]
Once out of beta, we may have two branches (Early & Production). However, there is never a guaranty that something will not fail down the road with the agent and so, MC needs an agent recovery system, even if it's never needed or used. I am going to close this issue, we can re-open discussion on this once we get something implemented in this space.
