### ISSUE TITLE
Please enable 2FA when using LDAP for auth

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1340]
Subject says it all :)

This issue is opened following the discussion on this issue : https://github.com/Ylianst/MeshCentral/issues/1335

Thanks!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.32 where I think it's enabled, but since I don't have LDAP, I can't test it. Let me know if it works.

**Comment by guerby** [comment]
I confirm v0.5.32 has working LDAP + 2FA, thanks again!

**Comment by Ylianst** [comment]
Excellent! Thanks for reporting back.
