### ISSUE TITLE
Agent-based remote desktop on Windows not working in v0.5.27+ (v0.5.32)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#1342]
Hi!

I noticed that the remote desktop is not working for any of my Windows users with MeshCentral >0.5.26, including 0.5.32:

After hitting the "Connect" button, the Windows client shows the consent window. After accepting, the remote management bar shows up on top of the screen, and MC shows the status "Connected" and the clock is counting, but the screen stays black.
Also after disconnecting in MC, the remote management bar on the client does not disappear.

* AMT console/HW connect is not affected.
* Linux agent is not affected
* macOS agent was not tested
* plugins and minifying have been disabled in config for testing, problem persists
* problem occurs in both current Firefox and Chromium
* Firefox' JavaScript console does not show any errors/warnings except these (which also appear on a working 0.5.26 installation):
  * recommendation to setup a STUN server for WebRTC when ICE fails
  * sometimes "The connection to wss://.../meshrelay.ashx?browser=1&p=7&nodeid=node//...&id=...&auth=... was interrupted while loading the page. agent-redir-ws-0.1.1.js:52:21" (translated from German)

The runtime environment:
* MC runs on CentOS 7.8 x86_64 system with all updates installed
* Node from RedHat's rh-nodejs10 SCL repository:
  * rh-nodejs10-3.2-3.el7.x86_64
  * rh-nodejs10-nodejs-10.19.0-1.el7.x86_64
  * rh-nodejs10-runtime-3.2-3.el7.x86_64
  * rh-nodejs10-npm-6.13.4-10.19.0.1.el7.x86_64
* MC was installed via npm, fresh install

Any help is appreciated.

Best regards,
// Veit

**Comment by petervanv** [comment]
I can confirm the same issue, the log at the node say's: 
[2020-05-13 12:24:20 PM] FATAL EXCEPTION [MeshAgent_72C50F4A2BFDE64F.exe] @ [FuncAddr: 0x00007ff6483644ac / BaseAddr: 0x00007ff6483ce878 / Delta: 435148]

when the same machine does not haven user consent and the connection toolbar, switching between the options, did not resolve the problem. disabling the consent and toolbar resoves the problem .

**Comment by Ylianst** [comment]
Yes, the user consent prompt is causing the agent to crash when you click "yes" or "not". Bryan is aware of this and working on a new agent that fixes it.

**Comment by amenolo** [comment]
Any news about this issue? Thanks

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.37 with Bryan's newest MeshAgent with a lot of stability improvements. it should fix the user consent issues and a lot more, especially on Windows.

**Comment by amenolo** [comment]
> it should fix the user consent issues

Yes it does!

**Comment by Ylianst** [comment]
Also, user consent prompt now shows up on top of other windows! (All credit goes to Bryan for this)

**Comment by vitko-bg** [comment]
> All credit goes to Bryan for this

THANKS Bryan!!!!

**Comment by petervanv** [comment]
Confirmed working here also.
Thx Bryan

**Comment by veitw** [comment]
Thank you very much, Bryan! 

As I am on holiday at the moment, I will not be able to verify and close the issue by myself until end of May, but I will instruct my colleagues to give 0.5.37 a try and report back.

**Comment by veitw** [comment]
My collegues report it working like a charm, thank you very much!
