### ISSUE TITLE
Both update checkbox options are selectable at the same time

### ISSUE THREAD

**Issue by bnrstnr** [Ylianst/MeshCentral#1343]
In the Server Version window, if you're not on either the latest or stable build it will allow you to check both boxes. I didn't go through and check the OK button to see what would happen, but the option was available.

**Comment by Ylianst** [comment]
Where you select both, the OK button is grayed out, so it's should not be possible to act on this selection. Still, because you mentioned it, I fixed it so that the other option is grayed out when one is selected. It will be in v0.5.33 when it's next published.

**Comment by bnrstnr** [comment]
Ah, sorry for the mistake. Thank you for the reply!
