### ISSUE TITLE
Mesh agent does not work for some Windows machines

### ISSUE THREAD

**Issue by turin331** [Ylianst/MeshCentral#1345]
I have been trying to use meshcentral for remote assistance. 
It seems to work fine on Linux and Windows Pro up to 1903. 

But there are certain versions that on windows even though the agent seems to operate the PC does not appear on mesh central. It is allowed through the firewall so this should not be an issue. 

These versions seem to be Windows 10 enterprise 2016 LTSB and Windows Pro 1909. 

I actually noticed a detail. The PCs that do not connect were also on different VLANs in the local network could that be an issue?

I am using server Version 0.5.32 and agent version 0.2.1.

**Comment by turin331** [comment]
I actually noticed a details that might be a different issue entirely.  The that do not connect were also on different VLANs in the local network could that be an issue?

**Comment by petervanv** [comment]
the situation of your server, does it communicate via a wan or only lan?
and can your computer that cannot connect connect to the server running meshcentral? (ping for example?)

**Comment by turin331** [comment]
The server communicates through LAN. But the machines can ping the meshcentral server fine.

**Comment by petervanv** [comment]
can the server ping the workstation correctly ?

**Comment by turin331** [comment]
Yes it does.

**Comment by petervanv** [comment]
is it possible to place the computer in the same vlan as the meshcentral server to test ?

**Comment by turin331** [comment]
Was thinking the same thing. I am not physically at the site but will do so when there.

**Comment by krayon007** [comment]
if you can look at the msh file of your agent, I'd be curious to know if the server url has an actual url, or it it says local. If the latter, it uses multicast to find the server... I know a lot of corporate VLANs are setup to not propagate multicasts, which is what I'm guessing your issue is.

**Comment by turin331** [comment]
> if you can look at the msh file of your agent, I'd be curious to know if the server url has an actual url, or it it says local. If the latter, it uses multicast to find the server... I know a lot of corporate VLANs are setup to not propagate multicasts, which is what I'm guessing your issue is.

It is indeed set as local. Should i change this to the server IP?
How would i do that on meshcentral in order to produce a correct agent executable?

**Comment by turin331** [comment]
@krayon007 I did try to use the server IP or computer hostname on the msh file but the results were the same.

**Comment by Ylianst** [comment]
You can't just replace "local" with the hostname or IP address, you have to put the full websocket URL:

```
MeshName=Home Computers
MeshType=2
MeshID=0xEDBE1...
ServerID=D99362D...
MeshServer=wss://server.com:443/agent.ashx
```

However, changing the .msh file yourself it not the right way to do this. [Follow the installation instructions](https://www.npmjs.com/package/meshcentral), there is a "--cert" option where you put the IP address or DNS name of your server and the server will switch from "local" to "Hybrid" mode and agent agents installed after that will have the right .msh file with the correct URL.

**Comment by turin331** [comment]
Thank you this did work. I did run the cert option the first time i set up the server. I thought it would be retained after reboot. Thanks a lot!
