### ISSUE TITLE
Leftovers of Mesh Agent after uninstall

### ISSUE THREAD

**Issue by dnutan** [Ylianst/MeshCentral#1346]
On Windows, after uninstalling the agent there are leftovers.
The service and the installed program entry are removed but the installation directory and files remain in Program Files (meshagent.[exe|db|msh]), as well as the firewall rules. Haven't checked if there's anything in appdata directory or in the registry.

**Comment by Ylianst** [comment]
I think Bryan got this fix for the upcoming version of the MeshAgent. However, there are many other changes and so, the agent has to go thru a bunch more testing and fixes.

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
