### ISSUE TITLE
How to get the list of Online Users?

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1348]
Hi,

I've been looking for a way to get the list of Online Users from meshctrl or by parsing files on the server but without luck so far.

The web server does it in js:

```
// Online users
   for (var i in sortedUserIds) {
     var user = users[sortedUserIds[i]], sessions = null;
     if (wssessions != null) { sessions = wssessions[user._id]; }
     if ((sessions != null) ... => active
```

Is there a way to get this information with meshctrl or reading *.db files?

Could be a flag on userinfo or a session list or anything else.

Thanks!

**Comment by Ylianst** [comment]
Just added a new "ListUsersSessions" command to MeshCtrl.js. It will be in MeshCentral v0.5.33 when it next comes out.

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.5.33 was published, so this should be solved.

**Comment by Ylianst** [comment]
Got no feedback so closing this one. Please re-open if needed.
