### ISSUE TITLE
Feature Request: Desktop connect right click -> Show connection toolbar

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1349]
Thanks for all hard work.
Will it be difficult to add a Show connection toolbar or just "Toolbar" on desktop connect right click?
For some cases it will be very useful - not all computer in the group need toolbar and not always. So would like to have it for one-off connections.
Thanks!!!

**Comment by Ylianst** [comment]
Just added it. Will be in MeshCentral v0.5.33 when next published.

![image](https://user-images.githubusercontent.com/1319013/81976472-72874480-95dd-11ea-8dad-8856221a74ab.png)

**Comment by vitko-bg** [comment]
THANKS!!!!!!! That was quick!!!
Will test it now.

**Comment by vitko-bg** [comment]
Working GREAT! Closing now!
THANKS AGAIN!!!!
