### ISSUE TITLE
Cannot go to device

### ISSUE THREAD

**Issue by shihuihzh** [Ylianst/MeshCentral#135]
Hi. Mesh is a wonderful project. And I try to use MeshCentral to manage my AMT device but there some problem on my local test computer.

![20190317220107](https://user-images.githubusercontent.com/4484295/54492295-2882d000-4900-11e9-9c93-2c800a17d4e1.png)

There is an error when I click my device in the page.
My local test platform is Arch which is one of pupular  Linux distribution.
May I know what happen about this? Thanks for you help in advance.
 
![20190317215621](https://user-images.githubusercontent.com/4484295/54492260-f4a7aa80-48ff-11e9-8bc1-6b80b665ac2e.png)

**Comment by Ylianst** [comment]
Oh! I will fix this tomorrow when I get to work. Probably just a small UI bug. Thanks for the report.

**Comment by krayon007** [comment]
Just for good measure, I'll create an Arch Linux VM and do some testing with it...

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.0-o with a fix for this. Easy UI fix.

**Comment by krayon007** [comment]
As a sidenote, I setup ArchLinux . In order for KVM to work, you need to edit:
/etc/gdm/custom.conf
to force the logon manager to spawn an Xorg session instead of a Wayland session.

**Comment by Ylianst** [comment]
I will close this one since I am pretty such it's fixed. Please re-open if needed. I know Bryan has been working on Arch Linux agent support. Pretty crazy how many Linux distro's he is testing now.

**Comment by shihuihzh** [comment]
Hey @Ylianst @krayon007 . Thanks for your reply.
It works now even  the newest version in npm or use source code from this repository.
Thank you very much again. This is a fantastic project.
