### ISSUE TITLE
meshctrl removeuserfromdevice does not completely remove the device from user web UI

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1350]
When launching meshctrl removeuserfromdevice the removed device still appears in the web UI for the given user, but the user has no right to use it.

Checking the code in meshctrl.js : 

```
            case 'removeuserfromdevice': {
                var op = { action: 'adddeviceuser', nodeid: args.id, usernames: [args.userid], rights: 0, responseid: 'meshctrl' };
```

I added `remove: true,` to the op and then the device really disappear from the user web UI.

I don't know if the current behaviour is wanted or if it is just a bug?

**Comment by Ylianst** [comment]
That is a bug and your exactly right about the fix. Just checked it in, will be in MeshCentral v0.5.33 when next published.
