### ISSUE TITLE
Getting MeshCentral to work with Caddy v2

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1351]
@Ylianst @krayon007 @whalehub 

You guys were of tremendous assistance in solving some caddy reverse proxy issues earlier on this ticket:
https://github.com/Ylianst/MeshCentral/issues/838

Do you guys have an updated Caddyfile for Caddy V2?
After upgrading I'm getting errors in Caddy trying to get a certificate, because of a TLS handshake error

########
2020/05/14 11:17:00 http: TLS handshake error from 192.168.2.178:51983: no certificate available for 'mesh.southeastern.biz'
2020/05/14 11:17:00 http: TLS handshake error from 192.168.1.54:38626: no certificate available for 'mesh.southeastern.biz'
2020/05/14 11:17:00 http: TLS handshake error from 96.89.67.73:47834: no certificate available for 'mesh.southeastern.biz'
##########

The previous Caddyfile directives no longer work:
#########
mesh.southeastern.biz  {
        reverse_proxy 192.168.1.63:80
  tls {
   protocols tls1.3
  }
}
########

It's entirely possible I've got my syntax wrong.
Thanks!
Shane

**Comment by southeasterntech** [comment]
note TLS 1.2 also produces a handshake error

**Comment by Ylianst** [comment]
What version of NodeJS are you using to run MeshCentral? NodeJS v12 supports TLS1.3. Without looking into this in detail, it could be that upgrading NodeJS will help.

**Comment by southeasterntech** [comment]
Thanks @Ylianst 
I'm on Node 10.15.3, but note that the above screenshot was after attempting TLS1.3, but, I was using 1.2 previously, on Caddy V1.  Now that I've gone to Caddy V2, TLS 1.2 no longer works... and it's fairly above my head as to why.  Any other ideas?  1.2 is what I'm really trying to get working.
Thanks

**Comment by southeasterntech** [comment]
this was resolved by moving the Mesh port from 443 to 4430, in CaddyV2 I think 443 is used, and possibly you can't use mesh on 443 also.  I also upgraded to the latest NodeJS, 14.4  Now everything is working. 
Thanks!

**Comment by SemoTech** [comment]
> this was resolved by moving the Mesh port from 443 to 4430, in CaddyV2 I think 443 is used, and possibly you can't use mesh on 443 also. I also upgraded to the latest NodeJS, 14.4 Now everything is working. Thanks!

Hey @southeasterntech, would you mind sharing the relevant configs for both MeshCentral and Caddy 2 that worked for you?  I am getting errors and am unable to get this working.  See configs I have below as well as the error messages:

https://pastebin.com/gMhqALGi
