### ISSUE TITLE
Wording on Agent Invite page

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1352]
I've recently noticed that the wording on the Remote Agent Installation page (the page that is generated from an Invite link) has poor wording.  It currently reads like this:

 "You have been invited to install a software that will allow a remote operator to fully access your computer remotely including the desktop and files. Only follow the instructions below if this invitation was expected and you know who will be accessing your computer. Selecting your operation system and follow the instructions below. "

It would be better worded like this or something similar:

"You have been invited by (%CompanyName%) to install an application that will allow a remote operator to securely access your computer including the desktop and files. Only follow the instructions below if this invitation was expected and you know who will be accessing your computer. Select your operating system and follow the instructions below for installation. "

For Company Name I'd want to be able to customize that so it shows the name of my Company and/or my real name (not my MeshCentral logon name).

**Comment by Ylianst** [comment]
Thanks for the request. I changed the text to this for now:

"You have been invited to install an application that will allow a remote operator to securely access your computer including the desktop and files. Only follow the instructions below if this invitation was expected and you know who will be accessing your computer. Select your operating system and follow the instructions below for installation. "

I need to work on what to do about the company name.

**Comment by PathfinderNetworks** [comment]
Perfect. Thank you.  The company name part would just make it look more official to those I invite.
