### ISSUE TITLE
Session indicator shows too many connections

### ISSUE THREAD

**Issue by pedjateg** [Ylianst/MeshCentral#1353]
MeshCentral Version 0.5.32
There is no active sessions, last session was 3 hours ago and that computer (initiator) is shut down.
 I am only active user on meshcentral server.

![mc-1256sessions](https://user-images.githubusercontent.com/64255854/81979102-bc4b4b80-962c-11ea-9c9b-c4e1751e9148.png)

**Comment by Ylianst** [comment]
Oh dear! I will look into this. Interesting that it's the "files", that gives me a hint.

**Comment by Ylianst** [comment]
I can't seem to replicate this... if you have any way to make this happen, let me know.

**Comment by ryanblenis** [comment]
You should be able to replicate it fairly easily: 
- Go to the Files tab
- Click connect
- Every folder / file you click (even going back to the Root) increases the session counter.

**Comment by Ylianst** [comment]
Ok, thanks. Will look at this now.

**Comment by Ylianst** [comment]
Ok, I see the same problem now! Working on it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.35 with a fix for this. Let me know if it works.

**Comment by pedjateg** [comment]
It works.
Thanks.
