### ISSUE TITLE
Waiting for user grant access

### ISSUE THREAD

**Issue by khuyenht** [Ylianst/MeshCentral#1355]
Hi ,
Mesh Central upgraded from Stable version 0.5.11 to 0.5.31, when connect to terminal Raspberry Pi
i found this notification Waiting for user grant access , i can't access to terminal.
![raspberry](https://user-images.githubusercontent.com/62901295/82008216-467bca00-9696-11ea-99a8-1721dd4476d1.PNG)
Please help.
Thanks & Best Regards,

**Comment by petervanv** [comment]
Possible ways to fix your problem:

config.json
![Screenshot_31](https://user-images.githubusercontent.com/58996467/82067744-69779f80-96d1-11ea-98be-4a9069508813.jpg)

In meshcentral self
![Screenshot_30](https://user-images.githubusercontent.com/58996467/82067745-6a103600-96d1-11ea-8a82-79124884ac21.jpg)

**Comment by Ylianst** [comment]
Correct, you have user consent prompt turned on for the terminal. This can be enabled for a given device, for the device group or for the entire server.

For the device:
![image](https://user-images.githubusercontent.com/1319013/82092266-c9f4e580-96ad-11ea-829b-ec057f988d57.png)

For the device group:
![image](https://user-images.githubusercontent.com/1319013/82092332-ebee6800-96ad-11ea-9e43-bea56daba289.png)

**Comment by khuyenht** [comment]
Thanks so much for your guide,it's working well
