### ISSUE TITLE
screen stays black when connecting remote from large view

### ISSUE THREAD

**Issue by schplurtz** [Ylianst/MeshCentral#1356]
Hi

This is hard to describe. Hopefully the screenshots will be easy to understand.
meshcentral version : 0.5.33
node version : Node.js v14.2.0.
The screenshot show a remote linux, but I have the same behaviour with macos or windows remote computer.

![image](https://user-images.githubusercontent.com/1008292/82015845-fdb91680-967f-11ea-92e6-6d5cd9da598c.png)

**Comment by Ylianst** [comment]
Thanks for the report. You are right, I see the same problem. Never noticed that before.

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.5.34.

**Comment by schplurtz** [comment]
Thanks for the super fast fix.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.34. Re-open if not fixed. I also improved mouse cursor handling.

**Comment by schplurtz** [comment]
Thanks. I missed 0.5.34, but now use 0.5.36. Everything works great.
