### ISSUE TITLE
Branding / Logo for MeshCentralRouter.exe

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1358]
This isn't an issue, but more of a question.  Would it be possible to set logo branding for the MeshCentralRouter.exe file?  Maybe even alter the filename itself as well?

Thanks!

**Comment by ryanblenis** [comment]
It's all [open source](https://github.com/Ylianst/MeshCentralRouter) so you can change pretty much anything you like!

**Comment by Ylianst** [comment]
Right, MeshCentral Router is [open source C# code on GitHub](https://github.com/Ylianst/MeshCentralRouter), so you can brand it any way you like. I could make it easier to brand, but already overwhelmed with requests.
