### ISSUE TITLE
Server Version Check Failing

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1359]
This does not seem to be a bug affecting all installs since a friend of mine is not having this issue but on my server (currently running 0.5.33), the server version check shows "Unknown" for both Stable and Latest versions. Anything I can check to figure out what's keeping it from checking properly? It worked fine until yesterday or late the day before.

**Comment by PetieM** [comment]
Quick update - for some reason, this seems to have resolved itself. Not sure what was going on but I'm currently seeing correct version numbers.

**Comment by Ylianst** [comment]
Weird. In general, MeshCentral will display "unknown" if it can't find or call "npm" to get version information. MeshCentral will try to find "npm" on it's own, but if your seeing this one fix is to explicitly specify the NPM path in the settings section of config.json like this:

```
"NpmPath": "c:\\npm.exe",
```

That will fix it.

**Comment by PetieM** [comment]
It fixed itself this time but I added the npm path regardless, just in case. Thanks!
