### ISSUE TITLE
Incorrect Agent Status

### ISSUE THREAD

**Issue by openmoto** [Ylianst/MeshCentral#136]
I've noticed that when I open the agent installer on a system that's already installed and online on meshcentral server,, the status shows "Not Installed".
I've tried this on a few other systems and it's always the same.

**Comment by Ylianst** [comment]
Thanks for the report. Is this 32 or 64 bit? If you right click on the agent and run "As administrator", does it change the outcome? - Thanks.

**Comment by Ylianst** [comment]
I do notice that if the agent is not "Run as administrator" it does indeed not show the correct running state. Looking into this.

**Comment by Ylianst** [comment]
Ok. Fixed it in the agent, but this will only be published when the new agents get pushed into MeshCentral. This could take a week or more since this is not critical.

**Comment by theredkoala21** [comment]
Also seems that some clients are not being detected as OFFLINE. MeshCentral says they are online.
The way i confirm this is by going into the agent console of the device and sending "help". 
No response means offline, response = online!

Is there a better way to correctly detect power state?

**Comment by openmoto** [comment]
Sorry for dropping off here.

Tested server version 0.3.3-a on Ubuntu 18.04.2 LTS as well as server 2012R2 (Both 64bit OS)
When new agent is downloaded and run as admin, it does show status as running.
Without running as admin, it doesn't detect running service even if logged on user is admin.

This works for me. However installing the new agent 
Client OS is Windows 10. 64bit.

Though after installing the new agent it went offline :(
Restarting service or rebooting computer didn't help though.

**Comment by Ylianst** [comment]
The incorrect Windows Service status report is fixed int he code. This is only for the Windows Agent when looking at the dialog box without administrator permissions. This will be in the next MeshAgent release, hopefully next week.

For debugging the agent, open a command prompt in administrator mode and run "meshagent.exe run", you should see what is going on. If there is a problem, please report back. Thanks.

**Comment by openmoto** [comment]
Looks like we're good.
Must have been something on my computer.
At first run seems like couldn't access database so rebooted again and it just came back online.

>C :\Program Files\Mesh Agent>meshagent.exe run
MeshCentral2 Agent
Connecting to: wss://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:443/agent.ashx
Connected.
Server verified meshcore.... Launching meshcore...

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.6-n with the new MeshAgent that has a fix for this. I tested it and it works. I am going to close this one, but please re-open if needed.
