### ISSUE TITLE
Device group counter (0.5.34)

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1362]
After creating, en cleaning up device groups i saw the counter only increase and after removing the group not decrease in numbers.

![Screenshot_32](https://user-images.githubusercontent.com/58996467/82100659-8c727580-970a-11ea-8719-0a8d2ea2f35e.jpg)

**Comment by Ylianst** [comment]
Ha yes, this is because when you delete a device group, it just marks it as deleted so I can "un-delete" it if an agent connects back to a deleted device group. I will fix this now to only count active device groups.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.35 with a fix for this!

**Comment by petervanv** [comment]
Your fast, confirmed fix

Thx again
