### ISSUE TITLE
[Question] DesktopMultiplex

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#1364]
Just wondering the state of DesktopMultiplex. Is it stable? Is it preferred? Should it be enabled? Is it going to eventually replace the current connection method as the default?

On a larger note, while everyone loves new functionality, I think sometimes (especially where manual config.json changes are concerned) it is a little unclear as to the intended use cases or preferred usage/implementation of some of the features that get introduced.

Thank you as always.

**Comment by Ylianst** [comment]
DesktopMultiplex seems to be pretty stable at this point. Right now it seems to be more stable that having the agent deal with many remote desktop connections. The current drawback of DesktopMultiplex is that it effectively disabled WebRTC for remote desktop. So, all the traffic much go thru the server.

One thing I would like to do it setup WebRTC but switch back to going thru the server if a second user connects. So i would have to undo the WebRTC connection.

There is no question that if you often have 2 or more users viewing the same remote desktop at the same time, the DesktopMultiplex feature is really good.

As with any new feature, I keep things disabled at the start. In this case, if you have WebRTC disables anyway, you should probably turn on DesktopMultiplex.

**Comment by ryanblenis** [comment]
Thank you!
