### ISSUE TITLE
Feature Request: Admin View Log Events

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#1369]
Hi, 

Is possible that the admin users groups, can view all task and actions over agentes, for example, I can see my own actions (log events), but we need view another actios from normal users. 

This because going to all users, one to one for audit his actions, take a long time.

Thank You,

**Comment by Ylianst** [comment]
If you are administrator for a device group, you should be able to see all actions taken by all users for devices on that group. That should be the behavior now. You should also be able to click on a device and look at "events" to see all actions taken by any users on that device. This should work now. Let me know if it works.

**Comment by Ylianst** [comment]
I am going to close this one, but feel free to re-open if that did not answer the question.
