### ISSUE TITLE
Backspace on partial user

### ISSUE THREAD

**Issue by sdlopexvidri** [Ylianst/MeshCentral#137]
Hello, a comment, when I set up a user with partial rights, this can not make backspace on the keyboard and can not shift + home for a text select.

Thank you

**Comment by Ylianst** [comment]
Can you provide a screen shot of the rights and the place where backspace does not work? - Thanks.

**Comment by Ylianst** [comment]
Pretty sure this issue has been solved many versions ago. I will close it, but feel free to reopen if needed.
