### ISSUE TITLE
Errors in Install manual

### ISSUE THREAD

**Issue by hellofaduck** [Ylianst/MeshCentral#1372]
I found that commands in "6.8 Increased Security Installation" section are not working.
I can make it work after i changed:
`sudo chmod –R 755 /opt/meshcentral/meshcentral-*`
to
`sudo chmod 755 -R /opt/meshcentral/meshcentral-*`
After that there is no errors after runing this command and all others command with chmod.
Hope this helps someone

**Comment by Ylianst** [comment]
Thanks for the report. Just updated the [Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf). Let me know if it looks ok.

**Comment by hellofaduck** [comment]
Ctrl-F not found wrong commands :) Looks good for now!
