### ISSUE TITLE
Strange problem with Let's Encrypt ACME module

### ISSUE THREAD

**Issue by hellofaduck** [Ylianst/MeshCentral#1373]
Our network scheme:
WAN -> 3000(https ) -------N-----3000----> Mesh
WAN-> 80(redir_to_3000) --A-------80----> Central
WAN ---------------------> T --------------> Server

MeshCentral works fine LAN and WAN agents working flawlessly, but when i try to get staging certificate it not working.
Its more intriguingly that  letsdebug.net says me thats all working fine, but in mesh at same time i see this
![изображение](https://user-images.githubusercontent.com/49034105/82199883-f8213200-9906-11ea-8d35-8c179c10e8c5.png)

In what direction i need to digg?
I doublecheck my local ufw firewall, even try to disable completly.

**Comment by Ylianst** [comment]
In looking at your network scheme, are you redirecting external port 80 to internal port 3000? Right now, MeshCentral does not expect challenges to be directly at the "HTTPS" port. One thing you can do is enable both "cert" and "webrequest" tracing. This way you see all HTTP requests.

![image](https://user-images.githubusercontent.com/1319013/82257933-c2337c00-990d-11ea-95d0-bf6dbfa9c957.png)

The other thing to note is that Let's Encrypt will check that your email address is somewhat valid. This is not something letsdebugnet will look at.

**Comment by hellofaduck** [comment]
Tracing with web-requests during letsdebug testing
![изображение](https://user-images.githubusercontent.com/49034105/82290756-4d654e00-99b0-11ea-9f99-376b54e0218d.png)

Ok, if my current network scheme cant work by design, and what is right scheme?
I have ~250 current agents working on 3000 port, what i need to enable to get challange work? Expose additionaly 443 port from my Mesh Server to the WAN?
Thanks for fast answer!

**Comment by uldiseihenbergs** [comment]
as far as i know, LE is doing it's challenges on port 80.

**Comment by hellofaduck** [comment]
May be i draw not very simple to understand scheme.
We have 1:1 NAT, 80 and 3000 port on WAN address corresponds to 80 and 3000 port on LAN address of MC. 80 port is redirect port to 3000, yes, we have non standard https port 3000, but in User Manual of MC in section about Let's Encrypt i dont found any restrictions about using non standard port, besides we have 80 port redirecting to our working and active 3000 port with web server. Only strict requirement i found in manual is open 80 port on WAN, if i am read manual wrong  switch me to right rails :)

**Comment by Ylianst** [comment]
So, you correct that Let's Encrypt should only need the WAN port 80 to be directed to the MeshCentral HTTP "Redir" server that is normally on port 80.

So you have:

```
TCP 3000 ---> MeshCentral HTTPS 3000 ("port":3000 in config.json)
TCP 80 ---> MeshCentral HTTP 80 ("redirport":80 in config.json).
```

I have never tried it, but it should work. The fact that your not getting any challenge requests from Let's Encrypt could be a few things.

First, please do this with `"production": false` in the Let's Encrypt section of config.json. If you try too many times, especially with production set to true, they will ban you for some time. So be careful.

Second, check the email address you put in the "letsencrypt" section on config.json. It has to be accurate. Let's Encrypt does some effort to make sure that email address looks right. If there are invalid spaces, characters or it looks like a dummy email, they will fail.

Also, (and this may sound basic, apologies, but I had to say this all the time) make sure the DNS name or names you are requesting are correctly registered with a DNS provider and work worldwide. Let's Encrypt will try to resolve the name from different servers and will perform the challenge from different places in the world.

On a bit of a separate note, I usually don't recommend running MeshCentral on a non-443 port if you can avoid it, there are plenty of HTTP proxies and networks that will block outbound HTTP connections except for port 80 and 443. Ideally, you want to use a reverse proxy. However, this setup should still work.

**Comment by si458** [comment]
by default meshcentral will do a selfcheck to see if it can renew the certificate and can sometimes fail due to proxys/firewalls/etc...
so you can simply skip this behaviour now by setting `skipChallengeVerification: true` inside of `letsEncrypt` in `config.json`
![image](https://github.com/Ylianst/MeshCentral/assets/765314/86dc30ff-cf03-43ec-8649-8fddb47e2eb8)
