### ISSUE TITLE
Clear My User Recordings logs?

### ISSUE THREAD

**Issue by black3dynamite** [Ylianst/MeshCentral#1374]
How can I clear the **My User Recordings** logs?

![image](https://user-images.githubusercontent.com/22382399/82270713-efdeec00-9932-11ea-9f9c-9b5bc360c477.png)

**Comment by Ylianst** [comment]
Hi. There is no way to clear these logs yet, they are log events that will be automatically removed after 20 days, but you can change the configuration of this settings section of config.json:

```
    "DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    }
```

This is the number of seconds to keep the events in the event logs. Hope that helps.

**Comment by black3dynamite** [comment]
Thanks!

**Comment by DaanSelen** [comment]
Is this now supported to specifically clear recordings log?

**Comment by si458** [comment]
> Is this now supported to specifically clear recordings log?

please see comment above, the is no manual way to do it, you have to set values inside of your `config.json` and this will do it automatically for you
https://github.com/Ylianst/MeshCentral/issues/1374#issuecomment-631662252

**Comment by DaanSelen** [comment]
> > Is this now supported to specifically clear recordings log?
> 
> please see comment above, the is no manual way to do it, you have to set values inside of your `config.json` and this will do it automatically for you [#1374 (comment)](https://github.com/Ylianst/MeshCentral/issues/1374#issuecomment-631662252)

This will do all logging events, I assume?
