### ISSUE TITLE
"My Files" don't work as expected

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#138]
Hi,
I'm trying to use "My Files" folders to share documents to operators. Every group folder must have their own files.

I'm working with primary admin user while uploading, but when I try a "create folder" (in every group folder), when I click OK to confirm, I receive a message "Server Disconnect" and page is not accessible for a while, seems a restart.
Same story if I upload a file (correctly) and I try to delete it (checkbox then delete) I got the "server disconnects" again

Could be a wrong permission setup ?
Server is on a Win serv 2016 with domain admin rights
Thanks in Advance

Merlinweb

**Comment by Ylianst** [comment]
As administrator, can you got to the "My Server" tab, click on "Show server error log" and post any exceptions reported? - Thanks.

**Comment by Ylianst** [comment]
Never mind - Just published MeshCentral v0.3.0-r with a fix for this. Good find, thanks for reporting this. Let me know if the fix works.

**Comment by merlinweb** [comment]
OK Ylianst, now Uploading and erasing are working as expected, thanks a lot!
Only a little consideration:
I see files on server are in the path C:\Program Files\Open Source\MeshCentral\meshcentral-files\domain
Do you think could be useful to insert another parameter in configuration file to set the path of  meshcentral-files\domain ?
In my servers, I always split Os and data in several logical unit (C:, D: etc), to prevent system halting due to disk full. 
It's only an idea, thanks for all, you are an amazing team

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Thanks for the report. Also, you can put "filespath" in the settings section of config.json to set the path of the entire "meshcentral-files" folder. Let me know if that works for you.

`"filespath":"c:\\temp"`

**Comment by merlinweb** [comment]
Hi Ylianst,
I've created a new logical disk in my VM:  E:\
In config.json added a line in setting section (last Line) as follow:
"filespath":"e:\\Servnet_Files" (folder where I want to store my user and group files)
Restarting meshcentral service, but it don't keep alive, switching off after a couple of seconds

I've done something wrong ? I've noticed if I put some misconfiguration in json result is the same, service go down...

thanks
Merlinweb

**Comment by Ylianst** [comment]
Can you go in "meshcentral-data" and send back what is in "meshserrors.txt"? I am guessing the server faulted. - Thanks.

**Comment by merlinweb** [comment]
Sorry, but I can't find any file named mesherrors.txt in meshcentral-data folder...
![image](https://user-images.githubusercontent.com/48550288/54783370-7c075d80-4c21-11e9-9dcb-029962e5aef6.png)

**Comment by merlinweb** [comment]
any info on this ?
At the moment there is no way to get functional following config:
`"filespath":"e:\\Servnet_Files"`

Would be great for better file management in server

Thanks for support

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Yes. I will work on it tomorrow when I get in the office. I can't imagine this will be a difficult fix.

**Comment by Ylianst** [comment]
I just went to work and took a look at this. I tried `"filespath":"c:\\Servnet_Files"` on my computer at everything worked perfectly. The folder is auto-created if it does not exists and files are correctly placed into it. I see you probably used the MeshCentral Windows Installer. I you can:

- Stop the MeshCentral service
- Add "filespath":"e:\\Servnet_Files" back into the config.json
- Optionally, cut & paste the entire config.json into https://jsonlint.com and hit validate to make sure the file is correctly formatted.
- Go in the command prompt as administrator.
- type "cd C:\Program Files\Open Source\MeshCentral"
- type "node node_modules\meshcentral"

This will start the server in manual mode. Make the server crash or reset and cut & paste the you see back. I will fix any issues you see right away.

Hope it helps,
Ylian

**Comment by merlinweb** [comment]
Thanks a lot Ylianst, 
solved using https://jsonlint.com/ (I'll keep using it in the future)
A stupid mistake in my json (forgotten comma)
Very sorry for time wasted and thanks for support
Folder change works like a charm

Cheers

Merlinweb

**Comment by merlinweb** [comment]
not an Issue, my fault
