### ISSUE TITLE
QuickShare feature/right ?

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1380]
Hi,

Thanks to meshcentral (and meshcentral developers ultra fast request response time :) we've been able at our university to offer remote access to computers inside our universty to our students and teachers (at home because of COVID19), and the first courses were successful in the past few days.

We have a server script (service) which thanks to meshctrl features detects when a student or teacher logs in and runs AddUserToDevice on a free school computer and so the user has one computer in "My Devices" to work with.

We give to teachers and students "Control (No Terminal, No Files, No AMT), Limit Events, Chat" = "--remotecontrol","--noterminal","--nofiles","--noamt","--limitedevents","--chatnotify".

We were asked to add a feature so that teacher can access student remotely controlled computers, and also that students can share the remotely controlled computers between them so they can be two or three on one computer like they do when they're physically inside the university.

To be able to do this we hacked quickly something using the "Log Event" device feature and asking our user to enter "share:with:LOGIN" in there so our script can know about the sharing request and then run the needed AddUserToDevice. 

It works but it's not "nicely" integrated into meshcentral UI.

If you think this feature could be useful (mainly to universities in this time of COVID19) may be it could take the form of an additional right "quickshare" given to the user on the device (when first added with AddUserToDevice) and that allows the user to share with other meshcentral users the rights he currently has on the device, with less or same rights that he has. To simplify the UI for teacher and student may be just offer "remote view only" yes/no to filter the rights. May be minus the quickshare right automatically to avoid transitive propagation of the right. When the quickshare right is given it should automatically be removed when the original quicksharing user loses the right to the device (logout, inactivity, or eg our script calls RemoveUserFromDevice at the end of the course).

I hope I explained not too badly our use case, let us know what you think.

Thanks again for meshcentral!

**Comment by olberger** [comment]
It would be interesting to be able to share a session with a coworker or professor, possibly from a GUI button/menu.

How hard would it be to develop such an add-on/plugin ?

**Comment by guerby** [comment]
@Ylianst I've tested the new "Share" feature and it's really nice!

https://meshcentral2.blogspot.com/2020/08/meshcentral-desktop-sharing-fido-pin.html

To help our teaching use case we would need a slight variation : share for a limited time (in minute since classroom duration will vary a lot by institution and type of lecture) with a user who has an account (so enter login name) and the machine with current user rights.

So when a student shares to his/her teacher, the teacher gets the machine in his view and can do multi desktop view of all students desktop on his meshcentral session.

Another use case is with so called hybrid classroom where part of the students are in the school and some other students are at home : one student on site can give his machine right to the other student of site through meshcentral (since the other student has a login on meshcentral).

Thanks again!
