### ISSUE TITLE
Questions: docker, user perms on agents

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#1384]
Hello there, I have two questions for the team:

1) Is there a recommended docker image at docker hub (or elsewhere) for running meshcentral, and are there problems with running in a container?

2) Is there ever any intention of assigning user permissions at the agent level, or will the device group level stay as the most specific level?

Thanks for all you do!

**Comment by ryanblenis** [comment]
1. See [here](https://github.com/Ylianst/MeshCentral/issues/22)
2. You can already assign permissions at the node level (look at the bottom of the _General_ tab within each node).

**Comment by Ylianst** [comment]
Ok, I think Ryan just took care of this one. @edlins, please close if solved. Providing an official MeshCentral docker image has been an ask for a long time, I have no idea when I will get to it. So much work to do.

**Comment by edlins** [comment]
1. Thanks for the link!  Didn't see that in my search..

2. Hmm, I don't see this, maybe I'm looking in the wrong place.  At the bottom of `General` I see `Interfaces`, `Location`, `Router`, `Putty`, `WinSCP`, `Change Group`, and `Delete Device`, but nothing regarding permissions.

**Comment by ryanblenis** [comment]
What version of MeshCentral are you running?

**Comment by edlins** [comment]
0.4.9-k.  Is this a newer feature?  It shows 0.5.37 available.

**Comment by ryanblenis** [comment]
Yes, I believe it was introduced in the late 0.4.9 series. Highly recommend updating!

**Comment by Ylianst** [comment]
Right, per-device user permissions was recently added (it was a LOT of work).

**Comment by edlins** [comment]
Upgraded and confirmed!  I do see now when I check the version that it indicates a "latest" version and a "stable" version, and I'm now on "latest" (0.5.37).  Next time I upgrade, can I indicate that I only want the "stable" version?  And, what's the difference?

**Comment by ryanblenis** [comment]
Currently the "stable" version is arbitrarily chosen from one of the "latest" versions. It's subject to bugs (as there are no fixes actually backported into the stable version yet), so until that happens I personally feel that the "stable" branch is no better than the "latest", other than longer periods of time in between updates. Depending on the actual release that is chosen that could be both good and bad. In which case you may miss newly introduced bugs, but also newly introduced features in addition to bug _fixes_.

Also, don't forget to close this issue if everything is resolved here for you.

**Comment by edlins** [comment]
Great, thank you so much for the assistance!
