### ISSUE TITLE
Question: Filtering computers / devices by IP addresses

### ISSUE THREAD

**Issue by orion88-admin** [Ylianst/MeshCentral#1385]
Hello
I am currently implementing meshcentral 2 software at the company I work with.
I have already added a large number of computers to manage through meshcentral, currently I have over 150 hosts and that's not all. And I have a question, is it possible to add the search functions of computers / devices by IP addresses?
Of course, I mean the tab my devices.
![filter_by_ip_adress](https://user-images.githubusercontent.com/65662158/82568556-4b9db500-9b7f-11ea-98fc-9da09c43498a.JPG)
I think it would be useful.

Best Regards

**Comment by vitko-bg** [comment]
You can try to use Tags.
Just one of the tags to be IP or IP class of the devise

**Comment by Ylianst** [comment]
In the filter box, type `ip:1.2.3.4` to filter by IP address. You can also type `user:username` or `u:username` to filter by logged in user. This is available now.

![image](https://user-images.githubusercontent.com/1319013/82603020-ca3a2880-9b66-11ea-9b3f-9b020123ebd9.png)

**Comment by vitko-bg** [comment]
> In the filter box, type ip:1.2.3.4 to filter by IP address. You can also type user:username or u:username to filter by logged in user. This is available now. Let me know if this works.

That is a good one :) Thanks you! Did not know about this options .....

**Comment by orion88-admin** [comment]
It works very well.
Thank you
