### ISSUE TITLE
Console Error on Mac

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1386]
This is fairly low priority since it doesn't seem to be affecting functionality and is only happening on one (older) Mac but it's still worth pointing out. I've seen this error mentioned in a couple of other issues but they were for specific problems so I thought creating a new one would be best.

I'm seeing the following console error coming only from an old Mac mini running High Sierra (10.13.6 - unfortunately the last supported version for that machine):

`uncaughtException1: Error: timers.onElapsed() callback handler on 'sendNetworkUpdate()'  => TypeError: cannot read property 'toString' of undefined`

I'm not sure what actually triggers it as I just tried connecting and disconnecting a couple of times and don't more of them coming up but when I first looked today, I saw it 6 or 7 times and now there's 11 so something is definitely going on.

**Comment by Ylianst** [comment]
Note for Bryan, I suspect this code in meshcore.js:

```
// Update the network interfaces information data
var netInfo = mesh.NetInfo;
if (netInfo) {
    netInfo.action = 'netinfo';
    var netInfoStr = JSON.stringify(netInfo);
    if ((force == true) || (clearGatewayMac(netInfoStr) != clearGatewayMac(lastNetworkInfo))) { mesh.SendCommand(netInfo); lastNetworkInfo = netInfoStr; }
}
```

Every 20 minutes, the MeshAgent will check if the OS network interfaces has changed. If they did change, it sends an update to the server. It looks like 'mesh.Netinfo' may be incorrect on macOS?

**Comment by PetieM** [comment]
For reference, I do not get this error for my Catalina MacBook Pro so it may just be that something has changed in the last couple of versions of macOS.

**Comment by trenton92** [comment]
I had this error on Mojave
