### ISSUE TITLE
OS Name field

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1388]
Lately I was wondering: there's a specific reason why OS name field - which reports hostname indeed - has been named that way?

Moreover: why isn't being displayed in linux clients?

Thanks!

**Comment by Ylianst** [comment]
That is a good question and there is a bit of history behind this. Devices have 3 "names":

**The server side name** - This starts out has being the same as the operating system name, but the administrator on the server can change it to anything you like.
**The OS name** - This is the name in the operating system. This can be changed over time and the agent will update the server as needed. If the server name and OS name are the same, currently this is not displayed in the "General" tab. This name is generally not a fully qualified domain name (FQDN) so it's going to be "bob-laptop" or something.
**HostName** - In some cases, MeshCentral may have this extra name. This is usually for cases where MeshCentral needs to connect to the remote computer, for example for agent-less Intel AMT operations. In that case, this will contain the FQDN to use to connect to the device. It can be an IP address or "bob-laptop.mydomain.com".

So yes, if the server name and OS name are the same, it will not be displayed. You can click on a device name and change it, the OS name will show up immediately.

Hope that helps,
Ylian

**Comment by amenolo** [comment]
> If the server name and OS name are the same, currently this is not displayed in the "General" tab

Never noticed until now, I swear :open_mouth:

Anyway your explanation has been very appreciated, I'm going to close this one.
