### ISSUE TITLE
A terminal errors

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1389]
The more you use your program, the more you admire it.
Thank you for making a good program.

One problem appears when using the terminal.
Not always, but sometimes problems appear.
I am using the Korean version.

1. Connect to the terminal (My client is Windows 10 x64 2004, build 19041.264)

2. Move file tap

3. Download any file

4. Return to terminal tap

Then the screen is broken, like below :
![image](https://user-images.githubusercontent.com/46802819/82637147-23758b00-9c3f-11ea-8d1f-d69e3fe317e5.png)

**Comment by Ylianst** [comment]
Hi. What browser are you using? -Thanks.

**Comment by Ylianst** [comment]
Ok! I see the problem in Chrome, but not in FireFox.

**Comment by Ylianst** [comment]
I just fixed it, it will be in MeshCentral v0.5.38. I also made it so the terminal gets focus when you enter the terminal tab, so you can start typing right away.

**Comment by eu4you** [comment]
Thank you much!

**Comment by Ylianst** [comment]
If it is fixed, you can close the issue. I think it this one if fixed, but please re-open if needed.
