### ISSUE TITLE
Terminal Ctrl-C

### ISSUE THREAD

**Issue by VelosityElectroincs** [Ylianst/MeshCentral#139]
In terminal on a Win 7 Pro client, when I do a ping -t, neither the Ctl-C in the bottom left or the Ctrl-C send in the bottom right seem to send the Ctrl-C to stop the ping to the terminal.

**Comment by Ylianst** [comment]
Thanks for the report. Indeed, I just checked and this is a problem. I will check with Bryan when he is back from vacation for a fix on this.

**Comment by sorvani** [comment]
possible related.
https://github.com/Ylianst/MeshCentral/issues/123

**Comment by krayon007** [comment]
This is a limitation of how the windows console object captures and propagates signals. In order to fix this I need to rewrite terminal on windows to instantiate a pseudo terminal instead a console. This will take a little bit of time...

Bryan

**Comment by Ylianst** [comment]
Going to close this one as the terminal code has been re-written and does support CTRL-C, but only on Windows 10. This can't be fixed on older windows.
