### ISSUE TITLE
Suggestion for file download

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1390]
And when downloading files, are the following features possible?

1. Download multiple files

2. Folder Download

I am using Qnap NAS. when downloading multiple files or folders from the web, they are bundled and downloaded as a zip file.

I don't know about programming languages, but I think there are many similar sources, so I was googling one and link it. I hope it helps a little.

https://stackoverflow.com/questions/1754352/download-multiple-files-as-a-zip-file-using-php

3. File transfer speed and time remaining

4. When downloading / uploading files, the background task is allowed and the task status confirmation window. This is for heavy files.

5. Similar to the My files item, copy / paste is performed for each device to other device, not download or upload to the current device.

If these features could be added, I think it would be much easier to manage the device with MeshCentral.

**Comment by ryanblenis** [comment]
Dupes on multiple files/folder downloading: #782, #525, #503, #323, #50.

**Comment by dinger1986** [comment]
duplciates can be closed @si458
