### ISSUE TITLE
Regarding SSL Certificates installation 

### ISSUE THREAD

**Issue by yogesh2312-more** [Ylianst/MeshCentral#1391]
Hello Ylianst

As i am trying to installing SSL certificate for WEB server on  my own deployed server for meshcentral in WAN mode but i am failed to get secure connection.

Can you please suggest me on this for taking right action?

**Comment by eu4you** [comment]
Have you tried registering the file as shown on page 5 of the manual file and giving the cert option on page 7? I am doing https fine with those two tasks.

**Comment by yogesh2312-more** [comment]
as per page 5 and 7 i have define setting in config.json and also added certificates inside meshcentral-data folder but may i know is there need to define certificates path or name inside config.json file?

**Comment by Ylianst** [comment]
If you have an existing certificate, start by placing the DNS name of your server in the settings "cert" value. Even if you don't use the MeshCentral certificate, this will help to tell MeshCentral what DNS name you want to use.

```
{
  "settings": {
    "Cert": "myserver.mydomain.com",   <-----------
    "WANonly": true,
    "Port": 443,
    "RedirPort": 80
  }
}
```

Then, in "meshcentral-data", you replace the two following files to put your certificate:

```
webserver-cert-public
webserver-cert-private.key
```

These two files are text file, so you can use a text editor to cut & paste your certificate. Each file has a header and footer like "-----BEGIN CERTIFICATE-----" and that should stay the same.

Once you make these changes, you can restart the MeshCentral server and it should work.
