### ISSUE TITLE
Mobile view suggestion: filter box

### ISSUE THREAD

**Issue by PTR-inc** [Ylianst/MeshCentral#1394]
I regularly use the mobile view on my iphone to quick check the status of pc's. With over a hundred pc's the list is long and needs to be scrolled through from the top. It would be really useful if the filter box from the desktop app is available in the mobile view.

**Comment by Ylianst** [comment]
Just added it, it will be in MeshCentral v0.5.40 when it's next published.

![MC2-MobileFilterbar](https://user-images.githubusercontent.com/1319013/82718612-54ae8500-9c58-11ea-8c45-32d8cb853a4d.png)

**Comment by PTR-inc** [comment]
Very nice, thanks!

**Comment by Ylianst** [comment]
Just published v0.5.40, I also added the device details page.

![MC2-MobileFilterDetails](https://user-images.githubusercontent.com/1319013/82740022-b410a180-9cf9-11ea-90fd-8225cc3b6b4b.png)

**Comment by PTR-inc** [comment]
Works like a charm!
