### ISSUE TITLE
AgentPort not working with latest Windows agent

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1396]
So, after a latest updates, it looks like new Agents are not connecting to AgenPort, but on Port.
i have the following config:
```
   "Port": 8443,
    "AgentPort": 443,
    "RedirPort": 80,
```
when i downloaded fresh Windows Agent, i see this, it must connect on 443 instead of 8443.
![image](https://user-images.githubusercontent.com/60253253/82683579-ea96df80-9c59-11ea-9e46-f60a5a889ade.png)

when i manually edit msh file to port 443, it connects to MC and is working just fine.
i'm on MC 0.5.38.

**Comment by Ylianst** [comment]
Looking at the code, I don't think this behavior has changed in the latest version. Agents always connected to the main HTTPS port unless told otherwise, even if a agent-only port was enabled. You can indicate what port the agents need to connect to using:

```
"AgentAliasPort": 443,
```

However, I just changed the behavior so that if an agent-only port exists, it will use that. This will be in the next version.

**Comment by uldiseihenbergs** [comment]
Thanks for quick update, i think i was upgraded from v0.5.28.
i will test next version, and let you know hot it works.

**Comment by Ylianst** [comment]
You can use the `"AgentAliasPort": 443` right now, no need to wait for the next version.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.39 with a fix for this. Let me know if it works.

**Comment by uldiseihenbergs** [comment]
something wrong here - i simply updated to 0.5.39, and no agents comes back after update. then i tried to run one agent manually to see what is happening, and got these errors in MeshAgent.log
```
[2020-05-23 08:50:06 AM] FATAL EXCEPTION [MeshAgent_91FBC0ECD6524754.exe] @ [FuncAddr: 0x00007ff64fc03a4d / BaseAddr: 0x00007ff64fc2f608 / Delta: 179131]

[2020-05-23 08:53:13 AM] Certificate loaded from DB was not signed by our root cert in the Cert Store
```
then back to 0.5.38, all agents comes back immediately.

**Comment by uldiseihenbergs** [comment]
looks like it's related to #1395 ? i'm behind Apache reverse proxy.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.41 to fix the agent port. However, the error your reporting seems to be something else on the agent. Bryan would want to look at this.

**Comment by Ylianst** [comment]
FYI. "AgentPort" was broken in v0.5.39 and v0.5.40. So, using 38 or 41 should work for you.

**Comment by uldiseihenbergs** [comment]
still weird - updated to .41, and some Agents comes up, but very slowly - i have a very small environment with about 10 agents, 4 of them comes up with .41 (1 Linux, three Windows), back to .38 and all agents are back in few seconds.

**Comment by Ylianst** [comment]
Ok, I am going to re-test the agent port again. Can you confirm that all your agents connect to the agent-only port?

**Comment by uldiseihenbergs** [comment]
Yes, in my setup all agents are connecting to AgenPort.

**Comment by Ylianst** [comment]
I am going to need some help fixing this. I just tested my server by putting the HTTPS port on 444 and placing the agent-only port on 443. Both with TLS enabled and all agents connected immediately.

If you ever get a chance, install the latest MeshCentral in a separate folder, copy your "meshcentral-data" over, stop the old server and start the new one manually with `--debug agent,web,webrequest`. You should see something like this:

![image](https://user-images.githubusercontent.com/1319013/82762998-34e2a280-9db9-11ea-921c-9d54dc080f6e.png)

I would be interested to see if there are anything interesting that shows up in your case. Also make sure that when you try to access to agent-only port from outside, you get a "Cannot GET /" response.

![image](https://user-images.githubusercontent.com/1319013/82763038-73785d00-9db9-11ea-9513-bb75c3c46a5a.png)

Any hint at all as to what is going on would be appreciated.

**Comment by uldiseihenbergs** [comment]
huh, i got one idea, but cannot prove. i have an Apache reverse proxy, and with AgentDNS virtual host i'm forwarding only wss protocol. With 0.5.38 it works just fine - something changed after this version?
my Apache conf bellow:
```
<VirtualHost *:443>
    ServerName mesh.example.com
    DocumentRoot /var/www/meshcentral

    SSLCertificateFile    /etc/letsencrypt/live/mesh.example.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mesh.example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/mesh.example.com/chain.pem

    SSLEngine on
    SSLProxyEngine On

    SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    SSLHonorCipherOrder on

    RemoteIPHeader X-Forwarded-For
    RemoteIPInternalProxy 127.0.0.0/8

    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule . "wss://192.168.111.222:433%{REQUEST_URI}" [P]

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

```
when i browse this from outside, i get - and that's fine.
![image](https://user-images.githubusercontent.com/60253253/82788305-e1339000-9e70-11ea-871e-93a88445dba6.png)

**Comment by uldiseihenbergs** [comment]
i just did a full test as requested with 0.5.44(with both ports allowed full MC access from outside)
on console i see nothing wrong, but lot of messages like this, and going to repeat:
```
WEBREQUEST: (192.168.50.254) /agent.ashx/.websocket
AGENT: New agent at 192.168.50.254:34416
WEBREQUEST: (192.168.50.254) /agent.ashx/.websocket
AGENT: New agent at 192.168.50.254:34490
WEBREQUEST: (192.168.50.254) /agent.ashx/.websocket
AGENT: New agent at 192.168.50.254:34490
WEBREQUEST: (192.168.50.254) /agent.ashx/.websocket
AGENT: New agent at 192.168.50.254:35264
WEBREQUEST: (192.168.50.254) /agent.ashx/.websocket
AGENT: New agent at 192.168.50.254:35264
```
and when browsing to agent-port only website, full MC login page opens - thats wrong..

according to agents - after some more minutes waiting, one Agent appeared in MC, and i see in console:
`AGENT: Verified agent connection to xxxxxxxxxxxxxxxxxx (192.168.50.254:36636).`
previous messages going to repeat over and over.

**Comment by Ylianst** [comment]
Hi. So, sadly, I don't have sufficient information to debug anything. It's not clear if the agents are showing up on the console or not, are the repeat message different agents or the same agent? Etc.

If you want to clone your server, create a test setup and send me the [credentials directly, you can use my PGP key if you like](https://www.meshcommander.com/contact-information), I will login and debug the problem. I can use my own agent and you don't need a real DNS name or real TLS certificate for the test setup. This said, I don't think I can help otherwise, there are just too many factors.

**Comment by uldiseihenbergs** [comment]
huh, i just did a bunch of other tests:
1. created a second environment for testing purposes with configuration max similar to prod environment. and for sure - it worked as expected - when i added new agents, all comes in immediately. 
2. so next i moved all meshcentral-data folder from prod to new environment, and reconfigured my Apache reverse proxy to new environment and voila - agents slowly one by one but all came up.

so. differences: old prod environment is running on docker container, while new environment is a fresh Ubuntu 18.04 server(it is running in LXC container now).

@Ylianst are you changed some dependent components after version 0.5.38? this is the only reason IMHO why just updating old prod environment won't work..
and about a docker you have unanswered question in other thread... and i just hope, i can run it in Docker again - it uses much less resources than a dedicated VM or LXC container.

**Comment by Ylianst** [comment]
This is super weird, I am not sure what is going on in your case, I can't imagine it's Docker related. Note that if you ever want, you can also do this:

```
systemctl stop meshcentral
mv node_modules node_modules_backup
npn install meshcentral
node node_modules/meshcentral
(wait a bit for all extra modules to install)
[ctrl-c]
systemctl start meshcentral
```

That is, you can at anytime just re-install MeshCentral from nothing and run it again. This could be useful if you installed MeshCentral a long time ago and some of the dependency modules are really old. This way, you get a "fresh install" in a few minutes. If anything goes wrong, you can move the "node_modules_backup" back and launch again.

**Comment by uldiseihenbergs** [comment]
Thanks for your help, i will try when i have more time, and will report back.
node and npm version is much newer on old prod environment already than on my test environment with fresh Ubuntu install. Does npm and node versions make some impact on MC?

**Comment by Ylianst** [comment]
As long as you have NodeJS 8.x and higher, it should not make any difference. Note that NodeJS v13 and higher support TLS 1.3 and so, you may get a small speed and security benefit since a lot of TLS is used for Browser and Agent connections. If you use a reverse proxy to perform TLS, then there is no impact from NodeJS support of TLS 1.3.

**Comment by uldiseihenbergs** [comment]
ok, just did a view steps further:
1. i tried above suggestions about reinstall MC inside Docker, but it didn't help.
2. i tried another Docker image from bsmout/meshcentral, didn't help either.
3. i decided to build my own Docker image with node version 8.10 as in original Ubuntu 18.04 server. I never built Docker images before, it was a bit challenge to me, but learned something new :) first i built new Docker image with MC 0.5.38 and tested - worked as expected. then i built MC 0.5.45 and voila - works as expected.
So, looks like there are some incompatibilities with never node versions and Docker. Because all other Docker images i tried, was built with latest node versions.
BTW, my build images are here: https://hub.docker.com/r/uldiseihenbergs/meshcentral/tags
images are based on node:8.10-slim.
So, i'm not sure how to proceed next. my prod environment is running on Docker-18.06.1-ce.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
