### ISSUE TITLE
Remote Desktop Settings don't hold their values

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#140]
When I jump around browsers and different computers I noticed I have to go though and set my Remote Desktop Settings again (Quality %, Scaling % and Framerate as well select Desktops view instead of lists view. and my sort by settings. Im guessing this is because meshcentral saves these settings in HTML5 cache or a cookie. It would be awesome if these settings were saved on the server side per user. Maybe set a global settings and per user setting user settings should override the global.

**Comment by Ylianst** [comment]
Correct, right now the settings are saves in the browser store. Having a server-side user settings bucket is a good idea.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.3-k with a fix for this. Many settings are now stored server-side, some settings are are even real-time. For example, if you change the web page UI mode (little diamond icon on the upper right), all you browser sessions will switch to the new mode. Feedback appreciated.

**Comment by johnnyq** [comment]
You are the best!! Thanks @Ylianst everything works great now, keep the going going, your doing a great job on this project and appreciate all the work you put into this project..

**Comment by Ylianst** [comment]
Thanks and thank you for suggesting this. I am going to close this issue, feel free to file another if anything does not work right.
