### ISSUE TITLE
Share desktop with external partners

### ISSUE THREAD

**Issue by FelR** [Ylianst/MeshCentral#1401]
Sometimes external partners need to connect to a desktop of a local machine for support. I know two authenticated users can view/access a desktop at the same time. But in our case we use LDAP authentication for internal users, so external partners cannot simply register for a user account and instead I'd have to add an LDAP account for them which is not feasible. A possible solution would be an option to create a one-time/time limited access link for the machine that does not require authentication or just a simple password you can send along the link to the external partner (just like the dropbox share link for single files).

Anyway thank you for this great piece of software and keep up the good work.

**Comment by guerby** [comment]
LDAP is currently exclusive with local accounts. Many web software offer a choice of authentification provider at the login screen with a choice of "LDAP account" vs "Local account", may be that's a solution to consider for this issue as well.

**Comment by si458** [comment]
you should be able to use the 'share' feature now
https://meshcentral2.blogspot.com/2020/08/meshcentral-desktop-sharing-fido-pin.html
