### ISSUE TITLE
sample-config-advanced.json is missing

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1402]
I've been comparing my config file to the sample to make sure I'm not missing any new options but as of the last few versions, the default sample-config.json has a very barebones configuration displayed and refers to node_modules/meshcentral/sample-config-advance.json which does not appear to be present, at least on my system (CentOS 8).

**Comment by MordyT** [comment]
Here:
https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json

**Comment by Ylianst** [comment]
Oh, your right. The new "sample-config-advanced.json" is not in the NPM package. I was just about to publish v0.5.42, so I am fixing it now.

**Comment by Ylianst** [comment]
MeshCentral v0.5.42 is published with the fix for this.
