### ISSUE TITLE
Feature Request - Update MeshCentral DNS / IP remotely in agent config

### ISSUE THREAD

**Issue by davscot** [Ylianst/MeshCentral#1403]
Hi Ylianst / community,

Unless this feature already exists, I'd like to be able to update the MeshCentral hostname / IP (if hardcoded) on the remote agent without re-installing the agent.

Ideally it would be great to be able to do this in bulk for any major changes which require IP change (not recommended of course to hardcode this) or in my case the MeshCentral DNS address which agents currently point to.

Since introduction of AgentAliasDNS in the config file I'd like to update all existing agents to use my new agent hostname. I know I can create CNAME records and point the old DNS record to the new, however to keep things tidy it would be nice to remove old records no longer needed.

It would also be beneficial to be able to change the port in which the agent connects back to (just in case this also requires changing).

Happy for your feedback on this, of course these sort of remote changes could be dangerous if done incorrectly. Could put a timer on to revert changes after 5min if not committed...?

David.

**Comment by uldiseihenbergs** [comment]
you can change it manually now - look for MeshAgent.msh file (on Program files\Mesh agent, if on windows) - it's a text file.

**Comment by davscot** [comment]
@uldiseihenbergs 

Thanks appreciate your help, I will look at this in the meantime for any computers I remote into. Is this documented somewhere for my future reference or did you come across this?

Of course it would be nice to have this built into the server side of MeshCentral which allows bulk update of agents as it would take forever to manually update if one has many devices (assuming this is done on the agent side).

David.

**Comment by uldiseihenbergs** [comment]
i'm not sure about documentation, but it should work. and i agree, that it would be nice to migrate all agents to other site by few clicks :)

**Comment by ryanblenis** [comment]
Out of curiosity, what is the use case for moving an agent from one server to another?

**Comment by uldiseihenbergs** [comment]
i think, it's about new config item discovered: `AgentAliasDNS`. i din't know such exists and it's very well idea to move agents to different DNS to secure MC webUI - if someone at agent side looked at msh file, then it can start to tinker your site. if MC main web is on different DNS, then you have additional piece of security. i just hope this dns can be some different, for example mesh.example.com for main site, and agents.mesh.com for agent connection..

**Comment by openmoto** [comment]
@davscot, this seems like a one off thing?

I would reccomend using @ryanblenis [Meschentral-ScripTask](https://github.com/ryanblenis/MeshCentral-ScriptTask) instead and run a script like below on the machines.
`$output = "$PSScriptRoot\meshagent.exe"`
`(New-Object System.Net.WebClient).DownloadFile("http://yourwebsrever/path.meshagent.exe", "C\Setup\meshagent.exe")`
`C\Setup\meshagent.exe --fullinstall`

Haven't tested this but it's the general way I script download and install using powershell + script task.

**Comment by davscot** [comment]
@ryanblenis Specifically in my case it's to update agents to use a new agent specific DNS record on an existing MeshCentral deployment (using AgentAliasDNS in MeshCentral config) . 

Use case #2 existing setup - If one were to still use the existing MeshCentral DNS record for WEB UI (currently shared with WEBUI and agents) they wouldn't be able to setup a CNAME record to point to agent specific record as a workaround. Hence the need to update all agents to use a new DNS record.. 

@uldiseihenbergs Correct I've setup a new DNS record specifically for agents to connect to using the AgentAliasDNS setting. It works great for new agent installs and I'm currently getting by using a CNAME record for the old records. I believe Ylian added AgentAliasDNS to MeshCentral config due to an issue I was experiencing when running MeshCentral behind Azure Application Proxy. The sperate DNS record was needed for agents to map directly to the MeshCentral server.

@openmoto For myself yes it's a once off thing however it would be nice to future proof things by giving the admins the ability to update remote settings on the agents as needed. We never know what gets thrown at us and we'll at least have a way to change these settings if needed. 

Thanks for the script, I'll try ill on some test deployments although would need something for Linux and MacOS if this were to be implemented into MeshCentral.

Thanks

David.

**Comment by ryanblenis** [comment]
Ah, I see now with the AgentAliasDNS setting change, although I'd agree with @openmoto that it does sound like a one-off for most people. Maybe Ylian would implement something, but the script from openmoto could be adapted with wget or curl for other OS's. Even easier, could just be done by changing the `MeshServer` line in the msh file and restarting the Mesh agent service (no download required).

**Comment by openmoto** [comment]
@davscot,I just tried something on windows that works without reinstalling agent. It's just a temporary fix till meshcentral is updated with the feature.

Using @uldiseihenbergs suggestion to edit the text file, I came up with a way to script it.

`$MeshAgent = Get-Content  "C:\Program Files\Mesh Agent\MeshAgent.msh"`
`$NewMeshAgent = $MeshAgent -replace "oldserver.olddomain", "newserver.newdomain"`
`$NewMeshAgent | Out-File -FilePath "C:\Program Files\Mesh Agent\MeshAgent.msh"`
`"C:\Program Files\Mesh Agent\MeshAgent.msh" -restart`

Second line just insert your old dns name and the new dns name then save it as powershell script in meshcentral-scriptask.

I don't have alternate dns name to test with but replacing with the IP address continued working.

If it's not a one time fix, I would probably install powershell on Mac and Linix computers and use environmental variables instead of absolute path and the same script should work across all OS.

**Comment by si458** [comment]
you can use the new `msh` command in the console tab of a device
`msh get MeshServer` -> returns current meshserver url
`msh set MeshServer "wss://new.meshcentralserver.com:443/agent.ashx"` -> set meshserver url
dont forget to restart the agent afterwards with `service restart`
