### ISSUE TITLE
A Wake on Lan Problem

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1406]
Hi.
I think there is a bug about the WOL function.

I have two computers in an account which is not the administrator account, and these two computers are remote, off, in there.

Currently, the computer that can command WOL is located at a remote location,
but can only be accessed with an administrator account.

In this case,
the problem is that when I run WOL from the administrator account,
the computer turns on,

but when I run WOL from the user account,
the computer does not turn on.

What should I do?

**Comment by Ylianst** [comment]
The MeshCentral WOL feature will cause all the computers you have right to, to send out WOL packets. Because your triggering WOL from an account with two sleeping computers, there is no computer to send WOL on.

Are you asking that WOL should be sent out even on computers that are not on your account?

**Comment by eu4you** [comment]
I think I didn`t explain it well.

There are 4 computers in the remote. One of them is a computer that is always on. There are four in administrator account.

However, there are only two of them in a user account, which are usually turned off.
There is not the computer which is turned on always.

If I do WOL with an administrator account, WOL works via a computer that is always turned on.
But if I use a user account, WOL does not work.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.19 with improved Wake-on-LAN support. it should work much better now. Feedback appreciated.
