### ISSUE TITLE
SSO Enhancement: Router login via SSO

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1408]
MeshRouter should have SSO login support.

Proposed option to make this easier to maintain:

Router asks for Mesh Server Address on first page.
iframe equivalent the login from the server on next page (right now 2FA is on second page)

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.49 with a new version of MeshCentral Router. You can now click the "Install" button in MeshCentral Router to register it as the "**mcrouter://**" protocol. Then, you can open MeshCentral Router directly from the website with a single click, no further login and this works for SSO accounts. Feedback appreciated.

![MC2-MeshCentralRouterDirect](https://user-images.githubusercontent.com/1319013/83342069-9ade9680-a29f-11ea-8488-120c0b2c43d8.png)

**Comment by MordyT** [comment]
So this does work as described, thanks! I do wonder if I could request an enhancement - is it possible to call the "start router" via a desktop shortcut?

If not, no worries. Just trying to streamline it - click this, router comes up, click the rdp link and you are off to the races.

**Comment by Ylianst** [comment]
So, your need to be logged into the web site for the server to generate a time-limited login token that is passed to MeshCentral Router. This said, if your using a normal username/password account, you can launch MeshCentral Router with arguments, so create a shortcut. If I remember right, add -url wss://server... -user [username] -pass [password] to auto connect.

**Comment by MordyT** [comment]
Ok - last question about this. Can I call "Install" via command line?

If I wanted to deploy Router to everyone's PC via my own management tools and register it, I could robocopy it, place it in the directory I want it, then call install somehow?

**Comment by Ylianst** [comment]
Just looked it up, there are all the command line options:

```
-install	  Install the mcrouter:// protocol
-uninstall	  Uninstall mcrouter:// protocol
-ignorecert	  Don't display invalid certificate warning
-all		  Bind redirection local ports to all interfaces (not just loopback)
-tray		  Put MeshCentral Router on system tray
-host:[host]	  Set server name
-user:[user]	  Set username
-pass:[pass]	  Set password
-search:[string]  Set search string
```

So, correction, it's not -url, it's -host. yes, in can install using -install, but you need to be administrator privileges for it to work. When you hit the "Install" button in the UI, it will prompt for elevation before running -install. Hope that helps.

**Comment by MordyT** [comment]
Perfect, thanks again!
