### ISSUE TITLE
SSO: Adding user to a group

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1411]
When a user is from SSO, you cannot edit a group and add the user to it. The user shows up in autocomplete, but saving produces this error:

"Device Group: User xxx not found"

You can however edit the user and add him to the group that way.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.45 with a fix for this, let me know if it works. I improved the user suggestion box and added support for user identifiers.

![x](https://user-images.githubusercontent.com/1319013/82961076-27701880-9f71-11ea-83eb-42b59a62dcd3.png)

**Comment by MordyT** [comment]
Working and I love the identifiers!
