### ISSUE TITLE
SSO: NewAccountsRights not respected

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1412]
You can use "NewAccountsRights": [ "nonewgroups", "notools" ], for standard accounts, but accounts originating from SSO do not respect this setting.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.45 with a fix for this. Should work now, let me know if it does.

**Comment by MordyT** [comment]
This is now working!

**Comment by MordyT** [comment]
Sorry to re-open this...

In the following situation...
When domain configuration is set to 
"NewAccountsRights": [ "nonewgroups", "notools" ],

and saml configuration is set to:
"NewAccountsRights": [ "nonewgroups" ],

I would expect that local users don't have tools or new groups, but saml users have tools (but no groups).

The actual behavior is that saml users don't have tools or groups.

If you change the domain configuration to "NewAccountsRights": [ "nonewgroups" ], then saml users have tools (as do local users).

Let me know if this is clear enough

**Comment by Ylianst** [comment]
Looking into this one now

**Comment by Ylianst** [comment]
So, "newAccountsRights" was never implemented in the SAML section, adding it now.

**Comment by Ylianst** [comment]
Just added "newAccountsRights" support to SSO, will be in v0.5.47. Remove the "_" to make use of this feature.

```
        "saml": {
          "_callbackurl": "https://server/auth-saml-callback",
          "_disableRequestedAuthnContext": true,
          "newAccounts": true,
          "_newAccountsUserGroups": [ "ugrp//xxxxxxxxxxxxxxxxx" ],
          "_newAccountsRights": [ "nonewgroups", "notools" ],   <----------
          "entityid": "meshcentral",
          "idpurl": "https://server/saml2",
          "cert": "saml.pem"
        }
```

**Comment by MordyT** [comment]
Seems to be working, thanks!
