### ISSUE TITLE
Node and MongoDB error

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1413]
New issue for this error:

`(node:5888) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:5888) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:5888) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:5888) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency`

For the error, [I found this link](https://stackoverflow.com/questions/61406974/how-to-clear-warnings-in-node-js-while-using-mongoose). Looks like a problem with MongoDB and Node14 not related to any of this. Seems like the mongodb module will need to be updated.

_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/198#issuecomment-633694980_

**Comment by Ylianst** [comment]
Can you confirm you are using NodeJS v14? -Thanks.

**Comment by MordyT** [comment]
Yeah, I upgrades from 13.3 to 14 when setting up SSO just in case it was too old. I can downgrade if need be.

**Comment by Ylianst** [comment]
You can probably just fix it by stopping MeshCentral and doing:

```
npm install mongodb
```

This will update the mongodb module. Just in case, backup the "node_modules" folder before you do this. Then restart the server and it should work.

**Comment by MordyT** [comment]
This appears to have fixed it.
