### ISSUE TITLE
--loginkeyfile and possibly --loginkey appear to be broken in meshctrl in 0.5.45

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#1416]
# Problem Description:
`--loginkeyfile` and possibly `--loginkey` appear to be broken in meshctrl, the documentation may need to be updated, or I'm doing something wrong :) 

FYI, this error (Invalid login.) is the same as I get in https://github.com/Ylianst/MeshCentral/issues/1206 but I'm not sure if it's the same root cause.

# Environment
## MeshCentral Server
**Version:** v0.5.45
**Server OS:** Ubuntu 18.04.2 LTS

# Testing
As per the manual (http://info.meshcentral.com/downloads/MeshCentral2/MeshCtrlUsersGuide-0.0.1.pdf) on page 4:

We use this to generate a key (I will use the key in the example)

```
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --logintokenkey
```

Which generates this key
```
f3bd69a08a2dde4a3423bec8f20d8626b1e6365381f2d9919e7dfe256ace9cbbdea66bed2bdcd00b71eea9d7c727cb6eb37f3148c0c2d240d5ed44c8f3f6795a479c949159dad366571fea4db7f31c24
```

We put this into a file
```
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --logintokenkey > key.txt
```

We validate that the keyfile matches the `--logontokenkey`
```
# cat key.txt
f3bd69a08a2dde4a3423bec8f20d8626b1e6365381f2d9919e7dfe256ace9cbbdea66bed2bdcd00b71eea9d7c727cb6eb37f3148c0c2d240d5ed44c8f3f6795a479c949159dad366571fea4db7f31c24
```

We validate that the root domain's admin user is 'admin'
```
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --ListUserIDs
user//admin
```

Next, we try and get the `serverinfo`, but get an **invalid login** error.
```
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js serverinfo --loginkeyfile key.txt --loginuser admin
Invalid login.
```

If `--loginkey` is equivalent of `--loginkeyfile` then this also does not work for me
```
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl.js serverinfo --loginkey f3bd69a08a2dde4a3423bec8f20d8626b1e6365381f2d9919e7dfe256ace9cbbdea66bed2bdcd00b71eea9d7c727cb6eb37f3148c0c2d240d5ed44c8f3f6795a479c949159dad366571fea4db7f31c24 --loginuser admin
```

Additionally, as per https://github.com/Ylianst/MeshCentral/issues/1329 you state 
> The "LoginTokenKey" is static and will not change, however it's probably a good idea to rotate this key occasionally and so, you can run this to generate a new login key:
node node_module/meshcentral --logintokengen

When trying to use the `logintokengen` function a second instance and comes to the foreground, which doesn't seem to happen for any of the other commands.

```
# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --logintokengen
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.45, LAN mode.
MeshCentral HTTPS server running on port 443.
```

In my case, I'm running the command as root, but the service is owned by a separate user I've created called "meshcentral" not sure if this is breaking things?

```
$ ps aux | grep mesh
meshcen+  1797  9.0  0.8 1088244 67368 ?       Ssl  00:59   0:01 /usr/bin/node /opt/meshcentral/node_modules/meshcentral
meshcen+  1820 18.0  1.4 1321252 116716 ?      Sl   00:59   0:02 /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 1797
root      1836 13.9  0.8 1088500 67608 pts/0   Sl+  00:59   0:01 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --logintokengen
root      1846 26.3  1.4 1321380 117108 pts/0  Sl+  00:59   0:02 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral.js --logintokengen --launch 1836
```

If I use this new key, the result is the same, **invalid login**.

**Comment by Ylianst** [comment]
Ok, I will look into this tomorrow.

**Comment by Ylianst** [comment]
The feature works perfectly, but the likely problem is that both the computers you are running meshctrl.js on and the MeshCentral server needs to have clocks sync'ed. If theyr are off by too much, MeshCtrl.js will use the key to generate a time-limited login token that will not work.

I am fixing MeshCtrl.js now to indicate a better error and indicate the time much be correct.

**Comment by Ylianst** [comment]
Ok, this will be the new error when --loginkey or --loginkeyfile are used.

```
node meshctrl.js --loginkeyfile key2.txt serverinfo --loginuser admin --url wss://alt.meshcentral.com
Invalid login, check the login key and that this computer has the correct time.
```

**Comment by darryl-h** [comment]
> but the likely problem is that both the computers you are running meshctrl.js on and the MeshCentral server needs to have clocks sync'ed.

In my case, meshcentral and meshctrl are running on the same linux machine, sorry I should have stated that in my initial report.

**Comment by darryl-h** [comment]
That took surprisingly longer than expected. I'm unable to replicate this with a new Ubuntu 18.04 OS build (albeit, I'm not honestly sure how I got UTC in my old build, the installer auto-detects locale) there could have been a few things going on here, but I'm unable to pinpoint exactly which one(s) could be the culprit: 

1) During the OS and MeshCentral installation I did not set a timezone (Was UTC, not exactly sure how)
2) In the new installation, I did not setup a separate database (using the internal vs MongoDB)
3) I upgraded the MeshCentral service many times between installation and now (0.4.1-a, 0.4.1-x, 0.4.6-f, 0.5.10, 0.5.12, 0.5.1-j, 0.5.1-v, 0.5.3, 0.5.9) 
4) The server was not rebooted in a while (I neglected to capture that before rebooting)

In any case, **you may close this bug**, and I will revisit https://github.com/Ylianst/MeshCentral/issues/1206 in the near future (but thanks for the time heads up!) and as usual, thanks for all your hard work :)

**Comment by Ylianst** [comment]
The time used to generate the time limited login tokens should be UTC and so, should not depend on timezones. I will close this, but feel free to re-open or open a new issue as needed.
