### ISSUE TITLE
Mutli-OS-User-Consent

### ISSUE THREAD

**Issue by bryan-lieben** [Ylianst/MeshCentral#1419]
Hi, I want to install MeshCentral2 to use the User Consent Features, but i need to know if the user is not available to accept the request, can i configure like an automate accept after 30seconds if no interaction from the user to accept?

**Comment by bryan-lieben** [comment]
Hi Ylianst, any update or feedback on this request?

**Comment by si458** [comment]
this has been implemented now,
you enable `autoAcceptOnTimeout` under `consentMessages` under `domains`,
NOTE: this is on a DOMAIN LEVEL, it hasnt been implemented on a per device, or per group level yet
![image](https://github.com/Ylianst/MeshCentral/assets/765314/51bdd23c-8441-4d48-9ae7-4eefbd554869)
