### ISSUE TITLE
meshagent silent install on windows

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#142]
hi, is there a way to install meshagent in win without any window or message ?
I've downloaded agent from meshcentral in background mode, but when I run, it always display the standard window:
![image](https://user-images.githubusercontent.com/48550288/54824145-57a39380-4caa-11e9-9962-3dfafb61be37.png)

Is possible to use some sort of switch like /s or /h to get install completely stealth ?
We are trying to script installation across our domain, in unattended mode

Thanks for support

Merlinweb

**Comment by merlinweb** [comment]
Sorry for my stupid question without investigate deeply...

I've tried to type in command prompt meshagent.exe -h
![image](https://user-images.githubusercontent.com/48550288/54824826-51161b80-4cac-11e9-9daf-70ba1888c864.png)

run meshagent.exe with -fullinstall option (run as with administrative privileges, in a domain environment) and agent will install silently

Hope could help someone who need this....


Cheers

Merlinweb

**Comment by mschubeck** [comment]
Yes, using the "-fullinstall" switch has worked well on Windows clients for a while now, and it allows it to be used as an automatic GPO-based installation for AD-joined machines.

**Comment by merlinweb** [comment]
confirmed, both GPO or PSScript remote install work well

Thanks

**Comment by PathfinderNetworks** [comment]
Thank you for this- I was going to ask exactly the same question.  So, I assume I can use this -fullinstall command to silently upgrade my existing MeshCentral1 devices to MeshCentral2?  My goal would be to terminal in to the devices from my MeshCentral1 server.  Then run the MeshCentral2 agent in that terminal using the -fullinstall switch and then have that device be migrated on to my MeshCentral2 server.  
Has anyone tried that?

**Comment by mschubeck** [comment]
I did several months ago and it didn't work very well.  What I ultimately did was use scripts to do the following:
1. Copy the latest meshagent.exe installer to a temp directory on all machines.  This is where your "other" RMM software comes in handy, but it can be scripted through GPO if all of your machines are under domain control.  Most of mine are, some are not.
2. Run the latest meshagent.exe with the **-fulluninstall** switch
3. Run it again with **-fullinstall** switch.

This method worked on all but 2-3 machines that wouldn't reinstall to connect to the MC2 server.  What was happening was that the newest agent would install, but show up in the older MC v1 server.  Ylian wrote an automatic-manual uninstaller that you can get from the "download mesh agent" menu, and that worked on those last 2-3 stubborn machines I had.
![image](https://user-images.githubusercontent.com/48728727/54848837-c556bc00-4cb8-11e9-84f5-97b1fe984b95.png)

**Comment by jsastriawan** [comment]
What I did in the past to migrate MC1 to MC2 is to run uninstall old agent chained with new agent installation.

E.g.

C:\Program Files (x86)\Mesh Agent\MeshAgent.exe -fulluninstall && c:\downloads\MeshAgent.exe -fullinstall

It works quite well from MC1 remote terminal.

I think Ylian has written MeshCentral migration tools too.

**Comment by PathfinderNetworks** [comment]
I just tested a device to see how this was going to work.  The device is running Windows 7 and has been on my MeshCentral1 server for quite a few  years.  I transferred the MeshCentral2 agent to it and then opened a remote terminal via MeshCentral1.  I ran meshagent-name -fullinstall through that terminal (without removing the MeshCentral1 agent as I was using that agent for the remote terminal session).  It did exactly what I wanted- moved the device from the MeshCentral1 server to the MeshCentral2 server. All within seconds and without issue.   Granted, this is only the first system I tried that on. But I didn't have to uninstall the old agent first for it to work.  BTW, the system is no longer showing as present on the MeshCentral1 server (although it's entry is still there- just not powered on.  Which is fine as I manually delete them as I move them over anyway).

**Comment by krayon007** [comment]
I think that's because the mesh1 and mesh2 agent use the same name so the mesh1 agent gets removed when installing the mesh2 agent. I haven't personally tested this scenario tho. However I do install the mesh2 agent from terminal all the time, tho I use JS code to do it so I can specify the service name...

**Comment by PathfinderNetworks** [comment]
I just tested the same process on a number of Windows 10 devices (copying the MeshAgent2 on to the device, opening a remote terminal via MeshCentra1, running meshagent-name.exe -fullinstall through that terminal) and it worked correctly on all of those devices as well.  Or at least appears to be working correctly.  All of those devices show up on my MeshCentral2 server and are full accessible through it.

**Comment by Ylianst** [comment]
Seems like the original issue has been solved. Additionally of note is that the old MeshAgent v1 and new MeshAgent v2 do indeed have the same Windows Service name and so, one will over-install on top of the other. I will close this one, but feel free to reopen or open a new issue if needed.
