### ISSUE TITLE
gnome-session not found

### ISSUE THREAD

**Issue by merinleona** [Ylianst/MeshCentral#1422]
I am trying to connect to a laptop with Fedora with a KDE Plasma environment on it. 
The picture is extremely laggy (sometimes 5 minutes behind) and the Konsole keeps saying gnome-session not found.. well of course not there is no Gnome on there?
The mouse on the "remote" laptop moves fine when I move it the browser session and the laptop is responsive. I just can't see what I am doing in the browser because the picture lags.
Any idea why?

**Comment by krayon007** [comment]
What version of fedora and what version of plasma?  And when you say the konsole is saying gnome-session not found, which konsole is saying that? The service should be running without a console so it wouldn't have anywhere to output such messages...

**Comment by merinleona** [comment]
Fedora 31 (Kernel 5.6.6-200.fc31.x86_64)
with Plasma 5.17.5

I am not running the service in a terminal. I mean the Meshcentral Console tab. I clicked through all the tabs searching for a solution for it not working and noticed that is kept repeating gnome-session not found.

**Comment by merinleona** [comment]
![Screenshot_20200527_195543](https://user-images.githubusercontent.com/10296389/83055565-4bf0f100-a054-11ea-9300-957374338032.png)

**Comment by krayon007** [comment]
ok. I'll setup a newer Fedora system to try to replicate this issue, as the latest Fedora that I have tested this on was Fedora 29.

**Comment by krayon007** [comment]
By the way, which Mesh Central server version are you running?

**Comment by merinleona** [comment]
0.5.45

**Comment by krayon007** [comment]
I'm not sure what's happening on your system. I just did a fresh setup of:
Fedora 32, Kernel 5.6.6-300
KDE Plasma 5.18.3
and everything appears to function normally, with no lag. I also don't see the gnome-sesison thing...

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
