### ISSUE TITLE
ManageAllDeviceGroups with SSO Users not working

### ISSUE THREAD

**Issue by MordyT** [Ylianst/MeshCentral#1423]
https://github.com/Ylianst/MeshCentral/issues/198, @Ylianst stated:
`For "ManageAllDeviceGroups", add "user/[domain]/~saml:userid", that should work. You can also do node node_modules/meshcentral -listuserids to see all user identifiers and cut & paste the right one.`

In Mesh web portal, there is a User Identifier - if you run the command: node node_modules/meshcentral --listuserids you see the same ID. It is formatted:

user//~saml:email@domain.com

Placing this in the ManageAllDeviceGroups does not appear to work.

(I'll be out at work with no network access for a few days but will reply when I get back)

**Comment by Ylianst** [comment]
Note that you must also have full server rights for "ManageAllDeviceGroups" to work. I will test it again now, but unless the account has full server rights, "ManageAllDeviceGroups" will do nothing.

**Comment by Ylianst** [comment]
Ok, your right. It did not work right. This is fixed in the next version. You can now do this in the settings section:

`"ManageAllDeviceGroups": [ "user//admin", "user//~saml:bob" ]`

And/or do this in the domain section

`"ManageAllDeviceGroups": [ "~saml:bob" ]`

Both will work.

**Comment by MordyT** [comment]
Seems to be working. I was a little hesitant since the user// is missing when doing it in the domain section, but it works.
