### ISSUE TITLE
Desktop won't open on old iPad devices

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1425]
Hi.

I am currently using the iPad mini 1. (iOS 9.3.5)

In the mobile version, the web page comes out well,
but when the desktop is connected, the remote monitor is not displayed.

When connected in desktop mode,
the web page frame is also displayed abnormally,
and the remote monitor is also not displayed.

The same goes for Safari, Chrome (83.0.4103.63) and Dolphin Browser HD 9.24.4.

**Comment by si458** [comment]
all working on latest ios browsers and android browsers in 2023
