### ISSUE TITLE
Delete user group causes crash when computer groups still defined

### ISSUE THREAD

**Issue by ckibodeaux** [Ylianst/MeshCentral#1430]
Testing out the user groups feature on version 0.5.47 I created a user group and assigned a couple computer groups to it with a user. After testing I went to delete the group and was redirected to "server disconnected reconnect to server." A page refresh later and I'm back at the user group. Only way to delete the user group is to remove all the assigned computer groups first. Attached is the error log that was generated at the crash.

[servererrors.txt](https://github.com/Ylianst/MeshCentral/files/4701540/servererrors.txt)

**Comment by Ylianst** [comment]
Thanks for reporting this, I am fixing this right away!

**Comment by Ylianst** [comment]
Check in a fix for this, will be in MeshCentral v0.5.48 when it's next published.

**Comment by Ylianst** [comment]
Fix is published, let me know if it works.

**Comment by ckibodeaux** [comment]
Confirmed that deleting group works as expected.
