### ISSUE TITLE
NPM installation procedure for Raspi insecure

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshCentral#1433]
In the installation guide, in the raspi section, I see:
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash

Using curl | sudo is really bad advice, IMHO, even if I can understand the search for easiest procedure for noobs...

Wouln't there be a more secure option for raspian ?

Thanks in advance.

**Comment by olberger** [comment]
Maybe at least a pointer to https://github.com/nodesource/distributions/blob/master/README.md#manual-installation would be nice so people are offered the choice of selecting the best procedure ?

**Comment by olberger** [comment]
Btw, on raspbian buster, there's a 10.x version of the nodejs already available in the repos... so I fear these instructions are either useless, or there's a need for some explicit selection of the version to install with apt (and apt-get is deprecated now, in Debian)

**Comment by Ylianst** [comment]
Instructions where written when NodeJS was not available in Raspbian. By the way, do feel free to update the instructions and do a pull request, that would be much appreciated.

**Comment by olberger** [comment]
Uh... I was ready to do so, but I'm afraid a PR on a .odt document won't work.

Would there be a possibility to get another form of source for the docs (maybe HTML, kinda, or markdown, org-mode or whatever else can generate HTML, ODT, etc.) ?

**Comment by si458** [comment]
its best to now use `nvm` to install node
```
# installs nvm (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash

# download and install Node.js (you may need to restart the terminal before running this command)
nvm install 22

# verifies the right Node.js version is in the environment
node -v # should print `v22.11.0`

# verifies the right npm version is in the environment
npm -v # should print `10.9.0`
```
