### ISSUE TITLE
Clarify NodeJS version dependency

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshCentral#1434]
I've tried installation on a raspi running raspbian, buster version.

There's a nodejs versions 10 available in the Debian packages, so the 8.x installation mentioned in the installation docs is pointless...

But afterwards, npm complains that version 10 isn't supported :-/

Maybe it should be stated in the docs which version is required/recommended ?

Then maybe adjust the apt-get installation commands provided in the docs, to specify precisely the version (it different from 10, current in Debian).

Thanks in advance.

**Comment by Ylianst** [comment]
MeshCentral supports NodeJS 6.0.0 and higher, but some features will required NodeJS 8.x or higher. If this happens, MeshCentral will clearly state this.

However, I don't think your problem above is related to MeshCentral.
