### ISSUE TITLE
WAN only and --lanonly confusion in raspi installation docs

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshCentral#1435]
The installation docs () state in "5.3 Installing MeshCentral"

> After that, we can run MeshCentral for the first time. We want to run in WAN-only mode since we
> will not be managing any computers on the same local network at this server. We also want to
> create a server with a certificate name that is the same at the AWS instance name. So, we will use
> “--wanonly” and “--cert [name]” arguments to get the server started. For example:

But the snipped provided is:
```
node node_modules/meshcentral --lanonly --fastcert
```
I guess there's some confusion between AWS and raspi, WAN and LAN...

Hope this helps,

**Comment by si458** [comment]
the is new docs here to follow instead of the PDFs
https://ylianst.github.io/MeshCentral/install/install2/
