### ISSUE TITLE
[Feature Request] Screen capture when not connected

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#1436]
Hi Ylianst / community,
MeshCentral is very good software thank you for all this effort. 
One feature I want to use is the ability to capture screen without connection.
I manage several devices using meshcentral, but I want to periodically capture the screen and save it as a file. It would be great if you could do this automatically without having to connect every time. 
Is there a way to do this using meshcore in the current version? And if consideration for adding this feature would be even more appreciated. 

Thank you for all you do.

**Comment by Ylianst** [comment]
This is not possible right now. We have to create a new process to perform screen capture, we would have to automate, etc. Probably best to run a process that runs as the user that performs that tasks and sends it back to the server. It don't think meshcore.js is well adapter to do this.

**Comment by hchkim** [comment]
OK, I see.
Thanks for feedback!
