### ISSUE TITLE
Downloading a file clones a new files tab window

### ISSUE THREAD

**Issue by PTR-inc** [Ylianst/MeshCentral#1437]
V0.5.49
Tried and seen on vivaldi, firefox and safari on mac

When I click a file to download in the files tab, a new window/tab is cloned from the files view with the save requester. The new window isn't closed after saving, which I think was the original behaviour.

**Comment by Ylianst** [comment]
Thanks for reporting this. Just published v0.5.50 that includes a fix for this. If it works, please close this issue.

**Comment by PTR-inc** [comment]
Fixed, thanks!
