### ISSUE TITLE
I should restart MeshAgent in Remote

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1439]
Hi.
Thank you for making a very good program, and I use it very well.

When the CPU load is excessive,
the MeshAgent sometimes becomes stuck while using remote control.
I wish I could restart the agent from the agent console.

**Comment by MordyT** [comment]
Open a terminal and restart the service? something like:
` Restart-Service -name *mesh*`

**Comment by PTR-inc** [comment]
Tried that once, but with stopping the agent, the shell gets killed as well before the start command is issued to the agent service ending up with a stopped agent.
I've seen the cpu problem before on older windows os'es and now just do a nightly scheduled restart through the task scheduler.
An 'internal' agent restart would be nice.

**Comment by vitko-bg** [comment]
I am in this request also. In some cases would be very usefull to have this option. I also created a BAT file to be able to restart agent, but does not work - as session becomming unavailable once service is stopped and does not start service after stopping.

**Comment by krayon007** [comment]
If you click on the desktop tab, then click on the tools button, you can click on services, and find the meshagent service in the list, and click on it. There is a restart button there.

**Comment by PTR-inc** [comment]
Works like a charm, thanks!

**Comment by vitko-bg** [comment]
Thanks @krayon007

**Comment by krayon007** [comment]
Eventually, @Ylianst  is going to add a "tools" button to the terminal tab too, becuase some machines won't have a desktop tab, which makes the tools functionality inaccessible. But that's just a UI change.

**Comment by si458** [comment]
this has been implemented as explain above using the tools/services tab 
OR
by sending `service restart` in the contab tab of the device!
