### ISSUE TITLE
Generate new ID on sysprep

### ISSUE THREAD

**Issue by sorvani** [Ylianst/MeshCentral#144]
I would love to install this agent on my base image for deployment, but I assume that the unique agent ID would then not be reset.

Is there anyway to install it that would work with this deployment method? Or will I be required to always run this in a post image script?

**Comment by krayon007** [comment]
So in your base image, the agent is already installed? If so, if you pull the agent from git, and temporarily copy the dbTool.js file from the modules folder, you can use that to delete the cert from the DB. That way when you deploy the agent will generate a new cert and new ID on first start. 

Im on the road at the moment, but when I get a few cycles I can post back with the I instructions on how to do that, as I can't remember the name of the dbkey you need to delete off the top of my head.

But you would basically run the command:

MeshAgent dbTool.js delete keyname

Where keyname is the name of the key you want to delete...Also substitute the name of the binary for MeshAgent as it's different on each platform.

**Comment by Ylianst** [comment]
Two things on this.

- First, the MeshAgent has a anti-cloning system that will auto-reset it's id if all MAC addresses on the system are different than the last time it started. So if you clone the OS with a MeshAgent on many different computers, it should auto-reset it's agent certificate. However, in some VM's, that may not work.
- Second, you can just delete the MeshAgent.db file before taking a snapshot. The agent will re-create it and generate a new certificate for itself. As long as the .msh file points to the right server, that should work.

Bryan has a more fancy technique where you remove a specific entry in the MeshAgent.db file.
Hope it helps - Ylian

**Comment by jdpillon** [comment]
Hello,
I am new to meshcentral and I love it. Thanks.
I did want to do the same (on linux but I think it will work as well on other os).

I just create a "Pending" group on my meshcentral server and add my master image to this group. So when the deployed machines starts, they will register to this group. A little bit of work has to be done to dispatch the computers in it's real group afterwards but it works fine for me.

JD

**Comment by Ylianst** [comment]
Closing this issue as I think it's solved. Feel free to re-open or file a new issue if the agent anti-cloning system does not work as expected.
