### ISSUE TITLE
Clipboard issue

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#1441]
Hi

I recently deployed meshagent to an Ubuntu 18.04 and Ubuntu 20.04 and on both machines when you try to set the clipboard, its says success. However there is nothing too paste on the target machine. If on the ubuntu machine i copy something to the clipboard, and perform a get clipboard this is retrieved. Seems like only when trying to set is not working.

The clipboard feature works fine on win 10 and 7, and also ubuntu 14.04 (i have only tested the remnux edition).

Server version 0.5.24
Happy to provide additional logs etc, if you can point me into the correct location.

**Comment by krayon007** [comment]
Try using the middle mouse button. Clipboard on Linux is very different from windows, because on Linux, there are multiple different clipboard buffers. I had to use the X clipboard buffer, but not all apps on Linux use that. Many use their own clipbuffer, like the terminal app. But usually the middle mouse button is tied to the buffer.

**Comment by vish84** [comment]
Thanks. I will give that a test. Just something im trying to wrap my headaround, why does get work, but not set for the clipboard.

**Comment by krayon007** [comment]
That's becuase I remember reading a while ago, that one of the components running in X, automatically hooks one of the clipboard events, and copies data to the buffer I'm reading from when something writes to the other clipbuffers. But the reciprocal is not the case. Or something like that, it was a while ago... The documentation for accessing the clipboards in X is pretty sparse.

**Comment by vish84** [comment]
Thanks for the info, helped me do a little research of around this issue. The middle click does work, however I found it to be a little fiddly. I have found you can install other clipboard managers on ubuntu which will synchronise both clipboards together, which allows you to use the right click or ctrl v, without having to worry about the middle click. The one that I have tested and found works for me is Diodon and Clipit, but there are several others.

**Comment by vish84** [comment]
Thanks for the info, helped me do a little research of around this issue. The middle click does work, however I found it to be a little fiddly. I have found you can install other clipboard managers on ubuntu which will synchronise both clipboards together, which allows you to use the right click or ctrl v, without having to worry about the middle click. The one that I have briefly tested and found works for me is Clipit, but there are several others.

Not sure if its possible for the agent to perform this type of clipboard synchronisation instead of installing other apps.

**Comment by krayon007** [comment]
I originally looked into doing something like that, but it looked like I would need to install some helper libraries to do that, and I was trying to avoid having additional dependencies.

**Comment by krayon007** [comment]
One thing I can do, is I can try to detect if xclip is installed and use that if it's there...

**Comment by krayon007** [comment]
ok, I updated the linux agent (will be in next update), so that if xclip is installed on the platform, it will take advantage of it when reading/writing to the clipboard. This makes it so the clipboard seems more like the clipboard on windows. I was able to copy/paste straight into the terminal, etc...

**Comment by krayon007** [comment]
While I was at it, I added clipboard support to macOS... It will be in the next update as well.

**Comment by vish84** [comment]
Thats great, look forward to the next update to give this a test

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.51 with Bryan's latest MeshAgents. You also need to install "xclip" to make the new clipboard work.

**Comment by vish84** [comment]
Thanks guys for the rapid enhancement, you guys do a great job. 

I can confirm that I have tested this on ubuntu 20.04 with xclip installed. I can confirm this is working as expected, you can use ctrl-v and also from the context menu when using the mouse.
