### ISSUE TITLE
How can it be rebuilt from sources ?

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshCentral#1442]
I've not found a straightforward description of how to rebuild MeshCentral from sources.

It seems there's a lot of VS/Windows stuff, but I'm on Linux, so I'm a bit clueless.

Would there be some docs/instructions ?

Thanks in advance.

**Comment by krayon007** [comment]
Are you talking about the server or the agent?

**Comment by olberger** [comment]
Well, I guess the server, as I've been looking in this MeshCentral repo only, yet.

**Comment by ryanblenis** [comment]
There's nothing really to "build" of the server, if you clone the repo, you can run `node meshcentral` directly and have a running instance up (assuming you've got the dependencies installed). They're javascript files for the admin web interface.

If you want to build MeshRouter, MeshCmd, MeshAgents, etc. that the project contains, those repos will help you out if needed (Brian especially on the agents)... but the server itself does not really require any compiling once you've got the source.

**Comment by olberger** [comment]
Thanks for these responses. Could you maybe add that to the documentation, so as to make it explicit ?
Best regards,
