### ISSUE TITLE
Log Retention

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#1443]
Log retention (at least on meshcentral.com) seems to be only 21 days. Is this expected behavior? If so could it be extended or archived logs sent somewhere?

**Comment by Ylianst** [comment]
In the "settings" section of config.json, add this section:

```
    "DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    }
```

This is how long to keep all events in seconds, put the values you want.
