### ISSUE TITLE
Meschentral on raspberry4 CPU load information not updating

### ISSUE THREAD

**Issue by Fred1984** [Ylianst/MeshCentral#1444]
hello @Ylianst 

the CPU load field always show 0,0,0 maybe it is a bug? i installed it on raspberry pi4  with 0.5.49
I also compared with my production server (which is 0.5.50) and this field is even not displayed

![image](https://user-images.githubusercontent.com/62277469/83606929-f618cd80-a5ac-11ea-9dab-b435fbdb6035.png)

if it is a bug, be free to handle it as you want :)

Frederic

**Comment by Ylianst** [comment]
The CPU load is not displayed if MeshCentral is setup of a Windows machine. Windows servers will only have the memory indicator (has to do with being able to get this data from NodeJS).

What version of NodeJS are you using on the RPi 4? Thanks.

**Comment by Fred1984** [comment]
Hi Ylianst, 
here it is
![image](https://user-images.githubusercontent.com/62277469/83863442-eb4d6c80-a755-11ea-9bd4-fbf454266afc.png)

**Comment by Fred1984** [comment]
hello the problem is now ok with the last update thanks you
