### ISSUE TITLE
about public/commander.htm

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#1446]
Hi Ylianst / community,

I want to change the public/commander.htm file. However, it is difficult to modify because it is minified. I wonder if there is a way to change and build it.

**Comment by Ylianst** [comment]
MeshCommander is on my GitHub here: [https://github.com/Ylianst/MeshCommander/](https://github.com/Ylianst/MeshCommander/). It's also open source. Hope that helps.
