### ISSUE TITLE
Logged-in user is not updating

### ISSUE THREAD

**Issue by GibsonX72** [Ylianst/MeshCentral#1449]
I am seeing many instances of the "User" field not updating and showing when users have logged in or out.  My whole client environment is Win10 1703 or higher, but are several different CPU types.  Other functions of the mesh agent seem to be working as expected, and the User info will update properly if I restart the mesh agent service on the client, but will eventually stop updating User info again.

MeshCentral running on VMWare VM, CentOS 7.8.2003, currently at version 0.5.50...I am 99% sure this was not happening on versions up to and including 0.5.36, but this issue is easy to miss if you're not paying close attention, so I don't know what exact version after .36 it may have popped in at.

Thanks!

**Comment by GibsonX72** [comment]
Update:  I rolled the server back to 0.5.46 from a VM snapshot, and the problem appears to have gone away.  User information is updating properly, as near as I can see....will update if it starts happening again.

**Comment by krayon007** [comment]
When it wasn't working.... Was it updating and then eventually stopped updating, or did it just not update at all?

**Comment by GibsonX72** [comment]
It would start out working for awhile when either the mesh agent service or the whole client was restarted, but would eventually stop updating the user info after what appears to be a couple hours.

**Comment by GibsonX72** [comment]
Update - just went through all my devices, and it appears that rolling back to 0.5.46 fixed the issue.  All are still updating user information properly since the rollback on Thursday.  Let me know if you need any further info, logs, etc. and I'll get you whatever you need.  Thanks!

**Comment by krayon007** [comment]
Are you saying 0.5.46 is the last version where the update worked, or that just happens to be what you rolled back to?

**Comment by GibsonX72** [comment]
0.5.46 was working when I updated to it, then I went up to .50 and that broke the functionality.  I then rolled back to .46 again, and it has been working again since then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ylianst** [comment]
I have not seen this on latest versions of MeshCentral. I am going to close this, but please open again if you see this happen.
