### ISSUE TITLE
Not able to add Mac in 0.5.11

### ISSUE THREAD

**Issue by thalhammermax** [Ylianst/MeshCentral#1451]
Unable to add a mac computer in 0.5.11(latest stable), It was working fine and connecting to another machine with Work From Home Plugin, and then the user started reporting issues, just checked mesh, and it says the device is offline, even though user is on the machine, using it, and I cannot re-add the machine, or even add my own mac to the server. Help!!!

**Comment by krayon007** [comment]
Only macs aren't appearing on your server?
