### ISSUE TITLE
No way to bind on specific network interface

### ISSUE THREAD

**Issue by M1CK431** [Ylianst/MeshCentral#1452]
Hi @Ylianst ,

First of all, thanks a lot for this awesomely great tool! :kissing_heart: 

I have setup a selfhosted instance of MeshCentral on my server. This server is also used for other purposes (incl. as a web server) and so I have created and configured an Apache vhost to act as a reverse proxy (which also take care of SSL stuff). Everything is working very well, thanks to `TlsOffload` option. :tada: 

But now (for obvious security reasons) I would like to make MechCentral itself only reacheable from loopback interface (aka 127.0.0.1). Unfortunatly, I haven't found any `host` option in CLI or config file where I could tell MeshCentral to bind all his listening ports on a specific network interface.

Is there any way to achieve that?

**Comment by Ylianst** [comment]
This is a good request. It's not possible now, but I will add an option for this. Anything security related is always a good idea.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.51 with there 4 added options on the settings sections of config.json:

```
    "PortBind": "127.0.0.1",
    "RedirPortBind": "127.0.0.1",
    "AgentPortBind": "127.0.0.1",
    "MpsPortBind": "127.0.0.1"
```

When specified, it will bind that port to the specified interface. Let me know if that works.

**Comment by M1CK431** [comment]
It works! :man_cartwheeling: 
As a JS developer myself, you impressed me: you have fix this so fast! :rocket: 

Thanks A LOT :kissing_heart: 
Have a nice day

**Comment by vicomte** [comment]
I hate to ask right after you finished, but can you specify multiple interfaces?

**Comment by Ylianst** [comment]
The operating system does not allow a socket to bind to anything else than a single interface or all. There is no in between. The alternative is to use a reverse proxy on the same machine and setup the proxy the way you want it with different forwarding routes for each interface. Maybe you could also use ANY and use firewall rules to block things. Hope that helps.
