### ISSUE TITLE
How to get the node id of the meshagent in the agent side using terminal

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1455]
How to get the node id of the meshagent in the agent side using terminal

**Comment by Ylianst** [comment]
On Windows, take a look in the registry at this location:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Open Source\MeshAgent2
```

You get a bunch of information about the agent.

![image](https://user-images.githubusercontent.com/1319013/83843164-467d5180-a6b9-11ea-9ca2-d4822a00985b.png)

**Comment by Ylianst** [comment]
Somewhat related, you can create a "meshagent.tag" file with some simple text data next to the agent and restart the agent. The content of the file will show up on as "Agent Tag" in the devices general page.

**Comment by Ylianst** [comment]
On Linux:

```
sudo /usr/local/mesh/meshagent -nodeid
```

**Comment by aimdharma1990** [comment]
Thanks for the information. This will not work when we run using "run"
command from the windows terminal. Even i create tag, i couldn't able to
access the machine using that .

https://localhost/?*tags=xys*&viewmode=11&hide=15
<https://localhost/?node=UkSNlz7t...2Sve6Srl6FltDd&viewmode=11&hide=15>

how to achieve this.?

**Comment by Ylianst** [comment]
You can't run the agent and ask for the nodeid in the same command. Just run the agent in the background and then run the agent again with -nodeid.

**Comment by JohnyHHH** [comment]
how to get the node id for agent that run in temporary mode?
Possible to get it from command too?
