### ISSUE TITLE
No way to disable redir and MPS port

### ISSUE THREAD

**Issue by M1CK431** [Ylianst/MeshCentral#1456]
Hi (again) @Ylianst ,

Following my previous issue (#1452 - where I describe my setup), I'm taking care of the HTTP => HTTPS redirection in my reverse proxy. And so I think that it could be a performance enhancement to disable the redir port. However I haven't found any way to do it.

The same thing for MPS port: thanks to new option `MpsPortBind`, this port isn't publicly reachable anymore and because I don't plan to use it, I would like to disable it. Again however, I haven't found any way to do it.

Generaly, I think more intuitive, performance saving and reassuring to only listen on effectively used port. What do you think?

**Comment by vitko-bg** [comment]
Try to use underscore before parameter, ie. _MpsPortBind

**Comment by uldiseihenbergs** [comment]
if you want disable mps post, use: `MpsPort": 0`. i think it works for me, i don't see a message in logs about starting mps server anymore.

**Comment by M1CK431** [comment]
Hi @uldiseihenbergs ,

It works, both for `RedirPort` and `MpsPort` :tada: 

Here is my perfect config file:
```json
{
  "settings": {
    "Cert": "mesh.domain.com",
    "ExactPorts": true,
    "Port": 4430,
    "PortBind": "127.0.0.1",
    "AliasPort": 443,
    "RedirPort": 0,
    "AgentPong": 300,
    "MpsPort": 0,
    "TlsOffload": "127.0.0.1",
    "Minify": 1,
    "Wanonly": true
  },
  "domains": {
      "": {
          "certUrl": "https://127.0.0.1:443/",
          "NewAccounts": 0
      }
  }
}
```

I think that a mention about this behaviour should be added in the documentation.

Thanks everyone for your precious help :heart_eyes:
