### ISSUE TITLE
Using MeshCMD in bash script

### ISSUE THREAD

**Issue by ckibodeaux** [Ylianst/MeshCentral#1457]
Using MeshCMD to access ports on other networks from a host computer is AMAZING! I download the meshcmd file for Linux and the meshaction.txt for the remote agent. After tweaking the ports and such in the meshaction.txt I run the meshcmd file and everything works.

The problem is that I would like to have several meshaction.txt files available for use when needed, however if you rename the meshaction.txt file, meshcmd will no longer see the file. I thought, OK, I'll use a bash script to get this going. Using the bash script the terminal reports that the port has been redirected, but it doesn't actually work.

Is there a way to call a renamed .txt file with meshcmd:
**`./meshcmd --config port.txt`**
or can you assist with my bash script? I've attached both for review. The ID's in the file have been truncated to "..." for privacy. Currently on server version 0.5.51.

[bash.txt](https://github.com/Ylianst/MeshCentral/files/4737469/bash.txt)
[meshaction.txt](https://github.com/Ylianst/MeshCentral/files/4737465/meshaction.txt)

**Comment by ckibodeaux** [comment]
Turned on server tracing to see if there was anything going on.

When using meshcmd with the meshaction.txt file LOADS of relay traffic is displayed.

When using the bash script only one line gets entered:
`RELAY: Relay: Soft disconnect (98.186.194.18)`

**Comment by D4V3M0NK** [comment]
@ckibodeaux have a peek at what I use, just uploaded it to [github](https://github.com/D4V3M0NK/meshcentral-meshAgentController) - I had the same requirements so decided to use a couple of scripts to manage them all (I have about 30 of them at the moment)

**Comment by baikal** [comment]
The option for another filename is --actionfile, e.g. `meshcmd --actionfile otherfile.txt`.

For scripting purposes, I was successful with heredoc-style like
```
read -p password: -s PW
meshcmd --actionfile /dev/stdin <<EOF
{
 "action": "route",
 "localPort": 44310,
 "remoteNodeId": "node//Q...5",
 "remoteTarget": "192.168.0.21",
 "remotePort": 443,
 "username": "c...x",
 "password": "$PW",
 "serverId": "3...B",
 "serverHttpsHash": "3...B",
 "serverUrl": "wss://mesh.domain.com:443/meshrelay.ashx"
}
EOF
```
This avoid having passwords written to files or appear on commandlines (visible by `ps`). But I guess there will be ways to peek at stdin of processes to ...

**Comment by ckibodeaux** [comment]
I will be prompting for password and 2FA token in production (if I can get things working) but for the testing system I put the login in the file for ease instead of typing it over and over.

@D4V3M0NK I'll check it out.
@baikal I tried the --actionfile port.txt before posting and didn't have any success. Just tried it again and I'll be damned. It worked! Must have had a typo the first time around. I'm going to mark this as closed because it solved the need I had. Thanks to both of you!

**Comment by ckibodeaux** [comment]
Going through the history log I see where I messed up the first time trying to call the file. I was using ./meshcmd --actionpath port.txt instead of --actionfile. Doh!

There was a pull request #1397 about using authCookie for authentication, but I have yet to venture that far.

**Comment by baikal** [comment]
@ckibodeaux regarding token: I am using that as well, prompting and in the heredoc-json as for the password
```
read -p token: TOK
...
 "token": "$TOK",
...
```

@D4V3M0NK you can avoid stripping the quotes of by using `jq -r '.password'` in your 'fly', bonus  it would also work if the password actually contained quotes.

**Comment by ckibodeaux** [comment]
Posting in case anyone else stumbles on this with a similar use case. This works for what we wanted but your usage may vary. We have multiple clients with devices that can usually only be accessed on the local LAN. We can't program for every device in every site as it would lead to an unmanageable level of files. What we did was download a meshaction.txt file for an always on system located on each site then use a script to prompt what target and ports to use.

### meshagent.txt renamed to pc-name.txt
{
 "action": "route",
 "remoteNodeId": "node//Y...@",
 "username": "c...x",
 "serverId": "3...B",
 "serverHttpsHash": "3...B",
 "debugLevel": 0,
 "serverUrl": "wss://mesh.domain.com:443/meshrelay.ashx"
}

### Script called pc-name.sh
#!/bin/bash

read -p "Target: " target
read -p "Remote Port: " rport
read -p "Local Port: " lport
read -sp "Password: " password
echo ' '
read -p "Token: " token

/opt/meshcmd/bin/meshcmd --actionfile /opt/meshcmd/client/pc-name.txt --remotetarget $target --remoteport $rport --localport $lport --password $password --token $token

Thanks again to @baikal & @D4V3M0NK for their help in pointing me in the right direction. D4V3M0NK, I'm pretty sure I'll implement your version soon, but this was enough to get us started while we are still experimenting with MeshCentral.

**Comment by D4V3M0NK** [comment]
This was my first time using jq and it was a while ago - been using it more
recently and haven't gone back to revise the code, but thank you for the
comments.I like use of heredocs for capturing the security credentials - am
thinking of integrating that into a potential new option, with all due credit!

**Comment by D4V3M0NK** [comment]
@baikal - thanks for the note regarding `jq -r` ... makes life easier!
