### ISSUE TITLE
Bug? Download file includes download.html

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1458]
Hello chaps - it's been a while...
Just updated to 0.5.51 in order to download a file from a server, and when I do so, I notice that Chrome prompts me for multiple downloads. Not only does the file that I want download, but `download.html` downloads too.

Not urgent, just thought I'd mention it.

**Comment by Ylianst** [comment]
Thanks for the report. Published MeshCentral v0.5.52 with a fix for that. Let me know if it's ok.

**Comment by D4V3M0NK** [comment]
Yup, all sorted thanks Ylian!
