### ISSUE TITLE
More information for "Agent bad web cert hash, holding connection"

### ISSUE THREAD

**Issue by luckydonald** [Ylianst/MeshCentral#146]
So I get
```
meshcentral_1  | Agent bad web cert hash (Agent:cfe5a40fc3 != Server:582e177d35 or 927f3d1b51), holding connection (172.18.0.7:34100).
```
This might be related to either cloudflare in front of my server or the nginx reverse proxy container of my server.
I have set up the `CertUrl`, that's probably why there is a `or` part and two certificates to match with.
However it is (obviously) not working out, and the hashes aren't providing any good clue on why that is.

I can post my specific configuration to troubleshoot, but a more descriptive error message indicating which certificate actually were used, would help better in the long run.

Maybe we could additionally display the standard fields any common browser displays:
- Issued To
  - Common Name (CN)
  - Organisation (O)
  - Organisational Unit (OU)
  - Serial Number
- Issued By
  - Common Name (CN)
  - Organisation (O)
  - Organisational Unit (OU)
- Fingerprint
  - SHA-256
- _maybe_ Extension Fields:
  - DNS Name(s)  (E.g. cloudflare certificates)

To make resolving those issues easier, as you'll know what's going on.

**Comment by Ylianst** [comment]
The agent is seeing a TLS certificate that is different that then one one the server expects the agent to see. The CertUrl to point to a HTTPS URL where the server will see the same certificate that the agent will see. If you hit the CertUril from the server and hit the HTTPS url the agents use to connect to the server, you should see the same TLS cert. If you don't that is your problem.

Also, try running the server manually... when it starts up you should see the server loading the CertUrl and giving you the hash that is loaded. The should match the hash the agent sees.

A bad way to fix this is to add:

`"IgnoreAgentHashCheck": true`

in the settings section of config.json. Of course, the is super bad because someone can man-in-the-middle the agent connection.

**Comment by luckydonald** [comment]
I'm getting
```
MeshCentral HTTP redirection server running on port 443.
MeshCentral v0.2.6-v, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on meshcentral.bonbotics.io:4433.
MeshCentral HTTP server running on port 80.
Agent bad web cert hash (Agent:cfe5a40fc3 != Server:582e177d35 or 927f3d1b51), holding connection (172.18.0.7:51024).
```

`settings.json`:
```
{
    "__comment__": "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
    "settings": {
        "Port": 4430,
        "AliasPort": 443,
        "RedirPort": 80,
        "_notls": true,
        "TLSOffload": "proxy",
        "exactports": true,
        "cert": "meshcentral.bonbotics.io, EQ",
        "CertUrl": "https://meshcentral.bonbotics.io:443/",
        "_MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
        "_MongoDbCol": "meshcentral",
        "WANonly": true,
        "_LANonly": true,
        "_Minify": 1,
        "_SessionTime": 30,
        "_SessionKey": "MyReallySecretPassword",
        "_AllowLoginToken": true,
        "_AllowFraming": true,
        "_WebRTC": false,
        "_ClickOnce": false,
        "_SelfUpdate": true,
        "_UserAllowedIP": "127.0.0.1,::1,192.168.0.100",
        "_LocalDiscovery": {
            "name": "Local server name",
            "info": "Information about this server"
        },
        "_MpsTlsOffload": true,
        "_WebRtConfig": {
            "iceServers": [
                {
                    "urls": "stun:stun.services.mozilla.com"
                },
                {
                    "urls": "stun:stun.l.google.com:19302"
                }
            ]
        }
    },
    "domains": {
        "": {
            "title": "Lemme Mash!",
            "title2": "Becky!",
            "_TitlePicture": "title-sample.png",
            "UserQuota": 1048576,
            "MeshQuota": 248576,
            "NewAccounts": 0,
            "newAccounts": 0,
            "Footer": "Benis",
            "CertUrl": "https://meshcentral.bonbotics.io:443/",
            "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
            "_PasswordRequirements": {
                "min": 8,
                "max": 128,
                "upper": 1,
                "lower": 1,
                "numeric": 1,
                "nonalpha": 1
            }
        }
    },
    "_letsencrypt": {
        "email": "myemail@myserver.com ",
        "names": "myserver.com,customer1.myserver.com",
        "rsaKeySize": 3072,
        "production": false
    },
    "_peers": {
        "serverId": "server1",
        "servers": {
            "server1": {
                "url": "wss://192.168.2.133:443/"
            },
            "server2": {
                "url": "wss://192.168.1.106:443/"
            }
        }
    },
    "_smtp": {
        "host": "smtp.myserver.com",
        "port": 25,
        "from": "myemail@myserver.com",
        "tls": false
    }
}
```

**Comment by Ylianst** [comment]
Ok, I will take a look at this soon. Plenty of information here for me to do a bunch of testing.

**Comment by Ylianst** [comment]
So, the "CertUrl" in the settings section should do nothing. The "CertUrl" in the default domain should cause the server to load the certificate. But it's not even trying. Then I notice you are running "v0.2.6-v", that is super old. So old, I don't think "CertUrl" was supported in that version. Can you update to the latest and try again?

**Comment by Ylianst** [comment]
I am pretty sure the old server version had everything to do with the this issue. The next "npm install meshcentral" should fix it. I am going to close this, but feel free to re-open if needed.

**Comment by luckydonald** [comment]
That makes sense, must be the container having a old version preinstalled, to which it obviously reverts on restarts. Woops. I'll check.

**Comment by luckydonald** [comment]
Also the config file was not registering changes (i.e. a old value was kept in the docker volume), also see #160.
