### ISSUE TITLE
Mesh Agent Permissions on Mac after Update

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1461]
I'm sure this is related to the same security settings on Macs that prevent control from the login screen but just so it's documented, in my experience on Catalina at least, every time the agent is updated (e.g. after a server update), the screen recording and accessibility permissions have to be re-granted which adds a bit of hassle to supporting users remotely (especially when combined with the other current issue that the agent does not reconnect after a reboot).

**Comment by krayon007** [comment]
I'm working on the reboot issue...
The permissions thing, there really isn't much I can do about that. The biggest pain, is that there's a bug in the security preferences UI on macOS. The security preferences are keyed by the binary hash of the file, but the UI is keyed by the name of the binary, making it so on Catalina, the checkbox is already checked, so you have to uncheck it and recheck it... Pre-catalina, the prompt may not actually occur, unless you clear the settings first.

But like I said, I'm working on the reboot issue...

**Comment by PetieM** [comment]
Yeah, I figured it was something along those lines but wanted to put in the report regardless. I don't expect there will be much you can do to fix this one but at least I know why it behaves the way it does (with the requirement to uncheck and recheck) now.

**Comment by n9yty** [comment]
sorry if my other post was a duplicate of this, at least in terms of operation I think this clears up the other one, #1491 that I created.
