### ISSUE TITLE
TypeError: Cannot read property 'x-forwarded-for' of undefined After 0.5.54 Update

### ISSUE THREAD

**Issue by felipe4334** [Ylianst/MeshCentral#1463]
I"m getting "ERR: TypeError: Cannot read property 'x-forwarded-for' of undefined" error after updating to version 0.5.54 from version 0.5.52.

I'm currently running Meshcentral behind HAProxy, no configuration changed on server was updated through the web interface.

Is this a known issue?

Thanks.

**Comment by Ylianst** [comment]
I don't knwo about this one. Can you post the entire exception? It should be in "meshcentral-data/mesherrors.txt" - Thanks.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.55 with a fix that may work. However it would be nice to get the exact exception because it's a bit like shooting in the dark.

**Comment by felipe4334** [comment]
Thank you for the quick response Ylianst. 0.5.55 fixed the issue, thank you very much! :)
I'm sorry but I can't get the logs since I restored from a previous working snapshot.
Good job on this project! it's awesome!
