### ISSUE TITLE
User notification and consent does not work propelry through RDP

### ISSUE THREAD

**Issue by turin331** [Ylianst/MeshCentral#1464]
I was playing with the user consent/notifications and noticed that the notification or prompt does not come up when you try to take over an RDP session. Only the connection tool bar worked. On a non-remote session it seems to work as intended. Is this a glitch or perhaps i am missing a setting that should be on?

I am on version 0.5.32 and tested it on windows 10 pro 1909.  

Thanks!

**Comment by krayon007** [comment]
Please update your server. This was already fixed in v0.5.37

**Comment by turin331** [comment]
Ah right i see...thank you!
