### ISSUE TITLE
macOS: If display is off on laptop, only see black in Desktop view

### ISSUE THREAD

**Issue by n9yty** [Ylianst/MeshCentral#1465]
This may be an Apple issue, but thought I would report/document it.

If the laptop has turned it's screen off and I connect to the Desktop, I can hear indications it is receiving keystrokes/etc, but nothing I can do will wake the display up. If I use the newly added NoVNC it will wake up the display and then re-connecting to Desktop works. Also, if I open a terminal, I can use 'caffeinate -u -t 2' (for example) to simulate user activity which wakes up the display.

Test laptops are both 10.13.6 so I don't know if this problem exists on other macOS versions.

**Comment by krayon007** [comment]
Thanks for the heads up. I can add the caffeinate thing so that it is called automatically when the kvm session is connected.

**Comment by zaggynl** [comment]
On Monterey this no longer seems to work on connect, if I manually use "caffeinate -u -t 2" the screen shows briefly, if I increase the time to 20 I have enough time to type in my password.

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
