### ISSUE TITLE
Change notification message in meshcore.js

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#1468]
Hi, Ylianst

I would like to change the above phrase to Japanese. If I change it to English, it works fine. But when I change it to Japanese, I got a meshcore error, so the Desktop menu is not shown? Is there a way to solve it?
![image](https://user-images.githubusercontent.com/3539914/84125694-e0f1e200-aa77-11ea-81f4-3b96a29f924b.png)

Thanks in advance.

**Comment by krayon007** [comment]
I'll take a look at it

**Comment by hchkim** [comment]
Thank you :)

**Comment by krayon007** [comment]
This is fixed in v0.5.58 for Windows and Linux...  It will be in the next update for macOS.

**Comment by hchkim** [comment]
Thank you for updating.
I tested it after update. But it didn't work.

1. I upgraded meshcentral and I reinstall meshagent.

2. I changed message in meshcore.js to japanese.
![image](https://user-images.githubusercontent.com/3539914/84564017-d64a8c00-ad9a-11ea-935f-49d14c618010.png)

3. I updated meshcore.js to /agents/meshcore.js

4. I restarted meshcentral.

5. It doesn't show desktop/terminal menu on meshcentral.
![image](https://user-images.githubusercontent.com/3539914/84564007-b74bfa00-ad9a-11ea-940b-35cd1163f7cb.png)

How should I do to solve it?

**Comment by krayon007** [comment]
ok, I see the issue... I had fixed the method call, to support UTF-8 messages... But it looks like the problem you are seeing, is that the meshcore.js file was not loaded as a UTF-8 document, the Javascript file was getting corrupt.... I'll take a look at it in the morning...

**Comment by Ylianst** [comment]
Hi. Just published MeshCentral v0.5.60 with an official way to change the user consent messages. In the domain section of the config.json, add the new "consentMessages" section like this:

```
  "domains": {
    "": {
      "consentMessages": {
        "Desktop": "{0} requesting remote desktop access. Grant access?",
        "Terminal": "{0} requesting remote terminal access. Grant access?",
        "Files": "{0} requesting remote files access. Grant access?"
      }
  }
```

Make sure to save the config.json in "UTF8" format. You can edit the strings like you want and `{0}` will be replaced with the username that is making the request, but it is not required to use `{0}` in the string.

Let me know if this works.

**Comment by amenolo** [comment]
Like a charm!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.61 and you can now customize the consent prompt title and notification messages by adding this to the domain section of config.json:

```
      "consentMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} requesting remote desktop access. Grant access?",
        "Terminal": "{0} requesting remote terminal access. Grant access?",
        "Files": "{0} requesting remote files access. Grant access?"
      },
      "notificationMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} started a remote desktop session.",
        "Terminal": "{0} started a remote terminal session.",
        "Files": "{0} started a remote files session."
      }
```

This would make everyone happy :)

**Comment by amenolo** [comment]
Uhm...how are `notificationMessages` supposed to be displayed?

I guess in the same way of this one...

![immagine](https://user-images.githubusercontent.com/29974944/84579166-12e2ab80-adcc-11ea-9621-55de8e7fe32c.png) ![immagine](https://user-images.githubusercontent.com/29974944/84579101-7d471c00-adcb-11ea-98b6-61f19e30b7e5.png)

...anyway nothing happens...what am I missing? :confused:

**Comment by Ylianst** [comment]
In user consent options, enable "Notify User"

![image](https://user-images.githubusercontent.com/1319013/84579298-7b586b00-ad81-11ea-898f-3a7f27699c56.png)

**Comment by amenolo** [comment]
Wasn't so hard to get there...my bad, sorry :flushed:

**Comment by krayon007** [comment]
Also, on windows, (at least with Windows 10), if you have any apps running fullscreen, toast notifications are blocked by the OS, until you exit out of your fullscreen app.... Personally, I found it quite annoying, because I had the fullscreen app on a secondary monitor, but Windows still blocked all toast notifications...

**Comment by hchkim** [comment]
It works well. 
Thank you for all :)

**Comment by kpetrow** [comment]
> Also, on windows, (at least with Windows 10), if you have any apps running fullscreen, toast notifications are blocked by the OS, until you exit out of your fullscreen app.... Personally, I found it quite annoying, because I had the fullscreen app on a secondary monitor, but Windows still blocked all toast notifications...

This is a setting in windows "Focus Assist" =? "When I'm using an app in full screen mode" => Off. Wil allow the message through
