### ISSUE TITLE
Updating Meshcentral error

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#1475]
![Capture](https://user-images.githubusercontent.com/50190618/84327172-04c13f00-abc2-11ea-9ae6-0b55c989700b.PNG)

Currently running Meshcentral version 5.33 want to update it to the latest but not to sure how to.
any help would be appreciated

**Comment by Ylianst** [comment]
So, this is not really a MeshCentral problem, NPM can't connect to the npmjs.com server. Not sure what is going on. Note that instead of "npm update", I use "npm install" even over an existing installation. One idea with to do this:

```
mv node_modules node_modules_back
npm install meshcentral
```

This will re-install from fresh including all dependencies. This said, if "npm install" does not work, check your network connectivity.

**Comment by haxmachine** [comment]
I must say Meshcentral is fantastic and your work is amazing on it.
will the install wipe out my current configurations or agents that report back?

and thank you for your swift response

**Comment by haxmachine** [comment]
is there a way internally meshcentral can update itself example passing a command in the console?

**Comment by haxmachine** [comment]
error after running the commands you suggested 
![image](https://user-images.githubusercontent.com/50190618/84328205-ac3f7100-abc4-11ea-9bc0-60aefe17cbc6.png)

**Comment by Ylianst** [comment]
As long as you have a a copy of "meshcentral-data" and if you use MongoDB, a copy of your database, you should fine. Take this opportunity to backup "meshcentral-data" and put it on a different secure location, it's always a good thing to do.

Once you run 'npm install meshcentral' and run MeshCentral again, if there is already a "meshcentral-data", it will just use that. It will not start over.

**Comment by haxmachine** [comment]
Thanks ill see how i go 👍

**Comment by haxmachine** [comment]
this is where im at the moment
![image](https://user-images.githubusercontent.com/50190618/84329977-75b82500-abc9-11ea-8740-b0fbe1691ccd.png)

**Comment by Ylianst** [comment]
It does not look like you have network access, not sure if this is something I can help with. I guess you could try `ping npnjs.org` and see if you get a response back. This said, I don't know the details of your setup and a lot of things could be blocking your network access.

**Comment by haxmachine** [comment]
if i just do a fresh install of Meshcentral where can i get the latest build?
also is there a files or files i need to copy back in to keep my previous config and agents will reconnect

**Comment by Ylianst** [comment]
MeshCentral is distributed thru NPM, you can get the latest version by typing:

```
npm install meshcentral
```

You can also get a previous version by specifying the version like this:

```
npm install meshcentral@0.5.11
```

Once you install MeshCentral, you need to copy the "meshcentral-data" folder back to get all the old server settings. It's always a good idea to keep a backup of the "meshcentral-data" folder.

**Comment by haxmachine** [comment]
ill give it a crack, thank you for any help you provide.
i really appreciate it

**Comment by haxmachine** [comment]
using the npm install meshcentral@0.5.11 
worked and now running the latest build
