### ISSUE TITLE
Wish: device location tracking(notebooks, macbooks)

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#1476]
It would be cool to track the device on the map. It seems like Windows allows.

**Comment by Ylianst** [comment]
In the domain section of config.json you can add this:

```
"GeoLocation": true
```

It will add a new tab with OpenStreetMaps map. This said, I am not doing any development on this feature right now and don't expect it anytime soon. One problem with this feature is that there is some issues with location tracking of devices and generally has organizations avoid this feature.
