### ISSUE TITLE
Translate MeshCentral Router

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1478]
![Screenshot_33](https://user-images.githubusercontent.com/58996467/84366711-8077b780-abd3-11ea-8ab4-fb4f3d5865c9.jpg)

**Comment by Ylianst** [comment]
So in general, all of MeshCentral Router is not translated yet, not just that part.

**Comment by petervanv** [comment]
I did notice that, it was only too complete the meshcentral web interface.

**Comment by Ylianst** [comment]
I got the first version of MeshCentral Router that is internationalized to many languages. You can get is here: [http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.zip](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.zip)

![image](https://user-images.githubusercontent.com/1319013/84559183-78ac3600-aced-11ea-81fd-e5cebde9de15.png)

The translation file is here: [https://github.com/Ylianst/MeshCentralRouter/blob/master/MeshCentralRouter-translation.json](https://github.com/Ylianst/MeshCentralRouter/blob/master/MeshCentralRouter-translation.json)
