### ISSUE TITLE
Blank page after update

### ISSUE THREAD

**Issue by Julien-asv** [Ylianst/MeshCentral#1480]
Hi,
I didn't had the time to make a full feedback of Meshcentral, that i discoverd some weeks ago (i have some issues with chat, recorded session not working or user authorization validation is sometimes reverse). 
But for now i need your help. 
I have build 2 Meshcentral servers on 2 separates networks at my work, and i have on both some issues with the windows 10 agent, it work when i install them, but some times after, computers are offline.
So i update one server just now, after i found the isses 556, i updated it from the dashboard, and now i have a blank page ... i have the login page, but after i log in, i have nothing, just a blank page.
I have restarted the server (Ubuntu 20.04) it didn't change anything, can you help me ? 

thank you.

**Comment by tranbert** [comment]
Hop, update and poof !  Wihte blank screen after connexion...

**Comment by tranbert** [comment]
Back to 5.55 via sudo npm install meshcentral@0.5.55 

OK 5.55

**Comment by Ylianst** [comment]
Looking into this now. What language are you using and are you using minified web pages?

**Comment by tranbert** [comment]
For me; french... Minified ? No i don't think so :-)

**Comment by Ylianst** [comment]
Working on a fix for this. If you ever see a white page, you can add `?lang=en` to the URL to force the English page as a temporary fix.

Also, if you open the browser console, you will typically see an error like this:

![image](https://user-images.githubusercontent.com/1319013/84418891-aa79ab80-abcc-11ea-92fc-1efddb17c55f.png)

In this case, I got a new French translation and it broke a few things. Fixing it now.

**Comment by tranbert** [comment]
Ok  I'll test a new upgrade when you tell me to do so..

Thank's

I'ts time to take a snapshot :-)

**Comment by tranbert** [comment]
Yep

![Capture](https://user-images.githubusercontent.com/9928216/84422363-36b3bf00-ac1d-11ea-8d29-3e022cad4b1b.PNG)

**Comment by laboiteajb** [comment]
The update corrected the problem for me thank you for your speed

**Comment by Julien-asv** [comment]
Hi, i rollback to 0.5.55 with the command line, and i update to 0.5.58 from the dashboard, and it's working. Thank you for your reactivity (I am french too).

**Comment by Ylianst** [comment]
Thanks. Yes, it was a problem with the french translation. Closing this.
