### ISSUE TITLE
big wish: popup note after a session -> like teamviewer comment...

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#1481]
good morning @all, near perfect remote help solution. i miss only one thing ;-) bevor a long time we have discuss this. (09.10.2019) but nothing read since there about this, or im to stupid to found it ;-) whe i make a job with teamviewer, i receive a comment text box when im finish this job. in this box i write what i have make for this client. in a spezial log file this information are stored for make the bill later. it is possible to make this also with meshcentral? could this be improved with functions like checkboxes. e.g. for recurring jobs, so that you can create standard jobs with just a few clicks? thanks for all, this is a real great software!

**Comment by krayon007** [comment]
Is this comment box server side or client side? (ie, would it pop up on the mesh central ui for a given device, or would it pop up on the agent side?)

**Comment by Ylianst** [comment]
Also, if any screen shots can be provided, that would be great. Thanks.

**Comment by wvt-adm** [comment]
good morning @ALL, this is on "server side" -> when i press the DISCONNECT button under Desktop, make open this comment box. 
![tv-comment](https://user-images.githubusercontent.com/56296924/84477102-67ccd780-ac8f-11ea-961e-74cc6893257d.PNG) 
and when its end of the month, i export this entrys to my excel and make the bills to the clients - locks like this: 
![tv-comment1](https://user-images.githubusercontent.com/56296924/84477391-d3af4000-ac8f-11ea-83a7-78e64ee3a40a.PNG)

-> nice when i can activate / deactivate this comment box for every machine, because we have a lot of internal machines, and for this we dont make a bill ;-)
-> also nice, in the screenshot written: the 5 or more checkboxes with customable template text 

thanks a lot for your time!

am

**Comment by Ylianst** [comment]
I just published MeshCentral v0.5.61 with improvements to UI customization. To try it out, add the following in the domain section of the config.json:

```
  "domains": {
    "": {
      "_customui": {
        "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
        },
        "deviceButtons": {
          "exec4": {
            "name": "Execute4",
            "action": "dialog:dialog1"
          }
        },
        "desktopButtons": {
          "exec5": {
            "name": "Execute5",
            "action": "dialog:dialog1"
          }
        },
        "terminalButtons": {
          "exec6": {
            "name": "Execute6",
            "action": "dialog:dialog1"
          }
        },
        "filesButtons": {
          "exec7": {
            "name": "Execute7",
            "action": "dialog:dialog1"
          }
        },
        "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",
            "title": "This is the title",
            "text": "This is some test",
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Sample1",
                "type": "text"
              },
              "test2": {
                "_name": "Sample2",
                "type": "textarea"
              },
              "test3": {
                "name": "Sample2",
                "type": "droplist",
                "options": {
                  "1": "Option1",
                  "2": "Option2",
                  "3": "Option3",
                  "4": "Option4"
                }
              }
            }
          }
        }
      }
    }
  }
  ```

This will add buttons at various places in the MeshCentral user interface and add a custom dialog box that you can enter values and it will log it.

![MC2-CustomUI1](https://user-images.githubusercontent.com/1319013/84578227-3c71e780-ad78-11ea-92df-eb7ae915b618.png)

It will also add buttons in the device, desktop, terminal and files tab. if that works for you, I will need to add a "meshctrl.js" command to pull all of the "customui" events for the last month from the MeshCentral event logs.

Feedback appreciated.

**Comment by wvt-adm** [comment]
good morning ylianst

thanks for your work! i have put in the config.json under the domain section this, but i dont see the change… what i make wrong? (the server is under


    "domains": {
     "": {
         "title": "titel",
         "footer": "footer",
          "geolocation": true
          },
     "_customui": {
         "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
         },
         "deviceButtons": {
          "exec4": {
            "name": "Execute4",
            "action": "dialog:dialog1"
          }
         },
         "desktopButtons": {
          "exec5": {
            "name": "Execute5",
            "action": "dialog:dialog1"
          }
        },
         "terminalButtons": {
          "exec6": {
            "name": "Execute6",
            "action": "dialog:dialog1"
          }
         },
         "filesButtons": {
          "exec7": {
            "name": "Execute7",
            "action": "dialog:dialog1"
          }
         },
         "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",
            "title": "This is the title",
            "text": "This is some test",
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Sample1",
                "type": "text"
              },
              "test2": {
                "_name": "Sample2",
                "type": "textarea"
              },
              "test3": {
                "name": "Sample2",
                "type": "droplist",
                "options": {
                  "1": "Option1",
                  "2": "Option2",
                  "3": "Option3",
                  "4": "Option4"
                }
              }
            }
          }
        }
      }
    },

­­­­­­­­­­­­­­­­­­­­­­­
[cid:image001.png@01D641F1.BE0B6570]

[cid:image002.png@01D641F1.C8F19E50]

with best regards and thanks

am


Von: Ylian Saint-Hilaire <notifications@github.com>
Gesendet: Samstag, 13. Juni 2020 22:19
An: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ylianst/MeshCentral] big wish: popup note after a session -> like teamviewer comment... (#1481)


I just published MeshCentral v0.5.61 with improvements to UI customization. To try it out, add the following in the domain section of the config.json:

  "domains": {

    "": {

      "_customui": {

        "devicesBarButtons": {

          "exec1": {

            "name": "Execute1",

            "action": "event",

            "logmsg": "Button 1 pressed"

          },

          "exec2": {

            "name": "Execute2",

            "selection": "one",

            "action": "event",

            "logmsg": "Button 2 pressed"

          },

          "exec3": {

            "name": "Execute3",

            "selection": "many",

            "action": "dialog:dialog1"

          }

        },

        "deviceButtons": {

          "exec4": {

            "name": "Execute4",

            "action": "dialog:dialog1"

          }

        },

        "desktopButtons": {

          "exec5": {

            "name": "Execute5",

            "action": "dialog:dialog1"

          }

        },

        "terminalButtons": {

          "exec6": {

            "name": "Execute6",

            "action": "dialog:dialog1"

          }

        },

        "filesButtons": {

          "exec7": {

            "name": "Execute7",

            "action": "dialog:dialog1"

          }

        },

        "dialogs": {

          "dialog1": {

            "logmsg": "Dialog 1 filled",

            "title": "This is the title",

            "text": "This is some test",

            "buttons": 3,

            "elements": {

              "test1": {

                "name": "Sample1",

                "type": "text"

              },

              "test2": {

                "_name": "Sample2",

                "type": "textarea"

              },

              "test3": {

                "name": "Sample2",

                "type": "droplist",

                "options": {

                  "1": "Option1",

                  "2": "Option2",

                  "3": "Option3",

                  "4": "Option4"

                }

              }

            }

          }

        }

      }

    }

  }

This will add buttons at various places in the MeshCentral user interface and add a custom dialog box that you can enter values and it will log it.

[MC2-CustomUI1]<https://user-images.githubusercontent.com/1319013/84578227-3c71e780-ad78-11ea-92df-eb7ae915b618.png>

It will also add buttons in the device, desktop, terminal and files tab. if that works for you, I will need to add a "meshctrl.js" command to pull all of the "customui" events for the last month from the MeshCentral event logs.

Feedback appreciated.

**Comment by Ylianst** [comment]
You know that placing a underscore "_" in front any any name of section will cause it to be ignored?

**Comment by wvt-adm** [comment]
… now -> yes… thanks,

the change i dont see, but in the cmd node meshcentral i see the following line :

server customui has no user, next new account will be the site administrator


  *   i have make a new user, but this line persist

thanks for help

and best regards

am


Von: Ylian Saint-Hilaire <notifications@github.com>
Gesendet: Sonntag, 14. Juni 2020 02:52
An: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ylianst/MeshCentral] big wish: popup note after a session -> like teamviewer comment... (#1481)


You know that placing a underscore "_" in front any any name of section will cause it to be ignored?

**Comment by Ylianst** [comment]
If you look at my example closely, the "customui" section is within the defauit domain section, like this:

```
  "domains": {
    "": {
      "customui": {
        ...
      }
    }
  }
```

You put the "customui" section like if it was a second domain, this is not right.

**Comment by wvt-adm** [comment]
good morning ylianst

sorry – your hint i have understand, but it will not work, im shure i make it wrong, but i dont understand where… 😉

so i put you my config here in – hope you have time to help me -> thanks for all!


{
   "settings":                       {
                               "cert": "name.domain.tld",
                               "wanonly": true,
                               "_minify": true,
                               "selfupdate": true,
                               "Port": 443,
                               "RedirPort": 80,
                               "AgentPing": 60,
                               "AgentPong": 60,
                               "AllowHighQualityDesktop": true,
                                               "autobackup": {
                                                               "backupIntervalHours": 24,
                                                               "keepLastDaysBackup": 10,
                                                               "zipPassword": "Just4F3$",
                                                               "backupPath": "E:\\BACKUP"
                                               }
                },
                "letsencrypt":    {
                               "email": "name@domain.tld",
                               "names": " name.domain.tld",
                               "rsaKeySize": 3072,
                               "production": true
                },
    "domains": {
                               "": {
         "title": " name.domain.tld",
         "footer": "firm",
"geolocation": true,
                                               "devicesBarButtons": {
                                                               "exec1": {
                                                                               "name": "Execute1",
                                                                               "action": "event",
                                                                               "logmsg": "Button 1 pressed"
                                                               },
                                                               "exec2": {
                                                                               "name": "Execute2",
                                                                               "selection": "one",
                                                                               "action": "event",
                                                                               "logmsg": "Button 2 pressed"
                                                               },
                                                               "exec3": {
                                                                               "name": "Execute3",
                                                                               "selection": "many",
                                                                               "action": "dialog:dialog1"
                                                                               }
                                                               },
                                                               "deviceButtons": {
                                                               "exec4": {
                                                                               "name": "Execute4",
                                                                               "action": "dialog:dialog1"
                                                                               }
                                                               },
                                                               "desktopButtons": {
                                                               "exec5": {
                                                                               "name": "Execute5",
                                                                               "action": "dialog:dialog1"
                                                                               }
                                                               },
                                                               "terminalButtons": {
                                                               "exec6": {
                                                                               "name": "Execute6",
                                                                               "action": "dialog:dialog1"
                                                                               }
                                                               },
                                                               "filesButtons": {
                                                               "exec7": {
                                                                               "name": "Execute7",
                                                                               "action": "dialog:dialog1"
                                                                               }
                                                               },
                                                               "dialogs": {
                                                               "dialog1": {
                                                                               "logmsg": "Dialog 1 filled",
                                                                               "title": "This is the title",
                                                                               "text": "This is some test",
                                                                               "buttons": 3,
                                                                               "elements": {
                                                                                              "test1": {
                                                                                                              "name": "Sample1",
                                                                                                              "type": "text"
                                                                               },
                                                                               "test2": {
                                                                                              "_name": "Sample2",
                                                                                              "type": "textarea"
                                                                               },
                                                                               "test3": {
                                                                                              "name": "Sample2",
                                                                                              "type": "droplist",
                                                                                              "options": {
                                                                                                              "1": "Option1",
                                                                                                              "2": "Option2",
                                                                                                              "3": "Option3",
                                                                                                              "4": "Option4"
                                                                                                              }
                                                                                              }
                                                                               }
                                                               }
                                               }
                               }
                },
   "smtp": {
                               "host": "ipfromhost",
                               "port": 25,
                               "from": " name@domain.tld“,
                               "user": " name@domain.tld",
                               "pass": "password",
                               "tlscertcheck": false,
                               "tls": false
                }
}


Von: Ylian Saint-Hilaire <notifications@github.com>
Gesendet: Sonntag, 14. Juni 2020 09:11
An: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Cc: wvt-adm <fws@wvtnet.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ylianst/MeshCentral] big wish: popup note after a session -> like teamviewer comment... (#1481)


If you look at my example closely, the "customui" section is within the defauit domain section, like this:

  "domains": {

    "": {

      "customui": {

        ...

      }

    }

  }

You put the "customui" section like if it was a second domain, this is not right.

**Comment by Ylianst** [comment]
Here is the corrected config.json. However, this is a sample of how you can customize MeshCentral by adding user interface elements. If you are not familiar with JSON, this is not going to be good for you.

```
{
  "settings": {
    "cert": "name.domain.tld",
    "wanonly": true,
    "_minify": true,
    "selfupdate": true,
    "Port": 443,
    "RedirPort": 80,
    "AgentPing": 60,
    "AgentPong": 60,
    "AllowHighQualityDesktop": true,
    "autobackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "zipPassword": "Just4F3$",
      "backupPath": "E:\\BACKUP"
    }
  },
  "letsencrypt": {
    "email": "name@domain.tld",
    "names": " name.domain.tld",
    "rsaKeySize": 3072,
    "production": true
  },
  "domains": {
    "": {
      "title": " name.domain.tld",
      "footer": "firm",
      "geolocation": true,
      "customui": {
        "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
        },
        "deviceButtons": {
          "exec4": {
            "name": "Execute4",
            "action": "dialog:dialog1"
          }
        },
        "desktopButtons": {
          "exec5": {
            "name": "Execute5",
            "action": "dialog:dialog1"
          }
        },
        "terminalButtons": {
          "exec6": {
            "name": "Execute6",
            "action": "dialog:dialog1"
          }
        },
        "filesButtons": {
          "exec7": {
            "name": "Execute7",
            "action": "dialog:dialog1"
          }
        },
        "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",
            "title": "This is the title",
            "text": "This is some test",
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Sample1",
                "type": "text"
              },
              "test2": {
                "_name": "Sample2",
                "type": "textarea"
              },
              "test3": {
                "name": "Sample2",
                "type": "droplist",
                "options": {
                  "1": "Option1",
                  "2": "Option2",
                  "3": "Option3",
                  "4": "Option4"
                }
              }
            }
          }
        }
      }
    }
  },
  "smtp": {
    "host": "ipfromhost",
    "port": 25,
    "from": "name@domain.tld",
    "user": "name@domain.tld",
    "pass": "password",
    "tlscertcheck": false,
    "tls": false
  }
}
```

**Comment by wvt-adm** [comment]
good morning ylianst

thanks a lot for your real fast help and work. now it works!
and I saw my mistake... ;-)
two three questions:
1.. What are the three execute1/2/3 for?
2. I rewrote the buttons at desktop / terminal & files, so that they correspond approximately to what I meant.
3. the templates I have recorded
4. is it possible to automatically fill the title of desktop / terminal & files with the remote maintenance you just did?
thank you very much for your great effort!


        "customui": {
        "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
        },
        "deviceButtons": {
          "exec4": {
            "name": "Accounting",
            "action": "dialog:dialog1"
          }
        },
        "desktopButtons": {
          "exec5": {
            "name": "Desktop Accounting",
            "action": "dialog:dialog1"
          }
        },
        "terminalButtons": {
          "exec6": {
            "name": "Terminal Accounting",
            "action": "dialog:dialog1"
          }
        },
        "filesButtons": {
          "exec7": {
            "name": "File Accounting",
            "action": "dialog:dialog1"
          }
        },
        "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",
            "title": "connection accounting",
            "text": "note down your work",
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Titel",
                "type": "text"
              },
              "test2": {
                "_name": "Text",
                "type": "textarea"
              },
              "test3": {
                "name": "Template",
                "type": "droplist",
                "options": {
                  "1": "Windows Updates",
                  "2": "Application Updates",
                  "3": "Maintenance",
                  "4": "Restore from Backup"
                }
              }
            }
          }
        }
      }
    }
  },

**Comment by Ylianst** [comment]
1. What are the three execute1/2/3 for?

There are 3 buttons on the "devices" tab, you can remove them if you don't need them.

4. is it possible to automatically fill the title of desktop / terminal & files with the remote maintenance you just did?

I don't understand the question. When you click OK on the dialog, the NodeID of the device you are on will be recorded as part of the event.

**Comment by wvt-adm** [comment]
if i click the button "desktop accounting" after a remote maintenance, the following should be entered in the log: 1. computer/customer name 2. date, 3. time, 4. duration, 5. description which i enter manually or via a template. 

at the end of the month the secretary should be able to export a log with exactly these data. 

in the export i can see that i can export the last 1000 events, but it contains the complete log from the server. would it be possible to have a separate export for billing?

it would be even more elegant if the server would automatically trigger this by mail at the end of the month...

thanks a lot for the great work!

best regards

am

**Comment by wvt-adm** [comment]
good morning @all, can you show me how to export the protocol so that I receive the following information e.g. via csv: client name, date, duration, note etc. thanks in advance best regards am

**Comment by wvt-adm** [comment]
good morning @ALL, can you show me how to export the protocol so that I receive the following information e.g. via csv: client name, date, duration, note etc. thanks in advance best regards am

**Comment by MatinatorX** [comment]
Sorry for digging up an old issue, but I wanted to ask if any other actions are supported for these buttons besides logging. I was poking around to see if I could make a deviceBarButton that would download a file from the server, or do the same thing as one of those fancy meshrouter quick map links on device pages.

**Comment by smartekIT** [comment]
hi @Ylianst 
in your example for each button you have action value, what is the possible values we could use there?
also under the dialog section you have type values as: text, textarea and droplist. any other possible values?
also in the dialog section where the options values, can you list possible values we could use?

it would be so nice and I believe this opens lots of customizations to people if we have all the possible values documented which will of course lead to new options implementation by admins and who knows news ideas and suggestions.
thanks heaps.

**Comment by si458** [comment]
you can also follow the sample plugin here https://github.com/ryanblenis/MeshCentral-Sample/tree/master
this simply pops up the 'make a note' tab after you disconnect from a computer to make notes,
the notes then get saved in the 'My Events' tab
