### ISSUE TITLE
Any thought of making a MeshAgent for Mac OS that is only a client

### ISSUE THREAD

**Issue by formanjackj** [Ylianst/MeshCentral#1482]
Ideal with a few independent lawyers that I try to help out.
Due to privacy and security concerns, the Windows is a client is perfect.
I was hoping, and asking if this possible to do a client only for Mac OS

**Comment by krayon007** [comment]
I'm not sure I understand your request, as the Windows and macOS agent share a code base, so have nearly identical features.

**Comment by formanjackj** [comment]
In the Windows version of the Mesh Agent you can select the installation type background, interactive, or background and interactive. If the agent is created as background and interactive, when you run the install you have a choice across the bottom is install/update, uninstall, or connect.

In the Mac OS version you do not have a type of install selection, and when you run install package, you not given any selections at all it just installs in the background as a service.

When I say as a client only, I guess I'm looking for the same thing as a connect button during startup.

**Comment by formanjackj** [comment]
My error hit the wrong button I had no intention to close this

**Comment by krayon007** [comment]
Oh ok, I see... The only difference in this case, is that the Windows Installer dialog is part of the binary. macOS uses the package interface to install the service...  If you run the binary directly, you can run the agent on macOS as client only... I'll have to think of a good way to offer that option, because I don't think the traditional mac installer package framework had that use case in mind. I'm thinking I can do something like that with some embedded Apple Script or something... I'll have to think about it...

**Comment by formanjackj** [comment]
Whatever happened to this request for a Mac OS agent that would not install and only connect.

**Comment by krayon007** [comment]
> Whatever happened to this request for a Mac OS agent that would not install and only connect.

It's actually already deployed... If you go to add an agent, select the binary installer, for linux, macos, freebsd, and select osx x86-64.

That binary, when you run it will present a UI.. Depending on the server configuration, you can Install/Update, or Connect.... The server can be configured so this will only allow connect, as you mentioned earlier. @Ylianst can probably step in with details for what configuration on the server controls this...

**Comment by tootai** [comment]
Hi. I try to install meshagent on a Macbook pro early 2013 running Catalina 10.15.7 and can't get it work. From waht I read I have to install meshagent binary for /Linux/Bsd/Mac os and not Apple MacOs one: true ?
After downloading the binary to the Mac (Desktop) I open Terminal and run "sudo /Users/<myUser>/Desktop/meshagent" I'm asked for the password and after this nothing: terminal window stay indefinitely open and nothing happend.
What am I doing wrong ?
-- Daniel

**Comment by tootai** [comment]
Up: after choosing /Linux/Bsd/Mac os I selected type Apple OSX Universal

**Comment by krayon007** [comment]
Are you trying to install from a console terminal, or from an SSH terminal?  If you downloaded the binary installer, you can try to run it this way:

`sudo /Users/Desktop/meshagent -install`
or for a list of supported commands
`sudo /Users/Desktop/meshagent -help`

**Comment by tootai** [comment]
I tried from a console terminal. The path is /Users/<myUser>/Desktop if relevant. The meshagent -help showned only -connect -fulluninstall and -help

**Comment by tootai** [comment]
Hi. Is there a way to run meshagent on demand using applescript ? I got it by creating a .sh script on the desktop, but that's not a proper way (and look)

**Comment by tootai** [comment]
Le 29/03/2021 à 19:21, Bryan Roe a écrit :
>
> Are you trying to install from a console terminal, or from an SSH 
> terminal? If you downloaded the binary installer, you can try to run 
> it this way:
>
> |sudo /Users/Desktop/meshagent -install|
> or for a list of supported commands
> |sudo /Users/Desktop/meshagent -help|
>
|Finally I created a command script that I installed in Finder => 
Applications => Utilities. The user launch the script and can get help. 
Small problem, I couldn't get the terminal windows closed automatically 
and the end of the session, but that's OK.|

|Thanks for your support
|

|--
Daniel
|

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
