### ISSUE TITLE
Problem when Installing meshagent to Opnsense

### ISSUE THREAD

**Issue by Novum2025** [Ylianst/MeshCentral#1484]
At the moment I am trying to add an Opnsense Maschine to our meshcentral. But I am having issues. The installation goes through fine and that Status of the Service is running but the Device is not showing up in our meshcentral.

Here you can see the Installation runs without any errors (The Redacted parts are the Domain and IP):
![Meshagent Installing Opnsense](https://user-images.githubusercontent.com/33344390/84515923-64f0d780-accd-11ea-8b8c-29ee880c06a1.png)

And here is the status of the Service:
![Status of Meshagent](https://user-images.githubusercontent.com/33344390/84516008-7df98880-accd-11ea-8760-8739c9ada2b6.png)

**Comment by krayon007** [comment]
One thing I noticed about OPNsense, that I saw posted in the forums too, is that the DNS on it doesn't work well. I saw on the forums it said that many times when you try to connect to a dns name, it will fail to resolve the first time... But if you try a second time it will work... So I noticed that with the agent, it may fail to resolve the server host name the first time.

Try doing: service meshagent restart

and see if that helps... I'll double check the logic to make sure the agent will retry if the DNS resolve fails. The agent will cache DNS results for cases where the resolve fails but it has already resolved before, but I can't remember if it will retry if the dns has never resolved before...

**Comment by krayon007** [comment]
Although, if you downloaded from the server the install script, the dns name probably already resolved... Try going to the /usr/local/mesh_services/meshagent folder and see if there is a .db and .log file.

You are running server version 0.5.58, yes? Versions prior to that, the BSD binary was compiled on freebsd 12, which will not run on OPNsense, but the 0.5.58 version and newer, I compiled them with freebsd 11.2, which I tested runs on my OPNsense VM.

**Comment by Novum2025** [comment]
I appreciate you wrote back so swiftly. The Problem with connecting Our Opnsense Machine was due to our old Version we had 0.5.36. After the Update I uninstalled, then reinstalled the meshagent and it the Opnsense was connected.

Thanks Again for the Quick response
