### ISSUE TITLE
Re-login causes agent to crash

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1485]
MC v.0.5.58 and Windows 10 VM guest ~with TightVNC server installed on and properly set up to accept loopback connections: noVNC runs fine except when I log in guest machine after prior logged out, in that case agent abruptly crashes.~

Agent log reports

`[2020-06-12 11:28:56 PM] FATAL EXCEPTION [MeshAgent_E5537759C5BF0079.exe] @ [FuncAddr: 0x00007ff77f0d9eda / BaseAddr: 0x00007ff77f0d0f1c / Delta: -36798]`

Let me know if you want more tests, thanks.

ps. BTW after a bunch of crashes I had to reinstall agent from scratch in order to get remote desktop fully functional again (otherwise was stuck in `setup` stage) and I noticed this warning in its log's very first line: `Info: No certificate was found in db`...never saw before, as far as I can tell...server side nothing changed, any hint?

**Comment by krayon007** [comment]
Can you get me a crash dump?
As far as the setup stuck thing, that is actually a browser issue. If you hit the refresh page, it should resolve. There is a one hour timeout on the session cookie. After an hour, the tunnel will fail to connect because of the stale cookie. Ylian said he fixed this issue, not sure which version.

**Comment by krayon007** [comment]
The certificate thing is normal. I was logging every case that would cause the agents NodeID to change. So I could try to figure out why some people were seeing duplicate agents after a windows update.

**Comment by amenolo** [comment]
> Can you get me a crash dump?

I could use a little hand here: how can get it in the easy way?

> If you hit the refresh page, it should resolve.

Oh, I see...to be honest didn't seem that way to me...anyway next time I'll give one more try!

> The certificate thing is normal.

So be it, thanks.

**Comment by krayon007** [comment]
It's ok, I figured it out... It was actually unrelated to noVNC. It happened if you were connected with KVM and logged out... There was a NULL exception when it was trying to update the metadata for the process when it was switching to the logon process... I just fixed it... It will be in the next update

**Comment by krayon007** [comment]
As far as the browser, a couple times, chrome seems to keep some things cached, so I had to close the browser and re-open it... But Ylian says he has a fix for these things

**Comment by amenolo** [comment]
> It was actually unrelated to noVNC. It happened if you were connected with KVM and logged out

Now that you pointed it out, I tried again and...you're absolutely right, I was fooled by encountering the error while using noVNC...

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.59 with Bryan's all new MeshAgents. Should fix this, let us know if it works.

**Comment by amenolo** [comment]
Guys you nailed it again! Going to close this one, thanks!
