### ISSUE TITLE
How to give custom path during Mesh Agent full installation

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1486]
How to give custom path during Mesh Agent full installation in command line.

**Comment by krayon007** [comment]
Which OS are you installing on? If on windows, you specify:
MeshAgent -fullinstall --installPath="Your\\\\Custom\\\\Path"

Right now, specifying a custom path is only supported on Windows, becuase Linux/MacOS/FreeBSD has filesystem permission issues that could prevent the agent from functioning correctly if you install the agent into a folder or mounted file system with the improper characteristics. 

Also, make sure the backslashes are escaped.. There should be double backslashes... I had to escape the text above to it would show correctly on this html post... If you are reading this on email, it will probably show 4 backslashes, but it should be 2...

**Comment by krayon007** [comment]
And just for clarity, the path specified above is the path for the folder of where the binary will be installed.

**Comment by aimdharma1990** [comment]
> Which OS are you installing on? If on windows, you specify:
> MeshAgent -fullinstall --installPath="Your\\Custom\\Path"
> 
> Right now, specifying a custom path is only supported on Windows, becuase Linux/MacOS/FreeBSD has filesystem permission issues that could prevent the agent from functioning correctly if you install the agent into a folder or mounted file system with the improper characteristics.
> 
> Also, make sure the backslashes are escaped.. There should be double backslashes... I had to escape the text above to it would show correctly on this html post... If you are reading this on email, it will probably show 4 backslashes, but it should be 2...

Hi, 

Thanks for your reply. 

I have tried with following but getting the error

Command : meshagent32-SAPP.exe -fullinstall --installPath="C:\Program Files (x86)\XYZ\MeshAgent"

**"SyntaxError: invalid json (at offset 22)"**

**Comment by krayon007** [comment]
You need to escape the backslashes.

**Comment by Ylianst** [comment]
You must do:

`meshagent32-SAPP.exe -fullinstall --installPath="C:\\Program Files (x86)\\XYZ\\MeshAgent"`

**Comment by aimdharma1990** [comment]
Thanks, it's working now after changing to \\.

**Comment by rainbow-james** [comment]
Hi, 

How to run this line meshagent32-SAPP.exe -fullinstall --installPath="C:\\Program Files (x86)\\XYZ\\MeshAgent" in .bat file on Windows?

ive tried to run on .bat file: 
start meshagent32-SAPP.exe -fullinstall --installPath="C:\\Program Files (x86)\\XYZ\\MeshAgent"

but seems this line is not executed. There is no Meshagent folder created and no mesh agent install installed.

**Comment by rainbow-james** [comment]
> Hi,
> 
> How to run this line meshagent32-SAPP.exe -fullinstall --installPath="C:\Program Files (x86)\XYZ\MeshAgent" in .bat file on Windows?
> 
> ive tried to run on .bat file:
> start meshagent32-SAPP.exe -fullinstall --installPath="C:\Program Files (x86)\XYZ\MeshAgent"
> 
> but seems this line is not executed. There is no Meshagent folder created and no mesh agent install installed.

https://github.com/Ylianst/MeshCentral/issues/1486#issuecomment-643671819

**Comment by krayon007** [comment]
You need to escape the backslashes... (double backslashes)
