### ISSUE TITLE
[v0.5.59] Continuous bulk "refresh.ashx" file AJAX call failing which is showing on Chrome devtool

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#1487]
Today I have updated server with v0.5.59. After login home screen rendering little slow. When I had checked chrome devtool's Network tab and Console tab, there lot of "refresh.ashx" AJAX call failing continuously. Screenshot attached below- 
 
![image](https://user-images.githubusercontent.com/14121807/84567275-2888ae80-ad95-11ea-982f-0e9cfb263f3b.png)

**Comment by Ylianst** [comment]
Checking this now. There is not code that tries to renew the session cookie at 80% the time of the cookie. I will change this so if it fails, it does not try anymore.

**Comment by Ylianst** [comment]
Also, in your config.json, in the "settings" section, check if you have the "sessiontime" line:

```
"SessionTime": 60
```

If that is set to 0, it will cause a problem. It should be at least 10 minutes.

**Comment by AnjaniKumar15** [comment]
Earlier it was not set and look like "_sessionTime: 30". Now I have set to 30 and removed the underscore. now issue resolved. I think default case is stop working in this version, which was mentioned on MeshCentral document.

![image](https://user-images.githubusercontent.com/14121807/84568264-c2535a00-ad9b-11ea-8149-c2694ef2ddf7.png)

**Comment by Ylianst** [comment]
Thanks for pointing this out, will release a fix shortly.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.60 with a fix for this.
