### ISSUE TITLE
Feature Request: viewmode for MSTSC

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#1489]
Hi, would it be possible to add a viewmode for MSTSC like there currently are for other viewmodes like desktop, terminal etc, using logintoken and nodeidhex in the url params?

Maybe something like mesh.example.com/mstsc.html?login=LOGINTOKEN&node=NODEIDHEX

Thank you

**Comment by Ylianst** [comment]
Ok, let me look into this. Currently the login token is time limited so your can't bookmark the URL, but I will change things around to fix this.

**Comment by wh1te909** [comment]
Great! Was not even thinking about it being permanent to be bookmarked, just wanted to generate a link dynamically from my business server so users can access mstsc without having to login directly to meshcentral website to click on the 'Web-RDP' link.

**Comment by Ylianst** [comment]
Oh, you still will need to login. You asked for viewmode like this other pages, if you are not logged in, you will be sent to the login page.

**Comment by wh1te909** [comment]
Sorry, I meant I am already generating the login token with some python code, which is only valid for 1 hour I believe, so the other viewmode pages work but are not permanent, so just wanted this to be similar and not a permanent url.

**Comment by Ylianst** [comment]
Got it. Working on it now :)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.62 with support for your exact example:

`mesh.example.com/mstsc.html?login=LOGINTOKEN&node=NODEIDHEX`

If you are logged in, you only need to specify the node. Let me know if it works.

**Comment by wh1te909** [comment]
It's working perfectly!! Thank you so much :)
