### ISSUE TITLE
Proxy for meshcmd behind a firewall?

### ISSUE THREAD

**Issue by jayrisko** [Ylianst/MeshCentral#149]
I can't don't see any argument options for the "route" action in meshcmd to allow it to work  behind a firewall using a proxy...  Is this possible?  The proxy worked before with the old stand-alone mini-router command-line tool.

**Comment by jsastriawan** [comment]
Try adding file meshcmd.proxy with its content like:

proxy-hostname:proxy-port

This file should have the same filename (without extension) as the binary.

Otherwise you can check mc2router in my repo which you can specify proxy (HTTP or SOCKS).

**Comment by jayrisko** [comment]
Thanks for the tip!  I created a file named meshcmd.proxy (executable is meshcmd.exe on Windows) containing proxy.host.name:port (containing my actual hostname and port number) in the same directory, but get the same error as before when my ssh client tries connecting.  Where can I find the repo containing mc2router

Error:
Redirecting local port 8022 to xxx.xxx.com:22.
Press ctrl-c to exit.
Client connected
ERROR: {"message":"TLS Handshake Error"}

**Comment by Ylianst** [comment]
"meshcmd.proxy" is not going to work. There is no MeshCMD proxy support right now, I would need to add it in.

**Comment by jsastriawan** [comment]
See https://github.com/jsastriawan/mc2router

**Comment by jayrisko** [comment]
Is this proxy mechanism documented anywhere?  docs are kind of skimpy with info...

**Comment by jayrisko** [comment]
Thanks for the repo info!  much appreciated!

**Comment by jayrisko** [comment]
Does meshcmd natively support a proxy or is a 3rd party mechanism needed?

**Comment by jsastriawan** [comment]
> "meshcmd.proxy" is not going to work. There is no MeshCMD proxy support right now, I would need to add it in.

Yes, I look at 
https://github.com/Ylianst/MeshAgent/blob/master/meshcore/agentcore.c#L3720
It seems .proxy file is only considered in agent mode, not standalone MeshCmd mode.

**Comment by jayrisko** [comment]
ahhh....   thanks!   guess we have wait for now...

**Comment by jayrisko** [comment]
Any ETA for the proxy capability with meshcmd?

**Comment by Ylianst** [comment]
ETA 0 minutes. Update to MeshCentral v0.3.1-m, download MeshCMD and when you run it add:

`--proxy hostname:port`

Let me know if it works for you.

**Comment by jayrisko** [comment]
Woohoo!  The meshcmd route action via corporate proxy works now!   Thanks! 👍 

Just a followup question - will this proxy functionality be incorporated into the meshcmd so it can be specified as a JSON parameter within the "meshcmd.txt" file?

And a related followup enhancement request - unless I'm already missing something - can an alternate "meshcmd.txt" filename be specified on the command line so that the file can actually have any name?  It makes it difficult to manage since meshcmd only reads it's parameters from that one single file name, when I might want to run against several different targets and would have to change the filename each time for each target.  The "default" file name could still be "meshcmd.txt" unless an alternate is specified...   
Thanks for bearing with me!  BTW, I also work for Intel - FM site...

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back. All of the command line switches can be set in the "meshcmd.txt" file, so you, can should be able to set the "proxy" value in the file now. For the file, yes, you can do this now:

`meshcmd.exe --actionfile bob.txt`

That will load "bob.txt" as the action file. Let me know if it works.

**Comment by jayrisko** [comment]
Thanks a bunch for the updates so far!

Adding the parameter "proxy":"proxy-host-name:port" into the action file does not work for me.
Specifying the --actionfile parameter on the command line works!

Almost there!    Very cool stuff!  👍

**Comment by Ylianst** [comment]
Ok, let me check the proxy in the action file thing later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.1-o with a fix for this. You can now set the proxy in the meshaction.txt file.

**Comment by jayrisko** [comment]
Adding the proxy parameters into the actionfile still doesn't work.  Has the binary exe been updated on the download site?

**Comment by Ylianst** [comment]
Let me check...

**Comment by Ylianst** [comment]
Ha! Fixed it. I forgot to code sign that latest version. It's online now and in MeshCentral v0.3.1-p. Let me know if it works.

**Comment by jayrisko** [comment]
Woohoo!   All's good and working now!

Really appreciate all your great work!  Awesome package!  👍

**Comment by Ylianst** [comment]
Thanks. I will close this issue, but feel free to open a new issue if anything comes up.

**Comment by Ylianst** [comment]
Thanks. I will close this issue. Feel free to open a new issue if anything comes up.
