### ISSUE TITLE
Feature request: files/terminal connection toolbar

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1490]
If not there already a good reason must be, besides I already filed similar suggestion once https://github.com/Ylianst/MeshCentral/issues/1153#issuecomment-614306536, so perhaps it's a long shot but well worth trying: having those options under user/device/device group `user consent` menu would be pretty useful in my typical case scenarios :smiley:

Thanks!

**Comment by Ylianst** [comment]
So, the link does not work... not sure what is being asked.

**Comment by amenolo** [comment]
Link edited!

Anyway the request is about having files/terminal connection toolbar option in user consent menus.

**Comment by TotallyNotElite** [comment]
@Ylianst you can probably close this
