### ISSUE TITLE
web-rdp very bad expierence

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1493]
_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/1467#issuecomment-644357713_

i'm opening new issue abou new web-rdp feature. this feature would be very useful if RDP experience would be better. now i'm seeing how screen is repainting line by line..

**Comment by orion88-admin** [comment]
Hi,
I updated my meshcentral version today to version 0.5.65 and turned on the web-rdp function but I can't log in this way and I have the following error:

**ERR: {"name":"node-rdpjs","hostname":"xxx.xxx","pid":14252,"level":40,"msg":"ERR_SSL_UNSUPPORTED_PROTOCOL(140103960647552:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:\n)\nError: 140103960647552:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:\n","time":"2020-06-16T10:31:01.989Z","v":0}**

It tries to connect in this way to Windows 7 32 bit.

**Comment by Ylianst** [comment]
The RDP client is based on the [node-rdpjs open source project](https://github.com/citronneur/node-rdpjs). Sadly, it's not super efficient or feature rich. I may look at using another project in the future but for now, not sure I can do anything about performance.

For MeshCentral RDP to work, the operating system needs to support TLS security. I think Windows7 does not support RDP-over-TLS and so, it will not work. Nothing I can do about that anytime soon.

The alternative is to use MeshCentral Router, login to MeshCentral and click the "RDP" button to use the real Windows MSTSC client. This will be very fast and work even on older Windows. Hope that helps.

**Comment by uldiseihenbergs** [comment]
> The alternative is to use MeshCentral Router, login to MeshCentral and click the "RDP" button to use the real Windows MSTSC client. This will be very fast and work even on older Windows

i'm Linux user, and if i remember correctly, MC Router works on Windows only. maybe it's time to MC Router on Linux too?

**Comment by marclaporte** [comment]
Related: https://github.com/Ylianst/MeshCentral/issues/958

**Comment by Tomatoschewps** [comment]
Hi,
I just tried the html5 rdp feature to one of our win2012r2 and win2019 servers and I have the error
"NODE_RDP_PROTOCOL_X224_NEG_FAILURE(Failure code:5 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx))\nError: Failure code:5 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx)"

With some researches for that faillure code (HYBRID_REQUIRED_BY_SERVER) I've found this post who explain that "node-rdpjs" can be used with NLA but without TLS by using "--sec nla" switch.
https://freerdp-devel.narkive.com/o1P31M3p/error-hybrid-required-by-server-when-win-7-nla-is-enabled
