### ISSUE TITLE
Question on updates

### ISSUE THREAD

**Issue by rogalskij13** [Ylianst/MeshCentral#1494]
I have been updating MeshCentral via the "Check Server Version" link on the "My Server" page.  What I noticed is that at the bottom of the github page it tells you "For updating, just install over the previous version by installing again".  Do I need to do the install again?  Or will the self updater work for all the updates?  I don't want to miss anything in the product due to me updating it incorrectly.  Any clarification is appreciated thanks!

**Comment by vitko-bg** [comment]
To update to latest version from shell just install it as normal, and it will update the server. From GUI you can feel free to click on update, and all will happen by itself :)

**Comment by rogalskij13** [comment]
Thank you Vitko-bg.  So just for confirmation the update from the GUI is the ENTIRE update?  I don't have to update both from the shell and from the GUI?

**Comment by Ylianst** [comment]
Correct, the GUI will update everything. Once the server is updated, the agents will also be auto-updated if needed. So, the GUI updates the server and agents.

As a side note, there are administrators that install MeshCentral in a secure way that does not allow the server to "write itself". In that case the GUI option is not available and they have to manually update using `npm install`.

Hope that helps.

**Comment by muahdib69** [comment]
Just to clarify, if you do not update via the GUI, if you update using npm install, also everything will be done? And then the agents do auto-update if needed? 

thanks

**Comment by Ylianst** [comment]
Correct, if you use GUI or `npm install meshcentral`, in both cases the agents will be auto-updated.

In fact, the GUI will do `npm install meshcentral` in the background for you.
