### ISSUE TITLE
Unexpected /meshagents traffic

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1495]
When looking at the trace page, I got 2 hits to the direct meshagent url (/meshagents?id=4&meshid=o4nh....) after installation using the invite url. The install was a week ago.
Those hits are both from an Microsoft IP.

It could be that I used internet explorer to install the meshagent, could be chrome incognito tab as well.. can't find it anymore.
The thing is the url might become public and than everyone can join my mesh server.

Anyone seen this behavior before?

**Comment by Ylianst** [comment]
I am not sure what your question is. When you use the invitation URL, the user will enter the code and get a download link to the MeshAgent.

Are you saying that your got two downloads you did not expect?

**Comment by Allowee** [comment]
Yes that is correct. It is not related to mesh itself I believe.

It could be related to the smart screen filter in Windows, checking the download url from time to time for malware.
That is why I ask if other mesh users have seen this, agent download requests from a Microsoft IP. don't want the direct agent download url in bing ofcourse.

I will log the webrequests and get back if something pops up.

**Comment by Allowee** [comment]
Got a few hits:

3:08:49 AM - webrequest: (157.56.160.42) /meshagents?id=4&meshid=o4nhyywqf
5:06:20 AM - webrequest: (138.91.253.138) /meshagents?id=4&meshid=o4nhyywqfu
5:09:23 AM - webrequest: (13.92.127.51) /meshagents?id=4&meshid=o4nhyywqfu
5:21:12 AM - webrequest: (13.92.127.51) /meshagents?id=4&meshid=o4nhy

I have now added honeypot groups and downloaded the new agents on the 2 suspect machines.

Although harmless I will investigate further to see if the download url might need more security or that this a result of something else.

**Comment by Ylianst** [comment]
Ok, I am going to work on added security for the download URL... The URL's will be time limited.

**Comment by Ylianst** [comment]
I just checked in time-limited encrypted MeshID's for the invite page. It will be in MeshCentral v0.5.68 when it's next published and hopefully will fix this.

**Comment by Allowee** [comment]
Perfect!
Returning a 404 when the link is expired and Unauthorized for the download url when expired.

I did notice the download url expires quicker, but a refresh of the invite link page helps. This does not bother me.

Thank you for the quick update!
