### ISSUE TITLE
Feature Request: Join Remote Computer via Tech Created Code

### ISSUE THREAD

**Issue by cjmny** [Ylianst/MeshCentral#1496]
With ConnectWise seemingly abandoning their Linux server support for Control, we are currently exploring other options for remote support.  MeshCentral has been a leading candidate so far.  In a situation where you are doing a lot of one time/ad hoc support, having the ability to direct a customer to a website and enter a simple, tech generated (or even automated) code to download the software and join a session is very nice to have.  Do you have any plans of adding that in the future?  Thanks!

**Comment by Ylianst** [comment]
This feature exists, take a look at #1019. You will need to add `"agentInviteCodes": true` in the domain section of config.json.

![image](https://user-images.githubusercontent.com/1319013/84808866-26556880-afbe-11ea-99e8-1a7ce6b2ef14.png)

**Comment by cjmny** [comment]
Wow, that is great!  I searched, but just couldn't find it.  Thank you!!!
