### ISSUE TITLE
noVNC - how to connect to another port

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#1497]
I have VNC server running on Linux on non-standard port - how to specify custom port in MC?

**Comment by Ylianst** [comment]
Right click on "noVNC" link in web page and you can set a different port for this device. Let me know if this works.

**Comment by uldiseihenbergs** [comment]
Thanks, that works :) and side question - how can i change mouse pointer? i only see small dot instead of normal mouse pointer..

**Comment by Ylianst** [comment]
The mouse pointer seems to be a noVNC issue, it stays a small dot until it gets updated the first time. So if you move the mouse point to a location where it changes to some other pointer, it will update and be ok. I may need to debug the noVNC code and fix that, it is annoying.
