### ISSUE TITLE
meshagents are not working properly

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#1498]
Since a week ago, mesh agents are randomly get issues on connections, just appear the "setup" message when trying to connect but it dissapear and just appear as disconnect (and the same happens for Terminal and Files).  In some cases reinstalling the agent have solved the issue, but in other cases it doesn´t.  Restarting the service have help but the issue appear again after a couple of hours.  The weird point is that those agents was working fine in the past and now agents are appearing with this issue on a frequent basis.

**Comment by MC-PM** [comment]
need to clarify that antivirus and firewalls was checked so the issue is not related to it.

**Comment by krayon007** [comment]
When this happens, if you click on the console tab, does it say unable to connect tunnel?

**Comment by Ylianst** [comment]
When the problem occurs, can you switch to the device "console" tab and see if any errors show up? Thanks.

**Comment by Ylianst** [comment]
I can get the agent side of the relay connection to fail fairly often on my development system. I am trying to track what is going on.

![image](https://user-images.githubusercontent.com/1319013/84878112-3ca30900-b03e-11ea-81c2-79d9caf732ac.png)

**Comment by Ylianst** [comment]
It looks like the MeshAgent can't open a websocket connection to some URL's. For example, this URL will work:

```
wss://central.mesh.meshcentral.com/meshrelay.ashx?p=5&nodeid=node//1eHM8PKOeXH8UEdNMmN8z@suIwW8fbfBassJEE5uxS8fACdxdfnwcLXr9j30qe8x&id=vf5fdhogg5k&auth=dGYKuVdLRzQCcOuflCdJgY9$K@OMvN2oq542UZtnFrNrZYy$KbDuByuxrju@etqZSNiikz@vJG3qysh@boshPWyjiz$Dr4DsY9IHd1EMFTmIA8Ukvw==
```

But this one will fail:

```
wss://central.mesh.meshcentral.com/meshrelay.ashx?p=5&nodeid=node//1eHM8PKOeXH8UEdNMmN8z@suIwW8fbfBassJEE5uxS8fACdxdfnwcLXr9j30qe8x&id=vf5fdhogg5k&auth=Ivz8p$f1DGYc7x0hueXq4aGi0XAyYULf1qzZb8pbQj5y1fpe7vbgPfz3$FTNFY7dg1$Lz14rNPSqetEJShTyhMFqBANllTNlS6Damg956byfETxzyQ==
```

Note that this has nothing to do with server code, the server does not even get the request on the bad URL, so it can't do any processing on it. The agent simply fails to connect. I am using the "wsconnect" agent console command to test this.

**Comment by orion88-admin** [comment]
I have version 0.5.65 and I have the same problem in the console.

![console_meshcentral](https://user-images.githubusercontent.com/65662158/84901228-72caa200-b0ab-11ea-9e71-ca783539e8c2.JPG)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.66 with a fix for this. Turns out, I had to escape the $ and @ URL characters before the agent can connect.

**Comment by uldiseihenbergs** [comment]
Hi, i just tested this new release .66 with Win agent that previously displayed this "setup.." message. it's a Windows Server 2012 R2. when i first tried to connect to specific user session, it tries to connect to Console - just displays a Login window. then i restarted agent service, and now i can connect to specified user session. i'm not sure if its related to original problem..

**Comment by Ylianst** [comment]
This is likely a different issue. Bryan would have to look at that one.

**Comment by MC-PM** [comment]
seems that now is working fine... thanks!
