### ISSUE TITLE
Duplicate agents when agents re-installation

### ISSUE THREAD

**Issue by HLneoh** [Ylianst/MeshCentral#1499]
Hi, there are duplicate agents when the agent is reinstalled in the same pc. A new node id is introduced after agent reinstallation. Is there a way to retain the node id when agent re-installation?

FYI, I have used the same meshagent.exe. 
Plus, I have uninstalled the agent first before re-installing it.

![image](https://user-images.githubusercontent.com/25906607/84851385-b366f300-b08c-11ea-9f8d-9ce3be0a2a81.png)

**Comment by krayon007** [comment]
How are you reinstalling the agent?

**Comment by HLneoh** [comment]
@krayon007  To reinstall, I just install the agent as usual using the same meshagent.exe.

I am realized that when I uninstall an agent, all the related files (meshagent.msh, meshagent.db, meshagent.exe) are deleted in C:\Program Files\mesh\Mesh Agent. When I reinstall the agent again, this directory is replaced with new files. 

I guess meshagent.db stores the identity of the agent (node id). Therefore, when agent reinstallation, new node id is assigned as new meshagent.db is created. 

In order to solve this issue, is it possible to remain the meshagent.db during uninstall the agent?

**Comment by krayon007** [comment]
I don't know if you're using the dialog or command line, but if you do:

Meshagent -fullinstall

It will keep the .db file if it's already there. It only gets deleted if you donan uninstall.

**Comment by HLneoh** [comment]
@krayon007 Thanks for your reply. I am using dialog. Is there any way to keep .db file when uninstall the agent using dialog?

**Comment by krayon007** [comment]
I also double checked... If you click the Install/Update button in the dialog, the .db is not deleted. Did you click the uninstall button? That does a full uninstall.

-fullinstall will install the agent into:
 %ProgramFiles%\\Mesh Agent or %ProgramFiles(x86)%\\Mesh Agent 
depending on which agent and which windows you are installing into.

-install will install into the current folder.

**Comment by HLneoh** [comment]
@krayon007 Thanks for your info. Yes. I did click the uninstall button. 
As I feel that the 'correct' flow to reinstall something should be 'uninstall' first, then only 'install' back.

In order to achieve my scenario - keep my .db file during uninstall an agent,
the only way is to use command line 'MeshAgent -uninstall' as the uninstall button does a full uninstall. Am I right?

**Comment by krayon007** [comment]
With the dialog, the idea was if you wanted to re-install, you would just click the Install/Update button. The uninstall button in the dialog, was meant if you wanted to do a full uninstall.

**Comment by krayon007** [comment]
But to answer your question, yes. The -uninstall switch from the command line, only deletes the binary. -fulluninstall removes everything associated with the agent.

**Comment by HLneoh** [comment]
@krayon007 Thanks for your time and explanation! Got it!
