### ISSUE TITLE
Do not load password reset page

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1500]
Hello, do not load the page to reset password if you have forgotten it.

![image](https://user-images.githubusercontent.com/26174637/84934269-b4a01c00-b09c-11ea-8776-112ed2cad8d6.png)

![image](https://user-images.githubusercontent.com/26174637/84934290-bcf85700-b09c-11ea-8623-a6799f1575e9.png)

**Comment by Ylianst** [comment]
Correct. Working on a fix for this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.67 with a fix for this. Let me know if it works.

**Comment by desarrollocdb** [comment]
Thanks, can I update at this time?

**Comment by Ylianst** [comment]
Yes, you can update and it should fix the problem. If you can confirm it's fixed, please close this issue. Thanks.

**Comment by desarrollocdb** [comment]
Solved. Thank you
