### ISSUE TITLE
Errant find & replace?

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1502]
I've been looking through the new config file changes and I'm seeing what may have been the result of a find & replace gone wrong? At least on lines 65 and 66 of sample-config-advanced.json, the options read _rlsOffload and _rrustedProxy so I'm thinking a find _T, replace _r may be the culprit here. I haven't scoured the rest of the file so there may be other affected lines.

**Comment by Ylianst** [comment]
Thanks for noticing, will fix this in the morning.
