### ISSUE TITLE
Chat not working and giving error as connection closed

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1503]
Chat not working from browser and no popup in the target system too. 
![image](https://user-images.githubusercontent.com/9078295/84975617-7f9ad480-b143-11ea-9f96-ecc2a7d49bb6.png)

**Comment by Ylianst** [comment]
Thanks for the report, will test this in the morning.

**Comment by aimdharma1990** [comment]
Thanks . I will wait for your update. Thanks once again.

**Comment by vitko-bg** [comment]
Chat is working now - but not really, it opens an URL which is non-working URL
https://https//my.domain.com/:444/messenger?id=meshmessenger/node%2F%2Fc<randon_letters>/user%2F%2Fusername
As soon as URL is manually fixed with correct https and port - all working fine
https://my.domain.com:444/messenger?id=meshmessenger/node%2F%2Fc<randon_letters>/user%2F%2Fusername

**Comment by aimdharma1990** [comment]
Thanks for the update. Is there any workaround right now to make it work in
my local?

**Comment by Ylianst** [comment]
I just tested it and I can't see any issues, it works for me. I also tried placing the server on port 444 and it also worked for me. Could you provide an anonymized version of your config.json? I would like to see if there is anything special in your configuration that would help me figure this out. Thanks.

**Comment by vitko-bg** [comment]
Hi @Ylianst 
Here it is: I am running NGINX, and NGINX config is after meshcentral conf
{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "https://remote.svdecision.com/",
    "_MongoDb": "mongodb://127.0.0.1:27017",
    "_MongoDbName": "meshcentral",
    "_MongoDbChangeStream": true,
    "_WANonly": true,
    "_LANonly": true,
    "_Minify": 1,
    "_SessionTime": 30,
    "_SessionKey": "MyReallySecretPassword1",
    "_DbEncryptKey": "MyReallySecretPassword2",
    "_DbExpire": {
      "events": 1728000,
      "powerevents": 864000
    },
    "_RedirPort": 80,
    "Port": 444,
    "_AliasPort": 443,
    "AgentPort": 444,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "WebRTC": true,
    "ClickOnce": true,
    "_SelfUpdate": true,
    "_AgentPing": 60,
    "_AgentPong": 60,
    "_AgentIdleTimeout": 150,
    "_MeshErrorLogPath": "c:\\tmp",
    "_NpmPath": "c:\\npm.exe",
    "_NpmProxy": "http://1.2.3.4:80",
    "AllowHighQualityDesktop": true,
    "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
    "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
    "_AgentAllowedIP": "192.168.0.100/24",
    "_AgentBlockedIP": "127.0.0.1,::1",
    "_LocalDiscovery": {
      "name": "Local server name",
      "info": "Information about this server"
    },
    "_TlsOffload": true,
    "_MpsTlsOffload": true,
    "_No2FactorAuth": true,
    "_WebRtConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    },
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "my",
      "backupPath": "/my/path/to/meshcentral-backup"
    },
    "_Redirects": {
      "meshcommander": "https://www.meshcommander.com/"
    },
    "ManageCrossDomain": [ "user//admin1","user//admin2" ]
  },
	"domains": {
		"": {
			"ManageAllDeviceGroups": [ "admin1","admin2" ],
			"Title": "My",
			"Title2": "my",
			"_welcomePicture": "mainwelcome.jpg",
			"welcomeText": "my",
			"GeoLocation": true,
			"_TitlePicture": "title-sample.png",
			"_UserQuota": 1048576,
			"_MeshQuota": 248576,
			"_NewAccounts": true,
			"_UserNameIsEmail": true,
			"_NewAccountEmailDomains": [ "sample.com" ],
			"_NewAccountsRights": [ "nonewgroups", "notools" ],
			"urlSwitching": false,
			"_Footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
			"_CertUrl": "https://192.168.2.106:443/",
			"agentInviteCodes": true,
			"PasswordRequirements": {
				"min": 8,
				"max": 128,
				"upper": 1,
				"lower": 1,
				"numeric": 1,
				"nonalpha": 1,
				"reset": 90,
				"force2factor": true
			},
			"_AgentNoProxy": true,
			"GeoLocation": true,
			"_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
			"_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
			"_AgentAllowedIP": "192.168.0.100/24",
			"_AgentBlockedIP": "127.0.0.1,::1",
			"___UserSessionIdleTimeout__" : "Number of user idle minutes before auto-disconnect",
			"_UserSessionIdleTimeout" : 30,
			"__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
			"_UserConsentFlags" : 7,
			"_consentMessages": {
				"_Title": "my",
				"_Desktop": "{0} requesting remote desktop access. Grant access?",
				"_Terminal": "{0} requesting remote terminal access. Grant access?",
				"_Files": "{0} requesting remote files access. Grant access?"
			},
			"notificationMessages": {
				"Title": "my",
				"Desktop": "{0} started a remote desktop session.",
				"_Terminal": "{0} started a remote terminal session.",
				"_Files": "{0} started a remote files session."
			},
			"customui": {
		        	"devicesBarButtons": {
					"exec1": {
					"name": "Execute1",
					"action": "event",
					"logmsg": "Button 1 pressed"
				},
				"exec2": {
					"name": "Execute2",
					"selection": "one",
					"action": "event",
					"logmsg": "Button 2 pressed"
				},
				"exec3": {
					"name": "Execute3",
					"selection": "many",
					"action": "dialog:dialog1"
				}
			},
			"deviceButtons": {
				"exec4": {
					"name": "Execute4",
					"action": "dialog:dialog1"
				}
			},
			"desktopButtons": {
				"exec5": {
					"name": "Execute5",
					"action": "dialog:dialog1"
				}
			},
			"terminalButtons": {
				"exec6": {
					"name": "Execute6",
					"action": "dialog:dialog1"
				}
			},
			"filesButtons": {
				"exec7": {
					"name": "Execute7",
					"action": "dialog:dialog1"
				}
			},
			"dialogs": {
				"dialog1": {
					"logmsg": "Dialog 1 filled",
					"title": "This is the title",
					"text": "This is some test",
					"buttons": 3,
					"elements": {
						"test1": {
							"name": "Sample1",
							"type": "text"
						},
						"test2": {
							"_name": "Sample2",
							"type": "textarea"
						},
						"test3": {
							"name": "Sample2",
							"type": "droplist",
							"options": {
								"1": "Option1",
								"2": "Option2",
								"3": "Option3",
								"4": "Option4"
							}
						}
					}
				}
			}
		},
      "_Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      },
      "_AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
      "_Redirects": {
        "meshcommander": "https://www.meshcommander.com/"
      },
      "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
      "_httpheaders": { "Strict-Transport-Security": "max-age=360000" },
      "_agentConfig": [ "webSocketMaskOverride=1" ],
      "_SessionRecording": {
        "_filepath": "C:\\temp",
        "protocols": [ 1, 2 ]
      }
    },
    "_my": {
      "_DNS": "sub.my",
      "Title": "my",
      "Title2": "TestServer",
      "_NewAccounts": 1,
      "_Auth": "sspi",
      "_Footer": "Test",
      "_CertUrl": "https://192.168.2.106:443/"
    },
    "_info": {
      "share": "C:\\ExtraWebSite"
    }
  },
  "_letsencrypt": {
    "__comment__": "Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@myserver.com ",
    "names": "myserver.com,customer1.myserver.com",
    "rsaKeySize": 3072,
    "production": false
  },
  "_peers": {
    "serverId": "server1",
    "servers": {
      "server1": { "url": "wss://192.168.2.133:443/" },
      "server2": { "url": "wss://192.168.1.106:443/" }
    }
  },
  "_smtp": {
    "host": "smtp.myserver.com",
    "port": 25,
    "from": "myemail@myserver.com",
    "tls": false
  }
}

NGINX CONF:
server {
    if ($host = my.domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  proxy_send_timeout 999999s;
  proxy_read_timeout 999999s;
  server_name my.domain.com;
  return 301 https://$server_name$request_uri;

}

#HTTPS
server {
    listen 443 ssl;
     proxy_send_timeout 999999s;
     proxy_read_timeout 999999s;
    server_name my.domain.com;
    ssl_certificate /etc/letsencrypt/live/my.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.domain.com/privkey.pem; # managed by Certbot
    ssl_session_cache shared:WEBSSL:10m;
    ssl_session_timeout 999999s;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    location / {
        proxy_pass https://127.0.0.1:444;
        proxy_http_version 1.1;


        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }

}

**Comment by Ylianst** [comment]
I cleaned up your config.json. Note that "geolocation" is present twice and your using "customui" section but it's just the sample buttons, but sure if you really want to have these extra buttons on the user interface that probably don't do anything.

```
{
  "settings": {
    "Cert": "https://mysite.com/",
    "Port": 444,
    "AgentPort": 444,
    "WebRTC": true,
    "ClickOnce": true,
    "AllowHighQualityDesktop": true,
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "my",
      "backupPath": "/my/path/to/meshcentral-backup"
    },
    "ManageCrossDomain": [ "user//admin1", "user//admin2" ]
  },
  "domains": {
    "": {
      "ManageAllDeviceGroups": [ "admin1", "admin2" ],
      "Title": "My",
      "Title2": "my",
      "welcomeText": "my",
      "GeoLocation": true,
      "urlSwitching": false,
      "agentInviteCodes": true,
      "PasswordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "reset": 90,
        "force2factor": true
      },
      "UserConsentFlags": "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
      "notificationMessages": {
        "Title": "my",
        "Desktop": "{0} started a remote desktop session."
      },
      "customui": {
        "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
        },
        "deviceButtons": {
          "exec4": {
            "name": "Execute4",
            "action": "dialog:dialog1"
          }
        },
        "desktopButtons": {
          "exec5": {
            "name": "Execute5",
            "action": "dialog:dialog1"
          }
        },
        "terminalButtons": {
          "exec6": {
            "name": "Execute6",
            "action": "dialog:dialog1"
          }
        },
        "filesButtons": {
          "exec7": {
            "name": "Execute7",
            "action": "dialog:dialog1"
          }
        },
        "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",
            "title": "This is the title",
            "text": "This is some test",
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Sample1",
                "type": "text"
              },
              "test2": {
                "_name": "Sample2",
                "type": "textarea"
              },
              "test3": {
                "name": "Sample2",
                "type": "droplist",
                "options": {
                  "1": "Option1",
                  "2": "Option2",
                  "3": "Option3",
                  "4": "Option4"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by vitko-bg** [comment]
Thanks, I will try with updated file.
The second domain is live, just commented it for tests. More domain will be implemented for all regional offices. Also buttons are for testing only. Will get rid of them as they do nothing :)
will update you once new config applied. Will UserConsentFlags fix the Chat issue?
However, update will be posted. Thanks again

**Comment by Ylianst** [comment]
I have not looked at the chat issue yet, but your config.json is very weird. So let me know if things change after you clean it up.

**Comment by aimdharma1990** [comment]
Hi 

> I have not looked at the chat issue yet since it works on my servers. Your config.json is very weird. So let me know if things change after you clean it up.

Hi KIndly find my config.json. 

{
  "__comment1__" : "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__" : "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_Cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_SessionKey": "MyReallySecretPassword1",
    "_Port": 443,
    "_AliasPort": 443,
    "_RedirPort": 80,
    "_RedirAliasPort": 80,
	"allowLoginToken": true,
	"allowFraming": true
  },
  "domains": {
    "": {
      "_Title": "MyServer",
      "_Title2": "Servername",
      "_Minify": true,
      "_NewAccounts": true,
      "_UserNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

the popup opening properly 

https://<ServerIP>/messenger?id=meshmessenger/node%2F%2F2RAiwMnkSdsneWVolOrsScwGpXjaRG7HAuyAeZUX90832c9g8CRYkm9eojHKo1uC/user%2F%2Fadmin&title=DESKTOP-LVQQCPM&auth=1@3yJr3QGJvmd6MwrhHjRAg7g8sQXn4heNyRi5cl8TyA0SRY5XI06376yQWRtxPeZW1nQwFqpYPqPn0qprPfdJ$rUX0I3bdTBXbXb4@vzuh5YdFe9schfVOvfeMc04jiz0fGG9Cyfg==

**Comment by johnczer** [comment]
Just to add to this post:  The Open web address, Display notification, and chat window does not work on a domain joined PC.  This has been an issue for quite some time.  I have tested on my network within my domain and Display notification is the only thing that works.  When I try this on PCs that are not members of a domain but rather a (WORKGROUP) everything works as expected.

**Comment by johnczer** [comment]
Thanks Bryan, I will run this and get back to you.

**Comment by johnczer** [comment]
Okay, one thing I forgot to mention is what if I am accessing a remote computer that is on a domain that I am not a member of.  It shouldn't matter, correct? This would be the case with each site's computer I am connecting to. I can run the commands above on the remote PC that is connected to a domain I am not a member of and it creates the scheduled task just fine.

**Comment by johnczer** [comment]
Here is the output of the commands you wanted me to run:
""
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>SCHTASKS /CREATE /F /TN TestTask /ST 00:00 /SC ONCE /RU DOMAIN\Username/TR "C:\windows\system32\cmd.exe"
ERROR: Invalid argument/option - 'C:\windows\system32\cmd.exe'.
Type "SCHTASKS /CREATE /?" for usage.

C:\Windows\System32>SCHTASKS /CREATE /F /TN TestTask /ST 00:00 /SC ONCE /RU DOMAIN\Username /TR "C:\windows\system32\cmd.exe"
WARNING: Task may not run because /ST is earlier than current time.
SUCCESS: The scheduled task "TestTask" has successfully been created.

C:\Windows\System32>SCHTASKS /QUERY /XML /TN TestTask
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task
">
  <RegistrationInfo>
    <Date>2020-08-20T17:58:44</Date>
    <Author>Username</Author>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <StartBoundary>2020-08-20T00:00:00</StartBoundary>
      <Enabled>true</Enabled>
    </TimeTrigger>
  </Triggers>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\windows\system32\cmd.exe</Command>
    </Exec>
  </Actions>
  <Principals>
    <Principal id="Author">
      <UserId>DOMAIN\Username</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
</Task>
C:\Windows\System32>

""

I've replaced actual DOMAIN\Username for security.

**Comment by johnczer** [comment]
Bryan,
Is there a way to specify a DOMAIN\Username for the individual device groups that the remote agent on the remote PC would know to run these commands (web address /notification/chat) under that account?  They would be different for the various sites I connect to. I guess I don't understand how meshcentral knows what creds to use to run these commands. Does this make sense?

**Comment by si458** [comment]
CLOSING STALE
