### ISSUE TITLE
To use noVNC, do I need to have VNC server installed on the computer I want to connect to?

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#1504]
Hi.

I was happy that I could connect to noVNC.
However, I have experienced that no matter how many attempts are made to connect to the target window. [Failed when connecting: Connection closed (code: 1006)]. Could I access it only if VNC Server is installed on the target computer?

**Comment by Ylianst** [comment]
Hi. So right, if you want to use noVNC, you need to setup the server on your own. macOS has a server you can enable, but for Windows you need to download and install you own. Hope that helps.
