### ISSUE TITLE
Recordings cannot be played from https://meshcentral.com/player.htm.

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1506]
Recordings cannot be played from https://meshcentral.com/player.htm.

The recording does not play or advance in time and this error appears in the console every time you try to play it.

![image](https://user-images.githubusercontent.com/26174637/85044362-20dd5700-b153-11ea-84ad-c58e1176179e.png)

**Comment by Ylianst** [comment]
Are you recording using the browser record feature? Or is it recorded on the server? Do you have desktop multiplexor turned on? - Thanks.

**Comment by Ylianst** [comment]
ok, thanks. I just fixed it. It will be in MeshCentral v0.5.68 when it's next released.

**Comment by aimdharma1990** [comment]
> ok, thanks. I just fixed it. It will be in MeshCentral v0.5.68 when it's next released.

Is there any option to play the recording in other players ?

**Comment by desarrollocdb** [comment]
I confirm error repair
