### ISSUE TITLE
Question: MeshCentral2, NGINX, Letsencrypt

### ISSUE THREAD

**Issue by muahdib69** [Ylianst/MeshCentral#1508]
Hello!

Thanks for a great piece of software, I just installed it fine on OpenBSD 6.7 and it works like a charm.

I have one question though, I installed NGINX as a proxy in front of MeshCentral and I created a letsencrypt certificate with the openbsd acme client.

I could not use the meshcentral letsencrypt functionality because I use a non-privileged user to run meschcentral, therefore I can not bind to port 80 and have to bind to ports > 1024, so I bind to 8000, but meshcentral, on startup, says it will not use letsencrypt because it does not have the redirect port configured to be 80, which I think might be an error if you have a Proxy sitting in front of it, as the proxy will forward any and all requests, it should just work, maybe a configuration option: behind_reverse_proxy:(true|false) would be nice, and make the letsencrypt code conditioned on port == 80 or (port != 80 and behind_reverse_proxy == true and certificate_offload == true) or something.

Anyhow, I have now letsencrypt certificates, which I created directly in the meshcentral-data directory, basically overwriting the self signed certificates with the acme client and pointing NGINX to those same certificates.

My question is, do I have to restart meshcentral when the certificates renew? Or is it sufficient that NGINX is reloaded? Does meshcentral need the certificate when NGINX sits in front of it? My concern is, if I have to restart meshcentral, I kill all states and might lose sessions just to load the new certificate.

So it would be great to not have to do that.

While I thought about that, I remembered that I had a couple of similar cases in the past, I developed a couple of PBX solutions and what I did, to be able to survive a restart of the server application without loosing (in this case voice) sessions was to store the state in memcached. It is nearly the same as having the values in memory, but has the advantage that you could restart meshcentral without having to worry about state.

thank you, 
best
Rai

**Comment by Ylianst** [comment]
Hi. So, there is a solution to your port 80 problem. Try this in the settings section of config.json:

```
    "Port": 8001,
    "AliasPort": 443,
    "RedirPort": 8000,
    "RedirAliasPort": 80,
```

This will indicate that MeshCentral should use port 8001 for HTTPS and port 8000 for HTTP. It also indicates that in reality, port 443 will be used for HTTPS and port 80 will be used for HTTP. AliasPort indicates what the real external port will be.

By putting "RedirAliasPort": 80, you will be able to use the built-in Let's Encrypt support. MeshCentral will auto renew the certificate and restart the server when needed. This is the easiest way.

If you are using a reverse proxy that is doing TLS encryption and doing the Let's Encrypt certificate work, you will need to add this to the config.json settings section:

```
"TlsOffload": "127.0.0.1"
```

Where 127.0.0.1 should be the internal IP address of your reverse proxy. Also, in the domain section of the config.json, add this:

```
"certUrl": "https://127.0.0.1:443",
```

Here, this is the URL where MeshCentral can get the same TLS certificate that the agents will see when connecting. This way, MeshCentral can know what certificate the agents will see and do proper security checking. If the reverse proxy changes the certificate on HTTPS/443, the agents will start connecting to MeshCentral and indicate they are seeing an unexpected certificate. MeshCentral will re-load the "certURL", get the updated certificate and everything will be fine.

Hope this helps,
Ylian

**Comment by muahdib69** [comment]
Ok, Thank you, perfect, so the meshcentral server will automatically refresh the certificate from the nginx server, I do not have to worry about the certificate when it gets renewed and also do not have to restart the server. 

Great. Thank you very much for your clarification and the alias tip!

**Comment by Ylianst** [comment]
Correct, it will auto-renew from NGINX. Don't hesitate to open a new issue if needed.
