### ISSUE TITLE
AntiVirus / Agent Problem

### ISSUE THREAD

**Issue by muahdib69** [Ylianst/MeshCentral#1509]
Hi, 

I installed meshagent on windows 10 machines with kaspersky antivirus installed. After I installed the service, Kaspersky identified it as a some kind of virus, deleted the executable and might have done something to the registry (if meshagent uses registry on windows?). I just saw some audit log in Kaspersky mentioning reverting some registry settings. 

I added meshagent.exe and the installer file to the whitelist of the antivirus, and now I can install it right away and without problems on other computers, but on this one computer I can not uninstall/install the agent. 

Clicking either on install/upgrade or uninstall opens a cmd line window, which will be closed nearly immeadiatly and I can not see the content of the window. 

When installing on other machines, at least I can make out some of the text in the cmdline window before it closes, it stays open a couple of seconds. 

So there is samething weird with the state the antivirus left the agent install in. 

Could you help me on how to clean the install up manually?

thank you
best

**Comment by krayon007** [comment]
run the installer from the command line, that way the window won't close:

meshagent -fullinstall

**Comment by Ylianst** [comment]
Hi. You can clean up the agent installation with:

`meshagent.exe -fulluninstall`

You can also run this to get all the possible command line switches:

`meshagent.exe -help`

As for the anti-virus, this is a common problem and you need to report this to Kaspersky as a false-positive. Are you using the 32bit or 64bit version of the agent?

**Comment by Ylianst** [comment]
Hi. You can clean up the agent installation with:

`meshagent.exe -fulluninstall`

You can also run this to get all the possible command line switches:

`meshagent.exe -help`

As for the anti-virus, this is a common problem and you need to report this to Kaspersky as a false-positive. Are you using the 32bit or 64bit version of the agent?

**Comment by muahdib69** [comment]
Thank you, will try this out tomorrow. I used the 64bit version of the agent. 

I also will report it to Kaspersky, but I am not entirely sure about how, if I make progress, I report it here so others could do the same if it keeps happening.

**Comment by Ylianst** [comment]
This link may help, thanks: [https://support.kaspersky.com/1870](https://support.kaspersky.com/1870)
