### ISSUE TITLE
Mesh Agent Windows 7 VM/KVM 

### ISSUE THREAD

**Issue by adonaiechad** [Ylianst/MeshCentral#151]
Estimado,
Tengo en un KVM un Windows Server 2012 R2 y un windows 7 virtualizado, en ambos el agente de Mesh esta en ejecucion pero solo funciona en la WS2012, la vm de W7 tiene el servicio de mesh en ejecucion y no funciona no logro tomar desde meshcentral el equipo de hecho ni figura, actualice a ultima version MeshCentral v0.3.1-h que puedo probar no tengo ningun log. saludos GRACIAS

**Comment by adonaiechad** [comment]
Estimado actualice a MeshCentral v0.3.1-i  y sigo sin ver el equipo.
Tenia en eventos lo siguiente El servicio Mesh Agent background service ha sido marcado como servicio interactivo. Sin embargo, el sistema está configurado para no permitir servicios interactivos. Este servicio puede tener un funcionamiento incorrecto.

Modifique el servicio, destilde la opcion de iniciar sesion y sigo sin poder ver el equipo en meshcentral, agradecere tu ayuda. Saludos

**Comment by Ylianst** [comment]
Hi. Bryan may correct me, I think the MeshAgent will run correctly only on Windows 7 SP1 or better. On older Windows operating systems, it will run but will not connect to the server. Can you indicate what exact version of Windows 7 you are using? - Thanks.

**Comment by adonaiechad** [comment]
Hi Ylian, is older Windows 7 Profecional.

It is an excellent tool


Thanks for answer quickly.

**Comment by Ylianst** [comment]
Sadly, I don't think there is an easy way for us to support Windows 7 pre-SP1. Bryan looked at it a bit and there is no good way around just installing the SP1 update to make the agent work. I am going to close this issue, but feel free to provide comments or extra details.
