### ISSUE TITLE
Problem with Google Single Sign On

### ISSUE THREAD

**Issue by muahdib69** [Ylianst/MeshCentral#1510]
Hello, 

I configured for our organisation google single sign on. I created the project in the google console, registered it as an internal web app, configured the callback URL and got the clientid and clientsecret. 

I configured the values in the domains part of the configuration and after a restart and installation of the required plugins I have a Google Logo on the login page, clicking on it I get redirected to the google login page, I select my user and authenticate, but then I land again on the meshcentral login page, I will not get logged in. 

The admin user has as email the email address I try to login with from google. 

Here is the configuration part in config.json, I was not sure about __callbackurl, so i left a __callbackurl and callbackurl:

```
  "domains": {
    "": {
      "Title": "XXXXXX IT Support",
      "_Title2": "Servername",
      "_Minify": true,
      "_NewAccounts": true,
      "_UserNameIsEmail": true,
      "certUrl": "https://NGINX-IP:443/",
      "authStrategies": {
        "google": {
          "__callbackurl": "https://support.MYSERVER.com/auth-google-callback",
          "callbackurl": "https://support.MYSERVER.com/auth-google-callback",
          "clientid": "XXXXXXXXXXXXXXXXXXx.apps.googleusercontent.com",
          "clientsecret": "YYYYYYYYYYYYYY"
        }
      }
    }
```

Thank you for your assistence!

**Comment by muahdib69** [comment]
after posting I realized the UserNameIsEmail, I eliminated the _ to activate this configuration, thinking maybe that is the issue, but I still can not login, but maybe this would only work for new users? Must I convert somehow existing users?

thanks
Rai

**Comment by Ylianst** [comment]
Try adding the following line:
```
  "domains": {
    "": {
      "Title": "XXXXXX IT Support",
      "_Title2": "Servername",
      "_Minify": true,
      "_NewAccounts": true,
      "_UserNameIsEmail": true,
      "certUrl": "https://NGINX-IP:443/",
      "authStrategies": {
        "google": {
          "newAccounts": true,  <--------------
          "callbackurl": "https://support.MYSERVER.com/auth-google-callback",
          "clientid": "XXXXXXXXXXXXXXXXXXx.apps.googleusercontent.com",
          "clientsecret": "YYYYYYYYYYYYYY"
        }
      }
    }
```

This will indicate that MeshCentral is allowed to create new user accounts when a user if authenticating using Google. Let me know if this works.

**Comment by muahdib69** [comment]
Hello, 

this seems to work, but it creates completely new users. does this mean that now every on in my google domain can create users? 

I would rather I create the useraccounts in the interface, but let them log in via google, is there no way to match the google logon with an already existing meshcentral user via its email address? 

Thank you
best
Rai

**Comment by muahdib69** [comment]
In any case, it works now and it would be nice to be able to users already created in the interface, but I can live with it for now as it is. If you want to you can close the issue!

Thank you for your time and patience,
Rai

**Comment by muahdib69** [comment]
In any case, it works now and it would be nice to be able to users already created in the interface, but I can live with it for now as it is. If you want to you can close the issue!

Thank you for your time and patience,
Rai
