### ISSUE TITLE
Configurate e-mail invitation

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1511]
I do not know how to configurate the e-mail invitatio in my ubuntu server with mesh central.

Could you help me?

**Comment by openmoto** [comment]
Add this to the end of your config.json file
` "smtp": {
    "host": "aspmx.l.google.com",
    "port": 25,
    "from": "donotreply@clockworx.ca",
    "tls": false
  }`
This should work but not recommended, use authenticated email.
See page 23 [here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.3.pdf)

**Comment by CLAVERATOR** [comment]
First of all thank you so much for your answer.
I does not work that configuration for me 
SMTP server failed (Retry:3/3): {"code":"EENVELOPE","response":"550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient's email address for typos or\n550-5.1.1 unnecessary spaces. Learn more at\n550 5.1.1  https://support.google.com/mail/?p=NoSuchUser b7si11651367wmh.190 - gsmtp","responseCode":550,"command":"RCPT TO","rejected":["guillermoclaveromiro@outlook.es"],"rejectedErrors":[{"code":"EENVELOPE","response":"550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient's email address for typos or\n550-5.1.1 unnecessary spaces. Learn more at\n550 5.1.1  https://support.google.com/mail/?p=NoSuchUser b7si11651367wmh.190 - gsmtp","responseCode":550,"command":"RCPT TO","recipient":"guillermoclaveromiro@outlook.es"}]}

I guest i need to create a smtp server
Right?

**Comment by Ylianst** [comment]
MeshCentral will not create an SMTP server for you. You must set it up and provide the correct settings to connect to it.
