### ISSUE TITLE
Folders uploads

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#1512]
Hello,
Is there the possibility of being able to send entire folders to the remote machine and not just files, when we are on the "folders" tab.
thank You

**Comment by Ylianst** [comment]
Right now, there is no way to upload a folder. Bryan is working on adding zip support to the agent for compression and it could maybe be used in the future to drag & drop a .zip file you want extracted. Bryan would have to look at this.

**Comment by Fredoberti11** [comment]
Ok ... Thank You

**Comment by orion88-admin** [comment]
Hi,

It could also be useful to select and download the entire catalog.
And I don't know why, but you can't download files that are shortcuts, e.g. to an application, the download window does not appear and I have a message in the browser that the download failed.

**Comment by energywave** [comment]
A vote to upload folders. When connected to a customer to update the software we upload the program folder to update files and that involves multiple folders, most of the time. This means going through each folder and upload files, one folder by one.
Some VNC software do this by zipping the folder, uploading the zip and unzipping the folder on the server side.
This could be a very valuable addition, in my opinion (and for my usage :)

**Comment by githubbiswb** [comment]
Another up vote for folder upload, someone mentioned it on /r and I went looking, it would be a handy thing to have for sure

**Comment by si458** [comment]
im going to close this because this wont be possible,
you cant upload folders in a web browser
HOWEVER, you can upload a ZIP file, and use the new unzip feature which is going to be in the next release 1.1.22
