### ISSUE TITLE
MeshCommander: Remote desktop doesn't work

### ISSUE THREAD

**Issue by JulioQc** [Ylianst/MeshCentral#1513]
Hi,

In Meshcommander 0.8.5 the Remote Desktop feature does not work... Instantly disconnects after connect message. Works fine in Intel Commander and VNC.

Any log I could look at to investigate the cause of the trouble?

**Comment by Ylianst** [comment]
Before going too deep in this. Intel AMT has a 8 megabyte display buffer, so if you are remote controlling a large display, Intel AMT may not be able to support it with 16bits-per-pixel. Change the setting to "RLE8" in MeshCommander and try again.

![image](https://user-images.githubusercontent.com/1319013/85157511-6f046000-b210-11ea-8eb0-29d96f98e0ab.png)

If that does not work, you can run MeshCommander like this:

`nw.exe -debug -norefresh`

There will be a debug box that will show up. As you connect to KVM, let me know if you see any messages in the box. Thanks.

**Comment by JulioQc** [comment]
Default is RLE8, and all 4 modes don't work. Connecting... Setup... Disconnected. All within 1-2 sec. 
In debug, nothing coming out the debug window unfortunately. 

Might be unrelated but I noticed Remote Desktop not available on AMT firmware 9.1 but available on 11.7 firmware. They are all configured using the same RCS profile. Neither work in MeshCommander but the 11.7 work in Intel Commander (RLE16). Both Kerberos and TLS enabled on client.

**Comment by JulioQc** [comment]
This is still broken in 1.8.6 unfortunately. I dont understand how this works in Intel's own version of this software!

**Comment by Ylianst** [comment]
Oh. Your using Kerberos for authentication? That could be the problem. Can you try with user/pass and see if it works? If so, I need to hunt down the Kerberos issue. That may be the problem.

**Comment by JulioQc** [comment]
Just gave it a shot... no luck, same behaviour :( But I agree, Kerberos can be an issue quite often! 
I assume you figured I use Kerberos from my email so while I'm at it, I managed to get the deployment done with the RCS console and generate certs from an in house CA during the process for each machine. The CA certificate is deployed by GPO and even imported into MeshCommander. That type of deployment can be causing the problem maybe? 

Any way to launch this in debug to get more output?  I'd be more then happy to help track this down :)

Merci!

**Comment by Ylianst** [comment]
Can you do a big favor and run MeshCommander like this:

```
nw.exe -debug -redirtrace -logfile:log.txt
```

When connect to remote desktop and send me the `log.txt` file back. You can mail me the log file at my [contact information here](https://www.meshcommander.com/contact-information). Hopefully this will show exactly that the problem is and I will be able to fix it right away. Thanks.

**Comment by JulioQc** [comment]
Of course! Sent to your email. 
Seems like gibberish but I assume you're familiar with the encoded output :)

**Comment by penguin02007** [comment]
I have the same problem and it turns out it is because AMT doesn't support external video card.

**Comment by JulioQc** [comment]
Possible it's not supported on your device (see hardware info) but first
check it works if you plug the HDMI/DP cable in the embedded (Intel? amd?)
GPU.

For us it doesn't work because we use the PCIe GPU

**Comment by penguin02007** [comment]
It was over DVI / VGA, I never tried HDMI. Some modern desktops doesn't have VGA and DVI therefore I was using an PCI-E card.

Couple days ago I switched to onboard HDMI and it works right away.

**Comment by jsastriawan** [comment]
Are you able to share with us the device type and vendor? I notice you are saying AMT 9.1. I have seen certain OEM BIOS update could fix it by upgrading its video BIOS or UEFI GOP.

**Comment by JulioQc** [comment]
Exactly what's to expect :)

AMT redirects the video output from the onboard gpu so if you use an
extension gpu, that output is disabled and you see a blank screen.

**Comment by penguin02007** [comment]
It is a Dell Optiplex [7040](https://www.dell.com/support/home/en-us/product-support/servicetag/0-WDAybGRPYjZ0Q0VUUHo5K2ZqNzE1dz090/overview). I don't remember the card model but it is Nvidia chip.

> AMT redirects the video output from the onboard gpu so if you use an
> extension gpu, that output is disabled and you see a blank screen.

Yup, shame on me for not realizing it earlier as I could have just using a converter cable.

If it stayed connected with a blank screen I could have done more troubleshooting. :( But since it is connect and disconnect, I thought I ran into display support issue as I saw a [forum post](https://community.intel.com/t5/Intel-Business-Client-Software/KVM-Remote-Control-Connects-and-then-disconnects-immediately/m-p/1179207) saying high resolution may not be supported over remote desktop.

**Comment by sunryze-git** [comment]
I'm not sure if this is the same issue that others here have had but I recently picked up a Latitude E6440. Turned on AMT. As I try to connect with MeshCommander and Intel Management Commander, the remote desktop will connect but will display black, even on 5900 VNC. I can still control and interact, though. I have tried different video modes too. The CPU should support vPro (i5-4310M) by the way.

I read on the AMT wikipedia that the version of it i have (v9.1.45) should support the laptop's internal resolution (1920x1080 over eDP). Running with `-debug -norefresh` shows nothing useful in console. I created a log.txt too that does have some information in it, but it's cryptic to me.

The laptop has 3 mediums of display; eDP, VGA, and HDMI. I could try to connect with the primary display on each port under various resolutions to see. I'll check back if I get any results. I'm also considering maybe doing a full deprovision and reprovision of MEBx? Maybe even re-update the BIOS? Not really sure where to go from if none of those bring results.

**Comment by jsastriawan** [comment]
For Latitude issue, have you tried upgrading the BIOS. I had experienced similar issue but with different OEM in the past due to a bug in VBIOS.

**Comment by sunryze-git** [comment]
I discovered the cause of my issue. Weirdly, when the system is set to UEFI only, KVM display stops working. I could try to "repair" the BIOS, as it is already on the latest.

**Comment by jsastriawan** [comment]
Interesting. Thank you for sharing your finding. So it looks like GOP firmware issue (the equivalent of VBIOS for UEFI).

**Comment by si458** [comment]
closing as stale and also wrong repo,
this should be moved to https://github.com/Ylianst/MeshCommander
