### ISSUE TITLE
Restart Meshcentral Server option

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#1515]
Hi is there anyway to restart meshcentral from within the web console, or is this a feature coming?

**Comment by petervanv** [comment]
you can by starting an update command, go to "my server" and then to "console" at the bottom type the command: serverupdate   your server is now updating and restarts its service.

![Screenshot_2](https://user-images.githubusercontent.com/58996467/85206301-664f7f00-b321-11ea-91b6-40af73f14eb4.jpg)

**Comment by haxmachine** [comment]
is there another way without having to update the build?
sometimes your may be on a great stable build.
the only reason i want restart it is i made some changes that dont take effect until it restarts

**Comment by petervanv** [comment]
if you replace "serverupdate" with resetserver   , it reboots its service without installing update's
