### ISSUE TITLE
server side recording -> play directly from the recordings page possible?

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#1516]
good morning, what is the reason, why you can't click directly on the mrec file and it is opened in the player? or asked the other way round, why do i have to download the mrec file to my computer first, so that i can transfer it with the player? a direct link would simplify this, or did i miss something? thanks for this great remote maintenance software!

**Comment by Ylianst** [comment]
It's not currently possible to play a recording directly from the web page, however I do want to make this possible in the future. I also want to make it so you can skip forward & back in the file which is more complicated.

**Comment by vitko-bg** [comment]
Agree! Looks like there is no way to play recordings which are recorded on the server.....
BTW, is there a way at least to download those recordings? I never found the option ......

**Comment by vitko-bg** [comment]
PLEASE IGNORE ALL ABOVE :) 
I just fond where recording are.
I do agree it will be very useful to play them directly from the server ............

**Comment by Ylianst** [comment]
Glad you found them. By default, they are in the "meshcentral-recordings" folder, but you can also find the recordings tab on the web page and see and download the recordings from there.

**Comment by si458** [comment]
you can play and download recordings directly from the web ui now
![image](https://github.com/Ylianst/MeshCentral/assets/765314/994632f6-a39e-4d86-ba50-32646524baeb)
you can also go directly to the player url `https://MYSERVER.com/player.htm` without having to be logged in
so guests can go to the url and then upload the mcrec u downloaded and sent then for example
