### ISSUE TITLE
Automatically starting the server

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1518]
The automatically starting the server it does not work for me, i follow every single steep but i do know why the server does not start this is my configuration file

[Unit]
Description=MeshCentral Server
[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /home/atlas/node_modules/meshcentral --cert meshcentral.atlas-sap.com
WorkingDirectory=/home/atlas
Environment=NODE_ENV=production
User=atlas
Group=atlas
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service
[Install]
WantedBy=multi-user.target

**Comment by duzmoraes** [comment]
Hi Claverator, I'm using the service configuration file like this:

[Unit]Description=MeshCentral ServerAfter=network-online.targetWants=network-online.target
[Service]Type=simpleLimitNOFILE=1000000ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentralWorkingDirectory=/rootEnvironment=NODE_ENV=productionUser=rootGroup=rootRestart=always# Restart service after 10 seconds if node service crashesRestartSec=10# Set port permissions capabilityAmbientCapabilities=cap_net_bind_service
[Install]WantedBy=multi-user.target

 Change "ExecStart" to your environment. 
    Em segunda-feira, 22 de junho de 2020 06:33:00 BRT, CLAVERATOR <notifications@github.com> escreveu:  
 
 


The automatically starting the server it does not work for me, i follow every single steep but i do know why the server does not start this is my configuration file

[Unit]
Description=MeshCentral Server
[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /home/atlas/node_modules/meshcentral --cert meshcentral.atlas-sap.com
WorkingDirectory=/home/atlas
Environment=NODE_ENV=production
User=atlas
Group=atlas
Restart=always

Restart service after 10 seconds if node service crashes

RestartSec=10

Set port permissions capability

AmbientCapabilities=cap_net_bind_service
[Install]
WantedBy=multi-user.target
