### ISSUE TITLE
Agent won't run on some machines (Windows)

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#152]
I've installed mesh on around 150 machines so far (I work for a MSP) and it's been amazing so far.
We have a mix of windows 10 and windows 8.1.
However around 20 of these computers (mix of both 10 and 8.1) I just cannot get mesh to run. Always get the same error:
`..\microstack\ILibAsyncSocket.c:934 (10022,0) (null)`
The computers are very similar in both hardware and software so nothing really stands out as to why some just don't work. I even tested on 2 identical machines with exact same hardware specs and software stack and one works the other gives that error.

**Comment by Ylianst** [comment]
Interesting. Looks like a problem at a setsockopt() line.

```
	if (module->RemoteAddress.sin6_family != AF_UNIX)
	{
		// Turn on keep-alives for the socket
		if (setsockopt(module->internalSocket, SOL_SOCKET, SO_KEEPALIVE, (char*)&flags, sizeof(flags)) != 0) ILIBCRITICALERREXIT(253);
	}
```

I am sure Bryan will take a look at it.

**Comment by wh1te909** [comment]
nope thanks!
