### ISSUE TITLE
"WebRTC" setup documentation

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#1522]
In MeshCentral2 documentation, WebRTC connection described but not fully, like how to setup and what things need to configure to establish WebRTC remote connection. It will be very helpful for us, if you can provide us detailed WebRTC setup documentation.
Thank you.

**Comment by Ylianst** [comment]
In the settings section of config.json, just set:
```
"WebRTC": true
```
This will turn on WebRTC support on MeshCentral. Note that I still find some instability with it sometimes and so, I encourage testing this first before turning it on in production.

Also, if you want to configure STUN servers, add this to the settings section of the config.json:

```
"WebRtConfig": {
  "iceServers": [
    {
      "urls": "stun:stun.l.google.com:19302"
    },
    {
      "urls": "stun:stun.services.mozilla.com"
    }
  ]
}
```

Note that MeshCentral will first act as a relay and switch over to WebRTC when possible.

**Comment by maccn** [comment]
Is there a way to know if the remote desktop/file transfer connection is
established by WebRTC p2p or relay?

**Comment by zroug** [comment]
Also here you said to use `WebRtConfig` but https://info.meshcentral.com/downloads/meshcentral-config-schema.json says it is `webrtcConfig` (different number of 'c'). Which one is correct? And can Meshcentral itself be the STUN server?
