### ISSUE TITLE
Additional domains on MC behind NGINX

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1524]
Almost giving up - looks like I cannot get the configuration right, or MC does not work as expecting with additional domain configured.
**My setup:**
domain.com - running on NGINX static site - completely separated from MC.
remote.domain.com - MC(running on port 444) behind NGINX reverse proxy
Now - the problem is: when adding extra domain to MC config.json and trying to get to sub1.domain.com, it redirects me to remote.domain.com. Same with sub2.domain.com
Created a vhosts on nginx for sub1.domian.com and sub2.domain.com - nothing helps. With "TlsOffload":"127.0.0.1" or "TlsOffload": true, results are 502 bad gateway.
Tested all setup with no reverse proxy - directly by accessing server on port 444, i.e. https://sub1.domain.com:444 and https://sub2.domain.com:444 - working fine as configured in MC config.json.

Posting my conf files, if anyone can help PLEASE advise what is wrong?!?!? Does anyone tried this setup before???? Once this setup is done - will move to second stage, exporting NeDB to Mongo, certificates, etc. But without main config - cannot go forward.......

**MC config.json**

{
   "settings": {
    "Cert": "https://remote.domain.com/",
    "Port": 444,
    "AliasPort": 443,
    "RedirPort": 81,
    "RedirAliasPort": 80,
    "AgentPort": 444,
    "WebRTC": true,
    "ClickOnce": true,
    "AgentPong": 300,
    "MeshErrorLogPath": "/my/path/meshcentral/meshcentral-data/",
    "AllowHighQualityDesktop": true,
    "TlsOffload":"127.0.0.1",
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "zipPassword",
      "backupPath": "/my/path/meshcentral/meshcentral-backup"
    },
    "ManageCrossDomain": [ "user//admin","user//admin2" ]
  },
	"domains": {
		"": {
			"ManageAllDeviceGroups": [ "admin","admin2" ],
			"Title": "MAIN Domain",
			"Title2": "main one",
			"welcomeText": "MAIN DOMAIN MAIN DOMAIN MAIN DOMAIN",
			"urlSwitching": false,
			"CertUrl": "https://127.0.0.1:443/",
			"agentInviteCodes": true,
			"PasswordRequirements": {
				"min": 8,
				"max": 128,
				"upper": 1,
				"lower": 1,
				"numeric": 1,
				"nonalpha": 1,
				"reset": 90,
				"_force2factor": true
			}
		},
		"sub1": {
                        "ManageAllDeviceGroups": [ "admin","admin2" ],
                        "DNS": "sub1.domain.com",
                        "Title": "SUB 1",
                        "Title2": "SUB1",
			"welcomeText": "SUB 1 DOMAIN SUB 1 DOMAIN",
                        "NewAccounts": 0,
                        "urlSwitching": false,
                        "PasswordRequirements": {
                                "min": 8,
                                "max": 128,
                                "upper": 1,
                                "lower": 1,
                                "numeric": 1,
                                "nonalpha": 1,
                                "reset": 90,
                                "_force2factor": true
                        }
		},
		"sub2": {
                        "ManageAllDeviceGroups": [ "admin","admin2" ],
                        "DNS": "sub2.domain.com",
                        "Title": "SUB2",
                        "Title2": "SUB 2",
						"welcomeText": "2222222222222222222222222222222",
                        "NewAccounts": 0,
                        "urlSwitching": false,
                        "PasswordRequirements": {
                                "min": 8,
                                "max": 128,
                                "upper": 1,
                                "lower": 1,
                                "numeric": 1,
                                "nonalpha": 1,
                                "reset": 90,
                                "_force2factor": true
                        }
		}
	}
}

**NGINX.conf**

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
}

**remote.domain.com conf**

server {
        if ($host = remote.domain.com) {
                return 301 https://$host$request_uri;
        } # managed by Certbot
        listen 80;
        proxy_send_timeout 999999s;
        proxy_read_timeout 999999s;
        server_name remote.domain.com;
        return 301 https://$server_name$request_uri;
}
#HTTPS
server {
        listen 443 ssl;
        proxy_send_timeout 999999s;
        proxy_read_timeout 999999s;
        server_name remote.domain.com;
        ssl_certificate /etc/letsencrypt/live/remote.domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/remote.domain.com/privkey.pem; # managed by Certbot
        ssl_session_cache shared:WEBSSL:10m;
        ssl_session_timeout 999999s;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/remote.domain.com-access.log;
        error_log  /var/log/nginx/remote.domain.com-error.log;
        location / {
                proxy_pass https://127.0.0.1:444;
              #proxy_pass https://remote.domain.com:444;
                proxy_http_version 1.1;
                #proxy_ssl_server_name on;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}

**sub1 and sub2 nginx conf files are similar**

server {
        if ($host = sub1.domain.com) {
                return 301 https://$host$request_uri;
        } # managed by Certbot
        listen 80;
        proxy_send_timeout 999999s;
        proxy_read_timeout 999999s;
        server_name sub1.domain.com;
        return 301 https://$server_name$request_uri;
}
#HTTPS
server {
        listen 443 ssl;
        proxy_send_timeout 330s;
        proxy_read_timeout 330s;
        server_name sub1.domain.com;
        ssl_certificate /etc/letsencrypt/live/sub1.domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/sub1.domain.com/privkey.pem; # managed by Certbot
        ssl_session_cache shared:WEBSSL:10m;
        # ssl_session_timeout 999999s;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        location / {
                proxy_pass https://127.0.0.1:444/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

}

Thanks for any help provided!!!

**Comment by vitko-bg** [comment]
A little update - once line
proxy_pass https://127.0.0.1:444/; 
in sub1.domain.com.conf is changed to 
proxy_pass https://127.0.0.1:444/sub1;
result is blank - white page.

**Comment by vitko-bg** [comment]
More diag info.
on MC debug with command "node meshcentral --debug" result is:

MAIN: Core module windows-amt is 403589 bytes.
MAIN: Core module linux-amt is 374727 bytes.
MAIN: Core module linux-noamt is 281925 bytes.
MAIN: Core module windows-recovery is 56743 bytes.
MAIN: Core module linux-recovery is 33586 bytes.
MAIN: Core module windows-agentrecovery is 29522 bytes.
MAIN: Core module linux-agentrecovery is 6365 bytes.
MeshCentral HTTP redirection server running on port 81.
CERT: loadCertificate() - Loading certificate from 127.0.0.1:443, Hostname: https://remote.domain.com/...
CERT: loadCertificate() - Loading certificate from 127.0.0.1:443, Hostname: sub1.domain.com...
CERT: loadCertificate() - Loading certificate from 127.0.0.1:443, Hostname: sub2.domain.com...
MeshCentral v0.5.67, Hybrid (LAN + WAN) mode.
CERT: loadCertificate() - TLS connected, got certificate.
Loaded web certificate from "https://127.0.0.1:443/", host: "https://remote.domain.com/"
  SHA384 cert hash: 726********************************************
  SHA384 key hash: 1d3********************************************
CERT: loadCertificate() - TLS connected, got certificate.
Loaded web certificate from "https://127.0.0.1:443/sub1", host: "sub1.domain.com"
  SHA384 cert hash: 726********************************************
  SHA384 key hash: 1d3********************************************
CERT: loadCertificate() - TLS connected, got certificate.
Loaded web certificate from "https://127.0.0.1:443/sub2", host: "sub2.domain.com"
  SHA384 cert hash: 726********************************************
  SHA384 key hash: 1d3********************************************
DISPATCH: DispatchEvent [ '*' ]
MAIN: Server started
ERR: ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
MeshCentral HTTPS server running on https://remote.domain.com/:444, alias port 443.
MeshCentral HTTPS agent-only server running on https://remote.domain.com/:446.

**Comment by Ylianst** [comment]
In your NGINX configuration, add the following line:

```
proxy_set_header Host $host;
```

This will forward the browser host header to MeshCentral and should fix the problem. Let me know if it works.

```
location / {
  proxy_pass https://127.0.0.1:444/;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Host $host:$server_port;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by Ylianst** [comment]
Actually, you should add the following line for the `server_name _` section.

```
proxy_set_header Host $host;
```

In the `servername_name sub1.domain.com` section, you should add:

```
proxy_set_header Host sub1.domain.com;
```

**Comment by vitko-bg** [comment]
Hi @Ylianst , result is same with both options.
I have added a

> proxy_set_header Host $host;

to sub1.domain.com.conf on nginx and also added
proxy_set_header Host sub2.domain.com;
to sub2.domain.com.conf on nginx

After nginx reload - no changes - in address bar displaying correct cub1 or sub2.domain.com, but I know that it is not domains in MC, as different  "Ttitle" are set ......

Looks like nginx does not passing URL to MC, or MC cannot get the exact hostname from nginx .......

**Comment by vitko-bg** [comment]
![oq2XEIKaX2](https://user-images.githubusercontent.com/59362521/85467641-6068d080-b5a3-11ea-8242-5878a047e17d.png)
![ncB5uAHm3p](https://user-images.githubusercontent.com/59362521/85467651-6363c100-b5a3-11ea-8c4e-5670b98f9635.png)
With sub2.domain.com - same

**Comment by vitko-bg** [comment]
**UPDATE:** 
By some reason, not only nginx reload required, MC restart is required also. Looks like it is working now - but please do not close the case, I will do it tomorrow, after some more tests ............ @Ylianst **A BIG THANK YOU FOR ALL YOU ARE DOING!!!!**

**Comment by vitko-bg** [comment]
Sorry for not MC related issues - this one is 100% lack of NGINX knowledge from my side :)
Thanks a lot again!!!! All working as expected.
