### ISSUE TITLE
In the My device ->detail option, , windows agent and Linux agent have different output

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#1525]
Dear all:
I have tested version 5.69. I found that there is a difference between windows and Linux agent. In my device ->detail option, the Windows OS agent get little information, while Linux displays Complete configuration information. In general, we attach great importance to displaying more configuration information.
![linux agent](https://user-images.githubusercontent.com/42434331/85367167-50c59980-b55b-11ea-96e7-62729bac60d9.PNG)
![windows agent](https://user-images.githubusercontent.com/42434331/85367174-5622e400-b55b-11ea-8b25-59f823915307.PNG)

In addition, there was no show in my Server Stats option.
![no stats display](https://user-images.githubusercontent.com/42434331/85367183-5d49f200-b55b-11ea-9820-9902c0c1b62d.PNG)

Thanks so much.
Billy

**Comment by krayon007** [comment]
That's interesting... I just tested it on a bunch of different versions of Windows going back to Windows 7 and Windows Server 2008 R2, and it seems to get complete information...

Can you run the following command on your windows machine:
MeshAgent -exec "console.log(JSON.stringify(require('identifiers').get(),null,1));process.exit();"

**Comment by Ylianst** [comment]
I am working on a fix for the server stats. I see the same problem. In the future, please open two different issues.

**Comment by billydu1980** [comment]
> That's interesting... I just tested it on a bunch of different versions of Windows going back to Windows 7 and Windows Server 2008 R2, and it seems to get complete information...
> 
> Can you run the following command on your windows machine:
> MeshAgent -exec "console.log(JSON.stringify(require('identifiers').get(),null,1));process.exit();"
——————————————————————————————————
Hi， I tried to execute this script, no output，the screenshot is as follows
![exec meshagent](https://user-images.githubusercontent.com/42434331/85490036-9a69bf00-b603-11ea-84ab-8d2f67206260.PNG)

**Comment by billydu1980** [comment]
@Ylianst Okay, Thank you for your instruction.

**Comment by krayon007** [comment]
@billydu1980 , try this command:
MeshAgent -exec "try{console.log(JSON.stringify(require('identifiers').get(),null,1));}catch(x){console.log(x);}process.exit();"

**Comment by billydu1980** [comment]
@krayon007  new error prompt: 
![internal error](https://user-images.githubusercontent.com/42434331/85988449-98e43080-ba21-11ea-9d40-de44bc41534e.PNG)

**Comment by si458** [comment]
this has been fixed recently, just awaiting new build if agents

**Comment by billydu1980** [comment]
Dear all :

We configure a Meshcentral system for our office,  using the Mongdb database.  It is a great pity that the Meshcentral only has one account as full site administrator, and the password has been forgotten. Is there any emergency repair method available.  Currently,the Meshcentral manages over 150 PC workstation systems.

"meshVersion": "v1.1.21", "nodeVersion": "v16.13.2", "runMode": "LAN mode", "productionMode": false, "database": "MongoDB", "dbChangeStream": false, "dbBulkOperations": false, "platform": "linux", "arch": "x64",

Thanks for you reply. 

Best regards!



Billy.Duu 
 
From: Simon Smith
Date: 2023-11-11 11:43
To: Ylianst/MeshCentral
CC: billydu; Mention
Subject: Re: [Ylianst/MeshCentral] In the My device ->detail option, , windows agent and Linux agent have different output (#1525)
Closed #1525 as completed.

**Comment by si458** [comment]
@billydu1980 you can use 
`   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.`
example below:
`node node_modules/meshcentral.js --resetaccount user//admin --pass newpasswordhere`

**Comment by billydu1980** [comment]
Dear Simon:


Thank you for your guidance. We were previously unfamiliar with the meshcentral.js command, but the test went smoothly and the issue has been resolved.


Best regards!



Billy
 
From: Simon Smith
Date: 2024-06-19 19:20
To: Ylianst/MeshCentral
CC: billydu; Mention
Subject: Re: [Ylianst/MeshCentral] In the My device ->detail option, , windows agent and Linux agent have different output (#1525)
@billydu1980 you can use
--resetaccount [userid] Unlock an account, disable 2FA and set a new account password.
example below:
node node_modules/meshcentral.js --resetaccount user//admin --pass newpasswordhere
