### ISSUE TITLE
PROBLEM with SMTP configuration

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1526]
Hellow.
This is the error that i got when i lunch the mesh central service with my server smtp.
root@atlasmesh:/home/atlas# node ./node_modules/meshcentral --cert meshcentral.atlas-sap.com
MeshCentral HTTP redirection server running on port 81.
MeshCentral v0.5.69, Hybrid (LAN + WAN) mode.
ERR: ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
MeshCentral HTTPS server running on meshcentral.atlas-sap.com:444.
**SMTP mail server smtp.office365.com failed: {"code":"ESOCKET","command":"CONN"}**

And this is my config.json:

```
 "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are i>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "meshcentral.atlas-sap.com",
    "production": false
  },
  "smtp" : {
       "host": "smtp.office365.com",
       "port": 587,
       "from": "atlas@atlas-pi.com",
       "user": "atlas@atlas-pi.com",
       "pass": "********",
       "tls": true
   }
```

Any ideas why i recebeing his error, This is the first time that i configurate the smtp server.

Thank you

**Comment by Ylianst** [comment]
I am not familiar with Office365 SMTP server, but you should try setting TLS to false and see if it works. The "TLS" setting indicates if TLS should be used at the start. If you put false, it will start without TLS and upgrade to TLS after the initial exchange.

You can also look at [help links like this one](https://answers.microsoft.com/en-us/msoffice/forum/all/smtpoffice365com-535-573-authentication/2e708a73-3340-4d24-b4e5-b97ff999dbae).

**Comment by CLAVERATOR** [comment]
tank you so mucho @Ylianst, i really apreciate it, i finally could fix it, the problem was in the tls, i put it like false and now it is working

**Comment by Ylianst** [comment]
Nice. I do want to assure you, even if you put TLS to false, you will still get TLS security.

**Comment by CLAVERATOR** [comment]
Ok thank for the support
