### ISSUE TITLE
HOW CAN I INTRODUCE A VALIDATE CERTIFICATE

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1527]
I was wondering How can i put a trusted certificate in my meshcentral server with ubuntu and in witch format (.cert, .pfx) should i put it

**Comment by uldiseihenbergs** [comment]
see here, section nr.5. http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

**Comment by CLAVERATOR** [comment]
yea I know but i don´t have a trusted certificate and i don´t know how lest's encrip works

**Comment by uldiseihenbergs** [comment]
huh, please read section 11 of the same documentation.

**Comment by Ylianst** [comment]
Really, no all caps titles on issues.
