### ISSUE TITLE
CUSTOMIZE THE MAIN WEB PAGE OF MESH CENTRAL

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1528]
There is any way that can i personalice the page of mesh central, for example i would like to change the logo of meshcentral and the logo of my own company
![Screenshot_2](https://user-images.githubusercontent.com/67141657/85369921-3f19cd00-b52e-11ea-848d-2a5a9a037c01.png)

**Comment by vitko-bg** [comment]
To change it add "Title": "My Server" to domain section in the config.json on MC server

**Comment by CLAVERATOR** [comment]
"domains": {
    "": {
      "_title": "ATLAS Proyectos Informáticos",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
I put this in my config.json but it doesn't change tha banner

**Comment by vitko-bg** [comment]
Get rid of underscore, it is for comments

**Comment by CLAVERATOR** [comment]
aaaaaaaa ok i got it, thank you so much

**Comment by CLAVERATOR** [comment]
And for example if i want to chenge this 
![Screenshot_3](https://user-images.githubusercontent.com/67141657/85373195-34ae0200-b533-11ea-82d8-ea592ef6f322.png)

**Comment by vitko-bg** [comment]
Add  "welcomeText": "blabla",

**Comment by CLAVERATOR** [comment]
where in settings? section in the config.json

**Comment by vitko-bg** [comment]
In the domain section, as this is related to your current domain.
You posted above config, it should look like:
"domains": {
"": {
"title": "ATLAS Proyectos Informáticos",
"title2": "Add if you want",
"welcomeText": "Welcome to my site!!!",
"_minify": true,
"_newAccounts": true,
"_userNameIsEmail": true
}
},

**Comment by CLAVERATOR** [comment]
ok thank you, but this, i don't know how to change it 

![Screenshot_5](https://user-images.githubusercontent.com/67141657/85378784-4bf0ed80-b53b-11ea-8763-70eb0c0dfa79.png)

**Comment by vitko-bg** [comment]
Ahaaaaa, try with English version. If you will see Welcome that means that you have some untranslated strings for your language..... Looks like not related to config file, entirely translation issue.
What language you are using? I'll try it on my installation.

**Comment by CLAVERATOR** [comment]
I use spanish language

**Comment by CLAVERATOR** [comment]
How can i Change the language

**Comment by vitko-bg** [comment]
![image](https://user-images.githubusercontent.com/59362521/85383836-62497a00-b538-11ea-967b-61b2c923734b.png)

**Comment by CLAVERATOR** [comment]
nop it still appear 
![Screenshot_1](https://user-images.githubusercontent.com/67141657/85384208-3252a480-b541-11ea-9e66-cf875ece5053.png)

i wonder how can i change it

**Comment by vitko-bg** [comment]
As I know( i.e. not sure) "Welcome" sign cannot be changed/personalized - only text uner it can be, but wait for @Ylianst to check. To me it is looks like untranslated string. Again - I am not sure...

**Comment by CLAVERATOR** [comment]
Finally i fix it 

![Screenshot_4](https://user-images.githubusercontent.com/67141657/85391789-ead11600-b54a-11ea-86c6-6a9d41046dd8.png)
i just change the translation options

**Comment by vitko-bg** [comment]
Please share what have you done exactly, possibly will do it also :)

**Comment by Ylianst** [comment]
Ok, really, no all caps titles on issues.

**Comment by c00perMo** [comment]
Thank you, useful !
