### ISSUE TITLE
MeshCentral update to 0.3.1-m failing

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#153]
Pretty serious issue I just ran in to.  
I attempted to update my server from 0.2.9-a to 0.3.1-m (on Windows) using the MeshInstaller v1.5.  The update stalled with the below message in the installer window. I let it sit for about an hour and it never progressed or finished.  I exited that window and was left with a non-functioning MeshCentral2 server.  Most of the server files are now gone.  The entire daemon folder is gone (and not sure what else).  I rebooted the server and tried running the installer again and running the check for update option. It found the update so but stopped in exactly the same spot.  Fortunately this is a Hyper-V VM so I was able to roll back to a snapshot from earlier today before I had tried to perform that update. 

![mesh_update1](https://user-images.githubusercontent.com/48607498/55050206-dd666c80-5025-11e9-8fdb-e8bd42038f36.JPG)
![mesh_update](https://user-images.githubusercontent.com/48607498/55050209-e0f9f380-5025-11e9-9bce-025013cb712f.JPG)

**Comment by PathfinderNetworks** [comment]
This does raise another question- is there a process we can use to fully back up the MeshCentral server application so we can quickly and easily roll back should a failure like this happen in the future (or any other situation that might require a restore).  I'd rather restore just what I need than to roll back to a previous VM.

**Comment by PathfinderNetworks** [comment]
I just tried another update and saw another error pop up (and still got exactly the same message in the MeshCnetral Installation tool as I posted previously).  I can also confirm it does, in fact, completely remove the daemon folder from \MeshCentral\node_modules\meshcentral. Not sure if it's removing any other folders/files though. 
![mesh_update2](https://user-images.githubusercontent.com/48607498/55050771-c1b09580-5028-11e9-89b4-4a732aa156db.JPG)

**Comment by PathfinderNetworks** [comment]
Next thing I tried- I copied the meshcentral-data and meshcentral-files folder from the working 0.2.9-a install.  I then reinstalled MeshCentral and verified it was now at 0.3.1-m (although it was now a completely new server with none of my data).  I stopped the MeshCentral services and copied back the meshcentral-data and meshcentral-files folders.  I then restarted the MeshCentral service. I watched the task manager and saw Node.js ran at near 100% CPU for a few minutes then just stopped.   The MeshCentral service was then no longer running and I never was able to access the MeshCentral site (at least not after copying over the two folders that were backed up- it was accessible as a 'new' server after the initial reinstall. 
So it feels like there is something about the 0.2.9-a files that is incompatible with 0.3.1-m (Iike a database change or something along those lines?)

**Comment by Ylianst** [comment]
Hi. There is certainly something different with the new NPM that is causing problems with the Windows Installer. In the past you could install a new module and it would not remove the old ones, but now, it removes everything except the new modules.

First for backup: Always backup "meshcentral-data" and "meshcentral-files". If you use NeDB, that is all you need. If you use MongoDB, you also need to backup the MongoDB database. I just run the command:

`mongodump --archive=backup.archive`

Then, you can re-install a fresh server, put back the data and files folders and if you you MongoDB, type:

`mongorestore --archive=backup.archive`

It's all pretty easy. There is not other files or registry settings. I personally never use the MeshCentral Windows installer. Just create a new folder "C:\meshcentral", go in it and type "npm install meshcentral". Then "node ./node_modules/meshcentral". That will start the server. You then stop it (CTRL-C), put you "data" and "files" folder in place and start it up again. There are a few command line switches to setup and start as a Windows service. Run "node ./node_modules/meshcentral --help" to see them.

You get a lot more control doing it manually. You can also backup the entire "C:\meshcentral" folder. If anything goes wrong, you can just restore it and run.

I will take a closer look at the Windows Installer tomorrow... it certainly looks like it's behaving badly.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian, if you look at my last post (the one right before yours) you'll see I did try what you said- backed up the meshcentral-data and meshcentral-files folders, installed MeshCentral 0.3.1-m, stopped the MeshCentral service, copied the meshcentral-data and meshcentral-files folders in to the new server, then restarted the MeshCentral service.  Doing that still failed- I could see the Node.js task running in task manager at near 100% CPU for a few minutes.  Then it stopped. After that the MeshCentral service was no longer running- nor would it start because the daemon folder was, once again, missing.  So something is happening even when trying to use the backed up files from 0.2.9-a copied to 0.3.1-m.

**Comment by Ylianst** [comment]
Oh sorry. First, if there is a "mesherror.txt" file in "meshcentral-data". Take a look at it and send back any errors you see. Also, can you run the server manually and see what is going on?

- Stop the service.
- Open a command shell as administrator
- "cd c:\Program Files\Open Source\MeshCentral"
- "node .\node_modules\meshcentral"

You should see exactly what is going on.

**Comment by PathfinderNetworks** [comment]
I'll try tomorrow evening.  Right now there are no errors because I had to roll back to a previous VM image to get the server online again.  Tomorrow I will just backup the entire MeshCentral folder and do the upgrade again.  If it fails I'll grab the error logs and see what else I can find before restoring the backed up MeshCentral folder (as I need to keep the downtime to a minimum).

**Comment by Ylianst** [comment]
When you try again, just do a manual install of MeshCentral in a different folder (like c:\meshcentral") and copy the data and files folders over. No need to touch or even stop the working server until the new one works. It's super difficult to know what is going on with a Windows Service, so command line install is really much better.

**Comment by PathfinderNetworks** [comment]
Ok, I decided to try it again.  Hopefully this error will help.  First I created a MeshCentral folder at the root of the drive (different than the default meshcentral install location).   I installed MeshCentral from an elevated command prompt using "npm install meshcentral".  Then I started the server with "node ./node_modules/meshcentral"  That allowed me to browse to the new MeshCentral server site like you'd expect.  No trouble there.  I stopped that server and then copied over the meshcentral-data and meshcentral-files folders from the 0.2.9-a install.  Then I started the server again using "node ./node_modules/meshcentral"  This time it threw an error about installing 'greenlock'.  Below is a screen grab of that.  
![meschentral_error](https://user-images.githubusercontent.com/48607498/55053642-3c7eae00-5033-11e9-8e69-4fd07713c6b2.JPG)

**Comment by Ylianst** [comment]
You can try manually installing the missing module:

`npm install greenlock`

I do wonder why it's failing to install.

**Comment by PathfinderNetworks** [comment]
As another test- I edited the config.json file in the C:\meshcentral\meshcentral-data folder and removed the LetsEncrypt code.  Once I did that I was able to start and run that new MeshCentral install using the data copied from the 0.2.9-a install.  The site came up and I was able to log in to it.   Although with the site being not secure (due to no SSL cert).

**Comment by PathfinderNetworks** [comment]
I'll try installing greenlock and adding the LetsEncrypt data back to the config.json file.

**Comment by PathfinderNetworks** [comment]
Manually installing greenlock with that command you provided worked.  So I then added the LetsEncrypt code back to config.json and tried to start the server again.  This time it failed on trying to install 'le-acme-core'.  
![meshcentral_error2](https://user-images.githubusercontent.com/48607498/55054419-31794d00-5036-11e9-8bde-e56cc6150aa5.JPG)

**Comment by PathfinderNetworks** [comment]
Something is definitely not right.  I then manually installed le-acme-core using 'npm install le-acme-core' and it completed.  I then tried to start meshcentral again and, this time, it failed on installing @davedoesdev/fido2-lib  
It's like the scripts for automatically installing those modules is failing- but very strange that manually installing them works.

**Comment by Ylianst** [comment]
Right. MeshCentral is really just calling "npm install <module>", not sure why it's not working. Can you do:

```
npm -v
node -v
```

And give me the versions of NPM and node you are using? I will try tomorrow on my computer. - Thanks.

**Comment by PathfinderNetworks** [comment]
NPM is 6.7.0 
Node is 11.10.1

**Comment by Ylianst** [comment]
Thanks. I will give it a try.

**Comment by mschubeck** [comment]
I should have looked here before trying to upgrade this morning because I'm faced with major problems during upgrade also. In my case, the "upgrade" reverted the system from 0.3.0-u to 0.2.4-m instead of upgrading it to 0.3.1-m. (?)

- There was no mesherrors.txt generated during the "failed" upgrade process, however, one was just created after it completed and the server came back online.  It's contents are solely limited to LE:
`-------- 3/27/2019, 9:56:14 AM ---- 0.2.4-m --------
Detected Let's Encrypt v01 URL (deprecated). Changing version to v01.

-------- 3/27/2019, 9:56:14 AM ---- 0.2.4-m --------
=== WARNING ===
Let's Encrypt v1 is deprecated.
Please update to Let's Encrypt v2 (ACME draft 12)
`

- Running "node .\node_modules\meshcentral" I get several dozen similar messages:
Agent connected with bad signature, holding connection (10.1.101.56:59991).
Agent connected with bad signature, holding connection (68.56.xxx.xxx:58638). etc.
where each of the IP addresses seem to correspond to agents showing offline.

- For what it's worth, after 45 minutes roughly half of the agents are online while the other half are offline.

- Not every agent that is offline has a "bad signature" entry.

Stupidly, this was one time that I did not snapshot the server prior to upgrading... I was lured into a false sense of security because the updates have been pretty stable for the past few months.  But, it was my mistake so I'll rebuild whatever I need to manually.

Ylian, is there anything you would like me to check or test prior to getting started?

**Comment by Ylianst** [comment]
Can you do "npm -v" and "node -v" and get me the versions it returns?

Of course, running such an old version of MeshCentral is going to be a problem. I have a theory of what is going on... as soon as I get in the office, I will post a new version and have you try the update again.

**Comment by merlinweb** [comment]
Thanks YLianst, a couple question, when bugs will be solved:
1 - is it better to backup data and reinstall from scratch or can we update existing installation?
2 - can we keep using windows installer or better begin to use npm method ?

Thanks a lot 

Merlinweb

**Comment by Ylianst** [comment]
Well, you should always backup periodically no matter. However, the server self-update should work correctly, if it does not, it's a bug and I need to work on it. Windows installer should work (once I fix it right, hopefully today). If you run a sizable server, you should consider using command line since you got a lot more control over everything. The Windows installer just does the same "npm" commands, but it's mostly hidden, also, the commands are not that difficult.

**Comment by Ylianst** [comment]
Just published v0.3.1-n that hopefully will fix the problem of people getting a really old version instead of the latest one. If it works, let me know.

**Comment by mschubeck** [comment]
npm -v  6.4.1
node -v  10.14.2

**Comment by Ylianst** [comment]
Just posted [MeshCentral Installer for Windows v1.6](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-1.6.exe ). Hopefully this version will solve a lot of issues. I added enterprise proxy support and improved how npm is run within the installer.

If you want, backup your "meshcentral-data" and "meshcentral-files" folders. Uninstall MeshCentral and re-install it. Then stop the service, put the "data" and "files" folder back and start the service again. Should work now.

I should have fixed up the Windows installer a while back.

**Comment by mschubeck** [comment]
Yes, the Windows installer v. 1.6 seems to have solved the installation problem with minimal effort on my part.  Thanks for the quick fix!

**Comment by Ylianst** [comment]
Oh nice! Thanks.

**Comment by PathfinderNetworks** [comment]
I just updated my server from 0.3.1-m to 0.3.1-p using the Windows installer version 1.6.  At first I thought it may have failed again but it did do the upgrade.  I thought it failed because the installation tool stalled on the screen below.  Or rather not exactly stalled- just the Finish button never became clickable (nor any other notification) letting me know the update had completed.  Even though it did actually complete.  
And thanks again for you and your team's near non-stop work on this great project!
![mesh](https://user-images.githubusercontent.com/48607498/55125094-05fe6d00-50df-11e9-9045-e9f03d72794f.JPG)

**Comment by Ylianst** [comment]
Thanks for posting this. Indeed, it seems like everything worked except that the Installer never detected that the server started up again. I will take a look at this.

**Comment by merlinweb** [comment]
I've got some strange NPM WARN on last page of 1.6 Installer,  upgrading to 0.3.1-p
Unfortunately, can't grab it because page changed in "server restarting" after a while

Meshcentral seems working fine after restart

I think it's a recursive error, next time I will copy it

Cheers

Merlinweb

**Comment by merlinweb** [comment]
I get a screenshot of my strange errors, Thinking  is my only case:
![image](https://user-images.githubusercontent.com/48550288/55606484-3dbd8280-5779-11e9-9709-d6a170c658bd.png)


any idea ? it's only WARN but it's weird…

thanks

**Comment by Ylianst** [comment]
These warning are normal... I should look into fixing them, but have not had the time to look into it. When you do "npm install meshcentral" manually, you see the same thing. I could clean up the installer to not show these.

**Comment by Ylianst** [comment]
I am going to close this issue as I am pretty sure the latest installer works. Please open a new issue if the MeshCentral installer does not work as expected.
