### ISSUE TITLE
WARNING: MeshCentral is running without permissions to use ports below 1025

### ISSUE THREAD

**Issue by pepelemoko37** [Ylianst/MeshCentral#1532]
Hi everyone,

I install MeshCentral on a Raspberry Pi 4 (4Gb model). The installating doing good but  with my other computer (on Debian 10) I cannot connect from my dns hostname (myxxxxxxxxxxxxcentral.duckdns.org:4433) , I have a ERR_CONNECTION_TIMED_OUT

I try to connect directly in my local server (https://192.168.1.12:4433) and I have this message :
**MeshCentral2 MPS server.
Intel® AMT computers should connect here.

The terminal on server say :
```
pi@raspberrypi:~/meshcentral/node_modules $ node meshcentral
MeshCentral HTTP redirection server running on port 1024.
MeshCentral v0.5.67, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on myxxxxxxxxxxxxcentral.duckdns.org:4433.
Server has no users, next new account will be site administrator.

WARNING: MeshCentral is running without permissions to use ports below 1025.
         Use setcap to grant access to lower ports, or read installation guide.

   sudo setcap 'cap_net_bind_service= +ep' `which node`
MeshCentral HTTPS server running on myxxxxxxxxxxxxcentral.duckdns.org:1025.**
```
I also try with the command : sudo setcap 'cap_net_bind_service= +ep' `which node` but it's change nothing.

I check on forum and other sites but I can't find the solution. Can you help me?

Thank you very much.

Have a nice day

Guillaume

**Comment by Ylianst** [comment]
So, on all Linux, software can't bind to ports 1024 and below unless they run as root or have been given permission by root. So, the error you are getting is completely normal. You need to give node right to bind to 1024 and lower ports.

Start by typing: `which node`. This should give you the path to `node` on your system. Check that this is correct. If it is, you should be able to run:

```
sudo setcap 'cap_net_bind_service= +ep' [path to node]
```

Where [path to node] is the path to your node executable. Of course, if you are granting the wrong node binary permissions, that will not do anything.

Also, port 4433 is for Intel AMT, if you don't plan on using that, you can put `"mpsport":0` in the settings section of config.json to turn that off.

**Comment by pepelemoko37** [comment]
Hi,

Thank you very much for your very quick answer.

I did what you telling me but I have this message : 

pi@raspberrypi:~ $ which node
/home/pi/.nvm/versions/node/v14.4.0/bin/node
pi@raspberrypi:~ $ /home/pi/.nvm/versions/node/v14.4.0/bin/node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> sudo setcap 'cap_net_bind_service= +ep' [/home/pi/.nvm/versions/node/v14.4.0/bin/node]
sudo setcap 'cap_net_bind_service= +ep' [/home/pi/.nvm/versions/node/v14.4.0/bin/node]
     ^^^^^^

Uncaught SyntaxError: Unexpected identifier
> 

I make a mistake ?

Thank you again.

**Comment by Ylianst** [comment]
So, first, you can't run the "setcap" command within node. Exit node and from the shell run:

```
sudo setcap 'cap_net_bind_service= +ep' /home/pi/.nvm/versions/node/v14.4.0/bin/node
```

Let me know if that works.

**Comment by Ylianst** [comment]
Ok, I removed the space in `'cap_net_bind_service=+ep'`, will be in next version of MeshCentral.

**Comment by pepelemoko37** [comment]
Hi,

Great ! it's functioning like this. But after install client on devices (I try a linux and a win10) in dashboard with both, when I click to ''connect'' I see ''connecting...'' during one second and he come back on disconnecting mode. On remote screen, terminal or files, it's the same.

I'm very sorry for all this question.

Thank again for you answer and your program

Guillaume

**Comment by Ylianst** [comment]
I just tested two domains with NGINX again and it worked for me including desktop, terminal, files. Can you go in the My Server / Trace tab, enable "web", "webrequest" and "relay" and try the remote desktop again. Then post what you see. Should look like this.

![image](https://user-images.githubusercontent.com/1319013/85615617-67c6c300-b611-11ea-8cb6-db91cd56b543.png)

**Comment by pepelemoko37** [comment]
![Capture d’écran du 2020-06-24 21-55-13](https://user-images.githubusercontent.com/67332893/85621358-78088d80-b665-11ea-942b-17b0e1393ddb.png)
I have this. Maby it's important, i'm connecting with my internat ip adress beacuse via the domain name I have trouble for now.

Thank you so mutch.

**Comment by Ylianst** [comment]
Hi. From the screen above, it looks like both sides of the relay connected correctly and the relay session was successful. Are you saying that it failed on the screen? Very weird.

**Comment by pepelemoko37** [comment]
Yes, he cannot connect. It's strange yes.

Thank you for your time and your answer

**Comment by Ylianst** [comment]
If you server is public, [you could mail me](https://www.meshcommander.com/contact-information) a temporary account and I can give it a try. Not sure I have sufficient information to debug this.

**Comment by pepelemoko37** [comment]
hi,

Thank you so mutch for your proposal.

I shut the server for the night and now it's functionning. The magic of reboot.

J'ai vu sur votre Linkedin que vous parliez français (votre nom de famille le laissait penser) donc j'en profite pour vous dire encore merci dans ma langue et continuez votre super travail.

Bonne journée à vous.

Guillaume

**Comment by Ylianst** [comment]
Merci. Avec un nom comme Guillaume, il y a des chances que tu sois français. Je suis du Québec.

**Comment by pepelemoko37** [comment]
Absolument. Français vivant en Belgique d'où le besoin d'un contrôle à distance.

Bonne journée et encore merci.
