### ISSUE TITLE
Networking info in Details tab glitches for multiple IPs

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#1533]
One of my machines (Pi Zero, ARMv6l / ARMv7l, Raspbian GNU/Linux 10 (buster)) does have multiple IP-addresses (different local subnets) on its ethernet port (usb-ethernet adapter):
```
$ ip address
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:4b:39:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.222/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.33.222/24 brd 192.168.33.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.56.222/24 brd 192.168.56.255 scope global eth0
       valid_lft forever preferred_lft forever

$ ip route
default via 192.168.56.254 dev eth0 onlink 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.222 
192.168.56.0/24 dev eth0 proto kernel scope link src 192.168.56.222 
192.168.33.0/24 dev eth0 proto kernel scope link src 192.168.33.222
```
On the details tab, there are 3 entries - but 3 times just the one for the first IP.
![image](https://user-images.githubusercontent.com/83393/85548299-1a515280-b61f-11ea-9487-f308c8a0cf29.png)

On the [console], all 3 IP show correctly with `netinfo`:
```
  eth0: {
    0: {
      mac: "00:E0:4B:XX:XX:XX"
      type: "ethernet"
      status: "up"
      address: "192.168.1.222"
      family: "IPv4"
      gateway: "192.168.56.254"
      netmask: "255.255.255.0"
    }
    1: {
      mac: "00:E0:4B:XX:XX:XX"
      type: "ethernet"
      status: "up"
      address: "192.168.33.222"
      family: "IPv4"
      gateway: "192.168.56.254"
      netmask: "255.255.255.0"
    }
    2: {
      mac: "00:E0:4B:XX:XX:XX"
      type: "ethernet"
      status: "up"
      address: "192.168.56.222"
      family: "IPv4"
      gateway: "192.168.56.254"
      netmask: "255.255.255.0"
    }
```

On machines running Windows 10 or 7 with the same configuration, there is a similar but different glitch on the Details tab. Only the first IP shows up, **only once**. The response given by `netinfo` seems to be fine (includes all IPs and much more) as well.

**Comment by Ylianst** [comment]
I just tested this on Windows and multiple interfaces seem to work. Looks like a Linux problem.

![image](https://user-images.githubusercontent.com/1319013/85611907-36e48f00-b60d-11ea-9632-a71cc7b4f393.png)

**Comment by baikal** [comment]
To clarify: I was writing about **multiple** IPs on **one** network adapter (linux and windows). On windows only the first IP out of multiple on one network adapter is shown, on linux the (one-and-only) network adapter eth0 having multiple IPs is shown multiple times (3 * eth0) - each of which showing only the first IP (of eth0)
Your screenshot shows two different network adapters (Ethernet, Ethernet 2), presumable having one IP on each of them (well, zero for your Ethernet 2). I think if you add another IP (say 192.168.99.99) to 'Ethernet', it will not show up in Details (but be listed by `netinfo` in the console)

In any case - no big deal, just noticed an thought to report about it here.

**Comment by Ylianst** [comment]
Oh! Sorry, I see now. Ok, let me fix that.

**Comment by baikal** [comment]
@Ylianst Yes, in my case there is only one MAC for that one network adapter/interface. And your proposition covers that perfectly fine.

I do not know if there could be multiple MACs per adapter/interface as well. If so, then  one UI entry per adapter/interface with one line for each MAC as well as one line for each IP might be better? Or on line for each MAC-IP combo?

**Comment by Ylianst** [comment]
Ok, I am about to check in a change that will display many IPv4 for the same adapter. This will be in the next version of MeshCentral v0.5.73.

![image](https://user-images.githubusercontent.com/1319013/85809814-f3257e80-b70d-11ea-8de6-14eca4a3d446.png)
