### ISSUE TITLE
Latest update broke MeshCentral

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1534]
Hi, I just updated my MeshCentral Server, and it's gone!  I've tried restoring from an earlier backup, but nothing works.  The service is running, but just says "This site cannot be reached." in the browser.

Please help!!!

**Comment by PathfinderNetworks** [comment]
I suspect it's not actually a MeshCentral issue (but that's just a guess).  What is the OS you are running the server under?  It could be something like a firewall (either a physical firewall or a software firewall on the OS) blocking the ports.  Could also be something like the IP address of the device you are using as a server has changed, etc.  Is the device you are using as a server using a statically assigned IP address?

**Comment by Ylianst** [comment]
Your going to need to provide a lot more information. Are you running the server on Windows, or Linux? Node version? If there a "mesherrors.txt" file in the "meshcentral-data" folder? If so, can you see if there are any errors?

Also, can you run MeshCentral manually? If so, what do you see?

Are you using "loginkey" in the config.json? One recent change is that "LoginKey" now has to be alpha-numeric. You can't put any special characters as a key.

**Comment by trentdavis** [comment]
My server is running Windows Server 2012, fixed IP.  


Trent Davis
Managing Director

Buckley’s, P.O. Box 3009 | St. John’s, Antigua
Tel: (268) 720-6819 [tel:%28268%29%20720-6819] | Skype: trentdavis | Email: tdavis@artiostech.com [mailto:tdavis@artiostech.com]
On 6/24/2020 1:59:17 PM, Parrish Reinoehl <notifications@github.com> wrote:
I suspect it's not actually a MeshCentral issue (but that's just a guess). What is the OS you are running the server under? It could be something like a firewall (either a physical firewall or a software firewall on the OS) blocking the ports. Could also be something like the IP address of the device you are using as a server has changed, etc. Is the device you are using as a server using a statically assigned IP address?

**Comment by trentdavis** [comment]
Just tried disabling the firewall, but still can't access.  Is there any way to re-install?

**Comment by trentdavis** [comment]
You're right!  There are a bunch of errors in the mesherrors.txt file (see below).  I'm not using loginkey.

-------- 6/24/2020, 2:42:26 PM ---- 0.5.70 --------

C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1981
        meshCmd = meshCmd.replace("'***Mesh*Cmd*Version***'", '\'' + getCurrentVerion() + '\'');
                          ^

TypeError: Cannot read property 'replace' of null
    at Object.CreateMeshCentralServer.obj.updateMeshCmd (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1981:27)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1180:17
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:1106:25
    at newArguments.(anonymous function) (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:484:12)
    at callback (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:126:19)
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:193:12
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:130:20)
    at C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:323:11
    at fn (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at processImmediate (timers.js:637:19)

**Comment by Ylianst** [comment]
Ok, this helps. Taking a look at it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.71 with a fix for this. However, the root cause is that the file "meshcmd.js" can't be found. It should in the in `node_modules/meshcentral/agents` folder. The latest MeshCentral will gracefully ignore the missing file, but you can't download meshcmd on Linux anymore.'

Let me know if this helps.

**Comment by trentdavis** [comment]
Thanks!  However, since my MeshCentral Server no longer starts, how do I do the update manually?

**Comment by Ylianst** [comment]
First, always backup the "meshcentral-data" folder, this folder is very important.

One way is:

- Open a shell as administrator
- Go in the MeshCentral folder, the one above "node_modules" and "meshcentral-data".
- Rename "node_modules" to "node_modules_back"
- Type `npm install meshcentral`
- Once done, launch the service again.

Another way is to uninstall and re-install MeshCentral, but once re-installed, put the old "meshcentral-data" folder back. This way you get everything like it was before.

Hope that helps,
Ylian

**Comment by trentdavis** [comment]
Tried the manual command, but it didn't work.  After manually updating, the system wouldn't run the meshcentral service.  So I reinstalled the meshcentral server using the windows installer.  Not it installs, but the first 3 icons on the left are blank, and I'm still waiting to see if any of the agents connect.  I've also lost my https functionality.

**Comment by trentdavis** [comment]
UPDATE:  Icons are now back to normal, and agents are reconnecting.  Trying to get back https functionality now.

**Comment by trentdavis** [comment]
Https functionality is now back.  Thanks much!!
Will continue checking other functions.

**Comment by Ylianst** [comment]
So, it looks like an update did not go well. Not sure what happened. Just for safely, create a backup of the "node_modules" folder in addition to a backup of "meshcentral-data". In the future, if the update does not work, just stop the server, copy "node_modules" back to a working version and start again.

**Comment by trentdavis** [comment]
Thanks again!  I detected another issue, but I think it's separate from this so I'll open a new ticket.
