### ISSUE TITLE
meshagent for linux creating improper users within /home/

### ISSUE THREAD

**Issue by rodrigospc** [Ylianst/MeshCentral#1535]
Hello friends,

I would like help with a behavior with meshagent on Linux Ubuntu operating systems.

The meshagent is creating users and groups from the local network ldap base within the / home of the users' linux workstations. It creates home/username/.cache/dconf/users being root::root
Example:

rodrigoscruz@ecelepar21147:/home$ ll
total 5904
drwxr-xr-x        1457 root                  root                   77824 jun 24 16:42 ./
drwxr-xr-x            27 root                  root                    4096 jun 24 15:29 ../
**drwx------             3 root                   root                    4096 jun 24 16:41 aalcarvalho/
drwx------             3 root                   root                    4096 jun 24 16:41 abaptista/
drwx------             3 root                   root                    4096 jun 24 16:41 abmattes/
drwx------             3 root                   root                    4096 jun 24 16:41 abntsoftware/
drwx------             3 root                   root                    4096 jun 24 16:41 abrusco/
drwx------             3 root                   root                    4096 jun 24 16:41 absantos/**
_drwxr-xr-x           33 rodrigoscruz    grupo-celepar-usuarios  4096 jun 24 16:59 rodrigoscruz/_

Note that he only created users who had not logged on to the computer, but on existing users he created the / dconf / users folder within the user's ./cache.

Even analyzing the logs and codes of meshinstall.sh, meshagent.sh does not identify the reason for this action. The only thing we can identify is that the meshagent.db of /usr/local/mesh/ is responsible for this behavior.

If anyone can guide us we will be grateful.

Att, Rodrigo Sperandio.

**Comment by krayon007** [comment]
@rodrigospc  by any chance is your setup similar to issue: #695 ?
Symptoms seem similar, but we never got to the bottom of that one, becuase the original poster never got back to us...

**Comment by Ylianst** [comment]
Hi. Can you explain in more detail this line?

```
The only thing we can identify is that the meshcentral.db of /usr/local/mesh/ is responsible for this behavior.
```

Any additional information appreciated. Thanks.

**Comment by rodrigospc** [comment]
> Hi. Can you explain in more detail this line?
> 
> ```
> The only thing we can identify is that the meshcentral.db of /usr/local/mesh/ is responsible for this behavior.
> ```
> 
> Any additional information appreciated. Thanks.

In the tests we performed we noticed from the logs that at the moment when meshagent.db is created, network users also have their perfect creator locations within /home so that ./cache/dconf/users is created, I will attach the syslog files from linux.

**Comment by Ylianst** [comment]
Oh, so it's "meshagent.db", not "meshcentral.db"? I was wondering because "meshcentral.db" is server side.

**Comment by rodrigospc** [comment]
> @rodrigospc by any chance is your setup similar to issue: #695 ?
> Symptoms seem similar, but we never got to the bottom of that one, becuase the original poster never got back to us...

Yes they do, but in our case it creates network users in / home with root :: root and the meshcentral server is not configured to ldap only workstations.

**Comment by krayon007** [comment]
> > @rodrigospc by any chance is your setup similar to issue: #695 ?
> > Symptoms seem similar, but we never got to the bottom of that one, becuase the original poster never got back to us...
> 
> Yes they do, but in our case it creates network users in / home with root :: root and the meshcentral server is not configured to ldap only workstations.

This may take a while to figure out what is causing it. The agent never directly creates any folders on the system,. It is the OS that is passively creating those folders as a result of one of the commands the agent runs (that I havent' figured out which yet) that causes it. It's hard to test on my side at the moment, as we are all working from home right now due to Covid, so I don't have access to a linux machine that is configured for LDAP.

When this issue happens, is this before anybody uses/connects to the agent, or is it only after you interact with the agent?

**Comment by rodrigospc** [comment]
> Oh, so it's "meshagent.db", not "meshcentral.db"? I was wondering because "meshcentral.db" is server side.

That's right **meshagent.db** in the post this I put it wrong sorry!

**Comment by krayon007** [comment]
A couple scenarios to test:

1. If you stop the agent (systemctl stop meshagent), then delete all those folders, then start the agent again (systemctl start meshagent), do those folders get created again?

2. And if so, if you stop the service, delete the folders, then modify the meshagent.msh file so that it can't connect to the server, by altering the URL, then starting the agent again... Does this also create all those folders again?

**Comment by rodrigospc** [comment]
> > > @rodrigospc by any chance is your setup similar to issue: #695 ?
> > > Symptoms seem similar, but we never got to the bottom of that one, becuase the original poster never got back to us...
> > 
> > 
> > Yes they do, but in our case it creates network users in / home with root :: root and the meshcentral server is not configured to ldap only workstations.
> 
> This may take a while to figure out what is causing it. The agent never directly creates any folders on the system,. It is the OS that is passively creating those folders as a result of one of the commands the agent runs (that I havent' figured out which yet) that causes it. It's hard to test on my side at the moment, as we are all working from home right now due to Covid, so I don't have access to a linux machine that is configured for LDAP.
> 
> When this issue happens, is this before anybody uses/connects to the agent, or is it only after you interact with the agent?

This occurs exactly when the meshagent is being installed and meshagend.db is created, we had this same conclusion, that in the system commands in the agent configuration process that it creates this users and we were unable to locate where it comes from. I have the syslog I will post.

**Comment by rodrigospc** [comment]
> A couple scenarios to test:
> 
> 1. If you stop the agent (systemctl stop meshagent), then delete all those folders, then start the agent again (systemctl start meshagent), do those folders get created again?
> 2. And if so, if you stop the service, delete the folders, then modify the meshagent.msh file so that it can't connect to the server, by altering the URL, then starting the agent again... Does this also create all those folders again?

The first part we tested yes and when you start the meshahent service it creates the folders again.

The second part is not, I will test and return thanks!

**Comment by rodrigospc** [comment]
@Ylianst @krayon007 
Dear friends, follow the syslog pdf when creating user sessions.

[syslog.pdf](https://github.com/Ylianst/MeshCentral/files/4828368/syslog.pdf)

**Comment by krayon007** [comment]
My initial suspect, is when I check the proxy settings..
I use the results of: getent passwd
to fetch the uids.

But in your case, I suspect it is Gnome that is creating those folders, becuase after I fetch the login ids, if gnome is on the platform, I use gsettings to fetch the settings... gsettings takes as input the user's home folder location. My hypothesis is that Gnome is creating those folders if they don't exist when I query gsettings for the proxy settings for a particular user... If that is the case, I can modify it, so that I don't query gsettings if the home folder doesn't exist....

Altho it is possible that getent passwd is what actually creates the folder, because the home folder is one of the outputs of that command...

Can you verify if calling getent passwd   causes any folders to get created?

**Comment by krayon007** [comment]
Also, do you have autofs enabled? I think in that other thread that I linked, autofs might be mounting the user folder when anyone pokes a folder in home. If that's the case, later, I'll send you a command to test to see if the folder gets created if someone does an fstat() for that folder path, to see if it exists. Hopefully the OS doesn't mount or create it when someone does an fstat() on it.

**Comment by rodrigospc** [comment]
> A couple scenarios to test:
> 
> 2. And if so, if you stop the service, delete the folders, then modify the meshagent.msh file so that it can't connect to the server, by altering the URL, then starting the agent again... Does this also create all those folders again?

Hello Friend,

We carried out the suggested test of stopping the meshagent and changing the server URL in meshagent.msh and when the meshagent service was started it did not communicate with the server did not create the network users' folders in / home is the meshagent's timing with the meshcentral that has the action that creates the user folders, because when I returned the correct URL he created the folders at the time the meshagent was started.

> My initial suspect, is when I check the proxy settings..
> I use the results of: getent passwd
> to fetch the uids.
> 
> But in your case, I suspect it is Gnome that is creating those folders, becuase after I fetch the login ids, if gnome is on the platform, I use gsettings to fetch the settings... gsettings takes as input the user's home folder location. My hypothesis is that Gnome is creating those folders if they don't exist when I query gsettings for the proxy settings for a particular user... If that is the case, I can modify it, so that I don't query gsettings if the home folder doesn't exist....
> 
> Altho it is possible that getent passwd is what actually creates the folder, because the home folder is one of the outputs of that command...
> 
> Can you verify if calling getent passwd causes any folders to get created?

Hello,

We tested getent passwd and it only listed the users and groups that are in its base but did not create anything in / home, only displayed the content.

I also suspect gnome for some meshagent or meshcentral query action, if you can make this change to not query gsettings if the user does not exist in / home it will be a big test.

**Comment by krayon007** [comment]
Try this meshagent...
run it with this parameter:
./meshagent --disableUpdate=1

This will prevent the agent from self-updating to the version on your server... Before you run this agent from the command line, delete all the network folders that were created... Let me know if this agent does better... I modified it so it does not call gsettings on users where the home folder does not exist.


[meshagent.zip](https://github.com/Ylianst/MeshCentral/files/4833550/meshagent.zip)

**Comment by krayon007** [comment]
The fix mentioned above is live in server version 0.5.73

**Comment by rodrigospc** [comment]
> Try this meshagent...
> run it with this parameter:
> ./meshagent --disableUpdate=1
> 
> This will prevent the agent from self-updating to the version on your server... Before you run this agent from the command line, delete all the network folders that were created... Let me know if this agent does better... I modified it so it does not call gsettings on users where the home folder does not exist.
> 
> [meshagent.zip](https://github.com/Ylianst/MeshCentral/files/4833550/meshagent.zip)

Hello Friend,

We performed the test of subsisting the meshagent file attached by you, we followed exactly the guidelines and it worked when you start the service manually with the parameter --disableUpdate = 1 it starts normally and communicates without error with the meshcentral server, but if you start the service again via systemctl he creates users again. I'll post the prints.

![Captura de Tela 2020-06-26 às 15 30 49](https://user-images.githubusercontent.com/67379918/85891507-9be2e500-b7c5-11ea-8b2b-2cd6963c76fb.png)
![Captura de Tela 2020-06-26 às 15 43 20](https://user-images.githubusercontent.com/67379918/85891527-a1402f80-b7c5-11ea-9c27-7b7ef37e0c40.png)
![Captura de Tela 2020-06-26 às 15 43 32](https://user-images.githubusercontent.com/67379918/85891530-a56c4d00-b7c5-11ea-9610-4c8e860fcd2a.png)
![Captura de Tela 2020-06-26 às 15 48 56](https://user-images.githubusercontent.com/67379918/85891545-a9986a80-b7c5-11ea-8682-7ecd819c7884.png)
![Captura de Tela 2020-06-26 às 15 48 36](https://user-images.githubusercontent.com/67379918/85891564-af8e4b80-b7c5-11ea-971e-7f8c91fb9b0a.png)

**Comment by rodrigospc** [comment]
> The fix mentioned above is live in server version 0.5.73

Hello, excellent news or upload a server to test this version, I will return with a summary of the tests.

Thank you for your help.

**Comment by krayon007** [comment]
> > Try this meshagent...
> > run it with this parameter:
> > ./meshagent --disableUpdate=1
> > This will prevent the agent from self-updating to the version on your server... Before you run this agent from the command line, delete all the network folders that were created... Let me know if this agent does better... I modified it so it does not call gsettings on users where the home folder does not exist.
> > [meshagent.zip](https://github.com/Ylianst/MeshCentral/files/4833550/meshagent.zip)
> 
> Hello Friend,
> 
> We performed the test of subsisting the meshagent file attached by you, we followed exactly the guidelines and it worked when you start the service manually with the parameter --disableUpdate = 1 it starts normally and communicates without error with the meshcentral server, but if you start the service again via systemctl he creates users again. I'll post the prints.

That's because if you just copy over the binary, and restart the service, the service will get 'auto-updated' to the version on the server.

**Comment by rodrigospc** [comment]
> The fix mentioned above is live in server version 0.5.73

Hello Friend,

We upgraded the meshcentral version on the production server to 0.5.73 with the fix for the meshagent, and it no longer presented the problems that were occurring in creating users inside / home.

I would like to thank you for your attention and say that this meshcentral tool is excellent.

The next step is to integrate it with the company's OpenLdap, we will return with new questions in a next topic. Thank you and see you later.

**Comment by rodrigospc** [comment]
Problem solved by updating developers on the linux meshagent.
