### ISSUE TITLE
Feature Request: True Full Screen

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1537]
I'm not sure how much is involved in this but if it's possible, I'd love to see support for true full screen using the browser's native implementation. The ability to maximize the remote desktop window within the browser is great (and I'm not looking for this new feature to replace it) but a fair bit of screen real estate is lost with things like the Windows task bar, browser tab/bookmarks bars, etc. and reclaiming it with an actual full screen implementation could be really useful.

The way I'm envisioning it, the full screen toggle would be separate from the current maximize feature and would either have a toggle for including the top and bottom menu bars and/or the ability to show them when the mouse is held at the top or bottom of the screen with them being hidden by default.

Thanks and keep up the awesome work!

**Comment by Ylianst** [comment]
For true full screen, hold shift and hit the full screen button. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/85653816-640f5c80-b662-11ea-8422-7240850c5c5f.png)

**Comment by PetieM** [comment]
I had no idea that was there but it definitely works. Toggle-able/mouse-over top/bottom bars would still be a nice enhancement, as would some indication that shift+click on full screen gives this functionality, but this is exactly what I was looking for. Thanks!
