### ISSUE TITLE
Mesh agent installed date

### ISSUE THREAD

**Issue by HLneoh** [Ylianst/MeshCentral#1538]
Hi, is there any way to know/get the installed date of an agent/node?

**Comment by krayon007** [comment]
Which OS?

**Comment by HLneoh** [comment]
Windows and Linux

**Comment by Ylianst** [comment]
Would having the date that the agent first connected to the server be ok?

**Comment by HLneoh** [comment]
Yes, that is what I am looking for. It would be better if it is a datetime. Thanks!

**Comment by ImUrX** [comment]
+1

**Comment by krayon007** [comment]
I can look into this

**Comment by si458** [comment]
i have added `installdate` to the output of `installedapps` which might help 
but sadly at the moment, the `installdate` doesnt seem to get added all the time so its 50/50 chance

**Comment by si458** [comment]
this has been fixed by the PR here for the agent https://github.com/Ylianst/MeshAgent/commit/3f2bc445f4ab75dea54ff960dc06d0a2608f5653
we just need to build new agents for this to be included ao closing for now
