### ISSUE TITLE
noVNC Error on Latest Version

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1539]
I'm not sure if this error was just introduced in 0.5.71 or if it has been present for the last couple of versions but I'm now getting an error when trying to connect via noVNC - "Uncaught Error: Must specify URL"

**Comment by Ylianst** [comment]
I think Bryan just saw the same bug, looking into it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.72 with a fix for this. Let me know if it works.

**Comment by PetieM** [comment]
Seems to be fixed in my spot checks. Thanks for the quick update.

**Comment by Allowee** [comment]
Found the problem!

 (str.indexOf('-') == -1))

my domainname contains a "-"
Using the alias domain without a - it gives another error, will open seperate issue
