### ISSUE TITLE
Execute group Script (or programs) for massive update/installations

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#154]
Would be great to execute multiple install on remote computer by checkbox in groups
Launching a Script, start an installation, execute a program, using shared folders as repository to transfer files to selected clients...
Not all machines are in a domain to get gpo or similar, this sort of "remote installer" would be very useful

Maybe  it's only a dream, but ...

Cheers

Merlinweb

**Comment by automacondev1** [comment]
yes. we want)

**Comment by Ylianst** [comment]
You guys are demanding :) Got lots on the plate right now, I am sure we will get there eventually.

**Comment by merlinweb** [comment]
I have a dream…. :) 
To be happy, for me it's enough to know this feature is possible to be developed in the future, just a little line in your huge to-do list…

Thanks for quick answer Ylianst


Cheers

Merlinweb

**Comment by jsastriawan** [comment]
Technically we can do something like:
- Upload the scripts to common folder for that particular device group
- Send command to agent to "sync" the content of the folder to local machine
- Send command to agent to execute particular script

This will require few new "msg" handler in meshcore.js (to sync and to exec).

**Comment by mschubeck** [comment]
Here's an example of the front end GUI on another RMM system manager:
![Capture1](https://user-images.githubusercontent.com/48728727/56156858-19894f00-5f8c-11e9-91bf-19d4fc0015ef.PNG)

The machines here are all in one group.  The command line here runs the native CLI for the respective OS of the clients, and has full clipboard access (both C&P).

**Comment by Baltix** [comment]
I've found some tools for multiple computers configuration management and automation, for example:
https://cfengine.com/product/
https://github.com/duncs/clusterssh
Some other simple tools are described here:
https://www.tecmint.com/run-commands-on-multiple-linux-servers/

**Comment by MailYouLater** [comment]
See also: [ScriptTask](https://github.com/ryanblenis/MeshCentral-ScriptTask) plugin by [ryanblenis](https://github.com/ryanblenis).

**Comment by JSuenram** [comment]
Any update on this aging request?
Any forecasts if and when this will be worked on?

**Comment by dinger1986** [comment]
this is an rmm feature, unlikely to be implemented @si458

**Comment by si458** [comment]
thia already exists now,
select devices -> group action -> run commands
then select if cmd or powershell or bash
then select ur file with commands in OR type out the commands
then select if running as agent or user
then RUN

note: you wont get a reply back

**Comment by dinger1986** [comment]
even better :)
