### ISSUE TITLE
Windows 10 64b Unable to connect

### ISSUE THREAD

**Issue by Julien-asv** [Ylianst/MeshCentral#1541]
Hi,
I didn't yet deploy meshcentral to all my IT infrastructure yet. It works fine with windows 7, but i have an issue with windows 10. I have installed the client only on somes windows 10 computers, i had the offline problem, i saw #556, so i sett the Mesh Agent service to Automatic (Delayed Start), and after 10 days, they are still all online. But when i try to connect to a windows 10 i have an error. 
In one computer :
> ERROR: Unable to connect relay tunnel to: wss://[fe80::250:56ff:fea9:f6fb%10]:443/meshrelay.ashx?p=2&nodeid=node//TiFtODVSEL4tRoENM13gncgj77gKWyTxW$SRV11kaLT7MYs3apXOHY99KWdTDaM7&id=eiuyuiitu6j&rauth=qTcuNvh9rA9XsswouRH7VPN8b3lmUQYUQ1Ijy6REoJjg9In2rGNzW9dM5LXF8UiDGNyrZd5R9E$VpOtU6enzFIwm@9K4x6at, {}

an other :
> ERROR:``` Unable to connect relay tunnel to: wss://[fe80::250:56ff:fea9:f6fb%9]:443/meshrelay.ashx?p=2&nodeid=node//9tPSidlrQ46KghLpWNCWR4gRmn61xpmrd0QKidUubOgCxopxA37boOc$VvAyvwI2&id=x6v8aqwav09&rauth=qTcuNvh9rA9XsswouRH7VPN8b3lmUQYUQ1Ijy6REoJjg9In2rGNzW9dM5LXF8UiDGNyrZd5R9E$VpOtU6enzFIwm@9K4x6at, {}

Clean the core or download default core, didn't change anything.
Meshcentral 0.5.58 on Ubuntu 20.04.

Thank you for your help.

**Comment by Julien-asv** [comment]
I see  #1498 and #1542, i updated the server, and it's look ok on mine, i have to wait tomorrow to test the other one.

**Comment by Ylianst** [comment]
Let me know if the latest MeshCentral fixes it. We updated the MeshAgent with bug fixes after v0.5.58. Current version is v0.5.72.

**Comment by Julien-asv** [comment]
Yes v0.5.72 fixe the issue. I can connect to the last one, no error. Thanks
