### ISSUE TITLE
Agents Disconnecting Since Update to Version 0.5.58

### ISSUE THREAD

**Issue by jsmith1992** [Ylianst/MeshCentral#1542]
After updating to version 0.5.58, I've noticed a large number of devices appearing offline in the mesh central interface. This appears to be an issue with the device's Mesh agent, because if I connect to the device, I can restart the Mesh Service, and it will reconnect to the web interface. 

Information about my setup:
-Meshcentral is running on a Windows 10 VM, locally hosted.
-Around 140 computers connected, mostly windows 10, with some windows 7. The windows 7 ones seem to disconnect more frequently if that information helps.
-The clients are all either on a lan, or connected from another location over VPN. There doesn't seem to be any correlation between these issues and the computers that connect over the VPN.

If any more information is needed, I can provide it.

**Comment by uldiseihenbergs** [comment]
this one? #1498

**Comment by jsmith1992** [comment]
That does actually sound like the same issue. So I guess my solution is updating to the newest version?

**Comment by uldiseihenbergs** [comment]
i think so.

**Comment by Ylianst** [comment]
Let me know if the latest MeshCentral fixes it. We updated the MeshAgent with bug fixes after v0.5.58. Current version is v0.5.72. Lots of fixes have been done since.

I know we had a problem with the MeshAgent and HTTP proxies, but that has been fixed in latest releases.
