### ISSUE TITLE
MeshRemote is being setup with port 444 which does not work.

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#1543]
I've noticed that installing the remote mesh agent does not work anymore.  I checked and discovered that the agent config file is using port 444, and that causes the remote agents not to appear.  If I manually change the port to 443 in the remote agent config file, then the agents magically appear!

I suspect this has something to do with the agentport option you provided a few versions back, however I can't seem to get the setup file to change to 443, or to get the system to recognize agents on port 444.

What can I do here?  Thanks in advance!

**Comment by Ylianst** [comment]
Hi. Can you send over your config.json? (Remove any private names). I want to make sure I understand. Thanks.

**Comment by trentdavis** [comment]
{
  "settings": {
    "RedirPort": 80,
    "_Port": 443,
    "AgentPort": 444,
    "WebRTC": false,
    "cert": "mydomain.com",
    "CertUrl": "https://mydomain.com/",
    "plugins": {
      "enabled": false
    }
  },
  "domains": {
    "": {
      "_titlehtml": "This is a <b>TEST</b>",
      "title": "Company Name",
      "titlePicture": "CompanyLogo.png"
    }
  },
  "letsencrypt": {
    "email": "email@domain.com",
    "names": "mydomain.com",
    "rsaKeySize": 3072,
    "production": true
  }
}

**Comment by Ylianst** [comment]
So, not completely sure what you are trying to do, but maybe this will make it more clear. Most people should not use the "AgentPort" option, when you set `"AgentPort": 1234`, MeshCentral will start listening to port 1234 with a HTTPS web server that will only accept agent connections. If you browse to https://server:1234, the browser will not see the login screen on this port.

This is useful if you want agents to connect to your server but want to provide extra security for the user web portal.

I would recommend you remove "AgentPort" from your configuration and just use "Port":443. This way, both agents and your browsers will use that same port.

Hope that makes sense,
Ylian

**Comment by trentdavis** [comment]
Yeah, I tried that, but the problem is that whatever is compiling the remote agent setup exe file is still coding port 444.  So new agents do not appear.  I can login just fine, but it doesn't appear to be listening on port 444 for the agents anymore.

**Comment by Ylianst** [comment]
So, if you set `"Port": 443` (which is the default) and restart the server. When you download a new agent, it should encode port 443 in the agent. If not, there is something really wrong. Also note that if the server sees that port 443 is already occupied, it will bind to port 444 instead, so maybe that is what is happening for you.

Are you using a reverse proxy or any port mappings in front of your server?

One other option is to put `"AliasPort": 443`. This will indicate that regardless of what port MeshCentral is using, assume that port 443 is used externally.
