### ISSUE TITLE
Issue with '-' in domain name

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1544]
The function  isSafeString(str) checks for forbidden chars in a string.
The function checks for the '-' which, in my case, is part of the domain name. (the - is the only allowed char in a domain name)

The function is present in:
public/novnc/app/ui.js
public/scripts/common-0.0.1.js
views/mstsc.handlebars
views/xterm.handlebars

For some reason the function is redefined instead of used from the common js

**Comment by Ylianst** [comment]
Your right, fixing this now.

**Comment by Ylianst** [comment]
Just checked in the fix, will be in MeshCentral v0.5.74.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.74 with a fix for this. Close this issue if the problem is solved. Thanks.

**Comment by Allowee** [comment]
Yes this is fixed.
