### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by HLneoh** [Ylianst/MeshCentral#1545]
Hi, is there a way to transfer file from remote pc to local pc?

**Comment by vitko-bg** [comment]
@HLneoh - click on the device and check the files tab - all info is there.

**Comment by Ylianst** [comment]
To download, just click on the filename. Let me know if that helps.

![image](https://user-images.githubusercontent.com/1319013/85880273-98813680-b790-11ea-9aaf-f94706a63110.png)

**Comment by HLneoh** [comment]
Cool. It works. Thanks so much!
