### ISSUE TITLE
Question: what does the linux terminal do when you click connect

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1546]
When clicking connect on the Terminal page, on a linux system, it quickly shows something before clearing and displaying the prompt.

something like alias or colors?

Also I noticed on my pi the starting directory is always "/usr/local/mesh" and on another linux system the starting directory is "/"
I would prefer this to be the users home directory.

**Comment by uldiseihenbergs** [comment]
you can right click on Terminal page Connect button, and there are few choices to connect.

**Comment by Ylianst** [comment]
You can see the [answer on this line in the code](https://github.com/Ylianst/MeshCentral/blob/22ffb48b75af0427ff5f3dc5e1c664c43d77fd83/agents/meshcore.js#L1417). It sends the following two terminal commands:

```
alias ls='ls --color=auto';
clear
```

This enables color for the "ls" command. Hope that helps.

**Comment by krayon007** [comment]
> When clicking connect on the Terminal page, on a linux system, it quickly shows something before clearing and displaying the prompt.
> 
> something like alias or colors?
> 
> Also I noticed on my pi the starting directory is always "/usr/local/mesh" and on another linux system the starting directory is "/"
> I would prefer this to be the users home directory.

On your machine that is showing '/' did you install the agent on this machine a long time ago (relatively speaking, compared to your pi)

The reason for this, is that there use to be an error in the install script, such that the working directory was not set correctly in the service configuration. The only way to fix this, is to fix the service configuration. The easiest way to address this, is to go to where the agent is installed, run:

./meshagent -fullinstall

This will cause the agent to rewrite the service configuration file.

**Comment by krayon007** [comment]
Otherwise, if you prefer, let me know which linux distro/version you are running, and I can show you how to fix the service configuration manually.

**Comment by krayon007** [comment]
Actually, let me know what linux distro/version you are using, so I can help you edit it manually. Because if you run the command line installer, the agent will be re-installed into /usr/local/mesh_services/meshagent, so if you agent isn't currently installed there, it's going to recreate the db and such... If I help you edit the service configuration, we can keep the agent in the directory it is already installed in.

**Comment by Allowee** [comment]
Okey, only the alias command. 
It seems there is also output from my .bashrc
"dircolors: no SHELL environment variable, and no shell type option given”
I don't think this a mesh issue.

I see there is an option to load another core, is this the meshcore.js file I can edit and upload to disable the clear and see what is going on?

The linux box is Debian 9.6 (mesh installed on may 26)
The pi Armbian 10.3 (mesh installed on june 2)

For now I just add 'cd /root'in my .bashrc

**Comment by Ylianst** [comment]
You can go in "node_modules/meshcentral/agents" and remove "meshcore.min.js" and edit "meshcore.js" to make the changes you want, but your changes will be lost on the next update.

You can also copy meshcore.js to "meshcentral-data" and make change there. MeshCentral will use the copy in "meshcentral-data" if present. However, once you update MeshCentral, there will be a mismatch between the server and the meshcore. js.

Probably the best is to edit .bashrc.
