### ISSUE TITLE
Add Users to Device Group using HTTP request (webserver.js)

### ISSUE THREAD

**Issue by gitoaklog** [Ylianst/MeshCentral#1548]
Hello,

lately I've been trying to create users and grant them access to a **device group** using http request. But it doesn't seem like it is possible or maybe I didn't find the right endpoint. 

![image](https://user-images.githubusercontent.com/67440399/85868933-f9147180-b798-11ea-9f34-29cd30e254a1.png)
_List of endpoints I've found_

![image](https://user-images.githubusercontent.com/67440399/85868971-09c4e780-b799-11ea-9356-91d06d1c7ac2.png)
_What I'm trying to do with http requests_

If there's any documentation on the webserver endpoints I would also be interested (or examples). I'm also having issues to understand how to create accounts (function handleCreateAccountRequest is throwing me error 401), but before I get more into that I would like to know if it is possible to add a user to a device group using http requests.

**Comment by Ylianst** [comment]
MeshCentral uses a websocket interface for almost all commands. This allows for a two-way conversation. One trick you can use it to add `?trace=1` or `&trace=1` at the end of the URL and you will be able to see all the commands sent and received by the browser on the websocket channel. For example in FireFox:

![image](https://user-images.githubusercontent.com/1319013/85880859-923f8a00-b791-11ea-8e97-8e7b91c40e56.png)

You can write you on application to connect to MeshCentral over WebSocket and send commands, but MeshCentral comes with a command line tool that can do this. It's called `meshctrl.js`. In the folder above "meshcentral-data" and "node_modules" type this:

```
node node_modules/meshcentral/meshctrl
```

You will see something like this:

![image](https://user-images.githubusercontent.com/1319013/85881075-eba7b900-b791-11ea-845e-e5f1bf1ce7f8.png)

This is a command line tool that allows you to list/create/delete accounts and much more. Let me know if this works for you. Your also free to look at the code of MeshCtrl.js to see how it works and use the code in your own projects.

Let me know if that helps,
Ylian

**Comment by gitoaklog** [comment]
Thanks for your quick answer.

I just want to make sure, my application is web based (and hosted on a different domain) and I would like to POST to something like https://mymeshcentral.com/addusertodevicegroup with a user id and parameters I want (full rights etc.). This isn't possible right ? 

If not, I will try to make a WebSocket application to use command lines like you suggested me.

**Comment by Ylianst** [comment]
HTTP POST operations are not currently supported. I could add that as a feature. Currently, only websocket is supported.

**Comment by gitoaklog** [comment]
Alright thanks for the clarification and help, I will work on the websocket solution.
