### ISSUE TITLE
Update MeshCentral 0.3.1-? on linux ubuntu Dashboard not load

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#155]
After update MeshCentral to 0.3.1 can not load manage web page.
MeshCentral is installed on Ubuntu 18.04. My serverstate.txt:
time=
state=running
redirect-port=80
mps-port=4433
mps-name=myurl.es
servername=myurl.es
https-port=444

Thaks

**Comment by Ylianst** [comment]
Can you run "npm -v" and "node -v".
Also, can you run the server manually: "node node_modules/meshcentral"
Thanks.

**Comment by Ylianst** [comment]
Also, you should do "npm install meshcentral" again to update to the latest MeshCentral version. Some installation fixes have been done.

**Comment by edorbike** [comment]
Running "npm -v" and "node -v". Also, "node node_modules/meshcentral"  this is a message on terminal:
ERROR: Unable to install missing package
![imagen](https://user-images.githubusercontent.com/45072744/55138839-adf25580-5134-11e9-990f-12ebcee97fca.png)

**Comment by edorbike** [comment]
If I reinstalled meshcentral, would the configuration be lost? Would the list of manage computers connected be lost?
Thanks.

**Comment by Ylianst** [comment]
It will not be lost, but to make sure, backup the "meshcentral-data" folder. For the error above, try manually installing the missing module using "npm install @davedoesdev/fide2-lib".

**Comment by edorbike** [comment]
Thank you so much
