### ISSUE TITLE
Additional domain Device Groups issue

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1550]
With my setup remote.domain.com and sub1.domain.com the current issue is:
step 1: Administrator on remote.domain.com is logged in and stay on Device Groups page
step 2: User for sub1.domain.com(with manager rights) logging to sub1.domain.com and creating a group of devices.
step 3: Guy from step 1 - can see newly created group and all devices, can see rights and username who is created that group.
step 4: Administrator on remote.domain.com refreshing page - and group from step2 disappearing :)

Instead of making this a bug and fix it :) , may this be an Option within MC, so main domain admin can choose to see all devices from other domains or not. It will cover some(not all) of my request in #974 :):) Thanks.

**Comment by Ylianst** [comment]
Thanks for reporting this. This is certainly a bug.

Is your administrator set to manage all device groups within the domain in the config.json? Are you using `manageAllDeviceGroups` in your config.json?

Currently you can manage users across domains using, for example:

```
"manageCrossDomain": [ "user//admin" ],
```

However, you can't manage devices groups domains.

**Comment by vitko-bg** [comment]
Yes it is set to manage all groups, and Yes - I am using managecrossdomain option. 
I am using this, as trying somehow to get Super User working, as this is not implemented yet

**Comment by Ylianst** [comment]
Ok, I think it's the same root cause as #1549. I need to look into this.

**Comment by Ylianst** [comment]
I have a fix for this in MeshCentral v0.5.74 that I will publish later today. Let me know if it works.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.74 with a fix for this. Close this issue if the problem is solved. Thanks.

**Comment by vitko-bg** [comment]
Solved. Thanks!
