### ISSUE TITLE
AmtAcmActivation not working...

### ISSUE THREAD

**Issue by dubs740** [Ylianst/MeshCentral#1552]
I'm setting up a test instance of MeshCentral to see if it would work for our organization, as a replacement for an Intel SCS server, and want to use the trusted pki certificate we already have to do automated ACM activation.  Following some older threads, I've added to my config.json:

```
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
      "auth": "sspi"
    },
    "AmtAcmActivation": {
     "log": "amtactivation.log",
     "certpfx": "cert_for_ms.pfx",
     "certpfxpass": "*password obscured*"
    }
   }
```

But this doesn't seem to work.  I only see options for adding CCM activation to a device group.  I'm not sure where any log files may exist to show what went wrong?  I also tried splitting the certificate and using:

    "AmtAcmActivation": {
     "log": "amtactivation.log",
     "certs": {
      "servername": {
       "certfiles": [ "cert_for_ms.crt", "SectigoRSAProSeriesSecureServerCA.crt", "AAACertificateServices.crt" ],
       "keyfile": "private.key"
       }
      }
     }

And see the same results.  I'm not sure whether I have a syntax error in the config file, or there's an issue with the certificate itself (though it works with Intel SCS and does remote ACM activation successfully). and where there may be a log file to show what's going wrong?  Thank you!

**Comment by Ylianst** [comment]
The "AmtAcmActivation" section must be located within the default domain section like this:

```
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
      "auth": "sspi",
      "AmtAcmActivation": {
       "log": "amtactivation.log",
       "certpfx": "cert_for_ms.pfx",
       "certpfxpass": "*password obscured*"
      }
    }
   }
```

As specified in your example, it would create a new domain called "AmtAcmActivation". Hope that helps.

**Comment by dubs740** [comment]
Thanks! That seems to have worked, and I can now assign "Simple Admin Control Mode (ACM) + CIRA" to a device group, but the test devices I have in the group don't seem to be activating.  Maybe I'm being naive in thinking the mesh agent should do so automatically now that the policy is applied? The test devices have their drivers and such installed, and are in an unconfigured state, so should be ready to activate.
