### ISSUE TITLE
MAC installation getting failed.

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1554]
![image](https://user-images.githubusercontent.com/9078295/85923431-96aa9680-b8a8-11ea-9afb-2213c355c814.png)

**Comment by krayon007** [comment]
Which version of macOS are you running? I just tried the installer on Mojave and Catalina, but could not reproduce your isssue.

**Comment by krayon007** [comment]
And which server version are you running?

**Comment by aimdharma1990** [comment]
I am trying to  install agent in Yosemite. I have downloaded agent from "
https://meshcentral.com/ "  cloud server.

**Comment by krayon007** [comment]
Did it ask for your password to elevate permissions? I just tried it with Yosemite, with www.meshcentral.com, and it worked fine for me.

**Comment by aimdharma1990** [comment]
Yes . It's prompted for password, post it proceeds and finally its given
then error popup. Is there any logs to check the error. ?

**Comment by SomeGuru** [comment]
Is this a direct MAC connected system or a VM? I see a lot going on in the window that has peaked my curiosity. Can you please elaborate the system in question?

I also was unable to reproduce this same behavior on my machines. I can however repro what looks to be similar in my Non-VMWare based VM controller.

Thanks,
SomeGuru

**Comment by aimdharma1990** [comment]
Its an Direct system which i am trying which i am connecting through VNC to
perform the installation ..

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
