### ISSUE TITLE
Dell / Intel AMT unable to wake from Deep sleep.

### ISSUE THREAD

**Issue by cahsdhelpdesk** [Ylianst/MeshCentral#1558]
Good morning.

I am not sure if this is a "real" issue across the board (affecting Intel or just Dell products) but I have noticed that when a Dell (PC or laptop), with AMT enabled, goes into "deep sleep" I am unable to wake it. When I try to connect to the KVM it states (in an orange bar) that the device is not in a powered state and to power it up. Sorry, I do not have a screen shot.

Right now I have discovered a couple of work arounds. One is to turn off "deep sleep" in the BIOS and the second, "reset" (reboot) the device with the latter not working 100%.

If it is just something localized I am fine turn off the "deep sleep" in the BIOS.

I just wanted to make you aware in case this is a real issue regarding sleep states.

Thanks again for all you do.

**Comment by Ylianst** [comment]
How are you trying to wake it? MeshCommander / MeshCentral?

**Comment by cahsdhelpdesk** [comment]
This particular case is a laptop. I have tried using both MeshCommander / MeshCentral. However, for some reason, even though the laptop currently shows "online" in MeshCentral, I cannot connect to AMT but I am able to with MeshCommander.

![image](https://user-images.githubusercontent.com/60752638/86035548-26178d00-ba02-11ea-99ab-03b5742a506c.png)
![image](https://user-images.githubusercontent.com/60752638/86035971-c66db180-ba02-11ea-966e-97852058fcc7.png)
![image](https://user-images.githubusercontent.com/60752638/86036049-df766280-ba02-11ea-9410-d08cb099a0d9.png)


![image](https://user-images.githubusercontent.com/60752638/86035420-f23c6780-ba01-11ea-94d4-a5e101668546.png)

**Comment by cahsdhelpdesk** [comment]
We have decided to disable "deep sleep" in the BIOS as our solution.
Thanks.
