### ISSUE TITLE
Privacy bar - broken in current version

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1559]
![image](https://user-images.githubusercontent.com/59362521/86036666-1c0f8180-ba36-11ea-955b-7861e52cc8d5.png)
Was fine in previous version, now it is on strange language.

**Comment by krayon007** [comment]
What language is that supposed to be displaying for you? (So I can do testing)

**Comment by vitko-bg** [comment]
English :)

**Comment by Ylianst** [comment]
Also, what operating system & CPU is on the remote computer? What version of MeshCentral?

**Comment by vitko-bg** [comment]
Remote system is W10 64 bit, Acer Aspire V5-122, MC - current latest one 0.5.75

**Comment by vitko-bg** [comment]
Tried on different W10 64 bit - result is same:
![image](https://user-images.githubusercontent.com/59362521/86037564-72c98b00-ba37-11ea-9ab2-76f1d917a214.png)

**Comment by krayon007** [comment]
I figured it out... There was a pending change in one of the files that wasn't commited yet. It's fixed now. It will be updated shortly.

**Comment by Ylianst** [comment]
Working on this now!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.76 with Bryan's fix.

**Comment by vitko-bg** [comment]
Thanks. Once tested will let you know.

**Comment by vitko-bg** [comment]
Fixed! Thanks.
