### ISSUE TITLE
meshcmd not working after update

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#156]
Not sure if related to issue #149 but after updating from 0.3.0-s to 0.3.1-p my mesh router is not working on any agents, linux or windows (no proxy just normal). Was always working before the upgrade. Am using latest binaries.
Turned on debug and when I initiate the connection, it just hangs forever and never connects. RDP and SSH both hang

![3389](https://user-images.githubusercontent.com/7434746/55115259-4fc86280-50a1-11e9-8ef7-3f27e79d8714.PNG)

**Comment by Ylianst** [comment]
Arg. Ok, taking a look into this.

**Comment by Ylianst** [comment]
I just tested [MeshCentral Router](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) and it worked for me. Going to test MeshCmd now...

**Comment by Ylianst** [comment]
I just tested MeshCmd and it worked for me. You can set "debuglevel" in the meshaction.txt to 1 and see what happens. Also, try the MeshCentral Router. Lastly, make sure your username and password are correct in the meshaction.txt file. Not sure I can do more without more data.

**Comment by wh1te909** [comment]
Thanks, sorry must be something going on with Azure where I'm hosting my original setup. Just tested on another cloud provider and it's working.

**Comment by Ylianst** [comment]
This is odd, it should work with any cloud provider. If in the future there are insights as to what happened, please feel free to add here.

**Comment by wh1te909** [comment]
Was able to spin up another identical VM in Azure and install meshcentral fresh.
Copied my config.json from original setup, only changing the subdomain...router still not working.

Reinstalled meshcentral on the new VM, used the new config.json and mimicked settings from original setup...router works now.

I haven't updated my config.json in months, have only been updating mesh with npm. I noticed the new one has a ton more options but is odd because I left them all commented out and just enabled whatever was on my original config, but for whatever reason the router starts working once I'm using the new config.json format.
