### ISSUE TITLE
Messenger is not scrollable .....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1560]
Hi, just had a chat using MC Messenger, and I can see that there is an option to export messages, but it is very uncomfortable not to be able to scroll up during the chat session. To see what I typed, possibly to copy some rows ...
And on both sides is the same - Mesh Agent computer and MC device - no scroll .....
Can this be fixed please?
THANKS!!!!

**Comment by Ylianst** [comment]
Wow, you right. Thanks for the report. Working on it now.

**Comment by Ylianst** [comment]
Just submitted a fix for this, will be in MeshCentral v0.5.76 when next published.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.76 with the fix for this.

**Comment by vitko-bg** [comment]
That's quick :) will test it on next release, and will let you know

**Comment by vitko-bg** [comment]
Confirmed - thanks a lot!!!
