### ISSUE TITLE
Localization set on English, yet noVNC on dutch

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1561]
I have set the localization to english manually as my browser is dutch.
The noVNC page and messages are in dutch.

I see that the noVNC uses it's own localization system, maybe it can be integerated for easy translating or the mesh localization setting can be checked if this language is available in noVNC.

**Comment by Ylianst** [comment]
I just submitted a fix for this, it will be in MeshCentral v0.5.78.

**Comment by Allowee** [comment]
Yes this is working correctly now, thanks for the fix.
