### ISSUE TITLE
in my eyes a dangerous condition... desktop -> connect -> to a terminalserver with several sessions -> cancel is missing!

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#1562]
during daily work with remote maintenance, if you are not careful, the following problem can occur: if i have selected a device for remote maintenance and in the register desktop -> connection -> to a terminal server with several sessions -> establish, there is no cancel button, so if i select another device under devices, because i click on desktop again and choose connect, i am still on the connection that was not cancelled before. i think it would be helpful if you can cancel the connection or if it would even end automatically... 

Translated with www.DeepL.com/Translator (free version)

**Comment by Ylianst** [comment]
I am not sure I understand, can you send a screen shot and indicate where you would like the cancel button? Thanks.

**Comment by wvt-adm** [comment]
i send you a screenmovie for explain ;-) to your mail adress. you see there that i open a device - go to desktop and press connect. now you see two sessions - i dont choos one - i go back to the device list and choos an other - go also to desktop and press connect - now i stay not in the device that i have choose the second - i stay now on the first one... thats not so cool ;-) hope you understand me. thanks am

**Comment by Ylianst** [comment]
Ok, I got the movie and see the problem. Thanks you. I will work on a fix.

**Comment by Ylianst** [comment]
I submitted a fix for this, it will be in MeshCentral v0.5.77. When you click connect and you see the session, there is no connection at that moment, so no need for "cancel". However, the session list is not cleared when changing to a different computer, this is a bug. I fixed that. Once you get the update, let me know if this is ok.

**Comment by Ylianst** [comment]
MeshCentral v0.5.77 is published, let me know if it works.

**Comment by wvt-adm** [comment]
i have test this with 0577 - but it is the same behavior... when i click to a terminalserver with more user online and no session choose, change to an other device and click connect i stay on the bevor choosd terminalserver sessions...

**Comment by wvt-adm** [comment]
since i was otherwise occupied, i could only test again today. this bug is fixed - at the moment i'm using version 0.5.85 - so i don't know exactly from which version this was fixed - but THANK YOU!! :-)
