### ISSUE TITLE
Enhancement request - Add user real name ....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1565]
In MC username to login to system is used  as identifier and cannot be changed,
Is there a way to add a real name field, or nick name, or just name - different from login name
It will be very useful for a lots of options - one of them let's say for privacy bar, so message can be customised with a name instead of username. I.E "Remote connection by John Smith is established" instead of "......john.smith@gmail.com ......"
Also if that name will be editable(as current username is not) - would be great.
Not sure how difficult is to implement it, but think it will be useful.
Thanks.

**Comment by unguzov** [comment]
I want to support this! Showing username on privacy bar can lead to security problem - now all my clients have our exact login names.

Also we want to show our company name on the privacy bar. 

Thanks!

**Comment by petervanv** [comment]
> I want to support this! Showing username on privacy bar can lead to security problem - now all my clients have our exact login names.
> 
> Also we want to show our company name on the privacy bar.
> 
> Thanks!

In the config.json there is an line: desktopprivacybartext. change its content there

![Screenshot_34](https://user-images.githubusercontent.com/58996467/87150733-ef1f6200-c2b2-11ea-9d61-01f272fa41ed.jpg)

than the text will be shon at the bar on top. (remember to remove the **_** )

**Comment by Ylianst** [comment]
Ok, I just submitted this change. It will be in MeshCentral v0.5.84 when its next published.

![image](https://user-images.githubusercontent.com/1319013/87183070-41a05480-c29a-11ea-94c0-219fab1bbf54.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.84 with support for real names.

**Comment by ckibodeaux** [comment]
It works on Ubuntu 18.04 (host and client) and was much needed. Thanks Ylian and team!

**Comment by vitko-bg** [comment]
@Ylianst In my config file I have a:
"desktopPrivacyBarText": "Operator \"{0}\" is connected",

{0} - is for User name or for Real name?

What are the options for Real and User names?

Thanks.

**Comment by Ylianst** [comment]
I just added it, starting with MeshCentral v0.5.86, you can use {0} for realname/username or {1} for username.

**Comment by vitko-bg** [comment]
Thanks for clarify. Closing issue now, as it is working as expected.
Thanks again for all effort!!!!
