### ISSUE TITLE
Enhancement request - MC Messenger - export button ...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1566]
In MC messenger it will be great to have next to "Microphone" and "Attach file" buttons one more button for export - to be able to export conversation.
It would be good to have it active even if one of the sides has closed the chat - so the other one can export it.
Thanks.
BTW - may all chats be stored somehow, similar to session recordings?

**Comment by Ylianst** [comment]
Export button, yes, I can add that.

**Comment by vitko-bg** [comment]
Thanks. I think it will be usefull for lot of MC users.

**Comment by Ylianst** [comment]
Ok, this will be in v0.5.78. Just checked it in.

![image](https://user-images.githubusercontent.com/1319013/86169976-4f521f00-bacf-11ea-9236-b245ac7b744f.png)

**Comment by vitko-bg** [comment]
Was about to write that it is not fixed, LOL, but checked that you said 0.5.78 version.
Current latest is 0.5.77
On next release will test it and will update issue. Thanks!

**Comment by Ylianst** [comment]
Right, I will publish it sometime today.

**Comment by Ylianst** [comment]
Closing this one since it's been published. I just improved the export to include the file sizes and time stamp of each message.
