### ISSUE TITLE
Enhancement request - Restart agent from console ...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1569]
I know that there is a way to restart Agent from Tools->Services on MC -> click on service and Restart...
The only concern is that first of all to open Tools menu takes some time, and after that in Services lots and lots of other services with no filter or find option.....(btw some filter or live search in services will be good idea also :) ) It is taking some time to find MeshAgent in services and to click on it to restart it. 
Is it possible to make an "agentrestart" command let's say, or some other so this can be done from a console window?
Or some filter in Services tab?
Or both :) :) :)
Thanks!

**Comment by Ylianst** [comment]
I think Bryan has a command for this, of course, such a command should not be commonly needed.

**Comment by vitko-bg** [comment]
@krayon007 please share info what command it is .... Thanks.

**Comment by vitko-bg** [comment]
No update on this issue since 2020, so closing it. If need the command or filter will open a new one.

**Comment by si458** [comment]
This is already possible, You can go in to the console tab and type 'service restart'
