### ISSUE TITLE
Secure connections to MySQL

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1570]
I'm a little unsure as to whether or not MySQL is officially supported as of yet, but from what I can see, there doesn't appear to be any settings for a secure connection to the database. 

I'm setting up MC2 in an AWS cloud environment and got to thinking that I can use an Aurora database and utilize EFS as the location of the config files. I will probably only have a single server hosting everything (although if I have everything in EFS, then one could pose the question that I could set up an auto-scaling group of more than one hosted server?!) but I want to ensure that everything within that environment is secure, including the database connections.  If my database is set up to "require SSL" for the MC2 user, are there any settings within the config that I can set that enforces that, maybe by providing access to a combined PEM file from the database?

**Comment by Ylianst** [comment]
MeshCentral makes use of the [MySQL package on NPM](https://www.npmjs.com/package/mysql) for connecting to the MySQL database. It does support TLS connection along with [many TLS options](https://www.npmjs.com/package/mysql#ssl-options). So, I think you should be alright in connecting to MySQL securely. I don't test MySQL much, but let me know if you run in any issues.
