### ISSUE TITLE
Feature Request: Multi-Monitor Pop-out

### ISSUE THREAD

**Issue by orthelan** [Ylianst/MeshCentral#1571]
It would be handy to be able to pop-out each monitor on a multi-monitor client at full resolution into their own window that can be moved, viewed, and managed independently of one another.

**Comment by southeasterntech** [comment]
+1

**Comment by robclay** [comment]
+1 and I think this is the same as https://github.com/Ylianst/MeshCentral/issues/1105

**Comment by Ylianst** [comment]
Published MeshCentral v0.9.75 with a new version of MeshCentral Router that can "popup" displays if the remote device has multiple desktops.

![MC2-RouterDesktopSplit](https://user-images.githubusercontent.com/1319013/151681558-a37b69c5-3091-4502-9f99-1e5a31a2e4b3.png)

**Comment by robclay** [comment]
Tested quickly - works at first glance!  Thanks Ylianst!

**Comment by vitko-bg** [comment]
Amazing! I'll test it and will close one of my requests as I had a request fot this option. Thanks!

**Comment by southeasterntech** [comment]
Amazing!  Thanks Ylian!  Any chance of seeing this in the web interface in the future?

**Comment by dinger1986** [comment]
@si458 sorted can close
