### ISSUE TITLE
Cannot connect if RDP session active

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#1572]
Cannot desktop connect to a remote computer if someone is RDPed to the remote computer. This was not the case with MeshCentral v1. Using meshcentral.com.

**Comment by krayon007** [comment]
This issue was fixed in a newer server version then is currently on meshcentral.com... We will update meshcentral.com after the holiday weekend.

**Comment by FilGov** [comment]
Thank you.
