### ISSUE TITLE
DNS confict

### ISSUE THREAD

**Issue by Maxime1988** [Ylianst/MeshCentral#1578]
Hi,

I have a trouble with my dns configuration. I use NextCloud at home on RasperryPi and everything is fine. But now I installed MeshCentral on another RaspberryPi. On local network everything is fonctional.

I use DuckDns.org for using NextCloud and MeshCentral outside out of my network. NextCloud work, but when I want connect on the DNS adress of my MeshCentral I'm on an NextCloud page ''Access through untrusted domain''. But I dont want this address point on NextCloud but MeshCentral.

In my DuckDns page the two domain names are different but the ip address are the same, maby it's the problem. But when i change manually the ip, my MeshCentral domain name doesn't work.

Maby someone has already had this kind of conflict.

Thank a lot and have a nice week end.

Maxime

**Comment by Ylianst** [comment]
So, I imagine you have a single external IP address. In that case, unless you have a reverse proxy running in your home (like NGINX) you can't have the same port 443 shared between the two services. You can ether move MeshCentral to a different port (say port 444) or your going to have to use a reverse proxy to detect that domain name was used to access port 443 and route the connection to the right place.

If you just want to keep it simple, just register one name to your IP address in DuckDns and access https://myserver for NextCloud and https://myserver:444 for MeshCentral.

Hope that helps,
Ylian

**Comment by Maxime1988** [comment]
Ok I will try. It's automatic for the port if I install MeshCentral and I make the cert --myserver:444 or how I put MeshCentral on port 444?

Thank you

**Comment by Ylianst** [comment]
It's not automatic, in the settings section of config.json, set the port to 444 like this:

```
{
  "settings": {
    "port": 444
  }
}
```

**Comment by Maxime1988** [comment]
Hi,

Thank for the advice. I try like this as soon as possible. I cannot add :444 on Duckdns dashboard. So I will try with the config.json file only.

I keep you in touch.

Maxime

**Comment by Maxime1988** [comment]
It's not functionnig like this : 
My json file dont have my good information for domain and other thing, is it normal?
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 444,
    "_aliasPort": 444,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

And my server, after reboot dont take the port. Maby I have to remake the ''cert --'' part?

pi@raspberrypi:~/meshcentral/node_modules $ node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.78, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on myXXXXXXXXXXXXXXXX.duckdns.org:4433.
MeshCentral HTTPS server running on myXXXXXXXXXXXXXXXX.duckdns.org:443.

Maby I missunderstand your advice?

Have a nice day

Maxime

**Comment by vitko-bg** [comment]
Looks like you misunderstood...
All parameters with _(underline) in front are comments...
So, put back "comment": to "_comment": and all parameters that you need, remove the underline, i.e.
"_cert": "myserver.mydomain.com", have to be "cert": "myserver.mydomain.com", in order to have it working.....

**Comment by Maxime1988** [comment]
Thank for the advice man,

The setting for port seem functioning but the server is not reachable. Sorry for this, i'm obviously not an network expert.

**My browser** (out of my internal network of course) say :  

Secure Connection Failed

An error occurred during a connection to myXXXXXXXXXX.duckdns.org:444.
PR_CONNECT_RESET_ERROR
    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**This is my json :** 
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "myXXXXXXXXXX.duckdns.org",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

**and my terminal :** 
pi@raspberrypi:~/meshcentral/node_modules $ node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.78, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on myXXXXXXXXXX.duckdns.org:4433.
MeshCentral HTTPS server running on myXXXXXXXXXX.duckdns.org:444.

Thank for your time.

Maxime

**Comment by Ylianst** [comment]
Your MeshCentral server is using the default self-signed HTTPS certificate, browsers will indicate an error because the site is not trusted. This is normal for your configuration, you will need to tell the browser to ignore the warning and connect anyway. If you want to solve that problem, you need to get a HTTPS certificate using Let's Encrypt which is a different issue. Hope that helps.

**Comment by Maxime1988** [comment]
Hi,

I follow your advice, and your user guide for using Let's Encrypt. I wait one night for the certificate, but this morning the letsencrypt-certs is still empty. However, Let's Debug site say my dns is ''all ok''. maby somthing missing in my json?

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "myXXXXXXXXXX.duckdns.org",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "XXXXXXXXXX@gmail.com",
    "names": "myXXXXXXXXXX.duckdns.org",
    "rsaKeySize": 3072,
    "production": false
  }
}

The server install somethings and create the cert folder
pi@raspberrypi:~/meshcentral/node_modules $ node meshcentral
Installing acme-client...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.81, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on myXXXXXXXXX.duckdns.org:4433.
MeshCentral HTTPS server running on myXXXXXXXXXX.duckdns.org:444.

And i have the correct version of nodejs
pi@raspberrypi:~ $ nodejs -v
v10.21.0

I dont understand why I dont receve certificate this night. Do you have any ideas for this?

Thanks again.

Maxime

**Comment by Ylianst** [comment]
If port HTTP/80 from the Internet routed to port 80 on MeshCentral?

Also, can you go in "My Server" / "Console" and type "le" and "leevents" and send back the result? For example:

![image](https://user-images.githubusercontent.com/1319013/87131471-50125000-c249-11ea-9ff7-a192f6868784.png)

**Comment by Maxime1988** [comment]
HI,

For the port I think it's ok because before I install NextCloud I can lauch MeshCentral via my DNS adress.

This is my printscreen, is not like yours...
![2020-07-10-164353_1920x1080_scrot](https://user-images.githubusercontent.com/67804875/87167656-9b6e4200-c2cd-11ea-92e4-371d07893cc3.png)

Thank you

Maxime

**Comment by Ylianst** [comment]
It's certainly trying to get a certificate and it's not working out. MeshCentral is not getting the ACME challenges on port 80. In other words, Let's Encrypt will try to access "http://yourserver:80/challenge" and MeshCentral is not getting this request and so, can't answer it.

If your making a request to port HTTP port 80 from the Internet and it's landing on a different server, this is not going to work.

**Comment by Maxime1988** [comment]
Maby this port is already using by NextCloud. Can I change this port on MeshCentral config.json?

**Comment by Ylianst** [comment]
I can't help you with your port mappings, the external port 80 needs to be mapped to port 80 on MeshCentral. This is not something you can configure in MeshCentral.

**Comment by Maxime1988** [comment]
Ok thank you,

I try to change directly on the option page to my modem but he ask me some option and when I click ok he talk about upnp.

![2020-07-10-201508_1920x1080_scrot](https://user-images.githubusercontent.com/67804875/87185866-c4510000-c2ea-11ea-946f-1753605cb7f5.png)
![2020-07-10-201703_1920x1080_scrot](https://user-images.githubusercontent.com/67804875/87185867-c4e99680-c2ea-11ea-94f6-19dd0ac59391.png)

**Comment by Maxime1988** [comment]
Thank for your great help.

I will make some change. I see the port 80 is ok. I change the port of the Next Cloud. Maby...

I have a last question and I stop to borring you : If I use the same DNS name on MeshCentral and NextCloud, just the port change, do you thing thas work? Or maby install the two service on the same Pi is better?

thank again and have the nice week end

Maxime

**Comment by Ylianst** [comment]
I am not sure I understand your question. If you using the same DNS name for both services you must to use different ports or use a reverse proxy (For example, NGINX). If you want to get a Let's Encrypt certificate, you must route external port 80 to MeshCentral port 80.

**Comment by Maxime1988** [comment]
Ok I dont know how it's work but I have to check this.

Thanks again.

Maxime

**Comment by Maxime1988** [comment]
Hi,

I try with nginx. I follow step by step your user guide but now my terminal say :
pi@raspberrypi:~/meshcentral/node_modules $ node meshcentral
ERROR: Unable to parse /home/pi/meshcentral/meshcentral-data/config.json.

I send you my config.json and my nginx.config maby I make a mistake.
[configjson.txt](https://github.com/Ylianst/MeshCentral/files/4914859/configjson.txt)
[nginxconf.txt](https://github.com/Ylianst/MeshCentral/files/4914860/nginxconf.txt)

Thank for your time and sorry for all my question.

Maxime

**Comment by Ylianst** [comment]
JSON files have a very specific format. If you run into this problem, you can use the [DuckDuckGo JSON lint](https://duckduckgo.com/?q=json+lint&t=ffnt&ia=answer).  You can cut & paste your JSON into it and it will show you where the error is. Below, I fixed you config.json.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "Cert": "myXXXXXXXXXX.duckdns.org",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AgentPong": 300,
    "TlsOffload": "127.0.0.1"
  },
  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443/"
    }
  }
}
```
