### ISSUE TITLE
Config.json parameters

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1579]
Hello, where can I find the manual about all the parameters of the config.json file? I want to configure the recordings on the server but I have seen that there are configurations where they limit the size and quantity of recordings but I cannot find these parameters.

**Comment by Ylianst** [comment]
This is an area where documentation is far behind the implementation. In the future, I do want to look at creating an web-based configuration editor, but for now there is a trick I was working on. I was writing the config.json schema, it's a file called "meshcentral-config-schema.json" that is in the "node_modules\meshcentral" folder. If you edit the config.json using Visual Studio or some fancy JSON editor, you can put the following $schema line in your config.json:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "Cert": "local.mesh.meshcentral.com"
  }
}
```

After that, Visual Studio will auto-complete and validate your config.json. It will also give you tips on each values. All this said, for recordings it looks like this:

```
      "SessionRecording": {
        "filepath": "/root/meshcentral/meshcentral-recordings",
        "index": true,
        "maxRecordings": 100,
        "maxRecordingSizeMegabytes": 100,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [
          1,
          2,
          101
        ]
      }
```

Hope that helps,
Ylian

**Comment by desarrollocdb** [comment]
Thanks, it's perfect.
Thanks, it's perfect.
