### ISSUE TITLE
MeshCentral User disable create mesh / meshcmd

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#158]
I have the requirement for a vendor's support staff to be able to remote into one of my systems. I've set them up with 

1. Remote Control
1. Server Files
1. Remote View only

However when in testing, I see that when I log in under their account, they are are able to **add a device group** and create a **meshcmd**. 

I think these are rights that shouldn't be exposed with the three permissions granted to them.

**Comment by Ylianst** [comment]
Good point. I am on vacation until next Wednesday and have plenty on the todo list. However, I will take a look at fixing this when I get back.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.1-y with two additional server permissions to restrict new groups and meshcmd. In the case of MeshCmd, technically it only removes the link right now, but you could still use MeshCmd. Can you try it out and see if this works for you? - Thanks.

![MC2-ServerRestrictions](https://user-images.githubusercontent.com/1319013/55664806-3c2ba300-57e9-11e9-83d4-b78634119a47.png)

**Comment by Ylianst** [comment]
Comments on this? Probably works, but would be nice to have feedback.

**Comment by D4V3M0NK** [comment]
Apologies, dropped the ball on this Ylian...

So I see that the default is to permit a non-admin user to have rights to create a mesh group and meshcmd. I'm more of the opinion that - by default - a user shouldn't have any rights whatsoever. If I want to grant those rights, then so be - I have to go into their account and apply them. However, I'm also aware that my requirements for the system may be different to others, in which case they probably do require those rights. Therefore I propose that there's a control that as an admin, I can set the default permissions when a new user is created. I believe that that would address all eventualities.

So, that being said, I've created a new user and logged in as them and see that I can create groups and cmds. After logging in as an admin, and then selecting their permissions to "No new Device Groups" and "No MeshCmd" I see that they're permissions are set to "User*" (nice to see that there's a visual change from the default). When I log in as them, I do see the "To get started, click here to create a device group" but when I click on it, I have no permissions. From a UX point of view, I'm of the opinion that WYSIWYG ... if I see that link, I expect to be able to use it, rather than click it and be told that I don't.

Just my point of view sir.



Dave


On Wed, 2019-04-10 at 11:56 -0700, Ylian Saint-Hilaire wrote:

Comments on this? Probably works, but would be nice to have feedback.

**Comment by Ylianst** [comment]
Good feedback. So two things:
- Add a config.json setting to set the default user permission when a new user is created.
- Remove all references to adding a group in the UI if you don't have access.

Would that be ok?

**Comment by D4V3M0NK** [comment]
Sounds like a plan to me sir. IMHO, for any permission based role, don't show the feature in the GUI if you don't have access to it. MeshCentral is exceptionally dynamic in assigning permissions and having the UI update immediately, so if users get used to that (as one would expect them to) then not seeing something means you simply don't have that level of access. You may notice I've added a comment in the closed ticket 101 regarding user permissions, which also follows this train of thought (ie, a user has no access to Terminal or Files, but I see the tabs when I log in as them ... I also do have access, which is the reason for the post on #101)

On Wed, 2019-04-10 at 13:30 -0700, Ylian Saint-Hilaire wrote:

Good feedback. So two things:

  *   Add a config.json setting to set the default user permission when a new user is created.
  *   Remove all references to adding a group in the UI if you don't have access.

Would that be ok?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.2-h with all links to create a group removed on the desktop app when you don't have rights to do so. Just realized I forgot to do the same on the mobile app, working on that now.

**Comment by Ylianst** [comment]
Actually, I did not allow group creation on the mobile app, but fixed a few things. It will be in the next release.

**Comment by Ylianst** [comment]
Closing this one as a new user permission setting fixes this issue.
