### ISSUE TITLE
Personalize de e-mail inviation

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1581]
There is anyway to personalize the e-mail invitation message like what ever i want for example writting a kind of mini tutorial of how to intall the agent in the body of the message.

![imagen](https://user-images.githubusercontent.com/67141657/86562047-4e533e80-bf62-11ea-9580-752c9f6746ee.png)

**Comment by Ylianst** [comment]
Yes, you can customize the emails. Create a new folder called "emails" in the "meshcentral-data" folder, then copy the "node_modules/meshcentral/emails" files into it and change the email files like you want.

What is nice is that when you update the server, your customized emails will stay. Hope that helps.

**Comment by guru69** [comment]
My Mesh server has 2 separate domains, how can each domain have its own custom emails folder for invites, etc?

**Comment by Ylianst** [comment]
Yes, add the following line in the domain section:

```
"WebEmailsPath": "/myserver/email-templates"
```

You put the path to the email templates you want for this domain. Hope that helps.

**Comment by CLAVERATOR** [comment]
> node_modules/meshcentral/emails

What is the comand toc copy directorys into another directory because i am trying with "cp"

**Comment by CLAVERATOR** [comment]
> 
> 
> Yes, add the following line in the domain section:
> 
> ```
> "WebEmailsPath": "/myserver/email-templates"
> ```
> 
> You put the path to the email templates you want for this domain. Hope that helps.

![imagen](https://user-images.githubusercontent.com/67141657/87636988-de06a300-c741-11ea-970b-70d6e2c0c71b.png)


I don't know why it does n¡t work

**Comment by CLAVERATOR** [comment]
https://github.com/Ylianst/MeshCentral/issues/1581#issuecomment-654336892

![imagen](https://user-images.githubusercontent.com/67141657/87637246-3ccc1c80-c742-11ea-8a6c-b56c74d2ed6f.png)
i think i putting the comand in a wrong way

**Comment by CLAVERATOR** [comment]
> 
> 
> Yes, you can customize the emails. Create a new folder called "emails" in the "meshcentral-data" folder, then copy the "node_modules/meshcentral/emails" files into it and change the email files like you want.
> 
> What is nice is that when you update the server, your customized emails will stay. Hope that helps.

As you say i copy the emails folder into the meshcentral-data but i do not receive an update of the email customization 

![imagen](https://user-images.githubusercontent.com/67141657/87638583-4fdfec00-c744-11ea-91ba-24b05363a4d2.png)
