### ISSUE TITLE
I have a problem with the certificate generate with let's encrypt 

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1582]
This is my let´s encryp configuration in my config.json file 
![imagen](https://user-images.githubusercontent.com/67141657/86565636-7cd41800-bf68-11ea-9f72-cb924a8761d7.png)

Then i restart the server, and automatically the server generates this directory 
![imagen](https://user-images.githubusercontent.com/67141657/86565682-983f2300-bf68-11ea-83dd-19b7fd7e9ff4.png)
I understand that is the directory where the certificates are located but for me this directory is empty and the server is not generating any certificates at all

**Comment by Ylianst** [comment]
Hi. To debug this, you can run `node node_modules/meshcentral --debug cert`. This will display what is going on with Let's Encrypt. You can also go in the "My Server / Console" tab and type "le" and "leevents" to see the status and last events.

Lastly, make sure to check your server using https://letsdebug.net to make sure everything is ok. HTTP port 80 needs to be exposed on the Internet for Let's Encrypt certificate checking to work.

**Comment by CLAVERATOR** [comment]
Hellow @Ylianst 

First of all thank you for the support 

Secondly i got this code error when let's Encrypt is trying to generate a certificate

![imagen](https://user-images.githubusercontent.com/67141657/87278446-c41c5480-c4e4-11ea-8f9e-4eb6606f9909.png)

**Comment by Ylianst** [comment]
So, to be clear, you need to ask Let's Encrypt for a DNS name that you own, the DNS name needs to point to MeshCentral server, the external port 80 needs to route to port 80 of the MeshCentral server.

I see above your asking for a certificate for "atlas-sap.com", if I try to access that DNS name, it's not pointing to your MeshCentral server, so, that is not going to work.

By the way, Let's Encrypt server will only give you a certificate if you can prove you have control over the DNS. Let's Encrypt is not a library that will "generate" you a certificate. It will talk to the Let's Encrypt server and check your server. I hope this is clear.

**Comment by CLAVERATOR** [comment]
Thank you so much @Ylianst 

Now i FIX IT

The problem was that the dns name was not pointing to the server
