### ISSUE TITLE
dbExpire not working

### ISSUE THREAD

**Issue by untipocualquiera** [Ylianst/MeshCentral#1584]
Hi Ylianst,
First of all I want to congratulate you because MeshCommander and MeshCentral development. I think that MeshCentral is the best software I found for several years. I want to "delete" / "clean" events log. I have found your solution and I have added dbExpire to config.json and reboot server.

![image](https://user-images.githubusercontent.com/67922455/86624805-40360a00-bfc4-11ea-9339-078601919552.png)

After this steps, I have events from two weeks:
![image](https://user-images.githubusercontent.com/67922455/86624981-9905a280-bfc4-11ea-9d33-9f94d057d2c5.png)

Sorry for the inconveniences.

Best regards.

**Comment by Ylianst** [comment]
Thanks for the report, I will take a look at it. What database are you using? The built-in one (NeDB) or did you configure MongoDB?

**Comment by untipocualquiera** [comment]
Hi Ylianst,
I have the built-in one NeDB. MeshCentral version 0.5.78.

Thanks!

**Comment by Ylianst** [comment]
I see the problem, got a fix for it. Note that in your config.json, the following lines:

```
    "DbExpire": {
      "events": 120,
      "powerevents": 120,
      "statsevents": 120
    }
```

The 120 is the number of seconds to keeps the log entries. So, this will only keep events for 2 minutes. You probably want to change this to a higher number before updating to MeshCentral v0.5.81 that will have the fix for this.

**Comment by untipocualquiera** [comment]
Hi Ylianst,
Many thanks for your quick reply and solution. It seems solved:
![image](https://user-images.githubusercontent.com/67922455/87021922-118f7d80-c1d6-11ea-9f61-97df7298ed6b.png)

Thanks for this software!!

Best Regards.
