### ISSUE TITLE
Encourage users to show their support on OpenHub.net (Synopsys Black Duck Open Hub)

### ISSUE THREAD

**Issue by marclaporte** [Ylianst/MeshCentral#1585]
https://www.openhub.net/ is a fantastic ressource.

Here is the entry about MeshCentral: https://www.openhub.net/p/MeshCentral

I think we should promote this. Ex.: 

Please show your support for MeshCentral by clicking "I Use This" on Open Hub.

Thus, a better ranking in examples like this:
https://www.openhub.net/tags?names=vnc

Thanks!

Marc

**Comment by Ylianst** [comment]
Nice! I did not know about this. Thanks for posting.
