### ISSUE TITLE
Problem conecting desktop in virtual servers 2019

### ISSUE THREAD

**Issue by CLAVERATOR** [Ylianst/MeshCentral#1586]
Hi 

I don't know why when i intall the agent in virtual servers 2019 it appears this message

![imagen](https://user-images.githubusercontent.com/67141657/86741126-7365b100-c037-11ea-907b-3aa2a439ffcd.png)

What does it mean?

and i Can not conect with the desktop

**Comment by PathfinderNetworks** [comment]
When you connect to a device that uses RDP and has multiple active logins you can select which login to view.  On that screen you just click the login you want to connect to then the desktop display will load.

**Comment by CLAVERATOR** [comment]
ok thank you so much
