### ISSUE TITLE
Error log location?

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1587]
Forgive the rather simple question, but where's the MC2 error file? I'm trying to get a "secure" installation running and the service keeps failing and I'm sure something's being posted into a file somewhere, but I can't seem to find it?!

**Comment by D4V3M0NK** [comment]
and of course, as soon as I post I think about using syslog...

**Comment by Ylianst** [comment]
If MeshCentral crashes, it will save the exception in "mesherrors.txt" file in "meshcentral-data". You can see this file on the web interface by going in the "My Server" tab and clicking the "Show server error log" link.
