### ISSUE TITLE
Is there a way to link existing letsencrypt cert

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1590]
At this moment I am running my sites with Apache on port 80 and 443 and mesh on port 444, on linux.
This way it is not possible to get a letsencrypt cert for mesh, but they are present for the Apache websites.

Is there a way to symlink the existing cert, for the same domain I also use for mesh, to the mesh central webserver cert?

I want to avoid setting up a reverse proxy, would this be possible?

**Comment by Ylianst** [comment]
Yes, in the "meshcentral-data" folder, look for these two files:

```
webserver-cert-public.crt
webserver-cert-private.key
```

They are both text files you can edit and take a look at them. You can them rename them to ".bak" and add symlinks to the equivalent files in Apache. Once done, restart the MeshCentral server and you should be good. Let me know if that works.

**Comment by Allowee** [comment]
Okay cool, that works!

On Windows server I have the same issue, but I have a purchased certificate available.
The file only contains "-----BEGIN CERTIFICATE-----"
Any idea how I would be able to use that for the meshcentral webserver?

**Comment by Ylianst** [comment]
On Windows, you can rename the existing certificate files to add "-bak" and put the new files you paid for in the "meshcentral-data" folder instead. Just rename them to match the names:

```
webserver-cert-public.crt
webserver-cert-private.key
```

If your paid certificate is in .p12 format, you will need to convert it to extract the .key file. In some cases when you buy a certificate from GoDaddy or others, they are directly imported into the Windows certificate store, if the certificate is marked for export, you can export is and convert it.

Another way to do this is to go back to your certificate provider and, even if you are using Windows, just pretend you are using Linux and download the certificate in Linux format.

Hope this helps,
Ylian

**Comment by Allowee** [comment]
Ah yes I was trying to use the wrong cert.
Found that I needed to export the private key to a different format.

Thanks for the help!
