### ISSUE TITLE
Question: Does MeshCental support Global Catalogs (GC) with LDAP authentication queries?

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#1592]
## Problem Description
It looks like LDAP querying use the **Global Catalog** may not work, that said, for me, this has never worked, so it's unclear to me if I've just mis-configured it, or it's not supported. Since the `Active Directory` server is not under my control, I am unable to test using the **Active Directory** method.

## Background
Through my research it looks like there are two methods (**Active Directory** vs **Global Catalog**) that LDAP supports for query, and SSL on top of these two methods, which are outlined in the following table. From my understanding a `Global Catalog` contains every object in the `Active Directory Forest` as opposed to `Active Directory` only containing the objects from a single `Active Directory` domain. Additionally the `Global Catalog` contains a **Partial Attribute Set** (PAS) as defined by the **Schema**. (If any of this is incorrect, please feel free to comment!)

| Port     | Description                           |
| :------- |:------------------------------:|
| 389      | Active Directory Plain Text   |
| 636      | Active Directory over SSL/TLS    |
| 3268    | Global Catalog Plain Text    |
| 3269    | Global Catalog over SSL/TLS      |

As per https://github.com/Ylianst/MeshCentral/issues/165 it looks like MeshCentral has implemented LDAP using `ldapauth-fork`. I've looked at https://www.npmjs.com/package/ldapauth-fork which leads me to https://github.com/vesse/node-ldapauth-fork briefly, but I'm unable to determine if it supports the **Global Catalog** method, most of the examples that I have found use the **Active Directory** method (Both SSL and plain text), but not the **Global Catalog** method. I'm also not a windows person, so `Active Directory` is very much a black box to me.

### Server OS
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

### Memory
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:          16039         320       14870           0         848       15448
Swap:             0           0           0
```

### MeshCentral Version Information
MeshCentral v0.5.75, WAN mode, Production mode.

### MeshCentral Configuration
I've tried both `ldap://` and `ldaps://` in the url, the result is the same.
```
# cat config.json
{
  "settings": {
    "Port": 443,
    "RedirPort": 80,
    "WANonly": true,
    "Cert": "<COMPANY.COM>",
    "allowLoginToken": true,
    "SessionTime": 30,
    "AgentPong": 60,
    "MongoDb": "mongodb://<MESHDB_USERNAME>:<MESHDB_PASSWORD>@<MONGODB_IP>:27017/meshcentral"
  },
  "domaindefaults": {
    "twoFactorCookieDurationDays": 7,
    "UserSessionIdleTimeout": 30,
    "UserQuota": 1048576,
    "MeshQuota": 248576,
    "NewAccounts": false,
    "PasswordRequirements": {
      "min": 8,
      "max": 128,
      "upper": 1,
      "lower": 1,
      "numeric": 1,
      "nonalpha": 1,
      "reset": 90,
      "force2factor": true
    }
  },
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
      "UserAllowedIP": "127.0.0.1"
    },
    "Domain3": {
      "Title": "test company 3",
      "auth": "ldap",
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "objectSid",
      "ldapOptions": {
        "_url": "ldap://<LDAP_IP>:3269",
        "url": "ldaps://<LDAP_IP>:3269",
        "bindDN": "CN=Darryl,CN=Users,dc=CORP,dc=<COMPANY_NAME>,dc=COM",
        "bindCredentials": "<PASSWORD>",
        "searchBase": "DC=CORP,DC=<COMPANY_NAME>,DC=COM",
        "searchFilter": "(sAMAccountName={{username}})"
      }
    }
  }
}
```

## Symptoms:
In Chrome, when I try to access the secure LDAP page, I get the following error: 

```
This page isn’t working
<PUBLIC.IP.ADDRESS> didn’t send any data.
ERR_EMPTY_RESPONSE
```

### mesherrors.txt file
When I attempt to access this domain, I get the following error, note that I am able to access other domains hosted on the same MeshCentral server without an issue.
```
-------- 7/8/2020, 3:50:20 PM ---- 0.5.75 --------

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
```

## Ask
1) Does ldapauth-fork support Global Catalogs?
2) Assuming ldapauth-fork does support Global Catalogs, can you point me in the right direction for my configuration?
3) Do you need any additional information from my AD server to move forward (Please be as specific as possible, if you could tell me what commands you would like me to run, that would be ideal, as I'm not experienced with AD)
4) Is there a way to increase the logging for this error, the `mesherrors.txt` file doesn't give me a lot of clues here.

:star_struck: As always, thanks for your assistance and great work over the past decade+ on this software!

**Comment by dinger1986** [comment]
this should probably be converted to a discussion or closed @si458
