### ISSUE TITLE
[Feature Request] Run batch command and batch file send

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#1595]
Hello Ylian,

Is been a long time since i last checked in due to Covid and furlough leave.

I would like to request a feature where you can select multiple or all the computers from the group create jobs and send a batch command to complete with time interval between batches e.g. i have 100 machines and i want to run an unzip command for a group of 10 machines every minute until all 100 machines are completed. And same for file send on a default directory.

Kind regards

**Comment by PTR-inc** [comment]
You could check out this one:
https://github.com/ryanblenis/MeshCentral-ScriptTask

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.5.85, you can now select many devices and in "Group Actions", select "Run Commands". That will run a set of shell commands on all the selected computers. You can see the execution in the agent console.

![MC2-BatchShellExec](https://user-images.githubusercontent.com/1319013/87232298-9dd6a780-c372-11ea-8290-b0f1a712adc7.png)

Feedback on this appreciated.

**Comment by cgb** [comment]
Hi Yilan,

This looks like a great addition!  One question about invoking this - is there a way to trigger or perform this via the CLI of a MeshCentral server?  e.g. via meshctrl.js or similar?

Thanks!

**Comment by penguinthingie** [comment]
> Starting with MeshCentral v0.5.85, you can now select many devices and in "Group Actions", select "Run Commands". That will run a set of shell commands on all the selected computers. You can see the execution in the agent console.
> 
> ![MC2-BatchShellExec](https://user-images.githubusercontent.com/1319013/87232298-9dd6a780-c372-11ea-8290-b0f1a712adc7.png)
> 
> Feedback on this appreciated.

WHOA!!!! THAT IS AN AWESOME addition!!!! Thank you @Ylianst !

**Comment by treicadani** [comment]
This is an awesome new addition to the project the commands works as expected but the file transfer only works by single group, could it be done the same way as the commands function?

Many thanks

**Comment by Ylianst** [comment]
@cgb Working on adding more command exec to MeshCtrl.js now.
@penguinthingie  Thanks!!!!
@treicadani I don't think we have batch file transfer yet? Can you explain "file transfer only works by single group"? Thanks.

**Comment by treicadani** [comment]
I am sorry i meant to write single machine, i guess i had groups in mind.

**Comment by Ylianst** [comment]
Got it. Yes, at some point, batch upload/download would be an excellent feature request.

**Comment by Ylianst** [comment]
Ok, check in a new "RunCommand" in MeshCtrl.js, for example:

```
node meshctrl.js runcommand --id oL4Y6Eg0qjnpHFrp1AxfxnBPenbDGnDSkC@HSOnAheIyd51pKhqSCUgJZakzwfKl --run "echo abc" --powershell
```

This will run "echo abc" as PowerShell on a remote device. This will be in MeshCentral v0.5.86.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.86 with the added "RunCommand" feature in MeshCtrl.js

![MC2-RemoteCommand](https://user-images.githubusercontent.com/1319013/87360113-3f4e2c80-c51e-11ea-8d63-e8c43aa32ed1.png)

As a bonus, MeshCtrl.js also has a new "shell" command to shell into a remote devices.

![MC2-RemoteShell](https://user-images.githubusercontent.com/1319013/87360148-54c35680-c51e-11ea-8ee1-053a7a18fa8f.png)

Feedback appreciated.

**Comment by cgb** [comment]
Hey Yilan,  Fantastic, thank you for the meshctrl addition.  Running once-off commands to Win10 via command prompt and powershell seem to work.

Would there be any way to support the output to stdout rather than log to the console?  I'm envisaging a use-case where I can automate the execution & collection of output from an agent.

Also I've tried shell support from a Linux MeshCentral server and it doesn't appear to work:

`$ node ./node_modules/meshcentral/meshctrl.js \
   --url wss://mesh.mydomain  \
   --loginkeyfile key.txt \
   --loginuser myuser \
    Shell \
   --id 'myNodeId'
Connecting...
Waiting for Agent...
Connection Closed.

$ node ./node_modules/meshcentral/meshctrl.js  \
    --url wss://mesh.mydomain  \
    --loginkeyfile key.txt \
    --loginuser myuser \
    Shell \
    --id 'myNodeId' \
    --powershell
Connecting...
Waiting for Agent...
Connection Closed.
`

Any suggestions on debugging or can I provide more information?  Thank you... :)

**Comment by MordyT** [comment]
@Ylianst can you add a permission for being able to use this new feature?

**Comment by Ylianst** [comment]
@MordyT You need the "Remote Control" permission, this is the same permission needed for the terminal on the web site.

**Comment by MordyT** [comment]
@Ylianst Yes, removing remote control blocks it. I want to block it without losing remote control.

On the web I can use No terminal to remove terminal tab, but this is still present.

**Comment by Ylianst** [comment]
@cgb Just found and fixed the shell connection bug. It will be fixed in MeshCentral v0.5.87.

**Comment by Ylianst** [comment]
@MordyT Just fixed it, "No Terminal" will also block MeshCtrl.js Shell in MeshCentral v0.5.87.

**Comment by cgb** [comment]
@Ylianst I've manually tested the fix and it is working now.  Thank you for the quick fix! :)

**Comment by Ylianst** [comment]
Wow, your fast. Yes, the fix was small.

**Comment by MordyT** [comment]
> @MordyT Just fixed it, "No Terminal" will also block MeshCtrl.js Shell in MeshCentral v0.5.87.

I tested on version 0.5.88 and still have Run Command when no terminal is set. Do I have to set any config.json options?

**Comment by Tomatoschewps** [comment]
Hi @Ylianst ,
"Run Commands" is really a great feature , thanks for it (and batch run commands from agent list ^^)
By using it i've seen that we don't have much details on log page. Basically we don't see who have launch commands :
`
15:06:51 - <Agentname> → Running commands
`
