### ISSUE TITLE
HTTP ERROR 403

### ISSUE THREAD

**Issue by NeeDforKIll** [Ylianst/MeshCentral#1599]
Hello, first time try to use Mesh Central. Installed by MeshCentralInstaller  on Windows 10 machine for test.  Server mode Lan, getting this http error 403 in any browser. 
Sorry for noob question.

```
Config.json 
{
  "settings": {
    "lanonly": true,
    "_minify": true
  }
}
```

**Comment by Ylianst** [comment]
Hi. I just tested the MeshCentral Windows Installer and it worked for me. Can you open the following file:

`C:\Program Files\Open Source\MeshCentral\meshcentral-data\serverstate.txt`

It should look something like this:

```
time=1594494846024
state=running
server-pid=1316
redirect-port=80
https-port=443
```

The `https-port` will indicate on what port MeshCentral is on. If it's not 443, you will need to browse to https://127.0.0.1:xxx/ where xxx is the MeshCentral HTTPS port. When you start, you don't have a trusted certificate so you will get a warning in the browser, just skip that.

Let me know if that works,
Ylian

**Comment by NeeDforKIll** [comment]
First time when i installed. I get on localhost page asking about trusted cerfiticate, i skipped that and got Http error 403. 
https://imgur.com/a/HvcSCeg

**Comment by NeeDforKIll** [comment]
I am very sorry. Never thought vmware used 80 port. Thank you for helping
