### ISSUE TITLE
System keys are not working in remote desktop (CIRA-KVM)

### ISSUE THREAD

**Issue by judicapo** [Ylianst/MeshCentral#16]
### What are you doing?
sending `[Windows key]` or combination of keys like `[Windows + R]` CIRA-KVM remote desktop 

### What is happening?
Keys are not being sent or the complementary key `r` keeps pressed in remote machine.

![image](https://user-images.githubusercontent.com/3493355/44466879-a9efd980-a621-11e8-8beb-3a1810d966ee.png)

### What do you expect to happen?
Capture correctly the mentioned keys and send it to remote machine.
It would be nice to understand how this signals are sent, those have to be mapped In amt script?.

**Comment by Ylianst** [comment]
Ok, I need to investigate this. Note that you should switch the local or remote keyboard mapping to "EN-US" because if you use any other keyboard, the key conversion will be applied twice.

**Comment by judicapo** [comment]
Hello there, this is the result of your suggestion:

![image](https://user-images.githubusercontent.com/3493355/44991407-38eee100-af94-11e8-983e-3ea391b3a9d0.png)


As you can see, we have set both keyboards in ENG-US and the behavior is the same.

I really appreciate your collaboration with this issue 😄

**Comment by jsastriawan** [comment]
I think we need to bring special keys from MeshCommander to MeshCentral desktop. Win+R I believe should be sent in VNC emcoded key events.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.2-m on NPM. It has special keys drop down on the bottom left and I added WIN+R in this version. I can't trap the Windows key within a browser so this is the next best thing. I also tested WIN+R using the MeshAgent KVM and Intel AMT KVM, both work.
