### ISSUE TITLE
Question: Action - Wake-Up (WOL functions)

### ISSUE THREAD

**Issue by orion88-admin** [Ylianst/MeshCentral#1605]
Hi,

Hello, does anyone have a function from the actions menu? I am thinking of Wake-Up. I have added a computer to meshcentral with the agent installed and the wake-on-lan option in the BIOS enabled.

And when I want to wake the computer using this function, nothing happens, the computer does not get up.
I have MeshCentral version 0.5.86 and WAN Production Mode set, the server works for many local networks.
I will add that using other wake-on-lan software the same computer starts up.

What could cause this option not to work?

**Comment by vitko-bg** [comment]
Do you have other devices with MeshAgent installed on the same network? As I know WOL on MC using other "live" agents to wake device up...

**Comment by Ylianst** [comment]
Right, the MeshCentral Wake-on-LAN feature will cause agents that are awake to send the WOL Packet on all networks they are connected to. So, if you have an office with 10 computers, and have 9 of them sleeping, you can wake them up. If all 10 are sleeping, you can't wake any of them up. Hope that helps.

**Comment by Ylianst** [comment]
Also note that if the MeshCentral server is in LAN/Hybrid mode, it will also send WOL packets on it's own local network.

**Comment by orion88-admin** [comment]
My MeshCentral server is in WAN mode.
Yes, I have other computers on the same network.
I thought this option works like a regular wake-on-lan that is, sends MagicaPacket to the network card to a specific MAC address on ports 7 or 9

Okay, now I understand how it works for MeshCentral.
It is a pity that you cannot turn on remotely turned off computers connected to the meshcentral network via WOL.
Thanks for the explanation.

**Comment by Ylianst** [comment]
If you have Intel AMT setup, I will be adding in the future remote wake/sleep/off. That will work anywhere, without the need for other computers. This is because Intel AMT can communicate to the MeshCentral server even when the computer is sleeping/soft-off.

**Comment by orion88-admin** [comment]
I do not currently have the intel AMT configuration, but thank you for the information and the answers provided.

**Comment by krayon007** [comment]
The other issue with WOL is that while a device is sleeping, the ARP cache of the upstream router can get flushed, making directed packets to the sleeping device non-routable. This is why wol is not reliable outside the local network.
