### ISSUE TITLE
Question - how do I get the MeshID

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#1606]
Hi 

How do I obtain the meshid which is generated for a device group. I am trying to automate a process where I hope I can replace the .msh file on the client containing the correct meshID to ensure the machine appears in the group as per the meshID. I'm trying to avoid using multiple installers for different groups.

However I have noticed that when I run the command to obtain the group IDs, this ID is different to what is shown if I generate an installer for that group and install.

From server running the following commands give me this back for my ID: node meshcentral --showmeshes or node meshctrl.js listDeviceGroups

   _id: 'mesh//y5q@U93nSWYQ$HR53uBetxJBlSSkpxVia3MgwMqdefzwyj6YrCKI7FYm6Ivl$Yjn',

But on the client if I generate an installer and install the exe, the .msh file contains the MeshID as follows:
0xCB9ABE53DDE7496610FC7479DEE05EB712419524A4A715626B7320C0CA9D79FCF0CA3E98AC2288EC5626E88BE5FD88E7

Many Thanks

**Comment by Ylianst** [comment]
The best method is to use MeshCtrl.js like this:

```
node node_modules/meshcentral/meshctrl listdevicegroups
```

You will need to add login user/pass, etc. Another way to do this on the server is:

```
node node_modules/meshcentral --showmeshes
```

There is one issue, due to some history, the MeshID in the .msh is encoded in HEX, not Base64. So it will start with "0x". You can use [this web page to convert Base64 to HEX](https://base64.guru/converter/decode/hex).

Hope that helps,
Ylian

**Comment by vish84** [comment]
Thanks for the info, not quite sure how I will yet convert the base64 to hex in Powershell, to help in my automation. However I noticed when I try the converter link, using my values above, I get an error when converting from base64 to Hex. If I convert the hex value to base64, I notice that the @ character is replaced with + and that the $ is has been replaced with /

Am I missing something

**Comment by Ylianst** [comment]
Your right, there is also + and /. I swap these so the meshid can be used in a URL. As a better solution, I just added the --hex option in "meshctrl listdevicegroups". So you can get the meshid's in the right format. It looks like this:

![image](https://user-images.githubusercontent.com/1319013/87605588-e7463000-c6ad-11ea-933d-e6754ffdada6.png)

This will be in MeshCentral v0.5.88.

**Comment by vish84** [comment]
That's perfect, this will help me out significantly.

As always you do a fantastic job, and your hard work along with all the others that help maintain the code is much appreciated.

**Comment by vish84** [comment]
Hi

I noticed that when I use --hex with --json the json output does not contain the hex output, but shows the base64 output, is there any chance the hex value can be displayed when using --json.

Thanks

**Comment by Ylianst** [comment]
Working on that now :)

**Comment by Ylianst** [comment]
Ok, just check it in. In MeshCentral v0.5.94 when I next publish it, if you do both --hex and --json you will see the hex added to the json like this:

```
{
    "_id": "mesh//xYMpQG$jfLh6nPzpCbdHwoiT6aXWaki2O7DJY0LLuNold2Cz71sq@kFtxqS9Hxa8",
    "type": "mesh",
    "name": "MyHomeComputers",
    "mtype": "2",
    "desc": "",
    "domain": "",
    "links": {},
    "_idhex": "0xC58329406FE37CB87A9CFCE909B747C28893E9A5D66A48B63BB0C96342CBB8DA257760B3EF5B2AFA416DC6A4BD1F16BC"
  }
```

Hope that helps.

**Comment by vish84** [comment]
Thanks that will help me significantly.
Many thanks

**Comment by Ylianst** [comment]
MeshCentral v0.5.94 is published. Let me know if it works.

**Comment by vish84** [comment]
Thanks, that worked perfectly.
