### ISSUE TITLE
Wake on lan fails

### ISSUE THREAD

**Issue by TotallyNotElite** [Ylianst/MeshCentral#1607]
Wake on LAN recently stopped working for me, I don't know which version caused it exactly tho.

Meshcentral agent console output (same network): 
![image](https://user-images.githubusercontent.com/38938720/87583497-576baa80-c6dc-11ea-9e6e-8ed3b000aab3.png)

This implies that the mac address array is empty.

I'd be happy to provide any additional information required but I can't think of anything right now.

**Comment by Ylianst** [comment]
Thanks for the report, checking this now.

**Comment by Ylianst** [comment]
Yes, I see the same problem.

**Comment by Ylianst** [comment]
Checked in the fix, it will be in MeshCentral v0.5.88. I also improved that wake feature so that devices that you have rights to under user groups or individual device rights will also be included when sending wake packets.

**Comment by TotallyNotElite** [comment]
Will confirm and close once the version has been released.

**Comment by TotallyNotElite** [comment]
> I also improved that wake feature so that devices that you have rights to under user groups or individual device rights will also be included when sending wake packets.

What does this mean? Can devices you don't have permission to not send wake packets?

**Comment by TotallyNotElite** [comment]
Can't confirm and close. It has just stopped sending the wake packets entirely now.

**Comment by TotallyNotElite** [comment]
Any updates on this? Can I help reproduce this/fix this issue?

**Comment by Ylianst** [comment]
Apologies, it should be fixed in MeshCentral v0.5.92. I did find that it was sending something, but it was not building the magic packet correctly. Let me know if it works again, if not, I will have look into this some more.

**Comment by TotallyNotElite** [comment]
Nope, still nothing.  Sending a wakeonlan using `etherwake` works perfectly. Just FYI, I am not seeing a WOL message in the agent consoles either.

**Comment by Ylianst** [comment]
Arg! Ok, will look into it.

**Comment by TotallyNotElite** [comment]
Any way I can help or any info I can provide?

**Comment by Ylianst** [comment]
Yes. Can you do me a big favor and try to wake your machine using the manual "wakeonlan" command in the agent console.

![image](https://user-images.githubusercontent.com/1319013/88419977-f35f7b00-cd9a-11ea-9c63-b185f75427bc.png)

Depending on if it works of not, you will point me in the right direction.

**Comment by TotallyNotElite** [comment]
![image](https://user-images.githubusercontent.com/38938720/88480639-5d248400-cf57-11ea-8e57-ffe41473e51f.png)
But it's not waking up.

**Comment by TotallyNotElite** [comment]
Any updates on this or any info I can provide to help fix this?

**Comment by Ylianst** [comment]
Forgot to mention, Bryan fixed it, it should work in MeshCentral v0.6.2. Let me know if you can wake systems. Bryan found that the multicast interface needed to be set for packets to be sent.

**Comment by TotallyNotElite** [comment]
WOL via agent command: Device wakes up
WOL via GUI: No reaction

**Comment by TotallyNotElite** [comment]
Any updates on this so far?

**Comment by Ylianst** [comment]
So I finally put some cycles on this. 

**Test setup** 

- I have a [Intel NUC7i5DNKE](https://www.intel.com/content/www/us/en/products/boards-kits/nuc/kits/nuc7i5dnke.html) for testing with Windows 10.
- I have other computers on the same network that the MeshAgent installed. So the agents that are awake will send the wake-on-lan (WOL) packet on the local networks they are on.
- The BIOS is setup to wake from S3/S5.
- I setup Windows10 with my network adapter properties to allow the network adapter to wake the device and I selected to only wake when the magic packet is used.

**Testing**

- I start by selecting "Sleep" in Windows10, NUC powers down and starts blinking the power light. I go in MeshCentral, in the device, click "Action" button, select "Wake-up" and the device wakes up.
- I select "Shutdown" in Windows 10 and try again. This time, it does not wake up.
- I go in the BIOS, turn off the computer from the BIOS screen and WOL works again.

I tested the 3 cases above a few times, this is consistent behavior. The computer always wakes up except when I shutdown from Windows 10.

I start looking online and find this [Microsoft post](https://support.microsoft.com/en-us/help/2776718/wake-on-lan-wol-behavior-in-windows-8-windows-8-1-and-windows-10). Basically, when you select to shutdown on Windows 8 and higher, it placing the computer is "Fast Startup" (S4) mode and WOL is disabled.

As the Microsoft post indicates, if disable "Fast Startup" and shutdown from Win10, WOL does work again.

Can you try this can confirm? - Thanks.

**Comment by Ylianst** [comment]
Note that I also spotted this [Microsoft post](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/solved-windows-10-wake-on-lan-problem-after/89ea895f-592f-4a29-be05-ac5f3badcd3c) suggesting some changes to the motherboard settings. But I suspect the Windows 10 shutdown problem is the issue.

**Comment by Ylianst** [comment]
One more thing. I disabled wake-on-lan on that agents and tested that the MeshCentral server is sending wake-on-lan in LAN and Nybrid modes. It was not. It's not check in GitHub and will be published in MeshCentral v0.6.10.

So, if you are running MeshCentral on a local LAN, you should not need any connected agents to wake a computer.

**Comment by TotallyNotElite** [comment]
@Ylianst I think I may have identified the problem I was having, please read carefully. (NOTE: this is """fixed""" in version 0.6.10, but only if the server is in the same lan)

A wake on LAN request made via the GUI will **NOT** prompt any agents to send a wake on LAN request. (NOTE: in 0.6.10 the SERVER will send the request, not the AGENT)
A wake on LAN request made via the CLI will successfully wake up the requested device.

All the agents that are in the network and that I tested are Linux agents.

**Comment by Ylianst** [comment]
Oh. So, when you select to wake a device on the GUI, connected agents should be instructed to send WOL and in addition, if the server is in LAN or Hybrid mode, the server will also send WOL.

Looks like I have to check of Linux agents are sending WOL. In your case, the server fix "fixed" it, but it's still a problem if Linux agents are not sending WOL.

**Comment by TotallyNotElite** [comment]
Linux agents are able to send the WOL packet, but only if you instruct them to using the agent console, don't forget.

**Comment by TotallyNotElite** [comment]
I don't need this issue fixed anymore, but maybe it's still worth a look?

**Comment by in-voker** [comment]
can you give me an update about this issue?

I am currently expecting a simliar problem with this. 
the mesh server is on 0.7.47 and in hybrid mode.

I am trying to wakuep one computer over WAN but this is not working... 
there is one other computer online in the same subnet (different then mesh central server) and if i send the wakeup command from the online device in console mode "> wakeonlan XXXXXXXXXX
Sent wake-on-lan on 1 interface(s)."
the server goes up fine and quickly.

But if i try to wake up via GUI, nothing happens.

**Comment by TotallyNotElite** [comment]
Indeed, that's the same behavior I experienced: https://github.com/Ylianst/MeshCentral/issues/1607#issuecomment-674573532

**Comment by jdvmanen** [comment]
@Ylianst really looking forward to the bug fix for this one... WOL eliminates the need for phone calls, or (worse) getting onsite.

**Comment by TotallyNotElite** [comment]
I used to know the offending commit for this issue, but I have since forgotten it (for obvious reasons). Unfortunate.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.19 with improved Wake-on-LAN support. It should work much better now. Feedback appreciated.

**Comment by jdvmanen** [comment]
Seems to work better now!


Met vriendelijke groet,

Dirk

>
>

**Comment by thinkbig1979** [comment]
I'm having issues with WOL as well.
My server is in WAN mode and I have 2 clients on a local LAN. When I select the Wake-Up functinon on the offline node, and go to the console of the live node, I see the following:
```bash
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'trim' of [object Function]) in method 'handleServerCommand()'
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
```
