### ISSUE TITLE
PCs mounted with AMD processors do not go up in MeshCentral

### ISSUE THREAD

**Issue by stimut79** [Ylianst/MeshCentral#1608]
Hello,
First of all, thank you for your tool which is very efficient and scalable.
We have a little problem.
We changed our computer park by assembled pcs and laptops. They are installed with Windows 10 (Same version for the computer park).
Only laptops go up in MeshCentral.
So, it's not a network problem.
I wonder if it is not related to the fact that the stations are assembled, and they have AMD Ryzen processors?
Thank you in advance for your reply.

**Comment by krayon007** [comment]
There is no dependency on the CPU. Can you run the agent in console mode, and see what it says?

**Comment by PathfinderNetworks** [comment]
Almost all of the devices I support are AMD based.  Probably a couple hundred or so are AMD Ryzen based as well.  It's definitely not an issue with the processor. 
Do you have the laptops on a wireless network while the desktops are wired?  It sounds more like you have something going on with the wired network not allowing the Mesh agent to communicate correctly.

**Comment by Ylianst** [comment]
Just to add the the confirmation, there is no limitation on the type of processor that can be used, MeshCentral server and agents should work on AMD Ryzen processors. If you have any additional data on the issue you are encountering, please let us know.
