### ISSUE TITLE
Mesh router, Relay Map question

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1609]
Guys,

I'm playing with Mesh Router today.  Very cool tech.  One of the things I'm trying to understand is how the Relay mapping works.  Is there any better documentation or examples on this?

For example, I was successfully able to get a remote VM server (xenserver host) to connect to my local Xencenter application by remapping port 443.  But I can't get console traffic which is only locally accessible.  So while I can control the machines remotely, I cannot see what's on the console.  So the following post documents the issue:

"Hi Bill,

XenServer uses port 443 for most communication between XenCenter and the XenServer host itself. For Linux guests, it also uses port 5900 to connect to the graphical console.

We normally recommend that you set up a VPN connection so that the host XenCenter is running from can route packets directly to the XenServer host (in other words, the XenCenter host should be on the same subnet as the XenServer host itself).

If you configure your XenServer host behind a gateway performing NAT, you'll find that the XenCenter works for most operations, but cannot connect to the consoles of the VMs. The reason for this is that the XenCenter reports the local IP of the XenServer host and the remote host attempts to connect to the local IP, not being aware that there is NAT in the way.

Hope this helps!

Kind Rgards,
Jonathan"

1.  So it seems I need to find the local IP of the server to get console traffic.  Is this where relay mapping helps?
2.  Another question.  If a remote application uses more than on port.  Say 80 and 8080.  Could twoor more ports be mapped so that a remote application could fully function?

Thanks
Shane

**Comment by D4V3M0NK** [comment]
Bill,
You should can map multiple ports from your remote host, to your local system - one of the most powerful elements of MC, IMHO. 

For the majority of the remote systems I manage, I map 22, 80, 443 and/or 3306 to local ports so that I can connect to those systems using the individual ports on my local system. Additionally (totally up to you of course) I assign a range based upon the customer: 

- Customer 1 is in the 70xx range
    - SSH (remote) is mapped to 70**22** (local)
    - HTTP (remote) mapped to 70**80** (local)
    - HTTPS (remote) mapped to 70**43** ...ok, so I'm missing a '4' here, but I think you get the drift

When I connect via SSH to the remote system, everything appears as if I've logged onto the terminal.

HTH

**Comment by Ylianst** [comment]
I have used XenClient and XenServer in the past. You should be able to port map your local port 443 to remote port 443 on the XenServer and then connect the XenClient to 127.0.0.1:443. Same for port 5900. For VM's, if I recall correctly there is a set of ports that XenServer will use for VN's and I think they are consecutive, like 5901, 5902... In that case, you will need to port map a local port to the required remote port and connect you VNC client to 120.0.0.1:xxx local port.

You can certainly map as many ports as you need, it should not be a problem. Hope that helps.
