### ISSUE TITLE
Keyboard input failing (depending on role)

### ISSUE THREAD

**Issue by visualwritings** [Ylianst/MeshCentral#161]
Hi,

We've just installed the latest version of meshcentral (0.3.1-R) and are experiencing some issues with keyboard input, possibly related to or same issueas #137 . In the administrator-role the _/- key, +/= key and backspace aren't working (US qwerty). As a partial administrator all characters other than a-z / 0-9 fails. This is regardless of where you're trying to input text (login, cmd, notepad, whatever).

When I say 'failing' I mean it just doesn't accept the input, it does nothing. We can use on screen keyboard on the managed machine as a workaround but this is obviously not ideal.

Any thoughts would be appreciated.

~Martijn

**Comment by Ylianst** [comment]
Hi. About a month ago I added a "Kiosk mode" where only keys a-z and 0-9 could be sent by a user that had very limited rights. However, I did cause a problem and this mode seems to be in use even when it's not selected. I will look at a fix when I am back from vacation.

**Comment by visualwritings** [comment]
Thanks. Is there a setting somewhere which we can check to see if it's on or not?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.1-u with hopefully a fix for this. If you can try it and let me know if it works, that would be great.

**Comment by Ylianst** [comment]
Will close this one as I am pretty sure it's fixed. However, please re-open if needed.
