### ISSUE TITLE
Question about "Real-time Session Indicator"

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#1612]
Hi,
I have a question about the Real-time Session Indicator.
When I connect through the web, I see the blue indicator. But when the connection is through the MC Router with port relay (RDP), the indicator is not shown. Is that normal?
Thanks.

**Comment by Ylianst** [comment]
Oh, the session indicator only shows desktop/terminal/files sessions, but not TCP routing sessions. Now that you mention it, maybe it should also be enabled for TCP routing?

**Comment by lergolas** [comment]
I think it would be a good idea.

**Comment by Ylianst** [comment]
Ok, added TCP/UDP routing indicator, this will be in MeshCentral v0.5.95.

![image](https://user-images.githubusercontent.com/1319013/88435385-f10b1a00-cdb6-11ea-8192-605ebadcba11.png)

Let me know if that works.
