### ISSUE TITLE
Interfaces link issues

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1615]
When I click the interfaces link I get the following 

![image](https://user-images.githubusercontent.com/55733884/87781154-6fecd980-c830-11ea-88fd-0843d56e86d1.png)

Networking is also not visible on the details tab, yet 'netinfo' in console tab will return the correct info.
For some reason only the machines in a specific group have this issue

**Comment by Ylianst** [comment]
That is not good, can you run "netinfo" in the console tab, replace any private info with XXX (if letter) or 888 (if number) and send it over? I will take a look at this.

**Comment by Allowee** [comment]
This is on some computers.
All are running the 64bit agent

Computers with the isatap interface seem to have this issue


working:

> netinfo
{
  Ethernet: {
    0: {
      address: "fe80::f062:1002:57e4:68fb%8"
      fqdn: ""
      family: "IPv6"
      mac: "9C:7B:EF:BB:8F:FD"
      index: 8
      status: "up"
      type: "ethernet"
    }
    1: {
      address: "192.168.0.82"
      gateway: "192.168.0.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.255.255.0"
      mac: "9C:7B:EF:BB:8F:FD"
      index: 8
      status: "up"
      type: "ethernet"
    }
  }
  Loopback Pseudo-Interface 1: {
    0: {
      address: "::1"
      fqdn: ""
      family: "IPv6"
      mac: "00:00:00:00:00:00"
      index: 1
      status: "up"
      type: "loopback"
    }
    1: {
      address: "127.0.0.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.0.0.0"
      mac: "00:00:00:00:00:00"
      index: 1
      status: "up"
      type: "loopback"
    }
  }
}

-------------------------------------------
This is a computer that gives the error

> netinfo
{
  Embedded LOM 1 Port 1: {
    0: {
      address: "fe80::fc7e:39cb:68fc:379a%13"
      fqdn: ""
      family: "IPv6"
      mac: "98:F2:B3:8F:43:4C"
      index: 13
      status: "up"
      type: "ethernet"
    }
    1: {
      address: "192.168.215.33"
      fqdn: ""
      family: "IPv4"
      netmask: "255.255.255.224"
      mac: "98:F2:B3:8F:43:4C"
      index: 13
      status: "up"
      type: "ethernet"
    }
  }
  Embedded LOM 1 Port 2: {
    0: {
      address: "fe80::61c3:fd7f:3eff:26c7%12"
      fqdn: ""
      family: "IPv6"
      mac: "98:F2:B3:8F:43:4D"
      index: 12
      status: "up"
      type: "ethernet"
    }
    1: {
      address: "192.168.4.11"
      gateway: "192.168.4.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.255.255.0"
      mac: "98:F2:B3:8F:43:4D"
      index: 12
      status: "up"
      type: "ethernet"
    }
  }
  Loopback Pseudo-Interface 1: {
    0: {
      address: "::1"
      fqdn: ""
      family: "IPv6"
      mac: "00:00:00:00:00:00"
      index: 1
      status: "up"
      type: "loopback"
    }
    1: {
      address: "127.0.0.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.0.0.0"
      mac: "00:00:00:00:00:00"
      index: 1
      status: "up"
      type: "loopback"
    }
  }
  isatap.{EBC16BDB-3FD8-4F83-83D9-EC628E4ACD41}: {
    0: {
      address: "fe80::5efe:192.168.4.11%14"
      fqdn: ""
      family: "IPv6"
      mac: "00:00:00:00:00:00:00:E0"
      index: 14
      status: "down"
      type: "tunnel"
    }
  }
  isatap.{AE45FEFD-6636-4F8F-A1B9-84297E4B3853}: {
    0: {
      address: "fe80::5efe:192.168.215.33%15"
      fqdn: ""
      family: "IPv6"
      mac: "00:00:00:00:00:00:00:E0"
      index: 15
      status: "down"
      type: "tunnel"
    }
  }
}
