### ISSUE TITLE
UAC popup not capturing in mesh agent

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1616]
I have taken the remote access. when i open the cmd.exe with UAC, That time mesh remote control showing blank screen

**Comment by krayon007** [comment]
Are you running the agent as a service, console mode, or temp mode?

**Comment by aimdharma1990** [comment]
Running as Temp mode.

**Comment by krayon007** [comment]
What server version are you running? When you click on connect to connect in temp mode, you should get a UAC prompt to elevate the agent running in temp mode. If you don't accept this elevation, it will run without elevation. If the agent does not have elevation, then desktop remoting will not be able to capture UAC prompts.
