### ISSUE TITLE
ldap connection fail and no logs

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1617]
Hi !

We are trying to use ldap auth for our newly installed MeshCentral server :)
But it's not working and I see nothing in my ActiveDirectory events on user connection attempts.

How can I turn on log on my meshcentral server (Debian 10) ?

And other questions on ldap auth, do I need to install ldapauth-fork module manualy ? (I did it but is it necessary ?)

D.

**Comment by Ylianst** [comment]
When you configure MeshCentral to use LDAP, it will automatically install the ldapauth-fork module the next time you run MeshCentral. So, that should be a good hint that the config.json is at least a bit correct. Can you send an anonymized version of your config.json so I can see how you configured it? Many sure to XXXX any private information.

As a side note, I am really no LDAP expert. I actually never tested MeshCentral with LDAP myself, so you guys are going to be a lot better at figuring out what is going on once LDAP is minimally configured.

**Comment by Tomatoschewps** [comment]
Ok for ldapauth-fork module.

We connect all our tools to LDAP so it's not all new for me but without logs I don't know where to start looking.

How can I keep my meshcentral admin login when I activate ldap ? That way I will be able to see logs inside de webui.

---
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "XX.XXXXXXXX.XX",
    "mongodb": "mongodb://XXXXXXXX:XXXXXXXXX@127.0.0.1:27017/XXXXXXXXXX",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "auth": "ldap",
    "ldapUserName": "samaccountName",
    "ldapUserBinaryKey": "objectSid",
    "ldapOptions": {
      "url": "ldap://X.X.X.X:389",
      "bindDN": "CN=meshcentral,OU=XXXXXXX,DC=XXXXXXXX,DC=XXXXXXX",
      "bindCredentials": "XXXXXXXXXX",
      "searchBase": "OU=XXXXXXXXX,DC=XXXXXXXX,DC=XXXXXXXXXX",  <== My users are in an OU
      "searchFilter": "(sAMAccountName={{username}})"
    }
  },
  "domains": {
    "": {
      "title": "XXXXXX",
      "title2": "RemoteManagement",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "XXX@XXXX.XX",
    "names": "XX.XXXXXXXX.XX",
    "rsaKeySize": 3072,
    "production": true
  }
}

**Comment by vish84** [comment]
i've been struggling with the same issues in trying to configure LDAP Authentication. @Tomatoschewps not sure if this help but I found that for me moving the ldap config into the domains section, got me a little further, but when it tried to login I got a "this site cannot be reached". This is all I have in my config on my test box. The only way I found to use the local login, I have to disable the domains section and restart. Would be nice to be able to use a local account and ldap once this works. However unsure where to debug this further in meshcentral. 

`{
  "settings": {
    "cert": "xx.xx.xx.xx",
    "_minify": true
  },
"domains": {
	  "": {
			"title": "MyServer",
      		        "title2": "Servername",
			"auth": "ldap",
			"ldapUserName": "sAMAccountName",
			"ldapUserBinaryKey": "objectSid",
				"ldapOptions": {
				"url": "ldap://xxx:389",
				"bindDN": "CN=xx,OU=xx,DC=xx,DC=xx,DC=xx",
				"bindCredentials": "xx",
				"searchBase": "DC=xx,DC=xx,DC=xx",
				"searchFilter": "(sAMAccountName={{username}})"
			}
		  }
         }
}`

**Comment by vish84** [comment]
I did get mine working, I needed to use LDAPs, mistake on my part. But if you want to view logs inside the meshcentral-data folder (on windows, I assume its the same folder on linux), there is a file which is called mesherrors.txt I found this quite helpful when I had an error in mt syntax.

**Comment by Tomatoschewps** [comment]
Hi @vish84 , I tried LDAPs but we didn't use it for our other services so no luck.
My server is on Debian, I have the meshcentral-data folder but I didn't have mesherrors.txt log file...

We agree that with "ldapUserName": "sAMAccountName" your login in meshcentral is with your windows user name without DOMAIN\ or @domain.local ?

**Comment by vish84** [comment]
My meshcentral server is running on a windows machine (non-domain joined). 
Correct I do not need to include @domain.local or domain/ just the username.

Did you try move the ldap config section under the domains tag, as I noticed you have it under settings, when I was testing I noticed it did not work for me when it was under settings. 

Not sure if you can setup a test windows box to test this.

**Comment by Tomatoschewps** [comment]
Ok, I've not found logs but saying myself "It hase to be a simple problem" and verified again my confing.json I've corrected the :
"ldapUserName": "samaccountName",
by :
"ldapUserName": "sAMAccountName",
 And it works ...

@vish84, what do you see in the upper right corner for welcome "XX" ? I have a string that doesn't correspond to anything (not objectUID, objectSid or nothing in my Active directory).
And with my ldap user I don't see the groups and agents added with my local admin

**Comment by Tomatoschewps** [comment]
Well ...
With a logout, login, I see my ldap username now in the upper right :)

**Comment by Tomatoschewps** [comment]
And I have understand the right management, created my groups and affected them.
@Ylianst The only point left is the hability to login with local users even if ldap is activated. ;)
