### ISSUE TITLE
High CPU usage on MeshAgent when on WiFi

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#1619]
Hi,
I was wondering if someone else has had this issue before, 
Currently when the windows 10 connects to a network wired works fine using 2% of CPU but if i change to WIFI or have them both connecting wifi and wired i get something odd on the CPU usage 
See picture
Thank you 
![Screenshot_2020-07-17_14-40-47](https://user-images.githubusercontent.com/13953629/87825532-ef80a580-c83c-11ea-8013-44870492e554.png)

**Comment by krayon007** [comment]
> Hi,
> I was wondering if someone else has had this issue before,
> Currently when the windows 10 connects to a network wired works fine using 2% of CPU but if i change to WIFI or have them both connecting wifi and wired i get something odd on the CPU usage
> See picture
> Thank you
> ![Screenshot_2020-07-17_14-40-47](https://user-images.githubusercontent.com/13953629/87825532-ef80a580-c83c-11ea-8013-44870492e554.png)

What are you doing at the time of this snapshot? (ie, are you using Remote Desktop, Terminal, etc).
I see there are two instances running, which implies the agent is doing something like Desktop or Terminal...

**Comment by killmasta93** [comment]
Thanks for the reply, only was using the remote desktop feature, the only thing that what changed from wired to wifi and the spike on the CPU

**Comment by Ylianst** [comment]
I have noticed that when the disk is full the agent does go to 100% CPU, Bryan is working on that issue. Hopefully it will also fix this.

**Comment by krayon007** [comment]
> Thanks for the reply, only was using the remote desktop feature, the only thing that what changed from wired to wifi and the spike on the CPU

Is this only while doing remote desktop? CPU usage during remote desktop is normal, because we are relying on GDI to fetch the desktop. Depending on what your refresh setting is, it is normal for it to use between 10% and 30% cpu. I used a performance analyzer and found that is inside GDI.

Are you seeing the CPU usage on wifi outside of remote desktop?

**Comment by killmasta93** [comment]
Thanks for the reply, this happens when im on the remote desktop but only if i do the change  from cable to WIFI

**Comment by Ylianst** [comment]
I think I am seeing the same thing, but only on some of my machines. I will be investigating this more tonight.

**Comment by killmasta93** [comment]
thanks for the reply, let me know if i can help

**Comment by Ylianst** [comment]
FYI. I have noticed that there is always high CPU usage when the Privacy Tool bar is shown on the remote desktop during a remote desktop session. Bryan is looking into it and will issue a fix for the ASAP. If is possible by chance that this is also what you are seeing?

**Comment by Ylianst** [comment]
Can you update to latest MeshCentral v0.5.95 and try again. This new agent no longer uses high CPU in my situations, but I want to know if it fixes the issue presented here. Thanks.

**Comment by killmasta93** [comment]
Thanks for the reply, when you say privacy tool bar not sure what you mean?
Going to update it and let you know thank you again ill post back

**Comment by killmasta93** [comment]
wanted to post back so far no issues with high CPU usage ill close the issue for now ill post back if i see that again thank you so much again for all the help
