### ISSUE TITLE
Restrictive Terminal / SSH

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#162]
Is there a way of enhancing the terminal connection (equivalent of SSH) when connecting to a Unix system? Currently, when connected to a Ubuntu (for example) system via Terminal, I have basic navigation but I'm unable to use "vi" to edit files, "cat" to view files through the terminal.  It appears to only permit one screen's worth of the file and then automatically comes out of whatever program I'm in and back to the command prompt.

Perhaps I'm missing something either that should be set up on the server, or perhaps on the client?

**Comment by Ylianst** [comment]
Hi. So, terminal is not that great right now. Lots of fixes to make on it. I am on vacation now, I will look at it when I get back. There is a huge list of things I need to do. One alternative is to use the MeshCentral Router with PuTTY to get a really nice terminal.

**Comment by D4V3M0NK** [comment]
Ok, so I'm trying to get to grips with using router with little luck. I'm attempting to get an "SSH" link underneath a system listed in Mesh Central so that others can use their SSH client of choice to connect through to this systems' terminal, bypassing the existing terminal.

For this test, my personal Ubuntu client machine is hosting a number of VirtualBox VM's (all Ubuntu 16 servers).
1. From my (host) machine, I log into my Mesh Central server (meshadmin:mesh.example.org), select my mesh and my target device "ubuntuTest".
1. From the link at the bottom, I select "Router" and download the Linux x64 "meshcmd" and "MeshAction.txt"
1. I get these two files onto my vagrant-enabled Ubuntu 16 server VirtualBox VM
1. I rename MeshAction.txt to meshaction.txt, update "remotePort" to "22" and change the "username" to meshadmin
1. Once the file is saved, I log into my VM, run "./meshcmd" and I get prompted for a password. I enter the password of the meshadmin
1. The command shows me that it's redirecting local port 1234 to "ubuntuTest":22

It's at this point that I was hoping that a new link would appear beneath ubuntuTest within Mesh Central (named ?) that would allow me to SSH into the system.  I don't see anything. 

I get the feeling that perhaps this feature only works on Windows, as I've been through the videos and all are shown in Windows, but my gut tells me I'm missing something obvious here. The User Guide (0.2.2) doesn't contain anything, so I'm using all the information that I'm gathering online...

**Comment by nlyaple** [comment]
I would like to add my $.02.  It would be great to have:
 - Command history and navigate using the cursor keys. (Up and down to iterate through command history)
 - Tab key to finish the line (type 'cd /op', press tab key)  
 - Nano editor support
 - Backspace key (try a tab key and then backspace)
 - Support 'more' and screen buffer. (type 'ls | more')

**Comment by jsastriawan** [comment]
Ylian created MeshRouter (the UI version of MeshCmd). Not sure where @Ylianst upload the binary is but this should help you to create tunnel to SSH. I also played to tunnel Meshcentral Terminal to putty raw terminal too but that terminal is not fully VT100 compliant (https://github.com/jsastriawan/mc2router).

![image](https://user-images.githubusercontent.com/6583218/55591148-a4935b00-56e9-11e9-861c-f85b86ca535e.png)

Windows is working too.
![image](https://user-images.githubusercontent.com/6583218/55591202-c42a8380-56e9-11e9-9342-995993a11c7b.png)

**Comment by merlinweb** [comment]
> Ylian created MeshRouter (the UI version of MeshCmd). Not sure where @Ylianst upload the binary is but this should help you to create tunnel to SSH

In Ylian's blog you can find an article with download link:
[https://meshcentral2.blogspot.com/](url)

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.1-x with improved terminal. Should make cat and nano usable. Testing and feedback appreciated.

![MC2-Terminal-Nano](https://user-images.githubusercontent.com/1319013/55647113-ae709900-5791-11e9-88ed-094a9b3ddd87.png)

**Comment by D4V3M0NK** [comment]
Certainly an improvement!  I tend to use _vi_ as my editor but appreciate that many others use _nano_ 
 - will there be a _vi_ update too?

When creating a brand new file, everything looks really good. However, with an existing file (and RW permissions) I can't seem to add a new line (in order to write a comment, for example).  It appears that I just keep writing over the existing as opposed to inserting a new line and then typing on that line.

Other comments : and please understand these are just suggestions, I totally get that this all takes time and effort to put into place (I wish in some way I could assist), but the _Home_ and _End_ key functions don't appear to work and using _TAB_ to complete a line would be really useful, along with _UP/DOWN_ to review command history.

**Comment by D4V3M0NK** [comment]
> It appears that I just keep writing over the existing as opposed to inserting a new line and then typing on that line.

Just double checked this and it appears to be a screen refresh issue, the line does actually get inserted, but the screen doesn't show it.

(BTW : updated to -x with an updated NPM (now 6.9.0)

**Comment by Ylianst** [comment]
I am going to have to learn vi again. I just did some fixes and I can now scroll up and down thru large files in vi. That will be in the next release.

**Comment by theredkoala21** [comment]
What about a prebuilt terminal emulator?

https://github.com/xtermjs/xterm.js

or

https://github.com/chjj/term.js/

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.1-y with more terminal improvements... and yes, I should really be looking into xterm.js, looks really good.

**Comment by Ylianst** [comment]
More terminal improvements on MeshCentral v0.3.2-b. Arrow, home, end, page up, page down, delete, insert keys now work. Improved escape code handling.

**Comment by merlinweb** [comment]
After update I get "server disconnect" every few minutes...
Server remain not accessibile for a while then prompt for credential
Restarted service, then reboot, but issue is still present
no errors in MC2 logs

hope this helps

Cheers
Merlinweb

**Comment by Ylianst** [comment]
Update to MeshCentral v0.3.2-c and let me know if it fixes it.

**Comment by D4V3M0NK** [comment]
v0.3.2-d is looking very promising (from vi's point of view at least!)  The page down (CTRL + D) doesn't refresh the screen (appears to keep the top 13 lines or so)

![viPageDown](https://user-images.githubusercontent.com/7572742/55906356-f3793e80-5b88-11e9-8b12-98d8b253d768.png)

**Comment by D4V3M0NK** [comment]
One thing that I would also like to mention, which I'm not sure is a terminal issue or how meshcentral was installed on the client, but when attempting to exit vi I get the message "E138: Can't write viminfo file $HOME/.vminfo!" ... not sure this is a big deal or not, but thought I would mention it

**Comment by D4V3M0NK** [comment]
BTW : definitely worth mentioning ... the server update process for MeshCentral is unbelievably easy. Can't impress this upon you more Ylian! Super easy and quick.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.2-i with a fix for CTRL-D in vi. Let me know if it works.

**Comment by D4V3M0NK** [comment]
Hold my beer ...

On Wed, 2019-04-10 at 16:37 -0700, Ylian Saint-Hilaire wrote:

Just published MeshCentral v0.3.2-i with a fix for CTRL-D in vi. Let me know if it works.

**Comment by D4V3M0NK** [comment]
Ctrl+[U|D] works beautifully.

**Comment by Ylianst** [comment]
Ok, closing this issue since the terminal is much better. However, please open another issue if a specific application does not work as expected.

**Comment by GusevVictor** [comment]
> 
> 
> Just published MeshCentral v0.3.1-y with more terminal improvements... and yes, I should really be looking into xterm.js, looks really good.

PLEASE use a normal terminal. There is a lot bug. I think ssh + xterm.js will be good chouse. Don't spend you time just switch to xterm.js. It will be good for ssh (with private key storage) - just see apache guacamole + xterm.js

Best regards.
