### ISSUE TITLE
Provide a method to sign agents (using trusted code signing cert) agents on the fly

### ISSUE THREAD

**Issue by Jamesits** [Ylianst/MeshCentral#1622]
We'd like to deploy MeshCommander in a highly secured network where every executable must be signed by a trusted code signing cert. Is it possible to sign MeshCommander generated agent exes with some sort of automated cert signing service? (e.g. provide a plugin hook where we can submit the generated exe to our signing service and retrieve the signed one.)

**Comment by Ylianst** [comment]
A bit confused by your question. Are you wanting to sign MeshCommander? Or the MeshAgent from MeshCentral?

**Comment by Jamesits** [comment]
Sorry, got a little bit confused on the names. I wanted to sign MeshCentral agents on the fly while downloading them from the MeshCentral.

**Comment by Ylianst** [comment]
Got it. When you download a new version of MeshCentral using NPM, the Windows agents are signed using a self-signed certificate that I have. You will find the following files in "node_modules/meshcentral/agents":

```
MeshService.exe
MeshService64.exe
MeshService-signed.exe
MeshService64-signed.exe
```

All you need to do it use "signtool.exe" and sign 'MeshService.exe' and put the result in 'MeshService-signed.exe', and do the same for the 64bit version. This can be done using a batch file.

You do something like copy "MeshService.exe" to "MeshService-signed.exe" and do this:

```
"C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool" sign /sha1 fc7dbce2b19c0a62bba32ca246fa22260bb86333 /fd sha384 /du "https://meshcommander.com" /d "MeshCentral Remote Management Agent." /t "http://timestamp.comodoca.com/authenticode" "MeshService-signed.exe"
```

Once you start MeshCentral, it will use the signed version of the executable first when present. Let me know if that helps.

**Comment by Jamesits** [comment]
OK this works for me. Thank you!

**Comment by robclay** [comment]
After we upload our signed copies of MeshService-signed.exe and MeshService64-signed.exe rewriting the existing files in node_modules/meshcentral/agents, do we need to restart the server?

**Comment by GabrieleV** [comment]
Why don't you ship the execucìtable already signed ?
