### ISSUE TITLE
Agent keepalive causing port forwarding to go wrong

### ISSUE THREAD

**Issue by Jamesits** [Ylianst/MeshCentral#1623]
Environment:

* MeshCentral 0.5.88
* Nginx reverse proxy w/ TLS offloading
* MeshCentral Router bundled with the server

Settings:

```
"agentPing": 30,
```

Reproduction:

1. Install MeshCentral, set `agentPing` to 30 or other short value
2. register a Linux agent (x86_64)
3. Start MeshCentral Router using `mcrouter://` URL
4. Launch PuTTY within MeshCentral Router, log in normally
5. Wait 30 seconds (or whatever you set for `agentPing`)

Expected:
SSH session should still be connected.

Actual:
PuTTY alerts "Incoming packet was garbled on decryption" and disconnects.

Server side log shows that it always disconnects at exactly the `agentPing` time:
![image](https://user-images.githubusercontent.com/1297257/87853398-3a351700-c93c-11ea-9d81-01984fc90437.png)

Notes:
* ClickOnce port forwarder also have this problem.

**Comment by Ylianst** [comment]
Thanks for reporting. This is clearly a bug. MeshCentral Router should be ignoring the ping data instead of forwarding it. I will look into this.

**Comment by Ylianst** [comment]
A quick note on this, if you do:

"agentPing": 30,

Then the server will send a PING to the agent that will respond with a PONG every 30 seconds. However, if you do this:

"agentPong": 30,

The server will send a PONG to the agent every 30 seconds and the agent will not reply. If you can make NGINX work with just agentPong, you should as it will reduce the amount of traffic.

Regardless, you report is still valid.

**Comment by Ylianst** [comment]
FYI. I can confirm that I see the same problem.

**Comment by wh1te909** [comment]
oh wow this explains why my meshrouter RDP connections keep getting disconnected every 5 minutes, I have agent pong set to 300. Thought my connection was garbage lol.

**Comment by Ylianst** [comment]
Working on it now, I will update shortly.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.89 with a fix for this. You will need to update MeshCentral in addition to updating MeshCentral Router / MeshCMD to fix this issue. Please let me know if it works.

**Comment by Jamesits** [comment]
Cannot reproduce in 0.5.89, I guess it is fixed. Thank @Ylianst for the quick fix!

@wh1te909 Initially thought my connection was garbage too, but after multiple occurrences my intuition said "grab a stopwatch and count the seconds".

**Comment by Ylianst** [comment]
I am SOO glad you grabbed a stopwatch! This was an outstanding bug report.

**Comment by Jamesits** [comment]
BTW, MeshCentral <=0.5.90 will also disconnect a file upload session at agent ping. Current stable version (0.5.81) is affected so I think I'll mention this in case anyone else have the same issue. 

Unable to reproduce at 0.6.11.
