### ISSUE TITLE
Feature Request: Embedded desktop only permissions

### ISSUE THREAD

**Issue by matthewquinn** [Ylianst/MeshCentral#1626]
Hi, we are looking to use MeshCentral to give our non-admin users access to their devices using the minimal embedded desktop on a specific node. We have been doing this in V1 using the MeshSimpleAPI & meshdesktop.js script.

The viewmode and hide params get us close to what we want but it is very easy for a user that knows what they are doing to copy the iframe's url and gain access to meshcentral's UI.

What would be ideal in our situation is more fine grained permissions which are enforced by MeshCentral and not the GUI:
- Embedded desktop only
- Login with token only
- Cannot shutdown/reset/sleep devices (and maybe further permissions to disallow other GUI controls on the desktop view)

And maybe a viewmode or separate html file which doesn't try bring in as much of MeshCentral's capabilities.

We have ideas on how we might implement something ourselves without changing MeshCentral but are aware functionality would still be available over the websocket connection which for us is a potential security issue.

**Comment by dinger1986** [comment]
this can be done with sharing links now, so just share the desktop url for each user @si458 can close

**Comment by si458** [comment]
correct! you can also use the new embedding mode with different options and methods
https://ylianst.github.io/MeshCentral/meshcentral/#embedding-meshcentral
