### ISSUE TITLE
Accept reject option during the Remote access

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1629]
When ever we are taking the remote machine access the user might be working some confidential things. That time should we have any policy which will prompt the popup as "Accept" or "reject" the request like that?

This option is available in the Ultra VNC remote control Tool.

**Comment by vitko-bg** [comment]
It is available on MC.
Check the documentation

**Comment by aimdharma1990** [comment]
Hi.

Thanks for the communication, I have tried to find the documentation and i
couldn't find it. Can you please share the section which you are referring
to?

**Comment by vitko-bg** [comment]
Use this option in your config.json file
 "__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
"UserConsentFlags" : 7,

OR

In user properties: 
![image](https://user-images.githubusercontent.com/59362521/88067702-3afdc100-cb67-11ea-8252-28dae185f594.png)

**Comment by aimdharma1990** [comment]
Thanks, It's working now.. In the target i am getting the popup

[image: image.png]


Will it be possible to change the time out for this? Can this message be
modified ?

**Comment by Ylianst** [comment]
Currently the timeout is set to 30 seconds. If you open a different issue requesting this, I can make it configurable.

**Comment by vitko-bg** [comment]
" vitko-bg removed their assignment 11 seconds ago" - by mistake :)

**Comment by vitko-bg** [comment]
Check that ( got it from different issue #1630 - may help you ):
      "consentMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) requesting remote desktop access. Grant access?",
        "Terminal": "{0} ({1}) requesting remote terminal access. Grant access?",
        "Files": "{0} ({1}) requesting remote files access. Grant access?"
      },
      "notificationMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) started a remote desktop session.",
        "Terminal": "{0} ({1}) started a remote terminal session.",
        "Files": "{0} ({1}) started a remote files session."
      }

**Comment by Ylianst** [comment]
@vitko-bg I just assigned you as a show of thank you for responding. No obligation on your part, but thanks for helping. Very much appreciated.

**Comment by vitko-bg** [comment]
@Ylianst no problems. Trying to help others as I was same in the beginning :)
You are alway welcome - thanks for all that you are doing for us!!!
@aimdharma1990 Did you managed to find and test those options? Is that resolving your issue?
