### ISSUE TITLE
Guide on edit style and custom consent messages

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1630]
There is some information available for using own branding in the self-hosted version. However, it is not clear to me how to do this.

More important for me is the custom consent message; for remote access it is more trustworthy if the consent request is in the native language :-)

**Comment by Ylianst** [comment]
Your right that documentation is lagging all the settings of the config.json. Take a look at the file "node_modules/meshcentral/meshcentral-config-schema.json". You will see a description of all of the possible config.json settings.

In your case, in the domain section of your config.json, add this:

```
      "consentMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) requesting remote desktop access. Grant access?",
        "Terminal": "{0} ({1}) requesting remote terminal access. Grant access?",
        "Files": "{0} ({1}) requesting remote files access. Grant access?"
      },
      "notificationMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) started a remote desktop session.",
        "Terminal": "{0} ({1}) started a remote terminal session.",
        "Files": "{0} ({1}) started a remote files session."
      }
```

You can then customize the notification and consent messages. Hope that helps.

**Comment by jdvmanen** [comment]
Hi Ylianst,

I've this config.json content (complete) but it doesnt work yet...?



`{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "server.abcdef.info",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "CertUrl": "https://server.abcdef.info",
    "AllowHighQualityDesktop" :  true,
    "SelfUpdate": true
  },
  "domains": {
    "": {
      "title": "ABCDEF",
      "title2": "Remote Support",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "email": "jdvmanen@my-email.com",
    "names": "server.abcdef.info",
    "rsaKeySize": 3072,
    "production": true
  },

"consentMessages": {
        "Title": "ABCDEF - Hulp op afstand",
        "Desktop": "{0} ({1}) vraagt toestemming om uw computer te bedienen. Wilt u dit toestaan?",
        "Terminal": "{0} ({1}) vraagt terminal-toegang tot uw computer. Wilt u dit toestaan?",
        "Files": "{0} ({1}) vraag toegang tot uw bestanden. Wilt u dit toestaan??"
      },
      "notificationMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) bediend momenteel uw computer.",
        "Terminal": "{0} ({1}) heeft momenteel een terminal-sessie openstaan met uw computer.",
        "Files": "{0} ({1}) heeft momenteel toegang tot uw bestanden."
      }
}
`

**Comment by Ylianst** [comment]
So, consent messages section goes in the domain section like this. Let me know if it works. I also recommend setting a "sessionkey" so that you don't need to re-login each time you reset the server. Just set it up a random value. Let me know if that works.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "server.abcdef.info",
    "WANonly": true,
    "sessionKey": "MyReallySecretPassword1ABC",
    "port": 443,
    "redirPort": 80,
    "CertUrl": "https://server.abcdef.info",
    "AllowHighQualityDesktop" :  true,
    "SelfUpdate": true
  },
  "domains": {
    "": {
      "title": "ABCDEF",
      "title2": "Remote Support",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "consentMessages": {
            "Title": "ABCDEF - Hulp op afstand",
            "Desktop": "{0} ({1}) vraagt toestemming om uw computer te bedienen. Wilt u dit toestaan?",
            "Terminal": "{0} ({1}) vraagt terminal-toegang tot uw computer. Wilt u dit toestaan?",
            "Files": "{0} ({1}) vraag toegang tot uw bestanden. Wilt u dit toestaan??"
          },
          "notificationMessages": {
            "Title": "MeshCentral",
            "Desktop": "{0} ({1}) bediend momenteel uw computer.",
            "Terminal": "{0} ({1}) heeft momenteel een terminal-sessie openstaan met uw computer.",
            "Files": "{0} ({1}) heeft momenteel toegang tot uw bestanden."
          }
      }
    }
  },
  "letsencrypt": {
    "email": "jdvmanen@my-email.com",
    "names": "server.abcdef.info",
    "rsaKeySize": 3072,
    "production": true
  }
}
```

**Comment by jdvmanen** [comment]
Works! Thanks!

Met vriendelijke groet,

Dirk van Manen

Op wo 29 jul. 2020 om 05:51 schreef Ylian Saint-Hilaire <
notifications@github.com>:
