### ISSUE TITLE
Tray icon (preferable custom)

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1631]
It would be gold if the client agent shows up in the tray icon section, in the Windows taskbar.

Even better would be if that tray icon is customizable. (our company logo)

The absolute best option would be if the customer can start a (support) chat from that tray icon, and if the chat request would have an auto-answer like "Your message is sent to an operator. The operator will contact you within 12 working hours". (Message, yes, customizable).

**Comment by PathfinderNetworks** [comment]
Please, if this is implemented, make it an optional setting- ideally on a per group or per device basis so we could pick and choose where it shows up.  Some of us may not want the tray icon as it can cause confusion among some clients and they will try to shut it down (like they do with antivirus, etc).  But, I do agree, I can see a benefit to having a tray icon as long as it can be branded/customized.

**Comment by Ylianst** [comment]
Not to worry, there is no question that such a feature would be optional. Since the agent is system as a background system process, it's not well adapted for displaying a tray icon. But I could make an optional added tool to make this happen.

**Comment by si458** [comment]
you can download the 'meshcentral assistant' and use the 'application mode, monitor only' mode
you can copy the assistant.exe to next to the meshagent,exe, then ask the assistant.exe to run on users login manually,
then the is a tray icon to monitor the background service, including a request for help button
