### ISSUE TITLE
Install on Windows 10 Build 2004

### ISSUE THREAD

**Issue by ClickLeft** [Ylianst/MeshCentral#1633]
Hi,

I'm trying to install the server version 2.6 on Windows 10 build 2004. I'm getting the following error:

![image](https://user-images.githubusercontent.com/1319013/88265584-a1c3cd00-cc82-11ea-9a3e-5ca1f8bde21a.png)

I have administrative privileges so I'm not sure what else to try.

**Comment by Ylianst** [comment]
Oh dear. I will take a look at this now.

By the way, the version 2.6 is just the version of the Windows Installer, but it will install whatever is the current version of MeshCentral on NPM.

**Comment by Ylianst** [comment]
I just uploaded an updated version of the [MeshCentral Installer 2.6](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-2.6.exe). You can try this one and let me know if it works? Thanks.

**Comment by tlcarpenter** [comment]
I had a similar experience trying to update my MC2 0.5.85 server (I think that was the version number) to 0.5.91 on Windows 10 Enterprise 1909 64-bit (build 18363.959). I got the same or a similar message as ClickLeft did I believe when I tried using the 'reinstall' option of MeshCentralInstaller-2.6 (version  2.6.7486.31421 according to the Windows' file properties information) which I had downloaded 7/19/20. I tried 'reinstall' after quitting the installer when it stalled on "Installing MeshCentral Service...". When 'reinstall' didn't work I uninstalled MeshCentral2 (using the MeshCentralInstaller-2.6), used Windows' Programs and Features to uninstall Node.js, restarted my system, downloaded a fresh copy of MeshCentralInstaller-2.6 that I downloaded last night around 10:30pm (UTC-5), but the installation didn't complete, again stalling at "Installing MeshCentral Service..."; version number from Windows' file properties information for the copy I downloaded last night says the version number is 2.6.7486.31421. I just downloaded a copy using the link in this thread and tried reinstalling MC2 but it stalled on "Installing MeshCentral Service..." as well and after 20 minutes I killed the installer. Windows' file properties information for the copy I downloaded using the link in this thread is the same as the copies I downloaded previously; any chance the copy of the installer that was uploaded earlier isn't the updated version or is it that Windows' file properties information doesn't reflect the actual version of the MC2 installer (no snark intended) - version information displayed in the lower left corner of the MeshCentralInstaller-2.6.exe I downloaded from the link above reads "v2.6.746" as did the copies of MeshCentral-2.6.exe I downloaded previously.

On a whim just now, after quitting MeshCentralInstaller-2.6 that I downloaded from the link above, I re-ran the installer and had it check for updates - the installed version is 0.5.92 but the MeshCentral service has not been added to Windows' 'Services'. Tried installing the service manually and got the following output

C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --install
Installing MeshCentral as Windows Service...
Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\node_modules\minimist'
Require stack:
- C:\Program Files\Open Source\MeshCentral\node_modules\WinService\winservice.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at start (C:\Program Files\Open Source\MeshCentral\node_modules\WinService\winservice.js:39:22)
    at Object.<anonymous> (C:\Program Files\Open Source\MeshCentral\node_modules\WinService\winservice.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Program Files\\Open Source\\MeshCentral\\node_modules\\WinService\\winservice.js'
  ]
}

**Comment by Ylianst** [comment]
Ok, I am going to add a log feature to the installer to generate a full log file of what is going on. Will make things a lot easier to debug & fix. Working on this now.

**Comment by Ylianst** [comment]
[MeshCentral Windows Installer 2.7 is out](https://www.meshcommander.com/meshcentral2). You guys where right, new version of node-windows also broken things. Let me know if it works.

**Comment by tlcarpenter** [comment]
Uninstalled MC2 0.5.92 and Node.js, then downloaded and ran the Windows Installer v2.7 using the link from the page above; installation completed without any issues and MC2 was added to Windows' "Services" and started automatically after rebooting the system. Enrolled a macOS Catalina system with the MC2 v2.7 server, and that works. Looks good. Thank you.

**Comment by Ylianst** [comment]
Excellent, that is how it should work.
