### ISSUE TITLE
Meshctrl.js can't change device group options

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#1634]
Hi

I'm using the meshctrl to automate creation of groups, which works. However trying to identify how I can set the options for the group once this has been created or at the time of creation, at present I can only see how to do this manually from the UI.

the ones i'm interested in are, edit the group features such as "remove device on disconnect" or "sync server device to hostname" but appreciate there maybe other similar items to this.

Alternatively if these options can be set in the config.json as a global parameter to ensure all groups created have these options set, that would also work.

Thanks

**Comment by Ylianst** [comment]
This is a good request, meshctrl can't do that right now.

**Comment by Ylianst** [comment]
I just checked in a new "EditDeviceGroup" action in MeshCtrl.js. This will be in MeshCentral v0.5.94 when I next publish it. Allows you to change all device group settings, including invite codes, name, description...

![image](https://user-images.githubusercontent.com/1319013/88428581-0463b880-cdaa-11ea-8312-3a8678942995.png)

**Comment by Ylianst** [comment]
MeshCentral v0.5.94 is published. Let me know if it works.

**Comment by vish84** [comment]
Perfect, I tested the --flags, this worked fine. Exactly what I was looking for
