### ISSUE TITLE
0.5.91 issue with devices not connecting after upgrade

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1637]
I just upgraded my server from 0.5.88 to 0.5.91.  
I'm now seeing a very strange issue.  I have a little over 300 or so devices in various groups.  After the upgrade only a very small number of those devices are shown as being connected. Typically, after the server restarts like that, you have to wait a few minutes for the devices to start showing back up- so I wasn't concerned about it at first.  But it's been about 2 hours and almost all of the devices have not  reconnected.  I know these are devices that are currently online as I can see them via my Avast CloudCare portal. 
I connected to a couple of devices via another remote tool and restarted the MeshCentral service.  As soon as I did that those devices showed as being online in MeshCentral.  
So, for some reason, this particular server upgrade is causing some type of issue where the agents aren't reconnecting until the service is restarted.  Obviously that is less than ideal as a very large number of my devices are on 24x7x365.  
Any console commands I should be looking at to help diagnose what is causing this?

**Comment by PathfinderNetworks** [comment]
Well, maybe what I posted above isn't actually an issue with MeshCentral.  This is very strange.  Right after I remoted in to those few devices and restarted the MeshCentral services to get them to reconnect I am now noticing that all my other devices are starting to come back as being online.  
It's almost like restarting the MeshCentral service on a couple of those devices kick started something?  Although I know that is likely not the case.  
Just very odd that they are all coming back now.

**Comment by Ylianst** [comment]
This is very odd. Note that all the new MeshCentral compression feature are off by default, so it should not cause any issues. Are you using a reverse proxy? One possibility is that MeshCentral did not pickup the right TLS cert from your proxy and so agents could not connect. Once reset, the server got the right cert and everything worked. However, this is just a theory.

**Comment by PathfinderNetworks** [comment]
No reverse proxy.  Some of the devices (maybe 5% or so?) did reconnect right after the server rebooted after the upgrade. Which is what I typically see- so I didn't think anything about all the other devices showing as offline.  I was confident they'd come back after a few minutes.  But they didn't- at least not until a couple of hours later then they all started showing up around the same time.  
As of right now it's all looking good.  I did find a couple random devices where I still did have to go in and restart the MeshAgent service to get them to reconnect- but these were devices that had been showing as offline for over a week (so something else was going on in that case).

**Comment by PathfinderNetworks** [comment]
I'm going to close this one as I don't know if it actually had anything to do with the upgrade.
