### ISSUE TITLE
can't install mc2 v0.5.92 as a Windows service 

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1640]
I made related comments about this in the context of using MeshCentralInstaller-2.6 in issue 1633, but for this issue I installed MC2 0.5.92 on Windows 10 Enterprise 1909 using npm. I can start the server but can't install it as a Windows service.

C:\Program Files\meshcentral\node_modules\meshcentral>node meshcentral --cert <my server FQDN>
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.92, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on <my server FQDN>:4433.
MeshCentral HTTPS server running on <my server FQDN>:443.
Server Ctrl-C exit...
C:\Program Files\meshcentral\node_modules\meshcentral>node meshcentral --stop
MeshCentral service stopped.
C:\Program Files\meshcentral\node_modules\meshcentral>node meshcentral --install
Installing MeshCentral as Windows Service...
Error: Cannot find module 'C:\Program Files\meshcentral\node_modules\meshcentral\node_modules\minimist'
Require stack:
- C:\Program Files\meshcentral\node_modules\WinService\winservice.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at start (C:\Program Files\meshcentral\node_modules\WinService\winservice.js:39:22)
    at Object.<anonymous> (C:\Program Files\meshcentral\node_modules\WinService\winservice.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Program Files\\meshcentral\\node_modules\\WinService\\winservice.js'
  ]
}

**Comment by Ylianst** [comment]
The module "node-windows" just released a new version that broke MeshCentral. I just published a new version of [MeshCentral Windows Installler 2.7](https://www.meshcommander.com/meshcentral2) and just about to push an update to MeshCentral to fix this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.93 to also fix this. Try the latest Windows Installer, it should work now.

**Comment by johnczer** [comment]
I am getting this same error after upgrading to version 0.6.0.  I used to have to copy the node-modules folder with minimist and node-windows folders to C:\meshcentral\node_modules\meshcentral\ but now this does not work anymore.  When I run "node meshcentral --install" it just deletes this folder now and I get the same error as tlcarpenter stated.

**Comment by johnczer** [comment]
I fixed this by installing the minimist and node-windows@0.1.14 manually!

**Comment by tlcarpenter** [comment]
I was on vacation last week but I'll try updating my MC2 server today and report back.
