### ISSUE TITLE
Smartscreen warning

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1643]
Hi,
Is there a way not to have smartscreen warning display when we execute meshcentral on client computers ?
For all of use using actively meshcentral it's not a problem but for our end users ... They can be confused
D.

**Comment by Ylianst** [comment]
Probably the best way to solve this is to sign the MeshAgent.exe with your own code signing certificate. I use to do that, but people abused it and so, I don't do that anymore. You can take a look here for [instructions on code signing](https://github.com/Ylianst/MeshCentral/issues/1622). Of course, you need a code signing certificate which is not free.

You can probably could also wrap the meshagent.exe in your own installer. Hope that helps.

**Comment by Tomatoschewps** [comment]
Sorry for the double post on same subject ...
I'll test this !
________________________________
De : Ylian Saint-Hilaire <notifications@github.com>
Envoyé : vendredi 24 juillet 2020 19:36
À : Ylianst/MeshCentral
Cc: Damien Brochard; Author
Objet : Re: [Ylianst/MeshCentral] Smartscreen warning (#1643)


Probably the best way to solve this is to sign the MeshAgent.exe with your own code signing certificate. I use to do that, but people abused it and so, I don't do that anymore. You can take a look here for instructions on code signing<https://github.com/Ylianst/MeshCentral/issues/1622>. Of course, you need a code signing certificate which is not free.

You can probably could also wrap the meshagent.exe in your own installer. Hope that helps.

**Comment by Ylianst** [comment]
No worries. Each post adds to the knowledge base :)

**Comment by jdvmanen** [comment]
Sorry lads, again a question about this. I find out that a certificate is not free, but also not cheap so to say... 

@Ylianst , you've said earlier in this post that "You can probably wrap the meshagent.exe in your own installer" is that a workaround to get rid of expensive recurring certificate costs? 

(Sorry for not opening a new issue, but this isn't a 'new' IMHO, but a digging-deeper-question ;-) )
