### ISSUE TITLE
On fresh install of Mesh Central, RDP ClickOnce on Agent no longer works

### ISSUE THREAD

**Issue by FiftyTifty** [Ylianst/MeshCentral#1644]
After having no problems with Mesh Central since I installed it a couple seasons ago, I've found a wee hiccup after doing a reinstall of Windows on my server. Now clicking **RDP** no longer works, whereas it did a few hours ago prior to the new install.

There's no discernable output, so is there a log kept somewhere that I can share?

This occurs on both 0.5.81, and 0.5.93. Browser I'm using is Firefox with the Breez ClickOnce extension. The server's OS is Windows 10 Enterprise LTC 2019 (Windows 1809), as is the desktop I'm using to access Mesh Central.

I've tried using the RDP ClickOnce feature just after logging in with the new admin account, which didn't work. Then I added my settings to config.json, added 2FA via the Google Authenticator app, and still RDP doesn't work.

To clarify, when I say it no longer works, absolutely nothing happens after clicking **RDP**. No windows pop up, no error message, no options, nothing.

**Comment by Ylianst** [comment]
Somewhat related to this, I was thinking of removing OnceClick support because it's a pain and it only works on IE. If you have FireFox of Chrome you need to install a ClickOnce add-on and MeshCentral can't detect if you have the add-on installed or not.

The alternative is to download MeshCentral Router, on the first screen you can register "mcrouter://" and then, from any browser you can click the link to invoke it. It works a lot better in my view.

This said, I will see what is going on with ClickOnce. I have not changed it in a long time.

**Comment by FiftyTifty** [comment]
Ooh. Are there step by step instructions for MeshCentral Router? I remember taking a look at it in the past, but it wasn't intuitive enough for me.

**Comment by Ylianst** [comment]
Here are the instructions. Your right, the UI needs to be improved. I will be adding direct links from the devices page for use with MeshCentral Router. Feedback appreciated.

![image](https://user-images.githubusercontent.com/1319013/88421072-b98f7400-cd9c-11ea-9002-8f9600b69926.png)

**Comment by Ylianst** [comment]
I just tested on the developer server and ClickOnce worked for me. Can you try IE11 and see if it work. I will take a guess that the pop-up blocker on FireFox may be blocking it. In FireFox, you can open the console (CTRL-SHIFT-K) and see if there are any error messages. I think this is just a case of pop-up blocking.

![image](https://user-images.githubusercontent.com/1319013/88429649-daab9100-cdab-11ea-9ea1-8ea12c88a71d.png)

**Comment by FiftyTifty** [comment]
You were correct, Firefox was blocking pop-ups, and I had to add an exception. This was pure user error then, my apologies.

**Comment by Ylianst** [comment]
No worries :) Thanks for reporting back.
