### ISSUE TITLE
Agent bad web cert hash

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1646]
After upgrade to v0.5.94 popped out `Agent bad web cert hash error` so no client is reachable anymore, I haven't changed anything else in my server configuration...hints? Thanks!

**Comment by Ylianst** [comment]
As a temporary measure, you can add the following line in the settings section of config.json:

"ignoreagenthashcheck" : true

What version of NodeJS are you using? Is the server on Windows or Linux? Do you have a reverse proxy? Are the agents that don't connect all Windows, all Linux or both? - Thanks.

**Comment by amenolo** [comment]
Sorry to have been so scanty in details, I was in a hurry...here we are:

- server info


 Download console text
> info
```
{
    "rss": 133214208,
    "heapTotal": 46768128,
    "heapUsed": 45328248,
    "external": 29915656,
    "arrayBuffers": 28507648,
    "dbType": "NeDB",
    "nodeVersion": "v13.11.0",
    "meshVersion": "0.5.94",
    "platform": "linux",
    "arch": "x64",
    "pid": 28274,
    "uptime": 18032.440099056,
    "cpuUsage": {
        "user": 4330050,
        "system": 313109
    },
    "warnings": [],
    "database": "NeDB",
    "productionMode": true
}
```

**Comment by amenolo** [comment]
Sorry to have been so scanty in details, I was in a hurry...

All agents unreachable regardless clients OS, server running behind Apache2 reverse proxy (along with Let's Encrypt TLS certs, updated)

**Info**

```
{
    "rss": 133214208,
    "heapTotal": 46768128,
    "heapUsed": 45328248,
    "external": 29915656,
    "arrayBuffers": 28507648,
    "dbType": "NeDB",
    "nodeVersion": "v13.11.0",
    "meshVersion": "0.5.94",
    "platform": "linux",
    "arch": "x64",
    "pid": 28274,
    "uptime": 18032.440099056,
    "cpuUsage": {
        "user": 4330050,
        "system": 313109
    },
    "warnings": [],
    "database": "NeDB",
    "productionMode": true
}
```

**Config**

```
{
  "settings": {
    "cert": "mesh.domain.tld",
    "Port": 8081,
    "RedirPort": 8082,
    "AliasPort": 443,
    "AgentPong": 300,
    "TLSOffload": "192.168.1.3",
    "Wanonly": true,
    "WebRTC": true
  },
  "domains": {
    "": {
        "newAccounts" : 0,
        "certUrl": "https://mesh.domain.tld",
        "mstsc": true
    }
  }
}
```

**Apache2 vhost**

```
<VirtualHost *:80>
    ServerName mesh.domain.tld
    Redirect permanent / https://mesh.domain.tld
</VirtualHost>

<VirtualHost *:443>

        ServerName mesh.domain.tld

        Include /etc/apache2/domain.ssl

        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule . "ws://192.168.1.4:8081%{REQUEST_URI}" [P]

        ProxyPass / http://192.168.1.4:8081/ connectiontimeout=86400 timeout=30
        ProxyPassReverse / http://192.168.1.4:8081/
        ProxyPreserveHost On

        ErrorLog ${APACHE_LOG_DIR}/mesh_error.log
        CustomLog ${APACHE_LOG_DIR}/mesh_access.log combined

 </VirtualHost>
```

All of above settings have been unchanged for a long time now and meanwhile I didn't modify anything in networking config, yesterday I just updated server (via WebUI as usual) before shutting down my box and I happened to notice the issue today.

**Comment by amenolo** [comment]
I owe you my sincere apology for wasting your time in helping me since I was in a hurry and I didn't pay more attention to the full error which stated also Failed to load web certificate at: "https://mesh.domain.tld"...long story short my router "decided" not to execute hairpin NAT rules no more even if I didn't touch relative settings for a long time now...anyway I sorted it out so currently MC is full functional again and agents online.

Regardless of my blunder your readiness is always appreciated, of course 👍

**Comment by Ylianst** [comment]
Ha yes, I completely understand what happened. Since it failed to load your TLS cert, it should be authenticate the agents correctly. Thank you for reporting back in such a detailed way, I am glad you back up and running.
