### ISSUE TITLE
open chrome session as "open as windows"

### ISSUE THREAD

**Issue by fcaiveau** [Ylianst/MeshCentral#1647]
![image](https://user-images.githubusercontent.com/53363959/88478927-47f62800-cf4c-11ea-9053-85904b1a3545.png)

it would be nice to be able to open the session or even mesh central directly like the feature that chrome offer to open a new windows as "open as windows" which will remove any bar or bookmark in chrome windows

![image](https://user-images.githubusercontent.com/53363959/88479065-fb5f1c80-cf4c-11ea-8777-5b4b46009f26.png)

or when we click on the computer instead of opening in a frame to open it in new windows like "open as windows" 

hope this will be helpful...

**Comment by Ylianst** [comment]
Can you try holding the SHIFT key and clicking on devices, or tab headers? It should open what you click on a new tab. Let me know if that works for you. Thanks.
