### ISSUE TITLE
Add "description" column on the view from "My Devices"

### ISSUE THREAD

**Issue by supr4s** [Ylianst/MeshCentral#1653]
Hi,

It would be great if the description of the agent was displayed in the "list" view in addition to his name and public IP address.

In my case (and I think it is for many other people) I have several groups and in each group a lot of PCs in it. The PCs have a description box that is used to describe the person using the computer, its location etc.
In order not to waste time clicking on each agent to read its description, it should be displayed directly!

Regards,
Supras

**Comment by vitko-bg** [comment]
In addition to request above, please add last seen column also. Requested in #1137 :)
Thanks.

**Comment by si458** [comment]
This is already possible now,
In list view, click the cog on top right hand side, and select what columns you want to show
