### ISSUE TITLE
SUGGESTION: Favorites Section for frequently connected to computers

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1655]
So we have some 1500ish computers in mesh.  Working great by the way.  Thanks to Ylian, Bryan and team for all their hard work.

Sometimes finding that oft-connected to computer means lots of scrolling and searching through many groups and systems.  

A suggestion then: 
1.  Make the Group name searchable as well, not just the system name
2.  Make a "Favorites" section, where we can click on a button and add a device to the favorites group.  I've attached a screenshot that adds a star icon, (much like adding a bookmark in a web browser).  If the device is starred, then it is added to a "favorites" group.  You could then add a "favorites" to the top filter and only see those devices you have starred. 
(See attached)

![image](https://user-images.githubusercontent.com/45638572/88564577-5baf9600-d001-11ea-9296-0d04805ff63a.png)
![image](https://user-images.githubusercontent.com/45638572/88564612-6538fe00-d001-11ea-836a-67c35bb6e34a.png)
![favorites](https://user-images.githubusercontent.com/45638572/88564627-6a964880-d001-11ea-912f-22904159c2cd.jpg)
![favorites2](https://user-images.githubusercontent.com/45638572/88564628-6a964880-d001-11ea-9378-2ce94d6cfd4e.jpg)

Thanks!

**Comment by vitko-bg** [comment]
There is already option to search by group in MC, try searching "group:<groupname>" - works fine for me.
In regards to favourites - looks like only @Ylianst can answer this :)

**Comment by southeasterntech** [comment]
> There is already option to search by group in MC, try filtering with string "group:", i.e. "group:blablabla" - works fine for me.
> In regards to favourites - looks like only @Ylianst can answer this :)

Didn't know this!  that's a great tip!  Still like the favorites idea though.  Thanks for the response!

**Comment by Ylianst** [comment]
The search box support the following: 

`user:` or `u:` to filter devices with a given user logged on the remote device.
`ip:` devices at a given IP address.
`group:` or `g:` for devices within a device group.
`tag:` or `t:` filter devices with a tag.
`atag:` or `a:` filter on agent tag (meshagent.tag file).

I do like the stars, but I image that would be per-user where different users would have different device stars? I would need to think about this.

**Comment by southeasterntech** [comment]
Thanks Ylian... yes...I would think each user would have a different favorites list as their job function might have them connecting to different systems.  Thanks!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.96 with a new device "Star" feature. You can right click on a device and hit "Toggle Star" to add or remove a star next to the device. You can also type * in the filter box to only show starred devices. Each account can star at most 20 devices (this is to limit the account state size).

![image](https://user-images.githubusercontent.com/1319013/88740782-e7edb600-d0f2-11ea-8da5-5a3e9fe7f390.png)

Feedback appreciated.

**Comment by southeasterntech** [comment]
Amazing Ylian!  Better than I'd hoped.  Great job.
