### ISSUE TITLE
Failed to restore database

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1657]
![image](https://user-images.githubusercontent.com/26174637/88615999-a5779b00-d058-11ea-9e63-d07ee6bfc1ef.png)
Hello, while updating mongo I had a number of problems. I have restored the server settings but I am getting these errors. Could you please tell me how I can get this income back?

I have lost all my groups by updating mongodb.
![image](https://user-images.githubusercontent.com/26174637/88616098-d8219380-d058-11ea-87bf-0f5f38137a03.png)

**Comment by Ylianst** [comment]
Are you trying to migrate from NeDB to Mongo? If so, let me know. You need to export the database as a JSON, then enable MongoDB and re-import the data. I can give you instructions.

**Comment by desarrollocdb** [comment]
I've always used mongo, I don't think I'm using NeDB, how do I know this?

Another matter: sometimes I have to restart the server to recognize new agents.

**Comment by Ylianst** [comment]
Hi. NeDB is the built-in database that is in MeshCentral is you have not configured MongoDB. So, the original question is that you reset the MongoDB database and now you need to restore it. To did you have a backup of the database? MeshCentral will make a backup in "meshcentral-backup" and that may contain the MongoDB database backup.

**Comment by desarrollocdb** [comment]
![image](https://user-images.githubusercontent.com/26174637/88687896-70059880-d0be-11ea-9d09-fef523dc0ca7.png)


Thanks for the reply. I'm supposed to have automatic backup turned on but it apparently didn't work.

In conclusion, I have lost my database.

**Comment by desarrollocdb** [comment]
Get unknown device group error. How can I recover the connections of those agents?

**Comment by Ylianst** [comment]
First, a note to everyone. If you own a MeshCentral server please always backup the "meshcentral-data" folder and if you are using MongoDB or a different database other than the built-in one, please backup both "meshcentral-data" and the database you are using.

So, there is the way to save your server. In the domain section of the config.json add this line:

```
"orphanAgentUser": "admin"
```

There "admin" should be the user name of your account. When agents connect, if there is an unknown device group, a new device group will be created in your account and agents will connect correctly. For example:

```
{
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "orphanAgentUser": "admin"     <---------------
    }
  }
}
```

When agents reconnect, you will need to rename the device groups. Hope that helps.

**Comment by desarrollocdb** [comment]
Fantastic!!!!!!!!. You have saved my life. Thinking of recovering the connection of 120 machines. You are a teacher, thank you very much.

Fantastic!!!!!!!!. You have saved my life. Thinking of recovering the connection of 120 machines. You are a teacher, thank you very much.

The groups have indeed been created.

**Comment by dasilvasp** [comment]
I had a problem where autobackup did not copy the mongodb archive. 

When I enter "orphanAgentUser": "admin" (using my user ID) below "_userNameIsEmail": true and restart the server, the warning "ERROR: Unable to parse /home/ubuntu/MeshCentral/meshcentral-data/config. json." and the server does not start in Ubuntu. 
I did the test with and without quotes.


  "domains": {
    "": {
      "title": "Mesh Service - Certti",
      "title2": "Server Oracle",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
      "orphanAgentUser": "admin"
    }
  },

**Comment by si458** [comment]
@dasilvasp run ur config.json through https://jsonlint.com, you have forgotten to put a `,` after ur `_usernameisemail` line

**Comment by dasilvasp** [comment]
@si458, That's right, I copied the code into Sublime and managed to find the problem. Thank you very much for your help! Good Business!

@si458, Era isso mesmo, eu copiei o cídigo no sublime e assim consegui achar o problema. Muito obrigado por sua ajuda! Bons negócios!
