### ISSUE TITLE
Filter on public IP address

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1658]
Hi,

It would be helpfull in some cases to be able to filter on IP address, where you now can filter on configured agent name and machine name.

Doing this, you see all the connected machines to the same network. This can help to find a strange-named agent. Plus, it can give me an indication if it makes any sense to send a 'wake machine' signal :-)

**Comment by Ylianst** [comment]
Hi. In the "My Devices" page, you can type in the filter box the following:

`user:` or `u:` to filter devices with a given user logged on the remote device.
`ip:` devices at a given IP address.
`group:` or `g:` for devices within a device group.
`tag:` or `t:` filter devices with a tag.
`atag:` or `a:` filter on agent tag (meshagent.tag file).

So, for example `ip:192.168.` to see any devices that have `192.168.` in the IP address. Let me know if this helps.

**Comment by jdvmanen** [comment]
Hi Ylianst, 

That's exactly what I need! Thanks for outstanding and fast support.
