### ISSUE TITLE
Potential bug: inability to create folders via upload?

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1660]
Using MC2 v0.5.52 (and built in FIPS mode, hence the "potential" bug) when I connect to my remote client, I'm unable to select folders from my host and transfer them directly to the client. The interface stalls. I can cancel the upload, create the folder on the client manually (using the Create Folder button on the toolbar), navigate into that folder (on both my host and the client) and then upload the files just fine.

In the event log, when attempting to drag a folder from the host to the client, I do see an entry stating "Starting remote files without notification" but then that's it.

When I manually create the folder (remotely) and then upload the files within that folder, the event shows the "Create folder: xxx" entry and all the "Upload yyy" individual sessions.

Thoughts?

**Comment by jsastriawan** [comment]
FIPS mode disable several hashing algorithms considered insecure. I am not sure where the hashing algorithms (MD5) are being used here (probably somewhere in the websocket or file upload mechanisms). So, fail because of this is possible.

**Comment by D4V3M0NK** [comment]
Additionally, it appears that I can't upload to the MC2 server either, within the **My Files** section either.

@jsastriawan I've also just tested this on a secure installation locally (as per #830) which is a standard (non-FIPS) kernel system and I can't do that either.  I appreciate that this may have something to do with the secure installation...

**Comment by D4V3M0NK** [comment]
Just searched on "drag and drop" and saw #1512 so I'm going to close this
