### ISSUE TITLE
[Feature request] - Chat / audit function

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#1661]
Hello,

I know there is a chat function between MC users but i would want to see chat / audit function when assisting a remote session and the other end is not a user in the system, which the chat bubble should only be visible when enabled by the support provider.

**Comment by Ylianst** [comment]
Not sure I understand the request. Do you want chat recording? Or a way to turn off chat completely?

**Comment by treicadani** [comment]
Completely missed that one out, i saw now there is a little chat bubble at the bottom right of the remote desktop function, but can it be changed in the other end to be like a small bubble to be always on top or something? as it opens a full web browser window in the other end. And can it be automated to save the transcript at the end of the conversation?

**Comment by si458** [comment]
you can now save chats using `sessionRecording` and setting `protocols` to include `200`
also sadly the is no way to make a small version of the chat window, as it opens up in the users default web browser
but the user could just make the window smaller themselves
