### ISSUE TITLE
Mesh Router constant refresh, version 0.5.81

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1664]
My Mesh router is constantly refreshing, on the mesh server and on all users.  On most of my users, the devices never actually load.  See screenshot.  Restarting mesh does not fix.  I dona't see anything related to this in mesherrors.txt.

Is this a bug in the new version, or a configuration issue on my end?
Thanks (see screen)
![router-refresh](https://user-images.githubusercontent.com/45638572/88814639-62b4e080-d188-11ea-8098-20ace150c468.JPG)

**Comment by Ylianst** [comment]
That is not good. Can you run `MeshCentralRouter.exe -debug`? This will create a debug.log file. You can then send it to me privately, [my contact here](https://www.meshcommander.com/contact-information). I will take a look at it. You can also post the log here, but make sure to XXXX any private information. Thanks.

**Comment by southeasterntech** [comment]
Just emailed you the debug log.  Thanks Ylian,
Shane

**Comment by Ylianst** [comment]
Thanks for the logs. Logs did not show anything interesting except that you have a lot of devices on a single account and the MeshCentral Router user interface is having a hard time with it. So, I just created a new version with a different device list that can render much faster and a lot more devices. You can [download it here](info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.zip). Can you give it a spin and let me know if it works? I will update the version within MeshCentral once you give the ok.

Also, you can run `MeshCentralRouter.exe -oldstyle` if you want to see the old interface. Thanks.

**Comment by southeasterntech** [comment]
Sorry Ylian, got distracted for a few days... the link isn't working now?  Thanks for this.

**Comment by southeasterntech** [comment]
disregard, found the old link which looks like it's updated.  Looks GREAT!  instant loading now

Thank you sir.  You're the world's most awesome dev!
Shane
