### ISSUE TITLE
Grouped action : Add TAG

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1665]
Hi,

We are migrating hundreds of machine to meshCentral and we have some info that we want to add in tags.
IMO it might come inhandy to add/replace tag to multiple agent at a time by the "Grouped action" button.

What do you think ?

**Comment by Tomatoschewps** [comment]
Sorry, already asked in #926 but not answered, contrary to the other requests from same issues

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.98 with a new "Edit Tags" in the device groups actions. Let me know if this works for you.

![image](https://user-images.githubusercontent.com/1319013/88987823-076c1680-d28c-11ea-9219-80486dc35e5b.png)

**Comment by Tomatoschewps** [comment]
Amazing !
Thanks :)
