### ISSUE TITLE
Agents connecting and disconnecting on v.0.5.96

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1666]
I've got an issue lately where agents will connect and then disconnect periodically, maybe 2 or 3 times per minute.  I am using Caddy reverse proxy here, and wonder if that's part of this, though it's been working fine in the past.  What's the best way to troubleshoot this?

Thanks.
Shane

**Comment by Ylianst** [comment]
Are the machines doing this running Windows Server 2012 by any chance? (If so, we have a fix coming up) If not what agents are doing this? All of them, or what OS are they running?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.5.97 with Bryan's fix for Windows Server 2012.

**Comment by southeasterntech** [comment]
The one's I've noticed do seem to be 2012R2 now that you mention it.  I'll update and report back. 
Thanks!

**Comment by southeasterntech** [comment]
I'm going to say cautiously that resolved it.  I'm seeing all my 2012's online now, where it was totally hit and miss.  The ones that word flashing on and off, don't appear to do it now!

Thanks Ylian, Bryan and team, you guys are really the best

**Comment by Ylianst** [comment]
Oh good. Yes, there was certainly a problem with WS2012 that should be fixed in this agent.

**Comment by asasin114** [comment]
FIXED! Thank you!
