### ISSUE TITLE
Server reset warning message prior to updates

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1667]
Hi MeshCentral Dev Team,

Here is a feature request for the server side of the coin, can active users that are online be ballon notified or Toast notice of server rebooting in x amount of time due to server upgrades? 

Thoughts and concerns greatly appreciated.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
This is a good request. If the server is about to update, it would be nice to broadcast a message to all users that indicates that this is about to happen.
