### ISSUE TITLE
Odd Agent Behavior, duplicated Computers on some (0.5.98)

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1668]
**_UPDATE: Similar to issue #774_**

I saw something strange today.  Not sure how to explain it, but here goes.

1.  Was working on a 2016 Server.  Utilizing your new "Toggle Star" feature.  Server was in the Starred list
2.  Processed some updates on the server, server requested restart.
3.  Restart server.
4.  Noticed in Mesh, server did not come back online.  
5.  Noticed Server was online in another RMM tool, connect, MeshAgent Service is running, that's weird
6.  Remove the * filter, then search for the server name...
7.  Weird, there's the server in Mesh...showing online, now I have 2.  The online server is not "Starred", offline IS "starred"
7.  Deleted my "Starred" Server, and Starred the new Server that showed up.
8.  Why did it come back as a new entry\agent?

On this note, I seem to have a great many duplicated devices, but not all are duplicated.  I'm constantly having to go and delete duplicate computers that are showing offline, but online in a duplicated entry.  I am using caddy reverse proxy.
1.  How to mass delete duplicate computers that show offline?
2.  Better yet how to detect those "new" online versions of the same computer and merge them, and\or fix bug\config issue?
3.  This has been a long-standing issue.... happening to all users, and over the last 2+ years we've been using mesh.
![dupe2](https://user-images.githubusercontent.com/45638572/89042273-adfbfa00-d314-11ea-8a7a-8d1e64cd7781.JPG)
![dupe](https://user-images.githubusercontent.com/45638572/89042275-adfbfa00-d314-11ea-8714-a31bed9d2351.JPG)

**Comment by krayon007** [comment]
For one of your agents that is duplicated can you show me your log file that was generated. I had updated the agent a while back so it will write new entries in the log whenever it needs to change its node ID which is what would cause it to duplicate in the browser.

**Comment by southeasterntech** [comment]
So...looks like a MAC address mismatch?  This server has multiple network adapters.  Would this be to say that if a person connects with wifi it will have a mismatch the next time that device connects with ethernet?

_____________Server Agent Log____________


[2020-06-18 12:40:55 AM] FATAL EXCEPTION [MeshAgent_7E1808999D982720.exe] @ [FuncAddr: 0x00007ff63bdca5e1 / BaseAddr: 0x00007ff63bdf7798 / Delta: 184759]

[2020-07-07 12:48:35 AM] FATAL EXCEPTION [MeshAgent_3991501F204C77A1.exe] @ [FuncAddr: 0x00007ff60fa4c3e5 / BaseAddr: 0x00007ff60fa79bdc / Delta: 186359]

[2020-07-31 09:36:53 AM] NodeID will reset, MAC Address Mismatch: [5A:25:41:21:9C:59][5A:25:41:21:9C:59][5A:25:41:21:9C:59][5A:25:41:21:9C:59] <==> [BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA][BE:FA:D5:70:DA:FA]

**Comment by krayon007** [comment]
The way it's supposed to work, is that it compares the list of MAC addresses it currently finds, with the list of MAC addresses that were saved... So even if you connect with WiFi then Ethernet, it should still find at least one match...  This use case was to detect things like when you copy a VM instance, etc...

What's interesting is that the saved MAC address list looks to list the same MAC address multiple times... Is that MAC address match any of your interfaces? I'll see if I can reproduce a scenario where the list looks like that...

**Comment by krayon007** [comment]
Are you able to show me the output of: ipconfig /all
I want to see how your interfaces are configured... My system has multiple interfaces as well, but my MAC address list isn't duplicated like yours is... I want to see if I can duplicate your setup, so I can see what is going on...

**Comment by krayon007** [comment]
If you need to sanitize the output for privacy reasons, I only really need just a partial on the ip address and MAC address....

**Comment by krayon007** [comment]
And the output of this command:
MeshAgent -exec "console.log(JSON.stringify(require('os').networkInterfaces(),null,1));process.exit();"

**Comment by Ylianst** [comment]
As Bryan mentioned, we have an "anti-cloning" feature in the MeshAgent when if you image a boot disk and copy it to many other computers, the agent will notice that none of the MAC addresses match the last time it ran. When it detects this situation, it resets it's identity. This is so that if you image many computers with the same OS image, all the agents will not all show up as the same computer.

In your case, the server you are running changed it's MAC address and triggered the anti-cloning system. We have to figure out if we did a bad job detecting the network interfaces, or if this performed as expected.

**Comment by emersonnpe** [comment]
Has anyone managed to find the solution? I have the same problem.

**Comment by fabiomontefuscolo** [comment]
Same thing on Manjaro linux

```
➜  meshagent cat meshagent.log 

[2022-02-18 08:41:01 PM] [*************************] microstack/ILibParsers.c:10746 (0,0) Info: No certificate was found in db
[2022-02-18 08:42:22 PM] [*************************] microstack/ILibParsers.c:10746 (0,0) NodeID will reset, MAC Address Mismatch: [00:00:00:00:00:00][00:00:00:00:00:00][12:5F:3C:7B:C4:51] <==> [00:00:00:00:00:00][00:00:00:00:00:00][B0:A7:B9:F6:BB:5E][B0:A7:B9:F6:BB:5E]
[2022-02-18 08:49:14 PM] [*************************] microstack/ILibParsers.c:10746 (0,0) NodeID will reset, MAC Address Mismatch: [00:00:00:00:00:00][00:00:00:00:00:00][3A:CB:F8:50:EF:8E] <==> [00:00:00:00:00:00][00:00:00:00:00:00][12:5F:3C:7B:C4:51]%                                                                                                                                                                                                                                         ➜  meshagent ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wls33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b0:a7:b9:f6:bb:5e brd ff:ff:ff:ff:ff:ff
    altname wlp3s0
    inet 192.168.1.143/24 brd 192.168.1.255 scope global dynamic noprefixroute wls33
       valid_lft 86277sec preferred_lft 86277sec
    inet6 fe80::f196:3163:c7d2:1802/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
➜  meshagent pwd
/usr/local/mesh_services/meshagent
```

**Comment by si458** [comment]
you can add `skipmaccheck=1` to your `meshagent.msh` file to help with duplicates
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back

**Comment by KellyDi0te** [comment]
Hello, 

The issue has been occuring for the past 2 weeks in my company. 
As you can see in the screenshot, some of my agents are duplicate : 

![image](https://github.com/Ylianst/MeshCentral/assets/41836497/943fadc5-0f59-4401-98dd-ef6f1bc3b54a)


I also noticed in the console that it's possible to see the number of duplicateAgents.
By doing : 
> agentstats
createMeshAgentCount: 5102
agentClose: 4604
agentBinaryUpdate: 35
agentMeshCoreBinaryUpdate: 0
coreIsStableCount: 4336
verifiedAgentConnectionCount: 4648
clearingCoreCount: 0
updatingCoreCount: 702
recoveryCoreIsStableCount: 0
meshDoesNotExistCount: 0
invalidPkcsSignatureCount: 0
invalidRsaSignatureCount: 0
invalidJsonCount: 0
unknownAgentActionCount: 0
agentBadWebCertHashCount: 0
agentBadSignature1Count: 0
agentBadSignature2Count: 0
agentMaxSessionHoldCount: 0
invalidDomainMeshCount: 0
invalidMeshTypeCount: 0
invalidDomainMesh2Count: 0
invalidMeshType2Count: 0
**duplicateAgentCount: 960**
maxDomainDevicesReached: 0
agentInTrouble: 1
agentInBigTrouble: 0


Is it also possible to delete them all with a command ? 

Thank you,

**Comment by si458** [comment]
@KellyDi0te sadly you have to add the value one machine at a time and the restart meshagent

The is already a feature request open to allow this to be pushed to remote devices which I'm looking into https://github.com/Ylianst/MeshCentral/issues/5845

**Comment by si458** [comment]
@KellyDi0te also just realised u meant delete the duplicate agent.
No the isn't a command,
you have to tick the checkboxes next to the devices u don't want in the webui, then click group actions and delete devices

**Comment by silversword411** [comment]
https://www.si458.co.uk/2024/01/05/donation/

To keep those fixes coming

**Comment by KellyDi0te** [comment]
Hello again, 

Agents were duplicating because of my mistake.. I have a script to deploy the agent on every machine, but sometimes the script would launch itself again, uninstall the agent then reinstall it, making a duplicate on the web interface. 

Changed the script, everything works fine now. 
I added `skipmaccheck=1` by precaution as well.
