### ISSUE TITLE
How to find the "None" tags?

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#1671]
Devices with "None" tags are not easy to find, due to even using the Sort or Search option, those without a tag are not appearing anywhere.

**Comment by Ylianst** [comment]
To find a tag, enter `tag:<tag>` or `t:<tag>` in the devices filter box. To find devices without any tags, just type `tag:` or `t:`. That should do it. Let me know if it works.

**Comment by MC-PM** [comment]
works great... thank you!
