### ISSUE TITLE
WS 2012 R2 not respond

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#1674]
[MeshAgent.log with WS](https://github.com/Ylianst/MeshCentral/files/5014062/meshlog.txt)
The server on which the meshagent is installed has stopped responding. It was impossible to enter either via the rdp or locally. In the Windows event logs, multiple restart of the meshagent service.
Server version Meshcentral - stable 0.5.11

**Comment by Ylianst** [comment]
Windows Server 2012 has some oddities. Over the last few weeks we got some reports of issues and Bryan tested and fixed them. Starting with MeshCentral v0.5.97, the MeshAgent should work much better on WS2012. Let me know if that helps. See issues #1656, #1666 for details.

**Comment by Ilia1** [comment]
I cannot update the MC server until this bug is fixed #1331, thanks.

**Comment by Ylianst** [comment]
Ok. I will close this one since it's fixed in later versions. If you update and if happens again, please open the issue once more.
