### ISSUE TITLE
Guest account restrictions

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1677]
Is it possible to restrict an account so that it is unable to change passwords, 2FA etc? Perhaps even get rid of the account tab for that user? We have a guest account setup and it requires 2FA which is sent to an email distribution group for our technicians. This makes it so the end user must be talking with a tech in order to get the code. I don't want a guest user able to make account changes, otherwise we would have to change the password each time.

**Comment by Ylianst** [comment]
Yes, this is a good request.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.2 with new "Lock Account Settings". This is an account server permission that blocks any settings from being changed on the account. This includes language, password, email, etc. Can you give it a try and let me know if it works? Thanks.

![MC2-GuestAccounts](https://user-images.githubusercontent.com/1319013/89491388-0b080d80-d764-11ea-9921-598e86a44f1c.png)

**Comment by frankmcc** [comment]
Perfect!  Thanks!
