### ISSUE TITLE
[0.3.1-x] Remote "Desktop" view - cuts bottom of full screen

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#168]
When using MeshCentral webui 'Desktop' view, the remote screen is displayed in full with no issues.

However when the "fullscreen" button is pressed and fullscreen mode activated it cuts a large chunk of the remote screen. It has worked in previous versions. 

It occurs in Firefox and Chrome. Has no errors in developer console. Tested on multiple agents.

**Note the absence of the "Windows Server 2008R2" logo in the second picture.**

See images below.

![no full screen](https://user-images.githubusercontent.com/37466255/55664213-9f174b80-5876-11e9-968f-89db79dd81f4.JPG)

![full screen - cuts image](https://user-images.githubusercontent.com/37466255/55664215-a2aad280-5876-11e9-9d6f-af22029f098f.JPG)

![ver](https://user-images.githubusercontent.com/37466255/55664216-a50d2c80-5876-11e9-8de9-7f6f0955af4f.JPG)

**Comment by Ylianst** [comment]
Thanks for the report. Just published MeshCentral v0.3.1-y with a fix for this. Let me know if it works.

**Comment by theredkoala21** [comment]
Tested with new update. Resolved.
