### ISSUE TITLE
Updating MC2 0.5.94 to 0.6.1 broken

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1680]
I installed MC2 0.5.94 (using MeshCentralInstaller-2.7 build/file version 2.7.7509.26426) on a Windows 10 Enterprise 1909 64-bit system (OS build 18363.959) a week an a half ago. Ran MeshCentralInstaller-2.7.exe again to check for updates and had it attempt to install the update to 0.6.1. Towards the end of the update to 0.6.1 I got the following error

![20200804-mc2-0 5 94-update-to-0 6 1-error](https://user-images.githubusercontent.com/727537/89315850-537ed880-d649-11ea-9468-c0f2b1aa8fa6.PNG)

**Comment by tlcarpenter** [comment]
FWIW I downloaded a new copy of MeshCentralInstaller-2.7.exe (same build/file version as above, 2.7.7509.26426) today. I still had the copy of MC2 installed that produced the error above and when I ran the new copy of MeshCentralInstaller-2.7.exe, I had it check for updates, and was told the installed version was already 0.6.1. I tried connecting to the console but was unable to - sorry, didn't check if the service was installed and running. I then re-ran MeshCentralInstaller-2.7.exe and chose the "Reinstall" option which finished without any errors and I was then able to connect to the console. The reinstalled MC2 server was running the default 'config.json' so I just replaced that with a backup copy of my modified config.json and things appear to be back to normal.

**Comment by Ylianst** [comment]
Looking into this one now.

**Comment by Ylianst** [comment]
Thanks for reporting this. Indeed, when updating the NodeJS version was set to null and causing the exception. I just fixed it and uploaded a new version of [MeshCentral Installer 2.7](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-2.7.exe ). Next time you update, feel free to give it a try, should work now.
