### ISSUE TITLE
FEATURE REQUEST - Desktop Icon

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#1682]
Hi,

Maybe, is possible with agent installer, create a desktop Icon for get computer information, for example:

Hostname:
Windows Versión:
UserName:
Public IP:

This is for remote support similar to Anydesk or teamviewer.

**Comment by Ylianst** [comment]
Also, if you have screen shots of the request, that would help.

**Comment by FrankSanabria** [comment]
Thanks for answering.

For example, a user creates a ticket to request support, we to provide support request the name of the PC, but not all users know how to obtain this information. It would be easy for the MeshAgent icon to show this information on the desktop to be attached to the Ticket.

**Comment by Ylianst** [comment]
Indeed, it would be interesting to be able to request a support ticket directly into MeshCentral. Right now, you can look in the registry and find the NodeID for your own device. You can also type "u:<username>" to filter devices by logged in users.

In the past few weeks, we also added a new agent notification system that allows an agent to display messages on the web page. It's not used for anything yet, but it could be used for this purpose.

![image](https://user-images.githubusercontent.com/1319013/89610207-cf864580-d82e-11ea-8cbd-5e93a9370907.png)

**Comment by Tomatoschewps** [comment]
Hi @Ylianst 
agent notification system can be a great new feature !
IMO it can be used by a desktop icon or by a systray icon as say in #1631 .

In the meantime is there a way to use the agent notification system by calling the agent with parameters or something or is it just there but not usable yet ?

I think of a desktop icon starting a small batch file that end user can launch when they want assistance until you get time to add such function :)

**Comment by FrankSanabria** [comment]
You're right, for example, we use this bat file in the desktop User (Windows 10), and him send us via email the screenshot:
```
@echo off
echo            =========================================
echo            = DATOS NECESARIOS PARA BRINDAR SOPORTE =
echo            =========================================
echo\
echo  Fecha de hoy: %date% 
echo.
echo  Nombre del Equipo: %computername% 
echo.
echo\
nslookup -querytype=TXT o-o.myaddr.l.google.com ns1.google.com > ip.txt
echo  Direccion IP Publica:
findstr """ ip.txt 
del ip.txt
echo\
echo  El Usuario es: %USERNAME% 
echo.
echo\
echo  Presione la tecla "SPACE" para cerrar esta ventana...
pause > nul
```

**Comment by si458** [comment]
closing as stale and wont be implemented, sorry about this
