### ISSUE TITLE
Adding System Icons

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1683]
I'm working on adding some system icons to the iconsxxx.png files.  Where are these referenced when picking them from the web interface?  

Perhaps in the future a feature could be added to allow end users to add their own icons?

**Comment by Ylianst** [comment]
Right now, you can't add new icons but you can change the existing one. Next to the "meshcentral-data" folder, create a new folder called "meshcentral-web", create a "public" folder in it. Then create a "images" folder in the "public" folder. Lastly, copy any files you want from "node_modules/meshcentral/public/images" into your new "images" folder. You can then change the files as you like.

This is the nice way to customize the web site as the files in "meshcentral-web" will be served first and you can update MeshCentral while keeping your changes.

Let me know if that helps,
Ylian

**Comment by frankmcc** [comment]
I'm assuming I can only change the existing images, not add new?

**Comment by frankmcc** [comment]
This works great.  Thanks.
