### ISSUE TITLE
How would one drop a file to a agent machine

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1685]
Hi MeshCentral and OpenSource community,

Has anyone been able to get events logged dumped down to a machine running the agent? I want to capture events and do some offline or away analysis of the data.

Steps I used to make the listener is this, which does for the localhost 443 port, but I need this to get to a system within the groups remotely...

 node ./node_modules/meshcentral/meshctrl showevents url wss://localhost:443  --loginuser "testuserdata" --loginpass "Cip@Darpa123" > ~/events.log

This starts a listening agent that then spits out all the calls as I would expect, just on the server itself, where the data will grow exponentially very quickly, and I want to have control over dumping the data after running some machine learning scripts over it for parsing to BIs.

Thanks,
Some-Guru

**Comment by Ylianst** [comment]
On an unrelated note, Meshctrl.js has a new upload and download feature as of a few weeks ago. I may have forgotten to announce it. You could use this to automate getting and pushing files to remote agents. Could be used to fetch logs from remote agents.

```
node meshctrl.js upload --id 'deviceid' --file sample.txt --target c:\\
node meshctrl download --id 'deviceid' --file C:\\sample.txt --target c:\\temp
```

Now, when it comes to getting server events, I could add a --filter [xxx] and --savetofile [file] to the showevents operation of MeshCtrl.js.
