### ISSUE TITLE
Agent issue with Cert db?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#1686]
Hi
I was wondering if someone else has had this issue before, Currently a few agents not all having the issue on the db

![Screenshot_2020-08-06_10-05-08](https://user-images.githubusercontent.com/13953629/89548779-104d7280-d7cd-11ea-9b32-c2c12ede447c.png)

and currently using lets encrypt what is odd is that only a few handful computers 

Thank you

**Comment by krayon007** [comment]
Is the service still running? If it is the DB is locked by the service. if you want to run in console mode from the same location as the service, you will need to stop the service first

**Comment by killmasta93** [comment]
thanks for the reply, correct the service is running i tried uninstalling it and re installing it but no luck, the issue might be with the agent itself not the server?

**Comment by krayon007** [comment]
What exactly are you trying to do? The service needs to be stopped otherwise that file is always going to be locked.

**Comment by Ylianst** [comment]
As Bryan indicated, when the agent is running, it grabs exclusive lock on the meshagent.db. So the above behavior is expected.

**Comment by killmasta93** [comment]
so if i understood correctly stop the service, then uninstall it then reinstall it?

**Comment by Ylianst** [comment]
No sure what you are trying to do, but as soon as you stop the service, you can run the agent from the command line. Once you are done debugging, just start the service again. No need to uninstall/reinstall.

**Comment by killmasta93** [comment]
ok gotcha let me try and post back

**Comment by uldiseihenbergs** [comment]
are you running Admin Command prompt? i got the same error while back - it was because of non admin Command prompt..

**Comment by Ylianst** [comment]
You are right! It can also be caused be the agent not having access to the meshagent.db file.
