### ISSUE TITLE
Unlimited Link with connect only option

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1687]
We would like to be able to create a link that will only connect instead of installing. This would allow use it on a support page for one off customer support.  I realize this would only be for windows and possibly mac, but it would be helpful as a tech support tool.

**Comment by Ylianst** [comment]
Good request. I checked this feature in yesterday, it will be in the next published version of MeshCentral v0.6.3 when it comes out.

![MC2-InviteLinkInstallType](https://user-images.githubusercontent.com/1319013/89587015-92ea2800-d7f5-11ea-8980-bd8262fc8fba.png)
