### ISSUE TITLE
Linux Remote Agent not Connecting Similar to #1536

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1689]
This might have some similarity to #1536.

I've got an Ubuntu agent that will not show up in MC.  I also am running caddy reverse proxy.  

![agentconnect](https://user-images.githubusercontent.com/45638572/89653996-f62b9700-d895-11ea-92d1-06da8a73bfc1.JPG)

What's the best way to troubleshoot this?
Thanks
Shane

**Comment by vitko-bg** [comment]
I am not an expert, but looks like same problem as in my issue #1536.
I still did not managed to fix it....

**Comment by southeasterntech** [comment]
But yours is on the domain I think I read?  I deployed mine through the mesh script, I'm trying to install the new binary now, to see if it does anything different

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
