### ISSUE TITLE
SHIFT Key + Other Keys (Arrow or Del) don't work as expected.

### ISSUE THREAD

**Issue by davidblackmx** [Ylianst/MeshCentral#169]
Hello =)

SHIFT key isn't working correctly when is combined for example with the arrow keys or DEL key.
In Windows Explorer if I have selected a folder and I use shift + key down to select more folders, the selected folder change to the next one, and don't select 2 or more folders.

![image](https://user-images.githubusercontent.com/1387863/55675255-44352280-587d-11e9-91d2-e49a629a9d11.png)
If I use shift + mouse click works fine, fail when I only use the keyboard.

In windows explorer too, if I want to permanently delete a folder (SHIFT + DEL) the system show the normal delete dialog (Trash Bin).

Same problem in Excel for example, when I use shift + arrows to select multiple cells.

Regards...

**Comment by TitovLab** [comment]
Also ran into this.
The SHIFT key combination (for example, SHIFT + HOME) does not work in any programs, not only in Explorer. Starts to work if you enable Numlock.

**Comment by TitovLab** [comment]
Or sometimes you need to disable numlock. Such bug is always there and only if the agent is installed on Windows. There is no such error on Linux.

**Comment by Ylianst** [comment]
Will look into it. Pretty sure this is a bug.

**Comment by MailYouLater** [comment]
So, I am able reproduce this on MeshCentral<sup>2</sup> version 0.3.6-g installed via npm on NodeJS 10.15.3 while remote controlling either a Windows 7 or Windows 10 desktop (each from the other), using either the Windows 32 or 64 bit meshagent.exe (acquired via the invite link, though I doubt that matters).

Interestingly, right-clicking a file and pressing <kbd>Shift</kbd>+<kbd>D</kbd> correctly brings up the "Are you sure you want to permanently delete this file?" window, whereas selecting the file and pressing <kbd>Shift</kbd>+<kbd>Del</kbd> brings up the "Are you sure you want to move this file to the Recycle Bin?" window, exactly the same as pressing the <kbd>Del</kbd> key without <kbd>Shift</kbd>.

**Comment by lrq3000** [comment]
Same here with the version on meshcentral.com, a bit annoying since I use SHIFT+keys a lot (for remote text and files manipulation it's great to use SHIFT + arrow keys or ORIGIN or END to select lots of items).

**Comment by whalehub** [comment]
@Ylianst Any update on this?

**Comment by vitko-bg** [comment]
Looks like it is still  not resolved - running latest at the moment 0.4.7-z

**Comment by vitko-bg** [comment]
0.5.45 - still same issue ...

**Comment by OutbackMatt** [comment]
I reckon that I still get this on 0.7.28

**Comment by uldiseihenbergs** [comment]
huh, it's already 2021, and i still can't select more folders with Shift+Arrow in windows. any suggestion?

**Comment by uldiseihenbergs** [comment]
looks like it wont work, when NumLock is on.. when i turn it off, then it works..

**Comment by vitko-bg** [comment]
running on MC2 0.7.53 - the issue still persist

**Comment by LordBritish2000** [comment]
I made some additional experiende with this bug:
https://github.com/Ylianst/MeshAgent/issues/126

**Comment by chhh** [comment]
This bug is still there

**Comment by si458** [comment]
im closing this as its stale,
also ive just tried it here with latest version, and i dont have any issues? tried mac/windows/linux
