### ISSUE TITLE
Linux server does not generate login token at command line

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1690]
~/node_modules/meshcentral/bin$ node meshcentral --logintoken user//guest
~/node_modules/meshcentral/bin$ node meshcentral --logintokenkey

produces no output

config.json includes:
    "AllowFraming": true,
    "allowLoginToken": true,

I've read and re-read the documentation, am I missing something?

**Comment by Ylianst** [comment]
Ok, I need to take a look at this.

**Comment by Ylianst** [comment]
I get the same results, but that's because your running the command from the `~/node_modules/meshcentral/bin` folder. Go up one folder and try again, it will work.

```
~/node_modules/meshcentral$ node meshcentral --logintoken user//guest
~/node_modules/meshcentral$ node meshcentral --logintokenkey
```

Hope that helps,
Ylian

**Comment by frankmcc** [comment]
Bingo!  Thanks.
