### ISSUE TITLE
Does not recognize new agents

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#1691]
Hi, I have a problem. When I want to install a new computer, the list does not appear. I have to restart the meshcentral.service service on linux for it to recognize the new machine. Which may be? Thank you

**Comment by krayon007** [comment]
Which server version are you running? And to clarify, you are talking about restarting the server, not the agent? Is your server configured for local lan only? There was a previous bug that was fixed where the server was not responding to broadcast requests, which sounds like what you are seeing? Can you verify which server version you are using?

**Comment by desarrollocdb** [comment]
Server version: 0.5.95
I have to restart the server, it is a linux server with agent working in wan mode. Before I did not have this problem.

**Comment by Ylianst** [comment]
This is strange. I could understand if the server was in LAN mode, but I have no idea if the server is in WAN mode. Are you using a reverse proxy? Are you using NeDB or MongoDB? Is this happening on all devices? Is this a new server or something that started happening recently?

You saying that you install the agent, device does not show up. Then, you restart the server and the agent is present?

**Comment by desarrollocdb** [comment]
I use mongodb, it is a recent problem. Sometimes I have to restart the server so that the system detects the new installed agent in the groups list. Use apache reverse proxy.

Once I restart the server, everything returns to normal but after a while it fails again.

**Comment by Ylianst** [comment]
I would not be surprised if this was a reverse proxy issue. One thing you can do is go in the "My Server" / "Trace" tab and enable "Web Server Requests" tracing. You should see a request to "/agent.ashx" each time an agent connects.

![image](https://user-images.githubusercontent.com/1319013/89693110-5d5f4080-d8c2-11ea-9368-be34fe3fbb08.png)

I am going to guess your not going to see that when it fails. Also, if you can go in the Apache reverse proxy logs, I am guessing there will be a really good hint as to what is going on.

**Comment by Ylianst** [comment]
Also, when the server fails, go in "My Server" / "Console" tab and type the "agentstats" command and report back. It should look like this:

![image](https://user-images.githubusercontent.com/1319013/89693262-e0809680-d8c2-11ea-9233-efde82acb2ed.png)

**Comment by desarrollocdb** [comment]
> agentstats

createMeshAgentCount: 436
agentClose: 379
agentBinaryUpdate: 1
coreIsStableCount: 418
verifiedAgentConnectionCount: 424
clearingCoreCount: 0
updatingCoreCount: 2
recoveryCoreIsStableCount: 0
meshDoesNotExistCount: 0
invalidPkcsSignatureCount: 0
invalidRsaSignatureCount: 0
invalidJsonCount: 0
unknownAgentActionCount: 0
agentBadWebCertHashCount: 0
agentBadSignature1Count: 0
agentBadSignature2Count: 0
agentMaxSessionHoldCount: 0
invalidDomainMeshCount: 0
invalidMeshTypeCount: 0
invalidDomainMesh2Count: 0
invalidMeshType2Count: 0
duplicateAgentCount: 110
maxDomainDevicesReached: 0

**Comment by desarrollocdb** [comment]
I have to clarify that meshcentral gets to know new agents again if I restart the meshcentral.service service. I don't have to restart apache or another service.

**Comment by desarrollocdb** [comment]
@Ylianst This is what happens when a new agent is installed and is not recognized on the server.

![image](https://user-images.githubusercontent.com/26174637/91231528-072c3300-e6f3-11ea-8e5b-e8b13ac50554.png)

**Comment by krayon007** [comment]
That's not an error, that's just informational, saying it is generating a certificate, which it will do on first start. What does the agent say, if you stop the service, and run the agent in console mode? 

From an elevated command prompt, you can stop the service by typeing:
wmic service "Mesh Agent" call stopservice

Then if you navigate to the mesh folder (usually C:\\Program Files\\Mesh Agent)
and type: meshagent run
what does it say on the screen when it is connecting?

**Comment by desarrollocdb** [comment]
Thanks @krayon007 , I have done the process and I get this in the log:

[2020-08-26 02:48:40 PM] Certificate loaded from DB was not signed by our root cert in the Cert Store

But the team does not appear in the group


![image](https://user-images.githubusercontent.com/26174637/91350169-ec69c500-e7ab-11ea-8563-456cc9a4051a.png)

In the server trace, it shows me this:

2:53:58 p. m. - AGENT: Verified agent connection to hgKowszJNyorX@lFVY9DyKZeJV6wS7PYGHTq1kPIIlgxBxyjaxaK6b2QOOI$7Es3 (IP:45286).

2:55:33 p. m. - AGENT: Agent disconnect hgKowszJNyorX@lFVY9DyKZeJV6wS7PYGHTq1kPIIlgxBxyjaxaK6b2QOOI$7Es3 (IP::45286) id=Unknown


After restarting the meshcentral.service, this is what the trace shows:

2:57:31 p. m. - AGENT: Updating core windows-amt
2:57:29 p. m. - AGENT: Verified agent connection to hgKowszJNyorX@lFVY9DyKZeJV6wS7PYGHTq1kPIIlgxBxyjaxaK6b2QOOI$7Es3 (IP:46072).
2:57:29 p. m. - AGENT: New agent at IP:46072

**Comment by krayon007** [comment]
You need to type: meshagent run

You omitted the word run, so you didn't actually run the agent in console mode.

**Comment by desarrollocdb** [comment]
@krayon007 

![image](https://user-images.githubusercontent.com/26174637/91363481-542b0a80-e7c2-11ea-8fd6-61432708c1de.png)

**Comment by desarrollocdb** [comment]
@Ylianst 

Any ideas on this error?
![image](https://user-images.githubusercontent.com/26174637/93143393-7ae7ad00-f6ad-11ea-9e76-8a98ce92e1e6.png)


I have to restart the meshcentral service on my server so that it can accept new connections or have the old ones reconnect.

**Comment by FrankSanabria** [comment]
> @Ylianst
> 
> Any ideas on this error?
> ![image](https://user-images.githubusercontent.com/26174637/93143393-7ae7ad00-f6ad-11ea-9e76-8a98ce92e1e6.png)
> 
> I have to restart the meshcentral service on my server so that it can accept new connections or have the old ones reconnect.

Same Error Here... We need restart MC for connect with new agents.

Use Debian 10, and LEtsencrypt Certificate, Direct Conection WIth Out Proxy

**Comment by desarrollocdb** [comment]
Same configuration but with proxy, in May I did not have this problem.

**Comment by krayon007** [comment]
I'm not seeing any error messages in those traces.. (The thing about the certificate not being found is normal when the agent is first run...)

Is there any errors showing up on the server side?

**Comment by FrankSanabria** [comment]
**Log MeshAgent:**

[2020-09-17 03:27:16 PM] Info: No certificate was found in db

**Log Server:**
https://pasteboard.co/Jry5JaP.png


SO: Debian Versión 10.5
Proxy: No
NAT: No

**Comment by desarrollocdb** [comment]
@Ylianst any indication to solve this?

**Comment by desarrollocdb** [comment]
I still have the problem. For now, it only remains to restart and wait.
