### ISSUE TITLE
Feature Request: Add Last Seen Date Column to List View

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#1693]
Please add Last Seen Date Column to List View .This would be fantastic way to easily sort out what computers have been offline for awhile especially when you have many agents. Currently I have to click on each agent to see the last seen date. Thank you!! =] and Excellent work!!!

**Comment by johnnyq** [comment]
Even OS Would be helpful in the list view and LAN IP and rename Address column to WAN IP and add MAC Address and add action column with the following actions icon for remote desktop file manger terminal, details. Just some ideas throwing them out there. Thanks again

**Comment by Ylianst** [comment]
What I really need to do is allow customization of the columns, there are requests for all sorts of information on that view and so, I need to have people sure setup the columns the way they want.

**Comment by vitko-bg** [comment]
+1 for the above request :)

**Comment by Mfinadmin** [comment]
> What I really need to do is allow customization of the columns, there are requests for all sorts of information on that view and so, I need to have people sure setup the columns the way they want.

@Ylianst - pls do if possible

**Comment by vitko-bg** [comment]
@Ylianst Please please add the column "Last seen". Recently you added IP address to columns #2580 and a column with RDP/SSH links, but this issue is open from long time. I think lots of people will appreciate the option to have this column in detail view.
Big THANKS in advance :)

**Comment by VINISHVV** [comment]
> What I really need to do is allow customization of the columns, there are requests for all sorts of information on that view and so, I need to have people sure setup the columns the way they want.

Please allow customization based on all available details...

**Comment by si458** [comment]
this already exists, click the COG in the columns view and select 'Last Seen'
