### ISSUE TITLE
Bulk adding AMT capable machines with password

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1694]
Hi Ylian,

I am looking to bulk load systems into MeshCentral server with AMT and both default and unique passwords.

Example of a .CSV could be formatted like this;
PC Name, Amt Pass, Proxy, Static IP, Key File
Maker-db, Arty$123, http://chain.mydomain, 101.101.101.101
Server-001, Fishy%5*, no, 86.75.30.9

Also making a manifest file that the MeshAgent could look into and find the assigned connection details like Proxy or IP Static/DHCP.

Can you make this bulk add option?

Thank you, 
SomeGuru

**Comment by Ylianst** [comment]
Yes, I think this is a great suggestion.

**Comment by mmhparvez716** [comment]
@Ylianst You suggest me to put in a request with similar functionality and sample file. I will follow this post.
Thanks @SomeGuru .

**Comment by mmhparvez716** [comment]
Any update on this enhancement? Thank you as always.
