### ISSUE TITLE
Small visual bug on multi monitor with Firefox

### ISSUE THREAD

**Issue by turin331** [Ylianst/MeshCentral#1699]
When connecting to Linux desktop a good deal of the screen appears black and requires some graphical movement to for the desktop elements to appear. 

Example: https://imgur.com/Zgy5a0V 

This seems to only happen in Firefox (version 79) - On chromium there is no such issue. That is only on a linux remote machine. No such issue on other OSs or on a Linux remote machine with a single monitor. 

MeshCetral: Version 0.6.4  
Remote Machine: Ubuntu Server 18.04 with Mate Desktop

**Comment by si458** [comment]
this no longer happens in testing, closing as old and stale
