### ISSUE TITLE
Show 'available' memory instead of 'free' on Linux server

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#1700]
Hi,
The "Free" memory info in "My Server" section is a good idea but "available" memory will be more pertinent.

[Free/Available memory](https://www.linuxatemyram.com/)

Is it possible to change the check ?

Best 
D.

**Comment by Ylianst** [comment]
Your right. Available memory is a much better number. Just fixed it in MeshCentral v0.6.10. I also added a decimal to the memory amount.

![image](https://user-images.githubusercontent.com/1319013/90342256-82873980-dfbb-11ea-9b35-93d179d70adb.png)

**Comment by Tomatoschewps** [comment]
Yeah :)
Perfect for me !

By the way it's amazing how the server consume so little memory and CPU, great job on this point too ;)

**Comment by Ylianst** [comment]
Thanks. You right, it's pretty efficient. I have run MeshCentral on a Raspberry Pi 4 and it works great.

**Comment by Tomatoschewps** [comment]
By the way, do you have feedback on consumption based on the number of agents ?

Here we have 250 agents/95 connected today and for now we use 670Mo of RAM.
(With MongoDB)
