### ISSUE TITLE
2FA not working on Mobile - Android 9 &  10 OSes

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1702]
Hi Ylian and team,

Found that 2FA is not working with mobile devices using alternate devices that are not ever logged on the MeshCentral.

Both SMS and Email methods are bypassed.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Are you sure you did not opt to remember the device for 30 days? If you do opt to remember the device, 2FA will be skipped on that device for the duration. Reset your device cache and try again. If you still see the problem, let me know.

**Comment by SomeGuru** [comment]
I will try on another device this evening that I have never signed in with, and see if it has the same results... I used a friends iPhone and it didn't ask on that either... On desktop it asks unless like you stated the check is set to not ask... More than likely a configuration issue on my devices due to a corporation IT policy to the regards on the these two devices.

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
Did a dump and removed IT policy from phone and it resolved the issue... Looks to have been based on a saved profile by the IT folks.
