### ISSUE TITLE
Password time based expiry

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1703]
Hi Ylian,

Can we add a expiry duration to the passwords field?
Example below:

```
 "PasswordRequirements": {
   "min": 48,
   "max": 156,
   "upper": 1,
   "lower": 1,
   "numeric": 1,
   "nonalpha": 1,
   "expire": 1,      _1: yes 0:no
   "expire duration": 90 _duration in days
```

If this exists then I must be missing it in the documents.

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
Yes, use the `reset` value to set the number of days, for example:

      "passwordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "reset": 90,                    <-------------
        "force2factor": true,
        "skip2factor": "127.0.0.1,192.168.2.0/24"
      },

I will add the description to the schema and yes, it need to be better documented.

**Comment by SomeGuru** [comment]
Added and will await a password refresh... One question on this however, is how many new passwords required before users could potentially reuse an old password. Also is there a force password change on x amount of failed logins after say 3 temporary bans?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
There is currently no old password memory or force change after x failed logins. If you need these, let know. For the password reset, you can test by moving the server clock forward.

**Comment by SomeGuru** [comment]
Hi Ylian,

I think this would come in handy just in case if there was a breach on a  server, it could be one of the pinch points that could prevent loss. 

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v0.6.10.

![image](https://user-images.githubusercontent.com/1319013/90341171-2ec42280-dfb2-11ea-9af5-20eec268c6bf.png)

**Comment by Ylianst** [comment]
MeshCentral v0.6.10 is published. I just added another feature that will make it in v0.6.11. You can now ban the top 10000 most commonly used passwords from being used for MeshCentral accounts. Uses the the [WildLeep](https://www.npmjs.com/package/wildleek) module. No network checking is done. The [commonly used passwords list is here](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-10000.txt).

![image](https://user-images.githubusercontent.com/1319013/90343625-393ce700-dfc7-11ea-8ab9-3c40cd5520b8.png)

**Comment by SomeGuru** [comment]
Rolling out in next deployment on mainline, however it looks to work of pre-prod launch server, so will attempt with the larger one on next roll and reopen ticket if issue is seen... Closing for now...

Thank you,
SomeGuru
