### ISSUE TITLE
MeshAgent on Ubuntu Core / Within a Snap

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#1704]
Recently we received some "IoT" boxes in for site deployment that run Ubuntu 16 Core. I would love to put a MeshAgent on them, but so far haven't met with success as by default Core doesn't even come with wget. I played around a little with the "classic" snap but couldn't get the MeshAgent service started due to a PolicyKit1 error, despite PolicyKit being installed. I would try to create my own snap, but that's a bit beyond my skills.

I don't suppose there is a way to get a MeshAgent running on them?

**Comment by krayon007** [comment]
I'll setup a Ubuntu Core system/VM and see what I can do...

**Comment by MatinatorX** [comment]
Thank you, definitely let me know if I can help in any way! I'm going to keep poking at it myself to see if I can make a bit more progress.

**Comment by krayon007** [comment]
I did find this tidbit about classic:

> Daemons are not started in the classic dimension and all running background binaries will exit when the classic dimension is closed.

So I'm not sure how useful it would be, unless the agent is actually deployed as a snap... But looking at the restrictions on the snap sandbox, it also looks like it is very confining.... It looks like it may have to be deployed as a snap using --devmode classic, which I'm not sure is something feasible, as it says it cannot be installed into a stable release version of Ubuntu Core, if I read the docs correctly...

**Comment by MatinatorX** [comment]
In my testing, I was able to install the "classic" snap using the --devmode classic parameter, so I think it's doable on any Ubuntu Core system. Rather, the docs seem to suggest that if you want to provide the snap to users through the standard snap repository, they would have to specify a non-stable channel such as candidate, beta, or edge. For example:

`snap install meshagent --channel=edge` as opposed to the normal `snap install meshagent`

This would allow the snap to be hosted on and installed from the standard snap repository used by Ubuntu Core. I'm definitely no expert though, so I could be wrong, but that seems to be the case from what I've learned trying to get it to work myself.

**Comment by MatinatorX** [comment]
Small update, I did get the meshagent running within the classic snap thanks to @kevhawk2914 helping to bypass systemd. Just ran:

`sudo /usr/local/mesh/meshagent &`

...and it started right up and popped up on MeshCentral.

Tried adding that command to /etc/rc.local however, and while the changes persisted on reboot it did not execute the agent and I had to run the command again. Next step is to look into making a snap...

**Comment by krayon007** [comment]
Yeah, I had gotten it to run as a console app earlier as well, and was looking into seeing if I could figure out how to actually get it to run as a proper service...

**Comment by MatinatorX** [comment]
From what I understand, it's going to require building an actual snap for it thanks to the PolicyKit issues. I've heard there's a way to use the classic snap to build your own proper snap, so I'm going to attempt to do so as soon as I get some free time this week.

**Comment by kevhawk2914** [comment]
It's less a PolicyKit issue more that the classic snap has no init or systemd support besides basic functions it's a very basic container to get you started building snaps. You won't be able to get a persistent service running within classic.

**Comment by MatinatorX** [comment]
I have made some progress making a snap for our MeshAgent, however I've run into an issue where the MeshAgent can't start due to being unable to create/open the meshagent.db file.

When running in the classic snap, everything works properly when running the binary at /usr/local/mesh/meshagent. On first run, the agent creates the necessary meshagent.db file (and meshagent.log) in /usr/local/mesh and connects to MeshCentral.

With this working, I created a snap containing the meshagent binary and meshagent.msh and set it up as a daemon. On system boot, the daemon attempts to start, however the snap logs indicate it's unable to open the database. I tried with confinement set to devmode and with the snap configured as both app and base, but saw the same issue. It seems the agent cannot create meshagent.db, but even when I added a database file created in the classic snap, it still couldn't find it.

I'm curious how the MeshAgent looks for the database file. Is it a hardcoded path (/usr/local/mesh or /usr/mesh) or does it just expect it to be in the same folder as the binary? Snaps do some strange things with paths since each one runs in a VM, and the "working" directory for the files in the snap actually start in /snap/[snapname]/[revision]. I tried playing around with snap layouts to set up binds/symlinks to /usr/local/mesh, but ran into problems with the binary not being found by the snap service.

I'm going to keep poking at it, but I'm no expert so if anyone has any ideas let me know! For reference here is my current snapcraft.yaml:
`name: testsnapagent
version: '0.1'
summary: Test Commander Mesh Agent Snap
description: |
  Adds a MeshAgent on systems running Ubuntu Core to the MeshCentral portal for remote access.

confinement: devmode
grade: devel

apps:
  testsnapagent-service:
    command: meshagent
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network-bind
      - network

parts:
  testsnapagent:
    source: /usr/local/mesh/
    plugin: dump

**Comment by edlins** [comment]
This is very important to me as I'm evaluating `Ubuntu Core` as the OS for a fleet of IoT devices.  At some point I may be able to assist but I'm not there yet with `snap` development experience.

**Comment by krayon007** [comment]
> With this working, I created a snap containing the meshagent binary and meshagent.msh and set it up as a daemon. On system boot, the daemon attempts to start, however the snap logs indicate it's unable to open the database. I tried with confinement set to devmode and with the snap configured as both app and base, but saw the same issue. It seems the agent cannot create meshagent.db, but even when I added a database file created in the classic snap, it still couldn't find it.

On linux, I use readlink() on /proc/self/exe to get the the current executable path. Then I add '.db' to it.

If you still have issues, you can also run the agent with:
> --readonly=1

which will open the db in memory only... This has a side-effect that it will need to recreate the cert every time it runs, making it so it generates a new node id, but if you were just testing it to see if it works...

**Comment by MatinatorX** [comment]
That worked great! No more database errors in the snap log and everything working as expected, even after a full reboot of the system. Of course it showed up as a new device as mentioned, but it's good to know it might be something simple.

Problem is, I'm not sure where to go from here. I searched everywhere for the meshagent.db file with every attempt I've made. The full list of snap-specific environment variables is here:
[https://snapcraft.io/docs/environment-variables](https://snapcraft.io/docs/environment-variables)

I never found the database file at any of those paths. I've even tried adding the following to snapcraft.yaml to map the snap working directory to the normal install path:
```passthrough:
  layout:
    /usr/local/mesh:
      bind: $SNAP_DATA```

If you're checking the executable path I imagine this wouldn't help at all though. The last bits of info I have is the systemd mount and service files created when installing the snap, which (I believe) shows that the working directory for the service should be $SNAP_DATA:
```
[Unit]
Description=Mount unit for testsnapagent, revision x1
Before=snapd.service

[Mount]
What=/var/lib/snapd/snaps/testsnapagent_x1.snap
Where=/snap/testsnapagent/x1
Type=squashfs
Options=nodev,ro,x-gdu.hide
LazyUnmount=yes

[Install]
WantedBy=multi-user.target
```
```
[Unit]
# Auto-generated, DO NOT EDIT
Description=Service for snap application testsnapagent.testsnapagent-service
Requires=snap-testsnapagent-x1.mount
Wants=network.target
After=snap-testsnapagent-x1.mount network.target snapd.apparmor.service
X-Snappy=yes

[Service]
EnvironmentFile=-/etc/environment
ExecStart=/usr/bin/snap run testsnapagent.testsnapagent-service
SyslogIdentifier=testsnapagent.testsnapagent-service
Restart=no
WorkingDirectory=/var/snap/testsnapagent/x1
TimeoutStopSec=30
Type=simple

[Install]
WantedBy=multi-user.target
```
In my testing I couldn't figure out how to move and files there from the snapcraft.yaml file. The organize: parameter seems to just ignore me when I specified $SNAP_DATA as a file location, and instead created a folder called $SNAP_DATA inside $SNAP. I'll keep poking at it though, learning a lot!

**Comment by MatinatorX** [comment]
So, from what I can tell, the issue here is that the binary is trying to stick meshagent.db next to the binary and not putting it in the working directory where it should actually go as per how snaps normally work. Is there a way to tell the binary to put/look for the database file in $SNAP_DATA?

**Comment by krayon007** [comment]
If you run the agent, with the readonly mode like I mentioned, then go to the console tab, and run the following two commands:
> setdebug *
eval console.log(process.execPath)

The first command just redirects stdout to the console tab, the second command will show where it thinks the binary is located, hence, where it thinks the db should be.

**Comment by kevhawk2914** [comment]
Biggest issue here is there isn't a startup argument to tell the meshagent app to look for the database or config elsewhere.

That'd solve this almost immediately as the binary location is readonly while the working directory is separate and readwrite in snaps.

**Comment by MatinatorX** [comment]
I get
```/snap/testsnapagent/23/meshagent```
...which is a read-only directory. That confirms that.

**Comment by krayon007** [comment]
if you run:

> eval console.log(process.cwd())

does it show the working directory as what you expect it to be?  If so, i can add the functionality you mentioned... I'll have to modify the code to support that tho, but it should be fairly simple.

**Comment by kevhawk2914** [comment]
Yeah, snaps copy the binary into a read only directory and attempt to execute it from there while also specifying a working directory that meshagent does not respect.

As such a startup argument would need to be added or at least the working directory respected for config and database files.

**Comment by krayon007** [comment]
I'll implement it as a startup switch, just so we don't unintentionally break things, as the reason the .db, .proxy, and .tag files use the binary path location instead of the working directory, was for consistency, because when we first released the agent, setting the working folder wasn't consistent across platforms, especially when some people used a batch script to launch/setup the agent, and didnt' always set the working folder.

**Comment by kevhawk2914** [comment]
Sounds good!

**Comment by MatinatorX** [comment]
> if you run:
> 
> > eval console.log(process.cwd())
> 
> does it show the working directory as what you expect it to be? If so, i can add the functionality you mentioned... I'll have to modify the code to support that tho, but it should be fairly simple.

It does indeed! `/var/snap/testsnapagent/23/`

That directory is the read/write $SNAP_DATA directory. If you're able to make it so that we can set the working directory for the database, log and config files, it would be fully funtional.

In the meantime I'll work on expanding the snap capabilities to support passing the server info and generating the meshagent.msh itself like the normal install script does, so it can work with any MeshCentral server. Then the snap could be made public. It'd require --devmode and --beta to install, but it would work.

If that goes well, I've got the snappy-debug data which shows which plugs needed when confined. Might even be possible to get a strict confinement snap working, which wouldn't need --devmode or --beta.

**Comment by krayon007** [comment]
On a side note, since the agent binary path is readonly, self update will not work correctly. How does one normally update snaps?

**Comment by MatinatorX** [comment]
Snaps are updated automatically. The Ubuntu Core system runs a check against the snapcraft store 4 times per day to find new versions and install them if available. You can also run `sudo snap refresh`.

The alternative is to try and move the binary into $SNAP_DATA and run it from there, but I haven't found a good way to do that yet. It will definitely require launching a script with the snap instead of launching the binary directly. That's one of the things I'll be messing around with tomorrow.

**Comment by krayon007** [comment]
The only issue with this, is that normally the agent should be "owned" by the server, not the app store, since there are dependencies between the server version and the agent version. One alternative if the snap installer can't write the agent binary into a RW partition, is that a different command line switch could be created such that when the agent is started, it will respawn from a different location, or something like that...  @Ylianst?

**Comment by krayon007** [comment]
Something like it can check the working directory (if it's different then the binary path), and if the binary is not there, copy itself there.... Then respawn from the working folder.

**Comment by MatinatorX** [comment]
I think I can modify the normal install script to grab the binary off the server and put it in $SNAP_DATA right off the bat, or launch it if it finds that it already exists there. Wget is not present in the core files, but I should be able to bundle it in with the snap to get around that. Anything in $SNAP_DATA persists through reboots/snap refreshes and is writable, which should enable the agent to still change out the core file. I'll take a crack at it tonight when I get home.

**Comment by krayon007** [comment]
I updated the agent repo, so now you can specify:
`--configUsesCWD=1`

and it will cause all the config/log files to use the working path instead of the binary path

**Comment by MatinatorX** [comment]
Thanks! I haven't had the time to revisit this yet but I'll update once I've got a more flexible snap built.

**Comment by edlins** [comment]
@MatinatorX Can you share your latest `snapcraft.yaml` file here?

**Comment by MatinatorX** [comment]
@edlins Sure thing. I had given up on this for a while but just came back to it today and got it working. I haven't made a universal snap yet, but here's how you can build one for a specific device group of yours:

1) Download the meshagent Linux binary installer for your desired device group and copy it to a folder in your home directory on your Ubuntu Core box. For example, /home/admin/meshsource

2) In this same directory, create a script ("meshagent.sh" in this example) that will copy our binary if it's not found, then run it:
`#!/bin/sh
# Mesh Agent Service Script

if [ ! -f "$SNAP_DATA/meshagent" ]; then
    cp $SNAP/meshagent $SNAP_DATA/meshagent
fi

$SNAP_DATA/meshagent -connect`

3) For your snapcraft.yaml:
`name: meshagent
version: '0.1'
summary: Mesh Agent Snap
description: Mesh agent for remote access.
confinement: devmode

apps:
  meshagent-service:
    command: meshagent.sh
    daemon: simple
    restart-condition: always
    plugs:
      - home
      - network-bind
      - network
      - dcdbas-control
      - hardware-observe
      - hardware-random-observe
      - location-observe
      - network-manager-observe
      - network-observe
      - network-setup-observe
      - network-status
      - physical-memory-observe
      - shutdown
      - ssh-public-keys
      - system-backup
      - system-observe
      - upower-observe

parts:
  meshagent:
    source: /home/admin/meshsource/
    plugin: dump`
    
To install the newly-created snap, simply run `sudo snap install meshagent_0.1_amd64.snap --devmode --dangerous`

It's quite likely all of the plugs above are not needed but I haven't had the time to go through and see which ones aren't used. Now that's I've gotten this far though, hopefully I'll be able to make a universal public snap soon.

**Comment by MatinatorX** [comment]
Finished a public snap: https://snapcraft.io/meshagent-ubuntucore

Source is here: https://github.com/MatinatorX/meshagent-ubuntucore

@Ylianst Let me know if it's alright to keep that snap up or if you'd prefer to host it yourself.

I would have liked to put the snap in strict confinement and release to stable, but the number of permissions the MeshAgent needs was causing AppArmor to co crazy. I can't see Canonical approving auto-connection of all the required interfaces, so it's probably better to require devmode and beta arguments instead of the user manually configuring 20 or so plugs.

The installation script is mostly just a pared back version of the normal meshinstall.sh, with a bash function replacing wget and curl, since Ubuntu Core doesn't ship with them.

Hopefully this helps someone!

**Comment by MatinatorX** [comment]
Closing this since work on a public snap is completed.
