### ISSUE TITLE
Remote control of Active RDP session results 100% CPU

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#1706]
Hi there,

There seems to be an issue with connecting to a MeshAgent RDP session where CPU shoots to 100% after connecting, and after disconnecting, MeshAgent.exe continues to burn CPU.

OS is Windows 10 1903, up to date with patches.  Meshcentral running 0.6.6

Issue doesn't appear to happen when connecting to the console of the Win10 desktop.

There is a hint that this issue has been seen before and a possible fix released:
https://github.com/Ylianst/MeshCentral/issues/1628#issuecomment-665413033

But I seem to still be able to reproduce it.  Happy to perform further tests as needed :)  Thanks!

![image](https://user-images.githubusercontent.com/202961/90138157-ba249480-ddb5-11ea-878e-78920ac86cc2.png)

![image](https://user-images.githubusercontent.com/202961/90138263-e809d900-ddb5-11ea-96f9-0656aec6b838.png)

![image](https://user-images.githubusercontent.com/202961/90139706-dde8da00-ddb7-11ea-8b48-41f45eb399b4.png)

![image](https://user-images.githubusercontent.com/202961/90139755-ef31e680-ddb7-11ea-9b32-792d0bb2af10.png)

- Disconnect
- MeshAgent.exe continues to consume 100% CPU while disconnected

![image](https://user-images.githubusercontent.com/202961/90139921-286a5680-ddb8-11ea-9c92-491a8e5028f6.png)

![image](https://user-images.githubusercontent.com/202961/90139983-3c15bd00-ddb8-11ea-84ae-8a4bc054cabc.png)

Stopping the agent immediately stops the CPU burn:

![image](https://user-images.githubusercontent.com/202961/90140051-58195e80-ddb8-11ea-972f-3cf6543a2e4b.png)

**Comment by krayon007** [comment]
So far I've tested Windows 10 Enterprise 1803 and 2004, and have been unable to reproduce this issue. I'll see if I can find/build a 1903 system.

**Comment by si458** [comment]
meshagent doesnt use the GPU for encoding, it uses the CPU for encoding
given the screenshots you only have a single core this is expected,
you should give the VM like 2 or 4 cores at a minimum
