### ISSUE TITLE
Issue with Spanish Web-Browsers  (Blank after login MC)

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#1710]
On Spanish language web browsers (chrome, edge, opera) mesh central goes blank after put your credentials on it. The fast solution is to change language to English.  But looking in detail on the issue I found that probably the issue is here:

x += '<br /><div>' + "Ejecute MeshCentral Router y haga clic en \ "instalar \" para que se pueda iniciar desde el navegador." + '</div>';

look on "instalar" previous backslash, that stops the site to continue running.  Hope this helps to solve.

**Comment by MC-PM** [comment]
Found that this only happens on devices where MC will be logged first time (not sure if this issue is related to recent updates).  If you have used MC to login the first time in the past, and change to spanish language, it will work fine.

**Comment by Ylianst** [comment]
Oh!!! Working on it now.

**Comment by Ylianst** [comment]
I see the same problem, working on an immediate fix for this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.8 with a fix for this. You can add "&lang=en" or "?lang=en" to the URL to make the web page English and update your server. Let me know if it works.

**Comment by MC-PM** [comment]
it works great... thanks!
