### ISSUE TITLE
How to graceful/gracefully shutdown a Ubuntu machine?

### ISSUE THREAD

**Issue by rgl** [Ylianst/MeshCentral#1712]
How to graceful/gracefully shutdown a Ubuntu machine?

Do I need to install some agent (LMS?) in the machine before I can gracefully shutdown/restart it? If so, can you please point me in the right direction?

FYI, `CIM_AssociatedPowerManagementService` does not return any of the "graceful" options. It just returns these:

```json
{
 "AvailableRequestedPowerStates": [
  10,
  8,
  5,
  11
 ],
 "PowerState": 2,
 "RequestedPowerState": 2,
...
```

Which corresponds to:

```
powerState: #2 (On)
availablePowerStates: [
  '#10 (Master Bus Reset)',
  '#8 (Off - Soft)',
  '#5 (Power Cycle (Off - Soft))',
  '#11 (Diagnostic Interrupt (NMI))'
]
```

**Comment by Ylianst** [comment]
So, your question completely fails to mention that your trying to perform the operation thru Intel AMT and does not mention what tool your using to make the operation. Yes, you need Intel LMS installed to do graceful power operations thru Intel AMT.

**Comment by rgl** [comment]
Sorry, I was using MeshCentral/MeshCommander. They show a combobox with the power options, but not all of them actually work (like Graceful Shutdown), they just silently get executed and no warning/error is displayed, which leaves the user wondering of what happened. In this case, nothing happened in the machine.

After looking into the code, the RequestPowerStateChange call actually returns a response body with an error, but the UI never shows that to the user. Maybe it should?

Do you known what package contains the Intel LMS in Ubuntu? Can it be MeshCommander MicroLMS?

**Comment by jsastriawan** [comment]
Try to install lms from snap. E.g. snap install lms. Or if you want to build Debian package, find the source at github.com/intel/lms. That LMS version supports OS assisted power control.

**Comment by rgl** [comment]
Thank you! 

Now that the lms service is running, the MeshCommander "Soft-off" power action works as expected :-)

BTW, I'm playing with this at https://github.com/intel/lms/pull/3.

**Comment by jsastriawan** [comment]
Awesome, I saw your PR to lms project and Tomas has replied too.

**Comment by rgl** [comment]
I forgot to add that I can now see these power action being returned by CIM_AssociatedPowerManagementService.AvailableRequestedPowerStates:

```
powerState: #2 (On)
availablePowerStates: [
  '#10 (Master Bus Reset)',
  '#8 (Off - Soft)',
  '#5 (Power Cycle (Off - Soft))',
  '#11 (Diagnostic Interrupt (NMI))',
  '#4 (Sleep - Deep)',
  '#7 (Hibernate (Off - Soft))',
  '#14 (Master Bus Reset Graceful)',
  '#12 (Off - Soft Graceful)'
]
```
