### ISSUE TITLE
Added DBEncryption - lost a group

### ISSUE THREAD

**Issue by robclay** [Ylianst/MeshCentral#1714]
In config.json, I added 
"DbRecordsEncryptKey": "REDACTED Really Secret Password"
and then did the 
`node node_modules/meshcentral --recordencryptionrecode`
command.  It reported `Re-encoded 6 record(s).`

I then updated the server version from 0.6.9 to 0.6.10.

I noticed that I lost a group!  I had 4, but now only see 3 and lost the 2 computers within the lost group.  So I readded the group, and am reinstalling the agents... But something caught my eye:  On the server page, it is showing 5 groups.  Makes me think that it knows where the missing one is somehow?

**Comment by Ylianst** [comment]
I will finish up what I am working on now and take a look at this. I will test DbRecordsEncryptKey a bunch.

Also, a fun trick, in the domain section of config.json, you can add this:

```
"orphanAgentUser": "admin"
```

When a device attempts to connect to an unknown device group, a new device group will be created can the specified user will be given access to it. This is a nice trick if you need to recover from lost data. I added this option to the `meshcentral-config-schema.json` file for the next version of MeshCentral.

**Comment by robclay** [comment]
I added that line and restarted.  It didn't show anything for me at first...  But...  after following the database reset (https://github.com/Ylianst/MeshCentral/issues/1713) the computer was displayed in my 'reset' install.

**Comment by Ylianst** [comment]
I just tested and fixed the `--recordencryptionrecode` option. It could cause NeDB database to corrupt. It's going to be fixed in MeshCentral v0.6.23 when it's next published. The problem was not the encryption, but the way the database was re-encoded.
