### ISSUE TITLE
My Account page maps to last group chosen of My Devices

### ISSUE THREAD

**Issue by robclay** [Ylianst/MeshCentral#1715]
Odd behavior, Server 0.6.10

When I am on My Devices page, I click on the group "I made this to test 4." (See Step 1)
![Step 1](https://user-images.githubusercontent.com/19339985/90355471-1126a580-e012-11ea-9164-b91094f4dd50.png)

And it opens just fine where I can edit the group.
If I then go BACK to My Devices.    (See Step 2)
![Step 2](https://user-images.githubusercontent.com/19339985/90355473-11bf3c00-e012-11ea-8c4d-f50aa052633b.png)

and change to My Account menu, regardless of what group I click, (See Step 3),
![Step 3](https://user-images.githubusercontent.com/19339985/90355474-11bf3c00-e012-11ea-8561-8f7671baa994.png)

the group that will be displayed is the one from Step 1.  (See Step 4)
![Step 4](https://user-images.githubusercontent.com/19339985/90355475-1257d280-e012-11ea-961f-fb553a1c9fd0.png)

**Comment by robclay** [comment]
For debugging purposes, I dropped the database and started over.  Same behavior.

**Comment by Ylianst** [comment]
Oh dear!!! I just sorted that list a few versions back and missed that the mouse selection was not right. Just published MeshCentral v0.6.11 with a fix for this. Let me know if it fixes it.

**Comment by robclay** [comment]
Fixed!
