### ISSUE TITLE
Server administrator view of group creators

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1716]
Hi MeshCentral team,

Any chance that an option could be made for viewing the creators of groups? Reason I ask this is because all my group admins add my team to their groups, but then we don't remember who created it, and we have to contact a few different people per group. We are approaching 150 unique groups... figure an option on gui to expose in the group title the username who created it... example: Yacht_Octopus_Comms (SomeGuru)
Yacht_ICON 280_Telemetry (VData)
Yacht_YlianSt_Mesh (Ylianst)

This would help in fixing issues quickly...

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
Working on this one now.

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v0.6.12 when it's next published. Let me know if that works for you.

![MC2-DeviceGroupCreation](https://user-images.githubusercontent.com/1319013/90436975-6bf9e480-e086-11ea-9e1a-14f51d4c07e2.png)

**Comment by frankmcc** [comment]
Does something need to be done to the config or style.css (I've customized mine) for this to work?  I've created new groups and cannot see the creator information even though I am an admin.

**Comment by Ylianst** [comment]
Nothing needs to be done. The extra information will only show up for groups created after the update to v0.6.12. Let me know if you still don't see it.

**Comment by frankmcc** [comment]
I'm on 6.13 and I don't see it.

**Comment by Ylianst** [comment]
@SomeGuru, can you test when you can and see if it works for you?

**Comment by SomeGuru** [comment]
Hi YlianSt,

I have to tap down larger server with a reboot. Seeing similar however to Frank right now without a reset on my servers...

**Comment by Ylianst** [comment]
Hold on, I see the problem now... working on it!

**Comment by Ylianst** [comment]
I see the problem, you need to hit refresh on the page after you create the device group. Working to fix this now.

**Comment by Ylianst** [comment]
Just fixed it, it will be in MeshCentral v0.6.14 when next published. For now, just hit browser refresh once after creating the device group.

**Comment by frankmcc** [comment]
Got it.  Thanks!

**Comment by Ylianst** [comment]
MeshCentral v0.6.14 is out. Should fix this.

**Comment by SomeGuru** [comment]
Resolved in the latest without issue... Closing as fixed.
