### ISSUE TITLE
Android 9 & 10, Mobile View extremely laggy on MechCentral servers with large deployments

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1717]
Hi MeshCentral team,

I have started seeing where mobile versions of the dashboard on Android 9 & 10 are unable to display without  extreme lag or browser crashing in mobile mode only larger mechcentral deployments with several hundred systems online. Average group sitting at 65 units per group with over 76 groups visible upon logon... can this be resolved for Android mobiles?

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
I just checked in a few performance improvements that you can try out in MeshCentral v0.6.13 when it comes out. Basically, the new version of the app will hide all devices in the list except the ones that are visible in your scrolling range. Hopefully hat way, the device has much less stuff to draw. Let me know what you need once the next version is published. Thanks.

![image](https://user-images.githubusercontent.com/1319013/90489701-7eaa0300-e0f2-11ea-900f-697be35bbccd.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.13, let me know if it's faster now.

**Comment by SomeGuru** [comment]
Improvement, but still showing lots of lag on profile that is larger numbers... 

Any way to default mobile views to accordion closed until a group is selected and then it expands?

Just a thought.
SomeGuru

**Comment by Ylianst** [comment]
Just checked in a change that should give you another 10x speed boost on the mobile app when there is a long device list. It will be in MeshCentral v0.6.15 when it comes out.

**Comment by Ylianst** [comment]
MeshCentral v0.6.15 is out with the speed boost. Let me know what you see.

**Comment by SomeGuru** [comment]
This improved some lag of the mobile side, but I think it might have added a slight lag on the desktop side... However not able to do something more than crashing in Mobile browser.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Desktop web application is completely unchanged. If you see a mobile crash, can you add `&mobile=1` in a desktop browser and see if you get an error? If so, send back the error from the browser console. Thanks.
