### ISSUE TITLE
 Feature Request: Allow user dialog box to be expanded

### ISSUE THREAD

**Issue by robclay** [Ylianst/MeshCentral#1718]
When I am adding and selecting the options of a user for a group, I wish I could see more "real estate" of the selection box... or allow me to expand it manually.
![User Dialog](https://user-images.githubusercontent.com/19339985/90420897-381ac100-e07e-11ea-8fca-0b7ce17b877f.png)

**Comment by dinger1986** [comment]
@si458 seems pretty niche

**Comment by si458** [comment]
all fixed 👍 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/4e457414-a7c6-4253-8d14-fa89c8abd4be)

**Comment by dinger1986** [comment]
sweet
