### ISSUE TITLE
ClickOnce require Edit Device Group rights?

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#172]
If the user does not have “Edit Device Group” rights, then he sees ClickOnce links (RDP / Putty), but nothing happens when you click on them. It seems to be a mistake?

**Comment by Ylianst** [comment]
You right. Fixed it in MeshCentral v0.3.1-a that I just published. Check and close the issue when you can. Thanks.

**Comment by TitovLab** [comment]
Yes, the problem has disappeared. Thank you!
