### ISSUE TITLE
Using SSL Certificate On Ubuntu Server

### ISSUE THREAD

**Issue by IndigoRise** [Ylianst/MeshCentral#1720]
Hello Ylian,
i wanted to activate a ssl certificate (let’s encrypt) on an ubuntu 20 Server. But unfortunately i failed. Is there a short tutorial how todo it? I didn‘t find a description. Would be great to know.
Thanks in advance,
Alvaro

**Comment by Ylianst** [comment]
Hi. It's not clear from your question if you already have a certificate and wish to use it for MeshCentral, or want to setup MeshCentral's built-in Let's Encrypt support. Note that MeshCentral will not get a domain name for you, you must get one separately and make the DNS name point to the MeshCentral server on your own. Make sure you also set the "cert" value to the "settings" section of config.json to your DNS name.

If you already have a certificate, you can replace the following two files in the "meshcentral-data" folder with your own certificate:

```
webserver-cert-public.crt
webserver-cert-private.key
```

If you want to use the built-in Let's Encrypt support, first make sure that HTTP port 80 from the outside internet is routed to port 80 on your MeshCentral server. Then use [https://letsdebug.net/](https://letsdebug.net/) to check that everything is ok. Lastly, go on the [MeshCentral web site](https://www.meshcommander.com/meshcentral2), get the User's Guide. There is a section on Let's Encrypt. Take a look at that. It should not take long and MeshCentral will automatically renew your certificate.

Hope that helps,
Ylian

**Comment by IndigoRise** [comment]
Hello Ylian, thanks for responding so quick. I wanted to use the build in functionality of meshcentral. I already have setup the dns and domain. I will take a look into the user guide again. I might overlooked it. Thanks again!!

**Comment by Ylianst** [comment]
Excellent. I will close this, feel free to re-open if needed.
