### ISSUE TITLE
Agent Crash on Windows Server 2008 R2

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#1722]
I've Installed Mesh Agent on a Windows Server 2008 R2 and got the following message in the log file:

[2020-08-18 08:00:06 PM] FATAL EXCEPTION [meshagent64-RCGRestaurants (1)_8B576391D4FE9745.exe] @ [FuncAddr: 0x000000013fbe22f1 / BaseAddr: 0x000000013fbdc1bc / Delta: -24885]

The Agent work for a while but then connection is broken while the Agent running at 50 CPU.
The Agent is version 0.2.1 64bit and Server is version 0.6.12.

**Comment by Ylianst** [comment]
Hi. Not sufficient data for us to debug this. We need a core dump. If you have your own server, add the `AgentCoreDump` line in the settings of the config.json like this:

```
{
  "settings": {
    "Cert": "central.mesh.meshcentral.com",
    "AgentCoreDump": true
  }
}
```

Then, restart your server. The next time the agent crashes, it will generate a dump file and on agent restart, it will upload it in the "meshcentral-data/coredumps". You can then send me this file privately, here is [my contact info](https://www.meshcommander.com/contact-information). We will take a look at it.

Bryan just tested the agent on Windows Server 2008 R2 and did not see any issues. Thanks.
