### ISSUE TITLE
Wrong case on letsencrypt.js name

### ISSUE THREAD

**Issue by steuck13** [Ylianst/MeshCentral#1723]
Greetings

I was trying to enable letsencrypt section of my config.json file but decided to look at what the code was doing and I've found the following:

![image](https://user-images.githubusercontent.com/997689/90557371-c2dbe880-e170-11ea-965c-adfe18aa60a1.png)

While the actual file is named `letsEncrypt.js`. When I tried to run meshcentral this happened to be a problem since it couldn't find the file. Am I missing something or is this a bug?

**Comment by Ylianst** [comment]
The name of the file should be:

```
node_modules/meshcentral/letsencrypt.js
```

That is what I have. I try to use all lower cases for the file name because of Windows/Linux handling of file cases. Are you seeing "letsEncrypt.js"? Did you install using NPM?

**Comment by steuck13** [comment]
Thank you for your answer.
Not really, installing from NPM this doesn't happen. The problem appeared using the code cloned directly from this repository.

**Comment by Ylianst** [comment]
Oh. Not something that would be normally encountered since people usually install from NPM, but still a problem.

**Comment by Ylianst** [comment]
Fixed. Thanks for reporting. it.

**Comment by steuck13** [comment]
Tyvm
