### ISSUE TITLE
Agent not back online after modem reboot

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1724]
I have a problem with a specific agent not coming back online.

This laptop is connected to a 4G modem (tp-link mr200) and when I reboot the modem the agent goes offline as expected. 
After hours of waiting the agent does not come back online (the internet is active again )
Teamviewer is back online immediately and I use this to restart the mesh service.

I have multiple setups like this, with modems that reboot nightly, and all is ok.
The only difference in this case is that the laptop is directly connected to the modem lan port, making the ethernet ports also go offline when rebooting.
Could this be related to the agent not detecting that it needs to re-connect?

Anything I can help with to debug this issue?

**Comment by Ylianst** [comment]
What agent are you using? Is this Linux, Windows, MacOS, BSD?

**Comment by Allowee** [comment]
This is the 64 bit windows agent

**Comment by Ylianst** [comment]
One thing that will help if you can do it is to stop the MeshAgent windows service and run the agent manually from the command prompt. You need to open a administrator command prompt, go to `C:\Program Files\Mesh Agent` and type:

```
meshagent run
```

It should look like the screen below and you will see all agent connection attempts, etc. Would be interesting to see what is going on.

Ylian

![image](https://user-images.githubusercontent.com/1319013/90691277-ef067080-e227-11ea-8a8d-263308f2396b.png)

**Comment by Allowee** [comment]
okey... this seems resolved by updating to the latest version.
Tested it using the run command and with the service.

Here is the log from the old agent version anyway.
I will open another issue if the problem comes back

c:\Program Files\Mesh Agent>MeshAgent.exe run
MeshCentral2 Agent
Connecting to: wss://example.com:444/agent.ashx
Connected.
Server verified meshcore... Launching meshcore...
Mesh Server Connection Error
Connecting to: wss://example.com:444/agent.ashx
Mesh Server Connection Error
AutoRetry Connect in 2178 milliseconds
Connecting to: wss://example.com:444/agent.ashx
Mesh Server Connection Error
AutoRetry Connect in 3600 milliseconds
Connecting to: wss://example.com:444/agent.ashx
Mesh Server Connection Error
AutoRetry Connect in 6898 milliseconds
Connecting to: wss://example.com:444/agent.ashx
Mesh Server Connection Error
AutoRetry Connect in 4829 milliseconds
Connecting to: wss://example.com:444/agent.ashx

and this hangs at the last message (waited 5 minutes)

**Comment by Allowee** [comment]
Tested again today, still working correctly.
I don't know how but since it's fixed I will close this issue
