### ISSUE TITLE
Enabling AgentWsCompression results in blank screen 

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1725]
I'm trying to enable websocket compression on my MeshCentral server.
The WsCompression command seems to be working.
But, if I also use the AgentWsCompression command the end result is a black screen when connecting to a device desktop.  The connection does initiate and shows as connected- but it never shows the desktop.
If I try to connect to the remote terminal it will also show as connected and begin displaying the remote command prompt- but usually stops updating around this point:
![terminal](https://user-images.githubusercontent.com/48607498/90702082-54725580-e258-11ea-9097-f86d37a9d4af.JPG)

Setting AgentWsCompression to false gets everything working again.

I first tried this with version 0.6.6 and just upgraded to 0.6.14 and seeing the same thing in both versions.
Here's what my settings looks like.  Do I have that command entered correctly?

```
{
   "settings": {
      "RedirPort": 80, 
      "cert": "mesh.xxxxxxxx.com", 
      "wanonly": true, 
      "selfupdate": false,
	  "desktopmultiplexor": true,
	  "WsCompression": true,
	  "AgentWsCompression": true,
	  "autoBackup": {
		"backupIntervalHours": 24,
		"keepLastDaysBackup": 15,
		"zipPassword": "xxxxxxxxxx",
		"backupPath": "C:\\Mesh Backups"
		}
   }, 
```

**Comment by Ylianst** [comment]
What exact version of NodeJS are you using? I will install the same and try. You can get the version by typing `info` in the "MyServer" / "Console" tab. Thanks.

**Comment by PathfinderNetworks** [comment]
It is version v13.2.0 of NodeJS

**Comment by Ylianst** [comment]
Your right! I see the exact same problem on NodeJS v13.2.0. Now to figure out what to do about it...

**Comment by Ylianst** [comment]
I just checked MeshCentral Router's websocket compression against NodeJS v13.2.0 and it works.

![image](https://user-images.githubusercontent.com/1319013/90818360-3bfb4d00-e2e3-11ea-9431-a4783c174ec0.png)

**Comment by PathfinderNetworks** [comment]
If need be, I am ok with moving to a newer version of NodeJS.  I think they are up to version 14 or something along those lines. Although I suspect you are likely still writing MeshCentral to work best with version 12?

**Comment by Ylianst** [comment]
My dev machine uses NodeJS 6.0.0, so anything above that should work. However, some optional features require v8 or higher like Let's Encrypt.

We did know that v11.11 to v12.15 have a problem. The server auto-detects and turns off web socket compression in that range. But you found a bad version outside that range.

**Comment by Ylianst** [comment]
But the way, I tested on NodeJS v14.3.0 and agent compression works.

**Comment by PathfinderNetworks** [comment]
I just updated to NodeJS v14.8.0 and agent compression is working properly.  
Thanks!
