### ISSUE TITLE
Error after upgrade to 6.14

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#1726]
After upgrade from 6.13 to 6.14 the device list and groups not show. 

Console From Web Browser:
`Uncaught TypeError: Cannot read property 'length' of undefined
    at updateDevices (?lang=eng:1)
    at ?lang=eng:1
updateDevices @ ?lang=eng:1
(anonymous) @ ?lang=eng:1
setTimeout (async)
mainUpdate @ ?lang=eng:1
onMessage @ ?lang=eng:1
MeshServerCreateControl.o.xxOnMessage @ meshcentral-min.js:1`

**Comment by FrankSanabria** [comment]
In Source from Browser have mark error in line 3419:

```
function modifyMarkerloc(e) {
    var t = e.getId();
    if (t && (e.setStyle(markerStyle(getNodeFromId(e.a), 4)),
    !getActiveInteractions(e))) {
        var n = new ol.interaction.Modify({
            features: new ol.Collection([e]),
            pixelTolerance: 10
        });
        xxmap.activeInteractions.push({
            featureid: t,
            feature: e,
            interaction: n
        }), -> This line mark error
        xxmap.map.addInteraction(n)
    }
}
```

**Comment by Ylianst** [comment]
Can you add `&minify=0` or `?minify=0` to the URL and let me know if you see an error? If so, can you report it back? Looks like the minified page has an issue. If the same problem occurs on the normal page, the error report will be better. Thanks.

**Comment by FrankSanabria** [comment]
Hi, This is a error with minify=0:

`Uncaught TypeError: Cannot read property 'length' of undefined
    at updateDevices (?minify=0:3608)
    at ?minify=0:1857
updateDevices @ ?minify=0:3608
(anonymous) @ ?minify=0:1857
setTimeout (async)
mainUpdate @ ?minify=0:1852
onMessage @ ?minify=0:2070
MeshServerCreateControl.obj.xxOnMessage @ meshcentral.js:52`

**Comment by Ylianst** [comment]
Found the issue!!! Working on a fix now!

**Comment by Ylianst** [comment]
Fixed in MeshCentral v0.6.15, it's out now! Let me know if it works.

**Comment by FrankSanabria** [comment]
Yes, it works

**Comment by Ylianst** [comment]
Thanks. I am pretty sure it's fixed.
