### ISSUE TITLE
How to enable Remote desktop share

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1727]
After clicking the "Remote Desktop Link" its directing to  " desktop?c=wMYVf2ZRJ" 

But its giving page not found.

**Comment by SomeGuru** [comment]
Hi Aimdharma1990, 

Can you give a bit more detail that kind of draws out your environment to us... such as OSes involved and versions and build numbers if available, also if you are attempting from within the same subnet or outside of the subnet that this machine is located in? Also if you are running the agents/routers on connection or if they are installed.

Thanks,
SomeGuru

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
