### ISSUE TITLE
MeshMessenger Error: No connection key specified.

### ISSUE THREAD

**Issue by sdm216** [Ylianst/MeshCentral#1728]
Chat hasn't been working for the last few releases. When opening chat with any client machine, my machine gives error "Error: No connection key specified." in the chat Window.
![image](https://user-images.githubusercontent.com/62703673/90774622-c46af500-e2c5-11ea-948f-8b284a79f2e3.png)

**Comment by sdm216** [comment]
Update: I believe the issue is only with Azure AD accounts. I created a local user, and did not get this error.

**Comment by Ylianst** [comment]
Yes, I see the same problem. Working on it.

**Comment by Ylianst** [comment]
MeshCentral v0.6.16 is out with a fix for this. Thanks for reporting.

**Comment by sdm216** [comment]
Yep that did it. Thanks!
