### ISSUE TITLE
Difficult to determine local pointer vs remote pointer when they look the same

### ISSUE THREAD

**Issue by JAL741** [Ylianst/MeshCentral#1729]
Issue #191, "Mouse pointer not where it shows", is made more complicated when the local mouse pointer and the remote mouse pointer look visually identical.  Therefore this is a request for an option to make the local mouse pointer be visually different from the remote mouse pointer (For example, products like VNC Viewer Plus use a small square for the local mouse pointer)

**Comment by krayon007** [comment]
What OS are you running on each side, and which browser are you using?

**Comment by JAL741** [comment]
• Local machine running Mesh Commander 0.8.8 uses Windows 10 version 1809.  also tested on a different computer using Windows 10 version 1909.
• Machine being remotely managed uses Windows 10 IoT Enterprise version 1903.  This machine has two displays; one at 1366x768, the other at 1920x1080 resoluton.

**Comment by Ylianst** [comment]
So, just to be clear, this is not a MeshCentral issue. Your reporting on a MeshCommander issue?

**Comment by JAL741** [comment]
correct
