### ISSUE TITLE
Force 2-step login

### ISSUE THREAD

**Issue by elric72** [Ylianst/MeshCentral#173]
Hi,

First of all, thank you for your great job on this software.
I have a quick question, is it possible to force 2-step login for all users or is it plan to implement this feature ?

Thank you in avance for your answer.
Best regards
David

**Comment by Ylianst** [comment]
Good request, I just added that into MeshCentral v0.3.2-d. In the domain section of config.json, you can add a password requirement section like this:

`"PasswordRequirements": { "min": 8, "max": 64, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "hint": true, "force2factor": true }`

Or just add this:

`"PasswordRequirements": { "force2factor": true }`

When added, users will not be able to create device groups or click on devices until they add 2-factor auth to their account. Please test and report back if it works for you.

![MC2-RequireTwoFactor](https://user-images.githubusercontent.com/1319013/55904837-9f208f80-5b85-11e9-8ec3-1bbf3721f5dd.png)

**Comment by openmoto** [comment]
Cool, looking great!
Thanks

**Comment by Ylianst** [comment]
Thanks. If it works, close this issue. If you run into any issues, feel free to re-open anytime.

**Comment by Ylianst** [comment]
Ok, closing this. Re-open if needed.

**Comment by elric72** [comment]
Sorry for the long time to feedback, I am pretty busy rught now.
It sounds good. I will try this in one week and I will keep you inform.
Again thank you for this great project.

**Comment by elric72** [comment]
I have tested today and it works very well.
Great job.

Thank you
David
