### ISSUE TITLE
Device groups created by other users not visible to admin

### ISSUE THREAD

**Issue by sheruvs** [Ylianst/MeshCentral#1737]
First of all, a bunch of thanks for this wonderful software, thats making life easier for so many!

A query - When a user creates a Device Group, the same is not visible to the admin user (unless the user manually adds admin to the Device Group). What configuration is to be done for admin to 'see' and manage ALL devices created by all users? My understanding is that by default, all devices should be visible to admin as s/he is the superuser.

Thanks in advance.

**Comment by Ylianst** [comment]
Thanks. Yes, this feature do exist. In the domain section of the config.json, add "ManageAllDeviceGroups" with a list of users that will manage all the device groups. Note that users listed in this list MUST also be server administrators.

```
  "domains": {
    "": {
      "title": "MyServer",
      "ManageAllDeviceGroups": [ "admin" ]
    }
```

Let me know if it works.

**Comment by sheruvs** [comment]
Wow! Thanks for the very prompt response.
Will check it out and get back.

Also, by the way, what is an "Admin Realm"?  Can you please point me to some documentation?

Thanks again!

**Comment by sheruvs** [comment]
> Thanks. Yes, this feature do exist. In the domain section of the config.json, add "ManageAllDeviceGroups" with a list of users that will manage all the device groups. Note that users listed in this list MUST also be server administrators.
> 
> ```
>   "domains": {
>     "": {
>       "title": "MyServer",
>       "ManageAllDeviceGroups": [ "admin" ]
>     }
> ```
> 
> Let me know if it works.

Yess! It works! 
Thanks a ton, Ylianst!
