### ISSUE TITLE
Error on Windows Server 2012 R2

### ISSUE THREAD

**Issue by sdlopexvidri** [Ylianst/MeshCentral#1741]
Hi, jus a little problem with one server on my mesh central, when I click on conect on Desktop tab, don't do that, and on console I get the problem

uncaughtException1: promise.uncaughtRejection: Error calling WTSQuerySessionInformationW: undefined

My device is a windows Server 2012 R2.

Thanks in advance.

**Comment by si458** [comment]
closing as stale and server 2012 r2 is no longer supported
