### ISSUE TITLE
Request - Uninstall Agent and Delete from server in one click

### ISSUE THREAD

**Issue by cjmny** [Ylianst/MeshCentral#1742]
We are looking to switch full time to MC from ConnectWise Control.  We mostly deal with ad-hoc support sessions, and it would be useful to have an "Uninstall Agent and Delete from Server" as a single option when you are closing out of a session.  Is that possible?  Thanks!

**Comment by si458** [comment]
You can now run `uninstallagent` from the console tab of a device
And it will run the uninstall command for you :)
