### ISSUE TITLE
Unable to navigate into directories with many files in the Files view

### ISSUE THREAD

**Issue by PTR-inc** [Ylianst/MeshCentral#1745]
MC v0.6.19 on server 2016
Agent on windows 10 2004, 1903, server 2016
Browsers on mac, edge and safari

When navigating in the files view and trying to enter a folder with many files, like the 'system32' folder on windows for example, nothing happens. The view doesn't enter the directory. Also experienced it on other non-system folders.

**Comment by Ylianst** [comment]
I can't make this happen. Can you open the browser console and see if any errors show up when no files are displayed? If there are any errors visible, please post them here. - Thanks.

**Comment by PTR-inc** [comment]
Ofcourse! I could get the error properly copied for some reason, so made a snap of it:

<img width="794" alt="Screenshot 2020-08-25 at 00 12 32" src="https://user-images.githubusercontent.com/47147771/91101824-30ec4800-e668-11ea-9706-32efcff4ecdf.png">

Hope this helps.

**Comment by Ylianst** [comment]
Oh perfect! This helps a lot, thanks!

**Comment by Ylianst** [comment]
Ok, I am getting this problem in Chrome but not FireFox. Working on it.

**Comment by Ylianst** [comment]
Fixed this, it will be in MeshCentral v0.6.21 when it's next published.

**Comment by PTR-inc** [comment]
Confirmed, thanks!
