### ISSUE TITLE
How can i add new language for translation?

### ISSUE THREAD

**Issue by volkans80** [Ylianst/MeshCentral#1747]
Hello,

I want to add Turkish translation but language lists are not containing Turkish language. How can i add new language to all lists? Is there a simple way or should i modify all related files?

Thanks,

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.20 with an automated translation of MeshCentral in Turkish. Can you take a look at the "translate.json" file and make any fixes? You can make a [pull request on GitHub in this folder](https://github.com/Ylianst/MeshCentral/tree/master/translate), or you can just send me the updated file, [my contact info is here](https://www.meshcommander.com/contact-information). Thanks in advance.

**Comment by volkans80** [comment]
Thanks, i will update language file.

**Comment by volkans80** [comment]
I got error with v0.6.20

```
ERR: D:\MeshCentral\node_modules\nedb\lib\datastore.js:77
    if (err) { throw err; }
               ^

Error: Cannot create a string longer than 0x3fffffe7 characters
    at Object.slice (buffer.js:606:37)
    at Buffer.toString (buffer.js:803:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}
Error: Command failed: C:\Program Files\nodejs\node.exe D:\MeshCentral\node_modules\meshcentral --launch 532772
D:\MeshCentral\node_modules\nedb\lib\datastore.js:77
    if (err) { throw err; }
               ^

Error: Cannot create a string longer than 0x3fffffe7 characters
    at Object.slice (buffer.js:606:37)
    at Buffer.toString (buffer.js:803:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Program Files\\nodejs\\node.exe D:\\MeshCentral\\node_modules\\meshcentral --launch 532772'
}
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
```

**Comment by Ylianst** [comment]
Not sure if this is related to the original issue above. Did you make changes to any of the files? What where you doing when this happened?

**Comment by volkans80** [comment]
I updated the application with MeshCentralInstaller and application did not work. Then i run the application with `D:\MeshCentral\node_modules> node meshcentral` and i got this error. I will try clean install.

**Comment by Ylianst** [comment]
Can you rename the "meshcentral-data" to "meshcentral-data2" and reset the server? It looks like a problem with the database, but not sure.

**Comment by volkans80** [comment]
Yes it is working when renaming folder. I am looking old database files. Why smbios db is very large 1.1GB. I just installed and added 15 computer and it is worked for two days.

**Comment by volkans80** [comment]
Ok i deleted smbios db and it works now. Also i sent you the smbios db. Thanks.
