### ISSUE TITLE
Allow for hex encoded node ids in urls

### ISSUE THREAD

**Issue by tiny6996** [Ylianst/MeshCentral#1748]
[based on this reddit post](https://www.reddit.com/r/MeshCentral/comments/iei5uy/struggling_to_create_link_directly_to_node/) I would like to be able to link to the remote access page of a host from a monitoring platform. In order to facilitate this please allow linking via the nodeid in addition to using the modified base64 encoding.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.20. Included in this version, you can use the HEX encoded NodeID that you get from running "meshagent -nodeid", in the "&gotonode=" of the web application. Let me know if it works.

**Comment by tiny6996** [comment]
tested on the new release and works great thanks for the rapid  response keep up the good work
