### ISSUE TITLE
Issue installing on Linux

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1749]
While installing the linux agent I discovered something.

Server: Windows 2012R2 and installed own bought ssl web cert in meshcentral
Client: Ubuntu server 20.04.1 LTS

Downloading the script is ok (because of the wget --no-check-certificate)
The next step, running meshcentral.sh, the wget connection fails because of a bad root certificate.
I think the install script should also use the --no-check-certificate in this case and not try to use http://

The underlying issue is, I think, the Comodo/Sectigo Root cert is no longer valid since May 30th.

**Comment by Ylianst** [comment]
The way this should work is that if MeshCentral sees your using the built-in self-signed certificate, it should add the "--no-check-certificate" to the script. However, if you are using a trusted root certificate, then the "--no-check-certificate" should not be used.

In your case, MeshCentral thinks you should be using a real trusted certificate and so, the checks should be made. Your going to have to go back to the self-signed cert or update your trusted cert... or use Let's Encrypt.

Hope that helps,
Ylian

**Comment by Allowee** [comment]
Ah figured it out. Mesh is smarter then I thought.
https://whatsmychaincert.com/ helped me with adding the correct root cert and all is ok now.
Thanks for the push in the right direction
