### ISSUE TITLE
WebApp Exception with devices that are granted individual permissions

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#1750]
Have found an issue/bug, which in the past was working fine, some user accounts assigned on devices are not able to connect, device appear on the list of devices, but when click on it, nothing happens, found this 3 different times today (this account/devices was working fine until last week).  have tried: resetting the account, move device to another group, reinstall MC, but only works when user is moved to a device group account...  probably this is missing a code or typo on last update.  Just to clarify, other devices for the same account connects and works fine.

**Comment by Ylianst** [comment]
Sadly, not sufficient information provided to fix anything. Can you open the browser console windows and try clicking on a device that dies nothing and see if an error occurs? - Thanks.

**Comment by MC-PM** [comment]
sorry for the incomplete information... attached you´ll see the error that appear in console when a click is performed

![error on MC](https://user-images.githubusercontent.com/63015155/91113213-0217a700-e653-11ea-9305-27b1888894c3.png)

**Comment by Ylianst** [comment]
Perfect, thanks. I think I will be able to fix this tomorrow morning.

**Comment by MC-PM** [comment]
Thank you! this bug is affecting more devices so I really appreciate your help on this.

**Comment by Ylianst** [comment]
Just fixed it. Will be releasing an update shortly.

**Comment by Ylianst** [comment]
MeshCentral v0.6.21 is now published with the fix. Thanks for reporting this. Let me know if it works.

**Comment by MC-PM** [comment]
It´s working fine now... thanks a lot for your help!
