### ISSUE TITLE
List of support keys in config.json

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1751]
Is there any list where i can get the list of configuration keys for meshcentral which we can configure in config.json?

**Comment by PetieM** [comment]
There's a sample config file in [install path]\node_modules\meshcentral. If you want all of the details, you're looking for node_modules\meshcentral\sample-config-advanced.json.

**Comment by Ylianst** [comment]
Another option is to look at the config.json schema file at:

```
node_modules\meshcentral\meshcentral-config-schema.json
```

It includes the keys, expected type, description and default values. If you use Visual Studio or another JSON editor that support the JSON schema, it will auto-correct your JSON using this file.

**Comment by aimdharma1990** [comment]
THanks it helps a lot

**Comment by nikcoultas** [comment]
"In the future, I may work on a more friendly configuration editor."

@Ylianst - Would be massively appreciated! Every time I look at my config to try to add in SMTP support I break it.
