### ISSUE TITLE
gui-agents for invite links

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#1754]
Just noticed that the recently added "Linux, macOS, BSD Self-installing Agent Binaries" available on the Add Mesh Agent dialog are not (yet) listed on the /agentinvite page.

**Comment by dinger1986** [comment]
@si458 these still arent there

**Comment by si458** [comment]
@dinger1986 assigned to me and on my to-do list!

**Comment by si458** [comment]
better late than never, how does this look?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/538b53cd-da07-4fc8-add9-034458ccb270)

**Comment by dinger1986** [comment]
Looks good to me
