### ISSUE TITLE
Mac Remote Desktop - Multi-Monitor Screen Selection

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1757]
Is multi-monitor support for Mac on the roadmap? MeshCentral has been saving me at my day job recently with Kaseya basically not working at all on Mac and MeshCentral working very well with the sole exception of multi-monitor support so I'd love to see monitor selection added for Mac agents as well.

**Comment by ryanblenis** [comment]
Not sure if you're VSA is hosted or self-hosted, but Kaseya actually released a new Mac agent (written in Go) that actually works. Of course, with both MC and Kaseya you need to walk the user through giving security perms for accessibility and whatnot prior to usage, but just an FYI.

I don't have any info on the multiple monitors though, I haven't tried on either platform.

**Comment by PetieM** [comment]
We're self-hosted but that's good to know, thanks! My issue recently has been related to installing it but I'm not sure if the latest installer we have is their newest client so I'll definitely look into that.

Multiple monitors is working well on Windows. I can't speak for Linux as I don't have any multi-monitor setups running it but I do know it doesn't currently work on Mac.

**Comment by PetieM** [comment]
Just want to revisit this. Kaseya has since updated and is working well on Macs again but I'd still love to have monitor selection available via MeshCentral if it's possible. I obviously don't know the ins and outs of what's involved there but only being able to view the primary monitor on Macs at the moment a bit limiting at the moment.

**Comment by PetieM** [comment]
Just stopping in again to see if there is any progress (or even a plan) for this? Not being able to select displays on Macs makes things a bit difficult (not impossible but it would definitely be better if I could see all remote displays).

**Comment by PetieM** [comment]
Closing this as it's covered by #3773 at this point.
