### ISSUE TITLE
Simultaneous Multi User Machine Desktop

### ISSUE THREAD

**Issue by AnonJervis** [Ylianst/MeshCentral#1759]
Hi @Ylianst and team! This is an amazing piece of software and thank you for actively developing it!

I have a linux and a windows desktop for my family that has users logging into their own account simultaneously. Meshcentral2 will show both active users connected under "General" tab but when connecting to desktop it only shows one of the desktop. Are there possible ways to switch between user's desktop on a single machine?

**Comment by krayon007** [comment]
Are you talking about multiple users on the same physical machine? (ie, user accounts on the window machine, and user accounts on the linux machine?)

Which windows and linux OS are you running?
On Windows Server, you can select different active Windows Terminal Services Sessions... 
If you go to the console tab, what does it say if you type "users"  without the quotes?

**Comment by AnonJervis** [comment]
Hi @krayon007 ,

Yes, I am talking about multiple users on the same physical machine and I do have one for Windows and one for Linux each in my homelab. The Windows machine runs on Windows10Pro and the other is Ubuntu 20.04 Desktop. 

In the console window of my window's machine, it says,

`> users
{"SessionId":0,"StationName":"Services","State":"Disconnected"}
{"SessionId":1,"StationName":"Console","State":"Active","Username":"user1","Domain":"DESKTOP-5Q6MF5G"}
{"SessionId":2,"StationName":"","State":"Disconnected"}
{"SessionId":65536,"StationName":"RDP-Tcp","State":"Listening"}
Active Users: DESKTOP-5Q6MF5G\user1, DESKTOP-5Q6MF5G\user2.`

**Comment by krayon007** [comment]
By any chance are you using Fast user switching on Windows?

**Comment by AnonJervis** [comment]
Hi @krayon007 sorry for the late reply. 

No I am not using Fast user switching. I am using rdpwrap as a broker for users to log into my windows VM simultaneously.

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
