### ISSUE TITLE
CertUrl breaks the Router and ClickOnce

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#176]
NGINX is working in front of MeshCentral, MeshCentral takes certificate data from CertUrl. When launching MeshCentral, the correct SHA384 key hash is written, but when generating MeshAction.txt, the wrong serverHttpsHash is substituted from the unused ./meshcentral-data/webserver-cert-private.key.
Therefore, error occurs in MeshCmd: {"message": "TLS Handshake Error"}

**Comment by Ylianst** [comment]
Nice catch. Published MeshCentral v0.3.2-f with a fix for this. Let me know if it works.

**Comment by TitovLab** [comment]
Cool! It works now.
I've never seen that so quickly fixed!
Thank you!
