### ISSUE TITLE
How to allow user to edit device name but to prevent deletion of device

### ISSUE THREAD

**Issue by sheruvs** [Ylianst/MeshCentral#1762]
Hi,

I'm using MeshCentral ver 0.5.95  on Ubuntu LTS server ver 18.0.4.

I am trying to give permissions to a user to edit Server-side device name, Description and ability to add tags of systems. I am able to allow this when I edit the device group the end system is a part of and checking on the check-box "Manage Device Group Computers". But this is also giving the ability to the user to change the device group (that the end system is a part of) and also to delete the device itself completely.

How can I prevent the user from deleting the device and from changing group device membership?

Thanks in advance.
![system-perm](https://user-images.githubusercontent.com/70002420/91535887-7becb080-e931-11ea-8a63-095de7d01790.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.24 with a fix for this. You now need "agent uninstall / delete device" permission to remove a device. Also, moving a device between groups requires "Edit Device Group" rights. Let me know if that works for you.

**Comment by sheruvs** [comment]
Great! Thanks a lot,  Ylianst!
Just upgraded and checked in ver 0.6.24 and it works just fine.
