### ISSUE TITLE
Web UI gets 502 bad gateway error with nginx tls offload on server restart during upgrades

### ISSUE THREAD

**Issue by mherrb** [Ylianst/MeshCentral#1763]
Hi,

I've setup MC with nginx as reverse proxy for TLS offloading. When the web interface is used to upgrade MC to the current version, the browser tries to refresh the page before MC as finished upgrading itself. This causes a 502 Bad Gateway error from the proxy.

Then nginx config has `proxy_read_timeout 180s;` but this happens way faster than 3mn after clicking on the 'OK' button in the upgrade panel. nginx is getting an immediate error when connecting to MC.

The solution would probably to have code running in the browser UI to intercept the 502 error and retry for a while to let the MC server to finish restarting.

**Comment by Ylianst** [comment]
Interesting, this occurs only during the upgrade process? I need to take a look at this.

**Comment by mherrb** [comment]
I've seen a few disconnections with the 502 error duing normal use, but this is really rare and looked like some random bugs triggered a server restart.
In the upgrade case it happens 100% of the time (and I've been upgrading the server at least weekly since we started using MC back in march).
But of course if the code running in the browser is able to handle the errors and retry for a (short) while before reporting the error to the user, that should also handle the seldom events outside the server upgrade

**Comment by Ylianst** [comment]
If you see occasional connection drops, try this in the settings section of config.json

```
    "BrowserPong": 120,
    "AgentPong": 120
```

That will cause the server to generate data on the connections every 2 minutes, you can adjust the time for you case. Sometimes reverse proxies don't like long idle connections.

I will look into the 502 error. The browser page does auto-retry when the websocket connection drops, I will see if I can handle this case.

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
