### ISSUE TITLE
Help with Reverse Proxy

### ISSUE THREAD

**Issue by systemlord83** [Ylianst/MeshCentral#1764]
Hi,

Thanks for such a wonderful project. I have been running Meshcentral on a cloud server for some time now and now wanted to have it running locally. My setup is simple enough.

https://mesh.mydomain.com (DNS) ----> Letsencrypt (Docker) ---> Mesh Container.

 **Letsencrypt conf**

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mesh.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app mesh;
        set $upstream_port 443;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
		   }
}
```

**MeshCentral config.json**

```
{
  "settings": {
    "AllowHighQualityDesktop": true,
    "Cert": "mesh.mydomain.com",
    "Minify": 1,
    "MpsTlsOffload": true,
    "Port": 443,
    "RedirPort": 80,
    "SelfUpdate": true,
    "TlsOffload": true    
  },
  "domains": {
    "": {
      "certUrl": "mesh.mydomain.com:443",
      "newAccounts": 0
    }
  }
}
```

Now all seems well, I can get to the setup admin page and also now log in, however, I cannot get past this error:

"Unable to connect web socket, click to reconnect."

I have tried updating NodeJS as advised in another issue raised here and is running v12.1.0 .

I have tried multiple configs options to no avail. Thanks in advance for any help or direction.

Kindest regards,
Systemlord.

**Comment by Ylianst** [comment]
Hi. Your almost there. By default NGINX will not forward websocket connections and MeshCentral makes heavy use of websockets for both browser and agent connections. In the [MeshCentral User's Guide section 16](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf), there is a sample configuration for NGINX. The important lines are the following:

```
# Allows websockets over HTTPS.
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

You may also want to take a look at increasing timeouts

```
# MeshCentral uses long standing websocket connections, set longertimeouts.
proxy_send_timeout 330s;
proxy_read_timeout 330s;
```

Hope that helps,
Ylian

**Comment by systemlord83** [comment]
Hi Ylianst,

Thanks so much for the reply, I in fact have it running correctly. Missed that entirely. 

Thanks once again!!

Kind regards
Systemlord.
