### ISSUE TITLE
Detection by antivirus - virus total results

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#1765]
I got the server setup with a domain and proper SSL and all. The server seems to work fine, except for the detection of my favorite antivirus, Kaspersky. I've read this forum and reddit, somewhere I saw a comment saying that the agent was tested with virustotal.com. So I did a test myself uploading to virustotal.com the agents my server provided me with and both 32 and 64 bit agents where considered a threat by some antivirus. For some reason the 32bit version has been detected by more antivirus than the 64bit version.  I've tested with Kaspersky own website as well. I'm not sure what is in my powers at the moment to change. Any suggestions?

Here are the links to a screenshot of the result:

**32bit** https://imgur.com/94NKMk5

**64Bit** https://imgur.com/J2fmuYb

Kaspersky results 64bit only:

https://imgur.com/eIuhzZL

BTW, is dwservice.net based on meshcommander?

**Comment by solrac901** [comment]
exclude the file on your antivirus as you may see on the results is being categorized as a Remote Admin tool, so i'm assuming that you can exclude the file on this AV.  Maybe this link can help on the exclusion i don't know which version of kaspersky you are using.
https://support.kaspersky.com/4579
Regards.

**Comment by PathfinderNetworks** [comment]
This has been a problem for quite some time.  Most antivirus vendors see the 32bit version as a virus.  I use Avast CloudCare for all of my customers and have to, fairly regularly, submit false positive reports to them to get them to whitelist it.  Even though I have the files and folders excluded in my CloudCare policies it will still detect it every so often.  I suspect there are 'bad actors' out there using MeshCentral as a hacking tool- hence why it gets listed.  But that's just a guess.

**Comment by rodrigolzd** [comment]
Please dont close this yet. I'm testing this out on a few computers with kaspersky antivirus, hopefully I'll get a list of execeptions to report here and that might help some people.

**Comment by damascene** [comment]
Here is the direct link to Kaspersky results for the new release:
https://opentip.kaspersky.com/97D37E948E91A98D65860B20A885DDBEE90D1BEB96816FD83C7FAC840FEA1ADD/
