### ISSUE TITLE
[Bug] linux/raspberry agent session died when conversion key pressed

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#1768]
Hi Ylianst / community,
MeshCentral is very good software thank you for all this effort.
I found a bug when conversion key pressed on terminal menu.
When the agent is installed on Linux and Raspberry Pi, and if you press the Korean-English conversion key or the Japanese-English conversion key(Special Key) on terminal menu, the agent session is died and it is not recovered.
We will be glad to assist if you need logs or any other need to fix the problem.

**Comment by krayon007** [comment]
When you say died, do you mean the agent crashes, or do you mean the terminal session disconnects?
If it crashes, are you able to supply a core dump file?

Is there an easy way to reproduce this with hotkeys/virtual keyboard for this? I've used a virtual korean keyboard on windows, but not on linux...

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
