### ISSUE TITLE
View users when assigning permissions

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#177]
When adding permissions to users, it would be helpful to have some sort of AJAX-esque lookup against existing users, as an admin starts typing in their name. It would make adding users much easier when the system prompts you for the users it knows about, rather than having a fat-fingered-clumsy-admin-like-me typing their name incorrectly.

**Comment by Ylianst** [comment]
Agreed, but I may need to make it an option because on public servers like [meshcentral.com](https://meshcentral.com), you don't want to show the list of other accounts to users. If you are server administrator, that is not a problem. Any suggestions around this appreciated.

**Comment by D4V3M0NK** [comment]
How about a setting within config.json?  Within the "settings" section, **"showUsers": false,** would define the default behavior and is set to how things are at the moment. However, the default could be overwritten by the same property set within "customer1", "customer2" etc sections. That way you can set the default, but if hosting in a multi-tenant environment, they could choose to either enable it or not (I assume users are defined for each customer within the database).

This also begs the question, is a config.json file the best place for an admin to administer these changes. Why not include these options within the "My Server" section of the GUI, which ultimately writes the settings to config.json under the hood? (I appreciate that this could be a feature request in itself and I'd be more than happy to put it into it's own ticket if you deem it appropriate?)

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-p that does user name matching when adding users to a device group. For now, you only see the list of users if you are the rights to see that list. Feedback welcome. I have not tested this with LDAP yet.

![MC2-UserAutoComplete](https://user-images.githubusercontent.com/1319013/58665870-b0189200-82e6-11e9-86f4-da690e7da2bd.png)
