### ISSUE TITLE
New optional log in style

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1771]
This isn't an issue as much as a question (as I don't use Twitter and can't comment that way).  
I saw the notification about this new style that can be used for the login.  I currently have the traditional login page customized with my own logo and footer.  Are we able to customize the new style login page with graphics and other information?  Such that, whenever there is an update, those customizations will stay- like they do now?
I like the look of that new logon page but would need to be able to have my logo, etc displayed.

**Comment by Ylianst** [comment]
That is a wonderful question/request and one that I want to address. Currently this not customizable, but yes, I want to add customization options and I think it's going to be a lot of fun and look great. Give me a bit more time to work on it and if you have specific requests, yes, please let me know.

(And yes, commenting here on the Twitter posts is excellent!)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.27 with customization improvements to the new login screen.

![MC2-NewStyle3](https://user-images.githubusercontent.com/1319013/92097405-e451ec80-ed8c-11ea-9a88-1c3501919228.png)

Let me know if this works for you.

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.28 with one more fix related to this. You can now put optional "WelcomeText" and it will show up on the new login page.

![MC2-NewStyle4](https://user-images.githubusercontent.com/1319013/92184165-5108cd80-ee05-11ea-97e7-651c2e459e89.png)

**Comment by PathfinderNetworks** [comment]
I just updated to 0.6.28 and set up this new login style.  I love it!  
Thank you for all the hard work you and your team have been putting in to this project.  It is greatly appreciated!
![mesh](https://user-images.githubusercontent.com/48607498/92198756-3d7c5780-ee43-11ea-8cae-ca75e22c7e9c.JPG)

**Comment by PathfinderNetworks** [comment]
Also, the new Zip feature on the files page rocks as well!  I just tried it and it works great. This will be a huge time saver when dealing with trying to copy folders.

**Comment by Ylianst** [comment]
Oh wow! Your page looks wonderful! Nice logo, nice background and excellent use of the footer. Outstanding!

**Comment by whalehub** [comment]
I really like the new design as well. 👍 

![PDH](https://xbb.datahoarder.dev/VUSu3/zOwaNuLe38.png/raw)

**Comment by whalehub** [comment]
I really like the new style as well. 👍 

![PDH](https://xbb.datahoarder.dev/VUSu3/fiBUDuyo29.png/raw)

**Comment by Ylianst** [comment]
Going to close this since the new login page seems to work pretty well. I will be making it the default at some point.
