### ISSUE TITLE
Group Action options repeated

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#1772]
Hi

Running on version 0.6.26 on Ubuntu 19.

Seeing this via Chrome Version 84.0.4147.135 (Official Build) (64-bit)

When selecting mutiple devices to perform a group action, the drop-down list contains duplicates of the possible options available. Screenshot attached for reference. 
<img width="1128" alt="PjTis5igYm" src="https://user-images.githubusercontent.com/6532805/92015670-104b7e80-ed49-11ea-9bcb-efb9bed36bdf.png">

**Comment by Ylianst** [comment]
Your right! Will fix this in the next version. Thanks for reporting this.

**Comment by Ylianst** [comment]
Just fixed it, it will be published in MeshCentral v0.6.27 later today.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.27. Please close this issue if it works.

**Comment by drnikcuk** [comment]
Yup, much better, thanks !
