### ISSUE TITLE
CIRA Not Checking In

### ISSUE THREAD

**Issue by cdw-brendenmorgenthaler** [Ylianst/MeshCentral#1773]
I have created a test group (Agent + CIRA) in MeshCentral 0.5.81 and added three different systems to it.  All three are remote, no physical access, so I setup them up as follows.

1) Reset AMT on all of them so it was in a pre-provisioned state
2) started meshcmd microlms and Activated AMT (now the device is sitting in Activated CCM mode)
3) ran a meshcmd AmtScript to add the device to the group.

Now one of the devices has checked in and shows up as connected by CITA - Intel ME: Activated CCM, v11.8.65. The other two devices do NOT show up.  

4) Ran meshinstall.sh on all three nodes

Now all the devices show up in the group however node 1 is Agent + CIRA, the other two are Agent only though they all show Intel ME as activated.

Node 1) Agent + CIRA, Intel ME: Activated CCM, v11.8.65
Node 2) Agent, Intel ME: Activated CCM, v11.8.65
Node 3) Agent, Intel ME: Activated CCM, v11.8.77

Stopping meshagent on each system and firing up microLMS doesn't show anything different between them that isn't expected (random security domains, different IP addresses, etc.).  Well one thing that is different is Node 1 doesn't report an IP address for AMT even though it has one.

![Screen Shot 2020-09-02 at 3 53 33 PM](https://user-images.githubusercontent.com/49529537/92035542-7974c700-ed34-11ea-82d8-d31bda8f176b.png)
![Screen Shot 2020-09-02 at 3 54 17 PM](https://user-images.githubusercontent.com/49529537/92035604-93160e80-ed34-11ea-80d2-28d0e8b98a20.png)

EDIT: more information

The group is setup with an AMT policy of Simple Admin Control Mode (ACM) + CIRA but I don't think that is being applied.

**Comment by jsastriawan** [comment]
Activation of AMT to ACM needs the right domain environment and proper activation certificate. If ACM activation failed, it will attempt to activate to CCM.

When CIRA is activated, IPV4 is None which is the right behavior. It looks like the other two system CIRA configuration is not activated yet, If you have access to the system via MeshCommander, please check "Internet Settings".
![image](https://user-images.githubusercontent.com/6583218/92643314-69aa3500-f296-11ea-92a8-93d3597a504d.png)
There should be some entries on the yellow highlighted area. If not, you could run cira_cleanup.mescript followed up by cira_setup_xxx.mescript (for your specific Device Group) on each machine to see if it can connect.

If it still cannot connect, please check the system UUID of the AMT. Sometimes corrupt SMBios table caused UUID to be not unique thus CIRA connection is rejected,

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, the was a few AMT fixes recently,
if issue still happens, please reply back
