### ISSUE TITLE
Feature Enhancement Request: Cloud Backup

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1775]
@Ylianst, you've done it again! Thank you so much for all your work on this project! The new Google Drive backup feature looks absolutely amazing and I do plan to give it a try but I'm wondering if it's possible to add other cloud backup options like OneDrive, Azure blob storage or even Dropbox as alternative cloud storage backup location options. No rush at all as we snapshot our server but it would be super cool to have some additional options. Tha la again for the project!

**Comment by whalehub** [comment]
This is just my two cents, but I think it would be more prudent to use something like rclone or Duplicati to copy/move backups to other cloud destinations because implementing support for all the different providers that people use would not only be a large undertaking in terms of time and effort spent, it would also add a continuous maintenance burden in the form of keeping up with API changes made by these providers.

**Comment by robclay** [comment]
What about incorporating WebDav?  Would that cover both scenarios?  (Selfishly, that would cover NextCloud backups!)

**Comment by asasin114** [comment]
> What about incorporating WebDav? Would that cover both scenarios? (Selfishly, that would cover NextCloud backups!)

I just listed a few services that came to my mind when making the request. I don't use NextCloud in my environments but it would be a great add as well!

**Comment by Ylianst** [comment]
A took a quick look at this, WebDAV seems like it could be a good choice but you can authenticate using HTTP Digest or OAuth. If I where to go in that direction, would HTTP Digest be sufficient?

**Comment by robclay** [comment]
I think NextCloud is HTTP Digest, but I am not sure.

**Comment by whalehub** [comment]
@Ylianst Yeah, HTTP Digest would be sufficient. It's what Nextcloud uses.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.32 with auto backup WebDAV support. Let me know if it works, I tested it using a free provider and it seems to work.

![MC2-WebDAV1](https://user-images.githubusercontent.com/1319013/92797879-51eeb180-f367-11ea-974c-3c93167cce26.png)

![MC2-WebDAV2](https://user-images.githubusercontent.com/1319013/92797890-54510b80-f367-11ea-8632-9125b695e22b.png)
