### ISSUE TITLE
Possible improvements to the 7 days power state chart

### ISSUE THREAD

**Issue by LFM8787** [Ylianst/MeshCentral#1778]
I've been looking the 7 days power state chart and I liked it a lot. One improvement that would be great is the hour of the day column, like a table header to quickly know with a little error the using behaviour of the user:

![image](https://user-images.githubusercontent.com/13755139/92275211-18c8c400-eec5-11ea-8e89-4f2604aee52e.png)

In this example, I imagined a record of the actual battery state in time, I know the little battery icon indicates the current state but there is no over time record:

![image](https://user-images.githubusercontent.com/13755139/92275231-22522c00-eec5-11ea-8291-ccecde2341f2.png)

A less consumption alternative of the above idea, only charging/discharging states:

![image](https://user-images.githubusercontent.com/13755139/92275249-29793a00-eec5-11ea-870b-a060c3923a47.png)

**Comment by yomono** [comment]
I'm interested on the first approach.. Today is just a long black bar that don't actually says anything to me..
Example:

![ksnip_20200904-234139](https://user-images.githubusercontent.com/31445936/92296181-34a18980-ef08-11ea-8dae-7b7d389f3aab.png)

I mean.. yeah, it was online most of the time.. that all i can know by looking at that

**Comment by Ylianst** [comment]
Yes, good requests. Note that if you hover the mouse over a power bar, you should see the start and end time of the bar.

**Comment by yomono** [comment]
> Yes, good requests. Note that if you hover the mouse over a power bar, you should see the start and end time of the bar.

damn, this thing is full of secrets isn't? 😄

**Comment by Ylianst** [comment]
I had not considered this, but Easter Eggs will be added.

**Comment by si458** [comment]
as @Ylianst explained, if you hover over a section of the power graph, it will display times for you, the same for white spaces
