### ISSUE TITLE
0.6.28 - login form and image are missing with siteStyle:2

### ISSUE THREAD

**Issue by jonathandewitt** [Ylianst/MeshCentral#1779]
Updated to 0.6.28 and have "siteStyle":2 set, but login page/fields only work if this option is unset. If I set it and restart the server, I get a blank page with the proper fields present but a CSS property of display:none set. They never appear or become usable.

![image](https://user-images.githubusercontent.com/45440466/92290186-3572f500-eee1-11ea-814e-26ea706bc494.png)

`{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "redacted",
    "MongoDB": "mongodb://127.0.0.1:27017/meshcentral2",
    "WANonly": true,
    "port": 8443,
    "aliasPort": 443,
    "redirPort":8080,
    "redirAliasPort": 80,
    "ExactPorts": true,
    "AgentPong": 120,
    "TlsOffload": "127.0.0.1"
  },
  "domains": {
    "": {
	  "siteStyle": 2,
      "title": "redacted",
      "title2": "",
	  "titlePicture": "logo-dev.png",
      "minify": true,
      "_newAccounts": false,
      "userNameIsEmail": true,
      "certUrl":"https://127.0.0.1:443",
      "ManageAllDeviceGroups":[ "redacted@redacted.net","redacted@redacted.net" ],
	  "welcomeText": "Please log in to continue."
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
`

**Comment by jonathandewitt** [comment]
For what it's worth, other A tags appear to work, the Terms link for example works and navigates to another page, which looks like the same page as the terms page with siteStyle:2 not set.

**Comment by PathfinderNetworks** [comment]
How do you have that line entered in your config.json?  In your post you mention  "SiteStyle":2  When it should be "SiteStyle": 2 (a space between : and 2).  I'm running 0.6.28 and not seeing this same issue.  So I'm wondering if it may just be a syntax issue in config.json?

**Comment by jonathandewitt** [comment]
I just tried it both ways, with the same result. I only get login forms to display when that value is set to 1, or if that whole config parameter isn't set.

**Comment by PathfinderNetworks** [comment]
Can you post your config.json- obviously with the sensitive info obfuscated?

**Comment by jonathandewitt** [comment]
A complete config.json was included in the original post.

**Comment by PathfinderNetworks** [comment]
Sorry, my bad.  The way it appeared in the post it looked like some other code.  
I do see where it looks like you are missing a closing bracket ( } ) at the end of your settings group.
You have 
"settings": { 
"cert": "redacted", 
"MongoDB": "mongodb://127.0.0.1:27017/meshcentral2", 
"WANonly": true, 
"port": 8443, 
"aliasPort": 443, 
"redirPort":8080, 
"redirAliasPort": 80, 
"ExactPorts": true, 
"AgentPong": 120, 
"TlsOffload": "127.0.0.1" 
}, 
But it should be (I believe)
"settings": { 
"cert": "redacted", 
"MongoDB": "mongodb://127.0.0.1:27017/meshcentral2", 
"WANonly": true, 
"port": 8443, 
"aliasPort": 443, 
"redirPort":8080, 
"redirAliasPort": 80, 
"ExactPorts": true, 
"AgentPong": 120, 
"TlsOffload": "127.0.0.1" 
}
},

**Comment by PathfinderNetworks** [comment]
I also see a couple space issues in the Domains section.

"domains": { 
"": { 
"siteStyle": 2, 
"title": "redacted", 
"title2": "", 
"titlePicture": "logo-dev.png", 
"minify": true, 
"_newAccounts": false, 
"userNameIsEmail": true, 
"certUrl":"https://127.0.0.1:443", 
"ManageAllDeviceGroups":[ "redacted@redacted.net",
"redacted@redacted.net" ], 
"welcomeText": "Please log in to continue." } 
}, 

"certUrl":"https://127.0.0.1:443",  should be 
"certUrl": "https://127.0.0.1:443", 

and 
"ManageAllDeviceGroups":[ "redacted@redacted.net","redacted@redacted.net" ], 
should be 
"ManageAllDeviceGroups": [ "redacted@redacted.net","redacted@redacted.net" ], 

But I don't think it's even getting to your Domains section due to the missing end bracket in the settings section.  Typically, when there are formatting errors in config.json the server will crash when starting. So I'm surprised that wasn't happening?

**Comment by jonathandewitt** [comment]
`{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "20200905-0005",
  "settings": {
    "cert": "redacted",
    "MongoDB": "mongodb://127.0.0.1:27017/meshcentral2",
    "WANonly": true,
    "port": 8443,
    "aliasPort": 443,
    "redirPort":8080,
    "redirAliasPort": 80,
    "ExactPorts": true,
    "AgentPong": 120,
    "TlsOffload": "127.0.0.1"
  },
  "domains": {
    "": {
	  "siteStyle": 2,
      "title": "redacted",
      "title2": "",
	  "titlePicture": "logo-dev.png",
      "minify": true,
      "_newAccounts": false,
      "userNameIsEmail": true,
      "certUrl":"https://127.0.0.1:443",
      "ManageAllDeviceGroups":[ "redacted","redacted" ],
	  "welcomeText": "Please log in to continue."
    }
  }
}`

**Comment by PathfinderNetworks** [comment]
Sorry, I just looked at my config.json and see why I have the extra closing bracket in my settings.  Mine extra closing bracket is due to the 'Autobackup' section there.  
In your case it may just be due to the missing spaces I mentioned?

**Comment by Ylianst** [comment]
Hi. When looking at the empty login page, can you save the HTML in the browser using "Save as..." and zip the saved data (+ all images if saved with the page) and send that to me at [my contact address](https://www.meshcommander.com/contact-information). I should be able to fix it. Also, if you can open the browser console (Ctrl-Shift-K in Firefox) and reload the page and send over any errors you see. That would be great.

My pure guess is a single (') or double quote (") in the redacted title or special character is causing a miss-parse. I should be able to fix this quickly. Thanks.

**Comment by jonathandewitt** [comment]
![BrowserConsole](https://user-images.githubusercontent.com/45440466/92300802-da1a2480-ef2b-11ea-8797-0701e97db1c6.PNG)
![FunctionThrowingError](https://user-images.githubusercontent.com/45440466/92300803-dbe3e800-ef2b-11ea-8836-b715f5cfbd78.PNG)
![ConfigRedacted](https://user-images.githubusercontent.com/45440466/92300806-ddadab80-ef2b-11ea-936d-10b6d2c408d7.PNG)

**Comment by jonathandewitt** [comment]
I sent you an email as well with some further information and an actual example config.

**Comment by Ylianst** [comment]
I don't seem to have received any emails. Can you check again and you may need to password zip any html files. Thanks.

**Comment by jonathandewitt** [comment]
Checked my outbound provider this morning, Google will not accept any emails with attached zip files. Not sure how to proceed from here.

**Comment by Ylianst** [comment]
There are plenty of ways to send a zip files, you can also password protect the zip file and can send me the browser consoles errors if you like. Feel free to use any way you like.

**Comment by sharifm-informatica** [comment]
Bug still appears in 0.6.31 but I tried a few combinations of settings and found that the bug happens when ```"userNameIsEmail": true```
if commented out all is well and the login form appears.

**Comment by jonathandewitt** [comment]
> 
> 
> Bug still appears in 0.6.31 but I tried a few combinations of settings and found that the bug happens when `"userNameIsEmail": true`
> if commented out all is well and the login form appears.

This checks out on my install as well. As soon as I comment out that option, the login form appears upon restart of the meshcentral service.

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.34 with a fix for this. Let me know if it works.

**Comment by sharifm-informatica** [comment]
Tested. Fixed. 
Thank you

**Comment by jonathandewitt** [comment]
Updated this morning and tested. Issue appears to be fixed. Many thanks for your attention to this!
