### ISSUE TITLE
Need help server is now running on Port 1029

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#1780]
My meshcentral server has always been running on port 1027 and for some reason my server went down and now when i start it, 
it runs on port 1029 and none of my clients report back now.
is there a way i can start the service on a specific port.

the command i use to start meshcentral is 
nohup node ./node_modules/meshcentral &

any help would be appreciated thanks.

**Comment by Ylianst** [comment]
Hi. The quick answer is that your probably running MeshCentral twice or more. Do `ps -aux | grep mesh` and look at see the over processes you are running.

The longer answer is that MeshCentral will try to use the ports that are specified in config.json, but if not available will use the next available port. So, 1027 is busy and it's going to jump to the next available higher port. Your going to have to stop MeshCentral, stop the process that is using port 1027 and start MeshCentral again.

Try running MeshCentral without the & at the end and you will see what ports it's using and can hit ctrl-c to stop and start again. Should make it easy to see what is going on.

Hope that helps,
Ylian

**Comment by haxmachine** [comment]
![image](https://user-images.githubusercontent.com/50190618/92318826-29a83f80-f055-11ea-829c-1d47a9eaf91b.png)

**Comment by Ylianst** [comment]
So, screen shows MeshCentral running. Your going to have to diagnose this a bit more. Kill that version and try running it again.

**Comment by haxmachine** [comment]
i have stopped meshcentral and confirmed with my Host that port 1027 is free and available yet meshcentral wants to start on 1029.
is there a way i can set the port in the config.json to always use port 1027?

**Comment by drnikcuk** [comment]
> confirmed with my Host that port 1027 is free

Do you mean you have verified yourself that nothing else is running on that port? What does netstat -tulpn show ?

**Comment by Ylianst** [comment]
There is a [sample config.json here](https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json) and a more [advanced sample here](https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json).

You can set the port like this:

```
{
  "settings": {
    "cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "port": 443,
    "redirPort": 80,
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true
    }
  }
}
```

Change port 80 and 443 to the ports you want.

I also would like to know what "netstat -tulpn" returns.

**Comment by haxmachine** [comment]
I wasnt able to run the command netstat -tulpn it returned the below message

![image](https://user-images.githubusercontent.com/50190618/92335104-235aa780-f0d7-11ea-8cd6-1795f79e4438.png)

**Comment by haxmachine** [comment]
also changed these to 1027 and some reason it still start on 1029

![image](https://user-images.githubusercontent.com/50190618/92335182-138f9300-f0d8-11ea-92bb-73a9e8de202e.png)

**Comment by whalehub** [comment]
@haxmachine The `Port` and `RedirPort` values have to be different; they can't occupy the same port.

**Comment by Ylianst** [comment]
`RedirPort` is a HTTP port that typically redirect to the HTTPS port, it's optional, if you don't want it, put 0 as the value.

**Comment by drnikcuk** [comment]
> I wasnt able to run the command netstat -tulpn it returned the below message
> 
> ![image](https://user-images.githubusercontent.com/50190618/92335104-235aa780-f0d7-11ea-8cd6-1795f79e4438.png)

Whats your OS ?

**Comment by haxmachine** [comment]
Its running on my web-host shared server which is a Linux distro not sure which one though.

**Comment by whalehub** [comment]
@haxmachine You can find out which distribution you're running by executing the following command:

```
cat /etc/os-release
```

If netstat isn't installed on it by default, which seems to be the case here, you can get it by installing the package `net-tools`.

**Comment by haxmachine** [comment]
doesnt matter what i do to my config it starts on port 1029 LOL this a killer.
was working perfectly fine before now i have lost all remote access

**Comment by haxmachine** [comment]
Linux version 3.10.0-962.3.2.lve1.5.27.el7.x86_64 (mockbuild@buildfarm02.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Sat Nov 30 02:18:52 EST 2019

**Comment by drnikcuk** [comment]
netstat is not included in redhat by default I believe, try:

https://ostechnix.com/linux-troubleshooting-netstat-command-not-found-in-centos-7-rhel-7/

**Comment by haxmachine** [comment]
since its on a shared webhost i will not be able to run that command, the helpdesk assure me that port 1027 is not being used by anything

**Comment by haxmachine** [comment]
any other ideas ive been trying my hardest to get it to run on port 1027 but it always goes to port 1029
