### ISSUE TITLE
Convert manuals to markdown or LaTeX for easy git tracking and maintenance

### ISSUE THREAD

**Issue by sharifm-informatica** [Ylianst/MeshCentral#1782]
I only found .ODT files. It would be easier to maintain and contribute if the source was in plain text format like markdown or LaTeX. I recommend markdown to be easier for more contributors.

If this is acceptable I will do the conversion myself and correct any conversion issues. I will also generate the ODT and PDF output files. The project is amazing. I would love to give back.

**Comment by robclay** [comment]
@sharifm-informatica , I will send you some markups I made if you take this on.

**Comment by sharifm-informatica** [comment]
Sure

**Comment by sharifm-informatica** [comment]
@Ylianst is this suggestion acceptable to you? If yes, I will begin converting one of the manuals to markdown as pilot test for feedback.

**Comment by silversword411** [comment]
I converted the PDF/odt to MD a while ago.

It's in the docs folder and what shows when you go to https://ylianst.github.io/MeshCentral/

**Comment by silversword411** [comment]
Lol...this is a 2 year old issue closing.
