### ISSUE TITLE
Make agent functions more visible

### ISSUE THREAD

**Issue by tiny6996** [Ylianst/MeshCentral#1785]
[Based on the this reddit thread](https://www.reddit.com/r/MeshCentral/comments/imwj1t/can_the_font_size_be_changed/) please increase the font size of the agent functions or make them buttons so users on high DPI monitors can see them better. See the image below for an example of the issue.

![image](https://user-images.githubusercontent.com/13280132/92396676-09c35b00-f0eb-11ea-91d1-d3f4fd70210d.png)

**Comment by yomono** [comment]
I would label this as "change font size in general" because that one is just one example. You have that type of text on almost every page

**Comment by Ylianst** [comment]
Just pushed MeshCentral v0.6.29 with Spanish and Dutch fixes and changed all x-small to small fonts. Let me know if that works.

**Comment by yomono** [comment]
It works for me :D

**Comment by tiny6996** [comment]
works again thanks for the quick turnaround
