### ISSUE TITLE
Feature suggestion: System cpu/ram/net/etc status

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#1786]
For my use case (remote machines on a 4G modem) it would be really handy if the agents can collect cpu/ram/daily network traffic data and display this on a separate tab.
This will help identify if the processes are running correctly and synchronizing with a central server.

This would, of course, mean that there will be more traffic over the connection.
A 5 minute average will be enough for a quick daily overview of the performance and not impact the monthly limit of the mobile connection.

**Comment by si458** [comment]
this is more of a remote monitoring and management feature than a remote support issue
i would recommend you look at [tacticalrmm](https://docs.tacticalrmm.com/)
