### ISSUE TITLE
Question: Show title on tab without showing on login page

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1789]
Wondering if there's a way to show my title on a browser tab without showing it in the login page. On the attached picture it shows the "title" text and "loginpicture" image and the tab title is "Mesh Central". I'd like the "title text not to show in the the login page but still show in the tab.
![Screenshot_20200907-194223_Edge](https://user-images.githubusercontent.com/417006/92433301-e2f03d80-f159-11ea-9f57-8abea149bc3c.jpg)

**Comment by asasin114** [comment]
I can achieve what I'm looking for by removing the "title" section from the div under the "LoginPicture" line.

**Comment by asasin114** [comment]
Only downside to my solution is I have to remove the "title" section after every version update.

**Comment by Ylianst** [comment]
I can't look at the code now, but try:

```
"title": "My Name",
"title1: ""
```

Let me know if that works.

**Comment by asasin114** [comment]
@Ylianst, that doesn't appear to be working unfortunately. It's not a big issue so don't worry about it to much.

**Comment by Ylianst** [comment]
I fixed the problem and will be in MeshCentral v0.6.30. Thanks for reporting this.

**Comment by asasin114** [comment]
Wow! Thank you! You continue to amaze me with how rapidly you've been pushing new features and how quickly you respond to the community over such small things. You're awesome @Ylianst! Thank you so much for this project!

**Comment by Ylianst** [comment]
Thanks. With 400+ pending issues, just doing the best I can, same for Bryan. This said, your note is much appreciated. I like small clear issues, they are easy to replicate and fix. Published MeshCentral v0.6.30, let me know if it work.

**Comment by asasin114** [comment]
That worked like a charm! Thank you again!
