### ISSUE TITLE
Feature Request: Set server-side name

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#179]
When installing a client, have an optional command to set the server-side name so that when it registers against the server, it uses that server-side name as opposed to the hostname.

**Comment by Ylianst** [comment]
This is a good request, mesh agent feature so Bryan will have to look into this.

**Comment by kd4zay** [comment]
> This is a good request, mesh agent feature so Bryan will have to look into this.

Hi Guys, not sure if the issue I'm having is related but when I change the name of the host  here:
![image](https://user-images.githubusercontent.com/11742395/57586375-b28f8500-74ba-11e9-8b47-c7e6ce6da7fc.png)
I am unable to re-establish a desktop session and the device appears greyed out,

**Comment by Ylianst** [comment]
Hi. You problem is not related to the original request above, it should be a new issue. In any case, I have not see this problem before. You can indicate if you server is running in LAN mode? have you assigned an IP address or static DNS name to your server or just managing devices on the local network?

**Comment by kd4zay** [comment]
Currently, the mesh server resides on the LAN and just currently being used to manage LAN devices.
The Mesh server has a static IP assigned.
I have made sure to enable the agent service on the boot of the client pc.
Initially, it will work though once I have changed the name OR if I reboot the system if the following error when trying to reconnect to the desktop:
![image](https://user-images.githubusercontent.com/11742395/57592708-bc86a780-74fd-11e9-86c5-29017556ee06.png)

connecting to the terminal is unaffected and works after reboot.
The client is a ubuntu based machine.

**Comment by Ylianst** [comment]
For the original request, there is a new option in the device group "Features" to sync the server-side name to the hostname of the computer. You can enable that and when a computer changes it's host name, it will change the server name. This may take a while or a reboot for the agent to notice the hostname change, but it will sync up.

**Comment by D4V3M0NK** [comment]
Is there any way of adding a switch to the install agent script that defines the name to be shown in MC, rather than always using the configured hostname? I was thinking of something like this:

`(wget https://mesh.mydomain.org/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh || wget https://mesh.mydomain.org/meshagents?script=1 --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://mesh.mydomain.org 'M35hC3ntr4lUn1qu3GrOup1dEntIf3r' 'ClientNameWithinMC' `

Therefore, meshinstall posts not only to my server, and the group but also sets the name to be shown in MC for this install (_ClientNameWithinMC_ in this case)

**Reason**: I'm looking at using this for deploying systems out in the field that use a standard VM for my customers, but they do not have local root access. What the customer does have is a small utility that grants them terminal access to a menu to set the system up on the network and allow them to enter in a unique code for their install. That code calls into an API of mine and assigns a number of instructions to the server, including the MC client installer - and it'd be that string that not only (obviously) assigns that client to a particular group within MC, but ideally I'd like to simply add their customer name as the name within MC. 

I run into other issues that I can't control if I were to alter the hostname of every system that's deployed.
