### ISSUE TITLE
Bug when performing action in multiple devices

### ISSUE THREAD

**Issue by LFM8787** [Ylianst/MeshCentral#1790]
When I select multiple devices in multiple device groups, this is what the Group Action dropdown list looks like:

![image](https://user-images.githubusercontent.com/13755139/92523406-ade5f880-f1f6-11ea-80b3-c3f44f7165e8.png)

**Comment by Ylianst** [comment]
What version of MeshCentral are you using?

**Comment by LFM8787** [comment]
I forgot to update when I reinstalled the server! The bug is not present in the latest update 0.6.29!

Thank you!
