### ISSUE TITLE
Latest Version on github behind the runtime server "check version"

### ISSUE THREAD

**Issue by sharifm-informatica** [Ylianst/MeshCentral#1794]
Latest version in this repo is currently 6.28. In the running server when checking for new versions, the latest is 6.30. 
![Screenshot from 2020-09-09 16-26-21](https://user-images.githubusercontent.com/16869933/92611686-53fa3700-f2b9-11ea-8d81-224ed97b9acb.png)

Where is that coming from? how can we track the new changes in the new versions. Is there another repo providing the latest version to the running servers?

**Comment by Ylianst** [comment]
Looking at the [GitHub repo](https://github.com/Ylianst/MeshCentral), current version is v0.6.30, same for [NPM](https://www.npmjs.com/package/meshcentral). If you can provide an exact link as to where you see that v0.6.28 is current, that would be appreciated.

**Comment by sharifm-informatica** [comment]
Sure https://github.com/Ylianst/MeshCentral/releases/tag/MeshCentral_v0.6.28 is the link on the homepage of the repo
![Screenshot from 2020-09-09 18-22-28](https://user-images.githubusercontent.com/16869933/92626166-d8ed4c80-f2c9-11ea-83c4-482c7632a45a.png)
you can see it at the bottom right of the screenshot.

**Comment by Ylianst** [comment]
Oh, I see. I think Bryan should have been adding these tags to the MeshAgent repo, not MeshCentral. I will check with him.

**Comment by Ylianst** [comment]
So, the tag on the bottom right is intended to indicate the last version of MeshCentral where we updated the MeshAgent. Bryan is using this so we can tell what version of the server has what agent. I do agree that it's not super clear, but you can ignore that tag. The real way to see the currently published version is to [look on NPM](https://www.npmjs.com/package/meshcentral).

**Comment by sharifm-informatica** [comment]
Great, Many Many thanks.
