### ISSUE TITLE
Error Removing Device

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1797]
I just uninstalled the agent from a device and am now trying to remove it but the server is crashing whenever I do so. Log file is attached.
[servererrors.txt](https://github.com/Ylianst/MeshCentral/files/5197576/servererrors.txt)

**Comment by Ylianst** [comment]
OH!!! Working on a fix for this right away!!!

**Comment by Ylianst** [comment]
Just rushed a fix for this one, MeshCentral v0.6.31 is out. Let me know if it works for you.

**Comment by PetieM** [comment]
Working now. Thanks for the quick fix!
