### ISSUE TITLE
Antivirus status for Windows Server platform to match Workstations view

### ISSUE THREAD

**Issue by FDrebin** [Ylianst/MeshCentral#1798]
Is it possible to have the same "Antivirus" info listed for Windows Server operating systems the way that it is listed for Workstations/laptops? While strange I know to want AV info for servers, we have servers that are technically VDI instances due to licensing and this would be useful info.

![image](https://user-images.githubusercontent.com/13129353/92647648-38d9f800-f2b6-11ea-8064-12e990cb9ce9.png)

**Comment by krayon007** [comment]
Interesting, I never noticed that this data didn't show up for Windows Server. IIRC, I was using WMI to query the antivirus state... I'll have to see what is going on with Windows Server SKUs...

**Comment by krayon007** [comment]
So this isn't working because the SecurityCenter wmi namespace doesn't exist on Windows Server SKU's... So far, from googling, it looks like it is not possible to query Antivirus state on Windows Server, in a standard way.  I'm still searching, so I'm open to suggestion, but from the looks of it, I'm not sure I'll be able to fix this...

**Comment by FDrebin** [comment]
I'll tinker around on Monday, see if the data can't be gathered via PowerShell or something.

**Comment by FDrebin** [comment]
Well after 2 days of trying , searching, trying again, and more Googling I can not think of how else to do it...Is there a way to add on to the config of the agent or server component to check for custom services or file paths such as the Symantec service or CrowdStrike service?

**Comment by si458** [comment]
sadly this isnt possible with standard methods,
because as explained above the `SecurityCenter` wmi doesnt exist in Windows Server
so the only method would be to Search all installed products, then loop each product and see if the name matches any of a list of known antiviruses
