### ISSUE TITLE
Ability to change AMT Policy

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#180]
When setting up a user which has "No Intel AMT Access", the user can log in, click on their device group and edit the AMT Policy.

**Comment by Ylianst** [comment]
Yes, I need to fix this.

**Comment by Ylianst** [comment]
Should be fixed in latest version. Let me know if there still an issue.

**Comment by Ylianst** [comment]
Closing this one since it's fixes.
