### ISSUE TITLE
Agent doesn't honor the "background only"  on invite code.

### ISSUE THREAD

**Issue by robclay** [Ylianst/MeshCentral#1801]
I used the following invite code and setting:

![image](https://user-images.githubusercontent.com/19339985/92670709-34273b00-f2da-11ea-89c1-2d1fc68e5a9e.png)

But upon use, the agent seemed to be "Interactive Only."

**Comment by Ylianst** [comment]
Can you provide more details? What agent your trying? Provide steps to make this problem happen?

**Comment by robclay** [comment]
64 bit WIndows

**Comment by Ylianst** [comment]
When you go to the install page and look at the link, what is the "installflags=x" value?

![image](https://user-images.githubusercontent.com/1319013/92815969-a864eb80-f379-11ea-9bc4-5695a128e3e4.png)

**Comment by robclay** [comment]
installflags=1

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
