### ISSUE TITLE
Can meshcentral obtain device power consumption, temperature and CPU utilization through AMT or agent?

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#1802]
Dear All:
Can MeshCentral obtain PC device power consumption, temperature and CPU utilization through AMT or agent?
Is there a plan to achieve it?

Thanks so much!
Billy

**Comment by LFM8787** [comment]
I love this idea! I think the 7 state chart can be used to mark >90% CPU usage in a period of time or even >75°C of internal temperature, for example.

**Comment by jsastriawan** [comment]
While this idea is great, I would prefer to use proper telemetry software such as collectd or Prometheus. Surely we can collect data through WMI and proc filesystem. It is just a matter of adding this capability to meshcore.js and some backend code for storage. However I personally have concern on the resources taken by this task.

**Comment by L422Y** [comment]
@jsastriawan these sensors already exist and are part of most operating system functionality, it should be (is) trivial to add this functionality – even back in the early 2000s this functionality was readily available when I created a monitoring system for interactive installations. i am definitely looking into this to see if maybe i can help. this is really the only thing keeping me from switching to meshcentral

**Comment by L422Y** [comment]
macOS: `sudo powermetrics --samplers smc -i1 -n1`

Linux: 
Temperatures: `cat /sys/class/thermal/thermal_zone*/temp`
Fan speed: TBD... nice to have but not something I need

Windows:
Use WMI: https://stackoverflow.com/a/45736579/887164

**Comment by si458** [comment]
this is already partely implemented,
mac/windows/linux show CPU/memory usage when u click the graph icon,
they also show temperatures of any sensors it can get its hands on
