### ISSUE TITLE
Related to #1688 - Configure Shared system timeout.

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1806]
Can the share timeout be configured in the config.json? Or could the timeout increments be increased to include multiple hours?

1 hour is the current max and we sometimes need up to 8 hours.

**Comment by Ylianst** [comment]
What is "share timeout"?

**Comment by frankmcc** [comment]
I'm speaking of when you share a desktop, the options for creating the link
only allow from 1 minute to 1 hour.  It's based on the share button you
added in issue #1688.

**Comment by frankmcc** [comment]
To further clarify:
![image](https://user-images.githubusercontent.com/26459563/92929144-15c25c00-f40e-11ea-96b1-75b18795728c.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.35 with adjustable max time for desktop sharing. You need to add `"maxGuestSessionSharingTime": 5760` in the domain section of config.json, time is in minutes, default is 60. Let me know if it works.

![MC2-MaxShare](https://user-images.githubusercontent.com/1319013/92981185-a1a7a880-f44d-11ea-8f27-7afc932c5a41.png)

**Comment by frankmcc** [comment]
Perfect!

**Comment by Ylianst** [comment]
Good. Next time, feel tree to close the issue if it works. Thanks.
