### ISSUE TITLE
How are vulnerabilities and patching handled of MeshCentral itself?

### ISSUE THREAD

**Issue by FDrebin** [Ylianst/MeshCentral#1808]
Hello,

I am trying to find out how vulnerabilities are found, addressed, and patched either that exist in MeshCentral itself or in any package(s) that MeshCentral relies on.

I am hoping I am conveying and wording this correctly.

**Comment by Ylianst** [comment]
Hi. MeshCentral is of course an open source project under Apache 2.0 and so, we rely on the community and various scanning tools to find vulnerabilities. As for patching, MeshCentral is posted on NPM with frequent updates (many times a week) and there is an self-update system that many people use and updates the server in 10 to 20 seconds.

Lastly, when you update the MeshCentral server, all agents will reconnect and get updated if needed. The agent is compiled in C and uses OpenSSL so we many sure to keep up with any OpenSSL releases.

Hope that helps,
Ylian

**Comment by FDrebin** [comment]
Thank you so much, this satisfies my needs for the time being, but I may be back. Thank you again.
