### ISSUE TITLE
Documentation Update: Ubuntu 18.04 requires "universe" repo

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#181]
MeshCentral2InstallGuide.pdf
Section 6.1 
Before nodejs and npm can be installed, the universe repository needs to be added to the system.

`sudo add-apt-repository universe`
`sudo apt update`

then the following works

`sudo apt install nodejs -y`
`sudo apt install npm -y`

**Comment by Ylianst** [comment]
Your keeping me busy. I just updated the doc silently (did not change the document version number). Update is here: [http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.6.pdf](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.6.pdf)

**Comment by Ylianst** [comment]
Closing this one since it's fixed.
