### ISSUE TITLE
wget -O meshagent binary installer fails 0.6.35 : 401 unauthorized

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#1811]
Running 0.6.35 when trying the command to download the binary installer (for linux x86_64) it fails with authentification failed:

```
# wget -O meshagent "https://meshcentral.xx.yy/meshagents?id=$zzz&installflags=0&meshinstall=6"
...
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

```

Downloading by clicking on the meshagent binary agent download web dialog "meshagent" works fine and it's the same URL so I assume login cookies checks are not disabled as they should on the download URL.

Suggestion: put linux x86-64 first in the dialog box as it's likely far more common than x86-32 which is currently the default choice :)

**Comment by Ylianst** [comment]
Thanks for the report, I will check this. Also, your right about placing the 64bit Linux agent first, that's a good idea.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.36 with a fix for this. Also, the installer has a few more issues and I made more improvements in this area. Let me know what you think.

**Comment by guerby** [comment]
wget works as does the agent on my test system with 0.6.36,  thanks!

<pre>
wget -O meshagent ...
chmod 755 meshagent
./meshagent -install --installPath=/opt/mesh
</pre>

**Comment by bdasamara** [comment]
Hi,  today i attempted to install mesh agent on 2 devices.  first of the devices installed and connected to the meshcentral device group quickly and without problem.  second device is giving the issue of ":401 unauthorized" and in the meshagent.msh file it says "UnauthorizedStartupType=1".  is there a specific log file to look in to self-help on this?   the device which fails to connect to the meshcentral is Ubuntu 18.04 "server" (headless) OS.
