### ISSUE TITLE
loading devices

### ISSUE THREAD

**Issue by Re9iNee** [Ylianst/MeshCentral#1813]
is there any options to show only last ten connected devices, or recently devices? not all devices in a group.

**Comment by Ylianst** [comment]
Last ten device you connect to? Or last ten that connected to the server? No such feature now, but at the devices page, you can type to filter out devices and can use these options:

`user:` or `u:` to filter devices with a given user logged on the remote device.
`ip:` devices at a given IP address.
`group:` or `g:` for devices within a device group.
`tag:` or `t:` filter devices with a tag.
`atag:` or `a:` filter on agent tag (meshagent.tag file).

In addition, you can right click on a device and "Toggle Star" to mark a device. Then enter * in the filter box to only see stared devices.

**Comment by Re9iNee** [comment]
thanks
