### ISSUE TITLE
connect via entering the computer name

### ISSUE THREAD

**Issue by Re9iNee** [Ylianst/MeshCentral#1814]
I was going to add this option as a personal customization to MC. but before I needed to ask if there was any option similar.

what I'm looking for is something like AnyDesk that in an input box asks for userId ( in MC: Computer-Name) then you can connect to Agents directly. Do we have an option like this? if not how can I implement this correctly?
Thanks in advance.

**Comment by Ylianst** [comment]
Hi. I have never used AnyDesk, so I don't know the details of the feature you are asking for, if you do make a new feature, please submit it as a pull request. Would be great to benefit everyone.

When you are at the devices tab, you can type a computer name and it will filter the devices. You can also use one of the following in your search:

`user:` or `u:` to filter devices with a given user logged on the remote device.
`ip:` devices at a given IP address.
`group:` or `g:` for devices within a device group.
`tag:` or `t:` filter devices with a tag.
`atag:` or `a:` filter on agent tag (meshagent.tag file).

Let me know if that helps,
Ylian

**Comment by Re9iNee** [comment]
Yes Im Working on it, and I'll post some PR. thanks anyway.
