### ISSUE TITLE
Non standard SSH Port support

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#1815]
As a starting port for securing my linix boxes I always change the SSH port and I think this causes MeshRouter generated putty SSH session to not work.

I have tested with a box running on standard SSH port and I can use the router to create the putty session and it works great, but when i try with a host on non-standard SSH port it fails to connect.

AM i correct that this config is not supported right now?

**Comment by Ylianst** [comment]
When using MeshCentral Router and clicking on the "SSH" button, that will assume you are using port 21, the default SSH port. If you are using a different port, just go in the "mappings" tab and create a custom port mapping. You can select the device you want, the port and the application. Once done, you can save your mappings and load them later. Hope that helps.

**Comment by drnikcuk** [comment]
Yup, that does indeed work ... brings me onto the next ssh, but that deserves its own thread 👍
