### ISSUE TITLE
Filter devices by connected?

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1816]
![image](https://user-images.githubusercontent.com/26459563/93114704-e8351700-f688-11ea-8b33-4774e9de226a.png)

A filter checkbox to quickly show which devices currently have active connections?

Now that we are using this more and more people are involved.  It would be nice to see how many current connections there are so  we don't accidentally disconnected them when we want to make changes to the config or upgrade the server.

**Comment by Ylianst** [comment]
Hi. So, the "Online" checkbox just left of your proposed "Connected" checkbox will filter out all non-connected devices. Is this not what you are requesting? Let me know if some changes to "Online" need to be made.

As for current user connections, you can go in "My Server" tab and see the number of user connections and relays sessions. Relay sessions include remote desktop, terminal, files, and TCP/UDP port mapping connections.

As for changing the config.json, it's technically possible for some options to be changed without having the server be reset. This is not implemented now, but something that could be requested.

Hope it helps,
Ylian

**Comment by frankmcc** [comment]
I'm actually looking for devices with open sessions, so I don't interrupt
someone that is working.

**Comment by Ylianst** [comment]
Don't devices with open sessions have a blue icon next to them to show the sessions?

**Comment by frankmcc** [comment]
Yes, however we have upwards of 60 systems and adding more, so it takes a
lot of scrolling and expanding groups to verify activity.

**Comment by frankmcc** [comment]
Having reviewed the current options.  I agree that this is not necessary.  Looking at the current server connections on the server page, addresses the need.   Thank you for the feedback and guidance.

**Comment by Ylianst** [comment]
Well, I built it anyway. I replaced the "online" option with a drop down with many more options. Let me know if this works. Published in MeshCentral v0.6.38.

![MC2-DeviceFilter](https://user-images.githubusercontent.com/1319013/93264934-bab99d80-f75c-11ea-999d-f4a40a443905.png)

**Comment by frankmcc** [comment]
Even better!  It works perfectly!

**Comment by frankmcc** [comment]
Spoke too soon.. Can you add Offline to the list?
![image](https://user-images.githubusercontent.com/26459563/94028244-ba875680-fd89-11ea-9427-bc1af569d45f.png)

**Comment by Ylianst** [comment]
Just added "Offline" filter, will be in v0.6.49.

![image](https://user-images.githubusercontent.com/1319013/94290936-c56bf380-ff0f-11ea-9f52-17f1ad545c73.png)

**Comment by frankmcc** [comment]
Awesome!

**Comment by frankmcc** [comment]
Since adding the MeshCentral Assistant Tray Icon Tool that flags a device as needing help, can this be added to the filter list?

**Comment by cgb** [comment]
Hey Frank, this might already be done?

![image](https://user-images.githubusercontent.com/202961/96056793-07fd6c00-0ecf-11eb-999a-d508a27cfb9b.png)

**Comment by frankmcc** [comment]
You are correct.  I really need to get my glasses checked...

Thanks.  I'll close the ticket
