### ISSUE TITLE
Email Invitation Mac Download Issue

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1818]
There seems to be a problem with the Mac agent download when having the MeshCentral server directly send an email invite. The Windows version link works (though it appears to default to 32-bit) but the Mac link downloads an extension-less file called "meshagent" which, in my testing, does not appear to be a misnamed zip or mpkg file (maybe it's the binary itself?). The Mac download link works as expected if you generate a link invitation and send that instead.

**Comment by Ylianst** [comment]
Can you send the URL link of the mac agent that works and does not work? Do XXXX any private parts of the URL. Thanks.

**Comment by PetieM** [comment]
Not Working: https://XXX/meshagents?id=16&meshid=XXX&tag=mailto:XXX&installflags=0
Working: https://XXX/meshosxagent?id=16&meshid=XXX

So it looks like the email invite needs to use meshosxagent instead of meshagents?

**Comment by Ylianst** [comment]
Oh! Thanks. That was super helpful. Let me look into this now.

**Comment by Ylianst** [comment]
Fixed, should be in MeshCentral v0.6.39 when next published. Thanks for reporting this.

**Comment by PetieM** [comment]
Confirmed fixed for Mac downloads. Windows still defaults to 32-bit though - is that intentional?

**Comment by Ylianst** [comment]
Can you send a screenshot of where it defaults to 32but? Thanks.

**Comment by PetieM** [comment]
Screenshot attached. That was the result of clicking the Windows agent link in Chrome on Windows 10 x64.

![32-bit Download](https://user-images.githubusercontent.com/16453878/93499468-44d64300-f8d0-11ea-8942-e64606874b98.png)

**Comment by Ylianst** [comment]
Your screenshot is of no help, I want to know where you got the link from.

**Comment by PetieM** [comment]
Oh, completely misunderstood what you needed to see. The link came from the same invite email that the broken Mac link came from originally. Hopefully this one is what you needed:


![Email](https://user-images.githubusercontent.com/16453878/93509849-8caf9700-f8dd-11ea-9c77-5273107f09b3.png)

**Comment by Ylianst** [comment]
Oh! Got it.

**Comment by Ylianst** [comment]
Fixed, it will be in MeshCentral v0.6.41.

**Comment by PetieM** [comment]
Confirmed fixed on v0.6.41. Thanks!
