### ISSUE TITLE
Question about the repos and a router issue

### ISSUE THREAD

**Issue by cookta2012** [Ylianst/MeshCentral#1819]
Yilanst I have opened issues on the router repo, should I open them here instead. I'm confused.

**Comment by cookta2012** [comment]
The router remote desktop seems only to work when logging in directly in the router, if I "launch meshrouter" from meshcentral it will not allow remote control, but I can use port mapping

**Comment by Ylianst** [comment]
If the bug has to do with MeshCentral Router, you should open the issue on the [MeshCentral Router GitHub](https://github.com/Ylianst/MeshCentralRouter/issues). This said, I just published MeshCentral v0.6.39 that includes a fix for this. If it works for you, please close this issue. Thanks.
