### ISSUE TITLE
Keep track of remote desktop connections

### ISSUE THREAD

**Issue by elric72** [Ylianst/MeshCentral#182]
Hi,

Is there a way to fire an event to keep track of remote desktop connections like it is done to every actions (create a user, login to the app, ...) ?

Thank you in advance for your answer
Regards
David

**Comment by Ylianst** [comment]
That is a good request, I need to add that. There is no events or logs right now, but needs to be added.

**Comment by SomeGuru** [comment]
@Ylianst,

This is implemented as of late no? 

SomeGuru

**Comment by dinger1986** [comment]
@si458 this has been implemented, please close

**Comment by si458** [comment]
indeed, this will show in the events as `Started Web-RDP session` and `Left Web-RDP session after X seconds`
