### ISSUE TITLE
Data Base File (.db) high space usage

### ISSUE THREAD

**Issue by BDMarty** [Ylianst/MeshCentral#1820]
Hi,

Recently I started using Mesh Central, but I've come across some computers having abnormal disk usage. Upon inspection I have found this: https://imgur.com/a/it8IGvD

I have also found one which was 60 and other 80 GB.

Could anyone assist as to why this is happening?

**Comment by krayon007** [comment]
Are you using any plugins?

**Comment by Ylianst** [comment]
This is almost certainly due to badly behaving plug-ins. Let us know what plug-ins you have installed. Thanks.

**Comment by BDMarty** [comment]
Thanks for the reply guys. I am using the following plugins:Event Log - File Distribution - ScriptTask -Work From Home

**Comment by Ylianst** [comment]
So, one of these plugins is causing the issue. Sadly, we can't help with that, plugin's are not built by us. You can stop the agent, delete the meshagent.db file and start the agent again. The computer may show up as a new device on the website.

**Comment by ryanblenis** [comment]
Hi @BDMarty ,

I made all those plugins. Hope you're enjoying them beyond this issue you're experiencing!

1. Are you on the latest version of each?
2. What server version?
3. What client OS is that endpoint?
4. After clearing the DB (if you did already) once it starts to grow a little again, send me a compressed copy of the file and I can see what's causing it.

Thank you.
