### ISSUE TITLE
Intel AMT Issue

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#1821]
Hi 

Struggling with getting AMT to connect in a particular scenario.

Intel vPro has been setup to have a local static IP. i.e. 192.168.1.10. However once an OS is installed this will get a DHCP address,which is independent of the vpro ip which remains as set statically.
In my test setup the MeshCentral Server (latest version) is 192.168.1.9, so there in the same subnet

Current Setup which works:
Device Group: Intel® AMT only, no agent
I can successfully connect to the machine using vpro

If I set a group using Manage using a Software Agent. I can successfully connect to the machine using the Agent, however I cannot use the connect to Intel AMT function, as from the General Tab, the IP address under hostname is the DHCP address of the OS. If I update the IP from the general tab > Hostname to 192.168.1.10 this works temporarily and allows me to connect with both agent and AMT, but if the OS is rebooted, this IP reverts back to i.e. the DHCP address 192.169.1.50

Is there a way that I can set the vPRO ip on the console. 

I'm trying to use one group to manage the machine rather than having to use a separate one for vPRO and one for the Agent.

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
