### ISSUE TITLE
Cross-origin frame issues

### ISSUE THREAD

**Issue by chatu** [Ylianst/MeshCentral#1822]
I'm running MeshCentral behind NGINX as per the [user guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf) directions (NGINX Reverse-Proxy Setup) however, I get "X-Frame-Options" and cross-origin frame errors.

<img width="857" alt="meshcentral" src="https://user-images.githubusercontent.com/556297/93369876-db3d3280-f804-11ea-9aac-038981955448.png">

I haven't tested all features but timeline is not available on Chrome (Desktop connection works fine) and nothing loads on Safari (including macOS and iOS).

<img width="856" alt="meshcentral1" src="https://user-images.githubusercontent.com/556297/93370780-36bbf000-f806-11ea-81cf-d9b621e6f912.png">

**Comment by Ylianst** [comment]
Seems like you NGINX is adding another "X-Frame-Options" in the HTTP response header on top of the existing one. The browser will see two of them and ignore both causing the problem. Your going to have to look at your NGINX configuration to fix this.

**Comment by chatu** [comment]
Thanks for the quick response. You are absolutely right, My NGINX configuration was adding another "X-Frame-Options" in the HTTP response header on top of the existing one.
