### ISSUE TITLE
Computers Missing

### ISSUE THREAD

**Issue by Electricity2015** [Ylianst/MeshCentral#1825]
The computers dosen't show up on grups ,
I searched on database to see if there exist and there are. 

What to do?

**Comment by Electricity2015** [comment]
Sorry it was my mistake ,i was filtering the computers by "n" but I didn't know I put the filter on .

![image](https://user-images.githubusercontent.com/8312565/93449952-09427580-f8de-11ea-84fa-e7c3a2a02a58.png)

I restarted the server several times and the filter still was applied

**Comment by Ylianst** [comment]
If you hit the "ESC" key, it will also clear the filter.
