### ISSUE TITLE
after upgrade to 0.6.39 -> mc crash with critical error -> cannot read proberty... 

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#1826]
![image](https://user-images.githubusercontent.com/56296924/93457709-9fc36680-f8df-11ea-9e8f-e29cb2a5ea3f.png)

any idea what we make wrong?

thanks for help

**Comment by wvt-adm** [comment]
node update to 12.18.4 we have make...

**Comment by southeasterntech** [comment]
-------- 9/17/2020, 10:31:51 AM ---- 0.6.39 --------

c:\meshcentral\node_modules\meshcentral\webserver.js:727
        if (token.startsWith('cookie=')) {
                  ^

TypeError: Cannot read property 'startsWith' of undefined
    at checkUserOneTimePassword (c:\meshcentral\node_modules\meshcentral\webserver.js:727:19)
    at c:\meshcentral\node_modules\meshcentral\webserver.js:937:21
    at c:\meshcentral\node_modules\meshcentral\webserver.js:599:36
    at AsyncWrap.<anonymous> (c:\meshcentral\node_modules\meshcentral\pass.js:31:88)
    at AsyncWrap.wrap.ondone (internal/crypto/pbkdf2.js:36:48)


===========================================

Note Same problem on node 14.11.0
NOTE:  Upon Pressing Login, Crash and above error is generated in:
-Chrome
-Edge
-Firefox

DOES NOT OCCUR:
-Opera

**Comment by jsastriawan** [comment]
It looks like a bug. It should be:

if (token!=null && token.startsWith('cookie=')) {


it seems we need to work better on sanitizing the code from null or undefined variables more.

**Comment by Ylianst** [comment]
Exactly. Just rolled back to v0.6.38 until I can fix this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.40 with a fix for this.

**Comment by southeasterntech** [comment]
Seems to be working now on .40!  thanks guys

**Comment by wvt-adm** [comment]
works - thanks a lot! great work!
