### ISSUE TITLE
Two step authentication

### ISSUE THREAD

**Issue by multiflexi** [Ylianst/MeshCentral#1828]
Hi,
after I log in to MeshCentral the web dies - Server Not Found. I activated 2-pass authentication and that is when it happened. I have more secure installation in /opt/meshcentral. I use Debian Buster and node 12.18.4 LTS. How can I fix this or disable 2-pass auth?

Log: 
![Screenshot from 2020-09-17 14-51-52](https://user-images.githubusercontent.com/11663844/93473035-ca201e80-f8f5-11ea-838b-b2dd85cb051d.png)

**Comment by truncat** [comment]
Hello!

I have the same issue. You can disable 2FA for specific account with:

`node ~/node_modules/meshcentral --resetaccount $USERNAME --pass $NEW_PASSWORD`

**Comment by 8aXaJzvh** [comment]
Disabling 2FA allows access back into the account. Re-enabling 2FA causes the issue to occur again.

**Comment by Ylianst** [comment]
Just rolled back to v0.6.38 because of this bug. Will fix ASAP.

**Comment by Ylianst** [comment]
MeshCentral v0.6.40 published with a fix for this.

**Comment by 8aXaJzvh** [comment]
Working after the update. Thank you.
