### ISSUE TITLE
Editing Remote installation pages to add instructions for MAC

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1829]
So we are running into this issue with MACs that require the end user to add the mesh agent to Accessibility in the Security and privacy settings.  It would be nice to add instructions for this on the Remote installation page, so we do not have to coach them each time.  I know that we can create a ~/meshcentral-web/public_html and place files we want to change there, but this does not seem to work when creating the ~/meshcentral-web/views and copying the agentinvite.handlebars to this location.  Edits just don't seem to have any effect.

Am I editing the wrong file or doing something wrong?

Attached is a word Document with what we want to accomplish.
[Setup Mac with MeshAgent.docx](https://github.com/Ylianst/MeshCentral/files/5239929/Setup.Mac.with.MeshAgent.docx)

**Comment by Ylianst** [comment]
This is an excellent idea. I have been asking Bryan for a while to provide me to screen shots on macOS to add such instructions. I imagine you would like the instructions to be added to this screen?

![image](https://user-images.githubusercontent.com/1319013/93558902-4dac3080-f933-11ea-9129-b12721192ea9.png)

Can you send me another word document (or .zip file) with clean screen shots? If possible use as much as possible the default macOS look (no night mode). I will use your graphics and create an instruction page and add it to the next release. - Thanks.

**Comment by frankmcc** [comment]
Yes, Ylianst,

That is the screen we are talking about.  I will get clean screenshots
or you within a day or two.

Thanks again for your hard work and dedication to this project!

**Comment by frankmcc** [comment]
Updated Mac instructions.  

[Setup Mac with MeshAgent.docx](https://github.com/Ylianst/MeshCentral/files/5372711/Setup.Mac.with.MeshAgent.docx)

**Comment by si458** [comment]
we have multiple options for mac os 14 or less now,
MPKG which you run and install
OR
the binary tab ro use the binary file instead which has instructions
