### ISSUE TITLE
upload and add agent not functional

### ISSUE THREAD

**Issue by bberz** [Ylianst/MeshCentral#183]
Hello,
First of all, congratulations for the quality of your work.
I installed meschcentral on a web server already running (seven pro iis 7.5).
I redirected the https url to meschcentral and I can connect to it from the Internet (windows 10 chrome) where I can create a device group but I encounter the error "Unable to download agent." when I want to add the agent.
On the server I tried to upload meshagent.exe without result (no error).
No log reports these errors in the MeshCentral subfolders.
By copying meshagent.exe by teamviewer I was able to install the agent and the desktop works.
Does file transfer require port forwarding? 
How can I help to analyze the problem?
Thank you in advance

**Comment by Ylianst** [comment]
Hi. Type this link on your server:

`https://servername.sample.com/meshagents?id=3`

It should download the agent. If not, probably some HTTP routing issue.

**Comment by bberz** [comment]
thank you so much
My problem was the redirect rule
cordially
