### ISSUE TITLE
Ubuntu node not visible after meshagent reinstall

### ISSUE THREAD

**Issue by sheruvs** [Ylianst/MeshCentral#1837]
I had installed a meshagent from a test MC (ver 0.6.24) server onto a Ubuntu 18.04 64b desktop system. This was visible on the test MC. Uninstalled the meshagent, then when I installed an agent from the production MC server (ver.0.6.39), the Ubuntu system is not visible in MC Device_Group. 
Tried uninstalling and reinstalling, but of no avail. 

Interestingly, a Windows system that I had tested under exactly the same circumstances is visible on the production MC. Also, another Ubuntu system (18.04 64b server) onto which I installed the meshagent, becomes visible in MC (no agent was installed on this system earlier).

I read in one of the posts, to test by enabling "ignoreagenthashcheck": true, in config.json, but no improvement after trying this out. Where are the MC logs stored? 

Any idea how to go about sorting this out? 
Thanks in advance.

**Comment by krayon007** [comment]
If you first stop the agent:
`systemctl stop meshagent`
then navigate to the installation folder, usually `/usr/local/mesh_services/meshagent`
and then manually run the agent in console mode:
`./meshagent`
you should see what the agent is doing via the display messages... Can you post back what it is doing?

**Comment by sheruvs** [comment]
Thanks for getting back, krayon007.
Just tried as you suggested. It appears that meshagent is unable to open the db. 

> netops@netops-Latitude-5580:/usr/local/mesh$ ./meshagent
Unable to open database (1/10)...
Unable to open database (2/10)...
Unable to open database (3/10)...
Unable to open database (4/10)...
Unable to open database (5/10)...
Unable to open database (6/10)...
Unable to open database (7/10)...
Unable to open database (8/10)...
Unable to open database (9/10)...
Unable to open database (10/10)...
Unable to open database.
netops@netops-Latitude-5580:/usr/local/mesh$

Tried uninstalling and reinistalling the meshagent from prod MC, still the same issue.

**Comment by sheruvs** [comment]
Sorry, while posting, accidentally deleted the issue. Reopening it...

Thanks for getting back, krayon007.
Just tried as you suggested. It appears that meshagent is unable to open the db.

netops@netops-Latitude-5580:/usr/local/mesh$ ./meshagent
Unable to open database (1/10)...
Unable to open database (2/10)...
Unable to open database (3/10)...
Unable to open database (4/10)...
Unable to open database (5/10)...
Unable to open database (6/10)...
Unable to open database (7/10)...
Unable to open database (8/10)...
Unable to open database (9/10)...
Unable to open database (10/10)...
Unable to open database.
netops@netops-Latitude-5580:/usr/local/mesh$

Tried uninstalling and reinistalling the meshagent from prod MC, still the same issue.

**Comment by krayon007** [comment]
When you run it from command line, do it with sudo, because the DB needs root to open for RW.

**Comment by sheruvs** [comment]
OK, thanks for update.. This is the o/p

> netops@netops-Latitude-5580:/usr/local/mesh$ sudo ./meshagent
[sudo] password for netops: 
No MeshCentral settings found, place .msh file with this executable and restart.

**Comment by sheruvs** [comment]
Just compared the meshagent.msh files in a working node against this problematic system. Found that this Ubuntu desktop's meshagent.msh had only one line 

> UnauthorizedStartupType=1

whereas the other working system's  .msh file had a whole lot of stuff - MeshName, MeshType, MeshID etc..
Copied all that and Bingo! its working now and I can see the node on the prod MC system.

Thanks a lot, for pointing towards the right direction, krayon007.

You guys are awesome for developing, maintaining and supporting such a mindblowing software!
