### ISSUE TITLE
Intel AMT options Grey

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#1839]
I'm sure I've asked this before but I don't remember if this was ever solved. I have Mesh Central 2 running behind a reverse proxy in a virtual box environment on my Dell Server at home (it's running on Ubuntu 18), The main operation system is Windows 10 professional and I have the Mesh Central 2 client installed on Windows 10. Everything is working as intended but on my Intel Amt machine (the dell server I just mentioned) shows Intel ME Activated 12.0.40 but on the Desktop Tab HW connect is greyed out and also in the Intel AMT tab connect is greyed out as well (I did enter credentials as well, I know they work because I can connect with mesh commander). On the Desktop tab  HW connect is grey and the intel amt information connect is grey. I also tried using cira (showed up in mesh central after a reboot but didn't show any intel amt options and hw connect looked like it was working but only connected to a black screen), cira worked as well but just like you said in your video removes it from mesh commander (where my dell server is the mesh central server, if it drops offline I would have no way to get back in :) so I removed cira and just went back to mesh commander for now). Hope that makes sense...

Dell Server (Intel AMT)
OS is Windows 10 (has the client installed from my Mesh Central 2 Virtual box server, detects AMT but can't use the features).
Has two virtual boxes installed and forwarded to my LAN one of them has the Mesh Central 2 server on it, so I don't use cira in case of a power outage or a windows update, that way I can still get in via mesh commander.

**Comment by dinger1986** [comment]
@si458 unanswered, 4 years old. Id answer it but dont know the answer myself

**Comment by si458** [comment]
the was a recent fix for intel amt and newer node js versions, please try updating and still see if your having issues,
if you are please feel free to reply/re-open but closing as stale
