### ISSUE TITLE
add remote CLI access for AMT powerstates or SSH option?

### ISSUE THREAD

**Issue by babbahotep** [Ylianst/MeshCentral#184]
Hi, I am trying to remote power up a AMT PC. (HP 600 G2) via the command line.
I found amttool & amtterm but they dont seem to work any longer.

Would it be possible to add the simple power commands to meshcommander firmware?
Or add shh access to ssh into the machine and poer it up from there?

info            - print some machine info (default).
reset           - reset machine.
powerup         - turn on machine.
powerdown       - turn off machine.
powercycle      - powercycle machine.

best regards
Chris

**Comment by Ylianst** [comment]
Well, the way to do a command line Intel AMT power up would be to do it using MeshCMD.exe. That executable does a bunch of things right now, but now power actions. I would need to add that in. I am really busy these days, but at some point that is a good request. If you have something else in mind, let me know.

**Comment by si458** [comment]
this is currently now possible using the meshcmd.exe
download it from your web UI, copy it to the remote machine,
run `meshcmd.exe AmtPower --user admin --pass theamtadminpassword`
help docs for it
```
simon@testmc:~/meshcentral$ ./meshcmd help AMTPower
AmtPower will get current pwoer state or send a reboot command to a remote Intel AMT device. Example usage:

  meshcmd amtpower --reset --host 1.2.3.4 --user admin --pass mypassword --tls

Required arguments:

  --host [hostname]      The IP address or DNS name of Intel AMT.
  --pass [password]      The Intel AMT login password.

Optional arguments:

  --reset, --poweron, --poweroff, --powercycle, --sleep, --hibernate
  --user [username]                                    The Intel AMT login username, admin is default.
  --tls                                                Specifies that TLS must be used.
  --bootdevice [pxe|hdd|cd|ider-floppy|ider-cdrom]     Specifies the boot device to use after reset, poweron or powercycle.
  --bootindex [number]                                 Specifies the index of boot device to use.
```
