### ISSUE TITLE
Trying to update json file, I am new to this 

### ISSUE THREAD

**Issue by dkhan717** [Ylianst/MeshCentral#1844]
Hi this might be something very simple, I apologize in advance 
When I try to test the new feature to expand the time limit for sharing using config.json file and update it, after that it will stop the server service automatically in few seconds. 

This is my current config that works, but if I add the value "maxGuestSessionSharingTime": 5760, under domain section it will stop the service from running. 

```
{
   "settings": {
      "lanonly": true, 
      "_minify": true, 
      "webrtc": true, 
      "allowframing": true, 
      "allowlogintoken": true
   }, 
  "domains": {
      "": {
         "title": "My Company ", 
         "title2": "Title Demo", 
         "footer": "ALL RIGHTS RESERVED ", 
         "newaccounts": false
      }
   } 
}
```

If possible can you give me example of how I should put it in my current configuration, I appreciate your work and product it is amazing

Thank You,
Dan

**Comment by Ylianst** [comment]
No worries, good question. In general the JSON format was not intended for human's to edit, it's more of a good software to software type of format so you are not alone feeling this way. If you get into any issues, you can using the [DuckDuckGO JSON Lint page](https://duckduckgo.com/?t=ffnt&q=json+lint&ia=answer) to check that your JSON is formatted correctly. Of course, I would remove any secrets from the JSON before doing any such validation on any web page. Anyway... The nice thing it, it will tell you if and where any problems are.

In your case, all you need to do is this:

```
{
   "settings": {
      "lanonly": true, 
      "_minify": true, 
      "webrtc": true, 
      "allowframing": true, 
      "allowlogintoken": true
   }, 
  "domains": {
      "": {
         "title": "My Company ", 
         "title2": "Title Demo", 
         "footer": "ALL RIGHTS RESERVED ", 
         "newaccounts": false,
         "maxGuestSessionSharingTime": 5760
      }
   } 
}
```

Note that command at the end of each line. It's not present at the end of the last line of a { } block. If you where to add it like this, it would not work:

```
{
   "settings": {
      "lanonly": true, 
      "_minify": true, 
      "webrtc": true, 
      "allowframing": true, 
      "allowlogintoken": true
   }, 
  "domains": {
      "": {
         "title": "My Company ", 
         "title2": "Title Demo", 
         "footer": "ALL RIGHTS RESERVED ", 
         "newaccounts": false,
         "maxGuestSessionSharingTime": 5760,        <---- Extra comma
      }
   } 
}
```

Hope that helps.

**Comment by dkhan717** [comment]
Worked perfectly and thank you for this explanation, I will try to learn more on this and again thank you for all that you do for us, hope we can somehow contribute to your efforts. I use it for a very different purpose, I use it inLMS system and teach IT skills, once I have the project completed, I will share use case with the community here. 

Thank you,
Dan
