### ISSUE TITLE
Cannot lock user account

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1846]
A bit of prehistory - I had an Admin account long time ago, and after lots of changes in MC, especially after adding an option  "ManageAllDeviceGroups": [ "admin","admin2" ], I have started using an Admin2 account. Using Admin2 account I locked Admin account and removed all Administrator rights(because cannot change it's login name)- which is fine
![image](https://user-images.githubusercontent.com/59362521/94122299-4a8cd500-fe4a-11ea-887d-5e65bfd7d376.png)

However, now - using Admin2 account i have some problems with rights.
1. Admin2 cannot lock any other account, when choosing option to lock account for some user(s) and clicking OK, nothing happens.
2.  When trying to add more groups to Admin2, and clicking OK, nothing happens - does not show in Common Device Groups
![image](https://user-images.githubusercontent.com/59362521/94122738-d7379300-fe4a-11ea-83da-84ea692cca3e.png)

I think that originally created Admin account on MC when installing and running on first run have more rights and working much better than any other Admin account created on later stage. Any chance to compare those rights for Admin users?!?!?

MC - 0.6.42 (did not go yet to 0.6.48 as there was some update issues :) )
DB - NeDB
OS - Debian Jessie
Node - v10.16.2
NPM - v6.13.4

**Comment by Ylianst** [comment]
Interesting, I will take a look at this when I get a chance. Both admin and admin2 accounts should work the same way.

**Comment by vitko-bg** [comment]
A bit more info to help you with problem solving:
Admin(created on MC installation and used on MC before Admin 2 creation) looks like this:
![image](https://user-images.githubusercontent.com/59362521/94248097-e6cfde00-ff15-11ea-85f1-5035e615d773.png)

And Admin 2 (created on later stage):
![image](https://user-images.githubusercontent.com/59362521/94248319-36160e80-ff16-11ea-811d-8e51afe813a0.png)

One group which shows under Admin2 is created by Admin2 user.....

Also most of other users are created by Admin user at the beginning, so that why probably Admin2 does not have rights to lock them. However, because Admin2 is Full Administrator I think it should be able to to have full rights everywhere ....

**Comment by vitko-bg** [comment]
@Ylianst - important update - just made some more tests, and actually Admin2 cannot lock accounts on other subdomains.....
I have couple of them...... My main one is remote.domain.com, and rest of them are office1.domain.com, office2.domain.com, etc.
Also - updated MC to latest current version 0.6.48

**Comment by Ylianst** [comment]
1. On the account locking part. Locking a user account requires that you have "Manage Users" server rights. If you want to manage users across domains, you need to be full administrator and have the following in the settings section of the config.json:

```
    "ManageCrossDomain": [
      "user//admin2"
    ]
```

This will allow "admin2" to see all users across domains in the "My Users" tab and perform account lock/unlock. Let me know if that works. If you don't have this, "admin2" should not be able to see any users across domains.

2. So for adding more device groups. First, you can't add device groups across domains, device groups can only be used within a domain. Next, the "Add Device Group Permission" will not create a new device group, but grant access to an existing one. If you want to create a new device group for a user, you need to create a new group using the "Add Device Group" link in the "Devices" page and then add the user to it.

Let me know if that helps. I did some testing on my side and did not see anything unexpected, but maybe I need to improve things.

**Comment by vitko-bg** [comment]
Hi @Ylianst - thanks for explanations, all seem rights on my side. Please see below:
1. I do have option in config.json in settings section the following line
 "ManageCrossDomain": [ "user//admin","user//admin2" ] - that why I can see all users for all subdomains, otherwise I won't be able to see them. However, locking accounts(on other domains) using "admin2" still does not work.
2. In regards to groups - on my first post I meant adding groups from a main domain to Common Device Groups to "admin2" - nothing related to subdomains. Possibly I explained it incorrect on first post, sorry. If you will check both screenshots below - you can see the difference between "Admin" screen, and "Admin2" screen:
Admin
![image](https://user-images.githubusercontent.com/59362521/94343082-950a7f00-000d-11eb-9e32-f207cf69ee75.png)

Admin2 (created on later stage)
![image](https://user-images.githubusercontent.com/59362521/94343088-a3589b00-000d-11eb-9f76-5d8cffb92652.png)

"Admin2" can see all groups and interact with them on main screen, but in users screen, looks like "Admin2" have only 1 group.

Shall I split both issues 1. and 2. so not to have any confusion?

Thanks.!

**Comment by vitko-bg** [comment]
Closing issue now, as solved the problem by creating a new groups using Admin2 account and moving all devices into a newly created groups. It took some time :) as ~75 groups was recreated :)
