### ISSUE TITLE
CentOS 8 blank screen desktop

### ISSUE THREAD

**Issue by uhofemeier** [Ylianst/MeshCentral#1847]
Hi Ylian and team,

I just created a new group on meshcentral.com and added two QEMU VMs running CentOS 8 with Gnome 3.28, which uses Wayland as a display manager. I added both systems using using the wget + script execution copy and paste method provided through the website. 

Both systems show up in meshcentral.com but when I try to connect the desktop remains blank.

I must get this to work since I plan to use 30 VMs to host an AI/ML workshop soon.

Hope you can help :)

Thanks,
Ulf

**Comment by krayon007** [comment]
The remoting technique we use on linux does not support Wayland. Here's the comments I added about how to get this working:

```
 Special Note about KVM Support on Linux: 
    If you get an error stating that an Xauthority cannot be found, and asking if your DM is configured to use X, 
    or if you get a black screen when connecting to the login screen, you may need to: 
    1. Open /etc/gdm/custom.conf or /etc/gdm3/custom.conf
    2. Uncomment: WaylandEnable=false.
    3. Add the following line to the [daemon] section:
       DefaultSession=gnome-xorg.desktop
```

**Comment by krayon007** [comment]
Let me know if you still have issues. My CentOS test systems are CentOS 5.11 and CentOS 7, but I can setup a CentOS 8 system if necessary.

**Comment by uhofemeier** [comment]
Thank did the trick. Thanks!
