### ISSUE TITLE
When creating a new device group, the device group length can be 64 characters, however, when renaming the same device group, the field length is limited to 32 characters

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#1849]
# Problem Description
When creating a new device group, the device group length can be 64 characters, however, when renaming the same device group, the field length is limited to 32 characters.

# Environment
## MeshCentral Server
**Version:** v0.6.48
**Server OS:** Ubuntu 18.04.4 LTS

## Physical Host
**OS:** VMware ESXi 7.0.0 (16324942)
**CPU:** 4 CPUs x Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
**Memory:** 24 GB

# Replication
1) Create a device group with the name "a123456789b123456789c123456789d123456789e123456789f123456789g123" (64 characters)
2) Attempt to rename the device group to "g123456789f123456789e123456789d123456789c123456789b123456789a123" (64 characters, but backwards)
3) Observe that the device group field only allows up to "g123456789f123456789e123456789d1" (32 characters)

# Ask 
1) Is it possible to have the new device group character length and rename device group character length in sync?
2) Is it possible to **increase** the number of characters allowed for new or rename operations to 128 or 256? (I understand that the remote ID is based off this, so it may not be possible)

**As always, thanks for all your hard work and amazing software.**

**Comment by Ylianst** [comment]
Oh! Good report (as usual). Thanks for noticing that. I will fix this next time I get a chance.

**Comment by Ylianst** [comment]
Just fixed this and changed the max length 128 characters. It's starting to be a long name and some of the web pages and tools may need to be changed to handle this length.

**Comment by darryl-h** [comment]
**Super quick fix, Thanks, yew da best. :)** 

Do we know what version this fix will be in? I will test once I can update my local version to it and report back.

**Comment by Ylianst** [comment]
Oh right. I forgot to write that, it will be in MeshCentral v0.6.49 when next published.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.49

**Comment by darryl-h** [comment]
## Resolution
Tested in 0.6.49 and works **exactly** as you described.

## Testing
- Renaming groups, now able to rename old group to 64 characters instead of 32.
Example:
`g123456789f123456789e123456789d123456789c123456789b123456789a123`

- Creating a new group works to 128 characters 
Example: `a123456789b123456789c123456789d123456789e123456789f123456789g123456789h123456789i123456789j123456789k123456789l123456789m1234567`

- Renaming the same new group backwards to 128 characters works as expected
Example: `m123456789l123456789k123456789j123456789i123456789h123456789g123456789f123456789e123456789d123456789c123456789b123456789a1234567`

**As always, thanks for the super quick fix, much appreciated!**

Closing Request.
