### ISSUE TITLE
Assigned device group on user edit

### ISSUE THREAD

**Issue by sorvani** [Ylianst/MeshCentral#185]
I would love to be able to assign device groups to a user form the user edit screen.
![image](https://user-images.githubusercontent.com/3302372/56084990-93d99800-5e01-11e9-935a-3841a302f0e9.png)

**Comment by Ylianst** [comment]
Good request. I am busy with plenty of other requests right now, but will get to this at some point.

**Comment by dinger1986** [comment]
AMT unlikely to be implemented

**Comment by dinger1986** [comment]
sorry wrong comment on here @si458 but this looks to be done
![image](https://github.com/Ylianst/MeshCentral/assets/7244447/21ab759a-efb4-4dc2-a6f0-a10765e067d4)
