### ISSUE TITLE
Devices subgroups

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#1850]
Hi!
What would be the best approach generate "folders" or "groups" inside the current device groups?

For example, if I have a device called "Client1", and I want to create groups or folders named "1st floor", "2nd floor", etc.

I thought about the Agent Tags (especially with the last update, that allows you to use multiple tags) but the limit this way is I only can filter the devices by group, OR by tag. So I cant really see a group with its consequential subgroups or tags.

For example: If I have a "Client1" and a "Client2", and both of them have a "1st floor" folder or tag, when I just filter by tag, i will se two devices under that one, even when the don't belong to the same client.

Anyway, I was just wondering if there is a more "organized" way to achieve this. Thanks!

**Comment by Ylianst** [comment]
Just added a "Group-Tags" sort option. This will be in v0.6.48. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/94293660-7c1da300-ff13-11ea-8efb-59614d848207.png)

**Comment by yomono** [comment]
Damn!! Sometimes I can't believe how fast you bring solutions. Can't thank you enough

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.49 :)
