### ISSUE TITLE
[bug] 6.49 Refresh stops working after selecting sort option Group-Tags

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#1854]
This morning I'm trying to logon but I get no agents showing.  I had them at first but then after clicking on the new Group Tags filter, they disappeared.  It seems to be linked to my account somehow, since none of my users are complaining.  I've tried on multiple browsers on multiple machines.  No Joy.  One thing in common is that my sort goes to Group Tags on every machine I logon to.  I had a tech logon to my computer and they did not experience this problem.  So I tried to duplicate what I did to recreate the problem with a different account and was not able to reproduce it.  

I'm checking my account in the database now.....

**Comment by frankmcc** [comment]
Found //wuser/[username] in the meshcentral database [id] edited the sort option from 4 to 0 in the [state] field and then refreshed my page.  Viola, they are all back.   

So I tried again and found that I can duplicate the problem by typing something in the filter then sorting by Group-Tags where none of the tags match the filter.  This results in a blank page.  However this is not the problem only a symptom.  

Further testing indicates that the problem is that the refresh quits after selecting the Group-Tags in the Sort box.  any attempt to switch the sort to anything else does not work.. each time I must go into the database and edit the sort option to anything but 4 and my page comes back.

**Comment by Ylianst** [comment]
Looking into this now!

**Comment by Ylianst** [comment]
I am trying to make this problem happen with no luck on my part. Can you open the browser console and tell me if you see any errors when your refresh gets stuck? On Chrome, you open it in the "Developer Tools" or "Ctrl-Shift-i". Thanks.

![image](https://user-images.githubusercontent.com/1319013/94459265-f5afce00-016b-11eb-839e-34f8df5c6574.png)

**Comment by frankmcc** [comment]
(index):46 Uncaught TypeError: Cannot read property 'name' of undefined
    at updateDevices ((index):46)
    at (index):46

**Comment by Ylianst** [comment]
Ha! That helps a lot. Taking a look now.

**Comment by Ylianst** [comment]
Turns out that if you shared individual devices, the "Group-Tag" sort would cause this error. Published MeshCentral v0.6.50 with a fix for this. Let me know if it works.

![image](https://user-images.githubusercontent.com/1319013/94489363-28bc8680-0199-11eb-945a-206709aebcfa.png)

**Comment by frankmcc** [comment]
Seems to be working ok now.  Thanks!
