### ISSUE TITLE
Feature Request: Session Recording for Specific Device Groups

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#1855]
Our MeshCentral server is used both for connecting to customer sites using one specific device group, as well as for employees to set up personal device groups for their own machines and uses. As far as I can tell, server-side recording applies to all sessions regardless of device group. For us, we only care about recording sessions where we are connecting to customer machines for remote troubleshooting and would like to disable recording for other device groups for privacy and space saving reasons. Would this be possible?

**Comment by Ylianst** [comment]
Ok, I just added support for this in MeshCentral v0.6.52. You can add `"onlySelectedDeviceGroups": true` to `SessionRecordings` and you will have a new feature option in the device group. Let me know if it works.

![MC2-SelectiveSessionRecordings](https://user-images.githubusercontent.com/1319013/94624340-114dce00-026b-11eb-8acb-c43f7c1bac1e.png)

**Comment by MatinatorX** [comment]
Wow, that was quick. Just tested it out and it works great! Thanks!
