### ISSUE TITLE
Bug: MeshRouter Option to Remember Token for 30 Days Disappears if Incorrect Token Entered

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#1856]
Minor issue as described in the title. Using Windows 10, latest version of MeshRouter. Clicking "Back" and then "Login" causes the checkbox to reappear.

Absolutely love the new file manager by the way.

**Comment by Ylianst** [comment]
Your right, just checked in the fix for this. It will be in MeshCentral v0.6.51. The problem is server-side, but I also updated MeshCentral Router's handling of `?key=pass` when an invalid 2FA token is entered.

**Comment by MatinatorX** [comment]
Confirmed fixed on v0.6.53. Thanks!
