### ISSUE TITLE
ClickOnce fail if WinSCP already running

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#186]
MeshCentral 0.3.2-m.
ClickOnce can only one WinSCP connection at one time. If you run second ClickOnce WinSCP connection (to the same agent or another) it will fail after 1-2 seconds after successful WinSCP login.
It looks like MeshMiniRouter.exe die after successful WinSCP login to second and subsequent server (because WinSCP run multiple connections in one window?).
Tried WinSCP 5.9.5 and latest 5.15.1.
Putty and RDP works fine. WinSCP via MeshCmd works fine too. Error only with MeshMiniRouter and WinSCP.

**Comment by jsastriawan** [comment]
Apparently MeshMiniRouter can only keep one Websocket tunnel session. The logic should be every single SFTP/SCP connection should use different websocket tunnel.

**Comment by TitovLab** [comment]
Yes, MeshMiniRouter.exe can only keep one tunnel session. Each ClickOnce run its own MeshMiniRouter.exe.
It seems that MeshMiniRouter.exe incorrectly believes that WinSCP has closed.

**Comment by Ylianst** [comment]
That is a bug, MeshMiniRouter should be able to handle many connections at once. I will take a look when I can.

**Comment by Ylianst** [comment]
I just took a look at this and I have no problem getting multiple sessions running thru MeshMiniRouter. Note that MeshMiniRouter will launch WinSCP and relay sessions until WinSCP closes. In that case, it will also exit. Both with WinSCP and Putty, if I duplicate the session it still works fine for me. Can I get an exact series of steps to make the problem occur? - Thanks.

**Comment by TitovLab** [comment]
This bug is very interesting, let's go in order.
MeshCentral 0.3.2-m:
1. Click on WinSCP ClickOnce link in MeshCentral
2. First MeshMiniRouter.exe starts **in background**
3. Check WinSCP path, click OK, first WinSCP.exe starts
4. Enter login and password in WinSCP
5. WinSCP first connection successful, directory contents shown
6. Click on WinSCP ClickOnce link in MeshCentral (same agent or another, no matter)
7. Second MeshMiniRouter.exe starts **in background**
8. Check WinSCP path, click OK, second WinSCP.exe starts
9. Enter login and password in WinSCP
10. WinSCP second connection successful, directory contents shown
11. **WinSCP combines two processes into one, second WinSCP.exe killed**
12. Second MeshMiniRouter.exe thinks the work is complete and closes
13. Boom, second WinSCP connection die

MeshCentral 0.3.2-w is more interesting:
1. Click on WinSCP ClickOnce link in MeshCentral
2. First MeshMiniRouter.exe starts **in interactive mode**
3. Click Start button in Mesh Mini Router window
4. Check WinSCP path, click OK, first WinSCP.exe starts
5. Enter login and password in WinSCP
6. WinSCP first connection successful, directory contents shown
7. Click on WinSCP ClickOnce link in MeshCentral (same agent or another, no matter)
8. Second MeshMiniRouter.exe starts **in interactive mode**
9. Click Start button in Mesh Mini Router window
10. Check WinSCP path, click OK, second WinSCP.exe starts
11. Enter login and password in WinSCP
12. WinSCP second connection successful, directory contents shown
13. **WinSCP combines two processes into one, second WinSCP.exe killed**
14. **Second MeshMiniRouter.exe thinks the work is complete, the start button again becomes active**
15. **But second WinSCP connection still works until we click close on second MeshMiniRouter.exe with active start button.**

**Comment by Ylianst** [comment]
Oh! I see. What I missed is that you are running two MeshMiniRouter's to different computers at the same time. I will give this a try. I don't think i ever tested this case.

**Comment by SomeGuru** [comment]
TitovLab, Are you still seeing this issue? I am unable to recreate this in the latest.

**Comment by Ylianst** [comment]
Closing. ClickOnce support was removed.
