### ISSUE TITLE
2FA SMS Not staying resident between systems

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1860]
Hi YlianSt,

So I have been experiencing this issue for some time now, I use Twilio for SMS gateway for 2FA method on my domain, I am seeing that when I take a brand new installed OS with latest browser updates added to them, that the MeshCentral doesn't seem to keep the login information after authenticating on a secondary system. In fact once logged off on both systems, both require an new SMS. I checked internet settings and browser settings and the cookies and other such items are retained between browser closure sessions. Can this be bumped to allow for multiple devices and for longer duration. 

Any questions, please ask away
SomeGuru

**Comment by Ylianst** [comment]
Is this only for SMS 2FA? Does not happen for other 2FA methods?

**Comment by Ylianst** [comment]
Do you have the `twoFactorCookieDurationDays` value set in the config.json of your server and what value do you use?

**Comment by SomeGuru** [comment]
Hi YlianSt, 

I looked in sample-config-advanced.json and in config.json and the guides but don't see that setting... how, where and what section does this belong in? What is the duration that the token is good for longest?

SomeGuru

**Comment by Ylianst** [comment]
Just added 'twoFactorCookieDurationDays' to the Schema and advanced config example. The default value is 30 days and should not be a problem when not set.

**Comment by SomeGuru** [comment]
This issue is resolved with the latest enhancements. Closing to clean things up.
