### ISSUE TITLE
Can different users be provided diverse user consent parameters to nodes in a Device Group?

### ISSUE THREAD

**Issue by sheruvs** [Ylianst/MeshCentral#1861]
Thanks for such an awesome software. I'm using MeshCentral ver 0.6.39 running on a Ubuntu 18.04 64b LTS server.

I have a use case wherein a user U-1 requires access to his own node (which is a part of Dev_Grp-1) without any user consent. Another user U-2 should be given access to this node only after U-1 is prompted and provides consent. MC at present provides setting the User Consent either at User level / at Device group level / node level. When user consent is set at user level, it applies to ALL nodes in all device groups; when it is set at Device grp level, the same is enforcable across  ALL users and all nodes; if it is set at node level, it applies across ALL users and ALL Device groups. For eg, if 'Prompt for user consent" is set for a Device group or for a node, even the Administrator can gain access only after the user accepts the connection for that node in that Dev_Grp. 

A possible solution is to provide the setting of User consent parameters for User_Groups. For the above use case, I can make user U-1 as a member of user group UG-1, set user consent parameters for UG-1 (so that no user consent is required), add the Dev_Grp-1 to this user grp (so that all nodes in Dev_Grp-1 do not require user consent by all members of UG-1) ; similarly, I can make user U-2 a member of user group UG-2 and set different user consent params for UG-2. Can this feature be implemented? 

As per attached diagram, the user consent params apply for the users belonging to their respective user groups and flow downwards towards nodes in the Device groups. By making users members of different user groups, there is a lot more flexibility in implementing different consent permissions.

The present options of setting user consent at user level & node level can be retained, so that if these are set, they override all other settings. 

I was curious about the "Admin Realms"  under User properties. Can I use this to achieve the above purpose?  Searched through all docs and the issues as well here, but couldn't find out what exactly this is. Can you point me to some doc on this?

Thanks again and best regards
![user-consent](https://user-images.githubusercontent.com/70002420/94657037-83331f80-031e-11eb-9064-de59234915b9.png)

**Comment by Ylianst** [comment]
Just added your request to MeshCentral 0.6.54. It's published now, let me know if it works. You can how add user consent flags to user groups. If a user does not have direct rights to a device or a device group, the user group consent flags will be in effect.

![MC2-UserGroupConsent](https://user-images.githubusercontent.com/1319013/94725611-e74ee700-0310-11eb-96b5-6b1f48f70276.png)

**Comment by sheruvs** [comment]
This is simply awesome! The speed at which you respond to and come out with enhancements is unbelievable. 
Thanks a ton!
