### ISSUE TITLE
Limit permissions

### ISSUE THREAD

**Issue by elric72** [Ylianst/MeshCentral#1862]
Is there a way to limit permissions for a group of users especially the ability to :
- Reset
- Sleep
- Power off
- Run command

Thank you for your great job on Meshcentral.
Regards
David

**Comment by vitko-bg** [comment]
May I join this issue and request please a Full Admin rights for user, but with no Server tab right, rest to remain same as Administrator. Thanks.

**Comment by Ylianst** [comment]
So, obviously if you grant access to "Remote Control" and a user is allowed to remote desktop to a remote computer, they can also perform all the operations above. This is why I did not separate these permissions. If you have a good justification why remote desktop should be offered but not the 4 operations above, let me know.

As for the "My Server" tab, in the latest MeshCentral you can remove almost all of the features in the "My Server" tab if you like. This is per-domain so you can have an account that is "Full Administrator" but has none of these server-wide features.

![MC2-MyServerTab](https://user-images.githubusercontent.com/1319013/94714033-6851b280-0300-11eb-81a9-a312f4202de0.png)

**Comment by MordyT** [comment]
So I just updated to latest version (6.54) and in my server tab, backup and restore disappeared.
I added the config switches to config.json, and I can disable and enable errorlog (so it's being read) correctly, but can't get backup/restore back.

Let me know what I can provide for this. Tested with a local mesh user and with a SSO user just in case.

**Comment by elric72** [comment]
> So, obviously if you grant access to "Remote Control" and a user is allowed to remote desktop to a remote computer, they can also perform all the operations above. This is why I did not separate these permissions. If you have a good justification why remote desktop should be offered but not the 4 operations above, let me know.
> 
> As for the "My Server" tab, in the latest MeshCentral you can remove almost all of the features in the "My Server" tab if you like. This is per-domain so you can have an account that is "Full Administrator" but has none of these server-wide features.
> 
> ![MC2-MyServerTab](https://user-images.githubusercontent.com/1319013/94714033-6851b280-0300-11eb-81a9-a312f4202de0.png)

Hi @Ylianst, this is for hotliners. I have installed several linux machines with no possibility to reboot, power down or sleep the machine. They only have access to a web browser. So I don't want to allow them to perform such actions through the Meshcentral. Do you understand my demand with these precisions ?

**Comment by Ylianst** [comment]
@MordyT Oh, I did not mention this, but the "backup" and "restore" options on the "My Server" page are now only displayed when using NeDB. That is because these options have never backed up the database when MongoDB or other DB's are used. I did not want to create a false sense a security because people used it without database backup. The automatic backup continues to include the MongoDB dump.

**Comment by Ylianst** [comment]
@elric72 Just curious, what are "hotliners"?

**Comment by elric72** [comment]
> @elric72 Just curious, what are "hotliners"?

This external guys who have access to our tests platform and answer to our customers.

**Comment by MordyT** [comment]
> 
> 
> @MordyT Oh, I did not mention this, but the "backup" and "restore" options on the "My Server" page are now only displayed when using NeDB. That is because these options have never backed up the database when MongoDB or other DB's are used. I did not want to create a false sense a security because people used it without database backup. The automatic backup continues to include the MongoDB dump.

Thanks, that explained it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.57 with new "Remote Command" and "Reset / Power Off" device rights. Let me know if this works.

![MC2-NewAccessRights](https://user-images.githubusercontent.com/1319013/95125640-1a76e900-070a-11eb-841a-d7cbdfc7155d.png)

**Comment by elric72** [comment]
> Just published MeshCentral v0.6.57 with new "Remote Command" and "Reset / Power Off" device rights. Let me know if this works.
> 
> ![MC2-NewAccessRights](https://user-images.githubusercontent.com/1319013/95125640-1a76e900-070a-11eb-841a-d7cbdfc7155d.png)

I asked my manager and I will be able to make the upgrade tomorrow. I will keep you inform if it works.
Thank you for your quick modification.

**Comment by elric72** [comment]
I have upgraded my meshcentral serveur to 0.6.58 and I confirm, it is working.
Again thank you for your quick action.
