### ISSUE TITLE
"No connection key specified" error in the chat window

### ISSUE THREAD

**Issue by rrech** [Ylianst/MeshCentral#1866]
We started seeing this error recently. We used this feature before and it was working. Settings we recently changed was to use the LoginKey in the URL and force2factor: true.

Chat windows are open on both sides and the error shows up on both chat windows, too.

We tried to remove the LoginKey and force2factor configuration, even so the error occurs. It is probably not related to this configurations.

We tried to update Mesh Central to 0.6.54, too. Even so, not working this feature.

**Comment by zaggynl** [comment]
I'm getting the same issue, I've updated to 0.6.54.

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Your right, I am seeing the same problem. Working on it.

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.6.55.

**Comment by rrech** [comment]
Just perfect, updated and resolved. Tks, Ylian.
