### ISSUE TITLE
 backup and restore menu in my server disappeared after updating to 0.6.54

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#1867]
hi!
 backup and restore menu in my server disappeared after updating to 0.6.54

**Comment by vitko-bg** [comment]
Here is the answer:
https://github.com/Ylianst/MeshCentral/issues/1862#issuecomment-701986238

**Comment by paolor1965** [comment]
I did not think about it.
True, it can give a false sense of security
Thanks again for the wonderful work
