### ISSUE TITLE
Feature request: Open website from meshcentral router

### ISSUE THREAD

**Issue by bsmout** [Ylianst/MeshCentral#187]
Put a link in the Meshcentral router to open the website without the need for authentication.

**Comment by Ylianst** [comment]
Good idea.

**Comment by Ylianst** [comment]
Just uploaded new [MeshCentralRouter](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). New button on the bottom left, let me know if that works.

![MeshCentralRouter-OpenWebSite](https://user-images.githubusercontent.com/1319013/56543698-16133c00-6527-11e9-9909-99d297a2091b.png)

**Comment by bsmout** [comment]
I tried on 2 different Win 10 machines but the button doesn't do anything.

**Comment by Ylianst** [comment]
I forgot to mention, you need to update your server to the latest version. MeshCentral Router will get a login cookie from the server and use the in the URL to open the web page without login, however you need the latest server to do this. If not, the button will not do anything.

**Comment by bsmout** [comment]
The button works with the latest version however I still need to login. I'm using 2FA, maybe that's the issue ?

**Comment by Ylianst** [comment]
Oh, that is weird. I will need to check this again. You should not have to login.

**Comment by Ylianst** [comment]
I am dumb. I just realized you need to add this line to the "settings" section of config.json:

`"AllowLoginToken": true`

I will fix things now to not make the button show up on the MeshCentral Router unless this is on.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.3-d with full fox for this. MeshCentral Router will no longer not show the website login button unless "AllowLoginToken" is set to true.

**Comment by bsmout** [comment]
Great, with the option "AllowLoginToken" it works. Thanks.
