### ISSUE TITLE
MeshCentarl Agent is generating as local to connect 

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1874]
When i download the agent its connecting to local by default how to make it connect to fqdn.?

**Comment by Ylianst** [comment]
In the config.json file that is located in "meshcentral-data" add the following line:

```
{
  "settings": {
    "Cert": "server.domain.com",          <---------------
    "Port": 443,
    "RedirPort": 80
  }
}
```

You need to restart the server when you make changes to config.json. If this is the first time you are editing the config.json, make sure the file is valid when you save it. One way to do that is to use a JSON verification tool like this one: [https://jsonlint.com/](https://jsonlint.com/). Hope that helps.
