### ISSUE TITLE
Ubuntu Desktop 18.04.5 LTS, GDM3 greeter, Wayland, blank Desktop

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#1877]
By default, Ubuntu uses GDM3 with Wayland to present the greeter.  After a reboot, attempting to connect to the Desktop when it's displaying the greeter in Wayland gives a blank screen.  Moving the mouse, issuing keyboard shortcuts, restarting GDM, etc do not resolve the blank screen.  Open a Terminal, `vi /etc/gdm3/custom.conf` and change
```
#WaylandEnable=false
```
to
```
WaylandEnable=false
```
then `reboot`, wait for the OS to boot, connect to Desktop, and the greeter appears.  I have just gone back and forth about six times to verify this issue.

MeshCentral version 0.5.37

**Comment by krayon007** [comment]
In addition to uncommenting that line, you also need to add the following line to the [daemon] section
 `DefaultSession=gnome-xorg.desktop`

**Comment by edlins** [comment]
I guess this is just an item for the documentation, closing.  Thanks!
