### ISSUE TITLE
Feature Request: Distribute Meshcentral router with Meshcentral

### ISSUE THREAD

**Issue by bsmout** [Ylianst/MeshCentral#188]
Include the binary so it can be downloaded from the server itself.

**Comment by Ylianst** [comment]
Agreed. Next time I get a chance, I will do it.

**Comment by Ylianst** [comment]
Published v0.3.2-y with MeshCentral Router download built-in. The link will only show up on Windows browsers.

![MeshCentral-MeshCentralRouter](https://user-images.githubusercontent.com/1319013/56616731-ede11700-65d2-11e9-88c2-19515b5975cd.png)

**Comment by bsmout** [comment]
Great, thanks !

**Comment by Ylianst** [comment]
Cool. Closing this one.
