### ISSUE TITLE
Screen refresh button

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#1880]
Sometimes (frequently), when connected to desktop, the screen is not updating correctly. I suppose this is bound to a detection of what on screen changes and I'm sure that's very complex and non uniform depending on what's the window with focus... This a mild example of that:
![image](https://user-images.githubusercontent.com/2051567/95462514-e3a60a80-0977-11eb-8520-aa28e47b7361.png)

The same is happening with every flavor of VNC. As a workaround, in VNC, there is a button to refresh the entire screen surface, so that what you see is returning the real screen content.
That's function is missing in MeshCentral and, specially with some windows that maybe use uncommon techniques, sometimes could be a problem as there is no way to do that and the screen remains very messy. Sometimes you can move the window to obtain a refresh but sometimes the window title bar is messed and you don't even know where it is and risk to make a click on something undesirable...

I think that the solution could be a simple button that send to mesh agent a screen refresh request. That could be enough and resolve those situations.
I know you're working on a new and better supported way of updating the screen so I'll understand if you'll wait to that point the evaluation of this issue.

Thank you in advance for your time.

**Comment by tektrak** [comment]
I have seen this issue frequently and though a refresh button would be very helpful.

**Comment by Ylianst** [comment]
This makes sense to me. I can add a refresh button.

**Comment by si458** [comment]
this is already done, the is a refresh icon in the bottom right next to all the other icons.
this will refresh the screen for you
