### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1881]
issue #730 would make Mescentral to my very best friend. I'm kind of married with my keyboard and try to ignore my mouse as much as possible. However, Remote Sessions via meshcentral forces me to move to the mouse.

Is there any change #730 will get rid of the tag 'WontFix'? possible solutions are mentioned in there?

**Comment by Ylianst** [comment]
Because MeshCentral runs in a browser, there are keys that we can't capture. This said, can you try MeshCentral Router? You can right click on a device and select "Remote Desktop". That is a native Windows viewer and should capture more keys including the Windows key. Let me know if that works.

![MC2-ImprovedMeshRouter](https://user-images.githubusercontent.com/1319013/95495265-06bec300-0954-11eb-8d93-eedca489e8d9.png)

**Comment by ryanblenis** [comment]
I don't know if it has been looked into, but for some browsers (Chrome) this may be a possibility with the the newer keyboard lock API https://web.dev/keyboard-lock/ . From a quick read it seems the Windows key is encompassed in it. I primarily use macOS as the controlling computer, so I haven't run a test, but it may in fact be possible.

**Comment by Ylianst** [comment]
Ha yes, I need to look into this.

**Comment by jdvmanen** [comment]
The MeshCentral Router is great, it supports the keyboard short cuts as required. Thanks for that suggestion!!

The option mentiond by @ryanblenis is worth investigating. I think this should be a great improvement...

**Comment by ryanblenis** [comment]
Just wanted to update this post:

As stated before, I use a Mac for the admin side, so I have been able to use Cmd-* functions that pass through to Windows systems as WinKey-* functions without issue. As of the latest versions (at least 0.7.10+) this is no longer the case for all combinations, as the OS/browser now intercept several commands (such as Cmd-R to open a Run dialog on a remote Windows machine), which is now being captured by the host OS (leading Cmd-R to reload the page in the local browser). So it would be wonderful to take a look at the keyboard lock API for another reason now!

**Comment by Ylianst** [comment]
Somewhat related, starting with MeshCentral v0.7.45 you can customize shortcuts on the website.

![MC2-KeyboardShortcuts1](https://user-images.githubusercontent.com/1319013/103988993-da2d6980-5143-11eb-9a4a-6118acbe5264.png)

**Comment by fanynek86** [comment]
Hello everyone!
Keyboard shortcuts (eg WIN+R; ALT+TAB, etc.) cannot be used very well via a web browser. You can use the "Send" button, but this is very slow. MeshCentral Router also does not always perform correctly even when the "Use Remote Keyboard Map" option is checked. It would not be possible to bind shortcuts, for example Shift+F1 
= ALT+TAB etc.?

Wtih BR
František

**Comment by si458** [comment]
@fanynek86 ALT+TAB does work as ive just tried it here BUT do note, it only works because im on mac

if you are using the SAME OS as the remote device, then YOUR OS will take over controls of certain key presses
for example you cant CTRL+ALT+DELETE as your OS takes over those commands,
its sometimes the same for CTRL+W or ALT+F4 !

but sadly the is no way currently to bind different key presses to different key presses like you said
SHIFT+F1 presses ALT+TAB

**Comment by fanynek86** [comment]
@si458 And the possibility that @ryanblenis mentioned here is not possible https://web.dev/keyboard-lock/ ? I tried it in the DEMO here: https://keyboard-lock.glitch.me/ and it worked beautifully. It only works for me on Chrome. Unfortunately, FireFox does not support this.

**Comment by si458** [comment]
@fanynek86 That's the problem, it's only Chrome support, the is no safari, and Firefox support
So we can't really implement something with only 1 browser in mind. It needs to work for all browsers

**Comment by si458** [comment]
@fanynek86 ive just realised/noticed in the source code
if you HOLD the SHIFT key while clicking the fullscreen button, it will ask the browser to go fullscreen
and according to the docs https://wicg.github.io/keyboard-lock/#escape-key all we need to do is `lock` and `unlock` etc!
so in theory it already works from the word go!
i will do some testing!
so windows os to windows os correct that you have the issues with?

**Comment by fanynek86** [comment]
@si458 Unfortunately, I tried everything in fullscreen in the browser while clicking the "fullscreen" icon in MeshCentral before writing this post. Hotkey transfer only works via MeshCentral Router and not always. That's why I found this solution to be a handy help for many of us. Yes, I use Windows OS.
Sorry, I don't understand what you mean - lock and unlock before going to full screen mode?

**Comment by si458** [comment]
@fanynek86 if you are happy changing some code to do some testing here what you can do.
1. inside `default.handlebars` the is a function called `enterBrowserFullscreen`
add the following inside the function at the beginning of the function
`if (navigator.keyboard && navigator.keyboard.lock) { navigator.keyboard.lock(); }`
2. inside `default.handlebars` the is a function called `exitBrowserFullscreen`
add the following inside the function but at the end of the function
`if (navigator.keyboard && navigator.keyboard.unlock) { navigator.keyboard.unlock(); }`
3. make sure you use the ENGLISH web ui for testing `/?lang=en`
4. refresh the webpage then connect to a device then HOLD THE SHIFT KEY while clicking the full screen button
5. try all the different key presses, see if they work

**Comment by si458** [comment]
@fanynek86 you can also try, just before you hold the shift key and click the fullscreen icon,
enter `navigator.keyboard.lock();` into your developer tools of the chrome browser to activate the lock feature

then once you leave the full screen, run `navigator.keyboard.unlock();` to get control back

**Comment by fanynek86** [comment]
@si458 Great, I used the first option and everything works exactly as it should (ALT+TAB; WIN+R; WIN+PAUSE, etc.). Thank you very much for your help. A very useful feature that will help us all.

**Comment by si458** [comment]
@fanynek86 glad that worked! ive just pushed it to the repo so im going to close this issue now :)

**Comment by fanynek86** [comment]
@si458 The absolute nicest thing would be if we could press activate it in a window and not have to be in fullscreen.

Here is another alternative:
https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock

If you think of something...

**Comment by si458** [comment]
sadly, if you read the specs
https://wicg.github.io/keyboard-lock/#handling-keyboard-events
https://developer.chrome.com/docs/capabilities/web-apis/keyboard-lock#prerequisite
the webrowser MUST be in full-screen mode, so sadly it cannot be used in a non-fullscreen mode!
nothing we can do, its up to chrome to implement it (which they wont as they have to follow the specs)
