### ISSUE TITLE
Question: PM2 monitoring MeshCentral Application?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1882]
Hi YlianSt,

I am wondering if PM2 [https://github.com/Unitech/PM2/](https://github.com/Unitech/PM2/) can run alongside MeshCentral server without any inherent risks or issues. I don't want to inject issues into my current architecture, but I want to get some deeper statistical data on the server and the processes running... I also want to make  sure that I am keeping with licensing requirements as not to incur license violations.

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
I don't know anything about PM2, from a quick look at it, it does not seem to be a problem. It's a process manager, should run fine. As for license, MeshCentral is Apache 2.0, PM2 is AGPL 3.0 but you don't need to link them together, so, I don't see any issues.
