### ISSUE TITLE
Group collapse/expand action available? 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1883]
Hi YlianSt,

Group collapse/expand action at the top of the portal/dashboard? I don't see one, but that would come in very handy for those that might have larger 50+ unit per group environments. Especially if they have multiple of those groups around the globe...

I might have missed it in the documentation, or in the actual server page itself, just wondering if its there, or in the works.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Are you talking about this?

![image](https://user-images.githubusercontent.com/1319013/95497588-68346100-0957-11eb-8353-5161a93e96e4.png)

**Comment by SomeGuru** [comment]
Yes, except for at the parent level of the whole tree... so a master open and close of all the expansions... 

Example shown;
next to select all, could be an +/- Groups button that would in essance
trigger all the groups to open and close the tree...

So you only show the group titles, but not the group systems themselves, then you can drill down to a group like Intel Amt Group and open just that group.

Likewise if you need all group trees open, you would hit the +/- Group to open them all back up... I think this would help the mobile users that have lots of systems to move more rapidly through the list of groups and allow expanding of the sub group needed...

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
So, your looking for "Expand all" and "Collapse App" options?

**Comment by SomeGuru** [comment]
Exactly, so then less burden overall for loading super groups that maybe nothing is needed in at the moment... 

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Just published in MeshCentral v0.6.62, you can now right click on the group expand/collapse icon and expand or collapse all groups. Let me know if this works.

![MC2-ExpandAll](https://user-images.githubusercontent.com/1319013/95805846-37d42600-0cbb-11eb-97b4-abe8c92dd8b2.png)

**Comment by SomeGuru** [comment]
Hi YlianSt,
I looked into this on the latest build, and I found it works on the PC side fairly well, except if you collapse all groups and then restart the server, the units as they come online will show for about 1 minute in the groups and then disappear for non expanded groups... I am slightly confused on how to enable on the mobile side with Android, I don't have an apple to try on yet... So just wondering how to enable this that way... Still really nice to make sure we collapse for the larger groups... Thank you for making this happen off a very poor repetitive request... 

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Can you try the group expand/collapse all options again? It should be fixed in latest versions.

**Comment by SomeGuru** [comment]
Fixed that popping open then closed issue... However on mobile is there a way to do this also? Unable to long hold for opposite mouse click like other applications seem to read the long press as. So need a solution to hit mobile side also if possible...

Also as of 0.6.80 large server instances seem to lag processing the large list of deployed vms and physical assets.

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
This works and therefore I am closing this issue. Thanks Ylian.

SomeGuru
