### ISSUE TITLE
Update Agent After Port Change

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#1884]
A couple of months ago I found myself needing to change the agent port from 443 to 444.

On the firewall I put the new rule in for 444 --> 444 but also changed the old rule so 443 went to 444.

This worked fine for the existing agents to communicate and I had hoped that they would get the new configuration if not straight away at least when the server next updated however when I took the 443 --> 444 port forward away today, the old agents that were installed before the change all dropped off.

So I restored the port forward but now I'm wondering if there is a way to get them to all update which port they should be connecting on without having to manually remote in to each one and re-install?

**Comment by Ylianst** [comment]
In each agent install folder there is a "meshagent.msh" file. This is a text file and has the connection URL for the agent. You could update this file remotely and restart the agent. There is no automated way to do this. Of course, try first on devices you have access to to make sure this process works for you.

**Comment by plwc** [comment]
Thanks, that will work well.
