### ISSUE TITLE
CIRA connections slow to reconnect on intermittent internet connection

### ISSUE THREAD

**Issue by axelandy** [Ylianst/MeshCentral#1886]
My Internet connection has intermittent issues, and has for over a year now.  The 2 screenshots below are the same PC.  You can see that the software agent quickly reconnects after packet loss/disconnection, but the CIRA does not.  When I notice the CIRA connection has not reestablished, I can issue the resetserver command, and the CIRA connection is back online within a few seconds.  I have seen the same behavior from 4 different PC's with 3 different versions of AMT.  This has been happening since I first started using MeshCentral.  

![Screenshot - 10092020 - 08:41:29 AM](https://user-images.githubusercontent.com/55218587/95603974-e2262200-0a0b-11eb-9063-db6a30898023.png)
![Screenshot - 10092020 - 08:40:48 AM](https://user-images.githubusercontent.com/55218587/95603976-e2beb880-0a0b-11eb-9a2f-4f2547e72a03.png)

**Comment by Ylianst** [comment]
So yes, sadly the decision to retry a CIRA connection is decided by the Intel AMT firmware and I have no control over it. I have noticed that firmware will try twice and stop trying for a long time. MeshAgent has a very different behavior by design. Not sure what I can do about this.

**Comment by Ylianst** [comment]
On a unrelated note, I am working on lots of Intel AMT & CIRA improvements. That will be announced in the coming weeks.

**Comment by axelandy** [comment]
As soon as I restart the server, it comes back online, regardless of how long it has been showing as offline. This leads me to believe that there may be something going on on the server that could solve this.

**Comment by axelandy** [comment]
As I was going through my e-mail and saw your reply, I remembered that when I first saw this happening, I tried resetting the PC's AMT by unplugging the power cord for a few seconds.   I did this on several PC's.  They would not come back online until I reset the server.  I didn't think of resetting the server until trying other things for quite some time.

**Comment by axelandy** [comment]
Since Version 0.6.60, this is no longer happening.
Thank you.  And thank you for all you have been doing making a great software.
