### ISSUE TITLE
Edit files stopped working

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1888]
On first introduction to edit files on MC all was working file for certain period of time.
Now on 0.6.58 - it does not work anymore.
I updated to latest 0.6.60 - but still same, selecting file by checkbox and on "edit" button nothing happens.
Could you please fix this - I use this to block youtube on my kids computer, I have copied "hosts" file to Program Files\MeshAgent and usually editing it there. Once I edit it, using a terminal I copy it to C:\Windows\System32\drivers\etc.
All this is because file manager on MC does not allow to browse within this folders ( terminal does :) )

"Edit" option does not work in all locations, not only in Program Files or Windows.

**Comment by Ylianst** [comment]
Thanks for the report. Just fixed it, it will be in MeshCentral v0.6.62 when it's next published.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.62, let me know if it works.

**Comment by vitko-bg** [comment]
Fixed - thanks!!!!
