### ISSUE TITLE
Drive names on Files tab

### ISSUE THREAD

**Issue by IntExCZ** [Ylianst/MeshCentral#1892]
Hello,
it would be very useful if there will be shown a drive name and better, drive type (removable, cdrom, ...) too instead of just drive letter.
Is it possible?

Thank you,

Jan

**Comment by Ylianst** [comment]
Good request. I am currently working on Intel AMT and security stuff, but will get back to one when I can.

**Comment by si458** [comment]
How do these look? only 3(ish) years late!
currently it will get the drive names from the volumes date (this data gets uploaded when the meshagent starts up on boot up)
so if you plug in a USB drive it might not show a name until the 20min update cycle where it rechecks volumes and gets names of the drives etc, unless you want for force the update manually using `coreinfoupdate` in the console tab
![image](https://github.com/Ylianst/MeshCentral/assets/765314/a4e9735b-0842-4d35-bbff-5f01ba5c74f4)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/bcfe1dde-2a3f-4f33-905c-15b877e5a9d6)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b508fe2e-55f3-4e12-93ea-cfeb39b8d4a7)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/cbb77759-2f86-4759-abaf-5e6bddce6ae8)

**Comment by IntExCZ** [comment]
Late but still. ;-)
Nice. :-)

**Comment by si458** [comment]
PR done! will be in next release!
dont forget to donate! https://www.si458.co.uk/2024/01/05/donation/
