### ISSUE TITLE
After update to 0.5.81 some agents change from online to offline status continuously. Part2

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#1893]
Some agents continously change from online to offline. Most of this agents access to internet form 3g router, but others, by wifi or ethernet cable to an adsl or fiber optic router. When are offline i can enter from teamviewer but not from mesh. If I restart the mesh client agent service on a remote pc change status to online but after some minutes later change to offline again. One hour later the devices are permanently offline.

I have done different tests. With either of the two settings ("AgentPong": 60 or "AgentPing": 60), it is necessary to restart the client agent on all remote computers to set them online. Besides, when the ubuntu server is restarted (mesh server is instaled on ubuntu 18.04.5) all the computers set offline again. This behavior occurs not only on some computers (not at all) with 3g connection but also on computers connected to a LAN.
Thanks for your help.

**Comment by Ylianst** [comment]
Can you run the following test. On a remote machine that causes these problems, stop the "MeshAgent" service and run the agent manually by opening a command prompt then:

```
cd c:\program files\meshagent
meshagent run
```

You will see the agent connect, etc. Leave that running and report back what you see. You could also do this:

```
meshagent run > agent-output.txt
```

When you are done with the test, you can hit ctrl-c to exit the agent.

**Comment by edorbike** [comment]
Hi Yliants:
On one of remote machine that causes problems I have stopped the service and executed the instruction:
meshagent run > agent-output.txt
A new device has been created on a MeshCentral with the same name as the old device. The agent-output.txt report shows the following:
   MeshCentral2 Agent

  Connecting to: wss://centroloiu.edukinet.es:444/agent.ashx
  Connected.
  Server verified meshcore... Launching meshcore...

It seems that it connects correctly but, as I have commented previously, this also happens if I restart the service. But if the server is restarted for any reason, software update ..., these computers have to be offline again.

These two new lines are added to the report when the server is restarted:

   Mesh Server Connection Error
   Connecting to: wss://centroloiu.edukinet.es:444/agent.ashx
   Mesh Server Connection Error
   AutoRetry Connect in 1263 milliseconds

The device goes offline.

Thanks for help me.

**Comment by Ylianst** [comment]
So you are saying the agent will show this:

```
...
Mesh Server Connection Error
Connecting to: wss://centroloiu.edukinet.es:444/agent.ashx
Mesh Server Connection Error
AutoRetry Connect in 1263 milliseconds
```

It should retry to connect in 1.2 seconds, but it does not? Correct?

**Comment by edorbike** [comment]
The server takes about three minutes to restart. The agent should retry the reconnection process every 1.2 seconds, right?
The agent goes offline and does not reconnect.

**Comment by scorpion-90** [comment]
it also happens to me only on windows 7, I am attaching the dump files: https://mega.nz/folder/ptBEiRDQ#Rwvqw9YgGLF5Vzp_7msHZw

**Comment by scorpion-90** [comment]
> So you are saying the agent will show this:
> 
> ```
> ...
> Mesh Server Connection Error
> Connecting to: wss://centroloiu.edukinet.es:444/agent.ashx
> Mesh Server Connection Error
> AutoRetry Connect in 1263 milliseconds
> ```
> 
> It should retry to connect in 1.2 seconds, but it does not? Correct?

it also happens to me only on windows 7, I am attaching the dump files: https://mega.nz/folder/ptBEiRDQ#Rwvqw9YgGLF5Vzp_7msHZw

**Comment by edorbike** [comment]
Yes, all the devices that fail are windows 7 32 bits or 64 bits. All devices with windows 10 are online but curiously, some devices with windows 7 are also online.
I have updated the server version to 0.6.71 but the problem continues.
