### ISSUE TITLE
Meshcentral did not start / error logging

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#1894]
Hello,
this night my server where MeshCentral is installed did a Windows Update and rebooted. At reboot MeshCentral did not start, even if the service is set to start automatically.

MeshCentral 0.6.62, no reverse proxy.

Ok, so I started searching for a trace of the error that prevented the service from starting. The problem is that there where no trace (or I did not found it)
I've searched there:
**Windows Registry**, only these two relevant entry:
- Origin: Service Control Manager, event ID 7009: timeout 30000 millisecond waiting the connection to MeshCentral service
- Origin: Service Control Manager, event ID 7000: MeshCentral service did not start for the following error: The service did not reply to the start or control request in the estimated time.

**meshcentral.wrapper.log**, I see the stopping and finished when the server shut down at reboot but no trace of the start trial. Then there is the manual start I've done later.

**meshcentral.out.log**, no date/time so I don't know but no error or warning there

**meshcentral.err.log**, empty file

Did I miss a place to check for errors? Is there some init code with not exception catching that could lead here?
I've set the service start to Automatically (delayed) to try to mitigate the problem.

**Comment by Ylianst** [comment]
Hi. First, can you go in "meshcentral-data" and see if there is a "mesherrors.txt" file? If so, send over the last errors at the bottom of this file.

Next, can you run MeshCentral from the command line:

- Stop the MeshCentral service (if not already stopped).
- Open a admin command prompt, "cd" to the MeshCentral folder (just above the "node_modules" folder").
- Run "node node_modules/meshcentral"

Let me know what you see. Thanks.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
