### ISSUE TITLE
Last Access shows Creation Time; Can't blank email

### ISSUE THREAD

**Issue by LFM8787** [Ylianst/MeshCentral#1896]
There's a small issue with the last access time of the users:

![image](https://user-images.githubusercontent.com/13755139/96172814-51fd4680-0efd-11eb-8f63-f6e95a0d7440.png)

It's already showing the creation time:

![image](https://user-images.githubusercontent.com/13755139/96173190-e10a5e80-0efd-11eb-976b-ddf2e34c1bf2.png)

Also, there's no way to blank the email address:

![image](https://user-images.githubusercontent.com/13755139/96173089-bae4be80-0efd-11eb-86e7-8e5c650cb6df.png)

Thank you!

**Comment by Ylianst** [comment]
I added support for removing the email address of a user account in MeshCentral v0.6.64. However for the account creating/last login, I see you have the same value for both I don't have the same issue on my server. If you can provide a step by step guide to how you get that, it would be appreciated.
