### ISSUE TITLE
Updateing Nodejs

### ISSUE THREAD

**Issue by KieranSmith892** [Ylianst/MeshCentral#1897]
I've been trying to setup WebDAV backup.

I'm getting the sever error "WARNING: WebDAV requires Node v10.x or higher."

I've updated Node to 12.19.0 and npm to 6.14.8 but this update doesn't seem to be recognised in MeshCentral.

I've tried restarting MeshCentral and rebooting the server and it still apears to be using an old version of node.

Thanks

**Comment by KieranSmith892** [comment]
If I stop the service and run manually it works as expected and uses the correct version of node.

`sudo systemctl stop meshcentral.service
node node_modules/meshcentral`

I'm not very experienced with node but I'm assuming that this is caused by the version of node used in the service startup file?

Any help would be greatly appreciated.

Thanks

**Comment by q16marvin** [comment]
Hi, i have same problem... can you tell me what exatkly you change in this file /etc/systemd/system/meshcentral.service?

**Comment by rrech** [comment]
Same here. Updated Node to last LTS version: v16.17.0.

Nonetheless, versions (in MeshCentral server console) show "node": "10.19.0".

I'm trying to find some reliable instructions on how to do this change. 

I believe that specific instructions on how to do this in a MeshCentral environment would be important for people who are unfamiliar with NodeJS. If something like this already exists, could you let us know? Unfortunately, I didn't.

**Comment by rrech** [comment]
Solution:

Execute: which node
Result: /path/to/your/version

With the path shown, change meshcentral.service

Example

If you have this configuration:
ExecStart=/usr/bin/node /home/administrador/meshcentral/node_modules/meshcentral

change to:
ExecStart=/path/to/your/version /home/administrador/meshcentral/node_modules/meshcentral

Restart meshcentral service.
