### ISSUE TITLE
How to run the meshcentral as service in windows. 

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#1899]
How to run the meshcentral as service in windows. 

Is there any steps. 

Right now i am running in cmd prompt as "node meshcentral" 

Is there any option to run as service

**Comment by Ylianst** [comment]
Should be easy. First, try running MeshCentral with --help, you should see this:

```
MeshCentral v0.6.50, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcommander.com/meshcentral2

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.
   --removeaccount [userid]          Remove a user account.
```

The --install, --uninstall, --stop, --start switches should allow you to setup MeshCentral as a background service and this should work on both Windows and Linux. Let me know if that works.

**Comment by JavierChaparroMX** [comment]
> Should be easy. First, try running MeshCentral with --help, you should see this:
> 
> ```
> MeshCentral v0.6.50, remote computer management web portal.
> This software is open source under Apache 2.0 license.
> Details at: https://www.meshcommander.com/meshcentral2
> 
> Run as a background service
>    --install/uninstall               Install MeshCentral as a background service.
>    --start/stop/restart              Control MeshCentral background service.
> 
> Run standalone, console application
>    --user [username]                 Always login as [username] if account exists.
>    --port [number]                   Web server port number.
>    --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
>    --exactports                      Server must run with correct ports or exit.
>    --noagentupdate                   Server will not update mesh agent native binaries.
>    --listuserids                     Show a list of a user identifiers in the database.
>    --cert [name], (country), (org)   Create a web server certificate with [name] server name.
>                                      country and organization can optionally be set.
> 
> Server recovery commands, use only when MeshCentral is offline.
>    --createaccount [userid]          Create a new user account.
>    --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
>    --adminaccount [userid]           Promote account to site administrator.
>    --removeaccount [userid]          Remove a user account.
> ```
> 
> The --install, --uninstall, --stop, --start switches should allow you to setup MeshCentral as a background service and this should work on both Windows and Linux. Let me know if that works.

Hello Ylianst, I tried the Start commands on Server 2022 after the Install cmdlet, but get this:

"C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --install
Installing MeshCentral as Windows Service...
MeshCentral service already installed.


C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --start
Error: The service "MeshCentral" does not exist or could not be found."

do I have to be in a different directory?

**Comment by JavierChaparroMX** [comment]
> > Should be easy. First, try running MeshCentral with --help, you should see this:
> > ```
> > MeshCentral v0.6.50, remote computer management web portal.
> > This software is open source under Apache 2.0 license.
> > Details at: https://www.meshcommander.com/meshcentral2
> > 
> > Run as a background service
> >    --install/uninstall               Install MeshCentral as a background service.
> >    --start/stop/restart              Control MeshCentral background service.
> > 
> > Run standalone, console application
> >    --user [username]                 Always login as [username] if account exists.
> >    --port [number]                   Web server port number.
> >    --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
> >    --exactports                      Server must run with correct ports or exit.
> >    --noagentupdate                   Server will not update mesh agent native binaries.
> >    --listuserids                     Show a list of a user identifiers in the database.
> >    --cert [name], (country), (org)   Create a web server certificate with [name] server name.
> >                                      country and organization can optionally be set.
> > 
> > Server recovery commands, use only when MeshCentral is offline.
> >    --createaccount [userid]          Create a new user account.
> >    --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
> >    --adminaccount [userid]           Promote account to site administrator.
> >    --removeaccount [userid]          Remove a user account.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The --install, --uninstall, --stop, --start switches should allow you to setup MeshCentral as a background service and this should work on both Windows and Linux. Let me know if that works.
> 
> Hello Ylianst, I tried the Start commands on Server 2022 after the Install cmdlet, but get this:
> 
> "C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --install Installing MeshCentral as Windows Service... MeshCentral service already installed.
> 
> C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --start Error: The service "MeshCentral" does not exist or could not be found."
> 
> do I have to be in a different directory?

Ran the --restart option and got some more info:
C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --restart
MeshCentral service stopped.
Holding 5 seconds...
C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:517
          throw Error('The service "'+this.name+'" does not exist or could not be found.');
          ^

Error: The service "MeshCentral" does not exist or could not be found.
    at daemon.value [as start] (C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:517:17)
    at Timeout._onTimeout (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:389:220)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.15.0

**Comment by JMalland** [comment]
I believe I'm currently experiencing the same issue. 

It seems to install the service, and it looks like I can uninstall it as well. It just throws a couple errors unlinking the files in the MeshCentral/winservice/daemon/ directory. However, any time I run --stop, --restart, --start, etc, it doesn't actually do anything.

The common error is: The service "MeshCentral" does not exist or could not be found.

I can see the service running in Windows services.msc, but thats all I know, or can do.

--install:
```
Installing MeshCentral as Windows Service...
MeshCentral service already installed.
```
--start:
`Error: The service "MeshCentral" does not exist or could not be found.`
--stop:
`MeshCentral service stopped.` (I presume it only says that since it thinks it's not installed)
--restart:
```
MeshCentral service stopped.
Holding 5 seconds...
C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:517
          throw Error('The service "'+this.name+'" does not exist or could not be found.');
          ^

Error: The service "MeshCentral" does not exist or could not be found.
    at daemon.value [as start] (C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:517:17)
    at Timeout._onTimeout (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:383:220)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
--uninstall:
```
Uninstalling MeshCentral Windows Service...
ERROR: Unable to uninstall MeshCentral service: Error: Command failed: node winservice.js --uninstall
node:fs:1878
  binding.unlink(path);
          ^

Error: EPERM: operation not permitted, unlink 'C:\Program Files\Open Source\MeshCentral\WinService\daemon\meshcentral.exe'
    at Object.unlinkSync (node:fs:1878:11)
    at rm (C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:458:22)
    at C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\daemon.js:471:15
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Program Files\\Open Source\\MeshCentral\\WinService\\daemon\\meshcentral.exe'
}

Node.js v20.11.0
```

**Comment by JMalland** [comment]
I've gone through some debugging, and it seems like it's line 599 in daemon.js that's causing my issue.

`return fs.existsSync(path.join(this.directory(),this.id+'.exe')) && fs.existsSync(path.join(this.directory(),this.id+'.xml')) ;`

The program returns false for both files, because it's looking for them to exist in `/MeshCentral/daemon/` instead of `/MeshCentral/winservice/daemon/` where they get installed. 

Moving the daemon directory out of winservice solved my problem.

**Comment by JavierChaparroMX** [comment]
> I've gone through some debugging, and it seems like it's line 599 in daemon.js that's causing my issue.
> 
> `return fs.existsSync(path.join(this.directory(),this.id+'.exe')) && fs.existsSync(path.join(this.directory(),this.id+'.xml'));`
> 
> The program returns false for both files, because it's looking for them to exist in `/MeshCentral/daemon/` instead of `/MeshCentral/winservice/daemon/` where they get installed.
> 
> Moving the daemon directory out of winservice solved my problem.

Awesome! I'll try that later this week, if I can replicate the fix I'll let you know so we can hopefully fix it for everyone!
