### ISSUE TITLE
Terminal do not show letters while typing

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#19]
Like in the topic, no matter if it is windows 7 or 10, when connecting into terminal and typing, letters are not visible until Enter hit. Even when using "Paste" option, the things are not visible until Enter.

Also there is problem with listing files in folder. Dir command do not show .exe files. Like on the screenshot.
![zrzut ekranu 98](https://user-images.githubusercontent.com/5872054/45749448-fbcd5480-bc0b-11e8-8aed-05cc4cee2125.png)

**Comment by jsastriawan** [comment]
Windows shell accepts line by line input, not echoing character by character. This is known limitation now. We need to look at meshcore.js to perform character echo rather than line by line echo.

**Comment by nicrame** [comment]
It would be cool, because i never know if i did some typo.

**Comment by Ylianst** [comment]
Yes, we know about this. Bryan who is working on the MeshAgent will be looking into fixing this in the coming weeks.

**Comment by nicrame** [comment]
Thank You :)

**Comment by Ylianst** [comment]
Bryan is still working on this one. It's a bit tricky because you need to capture the command prompt in a completely different way. However, Bryan has a working prototype.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.4-h with a fix for the terminal in Windows. Bryan did all the work. The terminal will now show the keys as you are typing. There are a few bugs with the new system, the first line in the terminal does not show and colors are not supported yet. Will work on these at some point.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.4-h with color support in the Terminal when used with Windows.

![mc2-colorterm](https://user-images.githubusercontent.com/1319013/50048709-3ec28b00-0088-11e9-8b1d-1d875f33747b.png)
