### ISSUE TITLE
Sample Apache "server".conf and MeshCentral config.json

### ISSUE THREAD

**Issue by ewm0657** [Ylianst/MeshCentral#1900]
I need a sample Apache "server".conf and MeshCentral config.json file that will allow me to proxy MeshCentral on the same server securely. My web sites work great and I have the cert for my meshcentral serve domain but can't get this working. Apache2 on Ubuntu, with MeshCentral help needed please.

**Comment by ewm0657** [comment]
Apache2 on Ubuntu, with MeshCentral help needed please.

**Comment by Ylianst** [comment]
Hi. I made changes to your issue request as placing the entire request in the title does not look good. The [MeshCentral User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf) has examples for NGINX and Traefik, but not Apache. Take a look at issue number #317, there are full examples of configuration files for Apache used as a reverse proxy. Let me know if that works.

**Comment by ewm0657** [comment]
I ended up uninstalling Apache and installing NGINX. I just could not
get it to function with Apache on Linux. It is 100% my lack of proxy
knowledge. Your assistenace was great. I have it installed and semi-
working. Just the issue with remote clients being redirected to
127.0.0.1. I will be working on that next. Thank You Thank You Thanks
You.
