### ISSUE TITLE
Feature Request - curl instructions

### ISSUE THREAD

**Issue by map7** [Ylianst/MeshCentral#1901]
Some of the computers I've added to MeshCentral don't have wget and cannot be installed, but they do have 'curl'. I got meshagent installed with the following;

`curl -k -o meshagent "<https address>"`

My request is that the curl instructions be displayed as an alternative to wget when adding/inviting an agent.

**Comment by b8two** [comment]
@map7, I agree and posted a suggestion [965#issuecomment-708971952](https://github.com/Ylianst/MeshCentral/issues/965#issuecomment-708971952) to resolve the inconsistancies.

**Comment by si458** [comment]
closing as stale
