### ISSUE TITLE
Feature request - changes to agent installation binaries - 1 of 2

### ISSUE THREAD

**Issue by mschubeck** [Ylianst/MeshCentral#1902]
I'm writing these up separately.  My first request is for a minor change to the existing installation binaries:
Please add a field - preferably at or near the top, or even in a separate section - that displays the computer name in an easy-to-read format.

I'm using the temporary "Connect" feature of the installation binary for temporary remote desktop assistance for our help desk, rather than continuing to pay annually for this ability with certain other providers.  However, many clients don't know their computer name for a technician to be able to connect to the right machine.  Adding it to the information displayed when the binary is opened would be helpful for the client to read to the tech.

A "plus" would be to generate a random 6- or 9-digit number instead of the computer name, or pre-pending it to the displayed computer name for those instances when the computer's name is "OWNER-PC" or "John's Mac", but that's not super important.

**Comment by dinger1986** [comment]
@si458 could be useful for temporary connect

**Comment by si458** [comment]
closing this as old/stale but also duplicate of a newer requests with better examples/templates 
#1902
