### ISSUE TITLE
Feature request - changes to agent installation binaries - 2 of 2

### ISSUE THREAD

**Issue by mschubeck** [Ylianst/MeshCentral#1903]
Add an agent binary that is just the temporary "Connect" feature only, instead of also having the option to install.  Ideally, it would also generate a random 6- or 9-digit number (displayed in the typical hyphenated group of three) for a temporary ID rather than just using the computer name.

I've started using the installation agent binary's "Connect" option for temporary remote desktop sessions for the Help Desk to get away from using existing remote session software from TeamViewer and Logmein Rescue.

Alternate temp connect method:
Even better, be able to launch the code from an embedded link from a script on a webpage.  This *should* get around the problem where the OS blocks execution of the binary because it doesn't recognize the developer.  However, I'll take whatever I can get in improvements on the existing method(s) for help desk support. 😁

**Comment by Ylianst** [comment]
For the "Connect" only option, it's already there. When you get the agent, select "Interactive only" and give that a try. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/96515614-7cf7db00-121a-11eb-8abb-34290e9bdd54.png)

**Comment by mschubeck** [comment]
Awesome, that's it.  Thanks!
