### ISSUE TITLE
Meshctrl upload/download not working

### ISSUE THREAD

**Issue by adsgreen** [Ylianst/MeshCentral#1906]
I noticed the recent comment about upload and download commands being added to meshctrl.js so investigated further.

However I'm not able to get either functionality working.
For example:
`node meshctrl.js upload --id 'jfL....' --file readme.md --target c:\\temp --loginuser ****** --loginpass *******`

This is run from the meshcentral node repository so just testing uploading the readme.md file.
The command confirms the file is there as if I specify a file that doesn't exist it returns the correct error.
The deviceid, username and password are all correct (just masked)

When running the command the only output is:
`Connecting...`
`OK`

And nothing else happens (no file is sent).

This is run from the node server itself (An Amazon Linux Fedora 2018.03 with MeshCentral 0.6.65) and targeting a Windows 10 Pro - 2004 [19041] machine.
The destination directory C:\Temp exists and is not under any permissions.

Windows 10 agent:
`> versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-10-12T01:59:09.000Z"
}`

Not sure what is going wrong?
Same behavior in reverse for download.

Edit: Also the same for the 'shell' command so its looking like a websocket connection issue?
Everything else works as far as I can tell - I can remote desktop and transfer files using the server's user interface no problem.

**Comment by Ylianst** [comment]
Thanks for the report. I have a fix for meshctrl file upload, it will be in the next published version v0.6.66. If you want to try it now get the latest [MeshCtrl.js here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshctrl.js). You just replace and let me know if it works for you. Thanks.

**Comment by adsgreen** [comment]
Perfect!
Confirmed new pre-release code fixes upload / download.

**Comment by Ylianst** [comment]
MeshCentral v0.6.66 is out with this fix.
