### ISSUE TITLE
Need to send "ESC" to remote agent desktop while connected in "browser full-screen"

### ISSUE THREAD

**Issue by mschubeck** [Ylianst/MeshCentral#1907]
The workaround is to exit the "browser full-screen" desktop, send the ESC character, then go back into browser full-screen mode.  Ideally, the best fix to this would be to add "ESC" to the key combinations that can be sent from the pop-up menu with Ctrl+Alt+Del, Win+R, etc.

If it's not an easy fix, we can still go through the workaround instead, but it's not very intuitive that way.

**Comment by Ylianst** [comment]
I should just add a `esc` key when in full screen, that seems useful.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.66 with a new "ESC" button on the bottom left when in browser full screen. Let me know if that works.

**Comment by mschubeck** [comment]
It works, thank you!
