### ISSUE TITLE
File transfer/move issue

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#1908]
Hi @Ylianst,

I attempted to move folders this morning using the files tab on the MeshCentral server setup I have, however when I did the cut and then moved into the folder one level down and pasted, the prompt for number of checked items was correct, however the action never took place after clicking the OK button. I think this might be a bug in regards... So I thought maybe it wasn't able to do multiple files so I attempted again with a single file and same results happened with this single file... So I bring you this bug for investigation... 

Thanks,
SomeGuru

**Comment by vitko-bg** [comment]
There is an issue at the moment as I know with upload/download. But also as I know @Ylianst promised to fix it in next version. So wait for next version, update and try. Hope that will help.

**Comment by vitko-bg** [comment]
Found it #1906 looks like same issue

**Comment by SomeGuru** [comment]
@vitko-bg,

That is for MeshCtrl.js what I am referring to is on the server page files tab the movement never happens after the selection is made and the folder change is made and paste action shows number of files to be moved, but the action never invokes to move the file(s) to the other folder or location in the same machine.

So similar but different in my opinion... However fix might be for both in regards...

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
I will look into this, MeshCtrl.js is fixed in GitHub and will be in the next published version, but right, this is a different issue.

By the way, I am furiously working on Intel AMT improvements, hopefully v0.6.66 will be out tomorrow. After that, I can get back to user requested issued next week.

**Comment by SomeGuru** [comment]
This seems to have been implamented...  Closing this issue as fixed.
