### ISSUE TITLE
erorr systemctl status  meshcentral2.service

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#1910]
Hello
after updating to version 0.6.65 i believe i encountered the following  log errors
it may be due to a bad configuration of my server
however the server seems to function regularly as far as the connectivity of the agents is concerned.
in config.js  i have  "WANonly": false,

hope it can help

at https://meshcentral2.amm.balbi.unige.it:4433/  :

MeshCentral MPS server.
Intel® AMT computers should connect here.

 
 my system:
 Virtualization: vmware
 Operating System: CentOS Linux 8 (Core)
 CPE OS Name: cpe:/o:centos:centos:8
 Kernel: Linux 4.18.0-147.8.1.el8_1.x86_64
 Architecture: x86-64

systemctl status  meshcentral2.service: 

:     at Object.attemptLocalConnectResponse (/srv/meshcentral/node_modules/meshcentral/amtmanager.js:321:56)
:     at Object.<anonymous> (/srv/meshcentral/node_modules/meshcentral/amt/amt.js:149:186)
:     at /srv/meshcentral/node_modules/meshcentral/amt/amt.js:67:157
:     at Array.<anonymous> (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman.js:51:17)
:     at Object.CreateWsmanComm.obj.gotNextMessages (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:493:26)
:     at Object.CreateWsmanComm.obj.xxProcessHttpResponse (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:435:17)
:     at Socket.CreateWsmanComm.obj.xxOnSocketData (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:412:25)
:     at Socket.emit (events.js:198:13)
:     at addChunk (_stream_readable.js:288:12)
:     at readableAddChunk (_stream_readable.js:265:13)

**Comment by paolor1965** [comment]
[servererrors_.txt](https://github.com/Ylianst/MeshCentral/files/5425591/servererrors_.txt)

**Comment by Ylianst** [comment]
Interesting. As a workaround, add the following line in your config.json's settings section:

```
{
  "settings": {
    "Cert": "central.mesh.meshcentral.com",
    "AmtManager": false,                                      <-------------
    ...
  }
}
```

That should fix it. I am working on major changes to Intel AMT handling on MeshCentral, it's going to be out in v0.6.66 when I next publish it.

**Comment by paolor1965** [comment]
thank you so much for the help

**Comment by Ylianst** [comment]
Note that since this bug, the AMTManager works a lot better now and should be enabled by default.
