### ISSUE TITLE
Feature Request: Session indicator option when connected

### ISSUE THREAD

**Issue by jlydia** [Ylianst/MeshCentral#1913]
How about a way to toggle a transparent popup on the remote desktop, allowing us to alert the user that we are connected and working on their issues. This would also double as a notice to those paranoid users weary of "big brother" spying on them.
(see attached idea)

![session_indicator](https://user-images.githubusercontent.com/43318108/97063927-97122000-1570-11eb-9f54-419fa5862957.png)

**Comment by Ylianst** [comment]
The feature is already there. First, you can right click on the "Connect" button of the remote desktop and you will get options to remotely connect with notification and/or privacy bar. In addition, look for "User Consent" options in the devices tab or in the devices group tab, that will allow you to set notifications for a device, a device group. You can also set it for a user or user group and lastly, there is a setting in config.json to make it server wide.

Let me know if that works,
Ylian

**Comment by jlydia** [comment]
Ok, didn't know that was an option. 

It appears to do what I want, thx

Question: If I set "Real Name", right-click Connect and select "Privacy bar", it displays the "Real Name" -- I like that.
However, If I set "Real Name", right-click Connect and select "Ask Consent + Bar", it displays the username "admin"
Is there a way to display "Real Name" in both instances?
Thx.

**Comment by vitko-bg** [comment]
You have to change you config.json change 0 to 1
"consentMessages": {
        "title": "MeshCentral",
        "desktop": "{0} requesting remote desktop access. Grant access?",
        "terminal": "{0} requesting remote terminal access. Grant access?",
        "files": "{0} requesting remote files access. Grant access?"
      },
