### ISSUE TITLE
Remote mouse out of Sync

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#1914]
I have one client that has an issue with the remote mouse been way out of sync with my mouse, to the point it's unusable.

Client is running latest agent on latest Windows 10 and i see the behaviour when connecting via the browser or the remote desktop client in the router.

Any tips on where to start looking at what could be the issue?

Cheers

**Comment by si458** [comment]
STALE CLOSING, if you still have this issue, please open a new issue
