### ISSUE TITLE
Untagged Display

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#1918]
Hopefully a quick and easy UI request - when viewing devices by Tags or Group-Tags, I'd really appreciate an "Untagged" display instead of having untagged devices completely disappear. This would help me make sure I don't forget to tag new devices in a much more efficient way than going through each one individually. Thanks!

**Comment by Ylianst** [comment]
Just added it, will be in MeshCentral v0.6.69 when it's next published.

![image](https://user-images.githubusercontent.com/1319013/97368878-12255000-1869-11eb-91c5-769de272f933.png)

**Comment by PetieM** [comment]
That's actually better than what I had in mind. Works perfectly - thanks!
