### ISSUE TITLE
Let's Encrypt certificate does not work

### ISSUE THREAD

**Issue by sylvaincolson** [Ylianst/MeshCentral#1919]
Hi Ylianst and team,

I have tried to set Let's Encrypt up, but even after waiting for more than a week without touching anything, the server has not rebooted and I keep getting a warning "Your connection is not secure".

I do not really understand what is wrong with my configuration file. I have tested my server on https://letsencrypt.org/ which tells me that there should be no problem. So here I come, asking for help and/or explainations. I attach a copy of my `config.json` file so that you can check whether I made a mistake or not.

Thank you for your amazing job and for your precious time.

```
{
        "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
        "settings": {
                "Cert": "myservername.xyz",
                "Port": 443,
                "_AliasPort": 444,
                "RedirPort": 80,
                "_ExactPorts": true,
                "_AllowLoginToken": true,
                "_AllowFraming": true,
                "_AgentInviteCodes": true,
                "AuthLog": "/var/log/kqt/meshcentral/auth.log",
                "__MaxInvalidLogin": "Time in minutes, max amount of bad logins from a source IP in the time before logins are rejected (ban setup).",
                "MaxInvalidLogin": { "time": 600, "count": 5, "coolofftime": 60 },
                "_Plugins": {
                        "enabled": true
                }
        },
        "letsencrypt": {
                "__comment__": "Requires NodeJS 10.12 or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
                "email": "sylvain.colson@gmail.com",
                "names": "myservername.xyz, www.myservername.xyz",
                "rsaKeySize": 3072,
                "production": false
        }
}
```

**Comment by evgeniysevost** [comment]
>  "production": false
RTFM!
http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf pg 22-23

**Comment by sylvaincolson** [comment]
OMG... I really did not expect it was all.... I reaaaaaally am sorry for having opened an issue for such a stupid problem.
I swear, when I read it, I had not understood the purpose of this parameter, and I thought leaving production to false would not bring any issue for the certificate.

Thank you @evgeniysevost for this simple, fast and.... quite incisive answer ;)

**Comment by evgeniysevost** [comment]
Sorry if it seemed rude, I tried to give a short and clear answer))

**Comment by Ylianst** [comment]
This is excellent :) At least you correctly setup a non-production certificate first to make sure that worked!

**Comment by sylvaincolson** [comment]
> Sorry if it seemed rude, I tried to give a short and clear answer))

In my opinion, the "RTFM" is not that rude when it's accurate ;)
In this case, it was more a "Understand TFM" but still.... I should have read it correctly.

> This is excellent :) At least you correctly setup a non-production certificate first to make sure that worked!

Thank you for your support :D
