### ISSUE TITLE
changing "Server Mode" during installation not applied

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1922]
Over the past few days I've installed MC2 a couple of times on a Windows 10 Enterprise 1909 (build 18363.1139) system using the MeshCentralInstaller-2.8 (file version 2.8.7542.17902), uninstalling MC2 and NodeJS in between each installation. During the MC2 installation I changed "Server Mode" from "LAN Mode" to "WAN Mode"; once the installation reached the "Installation Completed" screen, without quitting the installer, I opened "Advanced Configuration..." and found that "General | Server Mode" was set to "Hybrid Mode". If I change Server Mode to "WAN Mode", click "Apply", close the installer, re-run the installer, "Server Mode" remains set to "WAN Mode".

**Comment by Ylianst** [comment]
You right. Thanks for reporting that. MeshCentralInstaller-2.9.msi just published with the fix for that. Thanks.
