### ISSUE TITLE
MeshCentral Router shortcut request

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1924]
The link 'Router' has an dishonorable place in the far bottom of the systems list,
Since it is a very usefull function; can it be that it becomes a quick-access link in the left navigation button list?

![image](https://user-images.githubusercontent.com/68591647/97404260-1b103300-18f6-11eb-8411-f0e1082d1dfa.png)

**Comment by jdvmanen** [comment]
If the router is installed already, the popup can be skipped...

**Comment by Ylianst** [comment]
Fixed the title. In latest version of MeshCentral, I replaced ClickOnce with MeshCentral Router and the RDP/SSH/WinSCP links are now a MeshCentral Router link. Let me know if that works.

![MC2-ClickOnceNewRouterLinks](https://user-images.githubusercontent.com/1319013/97755085-cadfcf00-1ab5-11eb-986a-49aedf8b7789.png)

**Comment by jdvmanen** [comment]
Thanks for the change. This is already faster than it was! It still needs a few clicks to have a remote session (search for PC, click on RDP, then the router opens, then search again for the PC in the Router, right-click PC and select remote desktop). 

Can the default double-click action in the router be configurable?

**Comment by Ylianst** [comment]
@jdvmanen Did you update MeshCentral Router to the latest version? It should be just one click. If you have an older version, MeshCentral Router, it will not automate the port mapping and app start.

**Comment by Ylianst** [comment]
Note that new versions of MeshCentral Router now have a self-update feature, so in the future I will no longer have to remind people to update their Router.

![MC2-RouterAutoUpdate](https://user-images.githubusercontent.com/1319013/97978250-280fa500-1d82-11eb-94cb-7b3f0af1299b.png)

**Comment by jdvmanen** [comment]
Hi Ylianst,

Thanks for clarification, I did not update the Router, and yes, with one click I'm now starting a RDP session.

I'm really sorry for another 'however' :-) but nevertheless here it comes :). Most of my remote PC's don't have RDP and RDP locks the local session. So I used the word "RDP" but the remote access I normally use (via web or router) is Remote Desktop. Can that link be added, so that in one-click the router opens and a remote desktop session is started?

Besides that; for me the router isn't required to auto-close after the RDP (or remote desktop session) is closed, but now it closes directly after closing the RDP session.

**Comment by Ylianst** [comment]
I don't mind having more issues created for these additional issues, it avoids having one long issue thread where I can no longer track what people want. So, if you can create new issues and be as specific as you can on what is needed, that would be great.

Your are correct that "RDP" to me is the Microsoft Windows RDP protocol, not the MeshCentral Remote Desktop. So you want to change the double click default on MeshCentral Router to "Mesh Desktop Protocol"?

For the auto-closing of MeshCentral router, would it be ok if I don't auto-close if you use the Router Window to add any new mappings / open remote desktop?

**Comment by jdvmanen** [comment]
Ylianst, I'll close this because the issue is covered and rephrased in #1964 .
