### ISSUE TITLE
Wake on Lan (WoL)

### ISSUE THREAD

**Issue by xanpri** [Ylianst/MeshCentral#1925]
Hi, 

I need assistance to complement WakeOnLan MeshCentral. My server is at stable version 0.5.81.

I verified that it sends a magic packet on port 7 and only to the MAC Address. This way it sends the magic packet only to the broadcast domain, not reaching other networks.
I have a network with several subnets and I would need it to send the packet with the IPv4 + MAC Address.
On the Linux operating system I can send the package via WakeOnLan like this: "wakeonlan -i IPv4 MAC" (wakeonlan -i xx.xx.xx.xx XX: XX: XX: XX: XX: XX).

If it is correct I found the function in meshcore.js:

```
    // Send a wake-on-lan packet
    function sendWakeOnLan(hexMac) {
        var count = 0;
        try {
            var interfaces = require('os').networkInterfaces();
            var magic = 'FFFFFFFFFFFF';
            for (var x = 1; x <= 16; ++x) { magic += hexMac; }
            var magicbin = Buffer.from(magic, 'hex');

            for (var adapter in interfaces) {
                if (interfaces.hasOwnProperty(adapter)) {
                    for (var i = 0; i < interfaces[adapter].length; ++i) {
                        var addr = interfaces[adapter][i];
                        if ((addr.family == 'IPv4') && (addr.mac != '00:00:00:00:00:00')) {
                            var socket = require('dgram').createSocket({ type: 'udp4' });
                            socket.bind({ address: addr.address });
                            socket.setBroadcast(true);
                            socket.send(magicbin, 7, '255.255.255.255');
                            count++;
                        }
                    }
                }
            }
        } catch (e) { }
        return count;
    }
```

But I don't know how to add IPv4 to send the magic package.

**Comment by Ylianst** [comment]
So, your request is confusing. Right now the server sends the wake-on-lan packet using IPv4 UDP on the broadcast address, same for MeshAgents. There is no code to send the magic packet "to a MAC address".

In what mode in your server? LAN, WAN or Hybrid?

You pointing to the code running on the meshagent. You want the agent to send a directed wake-on-lan to the last know IP address of the device to wake up?

I just changed the MeshCentral server to send a directed wake-on-lan to the device hostname if set. That should work in LAN and Hybrid modes. That change will be in MeshCentral v0.6.70. Let me know if that works for you.

**Comment by xanpri** [comment]
Sorry for the delay to reply.
Thank you it worked correctly to turn on the computer through the general tab, Action button and select Wake-up and ok.
