### ISSUE TITLE
MC2 console won't load after deselecting "Multi-user server" during installation

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1927]
I installed MC2 (0.6.67) on an AD-bound Windows 10 Enterprise system, unchecking the "Multi-user server" option. Installation runs to completion but when I access the console, the main structure of the console is displayed (i.e. title, tabs, etc) but the main window/status area only displays "Loading...".

Not sure if this is related , I just tried reinstalling (using MeshCentralInstaller-2.8, file version 2.8.7542.17902) to make sure I noted the behavior correctly and the installed antivirus software flagged some MC2 components. AV software is Sophos Central Endpoint, MC2 components flagged (all identified by Sophos as "Generic ML PUA") are

C:\Program Files\Open Source\MeshCentral\node_modules\.staging\meshcentral-7ee17c2f\MeshService.exe

C:\Program Files\Open Source\MeshCentral\node_modules\.staging\meshcentral-7ee17c2f\MeshService-signed.exe

C:\Program Files\Open Source\MeshCentral\node_modules\.staging\meshcentral-7ee17c2f\MeshCmd-signed.exe

Uninstalled MC2 and Node.js then tried reinstalling MC2 using MeshCentralInstaller-2.9 (v2.9.7606) and got the same behavior. I'll have to check our Sophos console's history for this system, but I don't recall seeing Sophos PUA detections for the MC2 0.6.67 installation. I'm not sure if Sophos was updated prior to reinstalling the MC2 the first time today - I'll see if I can figure that out from the Sophos console as well.

**Comment by Ylianst** [comment]
Hi. So a few things here, first, typically your install MeshCentral in multi-user mode. I have not tested single-user mode in a long time, I can give it a try, but that mode is for people that want to manage a few computers on the local network and don't want to ever see the login page. It's a bit of a "beginner mode".

For the anti-virus, this is a long standing problem. The 32bit MeshAgent is often flagged by AV software and there is little I can do about it but tell people to flag it as a false positive. The entire source code to the agent is [here for anyone to review](https://github.com/Ylianst/MeshAgent).

**Comment by tlcarpenter** [comment]
I'll try to figure out what may have changed with Sophos.

Not to extend this issue (should start a new one?), I deselected "Multi-user server" because I wanted to use a different database than NeDB and didn't know how best to do that. Specifically, is best/easiest to simply complete MC2 install first then import the NeDB database to another database or is there a way (e.g. using npm) to specify an alternate database during the MC2 installation and avoid an export/import operation?

**Comment by Ylianst** [comment]
Ha! I see. If you are an expert user, I would not recommend using the MeshCentral Installer at all. Instead, install NodeJS (you already have it installed i am sure) then do this from the command prompt:

```
mkdir c:\meshcentral
cd c:\meshcentral
npm install meshcentral
node node_modules\meshcentral
(wait for server to finish installing and start, then hit ctrl-c).
node node_modules\meshcentral --install
(will install as a service)

node node_modules\meshcentral --help
(show options to start/stop the service, etc).
```

Once you got it setup, you can quickly run MeshCentral manually using:

```
cd c:\meshcentral
node node_modules\meshcentral
```

So, you can quickly try things out. Then, go in "meshcentral-data" and start changing the config.json. This is how I do it since you have all the control you want oven the entire process. Hope that helps.

**Comment by tlcarpenter** [comment]
I'll try that out. Thanks so much.
