### ISSUE TITLE
[Feature Request] Add option for MeshCentral Router to remember its last window position

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#1929]
If you launch the latest version of MeshCentral Router, adjust its position on your screen, close it and open it again, it will currently open at the same place it did the first time you launched it instead of the position you moved it to prior to closing it.

It would be nice if MeshCentral Router either remembered its last window position by default, had an option to do so or always launched in the center of the screen like MeshCommander instead of the upper left corner of the screen like it currently does.

This is purely a quality of life improvement.

**Comment by Ylianst** [comment]
Agreed :) Working on it.

**Comment by Ylianst** [comment]
Fixed, it will be in MeshCentral v0.6.72. Or you can download the new [MeshCentral Router here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

I do like that quality of life improvement. Good request.

**Comment by whalehub** [comment]
@Ylianst Thanks for the quick implementation! It's working nicely.
