### ISSUE TITLE
MeshCentral Router Add Relay Mapping

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1930]
This is an enhancement request. 
When you attempt to create a Relay Mapping in MeshCentral Router and select the device group the group listing is not sorted by alphabetical order.  I'm honestly not sure how the list is sorted- but it's pretty frustrating due to it not being in alphabetical order.  As a result, when you have numerous groups, it is difficult to find the group you want.  
Can this be modified so that it will sort the group list in alphabetical order?  It is in alphabetical order (by group) in the Devices list in MeshCentral.  Just not in the Mappings area.

**Comment by Ylianst** [comment]
Yes, working on this now!

**Comment by Ylianst** [comment]
Fixed, it will be in MeshCentral v0.6.72. Or you can download the new [MeshCentral Router here](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

**Comment by PathfinderNetworks** [comment]
Excellent! Works perfectly now.  Thanks for the very speedy resolution!
