### ISSUE TITLE
allow mac novnc to use user/pass instead of pass

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1934]
Is there a way to access macOS systems, using MC2 or MeshCmd, that would authenticate users with their macOS account credentials rather than a VNC password (which appears to be the only option with noVNC). Remmina's VNC plugin supports authentication using macOS account credentials, which I've used to connect both directly to macOS and over an SSH-tunneled connection; no VNC password set in either scenario. This works with macOS' Sharing configured to use "Screen Sharing" or "Remote Management".

I searched noVNC's discussion group and found this thread

https://groups.google.com/forum/?fromgroups#!searchin/novnc/macOS%7Csort:date/novnc/1UR8-NvRsEc/bvlUkRYaFQAJ

in which noVNC's Pierre Ossman provides a link to this code in libvncserver

https://github.com/LibVNC/libvncserver/commit/030ccf673d96016733ffb3bef3feede20dba19a7

**Comment by dinger1986** [comment]
@si458 I think the answer to this is no and without having a mac to test on will be hard to develop!

**Comment by si458** [comment]
this is already possible now with a recent novnc update,
just tried it on my mac mini M1 and old macbook pro
