### ISSUE TITLE
MariaDB Connector/Node.js and MC2

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1935]
I was preparing to download MariaDB for use with MC2 and noticed the "Download MariaDB Connector/Node.js" link on the MariaDB download page.

https://mariadb.com/kb/en/nodejs-connector/

Is MC2 able to make use of this connector? I see that the connector can be installed using npm.

https://www.npmjs.com/package/mariadb

**Comment by Ylianst** [comment]
If you configure MeshCentral to use MariaDB in the config.json, it will automatically download the connector on NPM next time you run MeshCentral. Note that I have not tested MariaDB a lot of MeshCentral, I use MongoDB on my servers, so please test and let me know if you find any issues.

**Comment by tlcarpenter** [comment]
Will do. Thanks.
