### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1936]
node.js v12.19.0, npm v6.14.8, windows 10 ent 1909 x64

```
C:\meshcentral>npm install meshcentral
npm WARN saveError ENOENT: no such file or directory, open 'C:\meshcentral\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\meshcentral\package.json'
npm WARN meshcentral No description
npm WARN meshcentral No repository field.
npm WARN meshcentral No README data
npm WARN meshcentral No license field.

+ meshcentral@0.6.71
added 138 packages from 139 contributors and audited 138 packages in 11.77s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\meshcentral>dir
 Volume in drive C has no label.
 Volume Serial Number is 6E7F-A352

 Directory of C:\meshcentral

10/30/2020  05:42 PM    <DIR>          .
10/30/2020  05:42 PM    <DIR>          ..
10/30/2020  05:42 PM    <DIR>          node_modules
10/30/2020  05:42 PM            40,183 package-lock.json
               1 File(s)         40,183 bytes
               3 Dir(s)  202,293,788,672 bytes free
```

**Comment by Ylianst** [comment]
The installation worked, you can ignore these messages. One day I need look into what I can do to clean that up, but if you do this:

```
node node_modules/meshcentral
```
It should complete the installation and run MeshCentral. Let me know if that works.

**Comment by tlcarpenter** [comment]
I only included part of the output from my attempt at installing MC2 using npm - I went as far as running

mkdir c:\meshcentral
cd c:\meshcentral
npm install meshcentral
node node_modules\meshcentral

I just uninstalled MC2 then went through the same steps plus "node node_modules\meshcentral --install", which generates the output below.

================================================= 

C:\>mkdir meshcentral

C:\>cd meshcentral

C:\meshcentral>npm install meshcentral
npm WARN saveError ENOENT: no such file or directory, open 'C:\meshcentral\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\meshcentral\package.json'
npm WARN meshcentral No description
npm WARN meshcentral No repository field.
npm WARN meshcentral No README data
npm WARN meshcentral No license field.

+ meshcentral@0.6.73
added 130 packages from 138 contributors and audited 130 packages in 13.117s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\meshcentral>node node_modules\meshcentral
Installing archiver@4.0.2...
Installing node-windows@0.1.14...
Installing otplib@10.2.3...
Module node-windows can't be loaded. Restart MeshCentral.

C:\meshcentral>node node_modules\meshcentral --install
Installing MeshCentral as Windows Service...
Error: Cannot find module 'C:\meshcentral\node_modules\meshcentral\node_modules\minimist'
Require stack:
- C:\meshcentral\node_modules\WinService\winservice.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at start (C:\meshcentral\node_modules\WinService\winservice.js:39:22)
    at Object.<anonymous> (C:\meshcentral\node_modules\WinService\winservice.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\meshcentral\\node_modules\\WinService\\winservice.js' ]
}


C:\meshcentral>

**Comment by Stan-Stani** [comment]
I just had this issue.

**Comment by si458** [comment]
@Stan-Stani you have no issue
Your issue happens from time to time, because it installs modules while node is running, and node can't find the modules until u restart it :)

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
