### ISSUE TITLE
MeshCentral Server Update Unknown

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#1938]
I just went to update my server and I'm showing Unknown on the Stable Branch and the Latest. The only thing I can remember doing was switching my server from Apache to NGINX? Would this have caused this?

**Comment by Ylianst** [comment]
MeshCentral will try to run the following command to get the latest versions:

```
npm dist-tag ls meshcentral
latest: 0.6.72
stable: 0.5.81
```

Give this command a try manually. If NPM needs to be configured with a proxy or MeshCentral needs to path to the npm command you can use the following in the settings section of config.json:

```
   "npmpath": "path...",
   "npmproxy": "http://proxy"
```

Hope that helps. Let me know what you see.
Ylian

**Comment by 82280zx** [comment]
That was it, thank you! I updated to Ubuntu 20 lts recently and my npm must of broke during the upgrade, I reinstalled it doing 

```
sudo apt install libssl1.1=1.1.1f-1ubuntu2
sudo apt install npm
```

then did the command you specified 

`npm dist-tag ls meshcentral`

and it showed up correctly, thank you again!
