### ISSUE TITLE
MeshCentral Router with remote host using public key

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#1939]
Hey guys - it's been a while, I hope you're all well and healthy considering the recent climate.

Quick (?) question: is it possible to connect through MC2Router to a remote host that's configured to only permit SSH connections when using a key pair?

 It's only dawned on me recently that my MCR connections which are working flawlessly are also those systems which are accessible using basic username/password credentials: when I attempt to connect to other systems configured to permit connections only when I can supply the corresponding private key to the presented public keys, I never get a connection. For example, I have a number of systems running inside private VPCs in AWS: none of them have public IPs but they are all configured to only permit access when the key pairs match.

Am I missing something here, or is this a restriction with MCR?  I'm looking through the JSON files that I use to connect
```
{
"action": "route",
"localPort": 12345
...
}
```

am wondering if there's a way of adding a path in these JSON files that points to the private key that MCR can use:
```
{
"action": "route",
"localPort": 12345
...
"key": "/home/dave/connections/server.pem"
}
```
Immediately I wonder if this isn't possible due to the fact that it poses a potential security issue, but would like to hear your take on things - personally I find it somewhat embarrassing even asking this question, as I'm sure you've already got an answer to it ?

**Comment by Ylianst** [comment]
So, MeshCentral is just does TCP port mapping. Yes, there should not be any problem doing an SSH session with a key pair over MeshCentral, just configure your SSH client with the key and connect. You don't need to configure MeshCentral Router with any keys.

I will note the from your SSH server's perspective the SSH client is going to be connecting from the MeshAgent's IP address. If you have IP address filtering (for example, the security group on AWS) then your connection is going to get rejected unless allowed from the Agent's public IP address.

Hope that makes sense,
Ylian

**Comment by D4V3M0NK** [comment]
Understood Ylian - I'm checking it now but something's still amiss.

Am looking through a new `meshcommand` file and see that there's a new section in the file:
```
"remoteTarget" : "",
```

Which is blank for all my connections.  May I ask if that has anything to do with the issues I'm seeing?

**Comment by D4V3M0NK** [comment]
Also wondering if this is a firewall issue, but my understanding is that if my remote can connect to MC2, then that's all that I need : everything is tunneled through the ports already set up, correct?

**Comment by Ylianst** [comment]
Ha yes, "remoteTarget". There are two types or routing possible thru MeshCentral Router. You can see in by pressing the "?" icon in the mappings tab of MeshCentral Router. The default route targets a port on the computer running the MeshAgent, in that case the remote target is empty. The other route goes thru a specified agent and targets a remote IP:Port. In that case, the remote target needs to be the IP address of the final destination of the TCP connection.

If your trying to connect SSH to AWS thru a MeshAgent, then yes, you should have your remote target set to the IP address of AWS.

**Comment by D4V3M0NK** [comment]
Hmmm ... still can't get this to work.  

Am wondering if this is possibly a networking issue that I'm experiencing? The only thing that makes me think that it's **not** is that the host is able to connect just fine with the MC2 server, and the terminal / files etc through the MC2 server works flawlessly.


Just ensuring that I'm correct in my understanding, if the host that I'm wanting to connect to is able to communicate with the MC2 host just fine, w

**Comment by D4V3M0NK** [comment]
and of course, as soon as I publish that last comment, I download the meshaction.txt file again, make some changes into a test file and test it ... it bloody works!

("Well of course it does!" I hear from the MC2 team...)

Dave slinks away, shaking his head: unlikely to regain any form of professionalism he may have ever had ...

**Comment by D4V3M0NK** [comment]
Somehow I'd gotten a completely different node ID in the file I was originally using ... it's possible that that was from a former instance in AWS (some are in auto scaling groups) but ... well ...
