### ISSUE TITLE
Blank device screen after update 0.6.73

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#1942]
After updating to the latest version, all my clients disapeard, the web interface is fully working, switching to english did not solve the problem. The log file does not contain any errors.

OS: Ubuntu 20.04 LTS (Server)
NPM:  6.14.4
NODE:  V14.0.0

Restoring to version 0.6.72 (wich was working before the upgrade) did not resolve the problem.

Restoring an older os (ubuntu 18.04 lts) with older meshcentral version resolved the problem. after restoring an backup the server went blank again, showing interface, but no devices anymore

**Comment by petervanv** [comment]
Update: after restoring ubuntu 20.04 lts again, and downgrade to stable version 0.5.81 it is working again, restored the database so all devices are back online. not all things are working, layout cant be changed. ill try to make an screenshot when i return home

**Comment by rroseselavy42** [comment]
can confirm this  on 18.04 LTS with latest 0.6.73 will blank out the My Devices screen, however, I still see the agents are connected

**Comment by petervanv** [comment]
selecting list, desktop or collums has no effect on the presentation of the devices.
![Screenshot_1](https://user-images.githubusercontent.com/58996467/97887112-bdcb1600-1d29-11eb-9248-f8fc2f97439f.jpg)

**Comment by petervanv** [comment]
After clicking at the list button, this error is listed in teh inspection at google chrome
![Screenshot_2](https://user-images.githubusercontent.com/58996467/97893616-cd4e5d00-1d31-11eb-8534-acb331947054.jpg)

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.74 with a fix for this, let me know if it works.

**Comment by petervanv** [comment]
The problem is not fix, the selection of the list colums or desktop is not fixed.
after clicking on list, does not change the view, and when this is done, mouse over an device creates more errors
![Screenshot_3](https://user-images.githubusercontent.com/58996467/97903202-f1646b00-1d3e-11eb-8fc9-ee26671fb903.jpg)

**Comment by petervanv** [comment]
After restoring ubuntu 18.04 LTS to its original state i managed to get it working again, maybe there is an issue with in ubuntu 20.04 LTS. so its partly fixed for the moment
