### ISSUE TITLE
after update to 0.6.73 in mydevice if I select list or desktops at the top right all devices disappear 

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#1943]
hi after update to 0.6.73 in mydevice if I select list or desktops at the top right all devices disappear after page refresh.
If I select columns again they return.

**Comment by paolor1965** [comment]
I upgraded to 0.6.73 on a twin machine with no online device, except amt device and I didn't encounter the problem.
So on the first production vm I restored the previous snashot of two days ago (version 0.6.71) and the problem did not occur

**Comment by Ylianst** [comment]
Your right, working on this now!

**Comment by paolor1965** [comment]
thank you so much


Inviato da Posta per Windows 10
UNIVERSITA' DEGLI STUDI DI GENOVA
Paolo Russo
+39 010 353 2335
paolor@unige.it
www.cedia.unige.it/ 
https://rubrica.unige.it/personale/VUZDWFhv


Da: Ylian Saint-Hilaire
Inviato: lunedì 2 novembre 2020 18:26
A: Ylianst/MeshCentral
Cc: paolor1965; Author
Oggetto: Re: [Ylianst/MeshCentral] after update to 0.6.73 in mydevice if Iselect list or desktops at the top right all devices disappear (#1943)

Your right, working on this now!

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.74 with a fix for this. Let me know if it works.

**Comment by paolor1965** [comment]
all right now thanks inifinite

**Comment by rroseselavy42** [comment]
also confirmed, Thanks!
