### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1944]
I'm trying to use MariaDB with MC2. I've created a MariaDB user, 'mc2admin', and enabled all privileges for the account in the 'Global privilges' section (using the HeidiSQL management utility). Below is the output from 'meshcentral --debug db'. I'm guessing that giving the MC2 acces to a MariaDB account with such broad privileges is a security risk - just a temporary solution to try to figure out where MC2 is having trouble with MariaDB. Related question: can one create a database in MariaDB (say 'meshcentral'), explicitly for MC2's use, and specify that in MC2's config.json, e.g.

      "MariaDB": {
         "host": "localhost", 
         "user": "<database username>", 
         "password": "<password>",
         "database": "meshcentral"
      }

C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --debug db
DB: ERROR: USE meshcentral: Error: (conn=145, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)
DB: Creating database...
DB: BatchSetupDb: Error: (conn=146, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)
DB: ERROR (Get DatabaseIdentifier): Error: (conn=148, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)
DB: ERROR (Get SchemaVersion): Error: (conn=149, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)
DB: ERROR (GetAll mesh): Error: (conn=155, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)
SQLERR3 TypeError: Cannot read property 'length' of undefined
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1158:26
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:837:21
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:769:61
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
DB: ERROR (GetAll user): Error: (conn=159, no: 1045, SQLState: 28000) Access denied for user 'mc2admin'@'localhost' (using password: YES)

**Comment by Ylianst** [comment]
I will need to look into this, I have not tried MariaDB in a long time. Yes, you should be able to create a "MeshCentral" database in MariaDB that is completely separate from your other databases and have your MeshCentral instance login and only have access to it's own database and none of the others. I think the default database name is "meshcentral", but you can change it in the config.json.

**Comment by Ylianst** [comment]
I just did more testing on MariaDB and published MeshCentral v0.6.77 with some fixes. Update and let me know if it works. Note that the database name is hard coded to "meshcentral", so the line `database` in your config.json will probably not work, I would remove it.

Also, in my tests I just give MeshCentral root access to the database. This is needed at first because MeshCentral will create the database, tables, indexes, etc. the first time you run it. So, make sure in your case the "mc2admin" has full rights on first run, you can then restrict.

Let me know if that works.

**Comment by tlcarpenter** [comment]
Sorry for the long post...

Notes from initialization of MariaDB database.

So, MC2 now appears to be able to connect to MariaDB and create a database (notes below),
and seems to be working, with a few bumps along the way.

I tried installing MC2 using 'npm' but I wasn't able to install MC2 as a service so I
resorted to using the Windows installer. After installing MC2 and then switching over to
MariaDB, if I tried restarting MC2 using the Windows installer (start to Edit, then click
apply), the installer would crash, and I had to start MC2 from the command line with
"--debug db". Once I restarted the system though, I checked Services and MC2 had started
and was running; the MC2 Windows installer could also restart MC2 without the installer
crashing.


NOTES
=====

MC2 v0.6.77 installed using MeshCentralInstaller-2.9. Accessed MC2 console creating
a first user. Stopped MC2, edited config.json, (adding "Auth": "sspi"), restarted
MC2 and accessed console while logged in to a local Windows account with administrative
rights. Stopped MC2 from command line.

Created "mc2admin" account in MariaDB, enabled access to all "Global privileges".

Edited config.json, adding

"mariadb": {
         "host": "localhost", 
         "user": "mc2admin", 
         "password": "<password>"
      }


Tried starting MC2 from Command Prompt ("run as dministrator") but didn't work
until started using "--debug db" option.

===========================================================================
C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --start
Installing mariadb...
Error: The service "MeshCentral" does not exist or could not be found.

C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --stop
MeshCentral service stopped.

C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --start
Error: The service "MeshCentral" does not exist or could not be found.

C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral --debug db
DB: ERROR: USE meshcentral: Error: (conn=4, no: 1049, SQLState: 42000) Unknown database 'meshcentral'
sql: USE meshcentral - parameters:[]
DB: Creating database...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.6.77, WAN mode.
MeshCentral Intel(R) AMT server running on < MC2 server FQDN >:4433.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on < MC2 server FQDN >:443.
Server Ctrl-C exit...

C:\Program Files\Open Source\MeshCentral>
===========================================================================



Below is just info from MariaDB displayed in HeidiSQL after starting MC2 with the
"--debug db" option - just showing that the "meshcentral" database was created.
After seeing that the 'meshcentral' database was created, prior to restarting the
system, I demoted the "mc2admin" database user to only have privileges for the
'meshcentral' database, i.e. the MC2 server started automatically when the sytem
restarted and could still access the 'meshcentral' database using the 'mc2admin'
account. Also, accessed the MC2 console with an AD account I hadn't used before
with this particular MC2 installation - verified that the account was indeed added
to the 'meshcentral' database.

===========================================================================
/* Connecting to 127.0.0.1 via MariaDB (TCP/IP), username root, using password: Yes ... */
SELECT CONNECTION_ID();
/* Connected. Thread-ID: 14 */
/* Characterset: utf8mb4 */
SHOW STATUS;
SELECT NOW();
SHOW VARIABLES;
SHOW DATABASES;
/* Entering session "local MariaDB" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='meshcentral';
SHOW TABLE STATUS FROM `meshcentral`;
SHOW FUNCTION STATUS WHERE `Db`='meshcentral';
SHOW PROCEDURE STATUS WHERE `Db`='meshcentral';
SHOW TRIGGERS FROM `meshcentral`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SHOW EVENTS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='meshcentral';
===========================================================================

**Comment by Ylianst** [comment]
I am not sure what specific question you are asking. If you need to stop/start the MeshCentral service, your going to have to run in an administrator command prompt. Personally, I don't use the Windows installer and just do everything manually, but install is also ok.

You can run MeshCentral manually using:

```
node node_modules\meshcentral
```

I always do that to make sure everything works before running it as a service. If MeshCentral has any missing modules, it will install them and you can make sure everything works before you run it in the background.

**Comment by tlcarpenter** [comment]
The important thing is that it appears as though MC2 is successfully using MariaDB.

I just wanted to include the fact that I ran into some problems along the way, but those problems don't directly interfere with MC2 communicating with MariaDB.

The first problem I ran into is similar to or the same as #1936, i.e. I can't seem to get MC2 to install as a service when using npm to install MC2. Because of that I used the Windows installer to get a working installation of MC2 that I could use try to connect to MariaDB.

The second problem that came up was that after installing MC2 using the Windows installer and then editing config.json so that MC2 would use MariaDB, MC2 didn't seem to be creating and initializing the database in MariaDB. I stopped MC2 (which was installed using the Windows installer) from the command line, modified MC2's config.json to use MariaDB, then tried to start MC2 from the command line, but I didn't see the normal output one normally sees when MC2 starts up.  When I ran "node node_modules\meshcentral --debug db" MC2 then appeared to create and initialize the database in MariaDB.

The last problem that came up is that after getting MC2 to use MariaDB, if I started the MC2 Windows installer, used the 'edit configuration' option, and then clicked "Apply", the MC2 Windows installer closed abruptly. That behavior stopped after I restarted the computer. Again, this problem occurred after first trying to install MC2 with npm, and when that didn't work installing MC2 with the Windows installer, and then changing over to MariaDB, all without having restarted the computer before using the Windows installer to edit the MC2 configuration.

**Comment by Ylianst** [comment]
Ha, I got it. I need to address any issues with server installation that don't involve the Windows Installer. I consider the Windows installer to be a bit of a "noob" thing, it should not have to be used by experts. Thanks for the feedback.

Your probably one of the very few that uses MariaDB. Note that the auto-backups performed in "meshcentral-backups" will not include a backup of the database, so make sure to perform backups from time to time and keep an off-site backup of "meshcentral-data" as you can't recover your server without that.

**Comment by tlcarpenter** [comment]
You're welcome on the feedback. Many thanks to you and the rest of the team for your efforts.
