### ISSUE TITLE
rights bug with session sharing

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#1945]
Hello,

since the last update, I can no longer add a user with the rights to share a session with a guest.

I put the group with all the rights and the user in administrator but the share button does not appear

And is it possible to separate the rights to allow session sharing only?
This allows to give rights to details

version : 0.6.76

thank you

**Comment by laboiteajb** [comment]
I also just saw that desktop sharing on linux is no longer possible

The other tabs are present but no longer the desktop tab

In console : 
```
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-09-10T17:49:26.000Z"
}
```

**Comment by Ylianst** [comment]
I am having a hard time reading your messages.

"I can no longer add a user with the rights to share a session with a guest." - Can you explain exactly how you did that before?

"desktop sharing on linux is no longer possible" - The share button is not present or the desktop tab is not present or both?

**Comment by laboiteajb** [comment]
sorry, i'm french and i use google translate

To add the right to create an external sharing link on a device page
(https://ibb.co/dM1N9X3)

can add in the rights of the groups the possibility of giving access to allow the creation of a guest session sharing link
(https://ibb.co/FbXQMRV)

the desktop tab is no longer visible on a linux pc
(https://ibb.co/hYwmgGF)

**Comment by Ylianst** [comment]
I just published MeshCentral v0.6.77 with a possible fix, let me know if it works.

**Comment by laboiteajb** [comment]
- for the bug on linux it is fixed
- for the bug of the guest session sharing button it is fixed

Can you confirm for me: to give a user access to create a guest sharing link, you must check "Limited entry only"?

Is there a list detailing the rights of each option?

Thank you for your work and your speed

**Comment by Ylianst** [comment]
Right now I am pretty sure anyone with "Remote Control" rights to a device can create a guest link. If you want to create a new issue to have a separate right assigned for this, that would be fine. Note that you probably need both "Remote Control" and the new right to perform sharing as it would not make sense to allow a user to create sharing links without them also having rights to perform remote desktop sessions.
