### ISSUE TITLE
MeshCentral Router shortcut to Remote Desktop

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1946]
Hi Ylianst,

As required by yourself, a seperate issue for this one. I've tried to reformulate my questions to be as clear as I can as not native speaker :).

Please can MeshCentral router have the default to 'Mesh Desktop Protocol'? Or have it as a setting in MeshCentral Router to each ones preferences?

Also, MeshCentral Router closes right after a session initiated by the router gets closed. Since the Router is my 'start point of work' where I decide which PC needs maintenance, it is annoying it auto-closes after a remote session-end. Can that be disabled by setting or by default?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.78 with improved MeshCentral Router. Let me know if that works.

![MC2-MeshCentralRouterCustomizations](https://user-images.githubusercontent.com/1319013/98167024-3dc5bd00-1e9d-11eb-9166-a15000030581.png)

**Comment by jdvmanen** [comment]
This is amazing, thanks for the support!!

**Comment by Ylianst** [comment]
Your welcome. Feel free to close issues when done :) I will close this one.
