### ISSUE TITLE
Issues found while creating new device groups using AddDeviceGroup meshctrl command

### ISSUE THREAD

**Issue by Jtelagu** [Ylianst/MeshCentral#1947]
I noticed three interesting behavior while create groups using “AddDeviceGroup”  meshcentral command

1.	I can create groups with duplicate group name using “AddDeviceGroup”
2.	If there a duplicate group and if I try to add device to the device group it fails.
3.	ListDeviceGroup fails to provide device group name that does not have any device under it.    I think this problem is contributing to above two problems.

**Comment by Ylianst** [comment]
Hi. So you can have many device groups with the same name and that is ok, the device group name is not a unique identifier. So you can do this:

```
> node meshctrl AddDeviceGroup --name TestGroup
ok mesh//BhaBnAGis3umD0zy8$3KR3t7jftR5yG2rNlraqnfAwULbaLF1JgfQBM6wOgWBr4Q

> node meshctrl AddDeviceGroup --name TestGroup
ok mesh//s5rwMG7g9Webh855e5UpEnqgGsf1NxLNx2qGcrXhCKNeGRIXa5ny0InD1KXRoRXy

>node meshctrl AddDeviceGroup --name TestGroup
ok mesh//Fxfws3jSQ1B9EvglMfJmXt4DhVoQrlRC@sd9Y4zrrqt9Gn4S@68oPdHZx6Hoios3

>node meshctrl ListDeviceGroups
id, name
---------------
"3jmSVt4CrsjTw9UQsUxeQfVm2gnBnRyEbBcatbXU3080Hyw7OujrpEYz0lY$kFTd", "Empty Group"
"7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c", "Lab Computers"
"UE0kxwDwTXkSUtSvrF8W24iOkO@dRUOU5LMtPKA@powM68T7omPqSJM6gSXqLDKq", "MyHomeComputers"
"sjN2rO85LGJCEXxW50TUI1vOCr@9zVpE4A@9jrAcPjA7n531RHZVMGpksK1yWY4O", "Intel Amt Group"
"BhaBnAGis3umD0zy8$3KR3t7jftR5yG2rNlraqnfAwULbaLF1JgfQBM6wOgWBr4Q", "TestGroup"
"s5rwMG7g9Webh855e5UpEnqgGsf1NxLNx2qGcrXhCKNeGRIXa5ny0InD1KXRoRXy", "TestGroup"
"Fxfws3jSQ1B9EvglMfJmXt4DhVoQrlRC@sd9Y4zrrqt9Gn4S@68oPdHZx6Hoios3", "TestGroup"
```

Here I created 3 device groups with the same name and they showed up with different identifiers. When doing various commands, it's best to specify the device group identifier, but I do allow you to specify the device group name in some cases. If there are two device groups with the same name, that will understandably cause an issue.

I can't make you 3rd problem occur. When reporting an issue, it's best to always provide a step-by-step guide to how I can made the problem occur. Hope that helps.
