### ISSUE TITLE
Need better parameter escaping when calling with --launch

### ISSUE THREAD

**Issue by damonmaria** [Ylianst/MeshCentral#195]
I'm trying to pass to `--mongodb` a URL to Mongo Atlas (a hosted MongoDB service). Since the `mongojs` driver used by MeshCentral isn't 3+ it can't handle the new `mongodb+srv://` URLs it has to be a super long URL with lots of query options. Example: `...?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true`. At the moment when passing args through to `launchChildServer` only args with space in them are protected with double quotes. That means the `&` in the URL above gets interpreted by the shell and everything from the `&` onwards is missing from the `--launch` command line. 

Maybe use [child_process.execFile](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) instead as all these escaping issues go away. You'll need to specify `shell=true` to make the call the same but maybe that actually isn't needed? 

https://github.com/Ylianst/MeshCentral/blob/fdf361d6c3f4f5cf28dd462ed811bea5aae032f8/meshcentral.js#L158

**Comment by damonmaria** [comment]
The workaround is to quote the URL and add a space at the end:
`"mongodb://...&retryWrites=true& "`

**Comment by Ylianst** [comment]
Interesting. This is the next thing I am going to look into.

**Comment by Ylianst** [comment]
Published MeshCentral 0.3.2-u with a fix for this. Let me know if it works.

**Comment by damonmaria** [comment]
Works great thanks
