### ISSUE TITLE
Installed on Ubuntu 20.04.1 LTS MeshCentral version is 0.6.78 ?

### ISSUE THREAD

**Issue by kevev** [Ylianst/MeshCentral#1951]
Hello. I am not sure if I am running the latest vesion of MeshCentral as I do not see the 2fa option and some other things that the documentation refer to. Any ideas on how to upgrade if that is what I need to do? Thanks!

![image](https://user-images.githubusercontent.com/30596592/98184281-99a93980-1ecf-11eb-8f90-460ae166ab9d.png)
![image](https://user-images.githubusercontent.com/30596592/98184299-a9288280-1ecf-11eb-9137-e003929086ea.png)
![image](https://user-images.githubusercontent.com/30596592/98184577-57ccc300-1ed0-11eb-8d51-7a6e1b128b8a.png)

**Comment by kevev** [comment]
OK I fixed this by running with --cert.

Now I am attempting to connect to a temprarily running agent on a computer that is behind a seperate NAT'd network. Do I need a reverse proxy or something for this?

**Comment by kevev** [comment]
The agent connects to the server with no errors. When I launch novnc it attempts to connect continually, but never actually connects. The RDP button does nothing in Chrome or Firefox. In IE it askes for an app to open the app. lol :P

**Comment by kevev** [comment]
I'm slow. Please ignore my ignorance. I finally read the User Guide. :(

Sweet app! Thank You very much. :D

**Comment by Ylianst** [comment]
No worries. You need to install MeshCentral Router to have the RDP link to work.
