### ISSUE TITLE
Feature Suggestion: Files Search

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#1954]
Today I'm in a linux box using mesh, looking at Files... which is super convenient.  I'm looking for a particular file, and I have no idea where it is.  I'm about to bust out the CLI and search for it, and then I wonder if it's possible to have a search button to search for files recursively in Mesh Files...  Might be beyond the scope of Mesh..but I thought it would be cool...

Thanks as always for this killer product
Shane

**Comment by krayon007** [comment]
I just added this feature in the agent. It'll be released in an upcoming update. I tested it on Windows, Linux, macOS, and FreeBSD.

**Comment by southeasterntech** [comment]
Wow Bryan. You guys are amazing. Thanks! Now I dont need winSCP anymore! Mesh all the way!

Thanks,

Shane D. Lewis

**Comment by cgb** [comment]
Just Just had a look at the agent code, it's exactly what I'd do via powershell but now via the agent.  Very handy feature!  Looking forward to testing it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.86 with Bryan's file search. Feedback appreciated.

![MC2-FileFind](https://user-images.githubusercontent.com/1319013/98906508-042f1c00-2472-11eb-8a5e-75329fe1e8a0.png)
