### ISSUE TITLE
Unable to upgrade version

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#1957]
A few days ago I performed a new installation followed by proper backup's recovery, from then on all seems good except the upgrade feature: tried many times via CLI and via GUI, version remains the start-up one (0.6.72)...any ideas? :disappointed:

Thanks!

**Comment by Ylianst** [comment]
Take a look at #1938 and let me know if that helps.

**Comment by amenolo** [comment]
That command returns

```
root@mesh:/opt# npm dist-tag ls meshcentral
latest: 0.6.79
stable: 0.5.81
```

which matches GUI output

![immagine](https://user-images.githubusercontent.com/29974944/98335517-67015d00-2005-11eb-9b35-e71eb702f85c.png)

Systemd log seems good:

```
Nov 05 22:37:08 mesh node[19269]: MeshCentral HTTP server running on port 8081, alias port 443.
Nov 05 22:47:09 mesh node[19269]: Starting self upgrade...
Nov 05 22:47:11 mesh node[19269]: Update completed...
Nov 05 22:47:14 mesh node[19269]: MeshCentral HTTP redirection server running on port 8082.
Nov 05 22:47:14 mesh node[19269]: MeshCentral v0.6.72, WAN mode, Production mode.
```

I can't see any error around, really...maybe my mistake...
Wondering if it might have something to do with the fact that now is running in a LXC (privileged) instead of a classic VM...

**Comment by Ylianst** [comment]
I see. Looks like NPM is working for you. The next issue is that for the self-update to work, MeshCentral needs to have permissions to write it's own files. This is not the greatest as far as security. If you run MeshCentral as a user that has limited privileges, it's great for security but the self-update will not work just like your reporting. This is normal and expected.

If you are in this situation, I would probably keep it like this and keep your server running with restricted permissions and perform the server update manually. Something like:

```
systemctl stop meshcentral
mv node_modules node_modules_backup
npm install meshcentral
systemctl start meshcentral
```

You can make yourself a shell script to automate this and you login with higher permissions and do this from time to time. This also has the benefit that if something goes wrong, you can put the old "node_modules" back and go back to a known good version.

Hope that makes sense.

**Comment by amenolo** [comment]
> If you run MeshCentral as a user that has limited privileges (...)

MC instance is running as root (as was before) so definitely not my case, sorry for not making this clear earlier...

Anyway I just took a shot at your hint but oddly enough the version still did not upgrade and only removing all files and restarting at all from scratch did the trick...

I will take a look at next upgrade and I'll give you further feedbacks.

Thanks!

**Comment by Ylianst** [comment]
I just published MeshCentral v0.6.80 so you can try now. Very curious. Let me know what you see on this one.

**Comment by amenolo** [comment]
No luck, same weird behavior...I'm going to perform some other cross tests...

**Comment by Ylianst** [comment]
So, you are saying that if you type:

`npm dist-tag ls meshcentral`

You see the latest version, but if you install using

`npm install meshcentral`

You get the old version. If you type:

`npm install meshcentral@1.2.3`

You get the expected latest version? Seems like a weird bug with NPM. You can do `npm help` and look at clearing the NPM cache or you are in some location in the world that has a server with older versions. Not sure. If you are right, I should be specifying the version when doing a "latest" update.

**Comment by Ylianst** [comment]
Ok, starting with MeshCentral v0.6.81 the self-update system will always specify the exact version in the `npm install` command. So you need to update once more manually and after that it should (hopefully) work better.

Up to now, if you selected "latest" it would call `npm install meshcentral` with no version number.

**Comment by amenolo** [comment]
> So, you are saying that (...)

Correct!

> Seems like a weird bug with NPM (...)

Not really sure about any assumption here since I'm facing a "mint condition" scenario i.e. OS and programs installed from scratch, in fact npm upgrading feature is working fine for others packages starting from npm itself (no need to clear cache or something).

To clear up doubts:

[![asciicast](https://asciinema.org/a/L6omx9yjGFQeZoE9bmLI9TQ8p.svg)](https://asciinema.org/a/L6omx9yjGFQeZoE9bmLI9TQ8p)

> starting with MeshCentral v0.6.81 the self-update system will always specify the exact version in the npm install command

Much appreciate your willingness and yet...still wondering how's that no one else - you first - doesn't seem affected by such a weird sudden issue which moreover seems to be reproducible and replicable in my scenario at least...I'm missing something...

**Comment by Ylianst** [comment]
I have see a case where I would publish a new version on NPM and very quickly try to update my servers. It would show the updated version on the UI, but would not update to the latest until I specified the version just like you report. However, this would only last a few minutes until NPM servers updated. It seems like you have a permanent case of this. In any case, if you select latest and it shows a specific version, it's normal the server would request the version you selected, so this is a good change.

**Comment by whalehub** [comment]
> The next issue is that for the self-update to work, MeshCentral needs to have permissions to write it's own files. This is not the greatest as far as security. If you run MeshCentral as a user that has limited privileges, it's great for security but the self-update will not work just like your reporting. This is normal and expected.

@Ylianst I ran into this issue last year and eventually tracked the cause of the issue down to NPM requiring a user to have a home directory for caching package downloads and version infos in `~/.npm`. Just for reference, this is my hardened systemd file for MeshCentral and the self-update feature works fine with it:

```
[Unit]
Description=MeshCentral
Documentation=https://www.meshcommander.com/meshcentral2
Requires=mongod.service
After=mongod.service network.target

StartLimitIntervalSec=14400
StartLimitBurst=10

[Service]
Restart=on-abnormal

Type=simple

User=meshcentral
Group=meshcentral

Environment="NODE_ENV=production"

ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral

KillMode=control-group
KillSignal=SIGINT
TimeoutStopSec=60s

LimitNOFILE=infinity
LimitNPROC=512

CapabilityBoundingSet=
LockPersonality=true
MemoryDenyWriteExecute=false
NoNewPrivileges=true
PrivateDevices=true
PrivateNetwork=false
PrivateTmp=true
PrivateUsers=true
ProtectControlGroups=yes
ProtectHome=true
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=strict
ReadWritePaths=/opt/meshcentral
RemoveIPC=true
RestrictAddressFamilies=~AF_PACKET
RestrictRealtime=true
SystemCallArchitectures=native
UMask=0077

[Install]
WantedBy=multi-user.target
```

```
whalehub@pdh:~# grep meshcentral /etc/passwd
meshcentral:x:502:502::/opt/meshcentral/meshcentral-home:/usr/sbin/nologin
```

**Comment by amenolo** [comment]
Meanwhile...upgrade from 0.6.81 to 0.6.84 done flawless via GUI 👍 

Much appreciated @whalehub 's post too.
