### ISSUE TITLE
Safety warning for agent installation

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1958]
Hi Ylianst,

If a help-requester downloads the agent, Chrome / edge /  report a warning:
![image](https://user-images.githubusercontent.com/68591647/98344717-f1e95400-2013-11eb-85a1-b314c5284685.png)

(Print screen in dutch, but it says something as 'download blocked because this can be harmful for your device').

![image](https://user-images.githubusercontent.com/68591647/98344794-0decf580-2014-11eb-8f84-077e1269a6de.png)
clicking the three-dots enables 'behouden' which is 'keep'. But then the pain hasn't ended;

![image](https://user-images.githubusercontent.com/68591647/98344863-26f5a680-2014-11eb-8c5e-3e0678631512.png)
again a warning that 'this app is probably harmfull'. User has to click ''Meer weergeven" or 'Show more' and:

![image](https://user-images.githubusercontent.com/68591647/98344926-3bd23a00-2014-11eb-80dc-d5d051e85212.png)

and click 'toch behouden' or 'keep nevertheless'.

Pain not at the end, because the browser has now stopped stopping me :). Windows comes in when the agent is opened:

![image](https://user-images.githubusercontent.com/68591647/98345023-63290700-2014-11eb-8a36-0f87a3b7da44.png)
Windows defender is blocking. If I click on 'Meer informatie' which translates to... 'more information' : 

![image](https://user-images.githubusercontent.com/68591647/98345095-7b008b00-2014-11eb-9325-7b922deedfd0.png)

I can finally click 'Toch uitvoeren' or 'Execute nevertheless'.

What can I do to avoid all these confusing safety warnings for the user at the other end. The user is already having a problem, thats why he calls me. Now I've to guide him about 4 minutes (each browers has other texts to inform about risks).

**Comment by amenolo** [comment]
Recurring issue: due to understandable reasons - already explained in other closed issues - agents are using a self-signed certificate but you're allowed to sign them with a trusted certificate if available to you, eg. #1622

**Comment by jdvmanen** [comment]
Thanks
