### ISSUE TITLE
Small UI fix in MeshCentral Router needed

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#1959]
I am on MeshRouter version 1.1.7613.22744 which came with version 0.6.81 of the MeshCentral server. 

It is working great, so well done on that, but I have noticed when I click Add Map, the PuTTY and RDP ports are switched. If you continue with the mapping, the mappings screen shows the correct port, so everything looks wired correctly to me. 

If you pick RDP it shows trying to use port 22 and if you choose PuTTY it wants to use port 3389. I have included screenshots to help see the issue if my description doesn't make a ton of sense. 

![AQg8dRXdgZ](https://user-images.githubusercontent.com/51446227/98449740-26d4d400-2104-11eb-9456-dec62a9126f3.png)
![Cwed360Vpt](https://user-images.githubusercontent.com/51446227/98449741-28060100-2104-11eb-8b4a-18803995b2ce.png)

**Comment by Ylianst** [comment]
Good one. Just fixed it in GitHub. next time I update MeshCentral Router it will be fixed.

**Comment by githubbiswb** [comment]
My container maintainer just put out the update to 0.6.98 and this is fixed, closing the issue
