### ISSUE TITLE
UI Fix in MeshCentral Router

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#1960]
Not a duplicate I promise!

I am on MeshRouter version 1.1.7613.22744 which came with version 0.6.81 of the MeshCentral server.

When you have Meshrouter open and my guess is installed you get a new button that says Cancel Auto-Close, but this button covers up and makes impossible to connect to the devices that are at the bottom of the list when you have more than 12 options to connect to. You can scroll it up to get to ones in the middle, but the bottom two are always covered. 

You can filter the list to get them to show, and you can also use your arrow keys to put the focus on them and of course make your mappings, but you really don't have any idea of what is under there when you do that, nor would you know the name to filter. 

![2C9vwaPICg](https://user-images.githubusercontent.com/51446227/98449811-2852cc00-2105-11eb-9ef3-edb0656bec4a.png)

**Comment by Ylianst** [comment]
What I can do is to automatically cancel the auto-close anytime you click on the device list or switch to the mappings tab. The goal of auto-close is to close MeshCentral Router when you have no need to interact with it. Would that be ok?

**Comment by githubbiswb** [comment]
Ylianst, sounds good to me. Thank you for all your hard work

**Comment by jdvmanen** [comment]
Can auto-close also move to the settings-tab? I will use 'Cancel auto-close' without exception?

And maybe the auto-close can be a logo, like the blue S in the footer?

**Comment by vitko-bg** [comment]
What about having "Show in tray" also in setting, not on S logo?
Thanks

**Comment by Ylianst** [comment]
Ok, did a bunch of UI changes to MeshCentral Router, will be in MeshCentral v0.6.83. Let me know what you think.

**Comment by githubbiswb** [comment]
Just updated to 0.6.98 and it looks great to me although I don't want to close it as some other suggestions came in and I don't want to speak for them being fixed since I only had the one issue to bring up. I see the tray thing that @vitko-bg mentioned but not sure if this all works for @jdvmanen, maybe he can comment and say its good and then I can close?

**Comment by jdvmanen** [comment]
a yes, the changes work for me! Sorry, I went father the past day's and didn't find time to answer ;-)
