### ISSUE TITLE
[Question] Intel AMT over WLAN on Linux

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#1961]
This is a general question about the features supported by Intel AMT on Linux.

The first time I experimented with Intel AMT on my vPro-enabled NUC, I installed Windows 10 on it and everything worked as expected. The AMT module and Windows were able to use the WiFi module at the same time after installing the AMT driver.

The second time around, I installed Debian 10 on the NUC and noticed that the AMT module was unable to use the WiFi module while it's in use by the operating system, which resultsed in AMT being unable to establish a CIRA connection with MeshCentral.

I researched whether this is expected behavior on Google and found an [Intel document](https://www.intel.com/content/dam/support/us/en/documents/technologies/intel_amt_linux_enablement_guide_revision_1_1.pdf) from 2013 which says that Intel AMT is not supported over WLAN in section 3.

![vivaldi_2020-11-08_17-24-17](https://user-images.githubusercontent.com/44198148/98470621-4133ae00-21e7-11eb-82dc-e3a1aeaf55a9.png)

Is this information up-to-date or was support for this configuration added at some point in the last seven years?

**Comment by jsastriawan** [comment]
That's still valid Aaron. Linux wifi driver doesn't coexist well with AMT.

**Comment by whalehub** [comment]
@jsastriawan Thanks for the quick response. I'll probably go back to using Windows 10 on the NUC then.
