### ISSUE TITLE
Impossible to download files or folders during remote control

### ISSUE THREAD

**Issue by eddie31100** [Ylianst/MeshCentral#1962]
Hi,
We use since a few time a Mesh server in my office.
I've started testing it and I've found one annoying thing : it seems it's impossible to download a file or a folder from the distant computer to the local computer.
In the other direction (local >>> distant), it's possible. But in distant >>> local direction, I've not succeeded.
It's sad because it can be useful and it's possible on most remote assistance softwares (VNC, TeamViewer, LanDesk,...).

Could it be possible to implement this function?

**Comment by krayon007** [comment]
Which OS and server version are you running? What error are you getting? I just tested this on Windows and Linux, and file download seems to work fine during remote control... Do you have user consent enabled?

**Comment by eddie31100** [comment]
I don't know for the server because I'm not the one who mounted it and I can not access it. I just have user rights to take remote control.
It's strange for me that you say it's working because me and all of my colleagues have the same problem : the functionality (a simple button) does not exist!
There is a "Download" button which can permit to send files or folders, but no button to do the same in the other direction.

![image](https://user-images.githubusercontent.com/74154634/98483919-2162b100-220c-11eb-8918-8a6e7a09d847.png)

**Comment by Ylianst** [comment]
Hi. Your providing very little detail on the problem. Note that you have to click on the file to download it. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/98483946-dc655d00-21c0-11eb-931a-a75c4a7c19ec.png)

**Comment by eddie31100** [comment]
Hi Ylianst, and thanks! I was checking the files and folders, so it did not work...
It's ok when just clicking on it (so simple...).
And I've found that to download a folder, we must check it and then click on "Zip" button to zip it before downloading.
So sorry and many thanks.

**Comment by Ylianst** [comment]
Exactly, I just going to add that there is a ZIP feature that is useful for downloading many files at once.
