### ISSUE TITLE
extra link in station details

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#1964]
![image](https://user-images.githubusercontent.com/68591647/98544952-fec8aa80-2294-11eb-840a-1c6b01cc2492.png)

One image tells more than 1000 words... can you add a link to open up 'Remote Desktop' with oneclick via the MeshCentral router.

**Comment by si458** [comment]
this can now be achieved by adding a custom meshremotelink
use the following inside your `config.json` and under `domain`
```
      "deviceMeshRouterLinks": {
        "extralinks": [
          {
            "name": "MCRDesktop",
            "protocol": "mcrdesktop"
          }
        ]
      }
```
