### ISSUE TITLE
feature request - MC2 domain authorization via sspi

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#1965]
Would it be possible to restrict access to an MC2 domain by requiring membership in an AD group returned by node-sspi?

**Comment by Ylianst** [comment]
Yes, in one of the domains in the config.json add this line:

```
"auth": "sspi",
```

MeshCentral must be running on a Windows computer that is part of that domain. I use for a long time now on one of my servers and it seems to work well.

**Comment by tlcarpenter** [comment]
I looked over the documentation for node-sspi, which mentions an option "retrieveGroups". I was looking for a way to assign users to MC2 device groups base on membership in an AD security group, something like 'if req.connection.userGroups includes <AD group allowed access to MC2 device group>, then the user is a member of the MC2 device group'. I looked through the MC2 code a little but didn't find any instances of "retrieveGroups". Also, I see there are other requests that seem to be touching on similar/related aspects, i.e. #1383, #1409, #1869, and #1971 

The "MC2 domain" aspect of my initial question had to do with me thinking that it might be possible to define different domains in MC2's config.json that correspond to each AD OU; that way if MC2 was able to use node-sspi's "retrieveGroups" option, it might be possible only allow AD users that are assigned to that AD OU to log in to the corresponding MC2 domain. This assumes that different "domains" sections in config.json can all use "auth": "sspi" without conflict.

Alternatively, would I be able to achieve the kind of control I'm looking for by using "auth": "ldap" instead? Would it work to create separate "domians" sections in config.json for each AD OU and use an appropriate LDAP filter as a way to restrict access to an MC2 domain to users that are members of an AD security group?

**Comment by Ylianst** [comment]
Oh, sorry. I missed that. Right, there is no AD group support right now. You can create your own user groups in MeshCentral but right, there is no AD groups. I really need to setup a test LDAP server as some point, I have no such test server and so, I can't do any LDAP testing which is terrible and the LDAP learning curve seems pretty steep. I have no idea if your domain/LDAP filter thing would work.

**Comment by tlcarpenter** [comment]
Can one define unique "auth" entries (configured to use either "sspi" or "ldap") for each domain defined in the "domains" section in config.json, or, does config.json only support one "auth" entry that is used globally?

**Comment by tlcarpenter** [comment]
While I haven't tested my configuration extensively, defining multiple domains in the "domains" section of config.json, each with its own "auth": "ldap" entry and with its own "ldapoptions" section, does seem to be working. The config.json file I'm using (below) uses LDAP search filters that are specific to the "Users" OU for the two departments, restricting access to each of the MC2 domains to the AD users in their respective department's "Users" OU.


{
   "settings": {
      "cert": "< MC2 server FQDN >", 
      "wanonly": true, 
      "_minify": true, 
      "minify": true
   }, 
   "domains": {
      "": {
         "newaccounts": false
      }, 
      "<department 1>": {
         "newaccounts": false, 
         "auth": "ldap", 
         "ldapusername": "sAMAccountName", 
         "ldapuserkey": "sAMAccountName", 
         "ldapoptions": {
            "url": "ldaps://< AD DC FQDN >:636", 
            "bindDN": "CN=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX,DC=XXXXX,DC=XXXXX", 
            "bindCredentials": "< password >", 
            "searchBase": "OU=YYYYY,OU=YYYYY,OU=YYYYY,OU=YYYYY,DC=YYYYY,DC=YYYYY,DC=YYYYY,DC=YYYYY", 
            "searchFilter": "(&(objectclass=user)(sAMAccountName={{username}}))"
         }
      }, 
      "< department 2 >": {
         "newaccounts": false, 
         "auth": "ldap", 
         "ldapusername": "sAMAccountName", 
         "ldapuserkey": "sAMAccountName", 
         "ldapoptions": {
            "url": "ldaps://< AD DC FQDN >:636", 
            "bindDN": "CN=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX,DC=XXXXX,DC=XXXXX", 
            "bindCredentials": "< password >", 
            "searchBase": "OU=ZZZZZ,OU=ZZZZZ,OU=ZZZZZ,OU=ZZZZZ,DC=ZZZZZ,DC=ZZZZZ,DC=ZZZZZ,DC=ZZZZZ", 
            "searchFilter": "(&(objectclass=user)(sAMAccountName={{username}}))"
         }
      }
   }
}
