### ISSUE TITLE
All Displays not displaying all displays

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#1966]
Version 0.6.81

When connecting to a Windows PC with multiple displays only one display is showing, switching between Display 1 and 2 does work.
Happening on all computers with multiple (2) Displays.

**Comment by Ylianst** [comment]
Is this like described in #1984?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.88 with a fix. Let me know if it works.

**Comment by Ylianst** [comment]
Ok, this seems fixed according to #1984.
