### ISSUE TITLE
Azure SSO - Case Sensitivity

### ISSUE THREAD

**Issue by flyRV** [Ylianst/MeshCentral#1968]
I have observed an issue applying User Group Memberships to users 'auto-created' when logging in via Azure SSO whereby an error of "user cannot be found" is reported when the user has mixed case. Mesh recognizes the user as "user//~azure:User@domain.com".

 I was able to fix this by deleting the user within Mesh, changing the case, and logging in again--now with Mesh recognizing the user with all lower case (user//~azure:user@domain.com) and no error assigning group memberships.

I was unable to find previous mention of this, perhaps one possibly related to LDAP, and so if if this has been previously addressed or brought up, please pardon me and close this issue.

**Comment by Ylianst** [comment]
Thanks for the report. Just published MeshCentral v0.7.6 with fixed for this. Let me know if it works.

**Comment by flyRV** [comment]
Confirmed this has fixed issues adding users to groups, as well as adjusting 'Server Permissions' to users with mixed case in the 'User Identifier' field.
