### ISSUE TITLE
Can't connect to Computer with changed admin account

### ISSUE THREAD

**Issue by kindlydodo** [Ylianst/MeshCentral#1970]
Steps to reproduce:

1. change the admin account of the intel amt setting:
   * username = "somename-name"
   * password = cr$Vr9FXi%BtR*A

Now i try to connect trough Mesh Commander. I get an Error:  

_authentication error_

But, i can successfully login via Intel AMT in the Browser (Basic Auth)

When i set the admin account password to the old one, everything working as expected

**Comment by Ylianst** [comment]
Before I look into this more, did you set the new admin name in MeshCommander?

![image](https://user-images.githubusercontent.com/1319013/98780794-2eb5a200-23aa-11eb-9a3f-ae046d1a77e7.png)

**Comment by koalifyed** [comment]
Yes i did

**Comment by si458** [comment]
closing this as stale but also you should ask future issues with meshcommander in its repo
https://github.com/Ylianst/MeshCommander
