### ISSUE TITLE
Remote Desktop function does not work when connected over CIRA (from remote network)

### ISSUE THREAD

**Issue by Strider3000** [Ylianst/MeshCentral#1976]
First off, MeshCentral is great. I've been using it on a Linux VM and it's saved my butt at least three times. Kudos for the nice solution. Currently I'm using MeshCentral 0.6.84. The computer in question is a Lenovo M910Q Tiny implementing Intel AMT ME v11.8.79 activated in Admin Control Mode (ACM).

I have a computer I configured for CIRA through MeshCentral's new automatic CIRA provisioning function while on my network (very nice btw). Remote Desktop worked great while the computer was on the local network. Since then I've re-located the computer to my friend's house several thousand miles away. CIRA still connects and I can still manage the computer remotely (including power functions, which have been awesome to use) - however, Remote Desktop no longer connects at all. Even when I sit and wait for several minutes, I get nothing but a blank screen.

Is Remote Desktop not expected to work with CIRA when connecting over the internet? Are there any special considerations (bandwidth, latency, static NAT) that need to be tweaked for Remote Desktop with CIRA to work in this scenario? Is this use case simply not supported, or could it be a use case to be supported in a future version of MeshCentral? Any feedback is appreciated.

**Comment by jsastriawan** [comment]
Quick check: is the status of remote desktop 'Connected'  after you click connect?

If it does, is this machine display port (HDMI/DP) connected to a monitor?

AMT Remote Desktop will capture whatever is displayed on connected monitor. It nothing is connected, nothing is displayed and nothing AMT can capture.

**Comment by Strider3000** [comment]
Great question.
It does show "Connected" with a blank screen when I attempt to connect.
The primary interface on this unit is VGA, and there is currently no monitor connected.
Will a dummy plug make this plug?

**Comment by jsastriawan** [comment]
Yes, typically dummy plug will work. It emulates connected monitor. Some NUC has built in capability to emulate persistent monitor connection but I don't thing the Tiny has that capability.

**Comment by Strider3000** [comment]
I never saw the option in the BIOS to emulate persistent monitor.
I have ordered a dummy plug off Amazon and I'll see if that makes a difference. 
If so, I'll update this issue and close it.

**Comment by Ylianst** [comment]
I think this is the correct answer. If there is no monitors attached, Intel AMT KVM may not work and a dummy HDMI will fix it.
