### ISSUE TITLE
Remote computer client update and versioning not accessible in the dashboard

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#1979]
I'm unclear on how (if?) the remote client agent updates when a new version has been released.  Is there a version check that happens occasionally?  Do we have to manually update?  Is there an action or trigger for the updates in the dashboard somewhere?

Also, I don't see anywhere in the dashboard where we can see the currently installed version.  Is that available?  

I was using 0.6.82, but had to downgrade to 0.5.81 yesterday to get around a couple of errors.  Unsure if they were related to the version or something else, as I didn't have time to explore it, but I'm upgrading again to 0.6.85 so I can check things out more.

**Comment by Ylianst** [comment]
The server will automatically update agents to match the agents in the server version, so if you downgrade a server, all agents will also be downgraded if needed. Starting with v0.6.85 the server has a new set of MeshAgents and you can use the "versions" command in the agent console to see the agent compile and commit time . Hope that helps.

![image](https://user-images.githubusercontent.com/1319013/98905699-b534b700-2470-11eb-9e20-b729d4be620b.png)

**Comment by mikecole79** [comment]
Nice, thank you.  I appreciate the info!  As usual, awesome product.  I love the bejeepers out of it!
