### ISSUE TITLE
downloading  files does not work 

### ISSUE THREAD

**Issue by leok0** [Ylianst/MeshCentral#1981]
downloading files does not work in version 0.6.70,
upload files is work perfectly,
from the meshcentralrouter if it works,
in version 0.5.81 it worked perfectly

**Comment by Ylianst** [comment]
Checking now. Are you downloading from the web site or MeshCentral Router?

**Comment by Ylianst** [comment]
I just tested with the web site and MeshCentral Router and upload/download both work for me. When filing a bug, please include the exact steps to make the problem happen. Thanks.

**Comment by leok0** [comment]
hi, thanks, now i upgrade to 0.6.87, and recived 500,in older version i
recived 200 and not downloaded, in 0.5.81 is work fine, i use citrix adc as
reverse proxy.

the product is the best remote control tool ever, and i recommended to all
community of infrastructure managers in israel.

**Comment by Ylianst** [comment]
Oh perfect. Nice to hear. If you run into any other issue, please don't hesitate to report it, but please provide steps and data so we can make the same situation happen here. Screenshots help a lot.

**Comment by leok0** [comment]
![Capture](https://user-images.githubusercontent.com/21316658/99045269-bdd4dc80-2599-11eb-93a3-8b7a8206c961.PNG)

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.89 with a fix for file download, but not sure if it's related to this issue. If you see any server exceptions in the "My Server" tab in "Show server error log", let me know.
