### ISSUE TITLE
Nginx Reverse proxy : Failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by Frantzd** [Ylianst/MeshCentral#1983]
Hello,

I use Nginx 1.14.0 (Ubuntu 18.04) configured as a reverse proxy not on the same machine as meshcentral, 
but on its own server, and proxying several other virtual hosts.
When I try https://mesh.mydomain.fr in the browser, I get "502 Bad Gateway" 

- Here are the nginx logs :

==> mc-error.log <==
2020/11/13 11:22:34 [error] 26611#26611: *1033752 connect() failed (111: Connection refused) while connecting to upstream, client: client.browser.wan.ip, server: mesh.mydomain.fr, request: "GET / HTTP/1.1", upstream: "http://mesh.server.lan.ip:4430/", host: "mesh.mydomain.fr"
2020/11/13 11:22:34 [error] 26611#26611: *1033752 connect() failed (111: Connection refused) while connecting to upstream, client: client.browser.wan.ip, server: mesh.mydomain.fr, request: "GET / HTTP/1.1", upstream: "http://mesh.server.lan.ip:4430/50x.html", host: "mesh.mydomain.fr"

==> mc-access.log <==
client.browser.wan.ip - - [13/Nov/2020:11:22:34 +0100]  mesh.mydomain.fr "GET / HTTP/1.1" 502 166 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"

==> mc-error.log <==
2020/11/13 11:22:34 [error] 26611#26611: *1033752 connect() failed (111: Connection refused) while connecting to upstream, client: client.browser.wan.ip, server: mesh.mydomain.fr, request: "GET /favicon.ico HTTP/1.1", upstream: "http://mesh.server.lan.ip:4430/favicon.ico", host: "mesh.mydomain.fr", referrer: "https://mesh.mydomain.fr/"
2020/11/13 11:22:34 [error] 26611#26611: *1033752 connect() failed (111: Connection refused) while connecting to upstream, client: client.browser.wan.ip, server: mesh.mydomain.fr, request: "GET /favicon.ico HTTP/1.1", upstream: "http://mesh.server.lan.ip:4430/50x.html", host: "mesh.mydomain.fr", referrer: "https://mesh.mydomain.fr/"

==> mc-access.log <==
client.browser.wan.ip - - [13/Nov/2020:11:22:34 +0100]  mesh.mydomain.fr "GET /favicon.ico HTTP/1.1" 502 166 "https://mesh.mydomain.fr/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"

- I run meshcentral like this :
```
#/opt/meshcentral } node ./node_modules/meshcentral --cert mesh.mydomain.fr
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.13, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on mesh.mydomain.fr:4433.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on mesh.mydomain.fr:443.
```

Here is my config, based on the meshcentral2 user guide :

- Server : MeshCentral v0.5.13 on Debian 10

  - config.json :
```
{
  "settings": {
  "Cert": "mesh.mydomain.fr",
  "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
  "Port": 4430,
  "AliasPort": 443,
  "RedirPort": 800,
  "AgentPong": 300,
  "TlsOffload": "proxy.server.lan.ip"
 },
 "domains": {
   "": {
     "certUrl": "https://proxy.server.lan.ip:443/"
   }
 }
}
```

- Nginx config file for the meshcentral virtual host :

```
server {
    listen 80;
    server_name mesh.mydomain.fr;

    location / {
        proxy_pass http://mesh.server.lan.ip:800;
        proxy_http_version 1.1;
        # inform MeshCentral about the real host, port and protocol.
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
        listen 443 ssl;
        server_name mesh.mydomain.fr;

        #MeshCentral uses long standing websocket connections, set long timeout.
        proxy_send_timeout 330s;
        proxy_read_timeout 330s;

        ssl on; # obsolete a partir de la version 1.15.0
        ssl_certificate /etc/nginx/ssl/mesh.mydomain.fr.pem;
        ssl_certificate_key /etc/nginx/ssl/mydomain.fr.key;
        ssl_session_cache shared:WEBSSL:10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        location / {
                proxy_pass http://mesh.server.lan.ip:4430;
                proxy_http_version 1.1;

                # Allows websockets over HTTPS.
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                # Inform MeshCentral about the real host, port and protocol
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
        access_log /var/log/nginx/mc-access.log combined2;
        error_log /var/log/nginx/mc-error.log;
        error_page 404 /404.html;
} 
```

I've tried several other possibilities, but nothing works :disappointed: 

Regards.

**Comment by Ylianst** [comment]
H. I few things here. First, you don not need to specify `--cert` when you run MeshCentral since you already have this in the config.json file. So you can just do `node node_modules/meshcentral` to run the server.

Next, when you run the server, it shows this line:

```
MeshCentral HTTPS server running on mesh.mydomain.fr:443.
```

So, MeshCentral is listening on port 443 and using TLS. However your config.json indicates it should be listening on port 4430 with alias to 443 without TLS. It seems MeshCentral is ignoring your config.json completely. Are you sure you put the config.json in the meshcentral-data folder and it has the right name?

Also, in "tlsoffload", your going to have to put the private IP address(s) of your reverse proxies. I don't think the DNS name will work. So something like:

```
"TlsOffload": "192.168.1.100,192.168.1.101"
```

In addition, you have this line:

```
"certUrl": "https://proxy.server.lan.ip:443/"
```

Again, when you start the server, there is no indication it's trying to load the certificate. So, the entire config.json is being ignored. Not sure why.

Your on the right track for configuring everything. But since MeshCentral is listening on 443 and NGINX is trying to connect to 4430, it's normal your getting connection errors.

Hope that helps,
Ylian

**Comment by Frantzd** [comment]
Hello,

In fact, I also suspected that my config.json file was being ignored.

Now that it's in the right place and with the right settings, everything seems to work fine :-)

I close this issue.

Thank you very much for your reactivity! 

Best regards.
