### ISSUE TITLE
Bug: Multiple Displays not rendering correctly when All Displays selected

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#1984]
I don't see any posts about this at the moment so here goes. I've got an issue where, when I connect to a machine with multiple displays I see that it is supposed to be showing all displays but I'm only seeing one or one and part of the other. This isn't a huge deal as I typically swap between displays anyways but thought I'd mention it. Screenshots below for reference.

![image](https://user-images.githubusercontent.com/417006/99080491-0040ee00-2587-11eb-9838-efbb33548f3d.png)

Note: The black is Display 1 and the wallpaper to the right is the login screen showing on Display 2

**Comment by krayon007** [comment]
What server version are you using? What OS version is the agent running on?

**Comment by Ylianst** [comment]
I am not seeing this on any of my devices. Are you saying that this is a new issue you did not see before? Also, the your seeing this issue on agents running on these operating systems? "Windows 10 (1909, 2004, 2009) and Windows 7 (7601)"

**Comment by krayon007** [comment]
Just to clarify... You are saying it correctly shows each individual display, when you select it, but it does not correctly render the "all display" view?

**Comment by krayon007** [comment]
I think I was able to reproduce this... Can you verify this behavior:

When you connect KVM, you get the display showing as above... But if you select any of the individual displays, then select "All Displays", it correctly renders the All Displays view?

**Comment by asasin114** [comment]
Close, sometimes going back to All Displays works but not all the time.

________________________________

**Comment by Ylianst** [comment]
Ok, I am seeing the same problem! Working on it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.88 with a fix. Let me know if it works.

**Comment by asasin114** [comment]
Fix confirmed! Thank you so much @Ylianst! You're the best!
