### ISSUE TITLE
version 0.6.88 cannot download file from the Files tab

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#1986]
After updated to version 0.6.88, the download file action in the Files tab (by cicking on a file) will force a logout.

**Comment by asasin114** [comment]
Can confirm running version 0.6.88 and attempting to download a file from a Windows Server 2012 R2 server (Haven't tried with anything else yet.

**Comment by Ylianst** [comment]
I will be releasing a fix later tonight (US Pacific time)

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.89 with a fix for this. Let me know if it works.

**Comment by asasin114** [comment]
Confirmed fixed for me!
