### ISSUE TITLE
Find Files feature doesn't seem to be always functional

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1987]
I was doing some testing tonight with the new Find Files feature.  I tried it under different clients running various flavors of Windows.  At first I thought the issue was just under Server 2019.  But, as I do more testing, it seems to be under any variation of Windows.
I'm trying to duplicate the issue to narrow it down to something specific- such as trying to search in a folder with numerous files/folders.  Or if it's just when using wildcards.  But I'm coming up empty in regards to anything specific.

What I'm seeing is that the search just doesn't always work.  In some cases (like on this Server 2012 box I'm connected to as I compose this) any file I try to search for just results in an empty results window but with the 'Search' button greyed out (almost like it's still trying to search). I tried searching in a single folder that only has about 40 files and no subfolders.  First I tried with a wildcard (such as *.txt).  Then I tried searching for a specific file that I can see in the list.  Same results in both cases- empty search results with the 'search' button greyed out. 

On a Server 2019 box the results are almost the same- only difference is the 'search' button goes grey once you click it. Then, after a couple seconds, it comes back to being selectable again.  But with no results.  
I tried it on Server 2008, Server 2012, Server 2016, and Server 2019.  Not working under any of those.  Also doesn't appear tob e working under Windows 7. 

It seems to be working correctly under Windows 10 though.  

Very odd!

**Comment by krayon007** [comment]
Thanks for the feedback, I'll take a look. For the windows version, I did most of my testing on Windows 10, lol. When the button is selectable, that means the search completed. I'll take a look under those other versions of windows to see what I can find. I used a simple powershell command under the covers for windows, so it should be pretty easy to see what's going on.

**Comment by krayon007** [comment]
What kind of search query did you use? I tried *.doc on Windows Server 2019, and it seems to have worked..

**Comment by krayon007** [comment]
I tried *.doc on windows server 2016, and it worked too... Maybe you have some sort of policy to disallow powershell?

**Comment by PathfinderNetworks** [comment]
No special policies in place on any of the servers.  Here's a screen grab of a search I tried just now.  This is on a Server 2019 box.  In this folder I searched for *.zip.  No results found- even though you can definitely see there is at least one zip file present in the folder.  
![file_find](https://user-images.githubusercontent.com/48607498/99212673-b2500400-2799-11eb-9859-5e61a317be21.JPG)

**Comment by krayon007** [comment]
If you look at the file properties for those zip files, they aren't hidden files or anything are they? I noticed that the file-search doesn't pick up hidden files....

But can you run the following powershell command? Just open a command prompt on the local computer, and go to Powershell, and run the command:

`Get-ChildItem -Path C:\****\ -Include *.zip -File -Recurse -ErrorAction SilentlyContinue`

substitute the **** for where you want the search to start, making sure it ends with a trailing backslash.
This is the exact command I run... Does this pickup those files that are missing from your search results?

**Comment by PathfinderNetworks** [comment]
The PowerShell command does find them- as long as I enclose the file path in quotes due to the spaces in the names of the folder structure.  I wonder if the command you are running is not enclosing the path in quotes?  The very odd thing is that I can search in some folders and it works.  Other folders it doesn't.  This particular folder, where the PowerShell script finds them but the MeshAgent find feature doesn't, the folder has no special attributes nor hidden files.  Here's a screen grab of the PS results both with the path in quotes and without. By the way, this is the exact folder I tried to use the Find feature in my screen grab in my previous post.  
![PS_search](https://user-images.githubusercontent.com/48607498/99216602-0a8c0380-27a4-11eb-9d45-3c7d94ba1a35.JPG)

**Comment by krayon007** [comment]
It must be the spaces, becuase I'm not enclosing them in quotes... I'll do some testing with folders with spaces to verify, and make the change... Thanks for the help!

**Comment by Ylianst** [comment]
FYI. Next version will show "No files found" in the center of the search box when no files are found.

![image](https://user-images.githubusercontent.com/1319013/99316446-40b79a80-2819-11eb-85b8-2002d176fbf5.png)

**Comment by Ylianst** [comment]
MeshCentral v0.6.91 published with the UI improvements. Does not affect this issue, just UI.

**Comment by krayon007** [comment]
I updated meshcore.js on the server repo, so the next server update should have a fix for this search issue.

**Comment by Ylianst** [comment]
Nice! Just pulled it. Will be in MeshCentral v0.6.92 when it's next published.

**Comment by Ylianst** [comment]
Note that MeshCentral v0.6.92 is now published. Let us know if the problem is fixed.

**Comment by PathfinderNetworks** [comment]
It does seem to be working properly in 0.6.92. Thanks!
