### ISSUE TITLE
File upload under Group Action causes MeshCentral 0.6.88 server to crash

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#1988]
I'm running 0.6.88 under Server 2019. 
When using the File Upload feature under Group actions it causes the MeshCentral server to crash.  
To replicate here is what I am doing:
I'm choosing a single device in a group (but it also crashes even if you choose more than one device). Selecting File Upload and then select a group of 77 files contained in a folder.  The total size of the files is about 37mb.  It doesn't matter if I select an existing folder on the remote device or have it create a new folder- almost as soon as you click 'Ok' the MeshCentral server will crash.

These are the logs it is generating:

-------- 11/14/2020, 11:28:59 PM ---- 0.6.88 --------

internal/validators.js:121
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:375:7)
    at c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:3241:300
    at c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:5847:47
    at c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:1152:25
    at newArguments.<computed> (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:484:12)
    at callback (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:126:19)
    at c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\cursor.js:193:12
    at c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:130:20)
    at c:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:323:11
    at fn (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (c:\Program Files\Open Source\MeshCentral\node_modules\nedb\node_modules\async\lib\async.js:498:34)
    at processImmediate (internal/timers.js:458:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Also, if I choose to upload only a single file it doesn't crash the server but the file never makes it to the device.

**Comment by PathfinderNetworks** [comment]
Also, not sure if this bug is related to this #1986?
https://github.com/Ylianst/MeshCentral/issues/1986

**Comment by Ylianst** [comment]
Probably not related to #1986. I am looking into this.

**Comment by Ylianst** [comment]
By the way, thank you so much for the detailed report and exception log. Super helpful.

**Comment by Ylianst** [comment]
In MeshCentral v0.6.91 I added code to make sure the server does not crash. However, I am not sure what the exact problem is. If you can give it a try and let me know if you see a problem.

**Comment by PathfinderNetworks** [comment]
I updated to 0.6.91 and tried again.  It's no longer crashing in my tests. But the files still aren't being sent to the device.  I don't see any errors in the server error log either.

**Comment by Ylianst** [comment]
Ok, with v0.6.92 just published, you can go in the "My Server" / "Trace" tab and enable the "Web Server" tracing. Then do a batch upload and if it does not would you should see the error messages on the trace screen. You can use two tabs in your browser (one to upload, the other to trace).

![image](https://user-images.githubusercontent.com/1319013/99454757-b71cd100-28db-11eb-904d-8931fd569cae.png)

If you see the errors, download the events using the down arrow on the upper right and send it over. If there is private info, use my [contact info](https://www.meshcommander.com/contact-information). Should give me everything I need to fix this. Thanks.

**Comment by PathfinderNetworks** [comment]
I just emailed you a copy of the trace log.  Basically this is the error that is being generated:
7:13:42 PM - WEB: AgentPath: undefined
7:13:42 PM - WEB: Exception: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by PathfinderNetworks** [comment]
Also, I just tried it using Google Chrome (I was using Microsoft Edge) and get the same errors in the trace log.

**Comment by Ylianst** [comment]
I am not sure why, but the path you type into this box is not being sent to the server.

![image](https://user-images.githubusercontent.com/1319013/99484756-f23bf600-2915-11eb-889d-437f34ee73b7.png)

The next version of MeshCentral the trace will show all the fields that are passed in. Are you using a reverse proxy in front of MeshCentral that would be filtering queries? I tried FireFox, Chrome, IE, Edge and still can't cause this to happen.

**Comment by PathfinderNetworks** [comment]
No reverse proxy or anything like that.  It's a Windows 2019 server (VM running under Hyper-V) with nothing else installed.  It's sitting behind its own static IP address (using a firewall with port forwarding obviously).  But nothing special or unique about the setup.

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
