### ISSUE TITLE
new install - cant connect to any machine

### ISSUE THREAD

**Issue by tulik23** [Ylianst/MeshCentral#1989]
Hi
i just installed the meshcommander at my domain 
and when i tried to add a machine i cannot connect to it not by name and no IP
what security i am missing ?
(i have ping and i tried to enter my domain/user also but with no success

**Comment by Ylianst** [comment]
This is the MeshCentral Github issues, not MeshCommander. Also, you need to have Intel AMT activated to use MeshCommander. Try navigating to http://machine:16992 or https://machine:16993 to see if you computer has Intel AMT activated.
