### ISSUE TITLE
Zoom Capability

### ISSUE THREAD

**Issue by dmccracken-livewire** [Ylianst/MeshCentral#199]
Hi Ylian, Have you given any more thought to a zoom feature?  It is very difficult to view a remote screen that has a high resolution, particularly in portrait mode (1080w x 1920h).

**Comment by Ylianst** [comment]
Good idea. I will look into it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.3-b with "Zoom" feature. You can now toggle various view modes in the upper right on the remote desktop screen. Feedback appreciated.

![MC2-Zoom](https://user-images.githubusercontent.com/1319013/56838978-40217280-6835-11e9-8fa8-b4a5ee339e9c.png)

**Comment by dmccracken-livewire** [comment]
Fantastic!  We’ll check it out asap.  Thank you!!

**Comment by Ylianst** [comment]
Thanks. Feedback appreciated. If it works for you, please close this issue. Thanks.

**Comment by dmccracken-livewire** [comment]
This is very helpful !!
Ultimately it would be great to be able to select the % to zoom in or have zoom in and zoom out buttons that do 5% or 10% increments.

**Comment by PathfinderNetworks** [comment]
I just updated my server and tested this.  It is working correctly from what I can tell.   I do agree with what dmccracken mentioned about the zoom feature.  It would be beneficial to be able to select the zoom level.

**Comment by Ylianst** [comment]
Getting swamped with feature requests so, no sure when I will get to implementing zoom levels.

**Comment by map7** [comment]
This problem also happens when connecting to clients which have multiple screens. One of my clients has 3 screens and it would be easier if I could select the Display screen to look at in Desktop when connected. This is how it's done in DWService (which we used to use).

**Comment by dinger1986** [comment]
this is done @si458

**Comment by si458** [comment]
as explained above this has been implmented now using the zoom icon - https://github.com/Ylianst/MeshCentral/issues/199#issuecomment-487216554
