### ISSUE TITLE
Windows agent fails to start / install on server core 2012 R2 / 2019

### ISSUE THREAD

**Issue by nroach44** [Ylianst/MeshCentral#1990]
As of the morning of the 13th (GMT+8) agents running on Windows Server core 2012R2 or 2019 no longer start. 2016 GUI and 2019 GUI are fine.

There's no apparent log file for the service when it is installed, but when attempting to run the installer from task manager, the following error is seen:

---------------------------
meshagent64-z_NewAgents.exe - System Error
---------------------------
The program can't start because SAS.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
![image](https://user-images.githubusercontent.com/518487/99253043-fe0eb600-284a-11eb-93aa-72eef40d92ae.png)

It appears that the server updated to v0.6.86 at that time, but it was definitely not working under v0.6.89.

Downgrading to v0.6.70 solves the issue.

**Comment by krayon007** [comment]
Thanks for the heads up. There was a workaround for a windows 7 issue where I tried to work around an SP1 issue by linking sas.dll instead of dynamically loading it. Looks like windows core doesn't have that dll so I'll have no choice but to dynamically load it. I'll address that right away and have ylian push an update

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.93 with Bryan's new MeshAgents for Windows that should fix this. Let us know if it works.

**Comment by nroach44** [comment]
Yup, I can confirm that the agents have been online for the past 12+ hours with no hiccups.

Thanks Bryan & Ylian!
