### ISSUE TITLE
Cannot connect to any agent in 0.6.90

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#1993]
Updated MC2 0.6.87 to 0.6.90 (running on Debian 8 behind Nginx preverse proxy) and now cannot connect to any agent, desktop, files, terminal, nothing......

Error in console:

ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=5&nodeid=node//35spl6%40bzYvr***, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=2&nodeid=node//35spl6%40bzYvr*************, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=1&nodeid=node//35spl6%40bzYvr%24K*******************************, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=5&nodeid=node//35spl6%40bzYvr**********, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=2&nodeid=node//35spl6%40bzYvr***********, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=1&nodeid=node//35spl6%**********, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=2&nodeid=node//35spl6%40bz**************, {"message":"TLS Handshake Error"}
ERROR: Unable to connect relay tunnel to: wss://remote.domain.com:449/meshrelay.ashx?p=1&nodeid=node//35spl6%40b************, {"message":"TLS Handshake Error"}

Please help

**Comment by vitko-bg** [comment]
Tried to downgrade with:

systemctl stop meshcentral
mv node_modules node_modules_backup
npm install meshcentral
systemctl start meshcentral@0.6.87

And the result is:

npm install meshcental@0.6.87
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/meshcental - Not found
npm ERR! 404
npm ERR! 404  'meshcental@0.6.87' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-16T20_51_49_395Z-debug.log

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
As a temporary solution add the following line in the "settings" section of your config.json:

```
"ignoreAgentHashCheck": true
```

This will cause the agents to not check the certificate of the serve when doing desktop/terminal/files connections.

Also, are you using a reverse proxy?

**Comment by vitko-bg** [comment]
Yes, I am using NGINX reverse proxy. 
All was working fine in 0.6.87

**Comment by Ylianst** [comment]
The problem is that when the agent initiates a connection to the server using url "wss://remote.domain.com:449/meshrelay.ashx", it's getting a TLS certificate from the server that it did not expect. So, it thinks there is an attacker trying to intercept the connection. Do you have any idea what would be causing this?

One possibility is that the agent is connecting to "wss://remote.domain2.com" in the .msh file, but "wss://remote.domain.com" for the remote desktop? Or a different port is being used? Or there is something in NGINX that is causing a different certificate to be served?

I have to keep the TLS check in place as this is pretty important for server security. One way to can test this is to try the same URL's with a browser and see if you get the same certificate. Given this, let me know if you have more data.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.6.91, that will accept the relays connection TLS certificate if it's the same as the one the agent got with the control connection. So, when the agent first connect, the TLS cert presented to the agent then will also work later, this on top of what the server indicates if the correct certificate.

Give it a try and let me know if it works.

**Comment by vitko-bg** [comment]
Once updated to 0.6.91 all is fixed and working. 

However, I read carefully what you said and ...... you may be right

> One possibility is that the agent is connecting to "wss://remote.domain2.com" in the .msh file, but "wss://remote.domain.com" for the remote desktop? Or a different port is being used? Or there is something in NGINX that is causing a different certificate to be served?
Before I was using different domain name, and now moved to a new one. All agents are fixed exclude 1 group - but somehow it is working fine.
This particular one group is connectiong to MC2 via remote.domain2.com (pointing to current public IP) and on different port. But that different port is redirected on the router to 449. So in some of the client are connecting to wss://remote.domain2.com:444 and on 0.6.87 all was working fine.

**Comment by vitko-bg** [comment]
My NGINX conf:

server {
        proxy_send_timeout 999999s;
        proxy_read_timeout 999999s;
        server_name remote.domain.com;
        return 301 https://$server_name$request_uri;
}

#HTTPS
server {
        listen 443 ssl;
        proxy_send_timeout 330s;
        proxy_read_timeout 330s;
        server_name remote.domain.com;
        ssl_certificate /etc/letsencrypt/live/remote.domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/remote.domain.com/privkey.pem; # managed by Certbot
        ssl_session_cache shared:WEBSSL:10m;
        ssl_session_timeout 999999s;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/remote.domain.com-access.log;
        error_log  /var/log/nginx/remote.domain.com-error.log;

        location / {
                proxy_pass http://127.0.0.1:444/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}

**Comment by vitko-bg** [comment]
MC2 config:

  "settings": {
    "Cert": "remote.domain.com",
    "Minify": 1,
    "Port": 444,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "AgentPort": 449,
    "AgentPortTls": true,
    "TlsOffload": "127.0.0.1",
    "MpsPort": 4433,
    "MpsTlsOffload": true,
    "WebRTC": true,
    "ClickOnce": true,
    "AgentPing": 60,
    "AgentPong": 300,
    "MeshErrorLogPath": "/my/path/meshcentral/meshcentral-data/",
    "AllowHighQualityDesktop": true,
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "mypassword",
      "backupPath": "/my/path/meshcentral/meshcentral-backup"
    },
    "ManageCrossDomain": [ "user//admin","user//admin2" ]
  },

**Comment by Ylianst** [comment]
Thanks for the info. Yes, the problem was the "AgentPort". On that port, MeshCentral uses the default self-generated TLS certificate, not the one you used by NGINX on port 443. So, the server told the agent to connect and expect the NGINX cert, but the agent got the MeshCentral self-generate cert on 449.

This is fixed now because the agent is now ok with both the NGINX (443) or Self-Generate (449) certs. Unless you see any other issue, I think this is solved.

**Comment by vitko-bg** [comment]
Closing the issue now, as all working as expected.
THANKS for quick response!!!!
