### ISSUE TITLE
lets encrypt - Error unmarshaling finalize order request

### ISSUE THREAD

**Issue by cluelessbuddy** [Ylianst/MeshCentral#1994]
having issue with let's encrypt with following error

> le
{
    "configOk": true,
    "leDomains": [
        "rm.xyz.com"
    ],
    "challenges": {},
    "production": false,
    "webServer": true,
    "certPath": "/root/meshcentral/meshcentral-data/letsencrypt-certs",
    "cert": "None"
}
> leevents
17/11/2020 9:21:42 am - Getting certs from local store (Staging)
17/11/2020 9:21:42 am - No certificate files found
17/11/2020 9:21:47 am - Got no certificates, asking for one now.
17/11/2020 9:21:47 am - Generating private key...
17/11/2020 9:21:47 am - Setting up ACME client...
17/11/2020 9:21:47 am - Creating certificate request...
17/11/2020 9:21:47 am - Requesting certificate from Let's Encrypt...
17/11/2020 9:21:54 am - Succesful response to challenge.
17/11/2020 9:21:56 am - Succesful response to challenge.
17/11/2020 9:21:56 am - Succesful response to challenge.
17/11/2020 9:21:56 am - Succesful response to challenge.
17/11/2020 9:21:56 am - Succesful response to challenge.
17/11/2020 9:21:58 am - Failed to obtain certificate: Error unmarshaling finalize order request

configure.json file

"letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "abc@def.com",
    "names": "rm.xyz.com",
    "__rsaKeySize": 3072,
    "production": false

**Comment by Ylianst** [comment]
Weird, I have never seen this before. Will take a look next time I can.

**Comment by visualwritings** [comment]
We're experiencing this exact issue, just to confirm @cluelessbuddy isn't the only one having problems. I'll let you know if we have any additional info on this.

**Comment by Ylianst** [comment]
Ok, this is going to go up my priority list. Since I have not changed the Let's Encrypt code is a long time, I expect the problem is that one of the dependencies did a change that broke stuff and if causing this. I will investigate.

**Comment by visualwritings** [comment]
I've been debugging the letsencrypt code and trying some stuff to see what does or does not work:
- remove email from request (found some remarks on community.letsencrypt.org about keeping it out)
- changes rsaKeySize to 2048 instead of 3072
- check responses/challenges from acme-client

One thing to note is that we are running mesh on a subdomain. I found a remark somewhere regarding the mentioned error that noted it had something to do with the cert being issued to a single domain. I happened to have another domain pointing to the same server so I added that to the config.json (letsencrypt.names) and lo and behold, we got ourselves a certificate (both in staging and production).

I've never had any issues requesting single subdomain certificates from Let's Encrypt before (all outside of mesh though).

One thing I did notice is that event though we requested a certificate with rsaKeySize 3072, the resulting certificate is 2048. I'll create a separate issue for this though.

**Comment by Ylianst** [comment]
So "rsaKeySize" is not currently support and it's it done not matter that value you put in that key. It's not used. So your saying that removing the email address worked for you? Interesting.

**Comment by visualwritings** [comment]
No sorry. The first three mentioned changes didn't do a thing. Adding another domain to the config (so basically 2 (sub)domains instead of 1) did.

**Comment by Ylianst** [comment]
Oh! Got it. That is super weird.

**Comment by visualwritings** [comment]
I just remembered I also tried commenting the altNames in the cert request (since we had none) but that made no difference.

**Comment by vitko-bg** [comment]
> I just remembered I also tried commenting the altNames in the cert request (since we had none) but that made no difference.

How did you commented altNames? Cannot find this option and today I had an issue when was trying to configure Let'sEncrypt. Do not have exact error, but it was related to altNames, as I have some subdomains on MC2 configured.

**Comment by visualwritings** [comment]
Commented line 176 in node_modules/meshcentral/letsencrypt.js (and removed the comma in the line above it).

**Comment by Ylianst** [comment]
Oh, but if you do that, you can't ask for a certificate with many domains. This said... if you are asking for a single domain anyway, probably not a bad idea to remove 'altnames'.

```
            // Create Certificate Request (CSR)
            obj.log("Creating certificate request...");
            acme.forge.createCsr({
                commonName: obj.leDomains[0],
                altNames: obj.leDomains                     <---- Remove this
            }).then(function (r) {
```

**Comment by visualwritings** [comment]
@vitko-bg what we did before using the built in LE, is using certbot standalone to generate the certificates and symlink to those from the meshcentral-data directory. Worked pretty good, although we did have to temporarily stop MC2 to renew the certificates. But in general that was a less than 2 second operation, except for when it was actually renewed once every 2 months. For now we are keeping this in place actually as a fallback.

**Comment by visualwritings** [comment]
> Oh, but if you do that, you can't ask for a certificate with many domains. This said... if you are asking for a single domain anyway, probably not a bad idea to remove 'altnames'.
> 
> ```
>             // Create Certificate Request (CSR)
>             obj.log("Creating certificate request...");
>             acme.forge.createCsr({
>                 commonName: obj.leDomains[0],
>                 altNames: obj.leDomains                     <---- Remove this
>             }).then(function (r) {
> ```

Having a check in there to see if the list of domains is actually longer than 1 might be good, although as mentioned it didn't actually resolve the issue we have.

**Comment by Ylianst** [comment]
Yes! Just changing that now.

**Comment by Ylianst** [comment]
I just did a fresh install of my server with "npm install meshcentral" and then ran it with `--debug cert` to see what is going on.

```
[ec2-user@ip-xx-xx-xx-xx ~]$ node node_modules/meshcentral --debug cert
Installing archiver@4.0.2...
Installing node-rdpjs-2...
Installing passport...
Installing passport-twitter...
Installing passport-google-oauth20...
Installing passport-github2...
Installing passport-reddit...
Installing passport-azure-oauth2...
Installing jwt-simple...
Installing acme-client...
Installing aedes...
Installing mongodb...
Installing saslprep...
Installing nodemailer...
Installing archiver-zip-encrypted...
Installing googleapis...
Installing yubikeyotp...
Installing otplib@10.2.3...
Installing twilio...
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.6.92, WAN mode.
MeshCentral Intel(R) AMT server running on alt.meshcentral.com:4433.
MeshCentral HTTPS server running on alt.meshcentral.com:443.
SMTP mail server smtp.gmail.com working as expected.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Got certificate.
CERT: LE: Performing server restart...
Updating server certificates...
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.6.92, WAN mode.
MeshCentral Intel(R) AMT server running on alt.meshcentral.com:4433.
MeshCentral HTTPS server running on alt.meshcentral.com:443.
SMTP mail server smtp.gmail.com working as expected.
CERT: LE: Certificate has 89 day(s) left.
CERT: LE: Certificate is ok.
```

My config.json had:

```
  "letsencrypt": {
    "email": "xxxxxxxxxxx@hotmail.com",
    "names": "alt.meshcentral.com",
    "production": false
  },
```

Sadly, I have not encountered a problem in my case.

**Comment by Ylianst** [comment]
I just did a bunch more testing, 4 more certificates on the Let's Encrypt staging server and it all worked for me. I removed the "altNames" when there is only one domain requested and it made no difference, the resulting certificate still has the common name in "Subject Alt Names". So, I am sort of stuck as to what the problem is.

**Comment by cluelessbuddy** [comment]
Ylianst, happy to give you access to my system, as I'm just in a testing mode in a VM, with no real data. PM me if you want to have a snoop around.

**Comment by Ylianst** [comment]
Before we go that route, what version of node are you running? `node -v` to find out.

**Comment by cluelessbuddy** [comment]
node 15.2.0

**Comment by Ylianst** [comment]
Node 15, that is cutting edge. I am currently running my servers on v10.15.1. I will need to check using the latest NodeJS.

**Comment by cluelessbuddy** [comment]
ok.. have some good news, and have narrow down on what might have cause the issues
I did a fresh install of nodejs ver 10+ and letsencrypt and all is good. able to get a certificate for staging and production.
did another fresh install nodejs ver14+ and letsencrypt staging/production and am getting the certificate. is all working on mesh.

**Comment by cluelessbuddy** [comment]
just for fun, i did another clean install with nodejs v15.2.1 and let's encrypt seem to be working fine both in staging and production.

So there you go, may be some configuration issues/software versioning. or something, but it's working as expected. Thank for looking into it Ylianst.

**Comment by visualwritings** [comment]
For completeness-sake, we're running node 12.19.0 & npm 6.14.8. Since it's a production environment I can't fiddle around too much unfortunately.
