### ISSUE TITLE
Cannot send login token by email

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#1995]
Hello,

v0.6.91

I have two-factor authentication enabled on my account, and my email address is correct.
On connection, if I choose to send the token by email, I will not receive anything.
https://i.imgur.com/SKEEne7.png

Sending mail via the user's page from another account works without problems
https://i.imgur.com/XxXvYaw.png

thank you

**Comment by Ylianst** [comment]
I just tried it and it worked for me.

![image](https://user-images.githubusercontent.com/1319013/99458540-8b044e80-28e1-11eb-95b2-c8cc521ee642.png)

I will test the french page now just in case.

**Comment by Ylianst** [comment]
Just tested it in French and it also worked for me.

![image](https://user-images.githubusercontent.com/1319013/99458955-3f9e7000-28e2-11eb-8ad9-753c5a896814.png)

One thing you can do it turn on the "Email/SMS" tracing in the "My Server" / "Trace" tab and see what it going on when you hit the button to sent a token by email.

![image](https://user-images.githubusercontent.com/1319013/99459207-9310be00-28e2-11eb-846b-ac07f268fbe0.png)

**Comment by laboiteajb** [comment]
Hello
Here is the trace at the time of the connection test : 
`08:16:38 - EMAIL: checkEmail: jbmXXXXXX@XXXXX.fr, false`

no mail is sent from the mesh server when I look at my logs from my mail server

but if I send an email from the user's page
https://i.imgur.com/lcJaino.png

Here is the result
https://i.imgur.com/7icduH7.png

And from my mail server
https://i.imgur.com/7DXoMGe.png

I also tried to create a new account.
when setting up double authentication I do not receive an email and I have no traces

**Comment by Ylianst** [comment]
The `checkEmail: jbmXXXXXX@XXXXX.fr, false` indicates that MeshCentral did a DNS query for the MX record of "XXXXX.fr" and could not find it. So, it thinks this is a bad email address.

I just published MeshCentral v0.6.95, in that version you can do this:

```
  "smtp": {
    "host": "xxxxxxxxxxx.com",
    "port": 444,
    "from": "xxxxx@xxxxx.com",
    "user": "xxxxx@xxxxx.com",
    "pass": "XXXXXXXXXX",
    "tls": true,
    "verifyEmail": false                   <-------------
  },
```

Add the `"verifyEmail":false` and restart your server. That will remove the DNS MX check. Let me know if that works.

**Comment by Ylianst** [comment]
Got no feedback on this. Closing. If anything does not work, please open again.

**Comment by laboiteajb** [comment]
Hello,

sorry for the delay.

it's ok for me thanks
