### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#1996]
Hello,
would it be possible to upload files to a group of computers?
Thank you

**Comment by Ylianst** [comment]
Yes, I announced this last week. Select multiple computer, hit "Group Action" and "Upload Files".

![MC2-BatchUpload](https://user-images.githubusercontent.com/1319013/99444740-7ddf6380-28d1-11eb-8bc2-8d2cc2d554df.png)

Let me know if that works.
