### ISSUE TITLE
Let's Encrypt cert has key size 2048 even though config says 3072

### ISSUE THREAD

**Issue by visualwritings** [Ylianst/MeshCentral#1997]
We got our LE certs working (see remarks in #1994 ), however the certificate has key size 2048 while our config.json says 3072. I'm not all that familiar with node, but the code for letsencrypt looks for obj.parent.config.letsencrypt.rsakeysize, while the example in the manual (and thus our config) has "rsaKeySize": 3072. 

The manual does also state that 3072 is the default, so I would assume that if the code can't access the value from the config due to case-sensitivity it would default to 3072, but the returned cert is 2048.

What am I missing here?

**Comment by Ylianst** [comment]
Ha. I changed the library used to get Let's Encrypt certificate a long time ago and "rsaKeySize" is ignored. You can only get a 2048 cert right now. I should remove the "rsaKeySize" from the documentation until it's supported again in the future. Your not missing anything except old docs.

**Comment by visualwritings** [comment]
Clear, thanks for clarifying!
