### ISSUE TITLE
Translate Meshcentral

### ISSUE THREAD

**Issue by artamerh** [Ylianst/MeshCentral#20]
Hello @Ylianst ,
I was woundering if there is possibility to translate to another language all Meshcentral staff (clients, interface, mails templates, etc) and maintain the translation even after updates/upgrades. I have it running on Debian. I checked a tool in http://www.meshcommander.com/translator but,be honest, didn't understand what it does.
Thank you!

**Comment by Ylianst** [comment]
Hi. Translation into other languages is certainly part of the plan later on, MeshCentralv1 had multiple language support and I expect the same for MeshCentralv2 (this project) in the future. However, it's a year away at least since there are lots of features to stabilize first.
