### ISSUE TITLE
Support for Aarch64 (ARMv8)

### ISSUE THREAD

**Issue by Patriciawa** [Ylianst/MeshCentral#200]
Hi,

Is there any support for armv8 the 64bit version? When I install the agent on my RK3399 board, it says: Unsupported machine type: aarch64. 

thanks! :)

**Comment by Ylianst** [comment]
I don't have ARM v8 64bit yet... however, I would like to add it. I need to get myself a ARM64 device, the latest Raspberry Pi and TinkerBoard should do it. What OS are you using?

**Comment by Patriciawa** [comment]
Hi,
If you purschase the Raspberry Pi 3b+ (note the plus!) it's good, that has a armv8 chipset, I don't know about the tinkerboard though. I am using Ubuntu 18.04 Bionic.

**Comment by Ylianst** [comment]
Can you link to where I can get the Ubuntu 64bit OS for the Pi? I have a spare 3b+ I can use for this.

**Comment by D4V3M0NK** [comment]
http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/

**Comment by Ylianst** [comment]
Perfect. Thanks.

**Comment by Patriciawa** [comment]
Here's the device I use: https://www.friendlyarm.com/index.php?route=product/product&product_id=225
As far as i know, if it works on the pi, it should work on this device right? its both the same chipset

**Comment by Ylianst** [comment]
Yes, I think it should work. Now I got to get my Pi ready.

**Comment by Patriciawa** [comment]
okay, thanks!

**Comment by Patriciawa** [comment]
I've tested on my pi 3b+ and the command "uname -m" gives "armv7l" and not aarch64. The pi is running the latest version of raspbian.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.3-f with ARMv8 64bit support (aarch64). I installed Ubuntu64 on my Raspberry Pi 3B+, compiled the agent and tested on it. This now part of the "test fleet" of devices we have. It's the right most one on this picture. Testing and feedback appreciated.

![IMG_20190428_102812](https://user-images.githubusercontent.com/1319013/56867930-be4e5800-69a0-11e9-875e-8c60699def13.jpg)

**Comment by Patriciawa** [comment]
I'd like to test it out, do I follow the normal installation process?

**Comment by Ylianst** [comment]
Yes, just run the normal Linux install script. It should auto-detect "aarch64" and download and install the right MeshAgent.

**Comment by Patriciawa** [comment]
thanks, will let you know how it goes

**Comment by Patriciawa** [comment]
Haven't found any issues, it works as it should.

**Comment by Ylianst** [comment]
Nice! Thanks.
