### ISSUE TITLE
"Duplicate agent" - is that normal?

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2000]
I am trying lately to further diagnose the issue that I have with Linux agents - #1536 and I activated the Trace on the server for new agents. the log I have is:

17:05:53 - AGENT: Duplicate agent b$tc6$yuUq1n9R4daFFET$TmXXXXwq (X.X.X.169:49488)
17:05:53 - AGENT: Verified agent connection to b$tc6$yuUq1n9R4daFFET$TmXXXXwq (X.X.X.169:49488).
17:05:40 - AGENT: New agent at X.X.X.169:49488
17:05:36 - AGENT: New agent at X.X.X.169:49478
17:03:51 - AGENT: New agent at X.X.X.169:49386

However - agent is connected and accessible, all is working fine, but the question is - Is that something normal or? :)
Thanks.

MC2 - 0.6.92
OS - Debian Jessie
Node - 10.16.2
NPM - 6.13.4
Nginx (reverse proxy) - 1.15.12

**Comment by Ylianst** [comment]
Hi. "Duplicate agent" is probably normal. Each agent has a unique identifier and you can't have two agents with the same identifier connect to the server. If the agent is connected over WIFI for example and the access point drops, the agent will know the connection dropped but the server would not know until the connection timeouts.

When the agent connects again, the server will need to drop the old connection (that will timeout anyway) and accept the new connection. You see a "duplicate agent" at that point, but that is ok. The server is dropping the old connection from that agent and moving to the new one.

If you see this "duplicate agent" a lot, it could be that two agents where cloned and have the same identifier and are fighting to connect to the server. This is unlikely, but let me know.

Hope that helps,
Ylian

**Comment by vitko-bg** [comment]
Thanks for answer, that will explain why :)
Closing this ticket now as looks like all is fine.
Will reopen if necessary.
