### ISSUE TITLE
Typing in V0.6.95 not possible

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2002]
Hi Ylian and Team,

This morning i updated my meshcentral from 0.6.93 to 0.6.95, and after that i needed to support an customer. I noticed that typing was not possible anymore, also the new inplemented : "Enter text and click OK to remotely type it" does not work. i reverted my installation to different versions, and the latest version working is V0.6.93 . in Github desktop i saw an change notice: Fixed remote desktop typing, maybe it got to do with that ? In both MS chromium Edge and Google  Chrome are the same problems

If needed something to test, please let me know 
PS there is no error logging regarding this issue, and no problem to be found in the chrome browser

**Comment by Guerdal** [comment]
Same problem for me, early today I upgrade to 0.6.95 and no remotely typing is possible on desktop sharing.
For the Terminal it's ok.

**Comment by Ylianst** [comment]
I am working on a new setting to disable the international keyboard support. That way, I will give everyone a workaround until we root cause the problem. I will have a new version shortly.

**Comment by krayon007** [comment]
@petervanv, is your agent Windows or Linux?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.96 with a new option to work around this issue. However, I would like root cause the problem.

![image](https://user-images.githubusercontent.com/1319013/99711532-b9f00100-2a56-11eb-94e7-75c86cfa7566.png)

**Comment by petervanv** [comment]
my agent is Windows, server is Ubuntu 18.04 LTS

**Comment by Ylianst** [comment]
Can you go in device console and type `versions` and report back the "compileTime"?

![image](https://user-images.githubusercontent.com/1319013/99711925-3aaefd00-2a57-11eb-8043-a5d1877f236a.png)

Agent should have been compiled on November 17th or later. Let me know what you see.

**Comment by petervanv** [comment]
![info - versions](https://user-images.githubusercontent.com/58996467/99712310-285ab080-2aa3-11eb-86ce-d035ef23d7d7.jpg)

**Comment by petervanv** [comment]
with the temporary fix, im able to type again. :-))

**Comment by Ylianst** [comment]
Ok, so you have the latest agent. That is good. I am testing a bunch of browsers now.

**Comment by guerby** [comment]
Temporary fix allows typing again (but without my #1306  fixes).

**Comment by petervanv** [comment]
> Thanks. you have the latest agent. That is good. The agent updated. I am testing a bunch of browsers now. Let me know what browser you are using?

google chrome and chromium edge

**Comment by Ylianst** [comment]
Can you open the developer tools / console and let me know if you see any errors in the console? If you can type in the remote desktop using without the workaround, the look for any errors, that would be great. Thanks.

![image](https://user-images.githubusercontent.com/1319013/99713674-721ea900-2a59-11eb-9477-c51113e18f6d.png)

**Comment by petervanv** [comment]
i do not get any errors in the console at all

**Comment by Ylianst** [comment]
One more question, that is you local keyboard layout? I am testing on English and French.

![image](https://user-images.githubusercontent.com/1319013/99714909-04737c80-2a5b-11eb-87fc-c7518d4d9de2.png)

**Comment by petervanv** [comment]
Local computer
![image](https://user-images.githubusercontent.com/58996467/99715136-bedca100-2aa6-11eb-9ae4-5d5685275764.png)

remote computer
![image](https://user-images.githubusercontent.com/58996467/99715301-f21f3000-2aa6-11eb-9720-7400ba2216f5.png)

**Comment by guerby** [comment]
@Ylianst in daemon.log on my debian 10 meshcentral server I have multiple lines like the following:

```
Nov 19 19:14:52 meshcentral node[213]: Un-handled viewer command: 85
```

**Comment by Ylianst** [comment]
OOHHH!!!! @guerby Thank you!!! The problem is that the desktop multiplexer does not support the new unicode keys!!! Working on a fix now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.6.97 with a keyboard fix. You would not see any keys when you have this option turned on in config.json:

```
"DesktopMultiplex": true
```

Should work perfectly with v0.6.97. Let me know if it works.

**Comment by petervanv** [comment]
Fixed, thx for the quick respons at the issue

**Comment by guerby** [comment]
Works again thanks!

For some reason the  Un-handled viewer command did not show up in the "server log" web button, only in daemon.log.

I tested all key controlling a Windows machine and they worked fine but with one exception : the ^ circumflex and trema key (right of "p"). On the physical machine if you press circumflex then space it will produce a circumflex character, if you press circumflex then e it will produce ê. It doesn't work through meshcentral.

On Linux on some cases it works great but in some not at all (or very slow random key). In a gnome terminal it works great. But in the password form of the ubuntu lock screen no key appear. Also if you launch firefox 83 and try to type in the URL bar it doesn't work too.

I assume it's more on @krayon007 side.
