### ISSUE TITLE
0.6.95 update - lost agents

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#2004]
I updated to 0.6.95 (from 0.6.92 I believe). While Linux machines (Raspberry Pi Zero) came on quickly, Windows 7 machines "struggled" quite a bit - they would be appear and dissappear ~ 2 seconds later several times until the would be active steadily (took 10 minutes or so).
Windows 10 machine did not come active again at all, though. Which is unfortunate, as this machine is physically remote for me ...

**Comment by petervanv** [comment]
with this command (lnux based) you can return to an previous version: npm install meshcentral@0.6.93
change the last digits to go the version wich worked for you.

**Comment by baikal** [comment]
thank you. Will try the update first - and the downgrade if needed.

**Comment by PathfinderNetworks** [comment]
I suspect it might have something to do with the new MeshAgent version being pushed to the devices as part of the update.  I noticed the devices going on and off as well but attributed it to the MeshAgent getting updated.  My devices all seem to be stable now.

**Comment by baikal** [comment]
Turns out that someone turned off that Windows-10 machine at almost exactly the same time as my server upgrade ... sorry for the fuzz. Once turned on again, everything is normal - and updated to 0.6.97.

Although the observation of the Windows-7 machines taking quite some time to be steadily active was real - and yes @PathfinderNetworks, mine are stable since then as well.
