### ISSUE TITLE
macOS agent

### ISSUE THREAD

**Issue by tlcarpenter** [Ylianst/MeshCentral#2006]
Any fixes/updates for the macOS agent on the near horizon? Specifically I'm wondering if logging in to macOS via the meshagent (vs noVNC) will be possible? I support a number of Apple users that are running Catalina; my test system does as well and 95% of the time when I access it using noVNC the cursor is a dot. A workaround is to log in via noVNC and then use "Desktop | Connect" to connect via the meshagent - clunky, but it works. From what I've read on the noVNC forums, the dot cursor issue due to Apple's non-standard use of RFB. I know Apple changed things (#1459) that prevent one from using a keyboard and mouse when nobody is logged in - no video either, at least for me on my Catalina system.

**Comment by dinger1986** [comment]
@si458 newest agent update once tested and released should fix this

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back
