### ISSUE TITLE
Maintenance mode for the Server?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2009]
Hi MeshCentral Team,

I am wondering if there is a maintenance mode that the server is put into, to prevent users unless its an administrator from accessing the server during update/rollouts of new features?

Thanks,
SomeGuru

**Comment by petervanv** [comment]
i saw something in the committed files, so it could be your lucky day

**Comment by Ylianst** [comment]
Yes, it's been announced on Twitter for MeshCentral v0.6.98. You can enable it in the config.json or use the "maintenance" command in the server console.

![EnTxZRVUcAE5asy](https://user-images.githubusercontent.com/1319013/99915938-d0e35d00-2cbb-11eb-8c19-f2a6695c028d.png)

**Comment by petervanv** [comment]
Oh, i missed that, cant find it either, but im following meschcentral };-(

**Comment by SomeGuru** [comment]
Wow!!! It is there.. testing now... I am impressed... will close after a few small tests...

**Comment by vitko-bg** [comment]
No "maintenance" in help command...

the result is:
> help
Available commands:   acceleratorsstats, agentstats, amtacm, amtmanager, autobackup, backupconfig, badlogins,  certhashes, closeusersessions, cores, dbstats, dispatchtable, dupagents, heapdump,  help, info, le, lecheck, leevents, migrationagents, mpsstats, nodeconfig, relays,  resetserver, serverupdate, setmaxtasks, showpaths, sms, swarmstats, tasklimiter, updatecheck,  usersessions, versions, watchdog, webstats
Type help <command> for details.

Please add it to "help" command

**Comment by vitko-bg** [comment]
Also - Looks like maintenance mode does not work when updating the server or restarting it.

Steps to recreate:
1. Put MC2 in "Maintenance mode"
maintenance enabled
> Maintenance mode: Enabled
2. Restart the MC2 server
resetserver
> Server disconnected, click to reconnect. ----> for 3 seconds
> 502 Bad Gateway ----> after 3 seconds
3. Once MC2 is restarted - "Maintenance" mode is OFF ....

**Comment by SomeGuru** [comment]
I see same response as @vitko-bg with this... Also is there a way to execute the command also from ssh? Like > node ./node_modules/meshcentral --debug --maintenance ? Still gives some time with testing if nor reboots or resets done for the server or the OS level activities.

SomeGuru

**Comment by SomeGuru** [comment]
Seems I am doing something wrong in the Config.json as the server never starts in the maintenance mode... 

config.json snip

    "manageAllDeviceGroups": [ "user//someguru", "user//salesforce" ],
    "manageCrossDomain": [ "user//someguru", "user//salesforce" ],
    "maintenanceMode": true,
    "_localDiscovery": {

Is there something wrong in how its written in there? Because no action from Config changes... 

SomeGuru

**Comment by Ylianst** [comment]
Ok. Starting with v0.6.99, "maintenance" is in the help. Also, you can now do this:

```
node node_modules/meshcentral --maintenancemode
```

To start MeshCentral in maintenance mode. Note that maintenance mode is not "sticky" so if use the "maintenance" command in the console and restart MeshCentral, it will not stay.
