### ISSUE TITLE
Production mode in Ubuntu

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#201]
My install is:
Ubuntu 18.04 on Azure B2s and I use "Increase Security Installation" with meshcentral user.
I set NODE_ENV=production in /etc/environment and restarted server.
After this I checked environment and was OK
$ echo $NODE_ENV
production

but in syslog I get:
MeshCentral v0.3.2-y, Hybrid (LAN + WAN) mode.
without Production mode.
Meshcentral restart does not help.

???

**Comment by Ylianst** [comment]
Can you try to add this line:

`Environment=NODE_ENV=production`

In the /etc/systemd/system/meshcentral.service file? If it works, let me know. I will add it to the install guide.

**Comment by motapek** [comment]
It is working.
Thanks

**Comment by Ylianst** [comment]
FYI. Just did a silent update of the [MeshCentral Installer's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.6.pdf) to add this line to the meshcentral.service file.
