### ISSUE TITLE
change login screen

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2011]
Hey Ylian,

The new login screen you introduced earlier this year is nice, but i want to lower the logo, i can't find how to change it ?
Can you help me with that.

![image](https://user-images.githubusercontent.com/58996467/100022853-2e72c900-2de4-11eb-8680-5f2ae4e3e858.png)

**Comment by vitko-bg** [comment]
I do not have that issue ....
Have you tried to reduce your logo size?

**Comment by petervanv** [comment]
never thought about that option, was thinking it is in the css files.

Thx for the quick reply
