### ISSUE TITLE
Questions about USB ACM Activation through Mesh Central 

### ISSUE THREAD

**Issue by mfroeh103** [Ylianst/MeshCentral#2014]
Thank you for the recent updates for AMT/vPro activation. Those have been really helpful for us. 

Right now we are trying to move devices from CCM to ACM after they have been automatically activated through Mesh Central. We are having issues getting the devices into ACM. Issue 1 is that we cannot change into ACM mode from CCM. Issue 2 is that using Simple Admin Control Mode does not fully configure with the USB. 

Issue 1
Here are the steps we have done - 

1. Created a device group in Mesh Central
2. Set "Intel AMT" to "Fully Automatic"
3. Installed the Mesh Central agent on the system
4. At this point the systems work in CCM mode. The Intel ME shows "Activated CCM" in the device info.
5. I went to device group settings and click "ACM" and create a setup.bin file and add that to a fat formatted flash drive
6. When we reboot with this flash drive attached and press "y", we get the following text. 
"Intel (R) AMT is already provisioned. 
Provisioning related messages may fail. 
Press any key to continue..." 
7. The system does not change to ACM in Mesh Central. 

Issue 2 
I then tried a different method without going from CCM to ACM.

1. Created a device group with "Intel AMT" set to "Simple Admin Control Mode" and moved my device to this group. 
2. Completed a "Full unprovision" of network access in the AMT settings on the device. 
3. Created a new USB file from the new group. 
4. Rebooted with flash drive attached and selected "y" and got the following text. 
"Configuration Settings from the USB file were successfully applied.
Press any key to continue with system boot..." 
5. Inside of Mesh Central, the amt mode never updated. I was able to use the software agent to connect, but no AMT access. 
6. I then went into the AMT settings and had to click "Activate Network Access"  
7. After activating network access, the device has full ACM access through mesh central. 

My question is - Am I doing the steps correctly for enabling ACM? Or is there a different method I should be using.

**Comment by Ylianst** [comment]
Interesting, let me investigate this and get back to you.

**Comment by mfroeh103** [comment]
I did have one system flip to ACM after I hit submit. This is one from issue #1. How long should the change take? We had four systems that we ran the USB process on. It's been 5+ hours since we ran that.

**Comment by Ylianst** [comment]
Ok. Your absolutely right that when activated in CCM, the USB setup.bin file does not work. This is disappointing and I can't see any option to deactivate CCM as part of the USB setup. So, this is a good case where you can't just use CCM as an alternative until you make it to ACM. As a result, I just published MeshCentral v0.7.2 with a few Intel AMT improvements.

![image](https://user-images.githubusercontent.com/1319013/100196597-f1730900-2ead-11eb-9e99-f5f6df4b9ae7.png)

You can now select the "Simple Admin Control Mode" policy and indicate the CCM should be deactivated if Intel AMT is in this state. That way, you have a policy that makes sure you never have CCM enabled. Also, I added code to make sure the "remote configuration" option is disabled. This is unlikely to ever be a problem, but I added it to make sure ACM activation would work.

I also improved the "amtinfo" action in MeshCMD to show CIRA connection status which should be useful for debugging.

For your second point, I am not sure why the server did not bring the machine to ACM, but the new ACM simple policy without CCM could help. More importantly, you can go in the device's "Console" tab as administrator and type "amtevents" to see what the activation server did on this machine.

![image](https://user-images.githubusercontent.com/1319013/100196885-65adac80-2eae-11eb-9129-f3f50a724421.png)

You can also type "amtconfig" in the console window to force the server to take a look at that machine again. If it does not work, let me know what you see with these commands. Thanks.
