### ISSUE TITLE
IDE-R whether or not to be successful used in the MeshCentral UI for OS installation

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#2015]
Dear ALL:

Up to now, can you use IDE-R in the MeshCentral UI to mount ISO files? To complete the remote PC operating system installation in the LAN.

I've been testing, but I haven't succeeded.

Thank you very much for your advice!

Billy

**Comment by Ylianst** [comment]
Hi. IDER should work, however if your running into issues you going to have to describe the situation and results in sufficient detail that we can make the same problem happen on our development servers.

So to answer the question, yes, you can do that.

**Comment by billydu1980** [comment]
We have been promoting Intel AMT and vPro solutions in smart factories. Our greatest interest in out of band management is to remotely reload the OS. The following configuration process and error reporting screenshot


![01](https://user-images.githubusercontent.com/42434331/100206400-3c8a2c00-2f41-11eb-92b6-f2967a9999f4.PNG)
![02](https://user-images.githubusercontent.com/42434331/100206405-3e53ef80-2f41-11eb-83ca-178259cf12c1.PNG)
![03](https://user-images.githubusercontent.com/42434331/100206406-3f851c80-2f41-11eb-9789-2b4379cec431.PNG)
![04](https://user-images.githubusercontent.com/42434331/100206408-401db300-2f41-11eb-9a53-42f1dad000c7.PNG)
![05](https://user-images.githubusercontent.com/42434331/100206409-40b64980-2f41-11eb-8cda-6561ec3d9b2a.PNG)

Thank you for your analysis and suggestions.
Billy

**Comment by Ylianst** [comment]
Hi. Thanks for the details. Can you give the URL to the CentOS ISO you are using? I will use the same one for my testing. Thanks.

**Comment by billydu1980** [comment]
Dear  Ylianst:
Thanks so much for your reply.
CentOS-7.6-x86_64-DVD-1810.iso，we try other ISO also did not succeed, it is not clear whether the setting problem. Our application is in the LAN environment. When I add an AMT PC, I can only select no TLS security.

Best regards,
Billy

**Comment by Ylianst** [comment]
Can you give the URL to the ISO file? Thanks.

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
