### ISSUE TITLE
RDP stops working

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#2016]
Im using version 7.2 Also previous versions have same issue. When i click RDP link only # is added to URL, but nothing happens. I have installed ClickOnce in Chrome, but it just suddely stops to work.

I also read that Mesh does not need ClickOnce anymore. How to set it up to work without ClickOnce plugin?

regards

**Comment by Ylianst** [comment]
Right, MeshCentral no longer uses clickonce. Download the MeshCentral Router, run it and hit the "install" button. It will register itself as the mcrouter:// protocol. Then close it and click the links again. Let me know if that works.

**Comment by alesribic73** [comment]
Yes, i can confirm it is working. 

Thanks

**Comment by Ylianst** [comment]
Good. Should work on all browsers and no ClickOnce add-in's required.
