### ISSUE TITLE
Share button for linux/windows terminal sessions

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2018]
This is not a bug but a feature request. Is it possible to share a terminal session (linux/windows) with some people for education purposes (so they can see the same session) ?

Thanks
Vince

**Comment by Ylianst** [comment]
Feature requests are great. I realize it's the GitHub "issues" section, but even opening an issue any feedback is ok.

By default each time you connect to the terminal, it creates a new terminal session. So, I could have the same sharing feature as remote desktop but for the terminal but it would create a new terminal on the remote machine each time.

What your asking for is to be able to see the same terminal session you have? I have to think about how to do this.

**Comment by vtacquet** [comment]
Hey Ylian, well both options are valid. Sometimes you might need the assistance of someone to have a look at the same screen you are seeing for troubleshooting or educational purposes. But also inviting a specialist to a new “private” terminal session to solve something you really don’t want to see yourself could be a nice addition...

**Comment by Ylianst** [comment]
Sharing a new "private" session is certainly something I can add. For sharing the same terminal, that is going to be more difficult. For example, I would have to keep the VT100 stream of the terminal on the server and "replay" the stream to anyone joining in, or more complex yet, I try to decode the terminal stream on the server and sent the current screen to anyone connecting. Also, terminal sessions are short lived, you would need to resent the sharing links to everyone each time you open a new terminal.

**Comment by vtacquet** [comment]
Resending the sharing links are not a real issue as long as the sessions stays active while you are using the terminal.

**Comment by Ylianst** [comment]
Just added terminal sharing in MeshCentral v0.7.3. Let me know if that works.

![MC2-TerminalSharing](https://user-images.githubusercontent.com/1319013/100486678-cc52e600-30b9-11eb-95b0-afa9a9486445.png)

**Comment by Prikith** [comment]
this does not appear to work on linux devices that do not have a desktop environment 
![image](https://user-images.githubusercontent.com/38623521/100498130-679e9680-3160-11eb-8f14-d9e8a021319d.png)

**Comment by vtacquet** [comment]
I can confirm, no share button on any linux server without X

**Comment by Ylianst** [comment]
Oh right. The share button only shows up if the device supports remote desktop. I will fix this now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.7.5 with a fix for this. Let me know if it works.

**Comment by Prikith** [comment]
It works now thanks.
![image](https://user-images.githubusercontent.com/38623521/100527036-f8ac5680-31ce-11eb-8217-a2e18b5f2c15.png)

**Comment by petervanv** [comment]
It creates an link, but when testing it does not show what is done at the "head" terminal. It is only an empty terminal

**Comment by Ylianst** [comment]
Right, a new terminal session is created each time. You don't see the terminal session for someone else. As I indicated before, that would be difficult to do.

**Comment by vtacquet** [comment]
I can confirm it is working now. The 'share' stays in the Active Device Sharing section even when the session has expired, is that normal ?
![image](https://user-images.githubusercontent.com/5128967/100534890-413a3300-3214-11eb-931f-bbde6d61dbc2.png)

**Comment by Ylianst** [comment]
This is not normal, it should disconnect when expired. I will try it out again.

**Comment by Ylianst** [comment]
If you create a 1 minute terminal and connect to it, does it disconnect after 1 minute? Is the problem only time-range? Any details appreciated.

**Comment by Ylianst** [comment]
I tested the time range and it disconnected correctly. So, I will need more details.

**Comment by vtacquet** [comment]
Yes there is no problem with the disconnect, it just stays listed in the "active device sharing" overview even when the time range has expired (and the session stopped).

**Comment by Ylianst** [comment]
Ha yes, that can take a little bit longer to be removed but it will eventually be auto-removed. It's not instant, however the link will not be valid.
