### ISSUE TITLE
(Guide) Implementation of server at cloudfoundry

### ISSUE THREAD

**Issue by bengchet** [Ylianst/MeshCentral#202]
Hi, recently I attempted to implement custom meshcentral2 server on cloud foundry. From my understanding, Cloud foundry hosts the application in the container which exposes internal port 8080 to external port 443. I run meshcentral.js with notls and port 8080, and still able to access to meshcentral2 main page with given url like https://<cloudfoundrydomain>.

Now the problem comes. Installation guide and meshagent.msh will be showing server urls with notls and port 8080. Does that mean we have to modify all of server urls to these files manually? Will it affect the operation of websockets and such as well? If so, what is the best way to host meshcentral2 server on cloud foundry?

Looking for any suggestions.

Thanks.

**Comment by Ylianst** [comment]
Hi. Yes, a few things on this. First, you should use "tlsoffload" instead of "notls" to inform the server that TLS is present but provided by an entity in front of the server. Then you can set the port to 8080, but set the "AliasPort" setting to 443. That will tell the server that port 443 is really being used. Lastly, you can set "TlsOffload" to "true", but instead you can set it to the private IP address of the reverse proxy. If you do that, and source IP address and hostname are in the HTTP header, MeshCentral will trust these fields.

Hope it helps,
Ylian

```
{
  "settings": {
    "Port": 8080,
    "AliasPort": 443,
    "TlsOffload": "1.2.3.4"
  }
}
```

**Comment by Ylianst** [comment]
Did this answer your question? If so, please close the issue report. Thanks.

**Comment by bengchet** [comment]
Hi,

Yes this have answered my question. I have also check the user manual guide to confirm my doubts. Setting aliasport and tlsoffload did work well for me. I will also need to point domains Certurl to cloudfoundry https url to make it working.

However I can see when the meshcentral first startup, settings from sample-config.json doesn't apply, I have to modify getConfig(false) from mainStart function in meshcentral.js to getConfig(true) to make settings applied when meshcentral first starts. May I know what is the purpose of making getConfig false instead of true?

**Comment by Ylianst** [comment]
Hi. The file "sample-config.json" should never be used or modified. If you chance that file, the next time you update the server, your changes will be lost. You need to find the file "config.json" in the folder "meshcentral-data" and change this file. I suggest you undo the getConfig() change you made and instead use the correct settings file. All of the data in "meshcentral-data" folder will remain after a server update. Hope it helps.

**Comment by bengchet** [comment]
Hi,

Thanks for clarifying. I will do that.

Many thanks for help.
