### ISSUE TITLE
Make desktop toolbar universal for all clients

### ISSUE THREAD

**Issue by valnar1** [Ylianst/MeshCentral#2020]
I noticed that interactive agents are not "kept" listed in the device group when they go offline and stop running the agent.  This is not like the regular agents.

It doesn't bother me that they are not listed, except that the user consent parameters do not stick.  Specifically, I want all agents to have connection toolbar present.  Actually, that's more of my problem.  How can I make that a universal setting for all agents?  Then I would not need them to be listed at all times.  thank you.

**Comment by valnar1** [comment]
I looked in the advanced config.json example and do not see the setting.

**Comment by Ylianst** [comment]
Ha correct, right now interactive agent don't stay. This is because this sort of expected that the interactive agents would create a new device identifier each time and so, if we kept the device it's possible you would see a "new" device each time they connect. If you like, I could create a server setting to never remove a device when it's interactive?

**Comment by valnar1** [comment]
That would be useful, but my primary purpose is just to make the desktop toolbar universal for all clients.  I cannot find that config setting, so that would be better.  thanks.

**Comment by PetieM** [comment]
I don't have a spare computer to test this with at the moment but what I believe should work would be setting the user consent options for the group that you're inviting these interactive agents too (either via the Add Agent or Invite links on the group itself). I know for background agents at least, I have a group that requires user consent and the privacy bar visible set on the group, not on the individual clients, and it functions as expected so I'd guess it would work the same if the temporary agent gets added to a group with those settings.

**Comment by valnar1** [comment]
I don't see the setting to set it for the group.  I've checked all the config options.

**Comment by Ylianst** [comment]
To make the desktop toolbar universal for all clients, add the following to the domain section of the config.json:

```
      "userconsentflags": 64
```

Starting with MeshCentral v0.7.3, you can also do this:

```
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": true,
        "terminalprompt": true,
        "fileprompt": true,
        "desktopprivacybar": true
      },
```

This allows you to specify the required user consent flags for the entire domain. Let me know if that works.

**Comment by valnar1** [comment]
Thank you!  That was fast.  I'm currently having this issue since I started with 0.71.  If I can get that working, I'll upgrade to 0.73
https://www.reddit.com/r/MeshCentral/comments/k1j5tb/meshcentral_071_upgrade_issue

**Comment by Ylianst** [comment]
To be clear, you don't need to update, just put this line in the domain section of your current version:

```
"userconsentflags": 64
```

**Comment by PetieM** [comment]
Ylian's method is definitely best for forcing it on the entire server but for reference, I was referring to settings on the web interface, not the config file. From the My Account tab, you can click on a group and then click the edit button next to User Consent so set required options for just that individual group if you don't want to apply it to the entire server/domain.

**Comment by Ylianst** [comment]
You are correct. You can set this option for a device group like this:

![image](https://user-images.githubusercontent.com/1319013/100488061-de845280-30c0-11eb-8a13-ff215dddd989.png)

**Comment by valnar1** [comment]
Thanks everyone
