### ISSUE TITLE
Cannot upgrade or install as service

### ISSUE THREAD

**Issue by valnar1** [Ylianst/MeshCentral#2021]
This affects versions 0.7.1 and above, possibly even earlier ones.  Two issues possibly related?

**1)** On a brand new Windows 8.1 or 10 install, you cannot install it as a service.  This is from NPM.  Example is shown with 0.7.1, but affects anything recent.  This is duplicatable.

C:\meshcentral\node_modules\meshcentral>node meshcentral --install
Installing MeshCentral as Windows Service...
Error: Cannot find module 'C:\meshcentral\node_modules\meshcentral\node_modules\minimist'
Require stack:
- C:\meshcentral\node_modules\WinService\winservice.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at start (C:\meshcentral\node_modules\WinService\winservice.js:39:22)
    at Object.<anonymous> (C:\meshcentral\node_modules\WinService\winservice.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\meshcentral\\node_modules\\WinService\\winservice.js' ]
}

**2)** When I try to upgrade via the GUI from 0.71 to higher, it seems to work, but then doesn't.  It stays at the earlier version.  Here is the output as I do it.

C:\meshcentral\node_modules\meshcentral>node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.1, WAN mode.
MeshCentral Intel(R) AMT server running on ns.obscured.net:4433.
MeshCentral HTTPS server running on ns.obscured.net:443.
MeshCentral HTTPS agent-only server running on ns.obscured.net:4030.
Starting self upgrade to: 0.7.2
Update completed...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.1, WAN mode.
MeshCentral Intel(R) AMT server running on ns.obscured.net:4433.
MeshCentral HTTPS server running on ns.obscured.net:443.
MeshCentral HTTPS agent-only server running on ns.obscured.net:4030.

**Comment by techno-express** [comment]
It seems the way you installing.
> C:\meshcentral\node_modules\meshcentral>

Why from inside **node_modules**? 
That folder is created on all **npm install**'s from the directory you ran `npm` in.
The error traces to one level up from the directory you're in. it expects `minimist` and others to be installed already be the way you running, otherwise it would have **pulled** it in to current directory..

**Comment by valnar1** [comment]
I'm just following the official instructions.  I tried it at a couple different levels.  So where do I run it then?

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by valnar1** [comment]
The PDF for installation suggests using the --install, and it doesn't work as shown. The GUI upgrade method (while running from a CLI, since I can't install the service) shows the output above too.  If tried both things several times on different computers, so I'm not sure why.

I installed NodeJS 14.15.1

**Comment by Ylianst** [comment]
I will an an update shortly and working on fixing the documentation.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.5 with fixes. Can you test and let me know if it works for you? Thanks.

**Comment by Ylianst** [comment]
Just updated the [MeshCentral Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.1.0.pdf). A problem on Windows with NPM when installing new modules or performing an update is that if you have an open command prompt located in the "node_modules\meshcentral" folder, it will lock that folder that stop any modules from being installed or self-update.

So, on Windows, do NOT to this:

```
cd c:\myserver\node_modules\meshcentral
node meshcentral
```

Instead, do this:

```
cd c:\myserver
node node_modules\meshcentral
```

The new version of MeshCentral will suggest doing this if it runs into issues.

**Comment by valnar1** [comment]
All of it works now!  I updated and installed it as a service.
Thank you.
