### ISSUE TITLE
Manage phone number not with country number ?

### ISSUE THREAD

**Issue by pdreissen** [Ylianst/MeshCentral#2024]
I can only use a phone number without country code.

<img width="1460" alt="Screenshot 2020-11-29 at 20 32 18" src="https://user-images.githubusercontent.com/9047700/100551654-5d74b900-3282-11eb-9dfc-1db3bca55f6a.png">

<img width="1104" alt="Screenshot 2020-11-29 at 20 37 31" src="https://user-images.githubusercontent.com/9047700/100551722-dffd7880-3282-11eb-98a1-899041515fd2.png">

This is likely a problem since plivo adds the country code of US before the mobile number which fails

<img width="1365" alt="Screenshot 2020-11-29 at 20 39 14" src="https://user-images.githubusercontent.com/9047700/100551800-5a2dfd00-3283-11eb-9587-c959e7fa2b8c.png">

**Comment by Ylianst** [comment]
Ok, I changed the phone number validation to allow "+" numbers. It will be in MeshCentral v0.7.8 when it's next published. If you can test it and let me know if it work, that would be great.

**Comment by pdreissen** [comment]
> Ok, I changed the phone number validation to allow "+" numbers. It will be in MeshCentral v0.7.8 when it's next published. If you can test it and let me know if it work, that would be great.

Great, will do however it is also limited to min 10 and max 11 numbers don't now if this has been changed also ? In my country 10 is normal however not sure about other countries.

**Comment by pdreissen** [comment]
I just tested 0.7.8, + numbers are allowed but i can't complete my number since there is a max number of 11 characters, i need 12 to complete my number which isn't allowed as it seems.

11 characters allowed:
<img width="1074" alt="Screenshot 2020-11-30 at 23 00 23" src="https://user-images.githubusercontent.com/9047700/100671084-296fc580-3360-11eb-9d82-d09f87b039d0.png">

12 characters no go, however i need 12 included with my country number:

<img width="1074" alt="Screenshot 2020-11-30 at 23 00 23" src="https://user-images.githubusercontent.com/9047700/100671140-41474980-3360-11eb-9cf9-ed8debbb6a32.png">

**Comment by Ylianst** [comment]
Ok, checking now.

**Comment by pdreissen** [comment]
Hi just updated to 0.7.9 and now it is working as expected. Thanks!
