### ISSUE TITLE
Quick Visual Suggestion

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2026]
This is super-low priority but when clicking on basically everything that isn't a button or link (e.g. the left and top navigation), the browser adds an outline to the selected object. Adding 'outline: none" to these classes (or the really quick and dirty way, to the * selector) removes this and makes the page look better. Unless you left those outlines in for a reason?

**Comment by Ylianst** [comment]
Ha! You right. Use FireFox a lot and did notice that on Chrome. Just added the style, it will be in MeshCentral v0.7.7.

**Comment by PetieM** [comment]
Looks much better, thanks!
