### ISSUE TITLE
MeshAgent.dmp file downloaded after shutdown

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2027]
I seem to notice that on 1 laptop the meshagent.dmp file is downloaded, but not by me. (I do have coredump on)
The laptop has been shutdown / rebooted so I won't expect a crashdump, is this intentional after each reboot or did Windows not do a proper shutdown?

Also can you please mark this file download as "Automatic Meshcentral coredump download"
I was confused for a bit who downloaded the file as there is no user assigned to it.

![image](https://user-images.githubusercontent.com/55733884/100590741-1a076280-32f5-11eb-8d20-fae222ff72e3.png)

**Comment by Ylianst** [comment]
Thanks for the report. Starting with MeshCentral v0.7.8, the core dump download message will be different:

![image](https://user-images.githubusercontent.com/1319013/100666009-2f888680-330d-11eb-94aa-8942945d3392.png)

When you have `"agentCoreDump": true` in the settings section of the config.json, the server will automatically download up to 20 agent crash dumps into the "meshcentral-coredumps" folder. This is crash dump presence it checked each time the agent connects. If the agent crashes, on re-connection the dump to be sent to the server. Again, the server will stop at 20 and you need to remove them dumps to get more.

Let me know if that helps,
Ylian

**Comment by Allowee** [comment]
Thank you!

Just checked with a VM.
After a normal reboot it will send the dumpfile, I don't think this should be the case

**Comment by Allowee** [comment]
Investigated this further

When I do  a "Start -> Power -> Reboot" the following error appears in the meshagent.log

[2020-12-02 10:26:15 AM] FATAL EXCEPTION [MeshAgent_622A8627B9E2B449.exe] @ [FuncAddr: 0x00007ff6c5f5bd20 / BaseAddr: 0x00007ff6c5f7e67c / Delta: 141660]

**Comment by Ylianst** [comment]
Since you have the agent crash dump for this exception, can you mail it to me privately? [My contact info is here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by Allowee** [comment]
Done :)

**Comment by Ylianst** [comment]
Bryan looked at your dumps and MeshCentral v0.7.11 was published last night with all new MeshAgents that should include a fix for this. Update your server, all agents should auto-update. Let us know if that works.

**Comment by Allowee** [comment]
Yes that seems to work, thanks
