### ISSUE TITLE
After upgrade to v0.7.7, nothing to see anymore

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2028]
I upgraded from 0.7.2 to 0.7.7. Then I see nothing anymore, No devices, no groups, No events, etc. How to solve this?

![image](https://user-images.githubusercontent.com/5203309/100631423-fca1bb00-332b-11eb-8cfe-e9f42abca98c.png)
![image](https://user-images.githubusercontent.com/5203309/100631536-1d6a1080-332c-11eb-982c-12e4e9a20057.png)

**Comment by hunter-nl** [comment]
I've downgraded to 0.7.6 And this is working. So something is broken in version 0.7.7

**Comment by petervanv** [comment]
What view are you using ?

![image](https://user-images.githubusercontent.com/58996467/100632835-9a49ba00-332d-11eb-9412-e0825adc67d7.png)

**Comment by hunter-nl** [comment]
View icons not showing and grey bar is empty.

**Comment by Ylianst** [comment]
@hunter-nl Are you using a reverse proxy? Also, can you open the browser's console and send over any errors you see?

You can open it in FireFix using CTRL-K:
![image](https://user-images.githubusercontent.com/1319013/100655983-e5010d00-3300-11eb-9863-2e79d98bc685.png)

In Chrome it's CTRL-SHIFT-I:
![image](https://user-images.githubusercontent.com/1319013/100656101-0eba3400-3301-11eb-80ae-79cb50134f28.png)

Thanks,
Ylian

**Comment by Ylianst** [comment]
I just published MeshCentral v0.7.8 with a fix to what I am guessing is the problem. This is a complete guess since I have no data except what was changed in recent versions. Let me know if it works, if not, please send over the browser console messages. Thanks.

**Comment by hunter-nl** [comment]
Yes, with v0.7.8 it has been fixed. Thank you!

**Comment by Ylianst** [comment]
Nice! I am pretty sure you have a reverse proxy :) Thanks for reporting back.
