### ISSUE TITLE
No keyboard input on Server 2016 and 2019 - starting with 0.7.7

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2029]
For some crazy reason keyboard input is no longer working on Server 2016 and Server 2019- even though it still works on my Windows 10 devices.  Even stranger is that I can send special keys- such as the Ctrl-Alt-Del command without issue.  It also recognizes when I switch caps lock on or off.  But I cannot enter any actual text.  
I first noticed this on the password entry screen at the logon prompt.  I used the on-screen keyboard to log in.  But even after logging in I cannot enter text using the keyboard.  
I was on 0.7.7 when I noticed it. Then I upgraded to 0.7.9 hoping maybe it was fixed in that version. Same issue.  
It does work on Server 2012 (and Windows 10 as mentioned).

I'm wondering if maybe Microsoft pushed out some very recent security update for Server 2016 and 2019 preventing remote keyboard input?  Kind of like what they had done with the previous version of Microsoft Edge?

**Comment by PathfinderNetworks** [comment]
As a test, I  just tried accessing those same servers using Premium Remote Control (the remote control tool used in Avast CloudCare).  Keyboard input is working properly with Premium Remote Control.

**Comment by vic-wstrnmw** [comment]
i've found this as well, however if I Disconnect and re-Connect it works fine.

**Comment by Ylianst** [comment]
FYI. If you click remote desktop "Settings" and select "Use Remote Keyboard Mapping", you will return to the old keyboard system. This likely is a workaround for now.

**Comment by PathfinderNetworks** [comment]
> FYI. If you click remote desktop "Settings" and select "Use Remote Keyboard Mapping", you will return to the old keyboard system. This likely is a workaround for now.

Thank you.  Using this setting does allow keyboard input on Server 2016 and 2019.  What's different about Server 2016 and 2019 that cause this?

**Comment by PathfinderNetworks** [comment]
> i've found this as well, however if I Disconnect and re-Connect it works fine.

I tried this as well as the setting Ylian mentioned. Disconnecting and reconnecting also works, like you mentioned.  Very strange.

**Comment by Ylianst** [comment]
Bryan has a few virtual machines with Windows Server 2016 and 2019 so, we will take a look. The new keyboard system should work with international keyboards, but may not work on older OS's. I may need to auto-detect and switch modes automatically.

**Comment by PathfinderNetworks** [comment]
I was mistaken when I said this trouble wasn't present on Server 2012 devices.  It affects that version of Server as well. When I first tried it I must have disconnected and reconnected to the device.  I did more testing tonight and had the same issue as I mentioned with Server 2016 and 2019.

**Comment by krayon007** [comment]
I just tested with Windows Server 2012, 2016, and 2019. The keyboard works correctly for me, in both english and french...
You guys aren't running your Windows Server instance in a Virtual Box VM are you? I remember someone posted saying that keyboard input was messed up on Virtual Box if the Host and Guest OS were not configured the same.

**Comment by krayon007** [comment]
Also, what browser are you using, and what OS are you running on the browser side?

**Comment by krayon007** [comment]
Nevermind, I was able to reproduce it... It seems to happen when you send "ctrl-alt-del"... After you send that, the unicode keys stop working unless you disconnect and reconnect.  We'll look into it...

**Comment by PathfinderNetworks** [comment]
Thanks Bryan.  Yes, all of the servers I connect to do require logging in with Ctrl-Alt-Del.  So that makes sense.  Also makes sense why I initially thought Server 2012 was unaffected as the device I had first connected to was already logged in to and all I was doing was typing characters in to Notepad. Once it was logged out and I had to use Ctrl-Alt-Del then I noticed the same issue.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.10 with a fix for this. Turned on it was an UI issue. When you hit the "Send" button, it would keep focus in the browser and receive all the key press events. Same problem for the "Input" checkbox and "Tools" button, I fixed all of that. Let me know if this works. The mobile site does not seem to be affected.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian, 
I just updated to 0.7.10 and can confirm it is working correctly now.  Thank you!
