### ISSUE TITLE
How to perform clustering in meshcentral

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2034]
How to perform clustering in meshcentral

Is there any documentation ?

**Comment by Ylianst** [comment]
Take a look at section 7.3 of the [MeshCentral User's Guide](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf). You must first use MongoDB with "Change Stream" enabled, then you can run two or more servers and the configuration is pretty simple. Let me know if that works.
