### ISSUE TITLE
Fun fact : type fonction does'nt like repetition

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#2035]
On a french to french pc fr keyboard : 

- Copy a windows password from bitwarden / or type : ex Gaaw115778
- paste this password (or by manual entry)  in "type" windows + click ok

password is transmitted as Gaw1578 on client pc....

Not exactky the same...

**Comment by circlecomputers** [comment]
This also happens on the UK to UK so I think it must be a bug that has crept in generally

**Comment by Ylianst** [comment]
Oh weird!!! Thanks for reporting. We will look into this.

**Comment by Ylianst** [comment]
I just tested this feature and can't find any issues. What OS is running on the remote computer?

![image](https://user-images.githubusercontent.com/1319013/100924477-8ae58080-3495-11eb-828d-442bebb32f50.png)

**Comment by tranbert** [comment]
win 10 on win 10. but i « paste » the password for windows logon

**Comment by Ylianst** [comment]
Does it work for you everywhere else? Like in Notepad?

**Comment by tranbert** [comment]
yes it works in notepad...

**Comment by circlecomputers** [comment]
I use the type feature to pass info into credentials prompts when setting up Microsoft 365/Outlook etc. and its these prompts I found it has started dropping duplicate letters/numbers. This only started happening recently, probably since I moved to the 0.7 builds.

**Comment by OutbackMatt** [comment]
I noticed that this also happens for urls in web browsers which is a pain when http become htp

It does NOT  happen in notepad
It does happen in chrome

I'm currently on 0.6.99
It does happen in Firefox
it does happen in command prompt
