### ISSUE TITLE
Network adapter with "." will result in error

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2036]
After checking, renaming as "Wi.Fi" and renaming back as "Wi-Fi"  
I am sure the problem is a . in the name of the network adapter.
This will result in the error below and not display the network interfaces on the details tab.

![image](https://user-images.githubusercontent.com/55733884/100848604-a3e43680-3481-11eb-9227-0a9d3dcc5ac3.png)

The adapter with a . in it is the internal Windows ipv6 tunnel, isatap 

```
 isatap.{F0F4DD31-E072-419B-9BE8-EE4973F032EE}: {
    0: {
      address: "fe80::5efe:192.168.1.58%33"
      fqdn: ""
      family: "IPv6"
      mac: "00:00:00:00:00:00:00:E0"
      index: 33
      status: "down"
      type: "tunnel"
    }
  }
```

**Comment by Ylianst** [comment]
Interesting! Thanks for reporting this. I will take a look at it.

**Comment by krayon007** [comment]
Which windows OS are you running? I tested on Windows 10, and renamed my network adapter to have a dot in it, and it still works...

**Comment by Ylianst** [comment]
Same here, I just renamed my network interface "Wi.Fi" and looks ok:

![image](https://user-images.githubusercontent.com/1319013/100923915-c59ae900-3494-11eb-8f8a-51d7766a1739.png)

**Comment by Allowee** [comment]
Hmm interesting.

Using Windows 10 Pro - 1903 [18362]

I did delete the agent and re-added it.
It would not update within a few minutes.

The Wi.fi adapter was not active, I will try to enable end rename it and report back

**Comment by Allowee** [comment]
Renamed 1 interface to "EthernetXX" , restart mesh agant service and instant update to the new name
Changed it back to "Ethernet" and restarted mesh agent... back to the correct name.

changed it to "Ethernet.test"... nothing
The "Last interfaces update" is not updating.

The text in the console after typing "netinfo" does update correctly... so I think this would  be related to the server and not the agent.

No other difference except for the . in netinfo

  EthernetXX: {
    0: {
      address: "fe80::8c83:8b1:1b50:84fb%13"
      fqdn: ""
      family: "IPv6"
      mac: "E8:D8:D1:71:3F:E1"
      index: 13
      status: "down"
      type: "ethernet"
    }
    1: {
      address: "192.168.1.57"
      gateway: "192.168.1.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.255.255.0"
      mac: "E8:D8:D1:71:3F:E1"
      index: 13
      status: "down"
      type: "ethernet"
    }
  }

  Ethernet.test: {
    0: {
      address: "fe80::8c83:8b1:1b50:84fb%13"
      fqdn: ""
      family: "IPv6"
      mac: "E8:D8:D1:71:3F:E1"
      index: 13
      status: "down"
      type: "ethernet"
    }
    1: {
      address: "192.168.1.57"
      gateway: "192.168.1.1"
      fqdn: ""
      family: "IPv4"
      netmask: "255.255.255.0"
      mac: "E8:D8:D1:71:3F:E1"
      index: 13
      status: "down"
      type: "ethernet"
    }
  }

**Comment by Ylianst** [comment]
Oh!! What database are you using? Are you using MongoDB by any chance? If so, what version of MongoDB? The problem is that MongoDB does not allow a "." in the key name. I will have to fix this.

**Comment by Allowee** [comment]
It does not seem so... although this installation is quite old.
I do see "NeDB"

> info
{
    "rss": 123060224,
    "heapTotal": 69365760,
    "heapUsed": 56915376,
    "external": 14159153,
    "dbType": "NeDB",
    "nodeVersion": "v11.10.1",
    "meshVersion": "0.7.1",
    "platform": "win32",
    "arch": "x64",
    "pid": 12840,
    "uptime": 732013.317,
    "cpuUsage": {
        "user": 165937000,
        "system": 34828000
    },
    "warnings": [],
    "database": "NeDB",
    "productionMode": false,
    "allDevGroupManagers": []
}

**Comment by Ylianst** [comment]
Interesting. Well, I do know that having a . in the key name of an object is sometimes a problem. I will need to investigate this.

**Comment by Allowee** [comment]
Also just tested on a  Debian server. Same result.

> info
{
    "rss": 167026688,
    "heapTotal": 43954176,
    "heapUsed": 42182160,
    "external": 12120667,
    "dbType": "NeDB",
    "nodeVersion": "v12.16.1",
    "meshVersion": "0.7.10",
    "platform": "linux",
    "arch": "x64",
    "pid": 23791,
    "uptime": 660.658128113,
    "cpuUsage": {
        "user": 4732000,
        "system": 428000
    },
    "warnings": [],
    "database": "NeDB",
    "productionMode": true,
    "allDevGroupManagers": []
}
> versions
{
    "node": "12.16.1",
    "v8": "7.8.279.23-node.31",
    "uv": "1.34.0",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.15.0",
    "modules": "72",
    "nghttp2": "1.40.0",
    "napi": "5",
    "llhttp": "2.0.4",
    "http_parser": "2.9.3",
    "openssl": "1.1.1d",
    "cldr": "35.1",
    "icu": "64.2",
    "tz": "2019c",
    "unicode": "12.1"
}

**Comment by Ylianst** [comment]
Ok, just found and fixed the problem. Will be in MeshCentral v0.7.33. Let me know if it works once the new version is published.

**Comment by Allowee** [comment]
Nice this is fixed. :)
Interesting that it was caused by escaping/unescaping
