### ISSUE TITLE
Keyboard repeated output

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#2039]
Hi Ylianst,

Since the update about 'better keyboard mapping' I've issues that my keyboard input is doubled on the client side. Thus if I type 'cmd', on the other end input appears 'ccmmdd'.

If I set the checkmark 'Use remote keyboard map' it works normally.

**Comment by krayon007** [comment]
> Hi Ylianst,
> 
> Since the update about 'better keyboard mapping' I've issues that my keyboard input is doubled on the client side. Thus if I type 'cmd', on the other end input appears 'ccmmdd'.
> 
> If I set the checkmark 'Use remote keyboard map' it works normally.

Which OS and version is your agent running on?

**Comment by jdvmanen** [comment]
versions output console:

> versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "commitDate": "2020-11-18T07:47:29.000Z",
  "commitHash": "2fc2206eb9c2476bd2079e467d7f621ec2c9acf8",
  "compileTime": "23:53:04, Nov 17 2020"
}


commandline:

C:\Program Files\Mesh Agent>ver

Microsoft Windows [Version 10.0.19041.630]


Op wo 2 dec. 2020 om 19:31 schreef Bryan Roe <notifications@github.com>:

**Comment by Ylianst** [comment]
FYI. As a temporary workaround, you can go back to using the old keyboard system by selecting "Use Remote Keyboard Map" in the desktop settings.

![image](https://user-images.githubusercontent.com/1319013/100923448-0a725000-3494-11eb-83b0-97a3ba23fdf3.png)

**Comment by jdvmanen** [comment]
yes I found that solution as well as mentioned in the issue start message. Wth that checkbox enabled it works fine.

**Comment by krayon007** [comment]
What browser are you using? I have that exact version of windows, and tested it with Chrome, and cannot reproduce the double key input...

**Comment by jdvmanen** [comment]
I use mostly the new edge browser but for remote desktop (not rdp) I use
the meshcentral router to initiate the session.

Another computer with exact the same behavior was:

> versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "commitDate": "2020-11-18T07:47:29.000Z",
  "commitHash": "2fc2206eb9c2476bd2079e467d7f621ec2c9acf8",
  "compileTime": "23:53:04, Nov 17 2020"
}
and
C:\Program Files\Mesh Agent>ver

Microsoft Windows [Version 10.0.18363.1198]



Third computer (microsoft surface):

 versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "commitDate": "2020-11-18T07:47:29.000Z",
  "commitHash": "2fc2206eb9c2476bd2079e467d7f621ec2c9acf8",
  "compileTime": "23:53:04, Nov 17 2020"
}

C:\Program Files\Mesh Agent>ver
Microsoft Windows [Version 10.0.18363.1237]


All the same behavior.



Op wo 2 dec. 2020 23:03 schreef Bryan Roe <notifications@github.com>:

**Comment by Ylianst** [comment]
"I use the meshcentral router to initiate the session." - Are you saying that this problem occurs when using the MeshCentral Router Desktop Viewer? Or are you seeing the problem with the web based viewer?

**Comment by jdvmanen** [comment]
Hi Ylianst,

Yes, I tried to say that this problem occurs when using the
MeschCentral Router Desktop Viewer. The web based viewer I'm not 100% sure,
I think I've not used the web based viewer.




Op do 3 dec. 2020 om 23:14 schreef Ylian Saint-Hilaire <
notifications@github.com>:

**Comment by lizardkng** [comment]
I am having this problem as well, Chrome version  89.0.4389.90 (Official Build) (64-bit) running windows 10 build 19041. Not using mesh router, using web desktop sharing. Mesh current version, 0.7.89

**Comment by si458** [comment]
this should now be fixed,
please use the latest version and also try the 'use remote keyboard map' option if your having issues,
you maybe also need to disconnect and reconnect for it to take effect
