### ISSUE TITLE
Duplicate machines

### ISSUE THREAD

**Issue by emersonnpe** [Ylianst/MeshCentral#2043]
Good afternoon everyone.

I use ** Mesh ** installed on a server ** Linux Ubuntu 18.04 **. The installed version of ** Mesh is 0.6.70 **, (recently updated from version 0.4.8)
On the host the machines are duplicated, and even using the connected / offline filter I saw several duplicated machines, some online, others off and some with the AMT technology repeated in some cases in more than 5.
The system works normally, but I have this problem of duplicating machines. Sometimes the number of duplicate machines increases, normally being machines in the Off status. Follows print of duplicate machines that the agent has but does not recognize, in this case it recognized only AMT (users' machines).
![mesh](https://user-images.githubusercontent.com/75445621/101085013-987e3180-358d-11eb-8248-4c8d8e165408.PNG)

Follows print of machines that have the agent and are offline (EXAMPLE: servers).
![mesh off](https://user-images.githubusercontent.com/75445621/101085302-0296d680-358e-11eb-8a3f-e73dbf411974.PNG)

NOTE: When I restart the server, the machines go up again (they stay with the online agent), but they duplicate even more.

**Comment by si458** [comment]
closing as stale
