### ISSUE TITLE
can't type into IBM AS400 5250 emulator

### ISSUE THREAD

**Issue by dashrender** [Ylianst/MeshCentral#2044]
MC version .7.x 
Windows 10 pro 1909 x64

We have iSeries Manager V5R2 (yep ancient) installed.  We can't type into the AS/400 session with normal keyboard input, simply nothing happens.  If we use the onscreen keyboard from Win10, it works.  

FYI - Previously we've used ConnectWise Connect and have no issue with the keyboard passthrough during remote access.

**Comment by Ylianst** [comment]
Can you try this and see if it works? Thanks.

![100923448-0a725000-3494-11eb-83b0-97a3ba23fdf3](https://user-images.githubusercontent.com/1319013/101094944-0a488200-3572-11eb-815e-6d6e69abead1.png)

**Comment by dashrender** [comment]
Wow, super fast. I did try that and the keyboard seemed to stop working completely, i.e. it wouldn't type into windows anymore either, nor the emulation software.

**Comment by krayon007** [comment]
Which browser are you using? And what OS is that browser running on?

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back

**Comment by silversword411** [comment]
As400 emulator?

I invite you to join the 21st century. 🤌

Step out from the darkness and enter the light.

**Comment by dashrender** [comment]
After more than 3 years, this is finally closed - the people want to come in here and harass me about joining the 21st century?  Seriously?

not that it matters - the client this question came from retired their AS/400 18 months ago.
