### ISSUE TITLE
Remove start page if a single SSO is chosen to handle user connection [Enhancement]

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2045]
Hi YlianSt,

Can there be a way to enable the server to drop the logon page if a single SSO option is selected by the server admin to run the whole access permission?

This would help for those that don't want users attempting to login with invalid credentials or off the SSO.

Thank you,
SomeGuru

**Comment by datapharmer** [comment]
I'd also like to see this or if easier a way to simply disable local login so SSO is the only mechanism available.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.30 with a new option to remove the username/password from the login screen:

```
"showPasswordLogin": false,
```

Note that the server will still allow username/password login and you can override the setting by adding ?passlogin=1 in the URL. This is very practical as you probably don't want to show this option to users if your only going to use it for admin accounts. let me know if this works.

![MC2-NoUserPass](https://user-images.githubusercontent.com/1319013/102703908-04b59200-422a-11eb-8765-a35b3cd43e8a.png)

**Comment by SomeGuru** [comment]
Got it, doing that on my server now… Thanks Ylian :)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
