### ISSUE TITLE
tls handshake error in bash script to run meshcmd

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#2048]
hi , i made a bash script but when i run it i get:
Error: Failed to verify server certificate.
Server TLS hash: A253020B5558A1D32313972A85A60571A170FF12FBABBA3EC031297AB94ADF8D63D3FCFDFAA63033E1EBD5001E277380
ERROR: {"message":"TLS Handshake Error"}

what could be ?

**Comment by Ylianst** [comment]
Is the batch script running MeshCtrl.js or MeshCMD.exe? Or something else? Can you please provide sufficient information so I can make the same problem happen on my computer. Thanks.

**Comment by tradexsrl** [comment]
i was connected with my rpi 3 to meshcentral web interface to the user account , i click on meshcmd and i select linux arm 32 bit (which is my os) and then i download it.next i chmod +x and i download also the meshaction.txt .
i do a nano mesh.sh , created a script to load that txt ...that txt was rebuild with nano editor because it gives error because was created in msdos mode..

**Comment by tradexsrl** [comment]
Hi , have you had a chance to check this error?

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
