### ISSUE TITLE
Consent Language

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#2049]
On client workstations, the request for consent during connection is in English. Is there a way to translate it into French ?
Thank You

**Comment by Yamacore** [comment]
is there a way to change the "allow" "deny" button text aswell?

**Comment by openncomp** [comment]
The translation of the "allow" and "deny" buttons into Russian does not correspond to the grammar.
"allow" = "разрешить"
"deny" = "отклонить"

**Comment by krayon007** [comment]
By the way, the user consent was updated on windows, and now supports translation. @Ylianst will have to chime in with regards to where to specify the translations. Translations are now also supported on notifications and privacy bar for all platforms as well.

**Comment by si458** [comment]
this has been implemented now
