### ISSUE TITLE
Safari browser in Big Sir fails to display MeshCentral Clients

### ISSUE THREAD

**Issue by ewm0657** [Ylianst/MeshCentral#2052]
Safari browser in Big Sir doesn't display MeshCentral clients. Firefox, Chrome, Brave all work. This has been replicated on MacBook, MacBook Pro, and Mac Mini.
![Snip20201206_1](https://user-images.githubusercontent.com/24573738/101290783-601b6500-37d2-11eb-8153-eb141ba9706d.png)

**Comment by ewm0657** [comment]
Firefox on same machine...
![Snip20201206_2](https://user-images.githubusercontent.com/24573738/101290846-ae306880-37d2-11eb-95ac-c5188c6e3f37.png)

**Comment by krayon007** [comment]
Wierd, it works on my 16" Mac Book Pro... I have an Apple Silicon mac arriving soon, so I'll test on that when it arrives.

![macOS Big Sur-2020-12-06-14-56-42](https://user-images.githubusercontent.com/29240564/101295590-6eb64c00-37d3-11eb-9fd3-dca7ddd0e318.png)

**Comment by ryanblenis** [comment]
@ewm0657 From previous issues (https://github.com/Ylianst/MeshCentral/issues/738#issuecomment-566898562), this can happen when you have a filter applied or a different view. Given the change in the sidebar between your Safari and Firefox screenshots, I'm thinking you may be logged in as a different user. Can you try clearing all your cookies for the site in Safari and logging back in?

**Comment by ewm0657** [comment]
It worked before Big Sir.

Eric Morgenstern

**Comment by ewm0657** [comment]
I only have 1 account on the server. I also opened up everything in Safari. Only difference is Big Sir and Safari, Catalina and Safari worked.

Really.. all 3 Mac’s don’t work since I upgraded. I can still access them remotely, in different browsers on the same machines. 

Eric Morgenstern

**Comment by Ylianst** [comment]
Bryan and I should get new Mac's this week and will look into this.

I have noticed that on iPhone's and iPad's if you are using a server that does not have a real trusted TLS certificate like Let's Encrypt, the web socket connection will fail even if you approved the invalid certificate warning. Are you using a server with a self-signed TLS cert?

Also, if you can open the browser's developer console and send back any errors you see, that also helps.

**Comment by ewm0657** [comment]
I use Let’s Encrypt, certificates. Safari trust the certificate. In the developer area, it is not reporting any errors. Chrome, Edge, Firefox, and Brave browsers all work fine, and I mostly use Firefox. I only tried Safari because iCloud works easier in Safari, so it was totally by accident that I even noticed it.

Like I said, you guys are awesome. This is not a priority for me. Just wanted to give you feedback.

Eric Morgenstern

**Comment by Ylianst** [comment]
Bryan and I both got our Apple M1 devices today. I tested Safari with my MeshCentral instance with and without trusted certificate and it works for me, I am using macOS Big Sur 11.0.1.

You could privately mail me a dummy account to your server, [contact info here](https://www.meshcommander.com/contact-information). I will do some testing.

**Comment by ewm0657** [comment]
I found the issue I think. I’m not sure why it is happening, but if I connect to wss://connect.XXXXXX.com it works

It may be that I use an Nginx server in front.

[Error] Refused to connect to wss://connect.XXXXXXXX.com/control.ashx?auth=n4tH8x9TqM5xiNJ0KOsaLelExg5NLfAkmTpGpH25f5Ncc4mSbyBixStdvQzfNVJIaDEiWkMKxKM5SWnHdxReWDiH9VReWN6k@NCruLFbGBRh8cL1RR0CGSKdRX8pzzFmeDJacU7FycqpQ1c= because it does not appear in the connect-src directive of the Content Security Policy.

[Error] SecurityError: The operation is insecure.
	(anonymous function) (meshcentral.js:27)
	(anonymous function) (meshcentral.js:27)
	startup (connect.XXXXXXXX.com:1399)
	onload (connect.XXXXXXX.com:41)

[Error] TypeError: null is not an object (evaluating 'userinfo.siteadmin')
	go (connect.XXXXXXXX.com:13212)
	onclick (connect.XXXXXXXX.com:159)

[Error] TypeError: window.serverMainStats.update is not a function. (In 'window.serverMainStats.update()', 'window.serverMainStats.update' is undefined)
	updateServerTimelineHours (connect.compusults.com:12969)
	onclick (connect.XXXXXXXXX.com:991)

**Comment by Ylianst** [comment]
That is exactly the problem, Safari is very strict with the 'Content-Security-Policy' HTTP header. In the domain section of the config.json, you could add: 

```
"httpheaders": {}
```

However, this will remove all security headers placed by MeshCentral and will lower your site security. If you want a better solution, you need fix the "Host" header sent to the MeshCentral server from NGINX to specify the correct host.

**Comment by ewm0657** [comment]
We can close this issue. Everything I try just makes it worse. I can manually go to wss://connect.domain.com instead if https://connect.domain.com, and is works fine in Safari. As I stated other browsers work fine with my configuration. I just can not get the proxy headers to pass the changes in Safari. It must be specific to my setup. My Nginx .conf file is identical to the User Guide. If I find a solution, I'll post it.
