### ISSUE TITLE
Mouse pointer accuracy off again

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2053]
I know this was an issue a while back but it seems like it had been resolved. But I'm noticing it once again- and it almost seems a bit worse this time around.
I'm finding that the accuracy of the mouse pointer is off.  I was trying to configure some apps in a new Server 2019 box and had a heck of a time resizing windows.  I'm finding the accuracy is off at least a few mm (although the actual measurement is completely depending on screen resolution, etc.).  It also never changes the cursor to reflect when you are on the edge of window (the double arrows)
 The odd thing, however, is that it's not off at all on other devices.  I have other Server 2019 boxes where it has perfect accuracy and does display the double arrows at the edge of a window.  

I do know this trouble is common among a certain set of hardware.  Namely the HPEnterprise ProLiant ML110 Gen10 servers I have.  All of those are experiencing this accuracy issue.  Those devices use the Matrox G200eh3 graphics card- so maybe the video driver has something to do with it?  It's a very low end graphics adapter (since it's on a basic file server).  

I do also have other servers (based on SuperMicro motherboards) that are also using the Matrox G200e chip- but that aren't having this issue.  

So just very weird.

**Comment by si458** [comment]
STALE CLOSING, if you still have this issue, please open a new issue
