### ISSUE TITLE
Export a detailed list of devices from groups

### ISSUE THREAD

**Issue by Electricity2015** [Ylianst/MeshCentral#2054]
It is possible to export a detailed list of devices from meshcentral ?

Thanks

**Comment by Ylianst** [comment]
Hi. Yes, you can select devices or hit "Select All" and then "Group Action" and you can export device information in .csv and .json format.

![image](https://user-images.githubusercontent.com/1319013/101535644-ced0fd80-394d-11eb-9f20-c9cdad25207e.png)

You can also use meshctrl.js to pull device information using the "DeviceInfo" action.

![image](https://user-images.githubusercontent.com/1319013/101535853-12c40280-394e-11eb-9897-69cad5cb1245.png)

Let me know if that helps,
Ylian

**Comment by Electricity2015** [comment]
Yes but ,How can i select all devices from a group?(not manualy)
And in export device information it dosen't give all details. It is a way to export from web all details of a device/devices ?

**Comment by Ylianst** [comment]
You can right click on a device group header and hit "Select All" to select all the devices in a device group.

![image](https://user-images.githubusercontent.com/1319013/101942106-da1a6800-3b9d-11eb-81ec-be470cffa1af.png)

Hope that helps.

**Comment by Electricity2015** [comment]
Ok thanks ,
but the export device options it dosen't give all details.
how can i export all details(hardware and software)  of devices?

**Comment by si458** [comment]
when you click expot device information, the is a new option saying 'include device details' which will include all spec of machine etc
![image](https://github.com/Ylianst/MeshCentral/assets/765314/ccf51f19-c3ec-4f1c-a901-069c90803382)

**Comment by JuniPlum** [comment]
> when you click export device information, the is a new option saying 'include device details' which will include all spec of machine etc ![image](https://github.com/Ylianst/MeshCentral/assets/765314/ccf51f19-c3ec-4f1c-a901-069c90803382)

I tried this; I only have a problem when I need the OS build version. I can only extract _Microsoft Windows 11 Home Single Language - 25H2/26200_ but not the whole build number _10.0.26200.9168_. Any way I could achieve this?

**Comment by si458** [comment]
@JuniPlum the field of BuildRevision is just missing from the csv,
but its in the JSON under `sys -> hardware -> windows -> osinfo -> BuildRevision`
if you need it shown in the CSV then please open a github issue and select feature request and we can look into it for you
