### ISSUE TITLE
Ghost entries when activating ACM agentless via meshcmd

### ISSUE THREAD

**Issue by ad-85** [Ylianst/MeshCentral#2055]
I am currently running an agentless environment. Using MESHCMD to enable AMT remotely (using the command from the Setup link) and then setting the MEBx password via policy within the MeshCentral GUI.

However, when I enable the host remotely, even though the trace logs pick up the hostname\port\successful import, the entry that appears under the mesh shows up as "None." If I delete the entry and then scan the network or manually add from the MeshCentral GUI, the device shows up and behaves normally.

Infrastructure: MongoDB & NPM install running on the same server.

![Mesh-Ghost](https://user-images.githubusercontent.com/75687646/101516813-f6c06100-394d-11eb-9b3f-e6c20457b60b.jpg)
![Mesh-Policy](https://user-images.githubusercontent.com/75687646/101516815-f758f780-394d-11eb-97d0-1f228c92ac70.jpg)

Any ideas?

**Comment by Ylianst** [comment]
Looking into it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.20 with plenty of bug fixes for using Intel AMT in agent-less mode. You should update your server and also re-download the latest version of meshcmd for the latest tricks.

- The device name will now show up correctly when a device is first added.
- If the device has a battery, when first added the mobile icon will be used.
- You can now specify `--pass [password]` on the `meshcmd amtconfig` line to send the AMT password to the server.
- You can now specify `--desc [description]` on the `meshcmd amtconfig` line to send a device description.

All these things only apply when a device is first added. Should make life a lot easier. Let me know if it works.

**Comment by ad-85** [comment]
Confirmed - fixed!! Thank you so much!
