### ISSUE TITLE
Sometimes the second menu bar with all the actions is not (or only partially) visible on Safari (iPadOS / iOS)

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2057]
When it is partially visible you are lucky and can click Terminal for example...

![image](https://user-images.githubusercontent.com/5128967/101616734-0902d380-3a10-11eb-9d12-da1d9a3d6f73.png)
![image](https://user-images.githubusercontent.com/5128967/101616865-2a63bf80-3a10-11eb-96ad-23f7a3626cdd.png)

MeshCentral 0.7.17
iPadOS 14.3

**Comment by vtacquet** [comment]
switching to Fixed Width Interface is a workaround 
![image](https://user-images.githubusercontent.com/5128967/101631392-8c2e2480-3a24-11eb-883a-98f83a0bdbfa.png)

**Comment by Ylianst** [comment]
Interesting. Thanks for reporting this. I will check when I get a chance.

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
