### ISSUE TITLE
how to work with cloudflare?

### ISSUE THREAD

**Issue by JustTestCode** [Ylianst/MeshCentral#2060]
when i use Flexible SSL Model in cloudflare ,chrome say `too many requests.`
Full model, i can open it,but after i login it,  `Unable to perform authentication, click to reconnect.`
use the lass MeshCentralInstaller-2.9.exe install it on win10

**Comment by JustTestCode** [comment]
already set certUrl 
```
{
   "settings": {
      "cert": "rdp.xxx.com", 
      "wanonly": true, 
      "_minify": true, 
      "clickonce": true, 
      "webrtc": true
   }, 
   "domains": {
      "":{
         "certUrl":"rdp.xxx.com"
      }
   }
}
```

```
C:\Program Files\Open Source\MeshCentral\node_modules>node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.17, WAN mode.
Loaded web certificate from "https://rdp.xxx.com", host: "rdp.xxx.com"
  SHA384 cert hash: e9b85c0c33dad26cc8d7ddb1530a61897840890139f3b5d763b2f27138
4e6570ad4816c30c16f7f35101287d945433
MeshCentral Intel(R) AMT server running on rdp.xxx.com:4433.
MeshCentral HTTPS server running on rdp.xxx.com:443.
```

**Comment by JustTestCode** [comment]
```
{
   "$schema": "./config.schema.json",
   "settings": {
      "cert": "rdp.xxx.club",
      "wanonly": true, 
      "_minify": true, 
      "clickonce": true, 
      "webrtc": true,
      "tlsOffload":"127.0.0.1",
      "Port": 80,
      "AliasPort": 80,
      "RedirPort": 800,
      "AgentPong": 300
   }, 
   "domains": {
      "":{
         "certUrl":"https://rdp.xxx.club"
      }
   }
}
```
still not working in  Flexible SSL Model ,

wss://rdp.meegar.club/control.ashx?xxxx
`{"action":"close","cause":"noauth","msg":"noauth-2"}`

still show `Unable to perform authentication, click to reconnect.`

**Comment by Ylianst** [comment]
Interesting. I have never tried CloudFlare. They do seem to support WebSocket connections. I have a lot on my plate, but I think I should be able to create an account and give it a try. if anyone else has tried this below, I would love to know.

**Comment by Ylianst** [comment]
Replace the line `"CookieIpCheck":false` with:

```
  "trustedproxy": true
```

You will see the right IP address start to show up.

**Comment by Ylianst** [comment]
FYI. Just added a way for MeshCentral to load the list of CloudFlare trusted proxies. Starting with MeshCentral v0.7.24, change the configuration to:

```
 "trustedproxy": "CloudFlare"
```

![MC2-CloudFlare](https://user-images.githubusercontent.com/1319013/101857329-1a390680-3b1c-11eb-90c7-1ff8ff3e8efa.png)

**Comment by JustTestCode** [comment]
thx,it's working now!

**Comment by LucasSaraivaAzevedo** [comment]
> hey there. can someone help me please. I tried your solutions but nothing works for me... meshcentral on docker. Tried to access via cloudflare tunnel, configured the json file with "trustedproxy": "CloudFlare". I can't access it... Can someone please help??

Still no fix until this day ???

**Comment by age6racer** [comment]
I'm having the same issue as @rpiproject 

I have MC (in a docker container) connected through a Cloudflare tunnel. 
I've tried TLS encryption mode on flexible.
I've added the "trustedproxy": "CloudFlare" line to my config.json

My agents cannot connect.

**Comment by kevpwhite** [comment]
For anyone else searching for this issue. You can find that there is an open case for it. 

https://github.com/Ylianst/MeshCentral/issues/5302
