### ISSUE TITLE
Recent Mac Updates?

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2064]
Did the recent agent updates break compatibility with older Macs? I have a Mac mini running 10.13.6 that has been working just fine until one of the recent updates (I'm not sure which as it was shut down for the last week or so). Tonight, it briefly connected, presumably updated, and has since refused to reconnect. Let me know if there's a log file or something I can provide (I seem to recall an option to include in the .msh file to generate a debug but I can't remember exactly what it was).

**Comment by Ylianst** [comment]
Yes. Bryan recently added support for Apple Silicon and came out with a new ARM and Universal Binary.

![MC2-AppleSilicon1](https://user-images.githubusercontent.com/1319013/101740931-4e5dea00-3a7e-11eb-916e-c305f1edf48e.png)

Bryan will have to do some testing.

**Comment by krayon007** [comment]
> Did the recent agent updates break compatibility with older Macs? I have a Mac mini running 10.13.6 that has been working just fine until one of the recent updates (I'm not sure which as it was shut down for the last week or so). Tonight, it briefly connected, presumably updated, and has since refused to reconnect. Let me know if there's a log file or something I can provide (I seem to recall an option to include in the .msh file to generate a debug but I can't remember exactly what it was).

Interesting.. I just did some testing, and it works going back to 10.14, but it doens't seem to work on 10.12 (I don't have a 10.13). The only difference I made, is that I compiled this last agent on my Apple Silicon macMini instead of my Intel Macbook Pro. But I compiled them both with big sur...  I'll do some more testing... Worst case, I'll recompile the intel binary on a different system, and remake the univeresal binary.

**Comment by krayon007** [comment]
Ok, I figured it out. It was the openssl/1.1.1i recompile. When I compiled openssl/1.1.1g, it was compiling with an older build target. However, openssl/1.1.1i was not set with a build target, so I hand modified the config to target an older build target, and recompiled it... I verified that the agent now works going back to 10.10. (That's the oldest environment I have at the moment).

Ylian is working on releasing it... The unfortunate part, is that if you already updated macOS that's older than 10.14, it looks like you'll have to manually update the binary or re-install, as that agent will exit when it tries to use openssl.

**Comment by Ylianst** [comment]
Publishing MeshCentral v0.7.21 with Bryan's updates now. Will be up in a few minutes.

**Comment by Ylianst** [comment]
MeshCentral v0.7.21 is published. Let us know if it works.

**Comment by PetieM** [comment]
That seems to have mostly fixed it so first and foremost, thanks for the quick turnaround! The agent now connects again and terminal and file access both work as expected. Desktop access though, while it does connect, seems to be having some display issues but only on my older system (it's fine on my 11.0.1 install). The dock and desktop background are visible but application windows, the menu bar, and the mouse are just white boxes. I've attached a cropped screenshot showing the top of the screen, a bit of the background, and the top of an application:

![Screen Shot 2020-12-10 at 9 39 18 AM](https://user-images.githubusercontent.com/16453878/101801903-154c6680-3acc-11eb-9281-9b4291b2bcfa.png)

**Comment by krayon007** [comment]
Did you try rebooting your machine? Here's a screen shot of the current agent doing KVM with macOS sierra - 10.12

![sierra](https://user-images.githubusercontent.com/29240564/101807052-850d2200-3ac9-11eb-9ed5-e6cbeb6ab549.png)

**Comment by PetieM** [comment]
I did - same behavior for me after reboot.

**Comment by krayon007** [comment]
Is VNC working correctly, or is that showing messed up too?

**Comment by krayon007** [comment]
Is the system showing the white boxes macOS 10.13?

**Comment by PetieM** [comment]
VNC is slow but looks correct. OS version is 10.13.6.

**Comment by krayon007** [comment]
I'm not sure where to look. I just setup a 10.13.6 high Sierra system, and KVM is working for me. Do you have other management software installed? Perhaps they are interfering with each other?

![highsierra](https://user-images.githubusercontent.com/29240564/101870364-4ceff880-3b36-11eb-868d-3ab0ac9981b4.png)

**Comment by PetieM** [comment]
So this issue seems to be getting more strange but it definitely seems like it may be limited to my specific machine. The KVM is now displaying correctly despite changing literally nothing but now the mouse doesn’t seem to be working correctly. I haven’t been able to narrow it down just yet but it behaves as if a key is being held down at all times (possibly space) which makes it impossible to left click on things but even that’s not consistent since I can click and drag on the desktop.

At this point, I think the original issue is resolved and I need to shift gears and reinstall. Any guidance on completely removing the agent software so I can reinstall clean?

**Comment by krayon007** [comment]
The easiest way to uninstall is to open a terminal window locally and go to where the agent is installed, usually /usr/local/mesh_services/meshagent
and run the following command:
`./meshagent -fulluninstall`

**Comment by PetieM** [comment]
Thank you. I’ll try that tomorrow but I think we can close this now as my issue no longer seems to be related.
