### ISSUE TITLE
Is there a way to use the router with Google accounts?

### ISSUE THREAD

**Issue by volkans80** [Ylianst/MeshCentral#2065]
Hi,

Our users using meshcentral with their google accounts but when we try to install router it is requesting username and password. Is there a way to use router with google account?

Thanks,

**Comment by Ylianst** [comment]
Yes. First, run MeshCentral Router and hit "Install..." to register it for the "mcrouter://" protocol. Then, go back to the website and hit the router link and "Launch MeshCentral Router"

![image](https://user-images.githubusercontent.com/1319013/101739864-fd99c180-3a7c-11eb-80f0-d61e2ad8db55.png)

That should get it connected regardless of the login system you use, including domain controllers, LDAP, etc.

You can also hit the "RDP" or for Linux machines "Putty" or "WinSSH" and MeshCentral Router will open directly to that device and launch the app.

![image](https://user-images.githubusercontent.com/1319013/101740096-45b8e400-3a7d-11eb-9f1d-50ea70cc4400.png)

Hope it helps,
Ylian

**Comment by volkans80** [comment]
Thank you for your quick reply.
