### ISSUE TITLE
[Feature] Settings on My Server page?

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2067]
Tried to search for this request, but with keywords like 'settings' & 'My Server'you get a lot of results.
My feature request:
Enable a view of all possible settings in the My Server page  and it's current setting (default or manually set)

Of course it would be ideal if the settings can be changed on that page as well, although this could be risky.

**Comment by si458** [comment]
this has been completed so i will close it

https://github.com/Ylianst/MeshCentral/commit/12a248f10238018c7c4cd05ba298fd89c1fb78c9
https://github.com/Ylianst/MeshCentral/commit/3a3663bb55ef34102f84e8ed65ef93625a132fd1
