### ISSUE TITLE
feature request to show the current time (vertical bar) on the 7 day power state view

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2069]
maybe even an title bar with 1-24 hours so it easier to see when someone was online

![time](https://user-images.githubusercontent.com/5128967/101913965-ffba6800-3bc3-11eb-9677-95e29a5e97a8.png)

**Comment by Ylianst** [comment]
Note that if you hover your mouse over one of the colored bars, it will show you the exact start and end time for that bar.

**Comment by vtacquet** [comment]
I know but still...

**Comment by vitko-bg** [comment]
May I join to this request with suggestion, please?
I advised on #808 that it will be very useful to have a timeline, looks similar to me with @vtacquet request.
here is the example
![image](https://user-images.githubusercontent.com/59362521/102218474-e708c580-3ed5-11eb-9107-ef556ac4098e.png)

At least to have a timebar, so it will be much easier to see connection/disconnection times.

Thanks

**Comment by si458** [comment]
closing as stale and this wont be added
