### ISSUE TITLE
Question: Terminal connecting as root user / implementing SSH

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#207]
During my testing phase of MC, I'm running a number of VirtualBox VMs to see how everything pieces together and of those VMs most of them are headless Linux (Ubuntu) systems. When installing I needed to run the script as a "sudo" user and so it doesn't surprise me that when I then use MC to remote into the system, I'm connected as the root user.

For most implementations that I can think of, SSH or even terminal access into the system as "root" is highly discouraged and so I wonder if there's a way of imitating perhaps an SSH connection as a particular user in place of, perhaps alongside, the terminal.

Now, I appreciate that there are capabilities of initiating an SSH connection to these servers via MeshRouter, but I'm still somewhat unclear how to achieve this in a headless Linux environment. I see in documentation "RDP", "SSH" etc links underneath a MC host and I would imagine that this would totally achieve I'm trying to do (with the added benefit of not having to grant terminal access to the user logging into MC) but again I'm struggling with how to achieve this.

Any assistance in being able to clear this up would certainly be appreciated!  Once I've gone through this successfully a couple of times, I would be more than happy to write up a "101" document to explain and then share with everyone who may be as confused as I appear to be!

**Comment by Ylianst** [comment]
Right now, the terminal is open we the same user and privileges as the MeshAgent.

So, when connecting the terminal tab, show the shell login prompt? Would require the user to have credentials on that machine. Or we could configure the agent to open a shell session to user "mesh" (or something) of that user account is present?

**Comment by Ylianst** [comment]
Any update on this? If I read the original post right, the request was to get more information on using MeshCentral Router / ClickOnce Router or MeshCMD Router? I am not clear what is requested.

**Comment by D4V3M0NK** [comment]
Ylian,
I'll close this - there's been a couple of other messages about setting up MC Router (Windows) or MeshCMD Router (Linux) ... I'm going to experiment with the Router product first on Windows and then when comfortable, see how to get it working on a Linux client. It's a really powerful utility to have, one that I just can't miss, but working day to day exclusively with Linux means using MeshCMD which I don't believe has too much information regarding it.  I'll open additional issues if I need them, but thanks for circling back to check.
