### ISSUE TITLE
Falcon CrowdStrike -> ALERT: [High] Malicious activity detected on MachineName

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#2070]
good morning, since last night falcon crowdstrike reports the following problem in connection with meshanget: 

SEVERITY: |   | High -   Prevented
TACTIC   & TECHNIQUE: |   | Execution via XSL Script Processing

Wmic attempted to launch a likely malicious payload via an Extensible Stylesheet Language (XSL) file. An adversary can embed a call to execute an arbitrary script from an XSL file, bypassing Windows security features. Review the XSL file and investigate the process tree.

it looks like this is related to one of the recent updates

any idea why? thanks for help and thanks for your real great product!

am

**Comment by Ylianst** [comment]
This is a question for Bryan. I know the MeshAgent will get platform data using WMI command-line (WMIC). He has made some changes because of #2058.

**Comment by krayon007** [comment]
Sounds like a bug in Crowdstrike. The only change, was that when using WMIC, I had to specify the full path of the XSL template, to work around a bug in Windows 7 and Windows Server 2008, where wmic was incorrectly searching the wrong folder if the locale and OS language were different.

Before, I just specified the template name, and windows found the template. Theoretically, one could swap the XSL in the folder wmic was expecting the file to be located, which would accomplish the same thing as what I would be doing.. So either this is safe, or it's not safe. If it's safe, then crowdstrike should detect the XSL path I specified points to the system XSL file. If it's not safe, then crowdstrike should'nt let you specify just the template name...

Not sure how to work around this, other than only specifying the XSL path on Windows 7 and Windows Server 2008, but that would add a bit of complexity, but wouldn't solve the end result of crowdstrike reporting a false positive.

**Comment by Ylianst** [comment]
Not sure it's a bug... but rather a false positive. I have never used Crowdstrike, I need to check it out.

**Comment by krayon007** [comment]
Well, I say bug, because if the issue is truly processing an XSL script, then this means even if you specify the XSL name, the same script would process. This means the prior behavior should have triggered the same warning, because it is still processing the exact same XSL script.

**Comment by wvt-adm** [comment]
is there any news on this yet, falcon crowdstryke generates nonstop detection alerts for us ;-) gruss am

**Comment by krayon007** [comment]
Is there anyway to whitelist the agent? This seems to be a false positive.

**Comment by si458** [comment]
closing as stale
