### ISSUE TITLE
Application name on mobile MFA

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2073]
FEATURE REQUEST?

Is there a setting that defines the MFA application name. On my Google authenticator, it lists the name of the application as a local IP address at the moment, whereas I believe it would be great to set this to (at least) the URL of the application that's accessible from a public point of view or (more appropriately) a shorter application name.

**Comment by PathfinderNetworks** [comment]
I use Authy for 2FA. In Authy I'm able to name each account whatever I want it to be named.  I would think Google Authenticator would let you name them whatever you want as well?  Seems crazy if it can't do that?

**Comment by D4V3M0NK** [comment]
@PathfinderNetworks Google authenticator will permit you to alter the username you're using (presumably for security reasons) but not the application name itself.

**Comment by PathfinderNetworks** [comment]
I did find this.  Looks like Google Authenticator uses the 'issuer' code to determine what to name the token.  I would think that should be something that can be modified within Mesh somehow? 
https://www.edwardthomson.com/blog/changing_titles_in_google_authenticator.html
"The QR code that you scan to set up a new account is generated by constructing a URL with the secret number and some metadata, and then encoding that with a QR generator. The format is:

otpauth://totp/account_name?secret=secret_key&issuer=Website_Title
The account_name - as the name suggests - reflects the name of your account on the website. This is your username or email address, generally. Google Authenticator shows this as the second line of the key.

The secret_key is the secret key that the web site gives you when you enable TOTP. (In the example above, it's XXXX ABCD XXXX ABCD).

Finally, the issuer is the name of the website itself. This is the larger header displayed above your key."

**Comment by PathfinderNetworks** [comment]
Also seems a bit crazy that Google Authenticator, by default, displays the account name as part of the 2FA token.  Yikes.  Authy only shows the 2FA code and whatever name I want to give it.  So if someone where to someone gain access to my Authy account/app there is no way they'd be able to figure out what my account name is for each of the tokens.  It's not even stored in Authy anywhere. 
Just seems like a pretty obvious security thing to not have that data be part of the token at all?

**Comment by D4V3M0NK** [comment]
@PathfinderNetworks correct  -  I've recently added MFA to a product that I'm working on and set the issuer to be the URL of that product itself as there's the possibility of one user using multiple sites using the same product. 

In another product, there's only one site so that `issuer` can be set to something a little more "application-esque".

Am hoping that there could be a setting that allows an admin to set something like `mfa_application_name` - at the moment, it's listed as an IP address of the server, which isn't overly useful.

**Comment by Ylianst** [comment]
Good request. Should be easy to change.

**Comment by Ylianst** [comment]
FYI. I will be slow in the next few days since I have not taken any real vacations since the start of the year... but will be looking into this.

**Comment by D4V3M0NK** [comment]
Certainly not urgent Ylian

**Comment by Ylianst** [comment]
The 2FA site name should match the domain name of you site. Now that I see in #2079 that you have not set this, is this issue still necessary? Since you where running your server in local LAN mode, it's normal that the IP address was used since no DNS was set.

**Comment by D4V3M0NK** [comment]
Again, you're 100% correct @Ylianst - the `cert` setting certainly becomes the `issuer` for the MFA client. I wonder if there's still a requirement here to make it (potentially) different - the `cert` can be quite a long URL whereas `mfaAppName` could be considerable shorter.  

The team has certainly got enough on their plate right now, so I will close this down - if you feel as if it's something you can add in, I'd certainly vote for it, but it's not a showstopper by any means.

Thanks again for all you do - especially considering you're not supposed to be working right now...!

Permit me to wish you a very Happy Christmas sir, and all the best for the New Year.
