### ISSUE TITLE
Enhancement request - sample-config-advanced.json

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2074]
It appears that `node_modules/meshcentral/sample-config-advanced.json` contains all of the available options for the current version of the software. Am thinking that it may be advisable to add a "version" entry to the top of the file, to show that the configs being shown will work for that specific version?

Eg:
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment__": "This is a sample configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__version__": "0.7.24",
  "settings": {
...
```

**Comment by Ylianst** [comment]
I am not exactly sure why this should be done? One could argue that all the files in the package (HTML, JS, CSS...) should be tagged with the number number?

**Comment by D4V3M0NK** [comment]
I don't believe (?) that the majority of people are changing the other files in the package, but it's highly likely that `config.json` will be altered according to requirement. I guess what I'm trying to suggest is that certain settings are only available in specific versions so perhaps there should/could be a history file ascertaining when the newer config settings were introduced? AFAIK, the sample file is the _only_ place where _all_ the config options available are listed.

At the moment I take it that in order to use any of the settings shown in the sample, one must assume that the very latest version of the software is to be used? If that's the case, is it the latest, or the _stable_ version? Both are options within the GUI to upgrade, if you're behind.

Perhaps there should be another page that outlines when/how to use the options that are available? That way the specific version could also be listed so that users would know that they'd need at least that version (or greater) in order for the software to use it.

**Comment by si458** [comment]
cloasing as stale and this wont be done
the idea of the sample-config-advanced.json is to show end users the possible options
in theory you would load up your config.json in visual studio code,
which in turn will load the lastest meshcentral-config-schema.json from the master repo and show all the available options
