### ISSUE TITLE
Cannot use space bar

### ISSUE THREAD

**Issue by valnar1** [Ylianst/MeshCentral#2075]
When I am running the interactive client on a Windows 10 (possibly others?) client machine, everything appears to work except the space bar.  I am running the latest version 0.7.24.  I remember it happening for a while, thinking it would fix itself, but for several versions.

**Comment by valnar1** [comment]
Correction.  It does it for the installed version too.

**Comment by krayon007** [comment]
Which browser are you using, and what OS is the browser running? I assume you are referring to the space bar on KVM?

**Comment by valnar1** [comment]
Yes, KVM on Chrome.

I found the problem.  I use an extension called "SmoothScroll" that was causing it.  If you turn off Keyboard Support within that extension it fixes it.  I don't believe there is anything that needs to be done with Meshcentral.
