### ISSUE TITLE
2FA works via router, 2FA not working via Webgui

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#2076]
So i recently had an issue with my server that needed the ubuntu boot disk rescue tool to resolve.

Post running the rescue the server boots up fine, no errors and the meshcentral services start.

I have configured the system to require 2fa and when i try to login via the router it works a charm, but via the webgui - the 2fa code is never accepted, this is what I see in the debug logs when trying to access the gui:

WEBREQUEST: (myip) /
WEB: handleRootPostRequest, action: tokenlogin
WEB: checkUserOneTimePassword()
WEB: checkUserOneTimePassword: fail (2).
WEB: handleLoginRequest: invalid 2FA token
WEB: handleRootRequestEx: sending 2FA challenge.
WEB: getHardwareKeyChallenge: fail
WEB: handleRootRequestLogin()

Server is running on latest version i believe, i cant logon to see but i tend to update as soon as new builds come out.

Any ideas 
?

Thanks

**Comment by drnikcuk** [comment]
Just to add, to get round this I have added my dns to the skiptwofactor setting in the config.

Would be nice to get it working again though.

**Comment by Ylianst** [comment]
When you say you are entering a code... are you using Google Authenticator App? A backup code?

If you are using a time based password, make sure your server is setup with the correct time and time zone. There server's UTC time needs to closely match the time on your phone.

**Comment by drnikcuk** [comment]
It was user error.

Sorry !!!
