### ISSUE TITLE
Weird Bug when using the Type feature with Powershell

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#2078]
I just tried opening a powershell on the remote computer through the GUI not the agents built in powershell feature and using the Type feature to enter a command.

The command I entered is below.

`Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

For some reason there were a bunch of extra letters.

`Get-ApppxPackage -alllusers Microsoft.WindowsStore | Foreach {Addd-ApppxPackage -DisableDevelopmentMode -Register "$($_.InstalllLocation)\ApppXManifest.xml"}`

If I open notepad it works fine and if I type individual letters or even individual parts of the command (e.g. Get-AppxPackage) it works just fine in power shell. It's only when pasting the whole command that it has an issue.

**Comment by ryanblenis** [comment]
There is an existing issue for this (https://github.com/Ylianst/MeshCentral/issues/2035) but I noted the issue as well "typing" into the password field on a web page via mesh today (server version 0.7.10, client OS (admin) OSX / Chrome, client target OS Windows Server 2012, "typing" into Chrome) with a password with successive repetitive characters).

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back
