### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2079]
Could someone please give me some clarification on some of the advanced settings within MC2, as my agents aren't being listed in the MC2 GUI and I'm 100% sure it's an advanced setting that I'm either not reading right, or not fully understanding.

In running MC2 behind load balancers, I notice that, when reviewing the AddAgent script for Linux, I see an IP address listed.  This is the same IP address that's shown when running the server in `--debug` mode, but is not the IP address that's configured on my server. That makes sense (considering NAT rules) so I'm guessing that there's a call made out (by MC2) to ascertain what address it thinks it should use? If so, then I'd like to understand how that call is made, considering that when I use something like `curl https://ipinfo.io/ip` I get a different IP address (a public one) and then IP in the AddAgent script is a private one. Either IP address is actually not the address that incoming calls are made on - for security, my server makes initiating online calls using an  address that's different to the one that users, or the MC2 agent, should use when attempting to login/connect.

I thought that the advanced "settings.agent*" settings are used here, but even in the User Manual, it's not clearly defined where and how each is used. There are NGINX reverse proxy settings as well as others, but it's not really explained how they're used (not to a simpleton like myself, that is). What I'm thinking of doing is, once I have this information, creating an image explaining which setting is used and where which hopefully might make this kind of setup a little easier to understand.  

Additionally, I'm sure there are some other settings that I need to be aware of when running behind LBs?

The agent script currently looks like this:
`(wget "https://INT_IP_ADDR/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || wget "https://INT_IP_ADDR/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo -E ./meshinstall.sh https://INT_IP_ADDR 'uniQueC03Pr0v1d3dByM35hc3ntr4l' || ./meshinstall.sh https://INT_IP_ADDR 'uniQueC03Pr0v1d3dByM35hc3ntr4l'`

I wondered which setting would be used to change (for starters) the INT_IP_ADDR to a public address, so I thought I'd try this config (with the exception of `trustedProxy`, everything is literal) to see if at least in the agent string, I could get that public address, but no luck thus far:

<details>
<summary>ConfigA</summary>

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "trustedproxy": ["LB_INT_IP_A", "LB_INT_IP_B"],
    "agentPort": "agentPort",
    "agentPortBind": "agentPortBind",
    "agentAliasPort": "agentAliasPort",
    "agentAliasDNS": "mq9.dev.vaultara.com"
  },
  "domains": {
    "": {
      "title": "domains..title",
      "title2": "domains..title2",
      "_minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "passwordRequirements": {
        "force2factor": true
      },
      "_cookieIpCheck": false
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```
</details>

When I alter the AddAgent script to point to the public address of my MC2 server, and run it on a test remote system, the agent certainly appears to download and install. However that's about as far as I get.

Now - to complicate matters just that little bit further - I've also had to build the agent manually as on this system, I have to be FIPS 140-2 compliant, which means dropping back to Node v8 and OpenSSL 1.0.2g-fips.  I've used [other tickets](https://github.com/Ylianst/MeshAgent/issues/44) to build the agent but I guess there's a reasonable chance that it's not as successful as I deemed it to be?

Are there test tools that we have access to that can check where we're going wrong?

**Comment by krayon007** [comment]
@Ylianst can pipe in about the server related things... But for the agent side of things...  Were you able to compile the .a files? Normally this is the command we use to configure OpenSSL when compiling, for linux on 64bit x86:
`./Configure linux-x86_64 no-weak-ssl-ciphers no-srp no-psk no-comp no-zlib no-zlib-dynamic no-threads no-hw no-err no-dso no-shared -no-asm no-rc5 no-idea no-md4 no-rmd160 no-ssl no-ssl3 no-seed no-camellia no-dso no-bf no-cast no-md2 no-mdc2
`

If you copy the two .a files into `MeshAgent/openssl/libstatic/linux/x86-64` and compile the agent, it should work. You can verify by running: `./meshagent -info` as that will query the actual linked openssl library to display the version string... It should match what you think you compiled against.

**Comment by krayon007** [comment]
On a side note, you shouldn't have to compile libturbo-jpeg, as it's basically a stand-alone library that doesnt' depend on any of the other components.

**Comment by Ylianst** [comment]
By default, MeshCentral starts in "LAN mode" where the server has no DNS name and the agents will multicast on the local network to find the matching server. This is nice to get started with, but not what you want in your case. You will first need to set the "cert" line in the settings section to the DNS name of the server. That is, the name that users and agents will generally use to communicate with the server. In you case, you probably don't want to be managing devices on the local network, so you also want "WANonly" set to true. Something like this:

```
  "settings": {
    "cert": "mq9.dev.vaultara.com",
    "WANonly": true,
    "trustedproxy": ["LB_INT_IP_A", "LB_INT_IP_B"]
  }
```

Oh top of this, if you really want agents to connect on a different port or DNS name than users, you can use the "AgentPort" settings. AgentPort should not normally be needed.

Let me know if that helps.

**Comment by D4V3M0NK** [comment]
@Ylianst - yup, setting `cert` certainly updated the AddAgent script and everything looks like it's running from a server point of view, thanks for the assistance there.  I'll close this out for the time being.

@krayon007 Bryan, I think I definitely have a problem with the agent though - when I run `meshagent -info` on the client, it's coming up with OpenSSL 1.1.1i which should read 1.0.2g.  I'm thinking (though) that when I run a server update, I'm guessing that it also installs a new agent, would that be correct @Ylianst?
