### ISSUE TITLE
CloudFlare proxy

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#2080]
https://github.com/Ylianst/MeshCentral/issues/2060

My config.json does not have "CookieIpCheck":false in the settings section.

Is it ok to manually add the Cloudflare line?

**Comment by Ylianst** [comment]
Hi. If you add the line:

```
"trustedproxy": "CloudFlare"
```

MeshCentral will start to see the real IP address of the users and so, you will no longer need to have the `"CookieIpCheck": false`. Hope that helps.
