### ISSUE TITLE
Feature Request - Way to update the installer icon and imagery that's displayed on the download pages

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#2081]
Would be awesome to have customization options for the download page, and the icon of the file when they download to install it.  

Thanks!

**Comment by Ylianst** [comment]
If you can provide a screen shot of what screen and icon you would like customized, that would be great. Thanks.

**Comment by LPJon** [comment]
![MeshAgentInviteDownloadPage](https://user-images.githubusercontent.com/46533576/103387901-eb370480-4acb-11eb-8692-39a2ed654da4.jpg)

@Ylianst 
- This is the screenshot of what we would like to be able to customize. It would be nice if each of the options had a customizable image we could assign. Maybe even a branding image that could be embedded into the page just so the customer feels for sure they are at the right place. 

- The "Icon" referenced is the image that is used on the Agent installer and MeshAgent.exe file. It would be nice to brand this installer with an icon that reflects the business logo. This really makes it a lot easier when instructing a user what to look for when they download the agent. An image is generally easier to locate than a name for most users with lots of things in their downloads folder.

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
