### ISSUE TITLE
[Feature] Customized list of keyboard shortcuts

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2084]
The current list are for "windows" desktops. For Mac OSX a different set of shortcuts is needed. I would like to customise the list of keyboard shortcuts for the desktop session.
For example a CMD+ALT+D, so I can show/hide the docker on the remote MAC OSX.
Currently when the remote dock is hidden, it is impossible to show the dock by mouse hover action, because the mouse pointer must be remotely at the lowest pixel row of the screen. And the remote desktop session does not move the the remote mouse pointer to the lowest pixel row. So it can not trigger to show the dock. That's why I need the remote keyboard shortcut CMD-ALT-D.

**Comment by Ylianst** [comment]
Published in MeshCentral v0.7.45. Let me know if it works.

![MC2-KeyboardShortcuts1](https://user-images.githubusercontent.com/1319013/103988765-7efb7700-5143-11eb-86a8-381760e50cf0.png)

**Comment by hunter-nl** [comment]
Great! For windows agents it is working. But for MacOS agents not. As Win key is not the same as Command ⌘ key. If this can be supported also then you make my day 👍 
And maybe customise the order of the shortcuts would be also a bonus.

**Comment by Ylianst** [comment]
Ok, next version (v0.7.45) will have the bonus. There are re-ordering arrows.

![image](https://user-images.githubusercontent.com/1319013/104015151-132c0500-5169-11eb-9aea-05fcac5a6098.png)

**Comment by hunter-nl** [comment]
Thanks for the quick addition of the customised shortcuts. It works great now for windows agents. But for the MacOS agent I can not create a shortcut with the command ⌘ key. I need this to get a shortcut ⌘ (command) + ⌥ (option/alt)+ D to hide/show the dock. It is impossible to show the dock right now due the mouse pointer can not far enough to the bottom (outside the screen range) to trigger the show dock action.
So hopefully you can also add the special key ⌘ to the shortcuts dialog for the MacOS agents.

**Comment by Ylianst** [comment]
FYI. Added shortcut customization support to the mobile app.

![MC2-MobileAppImprovements](https://user-images.githubusercontent.com/1319013/104111353-b4b07500-5295-11eb-862a-ebd96220bff7.png)

Ha yes, I need to work on macOS command key. Can you close this issue and open a new one for that? I will take a look into it. Thanks.
