### ISSUE TITLE
Add sendgrid support to nodemailer

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2086]
Right now the way nodemailer sends email isn't compatible with sendgrid. Expectations are described here: https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/

As a workaround I have added nodemailer-sendgrid-transport and patched the options manually in meshmail.js but this obviously gets overwritten on upgrade.

I'm hoping we can specify additional nodemailer options per https://sendgrid.com/blog/sending-email-nodemailer-sendgrid/ in the config in an upgrade safe way or otherwise support sendgrid for smtp.

**Comment by Ylianst** [comment]
Interesting. I just created an free account and working on integration now.

**Comment by Ylianst** [comment]
I just got SendGrid to work with these settings:

```
  "smtp": {
    "host": "smtp.sendgrid.net",
    "port": 465,
    "from": "verifiedSingleSender@server.com",
    "user": "apikey",
    "pass": "*****MYAPIKEY*****",
    "tls": true,
  }
```

Going to explore a bit more.

**Comment by Ylianst** [comment]
I get a free account, setup an API key and tested MeshCentral with these settings and it worked just fine:

```
  "smtp": {
    "host": "smtp.sendgrid.net",
    "port": 465,
    "from": "verifiedSingleSender@server.com",
    "user": "apikey",
    "pass": "***********MY API KEY***********",
    "tls": true
  }
```

I presume you did not try it? In any case, I added native support for SendGrid in MeshCentral v0.7.28. Instead of the "smtp" section, you will be able to add this:

```
  "sendgrid": {
    "from": "verifiedSingleSender@server.com",
    "apikey": "***********MY API KEY***********"
  }
```

MeshCentral will use the SendGrid WebAPI to send messages which is the recommended option.

**Comment by Ylianst** [comment]
Just sent [this out on Twitter](https://twitter.com/MeshCentral/status/1339355356367994880).

![MC2-SendGrid](https://user-images.githubusercontent.com/1319013/102419998-e47d9d00-3fb5-11eb-9191-960abba4750c.png)

**Comment by datapharmer** [comment]
Awesome, thanks! I was running into auth problems when I tried with an api key as recommended and base64 encoded. maybe the base64 encode info was wrong? The api is preferred so this is even better regardless!

**Comment by datapharmer** [comment]
I can confirm this works great!

**Comment by Ylianst** [comment]
On a related topic, you can test server emails using the "email" command on the "My Server" / "Console" tab. Quick way to find out if everything works ok.

![image](https://user-images.githubusercontent.com/1319013/102465111-1a487300-4002-11eb-84b0-1b6e6238d2e2.png)
