### ISSUE TITLE
Windows logon forces blue screen

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#2087]
Hi

I notice from time to time, that when i logon to remote windows machine, agents disconnects for a minute and came back. Now i know what happens. When i connect to remote windows machine i click send Ctrl-Alt-Del command. Windows asks me for password. I enter password and screen freezes. At this time sometimes it is enough to disconnect and connect again and i got desktop (i have an old topic on this. Answer was that rendering system at behind will be changed soon). But sometimes PC get blue screen.

Yesterday:
Dell server R520, running Windows 10 64-bit. Installation of Mesh works fine. Connects to server. But when i connect to Desktop and enter password, server emidiatly gets blue screen. Mesh agent log is showing only:
[2020-12-16 02:55:49 PM] Info: No certificate was found in db

Blue screen says Stop code: SYSTEM SERVICE EXEPTION
What failed: win32kbase.sys

I also notice Event viewer an event at crash:
Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          12/16/2020 3:49:13 PM
Event ID:      10016
Task Category: None
Level:         Error
Keywords:      Classic
User:          SYSTEM
Computer:      HDNVR1
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID
{8D8F4F83-3594-4F07-8369-FC3C3CAE4919}
 and APPID
{F72671A9-012C-4725-9D2F-2A4D32D65169}
 to the user NT AUTHORITY\SYSTEM SID (S-1-5-18) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-16T14:49:13.954541900Z" />
    <EventRecordID>3280</EventRecordID>
    <Correlation />
    <Execution ProcessID="976" ThreadID="1020" />
    <Channel>System</Channel>
    <Computer>HDNVR1</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="param1">application-specific</Data>
    <Data Name="param2">Local</Data>
    <Data Name="param3">Activation</Data>
    <Data Name="param4">{8D8F4F83-3594-4F07-8369-FC3C3CAE4919}</Data>
    <Data Name="param5">{F72671A9-012C-4725-9D2F-2A4D32D65169}</Data>
    <Data Name="param6">NT AUTHORITY</Data>
    <Data Name="param7">SYSTEM</Data>
    <Data Name="param8">S-1-5-18</Data>
    <Data Name="param9">LocalHost (Using LRPC)</Data>
    <Data Name="param10">Unavailable</Data>
    <Data Name="param11">Unavailable</Data>
  </EventData>
</Event>

**Comment by alesribic73** [comment]
Hi

Any news on this? i have 3 such machines st a customer site and i can not use MeshCentral...

**Comment by krayon007** [comment]
Can you provide more details on the client PC that is blue screening? I have not been able to reproduce a Bluescreen in any of my test systems. Are the machines that are Bluescreen similar in hardware configuration, or different from each other?

**Comment by alesribic73** [comment]
It is DELL rack mount server including:
-Windows 10 Enterprise 2016 LTSB - 1607 [14393] 64-bit
-BIOS 2.9.0
-Name: 051XDX
-Matrox G200eR (Renesas) WDDM 2.0
-NVIDIA Quadro M2000
-12Gb RAM
-DELL 12Tb HDD
-DELL 200Gb HDD

**Comment by alesribic73** [comment]
Any news on this?

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
