### ISSUE TITLE
smtp and invite code

### ISSUE THREAD

**Issue by Shootify** [Ylianst/MeshCentral#2088]
hello guys, i just installed this AWESOME software, trying to do some tweaks, like addin smtp and active Invite codes, however when i add the corresponding codes to the config.json files server wont start and get an error message : Unable to parse. would some please share a complete working config.json with no syntax error with smtp, agentinvitecodes. thanks for the help.

**Comment by petervanv** [comment]
activate the invite code:
![image](https://user-images.githubusercontent.com/58996467/102460534-6bc72100-4047-11eb-8905-6fe8502f66c1.png)

smtp like this: (using gmail)
![image](https://user-images.githubusercontent.com/58996467/102460919-f3149480-4047-11eb-91f2-6e9db02932c0.png)

tip, show yours, but make sure there is no personal data (replace with XXXXX)

**Comment by Ylianst** [comment]
Thanks. The config.json file is in JSON format which is really strict on it's syntax and so, if you are not familiar with JSON it's easy to create an invalid file. At some point I will add an easier editor but for right now, you need to be really exact in how you write the JSON file.

The easiest trick is to make changes and run the resulting JSON text thru a JSON lint tool, [DuckDuckGo has one built it here](https://duckduckgo.com/?t=ffnt&q=JSON+lint&ia=answer). Cut and paste the entire file into the browser and hit "Validate JSON". It will indicate if there are any issues.

Note that I don't recommand cut & pasting any secrets or private data into any web page, so best to replace any secrets with "xxxxxxx" before running the check. Once you get familiar with the format, it will be natural.

![image](https://user-images.githubusercontent.com/1319013/102463098-82e22080-3fff-11eb-921e-50727c74b040.png)

Make sure you have the same number of `{` as `}` and that you put a comma at the end of lines only if there is another value in the same section on the next line, etc.

Hope this helps,
Ylian

**Comment by Shootify** [comment]
thank you for the help guys, i got the Invite codes working on it, however i tried the smtp and i get this error :
SMTP mail server mail.mydomain.com failed  {"code":ESOCKET","command":"CONN"}
thank you.

**Comment by Ylianst** [comment]
If you are setting up a server to connect to a GMail account, use this:

```
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 465,
    "from": "xxxxxx@gmail.com",
    "user": "xxxxxxx@gmail.com",
    "pass": "xxxxxxx",
    "tls": true,
  }
```

For other servers, try `"tls": false`. You may think that this will not make it secure, but actually MeshCentral will connect and upgrade to TLS after a short exchange with the mail server. So, "tls":true only indicates that you need to start TLS right from the start, but even if false the connection will likely still be secure.

Let me know if that helps.

**Comment by Shootify** [comment]
hi Ylianst, i tried it with true and false, didn't worked.

**Comment by Ylianst** [comment]
Ok. Not sure I can help beyond this. You can always try turning on email tracing in the "My Server" tab and use the "email" command in the server console to help debug.

![image](https://user-images.githubusercontent.com/1319013/102704718-e48ad080-4233-11eb-9cf8-20303f53c900.png)

![image](https://user-images.githubusercontent.com/1319013/102704731-fb312780-4233-11eb-8bc9-85f1adb00769.png)

**Comment by Shootify** [comment]
alright thanks for the help.

**Comment by petervanv** [comment]
sometimes it helps to connect to an ipadres off the smtp server instead off the name. open cmd (windows) and type:  ping smtp.mydomainname.com  there's an ipadress as response, use that adres in the connection in the config,json. let us know off that worked for you
