### ISSUE TITLE
RDP Link - Refused to frame '' violates CSP

### ISSUE THREAD

**Issue by Jonathan-Garber** [Ylianst/MeshCentral#2090]
So the "Launch MeshCentral Router" link is busted and so is the "RDP" link on each machine/target.
Using Brave Browser - Console shows

>Refused to frame '' because it violates the following Content Security Policy directive: "frame-src 'self'".

Where is the CSP set for MeshCentral? Any pointers?

**Comment by Jonathan-Garber** [comment]
I fixed it for now by modifying headers in nginx configs. You guys may want to consider using a different method here.
I didn't dig deep into it, all I see is the console saying the iframe source is '' (blank) so if that really is the case you can try calling your Javascript in the source or using a blank call in the source.

Pseudo code...

```
<iframe src="javascript:functionhere();"
```
```
<iframe src="javascript:;"
```
That may allow CSP to properly check the source.

**Comment by Ylianst** [comment]
I just downloaded Brave and tested my dev server with and without NGINX and there was no issue at all. I will note that in the MeshCentral code, the `frame-src` is set like this:

```
frame-src 'self' mcrouter:
```

Is it possible that you NGINX configuration was overriding the MeshCentral Content-Security-Policy header  and removing the 'mcrouter:' portion? Thanks.

**Comment by Jonathan-Garber** [comment]
Nginx shouldn't be overriding anything like that but I'll review configs
again tomorrow to see if anything stands out.

I'm running Nginx 1.19 on Ubuntu 20.04

**Comment by Ylianst** [comment]
If you can post your NGINX config that would be great. Make sure to "xxxxx" any private values.

**Comment by Jonathan-Garber** [comment]
Clean install of Ubuntu 20.04 and Nginx 1.19

>Refused to frame '' because it violates the following Content Security Policy directive: "frame-src 'self'".

From my understanding the error message indicates the CSP is violated due to the 'self' directive.
Meaning that your CSP definition of 'self' is violated because the iframe referenced a '' (blank) source.
If you are defining your directives as

>frame-src 'self' 'mcrouter';

It won't matter because the source is '' (blank) which fails all directives from what I can see.

Is your code actually using <iframe src="" or is it more like <iframe src="mcrouter ...."
Inspecting the page shows a call to javascript function but I didn't dig any deeper.
I am guessing this function builds the iframe that Brave is blocking.

```
<a href=# cmenu=altPortContextMenu id=rdpMCRouterLink onclick=p10MCRouter("' + node._id + '","RDP2") title="' + "Requires installation of MeshCentral Router" + '.">' + "RDP" + '</a>
```
I think I see why you iframe it out, because you allow an alternate port to be set in the UI.
I'm not sure how everything here was coded but can you just use JS to generate a mcrouter hyperlink and insert the value for alternate port. Bypassing the need for an iframe at all?

JS routine get value of alternate port, build mcrouter link
```
mcrouter://blahblahblah... custom port value etc.
```
Just kicking ideas around here

Nginx Configs...
I am not an expert here by far so you may see something I don't but I don't see anything modifying CSP headers.

Configs have not been adjusted or fine-tuned.
No configs in conf.d directory
Configs below.

Nginx
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 768;
}
http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

Host
```
server {
  listen 80;
  server_name *******;
  return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl;
    proxy_send_timeout 330s;
    proxy_read_timeout 330s;
    server_name *****;
    ssl_certificate *********;
    ssl_certificate_key *************;
    ssl_session_cache shared:WEBSSL:10m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:4430/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;      
    }
}
```

Let me know if you can see anything or think of anything else.
I fixed it on my end by telling it to ignore CSP headers entirely. Not a real proper solution but works for now.

**Comment by wh1te909** [comment]
he is using my install script which is overriding: https://github.com/wh1te909/tacticalrmm/blob/0a9c647e199dbb7e16435fb75a3dadb5f6a5a46b/install.sh#L282
I haven't updated that in a while, not sure why I had to set those was a while ago, I remember it having something to do with embedding in iframe was not working unless i added those overrides. Not sure if they are still needed

**Comment by Jonathan-Garber** [comment]
Thank you for clarifying.

I wasn't expecting RMM to be factor here since it's more of an interface to MeshCentral functions. Sad thing is I was in that config to adjust the Title fields but didn't even notice the headers there.

closing this as I can address it on my own now.
