### ISSUE TITLE
Sudden system failure

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2093]
Hi, tonight the server wasn't responsive and I'm getting the following status from the service:

● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-12-19 02:12:31 UTC; 43s ago
 Main PID: 3588 (node)
   CGroup: /system.slice/meshcentral.service
           └─3588 /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral

Dec 19 02:13:14 node[3588]: at ChildProcess.exithandler (child_process.js:294:12)
Dec 19 02:13:14 node[3588]: at ChildProcess.emit (events.js:194:15)
Dec 19 02:13:14 node[3588]: at maybeClose (internal/child_process.js:970:16)
Dec 19 02:13:14 node[3588]: at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Dec 19 02:13:14 node[3588]: killed: false,
Dec 19 02:13:14 node[3588]: code: null,
Dec 19 02:13:14 node[3588]: signal: 'SIGKILL',
Dec 19 02:13:14 node[3588]: cmd:
Dec 19 02:13:14 node[3588]: '/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 3588' }
Dec 19 02:13:14 node[3588]: ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

Restarting the service, server or running an in place install didn't help. 
~

**Comment by datapharmer** [comment]
I do not see a MeshErrors.txt file either.

**Comment by Ylianst** [comment]
Can you manually run the server? Do this:

```
cd /home/ec2-user
node node_modules/meshcentral
```

Let me know what you see.

**Comment by datapharmer** [comment]
I get the same message:

$ cd /home/ec2-user
$ node node_modules/meshcentral
{ Error: Command failed: /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 3530

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: null,
  signal: 'SIGKILL',
  cmd:
   '/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 3530' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

**Comment by Ylianst** [comment]
I have never seen this. Before going too deep, backup you "meshcentral-data" folder offsite if you have not done so yet. Then, rename the node_modules folder and install MeshCentral again, this will not reset your server' data or database.

```
cd /home/ec2-user
mv node_modules node_modules_bak
npm install meshcentral
node node_modules/meshcentral
```

This way, if there is anything corrupt in the server, that will reload a fresh copy. Let me know what you see.

**Comment by datapharmer** [comment]
ahh actually found a mesherror file...  here we go:

/home/ec2-user/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:118:12)
    at createUnsafeBuffer (buffer.js:112:25)
    at Function.allocUnsafeSlow (buffer.js:302:10)
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:270:29)^M
^M
^M
-------- 12/19/2020, 3:15:57 AM ---- 0.7.28 --------^M
^M
/home/ec2-user/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: ENOENT: no such file or directory, rename '/home/ec2-user/meshcentral-data/meshcentral-stats.db~' -> '/home/ec2-user/meshcentral-data/meshcentral-stats.db'^M
^M

**Comment by datapharmer** [comment]
still getting the same error after reinstall:

ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
{ Error: Command failed: /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 6164

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: null,
  signal: 'SIGKILL',
  cmd:
   '/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 6164' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
{ Error: Command failed: /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 6164

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:194:15)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: null,
  signal: 'SIGKILL',
  cmd:
   '/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/node_modules/meshcentral --launch 6164' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

----------------------------------------------------------------------------------------------------------------------------------------

mesherrors.txt:
-------- 12/19/2020, 3:15:48 AM ---- 0.7.28 --------^M
^M
/home/ec2-user/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:118:12)
    at createUnsafeBuffer (buffer.js:112:25)
    at Function.allocUnsafeSlow (buffer.js:302:10)
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:270:29)^M
^M
^M
-------- 12/19/2020, 3:15:57 AM ---- 0.7.28 --------^M
^M
/home/ec2-user/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: ENOENT: no such file or directory, rename '/home/ec2-user/meshcentral-data/meshcentral-stats.db~' -> '/home/ec2-user/meshcentral-data/meshcentral-stats.db'^M
^M

**Comment by PetieM** [comment]
Do you see a file called meshcentral-stats.db~ (with the ~ at the end) in your meshcentral-data folder? If so, try removing the ~, ensuring your meshcentral user can read and write to that file (and the rest in that directory for that matter), and restart the server. Not sure why a tilde would be appended but the error seems to suggest this as the solution.

**Comment by datapharmer** [comment]
Hi Petie, thanks I saw this and checked, but don't see such a file. Here is what my meshcentral-data directory shows: 

$ ls
agentserver-cert-private.key  meshcentral.db~        mpsserver-cert-private.key  webserver-cert-private.key
agentserver-cert-public.crt   meshcentral-events.db  mpsserver-cert-public.crt   webserver-cert-public.crt
config.json                   meshcentral-power.db   root-cert-private.key
letsencrypt-certs             meshcentral-stats.db   root-cert-public.crt
meshcentral.db                mesherrors.txt         serverstate.txt

**Comment by PetieM** [comment]
I do see a meshcentral.db~ in that list. Maybe try renaming that one instead?

**Comment by datapharmer** [comment]
Hi Petie, I'm concerned doing so will wipe out all my agent records or other important config like logins and permissions. Can we confirm that it won't just put things back to a new deployment type state with no users or agents?

**Comment by PetieM** [comment]
I can only confirm with certainty that my own install does not have a tilde after that file so it seems abnormal to me. To be safe though, you can back up the entire folder or better yet, if it’s running in a VM, snapshot first.

**Comment by Ylianst** [comment]
It does look the there has been a database corruption. Note that the following 3 files are not essential and can be removed:

```
meshcentral-events.db
meshcentral-power.db
meshcentral-stats.db
```

If you remove them, you will loose the event, power and device stats data, but once you restart MeshCentral, the files will be re-created again and will start accumulating data once more. Let me know if that works.

If you are familiar with JSON files, you can take a look within the .db files with a JSON parser and fix any issues manually, but probably not worth the effort for any of these 3 files. Let us know if that works.

If you are running a lot of devices and users, I do recommend switching to MongoDB and NeDB is not built to handle a lot of transactions.

**Comment by datapharmer** [comment]
Thanks, only ~60 devices now, but probably should make the move. I see install steps, but is there a migration path or do I need to start fresh?

**Comment by datapharmer** [comment]
Nuking:
meshcentral-events.db
meshcentral-power.db
meshcentral-stats.db
had no effect unfortunately. Databases regenerate and message is essentially the same after reinstalling and restarting

**Comment by Ylianst** [comment]
Oh dear. If you rename meshcentral.db and try, does the server work?

Got MongoDB migration, look at section 8 of the [User's Guide](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.9.pdf). You basically use `--dbexport mydb.json' switch databases on the config.json and do `--dbimport mydb.json' and your done. It will only import the content of "meshcentral.db" so, devices, accounts, device groups.

**Comment by datapharmer** [comment]
Ok, definitely a db issue... switching to mongo got me up instantly, but lost all info obviously.

**Comment by Ylianst** [comment]
If you open your meshcentral.db file that NeDB created, you will see it's just a JSON file. You may be able to fix it up manually.

I do have an alternative if you are starting over with a new DB. You can configure MeshCentral create a few device group each time a device connects to an unknown group and grant that device group rights to a user. So, in the settings section of the config.json add this:

```
"orphanAgentUser": "admin",
```

Replace "admin" with your user account name. When you start the server, you will see a bunch of device groups and device show up in your account. The group names will not be correct, but you can click on each group and rename them correctly. That should get you back online without any agent re-install.

Let me know if that helps.

**Comment by datapharmer** [comment]
ok, so interesting not sure if it was the 7.30 update or the orphanAgentUser entry, but shortly after adding that entry and restarting it died on me again (now running mongo). The mesherror.txt now shows:

-------- 12/20/2020, 2:56:05 AM ---- 0.6.70 --------^M
^M
/home/ec2-user/node_modules/mongodb/lib/utils.js:106
      throw err;
      ^

TypeError: invalid IP address: CloudFlare
    at parseipNotation (/home/ec2-user/node_modules/proxy-addr/index.js:163:11)
    at compileRangeSubnets (/home/ec2-user/node_modules/proxy-addr/index.js:126:23)
    at Function.compile (/home/ec2-user/node_modules/proxy-addr/index.js:112:23)
    at exports.compileTrust (/home/ec2-user/node_modules/express/lib/utils.js:238:20)
    at Function.set (/home/ec2-user/node_modules/express/lib/application.js:372:34)
    at serverStart (/home/ec2-user/node_modules/meshcentral/webserver.js:4597:46)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:262:17
    at /home/ec2-user/node_modules/meshcentral/db.js:1013:115
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:677:5
    at handleCallback (/home/ec2-user/node_modules/mongodb/lib/utils.js:102:55)
    at cursor.close (/home/ec2-user/node_modules/mongodb/lib/cursor.js:838:66)
    at /home/ec2-user/node_modules/mongodb/lib/utils.js:677:5
    at _endSession (/home/ec2-user/node_modules/mongodb/lib/cursor.js:923:9)
    at Cursor._endSession (/home/ec2-user/node_modules/mongodb/lib/core/cursor.js:394:7)
    at cb (/home/ec2-user/node_modules/mongodb/lib/cursor.js:921:12)
    at maybePromise (/home/ec2-user/node_modules/mongodb/lib/utils.js:665:3)^M
^M
^M
-------- 12/20/2020, 2:56:11 AM ---- 0.6.70 --------^M
^M
/home/ec2-user/node_modules/mongodb/lib/utils.js:106
      throw err;

**Comment by datapharmer** [comment]
Ok, I've confirmed this is related to cloudflare. Removing "trustedproxy": "CloudFlare" causes various other problem (unless cloudflare is set to disabled) but doesn't die on me.

**Comment by Ylianst** [comment]
The error log above shows you are using v0.6.70, that version does not support:

```
"trustedproxy": "CloudFlare"
```

...so, this is an error I would have expected.

**Comment by kevinh-csalabs** [comment]
ok looks like npm install pulled down an older stable version instead of 7.3.0. Just reupdated and seems ok so far. Is there a flag I should be setting for latest instead of stable?

**Comment by Ylianst** [comment]
By default, `npm install meshcentral` will pull the latest version. I think you can use `npm install meshcentral@stable` to get the version marked as stable.

By the way, stable is just the version I run on [https://meshcentral.com](https://meshcentral.com) for a while. If nothing goes wrong, I mark that as stable.

**Comment by datapharmer** [comment]
Ok, so orphaned devices seem to be showing up with status "agent is online", but a number of tabs including the desktop tab to  remote control them seems to be missing even after reassigning them to another group.  Is there something that needs to be done to reset the permissions? General, Events, Details and Console are the only tabs that show up for these devices.

**Comment by Ylianst** [comment]
This should not be happening. For agents with missing tab, go in the "Console" tab for that agent and see if you can type "help" and get a response. If not, click the "Agent Action" button and try clearing and setting the default core. MeshAgents have a small JavaScript engine built-in and the server needs to send down the "brains" of the agent (a javascript file) so that the agent can start doing things and have tabs. Not sure why, but your server is not sending out the JavaScript.

**Comment by datapharmer** [comment]
ok help returned a list of commands as expected. just uploading the default core made not difference, but clearing and then uploading the core seems to have returned things to normal. Thanks!

**Comment by Ylianst** [comment]
Oh good. This is quite unusual for this to happen. I see it all the time because we clear and send new cores to agents all the time. I never got a report of someone having to do that. Let me know if you see a pattern.
