### ISSUE TITLE
Agent connected with invalid domain/mesh, holding connection problem

### ISSUE THREAD

**Issue by volkans80** [Ylianst/MeshCentral#2095]
Hello,

Strange things are happening in our meshcenter 0.6.99 installation.

1-Three days ago we changed some group's names and deleted some groups. These changes somehow reverted to their original state. Also some groups are missing.
2-Installed plugin DevTools and EventLog is missing.
3-Some computers custom names reverted to the original computer name.
4-When i start the meshcentral some agents says that "Agent connected with invalid domain/mesh, holding connection..."
5-On the my server general page there are 15 unknown device groups.

I tried to revert from backup but every backup is nearly same. I can't find any backup with our changes.

Thanks,

**Comment by Ylianst** [comment]
What database are you using with your MeshCentral server?

**Comment by volkans80** [comment]
Built in.

**Comment by Ylianst** [comment]
It looks like you had a database corruption. If using MeshCentral with a lot of device or for production use, you should use MongoDB. The built-in NeDB is great for getting started, but it's very basic. There is nothing much I can do just based on your description, I can say that the NeDB databases are just JSON files so you can edit "meshcentral-data/meshcentral.db" with a text editor and fix any issues you find.

Note that in the "meshcentral-data" folder, the only .db file that is important is "meshcentral.db", the other ones you can remove safely and you will loose events, etc but nothing critical.

The "meshcentral-backup" folder should have auto-backups and I imagine you looked at that for a previously working database.

You can look at #2093 for another example of database fail. If you have to start over, use this setting in the setting section of the config.json

```
"orphanAgentUser": "admin"
```

This will auto-create a device group for any device that shows up for a missing device group and assign that device group to user "admin". This is a quick way to recover without having to re-install agents.

Let me know if that helps.

**Comment by volkans80** [comment]
Thank you. I setup a new insallation with 0.7.31. Our device count no more than 25 but this time i setup mongodb.

**Comment by TerAnYu** [comment]
orphanAgentUser - does`nt work, if used LDAP.
```
mongosh
use meshcentral
db.meshcentral.insert( {"_id":"mesh//FgZPxsVElXbZ$2rE$epC9u0fNjgiQjs7lLabJ3MeQdIgj6Uk7vBFJEvEA870Ep1s","type":"mesh","name":"Default2","mtype":2,"desc":"","domain":"","links":{},"creation":946684800000,"creatorid":"","creatorname":"meshadmin"})
```
**FgZPxsVElXbZ$2rE$epC9u0fNjgiQjs7lLabJ3MeQdIgj6Uk7vBFJEvEA870Ep1s** - hash, which is used in the logs/console of the server;
**Default2** - group name;
**946684800000** - unixtime created group;
**meshadmin** - created user this group.

Executed this command, created a group, restarted the server and all the clients that requested it - connected.

**Comment by whlsxl** [comment]
> orphanAgentUser - does`nt work, if used LDAP.

If set `ldapUserBinaryKey`, orphanAgentUser should set ldap user's `ldapUserBinaryKey`. if `ldapUserBinaryKey` is not set, `ldapUserKey` present, orphanAgentUser should set ldap user's `ldapUserKey`.

**Comment by dmikoss** [comment]
I am using LDAP with option: "ldapUserKey": "sAMAccountName".

If I use the name KostenkovDM (mixed case), the option "orphanAgentUser": "KostenkovDM" **does not work**. 
Most likely, this is due to the toLowerCase() function as in the following code:
![image](https://github.com/user-attachments/assets/fef87f12-dd5a-43a0-9427-565df180fc4c)

**Comment by si458** [comment]
@dmikoss do a PR and I will try have a look over weekend and verify everything for u, haven't looked at this issue before?
