### ISSUE TITLE
Cloudflare rocketloader breaks js loading

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2098]
When the rocketloader setting is enabled (allows async js via rewriting) it causes things not to load. This is due to it coming from another domain. The error can be seen in the browser console. Can we whitelist the domain when the cloudflare proxy is set in the config.json?

**Comment by Ylianst** [comment]
I am not sure I understand the problem. Did you try this line in the settings section of the config.json?

```
"trustedproxy": "CloudFlare"
```

This only works on latest versions of MeshCentral and will load the set of CloudFlare proxies IP addresses each time you run the server.

![MC2-CloudFlare](https://user-images.githubusercontent.com/1319013/102924194-f3e16800-4445-11eb-8b44-c99c42eb1a7b.png)

I have no idea if that will fix you issue, but did you use this?

**Comment by datapharmer** [comment]
Yes, why I am asking is if 
"trustedproxy": "CloudFlare"
is present then can we allow cross site scripting from cloudflare’s js domain. 

Currently if you enable “rocket loader” under the “speed” settings in cloudflare it breaks the mesh central site.

**Comment by Ylianst** [comment]
Ok, I will have to try this myself and see what happens. I am not familiar with that option.

**Comment by datapharmer** [comment]
Here is the specific console message you get when it is enabled:

Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

The rendering impact is that there is no login username/password or sso option on the page, just the site title and blue background.

**Comment by Ylianst** [comment]
Ok, I researched this and indeed, a change was needed to the [Content Security Policy header](https://support.cloudflare.com/hc/en-us/articles/216537517-What-is-Content-Security-Policy-CSP-and-how-can-I-use-it-with-Cloudflare-). I made the change to it should work on MeshCentral v0.7.43.

You will need the following set to this to work.

```
"TrustedProxy": "CloudFlare"
```
