### ISSUE TITLE
hide option and power state

### ISSUE THREAD

**Issue by cuhkc** [Ylianst/MeshCentral#2099]
Hello. 

if I use the "hide" option in config.json then the "7 Day Power State" is no longer displayed in the desktop version.
![image](https://user-images.githubusercontent.com/76482930/102906461-b997bb00-4485-11eb-89bb-bbbc46f00e70.png)

![image](https://user-images.githubusercontent.com/76482930/102906570-df24c480-4485-11eb-8770-3352c7f01d7e.png)

In mobile version "7 Day Power State" is displayed normally(with "hide" option).

If I remove the "hide" option (or  "hide": 0)  then the activity is displayed normally in the desktop version.
![image](https://user-images.githubusercontent.com/76482930/102907175-b5b86880-4486-11eb-976f-c2a83a8f7a05.png)

may be a problem with the value of the "hide" option. 1 = Hide header.
if header is not displayed then activity is not displayed.

**Comment by Ylianst** [comment]
Your right. I see the same. That is a bug.

**Comment by Ylianst** [comment]
Ok, fix for this is in GitHub, will be in v0.7.32 when next published.

![image](https://user-images.githubusercontent.com/1319013/102925709-c5b15780-4448-11eb-96ca-80991d39e3aa.png)
