### ISSUE TITLE
Works on Windows CE?

### ISSUE THREAD

**Issue by maurodx** [Ylianst/MeshCentral#21]
I need to find some kind of RDP working on Windows CE and Windows 7. MeshCentral can work with CE and 7 or only standard Windows?

**Comment by Ylianst** [comment]
MeshCentralv2 (this project) currently works on Windows7 and newer and Linux. Currently working on OSX support. I don't think I ever got a request for WinCE support, I expect we will probably not support WinCE. It's a lot of work and would be a very narrow user base.

**Comment by Ylianst** [comment]
Going to close this one. No way we are doing WinCE :)
