### ISSUE TITLE
Assign rights to a group of user

### ISSUE THREAD

**Issue by elric72** [Ylianst/MeshCentral#210]
Hi,

Just a quick question, is there a way to define a group of users and assign rights to this group instead of per user ?

Thank you in advance
David

**Comment by cromra** [comment]
i totally second this request. Being able to assign rights to a user group in a computer group instead of a user, and assign server rights to a user group.

**Comment by Ylianst** [comment]
Agreed. Would be nice. I started adding user groups, but more needs to be done with them.

**Comment by elric72** [comment]
Great good news.
Tell me it will be available.
I will perform some tests.

Thank you for your great job.
Regards 
David

**Comment by sorvani** [comment]
#185 and #256 are related I think.

**Comment by Ylianst** [comment]
Closing this one as user group support was added.
