### ISSUE TITLE
Agent cleanup

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2101]
As a new feature it would be nice to have a fairly automated way to be able to remove old/other agents, such as in the case the ID changes due to agent customization.

**Comment by Ylianst** [comment]
You can select devices, hit "Group Actions" and "Uninstall Agent". Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/102924398-589cc280-4446-11eb-98dc-b4115001631a.png)
