### ISSUE TITLE
Add backup and export from UI

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#2102]
It would be nice to have a ui option that could export and tar the mongo db archive and data files or retrieve the automatic backup if mongo db is already included in this.

**Comment by Ylianst** [comment]
If you are using NeDB there is an option to zip and download the "meshcentral-data" folder in "My Server" tab. If you are using MongoDB, MeshCentral should be creating backups every 24 hours that includes MongoDB dump and put the file in "meshcentral-backups". My recommendation copy the last download from the folder. Let me know if that works.
