### ISSUE TITLE
Separating Ports

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2103]
Hi,

We'd like to limit https web gui access and will be using our firewall to do ip filtering, but if I understand correctly, Meshagent connects on 443 as well. Is there a way to have Meshagent connect to a different port so remote endpoints can connect from anywhere?

**Comment by ryanblenis** [comment]
#1767

**Comment by matt-cylanda** [comment]
Perfect! Thank you

**Comment by matt-cylanda** [comment]
I was following the thread and saw the option for 'userAllowedIp' which would accomplish exactly what we're going for... however we're running MeshCentral in a docker container and it's serving itself behind a reverse proxy.

Everything seems to work fine, but all of the agent IP's are listed as the IP of the NGINX Proxy Manager. When I implemented 'userAllowedIP', it didn't work, I'm assuming my IP is also showing up as the NGINX Proxy Manager's up. 

Is there a line in the NGINX config that would pass the agent and user IPs correctly to the server?

**Comment by matt-cylanda** [comment]
Nevermind, I figured it out, I had 127.0.0.1 set for the TlsOffload address instead of my NGINX instance. It seems to be working properly now
