### ISSUE TITLE
Agent Last Seen doesn't match Device is powered...

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2104]
If Agent was last seen at 9:30 how come MeshCentral knows it was powered on till 12:48, wouldn't that mean that Agent was at least "last seen" at 12:48 ?

![image](https://user-images.githubusercontent.com/5128967/102974848-7d08a580-44ff-11eb-9691-3878e9bbf342.png)

**Comment by dinger1986** [comment]
I think there was maybe some other issue going on here as referenced in the other issue @si458

**Comment by si458** [comment]
plz try updating to latest version, if issue still persists, then please reply/reopen
