### ISSUE TITLE
Unable to view Windows Desktop

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2105]
Hi, I've onboarded a number of systems into MeshCentral, but I have one system that for some reason is not viewable. I'm seeing this when I try to connect 
![image](https://user-images.githubusercontent.com/65490814/103035533-9a437100-450b-11eb-86ed-216815589f64.png)

**Comment by yomono** [comment]
The system is asking you to choose between the console session and the RDP session on the computer. You have to choose one of them

**Comment by matt-cylanda** [comment]
Oh crap! That's kind of awesome... last I checked when I had an RDP user connected to a machine I was only able to view the console. Nice, thanks!
