### ISSUE TITLE
Chase website fields typing incorrect characters

### ISSUE THREAD

**Issue by valnar1** [Ylianst/MeshCentral#2108]
I tested this in Chrome and FF.

If you remote control a PC with the Mesh agent, something funny happens when you try to type in numbers on the Chase Bank web site.  Please test:

Go to www.chase.com.
Click on the "Forgot username/password?" link below the blue Sign in box.  You do not need an account to do this.
Start typing in numbers into the Social security box.  It gives me the letter ç over and over.  If you type on remote computer normally, it works.

![chase-mistake](https://user-images.githubusercontent.com/30323282/103091963-cc180e80-45c3-11eb-86d2-0d20837c8469.jpg)

**Comment by yomono** [comment]
You can try enabling this option:
![image](https://user-images.githubusercontent.com/31445936/103102549-57f95d00-45fb-11eb-99eb-517b925a58dd.png)

**Comment by valnar1** [comment]
OK that works.  Thanks!  A few more questions:
Is there a reason why it doesn't work without that setting?  Everything is US keyboard.
What is the downside of leaving that active for all Mesh clients?
How can I enable it for all Mesh clients?

**Comment by valnar1** [comment]
NM.  I updated one client and they all seemed to have that option now.  Thanks.
