### ISSUE TITLE
MC Router logon and disconnect

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#211]
Hi,
after a couple of successful tests, I have some trouble with MeshCentral router:
It recognize corrected credentials, alerting with red "Invalid username  or password" if I write wrong data, but inserting right user & pass it return to login page immediately, I can see empty routing list for a couple of msec... 
Trying on other machines, behaviour is the same
Thanks
Merlinweb

**Comment by Ylianst** [comment]
That is weird. If you create a dummy account with no devices and try to login to that account, do it work? In "My Server" tab and click "Show server error log", is there any entries? I may need to update MeshCentral Router with a new debug mode and have you run it with debug turned on to see what is going on.

**Comment by merlinweb** [comment]
Hi Ylianst, with a basic dummy account, mesh router  works and open correctly Meshcentral router.
Switching to administrator don't change behaviour, but after assigning a group, dummy user begins to disconnect immediately
No error in server log
Hope this helps
Cheers
Merlinweb

**Comment by Ylianst** [comment]
That helps. I will take a look, thanks.

**Comment by Ylianst** [comment]
Last night I added a "-debug" mode to the MeshCentral Router. Not released yet, but just wanted to say that progress is being made on this. Once release, I will ask you to run it again with -debug so we get a dump of the network traffic to see the exact problem.

**Comment by merlinweb** [comment]
Ok, i am of course available to test it and return feedback, thanks

**Comment by Ylianst** [comment]
I just published MeshCentral v0.3.3-u with a new version of MeshCentral Router that can do UDP routing and has not command line arguments. You can take a look at the new [MeshCentral Router User Guide](info.meshcentral.com/downloads/MeshCentral2/MeshCentral2RouterUserGuide-0.0.1.pdf) for this. I added a "-debug" switch that will dump traffic to a log file. Can you run with -debug, make the problem occur and send the log file back to me? Feel free scrub the file of any private information and email it directly to me if desired. Thanks.

**Comment by merlinweb** [comment]
Hi Ylianst,
sent log to your mailbox, I've only removed server name for security
there is a strange response logged inside:
"Debug-Websocket receive large fragment:" then disconnect

let me know, thanks 

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Thanks. I see the problem clearly. If a 64k or more block of data is sent to MeshCentral Router, it will disconnect. It's this line in the .log file:

`Debug-Websocket receive large fragment: 107427`

I should not have any problem solving this.

**Comment by merlinweb** [comment]
Very good, if you need more test after fixing, let me know

Merlinweb

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.3-v with an updated [MeshCentral Router](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) that should fix this. Give it a try and let me know if it works.

**Comment by merlinweb** [comment]
Great, now work as expected
only one thing,It's not so easy to find machines in combo, due to strange order in "remote devices".
would be amazing if searchable like MC2 (with several machines become hard to find the right one)
just for information, thanks for fix

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Nice. I am going to close this issue, however feel free to open a different issue with a feature request. Please be as specific as possible when opening an new issue. Thanks!
