### ISSUE TITLE
MeshCentral Server Docker Container Crashing

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2110]
Hey all,

I've been loving this project more and more, we recently onboarded some endpoints that somehow automatically added AMT compatibility, so I've started playing around with that a little... good fun.

I've noticed tho in the past week or two the docker instance I have with the server randomly crashes a few times at day. Below is the output from the container:

```
Error: Cannot find module '/home/node/meshcentral/node_modules/meshcentral/meshcentral.js',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Function.Module.runMain (module.js:693:10),
    at startup (bootstrap_node.js:188:16),
    at bootstrap_node.js:609:3,
{ Error: Command failed: /usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7,
module.js:549,
    throw err;,
    ^,
,
Error: Cannot find module '/home/node/meshcentral/node_modules/meshcentral/meshcentral.js',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Function.Module.runMain (module.js:693:10),
    at startup (bootstrap_node.js:188:16),
    at bootstrap_node.js:609:3,
,
    at ChildProcess.exithandler (child_process.js:275:12),
    at emitTwo (events.js:131:20),
    at ChildProcess.emit (events.js:214:7),
    at maybeClose (internal/child_process.js:925:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5),
  killed: false,,
  code: 1,,
  signal: null,,
  cmd: '/usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7' },
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...,
```

Any ideas what this is about? I remember seeing something like this when I first got the container going, there were some permission issues, so I think I did a recursive  chmod 755 or something similar that made it boot properly. 

[mesherrors.txt](https://github.com/Ylianst/MeshCentral/files/5740883/mesherrors.txt)

I'm also including the error log. 

Right now, it seems like the only way to get it back up and running is to clear the container and re-run the composer file I setup.

Oh, and Merry Christmas everyone!

**Comment by ryanblenis** [comment]
Your mesherrors.txt shows that the files it is looking for don't exist. 

![image](https://user-images.githubusercontent.com/1929277/103114690-a58ebd80-462d-11eb-8699-537159735c91.png)

If you're running this in docker, you'll want to be mapping the meshcentral-data folders either to a folder on the host, or persistent volume in docker. The node-modules folder (or at least the required dependencies, including meshcentral) also doesn't appear to exist in full, so it sounds like whatever container you're using isn't set up to have that folder available, or isn't running 'npm install' prior to running. Is there a certain container you're using, or are you rolling your own?

Merry Christmas!

**Comment by matt-cylanda** [comment]
I've gotten pretty good at getting docker containers up and running. From what I can tell, everything is mapped correctly and the server runs for hours at a time without issue, and then all of a sudden it's as if it forgets where everything is and can't find it's needed files. The below is my compose file. I replaced/remapped a few graphic files to customize the interface a little, but initially it didn't seem to be causing any issues.

`
version: '3.5'

services:

  MeshCentral:
    image: uldiseihenbergs/meshcentral
    container_name: MeshCentral
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
    - /opt/MeshCentral/files/:/home/node/meshcentral/meshcentral-files
    - /opt/MeshCentral/data/:/home/node/meshcentral/meshcentral-data
    - /opt/MeshCentral/backup/:/home/node/meshcentral/meshcentral-backup
    #- /opt/MeshCentral/data/images/white-logo.png:/home/node/meshcentral/node_modules/meshcentral/public/logo.png:ro
    - /opt/MeshCentral/data/images/new-icons.png:/home/node/meshcentral/node_modules/meshcentral/public/images/leftbar-64.png:ro
    - /opt/MeshCentral/data/images/favicon.ico:/home/node/meshcentral/node_modules/meshcentral/public/favicon.ico:ro
    networks:
      Network-Bridge:
        ipv4_address: 172.0.0.150

networks:
  Network-Bridge:
    driver: bridge
    name: Network-Bridge
    ipam:
     config:
       - subnet: 172.0.0.0/16
`

**Comment by matt-cylanda** [comment]
After I recreate the container, this is the status of the server I'm seeing

```
Installing archiver@4.0.2...,
Installing otplib@10.2.3...,
MeshCentral HTTP redirection server running on port 80.,
MeshCentral v0.7.30, WAN mode.,
Loaded web certificate from "https://remote.cylanda.com", host: "remote.cylanda.com",
  SHA384 cert hash: 159db52168a79fc72df6424a48e611b9536ed8d1e0d9efa823f57e1f30f093c3052226ad40855466c8a19fca9cffb2b1,
  SHA384 key hash: 482d01d1fcff1699c0fa42ca9cf81d60c0a980ee024547e1f68b0a289cc3be5b5883f5127d929cb2629d2510a16478dd,
MeshCentral Intel(R) AMT server running on remote.cylanda.com:4433.,
MeshCentral HTTP server running on port 443.,
```

As far as I can tell, it all looks normal and configured correctly.

**Comment by ryanblenis** [comment]
Any chance your host OS running Docker is MacOS? I do remember having some issues with nested containers on MacOS with Docker (which is a Docker issue, not a MeshCentral one).

**Comment by matt-cylanda** [comment]
Unfortunately no, I’m pretty sure it’s Ubuntu Server 18.04

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanblenis** [comment]
Apologies, I saw your docker-compose file and deleted my previous comment presuming the /opt path wasn't being used on macOS for the host system. Figured I'd add it back here for the sanity of the thread.

The previous comment asked if the host OS was macOS, as I (and others) have had issues with nested containers having their directories and contents "disappear" within the container until a restart had occurred.

I'm not sure if this is the case across other versions of docker. When it does happen next, can you `docker exec -ti [container_id] /bin/bash` (or sh, whatever shell is available in your container) and verify that the files exist when the errors occur. (It may also be helpful to do this prior to the failure so you know what differences you're looking for)

**Comment by uldiseihenbergs** [comment]
@matt-cylanda rhanks for using my container :)
Does your /opt folder reside on same harddisk as Ubuntu installed, or is it mounted as separate volume?

**Comment by matt-cylanda** [comment]
Hi, Merry Christmas! Thank you for making this container... some day I’m going to have to learn this magic of container making.

The opt folder resides on the same drive in this Ubuntu install, and is running as a VM. I’ll have to double check if I made a swap partition, I’m pretty sure I did... not sure if that would make a difference here.

@ryanblenis when I have a chance, I’ll have to log into the container and take a look. Would the container still boot if the files weren’t present? They show in the GUI when I’m logged in... although it could be cached

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanblenis** [comment]
> Would the container still boot if the files weren’t present?
Yes, it's a mini-OS, you're really just mounting directories in certain locations within in and it's set to run a few commands automatically within a predefined environment

> They show in the GUI when I’m logged in
Which gui? The host OS? What we're trying to see here is if the container no longer has the correct mounts, so while they will still exist on the host OS, I believe they may be "disappearing" from the container OS.

**Comment by techno-express** [comment]
> Error: Cannot find module '/home/node/meshcentral/node_modules/meshcentral/meshcentral.js'

Why is it being loading from `node_modules` at second level? How is it being launched or how is the container launching it? 
The loading from should show `/home/node/meshcentral/meshcentral.js`
The startup directory should be `/home/node/meshcentral`. 
Only dependencies should be shown coming from `/node_modules/` sub folders.

**Comment by uldiseihenbergs** [comment]
that's not true. all meshcentral executable's are under /home/node/meshcentral/node_modules/meshcentral/*
/home/node/meshcentral is a root directory where you have subfolders:
- meshcentral-data for config files only
- meshcentral-backups for backups
- meshcentral-files for user files
- meshcentral-web for web pages overrides
all above 4 folders should be mapped as volumes in docker to save data in them after container restart/rebuild. if some volume is missing, meshcentral will continue to work, files will be created inside docker image and will be lost after docker image rebuild. 
/home/node/meshcentral/node_modules should not map to docker volume and will be created in container image, and that's fine - it will be recreated when you rebuild your docker with new version.

**Comment by techno-express** [comment]
No, you have a bad build. The only thing needing mapping is the data folders. **node_modules** directory is created on **npm install** if any dependencies are not there and folder is missing. 

You need to read up on how Node handle package installs, and docker volume mapping. No need to map that folder. You should not be touching **node_modules**, the reason for the error. Once you map any volume any updates to that part need to be updated within application running, so whatever the user did, **deleted it**. 

I created docker build around the time this project was started, https://hub.docker.com/r/technoexpress/meshcentral2 and https://hub.docker.com/r/technoexpress/meshcentral. One is for my fork.

**Comment by uldiseihenbergs** [comment]
your build is fine, mine too. please read carefully, no word from me to map node_modules folder or any subfolders inside.

**Comment by techno-express** [comment]
ok, i miss read. i never looked at your build, i was going by his compose file posted that has `node_modules` included. 
i see now your build do create the folder.

**Comment by matt-cylanda** [comment]
Wow, this thread got active. The only reason I mapped items from the `node_modules` directory was for theming/branding purposes. I've deployed this as a remote management portal with multi-tenant ability... MeshCentral so far has been great for this, but I needed the interface to look a bit more user friendly and branded with our company info.

As far as I could tell, mapping the `node_module` graphics didn't seem to have a negative impact, but is it possible that when the container updates itself, the mapping somehow breaks the ability for the directory to regenerate?

Sorry if I'm not properly addressing how containers work, I know how to deploy and configure them, but not 100% clear on how they operate internally.

**Comment by techno-express** [comment]
It's internal, once you mount a volume, only on the initial/first docker run stuff get copy to mount point and only if not initially present. 

Things afterwards like docker shutdowns restarts or build updates from the outside of the built application don't get touch. 

So if you happened to delete something from within that mount point and think build image updates would put it back, not going to happen. You would need to ssh into or mount volume point another way, to make changes.

**Comment by uldiseihenbergs** [comment]
@matt-cylanda if you need to modify web page, just map meshcentral-web volume. for example, i use this to fine-tune style.css. to do this, under meshcentral-web create folders public/styles, and copy original style.css inside. every time container starts, it should take style.css from there.
ok, i know, this is not a best approach to modify this file cos you wont receive any updates when a meshcentral version changes.. if anyone have better idea how to do it, just let me now.

**Comment by matt-cylanda** [comment]
Thank you @uldiseihenbergs, I was wondering how that map worked. Is the mapped web directory accessible via the web portal? if I put an images folder within the map with alternative images I'd like to theme with, what would the url be?

**Comment by uldiseihenbergs** [comment]
these files won't be accessible from web portal. any more details are beyond my knowledge. @Ylianst , can you please comment here about meshcentral-web loading?

**Comment by matt-cylanda** [comment]
Ahh! I think I figured it out... anything added to the public folder under the web map is replaced or added to the existing files shared within the public directory. I think I'm now able to replace image files without needing to alter the css file.

**Comment by uldiseihenbergs** [comment]
and yes, you can always look at meshcentral.js file, where all this magic happens :) just search for "meshcentral-web".

**Comment by matt-cylanda** [comment]
So far since mapping the web directory and replacing images that way our server hasn't crashed. Thanks everyone for the help
