### ISSUE TITLE
Migration from NeDB to MongoDB results in admin access issues

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2114]
I first reported this in issue #2062 but not sure if that original issue is still active (I've added to it but there has been no follow up). 

I'm running MeshCentral on Windows Server 2019.  I'm trying to move from the default NeDB to MongoDB.  I am able to perform the database export from NeDB and then do the MongoDB import.  MeshCentral loads and recognizes my account (as it will let me log in after importing the database).  But I then have no access to my devices.  Looking at the settings I can tell my account (which is the only account on the MeshCentral server) no longer has Administrator access.  Looking at the account under 'My Users' it does show as 'Administrator' under Permission but that account actually doesn't have admin access.  

So something seems to be happening somewhere between the database export from NeDB and the import to Mongo. 
That said, if I create a new device group I do end up having full access to the new device group.  But not to any of the pre-existing device groups nor any of the other system settings that require administrator permissions. 

Issue #2062 has more details about what I'm seeing. 

Also, I apologize for posting this as a new issue.  I fear my previous report has just been lost in the mix.

**Comment by Ylianst** [comment]
No worries. Thanks for posting again. I am back at work tomorrow and will take a look at this.

**Comment by Ylianst** [comment]
So, I think the problem turned out to be because of #2127 which is now fixed in MeshCentral v0.7.35. If you can update and migrate again, it should work now. Let me know if you have any issues.

**Comment by PathfinderNetworks** [comment]
I will try again over the holiday.  But I think I want/need to resolve the node_modules issue (mentioned in #2131) before I try migrating to Mongo again.  

Thanks!

**Comment by Ylianst** [comment]
Agreed, getting your server properly updated is the first step.

**Comment by PathfinderNetworks** [comment]
I finally have this fully resolved. First I had to resolve the issues with getting my existing MeshCentral install using a clean structure for node_modules (which I did via issue #2131 ).

Once I got MeshCentral running 'clean' I was then able to export the NeDB and import it in to MongoDB without issue.  
I'm now up and running under MongoDB. 

Thanks!

**Comment by Ylianst** [comment]
FYI. Starting with MeshCentral v0.7.40 that will be published soon, you can do this:

```
node node_modules/meshcentral --nedbtodb
```

This will transfer the entire NeDB database to the currently setup database. So, stop the server, setup MongoDB and run this to transfer everything.

**Comment by PathfinderNetworks** [comment]
That will definitely make things easier for others that will want to do this. Thanks!

**Comment by drnikcuk** [comment]
> setup MongoDB

Do you mean, update the config file with the related mongodb settings?
