### ISSUE TITLE
Native language switching

### ISSUE THREAD

**Issue by lingf1302** [Ylianst/MeshCentral#2116]
Hi,When I downloaded the Project on GitHub, I downloaded the MeshCentral project directly. After executing Node MeshCentral, the Language option was not seen in the localization option.Are there any other configurations required for language switching?

**Comment by Ylianst** [comment]
The version in GitHub does not include the translated web pages, but you can go in the /translate document and run "translate.bat" (or make the same script in Linux) and generate the translated pages. Once generated, the language switching option will show up on the web page.

Let me know if that helps,
Ylian
