### ISSUE TITLE
Intel AMT connect button not available

### ISSUE THREAD

**Issue by Scaff31** [Ylianst/MeshCentral#2117]
Hello,

I just need little help for understand how work Intel AMT.

![image](https://user-images.githubusercontent.com/16442430/103287274-6a500e00-49e2-11eb-8d40-0eee880e72dc.png)

What I show on agent console with "amtevent"

14:24:40, Checking Intel AMT state...
14:24:44, Intel AMT connected.
14:24:52, Done.
14:24:52, LMS tunnel closed.
14:25:13, LMS tunnel start.
14:25:14, Checking Intel AMT state...
14:25:18, Intel AMT connected.
14:25:24, Done.
14:25:24, LMS tunnel closed.
14:26:17, LMS tunnel start.
14:26:20, Checking Intel AMT state...
14:26:29, Intel AMT connected.

![image](https://user-images.githubusercontent.com/16442430/103287885-eac33e80-49e3-11eb-80ee-f56083f97ec2.png)

![image](https://user-images.githubusercontent.com/16442430/103287180-1fce9180-49e2-11eb-8c3d-f6695d7cb7a4.png)

I'm not able to use INTEL AMT with MeshCentral2

I use automatic config from group or CCM + CIRA result was same can't use connect button

![image](https://user-images.githubusercontent.com/16442430/103287431-cf0b6880-49e2-11eb-8c96-f3f35bfa40e4.png)

![image](https://user-images.githubusercontent.com/16442430/103287349-98cde900-49e2-11eb-8455-ece58edcff87.png)

Thank you all

**Comment by Scaff31** [comment]
Update 03/03/2021

![image](https://user-images.githubusercontent.com/16442430/109815636-25d62e00-7c30-11eb-81b8-5d2956c70fb2.png)

![image](https://user-images.githubusercontent.com/16442430/109818163-fd036800-7c32-11eb-861e-6623ad7e49ee.png)

If someone has and idea

**Comment by si458** [comment]
closing as stale, please update to the latest version 1.1.20 which has a few AMT fixes, and make sure to use node 18 or above,
if your issue still happens, plz reply
