### ISSUE TITLE
Larger image for the "mainwelcome.jpg"

### ISSUE THREAD

**Issue by jslync19** [Ylianst/MeshCentral#2119]
Appreciate you could share, where can we modify the allocated space size so that I could upload a larger image for the "mainwelcome.jpg"

**Comment by yomono** [comment]
I don't know if this anwer your question, but as you can see in the example configuration here:
https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json

You can select your own image using this option under "domains" section:
 "welcomePicture": "mainwelcome.jpg"

I actually did some test for myself and it didn't seem to have any size limitation.
Still, if your image is too heavy, it would be a good practice to reduce the size.

**Comment by Ylianst** [comment]
@yomono  Thanks for responding. I was going to answer this same.

**Comment by jslync19** [comment]
Thanks for your suggestion. I managed to find the way to change the height & width under #welcome image img section in ~/node_modules/meshcentral/public/styles/ style.css. Thereafter, you will be able to upload a larger image then...

**Comment by Ylianst** [comment]
Note that is you make a change to ~/node_modules/meshcentral/public/styles/style.css, the change will be reversed the next time you update the server. An alternative way is to create a folder called "meshcentral-web" next to "meshcentral-data". Then, create a "public" folder in it. Then a "styles" folder in the public folder and put your modified "styles.css" in that folder. So,

~/meshcentral-web/public/styles/styles.css

Once you restart the server you will see the MeshCentral will take any file from the "meshcentral-web" folder ahead of the default files. Now, you can update the server and your changes will not be lost.

Hope that makes sense,
Ylian
