### ISSUE TITLE
Enhancement : Monitor capability

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#212]
I have a remote technician working on my Ubuntu headless Linux system at the moment. It would be ***really*** cool if I could use MC to watch what he's doing as he's doing it ... you know, just so that I'm assured he's not getting up to anything nefarious...

I don't have a ton of Windows systems under MC at the moment, but the same would be true of them too...

**Comment by Ylianst** [comment]
Hi. So, I would like the issues to be a bit more specific, otherwise they can't ever be closed :). You would like to capture all ssh/shell sessions going on a system? Is there no other software that can do that?

**Comment by Ylianst** [comment]
After considering this a bit... This request to too much outside the scope of MeshCentral right now. If there is monitoring software like this, I am sure you could use MeshCentral to remotely use it. I am not sure how we would go about doing this anyway, even if I did know, probably not something we would do.
