### ISSUE TITLE
MeshCentral.com just got updated to v0.7.33

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#2120]
Just a notice that [https://meshcentral.com](https://meshcentral.com) was just updated to v0.7.33 and now has a new front page. The server will now be both the free community management site and the MeshCentral promotional site. It makes a lot more sense then going to [https://meshcommander.com](https://meshcommander.com) to get information about MeshCentral. If there is any feedback on this, please let me know.

![MC2-Frontpage1](https://user-images.githubusercontent.com/1319013/103329899-d860f900-4a13-11eb-8a31-a6b86a2dec11.png)

Note that people with accounts on MeshCentral.com just need to click the "Public Server Login" button on the upper right and everything should work just like before. Except for being the latest version and having the new front page, nothing should have changed much.

**Comment by petervanv** [comment]
your certificate on https://meshcommander.com has expired / points to another server.
![image](https://user-images.githubusercontent.com/58996467/103348441-4ea83e80-4a9a-11eb-8a51-393d074a6f9c.png)

**Comment by yomono** [comment]
This is without a doubt the most actively maintained project I've ever seen. Congrats!

**Comment by 1001crew** [comment]
Thanks for the great work you are doing and Congrats for every new step forward

**Comment by GRIFFCOMMca** [comment]
This version also has a new feature of not being able to connect to any existing desktops remotely....  opened a ticket here (also did it last night to the wrong github)

https://github.com/Ylianst/MeshCentral/issues/2128

**Comment by yomono** [comment]
> This version also has a new feature of not being able to connect to any existing desktops remotely.... opened a ticket here (also did it last night to the wrong github)
> 
> #2128

The sarcasm was unnecessary

**Comment by Ylianst** [comment]
@petervanv the [https://meshcommander.com](https://meshcommander.com) is hosted by Google sites. It seems Google is having a problem, but https://meshcommander.com should redirect to https://www.meshcommander.com anyway. So try [https://www.meshcommander.com](https://www.meshcommander.com) for now. If not fixed later today, I may have to investigate.

**Comment by Ylianst** [comment]
Thanks everyone. I will close this. Nice to have success, but now flooded with tickets :)
