### ISSUE TITLE
single agent not connecting anymore, but still sends requests to /agent.ashx

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2121]
Any idea how I can troubleshoot a single agent not connecting anymore. I can still see the agent.ashx requests in the reverse proxy log but in the "online" overview the agent is not present anymore. My 20+ other agents have no issues.

![image](https://user-images.githubusercontent.com/5128967/103337003-2c9ec400-4a7a-11eb-9973-fd79bced8b60.png)

![image](https://user-images.githubusercontent.com/5128967/103337052-4c35ec80-4a7a-11eb-84a0-b3af52691ac0.png)

I already changed the "IgnoreAgentHashCheck" to true a couple of days ago, still nothing. Anything else I can do before I have to physically move to that device ?

**Comment by Ylianst** [comment]
Can you go in the "MyServer" / "Console" tab and type "agentstats", you should see something like this:

![image](https://user-images.githubusercontent.com/1319013/103387637-a5714080-4ab9-11eb-863b-8521a15a2c1e.png)

Report back what you see. It hopefully should give you an idea what it going on.

**Comment by vtacquet** [comment]
> agentstats
createMeshAgentCount: 26
agentClose: 10
agentBinaryUpdate: 0
coreIsStableCount: 24
verifiedAgentConnectionCount: 25
clearingCoreCount: 0
updatingCoreCount: 0
recoveryCoreIsStableCount: 0
meshDoesNotExistCount: 0
invalidPkcsSignatureCount: 0
invalidRsaSignatureCount: 0
invalidJsonCount: 0
unknownAgentActionCount: 0
agentBadWebCertHashCount: 0
agentBadSignature1Count: 0
agentBadSignature2Count: 0
agentMaxSessionHoldCount: 0
invalidDomainMeshCount: 0
invalidMeshTypeCount: 0
invalidDomainMesh2Count: 0
invalidMeshType2Count: 0
duplicateAgentCount: 1
maxDomainDevicesReached: 0

**Comment by Ylianst** [comment]
Ok. Everything looks good. Looking at the timing, it looks like the agent is reconnecting every few hours. One possible pause is that this agent is behind a HTTP Proxy or NAT router that is dropping the connection if it's idle for a long time

In the settings section of the config.json add this:

```
"AgentPong": 300
```

It will cause the server to send data to all agents every 5 minutes (300 seconds). This could cause the agent to stay connected.

Do you know if the agent stays connected for a while? Or tries and disconnects immediately? Or never connects at all?

**Comment by vtacquet** [comment]
That is already there.

    "BrowserPing": 60,
    "BrowserPong": 60,
    "AgentPong": 300,

And the agent is just a regular user desktop (with a home router - like some of the other agents). Server side there is a Caddy reverse proxy (handling the LetsEncrypt certificates).

**Comment by vtacquet** [comment]
It never connected since 22/12/2020, 10:40:24.
It is the same agent as ticket [https://github.com/Ylianst/MeshCentral/issues/2104](url)

**Comment by LPJon** [comment]
> 
> 
> Any ideas before I have to drive over ?

Does your MeshCentral Server have more that one upstream reverse proxy (I mean more than the 1 proxy covered in the documentation). I have no idea if you have an alternate remote option but I would reset the agent by renaming the .msh and .db files to .msh.bak and .db.bak and then restarting the agent service. (Note: this will create another device listing in the device mesh/group that agent was downloaded for). Generally this has fixed this type of issue in the past for me. 

To be clear: In MeshCentral, your agent is actually showing as disconnected right? (It's greyed out). If the agent is actually connected but you don't have access to the tabs Desktop, Terminal, Files, etc. then this could be a different issue.

**Comment by vtacquet** [comment]
> Does your MeshCentral Server have more that one upstream reverse proxy (I mean more than the 1 proxy covered in the documentation). I have no idea if you have an alternate remote option but I would reset the agent by renaming the .msh and .db files to .msh.bak and .db.bak and then restarting the agent service. (Note: this will create another device listing in the device mesh/group that agent was downloaded for). Generally this has fixed this type of issue in the past for me.

No only 1 proxy and all other agents are fine. Well I have no other means of connecting except driving over there, so that is my last resort.

> To be clear: In MeshCentral, your agent is actually showing as disconnected right? (It's greyed out). If the agent is actually connected but you don't have access to the tabs Desktop, Terminal, Files, etc. then this could be a different issue.

Correct, it is not "active" but I still see the /agent.ashx requests coming in the proxy log. So that is why I don't understand it doesn't go further...

**Comment by LPJon** [comment]
Have you tried to run a trace from the MeshCentral web interface? Are you using NginX for the proxy? Does the stream look like this:

`Client-->[ Reverse Proxy(example.domain.com)/Reverse Proxy(domain.com)-->Back-End(MeshCentral ]`

So in the example above, the reverse proxy is on the same server as MeshCentral. Is that what you have or is your Reverse Proxy on a separate server like this?:

`Client-->[ Reverse Proxy(example.domain.com)/Reverse Proxy(domain.com) ]-->[ Back-End(MeshCentral ]`

Generally, I've only seen proxy entries like that when either a proper proxy is missing or when the agent is trying to authenticate to MeshCentral for a device mesh/group that no longer exists. 

Please note that you are going to see agent.ashx requests if you have other agents connecting to the MeshCentral server. 

Judging by all the information supplied so far, it really looks like the agent needs corrected/re-installed. This honestly looks like an agent authentication issue so far because you have other active working agents. It could also be related to Windows or Anti-Virus issues where they are interfering with the operation of the agent.

Unless you have alternate access to the machine, physically being there may be the only way to fix it. We usually deploy at least two ways for connection just for this reason. However, the secondary is usually shut off at a firewall unless it's needed.

Am I helping or repeating what you already know?

**Comment by vtacquet** [comment]
> Have you tried to run a trace from the MeshCentral web interface? Are you using NginX for the proxy? Does the stream look like this:

it's a caddy reverse proxy and the agent.ashx page gets served and the client doesn't reply anymore... so not much to debug

> Generally, I've only seen proxy entries like that when either a proper proxy is missing or when the agent is trying to authenticate to MeshCentral for a device mesh/group that no longer exists.

the group still exists, the agent is still in the group (but is gray) - together with other 'live' agents for the same company

> Judging by all the information supplied so far, it really looks like the agent needs corrected/re-installed. This honestly looks like an agent authentication issue so far because you have other active working agents. It could also be related to Windows or Anti-Virus issues where they are interfering with the operation of the agent.

only this agent for all my Windows customers ? I doubt it

> Unless you have alternate access to the machine, physically being there may be the only way to fix it. We usually deploy at least two ways for connection just for this reason. However, the secondary is usually shut off at a firewall unless it's needed.

yeah I had two ways before but I thought that was too much of a hassle and an extra security issue so I closed it.

> Am I helping or repeating what you already know?

no, all help is good, but I think it's time to heat up my car and drive there, I have no more tricks, problem is that I don't want it to happen again, I need a stable solution.

**Comment by LPJon** [comment]
Has it happened before? If not, I would say the likelihood of it happening again are remote....lol....pun intended.

**Comment by vtacquet** [comment]
I reinstalled the agent on site.
