### ISSUE TITLE
Desktop connect result in loop

### ISSUE THREAD

**Issue by dtphap** [Ylianst/MeshCentral#2122]
I installed a mesh agent on my laptop to make it a device in Mesh Central. My laptop has also external screen attached. When I connected to device to see desktop then it result in a loop of many screens, each located inside previous.
My laptop currently has Ubuntu LTS 18.05 as OS.
Please help to fix.

**Comment by krayon007** [comment]
When you connect to your device, where are you connecting from? Are you doing it from a browser on the same laptop?

**Comment by Ylianst** [comment]
If you see something like this:

![image](https://user-images.githubusercontent.com/1319013/103387835-cc7c4200-4aba-11eb-9d48-1e7cb8dcacc2.png)

This is perfectly normal. You are taking control of your own device and so, your watching yourself watching yourself to infinity.

If this is not the problem your having, post a screenshot. Thanks.
