### ISSUE TITLE
ignoreagenthashcheck:true for certain IPs only

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2125]
May I request please an option for "ignoreagenthashcheck":true for certain IP addresses only?
I know that in config.json there are options for Allowed IP and Blocked IP addresses, but looks like it is not something that will help to resolve my issue #1536
With option "ignoreagenthashcheck":true for dedicated IP addresses I would not expose my server to all WAN, just for certain IPs.
Please advise if that can be done.
Thanks.

**Comment by Ylianst** [comment]
Yes, I can add that. Working on it now.

**Comment by Ylianst** [comment]
Ok, check it in GitHub. Starting with MeshCentral v0.7.34, you can now specify IP's and IP ranges as the value for ignoreagenthashcheck. For example any of these would be ok:

```
"ignoreagenthashcheck": true
"ignoreagenthashcheck": "192.168.2.100"
"ignoreagenthashcheck": "192.168.2.0/24"
"ignoreagenthashcheck": "192.168.2.0/24,192.168.1.100"
"ignoreagenthashcheck": [ "192.168.2.0/24", "192.168.1.100" ]
```

Try that after MeshCentral is next published and let me know if it works.

**Comment by Ylianst** [comment]
MeshCentral v0.7.34 now published. Let me know if it works.

**Comment by vitko-bg** [comment]
Updated to 0.7.36 - unfortunately it does not work, tried 

"ignoreagenthashcheck": "86.134.X.X,149.11.X.X" - does not work, still error "Agent connected with bad signature, holding connection (149.11.X.X:41353)

"ignoreagenthashcheck": [ "192.168.2.0/24", "192.168.1.100" ] - also does not work - does not work, still error "Agent connected with bad signature, holding connection (149.11.X.X:41353)

with "ignoreagenthashcheck": true - all work for agents with bad signatures, but all server is exposed to all WEB.

I am using Linux agents for this purpose - as mentioned above to try to find a workaround on #1536

**Comment by Ylianst** [comment]
Your right. I have one more place I need to change to make this work. Will be in the next version v0.7.37.

**Comment by Ylianst** [comment]
Fixed it. v0.7.37 is out, let me know if it works. You also get the last feature of 2020 :)

**Comment by vitko-bg** [comment]
Thanks for the last feature in 2020!!! :)
In 0.7.37 all is working as expected - now I have a workaround for my Linux agents with bad signatures!!!!!
Thanks again for all hard work!
Best wishes in New 2021!
