### ISSUE TITLE
Issues when using Type button with duplicated characters

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#2126]
When uses Type button at Desktop tab, it doesn´t matter the browser, for windows logon or powershell, if you uses any duplicated character, it´s sent or taken just one, ie: used type to send "p@**ss**word" and it´s sent to de device "p@**s**word", for other apps such as notepad or word, it´s working fine, the issue is only happening for windows logon or powershell, generating issue when users try to type their passwords.

**Comment by OutbackMatt** [comment]
Also an issue when typing a url into a web browser

Makes https://www.example.com into htps://w.example.com

#2035
#2078
#2039

**Comment by kevinh-csalabs** [comment]
I'm experiencing this issue as well, and it is reproducible across the windows computers I've tested it on. It may be a windows issue, but slowing the typing speed slightly may be the easiest fix.

**Comment by tiikej** [comment]
I have this same problem.
It is very useful tool when we must type a password in windows system. We use this very often. Could you repair it ?

**Comment by MC-PM** [comment]
this get solved 1 month ago... thanks!
