### ISSUE TITLE
Feature Request: UDP support in MeshCentral Router

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#213]
I'm sadly not well-versed enough on the differences between UDP and TCP to know if this is technically possible, but MeshCentral has been absolutely amazing for me when it comes to remote access. However, there is one last thing preventing it from being my one-size-fits-all remote administration tool.

In my line of work, the Bacnet/IP protocol is king, and it only works over UDP. Currently, we have to set up a messy OpenVPN server and do some BBMD table mapping to be able to route Bacnet/IP traffic across a remote connection. It takes a long while to set up, and ideally everything has to be put back the way it was before I disconnect.

I find MeshCentral Router to be incredibly powerful and user-friendly. It would be amazing to be able to route UDP traffic as well so I could access Bacnet/IP devices through it!

**Comment by Ylianst** [comment]
Ok, will look at feasibility...

**Comment by MatinatorX** [comment]
Thank you very much, and let me know if I can help in any way!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.3-u with UDP routing support. You will need to update the server and MeshCentral Router and give it a try. I also published a new [MeshCentral Router User Guide](info.meshcentral.com/downloads/MeshCentral2/MeshCentral2RouterUserGuide-0.0.1.pdf). The guide has instructions for new command line arguments to help with login and creating port maps. Feedback appreciated.

**Comment by MatinatorX** [comment]
Wow, that was quick, thanks! I updated the server and my router binaries accordingly, and have been playing around with it for about two hours now. The command line options in particular work great and should come in very handy.

Unfortunately, I've not met with success with USP port mapping, but I'm fairly certain the issue is with the limitations of my UDP software and not with MeshCentral Router itself. The software I'm trying to route traffic to (Cimetrics BACstac Gateway, if you're curious) does not have the option to specify a UDP port only; rather, you must specify the port along with the NIC that you expect the UDP traffic on. I suspect the software only looks at traffic accessible by that NIC. I plan to have a chat with the Cimetrics team about this sometime tomorrow to find out for sure.

I did a quick test to see if the ports MeshCentral Router maps are accessible through the local computer's NICs, and my conclusion was that they are not. I mapped a simple HTTP port to my local computer, then confirmed I could access the webpage locally with the newly mapped port. I then tried to access this webpage through another local computer on the same private network, using the IP address and mapped port of the first local computer. The webpage would not load. The test was run with firewalls disabled and both local machines were able to ping each other.

While I'm not yet sure it would solve my specific problem, there may be times when a user would like to have the locally mapped ports accessible to other users on the local network. Would it be possible to have the option to expose these ports to NICs, or would that just be extremely complicated?

Lastly, I would very much like to donate beer and pizza for all your hard work! Do you happen to have a Paypal/donation link set up anywhere?

**Comment by Ylianst** [comment]
Thanks for the testing. No need for donations. You are correct that local port mappings right now and only for "localhost". I will add a new switch to bind to "INADDR_ANY" which will let other computers on the network access ports that are mapped by MeshCentral Router. Note that if your UDP app requires multicast to find devices on the network, that will not work with MeshCentral Router.

Let me make that added any interface switch improvement tomorrow and publish a new version.

**Comment by MatinatorX** [comment]
Of course! If you ever change your mind about the donations (or need commercial HVAC advice for any reason) let me know.

I think the above would be all I need to get things working. Once I have a UDP pipe to it, the hardware BACnet router I'm connecting to will handle multi-endpoint traffic for me. From the spec: "Note that networks accessed through a given active UDP port that are not directly connected, but are reachable by means of communication with another B/IP router shall, upon router startup, be deemed to be reachable." Even if that doesn't work, we also have the option to eschew multicast completely and instead assign a BBMD (BACnet/IP Broadcast Management Device) and map endpoints to it.

Anyways, thanks for all the hard work! Will you be allowing us to set the "INADDR_ANY" binding for mappings via the command line?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.3-v with an updated [MeshCentral Router](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) that accepts "-all". I also did a silent update of the [MeshCentral Router User's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2RouterUserGuide-0.0.1.pdf). You will see the new switch at the end of section 6.

One more thing: I have [UdpTester.exe here](http://info.meshcentral.com/downloads/MeshCentral2/UdpTester.exe) for testing. It's a small Windows C# built tool that sends and received UDP packets. I used to for my own testing. You welcome to try it.

**Comment by MatinatorX** [comment]
Thanks for all the help!

Unfortunately, after playing around with it for a whole day and night, I was not successful in routing any BACnet traffic over UDP. I tested the UDP routing with your tool as well as the -all command and they worked as expected, so it must be that Cimetrics requires multicast or some other complicated networking wizardry to function. I was really hoping it would work, since the BACnet spec doesn't mention multicast, and running a netstat on Cimetrics revealed it was only listening to UDP: 47808 on my LAN adapter interface. I even tried mapping the port to another computer on my local LAN to see if it could act as a relay of sorts, but no dice. If you have any ideas, I'd be happy to try them.

In any case, MeshCentral and MeshCentral Router are still great tools that will go a long way towards making my life easier. I'll just have to put up with OpenVPN when I need to route any BACnet traffic!

**Comment by Ylianst** [comment]
Arg. Probably not possible to solve this unless we know the details of how the application works. Even then, it may not work as the first UDP packet must come from the MeshCentral Router side and you can't have more than one IP:Port communicating with MeshCentral Router at any given time... and multicast does not work. I think you would need a proxy service that is specialized for your application. I am going to close this one, but please re-open if new data is available.
