### ISSUE TITLE
update unknown?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#2130]
Hi,
Currently wanted to see if there was an update but i get this issue 
![image](https://user-images.githubusercontent.com/13953629/103393072-cacc7180-4aee-11eb-9ce2-0eac28ab7dc7.png)

Thank you

**Comment by Ylianst** [comment]
Hi. This often happens because MeshCentral can't find "npm" in your system. MeshCentral uses this command to query for the current version and to perform the update. I have the same problem on my servers and I fix it by adding the "npmpath" value to the sessions section of the config.json. For example, my server looks like this:

```
"NpmPath": "/home/ec2-user/.nvm/versions/node/v10.15.1/bin/node /home/ec2-user/.nvm/versions/node/v10.15.1/bin/npm",
```

Let me know if that works.

**Comment by killmasta93** [comment]
thanks for the reply, i was looking at my server 
and found this part

```
root@remote:~# whereis node
node: /usr/bin/node /usr/share/man/man1/node.1.gz
root@remote:~# whereis npm
npm:
```
so the config would be like this? as i couldn't find the npm
`
"NpmPath": "/usr/bin/node",`

Thank you

**Comment by Ylianst** [comment]
On my server, I see this:

```
[ec2-user ~]$ whereis npm
npm: /home/ec2-user/.nvm/versions/node/v10.15.1/bin/npm
[ec2-user ~]$ whereis node
node: /home/ec2-user/.nvm/versions/node/v10.15.1/bin/node
```

Do you even have npm installed on your computer? What if you type `npm -v`?

**Comment by killmasta93** [comment]
thanks for the reply, it seems that i did not have it installed, installed it and added the route
`
"NpmPath": "/usr/bin/node /usr/bin/npm",`

and it works 

Thank you again

**Comment by killmasta93** [comment]
quick question, it is possible on the filter to show the computer the last seen time?

**Comment by Ylianst** [comment]
You can see the last time the agent connected here:

![image](https://user-images.githubusercontent.com/1319013/103424524-9f369f00-4b61-11eb-9b24-a1db89b56ca3.png)

I don't have a filter for it, but could be a feature request. At some point I need to fix this to also update the time when the agent disconnects, so it's not the last time it was connected, but the last time it was disconnected.

**Comment by killmasta93** [comment]
Thanks for the reply, i guess it could be a future feature on the right side to show the last time instead of going to each one.

Thanks again

![image](https://user-images.githubusercontent.com/13953629/103431852-d7ab9c80-4ba4-11eb-8989-f2d2a17de9ad.png)
