### ISSUE TITLE
Error: cannot find module 'express'

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2131]
I am splitting this issue off from my original issue #2062 as the original trouble reported in that issue seems to have been found and resolved (my username has a $ in it so that was causing the issues with migrating to MongoDB).  

Now, however, I am having this trouble when trying to update my MeshCentral install to a current node_modules dependencies structure.  My current MeshCentral2 install is from early 2018 and has been upgraded along the way.  When trying to export my NeDB database and import in to Mongo I am getting these two errors:

```
C:\Program Files\Open Source\MeshCentral>node node_modules/meshcentral --dbimport myserverdb.json
ERR: the options [useNewUrlParser] is not supported
ERR: the options [useUnifiedTopology] is not supported
Imported 2116 objects(s) from myserverdb.json.
```

Ylian mentioned this was due to my install being from so far back and the NodeJS node_modules is outdated.  I followed the steps below to force the node_modules to update to the most current version:

```
mv node_modules node_modules_bak
npm install meshcentral
node node_modules/meshcentral
```

However, after running those commands and starting MeshCentral I found that I was no longer able to access the MeshCentral site.  Looking at the Task Manager (I am running under Windows Server 2019) I noticed that Node.js: Server-side Javascript would spike to 100% CPU for a few seconds, then drop down to 0%, then spike back up to 100% about every 30 seconds or so.  

Looking at the mesherrors.txt log shows this entry being logged every 30 seconds or so (coinciding with the CPU spikes I see).  

```
internal/modules/cjs/loader.js:1083
throw err;
^

Error: Cannot find module 'express'
Require stack:

c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\lib\index.js
c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\index.js
c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js
c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js
c:\Program Files\Open Source\MeshCentral\winservice\winservice.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
at Function.Module._load (internal/modules/cjs/loader.js:923:27)
at Module.require (internal/modules/cjs/loader.js:1140:19)
at require (internal/modules/cjs/helpers.js:75:18)
at Object. (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\lib\index.js:12:16)
at Module._compile (internal/modules/cjs/loader.js:1251:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
at Module.load (internal/modules/cjs/loader.js:1100:32)
at Function.Module._load (internal/modules/cjs/loader.js:962:14)
at Module.require (internal/modules/cjs/loader.js:1140:19)
at require (internal/modules/cjs/helpers.js:75:18)
at Object. (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\index.js:1:18)
at Module._compile (internal/modules/cjs/loader.js:1251:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
at Module.load (internal/modules/cjs/loader.js:1100:32)
at Function.Module._load (internal/modules/cjs/loader.js:962:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\lib\index.js',
'c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\index.js',
'c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js',
'c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js',
'c:\Program Files\Open Source\MeshCentral\winservice\winservice.js'
]
}
```

Any ideas what I will need to do to resolve that?  For now I rolled back to my MeshCentral 0.7.33 install to get back up and running (which is also still using NeDB).  I'd like to get the node_modules dependencies updated and then finish migrating to Mongo.  Also, anything else I should look at cleaning up since my MeshCentral install goes back so far (I think I started on version 0.2.x?)

**Comment by LPJon** [comment]
I would suggest making a copy instead of using the "mv" command. This will leave your current folder in place and allow npm to update it. npm will not reinstall all the modules except meshcentral if you move the folder. So if you make a copy then you leave all of the currently installed modules in place so they can be upgraded and you also have a copy of them. The command I would suggest is:

- cp -P \<source folder\> \<destination folder\>

Note the capital "P".

**Comment by Ylianst** [comment]
Ok, so... the spiking is just due to MeshCentral starting up, crashing and trying to start up again. If that happens, just stop the service.

I presume that you can run MeshCentral manually and it works using:

```
node node_modules/meshcentral
```

My guess is that when you run "npm install meshcentral" you ran it under some user, then when you start the service it runs under a different user that does not have access? (or something of the sort).

Let me know if you can run your server manually and it works fine. If it does and it's the service that is the problem, look at directory permissions.

**Comment by Ylianst** [comment]
@LPJon I think in this case, he wants to have a fresh set of dependencies. His MongoDB module is super old and needs to be updated. So, in this case, doing a move and running 'npm install meshcentral' again is probably correct.

**Comment by LPJon** [comment]
> 
> 
> @LPJon I think in this case, he wants to have a fresh set of dependencies. His MongoDB module is super old and needs to be updated. So, in this case, doing a move and running 'npm install meshcentral' again is probably correct.

Ok. I was making an educated guess from an earlier attempt at troubleshooting MeshCentral when I also moved the directory and it resulted in a failed startup attempt. I'm not familiar with older versions of MeshCentral very sorry.

Question: Would it also be necessary to update npm and node in this case? Or does the Windows version not operate that way?

**Comment by Ylianst** [comment]
No need to be sorry. I can use all the help I can get on GitHub. @PathfinderNetworks is one of the original users of MeshCentral1 way back and moved to MeshCentral2 in the early days. Probably a good thing to update this server more fully. He is a rare case. In general, your correct and I would copy the node_modules folder.

As for updating node, as long as your not running a really old version, anything above 6.0.0 will work, but if you are using Let's Encrypt or other features, the server will warn that you need a better version. As long as it works, I have not seen the need to ask people to update.

**Comment by PathfinderNetworks** [comment]
> Ok, so... the spiking is just due to MeshCentral starting up, crashing and trying to start up again. If that happens, just stop the service.
> 
> I presume that you can run MeshCentral manually and it works using:
> 
> ```
> node node_modules/meshcentral
> ```
> 
> My guess is that when you run "npm install meshcentral" you ran it under some user, then when you start the service it runs under a different user that does not have access? (or something of the sort).
> 
> Let me know if you can run your server manually and it works fine. If it does and it's the service that is the problem, look at directory permissions.

Hi Ylian,
I just tried this again.  I upgraded to 0.7.37 before trying.  
Running node node_modules/meshcentral results in an error loop with the same error message as what I posted earlier. 

}
MeshCentral v0.7.37, WAN mode.
MeshCentral Intel(R) AMT server running on mesh.xxxxxxxxxx.com:4433.
SMTP mail server xxxxxxxxxxxx.com working as expected.
Error: Command failed: C:\Program Files\nodejs\node.exe c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral --launch 4628
internal/modules/cjs/loader.js:1083
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\lib\index.js
- c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\index.js
- c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js
- c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\lib\index.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (c:\Program Files\Open Source\MeshCentral\node_modules\express-ws\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Program Files\\Open Source\\MeshCentral\\node_modules\\express-ws\\lib\\index.js',
    'c:\\Program Files\\Open Source\\MeshCentral\\node_modules\\express-ws\\index.js',
    'c:\\Program Files\\Open Source\\MeshCentral\\node_modules\\meshcentral\\webserver.js',
    'c:\\Program Files\\Open Source\\MeshCentral\\node_modules\\meshcentral\\meshcentral.js'
  ]
}

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Program Files\\nodejs\\node.exe c:\\Program Files\\Open Source\\MeshCentral\\node_modules\\meshcentral --launch 4628'
}
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...


In looking at the folder structure under node_modules I can see that the 'express' folder is missing from the 'clean' node_modules folder.  If I look at the backup I made of the node_modules folder I see that it does have a folder named 'express'. 
There are other folders that present in the old version that aren't in the new as well- such as 'express-handlebars' but not sure what should be there or not?

**Comment by PathfinderNetworks** [comment]
As a test, I copied the 'express' folder from the old node_modules folder over in to the new node_modules folder and tried starting MeshCentral. But I get the same looping issue and same error message posted above.  That it cannot find the module 'express'.  

It's as though the Meshcentral installer is not installing/creating all the necessary dependencies?  I am running Node version 14.8.0 under Windows Server 2019 if that may have anything to do with it?

**Comment by PathfinderNetworks** [comment]
Digging deeper, I can also see that the new express-ws folder is missing a 'node_modules' folder that is present in the old 'express-ws' folder.  

Not sure what other folders may be missing data, etc?  BTW, I am running the installer under a command prompt with full administrator access.  The account logged in to the server is also a full administrator with full access to the 'meshcentral' folder and all subfolders.  In fact, the new node_modules folder has exactly the same permissions as the old node_modules folder.

**Comment by PathfinderNetworks** [comment]
More strangeness (or maybe this is what it's supposed to do?). I copied the node_modules folder that was present in the old express-ws folder over in to the new express-ws folder.  But when I run node node_modules/meshcentral it deletes that folder I had just copied over and then errors out and keeps with the same loop as before.

**Comment by PathfinderNetworks** [comment]
If you like, I could create a zip of my MeshCentral folder and could send that to you- if that would help?  I'm wondering if maybe there is something wrong with my directory structure that was created by the original MeshCentral2 installation?

**Comment by PathfinderNetworks** [comment]
I was able to get all of this resolved today.  Here's what I did.  I renamed the entire MeshCentral install folder and decided to do a completely clean, new install to a new, empty directory using 
npm install meshcentral
node node_modules/meshcentral
Once I got that new server up and running I then copied over the meshcentral_data folder from the backup.  I did have to install the Windows service files using 
node node_modules/meshcentral --install
and then manually modified the existing MeshCentral Windows service path to point to the new directory. 
That got me up and running 'clean' under the NeDB database and with a new and clean node_modules structure. 

There had to have been something from the original install that was gumming up the system I guess.

**Comment by Ylianst** [comment]
Oh perfect! One thing that is nice about NeDB is that you can just setup a completely new server and copy "meshcentral-data" back and you are done. This is important to note for people who need to recover from a backup. Thanks for reporting back.
