### ISSUE TITLE
Thank You! Thank You! Thank You!

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#2133]
Huge shoutout to @Ylianst, @krayon007 and @ryanblenis! You guys are phenomenal! Mesh has been the best tool for my business hands down. The care you put into this project and your incredibly rapid response times to fix even the smallest bugs does not go unnoticed. Thank you so much for all your hard work. I hope you both have a safe and happy new year ahead!

**Comment by darryl-h** [comment]
Couldn't agree more, thanks to everyone who has contributed time and effort!

**Comment by 1001crew** [comment]
I join in the congratulations.
I would like to thank you for the quality of the product and the service.
I am seriously thinking of replacing REMOTE.IT for the management of all the nodes scattered around the world.
If only I could get to grips with installing it under OpenWRT it would be simply fantastic.

**Comment by PathfinderNetworks** [comment]
Same here, MeshCentral (going back to the first version) has been the single most important tool used in my business. Truly, nothing else has been as important and impactful as Mesh!  Thank you Ylian and team!

**Comment by Ylianst** [comment]
Thanks you! Much more coming up on 2021. There is so much more work to be done. One note of the original post, Bryan (@krayon007) and myself work for the same large company and full time on MeshCentral. Bryan works on the MeshAgent and I work on the server. The MeshAgent is extremely complex and so, MeshCentral would not be possible without Bryan.

**Comment by routerino** [comment]
I also would like to give the team a thumbs up, you guys are doing fantastic work and I love it.
