### ISSUE TITLE
Unable to download Files from client computer (Windows 10) using files tab in MeshCentral 

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2134]
OS: Debian 10.7
Memory: 2GB
vCPU's: 1
MeshCentral Version: 0.7.37

Strangely I am able to successfully upload any file to the Windows 10 systems. However, downloading any files seems to fail. It will appear to hang and after about 30 to 60 seconds I will get the dialogue window of where to save the file but after saving it, it will always have a zero length. Any idea what would cause this? I do have 2 upstream proxies but I can't find any errors in any of their logs. Using the trace tab of MeshCentral says the connection is verified but is then never actually connected for the file transfer.

Below is the trace: (Note that I have removed the IP addresses)

3:33:51 PM - RELAY: Relay disconnect: w5gxdiox3pm
3:33:36 PM - RELAY: FileRelay disconnect: rmzckduvaqpc
3:33:06 PM - WEBREQUEST:  /devicefile.ashx?id=rmzckduvaqpc&rauth=%24dVpovDCxryyLsAL7Qn%24sskooibvTBPoSoj1QnZBxOEbDczqu78XtlmoqP%40dnHD%40fBtQ%40GVAZAG2GuVMx03aCw5mp8SnNfYUuCE7GZEX97q3glZkvl9tIrMyTAwDJQ==
3:33:06 PM - RELAY: FileRelay holding: rmzckduvaqpc  Authenticated
3:33:06 PM - RELAY: FileRelay: Sending agent tunnel command: {"nodeid":"node//uN46dxKLLzkpAtKVIx7np0ukuoEv8SuMTXAO4zYgy7qvFZB1H8xYHX1JsJTauugO","action":"msg","type":"tunnel","userid":"user//jonstuart@laptop-pitstop.net","value":"*/devicefile.ashx?id=rmzckduvaqpc&rauth=$dVpovDCxryyLsAL7Qn$sskooibvTBPoSoj1QnZBxOEbDczqu78XtlmoqP@dnHD@fBtQ@GVAZAG2GuVMx03aCw5mp8SnNfYUuCE7GZEX97q3glZkvl9tIrMyTAwDJQ==","soptions":{}}
3:33:06 PM - WEBREQUEST: /devicefile.ashx?c=HDYC68hCTnLMecd$34kcO46kStEVJ23g2ehaCscKKTocQnZa6rKRX1A4kWXdpr0t9w80mw5ZvOMxtUEcud4GvrG9y26qYIlNIf9YxicUXwNejkX8gnXBp6OwC0WsNJgd3oaScNYnnNjVhojAE05PSdBuMug3iIo6W$4avZqdHR0FzA==&m=K3$tE2PF8UCaUnBHx5GNXJDnMms8Uhpi6Vy5ZGqk4yUmGRbsc1dfml8lXbCcpqy$&n=uN46dxKLLzkpAtKVIx7np0ukuoEv8SuMTXAO4zYgy7qvFZB1H8xYHX1JsJTauugO&f=C%3A%2FbootTel.dat
3:33:01 PM - WEBREQUEST:  /images/icon-relay-notify10.png
3:33:01 PM - RELAY: Relay connected: w5gxdiox3pm 
3:33:01 PM - WEBREQUEST:  /meshrelay.ashx/.websocket?browser=1&p=5&nodeid=node//uN46dxKLLzkpAtKVIx7np0ukuoEv8SuMTXAO4zYgy7qvFZB1H8xYHX1JsJTauugO&id=w5gxdiox3pm&auth=HDYC68hCTnLMecd$34kcO46kStEVJ23g2ehaCscKKTocQnZa6rKRX1A4kWXdpr0t9w80mw5ZvOMxtUEcud4GvrG9y26qYIlNIf9YxicUXwNejkX8gnXBp6OwC0WsNJgd3oaScNYnnNjVhojAE05PSdBuMug3iIo6W$4avZqdHR0FzA==
3:33:01 PM - RELAY: Relay holding: w5gxdiox3pm 
3:33:01 PM - WEBREQUEST:  /meshrelay.ashx/.websocket?p=5&nodeid=node//uN46dxKLLzkpAtKVIx7np0ukuoEv8SuMTXAO4zYgy7qvFZB1H8xYHX1JsJTauugO&id=w5gxdiox3pm&rauth=ZqTv0QpBX9Y7I9ne2Yw3X6Oh0sRvyYkyy2Du4ObHP%24HbYwgdJPkEu9nBE0EhfmovTs32szdDT3WtJt5CTjUei0CD8KM5De0GSze

**Comment by Ylianst** [comment]
This is weird. From the log, I see the browser connecting to the server to perform the file transfer:

`3:33:06 PM - WEBREQUEST: /devicefile.ashx?id=rmzckduvaqpc...`

When, the server sends a command to the agent to download the file:

`3:33:06 PM - RELAY: FileRelay: Sending agent tunnel command...`

Finally the agent connects back:

`3:33:06 PM - WEBREQUEST: /devicefile.ashx?c=HDYC68hCTn...`

So, everything looks ok. Can you take a look at the browser console and see if there are any errors showing (probably not)? Also, can you go in the agent console and see if anything is displayed (maybe)? Is there a possibility that the agent is running in interactive mode, that is under user permission, and the downloaded file needs elevated permissions to access? If you try a different file, does it work?

I will try different things, but I am doing to have to shoot in the dark unless I get more data to reproduce the problem.

One thing I do want to do is have the agent send back error messages if it can't access the remote file or if the file has an exclusive lock or something. I think that will be useful. We don't currently do that.

**Comment by LPJon** [comment]
This error does exist in the console:

> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

The agent was installed with \"Background Only\" mode. However after looking at the service the checkbox that said \"Allow this service to interact with the desktop\" was checked, so I unchecked that and restarted the service. The problem still persists. The agent console is empty. I have noticed strange issues with running PowerShell's from the agent too lately. Could that be part of it?

Another strange thing is that the agent can edit the file in place with the right-click context menu option. So that would say the agent has access to the file. It just can't download it. I have tried may different files, file sizes, and types. I can upload them all...I just can't download them. I willing to do whatever you need to help. I could even give you temporary access to an account if you want. Just let me know what would be ideal for you or what you need me to perform.

**Comment by PathfinderNetworks** [comment]
Just shooting in the dark here- but could the antivirus on the device be interfering with the upload?

**Comment by LPJon** [comment]
No upload is fine.....only download is effected. I did consider that and completely removed my antivirus software. I also shutdown all the Windows 10 security that I could. Still has no effect. However, I should say that Windows 10 has a lot of built in security that like to get in the way of software like this. Am I supposed to sign the agent with some special certificate or something?

**Comment by PathfinderNetworks** [comment]
No, you shouldn't need to do that.  I have a few hundred Windows 10 and Server 2016/2019 devices and can upload/download files to/from those devices without issue.  So not sure what might be going on in your case?  I run Avast CloudCare on all of my devices.  There are times when Avast will see the MeshAgent installer as malware when doing the initial install but that's the only issue I've had.  I have seen the same with Windows Defender as well.  But, once the agent is installed, it seems to not be an issue (at least for the 64bit version- the 32bit version has been removed, at times, by various antivirus apps).

**Comment by PathfinderNetworks** [comment]
Could there be some Group Policy or other software in place that prevents files from being sent out from the devices?  But, if that were the case, I would expect it to fail immediately.

**Comment by LPJon** [comment]
Ok...so as I stated in the first post I have 2 upstream proxies which are showing no error. However, the issue may be how the connection is forwarded to the back-end MeshCentral server. I would need to know what files need to forwarded as WSS and which ones need to be forwarded as https/http.

Whatever the case it is only the incoming connection from the agent that seems to be the issue. So either the agent is having issues running it's command or the command/connection is not reaching MeshCentral properly.

**Comment by LPJon** [comment]
> 
> 
> Could there be some Group Policy or other software in place that prevents files from being sent out from the devices? But, if that were the case, I would expect it to fail immediately.

This is not a domain controlled PC and it's using the default GPO's. What GPO's would I need to start looking at?

And just figured out it's not the proxies. Direct access to the backend does the same thing. Can I ask how you go about installing your Agent, maybe I'm missing a procedure?

**Comment by Ylianst** [comment]
I just tested it on my servers and both upload and downloads work. If you would like, create a basic account on your server and send me a login, [my contact info is here](https://www.meshcommander.com/contact-information). I can take a look at it. I will setup a Win10 machine and try download a file and see what happens.

**Comment by LPJon** [comment]
I will setup an account for you tomorrow. We have a demo windows 10 vm to use as well. Would you also like an account for the meshcentral vm so that you have access to the terminal?

**Comment by LPJon** [comment]
@Ylianst @PathfinderNetworks I have narrowed this down to a proxy issue. Some of our proxies are a mixture. Apache seems to be the culprit. When I proxy with only NginX the downloads work fine. However, this mitigates some of our security measures. The Apache proxy has special forwards for the WSS connections since it has issues with forwarding this on it's own. Does anyone have an example of a working Apache proxy for MeshCentral. It seems to be related to how the /agent.ashx URI's are processed.

**Comment by Ylianst** [comment]
One thing I would do open the browser developer tools and look at the `Content-Security-Policy` header that is sent back by the server. I think you may find the when using Apache, this header is different from when using NGINX or using no reverse proxy.

**Comment by LPJon** [comment]
Reference Issue #317
@Ylianst @PathfinderNetworks 
This issue has been verified and resolved. Apache was failing to proxy web secure sockets correctly to the back-end MeshCentral server. I was able to correct this issue after reading the issue listed above and I have supplied a working solution below. 

	ProxyRequests Off
	ProxyPreserveHost On
	SSLProxyEngine on
	SSLProxyCheckPeerCN On
	SSLProxyCheckPeerExpire on

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteRule . wss://127.0.0.1%{REQUEST_URI} [P]
    
       ProxyPass / https://127.0.0.1/
       ProxyPassReverse / https://127.0.0.1/

Please note that you must have the proper IP to your back-end server for this to work. Also, if you are not using WSS you must change it to WS in the example above. This example is also obviously for secured connections so you will have to have HTTPS in place on your proxy.

Very sorry to waste everyone's time on this. I didn't see this example in the documentation...it may very well be worth putting in there.

**Comment by Ylianst** [comment]
Oh excellent! Thank you for reporting back the details on this and how you fixed it. Much appreciated.
