### ISSUE TITLE
allow hostname in TrustedProxy (for Docker setups)

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2135]
MeshCentral crashes on using a hostname instead of an IP address in TrustedProxy. This is however interesting with a docker setup where the IP address of the caddy proxy can change after restarts. In the MeshCentral container, the name of the proxy is resolved by Docker.

```
ERR: /meshcentral/node_modules/proxy-addr/index.js:163
    throw new TypeError('invalid IP address: ' + str)
    ^

TypeError: invalid IP address: caddy
    at parseipNotation (/meshcentral/node_modules/proxy-addr/index.js:163:11)
    at compileRangeSubnets (/meshcentral/node_modules/proxy-addr/index.js:126:23)
    at Function.compile (/meshcentral/node_modules/proxy-addr/index.js:112:23)
    at exports.compileTrust (/meshcentral/node_modules/express/lib/utils.js:238:20)
    at Function.set (/meshcentral/node_modules/express/lib/application.js:372:34)
    at serverStart (/meshcentral/node_modules/meshcentral/webserver.js:4886:46)
    at /meshcentral/node_modules/meshcentral/webserver.js:262:17
    at /meshcentral/node_modules/meshcentral/db.js:1181:107
    at newArguments.<computed> (/meshcentral/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/meshcentral/node_modules/nedb/lib/datastore.js:484:12)
Error: Command failed: /usr/local/bin/node /meshcentral/node_modules/meshcentral/meshcentral.js --launch 7
/meshcentral/node_modules/proxy-addr/index.js:163
    throw new TypeError('invalid IP address: ' + str)
    ^

```

**Comment by Ylianst** [comment]
Interesting. Yes, makes sense. I will be adding that when I get back to work.

**Comment by Ylianst** [comment]
Check this into GitHub, it will be in MeshCentral v0.7.38 when next published. When you get to test it, please report back if it works or not. Thanks.

**Comment by CHBMB** [comment]
Docker networking now working for me.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",

  "settings": {
    "cert": "meshcentral.server.com",
    "port": 443,
    "TlsOffload": "nginx"
  },
   "domains": {
     "": {
     "certUrl": "https://nginx:443/"
  }
 }
}
```

**Comment by Ylianst** [comment]
Excellent! Thanks for reporting back.

**Comment by CHBMB** [comment]
Docker networking now working for me.

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",

  "settings": {
    "cert": "meshcentral.server.com",
    "port": 443,
    "TlsOffload": "nginx"
  },
   "domains": {
     "": {
     "certUrl": "https://nginx:443/"
  }
 }
}
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.38, Hybrid (LAN + WAN) mode.
Loaded web certificate from "https://nginx:443/", host: "meshcentral.server.com"
SHA384 cert hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SHA384 key hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MeshCentral Intel(R) AMT server running on meshcentral.server.com:4433.
MeshCentral HTTP server running on port 443.

**Comment by vtacquet** [comment]
I am still seeing proxy IP addresses instead of real ones.

![image](https://user-images.githubusercontent.com/5128967/103616117-20a87b80-4f2c-11eb-945a-c1ac51f2ea55.png)

I do pass my X headers to the MeshCentral container.
![image](https://user-images.githubusercontent.com/5128967/103616187-3cac1d00-4f2c-11eb-8075-e852a8af46e2.png)

And both TLSOffload and TrustedProxy is in my MeshCentral config file.
![image](https://user-images.githubusercontent.com/5128967/103616251-5a798200-4f2c-11eb-9ad5-94f4d097e55d.png)

**Comment by Ylianst** [comment]
I just did another improvement for this, will come with v0.7.41 probably later today. Should fix the incorrect IP address issue.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/103741513-7f87f680-4ff9-11eb-87b7-235b67951e9d.png)

Well it updated but I am not able to logon anymore (I get this error after login and token and when it should be showing the webportal). Changed the config back to "TLSOffload": true without the "TrustedProxy" still nog go. Tried several different browsers.

**Comment by vtacquet** [comment]
Rolled back to 0.7.40 all is working again... Did something break on v0.7.41 with 2FA @Ylianst ?

**Comment by vtacquet** [comment]
#2150
