### ISSUE TITLE
"desktopMultiplex" does when work with server peering

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#2136]
hello Ylianst, first of all best wishes for the new year, hoping that the pandemic will end soon.
During the holidays I did some experiments with clutserized meshcentral.
Briefly, I have configured 3 nodes and activated a shardless replication set for simplicity. For each virtual mesh node I have configured 2 network interfaces, one connected on an internal lan, accessible only to the three nodes on which the three mongo dbs listen and the other accessible by mesh agents. So I configured the 3 peers using isolated internal IPs. Furthermore, I have also successfully activated 3 ucarp instances in order to obtain resilience to the fall of a node, and I entrusted the balancing to bind 9 (vm number 4) creating a dns record with three different IPs (Round robin resolution), corresponding to the three virtual IP of the three virtual groups ucarp Each node is active (virtual ip assigned) of a virtual group and passive for the other two. If a ucarp node does not respond, the virtual ip is transferred to one of the remaining nodes.
Everything works, I started the three mesh instances and installed an agent.
On each node I see exactly the same configuration, so mesh debugging tells me that all three peers are connected
For testing I have successfully activated the remote control simultaneously on the three nodes.
Then I wanted to activate the following option
"desktopMultiplex": true, on all three nodes and I encountered the following situation:
node 1: su I started the remote rdp session successfully
Node 2 and node 3 clicking on the connections the screen remains black.
On node 1 (where rdp works) I read the following error

node 1

RELAY: DesktopRelay: Connection (192.168.10.1)
RELAY: DesktopRelay: Error, duplicate agent connection

node 2
RELAY: DesktopRelay: Connection (192.168.10.1)
RELAY: DesktopRelay: Creating new desktop multiplexor

node 3
RELAY: DesktopRelay: Connection (192.168.10.1)
RELAY: DesktopRelay: Creating new desktop multiplexor

I redid the double check by disabling the option and the simultaneous remote control on the three nodes works again.
I forgot the file manager and the command prompt work in both cases. Maybe I'm doing something wrong in the configuration.
 I was wondering when to migrate to a replicated configuration ?? Actually I have a hundred clients always online out of over 200 total
I apologize if I have dwelt, I hope I was clear and thank you very much for everything
Paul

**Comment by Ylianst** [comment]
Oh, right. I see what is going on. "desktopMultiplex" does not work with server peering. Without even looking at the code, I can see why that would cause a problem. I will work on a fix in the next week.

**Comment by paolor1965** [comment]
thank you very much

**Comment by Ylianst** [comment]
I just check into GitHub multi-server support for desktop multiplexer. Should be in MeshCentral v0.7.39 when it's next published. Once published and you update, please report back if it works or not. Thanks.

**Comment by Ylianst** [comment]
MeshCentral v0.7.39 is out. Let me know if it works.

**Comment by paolor1965** [comment]
Hello after updating and installing by hand
npm install image-size, I confirm that now rdp works simultaneously on all nodes
I noticed this type of display in the statistics but the client has no connectivity problems
![Immagine 2021-01-05 124418](https://user-images.githubusercontent.com/58943816/103642934-2914ac80-4f54-11eb-8ed1-831a635e45ba.png)

**Comment by paolor1965** [comment]
the module image-size I had to reinstall because I was back with the snapshots

**Comment by Ylianst** [comment]
Oh right. I need to work on fixing the server graphs to support multi-server.

**Comment by Ylianst** [comment]
MeshCentral v0.7.42 when published will have support for graphics in multi-server configuration.

![MC2-MultiServer-Graph](https://user-images.githubusercontent.com/1319013/103733132-dcee5a00-4f9d-11eb-9fad-598c0f0c0f4a.png)

**Comment by paolor1965** [comment]
I have successfully updated to 0.7.41 and the multi server works correctly, also the simultaneous rdp works but I don't see the server selection menu in the statistics. Perhaps using a separate interface  for mongo can cause problems. I have debugged but I see no errors, apart from the initial connection to the peers, waiting for the other servers to be running
and the statistics are always in fits and starts
I probably have something wrong in the configuration
node 1

/etc/hostname
meshcentral1

/etc/hosts    #for all nodes
10.0.0.31 mongodb1 mongodb1.casa.it
10.0.0.32 mongodb2 mongodb2.casa.it
10.0.0.33 mongodb3 mongodb3.casa.it

192.168.10.31 meshcentral1 meshcentral1.casa.it   
192.168.10.32 meshcentral2 meshcentral2.casa.it
192.168.10.33 meshcentral3 meshcentral3.casa.it


192.168.3.35  meshcentral-cluster meshcentral-cluster.casa.it  #using dns for RRobin Virtual IP ucarp float
192.168.3.36  meshcentral-cluster meshcentral-cluster.casa.it #using dns RRobin   Virtual IP ucarp float
192.168.3.37  meshcentral-cluster meshcentral-cluster.casa.it #using dns Rrobin   Virtual IP ucarp float

node 1


 "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "desktopMultiplex": true,
     "webRTC": true,
    "_agentIdleTimeout": 300,
     "cert": "meshcentral-cluster.casa.it",
    "WANonly": false,
    "LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "MongoDbChangeStream": true,
   "_redirAliasPort": 80
  },



"peers": {
    "serverId": "mongodb1",
    "servers": {
      "mongodb1": { "url": "wss://mongodb1:443/" },
      "mongodb2": { "url": "wss://mongodb2:443/" },
      "mongodb3": { "url": "wss://mongodb3:443/" }
    }
  },


For the other nodes the configuration is identical except for the peers
node 2
"peers": {
    "serverId": "mongodb2",
    "servers": {
      "mongodb1": { "url": "wss://mongodb1:443/" },
      "mongodb2": { "url": "wss://mongodb2:443/" },
      "mongodb3": { "url": "wss://mongodb3:443/" }
    }
  },

"peers": {
    "serverId": "mongodb3",
    "servers": {
      "mongodb1": { "url": "wss://mongodb1:443/" },
      "mongodb2": { "url": "wss://mongodb2:443/" },
      "mongodb3": { "url": "wss://mongodb3:443/" }
    }
  },

node 3
"peers": {
    "serverId": "mongodb3",
    "servers": {
      "mongodb1": { "url": "wss://mongodb1:443/" },
      "mongodb2": { "url": "wss://mongodb2:443/" },
      "mongodb3": { "url": "wss://mongodb3:443/" }
    }
  },

**Comment by paolor1965** [comment]
I'm sorry I had some problems because the web update stopped working. I had to proceed to the command line.
Via web I go back to the stable version but then when I go back to the last one it fails.
It certainly depends on my problem because on other installations I use (non-clustered) it works.
 Apart from this now I see in the statistics the three servers mongodb1 + mongodb2 + mongodb3 + null
It seems to me everything
