### ISSUE TITLE
Windows Meshagent crashes when opening a desktop with 7 monitors

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#2137]
First off, I apologize for abusing my poor meshcentral server with a 7 monitor endpoint :). When attempting to connect to the desktop the agent will crash and then reconnect.

Turning down the quality enough will fix the problem, so I suspect it's bandwidth related? See linked gif.

https://i.imgur.com/YnCxFPc.gif

Not a show stopper certainly, I'm amazed that it worked at all. Changing to an individual monitor also prevents the problem from occuring.

**Comment by Ylianst** [comment]
Wow. 7 monitors! I not sure how we are going to replicate this.

**Comment by routerino** [comment]
> Wow. 7 monitors! I not sure how we are going to replicate this.

If it is a bandwidth issue like I suspect, you can replicate the problem with 2x 4k monitors at a higher quality.

**Comment by jsastriawan** [comment]
It could be memory allocation issue for for JPEG encoding buffer. But I think @krayon007 knows better.

**Comment by si458** [comment]
is this still an issue?

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
