### ISSUE TITLE
Linux interactive installer hangs since 0.7.28

### ISSUE THREAD

**Issue by Yvan-Masson** [Ylianst/MeshCentral#2140]
Hi,

Starting from MeshCentral 0.7.28, the interactive agent (the one you get from MeshCentral when clicking on "Add an agent -> Linux binary executable -> interactive only" (approximate translation sorry) hangs: process starts but does not display anything, nor in the console nor in a Zenity window, even with `-help` option. Issue is still here with 0.7.37.

I tested the agent on two computers: one running Debian testing, the other running Ubuntu 20.04.

Regards,
Yvan

**Comment by Ylianst** [comment]
Yes, this is because of the new agent multi-language support. Working on a fix for that.

**Comment by Ylianst** [comment]
Ok, found the problem and fixed it. Will be in MeshCentral v0.7.38. Thanks for reporting that.

**Comment by Ylianst** [comment]
Published MeshCentral v0.7.39. Let me know if it works.

**Comment by CHBMB** [comment]
Confirmed as working for me.

**Comment by Ylianst** [comment]
Excellent! Thanks for reporting back.

**Comment by Yvan-Masson** [comment]
It also works for me, thanks!
