### ISSUE TITLE
'Command' on 'MeshAgent' threw an exception: could not find service: Mesh Agent in method 'handleServerCommand()'

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#2144]
Hello, I have personalized the name of the meshagente service but when uninstalling an agent from the platform, it indicates the following error in console:
uncaughtException1: Error: => EventEmitter.emit (): Event dispatch for 'Command' on 'MeshAgent' threw an exception: could not find service: Mesh Agent in method 'handleServerCommand ()'

**Comment by krayon007** [comment]
I fixed this in meshcore, so should be included in the next server update

**Comment by mrkacg1** [comment]
@krayon007 Thanks, when do you think this update is available?

**Comment by krayon007** [comment]
> @krayon007 Thanks, when do you think this update is available?

Soon hopefully, I just need to get in touch with @Ylianst

**Comment by Ylianst** [comment]
Bryan's fix is now in MeshCentral v0.7.40 that was just published. Let us know if it works.

**Comment by mrkacg1** [comment]
Solved, thanks for the prompt assistance.
