### ISSUE TITLE
Scheduling Power Down & Power Up for Device Group

### ISSUE THREAD

**Issue by RMichaelPickering** [Ylianst/MeshCentral#2145]
Would it be possible to have an automated scheduling capability for a device group, to facilitate automatically powering down and/or powering up all the devices as per a predefined schedule (e.g. daily)?

**Comment by Ylianst** [comment]
I am going to start by adding wake/sleep/off capability to MeshCtrl.js so that you can perform power actions on remote devices using the command line. This should allow you to perform automated power operations on remote devices as you need. I should have this done in a few hours.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.41 with support for power actions from the command line. In the "node_modules/meshcentral" folder there is a file called `meshctrl.js`. This is a command line tool, you can run it like this:

```
node node_modules/meshcentral/meshctrl
```

It will show you plenty of instructions on how to use it and what command you can perform. You can do everything from managing user accounts to powering on/off devices from the command line. Try "DevicePower" action and let me know what you think.

![MC2-MeshCtrl-Sharing-Power](https://user-images.githubusercontent.com/1319013/103731956-3bfe9f80-4f9b-11eb-837d-e0b13ec2876a.png)

**Comment by jdvmanen** [comment]
Can these commands being initiated by the web GUI as well? Works this that one remote PC can wake up the other remote PC (both remote pc's in the same LAN, and WOL enabled?)

**Comment by Ylianst** [comment]
Yes, if you click on a sleeping device and hit the action button and select "Wake". All the devices you own will send wake-on-lan packets to the device you are trying to wake up. So, this should work in the web interface now. I just added the same feature to the command line tool.

**Comment by tranbert** [comment]
By the way, WakeOnLan is still unresponsive via web interface. (server 0.7.49)

On distant or lan pc  :   "wakeonlan f53fdb08de9c" from another mesh controled pc console is OK

Works also on lan via wol tool on windows (softperfect network scanner) or linux command line.

Any clue for this ?
