### ISSUE TITLE
Suggestion for another shortcut key

### ISSUE THREAD

**Issue by tprinslo** [Ylianst/MeshCentral#2146]
Hi Ylian

Thank you for all the hard work on MeshCentral. Awesome software.
Suggestion for another shortcut key.
Display the desktop on client’s machine (Win+D). 
Win+M will minimize all windows but some pop-ups can remain(like the for instance the MeshCentral agent if using connect only option) Using the Win+D  present one with a desktop where all the windows are minimized.

**Comment by yomono** [comment]
I would like to actually extend this request: custom shortcuts.
I imagine it like this: a config window that allows the user to make his own combination (let's say: ctrl + shift + J), save it, and add it to the key shortcut list. Ideally this could be global, being configured for the entire server and all agents.

Ps: actually the perfect scenario would be mesh central automatically calturing the keyboard shortcuts in real time when we are on the remote desktop section, but the custom shortcuts is a more realistic request I think, to this day

**Comment by Ylianst** [comment]
Just published this in MeshCentral v0.7.45, let me know if it works.

![MC2-KeyboardShortcuts1](https://user-images.githubusercontent.com/1319013/103988293-b0277780-5142-11eb-8718-7f157063a29a.png)

**Comment by tprinslo** [comment]
Super work. The changes works !
Thanks

**Comment by yomono** [comment]
Amazing

**Comment by orion88-admin** [comment]
Hello

I updated my Meshcentral instance to version 0.7.45 and decided to check the manual adding of shortcuts. Unfortunately, after adding the shift + alt + del shortcut, the shortcut does not work, it does not open the history cleaning window in the web browser window. Likewise, Win + L and Win + F4 shortcuts also do not work.

I checked the Embdeed 32 bit on Windows 7

Any ideas why it doesn't work?

**Comment by yomono** [comment]
> Hello
> 
> I updated my Meshcentral instance to version 0.7.45 and decided to check the manual adding of shortcuts. Unfortunately, after adding the shift + alt + del shortcut, the shortcut does not work, it does not open the history cleaning window in the web browser window. Likewise, Win + L and Win + F4 shortcuts also do not work.
> 
> I checked the Embdeed 32 bit on Windows 7
> 
> Any ideas why it doesn't work?

This is basic, but it worth to check: after selecting the shortcut, do you press the "send" button right next to it?
![image](https://user-images.githubusercontent.com/31445936/104050317-37b5ca80-51c5-11eb-8878-282fef1a8f80.png)

**Comment by Ylianst** [comment]
MeshCentral v0.7.46 was just published with keyboard shortcut customization on the mobile web site.

![MC2-MobileAppImprovements](https://user-images.githubusercontent.com/1319013/104082240-75c4e580-51e9-11eb-9f6e-e77dc93bc018.png)

**Comment by Ylianst** [comment]
Ok, I will close this one. If there are keys that don't work, please open a new issue and be as specific as possible. Thanks.
