### ISSUE TITLE
login page does not load

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#2149]
Hosted on my own server, auto-update is enabled.
I can SSH in.
Was on v 0.7.39, did a manual upgrade to 0.7.44

Still no luck getting the login page to load

**Comment by Ylianst** [comment]
One thing that did happen to me on this update is the my server ran out of disk space. As a result, the server would not start. Could it be you got the same problem? Use the "df" command on Linux to see disk usage.

Otherwise, start the server manually using:

```
node node_modules/meshcentral
```

Let me know what you see.

**Comment by FATeknollogee** [comment]
Brilliant, I think you are spot on...
/dev/vda1        25G   25G     0 100% /
Time to go increase disk space.

I'll report back shortly.

**Comment by Ylianst** [comment]
LOL. The NPM cache takes up a lot of space. Try this:

```
npm cache clean --force
```

If you have a small server, this alone may free up half you storage.

**Comment by FATeknollogee** [comment]
/dev/vda1        25G  5.6G   18G  24% /

Still no login after the force cmd

**Comment by Ylianst** [comment]
The problem is that you now have a badly updated MeshCentral. You going to have to do this:

```
mv node_modules node_modules_bad
npm install meshcentral
```

This will get you a fresh "node_modules" folder and you should be back online. If you are using MongoDB, the database may also be stalled and may need to be restarted.

**Comment by FATeknollogee** [comment]
Just did a reboot & everything is back online.

Thanks for the help!

**Comment by Ylianst** [comment]
Nice! To be honest, that is also what I did on my server. I cleared some space, got a fresh 'node_modules' and rebooted.
