### ISSUE TITLE
Mobile Desktop connect to RDP session not possible.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2152]
In Desktop browser mode, connect to a windows desktop. If there is next to the console session also one or more RDP sessions, then you can select the session to take over the screen of that session.
![image](https://user-images.githubusercontent.com/5203309/104005467-76d42380-51a5-11eb-9c66-380748af7dbb.png)

In Mobile browser mode, it will only connect directly to the console session.

**Comment by Ylianst** [comment]
MeshCentral v0.7.46. Let me know if that works.

![MC2-MobileAppImprovements](https://user-images.githubusercontent.com/1319013/104082159-ad7f5d80-51e8-11eb-8401-826c1c742593.png)

**Comment by hunter-nl** [comment]
Yes, I can confirm this is working great! Also the custom shortcuts.
