### ISSUE TITLE
Support for HTTP protocol?

### ISSUE THREAD

**Issue by hoFlyW** [Ylianst/MeshCentral#2153]
How can I support the HTTP protocol

**Comment by Ylianst** [comment]
Sorry, your going to have to be more specific. No idea what your question is.

**Comment by hoFlyW** [comment]
Now start to service, open the path to the https://localhost/, http://localhost/ does not support, I want to ask, how can support http://localhost

**Comment by Ylianst** [comment]
MeshCentral is a management web site and so, security is super important, so no, there is no HTTP support. There is a server on port 80 to redirect users to port 443 and perform other operations.
