### ISSUE TITLE
Standard user's shell and colour settings

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2155]
Is there a reason why using the Terminal in MeshCentral does not use the user's shell settings and 'environment' ? 

When logging on with a normal SSH terminal client the shell is zsh and has colours
![image](https://user-images.githubusercontent.com/5128967/104120091-669e7e80-5334-11eb-911c-bbedb7bfe331.png)

When logging on with MeshCentral Terminal the shell is bash and has no colours
![image](https://user-images.githubusercontent.com/5128967/104120125-b4b38200-5334-11eb-8cd2-61a6e3f221e3.png)

User has zsh as default shell
![image](https://user-images.githubusercontent.com/5128967/104120153-d6146e00-5334-11eb-970a-03dc62bea993.png)

**Comment by krayon007** [comment]
Right click on the connect button, and select login shell. That will use the user profile settings.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/104121236-02cc8380-533d-11eb-9342-4cb80e86d0b5.png)

that just goes 'denied', only root shell and login shell works (but that defaults to bash), can you set it default to what is in the user settings ?

**Comment by krayon007** [comment]
What linux distro are you using? I cannot set it to use the user profile because only the login shell can do that, which is what that other option is for. If you tell me what distro you are using I can try and figure out why the login shell isn't working.

**Comment by vtacquet** [comment]
well it is a bit of a special case, an "ubuntu:latest" in a docker container, it is used for testing.

**Comment by krayon007** [comment]
I assume you meant only root and user shell is working? Login shell spawns a login process which root and user shells do not.

**Comment by vtacquet** [comment]
![image](https://user-images.githubusercontent.com/5128967/104121368-f39a0580-533d-11eb-9ded-de7f1ce4ff53.png)
the green ones work but give a colourless bash shell. the red one gives a denied

**Comment by krayon007** [comment]
The login shell spawns a login process which is supposed to read the user profile. Is it prompting for a user name and password?

**Comment by vtacquet** [comment]
yes 
![image](https://user-images.githubusercontent.com/5128967/104121426-67d4a900-533e-11eb-8d2c-323d91a9ac78.png)

**Comment by krayon007** [comment]
That's interesting. Normally ssh client also spawns the same login process. I'll test with my ubuntu docker container tomorrow. Unless there's a different process I'm supposed to spawn in the docker container, I'm not sure if there's anything I can do. Normally the agent can't access the user profile script because it's running as a different user, which is why its supposed to rely on the login process to setup the environment.

**Comment by vtacquet** [comment]
I can confirm that the Denied is the same for a normal installation (outside of Docker). I do use zsh and Oh-My-Zsh.

![image](https://user-images.githubusercontent.com/5128967/104121551-5a6bee80-533f-11eb-8eac-7f441523faf2.png)

**Comment by krayon007** [comment]
Do you have user consent enabled? The user shell is supposed to spawn a process as the currently logged on user. The denied message looks like a user consent response. If no user is logged in, it should fail with a different error.

**Comment by krayon007** [comment]
Does the login shell use colors outside of your docker container?

**Comment by vtacquet** [comment]
The video is a bit low quality but it is just to show you there is nothing there when using iTerm.

https://user-images.githubusercontent.com/5128967/104121648-2cd37500-5340-11eb-8bfa-7cb0a1bcfebd.mp4

**Comment by vtacquet** [comment]
Very strange but the Login shell has only partial colours... The motd still shows its colours but the prompt has lost all colours.

![image](https://user-images.githubusercontent.com/5128967/104121688-7a4fe200-5340-11eb-8300-d47ea15e31f1.png)

**Comment by vtacquet** [comment]
seems that with the Login shell the default TERM=xterm is set instead of TERM=xterm-256color

(the motd doesn't check the TERM settings so that is why it is in colours)

**Comment by krayon007** [comment]
> seems that with the Login shell the default TERM=xterm is set instead of TERM=xterm-256color
> 
> (the motd doesn't check the TERM settings so that is why it is in colours)

Thanks! I'll check to make sure this is set to xterm-256color

**Comment by krayon007** [comment]
ok, I did a bunch of testing... It seems with the default `TERM=xterm` colors seems to work fine with bash, both inside and outside a docker container.

I built a docker image with zsh, and I can't get the terminal to show with colors, even with `TERM=xterm-256color`

**Comment by vtacquet** [comment]
try with this Dockerfile, it will install Oh My Zsh (this changes the prompt to colours)

`
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color

RUN apt -y update && \
    apt -y install zsh curl git

RUN yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
`

![image](https://user-images.githubusercontent.com/5128967/104153176-f3534600-53e1-11eb-978e-e69e3497a637.png)

**Comment by krayon007** [comment]
ok thanks! I created a new docker image, and verified it works with the change. It will be in the next agent update.

**Comment by Ylianst** [comment]
MeshCentral v0.7.47 was released with Bryan fix for this. Let us know if it works.

**Comment by vtacquet** [comment]
Root and Login Shell now have colours, that's perfect but I still get the Denied on the User Shell.

**Comment by krayon007** [comment]
> Root and Login Shell now have colours, that's perfect but I still get the Denied on the User Shell.

If you are using docker, that is normal. The "user" shell, just spawns a shell with the UID of the logged in user. However, with docker, there is no "logged in user", or at least the agent can't determine the logged in user, because `who` returns nothing.

**Comment by vtacquet** [comment]
This is not a docker test, this is just a regular Ubuntu 20.04 LTS (with zsh and Oh My Zsh).

**Comment by krayon007** [comment]
> This is not a docker test, this is just a regular Ubuntu 20.04 LTS (with zsh and Oh My Zsh).

That's wierd. I just tested on my Ubuntu 20.04 LTS, and it works fine. (granted I'm not using zsh, but I don't think that should be an issue)

If you click on the 'events' tab, does it show anything? If you connect a 'root' terminal, and type `who,` what does it say? (Is there a user actually logged into this machine?) What does it say if you type `users` on the console tab?

**Comment by vtacquet** [comment]
Hmm right, it is not related to zsh, I have it on hosts with bash too... 

In the event viewer you see the disconnect immediately (0 seconds)
![image](https://user-images.githubusercontent.com/5128967/104298560-692fde00-54c4-11eb-9447-68c8d0a6e0c7.png)

**Comment by dinger1986** [comment]
@si458 can close
