### ISSUE TITLE
Installing service [ERROR] Error Creating Service: 1072

### ISSUE THREAD

**Issue by 12nick12** [Ylianst/MeshCentral#2157]
I get the above error when trying to install on a Windows 10 machine. Any assistance would be appreciated.

**Comment by krayon007** [comment]
That error means there was already a service installed, so it tried to stop and uninstall the old service first, but it failed. You can try to install the service again, sometimes that works.... If that fails again, there are a few things you can check... The first would be check to see if the service is hung. You can go into the task manager, and see if there are any processing running with the name "MeshAgent.exe" or whatever the agent fileName was set to in the server config.

**Comment by PathfinderNetworks** [comment]
Also try running the MeshAgent installer as administrator.  I wonder if the user that you are running the installer under doesn't have full admin rights?  Right click the installer and choose Run as Administrator and see if that helps.

**Comment by 12nick12** [comment]
I've tried to uninstall and reinstall a couple times. When I go into the service it shows it as disable pending deletion. Is there anyway to make it force delete so I can re-create it?

**Comment by 12nick12** [comment]
Thank you everyone. I had to find the PID of the installer that as still running for some reason and then delete the service and "C:\Program Files\Mesh Central" (which was empty) and now it was able to install.
