### ISSUE TITLE
CentOS Installation Guide

### ISSUE THREAD

**Issue by infohou** [Ylianst/MeshCentral#2159]
CentOS is very popular with Linux server admins as it is an offshoot of RedHat Linux Enterprise.  Not including it in your Installation guide is a gross oversight.

Thanks,
Robert A. Ober

IT Consultant, Vidcaster, & Freelance Preditor(Producer/Editor)
www.infohou.com 
Houston, TX

**Comment by asasin114** [comment]
Have you tried installing the Linux agent? I've installed it on several of the FreePBX boxes I host which run a variant of CentOS and they work just fine.

**Comment by si458** [comment]
the is a guide for Amazon Linux 2 which is based off CentOS - https://ylianst.github.io/MeshCentral/install/install2/#amazon-linux-2_1
