### ISSUE TITLE
Localization Settings Date not saving

### ISSUE THREAD

**Issue by map7** [Ylianst/MeshCentral#2164]
When I set my Localization Setting Date to en-AU and click ok, then refresh the browser it forgets the Date and Time setting. But it doesn't forget the Langauge setting.

**Comment by 3freet** [comment]
@Ylianst Any updates on this?
Still loses configuration on tab refresh. Also does not take localization from browser, and defaults to en-us.

**Comment by EDIflyer** [comment]
yep I just noticed this too - it seems to ignore browser settings and although it says it has remembered `en-gb` when set to that the dates are all still in US format

**Comment by si458** [comment]
all fixed for you sorry for delay!
basically it was saving the settings in ur browser fine,
but the serverside was rejecting the settings and not saving it,
then when ur browser loads bk up, it asks the serverside for ur settings,
and the value was being removed because it didnt exist serverside
