### ISSUE TITLE
Feature Request - "noagentupdate: true" has ability to target a specific client agent for update

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2165]
In light of issue #2162 I'm making an official request to have the "noagentupdate" option allow for targeting a specific client agent for testing the agent updates before applying them to all client agents. Currently this option will disable all agent updates to prevent agent update loops allowing the agents to come back online after a reboot of the client. 

Additionally, it would be nice to be able to update the client agents from within the web UI. I would like to see an option to update an individual agent or all agents. This makes the process a little less automated and we IT guys can get a little more control over agent updates, testing, and reporting issues before they become big issues. **Having to reboot 700+ client systems/Servers can be very difficult especially when server restarts must be scheduled or when they are VM's that the customer client does not have access to.**

**Comment by Ylianst** [comment]
Completely agree. Thanks for posting this. We don't often get requests to improve the core infrastructure and so, that work is often undervalued. As a result of the v0.7.47 release, Bryan and I have made a bunch of changes.

- We now have a way to stress test the agent updates. Basically, we can have the server update our test devices non-stop for hours and so, any agent update issue will now be caught before release. I just ran this test on v0.7.47 and indeed, the problem shows up right away. This will now be part of the per-release standard testing.
- Bryan just added a completely independent second path to update the agent. For the most part, it does not shave any code with the existing path and give us more options going forward.
- Bryan simplified the current update system, so starting with the next release, the existing update system has fewer moving parts and less chances of anything going wrong.
- Bryan also added a new system to make it easy for the server to see what release date the connecting agent is so, we can change the behavior of the server to deal with older agents, etc.

On addition to all this, I do want to offer a way to manually update the agent when "noagentupdate: true". So yes, good idea. For most people, I think the best is to have a solid testing system on our side.

**Comment by LPJon** [comment]
![105072404-9f2c0f80-5a3a-11eb-842f-6699071e909e](https://user-images.githubusercontent.com/46533576/105210685-fbf9f980-5b10-11eb-8d7d-31ff2772317c.png)
If you want, you can turn off agent automatic update by adding the following line in the settings section of the config.json:

`"noagentupdate": true`

This will work on any version of MeshCentral. Then, you can go in the agent's console tab and type "versions" to see the agent version and starting with v0.7.48, you can type `agentupdate` to manually trigger an agent update.

![105073047-60e32000-5a3b-11eb-928a-e346053b8501](https://user-images.githubusercontent.com/46533576/105210731-0ae0ac00-5b11-11eb-8193-7274a3bd1381.png)

**I can confirm this feature works. Has anyone else been able to test this so that I can close it?**

**Comment by Ylianst** [comment]
@LPJon Nice! Thanks for placing this here and reporting back your findings. Glad it worked for you.
