### ISSUE TITLE
A message about failed login attempts.

### ISSUE THREAD

**Issue by orion88-admin** [Ylianst/MeshCentral#2166]
Hello

I noticed that in my version meschcentral 0.7.45 after unsuccessful login attempts, e.g. to the admin account. After successful login, a message with incorrect information about unsuccessful login attempts is displayed, the system shows only "0"

![BUG_MESHCENTRAL_LOGIN](https://user-images.githubusercontent.com/65662158/104578946-9f539600-565b-11eb-87d8-0aecd697ca77.jpg)

Regards

**Comment by mrkacg1** [comment]
I have the same problem. Version 0.7.40

**Comment by Ylianst** [comment]
Ha yes, I know about this one. It's was fixed in v0.7.47, but I removed that version of MeshCentral because of agent update issues. As soon as v0.7.48 is released, that will be fixed.

**Comment by orion88-admin** [comment]
ok I can see it works fine now, I updated my version to 0.7.49
greetings
