### ISSUE TITLE
Custom keyboard shortcuts "Win+R" is locking Windows 8/8.1/10 instead of bringing up "Run" dialogue box

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2169]
When using the "Win+R" keyboard shortcut in the "Desktop" tab of MeshCentral on Windows 8/8.1/10, it will lock the screen instead of bringing up the "Run" window. 

I'm still on MeshCentral v0.7.47.

**Comment by rowds15** [comment]
yes happens to me too, I also am on Version 0.7.47

**Comment by yomono** [comment]
In my case I'ts doing just nothing. Also on 0.7.47

**Comment by LPJon** [comment]
This issue appears to be fixed as of the 0.7.48 release. Can anyone else confirm so that I can close this issue?

**Comment by yomono** [comment]
Working on 0.7.48 for me

**Comment by Ylianst** [comment]
This should be fixed in v0.7.48. This said, like @LPJon mentioned in #2183, I need to fix "Win + L". However, this specific issue should be solved.
