### ISSUE TITLE
Share desktop with only view permissions 

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2172]
Hi. 
One question. Can I share desktop with only view permissions? 
Thanks in advance.

**Comment by LPJon** [comment]
> 
> 
> Hi.
> One question. Can I share desktop with only view permissions?
> Thanks in advance.

Not yet. Currently the only way to do view only is through the "noVNC" feature. This requires a "VNC" server on the client computer. Something like "TightVNC" works just fine. You would also then need to set the "View Only" option in the web interface. This option can be changed by anyone using it so it's not a security feature really. If you want to see this option in the Web UI of MeshCentral you should put in an official feature request. I actually wouldn't mind seeing this added for some training use cases where I need a user to see the computer but not have ability to control it.

**Comment by Ylianst** [comment]
When giving permissions to another user, check "Remote Control" and "Remote View Only". Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/104778966-1c057380-5733-11eb-8c1a-d3f04fb15585.png)

**Comment by LPJon** [comment]
> 
> 
> When giving permissions to another user, check "Remote Control" and "Remote View Only". Let me know if that works.
> 
> ![image](https://user-images.githubusercontent.com/1319013/104778966-1c057380-5733-11eb-8c1a-d3f04fb15585.png)

Yes! This does actually work. However, you must create a user account to use it. It is possible to use this feature from the "Share" button on the "General" tab so that you can just send a timed shared link without needing to create a user?

**Comment by Ylianst** [comment]
Oh. It's not currently possible for sharing links, but I was expecting that someone would ask for this. This is a good request.

**Comment by lergolas** [comment]
> > 
> > 
> > When giving permissions to another user, check "Remote Control" and "Remote View Only". Let me know if that works.
> > 
> > ![image](https://user-images.githubusercontent.com/1319013/104778966-1c057380-5733-11eb-8c1a-d3f04fb15585.png)
> 
> Yes! This does actually work. However, you must create a user account to use it. Is it possible to use this feature from the "Share" button on the "General" tab so that you can just send a timed shared link without needing to create a user?

My question is about this exactly, share with link, not with user.

**Comment by lergolas** [comment]
> Oh. It's not currently possible for sharing links, but I was expecting that someone would ask for this. This is a good request.

My question is about this exactly, share with link, not with user.

**Comment by Ylianst** [comment]
Agreed. Especially if you have this line in the settings section of the config.json:

```
"DesktopMultiplex": true,
```

Along with view only, you could run a classroom or presentation with the sharing link. I think this is a good idea.

**Comment by PetieM** [comment]
+1 for this request. I actually came here to make it myself.

**Comment by Ylianst** [comment]
I just pushed the changes into GitHub, with the next version of MeshCentral, you will be able to create a remote desktop sharing link that is "view only".

![MC2-ViewOnlyDesktopSharing](https://user-images.githubusercontent.com/1319013/104836961-5c194300-5866-11eb-9dc9-0483eba08a95.png)

**Comment by lergolas** [comment]
wow, that was fast! Thank you very much for implementing it.

**Comment by Ylianst** [comment]
It's not released yet :) Hopefully tomorrow.

**Comment by lergolas** [comment]
I know. I will test it when you release the update.
Thank you!

**Comment by Ylianst** [comment]
Ok, MeshCentral v0.7.48 is out. Let me know if it works.

**Comment by lergolas** [comment]
It works perfectly! Thank you very much.
