### ISSUE TITLE
Log off users

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#2173]
I was updating systems last night.

One computer had an existing Mesh connection by a user.
As admin, I couldn't see where this user was logged on from, nor could I log them off

A restart of the target system solved my issue, and luckily that didn't matter.

I would like, as an admin, to be able to log other users off, and to close connections.

**Comment by Ylianst** [comment]
Not sure I completely understand the question, but if you are looking to disconnect an agent from the server, you can go in the device "Console" tab, hit "Agent Action" and "Soft disconnect agent". However, the agent will generally reconnect unless it's an interactive agent.

For logging people off, in the same console tab, type `power logoff` and see if that works. It's not on the web interface, but could be added in the future.

![image](https://user-images.githubusercontent.com/1319013/104780075-1577fb80-5735-11eb-8aae-9ca0aea2c01f.png)

**Comment by vitko-bg** [comment]
What about login out users logged in to MC2?
Let's say I am Admin, but some of operators is logged in also to MC2 UI. Can I log the other user out of the MC UI? Or the only way is to disable that user temporary?

**Comment by Ylianst** [comment]
Oh, I see. Yes, in the "My Users" tab, click on the word "User" in the permission column and check "Lock Account". You can immediately unlock it if you like, but that will kick them off. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/104783239-6dfdc780-573a-11eb-8e83-3a72a957e82a.png)
