### ISSUE TITLE
Computer often greyed out in My Devices

### ISSUE THREAD

**Issue by paristotle** [Ylianst/MeshCentral#2175]
I am testing out Messh Central. So far I'm enjoying it. I have one issue with my test computer. Often it will appear greyed out or disconnected in the My Devices portion of the portal. I log in via another support tool and I see the service is running. When I restart the service the computer once again reappears in Mesh Central.
I thought maybe the AV was shutting it down but manage AV does not indicate any intervention on MeshAgent
I thought it might be name resolution but using my other support tool I am able to resolve the FQDN of the server from the client
In the event section of MeshCentral I see connections and disconnections I make to the computer but not agent status
I didn't find a log file in the install directory so I post here now.
What are the next troublshooting steps I can take for this?

**Comment by krayon007** [comment]
Do you know if there is a proxy or reverse proxy between the agent and the server?

**Comment by paristotle** [comment]
Hi. There's no proxy or reverse proxy, but there is a NAT router with a 
port forwarding rule

**Comment by yomono** [comment]
Since it's not behind a proxy or a NAT this could not have a lot of sense, but you can try add the "agentpong" parameter to the config.json file, under the "settings" section.
Something like:
"agentpong" : 30,

**Comment by honzamuzzy** [comment]
> Do you know if there is a proxy or reverse proxy between the agent and the server?

Hi, I have the same problem and I have a server behind reverse proxy. Is there a solution? Thanks

**Comment by si458** [comment]
You can set `agentPing: 28` or `agentPong: 28` to keep the connections open.
