### ISSUE TITLE
Meshcentral don't recognize agentCustomization option in config.json

### ISSUE THREAD

**Issue by fabtra31** [Ylianst/MeshCentral#2176]
Hi, 
I've just install Meshcentral with npm on an Ubuntu 20.4 LTS Server.
I have seen that in the complete config file available on GitHub there is an option called agentCustomization to add commentary and also change the name of the program for the name of the company. But I have an issue with it. In the options of the server, Meshcentral tell me that it doesn't recognize the option.

I can't give you any log beacause it's only a warning and not an error. I use the latest version of meshcentral (0.7.45).

This is my config current config.json file.

{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
	"__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
	"__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
	"settings": {
		"cert": "meshcentral.mycompany.com",
		"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
		"WANonly": true,
		"_LANonly": true,
		"_sessionKey": "MyReallySecretPassword1",
		"_port": 443,
		"_aliasPort": 443,
		"agentPort": 44305,
		"agentAliasPort": 44305,
		"_redirPort": 80,
		"_redirAliasPort": 80
	},
	"domains": {
		"": {
			"_title": "MyServer",
			"_title2": "Servername",
			"_minify": true,
			"_newAccounts": true,
			"_userNameIsEmail": true
		}
	},
	"agentCustomization": {
		"displayName": "Hotline",
		"description": "Agent de prise en main Ãƒ distance de My company",
		"companyName": "My company",
		"serviceName": "",
		"fileName": ""
	},
	"letsencrypt": {
		"__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
		"email": "sav@mycompany.com",
		"names": "meshcentral.mycompany.com",
		"rsaKeySize": 3072,
		"production": false
	}
}

Thanks a lot for your precious help !
Fabien.

**Comment by vitko-bg** [comment]
I am using customization and all works fine for me. The only issue I think it can be in you config file that you should have some values in
"serviceName": "some_value",
"fileName": "some_value",

**Comment by fabtra31** [comment]
Can you give me your config file ???
I will change those values, but I think that changing thoses values will not solve the problem, because it doesn't recognize the options and not the variable of the option. I think the developper will find the solution to my problem quickly ^^.
I suppose that the option is not placed in the right position in the config file (suppose that it will be in setting or something like that :/)

Thanks for your replies !

**Comment by vitko-bg** [comment]
Find the issue in your config file, move
"agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      },

Inside the domain section, somewhere in between those rows

"_minify": true,
"_newAccounts": true,
"_userNameIsEmail": true

Or at the end of
"_userNameIsEmail": true

But it should look like this

"_userNameIsEmail": true, 
"agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      } 

Keep trace on commas "," should not be on the last row within the group. Check JSON formats on Google

**Comment by fabtra31** [comment]
Thanks it's finally working, I've do the suggested modification and I receive a parse error :/ I've checked all the comma and the rows and I've finally found my mistake, and the option is understood by meshcentral ^^.

**Comment by vitko-bg** [comment]
Hi, if you managed to fix the issue, please close it.
Thanks
