### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by VmSupport** [Ylianst/MeshCentral#2177]
Hi, found this in our serverlog..

-------- 1/17/2021, 7:48:42 AM ---- 0.7.45 --------

(node:12515) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. 
Use emitter.setMaxListeners() to increase limit

Its running fine - so not urgent but after some searching it does however is releated to source code.. setMaxListeners

**Comment by Ylianst** [comment]
Interesting, I will look this up. Do you know what version of NodeJS you are running? You can go in the "My Server / Console" tab and type "info". It will show up as "nodeVersion". Thanks.

![image](https://user-images.githubusercontent.com/1319013/105073952-9e947880-5a3c-11eb-8f03-8b489d0f4ec7.png)

**Comment by frankmcc** [comment]
As of yesterday I am getting this same error.   "nodeVersion": "v16.6.1"  "meshVersion": "0.8.99",
Also some of my systems do not show the Desktop tab.  If I clear the Core and upload the default server core, that will fix it, sometimes.  Some I just cannot seem to fix.  Going to try re-installing the agent...

**Comment by polmck087** [comment]
I'm getting the same error as of 5 December, :
![image](https://user-images.githubusercontent.com/31737071/145981662-0f4646ce-4b66-4ea2-8b7f-45007da454b0.png)

-------- 12/5/2021, 5:55:14 AM ---- 0.9.50 --------

(node:4398) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
