### ISSUE TITLE
Feature Request - MeshCentral Router Show tags in groups

### ISSUE THREAD

**Issue by technoicon** [Ylianst/MeshCentral#2178]
It would be nice if meshrouter showed devices like the web interface does.

With devices grouped by "group" and then by "tags".  Also if the groups could be minimised.

with a large number of machines it's hard to sort them in mesh router.

Cheers.

**Comment by si458** [comment]
you can now now select 'collapse groups by default' under settings in meshcentralrouter

as for the tags, thats tricky because you have limited space at the moment, sorry
