### ISSUE TITLE
clickjacking

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshCentral#2180]
Hi,

Currently we do a vulnerabilities scan and we face the following issues.The below 2 ports is meshcentral :

The following pages do not use a clickjacking mitigation response header and contain a clickable event :

https://xxxxx.com:31443/

https://xxxxx.com:31443/terms

May I know for the below issues how can we fix it?

**Comment by Ylianst** [comment]
In the domain section of the config.json, add these lines:

```
      "httpHeaders": {
        "Strict-Transport-Security": "max-age=360000",
        "x-frame-options": "SAMEORIGIN"
      }
```

First one will force HTTPS, second should help with clickjacking. Let me know if that helps.

**Comment by yuling3086** [comment]
Hi 
As I try to access this from another port,so if I put SAMEORIGIN,it will have the following issues.

Access to XMLHttpRequest at 'https://dxxxx:30080/api/remoteControl/admin?deviceId=GfI5CozFB0LuJ92OYz0VDuWqAmrf9n$EAwokyxKwl7Wa2DPTus$Sw97sPqziIVHl' from origin 'https://xxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Ylianst** [comment]
So, you can setup the "x-frame-options" header any way you like. [See for example this web page](https://www.keycdn.com/blog/x-frame-options). You can do:

```
X-Frame-Options: allow-from https://www.example.com/
```

So, set the value that is correct for your site.

**Comment by yuling3086** [comment]
![image](https://user-images.githubusercontent.com/38518937/105121190-a290cb00-5b0e-11eb-86e6-1baae9a4627f.png)

I try to put this in our config.json file.
but after I check we can;t see the x-frame-options


![image](https://user-images.githubusercontent.com/38518937/105121295-ceac4c00-5b0e-11eb-86e9-809b6c0619eb.png)

**Comment by yuling3086** [comment]
If I change my allowFraming to false,then I will able to see the x-frame-options at my header.
But then it create another problems where I will embed  meshcentral in our application as iframe and it become a blank screen as below in our apps.
![image](https://user-images.githubusercontent.com/38518937/105122717-affb8480-5b11-11eb-81b5-6b3192c82e89.png)
