### ISSUE TITLE
Toggle view mode question

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2182]
My situation:
I have been loggedin with the same account on meshcentral server with 2 machines.
1 machine to monitor a pc an external party is working on. I disable input and this is working perfect.
1 machine I use for general use, I login into another remote pc and first have to enable input again (this is ok I guess)
When I click the Toggle view mode the screen on both machines is changed.

I can agree that saving this setting for future is Ok, but changing it in realtime on all sessions (different remote pc's) by the same user was unexpected.

Both machines have different resolutions so I would like to have 1 fullsize and 1 cropped, would it be possible to have this setting based on the current session and not update at both sessions

**Comment by Ylianst** [comment]
Can you confirm your talking about these settings on the right? You don't want them affecting all your open browsers? - thank.

![image](https://user-images.githubusercontent.com/1319013/105071755-d948e180-5a39-11eb-8875-97254d8f95d8.png)

**Comment by Allowee** [comment]
![image](https://user-images.githubusercontent.com/55733884/105073225-11c2dc80-5a87-11eb-8524-9a706e9fbaa8.png)

And indeed it would be handy if it does not affect all open browsers, especially on a different machine

**Comment by Ylianst** [comment]
Oh! That view mode. Got it.

**Comment by Ylianst** [comment]
Ok. Check in the change to Github. Will be in v0.7.49 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.7.49 is out. Let me know if that works for you.

**Comment by Allowee** [comment]
Just tested, perfect!
Thank you!
