### ISSUE TITLE
User Lost 2FA Device, No Way to Reset

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#2185]
We have a user who had 2FA enabled and broke their phone. We want to disable the 2FA from the admin account so that they can move to another device. But we can't find a way to disable 2FA should anything go wrong.

**Comment by Ylianst** [comment]
In the "My Users" tab, click a user, hit "Change Password" and if they are using 2FA, check "Remove all 2nd factor authentication". That should do it. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/105071147-0e086900-5a39-11eb-9c3b-b001da3afef9.png)
