### ISSUE TITLE
Feature Request - Be able to Remove Share with guests for certain users/groups

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#2186]
I would like to be able to remove the share with guest option.

![image](https://user-images.githubusercontent.com/47992409/105122378-358b2e80-5b2a-11eb-85f3-1da86b2ed64c.png)

**Comment by Ylianst** [comment]
You want to remove it server wide? I will add that now.

**Comment by rowds15** [comment]
no if i could disable it per user or group  that would be more beneficial.

**Comment by Ylianst** [comment]
Well, I just checked in the change in GitHub for per domain removal. So add this line to the domain section of the config.json:

```
"GuestDeviceSharing" : false,
```

That will get rid of that feature.

**Comment by LPJon** [comment]
@Ylianst I believe @rowds15 is wanting to control what users or groups are able to use the feature. Not totally disable it or a specific domain. That way you can control your users ability to share the PC's they have access to. This could be useful when you have users which have access to clients that are sensitive and you don't want those users to be able to share that client without having to get someone higher up on the administrative chain.

**Comment by rowds15** [comment]
Hi LPJon, yes that is what i mean. 
My use case is i have some support team members that offer support to other users on the network but i don't want them to share their sessions outside the network.

**Comment by Ylianst** [comment]
Understood. I added the domain wide setting since it was easy to add, required no UI changes. I will have to look into doing something more complex if it's more targeted.

**Comment by Ylianst** [comment]
Just published in MeshCentral v0.7.53, let me know if it works for you.

![MC2-GuestSharingPermission](https://user-images.githubusercontent.com/1319013/105780698-e6783b80-5f25-11eb-9935-bdf5bf0c754d.png)

**Comment by rowds15** [comment]
Thanks Ylian, button still there but does nothing.

**Comment by Ylianst** [comment]
I fixed the button so it will no longer show when you don't have permission to perform guest device sharing. This fix will be in v0.7.60.
