### ISSUE TITLE
Issue with SMTP and office365

### ISSUE THREAD

**Issue by fabtra31** [Ylianst/MeshCentral#2188]
Hi, 
I've tried to put the 2 factor authentication, and it says that it's recommended to enable smtp to be able to do a password recovery. So I check the parameters needed for this function and I add this to my config file : 
"smtp": {
		"host": "smtp.office365.com",
		"port": 587,
		"from": "mail@mycompany.com",
		"__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
		"tls": false,
		"___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
		"_tlscertcheck": false,
		"__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
		"_tlsstrict": true,
		"user": "mail@mycompany.com",
		"pass": "mypassword"
	},

Meshcentral says that the SMTP is working as normal, but when I want to login I need a mail validation. I've lauch meshcentral manually to see whats happening and it seems that there is some exeptions or security parameters that block sending mails with mesh. 
The error that came back on my console is Error: Message failed: 554 5.2.0, I've check on microsoft official documentation but I can't where the problem is.

Many thanks,
Fabien.

**Comment by LPJon** [comment]
> 
> 
> Hi,
> I've tried to put the 2 factor authentication, and it says that it's recommended to enable smtp to be able to do a password recovery. So I check the parameters needed for this function and I add this to my config file :
> "smtp": {
> "host": "smtp.office365.com",
> "port": 587,
> "from": "[mail@mycompany.com](mailto:mail@mycompany.com)",
> "**tls**": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
> "tls": false,
> "_**tlscertcheck**": "When set to false, the TLS certificate of the SMTP server is not checked.",
> "_tlscertcheck": false,
> "**tlsstrict**": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
> "_tlsstrict": true,
> "user": "[mail@mycompany.com](mailto:mail@mycompany.com)",
> "pass": "mypassword"
> },
> 
> Meshcentral says that the SMTP is working as normal, but when I want to login I need a mail validation. I've lauch meshcentral manually to see whats happening and it seems that there is some exeptions or security parameters that block sending mails with mesh.
> The error that came back on my console is Error: Message failed: 554 5.2.0, I've check on microsoft official documentation but I can't where the problem is.
> 
> Many thanks,
> Fabien.

Is your "from" setting and your "user" setting the same in the actual config? "_tlsstrict": true, should be `"tlsstrict": true,` . The "from" and "user" settings should match perfectly and should only contain the email address example: `jondoe@mycompany.com`

I personally have had many issues getting emails sent to ANY microsoft email accounts outside of MeshCentral (Like an actual SMTP email server). You could have everything perfect and it could still get refused just based on how many times you tried to deliver it or what email client you are using. However, the error code you provided seems to be revolving around how many times a delivery attempt was made in a period of time. So waiting a while (few days) and trying again may be just the thing you need too. 

This article may help:
https://stackoverflow.com/questions/60406094/transaction-failed-the-server-response-was-5-2-0-storedrv-submission-exception

**Comment by fabtra31** [comment]
Hi, 
Thanks for you reply but I've found a simple solution : change my SMTP provider. I've change for an OVH SMTP solution and it works perfectly now. Microsoft borred me with all those useless security policies... Anyway all the SMTP system for the account authentication and the password reset works nice now.

I close the issue now.

Fabien.
