### ISSUE TITLE
Feature Request - Option to force Linux "Terminal" to "Login Shell" to force a user login

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2189]
I have a lot of Linux boxes that are command-line only. I would like to force the "Login Shell" option to those boxes so that I can keep track of user actions in those boxes. I don't need to target "Users" or "Groups" so a domain wide option would work. Is there already a way to do this or would it need to be added?

**Comment by Ylianst** [comment]
Good idea, working on it now.

**Comment by Ylianst** [comment]
Just check it into GitHub. Starting with v0.7.49 you can add this to the domain section of the config.json:

```
      "terminal": {
        "linuxshell": "login"
      }
```

The will remove other options and default to "login" shell on Linux devices. The options are "any", "root", "user" and "login".

Let me know if that works.

**Comment by LPJon** [comment]
> 
> 
> Just check it into GitHub. Starting with v0.7.49 you can add this to the domain section of the config.json:
> 
> ```
>       "terminal": {
>         "linuxshell": "login"
>       }
> ```
> 
> The will remove other options and default to "login" shell on Linux devices. The options are "any", "root", "user" and "login".
> 
> Let me know if that works.


So to be clear. I can choose which options are displayed/usable by setting "any", "root", "user" and "login" and it will only apply to the Linux based agents? If so this is awesome!

**Comment by Ylianst** [comment]
The "linuxshell" option only applies to Linux devices. No changes for Windows.

**Comment by Ylianst** [comment]
MeshCentral v0.7.49 is out, let me know if that works for you.

**Comment by LPJon** [comment]
Getting this error on MeshCentral Server startup

`WARNING: Unrecognized configuration option "terminal".`

Under what context should this setting be listed in the config.json?

**Comment by LPJon** [comment]
There are no errors now but I'm still I'm not seeing it working. All options are still available. Any suggestions?

**Comment by LPJon** [comment]
Another correction: **It's working perfectly**
I made a mistake and essentially didn't restart MeshCentral after adding the setting to config.json.
Great Job and thank you for this feature! You guys have both been awesome!
