### ISSUE TITLE
Feature Request - Show "Firewall" status under "General" Tab next to "Antivirus" and to send notifications if either of these are in a "RED Letter" status.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2191]
Ok. I know I keep asking for features. I hope I'm not upsetting anyone. You all are just so very good at being responsive.

I would really like to be able to monitor my customers basic security on their computer systems and get notifications when this basic security is in a degraded state. I don't need to be able to control the state with this feature, just be notified so I can promptly respond to the customer. Might also be nice to be able to turn this feature on or off with a "Send Notifications" checkbox under this same tab of the device.

**Comment by Ylianst** [comment]
Bryan will have to look at pulling firewall status.

**Comment by krayon007** [comment]
I added support for this... I can now collect AntiVirus, Firewall, and Windows Update status from Windows Security Center, and I registered for the OS change event, and  send this information to the server. Each of these three items will report either "OK", "WARNING", "PROBLEM", or "UNKNOWN". @Ylianst just needs to update the server UI to reflect this data. It should be available in an upcoming release. I only report this data if the API query exists and is successful, so that probably means this won't work on Windows Server, since Windows Security Center I don't think exists on Windows Server.

**Comment by LPJon** [comment]
> 
> 
> I added support for this... I can now collect AntiVirus, Firewall, and Windows Update status from Windows Security Center, and I registered for the OS change event, and send this information to the server. Each of these three items will report either "OK", "WARNING", "PROBLEM", or "UNKNOWN". @Ylianst just needs to update the server UI to reflect this data. It should be available in an upcoming release. I only report this data if the API query exists and is successful, so that probably means this won't work on Windows Server, since Windows Security Center I don't think exists on Windows Server.

This is Awesome! Even if it doesn't work on Windows Server that still cuts down a lot of work. Thank you @krayon007, you're awesome.

**Comment by LPJon** [comment]
@Ylianst I wanted to make a slight change to this request. When producing notifications, it would be best if one email was sent with a list of affected clients/agents in a given Mesh Device Group in a programmable interval. So like every 24hrs or 12hrs or 1hrs if possible. Please let me know if I'm not being clear enough on that.

**Comment by Ylianst** [comment]
Thanks for Bryan's latest changes, you can now see the Windows Security Center state on MeshCentral. The state is real-time so if you turn on/off the firewall, it will show up on the web page immediately.

![MC2-WindowsSecurityCenter](https://user-images.githubusercontent.com/1319013/105754342-cb460580-5efe-11eb-97cf-590d80f33e63.png)

**Comment by LPJon** [comment]
@Ylianst This is great! It's also working. Are you still working on the notifications part of this? Was really hoping for the notifications or at least badges maybe.

**Comment by LPJon** [comment]
The primary part of this works great! So im going to close this. The notifications is a want more than a need. If you want add that feature on later when you have time thats great but im happy with this too. Thanks again for all of your hard work
