### ISSUE TITLE
Feature Request - When "Prompt for user consent" is checked the user can set a pre-determined amount of time to allow the connection WITHOUT consent.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2192]
I had a customer ask me if they could just set a pre-determined amount of time to allow me to remote with their system so they didn't have to keep answering "Yes" to a dialogue box each time I needed to restart. I'm aware that we can just turn this feature off and connect however, I would like to place some control into my customers hands. Especially when my support staff should not be able to access our customers computer at any time they choose. Is it possible to allow the customer to choose a specific amount of time for the technician to access their computer and then after that time has expired require their consent again?

**Comment by LPJon** [comment]
Exactly!

**Comment by si458** [comment]
this is now implemented per domain - https://github.com/Ylianst/MeshCentral/issues/4154#issuecomment-1162690472
```
      "consentMessages": {
        "consentTimeout": 30,
        "autoAcceptOnTimeout": true
      },
```
