### ISSUE TITLE
Features Request: Apps restrictions based on certain user group

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshCentral#2193]
Hi,

I would like to know whether meshcentral able to have apps restrictions based on certain user group.
For example: user group A is just able to access apps A,B,C while user group B is just able to access to apps A,B,C,D?

thanks

**Comment by Ylianst** [comment]
What apps are your referring to? The limiting remote desktop to loading nodepad.exe? In that case no, no sure limitation.

**Comment by yuling3086** [comment]
For example restrict the user to open notepad.exe.

**Comment by Ylianst** [comment]
Ok. No, there is not feature right now to do such restrictions.

**Comment by yuling3086** [comment]
Can we request for this features?

**Comment by Ylianst** [comment]
Not something that is easy to do. You can make a request for it and Bryan can look at it, but it not sure how we would be about implementing it.
