### ISSUE TITLE
webserver.js -> GetAllMeshWithRights returns empty array

### ISSUE THREAD

**Issue by sangrae** [Ylianst/MeshCentral#2194]
Hi.
I found little problem in tesing WOL.
I think m.rights should be m.rights[user._id].rights

Always thank you for your work.

webserver.js -> GetAllMeshWithRights
![image](https://user-images.githubusercontent.com/1788117/105287707-085a8100-5bfb-11eb-9fc5-f8d45910e136.png)

**Comment by Ylianst** [comment]
Thanks for reporting this, checking now.

**Comment by Ylianst** [comment]
Thanks! Your right. I fixed it by replacing `m.rights` with `user.links[i].rights`, but it's the same result. This will be in MeshCentral v0.7.52. Let me know if that works for you.

**Comment by sangrae** [comment]
it works. Thanks!
