### ISSUE TITLE
File size restriction on upload or download from client/device

### ISSUE THREAD

**Issue by tprinslo** [Ylianst/MeshCentral#2195]
Currently users of Meshcentral can have quotas on how much data they can store locally on the server and this works great.
Request: To be able to set a size limit on transferring files (upload and download)
It would also be nice if the event logging the upload download file name can include the size of the file in the event message. 
Thank you for all your hard work on a great project

**Comment by Ylianst** [comment]
I just checked in improved events for uploads that includes the file size and added the download events that was missing and that also includes the file size. For size limits, that is more work. Is that really needed? Someone you upload multiple smaller files and assemble them on the remote device or better yet, the instruct the remote device to download a big file using a different service. Just checking - Thanks.

**Comment by tprinslo** [comment]
Thank you Ylianst
New event message will be fine. The size issue is for when a technician would "hog" the bandwidth by not playing nice but we should be able to manage that

Regards
