### ISSUE TITLE
sendgrid emails no longer sending reliably in 0.7.48

### ISSUE THREAD

**Issue by kevinh-csalabs** [Ylianst/MeshCentral#2198]
Sending an email to the user from the users > email button or via the server console only works intermittently now. I sent 4 messages from the user page and 3 from the console, and only 1 message (from email page) ever made it to sendgrid's activity feed. Nothing seems to show up in the logs and the console indicates it was done.

**Comment by Ylianst** [comment]
I am going to take it easy for the next few days, v0.7.48 release was intense. However for this one, the way to debug this is to go in the "My Server / Trace" tab and enable "Email / SMS" tracing. You can then open another browser window and in the "My Server / Console" tab, use the email command to test sending emails. Let me know what you see in the tracing tab.

I may need to add email retry and added error messages.

**Comment by kevinh-csalabs** [comment]
Understandable - everyone needs a break. This isn't critical (the cloudflare websocket disconnect is more of a headache than this honestly).

In any case the server email trace didn't turn anything up. See attached.
Please let me know next steps and I'm happy to troubleshoot further!
![email command](https://user-images.githubusercontent.com/72226237/105507405-fec72c80-5c7f-11eb-9a6a-d6d708b74bd7.PNG)
![no tracing results](https://user-images.githubusercontent.com/72226237/105507408-ff5fc300-5c7f-11eb-908d-ec8f56e7a997.PNG)

**Comment by Ylianst** [comment]
Ok, thanks for checking that. I will add tracing messages for SednGrid and see if I can't do auto-retry, etc.

**Comment by Ylianst** [comment]
Ok, your correct. SendGrid code had issues and I saw the same problems you where seeing. I pushed fixes on GitHub. Fixes will be in MeshCentral v0.7.52 when it's next published. Once you update, let me know if it works.

**Comment by kevinh-csalabs** [comment]
looks to be fixed (tested in v0.7.53) all test emails sent as expected and showed in server trace.
