### ISSUE TITLE
Output of remote command - question

### ISSUE THREAD

**Issue by dtphap** [Ylianst/MeshCentral#2200]
When I issue a command through meshctrl.js the command get executed on the remote device but the output of command still invisible. How can we get the output of remote command (stdout) on the site from where we issued it?
Example: 
**Current output**
D:\Soft\mesh\node_modules\meshcentral>node .\meshctrl.js --url wss://somemeshcentralsite  --loginuser myuser --loginpass mypass runcommand --run whoami --id mydeviceID
OK

**Desirable output:**
D:\Soft\mesh\node_modules\meshcentral>node .\meshctrl.js --url wss://somemeshcentralsite  --loginuser myuser --loginpass mypass runcommand --run whoami --id mydeviceID
azureuser

**Comment by tiagogbarbosa** [comment]
Sorry to revive, but, any progress? or any way to do this?
Ty

**Comment by Gateworks** [comment]
Looks like this has been asked for several times - any update?

**Comment by si458** [comment]
RELATED/DUPLICATE #5203
