### ISSUE TITLE
Clickonce instead Mesh Router

### ISSUE THREAD

**Issue by 55code** [Ylianst/MeshCentral#2201]
Hello, 
Congratulations for excepcional work with MeshCentral, it is very helpful to manage my small environment. 

Can I replace temporarily Mesh Router by Clickonce as it was before? I really like to connect via RDP from any Windows PC with Internet Explorer without any additional download as I do with Clickonce. I'm not always use my desktop to access another computer, so it will help me a lot. 

There's anyway to achieve this?

Thank you very much!

**Comment by Ylianst** [comment]
Hi. Apologies but sadly no. Clickonce support was removed from MeshCentral a while back. It was a pain to maintain, had limited browser support and did not work cross-platform (macOS), so I was happy to ditch it. Indeed, you have to download MeshCentral Router, run it, hit "Install.." it it should work on any OS.
