### ISSUE TITLE
Run commands can't execute, already busy - Question

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2202]
Hi,

I try to send a basic command (cmd.exe) through the Action button just to discover this functionality.
When I do that, I find the message  "_Run commands can't execute, already busy_" in the console.
Why do I have that please ?

Just to be sure that I didn't make any mistakes : I click the " _Actions Button ---> Operation ---> Run Commands_"  then I choose the "_Windows Command Prompt", "Run as agent"_ and I type "_cmd.exe_". 
Is this the right way to use it ? Otherwise how does that work ?

Thank you in advance for your reply.

**Comment by krayon007** [comment]
the commands you "run" need to be self-contained tasks that don't require input... If you run `cmd.exe` that spawns a shell, and never comes back, becuase something needs to tell it to exit... Because it never comes back, is why you are getting "already busy", when you try to run other tasks, because the 'cmd.exe' task is still running...

**Comment by Ylianst** [comment]
Maybe we should auto-kill the process after one minute? Community suggestions are welcome.

**Comment by elpibedeoro** [comment]
> 
> 
> the commands you "run" need to be self-contained tasks that don't require input... If you run `cmd.exe` that spawns a shell, and never comes back, becuase something needs to tell it to exit... Because it never comes back, is why you are getting "already busy", when you try to run other tasks, because the 'cmd.exe' task is still running...

Is the shell supposed to spawn on the remote client or anywhere else ? I ask that because on the remote client, nothing spawned.
Thank you.

**Comment by Ylianst** [comment]
Bryan will have to validate this, but I think he hides it so it's not visible to the remote user.

**Comment by elpibedeoro** [comment]
Hi,
Ok I've got this.
Effectively, like in this case, I find your idea very attractive because it could be very useful to kill the process after a timeout.
I suppose that this could be done also through the task manager ?
Thank you.

**Comment by krayon007** [comment]
> Is the shell supposed to spawn on the remote client or anywhere else ? I ask that because on the remote client, nothing spawned.
> Thank you.

When you say nothing is spawned, did you check the task manager, or are you just referring to what is visible on the desktop? The process does indeed spawn, it's just that by default it is running in the context of LocalSystem, using an impersonation token of the logged in user, (if you choose user), or as LocalSystem, if you do not... These types of shells will NOT be visible on the user desktop. I do have a different technique to spawn a shell onto the user's desktop session, but that isn't what's used for the run command.

**Comment by elpibedeoro** [comment]
Thank you for your answer.
I was referring to the "visible" part but now I've understood that this functionality is not supposed to be visible on the user desktop. Just tried one more time and after have run the command it appears in the task manager.
Thank you for your help.

**Comment by redog** [comment]
I have this issue with 1.0.97

**Comment by nafai** [comment]
Still an issue in 1.1.22, can be triggered with any accidental input handling, such as:
```
set /p input=Test?
echo Done
```
Or something like forgetting to pass /f to REG ADD. Any timeout value would be better than indefinitely hanging.

**Comment by si458** [comment]
@nafai yes I've spotted this too recently. Please open a new issue. I'm thinking about adding a timeout value to config.json Then if command is so running after so long kill the current process

**Comment by DaanSelen** [comment]
> @nafai yes I've spotted this too recently. Please open a new issue. I'm thinking about adding a timeout value to config.json Then if command is still running after so long kill the current process

Did you manage to complete this idea?

**Comment by si458** [comment]
@DaanSelen no sadly not but will look into it,
just follow https://github.com/Ylianst/MeshCentral/issues/6076 for updates :)
