### ISSUE TITLE
Enhancement: Terminal access on the mobile version

### ISSUE THREAD

**Issue by TotallyNotElite** [Ylianst/MeshCentral#2204]
With the recent updates to the mobile page - including an updated remote desktop experience - making the mobile version of MeshCentral a first class citizen, there's only one thing I've noticed that's missing: A mobile terminal

I apologize if this has been asked for before, but I was not able to find anything after a short search in the GitHub Issues.

I've noticed that I absolutely hate having to bother with Android apps that try to provide a better SSH experience by providing things such as single click connection, ssh key management, etc. while it would be much more convenient to use MeshCentral instead, just like I do on Desktop. The advantage of MeshCentral being that all devices are synced, I don't have to bother with setting up everything again on another device and there is only a single password or OAuth login I need to worry about.

As of this point I look after 3 small scale deployments of MeshCentral and other users of those deployments also sometimes want to quickly address an issue or run a few commands on mobile. Does anyone else have a similar experience?

**Comment by yomono** [comment]
I also noticed this. It would be nice to have

**Comment by Ylianst** [comment]
Just added terminal support on the mobile web site in MeshCentral v0.8.5. Let me know if it works for you.

![MC2-MobileTerminal](https://user-images.githubusercontent.com/1319013/113947924-94bf1d80-97c0-11eb-86f7-36828dc01f87.png)

**Comment by TotallyNotElite** [comment]
Hm, it appears to crash or freeze the agents for a few minutes when I type something and then delete the text again. Just happened to 3 different Linux devices in a row 🤔 

Meshcentral version: Latest at the time of comment, on mobile, can't check
Browser: Firefox on Android
