### ISSUE TITLE
MC Router on MacOS (intel)

### ISSUE THREAD

**Issue by thelarz** [Ylianst/MeshCentral#2205]
Hello MeshCentral team,

I'm having an issue with MeshCentral router and MacOS Big Sur.

Download/Install seems to work perfectly.  
I logged into my meshCentral server and see a list of active remote computers. 
I created a new Map and selected SSH protocol.

![image](https://user-images.githubusercontent.com/345964/105654209-20443600-5e83-11eb-841e-71e50c5df4e6.png)

Clicking SSH and entering (unsure which account I'm supposed to enter) for user, I get the following message.

![image](https://user-images.githubusercontent.com/345964/105654302-5681b580-5e83-11eb-9ded-c23c807ab404.png)

Can you help solve this issue?

Thanks

**Comment by Ylianst** [comment]
It looks like the remote machine is not listening on port 22. Is that possible?

**Comment by vithusel** [comment]
I can confirm this is the case for me as well. 

I tried a test. I was able to SSH into a server directly with no issues, however trying to SSH with mesh router gave me the same error. Trying the same thing from a windows machine worked without issue. I would add that i also tried connecting to a webpage using the same method but that didnt work either on the mac. Perhaps theres a firewall issue? More then happy to provide remote access for you to test it out. 

Kind Regards,

Vit

**Comment by vithusel** [comment]
Thanks, Just for a bit of additional info. Im running MacOS Big Sur v11.1.  
My MeshRouter version is 0.0.2 (1) 
When trying to access a webpage i get the error message ERR_CONNECTION_RESET (on chrome) 
Let me know if theres anything else you want to know about my setup.

**Comment by thelarz** [comment]
Thanks @Ylianst. As well, let me know if i can provide any additional info. Love this feature.

**Comment by TiaPcom** [comment]
Me too.. mappings is not working.

**Comment by Ylianst** [comment]
I just tested it and indeed, it's not working. Looking into it now.

**Comment by Ylianst** [comment]
Ok. MeshCentral Router for MacOS v0.0.3 is out on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html) and in MeshCentral v0.7.59. This should fix it. Let me know if it works.

**Comment by thelarz** [comment]
Hello and Thank you Ylianst, I can confirm the macOS version 0.0.3 is working.

**Comment by TiaPcom** [comment]
thank you Ylianst, works great!

**Comment by Smiley-k** [comment]
when trying to click on the ssh button to open a terminal, a browser opens.

version meshrouter  0.0.4

**Comment by si458** [comment]
> when trying to click on the ssh button to open a terminal, a browser opens.
> 
> version meshrouter  0.0.4
> 
> 

Sound like your browser has the default open handler for ssh
If that isn't the case, try opening a separate issue in the meshcentralrouter repo
https://github.com/Ylianst/MeshCentralRouter
