### ISSUE TITLE
Safemode : a way to set a count time ?

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2206]
Hi,

I've tried to push a safemode command to a remote computer through the console.
Everything works great but I'd like to know if there was a way to reboot in normal way after a certain numbers of times ?
For example : safemode -n 1 so that it reboots in normal way at the next boot.

It'd be cool just in case a network problem occurs and the user is not administrator or he is not just comfortable with the computer... that would be easier to tell him "just reboot" instead of giving him a procedure.

Thank you.
(v. 0.7.52)

**Comment by si458** [comment]
sadly the is no way of doing this,
when you run `safemode status` in the console tab it will tell u what mode ur in but also what the next mode on reboot will be
so if your in normal mode, you can run `safemode on` to tell it to boot into safe mode next time round
and if in safe mode run `safemode off` to tell it to boot into normal mode next time round

```
> safemode
Proper usage: safemode (ON|OFF|STATUS)
> safemode status
Current: NORMAL, NextBoot: NORMAL
> safemode on
> safemode status
Current: NORMAL, NextBoot: SAFE_MODE_NETWORK
> safemode off
> safemode status
Current: NORMAL, NextBoot: NORMAL
```
