### ISSUE TITLE
Favourite "star" filtering does not work anymore 

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2207]
Looks like filtering by * is not working anymore.
MC2 0.7.48 running on Debian 8 behind NGINX reverse proxy.

Checked the documentation and issues related and according to the picture below it should work but does not:

![image](https://user-images.githubusercontent.com/59362521/105694975-6d62ef00-5ef9-11eb-829c-14e4dfaad585.png)

**Comment by petervanv** [comment]
it doesn't work in 0.7.52 too

**Comment by yomono** [comment]
Now you can use the dropdown filter:
![image](https://user-images.githubusercontent.com/31445936/105724496-af466200-5f06-11eb-9031-59ffe2b6272b.png)

**Comment by vitko-bg** [comment]
Thanks!!!!!
Feeling myself st*pid :) did not realized the change.
Thanks again.
