### ISSUE TITLE
Settings for Default New User permissions would be safer to have

### ISSUE THREAD

**Issue by Kodangi** [Ylianst/MeshCentral#221]
Currently, when NewAccounts is true, any internet user can create account and start sharing.

It would be safer have some settings for Administrator to set what is the default new user permissions.

If Administrator wants any new users to just connect only or share too (able to create new group, add system, share to any user)

**Comment by Ylianst** [comment]
Agreed. I will add this next time I can.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.4-e with new "newAccountsRights" setting in the domain section of config.json. You can now do:

```
{
  "settings": {
    "Port": 4430,
  },
  "domains": {
    "": {
      "title": "TestServer",
      "newAccountsRights": [ "nonewgroups", "notools" ]
    }
  }
}
```
Once set, all new accounts will have the "nonewgroups" and "notools" restrictions. In addition, a few weeks back I changed the default to not allow account creation on the login screen. You have to add:

`"newAccounts": true,`

In the domain section if you want to allow this. Can you check if this is ok for you? Thanks.

**Comment by Kodangi** [comment]
Thanks, verified - both cases - perfect.
Admins can setup the default user creation behavior, and if needed they can enable those two feature by default for all.

**Comment by Ylianst** [comment]
I will close this issue. I will note that you can speficy as default rights any of the following:

`fulladmin, serverbackup, manageusers, serverrestore, fileaccess, serverupdate, locked, nonewgroups, notools`

However, I am not sure you would want to use any of these except for nonewgroups and notools. It's safer to manually grant some of these permissions.
