### ISSUE TITLE
[Documentation] NGINX port forwarding does not work with default SELinux settings

### ISSUE THREAD

**Issue by sebtombs** [Ylianst/MeshCentral#2210]
The NGINX reverse proxy configuration shown in the documentation does not work if SELinux is on unless httpd_can_network_relay is set. If it isn't, one gets a 502 bad gateway in the browser and a permissions error shown in the logs.

It took me a while to find out what was causing this behaviour so, in order to assist others, may be worth adding to the documentation re NGINX, perhaps as a comment at the top of the .conf file.

Suggest:

`# Note: With SELinux, NGINX reverse proxy requires 'setsebool -P httpd_can_network_relay 1'`
`# Caution: httpd_can_network_relay only allows certain ports`
`#               Confirm you are using ports from this subset in Mesh Central`
`#               If you want to use a different port then you will need to add it to http_port_t`

**Comment by dinger1986** [comment]
@si458 wheres best to add this in the docs do you think?

**Comment by dinger1986** [comment]
https://github.com/Ylianst/MeshCentral/pull/5710
