### ISSUE TITLE
Enhacement: Regain same console session after disconnect

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#2211]
Hi, one more time.
If i'm using the terminal connection, and I disconnect from it, i lost all my work. When I reconnect, it start a new session.
My workaround to this is using tmux, so I reattach to the same tmux session.
But it would be nice to be able to just connect and regain control to the same sesion (like you normally do on "desktop" connection)

**Comment by Ylianst** [comment]
Not sure how we would do that. It's a bit like when you SSH into a device, once disconnected you can't open a new SSH and get the same session. Unless someone has more precise ideas, probably not something we can do.

**Comment by yomono** [comment]
In that case, I will close this issue. 
Is not that critical. After all, using tmux is not a big deal and I can accomplish my goal.
Thanks for the answer
