### ISSUE TITLE
BUG - FreeBSD Agent will not start on startup with OPNSense when using the binary

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2212]
This is strange. The agent functions properly but refuses to start at startup with OPNSense which is based around HardenedBSD. If I login to the Firewall (OPNSense) and manually start the agent after a reboot it connects without any problems. But it refuses to start at startup even when using the system method of "service meshagent enable". 

I should note that I'm using a customized agent but after install of the agent it is present in the `/etc/rc.conf.local` file. So it should be starting on boot. Any ideas anyone?

**Comment by krayon007** [comment]
Interesting... I was able to reproduce this issue with pfSense and OPNsense, but not with regular FreeBSD...  I'll see if I can dig around and figure out why it's not auto starting on pfSense/OPNsense.

**Comment by krayon007** [comment]
> This is strange. The agent functions properly but refuses to start at startup with OPNSense which is based around HardenedBSD. If I login to the Firewall (OPNSense) and manually start the agent after a reboot it connects without any problems. But it refuses to start at startup even when using the system method of "service meshagent enable".
> 
> I should note that I'm using a customized agent but after install of the agent it is present in the `/etc/rc.conf.local` file. So it should be starting on boot. Any ideas anyone?

ok, I think  I found the culprit.. Go to `/usr/local/etc/rc.d` folder.
You'll find two files, "meshagent" and "meshagent.sh".. (Or whatever you named your agent...)
The one with the .sh extension doesn't have execute permission... chmod 770 that file, and reboot and tell me if that works.

I remember I added the .sh file later, because I think pfSense/OPNsense looked for the file with the .sh extension, whereas vanilla FreeBSD did not... I think when I wrote the changes, I forgot to include the execute permission.

**Comment by LPJon** [comment]
> 
> 
> > This is strange. The agent functions properly but refuses to start at startup with OPNSense which is based around HardenedBSD. If I login to the Firewall (OPNSense) and manually start the agent after a reboot it connects without any problems. But it refuses to start at startup even when using the system method of "service meshagent enable".
> > I should note that I'm using a customized agent but after install of the agent it is present in the `/etc/rc.conf.local` file. So it should be starting on boot. Any ideas anyone?
> 
> ok, I think I found the culprit.. Go to `/usr/local/etc/rc.d` folder.
> You'll find two files, "meshagent" and "meshagent.sh".. (Or whatever you named your agent...)
> The one with the .sh extension doesn't have execute permission... chmod 770 that file, and reboot and tell me if that works.
> 
> I remember I added the .sh file later, because I think pfSense/OPNsense looked for the file with the .sh extension, whereas vanilla FreeBSD did not... I think when I wrote the changes, I forgot to include the execute permission.

@krayon007 In my case I do not see a .sh file in the folder at all anywhere.....sure that its `/usr/local/etc/rc.d`? However the agent binary is there and does have execute permissions.

**Comment by krayon007** [comment]
> > > This is strange. The agent functions properly but refuses to start at startup with OPNSense which is based around HardenedBSD. If I login to the Firewall (OPNSense) and manually start the agent after a reboot it connects without any problems. But it refuses to start at startup even when using the system method of "service meshagent enable".
> > > I should note that I'm using a customized agent but after install of the agent it is present in the `/etc/rc.conf.local` file. So it should be starting on boot. Any ideas anyone?
> > 
> > 
> > ok, I think I found the culprit.. Go to `/usr/local/etc/rc.d` folder.
> > You'll find two files, "meshagent" and "meshagent.sh".. (Or whatever you named your agent...)
> > The one with the .sh extension doesn't have execute permission... chmod 770 that file, and reboot and tell me if that works.
> > I remember I added the .sh file later, because I think pfSense/OPNsense looked for the file with the .sh extension, whereas vanilla FreeBSD did not... I think when I wrote the changes, I forgot to include the execute permission.
> 
> @krayon007 In my case I do not see a .sh file in the folder at all anywhere.....sure that its `/usr/local/etc/rc.d`? However the agent binary is there and does have execute permissions.

How did you install the agent? When installing on pfSense/opnsense, it should place the binary in /usr/local/mesh_services/xxxxx and the startup script will go into /usr/local/etc/rc.d

**Comment by krayon007** [comment]
You can try doing a clean install using the binary installer? In my test, I selected binary installer for BSD on the server, and copied the wget command, and changed it to curl when pasting it into my opnsense machine... I just needed to add:
 `--insecure`

**Comment by LPJon** [comment]
> 
> 
> > > > This is strange. The agent functions properly but refuses to start at startup with OPNSense which is based around HardenedBSD. If I login to the Firewall (OPNSense) and manually start the agent after a reboot it connects without any problems. But it refuses to start at startup even when using the system method of "service meshagent enable".
> > > > I should note that I'm using a customized agent but after install of the agent it is present in the `/etc/rc.conf.local` file. So it should be starting on boot. Any ideas anyone?
> > > 
> > > 
> > > ok, I think I found the culprit.. Go to `/usr/local/etc/rc.d` folder.
> > > You'll find two files, "meshagent" and "meshagent.sh".. (Or whatever you named your agent...)
> > > The one with the .sh extension doesn't have execute permission... chmod 770 that file, and reboot and tell me if that works.
> > > I remember I added the .sh file later, because I think pfSense/OPNsense looked for the file with the .sh extension, whereas vanilla FreeBSD did not... I think when I wrote the changes, I forgot to include the execute permission.
> > 
> > 
> > @krayon007 In my case I do not see a .sh file in the folder at all anywhere.....sure that its `/usr/local/etc/rc.d`? However the agent binary is there and does have execute permissions.
> 
> How did you install the agent? When installing on pfSense/opnsense, it should place the binary in /usr/local/mesh_services/xxxxx and the startup script will go into /usr/local/etc/rc.d

@krayon007 I Installed the binary version with the wget command supplied by the MeshCentral server originally. I think I found the issue though. The directory in the `/usr/local/mesh_services/` folder has a space in the name, `Laptop Pitstop`. Could this be it? I have already tried several clean install installs. The issue persists. Does curl do something different?

**Comment by krayon007** [comment]
By the way, are you sure the /usr/local/etc/rc.d/meshagent is a binary, and isn't a script file? It looks like only pfsense put the .sh file there... So I have to fix my opnsense detection... (or change it to always write the .sh file there for bsd)

**Comment by LPJon** [comment]
> 
> 
> By the way, are you sure the /usr/local/etc/rc.d/meshagent is a binary, and isn't a script file? It looks like only pfsense put the .sh file there... So I have to fix my opnsense detection... (or change it to always write the .sh file there for bsd)

Positive its the binary.

**Comment by krayon007** [comment]
> > By the way, are you sure the /usr/local/etc/rc.d/meshagent is a binary, and isn't a script file? It looks like only pfsense put the .sh file there... So I have to fix my opnsense detection... (or change it to always write the .sh file there for bsd)
> 
> Positive its the binary.

What's the length of that file?

**Comment by LPJon** [comment]
> 
> 
> > > By the way, are you sure the /usr/local/etc/rc.d/meshagent is a binary, and isn't a script file? It looks like only pfsense put the .sh file there... So I have to fix my opnsense detection... (or change it to always write the .sh file there for bsd)
> > 
> > 
> > Positive its the binary.
> 
> What's the length of that file?

@krayon007 `4566936`

**Comment by krayon007** [comment]
I have a hunch that your `/usr/local/etc/rc.d/LaptopPitstopAgent` file is < 600 bytes.. If that's the case, do the following:
```
cp /usr/local/etc/rc.d/LaptopPitstopAgent /usr/local/etc/rc.d/LaptopPitstopAgent.sh
chmod 770 /usr/local/etc/rc.d/LaptopPitstopAgent.sh
```

**Comment by krayon007** [comment]
Oh, and try the install with the binary installer, not the regular binary... I think the regular install script doesn't work with pfsense/opnsense.

**Comment by krayon007** [comment]
Just for clarification, when you select binary installer, and freebsd x86-64, there is still a wget link, but it is a link to download the binary installer, rather than a giant  install script...

**Comment by LPJon** [comment]
> 
> 
> Just for clarification, when you select binary installer, and freebsd x86-64, there is still a wget link, but it is a link to download the binary installer, rather than a giant install script...

That is 100% correct...

**Comment by krayon007** [comment]
Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...

**Comment by LPJon** [comment]
> 
> 
> Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...

@krayon007 LOL...I just applied that fix and restarted the firewall. Will post what I come up with.

**Comment by krayon007** [comment]
> > Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...
> 
> @krayon007 LOL...I just applied that fix and restarted the firewall. Will post what I come up with.

ok, I found the real solution for OPNsense...
go to the following folder:
`/usr/local/etc/rc.syshook.d/start`

You need to add a script to this folder... The easiest way is to just copy `90-cron` into `50-LaptopPitstopAgent`
Then edit the file and change:
`configctl cron restart` 
to
`service LaptopPitstopAgent start`
and save, chmod 770, and reboot.

I'll fix the installer to do this for opnsense.

**Comment by LPJon** [comment]
> 
> 
> > > Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...
> > 
> > 
> > @krayon007 LOL...I just applied that fix and restarted the firewall. Will post what I come up with.
> 
> ok, I found the real solution for OPNsense...
> go to the following folder:
> `/usr/local/etc/rc.syshook.d/start`
> 
> You need to add a script to this folder... The easiest way is to just copy `90-cron` into `50-LaptopPitstopAgent`
> Then edit the file and change:
> `configctl cron restart`
> to
> `service LaptopPitstopAgent start`
> and save, chmod 770, and reboot.
> 
> I'll fix the installer to do this for opnsense.

@krayon007 I can confirm with you that previous solution did not work. I will report in just a few about the latest solution you provided.

**Comment by LPJon** [comment]
> 
> 
> > > > Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...
> > > 
> > > 
> > > @krayon007 LOL...I just applied that fix and restarted the firewall. Will post what I come up with.
> > 
> > 
> > ok, I found the real solution for OPNsense...
> > go to the following folder:
> > `/usr/local/etc/rc.syshook.d/start`
> > You need to add a script to this folder... The easiest way is to just copy `90-cron` into `50-LaptopPitstopAgent`
> > Then edit the file and change:
> > `configctl cron restart`
> > to
> > `service LaptopPitstopAgent start`
> > and save, chmod 770, and reboot.
> > I'll fix the installer to do this for opnsense.
> 
> @krayon007 I can confirm with you that previous solution did not work. I will report in just a few about the latest solution you provided.

@krayon007 I confirm the latest solution did work! Thank you sir. Is it alright if I keep this open until it's in the agent binary?

**Comment by krayon007** [comment]
> > > > > Sorry, my mistake... The .sh fix, only seemed to correct auto_start on pfsense, not opnsense... I'll look into why auto_start isn't working opnsense...
> > > > 
> > > > 
> > > > @krayon007 LOL...I just applied that fix and restarted the firewall. Will post what I come up with.
> > > 
> > > 
> > > ok, I found the real solution for OPNsense...
> > > go to the following folder:
> > > `/usr/local/etc/rc.syshook.d/start`
> > > You need to add a script to this folder... The easiest way is to just copy `90-cron` into `50-LaptopPitstopAgent`
> > > Then edit the file and change:
> > > `configctl cron restart`
> > > to
> > > `service LaptopPitstopAgent start`
> > > and save, chmod 770, and reboot.
> > > I'll fix the installer to do this for opnsense.
> > 
> > 
> > @krayon007 I can confirm with you that previous solution did not work. I will report in just a few about the latest solution you provided.
> 
> @krayon007 I confirm the latest solution did work! Thank you sir. Is it alright if I keep this open until it's in the agent binary?

No problem...

**Comment by LPJon** [comment]
@krayon007 @Ylianst Where is this at? Has it already been released?

**Comment by krayon007** [comment]
> @krayon007 @Ylianst Where is this at? Has it already been released?

This should've went live with v0.7.59

**Comment by LPJon** [comment]
Thanks....closing
