### ISSUE TITLE
[FEATURE REQUEST] Desktop management on a single browser window

### ISSUE THREAD

**Issue by GabrieleV** [Ylianst/MeshCentral#2213]
It would be nice to have the possibility to open the desktop of the remote PC in a new window similar to noVNC.
In this way there is more screen space available.

Thank you, your work is aweseome !

**Comment by Ylianst** [comment]
Use the full screen icon to switch to a full size desktop view. You can also hold SHIFT and hit that icon to get full screen mode. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/105829897-bfe3f000-5f79-11eb-83be-7b118db5f450.png)

**Comment by GabrieleV** [comment]
Wonderful Undocumented Feature !
I think that a lot of features are not know to all users !

Thank you again,
GV

**Comment by LPJon** [comment]
I didn't even know you could use the shift key to actually make it FULL screen. This is awesome!
