### ISSUE TITLE
Desktop send Ctrl-w doesn't work when controlling ubuntu 20.04 (works when controlling Windows 10)

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#2216]
When using meshcentral 0.7.53 (latest available) to control an ubuntu 20.04 desktop, the function "send" "Ctrl-w" seems to do only a "w" without ctrl modifier. To test it I launched on the controlled machine google  chrome, opened a new tab, and send Ctrl-w to close it : not working. On a terminal send Ctrl-w writes a single character "w".

When controlling a Windows 10 machine "send" "ctrl-w" to close a web browser tab works fine so it's likely a linux only issue.

**Comment by krayon007** [comment]
> When using meshcentral 0.7.53 (latest available) to control an ubuntu 20.04 desktop, the function "send" "Ctrl-w" seems to do only a "w" without ctrl modifier. To test it I launched on the controlled machine google chrome, opened a new tab, and send Ctrl-w to close it : not working. On a terminal send Ctrl-w writes a single character "w".
> 
> When controlling a Windows 10 machine "send" "ctrl-w" to close a web browser tab works fine so it's likely a linux only issue.

Does it work if you select "Use Remote layout", from the settings prior to connecting the desktop?

**Comment by guerby** [comment]
> > When using meshcentral 0.7.53 (latest available) to control an ubuntu 20.04 desktop, the function "send" "Ctrl-w" seems to do only a "w" without ctrl modifier. To test it I launched on the controlled machine google chrome, opened a new tab, and send Ctrl-w to close it : not working. On a terminal send Ctrl-w writes a single character "w".
> > When controlling a Windows 10 machine "send" "ctrl-w" to close a web browser tab works fine so it's likely a linux only issue.
> 
> Does it work if you select "Use Remote layout", from the settings prior to connecting the desktop?

Use Remote Layout doesn't seem to change the behaviour: it prints a w in terminal and in navigator tab.

**Comment by guerby** [comment]
I upgraded to 0.7.63 and ctrl-w sent to my ubuntu 20.04 test NUC doesn't seem to work (outputs just a "w" in the URL bar), same with Use Remote Layout.

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
