### ISSUE TITLE
Detected as Virus by Windows Defender and Avast

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#2217]
Today I had two issues:

First, on one client, when trying to install the agent, an Avast popup analyzed the program and determined it was a virus. I had to manually click on a "open anyways" button. (no screenshot, sorry)

Second, another client appeared as disconnected since 3AM. I had to access via AnyDesk. Then I saw this:
![image](https://user-images.githubusercontent.com/31445936/105859529-63112580-5fcb-11eb-9475-27d704919a0d.png)

:(

Important info:
- Never happened before (just "smartscreen" alerts, but nothing serious)
- I'm using version 0.7.52
- I'm using a modified Agent

**Comment by GRIFFCOMMca** [comment]
This happens all the time with Windows 10, a few security hoops have to be jumped through to get the client installed (to keep the download THEN to run it).

**Comment by yomono** [comment]
> This happens all the time with Windows 10, a few security hoops have to be jumped through to get the client installed (to keep the download THEN to run it).

To be honest is the first time for me, and I have +100 client on windows, mostly Windows 10

**Comment by gadgetusaf** [comment]
I have not seen this issue either and I manage a bunch of windows and Linux clients.

**Comment by Ylianst** [comment]
There is nothing much we can do as developers if this happens. I would encourage reporting this as a fault positive to your AV vendor. Another more complex option is to get a code signing certificate and sign the agent yourself.

**Comment by yomono** [comment]
Got it. Closing

**Comment by Ridd01** [comment]
I almost always get accepted by Microsoft Smart Screen team when I report MeshAgent (by download it from my web page in edge, and clicking report this as safe). This procedure takes aprox. 3-4 days for them to accept MeshAgent and then Smart Screen accepts it with no problem.
