### ISSUE TITLE
Reset Admin password

### ISSUE THREAD

**Issue by pepelemoko37** [Ylianst/MeshCentral#2219]
Hi,

I need to reset or view the admin pasword after a mistake, I try this https://www.reddit.com/r/MeshCentral/comments/j1s526/forgotten_admin_password/  but me server say this :

support@support:~/meshcentral/node_modules

$ node node_modules/meshcentral --help
internal/modules/cjs/loader.js:896
  throw err;
  ^
Error: Cannot find module '/home/support/meshcentral/node_modules/node_modules/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

The server is shut. Maby I make a mistake ?

Thank for your help.

**Comment by yomono** [comment]
if you are already on the "node_modules" folder, the command should be "node meshcentral --help"

> Error: Cannot find module '/home/support/meshcentral/node_modules/node_modules/meshcentral'

See? You are looking for a "node_modules" folder inside the "node_modules" folder

**Comment by Ylianst** [comment]
Looks like an obvious solution, do this:

```
cd ~/meshcentral
node node_modules/meshcentral --help
```

You have to start from the ~/meshcentral folder.

**Comment by pepelemoko37** [comment]
It's working !

Thank you very much.
