### ISSUE TITLE
How to use --removeaccount option - cannot succeed - question

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2220]
have tried lots of combinations and no luck:

root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --listuserids
user//testtest
user//edited
user//edited
user//vaskotesta
user/domainedited/edited
user/domainedited/edited
user/domainedited/edited

and so on

root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount [user//vaskotesta]
Invalid userid.
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount vaskotesta
Unknown userid, usage: --removeaccount [userid] --domain (domain).
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta
Unknown userid, usage: --removeaccount [userid] --domain (domain).
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta --domain
Unknown userid, usage: --removeaccount [userid] --domain (domain).
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta --domain ""
Unknown userid, usage: --removeaccount [userid] --domain (domain).
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta --domain main
Unknown userid, usage: --removeaccount [userid] --domain (domain).
root@jessie: node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta --domain /
Unknown userid, usage: --removeaccount [userid] --domain (domain).

What am I doing wrong?

**Comment by Ylianst** [comment]
I just found and fixed an issue with this operation when using MongoDB. Will be fixed in MeshCentral v0.7.54. Your usage should work, the following are the same:

```
node meshcentral.js --removeaccount vaskotesta
node meshcentral.js --removeaccount user//vaskotesta
```

or if you are using multiple domains and want to remove a user in a specific domain the following is the same:

```
node meshcentral.js --removeaccount user/mydomain/vaskotesta
node meshcentral.js --removeaccount vaskotesta --domain mydomain
```

**Comment by vitko-bg** [comment]
Yes, I am using a MongoDB and domains, what will be the use if domain is the main one, in config.json it is "", what will be  - - domain option then? For extra domains it is clear, just to put - - domain my domain if if in config it is "my domain" {}.. What about the main one? Thanks.

**Comment by vitko-bg** [comment]
Actually sorry for the previous post :)
Looks like it will be "--removeaccount user/mydomain/username" and that is answering my question. Will test in new version and will let you know. Thank you!!!!

**Comment by Ylianst** [comment]
Excellent. I still did find a bug as a result of this request :) So this is good.

**Comment by vitko-bg** [comment]
@Ylianst - I cannot reopen the issue, as looks like it does not work. Actually it works, but requires a MC2 Server service restart.
**Steps to reproduce:**
1. Create user via WebUI of MC2, in my case I used username "vaskotesta"
2. List users from terminal to make sure that user is created:
root@jessie:# node /my/path/node_modules/meshcentral/meshcentral.js --listuserids
user//edited
user//vaskotesta
user/sub1/sub1edited
user/sub2/sub2edited
3. Delete user from terminal:
root@jessie:# node /my/path/node_modules/meshcentral/meshcentral.js --removeaccount user//vaskotesta
Done.
4. List users again to make sure that user is deleted - and it is deleted as per below command:
root@jessie:# node /my/path/node_modules/meshcentral/meshcentral.js --listuserids
user//edited
user/sub1/sub1edited
user/sub2/sub2edited
5. On WebUI of MC2 the user is still there - listed in all users list.... Can click on user name and it is not deleted
6.  Have tried to logout of WebUI and login again - no luck, result is same.
7. Restarted MC2 server:
node /my/path/node_modules/meshcentral/meshcentral.js --restart
and **only after MC2 server restart** user has gone.

**Comment by Ylianst** [comment]
So, what I am going to do is remove --removeaccount from meshcentral.js completely. I should never has implemented it in the first place as it's not possible to fix this correctly in this case.

Basically account recovery commands in meshcentral.js should only be used as a last resort when you lost your admin account and should not be used while the server is running. Instead, use:

```
node node_modules/meshcentral/meshctrl.js removeuser
```

Hope that helps,
Ylian

**Comment by Ylianst** [comment]
Ok. Just removed it. Will not be present in v0.7.57.
