### ISSUE TITLE
Some agents have same ip address of server

### ISSUE THREAD

**Issue by chadht** [Ylianst/MeshCentral#2223]
When I'm in my devices some of my agents have the same ip address as the server. When running ipconfig from the agent it has a different ip address which is correct. The Windows version the agents are running doesn't seem to matter as to why some are showing the server address and others are showing their correct ip address.  Is there a way to display the correct address when viewing agents from in my devices?

**Comment by krayon007** [comment]
So are you saying if you click on the details tab, the IP address shown for each interface is wrong?

**Comment by chadht** [comment]
Hi Bryan,

If I click the details tab for a device the correct address is shown. The My Devices screen shows several computers with an address that is the same as the server even though they have the correct ip address in details. Screenshot attached. Please let me know if you need additional information.

Thanks,
Chad Tidgewell
Technology Support | HCPSS
techsupport@hcpss.org<mailto:techsupport@hcpss.org> | Technology Resources<https://hcpss.instructure.com/courses/32959>


The information contained in this email transmission is privileged and/or confidential and is intended solely for the exclusive use of the individual addressee. If you are not the intended addressee, you are hereby notified that any retention, disclosure, or other use is strictly prohibited. If you have received this email in error, please contact the sender immediately and delete the material.

**Comment by Ylianst** [comment]
Hi. Are you running a reverse proxy in front of MeshCentral? If so, it's quite typical that if the reverse proxy is not trusted or does not send the correct HTTP headers, MeshCentral will think all connections (users and agents) are coming from the reverse proxie IP address.

One way to debug this is to go in the "My Server / Tracing" tab and enable the "Web Server Requests" tracing. You will see the Ip address of the incoming requests and you will see if they all come from the same place.

![image](https://user-images.githubusercontent.com/1319013/106065025-89a88c80-60af-11eb-85cf-54db9f45b555.png)

If that is you case, let us know. There are a few things to look at to fix this.

**Comment by chadht** [comment]
Hi,

We're using a proxy but not all computers are showing the same server address when I look at My Devices. Could the issue still be the proxy is not trusted or is not sending the correct HTTP headers? I traced the web server requests but do not see the server address listed, all ips are different, screenshot attached.

Thanks,
Chad Tidgewell
Technology Support | HCPSS
techsupport@hcpss.org<mailto:techsupport@hcpss.org> | Technology Resources<https://hcpss.instructure.com/courses/32959>


The information contained in this email transmission is privileged and/or confidential and is intended solely for the exclusive use of the individual addressee. If you are not the intended addressee, you are hereby notified that any retention, disclosure, or other use is strictly prohibited. If you have received this email in error, please contact the sender immediately and delete the material.

**Comment by Ylianst** [comment]
We did not get your attached image. Probably best to use the GitHub web interface if possible. In any case, I don't think I have sufficient information to make any headway on this. Your going to have to debug this a bit more. Is the common IP address the address of the reverse proxy?  Is there something that all devices with the same IP address have in common? Etc.

**Comment by LPJon** [comment]
I have a 4 proxy setup. There is no HA. In the trusted proxy setup I had to list the IP address of every **Proxy IP** in the `"trustedProxy":` settings section. You must also be sure that you are sending all of the `X-Forwarded-<option>` headers. If you are getting IP's that are not any of your proxies then that should/would be the PUBLIC IP of your client/agent and NOT it's internal IP address. The internal IP address is reported in the "Details" tab under the "Networking" section specifically at the list of NIC's

The webserver logs at the proxy/s would be very helpful in seeing what the proxy is seeing at it first comes into the webserver. Specifically the "error.log".

NOTE: Apache proxy requires some special trickery when dealing with web sockets (WS) or web sockets secure (WSS). Please let me know if you are using Apache to proxy with anywhere. I'm a webhost administrator and can help in that scenario. NginX is just like the docs and is pretty straight forward.

NOTE2: Some corporate firewalls route incoming and outgoing traffic through different IP addresses in very different Geo locations. Is it possible your are using GeoIP blocking? Or maybe your client side is?

**Comment by jarodct** [comment]
Hi 
how to connect meshcentral with nvr or ip camera  ...  any idea..

**Comment by LPJon** [comment]
> Hi how to connect meshcentral with nvr or ip camera ... any idea..

This isn't really possible unless you use the "relay" feature of "MeshCentralRouter" or "MeshCMD" for windows. There are also other factors at play. In my experience NVR's and IP cams don't like the way meshcentral routes the traffic and most of them will halt the connection citing a DNS rebind attack or Unauthorized. You will most likely have to access those devices directly from another device on the network they are connected to. For example another PC.

**Comment by sammyke007** [comment]
> Hi. Are you running a reverse proxy in front of MeshCentral? If so, it's quite typical that if the reverse proxy is not trusted or does not send the correct HTTP headers, MeshCentral will think all connections (users and agents) are coming from the reverse proxie IP address.
> 
> One way to debug this is to go in the "My Server / Tracing" tab and enable the "Web Server Requests" tracing. You will see the Ip address of the incoming requests and you will see if they all come from the same place.
> 
> ![image](https://user-images.githubusercontent.com/1319013/106065025-89a88c80-60af-11eb-85cf-54db9f45b555.png)
> 
> If that is you case, let us know. There are a few things to look at to fix this.

What was the fix please? My agents are all showing the same internal IP (from my Nginx Proxy Manager) instead of their real IP

**Comment by si458** [comment]
@sammyke007 you set `trustedProxy` in your `config.json` to the IP address of your nginx proxy manager server/container, then restart meshcentral

**Comment by sammyke007** [comment]
I use Cloudflare externally and NPM (nginx proxy manager) internally. Can I add two?

Current config that's working but showing the NPM's IP for all agents:
 "trustedproxy": "CloudFlare",

**Comment by si458** [comment]
so yes you would set `trustedProxy: "CloudFlare, 192.168.99.88, 172.16.9.88, 10.0.0.88"` for example

**Comment by sammyke007** [comment]
Ah ok, so adding both is not possible but probably not needed?
