### ISSUE TITLE
Alpine Linux Compatibility

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2225]
Hey all,

I'm testing out Alpine Linux as an alternative docker/webserver and discovered the meshagent doesn't seem to want to run. I get  `./meshagent: not found` as a result. I know the way alpine runs is different, so I wouldn't be surprised if I'm missing something simple. Just wondering if anyone here has alpine experience and knows what could fix it.

Not a biggie if it's a no go.

**Comment by Ylianst** [comment]
You probably got a agent binary that is not compatible with your OS or CPU. If you login to your MeshCentral server, change the URL to /meshagents. You will see a list of agent binaries you can download and try. It's possible the install script got the wrong one.

Let me know if that works.

**Comment by matt-cylanda** [comment]
Just went through every linux (non-arm) based binary... most gave the same output, some gave `cannot execute binary file: Exec format error`

**Comment by krayon007** [comment]
A quick google of Alpine linux, shows that distro does not use glibc, it uses musl. That's probably why it's not working... The same thing happens if you try to use a glibc agent build on openwrt, which is also musl based... I'll have to get or make a toolchain for alpine it looks like... Do you happen to have a link to an ova file or an iso so that I can run alpine in a vm?

**Comment by krayon007** [comment]
Ok, I was right... I got Alpine working in a VM, and verified that I need to recompile specifically for Alpine, as it doesn't work with any libraries compiled for glibc. I have a version working on Alpine that I just compiled, tho I still need to compile OpenSSL for it... After I get it done, I can have @Ylianst add it to the server.. Once I get it all working, I'll look at building a toolchain for it, so I don't have to compile using Alpine directly.

**Comment by matt-cylanda** [comment]
Wow... thank you Bryan! You majorly kick a$$!!

I've been finding more and more for my headless no-gui linux boxes, I prefer hopping into a shell thru MeshCentral over ssh... especially since everything I connect to is now centralized. Thank you again

**Comment by Ylianst** [comment]
Oh wow!!! Bryan texted me earlier to say he had Alpine Linux already compiled... I was blown away!! Bryan has a HUGE drive full of VM's that he uses for testing and compiling the MeshAgent. No way I would have that sort of speed to install a new OS, get the code over to it and compile/test it.

**Comment by krayon007** [comment]
> Wow... thank you @krayon007 ! You majorly kick a$$!!
> 
> I've been finding more and more for my headless no-gui linux boxes, I prefer hopping into a shell thru MeshCentral over ssh... especially since everything I connect to is now centralized. Thank you again

So far everything seems to work out of the box. I just need to figure out why the service doesn't auto start after a reboot.

**Comment by matt-cylanda** [comment]
That is so awesome! I think from now on I'm going to make my future docker servers/VM's Alpine server. All of the web services I've got running now on this old 4GB i3 definitely seem a lot snappier than when I was running them on Ubuntu... altho it's hard to imagine a slim server with a 140mb install wouldn't be fast :P

**Comment by Ylianst** [comment]
Quick note that last night MeshCentral v0.7.58 was published and it includes Bryan's latest Linux Alpine Mesh Agent. You will find it in the list when going to `/meshagents`. If you happen to run a v0.7.57 MeshCentral, that version has a Alpine agent, but don't use that version. Make sure to use the one in v0.7.58. Let us know if it works for you.

**Comment by krayon007** [comment]
The 'ps' console command doesn't work in the current Alpine agent version, but I already fixed that. It will be in the next agent update.

**Comment by krayon007** [comment]
> The 'ps' console command doesn't work in the current Alpine agent version, but I already fixed that. It will be in the next agent update.

Ok, this is fixed in server version v0.7.59

**Comment by matt-cylanda** [comment]
Awesome guys, it's working like a champ...

btw, the add agent command doesn't quite work. I had to manipulate the meshinstall script to replace the id=6 with id=33.

Otherwise it seems to be working perfectly. Thanks again!

**Comment by krayon007** [comment]
> Awesome guys, it's working like a champ...
> 
> btw, the add agent command doesn't quite work. I had to manipulate the meshinstall script to replace the id=6 with id=33.
> 
> Otherwise it seems to be working perfectly. Thanks again!

Oh yeah, I forgot to mention the install script wouldn't work, because normally the script only detects cpu architecture and OS. But in this case, that doens't work, because Alpine is still a linux, but using a different runtime library.... But if you download the binary installer, it should work.
