### ISSUE TITLE
Agents fail to update.

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#2227]
When I update the server to the latest all the agents report back that they have failed to upgrade.
Is it because meshcentral running on none standard port?
Also when I upgrade is my config.json suppose to have the new options in there?
any help would be appreciated.

**Comment by haxmachine** [comment]
When I update the server to the latest all the agents report back that they have failed to upgrade.
Is it because meshcentral running on none standard port?
Also when I upgrade is my config.json suppose to have the new options in there?
any help would be appreciated.

**Comment by asasin114** [comment]
Do you get an error about the agent hash check? If so, you can get the update to run by adding the "ignoreagenthashcheck: true" line to the Settings section of the config file. 

Config files with all options are found inside the "~/node-modules/meshcentral" folder or you can download the from meshcentral.com to see all available config options.

Hope this helps!

**Comment by Ylianst** [comment]
Looking into this now. I will re-test using a non-standard port and with "ignoreagenthashcheck: true" just to make sure both cases are handled.

**Comment by Ylianst** [comment]
Also, it would be great to get the full and exact error - Thanks.

**Comment by Ylianst** [comment]
Oh. Is it possible that all agents that are reporting that they can't update using HTTP proxies to connect to the server? I am investigating this now.

**Comment by Ylianst** [comment]
I don't know the root cause of this specific issue, but I did just publish MeshCentral v0.7.57 that fixes the agent self update system when used with "agentPort" or when used with the agent modified with connect to some URL that is other than the one used by browsers. Hopefully that will fix it.

**Comment by haxmachine** [comment]
Ill try the upgrade to the lasted build and see if it updates.
if it doesnt what information can i get you to help troubleshoot the issue?

**Comment by haxmachine** [comment]
I just updated to the lasted build you have available and looks like the agents are now updating without an issue.
