### ISSUE TITLE
MC Chocolatey Installer?

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#2229]
Guys, we push out software using Atera.... it uses Chocolatey packages.  Anyone ever create a chocolatey package?  Could that be done?
Shane

**Comment by southeasterntech** [comment]
or a script installer

**Comment by LPJon** [comment]
I really think this is a bad idea. Mainly because script installers are used in malware. Ive used Chocolaty before so I know what it is but I think this could lead to Anti-Virus software banning the MashAgent.

**Comment by Ylianst** [comment]
I have no idea with Chocolatey is. Not something I can comment on.

**Comment by southeasterntech** [comment]
@Ylianst Chocolatey is a collection of silent install scripts that allows you to install masses of software across many machines at the same time.  Having a mesh option would be cool.  Could do it with a silent install MSI as an alternative., with LPJon's opposition well noted... Thanks All... can close if no further relevance

**Comment by Ylianst** [comment]
The meshagent can self install using "meshagent.exe -fullinstall". You can also type "meshagent.exe -help" to see options. I would imagine given this to use pretty much any tool you like to install the agent.

**Comment by Ylianst** [comment]
Ok, will close this one as I think pretty much anyone can install using `meshagent.exe -fullinstall` in any other tool. If there is more to this, feel free to post here or open a new issue.
