### ISSUE TITLE
QUESTION - Is it normal to see numbers in "duplicateAgentCount"?

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2230]
![duplicateagent](https://user-images.githubusercontent.com/46533576/106179821-2ecf6d80-6161-11eb-91c9-5a943170e318.png)
@Ylianst or @krayon007 I'm seeing numbers in the "duplicateAgentCount" section of "agentstats" is this normal. I'm willing to bet this is from when I installed the default meshagents before I customized them but I wanted to make sure.

**Comment by Ylianst** [comment]
Yes, it is. Especially if some of the devices are on WIFI. When a device looses connection to the network and reconnects back again a minute later, the server never got an indication that the connection was broken in the first place. When the new connection arrives, the server will drop the old one to the same agent. That will cause this counter to go up, but it's ok.

If you see the counter going up non-stop, then it may be an indication that you have many "cloned" agents that all have the same certificate and nodeid. But this should not be typical.
