### ISSUE TITLE
Messenger : how to know when a user is typing ?

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2231]
Hi,

Is it possible to show, to the remote user, when I'm about to type a message ? 
Something like "User is typing..." ?

Thank you

**Comment by Ylianst** [comment]
Not something that is supported now. Bryan would have to look to see if it's possible.

**Comment by elpibedeoro** [comment]
Ok great, thank you.

**Comment by Ylianst** [comment]
I just realized you where asking this for MeshCentral Messenger, not remote desktop. Yes, I can work on adding this.

**Comment by Ylianst** [comment]
Added this to v0.7.60 when it's next published. Let me know if it works.

![image](https://user-images.githubusercontent.com/1319013/106669868-2b712300-6561-11eb-9a74-952a7178587b.png)

**Comment by elpibedeoro** [comment]
Wow that's incredible ! Sincerely, thank you so much for all your hard work and for the super rapid response times to fix problems or add new functionality to this great solution. I'm impressed !

**Comment by elpibedeoro** [comment]
Just tested and It works as well ! Great work !
Thank you.
