### ISSUE TITLE
Saving files is not enabled in hosted mode. Please inspect using chrome://inspect

### ISSUE THREAD

**Issue by Behradbb** [Ylianst/MeshCentral#2233]
Trying to use MeshCommander Debug mode in order to check for any sorts of error and export the logs however when trying to export getting the error message indicating that : Saving files is not enabled in hosted mode. Please inspect using chrome://inspect" and once click on inspect link, a blank page will open. test this with and without Admin permissions. also tested on 2 different windows version and MeshCommander version 8.8 and 9.0

**Comment by Behradbb** [comment]
![image](https://user-images.githubusercontent.com/78224036/106305915-4ecb6380-622b-11eb-9fff-a93b0ee0c137.png)
![image](https://user-images.githubusercontent.com/78224036/106305980-6571ba80-622b-11eb-8513-78d22db766cc.png)

**Comment by Ylianst** [comment]
It's not clear from your request how I can reproduce this issue. Can you indicate what steps you take to get into this situation? What exact place you click on what tab to see this error? Screenshots are always the best. Thanks.

**Comment by Behradbb** [comment]
1: I tried to open "Debug" mode through the Admin or non-Admin CMD
2: Mesh Commander opens along with the Developer tools for gathering the logs
3: perform the issue which is accessing a machine that is powered down and get the Error #500 after the first attempt ( I should mention that this error will not show up on the 2nd attempt onward)
4: Tried to save the log files through the toolkit and got and error that saving is not enabled and try the "inspect mode"
5: once click on the "chrome://inspect", the blank page will open and nothing happens after that. 

![image](https://user-images.githubusercontent.com/78224036/106625261-81839d80-6544-11eb-88fb-77ba0f385b5d.png)
![image](https://user-images.githubusercontent.com/78224036/106625450-a841d400-6544-11eb-8eab-86e2275086f7.png)
![image](https://user-images.githubusercontent.com/78224036/106625492-b09a0f00-6544-11eb-8ad2-2aa08d19f130.png)
![image](https://user-images.githubusercontent.com/78224036/106625551-c1e31b80-6544-11eb-8ba4-ca112555c43a.png)
![image](https://user-images.githubusercontent.com/78224036/106625591-cb6c8380-6544-11eb-91af-9bd1714cc639.png)
![image](https://user-images.githubusercontent.com/78224036/106625617-d32c2800-6544-11eb-847f-24a1a3109781.png)

**Comment by Behradbb** [comment]
Any update on your testing? extracting logs from Mesh Commander is now a crucial part of our operation which we can not perform.

**Comment by Behradbb** [comment]
We are still facing this issue...Any update?

**Comment by Behradbb** [comment]
Anybody will pick this up?

**Comment by si458** [comment]
closing as stale and also wrong repo,
this issue should be moved to https://github.com/Ylianst/MeshCommander
