### ISSUE TITLE
MeshCentral 'Files' Downloads Issue

### ISSUE THREAD

**Issue by corhsin** [Ylianst/MeshCentral#2235]
Chrome 88 on Win10 x64 20H2.  Downloading files beginning with the tilde (~) character does not begin.  This was not an issue until recently.  A workaround is zipping the file and downloading the zip.  TIA

**Comment by Ylianst** [comment]
I looked into this and it seems to be a Chrome thing. Chrome does not consider files with ~ to be safe and changes the names to _ instead. I tried Firefox and it does not do this. As a result, there is nothing I can do. If you can confirm you see the same, that would be great. If you really need to download files with ~, use a different browser.

**Comment by corhsin** [comment]
The tilde to underscore issue / 'security' is longstanding.  A file beginning with tilde was just downloaded.  MeshAgent was refusing to download outright.  I will attempt it again with FF next opportunity.  Thank you for investigating it.
