### ISSUE TITLE
10days event log

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2236]
Dear Sir,

I need to download the last 10days meshcentral event logs instead of 1000nos.

is ther any provision for the same

**Comment by VINISHVV** [comment]
Hi Please help to get the same from UI /database.

**Comment by VINISHVV** [comment]
@Ylianst - Please help

**Comment by Ylianst** [comment]
OK, I see you also posted #2241. If that is ok, I will work on adding a way to pull the event logs from MeshCentral using MeshCtrl.js. If you have not used that, try:

```
node node_modules/meshcentral/meshctrl.js
```

It allows you to do many commands on MeshCentral. You can new the "showevents" action to see server events on real-time. I know people that use this to do things when users perform specific actions.

**Comment by VINISHVV** [comment]
@Ylianst - Actually i am new to mesh central, can you suggest how can we export the log using command node node_modules/meshcentral/meshctrl.js

**Comment by Ylianst** [comment]
If you are using MongoDB, you can use the "mongo" command to query the events collection of the meshcentral database. This said, I just published MeshCentral v0.7.61 with an improved version of MeshCtrl.js. You can now use the "listevents" command to pull the event log. Give it a try and let me know if it works:

![MC2-MeshCtrl-ListEvents](https://user-images.githubusercontent.com/1319013/106733321-9a349780-65c6-11eb-8486-0cba0f93bf95.png)

**Comment by VINISHVV** [comment]
@Ylianst 

I have updated the MeshCentral v0.7.61. But unable to get the event logs.

I have tried below command, Please guide how we can export the file to json/csv.

_________________________________
PS C:\mesh> node **node_modules/meshcentral/meshctrl.js ListEvents**
{ action: 'events', responseid: 'meshctrl' }
Invalid login.
PS C:\mesh>
_________________________________________________________

**Comment by Ylianst** [comment]
Yes, you will need to provide login information, follow the [guide here](https://meshcentral.com/info/docs/MeshCmdUserGuide.pdf).

**Comment by VINISHVV** [comment]
Finally i understood how to works with meshctrl.

Thanks @Ylianst
