### ISSUE TITLE
[Not An Issue] Docker

### ISSUE THREAD

**Issue by Typhonragewind** [Ylianst/MeshCentral#2237]
Hello!

I really love this software you guys have been developing, it's awesome, secure and works wonderfully!

So as a challenge to myself and a way to develop my IT skills a bit, I've integrated it into a docker image, with some easy to deploy configurations via docker-compose. I've extensively read your User and Installer guides (great documentation there) and came up with something aimed not at Enterprise or large scale environments, but at small time self-hosters like me.

Some people on reddit seemed to like it and i wanted to ask, if you approve of this, if it would be possible to orchestrate between us the autobuild of this image upon each new release of MeshCentral.

Edit: Forgot the link to the repo: https://github.com/Typhonragewind/meshcentral-docker

**Comment by Ylianst** [comment]
Nice! First, of course I approve this :) [Searching for "MeshCentral" on Docker Hub](https://hub.docker.com/search?q=meshcentral&type=image) shows that there are already a few Docker images for MeshCentral. I have not made one available myself, but I am already so swamped with requests, I appreciate others taking this on.

I think one approach is to "npm install meshcentral" as part of the Docker script, that way, I don't need to coordinate with anyone. Anyway to lower my workload at this point is a good thing. If there is anything I can change in MeshCentral to make it easier for Docker, be sure to let me know.

**Comment by Typhonragewind** [comment]
> Nice! First, of course I approve this :) [Searching for "MeshCentral" on Docker Hub](https://hub.docker.com/search?q=meshcentral&type=image) shows that there are already a few Docker images for MeshCentral. I have not made one available myself, but I am already so swamped with requests, I appreciate others taking this on.

Yes, i realize there were already some, but I wanted a challenge to my growing skills 😅.

> I think one approach is to "npm install meshcentral" as part of the Docker script, that way, I don't need to coordinate with anyone. Anyway to lower my workload at this point is a good thing. 

That is certainly a way to do it, but the problem lies in that it makes the container based on that image takes much longer to start. This can be mitigated by mounting a volume containing the installation files, making only the first start of the image take a while.

> If there is anything I can change in MeshCentral to make it easier for Docker, be sure to let me know.

MeshCentral actually plays really well with Docker, with having all the necessary configs in a single directory, that was a godsend.

In any case I'll find a way to do it that does not give you any extra workload, don't worry about that!
