### ISSUE TITLE
Download Multiple Files

### ISSUE THREAD

**Issue by KSJakobsen** [Ylianst/MeshCentral#2238]
Hi,

this is not really an issue but rather a request/idea. A colleague of mine wanted to download multiple Files via the Files-Connection-Tab and it seems that this options is not yet included. 

Kind Regards
Kai - Stephan Jakobsen

**Comment by vitko-bg** [comment]
You can Zip them all and download the Zip file.

Hope that helps

**Comment by KSJakobsen** [comment]
I know. Told him the same. But out of convenience he just wanted to download several files without zipping them :)

**Comment by vitko-bg** [comment]
As I know it is not implemented yet. I may be wrong though

**Comment by Ylianst** [comment]
Browsers don't have any good options for downloading multiple files. Generally you have to zip and download... but there is another option: If you are running on Windows, download MeshCentral Router, login in using that tool, right click on a device and hit "Remote Files". You will see a file navigation UI to that device that allows you to select many files and upload/download them. Hopefully that helps.

![image](https://user-images.githubusercontent.com/1319013/106395569-c75f2b00-63b7-11eb-8059-c076a835e390.png)
