### ISSUE TITLE
Seeing error message with FreeBSDagent on OPNSense and seeing "Desktop" tab with a terminal only interface.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2239]
The error message is as follows on an OPNSense FreeBSDAgent "Console" tab. Another strange thing is that the "Desktop" tab is also visible when it should not be. I have only one instance with this behavior. I am using a customized agent setup. I have attempted to reinstall the agent to correct the issue already which did not work. Please let me know if there is any debug information I can pass along to you.

`uncaughtException1: Error: timers.onElapsed() callback handler on 'sendNetworkUpdate()'  => TypeError: cannot read property 'toString' of undefined`

**Comment by LPJon** [comment]
@Ylianst @krayon007 When should the Desktop tab be displayed. Is there an agent trigger which displays this tab when needed?

**Comment by Ylianst** [comment]
Can you go in the agent console, type "info" and report back what you see. There is a line there indicating if the agent detects if X11 is present on the platform. I am guessing it's miss-detecting it.

Also for the exception in the `sendNetworkUpdate()`, it's probably unrelated, but something we need to look at.

**Comment by LPJon** [comment]
Here is what I get from the console of that agent:

`Current Core: MeshCore CRC-2539382003`
`Agent Time: 2021-02-01 21:47:14.218+00:00.`
`User Rights: 0xffffffff.`
`Platform: freebsd.`
`Capabilities: 15.`
`Server URL: wss://<Hidden URL>:443/agent.ashx.`
`OS: FreeBSD 12.1-RELEASE-p12-HBSD amd64.`
`Modules: monitor-border, sysinfo, wifi-scanner-windows, wifi-scanner.`
`Server Connection: true, State: 1.`
`X11 support: true.`

**Comment by Ylianst** [comment]
Thanks. Interesting, `X11 support: true`. That is why the desktop tab is showing. Bryan will need to look into this.

**Comment by LPJon** [comment]
> 
> 
> Thanks. Interesting, `X11 support: true`. That is why the desktop tab is showing. Bryan will need to look into this.

Just let me know if you need anything from me.

**Comment by LPJon** [comment]
@krayon007 Any chance you have had a look at this?

**Comment by LPJon** [comment]
@Ylianst @krayon007 After second looking at this. OPNsense is not supposed to have the xorg package installed. Your side is working just fine. This is OPNsense related. Thanks for the help identifying it though. I'm closing this issue
