### ISSUE TITLE
not able Add new users to the Mesh 

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#224]
When using the Mesh i am not able to add several users with Full admin rites. only limited people are able to be added to the mesh.

**Comment by Ylianst** [comment]
Thanks for the report. I will check this today.

**Comment by Ylianst** [comment]
I did some testing and adding users works for me. Can you post a most exact list of actions you are doing that causes the problem and screen shots of the problem? Also, let me know if you are using your own custom server or a public server. If it's your own server, any server details would be appreciated. Thanks.

**Comment by Arun0711** [comment]
Hi Ylian ,

We are using this link – “mesh.intel.com” 
We are trying to add below people who are in our team to access our system

i have send u the details on ur mail 
Few users are able to be added but rest no error msg or details are seen.

Attached are the screen shot for the same.

![Mesh Home page](https://user-images.githubusercontent.com/50354309/57347120-d4150780-716e-11e9-97e5-ac213d30b242.jpg)
![Add_a New_User](https://user-images.githubusercontent.com/50354309/57347121-d4150780-716e-11e9-993f-1a53d0b5741c.jpg)

**Comment by Kodangi** [comment]
Possibly exceeded the maximum number of users: "MaxUserAccounts": 100?

**Comment by Arun0711** [comment]
I have added only around 5-6 users in a group.

**Comment by Kodangi** [comment]
Found why: You are trying to add users who are not in DB. Please ask them to login to site once, then you should be able to add them.

**Comment by Arun0711** [comment]
Okays sure let me check and update

**Comment by Arun0711** [comment]
Excellent I am able to add the users now.

Thanks for the help ☺

**Comment by Arun0711** [comment]
i am closing this issue as resolution is working

**Comment by Ylianst** [comment]
That is exactly right. You can only add users that are in the MeshCentral database and so, for servers using domain controllers, users will need to hit the web site once before you can add them. This said, I need to do something to improve this situation by adding a note to the "Add User" dialog box, or fix it and query the domain controller when an account does not exist yet.

**Comment by Arun0711** [comment]
Yeap that’s rite

Regard
Arun

**Comment by Ylianst** [comment]
One more note on this. I just published MeshCentral v0.3.3-w with a few fixes for this. First, if a user is not found the web site will now generate a notification. Also, if the server uses domain authentication or LDAP authentication, the add box will show extra text indicating that users need to login once before they can be added. Both of these should help with this issue.

![MC2-UserWarn](https://user-images.githubusercontent.com/1319013/57412725-903df480-71a6-11e9-8e68-057be977f019.png)
![MC2-UserWarn2](https://user-images.githubusercontent.com/1319013/57412726-9207b800-71a6-11e9-900e-c6aa5ae69b8f.png)

**Comment by Arun0711** [comment]
Thanks a lot Ylian for the support !!

Regard
Arun
