### ISSUE TITLE
Event Log for Remote access & file access

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2241]
Hi,

Is there a way to write all events to external file like below command.

"authlog" : "c:\\mesh\\auth.log"

Thank you...
Regards
VINISH

**Comment by Ylianst** [comment]
There is no way to do that now, but I think a good option would be to allow MeshCtrl.js to pull event logs from the database. Certainly something I want to add. Would it be of if you could generate a .log file when needed?

**Comment by VINISHVV** [comment]
Hi Ylianst,

Thanks for consider the request.
Please incorporate the changes.

Thank you...
Regards
VINISH

**Comment by VINISHVV** [comment]
Closing the task since it's already implemented in meshctrl.
