### ISSUE TITLE
 database auto-backup issue

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2242]
Hi,

getting below error message in my server. I have tried mongodb versions 3.4,3.6 & 4.0.

Please fix this issue.

Error Message - "Unable to find mongodump.exe, MongoDB database auto-backup will not be performed."

**Comment by vitko-bg** [comment]
You have to install mongodump, it is not part of MongoDB anymore

**Comment by Ylianst** [comment]
@vitko-bg is correct, starting with MongoDB 4.0, mongodump is not longer included and needs to be installed separately. In some cases, MeshCentral can't find mongodump, if this is the case, add the following line in the settings section of the config.json:

```
"mongoDumpPath": "C:\MyPath\mongodump.exe"
```

That should help.

**Comment by VINISHVV** [comment]
@Ylianst 

I have installed the mongodump tool separately and added below commands inside config.js.
But still i am getting **WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed.**

______________________________________________________________

"mongodb": "mongodb://127.0.0.1:27017/meshcentral",
"mongodbcol": "meshcentral",
"mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",

______________________________________________________________

But when i try the command manually it will run successfully.

_______________________________________________________

C:\Program Files\MongoDB\Tools\100\bin>mongodump --uri="mongodb://127.0.0.1:27017/meshcentral" --archive="C:\mesh\meshcentral-backup\mongodump-2021-02-03-18-05.archive"

2021-02-03T18:09:48.711+0530    writing meshcentral.events to archive 'C:\mesh\meshcentral-backup\mongodump-2021-02-03-18-05.archive'
2021-02-03T18:09:48.715+0530    writing meshcentral.power to archive 'C:\mesh\meshcentral-backup\mongodump-2021-02-03-18-05.archive'
2021-02-03T18:09:48.717+0530    writing meshcentral.meshcentral to archive 'C:\mesh\meshcentral-backup\mongodump-2021-02-03-18-05.archive'
2021-02-03T18:09:48.718+0530    writing meshcentral.serverstats to archive 'C:\mesh\meshcentral-backup\mongodump-2021-02-03-18-05.archive'
2021-02-03T18:09:48.757+0530    done dumping meshcentral.serverstats (5 documents)
2021-02-03T18:09:48.769+0530    done dumping meshcentral.events (3830 documents)
2021-02-03T18:09:48.802+0530    done dumping meshcentral.meshcentral (2691 documents)
2021-02-03T18:09:48.865+0530    done dumping meshcentral.power (26661 documents)
__________________________________________________________________________________

Please suggest if my configuration is wrong.

**Comment by Ylianst** [comment]
Try adding this line instead:

```
"mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
```

**Comment by VINISHVV** [comment]
@Ylianst - Tried the code provided by you. But still showing same error message.
_________________________________________________________________

"settings": {
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "mongoDumpPath": "c:\\\Program Files\\\MongoDB\\\Tools\\\100\\\bin\\\mongodump.exe",
    "_WANonly": true,
    "_LANonly": true,
    "_AllowHighQualityDesktop": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "authlog" : "c:\\mesh\\auth.log",
    "ListEvents" : "c:\\mesh\\event.csv"
      },

_________________________________________________________________

**Comment by Ylianst** [comment]
Arg! My fault. After looking at the code, replace "mongoDumpPath" with this in the settings section of config.json:

```
    "autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe"
    }
```

I will fix the schema and sample config.json in the next version. Let me know if that works.

**Comment by VINISHVV** [comment]
@Ylianst - Thanks, issue resolved.

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back.
