### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#2243]
Just a quick one. 

I currently have a few Pi's that i use at various different locations. 

They are all built using the same image. If i was to install MeshCentral onto it then create a image to flash onto multiple Pi's would it cause issues? Or should i rather create a first boot script to automatically install MeshCentral when the Pi boots for the first time? 

Kind Regards,

Vit

**Comment by krayon007** [comment]
As long as the MAC address is different, it will be fine. The agent will detect that the mac is different from what is saved in the db, and it will generate a new cert and have a different NodeID.

**Comment by krayon007** [comment]
If the db is not present, that will work too, as the agent will generate a new cert in that case too.

**Comment by vithusel** [comment]
Ah ok. 

Ill have to do some testing as im using some cheap Ethernet adapters on pi zeros and im pretty sure they kill the network when two of them are active due to having the same mac address. Thank you guys!
