### ISSUE TITLE
McRouter macOS: How to save mappings?

### ISSUE THREAD

**Issue by thelarz** [Ylianst/MeshCentral#2244]
Should File/SaveAs... actually save all the Device Mappings and Relays?

I've tried File/SaveAs and then close/reopen the app and click File/Open. No mappings were re-populated.

**Comment by Ylianst** [comment]
Weird, I will need to take a look at this.

**Comment by Ylianst** [comment]
This should be fixed in MeshCentral Router for macOS v0.0.4.

**Comment by thelarz** [comment]
Where do I download the latests version? MeshCentral server downloads v0.0.3. I'm on server version v0.7.59
