### ISSUE TITLE
Router Feature Request: Native SSH in Windows

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2246]
With Windows able to handle SSH natively now, would it be possible to have MeshCentral Router utilize Command Prompt for SSH connections rather than requiring PuTTY? Or perhaps make it a preference?

**Comment by Ylianst** [comment]
Just added it. Will be in MeshCentral v0.7.80 or you can [download it here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

![MC2-OpenSSH](https://user-images.githubusercontent.com/1319013/109744238-cd972180-7b86-11eb-8d97-a067f337ce9b.png)

Let me know if this works.

**Comment by PetieM** [comment]
Working perfectly here! Thank you!
