### ISSUE TITLE
"Desktop" tab is missing?

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#2247]
MeshCentral: v is 0.7.59

 Operating System: Fedora 33 (Thirty Three)
 CPE OS Name: cpe:/o:fedoraproject:fedora:33
 Kernel: Linux 5.10.11-200.fc33.x86_64
 Architecture: x86-64

> info
Current Core: MeshCore CRC-3384487988
Agent Time: 2021-02-02 11:29:23.821-08:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 14.
Server URL: wss://xxxx
OS: Fedora 33 (Thirty Three).
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: false.

**Comment by FATeknollogee** [comment]
But, on another desktop with the same o/s, the "Desktop" tab is fine?

Operating System: Fedora 33 (Thirty Three)
CPE OS Name: cpe:/o:fedoraproject:fedora:33
Kernel: Linux 5.10.11-200.fc33.x86_64
Architecture: x86-64

> info
Current Core: MeshCore CRC-3384487988
Agent Time: 2021-02-02 14:35:19.577-05:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 15.
Server URL: wss://xxxxx
OS: Fedora 33 (Thirty Three).
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: true.

**Comment by LPJon** [comment]
@krayon007 @Ylianst may be related to #2239

**Comment by Ylianst** [comment]
I am going to be investigating this, but the manual fix is to reset the core of the agent. Click on a device, go to the "console" tab, click "Agent Action..." and select "Clear the core". The do that again selecting "Upload default server core":

![image](https://user-images.githubusercontent.com/1319013/106656048-0378c400-654f-11eb-95a6-c2b4db6fb0e8.png)

That will bring back all the features immediately. If you have lots of devices doing this, I can work on a better solution.

**Comment by FATeknollogee** [comment]
Thanks, that'll work for now since I only have that issue with 2 devices.

**Comment by Ylianst** [comment]
Ok. Restarting the server will probably also fix it... but I do want to see what is going on.

**Comment by FATeknollogee** [comment]
Not sure if this is relevant.
When the desktop tab is missing, it also affects the actual user of the desktop.
The user claims the monitor output is black & the only fix is a hard power reset.

**Comment by LPJon** [comment]
> 
> 
> Not sure if this is relevant.
> When the desktop tab is missing, it also affects the actual user of the desktop.
> The user claims the monitor output is black & the only fix is a hard power reset.

@FATeknollogee That sounds OS related. Maybe that is the other way around....when there is no desktop on the Linux Client the desktop tab should actually not be visible in MeshCentral. The agent detects a desktop in Linux through this setting `X11 support: true.` X11 is specific to a Linux Desktop package installed on the the client.

**Comment by FATeknollogee** [comment]
> 
> @FATeknollogee That sounds OS related. Maybe that is the other way around....when there is no desktop on the Linux Client the desktop tab should actually not be visible in MeshCentral. The agent detects a desktop in Linux through this setting `X11 support: true.` X11 is specific to a Linux Desktop package installed on the the client.

@LPJon This os is Fedora Workstation, it always has a desktop.
btw, @Ylianst "console, clear the core" sequence did "fix" the problem

**Comment by LPJon** [comment]
> 
> 
> > @FATeknollogee That sounds OS related. Maybe that is the other way around....when there is no desktop on the Linux Client the desktop tab should actually not be visible in MeshCentral. The agent detects a desktop in Linux through this setting `X11 support: true.` X11 is specific to a Linux Desktop package installed on the the client.
> 
> @LPJon This os is Fedora 33 Workstation, it always has a desktop.
> btw, @Ylianst "console, clear the core" sequence did "fix" the problem

@FATeknollogee I expected that, but did you do any recent updates to your OS? It's not usual for a desktop to fail or vanish on Linux. If the desktop (Meaning the X11 services) failed or restarted then that could be how the agent is falsely identifying that Client as NOT having a desktop.

**Comment by FATeknollogee** [comment]
> @FATeknollogee I expected that, but did you do any recent updates to your OS? It's not usual for a desktop to fail or vanish on Linux. If the desktop (Meaning the X11 services) failed or restarted then that could be how the agent is falsely identifying that Client as NOT having a desktop.

Yes, some recent updates that included kernel updates.

**Comment by LPJon** [comment]
> 
> 
> > @FATeknollogee I expected that, but did you do any recent updates to your OS? It's not usual for a desktop to fail or vanish on Linux. If the desktop (Meaning the X11 services) failed or restarted then that could be how the agent is falsely identifying that Client as NOT having a desktop.
> 
> Yes, some recent updates that included kernel updates.

@FATeknollogee Ok....so you may try running a command at a command line to see if there is anything in your system logs about issues with restarting that service or that service failing.

**Comment by FATeknollogee** [comment]
@LPJon Ok, will try that the next time it fails.

**Comment by krayon007** [comment]
There are basically 3 steps to the detection logic. First it tries to find the x11 shared library. Then it tries to dynamically load it. Then finally it tries to find the server instance.

**Comment by krayon007** [comment]
So for example, I know there was one scenario someone had, where the agent was running as a background service as root... But the way their system was setup, X was not instantiated until a user logged in... In this scenario, when the agent started, it was unable to find an X server instance running.

**Comment by DMoRiaM** [comment]
Hi,

I'n one of my Linux machines the default runlevel is set to 3. I've
installed a minimal GUI but I need a startx command to bring it up. If the
X is active I am able to use it using the web panel. If not, the desktop
option won't appear. I always believed it to be the correct scenario.

Regards,


--

*Marcelo Amorim*
Analista de Sistemas
[image: logo] <https://www.tepfi.com.br/> <https://www.tepfi.com.br/>
(11) 99967-1956
marcelo@tepfi.com.br
*www.tepfi.com.br <http://www.tepfi.com.br>*

[image: banner] <http://www.tepfi.com.br/services>

*TEPFi Consultoria e Suporte* - São Paulo, Brasil
Este e-mail pode conter informação privilegiada e/ou confidencial,
destinada exclusivamente ao destinatário. Se não for o destinatário
não pode manusear este documento. Se por acaso receber indevidamente
este e-mail, agradecemos que nos contacte de imediato.

The information enclosed in this message is confidential and intended
solely for the use of the individual or entity to whom it is
addressed. If you are not the intended recipient, we kindly request
you to notify us and subsequently eliminate the message and all its
content.

La información adjunta en este mensaje es confidencial y está
destinada exclusivamente para el uso de la persona o entidad a quien
se dirige. Si no es el destinatario previsto, le rogamos que nos
notifique y, posteriormente, elimine el mensaje y todo su contenido.

Em 2 de fev de 2021 à(s) 22:53, Bryan Roe <notifications@github.com>
escreveu:

So for example, I know there was one scenario someone had, where the agent
was running as a background service as root... But the way their system was
setup, X was not instantiated until a user logged in... In this scenario,
when the agent started, it was unable to find an X server instance running.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ylianst/MeshCentral/issues/2247#issuecomment-772148604>,
or unsubscribe

**Comment by krayon007** [comment]
One further piece of information:

Currently the agent will only look for the X server once at startup. The only exception, being if it finds the shared library but cannot find the server. In this case it will retry a few times for like 3 minutes, or something like that, to catch the cases where the X server wasn't fully up yet... I had wanted to avoid constantly polling the server if it wasn't necessary. Does anyone know if there's an event somewhere I could listen or watch for, for those use cases you guys have where the X server is not instantiated until later? I know I tried looking for login/logoff events on DBUS, but I found that to be so inconsistent between distros.

**Comment by seblas81** [comment]
Hi
I have MeshCentral 0.7.89
I am experimenting similar issue. I have one machine with Ubuntu 20 and the Desktop Tab suddenly dissapeared. I tried fixing the core. The tab appeared again but when i clicked on "Connect" there is no display.

**Comment by BertJd** [comment]
Hi,

we also have problems, that the tab sometimes is missing, when login to our MeshCentral server. We made two observations, that may be helpfull:
First: The effect often depends on the user/group and there rights! Several times, when "remote"-users lost the "Desktop" tab, administrators had their full views and could connect to the device. (Website refresh on the remote-user browser had no effects, changing their rights deactivate and activate sometimes take effects).
Second: We suppose, that the disappearence correlate to network disconnections and network issues: Actually, our devices use VSL internet connections, which are disconnected at least every 24 hours by the IP provider. The agent reconnects after the break, but right there, the tab more often is missing. It gets back most times by >clear the core<, sometimes with >upload default core< or even >soft disconnect agent<. (One time, the tab appears, but "connect" could not established. But this seems to be not often.)
Previously, the devices were connected to a dedicated internet line. The effect was much rarer, but was still there. We didn’t pay much attention to it. But the situation is now quite different.
Thus, we actually restart the agent service after each network disconnect. The effect decreases, but also there it is not completely gone - thats to little success.

perhapts you have a hint or solution, we hope,
best regards,
Bert 

> info
Current Core: Aug 30 2021, 4052687721
Agent Time: 2021-09-08 12:49:00.750+02:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 15.
Server URL: wss://support.uiservice.net:443/agent.ashx.
OS: Garz & Fricke Yocto BSP (based on Poky) rocko-7.0-0 (rocko).
Modules: linux-dhcp, monitor-border, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: true.
