### ISSUE TITLE
Bug: MeshRouter - RDP and PuTTy Switches When Adding Map

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2248]
Seems like the bug was introduced in the latest version of MeshRouter. Steps to reproduce:

1) Open and log in to MeshRouter.
2) Go to "Mappings" tab and click "Add Map".
3) Choose either PuTTy or RDP as the Application.
4) Created map has PuTTy if RDP chosen, or RDP if PuTTy chosen.

The correct port is set for the initial application choice, but the "Open..." button launches the incorrectly assigned app, so creating an RDP map will have it trying to use PuTTy to open port 3389. Hopefully a simple fix!

**Comment by Ylianst** [comment]
Thanks for reporting this. It was reversed forever and never reported. Fixed it in MeshCentral v0.7.62, but you can download the latest MeshCentral Router now on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html). Let me know if that works.

**Comment by LPJon** [comment]
> 
> 
> Thanks for reporting this. It was reversed forever and never reported. Fixed it in MeshCentral v0.7.62, but you can download the latest MeshCentral Router now on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html). Let me know if that works.

@Ylianst This does not work! I just upgraded MeshRouter from the meshcentral.com website and it is now pulling up putty for RDP connections from MeshCentral with Putty instead of Remote Desktop Connection from Windows 10 20H2. Working version of MeshRouter is v1.1.7649. Non-Working version is v1.2.7704.

**Comment by Ylianst** [comment]
Arg! Working on it!

**Comment by Ylianst** [comment]
Ok, MeshCentral Router v1.3 now on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html). I reversed the changes from yesterday where I changed the internal identifiers and did a much better fix that only affects the UI. Let me know if that works.

**Comment by LPJon** [comment]
@Ylianst I can confirm that it is now working as expected. :-)

**Comment by Ylianst** [comment]
Excellent. Thank you so much for the quick report on this! Much appreciated.

**Comment by MatinatorX** [comment]
Confirmed here as well!
