### ISSUE TITLE
Desktop Multiplex might create the "Error, duplicate agent connection" ?

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2249]
Hi,

It's always me :-) , 
I'm sorry to open all these issues and to add you work.  

This is what happened this morning : 
Updated to 0.7.61, started a RDP session on a computer for testing. My colleague started a RDP session too on the same computer. When he started his session an "Error, duplicate agent connection" occurred.

Here is the result of the Trace :

09:59:23,"relay","DesktopRelay: Soft disconnect (13.***.***.***.***)"
09:59:16,"relay","DesktopRelay: Error, duplicate agent connection"
09:59:16,"relay","DesktopRelay: Connection (81.***.***.***)"
09:59:16,"webrequest","(81.***.***.***) /meshrelay.ashx/.websocket?p=2&nodeid=node//mLKFhjbCeLfgM8****"
09:59:16,"relay","DesktopRelay: Connection (13.***.***.***.***)"
09:59:16,"webrequest","(13.***.***.***.***) /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//mLKFhjbCeLfgM8****"
09:59:05,"relay","DesktopRelay: Connection (81.***.***.***)"
09:59:05,"webrequest","(81.***.***.***) /meshrelay.ashx/.websocket?p=2&nodeid=node//mLKFhjbCeLfgM8****"
09:59:05,"relay","DesktopRelay: Creating new desktop multiplexor"
09:59:05,"relay","DesktopRelay: Connection (13.***.***.***.***)"
09:59:05,"webrequest","(13.***.***.***.***) /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//mLKFhjbCeLfgM8****"

So, I tried to comment the "Desktop Multiplex" option in my config.json and the problem disappeared.
Have you already seen that ?

I thought to have found the solution at my DuplicateAgentCount, but not ...

Have a nice day !

**Comment by Ylianst** [comment]
Are you starting a remote desktop session? or a RDP session? RDP is a Windows protocol. Thanks.

**Comment by elpibedeoro** [comment]
Sorry, I may not have being correct. I mean the desktop session through the meshcentral web interface.

**Comment by Ylianst** [comment]
There must be something missing from your report. I just tested the desktop multiplexor and it works well. When enabled, it will hold one connection to the agent and split the remote desktop stream to all the browsers. In your case, the agent was asked to connect twice which should not be possible. Is there anything special about your server setup? Thanks.

**Comment by elpibedeoro** [comment]
Reading your explication, I understand what I missed is my colleague made a remote desktop stream from its own meshcentral account and from its own computer. 
So what I tried to do was a double connection from 2 different accounts from 2 different computers at the same time.
We succeeded it, I mean we were connected at the same time but the error in the log appeared.

About my setup, I do not think to have done any special setups. 
Here my settings part : 
settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "MyAddressServer",
    "port": 443,
    "authlog": "/var/log/meshcentral/auth.log",
    "_DesktopMultiplex": true,
    "Log": "main,web,webrequest,cert",
    "syslog": "meshcentral",
    "_WebRTC": true,
    "plugins": {
      "enabled": false
    },
    "maxInvalidLogin": {
      "time": 10,
      "count": 5,
      "coolofftime": 10
    }
  }

Thank you.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
