### ISSUE TITLE
Feature Request - Allow "Guest Share" to enable "Files" tab for guest file access on client

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2250]
@Ylianst I ran across a situation yesterday where a vendor needed to upload some files to complete a software installation on a machine they were working on. Our work around was for them to email me the file and for me to upload it for them. It would be nice to give a guest share the ability to upload files on the fly. Is that something that is doable?

**Comment by Ylianst** [comment]
Certainly doable, just more work :) I always wondered how much the guest sharing link system would be pushed. it seems to be in good demand.

**Comment by LPJon** [comment]
It is a very useful option and I really like the fact that you have it in MeshCentral. It's so much easier than having to create individual accounts for Vendors who only need a "One Off" connection. I'm not asking for it right this minute I know you guys have a lot moving, but I wanted to be sure I didn't forget about it.

This feature alone is one of the reasons I switched to your platform. We are loving how well you guys have done with this. All of the features of a very expensive 3rd Party service that's been wrapped up in something we can control, is well supported, the DEVs listen to the customer needs, and most of all is not limited. You guys really are awesome at what you do and I believe it's because you love what you do. I'm a Linux and Windows network administrator/webmaster/engineer/security analyst. I can't contribute in code (Unless it's Bash/Sh/Command-line/Power-Shell), but I have a wealth of knowledge that is always at your disposal if you ever want to ask someone questions. Any way I can help I'm willing because I want to see this project continue for as long as possible.

**Comment by Ylianst** [comment]
MeshCentral v0.8.6 has improved guest sharing with file support. Can you give it a try and let me know if it works? Thanks.

**Comment by LPJon** [comment]
Yes this works.....Awesome! Thanks for all your hard work.
