### ISSUE TITLE
Customising Mesh agent?

### ISSUE THREAD

**Issue by Botric** [Ylianst/MeshCentral#2251]
Hello,

is there a way for information to be hidden on the 'Mesh Agent V2.exe'
for example, for the server URL, mesh identifier, server identifier?
also, is there a way to change the name of the title of the application form 'mesh agent V2'?

I have looked in sample-config-advanced.json and there are some settings for the agent but not all of the ones I am looking for,
 
![image](https://user-images.githubusercontent.com/66216920/106824464-c7428200-667a-11eb-8e3c-3860a77a093b.png)

**Comment by Ylianst** [comment]
You can customize the agent by adding the following in the domain section of the config.json:

```
      "agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      }
```

Let me know if that works.

**Comment by robclay** [comment]
Can I change this after a few months of using MC?  In other words, will it mess up any of the existing client installs?  Or will it all be okay?

**Comment by vitko-bg** [comment]
All should be OK, as in my case I moved to customization on later stage. All old MC Agents are connected fine.

You have to keep in mind that if you adding agent to AV exceptions, it won't be anymore in MeshAgent folder, it will be in folder which stated in config.json

"companyName": "MyCompany", <-- folder name in Program FIles
"serviceName": "myservice", <-- filder name in MyCompany folder in Program FIles

**Comment by Botric** [comment]
> 
> You can customize the agent by adding the following in the domain section of the config.json:
> 

I have looked in here but I am unsure where it shows I can hide the '_installation section/parts_' from that section 

I have been able to work out the application name and fix 

was wondering if the information is stored under MeshCentral/agents/meshagent64.exe

**Comment by Ylianst** [comment]
If you want additional customization of the agent, please open a new issue and be as detailed as possible. Thanks.
