### ISSUE TITLE
MeshCentral Messenger customization, No messenger prompt on remote desktop.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2255]
I've added the new feature MeshCentral Messenger customization to my config.json. 
But then when I start a messenger, Its waiting forever to be accepted by the remote end. But on the remote end there will be no prompt at all. This happens on all type desktops (Windows, MacOS, Linux)

**Comment by Ylianst** [comment]
Does this happen only when MeshCentral Messenger is customized? - Thanks.

**Comment by hunter-nl** [comment]
> Does this happen only when MeshCentral Messenger is customized? - Thanks.

Yes

**Comment by Ylianst** [comment]
Oh! Let me check again.

**Comment by hunter-nl** [comment]
Solved with new agent
