### ISSUE TITLE
Error uninstall Mac High Sierra

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#2258]
Hi, I'm having trouble trying to uninstall the agent from the console. I get the following error:

uncaughtException1: Error: => EventEmitter.emit (): Event dispatch for 'Command' on 'MeshAgent' threw an exception: LaunchDaemon (undefined) NOT FOUND in method 'handleServerCommand ()'

**Comment by krayon007** [comment]
> Hi, I'm having trouble trying to uninstall the agent from the console. I get the following error:
> 
> uncaughtException1: Error: => EventEmitter.emit (): Event dispatch for 'Command' on 'MeshAgent' threw an exception: LaunchDaemon (undefined) NOT FOUND in method 'handleServerCommand ()'

Do you have a copy of the MSH file for your agent? (you can redact any sensitive info)
I just tested on macOS 10.13.6 with and without agent customization, and the uninstall from the web ui seems to work fine. What server version are you using?

**Comment by mrkacg1** [comment]
Hi, I think the error was caused by the service not being fully loaded. Then I was able to uninstall without errors. Thank you

**Comment by aaronzufall** [comment]
@mrkacg1 Can you elaborate on what "service not being fully loaded" means? I'm running into the same issue, and I've tried everything including reinstalling the server core.
