### ISSUE TITLE
MeshCentral Router forgets mappings after restart

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentral#2259]
Is it normal behaviour that MeshCentral Router (macos) forgets the mappings after it restarts ? It's a lot of work to add them all again. Is there a way to automate this (or to save them) ?

**Comment by vitko-bg** [comment]
I believe it is normal to forget mappings on MC Router restart, for me it is same. Unfortunately I am not using MC Router on mac os, but on windows there is an option to save mappings to a file and to open them on later stage after MC Router restart:

![image](https://user-images.githubusercontent.com/59362521/107040878-b51a2e00-67b7-11eb-9fbe-16411dfbe273.png)

**Comment by drnikcuk** [comment]
Would be great in the router looked for mappings and loaded them on launch !

**Comment by Ylianst** [comment]
Once you create your mappings, save them using the "Save mappings..." feature. You will get a .mcrouter file. You can associate the .mcrouter extension with MeshCentral Router and when you click on the file it will open MeshCentral Router and bring your mappings back.

One more trick. You can edit the .mcrouter file with notepad and add the password line below:

```
{
  "hostname": "xxxx.meshcentral.com",
  "username": "bob",
  "password": "xxxxxxxxxxx",                       <---------------
  "certhash": "02403...",
  "mappings":[
    {
      "nodeName": "Tiny1",
      "meshId": "mesh//7b4b43cd...",
      "nodeId": "node//4QBHyPR0...",
      "appId": 1,
      "protocol": 1,
      "localPort": 51840,
      "remotePort": 80
    }
  ]
}
```

Then, when you click the file it will auto-login and put the mappings. Let me know if that works.

**Comment by vtacquet** [comment]
There must be something wrong with my version. When I open de .mcrouter file (directly or via File - Open), it doesn't reload the mappings. When I open the file with an editor the mappings are there (so the Save function works). This is the mac version of MeshCentral Router !

**Comment by vtacquet** [comment]
My version is 0.0.3 (1)

**Comment by vtacquet** [comment]
@Ylianst Do you want me to create a new ticket about the mac version 'Open' function not working ?

**Comment by Ylianst** [comment]
If you can send me a .mcrouter file that does not load privately, [send it over here](https://www.meshcommander.com/contact-information). I want to see if there is a chance the .mcrouter file is corrupt in some cases. Thanks.

**Comment by Ylianst** [comment]
Ok, the .mcrouting files are saved without the "certhash" entry. I not have to investigate why.

**Comment by Ylianst** [comment]
MeshCentral Router should be working now. If not, please open a new ticket. Thanks.
