### ISSUE TITLE
Will mesh work on Wifi or will it work only on Lan

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#226]
Hi ,

Wondering if mesh can work on Wifi alone or does it need lan network always  ?

regards
arun

**Comment by Ylianst** [comment]
Hi. MeshCentral will work on any IP network, so both WiFi or LAN will work. So the connection between the MeshAgent and MeshCentral is pretty much the same as a typical browser.

If you are asking about Intel AMT which is not required to use MeshCentral. There is currently not automatically setup WiFi profiles within Intel AMT.

Hope it helps,
Ylian

**Comment by Arun0711** [comment]
thanks for the update
