### ISSUE TITLE
2f authnication using SMS

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2261]
I have configured twilio sms by editing config.js.

Now i am getting option for **Manage phone number** and i received the sms code in my phone.

But after verifying the OTP  2F authication using SMS is not working.

All other options like email & Authenticator apps are working properly.

I assume the special charcter i am using will create problem ( i am using indian number starts with +91 followed by 10 digit phone number. )

request you to do the needful.

Thanks,
VINISH

**Comment by Ylianst** [comment]
"SMS is not working." is not sufficient details to post an issue, I need to be able to make the same problem happen on my computer. Your not posting sufficient details for someone else to replicate the problem.

**Comment by VINISHVV** [comment]
@Ylianst - Thanks, 
SMS is working properly, i just made a mistake user phone number not mentioned in application.
Thanks once again
