### ISSUE TITLE
tlsOffload not working in meshagent

### ISSUE THREAD

**Issue by axeprpr** [Ylianst/MeshCentral#2263]
Thank you for providing such a good product. My English is not very good, so my questions may be difficult to read.
i set the tlsOffload to true because i want to use meshcentral in my website by iframe and without nginx or other proxy.
it works. but when i download the meshagent, the server url shows as wss://xxxxxx, and it can not connect to meshcentral.
tls is not important for me. can i turn it off completely?

**Comment by Ylianst** [comment]
Hi. The MeshAgent must use wss://, it can't connect to the server without TLS. When you set "TlsOffload", the server will not do TLS, but it will assume that software like NGINX will do TLS in front of the server.

You can still put MeshCentral within an iframe even with TLS. In the settings section of config.json, put this line:

```
"allowFraming": true
```

Hope that helps,
Ylian

**Comment by axeprpr** [comment]
Thank you for replying to me so quickly. I got the result I expected.
Another question, I need to pre-install the mesh agent in my client. I noticed that meshagent carries meshcentral server information, possibly device group id, etc. Is there any way to get a original meshagent, i can configure it later in my code?

**Comment by Ylianst** [comment]
Hi. Yes, you can get the original MeshAgent in `node_modules/meshcentral/agents`. You can then create your own .MSH text file.

**Comment by Ylianst** [comment]
Note that Bryan just put the .MSH file format details on the new [MeshAgent readme page](https://github.com/Ylianst/MeshAgent).

**Comment by axeprpr** [comment]
I see. Thank you for your support. that's very kind of you.
