### ISSUE TITLE
Create Account "Send invitation email" greyed out.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2265]
![Untitled-2](https://user-images.githubusercontent.com/42086791/107307377-97b5c000-6a54-11eb-8982-f21000f790d2.png)

For some reason this checkbox is greyed out. The email server is configured properly and email verification/password reset emails can go out, but it's not sending emails to users informing them an account was created for them (presumably because the checkbox is not selectable). This also means the random password feature is broken, since the user is not informed what that password is.

Wondering if I've forgotten a configuration option somewhere!

**Comment by SurrounDTech** [comment]
I think you will need to have Force password reset on next login and Email is Verified ticked before you can tick Send invitation email

**Comment by MatinatorX** [comment]
Aha, you're correct! Thanks for the tip! Issue closed.
