### ISSUE TITLE
Feature Request: Custom CSS/image resources per domain/tenant.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2266]
Had a read of the Reddit thread [here](https://www.reddit.com/r/MeshCentral/comments/imwj1t/can_the_font_size_be_changed/) and the issue [here](https://github.com/Ylianst/MeshCentral/issues/1683) and was delighted to see that custom CSS and images are easily supported. However, I was wondering if these customizations could be taken a step further and offered per tenant/domain, so that each tenant portal could have their of look and feel.

Perhaps a configuration option in the domain section of config.json that points to a directory to use for resources instead of `/opt/meshcentral/meshcentral-web/public/styles/` or `[directory with meshcentral-data]/meshcentral-web/public/images`.

Would really go a long way to help differentiate different tenants on the same meshcentral server!

**Comment by Ylianst** [comment]
Good request. This is already support but undocumented feature. Try this:

```
/opt/meshcentral/meshcentral-web-mydomain/public/styles/
/opt/meshcentral/meshcentral-web-mydomain/public/styles/
```

"mydomain" here must be the same domain identifier string that you have in your config.json. Let me know if that works.

**Comment by MatinatorX** [comment]
In my case, `/opt/meshcentral/` does not exist. My directory structure currently looks like this:
```
/home/username/node_modules/meshcentral/public/images/
/home/username/meshcentral-data/
/home/username/meshcentral-web/public/images/
/home/username/meshcentral-web-domain2/public/images/
```
I grabbed some images from `/home/username/node_modules/meshcentral/public/images/`, made 2 different versions of them, and put one new set each in `/home/username/meshcentral-web/public/images/` and `/home/username/meshcentral-web-domain2/public/images/`.

The images I put in `/home/username/meshcentral-web/public/images/` show up on both the default domain as well as domain2. Should I be using the FQDN for the folder names, including the default domain?

**Comment by Ylianst** [comment]
So, regardless of the directory structure your using, create a `meshcentral-web' and 'meshcentral-web-domain` in the same folder that contains `meshcentral-data`.

When loading an image, it will first go to the domain specific folder: 'meshcentral-web-domain'. If there is no image, it will go to main folder 'meshcentral-web'. If there is no image there, it will use the default in the `node_modules` folder.

**Comment by MatinatorX** [comment]
I am unfortunately not able to get it to use the images in the domain-specific folder. All domains are loading images from `meshcentral-web` even with a `meshcentral-web-domain` sitting next to it (named to match the domain of course).

I have tried using both the FQDN (for example `meshcentral-web-www.google.com` or  `meshcentral-web-google.com`) as well as the domain property name in config.json (for example `meshcentral-web-google`). Both the `meshcentral-web` and `meshcentral-web-domain` folders have an identical file structure/naming and permissions, just with some scribbles on them in the domain specific folder.

I must be doing something simple wrong, but I can't seem to figure out what it is.

**Comment by Ylianst** [comment]
Ok, I will have to take a look at it. Maybe it's not implemented.

**Comment by MatinatorX** [comment]
Poking at meshcentral,js, it looks like the feature is there starting on [Line 1183](https://github.com/Ylianst/MeshCentral/blob/9e06a24975ff6e1fc49d00b1c4e579a34e89033c/meshcentral.js#L1183), so I assume I'm just getting the directory naming wrong after `meshcentral-web-`. I poked around trying to figure out what the value of the "i" variable should look like but got a bit lost in the code...

**Comment by Ylianst** [comment]
Can you give me an example image your are trying to change? This way I can test using the same image you are trying to change. Thanks.

**Comment by MatinatorX** [comment]
Sure, here's my test image. I have the green version in `meshcentral-web\public\images\` and this yellow version in `meshcentral-web-test\public\images\`
![icons256-3-1](https://user-images.githubusercontent.com/42086791/107419505-e19ab680-6ae5-11eb-848b-d2f90d9af310.png)

**Comment by MatinatorX** [comment]
Github seems to have renamed it, but I have it named icons256-3-1.png.

**Comment by MatinatorX** [comment]
I decided to also test adding the directory to config.json file by adding this line in the domain section:
`"WebPublicPath": "/home/username/meshcentral-web-domain2/public/",`

Unfortunately this didn't work either, everything still loaded from `meshcentral-web`. Removing the `meshcentral-web` folder just caused the default resources to load.

**Comment by si458** [comment]
this should be fixed in new releases, please update and try again
if issue persists, plz reply back

**Comment by MatinatorX** [comment]
Can confirm this has been fixed for a while, I currently have custom images/css/email templates etc. working per domain/with tenancy with no issues 👌
