### ISSUE TITLE
Bug: Authenticator 2FA QR Code Shows Wrong Domain for Tenant Portals

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2267]
Scanning the QR code for 2FA is showing the main portal domain when scanned even from a tenant portal/domain. It still works fine for logging in, but can't rename it in the Google Authenticator app. On version 0.7.58.

**Comment by Ylianst** [comment]
Oh. Thanks for reporting that!

**Comment by Ylianst** [comment]
Your right. If the domain has it's own DNS name, the QR code link is wrong. Working on it.

**Comment by Ylianst** [comment]
Checked in the fix, will be in MeshCentral v0.7.66.

**Comment by MatinatorX** [comment]
Will do, thanks!

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.7.66 is out.

**Comment by MatinatorX** [comment]
Confirmed fixed in v0.7.66, thanks again!

**Comment by Ylianst** [comment]
Nice. Thanks for reporting it.
