### ISSUE TITLE
package meshcentral as an offline installation package

### ISSUE THREAD

**Issue by axeprpr** [Ylianst/MeshCentral#2268]
hi Ylianst,
is there any way to package meshcentral as an offline installation package?
i try to use node-pkg to do this and not going well.

**Comment by Ylianst** [comment]
No official way to do that, but if you run `npm install meshcentral` and get the server running, you can then zip the "node_modules" folder and re-deploy it anywhere you want offline. Just note that if you use extra features in the config.json, that may trigger the need for more dependency modules to be installed. Hope that helps.

**Comment by axeprpr** [comment]
thank you.
