### ISSUE TITLE
Feature Request: Different SMTP account per domain.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2269]
Now that we're jumping headfirst into multi-tenancy with our Mesh install, it would be great to be able to use a different SMTP account per domain so that email notifications can be further customized for different customers.

(Sorry for all the requests today!)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.68 with support for this. You can cut & paste the "smtp" section and place it in one or more domains and it should work. Let me know if it's working for you.

![MC2-DomainEmailServer](https://user-images.githubusercontent.com/1319013/107571889-5b8f7600-6ba0-11eb-816d-96e26188038d.png)

**Comment by LPJon** [comment]
@Ylianst So....how do you configure the account to send with and the port to use for each of these?

**Comment by Ylianst** [comment]
So, each "smtp" section needs to be complete and correct. If you don't specify the port in one of the domains, it will not take the parent port setting. So do specify the port and everything you need in each one.
