### ISSUE TITLE
Unknown command "nwslist"

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2270]
Hi,
Testing the console's commands, I've realized that the command "nwslist" doesn't work.
_> nwslist
Unknown command "nwslist", type "help" for list of avaialble commands._

Is there a sort of "documentation" about these commands ? It would be useful.

**Comment by drnikcuk** [comment]
Seeing the same here:

![image](https://user-images.githubusercontent.com/6532805/107366330-ec4d4f80-6ad5-11eb-8712-99811ec96d02.png)

![image](https://user-images.githubusercontent.com/6532805/107366361-f7a07b00-6ad5-11eb-9d70-40098dd47352.png)

**Comment by Ylianst** [comment]
I think this is a type and the command is "wslist", but I will check.

**Comment by Ylianst** [comment]
It's a typo, should be "wslist". I just fixed it, will be in MeshCentral v0.7.67. I will close this since it's small. Thanks for reporting it.
