### ISSUE TITLE
Something wrong with the "Type"  copy/paste function 

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2274]
Hi,

When I want to copy/paste some text through the "type" button, the string that contains several characters, that are repeated several times, is cut.

![type_button](https://user-images.githubusercontent.com/76168733/107383379-398aea80-6af1-11eb-817e-ffa79064be37.png)

Thanks for your help.

**Comment by OutbackMatt** [comment]
#2126
#2035
#2078
#2039
