### ISSUE TITLE
[question] How to force push agent update from the server to clients with the option "noagentupdate": true

### ISSUE THREAD

**Issue by PTR-inc** [Ylianst/MeshCentral#2275]
We're using the "noagentupdate": true setting on our setup and individual agent updates through the client console works like a charm. So testing is possible before the roll-out of the updated agent, big thanks for that option btw.

My questions is, is there an option to force push the agentupdate to all the clients after all testing is done? Like a serverconsole command or through the 'run commands' group action?
I looked through all the discussions and the docs for something like this, but can't find it. And changing the config option every time is possible, but seems a bit cumbersome.

**Comment by Ylianst** [comment]
Yes, click on a device, go to the "Console" tab and enter "agentupdate". If you like, you can also type the "versions" command before and after to check that it really updated.

**Comment by PTR-inc** [comment]
Ah oké. If you could put it on the request list... :-)
