### ISSUE TITLE
Clipboard Paste not working

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2276]
After updating today to the latest version the paste function in the clipboard popup does not work.
it does say "Succes" but when pasting in the remote machine it does not register something to paste.

Copy function works fine

**Comment by Ylianst** [comment]
Weird, I do not think we changed anything to that part of the code. Will check.

**Comment by Allowee** [comment]
I upgraded from a version that was released at the end of december I think.
Also checked the console, no errors

**Comment by Ylianst** [comment]
What server version are you using?

**Comment by Allowee** [comment]
Mesh 0.7.66 running on windows server 2012 R2
> versions
{
    "node": "11.10.1",
    "v8": "7.0.276.38-node.17",
    "uv": "1.26.0",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.15.0",
    "modules": "67",
    "nghttp2": "1.34.0",
    "napi": "4",
    "llhttp": "1.1.1",
    "http_parser": "2.8.0",
    "openssl": "1.1.1a",
    "cldr": "34.0",
    "icu": "63.1",
    "tz": "2018e",
    "unicode": "11.0"
}

tried multiple agents all were working before and now they dont paste

**Comment by LPJon** [comment]
@Ylianst I have also just checked and confirmed this issue. You can pull the clipboard from the agent machine but not push to it. MeshCentral v0.7.66 

Agent Version:
```
versions
{
  "openssl": "1.1.1i",
  "duktape": "v2.3.0",
  "commitDate": "2021-02-07T23:26:53.000Z",
  "commitHash": "43c5f2d1b57a9f477d3afec13e2873ed19bfd573",
  "compileTime": "15:55:41, Feb  7 2021"
}

info

Current Core: MeshCore CRC-1684278636
Agent Time: 2021-02-09 16:45:43.263-06:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://\<hidden url\>:443/agent.ashx.
OS: Windows 10 Home - 1803 [17134].
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, wifi-scanner-windows, wifi-scanner, win-console, win-info, win-securitycenter, win-terminal, win-virtual-terminal.
Server Connection: true, State: 1.
```

**Comment by Ridd01** [comment]
Same on linux clients.

**Comment by I2700I** [comment]
Same on Windows and Mac.

**Comment by VINISHVV** [comment]
We can pull the clipboard from the agent machine but not push to it. MeshCentral v0.7.68

**Comment by tranbert** [comment]
Just updated to 0.7.70 still not working when pasting to remote machine. (french keyboard / french windows chrome)

Type function is still Ok but with double character not printed cf #2274

**Comment by krayon007** [comment]
What OS is the remote machine? And which clipboard are you using? Does get/set clip work on the console tab?

**Comment by tranbert** [comment]
Os windows 10.fr on remote and local

clipboard via screen icons 

And yes get clip works, setclip seems ok. 

> setclip coucou
Setting clipboard to: "coucou"

But "coucou" is not pasted on remote text editor when crtl-v (don't know if it's a normal way...)

**Comment by LPJon** [comment]
> 
> 
> What OS is the remote machine? And which clipboard are you using? Does get/set clip work on the console tab?

@krayon007 @Ylianst Windows 10 x64 20H2 on all the agents. This is the "Clipboard" button on the bottom right of the screen on the "Desktop" tab. "Set Clipboard" on the "Remote Clipboard" window is what is not working. There is input in the agent console which is in JSON format and does contain a "data" field with the data I set in the window. It does not indicate an error.

```
setClip: {"action":"msg","type":"setclip","data":"adfadsfadsfas","sessionid":"user//<email address>/<meshID>","rights":<number>,"consent":0,"username":"<username>","realname":"<users name>","userid":"user//<usernameid>","remoteaddr":"<agent public ip>","privacybartext":"Connected with a Laptop Pitstop® Hyper Connect™ Technician"}
```

The above is what you seen when trying to SET the clipboard. I have omitted certain information.....if you need it let me know and I can provide it to you securely. 

I am not sure how to use this feature from the console tab. Could you please explain how to do this?

**Comment by Scaff31** [comment]
Another bug

When you try to use the "type" button on PowerShell with the "get-addomaincontroller" command on some windows, it removes duplicate characters and on others it triples the character

Local type = get-addomaincontroller
Remote type = get-adddomaincontrolller or get-adomaincontroler

**Comment by pedjateg** [comment]
I have same problem with paste from clipboard on Windows 7 and Windows 10 clients:
`setClip: {"action":"msg","type":"setclip","data":"192.168.19.51","sessionid":"user//admin/91d7590c541d5f999e71143a9293391a0d76c436","rights":4294967295,"consent":0,"username":"admin","userid":"user//admin","remoteaddr":"188.x.x.x"}`

**Comment by p-m-tech** [comment]
I have the same issue. 
Server Version: 0.7.72
Agent Compile Time: 15:55:41, Feb 7 2021

**Comment by PetieM** [comment]
Any updates on this? Confirming that I'm still seeing this issue on 0.7.78 and have been since the initial report. Both variants of get (clipboard button on the left and download button on the right) work but set, while it shows "Success" on the left clipboard button, does not function on either side.

**Comment by Ylianst** [comment]
I will put some energy on this issue on Monday, hopefully I will fix this ASAP. It would be nice to have a way for people to "up-vote" their top issue. This is clearly the leading one right now.

**Comment by krayon007** [comment]
I just fixed this issue server side for now. It should go live the next time Ylian updates the server. I'm not sure if there was a windows update that broke this or what, as I haven't touched this code in a very long time... But it looks like when setting the clipboard, it must be done from an interactive process for it to take effect. It looks like setting it from a process using token impersonation is not sufficient. (Tho it seems fetching the clipboard from said process still works).  So I modified the meshcore.js to use spawn an interactive user process to set the clipboard on windows. 

This will cause a momentarily flash on the the screen when you set the clipboard, but that's a separate issue that I haven't found a solution for, as whenever I use the task scheduler to spawn an interactive user process, it will spawn a visible window, which I immediately set to hidden, which is why it flashes.

**Comment by I2700I** [comment]
@krayon007 Does that affect the "Type" function with its double symbols removal or that's a totally separate issue?

**Comment by krayon007** [comment]
I'll take a look at that next. I think that's separate, as it just feeds into keyboard injection. Looks like it needs some extra delay I think.

**Comment by Ylianst** [comment]
MeshCentral v0.7.79 is out with Bryan fix. Let me know if it works.

**Comment by krayon007** [comment]
> It's a bit slow given that it needs to pop up a window now but it otherwise seems to be working sending to the remote system. Retrieving from a remote system appears to work correctly on Windows but I can't get the remote clipboard in Safari on a Mac (presumably a security setting on the Mac side).

For you mac scenario... Is your remote machine a mac, or is your local machine a mac? I just tested setting/getting the clipboard on my M1 Big Sur system. If you give me more details about your setup, I can check that specific scenario.

**Comment by PetieM** [comment]
Sorry about that - definitely should have been more clear. Get/Set works from Windows local to remote Mac. Set works from Mac (local) but get does not work from a remote machine to a local Mac. Hopefully that makes sense?

**Comment by tranbert** [comment]
> 
> 
> MeshCentral v0.7.79 is out with Bryan fix. Let me know if it works.

For me from win10 to win10 working OK

**Comment by krayon007** [comment]
> Sorry about that - definitely should have been more clear. Get/Set works from Windows local to remote Mac. Set works from Mac (local) but get does not work from a remote machine to a local Mac. Hopefully that makes sense?

Which get mechanism are you using? The clipboard button on the desktop tab? I just tried on Safari on my mac, connecting to another mac, and getting/setting the clipboard. does `getclip` from the console tab work for your remote machine you are testing?

**Comment by PetieM** [comment]
The Clipboard button "Get Clipboard" does successfully return the clipboard from the remote machine. The button to the right that's supposed to also set your local clipboard in the process is what's not working.

**Comment by krayon007** [comment]
> The Clipboard button "Get Clipboard" does successfully return the clipboard from the remote machine. The button to the right that's supposed to also set your local clipboard in the process is what's not working.
> 
> Oh, and yes, "getclip" also does return the remote clipboard from the console.

Oh, ok, I see... This may be a browser issue. I know Chrome supports this feature, but I remember @Ylianst saying that Firefox does not support the API to get the local clipboard, so he disabled the ability to set the local clipboard to the remote machine on Firefox... We may need to do something similar on Safari...

**Comment by PetieM** [comment]
Makes sense. All of that said, it's functional one way or another now which is the important thing. Thanks for the quick follow-up!

**Comment by Ylianst** [comment]
If you look at the two clipboard icons on the bottom right.

![image](https://user-images.githubusercontent.com/1319013/109575932-a61d5780-7aa7-11eb-9ad0-75eb9cfcc38b.png)

You should see both in Chrome and only one is FireFox. The icon to pull the remote clipboard text from the remote machine to your machine is safe and should be available on all browsers.

The one that "pushes" your clipboard into the remote machine is not safe as any website would try to access the consent of your clipboard that could contain personal information. Not sure why, but Chrome supports this, FireFox rightful (in my view) does not.

I am checking Safari now. Looks like I am detecting that it supports this feature, but it does not work.

**Comment by Ylianst** [comment]
Ok, on Safari you hit the button to transfer your local clipboard to the remote device then you have to click "paste".

![image](https://user-images.githubusercontent.com/1319013/109579287-7709e480-7aad-11eb-932c-212980358cc6.png)

I tested this on my Apple M1 and it works for me.

**Comment by VINISHVV** [comment]
@PetieM - i am also having same issues but i overcome the issue using below method.

Get Clipboard  function is working fine so i am using same function for get the remote clipboard to my local system.

For set clipboard the function i am using the **type button**

![image](https://user-images.githubusercontent.com/65057910/109610128-56479a80-7b52-11eb-86cc-773aa743173a.png)

**Comment by PetieM** [comment]
> Ok, on Safari you hit the button to transfer your local clipboard to the remote device then you have to click "paste".

Okay, so that's the problem. I don't get that option to click Paste and can't seem to find a setting that I set that's blocking it. For me, when I click that same button, I just get a brief freeze and then nothing happens.

**Comment by supr4s** [comment]
Hi everyone,

Same behavior on my side.  "Get Clipboard" function working, but "Set Clipboard" not working.
We use firefox browser, and latest stable version of MeshCentral.

**Comment by Ylianst** [comment]
When you say "Set Clipboard" not working, does it say "Success" in green or not?

![image](https://user-images.githubusercontent.com/1319013/110183444-ba24ca00-7dc3-11eb-89e3-42fa02dd6d94.png)

**Comment by LPJon** [comment]
@Ylianst Yes! Says "Success" in green but when you paste, it's greyed out in the context menu or does not paste what you entered but instead pastes the last thing copied on the agent side.

**Comment by krayon007** [comment]
> @Ylianst Yes! Says "Success" in green but when you paste, it's greyed out in the context menu or does not paste what you entered but instead pastes the last thing copied on the agent side.

I assume you are testing with v0.7.79+ ?

**Comment by LPJon** [comment]
> > @Ylianst Yes! Says "Success" in green but when you paste, it's greyed out in the context menu or does not paste what you entered but instead pastes the last thing copied on the agent side.
> 
> I assume you are testing with v0.7.79+ ?

@krayon007 Sorry...yes! Your fix is currently working. I was assuming @Ylianst was working on a solution that didnt require task scheduler. He was describing the behavier before your fix.

**Comment by southeasterntech** [comment]
For me, on 0.7.82, clipboard buttons work both ways on Windows.  On Debian\Ubuntu Linux, neither the Get\Set method nor the clipboard buttons work to paste\send text to the Linux machine, but both methods work to retrieve.  (Tested on 2 separate Debian machines, Terminal paste works fine.)

**Comment by krayon007** [comment]
> For me, on 0.7.82, clipboard buttons work both ways on Windows. On Debian\Ubuntu Linux, neither the Get\Set method nor the clipboard buttons work to paste\send text to the Linux machine, but both methods work to retrieve. (Tested on 2 separate Debian machines, Terminal paste works fine.)

On your linux machines, do you have `xclip` installed? If not, the behavior can seem very different from windows, because linux has multiple clipboard buffers. Mesh Central uses the x11 clipboard buffer, which isn't accessible to all applications, since they can use any number of different buffers.  If you middle click the mouse, it will usually paste the x11 buffer. xclip will automatically do the legwork of integrating the different clipboard buffers.

**Comment by krayon007** [comment]
What I meant was, that Mesh Central will detect if you have xclip installed, and will use that to get/set the clipboard instead of using x11 directly.

**Comment by appleimperio** [comment]
Having the same issue copy and paste between local(Mac) and remote(Mac). Unable to copy and parte. getclip and set clip work ok but the Automatic clipboard is not working

**Comment by silversword411** [comment]
Clipboard thru browser is fraught with security problems. Search issues and you'll find lots of limited restrictions based on browser choice. 

Chrome has stopped it. Contact chromium.

Firefox has explicit permissions you have to manually grant. Also described in other issues. Search to find the workarounds.

**Comment by Yogesh1190** [comment]
> Clipboard thru browser is fraught with security problems. Search issues and you'll find lots of limited restrictions based on browser choice.
> 
> Chrome has stopped it. Contact chromium.
> 
> Firefox has explicit permissions you have to manually grant. Also described in other issues. Search to find the workarounds.

If we can use Get and Set Clipboard using button option then its working perfectly. But when We use automatic clipboard option, Set Clipboard working fine. But Get Clipboard not working.

Is this known issue ? Even I have download agent from the meshcentral.com and tested automatic clipboard functionality. Only Set clipboard is working. Get Clipboard doesn't work. Is this known issue ?

**Comment by silversword411** [comment]
A web page able to automatically capture the clipboard without interaction is a security risk.

This is why automatic clipboard sync is disabled

**Comment by jonny190** [comment]
Has this function been removed in recent builds as i have no option for clipboard

**Comment by si458** [comment]
@jonny190 nope nothing has been removed
Do u have the automatic clipboard enabled? 
If u do this hides the option

**Comment by jonny190** [comment]
> @jonny190 nope nothing has been removed
> Do u have the automatic clipboard enabled? 
> If u do this hides the option

I had turned it on for testing in Firefox but it wasn't working, that would explain it

**Comment by si458** [comment]
@jonny190 yes automatic clipboard doesn't work correctly in Firefox because of the way it does security, otherwise every time u copy something you would have to still click paste in the window for it to actually paste the data
So best to disable it in Firefox, but works a treat in edge/chrome
