### ISSUE TITLE
Android Agent not connecting

### ISSUE THREAD

**Issue by SoluOpenC** [Ylianst/MeshCentral#2277]
Hello I have a little problem.
first of all please thank this great thing that is meshcentral

I have a proxmox lxc with debian 10 and a meshcentral installation. I have updated it to the latest version 0.7.66 and everything is fine.
I try to add to test the agent mobile android and it does not show me in the list of agents
If I make a link of 1 hour, yes, but it is not functional, if I scan the QR, it tells me invalid

What do I need for the mobile agent to be active?

I have to say that if this vm goes to the internet but it does not have a public name, is it for this reason that the mobile agent does not show me?

a greeting

**Comment by Ylianst** [comment]
Is your server public on the Internet? If so, can you create a dummy account and send me your server URL and the dummy username and password? I will test the Android agent myself. [My contact info is here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by vitko-bg** [comment]
@SoluOpenC - please try with latest MC2, it should be fixed now.
I tested on my setup and all is working fine.
