### ISSUE TITLE
Intel AMT IDER 

### ISSUE THREAD

**Issue by NewUser92** [Ylianst/MeshCentral#2279]
Hi,

i have mounted an iso image using IDER. It took more than an hour for a mini-image of 10MB.
Can anyone tell me what could be the possible reasons?

I am a beginner to this concept.

Thanks in advance!

**Comment by Ylianst** [comment]
This is sadly normal. Intel AMT IDER uses the same Serial ATA protocol that hard disks use from a short cable and uses it over the Internet. If the latency on your network is high, it's going to take a lot of time between requests and responses.

I have found that on old Intel AMT devices, if you create the same disk image as a .img file, it's sometimes faster, but not sure why.
