### ISSUE TITLE
Can't view server on any port but 80

### ISSUE THREAD

**Issue by jordanhandy** [Ylianst/MeshCentral#2280]
Hi there,

Not sure if this is a bug, or I'm just missing something.  I've spent the better part of two days trying to troubleshoot this, and cannot seem to get it to work correctly, even watching some YouTube videos for support.

On my server, I currently have things running that already occupy port 80 / 443.
When I start MeshCentral, it seems to pick the next available ports (82 / 444 in my case)

No matter what I do, I cannot get to the MeshCentral dashboard on any port except 80 / 443.  I have no firewall and nothing in my ACL (took it down to test) so traffic flows without impedance, but I can't connect to the start page using any port != 80 / 443.

If I stop my services currently using 80 / 443 and restart MeshCentral again, it will occupy 80 / 443 and the web GUI is accessible as normal.  I want to be able to access the GUI without having to change my port configs and accomodate port 80 when it should be able to be changed.

Am I missing something here?

Thanks

**Comment by Ylianst** [comment]
Not exactly sure what you are asking, but in the config.json file, you can set the MeshCentral ports you want, for example:

```
{
  "settings": {
    "port": 444,
    "redirport": 88
  }
}
```

Hope that helps,
Ylian

**Comment by jordanhandy** [comment]
@Ylianst , thanks, but that wasn't really what I was getting at.  I've changed the ports in that config file to a myriad of different ports.  No matter what I change it to, the server is always inaccessible, unless the port is 80.  As mentioned above, I have no  firewall, and no ACLs, letting all traffic in, and out.

I have various other services running on different ports with no issue.  Is there something I'm missing that is crucial to config?

**Comment by jordanhandy** [comment]
This can be closed, no matter what I tried, standard install wouldn't work.
I used someone else's docker container with the same config.json, and it appears to work.

Thanks for responding anyhow.
