### ISSUE TITLE
No certificate was found in db

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2281]
@Ylianst 

I am getting error "No certificate was found in db" for few agents.  Can you suggest the actual problem behind this error.

Regards
VINISH

**Comment by krayon007** [comment]
That's normal in first start. . It's just informational.  If you are having connection errors, the easiest thing to do is run the agent in console mode, so you can see the connection related output.

**Comment by VINISHVV** [comment]
Thanks.
