### ISSUE TITLE
Agent removed automatically

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2283]
@Ylianst - 

Good evening,

I have upgraded my server to 0.7.68. After upgrade i found that few agents are automatically removed from the application.

can you suggest how we can over come this issue.

**Comment by Ylianst** [comment]
Your providing very little details. If the agent executable was removed, it could be that your running an anti-virus software that removed the updated agent. Would be interesting to know from what version you upgraded from.

**Comment by VINISHVV** [comment]
@Ylianst 

 I have upgraded the version from 0.7.65 to 0.7.68.

In my case agent executable is running in agent PC but the same is not showing in the meshcentral dashboard.

**Comment by Ylianst** [comment]
Note that there is no MeshAgent changes between v0.7.65 and v0.7.68. More information would be needed to know what is going on.

**Comment by VINISHVV** [comment]
Thanks... 
I have updates the agent manually.. Now it's working.
