### ISSUE TITLE
[error report] Mesh Crashes with Assertion `MaybePassAuthTagToOpenSSL()' failed 

### ISSUE THREAD

**Issue by Da-Geek** [Ylianst/MeshCentral#2284]
Morning All
So I have a mesh install running quiet well so far, but the server keeps crashing and restarting (systemd unit restarts the server
instantly) with a similar error in the `messerrors.txt`
This error has happened a few times now, and I am not sure what action is happening that triggers the issue.
Is this something that has been seen before?

ServerOS: CentOS Stream release 8
Mesh Version: 0.7.68
The server is using LetsEncrypt
Direct Internet Connection/Public IP

Any help or suggestions would be great.

```
-------- 2/11/2021, 8:45:02 AM ---- 0.7.68 --------^M
^M
/usr/bin/node[122879]: ../src/node_crypto.cc:3047:node::crypto::CipherBase::UpdateResult
node::crypto::CipherBase::Update(const char*, int, unsigned char**, int*): Assertion `MaybePassAuthTagToOpenSSL()' failed.^M
^M
^M
-------- 2/11/2021, 8:45:02 AM ---- 0.7.68 --------^M
^M
 1: 0x5610a62bf734 node::Abort() [/usr/bin/node]
 2: 0x5610a62bf83c  [/usr/bin/node]
 3: 0x5610a63d8e16 node::crypto::CipherBase::Update(char const*, int, unsigned char**, int*) [/usr/bin/node]
 4: 0x5610a63def9e node::crypto::CipherBase::Update(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/bin/node]
 5: 0x5610a654a19c  [/usr/bin/node]
 6: 0x5610a654bc99  [/usr/bin/node]
 7: 0x22c72cddbf1d ^M
^M
^M
```

**Comment by Ylianst** [comment]
What version of NodeJS are you using? My first suggestion would be to update NodeJS since these errors are not in the MeshCentral code.

**Comment by Da-Geek** [comment]
> What version of NodeJS are you using? My first suggestion would be to update NodeJS since these errors are not in the MeshCentral code.

```
[mesh@mesh ~]$ node -v
v10.23.1
```
```
10.23.1-1.module_el8.4.0+645+9ce14ba2
```

**Comment by Ylianst** [comment]
I am not able to reproduce this problem. If this is a common occurrence, I would update your NodeJS. The problem is that the error is not in the MeshCentral code.
