### ISSUE TITLE
force push agent update from the server

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2285]
@Ylianst  

good evening.
Version - 0.7.68

from last 2 days i am getting few agent PC's with no desktop / file options. when i run the agentupdate command from console it will working fine. can you suggest the actual reason behind this issue. 

since the count of agent is more than 100 manual update is little difficult.  can you check the feasibility for force push agent from server.

![image](https://user-images.githubusercontent.com/65057910/107663125-08591880-6cb1-11eb-9760-5a11d98caddb.png)

**Comment by Ylianst** [comment]
I have seen this before, restarting the server will probably fix this. You can go in "My Server" / "Console" tab and type "resetserver".

**Comment by VINISHVV** [comment]
@Ylianst 

can you check the feasibility for force push agent from server.

**Comment by Ylianst** [comment]
Ok, I can add a way to batch push from the server.

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.7.70, if the server is set to not automatically update agents, you can now select to batch update many agents at once using a new action in "Group Settings".

![MC2-BatchAgentUpdate](https://user-images.githubusercontent.com/1319013/108180596-d20a0780-70bb-11eb-921c-0ced836de54e.png)

**Comment by VINISHVV** [comment]
@Ylianst - Sorry for the late response.
This new feature works perfectly for me.
Thanks to entire meshcentral teams.
