### ISSUE TITLE
Collapse all groups

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#2286]
To quickly move to a group, it can be very usefull to have a shortcut 'collapse all' (and expand all) on top of the pc list:

![image](https://user-images.githubusercontent.com/68591647/107730560-02d0f200-6cf4-11eb-9810-2428a64e7531.png)

Doing so you can quickly open te required group and have a dedicated list on screen, instead of clicking 5x to close unrelevant groups.

**Comment by Ylianst** [comment]
Right click on the small arrow to open/close a group. You can select "Expand all" and "Collapse all". Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/107740435-f9c62d80-6cbf-11eb-9e2d-57180f9814b7.png)

**Comment by VINISHVV** [comment]
@Ylianst - it's works fine.... 
I am using meshcentral from 1year, but now I realise such feature is available. .... 


Appreciate all the team behind this tiny but unbelievable tool......

**Comment by Ylianst** [comment]
Nice. Next time, please close issue when done. Thanks.

**Comment by jdvmanen** [comment]
Nice, didn't know this. Great!

Op vr 12 feb. 2021 20:05 schreef Ylian Saint-Hilaire <
notifications@github.com>:
