### ISSUE TITLE
MeshCentral crashes Windows Server 2016 Essentials on login, causing system reboot.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#229]
I tested this on two of my servers, one a fresh install with nothing else but hardware drivers and the MeshAgent installed, and the other a healthy server which has not shown any prior issues. Steps to reproduce:

- Log in to MeshCentral web portal.
- Select an active node running Windows Server 2016 Essentials.
- Switch to Desktop tab and click connect.
- Log in to the machine.

At this point the remote view freezes. Disconnecting, then reconnecting results in "Setup" being displayed, with the connection never completing. Checking the node status reveals it has gone offline. After a few minutes, the node comes back. This does not happen every time, but definitely the majority of the time.

A quick check of the Windows Event Log reveals a new entry of "The computer has rebooted from a bugcheck." with string "SYSTEM_SERVICE_EXCEPTION". The bug check code is always 0x0000003b, and the crash address is always at ntoskrnl.exe. I have attached screenshots of the event details as well as the system details.

I have a few machines running Windows Server 2008 R2, Windows 10, and Windows 7. None have them have had any issues with MeshCentral.

![Crash1](https://user-images.githubusercontent.com/42086791/57494155-1127e980-7296-11e9-8cee-be5ea8d9acf5.png)
![Crash2](https://user-images.githubusercontent.com/42086791/57494160-12f1ad00-7296-11e9-80d9-bec41850fb7c.png)
![Crash3](https://user-images.githubusercontent.com/42086791/57494170-14bb7080-7296-11e9-9e9c-54cac66f19c1.png)
![Crash4](https://user-images.githubusercontent.com/42086791/57494174-16853400-7296-11e9-84e9-e7de96676777.png)

**Comment by PathfinderNetworks** [comment]
I have a few systems running Server 2016 Essentials (and a couple at Server 2019 Essentials) and am not seeing anything like that.  That said, on one of the Server 2016 Essentials boxes (which is a new Lenovo ST50 server) the MeshCentral2 agent has a memory leak and, if I leaving it running for a few days, will eventually consume all system RAM causing the system to become unresponsive.  It doesn't do that with the MeshCentral1 agent.  As a work around I created a scheduled task that stops and restarts the MeshCentral agent service every 12 hours until a permanent fix is created.  Odd thing is that it's the only system I have that acts like that.  So, in my case, it has to be something to do with the Intel hardware Lenovo is using on that ST50 system.  I wonder if this issue you are having is related in some way to the memory leak I see?

**Comment by Ylianst** [comment]
Interesting reports. Bryan will have to take a look at both of these. Bryan has a new MeshAgent coming hopefully next week that may help with the leak.

**Comment by CrazybernieNL** [comment]
We are having similar problems on machines running windows 10. Behaviour only occurs if we have to login remotely to the console. 

Steps to recreate: 
- Lock windows machine 
- Connect to the desktop using meshcentral  
- Send Ctrl-Alt-Del 

Machine freezes, screen becomes black , after a few minutes machine comes back online or not. 

We have this problem on different built versions of windows 10.

**Comment by MatinatorX** [comment]
Has this been looked into by chance? I've noticed that the MeshAgent project is being actively worked on with frequent commits, but the version number of the MeshAgent hasn't gone up since I first started using MeshCentral. I am about a week an a half behind though with server updates. Have there been any updates to the MeshAgent?

**Comment by adsgreen** [comment]
We are seeing the same behaviour on our windows 10 machines.
If you logout or switch user it sends the PC into recovery mode.

**Comment by Ylianst** [comment]
Is this still occurring? The MeshAgent has been updated a lot and hopefully this is a long gone behavior.

**Comment by MatinatorX** [comment]
I still see this occasionally yes, though I am on 0.4.5e still. I am not sure what version of MeshAgent some sites are running. Is there a way to easily update all of them to the latest version (once I uodate MeshCentral itself)? I've seen the option to clear and re-send the MeshCore but couldn't find reference to it in the documentation. All of mine say Core v6.

**Comment by MatinatorX** [comment]
Can confirm this is still a big issue on the latest build 0.5.9. Had one of our servers crash and restart 6 out of 10 connections through the web desktop control. Zero issues through MeshRouter/RDP. The server is running Windows Server 2016 Essentials - 1607 [Version 10.0.14393].

Tried it on a few other Server 2016 devices and also saw the same issue. Confirmed all systems are running the latest Mesh Agent Version: 2020-04-13 23:08:32.000-04:00.

Not sure if it helps, but I see a bunch of occurrences of this in the agent log, though they don't seem to match up with when the crashes happen:

```
[2019-11-06 11:17:02 AM] FATAL EXCEPTION [MeshAgent_0E6B60297D2ADB72.exe] @ [FuncAddr: 0x00007ff67bde2bb9 / BaseAddr: 0x00007ff67be496dc / Delta: 420643]

[2019-11-06 11:19:01 AM] FATAL EXCEPTION [MeshAgent_0E6B60297D2ADB72.exe] @ [FuncAddr: 0x00007ff67bde2bb9 / BaseAddr: 0x00007ff67be496dc / Delta: 420643]

[2019-12-06 05:15:56 PM] FATAL EXCEPTION [MeshAgent_6478498241E8A009.exe] @ [FuncAddr: 0x00007ff6b6e24f5e / BaseAddr: 0x00007ff6b6e7adec / Delta: 351886]

[2020-04-16 09:21:54 PM] FATAL EXCEPTION [MeshAgent_6478498241E8A009.exe] @ [FuncAddr: 0x00007ff603834f5e / BaseAddr: 0x00007ff60388adec / Delta: 351886]

[2020-04-16 09:43:42 PM] FATAL EXCEPTION [MeshAgent_6478498241E8A009.exe] @ [FuncAddr: 0x00007ff6948e2d9d / BaseAddr: 0x00007ff69494adec / Delta: 426063]
```

**Comment by MatinatorX** [comment]
Also, just poking through the event viewer I found this just after reboot:

`The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xffffc3e098a10438, 0xffffdb8170c89e20, 0x0000000000000000). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: 50ebb193-b398-4862-bf14-7cc606d38b93.`

**Comment by G12385** [comment]
The same here. Windows Server 2016 Hyper-V  BSOD after a guest - also Windows Server 2016 BSOD. 
This happens when I try to log off the machine. Screen freezes and guest along with hypervisor go offline. System log of both hosts shows event 1001, source bugcheck and  analysis indicates : BUGCHECK_STR:  0x3B_c0000005 DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT_SERVER, PROCESS_NAME:  MeshAgent.exe.

**Comment by MatinatorX** [comment]
This seems to be solved now, haven't had anything crash in forever. Going to close the issue.
