### ISSUE TITLE
Informational only.... 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2290]
@Ylianst 

I am planning to deploy a server with 15k agent PC's for my official use... 

Can you help me to share the required server specs and bandwith specification, db etc   for 300+ concurrent remote sessions.

**Comment by yomono** [comment]
[HERE](https://github.com/Ylianst/MeshCentral/issues/2037#issuecomment-737450643) Ylian says they use a 4gb RAM, 2 vCPU instance to run about the same amount of agents, so it should be a pretty accurate reference

**Comment by VINISHVV** [comment]
@yomono - thanks.
