### ISSUE TITLE
General Question: Has anyone been able to make a MeshCentral WinPE drive?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2292]
Hi MeshCentral Users,

I am wondering if anyone has made a generic WinPE for Windows testing and debugging, if so have you had success in enabling the windows stack with the network drivers and adding in MeshCentral agent to have it available on the servers you are running? 

If so can you give guide on how you achieved this? I have done the integrated WinPE with other drivers, but not as of latest build and the dependency of latest drivers from network vendors.

@Ylianst & @krayon007, In your testing have you also maybe done something similar? Just a question...

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
Personally I have not tried the MeshAgent on WinPE.

**Comment by SomeGuru** [comment]
@krayon007,

Thank you for helping me with the command to get this working... I think its gainful knowledge that we can  share with folks that the agent does run in WinPE the way it is downloaded. Just simply putting it on a USB key or the WinPE USB key and then navigating to the drive, like mine was D: and then running the agent **"special-agent.exe" run** then it will start in the CLI, but won't show details due to the limitations of WinPE. However was able to mouse, keyboard, and video (desktop mode) with the WinPE system... 

Thanks guys!,
SomeGuru

**Comment by SomeGuru** [comment]
![image](https://user-images.githubusercontent.com/48393851/109741220-793d7300-7b81-11eb-826e-2244ffb6a90e.png)

This is the Agent working in WinPE... Bravo!!!

SomeGuru
