### ISSUE TITLE
WebPush

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#2293]
Anyone been able to get webpush working ?

I've added the following to my settings, and it's registered as during starting i saw that webpush was installed (note: i had to change the format from what was listed on twitter to get it to load).

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment__": "This is a sample configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remov>
  "settings": {
    "WebPush": {
       "email": "myuser@emailaddress"
    },
    "_cert": "myserver.mydomain.com",
    "_mongoDb": "mongodb://127.0.0.1:27017",
    "_mongoDbName": "meshcentral",
```

I don't see the option to enable webpush in the account settings page:

![image](https://user-images.githubusercontent.com/6532805/107887266-ca503480-6efc-11eb-80cf-68f52f318802.png)

**Comment by Ylianst** [comment]
The "Enable web notifications" option in the "My Account" page has been present for a long time and is only visible when it's not already authorized. In FireFox, I did not approve it yet, so I see it:

![image](https://user-images.githubusercontent.com/1319013/107888852-d23fb280-6ec3-11eb-8a39-0c6c76534947.png)

Once I approve it:

![image](https://user-images.githubusercontent.com/1319013/107888866-ed122700-6ec3-11eb-93b0-15bd0fe43198.png)

My guess is that you already approved it a long time ago, so push notification should start working.

**Comment by drnikcuk** [comment]
Yup that was it, I reset the site permissions in chrome and then hey presto that option appeared.
