### ISSUE TITLE
What is the domain input box in web-based RDP viewer?

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2294]
Hi,

I have activated the webRDP option through config.js. 

while accessing the webRDP its ask the domain name. can you help which domain mentioned here.

![image](https://user-images.githubusercontent.com/65057910/107975265-deb82e00-6fdd-11eb-9598-f194fc4a4d6d.png)

**Comment by drnikcuk** [comment]
It's the domain from where the credentials are from ... So if you are using AD it would be the AD domain name or I think if it's standalone workstation you might be able to use the machine name or get away with nothing in that field ?
