### ISSUE TITLE
Invalid argument "removeaccount", use --help.

### ISSUE THREAD

**Issue by radamhu** [Ylianst/MeshCentral#2295]
**It seems there is no removeacount argument for meshcentral.js? Really weird.**

➜  ~ node node_modules/meshcentral/meshcentral.js --removeaccount user//radamhu
Invalid argument "removeaccount", use --help.

**This is my server information.**

➜  ~ node node_modules/meshcentral/meshcentral.js --help
MeshCentral v0.7.68, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcommander.com/meshcentral2

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --nedbtodb                        Transfer all NeDB records into current database.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.

**Deployed by npm i meshcentral.**

**Comment by vitko-bg** [comment]
This option has been removed - see here --> https://github.com/Ylianst/MeshCentral/issues/2220#issuecomment-769292818

**Comment by radamhu** [comment]
so this option is only available on the UI, thanks

**Comment by Ylianst** [comment]
"removeaccount" command in meshcentral.js was removed because it could not be used while the server was running and people where using it that way. Use meshctrl.js instead, to see what it's capable of:

```
node node_modules/meshcentral/meshctrl.js
```

Use the 'removeuser' command of MeshCtrl.js to do the same and it will work when the server is running, the UI will update correctly, etc. You can do many other things with meshctrl.js, so take a look at it.
