### ISSUE TITLE
How to make Intel AMT work ?

### ISSUE THREAD

**Issue by Philippe34** [Ylianst/MeshCentral#2296]
I use Meshcentral with the agents and it works fine.
Now, I'm trying to use Intel AMT. I think the configuration is good side server (Nginx + MeshCentral).

```
#systemctl status meshcentral
...
MeshCentral Intel(R) AMT server running on mesh.domain.fr:44330, alias port 4433.
```
But I can't get anything. 
When I go to the BIOS of the machin, nearly nothing about AMT. I just can see an "Enable MEBx Hotkey" and an "Enable USB provision". If I do "CTRL P" : nothing

If I go to Meshcentral interface, I can add a AMT Group, but if I want to add a device, I never have the OK button

![add-AMTDevice](https://user-images.githubusercontent.com/12435553/108045180-70a65200-7043-11eb-9f36-f5ff28319d7b.png)

I follow your youtube presentation of AMT, but I don't have as you "Agent, AMT, powered"
The only thing I get is "Agent, powered"

![Device-powered](https://user-images.githubusercontent.com/12435553/108045956-58830280-7044-11eb-9798-b6bc95d91701.png)

What could be bad with my AMT environment ? I think I don't understand the Intel AMT concept. Could you advise me some documentation ?

Thanks

**Comment by Ylianst** [comment]
Hi. First, to use Intel AMT you don't need to create a device group for "Intel AMT only" unless you don't want to install the agent. If you are ok with installing the agent, just create a normal device group and install the agent like you do normally. Next, click on a computer and see if Intel AMT is supported:

![image](https://user-images.githubusercontent.com/1319013/108126101-4746ef80-705e-11eb-87f8-15e837e9334c.png)

You can also go in the device console tab and type "amt" to get the full Intel AMT status for your device:

![image](https://user-images.githubusercontent.com/1319013/108126162-5fb70a00-705e-11eb-9eca-0ea3a0b0c205.png)

Intel AMT is a big topic, but you can start by watching the [introduction video here](https://www.youtube.com/watch?v=mxkGRpHHvgA).

**Comment by Philippe34** [comment]
Yes it was my intention to always install the agent. But as I can't see "Intel AMT", I have to suppose this is not supported by any of the computers we have (they are Dell laptop and Optiplex 7450 AIO computers). 
My General tab is not as detailled as yours. So I suppose now I have to find a computer with AMT supported.

![general-tab](https://user-images.githubusercontent.com/12435553/108190200-ef69c080-7111-11eb-955a-5ea063dda2e5.png)

![amt-detected](https://user-images.githubusercontent.com/12435553/108190465-440d3b80-7112-11eb-80be-65cd9191ff21.png)

I have all the answers I need to close the issue.
Thank you @Ylianst
