### ISSUE TITLE
[BUG] List mode - all clients are colored (even when dev is off)

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#230]
When in list view of my Devices, the icons are not greyscale if the device is offline.
However if you return to Column View, they are greyscale if offline.

See images below. (sorry for all the redaction's!! and my mspaint skillz)

![List Mode](https://user-images.githubusercontent.com/37466255/57565093-5f55fd80-73fa-11e9-907e-494cf3e9234d.png)

![Columns](https://user-images.githubusercontent.com/37466255/57565095-64b34800-73fa-11e9-9916-a8e4f76aa798.png)

**Comment by Ylianst** [comment]
Good report! I will fix this when I get a chance.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.4-c with a fix for this. Please confirm and close this issue if it's ok.

**Comment by theredkoala21** [comment]
I just noticed a bug with the Dark Mode. When you refresh the page it reverts to Dark Mode (even incognito mode - default to Dark Mode).

However it seems that v0.3.4-c has fixed the Dark Mode bug + List Coloring Bug.
Excellent work!!

Thanks

**Comment by Ylianst** [comment]
Thanks. Just published MeshCentral v0.3.4-d with more UI fixes. I published dark mode too early, but now it's looking pretty good.
