### ISSUE TITLE
mehscentral agent will it work on windows machine in kiosk mode?

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#2300]
Hi , maybe a dumb question but i need to know if meshagent will work on a windows 10 machine fully locked down as kiosk mode.
i will be able to do remote desktop and other things ?

**Comment by krayon007** [comment]
I just setup a Windows 10 machine in kiosk mode... The mesh agent works perfectly fine. I was able to remotely connect to the kiosk, and view the desktop, connect terminal, files, etc.

**Comment by VINISHVV** [comment]
@tradexsrl - it's working fine for me.. 
I am using latest version.... Please try upgrade once

**Comment by SomeGuru** [comment]
I just did this with a real KIOSK, trust me this option works very well... 

Just remember that the Windows 10 PC has to be locked down also... There are still ways to break out of the box if you craft a way on the Windows 10 machine at the end...

Group Policy Editor is your friend!!!

Thanks,
SomeGuru

**Comment by tradexsrl** [comment]
thank you for the reply. i'll tell my sales rep. we can use it to remotely assist our customer with pc in kiosk mode.
