### ISSUE TITLE
Encrypted password for user in script

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2302]
At the moment, I have a script that, when setting up MC2, checks for a specific account on the server and if it doesn't exist, the script creates that user and assigns it as an admin account. At the moment, the script uses `meshcentral --createaccount` but that of course, places the password as clear text in my build system:
```
meshcentral --createaccount mickey_mouse --pass "walt_disney"
```
I was hoping to be able to place an encrypted password in the script instead, perhaps with an option stating it's already encrypted so that MC2 doesn't encrypt it again as the `--createaccount` command is processed. Something like:
```
encryptedPwd=$(mkpasswd --method=SHA-256 "walt_disney")
meshcentral --createaccount mickey_mouse --pass-encrypted --pass "${encryptedPwd}" 
```
I know in the example above I'm putting the password in clear text, just wanted to show how it may work. In reality it would be used something like this:
```
# encrypt hint: cartoonist who wrote on his death bed: "Kurt Russel"
encryptedPwd="$5$5TJSjFoqOiGgq$O8sKYo5tOcdHCCsHmtfFI4hW6VPjfTd5s9Dulllv5ZA"
meshcentral --createaccount mickey_mouse --pass-encrypted --pass "${encryptedPwd}" 
```
Is anything like this possible?

**Comment by Ylianst** [comment]
Good question. In your example, you set a password with a simple SHA256 hash which is super basic. MeshCentral stores user passwords using 12000 rounds of SHA384 hashing with a 128 byte long salt that is generated from strong (hardware) random source.

I can do this, but you will have to run your plain password thru meshctrl.js to generate the resulting hash first. You can then put the hash in your script. If that is ok, yes, I can do that.

**Comment by Ylianst** [comment]
Ok, next version of MeshCentral v0.7.70, you can do this:

```
node meshcentral --hashpassword "walt_disney"
nFAVxD2Xe19/aDLYkv9GmtJjF3Glfw9++E8yEjDlTxgpBridzss/7M7ai1GaQXL2J3iRrmCQXJRWhd8Tq4UF5C5/uVr4bGODkuVz38DhFk9Wy60jPA0W50Sgm/bqZYOYrf1Vir8JXLntln/ePjAJn+R+Kk7ZiPc1ynL9UP/8l8I=,4Ks8JFcRaxvKYPEdWNs6bIAqOjOBKA0bEfJNYHLI/yKawCQ5cRM+3lQbnejyL4UI+qJ6k/+BSKQInDTsN26gptTqtAMIf0yEQLcP0EQBhg6q/JCi/dGLTAyDlVl7PXk+UhzW7oCOC627KdQF89mqz1eN7INOhfv6PNr1k6Daorw=
```

Then:

```
node meshcentral --createaccount admin3 --hashpass nFAVxD2Xe19/aDLYkv9GmtJjF3Glfw9++E8yEjDlTxgpBridzss/7M7ai1GaQXL2J3iRrmCQXJRWhd8Tq4UF5C5/uVr4bGODkuVz38DhFk9Wy60jPA0W50Sgm/bqZYOYrf1Vir8JXLntln/ePjAJn+R+Kk7ZiPc1ynL9UP/8l8I=,4Ks8JFcRaxvKYPEdWNs6bIAqOjOBKA0bEfJNYHLI/yKawCQ5cRM+3lQbnejyL4UI+qJ6k/+BSKQInDTsN26gptTqtAMIf0yEQLcP0EQBhg6q/JCi/dGLTAyDlVl7PXk+UhzW7oCOC627KdQF89mqz1eN7INOhfv6PNr1k6Daorw=
```

You can also do:

```
node meshcentral --resetaccount admin3 --hashpass nFAVxD2Xe19/aDLYkv9GmtJjF3Glfw9++E8yEjDlTxgpBridzss/7M7ai1GaQXL2J3iRrmCQXJRWhd8Tq4UF5C5/uVr4bGODkuVz38DhFk9Wy60jPA0W50Sgm/bqZYOYrf1Vir8JXLntln/ePjAJn+R+Kk7ZiPc1ynL9UP/8l8I=,4Ks8JFcRaxvKYPEdWNs6bIAqOjOBKA0bEfJNYHLI/yKawCQ5cRM+3lQbnejyL4UI+qJ6k/+BSKQInDTsN26gptTqtAMIf0yEQLcP0EQBhg6q/JCi/dGLTAyDlVl7PXk+UhzW7oCOC627KdQF89mqz1eN7INOhfv6PNr1k6Daorw=
```

Let me know if that works.

**Comment by Ylianst** [comment]
MeshCentral v0.7.70 was released with this feature.

**Comment by D4V3M0NK** [comment]
Beautiful, works like a charm Ylian, thank you sir!!
