### ISSUE TITLE
if setting wrong Credentials for AMT, can't modify Credentials  password in web

### ISSUE THREAD

**Issue by tair8022** [Ylianst/MeshCentral#2303]
mechCentral version:0.7.69
if setting wrong Credentials for AMT, can't modify Credentials  password in web

**Comment by Ylianst** [comment]
I will check this. Normally it should check the credential and if it does not work, it should indicate the credentials are wrong and allow you to change them again.

**Comment by Ylianst** [comment]
Starting with MeshCentral 0.7.73, the server will display "Trying Credentials" when you enter new credentials and they are not yet confirmed to be correct. You can still change them or wait until it returned to "Invalid Credentials" to change them.

![image](https://user-images.githubusercontent.com/1319013/108779736-34c82c80-751c-11eb-921f-b553dea32347.png)

Once published, let me know if that works.

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.7.73 has been released.

**Comment by Tomtreas** [comment]
I can't seem to get AMT creds to do anything.  It just sits forever, days in fact at Trying. I can get into my test computer's AMT with MeshCommander. Shows AMT v11.6.10

![image](https://github.com/Ylianst/MeshCentral/assets/76670586/0f62c777-9cd5-4683-ad82-5768d765cfcd)

**Comment by si458** [comment]
Are u sure that machine has amt setup with that meshcentral?
One thing to try is enter credentials, wait 1 min, then go into the console tab and type `amtconfig` and see what the output is

**Comment by Tomtreas** [comment]
si458, thanks for your help.  I get this in the console:

> amtconfig
Enabled live view of Intel AMT configuration events, "amtevents off" to disable.
18:01:48, LMS tunnel start.
18:01:49, Checking Intel AMT state...
18:02:02, Intel AMT connected.

So it appears to connect.  The Trying credentials is gone and it still shows the version # but when I go to AMT@INtel it says disconnected.  I assumed that somehow I need to disconnect the tunnel started with amtconfig now but can't find the correct command.

**Comment by si458** [comment]
@Tomtreas you can try by going into the 'My Server Console' in the 'My Server' tab, and type the command `dropallcira`
this will drop ALL intel amt connections, and basically tell the remote machines, reconnect please,
see if it comes back online after say 5 mins, if not try physically restarting the meshcentral machine

**Comment by Tomtreas** [comment]
I'll check out your edit #5679 but wanted to post back.  dropallcira dropped it said 0 connections.  Restarted the MeshCentral service, then the machine then the target AMT machine.  no joy anywhere yet.  Appreciate your help by the way.  Will come back once I try 5679
