### ISSUE TITLE
Thermal sensors naming

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2304]
The new thermal sensors feature is nice!
Is there a way to always open de live data graph directly instead of clicking the icon?

The issue at hand, I'm missing info for the sensors, a hover should display atleast some info.
I found some info to be available on Windows, although not easily readable I can make out CPU, Graphics, battery
It would really help.

Also the values don't update in Windows, running the wmic command with high and low load will result in the same numbers. Could be some cache

![image](https://user-images.githubusercontent.com/55733884/108188240-a1ec5400-710f-11eb-96d8-78b451abaafc.png)

> C:\windows\system32>wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get
Active  ActiveTripPoint                 ActiveTripPointCount  CriticalTripPoint  CurrentTemperature  InstanceName             PassiveTripPoint  Reserved  SamplingPeriod  ThermalConstant1  ThermalConstant2  ThermalStamp
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               3262                ACPI\ThermalZone\CPUZ_0  0                 0         0               0                 0                 252
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               2732                ACPI\ThermalZone\GFXZ_0  3752              0         300             1                 2                 251
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               3092                ACPI\ThermalZone\EXTZ_0  0                 0         0               0                 0                 216
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               3102                ACPI\ThermalZone\LOCZ_0  0                 0         0               0                 0                 234
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               2982                ACPI\ThermalZone\BATZ_0  4012              0         300             50                0                 251
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     0                  3072                ACPI\ThermalZone\CHGZ_0  0                 0         0               0                 0                 96
TRUE    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}  0                     4012               2732                ACPI\ThermalZone\PCHZ_0  0                 0         0               0                 0                 97

**Comment by si458** [comment]
would hovering over the temperature and showing the InstanceName be ok?
this will at least help identify them a little bit

can you also run the following cmd with admin and let me have a few different outputs from different machines?
`wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature,InstanceName`
