### ISSUE TITLE
Android agent receives notifications from domain not registered on ...

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2306]
Hi @Ylianst , sorry for bothering you again, but I think it is a big issue with MC2 when messaging an Android Agent.

Feel free to test it on the test environment provided to you in our mail chain.

Steps to reproduce:
 - Install and open mesh agent on Adnroid.
 - Setup server on Android Agent to use some domain using the QR code. ( example - domain1.com )
 - Clear the server on the Android Mesh Agent
 - Setup a different server on the same android device using QR code from different domain ( domain2.com )
 - Login to first MC2 domain (domain1.com) click on the offline Android agent
 - Click on Message, type something in and send it.
 Notification will be received successfully on the Android device, even if it is connected to a different server.

I tested it on completely different MC2 servers, on different domains running on one MC2 server - in both cases result is the same.
Issue is the same when using more than one domain on MC2 server config file (as in my case - 1 main and 2 extra )

**Comment by Ylianst** [comment]
Ha yes, I expected this problem. The way push notifications works, once the device sends it's notification token to the server, there is no easy way to know that it's not a valid token anymore. I have to work on something to fix this.

**Comment by Ylianst** [comment]
Started doing some work on this. Made changes to both future Android Agent and MeshCentral server.

**Comment by Ylianst** [comment]
Published MeshCentral v0.7.73 and Android Agent v1.0.5 with fixes for this. You may see the fix only once you re-register your Android device. The server will now assign the push notification token to only one device in the server, but it will start once you remove and re-connect the device. Also, the server ID is now sent in each notification and so, if the received notification does not have the right server ID, the push message is ignored in some cases. That should fix it.
