### ISSUE TITLE
Installer not working on Server 2012

### ISSUE THREAD

**Issue by sdm216** [Ylianst/MeshCentral#2307]
It looks like the agent installer is using a PowerShell command that doesn't work in Powershell 3, which is what Server 2012 uses, when adding the firewall rules. The following error comes up when installing. It just freezes here and never continues or finishes installation. It works on Server 2012 R2, but not regular Server 2012.

...Checking for previous installation of "MeshAgent" [NONE]...Installing service [DONE]   -> Writing firewall rules for MeshAgent Service...New-NetFirewallRule : A parameter cannot be found that matches parameter name 'DynamicTarget'.At line:1 char:168+ ... MeshAgent Management Traffic (TCP-1)" -DynamicTarget Any -Ed ...+                                                    ~~~~~~~~~~~~~~    + CategoryInfo          : InvalidArgument: (:) [New-NetFirewallRule], ParameterBindingException    + FullyQualifiedErrorId : NamedParameterNotFound,New-NetFirewallRule

**Comment by arduin0guru** [comment]
I am having same problem .1st time i run gives  me
![MeshError](https://user-images.githubusercontent.com/18668814/110824682-22523080-8248-11eb-8419-63a062587a0f.png)

2nd time gives me
![MeshError2](https://user-images.githubusercontent.com/18668814/110824687-22eac700-8248-11eb-9669-37f375c94f3e.png)

I managed to run agent by turning mesh service on manually.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
