### ISSUE TITLE
Mesh Central 2 on Moblie Devices?

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#2308]
When I try to sign in on my tablet or my iphone, the page gets stuck connecting? Is there something blocking it? Works fine on the computer side but all my mobile devices get stuck? Thanks!

**Comment by krayon007** [comment]
What OS is your tablet, and what ios version is your phone? It works fine on all my android devices. I'll check what ios version my iPad is

**Comment by 82280zx** [comment]
I have a iphone and ipad, both are 14.4.

**Comment by krayon007** [comment]
I just tried in my iPad running 14.4 on both chrome and safari, and it worked fine. I vaguely remember @Ylianst saying ios requires a real cert as it won't prompt you to ignore. Not sure if that's your issue

**Comment by 82280zx** [comment]
Mines running behind a reverse proxy using nginx, so I'll have to look into that and check some settings, I know it used to work fine with apache but stopped when I switched over to nginx, should still have a valid cert.

**Comment by 82280zx** [comment]
I figured it out it was a config problem with my NGINX, its working good now! Found an older post that @Ylianst was helping another person here https://www.reddit.com/r/MeshCentral/comments/k12qut/meshcentral_mobile_site_not_loading/
