### ISSUE TITLE
[REQ] - Right click auto-connect to action

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#231]
When in the view of "My Devices" and you right click on the device, and click on one of the options (information, desktop, terminal, files, console).

Can we have it auto connect, if accessed through the right click menu of a device?

Just trying to save everyone valuable seconds!

![RightClick](https://user-images.githubusercontent.com/37466255/57565186-59f9b280-73fc-11e9-8bf1-9c164e533820.JPG)

**Comment by Ylianst** [comment]
Agreed, will do this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.4-d and added the auto-connect on context menu selection. Try it. If it works, please close this issue. Thanks.

**Comment by theredkoala21** [comment]
Yes all working, excellent job. Ticket closed.
