### ISSUE TITLE
Name Shown on Connection Toolbar

### ISSUE THREAD

**Issue by jrodriguez142514-dev** [Ylianst/MeshCentral#2310]
The name shown on the connection toolbar will not display the "Real Name" if Prompt for User Consent is selected.  The only way "Real Name" will display is if "Notify User" or "Show Connection Toolbar" are selected.  If Prompt for User Consent is selected, the "Real Name" will not show, but the username (user identifier) of the current user will.  

Fix to allow "Real Name" to be displayed with Prompt for User Consent option is selected.

**Comment by Ylianst** [comment]
Oh. Your right. Thanks for reporting that. I never noticed that before.

**Comment by Ylianst** [comment]
Ok, just checked in the fix for this. Will be in v0.7.73 when it's next released. When published, let me know if that works.

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.7.73 has been released.

**Comment by jrodriguez142514-dev** [comment]
Just updated to v0.7.73 and can confirm the fix is now working. Thank you.
