### ISSUE TITLE
Nginx Reverse Proxy + CloudFlare

### ISSUE THREAD

**Issue by eldadh** [Ylianst/MeshCentral#2314]
My setup is:
Mesh server on VPS ( Oracle Cloud )
NgineX Reverse Proxy on another VPS ( Oracle Cloud )
And CloudFlare Proxy

I read previous issues regarding the matter and wasn't able to sort it out

I am receiving a The fallowing Logging Event Which seem to supposed to work since the agents does report the correct SHA:

```
Loaded web certificate from "https://remotely.XXXXXXX.com:443", host: "remotely.XXXXXXX.com"
SHA384 cert hash: 5db18c385542eab661f678a66fddf1251dd01c4d347a1a38252a335b1785e098bb424d79aa9f745f253bd8ac46296a64

MeshCentral v0.7.72, WAN mode, Production mode.
Agent bad web cert hash (Agent:5db18c3855 != Server:51f549f2cc or 6368d24cc2), holding connection (XXX.XXX.XXX.XXX:34110).
Agent reported web cert hash:5db18c385542eab661f678a66fddf1251dd01c4d347a1a38252a335b1785e098bb424d79aa9f745f253bd8ac46296a64.
```

relevent lines from config:
```
"cert": "remotely.XXXXXXX.com",
"certUrl": "https://remotely.XXXXXX.com:443",
"TlsOffload": "172.16.1.9",
"trustedproxy": "CloudFlare",
```

Thnx In Advance
I am using version 0.7.72

**Comment by Ylianst** [comment]
Hi. Interesting situation. First, remove the `"trustedproxy": "CloudFlare"` as all the connections are coming from NGINX on 172.16.1.9 so that is the only IP address MeshCentral needs to know about. Looks like the hash is being loaded correctly... looking to it now.

**Comment by Ylianst** [comment]
Can you go in the "MyServer" / "Console" tab and run "certhashes" and let me know what you see? - Thanks.

![image](https://user-images.githubusercontent.com/1319013/108778134-caae8800-7519-11eb-904d-efb92ae66f9d.png)

**Comment by eldadh** [comment]
It solve the issue, Thnx
