### ISSUE TITLE
How to acquire ServerID for .MSH file

### ISSUE THREAD

**Issue by JohnyHHH** [Ylianst/MeshCentral#2315]
Hi,

I have a process required to create .MSH file from server for preinstalled agent.
May I know how to acquired ServerID from the MeshCentral server?

**Comment by Ylianst** [comment]
A trick on this, add `?debug=1` to the URL and you can download the raw .msh file from the server in the "Add Agent" dialog.

![image](https://user-images.githubusercontent.com/1319013/108820717-746d3380-7571-11eb-8b06-4e46b2e8356a.png)

Let me know if that works.

**Comment by JohnyHHH** [comment]
Hi @Ylianst ,
Ya, this method works.
However my process required to obtain it programmatically, is there away can get thru meshctrl or other command?
