### ISSUE TITLE
RECORD USER DESKTOP SESSION

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2316]
Hi,

Is there any provision for automatically record all remote sessions in server.

Regards
VINISH VIJAYAN

**Comment by Ylianst** [comment]
Please read how to write a correct [GitHub issue here](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f). Once done, please open a new issue correctly.

**Comment by VINISHVV** [comment]
@Ylianst 

Sorry to bother you.

i have found the solution here - https://github.com/Ylianst/MeshCentral/issues/1855
