### ISSUE TITLE
user consent override

### ISSUE THREAD

**Issue by cr-sh** [Ylianst/MeshCentral#2317]
Hi, I see there are multiple places where to specify "user consent" settings and I suppose its purpose is to achieve an override logic flexibility.  

Unfortunately the hierarchy behind this alleged logic of overrides is not clear to me, even after double checking the user guide. 

I'm going to explain it as I have understood it: 

- "User Consent" on the "Device Group properties" is the basic level. So every agent added to this group inherit these settings.

- "User Consent" on the each specific "Agent properties" is the second level which overrides its "group" settings. So if an agent has a custom "user consent" setting this one will be applied.

- "User Consent" on the "User properties" is the third level. So if a user has a different "user consent" setting against the group properties (or even against a specific agent property) it will overwrite the two levels before.

The problem is that "reality" doesn't seem to be adherent to this my interpretation of the "user consent settings" -- so here I am :)

**Comment by Ylianst** [comment]
In addition to the 3 levels you mentioned, there is also a domain-wide setting in the config.json:

```
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": true,
        "terminalprompt": true,
        "fileprompt": true,
        "desktopprivacybar": true
      }
```

These flags are simply added together. So, if you have "desktopnotify" setup domain wide and you are part of a device group that requires "desktopprompt", then both will be applied. There is no "override". Each time you start a desktop session, the flags for the domain+device group/user group+device+user are summed together. Hope that helps.

Ylian

**Comment by cr-sh** [comment]
Thanks for the clear explanation Ylianst, it's more basic than I thought. I will have to contrive a different strategy to handle exceptions (ie: remove user consent for an unattended agent in a group when desktopprompt is enforced, or remove desktopprompt for certain special users and so on). 

Maybe the idea of create also negative form of permissions as issue #1783 or bypassing prompt if user is not logged as issue #2100 could step in to help.

**Comment by Ylianst** [comment]
I do agree that it's basic. In security, you don't want to make things too complex. This said, I an open to suggestions, as long as it's clear what the end result is.
