### ISSUE TITLE
Feature Request - Remote Backups Through MeshCentral

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2318]
MeshCentral already has a remote file access system in place. What I would like to see is this system also be usable to define a set of files and/or folders to be automatically downloaded at a configurable interval directly into the MeshCentral server itself. It would be nice to specify only a general directory for the "Backups" location and have the "device name" used in that directory to separate the backup files for each device that's being backed up. Then make these backup files available in the MeshCentral Web UI under the devices set of tabs called "Backups". This way regular files can be backed up to MeshCentral on a regular interval.

It would also be really cool if this system tied into the WebDAV system for use with platforms like NextCloud. If this could be done then MeshCentral could be a backup system for integration with NextCloud installs that are already in place making it possible to backup and store files with NextCloud installations and the like (WebDAV servers). I know this is a big request but just imagine if MeshCentral could do this job, it wouldn't be like a bare-bones recovery solution but would definitely be an essential files solution.

Note: NextCloud offers a file syncing software but requires that software to be installed to work. What if MeshCentral could provide this same service with a single agent installation (meshagent)  and have it automated by the MeshCentral Server in just one direction...client to server.

**Comment by yomono** [comment]
It is a cool idea, but at the same time I think it goes a bit out of the main road, and at the end of the day we could have a too simple and incomplete backup solution, when there is A LOT of software designed for that purpose..
You know, the Unix philosophy: do one thing and do it well

**Comment by LPJon** [comment]
> 
> 
> It is a cool idea, but at the same time I think it goes a bit out of the main road, and at the end of the day we could have a too simple and incomplete backup solution, when there is A LOT of software designed for that purpose..
> You know, the Unix philosophy: do one thing and do it well

I realize that but it never hurts to ask. That's why I put in the second request #2319 . I would be happy with either of these,  and I understand that a tool which CAN integrate other tools is very useful. In this particular instance I wasn't looking for something comprehensive but exactly the opposite and very very basic. The complex and comprehensive backups I would want done by BackupPC. This was about a simple solution for users who want to backup a few files from their PC on a regular basis automatically without having to know how to do a bunch of configuration. It would be more of a "It Just Works" solution. Where as BackupPC is more of a comprehensive backup, storage, and archiving system with direct restorative capabilities.

**Comment by Ylianst** [comment]
Right now, you can use meshctrl.js to script file uploads/downloads to and from remote computers. I do agree that a correct backup solution would do a "delta" backup and only store changes to be efficient and also involve compression and encryption. Probably not something I am going to launch into. This said, if there are additional configuration options I can add to integrate other solutions, that is certainly could be the best way to go.

**Comment by LPJon** [comment]
> 
> 
> Right now, you can use meshctrl.js to script file uploads/downloads to and from remote computers. I do agree that a correct backup solution would do a "delta" backup and only store changes to be efficient and also involve compression and encryption. Probably not something I am going to launch into. This said, if there are additional configuration options I can add to integrate other solutions, that is certainly could be the best way to go.

I didn't even know that that could be done through scripting....hmmmm......that gives me other ideas but answers this feature request. I might create a new request where I can get a button that would execute a custom backup script already installed on the MeshCentral server or something similar. This poses another question though. Can a button pass arguments to a script execution? If so, that is awesome and I can construct a script that is configurable through the Web UI. I'll give it some more thought. For now #2319 will work just fine if we can get it going.
