### ISSUE TITLE
Firefox nightly 88 - Icon sprite sizes are not correct

### ISSUE THREAD

**Issue by loranger** [Ylianst/MeshCentral#2321]
Hello,

I'm using the latest MeshCentral version and have a tiny issue with Firefox nightly (88) and Macos 11.2.1 : The sprite icons looks oversized lately. That definitely not a big bug, but as a MeshCentral fan, I wanted you to notice this.

Here are some screenshots of the issue (which does not happens using a webkit based browser such as chrome, safari or brave)

![Capture d’écran 2021-02-24 à 10 20 09](https://user-images.githubusercontent.com/6014/108982147-c2775980-768d-11eb-82f7-03a2fb30dc6d.png)

![Capture d’écran 2021-02-24 à 10 19 38](https://user-images.githubusercontent.com/6014/108982163-c7d4a400-768d-11eb-83bb-20e22e3385c6.png)

By the way, I'd like to thank you so much for this awesome webapp !

**Comment by Ylianst** [comment]
I am not super surprised by this. Firefox did not support high DPI images when they are specified in the CSS file and I did read that they are planning to add support for this. On my Apple M1 device, Safari would use the high DPI graphics and FireFox would not. I am guessing they are experimenting with resolving this but it's not quite right yet. Since it's nightly, I will not take any action right now, but will continue monitoring this.

**Comment by Ylianst** [comment]
I just tried FireFox nightly on Windows but without high DPI and it's ok. I am pretty sure this will get fixed on FireFox side.

**Comment by loranger** [comment]
Actually it seems Firefox does not supoport [image-set](https://caniuse.com/css-image-set) at all, and [for about 6 years](https://bugzilla.mozilla.org/show_bug.cgi?id=1107646) now !

It's not clear for me weither if Firefox does not support image-set because [csswg has moved spec draft from CSS3 to CSS4](https://github.com/w3c/csswg-drafts/issues/1148) or if they moved it because it was not implemented correctly in all browsers. Anyway, I'm afraid it won't be fixed anytime soon.

Maybe a simple workaround would be to get the `-webkit` prefix back as it's still a draft, after all. 
It would not break the compliant implementations and make Firefox falling back on the default background style.
What's your opinion ?
If you do agree, do you need me to open a PR on this (tiny and not really important) issue ?

**Comment by Ylianst** [comment]
I am speculating that they started working on image-set in CSS since the screen shots you have exactly show problems in that exact case. I would recommend not doing anything to MeshCentral to fix a "nightly" browser, that seems excessive. I would hold off and wait for FireFox updates.

**Comment by loranger** [comment]
No problem, let's wait for the resolving firefox upgrade.
I'll keep you up-to-date here if I can see any change
