### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2322]
When connecting to a computer with multiple display's i noticed an untranslated part.  after looking in the translation file, it is there, but no xloc lokation
![image](https://user-images.githubusercontent.com/58996467/109017602-9ffa3600-76b7-11eb-8a4c-5b8f5feb43ee.png)

![image](https://user-images.githubusercontent.com/58996467/109016940-f87d0380-76b6-11eb-9c44-6b6a0063b616.png)

**Comment by Ylianst** [comment]
Thanks for reporting this. Will be fixed in next version, MeshCentral v0.7.75.

**Comment by Ylianst** [comment]
MeshCentral v0.7.75 is out with fix for this.

**Comment by petervanv** [comment]
will report back if my client is reconnecting, got only one withe dual screens

**Comment by Ylianst** [comment]
Ok. There will need to be a translation of "Display {0}" to get the full translation. Here is what is looks like now:

![image](https://user-images.githubusercontent.com/1319013/109236590-c639d780-7784-11eb-9c5c-ea94e71c6a59.png)

**Comment by petervanv** [comment]
looking at your screenshot, and completing my translation, its solved
