### ISSUE TITLE
deploy on a sublocation of a domain

### ISSUE THREAD

**Issue by cr-sh** [Ylianst/MeshCentral#2323]
Hi, I need to deploy meshcentral on a specific location of a domain (https://domain.tld/meshcentral) instead of the root path.

On the nginx in front of meshcentral I can easy achieve this with the following configuration:

location /meshcentral {
 proxy_pass http://10.10.10.10:443/; #meshcentral ip 
 proxy_http_version 1.1;

but unfortunately meshcentral still thinks to be on the root of the domain.tld, is there a parameter to inform it of the actual path?

thanks

**Comment by LPJon** [comment]
You can accomplish this in two ways. First, MechCentral has a feature called "Multi Tenancy" which allows for deploying MeshCentral in a directory location. You can find more about that [here](https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json) then search for `"_customer1": {` and follow the example. The setting that places MeshCentral in a directory location is `"url": "test",`. Whatever you put here will be the directory location in the URL. The second way of doing this is to use rewrite with your web server. I'm not sure how you can do this with NginX but here is an example for Apache, maybe you can convert it for NginX.

```
#=====================================================================================  
# Rewrite Rules for / Location
#=====================================================================================
  RewriteEngine On
  # Rule for / Directory Location. Forwards webroot to this location.
  RewriteCond %{REQUEST_URI} !^/(meshcentral)(.*)$
  RewriteRule ^(/)$     https://%{HTTP_HOST}/meshcentral\$1 [P]

#=====================================================================================
<Location /meshcentral/>
     RewriteEngine On
     ProxyAddHeaders On
     ProxyPass         https://<IP>:<PORT>/
     ProxyPassReverse  https://<IP>:<PORT>/
</Location>
#=====================================================================================
```
This is just and example and may not work specifically with your setup so you may need to do a little research how how to use rewrite rules. The multi tenancy option is by far much easier.

**Comment by Ylianst** [comment]
@LPJon is correct. Just to add, a config file like this would work:

```
{
  "settings": {
    "cert": "domain.tld"
  },
  "domains": {
    "": {
      "title": "MasterDomain"
    },
    "meshcentral": {
      "title": "SecondDomain"
    },
    "extradomain": {
      "title": "ThirdDomain",
      "dns": "extradomain.domain.tld"
    }
  }
}
```

Here, accessing "https://domain.tld" will get you to the main domain, accessing "https://domain.tld/meshcentral" gets you to the second domain. Just for kicks, accessing "https://extradomain.domain.tld" gives you access to the third domain. This is without NGINX. You get do more tricks with NGINX.

Hope that helps,
Ylian

**Comment by cr-sh** [comment]
Hi all and thanks for the replies, using "Multi Tenancy" is my current workaround to this issue but some requests, like chat for instance, are still trying to use the base domain https://my.domain.tld/messenger instead of appending the "meshcentral" multi tenancy slug https://my.domain.tld/meshcentral/messenger. Even with the @LPJon 's url rewrite example you're supposing my base domain is free so it's possible to rewrite all requests to the meshcentral sublocation. But in my base domain there's another application so it isn't a viable option.

**Comment by LPJon** [comment]
@cr-sh You could try using rewrite rules to redirect the requests from your webroot to your directory location. The thing with doing this is that it will take testing and playing around with it to get everything working. To do that you will need to know how to manipulate URL's. An example is below and it may fit your use case a little better.

```
RewriteEngine On
# Rule for /messenger URL in webroot. Forwards /messenger in webroot to /meshcentral/messenger.
RewriteCond %{REQUEST_URI} ^/(messenger)(.*)$
RewriteRule ^(/messenger.*)$     https://%{HTTP_HOST}/meshcentral\$1 [P]
```
In this example we take anything that starts with `/messenger` and rewrite that to `/meshcentral/messenger` . The `RewriteCond` is under what circumstance to we perform the rewrite and the `RewriteRule` is what do we rewrite the URL in the browser to be. These rewrite rules have to match your `Directory` directives for them to work and you may need several of each. Like I said it takes time and testing. NOTE: that anything in `( )` uses regular expressions to describe the specific URL you want to change and you can find more on that [HERE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

Still, the best way to handle this would then be to use the subdomain option of the "Multi Tenancy" feature and not a directory location. You could always redirect a directory location to a subdomain using a 301.
examples:
Subdomain: meet.google.com ----- "meet" is a subdomain of the Top Level Domain (TLD) "google.com".
