### ISSUE TITLE
Couple of minor typos (one from earlier this morning)

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#2324]
Hi, Ylian @Ylianst ,

Just saw this in the commit this morning:
![image](https://user-images.githubusercontent.com/7637082/109228929-743e8500-7777-11eb-89fa-cfb01923ce03.png)
Not sure if you had seen my comment, but, wanted to bring it up..

And on our server, I just noticed this:
![image](https://user-images.githubusercontent.com/7637082/109228979-891b1880-7777-11eb-8422-de05277eae57.png)

Just bringing them up if you wanted to make a quick fix before your next commit...

**Comment by Ylianst** [comment]
Thanks for reporting this! I just made the fixes in GitHub and it will be part of MeshCentral v0.7.77.

**Comment by mjpcomp** [comment]
Thanks @Ylianst  - looks like one more:

![image](https://user-images.githubusercontent.com/7637082/109231938-3b54df00-777c-11eb-8aa7-34dc88373db5.png)

Just saw that on the commit for the typos 😛

**Comment by Ylianst** [comment]
Oh good. Just fixed it.

**Comment by Ylianst** [comment]
MeshCentral v0.7.77 now published with these fixes. Let me know if that works.

**Comment by mjpcomp** [comment]
Updated to v0.7.78 and everything is looking good 👍
