### ISSUE TITLE
Agent not showing in Dashboard

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2325]
@Ylianst 

From last few day i am facing agent connecting issues. This is applicable for new agent installations only.
If i restart my server then it will show all the newly installed agents.
I assume this is related to my configuration. 
can you help me in this case.

Server Version - 0.7.77

Config.js
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "help.mydomain.org",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "_AllowHighQualityDesktop": true,
    "_compression": true,
    "_wscompression": true,
    "_agentwscompression": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "webPush": { "email": "myid@domain.com" },
    "_webRTC": true,
    "authlog" : "c:\\mesh\\auth.log",
    "_noagentupdate": true,
 "AllowLoginToken": true,
    "dbExpire": {
      "events": 31536000,
      "powerevents": 31536000,
      "statsevents": 31536000
    },
 "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 1,
      "keepLastDaysBackup": 20,
      "backupPath": "D:\\Meshcentral BACKUPS"
    }  
      },
  "domains": {
    "": {
      "title": "Meshcentral",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true 
 },
 "sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "D:\\Meshcentral RECORDINGS",
        "index": true,
        "maxRecordings": 10000,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
},
  "passwordRequirements": {
        "force2factor": true,
         "reset": 10        
      }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  },
 "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "something@gmail.com",
    "user": "something@gmail.com",
    "pass": "mypassword",
    "tls": false
  },
    "domaindefaults": {
    "": {
      "title": "Meshcentral",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "mstsc": true  
 },
 "sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "D:\\Meshcentral RECORDINGS",
        "index": true,
        "maxRecordings": 10000,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
},
  "passwordRequirements": {
        "force2factor": true,
         "reset": 10        
      },
  "_consentMessages": {
        "title": "Meshcentral",
        "desktop": "{0} requesting remote desktop access. Grant access ?",
        "terminal": "{0} requesting remote terminal access. Grant access ?",
        "files": "{0} requesting remote files access. Grant access?"
      },
  "_agentCustomization": {
        "displayName": "Remote-Access™",
        "_description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Meshcentral",
        "serviceName": "Meshcentral",
        "_fileName": "Meshagent"
}
  }
}
```

**Comment by asasin114** [comment]
Please provide more info on your server environment. What version of Windows is MeshCentral running on, how is your MeshCentral server setup to connect to the internet, do you have any port forwarding rules and/or any special rules set on your router, is the server hosted in a cloud instance through Amazon, Google, Azure, etc.?

The configuration itself looks fine so that leads to an environment issue. You've also got to give the agent a couple moments to connect sometimes. Clearly it is ultimately working if the agents are showing up after a server restart but it shouldn't take that to get it going.

**Comment by VINISHVV** [comment]
@asasin114 

Thanks for your replay.

Please note that the Meshcentral application  is running in in Windows server 2012  with 8CPU and 32GB RAM.

We have assigned direct Public IP to server without NAT.  Also i am using my own Domain name and SSL certificate  ( purchased from Go daddy.).

**Comment by Ylianst** [comment]
I ran the config.json thru [JSON lint here](https://duckduckgo.com/?t=ffnt&q=json+lint&ia=answer). The config.json is not good at all. First, there is 3 domains, the default master domain and a domain called "sessionRecording" and "passwordRequirements". This is almost certainly not correct. Here is the lint version:

```
{
  "settings": {
    "cert": "help.mydomain.org",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "webPush": {
      "email": "myid@domain.com"
    },
    "authlog": "c:\\mesh\\auth.log",
    "AllowLoginToken": true,
    "dbExpire": {
      "events": 31536000,
      "powerevents": 31536000,
      "statsevents": 31536000
    },
    "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe",
      "backupIntervalHours": 1,
      "keepLastDaysBackup": 20,
      "backupPath": "D:\\Meshcentral BACKUPS"
    }
  },
  "domains": {
    "": {
      "title": "Meshcentral",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    },
    "sessionRecording": {
      "onlySelectedDeviceGroups": true,
      "filepath": "D:\\Meshcentral RECORDINGS",
      "index": true,
      "maxRecordings": 10000,
      "_maxRecordingSizeMegabytes": 3,
      "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
      "protocols": [
        1,
        2,
        101
      ]
    },
    "passwordRequirements": {
      "force2factor": true,
      "reset": 10
    }
  },
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "something@gmail.com",
    "user": "something@gmail.com",
    "pass": "mypassword",
    "tls": false
  },
  "domaindefaults": {
    "": {
      "title": "Meshcentral",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "mstsc": true
    },
    "sessionRecording": {
      "onlySelectedDeviceGroups": true,
      "filepath": "D:\\Meshcentral RECORDINGS",
      "index": true,
      "maxRecordings": 10000,
      "_maxRecordingSizeMegabytes": 3,
      "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
      "protocols": [
        1,
        2,
        101
      ]
    },
    "passwordRequirements": {
      "force2factor": true,
      "reset": 10
    }
  }
}
```

I am not sure how the config.json even works at all. Here is my corrected version:

```
{
  "settings": {
    "cert": "help.mydomain.org",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "webPush": { "email": "myid@domain.com" },
    "authlog": "c:\\mesh\\auth.log",
    "AllowLoginToken": true,
    "dbExpire": {
      "events": 31536000,
      "powerevents": 31536000,
      "statsevents": 31536000
    },
    "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe",
      "backupIntervalHours": 1,
      "keepLastDaysBackup": 20,
      "backupPath": "D:\\Meshcentral BACKUPS"
    }
  },
  "domains": {
    "": {
      "title": "Meshcentral",
      "minify": true,
      "newAccounts": false,
      "mstsc": true,
      "sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "D:\\Meshcentral RECORDINGS",
        "index": true,
        "maxRecordings": 10000,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [1,2,101] },
      "passwordRequirements": {
        "force2factor": true,
        "reset": 10
      }
    }
  },
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "something@gmail.com",
    "user": "something@gmail.com",
    "pass": "mypassword",
    "tls": false
  }
}
```

May not address the original problem, but improves the config.json.

**Comment by Ylianst** [comment]
For agent connection issues, try stopped the agent service and running the agent manually using:

```
meshagent.exe run
```

You will see what the agent is going to try to connect. That should help debug the issue.

**Comment by VINISHVV** [comment]
@Ylianst - I have updated the config file based on your suggestion.

But still new agents are not connecting to dashboard.

When i run the command meshagent.exe run i am getting below error.

____________________________________________________________________
C:\Program Files\Mesh Agent>meshagent.exe run
Unable to open database (1/10)...
Unable to open database (2/10)...
Unable to open database (3/10)...
Unable to open database (4/10)...
Unable to open database (5/10)...
Unable to open database (6/10)...
Unable to open database (7/10)...
____________________________________________________________________

My configuration file 
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "help.muthoot.org",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "_AllowHighQualityDesktop": true,
    "_compression": true,
    "_ignoreAgentHashCheck": true,
    "_wscompression": true,
    "_agentwscompression": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "webPush": { "email": "itvinish@xxxxx.com" },
    "webRTC": true,
    "authlog" : "c:\\mesh\\auth.log",
    "_ListEvents" : "c:\\mesh\\event.csv",
    "_noagentupdate": true,
    "AllowLoginToken": true,
    "dbExpire": {
    "events": 31536000,
    "powerevents": 604800,
    "statsevents": 604800
    },
 "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 1,
      "keepLastDaysBackup": 20,
      "backupPath": "D:\\M-ACCESS BACKUPS"
    }  
      },
   "domains": {
    "": {
      "title": "Meshcentral",
      "title2": "Powerd by Team-IT",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
       "mstsc": true,
      "_userallowedip" : "202.191.157.10,49.36.131.141",   
       "sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "D:\\M-ACCESS RECORDINGS",
        "index": true,
        "maxRecordings": 10000,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
},
  "passwordRequirements": {
        "force2factor": true,
         "reset": 10        
      },
  "_consentMessages": {
        "title": "M-Access",
        "desktop": "{0} requesting remote desktop access. Grant access ?",
        "terminal": "{0} requesting remote terminal access. Grant access ?",
        "files": "{0} requesting remote files access. Grant access?"
      },
  "_agentCustomization": {
        "displayName": "Muthoot® Remote-Access™",
        "_description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Muthoot Finance",
        "serviceName": "M_Access",
        "_fileName": "Meshagent"
}
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  },
 "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "helpdeskdlh@gmail.com",
    "user": "helpdeskdlh@gmail.com",
    "pass": "Paddddeeesss3",
    "tls": false
  },
  "sms": {
    "provider": "twilio",
    "sid": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "auth": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "from": "+12564748475"
  }
 }

**Comment by krayon007** [comment]
Before you run the agent on console mode, make sure to stop the service first.

**Comment by Ylianst** [comment]
`Unable to open database (1/10)...` is because your running the agents twice.

**Comment by asasin114** [comment]
> I ran the config.json thru [JSON lint here](https://duckduckgo.com/?t=ffnt&q=json+lint&ia=answer). The config.json is not good at all. First, there is 3 domains, the default master domain and a domain called "sessionRecording" and "passwordRequirements". This is almost certainly not correct. Here is the lint version:
> 
> ```
> {
>   "settings": {
>     "cert": "help.mydomain.org",
>     "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
>     "mongodbcol": "meshcentral",
>     "webPush": {
>       "email": "myid@domain.com"
>     },
>     "authlog": "c:\\mesh\\auth.log",
>     "AllowLoginToken": true,
>     "dbExpire": {
>       "events": 31536000,
>       "powerevents": 31536000,
>       "statsevents": 31536000
>     },
>     "AutoBackup": {
>       "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe",
>       "backupIntervalHours": 1,
>       "keepLastDaysBackup": 20,
>       "backupPath": "D:\\Meshcentral BACKUPS"
>     }
>   },
>   "domains": {
>     "": {
>       "title": "Meshcentral",
>       "_minify": true,
>       "_newAccounts": true,
>       "_userNameIsEmail": true
>     },
>     "sessionRecording": {
>       "onlySelectedDeviceGroups": true,
>       "filepath": "D:\\Meshcentral RECORDINGS",
>       "index": true,
>       "maxRecordings": 10000,
>       "_maxRecordingSizeMegabytes": 3,
>       "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
>       "protocols": [
>         1,
>         2,
>         101
>       ]
>     },
>     "passwordRequirements": {
>       "force2factor": true,
>       "reset": 10
>     }
>   },
>   "smtp": {
>     "host": "smtp.gmail.com",
>     "port": 587,
>     "from": "something@gmail.com",
>     "user": "something@gmail.com",
>     "pass": "mypassword",
>     "tls": false
>   },
>   "domaindefaults": {
>     "": {
>       "title": "Meshcentral",
>       "minify": true,
>       "newAccounts": false,
>       "_userNameIsEmail": true,
>       "mstsc": true
>     },
>     "sessionRecording": {
>       "onlySelectedDeviceGroups": true,
>       "filepath": "D:\\Meshcentral RECORDINGS",
>       "index": true,
>       "maxRecordings": 10000,
>       "_maxRecordingSizeMegabytes": 3,
>       "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
>       "protocols": [
>         1,
>         2,
>         101
>       ]
>     },
>     "passwordRequirements": {
>       "force2factor": true,
>       "reset": 10
>     }
>   }
> }
> ```
> 
> I am not sure how the config.json even works at all. Here is my corrected version:
> 
> ```
> {
>   "settings": {
>     "cert": "help.mydomain.org",
>     "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
>     "mongodbcol": "meshcentral",
>     "webPush": { "email": "myid@domain.com" },
>     "authlog": "c:\\mesh\\auth.log",
>     "AllowLoginToken": true,
>     "dbExpire": {
>       "events": 31536000,
>       "powerevents": 31536000,
>       "statsevents": 31536000
>     },
>     "AutoBackup": {
>       "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe",
>       "backupIntervalHours": 1,
>       "keepLastDaysBackup": 20,
>       "backupPath": "D:\\Meshcentral BACKUPS"
>     }
>   },
>   "domains": {
>     "": {
>       "title": "Meshcentral",
>       "minify": true,
>       "newAccounts": false,
>       "mstsc": true,
>       "sessionRecording": {
>         "onlySelectedDeviceGroups": true,
>         "filepath": "D:\\Meshcentral RECORDINGS",
>         "index": true,
>         "maxRecordings": 10000,
>         "_maxRecordingSizeMegabytes": 3,
>         "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
>         "protocols": [1,2,101]
>       },
>       "passwordRequirements": {
>         "force2factor": true,
>         "reset": 10
>       }
>     }
>   },
>   "smtp": {
>     "host": "smtp.gmail.com",
>     "port": 587,
>     "from": "something@gmail.com",
>     "user": "something@gmail.com",
>     "pass": "mypassword",
>     "tls": false
>   }
> }
> ```
> 
> May not address the original problem, but improves the config.json.

I'll be honest, I didn't run the config through a checker. My bad.

**Comment by Ylianst** [comment]
@asasin114 No worries. In this case, the config.json is probably not related to the original problem.

**Comment by Ylianst** [comment]
I am going to close this since it's a bit all over the place. If an agent does not connect, first check the meshagent.msh file, make sure it contains the correct URL to your server.

On Windows, stop the agent service and run the agent from the command list like this:

```
meshagent.exe -run
```

On Linux, stop the agent service and run:

```
meshagent
```

You will see details of how the agent is trying to connect. If there is another problem, open a new issue. Hope that helps.
