### ISSUE TITLE
How to run meshcentral in http mode with out redirecting to https 

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2327]
1. How to run meshcentral in http mode with out redirecting to https 
2. Will it cause any issues in the mesh agent?

**Comment by VINISHVV** [comment]
Ylianst  says that  - MeshCentral is a management web site and so, security is super important, so no, there is no HTTP support. There is a server on port 80 to redirect users to port 443 and perform other operations

Source #2153

**Comment by Ylianst** [comment]
@VINISHVV is correct. Because of security, there is no support for HTTP.
