### ISSUE TITLE
Add Custom / "Last Seen" column in "My Devices" view

### ISSUE THREAD

**Issue by L422Y** [Ylianst/MeshCentral#2329]
Add "Last Seen" column into xdevices table view, better yet, make the columns customizable!  #enhancement

**Comment by vitko-bg** [comment]
This is a duplicate :) sorry, cannot provide number of the issue, as on the go and on the phone :)

**Comment by si458** [comment]
this already exists, click the COG in the columns view and select 'Last Seen'
