### ISSUE TITLE
Meshcentral Process Manager 2 (PM2) startup file

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#2330]
Trying to workout how to add Meshcentral to PM2, but want to know what the startup file is.
the webhost support are asking the following

we need your confirmation on where is the start-up file of this application located. Please provide us with the full path to the start-up file.

Additionally, if there is any online documentation that describes the recommended deployment procedure, please apply a web-link to it, so we can review it.

**Comment by Ylianst** [comment]
What does "PM2" stand for? Thanks.

**Comment by haxmachine** [comment]
I think its a way of stopping and starting NodeJS applications in CPANEL
they want to know what file needs to be started so meshcentral runs

**Comment by haxmachine** [comment]
Maybe this will help 
https://www.npmjs.com/package/pm2
:)

**Comment by LPJon** [comment]
@haxmachine @Ylianst PM2 is a service manager for NodeJS applications. Works very well i might add and is extremely easy to use. You will find what you need in the ´../node_modules/meshcentral´ folder of the installation directory you specified during the install.

**Comment by LPJon** [comment]
I believe this command should do the trick. pm2 start <path to install directory>/node_modules/meshcentral/ . There is no need to specify a file name because pm2 will work that out on its own. Just point it to the right directory and it should work for you.

**Comment by haxmachine** [comment]
@LPJon Does this look right, and thank you for any help

![image](https://user-images.githubusercontent.com/50190618/109490141-f0203080-7adb-11eb-94cd-cc52166fb6fc.png)

**Comment by LPJon** [comment]
> 
> 
> @LPJon Does this look right, and thank you for any help
> 
> ![image](https://user-images.githubusercontent.com/50190618/109490141-f0203080-7adb-11eb-94cd-cc52166fb6fc.png)

@haxmachine Change "Application startup file" to `meshcentral.js` . The "Application root" may need a trailing `/`. Under "Application URL" you may need to specify a directory location unless you are putting it in the root of your domain.

Please Note: The commands I specified are commands you run from the command-line of the web server. I'm not familiar with CPANEL or this web GUI interface. I'm simply helping you fill in the blanks for what I see in your screen capture.

**Comment by haxmachine** [comment]
Thanks ill try and see how i go
