### ISSUE TITLE
Feature requests: "Reset view" hotkey & "Focus search input" hotkey

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#2331]
Hi MC team,

I'd be glad to see a hotkey shortcut within MC to reset the current view by jumping back to the My Devices tab. This would help to speed up working with MC in the daily works, as it is literally for every single task either the last action performed after it completed, or the first action to begin a new task.
I suggest using `Ctrl`+`Esc` for this function. The function should only be triggered, if the current keyboard focus is **not** an active desktop or terminal session, so that the key combination can still be used to control remote software.

Additionally I'd like to suggest that hitting `Ctrl`+`F` in the My Devices tab should be captured and trigger a focus of MC's own search bar instead of triggering the browsers' internal search function, so you can work with MC's search specialities such as tags by using common shortcuts.

Thanks for all your great work and best regards,
// Veit

**Comment by Ylianst** [comment]
I added `Shift-ESC` in the next version that will return to devices view, clear the search and disconnect any connected desktop, terminal or files. When v0.7.80 next comes out, let me know if that works.

For `CTRL-F`, you should not need to focus on the search input box, just start typing and text should go there now. Let me know if that does not work.

**Comment by veitw** [comment]
> I added `Shift-ESC` in the next version that will return to devices view, clear the search and disconnect any connected desktop, terminal or files. When v0.7.80 next comes out, let me know if that works.

Thank you very much, I will try this once .80 is released.

> For `CTRL-F`, you should not need to focus on the search input box, just start typing and text should go there now. Let me know if that does not work.

Oh, I was not aware of this feature, thanks for the hint! :)

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.7.80 is now published.

**Comment by veitw** [comment]
Thanks, looks good. :)

I already found some more contextual mistranslations. I will collect some and create another PR.

**Comment by Ylianst** [comment]
One more MeshCentral hidden feature :)

**Comment by veitw** [comment]
> One more MeshCentral hidden feature :)

Yeah. :D

Regarding search filter features and keyboard shortcuts, maybe a filter/shortcut cheat sheet pop-up would become handy, both as reference and to bring the hidden features to the surface.

It could pop up e.g. when a "?" strategically placed next to the view change diamond symbol is clicked.
