### ISSUE TITLE
Add Key Combination "ALT + CTRL + END" to the Dekstop screen.

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#2332]
Can "ALT + CTRL + END" be added as a key combination to send.  

It's the RDP equivilent of "ALT + CTRL + DEL" which is useful in nested Mesh, RDP sessions.

**Comment by Ylianst** [comment]
Right click on the keyboard shortcut drop down and hit "Customize". You should be able to add the combination you want. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/109625795-9841f380-7af4-11eb-8473-8ac625e8f52a.png)

**Comment by b8two** [comment]
I didn't know customize was there.  I found an old bug #359 which is similar but it was still open.

Thank you
