### ISSUE TITLE
MeshCentral notifies the user that a remote connection is taking place

### ISSUE THREAD

**Issue by Philippe34** [Ylianst/MeshCentral#2333]
Hello,
Some users are reluctant to have Meshcentral installed on their workstation, because they don't want someone (their boss, a spy) to be able to connect and see their work without them knowing it.
Could we design a solution for this situation :
Optionaly, when MC is used for user assistance, the Meshcentral agent warns the user that a remote connection attempt is made (pop-up) and the user can optionally refuse it. It would also be an access control against hacking attempts. 
For another use, like "I want to remotely access my own computer", this option is of course not enabled because there is nobody in front of the machine to refuse or accept the connection.

Thanks

**Comment by Ylianst** [comment]
In a device group, click on "User Consent" and activate what you need.

![image](https://user-images.githubusercontent.com/1319013/109626058-ea831480-7af4-11eb-946e-65ff58bc68a7.png)

You can also set these per user group or per user in the user interface. You can also configure this as a domain wide option in the config.json. In the domain section of the config.json, add this:

```
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": false,
        "terminalprompt": false,
        "fileprompt": false,
        "desktopprivacybar": false
      }
```

Then, no users or administrators can override it. Let me know if that helps.

**Comment by Philippe34** [comment]
Great @Ylianst ! That is exactly what I need and it works perfectly.
