### ISSUE TITLE
Add copy button to agent download sections that have text commands

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2336]
Hi @Ylianst,

Can the linux and any others that installation methods that have a scripted text box get added with a copy to clipboard function in the box like that of some of the how-tos that are at digital ocean...

![image](https://user-images.githubusercontent.com/48393851/109703998-f7caee00-7b4a-11eb-9d08-7fdfd5093576.png)

This would be awesome to add this feature for ease of useage...

**Comment by Ylianst** [comment]
I don't understand this request.

**Comment by SomeGuru** [comment]
@Ylianst,

Essentially when copy and paste in browsers is done, I am seeing that some of the browsers add "browser" artifacts to the code (interprets the code as some of its code (Opera) as smileys or other related operators and changes the copied commands) Yet if that copy button action is used, it pushes the clipboard buffer with a raw statement fed from the actual written commands.

This in turn helps in the paste action on a new system getting Linux agent added via CLI/Terminal. This allows that system to come online otherwise the server is easily able to reject (as it should) the call from a malformed request due to action of the browser injection.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Can you provide exact steps to reproduce the problem and screen shots of when you are copying and what you are getting? Thanks.
