### ISSUE TITLE
Can a desktop snapshot be put in the General tab that updates on a timed interval?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2337]
@Ylianst,

Can a snapshot view of the desktop be made available on the generals tab that would look like the attached photo? 

![image](https://user-images.githubusercontent.com/48393851/109714961-e76d4000-7b57-11eb-8dc8-d2bf3ff70aa4.png)

Base the timing to no run live, but an updated giant thumbnail updated every 5 seconds or 30 seconds or 1 minute timeframe?

Reason I ask this, is because sometimes users are logged on directly to systems and having the view available allows a user in the group or administrator to see if someone might have locked the system, be using the system, or left the system open without doing desktop mode.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
This looks a lot like #2289.

**Comment by SomeGuru** [comment]
Hi Ylian,

Not exactly what I am referencing here... More like the photo above that I modified... it would show a semi-static image of the desktop mode, but is not actually downloadable like the #2289 seems to reference a download. My request is more to show a last relevant screen at a time delimited interval to allow someone to know what the system is doing... like the example shown is before the Windows 10 swipe action, and usually is shown when the system is completely free to login too... So from the perspective of the group user/admin this would allow them to know if they needed to go into the system, or maybe go to the terminal to update/run something as system vs. user space. Also it would tell me as administrator if a user has locked the system that I need to kick the user off via terminal. Thus this would save minutes of time that would turn into hours of savings over time and eventually money saved.

How I understand #2289 is that the person can without going into the system take a screen capture of the machine as an image file.  #2337 is not to actually have a screen captured to file, just to the MeshCentral General tab. I hope this clears up the confusion. 

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
I looked through configs but not seeing this change or enhancement done however maybe I am missing the change?

Thanks,
SomeGuru
