### ISSUE TITLE
Bug: MeshCentral Router Branding For Mcrouter:// Links

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2338]
I've got the branding working great for the MeshCentral Router, but noticed that it doesn't work when opening mcrouter:// links from the website. It almost seems like Windows is not using the correct working directory for MeshCentralRouter.exe when launched this way.

I was looking at the registry entry `HKCR\mcrouter\shell\open\command` but I'm not sure if I can add an argument or registry key to set the working directory manually.

**Comment by MatinatorX** [comment]
Managed to fudge a quick workaround to prove it's a working directory problem. Changed the registry key at `HKCR\mcrouter\shell\open\command` with this:

`cmd.exe /C pushd  "[path to MeshCentralRouter.exe]" && start MeshCentralRouter.exe "%1"`

...and now it works great, aside from a brief flicker of the command prompt.

**Comment by Ylianst** [comment]
Ha! Your right. Working on a fix now.

**Comment by Ylianst** [comment]
I just updated MeshCentral Router to fix this. It will be in MeshCentral 0.7.80, but you can get the new [MeshCentral Router executable now here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

Let me know if that works.

**Comment by MatinatorX** [comment]
Works great, thanks for the quick fix!
