### ISSUE TITLE
Restrict user login after office hours. 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2339]
Dear Ylianst, 

Please implement user login restriction after office hours. All the user with admin privilege have 24 hours login access and others users needs to restrict. 

We need to define the timing in either config.js Or GUI.

**Comment by Ylianst** [comment]
This is getting very specific. What time zone? Holidays? How about a feature where MeshCentral calls an external script to allow user login? That way, you can configure the script any way you like?

**Comment by VINISHVV** [comment]
Dear Ylianst,

The time zone is GMT 5.30

Office hours Monday to Saturday 09:00 AM to 06:00 PM

**Comment by vitko-bg** [comment]
@VINISHVV Have you tried Group Policies on Windows?
I think it is entirely to the OS options...

**Comment by Ylianst** [comment]
Oh. No way I am adding a MeshCentral feature that has a specific timezone or times. This request needs to be more generic so that more people can use it. If you want a very specific feature, you can edit the code yourself.

**Comment by VINISHVV** [comment]
@Ylianst 
Tahnks... No issue I  will check the feasibility through LDAP.
