### ISSUE TITLE
Not able to Wake the system in mesh (inbuilt action)

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#234]
Hi 

I am able to put the system to Sleep or S4 but not able to wake the system back to S0 state using the mesh action "Wake"

not sure if i am missing any steps

regards
arun

**Comment by Ylianst** [comment]
Hi. The wake button makes other computers on the save group send a "wake-on-lan" packet. For it to work, another computer needs to be powered on in the same network and the computer much have support for "magic packet" enabled in the network driver.

In the future I will also add support for Intel AMT power on. I will need to make it more clear in the user interface.

Ylian

________________________________

**Comment by Arun0711** [comment]
Thanks Ylian

Regards
Arun
