### ISSUE TITLE
How to change the mesh agent connection timeout

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2340]
How to change the mesh agent connection timeout?

My Network is too slow and its giving error "Network timeout error occurred"

Can i increase the agent time out?

**Comment by Ylianst** [comment]
Can you indicate where you see the timeout error? Are you running the agent manually?

You can see current agent [.msh options here](https://github.com/Ylianst/MeshAgent/blob/master/readme.md). There is no way to change the connection timeout. However, before adding such option, I want to make sure this is the problem your having.

**Comment by aimdharma1990** [comment]
> Can you indicate where you see the timeout error? Are you running the agent manually?
> 
> You can see current agent [.msh options here](https://github.com/Ylianst/MeshAgent/blob/master/readme.md). There is no way to change the connection timeout. However, before adding such option, I want to make sure this is the problem your having.

Thanks for sharing details. I was running as service but logs are not printing. so for debug purpose i have ran the meshagent in command prompt with run argument. 

There its printing the timeout error. The browser was taking nearly 20-30 sec to respond as internet is bit slow..

**Comment by Ylianst** [comment]
Are you sure the timeout is not caused by something else? Like the agent trying to connect to the wrong URL? Or the need for an HTTP proxy to be used? What is the approximate timeout your are seeing on the agent now? - Thanks.

**Comment by aimdharma1990** [comment]
Hi.

Thanks for your reply. I have confirmed the URL is correct. I found there
is some latency issue in network w.r.t port which is resolved now the Mesh
Agent is properly communicating.
