### ISSUE TITLE
Question : BadWebCertHash for an agent. Why this ?

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2341]
Hi,

I've got an agent with a "BadWebCertHash" and I'm wondering why this and if it's a security danger ?

I try to figure out by reading the "Meshcentral2 Design and Architecture - section 8. Agent to server handshake"
As far as I understand, this problem is at the first step where the agent perform a TLS connection to the server to check its web certificate. If it fails this step, the agent should not be able to make a connection. Is it right ?

Looking at the logs, I've this line : 
Agent bad web cert hash (Agent:****** != Server:xxxxx or yyyyyyy), holding connection (204.X.Y.Z:49175)
The agent's IP address doesn't seem to be familiar to me but it could be a connection through a VPN, by the way I cannot find any information in the database and it makes me a little bit worried.

I'm wondering about the "holding connection" that I didn't suppose to find. Did I mix up the concept of the handshake maybe ?

Could you help me to understand this and to realize the security risk please ?

Thanks in advance.

MC2 v.0.7.76 on a Debian 10, no reverse proxy.

**Comment by Ylianst** [comment]
Hi. So, the agent does connect to the server, but then the agent reports what TLS certificate it saw and the server needs to confirm this is correct. This error may be caused by an incorrectly configures reverse proxy or TLS offloader - If this is the case, all your devices will have this problem.

Now, if your devices generally work but your seeing this for one device only, one possibility is that one device is behind a corporate proxy that is a bit evil and acting as a man-in-the-middle for TLS connections. That is, the agent connects to the corporate proxy which will present a dummy corporate TLS certificate and decrypt the connection to inspect what is going on. If this is the case, the agent will tell the server it's seeing the corporate TLS cert and the server will not approve this.

From a security perspective, the server is doing the right thing and holding the connection. This will prevent the agent from trying the reconnect over and over again. You can set the config.json to ignore this and allow the connection anyway, but that would not be great for security.

Let me know if this helps. This is probably not someone trying to do anything bad, but rather a man-in-the-middle corporate proxy. I know these also exists on public WIFI on airplanes.

**Comment by elpibedeoro** [comment]
> 
> Hi. So, the agent does connect to the server, but then the agent reports what TLS certificate it saw and the server needs to confirm this is correct. This error may be caused by an incorrectly configures reverse proxy or TLS offloader - If this is the case, all your devices will have this problem.

Hi,
Thanks for your reply, your explication is clear and really useful. Effectively this is not my case.



> 
> Now, if your devices generally work but your seeing this for one device only, one possibility is that one device is behind a corporate proxy that is a bit evil and acting as a man-in-the-middle for TLS connections. That is, the agent connects to the corporate proxy which will present a dummy corporate TLS certificate and decrypt the connection to inspect what is going on. If this is the case, the agent will tell the server it's seeing the corporate TLS cert and the server will not approve this.

> From a security perspective, the server is doing the right thing and holding the connection. This will prevent the agent from trying the reconnect over and over again. You can set the config.json to ignore this and allow the connection anyway, but that would not be great for security.

When you say that the server doesn't approve this, it means that the connection is hold but the agent is not managed ?
About the config, you are right I'd rather keep to not ignore this indeed.



> 
> Let me know if this helps. This is probably not someone trying to do anything bad, but rather a man-in-the-middle corporate proxy. I know these also exists on public WIFI on airplanes.

Sure it helps, you gave me a great explication ! 
Just a question : I cannot find the agent's hostname, I only get its IP address. I see that several times, for instance for the duplicate agents.
For example, for this case when I type "ip:12.34.56.78" in the MC2 search engine, nothing appears. So how could I know the "IP address - hostname" association in my database ? This would help me to identify the computer affected by the problem.

A big thank you.

**Comment by Ylianst** [comment]
- When you say that the server doesn't approve this, it means that the connection is hold but the agent is not managed ?

Correct. The server will ignore any data coming from the agent and will not interact with it. So, it will not show up on the console. Basically, the server suspects that someone is listening to the conversation. It just holds the connection to avoid the agent trying to connect over-and-over again.

- I cannot find the agent's hostname

Not all IP addresses have a DNS name, in fact, most do not. So, you can try to perform a DNS reverse lookup, but for many IP addresses on the internet, there is no associated DNS name. So, this is normal.

**Comment by elpibedeoro** [comment]
> 
> 
>     * When you say that the server doesn't approve this, it means that the connection is hold but the agent is not managed ?
> 
> 
> Correct. The server will ignore any data coming from the agent and will not interact with it. So, it will not show up on the console. Basically, the server suspects that someone is listening to the conversation. It just holds the connection to avoid the agent trying to connect over-and-over again.
OK thanks, that's a really good point. As far as the computer is not showed up on the console, it's alright.

> 
>     * I cannot find the agent's hostname
> 
> 
> Not all IP addresses have a DNS name, in fact, most do not. So, you can try to perform a DNS reverse lookup, but for many IP addresses on the internet, there is no associated DNS name. So, this is normal.

Yes, I understand this. I think I might have been not clear. 
If I trace the server, some IP shows up as duplicate agents so I realize there must be an agent installed on the remote computer.
I look for this IP address in the search engine but I get any result. So I get confused : if an agent is installed, I expect to get some information about the remote computer, like the hostname for instance. 
Is there anything that I've missed up maybe ?

**Comment by Ylianst** [comment]
If you suspect that an agent is connecting but not showing up, you can go in the "My Server" / "Console" tab and type `agentstats` and `agentissues` to see any connection problems:

![image](https://user-images.githubusercontent.com/1319013/112381120-71b44a00-8ca7-11eb-8e1b-f7be01b2d514.png)

It's possible that an agent is not configured correctly and would try to connect but not authenticate the server correctly.
