### ISSUE TITLE
MeshRouter Relay Map mapping issue

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2344]
I know this was reported before but I can't find the original report.  But I see it is still present in the current version of MeshRouter with 0.7.80.

When you add a relay map the RDP and Putty pre-defined remote ports are swapped. What I mean by that is when you choose Putty, for example, it will populate the Remote Port field with 3389 (which is actually the RDP port).  If you choose RDP the it populates the Remote Port with 22 (which is the Putty port).  See the screen shots below. This has been an issue for quite a while now- going back many versions. 

![meshrouter1](https://user-images.githubusercontent.com/48607498/109850572-a8ef8800-7c20-11eb-9c83-dde2b26c91ae.JPG)
![meshrouter2](https://user-images.githubusercontent.com/48607498/109850573-a8ef8800-7c20-11eb-800d-c27a5d217150.JPG)

**Comment by Ylianst** [comment]
Your right. "Add Map..." is ok, but "Add Relay Map..." is not. Working on it.

**Comment by Ylianst** [comment]
Fixed. Will be in next MeshCentra v0.7.81, but you can download the new [MeshCentral Router here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) right now. Thanks for reporting. Let me know if that works.

**Comment by PathfinderNetworks** [comment]
It works perfectly now. Thanks!
