### ISSUE TITLE
list of all parameters for the configuration ini

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#2346]
Hi , is there an updated document that contains all the parameters for the configuration ini supported by the latest meshcentral version with a brief explanation?

**Comment by yomono** [comment]
There is no INI but i assume you mean the config.json file, right?
In that case yes, here is exactly what you are asking for: 
https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json

**Comment by tradexsrl** [comment]
yes is the json config file.
thank's
