### ISSUE TITLE
[Feature] Autosave chats and log names in saved chat conversation

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#2347]
I've been heavily using the chat feature to engage with users before remote controlling.  It's been working really well! :)

A couple of features I'd like to suggest:

- Configurable option to save all chats centrally.  I regularly do it manually but it would be handy if the server saved all chats so I can retrieve them in case I forget to save manaully
- In the conversation log, replaced 'Control>' and 'Local>' with the Meshcentral user, and the Windows username respectively
- Might be helpful to log the computer name at the top of conversation so it's easy to know what computer, and what user & support staff were communicating.

e.g. currently the chat log looks like this:

> 9:10:43 PM - Control> Waiting for other user...
> 9:10:59 PM - Control> Connected.
> 9:11:18 PM - Local> Hey
> 9:11:24 PM - Remote> Hey
> 9:11:30 PM - Remote> How is it going?
> 9:11:34 PM - Local> Good you?

Thanks! :)

**Comment by Ylianst** [comment]
Good suggestions.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.8 that now allows all chat sessions to be recorded.

![MC2-MessengerRecord1](https://user-images.githubusercontent.com/1319013/114347624-180ea500-9b1a-11eb-892a-56cad4c1dcc0.png)

![MC2-MessengerRecord2](https://user-images.githubusercontent.com/1319013/114347632-1a70ff00-9b1a-11eb-9b1d-b2a0e02197d9.png)

Let me know if that works.

**Comment by cgb** [comment]
Hey Yilan, yep that's looking great!  Thank you so much.

Would it be difficult to log the logged in username on the remote machine?  That will be helpful for multuser systems where the chat is related to a specific user.

And in my first test, I saw ctrlChannel pong messages in the chat history:
```
Mon, 12 Apr 2021 12:03:34 GMT, <<<START>>>
Mon, 12 Apr 2021 12:04:04 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:04:05 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:04:22 GMT, --> Hey is everything OK?
Mon, 12 Apr 2021 12:04:34 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:04:34 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:04:38 GMT, <-- Umm I'm having trouble opening Outlook
Mon, 12 Apr 2021 12:04:56 GMT, --> No worries, let me look into it
Mon, 12 Apr 2021 12:05:04 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:05:04 GMT, {"ctrlChannel":"102938","type":"pong"}
Mon, 12 Apr 2021 12:05:05 GMT, <<<END>>>
```

Is that expected?

Thanks!

**Comment by Ylianst** [comment]
Arg! I forgot about the ping/pong's! Fixing that now.

**Comment by Ylianst** [comment]
Put in a fix for this, will be in MeshCentral v0.8.9 when it's next published.

**Comment by cgb** [comment]
Thank you, I'll test it out. 

The other element of this feature request was logging the logged in user on the remote PC for clarity.  Would that be possible at some stage? :)

**Comment by Ylianst** [comment]
I will close this issue. For other requests, please open a new issue. Thanks.
