### ISSUE TITLE
NGINX Reverse Proxy Slowdown

### ISSUE THREAD

**Issue by rroseselavy42** [Ylianst/MeshCentral#235]
Hey There, 

I'm really going here as a last attempt as I can't seem to figure out what's going on. 
I'm using the reverse proxy with TLS offloading instructions in the setup guide. Currently I'm getting progressive slowdowns of NGINX with about 100 clients connected. I end up needing to restart nginx every 24 hours or I get timeouts when connecting to the frontend. 

Server load is fine, Ubuntu 18.04, plenty of RAM and CPU to go around. Hosting on Linode VPS which otherwise is serving up stuff just fine. 

Totally at a loss and I know this isn't truly a "bug" but possibly may need some adjusting to the setup instructions.

**Comment by rroseselavy42** [comment]
nginx does not present any useful errors in the access or error log. tried access log both on and off but no dice.

**Comment by rroseselavy42** [comment]
well This should teach me. Finally realized what probably is happening here. getting "Too many open files" error. set the `worker_rlimit_nofile` to an arbitrarily high number (20000) will check tomorrow and close it myself if that solves the issue.

**Comment by Ylianst** [comment]
Ha. Thanks for taking a look at this. Please let me know if it fixes it. I can add this to the MeshCentral NGNIX documentation. On a similar note I have noticed that by default MeshCentral would only support 4096 connections until I added this line to the meshcenral.service file:

`LimitNOFILE=1000000`

Because MeshCentral keeps long standing web socket connections, we may need to change the configuration of reverse-proxy software.

**Comment by rroseselavy42** [comment]
No luck, still getting 
`socket() failed (24: Too many open files) while connecting to upstream`

after several hours. 
It clears up for about 6 hours after I restart nginx, which makes me wonder if there is some sort of leak here?

**Comment by Ylianst** [comment]
You can take a look at this link: [https://www.nginx.com/blog/tuning-nginx/](https://www.nginx.com/blog/tuning-nginx/). There is a section on file descriptors with:

    sys.fs.file-max – The system‑wide limit for file descriptors
    nofile – The user file descriptor limit, set in the /etc/security/limits.conf file

One more thing to look at. When you are logged in as administrator on MeshCentral. Go to the "My Server" tab and the "stats" page. Look at the connections graph. You may see if there is a leak there.

On my servers I had an issue where the relays system would have lots of one-sided connections. I added a 30 second timeout to clean these up a few days ago and it really fixed the relay connections count that kept going up for me. This is in the latest version.

Lastly in the "My Server" tab, go to "console" and type "relays". That should not be too long of a list. Then try: agentstats, webstats, acceleratorsstats. These are counters that give a good idea what the server is doing. You can post these if you see something not right.

**Comment by rroseselavy42** [comment]
hmm, I did read through that, looks like adjusting this makes things take longer to cause problems, but still eventually causes them.  doing lsof for www-data is getting 3242 open files for ~100 agents connected which seems wrong.

**Comment by rroseselavy42** [comment]
Unfortuantely still getting this, but I did see something interesting in agentstats @Ylianst 
`> agentstats
createMeshAgentCount: 1995
coreIsStableCount: 2026
verifiedAgentConnectionCount: 1981
clearingCoreCount: 0
updatingCoreCount: 46
recoveryCoreIsStableCount: 0
meshDoesNotExistCount: 0
invalidPkcsSignatureCount: 0
invalidRsaSignatureCount: 0
invalidJsonCount: 0
unknownAgentActionCount: 0
agentBadWebCertHashCount: 0
agentBadSignature1Count: 0
agentBadSignature2Count: 0
agentMaxSessionHoldCount: 0
invalidDomainMeshCount: 0
invalidMeshTypeCount: 0
invalidDomainMesh2Count: 0
invalidMeshType2Count: 0
duplicateAgentCount: 1628`

should duplicateAgentCount be so high?

**Comment by rroseselavy42** [comment]
note on my install. I used a config management software (Puppet) to install the agent to sites into a Group called "Intake" and then moved computers into their proper group. I'm wondering if that could be part of the issue?

**Comment by Ylianst** [comment]
Well, there is a problem with "duplicateAgentCount: 1628". This happens when two agents have the same certificate and so, the same identifier. Because the server thinks they are the same device, when one connects the other is disconnected. Upon disconnection the disconnected agent tries to connect again and the cycle repeats. If you type "agentstats" many times, you will likely see the "duplicateAgentCount" go up every second as agents fight to reconnect. This is not good.

This is probably caused by a cloned computer. If you know what computers are doing this, stop the agent, delete the "meshagent.db" file and start it up again. It will generate a new certificate and connect with a new identifier.

I need to work on a better fox for this because it's also causing problems on my servers. One option would be for me to not disconnect the duplicate agent, just keep the connection but do nothing with it. That way, you don't get the connection storm.

**Comment by Ylianst** [comment]
... come to think of it, another possible cause of all the duplicate agents is that there is a timeout for idle connections on NGNIX. On my documentation I set the following timeouts:

In the http section:
    proxy_send_timeout 999999s;
    proxy_read_timeout 999999s;

http/server section:
    ssl_session_timeout 999999s;

**Comment by whorvath2** [comment]
FWIW: I started at a software shop the other day that uses nginx, which I had no experience with until then. After I'd finished configuring my machine at the end of my first day, I started trying to get their software running locally, incl. by starting nginx. I began encountering the 'too many files open' error on the second day, when trying to get it running again.

The short version of the story is that there was another set of nginx master/worker processes running that were gumming up the works:

`$ ps aux | grep nginx
nobody            1579   0.0  0.0  4337172    996   ??  S     2:47PM   0:00.06 nginx: worker process
root              1578   0.0  0.0  4292428    336   ??  Ss    2:47PM   0:00.00 nginx: master process nginx
nobody           88581   0.0  0.0  4337172    512   ??  S     5:36PM   0:00.45 nginx: worker process
root             88580   0.0  0.0  4283212      8   ??  Ss    5:36PM   0:00.00 nginx: master process nginx
bill              2869   0.0  0.0  4258648    208 s002  R+    3:15PM   0:00.00 grep nginx
`

After I killed off the older processes and restarted nginx, everything worked correctly. It's possible that a change I made to the configuration file before I started the more recent processes had something to do with how it all happend (I repointed / to port 80 from port 8080.)

**Comment by rroseselavy42** [comment]
> In the http section:
> proxy_send_timeout 999999s;
> proxy_read_timeout 999999s;
> 
> http/server section:
> ssl_session_timeout 999999s;

I did set the timeouts to be this long. 

> Well, there is a problem with "duplicateAgentCount: 1628". This happens when two agents have the same certificate and so, the same identifier.

From the design document, I gathered that the agent certs are generated on the host computer? how would there be an overlap? 
Is there an easy way to detect where this overlap may be occurring?

**Comment by Ylianst** [comment]
I am working on a new version of MeshCentral that will improve the debugging of "duplicate agents". Hopefully will be done later today.

Yes, an agent generates a self-signed certificate and uses that as identifier. It's very unlikely the same certificate would be generated by two different computers. Maybe a computer was copied into another one, or the same computer is running the agent twice, or the computer is getting disconnected and trying to reconnect to the server over-and-over again.

It looks like your NGNIX settings are correct, if you can post the complete settings you have for MeshCentral (config.json) and NGNIX, I can also try to make the problem happen myself. If you post settings please "xxxxx" any server names, secrets or private data... and/or mail it to me directly. I really want to fix this issue.

**Comment by rroseselavy42** [comment]
thank you for the interest in the issue as it seems extremely edge case. 
```
{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "XXXXXXXX",
    "Port": 1025,
    "AliasPort": 443,
    "RedirPort": 1024,
    "TlsOffload": "127.0.0.1",
    "mongodb": "XXXXXXX",
    "mongodbcol": "meshcentral",
    "WANonly": true,
    "WebRTC": true,
    "ClickOnce": true
  },
  "domains": {
      "": {
          "certUrl": "XXXXXXXX",
          "Title": "XXXXXXXX",
          "Title2": "Remote Management",
          "_TitlePicture": "logo.png"
      }
  },
  "smtp": {
      "host": "XXXXXX",
      "port": XXXXX,
      "from": "XXXXXX",
      "user": "XXXXXXX",
      "pass": "XXXXXXXX",
      "tls": XXXXXX
  }

}
```

```
server {
  listen 80;
  proxy_send_timeout 999999s;
  proxy_read_timeout 999999s;
  server_name XXXXXXXXXX;
  location / {
     proxy_pass http://127.0.0.1:1024;
     proxy_http_version 1.1;
     # provide host information
     proxy_set_header X-Forwarded-Host $host:$server_port;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
	}
}

#HTTPS
server {
    listen 443 ssl;
     proxy_send_timeout 999999s;
     proxy_read_timeout 999999s;
    server_name XXXXXXXXXXX;
    ssl_certificate XXXXXXXXX;
    ssl_certificate_key XXXXXXXXX;
    ssl_session_cache shared:WEBSSL:10m;
    ssl_session_timeout 999999s;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    location / {
        proxy_pass http://127.0.0.1:1025;
        proxy_http_version 1.1;
        

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```


things added to nginx.conf
```
worker_rlimit_nofile 30000;
events {
	worker_connections 3070;
     multi_accept on;
     use    epoll;
}
```

**Comment by rroseselavy42** [comment]
Thank you so much for the dupagent feature, I have done a test using the console and it's been interesting what comes up with this. 
Could moving agents to different device groups be causing this? We use this feature extensively to sort the devices that come into our system.I noticed none of the duplicate counts are in our default device group

**Comment by rroseselavy42** [comment]
to update on this. I've tried removing and re-adding systems that have a high duplicate agent counts (some as high as 1000's) Unfortunately they show up again and the number starts going up again. I'm having trouble figuring out exactly how this is happening as it's happening across multiple sites. Can I send along any other information that may be helpful here?

**Comment by Ylianst** [comment]
Thank you so much for your reports! Your certainly motivating me to fix this. I am seeing exactly the same problem on my servers and I am wondering why this is happening myself. So, I just published MeshCentral v0.3.5-i with new "AgentPing" and "AgentPong" settings that may help. You add this in the settings section of the config.json file with the number of seconds, for example:

```
{
  "settings": {
    "Port": 443,
    "AgentPing": 60
  },
  "domains": {
    "": {
      "title": "Test Server"
    }
}
```

This will send a "ping" command over the agents TLS control channel every 60 seconds and the agent will respond with a "pong". It will not show anything, but may keep the HTTP proxies / NAT's / Firewalls happy that there is traffic and not an idle connection.

You can also do "AgentPong": 60, in that case, every 60 seconds the server will send the "pong" command and the agent will not reply to it. So, it's server to agent traffic only. I am going to experiment with this and see if it makes any difference on my servers. If you do the same, please let me know if it changes anything.

**Comment by Ylianst** [comment]
I have been trying "AgentPing": 60 on my servers for a few days now and it makes no difference. I am now thinking that having duplicate agents is sometimes normal, especially if the remote agent is on wireless. If the wireless connection drops for a bit and comes back, the agent will reconnect without the server having received a connection closure for the previous connection. So, it would make sense this happens.

If I disconnect and re-connect the Ethernet cable from one of my computers, I can get this situation to happen. So, I now think it's just something the server needs to deal with. I also see the old connection timeout after a while, so things clean up correctly.

If I am correct, the agent duplicate connections do not answer the original issue with NGNIX posted here.

**Comment by rroseselavy42** [comment]
I mean I guess after that maybe it is a red herring, I just thought that it was connected as the vast number of open files was unusual. as was the large duplicate agent count.

**Comment by Ylianst** [comment]
**Try this!** Put "AgentPing": 300 in the settings section of config.json. Then change NGNIX config like this:

#HTTP
   proxy_send_timeout 60s;   # 60s is the default, so you can also comment out
   proxy_read_timeout 60s;    # 60s is the default, so you can also comment out

#HTTPS
   proxy_send_timeout 330s;
   proxy_read_timeout 330s;
   ssl_session_timeout 5m;    # 5m is the default, so you can also comment out.

This problem is likely that these long timeouts cause NGNIX to never clean up and pile up file handlers (which are also used for network sockets). You could also keep all of the NGNIX default values and put "AgentPing": 50 so that there is traffic to each agent each 50 seconds. However, probably better to put a longer timeouts on port 443 and ping at a slower rate to lower idle traffic.

Let me know what you see!

**Comment by Ylianst** [comment]
FYI. Just updated latest MeshCentral User's Guide with updated NGINX configuration: [http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf)

**Comment by rroseselavy42** [comment]
open file handles have kept a steady 250-300 for last several days! I think we can call this one fixed with the changes to the nginx configuration!
