### ISSUE TITLE
Feature Request: Added timestamp to event notification popup

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#2352]
Hi

Was wondering if it would be possible to add the date and time to events that pop up when an agent disconnects / reconnects, something like:

![image](https://user-images.githubusercontent.com/6532805/110105045-ceef6680-7d9f-11eb-92cb-359487c8393f.png)

Thanks

**Comment by Ylianst** [comment]
Good request. Working on it now.

**Comment by Ylianst** [comment]
I just noticed, if you hover over the notification, it will tell you when it occurred.

![image](https://user-images.githubusercontent.com/1319013/110164868-d2d2b700-7da6-11eb-849b-0c92eb88bdc7.png)

**Comment by Ylianst** [comment]
Ok. Added the time like this and hover still works. Will be in the next version.

![image](https://user-images.githubusercontent.com/1319013/110165193-6dcb9100-7da7-11eb-82b3-8d84fbc7c395.png)

**Comment by drnikcuk** [comment]
Amazing, thanks @Ylianst 

Have we lost the event that goes with the date? (Disconnected / Connected)

**Comment by Ylianst** [comment]
Click on a device and hover your mouse on top of the timeline power bars. It will tell you the start and end time.

![image](https://user-images.githubusercontent.com/1319013/110175948-67ddac00-7db7-11eb-8948-c11f0cede728.png)

**Comment by Ylianst** [comment]
MeshCentral v0.7.82 is out with this fix. Let me know if it works.

**Comment by petervanv** [comment]
On mouse over, the time is displayed partly in Dutch and English
![image](https://user-images.githubusercontent.com/58996467/110216770-419c3700-7eb1-11eb-8743-ca9537632034.png)

**Comment by Ylianst** [comment]
Still no feedback from @drnikcuk, closing.

**Comment by drnikcuk** [comment]
Sorry - i thought my comment saying it was Amazing covered it.

Its defo working and what I was hoping for, thanks.
