### ISSUE TITLE
Bug: Devices imported via MeshCmd defaulting to IP instead of hostname

### ISSUE THREAD

**Issue by ad-85** [Ylianst/MeshCentral#2354]
Having a new issue here in our agentless environment where the device will no longer be imported using its FQDN hostname after adding it via meshcmd. This used to work fine, but about a month ago when we updated to address different issues it started falling back to IP.

We looked into it being a DNS issue but even the server seems to pick up the hostname fine during the add process - it just doesn't show up in the device info afterward. We updated again today to latest but the issue is still persistent.

Versions:
![108251249-28f7f700-7125-11eb-9ea4-d3e0f00025a8](https://user-images.githubusercontent.com/75687646/110125787-b5dfb900-7d91-11eb-978b-92947859686f.png)

Server log excerpt during add:
![108251247-285f6080-7125-11eb-83e9-019a847bf268](https://user-images.githubusercontent.com/75687646/110125816-bbd59a00-7d91-11eb-9fbd-5e2af3cf39df.png)

Ping/NSlookup test
![108251248-285f6080-7125-11eb-8731-cabdcc53733d](https://user-images.githubusercontent.com/75687646/110125836-c132e480-7d91-11eb-8cab-7dd7a58132c2.png)

Sample device:
![Mesh-Device](https://user-images.githubusercontent.com/75687646/110125862-c8f28900-7d91-11eb-9639-4849cb3f2990.png)

**Comment by Ylianst** [comment]
Your right. This is an important one and good timing. I am working today on improved Intel AMT ACM activation and will add that in.

**Comment by Ylianst** [comment]
Working on this one now.

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v0.7.83 when it's next published. Let me know if that works for you.

![image](https://user-images.githubusercontent.com/1319013/110369082-b761e900-7ffe-11eb-9305-bcaf5d7a8c60.png)

**Comment by Ylianst** [comment]
MeshCentral v0.7.83 is out. Let me know if it works for you.

**Comment by ad-85** [comment]
It's working now! Thank you Ylian!
