### ISSUE TITLE
Force agent functions- clear core / update default core 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2355]
Dear Ylianst ,

First i would like to say big thanks to all MeshCentral Teams.

Recently implanted bulk agent update facility is working properly.

Due to increase the number of agents i have migrated the application into new server. 

After migration all Pc's came online in my dashbord, But while checking i found that approximate 350 system is not accessible and Desktop / Files options showing blank.

I have tried Clear core, Upload default core functions this will resolve the issues.

Can you please implement bulk clear core / update default core file function in upcoming versions.

**Comment by Ylianst** [comment]
Hi. Try this first. Run your server like this:

```
node node_modules/meshcentral --noagent update
```

Or add the following line in settings section of config.json

```
"noagentupdate": true
```

The restart your server. Then, select some devices and do "Force agent update" in "Group Action"

![image](https://user-images.githubusercontent.com/1319013/110162769-05c77b80-7da4-11eb-9d31-2df40c7b0b92.png)

Let me know if that works.

**Comment by VINISHVV** [comment]
Dear Ylianst 

I have already tried this method. But it's not succeed.

**Comment by Ylianst** [comment]
What version of MeshCentral are you using and are you using any plug-ins?

**Comment by VINISHVV** [comment]
@Ylianst 
I am using Version 0.7.81 without any plugins.

**Comment by Ylianst** [comment]
Ok, working on this one now.

**Comment by VINISHVV** [comment]
Thanks Ylianst

**Comment by Ylianst** [comment]
This will be on MeshCentral v0.7.83 coming out later today.

![image](https://user-images.githubusercontent.com/1319013/110361582-128ede00-7ff5-11eb-93b7-f2d43f230944.png)

**Comment by Ylianst** [comment]
MeshCentral v0.7.83 just got published.

**Comment by VINISHVV** [comment]
Thanks @Ylianst ...

Its working fine.
