### ISSUE TITLE
Issues with NGINX Proxy Manager / Lets Encrypt

### ISSUE THREAD

**Issue by SpikeyDan** [Ylianst/MeshCentral#2356]
Hi There! Love the software. 

I have an issue where I have installed Meshcentral on its own VM in Ubuntu 20.04 and NGINX Proxy Manager in a docker container and the agents will not connect back to Meshcentral. The error I am getting is: Agent bad web cert hash. I can see the two hashes are different. I did not have this issue until NGINX and SSL certs were involved. I have searched and searched past problems/manuals and have tried many different changes to the config but I cannot seem to get anywhere. I would be so grateful for help.

Here is my config JSON:

192.168.1.161 - NGINX
192.168.1.160 - Ubuntu VM with Meshcentral
"ignoreagenthashcheck": true - this unfortunately does not work either

```
{
"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_MongoDb": "mongodb://192.168.1.160:27017/meshcentral",
    "cert": "mesh.mydomain.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "Port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "TlsOffload": "192.168.1.161",
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "https://mesh.mydomain.com:443/"
      "title": "DansMesh",
      "title2": "DansMesh",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by Ylianst** [comment]
"CertURL"  need to be a uri when MeshCentral will load the same TLS certificate that agents will see when connecting. You could try:

"CertURL": "https://192.168.1.161:443"

When you run MeshCentral manually using:

node node_modules/meshcentral

You should see the server load the cert from NGINX and show the hash if the cert. Then, then agents connect you will see what hash they see compared to when MeshCentral wants.

**Comment by SpikeyDan** [comment]
Hi Ylianst, 

Thanks for the quick reply! 

I tried changing to "CertURL": "https://192.168.1.161:443" and there is no difference unfortunately. Here is the output of hashes:
```
AgentCertHash: 98a3c8e15eb2d34b62e69498bfb25559eb65b21c61612d353be538f7b6638a7acf5853e1e19f308ca3662c8c33305240
webCertificateHash (): B2DB312128E27B04FB6350E55C036F7FC8CD3C35C63032C702B13BCE6BD6F58DA6A53BD69A2BEA79D893A545F8A77798
webCertificateFullHash (): 2D3E54DDFD9FC5F08302FED445DCF60B4855A42500396B3C6BB5F5D0EFB1790114F3721D21B343137FCCF9389DFA76C7
defaultWebCertificateHash: B2DB312128E27B04FB6350E55C036F7FC8CD3C35C63032C702B13BCE6BD6F58DA6A53BD69A2BEA79D893A545F8A77798
defaultWebCertificateFullHash: 2D3E54DDFD9FC5F08302FED445DCF60B4855A42500396B3C6BB5F5D0EFB1790114F3721D21B343137FCCF9389DFA76C7
```

Yes I put "ignoreagenthashcheck": true in the settings section. I am not sure what is going on here. I can't figure out if it's a slight config issue in Meshcentral or I have done something wrong in NGINX Proxy Manager. I do get a proper SSL cert connection when browsing to my URL though. Only issue I am seeing is from the agents. 

Hope you can help solve this mystery as I am pulling out my hair lol

**Comment by SpikeyDan** [comment]
Hi Again,

After so much trial and error I just reinstalled the VM and MeshCentral. I made changes one line at a time till the host checked in again. It appears the agent hash is different still:

```
AgentCertHash: 489aa51895c2205c4b3823a661a1b1dbdbebfc4be8fd58d24adfb1e9b90de716bdbc3b21085693efbcdf2b89d829a6da
webCertificateHash (): 1939E2D56E44BFEC5EF607EEFEA1EFFACF15152CCBA728A25DB0C21B9CE71E4C50D3E4CE773DABAD9CC157646E50D6F5
webCertificateFullHash (): F28B3843C5E8B653C94C7337750981113A04D9ED3918020E4FD14DFB6272AFB99B498B003A5790DDCAEAB7BFBEC85F3D
defaultWebCertificateHash: 0E1C1E149FBC63FF6C26EC2816A2B01A82A7DC7EF0F7BEF0E28411673F50AC51CBBDD763C93572C53B0CD36441E3A793
defaultWebCertificateFullHash: 97EFDC1270FBF811F28681C5B542FD1BDCC651083FE7EFF36C11169ECE7653AEA13D5DCB5179E61A79B8811C9FC8AE50
```

Should I be concerned about this? Will this mean I am at risk of MITM attacks? FYI here is my current config which I made barely any changes to from default:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with >
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced >
  "settings": {
    "cert": "mesh.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "192.168.1.161",
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before try>
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by LPJon** [comment]
@SpikeyDan What's making it work in the new config is that MeshCentral is running in "Hybrid" mode. In your original config you had this:
```
    "WANonly": true,
    "_LANonly": true,
```
the new config (Hybrid Mode) looks like this:
```
    "_WANonly": true,
    "_LANonly": true,
```
In the first config MeshCentral was configured to only accept connections from Public IP's. Which means it's expecting to be connected to a public IP address(no proxy). In your first config you have a private IP address assigned to MeshCentral because of your proxy and your proxy also has a private IP address. This means that MeshCentral is seeing your proxies IP for connections and denying the connection. "Hybrid" mode accepts both Public(WAN) and Private(LAN) IP connections. Be sure to re-add this setting `"TlsOffload": "192.168.1.161",` but keep "Hybrid" mode and also add `"trustedProxy": "127.0.0.1,192.168.1.161",`

SIDE NOTE: MeshCentral evaluates the connecting IP address first before evaluating the ACTUAL IP of your remote agent. So basically MeshCentral ALWAYS sees your proxies IP address first then evaluates (through http headers) what IP is connecting through the proxy to MeshCentral. You need to tell MeshCentral about your proxy and that it needs to trust it with the `"trustedProxy": "127.0.0.1,192.168.1.161",` setting in the `"settings": {` section of the `config.json` with either mode enabled because you have a proxy. The Hash checks are related to the fact that you have re-installed MechCentral. Just re-install the agents you were using for testing with ones from the new install and that should sort itself out. To be clear you never had an issue with the Hash's it was simply the proxy and MeshCentral were not playing nicely because of those settings above.

Your new working config would look something like this:
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with >
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced >
  "settings": {
    "MongoDb": "mongodb://192.168.1.160:27017/meshcentral",
    "cert": "mesh.mydomain.com",
    "WANonly": true,     <------------Only if your agent connections are from the internet
    "_LANonly": true,     <------------Only if your agent connections are from your local network
    "__comment3__": "both of the above settings should have a "_" in front of them if you want to allow both types >
    "sessionKey": "You Should Fill This In With An Ultra Good Password",
    "Port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "TlsOffload": "192.168.1.161",
    "trustedProxy": "127.0.0.1,192.168.1.161",
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "https://mesh.mydomain.com:443/"
      "title": "DansMesh",
      "title2": "DansMesh",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before try>
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```



Hope that helps...

**Comment by SpikeyDan** [comment]
Hi LPJon. Thank you so much for the detailed reply.

I tried using all of your config and it unfortunately did not work. If I use the TLS offload option now it does not load the Mesh web page. Here is my current config that works in terms of the web page loading but not the agents checking in (IPs have changed):

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with >
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced >
  "settings": {
    "MongoDb": "mongodb://192.168.150.160:27017/meshcentral",
    "cert": "mesh.mydomain.com",
    "WANonly": true,     <------------Only if your agent connections are from the internet
    "_LANonly": true,     <------------Only if your agent connections are from your local network
    "__comment3__": "both of the above settings should have a "_" in front of them if you want to allow both types >
    "sessionKey": "You Should Fill This In With An Ultra Good Password",
    "Port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "_TlsOffload": "192.168.150.161",
    "trustedProxy": "127.0.0.1,192.168.150.161",
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "192.168.150.161"
      "title": "DansMesh",
      "title2": "DansMesh",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before try>
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

The console shows I successfully load the web cert but again the agents do not want to play ball. Not sure what to do next. Grateful if anyone has any ideas.


Thank you.

**Comment by SpikeyDan** [comment]
Hi All,

I think this one is now resolved. In the end it seemed to be a DNS issue where as MeshCentral was in a DMZ zone, my internal network was not able to get to my external facing address.

I used split DNS to solve this issue.

Thank you for your help. If there is any beta program or I can help with future testing then I would love to. Thanks again for the software. It is amazing!

- Daniel

**Comment by LPJon** [comment]
> 
> 
> Hi All,
> 
> I think this one is now resolved. In the end it seemed to be a DNS issue where as MeshCentral was in a DMZ zone, my internal network was not able to get to my external facing address.
> 
> I used split DNS to solve this issue.
> 
> Thank you for your help. If there is any beta program or I can help with future testing then I would love to. Thanks again for the software. It is amazing!
> 
>     * Daniel

That makes sense. Thank you for reporting back your resolution to this issue. It is very much appreciated.
