### ISSUE TITLE
Can't Connect with Router

### ISSUE THREAD

**Issue by GauchoEsq** [Ylianst/MeshCentral#2364]
I have a new install (0.7.83) on Ubuntu and am having difficulty using the router to connect to a server with RDP. I'm able to open the router and see my devices, but when I map a port and attempt to RDP through 127.0.0.1:33389 (or any other port I set up) it instantly fails. On the server, the trace log looks like the following:

404 Error /.websocket?key=XXXXXX/meshrelay.ashx

I am using a LoginKey. Everything else seems to work - I can RDP to the device locally and the regular Desktop MeshCentral connection through the site works.

**Comment by Ylianst** [comment]
The login key is not correctly placed in the URL. Which MeshCentral Router are you using? Windows, macOS?

**Comment by GauchoEsq** [comment]
I am using the Windows router that is presented as a download from within our instance MeshCentral

I run the router (1.4.7732) and at the login screen, I enter the URL in the form of xxx.xxx.com?key=xxxx. I am not entering http:// or https://. I then enter the MFA token and it takes me to a list of my devices/agents.  

I go to Mappings and press Add Map. I give it some name, select 33389 for the local port, change the application to RDP, and then press OK. There is only one agent installed at the moment so I don't need to select the remote device. It creates the entry under Mappings, and when I press Open I am presented with an RDP window with 127.0.0.1:33389 already entered. I then press Connect and it immediately fails and the 404 is entered into the trace log.

**Comment by Ylianst** [comment]
Ha! Ok. I see the same problem. Working on a fix now.

**Comment by Ylianst** [comment]
Ok, fixed MeshCentral Router. Will be in MeshCentral v0.7.85, but you can download the latest [MeshCentral Router v1.4.7739 here now](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Let me know if that works for you.
