### ISSUE TITLE
Feature request: Directly connect with RDP

### ISSUE THREAD

**Issue by kocane** [Ylianst/MeshCentral#2366]
Could you perhaps make it (optionally?) so when pressing connecting via RDP to a device thru the Mesh Router, it directly connects to the device instead of showing the Remote Desktop Connection window?

Also, thanks for the software - it's brilliant.

**Comment by OutbackMatt** [comment]
Can I add to this please
Can we have a RDP tab like the current "general', 'desktop', 'terminal', 'files', 'events', 'details', 'console', 'plugin' that says RDP 

Additionally I'd like a matching right click context option
And the ability to add that as an allowed function for specific users

The idea is that I can create users on my Mesh-Central that log into the web interface and from there can be presented with a selection of computers that they can ONLY RDP to. This would effectively make a web based MeshRouter that requires TFA.

RDP is faster and smoother than the 'Desktop', and also allows printing, and locks remote users out of the machine while it is being RDP'd to.

**Comment by kocane** [comment]
@Ylianst maybe just pass /v:127.0.0.1:port onto mstsc.exe. 

I wish mstsc had an idea about the client that we were connecting to so credentials could be saved per device in meshcentral but seeing as the computer will always be 127.0.0.1 maybe that's just the way it is.

**Comment by Ylianst** [comment]
I already pass in the IP and port to MSTSC. If there is some extra option I can pass, let me know. Closing for now.
