### ISSUE TITLE
MeshAgent built-in zip feature creates invalid file

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#2367]
I'm finding that a file created with the 'zip' facility in the 'Files' tab, when downloaded doesn't open, always gives an error.

Zipping the same folder from the desktop using Windows Explorer's built in 'compress files' gives a slightly different file size and is able to be opened upon download.

Also, is there a possibility of an 'un-zip' tool to extract files from a created zip.

(Love this software - thanks for your hard work)

**Comment by krayon007** [comment]
Can you send me the generated zip file?

**Comment by OutbackMatt** [comment]
Not the one I created the other day, but I will create a new one, and try and recreate the problem.

(I work in healthcare, and the file from the other day will contain patient detail)

**Comment by Ylianst** [comment]
Corrected the title. I just did a quick test and the zip file worked for me. We need more specific information to recreate the problem.

**Comment by VINISHVV** [comment]
@OutbackMatt 
I think this is generally due to zip algorithm used for each program.. I am using latest version of winrar and I can able to unzip the file...

I don't know whether this is  right answer., because I am also a meshCentral user like you....

**Comment by Ylianst** [comment]
So, it works for me, but if there is an exact case that it does not work... we need sufficient information to replicate the issue.

**Comment by Ylianst** [comment]
Ok, closing this one. If in the future you can provide a invalid zip file we can look at, please open a new issue. Thanks.
