### ISSUE TITLE
Plugins and MeshAgent.DB utilisation

### ISSUE THREAD

**Issue by circlecomputers** [Ylianst/MeshCentral#2368]
Hi

Many thanks for MeshCentral, it's a great product surpassing many commercial RMM solutions.

I have been testing some plugins on my Mesh Central install and have noted two issues that seem to co-inside with the plugin addition.

Node.js processor utilisation went up hugely following the installation (12thFeb on Graph) and I have also started to note that the MeshAgent.DB size on devices is hitting 22GB which means a couple of devices with small disks have started to show up as full.

I have now disabled the plugins and will monitor the utilisation. Can I just delete the associated folders from the plugins folder on the server?

Although the plugins are now disabled I suspect the MeshAgent.DB will need some manual processing to shrink it, or is the periodic rebuild process?

Gary

![image](https://user-images.githubusercontent.com/60174594/110591919-8ce46d00-8171-11eb-829c-54a9e161afd2.png)

**Comment by Ylianst** [comment]
I don't test plugin's at all and so, you need to file a bug with the plug-in author.

**Comment by circlecomputers** [comment]
Hiya

Agreed, I was just flagging the add in's impact as a lead in to the decision that I disabled them.

My question was around the removal of the add in from directory structure on the MeshCentral server. I assume I can just delete folders but wanted to check.

The other part was around resetting the size of MeshAgent.DB ... on the devices, I suspect this needs rebuilding back to a default size but I have no idea what is in the DB and is there is a 'prescribed' way to do this. If not I'll find a victim endpoint and delete the DB and see what happens!

Thanks

Gary

**Comment by Ylianst** [comment]
That should work. You can also remove the `"plugins"` line in the config.json, that will make sure MeshCentral does not load plugins.

For the MeshAgent.db. If you delete the MeshAgent.db and restart the agent, it will come back as a new device on the site and you will need to remove the old device from the web site. I don't have any way to go into the .db file of the agent and removing the extra data that was added in that database. That could be a request for Bryan if you want to open a new issue to ask for that.
