### ISSUE TITLE
Mesh Agent is crashing daily basis (v0.6.28)

### ISSUE THREAD

**Issue by Dhamotharan96** [Ylianst/MeshCentral#2369]
Hi Team,

The 32-bit mesh agent crash is occurring on daily basis in Windows 10 Pro 64 bit machine. The mesh central server version is 'MeshCentral v0.6.28'.
The attachment contains the mesh agent log, meshagent.exe and meshagent.dmp file(this file is generated by enabling the coredumpenabled=1 in meshagent.msh file).

[Mesh Central Support.zip](https://github.com/Ylianst/MeshCentral/files/6114767/Mesh.Central.Support.zip)

Thanks.

**Comment by rylangrant** [comment]
+1 to you being able to move the stable version forward, I'm eager to try out the new features! :)

**Comment by Ylianst** [comment]
The agents are stable and working well. I just moved MeshCentral.com to v0.7.85 to fix a bug with the feature that allows you to view previous account logins. Hopefully that will be the one I mark as stable. I will get it another day or two to make sure everything is ok.

**Comment by Dhamotharan96** [comment]
Thank you for this suggestion. 
I will hold one/two day for a confirmation from your suggested v0.7.85 stable version.

**Comment by Ylianst** [comment]
Stable was just moved to MeshCentral v0.7.89. As usual, please backup before updating.

**Comment by Dhamotharan96** [comment]
Thanks, having another concern. If we just upgrade the mesh central server to v0.7.89, the existing communicating mesh agent will be auto-upgraded(please suggest if we setting for enabling/disabling auto upgrade).

**Comment by VINISHVV** [comment]
@Dhamotharan96 
Once you updated the server, Connected agents also updated automatically after few minutes. 

To restrict this  add "noagentupdate": "true"  In config.js

**Comment by Ylianst** [comment]
Exactly right. Once the server is updated, all agents will auto-update unless you add `"noagentupdate": "true"` to the settings section of the config.json. I am going to close this issue since the new agents have the fixes. Please open a new issue if you have questions on the update process. Thanks.
