### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by NathanSweet** [Ylianst/MeshCentral#237]
```
C:\MeshCentral\> npm install meshcentral
npm WARN saveError ENOENT: no such file or directory, open 'C:\MeshCentral\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\MeshCentral\package.json'
npm WARN MeshCentral No description
npm WARN MeshCentral No repository field.
npm WARN MeshCentral No README data
npm WARN MeshCentral No license field.
```

**Comment by theredkoala21** [comment]
What are the commands you are using to install?

**Comment by NathanSweet** [comment]
@theredkoala21 I edited the first post (the command was cut off): `npm install meshcentral`
I tried nodejs `10.15.3 LTS` and `12.2.0`.

**Comment by NathanSweet** [comment]
I also tried the Windows installer, but it hangs (I assume it fails in the same way).

**Comment by theredkoala21** [comment]
I haven’t installed the server component on a windows machine before. Give me a few.

**Comment by theredkoala21** [comment]
Try this: (sorry about the non code blocks. On mobile)

Download:
https://nodejs.org/dist/v10.15.3/node-v10.15.3-x64.msi

Install above MSI. 
Navigate to nodejs directory. Then run “nodevars.cmd” (has batch file icon)


cd c:\meshcentral
npm install meshcentral
npm install @davedoesdev/fido2-lib


My install output:

C:\MeshCentral>npm install meshcentral
npm WARN saveError ENOENT: no such file or directory, open 'C:\MeshCentral\packa
ge.json'
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN enoent ENOENT: no such file or directory, open 'C:\MeshCentral\package.
json'
npm WARN MeshCentral No description
npm WARN MeshCentral No repository field.
npm WARN MeshCentral No README data
npm WARN MeshCentral No license field.

+ meshcentral@0.3.4-l
added 182 packages from 162 contributors and audited 463 packages in 30.734s
found 0 vulnerabilities


Then to run: it needs some arguments as well (site name etc)

node c:\meshcentral\node_modules\meshcentral\meshcentral.js

**Comment by theredkoala21** [comment]
I made a quick install script for Windows x64.

[https://github.com/theredkoala21/MeshCentral-InstallScripts](https://github.com/theredkoala21/MeshCentral-InstallScripts)

**Comment by Ylianst** [comment]
@theredkoala21, thank you so much for helping users. One good news: as of a few hours ago, the latest version of MeshCentral 0.3.4-p no longer needs the "@davedoesdev/fido2-lib" module. I build FIDO2 support within MeshCentral and removed many dependencies. Hopefully it will help with installations.

**Comment by Ylianst** [comment]
I just tested installing on Windows. Node v10.2.1, NPM v5.6.0. Worked for me. I should work on getting rid of the warnings...

![MC2-WinInstall](https://user-images.githubusercontent.com/1319013/57904581-2964af00-7828-11e9-8c97-a91321cc9a4f.png)

**Comment by Ylianst** [comment]
Any feedback on this? Did the install work? - Thanks.

**Comment by Ylianst** [comment]
Will close this since it's probably fine now. Please re-open if needed.

**Comment by NathanSweet** [comment]
Sorry for the delay. It did work via the CLI. I didn't try to repro the installer hang. FWIW, the warnings look scary to new users.

Cheers!
