### ISSUE TITLE
Restrict Agent Uninstallation using Password

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2370]
@Ylianst 

Is there any possibilities for restrict the mesh central agent uninstallation using password / from mesh central UI options only.

**Comment by Ylianst** [comment]
Can you be more precise when you mean "restrict the mesh central agent uninstallation"? If that local uninstall on the device itself? Remote uninstall in the device group option? Explain exactly what uninstall you want to block. Thanks.

**Comment by VINISHVV** [comment]
Dear Ylianst , 

Can we restrict the local user agent uninstall using a random password.generated through mesh central ui like agent token. 

Since remote uninstall is already avail in mesh central above mentioned feature is sufficient. 

Regards, 
Vinish

**Comment by Ylianst** [comment]
MeshAgent agent is installed with administrator permissions. You need Windows administrator rights to uninstall it. If you have Windows administrator rights, you can always manually uninstall the agent by deleting the files so, this will not stop the user from uninstalling it. You are saying you would like the agent to prompt for a password on uninstall even if the user can easily get around this?

**Comment by VINISHVV** [comment]
Closing this issue, since it's not accepted by majority of MeshCentral users.
