### ISSUE TITLE
I have configured the TLS offload with my azure server (Windows Mesh server) but agent not connecting?

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2371]
I have configured the TLS offload with my azure server (Windows Mesh server) but agent not connecting?

My mesh Server running with following configuration . 

![image](https://user-images.githubusercontent.com/9078295/110630009-dad98f00-81ca-11eb-932f-a334de7f5539.png)

I can able to access my management portal in https://xyz/

But My agents not connecting to 

wss://xyz:443/

Is anything i am missing?

**Comment by Ylianst** [comment]
You need MeshCentral to know the certificate that the MeshAgents will see when connecting. To fix correctly, add the following line to the domain section of the config.json:

```
"certurl": "https://127.0.0.1"
```

On start, MeshCentral will use this URL to load the certificate from NGINX.

Alternatively for testing only, you can try enabling this line by removing the _ from the line:

```
"ignoreagenthashcheck": true
```

This is not a secure setting. It allows agents to connect even if the certificate is not correct. Let me know if that works for you.

**Comment by aimdharma1990** [comment]
> You need MeshCentral to know the certificate that the MeshAgents will see when connecting. To fix correctly, add the following line to the domain section of the config.json:
> 
> ```
> "certurl": "https://127.0.0.1"
> ```
> 
> On start, MeshCentral will use this URL to load the certificate from NGINX.
> 
> Alternatively for testing only, you can try enabling this line by removing the _ from the line:
> 
> ```
> "ignoreagenthashcheck": true
> ```
> 
> This is not a secure setting. It allows agents to connect even if the certificate is not correct. Let me know if that works for you.

Hi Sorry to reply on the closed issue. But i have enabled tls (Disabled tls offload) and i have put the certificate the Azure Load balancer proxy . Now Agent is connecting but its not showing the RemoteDesktop / terminal Option

I have run the Meshcentral in the debug mode and found below are sequence

WEB: handleRootRequestLogin()
HTTPHEADERS: GET /agent.ashx/.websocket {
  connection: 'Upgrade',
  upgrade: 'websocket',
  host: 'remote.sapphireims.com',
  'max-forwards': '10',
  'sec-websocket-key': 'rur9PUZd2JW7nrhqEDigRA==',
  'sec-websocket-version': '13',
  'x-forwarded-proto': 'https',
  'x-forwarded-port': '443',
  'x-original-host': 'remote.sapphireims.com',
  'x-original-url': '/agent.ashx',
  'x-forwarded-for': '14.98.4.222:44131',
  'x-arr-ssl': '2048|256|C=GB, S=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA|CN=*.sapphireims.com',
  'x-arr-log-id': '2fb9edeb-0ad2-4541-811e-78bc86af6f27'
}
WEBREQUEST: (10.1.3.149) /agent.ashx/.websocket
AGENT: New agent at 10.1.3.149:19949
AGENT: Verified agent connection to PmEliLCY3uHUUz4Ra0zgZVFy@vYspA6PEllOEl06uVyDH9mXUvjfxpQrTmrfkvob (10.1.3.149:19949).
DISPATCH: DispatchEvent [
  'node//PmEliLCY3uHUUz4Ra0zgZVFy@vYspA6PEllOEl06uVyDH9mXUvjfxpQrTmrfkvob',
  '*',
  'mesh//WQ9kPfGvkfTAEBs5wwQW77dDBOZjnWH6a0$9CP$xza67YQcjZ5ZMeQut5bT4Y7uN'
]
HTTPHEADERS: GET / { connection: 'Keep-Alive', host: '127.0.0.1', 'max-forwards': '10' }
WEBREQUEST: (10.1.3.148) /
WEB: handleRootRequestLogin()
AGENT: Updating core windows-amt
DISPATCH: DispatchEvent [
  'node//PmEliLCY3uHUUz4Ra0zgZVFy@vYspA6PEllOEl06uVyDH9mXUvjfxpQrTmrfkvob',
  '*',
  'mesh//WQ9kPfGvkfTAEBs5wwQW77dDBOZjnWH6a0$9CP$xza67YQcjZ5ZMeQut5bT4Y7uN'
]
HTTPHEADERS: GET / { connection: 'Keep-Alive', host: '127.0.0.1', 'max-forwards': '10' }
WEBREQUEST: (10.1.3.149) /


But the same when i tried to run in same system in local where the MeshCentral is hosted its working fine. 

Is there any issue i can check to resolve this?

**Comment by aimdharma1990** [comment]
My issue still exits

**Comment by Ylianst** [comment]
Try adding the following two lines in the settings section of config.json:

```
    "CookieIpCheck": false,
    "CookieEncoding": "hex",
```

This is just a guess based on past experience with Microsoft.

**Comment by aimdharma1990** [comment]
Hi,

I have already tried but no luck..

**Comment by aimdharma1990** [comment]
Hi Ylianst/MeshCentral

One more update. i have added webSocketMaskOverride=1 in the client side.
Then only its communicating to the server.

Is there anything will help

Thanks
Dharmaraj.G

**Comment by aimdharma1990** [comment]
Hi Ylianst/MeshCentral

I am getting "Timeout waiting for Server, launching cached meshcore" in the
Agent.

TLS offload I have enabled as TLSOffload = true

THanks
DHarmaraj.G

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
