### ISSUE TITLE
Question: Setting up MC2 in an ephemeral environment

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2375]
I'm looking to deploy MC2 in an online environment where ephemeral systems would be used to permit expansion due to load. I would be VERY interested in hearing if anyone has done this thus far. However assuming that that's not the case, I'm trying to ascertain what issues I'm likely to run into.

Roughly, my environment looks like:
1. A persistent database server (read/write access, backed up daily).
2. A persistent filesystem (read/write access, backed up daily).
3. An application load balancer which will route traffic to 
    1. an auto-scaling group containing 
        1. one or more ephemeral systems

Within my CI/CD system, I would spin up a OS, install node and MeshCentral and using the environment's API calls, obtain all relevant information regarding the database and the persistent file system.  A mount point to the persistent file system would be created. I would then reconfigure the `config.json` to point to my database and add all the other niceties that I need and then place the finished system into a deployment group.

Although I understand that a lot of data is held in the database, I was kinda hoping to keep the `meshcentral-data` and `-files` folders in the persistent filesystem, accessible by one (or more) of the ephemeral systems.  In fact I believe this is going to be a requirement, the `-data` folder at the very least. Obviously as the deployment group scales up and down the data needs to be accessible by all systems, not to mention that it would also be included in the daily backups.

AFAIK, the *only* way to do this is, once spun up through the CI/CD process, to:
1. Stop MC2
2. For the initial system, the two folders in question would be copied to the persistent filesystem.
2. Delete the local copies of the folders from the initial ephemeral system
3. Create a mount point, pointing to the persistent filesystem, mimicking the two local folders that were deleted in (2).
4. Start MC2
    1. At this point, the system is reading the two folders from the persistent filesystem and reading from the persistent database.
6. As new ephemeral systems are spawned, (3) and (4) are repeated

I believe I've already dealt with certificates being presented (via the load balancer) as @Ylianst has already thought of that and has configuration in place for it.

Questions:
1. Are the `-data` and `-files` folders the only ones that I need to worry about?
2. lol ... what else am I missing?!! :smiley:

**Comment by Ylianst** [comment]
There is a way to load the content of the "meshcentral-data" folder into the database so that the only file you need is a config.json that points to the DB. However, I have not tried this recently and there are many new features that probably don't take this into account.

For the "meshcentral-files" folder, you can specify a different path in the config.json, so you can point to a network drive. This is important since if you are using the server files feature, you want all the servers to see the same user files.

I am interested to know other people's experience on such setup.

**Comment by D4V3M0NK** [comment]
Can I ask what settings within the `config.json` would be used to manage both the `-data` to the database, and the `-files` folder to a different location? I don't see anything obvious in the [full](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json) config option?

**Comment by Ylianst** [comment]
The commands are:

--dblistconfigfiles
--dbshowconfigfile
--dbpushconfigfiles
--dbpullconfigfiles
--dbdeleteconfigfiles
--loadconfigfromdb

You specify them when you run MeshCentral:

```
node node_modules/meshcentral --dblistconfigfiles
```

I have not tried these for a long time, so not sure if they work or not.

**Comment by D4V3M0NK** [comment]
But just to confirm @Ylianst , there shouldn't be a problem placing the meshcentral-data/files folder on a shared resource and having potentially multiple MC2 servers accessing them?

**Comment by Ylianst** [comment]
Should not be a problem at all, you can create a symlink to anywhere you want.
