### ISSUE TITLE
MeshCentral fails to start when using our own signed certs

### ISSUE THREAD

**Issue by aztlanla** [Ylianst/MeshCentral#2376]
MeshCentral fails to start when using our own signed certs

I created the certs in IPA CentOS 7.8. I grabbed them and swapped them out with 

webserver-cert-private.key
webserver-cert-public.crt

in the meshcentral-data folder.

I restarted the service on the meshcentral server
systemctl restart meshcentral
and it fails to start.

Here is the error from the mesherrors file

```
-------- 3/9/2021, 1:33:57 PM ---- 0.7.82 --------

/opt/meshcentral/node_modules/meshcentral/certoperations.js:727
                    var acn = altNames.altNames[i].value.toLowerCase();
                                                         ^

TypeError: altNames.altNames[i].value.toLowerCase is not a function
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:727:58)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1370:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:144:13)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1297:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I looked at our cert and this is the contents of the Subject Alternate Names section. I changed the domains and replaced the numbers to XX for safety.

```
DNS Name=mesh-01.site.groundtest.net
Other Name:
     Principal Name=HTTP/mesh-01.site.groundtest.net@GROUNDTEST.NET
Other Name:
     1.3.6.1.5.2.2=XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX

```
It appears the script is failing in the alt names section.

**Comment by Ylianst** [comment]
Just put in a fix for this. It will be in MeshCentral v0.7.86, but you can download the new "certoperations.js" file now from [GitHub here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/certoperations.js). Replace that file and try again.

It should work, but if it does not and you can send me the public part of your certificate [at my contact here](https://www.meshcommander.com/contact-information). I will make sure it's fixed. Hopefully, that should not be needed.

**Comment by aztlanla** [comment]
I replaced the file certoperations.js with the new version and I am able to start the service and no more errors. The signed cert works.

Thank you for the quick fix, I appreciate it.
