### ISSUE TITLE
meshcentral.com is hacked? (It's not)

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#2377]
I haven't visited a public meshcentral.com for a long time. When I logged in and looked at the history of the last logins, I found many successful logins. I had two-factor authentication enabled. Now I have changed my master password. Please check your website.

**Comment by Ylianst** [comment]
No, it's my fault. I display all account logins instead of only the ones for your account. I noticed this a few days ago and did the fix. I will update MeshCentral.com now.

**Comment by Ylianst** [comment]
Just updated MeshCentral.com to v0.7.85. Take a look at the logins again, should be correct now.

**Comment by Ilia1** [comment]
Yes, now I see my last two logins. Thanks for the quick fix!
