### ISSUE TITLE
Tried Agent on CentOS and Raspberry Pi not working

### ISSUE THREAD

**Issue by gcstang** [Ylianst/MeshCentral#2379]
Logged in as root and performed the install script
- Add Agent
- select Linux/BSD
- Copy and run on computer as root
- Shows in Webpage but nothing works
- If I click on Console it say's Agent is running but if I type a command like 'info' it does nothing

Not sure what I'm missing or if I have some odd configuration
<img width="481" alt="Screen Shot 2021-03-11 at 11 41 10" src="https://user-images.githubusercontent.com/3171369/110837993-2e95b800-825f-11eb-96b4-0bfb085af6c4.png">

**Comment by krayon007** [comment]
What server version are you running? And which CentOS version are you running?

**Comment by Ylianst** [comment]
Are you using any MeshCentral plugin's?

What do you see in the red area?

![image](https://user-images.githubusercontent.com/1319013/110845496-8cc29b00-825f-11eb-825c-7f2980d95660.png)

If you click "Agent Action" and "Upload the Recovery Core", do commands start working?

- Thanks.

**Comment by gcstang** [comment]
@Ylianst nothing shows in the red area you have circled
- performed click on Agent Action and Upload Recovery Core
- nothing happened and info still doesn't produce anything

@krayon007 
- meshcentral is 0.7.85
- CentOS version 7
- Raspberry Pi version 9

I'm running this in a Docker container 

**Configuration (domain changed to generic)**:
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "my.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "_agentPong": 300,
    "_tlsOffload": false,
    "_selfUpdate": false,
    "_allowFraming": false,
    "_webRTC": false
  },
  "domains": {
    "": {
    "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "newAccounts": false,
    "_userNameIsEmail": true,
    "certUrl": "https://my.domain.com/",
    "agentConfig": [ "webSocketMaskOverride=1" ]
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}

**Log from container (domain changed to generic)**:
# docker logs -f meshcentral
Installing archiver@4.0.2...
Installing otplib@10.2.3...
Installing archiver@4.0.2...
MeshCentral HTTP redirection server running on port 80.
Generating certificates, may take a few minutes...
Generating root certificate...
Generating HTTPS certificate...
Generating MeshAgent certificate...
Generating Intel AMT MPS certificate...
MeshCentral v0.7.85, Hybrid (LAN + WAN) mode, Production mode.
Loaded web certificate from "https://my.domain.com/", host: "my.domain.com"
  SHA384 cert hash: 0b4eeb8e4733e66edbea7485e9ac5672bba3910e0b89c78e006da3a1ec9ae6924172eecd8f411e18426dd6ab2c8bea67
MeshCentral Intel(R) AMT server running on my.domain.com:4433.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on my.domain.com:443.

**Log from RaspberryPi Agent**:
# cat /usr/local/mesh_services/meshagent/meshagent.log
[2021-03-11 08:44:24 PM] Info: No certificate was found in db

**Comment by krayon007** [comment]
Interesting. If you don't see anything in that red circle, it means your agent isn't communicating with the server. I just tested with a clean install on CentOS 7 using v0.7.85. @Ylianst can probably help by taking a look at your configuration.

![centos](https://user-images.githubusercontent.com/29240564/110857663-fc3f8700-826d-11eb-8ef5-f89ed7b2e4e6.png)

**Comment by gcstang** [comment]
@krayon007 is there any debug I can get from the agent side?

**Comment by krayon007** [comment]
The easiest way is to run the agent in console mode... To do that, first stop the agent service: 
`sudo systemctl stop meshagent`
then navigate to where the agent is installed, usually at `/usr/local/mesh_services/meshagent`
and run the agent directly:
`sudo ./meshagent`
it should output everything it's doing to stdout.

**Comment by gcstang** [comment]
@krayon007 
All I see is this
root@raspberrypi:/usr/local/mesh_services/meshagent# ./meshagent
Connecting to: wss://my.domain.com:443/agent.ashx
Connected.

**Comment by krayon007** [comment]
Sounds like what is happening is the server is dropping or ignoring the connection, or something like that... You don't have any logs on the server side that look peculiar?

**Comment by gcstang** [comment]
well I stopped using traefik and it's working not sure why, I need this to work outside my LAN also though so I'll still need help from @Ylianst

**Comment by Ylianst** [comment]
If your using a reverse proxy, I would have expected:

```
"tlsOffload": true
```

Unless you are re-doing TLS from the reverse-proxy to MeshCentral?

**Comment by gcstang** [comment]
@Ylianst 
I have a DNS CNAME entry in cloudflare for my domain
That domain comes into my network via a router that has 80/443 open to Traefik only
Traefik then forwards HTTPS to my Docker container 
I tried "tlsOffload": true but it won't even come up at all with that setting, when I disable it then the site comes up.

I start my Docker container with this now (to show more info): node node_modules/meshcentral --debug

When I add the agent on my Pi I see this in the server logs:

COOKIE: ERR: Bad AESGCM cookie due to exception: Error: Unsupported state or unable to authenticate data
COOKIE: ERR: Bad AESSHA cookie due to exception: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

I stopped the Agent on my Pi then run manually and I can see 
(Agent):
./meshagent
Connecting to: wss://mc.collins-tech.com:443/agent.ashx
Connected.

(Server):
HTTPHEADERS: GET /agent.ashx/.websocket { host: 'my.domain.com',
  'user-agent': 'Go-http-client/1.1',
  'accept-encoding': 'gzip',
  'cdn-loop': 'cloudflare',
  'cf-connecting-ip': '70.x.x.x',
  'cf-ipcountry': 'US',
  'cf-ray': '62e88f9e1d0a3661-LAX',
  'cf-request-id': '08c53816cd00003661a20b0000000001',
  'cf-visitor': '{"scheme":"https"}',
  connection: 'Upgrade',
  'sec-websocket-key': 'J9Q2I69g21kD3M/7DEtI6A==',
  'sec-websocket-version': '13',
  upgrade: 'websocket',
  'x-forwarded-for': '70.x.x.x',
  'x-forwarded-host': 'my.domain.com',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik',
  'x-real-ip': '172.69.34.245' }
WEBREQUEST: (172.20.0.8) /agent.ashx/.websocket
AGENT: New agent at 172.20.0.8:53556
AGENT: Verified agent connection to gRzaQhGVkWaZYoZhz14TDovpeut@mamoUTUTzQJHV@eEG53388u79WELsQ@0heHF (172.20.0.8:53556).
DISPATCH: DispatchEvent [ 'node//gRzaQhGVkWaZYoZhz14TDovpeut@mamoUTUTzQJHV@eEG53388u79WELsQ@0heHF',
  '*',
  'mesh//gbqNvlo3XoCANhaf8j4n0giF7u6x7oAZ7cy6qoJBuppNAvO8M0CLBT9laIzBrM@I' ]
AGENT: Updating core linux-noamt

**Comment by Ylianst** [comment]
Ok. Lots going on here. Do you want to have all agent traffic go thru CloudFlare? If not, you can add these two lines two the settings section of the config.json:

```
    "AgentPort": 889,
    "AgentAliasPort": 443,
    "AgentAliasDNS": "agents.mesh.meshcentral.com",
    "AgentPortTls": true,
```

This will start a different webserver port on MeshCentral that only agents can connect to. You can play with the settings so that agents will connect to your server directly instead of CloudFlare. You will need a DNS name that points to your server.

If you want to go thru CloudFlare with all agent connections some added debugging will be required. The way above may also save you in costs.

**Comment by gcstang** [comment]
thank you, I'd rather it all go through cloudflare, so the only open ports
are to the reverse proxy.

tell me what you need for debug and I'll get it to you.

**Comment by Ylianst** [comment]
So, you have both CloudFlare and a reverse proxy? The DNS name you are using in "certurl" is the name pointing to CloudFlare? (if not, it should)

**Comment by gcstang** [comment]
correct I use cloudflare free for dns and a reverse proxy that send
requests for the dns to the correct configuration.

I'm willing to jump on zoom with you if you think it will help.

**Comment by gcstang** [comment]
Added (controlChannelDebug=true)key=value on agent side and I see

./meshagent
Generating Certificate...
Attempting to connect to Server...
Connecting to: wss://my.domain.com:443/agent.ashx
Control Channel Connection Established [14]...
Sending Authentication Data...
ProcessCommand(1)...
ProcessCommand(2)...
Connected.
ProcessCommand(4)...
Authentication Complete...
ProcessCommand(12)...
BinaryCommand(12, 0)...
ProcessCommand(11)...
BinaryCommand(11, 0)...
Control Channel Disconnected [14]...
Mesh Server Connection Error [14]
Attempting to connect to Server...
Connecting to: wss://my.domain.com:443/agent.ashx
Control Channel Connection Established [13]...
TLS Server Cert matches Mesh Server Cert [13]...
Sending Authentication Data...
Connected.
ProcessCommand(1)...
ProcessCommand(4)...
Authentication Complete...
ProcessCommand(12)...
BinaryCommand(12, 0)...
ProcessCommand(11)...
BinaryCommand(11, 0)...

**Comment by gcstang** [comment]
I tried disabling the cloudflare proxy but still no luck, the initial connection happens because the device with the agent shows up but no Console, etc... works.

**Comment by Ylianst** [comment]
Try adding the following two lines in the settings section of config.json:

```
    "CookieIpCheck": false,
    "CookieEncoding": "hex",
```

Hopefully that will fix the bad cookie issue above.

**Comment by gcstang** [comment]
@Ylianst I see upon installing the agent

HTTPHEADERS: GET /meshagents?script=1 { host: '<my domain redacted>.com',
  'user-agent': 'Wget/1.18 (linux-gnueabihf)',
  accept: '*/*',
  'accept-encoding': 'identity',
  'x-forwarded-for': '<my external ip redacted>',
  'x-forwarded-host': '<my domain redacted>.com',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik',
  'x-real-ip': '<my external ip redacted>' }
WEBREQUEST: (172.20.0.8) /meshagents?script=1
HTTPHEADERS: GET /meshagents?id=25 { host: '<my domain redacted>.com',
  'user-agent': 'Wget/1.18 (linux-gnueabihf)',
  accept: '*/*',
  'accept-encoding': 'identity',
  'x-forwarded-for': '<my external ip redacted>',
  'x-forwarded-host': '<my domain redacted>.com',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik',
  'x-real-ip': '<my external ip redacted>' }
WEBREQUEST: (172.20.0.8) /meshagents?id=25
HTTPHEADERS: GET /meshsettings?id=smREz95ySOwxauSXCQCTfQuwsLqnAWAwdVz0$ucj825lwjMELK793KKMkNxqAJA2 { host: '<my domain redacted>.com',
  'user-agent': 'Wget/1.18 (linux-gnueabihf)',
  accept: '*/*',
  'accept-encoding': 'identity',
  'x-forwarded-for': '<my external ip redacted>',
  'x-forwarded-host': '<my domain redacted>.com',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik',
  'x-real-ip': '<my external ip redacted>' }
WEBREQUEST: (172.20.0.8) /meshsettings?id=smREz95ySOwxauSXCQCTfQuwsLqnAWAwdVz0$ucj825lwjMELK793KKMkNxqAJA2
COOKIE: ERR: Bad AESGCM cookie due to exception: Error: Invalid IV length
COOKIE: ERR: Bad AESSHA cookie due to exception: Error: Invalid IV length

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
