### ISSUE TITLE
is there a possibility to have Wake on Wifi enabled in mesh ?

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#238]
checking if there is a possibility to have Wake on Wifi enabled if system is in Sleep, Hibernate or CS

**Comment by Ylianst** [comment]
Hi. If you have a specific technology in mind to do this, I will take a look at it. If you have a wireless adapter that supports the "magic packet" for wake, it should work already but you need to make sure to enable this feature in your drivers. Also, for wake-on-lan or wake-on-wlan, you need another computer on that network that is powered on. MeshCentral will send a signal to other computers on your network to send the magic wake packet. If all your computers are off, this will not work.

**Comment by Arun0711** [comment]
Got it Ylian,

Will check the feasibility for using the Wake-on-Wlan

Regards
arun

**Comment by Ylianst** [comment]
Ok. I will close this, if you have a more specific request, please open a new issue.
