### ISSUE TITLE
Request: +\- Button to collapse\expand all device groups

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#2384]
thx!

**Comment by Ylianst** [comment]
Right click on collapse/expand button.

![image](https://user-images.githubusercontent.com/1319013/110876958-60be0e80-828d-11eb-9e3e-88d2f9547f89.png)

**Comment by southeasterntech** [comment]
Wow!  Who knew that was there?  You guys rock! Thanks, please close

**Comment by Ylianst** [comment]
Ok. Next time, please close yourself.

**Comment by southeasterntech** [comment]
apologies, didn't know I could close it....
