### ISSUE TITLE
Feature Request: Ability to filter the Description field

### ISSUE THREAD

**Issue by mrflaunted** [Ylianst/MeshCentral#2385]
Hello,

Currently the only field that can be filtered is the "device name" field. However, the meshcmd.exe allows for descriptions to be added when importing devices. We currently use this to add full username or login name during the automated import.

For now, we add the username to the device name manually but because of the human interaction there can be misspellings inconsistencies in formatting. 

Would it be possible to include that field in the filter\search next to the group actions button?

https://imgur.com/c7kfmEj

**Comment by Ylianst** [comment]
Ok, starting with MeshCentral v0.7.87 you can type "desc:<string>" in the filter box to filter on device description. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/111003667-72122400-833c-11eb-9549-f537d9eee850.png)

**Comment by mrflaunted** [comment]
Tank you,, this works to a degree. Say the Description contained the following:

John Smith (Domain\userid)

If I type, desc: John the result is returned, but if I type in desc:user I'd or desc:Smith it is not.

**Comment by Ylianst** [comment]
It's a problem with upper/lowercase. Fixed it, will be in v0.7.88.

**Comment by Ylianst** [comment]
MeshCentral v0.7.88 was published. Please close if it works.

**Comment by mrflaunted** [comment]
Working like a charm now, thank you.

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back and closing the issue.
