### ISSUE TITLE
There's no text (when typing) visible in the Terminal.

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshCentral#2386]
After updating to version 7.86 there's no text visible, you can type any command with enter and it executes or shows the output.
This only occurs on Linux machines - we also have MS Windows but if I type any command in the Terminal it just shows text.

**Comment by petervanv** [comment]
confirming that, same here, also meshcentral 0.7.86 In root shell and log shell

**Comment by Ylianst** [comment]
Oh dear. Your right, thanks for reporting this.

**Comment by Ylianst** [comment]
Ok, I know what is going on. Working on a fix now.

**Comment by Ylianst** [comment]
Should have a fix in 30 minutes.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.87 with a fix for this. Let me know if it works.

**Comment by petervanv** [comment]
fixed at my terminals, super quick thx

**Comment by LPJon** [comment]
I'm having issues with the windows command terminal. I type a command and only about half the output is displayed. A simple "dir" command will only show about the first line of output. Pressing "enter" several times seem to produce the rest of the output.

**Comment by Ylianst** [comment]
I am going to close this one since this exact issue has been fixed.

@LPJon I think your reporting something else. If you can file a new issue and provide data to replicate this, that would be great.
