### ISSUE TITLE
Limit the number of simultaneous desktop connections a user can have

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#2389]
Hi,

It would be nice to have an option in the JSON config to limit the amount of simultaneous connections per user. We traced an issue with the bandwidth at our meshcentral site down to one of our users opening *every* computer in the desktop preview mode simultaneously.

Aside from vigorous education on that user, it would be nice to prevent that problem to begin with.

**Comment by Ylianst** [comment]
Good request. There are [various limits you can configure](https://github.com/Ylianst/MeshCentral/blob/ca5a1a7d7bbfb44cd630a81f644c397c7dea592d/meshcentral-config-schema.json#L398), but not that one. I can understand why someone would open all the screens, there is a multi-screen mode in MeshCentarl (red circle on the upper right) and makes that super easy.

![image](https://user-images.githubusercontent.com/1319013/111096945-d5977f80-84fd-11eb-8742-428ababdd28e.png)

**Comment by Mfinadmin** [comment]
Can you enable an option for deactivate the multi screen mode through config.js

**Comment by si458** [comment]
this is now partly possible
you set `MaxSingleUserSessions: 3` under `limits` under `domains` in config.json
![image](https://github.com/Ylianst/MeshCentral/assets/765314/6ce420bf-7a57-4c99-b4c0-060c15e326f9)
