### ISSUE TITLE
Desktops preview of portrait display has distorted aspect ratio

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#2391]
Hello,

This regards 0.5.51 so I apologize if it's already been addressed in newer versions.  But I did search the open and closed issues and didn't see this exact item.

When looking at the Desktops view of devices I can click in the black Desktop area and get a preview of the desktop.  This is a very nice feature for checking many systems at a glance on one screen.  However, for Ubuntu 18.04 linux systems (have not checked Windows 10) if the display is portrait then the aspect ratio is distorted to fill the portrait Desktop preview area.

Thanks!

![mesh](https://user-images.githubusercontent.com/12804882/111195170-9a3e9480-8581-11eb-805c-62ffdbd2dc03.jpg)

**Comment by Ylianst** [comment]
This has not been addressed in newer versions. I need a way to display screens so the aspect ratio is correct when there are many screens being displayed. A bunch of photo sites have a good system to align pictures of different sizes and I need to do the same here.

**Comment by Ylianst** [comment]
Fixed. This is in MeshCentral v0.7.90 that was just published. Let me know if that works.

![MC2-MultiDesktopVariableWidth](https://user-images.githubusercontent.com/1319013/111730864-84ee9200-882f-11eb-9ed1-92a790c6038b.png)

**Comment by Ylianst** [comment]
No response from original poster so closing this.

**Comment by edlins** [comment]
Confirmed fixed.  Sorry for the delay, and thanks for the quick turnaround!
