### ISSUE TITLE
[Feature request] S3 storage as backup destination

### ISSUE THREAD

**Issue by cristianadrielbraun** [Ylianst/MeshCentral#2392]
Is this easy to implement? 
I'm currently using webdav to backup my server to a Nextcloud instance.
Originally, this issue was going to be about a bug, since the backups are being uploaded with 0kb.

But since I'm not sure if maybe is a misconfiguration on my Nextcloud instance, I decided to convert an issue to an opportunity.

It wuould be nice if we can use S3, or S3 compatible storage (I use Wasabi, for example) as a destination for the autobackup.

Thanks!

**Comment by Ylianst** [comment]
Good request. I have never used S3, but given how popular it is, I really should.

**Comment by routerino** [comment]
Hi Ylianst, I would suggest not implementing a direct S3 backup solution. It's gonna fragment your time too much (IMO).

S3 backup solutions exist already. [Rclone](https://rclone.org/) is a really good example. As long as your data exists, somewhere, there's a dozen solutions to get that data into cloud storage. No need to reinvent the wheel.

Rather than redevelop a cloud native backup, I'd suggest improving the documentation to include options to backup to cloud. Rclone is a great option, it supports basically ever cloud platform that currently exists.

**Comment by yomono** [comment]
> Hi Ylianst, I would suggest not implementing a direct S3 backup solution. It's gonna fragment your time too much (IMO).
> 
> S3 backup solutions exist already. [Rclone](https://rclone.org/) is a really good example. As long as your data exists, somewhere, there's a dozen solutions to get that data into cloud storage. No need to reinvent the wheel.
> 
> Rather than redevelop a cloud native backup, I'd suggest improving the documentation to include options to backup to cloud. Rclone is a great option, it supports basically every cloud platform that currently exists.

Despite being me who opened this issue, I think my friend here is right.
I have never thought about it, but yes, with tools like rclone around (which are REALLY simple to use. For real, just one line and it works), maybe is too much time wasted that you could use to MeshCentral itself.

Maybe (just to not throw away the idea completely) maybe you can just add a new "destination" being rclone itself, and there we just can complete the native parameters rclone needs. I mean this just to have "some" integration between them.

But yeah, @routerino is right. As I already commented in another issue (don't remember which one), spending too much time on secondary features (like external backups) is less time spended on the real thing here: The remote control solution

**Comment by Ylianst** [comment]
Thank you so the thinking and feedback. I am really swamped with requests so I do appreciated the thinking. Requests like this are many hours of work and so, I can only do 2 to 4 fixes or requests per days on a good day.

One argument for offering the direct backup is that the database is backed up along with "meshcentral-data". If you guys have ways of doing S3 backup of both file folder and database, I would be interested... at least for documentation to others.

**Comment by si458** [comment]
is this still a required feature? as i was just looking to add it for others :)
