### ISSUE TITLE
Select-All in single Group

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#2393]
Hey guys,

Long time, no chat... which I guess means you've  got a great project ;)

Quick question tho, we have a ton of systems now registered in our portal... but it dawned on me recently, there doesn't seem to be a way to do select all for a single group. Am I missing something? I couldn't find anything while searching either.

-Matt

**Comment by yomono** [comment]
Right click on the Group name -> Select all 😄

**Comment by matt-cylanda** [comment]
Wow *Face-Palm*... umm... ya, that'll make things a little easier for me lol
