### ISSUE TITLE
Profile image in user consent.

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2395]
Dear Mesh central Team,

I am a new user so i don't know whether its a good request.

If possible please enable a provision for uploading profile image of each user through "**My account**" option and display the same image in user **consent** dialog box.

**Comment by Ylianst** [comment]
Ha, that would be a fun feature.

**Comment by Ylianst** [comment]
For fun, I added account picture support to just published MeshCentral v0.7.91. Nothing is done with these pictures yet and that will take time. Below, myself on the left and Bryan's (Krayon007) on the right.

![MC2-AccountPictures](https://user-images.githubusercontent.com/1319013/111846740-ae0d3200-88c4-11eb-94c9-d65c08d29e2e.png)

**Comment by vitko-bg** [comment]
Cool. Will test it ;)

**Comment by mjpcomp** [comment]
There is a use case that just came up:

Some of our techs don't lock systems, so, we were thinking - upon a desktop connection session, the wallpaper will get set to the user's image 😛 

On a realistic note - eventually it would be nice to see the image implemented in the chat session (so the end user can see who they are chatting with), or, even a popup display option to briefly show the user's image (like the notification bar)

**Comment by Ylianst** [comment]
After adding support on the mobile app, adding it to the chat session will be the next one, since it's web based. Adding it to user consent will be more difficult, Bryan will have to take a look at it since it will be changes to the consent dialog and that is operating system specific.

**Comment by Mfinadmin** [comment]
@Ylianst - Thanks for a quick implementation of account picture.

I understand the concern regarding the consent  dialog box modification.

Request you to check the feasibility and if possible Please implement the same in upcoming versions.

**Comment by VINISHVV** [comment]
Wow nice feature !!!!

I am awaiting the upcoming features like profile image in chat, mobile app, user consent etc....

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.92 with account picture support in the mobile web site and messenger. Feedback appreciated.

![MC2-AccountPicturesMobile](https://user-images.githubusercontent.com/1319013/111923351-f448c980-8a5b-11eb-8df3-0d93f7f918d9.png)

![MC2-AccountPicturesMessenger](https://user-images.githubusercontent.com/1319013/111923353-f743ba00-8a5b-11eb-923f-117a0d1592bb.png)

**Comment by Mfinadmin** [comment]
Wow !!!!
Awesome features, Big thanks to all teams behind this projects.

**Comment by Ylianst** [comment]
Switching issue to Bryan who would need to investigate placing a picture on the consent dialog.

**Comment by VINISHVV** [comment]
Thanks Ylian & Bryan for implementing the account image support in Latest version of Mesh central Assistant.

**Comment by Mfinadmin** [comment]
Seems The feature is available in Meshagent's latest version.
Thanks, @Ylianst @krayon007 for your efforts.
