### ISSUE TITLE
Device notification - Replace \n with new line.

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2396]
@Ylianst 
I have tried to sent below message through device notification option.

____________________________________________________________________________________________
Dear Sir,

We are facing some technical issues in CRM application. This will resolve by 6:30 PM.

Regards
Helpdesk Team
____________________________________________________________________________________________

But the message shows like .
Dear Sir,**\n\n**We are facing some technical issues in CRM application. This will resolve by 6:30 PM.**\n\n**Regards\nHelpdesk Team
____________________________________________________________________________________________

If possible please do the needful to replace **\n** with New line

**Comment by Ylianst** [comment]
Can you provide a screen shot? I need to know where this message is displayed. Thanks.

**Comment by mjpcomp** [comment]
@Ylianst  - I noticed the same thing....

![image](https://user-images.githubusercontent.com/7637082/111537003-2be80680-8728-11eb-92eb-c25dbfa87a57.png)

**Comment by mjpcomp** [comment]
Oh, and sorry, to add - the Yes/No buttons - if you have  to fix the messaging code, can that Yes/No be changed to just an Ok? Or are there plans to be able to receive a response back in the Web GUI so that if someone responds with No, we'll see (e.g. if the message is "Is it okay to shutdown?")

**Comment by Ylianst** [comment]
Fixed this, will be in MeshCentral v0.7.91. Once published, let me know if it works.

**Comment by VINISHVV** [comment]
**Wow !!! Just updated MeshCentral v0.7.91 and it works perfectly.**
