### ISSUE TITLE
mobile option missing

### ISSUE THREAD

**Issue by gibbc** [Ylianst/MeshCentral#2397]
I am using 0.7.89 but when I try and add a device I do not have a mobile device option 

i did see it before but then on 1 update, it was gone.

this was an in-place upgrade as i been running the latest.

Is this a bug or did i miss something?

**Comment by Ylianst** [comment]
The "mobile" option is only available in Hybrid or WAN modes. If you have `"lanonly": true` in the settings section of your config.json, the mobile option will not show up. Let me know if that is the problem.

**Comment by gibbc** [comment]
yes this was the problem but even after i change it still will not show here my config

 ```
 "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a mo>
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_cert": "myserver.mydomain.com",
    "_WANonly": True,
    "_LANonly": false,
    "_sessionKey": "REMOVED!",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },

```

**Comment by Ylianst** [comment]
Oh, I see. Your server must have a DNS name for the mobile application to connect to. Since you did not specify one, your server is still in LAN mode. Remove the _ for the "cert" value and specify the DNS name that the mobile agent will use to connect to your server. That should fix it.

```
"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
 "__comment1__": "This is a simple configuration file, all values and sections that>
 "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a mo>
 "settings": {
   "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
   "cert": "myserver.mydomain.com",    <------------
   "_WANonly": True,
   "_LANonly": false,
   "_sessionKey": "REMOVED!",
   "_port": 443,
   "_aliasPort": 443,
   "_redirPort": 80,
   "_redirAliasPort": 80
 },
```

**Comment by yomono** [comment]
Not related but just a comment: if the key starts with a _, it's disabled. It's not being read by meshcentral, no mather the value

**Comment by Ylianst** [comment]
No response so, closing. Please re-open if needed.
