### ISSUE TITLE
Feature Request: Shortened URL Generator for adding an agent

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#2398]
It would be nice to have an internal generator for a group install URL. IE: there is a button on the add agent popup that says "generate short link", and then the link could be "https://contosso.com/install/GAde" (or some other randomly generated 4 character word). This link could sniff the user agent, and download the appropriate binary (or provide the install shell script if identified as wget/curl).

Would be a nice to have in situations where you are setting up a new computer without clipboard access, to have a nice URL you can just type in manually. Alternatively, it could provide an easy to share-over-the-phone link for one-time access.

**Comment by yomono** [comment]
I know this is not the answer you were expecting, but you could just generate a invite link with unlimited time, and make your own short link pointing to that generated address.
You can even serve your own short link generator server, so you can customize like you want

**Comment by Ylianst** [comment]
In the domain section of the config.json, add this line:

```
"agentInviteCodes": true
```

Restart the server and click on a device group. You should see an option to create an invitation code for that device group.

![image](https://user-images.githubusercontent.com/1319013/111595374-4e5e3c00-8789-11eb-98db-2de9a8b664a8.png)

Once you go to the invitation link, you can enter the code.

![image](https://user-images.githubusercontent.com/1319013/111595481-65049300-8789-11eb-9960-3d3ac9b929d6.png)

The install page will offer all agents, but will favor the agent based on your browser's user agent.

![image](https://user-images.githubusercontent.com/1319013/111595495-6afa7400-8789-11eb-8c88-de2c2e1cd403.png)

Let me know if that works.

**Comment by drnikcuk** [comment]
Didn't know about this feature, just enabled and tested and it works great.

Love it.

**Comment by routerino** [comment]
Cheers Ylianst. The amount of times I think, "this would be nice to have", and it's just there ready to use is fantastic. I should read completely through the [config schema](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) before I bring up anything else :).

**Comment by Ylianst** [comment]
No worries. These requests also help the community that searches thru GitHub issues.
