### ISSUE TITLE
issue with user upload in bulk

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2399]
@Ylianst 

I have noticed that user creation using file upload ( Batch create many user) having some issues, If we mention the **user name**  in CAPITAL Letter then all users will create in Meshcentral without any error, and its shows in user list. Also we can assign the user groups and devices/ user consent etc.... 

But if we try to Login such users,  Meshcentral will not allow the users to access the web portal. It always shows message **Invalid credentials** **(Tried reset option too but its failed ).** 

I have uploaded the below mentioned data in  **.json** format for your reference.  

```
[
{"user":"MF3766","pass":"12345","email":"ithariraj@mydomain.com","resetNextLogin":"true"},
{"user":"MF19127","pass":"12345","email":"itsathar@mydomain.com","resetNextLogin":"true"},
{"user":"MF17246","pass":"12345","email":"itdeepakkumar@mydomain.com","resetNextLogin":"true"},
{"user":"MF44057","pass":"12345","email":"itsreenathvs@mydomain.com","resetNextLogin":"true"},
{"user":"MF37692","pass":"12345","email":"ittinujohn@mydomain.com","resetNextLogin":"true"},
{"user":"MF14446","pass":"12345","email":"itsandeep@mydomain.com","resetNextLogin":"true"},
{"user":"MF38027","pass":"12345","email":"itlibin@mydomain.com","resetNextLogin":"true"},
{"user":"MF20780","pass":"12345","email":"itrakeshkp@mydomain.com","resetNextLogin":"true"},
{"user":"MF01457","pass":"12345","email":"itstephen@mydomain.com","resetNextLogin":"true"},
{"user":"MF18836","pass":"12345","email":"itsaneeshnm@mydomain.com","resetNextLogin":"true"},
{"user":"MF38002","pass":"12345","email":"itansonalex@mydomain.com","resetNextLogin":"true"},
{"user":"MF48536","pass":"12345","email":"itmaneeshpm@mydomain.com","resetNextLogin":"true"},
{"user":"MF17244","pass":"12345","email":"itprathish@mydomain.com","resetNextLogin":"true"},
{"user":"MF40326","pass":"12345","email":"itsajeesh@mydomain.com","resetNextLogin":"true"},
{"user":"MF35878","pass":"12345","email":"itabhilash@mydomain.com","resetNextLogin":"true"},
{"user":"MF45016","pass":"12345","email":"itjohn@mydomain.com","resetNextLogin":"true"},
{"user":"MF43160","pass":"12345","email":"itangel@mydomain.com","resetNextLogin":"true"}
]
```

If i use the **user** name in small letter then This error will no more appear. All users can access the Portal without any issues.

```
[
{"user":"mf43160","pass":"12345","email":"itangel@mydomain.com","resetNextLogin":"true"}
]
```

If possible please fix this issue and also enable one more option for upload /insert "**Real Name**" through Batch create many user options.

**Comment by Ylianst** [comment]
Good point. User identifiers in MeshCentral are always lowercase. I will make sure to lowercase the identifier. Fixing this now for the next release.

**Comment by Ylianst** [comment]
Ok, fix will be in MeshCentral v0.7.90. Also, I added "realname" support, so you can add:

```
[
{"user":"mf43160","pass":"12345","email":"itangel@mydomain.com","resetNextLogin":"true","realname":"Robert"}
]
```

Once published, let me know if it works.

**Comment by Ylianst** [comment]
MeshCentral v0.7.90 has been published.

**Comment by VINISHVV** [comment]
Wow !!! Just updated MeshCentral v0.7.90 and it works perfectly.
