### ISSUE TITLE
Disadvantages when using from mobile

### ISSUE THREAD

**Issue by dagors** [Ylianst/MeshCentral#24]
When using meshcentral from an Android mobile the connection works well but as it is necessary to write in a box or text box the mobile keyboard does not unfold and it is not possible to right click to display menu.

**Comment by jsastriawan** [comment]
I believe you are referring to MeshCentral 1 which is based on .Net. This repository is related to MeshCentral 2.

**Comment by dagors** [comment]
It is meshcentral 2, maybe it does not explain me well these problems occur when I login to meshcentral 2 from my android device to control pc's windows.

**Comment by Ylianst** [comment]
The mobile web site of MeshCentral2 does not currently support any user input (keys or mouse). You can only view the remote desktop but not control it. I need to work on some way to fix this in the future, but it's difficult to make it usable on small displays. Right now, you have to switch to the desktop version of the web site for remote input.

**Comment by amccre** [comment]
Is there any way to force the keyboard to popup on an iPhone from the meshcentral side? There is no native way to force the keyboard open on the iPhone from the iPhone side.  The mouse works fine, but if there are key presses needed, there is no way to cause the keyboard to pop up.  Possibly adding a "Show Mobile Device Keyboard" checkbox that could be toggled on or off near the input check box?  Also, maybe a button for right click.  Other remote session apps I have used will right click when holding a click for a few seconds.  MeshCentral2 works quite well in desktop site mode on the iPhone. There is no getting away from zooming and scrolling, but today's mobile phones do that quite well.   And having the ability to correct a problem while on the go is great!

**Comment by Ylianst** [comment]
There is no way right now to pop-up the keyboard on the mobile web site. However, feel free to open a new feature request for this if it would be useful. I will close this issue since it's too vague. The mobile web site does have much less features, but feel free to request some if needed.

**Comment by amccre** [comment]
Just yesterday I found out that the Puffin browser has a keyboard pop function. It works ok with MeshCentral on mobile. Right click is a little complicated, but possible with onscreen keyboard in Windows.
