### ISSUE TITLE
Feature Request: Minimize MeshCentral Router to System Tray

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#240]
I find myself using MeshCentral Router rather frequently but when I'm cleaning up my desktop of windows I always accidentally close it by mistake. Would be great to be able to minimize it to the system tray!

**Comment by Ylianst** [comment]
Good idea, will work on it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-a with a new version of MeshCentral Router. You can now run it with "-tray" to place it on the system tray. Let me know if it works for you.

**Comment by MatinatorX** [comment]
Thanks, that's awesome! What are the chances we'll ever see the -all and -tray functions accessible from the GUI?

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-e with updated MeshCentral Router with new settings dialog for -all and -tray.

![MC2-MeshRouterTray](https://user-images.githubusercontent.com/1319013/58346846-ff575200-7e10-11e9-90b2-b9c3a4a2a2a1.png)

**Comment by Ylianst** [comment]
FYI. Published MeshCentral v0.3.5-f with bug fixes to MeshCentral Router.

**Comment by Ylianst** [comment]
Will close this one since I am pretty sure the system tray is working correctly. However, please re-open if needed.
