### ISSUE TITLE
Notes on mobile site

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2400]
Is there any way to add the 'Notes' feature to the mobile site?  I use the notes feature quite a bit and really miss not being able to access it on the mobile site. I currently have to switch the browser to desktop mode to be able to pull up the notes.

**Comment by Ylianst** [comment]
You got it. It's in just published MeshCentral v0.7.90. Let me know if that works.

![MC2-MobileNotes](https://user-images.githubusercontent.com/1319013/111730832-6f796800-882f-11eb-8337-10d92800972e.png)

**Comment by PathfinderNetworks** [comment]
Excellent!  Just updated and it works perfectly.  I see I can also edit and save the notes from the remote site as well. 
thank you!
