### ISSUE TITLE
Meshcentral Doesn't work with Teaming NIC

### ISSUE THREAD

**Issue by arduin0guru** [Ylianst/MeshCentral#2401]
windows 2019 server works good with only 1 NIC no Teaming . As soon I configured teaming for 2NIC to 1 ,Connection dropped. I ran mesh agent again and reconfigured connection. Its not connection to mesh central server. Anyone has same problem ??

**Comment by Ylianst** [comment]
The MeshAgent makes a fairly standard TCP/TLS/WebSocket connection to the MeshCentral server. If your browser can reach the server, I would imagine the MeshAgent would also be able to. I don't have any more information on this.

**Comment by Ylianst** [comment]
I am going to close this since I don't expect this to be a MeshCentral issue. NIC teaming is a layer below the TCP stack. Feel free to open a new issue if there is anything MeshCentral specific.
