### ISSUE TITLE
Possibility to add a temporary user feild

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#2402]
Hi , we are setting up some laptop for temporary smartworking ; for example a collegue for 2 days needs to stay home we give a spare laptop that when they come back in office they return , so we can give it to another collegue in case of necessity.
laptop are configured with standard user profile named admin so in case of problem i'm not able to immediately identify which is which.
is it possible to have a column to temporary write the real user ?
please see the image attached where you can see one of these laptop and raspberry that have the same user:
![immagine](https://user-images.githubusercontent.com/62424179/111815138-9ab99100-88db-11eb-97bb-546da700dba1.png)

**Comment by Ylianst** [comment]
At some point I need to work on column customization for that screen. For now, you can change the server side device name to add the current user of it. You can also change the description (but that will not show on that screen) or you can also add a tag to the device and select to sort devices by tags.

![image](https://user-images.githubusercontent.com/1319013/111822465-0e8a7800-88a1-11eb-9440-c7a4d291be5c.png)

In the future, being able to show the device description in the column view would be nice.

**Comment by tradexsrl** [comment]
hi , i have not the possibility to change the name as you can in tiny1...see the image attached
anyway adding a tag and then sort by group-tag i can see which is which...is not immediate but better than nothing :-)
![immagine](https://user-images.githubusercontent.com/62424179/111825265-9004f900-88e7-11eb-8f0c-de3920bf6b75.png)

**Comment by VINISHVV** [comment]
@tradexsrl - To edit the computer name, you need to disable the sync host name. 

The option available @  Device Group settings. 
![IMG_20210320_062825](https://user-images.githubusercontent.com/65057910/111854522-a5a90b80-8945-11eb-9f5f-420f57560d11.jpg)

**Comment by tradexsrl** [comment]
@VINISHVV thank's solved.

**Comment by VINISHVV** [comment]
@tradexsrl - welcome. Please close the issue.
