### ISSUE TITLE
[Bug] Profile image overlapping

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#2405]
Hey!
I know this is a VERY recent addition, but I just want to let you know a little issue with the profile image option.

When I set a new profile image, the previous one is not removed, so they overlap. If you set a big enough JPG, you will not notice it. But if you set a transparent PNG you will se how they overlap. Plus to this, the background turns black. Maybe is a PNG issue? Maybe MeshCentral don't know how to deal with the transparency?
Look, this is what I mean:
![image](https://user-images.githubusercontent.com/31445936/111885621-a7a3b680-89a7-11eb-8bc1-db1f53d0724b.png)

Here we can se the original profile image, a first one I used for testing, and a second one that was the one i really wanted.

It looks like modern art 😄  but I just want one picture 😆

**Comment by Ylianst** [comment]
Thanks for reporting this, I would have never tried it in my testing.

**Comment by Ylianst** [comment]
Fixed. Will be in MeshCentral v0.7.92.

**Comment by Ylianst** [comment]
MeshCentral v0.7.92 is published. Let me know if it works. If it does, please close this issue.

**Comment by yomono** [comment]
it... sort of works:

![image](https://user-images.githubusercontent.com/31445936/111925654-8797f400-8a88-11eb-9140-59ceedabd83a.png)

It does delete the previous ones, but with transparency it still adding a black background.

Nevermind, it not that important, I will close this issue since I dont think this topic deserves a lot of time from you: I will just use jpg images with backgrounds!
But, in general, the images are NOT overlapping anymore so.. Issue closed!
