### ISSUE TITLE
Scroll down options  Missing in My user group ( ?viewmode=50 )

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2406]
@Ylianst 
The scroll down button is missing in user Group options. Please add the same in upcoming versions.

![image](https://user-images.githubusercontent.com/65057910/111895575-9a370c80-8a39-11eb-8431-48adb38460bb.png)

**Comment by Ylianst** [comment]
Your right. I will add this.

**Comment by Ylianst** [comment]
Fixed it. It will be in MeshCentral v0.7.92.

![image](https://user-images.githubusercontent.com/1319013/111900594-bebac680-89f0-11eb-9ab2-9c3b04cdb163.png)

**Comment by Mfinadmin** [comment]
Thanks @Ylianst  for quick resolution

**Comment by VINISHVV** [comment]
Thanks, it's working now.
