### ISSUE TITLE
Link to a node when using Azure AD

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2407]
Hello.
At the moment, MeshCentral version 0.7.89 is installed. Configured authorization via Azure AD.
We would like to enjoy sending links to specific PCs to our colleagues. We send links like this https://XXX.XXXXXX.XX/?viewmode=11&gotonode=XXXXXzoxy5NOqgUTyTL8RBAfPtDzO41yTab@dVyGKrre@qZg$x7Drs$POKxXXXXX

When an employee goes to the posting manually, he first logs in, he is redirected to the central page, and not by the link. He has to re-insert it into the browser. This is the first half of the problem.

If we indicate this link in our documentation on the Wiki, then each time you click on the link, it requests authorization without remembering the previous authorization.

Together, these problems form one big one, which does not allow the documentation to leave references to the management of specific computers.

But when authorizing using a local account, this problem is not observed. We get to the same node that we shared after authorization. Those. the issue is in preserving the redirect parameters after authorization in Azure AD. She always posts to the home screen.

**Comment by AntonAndreevichMoroz** [comment]
Judging by the description on the page https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow there is a state parameter that might help. You can send a referral link there and process it when responding.

**Comment by routerino** [comment]
I would say that adding platform specific features should not be a priority for meshcentral (arrogantly, I suppose, given that I'm not on the team). adding SAML compatibility is more than enough. Expecting platform specific features is a bit conceited.

SAML is a standard. Implementing Azure invite links is not.
