### ISSUE TITLE
Windows Desktops cursor and view a little off

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#2408]
Meshcentral installed on Ubuntu 18.04, with NginX reverse proxy
Connecting from my Windows 10 Pro Workstation, using Chrome

When I view a Windows desktop the bottom half of the 'Task bar' at bottom of screen doesn't show, and the cursor is always about have an icon above and slightly left of what is clicked on, for example in Windows Explorer (my Computer) I frequently click on the item below the one I intend to click on.

I do have very large resolution monitors on my workstation, 2 by 4K , windows sets them at 150%

**Comment by si458** [comment]
this is now fixed 
![Desktop-DESKTOP-SIMJAHR-2023-11-12-22-14](https://github.com/Ylianst/MeshCentral/assets/765314/69a8ec9e-6198-42c3-9259-6839ef9fc7f6)
