### ISSUE TITLE
Meshcentral Restarting Frequently - MC Version 0.7.92

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2409]
@Ylianst,

After updating the server to New version (0.7.92 ) i noticed that the Mesh central application is frequently restarting.

I am using latest version 0.7.92, with Mongo db in Windows server 2019.

Can you suggest how we resolve the issue.

**Error message**
____________________________________________________________________________________________________________________

--------- 22/3/2021, 10:17:22 am ---- 0.7.92 --------

C:\Meshcentral\node_modules\meshcentral\meshrelay.js:204
        if (obj.id.startsWith('meshmessenger/') && (obj.peer != null) && (obj.user != null) && (typeof obj.user.flags == 'number') && (obj.user.flags & 1)) {
                   ^

TypeError: Cannot read property 'startsWith' of undefined
    at Object.CreateMeshRelayEx.obj.sendPeerImage (C:\Meshcentral\node_modules\meshcentral\meshrelay.js:204:20)
    at C:\Meshcentral\node_modules\meshcentral\meshrelay.js:389:49
    at C:\Meshcentral\node_modules\meshcentral\meshrelay.js:657:90
    at FSReqCallback.wrapper [as oncomplete] (fs.js:638:5)

-------- 22/3/2021, 10:17:30 am ---- 0.7.92 --------

**Comment by Ylianst** [comment]
Working on it now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.93 with a fix for this. Let me know if it works.

**Comment by Mfinadmin** [comment]
Updated to latest version and now completed 1.30 hours.
Till now no such error found. @Ylianst Thanks for your fast rectification.

**Comment by Mfinadmin** [comment]
Closing the issue since its perfectly working.
