### ISSUE TITLE
What is the two-factor authentication ?

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#241]
Dear all:

I tried to install a new version 0.3.4-y of meshcentral today, with a pop-up prompt when I added a device group
"Unable to access a device until two-factor authentication is enabled. This is required for extra security. Go to the "My Account" tab and look at the "Account Security" section "
How to do that next step, thanks so much.

Best regards,
Billy Dudu

**Comment by Ylianst** [comment]
Hi. Two factor authentication is a way to increase the security of user login my using more than just a password. By default 2-factor authentication should not be required, but there is an option to require it on all accounts.

Can you attach the config.json for your server? Make sure to put "xxxx" for the server name and any secret or private data. I will debug this right away.

**Comment by Ylianst** [comment]
Note that to force 2-factor authentication, you need to set "force2factor" to true in "PasswordRequirements" in the domain section of config.json:

`"PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true }`

Can you check this? It should not be set if you don't want this.

**Comment by billydu1980** [comment]
Dear Ylianst: I see. The little problem has been solved. Thanks again.
