### ISSUE TITLE
Weird screen refresh issues in Teriminal with Server 2012 R2

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#2413]
Not sure how to describe the issue exactly so I am putting a link to a quick screen grab video I made of it. I cannot replicated this issue on Windows 10, and I have also restarted the agent on the Server 2012 R2 box. Sadly I only have one of these boxes, so I am not much help in the testing area other than the one I have. 

This happens with both powershell and command prompt

My meshserver is on 0.7.89 and my agent reports this information when I ask the version command

{
  "openssl": "1.1.1i",
  "duktape": "v2.3.0",
  "commitDate": "2021-02-07T23:26:53.000Z",
  "commitHash": "43c5f2d1b57a9f477d3afec13e2873ed19bfd573",
  "compileTime": "15:55:41, Feb  7 2021"
}

The first video is the problem occurring and the second video is it working as expected on the windows 10 machine. 

https://user-images.githubusercontent.com/51446227/112155091-58ce6a80-8bbb-11eb-8fa1-e8ddc93ef358.mp4

https://user-images.githubusercontent.com/51446227/112155103-5bc95b00-8bbb-11eb-9bfc-502bc7d78ac8.mp4

**Comment by krayon007** [comment]
That's a known limitation. Windows Server 2012 does not have native support for pseudo terminals, so it has to be faked with a console process and buffer scraping, but this has many drawbacks, one of which is problems such as what you describe. Newer versions of windows added support for pseudo terminals, with an API called ConPTY. The agent will detect platform support and use it if it is there. An easy way to tell if you have it, is to type `osinfo` in the console tab. It will either say ConPTY: Yes or No. For Windows 10, it was added with the Fall'2018 update. I can't remember which update it was added on Server 2016, but I know it's there for Server 2019.

**Comment by githubbiswb** [comment]
Thank you for the help, I searched for it and didn't see an issue but your explanation makes perfect sense. Thank you for all of your hard work!
