### ISSUE TITLE
meshctrl.js AddUserToDevice calls triggering strange behavior in desktop connections

### ISSUE THREAD

**Issue by mirumu** [Ylianst/MeshCentral#2415]
I've noticed some strange behavior in a production Meshcentral environment we're running on Linux. It's currently running release 0.6.70, but I did try the latest 0.7.x development release a few days ago which behaved the same way.

So if a user initiates a desktop connection to a node they have the permission for, and a "meshctrl.js AddUserToDevice" call is being performed on the command line against the same node and same user prior to the desktop connection completing it's initialization, the desktop connection will fail, and the websocket relay connection which was initiated remains open but appears to never to be used again. When in this state, the user interface in the node's Desktop tab updates the connection button to show "Connect" once again, but the status message beside the button varies. It can be left as either "Connected" or "Disconnected". Even if it says Connected however, the desktop display remains blank.

When clicking "Connect" again, the issue can happen multiple times in a row as long as meshctrl.js AddUserToDevice calls are being made against the node or if the permission update takes a while complete. By tracing websocket relay connections, I can see that each time it fails another fresh websocket relay connection is added causing them to build up. Eventually when the browser window is closed or the user navigates away, all the backed up relay connections are closed.

I can certainly understand why trying to edit a user's permissions for a node while they're connecting to it could cause this, but in this specific case the user already has access and their access is not being removed. I'm assuming the permissions are being torn down and rebuilt irrespective of whether this is required or not. 

Obviously I can try to work around this on our permissions automation by not trying to re-add permissions that a user has already been granted, but I thought it was worth raising as an issue here given the queuing up of websocket connections and how the desktop tab seems to get a bit confused as to whether it's connected or not.

Edit: In order to avoid adding access users already have I'd need to be able to retrieve the current list of users mapped to a device. Is there any meshctrl.js call that can return the list of users with access to a device? There is AddUserToDevice and RemoveUserFromDevice, but I can't see anything like ListDeviceUsers or an equivalent. I know this can be done at the device group level, but our permissions requirements are more fine-grained than that.

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back
