### ISSUE TITLE
My Account - ability to add user specific account special notes section.

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2418]
Hi MeshCentral team,

By any chance can a notes section be added to the My Account page? I ask this because I have multiple groups, and some of those groups I run on a enterprise proxy server environment and then others I run outside of that enterprise zone.

What I am trying to achieve in the "My Account" page, is the ability to dump some commands I might utilize time and time again, or special instructions I want to reference back to, or even website links that might have special how-tos I reference. 

I am trying to keep as much back and forth from systems to the site as possible, and if users had user only notes area that could keep 3Kb of notes, that should suffice for a decent amount of collected secured notes, plus prevent the departure from the site to fetch those notes. Also speeding up the time to get those notes which might turn into time savings if referenced a lot.

Thank you,
SomeGuru

**Comment by yomono** [comment]
I'm a little confused, but the My Account section already has the notes option:
![image](https://user-images.githubusercontent.com/31445936/112357451-4f71fa80-8cae-11eb-9787-3603da419091.png)

**Comment by Ylianst** [comment]
I have the same question.

**Comment by solrac901** [comment]
Hey there are using the product in Spanish cool.

**Comment by SomeGuru** [comment]
I must be missing something here... I don't have anything in my account page... I see notes for agent screens, but I want notes at a user panel level not at the agent installed. all I see are the following in my links under my account page.

![image](https://user-images.githubusercontent.com/48393851/112400754-3b39f780-8cc6-11eb-9657-b288cfdddd47.png)

**Comment by yomono** [comment]
> Hey there are using the product in Spanish cool.

Saludos desde Argentina! 😄

**Comment by Ylianst** [comment]
Just added personal notes to MeshCentral v0.7.96 that was just published. Let me know if that works.

![MC2-PersonalNotes](https://user-images.githubusercontent.com/1319013/112543419-f4eea200-8d72-11eb-80f0-876eea0a4b35.png)

**Comment by SomeGuru** [comment]
Confirmed, closing.
