### ISSUE TITLE
Autobackup in 0.3.4-y

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#242]
I saw the tweet from yesterday (the 20th) about the new Autobackup feature in 0.3.4-y. I updated my server this morning and wanted to check it out. 
But I'm not finding it.  The tweet mentioned that this feature is controlled by settings in config.json.  I'm looking at my config.json file and there are no entries at all related to autobackup.  Should these settings have been automatically added during the update to 0.3.4-y or do we need to manually add them?  If we need to manually add them where do I find documentation for it?

**Comment by Ylianst** [comment]
Hi. So, settings are not added to the config.json automatically and I still need to update documentation on this feature. Version 0.3.4-y should auto-backup every 24 hours in the "meshcentral-backup" folder. You can can a look here for [a sample config.json](https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json) or add this to the "settings" section of config.json:

```
    "AutoBackup": {
      "backupInvervalHours": 24,
      "keepLastDaysBackup": 10,
      "zippassword": "MyReallySecretPassword3"
}
```

Lastly, you can force an immediate backup by going to the "My Server" tab, the "Console" and type "autobackup". You should see the backup show up in "meshcentral-backup" folder.

Hope it helps,
Ylian

**Comment by PathfinderNetworks** [comment]
Thank you Ylian,
That worked.  Is there any way to modify the location of where the backups are stored?  Such as if we wanted the backup location to be on a share accessed via UNC path or maybe a USB drive?  If that's not currently possible can it be added as a feature request for down the road?  I run my MeshCentral servers as VMs and would prefer the backups to be stored somewhere outside the VM itself. Certainly I can use other tools to move the files- but it would be nice if I could just have the autobackup function do it directly.
One other thing, I set the zip password to a password of my choosing. But it doesn't appear that the resulting zip file is actually password protected.  In my case it's ok if it's not password protected- but just wanted to mention what I saw.

**Comment by Ylianst** [comment]
Thanks for the suggestions. I will check the zip password again and add backup path. Yes, being able to specify the backup is pretty much essential... I should have added that from the start.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-c with auto-backup path support, I also testing the zippassword and found it worked for me. If you can try again, that would be great.

```
    "AutoBackup": {
      "backupInvervalHours": 24,
      "keepLastDaysBackup": 15,
      "zipPassword": "test",
      "backupPath": "C:\\temp"
    }
```

**Comment by PathfinderNetworks** [comment]
I just tried these changes on my server.  While the backup is working (or at least it creates a backup when I run autobackup in the console- still not sure if it's happening automatically every 24 hours) the resulting zip is still not password protected nor did the backupPath entry change anything- the backup still went to the default /meshcentral-backup folder. It's almost like it's not recognizing the entries in the config.json file?  I assume that all I need to do for changes made to config.json to take effect is to restart the MeshCentral server service?  Or is there more to it?
This is on a Windows 2019 server.

**Comment by PathfinderNetworks** [comment]
I just checked my MeshCentral server- the autobackups are running every 24 hours.  But they are not password protected nor are they saving to the path I specified in config.json.  They are saying to the default meshcentral-backup location.  So something about MeshCentral running on a Windows platform doesn't work with the autobackup commands?  
Here is what the autobackup section looks like in my config. Maybe I have the syntax incorrect?

    "AutoBackup": {
      "backupInvervalHours": 24,
      "keepLastDaysBackup": 15,
      "zipPassword": "mypassword",
      "backupPath": "C:\Users\Administrator\Desktop\Mesh Backups"
}

**Comment by Ylianst** [comment]
Hi. Thanks for your report. I just did some testing and published MeshCentral v0.3.5-h with a fix for this. The problem seems to have been with using capital letters in "AutoBackup". Using "autobackup" would have worked, however the new version fixes this. There is a second problem which is the in JSON you need to double the "\" char. So you need to write "\\". The correct config.json should be:

```
"AutoBackup": {
  "backupInvervalHours": 24,
  "keepLastDaysBackup": 15,
  "zipPassword": "mypassword",
  "backupPath": "C:\\Users\\Administrator\\Desktop\\Mesh Backups"
}
```

One could argue this is is a good example of why using JSON is a bad format for a configuration file, so I may offer a different format in the future. Update your server, fix the config.json and try again, should work now.

**Comment by PathfinderNetworks** [comment]
I just tried to update from 0.3.5-d to 0.3.5-i.  But the upgrade failed.  The Windows installer tool stalled at this point.  It then left me with a non-functional MeshCentral server install.  I had to restore the 0.3.5-d files I had backed up to get it running again.  
![Capture](https://user-images.githubusercontent.com/48607498/58519667-9827fd80-8182-11e9-8c41-e6c27407543b.JPG)

**Comment by PathfinderNetworks** [comment]
So, upon further investigation, I can see this is failing due to the autobackup section in config.json.  I had modified the path statement to use \\ instead of just \.  Once I did that then I found that MeshCentral would no longer stay running.  The service would crash shortly after starting it (on 0.3.5-d).  So I removed the autobackup section from config.json which allowed the server to run again.  I then tried another update to 0.5.3-i using the Windows installation tool. This time it completed successfully.

**Comment by PathfinderNetworks** [comment]
Ok, another update- I think the main issue was my bad.  I kept digging through my config.json and it looks like I had one extra } at the end of the file.  
I've now got it running with the autobackup syntax in place. But now one question- while digging through the config I had noticed a misspelling.  In your original syntax you have "backupinvervalhours" but should that be "backupintervalhours" instead? The 'interval' part is misspelled.

**Comment by Ylianst** [comment]
Arg! Your right, it's misspelled in the code. I am fixing that in the next version, should be out in 15 minutes.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.5-k with the spelling fix. Hopefully that will solve everything.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.5-w. I got auto-backup working on my Windows server, this is the config.json I use. Note that because I run as a Windows Service, I had to add a setting to specify the path to "mongodump.exe". So there is the config.json:

```
{
  "settings": {
    "Port": 443,
    "autoBackup": {
      "backupInvervalHours": 6,
      "keepLastDaysBackup": 20,
      "zipPassword": "mypassword",
      "mongoDumpPath": "C:\\Program Files\\MongoDB\\Server\\4.0\\bin\\mongodump.exe",
      "backupPath": "C:\\MeshCentral-backups"
    }
  }
}
```

Once setup, you can force the server to immediately do a backup using the "autobackup" command in the server console. Go to "My Server" tab, then "console" sub-tab and type "autobackup". Should work perfectly.

![MC2-AutoBackup2](https://user-images.githubusercontent.com/1319013/58740587-fee92900-83c5-11e9-98c6-49d73944d272.png)

**Comment by Ylianst** [comment]
Going to close this one since auto-backup seems to work both on my Windows and Linux servers. Please open a new issue or re-open this one if anything is not right.

**Comment by PathfinderNetworks** [comment]
Hi Ylian, I finally had some time to try this again.  But it's still not working for me. The autobackups are working- but they continue to go to the default meschentral-backup folder nor is it password protecting the zip file.  So it's like the autobackup command is ignoring the settings I have in config.json.  I updated my server to 0.3.6-c and seeing the same thing.  One question, did you correct the spelling of 'backupinterval' or is it still supposed to be 'backupinverval'?  I have my config.json using 'backupinterval' so maybe that's why?

**Comment by Ylianst** [comment]
I did correct the spelling mistake, so you should be ok. Are you sure "autobackup" is inside the settings section? What I will do is add a new command to display what the server think's it's back settings are on the server console. So we can debug this correctly.

**Comment by PathfinderNetworks** [comment]
So that was it- I didn't have the autobackup commands inside the settings section. I had it in config.json but not contained within 'settings'.  I had it as it's own separate section.  I corrected that and now it's saving  the backups to the folder I specify.  
Thanks!

**Comment by Ylianst** [comment]
Perfect, I just added a new "backupconfig" command in the server console in MeshCentral v0.3.6-h to debug this, but not needed now. Thanks for the report.

![MC-backupConfig](https://user-images.githubusercontent.com/1319013/59138759-a543aa00-8943-11e9-89d0-65b78d5e86fa.png)

**Comment by wvt-adm** [comment]
what i make wrong? - setup autobackup
![autobackup-config](https://user-images.githubusercontent.com/56296924/66586142-71de8980-eb88-11e9-8b2a-226678f06435.JPG)
![autobackup-backupconfig on the console](https://user-images.githubusercontent.com/56296924/66586185-815dd280-eb88-11e9-8d50-97d708e14eb8.JPG)
![autobackup-what-the-server-writes](https://user-images.githubusercontent.com/56296924/66586263-9dfa0a80-eb88-11e9-86e9-cfc5cd3375d8.JPG)

thanks a lot for help
am

**Comment by TitovLab** [comment]
@wvt-adm: it seems that the "autobackup" section is not located inside the "settings" section.

**Comment by MailYouLater** [comment]
@TitovLab: We got it straightened out for @wvt-adm over at #582.
