### ISSUE TITLE
Small Visual glitch on Chrome-based broswers on 1440p 

### ISSUE THREAD

**Issue by turin331** [Ylianst/MeshCentral#2420]
There seems to be a small visual bug on Linux (i am on pop 20.04) on chromium based browsers on with the broswer maximized on 1440p. The bars at the end of the gradient on the client icons are misaligned. 
Only happens on 1440p full screen. Tried it with Chromium and Brave with the same result:

![Screenshot from 2021-03-25 01-05-51](https://user-images.githubusercontent.com/16760565/112400546-df449280-8d08-11eb-959a-db4c98ca7cf8.png)

On 1080p or non-maximized it seems fine.
Also no glitch using firefox in any case. 

If relevant:
I had this on Pop_OS 20.04
using mainline kernel: 5.11.8
AMD GPU (5700xt) with Mesa 20.3.2

**Comment by yomono** [comment]
Odd..
I have almost the same setup, except for the GPU (1440p, POP_Os, 5.11.8 kernel.. all of that) 
And I'm not seeing this issue.
I'm using the last version of Meshcentral, btw

**Comment by Ylianst** [comment]
Working on this one now. I have seen this before and pretty sure I know how to fix this.

**Comment by Ylianst** [comment]
Checked in a fix for this, will be in MeshCentral v0.7.96.

**Comment by turin331** [comment]
I forgot to mention but yeah was using the current stable version. I will give it a go when 0.7.96 is available. 

Thanks!

**Comment by Ylianst** [comment]
MeshCentral v0.7.96 was just published. Let me know if that works and if I did not break anything.

**Comment by yomono** [comment]
Oh boy.. sorry for this but.. Now I'm getting glitches!!

![image](https://user-images.githubusercontent.com/31445936/112583910-e1285780-8dd5-11eb-9e39-9742c5f1dab1.png)

When the name is too long, the items get mixed

**Comment by Ylianst** [comment]
Oh! Thanks for reporting that. Working on it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.98 that includes a fix for long device names. Let me know if that works.

**Comment by yomono** [comment]
Fixed! Thank you

**Comment by turin331** [comment]
> MeshCentral v0.7.96 was just published. Let me know if that works and if I did not break anything.

Downloaded 0.8.0 and the glitch is indeed fixed. Thank you!
