### ISSUE TITLE
Feature Request: MCRouter Links On My Devices Page

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2424]
Have been using the quick / custom mcrouter links for a few weeks now and it's sped up our workflow tremendously, especially the relay map links. We have a lot of devices which cannot run the agent but have web configuration and it's made a huge difference for us, so I want to thank you again adding that!

Right now getting to those links requires opening the General page for each device. I have noticed that there is a ton of free space on My Devices in the device columns, and it seems like a perfect place to mirror these links. It would be amazing to have the option to do so. See attached image for a quick mockup.

![Untitled-1](https://user-images.githubusercontent.com/42086791/112565218-140d2400-8db3-11eb-8c6a-1dfb19d3ce52.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.99. You can now select the columns to see and added a MeshCentral Router links column. Let me know if that works.

![MC2-Columns](https://user-images.githubusercontent.com/1319013/112697522-f12b5000-8e44-11eb-8ff5-d671f03f4658.png)

**Comment by MatinatorX** [comment]
Just gave it a test, and turning on the MeshRouter links causes all of my devices to appear to become blank space. Cleared my cache etc. just in case. It also breaks the responsiveness of everything else in the My Devices tab - once everything turns white, I can't change the view mode and see anything happen without refreshing the page. Clearing the Router Links checkbox and refreshing again gets everything working again, but of course no links. See attached screenshot. 

I'm playing around with different things to see if I can identify what might be causing the issue. I have a few links made in the config.json so I'll try removing some to get the number down (maybe 6 links is too many) or see if it's a relay map issue.

![Untitled-1](https://user-images.githubusercontent.com/42086791/112699873-2a72b880-8e63-11eb-9759-6b2bf99f949f.png)

**Comment by MatinatorX** [comment]
Narrowed it down. Having the "filter": property on any custom links breaks things as shown above.

**Comment by Ylianst** [comment]
Can you open the browser console and see if there are any errors showing up when the problem happens? If there are some, please send that over. I should be able to fix it. This is very likely a web page problem, nothing to do with the server.

![image](https://user-images.githubusercontent.com/1319013/112711980-b7306d00-8e89-11eb-8f15-bb2fedf0f4f0.png)

**Comment by Ylianst** [comment]
Oh! I get it not about the filter. Yes, your creating custom router links. Let me test that now.

**Comment by Ylianst** [comment]
I am seeing the same problem now. Working on it.

**Comment by Ylianst** [comment]
Ok, fixed it. Will be on MeshCentral v0.8.0. Thanks for reporting this with such detail.

**Comment by MatinatorX** [comment]
Of course, thank you for implementing the feature and for fixing it so quickly! I'll close this issue just as soon as v0.8.0 is out for me to test.

**Comment by Ylianst** [comment]
Publishing a new version in a few minutes.

**Comment by Ylianst** [comment]
MeshCentral v0.8.0 is now published. Let me know if it works.

**Comment by MatinatorX** [comment]
Works great! Thanks again!
