### ISSUE TITLE
Feature Request: MCRouter Links Open In Same MCRouter Instance

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2425]
Currently, when opening an mcrouter:// link, a new MeshCentral Router instance is opened even if one is already running and logged in. It would be great if there was a way to check if MeshRouter was already open and just use that instance if so, even if it means cancelling the auto-close option!

**Comment by Ylianst** [comment]
Good request, [I have a beta version ready here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Can you download and give it a try? Same version number but will do single instance and cancel the auto-close. Feedback appreciated. If it works, I will update the version number and include it in the next MeshCentral version.

**Comment by MatinatorX** [comment]
Just ran it through some tests, works perfectly. Thank you!

**Comment by Ylianst** [comment]
Thanks for the report.
