### ISSUE TITLE
Meshcentral Assistant Not working.

### ISSUE THREAD

**Issue by AMI231187** [Ylianst/MeshCentral#2428]
The Mesh Assistant not working .

Its showing Agent running status but request help button is disabled.

MC Version - 0.7.95
Agent Customization - No

![image](https://user-images.githubusercontent.com/81413474/112628589-1a55db80-8e59-11eb-8996-0e4f468bcf1d.png)

**Comment by VINISHVV** [comment]
@AMI231187 - Its already reported case- #2260

**Comment by Ylianst** [comment]
Not sure why this is happening. MeshCentral Assistant can see that the agent service is running, but it can't connect the named pipe to the agent, so it can't communicate with the agent.

Can you try running MeshCentral Assistant "As Administrator" and let me know if it starts working? If so, this is still a bug, but at least will give me an idea what the problem is.

**Comment by VINISHVV** [comment]
@Ylianst 
Run as administrator also not working.

**Comment by Ylianst** [comment]
@VINISHVV Ok, thanks for reporting back. That helps. I will do some testing.

**Comment by Ylianst** [comment]
Mine works. Are you running the 32bit or 64bit version of the agent?

![image](https://user-images.githubusercontent.com/1319013/112677242-b61a2400-8e26-11eb-87a1-20c627cabca8.png)

**Comment by VINISHVV** [comment]
I have tried in 64bit

**Comment by paolor1965** [comment]
hi on windows 10 version 1809 it works: mesh agent 64 bit,

 latest version meshcentral server

![Cattura](https://user-images.githubusercontent.com/58943816/112680766-0ff20c80-8e6e-11eb-90b7-d46e91b4f1a7.PNG)


on windows 10 pro version 20h2 does not work, mesh agent 64 bit, latest version meshcentral server 

![Cattura](https://user-images.githubusercontent.com/58943816/112680925-4596f580-8e6e-11eb-8dde-cd41c1bdfab9.PNG)



two computers from different subnets

**Comment by VINISHVV** [comment]
@paolor1965 you are correct the assistant app is working in specific os versions. 

@Ylianst can you look into this once, I understand it's little difficult else this will resolved with in seconds...

**Comment by Mfinadmin** [comment]
Assistant app is not working. I have tested the same in below Operating systems.


Windows 7   Professional [7601]
Windows 10 Pro - 1909 [18363]
Windows 10 Pro - 1809 [17763]
Windows 10 Pro - 2004 [19041]
Windows 10 Pro - 1703 [15063]
Windows 10 Pro - 2009 [19042]
Windows 8.1 Pro [9600]
Windows 7 Ultimate [7601]
Windows 10 Pro - 1903 [18362]
Windows 10 Pro - 1709 [16299]
Windows 8.1 Enterprise [9600]
Windows 10 Pro - 1803 [17134]
Windows 7 Home Premium [7601]
Windows 10 Pro - 1607 [14393]
Windows 10 Enterprise - 1909 [18363]
Windows 10 Pro for Workstations - 1909   [18363]
Windows 10 Enterprise - 1803 [17134]
Windows 8 Pro [9200]
Windows 10 Enterprise - 1809 [17763]
Windows 10 Enterprise - 2009 [19042]
Windows 10 Enterprise - 2004 [19041]
Windows 10 Enterprise - 1903 [18362]
Windows 10 Home - 2009 [19042]
Windows 7 Professional [7600]
Windows 10 Home - 2004 [19041]
Windows 10 Pro [10240]
Windows 10 Home Single Language - 2004   [19041]
Windows Vista (TM) Ultimate [7601]
Windows 7 Ultimate [7600]
Windows 7 Home Basic [7601]
Windows 10 Home Single Language - 1709   [16299]
Windows 10 Home - 1909 [18363]
Windows 10 Home - 1903 [18362]
Windows 10 Pro Education - 2004 [19041]
Windows 10 Pro - 1511 [10586]
Windows 8.1 Pro with Media Center [9600]
Windows Server 2012 Standard [9200]
Windows Server 2019 Standard - 1809   [17763]

**Comment by Mfinadmin** [comment]
@Ylianst - Any update on this ?

**Comment by VINISHVV** [comment]
@Mfinadmin -  cool.. This will fix soon

**Comment by VINISHVV** [comment]
This issue fixed in v0.8.16 as per #2518, But need to download New Assistant version is [available here.](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralAssistant.exe)

**Comment by AMI231187** [comment]
Wow its a great news....
For each issues we are getting proper and timely fix from MC team.
Thanks @Ylianst & @krayon007 - for your efforts to publish such wonderful tool.
Thanks @VINISHVV for the update.
