### ISSUE TITLE
Unable to import devices via MeshCMD

### ISSUE THREAD

**Issue by mrflaunted** [Ylianst/MeshCentral#2429]
It is an odd issue, as this was working fine a couple weeks ago. Essentially we have a script that checks a machines IP address,  downloads MeshCMD from our internal server, then deduces the device group ID from the IP and imports it in. It is now failing stating the device group cannot be found. Initially we checked networking side because of where the MeshCMD stopped, but as we looked at the MeshCentral logs, you can see MeshCMD open the socket but then it seems that MeshCentral is truncating the device group ID#.

We created a new device group, same issue. Use an existing device group, same issue.

We updated all components in an attempt to fix. So Mesh, MongoDB and node.js are all on latest releases. 

- Node.js > 14.16
- MongoDB > 4.4
- Mesh > 7.95

Any ideas?

Setup command: https://imgur.com/VXWqens
Remote machine: https://imgur.com/UDiRtvx
MeshCentral trace: https://imgur.com/fhLGHaG

**Comment by Ylianst** [comment]
Hi. Looking at your second screen here.

![image](https://user-images.githubusercontent.com/1319013/112674387-1c04ac80-8e23-11eb-8179-379a07b31325.png)

It looks like the command is cut so that instead of running:

```
meshcmd amtconfig --url wss://xxxxxxxxxxxx --id xxxxxxxxxxxxxx --serverhttpshash xxxxxxxxxxxxxxx
```

You are instead running:

```
meshcmd amtconfig --url wss://xxxxxxxxxxxx --id xxxxxxx
```

Basically, cutting off the command in the middle of the device group identifier. As a result, that identifier will not match on the server side which is what we see in the logs on the 3rd line here:

![image](https://user-images.githubusercontent.com/1319013/112674705-7b62bc80-8e23-11eb-8e20-cc180c1b21bf.png)

Let me know if that help. I think it's a question of running the entire command.

**Comment by mrflaunted** [comment]
Apologies, I am not sure I follow. In my example I am copying and pasting the command from the Setup link. I see it in the same format you mention.

https://imgur.com/HGNKItW

**Comment by Ylianst** [comment]
Just to make sure, past the command in NotePad.exe and make sure it's one single line. Is there word wrapping in the command shell? I did not think that was possible.

**Comment by mrflaunted** [comment]
yeah, you can in Windows now. I expanded it here:

https://imgur.com/ZDnnqm9

**Comment by mrflaunted** [comment]
I wanted to follow up and confirm that you see the command is not truncated. 

![full command prompt](https://user-images.githubusercontent.com/54959671/112982053-01377e00-912a-11eb-9c73-b08117ae1d6d.JPG)

**Comment by Ylianst** [comment]
Thanks for checking. I am out tomorrow and will be back at work after that and will take a look. Hopefully it's something simple like putting quotation marks around the device group identifier or something. I certainly need to print better error messages in this case.

**Comment by Ylianst** [comment]
I found and fixed this issue. It will be in MeshCentral v0.8.1 when published later today. Once published, if you can test that it's now working and close this issue. Thanks.

**Comment by mrflaunted** [comment]
Yes sir, once made available I can update the environment. You are amazing, thank you.

**Comment by mrflaunted** [comment]
Just upgraded to 8.01 and bulk imports are working again. Thank you much!
