### ISSUE TITLE
enable not-admin users to insert device tags

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#243]
Hi,
I'm playing with user and group rights, but I can't find a way to enable users inserting TAGS in device without assigning "Full administrator" checkbox.
how can I enable editing ? It would be very useful because tags are searchable, so they can filter devices in custom ways according to specific definitions

Thanks

Merlinweb

**Comment by jsastriawan** [comment]
This may have security implications. Any user could erase previous tags defined administrator too.

Per user tags may be possible not sure how this flexibility will impact implementation. We could store user defined tags for each node. When a node is detached, those tags  will be removed. Duplicate tags and merging those tags will also the issue that must be considered for this implementation.

Well it is up to Ylian to decide if this will be implemented.

**Comment by merlinweb** [comment]
It's correct Joko, someone can update/delete other writing, but manage 3/4 tags for about 800 devices, it's a load too big  for a couple of admins, I know it's just my case... for other mesh can be different, of course 
Adding a checkbox in "Add User to Device Group" window, enabling tags management (with overwrite, same tags for all), I think It's a good choice.
Admins can remove auth from an user if necessary, but technicians (users) haven't to be elevated to insert tags for improve searches
As far as I know, tags are only information data about device itself, or there are more hidden functionalities ?
thanks for ryour reply
Cheers
Merlinweb

**Comment by Ylianst** [comment]
I will fix this. Changing tags on devices should be a device group right, nothing to do with the server administrator.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.5-g with a fix for this. Users needs the "Manage Device Group Computers" right on a device group to change the tags. Also, if you don't have that, the UI will correctly not show the edit dialog box. Hopefully, this fixed this.

![MC2-DeviceTagsRights](https://user-images.githubusercontent.com/1319013/58434375-2fe8f700-8070-11e9-8f3f-0cf35d348013.png)

**Comment by merlinweb** [comment]
Thanks Ylianst,
now it works as excpected, enabled users can manage tags 
Perfect for users needs

Cheers

Merlinweb
