### ISSUE TITLE
Unable to create new device group

### ISSUE THREAD

**Issue by jjoelc** [Ylianst/MeshCentral#2431]
Strange one... Finally picked back up on getting our production server, updated Meshcentral to 0.7.98 without issue, and in the course of things, discovered that none of the admin accounts are able to create new device groups.

MeshCentral 0.7.98 running on Ubuntu Server 20.04, using MongoDB:
From My Devices page, click on Create New Device Group link, pop up window opens, we fill out the group name etc, click OK... and.. Nothing. No group appears, not error message, etc. Our testing server on the same version number, but using NEdb does not exhibit the issue. 

This has the feel of a database permission issue or similar, but I'm not familiar enough with MongoDB (or MeshCentral internals) to know where to start troubleshooting this.

Any pointers would be greatly appreciated.

**Comment by jjoelc** [comment]
slightly more info... this is the result trying to add group using meshctrl:
```
wansol@wansol-meshcentral:/opt/meshcentral/node_modules/meshcentral$ node meshctrl AddDeviceGroup --name JoelTest
Unable to connect to wss://localhost/control.ashx
```

**Comment by Ylianst** [comment]
Before looking at complicated things, can you open the browser console and see if there are any errors showing up when you create the device group? If so, please post them here. Thanks.

![image](https://user-images.githubusercontent.com/1319013/112689737-ea4a1080-8e37-11eb-8350-7f0a37f1d50a.png)

**Comment by jjoelc** [comment]
Sorry for the delay... We actually ended up rolling back to a snapshot previous to the issue, we then walked forward slowly through the config changes that were made, etc. with the final step being an update to Stable v0.7.89

At that point, we encountered the same issue. The below error shows in the browser inspection console, however, it appears before trying to create the device group. Attempting to create a device group does not produce any additional errors.
![Capture](https://user-images.githubusercontent.com/4069621/112695270-c693c400-8e51-11eb-905b-a49290626945.PNG)

**Comment by Ylianst** [comment]
Interesting. Looking into it now.

**Comment by Ylianst** [comment]
I just did a just change in just published MeshCentral v0.7.99. However, this is of concern since I don't see this problem and I don't have sufficient information to know what is going on. If you know what version of MeshCentral works and does not work, that would be helpful.

**Comment by jjoelc** [comment]
I hate having so little info myself! Sorry about that.

When creating device groups was working Mesh version was 0.7.28, when updated to stable 0.7.89 was when we discovered the issue. I wish it was a little narrower range for you.  If needed, I can find some time this weekend to manually install specific versions in that range and try to pinpoint it a bit better. I will test 0.7.99 this evening and let you know as well.

**Comment by jjoelc** [comment]
OK. I found time sooner than expected and was able to narrow it down a bit. 

- First bit - the issue seems unrelated to the error reported in the browser console.  I see the same error reported in versions where device group creation is working as well as versions where it is not.
- Next, Device group creation working in v 0.7.32, broken in 0.7.33

 Some details of the install, if needed I can provide temporary access to the web portal.
 - Ubuntu Server 20.04
 - npm v6.14.4 (I do get the notice about new major version of npm 7.7.5 available, OK to update?)
 - Mesh server running behind an nginx reverse-proxy
 - We **are** using client side certificates for additional security.
    - I mention this in case it may be related to the issue shown in browser console, mostly. We are aware of the restrictions this setup will place on MeshRouter, etc. So far we have been able to work around or live with all restrictions we have run into. Will of course be glad to share our experiences, but honestly things have behaved exactly as you predicted they would when I first asked about using client certificates.
  - If needed, I can provide a sanitized config.json file. I didn't include it here as it seemed to not be the cause of the issue.

As always, FABULOUS work, We truly appreciate MeshCentral.

**Comment by Ylianst** [comment]
Wow!!! This is really good data. Taking a look at code changes now between 0.7.32 and 0.7.33.

**Comment by Ylianst** [comment]
Looking at the code changes between 0.7.32 and 0.7.33, I do see something that could be an issue. Are you by any change using your own customized web pages? That is, your updating the server but not updating the web pages?

In the main web site, the file "default.handlebars" there is a change from:

```
(v0.7.32)
function account_createMeshEx(button, tag) {
  meshserver.send({ action: 'createmesh', meshname: Q('dp2meshname').value, meshtype: Q('dp2meshtype').value, desc: Q('dp2meshdesc').value });
}
```

```
(v0.7.33)
 function account_createMeshEx(button, tag) {
  meshserver.send({ action: 'createmesh', meshname: Q('dp2meshname').value, meshtype: parseInt(Q('dp2meshtype').value), desc: Q('dp2meshdesc').value });
}
```

There is an additional parseInt() added in on the new version. If you update the server, but keep the old web pages that don't include the parseInt(), the "createmesh" command will be ignored by the server. If you make this change to your customized pages, that should fix it.

I will also make a change on the server to handle both old and new style, just in case you just want to update.

Of course, this is a bit of a guess as to what is going on, but likely a good guess.

**Comment by Ylianst** [comment]
I just made a change to that v0.8.0 will accept the old format of the "createmesh" command just in case it helps.

**Comment by jjoelc** [comment]
Just wanted to confirm, that was in fact the issue. made the change you mentioned to default.handlebars and device group creation works as expected in stable v0.7.89

Thank you!
