### ISSUE TITLE
system uptime and agent version in List view / Export option

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2435]
Dear @Ylianst 

If possible please add "System Up time " & "Agent Version"  in list view  OR export device information options.

**Comment by si458** [comment]
you can see the 'agent version' already by clicking the cog and selecting 'agent version'
we are just missing the 'system uptime' being reported from the remote device

**Comment by si458** [comment]
meshcentral now records the `Last Boot Up Time` so would this be OK to shown in the column instead of `system uptime` ?
as we would have to do calculations for the `system uptime` based on the `last boot up time` ?

**Comment by VINISHVV** [comment]
Wow. Its good

**Comment by si458** [comment]
ok ill add `Last Boot Up Time` into the columns during the next week for you 👍

**Comment by silversword411** [comment]
Dont forget to donate ❤️ or look at his amazon wish list! https://www.si458.co.uk/2024/01/05/donation/

**Comment by si458** [comment]
PR DONE, it will now show you the `Last Boot Up Time` of the device and the `Agent version`
![image](https://github.com/Ylianst/MeshCentral/assets/765314/619d3ff1-18ef-4ace-ae84-34dca9932c46)
