### ISSUE TITLE
Report like RMM

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2438]
Hi, is it possible to export information about all devices in a group? the current one is exporting minimal info like counting sort of thing but not included the information like those found in details tab for each device... e.g Network, RAM, cpu anti-virus and OS software.

Thanks for the great software.

**Comment by Ylianst** [comment]
Hi. Your right, the current "Group Action" for exporting information is minimal, I can work on adding more data to it.

On a separate note, you can currently pull device details using meshctrl.js like this:

```
node node_modules/meshcentral/meshcentral/meshctrl.js deviceinfo
```

That should pull all of the device details using the command line.

**Comment by smartekIT** [comment]
Thanks champion,
but that command will pull or export details of all devices i guess !
I manage different sites, and each site has like 10 pcs, so i created a group for each site. now i'm in a situation that i need to do auditing on each site so i though it will be good if we can export detailed report for each site which will show same info we currently get on any pc details tab but instead it will be for every pc in the group.

computer 1 Name:
cpu, agent, ram, motherboard, network and IPs, hard drive, storage used, storage free, anti-v installed, OS version ...etc.

computer 2 Name:
cpu, agent, ram, motherboard, network and IPs, hard drive, storage used, storage free, anti-v installed, OS version ...etc.

all in one excel sheet or pdf. that would be great to have.

thanks in advanced for your work and efforts.

**Comment by VINISHVV** [comment]
@smartekIT - A small correction in the meshctrl command mentioned above.

Please use below one.

node node_modules/meshcentral/meshctrl.js deviceinfo

**Comment by Ylianst** [comment]
I think this is a good idea to add all that information. I am out for the next 3 days, when I get back to work I will add this.

**Comment by VINISHVV** [comment]
@Ylianst 

Happy holidays...

If possible include system up time and agent version in the export options #2435

**Comment by smartekIT** [comment]
enjoy your holiday @Ylianst
@VINISHVV it's a report, so the more info can get the better for auditing.
Thanks in advanced guys.

**Comment by Mfinadmin** [comment]
Wow !!! 

Hope this will available in Meshcentral soon.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.4 with extra export details. Let me know if it works.

![image](https://user-images.githubusercontent.com/1319013/113802237-325a1480-970f-11eb-9b5a-76964ca9d0cd.png)

**Comment by VINISHVV** [comment]
Wow !!..  Its great.

If possible please add the following options too.

1) Memory capacity ( RAM )
2) HDD Storage
3) System Up time / Last boot time.

**Comment by smartekIT** [comment]
@Ylianst  Thanks for the update. it's much better now.

have you had a chance looking at:
https://github.com/Ylianst/MeshCentral/issues/2460#issuecomment-813372791
and
https://github.com/Ylianst/MeshCentral/issues/2460#issuecomment-813378846

**Comment by smartekIT** [comment]
> Wow !!.. Its great.
> 
> If possible please add the following options too.
> 
> 1. Memory capacity ( RAM )
> 2. HDD Storage
> 3. System Up time / Last boot time.

yes it's currently not showing any of those in the exported sheet. they are very important to collect specially RAM and HDD.

**Comment by VINISHVV** [comment]
> Wow !!.. Its great.
> 
> If possible please add the following options too.
> 
> 1. Memory capacity ( RAM )
> 2. HDD Storage
> 3. System Up time / Last boot time.

@Ylianst 

is it possible to add those fields ?

**Comment by Mfinadmin** [comment]
The important details like HDD/ Memory details are still unavailable.
