### ISSUE TITLE
LDAP reverse account problem

### ISSUE THREAD

**Issue by alixxila** [Ylianst/MeshCentral#2439]
Hi everyone,

first my team and me have to be really thanksfull for this beautiful project/software alternative to TeamViewer you bring to us, the work behind MeshCentral is really huge.

We use it to take control over client sever and laptop, everything working well, we connected it with our Active Directory to log into MeshCentral via web server and the MeshRouter, we have setup a reverse proxy, we now have a new co-worker and we have a problem with the LDAP :

When he logged into his account for the first time he was on my account with the same ID user//alotsofnumber and when he was on his account i had two sessions active and his name was mine, like if the account was reversed " his name was displayed into the log of meshcentral when en logged in ( the third icon )  "  /!!\

I HAVE TO CHANGE OUR LAST NAME AND IP'S, I **CHANGED PRIVATE IP'S** WITH **RANDOM PUBLIC IP'S** !!

This is the logs of the first connexion,  **CEDRICK** is our new co-worker.

	 	`	 	08:59:39 - a.lastname → Tentative de connexion invalide de 180.40.205.122, Firefox/86.0, Windows/10	 
	 	08:59:29 - Cédrick lastname → Déconnexion du compte	 
	 	08:59:18 - Cédrick lastname → Connexion de 180.40.205.124, Firefox/86.0, Windows/10	 
	 	08:59:03 - Cédrick lastname→ Déconnexion du compte	 
	 	08:58:10 - Cédrick lastname→ Connexion de 180.40.205.124, Firefox/86.0, Windows/10	 
	 	08:58:10 - Cédrick lastname→ Unset email (no more email in LDAP)	 
	 	08:58:10 - Cédrick lastname→ Changed account display name to Cédrick lastname
	 	08:58:08 - Alix lastname → Déconnexion du compte	 
	 	08:57:40 - Alix lastname → Connexion de 180.40.205.122, Firefox/86.0, Windows/10	 
	 	08:57:40 - Alix lastname → Set account email to a.lastname@company-info.com. Sync with LDAP.	 
	 	08:57:40 - Alix lastname → Changed account display name to Alix lastname 
	 	08:56:41 - lastname → DC2019 → Session de bureau terminée "h7ao7c0jg57" de 180.40.205.124 à IpOfCient, 10 seconde(s)	 
	 	08:56:30 - Cédrick lastname → DC2019 → Bureau à distance lancé sans notification (180.40.205.124)	 
	 	08:56:30 - Cédrick lastname → DC2019 → Session de bureau lancée "h7ao7c0jg57" de 180.40.205.124 à 212.250.172.173	 
	 	08:56:10 - Cédrick lastname→ Connexion de 180.40.205.124, Firefox/86.0, Windows/10	 
	 	08:56:10 - Cédrick lastname→ Unset email (no more email in LDAP)	 
	 	08:56:10 - Cédrick lastname→ Changed account display name to Cédrick lastname
	 	08:56:07 - Alix lastname → Déconnexion du compte
`

So i tried to delete my account and i told him to try to connect again and when he logged into meshcentral he had the same user ID as mine like before but with a new account ( with no rights on any groups, like when you log in for the first time ). I really do not understand why.. When i checked the logs i found ( no more email in LDAP ).

We also have some request to upgrade meshcentral :

 - Add the RDP options into the " Double click actions "
 - Have the possibility to copy and paste directly without using the clipboard
 - Display the domain name on the web interface next to the user and admin when we go into the part " My Devices " ( tell me if it's possible to manage it directly into the code )

If we can help you coding these features please let us know !!

Thanks.

Best regards,

Have a good day.

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
