### ISSUE TITLE
MeshMessenger : show the conversation by clicking on the notification ?

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2440]
Hi,

I was thinking that it could be useful, for a remote user, to show the MeshMessenger conversation by clicking on the notification when that appears, especially when he has several web browsers tabs opened.

![notification](https://user-images.githubusercontent.com/76168733/112818151-82880580-9083-11eb-8567-379274bdc49a.png)

Also, is there a way for the meshagent to activate the browser's notification by default or it's up to the remote user to set it ?

Thank you.

**Comment by Ylianst** [comment]
Oh, I expected it would do that already. When I get back to work, I will test this. Clicking on a notification should bring you back to the conversation.

**Comment by si458** [comment]
all fixed https://github.com/Ylianst/MeshCentral/commit/ce4217c346d7bcd6e2bdf3fb2657a14bad74cd61
