### ISSUE TITLE
KVM Child Process has unexpectedly exited on Raspberry Pi

### ISSUE THREAD

**Issue by lulu3000** [Ylianst/MeshCentral#2441]
Hello,

I know that there is a lot of communication about this, but I didn't find a solution for me. I have set up MeshCentral and it works fine with my Windows Machine. However, with my Raspberry Pi, it worked only one time after installation of meshagent and after a restart ist only says "KVM Child Process has unexpectedly exited". I managed to repeat this behaviour once (new Installation - it workes once) but not more often.

My version of MeshCentral is 0.7.99
My version of Raspbian is Linux 8 (Jessie)

How can I investigate this further? It es especially strange that it worked 2 times.

Thank you for any help!!

**Comment by krayon007** [comment]
Do you have an actual monitor plugged into the Pi? I know on some linux distros, particularly on the PI, X doesn't actually start if there is not a monitor plugged into the DisplayPort/HDMI (does not need to be powered on). I know the work-around for this is configure X with a loopback driver.

**Comment by Ylianst** [comment]
What version of the Pi are you using? I have a bunch of them, I can try to replicate this.

**Comment by lulu3000** [comment]
Hello

> Do you have an actual monitor plugged into the Pi? I know on some linux distros, particularly on the PI, X doesn't actually start if there is not a monitor plugged into the DisplayPort/HDMI (does not need to be powered on). I know the work-around for this is configure X with a loopback driver.

There is no monitor plugged into. It can not be the reason for the crash, because, as I wrote, I saw it work twice.

**Comment by lulu3000** [comment]
> What version of the Pi are you using? I have a bunch of them, I can try to replicate this.

pi@raspberrypi:~ $ cat /etc/debian_version
8.0

 cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2709
Revision        : a02082
Serial          : 00000000ba6ae309

It's a "hifiberry".

Thank you!

**Comment by lulu3000** [comment]
Update: I have stopped the service and i have started "meshagent run" manually. It runs as user "pi".
When I try to connect the desktop very often, it works after some 30+ tries. 
Two things are also interesting: 
1. When it works, is survives also the next disconnects and connects. 
2. When it works, i suddenly see 2 meshagent processes:

 ps aux | grep mesh
pi        7922  1.5  2.4  33520 22884 pts/2    Sl   10:19   0:08 ./meshagent run
pi        9954 13.6  2.3  35460 22484 pts/2    R    10:28   0:05 ./meshagent run
pi       10037  0.0  0.2   4296  2012 pts/2    S+   10:28   0:00 grep --color=auto mesh

**Comment by lulu3000** [comment]
Update 2: 

Got it to work! When in move the mouse over the black screen, immediatly after pressing "connect", it works like a charm.
It's already good like this, but can I improve this behavour?

**Comment by Ylianst** [comment]
Is the problem that the Raspberry Pi has it's display in low power mode and moving the mouse wakes it up? I am not sure I could send a mouse event on connect because that would not be nice to the local user.

**Comment by lulu3000** [comment]
Thank you very much. 
I have disabled all the power and screen saver features and it seems to work now smooth.

**Comment by lulu3000** [comment]
Fun fact: I found a permanent solution by ENABLING the X screensaver and setting it to a non-blank saver. It seems to be important that the screen is sending something.
