### ISSUE TITLE
WebRDP session dies based on the AgentPong Value set in the config.json file

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#2442]
My server is at version 0.7.89
My agents are up to date with what ships with that version
Set in my config file is the AgentPong value of 30
	"AgentPong": 30,

When I use the Web-RDP option with the agent, it connects, asks for the password all in the browser, totally awesome. but the session dies and throws this log

  Ended relay session "23521107094493332" from 10.0.0.2 to 127.0.0.1, 30 second(s)

Weird IPs are because I am in a docker container with mesh, so all incoming looks like 10.0.0.2, not related, but could look odd. 

So I decided to change my AgentPong value to 35 and bounce Meshcentral,
	"AgentPong": 35,

Then the session died again except the log read
  Ended relay session "8728281513678566" from 10.0.0.2 to 127.0.0.1, 35 second(s) 

So to me it looks like they are tied together, which likely isn't what we want.

**Comment by Ylianst** [comment]
Thank you for reporting this. I know exactly how I will fix this. I am out on a small vacation until Wednesday. Once I get back, I will fix this right away.

**Comment by Ylianst** [comment]
I just put in the fix for this. The MSTSC channel will no longer have the agent ping/pong on it since it can't support it. This will be in MeshCentral v0.8.1.

**Comment by githubbiswb** [comment]
Just tested and it looks great, thank you for all of your hard work!
