### ISSUE TITLE
New agents not showing in dashboard till server restart 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2443]
Dear @Ylianst 

i am running Meshcentral with 6000+ agents. when the agent count increased from 2000 i notices that the newly installed systems are not came up/not showing in dashboard timely. When i restart the meshcentral service all the new and old agents connects properly.
After restart meshcentral new agents connects properly and after few hours another restart required. This issue i noticed only for new agent installation.
I have tried to run the agent in cmd mode using **meshagent run** command but its showing message connecting to my server and after few minutes its showing retry messages. If i restart meshcentral then the agent connects properly.

My server config is given below.

Server OS - Windows server 2019
DB - Mongodb
Plugins - Not used
my config file given below

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mydomain",
    "certUrl": "mydomain:443",
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "_AllowHighQualityDesktop": true,
    "_compression": true,
    "_ignoreAgentHashCheck": true,
    "_wscompression": true,
    "_agentwscompression": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "agentpong": 60,
    "agentIdleTimeout": 80,
    "_agentping": 30,
    "webPush": { "email": "itvinish@mydomain.com" },
    "webRTC": true,
    "authlog" : "c:\\Meshcentral\\auth.log",
    "_ListEvents" : "c:\\mesh\\event.csv",
    "noagentupdate": true,
    "AllowLoginToken": true,
    "MaxInvalidLogin": {
    "time": 10,
    "count": 50,
    "_coolofftime": 10
    },
    "dbExpire": {
    "events": 31536000,
    "powerevents": 604800,
    "statsevents": 604800
    },
	"_plugins": {
     "enabled": true
	},
 "AutoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 12,
      "keepLastDaysBackup": 20,
      "backupPath": "E:\\Meshcentral BACKUPS"
    }  
      },
   "domains": {
    "": {
      "minify": true,
      "newAccounts": false,
      "agentInviteCodes": true,
      "autocomplete": false,
      "_userNameIsEmail": true,
      "mstsc": true,  
       "sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "E:\\Meshcentral RECORDINGS",
        "index": true,
        "maxRecordings": 1000000,
        "_maxRecordingSizeMegabytes": 3,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
},
  "passwordRequirements": {
        "force2factor": true,
         "reset": 10        
      },
  "_consentMessages": {
        "title": "Meshcentral",
        "desktop": "{0} requesting remote desktop access. Grant access ?",
        "terminal": "{0} requesting remote terminal access. Grant access ?",
        "files": "{0} requesting remote files access. Grant access?"
      },
  "_agentCustomization": {
        "displayName": "Meshcentral",
        "serviceName": "M_Access",
        "_fileName": "Meshagent"
}
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  },
 "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "myemail@mydomain.com",
    "user": "myemail@mydomain.com",
    "pass": "xxxxxxxxxxxx"
  },
  "sms": {
    "provider": "twilio",
    "sid": "xxxxxxxxxxx",
    "auth": "xxxxxxxxxxxx",
    "from": "+xxxxxxxxxxxxx"
  }
 }
```

**Comment by Ylianst** [comment]
Can you send a screenshot of the agent cmd line with the retries? Thanks.

**Comment by VINISHVV** [comment]
@Ylianst 
sorry i will post the screenshot tomorrow, because now i am out of office.

**Comment by Ylianst** [comment]
Well, if the agent is connecting correctly, I guess agent screenshot is not needed but this will be difficult to debug with the information given. Would it be possible to give me a dummy account on your server? You can send me [the account privately](https://www.meshcommander.com/contact-information) and I can try installing a new computer and see if I can find any issues.

**Comment by Ylianst** [comment]
Note that [MeshCentral.com](https://meshcentral.com) has more devices that this and does not seem to have any issue. Do let me know if you have any reverse proxies or firewalls in front of your MeshCentral server.

**Comment by VINISHVV** [comment]
@Ylianst 
Yes I have firewall in front of my server. 
I will share the account details though email.

**Comment by Ylianst** [comment]
One possibility is that the firewall is starting to reject agent connections after some amount or in some situations. I will check, but this is not easy to debug these problems from my end. You have to look at the firewall events, etc.

Another thing that can help is to run the "agentstats" in the "My Server" console and see if anything unusual if happening like this:

![image](https://user-images.githubusercontent.com/1319013/112920540-065ee380-90be-11eb-8495-d1f3446b3081.png)

**Comment by VINISHVV** [comment]
@Ylianst 
Thanks for your advice.. 
Please enjoy your holidays...
 I will reach you after your 3days vacations.

**Comment by VINISHVV** [comment]
@Ylianst 

Please find the below screenshots. I am getting watchdog error in every minute if the number of connected agents increased to more than 2000.. 

**Agentstats**

![image](https://user-images.githubusercontent.com/65057910/113244756-44812080-92d3-11eb-9db3-dee406d99dab.png)

**Watchdog**

![image](https://user-images.githubusercontent.com/65057910/113244851-6d091a80-92d3-11eb-81af-177472d44995.png)

![image](https://user-images.githubusercontent.com/65057910/113244919-8f029d00-92d3-11eb-82e5-b330f56d90c1.png)

![image](https://user-images.githubusercontent.com/65057910/113244960-a477c700-92d3-11eb-8dd9-ac059abe579f.png)

**Comment by VINISHVV** [comment]
@Ylianst  - credentials shared via E-mail

**Comment by Ylianst** [comment]
Ok, I took at look at your server and now looking at your config.json again. You server has agents disconnecting and reconnecting at a rapid rate. One thing that is very bad is this line:

```
"agentIdleTimeout": 80
```

This will set an idle timeout for the agent of 80 seconds which is very low. The default is 150, I would put this value very high on your server, like:

```
"agentIdleTimeout": 900
```

Or even try to remove this timer completely:

```
"agentIdleTimeout": 0
```

I also noticed that your "MaxTasks" is set to 500. Not sure how you set this, it's not in the config.json, but it should be set lower. 50 is I good value I think.

Your server has a reverse proxy in front of it since all of the agent connections are coming from the same private IP address. However, the config.json above makes no mention of any reverse proxies, so I am not sure what software is running on front the MeshCentral. Whatever software is running in front, if it has a connection timeout, it should be set to be very long. This way, you can remove this line:

```
"agentpong": 60
```

It would be best not to have to ping/pong all of the agents every 60 seconds if possible, this adds a lot of traffic to the server and should be avoided if possible.

Hope that helps,
Ylian

**Comment by VINISHVV** [comment]
Thanks alot @Ylianst for your valuable findings. 
I will make necessary corrections in config.js and also clear the firewall configuration.  

Marking the task as closed. In case any issue notices o will reopen the new one.
