### ISSUE TITLE
32bit agent crash

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2445]
Running fairly recent version 0.7.82 at this moment.
The issue I have is only occuring on the 23bit agent and specific systems, it seems.

2 of 3 systems running the 32bit agent have this problem, all supplied by the same vendor.

The agent will disconnect and reconnect for a few times (I know there is a limit) each day. This is at a random time.
The agent stays online after the limit like there was nothing wrong, nothing in the log.  Checking the modem there is also no disconnect there. Looking in the MC trace windows just says "new connection... disconnect... new connection" nothing strange 

The other system also does this, but for some reason this agent also crashes when I want to connect to the desktop from time to time.
[2021-03-29 07:36:02 PM] FATAL EXCEPTION [MeshAgent_3B1115E83085CFBF.exe] @ [FuncAddr: 0x0012bdc9 / BaseAddr: 0x0017ca93 / Delta: 330954]
There is a dump file available, can I just mail the url from the dumps page to you?

not sure if the disconnects/crashes are related. is there a way I can log the connect/disconnect activity for these agents?

**Comment by Allowee** [comment]
Just updated to the latest version and enabled the trace log
some lines from the log that might help

`
21:22:09 - AGENT: Agent in trouble: NodeId=cYxZCz5meq0ak2QlozF$rF77WxPr52TjUwWPycgJhq$yHdHzQmBnTPeXrPkd2rPK, IP=89.xxxx
21:21:53 - AGENT: Agent disconnect cYxZCz5meq0ak2QlozF$rF77WxPr52TjUwWPycgJhq$yHdHzQmBnTPeXrPkd2rPK (89.xxxxx2:12197) id=3
21:21:44 - WEBREQUEST: (89.2xxxxx) /meshagents?id=3
21:21:44 - HTTPHEADERS: GET, /meshagents?id=3, {"host":"xxxxxx.com:444","content-length":"0"}
21:21:44 - DISPATCH: DispatchEvent, ["node//cYxZCz5meq0ak2QlozF$rF77WxPr52TjUwWPycgJhq$yHdHzQmBnTPeXrPkd2rPK","*","mesh//CncI2fMNzqWzkk6zxJh@d$uoBixV7wdOHtNrEb35xbqiMO0u@TKVmC9JOM6Z36Pj"]
21:21:44 - AGENTUPDATE: Sending agent update url: */meshagents?id=3
21:21:43 - AGENT: Updating core windows-recovery
`

**Comment by Allowee** [comment]
I think I have found the issue with the agent that could not auto-update.
in the console tab: "Self Update cannot continue, this agent is not an instance of (Mesh Agent)"

For some reason 4 meshagent.exe staid running, blocking the file for update. 

The crashed agent did not self-update yet, the file date is still at the install date, but not crashed again

**Comment by Extcee** [comment]
I'd like to note that I'm also having this issue.
