### ISSUE TITLE
Feature request - terminal shell permissions

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2446]
As #727 now permits various types of terminal shell capabilities, would it be possible to lock down who is able to perform what types of login shells? For example, there now appears to be three types of login shells under Terminal (available by right clicking on Terminal's **Connect** button itself):
1. Root Shell (default)
2. User Shell
3. Login Shell

It would be really helpful to restrict access to a specific type (eg Login Shell) by (for example) a user group.

Additionally, if possible, if a user only has access to one specific login shell type, could that be set as the default for the Connect button itself? That way, they just click on Connect and their default is set to (eg) Login Shell and not Root Shell

Lastly, I forget - did permissions ever get assign to user groups, or just device groups?

**Comment by Ylianst** [comment]
Yes. For Linux, you can change what terminal connections options that are available by adding this section in the domain section of the config.json:

```
"terminal": {
  "linuxshell": ["root","user","login"]
}
```

You can find this [setting in the schema here](https://github.com/Ylianst/MeshCentral/blob/1e6e3d8beb67f8d14a268893c73de9365fddaeff/meshcentral-config-schema.json#L438). Let me know if that works.

**Comment by D4V3M0NK** [comment]
Hey @Ylianst! You're supposed to be on holiday, young man!  

I'll check this out ...

**Comment by D4V3M0NK** [comment]
Thanks to you both @Ylianst and @krayon007 
That ... is a thing of beauty, right there...
