### ISSUE TITLE
Agent Liks

### ISSUE THREAD

**Issue by Fredoberti11** [Ylianst/MeshCentral#2448]
Hello,
is it possible to generate agent installation links with automatic detection of the type of PC and their operating system?

**Comment by VINISHVV** [comment]
@Fredoberti11 

I don't confirm whether you are asking for this.

You can create agent invite link by insert below command in domain section, and restart your server,

"agentInviteCodes": true,

Once its activated you just add the Invite code to required Device Group.

![image](https://user-images.githubusercontent.com/65057910/112968772-3b287480-916a-11eb-9d8b-9ae0544367f2.png)


If the above 2 process completed Please visit https://yourdomain.com/invite and enter the code.

![image]https://user-images.githubusercontent.com/1319013/76880778-69743400-6835-11ea-9015-eab7a71313ad.png)

**Comment by Fredoberti11** [comment]
Hello VINISHVV,
I agree with this, but there is no automatic operating system detection that would enable the download of the correct agent by default (Windows, Mac OS, ...)

**Comment by Mfinadmin** [comment]
@Fredoberti11 - yes you are correct.

**Comment by krayon007** [comment]
> Hello VINISHVV,
> I agree with this, but there is no automatic operating system detection that would enable the download of the correct agent by default (Windows, Mac OS, ...)

@Ylianst can chime in, as normally it would be done by looking at the browser user-agent. With that being said, personally, I can't stand installers that do this, because there are lots of times when I'm trying to download an installer for an offline install on a different platform. Also, there is quite a laundry list of user-agents that are advertised, and it gets even more complicated with browsers that support spoofing other user-agents, etc.

**Comment by krayon007** [comment]
Also, I just looked at what Safari sent in the User-Agent field, it looks like Safari on my M1 mac is incorrectly reporting itself as an Intel Mac, in the user-agent field. So that would be problematic as well...

**Comment by Ylianst** [comment]
The original post is low quality, bad title and the request is not clear. As @VINISHVV pointed out, you can create a agent invite code and the correct tab should be selected automatically depending on the browser user agent. I am going to close this issue. Please open a new issue and use a correct title and be specific with the request. Thanks.
