### ISSUE TITLE
Server trace not correct when clicking lines

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2449]
When you click on a line in the server trace window it will only display line 0 and line 2
![image](https://user-images.githubusercontent.com/55733884/112985345-58f0dc00-9160-11eb-9f92-93a95b18d202.png)

This seems to be because of this line.
https://github.com/Ylianst/MeshCentral/blob/master/views/default.handlebars#L14261
typo j instead of i in the onclick event

**Comment by Ylianst** [comment]
Thanks for reporting this. Just made your fix in GitHub, will be in MeshCentral v0.8.2 when it's next published.
