### ISSUE TITLE
Repush Agent looses AMT Credentials

### ISSUE THREAD

**Issue by Extcee** [Ylianst/MeshCentral#2450]
Hello :)
I've re-pushed the agent to a number of clients, however these used the Fully Automatic AMT policy when they first connected, and it seems that their credentials are no longer stored (I'm pretty certain they exist in the amtactivation.log file though)
`Activated ACM, v11.8.82, No Credentials Edit Intel® AMT credentials`
Is there any possibility or upcoming feature where Mesh can read this file and pre-populate the credential for a previously activated system, or is the only way to enter each credential manually?

**Comment by Ylianst** [comment]
I will work on a fix for this in the coming week. When Intel AMT is activated with "Fully Automatic", a random password is used and that password is stored in the "amtactivation.log" file in "meshcentral-data". When re-installing agents, I should be able to get the old AMT password from that file and automatically use it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.3 with a fix for this. MeshCentral will now look at current device AMT password, password in the AMT policy, passwords in the config.json and 3 last passwords that where given to that Intel AMT UUID and create a unique ordered list and try them one-by-one at 20 second internal. It will also save any newly discovered passwords into the amtactivation.log file with the UUID of the device.

As a result of this, you should be able to reformat and re-install an agent on a device and MeshCentral will auto-recover the Intel AMT password and get you back on fully automatically. This is a super valuable feature in my view. Let me know if it works for you.

![MC2-AmtPasswords](https://user-images.githubusercontent.com/1319013/113765490-30716080-96d1-11eb-8119-16e33c47e675.png)

**Comment by Extcee** [comment]
Will it only do this on new agent re-installs, or will it actively seek devices with no credentials from these sources?

**Comment by Ylianst** [comment]
It will do this on existing devices. On server start, it will scan your existing amtactivation.log file in the "meshcentral-data" folder, find all the previous Intel AMT passwords and use them if a device has an unknown Intel AMT password. Let me know if it works.

**Comment by Extcee** [comment]
Looks to be working, thank you so much Ylian!
