### ISSUE TITLE
Add A generic Server ( Without Agent)

### ISSUE THREAD

**Issue by eldadh** [Ylianst/MeshCentral#2452]
Hey Guys'
since you added RDP, 
will it be possible to add a generic "Agent-less computer/server 
and access it in RDP directly without installing an agent? 
eldadh

**Comment by Ylianst** [comment]
Hi. This is a low quality post with a poor title and the request is not clear. I imagine the request it for performing RDP on the local network to other devices? That would only work if MeshCentral is in LAN mode. I will close this issue. You can open a new more specific request if you like.
