### ISSUE TITLE
Question: Custom UI Buttons Info/Howto

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2455]
Continuation of [Issue #1481](https://github.com/Ylianst/MeshCentral/issues/1481). Was playing around with the custom buttons, and it made me wonder if any other actions are supported besides "event" and ""dialog:". A button which could perform other MeshCentral actions such as downloading a shared file, or opening an important MCRouter link could be very useful. Is this possible, or are the "customui" actions separate from how the rest of the the web portal works?

**Comment by Ylianst** [comment]
There are currently no other actions. This said, you can use meshctrl.js to listen to server events and use that to trigger your own server side actions. I know of people that do this and it's pretty powerful. When clicking on a custom action, you cause the server to send out an event internally that meshctrl.js can receive, you can then initiate your own actions. Hope that helps.

**Comment by jsastriawan** [comment]
To add to Ylian's response, if you want to take action on event, you can monitor control.ashx websocket. Most of the action can also be done by sending JSON command over that channel.

**Comment by Ylianst** [comment]
You are exactly right, meshctrl.js connects to control.ashx to send commands and get responses and events.

**Comment by smartekIT** [comment]
> This said, you can use meshctrl.js to listen to server events

not sure how to use meshctrl.js to listen to server events, any example please?

**Comment by smartekIT** [comment]
@VINISHVV thanks for pointing out. but going through the docs there i couldn't see any example of meshctrl.js listening to events in real time. to be honest when i read up that to know what commands and actions we could learn we need to make meshctrl.js listen to server events and learn from the outcome i thought it's a command we give to the file so it acts as an interceptor to show what commands and actions been given to server when we use the GUI if that make sense to you. maybe i was wrong and misunderstood you guys.

**Comment by Ylianst** [comment]
The command to listen to events using meshctrl.js is:

```
node node_modules/meshcentral/meshctrl showevents
```

This command will not exit unless you stop the process or use CTRL-C. Once running it displays all server events that you can receive for the account your using to login meshctrl with.

**Comment by smartekIT** [comment]
man your work is really impressive 🥇 thanks heaps

**Comment by MatinatorX** [comment]
Thanks for the info! It's probably going to take me a bit to figure this out, so closing this issue.
