### ISSUE TITLE
Previous AMT Client not showing AMT Options

### ISSUE THREAD

**Issue by Extcee** [Ylianst/MeshCentral#2456]
Hello
Wondering if you can help at all?
I've got a client that originally connected with ACM activation, however I had to swap the motherboard as it died a death. I fired up the client and decided to re-install the OS cleanly and now can't get any of the Intel ME options to show on the home page for the device.
I've wiped out MBEX multiple times, re-installed the OS multiple times and triple checked I've got latest BIOS and Intel Management Engine installed.. Client is on Windows 10 20H2.
I've manually provisioned via USB key, issued the meshcmd amtconfig command and nothing seems to work.
I did some Googling and saw that maybe its because it has a previously known unique SMBios UUID (or something similar) from a previously connected client.
Anyone got any tricks that I am missing in getting the ME status to show on this one?

```
C:\meshagent>meshcmd amtinfo
Intel SM v9.1.45, pre-provisioning state.
Wired Enabled, DHCP, xx:xx:6x:Bx:xA:xx
Trusted DNS suffix: rootcert.meshcentral.com
Connection Status: Outside, CIRA: Disconnected.

C:\meshagent>meshcmd AmtVersions
BIOS Version = A22
Flash = 9.1.45
Netstack = 9.1.45
AMTApps = 9.1.45
AMT = 9.1.45
Sku = 16 (ISM)
VendorID = 8086
Build Number = 3000
Recovery Version = 9.1.45
Recovery Build Num = 3000
Legacy Mode = False'
```
Just to note I can access amt via the http://ip-of-device:16992 & Intel ME software is properly installed.

Thanks :)

**Comment by Scaff31** [comment]
Hello,

I have the same problem, after multiple research and attempt my problem comes from the fact that amt and the MPS server do not communicate.

I can access my MPS on port 4433

```
MeshCentral MPS server.
Intel® AMT computers should connect here.
```

But in my amtinfo

```
C:\>meshcmd amtinfo
Intel AMT v14.0.39, activated in Client Control Mode (CCM).
Wired Enabled, DHCP, A4:BB:6D:D8:C4:C1
Connection Status: Outside, CIRA: Connecting to mesh.mycompany.com, Periodic.
```

No more info for the moment I'm still looking for a solution
