### ISSUE TITLE
Filter / search field in device list doesn't filter group name

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2457]
Hi,
When using the filter / search field in device list page to search for a specific group name it doesn't work, but it works if we search for a device name instead. is this normal behaviour or bug? Thanks

**Comment by VINISHVV** [comment]
@smartekIT  please try below search condition. 

Group:Name of the group

**Comment by smartekIT** [comment]
Thanks it works, i thought it works like searching the devices without putting "group:" in front of it. i will make sure i remember that.

**Comment by Ylianst** [comment]
You can use `g:` or `group:`, both do the same.
