### ISSUE TITLE
[Feature] Server CPU load on Windows

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2459]
In node there is no cpu load implementation for Windows. (os.loadavg)
I just found an alternative or maybe using the wmic command could help as well.

Would be realy nice to see the load on the server when running on Windows.

https://github.com/fider/loadavg-windows

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.1 and added "loadavg-windows". Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/113469891-0b959880-9406-11eb-9143-0310107dd60b.png)

**Comment by Allowee** [comment]
Awesome thank you!!
