### ISSUE TITLE
Upgraded to Fedora 30 and lost MongoDB

### ISSUE THREAD

**Issue by sorvani** [Ylianst/MeshCentral#246]
So, I run MC on Fedora with MongoDB. Has been running since Fedora 29. and used the native mongo from Fedora.

Fedora removed MongoDB because of the license change, so when I upgraded it was gone.

What is the best way to switch my broken install to the NeDB?

**Comment by Ylianst** [comment]
Good question. You now have old MongoDB files with your database and you can't read them? MeshCentral can't read MongoDB files directly, so I have no way to convert them to NeDB. Probably the best is to install MongoDB on Fedora 30 ([instructions](https://computingforgeeks.com/installing-mongodb-on-centos-fedora/)) and then continue running with MongoDB.

At that point, if you want to switch to NeDB, run "node node_modules/meshcentral --dbexport". Go in the config file and remove the "mongodb" line in settings when run "node node_modules/meshcentral --dbimport". This will export you DB to a .json file and re-import it into NeDB.

**Comment by sorvani** [comment]
That did it.
