### ISSUE TITLE
Agent microstack stuck

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2464]
After updating to the latest version today the one pc I can only access with mesh had failed to reconnect.
It came back online 20 minutes later, luckily.

running the 64bit agent, all other agents are fine.
Tried a service restart to re-check for this  and it came back immediately.

I have a dumpfille availble, I can mail it

[2021-04-03 01:05:09 PM] SelfUpdate -> Current Version: 43c5f2d1b57a9f477d3afec13e2873ed19bfd573
[2021-04-03 01:05:09 PM] SelfUpdate -> Updating and restarting service...
[2021-04-03 01:25:11 PM] Microstack STUCK: @ [FuncAddr: 0x6E40F53F01000000]
[FuncAddr: 0xDAAFF53F01000000]
[FuncAddr: 0x55B2F53F01000000]
[FuncAddr: 0xE2BBF53F01000000]
[FuncAddr: 0x87B4F53F01000000]
[FuncAddr: 0xA2DEF03F01000000]
[FuncAddr: 0xEC37F23F01000000]
[FuncAddr: 0x6B99EF3F01000000]
[FuncAddr: 0x2693ED3F01000000]
[FuncAddr: 0xC09CEF3F01000000]
[FuncAddr: 0xA993ED3F01000000]
[FuncAddr: 0x9158F13F01000000]
[FuncAddr: 0x6B99EF3F01000000]
[FuncAddr: 0x2693ED3F01000000]
[FuncAddr: 0xC09CEF3F01000000]
[FuncAddr: 0xA993ED3F01000000]
[FuncAddr: 0x6267F13F01000000]
[FuncAddr: 0x6B99EF3F01000000]
[FuncAddr: 0xCA17EF3F01000000]
[FuncAddr: 0xC09CEF3F01000000]
[FuncAddr: 0x2318EF3F01000000]
[FuncAddr: 0xEC11EF3F01000000]
[FuncAddr: 0x7E3FF23F01000000]
[FuncAddr: 0xF340EC3F01000000]
[FuncAddr: 0xC65EEC3F01000000]
[FuncAddr: 0x056BEC3F01000000]
[FuncAddr: 0xB21FF63F01000000]
[FuncAddr: 0x2522F63F01000000]
[FuncAddr: 0x0B05F53F01000000]
[FuncAddr: 0xC70FF53F01000000]
[FuncAddr: 0x7E77F53F01000000]
[FuncAddr: 0x92C4EC3F01000000]
[FuncAddr: 0xA817F73F01000000]
[RegisterServiceCtrlHandlerExA]
[BaseThreadInitThunk]
[RtlUserThreadStart]

[2021-04-03 01:28:16 PM] FATAL EXCEPTION [MeshAgent_3BCE6DD27B571420.exe] @ [FuncAddr: 0x000000013f3ae25b / BaseAddr: 0x000000013f264700 / Delta: -1350491]

**Comment by krayon007** [comment]
I'll take a look next week after my kids spring break. Looks like you ran into the built watchdog. I made it so that it can detect if the main event loop gets deadlocked. I made it abort after 10-15 minutes, I forget the exact number. 

When it came back, was it running the updated agent?

**Comment by Allowee** [comment]
Just checked, the agent timestamp is 01:05
It seems that it  updated, restarted and got stuck.
The manual service restart I did was at 1:28
