### ISSUE TITLE
Desktop connectbar, deskarea1, changed to 24px

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2465]
I was just wondering, the Desktop top bar (ccs deskarea1) with the Connect button has been changed from a height of 20px to 24px.

In my setup I cannot see why this has been changed, it now looks a bit strange and wrong.

**Comment by Ylianst** [comment]
Can you send a screenshot? There has not been any recent changes to the desktop privacy bar, but I imagine the DPI or font size settings of the OS would make a difference. Also, not sure what OS you are using.

**Comment by Allowee** [comment]
The change was in this commit
https://github.com/Ylianst/MeshCentral/commit/7bf0681f5be588d26688a0517e91a6ea6282d967#diff-b3999fbcfceec13796d145e3e7b8c4c17c2cecdf9bea23e3380e121f6da26285

Screenshots of the new and old

![Screenshot_20210404-093107](https://user-images.githubusercontent.com/55733884/113501875-be5e1780-9528-11eb-825a-4b8652e18c7d.png)
![Screenshot_20210404-093626](https://user-images.githubusercontent.com/55733884/113501936-45ab8b00-9529-11eb-8621-206661d6cfa7.png)

**Comment by Ylianst** [comment]
Oh! I get it now. There are cases where no buttons are displayed and the text would mess up. I will fix that.

**Comment by Ylianst** [comment]
Should be fixed in v0.8.2, let me know if it's ok.

**Comment by Allowee** [comment]
Perfect the min-height seems to be ok for me.
