### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2466]
Dear Ylian.  We are currently experiencing minor problems with the work of the Desktop tab.  As it seems to us earlier, there was a button to expand to full screen, but then we did not actively use MC2 yet, and it seemed to us that after some update this button disappeared.  Although we may be wrong.  but then I would like to add such a button to the interface so that when it is pressed, the remote desktop expands to full screen, this is convenient for administration

**Comment by PetieM** [comment]
If you hold Shift and click the full screen button (four arrows at the top right of the desktop view), you'll get a browser full screen window with just a small bar at the top and bottom for controls like disconnect and key combination sending.

**Comment by AntonAndreevichMoroz** [comment]
Maybe we're doing something wrong. but we don't have this button.
![image](https://user-images.githubusercontent.com/51225180/113491009-61397600-94d6-11eb-8ba5-74638cfc9b10.png)

**Comment by PetieM** [comment]
Oh, strange - you're missing the entire top bar there. Mine looks like this:

<img width="1920" alt="Screen Shot 2021-04-03 at 2 47 28 PM" src="https://user-images.githubusercontent.com/16453878/113491123-8f459880-948b-11eb-8002-c1e481ddc690.png">

**Comment by Ylianst** [comment]
The fullscreen button is typically located here.

![image](https://user-images.githubusercontent.com/1319013/113494734-1c92e800-94a0-11eb-9bbd-2ad83ce8bb6a.png)

It seems you have the part of the web page removed. I can replicate the same situation by adding `&hide=8` to the URL or you can go in the config.json and add `"hide": 8` in the domain section of the config.json.

![image](https://user-images.githubusercontent.com/1319013/113494776-7a273480-94a0-11eb-8ac4-b97f8a258ff9.png)

Can you check if you have this value set? Thanks.

**Comment by AntonAndreevichMoroz** [comment]
Oh. Really. I apologize for such simple questions and that you have to be distracted by them. I forgot I was working with this parameter.

**Comment by DaanSelen** [comment]
A question regarding this. I click the beforementioned Full-Screen button, but it becomes full screen up until the bookmarks. Can I make this use the full... screen?

**Comment by si458** [comment]
@DaanSelen make sure u use chrome/edge and when u click the fullscreen button it should go fullscreen and cover your browser (i will double check the code shortly as I could be wrong haha)

**Comment by si458** [comment]
@DaanSelen hold the SHIFT KEY then click the fullscreen icon, just checked code again
(also hover over icon and it will show a tooltip - `full screen. hold shift to browser full screen`)

**Comment by DaanSelen** [comment]
Ah okay, that clears that up. Thanks!
