### ISSUE TITLE
meshrouter default text field after staring program

### ISSUE THREAD

**Issue by bbrendon** [Ylianst/MeshCentral#2467]
for the lazy people like me. currently the default field when starting the program is the "Server" field. The username and server fields are both auto-populated.

Can't the default field then be password so I don't have to press tab twice? :)

**Comment by Ylianst** [comment]
Good idea. You can download the updated [MeshCentral Router for Windows here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). It will also be in the next version of MeshCentral v0.8.2. Let me know if that works, if it does, please close the issue.

**Comment by bbrendon** [comment]
looks like it works! thanks!
