### ISSUE TITLE
Feature Request: Alerts

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#247]
Cannot display alerts (messages) anymore on remote clients like in MeshCentral v1. Please restore this functionality. Thank you.

**Comment by Ylianst** [comment]
Bryan is coming out with a new version of the MeshAgent that can display message box prompts on Windows, Linux and MacOS. Once that is released, we can add this.

**Comment by FilGov** [comment]
Any progress? Been 3 months and the only difference we noticed is all of a sudden no devices connect and we must reinstall the agent everywhere.

**Comment by FilGov** [comment]
Anyone?

**Comment by FilGov** [comment]
Was this added already?

**Comment by Ylianst** [comment]
There is a toast notification button on the bottom right that will display a message on the remote side. Is this ok? It's not exactly the same as the old MeshCentral since it's a toast notification.

![MC2-DeviceToasts](https://user-images.githubusercontent.com/1319013/71535891-97914a00-28be-11ea-8d9e-637e1a956d51.png)

**Comment by FilGov** [comment]
I’m afraid unfortunately not, it’s easily missed (displays only briefly, then vanishes to action center, which our users virtually never open) and it doesn’t work if the session is locked anyway (we use it to let users know when we’re done and they can sign in again). Please restore the alert functionality from the old MeshCentral. Thank you. From: Ylian Saint-HilaireSent: 27 December 2019 23:36To: Ylianst/MeshCentralCc: FilGov; AuthorSubject: Re: [Ylianst/MeshCentral] Feature Request: Alerts (#247) There is a toast notification button on the bottom right that will display a message on the remote side. Is this ok? It's not exactly the same as the old MeshCentral since it's a toast notification.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FilGov** [comment]
I’m afraid unfortunately not, it’s easily missed (displays only briefly, then vanishes to action center, which our users virtually never open) and it doesn’t work if the session is locked anyway (we use it to let users know when we’re done and they can sign in again). Please restore the alert functionality from the old MeshCentral. Thank you.

**Comment by MailYouLater** [comment]
As someone who is not that familiar with old MeshCentral, what did these alerts you're requesting look like?

**Comment by FilGov** [comment]
Like a simple pop-up window in the middle of the screen.

**Comment by FilGov** [comment]
Any progress?

**Comment by krayon007** [comment]
The functionality in the agent is there, as that's what user consent uses. It should be easy enough to add in generic support. I'll add a console command that allows you to do that in a generic fashion.

**Comment by FilGov** [comment]
It'd be nice if it was just a button like before, but that's certainly better than nothing. Thank you very much.

**Comment by SomeGuru** [comment]
@FilGov 

This is enabled now in the latest server and agent releases is it not? Can you confirm and close on this issue if it is?

**Comment by FilGov** [comment]
I'm afraid unfortunately not, sorry, nothing changed, using the toast notification button still only displays a toast notification only visible (for a few seconds) if the user is logged in looking at the screen at the time and the session is unlocked.

**Comment by krayon007** [comment]
Have you tried the alert console command? I think this is more along the lines of what you were looking for?

**Comment by FilGov** [comment]
Did now. Yes, this is more along the lines of what I was looking for, thank you, but it unfortunately doesn't work on the lock screen like with MeshCentral v1.

**Comment by krayon007** [comment]
Were you using the same version of Windows with meshv1? I only ask, becuase in a previous life I found that starting with Windows 8, you couldn't draw anything on the lock screen unless you were a credential provider. I can certainly look into seeing if something changed for Windows 10, and see if I can find something else to draw to the lockscreen...

**Comment by FilGov** [comment]
Yeah, Windows 10. Thank you.

**Comment by krayon007** [comment]
Ok, I found a way to get the alert to show on the lockscreen. The only caveat, is that (On Windows 10 at least), you must swipe away the lockscreen to reveal the login prompt, to see the alert. (Windows has this thing called a "shade", that covers the entire lockscreen. You must swipe away the shade to see the login screen, which is where the alert will be.

I'll add this ability so that if the desktop is locked or nobody is logged in, alerts will go to the login screen.

**Comment by FilGov** [comment]
Thank you.

**Comment by krayon007** [comment]
Ok, found a way to get it to work on Linux too, tho on Linux it displays on the login screen, not the lockscreen...

**Comment by krayon007** [comment]
I'll probably make this windows only, as I did testing with different linux distros, and it seems the method I was using only works on older linux distros.
