### ISSUE TITLE
Export option Modify

### ISSUE THREAD

**Issue by AMI231187** [Ylianst/MeshCentral#2472]
Dear Meshcentral Team,

the current device export device info contains basic details only.  Is it possible to modify the same for getting below information's. 

Host Name
IP
Local IP
osdesc
Architecture
Mesh Agent Ver
Compile time / Agent Version
Ethernet Mac
BIOS Vendor
Motherboard - Vendor
Motherboard-Name	
Motherboard-Serial
Memory Capacity / Speed
Storage Capacity
Boot Time

**Comment by VINISHVV** [comment]
@AMI231187 duplicate task #2438

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.4 with option for extra export details... feedback welcome.

![image](https://user-images.githubusercontent.com/1319013/113802206-266e5280-970f-11eb-956c-32b0841287b2.png)

**Comment by AMI231187** [comment]
Wow !!!

Thanks Ylianst for the quick response.

Can you please include below fields in the same reports.

Memory Capacity / Speed
Storage Capacity
Free storage
Boot Time

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
i can add boottime to the report for you (only if its windows for the moment)
i can also add the storage device name and storage size for you too!

the report already shows you the total memory of your machine

we would be able to tell you free storage space as that could be different from windows/linux/etc...

**Comment by si458** [comment]
closing as stale
