### ISSUE TITLE
Successful login returns to login page

### ISSUE THREAD

**Issue by Chluz** [Ylianst/MeshCentral#2473]
Hi ,

This is really a great piece of software; as is the responsibility of our generation, I help all of my family with their issues through this. It's a lifesaver, saves me loads of time !

I've just been testing the 0.8.1 and 0.8.2 updates. 
In those, it seems that if I successfully login, I immediately get brought back to the login page. 
If I had a session cooky in browser and I do not need to login, everything works as expected. 

Reverting to 0.8.0 fixes this, and I've verifies this for SSO with saml and standard login. 

I have not seen anything in the general syslog logs indicating an issue, I could dig if needed. 

Thanks again !

**Comment by Jamesits** [comment]
We encountered exactly this situation too on `0.8.2`. Temporarily reverted to `0.7.89`.

Error log (not happening every time, but I guess it is related):
```
-------- 4/5/2021, 6:10:24 AM ---- 0.8.2 --------

TokenError: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
Trace ID: <redacted>
Correlation ID: <redacted>
Timestamp: 2021-04-05 06:10:24Z
    at AzureOAuth2.OAuth2Strategy.parseErrorResponse (/srv/meshcentral2/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at AzureOAuth2.OAuth2Strategy._createOAuthError (/srv/meshcentral2/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /srv/meshcentral2/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /srv/meshcentral2/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/srv/meshcentral2/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/srv/meshcentral2/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

And the `/auth-azure-callback` response (the 2nd one) doesn't have `Set-Cookie` HTTP header comparing to a successful login.

**Comment by nroach44** [comment]
I can confirm this, but only for TOTP accounts, or where a password reset is required (a normal local account without TOTP or "require reset on login" works fine).

**Comment by Chluz** [comment]
Hi, tested SSO login with 0.8.12, seems to work as expected. 
Bug fixed ?
