### ISSUE TITLE
Mesh Router for Linux?

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#2475]
Is there a mesh router for linux?  Suddenly that's looking like something I could use.

Thanks!
Shane

**Comment by drnikcuk** [comment]
No router client exists for Linux, however if you are looking to use it for relays then MeshCMD can do that for you.

https://info.meshcentral.com/downloads/MeshCmd/MeshCmdUserGuide.pdf - Section 3 has all the info on how to do it.

**Comment by Ylianst** [comment]
Someone did make a MeshCentral Router that works on [Linux here](https://github.com/jsastriawan/mc2router-electron), but I have never tried it. Indeed, MeshCMD will perform command line TCP port mappings on all platforms that the MeshAgent runs on.

To get started with MeshCMD routing, click on a device and hit the "MeshCmd" link and download the binary and meshaction.txt file. Put them in the same folder and run MeshCmd. You can edit the meshaction.txt file to map to the port you want, add you password, etc.

![image](https://user-images.githubusercontent.com/1319013/113744027-29d6ef00-96b9-11eb-9e3e-ee9e382e1640.png)

The meshaction.txt file is the same as running MeshCMD with lots of command list switches. Let me know if that works.

**Comment by jsastriawan** [comment]
Thanks @ylianst for linking mc2router-electron. Basically it is a desktop version of MC2 with configurable application tunneling. I have not specifically tested the app on Linux but it should work because it has no platform specific code.

**Comment by Ylianst** [comment]
I just noticed that @jsastriawan has a blog about this version of the [MeshCentral Router here](https://sastriawan.blogspot.com/2020/01/mc2router-simple-yet-versatile-tool-to.html).

**Comment by yomono** [comment]
I just want to add to this that I've been using MeshCentral Router on Linux with Wine, and it works just fine.
Port Map, Relay Map, Files, remote control... even putty! (you can download putty.exe and set the path).
The only one that didn't work was RDP. I assume is looking for the MSTSC.EXE and it couldn't find it (And I don't want to know what kind of mess it would be open an rdp connection via Wine 😮 )

> I just noticed that @jsastriawan has a blog about this version of the [MeshCentral Router here](https://sastriawan.blogspot.com/2020/01/mc2router-simple-yet-versatile-tool-to.html).
> 
> I need to find an easy way to deploy GUI tools on Linux.

For me, Go, being incredible portable and multiplatform is a good choise. For GUI, there are several projects (Go + SciterJS was the way to go for me. Sciter is a 15 years old software, very mature and production ready)

**Comment by falpi** [comment]
Hi everyone... just to let you know that I've completed a port of MeshCentral Router to .NET8, in console mode, and it can now run anywhere, including Linux and macOS: https://github.com/falpi/MeshTunnel
