### ISSUE TITLE
Feature Request: Support for computers without GUI / Terminal only client

### ISSUE THREAD

**Issue by lulu3000** [Ylianst/MeshCentral#2477]
Hello
it would be nice to have a client for (Unix) servers without GUI, just with the Terminal tab. Of course any SSH program would to the same thing, but it would be very practical to have this in the MeshCentral togehter with all the other machines.

**Comment by Allowee** [comment]
Have you tried installing the Linux agent and it did not work?

All my headless servers and pi's run without Desktop and display the Terminal tab. Running just like a SSH session

**Comment by lulu3000** [comment]
Oh in am so sorry, I didn't even try it. I did not know that this is possible. Thank you.
