### ISSUE TITLE
Not usable on ipad, because Keyboard does not come up - Mobile View possible?

### ISSUE THREAD

**Issue by lulu3000** [Ylianst/MeshCentral#2479]
Hello

The central can not really be used on an ipad, because you get the desktop view and the keyboard does not come up - this is clear, because IOS can not know what I am doing on the remote desktop. Maybe it would be realtively easy to enable mobile view on the ipad? Or ist it already possible to force mobile view?

Thanks for your great work!!!!

Lulu

**Comment by Extcee** [comment]
Press the AA in the top left hand of the search bar in safari and select Request Mobile Site.

**Comment by lulu3000** [comment]
Oh - I dont't have a search bar in my safari on the ipad, and no AA. I guess the OS is too old (iOS 12.5.2). I leave it open for the moment, maybe somebody knows something about it.
Thank you!

**Comment by lulu3000** [comment]
Update: I GET the mobile mode in both Safari and Chrome. Only in Firefox I get the desktop version - which is good to download the client. Everything ist fine!
