### ISSUE TITLE
Public link to download the agent

### ISSUE THREAD

**Issue by elric72** [Ylianst/MeshCentral#248]
Hello,

I have a quick question, is the a way to publish a public link to share the Meshcentral Agent ?
I only able to download the agent if I am connected to the web interface.
If it is the case, it possible to protect it with a password ?

Thank you in advance for your feedback
Regards
David

**Comment by merlinweb** [comment]
You can put agent in  "my files", public folder:
![image](https://user-images.githubusercontent.com/48550288/58431170-e074ec00-80ac-11e9-8c4a-0ee7e9e79111.png)

Files should be public available, but I think it's not a best practice for security...

Cheers

Merlinweb

**Comment by Ylianst** [comment]
That is the correct answer. I would like to work on improving the server files feature in the future, but for now just put the files in need shared in the public folder.

**Comment by elric72** [comment]
Ok I will try as you suggested.
Thank you for your answers

**Comment by Ylianst** [comment]
Ok, will close this one. If there is more of this, please feel free to open again.
