### ISSUE TITLE
Nodes and Events not Loading when using MySQL

### ISSUE THREAD

**Issue by gankur** [Ylianst/MeshCentral#2480]
Hi there,

Facing issue when configure MySQL database in MeshCentral. Its not loading nodes and events from the database.
I tried using meshctrl.js commands as well, just showing None.

Please help over this.

Thanks & Regards
Ankur Gupta
![image](https://user-images.githubusercontent.com/27963136/113723703-3dad4000-970f-11eb-8514-726f23ca2226.png)

**Comment by VINISHVV** [comment]
@gankur - I think this issue is resolved in Meshcentral 0.8.0,

If you are trying in old versions then please update to current version.

Reference #2423

**Comment by Ylianst** [comment]
I don't think #2423 fix will have an impact on this one. The issue post has very little information. What server versions are you using? Are you using any plug-ins?

The only help I can provide is to stop the server and export the database using:

```
node node_modules/meshcentral --dbexport myserver.json
```

Then, you can take a look at the file to make sure there are actually entries in it. [If you want to send me that file privately](https://www.meshcommander.com/contact-information), I can take a look at it.

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.22 and use node 18 or above,
if issue persists, please reply back
