### ISSUE TITLE
Change password dialog should include existing password field

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2481]
Using MC2 v0.8.0, when changing my own password, two fields are present labeled "Password".  IMHO there should be three fields:

1. Existing password
2. New password
3. Confirm new password

**Comment by Ylianst** [comment]
Is that not exactly what MeshCentral has?

![image](https://user-images.githubusercontent.com/1319013/113736998-7539cf00-96b2-11eb-830e-7d663d466c2c.png)

**Comment by Ylianst** [comment]
Your screenshot is account password change from the administrator. That it the one you get in "My Users" tab. Administrators don't know the previous password of any account, so I can't expect them to enter the old one.

**Comment by D4V3M0NK** [comment]
100% correct, apologies for the confusion
