### ISSUE TITLE
MeshRouter and issues/differences with group and user assigned permissions

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#2485]
I have a user that uses RDP through MeshRouter to connect to a Mesh managed VM. When I have him in a group with the permissions of
       Control (No Terminal, No Files, No AMT)
He gets in just fine. 

But if I take him out of the group, meaning he doesn't exist in any group, then go to the individual agent and assign those same permissions above, he can't get in. Not to RDP, noVNC or Web-RDP. Moving him back to the group resolves the issues. 

This happens if he launches the RDP session from the meshcental website or by trying to open just the standalone MeshRouter.exe file. 

One more thing that is interesting, when he is launching the .exe and is not in a group but only assigned permissions on the one VM, he gets the error he is giving an invalid username and password, which I know isn't the case. 

Happy to do any testing needed, and hopefully I described the issue well. I cannot get the logs from his machine (its a contractor situation) but if I am told where to look, I can duplicate the issue and capture logs there.

**Comment by yomono** [comment]
When you say "Groups" you mean User groups, or devices groups?
If you mean User groups, you should check if the individual user permissions allow him to access the device you want to

If you mean you take him out from the device group where the target device is, then what you are describing is the expected behavior

**Comment by githubbiswb** [comment]
Yep, I have a device group of a single VM, and in that a user has the above mentioned permissions. That all works as expected. 

I have another device group that contains all VMs, of which the user only needs access to one. So the user doesn't have permissions in this superset device group, but only to that one asset. This is when it doesn't work correctly. Even though the user is granted specific permissions to that asset

**Comment by yomono** [comment]
I can confirm that the regular "Desktop" control works if I assign permissions over a single Agent, even if I don't have permissions over the entire group.
Sadly I'm using Linux and I have no easy way to try this over RDP since the option is just not there for me

**Comment by githubbiswb** [comment]
Yep, totally agreed, the regular one does work as expected, which is why I made the assumption the RDP options would also work like this and made the change and then found it didn't work for RDP, or noVNC or Web-RDP

**Comment by Ylianst** [comment]
Looking into this now. I think what you mean to indicate is that the MeshCentral Router links don't work when the permissions are assigned for an individual device.

![image](https://user-images.githubusercontent.com/1319013/114065826-ee225d80-984f-11eb-8801-d8d23fc1166d.png)

**Comment by Ylianst** [comment]
Found the problem and fixed it. This will be in MeshCentral v0.8.6 when it's next published. Once released, please let me know if it works.

**Comment by githubbiswb** [comment]
Seriously, you are the best, understood my poor explanation and fixed it, well done ;) I will test when the new release comes out and update and close accordingly.

**Comment by yomono** [comment]
The best, indeed

**Comment by githubbiswb** [comment]
Looks perfect, thank you again!
