### ISSUE TITLE
[Feature Request] - E-mail and/or Browser notifications on event, per device configurable

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#2487]
It would be great (unless this already exists, and I haven't seen it) to be able to get notified if a device goes offline, rather than at an account level or group level. If there is a critical system I need to know about in a group, or, for example, I'm doing services, and waiting for a reboot that may take hours. It would be nice to get an e-mail if the system goes down and/or comes back online.

Ideally, we can get the same notifications that are available at the account level, but, at a device and even group level. During the Hafnium crisis a few weeks ago, we needed to make sure some systems came back up or didn't, but, since we had to do other tasks as well, we didn't want to keep watching the dashboards (and this way, with e-mail, we could also filter them or process them via other applications/alerting systems).

**Comment by yomono** [comment]
There is a similar request here: #2167

**Comment by si458** [comment]
this feature exists as of 2023
you can now set individual devices for notifications in your browser or using ur messaging method (discord, teams, email, etc)
