### ISSUE TITLE
Self Update failed

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#2489]
I've been having trouble with some devices not getting agent updates.  The end result being that the device is inaccessible via Mesh (the Desktop option is not even present and all other connection options are greyed out).  I just noticed, with version 0.8.4 (it may have been present in previous versions but I just now noticed it) that these errors are shown as a number next to the device name. 

The error I see when this happens is 'Self Update FAILED because the downloaded agent FAILED hash check'  It then has the URL to my MeshCentral site.  The final error being 'Self Update giving up, too many failures'.  

In this particular case it was on a desktop with a fresh install of Windows 10 version 20H2.  But the agent installer used was about a year old. Typically that wasn't ever an issue because it would just go out and download the current version and do a self update. But now I see that doesn't always work.   I've had other devices get stuck in the very same state- presumably for exactly the same reason.  
Is there any way to push a new version of the MeshAgent to the device when it's in this state- other than having direct access to the device itself?  This particular device is about an hour away from my office.  
Also, what is actually causing this issue?  I need to get it resolved so it never happens again.  I don't usually notice a device is in this state until I need to connect to it but then am unable to.  

![error](https://user-images.githubusercontent.com/48607498/113950187-bdeea680-97de-11eb-8502-5e46ed58dffa.JPG)

**Comment by Ylianst** [comment]
Hi. If you can cut & paste the URL used for the agent update and place it in a browser and see if you can download the agent correctly? If the URL is not correct, let me know and I can fix that.

In addition, you should be able to login to your server and access a URL like this: `https://server.meshcentral.com/meshagents`. It should give you a list of agents and download URL's. They should be the same URL that the agent is trying to update with. Let me know if these works or if the URL is different.

Next, we have two different agent update methods. If the agent is older than a few months back, we download using the URL. If it's a more recent agent we update using a server push. If you can install using a newer agent, the update method will be different and it may work.

If the URL is not correct, that would be the cause of the issue, but would love to get more data on that.

**Comment by PathfinderNetworks** [comment]
The URL contained in the error message does work. When I visit that URL it downloads the meshagent64.exe file.   If I visit the same URL with the ?id=4 it will display the list of agents like you mentioned. The URL for the 64bit Windows agent the device is trying to download for the self update is the same URL contained in that list.  
The agent that was used for the initial install is definitely an older one.  Probably about a year old as it is what they had available on the network share.  In the past there wasn't any issue with using an old agent installer as it would just update to the new version- so I didn't think twice about it during the install.

**Comment by Ylianst** [comment]
So, the URL works, but when the remote agent tries the URL it does not works? I guess the ultimate test would to be try the URL from the remote device. Another option you have it to run the agent update manually using the `agentupdate` command in the agent console like this:

![image](https://user-images.githubusercontent.com/1319013/114059663-72251700-9849-11eb-87c5-9e49f0517906.png)

It's always possible that there is a HTTP proxy in the way that is blocking the download, but you will need use the download URL on the remote device and check that.

If you can, do update the agent you use for initial install just to make it easy on the server. Let me know that you find.

**Comment by PathfinderNetworks** [comment]
I don't have physical access to the device because it's about an hour away.  But I tried using the AgentUpdate command.  I get the same error message.  It downloads the agent but it fails to install because it fails the hash check.  So I don't think it has anything to do with it not being able to download the file.  Why would the hash check be failing?

**Comment by Ylianst** [comment]
One cause of this would be that this specific device is behind an HTTP proxy that is denying the download and returning an error page instead. The error page is obviously not going to have the same hash as the agent and so, it fails. To check what is going on, you need to try to download using the URL on the remote device and see what gets downloaded. I am guessing you will get something different, but until you try it, not sure what you will find.

**Comment by b8two** [comment]
I find this an issue on Windows 7 32bit Devices.

It occured after upgrading from  1.0.24 to 1.0.85

My Work around is to connect to Files on the Recovery Core,
Change to the Mesh installation Directory C:\Program Files\Mesh Agent\

Upload the current Agent Installer.

Once Uploaded select the file and click rename, add a space then  **-install** to the end of the file name, then copy the filename with the -install part to clipboard then cancel the rename.
This ensures you have the correct spelling and the install command.

Change to connect to a Terminal Session.
by default you will be in the install folder, paste the clipboard contents, you will not understand what it responds with but press enter any way.

You'll start to see the installer text output, the Agent will disconnect and then reconnect and work as good a previously.
