### ISSUE TITLE
AutoBackup not dumping mongodb

### ISSUE THREAD

**Issue by ingzorrilla** [Ylianst/MeshCentral#2491]
Hi,

I'm attempting to set up my autoBackup and for some reason is just backing up the files and not the DB. Everything but that is working perfectly, even google backups, here the autoBackup part of my config.json. What am I doing wrong?

    "autoBackup": {
      "mongoDumpPath": "/usr/bin/mongodump",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 15,
      "zipPassword": "MySecretPassword",
      "backupPath": "/home/user/meshcentral-backup/",
      "googleDrive": {
        "folderName": "MeshCentral-Backups",
        "maxFiles": 30
      }
    },

**Comment by VINISHVV** [comment]
@ingzorrilla - Are you getting any error message like  **"WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed**" in my server -> General tab **or** in console while running autobackup command. 

Also Please confirm your meshcentral & Mongodb  versions

**Comment by yomono** [comment]
@VINISHVV That error you mention is for windows only (As far as I know)

@ingzorrilla you could try as VINISHVV said to do a "autobackup" command on the server console, so you can see the output in real time

**Comment by VINISHVV** [comment]
@yomono -  I have never tried MC in linux...
Thanks I will remember this always

**Comment by Ylianst** [comment]
With the latest version of MongoDB, the "mongodump" command now comes in a separate package. I think this is both on Window and Linux, so it's possible to see the "Unable to find mongodump" in both OS's (I think).

Anyway, if you see this error:

![image](https://user-images.githubusercontent.com/1319013/114061037-d3011f00-984a-11eb-8979-3e169f219753.png)

When you need to fix it by specifying the correct path to `mongodump` in the config.json like this:

```
    "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",     <------
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 3,
      "zipPassword": "test",
      "backupPath": "C:\\temp"
    },
```

This said, in the config.json above, the path is specified. You can also go in the "My Server" / "Console" tab and type "autobackup". This will trigger an immediate auto backup and may give more details as to what the problem is:

![image](https://user-images.githubusercontent.com/1319013/114061520-60dd0a00-984b-11eb-960e-b5348ebf56cb.png)

Let me know if you have more information.

**Comment by ingzorrilla** [comment]
@VINISHVV 
> @ingzorrilla - Are you getting any error message like **"WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed**" in my server -> General tab **or** in console while running autobackup command.
> 
> Also Please confirm your meshcentral & Mongodb versions

Yes I have this message on both My server General tab and when I check the status of Meshcentral service. 
MeshCentral = 0.7.95
mongod = 4.4.4
mongodump = 100.3.1

@yomono 
> @VINISHVV That error you mention is for windows only (As far as I know)

I have this "error" also and I'm running  Ubuntu 20.10.

> @ingzorrilla you could try as VINISHVV said to do a "autobackup" command on the server console, so you can see the output in real time

```
> autobackup

Starting auto-backup...
Auto-backup completed.
Attempting Google Drive upload...
Uploading to Google Drive...
Google Drive upload completed.
```

@Ylianst 
> I think this is both on Window and Linux, so it's possible to see the "Unable to find mongodump" in both OS's (I think).

I can definitely confirm that "Unable to find mongodump" is happening in Linux.

> When you need to fix it by specifying the correct path to `mongodump` in the config.json like this:

This example and all others seen on the internet only provide "mongoDumpPath" for windows, as you can see I tried to accommodate it for Linux and seems to be that is not working.

> This said, in the config.json above, the path is specified. You can also go in the "My Server" / "Console" tab and type "autobackup".

autobackup output posted above.

**Comment by yomono** [comment]
I did a "mongod --version" and I'm getting v3.6.8.
Ylian said that in the last version, mongodump comes in a separate package, so I assume that's why it works fine with me

**Comment by nzalev** [comment]
> @VINISHVV
> 
> > @ingzorrilla - Are you getting any error message like **"WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed**" in my server -> General tab **or** in console while running autobackup command.
> > Also Please confirm your meshcentral & Mongodb versions
> 
> Yes I have this message on both My server General tab and when I check the status of Meshcentral service.
> MeshCentral = 0.7.95
> mongod = 4.4.4
> mongodump = 100.3.1

When meshcentral starts, if you are using MongoDB, it will attempt to run mongdump. If the command fails (either an issue with mongodump, or the path to the executable is wrong), it will produce this warning. In vesrion 0.7.95, this warning would also be produced if you are running MongoDB on a remote server.

If you run `/usr/bin/mongodump` as your regular user, does it properly run? As your regular user, what is produced by the command `which mongodump`?

Are you running meshcentral as its own user? If you are, su to that user and run `which mongodump`. If this returns a valid path, you don't need to specify an absolute path in your config, just `mongodump`.

**Comment by VINISHVV** [comment]
@nzalev - I see the last PR related to the Auto backup issues. You have done a very Good Job !!!

@ingzorrilla   - I am running MC in Windows, So Please try the solution suggested by nzalev.

**Comment by ingzorrilla** [comment]
Hi all, 
Thank you very much for the support, here are my findings.
@nzalev

- Confirming that I'm NOT running mongodb on a remote server.
- `/usr/bin/mongodump`  does properly run with my regular user.
- `which mongodump` outputs `/usr/bin/mongodump` also as a regular user.
- `which mongodump` outputs `/usr/bin/mongodump` also as su.

And as you suggested commenting/deleting `mongoDumpPath` in fact resolves this issue. After succesufully creating the full backup tried to set up the full path again, and it worked... Soooo maybe a layer 8 issue? Thanks for taking your time @Ylianst  @yomono @nzalev @VINISHVV, you guys are awesome.
