### ISSUE TITLE
[RASPY] Letsencrypt error with any mail provided

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#2492]
Hi 
meschentral 0.8.0 on raspberry, raspbian CLI only
I am in trouble with letsencrypt certificate, every mail provided cause resolving error
![image](https://user-images.githubusercontent.com/48550288/113995139-43fa0400-9856-11eb-8196-078761738d61.png)

I've read in other issues that mailbox domain is not a problem, I can choose any mail I want without limitation

What's wrong ?

Thanks a lot

**Comment by vitko-bg** [comment]
As I remember for Let'sEncrypt you must provide a real e-mail address. Is your e-mail address real or fake one? My suggest is to try to use a real e-mail address.

**Comment by merlinweb** [comment]
absolutely REAL
tried with hotmail.com, gmail.com mydomain.com, warning is displayed
I'm afraid could be a dns linux issue

**Comment by vitko-bg** [comment]
Strange. I am using Let'sEncrypt on MC2 on Debian 8 with no problems. Try to flush dns possibly. Not sure now

**Comment by merlinweb** [comment]
can you confirm that mail domain is not related to MC (sub)domain ?
Just to be sure...

**Comment by vitko-bg** [comment]
Actually I cannot confirm the above, as my e-mail is MC2 domain related .... 
see below:
"letsencrypt": {
        "__comment__": "Go to https://letsdebug.net/ first before trying Let's Encrypt.",
        "email": "o****@mydomain.com",
        "names": [ "r*****.mydomain.com,b***.mydomain.com,a*****.mydomain.com" ],
        "rsaKeySize": 3072,
        "production": false
},

**Comment by merlinweb** [comment]
Thanks, I have a production (old) MC2 installation on win, and everything is ok with LE, using a mail with same domain.
But I've read mail is not required to be identical.
I Hope so, I haven't mail in my newly registered domain...

**Comment by merlinweb** [comment]
Could be related to Letsencrypt service disruption ?
![image](https://user-images.githubusercontent.com/48550288/114031152-63efee80-987b-11eb-8e46-2d509cc2bca4.png)

![image](https://user-images.githubusercontent.com/48550288/114031282-8124bd00-987b-11eb-9f55-3ee3549e46e9.png)

**Comment by Ylianst** [comment]
Interesting Let's Encrypt is having this outage. Thanks for reporting that, I would have never found that. However, issue is not related to any outages. MeshCentral makes an effort to validate the email address that was given in the Let's Encrypt section of the config.json. When you have this:

```
  "letsencrypt": {
    "email": "admin@sample.domain.com",
    "names": "myserver.meshcentral.com",
    "production": false
  }
```

MeshCentral will look at the email address, and try to resolve the MX record for the string after the @ in the email ("sample.domain.com" in the example above). The code that does this is [located here](https://github.com/Ylianst/MeshCentral/blob/46622192e8a399b067dc470b4b1b311fe0456e66/meshcentral.js#L1395). So, if your MeshCentral server is not connected to a DNS or the DNS does not resolve the domain MX record, you get that error and MeshCentral does not even try to contract Let's Encrypt. If you are sure the values are correct, you can bypass the check like this:

```
  "letsencrypt": {
    "email": "admin@sample.domain.com",
    "names": "myserver.meshcentral.com",
    "production": false,
    "nochecks": true              <------------
  }
```

Of course, I am trying to be nice to Let's Encrypt that offers a great server and make every effort to validate everything before making a request to them. Hope that helps.

**Comment by merlinweb** [comment]
Thanks Ylian,
I'll give a try with "nochecks": true

Only a last question...
how I can check if MC2 is connected to a DNS Server ?
I assume MC2 use dns in NIC  (eth0 in my case), tried to change it with public dns (8.8.8.8) but with no luck
can dnsutils help ?

**Comment by Ylianst** [comment]
You can use the `nslookup` on the server that is running your MeshCentral server. On [Windows you can do this](https://webhostinggeeks.com/howto/how-to-check-mx-record-using-nslookup-command-on-windows/):

```
nslookup
set type=mx
gmail.com
```

That should return the MX record for "gmail.com". You can try that for your own domain. Let's Encrypt will perform the same MX record check, so if your DNS does not have a MX record for your domain, even with `nocheck` it may cause Let's Encrypt to reject the request. In your case, it seems ok.

Let me know what you find out.

**Comment by merlinweb** [comment]
got it with dnsutils in raspbian
this is response:
nslookup                                                                                                                                                                                       
> set type=mx                                                                                                                                                                                                     
> gmail.com                                                                                                                                                                                                       
Server:         127.0.0.1                                                                                                                                                                                         
Address:        127.0.0.1#53                                                                                                                                                                                      
                                                                                                                                                                                                                  
Non-authoritative answer:                                                                                                                                                                                         
gmail.com       mail exchanger = 20 alt2.gmail-smtp-in.l.google.com.                                                                                                                                              
gmail.com       mail exchanger = 40 alt4.gmail-smtp-in.l.google.com.                                                                                                                                              
gmail.com       mail exchanger = 30 alt3.gmail-smtp-in.l.google.com.                                                                                                                                              
gmail.com       mail exchanger = 10 alt1.gmail-smtp-in.l.google.com.                                                                                                                                              
gmail.com       mail exchanger = 5 gmail-smtp-in.l.google.com.                                                                                                                                                    
                                                                                                                                                                                                                  
Authoritative answers can be found from:  

I use dnsmasq for my dhcp lease in Softether VPN (great sw)

I am afraid that dnsmasq is avoiding name resolution of MC2

I'm trying to solve it but with no luck

**Comment by Ylianst** [comment]
Well, you can just put `"nochecks": true` in your case and give that skip that check.

**Comment by merlinweb** [comment]
done
but now MC page is not accessible.... :(
ERR_CONNECTION_REFUSED
investigating...

**Comment by merlinweb** [comment]
is there a way to rollback from letsencrypt ?
removed letsencrypt dir and commented in config, but MC is stil not accessible

**Comment by vitko-bg** [comment]
Have you restarted MC2?

**Comment by merlinweb** [comment]
yes, rebooted raspberry too...
meshcentral.service - MeshCentral Server                                                                                                                                                                         
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)                                                                                                                       
   Active: activating (auto-restart) since Fri 2021-04-09 11:48:06 CEST; 8s ago                                                                                                                                    
  Process: 1896 ExecStart=/usr/bin/node /home/pi/node_modules/meshcentral (code=exited, status=0/SUCCESS)                                                                                                          
 Main PID: 1896 (code=exited, status=0/SUCCESS)

**Comment by merlinweb** [comment]
strange is that the in chrome bar address, "https://" is nor crossed out, before letsencrypt was.... and was operational

**Comment by Ylianst** [comment]
I generally stop the MeshCentral service and run MeshCentral from the command line to debug this.

`node node_modules/meshcentral --debug webrequests`

It will show you on what ports it's binded to and it will show you the HTTP requests coming in.

**Comment by merlinweb** [comment]
thanks, config.json mismatch, what a newbie....

**Comment by merlinweb** [comment]
GOT IT !
thanks for all support, nochecks is the key
