### ISSUE TITLE
No memory details on Linux systems?

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2494]
Just noticed there are no memory details, on details tab, when the agent OS is linux.
Although I only tested Debian based linux

tried `lshw -class memory`  and that output can be used, if availble.

Any reason this is not avaialbe?

**Comment by Ylianst** [comment]
Is it not the CPU details that are missing? If it's different, can you post a screenshot and indicate what Linux distro and version you are using? Thanks.

![image](https://user-images.githubusercontent.com/1319013/114068999-5aeb2700-9853-11eb-9431-9ca5052405fb.png)

**Comment by Allowee** [comment]
The cpu does indeed not update in the live graph

I mean the memory details between Motherboard and storage

![image](https://user-images.githubusercontent.com/55733884/114070252-19349d80-98a0-11eb-895d-c1ad256cc912.png)

**Comment by yomono** [comment]
I'm using ubuntu 20.10 and I can confirm this.
Plus, I can't see the Storage section either:
![image](https://user-images.githubusercontent.com/31445936/114087851-bbe22180-988a-11eb-9c8f-a31c1ed6b5f3.png)

**Comment by Ylianst** [comment]
Ha got it. I don't think the MeshAgent is providing that information. Bryan will have to look into it.

**Comment by Ylianst** [comment]
Storage shows up for my Ubuntu machine. Bryan confirmed the memory details are not currently present on Linux.

![image](https://user-images.githubusercontent.com/1319013/114091434-88dd6500-986d-11eb-9c26-ea34214f9bd1.png)

**Comment by Allowee** [comment]
I found the file: identifiers.js
On the Pi I get the DMI error message, but this blocks the rest of the commands, which could give resultst just fine.
` if (!require('fs').existsSync('/sys/class/dmi/id')) { throw ('this platform does not have DMI statistics'); }`

I have tried to comment out this DMI section, and it works
![image](https://user-images.githubusercontent.com/55733884/114180208-315bf980-9940-11eb-94cf-c98f4b2e46f5.png)



> I'm using ubuntu 20.10 and I can confirm this.
> Plus, I can't see the Storage section either:

Do you have lshw installed?

**Comment by yomono** [comment]
> I found the file: identifiers.js
> On the Pi I get the DMI error message, but this blocks the rest of the commands, which could give resultst just fine.
> ` if (!require('fs').existsSync('/sys/class/dmi/id')) { throw ('this platform does not have DMI statistics'); }`
> 
> I have tried to comment out this DMI section, and it works.
> Although the SD info cannot be found with the lshw command
> ![image](https://user-images.githubusercontent.com/55733884/114180208-315bf980-9940-11eb-94cf-c98f4b2e46f5.png)
> 
> > I'm using ubuntu 20.10 and I can confirm this.
> > Plus, I can't see the Storage section either:
> 
> Do you have lshw installed?

Yes. Actually using the same command you provided works fine
