### ISSUE TITLE
Is possible to run meshcentral behind a baseurl?

### ISSUE THREAD

**Issue by kurotorakun** [Ylianst/MeshCentral#2496]
Hi all,

I have installed meshcentral as a docker container and is running wonderful.
Now, I want to take the extra step to make it reachable from Internet.

In my current configuration, I'm using NGINX as a reverse proxy, and due to my domain limitations, working with subfolders configurations (instead of subdomain).

I was wondering if it's possible to set any baseurl param in order to make mesh available in the explained way.

_PS: sorry for my english, is not my main language._

Regards,
MC

**Comment by Ylianst** [comment]
Yes, you can create a sub-domain of MeshCentral with any sub-url you want. Something like:

```
{
  "settings": {
      "cert": "myserver.domain.com"
      ...
   },
   "domains": {
      "": {
         (Settings for default domain go here)
      },
      "mybaseurl": {
         (Settings for mybaseurl domain go here)
      }
   }
}
```

This will allow you to access a sub-domain as `https://myserver.domain.com/mybaseurl`

Hope that helps,
Ylian

**Comment by kurotorakun** [comment]
Dear @Ylianst,

Thanks for the fast answer :)
Yes, indeed, it's working as you mentioned.

Thanks for the support,
MC.
