### ISSUE TITLE
Pi identifier in Details tab

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2497]
While investigating the file identifiers.js I found some info that can be added on the Details tab for a Pi
It seems Pi specific.. so that might need a check

for the CPU name there is already a command 'cat /proc/cpuinfo | grep "model name"'
But by editing this we can get the Pi board info, which can be used for   ` identifiers['board_name']` for example

Tested on 2 Pi's:

Model           : Raspberry Pi Model B Rev 2
Model           : Raspberry Pi 4 Model B Rev 1.1

For this I added
>var child = require('child_process').execFile('/bin/sh', ['sh']);
>    child.stdout.str = ''; child.stdout.on('data', function (c) { this.str += c.toString(); });
 >   child.stdin.write('cat /proc/cpuinfo | grep "Model" | ' + "tr '\\n' ':' | awk -F: '{ print $2 }'\nexit\n");
  >  child.waitExit();
  >  identifiers['board_name'] = child.stdout.str.trim();

![image](https://user-images.githubusercontent.com/55733884/114186040-ad594000-9946-11eb-92dc-bf3913aee1cb.png)

**Comment by Ylianst** [comment]
This is a good idea. I have a lot of Raspberry Pi's and it would be great to see the exact model on the details page.

**Comment by Allowee** [comment]
I have checked on some linux systems and only on Pi's (only have with Debian) the exact "Model" string is present

My suggestion is to check the DMI first, if that fails try this method and only if there is a result assign it to board_name

dmi check:   if (!require('fs').existsSync('/sys/class/dmi/id')) { throw ('this platform does not have DMI statistics'); }
the throw should not be there, it stops the execution of following commands that work just fine

**Comment by si458** [comment]
i have partly added this support here - https://github.com/Ylianst/MeshAgent/pull/206

**Comment by si458** [comment]
Duplicate #795
