### ISSUE TITLE
Share Device Group to particular user / user group for a limited Period

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2499]
@Ylianst 

In our company each support team handle different department. Is there any staff shortage in particular department we need to shift few users in to new department.

Currently we are handling the situation by allocating particular device group to that user / user groups. But some time we forget to remove the same and it will create some internal issues.

If possible Please implement Device group share option for limited period.

**Comment by Mfinadmin** [comment]
sharing device group to user group or user for a limited period is definitely a good option.  I am also having such issues especially in lockdown period..

**Comment by Ylianst** [comment]
One way to do this right now is to use MeshCtrl.js to script granting and removing user rights on a timer. You can use the following MeshCtrl.js actions:

```
  AddToUserGroup
  RemoveFromUserGroup
```

You could create a script to add and remove user access rights at specific times. In the future, one idea is to provide a way to perform these commands at given times in MeshCentral, but that will take a while. If you need more details on how to use meshctrl.js, let me know.

**Comment by Mfinadmin** [comment]
@Ylianst 
Definitely I need your support since I am new to meshctrl.js.

**Comment by Ylianst** [comment]
Normally you run your MeshCentral server like this:

```
node node_modules\meshcentral
```

To run meshctrl, you go into the same place as where you run your MeshCentral server and run this:

```
node node_modules\meshcentral\meshctrl
```

It will give you help on how to get started. If you run with not parameters, you should see this:

```
eshCtrl performs command line actions on a MeshCentral server.
Information at: https://meshcommander.com/meshcentral
No action specified, use MeshCtrl like this:

  meshctrl [action] [arguments]

Supported actions:
  Help [action]               - Get help on an action.
  ServerInfo                  - Show server information.
  UserInfo                    - Show user information.
  ListUsers                   - List user accounts.
  ListUserSessions            - List online users.
  ListUserGroups              - List user groups.
  ListDevices                 - List devices.
  ListDeviceGroups            - List device groups.
  ListUsersOfDeviceGroup      - List the users in a device group.
  ListEvents                  - List server events.
  DeviceInfo                  - Show information about a device.
  Config                      - Perform operation on config.json file.
  AddUser                     - Create a new user account.
  EditUser                    - Change a user account.
  RemoveUser                  - Delete a user account.
  AddUserGroup                - Create a new user group.
  RemoveUserGroup             - Delete a user group.
  AddToUserGroup              - Add a user, device or device group to a user group.
  RemoveFromUserGroup         - Remove a user, device or device group from a user group.
  RemoveAllUsersFromUserGroup - Remove all users from a user group.
  AddDeviceGroup              - Create a new device group.
  RemoveDeviceGroup           - Delete a device group.
  EditDeviceGroup             - Change a device group values.
  MoveToDeviceGroup           - Move a device to a different device group.
  AddUserToDeviceGroup        - Add a user to a device group.
  RemoveUserFromDeviceGroup   - Remove a user from a device group.
  AddUserToDevice             - Add a user to a device.
  RemoveUserFromDevice        - Remove a user from a device.
  SendInviteEmail             - Send an agent install invitation email.
  GenerateInviteLink          - Create an invitation link.
  Broadcast                   - Display a message to all online users.
  ShowEvents                  - Display real-time server events in JSON format.
  RunCommand                  - Run a shell command on a remote device.
  Shell                       - Access command shell of a remote device.
  Upload                      - Upload a file to a remote device.
  Download                    - Download a file from a remote device.
  DeviceOpenUrl               - Open a URL on a remote device.
  DeviceMessage               - Open a message box on a remote device.
  DeviceToast                 - Display a toast notification on a remote device.
  DevicePower                 - Perform wake/sleep/reset/off operations on remote devices.
  DeviceSharing               - View, add and remove sharing links for a given device.

Supported login arguments:
  --url [wss://server]        - Server url, wss://localhost:443 is default.
                              - Use wss://localhost:443?key=xxx if login key is required.
  --loginuser [username]      - Login username, admin is default.
  --loginpass [password]      - Login password.
  --token [number]            - 2nd factor authentication token.
  --loginkey [hex]            - Server login key in hex.
  --loginkeyfile [file]       - File containing server login key in hex.
  --logindomain [domainid]    - Domain id, default is empty, only used with loginkey.
  --proxy [http://proxy:123]  - Specify an HTTP proxy.
```

Let me know if that helps.

**Comment by Mfinadmin** [comment]
@Ylianst 
Thanks, one more help, I tried to login meshctrl but it's not success can you post the sample login url once?

**Comment by Ylianst** [comment]
Certainly...

```
node node_modules/meshcentral/meshctrl serverinfo --url wss://central.mesh.meshcentral.com --loginuser admin --loginpass adminpass
```

Let me know if that works.

**Comment by Mfinadmin** [comment]
Dear @Ylianst 
i have tried login but getting error.

PS C:\mesh> node node_modules/meshcentral/meshctrl listdevices --url wss://localhost:443 --loginuser admin --loginpass admin --token 174523

buffer.js:333
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Ar
ray or an Array-like Object. Received type number (222555)
    at Function.from (buffer.js:333:9)
    at serverConnect (C:\mesh\node_modules\meshcentral\meshctrl.js:1021:99)
    at Object.<anonymous> (C:\mesh\node_modules\meshcentral\meshctrl.js:862:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Ylianst** [comment]
Try adding quotes:

```
node node_modules/meshcentral/meshctrl listdevices --url "wss://localhost:443" --loginuser "admin" --loginpass "admin" --token "174523"
```

If that works, there could be a character in the password that is causing the problem.

**Comment by Mfinadmin** [comment]
> Try adding quotes:
> 
> ```
> node node_modules/meshcentral/meshctrl listdevices --url "wss://localhost:443" --loginuser "admin" --loginpass "admin" --token "174523"
> ```
> 
> If that works, there could be a character in the password that is causing the problem.

Tried the same by adding quoted. But its not work...

![image](https://user-images.githubusercontent.com/80849522/114661048-efea9600-9d13-11eb-8b02-c2804a9dbc69.png)

**Comment by Mfinadmin** [comment]
@Ylianst - Ignore previous comment.

Its working fine after changing admin password from numeric to alpha numeric.

**Comment by Ylianst** [comment]
Oh!!! Ok, that helps. The password was all numbers. I will fix that.

**Comment by Mfinadmin** [comment]
@Ylianst - Its working fine......
But its little complicate for normal users to execute the commands at scheduled intervals.
can you check the possibility to add the same function in UI. 
Its very helpful for us.

**Comment by Ylianst** [comment]
I fixed the username/password all numbers issue for MeshCtrl.js, it will be in MeshCentral v0.8.13.

**Comment by Mfinadmin** [comment]
@Ylianst 

Thanks alot. 

Can add same function in UI.
Its very helpful for us.

**Comment by VINISHVV** [comment]
Dear @Ylianst 

Thanks for explaining Meshctrl.js  really its powerful tool.

Since we can achieve the goal through Meshctrl.js I am going to close this case.

@Mfinadmin - I think your issue is also resolved. If not Please raise a new case.
