### ISSUE TITLE
Email validation doesn't support new TLDs

### ISSUE THREAD

**Issue by dantheman2865** [Ylianst/MeshCentral#25]
Currently, email address validation supports 2-4 character TLDs (.us, .biz, etc.). Given the proliferation of longer TLDs, we should update this.

I can submit a PR which would remove the upper limit on length, but do we also want to allow international addresses at this time?

**Comment by Ylianst** [comment]
Your right. Published MeshCentral v0.2.2-l on NPM with a fix for this. Updated the email regex validation.
