### ISSUE TITLE
Last agent connect time column 

### ISSUE THREAD

**Issue by martadams89** [Ylianst/MeshCentral#2504]
Hey Ylian!

Can I log a feature request for a “Last Connect Time” column to be added, similar to the recently added MeshRouter links?

If there’s an old agent that’s been uninstalled, this will help to narrow down the correct computer to remove. Also could be useful as a spot check for agents that haven’t checked in for awhile and thus might need further investigation. 

Thanks for everything you do...!

**Comment by vitko-bg** [comment]
#2329 and #1693 are already same requests.
Otherwise +1 for this :)

**Comment by si458** [comment]
this already exists, click the COG in the columns view and select 'Last Seen'
