### ISSUE TITLE
Latest Language update 0.8.8

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2508]
[translate.zip](https://github.com/Ylianst/MeshCentral/files/6299336/translate.zip)

due upload problems (pull requests) old skool this time

Dutch Language file V0.8.8

**Comment by Ylianst** [comment]
Thanks. Working to merge this now.

**Comment by Ylianst** [comment]
MeshCentral v0.8.9 is out with your changes.
