### ISSUE TITLE
Feature Request: Notes Displayed On Device General

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#2513]
I get lots of questions about remote machines that I answer with "look in the notes". It would be great to have the option to just show the notes on the General page of a device, rather than having to click the button to see if any notes exist. Editing notes would ideally still require clicking the button.

**Comment by si458** [comment]
is this ok? 
![Screenshot 2023-11-12 at 15-17-09 DESKTOP-SIMJAHR - testgroup - MyRemoteAgent](https://github.com/Ylianst/MeshCentral/assets/765314/97b5ca77-b834-4bbf-8e36-4dcbd505f903)

**Comment by si458** [comment]
done! you can set `showNotesPanel: true` under `domains` in your `config.json` now
![Screenshot 2023-11-12 at 16-51-09 DESKTOP-SIMJAHR - testgroup - MyRemoteAgent](https://github.com/Ylianst/MeshCentral/assets/765314/a4595b5f-9da6-4dcb-bf15-decd9c47e95a)

**Comment by MatinatorX** [comment]
That looks perfect, thanks!

**Comment by si458** [comment]
Only took 3 years, so let's no rush things! Should be in 1.1.16 release!
