### ISSUE TITLE
Feature Request - Easily identify Bad Agents (Agent Error Counters)

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#2514]
In the My Server summary list of endpoints, if some are showing under "Agent Error Counters," such as:
![image](https://user-images.githubusercontent.com/7637082/114842838-16e5ae00-9d8e-11eb-8d6a-1f6b38d60ebb.png)

It would be great to know which machines these are from here, rather than going on a discovery or hunt to locate what is causing this.

**Comment by VINISHVV** [comment]
@mjpcomp - Please try below method to identify the system.

Goto my server console and  run the command "Agentissues".
You will get the affected system IP address like this.

---------------------------------------------------------------------------
 agentissues
12:07:45 pm, 122.161.224.214:53498, invalidPkcsSignature
12:07:45 pm, 122.161.224.214:53498, BadSignature2
12:07:49 pm, 223.177.190.144:51611, invalidPkcsSignature
12:07:49 pm, 223.177.190.144:51611, BadSignature2
12:08:08 pm, 27.58.2.84:65428, BadWebCertHash:
------------------------------------------------------------------------

**Comment by mjpcomp** [comment]
Thanks @VINISHVV - the problem with that, as you have in your screenshot, is that they are all public IPs, so, if you're managing customers, you only know that the issue exists at the customer, but, if there are a lot of devices with the agent, you still won't be able to pinpoint which device is the issue...

I also have this issue:
![image](https://user-images.githubusercontent.com/7637082/114901832-06532900-9dca-11eb-8b97-5e4e342c655c.png)
(the duplicate agent)... which may be related to another bug I posted, but, not sure which device(s) are causing that as it doesn't show up in the error list...

**Comment by VINISHVV** [comment]
@mjpcomp 

Yes if more agents are connecting from same public IP then its little difficult to identify....

For duplicate agents Please find below comment from @Ylianst .

-------------------------------------------------------------------------------------
Hi. "Duplicate agent" is probably normal. Each agent has a unique identifier and you can't have two agents with the same identifier connect to the server. If the agent is connected over WIFI for example and the access point drops, the agent will know the connection dropped but the server would not know until the connection timeouts.

When the agent connects again, the server will need to drop the old connection (that will timeout anyway) and accept the new connection. You see a "duplicate agent" at that point, but that is ok. The server is dropping the old connection from that agent and moving to the new one.

If you see this "duplicate agent" a lot, it could be that two agents where cloned and have the same identifier and are fighting to connect to the server. This is unlikely, but let me know.

Hope that helps,
Ylian
-------------------------------------------------------------------------------------------------

**Comment by mjpcomp** [comment]
Thanks for the quick reply, @VINISHVV - I know for one of the locations, the Duplicate Agent issue might be related to this:
https://github.com/Ylianst/MeshCentral/issues/2434

(the same system repeatedly showing up)....

Though it's not listed multiple times in the UI anymore, it's possible that the issues is from that system (as one of the IPs reporting duplicate agents is that site)... However, I know it's not from the cloning the agent or the database as the systems there were set up at different times and the agent downloaded manually.

**Comment by tradexsrl** [comment]
hi , i have the same problem and with these command i have seen the BadSignature and invalidPkcsSignature are from the same ip of the same machine...but why this message? what is the problem ? and as @mjpcomp with command Agentissues i have also some duplicate agent message which are not shown in the my devices tab

**Comment by si458** [comment]
just checked source code, we could add the devices nodeid to the end of `duplicateAgent` if thats helpful?

`1/17/2024, 10:28:14 AM, 62.255.xxx.xxx:57900, duplicateAgent, jr$S1mCptzQeHuSv3XXXXXXXXXXXXX`

**Comment by NiceGuyIT** [comment]
> we could add the devices nodeid to the end of duplicateAgent if thats helpful?

Yes, that would be helpful. Then we can identify which agent is being duplicated. At the very least it will give more information to troubleshoot this problem. Thanks si458!

**Comment by si458** [comment]
just found a hidden feature! so dont really need to change anything as its already built in
go to the Console tab in the 'My Server' Tab, type `dupagents` thank me later!
```
> dupagents
{"name":"HuDelli7-9750","group":"Hu","ip":["82.0.xx.xx"],"count":1}
```

**Comment by si458** [comment]
the other issue we have is the like errors `invalidPkcsSignature,invalidRsaSignature` could just simply be a BOT on the internet discovered the agent https port and realised its websocket, so tried to connect and poke around, so they wont have nodeids for example

going to close this as not much else we can do logging wise apart from what we have

**Comment by silversword411** [comment]
> just found a hidden feature! so dont really need to change anything as its already built in
> go to the Console tab in the 'My Server' Tab, type `dupagents` thank me later!
> ```
> > dupagents
> {"name":"HuDelli7-9750","group":"Hu","ip":["82.0.xx.xx"],"count":1}
> ```

Didn't I write that up in the docs when I discovered this? If not we should.

**Comment by silversword411** [comment]
Yeah, thought I put it in there 🙂

https://ylianst.github.io/MeshCentral/meshcentral/debugging/#finding-agent-problems
