### ISSUE TITLE
Feature Request - allow changing install path for Linux Agent installs with command line parameters

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#2515]
Noticed that on the agent install for Linux, the installation path appears to be hardcoded or, at least, it decides it wants to go to /usr/local/ (which becomes an issues on systems where the file system is write protected during normal runtime, as the agent will not work as it can't write to the protected file system).

It would be nice (unless it's possible, but, I couldn't see it in the meshinstall.sh script) to be able to set an installation path for the agent (and allow that to modify the meshagent.service file as well to point to the same path).

To deal with this, we have to unprotect the file system, run the install, move the meshagent folder to the rw filesystem, modify the service file to reference the new paths, and then all is well.

**Comment by Mfinadmin** [comment]
@mjpcomp  In windows we can install the agent application In different folder by enabling the agent customization. To enable this add below code under domain section. 

I have not tried this in Linux. But assume this will works in Linux also


"agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      },

**Comment by mjpcomp** [comment]
Thanks @Mfinadmin - I don't recall seeing path/location customization there, but, will take a look. The only issue is that, we don't want to change the path except on certain devices/appliances/Iot products which have a typically read-only root file system (as Mesh won't work when the filesystem is read-only). We have to put the agent in a rewritable path in those situations. It would be nice to simply send a different installation command line in order to accomplish that, versus the manual process we currently go through.

**Comment by Ylianst** [comment]
It should be possible to install many agents with different customization at the same time. In order to do that, install path should change for each customization. The company name in the customization will be used in the install path. Give it a try and let me know if it works for you.

**Comment by yomono** [comment]
> @mjpcomp In windows we can install the agent application In different folder by enabling the agent customization. To enable this add below code under domain section.
> 
> I have not tried this in Linux. But assume this will works in Linux also
> 
> ```
> "agentCustomization": {
>         "displayName": "Compagny® Product™",
>         "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
>         "companyName": "Compagny",
>         "serviceName": "compagnyagent",
>         "fileName": "compagnyagent"
>       },
> ```

The last time I checked, customization did not work on Linux or Mac. Just Windows.

**Comment by Ylianst** [comment]
Oh, I think customization on Linux was only built into the binary installer...

![image](https://user-images.githubusercontent.com/1319013/114991871-f03b7c00-9e4e-11eb-97f2-d7453d8ae4a9.png)

I still need to add support for that in the install script.

**Comment by ph4xo** [comment]
Sorry for hijacking this thread but I'm currently trying to install the MeshAgent on a PiKVM Arch Linux read only device and like you already mentioned, the agent wont connect after a reboot when the filesystem is not in read/write mode. How did you install the agent so it will run in read only mode @mjpcomp ?

**Comment by mjpcomp** [comment]
> Sorry for hijacking this thread but I'm currently trying to install the MeshAgent on a PiKVM Arch Linux read only device and like you already mentioned, the agent wont connect after a reboot when the filesystem is not in read/write mode. How did you install the agent so it will run in read only mode @mjpcomp ?


So, it's been a while since I initially created this ticket, and I hadn't worked with PiKVM or Arch linux before, but, now I have three v4 Plus units, and decided to just tackle this about 20 minutes ago...

Got it working after looking at how the TailScale-PiKVM package was built, and had to make some modifications to account for the meshagent.db:

STEPS:
SSH into the PiKVM (this was all done on v4, not sure if there are any changes in terms of the file/folder structure on the other builds):

`rw`
Login as root
DOWNLOAD AND RUN THE MESH INSTALLER (non-Binary version!) AND LET IT CONNECT
`systemctl stop meshagent`
`mkdir -p /var/lib/meshagent`
`chmod 700 /var/lib/meshagent`
`mv /usr/local/mesh_services/meshagent/* /var/lib/meshagent`
`mv /var/lib/meshagent/meshagent.db /var/lib/meshagent/meshagent.db.temp`

Going to make a couple of changes now:
`nano -w /etc/systemd/system/multi-user.target.wants/meshagent.service`
Modify the **WORKINGDIRECTORY** and **EXECSTART** to read as follows:
`WorkingDirectory=/var/lib/meshagent/`
`ExecStart=/var/lib/meshagent/meshstartup.sh`
Save and exit, and then reload systemctl:
`systemctl daemon-reload`

Now, we need to make a Symlink for the meshagent.db to be able to work with the ReadOnly filesystem...
`mkdir -p /var/log/meshagent`
`chmod 700 /var/log/meshagent`
`ln -s /var/lib/meshagent/meshagent.db /var/log/meshagent/meshagent.db`

And lastly, we're making that new meshstartup script:
`nano -w /var/lib/meshagent/meshstartup.sh`
Add the following content to it:

`#!/bin/bash`

`mkdir -p /var/log/meshagent`
`chmod 700 /var/log/meshagent`
`cp -rp /var/lib/meshagent/meshagent.db.temp /var/log/meshagent/meshagent.db`
`/var/lib/meshagent/meshagent --installedByUser=0`


Now, again, save and exit that file...

Switch the file system to RO:
`ro`
and give it a reboot
`reboot`

That should get it working...

**Comment by si458** [comment]
@mjpcomp seems a lot of work...

All I did was enter `rw` mode as root, change `ro` to `rw` in `/boot/cmdline.txt`, restart, then run the installer script

Also gives u full read/write access to the pikvm now too for future things

**Comment by telepath** [comment]
@mjpcomp thanks for the writeup. I really like the idea of integrating pikvm into meshcentral, it'a really neat addition to the support capabilities.
Also, once the agent is installed, updates can be done via script by the agent itself, so I'm good. I do prefer to keep the RO file system for normal operations, the pikvm is a device that needs to "just work" after all, it would be annyoing if it broke because it didn't shut down and some write process was interupted or something like that.

**Comment by mjpcomp** [comment]
> @mjpcomp thanks for the writeup. I really like the idea of integrating pikvm into meshcentral, it'a really neat addition to the support capabilities. Also, once the agent is installed, updates can be done via script by the agent itself, so I'm good. I do prefer to keep the RO file system for normal operations, the pikvm is a device that needs to "just work" after all, it would be annyoing if it broke because it didn't shut down and some write process was interupted or something like that.

Exactly - it's an "appliance" type product, and may not be accessible for the most part, so, anything that can impact the file system needs to be removed from the equation.
