### ISSUE TITLE
Reset account problem

### ISSUE THREAD

**Issue by rrech** [Ylianst/MeshCentral#2517]
Hi Ylian!

When trying to reset an account that is set up with 2FA via email, no email is sent to the configured address. The screen is stopped at the request of the token that does not arrive in the email (there is no e-mail icon in this case). This occurs on machines that have not yet been logged in with 2FA and/or that have not been given the option to remember for thirty days.

Version: 0.8.12 (updated before come to bother here, just in case!)

**Comment by Ylianst** [comment]
As a temporary solution, as administrator you can reset an account in the "My Users" tab. Click a user and hit "Change Password" and "Remove all 2nd factor authentication".

![image](https://user-images.githubusercontent.com/1319013/115063115-0160a900-9ea0-11eb-9a4a-3b0b211a063d.png)

You can also enable server tracing on email in the "My Server" tab to see if the server sent the email.

![image](https://user-images.githubusercontent.com/1319013/115063212-1fc6a480-9ea0-11eb-9288-0f54392404ca.png)

If I get a change, I will run thru that scenario and see if I can replicate it.

**Comment by rrech** [comment]
Hi, Ylian. Thanks for the answer!

I changed the password and worked fine. The problem is in situations that I can't be contacted or something else. Reported to see if we could solve this in future versions, because in cases where an account has 2FA (only by e-mail) configured, an user can't reset the password without intervention of an administrator.

To replicate, you could set an account with 2FA by e-mail and open the site in an incognito browser window.

I almost forgot to mention: tracing does not log anything in this situation here.

Tks!

**Comment by Ylianst** [comment]
Ha so, this is a topic of conversation because you may not want someone to be able to reset an account if 2FA is not verified. This is why I ask for 2 x 2FA to be setup so, there is always a backup 2FA. I will take a look at the flow again and see if I can improve things.

**Comment by rrech** [comment]
100% agree. You are right! Anyway, in this screen could exists an icon to send a 2FA to registered e-mail address. But, for sure, one has to maintain a backup 2FA. It's only an idea. Tks Ylian!

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
