### ISSUE TITLE
Hardware Connect  AMT access fails from corporate laptop

### ISSUE THREAD

**Issue by reidjr** [Ylianst/MeshCentral#252]
I have been a long term user of Meshcentral. I use  meshcentral running on a raspberry pi, on the same LAN as the machines being controled. My main use is access to a server (port forward of 443 from the internet)  which has  hardware AMT, but I also use meshagent  on multiple machines (including the server) .

I can access all of the meshagents from the internet and LAN and the hardware AMT from all of my own client devices ( apple/android/Linux/MS)) However I cannot  connect to the desktop of the server with hardware AMT from my corporate laptop, I can connect  to the servers desktop through meshagent, and I can connect to the AMT  status, reboot etc.

Running meshcentral with --debug, all I can see is that the websocket for the Hardware connect attempts from the laptop keep closing with ECONRESET.

An old install of meshcommander  beta 2 strangely does work for hardware desktop. 

Any guidance on solving this issue ?

**Comment by Ylianst** [comment]
Hi. Ok, I am trying to parse your text. You have a server on a Raspberry Pi with an external router port forwarding port 443 to the RPi port 443. I am having a hard time decoding: "However I cannot connect to the desktop of the server with hardware AMT from my corporate laptop".

Also you mention a problem with MeshCentral, but use MeshCommander in the past and it worked? These are two different software that work very differently.

I also don't understand this: "websocket for the Hardware connect attempts". Are you trying to connect using normal remote desktop? Or Intel AMT KVM?

Sorry, I don't understand the problem. Can you make it more clear? Thanks.

**Comment by reidjr** [comment]
Must try harder  on clarity :-).

1) I meant to say MeshCENTRAL beta 2 in the same situation works as expected. However current and recent versions of Meshcentral behave as below.
2) My use case is:
Internet explorer web browser on my corporate ( not under my control) laptop.
Connecting using HTTPS to the dynamic dns address of a broadband router/modem.
443  is portforwarded to an instance of Meshcentral running on the Raspberry pi,  as the meshcentral Server.
Meshcentral has both hardware INTEL AMT and meshagent access to a DELL server. The DELL server and the Pi running meshcentral are  on the the same LAN. The serve II am  trying to access runs Ubuntu 18.04).
When I press "connect" on the desktop tab for the server, I connect as usual and the desktop is working as expected ( I am typing this reply by this chain of Corporate laptop --> Pi--> server)
When I attempt to "HW connect" it cycles to "Setup ..." --"Disconnect".
"Intel AMT" tab works as expected.
Any web browser on any other device I have works with HW Connect, either on the LAN or accessing over the internet through the BB Router.

Thanks again.

**Comment by jsastriawan** [comment]
Would you give further details about the Dell server tech spec or at least model number? 

Are you able to access Dell server locally using MeshCommander (desktop version) and access remote desktop using this tool? Is KVM feature enabled on this system?

Is the Dell server using Intel graphic card or non-Intel graphic card? Intel AMT KVM doesn't work on non Intel graphic card due to the way AMT captures the framebuffer.

Regards,


Joko

**Comment by reidjr** [comment]
Thanks you for the reply.

Its a dell T20 with AMT v9.1.45
Intel integrated graphics.

To be clear, the ONLY time the "Hardware Connect" Desktop does not work is when I use my corporate laptop and its browser. Hardware/AMT based KVM works perfectly to the T20 when meshcentral web interface is accessed from any other device I have that supports a web browser.

kind regards

**Comment by reidjr** [comment]
OK,

Maybe this is very simple, and it is a browser incompatibility  issue.
The browser on th elaptop is running ie, and when I look at the developer tools debug on the browser I get this error when attempting to Hardware connect to the remote server through meshcentral.


SCRIPT5009: 'f' is undefined
File: amt-redir-ws-0.1.0.js, Line: 82, Column: 20

Is this enough to diagnos ethe issue ? I can not change the browser or its version,

**Comment by reidjr** [comment]
Confirmed Fixed in  #340

Was too slow to confirm before 340 closed. Thanks Ylianst.

I was testing the usability of hardware KVM now its working again, Not sure its worthy of opening another ticket, but Hardware KVM now works, but screen refresh is painfully slow compared with both software agent, and the old beta 2 version of Meshcentral. Its sometimes like an old slow scan TV.
