### ISSUE TITLE
Windows version 0.8.14 broken, error logs says:

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#2520]
Hi, we have a Windows install (nodeJS), it auto updates every night about 0000-0100, looks like 17 April 2021 version 0.8.14 is broken, Windows service will not stay running after about 4 seconds, error log below:

It was working 16 April 2021, didnt use it 17 April, however looking at the log it was likely done from 0005 17 April 2021

c:\Program Files\Open Source\MeshCentral\meshcentral-data\mesherrors.txt

```
-------- 4/16/2021, 5:03:26 PM ---- 0.8.12 --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.

-------- 4/17/2021, 12:05:43 AM ---- 0.8.14 --------

events.js:173

throw er; // Unhandled 'error' event

^

Error: EPERM: operation not permitted, watch

at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)

Emitted 'error' event at:

at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12)

-------- 4/17/2021, 12:06:17 AM ---- 0.8.14 --------

C:\Program Files\Open Source\MeshCentral\node_modules\nedb\lib\datastore.js:77

if (err) { throw err; }

^

Error: EPERM: operation not permitted, rename 'C:\Program Files\Open Source\MeshCentral\meshcentral-data\meshcentral.db~' -> 'C:\Program Files\Open Source\MeshCentral\meshcentral-data\meshcentral.db'

-------- 4/17/2021, 12:06:38 AM ---- 0.8.14 --------

ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
```

**Comment by nzalev** [comment]
This occurs when a second instance of the NeDB datastore is instantiated.

@Ylianst I can experimentally reproduce it by forcing it to load the datastore twice
```javascript
        var Datastore = require('nedb');
        var datastoreOptions = { filename: obj.getConfigFilePath('meshcentral.db'), autoload: true };
        var file = new Datastore(datastoreOptions);
```

I'm currently searching for some flow of execution that allows it to load the datastore twice.

**Comment by Ylianst** [comment]
Interesting. It may be that when updating, the old instance of MeshCentral did not close before the new instance got started. Temporary fix is to make sure there are not two instances of MeshCentral running at the same time. I am not seen this myself, but I mostly run MongoDB for which you would never see this.

**Comment by GRIFFCOMMca** [comment]
> Interesting. It may be that when updating, the old instance of MeshCentral did not close before the new instance got started. Temporary fix is to make sure there are not two instances of MeshCentral running at the same time. I am not seen this myself, but I mostly run MongoDB for which you would never see this.

What's the fix?  We have rebooted windows and the service (meshcentral.exe) starts then stops again about 3-5 seconds later.  No more entries are in the mesherrors.txt, so could it be the database is now corrupted, as i really have no idea why the service stops as "new" log entries are being found...

The Windows Event viewer says "The MeshCentral service terminated unexpectedly, it has done this 6 times(s)" (the times counter increases by 1 every time i try it.

**Comment by nzalev** [comment]
> > Interesting. It may be that when updating, the old instance of MeshCentral did not close before the new instance got started. Temporary fix is to make sure there are not two instances of MeshCentral running at the same time. I am not seen this myself, but I mostly run MongoDB for which you would never see this.
> 
> What's the fix? We have rebooted windows and the service (meshcentral.exe) starts then stops again about 3-5 seconds later. No more entries are in the mesherrors.txt, so could it be the database is now corrupted, as i really have no idea why the service stops as "new" log entries are being found...
> 
> The Windows Event viewer says "The MeshCentral service terminated unexpectedly, it has done this 6 times(s)" (the times counter increases by 1 every time i try it.

If you run meshcentral interactively, it will likely show more useful information. That would look like like
`C:\install\location\meshcentral> node node_modules\meshcentral`
in command prompt.

**Comment by GRIFFCOMMca** [comment]
> If you run meshcentral interactively, it will likely show more useful information. That would look like like
> `C:\install\location\meshcentral> node node_modules\meshcentral`
> in command prompt.

Well this cant be good, tried the above, get the below from the DOS black screen, and i agree i also cant find **_C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral_** on the drive, am hunting through the backup now to see when this was "removed" when i find it (as i have already) can i just copy and paste this back and restart the service?


```
C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules
\meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

C:\Program Files\Open Source\MeshCentral>
```

**Comment by nzalev** [comment]
> > If you run meshcentral interactively, it will likely show more useful information. That would look like like
> > `C:\install\location\meshcentral> node node_modules\meshcentral`
> > in command prompt.
> 
> Well this cant be good, tried the above, get the below from the DOS black screen, and i agree i also cant find **_C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral_** on the drive, am hunting through the backup now to see when this was "removed" when i find it (as i have already) can i just copy and paste this back and restart the service?
> 
> ```
> C:\Program Files\Open Source\MeshCentral>node node_modules\meshcentral
> internal/modules/cjs/loader.js:615
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules
> \meshcentral'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:539:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
>     at internal/main/run_main_module.js:21:11
> 
> C:\Program Files\Open Source\MeshCentral>
> ```

You can restore it from backup and re-run it. If your data directory is still present (`meshcentral-data`) you can also just reinstall with `npm install meshcentral@0.8.16`.

**Comment by GRIFFCOMMca** [comment]
Well this is kinda odd (it is working now..!)
- Copied the meshcentral folder from backup (0026 18 April 2021)
- Restarted MeshCentral service (took about 20 seconds to come up at the GUI)
- Server version 0.8.14 (from the restore)
- Run update to version 0.8.16, working ok

So really no idea what took the folder out, as the backup version was 0.8.14, was there a version 0.8.15 that maybe bricked it (and that version didnt log anything as it never installed correctly)?

**Comment by nzalev** [comment]
> Well this is kinda odd (it is working now..!)
> 
> * Copied the meshcentral folder from backup (0026 18 April 2021)
> * Restarted MeshCentral service (took about 20 seconds to come up at the GUI)
> * Server version 0.8.14 (from the restore)
> * Run update to version 0.8.16, working ok
> 
> So really no idea what took the folder out, as the backup version was 0.8.14, was there a version 0.8.15 that maybe bricked it (and that version didnt log anything as it never installed correctly)?

Meshcentral updates by shutting its server down and then running the `npm install meshcentral@x.y.z` command. I'm not sure if this can even fail in such a way that the meshcentral node module would be removed. I'm not certain though.

**Comment by GRIFFCOMMca** [comment]
Was there a version 0.8.15? if so would that have been available 17 April 2020 between 0000 > 0300?

**Comment by nzalev** [comment]
> Was there a version 0.8.15? if so would that have been available 17 April 2020 between 0000 > 0300?

https://www.npmjs.com/package/meshcentral/v/0.8.15

**Comment by GRIFFCOMMca** [comment]
> > Was there a version 0.8.15? if so would that have been available 17 April 2020 between 0000 > 0300?
> 
> https://www.npmjs.com/package/meshcentral/v/0.8.15

This looks like that version updated bricked the install by deleting the whole directory then, we are running on Windows with the full installer, seems odd, however would be the only logical explanation for how the directory was totally removed (based on the time and backup history).

**Comment by nzalev** [comment]
> > > Was there a version 0.8.15? if so would that have been available 17 April 2020 between 0000 > 0300?
> > 
> > 
> > https://www.npmjs.com/package/meshcentral/v/0.8.15
> 
> This looks like that version updated bricked the install by deleting the whole directory then, we are running on Windows with the full installer, seems odd, however would be the only logical explanation for how the directory was totally removed (based on the time and backup history).

If you want to know for sure, npm normally logs on failures. On Windows, this is usually at the location `C:\Users<user>\AppData\Roaming\npm-cache`, but it depends on what user meshcentral is running as.

**Comment by GRIFFCOMMca** [comment]
Found the logs, only 1 listed from 2018....

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.20 and also use node 18 or above,
if issue persists after this, please reply back
