### ISSUE TITLE
User group permission change

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2522]
Dear Ylianst
I have created few user groups in my server. And assigned the permission of user consent. 

If I add /remove some users / new device groups into this group then  user consent will reset to default/ none. 

If I again edit the user consent option and tick mark all options it will not save properly. I need to first select few options and save then only system allow to select all user consent fields. 

Can you pls look into this and fix in upcoming versions?

**Comment by Ylianst** [comment]
Thanks for reporting this. Certainly a bug if the user consent resets.

**Comment by Ylianst** [comment]
Thank you for confirming. I will look into it.

**Comment by Ylianst** [comment]
Just added a fox for this, will be in MeshCentral v0.8.17 when it's next published.

**Comment by VINISHVV** [comment]
Wow. You are always too fast. 
Thanks for quick fix

**Comment by VINISHVV** [comment]
This issue fixed in latest version.

**Comment by Mfinadmin** [comment]
Dear All, 

Sorry for late response. Due to lock down I am unable to check official mails. 


This issue is fixed in latest version. 

@Ylianst  thank you so much....
