### ISSUE TITLE
AMT - Respond to ping setting when using policy

### ISSUE THREAD

**Issue by lovemonkeyz** [Ylianst/MeshCentral#2526]
Hello! 

I've been digging through guides and all the different configuration samples, and have not been able to find this particular setting.
I'm running MeshCentral without the agent, with the help of MeshCMD to activate devices and add them to the server. The device groups are set to activate CCM and nothing else. 

I noticed that when this is done, AMT gets its network settings set to "Respond to Ping/ICMP" enabled by default. Where might I be able to change this behavior? I do not want AMT to respond to ping, unless that is something MeshCentral requires, and if so; why?

Thank you!

**Comment by Ylianst** [comment]
No settings for this right now, but I can add this. At some point, I may have to built a full Intel AMT profile editor where you can then assign the profile to device groups.

**Comment by si458** [comment]
if you activate AMT WITHOUT using meshcentral manually yourself the default behaviour is to 'respond to ping/icmp'
sadly intel isnt doing much more with AMT so chances are we wont implement anything for this
a work around is connect the device to meshcentral, then go into the AMT tab, connect to the AMT then manually 'disable ping' yourself, but this would need to be done per device sadly
