### ISSUE TITLE
Wake-up Permission not working

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2528]
Dear Ylianst,

I have created few users with "**wake device**" permission for particular system.

When the user tried to wake-up the system it will not **turn on** the system. 

But the same system we can turn on /wake-up from admin id. 

Meshcentral Version -v0.8.16
DB -MongoDB
Server OS- Windows server 2019

**Comment by Ylianst** [comment]
Thanks for reporting this, I will check next time I can.

**Comment by Mfinadmin** [comment]
I am also getting same issue. 
Only Full administrator have privilege for wake-up device.  If we assign the rights to normal user then it will not works.

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
MeshCentral wake-on-lan feature has always had issues and we root caused the problem. There is a fix on the server and Bryan is working on a agent fix. Next version of MeshCentral v0.8.19 should work much better.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.19 with improved Wake-on-LAN support. it should work much better now. Feedback appreciated.

**Comment by VINISHVV** [comment]
Dear Ylian & Bryan,
Thanks for quick fix.
 it's works awesome.
