### ISSUE TITLE
Question - Related to "My Files" tab 

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2529]
Hi,

Please suggest the actual use of "My Files" tab ?

when opening this page, it will show options for file upload,  but  after successful upload nothing shown inside the folder.

Since i am new to MC, i don't have much knowledge related to this specific tab.

**Comment by Ylianst** [comment]
Weird, if you upload a file, it should show up. There is a quota system that can be enabled, so very large files would not be accepted. There is no big use for "My Files" right now, in the future it could be your personal dropbox like repository. It would also be useful if you want agent to all upload/download files, etc. So, may be interesting for the future.

**Comment by pggsadmin** [comment]
Dear Ylian - Uploaded files are not showing. If i activate file distribution Plugin then it works.

Since interesting features are incorporate in future, so i am closing this issue.
