### ISSUE TITLE
Question: MeshCentral and MeshCommander behaviour

### ISSUE THREAD

**Issue by tolino978** [Ylianst/MeshCentral#2530]
Hello

I recently installed MeshCentral (npm) on a server and started adding pure Intel AMT Clients to an Intel AMT, no Agent Group. I tried to add 6 Clients, 3 of them are Fujitsu's and 3 of them are HP Elitedesk 800 G3's. The Fujitsu's work perfectly and I can control them within MeshCentral. The HP's on the other hand don't work. I can "add" them in MeshCentral and they show up, but they are greyed out all the time and AMT detected never shows up. The usual lines in the Trace tool, which show up when you add a device, also don't show up. The local AMT Configuration on the Fujitsu's and the HP's is identical and the passwords are correct. 

Now interestingly, when I run MeshCommander on the same server, I can add those HP's and they work, meaning that it recognizes AMT and I can control them. 

Now to my actual question: Isn't the part of MeshCentral, that controls AMT Clients, identical to MeshCommander, or am I missing something? And do you have any idea, why those HP's wouldn't work, even if the configuration is identical to the Fujitsu's?

MeshCentral:            v0.7.68
MeshCommander:    v0.9.0-c
Server OS:                 RHEL 8.3

**Comment by Ylianst** [comment]
Interesting. When using MeshCommander, there is a gray/green/red circle next to each device. The color of that icon is based on the response to the RMCP ping that MeshCommader sends out. By any chance, does the HP devices show up as red? If this feature is not turned on in MeshCommander, you can turn it on in the help menu.

MeshCentral and MeshCommander do share a lot of code, but the device discovery is very different. MeshCommander will allow you to try to connect to a Intel AMT computer regardless, but MeshCentral will actively try to see if a AMT device is present at the IP/DNS name.

**Comment by tolino978** [comment]
I am using the node Version of MeshCommander on a Server and access it with a browser. I don't have that circle and I also don't have a Help menu. Is there another way, that I can check the response to the RMCP ping?
![image](https://user-images.githubusercontent.com/45803151/115559282-dddc9a80-a2b3-11eb-81fb-2da2fbba4d73.png)

**Comment by tolino978** [comment]
We just got this to work, it turns out that we also had to enable Port 623 vor RMCP to work properly.
