### ISSUE TITLE
Computer Stuck in pre-provisioning state

### ISSUE THREAD

**Issue by ihntremmel** [Ylianst/MeshCentral#2531]
I have been playing with meshcentral for a few days and have a test computer with the agent installed and running fine. I turned on fully automatic AMT settings and it switched to CCM. I used the USB setup to try to switch it to ACM and it's now stuck in a pre-provisioning state. I did a full unprovision from mebx and it's still stuck like this. I have another computer with the agent and did the same process and it's successfully running ACM.

latest MeshCentral installed on Ubuntu 20.04

**Comment by Ylianst** [comment]
In the console tab of the device, can you try the "amtconfig" and "amtevents" commands and report back when you see.

![image](https://user-images.githubusercontent.com/1319013/115642893-9d3f4a00-a2d0-11eb-9aa0-63a816f5f074.png)

If you run "amtconfig", you may need to try "amtevents" a few times to see what is going on and let it finish.

**Comment by ihntremmel** [comment]
![Screen Shot 2021-04-22 at 7 52 00 AM](https://user-images.githubusercontent.com/78761896/115709823-a6b3cb00-a33f-11eb-83a0-421faf4bec83.png)

This is after an hour.

**Comment by ihntremmel** [comment]
cleared everything again and got it.
