### ISSUE TITLE
Automatic Clipboard Transfer

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#2534]
Hey there.
I use [Apache Guacamole](https://guacamole.apache.org/) very often for a few projects I have.
Its a VNC/SSH/RDP web proxy that requires no agent on the clients. Very much like the idea proposed on #2516

To the point:
Guacamole has a great Clipboard support, using the [Async Clipboard API](https://www.w3.org/TR/clipboard-apis/#async-clipboard-api), which had limited support not so long ago, but as far I know is working out of the box on Chromium based Web browsers and Firefox right know (didn't tested it on any other platform)

To be clear: They did not remove the old way to copy/paste with a button that get/set the clipboard, just like meshcentral do right now. But in the cases that it's supported (that seems to be 99% of the browsers people use), is working perfect.

Maybe the MeshCentral crew could dig into this?

**Comment by Ylianst** [comment]
Hi. The two icons on the bottom right of the remote desktop tab should implement exactly this feature. It should be able to "push" and "pull" your clipboard using exactly the API you mentioned.

![image](https://user-images.githubusercontent.com/1319013/115922261-86643900-a431-11eb-991d-bcc47762c0e5.png)

The page attempts to detect browser support for this feature and you will not see the "push" button on FireFox, but will see both "pull" and "push" on Chrome. Let me know if that works.

**Comment by yomono** [comment]
Oh I didn't know it was using that api. 
Yes, the buttons you mention works as expected!
But what happens in Guacamole is that the clipboard is automatically, no need for push and pull buttons. Just copy (both remotelly and locally), and that's it.
That was my request. No big deal to push the buttons, of course. But no harm to ask neither for this little enhacement

**Comment by Ylianst** [comment]
I see. I think I need to poll the clipboards. This is certainly a security concern since you are going to be sending your clipboard content to the remote device, so something that I need to add as an opt-in option.

**Comment by yomono** [comment]
The security concern makes sense

**Comment by frankemann** [comment]
+1 for auto clipboard. Teamviewer also has this as default and makes us work fast.

**Comment by vitko-bg** [comment]
+ 1 from me for AutoSync Clipboard.
As an idea - there can be a button to switch AutoSync On or AutoSync Off (instead off Get/Send Clipboard) during a remote session.

**Comment by technoicon** [comment]
+1 been waiting for the for a while.  Must have feature for me.

**Comment by jdvmanen** [comment]
+1 for this option. Very useful!

Tip: clear the remote clipboard when remote access session ends. That would reduce the security issue seriously.

**Comment by VINISHVV** [comment]
+1 from me for AutoSync Clipboard.

**Comment by Mfinadmin** [comment]
Good suggestion. Definitely this will reduce time. 
Hope this will be considered soon.

**Comment by Ylianst** [comment]
Automatic clipboard feature was added to MeshCentral v0.8.63 in both the main web site and MeshCentral Router.

![image](https://user-images.githubusercontent.com/1319013/122061066-060fe380-cda3-11eb-8f65-e25845197d60.png)

![image](https://user-images.githubusercontent.com/1319013/122061037-fee8d580-cda2-11eb-8256-77aab8cf47d1.png)

**Comment by uldiseihenbergs** [comment]
Sorry for stupid question, but how can i enable this feature? just upgraded to 0.8.66, and i have no such checkbox on Remote Desktop Settings from browser..

**Comment by VINISHVV** [comment]
@uldiseihenbergs Please see the [comment](https://github.com/Ylianst/MeshCentral/issues/2534#issuecomment-861499158)

**Comment by uldiseihenbergs** [comment]
Yes, i see it, but mine looks different.
![image](https://user-images.githubusercontent.com/60253253/123451894-968dc580-d5e6-11eb-818f-0aaf35354107.png)

**Comment by yomono** [comment]
You found a nice bug 😄 
Did you tried turning off and on again?
Just kidding.. But did you tried with another web browser?
I remember the website ask for your permission to use the Clipboard the first time.. I'm not sure if maybe that permission affect the presence of the button itself there, but you could also try clean all cookies for the site

**Comment by uldiseihenbergs** [comment]
OK, looks like it need to be working on - checkbox is no visible on Firefox, but is visible on Chrome. and this annoying cmd window, when it syncs clipboard... so keep going with it :) if i can test more, just ask.

**Comment by W1BTR** [comment]
Works sending clipboard to the remote device, but copying on the remote device does not send it back to the local device.
