### ISSUE TITLE
Rename the default database for MySql install

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#2535]
I am running on a managed server, and the databases are all forced to be prefixed with <username>_

I currently have a db named <username>_meshcentral but when trying to start the server, it's looking for a database simply named meshcentral, fails to find it, therefore tries to create it, and the user does not have access to create a database.  

Can I get a pointer to what file(s) need to be edited to make meshcentral point to the correct database?  I tried editing config.json like so, but it didn't change things.

`    "MySQL": {

      "host": "localhost",
      "user": "<USERNAME>",
      "password": "<PASSWORD>",
      "port": 3306,
      "database": "<USERNAME>_meshcentral"
},`

Thanks!

**Comment by nzalev** [comment]
Presently, the database name 'meshcentral' is hardcoded in every query.

I have started working on a fix for this.

**Comment by mikecole79** [comment]
Thank you.  Are we looking at days, weeks, or months?  Not trying to be pushy, just trying to get a feel for where we're at.  

Thanks!

**Comment by nzalev** [comment]
> Thank you. Are we looking at days, weeks, or months? Not trying to be pushy, just trying to get a feel for where we're at.
> 
> Thanks!

I have something that looks like it will work. I am currently in the process of testing it.

**Comment by mikecole79** [comment]
You are the man!  Thank you!!

**Comment by Ylianst** [comment]
@nzalev made excellent improvements and I approved them. They will be in MeshCentral v0.8.18 when it next published tomorrow.
