### ISSUE TITLE
Nginx config and Meshcentral- Ubuntu 18.04 

### ISSUE THREAD

**Issue by miroslavjaros** [Ylianst/MeshCentral#2537]
Hello Ylian,
I tested my IP address with ubuntu 18.04 server with meshcentral and can not let's encrypt work, but when I install nginx and meshcentral was off I installed cerbot and it was few second and certificate is ok. So problems is not in configuration my network.
The problems is with my configuration meshcentral and nginx, can you provide minimal working configuration for Meshcentral and Nginx working step by step for Ubuntu ?
Or do you have any virtual image setup for this ? I would like test it but I am stuck whit this.
I think , I missing something important. I configure nginx first time, so for me is very complicated.

Case from
https://github.com/Ylianst/MeshCentral/issues/2532#issue-864269589

Miroslav

**Comment by Ylianst** [comment]
Hi. If you plan to use NGINX for your production server, you should not use the Let's Encrypt support that is in MeshCentral. Remove the "letsencrypt" section in the config.json and instead, put the following line in your config.json:

```
"tlsoffload": "127.0.01"
```

There the IP address is the internal IP address of NGINX. Then, add the following line in the domain section of the config.json:

```
"certurl": "https://myserver.com"
```

You need to provide a URL where MeshCentral can load the certificate presented externally. Then, you can have NGINX manage the certificate from Let's Encrypt.

**Comment by miroslavjaros** [comment]
> Hi. If you plan to use NGINX for your production server, you should not use the Let's Encrypt support that is in MeshCentral. Remove the "letsencrypt" section in the config.json and instead, put the following line in your config.json:
> 
> ```
> "tlsoffload": "127.0.01"
> ```
> 
> There the IP address is the internal IP address of NGINX. Then, add the following line in the domain section of the config.json:
> 
> ```
> "certurl": "https://myserver.com"
> ```
> 
> You need to provide a URL where MeshCentral can load the certificate presented externally. Then, you can have NGINX manage the certificate from Let's Encrypt.
> 
> You can look at [section 16 of the MeshCentral User's Guide for details](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf).

Thanks for respond, but it did not wok. I put my setup nginx and meshcentral mayby you can help me with config.
 NGINX

user www-data;
worker_processes 1;
pid /run/nginx.pid;
#include /etc/nginx/modules-enabled/*.conf;


events {
 worker_connections 1024;
}
http {
        ##
        # Logging Settings
        ##
#include /etc/nginx/conf.d/*.conf;
include /etc/nginx/sites-enabled/*;
access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log;


 # HTTP server. In this example, we use a wildcard as server name.
 server {
 listen 80;
# server_name _;
 location / {
 proxy_pass http://127.0.0.1:800/;
 proxy_http_version 1.1;

 # Inform MeshCentral about the real host, port and protocol
 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 }
 }
 # HTTPS server. In this example, we use a wildcard as server name.
 server {
 listen 443 ssl;
# server_name _;
 # MeshCentral uses long standing web socket connections, set longer timeouts.
 proxy_send_timeout 330s;
 proxy_read_timeout 330s;
 # We can use the MeshCentral generated certificate & key
ssl_session_cache shared:WEBSSL:10m;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;

 location / {
 proxy_pass http://127.0.0.1:4430/;
 proxy_http_version 1.1;


 # Allows websockets over HTTPS.
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 # Inform MeshCentral about the real host, port and protocol
 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 }
 }
}


And for Meshcentral
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to t$
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "mesh.ithope.cz",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AgentPong": 300,
    "TlsOfload": "127.0.0.1",
    "_RedirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "https://127.0.0.1/",
      "title": "mesh.ithope.cz",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "miroslav.jaros@ithope.cz",
    "names": "mesh.ithope.cz",
    "rsaKeySize": 3072,
    "production": false
  }
}

Thanks for help

**Comment by Ylianst** [comment]
The MeshCentral and NGINX configuration look good. In your setup NGINX is now taking care of the TLS certificate. You cannot use Let's Encrypt support in MeshCentral anymore, you have to look at the NGINX documentation for how to make it work with Let's Encrypt.

One thing you can do is use CertBot to get a certificate and add the certificate to your NGINX configuration. I have never done this, but you specify the certificate in NGINX like this:

```
		ssl_certificate			test-dsa-public.crt;
		ssl_certificate_key		test-dsa-private.key;
```

At this point, this is not a MeshCentral problem anymore. Go in NGINX and Let's Encrypt forums for help on getting a certificate in NGINX.

**Comment by lexisman** [comment]
Here is what I did: 
1. First I created a file and name it after the fqdn of the central server. Ex. mycentral.xxxxx.xx. On that file make sure you have a server block configure, you may use the first server block of you configuration:
server {
 listen 80;
 server_name _;
 location / {
 proxy_pass http://127.0.0.1:800/;
 proxy_http_version 1.1;

 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 }
 }
2. Save the file in the location /etc/nginx/sites-available.
3. Then follow the instruction here on how to use the letsencrypt with nginx:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
4. After you received the keys, you may add the rest of your config file, removing the part about ssl.
5. The certbot will do it for you. Also if you have a warning from nginx about port 80 not binding, remove the line listen 80;

**Comment by Ylianst** [comment]
FYI. Recently added a [YouTube video on configuring NGINX with MeshCentral](https://www.youtube.com/watch?v=YSmiLyKSX2I).

**Comment by miroslavjaros** [comment]
> FYI. Recently added a [YouTube video on configuring NGINX with MeshCentral](https://www.youtube.com/watch?v=YSmiLyKSX2I).

Thank you Ylianst, for perfect explain video but i think you can show other guys exactly combination Lets encrypt and Meshcentral Nginx with Ubuntu server. Windows is great system but for server linux is something like FERRARI . I worked 10 days to understood nginx with meshcentral. After that i see how start this combination because you all times show, how use generate certificate from meshcentral server.
In this moment i have testing infrastructure behand meshcentral and i have to thank you for great product. Is better and better in my eyes.

Lexisman wrote what i tried find before 20 days ago in short manual. And this is perfect manual for new one. Maybe it will by great video. And explain exactly different between nginx.conf and sites-enabled
And for file what you create setup use /etc/nginx/sites-available/your_domain

If you want I can tried help manual step by step how to install this combination and upload as manual for community.
1. Install ubuntu and setup 2. Install nginx 3. Install lets'encypt 4. Install Meshcentral with Mongo DB with setup for this.

Miroslav

**Comment by miroslavjaros** [comment]
> Here is what I did:
> 
> 1. First I created a file and name it after the fqdn of the central server. Ex. mycentral.xxxxx.xx. On that file make sure you have a server block configure, you may use the first server block of you configuration: Note: Read the instructions here on how to configure nginx https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04:
> 
> ```
> server {
>  listen 80;
>  server_name _;
>  location / {
>   proxy_pass http://127.0.0.1:800/;
>   proxy_http_version 1.1;
> 
>   proxy_set_header X-Forwarded-Host $host:$server_port;
>   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header X-Forwarded-Proto $scheme;
>  }
> }
> ```
> 
> 1. Save the file in the location /etc/nginx/sites-available.
> 2. Then follow the instruction here on how to use the letsencrypt with nginx:
>    https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
> 3. After you received the keys, you may add the rest of your config file, removing the part about ssl.
> 4. The certbot will do it for you. Also if you have a warning from nginx about port 80 not binding, remove the line listen 80;
> 
> Note: In the nginx.conf file the only things that you may want to change are the following:
> worker_processes 1;
> worker_connections 1024;
> server_names_hash_bucket_size 64; - enable this line

Thanks, that's exactly what I was looking for .

Miroslav
