### ISSUE TITLE
Unable to login on new install 0.8.19 - email already in use on different account.

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#2544]
New install, just created my admin user.  Shutdown the server, came back, and tried to login.  Got a message that I needed to verify my email address.  Clicking the link in the email brings me to the /checkmail page, which shows me the message

![image](https://user-images.githubusercontent.com/6404936/116005569-6745e280-a5bc-11eb-8602-57a21600ea35.png)

I'm unable to get logged back in, as that's the only user I've created, and I'm unable to validate the email, since whenever I change it and it sends out the request to verify, it automatically tells me that the email address has been used on a different account.

**Comment by Ylianst** [comment]
Weird. You can probably get around this by disabling the "smtp" section in the config.json. So change "smtp" to "_smtp" and start the server again.

  "_smtp": {
    "host": "xxxxx.com",
    "port": 25,
    "from": "xxxxx@xxxxx.com"
  }

When, you can login and go in "My Users" and fix any emails. You could also run your server like this:

```
node node_modules/meshcentral --user accountname
```

This will force all logins to be authenticated as "accountname", you can then go in the "My Users" page and just mark your email as being validated.

I am not sure how you got into this situation. If you can replicate it step-by-step so it can be replicated, I would take a look at what is going on.
