### ISSUE TITLE
Win + L Shortcut keys doesn't work when connected to Desktop

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#2545]
Hi,

Issuing Win + L does nothing when connected to a Widows desktop. It actually issues a L character to an open app is command prompt

![image](https://user-images.githubusercontent.com/47992409/116010680-cca0de80-a663-11eb-86bf-7751bfb4e34f.png)

**Comment by Ylianst** [comment]
Ok, worked on this. Next version of MeshCentral will have a padlock on the bottom right to lock the remote desktop.

![image](https://user-images.githubusercontent.com/1319013/116171341-6cd72180-a6bd-11eb-97e6-64172e77a3a5.png)

This will be in MeshCentral v0.8.20 when it's next published.

**Comment by Ylianst** [comment]
MeshCentral v0.8.20 was published this will feature, please let me know if it works and close this issue if it does.

**Comment by rowds15** [comment]
Ok thanks, Fixed.
