### ISSUE TITLE
event logging

### ISSUE THREAD

**Issue by adsorrentino** [Ylianst/MeshCentral#2547]
Hi Yilan
How could i enable detailed logging for events?
i.e, when i change the consent option for a group, it shows that the parameter changed. But it doesn't show previos value and new value.

thanks in advanec
Best regards
Alejandro

**Comment by si458** [comment]
this already partly exists, you click in the event and you get an events pop up window showing infomation
![image](https://github.com/Ylianst/MeshCentral/assets/765314/8cd42c57-5806-4557-aa9d-a1e5fd6509ac)
