### ISSUE TITLE
Limit the number of simultaneous Desktop connections for one user.

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2549]
Dear @Ylianst.

Since we are facing some bandwidth related issues.

Can you implement some restrictions like limit  number of concurrent /simultaneous desktop connections for the user.

**Comment by Ylianst** [comment]
I can look into it. As a short term fix, add these 3 lines in the "settings" section of the config.json

```
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": true
```

And this line in the domain section of the config.json:

```
    "minify": true
```

This should cut down on traffic with compression. Will probably generate 10% to 30% less traffic.

If you have many people watching the same remote desktop, add this to the "settings" section of the config.json:

```
"DesktopMultiplex": true
```

This will make the server split the remote desktop stream. [YouTube explanation here](https://www.youtube.com/watch?v=r0IfzuZgf3s).

**Comment by VINISHVV** [comment]
Many users asked this features.
Few cases are given below.
#2389
#2540
#2334

@Ylianst - please do the needful to implement some restrictions. I am not forcing but its beneficial for many users.

**Comment by Mfinadmin** [comment]
Dear Ylian, 
Can you add a restrictions through config.js to limit the number of concurrent remote session for a user.

**Comment by JOSEPHDEVASSIA** [comment]
Awaiting for some restrictions to reduce the server bandwidth.

**Comment by si458** [comment]
closing as duplicate #2389
