### ISSUE TITLE
Disable user input on remote computer during user session

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2550]
@Ylianst  - like other remote desktop tool,  is there any provision for disable remote computer keyboard and mouse.
This feature will helps to many support users  to complete there task quickly.

**Comment by vitko-bg** [comment]
+1 from me. Pls check if this issue is not duplicate :)

**Comment by Ylianst** [comment]
I am sure it's a duplicate. This is one Bryan has to look at. I know there have been requests to blank the screen and I don't think it's possible for us to do that. Just blocking the mouse/keyboard input may be possible, Bryan would have to investigate this.

**Comment by Ylianst** [comment]
Bryan seems to have should a way to lock user input on Windows. I just added support for this on the server side, but it will require a new MeshAgent version which will be released in the future. This is what is looks like when it will be supported. Again, this is not yet supported in the agent, Bryan is working on it.

![image](https://user-images.githubusercontent.com/1319013/116483291-a33aab00-a83b-11eb-86f5-d7f6ca0add44.png)

**Comment by plwc** [comment]
Nice work :)

Looking forward to seeing this working. Got a couple of people that just can't stop clicking stuff while I'm trying to help them.

**Comment by intranceitrust** [comment]
I would like to add a point of caution as there has been a large number of scam/fraud "support" groups utilizing the ability to blank out the screens and also lock keyboard and mouse controls on their victims devices. While this is a major issue that has been plaguing all the remote screen sharing tools for many years, It would be a shame to have MeshCentral be associated with the criminals choice of tools. Only needs a few misunderstood group of people who might try to associate MC with the fraudsters in their incorrect understanding of technology. Just wanted to flag this major rising problem to be considered before introducing a perfectly legitimate usecase.

**Comment by Ylianst** [comment]
This is a good point. It's create that considering how often it's being flagged, I do suspect that MeshCentral is being used in incorrect ways already. Would you go so far as not releasing this feature?

**Comment by Mfinadmin** [comment]
@Ylianst 
This feature is currently available in most of the remote management tools like team viewer and logmein. I don't think this will create such problems. Because if some one having access then they can access the terminal and command prompt. From there they can do any type of operations.

I suggest to implement this feature in meshCentral.if possible in addition to this please add a mechanism for enable or disable the same through config.js.

If the people don't like this feature then then can ignore the configuration. Those who needs this then they can go ahead with this.

**Comment by intranceitrust** [comment]
> This is a good point. It's create that considering how often it's being flagged, I do suspect that MeshCentral is being used in incorrect ways already. Would you go so far as not releasing this feature?

Perhaps consider the possibility of not enabling the ability to blank out the screens at the minimum. In my career of 20+ years in the IT business, never have i found a good legitimate reason that would require blanking out the screens when working with an end user device directly. The reasons on why you would need to blank out the screens when assisting or working with someone realtime on their end user device seems highly questionable. In the scams, typically the scammers get the victims to login to the bank accounts and blank out the screens to make changes as needed for short periods of times throughout their interactions. As i said, the technology is not to be blamed but abuse of the technologies should also be considered.

**Comment by krayon007** [comment]
We don't support blanking out the screen, because the way we implement screen sharing, it's not possible to.

**Comment by VINISHVV** [comment]
> > This is a good point. It's create that considering how often it's being flagged, I do suspect that MeshCentral is being used in incorrect ways already. Would you go so far as not releasing this feature?
> 
> Perhaps consider the possibility of not enabling the ability to blank out the screens at the minimum. In my career of 20+ years in the IT business, never have i found a good legitimate reason that would require blanking out the screens when working with an end user device directly. The reasons on why you would need to blank out the screens when assisting or working with someone realtime on their end user device seems highly questionable. In the scams, typically the scammers get the victims to login to the bank accounts and blank out the screens to make changes as needed for short periods of times throughout their interactions. As i said, the technology is not to be blamed but abuse of the technologies should also be considered.
> 

Disable keybord and mouse will not create any problem. Since it can be done through terminal as mentioned by @Mfinadmin 


This will be a very good used case for those who are handling large number of computers. Since some time the end users not allow the system admins to complete the installation / deployment of patches. This will definitely delay some projects. 

I hope this will be implemented using enable or disable though config.js.  If those who dislike this function then they can disable the same.

**Comment by Ylianst** [comment]
Ok. I think we will implement it, but I will be removing this feature on the public [meshcentral.com](https://meshcentral.com) server for sure.

**Comment by robclay** [comment]
@intranceitrust:

> In my career of 20+ years in the IT business, never have i found a good legitimate reason that would require blanking out the screens when working with an end user device directly. The reasons on why you would need to blank out the screens when assisting or working with someone realtime on their end user device seems highly questionable.

I have used logmein, and now meshcentral to remote in to my CSR's computer and do payroll. When I had logmein, I could bkank the screen while doing payroll.  With meshcentral, I no longer have the ability to blank my screens, so now only do payroll in the late evening when the office is 'expected' to be empty.  Just pointing out that legitimate reasons can exist.  [And for the record, I am not complaining - i pay much less for MeshCentral than I did for logmein! AND meshcentral is better at almost everything else I use it for... So I easily accept the tradeoff!  :) ]

**Comment by AntonAndreevichMoroz** [comment]
> @intranceitrust:
> 
> > In my career of 20+ years in the IT business, never have i found a good legitimate reason that would require blanking out the screens when working with an end user device directly. The reasons on why you would need to blank out the screens when assisting or working with someone realtime on their end user device seems highly questionable.
> 
> I have used logmein, and now meshcentral to remote in to my CSR's computer and do payroll. When I had logmein, I could blank the screen while doing payroll. With meshcentral, I no longer have the ability to blank my screens, so now only do payroll in the late evening when the office is 'expected' to be empty. Just pointing out that legitimate reasons can exist. [And for the record, I am not complaining - i pay much less for MeshCentral than I did for logmein! AND meshcentral is better at almost everything else I use it for... So I easily accept the tradeoff! :) ]

use web-rdp or rdp via MeshRouter.  Then the remote desktop will appear as locked.

**Comment by robclay** [comment]
@AntonAndreevichMoroz 

All good suggestions.  The Quickbooks is installed on a Home version, so no legal Microsoft RDP per se... but does Mesh provide their own that would blank the screen?  (I'll be slightly embarrassed, and joyous if yes...)  :)

**Comment by Mfinadmin** [comment]
> Ok. I think we will implement it, but I will be removing this feature on the public [meshcentral.com](https://meshcentral.com) server for sure.

Dear Ylianst,

Can we expect this by next month ?

**Comment by Mfinadmin** [comment]
Thanks, @Ylianst / @krayon007 for implementing the same in  v0.8.98

**Comment by githubbiswb** [comment]
I hesitate bumping this thread but also want to leave this here for anyone that might come behind and have some of these same questions

1. Screen blanking where you as an admin can do things under a users account they can't see is dangerous especially for a free product
2. I have only seen one example now of where this is useful and isn't being used poorly where an administrative policy should be changed or how the IT business is done
3. If you are sure you can't work around that problem and still need a legit solution to blank the screen, do the following

- Use mesh, install the agent as you do
- Find a VNC server that blanks the remote screen as an option, and install it, ultraVNC being the one I found, I am sure there are others
- Use mesh to connect to the VNC server either via MeshRouter or WebVNC

This allows mesh to give a feature, and still for free without it being mesh directly enabling it. Because you will need to have administrative privileges on the remote machine to get the VNC server installed and blank the screen. 

In our bad actor scenario, if the bad guy gets a hold of having administrative privileges, mesh would already be able to do a lot of damage with terminal anyway. So I don't see even presenting this as riskier than where we already were. 

Happy to be wrong though, feel free to critique.
