### ISSUE TITLE
Full window

### ISSUE THREAD

**Issue by frankemann** [Ylianst/MeshCentral#2553]
Would be great to have a button to get a real 1:1 window without any menu lines.
It's great when working for a longer period on a server (full screen without any border menu would work even better with automatic clipboard..)

**Comment by Mfinadmin** [comment]
Please try shift + full screen button for the same.

**Comment by Ylianst** [comment]
Right. Hold the shift button and hit the full screen button on the top right. Let us know if that works.

![image](https://user-images.githubusercontent.com/1319013/116456296-f5b5a080-a816-11eb-8bf3-f606ded52925.png)
