### ISSUE TITLE
amtconfig "Device group not found"

### ISSUE THREAD

**Issue by ihntremmel** [Ylianst/MeshCentral#2554]
I was trying to configure an HP Elitedesk with AMT and I had built an AMT only group, but the devices just say CIRA: Connecting to mps.domain.com. So I tried loading the agent on the computer to see if it gave any other info when I run amtconfig from the mesh agent.  When I run it now I get this:
![Screen Shot 2021-04-28 at 1 18 29 PM](https://user-images.githubusercontent.com/78761896/116445777-3e278b00-a824-11eb-9875-9f02225cc3e2.png)
Intel ME Status shows Activated ACM, TLS and I had to enter the credentials from amtactivation.log. The AMT features are greyed out.  I had used a USB to ACM activate.

The computer is plugged in with it's only ethernet card which is the built-in that has AMT onboard.  I can connect to :16992 locally.  The computer shows

**Comment by sysadmin-us** [comment]
@ihntremmel Because after activating the amt device, you have moved the meshcentral group from one group to new another one that is why the error showing device group not found on the console, @Ylianst If we move the amt device group, CIRA connectivity not established in meshcentral why???

**Comment by sysadmin-us** [comment]
So is there currently a supported way (or workaround) to move a CIRA device to a new group and have it reconnect or is this just something that eventually needs to be fixed?
