### ISSUE TITLE
SSH browser support for local device group

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2558]
Continuing with request #2516 , please add the ability to connect to SSH without using Router. The same as for other nodes through the Terminal tab.

**Comment by VINISHVV** [comment]
I think Ylianst already working on this before raising this issues.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.25 with an all new web based SSH client. You need to activate it in the config.json and will cause a new "SSH2" module to be installed from NPM. After that, it should allow SSH sessions to remote devices with or without agent.

![MC2-SshClient](https://user-images.githubusercontent.com/1319013/116655536-22190c00-a940-11eb-9b94-04ec86f96d92.png)

Feedback appreciated.

**Comment by AntonAndreevichMoroz** [comment]
@Ylianst is very cool. I have already installed the update. The Web-SSH link came up, but it shows a 404 error when navigating.

**Comment by AntonAndreevichMoroz** [comment]
Oh, don't worry. It was my mistake, I found it. Everything works perfectly. Thank you.

**Comment by Ylianst** [comment]
Oh. That is a bug. The "Web-SSH" option should not show up on the web page unless it's activated. Fixing now.
