### ISSUE TITLE
Web-RDP with NLA

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2559]
Continuing with request #2516 . Please consider adding an NLA ("Network Level Authentication") operation to the Web-RDP. It will be great as it will not have to make unnecessary settings and will increase security.

**Comment by Ylianst** [comment]
I am hoping that I can add TLS to the connection to support NLA ("Network Level Authentication"), but I am not sure if RDP works that way or not. I will need to experiment.

**Comment by AntonAndreevichMoroz** [comment]
if I can help you do not hesitate to say so.

**Comment by Ylianst** [comment]
I did a first attempt at adding NLA... but it's more than just adding TLS. "[node-rdpjs-2](https://www.npmjs.com/package/node-rdpjs-2)" does not currently support NLA.

**Comment by Tomatoschewps** [comment]
Hi, I've tried local group today for windows servers and yes, we are blocked by NLA.
So just to say that we are impatient to have NLA support because disabling it on our infra is not an option for us ...

In other word, 👍 for this issue ;)

**Comment by AntonAndreevichMoroz** [comment]
Greetings.  can a replacement implementation solve this issue.  Here they write that this is possible in their code.  https://github.com/bloomapi/node-freerdp

**Comment by AntonAndreevichMoroz** [comment]
Greetings.  I saw a recent commit on the subject of NLA. @Ylianst  Is there any news on this issue?  I tried connecting after upgrading to 1.0.12.  But I still have an error.

**Comment by gaalos** [comment]
It might useful if you can repair it, Because rdp permit multiple sessions. instead of agent use one session.
Best regards

**Comment by Ylianst** [comment]
Update on this. Last last night after a week of difficult work, I did get RDP NLA ported for NodeJS and it seems to work great. I am going to work on cleaning up the code and a release hopefully today.

**Comment by PrplHaz4** [comment]
> Update on this. Last last night after a week of difficult work, I did get RDP NLA ported for NodeJS and it seems to work great. I am going to work on cleaning up the code and a release hopefully today.

Great to hear - your ability to get these big things through so quickly is really amazing!

Link to discussion here: #3914
