### ISSUE TITLE
Feature Request: "Add Administrators" checkbox for new device groups.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#256]
Even as an admin I still have to ask my users to add me to any new device groups they create. It would be great to have a checkbox when adding a new device group which would give admin users access. Perhaps an entry in the configuration file could toggle the default state of that checkbox (checked or unchecked) to cover different use cases of MeshCentral.

Also, I seem to recall reading another feature request for batch adding of users to device groups, and for a way to add users without having to type their full username, such as a user list with checkboxes. I can't seem to find the request, but I was wondering if this was still a planned feature.

Anyways, thanks again for this awesome project! I have a good twenty users now who never want to see TeamViewer or LogMeIn again after two weeks with MeshCentral.

**Comment by Ylianst** [comment]
Thanks. All good suggestions. For the checkbox, the site administrator is not always "admin", I would have to make that configurable. I could make it a checkbox and make it completely mandatory. I will see what I can do.

For the name suggestion, that is not difficult if you are administrator since the web application already has the list of all of the users. However, for normal users, I am not sure I want to give them a user list unless the server is configured to allow that. Seems like a fun add-on, I will take a look at this.

**Comment by Ylianst** [comment]
As a first step, published MeshCentral v0.3.5-o. You can now batch add users to a device group. Just type comma separated names. They will all get the same specified permissions.

![MC2-BatchUserAddToGroup](https://user-images.githubusercontent.com/1319013/58659706-82c4e780-82d8-11e9-82fe-b18158fe55c7.png)

**Comment by Ylianst** [comment]
As a second step, published MeshCentral v0.3.5-p with user name suggestion box that changes as you type when adding users to a device group.

![MC2-UserAutoComplete](https://user-images.githubusercontent.com/1319013/58665753-6c258d00-82e6-11e9-86cc-05c77ca3b139.png)

**Comment by MatinatorX** [comment]
Wow, that's awesome! I'll update my MeshCentral server tomorrow night and give it a whirl!

I understand about not giving non-admin users a user list. I think it mostly depends on the use case. In a small organization where you already know everyone has a user account, listing them while adding users is just a time-saving feature. In a big organization, I can see it being a bit of a security issue if non-admin users can identify who else has an account.

**Comment by sorvani** [comment]
this is related to #185 ?
