### ISSUE TITLE
McAfee Endpoint Security deleted MeshCmd64-signed.exe file while updating MC to new version 0.8.23

### ISSUE THREAD

**Issue by mmhparvez716** [Ylianst/MeshCentral#2562]
I was updating a test MC server to newest version 0.8.23. Before loading the webpage McAfee Endpoint Security deleted following file: "C:\Program Files\Open Source\MeshCentral\node_modules\.staging\meshcentral-7ee17c2f\agents\MeshCmd64-signed.exe". Afterward I couldn't find the .....\.staging folder. Similar kind of deletion happened during another MC installation but server ran okay, that's why I didn't pay that attention. McAfee both characterise them as Trojan and detection name like Artemis!xxxxxxxxxxxx.
Is there any item that I can whitelist so that on next update McAfee won't block or delete anything.
Thanks for your support.

**Comment by Ylianst** [comment]
If the signed version of the agent is not present, MeshCentral will serve the unsigned version. This is the unfortunate problem with open source remote management software, people use the agent to do bad things. The best solution is to submit [a false positive to McAfee](https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&articleId=TS103032&_afrLoop=1001785775561&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25#!%40%40%3FshowFooter%3Dfalse%26_afrLoop%3D1001785775561%26articleId%3DTS103032%26leftWidth%3D0%2525%26showHeader%3Dfalse%26wc.contextURL%3D%252Fspaces%252Fcp%26rightWidth%3D0%2525%26centerWidth%3D100%2525%26_adf.ctrl-state%3Dr40e0m2ch_9).

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.27 with new self-signed certificate. Also note that I have purchased a code signing cert and hoping to user it for all open source projects except the MeshAgent (MeshCentral Router, Installer, Assistant, Commander).

**Comment by mmhparvez716** [comment]
Thank you for the update. I updated to the newest version and didn't see McAfee blocking anything.
