### ISSUE TITLE
Feature request: Add SSH key authentication with web-ssh and linux terminal.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#2567]
I've some remote systems which are only ssh key authentication allowed due security concerns. So no password authentication is possible.

It would be very nice to have the possibility to configure (upload existing key into meshcentral vault) and use ssh key authentication to login automatically through Linux Terminal and/or web-SSH.

**Comment by Ylianst** [comment]
The "SSH2" library supports this, so certainly possible to do.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.3 with support for SSH keys. Let me know if it works.

![MC2-SSHKeySupport](https://user-images.githubusercontent.com/1319013/129319633-24113b58-21b3-4f5c-a179-146179ea9293.png)

**Comment by hunter-nl** [comment]
@Ylianst I'm sorry I couldn't react earlier.

I tried to use it. But I stuck with a disabled OK button.
![image](https://user-images.githubusercontent.com/5203309/129862347-fd8819e3-54cf-40d9-b9af-53a55cd7c3fa.png)

And when this is working, can this also be added to devices with an agent on linux/MacOS? So it is not only usable for local-devices.

**Comment by hunter-nl** [comment]
@Ylianst Any progress on this issue? I really depend on key authentication at devices which accepting only key authentication.

**Comment by hunter-nl** [comment]
@Ylianst In browser console I see this error on the OK button:
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.pushManager.subscribe')
```

**Comment by joeldeteves** [comment]
Sorry for asking a dumb question but how do I enable this? I can't find it in the docs and I see no such option as what's in the screenshot.

Running version 1.0.21
