### ISSUE TITLE
noVNC stopped working

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#2569]
Running version 0.8.16 on windows server 2012 r2

For some reason I cannot connect using the noVNC.
checking the trace windiws it seems to be connecting ok, but the noVNC stays on  "connecting..."
![image](https://user-images.githubusercontent.com/55733884/116720359-5f32dc00-a9dc-11eb-9e2d-195e586428b0.png)

I have another server with version 0.8.5 which works fine ( so this is no browser issue)

**Comment by Ylianst** [comment]
I will take a look. I probably broke something when adding the new Web-SSH feature.

**Comment by Ylianst** [comment]
I just tested MeshCentral v0.8.26 and I can't find any issues with noVNC. I tried local connections using the new "local device" group and over the Internet thru the MeshAgent - both work fine for me. When using VNC with the MeshAgent, you need to make sure your VNC server can receive connections thru the loopback port.

If this is still a problem with the latest version, I will need more information to replicate this. You can download the trace using the little arrow icon on the top right and remove any private info. That may help get more information.

![image](https://user-images.githubusercontent.com/1319013/116735112-ef542f80-a9a2-11eb-9d9b-f721eb927e3f.png)

**Comment by Mfinadmin** [comment]
I am using latest version v8.26 and able to access novnc for both local and remote systems.

**Comment by Ylianst** [comment]
Thanks for reporting back!
