### ISSUE TITLE
Documentation of websocket protocol

### ISSUE THREAD

**Issue by nicolasduteil** [Ylianst/MeshCentral#2570]
Hi. Is there any documentation available on the protocol used for meshrelay.ashx ?

Thanks

**Comment by Ylianst** [comment]
No documentation currently on meshrelay.ashx. There is source code to MeshCmd and MeshCentral Router that make use of it and I could consider writing up documentation if there is a good use for it.

**Comment by nicolasduteil** [comment]
Thanks. Use cases could be integration of the meshrelay in third party apps. I'll check MeshCmd & MeshCentral Router, as well as existing web UI, which should contain everything I need for now.

**Comment by Ylianst** [comment]
Ok. Note that I just added "localrelay.aspx" in addition to "meshrealy.aspx" to perform server relays to local devices in the same network as the server. Both work the same way.

Basically you connect the web socket with the right URL arguments to authenticate and indicate what route you want. You then wait and get the letter "c" or "cr" to indicate the you have a connection. "cr" indicates that the server is recording the connection.

Once you get the connection notice, you can send binary data into the websocket and it will be sent to the target, binary data coming back is from the target. String type data is used for control, so things like WebRTC setup, "PING" and "PONG" will be in JSON string format over the websocket. That is not "payload" data.

Hope that helps,
Ylian
