### ISSUE TITLE
Malwarebytes Endpoint Protection blocks upgrade of Meshadmin

### ISSUE THREAD

**Issue by zackrspv** [Ylianst/MeshCentral#2571]
Hello there :)

The latest version of Malwarebytes Endpoint Protection allows Mesh-Admin to be installed, but refuses to allow it to install any updates - in fact it keeps quarentining the files -.- I added it to the exclude list, but same action. I would usually complain to MBAM, but they said to check with your team first - they state it's because the file isn't digitally signed?

--Phillip

**Comment by Ylianst** [comment]
Hi. Not sure what "Mesh-Admin" is? Can you be more specific on the version and what files are being blocked?

This is an open source project and the files are signed using a self-signed root. Your free to sign the files yourself if you have a code signing certificate.

**Comment by zackrspv** [comment]
No worries - that answered my question well enough - we can get into the habit of signing the code with our enterprise code signing - and my apologies, i'm so used to talking short hand here in shop, i forgot to break out of that habit for posting here lol When I mean Mesh-Admin i'm referring to the mesh admin center (web interface) and mesh agent lol please ignore my silliness. 

But, we'll go ahead and just go forward with just signing them whenever we do our routine updates. 

Thanks!

**Comment by Ylianst** [comment]
The unsigned and self-signed agent executable are in the "node_modules/agents" folder. Signing is standard operation.
