### ISSUE TITLE
Desktop video recording: Convert .mcrec for a different file format

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2573]
I start recording while connected. After stopping, a file with the .mcrec extension is downloaded. In request #956 I found how to reproduce this file. Can you tell us whether the situation with the translation has changed since that time? Is it possible to get avi or mp4 from mcrec file now?

**Comment by Mfinadmin** [comment]
@AntonAndreevichMoroz 

I think it's not implemented. May be it's related to the screen capture technology used by meshcentral and other parameters like file size and server performance etc.....

**Comment by Jacky0400143** [comment]
@Ylianst 

It will be nice if we could transfer convert it into motion JPEG or some of common format for playback.

Because I now think of a stupid way to use another Video Record software to record during the playback process.

**Comment by Ylianst** [comment]
FYI. In upcoming MeshCentral v0.8.74, you can convert the .mcrec to .webm format. That will play in VLC Player and other players.

![MC2-WebMRecordings](https://user-images.githubusercontent.com/1319013/124401819-8b225480-dce0-11eb-807a-278d5457ce8b.png)

**Comment by AntonAndreevichMoroz** [comment]
Unfortunately, I don't have this button. Do I need to include or install something additionally?
![image](https://user-images.githubusercontent.com/51225180/131898687-4ffdef40-0d3d-43b1-a419-f4eedfbc4fe9.png)

**Comment by VINISHVV** [comment]
> Unfortunately, I don't have this button. Do I need to include or install something additionally? Server version 0.9.18
> ![image](https://user-images.githubusercontent.com/51225180/131898687-4ffdef40-0d3d-43b1-a419-f4eedfbc4fe9.png)

@AntonAndreevichMoroz - Can you switch the language to English and check it once.
I think it's not handled in all languages.

**Comment by AntonAndreevichMoroz** [comment]
Oh yes, you are absolutely right. The button appeared in English localization.

**Comment by fernandogobah** [comment]
No show button in the version 0.9.77 with language English.

**Comment by MarkStephan89** [comment]
> No show button in the version 0.9.77 with language English.

same here in version 1.1.22

**Comment by trmdi** [comment]
Excuse me, why doesn't my player have that button?
MeshCentral version: 1.1.33, language: English.

**Comment by si458** [comment]
@trmdi care to elaborate on that? What button?

**Comment by trmdi** [comment]
> @trmdi care to elaborate on that? What button?

The Convert button in this screenshot: https://github.com/Ylianst/MeshCentral/issues/2573#issuecomment-873678625

**Comment by si458** [comment]
@trmdi yeh i just re-read the post sorry having mad day!
Yeh never seen that button before, let along code to do any converting?
Maybe @Ylianst didn't add the code and forgot?
Will look into it

**Comment by trmdi** [comment]
For some reason, it's only displayed in Chrome?
https://github.com/Ylianst/MeshCentral/blob/7d59210d059d5667735771c3b1bb3b39559a97e0/views/player.handlebars#L451

**Comment by trmdi** [comment]
I use Edge btw. Please don't forget it. 😂

**Comment by si458** [comment]
Edge/chrome, same engine under the hood, just a different fancy front end, haha

**Comment by alltechbob** [comment]
> Edge/chrome, same engine under the hood, just a different fancy front end, haha

Turns out even though edge is chromium, I still had to download and open it in chrome to get the button.

**Comment by si458** [comment]
@alltechbob I quickly checked the code. It checks if the browser is CHROME and displays the browser, however if u remove the line and show the button 24/7 it actually works in firefox/edge but the is 1 bug i discovered, u can't run the convert twice!
You must refresh the browser page in-between for some reason

**Comment by si458** [comment]
enabled option to show `convert to webm` for any browser https://github.com/Ylianst/MeshCentral/commit/d9262f7c9da03881fd25c363f717f452d06e117d
plz be aware! from my testing you can only run the button ONCE!
if you try running it a second time, it generates a javascript error and wont work.
you MUST refresh the webpage after clicking the button once
this seems to be a BUG but the convert code/framework is a third party and hasnt been updated in years!
so this bug will need investigating!
