### ISSUE TITLE
Troubleshooting a client that is often unavailble

### ISSUE THREAD

**Issue by paristotle** [Ylianst/MeshCentral#2574]
I have one client that often appears disconnected in the Meshcentral control panel. Here's what I tried below. Any guidance or info on logs (and where to find them)etc, or troubleshooting workflow would be appreciated.

**Computer:** Up to date Windows 10 pro
**Problem**: Often is 'greyed out' in the portal, or appears available but I can't connect to it. (When I restart the service the problem is resolved)

**What I tried**:
- Installed another RMM and confirmed that the device is actually online and it's not an issue with the Internet
- I factory reset the computer and chose not to restore any third part AV or apps
- Installed a new meshagent
At this point I'm fairly certain that it's the client computer and not the server since other computers on the same Mesh install don't seem to have this problem. I don't know enough about how Mesh works or where logs are stored to go any deeper

**Comment by Mfinadmin** [comment]
Dear @paristotle 

If you are facing issues in windows PC, then Please try below troubleshooting method and post the result. 


1.Make sure the agent is installed in your system. 
2. Normally the installation  folder contain 4 files like db, MeshAgent, log file etc...... 
3. Check the MeshAgent service is running / stopped. 
4. If the MeshAgent service is running then just stop the service once. 
5. Open CMD and go to MeshAgent installation  folder ( C:\Program Files\Meshagent ) 
6. Then manually run the MeshAgent in Command prompt by using command "MeshAgent -run"

**Comment by paristotle** [comment]
Thanks. Here's what I found

1. I was able to start it only when I use an elevated command prompt. Otherwise it was unable to open the database
2. Once I started it with the run command it gave me
```
 connecting to: wss://myurl.com:443/agent.ashx
 connected
Server verified meshcore... Launching meshcore...
```
At that point it was connected to the Mesh server.

**Comment by Mfinadmin** [comment]
To run the MeshAgent  service it's require elevated command prompt.

In this case agents connected properly. Can you share below details once. 

Meshcentral Version
Agent Version / Compile time ( available @ details tab)

**Comment by paristotle** [comment]
The agent version is 0.2.1.3, and the creation date of the agent is April 20, 2021. 
However the Meshagent -info command gives me  Dec10 2020 as the compile date.

I cleared/uploaded the new core.
I keep thinking that this has something to do with the laptop resuming from sleep. The other connected clients are all desktops set not to sleep. And since this happens again after a wipe and reinstall I'm wondering what issue local to this station is causing this. Thanks for your help.

**Comment by Mfinadmin** [comment]
@paristotle - Thanks for reporting back. 
Can you confirm once, when the Laptop is resume functional from sleep mode whether it's showing online / not.

**Comment by OutbackMatt** [comment]
> Also you just try below method once.
> 
> 3. Select clear core and wait one minute.
> 4. Upload default core.

Had a machine that would show as online for desktop (and not actually connect), but offline for console
Did the above two steps remotely, and presto the machine connects to desktop correctly

Excellent thanks

**Comment by paristotle** [comment]
Thanks. When the computer resumes from sleep I can see it as available in Mesh but I can't connect. I use my secondary remote access solution to connect and restart  the the service and works from there on in. 
I have tried to clear the core and upload a default core but that doesn't change the above problem for me

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.20 and also use node 18 or above,
if issue persists after this, please reply back
