### ISSUE TITLE
Change Notification Type

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2576]
I'm not sure how possible this is but assuming it's something that can be done, can you change the type of notification sent when using the bell icon at the bottom right of the Desktop tab to be an alarm in Windows 10? It seems like these notifications are often hidden due to various manual or automatic rules present in Windows 10's notification settings but I'd like to make sure these notifications get through no matter what is happening on the remote computer.

I imagine a similar setting is available on the Mac but I'm not in front of mine to check exactly what it would be called at the moment.

Thanks!

**Comment by si458** [comment]
you cant currently change what type of notification gets sent from that button

BUT

if you go into your list/columns view, tick devices, then use the 'group action'->'device notification'
you can change what style gets sent!

but i will look at changing this for you so you can specify what type of notification gets sent

**Comment by si458** [comment]
done! 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/6cd2e049-c923-4578-9968-8a30106caea4)

**Comment by PetieM** [comment]
I completely forgot about this request but this is still going to be great for when the kids aren't paying attention and it's time for dinner or bed so thank you for getting this implemented!

**Comment by si458** [comment]
no worries, lets not rush this!
you can test each notification type right now using the batch method as described above https://github.com/Ylianst/MeshCentral/issues/2576#issuecomment-1879345434

but hopefully be added in next release 👍 

p.s. dont forget to donate to help support me! - https://www.si458.co.uk/2024/01/05/donation/

**Comment by PetieM** [comment]
Alert box is missing from that view for me but the other two seem to function and the message box option is exactly what I originally wanted as it stays on screen and pops up even with DND enabled.

**Comment by si458** [comment]
> Alert box is missing from that view for me but the other two seem to function and the message box option is exactly what I originally wanted as it stays on screen and pops up even with DND enabled.

ah yeh sorry, i added the 'old style alert box' last month, so cant remember if it was in the latest 1.1.16 NOW RELEASED or it will be included in next release 1.1.17, but glad u found it works!
