### ISSUE TITLE
Device Group share.

### ISSUE THREAD

**Issue by JOSEPHDEVASSIA** [Ylianst/MeshCentral#2579]
Hi,

I am using meshcentral in our office from last 2-3 month. 
Since In India, due to covid restrictions most of the areas are under lockdown and we are running our support team with limited staffs.

In Meshcentral can you implement some options to share device group for a selected user group or user for a short period (like individual device sharing)

**Comment by AntonAndreevichMoroz** [comment]
Not long ago there was a similar request #2521

**Comment by Ylianst** [comment]
Duplicate and the title is not clear, so I will close this. Feel free to thumbs up #2521 to indicate you want it implemented.
