### ISSUE TITLE
Feature Request : Linux terminal scroll

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#258]
The Linux terminal only shows about 25 lines, so if you're performing an "ls -al" for example on a folder that holds a couple of hundred files, you only see the last 25. Would it be possible to have a scroll feature that allows you to scroll up to review those lines that have scrolled off screen?

**Comment by Ylianst** [comment]
That is a good request.

**Comment by D4V3M0NK** [comment]
and, from what I can see, 0.3.5-n doesn't "more" correctly - not sure if this is related.

**Comment by Ylianst** [comment]
Can you give an exact example  of "more" that does not work?

**Comment by D4V3M0NK** [comment]
Apologies - I really should think more before I post...
I have a file that is about 1200 lines long. When I "more testfile" in a standard terminal, I see one screen-worth (eg ~30 lines) of the file and then the screen pauses: I have to press a key before it then shows me the next 30 lines of the file. 

At the moment, "more testfile" probably runs through the whole file rather quickly to the point that I probably only see the last (~25) lines of the file.

**Comment by Ylianst** [comment]
Yes, that is also what I see. You don't see the rapid scrolling of the text, just the end result.

**Comment by Ylianst** [comment]
Going beast mode today: MeshCentral v0.3.5-t now has 800 lines of scroll back buffer on the terminal - Enjoy!

![MC2-Terminal](https://user-images.githubusercontent.com/1319013/58736755-d5bf9d00-83b3-11e9-9dbf-9babf1be162b.png)

**Comment by Ylianst** [comment]
Arg. Terminal with scrollback does not show up correctly on Chrome, working on that now.

**Comment by Ylianst** [comment]
All fixed in MeshCentral v0.3.5-u.

**Comment by D4V3M0NK** [comment]
Lovely, thank you sir.
