### ISSUE TITLE
URL "pass" argument is kept after the login page.

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2582]
@Ylianst Earlier, you described how to log in using Login Tokens.

```
https://meshserver.com/?user=~t:ezTCXifX7YycJ8CO&pass=ALBsgjZfTc756m1VmO0t
```

_Originally posted by @Ylianst in https://github.com/Ylianst/MeshCentral/issues/2533#issuecomment-825876825_

When I decided to use this, I found that after authorization, the user parameter is removed from the URL, but the pass parameter is not. However, it follows all links when navigating inside MeshCentral.

For example
```
https://meshserver.com/?viewmode=4&pass=ALBsgjZfTc756m1VmO0t
```

I think this violates security. After all, Login Tokens are needed to get a valid cookie. Did I understand correctly? Then there is no point in showing pass for a long time.

**Comment by Ylianst** [comment]
I will fix this, but I want to mention that using "user=" and "pass=" in the URL is not secure to start with and certainly not recommended.

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.8.28. The "pass" argument is removed from the URL after login. No changes on the server side.

**Comment by Ylianst** [comment]
MeshCentral v0.8.28 was just published. Please close this if it works.

**Comment by AntonAndreevichMoroz** [comment]
All right. Thank you.
