### ISSUE TITLE
Linux Terminal view breaking

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#2585]
i occasionally use the screen app to keep services running in the background (occasional clean up jobs which i run manually). Ive noticed when i use meshcentral for terminal connections screen breaks. I am still able to use it but simple things such as pressing tab to autofill commands just creates gibberish or partial inputs. This doesn't happen when connecting to the device directly via putty. 

Im sure i need to provide more info but im not certain what i need to send. If you let me know i can gather the info and send it to you.

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
