### ISSUE TITLE
Other Settings not available in guest sharing

### ISSUE THREAD

**Issue by dani717** [Ylianst/MeshCentral#2588]
Hello Ylian,

is it possible to show other settings in the guest sharing access, I usually use the other settings if for some reason my keyboard is not working, some times a VM inside an agent controlled machine, I found that if I use "Use Remote Keyboard Map" this fix my issue, but when I use guest sharing I don,t see the options. I wanted to see if it is possible to add it from config or other area or if this can be included in updates 

Regards,
Dani

**Comment by Ylianst** [comment]
Ok, just added it. Will be in MeshCentral v0.8.29. Once published text it and if it works, please close this issue. Thanks.

![image](https://user-images.githubusercontent.com/1319013/117185239-7a13a080-ad8e-11eb-9b88-752de7e63349.png)

**Comment by dani717** [comment]
Thank you your awesome, I report back once it is released and tested

**Comment by dani717** [comment]
I can confirm the issue is now resolved after adding the options, I open the agent machine, then open ESXi inside that machine with a VM with this option the keyboards works, tested on multiple machines. Thank you for this quick fix 

regards,
Dani
