### ISSUE TITLE
Placement of Add Agent within GUI a little misleading?

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#259]
I've just added a new device to a group, but couldn't find it in MC afterwards. Only through a little trial and testing I realized that when I selected **Add Agent** to the device group I thought I would be adding it to, I was actually adding it to the group below.

As I look at this, I wonder if it would make more "sense" (I'm British, so take _that_ with a pinch of salt!) to alter the interface slightly so that devices are grouped either within "boxes" (see the mock up : "Dave's Local VMs" with 6 nodes) or perhaps move the "Add CIRA/Agent" text to alongside the name of the device group (see mock up of the top group of 10 nodes). IMHO this would then make MC extremely obvious which group you'd be adding the agent to.
![deviceGroupingMeshCentral0 3 5-n](https://user-images.githubusercontent.com/7572742/58653338-56a26a00-82ca-11e9-889f-6e52046d2d41.png)

**Comment by Ylianst** [comment]
Well... now that I see the problem... I can't unsee it. I still need to make it look good. I will try things out and see what I can do.

**Comment by D4V3M0NK** [comment]
It's really not that urgent : perhaps #179 would make things easier to find the system if one is as dopey as I am ...

**Comment by PathfinderNetworks** [comment]
I agree with D4V3M0NK - moving the links over to the left side (just to the right of the group name) would make things a lot cleaner.  Especially when viewing the site full screen on a high resolution monitor.

**Comment by Ylianst** [comment]
Ok. I will make the change tomorrow.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-q with changes for this. Feedback appreciated.

![MC2-Devices](https://user-images.githubusercontent.com/1319013/58723372-c2e6a180-838e-11e9-87c7-c773d7f89804.png)

**Comment by D4V3M0NK** [comment]
I think this works perfectly, thank you Ylian. Will close this issue
