### ISSUE TITLE
Improvement: Link to devices from the group page.

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2590]
All the time that we have been using MeshCentral, it seems logical to go to the device group and from there follow the link, where only computers of this group will be displayed. And we will never get used to the fact that there is no such link.
This is a minor improvement but adds a lot of convenience. As I see it, these are links to a regular list of devices, but with the auto filter applied only for this group. If it is possible of course.

**Comment by Ylianst** [comment]
Good request.

**Comment by Ylianst** [comment]
Just added the device list to the device group. Will be in MeshCentral v0.8.31 when it's next published. Please test and close this issue if it works.

![image](https://user-images.githubusercontent.com/1319013/117510395-d9191700-af40-11eb-938d-a3b9d982bcc7.png)

**Comment by Ylianst** [comment]
MeshCentral v0.8.31 is out.

**Comment by AntonAndreevichMoroz** [comment]
It looks great. Thank you so much
