### ISSUE TITLE
Collapse all and expand all buttons

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2593]
When working with a large list of groups and devices, even all possible sorts and filters often do not help. For convenient work, it would be useful to have 2 buttons "Expand all groups" and "Collapse all groups".
Thanks in advance.

**Comment by vitko-bg** [comment]
It is implemented from long time ago. Try right click on the group ;)

**Comment by nzalev** [comment]
@AntonAndreevichMoroz @vitko-bg 
In particular, if you right click the group, it will give you `select all` / `select none`

If you right click the small arrow next to the group name, it will give you the option
![Screenshot from 2021-05-06 15-19-08](https://user-images.githubusercontent.com/63608819/117353918-c0482d00-ae7e-11eb-97bd-a8ea8a378af4.png)

**Comment by AntonAndreevichMoroz** [comment]
@nzalev Oh, that's great) I would never have thought of right-clicking there myself. Thanks for the tip. I think I'm not the only one) Maybe it makes sense to move them to the top panel, just like the "Select All" button?
![mesh](https://user-images.githubusercontent.com/51225180/117354420-f787ff80-aeb9-11eb-9fa2-67841df399ce.jpg)

**Comment by nzalev** [comment]
@AntonAndreevichMoroz 
I have the button done - I am just getting the behaviour right when manually collapsing/expanding all.

![Screenshot from 2021-05-06 16-31-45](https://user-images.githubusercontent.com/63608819/117362082-d529be00-ae88-11eb-88c0-0c705db467ca.png)

![Screenshot from 2021-05-06 16-31-55](https://user-images.githubusercontent.com/63608819/117362093-d8bd4500-ae88-11eb-8c5f-16c3720b81fb.png)

It is up to @Ylianst to approve & merge - I don't know how he feels about changes to the UI.

**Comment by Ylianst** [comment]
Nice work by @nzalev. New button on top bar will be in v0.8.30.

![image](https://user-images.githubusercontent.com/1319013/117390222-9bfe4780-aea2-11eb-970e-0de85bc29041.png)

**Comment by AntonAndreevichMoroz** [comment]
This works great.
