### ISSUE TITLE
[Enhancement Request] - Show details of temperature sensors (mouseover or what sensor)

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#2596]
So, for some devices, there are a variety of temperature sensors being shown, however, there's no mouseover or other details for us to see what sensor is being used.. Example (this is an HP Laptop):
![image](https://user-images.githubusercontent.com/7637082/117372738-e077ec00-ae7e-11eb-9158-74f25399870e.png)
There are a variety of temperatures being shown, but, don't really see an easy way to identify what is what.

Thanks!

**Comment by si458** [comment]
would hovering over the temperature and showing the InstanceName be ok?
this will at least help identify them a little bit

can you also run the following cmd with admin and let me have a few different outputs from different machines?
`wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature,InstanceName`

**Comment by mjpcomp** [comment]
> would hovering over the temperature and showing the InstanceName be ok? this will at least help identify them a little bit
> 
> can you also run the following cmd with admin and let me have a few different outputs from different machines? `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature,InstanceName`

That would be better than nothing 👍

**Comment by si458** [comment]
@mjpcomp pr is done for you!
Do u have any macs spare? I could do with an output from `powermetrics -s smc` to verify the naming on the sensors

**Comment by NiceGuyIT** [comment]
>  Do u have any macs spare? I could do with an output from `powermetrics -s smc` to verify the naming on the sensors

That won't work because `smc` is not a metric, at least not on M1. Below is from macOS Ventura 13.6 (22G120) (M1).

`man powermetrics`
>      -s `samplers`, --samplers `samplers`
>             Comma separated list of samplers and sampler groups. Run with -h to see a list of samplers and sampler
>             groups. Specifying "default" will display the default set, and specifying "all" will display all
>             supported samplers.

`powermetrics -h`
```text
Usage: powermetrics [-i sample_interval] [-r order] [-t wakeup_cost]

  Gather and display CPU usage statistics (divided into time spent in
  user mode and supervisor mode), timer and interrupt wakeup frequency
  (total and, for near-idle workloads, those that resulted in package
  C-state exits), and on supported platforms, interrupt frequencies
  (categorized by CPU number), package C-state statistics (an indication
  of the time the core complex + integrated graphics, if any, were in
  low-power idle states), CPU frequency distribution during the sample.
  The tool may also display estimated power consumed by various SoC subsystems,
  such as CPU, GPU, ANE (Apple Neural Engine).
  Note: Average power values reported by powermetrics are estimated and may be
  inaccurate - hence they should not be used for any comparison between devices,
  but can be used to help optimize apps for energy efficiency.

The following command-line options are supported:

    -h | --help                  show this message

    -A | --show-all              Enables all samplers and displays all the
                                 available information for each sampler.

    -a | --poweravg <N>          display poweravg every N samples (0=disabled) [default: 10]
    -b | --buffer-size <size>    set output buffer size (0=none, 1=line)
    -f | --format <format>       display data in specified format [default: text]
    -i | --sample-rate <N>       sample every N ms (0=disabled) [default: 5000ms]
    -n | --sample-count <N>      obtain N periodic samples (-1=infinite) [default: -1]
    -o | --output-file <file>    output to file [default: stdout]
    -r | --order <method>        order process list using specified method [default: composite]
    -s | --samplers <samplers>   comma separated list of samplers and sampler groups
    -t | --wakeup-cost <N>       assume package idle wakeups have a CPU time
                                 cost of N us when using hybrid sort orders
                                 using idle wakeups with time-based metrics


    --show-initial-usage         print initial sample for entire uptime
    --show-usage-summary         print final usage summary when exiting

    --show-extra-power-info      unsupported power info (may change between releases)

    --show-pstates               show pstate distribution (XCPM only)
    --show-plimits               cpu limiting information
    --show-cpu-qos               show per cpu QOS breakdowns
    --show-cpu-scalability       show per cpu workload scalability
    --show-hwp-capability        show per cpu-thread HWP estimated efficient and guarateed frequencies (instantaneous)
    --show-process-coalition     group processes by coalitions and show per coalition information
    --show-process-wait-times    show per-process sfi wait time info
    --show-process-qos-tiers     show per-process QOS latency and throughput tiers
    --show-process-io            show per-process io information
    --show-process-gpu           show per-process gpu time
    --show-process-netstats      show per-process network information
    --show-process-qos           show QOS times aggregated by process
    --show-process-amp           show per-process AMP information
    --show-process-energy        show per-process energy impact number
                                 This implicitly enables sampling of all the
                                 above per-process statistics.
    --show-process-samp-norm     Show CPU time normailzed by the sample window.
    --handle-invalid-values      powermetrics will output invalid=true rather
                                 than abort when it sees invalid values.
    --hide-cpu-duty-cycle        hide CPU duty cycle data
    --unhide-info <samplers>     comma separated list of samplers to unhide (backwards compatibility)

The following sort orders are supported by --order:

    pid         process identifier
    wakeups     total package idle wakeups         (alias: -W)
    cputime     total CPU time used                (alias: -C)
    composite   weighted hybrid of package idle
                wakeups and CPU time used          (alias: -O)

The following output formats are supported by --format:

    text        human-readable text output
    plist       machine-readable property list, NUL-separated

This tool also implements special behavior upon receipt of certain signals
to aid with the automated collection of data:

    SIGINFO                 take an immediate sample
    SIGIO                   flush any buffered output
    SIGINT/SIGTERM/SIGHUP   stop sampling and exit

The following samplers are supported by --samplers:

    tasks             per task cpu usage and wakeup stats
    battery           battery and backlight info
    network           network usage info
    disk              disk usage info
    interrupts        interrupt distribution
    cpu_power         cpu power and frequency info
    thermal           thermal pressure notifications
    sfi               selective forced idle information
    gpu_power         gpu power and frequency info
    ane_power         ane power and frequency info

and the following sampler groups are supported by --samplers:

    all           tasks,battery,network,disk,interrupts,cpu_power,thermal,sfi,gpu_power,ane_power
    default       tasks,battery,network,disk,interrupts,cpu_power,gpu_power,ane_power
```

`thermal` output is below. Without `--sample-count`, it loops indefinitely. Unfortunately, "Nominal" doesn't exactly represent temperature.

```bash
$ sudo powermetrics --samplers thermal --sample-count 1
Machine model: MacBookAir10,1
OS version: 22G120
Boot arguments:
Boot time: Wed Oct  4 13:49:21 2023



*** Sampled system activity (Tue Oct 17 18:35:32 2023 -0400) (5001.23ms elapsed) ***



**** Thermal pressure ****

Current pressure level: Nominal
```

**Comment by NiceGuyIT** [comment]
From: <https://discussions.apple.com/thread/254104626?answerId=257710034022#257710034022>

> I was on the line with apple support for quite some time to find out why
>
>     sudo powermetrics  -- samplers mc |grep -i "CPU die temperature"
>
> which worked on my old MacBook pro did not work on my new M2 MacBook air.  I keep getting "unrecognised sampler: the sampler smcsmc" message in terminal.  I was told **the new macs don't support the  sampler smc**.  Is there another way to check on CPU (and GPU)die temps?

Answer: <https://github.com/exelban/stats>

**Comment by si458** [comment]
@NiceGuyIT oh dear that's not good!!!
So the old command must be for intel macs only then...
Can u try https://iboysoft.com/news/check-mac-temperature.html ?
I Need to get an a single output showing cpu die temperature or gpu die thermal !?

**Comment by NiceGuyIT** [comment]
This [image](https://discussions.apple.com/thread/254751005?answerId=258862088022#258862088022) shows the temp is a list of many temperatures in the M1/M2 CPUs due to their architecture.

One of the threads mentioned [Hot](https://github.com/macmade/Hot/) which is on GitHub, and this is where the rabbit hole begins.
- [Hot](https://github.com/macmade/Hot/tree/main/Submodules) imports a few submodules, one of which is [Sensors](https://github.com/macmade/Sensors/).
- [Sensors](https://github.com/macmade/Sensors/tree/main/Submodules) imports more submodules, one of which is [SensorKit](https://github.com/macmade/SensorsKit/).
- [SensorKit](https://github.com/macmade/SensorsKit/tree/main/Submodules) imports more submodules, one of which is SMCKit.
- [SMCKit](https://github.com/macmade/SMCKit) provides a command line (below) that _might_ provide what you're looking for.

`brew install --HEAD macmade/tap/smc-dump` requires XCode to compile the program.

```text
$ brew install macmade/tap/smc-dump
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).

==> Tapping macmade/tap
Cloning into '/opt/homebrew/Library/Taps/macmade/homebrew-tap'...
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 152 (delta 24), reused 34 (delta 11), pack-reused 104
Receiving objects: 100% (152/152), 6.98 MiB | 5.94 MiB/s, done.
Resolving deltas: 100% (76/76), done.
Tapped 15 formulae (32 files, 8.6MB).
Error: macmade/tap/smc-dump is a head-only formula.
To install it, run:
  brew install --HEAD macmade/tap/smc-dump

$ brew install --HEAD macmade/tap/smc-dump
smc-dump: A full installation of Xcode.app 8.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: smc-dump: An unsatisfied requirement failed this build.
```

Without providing a precompiled binary, your only option is to decipher the [SMCKit](https://github.com/macmade/SMCKit/blob/main/SMCKit/SMC.m) code and implement it yourself. Since the code imports Apple headers, I doubt that's an option.

----

With all that said, one of the forum posts mentioned that the "Current pressure level: Nominal" output is an aggregate of all the temperature sensors. Maybe that's sufficient for M1/M2 Macs because the actual temperature is a list of 20+ sensors; which one do you choose?

**Comment by si458** [comment]
Need to keep open as mac version might not work, but Windows/Linux ones are ok

**Comment by si458** [comment]
closing now as i have a new macbook pro 2019 (intel) and its showing the temperatures!
the is no way still at the moment to get the temps for ARM macs without librarys or new agent build
