### ISSUE TITLE
Remote Deployment

### ISSUE THREAD

**Issue by baclaeys** [Ylianst/MeshCentral#2597]
I have deployed MeshCentral within our network of 500+ desktops and servers, and so far it has been working really well.  I have gotten a lot of positive feedback from my coworkers.  One feature that I would love to see is an integrated way method of deploying the agent remotely.

**Comment by Ylianst** [comment]
Nice. If you run the agent with "meshagent.exe -help" you should see this on Windows

```
C:\Program Files\Mesh Agent>meshagent.exe -help
Mesh Agent available switches:
  run               Start as a console agent.
  connect           Start as a temporary console agent.
  start             Start the service.
  restart           Restart the service.
  stop              Stop the service.
  state             Display the running state of the service.
  -signcheck        Perform self - check.
  -install          Install the service from this location.
  -uninstall        Remove the service from this location.
  -nodeid                       Return the current agent identifier.
  -resetnodeid      Reset the NodeID next time the service is started.
  -fulluninstall    Stop agent and clean up the program files location.
  -fullinstall      Copy agent into program files, install and launch.

                    The following switches can be specified after -fullinstall:

     --WebProxy="http://proxyhost:port"      Specify an HTTPS proxy.
     --agentName="alternate name"            Specify an alternate name to be provided by the agent.
```

You should be able to auto-deploy by running `meshagent.exe -fullinstall` on each computer. Of course, you have to do this using some other system. Hope that helps.

**Comment by baclaeys** [comment]
Thank you for your prompt reply.  I have used this method to successfully deploy the agent with a third party tool, but they seem clunky.  Is there anything that you have used to remotely deploy software in an Active Directory environment?

**Comment by AntonAndreevichMoroz** [comment]
The easiest option is to make a bat file:
1.check if the agent has already been installed
2.start installation via -fullinstall from a shared folder

Add to startup scripts in GPO

Just a few lines and you're done. What solution do you expect? msi package? I think there are programs that can compile such a package quite simply. The most famous of them is NSIS

**Comment by yomono** [comment]
> The easiest option is to make a bat file:
> 1.check if the agent has already been installed
> 2.start installation via -fullinstall from a shared folder
> 
> Add to startup scripts in GPO
> 
> Just a few lines and you're done. What solution do you expect? msi package? I think there are programs that can compile such a package quite simply. The most famous of them is NSIS

There is also "Inno installer", which I find even easier to use than NSIS.
But yes, I still think a simple bat with a GPO is the simplest way to go (or some variation of this aproach). Doing more than that is just overkill for such a simple task

**Comment by AntonAndreevichMoroz** [comment]
@yomono Inno Setup is a good product, but unfortunately it only creates exe installers, which are difficult to distribute via GPO. And I agree with you that it is too difficult for the task at hand. It is not clear what the author meant and what he wanted to hear.
