### ISSUE TITLE
Possible Andriod Agent  Issue when using domain

### ISSUE THREAD

**Issue by tprinslo** [Ylianst/MeshCentral#2599]
I run and connect the android agent on both Phone and Tablets successfully when it is not a connection to a domain 
If I try to do a desktop connection to a Android device on the MeshCentral portal with a domain the desktop connection will not work.
Running a trace on the server shows that there could be a path issue. I would expect the path to be mtf only as this is the name of the domain but the 404 error points to mft/mft
```
“11:22:49 AM,"dispatch","DispatchEvent, node/mft/…..,*,mesh/mft/…………."
11:22:29 AM,"web","404 Error /mft/mft/meshrelay.ashx/.websocket?p=2…………l"
```

In the config.json file the domains are declared as follows

```
"domains": {
    "": {
      "title": "Remote Assistance",
	  "orphanAgentUser": "nccadmin"
    },
    "rdata": {
	"title": "R-Data",
	"title2": "Remote Support",
	"newAccounts" : 0
    },
    "mft": {
	"title": "MFT Property",
	"title2": "Remote Support",
	"newAccounts" : 0
    }
```

**Comment by AntonAndreevichMoroz** [comment]
@tprinslo 
Show your config file. Perhaps there is a problem. Are you using a reverse proxy in front of MeshCentral?

**Comment by Ylianst** [comment]
Thanks for reporting this. I am working on it now.

**Comment by Ylianst** [comment]
I see the same issue and working on a fix. It will be an new APK and update on Google Play.

**Comment by Ylianst** [comment]
Fixed. I just updated the ADK to version 1.0.13 on the [MeshCentral.com download page](https://meshcentral.com/info/downloads.html). I also submitted the fix to the Google Play store and will be available when they approve it.

If you can verify the fix works, please close this issue. Thanks.

**Comment by tprinslo** [comment]
Thanks Ylianst, will test as soon as it is updated in Playstore

**Comment by tprinslo** [comment]
Hi Ylianst, I can confirm it is working....great work
