### ISSUE TITLE
Feature Request : MC GUI Inactivity Timeout

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#260]
When using the MC web interface, add an inactivity timeout (configurable) so that a user is automatically logged out if they've been logged in without doing anything.

**Comment by Ylianst** [comment]
Should the timeout also apply administrators?

**Comment by D4V3M0NK** [comment]
IMHO, yes : with the possible caveat that could be an option that permits an extended timeout for admins, but I personally think that's too granular. Inactivity is inactivity and all should abide by the same requirements.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-q with user session idle timeout support. Add this in the domain section of the config.json:

`"UserSessionIdleTimeout" : 20`

Timeout is in minutes. When a user is under 5 minutes remaining, a timeout warning will show up on the upper right. Activity will clear the timeout. Feedback appreciated.

![MC2-IdleTimeout](https://user-images.githubusercontent.com/1319013/58723216-62effb00-838e-11e9-9224-ad47fe6d1583.png)

**Comment by D4V3M0NK** [comment]
Ylian,
Is the inactivity timeout based just on the browser/tab window, or for the entire system itself?  I've added a 5min timer to my system, changed tabs and continued working with something else (same system) and when I come back to MC about 15 mins later, I'm still logged in - and I don't see the remaining time shown.

**Comment by D4V3M0NK** [comment]
Looks and works perfectly. Beer being sent in the mail to you sir.

**Comment by TitovLab** [comment]
Please tell the difference between UserSessionIdleTimeout and SessionTime?
And how do the settings of these two parameters interact with each other?

**Comment by Ylianst** [comment]
Excellent question. The "SessionTime" is the timeout of the login cookie that is stored in the browser. So, as long as the session is valid, you can leave and come back or hit refresh on the page and not have to login. The UserSessionIdleTimeout is completely different, it monitors user activity on the web page and if they are not active for a while, it will logout and additionally invalidate the login cookie.

I think the main use of UserSessionIdleTimeout is to prevent users from keeping long standing websocket connections to the server. Without it users could keep a web page + websocket connection open to your server forever.
