### ISSUE TITLE
Root redirect shouldn't need the key

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#2606]
Hello, I've set `loginKey` and `rootRedirect`.
However, when I try to go to / without the login key set, it only displays "Not Found" now.

I believe that the root location should not require the key if the rootRedirect is set.

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.8.32.

**Comment by Ylianst** [comment]
MeshCentral v0.8.32 was published. Check if it works and close this issue if it does.

**Comment by mwllgr** [comment]
Will try to confirm asap. I am using the `typhonragewind/meshcentral` Docker image (is an official one planned?) so it could take a few days.

Is the loginKey needed for the agentInvite too?
