### ISSUE TITLE
Gitter chat or discussion for MeshCentral

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#2607]
Hi,

I think it would be nice if MeshCentral had a chat on Gitter (see https://gitter.im/home/explore#createcommunity) - it even works with Element. I sometimes feel like creating a new issue for a simple question is just too much, Gitter is a perfect place for these things.

You could link to the Gitter chat in the README with a badge.

**Comment by yomono** [comment]
there is a reddit forum for that

**Comment by mwllgr** [comment]
Gitter is just a bit more user friendly as it's _just_ for chatting and has Github integration (and login). I'd need a seperate account and use their website. With Gitter, I could use my local Element installation.

**Comment by si458** [comment]
the is also an unoffical discord channel for anybody interested - https://discord.gg/8wHC6ASWAc
