### ISSUE TITLE
Save User & Password SSH terminal agentless devices

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2608]
Hi,

The new feature of embedding the SSH-web in the Terminal tab is great.

Would it be possible to save the user and password of the terminal on the server? 
It would be very convenient not to have to put the username and password in each connection.

Thank you!

**Comment by AntonAndreevichMoroz** [comment]
This is a good idea. I think it should be extended not only to SSH, but also to RDP after RDP is also in the Desktop tab

**Comment by Ylianst** [comment]
This was just added in MeshCentral v0.8.44. Let me know if it works.

![MC2-RememberSSH](https://user-images.githubusercontent.com/1319013/119199517-0e912a80-ba40-11eb-83aa-94d46664d433.png)

**Comment by lergolas** [comment]
Thanks. 

Works perfectly!
