### ISSUE TITLE
Login page full screen background image

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2609]
Dear @Ylianst 

I don't know whether you consider this request but still i am asking.

Currently i have done few changes in login screen to for the background images showing in fullscreen mode. But when i update the server the changes will revert back to normal settings. 

Can you please incorporate the changes to show fullscreen background image in Login screen through config.js / any other method ?

**Comment by Ylianst** [comment]
In 2 days, I have a new [YouTube videos on MeshCentral customization](https://www.youtube.com/watch?v=Hg4CnrkFUzU) that will be coming out on the [MeshCentral YouTube channel](https://www.youtube.com/c/meshcentral).

See this image for customization options.

![image](https://user-images.githubusercontent.com/1319013/117693202-a0608400-b172-11eb-81d1-7dfecb822334.png)

Let me know if this is ok.

**Comment by VINISHVV** [comment]
Dear Ylian,

I am already using this customization. But there is no option for set the "welcomePicture" in Fullscreen mode.

**Comment by Ylianst** [comment]
Ok. I can work on that.

**Comment by Ylianst** [comment]
Ok, added the `"welcomePictureFullScreen": true` option to the config.json to allow for a full screen image. This will be in MeshCentral v0.8.34.

![MC2-LoginBackground](https://user-images.githubusercontent.com/1319013/117716117-0c9cb100-b18e-11eb-8783-0db130293f1b.png)

**Comment by VINISHVV** [comment]
PNG  extension is less priority. since we can utilize this time for many other features.

**Comment by Ylianst** [comment]
I just tried a .png file and it worked for me. In my case, I have:

```
      "welcomePicture": "desk.png",
      "welcomePictureFullScreen": true,
```

and the picture shows correctly.

![image](https://user-images.githubusercontent.com/1319013/117863511-b476b500-b248-11eb-9f57-f014f9ca8156.png)

Make sure the file name has the right capitalization if you are running the server on Linux, "desk.png" and "Desk.png" are different files.

**Comment by VINISHVV** [comment]
Dear Ylians - thanks it's working fine.
