### ISSUE TITLE
TypeError: Cannot read property 'on' of null

### ISSUE THREAD

**Issue by black3dynamite** [Ylianst/MeshCentral#261]
Operating System: Fedora Server 30
MeshCentral version: 0.3.5-r

None of my devices are showing up under My Devices. And I'm seeing this everytime I start meshcentral server. And if run `node /opt/meshcentral/node_modules/meshcentral` it will continuously repeat those messages.

When I click on `Show server error log`, it shows no error log.

![meshcentral_bug](https://user-images.githubusercontent.com/22382399/58727845-ab191880-83a2-11e9-97dd-8ad894ecbf5b.png)

**Comment by rroseselavy42** [comment]
getting same thing rolled back to 0.3.5-i and connecting again. 

Operating System: Ubuntu 18.04
nodejs version v12.3.1

**Comment by Ylianst** [comment]
WORKING ON IT!!!

**Comment by rroseselavy42** [comment]
thanks! if there is any other debugging information I can paste that would be helpful I can dig a bit

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.5-s with a fix for this. Seems this happens on latest NodeJS only, fixed it for all versions.

**Comment by rroseselavy42** [comment]
update fixed it for me

**Comment by black3dynamite** [comment]
I'm on MeshCentral version 0.3.5-u and its working for me.
Thanks!
