### ISSUE TITLE
Agent removal not working

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2613]
Currently using v 0.8.33

When I select a remote (Linux) system, select Actions > Uninstall Agent and then confirm, the remote system turns grey in the UI and on the remote itself the agent service stops. However, it doesn't disable or remove the service on that remote. If I reboot the remote, the agent starts back up again and the remote appears back in the MC2 UI.

If it helps, the agent was originally installed using the wget process

**Comment by si458** [comment]
closing as stale,
please use the latest version 1.1.20 and also node 18 or above and try again,
if your issue persists then please reply back
