### ISSUE TITLE
Can't find translated strings

### ISSUE THREAD

**Issue by luismanson** [Ylianst/MeshCentral#2614]
Hello, thank you very much for your work on this!

 I want to edit some sentences in Spanish, there is this one string I can't find. 

Its the string for "type" in a particular dialog. The word itself is translated ok, but when you click "Add new device group", the second field label reads "Send Text" (in Spanish) which does not make any sense.
I can't find any strgings with those words. 

I'm running: v0.8.33

**Comment by Ylianst** [comment]
Hi. Improvements to the translations are very much welcome. The translation string are in this file:

```
node_modules\meshcentral\translate\translate.json
```

You can also get the [latest translation file here](https://github.com/Ylianst/MeshCentral/blob/master/translate/translate.json). Feel free to make edits and send the [result back to me](https://www.meshcommander.com/contact-information). I will update in the next version. Make sure to tell me what language you made changes to.

Thanks,
Ylian

**Comment by luismanson** [comment]
Hello Ylianst i think there are no translation for mail templates, is that right?
Like: https://github.com/Ylianst/MeshCentral/blob/master/emails/account-invite.html

**Comment by Ylianst** [comment]
All mail templates are translated, the strings are all in "translate.json"
