### ISSUE TITLE
Search options

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#2619]
Hello,

We have a large number of clients on our server.

When we add a new customer, it becomes difficult to find it.

Can you add search by MeshID?

Add a button "copy the MeshID" on the agent mesh?

thank you

**Comment by VINISHVV** [comment]
@laboiteajb - having some confusions with MeshID.  Are you looking for a new requirement like Teamviewer / Anydesk ID ?

Currently i am running Meshcentral with 9000 agents and i have installed Meshcentral Assistant application.
If any help required then end users are able to request the same through Assistant application and the same will populated in meshcentral dashboard without delay.

**Comment by laboiteajb** [comment]
no, we have a park with pc with the same name.
Searching by ID allows you to find them faster and change their name

it's just when installing the agent

**Comment by laboiteajb** [comment]
OK, thanks.

I have a good example. I have more than 30 PCs which have the same OS name, same username ...
these are cloned pc.

Searching by agent ID would allow me to find them faster to rename them.

Currently, when I add a pc, I restart the meshagent service to see which pc this disconnected from meshcentral

**Comment by Ylianst** [comment]
By agent id, you mean you want a search like:

```
nid:xxxx
```

Where xxx is part of the NodeID, the value that is in the URL when you click on a device?

**Comment by laboiteajb** [comment]
cool thank
and by meshid in .msh is not possible ?

**Comment by Ylianst** [comment]
So, I am asking what search feature you want added. Please detail the feature request as exactly as possible.

**Comment by laboiteajb** [comment]
ok
Take an example, I have 100 cloned PCs. (same OS name, same user)

If I add a new pc, impossible to find it among the 100

the idea would be to search for it by meshid in .msh

or, add a function in meshcentral which warns of a new pc:
a pop up that redirects to the new pc
or make the icon flash or change color for x time

thank you
(tell me if it's good for you, my english is not good)

**Comment by vitko-bg** [comment]
Have you tried a Group Notification option? It will notify you on agent connection/disconnection. It works well for me. Cannot include screenshot as on the go :)

**Comment by laboiteajb** [comment]
@vitko-bg 
this option displays the new agent or each existing agent who reconnects?

I just tested, I am not notified when an existing agent is connected

**Comment by VINISHVV** [comment]
@laboiteajb -  Try meshcentral assistant  once.

**Comment by vitko-bg** [comment]
@laboiteajb First you have to activate notification options for your account

![image](https://user-images.githubusercontent.com/59362521/118245134-504a3000-b498-11eb-90cf-81a9caaeb58f.png)

After that configure the Group Notification 

![image](https://user-images.githubusercontent.com/59362521/118245052-33156180-b498-11eb-81b3-e979f54bc86d.png)

**Comment by Ylianst** [comment]
@laboiteajb The "meshid" is a identifier for the device group, so it would not work to identify new devices. All devices with the same "meshid" will all start in the same device group when they connect.

**Comment by MailYouLater** [comment]
@laboiteajb I have a suggestion that might help you.

When installing the agent, add the device to a temporary Device Group, that only exists for newly connected devices.  Once they've connected, you can change their configuration however you need to, including moving the device to the Device Group it belongs in.  This way, you can always identify a new device, simply by the fact that it's appearing in that particular Device Group.
