### ISSUE TITLE
Linux Terminal - nano Ctrl+W closes browser tab

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#262]
MC 0.3.5-r on Ubuntu 18.04.2 Server with Chrome 70.0.3538.77
I've just logged into MC to control the MC server itself, with the intention of altering the inactivity timeout from the default 20mins to 5mins. When I opened up the Linux Terminal, I used nano to edit config.json (normally I use "vi") but when I use Ctrl + W to utilize nano's "where is" feature, the browser tab that I was using closes. When I open a new tab and then go to MC to log in again, I am able to go straight to My Devices without logging in.  

Main bug here is the Ctrl + W closing my tab. Second "notice" is the not requiring to log back in again when I open a new tab (on the same browser session): I'm sure that's because the session is still valid and the browser is keeping it alive...

**Comment by Ylianst** [comment]
Your right about CTRL-W, I see the same. Working on it now.

For the second thing, your right, the session is not expired yet. So if you hit refresh or open a new tab, your are still in. If you hit "logout" it will clear the session.

**Comment by Ylianst** [comment]
Wow, looking at forums, there does not seem to be a way to disable CTRL-W in Chrome/FireFox, but will keep checking. This is annoying.

**Comment by Ylianst** [comment]
I added ALT-F4 and CTRL-W to the special keys drop down on remote desktop in the next version. For terminal, it's already in the drop down provided and it works for me. However, this is far for ideal.

**Comment by D4V3M0NK** [comment]
![vi](https://user-images.githubusercontent.com/7572742/58733661-faaf1280-83a9-11e9-8e50-ad3abd338cbd.png)
 :smiley:

**Comment by Ylianst** [comment]
Ok, closing this one as I think this is the best with can do given browser limitations. If anyone has suggestions to capture CTRL-W, please re-open.
