### ISSUE TITLE
Multisessions in Meshcentral

### ISSUE THREAD

**Issue by derdavin** [Ylianst/MeshCentral#2620]
Hello Community,

I am an absolutely avid Meshcentral user.

Is it possible to use multisessions without using multiple tabs in the browser?

I sometimes work on several machines at the same time.

e.g. on 5 different Windows desktops.

or on 3 Linux systems via the terminal.

I thank you very much for an answer.

Kind regards
Davin Hörnig

**Comment by vitko-bg** [comment]
Not sure what do you mean exactly, but I think you can try MC Router for this purpose. In this case you will have different sessions on different windows on the task bar.
