### ISSUE TITLE
Issue uploading .lnk or .url files to client 

### ISSUE THREAD

**Issue by juststevestuff** [Ylianst/MeshCentral#2622]
When trying to upload a .lnk or .url file to a client via "Files", it changes the name of the file to viewform[1] with no extension.  The shortcut doesn't work on the client it's uploaded to.  Tried renaming the shortcut to name.lnk or name.url after upload and it still will not launch properly.  Tried on multiple clients.

I was originally on stable v0.7.89 with this issue so I upgraded to latest v0.8.34 to see if the problem remained.  The problem is still present. 

All other file types I tried seem to work fine.

**Comment by Ylianst** [comment]
If I remember correctly, this may be a browser security issue. Let me know what browser your using and try a different browser (FireFox, Edge, Chrome) to see if it happens. If I recall, this is a Chrome specific problem and I can't do anything about it.
