### ISSUE TITLE
Is this tool used for OS monthly Patching

### ISSUE THREAD

**Issue by rajsathivada** [Ylianst/MeshCentral#2627]
Hi Team,

Actually we are planning to implement this tool in our environment. Shall we use this tool Operating system patching.like monthly Patching and kernel patching.shall we create a repository in this tool. Like Reshat satelite server.

Thanks and regards
Raju

**Comment by Mfinadmin** [comment]
@rajsathivada - currently this facility is not available. But you can run many batch files through meshcentral plugins. 

If you are looking for mashcentral with os patch update and other functionality please refer here[https://github.com/wh1te909/tacticalrmm/]()

**Comment by rajsathivada** [comment]
Is this free tool to control the devices?

**Comment by Mfinadmin** [comment]
@rajsathivada - Yes.
