### ISSUE TITLE
AMT Devices no longer working

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#2628]
Hi Guys, 

Previously on server version Server version 0.8.5 I had a Device Group (Intel AMT Only). Devices were manually added, and had been working fine. This has actually been working fine for all version prior as well 

Upgraded to 0.8.34 and I lost ability to connect any of my AMT devices. I reverted back to a snapshot as need this functionality to reimage devices. 

To try to further understand the issue, I setup a new test server with a new install, no fancy config.
Mesh server is Intel AMT machines are on the same local lan. 
I'm using basic auth, username and password for these devices.

Server version 0.8.5 and previous versions 
Scan Network and Add Local (Links are shown)
<img width="253" alt="0 8 5 Options" src="https://user-images.githubusercontent.com/51713320/117999741-10bb0100-b33d-11eb-88d4-806b12536ede.PNG">

Device is added successfully 
<img width="304" alt="0 8 5" src="https://user-images.githubusercontent.com/51713320/118000185-7e672d00-b33d-11eb-9375-d58677a17203.PNG">

Server version 0.8.34 (New Test Server)

Notice Scan Network and Add Local hyperlinks are missing
<img width="249" alt="0 8 34 Missing Options" src="https://user-images.githubusercontent.com/51713320/118000430-b53d4300-b33d-11eb-9be3-66574b53628c.PNG">

When I try to add add a device, the device is not added. Nothing seems happen.

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Hi. I just published MeshCentral v0.8.36 with some Intel AMT only device group fixes in the user interface. However, I think you problem is that your new test server is in "WAN mode". That is, your new server is configured to communicate only to devices over the Internet, no local networks.

In WAN mode, the "Add Local" and "Scan Network" links will not be shown. If you set a Intel AMT policy with CIRA, you will see a "Setup" link for that group.

If you want to have the links show, remove the `"WANonly": true` line in the config.json.

Hope that helps,
Ylian

**Comment by vish84** [comment]
Hi Ylianst

Ahh yes, you are correct about the WAN, apologies oversight on my part on my test server. 

I can confirm, version 0.8.36, now allows connecting to AMT devices correctly after upgrading. I have also tested adding a new AMT device, which is successful. 

Many thanks, for being super quick.
