### ISSUE TITLE
web-rdp or noVNC on a Raspberry

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#2629]
How do you use web-rdp or noVNC on a Raspberry?

**Comment by Ylianst** [comment]
I guess you would need to turn on VNC support on the Rapsberry Pi.

**Comment by mrkacg1** [comment]
Yes it is, but I try to use noVNC and it tells me: Failed to connect to server

Something to configure in meshcentral?

**Comment by Ylianst** [comment]
You specified no information in your issue, so it is not possible to help.
