### ISSUE TITLE
Can we use Meshcentrol as reposerver to update OS patches on clients

### ISSUE THREAD

**Issue by sreenivaskundala** [Ylianst/MeshCentral#2630]
We are planning to provision around 5000 intel NUC servers in my environment which are running on ubuntu 20.04 version .

now we need a solution to update OS level available patches on all intel NUC servers within certain time frame. 

Can we consider Meshcentrol is a solution for my OS patches requirement.

Thank you in advance.

Thanks,
Sreenivas Kundala
+919885068981

**Comment by Ylianst** [comment]
Hi. MeshCentral does no do OS patch management right now for any OS. If you want to make a required for that feature to be added, you can do so, but you have to be very specific as to exactly what you need. Hope that helps.

**Comment by jsastriawan** [comment]
Sreenivas,

You should look at setting up your apt-cacher-ng and let all 5000 NUC to proxy the apt via that proxy. Additionally you can set a crontab entry on each machine to perform update. If you want to script the command remotely, you should consider using meshctrl.js to invoke patching process.
