### ISSUE TITLE
MeshCentral Router crash on connect

### ISSUE THREAD

**Issue by yves-ledermann** [Ylianst/MeshCentral#2631]
Hi,

on connect to my server the meshcentralrouter crash after connect (without showing any Agents in the list) with the follwoing Error in debug.log:

> UnhandledExceptionEventSink: System.InvalidCastException: Das Objekt des Typs "System.Collections.Generic.Dictionary`2[System.String,System.Object]" kann nicht in Typ "System.Collections.ArrayList" umgewandelt werden.
>   bei MeshCentralRouter.MeshCentralServer.processServerData(String data)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.ProcessWsBuffer(Byte[] data, Int32 offset, Int32 len, Int32 op)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.ProcessBuffer(Byte[] buffer, Int32 offset, Int32 len)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.OnTlsDataSink(IAsyncResult ar)
>    bei System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
>    bei System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    bei System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
>    bei System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
>    bei System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
>    bei System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
>    bei System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    bei System.Net.ContextAwareResult.Complete(IntPtr userToken)
>    bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
>    bei System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
>    bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
> 

I just rechecked, the meshcentral router is working with the public server.
But i dont know what to check on my own installation...

Router Version: 1.7.7788
Server Version: 0.8.33

**Comment by VINISHVV** [comment]
Can you try with latest Meshcentralrouter once. To download click [here](https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe).

**Comment by yves-ledermann** [comment]
Thanks for the fast response.
But unfortunatly the new Version isn't any help.
I still get the same Error Message.
(There was an Popup Asking to update the Version wich i canceld. )

I even tried it with another user with only access to one agent group... but the error remains the same

> UnhandledExceptionEventSink: System.InvalidCastException: Das Objekt des Typs "System.Collections.Generic.Dictionary`2[System.String,System.Object]" kann nicht in Typ "System.Collections.ArrayList" umgewandelt werden.
>    bei MeshCentralRouter.MeshCentralServer.processServerData(String data)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.ProcessWsBuffer(Byte[] data, Int32 offset, Int32 len, Int32 op)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.ProcessBuffer(Byte[] buffer, Int32 offset, Int32 len)
>    bei MeshCentralRouter.MeshCentralServer.xwebclient.OnTlsDataSink(IAsyncResult ar)
>    bei System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
>    bei System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
>    bei System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
>    bei System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
>    bei System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
>    bei System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
>    bei System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    bei System.Net.ContextAwareResult.Complete(IntPtr userToken)
>    bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
>    bei System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
>    bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by Ylianst** [comment]
Hi. Can you run MeshCentral Router like this:

```
MeshCentralRouter.exe -debug
```

Them, cause the crash to happen and send the resulting debug.log file back. If you are concerned about privacy, feel free to send me the "debug.log" privately using [my contact information](https://www.meshcommander.com/contact-information) and/or put XXXXXXX on any private information.

I will fix this right away. Thanks.

**Comment by Ylianst** [comment]
Thanks for sending me the log file. I have a new version of MeshCentral Router with the fix. [You can download it here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe), it will also be in MeshCentral v0.8.39 when it's next published. If you can try it and let me know if it works. Thanks.
