### ISSUE TITLE
Android agent doesn't show on web meshcentral after connection

### ISSUE THREAD

**Issue by miroslavjaros** [Ylianst/MeshCentral#2632]
![server](https://user-images.githubusercontent.com/82977063/118115754-a7dd9280-b3e9-11eb-8042-0c50769d44f8.jpg)
Hello Ylian, today I want check file with my mobile Android Xiaomi redmi note 5 by mesh agent. Few days ago working without problems. After connection agent on mobile wrote is connected. I tried update server on newest version 0.8.36 but it not help.
When I check in my server I see from 10 active devices is 11. So connection is ok.
But I did not see device android in my group.
I tried add another PC,  is working ok problem is only with only this one mobil Android. With next one is working fine. 
I checked to database Mongo and there are 2 session from 2 different IP from Home and Office in collection meshcentral.
I found in meshcentral collection meshcentral, power, events and serverstats 
So is there any chance that some script, place in meshcetral is buggy ? Or some frozen session ?

What can by a problem ? How can I try debug this situation. Everything seems ok but not show in group device.

Thanks for response.
Miroslav

**Comment by si458** [comment]
closing as stale,
please try the latestgoogle play store release
