### ISSUE TITLE
Cannot install MeshCentral Agent on Android 11

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#2633]
Tried both - download from PlayStore and download an APK from meshcentral.com, in both cases installation is starting but finishing with a message "App is not installed"

Have tried to "Clear cache" and "Clear data" for Play Store as mentioned on google help - no luck, the result is same.

I have before installed MeshCentral Agent on the phone, but it is updated somehow to Android 11 and agent has been removed and cannot be installed anymore.

![EBliYBifVh](https://user-images.githubusercontent.com/59362521/118104872-9b4e3f80-b3d3-11eb-869e-a18380d5e4c4.png)

![kRyny07w8w](https://user-images.githubusercontent.com/59362521/118104905-a30de400-b3d3-11eb-8be8-1f5740b89c10.png)

![jer3jD7zkM](https://user-images.githubusercontent.com/59362521/118104899-a0ab8a00-b3d3-11eb-92c6-15c5c767a720.png)

**Comment by mwllgr** [comment]
Are you sure that the agent has **really** been removed? As far as I know, this error sometimes pops up when you have an old version of the app (with a different key) installed. Check the app list in your system settings.

**Comment by vitko-bg** [comment]
@mwllgr I am 100 % sure - it is not on the list with apps. I had it installed before upgrade, now it is gone by itself. 
Tried to find it in the list, in installed apps - missing everywhere exclude downloaded APK.

**Comment by krayon007** [comment]
Which phone are you using? I have it running on Android 11 with the latest May security patches on my Pixel 5.

**Comment by vitko-bg** [comment]
I am on OnePlus 7T Pro

**Comment by vitko-bg** [comment]
Have tried to delete data/Android/com.android.meshcentralagent - still the same error on installation

Please advise where MeshAgent is installing to on Android devices? So I can locate the leftover files and try to delete them.

Thanks.

**Comment by vitko-bg** [comment]
@krayon007 could you advise please on how to resolve the issue without resetting the phone?
Thanks.

**Comment by vitko-bg** [comment]
In case if that will help to someone - I managed to resolve the issue.
Steps were to get into Developer mode on Android and enable a debugging.
Once debugging is enabled I tried to install meshcentral agent to get the error in the logs.

Listing errors at the end of the post, in case someone is interested how they look like. The error in the log itself "Package com.meshcentral.agent2 signatures do not match previously installed version; ignoring!" helped me to find a way and to resolve the issue.

So I downloaded a ADBAppControl and run on the phone "adb uninstall "com.meshcentral.agent2". On the phone app was not on the list, no leftover files, nothing - so it was not possible to uninstall it from the Android GUI. So all is working now!

Hope that will help other people.

Closing the issue now.

Errors I found are:
`
12-01 11:46:07.439  1000  1595  1823 W PackageSettings: Skipping PackageSetting{60bd7a8 com.meshcentral.agent2/10388} due to missing metadata
12-01 11:49:17.563  1000  1595  4445 D OpRestartProcessManager: updateSelf :  com.meshcentral.agent2, size : 30
12-01 11:50:52.161  1000  1595  1700 I ActivityManager: Force stopping com.meshcentral.agent2 appid=10388 user=-1: installPackageLI
12-01 11:50:52.167  1000  1595  1823 W PackageManager: Scanning Failed.
12-01 11:50:52.167  1000  1595  1823 W PackageManager: com.android.server.pm.PackageManagerException: No signature found in package of version 2 or newer for package com.meshcentral.agent2
12-01 11:50:52.161  1000  1595  1700 I ActivityManager: Force stopping com.meshcentral.agent2 appid=10388 user=-1: installPackageLI
12-01 11:50:52.167  1000  1595  1823 W PackageManager: Scanning Failed.
12-01 11:50:52.167  1000  1595  1823 W PackageManager: com.android.server.pm.PackageManagerException: No signature found in package of version 2 or newer for package com.meshcentral.agent2

12-01 12:04:24.100 10198 18501 18501 I Finsky  : [2] iuq.z(7): Selecting account [5KOgXIpJrvjW-bynJeUVpP7Z9IF2yCHSex-1aR9Z1n0] for package com.meshcentral.agent2. overriding=[true]

12-01 12:04:25.150 10198 18501 18501 I Finsky  : [2] tgf.a(5): Will queue com.meshcentral.agent2 to be downloaded over any network
12-01 12:04:25.152 10198 18501 18501 W Finsky  : [2] eon.a(4): No everExternallyHosted provided for com.meshcentral.agent2
12-01 12:04:25.153 10198 18501 18501 I Finsky  : [2] jpd.accept(12): IQ: Attempting to validate incoming request. package=com.meshcentral.agent2
12-01 12:04:25.154 10198 18501 18530 I Finsky  : [2478] jsw.apply(26): IQ::IHP: com.meshcentral.agent2 is not applicable for install holdoff, modifying constraint.

12-01 12:04:28.994 10287  4981  4981 W NLService: onNotificationRemoved
12-01 12:04:28.994 10287  4981  4981 I NLService: ID :-56862258	MeshCentral Agent	com.android.vending

  Historical Broadcast foreground #12:
    BroadcastRecord{a8e8d1b u0 android.intent.action.PACKAGE_NEEDS_VERIFICATION} to user 0
    Intent { act=android.intent.action.PACKAGE_NEEDS_VERIFICATION dat=file:///data/app/vmdl349934087.tmp typ=application/vnd.android.package-archive flg=0x10000011 (has extras) }
      targetComp: {com.android.vending/com.google.android.finsky.verifier.impl.PackageVerificationReceiver}
      extras: Bundle[{android.content.pm.extra.VERIFICATION_INSTALLER_UID=10198, android.content.pm.extra.VERIFICATION_ID=24, android.content.pm.extra.VERIFICATION_PACKAGE_NAME=com.meshcentral.agent2, android.content.pm.extra.VERIFICATION_INSTALL_FLAGS=4210706, android.content.pm.extra.VERIFICATION_LONG_VERSION_CODE=18, android.content.pm.extra.VERIFICATION_VERSION_CODE=18, android.content.pm.extra.VERIFICATION_INSTALLER_PACKAGE=com.android.vending}]


  Historical Broadcast foreground #13:
    BroadcastRecord{28bec15 u0 android.intent.action.PACKAGE_NEEDS_INTEGRITY_VERIFICATION} to user 0
    Intent { act=android.intent.action.PACKAGE_NEEDS_INTEGRITY_VERIFICATION dat=file:///data/app/vmdl349934087.tmp typ=application/vnd.android.package-archive flg=0x50000011 pkg=android (has extras) }
      extras: Bundle[{android.content.pm.extra.VERIFICATION_INSTALLER_UID=10198, android.content.pm.extra.VERIFICATION_ID=24, android.intent.extra.PACKAGE_NAME=com.meshcentral.agent2, android.intent.extra.VERSION_CODE=18, android.content.pm.extra.VERIFICATION_INSTALLER_PACKAGE=com.android.vending, android.intent.extra.LONG_VERSION_CODE=18}]

  #37: act=com.android.vending.INTENT_PACKAGE_INSTALL_COMMIT.349934087 flg=0x10 (has extras)
    0 dispatch 0 finish
    enq=2021-12-01 12:04:27.097 disp=2021-12-01 12:04:27.097 fin=2021-12-01 12:04:27.097
    extras: Bundle[{android.content.pm.extra.STATUS=5, android.content.pm.extra.PACKAGE_NAME=com.meshcentral.agent2, android.content.pm.extra.SESSION_ID=349934087, android.content.pm.extra.LEGACY_STATUS=-7, android.content.pm.extra.STATUS_MESSAGE=INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.meshcentral.agent2 signatures do not match previously installed version; ignoring!}]
`
