### ISSUE TITLE
Manage client credentials

### ISSUE THREAD

**Issue by alex-p75** [Ylianst/MeshCentral#2634]
Hi,
there is a way to manage controlled pc login credentials?

Thank you

**Comment by VINISHVV** [comment]
Hi @alex-p75 - Can you share the requirement in detail ?

**Comment by alex-p75** [comment]
Hi,
I'm also using screenconnect and there is the option to save the user login credential  and send them to controlled pc .
I'd like to know if there is something like that on your great software :)

**Comment by Mfinadmin** [comment]
@alex-p75 
Are you looking for node /remote system credential management ?

**Comment by Ylianst** [comment]
This issue no not sufficient specific. When adding an issue, please exactly exactly what you looking for. I am going to close this one. @alex-p75, please open a new issue and offer a lot more details as to exactly what your asking for. Thanks.

**Comment by alex-p75** [comment]
@Mfinadmin yes thank you
