### ISSUE TITLE
[Minor - Typo] MeshCentral Router for Mac

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2636]
This is super minor but I wanted to mention it before I forgot. When downloading MeshCentral Router for Mac, the link shows MeshCentralRouter.d**w**g which should be MeshCentralRouter.d**m**g. The correct file is downloaded and opens regardless though.

**Comment by Ylianst** [comment]
Nice catch!

**Comment by Ylianst** [comment]
Fixed. Will be in the next version.
