### ISSUE TITLE
Invalid web page with white area after updating to v0.8.37

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#2638]
Updated to 0.8.37 this morning and when I logged in after the update I was greeted with the attached screenshot. My devices show online and such in the My Server tab but I can't see anything in any of the tables.

Running Node 14.5.1 and MongoDB. No error logs showing and this is on a vm running Windows Server 2019 DC Edition. Let me know if there's any more information I can provide.
![2021-05-14 08_46_31-MeshCentral and 10 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/417006/118288138-57ba0b00-b491-11eb-9fc9-a15204f0ee48.png)

**Comment by asasin114** [comment]
Upon downgrading to v0.8.36 I found this in the error log. Hope it's helpful.

-------- 2021-05-14, 8:56:20 a.m. ---- 0.8.37 --------

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on FSWatcher instance at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  filename: null
}

**Comment by Mfinadmin** [comment]
I also notices same issue. But clear browser history cache resolved my problem

**Comment by asasin114** [comment]
@Mfinadmin, that does seem to work for me as well. @Ylianst, not sure if the error log helps you at all or not so I'll leave this open unless there's nothing you need.

**Comment by Ylianst** [comment]
It looks like I did some changes to the some of the static files and the new web page needs the updated style sheets. The browser cache has the old version, that should auto clear after an hour or you can click shift-refresh of the browser to force all elements to be refreshed.

The real fix for this would be for me to change the filename of any static file when a change it made, but that is a lot of work. I may try to automate it in the future.

**Comment by PetieM** [comment]
I'm not sure if this is just a matter of cached files. I'm seeing the same thing on my side but only if I have MeshCentral Router links enabled in list mode. Disabling those and refreshing restores normal functionality.

Also, just FYI, query strings affect the cache status of things like .css and .js files. So, something like styles.css?version=1 and then changing version to 2 on the next update is sufficient, no need to constantly rename files. I use this on my own sites by including a version variable (e.g. styles.css?version=<?php echo $ver; ?>) and then set that $ver variable, to a date and version number like 2021-05-14_1, in a central file. The downside to this approach is that it marks every file that has that system in place as updated whenever I change the version, even if I'm only updating one file, but it happens infrequently enough that I find the minor inconvenience of re-caching CSS and JavaScript files occasionally to be an acceptable tradeoff for not having to maintain version numbers on a pre-file basis.

**Comment by Ylianst** [comment]
Do you see any errors show up in the browser console when white areas are showing? If so, please send over!

**Comment by VINISHVV** [comment]
Dear Ylian,

Getting below errors in browser console.

**Comment by PetieM** [comment]
Finally back in front of a computer to actually grab the error I'm seeing. Here it is:
```
[Error] ReferenceError: Can't find variable: getShortRouterLinks
	updateDeviceViewHtml (xxx.com:4223:150)
	onDevicesScrollEx (xxx.com:4094)
	updateDevices (xxx.com:4070)
	(anonymous function) (xxx.com:2061)
```

**Comment by VINISHVV** [comment]
In mycase this issue is noticed when i add the Meshrouter links & Operating system for List view menu.

**Comment by Ylianst** [comment]
Ha! Ok, I can fix the missing "getShortRouterLinks" problem.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.38 with a fix for this. Let me know if it works.

**Comment by PetieM** [comment]
Looks good to me now. Thanks!

**Comment by VINISHVV** [comment]
Issue resolved.
