### ISSUE TITLE
Allow changing the config.json from the web site

### ISSUE THREAD

**Issue by Ridd01** [Ylianst/MeshCentral#2639]
I think it would be great to have ability to set server settings via WWW GUI (like enable SSH, change graphics and like that stuff).

**Comment by Mfinadmin** [comment]
@Ridd01 - your request contains minimal info. Can you explain the same in detail? .

**Comment by Ridd01** [comment]
Page where you can change server settings by ticking it on or off. Maybe in this place 
![5tvloAb](https://user-images.githubusercontent.com/77367772/118292315-ca9aa480-b4d8-11eb-853b-cfe3f6f51f3c.png)
Enable disable SSH via WWW
Change image on login page
this kind of stuff that are add in future and has been added in past
Stuff that are edited via config file
This kind of stuff:
![E1F0F9cUcAsWD5q](https://user-images.githubusercontent.com/77367772/118292742-3c72ee00-b4d9-11eb-8878-238d4a6c7fc6.png)

**Comment by Ylianst** [comment]
I do agree that it would be great to edit the server configuration from the web site. It would make things a lot easier, especially if you are not familiar with JSON. One issue is that there are so many settings, it's sort of crazy.

**Comment by PathfinderNetworks** [comment]
Is there documentation that is kept current for all of the settings and their options in the config file?  There are so many, and so many that are always being added, that I'm finding it truly impossible to keep up with them.  I'm certain there are a great number of settings and features I don't know even exist- let alone have implemented.

**Comment by AntonAndreevichMoroz** [comment]
I am using this file.  There are parameters that are not described, but this is the most complete version that I have found.
https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json

**Comment by VINISHVV** [comment]
@PathfinderNetworks - Please refer the advanced config schema [here](https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json)

**Comment by nzalev** [comment]
One thing to keep in mind with this is that the config.json file may contain _many_ passwords, including database, zipped backups, webDAV, etc.

This has to be done in a way as to not leak sensitive information.

**Comment by Ridd01** [comment]
I dont know JSON but, maybe there is something like in php - "include file.cfg". Than passwords can be added in separate file.

**Comment by jjoelc** [comment]
I agree with others this would be a great feature. However I think no matter what you would still need to keep some portions (or large chunks) in the config file only, and not available to the website. I'm NOT a programmer, but I'm betting this would require some pretty serious re-structuring of the config file. I'd guess by splitting it into several smaller files. Maybe something like a "core-config.json" file with server and database settings, things like that which would be dangerous or impractical to have on the web.. Then "user-config.json" for all of the user customizations types of options, which WOULD be editable in the web interface. (Then domain-core-config... and domain-user-config... for each domain???)

In any case, yes, I agree it would be great,  but I believe it will take a lot more work than just picking an open source json editor and pointing it at the config file!

(And speaking of documentation - yes, the config-schema is probably going to be your best authoritative source right now (well... it is what DEFINES those settings, so...) but, I recently started a wiki at https://meshcentral-community.com which I would love to see grow into a community driven source of MeshCentral documentation. Feel free to drop by, add in any little snippets you have picked up along the way!

**Comment by si458** [comment]
we have added the ability to see your config in the web ui in 1.1.13, but i dont think we will add the ability to change ur config at the moment sorry
