### ISSUE TITLE
Cant get smtp.gmail.com server to send emails

### ISSUE THREAD

**Issue by shay-shilo** [Ylianst/MeshCentral#264]
Hi,
I have MeshCentral installed on a Raspberry pi inside my home network.
I've configure gmail SMTP and Meshcentral allows me to send emails but they don't get actually sent.
Setup information can be found below.

Other things I've tried:
- Working with and without TLS
- Using port 465 with and without TLS
- Using Gmail SMTP from Win10 email program - emails get sent.

Setup info:
------------
The PI is behind NAT, I intend to port-forward the device later on.
This is from my config.json:
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 587,
    "from": "mygmail@gmail.com",
    "user": "mygmail@gmail.com",
    "pass": "googleapppassword",
    "tls": false
  }

And this is the log:
-----------------------
systemd[1]: Started MeshCentral Server.
 node[2820]: MeshCentral HTTP redirection server running on port 80.
 node[2820]: MeshCentral v0.3.5-p, LAN mode, Production mode.
 node[2820]: MeshCentral HTTPS server running on port 443.
 node[2820]: SMTP mail server smtp.gmail.com working as expected.

Thanks,
Shay

**Comment by krayon007** [comment]
I'll ask Ylian what module he's using, but I ran into this issue with my IP cameras, because GMail deprecated some of their older authentication methods, so I created a special account just for this purpose where  the Gmail settings to "allow less secure apps" was enabled.

Not sure if that's what's going on in your specific case.

**Comment by Ylianst** [comment]
Bryan is likely correct, I will check the documentation but you need to enable the "Less secure app access" option. It's in the Google Account / Security. That is what I have foir my servers, I use a dedicated separate account for this usage.

![Gmail-LessSecurity](https://user-images.githubusercontent.com/1319013/58752531-19261400-8465-11e9-801d-537b5d256520.png)

**Comment by Ylianst** [comment]
Just silently updated the [MeshCentral user's guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf). End of section 13 has the update for this.

**Comment by shay-shilo** [comment]
Thanks Krayon and Ylianst. I'l use my other Gmail as recommended since I can disable two-factor authentication there.
Which brings me to another point which is that if you have two-factor authentication enabled in Gmail, you won't see an option for 'less secure...' at all. I was confused by it initially.
Might be a good idea to note it in the manual as well.

**Comment by Ylianst** [comment]
Thanks for the info on two-factor, I will update the documents. I do recommend having a different account for this use as you are placing the account password in the config.json of your server. I don't think it's a good idea to use a personal mailbox for this use.

**Comment by Ylianst** [comment]
Just did one more silent update of the [MeshCentral user's guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf) to note that 2-factor auth will remove the 'less secure...' option and recommend that a dedicated account be used. If it's ok, we can close this issue.

**Comment by PathfinderNetworks** [comment]
For Gmail, even if you use 2FA on the account, there is an option you can setup to create a per device password for those devices/services that can't interact with the Google 2FA.   Here is the Google help page discussing it and how to set it up.  https://support.google.com/accounts/answer/185833?hl=en

**Comment by shay-shilo** [comment]
> For Gmail, even if you use 2FA on the account, there is an option you can setup to create a per device password for those devices/services that can't interact with the Google 2FA. Here is the Google help page discussing it and how to set it up. https://support.google.com/accounts/answer/185833?hl=en

Thanks Parrish, before I opened this questions here I tried what you mentioned. No go :-(

> Just did one more silent update of the [MeshCentral user's guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf) to note that 2-factor auth will remove the 'less secure...' option and recommend that a dedicated account be used. If it's ok, we can close this issue.

Ylian, I set up my other Gmail account to disable 2FA and enabled the 'less secure ...'. Also no go.
Tried with 465 & 587 with and without tls set to true. 
Is there maybe a way to open additional logs so I can see if the email sending fails?

**Comment by Ylianst** [comment]
That is weird, I have not gotten any such problems so far. My servers are mailing away. I will look at adding more logging and a "testemail" command in the "My Server" console to help with this.

**Comment by shay-shilo** [comment]
I finally figured it out :-)
Turns out my server was configured for LAN ('_cert'). Once I unset the '_' and set the value to my public IP address I started getting the emails as expected.

**Comment by Ylianst** [comment]
I see, in "LAN mode" you can't send a agent invite email because the server does not have a fixed IP/DNS name. I need to check because this web application should be offer the option to send a invitation email in this case.

**Comment by Ylianst** [comment]
Ok. I just fixed the server so it does not propose password reset or email verification in LAN mode. I also display a warning when setting up an SMTP server while in LAN mode, so, should avoid this situation in the future.

![MC-EmailLanMode](https://user-images.githubusercontent.com/1319013/59135052-5e00ed80-8932-11e9-8edf-95b658879469.png)

**Comment by motapek** [comment]
Jun 28 17:20:22 XXXXXX node[1955]: SMTP mail server smtp.gmail.com working as expected.

For me working very well

**Comment by Ylianst** [comment]
Closing this once as I think it's fixed. Please open a new issue if there are problems in this area.

**Comment by Quigley-Brendan** [comment]
Everything here helped me. However there was one step that I did see. You need to enable IMAP in the gmail settings. 

Settings  > Forwarding and POP/IMAP > IMAP Access > Enable

![image](https://user-images.githubusercontent.com/6979628/153642803-b4a0ba51-6a91-48ec-8e4e-fedf10436a96.png)
