### ISSUE TITLE
LE no longer working

### ISSUE THREAD

**Issue by inmanturbo** [Ylianst/MeshCentral#2644]
This used to work, I have MC behind a firewall with the following configuration:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for deta>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mydomain.com",
    "port": 1025,
    "aliasPort": 1025,
    "redirPort": 1024,
    "redirAliasPort": 80
},
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "my@email.com",
    "names": "mydomain.com",
    "rsaKeySize": 3072,
    "production": false
  }
}

```

And I have an http reverse proxy listening on `mydomain.com:80` and sending traffic to MC server's local IP `192.168.1.234:1024`. `mydomian.com:1025` simply forwards to `192.168.1.234:1025` and skips the proxy.
This used to work perfectly. However for some reason lately I've been having problems with it, although it works (redirects and all) fine with a self-signed cert or event with expired cert, despite of course expired cert errors. 

 ```
meshcentral$ node node_modules/meshcentral --debug cert,web,webrequest
MeshCentral HTTP redirection server running on port 1024.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.7.65, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on mydomain.com:4433.
MeshCentral HTTPS server running on mydomain.com:1025, alias port 1025.
CERT: LE: Certificate has -2 day(s) left.
CERT: LE: Asking for new certificate because of expire time.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Failed to obtain certificate: Request failed with status code 404
```
Is there a way to simply use ssl termination, without the redirect or ssl? Between the external load balancer/Proxy and reverse proxy I can't seem to get ssl-> ssl-> ssl to work. It is far simpler to just terminate at an edge point.

**Comment by Ylianst** [comment]
Try [https://letsdebug.net/](https://letsdebug.net/) to make sure everything is ok.

**Comment by inmanturbo** [comment]
@Ylianst letsdebug shows everyting is fine, also I have no problem running the acme challenge on the reverse proxy, What I'm trying to avoid is having to manually install the cert from the proxy to the MC server every three months. It seems the NoTls option is ignored and MC still generates a self signed cert and runs https no matter what you do? Is it possible to use DNS based challenge rather than http?

I prefer to only allow access through a chain of proxies and VPN, each with their own security checks, so MC is nested a level deeper that we usually would perform https challenges at. And the gap only goes one way, so I would also rather not offload.

**Comment by Ylianst** [comment]
I don't see any "notls" options in your config.json. You can use:

```
"tlsoffload": "1.2.3.4"
```

There 1.2.3.4 is the internal IP address of your reverse proxy. Then using "certurl" in the domain section to have MeshCentral load the cert form the reverse proxy. [I made a video about all this here](https://www.youtube.com/watch?v=YSmiLyKSX2I&t=247s).

MeshCentral will always generate a self-signed TLS cert as a backup, but will not use it if "tlsoffload" is turned on. If you have a reverse proxy, best to have the reverse proxy get the Let's Encrypt cert and not have MeshCentral do that. Anyway, video should explain it all.

**Comment by inmanturbo** [comment]
@Ylianst That's correct. I dodn't have "notls in my config. It was just something I tried several times while trying to come up with a solution.

Thanks anyway though for the suggestion. I will try the tlsoffload option, but the User guide made it look like it requires some hacking on the reverse proxy configuration, which is not ideal.  Our reverse proxy is floating, opinionated, and stateless; and the configs are autogenerated, so adding snowflakes like custom proxy server blocks just make it that much more difficult to maintain.

**Comment by inmanturbo** [comment]
a Question, regarding this example from the user guide:
```
{
 "settings": {
 "Cert": "myservername.domain.com"
 "Port": 4430,
 "AliasPort": 443,
 "RedirPort": 800,
 "TlsOffload": "127.0.0.1"
 "MpsPort": 44330,
 "MpsAliasPort": 4433,
 "MpsTlsOffload": true
 },
 "domains": {
 "": {
 "certUrl": "https://127.0.0.1:443/"
 }
 }
}
```
If this server `https://127.0.0.1:443/` is handling connections for many many domains, how would it know which cert to hand off? Shouldn't it be like this: 
```diff
 "domains": {
 "": {
- "certUrl": "https://127.0.0.1:443/"
+"certUrl": "https://mydomain.com"
 }
 }
}

**Comment by Ylianst** [comment]
Excellent question. MeshCentral will query using the DNS name in this line:

```
"Cert": "myservername.domain.com"
```

So, it should get the right one.

**Comment by inmanturbo** [comment]
Evidently Not (Referring to above). I was able to get this working with the following configuration:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for deta>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "myserver.domain.com",
    "Port": 1025,
    "TlsOffload": "1.2.3.4",
    "AliasPort": 1025,
    "RedirPort": 1024,
    "RedirAliasPort": 80
  },
  "domains": {
     "": {
        "certUrl": "https://1.2.3.4:443"
     }
  }
}
```
And the following server block, which just sets a few headers and I am pleased to say is not so radical that it cannot be automated, we already have options in place for these parameters.

```nginx
  location / {
         proxy_set_header X-Forwarded-Host $host:$server_port;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $http_connection;
         proxy_http_version 1.1;
            # Proxy
            include conf.d/include/proxy.conf;
}
```
Thank you very much for your help. I am grateful. I will be closing this issue.

**Comment by Ylianst** [comment]
Excellent. Yes, this is the exactly correct way to do it!
