### ISSUE TITLE
send local clipboard as a keystroke 

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2645]
hi, it would be so useful if we can send the local clipboard as a keystroke instead of paste because at login screen paste is not an option and when we have a long and complex password then this feature will come very handy.

**Comment by smartekIT** [comment]
I think you already got that but you call it by pressing the Type button on bottom left on desktop mode. i just realized that now. thanks for that but i think it would be more clear for everyone if you call that button (send as keystroke).

**Comment by VINISHVV** [comment]
I think your requirement is same as #2637
