### ISSUE TITLE
Warning: Unrecognized configuration option "maxinvalidlogin".

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#2646]
good morning, what am i doing wrong here? 

have entered these lines in the config file...
--------
	"maxInvalidLogin": {
		"time": 10,
		"count": 10,
		"coolofftime": 10
	},
--------
that i get this error message?

--> Warning: Unrecognized configuration option "maxinvalidlogin".

thank you very much for your help - and a huge compliment for the really great software!

**Comment by AntonAndreevichMoroz** [comment]
if this is the most recent setting in the config file, then the comma after the closing parenthesis is superfluous.  Or vice versa, the previous setting did not have a comma added.  in a ripped-out context, it's hard to say what's wrong.  Check the config file for compliance with the json format.

**Comment by Ylianst** [comment]
This error is likely because you put the "maxInvalidLogin" in the root of the config.json document. It should go in the "settings" section. Fix that and it should work.

**Comment by wvt-adm** [comment]
yes - you right! thanks a lot for explain!
