### ISSUE TITLE
view problem - column work - list dont work

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#2647]
view problem

since one or two updates i can only use the column view, with the list view it doesn't show me any agents anymore, i attach a screenshot to show what i mean ;-) 

greetings and thanks for your help!
![1](https://user-images.githubusercontent.com/56296924/118384001-2c572d80-b603-11eb-8955-14d1a916e737.JPG)
![2](https://user-images.githubusercontent.com/56296924/118384002-2cefc400-b603-11eb-9668-6b08abbf4213.JPG)

**Comment by Ylianst** [comment]
What version are you running? I just fixed this in MeshCentral v0.8.38. Update and let me know if it works.

**Comment by wvt-adm** [comment]
thanks a lot - works after update!
