### ISSUE TITLE
syslog how to connect to mc

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#2648]
good morning ylianst, is there a way that i can connect meshcentral to a syslog server?

![image](https://user-images.githubusercontent.com/56296924/118385051-ece10f00-b60b-11eb-996e-6cc45e0b0ccb.png)

**Comment by nzalev** [comment]
Meshcentral uses the package `modern-syslog`. 

The config option is one choice out of the three:
```javascript
  "syslog": { "type": "string" },
  "syslogauth": { "type": "string" },
  "syslogjson": { "type": "string" },
```

However, from what I can see, it does not look to be supported on Windows:
```javascript
if ((require('os').platform() != 'win32') && 
  ( (config.settings.syslog != null) || (config.settings.syslogjson != null) || (config.settings.syslogauth != null) ) ) {
```

I am not really that familiar with Windows in general, so I am not sure if there is a technical limitation for this, or if support just hasn't been made yet.

**Comment by Ylianst** [comment]
Exactly correct. I am also not familiar with the "Visual Syslog" tool above. Looks like one could send events directly to that server over TCP. Certainly not something that is supported now... but if I request was made to do so, I could look into it.

**Comment by wvt-adm** [comment]
of course that would be sensational if that would also work under windows ;-) so i ask, can you look at that? thank you for the really sensational tool!

**Comment by Ylianst** [comment]
You can open an new issue with a request to have this feature added.
