### ISSUE TITLE
Duplicate entries from the same system

### ISSUE THREAD

**Issue by Kodangi** [Ylianst/MeshCentral#265]
Not sure, how to reproduce, but with one system, seeing duplicate entries of same system.

![image](https://user-images.githubusercontent.com/50257217/58756351-df2c3080-84ab-11e9-83fc-ae25994aa3df.png)

**Comment by Ylianst** [comment]
Hi. Can you let us know that operating system this system is running? There are a few things that could be going on:

- The meshagent.db file contains the identity of the agent. If that file gets deleted each time the computer boots for example, the agent will generate a new identity and reconnect leading to what you see above. Check that the meshagent.db file is not removed or corrupted. 
- There is a system in the MeshAgent I call "anti-cloning" where we check the MAC addresses of the interfaces on the system. If they are all different from the last one's we saw, the agent will reset it's identity. So, if you happen to have a system that boots up with completely different MAC addresses each time, the agent will do this. This may happen on test systems. If this is your case, we could add an option to the agent to turn off anti-cloning.

Hope it helps,
Ylian

**Comment by Ylianst** [comment]
I will close this one since there no further reports. However, if something was figured out it would be nice to get a report.

**Comment by Kodangi** [comment]
Sorry Ylian, I am back to work. Answers to your initial questions: this is a window 10 system, the steps taken by technician are: install windows OS, ran this accidentally two times and then system was rebooted 2 times.
No other steps were done by technician.
I will work with him to find and try to reproduce with another system
