### ISSUE TITLE
feature request -> syslog for windows

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#2650]
big wish - can you add syslog for windows to mc? 

thanks for your real great work!

**Comment by Ylianst** [comment]
Ok, check in and will be in MeshCentral v0.8.41. Once published, test and and close this issue if it works.

![MC2-SysLogTcp](https://user-images.githubusercontent.com/1319013/118770564-57759300-b836-11eb-837f-ee240add9835.png)

**Comment by Ylianst** [comment]
@wvt-adm I noticed you opened #2665 but this not close this issue. Why concern with closing this? Thanks.
