### ISSUE TITLE
Feature request -> EGLFS Remote Access for linux

### ISSUE THREAD

**Issue by mehranmd** [Ylianst/MeshCentral#2652]
Hi and thanks to all the maintainers of this project.
I know there is x11 support on Linux version of mesh project but if you take a look at projects done for 
devices like RPI3 you can see most of those apps use hw acceleration throw EGLFS surfaces.
  Just wanted to share the idea, because had a similar problem with my Qt-based application which uses EGLFS not xcb and couldn't add remote control feature to my project using mesh.

**Comment by jsastriawan** [comment]
The is a way to grab framebuffer from kernel using drm API however not all drm-based driver implement the buffer copy mechanism. The other complication is that to access the drm framebuffers/planes, the application which in this case is MeshAgent must be a drm master. So, I am not sure if your feature request can be addressed anytime soon. I tried few years ago but I don't know if it will scale.

**Comment by mehranmd** [comment]
I See, thanks for your quick response.
Just managed to solve my problem by making a version of Qt which supports EGLFS on X11.
I can confirm that this configuration will work with mesh pretty fine and it also includes HW acceleration.

![Capture](https://user-images.githubusercontent.com/35730154/118780585-752c1200-b8a1-11eb-96f8-2ea3b1bb27ad.PNG)

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and using node 18 or above.
if issue still persists, please reply back
