### ISSUE TITLE
add MeshCentral Router Link for Remote Desktop

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#2654]
Can we add here also a hyperlink to MeshCentral's Remote Desktop (via the MeshCentral Router) ?

![image](https://user-images.githubusercontent.com/68591647/118627846-590a7100-b7cc-11eb-9f7e-c098a5f78e65.png)

Now we can add HTTP, HTTPS, RDP, SSH and SCP. I would like to add a link to open the MeshCentral router, and open immediatly the "MeshCentral Remote Desktop". (not Windows RDP)

**Comment by Ylianst** [comment]
Ok, just added this. It will be in MeshCentral v0.8.44 and you will need to update your MeshCentralRouter.exe to the latest version. You then add two more links with protocols "mcrdesktop" or "mcrfiles".

```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "MCRDesk",
            "protocol": "mcrdesktop"
          },
          {
            "name": "MCRFiles",
            "protocol": "mcrfiles"
          }
        ]
      }
```

This will create links that go directly into MeshCentral Router and connect remote desktop or files. Once published, let me know if it works.

**Comment by AntonAndreevichMoroz** [comment]
I tried this. This is a very interesting and convenient function. Will the terminal be added there?
For MCRFiles, is it possible to copy folders, not just files?

**Comment by jdvmanen** [comment]
Ylianst, this is working as a charm! Many many thanks for your effort!!

**Comment by Ylianst** [comment]
@AntonAndreevichMoroz Not current capable of copying folders, but something that I could look into if requested.
