### ISSUE TITLE
Clipboard setting not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by turin331** [Ylianst/MeshCentral#2656]
As in the title. When connected to the desktop, setting the clipboard gives a message of success but does not actually affect the remote's machine clipboard. 

OS: Ubuntu 18.04.5 LTS with Mate desktop. 
Meshcetral version: 0.8.39 
Device: Intel NUC6i7KYB

Saw the same issue with older 0.7.x versions.

**Comment by krayon007** [comment]
Linux is a special case... Unlike windows, Linux has multiple clipboard buffers, that are not accessible by all applications... The easiest way to get the best clipboard experience on Linux, is to install `xclip`. The Mesh Agent will auto detect if you have xclip installed, and will use that when available. If you do not have that installed, then it will default to using the x11 clipboard, which is not accessible by all applications, such as the the terminal. In some cases you can access this buffer with a middle click. But I suggest to install xclip if you can, as the experience will be better.

**Comment by turin331** [comment]
Indeed xclip seems to work well. Thank you for the clarification.
