### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentral#2657]
I noticed today that one of my clients was connecting/disconnected a lot today, looked in the syslogs and could see lots of the below:

May 18 15:59:28 WP-SBC systemd[1]: Started meshagent background service.
May 18 15:59:29 WP-SBC systemd[1]: meshagent.service: Main process exited, code=killed, status=7/BUS
May 18 15:59:29 WP-SBC systemd[1]: meshagent.service: Failed with result 'signal'.
May 18 15:59:32 WP-SBC systemd[1]: meshagent.service: Service RestartSec=3s expired, scheduling restart.
May 18 15:59:32 WP-SBC systemd[1]: meshagent.service: Scheduled restart job, restart counter is at 4.
May 18 15:59:32 WP-SBC systemd[1]: Stopped meshagent background service.
May 18 15:59:32 WP-SBC systemd[1]: Started meshagent background service.
May 18 15:59:34 WP-SBC systemd[1]: meshagent.service: Main process exited, code=killed, status=7/BUS
May 18 15:59:34 WP-SBC systemd[1]: meshagent.service: Failed with result 'signal'.
May 18 15:59:37 WP-SBC systemd[1]: meshagent.service: Service RestartSec=3s expired, scheduling restart.
May 18 15:59:37 WP-SBC systemd[1]: meshagent.service: Scheduled restart job, restart counter is at 5.
May 18 15:59:37 WP-SBC systemd[1]: Stopped meshagent background service.
May 18 15:59:37 WP-SBC systemd[1]: Started meshagent background service.
May 18 15:59:38 WP-SBC systemd[1]: meshagent.service: Main process exited, code=killed, status=7/BUS
May 18 15:59:38 WP-SBC systemd[1]: meshagent.service: Failed with result 'signal'.
May 18 15:59:41 WP-SBC systemd[1]: meshagent.service: Service RestartSec=3s expired, scheduling restart.
May 18 15:59:41 WP-SBC systemd[1]: meshagent.service: Scheduled restart job, restart counter is at 6.
May 18 15:59:41 WP-SBC systemd[1]: Stopped meshagent background service.

So i stopped the service and ran the agent manually, this is what I am getting:

root@WP-SBC:/usr/local/mesh_services/meshagent# ./meshagent
Connecting to: wss://redactedurl:443/agent.ashx
Connected.
Bus error

I'm not really where to start looking as Bus error doesn't give me much to go on, any ideas please @Ylianst ?

This is running on a raspberry pi:

No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Thanks

**Comment by krayon007** [comment]
This isn't an error that the agent returns on it's own, it looks like an OS error that was propagated. From what I can tell it looks like a memory error.  Can you see how much free memory you have, and if any processes are consuming a lot?

**Comment by drnikcuk** [comment]
nik@WP-SBC:~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:           1798         228         908          17         661        1484
Swap:            99           0          99

Barely using the available memory by the look of that ?

**Comment by drnikcuk** [comment]
This was caused by changing the following setting on the pi:

/boot/config.txt

Add the following line.

arm_64bit=1

The result of this is to switch your Raspberry Pi to 64-bit kernel and also break meshagent !
