### ISSUE TITLE
meshcentral server keep crashing

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2661]
all the sudden the meshcentral keep crashing when trying to login,

this is the error:
```
/home/node/meshcentral/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:604:37)
    at Buffer.toString (buffer.js:801:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```

**Comment by Ylianst** [comment]
It looks like you NeDB database got corrupt. This is not something I can do anything about. Go in "meshcentral-backups" and restore the ".db" files to the latest working database.

If you have no backups, the .db files in "meshcentral-data" are next files and it's possible to fix them. Let me know if that is needed. If you are running a large server, I do recommend switching to MongoDB as it's more robust.

**Comment by smartekIT** [comment]
how to setup MongoDB in ubuntu 20.04 ?
also when i tried to extract the backup zip files it asks for password, but when i configured the backup i never set a password !!!

**Comment by smartekIT** [comment]
sorry i found the password, was in the config file. but although it worked for all file except the plugins directory saying it's wrong password!!! how come the password for the backup works to extract all files in the zip file except the plugin directory inside that zip file !!!

**Comment by Ylianst** [comment]
For MongoDB, please look at the MeshCentral User's Guide, [it's on this page](https://meshcentral.com/info/downloads.html).

**Comment by smartekIT** [comment]
thanks .. all good now.
