### ISSUE TITLE
Terminal sharing on linux is no longer possible.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2662]
Hello.
Terminal sharing on linux is no longer possible.
"Remote Terminal Link" is not created after setting "Share Device".
Guest sharing link is not created..

Thank you.

**Comment by Ylianst** [comment]
Oh, Your right! I see the same problem. Working on it now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.41 with a fix. Let me know if it works and close this issue if it does work. Thanks.

**Comment by kuksabong** [comment]
Terminal sharing on linux works well.  Thank you for your help.

**Comment by Ylianst** [comment]
Ok. Next time please close the issue.
