### ISSUE TITLE
Cannot reuse invite code

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2663]
Hello.
After changing the invite code to another value, the existing invite code cannot be reused.
If I enter an existing invite code that is not currently used anymore, the following error occurs.

**"Invite Codes: Error, invite code "1111" already in use."**

![image](https://user-images.githubusercontent.com/6889244/118930902-47b69580-b981-11eb-8ebe-c75bb72979ad.png)

**But invite code 1111 is a value that is no longer used by any group.**

Thank you.

**Comment by VINISHVV** [comment]
@kuksabong - can you try upgrade to latest version once ?

**Comment by Ylianst** [comment]
I did find that if you create a device group, put an invitation code and delete the group, the invitation code would remain and could not be reused. I put in a fix for this. Will be in MeshCentral v0.8.44.

**Comment by kuksabong** [comment]
Thank you so much for your hard work.

**Comment by Ylianst** [comment]
Did it fix it? If so, please close this issue. Thanks.
