### ISSUE TITLE
Mongodump error after update to latest version

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2666]
Dear Ylian,

After updating server from 8.40 to 8.43 system showing below error.

WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed.

**Comment by paolor1965** [comment]
Hi, I confirm the same error

**Comment by VINISHVV** [comment]
I am also having same issue.

**Comment by Ylianst** [comment]
Looking into it.

**Comment by nzalev** [comment]
> Looking into it.

Please see https://github.com/Ylianst/MeshCentral/pull/2659#issuecomment-845520929 , https://github.com/Ylianst/MeshCentral/pull/2659#issuecomment-845529253 , https://github.com/Ylianst/MeshCentral/pull/2659#issuecomment-845529253

**Comment by Ylianst** [comment]
Just put in a fix for this. I no longer try to change the URL is any way, but do display any MongoDB errors so that administrators can see any issues MongoDB has. I think that should be ok.

**Comment by VINISHVV** [comment]
This issue is resolved in v0.8.44

**Comment by Mfinadmin** [comment]
Thanks Ylian for quick fix.
