### ISSUE TITLE
Tools button disappeared in Desktop tab

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2667]
Hi,

I have updated to the latest version (0.8.43) and now the Tools button does not appear in the Desktop tab.
It is something very useful in my work.
Has it been moved to another site or is it an update failure?

Thank you.
Greetings.

**Comment by Ylianst** [comment]
Just checked and I still see the tools button. You will have to provide more information. That button shows up when connecting to remote desktop to a MeshAgent.

![image](https://user-images.githubusercontent.com/1319013/119162466-42079100-ba0f-11eb-9479-341f73e77bc9.png)

**Comment by lergolas** [comment]
Yes, indeed, it appears when you connect to the desktop.
But in previous versions, you had that button without needing to connect to the desktop.
You could see the processes and services of a computer without having to connect, simply by accessing the Desktop tab.
This was very useful to solve problems without interfering with the users' work.
The button was on both Windows and Linux.
It is a very useful feature for me.
Thank you.

**Comment by Ylianst** [comment]
Ok. That makes more sense. I can change that.

**Comment by Ylianst** [comment]
Ok, changed it, will be in MeshCentral v0.8.44.

**Comment by lergolas** [comment]
Thanks for the quick reply!

**Comment by Ylianst** [comment]
@lergolas I am going to close this for you. Next time, please close the issue if solved.

**Comment by lergolas** [comment]
Sorry @Ylianst 
Until today I have not been able to connect and update the Meshcentral to check it.
Next time I'll be faster.
Thanks for everything.
