### ISSUE TITLE
Black screen with no information on General Tab (for non-Administrator users)

### ISSUE THREAD

**Issue by MC-PM** [Ylianst/MeshCentral#2668]
This week several users are reporting that no information is appearing on the General Tab (just a white/black image) with no info and the WebRDP or RDP options are not available, for users using WebRDP this is really blocking their access to it, for tech (Administrator) users all on that tab is working fine.  

![image](https://user-images.githubusercontent.com/63015155/119175926-75aae100-ba38-11eb-98d4-901dfc7f923a.png)

**Comment by MC-PM** [comment]
![image](https://user-images.githubusercontent.com/63015155/119176166-befb3080-ba38-11eb-9b23-c3636a0c86c0.png)

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
I see the same problem. It seems to happen with you grant access to a specific device to a user.

**Comment by Ylianst** [comment]
Just fixed it. Will be in MeshCentral v0.8.44 in a few hours.

**Comment by Ylianst** [comment]
@MC-PM Is this solved? If so, please close the issue.
