### ISSUE TITLE
 Can we set the number of device additions?

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#267]
Dear Ylianst and your team:
Is there a relatively simple way to limit the number of device additions, including the number of agent and agentless, such as modifying config.json files?

Thanks,
Billy DuDu

**Comment by Ylianst** [comment]
Hi. Yes, MeshCentral supports something like this. In the domain section, add this:

```
      "Limits": {
        "MaxUserAccounts": 100,
        "MaxUserSessions": 100,
        "MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      }
```

You only need to put the lines you want to limit, so in your case 'MaxAgentSessions' would probably be it.  You can also go in the "node_modules/meshcentral/sample-config.json" to look at a big config.json sample that includes this.

If you want to limit the number of total agents in a domain (not just agent sessions) and block "add agent" if the number is reached, I don't have this, but if you let me know exactly what you want, I can look at adding it.

Hope it helps.
Ylian

**Comment by billydu1980** [comment]
Very thanks.

I've focused on the "Limits" section and verified that the MaxUserAccounts section is fine. Now I want to limit the number of total agents in a domain (include of software agent and intel AMT ) , base on this feature, it can restrict some users behavior, and reduce the risk of system operation.

Best regard,
Billy

**Comment by Ylianst** [comment]
To be clear, a new "MaxDevices" would limit the total number of devices on a domain and so, if a new device shows up on a domain, it would get rejected? I can do that.

**Comment by billydu1980** [comment]
Yes, that's what I means. 

Thanks,

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.6-a with new MaxDevices in the domain limits like this:

```
      "Limits": {
        "MaxDevices": 100,
        "MaxUserAccounts": 100,
        "MaxUserSessions": 100,
        "MaxAgentSessions": 100,
        "MaxSingleUserSessions": 100
      }
```

Please test and make sure it works. Thanks.

**Comment by Ylianst** [comment]
I will close this one as I think the new "MaxDevices" should solve this issue. Feel free to re-open if needed.

**Comment by bobtux** [comment]
Hi there guys, 
I was wondering, if it is possible to apply       """Limits": { ""  section only on  custumer section .

@Ylianst this feature works this way?

Thanks!
