### ISSUE TITLE
Invite Link missing on My Devices page

### ISSUE THREAD

**Issue by bevstarr** [Ylianst/MeshCentral#2674]
I just upgraded to 0.8.44 and I've noticed that the Invite link that was visible on the My Devices page next to each Device Group name is no longer there.  Is that by choice?

**Comment by Ylianst** [comment]
Fix bad title and spelling.

**Comment by Ylianst** [comment]
The "Invite" link is only available for the "Manage using software agent" device group. The two other device group types that don't use a MeshAgent don't have the invite link. Hope that helps.

**Comment by bevstarr** [comment]
Not exactly.

See the attached images for what I am referring to.
Also when I use the custom config the agents don't download with the correct URL configured, therefore the agents don't find the server.  What am I missing?


![default-mesh](https://user-images.githubusercontent.com/4682661/119277909-4212b700-bbf0-11eb-8637-4b5f0ddf5b4c.png)

![customized-mesh](https://user-images.githubusercontent.com/4682661/119277921-4f2fa600-bbf0-11eb-9abc-d3ecf1987b2b.png)

**Comment by Ylianst** [comment]
Taking a look at the code again, your server is probably in "LAN mode". In that mode, there is no invite link. This is because your server does not have a fixed DNS name, so it's not really possible to create URL links to your server.

**Comment by bevstarr** [comment]
OK got it sorted.  I miss understood the documentation and the settings.  I thought for Hybrid mode both WAN Only and LAN Only had to be set to true.  As it turns out those settings mean exactly what it says, "Only".  In LAN mode (which I didn't realize it was in) those "issue" were not issues, they were the correct operation of the system.  I have now gotten it to run in hybrid along with my custom config (so far) and all is smooth like creamy butter.  Thanks for your help.  Now onto the next bit of learning with this awesome software.
