### ISSUE TITLE
Using TLS Offload, please redirect `x-forwarded-proto=http` requests to use https

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#2675]
I'm testing MeshCentral in an environment where there's a reverse proxy in front of it, but unfortunately both http and https requests (on their standard ports) received by the reverse proxy get forwarded to the same port (I'm unable to change this in this environment) so I can't make use of MeshCentral's included redirect server, rather, MeshCentral ends up being fully accessible via either http or https.  Even worse, if I log in via either, I'm logged in on both, which ... I haven't thought too much about why, but ... it feels unsafe to me.

I believe it shouldn't be too difficult to add a check somewhere in the main MeshCentral server code so that when using TLS Offload It'll look for the `x-forwarded-proto` header and if it's set to `http` reply with a redirect to the requested url using `https` instead of `http`, but I'm not sure where it would belong.

**Comment by Ylianst** [comment]
Interesting. I had never had this request before. I am curious, what environment or hosting vendor has this type of setup?

In general, you don't really need the redirect HTTP port at all except for getting a Let's Encrypt cert and for some Linux distributions that can't download the MeshAgent over HTTPS. So, if I where to see `x-forwarded-proto: http` on MeshCentral 443 and simply deny the request, or just redirect to HTTPS always... would that work?

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.8.45.

**Comment by MailYouLater** [comment]
> I am curious, what environment or hosting vendor has this type of setup?

Heroku.

> In general, you don't really need the redirect HTTP port at all except for getting a Let's Encrypt cert and for some Linux distributions that can't download the MeshAgent over HTTPS... and for user convenience I guess. So, if I where to see `x-forwarded-proto: http` on MeshCentral 443 and simply deny the request, or just redirect to HTTPS always... would that work?

While my main concern was that I figured having a MeshCentral instance be accessible via http as soon as I sign in via https is a problem waiting to happen, therefore blocking it would alleviate my concerns, the convenience factor of being redirected is a big nice-to-have.

> Just put in a fix for this, will be in MeshCentral v0.8.45.

I look forward to verifying the fix soon.  Thank you so much for being so prompt.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.45 30 minutes ago with the fix. Let me know if it works.

**Comment by MailYouLater** [comment]
Just finished trying it out.  Looks like it's working perfectly to me.
