### ISSUE TITLE
migrate from 0.7.31 to latest 2.x

### ISSUE THREAD

**Issue by neroita** [Ylianst/MeshCentral#2676]
Hi all , I'm running a meshcentral 0.7.31 on openbsd 6.8 with mongodb 3.2.22 .
Is there a guide to migrate to latest version without losing agent connections ?
thank's in advance,
marco.

**Comment by nzalev** [comment]
> Hi all , I'm running a meshcentral 0.7.31 on openbsd 6.8 with mongodb 3.2.22 .
> Is there a guide to migrate to latest version without losing agent connections ?
> thank's in advance,
> marco.

We are using OpenBSD 6.8 with meshcentral 0.7.92 (and mongodb 3.2.22 - latest port avilable sadly). I'm a bit confused by your title `latest 2.x`, because none of the listed softwares have a version 2.x that is latest.

Have you upgraded meshcentral before? Are you asking how to go through the upgrade process, or did your agents lose connection after upgrading to a particular version?

**Comment by neroita** [comment]
Sorry , my mistake, I saw from the screenshots that "meshcentral 2" is shown everywhere and I thought there had been a version jump.
I never update version since installation so before doing anythink I've asked.
Is mongodb version a problem ?
Is there somewhere an update guide to be sure to save all my config and not loose connected agent ?
thank's in advance,
marco.

**Comment by nzalev** [comment]
> Sorry , my mistake, I saw from the screenshots that "meshcentral 2" is shown everywhere and I thought there had been a version jump.

I see, I understand the confusion.

> I never update version since installation so before doing anythink I've asked.
> Is mongodb version a problem ?

The MongoDB version is partially a problem, but currently it is not a big deal. The main difference is supported field names:
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names
```Otherwise, starting in MongoDB 3.6, the server permits storage of field names that contain dots (i.e. .) and dollar signs (i.e. $).```

Right now, this matters for some informational keys. For example, `isatap.{151E1E8D-A7C0-4190-9886-91D976E6B84E}`. I have done a fair bit of work recently on MariaDB/MySQL, which should be fully functional on OpenBSD if it ever becomes an issue.

> Is there somewhere an update guide to be sure to save all my config and not loose connected agent ?
> thank's in advance,
> marco.

Upgrading Meshcentral is quite easy and can be done from within the application. Personally, I make a full backup of the meshcentral directory in case a roll-back is ever needed (thankfully, it has never been needed). This does not modify the data directories at all. Internally, meshcentral runs `npm install meshcentral@0.x.y` and restarts itself. Running the npm install command is also a valid way of upgrading if you want a specific version.
![Screenshot from 2021-05-23 14-17-39](https://user-images.githubusercontent.com/63608819/119271994-fcdf8c80-bbd1-11eb-8eb8-67379aa69fc9.png)

The agents will keep their connectivity and do not need to be re-added.

**Comment by Ylianst** [comment]
Exactly right. The first generation of MeshCentral was built in C#/.NET/MSSQL and I ditched it many years ago. It's no longer available. The current generation is available on NPM and I called it "MeshCentral 2" but I am dropping the 2 now and just calling it "MeshCentral" as the first generation is now a bad memory.

**Comment by neroita** [comment]
Ok , thank's to all , I've correctly update to 0.7.89.

**Comment by Ylianst** [comment]
Ok. next time, please close the issue.
