### ISSUE TITLE
Can you use PXE and vPro at the same time?

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2678]

**Comment by Ylianst** [comment]
PXE is a specific type of boot, Intel vPro is a brand used by Intel to identify "made for business PC's". Not really related. I would imagine most Intel vPro computers also support PXE boot.

**Comment by MCJohnB** [comment]
i was not able to use at the same time and was hoping to clarify if they use the same protocols that would conflict.   my guess you have not used both at the same time.
