### ISSUE TITLE
MeshCentral2InstallGuide - "6.8 Increased Security Installation" needs adjustment

### ISSUE THREAD

**Issue by TechnicalJohn** [Ylianst/MeshCentral#2679]
In the Installation PDF, under "6.8 Increased Security Installation" heading, in version 0.1.0 of this doc it says this:

> We can then create the installation folder, install and change permissions of the files so that the
> “meshcentral” account gets read-only access to the files.
> ```
> sudo mkdir /opt/meshcentral
> cd /opt/meshcentral
> sudo npm install meshcentral
> sudo -u meshcentral node ./node_modules/meshcentral
> ```
> 
> The last line will run MeshCentral manually and allow it to install any missing modules and create
> the MeshCentral data folders. Once it’s running, press CTRL-C and continue. The following two
> lines will change the ownership of files to the meshcentral user and restrict access to the files.
> ```
> sudo chown -R meshcentral:meshcentral /opt/meshcentral
> sudo chmod 755 –R /opt/meshcentral/meshcentral-*
> ```

However, running "sudo -u meshcentral node ./node_modules/meshcentral" results in an error because archiver and otplib needs to be installed, and the owner of /opt/meshcentral has not yet been changed.

To get this to work properly, the "chown" command needs to come before "sudo -u meshcentral" and "chmod" should come after, like this:
```
sudo mkdir /opt/meshcentral
cd /opt/meshcentral
sudo npm install meshcentral
sudo chown -R meshcentral:meshcentral /opt/meshcentral
sudo -u meshcentral node ./node_modules/meshcentral
sudo chmod 755 –R /opt/meshcentral/meshcentral-*
```

**So perhaps re-writing that section like this:**

We can then create the installation folder, change permissions of the folder, install, and change permissions so that the
“meshcentral” account gets read-only access to the files.
```
sudo mkdir /opt/meshcentral
cd /opt/meshcentral
sudo npm install meshcentral
sudo chown -R meshcentral:meshcentral /opt/meshcentral
sudo -u meshcentral node ./node_modules/meshcentral
```
The last line will run MeshCentral manually and allow it to install any missing modules and create
the MeshCentral data folders. Once it’s running, press CTRL-C and continue. The following
line will change the ownership of files to the meshcentral user and restrict access to the files.
```
sudo chmod 755 –R /opt/meshcentral/meshcentral-*
```

**Comment by si458** [comment]
the PDF is outdated and shouldnt be used!
please follos the new docs instead https://ylianst.github.io/MeshCentral/
