### ISSUE TITLE
I am not able to use Meshcommander and Meshcentral to watch PXE boot process. Any suggestion?

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2680]
i was not able to use at the same time and was hoping to clarify if they use the same protocols that would conflict. my guess you have not used both at the same time.

**Comment by Ylianst** [comment]
This is not really a MeshCentral question. You can ask Intel support or got to Intel discussion forums for this.

**Comment by MCJohnB** [comment]
Thank you for your response and I will.
