### ISSUE TITLE
Assistant image file is missing from invite link.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2681]
Assistant image file "**assistant-312.png**" is missing from invite link.

![assistant-312 png_missing](https://user-images.githubusercontent.com/6889244/119421546-e6ecdb80-bd39-11eb-9982-4b927c523411.JPG)

Thank you.

**Comment by Ylianst** [comment]
Ha! Thanks for reporting this. Will be fixed in MeshCentral v0.8.46.

![image](https://user-images.githubusercontent.com/1319013/119427756-70f85e00-bcc0-11eb-8305-dd6996101e59.png)

**Comment by Ylianst** [comment]
MeshCentral v0.8.46 is published. Check and close this issue if ok.

**Comment by kuksabong** [comment]
Thanks a lot!
