### ISSUE TITLE
The terminal does not work in the local devices group.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2682]
After a certain period of time, terminal access to devices added to the local device group is not possible.
When I click the "Connect" button, the login window does not appear.
At this time, if I restart the service with the command "systemctl restart meshcentral", I can connect terminal again. 
But Remote access is possible with Web-SSH.

![agentless terminal](https://user-images.githubusercontent.com/6889244/119439013-668ba200-bd5c-11eb-9025-a6b1292c46f0.JPG)

**Comment by Ylianst** [comment]
Added a fix for this. Will be in MeshCentral v0.8.47. Once published, please check that it's ok and close this issue. Thanks.

**Comment by Ylianst** [comment]
MeshCentral v0.8.47 was published.

**Comment by kuksabong** [comment]
Thank you.!!
