### ISSUE TITLE
Issues related to Meshcentral Assistant in Invite page

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2683]
Dear Ylian,

Getting a zip file instead of Assistant.exe file from invite url. Please do the needful.

**Comment by Ylianst** [comment]
Thanks for reporting this. Just put in fix, will be in MeshCentral v0.8.47.

**Comment by MailYouLater** [comment]
I was also experiencing this issue, and I've just updated and am now able to download a `MeshCentralAssistant.exe` file from a `/agentinvite` url.

I'm having issues using it, but that belongs in a separate GitHub issue.

**Comment by VINISHVV** [comment]
Issue resolved.
Thanks Ylian.
