### ISSUE TITLE
Meshcentral Assistant option for auto-connect with mandatory user consent

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2685]
Dear Ylian,

I like the latest meshcentral Assistant with built in connectivity to server. Is there any options to run the assistant in bacground like meshagent instead of initiate request help ?. / Can you introduce such assistant ?

**Comment by Ylianst** [comment]
Would the background version of Assistant not be the MeshAgent? You can run the MeshAgent in the background and run Assistant on the taskbar and the user can request help thru the MeshAgent.

**Comment by Mfinadmin** [comment]
But in such case we need to install both meshagent and assistant.

 I would like to use all the functions of meshagent through assistant app only.

**Comment by Mfinadmin** [comment]
Like interactive and background meshagent can you develop meshcentral assistant with direct server connectivity ?

**Comment by Ylianst** [comment]
Why?

**Comment by Ylianst** [comment]
Ok.

1. To have help request, the app can't be in the background. It must be running on the user's desktop.
2. This is a valid request for MeshAgent.
3. If you run in the background, installation will be required.

**Comment by VINISHVV** [comment]
Yes. i would like to install single application.

is it possible to create such an assistant app ?

**Comment by Ylianst** [comment]
Can you be more specific? What will the "single application" do?

**Comment by Mfinadmin** [comment]
This will do all the activities of meshagent.  Since meshagent does not have the features mentioned above I would like to install assistant application in my office without agents. But the only problem I noticed the assistant require user action to connect to server

**Comment by Ylianst** [comment]
So you want the same Assistant, but with auto-connect to server?

**Comment by Mfinadmin** [comment]
Yes, is it possible ?

**Comment by Ylianst** [comment]
So, it would still run on the system tray. Because MeshCentral Assistant is a signed application, I have to have user initiation or user consent. So, if I create a mode to auto-connect, the user will still be able to disconnect and user consent will be mandatory. Is that ok?

**Comment by Mfinadmin** [comment]
Dear Ylian,

It's okay.  But if it require more time to develop such an application then you can change this issue priority to low.  Because this will not affect other important issues

**Comment by Ylianst** [comment]
I have been working on this as part of an update to MeshCentral Assistant. Hopefully I will have an update next week.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.49 with a new option to have MeshCentral Assistant be always connected to the server. You can see the option when you check "Add Agent". In this mode, Assistant will always prompt for user consent when doing remote desktop or remote files. Let me know if that works.

![MC2-Assistant-AlwaysConnected](https://user-images.githubusercontent.com/1319013/119913208-28d07a00-bf12-11eb-87d4-3ba8283bcf0f.png)

**Comment by Mfinadmin** [comment]
Wow !!!!!
You are really super fast.

I have tried the same and it's working fine in few systems. Some of the windows 7 PC's I am getting below error /debug file.

UnhandledExceptionEventSink: System.NullReferenceException: Object reference not set to an instance of an object.
at MeshAssistant.MainForm..ctor(String[] args)
at MeshAssistant.Program.Main(String[] args)

**Comment by Ylianst** [comment]
Yes, the null exception problem was reported as #2694. It's faulting here. One workaround until I fix it is to run the basic MeshCentralAssistant.exe from `/node_modules/meshagent` once. Then, stop it and then run the MeshCentralAssistant.exe you downloaded that includes the device group. I will have a fix for this in 2 days then I get back to work.

**Comment by Mfinadmin** [comment]
Thanks Ylian, Its working fine in latest version.
