### ISSUE TITLE
SSO + Maintenance Mode + Regular Users = Access to server

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#2686]
Hi Ylian,

I see that under a SSO engagement that the users are passing through the Maintenance mode, getting to the login page, then going from the login page through SSO and hitting the main page of the MeshCentral with their normal user access groups available to them.

I don't notice this being the case in the non SSO space... 

Thank you,
SomeGuru

**Comment by Ylianst** [comment]
Ha yes. Just put in a fix for this. Will be in MeshCentral v0.8.47. If it works, please close this issue.

**Comment by Ylianst** [comment]
MeshCentral v0.8.47 was published.

**Comment by SomeGuru** [comment]
Still seeing on main branch instance on Ubuntu 20.04 running latest MeshCentral 0.9.84. Have not pushed to production branch yet.

Thanks,
SomeGuru
