### ISSUE TITLE
Connecting with Share link fails with expiration date too far in the future

### ISSUE THREAD

**Issue by sblosser** [Ylianst/MeshCentral#2687]
Running 0.8.46

Steps to reproduce:

1. Create a "Time Range" Share link with an expiration date a year into the future
2. Try to connect using the Share link.
3. Connection gets stuck in "Setup..."

In reviewing the server error logs, this message is present:

```
(node:17952) TimeoutOverflowWarning: 32052562244 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

A share link with a closer expiration date works, but once I get over a few weeks it fails. I'd like to create a Share link good for at least a few months, or one that is good until revoked would also be OK.

**Comment by Ylianst** [comment]
Interesting. Checking this now. Thanks for posting the step to reproduce, that makes my work so much easier.

**Comment by sblosser** [comment]
I did a little more experimenting and if I keep the end time under 2147483647 (upper limit for 32-bit signed int) milliseconds (or 24.86 days) in the future, it works. You could probably reduce the time frame resolution to seconds which would increase the usable range by a factor of 1000.

**Comment by Ylianst** [comment]
Right. Exactly. I am trying to make this error happen now, before I try to fix it.

**Comment by Ylianst** [comment]
Fixed it. Will be in MeshCentral v0.8.47. This is a NodeJS timer issue, you can't specify a long timeout and it must be specified in milliseconds. So, for very long expire times, I don't start time timer at all. So, in theory if you start a session that expires more than 23 days after start, the server will not auto-disconnect it.

**Comment by Ylianst** [comment]
MeshCentral v0.8.47 was published. Check and if it works, please close this issue.

**Comment by MailYouLater** [comment]
> So, for very long expire times, I don't start time timer at all. So, in theory if you start a session that expires more than 23 days after start, the server will not auto-disconnect it.

This sounds bad... While a 23+ day connection seems unlikely, and anyone you're giving that long to be connected is likely someone you feel is trustworthy, I still really don't like the idea that you could offer someone a month-long session, and potentially end up giving them an unlimited length session instead.

Any chance that in cases where a timeout would be too long to fit in your variable, you instead run the timer for the full length that you're sure will fit, then try again?  (At which point either the proper timer length will fit, or you do the same thing again.)

Also, couldn't you double the length of allowed timers by using an unsigned variable instead of a signed one?

**Comment by Ylianst** [comment]
It does sound bad. Running the timer the full length and trying again is a good idea. Working on that now.

**Comment by Ylianst** [comment]
Ok, just push an improved version that fixes it without the 23 day issue.

**Comment by sblosser** [comment]
I can indeed confirm that this is fixed. Thanks so much @Ylianst for the quick fix!!

**Comment by PetieM** [comment]
Just tried creating a year-long link and am running into this issue now. I'm having other problems connecting to this machine which may or may not be related but I'm seeing the original error message in my own server logs. Currently running 0.8.62 and what's interesting is that the file manager connects and works just fine, the expiration date is shown correctly, but trying to connect to the desktop gets to the setup phase and then disconnects, throwing the TimeoutOverflowWarning in the process.

I was able to connect once via the normal desktop feature though that's not working now either (with the same setup/disconnect behavior though no error) so there's a possibility that whatever is going on there may be the cause of what I'm seeing and not this particular bug.
