### ISSUE TITLE
MeshCentral Assistant file does not run on the system tray

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2690]
After downloading the MeshCentral Assistant file from the invite page, I can't run Assistant on the system tray.

Thank you!

**Comment by Ylianst** [comment]
You have to provide a lot more information. What operating system are you running? What version of MeshCentral? What happens when you try to run it? Just saying "can't run" does not help solve the problem. Thanks.

**Comment by kuksabong** [comment]
Hello. 
I am sorry. 
When I download and run the MeshCentral Assistant file from the invite page, the Assistant appears in the system tray and disappears after a while.
- OS version  : Windows 10 Pro - 2004 [19041]
- MeshCentral version: 0.8.48

![assistant](https://user-images.githubusercontent.com/6889244/119640698-d597f200-be53-11eb-8e13-0739cc110f59.JPG)
