### ISSUE TITLE
It is not possible to wake-up the PC in sleep state.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2691]
Even if I issue a sleep action command to the remote PC in device action and then issue the wake-up action command again after a while, the remote PC continues to sleep.
In other words, it is not possible to wake-up the remote PC in sleep state.

Thank you!

**Comment by Ylianst** [comment]
For wake up to work you need to have Wake-on-LAN (WOL) enabled on the target device or have Intel AMT activated. For Wake-on-LAN, if your server is in "LAN mode" or "Hybrid mode", the server will send WOL packet on the local network. In addition to this, the server will ask all agents in your account to send WOL packets on their networks.

So, if you have an office with 10 computers and turn off 9 of them, you should be able to turn them back on. But if you turn off all 10, there is no way to wake up any of them.

Hope that helps.
