### ISSUE TITLE
MeshCentral Assistant Customization

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2692]
HI,
Will Assistant get customization option in the config.json like the agent do? so can change name, texts, colour .... etc. so can well reflect our existing branding option?

**Comment by Ylianst** [comment]
Yes, I will be working on MeshCentral Assistant branding. I think it was the option to look really good.

**Comment by Ylianst** [comment]
Published with MeshCentral v0.8.56. Let me know if that works.

![MC2-AssistantBranding](https://user-images.githubusercontent.com/1319013/120866171-3e622700-c544-11eb-8190-5f9236e9c1a3.png)

**Comment by smartekIT** [comment]
Thanks heaps, will try it.
