### ISSUE TITLE
Keyboard input language cannot be switched on Desktop.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2698]
Hi.
When I connected to the desktop and converted the keyboard input language from English to Korean, it was not inputted in Korean. It was continuously typed in English.

![language](https://user-images.githubusercontent.com/6889244/119843875-e7a48e00-bf42-11eb-913e-56a6c65b47a8.png)

**Comment by Ylianst** [comment]
Hi. Change this setting and let me know if it works:

![image](https://user-images.githubusercontent.com/1319013/119888503-48ec4300-beea-11eb-85d3-c191c2dc7490.png)

**Comment by kuksabong** [comment]
Thank you very much!
