### ISSUE TITLE
Question - Related to server bandwidth utilization

### ISSUE THREAD

**Issue by JOSEPHDEVASSIA** [Ylianst/MeshCentral#2699]
Hi
Facing issues related to server bandwidth. Currently i have activated below compression methods and my server running with the  session record  functionality. One day recording file size will be approximate 300GB.

Can you please confirm disabling session record will improve the bandwidth usage ? / can you implement restrictions like concurrent user sessions, Maximum desktop quality etc...

```
  "Compression": true,
  "WsCompression": true,
  "AgentWsCompression": true
  "minify": true
  "DesktopMultiplex": true
```

**Comment by Ylianst** [comment]
In the "settings" section, add the following line:

```
"AllowHighQualityDesktop": false
```

That will block selection of the highest remote desktop quality.

I also added a graph to see the types of traffic the server is receiving and sending.

![image](https://user-images.githubusercontent.com/1319013/119885716-070dcd80-bee7-11eb-9f26-0c014b600952.png)

Take a look at it and see if desktop is the highest or if it's something else.

In the domain section of the config.json, you can add this:

```
      "Limits": {
        "MaxDevices": 100,
        "MaxUserAccounts": 100,
        "MaxUserSessions": 100,
        "MaxAgentSessions": 100,
        "MaxSingleUserSessions": 100
      },
```

However, these are for all of the domain except for "MaxSingleUserSessions" which is the maximum number of browsers a user can have open. I need to add a limit on the number of connection tunnels a user can have and do want to add user accounting for traffic, so you know the exact cost for traffic for each user. Certainly things I want to build.

**Comment by JOSEPHDEVASSIA** [comment]
Dear Ylianst,
 Can you add  limit on the number of connection tunnels for a single user and user accounting for traffic,

**Comment by Ylianst** [comment]
Yes, this is already requested in #2549. I think it will also be important to keep track of how much data each user is using because even with 1 remote desktop tunnel, you can still use a lot of data.
