### ISSUE TITLE
Remote desktop key mapping

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#27]
When using the remote desktop the hash key(#) does not work.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.2-k on NPM that fixes the "-" and "=" keys on FireFox on US keyboards. Hopefully this will fix this problem. If not, please let me know the OS and browser you are using and the keyboard setup you have (US-EN, FR-CA...). Thanks.

**Comment by Ylianst** [comment]
There is a bit of a problem with MeshCentral and international keyboards. The keys are mapped to an international keyboard twice, once on the browser side and once on the remote PC. To solve this, you can add a "US-EN" keyboard on the browser side or remote PC. "US-EN" keyboard does not seem to do any key mapping and so, usually solves the problem. It would be nice if browsers gave key scan codes to web applications.

**Comment by Ylianst** [comment]
Taking a look at https://javascript.info/keyboard-events. I may be able to map key codes back into scan codes and make fix this problem. I will take a look.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.5-w with a fix for keyboard mappings. Starting with this version, the local keyboard language is ignored and only the remote keyboard mapping is used. This is a lot better than previous versions of MeshCentral where both local and remote keyboard language mappings where used causing all sorts of issues. Please re-open this issue if there are more problems. - Thanks.
