### ISSUE TITLE
auto lock pc upon disconnect

### ISSUE THREAD

**Issue by smartkid808** [Ylianst/MeshCentral#270]
would be nice to have MC auto lock the PC after disconnect.. Maybe make this a per group setting, as some groups you don't want to have it lock during support session.

**Comment by Ylianst** [comment]
Bryan will have to add locking support in the agent. I imagine the request is to lock only for remote desktop (not files/terminal)? Is this for Windows/Linux/MacOS?

**Comment by smartkid808** [comment]
Hi Ylian..  Just lock the desktop is good enough. have the ctrl-alt-del screen come up and for Windows.

**Comment by PathfinderNetworks** [comment]
Just make sure this is an optional thing (like a check box at the device level we can select per session- similar to the 'Input' box, etc).  I can't have this be a default setting for all devices.

**Comment by wcrlewis** [comment]
It should be an option for connection loss in addition to user-selected disconnection.

**Comment by krayon007** [comment]
I have support for locking the windows desktop, and just tested support for Linux. Will need to investigate MacOS and FreeBSD. Once I have those, it should be trivial for ylian to add a configuration for what you asked.

**Comment by smartkid808** [comment]
awesome thanks!

**Comment by krayon007** [comment]
I got it working on MacOS as well, so I'll tie it all up with some code, that Ylian can use to do what you need. I haven't found a way to do it reliably on FreeBSD yet, but for now, we'll support Windows, Linux, and MacOS with this feature.

**Comment by ghplw** [comment]
Humans are well known for being lazy so I would love to have the option of making this globally enforced for all my users.

**Comment by dernippel** [comment]
For Windows sending  "Win+L" would be an option. Sending this command is already implemented in the meshcentral gui. I do also prefer per device or per group definition of locking the screen after disconnect from desktop.

**Comment by JSuenram** [comment]
Is this already implemented?
Maybe we can close this?

**Comment by si458** [comment]
this is implemented now sort of,
simple connect, then before disconnecting, right click disconnect and click 'disconnect and lock'
