### ISSUE TITLE
Add optional version parameter to `serverupdate` command

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#2704]
It would be nice to be able to specify what version of MeshCentral to install when running `serverupdate`.  Is there any chance that you could update the command to accept an optional version number after it? i.e. `serverupdate 0.8.48`

Also, since the UI allows picking between two versions ("Stable" and "Latest") perhaps the command could also accept `serverupdate stable` and `serverupdate latest`.

I was wanting this so that I could test things on different versions, but it Seems likely that it would also be helpful in other situations.  For instance, reverting an update when the new version breaks something, and it would greatly simplify the instructions needed to do the temporary server downgrade you recommended in #2700.

You could just say "Go to the server console and run `serverupdate 0.7.1` instead of...
> Go in the folder above "node_modules" and "meshcentral-data". Then, do this:
> 
> - Stop the server from running in the background.
> - Rename "node_modules" to "node_modules_bak".
> - run "npm install meshcentral@0.7.1".
> - run "node node_modules/meshcentral"
> - Wait for all extra modules to be installed and the server to run.
> - Hit Ctrl-C
> - Start the server again in the background.

**Comment by nzalev** [comment]
@Ylianst I can take this if you want

I think for now, it will just be a console command, but I think I could add it to the UI as well - it just needs validation for the version number

**Comment by Ylianst** [comment]
This is a good idea, will certainly start by adding it to the console.

**Comment by Ylianst** [comment]
Ha! I just realized @nzalev already put in a pull request for this!!! #2707

**Comment by nzalev** [comment]
Latest pull request adds validation to the version argument. @MailYouLater I believe this will be in version 0.8.50.

I can add a version textbox to the UI, but that will be something separate to this issue.

**Comment by MailYouLater** [comment]
Honestly, I'm not sure it _should_ be added to the UI.  Keeping the UI simple and offering the more advanced options via console commands seems fine to me in this instance.

Thanks for working on this @nzalev.  If you're looking for more to do, I think the only thing left regarding this request is that it would be nice if a help message was added to explain the new functionality of the `serverupdate` command.

**Comment by nzalev** [comment]
> I think the only thing left regarding this request is that it would be nice if a help message was added to explain the new functionality of the `serverupdate` command.

Thank you for reminding me, this had slipped my mind today. I have added the updated help message to the pull request.

**Comment by Ylianst** [comment]
BIG THANK YOU to @nzalev for doing the MeshCentral change for this. It's in MeshCentral v0.8.50 that was just published. Let me know if it works.

**Comment by MailYouLater** [comment]
It's working as expected for me.

Thank you both so much!
