### ISSUE TITLE
MeshCentral v0.8.49 now required NodeJS v10 or better

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#2705]
Just a note to say that the latest published version of MeshCentral required NodeJS v10 or higher. In the past MeshCentral ran on v6 or better, but some features like Let's Encrypt required higher NodeJS versions.

I have to up the NodeJS version since many dependency modules only run on later versions of NodeJS and have security fixes. I feel security takes priority here.

This will probably not affect many people, but making sure everyone knows.

**Comment by Ylianst** [comment]
Note that you can see what your current NodeJS version is on the server by going to the "My Server" and "Console" tab and typing "Versions". Look for the "node" line.

**Comment by ryanblenis** [comment]
Perfect! Not sure if it was a thought as part of this, but I'd love to see more async / await syntax in the code versus callbacks- it makes the code look a lot cleaner and easier to comprehend at a glance!

**Comment by Ylianst** [comment]
Indeed, increasingly more modules are using this syntax and so, was important to set the new minimum bar.

**Comment by darryl-h** [comment]
Ran into this new version requirement in my dev environment when upgrading the other day. You may want to consider adding these instructions to https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf for Ubuntu 18 as canonical are at NodeJS 8.10.0 for Ubuntu 18.x

The instructions (at least for me) were found in the documentation from NodeSource for NodeJS (https://github.com/nodesource/distributions/blob/master/README.md) which seem to work for new installations as well as upgrades from NodeJS 8.x.

```shell
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**NOTE**: In one instance, I ran into a dependency issue with `nodejs-dev` (I can't reproduce now of course) and I needed to run `sudo apt-get --purge remove nodejs nodejs-dev npm` to work around it.


```shell
sudo apt-get --purge remove nodejs nodejs-dev npm
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Also note that for me, running `node` results in an error (both in the 8x branch, and the 16x branch, albeit they added color in the new version) and I believe the correct command to determine the version of NodeJS in Ubuntu 18 is `nodejs -v` not `node -v` orrr I'm doing it wrong. :)

In 8.x

```shell
# node -v
module.js:549
    throw err;
    ^

Error: Cannot find module '/root/–v'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
```shell
# nodejs -v

v8.10.0
```

In 16.x
```shell
# node –v
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/root/–v'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

```shell
# nodejs -v

v16.2.0
```

**Comment by uldiseihenbergs** [comment]
@Ylianst hi, i wrote an email to your hotmail yesterday with details about moving from node 8.10 to node 14 in docker..

**Comment by si458** [comment]
meshcentral now requries node 16 so cloing this issue as completed and old
