### ISSUE TITLE
Question: transferring remotes between MC2 servers

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2706]
If a remote system is configured to connect to a specific group (MCAG1) on server MC_A, is it possible to later run a subsequent installer script that moves it from MCAG1 to a specific group (MCBG2) on server MC_B? 

I'd normally just go ahead and try this without posting a question, but considering it could be quite the atomic change, I'd rather not lose access to the remote should anything go wrong.

Thoughts?

**Comment by Ylianst** [comment]
There is no built-in way to do this, but if you change the "meshagent.msh" file and restart the agent, the agent will connect to the new server. Of course, do test this first on dummy machines, but should work.

**Comment by MailYouLater** [comment]
I've done this in test environments.  After placing the new `.msh` file, you can go to the Desktop tab, click the Tools button, switch to the Services view, click on the Mesh Agent service, and trigger a restart.  Assuming you placed a valid `.msh` file in the correct location, it should work fine.  And as Ylianst says, it's always a good idea to test.

**Comment by D4V3M0NK** [comment]
For prosperity's sake a few notes I made regarding how to do this on Ubuntu, noting that the (source) server is the existing server that has the remote system already installed upon it, and the (target) server is the server that the remote will be moving to:

1. On a remote system already connected to the target server, run `sudo systemctl status meshagent`
   1. This should give a path to the meshagent executable that's running on the system.
   2. Typically this would be `/usr/local/mesh_services_meshagent/meshagent`
4. Navigate to the folder containing the running service binary (eg `/usr/local/mesh_services/meshagent`)
5. From the meshagent.msh file within that folder, ascertain (`head -n6 meshagent.msh`) the values of the following settings:
   1. MeshName, MeshType, MeshID, ServerID, MeshServer
7. On the remote system connected to the source server, run `sudo systemctl status meshagent`
   1. This should give a path to the meshagent executable that's running on the system.
   2. Typically this would be `/usr/local/mesh_services_meshagent/meshagent`
10. Navigate to the folder containing the running service binary (eg `/usr/local/mesh_services/meshagent`)
11. Backup the meshagent.msh file within that folder.
12. Update the meshagent.msh file with details copied from the existing target remote (3.i)
    1. `sudo vi /usr/local/mesh_services/meshagent/meshagent.msh`
14. Restart the meshagent service to move the remote from the source to the target server.
    1. `sudo systemctl restart meshagent`
