### ISSUE TITLE
Add ability to change sender name on MeshCentral agent invite emails. 

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#271]
Hi Ylian, this is an enhancement request to your newly added Mesh Agent invite feature (which is awesome!).  
I just updated my server and sent a test email using the invite system.  It looks good except that I don't like that it uses my MeshCentral logon name as the sender in the email.  It's showing up in two spots- in the first paragraph and in the salutation.  
It would be hugely beneficial if we could modify the sender name as necessary (ideally right in the invite dialog- or in the config.json at the worst case).   It would also be nice if I could change the wording a bit- the message doesn't really make it clear it's coming from my company.  Some users may (or should I would hope) think it's a phishing type of email as a result.    Obviously I would tell them in advance I'm sending the email but I would still like to customize it a bit.

**Comment by Ylianst** [comment]
Hi. The email invitation was added a long time ago, I just added the URL invitation this week and added the URL invitation to the same dialog box. One thing I was thinking is to change the email invitation to just send the invitation URL and make the email a lot simpler. Currently, I am placing all the instructions in the email which is not great.

More importantly: if you go in "meshcentral-data/mail-templates" you can customize the emails the way you want. Can you check that out and see if that works for you? Of course, I will change the templates again if we go for just sending the invitation URL.

**Comment by PathfinderNetworks** [comment]
Hi Ylian, 
I'm attempting to modify the templates.  I see mesh-invite.txt and mesh-invite.html.  I assume one is for HTML messages and the other plain text messages?  In any event, any changes I make to those templates is completely ignored.  Do I need to restart the server for it to use the changes in the template by chance?

**Comment by PathfinderNetworks** [comment]
Ok, just answered my own question. Yes, I had to restart the MeshCentral server for it to use the changes I made to the email templates.  Editing those templates works perfectly for my needs.

**Comment by Ylianst** [comment]
Perfect. yes, the server needs to be restarted. I could change that behavior if needed.

On a separate note, I am thinking of removing the Windows/Linux/MacOS instructions in the email and replace them with a link to the agent invitation page. Would that be ok with you?

**Comment by PathfinderNetworks** [comment]
Yeah, that would be fine with me.  Especially if we can continue to use the optional message field for those invite emails.

**Comment by Ylianst** [comment]
FYI. With MeshCentral v0.3.6-m I added an invitation link email option. You need to update your email templates to make it work. For most people, you delete the "mail-templates" in "meshcentral-data" and reset the server. The new version of the templates will be generated.

Some people that have custom templates, make a backup first and rename the "mail-templates" folder to get the new version of the templates. The changes are not too bad.

**Comment by dinger1986** [comment]
looks like this is done @si458

**Comment by si458** [comment]
@dinger1986 will keep open and add DOCS tab as i didnt no we could customise the email invites!
https://github.com/Ylianst/MeshCentral/issues/271#issuecomment-501580055
