### ISSUE TITLE
2F email sending option required in password reset page

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2710]
Dear Ylianst,

In my server i have activated force 2F authenication.

Recently i have noticed an issue for reset account. If some one forget the password and trying to reset the password through Reset password option, then system will ask the access token. There no options for sent token through email.

Can you add send token buttons in reset password page?

**Comment by Ylianst** [comment]
Hi. If a user wants to allow 2FA tokens to be sent by email, you need to turn on this in the "My Account" tab here:

![image](https://user-images.githubusercontent.com/1319013/120226819-ca9ae400-c1fc-11eb-84a1-b8271509a38c.png)

However, we use email for password recovery so also using email for 2FA is a security problem. Users are requested to setup as least two 2FA methods so the server can be use it's the right user. If a user's email account is hacked, it does not makes sense to have both password recovery and 2FA be the email account. Someone could take over the MeshCentra account.

Hope that makes sense, for security, I don't think this is possible.

**Comment by VINISHVV** [comment]
Dear Ylian,

Yes this is a security issue, Thanks for your detailed explanation.
