### ISSUE TITLE
Relay Mapping functionality needed. 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2712]
Dear Ylian,

I am currently using mesh router relay mapping optiins for connecting other agentless devices. This is a very helpful options for us.

can you enable same function in meshcentral without Router ?

**Comment by yomono** [comment]
This plugins does what you need, I think:
https://github.com/ryanblenis/MeshCentral-RoutePlus

**Comment by Ylianst** [comment]
Yes, the original request is not specific. Not sure what is requested. Let me know if the plug-in is what was needed.

**Comment by VINISHVV** [comment]
Installed the Plugin suggested by @yomono . Incase any issues i will create new issue
