### ISSUE TITLE
MeshCentral Assistant ConnectPipe() Failed with Built-in Agent

### ISSUE THREAD

**Issue by kj7ice** [Ylianst/MeshCentral#2713]
First, a huge thank you to Ylian and team for this amazing software! MeshCentral is by far my favorite RMM and remote desktop support tool.

I upgraded my server to version 0.8.50 to test out the new MeshCentral Assistant with built-in agent. I downloaded the assistant with the "connect on user request" installation type. On a computer that has never run any MeshCentral applications before, the Request Help button does nothing when I click on it. No request details prompt or anything comes up. Re-running with the -debug flag produces the log below. The computer is running Windows 10 Pro 64-bit.

Any suggestions or ideas? I also tried running the assistant on a different computer with the background mesh agent, and everything works fine there. Thank you in advance for your support!

```
23:11:PM.2863: ***** Starting MeshCentral Assistant *****
23:11:PM.2903: Checking for embedded MSH file
23:11:PM.3203: Set TLS 1.2
23:11:PM.3223: InitializeComponent()
23:11:PM.3713: Check for built-in agent
23:11:PM.3733: Starting built-in agent
23:11:PM.4073: MCAgent: LoadAgentCertificate() - Loaded existing certificate.
23:11:PM.4163: MCAgent: MSH MeshID: [hash]
23:11:PM.4163: MCAgent: MSH ServerID: [hash]
23:11:PM.4173: MCAgent: MSH MeshServer: wss://meshcentral.myserver.com/agent.ashx
23:11:PM.4183: Get list of background agents
23:11:PM.4493: MainForm_Load()
23:11:PM.4973: connectToAgent 
23:11:PM.5053: Agent: ConnectPipe()
23:11:PM.5133: Agent: ConnectPipe() - failed
23:11:PM.3554: Agent: ConnectPipe()
23:11:PM.3554: Agent: ConnectPipe() - failed
23:11:PM.3572: Agent: ConnectPipe()
23:11:PM.3572: Agent: ConnectPipe() - failed
23:11:PM.3561: Agent: ConnectPipe()
23:11:PM.3571: Agent: ConnectPipe() - failed
23:11:PM.3554: Agent: ConnectPipe()
23:11:PM.3554: Agent: ConnectPipe() - failed
23:11:PM.3565: Agent: ConnectPipe()
23:11:PM.3565: Agent: ConnectPipe() - failed
23:11:PM.3649: Agent: ConnectPipe()
23:11:PM.3659: Agent: ConnectPipe() - failed
23:11:PM.3599: Agent: ConnectPipe()
23:11:PM.3599: Agent: ConnectPipe() - failed
23:11:PM.3606: Agent: ConnectPipe()
23:11:PM.3616: Agent: ConnectPipe() - failed
23:11:PM.3598: Agent: ConnectPipe()
23:11:PM.3598: Agent: ConnectPipe() - failed
23:11:PM.3602: Agent: ConnectPipe()
23:11:PM.3602: Agent: ConnectPipe() - failed
23:11:PM.3675: Agent: ConnectPipe()
23:11:PM.3675: Agent: ConnectPipe() - failed
23:11:PM.3565: Agent: ConnectPipe()
23:11:PM.3575: Agent: ConnectPipe() - failed
23:11:PM.3657: Agent: ConnectPipe()
23:11:PM.3657: Agent: ConnectPipe() - failed
23:11:PM.3678: Agent: ConnectPipe()
23:11:PM.3678: Agent: ConnectPipe() - failed
23:11:PM.3620: Agent: ConnectPipe()
23:11:PM.3620: Agent: ConnectPipe() - failed
23:11:PM.7823: Agent: DisconnectPipe()
23:11:PM.7833: MCAgent: Disconnect
```

**Comment by Ylianst** [comment]
Thanks for reporting and providing the log file. It's holiday today in the US, but I will looking into this tomorrow.

**Comment by Ylianst** [comment]
Ok, I did a bunch of updates to MeshCentral Assistant. Fixes will be in MeshCentral v0.8.53 when it's next published. Let me know if it fixes it.

**Comment by kj7ice** [comment]
Thanks for all your work on this. Unfortunately I am still experiencing the same issue after updating my server to the latest version (v0.8.55) and downloading a fresh version of the assistant. Exact same behavior and debug log contents as in my original post. One thing I forgot to mention before is that I've tried running this normally and as administrator--the results are identical.

Any other troubleshooting steps I can try that would be helpful? I'll also include a screenshot of the assistant if that is of any use. The "Request Help" button looks like I should be able to click on it, but nothing happens when I do. I can only move or close the window.

![image](https://user-images.githubusercontent.com/85096517/120596547-bde2df80-c3f8-11eb-91f4-571c9122c2ff.png)

**Comment by kj7ice** [comment]
Version 0.8.56 solved this issue! MeshCentral Assistant is now able to connect with the built-in agent for me. I saw the comments in #2715 and thought I'd update and give it a try. Loving the application mode and white-label/customization too! Thank you!!
