### ISSUE TITLE
agent proxy setting does not work

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#2716]
Hello,

I have a machine with just an IP but no gateway and DNS configured

when I run agentmesh.exe run --WebProxy = "ip-my-proxy: port"

I have the result Could not resolve: mydomainemeshcentral

The proxy works fine with internetexplorer on my domain and teamviewer too

thank you

**Comment by VINISHVV** [comment]
Dear @laboiteajb - i think the command you run showing wrong. it should be like  **meshagent.exe run**
Also check whether you are able to access your meshcentral url from any browsers from this system.

**Comment by laboiteajb** [comment]
I relied on the help from "Meshagent.exe?"
The proxy works from the browser and I access my home page of my Meshcentral

I also tested to remove the "http: //" in the URL of the proxy

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if your issue persists, please reply back
