### ISSUE TITLE
MeshCentral Assistant download does not appear

### ISSUE THREAD

**Issue by SebastianMoyano** [Ylianst/MeshCentral#2720]
Hi everyone, I'm very grateful for this project. It's an excellent tool for IT and has helped me tons! I was just reading the meshcentral blog and it said that I could download the meshcentral assistant the same way we download the meshcentral agent so I updated the server and looked for the feature but didn't find anything.

<img width="530" alt="Screen Shot 2021-06-02 at 09 28 04" src="https://user-images.githubusercontent.com/60912834/120489508-af0f1500-c385-11eb-967a-a45d00c053af.png">

<img width="522" alt="Screen Shot 2021-06-02 at 09 28 24" src="https://user-images.githubusercontent.com/60912834/120489441-a0286280-c385-11eb-8a1d-2eaccef784df.png">

im using Linux Mint 20.1 Ulyssa

thanks in advance!

**Comment by Ylianst** [comment]
The MeshCentral Assistant and Mobile agent links only show up when MeshCentral is in WAN or Hybrid modes. It's likely your server is in LAN mode.

This said, I am going to work today to make MeshCentral Assistant work in LAN mode.

**Comment by SebastianMoyano** [comment]
Yes indeed is it in LAN mode, thank you! And thanks for your work! Amazing project, also sorry for my English, it's not my mother tongue

**Comment by Ylianst** [comment]
Fun fact, the [YouTube video on LAN, WAN and Hybid mode](https://www.youtube.com/watch?v=gx5Fh3pQOns) was just published this morning.

**Comment by SebastianMoyano** [comment]
Yess!  I saw it a few minutes ago, very informative and clear video! I learned a lot of things that I was confused with, thanks!

**Comment by Ylianst** [comment]
Note that just published MeshCentral v0.8.55 now has a MeshCentral Assistant that works on LAN mode, so the option is now shown in "Add Agent" link.

**Comment by SebastianMoyano** [comment]
Thanks!!

<img width="452" alt="Screen Shot 2021-06-03 at 12 27 49" src="https://user-images.githubusercontent.com/60912834/120679578-5152f980-c467-11eb-9972-17fadf5c254d.png">
A few little questions and sorry for going out of topic here. Is there any way to make the Meshcentral assistant persistent after reboot? should use schtask instead? Is it design to be used only when .exe is clicked? 
and one little thing, I think I found maybe a small typo
<img width="335" alt="Screen Shot 2021-06-03 at 12 32 09" src="https://user-images.githubusercontent.com/60912834/120680348-32a13280-c468-11eb-8629-9053a79af067.png">
Sorry for the bad quality

Thanks for your excellent work!
