### ISSUE TITLE
Web-RDP feature question and bug

### ISSUE THREAD

**Issue by Scaff31** [Ylianst/MeshCentral#2721]
Hello,

I'm testing the web-rdp feature, is it possible to use this feature to provide a third party who has no account on the meshcentral server access to a machine?

In my tests with the URL provided by meshcentral the server crashes when a third party who is not identified on the server connects

```
-------- 6/2/2021, 2:08:28 PM ---- 0.8.52 --------

/node_modules/meshcentral/apprelays.js:42
        if (obj.tcpServer) { obj.tcpServer.close(); obj.tcpServer.destroy(); delete obj.tcpServer; }
                                                                  ^

TypeError: obj.tcpServer.destroy is not a function
    at Object.obj.close (/node_modules/meshcentral/apprelays.js:42:67)
    at WebSocket.<anonymous> (/node_modules/meshcentral/apprelays.js:150:104)
    at WebSocket.emit (events.js:203:15)
    at WebSocket.emitClose (/node_modules/express-ws/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/node_modules/express-ws/node_modules/ws/lib/websocket.js:781:15)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:607:12)


-------- 6/2/2021, 2:09:01 PM ---- 0.8.52 --------

{"name":"node-rdpjs","hostname":"meshcentral","pid":1910847,"level":40,"msg":"undefined","time":"2021-06-02T14:09:01.723Z","v":0}
```

EDIT:

Same error if you are disconnected for inactivity, and you restart a connection from the Web-RDP, the server crashes and restarts.

To avoid crashes you have to close the tab and open a new one to generate a new link

**Comment by Ylianst** [comment]
Hi. Web-RDP is not currently available for users that don't have an account. I could look at adding this in the future, but currently quite full with requests.

Thank you for reporting this error, I just fixed it and will be in MeshCentral v0.8.54.

**Comment by Ylianst** [comment]
This fix was published. Let me know if it works and please close this issue if it does. Thanks.

**Comment by Scaff31** [comment]
> 
> 
> Hi. Web-RDP is not currently available for users that don't have an account. I could look at adding this in the future, but currently quite full with requests.
> 
> Thank you for reporting this error, I just fixed it and will be in MeshCentral v0.8.54.

This is the price of success =)

You have created a powerful and indispensable tool for IT departments

**Comment by Scaff31** [comment]
> 
> 
> This fix was published. Let me know if it works and please close this issue if it does. Thanks.

The server does not crash anymore. On the other hand, if you are disconnected for inactivity, and you try to reconnect via the page you opened previously, it does not work, black screen, and you return to the login page web-rdp

**Comment by smartekIT** [comment]
This black screen happen to me too but in my case with sharing a remote control.
