### ISSUE TITLE
Meshcentral goes blank when logging in and does not load

### ISSUE THREAD

**Issue by bierco** [Ylianst/MeshCentral#2722]
Good day,

When accessing the console it asks for a password and normal, but it does not load anything from the console, it remains blank. Could you please help me or is it just me?

**Comment by nzalev** [comment]
> Good day,
> 
> When accessing the console it asks for a password and normal, but it does not load anything from the console, it remains blank. Could you please help me or is it just me?

The behaviour you describe usually happens when an error occurs when trying to load the UI.

Can you please post what version you're running? In addition, can you open the browser dev console (in chrome, this is ctrl+shift+i   -- In firefox, ctrl+shift+j) and post any errors that appear

Example:
![Screenshot from 2021-06-02 11-24-01](https://user-images.githubusercontent.com/63608819/120507753-16809100-c395-11eb-8bb1-c65110744cce.png)


Additionally, you should run meshcentral interactively by navigating to its location in a shell (cmd, powershell, bash, etc) and running `node node_modules/meshcentral/` (replace slash with \ if using windows). You should see it print any errors.

**Comment by Ylianst** [comment]
I just noticed that Spanish language page on MeshCentral does not work. Fixing that now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.53 with a fix for Spanish translation. I also checked other languages and they seem to work.

**Comment by bierco** [comment]
![image](https://user-images.githubusercontent.com/85241835/120523704-d40e8280-c39b-11eb-8b46-f9c7539148d0.png)
 
I get this error that may be at the time of updating.
![msh](https://user-images.githubusercontent.com/85241835/120523793-f56f6e80-c39b-11eb-87a9-60a97674d7bc.PNG)

**Comment by Ylianst** [comment]
@bierco I think you are running the MeshCentral Installer to update? If so, turn off the MeshCentral server service first and try again. Also, you can update from within MeshCentral on the "My Server" page.

![image](https://user-images.githubusercontent.com/1319013/120524584-116b1400-c38c-11eb-846f-1533595454da.png)

**Comment by bierco** [comment]
It appears already updated but now it tells me that the server no longer exists.

**Comment by bierco** [comment]
> @bierco ¿Creo que está ejecutando el instalador MeshCentral para actualizar? Si es así, primero apague el servicio del servidor MeshCentral y vuelva a intentarlo. Además, puede actualizar desde MeshCentral en la página "Mi servidor".
> 
> ![imagen](https://user-images.githubusercontent.com/1319013/120524584-116b1400-c38c-11eb-846f-1533595454da.png)

But it won't let me access the server, not even through the web page.

**Comment by bierco** [comment]
![image](https://user-images.githubusercontent.com/85241835/120524926-32883080-c39d-11eb-80bc-270074ac665e.png)

**Comment by bierco** [comment]
Can you please tell me the name of the service?

**Comment by Ylianst** [comment]
By the way, I generally recommend using the "npm install" command line method for installing MeshCentral. You have much more control over what is going on. There is a [YouTube video on it here](https://www.youtube.com/watch?v=GsQbWZmRRAU).

The service should be "meshcentral.exe" like this image:

![image](https://user-images.githubusercontent.com/1319013/120527665-72e0b200-c38f-11eb-871f-511afaa75930.png)

**Comment by bierco** [comment]
I don't even get the service anymore. If I reinstall it, can I restore all the data I had as it was?

**Comment by bierco** [comment]
![image](https://user-images.githubusercontent.com/85241835/120528885-8a289b00-c3a1-11eb-8bf4-17d3781858e9.png)

I have 36 groups but it does not show me the devices.

![image](https://user-images.githubusercontent.com/85241835/120528967-9f052e80-c3a1-11eb-8964-9d7f93460094.png)

**Comment by Ylianst** [comment]
As long as you keep a backup on the "meshcentral-data" folder, you can put that folder back and restart the server and will see your old data back. If you use MongoDB/MySQL/MariaDB, you need to restore the database too. In your case, your probably using the built-in database, so just restore "meshcentral-data" folder and should be fine. You may have a backup in the "meshcentral-backups" folder.

**Comment by bierco** [comment]
Thank you very much, I was able to restore the server, reinstall it and copy the content. Thank you very much
