### ISSUE TITLE
Assigning Permissions for a single device instead of using groups leads to unexpected results on General Screen

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#2724]
If I assign a device or multiple devices to a user in the Add Device area but I do not assign it any permissions in a Device Group, then the General screen is completely blank. 

This keeps the user from being able to click the links found under the power status bars, like RDP, Web-RDP, VNC and all of that good stuff. 

If I put the user in a group, even not related to the machines that are assigned for singular permission, everything works fine. 

This also does not affect the abilities of the MeshRouter, which run as a standalone application connects just as you would expect. 

I can also connect no matter what on the Desktop tab. It is only the General screen that seems to be making a check it fails. 

The permissions I am assigning the person are the following: Control (No Terminal, No Files, No AMT)

This allows this one person to connect to only their VM while also keeping that VM in a group with all of the other VMs.

Happy to provide screenshots or other details if need be, thank you for all of your hard work!

**Comment by VINISHVV** [comment]
@githubbiswb - please specify your meshcentral version. If you are using older version please upgrade to latest version.

**Comment by githubbiswb** [comment]
Current version is 0.8.38 and will update to verify and close the issue once it has been addressed

**Comment by VINISHVV** [comment]
Please update to latest to version once, incase issue persist please share the screenshot

**Comment by githubbiswb** [comment]
I can understand wanting me to update to the latest, and that makes sense, but I am going to stay on the one I am on for now as this issue actually came over from 
https://www.reddit.com/r/MeshCentral/comments/np2ikx/single_user_single_asset_in_mesh_no_group_has/ 
And in that thread ylianst asked me to place the issue here. Were an update the fix, I assume he would mention that. But I appreciate your diligence @VINISHVV

**Comment by Ylianst** [comment]
Thanks for posting this, v0.8.38 is sufficiently recent. I will try to reproduce this issue.

**Comment by Ylianst** [comment]
When you don't see anything show up, can you open the browser's console and report any errors? That will help a lot.

In FireFox and Chrome, CTRL-SHIFT-J when reload the page and send any errors.

![image](https://user-images.githubusercontent.com/1319013/120864986-00640380-c542-11eb-81f8-b26692e3056f.png)

Thanks!

**Comment by githubbiswb** [comment]
Below is a export of the text of the console of errors
[console-export-2021-6-6_16-15-27.txt](https://github.com/Ylianst/MeshCentral/files/6604874/console-export-2021-6-6_16-15-27.txt)
And also a screen shot of what I am getting after I click into an asset, the My Devices screen is solid. Its when you click on it to the General screen where everything is blank
![4p06vTDy5E](https://user-images.githubusercontent.com/51446227/120938969-810e3580-c6e3-11eb-8908-2badeb8ab759.png)

**Comment by githubbiswb** [comment]
I also can update to 0.8.56 if that is helpful, I run with mesh in a container, and the maintainer just pushed an update, but I will wait to hear if you want me to do that

**Comment by Ylianst** [comment]
The browser console should indicate errors, however the "console-export-2021-6-6_16-15-27.txt" does not contain anything I recognize. If you can open the browser console, navigate to the device the does not show up and screen shot any error, that would be wonderful.

**Comment by githubbiswb** [comment]
I made a video of what I am seeing in the browser console, the export I gave you had my extensions turned off to clean it up, which I didn't do for this video
Let me know if you need more details on those errors that showed up, for the text I expanded all errors I got and told it to export to text which is what I uplaoded

https://user-images.githubusercontent.com/51446227/120940310-9dfa3700-c6ea-11eb-836c-93f240d0af9e.mp4

**Comment by Ylianst** [comment]
Ha. Your using plugin's. I don't test or support plugin's or support servers with plugin's installed.

I just did more testing on my server and can't find any issue. If the problem continues without plugin's... and if your server is public facing, you could create a dummy account with access to a dummy device and [send my the account info](https://www.meshcommander.com/contact-information). I can debug it in the web page and report back.

**Comment by Ylianst** [comment]
Thanks for sending me login information and for making it super easy for me to see the problem. This issue has already been fixed in MeshCentral a while back, just update to the latest version and it should work just fine.

Let me know if that works,
Ylian

**Comment by githubbiswb** [comment]
Updating to 0.8.56 resolved the issue, thank you!

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back.
