### ISSUE TITLE
Restrictions of Meshcentral tools for users not working

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#2726]
Dear Ylian,

In my server I have created few users with No tools (router/meshcmd). But while checking these users can directly login meshcentral router and access the devices.  I am using latest meshcentral version.

**Comment by MailYouLater** [comment]
Please state the actual version number instead of saying "latest", as there will be updates, so the version you're on currently will not always be 'latest'.

**Comment by Mfinadmin** [comment]
@MailYouLater -. I am using V 0.8.55

**Comment by Ylianst** [comment]
Thank you. Version number always helps.

**Comment by VINISHVV** [comment]
Noticed same issues in meshcentral V0.8.55

**Comment by Ylianst** [comment]
Oh. I see now. Currently "No Tools" just removed the links on the user's web page. It does not prevent tools to be used if the user gets them. Just to confirm, your asking that if tools connect to MeshCentral with a user that has the "no tools" set, you want the connection denied?

**Comment by VINISHVV** [comment]
> Oh. I see now. Currently "No Tools" just removed the links on the user's web page. It does not prevent tools to be used if the user gets them. Just to confirm, your asking that if tools connect to MeshCentral with a user that has the "no tools" set, you want the connection denied?

Dear Ylian,
 Is it possible to denied login access of meshcentral router based on user restriction.

**Comment by Mfinadmin** [comment]
Yes. Disable tools login will be better solution.

**Comment by Ylianst** [comment]
Ok, next version of MeshCentral will block tools correctly. If you update MeshCentral Router, you will also get the correct message.

![image](https://user-images.githubusercontent.com/1319013/120854699-5fba1780-c532-11eb-8123-0d9f119beff4.png)

**Comment by Mfinadmin** [comment]
Thanks Ylian,
Its resolved.
