### ISSUE TITLE
File upload on WIN based machines not working

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#273]
**MeshCentral v0.3.5-x (updating to 0.3.6-a at time of writing)**
**Update - Tested with 0.3.6-a -- issue still present**

I tried to upload a 900kb jpg to these machines. Linux based machines seem ok. But Windows seem to have an issue. I have tried uploading to AppData/Desktop/WinDir/etc, and it still has issues.

**Method:**
1. Select Device
2. Select Files, click connect
3. Select destination location
4. Click upload, select file, press ok.
5. Display's the filename (i.e test.jpg) but the progress bar is not moving.
6. Press cancel. It closes upload window.

**Tested on these linux OS's (_no issues with these_):**
- Ubuntu 18.04.2
- Ubuntu 16.04.6
- Raspbian

**Tested on these windows machines (_upload had issues_)**
- Server 2008R2
- 5x Windows 10 machines (different builds/makes/models)

**Comment by krayon007** [comment]
Are these standard installations? Can you check the permissions on the folders you are trying to write to? The only time I had issue with upload, is when I installed the Mesh Agent into my GIT folder, which had the permissions set in such a way, that the agent didn't have write access, so the upload failed...

I tested it just now, on my various windows 10 machines, and upload seems to work ok. I'll see if I can add some instrumentation so that if there is a access error, it'll propagate the error back up, because I don't think it currently propagates back to the web page.

**Comment by theredkoala21** [comment]
> Are these standard installations? Can you check the permissions on the folders you are trying to write to? The only time I had issue with upload, is when I installed the Mesh Agent into my GIT folder, which had the permissions set in such a way, that the agent didn't have write access, so the upload failed...
> 
> I tested it just now, on my various windows 10 machines, and upload seems to work ok. I'll see if I can add some instrumentation so that if there is a access error, it'll propagate the error back up, because I don't think it currently propagates back to the web page.

Yes they are standard installations of windows, and standard installs of meshagent. I have tested the permissions of the folders. (plus the MeshAgent.exe is running as SYSTEM). I tried multiple locations, desktop, appdata, root c:, my docs, pictures, etc - still an issue. I will test on more computers.

**Comment by theredkoala21** [comment]
Just checked Dev console on chrome. Saw this debug msg:

```
Unknown onFileUploadStateChange state 1
Unknown onFileUploadStateChange state 2
(index):5562 
```

**Comment by Ylianst** [comment]
Thanks for the report. I will check this tomorrow.

**Comment by PathfinderNetworks** [comment]
I just tested the file transfer on my system. No issues.  I'm running MeshCentral server on a Server 2019 box.  All of my agents are Windows devices (mostly Windows 10 but a large mix of everything from Win7 to Server 2019 and all in between).  The file transfer is working correctly on the devices I tested.

**Comment by theredkoala21** [comment]
Just updated and tried again. Still an issue.
Im running it on a linux box.

Linux ubuntu-xenial-armhf-1 4.2.8 #2 SMP Thu Aug 30 04:39:53 CST 2018 armv7l armv7l armv7l GNU/Linux

**Comment by Ylianst** [comment]
I cleaned up these lines in the latest MeshCentral:
```
Unknown onFileUploadStateChange state 1
Unknown onFileUploadStateChange state 2
```
They always showed up, even if the transfer was ok. I may need to add more debug information to see what is going on.

**Comment by Ylianst** [comment]
I tried a lot of things and I can't make this problem occur. I tried different browsers and systems, upload always works for me. Can you check if any errors happen in the agent console after the upload attempt? It's the console tab, you need to be administrator on your server.

![z](https://user-images.githubusercontent.com/1319013/59139547-85fb4b80-8948-11e9-94e6-b2d229b18f9c.png)

**Comment by protid** [comment]
I have the same problem

**Comment by theredkoala21** [comment]
**I attempted to upload again just now and recorded what happened:**

- Browse files
- Upload using upload button
- Network Tab: meshrelay.ashx (file browser) - last message: directory listing of current folder
- Network Tab: meshrelay.ashx (new wss, only has three packets)
-- RECV: c
-- SEND: 5
-- SEND: Binary Message (JSON - action upload with size, path, name etc)
-- no other packets sent or recv.

-----

Well that's good news. I was starting to think i was the only one.

> I have the same problem, but i can delete any file that i want

I can also create new folders, delete files/folders and traverse directory's with no issue.

My Mesh server is running on Ubuntu 18. 

------

> I tried a lot of things and I can't make this problem occur. I tried different browsers and systems, upload always works for me. Can you check if any errors happen in the agent console after the upload attempt? It's the console tab, you need to be administrator on your server.
> 
> ![z](https://user-images.githubusercontent.com/1319013/59139547-85fb4b80-8948-11e9-94e6-b2d229b18f9c.png)

Ylianst, could it be a bug when the server is linux? As @PathfinderNetworks said it is working for him and  is running the server on Windows Server. Again, linux agent transfers are working. Only windows agent transfers are not working. 

And there are no errors in the agent console after the upload attempt.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.6-n with a all new MeshAgent, if you can test again that this is still a problem, that would be appreciated.

**Comment by protid** [comment]
I am running mesh on centos 6  os

**Comment by protid** [comment]
after i updated to v0.3.6-n, uploading works fine, but downloading from remote pc still not working

**Comment by theredkoala21** [comment]
after i updated to v0.3.6-n:

- [x] Upload 300kb file
- [x] Upload 2.6mb file
- [x] Download 300kb file
- [x] Download 2.6mb file

Im happy to say that this issue has been fixed! :+1::+1::+1:
But i will keep it open for @protid

**Comment by protid** [comment]
Many thanks, now every think works fine in version v0.3.6-n, @theredkoala21, i think that the issue is finaly fixed !
