### ISSUE TITLE
Add CPU load tracking to Server Stats graphs?

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#2732]
It would be nice to be able to see the server's CPU load tracked over time in the Server Stats graphs.

**Comment by Ylianst** [comment]
I can add that. I will say that if your using MongoDB and you should if using MeshCentral in production, there is a free monitoring tool in MongoDB and is excellent. You enable it and it gives you a URL to see your stats, that includes the CPU. [Details here](https://www.linkedin.com/pulse/mongodb-free-monitoring-community-version-40-explained-jerwin-roy?trk=portfolio_article-card_title).

![image](https://user-images.githubusercontent.com/1319013/120900765-88eaae80-c5eb-11eb-86b1-bab03d7eba8a.png)

**Comment by MailYouLater** [comment]
I was hoping for longer term stats similar to the existing Connections, Memory, Inbound Traffic and Outbound Traffic stats graphs so that I could see how CPU usage is affected at different times by different usage.

Also, I am currently using MongoDB, but it's not running on the same server... so that's really cool, but it won't help me.

**Comment by Ylianst** [comment]
Ok, added CPU to server graph. Will be in MeshCentral v0.8.66.

![image](https://user-images.githubusercontent.com/1319013/122968142-121a1900-d340-11eb-9bc5-46e69a1989d1.png)

**Comment by MailYouLater** [comment]
Thank you so much for adding this.  And for doing it so quickly.  I was just now able to get back to this, and it's really nice having the CPU usage logged along with the other stats.
