### ISSUE TITLE
MeshCentral Assistant doesn't disconnect after support end customer closes application.  v0.8.56

### ISSUE THREAD

**Issue by Bobberty** [Ylianst/MeshCentral#2734]
Mesh Assistant doesn't disconnect after support end customer closes application.
This is using v0.8.56 with TLS offload.
The app prompts to ensure customer wishes to disconnect.  But app stays connected when "OK" is clicked.
The application closes as normal, but the desktop connection persists.

This has been tested with the end customer attempting to close the application directly and the support staff closing the application through the desktop connection.

**Comment by Ylianst** [comment]
Oh dear. Thanks for reporting this. I will fix ASAP, probably tomorrow when back in front of my development computer.

**Comment by Ylianst** [comment]
I just tried it and I can't immediately replicate this. What mode are you running the MeshAgent in? Are you using the multi-in agent or background agent?

![image](https://user-images.githubusercontent.com/1319013/120935217-8acd7400-c6b6-11eb-99ca-ee88758c679b.png)

**Comment by Bobberty** [comment]
Application, Always Connected.  

I'm going to test Connect on User Request.

**Comment by Bobberty** [comment]
....Application.

**Comment by Bobberty** [comment]
I seem to have duplicated it for both Applicataion binaries.

Method for Duplication:
Note:  Support System is the system the support staff would be using.  Target system would be the host for the remote support.

1)  On the target system open the email from the support staff that has the Mesh Assistant URL (App  Mode)
2)  Download/Launch the Mesh Assistant on the target system
3)  Support Staff notices target system is available through the MeshCentral Web Interface.
4)  Support Staff Selects the target system and connects to the Desktop Sharing (May take a few clicks to start sharing)
5)  User notices on the Target system a request to share the desktop and allows the connection.
6)  Service is performed.
7)  Slight Fork here....  7a) is Support Staff     7b) is Target User

7a1)  Support closes the application through the shared desktop.
7a2)  Support Staff selects the Confirm dialog to disconnect
7a3)  All application dialog boxes close
7a4)  Support Staff can still manipulate target desktop without any indication on the target.

7b1)  User closes the application on the target desktop directly
7b2)  User selects the Confirm dialog to disconnect
7b3)  All application dialog boxes close
7b4)  User never knows that the support staff still has direct control of the desktop.

**Comment by Ylianst** [comment]
Thanks. I found it. Releasing a new version in a few minutes.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.8.57 with a new MeshCentral Assistant that fixes this. Let me know if it works.

**Comment by Bobberty** [comment]
Perfect...  Thanks....
I tested the always connected.  Looks good.  Connected on the first click.  And the app died properly.

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back. Please close the issue in the future when it's solve.
