### ISSUE TITLE
Agent for OpenWRT/x86_64

### ISSUE THREAD

**Issue by D4rk4** [Ylianst/MeshCentral#2737]
Please add an agent for OpenWRT x86_64. Or suggest how to install an existing agent.

**Comment by krayon007** [comment]
Once I get a few cycles, this should be easy. I just need to build a new toolchain to do this.

**Comment by D4rk4** [comment]
Any chance to get agent for OpenWRT/x86_64?

**Comment by D4rk4** [comment]
Up

**Comment by krayon007** [comment]
This should already be live. I'll have to double check which server version this went live with.

**Comment by D4rk4** [comment]
I'm don't see options like Linux x86_64 (OpenWRT) in the binary agent list. I'm on 0.9.5.8

**Comment by D4rk4** [comment]
Still not available on 0.9.66

**Comment by krayon007** [comment]
If you look in the agents folder of your server, you should see the `meshagent_openwrt_x86_64` binary.

As far as compiling for it, you should be able compile it like this:

`make linux ARCHID=36`

In the makefile, look for PATH_OPENWRT_X86_64 near the top, and change the location to match where your toolchain is

**Comment by si458** [comment]
the is multiple options to pick from now (2023)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/c520e025-6232-4226-8bdc-b63f42cd6b1f)
