### ISSUE TITLE
Strange german localisation in MeshAssistant

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#2738]
I just noticed strange wording in MeshAssistant on Win10 german. Instead of 'Veranstaltung', Ereignis (plural Ereignisse) would be the correct translation for 'event'. (Veranstaltung is an event with people only).
And 'Ausgang' means 'the exit', better would be 'Beenden'.

![MC-Ass1](https://user-images.githubusercontent.com/83393/120940859-a9b42080-c71f-11eb-98ca-82f877e3f154.png)

**Comment by Ylianst** [comment]
Thanks for the report. I will change:

Veranstaltung  --> Ereignis 
Beenden --> Ausgang

Note that the MeshCentral [translation file is here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/translate/translate.json). Your always welcome to make changes and [mail me the result](https://www.meshcommander.com/contact-information). I will update it in the next version.

**Comment by Ylianst** [comment]
I added a fix for this in GitHub, will be in MeshCentral 0.8.58.

**Comment by baikal** [comment]
Thank you.
I found two more 'Veranstaltungen', changed them to Ereignisse ... .json attached.
What is the meaning of '&' in these Strings? I just left them as is.

```
      "de": "&Ereignisse anzeigen...",
      "en": "Show &Events...",
```
[translate.json.txt](https://github.com/Ylianst/MeshCentral/files/6606714/translate.json.txt)

**Comment by Ylianst** [comment]
Thanks. Just merged the changes in.

**Comment by MailYouLater** [comment]
> What is the meaning of '&' in these Strings?

That defines keyboard accessibility shortcuts for the button/list item that string is displayed on.  i.e. If it said `E&vents` pushing <kbd>V</kbd> (or <kbd>Alt</kbd>+<kbd>V</kbd>) would activate it.  But it says `&Events`, so <kbd>E</kbd> (or <kbd>Alt</kbd>+<kbd>E</kbd>) will activate it.
