### ISSUE TITLE
Input fails with multiple monitors

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#274]
When Multiple Monitors are present and especially with wireless displays the input may be extremely delayed (30+ seconds) or not register at all. Mouse to screen mapping may be offset with physical display mouse several inches below remote support user's mouse position and mouse pointer on remote computer is not visible even over high speed connections. 

Disconnecting monitors may result in only part of screen the screen being visible with no ability to redraw. Selecting a display number in the bottom right does not result in a different screen being selected. Only workable solution currently seems to be to have users remove all but one monitor and reboot before starting support, which isn't always practical.

Example System: Windows 10 Dell Latitude 7390 2-in-1 with Internal, VGA, HDMI and Wireless Display connected via wifi (not docked) over high speed fiber connection but have experienced similar behavior with Optiplex 990 with 2 Monitors via ethernet connection too.

When starting with 4 screens even eliminating several, disconnecting session and reconnecting didn't help.

Let me know if there is additional support information I can capture for you to assist in troubleshooting.

**Comment by krayon007** [comment]
I'm assuming your monitors have different DPI settings? If so, this issue is resolved in the next agent update. The bug is that the DPI setting of the primary display is used when selecting a different display. I have three HiDPI monitors on my Windows 10 machine, and verified it works.

I have not tested Wireless display. I'll have to track down a system with that capability. I know Wireless Display installs a custom video driver, so I'm not sure how that will affect the mechanism we use for KVM.  I will look at it when I get back next week.

**Comment by datapharmer** [comment]
Thanks you may be right - will try to confirm. The wireless display works
on most modern Intel laptops with Intel WiFi and graphics (vpro enabled
laptops on win 10 are a good bet)

**Comment by Ylianst** [comment]
Bryan just released a new MeshAgent and it's in MeshCentral v0.3.6-n. If you update your server and try again, multi-monitor with different DPI should not work correctly.

**Comment by datapharmer** [comment]
Is meshcentral.com on the new version? If so it is still not working (now getting no display for this scenario - see attached).

![image](https://user-images.githubusercontent.com/6548767/60095738-4476e880-971d-11e9-86ae-52008ae9388d.png)

**Comment by hunter-nl** [comment]
Multi monitor for OSX agent does not work. I've two monitors with different DPI. I can not switch to second monitor at all.
