### ISSUE TITLE
MeshCentral sessions : a time tracking solution ?

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#2740]
I've just tried [ActivityWatch](https://activitywatch.net/) to keep trace and make some stats on my remote sessions. Its open source / free. I used Timely before, but it was very difficult to have a "tab" tracking, no filters no customization, only a so-called IA trying to do his/her best...

With AW, an add-on in browser (chrome / Firefox) get traces of all pages/tabs title, so i'ts easy to filter with provided regex to get a fully automatic time tracking solution for Mesh central.

Edit : it tracks only active time in sessions, not the full session time, I like it....

You can also write your own "watcher" to collect more information, if you code... I don't.

It's a work in progress, but it seems to be very efficient :

![ItWorks](https://i.imgur.com/iDfxERD.png)

**Comment by si458** [comment]
this is more of a remote management feature rather than a remote support feature, so it wont be implemented, sorry
try something like [tactialrmm](https://github.com/amidaware/tacticalrmm)
