### ISSUE TITLE
NoTls flags not work

### ISSUE THREAD

**Issue by gouchaoer** [Ylianst/MeshCentral#2742]
Hi, I am deploying a MeshCentral server in local network and don't want to use tls certification.

v0.7.65

my config:
```
"settings": {
    "_cert": "myserver.mydomain.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 80,
    "NoTls": true,
    "_aliasPort": 443,
    "redirPort": 81,
    "_redirAliasPort": 82,
    "MySQL": {
      "host": "10.28.2.131",
      "user": "cd",
      "password": "fToK6B25u",
      "port": 3306,
      "database": "cd"
    }
  },

```

when I access the web front page. It just return empty content.
Could you offer a NoTls configuration example?

thank you!

**Comment by Ylianst** [comment]
The "NoTLS" option was removed a long time ago since it's bad security and during a security review, they wanted me to remove that option. This said, you can install the root cert if you like, there is a link at the bottom of the login page.

**Comment by gouchaoer** [comment]
> The "NoTLS" option was removed a long time ago since it's bad security and during a security review, they wanted me to remove that option. This said, you can install the root cert if you like, there is a link at the bottom of the login page.

thank you for your great work. could you please remove the NoTls content from the pdf document? it's out of date
