### ISSUE TITLE
Korean localization error in MeshAssistant

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2745]
I just noticed Japanese phrase in MeshAssistant on **Win10 Korean**.

![lang](https://user-images.githubusercontent.com/6889244/121176554-4f3dd000-c897-11eb-80b3-0d58d4d6f7f0.png)

**Comment by Ylianst** [comment]
What version of MeshCentral are you using? I think I fixed this in latest version.

**Comment by kuksabong** [comment]
Thanks!!
