### ISSUE TITLE
how to read and change the meshagent.db

### ISSUE THREAD

**Issue by gouchaoer** [Ylianst/MeshCentral#2746]
when the meshagent start, it generate a meshagent.db

how to read and change the file?

**Comment by Ylianst** [comment]
It's a binary format, it sometimes stores the agent certificate and mostly the javascript the agent runs and server URL and server authentication information. You can change the .msh file and re-start the agent is you want to change where the agent connects. .msh is a text file.

**Comment by gouchaoer** [comment]
> It's a binary format, it sometimes stores the agent certificate and mostly the javascript the agent runs and server URL and server authentication information. You can change the .msh file and re-start the agent is you want to change where the agent connects. .msh is a text file.

hi, I am using the "Linux/BST/macOS Binary Installer"， “Linux ARM 64 bit(glibc/2.24 NOKVM)”

so there's no `.msh` file， I think I need to change the meshagent.db directly. 
I try to open it by js script with NeDB but failed.
How can I change the meshagent configuration?

thanks!

**Comment by Ylianst** [comment]
The meshagent.db file is our own binary format, it can't be edited. You can create your own .msh file and restart the agent. The agent will read the values from the .msh. Let me know why you need to edit the .db, maybe we can help.

**Comment by PrplHaz4** [comment]
Per https://github.com/Ylianst/MeshCentral/issues/3095#issuecomment-912092391
> If you pull the code from the agent repo, copy the file modules/dbTool.js into the folder where the agent is installed. Then run the command:
MeshAgent dbTool.js list
This will list all the keys. We can start here to see if the db has a large number of keys.

Available Commands
```
c:\Program Files\Mesh Agent>meshagent dbTool.js
usage:
   [get/getx/delete/export/import] [KEY]
   [put/putx] [KEY] [value]
   [list]
   Commonly used keys are: disableUpdate and noUpdateCoreModule
```

**Comment by krayon007** [comment]
If you use the DB tool method you just need to make sure that you stop the agent service first
