### ISSUE TITLE
Right Click on compter and Details doesn't work

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#2747]
Hi Guys,

Very strange behavior, Right clicking on a device and selecting Details doesn't seem to work all the time. Sometimes gives results, sometimes doesn't, some of the time it gives me the results of the last computer that worked.
Works 100% of the time on Agent clients but not at all on AMT clients
Server in Hybrid mode Version 0.8.57

On the other hand I also have a server in WAN mode, also Version 0.8.57, and it seems to work 100% of the time.

**Comment by Ylianst** [comment]
MeshCentral v0.8.60 is out, let me know if it's fixed and close this issue if it is. Thanks.
