### ISSUE TITLE
Korean is broken when connecting to the terminal on Windows 7 korean.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2752]
I just noticed that korean is broken when connecting to the terminal on Windows 7 pro korean.
When connecting to Windows 10 korean via terminal, Korean was displayed normally.
Both Windows PCs have the same CodePage setting value of 949.

![terminal](https://user-images.githubusercontent.com/6889244/121453696-87026000-c9dc-11eb-9575-45a28b4b1221.JPG)

**Comment by krayon007** [comment]
This is because windows 7 does not support windows pseudo console API. That means there is a lack of UTF8 support with the fake console that I used to implement terminal for older versions of windows that lack a proper pseudo console interface.

**Comment by kuksabong** [comment]
Thanks!
