### ISSUE TITLE
MeshCentral Assistant : No terminal's tab showed

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2754]
Hi,

Is it planned that the terminal's tab is not showed when the Assistant is connected ?

Thanks.

**Comment by Ylianst** [comment]
MeshCentral Assistant does not currently support the terminal tab. That is something I need to add. The code for MeshCentral Assistant (C#) is completely different from Mesh Agent (C/C++).

**Comment by Ylianst** [comment]
MeshCentral v0.8.61 now published with terminal support in MeshCentral Assistant. The terminal tab will only show up for devices running updated versions of Windows 10. Let me know if that works, if it does, please close this issue. Thanks.

![MC2-AssistantTerminal](https://user-images.githubusercontent.com/1319013/121643818-1e040200-ca47-11eb-839c-94015f68416a.png)

**Comment by elpibedeoro** [comment]
Thank you Ylian, just tested and it works !

Just for info : when I tried to manual install v. 0.8.61 had an error about the 'ws' node module.
The solution was to rename the node_module folder and then to retry the installation. It's ok now.

Here is the error : 

`npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /opt/meshcentral/node_modules/ws
npm ERR! dest /opt/meshcentral/node_modules/.ws-mG5khDj9
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/meshcentral/node_modules/ws' -> '/opt/meshcentral/node_modules/.ws-mG5khDj9'
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-11T07_05_58_821Z-debug.log`


This is the log : 
`0 verbose cli [ '/usr/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'meshcentral' ]
1 info using npm@7.16.0
2 info using node@v10.24.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/opt/meshcentral/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 15ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
29 timing idealTree:init Completed in 96ms
30 timing idealTree:userRequests Completed in 2ms
31 silly idealTree buildDeps
32 silly fetch manifest meshcentral@^0.8.60
33 http fetch GET 200 https://registry.npmjs.org/meshcentral 126ms (cache hit)
34 silly placeDep ROOT meshcentral@0.8.61 Symbol(REPLACE) for:  want: ^0.8.60
35 timing idealTree:#root Completed in 155ms
36 timing idealTree:node_modules/meshcentral Completed in 1ms
37 timing idealTree:buildDeps Completed in 156ms
38 timing idealTree:fixDepFlags Completed in 2ms
39 timing idealTree Completed in 261ms
40 timing reify:loadTrees Completed in 262ms
41 timing reify:diffTrees Completed in 5ms
42 silly reify mark retired [ '/opt/meshcentral/node_modules/meshcentral',
42 silly reify   '/opt/meshcentral/node_modules/.bin/meshcentral' ]
43 silly reify mark retired [ '/opt/meshcentral/node_modules/ws' ]
44 silly reify moves { '/opt/meshcentral/node_modules/meshcentral': '/opt/meshcentral/node_modules/.meshcentral-giqs0rxf',
44 silly reify   '/opt/meshcentral/node_modules/.bin/meshcentral': '/opt/meshcentral/node_modules/.bin/.meshcentral-0XecywbG',
44 silly reify   '/opt/meshcentral/node_modules/ws': '/opt/meshcentral/node_modules/.ws-mG5khDj9' }
45 timing reify:rollback:retireShallow Completed in 5ms
46 timing command:install Completed in 298ms
47 verbose stack Error: ENOTEMPTY: directory not empty, rename '/opt/meshcentral/node_modules/ws' -> '/opt/meshcentral/node_modules/.ws-mG5khDj9'
48 verbose cwd /opt/meshcentral
49 verbose Linux 4.19.0-16-amd64
50 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "meshcentral"
51 verbose node v10.24.0
52 verbose npm  v7.16.0
53 error code ENOTEMPTY
54 error syscall rename
55 error path /opt/meshcentral/node_modules/ws
56 error dest /opt/meshcentral/node_modules/.ws-mG5khDj9
57 error errno -39
58 error ENOTEMPTY: directory not empty, rename '/opt/meshcentral/node_modules/ws' -> '/opt/meshcentral/node_modules/.ws-mG5khDj9'
59 verbose exit -39`
