### ISSUE TITLE
MeshCentral Assistant : a few questions

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2755]
Hi,

Just testing the new Assistant and I have a few questions about it.

1. When a help user request without a message, any notification is showed on MC nor the star icon to identify the client that needs support. Is it normal ?
2. Is it possible to have a notification or a sort of list about help user request when a MC administrator is not logged in ? I've just noticed that if I'm not logged in MC, the notification doesn't appear.  However, I can fin these kind of notifications in the My Events tab
3. Is it possible to create a filter by help user request in computer's list ? Just like those one that exist like "connected, tags, all..."
4. I've noticed that when you left click on the systemtray icon, the Agent Select is showed. What's the difference about "Direct connection" and "MeshAgent" ?
5. Is there a way to install the Assistant, maybe through the agent if it is present ? When computer reboot, the Assistant application or systemtray are not loaded. Did I miss anything about that maybe ?

Thank you.

**Comment by elpibedeoro** [comment]
Hi Ylian,

1.  I mean that when help is requested, you can add a message. If you leave it blank, without a message, any notification and help icon appear.
2. Thanks
3. Sorry, I didn't notice it.
4. Ok I understand thank you. 
5. Thanks

**Comment by Ylianst** [comment]
I will close this question. If you want to make requests, please open a different issue for each request. Thanks.
