### ISSUE TITLE
Change Performance Graphs in Details tab to right side

### ISSUE THREAD

**Issue by SystemAssure** [Ylianst/MeshCentral#2756]
The performance graphs in the details tab seem to work the 'wrong way round' as you show the newest data on the left. Conventionally performance graphs show the newest data on the right.
![image](https://user-images.githubusercontent.com/81509807/121509356-781cad00-c9de-11eb-9c48-8586d974e38a.png)

![image](https://user-images.githubusercontent.com/81509807/121509422-88cd2300-c9de-11eb-952e-e79533604382.png)

Is this something that can be changed, or have as a configuration setting? Its not a major issue, just a minor annoyance.

**Comment by Ylianst** [comment]
Fixed, will be in MeshCentral v0.8.61.

![image](https://user-images.githubusercontent.com/1319013/121593429-ca66c980-c9f0-11eb-9162-00f02df61da9.png)

Once published. Check if it works and close this issue if it does.

**Comment by SystemAssure** [comment]
Superb

Thanks very much for the amazing response. I will test as soon as it is released.

Regards

On 10 Jun 2021 21:37, Ylian Saint-Hilaire ***@***.***> wrote:

Fixed, will be in MeshCentral v0.8.61.

[image]<https://user-images.githubusercontent.com/1319013/121593429-ca66c980-c9f0-11eb-9162-00f02df61da9.png>

Once published. Check if it works and close this issue if it does.

**Comment by Ylianst** [comment]
MeshCentral v0.8.61 now published.

**Comment by SystemAssure** [comment]
Perfect - thanks very much
