### ISSUE TITLE
[Feature] Speed action / Fav commands to send

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#2757]
Hi,

It's been a long time since my last issue ^^
I've searched for my use case in resolved issues but didn't get result so her it is :

We have some commands or group of commands that we used regulary on user agent. For now we use 'action' menu with 'execute command' ans we copy/past commands from our knowledge base.

What would be awesome is that be able to save some commands or group of commands as speed action and get them directly from a sub 'action' menu

--> Select multiple agent --> 'Group Action' --> 'Speed task (?)' --> Get a list of previously saved commands --> Select one --> Execute

What do you think of that ?

**Comment by Ylianst** [comment]
Good request. I had someone tell me a while back that other management tools have a "tools kit" like this with know commands you can quickly run on a remote machines. I think this is a good idea. I do want to add that I am completely swamped with requests.

**Comment by AntonAndreevichMoroz** [comment]
You can use the plugin https://github.com/ryanblenis/MeshCentral-ScriptTask

**Comment by Tomatoschewps** [comment]
Ok, awesome !
It's been so long since I check MeshCentral options, I didn't know plugins exists ^^

Good for me, I'm closing it
