### ISSUE TITLE
Korean issue in Assistant's Help Request window

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2758]
If a user input  the request in Korean in the Help Request window of the Assistant and then send a message, a notification message is displayed in unrecognizable characters on MC as shown in the picture below.

![그림1](https://user-images.githubusercontent.com/6889244/121534010-ca3feb80-ca3b-11eb-8ae2-a85690e9f7b2.png)

**Comment by Ylianst** [comment]
Good request!! I will work on this.

**Comment by Ylianst** [comment]
Thank you for reporting this. I fixed MeshCentral Assistant, will be in MeshCentral v0.8.61.

![image](https://user-images.githubusercontent.com/1319013/121586930-19106580-c9e9-11eb-840d-d8746adca087.png)

**Comment by Ylianst** [comment]
MeshCentral v0.8.61 now published.

**Comment by kuksabong** [comment]
Thanks for your efforts!
