### ISSUE TITLE
Add Windows Security Center data in device details export

### ISSUE THREAD

**Issue by Tomatoschewps** [Ylianst/MeshCentral#2760]
Hello,

Is it possible to add the result of 'windows security' and 'antivirus' in CSV export ?
And as column in 'My devices' ?

Best regards
D.

**Comment by Ylianst** [comment]
Good request, but please in the future, write a correct title and describes the request.

**Comment by Ylianst** [comment]
Good idea. Just added it. Will be in MeshCentral v0.8.61. Once you check that it works, please close this issue. Thanks.

![image](https://user-images.githubusercontent.com/1319013/121595709-642f7600-c9f3-11eb-82fb-370111270eae.png)

**Comment by Tomatoschewps** [comment]
Ok, my bad, I'll do better next time.

I wasalso thinking of adding the AV name also :
![image](https://user-images.githubusercontent.com/10291238/121598451-1e4dce80-ca42-11eb-84de-de804f90cef3.png)

And what do you think to add these informations in 'my Devices' view as colums ?

**Comment by Ylianst** [comment]
Ok, next version will have AV details.

![image](https://user-images.githubusercontent.com/1319013/121736332-45d98100-caac-11eb-8900-9b1d5dc2acd9.png)
