### ISSUE TITLE
Android App wihout camera

### ISSUE THREAD

**Issue by pepelemoko37** [Ylianst/MeshCentral#2765]
Hi,

For a digital art apenning I want use [Android Box](https://www.amazon.fr/H96-Android-RK3328-Bluetooth-Control/dp/B07Y9ZF3BQ/ref=sr_1_32?dchild=1&keywords=TV+Box+H96+MAX&qid=1623438116&sr=8-32) with my MeshCentral server, the remote is not usable beause the projector are very high on a building. I have network so I want use your app but I need to take a picture when it's install. Do you have another solution for enter information ?

Thank for your great job and have a nice week end.

guillaume

**Comment by Ylianst** [comment]
There is an alternative. On the web site, right click the QR code and copy the link.

![image](https://user-images.githubusercontent.com/1319013/121742129-48d86f80-cab4-11eb-954c-5ad3789bfa10.png)

The link should start by "mc://". Then, paste that in the Android application. The MeshCentral Android agent should detect the device has no camera and offer to input the link manually. You can also go in the top right menu and select to enter the link.

Let me know if that works.

**Comment by MailYouLater** [comment]
You can also just click it, to open the link.  The MeshCentral Android Agent registers the intent necessary to be able to open `mc://` URLs.  It works for me.

**Comment by Ylianst** [comment]
@MailYouLater You are absolutely right. I forgot I did that.

**Comment by pepelemoko37** [comment]
Ok thank you for your very quick answer.

I try this at first hour on monday and I keep you posted.

Have a nice week end

Guillaume

**Comment by pepelemoko37** [comment]
![IMG_20210614_113222](https://user-images.githubusercontent.com/67332893/121916153-2d7b9780-cd34-11eb-9888-ac68622a65c5.jpg)
Hi,

It's working with my Android Box but with them on site I have a problem with the playstore. I try tomorrow directly with the APK or via another app manger.

Thank for your help.

Guillaume

**Comment by Ylianst** [comment]
Android v6 is required.

**Comment by MailYouLater** [comment]
I get the same message on Android TV 9.  I think what's going on is that the Google Play listing isn't marked as being compatible with Android TV based devices.

**Comment by pepelemoko37** [comment]
I have android 9 to. Itry direcltly with the APK or other store. I keep you in touch.

**Comment by Ylianst** [comment]
I will close this issue since the original question was answered. If you can open a new issue about Android TV with details, that would be great.

**Comment by pepelemoko37** [comment]
Yes thank you.

Unfortunately it will not be necessary because it does not work, neither with the APK, neither with another store like Aurora.

Thank again for your answer and for your great great work !

Guillaume

**Comment by MailYouLater** [comment]
> Unfortunately it will not be necessary because it does not work, neither with the APK, neither with another store like Aurora.

... What "does not work"? ...

Ignoring the issue that Google Play says it's incompatible and the fact that Aurora doesn't help with that, I had no other problems loading the APK onto my Android TV 9 device, and while I'd say that the Android app still needs work, everything that works on my phone also works on my Android TV device.

**Comment by MailYouLater** [comment]
@pepelemoko37?
