### ISSUE TITLE
Click a row in process list to show more info/options/actions

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#2767]
On the Desktop tab, the sidebar that opens when you click Tools has two tabs, Processes and Services.  Clicking a row in the Services list shows a little more info about that particular service, and offers the ability to Start, Stop or Restart it.

This request is to ask you to add a similar ability to click a row in the Processes list to get more information about that particular process (executable location, command line used to launch it, process ID, associated service if applicable), and if possible the ability to do actions like kill the process/tree, suspend/resume the process, or change the process's priority.

**Comment by Ylianst** [comment]
When clicking on a process, I added a details dialog with plenty of data on the process. Right now, it only works with latest MeshCentral Assistant until it's also added to the MeshAgent.

![image](https://user-images.githubusercontent.com/1319013/121949939-eaa6c900-cd0d-11eb-9192-ada2274b9769.png)

**Comment by MailYouLater** [comment]
Cool.  Does it give you the option to kill, change the priority of, and/or do any other actions to the process?

I'd like to be able to do things like clicking a `rundll32.exe` process, use the `Command Line` to see what DLL it's running, and be able to kill it or bump up/down the priority in that window.

Looking forward to seeing this in the agent.

**Comment by Ylianst** [comment]
You can kill the process using the little trashcan next to the process in the list. There is no change in priority feature, but may add that in later.

**Comment by MailYouLater** [comment]
Yes, I'm aware that you can kill the process via the icon in the same row as the process name on the list, but once you've clicked the process name to open the dialog, it would be convenient to be able to set the priority and/or kill the process with a button/dropdown that's inside the dialog, perhaps along side the OK button.  This way you can be certain that you're killing/adjusting the same process that you're looking at, which can be a problem when you have several `rundll32.exe` processes running at the same time.

**Comment by MailYouLater** [comment]
So... I was finally able to get back to this and... I've updated to the latest version (0.8.75), and clicking on a row in the process list gives me no useful information or options at all... when I click on the row of a process, all I get is a "Process Details, #\<PID\>" dialog that very briefly says "Requesting details..." then changes to "No information provided".
![Process Details, #876 - Requesting details... - [OK]](https://user-images.githubusercontent.com/1279475/125135923-ab765880-e0be-11eb-80f8-f52e2d02883d.png)
![Process Details, #876 - No information provided - [OK]](https://user-images.githubusercontent.com/1279475/125135980-c1841900-e0be-11eb-9184-46e71e476f90.png)

**Comment by si458** [comment]
PR in the works for you to fix this!
the code was there in the agent, we just needed to add it to the frontend
