### ISSUE TITLE
MeshAgent doesn't update info in UI after manual changing .msh file.

### ISSUE THREAD

**Issue by tersion** [Ylianst/MeshCentral#2768]
After downloading _MeshAgent-%GROUP_NAME%.exe_ from the web-panel of MeshCentral (in this scenario, .exe file has embedded .msh file), and after first start, it creates _MeshAgent-%GROUP_NAME%.msh_ file. If I manually change for example 'MeshServer' key, restart .exe file, I still see old URL to Mesh server. BUT in registry this 'MeshServerUrl' key would be updated.
If using _MeshAgent.exe_ without emdedded .msh file, than all works fine - changes in .msh file reflected in UI.

**Comment by si458** [comment]
im not sure what ur trying to achieve here?
you shouldnt really be changing the msh file as its self built/self updating
also you might need to restart the meshagent service too
closing as old and stale
