### ISSUE TITLE
Chat function doesn't work.

### ISSUE THREAD

**Issue by tersion** [Ylianst/MeshCentral#2769]
I have setup local (LAN only) MeshCentral server for test purposes. I have one server PC (Debian 10, where is MeshCentral deployed) and two workstation PC's with Windows 7 SP1 (one is fully updated, another is just vanilla SP1). I can successfully connected on both PC's to each other, control the desktop, etc., but when I start Chat, on web side continuously: 'Waiting for other user...', on remote side - nothing. It's seams like [#440](https://github.com/Ylianst/MeshCentral/issues/440) issue still there. But this PC's doesn't login in any domain. Just on it's own, even with different user names.
Trying to run MeshAgent with\without admin. privileges, and as a service also. Always the same result - chat doesn't start on a remote side.

**Comment by krayon007** [comment]
From the console tab of the remote machine, does the following command do anything:
`openurl http://www.google.com`

**Comment by tersion** [comment]
**krayon007**, yes, it's perfectly works on both sides:
```
> openurl http://www.google.com
Success.
```
For a second I see cmd window with something in a title like: "taskgen.exe" and than successfully opens new tab with Google page in a default Chrome browser.

**Comment by tersion** [comment]
**krayon007**, I've checked chat function on Windows 10 (2004) - it's correctly works. This PC doesn't connect to any domain\AD. And also checked on Windows Server 2008 R2 with all updates - chat not working. As I understand from previous issues related to this problem, MeshAgent uses Windows task scheduler to spawn browser webpage. I try manual run next commands in cmd.exe:
```
SCHTASKS /CREATE /F /TN TempTask /SC ONCE /ST 00:00 /RU USERNAME /TR "C:\windows\system32\cmd.exe /C START http://www.google.com"

SCHTASKS /RUN /TN TempTask

SCHTASKS /DELETE /F /TN TempTask
```
All works fine on Windows 7 SP1 or Windows Server 2008 R2, task is correctly scheduled and executed from cmd. Can I make any other debug things to investigate why and where exactly problem is occure?

**Comment by dinger1986** [comment]
chat has greatly improved since then @si458 I dont have issues with it when we use it anymore

**Comment by si458** [comment]
closing as stale plus i believe this is fixed now anyways
