### ISSUE TITLE
IPv6 address not visible in network interfaces popup info

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#277]
![image](https://user-images.githubusercontent.com/5203309/59086554-60e3ea00-8902-11e9-9e1c-adec3ce42b08.png)
Only the first part left to the : is shown as an IPv6 address.

**Comment by Ylianst** [comment]
Thanks for the report. Fixed in MeshCentral v0.3.6-f when I publish it.

**Comment by hunter-nl** [comment]
Yes, this has been fixed. It would be nice if in the lower part of the popup window also shows IPv6 addresses information with the visible IPv4. On some systems I have only IPv4 or only IPv6 and most for them dual stack. But I guess, the agents needs to provide this information.

**Comment by hunter-nl** [comment]
Solved
