### ISSUE TITLE
MeshRouter 1.3.7704 not routing specified IP in the MeshCentral config.json

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2770]
I recently upgraded MeshRouter to 1.3.7704 and found that all of my link configs in the config.json no longer routed to the specified IP address. Instead all of them default to "localhost" and route the port to the localhost. MeshRouter Version 1.6.7755 works perfectly however. That was the version I upgraded from. MeshCentral Server version is v8.60.

**Comment by Ylianst** [comment]
Humm... You "upgraded" from 1.6.7755 to 1.3.7704? The older version of MeshCentral Router does not support links thru a device to a remote IP address. Maybe your saying that the new MeshCentral has an older Router?

**Comment by LPJon** [comment]
Ya know.....why didn't I catch that? Ok so that means that the version of MeshCentralRouter for download on your downloads page at https://meshcentral.com/info/downloads.html is 1.3.7704 and I just confirmed that. Is it recommended to always download MeshCentralRouter directly from the MeshCentral Server instance?

**Comment by Ylianst** [comment]
Ha. I just updated that link. Yes, I often assume people are using the MeshCentral Router that is part of the MeshCentral NPM package... but I should keep the site updated.
