### ISSUE TITLE
Check agent status

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshCentral#2771]
Hi,

I am using meshcentral for our web application.
I use the meshcentral MeshCtrl ListDevices, while I found out if my agent is offline the ListDevices still return online.
May I know how long will it take to reflect an offline status if an agent is offline?

**Comment by Ylianst** [comment]
When running `nodejs meshctrl.js listdevices" you get something like this:

![image](https://user-images.githubusercontent.com/1319013/121952153-b97bc800-cd10-11eb-84da-0e6abe9a87f4.png)

The 3 last numbers are the device icon, the device connection state and the device power state.

The second value, the connection state is the sum of a set of flags:

```
1 = Agent Connected
2 = Intel AMT detected
4 = Intel AMT CIRA connected
16 = MQTT connected
```

In your case, as long as the connection number is odd (has 1 as part of the sum) then the agent is connected.

Hope that helps,
Ylian

**Comment by yuling3086** [comment]
Hi,

Actually when my agent go offline like network connection suddenly disabled.
I try to run ListDevice in my another PC,it still showing as 1 means connection is connected.


Below is what I get :

"x26hdp7jZiCERde5f4Kzo25ASl7IACswnC2uZQJlWfSLJd293xlozo4@4WimSlMI", "5CD03326HV", 2, 1, 1 

Thanks

**Comment by MailYouLater** [comment]
I also started noticing recently that when the agent gets disconnected, the server doesn't seem to notice that it's gone.

Do you have an `agentPing` or `agentPong` line in your server's `config.json` file?  If so, what is it set to?

**Comment by yuling3086** [comment]
I do set the agentPong in my config.json file as 10.
![image](https://user-images.githubusercontent.com/38518937/121974905-07e1a300-cdb3-11eb-860a-754e4920baed.png)

**Comment by MailYouLater** [comment]
> Do this related with the agentPing or agentPong?

I don't know, but I have `agentPing` set, and I would have thought that having `agentPing` or `agentPong` set would help alleviate an issue like this if one existed, since it should keep the server and the agent communicating.  However since both of us who are noticing this issue have `agentPing` or `agentPong` set, it might be a bug in the way the server handles the `agentPing`/`agentPong` feature.

**Comment by yuling3086** [comment]
I do found out even I go to the interface I also still see the agent is showing online.

![image](https://user-images.githubusercontent.com/38518937/121979354-9575c080-cdbc-11eb-9ffd-f7cc30078ea5.png)

**Comment by Ylianst** [comment]
Note that the server will disconnect an agent that has not sent traffic after "AgentIdleTimeout" seconds. The default is 150 seconds. I noticed above, you set this value to 10 seconds, that is going to cause issues. You what that value to be at least a bit larger than the ping time.

**Comment by MailYouLater** [comment]
I have not set `AgentIdleTimeout` in my `config.json`.

**Comment by Ylianst** [comment]
So, I ran a test where I connect an agent, unplug the agent computer from the network and time how long it takes for the server to show the agent as disconnected. In my case, it switched to disconnected around the 2 minute mark. This should be about right, at most it should be 2:30 with default value.

If you run the experiment and it does not show the agent going away, there is certainly a problem. Open a issue and indicate that version of NodeJS your using, config.json and that you conducted the experiment and the agent is still showing as connected after 2 minutes and 30 seconds.
