### ISSUE TITLE
I can't copy file to multiple computers with overwrite option

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2772]
Hello,

I have encountered a small error when uploading files to multiple computers at the same time. Or maybe I'm doing something wrong.

I select multiple computers / Group Action / Upload files. 
I select the file and mark the option to overwrite. 
If the file already exists in the destination and I want to overwrite it (by checking the overwrite option), it is not copied. On the other hand, if the file does not exist, it is perfectly copied to all computers.

If I upload a file that already exists in the destination from the "Files" tab on a computer, it asks me to overwrite and if I accept it copies it well.

It only happens with the upload to multiple computers, either marking a single team or several.

The target computers all have Windows 10.

I have tested with 2 servers, one running with version 0.8.48 and the other with the latest version 0.8.62, the same thing happens in both.

Thank you very much for your help.

Greetings.

**Comment by Ylianst** [comment]
Ok, I just did a fix for this, but found another problem. If you upload the same file twice in a row, it fails the second time. Bryan will be looking into that.

**Comment by Ylianst** [comment]
MeshCentral v0.8.63 was published with a fix for this. Let me know if it works.

**Comment by lergolas** [comment]
It works perfectly.

Thank you very much for fixing it!
