### ISSUE TITLE
Adding timestamp for the command "agentissues"

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2774]
Hi,

Is it possible to add the complete timestamp (date+hour) for the command "agentissues" ? Actually it does show only the hour.
Thank you.

**Comment by Ylianst** [comment]
Changed it, will be in MeshCentral v0.8.64.

**Comment by Ylianst** [comment]
MeshCentral v0.8.64 was just published.

**Comment by elpibedeoro** [comment]
Great, it works !
Thanks you Ylian !
