### ISSUE TITLE
Multi Domain Support for mobile app

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2775]
Dear Ylian,

Is it possible to enable muti domain agent support for meshcentral mobile app.

**Comment by Ylianst** [comment]
I am not sure I understand the request. You can create many domains and users can connect to one domain.

**Comment by VINISHVV** [comment]
@Ylianst - Yes we can create many domains and users can connect to one domain.

Like mesh agent is there any option for connecting same mobile to different server at a time ?

**Comment by Ylianst** [comment]
I don't understand the question.

**Comment by asasin114** [comment]
@VINISHVV are you wanting to have multiple agents running on a single Android device? That currently isn't possible and would probably require a complete overhaul of the app for such support.

**Comment by yomono** [comment]
If you think about it, you can not do this on desktop either. You have to install two separate agents for accomplish this.
You could give https://appcloner.app/ a try. I actually use it for some apps and it works well. Of course you would be on your own, but if you really need it it could worth to try

**Comment by VINISHVV** [comment]
@yomono - Thanks appcloner / parallel space resolve my issues.
