### ISSUE TITLE
Share Link Expiration Issues (Re-open #2687)

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2777]
I posted this in #2687 but just confirmed that the normal desktop connectivity issue seems to be unrelated as I am able to connect via the desktop tab while logged in just fine today. I'll leave the original in its entirety for reference anyway though.

>Just tried creating a year-long link and am running into this issue now. I'm having other problems connecting to this machine which may or may not be related but I'm seeing the original error message in my own server logs. Currently running 0.8.62 and what's interesting is that the file manager connects and works just fine, the expiration date is shown correctly, but trying to connect to the desktop gets to the setup phase and then disconnects, throwing the TimeoutOverflowWarning in the process.

>I was able to connect once via the normal desktop feature though that's not working now either (with the same setup/disconnect behavior though no error) so there's a possibility that whatever is going on there may be the cause of what I'm seeing and not this particular bug.```

_Originally posted by @PetieM in https://github.com/Ylianst/MeshCentral/issues/2687#issuecomment-860353073_

I'm currently running v0.8.63 and getting the same error message (`(node:883303) TimeoutOverflowWarning: 31393736597 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.`) as was originally reported. Please let me know if you need anything else from me.

**Comment by Ylianst** [comment]
Can you provide step-by-step guide to make this issue happen? I have no idea what you are doing.

**Comment by PetieM** [comment]
It's exactly the same process as in the original report: https://github.com/Ylianst/MeshCentral/issues/2687#issue-901169217

1. Create a share link with a long expiration (in this case, a date range spanning 1 year).
2. Open the share link and click on Connect on the desktop tab.
3. "Connecting..." appears and then immediately disconnects. The specified TimeoutOverflowWarning error is logged.

This is only happening on the desktop tab though. I created a share link that included file and terminal access and they both work as expected and no error is logged.

**Comment by Ylianst** [comment]
Yes, sorry about that. I was able to make the error happen and changed my post to save you some work. I got the fix done now, will be in the next MeshCentral v0.8.64.

**Comment by PetieM** [comment]
No worries - thank you for the super-fast fix!

**Comment by Ylianst** [comment]
Thanks. I wish I could stop time and do that for all of the issues... doing my best.

**Comment by PetieM** [comment]
I wish I had enough knowledge about how this all works to actually help. Your best is already far more than I, and I imagine many others, could have possibly expected, especially on a product you're developing an offering for free. You have my sincere thanks for the incredible amount of time you dedicate to this project. Will test this fix after the update goes live and close this once I confirm it's working.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.64, let me know if it works :)

**Comment by PetieM** [comment]
Looks like that did it! Thanks again!

**Comment by PetieM** [comment]
Sorry, ignore that last comment. Refreshing seems to have fixed it so all is well!
