### ISSUE TITLE
Need to recover Intel AMT password in MeshCommander

### ISSUE THREAD

**Issue by bwanaaa** [Ylianst/MeshCentral#2778]
I have been using mesh commander to administer several intel machines with AMT for a while. Unfortunately, I didnt write down the password when I initially configured AMT for a certain machine. Although I can still activate it from mesh commander on the machine I normally use, I want to install mesh commander to another machine. To configure the connection tho I need to remember the password I specified for the target AMT machine. And my memory has failed me. Although the mesh commander settings page still has the password, it is all asterisks. Where does mesh commander save this data?

**Comment by Ylianst** [comment]
In MeshCommander, go in the file menu and select "Save Computers..." and save the computer list to a file. You will see the password in that file. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/122166274-394b8480-ce2e-11eb-8891-5e980e265ba6.png)

**Comment by bwanaaa** [comment]
Works. Thank you

**Comment by Ylianst** [comment]
In the future, please close the issue.
