### ISSUE TITLE
Mesh agent connection status not updated

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshCentral#2779]
I had try unplug the agent computer from the network at 8.56am until 9.01am the agent is still online.
I am using node.js version v15.1.0.
I had try to change the agentPing and agentPong to 1 but it still same.

Below is my config.json file.
```
{
  "settings": {
    "mongodb": "mongodb://",
    "mongodbcol": "remoteagents",
    "mongoDbName": "edulab",
    "sessionTime": 240,
    "port": 31443,
    "redirPort": 31080,
    "allowLoginToken": true,
    "allowFraming": true,
    "cookieEncoding": "hex",
    "cookieIpCheck": false,
    "browserPong": 30,
    "agentPong": 15,
    "agentPing":15,
    "wscompression": false,
    "agentwscompression": false,
    "desktopMultiplex": true
  },
  "domains": {
    "httpHeaders": {
      "Strict-Transport-Security": "max-age=360000",
      "x-frame-options": "SAMEORIGIN",
      "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
    }
  }
}
```

**Comment by Ylianst** [comment]
I tested with these settings on my development server and after 2:30 seconds the agent did disconnect.

I don't understand why you are using ping/pong commands with such low values. Ping/pong is used when the browser or agent are disconnecting unexpectedly. So, you need to add traffic to keep them connected. I would remove all ping/pong and only add them if you need them.

You have the opposite problem, the agents are not disconnecting. For testing, try:

```
"AgentIdleTimeout": 10
```

This should disconnect the agent after 10 seconds of idle traffic. It's just a test, but agent should not be able to stay connected. If that works, you can set that time as needed.

**Comment by yuling3086** [comment]
Hi,

May I know which version of meshcentral you are using?
I am using meshcentral 0.6.97.

**Comment by yuling3086** [comment]
Hi,

Anyone facing the same issue where need agent pong to keep the connection alive which not lead to disconnect after 30 mins and still need to detect if the agent go offline?

How is your configuration for this?

Thanks
