### ISSUE TITLE
Link to image user-256 is wrong

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#278]
On the user details webpage the user icon is "missing"
![image](https://user-images.githubusercontent.com/5203309/59090325-c2a95180-890c-11e9-9fc9-d95889d7e71c.png)
It is pointing to the jpg version. But the image is stored as PNG.

**Comment by Ylianst** [comment]
Thanks for reporting. Indeed for browsers that don't do webp, the link would be broken. Fixed in MeshCentral v0.3.6-f when I publish it.

**Comment by hunter-nl** [comment]
Yes, Fixed! Thanks!
