### ISSUE TITLE
404 page error when clicking "Open Web Site" tab in MeshCentral Router

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2783]
Hi.
When I launch MeshCentral Router after logging into MC, I get a 404 page error when I click the "Open Web Site" tab in the MeshCentral Router.

![그림1](https://user-images.githubusercontent.com/6889244/122172545-d1dc1600-cebb-11eb-8d5d-6af5a8a926ba.png)

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
What version of MeshCentral Router are you using?

![image](https://user-images.githubusercontent.com/1319013/122268511-01295d80-ce91-11eb-9584-534cd511bce6.png)

**Comment by Ylianst** [comment]
Fixed it. Will be in next version of MeshCentral v0.8.65 or you can download the latest [MeshCentral Router here](https://meshcentral.com/info/tools/MeshCentralRouter.exe).

**Comment by kuksabong** [comment]
Thanks for your help.
