### ISSUE TITLE
MeshCentralInstaller-2.9 Download error

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#2784]
I want to install fresh MeshCentral to Windows 2019 Server. After i run MeshCentralInstaller-2.9, i set WAN mode, set my domain, and click next. Imediatly i get this screen below. Internet is working and i have downloaded installer from this machine. How to debug?
![Capture](https://user-images.githubusercontent.com/17468203/122176858-58c1cc00-ce85-11eb-8c16-caf18a60c2b5.JPG)

**Comment by VINISHVV** [comment]
An alternate method will be given below.

1) install NodeJS. 
2) create an empty folder in any drive ( eg. c:\Meshcentral)
3) Open powershell and chenge directory to the empty folder ( cd c:\Meshcentral) 
4) run the command "**npm install meshcentral**"
5)run **"node node_modules/meshcentral"**

That's it.

**Comment by alesribic73** [comment]
Hi

Installation went smoothly. But service is not installed. Can you please assist on this also?

Thanks a lot!

**Comment by VINISHVV** [comment]
> Hi
> 
> Installation went smoothly. But service is not installed. Can you please assist on this also?
> 
> Thanks a lot!

@alesribic73 - In which method installation completed successfully ( Meshcentral installer exe / NPM command line).
If its meshcentral installer try reboot your server once.
If its NPM command line method please run **"node node_modules/meshcentral"** the command and post the response.

**Comment by alesribic73** [comment]
After manual install of NodeJS i try windows installer again and it installs. It seems like WindowsInstaller does not instal NodeJS.

Thanks

**Comment by VINISHVV** [comment]
whether your issue resaved after manual install of Nodejs ?

**Comment by alesribic73** [comment]
Yes. First manual install NodeJS, ten i use MeshCentralInstaller-2.9 and installs without error.

**Comment by VINISHVV** [comment]
Thanks for confirming !!

Not sure, I think the installer comes with old version of Nodejs. 
Latest version of meshcenral only support nodejs 10 or higher.

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
I just published MeshCentral Installer v0.2.11, it will now try to download and install NodeJS v14.17.1. If it can't download, it will now ask to install NodeJS manually. i also added more debug logs. If there is any issues, you can debug by running:

```
MeshCentralInstaller.exe -log
```

This will generate a log.txt file with more detailed errors.

Also, the recommended way to install MeshCentral is using the command line, there is a [YouTube video on this here.](https://www.youtube.com/watch?v=GsQbWZmRRAU)

**Comment by alesribic73** [comment]
Great! Thanks.
