### ISSUE TITLE
Local time in Computer Uptime Export

### ISSUE THREAD

**Issue by nutterbg** [Ylianst/MeshCentral#2785]
Hi,

Quick feature request:
Is it possible for the machine uptime report export to have a column that lists local time for the user, in addition to UTC? This is similar to the request in Issue #918.

Thanks and best regards!

**Comment by Ylianst** [comment]
What is "uptime update export"? Can you show a screen shot of where you export that?

**Comment by nutterbg** [comment]
> 
> 
> What is "uptime update export"? Can you show a screen shot of where you export that?

Sorry, don't know where my mind was writing that.

This is what I'm talking about:
[https://imgur.com/a/Laoek6S](https://imgur.com/a/Laoek6S)

Currently, this has a column with the UTC time of each state change. I was wondering if it might be possible for that column's timezone to either be configurable(and matching the user?), or to have an additional column with the user's time zone, similarly to how it was implemented in #918.

I hope that makes sense.

Thanks,

**Comment by Ylianst** [comment]
Got it. I updated it for the next version. I realize that it was printing the local time of the server, this is not that useful. I changed it to UTC time and browser local time, both in ISO format. Hope that is ok.

![image](https://user-images.githubusercontent.com/1319013/122295588-40b27280-ceae-11eb-80d6-ef2fa3f6f443.png)

**Comment by Ylianst** [comment]
Version 0.8.65 was published with this fix.

**Comment by nutterbg** [comment]
Amazing! MeshCentral is seriously the best thing ever!
I wish #1952 could be resolved in a way where people could at least give symbolic gestures of thanks, even though they would be absolutely not enough to appreciate software that replaces and completely blows out of the water commercial solutions that have been in development since several years prior.
Cheers!
