### ISSUE TITLE
One-way automatic clipboard

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2786]
Tried the new automatic clipboard feature today. I noticed that this only works from my machine to the remote one. But if I copy something on the remote computer it doesn't migrate to my local one. And even when the automatic clipboard function is enabled, the button for manually retrieving the value of the remote clipboard disappears. And it turns out that it is not possible to use this fully. But the function is very handy and useful. Thank you for your work.

**Comment by Mfinadmin** [comment]
Yes. I also noticed this today.

**Comment by VINISHVV** [comment]
Facing same issue. Tried below Os versions
Windows 7
Windows 10 pro
Windows server 2019

**Comment by Ylianst** [comment]
That is correct, this is how it's built. Automatic clipboard is only one way, from browser to remote computer. Maybe I should make this more clear.
