### ISSUE TITLE
MongoDB Shrink

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#2789]
HI,
MongoDB size become big, any help how to shrink it by deleting logs and events or none useful data from the database before dump it?
Thanks

**Comment by nzalev** [comment]
> HI,
> MongoDB size become big, any help how to shrink it by deleting logs and events or none useful data from the database before dump it?
> Thanks

As a quick fix, you can safely drop the event history by exporting and importing the database. I stronly recommend taking backups before modifying the database in any way though.
```
node node_modules/meshcentral/ --dbexport server.json
```

```
node node_modules/meshcentral/ --dbimport server.json
```

**Comment by smartekIT** [comment]
thanks but these commands what I actually used when converted from NeDB to MongoDB and then the size start growing up from 60M to 500MB in just 1 week without any new devices added.
I'm looking into schedule db backup in the background while these command doesn't work for this purpose, because before import the DB if it exist then you have to drop the existing one.

the command I use to backup MongoDB is:
mongodump --archive=backup.archive

while the restore command is:
mongorestore --archive=backup.archive

when doing the backup it generate 500MB file size, of course this will even grow up more as we go.

keeping the MongoDB small and clean produce faster server commands and functions so we need a permanent maintenance command to clean the MongoDB could run per schedule.

**Comment by nzalev** [comment]
> thanks but these commands what I actually used when converted from NeDB to MongoDB and then the size start growing up from 60M to 500MB in just 1 week without any new devices added.
> I'm looking into schedule db backup in the background while these command doesn't work for this purpose, because before import the DB if it exist then you have to drop the existing one.
> 
> the command I use to backup MongoDB is:
> `mongodump --archive=backup.archive`
> 
> while the restore command is:
> `mongorestore --archive=backup.archive`
> 
> when doing the backup it generate 500MB file size, of course this will even grow up more as we go.
> 
> keeping the MongoDB small and clean produce faster server commands and functions so we need a permanent maintenance command to clean the MongoDB could run per schedule.

It sounds like something is going wrong. How many agents do you have? Our deployment has agents in the thousands, but only takes a few MB.

**Comment by smartekIT** [comment]
this server has around 20-25 agents

**Comment by nzalev** [comment]
> this server has around 20-25 agents

Your DB should probably be less than 1 MB. What version of meshcentral are you running? This can be found by the "check server version" link under the server page (see screenshot)
![Screenshot from 2021-06-17 12-06-57](https://user-images.githubusercontent.com/63608819/122433933-ab25ea00-cf64-11eb-8ff6-fe2e62d2c174.png)

Are there any errors in your error log? You can click "Show server error log" and download the file as seen in the screenshot above.

**Comment by smartekIT** [comment]
running the latest version 0.8.65
for the error log yes there is errors there. the server functions itself running ok though even if it's slow sometimes.
it's ubuntu 20.04 with 48G RAM and 12 CPU

**Comment by nzalev** [comment]
> running the latest version 0.8.65
> for the error log yes there is errors there. the server functions itself running ok though even if it's slow sometimes.
> it's ubuntu 20.04 with 48G RAM and 12 CPU

can you post the error log?

**Comment by smartekIT** [comment]
I will check and post here soon, as this log contains critical security info. Thanks

**Comment by smartekIT** [comment]
-------- 6/8/2021, 11:59:49 AM ---- 0.8.57 --------

/home/node/meshcentral/node_modules/mongodb/lib/utils.js:113
      throw err;
      ^

Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/node/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at /home/node/meshcentral/meshcentral-data/plugins/eventlog/eventlog.js:495:41
    at /home/node/meshcentral/meshcentral-data/plugins/eventlog/db.js:72:19
    at /home/node/meshcentral/node_modules/mongodb/lib/utils.js:704:5
    at handleCallback (/home/node/meshcentral/node_modules/mongodb/lib/utils.js:109:55)
    at /home/node/meshcentral/node_modules/mongodb/lib/cursor.js:840:66
    at /home/node/meshcentral/node_modules/mongodb/lib/utils.js:704:5
    at /home/node/meshcentral/node_modules/mongodb/lib/cursor.js:925:9
    at Cursor._endSession (/home/node/meshcentral/node_modules/mongodb/lib/core/cursor.js:397:7)
    at /home/node/meshcentral/node_modules/mongodb/lib/cursor.js:923:12
    at maybePromise (/home/node/meshcentral/node_modules/mongodb/lib/utils.js:692:3)
    at Cursor.close (/home/node/meshcentral/node_modules/mongodb/lib/cursor.js:916:12)
    at /home/node/meshcentral/node_modules/mongodb/lib/cursor.js:840:27
    at handleCallback (/home/node/meshcentral/node_modules/mongodb/lib/core/cursor.js:32:5)
    at /home/node/meshcentral/node_modules/mongodb/lib/core/cursor.js:683:38
    at _setCursorNotifiedImpl (/home/node/meshcentral/node_modules/mongodb/lib/core/cursor.js:696:10)


6/8/2021, 12:00:02 PM: Watchdog timer timeout, 718ms.
6/8/2021, 12:00:02 PM: Watchdog timer timeout, 598ms.
6/8/2021, 12:00:05 PM: Watchdog timer timeout, 1075ms.
6/8/2021, 12:00:06 PM: Watchdog timer timeout, 975ms.
6/8/2021, 1:10:05 PM: Watchdog timer timeout, 578ms.
6/8/2021, 2:05:03 PM: Watchdog timer timeout, 464ms.
6/8/2021, 3:43:02 PM: Watchdog timer timeout, 609ms.
6/8/2021, 3:47:54 PM: Watchdog timer timeout, 412ms.
6/8/2021, 4:19:16 PM: Watchdog timer timeout, 480ms.
6/8/2021, 4:25:09 PM: Watchdog timer timeout, 860ms.
6/8/2021, 4:25:14 PM: Watchdog timer timeout, 1075ms.
6/8/2021, 4:25:16 PM: Watchdog timer timeout, 468ms.
6/8/2021, 4:25:19 PM: Watchdog timer timeout, 3467ms.
6/8/2021, 4:25:22 PM: Watchdog timer timeout, 548ms.
6/8/2021, 4:25:23 PM: Watchdog timer timeout, 928ms.
6/8/2021, 4:25:25 PM: Watchdog timer timeout, 896ms.
6/8/2021, 4:25:26 PM: Watchdog timer timeout, 553ms.
6/8/2021, 4:25:26 PM: Watchdog timer timeout, 564ms.
6/8/2021, 4:25:31 PM: Watchdog timer timeout, 427ms.
6/8/2021, 4:25:33 PM: Watchdog timer timeout, 410ms.
6/8/2021, 4:25:36 PM: Watchdog timer timeout, 521ms.
6/8/2021, 4:25:39 PM: Watchdog timer timeout, 636ms.
6/8/2021, 4:25:39 PM: Watchdog timer timeout, 1153ms.
6/8/2021, 4:25:41 PM: Watchdog timer timeout, 1223ms.
6/8/2021, 4:25:57 PM: Watchdog timer timeout, 463ms.
6/8/2021, 4:31:02 PM: Watchdog timer timeout, 498ms.
6/8/2021, 4:31:03 PM: Watchdog timer timeout, 1536ms.
6/8/2021, 4:45:03 PM: Watchdog timer timeout, 762ms.
6/8/2021, 4:45:04 PM: Watchdog timer timeout, 643ms.
6/8/2021, 4:45:05 PM: Watchdog timer timeout, 417ms.
6/8/2021, 4:45:07 PM: Watchdog timer timeout, 449ms.
6/8/2021, 4:45:08 PM: Watchdog timer timeout, 453ms.
6/8/2021, 4:50:08 PM: Watchdog timer timeout, 551ms.
6/8/2021, 5:00:07 PM: Watchdog timer timeout, 595ms.
6/8/2021, 5:00:07 PM: Watchdog timer timeout, 439ms.
6/8/2021, 5:05:04 PM: Watchdog timer timeout, 964ms.
6/8/2021, 5:05:04 PM: Watchdog timer timeout, 450ms.
6/8/2021, 5:06:02 PM: Watchdog timer timeout, 465ms.
6/8/2021, 5:15:04 PM: Watchdog timer timeout, 1107ms.


the last one (Watchdog timer timeout) keep repeating all over the place.

**Comment by nzalev** [comment]
You have `watchdog` enabled in your config.json. The watchdog timer runs a `setInterval` and will warn if it next comes up too long beyond that interval (the timeout period). This is pretty much confirmation of the slowness you feel.

I imagine this is not the only stack trace? The mesherrors log should contain mainly just stack traces. I am looking for anything that would be balooning the size of your db. You had said as well that your neDB was 60 MB. Again, this is way too big.

Likely, this is unrelated to the database (or choice of database). There is most likely something repeatedly entering data. There was a bug where agents were being repeatedly re-added, but you would see these in the UI. I think something similar is going on.

If you import and export your db using the previous commands, and the size goes substantially down, it is event data. If the size does not go down, there are a few candidates:

- Node types. Example:
```
node//HD4gT$cZG2V5ZKJEuLiIQKCVfF$OMgM$Wde6MOwnEE2o3fPaGmytBp6myjOyfizc
```
There should only be as many nodes in the database as there are agents.

- ifinfo:
```
ifnode//ZezrBSGLmN5ZOnifw2rdCVG0SJqR$mN0DiVlv33np46@5BGo1oRVYKTIhIcytfKM
```
There should be less than or equal to nodes

- `sinode` type keys: there should be an equal number to number of agents
- `lcnode` type keys: less than or equal to number of agents
- `mesh` type keys: These are the groups. There should only be as many as the number of groups you have.

There is a good mongodb GUI program to see the keys that are in your DB. I'd try and see whats consuming 599MB.

**Comment by smartekIT** [comment]
could it be the event plugin I activated on the server? i will uninstall it then measure the db size after export/import

**Comment by Ylianst** [comment]
For MeshCentral database events, you can add this section to the config.json to set how must time to keep events:

```
"dbexpire": {
  "events": 1728000,
  "powerevents": 864000,
  "statsevents": 2592000
}
```

Above are the default values in seconds. You can put this section and set lower value.

I don't do any testing with plugins, so if plugins are in use I can't help.

**Comment by VINISHVV** [comment]
> could it be the event plugin I activated on the server? i will uninstall it then measure the db size after export/import

I am running meshcentral with 9000+ agents also i am keeping 1 year events logs in my Database. The current DB size is 350MB only. In your case its definitely due to the Plugins. Please try deactivate Plugins and drop below tables.

plugin_filedistribution 
plugin_routeplus 
plugin_scripttask 
plugin_workfromhome 
plugins 
etc...

**Comment by smartekIT** [comment]
Thanks heaps everyone. yes it was a plugin called: plugin_evenlog
after dropping the related tables (plugin_evenlog and plugin_evenlog_settings) the size of the database backup was reduced to 5MB.... wow that's a huge change.

here is the steps I've done to alter the MongoDB and drop these tables for the benefit of other users:

# connect to MongoDB:
mongo

# list databases:
show dbs

# selecting meshcentral db:
use meshcentral

# list tables (collections):
show collections

# this will list the following;
events
meshcentral
plugin_eventlog
plugin_eventlog_settings
plugin_filedistribution
plugin_routeplus
plugin_scripttask
plugins
power
serverstats

# now drop plugin_eventlog and plugin_eventlog_settings by the following commands:
db.plugin_evenlog.drop()
db.plugin_evenlog_settings.drop()

All done and we have a small database back again.

**Comment by ryanblenis** [comment]
Any chance you have Win7 agents connecting? I've seen some reports of databases growing with eventlog on Win7 machines.

**Comment by smartekIT** [comment]
> Any chance you have Win7 agents connecting? I've seen some reports of databases growing with eventlog on Win7 machines. I thought the issue was fixed, but of course, eventlog will store event logs for all the endpoints, which of course, will take up space.

I've checked connected agents and from what I can see they mostly win servers and win10.

**Comment by Ylianst** [comment]
I will close this since it's not MeshCentral related. However, please continue to give information to @ryanblenis is possible.
