### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [issus]  [Rec Player Not functioning properly]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2795]
Hi, 
Separate issue From #2793 

> [Rec Player]

Desktop Recoding
Most sessionRecording on the server side can be played normally
But the  sessionRecording file recorded manually during desktop connection cannot be played.
The progress bar cannot jump to a certain period of time.
;

**Comment by Ylianst** [comment]
If you can provide a sample file with this problem, that would be great.

**Comment by Jacky0400143** [comment]
@Ylianst 
I Send  a sample file and sent to the hotmail provided on your github
The device is as same as #2794  , and server hosted sessionRecording works fine except index not funtion.
I also tested other devices, but none of them can be played when using recorded manually (not server recording)

Thank you

**Comment by Ylianst** [comment]
I looked at the file you sent me and I can index it correctly. I am guessing that because your server is overloaded, it could not index correctly. In MeshCentral v0.8.66, I have a new command:

```
node meshcentral --indexmcrec "c:\tmp\myrecording.mcrec"
Indexing file: c:\tmp\x.mcrec
```

This will allow you to manually index any file you like. In addition, I added 5 second pause before the server starts indexing a recording, hopefully that will solve this when the server is busy.

**Comment by Jacky0400143** [comment]
@Ylianst 

Thank you for Comment.
very happy you can provide updates as fast you can.
Sorry for asking some questions

New command could done on the server or i has to use linux terminal ?

```
node meshcentral --indexmcrec "c:\tmp\myrecording.mcrec"
Indexing file: c:\tmp\x.mcrec

```

and another question is 
without problem of index , server host session record can normaly playback 

but i can not play any record file via using the "record remote session to file" funtion.
It does generate a file to download, but when I use the player to play, nothing happens, whether it is selecting the file or using drop funtion.

May I ask what problem is, I also provided relevant samples in another letter a few days ago.


![圖片](https://user-images.githubusercontent.com/75102529/123089458-ed1dc700-d461-11eb-9d6f-f9c77a8cc7d4.png)

**Comment by Jacky0400143** [comment]
A new issue has been resubmitted on #2818
