### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [Features] [List of installed software]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2796]
Hi, 
Separate issue From #2793 

> [List of installed software] 

Just like old Issue #393 , Is this function implemented?
;

**Comment by si458** [comment]
added installedapps to console for windows - https://github.com/Ylianst/MeshCentral/commit/12c3e4ee53a6a8a4108e9a7946d6df60dcd7a280
