### ISSUE TITLE
MeshCentral 0.8.63~0.8.65 . [Features] [sessionRecording Convert]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2799]
Hi, 
Separate issue From #2793 

> [sessionRecording Convert]

Is there a way to convert the file to a common format for playback?
;

**Comment by VINISHVV** [comment]
Duplicate #2573

**Comment by Jacky0400143** [comment]
@VINISHVV 
Thanks for Duplicate Question.

**Comment by Ylianst** [comment]
At some point, I could look into converting to .mjpeg file, but I need to find the file format for this.
