### ISSUE TITLE
Ylianst is on vacation until Thuesday June 22th.

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#2802]
Quick note to say that I am on vacation until June 22th so, I will be slow with responses and will probably not do any new releases until then. It's my first small vacation since COVID started and I am fully vaccinated.

There is a lot of traffic on MeshCentral GitHub which is great and I will continue to help as much as possible.

**Comment by PetieM** [comment]
We'll survive a few days - enjoy some well-deserved rest and a bit of normalcy after a year and a half of quarantine!
