### ISSUE TITLE
Add X-Frame Option and Strict-Transport-Security headers

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2807]
AutoComplete Attribute Not Disabled for Password in Form Based Authentication	
X.509 Certificate SHA1 Signature Collision Vulnerability	
HTTP Security Header Not Detected

**Comment by Ylianst** [comment]
1. Currently, `autocomplete="current-password"` is used which is correct. If you want to disable that use `"autocomplete":false` in the domain settings. Note that `autocomplete=false` is ignore by browsers, so it's not that useful.
2. MeshCentral uses SHA384, if you put your own certificate, that is your issue. If you have more details, let me know.
3. MeshCentral uses a very strict CSP header. If you have more details of what header you would like to see, let me know.

**Comment by aimdharma1990** [comment]
> 3\. MeshCentral uses a very strict CSP header. If you have more details of what header you would like to see, let me know.

Thanks. According the scan the X-Frame Option is missing the header

Following will the HTTP response header

GET / HTTP/1.0
Host: 172.19.128.170:8443
 
 
HTTP/1.1 200 OK
Referrer-Policy: no-referrer
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' wss://172.19.128.170:8443; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self' mcrouter:; media-src 'self'; form-action 'self'
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: text/html; charset=utf-8
Content-Length: 30746
ETag: W/"781a-mBvsYqMUdNLrmFk7SCFwzbs7jFM"
Vary: Accept-Encoding
Date: Thu, 17 Jun 2021 03:57:04 GMT
Connection: keep-alive
Keep-Alive: timeout=5
 
Strict-Transport-Security HTTP Header missing on port 8443.
 
HTTP/1.1 200 OK
Referrer-Policy: no-referrer
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' wss://172.19.128.170:8443; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self' mcrouter:; media-src 'self'; form-action 'self'
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: text/html; charset=utf-8
Content-Length: 30746
ETag: W/"781a-mBvsYqMUdNLrmFk7SCFwzbs7jFM"
Vary: Accept-Encoding
Date: Thu, 17 Jun 2021 03:57:06 GMT
Connection: keep-alive
Keep-Alive: timeout=5#

**Comment by Ylianst** [comment]
Unless you add:

```
"AllowFraming": true
```

To the settings section of the config.json, you should see `X-Frame-Options: sameorigin' in the MeshCentral response.

![image](https://user-images.githubusercontent.com/1319013/123478421-47c73800-d5b4-11eb-9e7e-682f449ce7d1.png)

Are you sure you don't have a reverse proxy removing this line or you added AllowFraming?

**Comment by Ylianst** [comment]
MeshCentral v0.8.67 will have "Strict-Transport-Security" enabled by default. You can turn it off by adding this line in the settings section of the config.json:

```
"StrictTransportSecurity":false
```

Or customize it like this:

```
"StrictTransportSecurity":"my own value"
```
