### ISSUE TITLE
Text "undefined" with email confirmation notification popup

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#281]
![image](https://user-images.githubusercontent.com/5203309/59095777-9811c580-8919-11e9-978b-b9837f5cd38d.png)
When an email confirmation has been done by a user. The popup notification show "undefined".

**Comment by Ylianst** [comment]
Thanks for the report. Just fixed it. Will be in MeshCentral v0.3.6-f when I publish it.

**Comment by Ylianst** [comment]
Ok, MeshCentral v0.3.6-f is up. Thank you very much for all the reports, very much appreciated.

**Comment by hunter-nl** [comment]
Yes, fixed. Thanks!
