### ISSUE TITLE
Display selection tab of MC Router does not work

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2810]
When remotely accessing a remote PC using dual monitors through the MC Router, I selected one of the dual monitors, but the display tab of the MC Router did not work.

![그림1](https://user-images.githubusercontent.com/6889244/123180653-a0200c00-d4c6-11eb-8ff8-30ac88072c51.png)

**Comment by Ylianst** [comment]
I just tested it and it worked for me. You will have to provide more information.

![image](https://user-images.githubusercontent.com/1319013/123481023-0769b900-d5b8-11eb-9c69-bd613a167358.png)

**Comment by Ylianst** [comment]
Ok, fixed it. Will be in new MeshCentral Router included in MeshCentral v0.8.67.

![image](https://user-images.githubusercontent.com/1319013/123485208-7e09b500-d5be-11eb-9d65-f91528173a20.png)
