### ISSUE TITLE
Show guest name in session list for sharing links

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2812]
Minor feature request - can you show the guest name instead of (or in addition to) the account that shared the link when a guest is connected via a sharing link? Right now, it shows my username when guests connect which isn't terribly useful. Maybe something like "Guest Name (Account Name)" where the account name is the user who created the share link? Thanks!

**Comment by Ylianst** [comment]
Oh, I get it now. This is for notification and user consent prompt when connecting using guest.

**Comment by PetieM** [comment]
It's actually more for the list of active sessions shown on the device in MeshCentral itself. It appears to show both names for remote connections. I've attached two screenshots with the second being the one that is not showing the guest name (Test, in this case).
![image](https://user-images.githubusercontent.com/16453878/123342133-6d990200-d50c-11eb-981e-e7ea831f96d2.png)
![image](https://user-images.githubusercontent.com/16453878/123342141-738ee300-d50c-11eb-8297-68413426ef3b.png)

**Comment by Ylianst** [comment]
Ok, next version will have the share name next to the user name:

![image](https://user-images.githubusercontent.com/1319013/123471877-4b09f600-d5ab-11eb-8037-f6df506117bd.png)

Hidden feature, but I also fixed it when you click on the number of user's watching the session.

![image](https://user-images.githubusercontent.com/1319013/123471777-29a90a00-d5ab-11eb-9cc5-278db6ca062e.png)

Will be in v0.8.67.

**Comment by Ylianst** [comment]
Added UTF8 guest name support.

![image](https://user-images.githubusercontent.com/1319013/123473353-4fcfa980-d5ad-11eb-8edc-4bed3be336b4.png)

**Comment by Ylianst** [comment]
Arg... I need to fix MeshCentral Assistant and MeshCentral Android Agent too.

**Comment by Ylianst** [comment]
Added support in MeshCentral Assistant.

![image](https://user-images.githubusercontent.com/1319013/123476426-8f989000-d5b1-11eb-8245-d932f40d492e.png)

**Comment by Ylianst** [comment]
MeshCentral v0.8.67 was posted with this fix. On a related note, I posted a video on [YouTube this week on device guest sharing](https://www.youtube.com/watch?v=qHJuXwiV-XU).

**Comment by PetieM** [comment]
I'm new getting an all lowercase version of my username and no guest name in the session list when looking at a connected guest session. Names are still appearing correctly in the consent prompt, privacy bar, and notification.

**Comment by Ylianst** [comment]
Oh, I will take a look at this.

**Comment by Ylianst** [comment]
I just did a bunch more bug fixes on this, will be in MeshCentral v0.8.68. Once published, let me know if it works.

**Comment by PetieM** [comment]
My username is no longer lowercase but it's still not showing the guest username in the session lists from the MeshCentral side (though it is still working properly in the consent prompt, privacy bar, and notification).

Just FYI, this isn't super high priority so if it's taking you away from other, more important tasks, feel free to stick it on the back burner.

**Comment by Ylianst** [comment]
Doh. Your right, I don't see the guest name on the MeshCentral site... working on this now.

**Comment by Ylianst** [comment]
Oh, I see the problem only happens for remote desktop sessions when the desktop multiplexor is enabled. Is this the same for you?

**Comment by PetieM** [comment]
I do indeed have the multiplexor enabled. I can test with it disabled if needed.

**Comment by Ylianst** [comment]
Ok, just fixed the multiplexor to also support sending the guest name.

![image](https://user-images.githubusercontent.com/1319013/124328656-e4eb1900-db3e-11eb-8c36-91e96fa84ef2.png)

Will be in v0.8.71.

**Comment by PetieM** [comment]
Confirming this is working for me now. Thank you!
