### ISSUE TITLE
My Events log showing 127.0.0.1 for devices added to Local devices group

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2813]
Hi. 
When remotely accessing a PC added to the Local devices group, the IP address of the PC that started remote access is not logged in My Events of MC, but 127.0.0.1 is logged.

![그림1](https://user-images.githubusercontent.com/6889244/123184935-c6967500-d4cf-11eb-842f-8f022bdb6573.png)

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.8.69. Let me know if that works. I also display the protocol. Since the session starts from the server, the "from" IP address made no sense.

![image](https://user-images.githubusercontent.com/1319013/123727685-e074e680-d846-11eb-985b-755d714cd509.png)

**Comment by kuksabong** [comment]
Thanks Ylian!
But I think it would be good for security audits if the "from" IP address logs the **IP address from which the MC is logged in.**
