### ISSUE TITLE
Terminal on mobile version hangs meshagent

### ISSUE THREAD

**Issue by TotallyNotElite** [Ylianst/MeshCentral#2814]
Whenever text is deleted on the mobile version of meshcentral, Linux agents hang completely.
I've already described this here https://github.com/Ylianst/MeshCentral/issues/2204#issuecomment-824010947 in April, but the issue was recently closed for whatever reason.
The same issue is also described [here](https://github.com/Ylianst/MeshCentral/issues/2478#issuecomment-817563865) and [here](https://github.com/Ylianst/MeshCentral/issues/2478#issuecomment-828204880).
This unfortunately makes the mobile terminal rather unusable :/
I've also noticed these hangs sometimes happen on the desktop version of MeshCentral too after entering some characters, although I can't actually reproduce the issue reliably. This makes me suspect that there's an underlying issue.
I've already done some investigative work on the agent by piping the ws output into the agents stdout, and it appears that backspace from the mobile site acts differently than backspace from the desktop site, but I don't know the exact specifics since the "data" event does not seem to act the same way as it does on nodejs.

**Comment by TotallyNotElite** [comment]
Any updates on this yet? I'd love to use meshcentral on mobile devices to admin systems on the go. I'm sadly not familiar enough with the codebase to figure out what's wrong myself :/

**Comment by TotallyNotElite** [comment]
Oh never mind I got it.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.8

**Comment by TotallyNotElite** [comment]
Can confirm this  is fixed, closing.
