### ISSUE TITLE
When exporting event lists to a csv file in My Events menu, Korean is broken

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2815]
Hi.
When exporting event lists to a csv file in My Events menu, Korean is broken

![그림2](https://user-images.githubusercontent.com/6889244/123392331-e749f200-d5d7-11eb-95d1-69c636d6fe65.png)

And if there is a **search function** in the My Events menu, it would be good for security audits.

**Comment by Ylianst** [comment]
Nice catch. Thank you for sending the screen shot, that helps a lot.

**Comment by Ylianst** [comment]
Thanks for reporting. Fixed in MeshCentral v0.8.67.
