### ISSUE TITLE
require confirmation when being controlled remotely

### ISSUE THREAD

**Issue by axeprpr** [Ylianst/MeshCentral#2816]
is there any configuration like this?

**Comment by VINISHVV** [comment]
Yes !.

You can enable user consent for individual user/user group.

**Comment by yomono** [comment]
Actually you can configure this from different places:
From the device group , the individual device, and at user/groups level as VINISHVV said.
It looks like this:
![image](https://user-images.githubusercontent.com/31445936/123453067-72fe5700-d5b5-11eb-99ce-a021ec658022.png)
As you can see, you can notify, ask for permission, or both, on any tipe of connection.
Pretty cool

**Comment by Ylianst** [comment]
Indeed, you can do it per-device group:

![image](https://user-images.githubusercontent.com/1319013/123458204-a206cf80-d599-11eb-82b4-abccc2551429.png)

Per device:

![image](https://user-images.githubusercontent.com/1319013/123458255-b1861880-d599-11eb-8395-26854c83c6d8.png)

Per user:

![image](https://user-images.githubusercontent.com/1319013/123458298-bf3b9e00-d599-11eb-8046-b8b27276f4bf.png)

Per user group:

![image](https://user-images.githubusercontent.com/1319013/123458355-cf537d80-d599-11eb-8835-9b47e8710ed8.png)

You can also do it server domain wide in the config.json, add this to the one of your domains:

```
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": false,
        "terminalprompt": false,
        "fileprompt": false,
        "desktopprivacybar": false
      },
```

**Comment by axeprpr** [comment]
thank you!
