### ISSUE TITLE
Power events showing wrong local time

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2817]
Dear Ylian,

Power event showing wrong local time. In my case i am getting 1 hour difference from my local time (UTC +5.30 (INDIA)). 

I Think the issue is happened after fix this issue #2785

**Sample Report.**

UTC Time - 2021-06-25T10:56:43.123Z
Local Time - 2021-06-25T05:26:43.123

**Comment by Ylianst** [comment]
Checked in a fix for this. Let me know if it works.

**Comment by VINISHVV** [comment]
Thanks Ylian,

Its resolved.

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back.
