### ISSUE TITLE
MeshCentral-0.8.67_[Issues]_[User Side Manual Desktop Session Recording Still Not Working]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2818]
similar issue like #2795

> MeshCentral version 0.8.67 , all agents are up to date
> Server : Raspberry Pi 4 2GB RAM , Linux raspberrypi 5.10.17-v7l+ #"1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
> 
> Using Firefox 64bit 89.0.2 and Edge based on Chromium 64bit 91.0.864.48

Issus :

> Can Not playback any record file via using the "record remote session to file" funtion.

I also asked the question in #2795, sorry to ask again, 

The server has been updated to version 0.8.67,
At the same time, I replaced a memory card For Raspberry Pi 4 with faster reading and writing speed to improve performance

Can Not playback any record file via using the "record remote desktop session to file" funtion.
It does generate a file to download, but when I use the player to play, nothing happens, whether it is selecting the file or using drop funtion.

![圖片](https://user-images.githubusercontent.com/75102529/123514094-e98d7880-d6cb-11eb-9997-6902fdc5421c.png)

Do I need to make any settings or adjustments?

Many Thanks

**Comment by Ylianst** [comment]
Thanks for reporting this. I will test it out when I get back to work.

**Comment by Ylianst** [comment]
Interesting, I just tested it and it works for me. I just tested it with a 30 second recording. I load the file in the player and I see this:

![image](https://user-images.githubusercontent.com/1319013/123555134-ae755e80-d738-11eb-8cc5-a6a5b15b5a16.png)

I then hit space and it starts playing as expected.

**Comment by Jacky0400143** [comment]
@Ylianst 

May I send You Video of my operation steps. also test files, including client and server.

Because the client side of my test is unavailable, but the server side can work.

Not sure if it was caused by a mistake in my operation

The difference between two Files .in addition to the different recording methods, there will also be a set of random values at the end of the file name on the server side Record.

Also Server side record has A File name Time Error Bug . Because today is "20210628"，but record file named "2021-05-28"，also recording time on the file name is wrong. Because my time zone is UTC+8 . The correct time should be 2021-06-28-11-36-23.

**Comment by kuksabong** [comment]
I tested it too and I have the same problem.
When I drag and drop the mcrec file into MeshCentral Session Player, nothing happens.

![그림1](https://user-images.githubusercontent.com/6889244/123727950-76535480-d8cd-11eb-9d4b-467f0558a9ee.png)
