### ISSUE TITLE
[RASPBERRY] Server cannot be updated

### ISSUE THREAD

**Issue by PandCall** [Ylianst/MeshCentral#2819]
Hello,
I have two Raspberry servers with Raspbian Buster.
For one of them (the first one), the update function through the interface or through the console (serverupdate) does not work. It acts as if it was updating, but remains on the same version. Without error messages

**First**
> updatecheck
Checking server update...
current: 0.8.62
latest: 0.8.67
stable: 0.7.89

> versions
{
    "node": "16.2.0",
    "v8": "9.0.257.25-node.16",
    "uv": "1.41.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.17.1",
    "modules": "93",
    "nghttp2": "1.42.0",
    "napi": "8",
    "llhttp": "6.0.1",
    "openssl": "1.1.1k+quic",
    "cldr": "39.0",
    "icu": "69.1",
    "tz": "2021a",
    "unicode": "13.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
}

> info
{
    "rss": 106594304,
    "heapTotal": 36827136,
    "heapUsed": 33853064,
    "external": 12380973,
    "arrayBuffers": 10586927,
    "dbType": "NeDB",
    "nodeVersion": "v16.2.0",
    "meshVersion": "0.8.62",
    "platform": "linux",
    "arch": "arm",
    "pid": 3688,
    "uptime": 289.724627421,
    "cpuUsage": {
        "user": 26795095,
        "system": 1015880
    },
    "warnings": [],
    "database": "NeDB",
    "productionMode": true,
    "allDevGroupManagers": []
}

**Second**
> updatecheck
Checking server update...
current: 0.8.67
latest: 0.8.67
stable: 0.7.89

**Comment by PandCall** [comment]
Same problem after full upgrade and Node Upgrade
> versions 
{
    "node": "16.4.0",
    "v8": "9.1.269.36-node.14",
    "uv": "1.41.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.17.1",
    "modules": "93",
    "nghttp2": "1.42.0",
    "napi": "8",
    "llhttp": "6.0.2",
    "openssl": "1.1.1k+quic",
    "cldr": "39.0",
    "icu": "69.1",
    "tz": "2021a",
    "unicode": "13.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
}

**Comment by nzalev** [comment]
Meshcentral performs its self update by spawning a child process and using it to run `npm install meshcentral@version`. It then restarts itself, so it will not show any errors in the UI.

A couple of months ago, I added a line which will print any errors from npm to the console, which can be seen by running meshcentral interactively, ie, cd to the meshcentral directory and run
```node node_modules/meshcentral```

and then try the update again to see what the error is.

**Comment by Ylianst** [comment]
The manual way to update:

- Go to the MeshCentral folder that is above "node_modules" and "meshcentral-data"
- Make sure you have an offsite backup of "meshcentral-data". If you are using a database like MongoDB, keep a backup of that. An easy way is to go in "meshcentral-backups" and download the latest auto-backup to a safe place.
- Stop the server.
- Recommended: copy or rename the "node_modules" folder to keep a backup of that.
- Type `npm install meshcentral`
- Start the server

That will update the "node_modules" folder with the latest MeshCentral and you are good to go.

For the automatic update, I MeshCentral tries to run "npm", but if it can't find it, it will not work. You can add the following link in the settings section of your config.json:

```
"npmpath":"\usr\example\npm"
```

That will tell MeshCentral exactly what "npm" to use and should make the auto-update work correctly.

**Comment by PandCall** [comment]
Thank you for your quick answer.
The manual update worked.
with this output return

-----------------------------------------------------------------------
npm install meshcentral

added 157 packages, and audited 158 packages in 47s

4 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

-----------------------------------------------------------------------

After command
npm audit fix
pi
└── https://github.com/sponsors/feross
    └── safe-buffer@5.2.1, buffer@5.7.1, base64-js@1.5.1, ieee754@1.2.1

-----------------------------------------------------------------------
npm audit fix

up to date, audited 157 packages in 7s

4 packages are looking for funding
  run `npm fund` for details

# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
No fix available
node_modules/underscore
  binary-search-tree  *
  Depends on vulnerable versions of underscore
  node_modules/binary-search-tree
    nedb  *
    Depends on vulnerable versions of binary-search-tree
    Depends on vulnerable versions of underscore
    node_modules/nedb
      meshcentral  *
      Depends on vulnerable versions of express-ws
      Depends on vulnerable versions of nedb
      node_modules/meshcentral

ws  5.0.0 - 5.2.2 || 6.0.0 - 6.2.1 || 7.0.0 - 7.4.5
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1748
No fix available
node_modules/ws
  express-ws  
  Depends on vulnerable versions of ws
  node_modules/express-ws
    meshcentral  *
    Depends on vulnerable versions of express-ws
    Depends on vulnerable versions of nedb
    node_modules/meshcentral

6 vulnerabilities (2 moderate, 4 high)

Some issues need review, and may require choosing
a different dependency.
-----------------------------------------------------------------------
I will test the automatic update next time.
Thanks for your help.
Regards

**Comment by Ylianst** [comment]
For the audit issues, I am aware of this. I need to update to a new version of ExpressJS/WS but the current MeshAgent uses WebSockets in a way that is not compliant with new versions of ExpressJS/WS and so, I can't update. Once Bryan gives me a new version of the agent and it's fully deployed, then we can update and fix this.
