### ISSUE TITLE
Can we restrict guest access under specific domain?

### ISSUE THREAD

**Issue by dani717** [Ylianst/MeshCentral#2822]
Hello all,

I want to embed desktop access in a separate domain but is it possible to restrict it to one or two domains from the server-side?

The problem I am facing is that I want to give 10 to 30 min guest access but under another domain and don,t want to let people directly use the original server link.

Thanks,
Dani

**Comment by Ylianst** [comment]
I should be able to add a way to disable guest access on a per-domain basis.

**Comment by Ylianst** [comment]
You can specify if you want guest device sharing enabled for each domain by adding the following line in the domain section of the config.json:

```
"guestDeviceSharing": false
```

The default is true. Let me know if that works.
