### ISSUE TITLE
[0.8.69]_[Issues]_[New Funtion ,CPU State History statistics data disappear]

### ISSUE THREAD

**Issue by Jacky0400143** [Ylianst/MeshCentral#2823]
Environment：

> MeshCentral version 0.8.67 , all agents are up to date
> Server : Raspberry Pi 4 2GB RAM , Linux raspberrypi 5.10.17-v7l+ #"1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

> Using Firefox 64bit 89.0.2 and Edge based on Chromium 64bit 91.0.864.48

Issus :

### Aboout New Funtion ,CPU State History statistics data automatically disappear.

Description：

- It is not possible to review the past CPU State history records. 
- If the webpage is not refreshed, the records will continue, but once the webpage is refreshed, the records will disappear

![圖片](https://user-images.githubusercontent.com/75102529/123589349-0c32a500-d824-11eb-8c73-99ebcfc032de.png)

- But other types of records are normal and will not disappear automatically, and will continue to maintain records

![圖片](https://user-images.githubusercontent.com/75102529/123589387-181e6700-d824-11eb-9f31-b8d0082cbc29.png)

Because this is a new category, I’m not sure if it’s normal or what settings need to be made.

Sorry for asking so many questions recently, thank you very much for your great help

**Comment by Ylianst** [comment]
The new CPU data will start being logged after you update to the latest version. It will take a while to fill the graph. If this is not the problem and data is removed, let me know.

**Comment by Jacky0400143** [comment]
@Ylianst 

I check CPU State today.Data disappeared again.
I took a look at the server folder /meshcentral_data/meshcentral-stats.db
But I don’t know how it works.There seems to be information in it, 

But the same, the number of connections and memory records exist.
Can be track back to a week ago to nearly 30 days.

### The screenshot shows the CPU status and memory status at the same time this morning.

![圖片](https://user-images.githubusercontent.com/75102529/123724143-c7137f00-d8c6-11eb-86f7-f3150b651991.png)

![圖片](https://user-images.githubusercontent.com/75102529/123724170-d5619b00-d8c6-11eb-81cf-f24ac37acdd8.png)

### The screenshot shows the CPU status and memory status at the same time right now.

![圖片](https://user-images.githubusercontent.com/75102529/123748599-60568b80-d8ef-11eb-8b15-ac29c3e0a176.png)

![圖片](https://user-images.githubusercontent.com/75102529/123748449-31401a00-d8ef-11eb-9f34-d8fae8e9c621.png)

### Reflash Browser websit
After I captured the above screen I Reflash Browser websit.The CPU status is removed,And re-record but other historical records still exist, such as memory, number of connections, network traffic, etc.

![圖片](https://user-images.githubusercontent.com/75102529/123749216-25088c80-d8f0-11eb-81af-7c73b0f7bc02.png)

![圖片](https://user-images.githubusercontent.com/75102529/123749253-2e91f480-d8f0-11eb-8eb8-d3894d4a2523.png)

**Comment by Jacky0400143** [comment]
@Ylianst 
Problem still Existing in the system after updated to the latest version (0.8.69),Only the processor status will be re-recorded after refreshing the page Sorry to interrupt, I don’t know if this problem is my settings error or a server problem.

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
