### ISSUE TITLE
Device transfer from account to account

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#2824]
Hi ylian,

Can we transfer or move the device from onee account to other account on the same server ?

**Comment by Ylianst** [comment]
Yes. You can click on a device group and grant another account access to the entire group by pressing this link:

![image](https://user-images.githubusercontent.com/1319013/123706084-ad1d6200-d81c-11eb-88d1-0da41c8bfb36.png)

If you want to grant access to an individual device, click on the device and click on this link:

![image](https://user-images.githubusercontent.com/1319013/123706190-cf16e480-d81c-11eb-9754-3fd8e4b393de.png)

Hope that helps,
Ylian

**Comment by sysadmin-us** [comment]
Thanks @Ylianst
