### ISSUE TITLE
Error Resource translation tool

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2825]
After downloading with github desktop, i openend the translate.json, the following error was shown

https://github.com/petervanv/MeshCentral/commit/803555b0dc2d59eb4679debbe050e913b09aac83#diff-8004ad1701cc7eb0ad4945e2f7210107baf5d342ad16f30d8c9e69d534c4d1ac
![image](https://user-images.githubusercontent.com/58996467/123690381-972b9380-d854-11eb-92ca-827e805a1f9d.png)

**Comment by Ylianst** [comment]
Thanks for reporting it. I see the same problems. Working on it now.

**Comment by Ylianst** [comment]
I got a fix for it. New [ResourceTranslator.zip](http://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip) here. I also added Swedish and code signed the tool. Let me know if it works.

**Comment by petervanv** [comment]
confirmed fix. Thx
