### ISSUE TITLE
MeshAgent vs Meshcentral Assistant 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2826]
Dear Ylian,

While comparing Meshcentral Assistant ( Always Connected ) with Meshagent, Assistant remote Access taking more time to connect and some time its hangs. 

Meshagent is working fine without any delays.

**Comment by Ylianst** [comment]
Both MeshAgent and MeshCentral Assistant should be fast. I will look, but it is a big delay and you can run MeshCentral Assistant with -debug and return the log, maybe i can see what is causing the delay.

**Comment by VINISHVV** [comment]
Dear Ylian,

Please note below debug logs.

[debug.log](https://github.com/Ylianst/MeshCentral/files/6735447/debug.log)

**Comment by Ylianst** [comment]
Last night I made improvements to MeshCentral Assistant to make start a lot faster, this will be in v0.8.70. As for the bug your are reporting, the logs show the agent disconnected but not sure why. I will do some testing.

**Comment by VINISHVV** [comment]
Dear Ylian,

I have updated the server to latest version v0.8.70. But still facing slowness.

**Comment by VINISHVV** [comment]
I have tried the Latest Assistant (Always Connected) in below OS. All showing slowness and some time system hangs for few minute.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Lenovo\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Lenovo\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



osdesc
--
Windows 7 Professional [7601]
Windows 10 Pro - 2004 [19041]
Windows 10 Pro - 1803 [17134]
Windows 10 Pro - 1909 [18363]
Windows 10 Pro - 2009 [19042]
Windows 10 Enterprise - 1903 [18362]
Windows 10 Enterprise - 1909 [18363]
Windows 8.1 Pro [9600]
Windows 10 Home Single Language - 1607   [14393]
Windows 8 Pro [9200]
Windows 10 Pro - 1709 [16299]
Windows 10 Enterprise - 2009 [19042]
Windows 10 Pro - 1903 [18362]
Windows 10 Pro - 1809 [17763]
Windows 10 Pro - 1703 [15063]
Windows 10 Pro [10240]
Windows 8.1 Enterprise [9600]
Windows 10 Enterprise - 2004 [19041]
Windows 10 Pro - 2009 [19043]
Windows 7 Home Premium [7601]
Windows 7 Ultimate [7601]
Windows 10 Home - 1909 [18363]
Windows 10 Home - 1903 [18362]
Windows 7 Ultimate [7600]
Windows 10 Pro - 1511 [10586]
Windows 10 Enterprise for Virtual   Desktops - 1903 [18362]
Windows 10 Home - 2009 [19042]
Windows Vista (TM) Ultimate [7601]
Windows 7 Home Basic [7601]
Windows 10 Enterprise - 2009 [19043]



</body>

</html>

**Comment by VINISHVV** [comment]
@Ylianst - if you need any debug log then please let me know.

**Comment by VINISHVV** [comment]
@Ylianst - I can see lots of efforts you have done.
Now the application is little better but not 100% .

**Comment by Ylianst** [comment]
Hopefully I just fixed this in MeshCentral v0.9.45. #3212
