### ISSUE TITLE
Ref: Exploring alternative database backends #322

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#2828]
@Ylianst, you mention Azure Cosmos. I don't know quite enough about the database options out there and what's supported in Mesh to know the answer to this question. Is Cosmos also supported given the list of currently supported DB options?

**Comment by nzalev** [comment]
> @Ylianst, you mention Azure Cosmos. I don't know quite enough about the database options out there and what's supported in Mesh to know the answer to this question. Is Cosmos also supported given the list of currently supported DB options?

The currently supported db backend are NeDB, MongoDB, MariaDB and MySQL.

I have never used Azure Cosmos, but it seems that it supports an API that is compatible with MongoDB. It looks like you may be able to point the mongodb URI at it and have it work.

https://docs.microsoft.com/en-us/azure/cosmos-db/create-mongodb-nodejs

**Comment by Ylianst** [comment]
@nzalev is exactly right. If it's MongoDB compatible and you try it, let us know if it works. It would be interesting to know.
