### ISSUE TITLE
Showing source IP address for devices added to Local devices group in My Events log

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2829]
Hi. Ylian!
I think it would be good for security audits if the **MC login IP address** is shown as the **source IP address("from" IP address)** for the devices added to the Local devices group in the My Events log.

_Originally posted by @kuksabong in https://github.com/Ylianst/MeshCentral/issues/2813#issuecomment-870392916_

**Comment by Ylianst** [comment]
Do you mean the from address should be the IP address of the browser?

**Comment by kuksabong** [comment]
Yes, that's right.

**Comment by si458** [comment]
this already exists now in 1.1.20 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/a692f781-85d9-4190-83f8-a8785279b1e6)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/895a225d-475c-45c8-aca3-a4ecb8f00cf9)
it can show the browser ip and if you click the event, you can see more info like from and to ips
