### ISSUE TITLE
HTML symbol characters Checkmark and Cross, not correctly visible in Safari browser

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#283]
For example the checkmark and cross symbol used to indicate the the status of verified email address. Is a "scrambled" character in Safari browser.
My experience to use a checkmark or cross in all browser it is better to use a different one.

Example:
```
if (serverinfo.emailcheck) { everify = ((user.emailVerified == true)?'<b style=color:green;cursor:pointer title="Email is verified">&#x1F5F8</b> ':'<b style=color:red;cursor:pointer title="Email not verified">&#x1F5F4</b> '); }

Replace &#x1F5F8 into &#x2713;
&#x1F5F4 into &#x2717;
```
For the correct html code the ; is required!

Example picture of the symbols shown in Safari browser:
![image](https://user-images.githubusercontent.com/5203309/59115070-c4910600-8948-11e9-879f-770a77c7410e.png)

**Comment by Ylianst** [comment]
Thanks! Fixed it. It will be in MeshCentral v0.3.6-f when I publish it.

**Comment by hunter-nl** [comment]
Yes, fixed. Thanks!
