### ISSUE TITLE
Moving to a new server

### ISSUE THREAD

**Issue by BeluRoja** [Ylianst/MeshCentral#2832]
A customer implemented AMT with MESH and they are about to change MESH to a new server because the current implementation shares space with another software infraestructure and they want to separate. If they do that, the devices already implemented will have to get a new agent with the new Mesh server, correct? or is there a way to move the server without having to install new agents?

**Comment by Ylianst** [comment]
Hi. Are you keeping the same server DNS name? If so, that should not be a problem. Just setup a copy of MeshCentral and the new server with a copy of "meshcentral-data" and if you are using a database like MongoDB, make sure to also copy the database. Once done, run the new server and access it using the IP address, make sure the same accounts are present and working, etc. if the new server looks good, switch the DNS name to point to the new IP address, wait 30 minutes or more and stop MeshCentral on the old server. You should see agents connect to the new server.

This assumes you are not changing DNS name and the new server port numbers are same as the old server. I have done this a few times myself, no problem.
