### ISSUE TITLE
(Low priority) add some space

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#2834]
could you make some more space between button, when connected to an client computer (disconnect) connected. It is also when the connection is going to be made
Button text Dutch (verbreken) verbonden
MC Version 0.8.69
![mesh spacer](https://user-images.githubusercontent.com/58996467/124101393-99ae0900-da5f-11eb-8b60-9119bd622407.jpg) ![image](https://user-images.githubusercontent.com/58996467/124101823-0aedbc00-da60-11eb-9a8f-22024ef94b70.png)

![image](https://user-images.githubusercontent.com/58996467/124101956-31135c00-da60-11eb-8d23-3c9dc622948f.png)

**Comment by nzalev** [comment]
Interestingly, the spacing on mine is fine:
![Screenshot from 2021-07-01 07-58-38](https://user-images.githubusercontent.com/63608819/124121117-7f196700-da42-11eb-83cc-57846d967c92.png)
![Screenshot from 2021-07-01 08-00-02](https://user-images.githubusercontent.com/63608819/124121125-817bc100-da42-11eb-9009-5df3602fae72.png)

**Comment by petervanv** [comment]
I tested it on google chrome and micirsoft edge, same results

**Comment by Ylianst** [comment]
That is interesting. I just tried many different languages and browser and I can't replicate this. I will look at the code and see if I can put the same spacing in a different way.

**Comment by petervanv** [comment]
i noticed that it is fixed in the past time.......... so closing
