### ISSUE TITLE
Saving computer list and Load computer list

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2837]
It would be nice to have a feature that allows us to save and load the lists incase the server goes down, which we can load and save into MeshCommander. Also, be able to select the group to be placed in or create if not present.

**Comment by Ylianst** [comment]
Is this request only for the Intel AMT only agent-less device group type?

**Comment by MCJohnB** [comment]
Yes

Sent from my iPhone

On Jul 1, 2021, at 11:31 AM, Ylian Saint-Hilaire ***@***.***> wrote:

﻿

Is this request only for the Intel AMT only agent-less device group type?

**Comment by Ylianst** [comment]
Added saving the device list when clicking on a Intel AMT device group. This will be in v0.8.70.

![image](https://user-images.githubusercontent.com/1319013/124189833-2ebbfc80-da76-11eb-914d-38a410e3da14.png)

**Comment by MCJohnB** [comment]
Thank you very much...

**Comment by Ylianst** [comment]
MeshCentral v0.8.72 now has both import and export of Intel AMT device. Let me know if that works.

![MC2-AmtDeviceImportExport](https://user-images.githubusercontent.com/1319013/124394912-59949380-dcb6-11eb-9f3e-d829db619b12.png)

**Comment by MCJohnB** [comment]
Thank you very much.  I will let you know how it works later in the week.  One question, how do I know where LAN and/or Hybrid mode is located.  I am trying to get to know MeshCentral better and all it's features.

**Comment by Ylianst** [comment]
There is a [video on MeshCentral LAN/WAN modes here](https://www.youtube.com/watch?v=gx5Fh3pQOns). When you start manually MeshCentral, you see the mode here:

```
>node meshcentral --user admin
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.8.73, Hybrid (LAN + WAN) mode.                    <---------------------
MeshCentral Intel(R) AMT server running on central.mesh.meshcentral.com:4433.
MeshCentral HTTPS server running on central.mesh.meshcentral.com:443.
```
