### ISSUE TITLE
Groups created by different users

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2839]
My users can create groups, but I cant see the groups they create or even the computers they add to them until they add me to the group, this is causing some small issues when it comes to supporting the end user, at times we unintentionaly forget to add someone to a new group and we get stuck

I like to set the default to public groups, and if needed it set the group to private or any other setting if needed or if the user has the rights to do it.

There are almost 30 device groups on my server, but I only see 7 with my user.

**Comment by Ylianst** [comment]
In domain section of config.json, add:

```
    "ManageAllDeviceGroups": [ "user//admin" ]
```

You need to put your userid and the userid must also be a site administrator. After that, restart the server and you will see all device groups.
