### ISSUE TITLE
Create deleted user again will restore partly old user.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#284]
When I delete an user. And create a new user with same name/email address. Then no email verification will be sent (option is also not available). So this user can not be activated as it is still waiting for confirmation.
And the events of the old deleted user is visible to this new user account.
So delete user action will not completely delete everything of the old user account..

**Comment by Ylianst** [comment]
That is not good.

**Comment by Ylianst** [comment]
I did a bit of testing on this and can't find the problem. If you are in "LAN Mode" or the "SMTP" settings are not set, the server should not offer e-mail verification. Once an account is created, you can edit the account and check the option to "verified" only is the server can offer email verification. I suspect that between server updates things may have changed and the email verification system was not enabled or something.

Can you double check? Maybe I am missing something.

**Comment by hunter-nl** [comment]
SMTP is configured. With a brand new user account, then it is working fine. But when you delete an user and create a new user with same name and email address, then email verification is not sent. And status of user is "not verified".
Also the events of the previously deleted user account are again visible for the new account.
I've rebuild the system completely with latest version (no upgrade). And I get the same behaviour.
I use Mongodb.

**Comment by hunter-nl** [comment]
This is still a bug.
When user gets deleted, and created again with same name/email address, everything has been cleared for the user except the events log of the old user. New user can see old events.

**Comment by hunter-nl** [comment]
Any progress on this bug? My auditors do not like old events from previously deleted account being visible in the new account when new user gets assigned same email address of old deleted user.
