### ISSUE TITLE
Edited Description / Nickname Computers

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2840]
I like to see the edited nickname of a computer regardless of who edited by default. Currently the only way to see the edited name is via the tooltip or by going into the computer description first. How can I change that?

**Comment by Ylianst** [comment]
You can click on a computer and click on the name to change the server side name for that device.

![image](https://user-images.githubusercontent.com/1319013/124198867-764a8480-da86-11eb-8aa9-51510ca23f65.png)
