### ISSUE TITLE
Make dialog boxes movable

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2841]
Currently there is no way to move the smaller dialog boxes move within the interface, and I've ran into situations where either the contents where below the screen and I could not click the save/ok button, or even they were on top of some text I wanted to read to double check (Like a user email address) and I had to cancel or somehow increase the screen area

**Comment by Ylianst** [comment]
Made it movable, will be in MeshCentral v0.8.71.

**Comment by Ylianst** [comment]
Published.

![MC2-DialogMove](https://user-images.githubusercontent.com/1319013/124338383-8df43c80-db5c-11eb-8dfc-b79a5dc86309.png)

**Comment by MailYouLater** [comment]
WFM
