### ISSUE TITLE
Put all blue Icons on the same row

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2842]
Currently there are 8 icons, 3 blue and 1 gray on top and 3 gray and one blue on the bottom.

**Comment by Ylianst** [comment]
No idea what you referring to. Please provide a screen shot.

**Comment by rodrigolzd** [comment]
![chrome_1aR3nFo7Ru](https://user-images.githubusercontent.com/4949495/124200121-ed920f80-daaa-11eb-9ac7-cee2f709969d.png)


This, not at all a priority, just a bit more organized.

**Comment by rodrigolzd** [comment]
I think this would be a better order 

![chrome_1aR3nFo7Ru](https://user-images.githubusercontent.com/4949495/124200449-c5ef7700-daab-11eb-9d08-7bead3100e3a.png)
