### ISSUE TITLE
Add Server Blue Icon

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2843]
I was using the standalone computer icon (I assume that's what it is) and the icon is actually gray, so when it's offline, it's just fainted out, making it harder to understand if it's online or not
![chrome_1aR3nFo7Ru](https://user-images.githubusercontent.com/4949495/124197530-1d3e1900-daa5-11eb-8ae8-3de2fe7335eb.png)

**Comment by Ylianst** [comment]
Not clear what this request is.

**Comment by MailYouLater** [comment]
@Ylianst: What rodrigolzd wants here is for the icons that have less color to be given a more noticeable splash of color somewhere so that the difference between when they are colored and when they become monochrome is more obvious.
