### ISSUE TITLE
Link to changelog

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2844]
Add a link to the changelog in the update window. We can see that there is an update, but not what is changed.

**Comment by Ylianst** [comment]
No idea what this request is about. Changelog of what?

**Comment by rodrigolzd** [comment]
Changelog of the versions of meshcentral. whatever was changed by the corresponding version of meshserver. I just checked the server for updates and there is one, however, I have no idea of what is going to be changed in the server. So, how do I see whats changed in the new version.

![image](https://user-images.githubusercontent.com/4949495/124200741-7cebf280-daac-11eb-8d35-87f4ab90fe24.png)

**Comment by Ylianst** [comment]
There is lots going on and no format change log, but you can look at the [GitHub commit log here](https://github.com/Ylianst/MeshCentral/commits/master).
