### ISSUE TITLE
Make config files accesssible via web interface.

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2845]
While having every feature available on the interface may not be feasible, maybe having a simple text only editor that can access config files would greatly improve the speed of debugging and server maintenance. One example would be to edit the main config file to enable the email configuration and lets-encrypt.  One example of this kind of setup is Webmin, where you get a GUI, but also a button to edit the config file directly.

**Comment by Ylianst** [comment]
The config.json file contains secrets, encryption keys, etc. So, there are security concerns with this. If you can provide more details as to exactly what you want / screenshot, that would be great. This request is too generic.
