### ISSUE TITLE
System Update Notification in the interface

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2848]
Right now, we have to manually look for the update to know if there is an update available. it would be nice if admins would be notified about it without having to check for it. Perhaps having a scheduled check would be nice to have.

**Comment by Ylianst** [comment]
Duplicate.

**Comment by MailYouLater** [comment]
Specifically this is a duplicate of #2748.
It's generally a good idea to mention the issue number that's being used to track the specified issue so that people who are looking at an issue closed as a duplicate know where to go for more up-to-date information.
