### ISSUE TITLE
Feature request: Make date/time format configurable.

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#285]
For example: instead of 6/7/2019 03:33 PM
2019-06-07 15:33
It is fine if it can be configured in config.json with:
"dateformat": "%Y-%m-%d"
"timeformat":"%H:%M"

**Comment by Ylianst** [comment]
On this topic, the web application should be formatting time and date for the user's local area. The setting should be in the OS. If it's not the case, let me know where on the web page it's not correct.

**Comment by hunter-nl** [comment]
I'm using Safari on OSX. My language and region settings on OSX are correct for my date/time format. But MC will shows "english" style. And everywhere in the web application where date/time is shown is in "wrong" format.
I tried it also in Chrome and on Windows with Chorme. All shows wrong format.

**Comment by Ylianst** [comment]
Ok. I will work on fixing this. The fix will not have me ask for the date format, rather the OS/browser date format should always be automatically applied.

**Comment by Ylianst** [comment]
After investigation, the date/time format used by the browser is related to the language preference of the browser, not the OS settings. I just published MeshCentral v0.3.6-j and you can set the "locale" in the URL. For example: https://myserver?locale=en-GB. I tried changing my browser language settings and indeed, it does work but you can specify the "locale=xxx" in the URL to override the browser's default locale. Given this info, is the behavior ok?

![MC2-LocaleArg](https://user-images.githubusercontent.com/1319013/59297696-b4757100-8c3d-11e9-805b-11137e757efd.png)

**Comment by hunter-nl** [comment]
Based on browser locale is acts wrong. When I set it manually with ?locale=nl-nl then it is fine. It would be nice if it is configurable option by user in the user account settings.

**Comment by Ylianst** [comment]
I am not a Mac person, but if you click on the Apple on the upper left, then "System Preferences...", "Languages & Region". I added french and placed it first in the list of preferred languages and refreshed the MeshCentral page on Safari and the date changed. This is the proper way to set this up, I don't think it's proper to have each web site have it's own settings for this.

**Comment by hunter-nl** [comment]
Why not? I have many web applications where I can setup the language/locale per user, independent from the OS.
My OSX system is English language and Region is The Netherlands (Dutch). The date/time format is for The Netherlands.

**Comment by Ylianst** [comment]
FYI. With the latest MeshCentral v0.3.6-m, if you put a URL argument on the login page, it will be kept as you login. So you can bookmark "https://myserver?locale=en-GB" then login and have the local be active. Before this version you have to login first, put the locale argument and hit refresh. I did not just do it for this issue, I figured it would be useful in general.

**Comment by hunter-nl** [comment]
Idea: Maybe a possibility to set locale in config file for main and/or extra domain(s), as a default locale. Users forget to use ?locale=en-GB when they are at remote locations and do not have their bookmarks available.

**Comment by hunter-nl** [comment]
Or let user select three own locale in user account properties. When chosen add automatically ?local=xx-xx to the url after login.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.8-p with a new "Localization Settings" in "My Account". Allows you to override the default browser value. Feedback appreciated.

![MC2-Localization](https://user-images.githubusercontent.com/1319013/61983606-e0627100-afb5-11e9-99ee-7b5625f3c310.png)

**Comment by hunter-nl** [comment]
Yes, This is working great! Thanks again!
