### ISSUE TITLE
Drop/kick Connection Button

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2850]
I have experienced at random times, a disconnect from remote pc but the server still sees an active connection. So far, the only way I've been able to drop this connection is by restarting the service or server.  It would be nice, as an admin or alike to be terminate any user connection.

**Comment by Ylianst** [comment]
Not sure if your talking about agent or user connection, you mention both?

![image](https://user-images.githubusercontent.com/1319013/124200533-72b8fc80-da8a-11eb-9998-79028cadae2d.png)

For users, just lock the account and unlock it again. The disconnects all their sessions.

**Comment by rodrigolzd** [comment]
Sometimes the blue icon indicating the connection is still there and when I connected to the desktop it shows that there are now 2 desktop connections. I thought it was possible to drop just that part of the connection, but not the reset the agent. So perhaps a soft disconnect button would be enough. but I think the location of the button might help to get this done faster and easier.

![image](https://user-images.githubusercontent.com/4949495/124209897-d231ff00-dac0-11eb-8f0c-f7e49977b568.png)
