### ISSUE TITLE
Add Ctrl+Shift+Esc to desktop Send button options

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2853]
This brings up the windows Task Manager. Can be helpful at times.

**Comment by Ylianst** [comment]
You can right click the area in read below, select "Customize" and setup Ctrl-Shift-ESC. That key combo will not work in the browser.

![image](https://user-images.githubusercontent.com/1319013/124200408-1f46ae80-da8a-11eb-8eb4-5a4858198734.png)

**Comment by rodrigolzd** [comment]
I had no idea such option to "Customize" existed.
