### ISSUE TITLE
MeshCentral Router blocks files after transfer

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#2854]
When I do a  file-transfer via Meshcentral-Router/remote-file then file is still looked after the transfer is finished. When I close the connection the file is still looked.
When I close the Meshcentral-Router program than the file is unlooked.

(it locks like a bug - that something like "fclose" is missing in the code)

**Comment by Ylianst** [comment]
Oh dear. I am testing the MeshCentral Router this morning, I will also test this.

**Comment by Ylianst** [comment]
Are you doing a download from the remote to local? Or upload local to remote? Is the locked file on the local side or remote side? - Thanks.

**Comment by Ylianst** [comment]
Ok, I found that if you upload a file from local to remote, the local file did stay open. Just fixed that. Will be in MeshCentral v0.8.71.

**Comment by schanir** [comment]
Hi,
Thangs a Lot!
Best regards
Ralf 
Freitag, 02 Juli 2021, 06:56nachm. +02:00 von Ylian Saint-Hilaire  ***@***.*** :

**Comment by Ylianst** [comment]
You can get the latest [MeshCentral Router here right now](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) if you want to try it.

I also added right-click context menu on the left side.

![image](https://user-images.githubusercontent.com/1319013/124322217-ea8f3180-db33-11eb-9a43-e071dcdaf1da.png)

**Comment by schanir** [comment]
Ok many thanks. 
It would be nice to have a asking dialog befor the Software overwrite an exsisting file.  
Nice work so far!
Bye
Ralf 
Freitag, 02 Juli 2021, 09:49nachm. +02:00 von Ylian Saint-Hilaire  ***@***.*** :

**Comment by Ylianst** [comment]
Please test and close this issue if it works. For other requests, please open a new issue. Thanks.
