### ISSUE TITLE
Feature request: allow exclusions to force2factor in config.json

### ISSUE THREAD

**Issue by bbrendon** [Ylianst/MeshCentral#2859]
Use case: I want the API account to NOT have 2fa but I want everything else to require 2fa.

**Comment by TotallyNotElite** [comment]
And... Why exactly can't you use login tokens for that...?

**Comment by Ylianst** [comment]
Hi. So, I don't think this request is a wise one as there are better security options than removing 2FA for an account. First, you can skip 2FA based on the incoming IP address right now. In the domain section of the config.json, you can put a "skip2factor" in "passwordrequirements" like this: 

```
      "PasswordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "force2factor": true,
        "skip2factor": "127.0.0.1,192.168.3.0/24"
      }
```

When a connection is coming from one of the excluded IP address, two-factor authentication is skipped.

Second, as @TotallyNotElite mentioned, if you are using an account for API access, you should use a login token. You can see a [YouTube video on this here.](https://www.youtube.com/watch?v=888ylAKDeP4) If you have a recent version of MeshCentral, go in "My Account" and click "Create Login Token". You will get a special username and password that you can give to MeshCtrl.js or any other code to have to access the API. The benefit here is that this token can't do any account operations. So, it can't change your password, or delete you account, etc. You can also revoke it at anytime.

![image](https://user-images.githubusercontent.com/1319013/124394172-0f5de300-dcb3-11eb-91ee-c4f212840e0c.png)

![image](https://user-images.githubusercontent.com/1319013/124394175-138a0080-dcb3-11eb-8bd5-3d230f861bf4.png)

If you have many tools using the MeshCentral API, you can name each login token with their usage, so you can easily revoke the right one if needed.

Lastly, if you find two-factor authentication annoying. Search for "Fido USB Key" on Amazon or eBay and get one for 20$ and keep it connected to your computer. You can 2FA with the press of a button and it's very secure. See the [YouTube video demonstration here](https://www.youtube.com/watch?v=luLZKcma9l0&t=368s).

Hope that helps,
Ylian

**Comment by bbrendon** [comment]
@Ylianst thank you very much for the detailed explanation!
