### ISSUE TITLE
File-Tranfer functions wishes/request

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#2861]
Hi,

I use Meshcentral on a daily basis on multible computers. It is a good tool! But a few things are still missing...
It would be nice to have this functions in the "Meshcentral-Router/File-Transfer".

1) warning if the destinations file allready exsists. Ask to replease this file or all files or skip or skip all.
1a) check if both files are identical - so no transfer is nessessery --> skip file

2) show the transfer speed (and the remaining time to finish the transfer)

3) Add an "Abort" Button. So that it is possible to stop the current transfer. Very important.

4) may be a automatic file compression befor transfer - and automatic decompress (to incrase speed)

Many Thanks so far!

**Comment by Ylianst** [comment]
For 3, there is a "Cancel" button on the file transfer. Is there some else that is needed?

![image](https://user-images.githubusercontent.com/1319013/124512754-ff670180-dd8d-11eb-8356-16e4bf14d38a.png)

**Comment by Ylianst** [comment]
FYI. Next version of MeshCentral will save the local (left side) path to registry, so when you open the file transfer again, it will go back to the old path.

**Comment by Ylianst** [comment]
Added overwrite check for both upload and downloads. Will be in next version.

![image](https://user-images.githubusercontent.com/1319013/124517565-224ae300-dd99-11eb-98d5-7ab3371b8d8f.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.74 with some improvements, but just added the transfer rate and estimated time. That will be in v0.8.75.

![MC2-MeshCentralRouterFileImprovements](https://user-images.githubusercontent.com/1319013/124524362-a740f700-ddaf-11eb-82ba-feb0f94023b3.png)

**Comment by schanir** [comment]
> 
> 
> For 3, there is a "Cancel" button on the file transfer. Is there some else that is needed?
> 
> ![image](https://user-images.githubusercontent.com/1319013/124512754-ff670180-dd8d-11eb-8356-16e4bf14d38a.png)
> 
> For 4. If you enable WebSocket compression, then the transfer will get compressed if possible. You can add these to the "settings" section of the config.json:
> 
> ```
> "Compression": true,
> "WsCompression": true,
> "AgentWsCompression": true,
> ```
> 
> MeshCentral Router does support WebSocket compression for both files and remote desktop when enabled on the server.

Yes I mean this "Cancel" button. May be I have overlooked it...

**Comment by schanir** [comment]
> 
> 
> Published MeshCentral v0.8.74 with some improvements, but just added the transfer rate and estimated time. That will be in v0.8.75.
> 
> ![MC2-MeshCentralRouterFileImprovements](https://user-images.githubusercontent.com/1319013/124524362-a740f700-ddaf-11eb-82ba-feb0f94023b3.png)

Looks great! Can not wait to test it....

Bye the way - is it at the emoment only possible transfer files (no folders)? Or I am to stupid/blind to find it?

Many thanks so far!!

**Comment by Ylianst** [comment]
Thanks. There is no folder transfer feature right now. Of course, that would be a different request :)

**Comment by schanir** [comment]
when do you release the v0.8.75 ?
I'm ready to test it (stress test it)  ;-)

**Comment by Ylianst** [comment]
You can get the latest [MeshCentral Router here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Let me know how it goes. I will work on #2873 now and release a new MeshCentral later today.

**Comment by schanir** [comment]
Hi,

I have tested the tranferfunction very much. It locks good - but...
When I upload a file and the file already existis --> then comes the question dialog if I want to overwrite it then I press "OK" and that is it. But in my case the destination file was blocked (he can not overwrite it) but it give me no feedback about this. So I am still thinking the trasfer was successful - but it was not! 

The transfer speed and the remaining time to finish the transfer works great!  :-)

**Comment by Ylianst** [comment]
Next version of MeshCentral Router will how keep file selections even when the control is out of focus.

![image](https://user-images.githubusercontent.com/1319013/125114674-1e6fd700-e09f-11eb-9d22-21084828a423.png)

**Comment by OutbackMatt** [comment]
My wish list to add to this excellent enhancement

I'd like to run a command (probably a cron) that could download all files in a particular folder from a particular client machine, resuming on disconnect, until complete. Multiple large 2GB+ files.

Either replace or skip duplicate files (set in cron command)
Perhaps purge local destination directory of files missing from source

For inspiration something like what Windows robocopy achieves, except over the mesh 
(I can manually download and upload large files quite quickly via Mesh, and with less drop outs. The file  transfer protocol that you use seems really robust and perhaps that it is the tunneled connection that protects this traffic from port scanners. Using WebDAV or FTPS just gives me grief, when downloading via Mesh files, large files just download)
