### ISSUE TITLE
Automatic Clipboard "issue"

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#2862]
Hi,

The automatic clipboard works as well from admin's computer to the client's computer.

Is it possible to have the same on the client' side ? if not, is it possible to show the clipboard button anyway so that I can get the remote clipboard ? 

Thank you.

**Comment by si458** [comment]
you can use the clipboard button to get and set manually
you can also use the 'automatic clipboard' under 'settings' now
but you must use chrome/edge as firefox lets you download the remote clipboard but wont wont let you set the remote clipboard
