### ISSUE TITLE
Fix issues related to WebRTC

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2863]
Dear Ylian,

Can you fix the known issues related to WebRTC.

**Comment by Ylianst** [comment]
This had been on Bryan's todo list for over two year. I agree, I would like to see this fixed.

**Comment by si458** [comment]
plz see update here, https://github.com/Ylianst/MeshCentral/issues/3463#issuecomment-2326767201
so im going to close this issue and you can follow there
