### ISSUE TITLE
dont see checkbox for "automatic clipboard"

### ISSUE THREAD

**Issue by q16marvin** [Ylianst/MeshCentral#2865]
hi,

maybe im to stupid, but on my side it looks like this:

![grafik](https://user-images.githubusercontent.com/19844709/124583747-b37e9000-de53-11eb-9f82-218bc0236955.png)

and in source:

![grafik](https://user-images.githubusercontent.com/19844709/124583804-c6916000-de53-11eb-9b57-bd64790b2415.png)

what i need to do to activate this function?

**Comment by Ylianst** [comment]
It's only available on supported browsers. Chrome will support is, FireFox does not (for now). Let me know if that is the issue.
