### ISSUE TITLE
Refactoring meshuser

### ISSUE THREAD

**Issue by nzalev** [Ylianst/MeshCentral#2868]
This is an issue purely to discuss code. I was reading #1321 last night and was encouraged to offer some reorganization. 

meshuser is a perfect starting place for this. Currently, it is a 5000 line switch statement, with a nested switch statement to handle console commands. Using some form of lookup table is a cleaner way of doing this that's used in a lot of other large projects.

I will give you an example

```javascript
    var commands = {};
    commands['intersession'] = intersessionCommand;
    commands['authcookie'] = authcookieCommand;
    ....


    function intersessionCommand( ... ) { ... }
    function authcookieCommand( ... ) { ... }

    function processWebSocketData(msg) {
        ...

        try {
            commands[cmd]( ... );
        } catch (e) {
            if (commands[cmd] == null)
                console.log('Command not found');
                // Handle command not found here
            else
                console.log(e);
                // Generalized error handling
                // Can re-throw
        }
    }
```

The main reason to structure it this way is readability and navigability (maintainability). Currently, finding the command you want can mean constantly ctrl+f'ing or scrolling through thousands of lines.

Having the table (in js's case an associative array) of all commands and their handlers at the top gives you the ability to see all of them at a glance, and most IDE's will allow you to ctrl+click the function name to jump directly to the handler. From a philosophical view, it also separates out responsibility into more suitable chunks.

I do not want to refactor the whole thing to find out the PR will not be accepted, so I am making this issue first to guage what you think.

**Comment by Ylianst** [comment]
I am ok with this. Let me refactor one switch statement and see how it goes.

**Comment by nzalev** [comment]
Before you start, I will put in a PR and see what you think. I did serverconsole as a test. @Ylianst

**Comment by Ylianst** [comment]
Arg. I was just doing my own refactor of this very same thing. Ok, now I have to figure out what to do.

**Comment by nzalev** [comment]
> Arg. I was just doing my own refactor of this very same thing. Ok, now I have to figure out what to do.

I am surprised at how quickly you finished!

**Comment by Ylianst** [comment]
Ok, that was not good. We did the same thing at the same time. My version is current, I am not going to touch it anymore. Can you take a look at it and if you don't like it, re-submit your version and I will accept it.

I would like all functions used for user commands to all start with the same prefix... like "serverUserCommandxxxxx" instead of starting with the command name "xxxxServerUserCommand'. If you order the function names, they order well. Also, I used the command table for the help command.

**Comment by nzalev** [comment]
I am looking it over now, I will re-branch off master.

Presently, both tables are in, and each command has two handlers. 

I saw you adjusted the help command to pull from the command table. I was going to make that same modification in another pull request.

I used a data object to pass in, including the result to avoid having to declare `var r = '';` and `return r;` in every handler. This cuts  out almost 100 lines alone.

I like the idea of putting the help message in the same table - that's not something I had thought of. It is only applicable to the console commands, but I think these should be in their own table.

**Comment by Ylianst** [comment]
Nice. I will let you make the changes.

**Comment by nzalev** [comment]
> Nice. I will let you make the changes.
Sure. I will finish serverconsole today.

My goal is to do all of meshuser, but that will take more time. I can work out a way for the two methods to co-exist while doing the larger switch statement.

**Comment by Ylianst** [comment]
Thanks for the pull request. Looks great. Just merged it. Apologies again for the code trashing.

**Comment by nzalev** [comment]
> Thanks for the pull request. Looks great. Just merged it. Apologies again for the code trashing.

Not a big deal, fairly easy to fix :). Plus, I think there are some good improvements combining the two.

**Comment by nzalev** [comment]
I can start on the rest of meshuser on or after this weekend.

I will start with a couple that I am familiar with and can test easily (lastconnect for example). I will also come up with a method for the function based handlers and switch statements to coexist, so it doesn't all have to be done at once.
