### ISSUE TITLE
User consent

### ISSUE THREAD

**Issue by Philippe687** [Ylianst/MeshCentral#2869]
Hello all,
what a amazing product ! Thank you Mister SAINT-HILAIRE.

After installing MeshCentral on an Ubuntu 18.04 and create the first user i joined my first agent from my laptot for testing. On remote desktop a user consent is requested.

In the rights management window all the boxes are checked by default and I don't have control over them. Have I missed something?
![Capture](https://user-images.githubusercontent.com/29157130/124824167-bac1ad00-dfbd-11eb-9964-4e9ff0fc5a66.png)

**Comment by Ylianst** [comment]
In the domain section of your config.json, take a look for this section:

```
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": false,
        "terminalprompt": false,
        "fileprompt": false,
        "desktopprivacybar": false
      },
```

This should control domain-wide user consent policy. When true, the policy is enabled and can't be disabled by any user in that domain. If this is not the problem, send over your config.json with XXXXX for any private data.

**Comment by Philippe687** [comment]
Hello Ylian,
thank you for your answer. I've changed true to false and that's it :) .
Now I can untick the check box.
![Capture 2](https://user-images.githubusercontent.com/29157130/124876202-7a8e1900-e015-11eb-8875-87a5112aacf3.png)

I unchecked all the boxes, but despite that, my agent continues to ask for consent. I think I have a problem with the agent because when I download it and install it it puts me "local" in the server address; I have to go to the Compagnyagent.msh file to manually enter the server address "MeshServer = wss: //control.clicandpublish.com/agent.ashx".

Thank you again for your help.

Best regards,

**Comment by nzalev** [comment]
>when I download it and install it it puts me "local" in the server address; I have to go to the Compagnyagent.msh file to manually enter the server address "MeshServer = wss: //control.clicandpublish.com/agent.ashx".

This occurs when the server is in LAN mode. You need to set `"cert": "control.clicandpublish.com"` and `"wanonly": true` in your config.json.

**Comment by Ylianst** [comment]
For details on what is LAN and WAN modes, you can look [at this YouTube video](https://www.youtube.com/watch?v=gx5Fh3pQOns). By default in LAN mode, agents will multicast to find the server. As @nzalev mentioned, once you set a server name in the config.json, the server will use that DNS name to tell the agents to connect back to the server.

So, set the `cert` name in the settings sections of the config.json, restart your server, re-download and install the agent.

**Comment by Ylianst** [comment]
You may also have to uncheck the consent boxes for the device group.

![image](https://user-images.githubusercontent.com/1319013/124980545-616f7300-dfe9-11eb-9739-54054129b074.png)

**Comment by Philippe687** [comment]
Thank you nzalev and Ylian.
The wan mode is on and the agent downloaded is set correctly. But it still ask the user consent for a remote desktop.
![image](https://user-images.githubusercontent.com/29157130/124980520-384df180-e080-11eb-99df-399d73ec7572.png)

Is it possible to cancel this userconsent ? 

Best regards,

**Comment by Ylianst** [comment]
Check that the device, device group, user and if needed user group all have user consent turned off.

**Comment by Philippe687** [comment]
GREAT !!!
The group user had user consent turned on !!!

Thank you Ylian. And "BRAVO" again for your awesome job.
