### ISSUE TITLE
Comment: visudo and meshinstall.sh

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2870]
When installing an agent on a remote system, and `meshinstall.sh` has been added to that systems specific user's `visudo` entry (`/etc/sudoers.d/username`), the meshinstall.sh script isn't able to be run with the `-E` switch, the system returning the following error message:
```
sudo: sorry, you are not allowed to preserve the environment
```

I don't believe this is a bug with MC2 at all, just an observation. The installer runs perfectly when the `-E` switch is removed. 

From what I can tell at this point, the system operates without flaw but wondered if @Ylianst or @krayon007 have any comments as to whether or not they forsee issues in dropping the environment switch (considering the installer is called with `sudo`)? I'd be interested to know what environment settings warranted the `-E` switch in the first place, so that I can potentially preserve them within the sudoers file itself, if warranted?

**Comment by krayon007** [comment]
At install time, the only environment variable that would be relevant is related to proxy detection. But even then, the agent will try a few things to try to determine proxy settings, such as apt config, etc.

**Comment by D4V3M0NK** [comment]
Great, thanks Bryan.
