### ISSUE TITLE
Meshcentral

### ISSUE THREAD

**Issue by spirelab** [Ylianst/MeshCentral#2872]
Hi All,

i am getting  "waiting for user to grant access" When i freshly installed and ran the server, i didn't have this as i recall, but now i am getting this, i dont need this as i am installing it on my servers and want to access without user input, how do i go about getting this done without user input

Best
Imran

**Comment by VINISHVV** [comment]
@spirelab 

You can enable /disable the user consent for individual user/user group / device /device group / Domain etc.... .

Please refer the [here ](https://github.com/Ylianst/MeshCentral/issues/2816#issuecomment-868694404) for more information.

**Comment by spirelab** [comment]
yes thank i was doing an random search now found the user consent thanks :)

**Comment by Ylianst** [comment]
FYI. When opening an issue, please put a proper title.
