### ISSUE TITLE
BUG - MechRouter Is not using the domain location when connecting with meshrelay.ashx

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2873]
It looks like I'm having issues with meshrelay.ashx because the requests are going to the "/" directory location instead of the "/remote/" directory location. So the uri should look like this "/remote/meshrelay.ashx?xxxxxx". Is there any way to get meshrelay.ashx available in the "/remote/" location?

**Comment by LPJon** [comment]
@Ylianst I think I have isolated this issue to a similar issue [here](https://github.com/Ylianst/MeshCentral/issues/239).
MeshRouter is not using the domain location setup in the config.json. Instead it is accessing it through the root domain location. This is why the desktop and terminal tabs work perfectly (Because the agent is using the domain location) but MeshRouter can't setup a connection to the server unless there is domain root access. I need MeshRouter to use the domain location in the config.json to perform it's meshrelay.ashx connection. I'm hoping that is a lot clearer for what I'm asking.

Apache Logs:
```
<PRIVATE DOMAIN>:443 <PRIVATE IP> - - [08/Jul/2021:01:30:18 -0500] "GET /meshrelay.ashx?nodeid=node/<PRIVATE DOMAIN LOCATION>/<PRIVATE AUTH> HTTP/1.1" 404 511 "-" "-"
<PRIVATE DOMAIN>:443 <PRIVATE IP> - - [08/Jul/2021:01:30:17 -0500] "GET /<PRIVATE DOMAIN LOCATION>/control.ashx?<PRIVATE AUTH> HTTP/1.1" 200 11622 "-" "-"
```

As you can see, control.ashx is being accessed at the DOMAIN LOCATION, where as meshrelay.ashx is being accessed at the domain root. This is purely from a connection attempt with MeshRouter. Let me know if you want me to provide more config info for you.

**Comment by LPJon** [comment]
@Ylianst 
Steps to reproduce this issue.
1. Setup a reverse proxy for the domain location only. (Be sure not to include the "/" root location in the proxy)
2. Setup a simple location deployment in the MeshCentral config.json
3. Setup a test account at the domain location from step 2 above and add at test remote device.
4. Test "Desktop", "Terminal", "Files" (These should all work. If they don't your proxy isn't right yet)
5. Download MeshRouter from the new installation
6. Attempt any connection with MeshRouter to the test device. (Be sure to test both WAN and LAN hybrid mode and that you test a local device and a non local device.)

This connection from step 6 will hang and then eventually close. When looking at the apache error.log you will see where `/meshrelay.ashx` was used to attempt the connection instead of `/<location>/meshrelay.ashx` and was met with a 404 code.

Here is a sample reverse proxy config that I am using:
```
        SSLEngine on
        SSLCertificateFile <CERTIFICATE FILE PATH>
        SSLCertificateKeyFile <PRIVATE KEY FILE PATH>
        SSLCertificateChainFile <FULLCHAIN FILE PATH>

        SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown

    ProxyRequests On
    ProxyPreserveHost On
    SSLProxyEngine on
    SSLProxyCheckPeerCN Off
    SSLProxyCheckPeerExpire Off
<IfModule mod_proxy.c>
<VirtualHost *:443>
ServerName <DOMAIN NAME>
#=====================================================================================
#                        Location for Meshcentral Remote Server
#=====================================================================================
<Location /<LOCATION>/>
    SecRuleEngine On
    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade$ [NC]
    RewriteCond %{HTTP:Upgrade} websocket$ [NC]
    RewriteRule . wss://127.0.0.1:4430%{REQUEST_URI} [P]

    ProxyPass https://127.0.0.1:4430/<LOCATION>/
    ProxyPassReverse /<LOCATION>/
</Location>
#=====================================================================================
</VirtualHost>
</IfModule>
```

Of course you need to setup Meshcentral to use port 4430 and you need to change the `<LOCATION>` sections to the location you specified in the config.json. Also, don't forget the SSL Cert, Key, and Fullchain files that need to be specified.

**Comment by Ylianst** [comment]
Thank you for the full and details report. Working on this right now.

**Comment by Ylianst** [comment]
Your absolutely right, I see the same problem. Looks like it will required both MeshCentral Router and MeshCentral Server update. I found multiple issues once I got it setup, almost done with the fixes.

**Comment by LPJon** [comment]
> 
> 
> Thank you for the full and details report. Working on this right now.

I also forgot to mention that there is no account setup on the "/" (root) domain location. 

Great to hear you were able to reproduce it! I'm watching very closely as I have client system I'm trying to get setup where this issue presented itself. Can't wait to test it! Thanks again for all your hard work and fast responses. They are invaluable and so very much appreciated.

**Comment by Ylianst** [comment]
I just submitted a fix for this. Let me test MeshCentral Assistant to see if I have the same issues in that tool and I will publish a new version of MeshCentral right away.

**Comment by Ylianst** [comment]
Ok, found issues in MeshCentral Assistant too... fixing that now.

**Comment by Ylianst** [comment]
MeshCentral v0.8.75 is out with many fixes for multi-domain servers. Let me know if it works. You will need to update both MeshCentral Server and MeshCentral Router.

**Comment by LPJon** [comment]
> 
> 
> MeshCentral v0.8.75 is out with many fixes for multi-domain servers. Let me know if it works. You will need to update both MeshCentral Server and MeshCentral Router.

Still waiting for the commit to his the server. I will post back here as soon as it does.....

**Comment by LPJon** [comment]
Okay.....so when I login to MeshRouter manually I am able to connect to the device with "map" and "relay map". When I use the links in MeshCentral server such as the "SSH" or "SCP" links, it still uses the `/meshrelay.ashx?xxx` method without using the location. So at least now MeshRouter will work when I manually login to it which is a step forward. 

Automatic login and relay map setup through MeshCentral Server is still not working though.

**Comment by LPJon** [comment]
@Ylianst Yup....100% confirmed. The link generation for the autologin feature between MeshCentral Server and MeshRouter when clicking on the "SSH", "SCP", or any "extralinks" does not include the domain location. Only when you login directly to MeshRouter does the "Map" and "Relay Map" functions work. Even when starting with the link from MeshCentral and then clicking on "Cancel Auto-Close" and then trying to create the map manually fails.

**Comment by LPJon** [comment]
Strangely while ssh or scp don't work....the desktop and files links inside MeshRouter do after the auto-login....

Steps to reproduce:
1. Use the SSH, SCP, or any other extralink in MeshCentral to auto deploy the MeshRouter tool
2. The connection should fail, when it does be sure to click on "Cancel Auto-Close"
3. Now switch to the "Devices" tab
4. Try to use "Remote Desktop" and "Remote Files" features.....they should work just fine
5. Now try to use "SSH" or "SCP". Agian, they will fail
6. Now click on logout
7. Then login directly with MeshRouter and perform step 5 again. Suddenly they work and you can establish a connection.

**Comment by LPJon** [comment]
Investigating a little further I found this in the MeshCentral Server Link to open MeshRouter.

`serverPublicNamePort="<PRIVATE DOMAIN>:443"`

Which does not include the location but there is a section with

`domain="<PRIVATE LOCATION>",domainUrl="/<PRIVATE LOCATION>/"`

Which seems to specify it. So I'm not sure why MeshRouter is not using this in it's request to MeshCentral Server ONLY when the auto-login feature is used.

**Comment by Ylianst** [comment]
Excellent. Nicely done.
