### ISSUE TITLE
Saving computer list and loading computer list at the Device Groups level.

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2876]
This will address the issue that i was trying to get across, however not succeeding, but with images it could help my cause better.  I want to thank you very much of the hard work you are doing.

If you can add those two buttons to save and load in the first image that would save the all of groups that solve my issue. 

![Device Groups level rev1](https://user-images.githubusercontent.com/83652365/124983012-722de200-e005-11eb-8907-51418d5fdad2.jpg)
![Group level rev1](https://user-images.githubusercontent.com/83652365/124983013-722de200-e005-11eb-9bb0-b3e9493c85fa.jpg)

Thank you

**Comment by Ylianst** [comment]
Next version of MeshCentral v0.8.76, you can save Intel AMT information for selected devices.

![image](https://user-images.githubusercontent.com/1319013/125112887-a7394380-e09c-11eb-8c65-f531de4abb27.png)

**Comment by MCJohnB** [comment]
Thank you very much!
Have a great day and a nice weekend!

**Comment by MCJohnB** [comment]
it works great thank you again!
