### ISSUE TITLE
BUG - MeshRouter only using domain location when logging into MeshRouter manually

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2877]
Similarly to issue #2873 MeshRouter is only using the domain location specified in the config.json when you login to MeshRouter directly. When using the "Mesh Central Router Links" MeshRouter is still not using the domain location for access to `meshrelay.ashx`.

Strangely while ssh or scp don't work....the desktop and files links inside MeshRouter do after the auto-login from "Mesh Central Router Links"....

Steps to reproduce: (Takes into account the setup referenced in the issue listed above)

1. Use the SSH, SCP, or any other "Mesh Central Router Links" in MeshCentral to auto deploy the MeshRouter tool
2. The connection should fail, when it does be sure to click on "Cancel Auto-Close"
3. Now switch to the "Devices" tab
4. Try to use "Remote Desktop" and "Remote Files" features.....they should work just fine
5. Now try to use "SSH" or "SCP". Agian, they will fail
6. Now click on logout
7. Then login directly with MeshRouter and perform step 5 again. Suddenly they work and you can establish a connection.

Investigating a little further I found this in the MeshCentral Server Link to open MeshRouter.

`serverPublicNamePort="<PRIVATE DOMAIN>:443"`

Which does not include the location but there is a section with

`domain="<PRIVATE LOCATION>",domainUrl="/<PRIVATE LOCATION>/"`

Which seems to specify it. So I'm not sure why MeshRouter is not using this in it's request to MeshCentral Server ONLY when the auto-login feature is used.

**Comment by Ylianst** [comment]
You are 100% right, I see the same problem. Working on it now.

**Comment by Ylianst** [comment]
Ok, this is a MeshCentral Router only fix. [I have a new version here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe), you can download and try it. Let me know if it works.

**Comment by LPJon** [comment]
Awesome! This fix is 100% working. Thanks again for your awesome hard work.

**Comment by Ylianst** [comment]
Nice! Thank you for reporting these with such details. Much appreciated.
