### ISSUE TITLE
MC Router is not working

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2878]
Hi !
When I connect the remote desktop through the MC Router, the MC Router does not work and there is no response as shown below.

![캡처](https://user-images.githubusercontent.com/6889244/125026812-46236700-e0c0-11eb-8e8e-43c6b03bc2b2.JPG)

**Comment by Ylianst** [comment]
Is this a new problem with the latest version of MeshCentral router? Did older versions use to work?

**Comment by vitko-bg** [comment]
Not sure, not in front of the PC but I think there is connect button, left hand side from Ctrl+Alt+Delete. Try to click on it.

**Comment by LPJon** [comment]
@kuksabong You are missing some important information.

What version of MeshRouter are you using? What is your version of MeshCentral Server? Did this just happen after an update? If so, from what version to what version? Have you tried using this feature before and it worked? If so, at what version of MeshRouter and MeshCentral did it work on? Is RDP enabled on the remote system you are trying to use it on?

**Comment by Ylianst** [comment]
I just tested MeshCentral Router in Korean and it worked for me. Without more information, not sure I can do anything else.

![image](https://user-images.githubusercontent.com/1319013/125132401-20df2a80-e0b9-11eb-87b2-a0c3f9587738.png)

**Comment by kuksabong** [comment]
Hi.
MC version is 0.8.77 and MC Router version is 1.8.7864.
I've tested the above issue on several Windows 10 versions.
In the case of Windows 10 Pro - 2004 [19041], MC Router worked normally.
However, in the case of Windows 10 Pro - 2009 [19043], I still couldn't access the remote desktop using the MC Router.

**Comment by LPJon** [comment]
Do you control these machines or do they belong to someone else?

**Comment by Ylianst** [comment]
I am not sure what is going on. Does the remote desktop on the web site work but remote desktop in MeshCentral Router does not work?

**Comment by kuksabong** [comment]
These machines belong to me.
The remote desktop on the web site works fine. 
Remote desktop in MeshCentral Router does not work.
And I also did other tests.
In MC Router v1.3.7704, the remote desktop worked normally regardless of the Windows 10 version.

**Comment by Ylianst** [comment]
What version of MeshCentral Router does not work?

**Comment by kuksabong** [comment]
My MeshCentral Router version is **1.8.7864.**
