### ISSUE TITLE
Information - Missing Information For Location Deployment with "MeshCentral Router Links" in the sample-config-advanced.json

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2880]
I'm on MeshCentral Server v0.8.75 and an issue has presented itself that when you specify a filter in the "extralinks" subcategory of "deviceMeshRouterLinks" for a location deployment the will not show for the specified "mesh" or "node". Only when there is no filter specified do they show up.

Steps To Reproduce:
1. Create a location deployment in config.json
2. Login to that location and add a test device
3. Create the "deviceMeshRouterLinks" section in the location created in step 1 of the config.json with the subcategory of "extralinks".
4. In the "extralinks" section of the config.json create a "filter" which specifies a "mesh" or "node" or both.
5. The link will NOT appear on any device or device group
6. Edit the "extralinks" section again and change "filter" to "_filter" and suddenly the link appears on every device in every device group. 

I believe this is again related to location deployments.

**Comment by Ylianst** [comment]
Testing this now.

**Comment by Ylianst** [comment]
So, it works for me... however, I can see why it would cause this issue report. By the way, thank you so much for submitting well written issues. Super appreciated.

For my test, I have a domain called "devtest". I added the router links and filter and it works. However, the identifiers in the filter are of the form "node/[domain]/[nodeid]" or "mesh/[domain]/[meshid]". For the default domain, the domain part is empty, so you write "node//xxxx". But for other domains, you need to put the domain identifier, so in my case "node/devtext/xxxx".

Let me know if that helps, my example below:

```
    "devtest": {
      "title": "DevBox",
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "TAP",
            "port": 443,
            "localPort": 47800
          },
          {
            "name": "xxHTTPS",
            "protocol": "https",
            "port": 443,
            "localPort": 12345,
            "ip": "192.168.2.147",
            "filter": [ "mesh/devtest/uEEmp1nznOA4PG$VcZDkV8$2lLDtST0J@hhe6TVFYxK1$G8hek8rX0JpGmwfaUh8", "xnode/devtest/Z9sebh$Cwab7uDHLhjRlvqWcaiFPGYdalEl1VbSZpGsYTspdK42Q7YHAAPYuLbXN" ]
          }
        ]
      }
    }
```

**Comment by LPJon** [comment]
Your instructions worked perfectly! Thank you Sir. This information is not in the "sample-config-advanced.json", might want to add it there.

You are very welcome on the issue submission quality. I'm in the IT field and hate it when some one wants me to help them but only says "When I press enter nothing happens" then later I find out they are on an android phone. Makes for a super interesting day. So anyways, I will always provide as much information as I can...it makes your job easier and my need for fixes much faster. You are super responsive and very fast and that makes my life easier....the least I can do is make yours easier whenever I can right?

**Comment by Ylianst** [comment]
Oh perfect. Thanks for reporting back. It's very true that if you about to spend hours working on a fix, it's nice to have good information to go on.

**Comment by Ylianst** [comment]
Added clarification in the advanced sample:

```
      "_deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80,
            "_ip": "192.168.1.100",
            "_filter": [ "mesh/(domainid)/(meshid)", "node/(domainid)/(nodeid)" ]
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "port": 443
          }
        ]
      },
```
