### ISSUE TITLE
BUG - "Chat" button in MeshCentral Server does not use the Location specified in the config.json for url generation

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2882]
MC v0.8.75
This issue pertains to location deployments. It also relates to issue #2873 with regard to using domain locations specified in the config.json. When a location is specified in the config.json and you are using that location to open a user chat with the agent side. The url used does not include the specified location but instead points to the root of the domain. Adding the location into the link  manually makes the chat window work perfectly. 

Sample URL Generated:
```
https://<PRIVATE DOMAIN>/messenger?id=meshmessenger/node%2F<PRIVATE DOMAIN LOCATION>%2<PRIVATE NODE ID>/user%2F<PRIVATE DOAMIN LOCATION>%2F<PRIVATE USER>&title=<PRIVATE AGENT HOSTNAME>&auth=<PRIVATE AUTH>
```

Corrected URL:
```
https://<PRIVATE DOMAIN>/**<PRIVATE DOMAIN LOCATION>**/messenger?id=meshmessenger/node%2F<PRIVATE DOMAIN LOCATION>%2<PRIVATE NODE ID>/user%2F<PRIVATE DOAMIN LOCATION>%2F<PRIVATE USER>&title=<PRIVATE AGENT HOSTNAME>&auth=<PRIVATE AUTH>
```

**Comment by Ylianst** [comment]
This is great. Your really putting the MeshCentral multi-domain feature to the test.

**Comment by Ylianst** [comment]
I just testing it and the URL sent to the remote computer is correct, but the URL opened on the administrator side is not.

**Comment by LPJon** [comment]
Sorry.....I was only able to see the administrator side because the agent side has a problem with the agent opening url's in reference to this issue #2881. I don't have any windows machines running on the domain....lol

**Comment by Ylianst** [comment]
Fixed it. Working on publishing MeshCentral v0.8.76 now so you can try it out.

**Comment by LPJon** [comment]
This is working 100%. Closing this issue. Thanks again for working on this so fast.
