### ISSUE TITLE
BUG - "Root Certificate" is still showing up on the main login page of Mesh Central in a domain location deployment

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#2883]
The link "Root Certificate" is present on the login page of a location deployment. When clicking the link it does not work because it is missing the domain location specified in the config.json

Sample URL Generated:
```
https://<PRIVATE DOMAIN>/MeshServerRootCert.cer
```
Corrected URL:
```
https://<PRIVATE DOMAIN>/<PRIVATE DOMAIN LOCATION>/MeshServerRootCert.cer
```

NOTE: The "Terms & Privacy" links works perfectly!

On a second related issue with the "Root Certificate" link. I have a valid SSL cert setup on this domain. Why is this link still appearing and is there is a way I can force it to disappear?

**Comment by Ylianst** [comment]
Thanks for reporting this. I just fixed the link and it will be in MeshCentral v0.8.77. This link should go away automatically when using your own certificate or a Let's Encrypt certificate. You can also remove it by adding the following link in the domain section of the config.json:

```
"trustedCert": true
```

So, you would need to add this to each of your domains you want the link removed. Let me know if that helps.

**Comment by LPJon** [comment]
> 
> 
> Thanks for reporting this. I just fixed the link and it will be in MeshCentral v0.8.77. This link should go away automatically when using your own certificate or a Let's Encrypt certificate. You can also remove it by adding the following link in the domain section of the config.json:
> 
> ```
> "trustedCert": true
> ```
> 
> So, you would need to add this to each of your domains you want the link removed. Let me know if that helps.

I tried using the `"trustedCert": true` in the domains section but it did not work. 

Example:

```
                  "domains": {
                    "<DOMAIN LOCATION>": {
                     "siteStyle": 2,
                     "title": "<TITLE>",
                     "title2": "TITLE 2",
                     "certurl": "https://<DOMAIN>:443/",
                     "minify": true,
                     "_tlsOffload": "127.0.0.1,<PRIVATE IP>",
                     "_trustedProxy": "127.0.0.1",
                     "agentInviteCodes": true,
                     "trustedCert": true
                     }
```
Is that the proper way to apply it?

**Comment by nzalev** [comment]
> I tried using the `"trustedCert": true` in the domains section but it did not work.
> 
> 
> Is that the proper way to apply it?

Hi Jon, this is not available through NPM until the next published version (0.8.77). Currently, the latest published version is still 0.8.76. I would guess 0.8.77 will be published Monday or shortly after. The fix is also live in github, if you want to download `webserver.js` from the repo directly.

**Comment by LPJon** [comment]
> > I tried using the `"trustedCert": true` in the domains section but it did not work.
> > 
> > 
> > Is that the proper way to apply it?
> 
> Hi Jon, this is not available through NPM until the next published version (0.8.77). Currently, the latest published version is still 0.8.76. I would guess 0.8.77 will be published Monday or shortly after. The fix is also live in github, if you want to download `webserver.js` from the repo directly (ps: I don't recommend mixing versions - this can introduce problems if the versions are too far apart or if there have been a lot of changes)

I see....i thought it was an undocumented feature he was telling me about before the release so I could remove it now. Ok....sorry for getting in a hurry. I didn't look at the code change.

**Comment by Ylianst** [comment]
Apologies, I was under the impression `"trustedCert": true` would work on older version but I must not have looked at it carefully. In any case, MeshCentral v0.8.77 is out and should fix this.

**Comment by LPJon** [comment]
@Ylianst Either way this issue is resolved and this is now working 100%. Thanks again for all the hard work. Sorry I got a little in a hurry. Was `"trustedCert": true` just added as a new feature or was it one already implemented? In other words should it work now or should I not even bother keeping it in my arsenal?

**Comment by nzalev** [comment]
> @Ylianst Either way this issue is resolved and this is now working 100%. Thanks again for all the hard work. Sorry I got a little in a hurry. Was `"trustedCert": true` just added as a new feature or was it one already implemented? In other words should it work now or should I not even bother keeping it in my arsenal?

In 0.8.76, the root cert link would generated unless letsencrypt or tls offloading was enabled. This did not take into account any domain settings.

`trustedCert` is not a *new* setting, but it was not previously used in generating the root certificate link.

**Comment by Ylianst** [comment]
That is correct. `"trustedCert": true` is not new, but I did make it so it would no longer show the root cert link on the new version when it's set.

**Comment by LPJon** [comment]
Not a problem.....thanks for clearing it up.
