### ISSUE TITLE
Server's action is not displayed 

### ISSUE THREAD

**Issue by Philippe687** [Ylianst/MeshCentral#2884]
Hello Ylian,
If my account is full admin i should see server's actions like this :
![image](https://user-images.githubusercontent.com/29157130/125155724-83b1ee00-e1ad-11eb-8ace-31f357234ac7.png)
Am I right ?
I didn't see it anymore... Just this :  
![image](https://user-images.githubusercontent.com/29157130/125155779-db505980-e1ad-11eb-866e-2670c3984db5.png)

Thank you in advance for help.

Best regards,

**Comment by nzalev** [comment]
Hi Philippe,

There are two things which are required to show the server actions panel
1. Correct server features
2. Correct server rights

1: Server features are controlled in config.json, in `domains` under `myserver`.
```json
  "domains": {
    "": {
      "myserver": {
        ...
      },
```
If you have this config option set, remove it. Then see if you have the Server Actions back.


2: Server rights are set at the user page
![Screenshot from 2021-07-10 16-05-19](https://user-images.githubusercontent.com/63608819/125175235-b43b5d00-e198-11eb-81e6-4975e8e15ec4.png)
You mention the account has Full administrator, so I assume this is not an issue.

**Comment by Ylianst** [comment]
Indeed, if you add these lines to the domain section of the config.json, it will remove the server actions even if you are full administrator:

```
      "myServer": {
        "Backup": false,
        "Restore": false,
        "Upgrade": false,
        "ErrorLog": false,
        "Console": false,
        "Trace": false
      }
```

**Comment by Philippe687** [comment]
Hello Nzalev & Ylian,
Thanks for your help :).
Done. I think that backup & restore are missing.
![image](https://user-images.githubusercontent.com/29157130/125187910-8f6ce580-e27d-11eb-99fc-92ff54c40acf.png)
Best regards,

**Comment by nzalev** [comment]
> Hello Nzalev & Ylian,
> Thanks for your help :).
> Done. I think that backup & restore are missing.

These two options will only show if using NeDB. These options are not available if you are using MongoDB, MariaDB, or MySQL.

I can look at adding backup, but I will likely not touch restore. If you need, you can use the `autobackup` command in the server console, and it will generate a file in `meshcentral-backup`.

**Comment by Philippe687** [comment]
Hi Nzalev,
Thank you for your explaination.
Your right. My setup is under Mongodb. 
Best regards,
