### ISSUE TITLE
Agents change from online to offline status continuously when mesh (mongoDB) server move to Internet

### ISSUE THREAD

**Issue by Susieji** [Ylianst/MeshCentral#2889]
hi, 
Agents change from online to offline status continuously when mesh (mongoDB) server move from local to Internet.

OS: win10 (different client with different win10 version have same issues)
mesh version: have tested both of the latest version and the stable server version 0.7.89

will add to more info in following days, thanks.

**Comment by Ylianst** [comment]
Add the following line in the settings section of the config.json:

```
"agentpong":30
```

This will cause the server to send a "pong" message to all agents every 30 seconds. If that does not work, try instead:

```
"agentping":30
```

This will cause a "ping" message to be sent to all agents every 30 seconds and agents will all respond with a "pong" message. You don't needs to have agentping and agentpong at the same time, that is just a waste.

If that works, then make the 30 second longer until you see the problem again. ping/pong traffic is a waste of traffic and increases hosting costs, so you want to limit use or it. If you are using a reverse proxy or firewall in front of MeshCentral, make sure you have connection timeouts that are 5 minutes or more.

Hope that helps,
Ylian

**Comment by Susieji** [comment]
Thanks Yilianst, it works.
