### ISSUE TITLE
Duplicate email accounts can be created within domain

### ISSUE THREAD

**Issue by Kodangi** [Ylianst/MeshCentral#289]
Steps:

Create an user 'user1' with email address user1@company.com
Change email address as 'verified'
Create another user 'user2' with same email address user1@company.com
Change email address as 'verified'

When 'Reset Account' is initiated for this email address, the email goes for the last account in the list. (user2). (alphabetically last user from the DB is used)

So for security purpose:

We should not be able to create new users with an existing email address

**_Observation: (not to be considered as a request/bug):_**

Able to create an username with same email address as admin/root account, but unable to set the 'Verified' for the email address. It makes sense. 

But at the same time, if root/admin was not Email Verified, the new user email can be set verified, and then root/admin email also can be set as verified, even though same email address.

In this case, admin/root will never able to reset the password, because it always will reset password for new user, if the username is alphabetically later than admin/root.

If duplicate email is not allowed, this entire use case issue will not happen. (not allowing duplicate email per domain)

**Comment by Ylianst** [comment]
Thanks for reporting this, it is most certainly a problem. I will have to do a bit of work next week to fix this one.

**Comment by whalehub** [comment]
@Ylianst Any update on this?

**Comment by si458** [comment]
this issue can be avoided by using `userNameIsEmail: true` but i understand that this shouldnt be possible so its defo a bug
