### ISSUE TITLE
BUG: hung session

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2892]
Good day.
Sometimes we catch stuck sessions and now we managed to collect some information about this. The desktop session has been hanging for over 3 days. Connected from the 9th, now 12. In the event logs, no disconnection is visible. In the server console, the session is seen as active. It also lights up on the Web.
But I know for sure that I do not work there. Moreover, all devices from which I could log in have already rebooted during this time and the authorization timeout is set in the server configuration for 15 minutes.
If you connect to the desktop and disconnect immediately, then the session closes normally.
Server version 0.8.74
![event](https://user-images.githubusercontent.com/51225180/125350777-ea7b0700-e367-11eb-95ba-0b15c95c97e2.JPG)
![config](https://user-images.githubusercontent.com/51225180/125350783-ed75f780-e367-11eb-986a-d8b4f2bdff92.JPG)
![console](https://user-images.githubusercontent.com/51225180/125351230-8278f080-e368-11eb-8da6-8dcfd0775afb.jpg)
![versions](https://user-images.githubusercontent.com/51225180/125350795-f1a21500-e367-11eb-8f1f-07943abdad2a.JPG)
![coreinfo](https://user-images.githubusercontent.com/51225180/125350800-f36bd880-e367-11eb-9a62-77a14801f6e3.JPG)
![web](https://user-images.githubusercontent.com/51225180/125350806-f5359c00-e367-11eb-9067-fae5a4296af6.JPG)

**Comment by Ylianst** [comment]
I have noticed this before and did some work to track this down. The next version of MeshCentral v0.8.78 will show "CLOSED-x" on the "usersessions" command if something did not close right. This should help identify the problem.

![image](https://user-images.githubusercontent.com/1319013/125503089-7ef27dc4-be85-4c69-ad40-59385ab4314e.png)

**Comment by Ylianst** [comment]
MeshCentral 0.8.78 was published with the improved "usersessions" command. Going to be interesting to see if there is anything shown when a session is stuck.
