### ISSUE TITLE
New Agents Not showing after enabling Session Record

### ISSUE THREAD

**Issue by JOSEPHDEVASSIA** [Ylianst/MeshCentral#2896]
Dear Ylian,

i am using latest version of Meshcentral ( v0.8.77) with 4000+agents. 
last day i have activated Session recording after that newly installed agents are not connecting with server.  
If i reboot the server then all the agents connects properly. 
I can see somany issues related to this, like #2800 #2443 etc....
If i deactivate the session recording then all the agents connect properly.

i am using windows server so i don't know how to add LimitNOFILE=1000000.

```
Server Os - Windows server 2019
RAM - 64GB
CPU - 32core
Node ver - node": "16.4.2"
DB - Mongodb
Plugins - Not used.
```

**Comment by Ylianst** [comment]
This is pretty crazy as enabling session recordings should not have any impact on agent connections. When activating session recording on the server, can you share what you put in the config.json? Thanks.

**Comment by AJITHMUT** [comment]
@Ylianst  
We have added below code.
After session record activation \ 10-20 sessions system works properly but after few hours mesh server hangs and agent remote connection will take more time and also its hang. Also no new agents connects with server till restarts.

"_sessionRecording": {
        "onlySelectedDeviceGroups": true,
        "filepath": "D:\\RECORDINGS",
        "index": true,
          "maxRecordings": 10000,
        "_maxRecordingSizeMegabytes": 3,
        "protocols": [ 1, 2, 101 ]
},

**Comment by Ylianst** [comment]
Thanks. I know this is a dumb question, but just to confirm, the D: drive that records all of the sessions is not full? Recording a lot of sessions will generate a lot of data, I will need to stress test this more.

**Comment by AJITHMUT** [comment]
@Ylianst - D drive having sufficient memory available only 10% we have used.
The maximum concurrent recording session is below 15 and per day maximum 50-60 sessions
I am using 100MBPS internet connectivity with unlimited Data, The bandwidth usage is not more than 50MBPS and i have enabled all types of compressions.

**Comment by Ylianst** [comment]
Ok, thanks. That is going to be a bunch of traffic to record... I will try to stress test and see what I can do.

**Comment by openncomp** [comment]
I confirm, I got the same problem on a freshly installed MeshCentral on Ubuntu with an activated record on the server side.

**Comment by silversword411** [comment]
I think this is another wayward soul of this fundamental issue. I also have session recording enabled.
https://github.com/Ylianst/MeshCentral/issues/2831

**Comment by si458** [comment]
PLEASE FOLLOW #4449
