### ISSUE TITLE
Unable to login when using the "--tlsoffload" flag

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#29]
I'm currently using MeshCentral behind a reverse proxy with the "--notls" flag. When I run MeshCentral that way, my agents can't connect to the server until I manually change the protocol in the MeshAgent.msh file from ws:// to wss://. This problem can be avoided by using the "--tlsoffload" flag instead, but that comes with its own drawbacks.

While my agents are able to connect to the server without any issues when using the "--tlsoffload" flag, I am unable to log into the MeshCentral site itself. When I enter my credentials and press Enter, the site simply reloads instead of logging me in. A workaround is to specify the user at runtime, but the obvious security implications prevent me from using it.

**Comment by Ylianst** [comment]
I will check this when I am back at work.

**Comment by whalehub** [comment]
This issue was fixed in MeshCentral v0.2.2-p.
