### ISSUE TITLE
In 'Reset account' email, it is good to not provide username

### ISSUE THREAD

**Issue by Kodangi** [Ylianst/MeshCentral#290]
In Reset account email, it is good to not provide username:

In case the password reset email is compromised, the middle man can login and access all the systems. (because username and password in same email)

So, if we do not include username in 'Reset account', it is safe for the user.

(could be diff item for enhancement to forgot username, but it is not really a big need, because that can be send via email from the admin - manually)

**Comment by Ylianst** [comment]
Agreed. It's the weekend here, I will work on this next week.

**Comment by whalehub** [comment]
@Ylianst Any update on this?

**Comment by dinger1986** [comment]
I dont use this @si458 shall I setup and test?

**Comment by si458** [comment]
this is already possible now, you can customise the emails that get sent
create a folder called `meshcentral-web` next to `meshcentral-data`, 
then inside `meshcentral-web` make a folder called `emails`
then inside `emails` COPY ALL the email templates from `node_modules/meshcentral/emails` into `emails`
then you can customise what is sent to end users/staff etc
