### ISSUE TITLE
Feature request: restrict clipboard access

### ISSUE THREAD

**Issue by OvrAp3x** [Ylianst/MeshCentral#2900]
It would be great if clipboard access could be restricted as a permission node.
This would be useful for preventing a user to copy data from a remote.
Preventing data leaks for sensitive systems.

**Comment by OvrAp3x** [comment]
Related to #2901

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Just published v0.8.79 with options to turn off clipboard features.

![image](https://user-images.githubusercontent.com/1319013/125866846-1130a4d7-56fd-41cb-976d-ba87d327ab8f.png)

**Comment by OvrAp3x** [comment]
Works great! Thank you for adding this!
Makes my life a lot easier!!
