### ISSUE TITLE
Feature request: disable screenshot and record button

### ISSUE THREAD

**Issue by OvrAp3x** [Ylianst/MeshCentral#2901]
It would be useful to be able to disable the screenshot and record buttons, to make leakage of data  harder.

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.8.78, you can add this line to the domain section of the config.json:

```
"LocalSessionRecording": true
```

That will remove the local session recording and screen shot options.

**Comment by OvrAp3x** [comment]
Great!
Thank you very much for feedback!

**Comment by Ylianst** [comment]
MeshCentral v0.8.78 was just published with this feature. Let me know if it works.

**Comment by OvrAp3x** [comment]
Working great!
![image](https://user-images.githubusercontent.com/14344702/125703140-012ad5b6-7b80-4b1d-a636-b34fa20b7f55.png)
