### ISSUE TITLE
Allow more info/notes to display next to hostname

### ISSUE THREAD

**Issue by soapster** [Ylianst/MeshCentral#2902]
It would be great to allow more info to be displayed next to a computer hostname.  There's a lot of open space next to the hostnames.
Things like phone extensions, or people's names would be good examples.
Currently, if you don't know exactly what the hostname of the computer you need to connect to is, you have to hunt for it.
My suggestion would be to allow a couple more columns to be enabled (optional). Like Description or Tags.

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.8.79 published later today, you can display the device description in the device list view. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/125849167-81516e13-0844-4e83-8168-8ed8ba603875.png)

**Comment by soapster** [comment]
WOW! Thank you!
