### ISSUE TITLE
Choose display issue?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#2903]
Hi
I was wondering if its normal when i give a user to only remote view but not be able to control the computer cannot switch display, but if the user has access to the desktop it can switch the display
Not sure if that's normal?

Thank you

**Comment by Ylianst** [comment]
Ha. It's normal and it's a bit of a problem. I\f many users are viewing a remote device, they will all see the same display. So, if one user changes the display they are looking at, it will change it for everyone. As a result of this, I opted to not allow view-only users to change the display. In reality, I would probably have to allow it until a user with input access connects. In that case, all users that are view-only would loose display control rights.

There are cases where students are all viewing a display with view-only permission. You don't want to allows a student to switch display selection for everyone.

**Comment by killmasta93** [comment]
Thanks for the reply, currently only have one user which only has the right to see but not move inside of the desktop but he needs to switch display is there a way to do that without giving him permission of the desktop?

Thank you again
