### ISSUE TITLE
Translations doesn't apply

### ISSUE THREAD

**Issue by LittleKing205** [Ylianst/MeshCentral#2904]
Hi Ylianst,

you do a really great job on Meshcentral. (I want to do say this)

I have a few problems with the online translation tool.
In German, a couple of strings weren't translated well. So I tried to fix this myself.

Unfortunately, when I press the translate button, nothing happens.

The "translate.json" file is saved correctly in the data folder.

I run MeshCentral as a normal user in the home folder.

System info:
   -> Debian 9 (on a VPS server)
   -> Node version: 12.21.0

Am I doing something wrong, or do I have to run this as a different user?

![zip meschcentral](https://user-images.githubusercontent.com/59285498/125716681-c37934ff-5757-418f-b1a6-044bb7afef65.png)
![zip meschcentral example](https://user-images.githubusercontent.com/59285498/125716683-df27f347-0342-4ff5-889f-f39d68987be1.png)

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again
if your still having this issue,
please reply back and let us know
