### ISSUE TITLE
after initial  installation of meshcentral and configuring it , the device groups and agents ,are missing after restart

### ISSUE THREAD

**Issue by harmelgill** [Ylianst/MeshCentral#2907]
i have blank device group and no agents

**Comment by Ylianst** [comment]
Your database is probably not setup correctly. You would need to provide much more information about your setup. MeshCentral version, NodeJS version, config.json, database you are using, etc.

**Comment by harmelgill** [comment]
Hi Thanks for the reply
this is really awesome  software
 i am using default settings  and nedb database i have not  configured and
database settings , i have left them as default.

do i need to  make any changes for nedb  i did not see anything in the
guides to make any adjustments.

Kind regards
Harmel

**Comment by nzalev** [comment]
> Hi Thanks for the reply this is really awesome software i am using default settings and nedb database i have not configured and database settings , i have left them as default. do i need to make any changes for nedb i did not see anything in the guides to make any adjustments. Kind regards Harmel

I installed a fresh version of meshcentral and with no settings configured, created a device group, added an agent, and reset the server. I did not lose anything after restarting the server.

In your meshcentral directory, is there the file `meshcentral-data/meshcentral.db`? Does the user running meshcentral have full permissions in the meshcentral directory?

Is there anything in `meshcentral-data/mesherrors.txt`?

If you run your server interactively (ie, from the meshcentral directory run `node node_modules/meshcentral`), does it print any errors?

**Comment by harmelgill** [comment]
Hi Noah

 thanks for the prompt reply

root is running user and as full access i just noticed that i have
2 meshcentral-data dirs

***@***.***:/var/www/mesh/meshcentral-data/meshcentral-data# ls -la
total 412
drwxr-xr-x 2 root root   4096 Jul 15 15:39 .
drwxr-xr-x 4 root root   4096 Jul 15 21:35 ..
-rw-r--r-- 1 root root   2498 Jul 15 15:39 agentserver-cert-private.key
-rw-r--r-- 1 root root   1538 Jul 15 15:39 agentserver-cert-public.crt
-rw-r--r-- 1 root root   1112 Jul 15 15:39 config.json
-rw-r--r-- 1 root root   1100 Jul 15 15:39 hg_config.json
-rw-r--r-- 1 root root   1196 Jul 15 15:39 meshcentral.db
-rw-r--r-- 1 root root 191487 Jul 15 15:39 meshcentral-events.db
-rw-r--r-- 1 root root    230 Jul 15 15:39 meshcentral-power.db
-rw-r--r-- 1 root root 166173 Jul 15 15:39 meshcentral-stats.db
-rw-r--r-- 1 root root   1702 Jul 15 15:39 mpsserver-cert-private.key
-rw-r--r-- 1 root root   1526 Jul 15 15:39 mpsserver-cert-public.crt
-rw-r--r-- 1 root root   2494 Jul 15 15:39 root-cert-private.key
-rw-r--r-- 1 root root   1566 Jul 15 15:39 root-cert-public.crt
-rw-r--r-- 1 root root    201 Jul 15 15:39 serverstate.txt
-rw-r--r-- 1 root root   2494 Jul 15 15:39 webserver-cert-private.key
-rw-r--r-- 1 root root   1650 Jul 15 15:39 webserver-cert-public.crt
***@***.***:/var/www/mesh/meshcentral-data/meshcentral-data# cd ../
***@***.***:/var/www/mesh/meshcentral-data# ls -la
total 804
drwxr-xr-x 4 root root   4096 Jul 15 21:35 .
drwxr-xr-x 6 root root   4096 Jul 13 22:33 ..
-rw-r--r-- 1 root root   2498 Jul 15 15:41 agentserver-cert-private.key
-rw-r--r-- 1 root root   1538 Jul 15 15:41 agentserver-cert-public.crt
-rw-r--r-- 1 root root   1088 Jul 15 21:28 config.json
-rw-r--r-- 1 root root   1100 Jul 15 15:41 hg_config.json
drwxr-xr-x 2 root root   4096 Jul 15 21:35 letsencrypt-certs
drwxr-xr-x 2 root root   4096 Jul 15 15:39 meshcentral-data
-rw-r--r-- 1 root root   2121 Jul 15 21:35 meshcentral.db
-rw-r--r-- 1 root root 404856 Jul 15 21:40 meshcentral-events.db
-rw-r--r-- 1 root root    758 Jul 15 21:35 meshcentral-power.db
-rw-r--r-- 1 root root 345065 Jul 15 21:40 meshcentral-stats.db
-rw-r--r-- 1 root root   1702 Jul 15 15:41 mpsserver-cert-private.key
-rw-r--r-- 1 root root   1526 Jul 15 15:41 mpsserver-cert-public.crt
-rw-r--r-- 1 root root   2494 Jul 15 15:41 root-cert-private.key
-rw-r--r-- 1 root root   1566 Jul 15 15:41 root-cert-public.crt
-rw-r--r-- 1 root root    203 Jul 15 21:35 serverstate.txt
-rw-r--r-- 1 root root   2494 Jul 15 15:41 webserver-cert-private.key
-rw-r--r-- 1 root root   1650 Jul 15 15:41 webserver-cert-public.crt
***@***.***:/var/www/mesh/meshcentral-data#


 i I think i I will rename    mesh  to mesh_old and do new install

Kind Regards
Harmel

**Comment by nzalev** [comment]
I am not sure how you ended up with nested data directories. But, one of those `meshcentral.db` files will contain your agents and mesh groups. I think likely the ones in the parent directory since they are larger. You can save those and drop them back in to restore your data if you go through with a re-install.

**Comment by harmelgill** [comment]
Hi
Thanks for your help i have  done new install and created  new device groups
i will check tomorrow see how it pans out

Many Thanks
Harmel
