### ISSUE TITLE
Manually adjusting group ID

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2909]
I cringe to even ask this question, as I should know better, but here goes:

Is it possible / safe to create a group on one MC2 server and then alter its ID through the database to an alternative one, just for a short while?

Somehow (we're still investigating) a script was placed on a customer site that installs the mesh agent but points to a group ID that doesn't exist any more on either our test or production systems. We know which server that script is pointing to so I'm hoping to simply re-create a group on that server, then alter it's ID in the main table on the database. 

"Reasonably" safe to do so?

I'm hoping that once we have access to the remote system, we'll change the .msh file to point to a "properly created" group and then we can remove the "fake" group, but wondered if there's something that would intrinsically go wrong with this approach?

Of course, this assumes that the creation of the groups is recorded in the database `main` table (I'm using MySQL)

**Comment by nzalev** [comment]
I will preface this by saying it is a bad idea. If you do go ahead with it, take a backup first.

Also, if you are basing the group ID off of the contents of the .msh file, that is a hash and not actually the group ID.

However, it is possible. You can create a new group entirely from within the database. You need to know a few things:

A "group" is internally referred to as a mesh. It has the following structure
```javascript
{
    "_id": "mesh//ZR5HmZw5M6WLuN@Ux2z0t5eylwA9YF07M71aLIwneeQgxK6SE3mmvWWQf1xD39UR",
    "type": "mesh",
    "name": "MESHNAME",
    "mtype": 2,
    "desc": "",
    "domain": "",
    "links": {
        "user//your-user-name": {
            "name": "your-user-name",
            "rights": 4294967295
        }
    },
    "consent": 71,
    "flags": 0
}
```

In the MySQL/MariaDB, the main table has the following columns, 'id', 'type', 'domain', 'extra', 'extraex', 'doc'. The domain should not be null. I am not using a domain, so it is an empty string. The type is 'mesh'. The id is the `_id` property from the mesh object. Doc is the json object in a single line.

The query will look like this:
```sql
insert into main values ('mesh//ZR5HmZw5M6WLuN@Ub2z0t5eylwF9YF07M71aLIwnjeQgxK6SE3mmvQWQf1xD39UR', 'mesh', '', null, null, '{"_id":"mesh//ZR5HmZw5M6WLuN@Ux2z0t5eylwA9YF07M71aLIwneeQgxK6SE3mmvWWQf1xD39UR","type":"mesh","name":"MESHNAME","mtype":2,"desc":"","domain":"","links":{"user//your-user-name":{"name":"your-user-name","rights":4294967295}},"consent":71,"flags":0}')
```

Next, you have to modify your user. The following is the structure of a user:

```javascript
{
    "_id": "user//your-user-name",
    "type": "user",
    "name": "your-user-name",
    "creation": 1578507890,
    "domain": "",
    "email": "your@email.address",
    "passchange": 1626123454,
    "salt": "...",
    "hash": "...",
    "siteadmin": 4294967295,
    "login": 1626228036,
    "links": {
        "mesh//...": {
            "rights": 4294967295
        },
        "mesh//...": {
            "rights": 4294967295
        },
        ...
    },
    "pastlogin": 1626214287
}
```

You will have to add a link from the user to the new mesh. Query for your user and copy the doc field.
```sql
select * from main where type = 'user'
```
Under links, add `,"mesh//your-new-meshid...": {"rights": 4294967295}`

Now, update your user.
```sql
update main
set doc = 'your updated user json here'
where id = 'user//your-user-id'
```

**Comment by Ylianst** [comment]
@nzalev describes it exactly.

I would have no problem creating a device group with a specific ID. Totally fine and have recommended it privately in the past. Make a backup of your database, create a new device group and change it's identifier. You will then need to change the device group identifier for your user entry.

Make sure to have the server stopped while you are doing the edit and start up the server once you are done.

I could consider making it so that you could create a device group with a custom identifier using meshctrl.js in the future to handle this case.

**Comment by D4V3M0NK** [comment]
Ah ... it was the user update that I was missing - I'd done everything else, but didn't think of that. Thanks @nzalev for the info. @Ylianst I'm not sure that this would really require any further action from a code point of view, this must be a fringe case scenario.

Just *purely* out of interest, how is the "rights" integer manifested?

**Comment by nzalev** [comment]
> Just _purely_ out of interest, how is the "rights" integer manifested?

It is an integer whose bits represent different permissions. 4294967295 is hex 0xFFFFFFFF, which is `1111...1111`, or all permissions set on.

The following are the permissions for a mesh (a group)

```javascript
    // Mesh Rights
    const MESHRIGHT_EDITMESH            = 0x00000001; // 1
    const MESHRIGHT_MANAGEUSERS         = 0x00000002; // 2
    const MESHRIGHT_MANAGECOMPUTERS     = 0x00000004; // 4
    const MESHRIGHT_REMOTECONTROL       = 0x00000008; // 8
    const MESHRIGHT_AGENTCONSOLE        = 0x00000010; // 16
    const MESHRIGHT_SERVERFILES         = 0x00000020; // 32
    const MESHRIGHT_WAKEDEVICE          = 0x00000040; // 64
    const MESHRIGHT_SETNOTES            = 0x00000080; // 128
    const MESHRIGHT_REMOTEVIEWONLY      = 0x00000100; // 256
    const MESHRIGHT_NOTERMINAL          = 0x00000200; // 512
    const MESHRIGHT_NOFILES             = 0x00000400; // 1024
    const MESHRIGHT_NOAMT               = 0x00000800; // 2048
    const MESHRIGHT_DESKLIMITEDINPUT    = 0x00001000; // 4096
    const MESHRIGHT_LIMITEVENTS         = 0x00002000; // 8192
    const MESHRIGHT_CHATNOTIFY          = 0x00004000; // 16384
    const MESHRIGHT_UNINSTALL           = 0x00008000; // 32768
    const MESHRIGHT_NODESKTOP           = 0x00010000; // 65536
    const MESHRIGHT_REMOTECOMMAND       = 0x00020000; // 131072
    const MESHRIGHT_RESETOFF            = 0x00040000; // 262144
    const MESHRIGHT_GUESTSHARING        = 0x00080000; // 524288
    const MESHRIGHT_ADMIN               = 0xFFFFFFFF;
```

Keep in mind, the powers of 2 are important so not more than one permission is turned on. You can quickly (computation wise) check if a permission is set via bitwise and, and set a permission via bitwise or.

**Comment by D4V3M0NK** [comment]
Hmmm ... in trying to update the `doc` I'm getting an error with an invalid escape character in string ... am wondering if this could be a potential MySQL issue?

**Comment by nzalev** [comment]
> Hmmm ... in trying to update the `doc` I'm getting an error with an invalid escape character in string ... am wondering if this could be a potential MySQL issue? Does the JSON have to be all on one line?

The json must be a single line. If you use a tool to minify it, make sure it does insert any additional characters.
