### ISSUE TITLE
Ability to add multiple redirects

### ISSUE THREAD

**Issue by johnczer** [Ylianst/MeshCentral#291]
Hi Ylian, Hope you had a good weekend!
Is it possible to have multiple redirects so the unlimited link can be added for multiple customers and the instruction page would be for that particular customer? 
Customer A: "customera" https://support.site.com/customeraagentlink....
Customer B: "customerb" https://support.site.com/customerbagentlink....

**Comment by Ylianst** [comment]
Hi. Yes, you can as many redirects as you link in the "Redirects" section of a domain. That is already present and should work.

**Comment by johnczer** [comment]
I tried several variations of adding these in the domains section but I could not get it to work. In the sample it only has one redirects and link. When I used the validation I can add a new link separated with “,” and it likes that but only second link works. Could you show me an example?

**Comment by johnczer** [comment]
This is working!  Not sure what the deal was but when I tried it this am it didn't appear to be working but circled back and it's all good!  Thank you

**Comment by Ylianst** [comment]
Perfect! I am a bit overrun by issues right now. Glad to close one.
