### ISSUE TITLE
Not installing on Unifi CloudKey Gen 2

### ISSUE THREAD

**Issue by 12nick12** [Ylianst/MeshCentral#2910]
I get the following error when trying to run on a CKG2. 

```
./meshagent: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./meshagent)
```

**Comment by krayon007** [comment]
That means the libc that your device was built with is older than the one I built that binary with. 

Do you have a tool chain for your device? The easiest way is to recompile the agent using the tool chain to target your device.

**Comment by Ylianst** [comment]
Note that if you access `/meshagents` on your server, you will see all the agent binaries included in MeshCentral.

![image](https://user-images.githubusercontent.com/1319013/125915204-44424c52-c882-485c-aaeb-1614ce25d2d4.png)

You may want to try agent 32 `Linux ARM 64 bit (glibc/2.24 NOKVM)` and see if that one works.

**Comment by 12nick12** [comment]
I've tried all, but wasn't able to get any to work. What info do you need to try and compile a version for me? Or how can I go about compiling myself?

**Comment by 12nick12** [comment]
I no longer have it, thank you for your awesome work. I wasn't able to get it to work.
