### ISSUE TITLE
Hi! I have a trouble with downloading large files

### ISSUE THREAD

**Issue by eu4you** [Ylianst/MeshCentral#2911]
HI!
I'm using Meshcentral very well.
Thanks for making a great program.
And the development of the program is dazzling and beautiful.

However, it always happens, and whenever I upload and download large files, I get a 'download error' or 'failed' message. There is a phenomenon that does not randomly jump from 3MB to 100MB and stops. And if you try again, the download will proceed from the beginning. This is independent of the file format, it happens the same in Firefox or Chrome, and uploads and downloads are the same. Same server but same problem with multiple clients.

If I can attach the log, where can I download the log?

I think if I download multiple files at the same time, the chances of success are higher.

I live in Korea and use the internet in a half gigabit environment, and the download/upload speed per second is estimated to be 5MB/s due to the capabilities of my NAS server.

**Comment by Ylianst** [comment]
Hi. Do you upload/download using the device "Files" tab on the web site? Let me know what version of MeshCentral you are using? Have you tried MeshCentral Router upload/download feature and if so, does it give the same problem?

![image](https://user-images.githubusercontent.com/1319013/125914736-9c859889-43c3-4c70-a5cc-924ecca22e63.png)

Thanks,
Ylian

**Comment by si458** [comment]
closing as stale, please update to the latest version 1.1.20, and make sure to use node 18 or above,
if your issue still happens, plz reply
