### ISSUE TITLE
MeshCentral-Router (Filetransfer) should get an feedback if a file can not be overwirten

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#2912]
It is really important that in the case of error the software get a feedback. 
At the Moment when I upload a file and and the file on the destination side it locked or read only then I get not feedback. In the result I do not know - was the tranfer succseful?
Please fix this issu - that would be very helpful.
Thanks so far for the gread work so far!!! I like the hole MeshCentral project. Please keep going...

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Added file upload/download error handling to MeshCentral Router on Windows.

![image](https://user-images.githubusercontent.com/1319013/126019879-382aa58f-67b9-415b-af1a-744a7d2e53b1.png)

Will be in MeshCentral v0.8.80, or you can download the improved [MeshCentral Router here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe). Let me know how that works.

**Comment by schanir** [comment]
Yes it work now! Many thanks for the quick response.
