### ISSUE TITLE
The TERMINAL tab and the WEB-SSH link do not appear in the local device groups

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#2913]
Hello,
I have a problem with one of my Meshcentral servers.
I have it updated to the latest version (0.8.79) installed on an updated Ubuntu 18.04.
The problem I have is that in the local device groups I do not see the WEB-SSH links or the TERMINAL tab in the devices that I add with the Linux option.
![mesh2](https://user-images.githubusercontent.com/11633829/125960265-ea950344-cf81-4b6f-9189-3304f8f525df.PNG)

In the config.json I have the ssh option activated within the domain.
![mesh1](https://user-images.githubusercontent.com/11633829/125960232-b0b78594-b92e-4907-a58a-f9b2c666e7f1.PNG)

I have another secondary server with Meshcentral, with the same version and in that they do appear. I have compared the config.json files and apparently they are with the same options.
Surely I have some error in the server configuration, but I can't find it.
Any ideas to solve it?
Thank you.
Greetings.

**Comment by Ylianst** [comment]
In your config above, you have "_domain".

![image](https://user-images.githubusercontent.com/1319013/125987825-2b32253f-1039-45e8-8ea6-3a6b73d8d68b.png)

All sections that start with _ will be ignored, so the entire domains section will be ignored including all values within it. Change "_domains" to "domains" and try again.

**Comment by lergolas** [comment]
It's true!  I'm blind.  That was the problem ... Thank you very much!
