### ISSUE TITLE
Script in Creating Local User Accounts to the Intel® AMT of a local computer in addition to the Admin user and another script to remove a local user.

### ISSUE THREAD

**Issue by MCJohnB** [Ylianst/MeshCentral#2914]
It would be nice to have a script that would create a local user on the computer with the necessary information in the fields, below, of a local Intel AMT user by selecting the group and one at the Device groups level.  In Addition, another script to remove a specific user. We will be adding over 2,000 computers in, MeshCentral, our environment and we need to have different IT Staff users access different areas of the buildings.  Manually would take to long to accomplish and the idea may lose steam of the importance of vPro Intel AMT management.  To be able to Manage the Intel® AMT user accounts for each computer.
 
![image](https://user-images.githubusercontent.com/83652365/125971776-24f1ea11-71f7-4407-b747-94a856e71f48.png)
![image](https://user-images.githubusercontent.com/83652365/125971812-7c641029-3cb0-4f25-b721-d81919bc3369.png)

**Comment by Ylianst** [comment]
Your request is difficult to understand. You would like a way to automate adding or removing Intel AMT user from MeshCentral?

**Comment by MCJohnB** [comment]
Thank you for getting back to me and I apologize the confusion.  I am trying to understand the logic of creating a user account.  Is the user stored on the local computer or is it stored on MeshCentral.  Yes, If possible I would like to create a new user to the computer at the group level instead of one by one. In Addition, if possible to remove a specific user as needed from the group level instead one by one.   The code is already written at the computer level all I would like if can be provided at a group level by setting it up for to hit all 50 computers in that group.  I hope this Helps and not confuse you even more.

**Comment by Ylianst** [comment]
Hi. MeshCentral has support for user groups. You can look at this [blog post for details](https://meshcentral2.blogspot.com/2020/01/meshcentral-support-for-user-groups.html). You can create a user group, add access to many device groups or devices in the device groups and them add users.

If you just want to add an account to a device group, you don't need to create a user group. Just click on a device group and hit "Add Users".

![image](https://user-images.githubusercontent.com/1319013/126082997-dd86bc73-be25-4fe3-9038-76cc41f480be.png)

You can then add them and they will instantly get access to all the computers in a device group.

Hope that helps,
Ylian
