### ISSUE TITLE
MeshAgent not able to connect to MeshCentral

### ISSUE THREAD

**Issue by FrinkMan** [Ylianst/MeshCentral#2915]
I've got two machines on which the MeshAgent won't connect to MeshCentral... Firewall exclusions are entered and even with the firewall off it won't communicate. At first I wondered if it was our corporate proxy, but then I installed it on a couple other machines with the proxy and they connected right away. If I run MeshAgent.exe from the command line, I can see it's getting stuck on "Connecting to wss://mesh.mydomain.com:443/agent.ashx" but I'm not really sure where to go from here. Any suggestions?

**Comment by Ylianst** [comment]
If you have a proxy, you can create a "MeshAgent.proxy" file. This file has the exact same name as the meshagent, but .proxy instead of .exe. Place it along side the meshagent.exe and with notepad, you put "proxy.corporate.com:1234". Once the file is created, stop and start the agent again and see if it works. This is a manual way to specify a proxy.

**Comment by FrinkMan** [comment]
I don't actually know the proxy server address, as it's a third-party program that uses several servers across NA to proxy through, depending on the load per server. I don't think the proxy is the issue though, I'm wondering if there's something machine-specific that's preventing websocket connections...

**Comment by nzalev** [comment]
The proxy *can* change things. You can run meshcentral in debug mode: `node node_modules/meshcentral --debug webrequest`

When the agent connects, what's expected is `WEBREQUEST: (127.0.0.1) /agent.ashx/.websocket`. My hunch is that either the server is not receiving the request, or the response is not making it all the way back to the client. Personally, this is when I would pull out wireshark.

**Comment by FrinkMan** [comment]
The server is definitely receiving the request, if I enable tracing and manually fire the agent, I get a request to agent.ashx in the tracing console from the machine's IP, it just never seems to complete

**Comment by FrinkMan** [comment]
> The proxy _can_ change things. You can run meshcentral in debug mode: `node node_modules/meshcentral --debug webrequest`

The only reason that I've ruled out the proxy is the fact that I've installed it on almost 20 other machines with the exact same proxy, and they've all worked

**Comment by FrinkMan** [comment]
The only thing I'm seeing in `logs` that would signify any error is `[2021-07-17 08:39:09 AM] Info: No certificate was found in db`, although it's not an ERROR or WARNING so I'm assuming it's not critical. I would agree with it not making it back to the client, but I can't figure out why it's only on certain ones

**Comment by Ylianst** [comment]
The `Info: No certificate was found in db` message is normal, agent does this the first time it will install. It's also an annoying message and Bryan removed it for the next version of the MeshAgent.

If you are getting the websocket request from the agent, but it's not showing up... one possibility is that it's connecting to a device group your not expecting. You could add ?debug=1 to the url, click on the device group your expect the device to show up and download the ".msh" file.

![image](https://user-images.githubusercontent.com/1319013/126083114-ce79c961-2480-4b12-88d5-d835524cde8d.png)

You can then go in the remote computer's agent folder and look for the "meshagent.msh". It's a text file, you can open it with notepad and look at it. The important values are the MeshID, ServerIS and MeshServer. Should look like this:

```
MeshID=0xEDBE1BE3771D69DF39D35DF97F7E9A6F7D75DB86F9D9EE3B735EBB7DB6B4E7971EF34D36EBB6B875CF3D7DED1EE7CD5C
ServerID=D99362D5ED8BAEA8BF9E743B34B242256370C460FD66CB62373C6CFCB204D6D707403E396CF0EF6DC2B3A42F735135FD
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx
```

One more thing you can do, go in "My Server" / "Console" tab and type "agentissues"

![image](https://user-images.githubusercontent.com/1319013/126083200-3e45da0b-2cbd-4129-80dc-a21827ffffda.png)

Maybe something will show up there.

**Comment by FrinkMan** [comment]
Looking in the server console for agent issues I see the following:

![image](https://user-images.githubusercontent.com/43939360/126163539-3a8897dd-09c4-4589-8175-3a19f10db738.png)

MeshAgent.msh appears to have the correct settings. Based on that error I am beginning to wonder if it is the proxy with it's SSL Inspection borking it, although it's strange that it would still work on some agents that have the proxy and not others

**Comment by FrinkMan** [comment]
The other thing that really boggles me is that I have another one of the exact same PC's, running the exact same OS, all with the latest updates. One connected fine, and this one refuses to connect

**Comment by Ylianst** [comment]
This error `bad web cert hash` is because the MeshAgent is connecting to a server with a different TLS certificate from your server certificate. This could be a security problem where someone is trying to do a "man-in-the-middle" attack or you did not setup your reverse-proxy correctly.

If you have a reverse proxy, look at this [video on how to set it up correctly](https://www.youtube.com/watch?v=YSmiLyKSX2I).

You can add this line in the setting section of the config.json:

```
"ignoreagenthashcheck": true
```

This will probably fix the problem, but this is not secure. It's possible that there is a proxy that is terminating the TLS connection to see what the agent is doing. The server is detecting this proxy as an attacker.

**Comment by FrinkMan** [comment]
That did it. I'm going to assume now that that machine has a slightly different proxy configuration, so I'm going to contact the proxy provider and see if I can get the .exe whitelisted. Thank-you for your help!

**Comment by Ylianst** [comment]
You can also do:

```
"ignoreagenthashcheck": [ "1.2.3.4" , "2.3.4.5" ]
```

This will ignore the certificate error for specific IP addresses.
