### ISSUE TITLE
Feature Request:  "toggle mouse and input" unchecked by default

### ISSUE THREAD

**Issue by ITOSV41** [Ylianst/MeshCentral#2916]
Not sure if this has been requested before, but I have a scenario in which I am setting up a "view only" instance of MC.

However, I have not been able to  find a way to have the the checkbox for "toggle mouse and input" unchecked by default for all the agents.

I hope my request makes sense and that it is as easy as adding a line on the config.json file.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.8.80 with a new option to turn off remote desktop input. Add the following to the domain section of the config.json:

```
      "desktop": {
        "viewonly": true
      }
```

There title of your request if to unchecked the input checkbox by default. But your request is ready to uncheck it and never allow it to be checked.

**Comment by ITOSV41** [comment]
Hi Ylian,

Thanks for implementing this so quick. It is surely working great.

All the best
