### ISSUE TITLE
AMT Power operations not available in Actions menu unless user is a full administrator of a group

### ISSUE THREAD

**Issue by ServError** [Ylianst/MeshCentral#2918]
I'm trying to set up user control of a machine and would like them to be able to use AMT to control device power.

As things stand their Actions menu only has basic agent controls, and no Intel AMT controls. They instead need to access the Intel AMT tab and use the power actions from there. Ideally I'd like to be able to keep them out of the Intel AMT tab in general to streamline their experience and keep them out of other settings, but at the least I'd like them to have the shortcut in the Actions menu.

The only workaround to give them the same Actions menu items as myself seems to be to make them a full administrator of the group containing the machine, which I don't want to do.

**Comment by ServError** [comment]
Closing this out because the "Wake up" action is smart enough to use AMT when that's what's available, and that fits my needs well enough.

**Comment by Ylianst** [comment]
Right, wake action will try any possible technique to wake (Intel AMT and/or Wake-on-LAN).
