### ISSUE TITLE
ERR: ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.

### ISSUE THREAD

**Issue by Philippe687** [Ylianst/MeshCentral#2919]
Hello All,
I try to fix this error message and I still don't know why the server can't see the 4433 available because it should ;).

![image](https://user-images.githubusercontent.com/29157130/126049934-7afa4f9c-8eaf-49e4-9895-c838547400b9.png)

Maybe I need to modify something on my config.json ?

Thank you in advance for your help.

Best regards,

**Comment by nzalev** [comment]
This happens when the server can't bind to that port. This means something is likely already listening on that port. If you are on windows, you can find it via
```powershell
Get-Process -Id (Get-NetTCPConnection -LocalPort 4433).OwningProcess
```

Make sure that no other part of meshcentral is using 4433 in your config.json as well.

**Comment by Ylianst** [comment]
Port 4433 is the default Intel AMT port is MeshCentral, however this is just a random number and you can set to port to any value you like. Just note that once set to a value, you don't want to move it since you may start configuring Intel AMT to connect to that port. You can change it by adding this line in the settings section of the config.json file:

```
"mpsport":4444
```

Generally if your port 4433 is busy, I could check if your not running another instance of MeshCentral on the same server.

**Comment by Philippe687** [comment]
i set "mpsport":4444 and also open it and now I got this message : ERR: ERROR: MeshCentral Intel(R) AMT server port 4444 is not available. 
@nzalev : I'm on ubuntu 18.04
BR

**Comment by Ylianst** [comment]
That is weird. Can you post your entire config.json, but put XXXXXX for any confidential information? I will try to replicate it.

**Comment by Philippe687** [comment]
Sure,
I just put XXXX on my "pass" for my mail setting; 

Here it is,
Best regards
[config.zip](https://github.com/Ylianst/MeshCentral/files/6835807/config.zip)

**Comment by Philippe687** [comment]
Meshcentral 0.8.79 on ubuntu 18.04.

**Comment by Ylianst** [comment]
I am not seeing anything wrong with your config.json. You don't need to specify `redirAliasPort` if it's going to be the same at the `redirPort`, but that should not have any impact.

If your not going to be using Intel AMT anyway, you can always set this:

```
"mpsport": 0
```

That will remove the feature that allows Intel AMT devices to connect back to your server. Many people will not use that and so, you can safely turn it off.

One things I can imagine is that your running two MeshCentral servers at the same time. Port 80 and 443 will automatically move up to the next available port, but MPS port will not do that. One way to test is to open a browser to the 4433 port and see what you get. Try https://examples.com:4433. You will get an invalid certificate. I fyou ignore the error, you may see:

![image](https://user-images.githubusercontent.com/1319013/126082669-0600c33f-ef59-4d6e-9dcf-b664fd90f0b8.png)

This means that a MeshCentral instance on your server is listening to port 4433. Let me know what you see.

Another option is that somehow (???) your MeshCentral instance does not have rights to listen to 4433. In that case, you could try running MeshCentral as root:

```
sudo node node_modules/meshcentral
```

See if that works.

**Comment by Philippe687** [comment]
Hello Ylian,
I've made the test and it seems to work... Anyway I will cancel this feature and only use the other very ritch features ;)
![image](https://user-images.githubusercontent.com/29157130/126083641-d8b8a368-83b4-42f7-9f09-2b89bff35b32.png)

I also tried to set the "smtp" feature without success. Before I post another issue, do you have  any advice to test this feature ? Where should I see the logs because when I launch the --debug I got "SMTP is working as expected" or something like that... Maybe we can have more details because no mail sent from my installation.

Best regards,

**Comment by Ylianst** [comment]
For SMTP, once setup if you run manually you should see the last line here:

![image](https://user-images.githubusercontent.com/1319013/126088717-e58b9b7d-1ca2-402c-8e48-d53d2434259d.png)

For testing you can use the email command in the "MyServer" / "Console" tab.

![image](https://user-images.githubusercontent.com/1319013/126088748-dd2ad07f-ecac-4f09-8275-441d8867edaa.png)
