### ISSUE TITLE
Install of ws@5.2.0 failed

### ISSUE THREAD

**Issue by uldiseihenbergs** [Ylianst/MeshCentral#2923]
Cross-posting from my docker build.. 
this started after i moved my docker to newer 14-slim base image.

https://github.com/uldiseihenbergs/meshcentral-builds/issues/5

```
Installing ws@5.2.0...
ERROR: Unable to install required module "ws@5.2.0". MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. To manualy install this module try:

   cd "/home/node/meshcentral"
   npm install ws@5.2.0
   node node_modules/meshcentral
```

But i can't replicate it this myself, all working as expected..

**Comment by Ylianst** [comment]
I am not sure what to do about this problem. I certainly can't replicate it.

**Comment by uldiseihenbergs** [comment]
as far as i understand it - ws@5.2.0 ir no more available in repository and you should install ws@5.2.3 instead..
but more me too - can't replicate.
hot to check availability of 5.2.0 ?

**Comment by Ylianst** [comment]
Ha! Let me check that.

**Comment by Ylianst** [comment]
I can still get both, but will test with ws@5.2.3 and change it.

**Comment by Ylianst** [comment]
Ok, made the change. It will be in MeshCentral v0.8.81

**Comment by uldiseihenbergs** [comment]
Thanks! i will check when available and close then.
