### ISSUE TITLE
how to get all events, not only 1000?

### ISSUE THREAD

**Issue by q16marvin** [Ylianst/MeshCentral#2929]
How can i get events from last month for example? Currently via webpage i can only download last 1000 events... Thx!

**Comment by VINISHVV** [comment]
If you are using MongoDB, you can use the "mongo" command to query the events collection of the meshcentral database.

Another option is through  **MeshCtrl.js** You can to pull the event log using command "listevents" .

**Comment by q16marvin** [comment]
hi, i dont use mongodb... with MeshCtrl.js the first events i can see is from 2021-07-01T12:34:12.899Z but we use mesh far longer :)

**Comment by VINISHVV** [comment]
Not sure, may be its due to your configurations / default meshcentral config to reduce the Database size.

Please add below commands under settings sections to increase the DB expiry.

"dbExpire": {
    "events": 31536000,
    "powerevents": 301400,
    "statsevents": 301400
    },

**Comment by Ylianst** [comment]
There is currently no way to get more than 1000 events from the web page. You can use other tricks like going directly into MongoDB, but this is a feature I would like to add. Also, better filtering on the web page would also be very good.

**Comment by Ylianst** [comment]
@nzalev pushed a fix for this with #2931. I will publish a new version on Saturday that includes it.

**Comment by Ylianst** [comment]
Fix will be in MeshCentral v0.8.84.
