### ISSUE TITLE
Generate Login Token in PHP

### ISSUE THREAD

**Issue by tea4tom** [Ylianst/MeshCentral#2932]
Hi Ylianst / all envolved... this is a great piece of kit and I'm only just joining the party - many thanks for your efforts so far.

My question may be a bit dumb but I've been reading the user manual and I feel like I am missing something; I understand that MC can create a loginToken that can be used to automate the login page when embedding, OR MC can generate a loginTokenKey that a remote site can use to create a one time loginKey as and when required.

The manual seems to end the explanation with :
_As illustrated above, we see the business site using the token key to generate a login token and
embed it into the response web page. The user’s browser then loads the iframe that includes both
the URL with the login token for MeshCentral. MeshCentral can then verify the token and allow
the web page to load as expected._

I can't find any official description of what the website is supposed to do with the tokenkey in order to generate a valid token. I have looked in the source of meshcentral.js and attempted to copy the routine from JS to my sites native PHP with no success. I have also found some examples in other languages on this forum that all seemed to have different ways of packaging the cookie data (some hash the cookie HMAC and then encrypt AES 128, others seem to skip the hash and simply encrypt the entire cookie data and it's just confusing the hell out of me. I figure only one method can be the correct one for the server to correctly decrypt the token?

A copy of my code is below (for what it is worth reference wise), I don't expect you to simply do it for me; but if you could point me in the right direction and perhaps let me now where to look for the server response to my tests that would be amazing!

`
// Prepare variables
$cryptKey = "secretkey_generated_by_meshcentralBLAHBLAHBLAHBLAHBLAHBLAHBLA"; 
$cipher = "aes-256-gcm";
$username = "admin";
$plaincookie = "{\"a\":3, \"u\":\"user//$username\", \"once\":" .time() .", \"time\":" .time() ."}"; // plain text login

// Split the key (the MC code seems to use the first 32bits and other code used 'key2' for hashing?
$key1 = substr($cryptKey, 0, 32);
$key2 = substr($cryptKey, 32);

if (in_array($cipher, openssl_get_cipher_methods()))
{

    // Generate an IV
    $ivlen = openssl_cipher_iv_length($cipher);
    $iv = openssl_random_pseudo_bytes($ivlen);
    
    // Create a cypher text of the cookie
    $ciphercookie = openssl_encrypt($plaincookie, $cipher, $key1, $options=0, $iv, $tag);
    
    // Convert the cyphertext to base64 for safer URL usage
    $loginToken = utf8_decode(rtrim(strtr(base64_encode($iv .$tag .$ciphercookie), '+/', '@$'), '='));
    
    // Prepare some debug info on the website side.
    $debugstr = "Cipher Method: " .$cipher ."\n";
    $debugstr .= "Plain cookie: " .$plaincookie ."\n";
    $debugstr .= "IV Len: " .$ivlen ."\n";
    $debugstr .= "IV (rnd): " .$iv ."\n";
    $debugstr .= "Cipher cookie (len): " .strlen($ciphercookie) ."\n";
    $debugstr .= "Token: " .$loginToken ."\n";

   /* 
     Later the variable $loginToken is used to form the URL of the IFRAME element as shown below:
       <iframe src="https://mc.internetdomain.com:443/?login=<?= $loginToken; ?>&hide=13"></iframe>
  */
} else {
  $warning = 'Cipher method not avaialble.';
}
`

**Comment by Ylianst** [comment]
Before answering, I do want to mention that if you need a temporary login token for a given account, you can create one using a different system. This gives you a time limited username and password with limited rights that you can use for tools like MeshCtrl.

![MC2-LoginTokens1](https://user-images.githubusercontent.com/1319013/126737725-bd247bbb-2e58-4b00-b9cb-8a826fc99cb2.png)

**Comment by Ylianst** [comment]
In you do want to create a login token, you first need to get the master key, you get this running:

```
node ./node_modules/meshcentral --logintokenkey
```

That should display the master key in HEX.

You can generate a login token by running this:

```
node ./node_modules/meshcentral --logintoken user\\admin
```

That will generate a login token for the "admin" user in the default domain.

Once you know this is what you want, you take the master key and the source code in MeshCentral to generate login tokens at will. One way you can do this is to split the "encodeCookie()" function out of MeshCentral.js and run that separately from Python. Otherwise, when I get back in the office, I can look at doing the same purely in Python.

**Comment by tea4tom** [comment]
My initial variable statement '$cryptKey' refers to the HEX key obtained by running:

`node ./node_modules/meshcentral --logintokenkey`

A pure Python version of the encryptCookie function would be great if possible, or even a Pseudo code description of what an encryptCookie function is actually doing with the bytes in the HEX key. I'm happy to help document embedding tips and share on here if  I can get my head around it to create some samples.

Has the encryptCookie method evolved over time? It appears to be implemented differently by various examples that I did find and I'm assuming I found old code?

**Comment by Ylianst** [comment]
Looking at #59, someone already build a login token encoder in Python. Here it is, let me know if that works.

```
import time
import hashlib
import secrets
import base64
from Crypto.Cipher import AES
from binascii import unhexlify

def encode(key,user,action=3):
    key         = bytes.fromhex(key)
    key1        = key[0:48]
    key2        = key[48:]
    msg         = '{{"a":{}, "u":"{}","time":{}}}'.format(action, user, int(time.time()))
    iv          = secrets.token_bytes(16)

    #sha
    h= hashlib.sha3_384()
    h.update(key1)
    msg= h.digest() + msg.encode()

    #aes
    a   = AES.new(key2, AES.MODE_CBC, iv)
    n   = 16-(len(msg)%16)
    n   = 16 if n==0 else n
    pad = unhexlify('%02x' % n)
    msg = a.encrypt(msg + pad*n)

    return base64.b64encode(iv+msg, altchars=b"@$").decode("utf-8")
```

**Comment by tea4tom** [comment]
Doing a quick test (at 1am Sunday morning) yielded the same results as previously. An encoded cookie is created using my code that tries to mimic the example you have found but my Mesh Central server simply ignores it in the GET request and the login page is shown. My code follows the same procedure of creating a cookie in string, it includes a "once" value in the cookie json which I found in the MC code I believe.

`
// aquired from mesh server
$cryptKey = "KEY_OBTAINED_FROM_MC_BLAH_BLAH_BLAH"; 
$cipher = "aes-256-cbc";
$plaincookie = "{\"a\":3, \"u\":\"user//admin\", \"once\":" .time() .", \"time\":" .time() ."}"; // plain text login

$key1 = substr($cryptKey, 0, 48); // First 48 bytes
$key2 = substr($cryptKey, 48); // remaining bytes
$ivlen = openssl_cipher_iv_length($cipher); // 16
$iv = openssl_random_pseudo_bytes($ivlen);
 
// SHA HASH USING KEY 1
$hashdigest = hash_hmac('sha3-384', $plaincookie, $key1, false);

// CREATE PADDING FOR HASHED COOKIE
$pad = '';
$xx = 16 - strlen($hashdigest) % 16;
for ($a = 1; $a <= $xx; $a++) {
  $pad .= chr(16 - strlen($hashdigest) % 16);
}
    
// AES 256 CBC USING KEY 2
$ciphercookie = openssl_encrypt($hashdigest .$pad, $cipher, $key2, $options=0, $iv, $tag);

// Base 64 - REPLACE CHARS '+/' WITH '@$'
$loginToken = utf8_decode(rtrim(strtr(base64_encode($iv .$tag .$ciphercookie), '+/', '@$'), '='));
$iframeURL = "https://server-domain.com:443/?login=$loginToken&hide=13";

`
This login token does not work.

Is there somewhere in meshcentral that I can find see a failed login log for the tokens that I try or is the silent rejection the only confirmation that something is not right?

Would a fair procedural description of the process be:

1/ Create **Key_1** from the first 48 char of **MC_TOKEN_KEY**
2/ Create **Key_2** from the **MC_TOKEN_KEY** - **Key_1**
3/ Create a SHA3_384 hash of the JSON cookie using **Key_1**
4/ Pad the **Hashed_Cookie** to ensure length division by 16
5/ Create a **Cipher_Cookie** from the **Hashed_Cookie** using **Key_2** (AES-256-CBC)
6/ Base64 encode **Cipher_Cookie** and replace chars '+/' with '@$' respectively to create **LoginToken**

I will have another play tomorrow and report back to let you know.

Thanks for your time and patience...

**Comment by tea4tom** [comment]
btw - You have renamed this " Genrate Login Token in Python " but my original question refers to **PHP** and that is my ultimate goal. I'll take working examples in whatever language you have if it will help me get my head around what I am doing wrong.

**Comment by Ylianst** [comment]
Doh! PHP, sorry about that. My mistake.

**Comment by Ylianst** [comment]
Here is a basic sample in NodeJS. It should allow you to test encoding and decoding using a master key. I put is a sample master key below for testing. Save this in 'mccookie.js` and run `node mccookie.js`.

```
// Setup crypto and the master key
var crypto = require('crypto');
var key = Buffer.from('584de81cefe79d3aabe0c7d6be7003a13f61f5da17164c78bdc9ac49c79b3b0d2e1f8767d96a2085ae7d16f55b097c757251f41002d21a6477f650898803073fdda1462e6d8a88753d7151bdfc93aa5e', 'base64');

// Encode and decode a cookie
var cookie = encodeCookie({ a: 3, u: 'user\\admin' }, key)
console.log('encoded', cookie);
var decoded = decodeCookie(cookie, key);
console.log('decoded', decoded);

// Encode an object as a cookie using a key using AES-GCM. (key must be 32 bytes or more)
function encodeCookie(o, key) {
    try {
        o.time = Math.floor(Date.now() / 1000); // Add the cookie creation time
        const iv = Buffer.from(crypto.randomBytes(12), 'binary'), cipher = crypto.createCipheriv('aes-256-gcm', key.slice(0, 32), iv);
        const crypted = Buffer.concat([cipher.update(JSON.stringify(o), 'utf8'), cipher.final()]);
        var r = Buffer.concat([iv, cipher.getAuthTag(), crypted]).toString('base64').replace(/\+/g, '@').replace(/\//g, '$');
        //console.log('Encoded AESGCM cookie: ' + JSON.stringify(o));
        return r;
    } catch (ex) { console.log('ERR: Failed to encode AESGCM cookie due to exception: ' + ex); return null; }
};

// Decode a cookie back into an object using a key using AES256-GCM. Return null if it's not a valid cookie. (key must be 32 bytes or more)
function decodeCookie(cookie, key, timeout) {
    try {
        if (key == null) { key = obj.serverKey; }
        cookie = Buffer.from(cookie.replace(/\@/g, '+').replace(/\$/g, '/'), 'base64');
        const decipher = crypto.createDecipheriv('aes-256-gcm', key.slice(0, 32), cookie.slice(0, 12));
        decipher.setAuthTag(cookie.slice(12, 28));
        const o = JSON.parse(decipher.update(cookie.slice(28), 'binary', 'utf8') + decipher.final('utf8'));
        if ((o.time == null) || (o.time == null) || (typeof o.time != 'number')) { console.log('ERR: Bad cookie due to invalid time'); return null; }
        o.time = o.time * 1000; // Decode the cookie creation time
        o.dtime = Date.now() - o.time; // Decode how long ago the cookie was created (in milliseconds)
        if ((o.expire) == null || (typeof o.expire != 'number')) {
            // Use a fixed cookie expire time
            if (timeout == null) { timeout = 2; }
            if ((o.dtime > (timeout * 60000)) || (o.dtime < -30000)) { console.log('ERR: Bad cookie due to timeout'); return null; } // The cookie is only valid 120 seconds, or 30 seconds back in time (in case other server's clock is not quite right)
        } else {
            // An expire time is included in the cookie (in minutes), use this.
            if ((o.expire !== 0) && ((o.dtime > (o.expire * 60000)) || (o.dtime < -30000))) { console.log('ERR: Bad cookie due to timeout'); return null; } // The cookie is only valid 120 seconds, or 30 seconds back in time (in case other server's clock is not quite right)
        }
        //console.log('Decoded AESGCM cookie: ' + JSON.stringify(o));
        return o;
    } catch (ex) { console.log('ERR: Bad AESGCM cookie due to exception: ' + ex); return null; }
};
```

**Comment by tea4tom** [comment]
You're an absolute STAR! That'll be perfect.

Thanks again - I'll get on this first thing (or I should say when I wake up). I'll update on here and hopefully close with a working PHP example I can leave on here in case anyone else should need it - I'm sure I'm not the only backward dev out here using it haha

Tom.

**Comment by tea4tom** [comment]
I've done the following tests:

Created a one time LoginToken using command: 'node ./meshcentral.js --loginToken --u user//{username}' - This worked and bypassed the login page as expected on the [REMOTE_SITE].

So then I updated the STRING in mccookie.js:
`var key = Buffer.from('{my_own_key_created_with_meshcentral_loginTokenKey}', 'base64');`
To use the key provided by my meshcentral server, and I updated the user name:
`var cookie = encodeCookie({ a: 3, u: 'user//{my_username}' }, key)`
(I changed the backslashes for forward slashes as that seems to match the code in meshcentral.js)

When I run 'node ./mccookie.js' it creates an encoded cookie that looks right and decodes it successfully to display the anticipated information. But the cookie it creates **does not work** and the login screen is still displayed. This leads me to believe there is something wrong with my [TOKEN_KEY]?

For the sake of clarity I'm going to use the following convention/definitions:

1. [TOKEN_KEY] = is the literal string of characters returned on the Cli when running 'node meshcentral.js --loginTokenKey'
2. [REMOTE_SITE] = is the 'other' secure site that I wish to be able to bypass the login providing my user has already authenticated.
3. [MC_SITE] = is actually the meshcentral server web interface

In the code you kindly provided, you start start by loading the key with `Buffer.from(STRING, 'base64')`. I am assuming that the STRING here is what I am calling [TOKEN_KEY] and you are decoding it using base64 to an array of binary?
This is the first time I have seen an example of this and as you can see from my OP I was splitting and using the literal string. 

To update my previous procedure notes:
1/ base64 decode MC_TOKEN_KEY to get THE_KEY
2/ Create Key_1 from the first 32 bit of THE_KEY
3/ Create Key_2 from the remainder part THE_KEY  - Is this unused?
4/ Create a JSON obj / STRING: { "a": 3, "u": "user//admin", "time": UNIX_TIMESTAMP / seconds since epoch
5/ Create a Cipher_Cookie from the JSON_Object using Key_1 (AES-256-gcm)
6/ Base64 encode Cipher_Cookie and replace chars '+/' with '@$' respectively to create LoginToken

Thanks,

Tom

**Comment by elihunter** [comment]
> I've done the following tests:
> 
> Created a one time LoginToken using command: 'node ./meshcentral.js --loginToken --u user//{username}' - This worked and bypassed the login page as expected on the [REMOTE_SITE].
> 
> So then I updated the STRING in mccookie.js: `var key = Buffer.from('{my_own_key_created_with_meshcentral_loginTokenKey}', 'base64');` To use the key provided by my meshcentral server, and I updated the user name: `var cookie = encodeCookie({ a: 3, u: 'user//{my_username}' }, key)` (I changed the backslashes for forward slashes as that seems to match the code in meshcentral.js)
> 
> When I run 'node ./mccookie.js' it creates an encoded cookie that looks right and decodes it successfully to display the anticipated information. But the cookie it creates **does not work** and the login screen is still displayed. This leads me to believe there is something wrong with my [TOKEN_KEY]?
> 
> For the sake of clarity I'm going to use the following convention/definitions:
> 
> 1. [TOKEN_KEY] = is the literal string of characters returned on the Cli when running 'node meshcentral.js --loginTokenKey'
> 2. [REMOTE_SITE] = is the 'other' secure site that I wish to be able to bypass the login providing my user has already authenticated.
> 3. [MC_SITE] = is actually the meshcentral server web interface
> 
> In the code you kindly provided, you start start by loading the key with `Buffer.from(STRING, 'base64')`. I am assuming that the STRING here is what I am calling [TOKEN_KEY] and you are decoding it using base64 to an array of binary? This is the first time I have seen an example of this and as you can see from my OP I was splitting and using the literal string.
> 
> To update my previous procedure notes: 1/ base64 decode MC_TOKEN_KEY to get THE_KEY 2/ Create Key_1 from the first 32 bit of THE_KEY 3/ Create Key_2 from the remainder part THE_KEY - Is this unused? 4/ Create a JSON obj / STRING: { "a": 3, "u": "user//admin", "time": UNIX_TIMESTAMP / seconds since epoch 5/ Create a Cipher_Cookie from the JSON_Object using Key_1 (AES-256-gcm) 6/ Base64 encode Cipher_Cookie and replace chars '+/' with '@$' respectively to create LoginToken
> 
> Thanks,
> 
> Tom

In case anybody else runs across this the issue was 
var key = Buffer.from('{my_own_key_created_with_meshcentral_loginTokenKey}', 'base64'); 
needs to be 
var key = Buffer.from('{my_own_key_created_with_meshcentral_loginTokenKey}', 'hex');
