### ISSUE TITLE
Export device information/getDeviceDetails via CLI

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#2933]
Hey Guys, is it possible to automate the export of detailed device information via CLI?  meshctrl.js has DeviceInfo but that is not the same information as getDeviceDetails in meshuser.js.  Is there a way to invoke getDeviceDetails without clicking through to the web interface?  Thanks!

**Comment by Ylianst** [comment]
This is a good feature request. I will add that.

**Comment by Ylianst** [comment]
Just checked in support for this. In MeshCentral v0.8.84 you will be able to do:

```
node ./node_modules/meshcentral/meshctrl.js listdevices --details
node ./node_modules/meshcentral/meshctrl.js listdevices --details --csv
```

First list will give you JSON output, second will give you CSV format. Once published, let me know if that works.

**Comment by Ylianst** [comment]
MeshCentral v0.8.84 was published.

**Comment by cgb** [comment]
Thank you Ylian, it is working perfectly :)

One extra request - listdevices appears to return node data, and listdevices --details returns data for node, sys and net data.
 
listdevices also returns the values for "conn", "powr" and "agct".  Could they somehow be melded into the output of listdevices --details so I can get both sets of data in one call?

**Comment by cgb** [comment]
Oh, and their device group name?  It looks like ListDevices and ListDevices --csv returns the device group name, but the json formats don't for both the details and non-details output...?

**Comment by Ylianst** [comment]
The JSON output has the "meshid" which is the device group identifier... but let me see if I can add the device group name.

**Comment by Ylianst** [comment]
Added meshid and groupname in JSON for detailed and not-detailed JSON in `meshctrl.js listdevices`. Will be in MeshCentral v0.8.86.

**Comment by cgb** [comment]
Thanks Ylian, can confirm groupname is now visible in listDevices.  Thank you very much!
