### ISSUE TITLE
Security weakness in 2FA login process

### ISSUE THREAD

**Issue by C4rb0n** [Ylianst/MeshCentral#2934]
When 2FA is enabled, if a user performs a username (or email address) and password login, MeshCentral waits for token entry, indefinitely. Hours or days later, if someone enters a valid token corresponding to the account that was partially logged in, authentication if successful.  Yes I realize this requires access to the individual's second factor and users routinely have their browsers remember password anyhow.  However, in a situation whereby the user did not actually save credentials but the second factor is via email and is viewable by an otherwise unauthorized person, this would be a problem.

If possible, could you please make an uncompleted 2FA process timeout and completely logout that particular session after about 30 seconds without input?  For those who may want a longer delay, that timeout could be configurable up to a reasonable maximum.  There should also be a minimum acceptable timeout (I'm guessing 5 sec, but someone might want a lower minimum).

Thanks

**Comment by Ylianst** [comment]
Good request.

**Comment by Ylianst** [comment]
Checking the code... the email and SMS 2FA codes are valid for 5 minutes. So while indeed, the web page does stay forever, email and SMS codes will not work after 5 minutes. Looking at the other factors, one time codes, OTP and FIDO don't need an expire time.

Given this, would you want me to have the token request page to go back to the login page after some time? Any refinement to the request?

**Comment by C4rb0n** [comment]
Actually, my point is that the first factor (username and password), once submitted, remains authorized indefinitely as long as the second factor has not yet been requested.  Thus, someone who does not know the username and password, but has access to a device or email client that can provide the second factor, could stumble upon a partially logged in account, hours or days later, and simple click to make the second factor request, enter it, and gain access.

**Comment by Ylianst** [comment]
Ok, I have been working on this, will be in MeshCentral v0.8.85.

![image](https://user-images.githubusercontent.com/1319013/126882303-038aebb6-aad6-4098-ba8e-ab80ab1f158c.png)

The default is 5 minutes, but you can set it to any value you like. Let me know if that works.

**Comment by C4rb0n** [comment]
Thanks for this.  I'll check it out once available.  Is it correct that the actual password is not left filled in after reset, as your screenshot seems to suggest, and those dots are just arbitrary?

**Comment by Ylianst** [comment]
In testing with Firefox, the browser will automatically add in the username and password if allowed. So, resetting the session will go back to the login page with the password filled. This is really browser policy, not MeshCentral settings.

**Comment by Ylianst** [comment]
MeshCentral v0.8.85 is published.

**Comment by C4rb0n** [comment]
I can verify that it's working as expected.  Thank you.
