### ISSUE TITLE
Token origin not enforced during 2FA

### ISSUE THREAD

**Issue by C4rb0n** [Ylianst/MeshCentral#2935]
If an account is partially logged in (i.e. awaiting token factor) at two separate locations, the session that did not request the token can still use that token, if received, to login.  Since MeshCentral does not timeout partially logged in sessions, a possible scenario is as follows: Person 1 entered username and password at Site A but got distracted and left in a rush before completing 2FA.  Since authentication was not completed, Person 1 would not have thought to end the session somehow.  To make matters worse, Person 1 also forgot cell phone (the second factor) and cell phone is configured such that notifications show content on lock screen.  Person 1 gets to Site B and tries to login, making the token request.  Person 2 at Site A happens to be at the keyboard and in possession of Person 1's cell phone when the token notification appears on the phone display.  Person 2 keys in token and does bad things. :-(

Effect is the save for email tokens.

By the way, I realize that the Person 2 could have just clicked on the 2FA SMS or Email button themselves; however, my point is that it should not be possible for the session that did not request that token to be authorized using that token.

**Comment by Ylianst** [comment]
Given data in #2934, let me know if anything needs to be done for this one. I could tie the SMS and Email code to the session, but I am hesitant to do this since a refresh of the browser would invalidate the codes and codes are 5 minute time limited. Let me know if you see want to press for this.

**Comment by C4rb0n** [comment]
The #2934 resolution seems like a reasonable mitigation to me.  If someone decides to disable and leave disabled the #2934 timeout, it's unlikely that person is all that concerned about security.  So, yeah I'm fine with your decision.  Thanks for the quick resolution.

**Comment by Ylianst** [comment]
Thank you for posting this request. Always a good idea to re-visit security and I do agree that a timeout on the token request page is a good idea.
