### ISSUE TITLE
Clipboard issue from Win10 --> Linux

### ISSUE THREAD

**Issue by bodycount28** [Ylianst/MeshCentral#2937]
Hi,

Not sure if this has been reported, I tried searching but couldn't find anything:

**From Win10 remoting into a Linux desktop (Mint 20.2)**
- I can not upload clipboard contents from Win10 to Linux
- I am able to download clipboard from Linux to Windows

**From Linux desktop remoting into Win10**
- Clipboard functions appear working in both directions

**Steps I've tried:**
- I've used both the quick upload/download buttons in the lower right as well is the 'Clipboard' button on the left, same results.
- I've also tested this on both Chrome and Brave browsers with same results.

I'm running version 0.8.83.

Any help or insight is appreciated!

**Comment by krayon007** [comment]
Do you have xclip installed on your Linux machine? By default the agent uses the x11 buffer which is not accessible from all apps. But if you have xclip installed it will try to use that, which provides a better/seamless experience.

**Comment by bodycount28** [comment]
xclip seems to be working better, thanks for the tip!
