### ISSUE TITLE
Missing "Desktop" "Terminal" " Files" Tab after rebooting

### ISSUE THREAD

**Issue by arduin0guru** [Ylianst/MeshCentral#2938]
After rebooting MeshCentral server I notice one of the group is missing "Desktop" "Terminal" " Files" Tabs. I moved some of the computer to different group , No change. Transfer to new group same thing. I rebooted again , same thing. I tried all backup in last week- no change. 
One more thing I observed is USER is missing in MY DEVICE Tab..
Is there any way we can see database to verify everything is fine or any utility to repair database ???
Thanks in advance..

**Comment by Ylianst** [comment]
Hi. Did you update your MeshCentral server from a very old version?

Click on the device and go to the "console" tab. Let me know what you see just left of the "Agent Actions" button. You can also type "help" and "versions" and let me know what you see.

![image](https://user-images.githubusercontent.com/1319013/126885327-ccd2ab52-3a5b-48ed-8fad-f333592c68ff.png)

You can click on "Agent Action" button and try the "Clear the core" and "Upload default server core" options.

![image](https://user-images.githubusercontent.com/1319013/126885352-74dcb431-d6da-4349-b9d9-36bba6230b0a.png)

You can also try the "agentupdate" command.

![image](https://user-images.githubusercontent.com/1319013/126885358-c335c847-3347-4698-a30f-04537554525c.png)

Let me know what you see.
Ylian

**Comment by arduin0guru** [comment]
Help Version Output
{
  "openssl": "1.1.1i",
  "duktape": "v2.3.0",
  "commitDate": "2021-02-07T23:26:53.000Z",
  "commitHash": "43c5f2d1b57a9f477d3afec13e2873ed19bfd573",
  "compileTime": "15:55:41, Feb  7 2021"
}
