### ISSUE TITLE
Warning Unrecognized configuration option "agentcustomization". in configuration server

### ISSUE THREAD

**Issue by Ajilis** [Ylianst/MeshCentral#2940]
Hi,

We are on Server version 0.8.85 / Docker: typhonragewind/meshcentral:latest

We get these warning, does its normal and not implemented in this version ?

ATTENTION: Unrecognized configuration option "agentcustomization".
ATTENTION: Unrecognized configuration option "androidcustomization".
ATTENTION: Unrecognized configuration option "devicemeshrouterlinks".

**Comment by nzalev** [comment]
You have not given your config.json, so I cannot say for sure, but you have likely put it in the wrong location within the config. Make sure that these options are within a given domain. 

```javascript
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "lockagentdownload": true,
    "mariadb": { 
        ...
    },
    ...
  },
  "domains": {
    "": {
      "agentcustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      },
      "androidcustomization": ...,
      "devicemeshrouterlinks": ...
    }
  }
}
```
For more info, you can find the config schema at https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json

**Comment by Ylianst** [comment]
Warnings like these show up when you put an unrecognized key name at the root level of the config.json.

```
ATTENTION: Unrecognized configuration option "agentcustomization".
ATTENTION: Unrecognized configuration option "androidcustomization".
ATTENTION: Unrecognized configuration option "devicemeshrouterlinks".
```

So yes, these keys must be placed in the domain section of the config.json, not at the root level.
