### ISSUE TITLE
A title without a back button when using the hide option

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#2942]
We use references to nodes in MeshCentral in the documentation. Add the hide parameter there with numbers 21, 23 and 31. When 31 is set, it is difficult for the user to get anywhere else, and we are happy with that.
But when showing the title at values of 21 and 23, I don't want to have a back button. which allows you to get to the entire list of devices.
Is there a way to hide it? Could there be an additional parameter or do some additional logic that if the left bar is hidden then the back button should not be displayed?
![image](https://user-images.githubusercontent.com/51225180/126912266-2476d3be-c9a3-4740-acaf-43323e2a3718.png)

**Comment by Ylianst** [comment]
Oh yes, that is a good request. Should not be too difficult to do.

**Comment by Ylianst** [comment]
Ok, in the next version MeshCentral v0.8.86, I added a new value 32 to hide the back buttons. So, add 32 to your current hide number and it should work.

**Comment by AntonAndreevichMoroz** [comment]
Thanks a lot. It works. But unfortunately not everywhere. I can still see the back button on the Details and Console tabs
![image](https://user-images.githubusercontent.com/51225180/127258315-282aeb77-b404-4748-8945-6cd550f7e7dc.png)
![image](https://user-images.githubusercontent.com/51225180/127258400-a271907c-ed57-41ef-9f96-464eb40a26d7.png)

**Comment by Ylianst** [comment]
You are right. Fixed, will be in MeshCentral v0.8.88.

**Comment by AntonAndreevichMoroz** [comment]
Everything works perfectly. Thanks for the quick solution
