### ISSUE TITLE
agent crash when installing in Win7(64)

### ISSUE THREAD

**Issue by Susieji** [Ylianst/MeshCentral#2943]
hi,

When installing mesh agent on Win7 (64bit), it is crashed.

Agent version: 0.2.1.3
HW: Dell vostro3900: i7-4790 @3.60GHz (screenshot in below attachment link )
OS: Windows7Ultimate - 1906 [7601] (64bit)
(There are 4 computers have the same OS, only this one crash, and the crash can reproduce)

Attach the log files: 
[https://intel-my.sharepoint.com/:f:/p/shujie_ji/ErQpUyaF559GqABccWvkIewB2od6WG82HUvn_45RBsOYRw?e=UTqMoh](url)

Could you kindly help to check? thanks.

**Comment by krayon007** [comment]
Which service pack is this machine running?

**Comment by Susieji** [comment]
@krayon007  Service Pack 1. Thanks

**Comment by krayon007** [comment]
Went down a few dead-ends  trying to reproduce what we see in your logs, but haven't been able to reproduce your issue, but that was with testing with a different windows version. I just downloaded Windows 7 64 bit Korean SP1, in hopes of seeing if it is possibly related to UTF8 support, as I know earlier I found differences in Windows API behavior between US-EN and other versions of Windows 7 that was not using a latin encoding.

**Comment by Susieji** [comment]
Thanks Bryan.
More info: the OS is Windows 7 64 bit Chinese SP1. And we have checked another computer with the same OS(Windows7 Ultimate - 1906 [7601] 64bit), it is also Chinese SP1, but work well.

**Comment by Susieji** [comment]
Thanks Bryan!
More info: the OS is Windows 7 64 bit Chinese SP1. And we have checked another computer with the same OS(Windows7 Ultimate - 1906 [7601] 64bit), it is also Chinese SP1, but working well.
Anything need we offer, please don’t hesitate to connect me.

Br,
Susie(书杰)

**Comment by Susieji** [comment]
Ji, Shujie would like to recall the message, "[Ylianst/MeshCentral] agent crash when installing in Win7(64) (#2943)".

**Comment by krayon007** [comment]
I was working on an agent build where I modified a few things to address a previous crash, that I only rarely saw, but looks very similar to what you saw... I've been running tests all day so far with it, and cannot get it to crash on my Win 7 test VM... But running the same test suite on the current deployed agent, I'm able to reproduce a crash fairly quickly on the same VM...  I'll post a test binary that I'd like you to test, to see if it works for your system shortly.

**Comment by Susieji** [comment]
Thanks for your efficient work.
Sure, I will complete support the testing.

**Comment by krayon007** [comment]
[MeshService64.zip](https://github.com/Ylianst/MeshCentral/files/6927496/MeshService64.zip)

Sorry for the long delay, I ran into some issues when I was doing testing, but I resolved those. You can try this binary and see if it works better for you. You can unzip it, and name it the same as your existing binary, then you can install it, in the following manner:

`MeshService64 -fullinstall --disableUpdate=1 --copy-msh=1`

Instead of MeshService64, call it whatever the binary name is. Also make sure your existing .msh file is in the same folder when you run this command, as it will use it to install the service. This will install the service with self-updates disabled, otherwise it will auto-update to whatever version is contained by your server.

**Comment by Susieji** [comment]
It works. No reproduction with your binary.
Thanks Bryan!

**Comment by Susieji** [comment]
found a issue:
KVM is work, but mesh report: "Unknown command 82 24" in the callback of the function obj.ProcessBinaryCommand = function (cmd, cmdsize, view) 
it is only reported in this binary.

**Comment by Ylianst** [comment]
Hi. For the report "Unknown command 82 24", this is not a problem with the agent. The new version of the agent will send information to the server of how many displays the agent computer has and there relative positions. On the server, in file `meshcentral\public\scripts\agent-desktop-0.0.2.js", find this method:

```
obj.ProcessBinaryCommand = function (cmd, cmdsize, view) {
```

And add the section 'case 82:' in the switch statement:

```
            case 65: // Alert
                var str = String.fromCharCode.apply(null, view.slice(4));
                if (str[0] != '.') {
                    console.log(str); //alert('KVM: ' + str);
                    if (obj.parent && obj.parent.setConsoleMessage) { obj.parent.setConsoleMessage(str); }
                } else {
                    console.log('KVM: ' + str.substring(1));
                }
                break;
            case 82: // DISPLAY LOCATION & SIZE
                if ((cmdsize < 4) || (((cmdsize - 4) % 10) != 0)) break;
                var screenCount = ((cmdsize - 4) / 10), screenInfo = {}, ptr = 4;
                for (var i = 0; i < screenCount; i++) { screenInfo[(view[ptr + 0] << 8) + view[ptr + 1]] = { x: ((view[ptr + 2] << 8) + view[ptr + 3]), y: ((view[ptr + 4] << 8) + view[ptr + 5]), w: ((view[ptr + 6] << 8) + view[ptr + 7]), h: ((view[ptr + 8] << 8) + view[ptr + 9]) }; ptr += 10; }
                //console.log('ScreenInfo', JSON.stringify(screenInfo, null, 2));
                break;
            case 87: // MNG_KVM_INPUT_LOCK
                if (cmdsize != 5) break;
                if ((obj.RemoteInputLock == null) || (obj.RemoteInputLock !== (view[4] != 0))) {
                    obj.RemoteInputLock = (view[4] != 0);
                    if (obj.onRemoteInputLockChanged) { obj.onRemoteInputLockChanged(obj, obj.RemoteInputLock); }
                }
                break;
            case 88: // MNG_KVM_MOUSE_CURSOR
                if ((cmdsize != 5) || (obj.stopInput)) break;
                var cursorNum = view[4];
                if (cursorNum > mouseCursors.length) { cursorNum = 0; }
                xMouseCursorCurrent = mouseCursors[cursorNum];
                if (xMouseCursorActive) { obj.CanvasId.style.cursor = xMouseCursorCurrent; }
                break;
            default:
                console.log('Unknown command', cmd, cmdsize);
                break;
        }
```

That should fix it. You can also update to latest `agent-desktop-0.0.2.js` file. Hope that helps.

**Comment by Susieji** [comment]
Nice received, thanks Yilian for your clear explanation.

**Comment by Ylianst** [comment]
Latest MeshCentral v0.8.98 has all new MeshAgent for Windows, Linux, macOS and BSD. The new agent will have the Windows 7 SP1 fix included.

**Comment by Susieji** [comment]
we will with ISV to update the MeshCentral to v0.8.98 and verify the issue status, thanks.

**Comment by Ylianst** [comment]
Ok. Please close the issue if the fix is verified. Thanks you.

**Comment by Susieji** [comment]
Sure, we will. Thanks Ylian and Bryan.
