### ISSUE TITLE
Tags for releases?

### ISSUE THREAD

**Issue by lheckemann** [Ylianst/MeshCentral#2944]
It looks to me like the last release tag was made for v0.7.65. Is there any chance that tagging could be introduced again for new releases?

**Comment by krayon007** [comment]
I usually tag server releases that contain agent updates, so that I can tag the agent repo accordingly, to keep track of which versions contain which updates.

**Comment by Ylianst** [comment]
For context, I think we are talking about tags in the MeshAgent repository. Bryan will tag a agent when it gets shipped into MeshCentral.

**Comment by lheckemann** [comment]
So MeshCentral tags (https://github.com/Ylianst/MeshCentral/tags) are only produced when the agent is updated?

**Comment by Ylianst** [comment]
Ok, you where not clear as to what tags you where talking about. For version information on MeshCentral, look at the [commit log](https://github.com/Ylianst/MeshCentral/commits/master). You will see for example "Version 0.8.85" in the comment.

**Comment by lheckemann** [comment]
Extracting the version information only from the commit log has a couple of disadvantages:

- The information isn't available without cloning the repo or manually browsing through the github API (`git ls-remote` can resolve a tag to a commit hash without getting the whole repo)
- No guarantee of uniqueness
- It's not possible to check out a specific version as it would be with tags (`git checkout v0.8.85`)

Do you have a particular reason not to tag, or could you maybe start creating them again?

**Comment by lheckemann** [comment]
I see you're tagging again, thanks <3

**Comment by lheckemann** [comment]
This isn't really completed? If it's a wontfix I can accept that, but completed seems off to me.
