### ISSUE TITLE
Expand / collapse button not working for sort options "Group-Tags"

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#2946]
Dear Ylian,

Expand / collapse button not working for sort  options "**Group-Tags**"

**Comment by Ylianst** [comment]
Thanks for reporting this. I will work on it.

**Comment by Ylianst** [comment]
Will be fixed in MeshCentral v0.8.86.

**Comment by VINISHVV** [comment]
@Ylianst 
In Earlier version while selecting "Group-Tags" only sub groups is visible to users ( Main group is not visible).
But now all the groups including subgroups visible to the user.

**Comment by Ylianst** [comment]
Is this related to this issue? If you want a new "Group-Tags only" option that does not show the main group, can you open a new issue?

Also, is this issue above solved now? Thanks.
