### ISSUE TITLE
A big "thank you" from me!

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#295]
I wasn't sure where else to send my feedback, so I decided to make this issue. I found out about MeshCentral about a year ago and have been following the project closely ever since then. I am very impressed by the dedicated development team. I made numerous bug reports and feature requests over the last several months and the team fixed all of them in a short amount of time and implemented the requested features without a hitch.

I have since founded my own LLC which offers MeshCentral as SaaS to small and medium-sized businesses. I demoed the software at a local convention in Germany a few months ago and the interest from the industry has been overwhelming. I will soon reach the point where I can quit my day job and live off of the revenue generated by my business. My LLC is also going to become an official partner of Intel soon which I expect is going to help drive even more customers my way.

Thank you for making this awesome piece of software! I hope your management hears about the positive impact that they're having on the day-to-day operations of businesses of all kinds.

**Comment by jsastriawan** [comment]
Great to have you onboard as a partner, Aaron.

**Comment by Ylianst** [comment]
Thank you so much for opening an "issue" like this, it's very much appreciated! I love working on this project and having a supportive community makes it such much better. This is also timely as I am looking at 73 issues to fix, having issue number 74 be this one is wonderful.

Feel free to promote your LLC when appropriate, I am very supportive of anyone turning MeshCentral into a commercial offering and promoting Intel products at the same time. I feel like it makes my life easier. Don't hesitate to ask if I can help.

**Comment by PathfinderNetworks** [comment]
Whalehub, how are you using it as a SaaS service?  Just curios.  I've been using MeshCentral in my business (I've been 100% self employed since 2004 but have had my own IT business since 1997) for about 5 years now.  It's absolutely crucial to my business as I use it to remotely manage endpoints and servers for my clients.  But I don't charge my clients for MeshCentral itself- it's just one of the tools I use.  But I'd love to hear how others are using it.  BTW, I moved to MeshCentral from LogMeIn and have never looked back.

**Comment by whalehub** [comment]
@PathfinderNetworks I'm afraid the specifics of that are a trade secret. I previously used TeamViewer and have also never looked back after switching to MeshCentral.

**Comment by Ylianst** [comment]
Ok, will close this one. But I do appreciate any feedback a lot. Please open more issue like this one! Apologies for the last week, I was very focused on the MeshCentral Intel AMT ACM activation feature and new version of MeshCommander. I will try to get to more GitHub bugs.
