### ISSUE TITLE
Update Meshagents to new url

### ISSUE THREAD

**Issue by haxmachine** [Ylianst/MeshCentral#2950]
Hi all,
is there a quick way to update the agents to a new url
example 
Old url is support.test.com to new url itsupport.test.com

**Comment by Ylianst** [comment]
Look for the "meshagent.msh" file in the same folder as the "meshagent.exe". You can edit it using notepad, change the address and restart the agent. Of course, if the new address contains a completely new server with new authentication certificates, you will have replace the entire .msh file. If only the DNS name changed, you can just edit the .msh and restart the agent.

Hope that helps.

**Comment by haxmachine** [comment]
yes that works, found it in one of your threads, i was hoping there was a way to send out a command in meshcentral to update the urls on all agents at once.
Wishful thinking.

**Comment by Ylianst** [comment]
Well, there is a way to run a command on a batch of devices at once. You can select devices, hit "Group Action" and there is an option to run a command. You could craft commands to do this, but I have not tried it.

**Comment by haxmachine** [comment]
ok that might work.
is there a command in console to restart the agent?

**Comment by Ylianst** [comment]
A quick look online:

```
net stop [service name] && net start [service name]
```

But maybe there are better options.

**Comment by haxmachine** [comment]
yeh i was using that in the send batch command using the net stop net start
ill test it on a couple first

**Comment by haxmachine** [comment]
yes the batch command does work, so long as the user or agent has permissions to the service
