### ISSUE TITLE
Disable "Remember this Device"

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#2951]
Is there already a way to disable the "Remember this Device for 30 days" option so that users are forced to use their 2FA everytime?

**Comment by plwc** [comment]
I have tried "twoFactorCookieDurationDays": 0 but that seems to have no effect.

**Comment by Ylianst** [comment]
Sure, I can add that.

**Comment by plwc** [comment]
I managed to get it working. I just had to move the twoFactorCookieDurationDays": 0 from settings to domaindefaults.

**Comment by Ylianst** [comment]
Indeed, I just looked a the code and config.json schema and this is already implemented. 0 will disable the remember device option.
