### ISSUE TITLE
Confusing Hardware Key Logon

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#2952]
This is what you see after entering your username and password when a hardware key has been setup.
![image](https://user-images.githubusercontent.com/44763211/127283401-5faa5585-59c6-462e-81fc-781b07638287.png)

To me this looks like you put your security key in and tap it at this screen and it's not until you hover over the picture that it becomes more obvious that you need to click on it to use your key.

I think most people who setup a key would prefer to have it ask them to use their key straight away rather than going to the token backup and have token backups along with any other 2fa they have already setup presented as an option if the key login fails.

**Comment by Ylianst** [comment]
The problem is that multiple 2FA can and should be setup. Current options are: OTP, Backup Codes, FIDO keys, email, SMS and Android Push. The 2FA screen needs to handle all cases.

**Comment by plwc** [comment]
E-Mail, SMS and Android Push?   I didn't think these were options.

I would argue that hardware keys are regarded by many as the most secure 2FA we currently have available and that users of them would expect that it is the default option when enabled to keep interaction to a minimum.

Most services I have tried so far will request it by default when enabled but give an option to use another method if you cancel the key login or it fails.

What is there now isn't too bad once you know how it works but I feel like the other way has a slicker more streamlined feel.

**Comment by Ylianst** [comment]
I have videos on [two-factor auth OTP, Backup and FIDO](https://www.youtube.com/watch?v=luLZKcma9l0) and [Push Notification 2FA](https://www.youtube.com/watch?v=AraEFxFUxHQ). I do want to make a future video on SMS.

I just added a new `autofifo2fa` option in the domain, passwordRequirements section that will auto-trigger security key usage if the account has one setup.

```
      "PasswordRequirements": {
        "min": 8,
        "max": 64,
        "upper": 1,
        "lower": 1,
        "loginTokens": true,
        "autofido2fa": true                      <---------
      }
```

Let me know if it works ok. That will be in MeshCentral v0.8.88 when next published.

**Comment by Ylianst** [comment]
I will post this on Twitter once MeshCentral v0.8.88 is published.

![image](https://user-images.githubusercontent.com/1319013/127387274-dedbf9f0-a54e-47c6-aee9-110952e891b0.png)

**Comment by plwc** [comment]
Works perfectly :)

Thankyou, login is really nice now!
