### ISSUE TITLE
Typo in balloon - very, very low priority!

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#2953]
For once, a simple one! When the balloon appears in the top right hand side of the interface prompting the user to add two factor backup codes, the 2nd sentence has a typo in it:

"If the current factor is lost, there is **[-not +no]** way to recover this account."

**Comment by Ylianst** [comment]
Thanks for reporting that! I like these reports, super easy to fix. Keep them coming. Will be fixed in MeshCentral v0.8.88.
