### ISSUE TITLE
Filter does not clear listing if X button is used

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2955]
Its a tiny thing, but whenever I use the filter field to find a pc, if I just change what is typed or backspace it all it works as it should (I think), but clicking the X does not clear the listing. I think it should. 
![2021-07-28](https://user-images.githubusercontent.com/4949495/127403549-74f90430-4d65-4ad6-8717-c178af84666a.png)

PS: the X clears the field, but not the listing results

**Comment by Ylianst** [comment]
Your right. It works in FireFox, but not in Chrome.

**Comment by Ylianst** [comment]
Put in a fix for this, will be in MeshCentral v0.8.89.

**Comment by rodrigolzd** [comment]
It´s working now! Thanks!
