### ISSUE TITLE
Minor Display Bug

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2956]
In list view, the colspan set on header rows is not taking into account the newly added "Last Seen" column (which was a great addition). It's not affecting usability but it does look a bit odd when the header stops before the end of the row:

![image](https://user-images.githubusercontent.com/16453878/127425145-b8b41c27-66ee-45f5-81ee-b0d99dd5f3e6.png)

**Comment by nzalev** [comment]
That's a bit strange. I remember dealing with this when I first prototyped it a while back, but I'm not getting the same results:
![Screenshot from 2021-07-29 11-11-06](https://user-images.githubusercontent.com/63608819/127517711-c3e3bad2-984e-490c-9e2d-30f66c44cfd1.png)

I tested with Firefox and Chromium. What browser are you using?

**Comment by PetieM** [comment]
I'm seeing this behavior across the board but it's not actually exclusive to the new column and more seems to be a function of how many columns are selected. I have all but the Router links showing and am getting that header issue. If I disable Last Seen and enable Router Links, I see the same one column gap. If I enable both, that gap grows to two columns.

**Comment by nzalev** [comment]
Thanks. I see the issue. It's column span is hard coded to 5, so it will only ever cover 5 columns. I will submit a patch.

**Comment by PetieM** [comment]
Just FYI, setting the colspan to a greater number of columns than shown will technically work but breaks in table-layout: fixed display modes so it's best avoided. It would likely be better to grab the number of displayed columns on change and dynamically update the colspan value at that time (assuming that's not already your plan).

**Comment by nzalev** [comment]
Yes, that's already the plan. The selected columns are stored in an array, `deviceViewSettings.devsCols`, so it is just a matter of taking length and adding 1 :)

Have to do it for each sort type though - since the header is generated separately for different view types.

**Comment by Ylianst** [comment]
Oh dear. I switched `colspan` to 99 and it seemed to work before I came here and read your comments. @nzalev let me know if you are working on it, I will not touch it.

**Comment by nzalev** [comment]
I'm about to push the fix

**Comment by nzalev** [comment]
@Ylianst please see PR. Other device headers (power, group-tag, etc.) also need to be updated.

**Comment by Ylianst** [comment]
Nicely done! The solution is very clean and elegant.

**Comment by PetieM** [comment]
Visually, this is looking perfect but there still seems to be an issue with the calculated colspan. It's adding one more column than needed which, again, won't break anything as far as how it renders but technically isn't correct and will break the layout if table-style: fixed is ever applied for any reason.

**Comment by nzalev** [comment]
The calculated colspan should be exactly what's needed. Keep in mind the name of the device is one column. With Last Seen selected for example, we expect the number of columns to be calculated at 2, which we see:
![Screenshot from 2021-07-29 22-58-34](https://user-images.githubusercontent.com/63608819/127593206-d491f9d6-0744-4a4a-94cb-a7b84c3baa3b.png)

If you manually set the colspan to 1, you will see the effect:
![Screenshot from 2021-07-29 22-58-48](https://user-images.githubusercontent.com/63608819/127593319-f4cf2d21-b23a-417d-9631-7ebafa6fa533.png)

Hope that clears things up. 

PS: if you have device description selected, it does not currently add an extra column but does affect colspan - I'm not sure if it's fully implemented yet.

**Comment by PetieM** [comment]
> PS: if you have device description selected, it does not currently add an extra column but does affect colspan - I'm not sure if it's fully implemented yet.

That's the culprit. I do indeed have description enabled, mostly just to see how it works. Counting the <td>s in each row, I get one more colspan than I do cell but that makes sense if the description is intended to eventually be its own column. As implemented now though, the description is floated to the right of the first column which means, assuming it is going to stay like that, it doesn't need to be counted in the colspan calculation.

**Comment by Ylianst** [comment]
FYI, this issue caused #2967. I just fixed it and quickly published v0.8.91. Hopefully the fix also takes care of the description column.

**Comment by nzalev** [comment]
> FYI, this issue caused #2967. I just fixed it and quickly published v0.8.91. Hopefully the fix also takes care of the description column.

I read through it - I apologize, that is my mistake. I am glad you got it fixed quickly.

The new commit also takes care of the description column.

**Comment by Ylianst** [comment]
No need to apologize, these things happen all the time. I had not caught that when I reviewed the code.
