### ISSUE TITLE
Sophos UTM appliance as Reverse Proxy

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#2958]
I have windows installation of MeshCentral behind Sophos UTM9. Im setting up reverse proxy, but it seems i have wrong config.json settings. Can anyone help me setting the right config? 
Reverse prox runs on external router and it is not on same machine as MeshCentral.

```
{
   "settings": {
      "cert": "rdp.hsi.si", 
      "port": 443,
      "TlsOffload": "127.0.0.1",
      "wanonly": true, 
      "_minify": true, 
      "webrtc": true, 
      "agentpong": 200, 
      "allowhighqualitydesktop": true, 
      "autobackup": {
         "backupIntervalHours": 24, 
         "keepLastDaysBackup": 60, 
         "_backupPath": "C:\\backups"
      }, 
   }, 
   "domains": {
      "": {
         "certUrl": "https://172.16.16.1:443/"
      }
   }
}
```

**Comment by Scaff31** [comment]
Try this

{
"settings": {
"cert": "rdp.hsi.si",
"port": 4439,
"AliasPort": 443,
"TlsOffload": "IP_Sophos",
"wanonly": true,
"_minify": true,
"webrtc": true,
"agentpong": 200,
"allowhighqualitydesktop": true,
"autobackup": {
"backupIntervalHours": 24,
"keepLastDaysBackup": 60,
"_backupPath": "C:\backups"
},
},
"domains": {
"": {
"certUrl": "https://meshcentral.domain.tld/"
}
}
}

on your reverse proxy set real server listen on port 4439

I'm using sophos i use HAProxy but it's work for me with this conf

**Comment by Ylianst** [comment]
The important two changes are these:

```
    "port": 4439,
    "AliasPort": 443,
```

MeshCentral will listen to port 4439, but expect that it's really listening to port 443. You then have to setup your reverse proxy to forward MeshCentral connections to port 4439. You should to the same for port 80:

```
    "RedirPort": 800,
    "RedirAliasPort": 80,
```

Here, the HTTP port is listening on port 800 but expecting to really be listening to port 80. You can then route MeshCentral HTTP port 80 connections to port 800.

**Comment by alesribic73** [comment]
Before i continue with Sophos, i want to update certificate. Im using latest version 0.9.40
This is my LE and LEEVENTS

> le
{
    "configOk": true,
    "leDomains": [
        "rdp.hsi.si"
    ],
    "challenges": {},
    "production": true,
    "webServer": true,
    "certPath": "C:\\Program Files\\Open Source\\MeshCentral\\meshcentral-data\\letsencrypt-certs",
    "cert": "Present",
    "daysLeft": -7
}
> leevents
2. 11. 2021 15:03:39 - Getting certs from local store (Production)
2. 11. 2021 15:03:39 - Reading certificate files
2. 11. 2021 15:03:39 - Setting LE cert for default domain.
2. 11. 2021 15:03:47 - Certificate has -7 day(s) left.
2. 11. 2021 15:03:47 - Asking for new certificate because of expire time.
2. 11. 2021 15:03:47 - Generating private key...
2. 11. 2021 15:03:47 - Setting up ACME client...
2. 11. 2021 15:03:47 - Creating certificate request...
2. 11. 2021 15:03:48 - Requesting certificate from Let's Encrypt...
2. 11. 2021 15:07:12 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80

Port 80 is open. also 443

**Comment by alesribic73** [comment]
Update

> leevents
2. 11. 2021 15:03:39 - Getting certs from local store (Production)
2. 11. 2021 15:03:39 - Reading certificate files
2. 11. 2021 15:03:39 - Setting LE cert for default domain.
2. 11. 2021 15:03:47 - Certificate has -7 day(s) left.
2. 11. 2021 15:03:47 - Asking for new certificate because of expire time.
2. 11. 2021 15:03:47 - Generating private key...
2. 11. 2021 15:03:47 - Setting up ACME client...
2. 11. 2021 15:03:47 - Creating certificate request...
2. 11. 2021 15:03:48 - Requesting certificate from Let's Encrypt...
2. 11. 2021 15:07:12 - Failed to obtain certificate: connect ETIMEDOUT 195.78.83.22:80
2. 11. 2021 15:10:23 - Failed to respond to challenge, token: letsdebug-test, table: {}.
2. 11. 2021 15:10:24 - Failed to respond to challenge, token: yGfFVLye24IXx6ZgbGw_YQd89xuWI4hf5qGjK8o0Ruc, table: {}.
2. 11. 2021 15:10:24 - Failed to respond to challenge, token: yGfFVLye24IXx6ZgbGw_YQd89xuWI4hf5qGjK8o0Ruc, table: {}.
2. 11. 2021 15:10:25 - Failed to respond to challenge, token: yGfFVLye24IXx6ZgbGw_YQd89xuWI4hf5qGjK8o0Ruc, table: {}.
2. 11. 2021 15:10:28 - Failed to respond to challenge, token: yGfFVLye24IXx6ZgbGw_YQd89xuWI4hf5qGjK8o0Ruc, table: {}.

**Comment by alesribic73** [comment]
Update: 
I succesfuly set reverse proxy. From outside i got router certificte on meshcentral web page. I can login, but Token (2FA) is not letting me in. When i enter token, i was forwarded back to login.

**Comment by alesribic73** [comment]
Can MeshCentral run only on plain text port 80? HTTPS disabled?
Because all HTTPS traffic is handeled by reverse proxy
