### ISSUE TITLE
Guest Names in Event Lists

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#2960]
Following up to add a bit more to a previous request (#2812) - now that we're properly seeing connected guests while they're live, can guest names (displayed in the same way) be added to event lists as well? Right now, I have a computer that I gave someone long-term guest access to and it shows that I'm connecting to it when they do which is a bit confusing when looking through logs.

Granted, I'm not sure if this will be as simple to implement as I'm guessing that guest users don't have a user ID so the logged ID is that of the issuing user but if it is possible, I'd love to see it.

**Comment by Ylianst** [comment]
Good request. Let me see what I can do.

**Comment by Ylianst** [comment]
This was a good idea. Just added it. Will be in MeshCentral v0.8.89.

![image](https://user-images.githubusercontent.com/1319013/127551564-f8f83532-bd1c-47c5-905e-c9c262761b48.png)

**Comment by PetieM** [comment]
Seems to be working just fine - thanks!
