### ISSUE TITLE
Meshcentral Assistant not working properly

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2961]
The always connected meshcentral assistant gets hanged and not getting the remote display properly.

**Comment by Ylianst** [comment]
Good request, but I need to be able to replicate the problem. This report does not allow me to do that.

**Comment by pggsadmin** [comment]
@Ylianst
This issue is not an invalid request refer task #2826 & #2879

As per your suggesion they have submitted the session recordings refer task #2879.

Apart from this if you require any logs / server access that we can provide.

Since this is an un imaginable platform i  like to resolve this issues at earliest..

I hope you consider this as a valid request.

**Comment by pggsadmin** [comment]
@Ylianst

I have removed assistant and started installation of meshagents.
