### ISSUE TITLE
Reset 2FA for a user

### ISSUE THREAD

**Issue by rossmarkflo** [Ylianst/MeshCentral#2963]
Can not reset 2FA for a user - user is stuck and can not login - is there a way to do this without re-creating the account?

**Comment by Ylianst** [comment]
Go to that user in the "My Users" tab and hit "Change Password". Keep the passwords blank and check the option "Remove all 2nd factor authentication". That should do it. You can also reset the password at the same time if you like.

![image](https://user-images.githubusercontent.com/1319013/127551981-702d0844-a16d-4613-81ab-a8365662e241.png)

**Comment by rossmarkflo** [comment]
That works with a user that uses a authenticator application. This specific one started the email-tokens but for some reason they come super delayed. So we wanted to set this back and use the authenticator app. In This case - I do not see the checkbox for RESET 2FA. Only with the users that use the authenticator application.

**Comment by Ylianst** [comment]
Oh! That is not good. Working on that now.

**Comment by Ylianst** [comment]
I see the same problem, fixing it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.8.89 with a fix for this. Let me know if it works.

**Comment by rossmarkflo** [comment]
That was fast - thanks! Works fine. Will divide the other suggestions in issues as well now.
