### ISSUE TITLE
Removing the file transfer feature

### ISSUE THREAD

**Issue by gesandovalr** [Ylianst/MeshCentral#2966]
Could be possible to have a feature to disable the file transfer on the Agent? unfortunately there are some customers who have Security Policies in place and don't allow the users to use file transfers using their BYOD.

Thank you.

**Comment by Ylianst** [comment]
Do you need it removed for just some users or removed for the entire server?

**Comment by gesandovalr** [comment]
It's for certain groups.

**Comment by Ylianst** [comment]
When adding a user or user group to a device group, you can select the "No File Access" permission. This will remove the "Files" tab.

![image](https://user-images.githubusercontent.com/1319013/127683644-2941cf52-5360-4819-91a3-b7086f23a946.png)

Let me know if that works.

**Comment by gesandovalr** [comment]
Thanks for your help.
