### ISSUE TITLE
all of my devices are no more listed

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#2967]
hi , from version 0.8.89 but also with 0.8.90 devices are no more listed, so i cannot remote control anymore please see image:
![immagine](https://user-images.githubusercontent.com/62424179/127612678-17a02094-77ba-4de9-baf9-220c88d47cef.png)
the only way to use the software is to go my account , then click on device group needed and then at the bottom select the pc
please let me know.

**Comment by Ylianst** [comment]
Can you open the developer console in your browser, refresh the page and report any error you see? I will fix this right away. Thanks.

![image](https://user-images.githubusercontent.com/1319013/127618271-4dd0bc56-dbaa-432d-942f-71050457f34b.png)

**Comment by tradexsrl** [comment]
ok done , i see these error:









Da:     "Ylian Saint-Hilaire" ***@***.***>
Per:    "Ylianst/MeshCentral" ***@***.***>
Cc:     "Marco Zaro" ***@***.***>, "Author" 
***@***.***>
Data:   30/07/2021 09:38
Oggetto:        [Marketing Mail] Re: [Ylianst/MeshCentral] all of my 
devices are no more listed (#2967)



Can you open the developer console in your browser, refresh the page and 
report any error you see? I will fix this right away. Thanks.

?

**Comment by Ylianst** [comment]
Not seeing your errors, can you post on GitHub? Thanks.

**Comment by tradexsrl** [comment]
![immagine](https://user-images.githubusercontent.com/62424179/127624575-ba43d625-96c8-4cca-a65f-ea24dc91db42.png)

**Comment by tradexsrl** [comment]
![immagine](https://user-images.githubusercontent.com/62424179/127624622-634b814f-c0fa-4843-8d53-bec4d0c44693.png)

**Comment by Ylianst** [comment]
Ok, working on it. Will have a new version in a few minutes!

**Comment by Allowee** [comment]
Had the same issue, but after a server move, both at version 0.8.90
I was able to solve this by clearing the cache..

**Comment by Ylianst** [comment]
Publishing v0.8.91 now with a correct fix for this. Will be available in a few minutes.

**Comment by Ylianst** [comment]
A workaround is to click the settings icon and ok.

![image](https://user-images.githubusercontent.com/1319013/127631321-fc717dbf-bfd9-4e7a-be07-54ebf6577b5e.png)

But v0.8.91 should fix it.

**Comment by tradexsrl** [comment]
ok with v0.8.91 is solved , many thank's
