### ISSUE TITLE
MeshCentral and Remote Desktop Small

### ISSUE THREAD

**Issue by TJKraft** [Ylianst/MeshCentral#297]

**Comment by TJKraft** [comment]
In the Remote Desktop feature of MeshCentral, why is the screen view so small?  Can this be adjusted?

**Comment by Ylianst** [comment]
Hi. There is a small button on the upper right of the remote desktop screen that can toggle the viewer between different view modes. Take a look at that, you can also put the viewer in full screen, but also try holding "Shift" while clicking on the full screen button. Let me know if that works for you.

![MC2-RemoteDesktopSize](https://user-images.githubusercontent.com/1319013/59290442-71130680-8c2d-11e9-8bc0-a0f66cd989b0.png)

**Comment by Ylianst** [comment]
I will close this one since I think it answers the question, but feel free to re-open if it does not. Thanks.
