### ISSUE TITLE
Translator tool link is dead

### ISSUE THREAD

**Issue by OvrAp3x** [Ylianst/MeshCentral#2970]
The link for the translator tool found here is dead,
https://github.com/Ylianst/MeshCentral/tree/master/translate

http://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip

**Comment by nzalev** [comment]
The link is not dead, but it is HTTP. The server will serve a 301 redirect to https.

This is likely being blocked for being mixed content, ie, trying to get HTTP from an HTTPS connection.

If you open the link in an incognito window, or you copy+paste it into a new window, it should download.

**Comment by Ylianst** [comment]
@nzalev Thank you so much! Your fix was accepted (of course!).

@OvrAp3x Please check and close this issue if it's fixed - Thanks.

**Comment by OvrAp3x** [comment]
Thank you🙂
