### ISSUE TITLE
Add "Last seen" data in export option

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2972]
@Ylianst
Can you include device last seen details in export menu ?

**Comment by Ylianst** [comment]
Good idea!

**Comment by Ylianst** [comment]
Ok, working on this one now.

**Comment by Ylianst** [comment]
Added last connection time and last connection address to device export. Will be in MeshCentral v0.8.92.

**Comment by pggsadmin** [comment]
Thanks @Ylianst
