### ISSUE TITLE
Auto remove device after few inactive days

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2974]
@Ylianst

Can you implement an option to remove all devices if they are not connected from last few days.

The days can be configurable on config.js like 10/30 days based on server config

**Comment by Ylianst** [comment]
This is a super good idea. I have wanted to add that for a long time.

**Comment by VINISHVV** [comment]
There is an option in Device group for remove device on disconnect.

but still this is a good feature that helps many people.

**Comment by Ylianst** [comment]
Started work on this...

![image](https://user-images.githubusercontent.com/1319013/127750093-4c408f6a-a9a1-486d-99a1-fc6b2e79cf72.png)

**Comment by VINISHVV** [comment]
@Ylianst
Latest version of meshcentral showing the auto inactive device remove options in device group. I have completed the config by selecting 10 days inactive durations but still more than 30 days devices are available in my dashbord.

Also the console command i have tried but its not functional.

Can you help how we activate this functionality?

**Comment by Ylianst** [comment]
One of the problems with this new feature is that all the existing devices before the update will not have the last connection time set correctly, so they will never be removed. After the update, if a device connects and disconnects and then you wait 10 days, it will be removed.

One idea would be for me to set all existing devices to have last connected 30 days ago unless the "last connect" is set correctly. I will take a look at options.

**Comment by VINISHVV** [comment]
@Ylianst
I have setup the auto removal period 2 days. Now almost 5days completed but still the devices not removed.

**Comment by pggsadmin** [comment]
> @Ylianst
> I have setup the auto removal period 2 days. Now almost 5days completed but still the devices not removed.



I am also facing such issues. I think this feature is not completed yet

**Comment by VINISHVV** [comment]
@Ylianst 
I have tested the same in the new server, Still auto removal not happening.

**Comment by pggsadmin** [comment]
This issue was resolved through #3089.
