### ISSUE TITLE
Feature Request: "Reset CIRA connection" function

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#2976]
Hi,

I have experienced several situations, where a device connected via CIRA became unavailable regarding AMT or did no longer respond to either work or disconnecting/connecting in the AMT tab or HW console in Desktop tab.

One of the occasions frequently provoking such situations is when upgrading ME firmware to a new version.

Observing this issue, I noticed that the CIRA connection to the MPS port was still active. Restarting meshcentral resolved this problem, but instead using iptables to firewall force-drop the TCP connection using `-j REJECT --reject-with tcp-reset` caused AMT to re-establish the connection, too, bringing back AMT/CIRA availability to MeshCentral.

Maybe MeshCentral could simply detect when an active CIRA connection becomes dead by "pinging" AMT from time to time, and drop dead connections automatically.

But for people in a hurry who do not want to wait for this to happen, I suggest adding a "Reset CIRA connection" function to the General tab of devices that have an active CIRA connection, and drop this when triggered.
Maybe also a "Reset all CIRA connections" function for the server tab could be reasonable for some cases, too.

If there is outstanding work queued in the AMT manager for either the single device resp. any device connected to the server, a warning requiring confirmation should be displayed.

Best regards,
// Veit

**Comment by jsastriawan** [comment]
It is a great idea. The implementation is as simple as closing CIRA socket connection.

**Comment by Ylianst** [comment]
To get started with this, I added a "dropallcira" command in the server console. Will be in MeshCentral v0.8.91. There is also a ping over CIRA and MeshCentral should disconnect on timeout... so not sure what is going on there.

![image](https://user-images.githubusercontent.com/1319013/127722340-2f30cb8a-bb27-4886-9c2d-f1b4c1043e82.png)

**Comment by veitw** [comment]
@Ylianst: Nice, thanks!

**Comment by si458** [comment]
command implemented `dropallcira`
sadly the really isnt a way to do it PER DEVICE, because the `agent actions` button is disabled when the machine is off,
so you have to run this command from the My Server Console Tab instead
