### ISSUE TITLE
Disable local input.

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#2980]
Is there any provision to lock keybord and mouse during remote session.

**Comment by VINISHVV** [comment]
@pggsadmin
Hope this will available soon.
Reference #2550

**Comment by VINISHVV** [comment]
@pggsadmin 
This feature is available in the latest meshcentral version v0.8.98.

**Comment by pggsadmin** [comment]
Wow, that's great News !!.

Upgraded to the latest version and seems it's working fine.
