### ISSUE TITLE
Feature Request: meshctrl RunCommand Result returned

### ISSUE THREAD

**Issue by 1ARdotNO** [Ylianst/MeshCentral#2982]
It would be very useful to get the results from running a command with RunCommand in meshctrl.js to return the results back to the "sender" in addition or instead of to the console only.

Ie. in cases where you want to automate some task chain, and perform a second action based on the result on the first one.
or simply for "ease of use"

Could be be set behind a command line switch like, --ReturnResponse or similar

**Comment by AntonAndreevichMoroz** [comment]
that's a good idea.  I would also like to have such a function

**Comment by si458** [comment]
RELATED/DUPLICATE #5203
