### ISSUE TITLE
user consent not showing for ubuntu machine

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#2983]
user consent not showing for ubuntu machine but its showing properly for windows OS

**Comment by krayon007** [comment]
Can you provide more details? What version of Ubuntu? Are any users logged into Ubuntu when you are trying to connect to it? What desktop manager are you using for you Ubuntu?

**Comment by aimdharma1990** [comment]
> desktop manager

Ubuntu 16, Yes user is logged in, Gnome is the desktop

**Comment by krayon007** [comment]
What server version are you running? I just tested on my Ubuntu 18.04 LTS machine, using the last two versions of the agent, and they both appeared to have user consent functioning correctly.

**Comment by aimdharma1990** [comment]
I am using latest MeshCentral Version. Its giving directly reject message
also not giving notification also. Is there anyway i can enable debugger in
the target ubuntu machine for debugging.?

Also in ubuntu 18.04 machine getting blank screen with this error

xauthority is not found! Is your DM configured to use -X

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
