### ISSUE TITLE
Terminal/Files with password ?

### ISSUE THREAD

**Issue by Gheppy** [Ylianst/MeshCentral#2984]
Is it possible to ask the user and password in the Terminal and Files before connecting?
As in the desktop connection version,where you must enter the account password.
Or simply disable them from the agent, and leave only the desktop 

Thank you

**Comment by ryanblenis** [comment]
Are the device permissions (for users and / or groups) somehow not fulfilling the need to disable terminal and / or file tab access?

**Comment by krayon007** [comment]
Also, which OS is this for? For Linux, macOS, and FreeBSD, if you right click on the terminal connect button, and select login shell, it will prompt/require credentials for one of the local users. (The server can be configured to only allow this type of connection, etc)

**Comment by Ylianst** [comment]
Note that there is a permission to remove the terminal. So, you can grant users remote access to a device but remove the terminal tab completely if you like.

![image](https://user-images.githubusercontent.com/1319013/128099097-5227b863-c4da-4be8-ad43-b5d09a007905.png)

**Comment by Gheppy** [comment]
@krayon007  > The server can be configured to only allow this type of connection <
How can I do that? Where I can read about it ?

@Ylianst , 
I saw this, but I want the same type of restrictions on the entire server for all computers (added by me as Admin and for those added by the user).
A kind of server-level restrictions, in which I can:
- to limit (eliminate) the terminal and / or files
- for linux (windows) where there is only a terminal to ask for username and password before connecting
- limitation with user and password to be for files as well
I want these settings to be mandatory for all users and admins.
For me, it's another level of security 


Thank you

**Comment by Gheppy** [comment]
I see that there is no answer, 
I have attached a photo to exemplify what I would like to be implemented (the marked ones ).

![image](https://user-images.githubusercontent.com/84496256/128376232-6c2f6218-e22a-4a98-8dc3-b1717b81b45c.png)

It is possible ?

Thank you

**Comment by Gheppy** [comment]
I have made the necessary changes ( that I need ) only to limit full access to the Terminal and Files, for all devices, regardless of group , of specific user.
The limit is on user part.

![image](https://user-images.githubusercontent.com/84496256/128492683-8213f01b-0acd-4b24-ba06-3acb5edc3cab.png)


I changed some files as follows:


```
**meshuser.js**

alter line 69
++    const SITERIGHT_NOTERMINAL          = 0x00001000; // 4096
++    const SITERIGHT_NOFILES             = 0x00002000; // 8192


**webserver.js**
after line 123
++   const SITERIGHT_NOTERMINAL          = 0x00001000; // 4096
++   const SITERIGHT_NOFILES             = 0x00002000; // 8192


**views/default.handlebars**

alter line 5493
++   var terminalAccessSite = ((userinfo.siteadmin == 0xFFFFFFFF) || ((userinfo.siteadmin & 4096) == 0));
++   var fileAccessSite = ((userinfo.siteadmin == 0xFFFFFFFF) || ((userinfo.siteadmin & 8192) == 0));							   

line 5496
--   QV('cxterminal', ((node.mtype == 1) || (node.agent == null) || (node.agent.caps == null) || ((node.agent.caps & 2) != 0) || (node.intelamt && (node.intelamt.state == 2))) && (rights & 8) && terminalAccess);
--   QV('cxfiles', ((node.mtype == 2) && ((node.agent == null) || (node.agent.caps == null) || ((node.agent.caps & 4) != 0))) && (rights & 8) && fileAccess);
++   QV('cxterminal', ((node.mtype == 1) || (node.agent == null) || (node.agent.caps == null) || ((node.agent.caps & 2) != 0) || (node.intelamt && (node.intelamt.state == 2))) && (rights & 8) && terminalAccess && terminalAccessSite);
++   QV('cxfiles', ((node.mtype == 2) && ((node.agent == null) || (node.agent.caps == null) || ((node.agent.caps & 4) != 0))) && (rights & 8) && fileAccess && fileAccessSite);


line 6753
--   if (terminalAccess) { setupTerminal(); }
--   if (fileAccess) { setupFiles(); }
++   if (terminalAccess && terminalAccessSite) { setupTerminal(); }
++   if (fileAccess && fileAccessSite) { setupFiles(); }

line 6765
--   QV('MainDevTerminal', (((node.agent == null) && (node.intelamt != null)) || (node.agent.caps == null) || ((node.agent.caps & 2) != 0) || (node.intelamt && (node.intelamt.state == 2))) && (meshrights & 8) && terminalAccess);
--   QV('MainDevFiles', (node.agent != null) && (node.agent.caps != null) && ((node.agent.caps & 4) != 0) && (meshrights & 8) && fileAccess);
++   QV('MainDevTerminal', (((node.agent == null) && (node.intelamt != null)) || (node.agent.caps == null) || ((node.agent.caps & 2) != 0) || (node.intelamt && (node.intelamt.state == 2))) && (meshrights & 8) && terminalAccess && terminalAccessSite);
++   QV('MainDevFiles', (node.agent != null) && (node.agent.caps != null) && ((node.agent.caps & 4) != 0) && (meshrights & 8) && fileAccess && fileAccessSite);

alter line 6925
++   if (siteRights & 4096) str1.push("No Terminal");
++   if (siteRights & 8192) str1.push("No Files");

line 12936
--   if ((user.siteadmin != null) && (user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & (64 + 128 + 1024)) != 0)) { permissions += '*'; }
++   if ((user.siteadmin != null) && (user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & (64 + 128 + 1024 + 4096 + 8192)) != 0)) { permissions += '*'; }

alter line 13355
++   x += '<label><input type=checkbox onchange=showUserAdminDialogValidate() id=ua_nomeshterminal>' + "No Terminal" + '</label><br>';
++   x += '<label><input type=checkbox onchange=showUserAdminDialogValidate() id=ua_nomeshfiles>' + "No Files" + '</label><br>';

alter line 13367
++   Q('ua_nomeshterminal').checked = ((user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & 4096) != 0));  // No Terminal
++   Q('ua_nomeshfiles').checked = ((user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & 8192) != 0));     // No Files

alter line 13420
++   QE('ua_nomeshterminal', !uself && (userinfo.siteadmin & 2) && (user.siteadmin != 0xFFFFFFFF) && (userinfo._id != user._id));
++   QE('ua_nomeshfiles', !uself && (userinfo.siteadmin & 2) && (user.siteadmin != 0xFFFFFFFF) && (userinfo._id != user._id));

alter line 13438
++   QE('ua_nomeshterminal', !Q('ua_fulladmin').checked);
++   QE('ua_nomeshfiles', !Q('ua_fulladmin').checked);
            
line 13939
--   if ((user.siteadmin != null) && (user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & (64 + 128 + 1024)) != 0)) { msg.push("Restrictions"); }
++   if ((user.siteadmin != null) && (user.siteadmin != 0xFFFFFFFF) && ((user.siteadmin & (64 + 128 + 1024 + 4096 + 8192)) != 0)) { msg.push("Restrictions"); }
```


I hope I can also do the part where the user and password are required by default (Terminal and Files)
**_And I hope that this change will be accepted and implemented in the project_**

**Comment by dinger1986** [comment]
Did you complete this?

**Comment by si458** [comment]
this has already been implemented now,
you can disallow access for users to things like terminal/files
and you can even disallow access for groups for certain users to things like terminal/files
![Screenshot 2023-11-16 at 22-12-48 MyRemoteAgent](https://github.com/Ylianst/MeshCentral/assets/765314/36af3420-7efe-44bb-a9c6-3df3494dc767)
![Screenshot 2023-11-16 at 22-11-33 MyRemoteAgent](https://github.com/Ylianst/MeshCentral/assets/765314/eaeeb9f4-c0e6-4477-b590-c203ca1656b2)
