### ISSUE TITLE
Mesh Central Router skip files already copied

### ISSUE THREAD

**Issue by drews11** [Ylianst/MeshCentral#2988]
I would like to have the ability to skip the downloaded files already and only copy what is missing if the connection drops out and has to start again.

![image](https://user-images.githubusercontent.com/88491026/128344800-96d0d71c-764d-4442-9f4b-389b7285c828.png)

**Comment by Ylianst** [comment]
Good request.

**Comment by Ylianst** [comment]
Half way there, I got it working for downloads... need to add it for uploads.

![image](https://user-images.githubusercontent.com/1319013/128389364-e419b4df-8f1e-416d-8e84-eeb0cee5c5f9.png)

**Comment by Ylianst** [comment]
I have an new [MeshCentral Router available here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe) that includes the new file skipping feature. Let me know if that works. This new MeshCentral Router will be included in MeshCentral v0.8.98.

**Comment by drews11** [comment]
Perfect! works a dream
