### ISSUE TITLE
Server wont start after upgrade to 0.8.96

### ISSUE THREAD

**Issue by bmttek** [Ylianst/MeshCentral#2989]
meshcentral/webserver.js:5919
                        const certPath = common.joinPath(obj.parent.datapath, domain.authstrategies.saml.cert);
                                                   ^

```
ReferenceError: common is not defined
    at serverStart (/home/srvadmin/node_modules/meshcentral/webserver.js:5919:42)
    at /home/srvadmin/node_modules/meshcentral/webserver.js:290:17
    at /home/srvadmin/node_modules/meshcentral/db.js:1548:107
    at newArguments.<computed> (/home/srvadmin/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/home/srvadmin/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/home/srvadmin/node_modules/nedb/lib/cursor.js:126:19)
    at /home/srvadmin/node_modules/nedb/lib/cursor.js:193:12
    at /home/srvadmin/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/home/srvadmin/node_modules/async/lib/async.js:130:20)
    at /home/srvadmin/node_modules/nedb/lib/datastore.js:323:11
```

**Comment by zanderson-aim** [comment]
Seeing the same problem as well, maybe this patch broke it? https://github.com/Ylianst/MeshCentral/commit/63b52fa1f61033330adcdfc4797456f3fca3b34e#diff-3bc3d64af608412ba09ac2d4e77293f9f427777f4c25c7643659ea104774519f

Going to try rolling back to 0.8.92

**Comment by bmttek** [comment]
I modified webserver.js link 5919 "common.joinPath" to "obj.common.joinPath" and that allowed the server to start

**Comment by Ylianst** [comment]
Working on this NOW!!!

**Comment by Ylianst** [comment]
Releasing new version in a few minutes...

**Comment by Ylianst** [comment]
MeshCentral v0.8.97 has been published with a fix for this. Please let me know if that works.

**Comment by bmttek** [comment]
Tested and works.
