### ISSUE TITLE
Let users Manage device Notes

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#299]
Hi Ylianst,
It would be great enabling users to manage notes, same way like tags. Every device Notes window can contain useful information about machine itself, for example a specific configuration or setup, sharing this info to all users
At the moment, only administrators can write notes, users can not save anything, only view.

Thanks

Merlinweb

**Comment by Ylianst** [comment]
Agreed, I need to look into this. If you have an opinion as to what Device Group permission should be used to view/edit notes, let me know.

**Comment by Ylianst** [comment]
After looking into this. Everyone that can view the device group can see the nodes and there is a separate permission for editing notes. So, you should be able to grant this permission to your users and be ok. This is not an administrator thing. Let me know if this is ok.

![MC2-EditNotes](https://user-images.githubusercontent.com/1319013/59294580-a2dc9b00-8c36-11e9-82f1-c4aa271088e1.png)

**Comment by merlinweb** [comment]
Sorry, Ylianst, but I can not confirm it's working properly
My account is Administrator, everything works, but other users with "partial Rights", like below:
![image](https://user-images.githubusercontent.com/48550288/59327411-bac12700-8ce9-11e9-9d34-99adf27a0786.png)
they can't edit notes,neither see the group device "notes" button:
![image](https://user-images.githubusercontent.com/48550288/59327487-f825b480-8ce9-11e9-8001-223dbb034195.png)

I suspect this could be an Admin behaviour:
![image](https://user-images.githubusercontent.com/48550288/59327698-9d408d00-8cea-11e9-84be-5d4517323145.png)

Hope this helps

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Ok, I will check this tomorrow... indeed the message is old and not correct and the button should show up.

**Comment by Ylianst** [comment]
I just noticed above that you are looking at device group notes. Notes can be placed on users, device groups and devices. I will take a look at device group notes.

**Comment by merlinweb** [comment]
I'm checking Both.
In my case, partial right users can't see device GROUP notes button
But they also can't write into device notes form, editing is not accepted clicking OK button

**Comment by Ylianst** [comment]
Ok, will check that tomorrow.

**Comment by merlinweb** [comment]
It's not a problem, guess midnight is gone in your local time
in my town is already tomorrow... :))

**Comment by Ylianst** [comment]
Correct, just past midnight here on the US pacific coast. Perfect time to post on GitHub.

**Comment by Ylianst** [comment]
Ok. I finally did some changes for this. The devices notes need to "Set Notes" permission, however for device group notes you need to be administrator of the device group. I think this seems reasonable since I don't expect users to edit the device group notes. This said, if you really want the device group notes to be user editable, let me know.

**Comment by merlinweb** [comment]
Thanks Ylian,

I agree, I can let only admin to edit group notes, not a problem
But issue is not solved, a non-admin can't write
I am testin a user with this permissions:
![image](https://user-images.githubusercontent.com/48550288/60646745-63bbf700-9e3c-11e9-8e2b-a5525b685037.png)
Thes are the steps:
write into yellow notes form of a group computer
![image](https://user-images.githubusercontent.com/48550288/60646937-d2995000-9e3c-11e9-940e-c21d1607ea54.png)
click OK
re-entering in notes bu form is empty...
![image](https://user-images.githubusercontent.com/48550288/60646968-e2189900-9e3c-11e9-9dfd-561bf0dd93ca.png)

Am I doing something wrong ?

Thanks

Merlinweb

**Comment by Ylianst** [comment]
Oh, this is not good. I will look into this. Should be easy to fix.

**Comment by merlinweb** [comment]
Hi Ylianst
just a remind, when you have time to fix it
thanks


Merlinweb

**Comment by b8two** [comment]
Hi,
Regarding Notes, is it possible to display them on the General Tab between the description and the Server Icon? Hence Allowing them to be Viewed (not edited) without needing to click another button.

**Comment by dinger1986** [comment]
@si458 shall we test this and close if working?

**Comment by si458** [comment]
this seems to work as expected now?

admin can read/write notes,
user with a group, has view permission but cant edit
another user with same group, has read/write permission
