### ISSUE TITLE
Create a Zip File from Mesh Router

### ISSUE THREAD

**Issue by drews11** [Ylianst/MeshCentral#2991]
I am having trouble creating a zip file using the browser, i think there is too many files for it too handle.

Is it possible to create a zip file from mesh router,

Also a search option would be amazing,
for example i want to download all filenames containing "DT01" in the name somewhere

**Comment by Ylianst** [comment]
Right now you can't ask the MeshAgent to create a zip file remotely using MeshCentral Router, but this is a good request.

**Comment by Ylianst** [comment]
Published MeshCentral v0.9.1 with updated MeshCentral Router that can now create zip files.

![MC2-RouterZipSupport](https://user-images.githubusercontent.com/1319013/129103912-323a2c9e-9b72-4b6a-8ac5-5d483d5a3bce.png)

Let me know if this works.

**Comment by drews11** [comment]
do you have an exe of the router i can get?

**Comment by drews11** [comment]
Hi Ylianst,
Do you have an exe for the router only that i can get? i don't know what version is the latest on the website.

**Comment by pggsadmin** [comment]
> Hi Ylianst,
> Do you have an exe for the router only that i can get? i don't know what version is the latest on the website.

If you are using latest version then check the  folder node_modules/meshcentral/agent

location once or download directy from the url [Here](https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe)
