### ISSUE TITLE
MeshCentral v0.8.98 has all new MeshAgents

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#2993]
I want to mention that MeshCentral v0.8.98 has all new MeshAgents for Windows, Linux, BSD, macOS. Updating to this version will automatically update all agents. The new agents have improved stability, a lot of bug fixes and new correctly implement WebSocket masking. So far, I have tested the self-update system 100's of times and ran thru a lot of testing.

Let me know if you see any issues. This has been a huge amount of work over many months. Many thanks for Bryan (@krayon007) for all his hard work.

MeshCentral Assistant and MeshCentral Agent for Android are not affected.

![MC2-NewAgents](https://user-images.githubusercontent.com/1319013/128468733-980f7d2e-44d4-4314-b3e4-98ffddb18da2.png)

**Comment by VINISHVV** [comment]
@Ylianst & @krayon007 

Many thanks to both of you for such an unimaginable open-source application.

Upgraded my server to the latest versions and it's working properly without any issues.
The only problem I noticed for a few agents is that the "Desktop / Terminal" does not show after the update ( There is an issue opened related to this #2994 ). But I have updated the same in bulk using Force agent update.

Now all of my agents ( 9000+ ) showing compile-time like - Aug 5 2021. Also, it's working well.

Also, I loved the latest feature "Local input disable" that I am waiting for for the last few months.

**Comment by Ylianst** [comment]
Ha yes, the new agent is capable of locking local user input.

![MC2-LocalInputLock](https://user-images.githubusercontent.com/1319013/128529380-7c7e0aa3-5640-4e84-ad68-2ac184648677.png)

For agents the are missing the desktop/terminal/files tab. I will investigate this, but maybe an easy fix is to reset the server once. You can use the "resetserver" command in the "My Server" / " Console" tab.

![image](https://user-images.githubusercontent.com/1319013/128529672-b186ea7a-e83e-4ecc-b97f-d711b14ae662.png)

This will cause all the agents to disconnect and reconnect and have the server push the missing meshcore to the agents. If you see a device in this situation and can try this, let me know if it works.

**Comment by plwc** [comment]
Yay!

I have one user in particular who just can't stop clicking on things even while I'm on the phone to them and specifically ask them multiple times not to touch the keyboard.

Very minor but I view the terms "remote" and "local" from the perspective of the terminals location rather than my location. You even call it "local user input" yourself above but in the meshcentral interface it is referred to as "remote input" when you hover over the icon and on the window the pops up when you click on it.

**Comment by smartekIT** [comment]
Thank you so much for this update, I even noticed the load on the server CPU is less. not sue if related to the new agent update but it's a bonus for me.
one thing was hoping to have, is the ability to have the agent interactive window with options like minimize, or even close to system tray icon!
for the current agent, the only way to move it off screen while working on remote pc is to click show desktop function in windows.

Thanks

**Comment by smartekIT** [comment]
![agentMinimize](https://user-images.githubusercontent.com/70715469/128827247-23825895-21f3-4213-8f0e-e60219b2e94d.PNG)

**Comment by Ylianst** [comment]
For an interactive agent, you may want to take a look at MeshCentral Assistant. I have a [YouTube video here](https://www.youtube.com/watch?v=HytCpYLxrvk).

**Comment by smartekIT** [comment]
Thanks, i already watched that before. in my case I dedicated one of the groups for Quick Support, where all the agents on that group are downloaded, run in instant connect modem with no installation then once they disconnect they get deleted automatically from that group. similar to TeamViewer QuickSupport agent. everything works perfect except it doesn't have a minimize button at least !!

**Comment by si458** [comment]
closing as old
