### ISSUE TITLE
Agent update failure After auto updating server to 0.8.98

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#2994]
Agents are missing a few menu items, I'm manually uploading the server core to them in order to get it back
![chrome_5ImnK9yFpL](https://user-images.githubusercontent.com/4949495/128514002-b6e10502-3c59-4d3e-8bc4-c800130d142b.png)

**Comment by VINISHVV** [comment]
@rodrigolzd - Normally new agent update will take few hours however.

just wait for few hours / manually update the agents in bulk by disabling auto agent update.

To disable; auto-update modify the **config.js** like below and restart the server.

  "_noagentupdate": true,

Once server starts select all such agents and click on **Group actions** -> **Force agent update**

**Comment by Ylianst** [comment]
Depending on how many agents are attacked to your server and must be updated, this can be normal for a while. If you have a lot of agents the need to be updated, you can to see how the server is doing by typing "tasklimiter" in the "My Server" / "Console" tab.

![image](https://user-images.githubusercontent.com/1319013/128530242-c3d5e01c-d55e-49f8-974d-137c594ed851.png)

You will see the last line "Pending" with 3 numbers. Type that command again and agent (up arrow and enter) to see the numbers drop as the server works to update all the agent. Once back to "0, 0, 0" all the agents should be updated.

After that, if you see agents with missing "desktop / terminal / files" tabs, you can fix it manually for that device by clicking on a device, going to the "console" tab and selecting "Upload default server core". You can also use this menu to "Clear server core" and upload it back again.

![image](https://user-images.githubusercontent.com/1319013/128530623-37d3b400-43fe-4e32-bae4-65dd9f95fe66.png)

A quick shortcut is to hold ALT and hit the "Agent Action" button to clear the core and hold SHIFT and hit "Agent Action" to upload a fresh core. You should see the missing tabs show up after a few seconds. The MeshAgent runs JavaScript code, so doing this updates the code the agent runs, it's like changing it's "brain".

Finally, if the task limiter shows the server is done updating all devices. You could just reset the server using the "resetserver" command in "My Server" / "Console" tab. This will cause all agents to disconnect and reconnect and should automatically update any missing cores.

![image](https://user-images.githubusercontent.com/1319013/128531273-af840952-67b4-441a-aa17-01df9ee64f49.png)

Let me know if this works. I will investigate this a bit more, any information is appreciated.

**Comment by rodrigolzd** [comment]
Hi,

I've done those steps, clearing the core and uploading a new server core. even tried a few other options. but not all computers were updated correctly. 


Also, I have added the "_noagentupdate": true, option, but I dont see the difference on my group actions. 
![image](https://user-images.githubusercontent.com/4949495/128534288-109cef03-2a2f-434c-b3b5-01c9931d33f2.png)

Perhaps a copy of my config.json file would help? I have removed sensitve information.

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "mesh.server.com",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "Password",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "_noagentupdate": true
  },
  "domains": {
    "": {
      "SiteStyle": 2,
      "title": "MeshCentral",
      "title2": "server",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "ManageAllDeviceGroups": [ "user1","user2" ]
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "email@server.com",
    "names": "mesh.server.com",
    "production": true
  },
  "_smtp": {
	 "_host": "server.com",
	 "_port": 465,
	 "_from": "email@server.com",
	 "_user": "email@server.com",
	 "_pass": "PASSWORD",
	 "_tls": false
}
}

**Comment by Ylianst** [comment]
Change this line:

```
"_noagentupdate": true
```

to

```
"noagentupdate": 1
```

Restart the server, you should see this in the group actions:

![image](https://user-images.githubusercontent.com/1319013/128544215-c88b3eff-f82c-497d-b97b-4a599b4ef7b8.png)

**Comment by rodrigolzd** [comment]
I'm a bit puzzled by what i'm seeing now. I did change the line to "noagentupdate": 1 and most the computers had their desktop options back, but when looking at the compile time it said march 25. 

Should I go back to automatic updates now? Also, is there a way to check all computers at once? I only have about 100 computers, but if I had a thousand would be a terrible task. I guess the solution is already there and I just dont know it.

**Comment by Ylianst** [comment]
I don't know the details of your setup, but in some way, agents have been setup to not allow self-update, then there is nothing more to do. You can try going to the device's "console" tab and type "agentupdate" and report back what happens. Best to type "versions" then "agentupdate" then "versions" and send a screenshot back.

By any chance, are the agents that are not updating all "interactive" agents? That is, agent that users manually click the "Connect" button to have them connect?

Its possible to continue running with the older agents and MeshCentral should work. If you turn on auto-update, MeshCentral will start by clearing the core and initiate the update. So, this is why you don't see the desktop/terminal/files tab as MeshCentral is trying to update the agent and not being successful.

There is a "Select All" button on the top you can click to select all devices.

**Comment by rodrigolzd** [comment]
I can test whatever you need here. My setup is pretty simple. The server is hosted online at Lunanode on a ubuntu 18.04 with a subdomain. 99% of the agents are desktops, windows 7 and 10, connecting only via installed agents, meaning no RDP and not manually connecting the client agent.

![image](https://user-images.githubusercontent.com/4949495/128557691-ce38ce2e-7527-4947-8048-d9e22cc02926.png)

Also, I meant if there was a way to see all the agent versions connected to the server. A column in the device list view with this info would be easier than going into the device details

it would be nice to see a "update complete"  on a agent update via console. The last output is Updating and restartting agent, but doesn't say its done. 

I dont believe my agents were setup not to update. where else could  that be setup. I have posted the entire contents of my config.json above.

**Comment by VINISHVV** [comment]
@rodrigolzd - 

Please export the device list in CSV format by selecting  **"include device details"**.
In the csv file you can **see agentCommitDate** filter the same and select all devices those commit date is older than current month.

Please select all those devices and force update the agent.

**Comment by frankmcc** [comment]
> "noagentupdate": 1

Should this be set back to 0 after you have applied the Forced Update?  Which begs the question, why not allow the Forced update option as well as the automatic update?

**Comment by Ylianst** [comment]
In theory, if automatic update is enabled (the default), you should not need to worry about manual update of the agents. Really the goal is have the server take care of this in the background so, the best is to fix any agent self-update issues instead of providing more options and menus for manual agent update.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.0 with new agent type and version columns.

![MC2-AgentTypeVersion](https://user-images.githubusercontent.com/1319013/128805754-451aeb87-8134-439d-bff0-ef8306777809.png)

**Comment by billymoox** [comment]
Hi,
I have the same problem after updated to version 0.8.99. On the server I got the error message "Agent in big trouble ..." see attached screen shot.
![mesh](https://user-images.githubusercontent.com/40301062/128924845-1ccf5443-9d3a-4d20-afe9-ef2cfa2b0200.jpg)

**Comment by rodrigolzd** [comment]
billymoox, looks like your screen shot is showing your server public address and ip. You might want to avoid that.

**Comment by billymoox** [comment]
Oops, I'll need to refresh and get a new IP from ISP.Thanks for pointing it out.On 10 Aug 2021 21:25, Rodrigo Lozada ***@***.***> wrote:
billymoox, looks like your screen shot is showing your server public address and ip. You might want to avoid that.

**Comment by robclay** [comment]
I was also having problems seeing DESKTOP after upgrading from 7.something to 8.99.  And like @rodrigolzd , I added the 

`noupdate: 1 `to the config file

Restarted the server and the computers had their desktop options back.

When looking at the Agent Version it shows as Mar 25 2021 2750472259.

I am now using Force agent update on the older ones.

I am still unsure what happens next?  Can I remove

`noupdate: 1 `

so the agents will start behaving again?  Or do I need to manually update the agents going forward?

**Comment by Ylianst** [comment]
If you happen to be using NodeJS v16, the self update system was broken. It's now fixed with MeshCentral v0.9.7.

**Comment by robclay** [comment]
So @Ylianst , it is now safe to remove "noupdate: 1"  from the config file assuming I want automatic updates?

**Comment by rapi3** [comment]
I have a very old computer with Linux Mint v14 x32 bit that after latest server upgrade 0.9.15 with newer agents it is unable to run the agent any more it failed to upgrade and after a manual agent reinstall from server, log it is full of agent crash.
I am looking for a link to download previous server with older agent to be able to manual replace the latest agent with old one.
Thank you.

**Comment by krayon007** [comment]
What server version were you upgrading from?

**Comment by rapi3** [comment]
I found how to download version 0.8.9.7 with working agent for linux 32 bit, I will install tomorrow.
From now one my server will stay with noagentupdate=true
