### ISSUE TITLE
Agent Remote Desktop Quality

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#300]
When using the remote agent to connect, the maximum quality can only be set to 60%.
Expected: Should be able to set up to 100%

P.S I would like to add this software is great

**Comment by Ylianst** [comment]
Hi. There is an option for this already, in the settings section of config.json, add this:

```
{
  "settings": {
    "AllowHighQualityDesktop": true
  }
}
```

That should allow you to select much higher quality settings. Of course, the server will relay more traffic.

**Comment by vish84** [comment]
Thanks for the rapid feedback. I can confirm that added the extra settings I was after.

**Comment by FilGov** [comment]
What about meshcentral.com?

**Comment by FilGov** [comment]
Anyone?

**Comment by FilGov** [comment]
Can anyone help?

**Comment by vish84** [comment]
I would suggest opening a new issue asking the question, someone else may be able to help

**Comment by MailYouLater** [comment]
As increasing the quality to 100% requires a lot more data to be transferred to & from the server, and 60% is usually high enough, and considering that @Ylianst runs the MeshCentral.com instance from his personal funds, I find it unlikely that he'll enable higher quality remote desktop through it.
