### ISSUE TITLE
file transfer between two peers behind 4G mobile router ?

### ISSUE THREAD

**Issue by ihubgit** [Ylianst/MeshCentral#3001]
Hi, just discovered MeshCentral and would like to know whether it can be used to transfer files between two endpoints who both are behind a different 4G mobile router. Problem is, only the mobile service provider knows the private IPs from the peers, so normally that's always a problem for p2p connections.
Can MeshCentral deal with this situation ? If i install the server on one PC and a client on another (not inside the LAN), will they be able to discover one another ?

**Comment by rapi3** [comment]
You need to have the server to a public internet IP / DNS not on 4G.
Clients can be on 4G, they will establish connection with the server and after that you can do what you want via MC.

**Comment by ihubgit** [comment]
and what if i put the server on ADSL with fix IP but behind proxy ?

**Comment by OutbackMatt** [comment]
I think that you would need to use the server in the middle

Download from Device A to server then upload to Device B from Server
