### ISSUE TITLE
Copy  Paste Files

### ISSUE THREAD

**Issue by s-monzon** [Ylianst/MeshCentral#3002]
Unable to copy and paste entire files (.txt, .exe. pdf. docx ...) when performing remote service
It was attempted from the clipboard or downloading the local clipboard to remote

**Comment by PathfinderNetworks** [comment]
The clipboard upload/download function is for text only.  If you want to transfer files you have to use the Files tab.  Or you can also use the MeshCentral Router for a better file transfer experience.  Open the MeshCentral router and right-click on the device you want to transfer files with. Then choose Remote Files.  A more functional file transfer utility will then load allowing you to move files between the remote device and your local drives.

**Comment by Ylianst** [comment]
Not sure I can do a file copy using the clipboard like this. I am sure Microsoft uses some tricks to do it over RDP. They must copy a shortcut into the clipboard and when you paste on the remote site, they would need to copy the file and move it to the right location.

We could explore this in the future, but it's probably a lot of work.
