### ISSUE TITLE
New Mesh agent crashes with three screens and 90% quality

### ISSUE THREAD

**Issue by adsgreen** [Ylianst/MeshCentral#3004]
On a PC with 3 x 1200x1920 displays the new mesh agent will crash and restart if a desktop terminal session is requested at 90% quality.
90% quality on other pc's with fewer screens or using 80% on the pc with three screens connects just fine.

Agent version:
```
> versions
{
  "openssl": "1.1.1k",
  "duktape": "v2.6.0",
  "commitDate": "2021-08-05T20:47:56.000Z",
  "commitHash": "9dfc4757e46cab6b7ce142dc66b93e64320d81a6",
  "compileTime": "14:22:26, Aug  5 2021"
}
```
PC Is Windows 10 Pro - 2009 [19042] 64bit

Not critical as acceptable workaround to use lower quality.

**Comment by Ylianst** [comment]
I wonder if this is related to #3041, as the agent seems to have problems sending large data blocks.

**Comment by Ylianst** [comment]
MeshCentral v0.9.16 was pushing with all new MeshAgents for all OS's that should fix this. Let us know if it works.

**Comment by adsgreen** [comment]
Sorry - yes retested and confirmed resolved.
