### ISSUE TITLE
Add Agent version to Device View Columns 

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3010]
Please consider adding the agent version to Device View Columns and make it sortable by it. 

It would help to identify outdated agents and possible connection problems.

**Comment by Ylianst** [comment]
Ok, added two more columns. Will be in MeshCentral v0.9.0

![image](https://user-images.githubusercontent.com/1319013/128787765-f494bbfc-9e47-4bd8-ace5-a6e943bb0916.png)

**Comment by rodrigolzd** [comment]
Works for me. Thanks. This can be closed
