### ISSUE TITLE
Add Force Agent Update to Perform Agent Action menu

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3011]
Regardless of the setting  "noagentupdate":  on config.json, I think the option to force the agent update or reinstall on demand should always available.

![2021-08-09](https://user-images.githubusercontent.com/4949495/128766935-8e1f3ed9-6a6c-4a64-a519-c58f14f9b1f7.png)

**Comment by Ylianst** [comment]
Well, this would be the same as typing "agentupdate" in the agent console tab. I can add it if you like, but it would quite literally just send "agentupdate" to the agent.

**Comment by rodrigolzd** [comment]
I honestly did not know if it was exactly the same as the agentupdate command. Also I was not sure the command would always work because of the setting noagentupdate. 

This raises another question. Are all the actions on the menu also also the same as some console command?

**Comment by Ylianst** [comment]
Regardless of the value in "noagentupdate" on the server, you can always type "agentupdate" in the agent console like this:

![image](https://user-images.githubusercontent.com/1319013/128775107-3a5c6716-bd6e-4458-bb3e-b59786802ddb.png)

It also helps to run "versions" before and after to see this difference.

The options in the agent console "Actions" menu are all thing the server needs to do. There is no agent command to do the same thing.

If you do set:

```
"NoAgentUpdate": 1,
```

In the "settings" section of the config.json, you can select many devices and in the group action, select to force update all selected agents. In that case, this is the same as typing "agentupdate" but on all selected agents.

![image](https://user-images.githubusercontent.com/1319013/128775550-2faec32b-fb96-4292-89d2-d61b67242c29.png)

Ideally the hope is that you just don't have to worry about this and everything is fully automatic.

**Comment by rodrigolzd** [comment]
I noticed a nice difference in the agent console, I can see info and date of the agent on the top right hand side of the window.  This is helpful, fewer steps to check the versions. At least I think it was not there before. 

![image](https://user-images.githubusercontent.com/4949495/129022741-aaee8510-3434-4d7b-bd27-a4620f435986.png)

So, I think we can keep the agentupdate function just as a command, but I dont see any harm in having it as a button either.
