### ISSUE TITLE
Question: Can the Device Tags window show existing tags?

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3013]
I just want to avoid creating a tag, forgetting about it and then creating something similar to it again. It might cause confusion. 

I'm used to the WordPress tags. I would like to see something like that as well, pretty simple to use.

![image](https://user-images.githubusercontent.com/4949495/128785086-5b47a70e-bac6-4d08-9318-7117d1c4bcf0.png)

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
This will be in MeshCentral v0.9.0. Let me know if that works.

![MC2-ImprovedDeviceTagging](https://user-images.githubusercontent.com/1319013/128804471-4028bac8-c9c0-4704-a1f6-796205ab381c.png)

**Comment by rodrigolzd** [comment]
This is working! it will help alot. Thank you!

As I suspected, I had some very similar tags already, Some like "Server" and "server"
