### ISSUE TITLE
My Server Tracing

### ISSUE THREAD

**Issue by itpilot** [Ylianst/MeshCentral#3015]
guys please can you help me

i have installed **Meshcentral v0.8.98** on **Ubuntu 20.4**

using **Mongodb**

everything works however when i go to " **My Server > Trace** " and i Choose **Tracing >  Core Server Options** eg: **Main Server Messages, MashAgent traffic, MashAgent update** 

**There are NO Tracing Details being shown**

any ideas what i did wrong and what i must do?

any help greatly appreciated

**Comment by Ylianst** [comment]
Once you have these tracing turned on:

![image](https://user-images.githubusercontent.com/1319013/128822626-d2502a02-3de8-489f-8bb7-35f2b8adbc9c.png)

Open a different browser tab, go to a device console tab and type "agentupdate".

![image](https://user-images.githubusercontent.com/1319013/128822714-3ea28aae-2d62-4929-8401-0c8a834b9db2.png)

In addition, click "Agent Action" and select "Soft disconnect agent"

![image](https://user-images.githubusercontent.com/1319013/128822763-74b33767-e193-44c5-80fb-f1b3ece84acf.png)

You should see things show up in the trace. Note that tracing is used by developers, not something typically used by MeshCentral administrators. Hope that helps.

**Comment by itpilot** [comment]
**Ylianst** thank you very much for your help

**it All Works!!**

now i understand

Thank you for a Brilliant Product!!
