### ISSUE TITLE
Profile image in user consent

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3017]
@Ylianst

Like meshcentral assistant is it possible to display the remote user profile image in meshagent?.

**Comment by Ylianst** [comment]
This has been requested before. MeshCentral Assistant does have the provide image in the user consent prompt. Would be great to have it in the MeshAgent too.

**Comment by Mfinadmin** [comment]
@pggsadmin 
seems feature available in latest version of meshcentral.
#2395 2395

**Comment by pggsadmin** [comment]
> @pggsadmin seems feature available in latest version of meshcentral. #2395 2395

Wow Great News....
Thanks @Ylianst , @krayon007 for your support.
