### ISSUE TITLE
Meshcentral Assistant Hangs

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3018]
@Ylianst

This is related to #2961
Can you fix the meshcentral assistant hang issues?

If you need any debug logs/ any access that i can arrange.

**Comment by Ylianst** [comment]
I can't reproduce this issue on the developer machine. If you have steps to make this issue happen, that would be great.

**Comment by pggsadmin** [comment]
Sure,
I come back with few findings.

**Comment by Ylianst** [comment]
Thanks. That would be great. If I can make the issue happen on my development computer, that is 50% of the solution.

**Comment by pggsadmin** [comment]
@Ylianst
Do you get this error in your environment?

**Comment by Ylianst** [comment]
I am going to start working on this tonight. This is going to be my priority this next week, I really want to get MeshCentral Assistant reliable.

**Comment by pggsadmin** [comment]
@Ylianst
I think you are not able to replicate this issue
Pls let me know then we can share more details.

**Comment by VINISHVV** [comment]
@Ylianst 
I just checked the meshcentral public server. Seems same issue.
I think you can easily re-create the issue.

**Comment by pggsadmin** [comment]
@Ylianst
Any hope in this case?

**Comment by Ylianst** [comment]
Hopefully I just fixed this in MeshCentral v0.9.45. #3212
