### ISSUE TITLE
Plugin Issue with Ubuntu

### ISSUE THREAD

**Issue by itpilot** [Ylianst/MeshCentral#3019]
guys please can you help me

i have installed **Meshcentral v0.8.98** on **Ubuntu 20.4**

using **Mongodb**

everything works and i have " **Downloaded the Following Plugins** "

1. **File Distribution**
2. **RoutePlus**
3. **ScriptTask**
my problem is that it shows that the Plugin **Status = Disabled**

when i **Action** the " **Install** " Option on Any of the Plugins i get "**Notice: Plugin have been altered, this may require agent core update** "

**I then get Logged Out of the Meshcentral System**

when i log back in and go to the Plugin i see that the **Plugin is NOT Installed**

**any ideas what i need to do to " Install " the Plugins ??**

any help greatly appreciated

**Comment by Ylianst** [comment]
To enable MeshCentral plugins, you need to add the "plugins" section in the settings section of the the config.json 

```
{
  "settings": {
    "plugins": {
     "enabled": true
    }
  }
}
```

Let me know if you have this? If it still does not work, post your config.json with XXXXX for any confidential information. Note that I don't test MeshCentral with plugins, so once you install plugin's your more on your own for support.

**Comment by itpilot** [comment]
Ylianst thank you for your reply

apologies i have forgotten to say that i **Have** " **Enabled** " the Plugin Option in the **config.jason**  file ie:

 **"plugins": { "enabled": true },**

when i **Action** the " **Install** " Option on Any of the Plugins i get "**Notice: Plugin have been altered, this may require agent core update** "

**I then get Logged Out of the Meshcentral System**

when i log back in and go to the Plugin i see that the Plugin is **NOT Installed**

**any ideas what i need to do to " Install " the Plugins ??**

**i think that this is a rights issue on my Ubuntu 20.04 VULTR Cloud Server**

so it is on my side, something i did or did not do ??

any help greatly appreciated

**Comment by itpilot** [comment]
Any update on the issue?

**Comment by VINISHVV** [comment]
@itpilot -

Please enable internet access in your server and do the below steps once.

Goto Meshcentral data/Plugins and remove all the plugins folders permanently.
Goto server -> Console -> and enter "resetserver" to restart the meshcentral.
Login mesh central and remove all plugins.
Reinstall the required plugins and click on refresh agent.

**Comment by ryanblenis** [comment]
Please note that there has been an issue with plugins since 0.9.7, I've submitted a patch to correct this #3143 . Subsequent to approval, I'll be pushing new plugin versions as well.
