### ISSUE TITLE
MeshCentral in Production Environment

### ISSUE THREAD

**Issue by johnczer** [Ylianst/MeshCentral#302]
Are there any videos or tutorials on how to set up MeshCentral in Production environment? I’ve been working on this and am having an issue where I cannot connect to remote computers reliably. I am running this on a Windows 2012R2 VM over HTTPS and I’ve even taken the firewall out of the mix just to eliminate this as being the problem. When I am on the same network and access the portal I have this issue but if I remote into a computer off site and access the portal I can click on a remote device’s drives and remote and it works as expected, connecting to everything fast and reliably. I thought maybe there were some instructions on the steps to set this up, in case I was missing something in my setup. Thanks for all of your help Ylian!

**Comment by MailYouLater** [comment]
Do you not have a U-Turn NAT set up on your router? At a guess, you're running the server in WAN mode, not hybrid (LAN+WAN) mode, so your LAN clients are trying to connect via the internet, and your router's not properly set up to direct the outbound traffic that's meant to go somewhere local where it's supposed to go.

**Comment by johnczer** [comment]
Thanks for responding! So to be in Hybrid mode using npm install method do I just un-comment out both _WANonly=true and LANonly=true in thre config.json? This may help to get me on the right track.

**Comment by johnczer** [comment]
I figured this out, thanks again for pointing me in the right direction.

**Comment by MailYouLater** [comment]
@johnczer: Out of curiosity, what did you do to fix your issue?  If others have this issue in the future, they may find themselves here, and since I'm hoping to set up a hybrid install of meshcentral in the future, I'd like to know what I'll need to do to make it work properly.

**Comment by johnczer** [comment]
Sorry, I didn’t put the solution up because I just thought it was ignorance on my part:) I just used the cert: “mysupport.domain.com” and commented out the wanonly and lanonly sections in config. I am behind a Sophos UTM Firewall as well, so that adds other variables to the mix. I am happy to share those if requested but I know that this is not a Sophos forum. Thanks again for pointing me in the right direction!

**Comment by MailYouLater** [comment]
Great, thank you.  I appreciate the info.

**Comment by NFBrewingTech** [comment]
> Sorry, I didn’t put the solution up because I just thought it was ignorance on my part:) I just used the cert: “mysupport.domain.com” and commented out the wanonly and lanonly sections in config. I am behind a Sophos UTM Firewall as well, so that adds other variables to the mix with regards to the actual certificate. I am happy to share those if requested but I know that this is not a Sophos forum. Thanks again for pointing me in the right direction!

Would you mind sharing the Sophos specific parts?  Setting up behind a Sophos UTM and having some issues (Unable to connect to websocket)  Sure I am missing something stupid

**Comment by johnczer** [comment]
Not a problem, I will get you some screenshots. It’s just like publishing any web server over port 443 (or desired) and using HTTPS redirect. The few important things that come to mind is to first have Sophos UTM updated to the latest version as this adds the ability to select Websockets for the virtual server’s site path and also, you’ll want to either use the new Letsencrypt functionality built into Sophos or the cert generated in MeshCentral but not both. This is what caused issues for me. If you use the Sophos cert which I found to be easier you can just download that and extract the cert, privkey, etc., using OpenSSL and then copy those to your Letsencrypt folder in MeshCentral.
