### ISSUE TITLE
Question: Can MeshCentral connect directly to powershell instead of the windows terminal?

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3021]
Had to use powershell a bit more than usual the past few days. I keep going to the terminal and running powershell directly. I wonder if it can connecto directly to it. Considering some windows servers that dont even have a GUI it might be a good idea to have it as a new separate tab option. I dont think it should replace the terminal connection, but it would be a nice option/addition.

**Comment by Ylianst** [comment]
Yes. Right click the connect button in the terminal and select PowerShell. Let me know if this works.

![image](https://user-images.githubusercontent.com/1319013/129047078-d77b7be7-a670-4372-ae81-0c8f051e7b7b.png)
