### ISSUE TITLE
Web-RDP not working on version 9.0

### ISSUE THREAD

**Issue by Scaff31** [Ylianst/MeshCentral#3022]
```
-------- 8/11/2021, 4:17:08 PM ---- 0.9.0 --------

{"name":"node-rdpjs","hostname":"meshcentral","pid":1068056,"level":40,"msg":"NODE_RDP_PROTOCOL_X224_NEG_FAILURE(Failure code:5 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx))\nError: Failure code:5 (see https://msdn.microsoft.com/en-us/library/cc240507.aspx)\n    at new ProtocolError (/node_modules/node-rdpjs-2/lib/core/error.js:40:8)\n    at Client.recvConnectionConfirm (/node_modules/node-rdpjs-2/lib/protocol/x224.js:221:9)\n    at TPKT.<anonymous> (/node_modules/node-rdpjs-2/lib/protocol/x224.js:202:8)\n    at Object.onceWrapper (events.js:286:20)\n    at TPKT.emit (events.js:198:13)\n    at TPKT.recvData (/node_modules/node-rdpjs-2/lib/protocol/tpkt.js:110:7)\n    at BufferLayer.<anonymous> (/node_modules/node-rdpjs-2/lib/protocol/tpkt.js:101:8)\n    at Object.onceWrapper (events.js:286:20)\n    at BufferLayer.emit (events.js:198:13)\n    at BufferLayer.recv (/node_modules/node-rdpjs-2/lib/core/layer.js:91:8)","time":"2021-08-11T14:17:08.249Z","v":0}

```

```
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: invalid base value in method 'onTunnelClosed()'
```

Error when i try to connect with Web-rdp

**Comment by Ylianst** [comment]
The problem with Web-RDP is that is does not support "Network Level Authentication" (NLA). So, you have to disable this option on the remote computer to use it. This is certainly a problem, I use [node-rdpjs](https://github.com/citronneur/node-rdpjs) which does not support NLA. It is on their todo list but no progress was made in years and I imagine I would need to add support for this at some point.

![image](https://user-images.githubusercontent.com/1319013/129047656-2c02a4fd-1182-45ed-ba01-ce87f8604c8f.png)

**Comment by Scaff31** [comment]
Thank you @Ylianst for the answer I have deactivated the NLA but the problem persists. Black screen for 10/15sec then back to the web-rdp connection page

I also still have the error in the agent console

`uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: invalid base value in method 'onTunnelClosed()'`

**Comment by Ylianst** [comment]
I just tested Web-RDP on a "Local devices" group. If NLA is enabled, I do get the "NODE_RDP_PROTOCOL_X224_NEG_FAILURE" error just like you have.

If I change the hostname to an invalid IP address, I try to connect Web-RDP and get a black screen for a long time.

Are you using a agent group or local device group?

**Comment by Scaff31** [comment]
I use Agent Group

**Comment by Ylianst** [comment]
Thanks for reporting back. Much appreciated.
