### ISSUE TITLE
manage push authentication error

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#3024]
Hi, I encountered another problem with "manage push authentication", when I request authentication on the web page I get the code to share and on the device 000000
![Screenshot_20210812-074533](https://user-images.githubusercontent.com/58943816/129145961-7469ed0e-74bb-40bf-9d40-b44fb507d7c5.png)

part of the trace

8:03:54 AM - WEB: handleRootRequestLogin()
8:03:54 AM - WEB: getHardwareKeyChallenge: fail
8:03:54 AM - WEB: handleRootRequestEx: sending 2FA challenge.
8:03:54 AM - WEB: handleLoginRequest: 2FA token required
8:03:54 AM - WEB: checkUserOneTimePassword: fail (2).
8:03:54 AM - WEB: checkUserOneTimePassword()
8:03:54 AM - WEB: handleRootPostRequest, action: login

**Comment by paolor1965** [comment]
I apologize I did another test by connecting to the university wifi network and it works. Maybe it could be down to the weak 4g network used earlier

**Comment by Ylianst** [comment]
Weird. I just tried it myself and it worked. I did make a change so that if the app does not work, it will display default "------" instead of "000000" so you know something is wrong.

![image](https://user-images.githubusercontent.com/1319013/129247847-a50539d8-0452-4279-9ac0-709ebb8ae22d.png)
