### ISSUE TITLE
Feature: do not alias ls when already set

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3026]
I tried to change my alias for the ls command in .bashrc and it didn't work.
This seems caused by Mesh setting this alias for me, after my .bashrc file is processed.
Would it be possible to first check if there is already an 'ls' alias?

https://github.com/Ylianst/MeshCentral/blob/189941bd44f69f1df7aa2b65c31ea16d5d14f1a1/agents/meshcore.js#L1967

**Comment by PetieM** [comment]
Is this why my alias hasn't been working? I never even thought to check! I just got into the habit of running "su" as soon as I connected to the terminal which brought me back into my normal profile when using the root account but just skipping the MeshCentral alias would definitely be easier.

**Comment by Ylianst** [comment]
Oh. That is a really good request.

**Comment by PetieM** [comment]
If you have an easy way to detect an alias already existing on the target system and only removing your alias then, I'd think that would be better but I'm not sure how feasible that is.

**Comment by Ylianst** [comment]
We launch the shell and run:

```
alias ls=\'ls --color=auto\';clear\n
```

So, we can change that to anything we want.

**Comment by Ylianst** [comment]
Yes! Your are on the right track. Another option is that I have a new domain-wide configuration for this. So you can configure to run nothing or whatever you like when a terminal starts.

**Comment by nzalev** [comment]
It is not useful trying to grep a particular file for an alias, because many shells exist and each have their own config. There are also other possible files such as `.profile`.

However, running `alias` on its own will print the current list of aliases. Example:
<pre>voltaire$ alias
l=ls
ll=&apos;ls -la&apos;
local=typeset
login=&apos;exec login&apos;
nohup=&apos;nohup &apos;
r=&apos;fc -s&apos;
stop=&apos;kill -STOP&apos;
</pre>

You must also check from the start of the line to avoid accidentally matching something like "alias shells=...". The following works:
```bash
alias | grep -E '^alias ls='
```

**Comment by PetieM** [comment]
Oh, nice! I didn't realize alias on its own listed current aliases. Thanks for the inadvertent new knowledge!

**Comment by Allowee** [comment]
I can even check the alias ls itself, not sure if this is the same on all systems
making it customizable would be even beter :) 

> xx@xx:/usr/local/mesh 20210813-08:39:44]# alias ls
> alias ls='ls --color=auto'
> xx@xx:/usr/local/mesh 20210813-08:39:46]# alias lx
> bash: alias: lx: not found

**Comment by Ylianst** [comment]
Ok, I will make this customizable. I think it's a good idea.

**Comment by Ylianst** [comment]
Just check in a new feature to allow configuration of the startup commands for Linux, macOS and FreeBSD. This will be in MeshCentral v0.9.8.

![MC2-TermStartCommands](https://user-images.githubusercontent.com/1319013/130145495-aea6b58e-2208-42f0-b808-ec039c0f8146.png)

**Comment by PetieM** [comment]
This appears to be working correctly with one issue - if you try to override the default behavior with nothing (e.g. `"linux": "",`), it fails to connect and crashes the agent (presumably - it still shows as online but after restarting the server, it was disconnected until I restarted the agent service and I don't see anything in the agent log). I've worked around this by setting the custom command to "clear\n" for the time being but I imagine this behavior isn't intended.

**Comment by Ylianst** [comment]
@PetieM Oh dear! Working on a fix for that right away!!! Thanks for reporting that.

**Comment by Ylianst** [comment]
Just pushed a fix for this. However, Bryan needs to look at to why writing an empty string causes an agent crash.

**Comment by Ylianst** [comment]
MeshCentral v0.9.10 is published with a fix for this. Let me know if it works.

**Comment by PetieM** [comment]
That seems to have done the trick. I actually wound up needing to utilize this feature (specifically to set $HOME as the mesh user does not have that variable set and it throws an error when editing in VIM) but I tested with a blank command and restarted the server a couple of times - terminal connects, there is no error, and the agent no longer crashes.

**Comment by Allowee** [comment]
Thank you @Ylianst 
Tested this and is working fine once the config is set :)
