### ISSUE TITLE
AMT issues - 0.9.1

### ISSUE THREAD

**Issue by mfroeh103** [Ylianst/MeshCentral#3027]
We have two issues with AMT. I'm not sure when this issue started as we weren't using AMT very much. But yesterday while we were testing after upgrading to 0.9.1, we ran into an issue where none of our AMT devices allow an AMT connection. 

We have 4 devices that have AMT configured. They are all showing activated in the "General" tab. 
![image](https://user-images.githubusercontent.com/53836896/129219018-b0bbe92e-c1fa-42ec-bd2f-d4f375614197.png)
But the HW Connect and Connect buttons in the "Desktop" and "Terminal" tab are greyed out. 
![image](https://user-images.githubusercontent.com/53836896/129219121-8f6cb10e-c9c9-4afe-86e0-b7b175442772.png)

This is what the amtevents look like. This is after running the amtconfig command(see below where it kicks us out of the server). 
![image](https://user-images.githubusercontent.com/53836896/129218484-99eff075-620f-4105-b93f-15ed6565ec92.png)

I found another issue when I went to the "Console" tab to run the amtconfig command. When I run the amtconfig command, I get disconnected from the server. We have tried this on multiple devices and two different users. 
![image](https://user-images.githubusercontent.com/53836896/129219674-7bba554d-2560-4edb-9000-39bae8d765d7.png)

**Comment by Ylianst** [comment]
The "amtconfig" causing the server to crash is high priority for me. Can you go in "meshcentral-data" and send back the last few errors in "mesherrors.txt" that relate to this crash? Please XXXX any confidential data. I will fix this ASAP.

**Comment by Ylianst** [comment]
I just tested "amtconfig" and don't see the issue. Your error report will get me on the right track.

![image](https://user-images.githubusercontent.com/1319013/129250798-570201ff-0c44-4f20-8c4a-1d88f8ecc88e.png)

**Comment by mfroeh103** [comment]
Here is what is in the error log. Let me know of anything else you need from me. 



/home/useraccount/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

 

TypeError: socket.end is not a function
    at /home/useraccount/node_modules/meshcentral/mpsserver.js:744:36
    at handleCallback (/home/useraccount/node_modules/mongodb/lib/utils.js:120:56)
    at /home/useraccount/node_modules/mongodb/lib/cursor.js:861:16
    at handleCallback (/home/useraccount/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/home/useraccount/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /home/useraccount/node_modules/mongodb-core/lib/cursor.js:599:16
    at queryCallback (/home/useraccount/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /home/useraccount/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by Ylianst** [comment]
I just put in a fix for the server exception. That will be in MeshCentral v0.9.3.

**Comment by mfroeh103** [comment]
Thanks! Updated the server and confirmed that the issue is resolved.

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back and closing the issue. Must appreciated.
