### ISSUE TITLE
MeshAgent router and MFA

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#3029]
Although I normally operate within the Linux environment, I've recently been using the Windows router (v1.7.7811) and noticed that, even if my MC2 account is configured with MFA, I can log into the router with just my basic credentials and not prompted for the MFA.

**Comment by Ylianst** [comment]
It's probably because you opted to "remember this device" for 30 days. In that case, the router will store a cookie in the registry and will present the cookie to the server which will service as 2FA for 30 days. If you don't think this is the case, I can check this again.

**Comment by VINISHVV** [comment]
@D4V3M0NK - i tested the same but its working for me.


Many authentication method available for web login, but only email / google authentication options works in meshcentral router. I think its due to the technology used in router and webpage both are different.

**Comment by Ylianst** [comment]
The MeshCentral Router does not support FIDO keys and Push Notifications, but should support: Backup Codes, Authentication App, SMS and EMail 2FA. With some work, I could support push notification 2FA.

Regardless of 2FA used, the MeshCentral Router should not be able to skip 2FA unless it has a 30 day 2FA skip token that it can present to the server.

**Comment by D4V3M0NK** [comment]
Could I grab the registry entry to check to see if I hit the 30 day storage option?

**Comment by Ylianst** [comment]
Look in `Computer\HKEY_CURRENT_USER\SOFTWARE\Open Source\MeshCentral Router`

![image](https://user-images.githubusercontent.com/1319013/129489430-980ff083-b882-423f-9598-7abce6c2ee37.png)

You should see a "TwoFactorCookie". Delete it and run MeshCentral Router again.

**Comment by D4V3M0NK** [comment]
Yup, there it is ... deleted it and worked as advertised. Apologies for the run around, I don't normally set those cookies which is why it threw me! Thanks for the follow up!

**Comment by Ylianst** [comment]
Nice. Thanks for testing that and reporting back. Much appreciated.
