### ISSUE TITLE
Can't uninstall with npm uninstall

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#303]
I noticed that if I run `npm uninstall meshcentral` it doesn't say `removed # package(s) and audited # package(s) in #.###s` like it does when I uninstall anything else I've installed with npm, so I compared the files before and after, and the only difference running `npm uninstall meshcentral` makes is that it adds one line from the `package-lock.json` file, which says `"dev": true,`.

What's going on here? Isn't npm's `uninstall` command supposed to "uninstall" the package?
When I noticed this, I had been thinking that uninstalling it would remove the package and its data, and then I could install again and it would be a fresh install, and while I'm not familiar enough with using node and npm to know if removing data during `uninstall` is normal or not, but generally `uninstall` should remove the package, not just add a "dev" flag to a configuration file.

Specifically the location and content of the data added to `package-lock.json` during `uninstall` is:

    {
      "dependencies" : {
        "meshcentral" : {
          "dev": true
        }
      }
    }

**Comment by Ylianst** [comment]
Will take a look at this next time I can.

**Comment by Ylianst** [comment]
Can you what OS and OS version you are using to do the "npm uninstall"? - Thanks.

**Comment by MailYouLater** [comment]
Windows 10 home version 1803 build 17134.829 with portable version of Node version 10.15.3 and NPM version 6.4.1 using installer found [here](https://github.com/jgonyea/nodejs-portable/releases/tag/10.15.3).
