### ISSUE TITLE
No Desktop or terminal after update to 0.9.3

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#3030]
Windows 10 PCs lost Desktop, Terminal, Files options after update from 0.8.85 to 0.9.3.
Don't know how to diagnose it further.
It looks that MeshAgents must be updated manually - but since i can't do that locally, i think reverting back to older version of MeshCentral would work better for me now. 
So i think this is the problem - MeshAgent isn't updated.

**Comment by Ylianst** [comment]
Take a look at #3025 and let me know if that works.

**Comment by nicrame** [comment]
Still didn't worked for me.
Console:
Agent Action - Upload default core - didn't help
Agent Action - Upload recovery core
then use "Agent Update" or "agentupdate" command didn't work.
![Zrzut ekranu (324)](https://user-images.githubusercontent.com/5872054/129457899-a82bc810-5cf3-4109-865b-ef42df66bfcb.png)

**Comment by rodrigolzd** [comment]
Use the Agent action button on the right to do a soft disconnect then clear the core and then upload default core. 

See if that helps.

**Comment by nicrame** [comment]
That didn't help too. Like the agent wouldn't even respond.

**Comment by Ylianst** [comment]
Confirm that "Agent Action - Upload recovery core" does not work?

**Comment by nicrame** [comment]
There is no response on 0.9.3 for Agent Action - clear and upload recovery after. 
I've got this problem on Win10 64bit, and WinServer (2012 and 2019) both 64bit.
Here is short video how it looks: https://love.itos.pl/s/Yg9fAisttRpEHkf
I'll try 0.9.4 in a moment.

**Comment by OutbackMatt** [comment]
I've just upgraded to 0.9.4

I can't pick 'which' desktop session I take over now. Important for terminal servers, and desktops offering RDP

**Comment by Ylianst** [comment]
@nicrame Is the agent you are running the 32bit or 64bit agent?

![image](https://user-images.githubusercontent.com/1319013/129489018-54b9d5ca-9481-4e49-a461-b532989967ac.png)

**Comment by Ylianst** [comment]
@OutbackMatt It does not look like the problem your reporting is related to this issue. If it's not, can you open a new issue. I will test RDP sessions.

**Comment by Ylianst** [comment]
@nicrame Another possibility is that your MeshCentral server has corrupted files. You could stop your server, rename "node_modules" to "node_modules_bak" and run `npm install meshcentral` to create fresh new "node_modules" folder. You can then start the server again and see if that fixes it.

It would be bad if your trying to push corrupt files to the agents.

**Comment by nicrame** [comment]
> Bryan and I are working on this and can't replicate the issue. We need sufficient information to be able to make this problem occur on our test machines.
> 
> @nicrame Is the agent you are running the 32bit or 64bit agent?
It is always 64bit agent (i do not have any 32bit OS left).
![Zrzut ekranu (327)](https://user-images.githubusercontent.com/5872054/129489489-816639da-5119-488a-9566-e8ae6fee5ee2.png)
![Zrzut ekranu (326)](https://user-images.githubusercontent.com/5872054/129489492-51f7e5a9-1685-4473-b8fc-21d8d406b241.png)
![Zrzut ekranu (325)](https://user-images.githubusercontent.com/5872054/129489502-ca85fac7-bafe-47f7-b8ce-a1921b975702.png)

> Also, if you can try the TinyCore.
Agent Action -> Clear the core -> Agent Action -> Upload tiny core and nothing happens. Like it wouldn;t accept anything from here.

> Lastly, is it possible that the remote computer has no disk space left or the disk is read-only?
No, it is like 20 computers, with different specs and HDDs/SSDs (one got more than 3TB free disk space).

What is interesting that Linux PCs are working fine (RedHat, RockyLinux, CentOS and Ubuntu).

**Comment by nicrame** [comment]
> 
> 
> @nicrame Another possibility is that your MeshCentral server has corrupted files. You could stop your server, rename "node_modules" to "node_modules_bak" and run `npm install meshcentral` to create fresh new "node_modules" folder. You can then start the server again and see if that fixes it.
> 
> It would be bad if your trying to push corrupt files to the agents.

Ok i will give it a try and report here.

**Comment by Ylianst** [comment]
Ok, your running 64bit Windows Agents... this is the agent I use the most. Your agent is just refusing the meshcores completely. I have not seen this before.

We push a different MeshCore to Windows and Linux machines, so, not entirely surprising you would see a difference.

**Comment by nicrame** [comment]
> 
> 
> Ok, your running 64bit Windows Agents... this is the agent I use the most. Your agents are just refusing the meshcores completely. I have not seen this before.
> 
> We push a different MeshCore to Windows and Linux machines, so, not entirely surprising you would see a difference.

So i removed node_modules, then installed meshcentral and started it.
I've also installed one Windows 10 32bit to check it too. And Windows 10 Home, with 32bit agent is working fine. There are all options, and console is working fine (help or versions command are working).

But 64bit is still the same - console do not reply on commands, and there are no desktop, terminal, files options.

Maybe this is something with my config? I'm running it on CentOS 7 x64.
`{
  "settings": {
    "cert": "mesh.itos.pl",
    "Port": 881,
    "IgnoreAgentHashCheck": true,
    "RedirPort": 0,
    "MpsPort": 4433,
    "AllowLoginToken": false,
    "AllowFraming": false,
    "WebRTC": false,
    "ClickOnce": true
  },
  "domains": {
    "": {
      "title": "XXX",
      "title2": "xxx.xx.xx",
      "userQuota": 1048576,
      "meshQuota": 248576,
      "newAccounts": 0,
   }
  },
  "_letsencrypt": {
    "email": "xxx@xx.xx",
    "names": "xxx.xxx.xxl",
    "rsaKeySize": 3072,
    "production": false
  },
  "smtp": {
    "host": "xxx.xx",
    "port": 25,
    "from": "xxx@xxx.xx",
    "user": "xxx@xxx.xx",
    "pass": "xxx",
    "tls": false
  }
}
`

**Comment by rossmarkflo** [comment]
After reading all of this and testing around - ended up installing the latest agent manually on those clients and they come back now.. still rolling out.. might wanna try that.. download it from your Mesh Central and install it / update it.

**Comment by pggsadmin** [comment]
> > Ok, your running 64bit Windows Agents... this is the agent I use the most. Your agents are just refusing the meshcores completely. I have not seen this before.
> > We push a different MeshCore to Windows and Linux machines, so, not entirely surprising you would see a difference.
> 
> So i removed node_modules, then installed meshcentral and started it.
> I've also installed one Windows 10 32bit to check it too. And Windows 10 Home, with 32bit agent is working fine. There are all options, and console is working fine (help or versions command are working).
> 
> But 64bit is still the same - console do not reply on commands, and there are no desktop, terminal, files options.
> 
> Maybe this is something with my config? I'm running it on CentOS 7 x64.
> {
> "settings": {
> "cert": "mesh.itos.pl",
> "Port": 881,
> "IgnoreAgentHashCheck": true,
> "RedirPort": 0,
> "MpsPort": 4433,
> "AllowLoginToken": false,
> "AllowFraming": false,
> "WebRTC": false,
> "ClickOnce": true
> },
> "domains": {
> "": {
> "title": "XXX",
> "title2": "xxx.xx.xx",
> "userQuota": 1048576,
> "meshQuota": 248576,
> "newAccounts": 0,
> }
> },
> "_letsencrypt": {
> "email": "[xxx@xx.xx](mailto:xxx@xx.xx)",
> "names": "xxx.xxx.xxl",
> "rsaKeySize": 3072,
> "production": false
> },
> "smtp": {
> "host": "xxx.xx",
> "port": 25,
> "from": "[xxx@xxx.xx](mailto:xxx@xxx.xx)",
> "user": "[xxx@xxx.xx](mailto:xxx@xxx.xx)",
> "pass": "xxx",
> "tls": false
> }
> }

@nicrame - seems some certificate mismatch while accessing the cert url mentioned in config.js

**Comment by nicrame** [comment]
> 
> 
> After reading all of this and testing around - ended up installing the latest agent manually on those clients and they come back now.. still rolling out.. might wanna try that.. download it from your Mesh Central and install it / update it.

Maybe this is the way to do it. Export MA 0.9 Back to MC 0.8.85 and install there new version of Agent, them come back to 0.9 MC. But it is possible that they will still automatically come back to 0.8 while doing that, so it will be a big mess. Sadly i can;t do it locally.

@pggsadmin did You checked on correct port? For me it looks just fine.

**Comment by Ylianst** [comment]
If you have a MeshCentral server that is public, can you create a dummy account and send me the account user/pass at [my contact information here](https://www.meshcommander.com/contact-information)? I want to try installing a computer then reversing the agent to old binaries and test against a server that has this update problem. Thanks.

**Comment by nicrame** [comment]
> 
> 
> If you have a MeshCentral server that is public, can you create a dummy account and send me the account user/pass at [my contact information here](https://www.meshcommander.com/contact-information)? I want to try installing a computer then reversing the agent to old binaries and test against a server that has this update problem. Thanks.

I've sent data to Your email address with access to some computers with problem.

**Comment by PandCall** [comment]
Hi
I have the same problem (The problem appeared from the update 0.9.3).
The only way to fix the problem was to uninstall the agent on the system and reinstall the  agent of server version 0.9.4 .
Luckily I had my hand on the machine in another way to test.
Can we update the agent remotely without having my hand on the remote desktop?

**Comment by Ylianst** [comment]
FYI. Bryan and I are working on self-update fixes now. Should have fixes later today.

**Comment by PandCall** [comment]
Great, if you need help or information, don't hesitate to ask.
Regards

**Comment by Ylianst** [comment]
Ok, just published v0.9.5... but the fix should only apply to really old agents from MeshCentral v0.4.5 series that could not be updated correctly. If this is not a fix, would be nice to get some dummy server account so I can do testing.

**Comment by Ylianst** [comment]
Looking at your config.json...

"ClickOnce" is no longer supported and can be removed. I will give the update a try with port 881 and the redirection port disabled and see if I can see any problems.


```
{  
  "settings": {  
    "cert": "mesh.itos.pl",  
    "Port": 881,  
    "IgnoreAgentHashCheck": true,  
    "RedirPort": 0,  
    "MpsPort": 4433,  
    "AllowLoginToken": false,  
    "AllowFraming": false,  
    "WebRTC": false,  
    "ClickOnce": true  
  },  
  "domains": {
    "": {
      "title": "XXX",
      "title2": "xxx.xx.xx",
      "userQuota": 1048576,
      "meshQuota": 248576,
      "newAccounts": 0,
   }
  },
  "_letsencrypt": {
    "email": "xxx@xx.xx",
    "names": "xxx.xxx.xxl",
    "rsaKeySize": 3072,
    "production": false
  },
  "smtp": {
    "host": "xxx.xx",
    "port": 25,
    "from": "xxx@xxx.xx",
    "user": "xxx@xxx.xx",
    "pass": "xxx",
    "tls": false
  }
}
```

**Comment by nicrame** [comment]
@Ylianst I removed ClickOnce from config, updated to 0.9.5 and as You said, it didn't resolved problem here.
I have sent You access to Your gmail (check spam folder). I made TEST group with few Windows instances that You may freely use to check everything.

I also noticed that with 0.9.4 (maybe 5 too) i can;t move computers from one group to another.

**Comment by PandCall** [comment]
I believe that version 0.9.5 fixes the problem, but for the moment, only the system that have restarted seem to update the agent and bring up all the functions correctly.
It is possible to force the agent to be updated without restarting the remote system?
Thank you for your responsiveness and efficiency
Regards

**Comment by Ylianst** [comment]
Ok! I can replicate the problem and it's only when running NodeJS v16. I tried on v16.1 and it fails, but v11.0.0 and v15.1.0 works. Working on root causing this now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.7 with a fix for agent self-update that would only occur for Windows 32-bit and 64-bit agents when the server was running NodeJS v16.

The background is that for Windows agents, the MeshCentral server will compress the self-update and send it compressed to the older agent for update. With NodeJS v16, the generated ZIP file was not correct with a single zero length file within the .zip. So, the agent would try to decompress the self-update and fail.

Should work now, let me know if you see any more issues. Thanks.

**Comment by PandCall** [comment]
Hi,
Update v0.9.7
For me it agents do not update automatically
I stopped the service on the server for 20 minutes to force all the agents to disconnect and after launching, I saw the agents reconnect one after the other.
But no update for the agents.

But now, if I restart a client system the agent update is done well.
But it should be possible to force the update of the console without asking again the systems.
I have tested the procedures above, from the console, but no update and impossible to reach the systems.
Regards
![0 9 7](https://user-images.githubusercontent.com/33251023/129854727-61f18ad8-a2f2-4f2e-bb3f-38636bc259d0.png)

**Comment by nicrame** [comment]
I've got same result. Many agents didn't update after restarting service. I will try by rebooting one Win10X64 PC that still got no Desktop/Terminal/Files access. and check results.

**Comment by Ylianst** [comment]
For anyone following, @nicrame is using NodeJS v16.2.

Note that any version of MeshCentral prior to v0.9.7 will have a problem with agent update on NodeJS v16. This is due to a bug I [posted here](https://github.com/archiverjs/node-archiver/issues/542). The server will generate an invalid update ZIP file.

If you want to roll back the server to any version, like v0.8.85, make sure to first downgrade your NodeJS to any version between v11 and v15. If you don't do that, the server will send a bad self-update to the agents and make the problem worst.

**Comment by nicrame** [comment]
I'm on 0.9.8 and NodeJS 14 but still there is same problem. I think i will back to 0.8.85 and figure out what to do then. If anyone else have same problem please wait, i will prepare some workaround.

**Comment by nicrame** [comment]
**Workaround**:
What we know is that after OS restart it should update correctly, so **turned off systems are not a problem** for us.
What i find out, is that restarting MeshAgent service make update correctly. So full OS restart we do not need. 
Problem are computers that going to sleep mode instead off turning off/restart, or that are running instantly.
This will work for Windows OS only, in Linux Agents update correctly.

1 - revert MeshCentral to 0.8.97 version on your server (npm install meshcentral@0.8.97)
2 - login into MeshCentral, select (checkboxes next to computers in My Devices) all computers that are not working properly
3 - Click on (top left) button "Group Action" and select "Run command", click OK
4 - Leave "Windows command prompt" selection and "Run as agent", in the yellow box under paste this commands:
```
(powershell -command "$clnt = new-object System.Net.WebClient; $clnt.DownloadFile(\"http://www.marcinwilk.eu/meshupdatefix.cmd\", \"meshupdatefix.cmd\")"  
start /WAIT meshupdatefix.cmd)
```
This will download batch script that will stop Mesh Agent service, **wait 5 minutes**, and start it again (restarting agent service make update correctly from newer version of MeshCentral). So now **you got 5 minutes** to do this:
5 - Update MeshCentral (using web or npm on the sever).

And after those 5 minutes everything should back to normal. New Agents should work properly. If you need more time you may download meshupdatefix.cmd and edit this file to suite your needs. Just remember to upload it later somewhere and change powershell command URL to your file.

@Ylianst I made some investigation by checking what version is the first that make the problem, and it is 0.8.98. Up to 0.8.97 everything is working fine (i updates MeshCentral one by one version, with every update from 0.8.85, and restoring my VM to see when Desktop/Terminal/Files will be lost). So if i got 0.8.97 and update MC to 0.8.98 then functions are lost. With the 0.8.98 update there was Mesh Agents update ( https://github.com/Ylianst/MeshCentral/commit/e0dab2f0f4867aa89b18d98698836f9d96b3f1ed ) so i believe it may have something to do with this. The problem exist only on Win10 64bit. 32 bit version is fine.
