### ISSUE TITLE
Windows Agent - Version in WMI / Registry

### ISSUE THREAD

**Issue by rossmarkflo** [Ylianst/MeshCentral#3032]
We had issues with the agent updates as well - Desktop not showing. It seems to help to just install the latest agent on our clients.

For this purpose we use tools like PQD Inventory and Deploy - how ever we can not just target a certain agent version and update them, as the Agent Version is not shown in the registry respective in the WMI information pulled from Windows.

Can you add the agent version so it is shown correctly? This would help us updating only agents that aren't up to date.

Central Mesh is not helping us here - as for some reason the update continues to fail. We tried all options there already.

**Comment by Ylianst** [comment]
The MeshAgent has registry keys at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Open Source\Mesh Agent`. Your right that is does not include the agent version. That would be a great add.

![image](https://user-images.githubusercontent.com/1319013/129603744-c58ff0fb-9adb-4182-a092-ab910e1f7f99.png)

**Comment by si458** [comment]
the agent now currently sets the `CommitDate` in the registry which is the meshcore/agent date
![image](https://github.com/Ylianst/MeshCentral/assets/765314/fb12f723-64c9-4dbd-aa7a-895b37bbc6fa)
same with the wmi registry
```
 {
  "name": "Mesh Agent",
  "version": "2022-12-02 19:42:16.000+00:00",
  "location": "C:\\Program Files\\Mesh Agent\\Mesh Agent\\"
 },
```
