### ISSUE TITLE
MeshAgent do not upgrade automatically - From 0.4.5-x to 0.9.4

### ISSUE THREAD

**Issue by itsmedakshesh** [Ylianst/MeshCentral#3033]
Tried the self-upgrade from 0.4.5-x to the most latest 0.9.4.
- No desktop Tab and none of the tabs works.
- Terminal does not accept commands. Stuck at "Setup..."
- Files tab is greyed out. Stuck at "Setup..."
- #3025 This did not helped.
- "agentupdate" command not working in Console.

No error during installation. Successful at the end.

- When adding a new computer after upgrade, it works just fine. Not the old agents already connected.

Please guide. Thank you.
<img width="1792" alt="Screen Shot 2021-08-16 at 12 33 39 PM" src="https://user-images.githubusercontent.com/78626086/129598158-b65c3a76-3e36-4ab9-90b6-8cb3eddebb7e.png">
<img width="810" alt="Screen Shot 2021-08-16 at 12 33 46 PM" src="https://user-images.githubusercontent.com/78626086/129598175-0f756093-d8e4-4e27-87a0-b53c52389200.png">
<img width="913" alt="Screen Shot 2021-08-16 at 12 33 52 PM" src="https://user-images.githubusercontent.com/78626086/129598189-0b46690b-b1e1-4481-b82b-31fc7a2e4c84.png">
<img width="1792" alt="Screen Shot 2021-08-16 at 12 34 16 PM" src="https://user-images.githubusercontent.com/78626086/129598198-8c5a8363-7445-42b9-a498-a526d3fd6394.png">

**Comment by itsmedakshesh** [comment]
I see that the agent version went to "MeshCore Recovery". 
<img width="993" alt="Screen Shot 2021-08-16 at 12 44 15 PM" src="https://user-images.githubusercontent.com/78626086/129599435-a41a973e-3371-4f01-b1a7-731956120d6a.png">

**Comment by Ylianst** [comment]
Can you go in the device "Console" tab and type "versions" and "agentupdate" and let me know that you see:

![image](https://user-images.githubusercontent.com/1319013/129602827-639305ca-d569-48fb-b9ff-24f1cceef158.png)

**Comment by itsmedakshesh** [comment]
> Can you go in the device "Console" tab and type "versions" and "agentupdate" and let me know that you see:
> 
> ![image](https://user-images.githubusercontent.com/1319013/129602827-639305ca-d569-48fb-b9ff-24f1cceef158.png)

Thank you for your reply.

"Versions" - Command worked
"AgentUdpate" does not work. 

and I waited a little longer but no progress.


<img width="809" alt="Screen Shot 2021-08-16 at 1 14 20 PM" src="https://user-images.githubusercontent.com/78626086/129603070-5fd46fa8-09f5-48b1-827e-840ac078eb7f.png">

**Comment by Ylianst** [comment]
MeshCentral v0.4.5-x is really old. Let me do a test and see what is going on. One possibility will be to roll back to an intermediate version of MeshCentral before going to the latest.

**Comment by itsmedakshesh** [comment]
Do you know if we can select which version to upgrade or update from mesh itself? Thank you.

**Comment by itsmedakshesh** [comment]
> MeshCentral v0.4.5-x is really old. Let me do a test and see what is going on. One possibility will be to roll back to an intermediate version of MeshCentral before going to the latest.

Just revert the version to "0.7.89" and noticed something like below" Any comments please? And can you guide me what is hash check refers to?

<img width="1789" alt="Screen Shot 2021-08-16 at 1 30 39 PM" src="https://user-images.githubusercontent.com/78626086/129605209-40cbaa0e-a63d-41fb-b862-ef8ce130c693.png">

**Comment by Ylianst** [comment]
Ohhh!!! You probably have a MeshCentral server in LAN mode and the agent did a multicast to find the server and found the IPv6 address of the server. I don't think we ever tested that case.

One crazy thing to do would be to turn off IPv6 on the server and try again... however, you just gave me a new test case that I can go explore now.

**Comment by itsmedakshesh** [comment]
> Ohhh!!! You probably have a MeshCentral server in LAN mode and the agent did a multicast to find the server and found the IPv6 address of the server. I don't think we ever tested that case.
> 
> One crazy thing to do would be to turn off IPv6 on the server and try again... however, you just gave me a new test case that I can go explore now.

I tried disabling the IPv6 address. Now I see the same error with the IPv4 Address in the error. But there is interesting I noticed. I downloaded the file using the URL and manually tried to "update" - This time the error went off and now the node is working fine. Now my question is why it is happened and what is this hashing referring to? Is that something we can modify and send it to agent? The reason I am avoiding to do it manually is because I have 800+ computers and a short deadline to push a file to each node. 

Maybe today I have bugged you enough. I really appreciate your quick responses. And ofcourse, I would love to join your team and help in difference cases to try and run. Let me know if I could be of any help.

Thank you.

**Comment by Ylianst** [comment]
FYI. Bryan and I are working on this right now. I am going back and forth between v0.4.5-y and v0.9.4 and we fixed a few things already. I should have an update in a few hours.

**Comment by itsmedakshesh** [comment]
> FYI. Bryan and I are working on this right now. I am going back and forth between v0.4.5-y and v0.9.4 and we fixed a few things already. I should have an update later today.

OMG!! You guys are best in this world. Let me know if you want me to try something. I can provide the connection information - I have a miniature version setup at my home. Feel free to connect. :)

**Comment by Ylianst** [comment]
Bryan got a fix ready. I am doing testing on it and will publish it as MeshCentral v0.9.5 shortly if all goes well. Should be able to update all the agent correctly as the new MeshCore and RecoveryCore will work on these old agents.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.5 with Bryan's fix for this. Let me know if it works. it should correctly update agents from the v0.4.5 series and up.

**Comment by itsmedakshesh** [comment]
Hello, I am afraid but the update did not work for me. I am not sure what is going wrong. Please find the attach screenshot.

![Screen Shot 2021-08-16 at 5 14 22 PM](https://user-images.githubusercontent.com/78626086/129630452-f0b941fd-6504-482a-86bb-d08ff9a79b7c.png)

**Comment by itsmedakshesh** [comment]
> Hello, I am afraid but the update did not work for me. I am not sure what is going wrong. Please find the attach screenshot.
> 
> ![Screen Shot 2021-08-16 at 5 14 22 PM](https://user-images.githubusercontent.com/78626086/129630452-f0b941fd-6504-482a-86bb-d08ff9a79b7c.png)

One another thing I just noticed that, when I type the URL I can download the file but its block at first attempt saying "
<img width="625" alt="Screen Shot 2021-08-16 at 5 29 02 PM" src="https://user-images.githubusercontent.com/78626086/129631849-9d8059cb-3c70-4df7-b630-82b11ceeacc1.png">
this download can harm your computer..."

I don't know if this is relevant but thought to share.

**Comment by Ylianst** [comment]
So, we are making progress. It does seem like the agent is downloading the update from the URL "https://172.16.10.24:443/meshagents?id=4" but fetching from that URL does not return the expected MeshAgent binary file.

Typing "AgentUpdate" in the console will have the agent try again.

![image](https://user-images.githubusercontent.com/1319013/129636711-0026f060-ed94-4a23-a10a-e19a916f956b.png)

I am noticing that your using a private IP address. Is there anything that could block loading the URL?

Also, for the "hard your device" warning, this is normal. Sadly, remote management agents are often used for bad things and so, this normal is normal. It's not impossible that at this point, it's an anti-virus that is blocking the download, but it's hard for me to debug this over GitHub.

**Comment by Ylianst** [comment]
Ok, I was able to replicate the "failed hash check" problem on a different server. It seems like the agent is not downloading the update correctly, Bryan will be investigating this.

**Comment by itsmedakshesh** [comment]
> Ok, I was able to replicate the "failed hash check" problem on a different server. It seems like the agent is not downloading the update correctly, Bryan will be investigating this.

You know I observed something:
1) I do not have a SSL certificate "Self-Signed" and I see that you have no error on certificate part (From SS I am saying) and,
2) The second server you tried, does it contain any trusted certificate?

I don't know if the above make any sense but thought to share. 

Thank you so much for investigating this issue more further.

**Comment by Ylianst** [comment]
The best way around this is to install MeshCentral v0.7.1 and wait a few weeks for all agents to update to that intermediate version, then you can update again. The problem is that the agent in v0.4.5-y is so old, it can't handle HTTPS file downloads correctly. Bryan may be able to fix it, but it's not a sure thing.

**Comment by itsmedakshesh** [comment]
> The best way around this is to install MeshCentral v0.7.1 and wait a few weeks for all agents to update to that intermediate version, then you can update again. The problem is that the agent in v0.4.5-y is so old, it can't handle HTTPS file downloads correctly. Bryan may be able to fix it, but it's not a sure thing.

I was wondering if you can help me to how to downgrade/upgrade to a specific version? I do not see more information on GUI ? 

Thank you.

**Comment by VINISHVV** [comment]
> > The best way around this is to install MeshCentral v0.7.1 and wait a few weeks for all agents to update to that intermediate version, then you can update again. The problem is that the agent in v0.4.5-y is so old, it can't handle HTTPS file downloads correctly. Bryan may be able to fix it, but it's not a sure thing.
> 
> I was wondering if you can help me to how to downgrade/upgrade to a specific version? I do not see more information on GUI ?
> 
> Thank you.

To install a specific version of meshcentraln application goto /node_modules and run
**npm install meshcentral@0.7.1** 

I suggest taking a backup of the existing application before running this command.

**Comment by itsmedakshesh** [comment]
> > > The best way around this is to install MeshCentral v0.7.1 and wait a few weeks for all agents to update to that intermediate version, then you can update again. The problem is that the agent in v0.4.5-y is so old, it can't handle HTTPS file downloads correctly. Bryan may be able to fix it, but it's not a sure thing.
> > 
> > 
> > I was wondering if you can help me to how to downgrade/upgrade to a specific version? I do not see more information on GUI ?
> > Thank you.
> 
> To install a specific version of meshcentraln application goto /node_modules and run
> **npm install meshcentral@0.7.1**
> 
> I suggest taking a backup of the existing application before running this command.

Thank you VinishVV, but this will remove my existing nodes from the mesh? Am I correct?

**Comment by VINISHVV** [comment]
> > > > The best way around this is to install MeshCentral v0.7.1 and wait a few weeks for all agents to update to that intermediate version, then you can update again. The problem is that the agent in v0.4.5-y is so old, it can't handle HTTPS file downloads correctly. Bryan may be able to fix it, but it's not a sure thing.
> > > 
> > > 
> > > I was wondering if you can help me to how to downgrade/upgrade to a specific version? I do not see more information on GUI ?
> > > Thank you.
> > 
> > 
> > To install a specific version of meshcentraln application goto /node_modules and run
> > **npm install meshcentral@0.7.1**
> > I suggest taking a backup of the existing application before running this command.
> 
> Thank you VinishVV, but this will remove my existing nodes from the mesh? Am I correct?

No this will not remove your existing configurations. The same command we are using for upgrading Meshcentral applications through UI options.

**Comment by Ylianst** [comment]
In a bit of a surprise, Bryan found a way to fix the invalid hash download issue. He is getting the fix ready and should be released shortly. This will only impact very old v0.4.6 and older agents that has this specific issue during update.

**Comment by Ylianst** [comment]
MeshCentral v0.9.6 just published! Let us know if is works!

**Comment by itsmedakshesh** [comment]
> MeshCentral v0.9.6 just published! Let us know if is works!

This is awesome... it worked!! but now the last part is "Desktop" tab cannot connect the system. Terminal - gets connected I see the command prompt. but no desktop. Let know if you have the same experience. Thank you. And once again... you guys are super cool. 
<img width="1086" alt="Screen Shot 2021-08-17 at 9 00 40 AM" src="https://user-images.githubusercontent.com/78626086/129730165-540810b3-71f2-4c93-8aeb-cc4989c272c3.png">

**Comment by VINISHVV** [comment]
> > MeshCentral v0.9.6 just published! Let us know if is works!
> 
> This is awesome... it worked!! but now the last part is "Desktop" tab cannot connect the system. Terminal - gets connected I see the command prompt. but no desktop. Let know if you have the same experience. Thank you. And once again... you guys are super cool.
> <img alt="Screen Shot 2021-08-17 at 9 00 40 AM" width="1086" src="https://user-images.githubusercontent.com/78626086/129730165-540810b3-71f2-4c93-8aeb-cc4989c272c3.png">

Are you getting any errors in the agent console?

**Comment by itsmedakshesh** [comment]
> > > MeshCentral v0.9.6 just published! Let us know if is works!
> > 
> > 
> > This is awesome... it worked!! but now the last part is "Desktop" tab cannot connect the system. Terminal - gets connected I see the command prompt. but no desktop. Let know if you have the same experience. Thank you. And once again... you guys are super cool.
> > <img alt="Screen Shot 2021-08-17 at 9 00 40 AM" width="1086" src="https://user-images.githubusercontent.com/78626086/129730165-540810b3-71f2-4c93-8aeb-cc4989c272c3.png">
> 
> Are you getting any errors in the agent console?

No, agent console looks good to me. All other functionality works fine. Even terminal I can access, files too. But desktop - no.

**Comment by itsmedakshesh** [comment]
> MeshCentral v0.9.6 just published! Let us know if is works!

Sorry it is working now. May be need a little time to finish the upgrade the agents. Its all working and we can now close this issue. Its finally resolved. And huge kudos to the owner and contributors.

**Comment by Ylianst** [comment]
Excellent!! I am so happy this one if fixed. Good work on Bryan's part to fix all the issues. Thank you for reporting the results and closing this.

**Comment by itsmedakshesh** [comment]
Hello @Ylianst ,

I was able to upgrade the 0.4.5-x to 0.9.7 in the production environment but I found out that Bulk uploads does not work as well as I see that plugins gets installed but does not show up as a tab on agents (or selecting single node).

![Screenshot_20](https://user-images.githubusercontent.com/78626086/130079679-1b6e7d2f-d49d-45af-b9e5-0ce0898868a4.png)
![Screenshot_21](https://user-images.githubusercontent.com/78626086/130079681-648dfec9-3264-4437-a9c7-687112b2e84c.png)
![Screenshot_22](https://user-images.githubusercontent.com/78626086/130079682-d2f3267c-7f3f-44fd-9863-44a5640426df.png)

**Comment by itsmedakshesh** [comment]
Never mind. its fixed now. Thanks a lot. 👍🏻
