### ISSUE TITLE
Reset password emails are broken

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#3034]
When a user tries to reset a password the (HTML) email doesn't show a link, and the email source includes some '=3D' that need to be removed to make the link usable.

0.9.4

**Comment by Ylianst** [comment]
I just tested it and I don't see any errors. I get an email with a link like this:

https://central.mesh.meshcentral.com/checkmail?c=P6MGMm9uIkCBZBAFi4VczcfjWcgJFEJ0Km@26JkyvAheOUhAScqkeHvMAJyfXavUwqIpPMh65R5tbiAM7fuPrkQdy$nvVGjpefGg9KXeRW0InWodPlanNJ6S2HzH1mY=

Can you send more details as to what link you get? Or send me the email you got to my [contact info here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by OutbackMatt** [comment]
Did you get my email with the broken link??

**Comment by OutbackMatt** [comment]
> Did you get my email with the broken link??

**Comment by si458** [comment]
this works perfectly fine now so please use the latest version and re-open if still having issues
