### ISSUE TITLE
Feature: Filter search in User row

### ISSUE THREAD

**Issue by sharpec** [Ylianst/MeshCentral#3037]
The name of the computers does not help me to understand which user is logged on.
If I use the browser search CTRL + F, it doesn't work on the not yet generated / rendered lines of the page.
The "Filter" box seems to me to act only on the "Device Name".

Is it possible to enable the search also on "User"? Thank you
![image](https://user-images.githubusercontent.com/5232619/129848040-6abf7bc9-db5b-4040-aa39-596e1a934fb4.png)

**Comment by Ylianst** [comment]
Yes, type "u:<username>" or "user:<username>"

**Comment by Ylianst** [comment]
All filters:

```
user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t: xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any
```

**Comment by sharpec** [comment]
I really needed that.  Amazing work! 
Thank you

**Comment by Ylianst** [comment]
FYI. Coming up in MeshCentral v0.9.14.

![M2-DeviceFilterOperators](https://user-images.githubusercontent.com/1319013/131209110-0a772022-24ef-40dd-859b-829f0551faef.png)
