### ISSUE TITLE
Customizing using meshcentral-web folder

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#304]
Invitation page is awesome! Thank you!
I tried to change its design, for this I create meshcentral-web folder and put only changed pictures into it, but after restarting MeshCentral did not work.
As I understand, if you use meshcentral-web, then you need to copy all the MeshCentral files into it, and not just the modified ones?
Incidentally, this is not a mistake? Because this is not exactly the expected behavior for this situation.

**Comment by Ylianst** [comment]
I will look at this. Yes, currently you need to copy everything from /node_modules/meshcentral/public into the "meshcentral-web" folder, however, I did not test the invitation link page in that situation, it's possible I missed it. I will check...

**Comment by Ylianst** [comment]
I just checked and realized I did not give the right instructions. You create a "meshcentral-web" folder and copy the "public" and "views" folders into "meshcentral-web". So, you should have two folders inside "meshcentral-web" and nothing else.

Can you try that and see if it works? I successfully changed the agent invitation page this way.

**Comment by TitovLab** [comment]
Did I understand correctly that in the "public" and "views" folders we need to copy all the files, not just the modified ones?
If so, then this behavior is not expected, as is usually the case. 
Usually, only changed files are in the "meshcentral-web" folder, the main distribution is updated, then with diff and patch the changed files are updated so that the customizations are not lost.
In the current scenario, folders are simply duplicated by 99%, which does not provide the usual flexibility.
Thank you!

**Comment by Ylianst** [comment]
Right, I completely agree that this is not ideal. Right now, I can only tell ExpressJS what folder to use and I specify the meshcentral-web/public and meshcentral-web/views when present instead of the defaults. I can take a look to see if I can make work differently. Probably something I can do at least for the views folder.

**Comment by Ylianst** [comment]
I am swamped with feature requests. This is a good issue but not sure when I will get to it. Pull requests in this area would certainly be nice.
