### ISSUE TITLE
Files tab - viewing a folder with a lot of files crashed the agent

### ISSUE THREAD

**Issue by soapster** [Ylianst/MeshCentral#3041]
I opened a folder that contained over 28k files, and it crashed the agent.

We have alternative ways to do what I was going to do, so we aren't stuck... I just wanted to mention it.

The agent did restart after the crash.

**Comment by Ylianst** [comment]
Oh dear. Thanks for reporting that. I don't think I would have ever tested that case.

**Comment by soapster** [comment]
I don't think so, but maybe. We have stations here with 4 monitors, and so far have not crashed. I'll get it installed on a station with 2x 5k monitors to see how it behaves.

**Comment by krayon007** [comment]
Which agent was this, windows or Linux?

**Comment by PathfinderNetworks** [comment]
I have seen this same issue as well. In my case it is the Windows agent.

**Comment by soapster** [comment]
Yes, windows agent.

**Comment by soapster** [comment]
So, I was able to test it on Windows 10 with 4 monitors, 2 of which were 5k resolution, and it did not have any issues.

**Comment by Ylianst** [comment]
So, it's not the number of monitors that will cause the issue. Rather, you need to cause the agent to send a single very large command. Sent the quality to 90% in desktop settings and put a complex image on the screen and hit connect. That should generate a very large and complex JPEG that, if sufficient large, will (hopefully) crash the agent. Bryan is looking into it.

**Comment by soapster** [comment]
Well, this issue is in regards to the number of files in a folder.  I was only commenting on the monitors because you referenced another issue.

**Comment by Ylianst** [comment]
Understood. My theory is that both issues are related. The agent will crash if sending a single very large command. You can make that happen with lots of files or a complex remote desktop. Bryan is looking into it.

**Comment by Ylianst** [comment]
Bryan did a fix for this. MeshCentral v0.9.16 was published with new MeshAgents that should fix this issue for all OS's. Let us know if it works.
