### ISSUE TITLE
Restrict plugin access

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3042]
@Ylianst
Currently the plugin is available for all users. Like the console or details tab can you enable some restrictions in plugin page?

**Comment by VINISHVV** [comment]
Somany users asked this question
Hope @Ylianst will implement required restrictions

#2505

**Comment by Ylianst** [comment]
I don't do any testing of MeshCentral with plugin's. One thing I need to look into is merging the existing plugin's into MeshCentral and doing security audit on the code, etc. I think that would be best long term and then, we can add access control depending on the specific feature, etc.

**Comment by itpilot** [comment]
Ylianst i totally agree

we understand that you are under pressure for providing an **EXCELLENT Tool**

hopefully you will have the time to do the integration as it will resolve issues with regards to the plugins

thank you again

**Comment by Ylianst** [comment]
What plug-in would be the first one I should integrate?

**Comment by VINISHVV** [comment]
@Ylianst

I think better one will be "MeshCentral-ScriptTask"

**Comment by ryanblenis** [comment]
> What plug-in would be the first one I should integrate?

🥳  Are you going to be integrating directly (e.g. putting things in-line with where certain functionality exists already) or in a more modular approach (where these converted plugins are mostly self-contained and hook into portions of the code where needed) as a first-party/native "plugin". I'd love to see the latter as it could really open up MeshCentral to more external developers and more functionality in the future!

As always, feel free to reach out to me with any questions if you have them (but you can probably figure out everything I've already done by looking at the code)! I haven't done a lot of MC coding lately as I've been on other projects, but I'm excited to see where you take this!

**Comment by itpilot** [comment]
**@Ylianst**

if at all possible

**1. MeshCentral-ScriptTask
2. File Distribution
3. RoutePlus**

**Comment by Ylianst** [comment]
@ryanblenis I will keep it modular. It will be mostly just you code. I will make changes so it is no longer a plugin, so it will not break the plugin if it's also installed. It going to be great to have then included. I will start with "ScriptTask".

**Comment by si458** [comment]
closing as duplicate
