### ISSUE TITLE
Default Core doesn't upload and reconnect behind reverse proxy

### ISSUE THREAD

**Issue by inzi** [Ylianst/MeshCentral#3047]
I open in incident here and have been troubleshooting agent that don't connect when installed behind a reverse proxy:
https://github.com/Ylianst/MeshAgent/issues/106

I'm opening a new issue because I've discovered something based on other issue threads I've read.

OS: Windows Server 2012
Agent OS: Windows Home 64bit
Node Version: v12.16.2.
MeshCentral version: 0.9.7
Agent Version: 64bit service, background & interactive: 2021-Aug-5 13:47:56-0700, 64bit

Agents connected to MeshCentral behind Reverse Proxy (Using IIS w/ ARR). Headers, as detailed in NGINX video tutorial, verified as being sent.

Steps to recreate:

Agent connected, everything functioning normally.

Go to console, instruct agent to clear the core. (Desktop tab disappears, as expected).

In console, instruct MeshCentral to upload default core.

Agent never reconnects.

My config.json file:

```
{
   "settings": {
      "cert": "mesh.domain.com", 
      "wanonly": true, 
      "_minify": true, 
      "port": 480, 
	  "redirPort": 88,
	  "redirAliasPort": 80,
	  "portBind": "127.0.0.1",
	  "AliasPort": 443,
	  "tlsOffload": "127.0.0.1",
	  "CookieIpCheck": false,
	  "CookieEncoding": "hex",
	  "AuthLog":"C:\\ProdApps\\MeshCentral\\logs\\auth.log",
	  "Log":"main,web,webrequest,cert",
	  "agentLogDump": true,
	  "agentLogDump": true,
	  "Plugins": {"enabled":true},
        "AllowLoginToken": true,
        "AllowFraming": true,
        "WebRTC": true,
        "ignoreagenthashcheck": false,	  
      "letsencrypt": {
         "email": "email@domain.com", 
         "names": "mesh.domain.com", 
         "rsaKeySize": 3072, 
         "production": false
      }
   }, 
   "domains": {
      "": {
         "title": "MY Mesh",
		 "AgentConfig": [ "webSocketMaskOverride=1" ],
		 "certUrl": "https://mesh.domain.com"
      }
   }, 
   "smtp": {
      "host": "smtp.office365.com", 
      "port": 587, 
      "from": "email@domain.com", 
      "user": "email@domain.com", 
      "pass": "password", 
      "tls": false
   }
}
```

I created a page that dumped all headers sent to the request, and have verified they are being sent:
X-Forwarded-Host
X-Forwarded-For
X-Forwarded-Proto

I am not sending CF-Connecting-IP as I'm not using CloudFlare.

If I stop the reverse proxy, and change my config use ports 80 and 443, the agent connect and update their core successfully and reconnect.

I can then revert to the 'proxied' config and the agents will work normally.

**Comment by inzi** [comment]
TinyCore loads successfully on the affected agents, default and recovery do not.

**Comment by Ylianst** [comment]
Working on it now! I think I know what the problem is.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.9 with a fix for this. (The version also has Polish translation). Let me know if it works.

**Comment by inzi** [comment]
Testing now -

**Comment by Ylianst** [comment]
Oh good! Let me know. If it does not work, let me know around what version of MeshCentral you updated from. I will try to replicate the issue.

**Comment by inzi** [comment]
Did not work. I updated from 0.9.8.

To test, I moved meshcentral to direct, instead of behind proxy.

Clients all connected.

Stopped all services, moved meshcentral behind proxy.

Clients all still connected.

Clicked on agent, cleared the core, uploaded default core, client did not reconnect.

Same behavior as before, unfortunately.

**Comment by Ylianst** [comment]
Ok. I am going to work on this now!!

**Comment by Ylianst** [comment]
I just noticed you have plugin's enabled. Can you disable them? I just realized that this may be the problem.

**Comment by inzi** [comment]
Gotcha. I don't use any plugins that I know of.  set it to false, restarted. 

This is a vanilla install, otherwise.  I think I enabled it because it was enabled in an example config.

Same behavior - tinycore will load and run, but default core won't push and update.

Are there any files I can send you that will assist?

**Comment by Ylianst** [comment]
Wow, that is crazy. Let me work on this a bit. hopefully I can replicate this using my own reverse proxy.

**Comment by inzi** [comment]
I have control channel logging enabled, and I see it connect to wss://<site>...

does a handshake, verifies the cert matches, sends auth data, processes the request, then says auth complete. 

then I get processcommand 12, then 11 - then control channel seems to go idle.  It's starts playing ping pong with the server for keep alive. 

What's throwing me is everything works with the agent IF, on its first connection to the server, it connect directly.  I'm just guessing, but it feels like that 'registration' bit, when it connects to get the core the first time, seems to fall down.  Once the msh file has the agent in it (I'm guess that's all the extra bytes I see in agents connected vs the ones that won't), the agents behave normally. 

It's when the msh file is in a 'fresh install' state, which I'm assuming is what 'clearing the core' does - sort of resets it.

Which makes me wonder, since it's behind a proxy, if that 'factory reset' agent is actually connecting at all to the URL. 

I've run the server in debug mode - I could do that again, uninstall from this machine - then attempt it again.  I can send you the msh of the misbehaving agent if you need it.

**Comment by Ylianst** [comment]
I just turned on my reverse proxy on a development server and did some testing and I can still push the core correctly... this is wild.

**Comment by Ylianst** [comment]
A few notes on your config.json:

- The Let's Encrypt section needs to be at the root level, not in the settings section.
- In Let's Encrypt section, "rsaKeySize" is no longer used.
- In domain section, agent config, "webSocketMaskOverride=1". New versions of the agent always mask now. So this option is always on and ignored. Can be removed.

Everything else looks good. My corrected config.json below. You are probably not using Let's Encrypt anyway, so I placed it at the right place and commented it out.

```
{
  "settings": {
    "cert": "mesh.domain.com",
    "wanonly": true,
    "_minify": true,
    "port": 480,
    "redirPort": 88,
    "redirAliasPort": 80,
    "portBind": "127.0.0.1",
    "AliasPort": 443,
    "tlsOffload": "127.0.0.1",
    "CookieIpCheck": false,
    "CookieEncoding": "hex",
    "AuthLog": "C:\\ProdApps\\MeshCentral\\logs\\auth.log",
    "Log": "main,web,webrequest,cert",
    "agentLogDump": true,
    "Plugins": {
      "enabled": true
    },
    "AllowLoginToken": true,
    "AllowFraming": true,
    "WebRTC": true,
    "ignoreagenthashcheck": false
  },
  "domains": {
    "": {
      "title": "MY Mesh",
      "certUrl": "https://mesh.domain.com"
    }
  },
  "smtp": {
    "host": "smtp.office365.com",
    "port": 587,
    "from": "email@domain.com",
    "user": "email@domain.com",
    "pass": "password",
    "tls": false
  },
  "_letsencrypt": {
      "email": "email@domain.com",
      "names": "mesh.domain.com",
      "production": false
    }
}
```

**Comment by inzi** [comment]
On the javascript - It's IIS, so it is possible IIS is trying to be helpful. 

While this meshcentral implementation isn't production, I do have some production services running on this box. 

Let me see if I can build a sandbox for you to test on somewhere with my config or both MeshCentral and IIS ARR. I can try and spin up a windows 10 machine and see For the headers required for being behind a reverse proxy - I built a small page that dumps the headers - so I did verify they're being passed correctly. 

for proto, however, I'm just passing "https" - would that matter? 

I can see a scenario where the agent request coming through the reverse proxy examines this header, doesn't see what it expects in order to detect its a secure request, and simply not sending it.   However, the value of 'https' should suffice. 

I'll test this to try and recreate on Windows 10 - setup IIS and ARR- try and recreate. 

if I can accomplish this, I'll get with you so you can remote into them - or document my exact steps. 

I did try and upgrade my node.js to v14 - the install put v12 on it.   Wondering if it was related to the v15 compression bug. 

Are there any switches I can use on both the agent and the server that would give me more info? 

On the server, I'm starting at a prompt with --debug switch. I did the same on the agent in an attempt to gather data.

I see in the code that the system will log 'agent' events, but I'm not sure how to turn it on.  I suspect that's debug information that'd be most illuminating.

**Comment by inzi** [comment]
An Update

I let agents connect directly, then put behind proxy, then cleared core for one machine.

Then, I started the agent from command line as administrator and got:

Connecting to: wss://<my mesh URL>:443/agent.ashx
Connected.
Server verified meshcore... Launching meshcore....
oops

"oops" doesn't sound good. =)

**Comment by inzi** [comment]
Anyway to get the exception from ILibDuktape_Helpers.h?

**Comment by inzi** [comment]
I'm going to setup nginx on this server, reverse proxy it, and try and recreate. 

If it works behind nginx, it's got to be something with my configuration, or something IIS ARR is doing, that's breaking this.

**Comment by inzi** [comment]
Update - Basic configuration behind NGINX works as expected. 

I'll examine the IIS ARR configuration in detail and update you. 

This has to be related to IIS & ARR - as the reverse proxy functionality performed flawlessly behind NGINX.

I'll leave this as open for now, if that's ok.

**Comment by inzi** [comment]
I'm going to close the issue for now - as the title should read that this is behind IIS ARR Reverse Proxy. 

I'm troubleshooting the IIS ARR configuration to see if I can make it behave exactly like NGINX, which is obviously having no issues.

**Comment by Ylianst** [comment]
I have never used IIS as a reverse proxy, but looking at this line:

**Comment by inzi** [comment]
I think this may be the issue.

Does "compression": false disable sending the meshcore in compressed form?

**Comment by inzi** [comment]
An option to encode all traffic in base64 would help tremendously - but I am fearful of the performance impact.

**Comment by inzi** [comment]
Of note - I've leveraged the agentPort feature, and put agent traffic on a specific port. 

While suboptimal, this allows use of IIS on the server in conjunction with ARR for the management portal.
