### ISSUE TITLE
Remote control Screen Off during session ?

### ISSUE THREAD

**Issue by PandCall** [Ylianst/MeshCentral#3048]
Hi Team
Is it possible to hide the remote screen during a remote control to hide the actions and information used (code, command, etc. ...)
Regards

**Comment by VINISHVV** [comment]
> Hi Team
> Is it possible to hide the remote screen during a remote control to hide the actions and information used (code, command, etc. ...)
> Regards
@PandCall - screen hide method is little difficult in current screen capture method and also this request is already dined by majority of community members.

**Comment by PandCall** [comment]
Thanks, that leaves a lot of evolution to come :)
Regards

**Comment by Ylianst** [comment]
Bryan took a look at this and there is no easy way to blank the remote screen and capture the screen at the same time. You can use MeshCentral to RDP into a remote computer using the web based RDP client or MeshCentral Router. In that case, the devices display will move back to the login screen.

This may be possible using a virtual mirror display driver? Not sure.
