### ISSUE TITLE
Dynamic device groups

### ISSUE THREAD

**Issue by WouterLS** [Ylianst/MeshCentral#3049]
Hi,

Would it be possible to define dynamic device groups?
for instance, Servers and workstations?
I would like to then set the prompt for consent on workstations, but not on servers.

**Comment by Ylianst** [comment]
You can move devices between device groups. So, you can create a new device group, multi-select your servers, hit "Group Actions..." and move the selected devices to another group. Once moved, the user consent policy of the new group will be effective immediately.

I am not sure about "dynamic device groups". The problem with more complex policy group constructs is that it gets more difficult to know what policy applies to each device.

Let me know if moving devices works.

**Comment by WouterLS** [comment]
I guess that would work. haven't tried it yet.
that would just mean we manually need to move either the servers or the others.

I wondered if there was a more efficient way.
