### ISSUE TITLE
Messenger on remote device

### ISSUE THREAD

**Issue by johnczer** [Ylianst/MeshCentral#305]
I noticed that the meshmessenger works on remote device when agent is connected using the install/update method (so running as a service) but does not work when using the "connect" temporary method.  Is this by design?

**Comment by krayon007** [comment]
I'll take a look at it, but I think it's caused because it  spawns a child process to launch the browser in the correct user context, but this requires local system privilege. I think I can fix it by detecting if the agent is running as the current user, in which case I won't need to try to create a security context.

**Comment by johnczer** [comment]
Not sure what rights are required but in this case and I think in most would be that the user would have local user Admin rights on the remote PC. There are some instances where if it is their personal device they may not have it set that way initially. So just to clarify it does work on a PC in my lab under the same account when using the permanent connection but just not the temporary method. I did try this on another PC outside of my environment and same result. Thanks for checking into this.

**Comment by Ylianst** [comment]
Bryan & I will take a look at it. Messenger should work fine even when using "connect".

**Comment by johnczer** [comment]
I just wanted to update this post with some log information from the remote device running the agent in temporary mode. This is from the 
meshagent.log: [2019-06-19 09:11:51 AM] ..\microstack\ILibProcessPipe.c:799 (2,1314) (null)
This error repeats itself in the logs each time I try to use the messenger.

**Comment by johnczer** [comment]
Ylian, did you verify that this was a bug in the meshagent or is there something maybe on my end? I have tried several things to get the chat to work over the temporary connection but not such luck. I know you guys are busy and I can start a new post but I also noticed that I am not able to type special characters (- and _) so far that I have discovered on a remotely connected PC.  Thanks for all of your hard work guys!

**Comment by johnczer** [comment]
Brian, Just to give you an update I tried to run the agent as current user and messenger works for the temporary connect method but breaks messenger on the permanent connection. When I say break I get an Interactive Services Detection popup on Windows 7 PC. I am not a coder but I have been researching this for some time thinking I could find the magic.

**Comment by krayon007** [comment]
Is the background service running as LocalSystem or as a specific user?

**Comment by johnczer** [comment]
It is running as Local System

**Comment by krayon007** [comment]
Are you seeing this issue on just your Windows 7 machine, or others too? (which Service Pack are you running on your win 7 machine?)

Thanks

**Comment by johnczer** [comment]
I have tried on the Windows 7 SP1, Windows 10, and Windows Server 2012R2 and see the issue only with the temporary connect. Otherwise messenger works on permanent agent install.  Thank you

**Comment by johnczer** [comment]
The reason I'd like to get this to work is because I would use the temporary agent for remote customer sites and when I am done I can just close out the agent to permanently disconnect. If I were to use the install method I have to remember to uninstall the agent or it stays connected.

**Comment by dinger1986** [comment]
looks to be sorted here @si458 https://github.com/Ylianst/MeshCentral/issues/440

**Comment by si458** [comment]
closing as stale but also dont have this issue anymore
