### ISSUE TITLE
Filter and export on additional fields

### ISSUE THREAD

**Issue by kevinh-csalabs** [Ylianst/MeshCentral#3054]
Currently the filter is only able to search/filter on select fields such as computer name. It would be helpful to be able to filter on additional fields such as current/last user's name and computer's serial number. 

Use case: user asks for support, but doesn't know the computer they are in. I can filter by user (this doesn't always work reliably with browser ctrl+f if the computer list is long)

It would also be helpful if the detailed device information export contained all the fields present in the computer details tab instead of just select fields.

Use case: match computer list against inventory records or other software systems where there may be a mismatch due to the system being renamed, but the serial remains the same.

**Comment by nzalev** [comment]
You can filter on additional fields, including username
```
user:username or u:username
ip:ipaddr
group:groupname or g:groupname
tag:tagtext or t:tagtext
desc:description
```

**Comment by kevinh-csalabs** [comment]
@nzalev Thank you - that's very helpful!  I guess I'd revise that then to say:
by default filter by all fields instead of computer name or
add field selection to filter to make this capability apparent to end users.

This capability wasn't apparent to me from the ui and I didn't find any reference to in in the user manual either.

**Comment by Ylianst** [comment]
Here is the full list of filters:

```
user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t: xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any
```

**Comment by dinger1986** [comment]
@si458 @silversword411 maybe needs added to docs and closed?

**Comment by si458** [comment]
already added to docs 
https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#search-or-filter
