### ISSUE TITLE
Meshcentral Agent - Windows - Memory Spike

### ISSUE THREAD

**Issue by KSJakobsen** [Ylianst/MeshCentral#3055]
Hi there,

We ran into an issue over the last few days, that when we are connecting via Meshcentral to our Windows machine (Server 2019 and Windows 10 21H1) they are experiencing a Spike in Memory usage until they are out of memory. The only solution to get the machines working again is a reboot.

I've searched through the issues here and found a similar problem with a Memory Leak on Windows machines. I disabled the plugin feature (since we are not using it) and it seems that it reduced the effect, but it is still happening.

The Screenshot is from today. And it shows the memory usage in percent.
![image](https://user-images.githubusercontent.com/44235327/130770920-a381d75a-02ed-45c6-be46-9c2c1d116e54.png)

As you can see, every spike is a made connection with Meshcentral. 

This is our redacted config file (Just cleaned out IP-Adresses, etc.). We are running on Version 09.10.

[config.txt](https://github.com/Ylianst/MeshCentral/files/7046061/config.txt)

Kind Regards,
Kai - Stephan Jakobsen

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
