### ISSUE TITLE
changed url - clients keep connect to old

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#3062]
I've bought a new url: moved from example.info to example.nl. Now, both are equal. 

The meshcentral server is reachable over example.nl
The android client 2D matrix contains the new URL
LetsEncrypt signs the new URL and certificate is valid

But the windows clients keep connecting to the old example.info url. 

If I go to the meshcentral dashboard and to a windows pc Console, and type info, I can see it connects to .info (old).
If I command 'agentupdate' the response is:
`Downloading update from: https://server.example.info:443/meshagents?id=3`

The only way I could move the installation from '.info' to '.nl' was to have local access to the system, to delete the meshcentral agent and to install it again.

Why does the url not update with the new url settings from config.json if 'agentupdate' command is given ?

**Comment by jdvmanen** [comment]
I would love to close this issue, but can someone give some information on updating the .msh file from central?

**Comment by VINISHVV** [comment]
> I would love to close this issue, but can someone give some information on updating the .msh file from central?

@jdvmanen - I can help you reinstall the agent in bulk.

**Comment by jdvmanen** [comment]
@VINISHVV That would be great, and also to update the .msh prior to the agentupdate?

**Comment by VINISHVV** [comment]
@jdvmanen - can you share below details.
How many agents are connected, How many groups are created in your server.

**Comment by jdvmanen** [comment]
@VINISHVV 157 agents in 8 groups.

**Comment by jdvmanen** [comment]
Some of them incidentical online

**Comment by VINISHVV** [comment]
Bulk installation is possible only for Online devices. Before doing this take complete backup.

1)  Copy meshcentral main folder (  the folder contains **mesh central-data**,  **meshcentral-files** ,**node_modules**) to another folder like Meshcentral 2 / any other drive . Also point both domains into same IP
2) Goto Newly created folder, and then open the mesh central-data\config.json
3) Replace the Cert/cert URL with a new domain 
4) under the domain section activate Agentcustomization by add the below codes as per your company name 

        "agentCustomization": {
        "displayName": "Meshcentral",
        "description": "Meshcentral.",
        "companyName": "Meshcentral",
        "serviceName": "Meshcentral",
        "fileName": "Meshcentral"
   }
5) Replace your domain certificate with new one by editing below files.

                    webserver-cert-private.key
                    webserver-cert-public.crt

6) Stop existing mesh central application.

7) Goto newly-created mesh central applicationfolder\nodemodules\
8)run mesh central using command.
9) Login the application using the new domain name.
10) Goto groups and download all 9 groups messages ( If the agent customization is correct then the downloaded file will like **filename.exe** mentioned in 4th step.
11) Once all groups agents are downloaded just stop the server.

_______________________________________________________________________________

12) Start new server
13) Goto my device right-click on one group and select all agents.
14) Upload the new exe downloaded for the group to any location like **c:\** using group actions.
15) Repeat the exe upload process for all the groups.
16) Goto my device right-click on one group and select all agents.
17) Select " run-command options" using group actions
18} enter below command to start the  installation of new agents.
         **c:\Newagentname.exe -fullinstall**
19)Repeat the same for all groups

Once the process is completed just stop old application  and starts new one.

**Comment by jdvmanen** [comment]
This works @VINISHVV, thanks!
