### ISSUE TITLE
Field is not being translated.

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3069]
![tempsnip](https://user-images.githubusercontent.com/5051443/131222173-3c1197d2-d1b5-4e39-a054-9c25c48c9f23.png)

This camp is not being translated to PT-BR.

**Comment by Ylianst** [comment]
You are right. Thanks for reporting this. Will be fixed in MeshCentral v0.9.14.

**Comment by KBCACheia** [comment]
Thanks, i am happy to help.
