### ISSUE TITLE
fix language encoding

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#307]
https://i.imgur.com/4dberQy.png
https://i.imgur.com/QPaH86s.png
Is it possible to correct the encoding? Windows system use Russian language

**Comment by Ylianst** [comment]
I will take a look at this when I can.

**Comment by motapek** [comment]
Polish language this same, please.

**Comment by Ilia1** [comment]
The username is now displayed correctly. Please do it in the terminal tab. The code page is set to 866.

**Comment by Ilia1** [comment]
I will be satisfied if the terminal will use the Latin alphabet. If you enter "chcp 28591" in the terminal tab, the output will be in Latin in the correct encoding. Correct the encoding automatically when opening the terminal.

**Comment by Ilia1** [comment]
Starting from version Microsoft Windows [Version 10.0.17763.973]  Cyrillic is supported in the terminal tab. For previous versions, a change to the Latin encoding works. Add coding change information to tips & tricks. I close issue.
