### ISSUE TITLE
Bug on "minify" : true,

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3071]
When we activate minify in domain block, the font became black.
![image](https://user-images.githubusercontent.com/5051443/131226026-b7bf9eeb-cce4-4a72-8ff1-dbdcf74d962f.png)
"minify" : true,
![image](https://user-images.githubusercontent.com/5051443/131226044-88d6868b-84b9-4b49-a2b6-1efd9613eb54.png)
"minify" : false,

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
I can't seem to make it happen. This look like "Pt-Br" with minification turned on.

![image](https://user-images.githubusercontent.com/1319013/131226519-4b80da56-c6eb-4a86-bc35-0da8531baf0e.png)

**Comment by KBCACheia** [comment]
Yes, it's PT-BR. I have already tested adding &minify=1 or &minify=0 to the URL. The same happens, if minify is false and the browser &minify=1 (to enable) some word turn black and if minify is true and the browser &minify=0 (to disable) the words stay ok (white). I tested on chrome and firefox.

**Comment by Ylianst** [comment]
Thanks. If your server happens to be public, can you create a dummy account and send over a username and password to me in private. I will try to debug this.

**Comment by KBCACheia** [comment]
> Thanks. If your server happens to be public, can you create a dummy account and send over a username and password to me in private. I will try to debug this.

I sended it to your gmail. Let me now if you need to be full administrator. Make yourself comfortable.

**Comment by Ylianst** [comment]
Thanks. I do see and did fix this problem:

![image](https://user-images.githubusercontent.com/1319013/131229893-abf71854-925c-4ea4-9fd9-1f73d7b5abac.png)

However, I don't see the problem above. Can you hit "SHIFT + Refresh" on your browser and make sure it's not a browser cache issue?

**Comment by KBCACheia** [comment]
> Thanks. I do see and did fix this problem and will be in next MeshCentral version:
> 
> ![image](https://user-images.githubusercontent.com/1319013/131229893-abf71854-925c-4ea4-9fd9-1f73d7b5abac.png)
> 
> However, I don't see the problem above. Can you hit "SHIFT + Refresh" on your browser and make sure it's not a browser cache issue?

The second image was only to show the minify=false behavior. But now i notice that:
![image](https://user-images.githubusercontent.com/5051443/131230220-11f22cc8-6fca-4bb6-9d0c-94e7d0e8f885.png)

The word "nenhum" (none) is black. I haven't notice that before.

SHIFT + Refresh didn't help.

Thanks for the answer.

**Comment by Ylianst** [comment]
One thing you can do it switch to while using the little diamond on the top right of the web page:

![image](https://user-images.githubusercontent.com/1319013/131230496-078f243e-a6f9-4482-8fe8-650397f68001.png)

Let me know what you see. Also, what browser you are using?

**Comment by KBCACheia** [comment]
> One thing you can do it switch to while using the little diamond on the top right of the web page:
> 
> ![image](https://user-images.githubusercontent.com/1319013/131230496-078f243e-a6f9-4482-8fe8-650397f68001.png)
> 
> Let me know what you see. Also, what browser you are using?

![image](https://user-images.githubusercontent.com/5051443/131230573-4daacffd-5db2-47a2-a078-b0700f3052b2.png)
 Wow, i didn't know that, rsrs. In Light Mode it shows. I am using Chrome and Firefox.

**Comment by Ylianst** [comment]
Ha yes, there are a lot of hidden options. Once I release MeshCentral v0.9.16 with the fix, let me know if it works and close this issue. Thanks.

**Comment by KBCACheia** [comment]
I have updated to v0.9.16, but the issue still happens. On device screen, when in Dark Mode, the font color stay black in Brazilian Portuguese (PT-BR) em minify is true..

**Comment by Ylianst** [comment]
I can't make this problem happen on my computer, even when using your server. Are you sure you are not using a night mode browser plugin or some other software to make the web page black?

**Comment by KBCACheia** [comment]
Hum, i don't have any night mode browser plugin or any software to do that. I have tried in EDGE, FIREFOX and CHROME. 
Are you trying in PT-BR language? And it happens only in devices pages.

Here is my config.json, maybe it helps. minify is commented because i am not using it. I tested on browser URL /?minify=1. I already clear the cache.
{
        "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
        "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
        "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",

        "settings": {
                "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
                "cert": "MY_DOMAIN",
                "WANonly": true,
                "_LANonly": true,
                "_sessionKey": "MyReallySecretPassword1",
                "_port": 443,
                "_aliasPort": 443,
                "_redirPort": 80,
                "_redirAliasPort": 80,
                "AgentPong": 300,
                "compression": true,
                "WsCompression": true,
                "AgentWsCompression": true,
                "_autoBackup": {
                        "_mongoDumpPath": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongodump.exe",
                        "backupIntervalHours": 24,
                        "keepLastDaysBackup": 10,
                        "zipPassword": "MyReallySecretPassword3",
                        "_backupPath": "C:\\backups"
                },
                "_maxInvalidLogin": {
                        "time": 10,
                        "count": 10,
                        "coolofftime": 10
                },
                "trustedProxy": "PROXY_IP",
                "TlsOffload": "PROXY_IP"
        },

        "domains": {
                "": {
                        "_title": "MyServer",
                        "_title2": "Servername",
                        "_titlePicture": "title-sample.png",
                        "_loginPicture": "title-sample.png",
                        "_welcomeText": "Sample Text on Login Page.",
                        "_welcomePicture": "mainwelcome.jpg",
                        "_welcomePictureFullScreen": false,
                        "_footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
                        "_loginfooter": "This is a private server.",
                        "_minify": true,
                        "_newAccounts": true,
                        "_userNameIsEmail": true,
                        "twoFactorCookieDurationDays": 7,
                        "geoLocation": true,
                        "certUrl": "https://"mydomain":443/"
                }
        }
}

**Comment by KBCACheia** [comment]
I've tested right now, its because of the DARK MODE on WINDOWS 10 SO. If i put the SO on light mode and the mesh on dark, it works correctly.

**Comment by KBCACheia** [comment]
> I've tested right now, its because of the DARK MODE on WINDOWS 10 SO. If i put the SO on light mode and the mesh on dark, it works correctly.

@Ylianst, did you saw this issue after my answer?

**Comment by dinger1986** [comment]
@si458 old and stale, maybe works fine now

**Comment by si458** [comment]
this is a dark/night mode bug which has been fixed i believe
i even fixed it autoswitching the other month, and fixed the tags in dark mode too
