### ISSUE TITLE
Assistant hangs

### ISSUE THREAD

**Issue by Adminvvs** [Ylianst/MeshCentral#3072]
Hi,
Seems mesh assistant is not stable while compare with agents. While searching i found many issues related to this but still its pending. Can you fix it at earliest?

**Comment by KBCACheia** [comment]
I am having the same issue. My infrastructure is FIREWALL (port 80 e 443) -> NGINX  (port 80 e 443) -> Mesh Central

**Comment by Adminvvs** [comment]
I think both assistant and agent using different technology.

> I am having the same issue. My infrastructure is FIREWALL (port 80 e 443) -> NGINX (port 80 e 443) -> Mesh Central

**Comment by KBCACheia** [comment]
> > I am having the same issue. My infrastructure is FIREWALL (port 80 e 443) -> NGINX (port 80 e 443) -> Mesh Central
> 
> I think both assistant and agent using different technology.

Yeah, they do. I am trying to test multiples environments to find the reason.

**Comment by Adminvvs** [comment]
Any progress on this?

**Comment by Adminvvs** [comment]
@Ylianst
Can you helps to resolve this issue?

**Comment by Ylianst** [comment]
Hopefully I just fixed this in MeshCentral v0.9.45. #3212
