### ISSUE TITLE
Agent for OpenBSD

### ISSUE THREAD

**Issue by Bobberty** [Ylianst/MeshCentral#3074]
Good Morning World,
A MeshAgent for OpenBSD.  Simple.

Just doing a quick survey, it looks like procfs might be a temp roadblock.

**Comment by krayon007** [comment]
Are you unable to mount procfs? From what I can tell, this should be easy to do on OpenBSD?

**Comment by qbit** [comment]
There is no procfs on OpenBSD. There was at one point, but it has been removed for some time now.

**Comment by krayon007** [comment]
So you are saying the mount_procfs utility was removed?

**Comment by qbit** [comment]
All OpenBSD versions released after 2010 have no procfs support in the kernel.

**Comment by krayon007** [comment]
I compiled a version of the agent that runs on OpenBSD without needing procfs. (I had to fix a few other things that were preventing it from working on OpenBSD). I just need to get the installer to work on OpenBSD, since if differs slightly from freebsd.

**Comment by si458** [comment]
this already exists now 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/7efd7b43-d04a-49c2-b058-c51359700171)
