### ISSUE TITLE
Edit User Feature Translation

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3075]
![Edit User Feature](https://user-images.githubusercontent.com/5051443/131366711-3c2b8b17-ef2a-4dab-9a58-bea62075578a.PNG)
This part is not being translated.
Thanks.

**Comment by Ylianst** [comment]
Hi. You need to grab the latest translation file. The best way to get [this file is here on GitHub](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/translate/translate.json). This link always points to the latest translations, you can make changes and send me the update or do a GitHub pull request. Hope that helps.

**Comment by KBCACheia** [comment]
Hi, i am with the new one. I think it something with this particular window. In the file its already translated.

**Comment by Ylianst** [comment]
Ok, will check.

**Comment by Ylianst** [comment]
Added auto-translate into Spanish (pt-br). Will be in v0.9.16.

![image](https://user-images.githubusercontent.com/1319013/131395929-f02c981d-9a01-4b5a-8e20-d234dcec661a.png)

**Comment by KBCACheia** [comment]
> Added auto-translate into Spanish (pt-br). Will be in v0.9.16.
> 
> ![image](https://user-images.githubusercontent.com/1319013/131395929-f02c981d-9a01-4b5a-8e20-d234dcec661a.png)

It's Brazilian Portuguese (PT-BR). ^^

**Comment by Ylianst** [comment]
So sorry. Brazilian Portuguese (PT-BR)

**Comment by KBCACheia** [comment]
Ok, it's been translated now.
