### ISSUE TITLE
Events Translate

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3076]
![My Events](https://user-images.githubusercontent.com/5051443/131366873-fe5caf51-9a09-47b4-99df-f7a80c9e593f.PNG)
Some events are not being translated.
Thanks.

**Comment by Ylianst** [comment]
Added auto-translate into Spanish (pt-br). Will be in v0.9.16. Should fix this.

**Comment by KBCACheia** [comment]
> Added auto-translate into Spanish (pt-br). Will be in v0.9.16. Should fix this.

Its Brazilian Portuguese, not Spanish.
Hehe, i will wait it.

**Comment by Ylianst** [comment]
Oh sorry. yes, Brazilian Portuguese.

**Comment by KBCACheia** [comment]
Perfect, it's ok.
