### ISSUE TITLE
Mesh Assistant don't shows up in the server, even message

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3077]
I have a Windows 10 pro computer that's Mesh AGENT runs perfectly. This PC is in a domain. But, the Mesh ASSISTANT connect with the server but the Help Request notification do not popup in the server and the computer doesn't shows up in the server. But in the ASSISTANT status is connected.
If i use the system tray ASSISTANT use the Computer Mesh AGENT, everything works. But if it use the own agent (agent of Mesh ASSISTANT), nothing happens. But the ASSISTANT shows connected to the server.

Here as the DEBUG txt.
[debug.log](https://github.com/Ylianst/MeshCentral/files/7078338/debug.log)

**Comment by Ylianst** [comment]
Oh. I think the important point is "This PC is in a domain".

Let me check if MeshCentral Assistant works with a sub-domain.

**Comment by Ylianst** [comment]
I logged into your server, downloaded MeshCentral Assistant and connected it and it worked for me. Can you describe each step I have to do to make the problem happens? - Thanks.

**Comment by KBCACheia** [comment]
> Oh. I think the important point is "This PC is in a domain".
> 
> Let me check if MeshCentral Assistant works with a sub-domain. I think the problem is that MeshCentral Assistant is connecting to the wrong domain and so, will show as connected but the server will not know what to do with the connection.

Sorry, when i said domain, it was active directory domain. But i think that is something about it, because other computer in the same network out of AD, it work, but it was windows 7. I am gonna make a few test with other computer.

**Comment by KBCACheia** [comment]
> I logged into your server, downloaded MeshCentral Assistant and connected it and it worked for me. Can you describe each step I have to do to make the problem happens? - Thanks.
That specific problem it in one PC only, i have not tested in another PC in my active directory domain yet.

PS.: But, the connection was not slow when you used it? When i use Assistant, the connection stay very slow.

**Comment by KBCACheia** [comment]
> > I logged into your server, downloaded MeshCentral Assistant and connected it and it worked for me. Can you describe each step I have to do to make the problem happens? - Thanks.
> 
> That specific problem it in one PC only, i have not tested in another PC Windows 10 in my active directory domain yet. I only tested in a Windows 2019 server and it works. Maybe is something in the specifically in this PC.
> 
> PS.: But, the connection was not slow when you used it? When i use Assistant, the connection stay very slow.

Ok, now i am scared. Today i've tested in a VM with Windows 10 pro, connected ia a active directory domain, (Like the machine where the issue happened): 
Without the Agent it works (it connected and showed the help message) ;
With the Agent it also works (it connected and showed the help message, using the Assistant App and Tray).

 Than i came back to the machine where i as having the issue, and everything worked too. I have no idea of why. Could be something of the latest update? When i tryied the last time, Mesh Server was 0.9.15, now is 0.9.18. The Agent was of August, 5, now is August, 30.  I will just wait a answer and close the issue. 
 Thanks soo much.
