### ISSUE TITLE
Screen recordings, keep files for number of days

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#3078]
Instead of defining the total number of recordings to be stored, it would be possible to define a deadline.
Ex. 90 days, so all recordings older than 90 days would be deleted.

**Comment by Ylianst** [comment]
Ok, added it. Will be in MeshCentral v0.9.17.

```
      "SessionRecording": {
        "onlySelectedUsers": true,
        "onlySelectedDeviceGroups": true,
        "index": true,
        "maxRecordings": 16,
        "maxRecordingDays": 30,                      <------------
        "maxRecordingSizeMegabytes": 30,
        "protocols": [ 1, 2, 100, 101, 200 ]
      }
```

You can specify max recordings, days and megabytes. Old files will be removed when one of them matches.

Note that files are removed after a recording is completed. So, if you start the server and there are old recordings, only after a new recording is added are the files checked for removal of old ones.

Once published, let me know if that works.

**Comment by fernandogobah** [comment]
Congratulations.
