### ISSUE TITLE
Select all for a group

### ISSUE THREAD

**Issue by nounours460** [Ylianst/MeshCentral#3079]
Hello,

It is more a request for improvement than a dysfunction

We can easily in MeshCentral select all the machines with the button "Select all" but there is no possibility to find this same function for each group. Also if you want to select 2 (important) groups you have to either select all and remove those you don't want, or do the opposite, which can be quite long depending on the number of machines.

Could you consider adding this feature?

Thank you for your understanding

**Comment by Ylianst** [comment]
Hi. You can right click on a device group name and hit "Select All". Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/131415491-be31c0c4-195a-44b8-9059-98a4a96a61b9.png)

**Comment by PathfinderNetworks** [comment]
I was wondering this same thing- thanks for the heads up for how to do it.  Works perfectly.
