### ISSUE TITLE
Scheduling Mesh Agents 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#308]
If you have a Mesh agent in one group and another agent in another group and need to have a dedicated time to utilize them both for some type or replicating data, systems, information. This would be an enhancement that allows clustering of agents together. Additionally being able to request a time slot to utilize a single agent instance would be beneficial in the same, so then a person could be the only person or key person for an agent during the given time slot.

**Comment by Ylianst** [comment]
Hi. So, I understand doing agent scheduling (assigning a time slot for a user to an agent). However, I don't understand the "clustering of agents together". Can you explain more on this?

**Comment by mschubeck** [comment]
It almost sounds like he wants to have certain employees restricted to certain groups, and have a scheduler move agents in and out of those groups on a scheduled basis for routine tasks or maintenance.

If I'm understanding it correctly, I get the concept but it's not a very productive method of task completion at any of my MSPs.

**Comment by Ylianst** [comment]
So, for this feature request there would be a lot of details that need to be worked out. Like, do you schedule per-machine or per-group? Who can do scheduling? Can you schedule many time slots? Does anyone need to approve the time slot? etc.

Given that this is a really big feature and I am flooded with new feature requests, it's unlikely I will even touch this anytime soon. If you have developers willing to work on this, I would certainly look at approving a pull request in this area.

As an alternative, you can embed MeshCentral into another web site (It's in the User's guide). So, would could have a scheduling web site that links to MeshCentral remote desktop/terminal/files only at the right time.

**Comment by SomeGuru** [comment]
Based on this requirement it would be allowing a machine to reside as an independant unit assigned to a time slot calendar similar to feel of G-Calendar or Outlook calendar. The object would be suspended in a locked mode to the requestor and then the requestor could do an invite code for his/her duration of usage with the locked asset. This would allow for sharing the overall end to end profile of that platform. 

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
Added with the latest enhancements and resolves needs. Thanks Ylian
