### ISSUE TITLE
MeshCentral v0.9.16 has all new MeshAgents

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/MeshCentral#3080]
Quick note to say that MeshCentral v0.9.16 was published with all new Mesh Agents. So, automatic update will be triggered. The new agent is compiled with OpenSSL 1.1.1l that has [two security fixes](https://www.openssl.org/news/secadv/20210824.txt).

The new agents have some improvements and bug fixes. The most important fix has to do with very large displays of file folders with 20k+ files in them. That would cause the previous agent to crash and restart, the new agent should work.

Thanks to Bryan for all the fixes. New agents are a lot of work to compile and test on all the different Windows/macOS/Linux/BSD platforms.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian,
What is the new agent version?  I just want to make sure I'm seeing them upgrade once I roll up to 0.9.16.  My current agent version (for Windows anyway) looks to be 1035350832 dated Aug 5.

**Comment by PathfinderNetworks** [comment]
Nevermind, I can see them already updating to version 2146746953 dated Aug 30.
Thanks!

**Comment by smartekIT** [comment]
in the list view it shows the new version compile date, while in the details tab of the device still showing the compile date as 5th of august. ok so jumping to the console tab of the device and issue: sysinfo
the result was an empty array like this: {}

refering to agent installed on Win10 x64 which always used to work properly.
nothing changed on the server other than update to 0.9.16

will do further testing for the sake of feedback.

**Comment by KBCACheia** [comment]
Hi, in my system all connection are super fast compared with before. Congratulation.

**Comment by rodrigolzd** [comment]
Small feedback, Just updated my server, agent updates set to automatic and everthing is fine so far, only one agent didnt update automatically, so I did it manually through the console and everything is fine.

**Comment by VINISHVV** [comment]
Upgraded my server today and everything working fine. This time all the 9000+ agents updated quickly as compared with older versions. 

Big thanks to @Ylianst & @krayon007 - For such an unimaginable tool with frequent security upgrades.

**Comment by rapi3** [comment]
For an old Acer laptop x86 32 bit:
Intel® Celeron® CPU 540 @ 1.86GHz
that run Linux Min 14 identified as: Ubuntu 14.04.6 LTS

latest agent that work for this machine it is:
Linux KVM/NoKVM x86-32bit
17:25:56, **Mar 25 2021**

**Comment by rodrigolzd** [comment]
Small Report. 

Installed the latest version after the update on a pc with the free version of AVG antivirus active, the installer and the agent were captured by the antivirus and automatically uploaded to them for threat testing. I was able to continue installing with warnings, but the install was successful and I was able to connect to the desktop This morning the same system had a notification from AVG saying that nothing dangerous was found in the installer and it was safe to open. I did not see any notifications about the installed agent.

Winddows 7 64bit

**Comment by leleb** [comment]
Hi,
I am having continuous periodic disconnection of the web interface every about 30 sec after updating to 0.9.16
log attached
[servererrors.txt](https://github.com/Ylianst/MeshCentral/files/7093299/servererrors.txt)

**Comment by Ylianst** [comment]
@leleb, quick look at the servererrors.txt, it seems like a problem with the "ScriptTask" plugin. I don't support plugins, but I am working on integrating that one into MeshCentral in the future.

**Comment by ryanblenis** [comment]
> Hi,
> I am having continuous periodic disconnection of the web interface every about 30 sec after updating to 0.9.16
> log attached (installed in Ubuntu 20.04)
> [servererrors.txt](https://github.com/Ylianst/MeshCentral/files/7093299/servererrors.txt)

I haven't tried it with the latest 0.9.16 version yet, but I assume you have scripttask installed. Can you restart your MeshCentral instance and see if the problem continues to occur?

**Comment by Ylianst** [comment]
I am going to close this since I just wanted to tell people about the new agents. Everything seemed to have gone well. Do open a new issue for any other topics.
