### ISSUE TITLE
Disconnect with auto lock

### ISSUE THREAD

**Issue by Gheppy** [Ylianst/MeshCentral#3082]
Hi,
I propose another change.
Disconnection with station lock. 
Another button that will automatically disconnect and lock the station

![image](https://user-images.githubusercontent.com/84496256/131479750-6e2831d6-0645-4f19-897f-81ac3924e137.png)

the code that i change and it works is:

**default.handlebars**

// START is start of change
// END end of change

```
.......................................
                           <div id="idx_deskFullBtn2" onclick=deskToggleFull(event)>&nbsp;&#x2716;</div>
                            <input type="button" id="autoconnectbutton1" value="AutoConnect" onclick=autoConnectDesktop(event) onkeypress="return false" onkeydown="return false" style="display:none" />
                            <span id=connectbutton1span><input type=button id=connectbutton1 cmenu="deskConnectButton" value="Connect" onclick=connectDesktop(event,3) onkeypress="return false" onkeydown="return false" disabled="disabled" /></span>
                            <span id=connectbutton1hspan><input type=button id=connectbutton1h value="HW Connect" title="Connect using Intel&reg; AMT hardware KVM" onclick=connectDesktop(event,2) onkeypress="return false" onkeydown="return false" disabled="disabled" /></span>
                            <span id=disconnectbutton1span><input type=button id=disconnectbutton1 value="Disconnect" onclick=connectDesktop(event,0) onkeypress="return false" onkeydown="return false" />
<!-- START -->
														<input type=button id=disconnectbutton3 value="Disconnect with lock" onclick=connectDesktop(event,4) onkeypress="return false" onkeydown="return false" /></span>
<!-- END -->
                            <span id="deskstatus" style="line-height:22px">Disconnected</span><span id="deskmetadata"></span>

........................................
                    desktop.onMetadataChange = function(metadata) { updateMetadata(desktop, 'deskmetadata'); }
                    desktop.m.ImageType = webpSupport?4:1; // Send 4 if WebP is supported, otherwise send 1 for JPEG.
                    desktop.m.CompressionLevel = desktopsettings.quality; // Number from 1 to 100. 50 or less is best.
                    desktop.m.ScalingLevel = desktopsettings.scaling;
                    if (desktopsettings.framerate) { desktop.m.FrameRateTimer = desktopsettings.framerate; }
                    if (desktopsettings.swapmouse) { desktop.m.SwapMouse = desktopsettings.swapmouse; }
                    if (desktopsettings.remotekeymap == true) { desktop.m.remoteKeyMap = desktopsettings.remotekeymap; }
                    desktop.m.onDisplayinfo = deskDisplayInfo;
                    desktop.m.onScreenSizeChange = deskAdjust;
                    desktop.Start(desktopNode._id);
                    desktop.latency.callback = function(ms) { console.log('latency', ms); updateSessionTime(); };
                    desktop.contype = 1;
                } else if (contype == 3) {
                    // Ask for user sessions
                    meshserver.send({ action: 'msg', type: 'userSessions', nodeid: currentNode._id, tag: consent });
                }
            }
// START
			else if (contype == 4){
                // Disconnect with lock and clean up the remote desktop
		desktop.sendCtrlMsg('{"ctrlChannel":"102938","type":"lock"}');
                desktop.Stop();
                webRtcDesktopReset();
                desktopNode = desktop = null;
                if (pluginHandler != null) { pluginHandler.callHook('onDesktopDisconnect'); }
            }
// END
			else {
                // Disconnect and clean up the remote desktop
                desktop.Stop();
                webRtcDesktopReset();
                desktopNode = desktop = null;
                if (pluginHandler != null) { pluginHandler.callHook('onDesktopDisconnect'); }
            }
        }

        function updateMetadata(conn, elementid) {
            var str = '', viewerCount = 0;
            if (conn && (conn.State == 3)) {
                if (conn.metadata && conn.metadata.users) { for (var i in conn.metadata.users) { viewerCount += conn.metadata.users[i]; } }
                if (viewerCount > 1) { str = '<span onclick=showSessionMetadata(1) style=cursor:pointer>' + format(", {0} watching", viewerCount) + '</span>'; }
            }
            QH('deskmetadata', str);
            if ((conn == desktop) && (xxdialogTag == ('sessionMetadata1'))) { showSessionMetadata(1); }
        }
.....................................................
```

**Comment by VINISHVV** [comment]
Hope this will be considered soon.

**Comment by Ylianst** [comment]
Bryan and I are working on it now. It's being implemented differently since I want the agent to lock the desktop if the connection is lost. So, it requires agent state, etc. We are 80% done with it, so should be in next version.

**Comment by Ylianst** [comment]
Ok, this feature is done and will be in MeshCentral v0.9.17. Should be published shortly.

**Comment by Gheppy** [comment]
It works when the computer loses connection,
I also wanted the ability to be active when I press the disconnect button to, that's why I created a second button.

thank you

**Comment by Ylianst** [comment]
This will be in the next version... Let me know if that works.

![MC2-DesktopLockDisconnectContextMenu](https://user-images.githubusercontent.com/1319013/131741578-613f0b24-e12e-4f49-a99d-97f2e469932b.png)

**Comment by krayon007** [comment]
Just a note, session locking currently only works on Windows. But I have a working prototype for Linux, so I'll be adding that soon.

**Comment by Ylianst** [comment]
Bryan is right. I forgot to mention the settings is present on all platforms, but only Windows supports it.

**Comment by Gheppy** [comment]
Linux is different from windows on the desktop side, but I'm glad to hear that there is a chance that it will also appear on linux with desktop.
On linux, from my point of view, it is more useful to be able to have an option just like the ones with "No Terminal" (recently implemented), which are at server level, in which you must enter username and password on the connection with terminal (on the desktop side there is a screen lock ).
On linux, an terminal with root is all you need to break the system, this is the reason why it would be good to ask for at least your password after a connection is initiated, and after pressing the disconnect button to disconnect from the session to so that a new connection to ask ask for your password again, as it is with putty for example

**Comment by Gheppy** [comment]
The new button "Disconnect and Lock" is not working on windows 10, on windows 7 is ok.
The lock button on the bottom right is working.
This is the info on the windows 10
![image](https://user-images.githubusercontent.com/84496256/131809089-3f512062-10d5-431b-a5ed-54ff07c7bdd6.png)

**Comment by hunter-nl** [comment]
It does also not work ("disconnect and lock" button and with "lock on disconnect" setting enabled) when a desktop session is done on a RDP session.

**Comment by Gheppy** [comment]
I update to day and the "Disconnect and Lock" it works on windows 10 to.
thank you

**Comment by krayon007** [comment]
It should work with RDP and Linux now. For Linux I use loginctl so if your distro has that it will work.

**Comment by Gheppy** [comment]
thank you
