### ISSUE TITLE
Auto remove device after configured inactive days

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3089]
@Ylianst
Sorry for creating duplicate task related to #2974

Actually this functionality not working properly. I have tested new agent installation and older agent. But auto removal is not happening.

**Comment by Ylianst** [comment]
Ok, let me check this now :)

**Comment by Ylianst** [comment]
I just made fixes and improved the server console `removeinactivedevices` command to show each device, what the idle time was and expire time. This will be in MeshCentral v0.9.18.

![image](https://user-images.githubusercontent.com/1319013/131787317-f92053b3-d459-428d-a9da-e8e6a0d1e652.png)

**Comment by VINISHVV** [comment]
Thanks @Ylian
Its working fine now. !!!
