### ISSUE TITLE
LDAP users get same login

### ISSUE THREAD

**Issue by sieuwe** [Ylianst/MeshCentral#3091]
Running version 0.9.15, but was also present on the latest stable version.
When 2 of our users log in via LDAP, they both get the same login user/userID.
Only the name update on MeshCentral.
Also updated the LDAP-Auth fork, but issue remains.

**Comment by sieuwe** [comment]
We ended up using "ldapUserKey": "sAMAccountName", to fix this issue and removed the ldapUserBinaryKey

**Comment by Ylianst** [comment]
Yes! That is exactly correct. You need to use a LDAP unique identifier for creating user accounts in MeshCentral.
