### ISSUE TITLE
MongoDB version update needed to update MC2 to v.0.9.18

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#3092]
Hi,

I updated MC2 from v. 0.8.87 to v.0.9.18 and I had a few problems.

When I start MC2 after the update (npm install meshcentral) a problem occurs while updating of MongoDB to the version 4.1.0. 

![2021-09-02 12_27_41-Window](https://user-images.githubusercontent.com/76168733/131828312-54b8e95a-dbe2-451a-aea7-62b36c9371ab.png)

I figured out that mongodb v.4.1.0 requires nodejs in v. >=12

My MC2 server is installed on Debian 10 and my nodejs version was on 10.24.0 (the latest in the Debian repositories) so I needed to get and install the latest version of nodejs (actually v.16.8.0) from the website in order to install the latest version of mongodb required by MC2.

To start MC2 as well, I had to first delete the folder /opt/meshcentral/node_modules (because the packages was compiled with the old version) then to type the command npm install meshcentral. 
After that everything works as well.

Has anybody got the same situation ?
Did I apply the right proceeding ?

Thanks.

**Comment by Ylianst** [comment]
I now only test MeshCentral on NodeJS v11 and higher. I can't really go lower than that anymore because a lot of dependencies have security fixes that are only available on new versions of NodeJS.

**Comment by elpibedeoro** [comment]
Ok thanks for your replies.
Have a nice day
