### ISSUE TITLE
Unclear where to set two-factor backup codes

### ISSUE THREAD

**Issue by derykl** [Ylianst/MeshCentral#3094]
I have set up two-factor authentication and on every login I get the following alert:

**Two factor authentication: Please add two-factor backup codes. If the current factor is lost, there is no way to recover this account.**

But nothing happens if I click on the message, I can only dismiss it, and it reappears next time.

I can't for the life of me work out where you add these codes (or where you get them from) or how to turn off the nag?  It's not in any documentation I can find.

**Comment by Ylianst** [comment]
You can set the backup codes in the "My Account" tab here:

![image](https://user-images.githubusercontent.com/1319013/131912164-e69b8773-e6fd-4168-9ec1-5b30774457f4.png)

This said, maybe I can look at adding a shortcut in the notification box.

**Comment by derykl** [comment]
I am clearly blind :). Apologies.  Though a link could certainly be of a help to new users.  Thanks!

**Comment by Ylianst** [comment]
Just put in a fix for this. In MeshCentral v0.9.19, when you click on the backup code notification, it will bring you to the backup code dialog box.
