### ISSUE TITLE
Detailed Report for a period- for audit purpose

### ISSUE THREAD

**Issue by Sarathsachu** [Ylianst/MeshCentral#3097]
Hi,

Is there any options to filter the mesh central event reports for audit purpose?

Since the current report contains many unwanted event logs. For audit purpose, we need the user activities for the period. ( User Name,Node Name,Time,Access type ( Files /RDP),Session duration,End time,File transfer size,File Name Etc....)

**Comment by Ylianst** [comment]
This is a good request, it's been asked before and I need to get on this. Would be great to filter events and export the result.

**Comment by soapster** [comment]
+1 Love this idea.

**Comment by VINISHVV** [comment]
+1 Love this idea.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.21 with new report generation capability. Let me know if it works. Some of the past events did not have all the correct data, so reports get better as new events are added.

![MC2-Reports](https://user-images.githubusercontent.com/1319013/132769482-e810301a-cbc7-46c4-b149-fff8d66652b6.png)

**Comment by soapster** [comment]
This looks amazing!

**Comment by VINISHVV** [comment]
Looks nice.....
Thanks @Ylianst

**Comment by Sarathsachu** [comment]
@Ylianst 
Big thanks. seems it's working perfectly.

**Comment by Ylianst** [comment]
Upcoming version of MeshCentral as initial work on adding traffic in/out accounting to the report. Also added Web-SSH, Web-SFTP, Web-RDP sessions in the report.

![image](https://user-images.githubusercontent.com/1319013/132931012-90aa72f5-d5d2-44f1-b69e-a70f0600e854.png)
