### ISSUE TITLE
Self Update Failed because this agent is not an instance of (Mesh Agent)

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3099]
Hi,

I am getting below mentioned popup in mesh portal for few end points. Any possible reason for this? Please mention if any more information needed to check this further.

![image](https://user-images.githubusercontent.com/10217409/132087236-a38694ac-98e5-42a1-97b1-603561f21263.png)

**Comment by VINISHVV** [comment]
Whether mesh agent is installed as service / its used as an interactive mode?

**Comment by knkumar93** [comment]
It is installed as service.

**Comment by VINISHVV** [comment]
Can you try below method once ?. Also let me know the version you are using.

Goto console and run "agentupdate"

**Comment by knkumar93** [comment]
![image](https://user-images.githubusercontent.com/10217409/132087498-f9a89abd-df55-40ae-b56f-96c607de7eb3.png)
This is the output

**Comment by VINISHVV** [comment]
Can you try below method once.

Goto agent console and hit agent action and select clear core.
Once its done desktop and files tab will disappear.
the again hit agent action and upload the default core once.

**Comment by krayon007** [comment]
What OS is that endpoint running? That error happens if the pid of the current process doesn't match the pid reported by the service manager for the service specified.

**Comment by knkumar93** [comment]
Hi @krayon007, End machine is Windows 10 Pro, I have tried the option mentioned by @VINISHVV, but still same problem. I will try to verify if any crash in mesh agent in the end machine (I can see it is showing as MeshCore Recovery mode)

![image](https://user-images.githubusercontent.com/10217409/132089853-f944fa9c-8620-415b-a837-a7bf3d3704be.png)

**Comment by krayon007** [comment]
The meshcore recovery is because the server will use that update path for older agents. For that agent, if you type `versions` in the console tab, what does it say? That way I can look into issues with that specific version. I tried to make the meshcore recovery method compatible with agents that are very old.

**Comment by knkumar93** [comment]
Below is the output for requested output. In end machine no EXE crash found.

> versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-09-03T20:42:44.000Z"
}
> agentupdate
Self Update Failed because this agent is not an instance of (Mesh Agent)

**Comment by krayon007** [comment]
> ![image](https://user-images.githubusercontent.com/10217409/132087498-f9a89abd-df55-40ae-b56f-96c607de7eb3.png)
> This is the output
> Mesh central version used is 0.7.89

Can you try with a more recent server version? There have been several updates to the `agentupdate` mechanism since v.0.7.89.

**Comment by krayon007** [comment]
If you cannot update to a later server, you can at least grab the recoverycore.js file from the agents folder in the latest server repo. If you use that version of recoverycore.js with your server, it should fix the `agentupdate` with your agent.

**Comment by Ylianst** [comment]
I want to mention that if you are upgrading MeshCentral to the current stable (v.0.7.89), make sure that you are NOT running NodeJS v15. If you are, downgrade to an older version of NodeJS of upgrade MeshCentral to the "latest" version instead.

If you are running NodeJS v15, older versions of MeshCentral will not compress the agent correctly and will cause the self-update to fail.

Let us know what version of NodeJS you are using. Thanks.

**Comment by knkumar93** [comment]
Hi,
Unfortunately, the issue was found on our Dev environment, and it got scrapped. After creating fresh setup, the problem hasn't occurred.

We are using Mesh central version v.0.7.89 with NodeJs v.14.17.1

One observation before setup scrap: Initially the agent was installed with service name Mesh Agent, later we have renamed the service, post that only issue observed. When I revert the service name back to Mesh Agent, the self-update warning was gone. Is there any possibility of issue when service renamed?

Thanks for the support. If above info is helpful to fix something, then it is good. Otherwise, this can be closed.

**Comment by krayon007** [comment]
> One observation before setup scrap: Initially the agent was installed with service name Mesh Agent, later we have renamed the service, post that only issue observed. When I revert the service name back to Mesh Agent, the self-update warning was gone. Is there any possibility of issue when service renamed? Any dependency with service name?

How did you rename the service? In the customization, when the agent is installed with a different name, the `meshServiceName` field is defined, so that the agent knows which service name to use.

When the agent is installed, it will normally add  `--meshServiceName="xxxx"` where xxx is the service name, into the ImagePath key for the service entry in the windows registry, such that when the agent is started by the windows service manager, it will launch the agent with the runtime commandline parameter `--meshServiceName="xxxx"`

**Comment by knkumar93** [comment]
Not reproducible further in my environment.
