### ISSUE TITLE
Desktop / Terminal / Files options are missing

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#31]
Hi, I've got similar problem like issue number #13 . I have two  windows 7 64bits sp1 PC´s with the same hardware ( Intel NUC DE3815TYKHE). The Mesh Central server version is 0.2.3-d.
I run meshagent and click on connect, when I click on the computer device in the mesh list, viewing the details of the Windows computer, my menu options in the menu bar at the top of the screen are:
General Events Console
I try remote reset cliking on "Actions" reset but remote PC doesn´t reset.
Here a printscreen of Console tap:
![mesh](https://user-images.githubusercontent.com/45072744/48619421-b96e8c80-e99c-11e8-88fa-dc4855aef703.jpg)

**Comment by jsastriawan** [comment]
It seems MeshAgent could not send capabilities back to server. There are several potential cause here. However my primary suspect is smbios table module. Some improperly filled SMBIOS table may return garbage or not returning readable string thus any string utilities will fail.

I recall the modules were fixed few weeks ago so I will do my best to replicate the issue and come back with some work around while Ylian is off on holiday.

Joko

**Comment by Ylianst** [comment]
This is not good, "MeshCore.js" is likely throwing an exception when loading. I am traveling now, but when I get back I will add code to work around exceptions like this so that at least we get partial functionality. I am back on the November 23rd.

**Comment by Ylianst** [comment]
Ok! I just published MeshCentral v0.2.3-e with a fix for this. Sometimes SMBios tables would not load and cause problems, but a bigger problem was a race condition that caused the server to not handle the device capabilities right. Should work now.

**Comment by edorbike** [comment]
Yes, it works perfect.
