### ISSUE TITLE
meshminirouter.exe certificate has been revoked

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#310]
I was testing the feature of ClickOnce RDP, however when the file is downloaded it fails to run as the certificate has been revoked, which was used to sign the meshminirouter.exe

<img width="306" alt="Capture" src="https://user-images.githubusercontent.com/51713320/59776161-3f8fe000-92aa-11e9-9580-fae6611c65ba.PNG">

**Comment by Ylianst** [comment]
Ha! Thanks for the report, I forgot about that one. It will be self-signed in the next version of MeshCentral I publish.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.6-s with MeshMiniRouter new self-signed. At some point if I get my real certificate back, I will put back proper signing.

**Comment by vish84** [comment]
Confirmed this is now working. Thanks Ylianst.
