### ISSUE TITLE
Push Agent across Lan network

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3101]
Dear Ylian,

Is it possible to push agent installation from one computer to entire systems connected in the same LAN?

Suppose If an agent is installed in particular LAN and we have approximate 100 systems with in same network. is it possible to bulk push same agent to all the 100 systems.

Few software like "Total Network for Employee Monitoring" having such facility to push agent remotely

**Comment by jsastriawan** [comment]
Have you look at batch psexec?

**Comment by VINISHVV** [comment]
> Have you look at batch psexec?

I have not tried. Is it possible through psexec?

**Comment by MordyT** [comment]
`psexec @%textfileofPCnames% \\server\share\meshagent.exe -fullinstall`

`invoke-command machine1,machine2 -ScriptBlock meshagent.exe -fullinstall} -Credential $Admin`
