### ISSUE TITLE
Desktop mode freezes if MeshAgent running in temporary mode.

### ISSUE THREAD

**Issue by tersion** [Ylianst/MeshCentral#3104]
As I wrote some time before (issue #2917), problem that Desktop mode is freezes or visual artifacts is appears, still bother me in latest 0.9.19 version of MeshCentral. As I wrote earlier, this problem occurs only if MeshAgent run in temporary application mode. I make little more investigation, and captured two videos, where I show what is going with agent data in WebSocket. It's just stop coming, if you don't hit "Refresh the desktop" icon. But still - it's help for some little time.
Here the links to videos:
1. First, MeshAgent run in temporary app mode, then in service mode: https://drive.google.com/file/d/1YZ6EgwBrRTGqIFmZviEQP7VoDIGCDW88/view?usp=sharing
2. Here MeshAgent runs only in service mode for a more long time, to show that in this mode no problems: https://drive.google.com/file/d/1gELTBUY9TxEUrY2B9ZGMuq0q_J6lCw4F/view?usp=sharing

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
