### ISSUE TITLE
Search through meshctrl.js

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3109]
Good afternoon.
I want to use meshctrl.js to search for devices by conditions. Specifically, I would like to get the device ID that has a certain line in the description. I have studied the documentation for meshctrl.js, but unfortunately I did not understand how to do it. I can get the details of a device by its ID.
But is it possible to search for a device by its parameters? Just as it does a search in the web interface using the "desc:" key.

**Comment by Ylianst** [comment]
Added advanced filtering to "ListDevices" in MeshCtrl. You can use the same string you use on the website. This will be in MeshCentral v0.9.20. Once published, let me know if it works.

![MC2-MeshCtrlListDeviceFilter](https://user-images.githubusercontent.com/1319013/132407258-a5294589-3e81-48f9-a0ea-5724a50dbeb2.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.20 was published.

**Comment by AntonAndreevichMoroz** [comment]
Thank you so much for the quick solution. It really works the way we wanted it to.
