### ISSUE TITLE
mescript

### ISSUE THREAD

**Issue by lenimon1483** [Ylianst/MeshCentral#311]
Hello - Does mesh commander have any sample script repository’s that I can use? I am new to using MC and will mainly use it give remote support and power actions to image computers.
I require a .mescript that will power on computers into a network boot for PXE. If I use the script editor it does not give me the option for boot to PXE. Network boot is the first option in the bios but the current script bypasses this. I know I can connect to each AMT and select Power action - power on to pxe but I need to do this on 50 computers at a time so a script would be very useful if anybody can help?

Thanks

**Comment by Ylianst** [comment]
Ha yes, the .mescript files are created in MeshCommander using the script editor tab. There are script blocks you can drag & drop and set to create your script. However, it's not super advanced and I have not spent much time enhancing it. Probably the next thing I really need to do is add Intel AMT power action commands to MeshCMD.

MeshCMD is a cross-platform tool that can do a bunch of Intel AMT operations (including IDER that I just added a few weeks back). If I did add power actions commands to MeshCMD, would that fix your request?

I wish I had more time to do more with mescript's, but I am crazy busy already. Another options is to use the Intel AMT PowerShell module, but I have never used it myself.

**Comment by lenimon1483** [comment]
Hi Ylianst,
Thank you for the reply
I've not used MeshCMD yet but from what I have just read it looks like a good tool for what I need to do. If you could add the power actions that would be great. I assume I can run a script in MeshCMD that will do multiple computers?
Thanks again :)

**Comment by Ylianst** [comment]
Hi. I just added "AMTPOWER" action a few days ago to MeshCMD and will be adding more in the coming week. The mescript's are difficult to work with and so, I rather just add feature to MeshCMD for batching since it's much easier.

**Comment by Ylianst** [comment]
FYI. I am going to close this issue. If you want, open a new issue and specifically ask for Intel AMT features against MeshCMD and I will work on that.

**Comment by garciajoaopaulo** [comment]
Hello Guys, i need turn on múltiple devices using mesh Commander. Do you know some script for this?
