### ISSUE TITLE
Mesh Central - Sort by Group Tags

### ISSUE THREAD

**Issue by KSJakobsen** [Ylianst/MeshCentral#3110]
This is maybe not an Issue but rather a question. One of my colleagues has not all the rights that an administrator does. And he wanted to sort the devices by Group Tags and all the devices were gone from his layout and he couldn't change back to any other type of sortation.

Is there a special right that you need to have to sort by Group Tags? 

Kind Regards
Kai - Stephan Jakobsen

**Comment by Ylianst** [comment]
Hi. If you don't see anything when selecting "Group-Tags" in the sort box, it's likely there is an error happening in the browser console. Open the browser console and let us know what error you see, I will try to fix that right away.

![image](https://user-images.githubusercontent.com/1319013/132547312-ab3b98ba-f473-4e63-b2cf-547365efbf43.png)

**Comment by KSJakobsen** [comment]
Hi,

![image](https://user-images.githubusercontent.com/44235327/132805258-84f14751-2da8-4124-9085-80d7dd4217ba.png)

**Comment by si458** [comment]
seems fixed in latest release
