### ISSUE TITLE
Keyboard not working properly on remote VirtualBox VM via remote windows 10 desktop 

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3112]
Accessing via agent a windows 10 pc and running a windows server 2019 eval on virtualbox causes the keyboard input on the VM to go crazy and I could not type in the password.

The pc is fine, I use it all the time, just when trying to access the VM that the keyboard input failed.

Not sure what other information about the setup might be helpful right now, so I'll post what I think it will help 

PC windows 10 21H1 64bit (Brazilian Portuguese)
Virtualbox 6.1.25.r145957 (Latest)
VM running windows 2019 Server Enterprise evaluation with virtualbox guest additions installed, also in Brazilian Portuguese, no internet on it, running as internal network (testing and learning windows server 2019 with dhcp and other configs that would conflict with my home network. )
Mesh is online, only agents, latest version (0.9.19) 
accessing mesh from a windows 10 desktop

I honestly considered this low priority at first and only posted after testing this same setup with anydesk on the same computer and it worked just fine. However, this might not be just a test setup of a VM for someone else.

**Comment by krayon007** [comment]
I vaguely remember seeing this issue before, I might have to search in history... But I remember this problem was specific to VirtualBox and how it was abstracting the keyboard. I was never able to reproduce this issue on VMWare, and I have a few different Brazilian Portuguese Windows VMs. I may have to setup a VM using VirtualBox instead of VMWare to see if I can figure out what is going on.

**Comment by Scaff31** [comment]
Have you tried this

![image](https://user-images.githubusercontent.com/16442430/132477439-3f3cd771-19cf-46b3-90ba-1f9b1669f011.png)

**Comment by Ylianst** [comment]
Yes, trying this is a good idea:

![image](https://user-images.githubusercontent.com/1319013/132546841-41275a4f-6f18-4793-a1d3-75216146399b.png)

Also, I know some applications like Microsoft Edge have a weird way to capture keys. Maybe it's for security, but they do not accept key input from the agent.

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and use node 18 or above,
if your issue persists, please reply back
