### ISSUE TITLE
Meshcentral Assistant hangs

### ISSUE THREAD

**Issue by Bintelons** [Ylianst/MeshCentral#3113]
The latest Meshcentral assistant application is pretty powerful while compare with message features.
But while updating my server to the latest one I found that the Assistant application is not responding properly. It's taking more time to respond also sometimes the system gets hangs.

I am using aws ec 2 linux server.
Meshcentral version - 0.9.20

**Comment by pggsadmin** [comment]
Duplicate of #3072, #3018,  #2961 etc
Hope this will fix soon

**Comment by Ylianst** [comment]
Hopefully I just fixed this MeshCentral v0.9.45. #3212
