### ISSUE TITLE
using logintoken from loginTokenKey in meshctrl.js

### ISSUE THREAD

**Issue by OvrAp3x** [Ylianst/MeshCentral#3115]
I'm trying to use a logintoken generated via loginTokenKey and this script https://info.meshcentral.com/downloads/MeshCentral2/meshgentoken.js 

When using it with ?login=generatedkey in the browser it works as expected, but using it on meshctrl and --loginkey it does not work.
The naming here is a bit confusing for me, I'm guessing i'm doing somthing wrong or misunderstanding something.
I am aware of the "login token" that you can create via the gui aswell, but ideally this should all be created using loginTokenKey  so that it can all be automated.

My goal is to have a system where my webserver can create tokens on behalf of my users.
The users can then push buttons in my webgui and perform quickactions on the computers using the runcommand feature in meshtrl.js

Is this maybe a missing feature, or is there some reason why this not should not be done this way? any tips welcome!

**Comment by Ylianst** [comment]
Your usage is exactly correct and your right, I have next correctly handled this case. I just put in a fix for this, it will be in MeshCentral v0.9.23. You should be able to do this:

```
node meshcentral --logintoken user//admin
```

That will return a login cookie, or you can use the [cookie encoding code here](https://info.meshcentral.com/downloads/MeshCentral2/meshgentoken.js). In that case you run:

```
node meshcentral --logintokenkey
```

Take that key and use it in the cookie encoder code.

Then, you can login using ?login=<cookie> or using MeshCtrl.js:

```
node meshctrl.js listdevices --url wss://myserver.com --loginkey <cookie>
```

Once v0.9.23 is published, let me know if it works.

**Comment by OvrAp3x** [comment]
Great !
Will do once the version is released :-)

**Comment by Ylianst** [comment]
MeshCentral v0.9.23 is now out!
