### ISSUE TITLE
MeshMessenger does not work

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#3118]
the chat is not working, when trying to start, the message waiting for the user appears, followed by the connection terminated message.

![image](https://user-images.githubusercontent.com/18504593/132878207-13b5e651-32d6-4099-bfc9-9ad41f0fd3c0.png)

**Comment by krayon007** [comment]
What browser are you using? Which OS is the browser running on? What OS is the agent running on?

**Comment by Ylianst** [comment]
Oh, I see the same problem. Working on it!

**Comment by Ylianst** [comment]
Fixed. Will be in MeshCentral v0.9.23 when published a bit later today.

**Comment by fernandogobah** [comment]
> What browser are you using? Which OS is the browser running on? What OS is the agent running on?

Web Browser (Agent): Firefox - Chrome - Edge
OS (Agent): Windows 10 - Windows 2019
Web Browser (Support): Firefox
OS (Support): Linux Debian

**Comment by Ylianst** [comment]
No need for further information. Will be fixed in next version :)

**Comment by Ylianst** [comment]
MeshCentral v0.9.23 is now out!

**Comment by fernandogobah** [comment]
It`s working
