### ISSUE TITLE
Plugin not working in latest version of meshcentral

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3120]
@Ylianst
Latest version of meshcentral not support the plugin feature because of some recent mongodb related changes.
Can you do the needful enable the same feature in latest version of meshccentral.

We are able to use plugins while changing db from mongodb to nedb.

**Comment by Ylianst** [comment]
Your report is not very specific. What version are you talking about? What is the problem? How are you changing database. It's not clear at all what needs to be fixed.

In general, I don't do any testing to plug-ins. In yesterday's version, I did add one more function in the database code to handle doing reports. however, I can't imagine that caused any issue.

If you want to re-file a new issue and be more specific as to the problem, that would be great.
