### ISSUE TITLE
Issue with Google Drive Backup - googleapis missing

### ISSUE THREAD

**Issue by sharpec** [Ylianst/MeshCentral#3121]
I have configure Gogole Drive Backup at 2021-01-31.

After a check i have found latest backup on 2021-06-04. If manually launch autobackup system crash (attach a video)

Check log and i found this (attached)

Backup is missing on Google folder.

Now i run in /opt/meshcentral/node_modules this command
and fix it 

> npm install googleapis@39 --save

[server_error.log](https://github.com/Ylianst/MeshCentral/files/7148349/server_error.log)

![Schermata 2021-09-11 alle 20 39 32](https://user-images.githubusercontent.com/5232619/132958074-2e62fccb-716b-4a09-9c92-ab325160b3d2.png)

https://user-images.githubusercontent.com/5232619/132958075-10dc5150-d5fe-408b-9005-44fd74a43e48.mov

**Comment by si458** [comment]
should be fixed now, closing old issue
