### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#3123]
I understand that using powershell/cmd, updating windows is possible so that there is no need to connect through desktop, however it would be nice if there is a one click by the mouse to send the windows updates or, driver installation/updates to the PC. Basically the administrator can do things in the background without the knowledge of the user of the pc.

**Comment by baclaeys** [comment]
I think that’s a great idea.  Perhaps that can be expanded to include other software installations or configuration changes that can be done through powershell/cmd.

**Comment by Ylianst** [comment]
Good idea. If you have more details on how this would be done, like... do you drag & drop a .MSI file on the remote machine? Also, the title "Feature Request" is not appropriate. Please put a descriptive title. I will close this issue, feel free to re-open with proper title and more details. Thanks!
