### ISSUE TITLE
Mongodb restore

### ISSUE THREAD

**Issue by pggsadmin** [Ylianst/MeshCentral#3124]
Hi,
I am planing to migrate my server. I am stuck with restore mongodb. Since the autobackup db extension is archive its not restore through mongo restore.
Can you help how to resolve this?

**Comment by Ylianst** [comment]
Hold on, looking up the command line now...

**Comment by Ylianst** [comment]
Should look like this:

```
mongorestore --archive=mongodump-2021-09-10-16-43.archive
```

**Comment by pggsadmin** [comment]
Thanks @Ylianst
Its working fine.
