### ISSUE TITLE
Has AmtLoadWebApp been deprecated?

### ISSUE THREAD

**Issue by woneill** [Ylianst/MeshCentral#3125]
I found https://www.meshcommander.com/meshcommander/firmware and thought it would be useful for having the KVM viewer and Serial-over-LAN terminal built in to the management web page. But since I don't have a windows machine to use it, I thought I would be able to use `meshcmd AmtLoadWebApp` from a linux host instead.

The version I'm using reports as `MeshCentral Command (MeshCmd)  v0.9.24` but `AmtLoadWebApp` doesn't appear to be a valid option anymore. It looks like it was removed in https://github.com/Ylianst/MeshCentral/commit/a2aca03406b655403821a3fe148f6d7e152383a8.

Is it no longer possible to load meshcommander into web storage?

**Comment by Ylianst** [comment]
Your right, I removed this feature. MeshCommander was designed to fit in the Intel AMT firmware, but that required work to maintain and with MeshCentral taking up a lot of my time, I did not have much time to dedicate to this effort. Additionally, If you look at the [Intel AMT Reference Guide here](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm), Intel announced "Deprecation of Web UI" in Intel AMT. I am holding off to see what they will offer as a replacement if anything.

**Comment by woneill** [comment]
Thanks for the background info!

I've tested both MeshCommander and MeshCentral (which are much appreciated BTW!) and was interested in the firmware approach since these are for my homelab. I'll continue using the non-firmware based approaches.

Thanks again for this work!
