### ISSUE TITLE
Error message : "MeshCentral SSH support requires NodeJS 11 or higher."

### ISSUE THREAD

**Issue by Scaff31** [Ylianst/MeshCentral#3126]
Linux Ubuntu 20.04 full update/upgrade
Meshcentral server version : 0.9.25

On My server tab i've this error:

![image](https://user-images.githubusercontent.com/16442430/133037647-6f924816-db2d-402c-9d3d-ff184ff838e9.png)

when i look on server console:
![image](https://user-images.githubusercontent.com/16442430/133037719-2d32f8a0-bf58-43a7-8168-41d55d233ab3.png)

but on my server

![image](https://user-images.githubusercontent.com/16442430/133037827-5fd45b39-5dc3-4564-bec9-672c6c2706c9.png)

Any idea why the version on meshserver was not the same as linux server ?

**Comment by lixxdee** [comment]
You have two versions of JSnode installed on your system. Your MeshCentral is using the old version. Just enter command "sudo whereis node" and edit your Unit file

**Comment by lixxdee** [comment]
![234234234234234](https://user-images.githubusercontent.com/48026553/133056783-5bf74393-6df9-4c9d-8a5d-11ec799d84f4.png)

**Comment by Scaff31** [comment]
@lixxdee thanks for respond

What is Unit file for you ?

i've only one 
![image](https://user-images.githubusercontent.com/16442430/133056716-1c3278c4-e9ae-4691-a69a-2eb5cc9266c5.png)

**Comment by lixxdee** [comment]
If you updated the JS node via NVM, your new version has a path to root. Run the command 'whereis node' as root

**Comment by Scaff31** [comment]
I don't use nvm for update
i use `sudo n stable`

**Comment by lixxdee** [comment]
Run the command 'whereis node' as root and send screen

**Comment by Scaff31** [comment]
same result from previous screen

**Comment by lixxdee** [comment]
go to "/etc/systemd/system" and search or make unit file "meshcentral.service" with 

`[Unit]
Description=MeshCentral Server

[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/puth for you node/ /puth for you meshcentral/
WorkingDirectory=/home/user
Environment=NODE_ENV=production
User=user
Group=user
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service

[Install]
WantedBy=multi-user.target
`

**Comment by Scaff31** [comment]
it's already set

![image](https://user-images.githubusercontent.com/16442430/133059202-f4a3a736-5635-4ecb-ac9c-94b718b9c3e8.png)

**Comment by lixxdee** [comment]
Try change puth for node "/usr/local/bin/node" but I suppose you have a defective version of the JS node

**Comment by lixxdee** [comment]
Update you JS with NVM [https://www.whitesourcesoftware.com/free-developer-tools/blog/update-node-js/](url)

**Comment by Scaff31** [comment]
Ok thanks with /usr/local/bin/node 

![image](https://user-images.githubusercontent.com/16442430/133060787-58b16766-32a9-48ca-b85c-843619d8c114.png)

**Comment by lixxdee** [comment]
good!)
