### ISSUE TITLE
Session Recording for selected user Groups

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3127]
Dear Ylian,

Can you implement a session recording feature for user-selected groups?

**Comment by Ylianst** [comment]
You guys are so demanding :) I am working on it now.

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v0.9.26. Let me know if it works.

![MC2-UserGroupSessionRecording](https://user-images.githubusercontent.com/1319013/133177434-2c0bc5eb-0783-44b8-b217-145eefe844a9.png)

**Comment by VINISHVV** [comment]
Thanks Ylian,
