### ISSUE TITLE
Need more space for better views

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3128]
It would be nice if there was moe space at the report section, now time and date are at 2 lines instead off 1
![space needed](https://user-images.githubusercontent.com/58996467/133103198-7486abca-500c-4ee2-8bd5-3d5d71be17ba.jpg)

**Comment by Ylianst** [comment]
Thanks for reporting this. It does this in Chrome but not FireFox. I did not expect the "-" to be a breakable character. Working on a fix now.

**Comment by Ylianst** [comment]
Ok, fix will be in MeshCentral v0.9.26.

**Comment by petervanv** [comment]
Confirmed fix thx Ylianst
