### ISSUE TITLE
meshcentral's agent not working on debian 7

### ISSUE THREAD

**Issue by bra00424** [Ylianst/MeshCentral#313]
When install meshcentral's agent on raspian 7 , the agent will not run because of following error:

./meshagent_armhf: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by ./meshagent_armhf)

It works great for raspian 8. Here is a link to the raspian image I am using for 7

https://downloads.raspberrypi.org/raspbian/archive/2015-02-02-01:50/

Also meshagent-linaro runs but on my raspian 7 box but it does not allow remote desktop only ssh connection

**Comment by Ylianst** [comment]
Thanks for the report. I will format one of my Raspberry Pi's with the older Raspian 7 and compile the agent on it in the next few days. That agent will probably work on Raspian 7 & 8 and so, that will be the new release.

**Comment by Ylianst** [comment]
According to the [Wikipedia entry on Raspbian](https://en.wikipedia.org/wiki/Raspbian), the version released on 2015-02-02, can only run on the Raspberry Pi 1 and 2, so I got my really old Pi out of storage and got it formatted. I am compiling on it now, it's crazy slow and I am not going to compile remote desktop support for now, but I should be able to make it work.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.6-t with a new Raspian 7 MeshAgent. When installing, your going to have to cut & paste the install command and add " 27" at the end. Like this:

`
(wget https://alt.meshcentral.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh || wget https://alt.meshcentral.com/meshagents?script=1 --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://alt.meshcentral.com 'xxxxxxxxxxxxxxxxxxxxxxxx' 27
`

The 27 at the end will override the auto-detection of the script and force the agent type 27 to be used. This agent does not have remote desktop support, but should work otherwise. I did a bit of work to look at desktop support and I can't get the older X11 libraries I need to compile it.

Hope it helps,
Ylian

**Comment by bra00424** [comment]
Thanks Ylian for working on this! I’ll give it a shot when get chance. (On vacation until next week) I was hoping to have remote desktop support for our use case here at GEL but it sounds like the older X11 libraries being unavailable. On a separate note  I was planning into adding some code to MeshCentral.js to watch a folder  and pick up client destined actions (in the form of json files) so that I can have a little better scripting control of the system. I know at some point you were planning on adding batch level scripting but I figured in the mean time this might be a hack that could get me by. 
Best Regards,
Brad

**Comment by Ylianst** [comment]
Hi. Let me know if the new agent works for you when you can. Bryan gave me some hint as to how I could make the remote desktop work even on an old built, but I will only give that a try if this agent works.

As for batching / scripting, if you can contribute something in this space, that would be much appreciated. I am pretty much packed with work as it is.

**Comment by bra00424** [comment]
Hi Ylian,
  I will test it out soon. Been on vacay and not had a chance. Get back on Monday so hoping to test then.
Thanks! ,
Brad

**Comment by bra00424** [comment]
Hey Ylian,

    Sorry it took me some time to get to this. I tested the new Raspian 7 Meshagent you built using agent type 27 and it is working although had to make a few modifications.
wget was giving me errors GnuTLS: A TLS fatal alert has been received so modified meshinstall.sh to use curl if wget gives errors. Also the startup type determination was failing because /sbin/init —version was giving error for raspberry 7. (The flag —version not valid for /sbin/init in this version). So modified meshinstall.sh to check that before returning startup type. With those 2 changes, it appears to work! I”ve attached snapshots below. Let me know if get chance to look at remote desktop support for this.  

Thanks,
Brad

**Comment by MailYouLater** [comment]
@bra00424: Supporting `curl` in cases where `wget` isn't available, or doesn't work sounds like a decent improvement. Perhaps you should post your changes so they can be incorporated for others to use.

**Comment by bra00424** [comment]
@Ylianst Not too familiar with github. Let me know if by posting changes you mean something else other than attaching the meshinstall.sh script with the changes below.
[meshinstall.sh.txt](https://github.com/Ylianst/MeshCentral/files/3357231/meshinstall.sh.txt)

**Comment by bra00424** [comment]
Sorry above should be directed to @MailYouLater

**Comment by MailYouLater** [comment]
@bra00424: I was actually thinking a pull request would be good, but short of that, a diff is good.
If I'm not mistaken the `meshinstall.sh.txt` you uploaded is edited from the `meshinstall-linux.sh` file located in the `agents` folder of this repo, so I `diff`ed the two.

I understand the addition of the ` || curl …` parts, but can you possibly explain your other changes?

> diff-U3 [agents/meshinstall-linux.sh](https://github.com/Ylianst/MeshCentral/blob/e23718a859ef9d1e6e144c8c1056565e8fb67846/agents/meshinstall-linux.sh) [meshinstall.sh.txt](https://github.com/Ylianst/MeshCentral/files/3357231/meshinstall.sh.txt)
> ```diff
> --- agents/meshinstall-linux.sh
> +++ meshinstall.sh.txt
> @@ -8,14 +8,19 @@
>    elif [[ $starttype == 'init' ]];
>        then
>           # Upstart
> -         if [[ `/sbin/init --version` =~ upstart ]]; then return 2;
> -         # Sysv-init
> -         return 3;
> -      fi
> +         /sbin/init --version  && [[ `/sbin/init --version` =~ upstart ]] && return 2 || return 3
> +  #       if [[ `/sbin/init --version` =~ upstart ]]; then return 2;
> +  #        Sysv-init
> +  #       return 3;
> +  #    fi
> +
> +
>    fi
>    return 0;
>  }
>  
> +
> +
>  # Add "StartupType=(type)" to .msh file
>  UpdateMshFile() {
>    # Remove all lines that start with "StartupType="
> @@ -97,13 +102,15 @@
>    mkdir -p /usr/local/mesh
>    cd /usr/local/mesh
>    echo "Downloading Mesh agent #$machineid..."
> -  wget $url/meshagents?id=$machineid --no-check-certificate {{{noproxy}}}-O /usr/local/mesh/meshagent
> +  wget $url/meshagents?id=$machineid --no-check-certificate -O /usr/local/mesh/meshagent || curl -L -k --output /usr/local/mesh/meshagent  $url/meshagents?id=$machineid
>  
>    # If it did not work, try again using http
>    if [ $? != 0 ]
>    then
>      url=${url/"https://"/"http://"}
> -    wget $url/meshagents?id=$machineid {{{noproxy}}}-O /usr/local/mesh/meshagent
> +    wget $url/meshagents?id=$machineid -O /usr/local/mesh/meshagent  || curl --output /usr/local/mesh/meshagent $url/meshagents?id=$machineid
> +
> +
>    fi
>  
>    if [ $? -eq 0 ]
> @@ -111,12 +118,12 @@
>      echo "Mesh agent downloaded."
>      # TODO: We could check the meshagent sha256 hash, but best to authenticate the server.
>      chmod 755 /usr/local/mesh/meshagent
> -    wget $url/meshsettings?id=$meshid --no-check-certificate {{{noproxy}}}-O /usr/local/mesh/meshagent.msh
> +    wget $url/meshsettings?id=$meshid --no-check-certificate -O /usr/local/mesh/meshagent.msh || curl -L -k --output /usr/local/mesh/meshagent.msh $url/meshsettings?id=$meshid
>  
>      # If it did not work, try again using http
>      if [ $? -ne 0 ]
>      then
> -      wget $url/meshsettings?id=$meshid {{{noproxy}}}-O /usr/local/mesh/meshagent.msh
> +      wget $url/meshsettings?id=$meshid -O /usr/local/mesh/meshagent.msh || curl --output /usr/local/mesh/meshagent.msh $url/meshsettings?id=$meshid
>      fi
>  
>      if [ $? -eq 0 ]
> @@ -145,7 +152,7 @@
>        elif [ $starttype -eq 3 ]
>            then
>            # initd
> -          wget $url/meshagents?script=2 --no-check-certificate {{{noproxy}}}-O /etc/init.d/meshagent
> +          wget $url/meshagents?script=2 --no-check-certificate -O /etc/init.d/meshagent || curl -k -L --output /etc/init.d/meshagent $url/meshagents?script=2
>            chmod +x /etc/init.d/meshagent
>            # creates symlinks for rc.d
>            update-rc.d meshagent defaults
> @@ -246,4 +253,4 @@
>    fi
>  else
>    echo "Must be root to install or uninstall mesh agent."
> -fi
> \ No newline at end of file
> +fi
> ```

**Comment by Ylianst** [comment]
Next time I get a chance, I will take a look at this. Bryan will probably need to review the chances as we don't want to break the existing users.

**Comment by bra00424** [comment]
@MailYouLater 
   Sorry for delay, On our raspian 7 pis, the /sbin/init --version gives error as shown below:
root@raspberrypi:~# cat /etc/issue
Raspbian GNU/Linux 7 \n \l

root@raspberrypi:~# /sbin/init --version
/sbin/init: invalid option -- '-'
Usage: init {-e VAR[=VAL] | [-t SECONDS] {0|1|2|3|4|5|6|S|s|Q|q|A|a|B|b|C|c|U|u}}


So I tried 
/sbin/init --version  && [[ `/sbin/init --version` =~ upstart ]] && return 2 || return 3

Which I think returns 2 if /sbin/init --version is a valid command and returns something like upstart and otherwise returns 3 .

Thx,Brad

**Comment by MailYouLater** [comment]
@bra00424: OK, and why remove the `{{{noproxy}}}` parts of the `wget` portion of the download lines?

**Comment by bra00424** [comment]
@MailYouLater :  Oh sorry, that should not be removed, meant to just have that line the same except for the || and what follows.

**Comment by MailYouLater** [comment]
@Ylianst: When you review this, it may also be a good idea to only include the `--no-check-certificate` option for `wget`, and `-k` option for `curl` _only_ when the server doesn't have a valid certificate.

**Comment by Ylianst** [comment]
Ok! Thanks. Working on this now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.7-n with the new install script that uses wget and curl. As suggested by @MailYouLater, the certificate check is removed only if the server uses an un-trusted certificate. Feedback welcome on this.

**Comment by bra00424** [comment]
Nice will test it out. Not sure if proper way to install but I git clone new repository  and then run node meshcentral.js and when do that get Error "cannot find module ‘./webauthn.js’ “ 
Then I run npm install webauthn and it installs ok.  Our meshcentral server is running Debian GNU/Linux 9. Thanks, Brad

**Comment by bra00424** [comment]
scratch that …i fixed it some other way. Checking now…It still fails after npm install webauthn. I think it was spelling or something.

**Comment by bra00424** [comment]
In the webserver.js I changed require(‘./webauthn.js’) to require(‘./Webauthn.js’) and it works for me.

**Comment by bra00424** [comment]
Sorry one other thing, I installed new server version but when click ‘Add one’ and choose ‘linux’ it only gives wget option and not the curl option fallback that is found in the meshinstall.sh script.
(wget https://mu01.gel.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh || wget https://mu01.gel.com/meshagents?script=1 --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://mu01.gel.com '1kb@1SOXLetSPC8cBatcuGT9C2R0LMHVS2RJOwcvWdjRUKITtNYvV8PvgjTkIx1k'

So when goto raspberry pi linux 7 get the error: 


GnuTLS: A TLS fatal alert has been received.
Unable to establish SSL connection.

**Comment by Ylianst** [comment]
I just fixed the "webauthn.js" filename on Github. Should have been all lower case. Thanks!

**Comment by Ylianst** [comment]
@bra00424 So, the line:

`(wget https://mu01.gel.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh || wget https://mu01.gel.com/meshagents?script=1 --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://mu01.gel.com '1kb@1SOXLetSPC8cBatcuGT9C2R0LMHVS2RJOwcvWdjRUKITtNYvV8PvgjTkIx1k'`

This is for wget with proxy and fallback without proxy. Is that ok? Or you want curl fallback? Or both?

I assume separately, you get this error when running the install script?

```
GnuTLS: A TLS fatal alert has been received.
Unable to establish SSL connection.
```

Does your server use a real TLS certificate? If so, did the install script you downloaded include the "--no-check-certificate" on the wget lines in the install script?
