### ISSUE TITLE
Add device group name to report view

### ISSUE THREAD

**Issue by Scaff31** [Ylianst/MeshCentral#3130]
Hi there,

In the report view, is it possible to have the name of the device group in addition to the name of the devices themselves when no filter is applied?

I have a lot of servers with the same name like SRV-DC / SRV-RDS and it's not easy to determine the group it belongs to

There are indeed filters that allow me to output group by group, but I would like to be able to output a single CSV file to process it later

**Comment by Ylianst** [comment]
Ok, added device group names to reports. Will be in MeshCentral v0.9.27.

![image](https://user-images.githubusercontent.com/1319013/133341726-b0824f3b-2645-4212-9213-8db6e2b68694.png)

**Comment by Scaff31** [comment]
Perfect!

Thanks Ylian
