### ISSUE TITLE
High Malicious activity detected "Post Meshagent" on windows.

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshCentral#3132]
In my local environment my antivirus was detected as below post installation of meshagent.

Description: Wmic attempted to launch a likely malicious payload via an Extensible Stylesheet Language (XSL) file. An adversary can embed a call to execute an arbitrary script from an XSL file, bypassing Windows security features. Review the XSL file and investigate the process tree.
Customer ID: XXYYY
Host name: XXXYYYY
File name: WMIC.exe
File path: \Device\HarddiskVolume4\Windows\SysWOW64\wbem\WMIC.exe

Is anything we are doing with wmic?

**Comment by pggsadmin** [comment]
100%  its not related to meshagent.
You can cross check the same by disabling meshagent service.

**Comment by knkumar93** [comment]
Hi,
We got into similar issue wherein Crowd Strike antivirus detect highly malicious activity with WMIC exe. Below are few snaps.

![image](https://user-images.githubusercontent.com/10217409/133975744-30c14392-2abc-49af-b82b-188eb6fa4be4.png)

![image](https://user-images.githubusercontent.com/10217409/133975619-a07b9a18-7102-4031-97d0-19b5d909c0d5.png)

![image](https://user-images.githubusercontent.com/10217409/133975422-6c2c9fe5-05e0-4757-8a63-dc568eede190.png)

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
closing as agreed, all AV ones will point to a discussion going forward, me thinks
