### ISSUE TITLE
Meshcentral install under Plesk

### ISSUE THREAD

**Issue by frufru99** [Ylianst/MeshCentral#3133]
Hi, I'm thinking about a switch from Screenconnect to Meshcentral, I have a VPS with Plesk wich theoriticaly supports NodeJS but the installation methods described in the docs doesn't work here. Has anyone tried to setup Meshcentral undes Plesk?

**Comment by fernandogobah** [comment]
Yes, i have too one vps plesk. Meshcentral work with plesk, however there may be some difficulties in implementing

**Comment by frufru99** [comment]
How did you manage that?
