### ISSUE TITLE
AutoRemoveInactiveDevices

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#3135]
Hi, I activated the "AutoRemoveInactiveDevices" feature: 37, and restarted the server. When I know them I execute the following command: removeinactivedevices showall the server starts scrolling the list of devices and then disconnects me. (server restart due to critical error)
I disabled the option and repeating the command: removeinactiveddevices showall, it is executed (see list) and the problem does not reappear
I used the same option on another test server with few devices and the problem doesn't show up

I attach error log.
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
[servererrors.txt](https://github.com/Ylianst/MeshCentral/files/7167736/servererrors.txt)

**Comment by paolor1965** [comment]
I did the same test on another backup server with many offline clients and I got the same result

-------- 9/15/2021, 9:36:30 AM ---- 0.9.26 --------

/srv/meshcentral/node_modules/meshcentral/db.js:205
                                                    if (db.changeStream) { event.noact = 1; } // If DB change stream is active, don't use this event to change the user. Another event will come.
                                                           ^

TypeError: Cannot read property 'changeStream' of undefined
    at /srv/meshcentral/node_modules/meshcentral/db.js:205:60
    at /srv/meshcentral/node_modules/meshcentral/db.js:1313:29
    at wrapper (/srv/meshcentral/node_modules/mongodb/lib/utils.js:530:9)
    at next (/srv/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:244:32)
    at cleanupCursor (/srv/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:484:55)
    at wrapper (/srv/meshcentral/node_modules/mongodb/lib/utils.js:530:9)
    at utils_1.maybePromise.done (/srv/meshcentral/node_modules/mongodb/lib/sessions.js:136:24)
    at Object.maybePromise (/srv/meshcentral/node_modules/mongodb/lib/utils.js:516:5)
    at ClientSession.endSession (/srv/meshcentral/node_modules/mongodb/lib/sessions.js:133:24)
    at cleanupCursor (/srv/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:530:32)

**Comment by paolor1965** [comment]
I am attaching versions 
{
    "http_parser": "2.9.4",
    "node": "10.23.1",
    "v8": "6.8.275.32-node.59",
    "uv": "1.34.2",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.15.0",
    "modules": "64",
    "nghttp2": "1.41.0",
    "napi": "7",
    "openssl": "1.1.1g",
    "icu": "64.2",
    "unicode": "12.1",
    "cldr": "35.1",
    "tz": "2019c"

**Comment by Ylianst** [comment]
You are right. Thanks for reporting this. I put in a fix, will be in MeshCentral v0.9.27.

**Comment by paolor1965** [comment]
thanks a lot
paolo

**Comment by Ylianst** [comment]
MeshCentral v0.9.27 is out with this fix.

**Comment by paolor1965** [comment]
I tried the removeinactivedevices command from the console and now the server won't reboot. I wait a day to see if the agents are removed with the custom policy made by the graphics
