### ISSUE TITLE
Tag issue

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#3136]
Hi I don't know from which version but, today I realized that on the latest release (0.9.26) I can insert the tags but when I search for them I can't find anything anymore. Do I need to activate a parameter in the config.json ??
i have the same problem on all servers

**Comment by VINISHVV** [comment]
Try t:<tag> or tag:<string>

In the search box, you cal use:

user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t: xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any

**Comment by paolor1965** [comment]
I did some tests with the different search criteria and they all work correctly except tag (t) and atag (a) for which I encountered this problem: I realized that if I write the tag with some capital letters, it is not found in the search even if the filter corresponds exactly to the text to be searched, if I rewrite the same tag even if it is composed of several words divided by space but lowercase the search filter is successful

**Comment by paolor1965** [comment]
Also if I search for the tag (for example) paolo with t: paolo finds it but if I do a partial search, that is t: pao gives me a result not found. It's correct??

**Comment by VINISHVV** [comment]
> Also if I search for the tag (for example) paolo with t: paolo finds it but if I do a partial search, that is t: pao gives me a result not found. It's correct??

Sorry, I am also getting the same error in the latest version. Tags not working properly.

**Comment by Ylianst** [comment]
Ok, I see the problem. If the tag has a capital letter in it, it will never match. Working on it.

**Comment by Ylianst** [comment]
This bug was probably introduced when I added "and/or" support. Just fixed it and publishing v0.9.27 now.

**Comment by paolor1965** [comment]
Hi it seems to me that the partial search of the tags does not work yet

**Comment by Ylianst** [comment]
Oh, tags are only full match. I can add partial match if you like??

**Comment by paolor1965** [comment]
Yes, thank you, if possible it is very convenient

**Comment by Ylianst** [comment]
MeshCentral v0.9.28 was just published with partial tag matching. Let me know if that works.

**Comment by paolor1965** [comment]
It works perfectly thank you so much.
It is a very convenient function because for each agent I have configured a tag with the name and surname of the PC user.
It is very fast in the search as well
Happy holidays
