### ISSUE TITLE
Assistant hang issues

### ISSUE THREAD

**Issue by Adminvvs** [Ylianst/MeshCentral#3137]
Hi,

Sorry for creating duplicate issues.
Can you helps to resolve the assistant hang issues on priority basis. I am asking this because meshagent service is restarting in every 3minite due to symantec / kaspersky flags so in every 3 minute i need to reconnect the agent pc. I have tried to whitelist the service from last 6month but still its pending from the AV teams. But in the case if assistant there is no blocking from av. We can access the system continuously.

**Comment by Ylianst** [comment]
Arg, I am going on vacation until October 5th. I have not taking a big vacation in over a year, so looking forward to it.

I totally get the request, I have not worked on Assistant for a while and I need to get back to it. I have not personally seen it hang, but I am sure I can find a way to get it to happen.

**Comment by Adminvvs** [comment]
> Arg, I am going on vacation until October 5th. I have not taking a big vacation in over a year, so looking forward to it.
> 
> I totally get the request, I have not worked on Assistant for a while and I need to get back to it. I have not personally seen it hang, but I am sure I can find a way to get it to happen.

@Ylianst
The same issue persist on meshcentral public server also. I think this will be easy to recreate. If possible please look into this after your holidays. Wish you a Happy holiday.

**Comment by Ylianst** [comment]
I imagine I need to use a server that has some network latency and bandwidth limitation to recreate the problem. That is why the server on my developer will never show this problem.

**Comment by Adminvvs** [comment]
> I imagine I need to use a server that has some network latency and bandwidth limitation to recreate the problem. That is why the server on my developer will never show this problem.

I dont think its difficult for reproduce this issue because the same is showing in meshcentral public portal.

**Comment by VINISHVV** [comment]
@Ylianst
Pls help for resolving this issues.

**Comment by Ylianst** [comment]
I think this is solved now in #3212, please test.
