### ISSUE TITLE
Install let'sEncrypt

### ISSUE THREAD

**Issue by aullah360** [Ylianst/MeshCentral#314]
Is anybody can instruct me to install let'sEncript for my Meshcentral Server which is hosted on a Windows 10 PC. Also, it has been pointed to a subdomain.
what is the procedure to get the Let' sEncrypt on my server?

Thanks

**Comment by whalehub** [comment]
Have a look at this ACME client for Windows: https://github.com/PKISharp/win-acme

**Comment by Ylianst** [comment]
MeshCentral has Let's Encrypt support built-in, take a look at Chapter 11 of the [User' Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf). If course, if you are using a reverse proxy (NGNIX, HAProxy...) probably best to have the reverse proxy manage Let's Encrypt.

**Comment by aullah360** [comment]
> MeshCentral has Let's Encrypt support built-in, take a look at Chapter 11 of the [User' Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf). If you are using a reverse proxy (NGNIX, HAProxy...) probably best to have the reverse proxy manage Let's Encrypt.

Hi,
I have added the code as you have suggested replaced my email and subdomain.  
 "letsencrypt": {
 "email": "myemail@myserver.com",
 "names": "sub.domain.com,",
 "rsaKeySize": 3072,
 "production": false
 },

then I have got a "letsencrypt" folder inside Meshcentral-data folder automatically. still, I see the root SSL on my site. I gase I just have to wait. I will keep updating. Thanks
if I have something wrong please let me know

**Comment by aullah360** [comment]
Thanks, It has been fixed. Now my meshcentral server has a valid SSL certificate from Let's Encripts

**Comment by aullah360** [comment]
@Ylianst , Thank you so much for a great piece of work.

**Comment by Ylianst** [comment]
Thanks. MeshCentral will start with the default self-signed certificate and make the Let's Encrypt request. It can take a few minutes but once the certificate is issued, MeshCentral will restart and use the new certificate automatically. It should also automatically re-new the certificate in the future and restart when the new certificate is received.
