### ISSUE TITLE
Branding 'TitlePicture' config not working

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshCentral#3147]
Hey guys,

It's been awhile, which I suppose it good, this project just works, which is awesome! I recently set up a new portal and wanted to customize it a little. I've done this before with the first portal I setup, but it doesn't seem to be working this time.

I've followed the instructions for adding TitlePicture in the config and have it pointed to the png, which I have located in the data directory., but for some reason the logo.png just shows up blank, instead of with the graphic I installed. Any ideas?

-Matt

**Comment by honestlai** [comment]
nvm, I ended up just putting logo.png in as many places as I could find, it ended up working :P

**Comment by theoneandonly-vector** [comment]
"titlePicture": "logo.png",
with logo.png inside meshcentral-data works, but I just use "nothing" because I don't need a logo there..

**Comment by vitko-bg** [comment]
Try with following
  "titlePicture": "something_not_existing. png",

**Comment by theoneandonly-vector** [comment]
@vitko-bg 
> but I just use "nothing"
.png is not needed :)
