### ISSUE TITLE
Feature Request - Alert/Notification on System Up/Down

### ISSUE THREAD

**Issue by mjpcomp** [Ylianst/MeshCentral#3150]
A feature request - If a system goes offline/comes back online, it would be nice to be able to set an alert/e-mail notification...

**Comment by Ylianst** [comment]
It's been asked before, but yes, good request. I am on vacation until October 6th, but will work on that. I want to add email and SMS notifications for this.

**Comment by JonathanReifer** [comment]
While I think built in email and/or sms notification is nice, even better would be just exposing the events (system connect/disconnect, login etc) to a user script would be even better.  That way we can do what we like with it. I for one would love to be able to implement webhook (matrix/slack) notifications.  And if people want full-on alerting (like pagerduty or goalert.me) they could connect there instance of mesh to that.

Awesome work btw!  This is a GREAT project, thanks!
