### ISSUE TITLE
Error when trying to start the service by command line

### ISSUE THREAD

**Issue by antunesn** [Ylianst/MeshCentral#3154]
Hi, when I try to start the service via command line, it throws an error...
Stopping via command line works fine.
Starting and Stopping through the MSC console also works fine.

`PS C:\mc> node node_modules\meshcentral --start
Error: The service "MeshCentral" does not exist or could not be found.
PS C:\mc> node node_modules\meshcentral --restart
MeshCentral service stopped.
Holding 5 seconds...
C:\mc\node_modules\node-windows\lib\daemon.js:672
          throw Error('The service "'+this.name+'" does not exist or could not be found.');
          ^

Error: The service "MeshCentral" does not exist or could not be found.
    at daemon.value [as start] (C:\mc\node_modules\node-windows\lib\daemon.js:672:17)
    at Timeout._onTimeout (C:\mc\node_modules\meshcentral\meshcentral.js:379:220)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)`

**Comment by si458** [comment]
this is because the service hasnt been installed in the backgroun
you can do this by using `node node_modules/meshcentral --install`
and to uninstall use `--uninstall`
