### ISSUE TITLE
Sort by "Users" or "Address"

### ISSUE THREAD

**Issue by PaliPalo** [Ylianst/MeshCentral#3159]
Hello,

It should be nice to be able to sort the devices list, by their connected user or their IP address. In my case, I generally have to help people and need to find them quickly by their name. 

A sort by "Addresse" could also be helpful. In my point of view, I would be able to directly see the region where people are connected to. Indeed some VPN users are using a specific LAN range. Sorting them that way can help me to determine that fact and estimate proper intervention.

I could use the search feature on the browser, though. But I think the sort approach more efficient.

**Comment by si458** [comment]
this isnt possible because for example a WAN setup would show the agent ip as the same ext ip if multiple clients behind the same ip, so how would you sort them?

closing as stale sorry
