### ISSUE TITLE
No agents appear via VPN

### ISSUE THREAD

**Issue by rt050** [Ylianst/MeshCentral#316]
Hi,

Is there something I should be doing with ports via vpn? I've opened any to any from the subnet to the address of Meshcentral and vice versa but the agents aren't appearing at the remote site...

Thanks

**Comment by Ylianst** [comment]
Hi. The MeshAgent is very similar to a browser in that it will connect to port 443 of the MeshCentral server. So, if you can browse to your server, the agent should be able to connect to it.

If you need to configure a proxy in the browser to connect to MeshCentral, you should create a "meshagent.proxy" file next to the mesh agent executable and put in it "proxyserver.domain.com:123" so the MeshAgent makes use of the proxy.

You can also manually run the agent to see what is going on using "meshagent.exe run". You will see where it's trying to connect.

Hope it helps,
Ylian

**Comment by Ylianst** [comment]
Closing this one, please open again if needed.
