### ISSUE TITLE
MeshAgent for Alpine Linux broken after update of MeshCentral

### ISSUE THREAD

**Issue by FelR** [Ylianst/MeshCentral#3162]
After updating MeshCentral from version 0.7.59 to 0.9.28 we lost connection to our Alpine Linux clients.

They have initially been set up using the binary installer and setting the id to 33 as mentioned in #2225
Probably due to auto update the clients downloaded a new agent version from the server, that does not work with Alpine Linux any longer. 

When trying to run the new binary installer manually this error message is thrown:

`Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./meshagent)`

**Comment by krayon007** [comment]
What version of Alpine are you using? I'm using v3.13, and can't reproduce this issue. I even did a force update, to update the agent, and it updated correctly.

**Comment by krayon007** [comment]
Are you able to pull the binary directly off the server, and see if it runs on your Alpine linux? You can run it with the following flag:

`./meshagent -info`

And it should give some basic information...

**Comment by FelR** [comment]
Thank you for your fast reply. As you suggested I tried to copy the binary directly from the server, but to my surprise there was no Alpine binary. It seems that from this commit on (https://github.com/Ylianst/MeshCentral/commit/889381d644288c208d626cd3bb948fe57bfcb5b8#diff-8c70b25cbbbe8e7935bbc70516181551934ae5e917b40d25c4a72bbbd865f2e4) the Alpine binary is missing in the agents directory. I then copied the latest available version from the previous commit to my client and tried to run it, when this error was thrown:

```
/usr/local/mesh_services/meshagent$ sudo ./meshagent
Connecting to: wss://***:443/agent.ashx
2021-09-26 12:32:53 AM: Control Channel Idle Timeout = 120 seconds
Connected.
2021-09-26 12:32:53 AM: MeshCore: Stop
SelfUpdate -> Updating Agent...
SelfUpdate -> Restarting Agent...
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/mesh_services/meshagent/meshagent)
```

**Comment by krayon007** [comment]
For alpine, you should use the binary that says openwrt_x86-64. I updated the toolchains because it wasn't necessary for me to compile on alpine because the openwrt toolchain uses musl just like alpine. So we updated the Arch ID to reflect this.

**Comment by krayon007** [comment]
In your example, after it shows that error, does it say the same error if you run:

`./meshagent -info`

**Comment by FelR** [comment]
I copied the openwrt binary from our server to the client and tried to run it with the info argument. That's the output:

```
/usr/local/mesh_services/meshagent$ sudo cp ~/meshagent_openwrt_x86_64 ./meshagent
/usr/local/mesh_services/meshagent$ sudo chmod +x meshagent
/usr/local/mesh_services/meshagent$ ./meshagent -info
Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./meshagent)
```

In the next step I checked if the libgcc package was installed, that was not the case. So I installed it manually and now the agent is working again:

```
/usr/local/mesh_services/meshagent$ ./meshagent -info
Compiled on: 15:00:13, Aug 30 2021
   Commit Hash: 38d9ddc3f5d47dfce1303aca995236e110d2a784
   Commit Date: 2021-Aug-30 14:58:22-0700
Using OpenSSL 1.1.1l  24 Aug 2021
Agent ARCHID: 36
Detected OS: Alpine Linux v3.14 - x64
```

So it seems to me the dependecies have changed. Maybe it would be wise to check, whether new requirements are fulfilled before automatically updating the agent.
