### ISSUE TITLE
Documentation Update turn into online docs and chat/collaboration

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#3163]
I was trying to look thru and add some server-side session recording. The only info on the topic I could find was a brief Blog release notes: 
https://meshcentral2.blogspot.com/2019/08/meshcentral2-500k-downloads-session.html
and youtube video:
https://www.youtube.com/watch?v=nDkNbYE8fT0 

Trying to check documentation file the only thing I see is from over a year ago from 5/2020
https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

and has no relevant information

-------------

I'm trying to get up to speed and collaborate with others on mesh features, but I feel like I'm poking around in the dark and trying to reinvent the wheel.

Do you have a chatting system that is an official location? Discord(preferred)/Slack/IRC etc. The only thing I see is a reddit forum listed which doesn't seem like an ideal collaboration medium for Open Source Software.

I'd be willing to convert the pdf into a Github repo, and mkdocs convert them so that at least there would be something online that users could collaborate on/update on a more timely basis. Also setup some chat.

Please let me know your thoughts on these 2 topics @Ylianst

**Comment by Ylianst** [comment]
FYI. I am on vacation until October 6th. I will take a look at this when I get back.

**Comment by silversword411** [comment]
I started poking around, it looks like you tested `gh-docs` in oct/2020 but it was a single shot at it and still has default GitHub data in it.

I'll start simple and make a first PR to that to try and improve it. Use this to update it:

https://www.mkdocs.org/user-guide/deploying-your-docs/

The PR should update everything in the appropriate places to make 

And I'll keep going. Thx!

**Comment by jjoelc** [comment]
I'm slightly embarrassed at how little I have added to the site in a while, but [MeshCentral-Community.com](https://meshcentral-community.com) is a wiki which was started with the aim of providing a place for users to post information, instructions, documentation for MeshCentral.

I don't believe there is anything already existing yet about session recording, but would love to invite you to join and add anything you feel would be helpful to others.

**Comment by silversword411** [comment]
> I'm slightly embarrassed at how little I have added to the site in a while, but [MeshCentral-Community.com](https://meshcentral-community.com) is a wiki 

So I didn't even see anything about that. Looking here: https://github.com/Ylianst/MeshCentral
All I see are links to 3 pdf's

Checking meshcentral.com what I think is the official website I don't see links to that website. Is this an official and sanctioned resource by @Ylianst ?

I just checked, and yeah....wiki<ug> ...all the different wiki languages give me a headache, and it looks like that one looks like another proprietary html-ish mishmash of the same.

Most modern html systems: gh-docs, mkdocs, https://vuepress.vuejs.org/ are all structured markdown so you can move from one doc system to another without complete re-writes. Since Meshcentral is using Github, it would seem logical to use the same systems. It also integrates with all the git-magic for change tracking etc instead of a proprietary wiki-system. That wiki also has no VSCode integration, extension support for formatting, no code signing...I could go on, but I'll spare you ;)

**Comment by silversword411** [comment]
@jjoelc 
Can you please update the main wiki page with something like this, you've locked that page so others can't update it. People find the wiki with old/incorrect information, and then come here asking for help.

Thanks

```
This wiki can contain old and outdated information Please use the official documentation source found here:
https://ylianst.github.io/MeshCentral/

If you'd like to edit the official docs, you can submit a Github PR request and it will be updated at next release.
```

**Comment by jjoelc** [comment]
I'll definitely be contributing to the official documentation. Glad to see it in place!
![image](https://github.com/Ylianst/MeshCentral/assets/4069621/6a5dfe98-4ca4-4cce-99d3-d6c6cec79df3)

**Comment by si458** [comment]
@jjoelc all the docs for https://ylianst.github.io/MeshCentral/ are located inside the folder [docs/docs](https://github.com/Ylianst/MeshCentral/tree/master/docs/docs)
if you want to add/update this please do!
ill review the PR and if ok ill merge for you!

**Comment by jjoelc** [comment]
Of course, on of the first things I noticed was all of the now broken links pointing to resources at meshcentral.com. Does anyone have copies of those resources? 

The pdf user guides, etc. would of course be helpful, but for many people, the windows installer, and the quick install scripts for Amazon and Azure would be most helpful.  Getting those added here in github would be a huge service. It would also of course be a starting point for keeping those scripts updated, and expanding them or combining into a dingle distribution independent quick install script. (Or at least a couple to cover apt vs yum based distributions...)

I also think some additional sample reverse proxy configs and scenarios would be helpful, and I have some of those I can add. 

Like many people, I have more ideas than time! But do look for me to start contributing! I'm very glad to see this source maturing quickly!

**Comment by si458** [comment]
@jjoelc @Ylianst made a copy of the website and put it all on github so its all here for you
https://github.com/Ylianst/MeshCentralSite
you can also do PR requests to fix anything on meshcentral.com in that repo too

**Comment by silversword411** [comment]
> Of course, on of the first things I noticed was all of the now broken links pointing to resources at meshcentral.com. Does anyone have copies of those resources?

I'm almost finished a PR to fix the links in the docs. Before meshcentral.com moved, I was copying anything relevant to the meshcentral repo for safe keeping including all the ppt files

**Comment by si458** [comment]
@silversword411 ive just updated a few links for you already haha sorry my bad
