### ISSUE TITLE
NPM Error tried to install install in differnet ways and differrent OS's

### ISSUE THREAD

**Issue by radha402** [Ylianst/MeshCentral#3169]
export NVM_DIR="/home/ec2-user/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
######################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v10.15.1 (npm v6.4.1)
Creating default alias: default -> v10.15.1
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN ec2-user No description
npm WARN ec2-user No repository field.
npm WARN ec2-user No README data
npm WARN ec2-user No license field.

+ meshcentral@0.9.28
added 118 packages from 126 contributors and audited 118 packages in 68.705s
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Created symlink from /etc/systemd/system/multi-user.target.wants/meshcentral.service to /etc/systemd/system/meshcentral.service.
Done. Wait two minutes and use a browser to access this server...
WARNING: First user account to be created is site administrator.
[ec2-user@ip-172-31-86-36 ~]$

**Comment by nzalev** [comment]
Hi there,

You have simply dumpted some command output without any description of your issue. Additionally, there are warnings that you have posted, but there are no errors.

```
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
```
These are to do with your own environment.

```
found 2 high severity vulnerabilities
run npm audit fix to fix them, or npm audit for details
```
These are known and are due to NeDB. This is already noted in #2727, #3081, ...  (For production environments, you should be using MongoDB/MariaDB/MySQL)

From the last part of your output, it looks like systemd has already started meshcentral as a service. If not, you can manually start it via `node node_modules/meshcentral`.

**Comment by si458** [comment]
you can use the ec2 script that was created by a community member and on the docs website
https://ylianst.github.io/MeshCentral/install/install2/#amazon-linux-2
