### ISSUE TITLE
Group action file upload fails when embedded in iframe

### ISSUE THREAD

**Issue by M-Ahall** [Ylianst/MeshCentral#3171]
Hi,

Group action file upload works beautifully when using a site directly, out of iframe.

Same site, within iframe authenticated with a login token, nothing visible happens, but javascript console responds prints out:
`POST https://<server>/uploadfilebatch.ashx 401 (Unauthorized)`

I tried the ScriptTask plugin with the same result as well.

Best regards,
Magnus

**Comment by Ylianst** [comment]
Add the following two lines to the settings section of the config.json:

```
"allowFraming": true,
"sessionSameSite": "none"
```

That should fix it. However, this affect cross-site security, so you need to know what you are doing.

**Comment by M-Ahall** [comment]
Yep, that fixed it.

Given the knowledge of the same-site issue, I will consider just putting it on a subdomain within the same domain as the enclosing website.

Thanks!
