### ISSUE TITLE
Documentation Typo for non Let's Encrypt SSL Certificates

### ISSUE THREAD

**Issue by jmantz** [Ylianst/MeshCentral#3174]
The documentation provided from Meshcentral.com here:

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.1.0.pdf

States the following for implementing your own SSL certificates, on page 8, section 5:

For large scale deployments or setup, a legitimate trusted certificate is highly recommended for
your web server. This way, any web browser that navigates to this web server will be able to
readily verify its authenticity.
 If a legitimate trusted certificate is available, replace “webserver-cert-public.crt” and
“webserver-cert-public.key” with your certificate. These files are located in
“meshcentral-data” folder of the server.

The private key file should actually be named webserver-cert-private.key, not webserver-cert-public.key as above.

**Comment by Ylianst** [comment]
This does not make sense, are you referring to the MeshCentral User's Guide?

[https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf)

Looking at that, the document is correct. Maybe you can indicate where it's wrong. Thanks.

**Comment by jmantz** [comment]
Apologies, I linked the wrong one, too many tabs open. Yes, I mean the MeshCentral User's Guide, this is the one I was referring to.

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.2.pdf

But I now see that this is version 0.2.2 and the latest that you've linked is 0.2.9 and it's correct as you said. I must have gotten the link from an older github issue and not noticed the version number.
