### ISSUE TITLE
Per-group notification broken in 0.9.28 server

### ISSUE THREAD

**Issue by Ajilis** [Ylianst/MeshCentral#3177]
Hi,
Its seems per-group notification is broken in 0.9.28 server.
- Global notification on connect active is OK
- If i disable this setting and put it only on a group and reboot a device no notifications.

Does someone get the same behaviour ?

_Originally posted by @Ajilis in https://github.com/Ylianst/MeshCentral/issues/361#issuecomment-937560863_

**Comment by Ylianst** [comment]
You are right! I see the same problem... looking into it now.

**Comment by Ylianst** [comment]
Thanks for reporting this. I just put in a fix, will be in MeshCentral v0.9.30

**Comment by Ajilis** [comment]
Thanx Ylianst, do you think there is a feature to use email notification instead of webpush ?

**Comment by Ylianst** [comment]
Please close this issue if it's solved. For email notification, this is a different issue and I am working on it.

**Comment by Ylianst** [comment]
@petervanv You are saying that you do not have device notification turn on in my account and in the device group and still see notifications? Make sure to turn notification off for all your device groups.

![image](https://user-images.githubusercontent.com/1319013/136856255-73f9eaff-ffb1-4f01-a9f3-65360ba770df.png)

With both turned off, you still see device notifications?

**Comment by Ylianst** [comment]
For new email notification system in MeshCentral v0.9.31, see #3150.

**Comment by petervanv** [comment]
> For new email notification system in MeshCentral v0.9.31, see #3150.

@Ylianst i looked it up, and yes it was on, but in the past it did cause any trouble at all, after the update all nodes are were notifien me of dis and connection without the change of settings.

After de secting that items it stopt notififing me, execpt for the nodes it was set to sent an notification. so problem solved !!

**Comment by Ylianst** [comment]
Good. Yes, the behavior was not correct before.
