### ISSUE TITLE
Sort is not correct

### ISSUE THREAD

**Issue by MalteKiefer** [Ylianst/MeshCentral#3178]
Hello,

I think the sort is not correct:

![image](https://user-images.githubusercontent.com/59220985/136394227-4c4d17d4-70f8-4b3a-b6c4-9afaa33be009.png)

it should be:

```
PC-LF-SU-2
PC-LF-SU-3
PC-LF-SU-18
PC-LF-SU-20
PC-LF-SU-24
PC-LF-SU-25
PC-LF-SU-26
PC-LF-SU-32
```

**Comment by Ylianst** [comment]
MeshCentral v0.9.29 is out with this fix.

**Comment by Ylianst** [comment]
Going to close this since it's likely fixed and no response was received.
