### ISSUE TITLE
Change the Agent icon

### ISSUE THREAD

**Issue by MalteKiefer** [Ylianst/MeshCentral#3179]
Good day,

is there a possibility here in the settings:

```json
"_agentCustomization": {
    "displayName": "Compagny® Product™",
    "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
    "companyName": "compagny",
    "serviceName": "compagnyagent",
    "fileName": "compagnyagent"
},
```

Also to specify a path to another icon for the agent? I would like to store our company logo.

Thanks

**Comment by Ylianst** [comment]
One of the problems with this is that the agent icon resource is within the signed portion of the agent. Not that it's super important since the agent is signed with an untrusted cert anyway. You could compile your own agent with a different icon right now, the [source is here](https://github.com/Ylianst/MeshAgent).

In general, I am not sure how we would go about doing this in a clean way. Another option is that you can built a wrapper installer with your own logo, etc and inside, call "meshagent.exe -fullinstall".

**Comment by frakman1** [comment]
I thought the agent icon is on the webserver component (not the meshagent)
I am talking about the pop-up list of options I get when I click on a device's icon on meshcentral server
![image](https://user-images.githubusercontent.com/5826484/148388360-1374af5e-a736-4e77-8e54-355ebd008fdf.png)
Just like I can change the displayed name of the device, I would like to replace the device icon with one that I can upload via the web browser.

**Comment by cheuklam** [comment]
> I thought the agent icon is on the webserver component (not the meshagent) I am talking about the pop-up list of options I get when I click on a device's icon on meshcentral server ![image](https://user-images.githubusercontent.com/5826484/148388360-1374af5e-a736-4e77-8e54-355ebd008fdf.png) Just like I can change the displayed name of the device, I would like to replace the device icon with one that I can upload via the web browser.

Same thought, If there is some OS related icons (said centos / ubuntu / android or basically an linux icon) would be nice. I can assume the remainings are windows device so that there will not be any issue with the logo copyright.

**Comment by mwllgr** [comment]
Now that we can change the file information thanks to https://github.com/Ylianst/MeshCentral/commit/44994a5a9bc49726076b8ecbcc269d56d25325c1, would it maybe be possible to change the executable icon too, @Ylianst? That would be a nice step forward regarding customization.

**Comment by mwllgr** [comment]
Oh, you're already working on it. Thanks! (Commit 48c6b42a0b9f5c1bc78fa2dd5e8e389e8a8499bb)

**Comment by Ylianst** [comment]
Just release this feature as part of 1.0.65. The code to break apart and re-assemble Windows a executable is complex so, I recommend trying this first on a non-production server. I will close this one, but do open a new issue if you see something that is not right.

![MC2-AgentIconCustomization](https://user-images.githubusercontent.com/1319013/184432527-316b6b62-bba8-4051-80bc-183bfce28fd0.png)

**Comment by EDIflyer** [comment]
> I thought the agent icon is on the webserver component (not the meshagent) I am talking about the pop-up list of options I get when I click on a device's icon on meshcentral server ![image](https://user-images.githubusercontent.com/5826484/148388360-1374af5e-a736-4e77-8e54-355ebd008fdf.png) Just like I can change the displayed name of the device, I would like to replace the device icon with one that I can upload via the web browser.

Did you find a way to edit these? Would be great to be able to add our own custom ones.
