### ISSUE TITLE
Check fo Update => Unknown

### ISSUE THREAD

**Issue by MalteKiefer** [Ylianst/MeshCentral#3180]
Just checked on my server to see if there is a new version for installation to check the #3178.
However, I only see that? Unbekannt => Unknown

![image](https://user-images.githubusercontent.com/59220985/136431379-6ca97f2a-8461-4633-90fe-dd0c1138ebca.png)

Debug log shows no error

**Comment by Ylianst** [comment]
Everything looks good for me, but this may depend on your region.

![image](https://user-images.githubusercontent.com/1319013/136486144-514ceeb9-4194-451b-8c17-2725de9f18b6.png)
