### ISSUE TITLE
Translate access request

### ISSUE THREAD

**Issue by MalteKiefer** [Ylianst/MeshCentral#3181]
When I installed the agent, the installation dialog was in German, which is correct. However, when I ask for access, the dialogs are each in English. I could not find the strings in the corresponding translation file either. How can I translate the following dialogs?

![image](https://user-images.githubusercontent.com/59220985/136408518-cafc8fd2-9315-49dc-8b54-ecf49a065eeb.png)
Buttons in German, the text in English.

**Comment by Ylianst** [comment]
In the domain section of the config.json, you can add this:

```
      "consentMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) requesting remote desktop access. Grant access?",
        "Terminal": "{0} ({1}) requesting remote terminal access. Grant access?",
        "Files": "{0} ({1}) requesting remote files access. Grant access?"
      },
```

This allows you to customize the request. Let me know if that works for you.

**Comment by Ylianst** [comment]
Nice. There is no way to change that icon now, but if you make a new request for it, Bryan may be able to look into it since that is a agent side request.
