### ISSUE TITLE
Upload files dialog only local, not from My Files on Server storage

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#319]
When in Files connection to agent and click upload. You can only select from local working system. I can not select files which are in My Files on the MeshCentral server.

With Upload Mesh Core Agent you can select local or server.
![image](https://user-images.githubusercontent.com/5203309/59965111-39983a00-950a-11e9-8a06-59c4222cb746.png)

It would be nice if it is also possible for all other upload actions.

**Comment by Ylianst** [comment]
So, the feature you show above is to upload a agent JavaScript core module to run that agent. It's really a developer feature, not something a normal user would typically use. I will take a look at it at some point, but certainly not a priority since Bryan, myself and over developers would be the main users.

**Comment by hunter-nl** [comment]
Yes, I understand that upload mesh agent core is a developer feature. But it is about the selection part of "Local file upload or Server file selection". This is very handy with other upload dialogs. In this way I can store a file on mesh server in a mesh group. And other member of that mesh group can use this file to upload to an agent through the files tab without to have it downloaded first from mesh server from "My Files" and then to upload it from local computer.

**Comment by Ylianst** [comment]
Got it. However, I am flooded with feature request and bug report right now, so it will take a while for me to get to this one. Could be nice to send big files directly from the server to agent for sure.
