### ISSUE TITLE
Per-device Email Notifications for Device State Change

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#3190]
I just saw that version 0.9.32 was recently released and can now send device connect/disconnect notifications via email. This is awesome.
However, it appears this notification is a group wide setting.  Not an individual device setting.
I really only want to be notified if certain devices in a group disconnect (such as a server).  
I'm requesting that the notification option, if possible, be modified so that we can select the notification settings on a per device basis.

**Comment by Ylianst** [comment]
MeshCentral v0.9.33 was published with pre-device notifications and email.

![MC2-SpecificDeviceNotifications](https://user-images.githubusercontent.com/1319013/137432956-09554914-3465-4052-b464-91055b85a417.png)

**Comment by PathfinderNetworks** [comment]
Thank you Ylian,
I updated very early this morning and this is working perfectly.  Absolutely wonderful and very useful feature!  I also appreciate that you configured it so that if multiple devices change state in a similar time period that it includes all those devices in a single email.  That helps immensely to prevent email overload like I get with some of my other MSP tools.

**Comment by Ylianst** [comment]
Interesting that other MSP tools would not group multiple notifications in a time period... that could lead to a lot of emails.
