### ISSUE TITLE
Feature Request : Would it possible to limit the scope of `MaxInvalidLogin` ?

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#3192]
# Problem Description:
Would it possible to limit the scope of `MaxInvalidLogin` ?

# Environment Details:
* MeshCentral Version : v0.7.89 (Latest Stable)
* Linux Distribution: Ubuntu 18.04.4 LTS
* Our authorized administrators all login to a VPN, from which, they then RDP into to a single jump box, then access the MeshCentral web UI.
* Our authorized administrators are generally the same on all our domains, and need access to multiple domains to manage the endpoints

# Research:
In https://github.com/Ylianst/MeshCentral/issues/640 you implemented `MaxInvalidLogin`, `time`, `count` and `coolofftime`. Testing that in our somewhat unique configuration results in all users getting locked out when one user incorrectly enters their password N times for Y minutes.

# Use Case:
In our case, our authorized administrators all login to a VPN, from which, they then RDP into to a single jump box, then access the MeshCentral web UI. From the MeshCentral server, this seems like all authorized administrators are logging into the UI from the **same** perceived IP, therefore, if one user incorrectly enters their password too many times, **all users** get locked out of **all domains** until the `coolofftime` expires.

# Priority:
Low

# Ask:
Would it possible to limit the scope of `MaxInvalidLogin` ?

For example, if a `scope` flag was added:

```json
"MaxInvalidLogin": {
    "scope": "domain",
    "time": 60,
    "count": 3,
    "coolofftime": 1440
}
```
Where `scope` would be: 
* global if no `scope` flag was set (so, it would function as it does now for backward compatibility)
* `domain` if the scope was per domain (It would only ban that IP on the associated domain for all user accounts)
* `user` if the scope was per user (It would ban that IP on all domains with the same named account)
* `specificaccount` if the scope was the least restrictive (It would only ban that IP on the account and domain where the offense occurred)

If there is some other way to achieve this, please let me know!

**As always, thanks to you and your teams amazing product and hard work. It is greatly appreciated**

**Comment by Ylianst** [comment]
I just added the 'exclude' feature to the `MaxInvalidLogin`. It will be in MeshCentral v0.9.33. However, you can easily add support in your existing server without updating. Add this exclude like this:

```
    "MaxInvalidLogin": {
      "exclude": [ "192.168.3.0/24", "192.168.2.146" ],
      "time": 60,
      "count": 3,
      "coolofftime": 1440
    },
```

Or like this:

```
    "MaxInvalidLogin": {
      "exclude": "192.168.3.0/24,192.168.2.146",
      "time": 60,
      "count": 3,
      "coolofftime": 1440
    },
```

Both are acceptable. Then, backup and edit the file 'node_modules/meshcentral/webserver.js and replace this function:

```
    obj.setbadLogin = function (ip) { // Set an IP address that just did a bad login request
        if (parent.config.settings.maxinvalidlogin === false) return;
        if (typeof ip == 'object') { ip = ip.clientIp; }
        var splitip = ip.split('.');
        if (splitip.length == 4) { ip = (splitip[0] + '.' + splitip[1] + '.' + splitip[2] + '.*'); }
        if (++obj.badLoginTableLastClean > 100) { obj.cleanBadLoginTable(); }
        if (typeof obj.badLoginTable[ip] == 'number') { if (obj.badLoginTable[ip] < Date.now()) { delete obj.badLoginTable[ip]; } else { return; } }  // Check cooloff period
        if (obj.badLoginTable[ip] == null) { obj.badLoginTable[ip] = [Date.now()]; } else { obj.badLoginTable[ip].push(Date.now()); }
        if ((obj.badLoginTable[ip].length >= parent.config.settings.maxinvalidlogin.count) && (parent.config.settings.maxinvalidlogin.coolofftime != null)) {
            obj.badLoginTable[ip] = Date.now() + (parent.config.settings.maxinvalidlogin.coolofftime * 60000); // Move to cooloff period
        }
    }
```

With this function:

```
    obj.setbadLogin = function (ip) { // Set an IP address that just did a bad login request
        if (parent.config.settings.maxinvalidlogin === false) return;
        if (typeof ip == 'object') { ip = ip.clientIp; }
        if (parent.config.settings.maxinvalidlogin != null) {
            if (typeof parent.config.settings.maxinvalidlogin.exclude == 'string') {
                const excludeSplit = parent.config.settings.maxinvalidlogin.exclude.split(',');
                for (var i in excludeSplit) { if (require('ipcheck').match(ip, excludeSplit[i])) return; }
            } else if (Array.isArray(parent.config.settings.maxinvalidlogin.exclude)) {
                for (var i in parent.config.settings.maxinvalidlogin.exclude) { if (require('ipcheck').match(ip, parent.config.settings.maxinvalidlogin.exclude[i])) return; }
            }
            return;
        }
        var splitip = ip.split('.');
        if (splitip.length == 4) { ip = (splitip[0] + '.' + splitip[1] + '.' + splitip[2] + '.*'); }
        if (++obj.badLoginTableLastClean > 100) { obj.cleanBadLoginTable(); }
        if (typeof obj.badLoginTable[ip] == 'number') { if (obj.badLoginTable[ip] < Date.now()) { delete obj.badLoginTable[ip]; } else { return; } }  // Check cooloff period
        if (obj.badLoginTable[ip] == null) { obj.badLoginTable[ip] = [Date.now()]; } else { obj.badLoginTable[ip].push(Date.now()); }
        if ((obj.badLoginTable[ip].length >= parent.config.settings.maxinvalidlogin.count) && (parent.config.settings.maxinvalidlogin.coolofftime != null)) {
            obj.badLoginTable[ip] = Date.now() + (parent.config.settings.maxinvalidlogin.coolofftime * 60000); // Move to cooloff period
        }
    }
```

Once you reset the server, you will get the exclusion. Let me know if that works.
