### ISSUE TITLE
Feature Request: Enroll

### ISSUE THREAD

**Issue by ThanosAntmanEntrance** [Ylianst/MeshCentral#3193]
Hey Guys, its me again.
Is there a feature or plugin or something to enroll hosts. 
Or is it possble to install a program to all my devices with some simple steps.

Cheers

**Comment by Ylianst** [comment]
You can download the MeshAgent and run `meshagent.exe -fullinstall` on a remote device to install it. Try `meshagent.exe -help` for all the command line switches.

As for how to deploy and run the agent install on lots of system, I think there was discussion on that in [Reddit](https://www.reddit.com/r/MeshCentral/) a while back by I can't find it. There are Windows domain tools you could probably use but not sure.
