### ISSUE TITLE
Help request assistant

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3194]
Meshcentral hosted on Linex VM 20.04 LTS
Meshcentral version: 0.9.32
Type: assistant application
remote machine: Windows 10 Home 21H1

When a user requests help, and he does not fill in an request the popup is showing span informatie.
could it be set to "the user did not specify an error" or somthing like that ?

It happens in connect on request and systray connect on request, other options i did not try.
![help request limited restrictions](https://user-images.githubusercontent.com/58996467/137330221-96e61fc3-28f8-4766-8a49-4751ea599f99.jpg)

**Comment by Ylianst** [comment]
Fixed it, will be in v0.9.33
