### ISSUE TITLE
Unrecognized configuration option

### ISSUE THREAD

**Issue by eglyn** [Ylianst/MeshCentral#3198]
Hi :)
I setup MeshCentral on a Debian 11 with npm, and I try to personalize settings in config.json
I use [this one](https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json) as model.

But I have this errors: 
WARNING: Unrecognized configuration option "maxinvalidlogin".
WARNING: Unrecognized configuration option "passwordrequirements".
WARNING: Unrecognized configuration option "userconsentflags".

Why meshcentral does not recognize the news parameters ?

**Comment by Ylianst** [comment]
Hi. The problem is that you are adding options to the root of the config.json when they should be in the "settings" or "domain" section. So, for example, this is not correct:

```
{
  "settings": {
    ..
  },
  "domains": {
    "": {
      ..
    }
  },
  "maxinvalidlogin": {},                      <--- Incorrect location
  "passwordrequirements": {},
  "userconsentflags": {}
}
```

This would work:

```
{
  "settings": {
    ..
  },
  "domains": {
    "": {
      "maxinvalidlogin": {},
      "passwordrequirements": {},
      "userconsentflags": {}
    }
  }
}
```

**Comment by eglyn** [comment]
Ok thx, it was that !
But config file sample misled me :)
