### ISSUE TITLE
OSX Agent: No interface information

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#320]
With OSX Agent, No interface information available.

![image](https://user-images.githubusercontent.com/5203309/59965211-5719d380-950b-11e9-969b-cf11b4d13192.png)

I expected a few interfaces and several IPv4/6 information.

**Comment by krayon007** [comment]
This is fixed in GIT. It will be released soon, when we release an agent update in the server.

**Comment by hunter-nl** [comment]
Any progress on this? With version 0.3.8-n same result.

**Comment by Ylianst** [comment]
I think this has been fixed a long time ago. Please open a new issue if this occurs again.
