### ISSUE TITLE
Remote unzip function on "Files" manager menu.

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3200]
This is a small, lowest priority idea for a feature.

There are some situations where having a remote unzip/unrar/unpack tool would be nice and helpful. Please consider adding this option.

Thanks.

**Comment by rodrigolzd** [comment]
Just saw the new edit function being added to the files menu. Any chance this could also be implemented?

https://github.com/Ylianst/MeshCentral/issues/4243

**Comment by si458** [comment]
this already exists in the console tab
`unzip C:\Users\PC\Documents\example.zip,C:\Users\PC\Documents\examplezipfolder`
just need to make a GUI button now next to `ZIP`
