### ISSUE TITLE
Windows 10/11 version identification wrong since 20H2

### ISSUE THREAD

**Issue by kiroubel-girma** [Ylianst/MeshCentral#3201]
Since Windows 10 version 20H2, MeshCentral reported OS version is the _Release ID_, which is no longer the official displayed version anymore.
All new Windows 10/11 PCs report version _2009_ instead of version 20H2, 21H1 or 21H2. Build number is correctly reported.
Display Version can be found in the registry.
So one solution seems to first query for value of version in :
**HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\DisplayVersion**
If that produces error, look for the release id in:
 **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseId**
Example test vbscript:
```
' Get Windows 10/11 version from registry
On Error Resume Next
Set objShell= CreateObject("WScript.Shell")
value = ""
Err.Clear
value = objShell.RegRead("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\DisplayVersion")
If Err.Number <> 0 Or value = "" Then
	Err.Clear
	value = objShell.RegRead("HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseId")
	If Err.Number <> 0  Or value = "" Then
		value = "No RealeaseID found."
	End If
End If
Wscript.Echo value
```
Note that Windows 11 internally reports as 10.
To get the OS name, query WMI as the _ProductName_ value in registry is no longer correct.
Example test command line (works on all supported Windows editions)
`wmic os get Caption`

**Comment by Ylianst** [comment]
FYI. Bryan seems to have a fix for this that will be release when an updated MeshAgent gets released.

**Comment by kiroubel-girma** [comment]
On the last agent update (1/7/2022) this is mostly fixed as the information displayed is now correct.
The correct **Windows Edition** is shown, but the **Version** is missing;  the main build number is still there.
For example now it shows **_Microsoft Windows 11 Pro N - 22000_** .
A better display would be something like **_Microsoft Windows 11 Pro N 21H2 - 22000_**. 
But build number is sufficient; it's like missing the service pack for Windows 7.
Maybe label as something like  _Known Issue_  and close issue if there are no plans to add version.

**Comment by krayon007** [comment]
I found where the friendly display name "21H1" is stored, so I will include that in the next agent update. This field will only show up on newer versions of windows tho.

**Comment by kiroubel-girma** [comment]
This has now been fixed, version and build number are displayed correctly.
