### ISSUE TITLE
Session recording not active over guest sharing 

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#3207]
I noticed that there is no server side session recording taking place when connection via a (time limited) guest sharing link.

- MC 09.35
- device group has 'Record Sessions' enabled
this is working for Users logged in to the WebUI
- for Windows 10 and Linux (Pi Zero) Agents
- for Desktop or Terminal (as configured)

But no recording at all for the very same Agents ... when used via guest sharing links.

Is this intentional (if so why?) or a bug?

_Oh, and there is a glitch regarding the naming of the .mcrec files, the month seems to be off by 1:_
relaysession-2021-**09**-19-10-54-39-user-machine-k1zoagmjjce.mcrec
_is from today (OCT-19)_

**Comment by Ylianst** [comment]
Guest shares should certainly be recorded. Will be looking into it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.9.37 with a fix for this. Let me know if it works.

**Comment by Ylianst** [comment]
Thanks for reporting, I will look at the glitch and month in the filename.

For the recording list, there are configuration options to auto-remove older recordings. [You can specify limits based](https://github.com/Ylianst/MeshCentral/blob/d52c4349614851d44a5c6e60e37cd94c67184c0c/meshcentral-config-schema.json#L697) on recorded files, days old or number of megabytes. In these cases, MeshCentral will automatically remove the older recordings.

You can also safely remove the recorded files from the "meshcentral-recordings" folder. The "My Recordings" tab will still show all the sessions, but will show a green check next to the sessions that recorded files are present.

Let me know if that works. If a removal feature is needed, just add a GItHub issue and make a request for it.

**Comment by baikal** [comment]
Confirmed everything works nicely on 0.9.38.

Regarding the Recording List. I already had deleted the files and was thinking about uncluttering the List from my test recordings. Anyway, I did tinker with meshcentral-events.db and got rid of the entries that way.
I knew about the limits - do the remove the files only or the entries as well?
