### ISSUE TITLE
Multiple servers for one agent

### ISSUE THREAD

**Issue by vedran-dobos** [Ylianst/MeshCentral#3208]
Hi,

Is it possible to have one agent (Windows 10 for example) connect to multiple MeshCentral servers?

I have run into a conflict with another software developer who is also using MeshCentral to support their clients.
We are now fighting over control, and reinstalling each other's agents 😅 .

Thanks for the great software!

**Comment by Ylianst** [comment]
@VINISHVV is exactly right. You can't install two MeshCentral agents with default configuration, but if you customize your agent with a different service name, you can install both agents at the same time.
