### ISSUE TITLE
MC Agent proxy support

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#321]
Hi Ylianst,

do you have planned to implement proxy/socks support in MC agent, by any chance?
If feasible, it would be very useful in some cases, doesn't it?
Just for the record: I know it's a kind of a gimmick, nonetheless under Windows (where I have to use proxy...) it works flawless with well known Proxifier.

Thanks

**Comment by jsastriawan** [comment]
It is supported. Just add a file named meshagent.proxy (matching binary name) which contains one line http proxy specification in a form of host:port. It will be read by mesh agent and it will be used as default proxy setting.

Regards,


Joko

**Comment by amenolo** [comment]
Intersting!

And what about proxy with autenthication support?

Thanks

**Comment by jsastriawan** [comment]
I don't think proxy with authentication is supported. @krayon007 may be able to explain. You can also see the MeshAgent code and suggest some modification if you want.

**Comment by amenolo** [comment]
> You can also see the MeshAgent code and suggest some modification if you want

If I were a programmer, I would with pleasure...but I have to face reality of being just a simple final user (luser, sometimes...).

Thanks for your kind replies!

**Comment by Ylianst** [comment]
So, you can create a "meshagent.proxy" file (just be the same name as the MeshAgent executable with .proxy, remove .exe on Windows). It's just a text file and you put "proxy.server.com:123". If proxy authentication is required, please let me know exactly what authentication is requested, Bryan would have to look into it since it's an Agent feature.

**Comment by amenolo** [comment]
> let me know exactly what authentication is requested

In my case it's about basic authentication but could be digest rather than NTLM, as you may know ([https://ec.haxx.se/usingcurl-proxies.html](url)).

**Comment by Ylianst** [comment]
Bryan will have to take a look at basic or digest proxy auth. For NTLM, a user would have to be logged in and the agent would not be able to run in the background for this to work.

**Comment by Ylianst** [comment]
I am going to close this since we got no more requests for basic/digest proxy auth. Please comment or re-open if this feature is important to you.

**Comment by GabrieleV** [comment]
Hy,
I need to use meshagent in Linux behind a proxy that require authentication. Is it supported now ?

**Comment by si458** [comment]
> Hy, I need to use meshagent in Linux behind a proxy that require authentication. Is it supported now ?

from what im aware, you can use a proxy as explained above
BUT it doesnt support authentication yet still sadly,
i would open a new issue (enhancement) in the meshagent repo so we can keep a track for you!
https://github.com/Ylianst/MeshAgent
the agent doesnt really get updates recently unless its urgent,
all the new features im adding are the javascript side of things to get information etc
where as proxy support requires a change in the agent itself
