### ISSUE TITLE
This platform is configured to use Xwayland  please modify config to use Xorg

### ISSUE THREAD

**Issue by zaggynl** [Ylianst/MeshCentral#3211]
I couldn't find anything in the manuals, did find a different issue mentioning this so thought I'd document it.
Below message appears when trying to connect to an Ubuntu 20.04.* desktop via Desktop tab:
![xwayland](https://user-images.githubusercontent.com/5062119/138089897-1e5c3353-ce28-4e3d-9c74-b88318dfa7a8.jpg)

Solution:
Switch to the terminal tab, connect
Edit the gdm custom file:
nano /etc/gdm3/custom.conf
remove the # before #WaylandEnable=false
Ctrl+O, Ctrl+X to save and exit
restart gdm: service gdm restart
(someone could do this with regexp and a bash oneliner, give a shout)
Go back to the desktop tab and try to connect.

**Comment by mthbrown** [comment]
@zaggynl Here's your one-liner :) It backups the original with the `.bak` extension as well

```
sed -i.bak "s/^#Wayland.*/WaylandEnable=false/g" /etc/gdm3/custom.conf
```

**Comment by edlins** [comment]
PinePhone Pro shipped OS is Manjaro + Plasma Mobile (XWayland only).  😢
