### ISSUE TITLE
[Question] Accessing a Mac that's on the Login Screen?

### ISSUE THREAD

**Issue by PlaneNuts** [Ylianst/MeshCentral#3213]
So, this is probably a dumb question, but maybe someone can point me in the right direction. I just came across MeshCentral today while looking for an RDP type solution for Macs. I got a test instance up and running, and as per this [comment](https://github.com/Ylianst/MeshCentral/issues/1948#issuecomment-805579635) I got the agent installed and running on a Mac running Big Sur 11.6. Everything works perfectly right up until I reboot or log off. 

On reboot
The agent doesn't seem to relaunch unless I log into an account

On Log Out
With the Mac on the login screen I can still connect to terminal and file sessions, but desktop sessions bring me to a black screen

I'm not sure if this is the normal behavior, or if I'm doing something wrong

**Comment by PetieM** [comment]
That's odd - my Mac service auto-starts just fine though I didn't follow the procedure referenced in your linked comment. I just installed using the installer and then connected once to trigger the permission prompt. Maybe try that?

**Comment by PetieM** [comment]
Got it, we'll probably need to wait for someone with a bit more knowledge than I have to chime in at this point. Sorry I couldn't get you the answer you needed!

**Comment by PlaneNuts** [comment]
Hi @krayon007 this is the output I got. I assume I needed to `sudo ./meshagent_osx64 -state` since it didn't find ./meshagent
```
MacBook-Pro:~ user$ cd /usr/local/mesh_services/meshagent/
MacBook-Pro:meshagent user$ sudo ./meshagent -state
Password:
sudo: ./meshagent: command not found
MacBook-Pro:meshagent user$ ls
DAIPC			meshagent_osx64		meshagent_osx64.log
kvm			meshagent_osx64.db	meshagent_osx64.msh

MacBook-Pro:meshagent user$ sudo ./meshagent_osx64 -state
Querying Mesh Agent state...
Mesh Agent connected to: [NOT CONNECTED]
 Chain Timeout: 168567 milliseconds
 FD[8] (R: 0, W: 0, E: 0) => Signal_Listener
 FD[11] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v4
 FD[12] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v6
 FD[13] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v4
 FD[16] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v6
 FD[14] (R: 0, W: 0, E: 0) => net.ipcServer.ipcSocketConnection
 FD[10] (R: 0, W: 0, E: 0) => net.ipcServer
 FD[15] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4


 Timer: 2.8 minutes  (0x7f855a809e00) [meshcore/agentcore.c:4077]
```

When that didn't work I kickstarted the process and got this

```
MacBook-Pro:meshagent user$ sudo launchctl kickstart -k system/meshagent

MacBook-Pro:meshagent user$ sudo ./meshagent_osx64 -state
Querying Mesh Agent state...
Mesh Agent connected to: local
 Chain Timeout: 117000 milliseconds
 FD[10] (R: 0, W: 0, E: 0) => MeshServer_ControlChannel
 FD[8] (R: 0, W: 0, E: 0) => Signal_Listener
 FD[11] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v4
 FD[12] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v6
 FD[13] (R: 0, W: 0, E: 0) => ILibMulticastSocket_v4
 FD[16] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v4
 FD[17] (R: 0, W: 0, E: 0) => ILibMulticastSocketListener_v6
 FD[18] (R: 0, W: 0, E: 0) => ILibMulticastSocket_v4
 FD[19] (R: 0, W: 0, E: 0) => net.ipcServer.ipcSocketConnection
 FD[14] (R: 0, W: 0, E: 0) => net.ipcServer
 FD[15] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4


 Timer: 2.0 seconds  (0x7f82a3c8dd90) [setTimeout()]
 Timer: 19.9 minutes  (0x7f82a3c90a30) [setInterval(), meshcore (InfoUpdate Timer)]
```
One thing that just occurred to me that is the device is bound to an AD domain. Don't know if that would have any impact. I tried both an AD mobile profile, and a local user profile. I don't have any MDM or policies installed (machine was literally wiped, and added to the domain, nothing else)

**Comment by si458** [comment]
duplicate #1459
