### ISSUE TITLE
web-rdp change IP/port

### ISSUE THREAD

**Issue by 12nick12** [Ylianst/MeshCentral#3216]
Any chance there would be a way to have the web-rdp tunnel to a specific IP/Port. Usage would be I have https://hub.docker.com/r/linuxserver/rdesktop on a rPi, and then MC on the Pi. It doen't have an actually GUI on the PI, just this rdesktop software. If I can tunnel to localhost I should be able to connect to that container. 

Thank you for the awesome software, I use it every day.

**Comment by Ylianst** [comment]
Hi. First, if you MeshCentral server is in LAN or Hybrid Mode, you can create a "Local devices" device group like this:

![image](https://user-images.githubusercontent.com/1319013/138575466-9100eda6-290f-4da6-980a-44aba01a6af7.png)

This will allow you to add a new device by hostname and specify if the device is Windows or Linux based. Then, you can right click on the "web-rdp" list and specify a different port if you like.

![image](https://user-images.githubusercontent.com/1319013/138575447-59b8c4ec-99af-4e91-bd3f-b999b86cfec4.png)

Let me know if that works.

**Comment by 12nick12** [comment]
Thanks for  the reply. It's in WAN mode.

Oct 23, 2021 8:38:26 PM Ylian Saint-Hilaire ***@***.***>:

**Comment by Ylianst** [comment]
In WAN mode, the server is not setup to reach out and connect to any device... so you need to install the MeshAgent on the remote device. This said, you can still right-click on the "Web-RDP" link and change the port.

You can also switch your server out of WAN mode by removing the `"WanOnly":true` in the config.json.

**Comment by 12nick12** [comment]
The device I'm connecting to is remote and has MA installed. I didnt know I can rightclick there. Thats awesome. Thank you.

Oct 23, 2021 8:42:17 PM Ylian Saint-Hilaire ***@***.***>:
