### ISSUE TITLE
Mesh Agent desktop connecting to a black screen Updated to latest version still happening.

### ISSUE THREAD

**Issue by YChaseLCC** [Ylianst/MeshCentral#3217]
We use Mesh to remote in and monitor/assist associates during training and on the floor when they are experiencing difficulties. We have been experiencing an issue where the agent desktop tab will allow you to connect but remain on a black screen. The resolution has been to switch to the console tab clear the agent core and then update with the default core.

PC's using the Mesh central remote are running mostly Windows 10 on the latest update. The connection issues mostly deal with units running Linux that are remoted into a windows environment on our server. We have about 300 machines and they run various versions of Linux mint Windows 10 and Windows 7 depending on their application of use. 

We have the MeshCentral server installed on our main server pc and we use web browsers (I use Google Chrome) to connect to agents pcs. These issues are periodic but its always the same solution. Im putting this out there as a placeholder with the intend to update and attach screenshots on the next incident so I can better document the OS version and things related to develop potential trends.

Thanks for any feedback and or questions this creates, I will do my best to answer them in an effort to help you all solve this issue!

**Comment by YChaseLCC** [comment]
![Mesh Problem](https://user-images.githubusercontent.com/93149839/140372166-2d125f09-218a-4e7b-ab32-2b36c41a0d65.png)

The issue is still happening after updating to the latest version.  above is the information for the unit we could not access and below is the screen we see when trying to connect to the mesh Desktop.


![mesh issue](https://user-images.githubusercontent.com/93149839/140373092-c46ca413-9ba4-4581-9dd8-9e6ee670c506.png)

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
