### ISSUE TITLE
MeshCMD.exe not connecting to Mesh Central Server for port maps on Windows

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3218]
Mesh Central Server Version:---------0.9.38
Mesh Central Router Version:--------1.8.7960.26198
MeshCMD Version:------------------0.2.1.3
Windows Version:--------------------21H1-19043.1288

The issue/question #112 has now become an issue. I have tested the port map functions of both Mesh Central Router and MeshCMD and have had the following results.

1. Mesh Central Router was able to perform the port map connection perfectly without issues and was able to work with the Login Token option provided by Mesh Central Server.

2. MeshCMD was unable to login to Mesh Central Server at all. Regular and token based logins did not work. In fact the Mesh Central Server Trace showed nothing. Thought well okay maybe it's being held up at the reverse proxy. After inspecting the reverse proxy logs I couldn't even find an attempted connection. 

MeshCMD Debug Output:
```
Settings: {"action":"route","localport":2222,"remotename":"<remote machine name>","remotenodeid":"node//<remote machine node ID>","remotetarget":null,"remoteport":2222,"username":"<Token Username>","serverid":"<Server ID>","serverhttpshash":"<Webserver Cert Hash>","debuglevel":1,"serverurl":"wss://<Webserver domain name>:443/meshrelay.ashx"}
Connecting to <subdomain.domain.tld>.
```

This issues appears to be related to issue [#2873](https://github.com/Ylianst/MeshCentral/issues/2873)
I suspect that there is some kind of issue with the URI construction like the issue listed above. 

I need MeshCMD port map to work because I need to perform the port map on Linux systems. Please let me know if there is anything I can do to help you test for this issue. 

Reference ticket from agents is [#113](https://github.com/Ylianst/MeshAgent/issues/113)

**Comment by Ylianst** [comment]
I just updated [MeshCentralRouterCmd.exe](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouterCmd.exe) so it can be installed as a Windows Service. it's signed, has an icon and help.

When you run it without an "action.txt" file or with `--help` you should see this:

```
MeshCentral Router Command Line Tool.
This tool is used along with a MeshCentral account to map a local TCP port to a remote port on any computer on your MeshCentral account. This action requires many arguments, to avoid specifying them all it's best to download the meshaction.txt file from the web site and place it in the current folder. Example usage:

  (Place meshaction.txt file in current folder)
  MeshCentralRouterCmd.exe --pass myAccountPassword

You can also install and start this tool as a Windows Service:

  MeshCentralRouterCmd.exe --install
  MeshCentralRouterCmd.exe --start
  MeshCentralRouterCmd.exe --stop
  MeshCentralRouterCmd.exe --uninstall

When running as a Windows service, the account password must be in the action.txt file.
```

Let me know if this works. I do want to close this issue. If you have another request, open a new issue. Thanks.

**Comment by LPJon** [comment]
@Ylianst The new MeshCentralRouterCMD tool seems to be working perfectly! Thanks for adding the windows service feature. This should come in real handy for direct connecting windows systems to the backup system!

Closing this issue and opening a new one for the Linux version of this tool.
