### ISSUE TITLE
Web-RDP not working

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#3222]
Hi!
I'm trying to use the web-rdp feature, but I get stuck at the login screen.
When I press Connect after filling the data, it just come back to the same screen after a short blink.
If I "inspect" the webpage with the Chrome dev tools, I get this in the console:

"[mstsc.js] error : NODE_RDP_CORE_TYPE_CONSTANT_VALUE_MISMATCH()"

Also, the meshcentral error log shows this:

<details><summary><code>Mesh Logs</code></summary>
-------- 10/27/2021, 6:12:37 AM ---- 0.9.39 --------

{"name":"node-rdpjs","hostname":"meshcentral","pid":1407,"level":50,"msg":"constant value mismatch 1 != 28271","time":"2021-10-27T06:12:37.302Z","v":0}

-------- 10/27/2021, 6:12:37 AM ---- 0.9.39 --------

{"name":"node-rdpjs","hostname":"meshcentral","pid":1407,"level":30,"msg":"during read of field header","time":"2021-10-27T06:12:37.303Z","v":0}
{"name":"node-rdpjs","hostname":"meshcentral","pid":1407,"level":30,"msg":"during read of field updateData","time":"2021-10-27T06:12:37.303Z","v":0}

-------- 10/27/2021, 6:12:37 AM ---- 0.9.39 --------

{"name":"node-rdpjs","hostname":"meshcentral","pid":1407,"level":40,"msg":"NODE_RDP_CORE_TYPE_CONSTANT_VALUE_MISMATCH()\nError\n    at new ProtocolError (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/error.js:40:8)\n    at UInt16Le.Type.read (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:148:10)\n    at Component.readValue (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:252:16)\n    at Component.Type.read (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:153:9)\n    at Factory.self.updateData [as factory] (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/pdu/data.js:1090:60)\n    at Factory.readValue (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:464:7)\n    at Factory.Type.read (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:153:9)\n    at Component.readValue (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:252:16)\n    at Component.Type.read (/home/meshcentral/node_modules/node-rdpjs-2/lib/core/type.js:153:9)\n    at Client.recvFastPath (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/pdu/global.js:271:38)\n    at Client.<anonymous> (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/pdu/global.js:76:9)\n    at Client.emit (events.js:400:28)\n    at Client.Sec.recvFastPath (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/pdu/sec.js:344:7)\n    at TPKT.<anonymous> (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/pdu/sec.js:293:9)\n    at TPKT.emit (events.js:400:28)\n    at TPKT.recvFastPath (/home/meshcentral/node_modules/node-rdpjs-2/lib/protocol/tpkt.js:140:7)","time":"2021-10-27T06:12:37.304Z","v":0}
</details>

I'm using the latest 0.9.39  version, and the nodejs v16.3.0

Is this some misconfiguration from my part, or is it, indeed, a bug?

thank you in advance!

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above.
if issue still persists, please reply back
