### ISSUE TITLE
Email configuration for SMTP server

### ISSUE THREAD

**Issue by singhchetan** [Ylianst/MeshCentral#3223]
Hi,

Below is the json configuration I am using.

```
 "smtp": {
      "host": "aaa.bbb.iphmx.com", 
      "port": 25,
      "from":"noreply-vproadmin@xxx.com",
      "tls": false,
      "tlscertcheck": false,
      "tlsstrict": false
}
```

My out log say:
MeshCentral HTTPS server running on xxx.zzz.com:444.
SMTP mail server aaa.bbb.iphmx.com working as expected.

But emails are not going. On the trace below is the error. How should it be fixed?

```
12:39:22 PM - EMAIL: SMTP server failed (Skipping): {"code":"ESOCKET","command":"CONN"}
12:39:22 PM - EMAIL: SMTP server failed (Retry:3): {"code":"ESOCKET","command":"CONN"}
12:39:22 PM - EMAIL: SMTP response: {"code":"ESOCKET","command":"CONN"}, undefined
```

**Comment by jnewman67** [comment]
new user, but long time admin.  new install, same issue as the original poster.  connecting to pretty standard postfix mailservers, been connecting outlook and phones to it for years - never an issue.  I've played with every combination I can think of (25/465/587, TLS checked/unchecked).  i can see the mesh server connect to the mail server and disconnect immediately - with zero attempt to deliver any email.  i have verified that the email account is accessible via webmail - i'm very sure it's a connection issue.  i use this same config info for other software/devices that spew emails, and they have no issues with it.  MC happens to be installed on a windows 10 pro desktop, and TLS 1.0, 1.1 and 1.2 are all activated in Internet Properties.  TLS 1.3 and SSL 3.0 are not activated.  for giggles, i opened the Mail app that comes with Windows 10, entered the email address and password, and it connected and set up the account successfully - using myserver.com, port 25, user/pw authentication, no SSL.  when i changed the config below to match those settings, still didn't work.

my config:
   "smtp": {
      "host": "mail.myserver.com", 
      "port": 587, 
      "from": "mesh@myserver.com", 
      "user": "mesh@myserver.com", 
      "pass": "mypassword", 
      "tls": false
   }

it's a problem.

here's the trace for one send attempt - notice the "undefined" in there...
6:46:06 PM - EMAIL: SMTP server failed (Skipping): {"code":"ESOCKET","command":"CONN"}
6:46:06 PM - EMAIL: SMTP server failed (Retry:3): {"code":"ESOCKET","command":"CONN"}
6:46:06 PM - EMAIL: SMTP response: {"code":"ESOCKET","command":"CONN"}, undefined
6:46:06 PM - EMAIL: SMTP sending mail to user@myserver.com.

here's the postfix logfile entries for the above attempt - notice how quickly it disconnects
Nov  4 18:45:46 dns postfix/smtpd[12630]: connect from mesh.myserver.com[zzz.zzz.zzz.zzz]
Nov  4 18:45:46 dns postfix/smtpd[12630]: lost connection after STARTTLS from mesh.myserver.com[zzz.zzz.zzz.zzz]
Nov  4 18:45:46 dns postfix/smtpd[12630]: disconnect from mesh.myserver.com[zzz.zzz.zzz.zzz]
N

**Comment by Ylianst** [comment]
Difficult to debug this without access to the server, but MeshCentral uses NodeMailer.

[https://nodemailer.com/about/](https://nodemailer.com/about/)
[https://www.npmjs.com/package/nodemailer](https://www.npmjs.com/package/nodemailer)
