### ISSUE TITLE
Mesh Agent install fails on Windows 2012 server on New-NetFirewallRule error (works on 2012 R2)

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#3226]
Hi,

I tried to install the windows64 agent from 0.9.39 on a windows 2012 server and it failed with an error on New-NetFirewallRule see screenshot attached below : 

![Screenshot from 2021-10-28 14-04-15](https://user-images.githubusercontent.com/6659329/139252995-f3c4cf31-0cd2-46ae-981d-060f4ae93baa.png)

On a Windows 2012 server R2 it works without issue so may be something changed in powershell options between 2012 and 2012 R2.

Note : with a much older meshcentral 0.5.81 the agent is installing fine on windows server 2012.

**Comment by krayon007** [comment]
I'm still trying to investigate what could be going wrong here... I just tested it on Windows Server 2012 (Non-R2), and it worked. I'm fixing a separate edge case where if there is a policy blocking Powershell... But that isn't your problem, as based on your error, PowerShell is working, it is complaining that a parameter isn't found, which is wierd, becuase according to MSDN, that particular thing was first defined in Server 2012...

**Comment by krayon007** [comment]
Ok, I figured it out... I actually fixed this in September, but the agent wasn't updated yet. The bug was that one of the parameters I used, "DynamicTarget" was not supported until R2. I fixed a few other issues in the mean time, which is why we were delaying updating the agent, to include some of these other fixes... The next agent update will fix this install issue for Windows Server 2012

**Comment by guerby** [comment]
Has the agent been updated with a fix to this issue in a recent release of meshcentral?

**Comment by krayon007** [comment]
Looking at the server logs, I don't think @Ylianst has updated the server with the agent yet. I think he was waiting for a few other fixes, since there were a few windows issues I was working on.

**Comment by guerby** [comment]
I just tried with 0.9.76 and the agent installer worked fine, thanks again!
