### ISSUE TITLE
Device sharing on Agent or Assistant itself?

### ISSUE THREAD

**Issue by alialpsln** [Ylianst/MeshCentral#3230]
Hello,

Device sharing, which we can do on Meshcentral server, can also be done by the agent itself? 

For example, when the Assistant (or Meshagent) tray icon is right-clicked, the share link can be obtained with "share this device" button?

Thanks

**Comment by Ylianst** [comment]
The sharing link is created on the server side and can only be created by someone that has rights to access this device. So, you can't create a sharing link from the agent side (Agent or Assistant or Android Agent).

You can use "meshctrl.js" to automate creation of sharing links if you like. Here is the help section of MeshCtrl.js device sharing.

```
node meshctrl.js help devicesharing
List sharing links for a specified device, Example usages:

  MeshCtrl DeviceSharing --id deviceid
  MeshCtrl DeviceSharing --id deviceid --remove abcdef
  MeshCtrl DeviceSharing --id deviceid --add Guest --start 2021-10-29T14:32:24 --duration 30
  MeshCtrl DeviceSharing --id deviceid --add Guest --type desktop,terminal --consent prompt

Required arguments:

  --id [deviceid]                - The device identifier.

Optional arguments:

  --remove [shareid]              - Remove a device sharing link.
  --add [guestname]               - Add a device sharing link.
  --type [desktop,terminal,files] - Type of sharing to add, can be combined. default is desktop.
  --viewonly                      - Make desktop sharing view only.
  --consent [notify,prompt]       - Consent flags, default is notify.
  --start [yyyy-mm-ddThh:mm:ss]   - Start time, default is now.
  --end [yyyy-mm-ddThh:mm:ss]     - End time.
  --duration [minutes]            - Duration of the share, default is 60 minutes.
```

Let me know if this helps.

**Comment by alialpsln** [comment]
Hi Ylianst, 
Thanks for reply. Actually, the problem is how can the agent give its own remote connection to someone else without a server. I thought it could be used because it's a feature like sharing. Maybe I can connect meshctrl.js with an external application (node app), bypassing the authorization stage?

Thank you.

**Comment by Ylianst** [comment]
I would have to think about this... I don't want to create a situation where the solution is not secure.

**Comment by Ylianst** [comment]
Published MeshCentral v0.9.48 with support for self-sharing. You need to enable it on the config.json and only MeshCentral Assistant supports it.

![image](https://user-images.githubusercontent.com/1319013/141230182-96d03c61-c24a-4f06-a46a-7e070b24c346.png)

Feedback appreciated.

**Comment by alialpsln** [comment]
Hello Ylianst,

Great work. I tested it and it works just fine.

This feature is really useful to me. Appreciate for your work. Thank you!

**Comment by Ylianst** [comment]
Thanks, [just posted it on Twitter](https://twitter.com/MeshCentral/status/1458925914268397573).
