### ISSUE TITLE
Files > Drive Connect > Find non-functional Windows 10 21H1

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#3231]
Hi Meshcentral team,

I attempted to us the Find button in Files tab and it doesn't fetch any files even the demo *.txt doesn't work. Is this expected behavior?

Thanks,
SomeGuru

**Comment by nzalev** [comment]
This is a bug. I have submitted a fix for it.

**Comment by Ylianst** [comment]
Outstanding fix by @nzalev. Pull request was accepted and fix will be in MeshCentral v0.9.40.

**Comment by SomeGuru** [comment]
Completed! Closing issue...

-SomeGuru
