### ISSUE TITLE
MeshCMD.exe not connecting to Mesh Central Server for port maps on Linux

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3234]
Mesh Central Server Version:---------0.9.38
Mesh Central Router Version:--------1.8.7960.26198
MeshCMD Version:------------------0.2.1.3
Debian:------------------------------4.19.171-2

NOTE: This instance of MeshCentral Server is behind an Nginx-->Apache-->MeshCentral Server reverse proxy

1. MeshCMD was unable to login to Mesh Central Server at all. Regular and token based logins did not work. In fact the Mesh Central Server Trace showed nothing. Thought well okay maybe it's being held up at the reverse proxy. After inspecting the reverse proxy logs I couldn't even find an attempted connection. 

MeshCMD Debug Output:
```
Settings: {"action":"route","localport":2222,"remotename":"<remote machine name>","remotenodeid":"node//<remote machine node ID>","remotetarget":null,"remoteport":2222,"username":"<Token Username>","serverid":"<Server ID>","serverhttpshash":"<Webserver Cert Hash>","debuglevel":1,"serverurl":"wss://<Webserver domain name>:443/meshrelay.ashx"}
Connecting to <subdomain.domain.tld>.
```

As you can see from the output, It just hangs at "Connecting to <subdomain.domain.tld>". There is no response from the MeshCentral Server Trace logs and there is nothing in the web-server proxy logs suggesting a connection attempt.

Related issue #3218

**Comment by Ylianst** [comment]
To even try fix this, I would need a network capture of MeshCMD and MeshCentralRouterCMD trying to perform port mappings. You can use WireShark to do this. I imagine both MeshCMD and MeshCentralRouterCMD are behind a HTTP proxy on the client side and the problem in that it can't get thru the proxy. Without packet captures, fixing this will be like shooting in the dark.

If you do get packet captures, you can send them privately to me, [my contact info is here](https://www.meshcommander.com/contact-information). Thanks.

**Comment by LPJon** [comment]
@Ylianst None of the clients are behind  an "Internet Proxy". However, The Mesh Central Server is behind a web proxy (As in the documentation for Nginx Proxy). MeshCentralRouterCMD.exe for windows works perfectly. It is only MeshCMD.exe that is having issues both on the windows and Linux versions. My guess is the method in which MeshCMD connects is the problem. I have noticed that MeshCentralRouterCMD.exe connects with "Control.ashx" and MeshCMD.exe is connecting with "MeshRelay.ashx". If you still need packet captures I can try and get them for you but please confirm.

**Comment by LPJon** [comment]
@Ylianst Ok, I just sent you the packet capture with the Contact info you listed above. Please let me know that you received it. It was done with WireShark.

**Comment by Ylianst** [comment]
Thanks. I will take a look at it when I next get a change. I am going to guess that the "Internet Proxy" on the client site is the issue, not anything to do with the server side reverse-proxy. However, I will let you know more details when I get a chance.

**Comment by LPJon** [comment]
@Ylianst There is NOT an Internet proxy. This is directly from my computer to the MeshCentral Server.  No client systems involved at this point. It's still in development. Plus I wouldn't be able to do a clear test if I used a clients network. Near as I can tell by the PCAP is the connection is getting reset.

**Comment by LPJon** [comment]
@Ylianst I sent you the dummy account info

**Comment by Ylianst** [comment]
Thanks. Going to try it shortly.

**Comment by Ylianst** [comment]
Indeed, we can replicate exactly the problem you described... looking into root causing this now.

**Comment by Ylianst** [comment]
FYI. Bryan solved the issue. MeshCMD.exe was not including the `host: server.com` header in the HTTP request. This explains why MeshCMD would not work with reverse proxies. Fix is simple and will be in next version of MeshCentral.

**Comment by LPJon** [comment]
@Ylianst @krayon007  That is great! Looking forward to the next release. Thank you for all of your hard work on this issue. You did a lot in a very short period of time.

**Comment by Ylianst** [comment]
Just confirmed the fix, working on publishing a release now.

**Comment by Ylianst** [comment]
MeshCentral v0.9.41 is out with a new MeshCMD.exe, let me know if that works.

**Comment by LPJon** [comment]
@Ylianst I am seeing the error below:
```
Unable to connect to server: Bad Request (400)
```
This is showing up on both Linux and Windows versions of MeshCMD.exe

**Comment by LPJon** [comment]
@Ylianst @krayon007 If you need another PCAP just let me know.

**Comment by Ylianst** [comment]
??? Let me try is again now. I must have messed up something.

**Comment by LPJon** [comment]
@Ylianst Just sent you a second PCAP on the 400 response error.

**Comment by Ylianst** [comment]
Oh. I see the problem. As a temporary solution, edit "meshagent.txt" and change `serverId` to `_serverId` or remove the `serverId` line and try it again.

It will connect and work, but will stop working when your server's TLS cert is changed... working on a fix now.

**Comment by Ylianst** [comment]
Fixed it. Will be in MeshCentral v0.9.42. That version will use the `serverId` to authenticate the server. The serverID does not change when the server TLS cert is updated, so it's better.

**Comment by LPJon** [comment]
> 
> 
> Oh. I see the problem. As a temporary solution, edit "meshagent.txt" and change `serverId` to `_serverId` or remove the `serverId` line and try it again.
> 
> It will connect and work, but will stop working when your server's TLS cert is changed... working on a fix now.

@Ylianst That worked! Awesome! Can't wait for the next release! Will wait til then to close the issue.

**Comment by LPJon** [comment]
@Ylianst I found the new MeshCMD.exe you just fixed, but where do I find the Linux version?

**Comment by Ylianst** [comment]
You will need to wait for the next release. MeshCMD.exe is generated by the server on-the-fly by merging Javascript code to a MeshAgent.exe for a given platform. The exception is the Windows signed versions that I have to pre-build. This is why, there is no Linux MeshCMD in the `/agents` folder, it's generated on the fly when you download it.

**Comment by Ylianst** [comment]
MeshCentral v0.9.42 is out. Let me know if it works on Windows and Linux.

**Comment by LPJon** [comment]
> 
> 
> You will need to wait for the next release. MeshCMD.exe is generated by the server on-the-fly by merging Javascript code to a MeshAgent.exe for a given platform. The exception is the Windows signed versions that I have to pre-build. This is why, there is no Linux MeshCMD in the `/agents` folder, it's generated on the fly when you download it.

That is awesome to know. I might have some ideas for the Linux version in the near future. I was actually hoping the the Linux version was that way.

**Comment by LPJon** [comment]
@Ylianst Finally! All tests worked perfectly for Windows and Linux versions of MeshCMD.exe. Thanks Ylianst and @krayon007 for your attention to this all this week. You guys are awesome!

**Comment by Ylianst** [comment]
Nice! Thanks for confirming!
