### ISSUE TITLE
Have to restart MC to see new agents

### ISSUE THREAD

**Issue by 12nick12** [Ylianst/MeshCentral#3237]
Hi, when installing new agents via the link I have to restart MC for them to show up. I'm on 0.9.40. 

Anything you'd like from me to figure this out?

**Comment by Ylianst** [comment]
How many agents do you have? One thing I have seen before is that something in front of MeshCentral will limit the number of connections. As a result, agents will connect until the limit is reached and then no new agents will connect. Restarting the server will cause a reshuffling of the agents that can connect and so, new agents will connect but old ones will not.

Check your firewall / router / reverse-proxy / OS for connection limits and raise it.

Let me know if that worked.

**Comment by AntonAndreevichMoroz** [comment]
Do you use recording sessions?  we have such a problem described here #3111

**Comment by 12nick12** [comment]
Yes I have session recording enabled.

**Comment by AntonAndreevichMoroz** [comment]
> Yes I have session recording enabled.

As a test, try turning it off and see if that solves the problem.

**Comment by Ylianst** [comment]
Oh wow. This is interesting! Can you got in "meshcentral-data" and see if there is a file called "mesherrors.txt"? If so, can you post the last few errors in this file? Thanks.

**Comment by K-O-K** [comment]
Hi!, I think I have the same issue.. I just noticed this afternoon that new clients didn't showed up in MC, I thought it was the AV blocking it or something so I left it to check it tomorrow.. later was trying to see if the server could recognize a favicon customization setting in the config.json (something like "favicon": "/path/to-the-favicon-file.ico"), so I restarted the service and while the favicon parameter wasn't recognized, the agents I've installed earlier showed up.
I've checked the mesherrors.txt file but there wasn't anything interesting there.

**Comment by 12nick12** [comment]
I've turned off session recording on another users MC and well see if that fixes it since they were having the same issue.

**Comment by K-O-K** [comment]
Yes, I realized this too, but it's a hard to make: 

Should I leave the recordings on? or, Should I restart the server (and kick out all users) almost each time I add and new agent?

Hope it gets fixed, and if the devs need anything from us to check this out, they just have to say so!

Thanks!

**Comment by openncomp** [comment]
I have session recording enabled and i have the same problem.

**Comment by si458** [comment]
PLEASE FOLLOW #4449
