### ISSUE TITLE
Nginx Set Real IP not working in Untangle Instance

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshCentral#3238]
So I have an odd one that you guys may or may not be able to help with.

I have Meshcentral running on a debian system in docker, much like how I have it running on a few other servers, with NGinx Proxy Manager in front of it handling the reverse proxy side of things. On the other servers, source IPs are reported successfully without issue, and IP filtering functions properly as well. 

I have a new server running this same config, but the debian deployment is running an Untangle Next Gen Firewall system. The distribution is actually an Untangle FW with the normal debian sources added so docker and a few other apps could be installed. 

I was able to get all of my docker services up and running, MeshCentral included, but for some reason, the source IP settings don't seem to get relayed  to MeshCentral. All of the endpoints that connect show up with the docker network gateway IP (172.0.0.1). Is there a set_real_ip setting that can be added to the meshcentral config itself? There's a network layer somewhere that I'm unaware of in this config that isn't relaying the source IPs. Below is my NGINX config

````
#Source IP Settings
set_real_ip_from 172.0.0.1/24;
real_ip_header X-Forwarded-For;
real_ip_recursive on;


#MeshCentral Custom Configs
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

proxy_send_timeout 330s;
proxy_read_timeout 330s;

ssl_certificate_key webserver-cert-private.key;
ssl_session_cache shared:WEBSSL:10m;
#ssl_ciphers HIGH:!aNULL:!MD5;
#ssl_prefer_server_ciphers on;
````

**Comment by Ylianst** [comment]
By default, MeshCentral will ignore a `X-Forwarded-For` HTTP header unless it comes from a trusted source IP address. The two ways you can tell MeshCentral to use `X-Forwarded-For` from a given IP address is to put one of the following lines in `settings` section of the config.json file:

```
    "tlsOffload": "172.0.0.1"
```

or

```
    "trustedProxy": "172.0.0.1"
```

This one will indicate to MeshCentral not to perform TLS on port 443 (since it's being offloaded) but to use `X-Forwarded-For` from `172.0.0.1`. The second line indicates the MeshCentral must do TLS on port 443, but also use `X-Forwarded-For` from `172.0.0.1`.

Let me know if that helps.

**Comment by honestlai** [comment]
Huh... I thought I'd already tried doing  "tlsOffload": "172.0.0.1"... but I decided to give it a shot again and it took!!

Thank you! This makes life MUUUCH easier now that I can more easily log network traffic and selectively block IP ranges

**Comment by honestlai** [comment]
Ugh... I'm sorry, it was working last night and then this morning it's not. I don't know what changed. All of the endpoints in the portal are showing up as 172.0.0.1

below is my config:


```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer   to the user's guide for details.",
   "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
   "settings": {
    "cert": "my.portal.com",
    "CookieIpCheck": false,
    "WANonly": true,
    "LANonly": true,
    "selfupdate": false,
    "noagentupdate": true,
    "WebRTC": false,
    "AllowFraming": "true",
    "_sessionKey": "xxxxxxxx",
    "port": 443,
    "aliasPort": 443,
    "AgentPong": 300,
    "redirPort": 80,
    "redirAliasPort": 80,
    "_ignoreagenthashcheck": true,
    "TlsOffload": "172.0.0.1"

  },
  "domains": {
    "": {
      "title": "Mesh Central Control",
      "minify": true,
      "newAccounts": false,
      "PasswordRequirements": { "min": 8, "max": 64, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "hint": true, "reset": 90 },
      "ManageAllDeviceGroups":["email@gmail.com"],
      "titlePicture": "customlogo.png",
      "_userNameIsEmail": true,
      "certUrl": "https://my.portal.com/",
      "userAllowedIp" : "a bunch of numbers",
      "ipBlockedUserRedirect": "https://www.microsoft.com"
    }

  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "email@gmail.com",
    "names": "my.portal.com",
    "production": false
  }
}

```

**Comment by honestlai** [comment]
I don't know if it matters, but the 172.0.0.1 is the internal docker subnet gateway, 172.0.0.101 is the nginx instance running the reverse proxy.

**Comment by honestlai** [comment]
Alternatively I have my domains setup at cloudflare. When I proxy the server address, everything works correctly, but the severs I monitor then connect and reconnect every 30 seconds to a minute. If I could get these connections to be more solid, then that would work for me.

**Comment by Ylianst** [comment]
Given #3242 is solved, is this one still an issue?

**Comment by honestlai** [comment]
Nope... since cloudflare solves this issue, this ticket is all good. Cloudflare is actually my preferred method for running these portals. I'm super happy right now! 

Thank you!
