### ISSUE TITLE
Changing/Customizing Chime Sound

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#3240]
You know you've developed something great when everyone's asking for new and better features :P 

This is totally extra, but I was wondering, if I wanted to change the chime sound for a connecting/disconnecting endpoint, where would I find that file, or how could I change it? 

I have a few of these portals running where I monitor client servers, but when one goes online/offline, I don't know which portal it's in, so I sometimes have to check all of them.

No major programming changes needed, just wanted to do a simple file swap.

**Comment by Ylianst** [comment]
This is an easy one. There is a system to replace any file of MeshCentral with your own version. The system is made so you can still update MeshCentral, but your custom changes are kept thru the update.

Next to the `meshcentral-data` folder, create a `meshcentral-web` folder and in it, create a `public` and `views` folders. In the public folder, create a `images` and `sounds` folder. Something like this:

```
-- meshcentral-data
-- meshcentral-web
    -- public
        -- images
        -- sounds
    -- views
```

You can then go in the `node_modules/meshcentral/public` and `node_modules/meshcentral/views`, see what files you want to change and place a replacement in the `meshcentral-web` folder at the same place.

So, in your case, you want to replace `public/sounds/chimes.mp3` with your own file.

Once done, restart the server and you should have your own sound. You can do the same for images, etc.

**Comment by K-O-K** [comment]
I can confirm this work for the favicon.ico file. Didn't tried the chime sound tho.

**Comment by Ylianst** [comment]
I tested it for the `chimes.mp3` before posting and it worked for me. Should work for anything in the "views" or "public" folders.

**Comment by Ylianst** [comment]
No confirmation from the original poster?

**Comment by matt-cylanda** [comment]
Hi,

I haven't had time to implement this, but thank you so much for the info. It sound like it should be an easy thing to do.

-Matt

**Comment by matt-cylanda** [comment]
Btw, I finally had time to implement this.

If anyone is looking to do this, keep in mind, the caching in your browser/nginx/cloudflare will mess you up and make you think changes like this are not working. Just fyi.

This is working perfectly for me... thanks again!
