### ISSUE TITLE
Issue: MC behind an AWS Application Load Balancer

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3241]
Hi, I've deployed MC in AWS EC2 instance that sits behind and Elastic Application Load Balance with a valid certificate. I begin to have problems with authentication because by default an AWS ELB it's deployed in two separated AZ with two dynamically assigned private IP's, to so I set up the parameter "cookieipcheck": false in the config file.

Is there any way that MC would be able to recognize the real public IP of the user?
Behind the same ELB I have another service: GLPI, that is able to recognize the real IP of the users.

i think the trusted tls offload parameter maybe would be useful.. but since the private IP of the ELB is dynamically assigned I'm not sure it would work. Can I put in that parameter a whole subnet or VPC CIDR?

**Comment by K-O-K** [comment]
I've just tried the whole VPC CIDR in the "trustedproxy": "X.X.X.X/Z", and the result is the same.. even the agents report different Private IP addresses withing that range (at least 4).
![image](https://user-images.githubusercontent.com/25281984/140243165-b4b4b96e-6bc2-4fcf-8851-d679e413d13d.png)

**Comment by Ylianst** [comment]
Elastic Application Load Balancer needs to give you the client public IP addresses in the HTTP header of the agent connection. Generally, it's a `X-Forward-For` header, but it could be something different.

Go in the "My Server" "Trace" tab and enable tracing of HTTP headers.

![image](https://user-images.githubusercontent.com/1319013/140247864-ccacb340-1548-4f8a-93aa-f0c7a8209f5b.png)

Then, have an agent connect and click on that request. Should be a request to `/agents.ashx` like this:

![image](https://user-images.githubusercontent.com/1319013/140248175-d094b16d-036c-4f0c-8405-6a23a7b629f8.png)

You will see the HTTP header in the data... in this case "host" and other fields. Look to see if the public IP address is present in that data and what name header name is used to give it to you.

**Comment by K-O-K** [comment]
I can confirm that the whole VPC CIDR network in the `"trustedproxy": "X.X.X.X/Z",` parameter worked. It just needed the agents to reconnect (restart the Agent Service) to start showing the real public IP in MC. I've also removed the `"cookieipcheck": false,` parameter and the authentication it's working properly too.
