### ISSUE TITLE
Cloudflare + NGinx + Meshcentral

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshCentral#3242]
I like to use cloudflare for all of my webapps. It's a great platform. But I noticed if I use it with meshcentral, all of the endpoints disconnect and reconnect about every 60 seconds. If you have the systems set with a chime and you have more than 10 systems, it's kind of a recipe for going insane :P

I'm pretty sure this happens because cloudflare loadbalances between 2 IPs when proxy'ing is enabled. Does anyone know how to disable the load balancing, or get the endpoints to only connect to one of the 2 ip's associated when proxied?

**Comment by Ylianst** [comment]
One possibility is that CloudFlare or your NGINX is disconnecting any websocket that is idle for more than 60 seconds. Check the configuration of both to see if you can raise the limit. You can also add these lines in the settings section of the config.json:

```
    "BrowserPong": 50,
    "AgentPong": 50,
```

This will have the server send traffic to the agent and browser websockets every 50 seconds. If that does not work, type instead:

```
    "BrowserPing": 50,
    "AgentPing": 50,
```

This will have the server send traffic to the browser and agent every 50 seconds and have them reply back. Of course, it's much better to find an increase the timeouts in NGINX and CloudFlare than to flood the network with this traffic.

Let me know if that works.

**Comment by honestlai** [comment]
```
    "BrowserPong": 50,
    "AgentPong": 50,
```


It worked!! I've been struggling with this for awhile, I never thought to lower the agent and browser pong that low... (I actually only needed to set it to 90). But so far it's working perfectly!

Thank you!!

**Comment by Ylianst** [comment]
Nice. Do look into placing these values in your NGINX configuration:

```
        proxy_send_timeout 330s; 
        proxy_read_timeout 330s; 
```

See if that helps. That may allow you to increase the MeshCentral "Pongs" to 300 which would reduce your traffic (and hosting costs).
