### ISSUE TITLE
Feature Request - Desktop Tab Screen Pop-Out

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3244]
It would be very nice to have a "Pop-Out" feature for the desktop tab screen window. This would make it easier to work to two systems at the same time without switching tabs or devices in the GUI. I would also like to see the controls go with the pop-out but not sure if that is possible. This feature would be similar to the pop-out feature in most modern web video playback systems/websites

**Comment by cgb** [comment]
Hey @LPJon it's not very discoverable but if you shift-click a device on the My Devices page, it opens in a new Window... Does that meet your needs?

**Comment by LPJon** [comment]
It does suffice, however it would be "nice" to see the pop-out for "ease of use". Still it is nice to know that you can do that. I was unaware of it so it will definitely help.

**Comment by Ylianst** [comment]
I have a video on [12 MeshCentral Tips & Tricks](https://www.youtube.com/watch?v=CmAG6cT1Yv8), that happens to be one of the tricks. I will close this issue, but if you have a specific request for exactly what you want added, please let me know.
