### ISSUE TITLE
Feature Request - Support for Port Relay in MeshCMD for Windows and Linux

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3247]
I need to be able to use MeshCMD as a port relay in Linux. It would also be nice to be able to install this tool into Linux as a service through a command line switch option.

**Comment by si458** [comment]
this is now possible i believe
![image](https://github.com/Ylianst/MeshCentral/assets/765314/3020dfc9-c945-41ea-9159-e4b1ec2e1d78)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/aa12422f-9298-49dd-ac23-83a26d07c4f7)
