### ISSUE TITLE
meshctrl.js DevicePower not working from remote machine

### ISSUE THREAD

**Issue by FelR** [Ylianst/MeshCentral#3248]
When running the DevicePower action in meshctrl.js from a remote machine, the command is confirmed with "ok" but nothing happens, the device won't change its power state. Running the command on the MeshCentral server itself or waking up and shutting down devices using the GUI works flawlessly. 

```
node ./meshctrl devicepower --wake --id "***" --url wss://*** --loginuser "***" --loginpass "***"
ok
```

Other commands like ListDevices work in this configuration. In the log files and using the Trace funtion I can't find any errors messages.

**Comment by Ylianst** [comment]
Ok, I improves `meshctrl.js wake` to return a proper notification of what is going on like this:

```
node meshctrl.js devicepower --wake --id lv1bwKrIYgIXO0uEzkJ0kugLidaUAoEQRvcFvOTgsdsmGTiUsBLH3DW1V3qv00D$
Used 15 device(s) to send wake packets
```

Or this:

```
node meshctrl.js devicepower --wake --id abc
Invalid nodeid
```

This will be in MeshCentral v0.9.45.

**Comment by Ylianst** [comment]
MeshCentral v0.9.45 is out.

**Comment by FelR** [comment]
Always amazing to see your fast response times. Thank you very much!

Unfortunately it still won't work, but thanks to the more detailed output one can see what's going on.

```
node ./meshctrl listdevices --url wss://*** --loginuser "***" --loginpass "***"

Device group: "***"
id, name, icon, conn, pwr
-------------------------
"JrIpyoKtqUIxKSBcg7V6xmU6oSGFr6ziySwKCvcRLViqwYxoFv1bx@cTfYXyu$cr", "***", 1, 0, 0
```

```
node ./meshctrl devicepower --wake --id "JrIpyoKtqUIxKSBcg7V6xmU6oSGFr6ziySwKCvcRLViqwYxoFv1bx@cTfYXyu$cr" --url wss://*** --loginuser "***" --loginpass "***"
Invalid nodeid
```

So despite using the correct node id copied from the listdevices command, meshctrl won't accept it as a valid id, when the device power command is run from a remote machine. When running this command on the mesh central server itself, it works.

My environment:
- MeshCentral 0.9.46 on Windows Server 2019
- MeshCtrl on Ubuntu 20.04

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
I suspect the problem is the $ character in the NodeID. When run on Linux, it will try to replace $c with a value and so, what is passed into MeshCtrl.js is not correct.

Try using single quotes:

```
node ./meshctrl devicepower --wake --id 'JrIpyoKtqUIxKSBcg7V6xmU6oSGFr6ziySwKCvcRLViqwYxoFv1bx@cTfYXyu$cr' --url wss://*** --loginuser "***" --loginpass "***"
```

This is what I use in the help. I am updating my Ubuntu machine now to try it.

**Comment by Ylianst** [comment]
I can confirm, use single quotes will fix the issue.

**Comment by Ylianst** [comment]
@FelR can you close if it worked for you? Thanks.

**Comment by FelR** [comment]
Using single quotes fixes the problem for me, too. Thank you for your help and keep on doing such an amazing work!
