### ISSUE TITLE
Account Security 2FA Notification even when its already configured

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3249]
I think this is a low priority since it's just anoying and doesn't prevent from using the platform.

I've configured MC ver.0.9.44 to require all user to have 2FA enabled with the config.json option:
 `"PasswordRequirements": { "force2factor":true }` and setup up the 2FA using a Google Authenticator like app in my phone. Although it's already set up, the Account Security notification keeps poping up when I hit refresh in the browser. I just click OK and it goes away..and I can use the platform normally.

![image](https://user-images.githubusercontent.com/25281984/140550147-73f534d6-7b25-46ee-9961-0d14f5a8e1dc.png)

How can I help to check what's making that notification show up?

**Comment by Ylianst** [comment]
What you should be seeing when you hit refresh is the notification on the upper right on this screen.

![image](https://user-images.githubusercontent.com/1319013/140589349-84bee3e7-5a91-46dd-9286-245b408cf9ec.png)

Is this what you are seeing?

**Comment by K-O-K** [comment]
HI Yliant,

I don't see that and I've already have the backup security codes set up.

![image](https://user-images.githubusercontent.com/25281984/140589596-c2f4c3c3-3481-4c50-b0fd-f57b4e72e370.png)

What it shows is that message right in the middle of the screen.

https://user-images.githubusercontent.com/25281984/140550147-73f534d6-7b25-46ee-9961-0d14f5a8e1dc.png

What can I do to check this? like I said, it's not a priority because it's just annoying and it really doesn't prevent me from using the platform.

Thanks!

**Comment by Ylianst** [comment]
This is odd. If you have 2FA setup, you should not see that nag dialog. I just tested it on my computer with Google OTP and that nag dialog does not show. Let me know that a bit, I have not seen this before.

**Comment by K-O-K** [comment]
What info should I provide for you to check it? the only "weird" thing I see is that I have `"userNameIsEmail": true,` but the user is not a email address because it was created before setting that option in the config.json file.

**Comment by Ylianst** [comment]
How does this message not stop you from using the platform? When you click on a device, does it not show the dialog and not go to the device? If it does go to the device, this is very odd.

Also, can you open the browser's console and see if there are any error messages?

Thanks,
Ylian

**Comment by Ylianst** [comment]
Ok, fixed a possible timing issue and could cause this. Will be in v0.9.45.

**Comment by PetieM** [comment]
I was also seeing this (usually after a server restart but also when refreshing) but it looks like your v0.9.45 fix may have worked because I just did both and did not get the 2FA prompt.

**Comment by K-O-K** [comment]
Like PetieM said, since this last update I haven't seen this anymore, so it seems like that timing issue solved it!
Thanks Ylian!

**Comment by Ylianst** [comment]
Nice. Yes, this was a timing issue when the page loads, glad it's fixed.
