### ISSUE TITLE
more settings to be saved in config.json

### ISSUE THREAD

**Issue by UnP1u9** [Ylianst/MeshCentral#325]
Hey, Just update to the latest version but lost most of the changes done on the meshcore.

like i had changed below 

var pr = require('message-box').create('MeshCentral', this.httprequest.username + ' requesting KVM Access. Grant access?', 10);

to something 

var pr = require('message-box').create('Office 1', this.httprequest.username + ' Want to Take Remote Access. Grant access? Yes/No', 10);

if we can add more setting like this to config.json or any other option to retain these kind of modification after an update like git etc.

Any idea would be helpful :)

**Comment by Ylianst** [comment]
So, there is an undocumented trick where if you put "meshcore.js" in "meshcentral-data", that file will be used first before the one in the "/node_modules/agents". This way you can keep updating the server without having your changes over written. Of course, you don't get the latest version of the meshcore.js file unless you merge the changes yourself from time to time.
