### ISSUE TITLE
Silent Recording

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3250]
Is there a way to set Session Recordings without the red notification dot icon for specific users, devices, group users and group devices? 

The Idea is that if Session Recording is enable specific users, devices, group users and group devices the red Recording Icon doesn't show up so the user doesn't know it's being recorded.

The other thing is that, to my knowledge, it only possible to set Session Recording for `SelectedDeviceGroups`.. so, it would be great to be able to choose specific devices too and not only the whole Device Group.

Thanks!

**Comment by Ylianst** [comment]
Currently no way to record without the red dot.

You can set recording per-user:

![image](https://user-images.githubusercontent.com/1319013/140589467-bf1ec0a1-c722-42b0-b1ee-632a07387d7c.png)

Or per-user group

![image](https://user-images.githubusercontent.com/1319013/140589521-d297d7c9-6a69-45fb-82b2-8c37de02772c.png)

But to activate this, add the "onlySelectedUsers", "onlySelectedUserGroups" and "onlySelectedDeviceGroups" in the "SessionRecordings" section:

```
      "SessionRecording": {
        "onlySelectedUsers": true,
        "onlySelectedUserGroups": true,
        "onlySelectedDeviceGroups": true,
        "filepath": "C:\\temp",
        "index": true,
        "protocols": [ 1, 2, 100, 101, 200 ]
      }
```

**Comment by K-O-K** [comment]
Hi Ylian,

It would be great to be able to choose specific Devices too and not only the whole Device Group.

Thanks!

**Comment by K-O-K** [comment]
Also, for some users or for specific servers, it would be nice to be able to Record every session without the user know it.

Thanks again!

**Comment by Ylianst** [comment]
So, you want to be able to select specific user-device pairs for recording and for each user-device pair if the recording should show or not?

**Comment by K-O-K** [comment]
Sorry I mixed up two topics kind of related.

- The first one is to be able to set recording per devices too:

```
SessionRecording": {
        "onlySelectedUsers": true,
        "onlySelectedUserGroups": true,

        ****"onlySelectedDevices": true,****

        "onlySelectedDeviceGroups": true,
        "filepath": "C:\\temp",
        "index": true,
        "protocols": [ 1, 2, 100, 101, 200 ]
      }
```

- The second is: to be able to record sessions silently (without the red dot icon showing up). Perhaps using check boxes, keeping all options and combinations possible, per Users, per UserGroups, per Devices, per DeviceGroups.

**Comment by Ylianst** [comment]
So per-device recording, when enabled would record all sessions for that device regardless of what user is using it?

**Comment by K-O-K** [comment]
> So per-device recording, when enabled would record all sessions for that device regardless of what user is using it?

Yes.. that´s correct! No matter what user is using it or to what DeviceGroup belongs!

**Comment by OutbackMatt** [comment]
> > So per-device recording, when enabled would record all sessions for that device regardless of what user is using it?
> 
> Yes.. that´s correct! No matter what user is using it or to what DeviceGroup belongs!

I expect that this would illegal in many jurisdictions

**Comment by K-O-K** [comment]
Why? I'm giving a user access to our devices and servers and I want to register what they're doing. It's something needed for audit.

I don't know if the request wasn't clear.. the idea is to be able to record REMOTE USER SESSIONS without the remote user knowing that he's being recorded... in any way the request is to be able to record a device local usage (when no one is connected to it).

**Comment by OutbackMatt** [comment]
> Why? I'm giving a user access to our devices and servers and I want to register what they're doing. It's something needed for audit.

Then why not tell them that the sessions are being recorded before they start using them?

This may well be legal where you live, but I'd certainly expect that here (Australia), and certainly in Europe, that recording sessions without knowledge or consent would be illegal, and would result in hefty fines and many civil law suits. Honestly, I'd also expect that someone who silently records here would also get gaol (jail) time.
