### ISSUE TITLE
Playback Recording on Streaming

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3251]
Hi,

Is there a way to playback a recording from the website without having to download the recording and then uploading it to the player?

I have MC in a cloud service and having to download to upload it again generate Data Transfer costs, the idea is that from the recording list be able to just click the recording it and start's playing it without even asking to download a file or anything.

Thanks!

**Comment by Ylianst** [comment]
No streaming right now, but note that you don't need to "upload it again". The player will open and play the .mcrec file completely locally, it's not uploaded to the server and so, in theory you could save the web page and play the .mcrec offline. So, your hosting costs is only one download (no upload).

**Comment by Ylianst** [comment]
Worked on adding support for streaming in the MeshCentral session player, it will be in MeshCentral v0.9.47. Uses websocket to pull 100k blocks at a time as needed during playback.

![MC2-MCRECStreaming](https://user-images.githubusercontent.com/1319013/140688434-59a3954e-6c4c-4372-b11d-d048d9d00d45.png)

Once published, let me know if it works.

**Comment by Ylianst** [comment]
MeshCentral v0.9.47 is published.

**Comment by K-O-K** [comment]
Thanks Ylian, I confirm the streaming is working! Thanks again!
