### ISSUE TITLE
Filters in My Events Tab

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3252]
Hi,

I think it would be useful to have the option to filter events in My Events Tab.. I imagine something like, in the same bar where the Show Last is, having the option to filter by event type (meaning the type of event like: change device, started/ended session, processing command), by user, by device, etc.

Thanks!

**Comment by si458** [comment]
this is already possible now
<img width="376" alt="image" src="https://github.com/user-attachments/assets/d7675f3b-79ee-49ef-b587-d41a20ae2969">
