### ISSUE TITLE
Missing info in Events

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3253]
Hi,

When I send a Power off Operation Action to a device.. in My Events and the Device Events the event doesn't say what user send the action.

Is it possible to show in the Event record who sent the action?

Thanks?

**Comment by Ylianst** [comment]
Just put in a fix for this. Will be in MeshCentral v0.9.45.

**Comment by K-O-K** [comment]
Thanks Ylian, I can confirm this is working.
![image](https://user-images.githubusercontent.com/25281984/140614420-3c2f8747-ce3e-481f-86b7-516ea75979cd.png)
