### ISSUE TITLE
Start Linux/Windows Terminal Session in a predefined path or in the root of the volume

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3258]
Hi,

Is there a way to always start a Linux Terminal Session in a specific path? Some option where we can set the path or if easier always start at the root disk `C:\` for windows and `/` form Linux?

Thanks!

**Comment by PetieM** [comment]
For Linux/Darwin/FreeBSD, you can customize the launch command in the config.json file. For instance:
```json
"linux": "cd /\nclear\n"
```

That would automatically switch you to / (and then clear the screen so you don't see the cd command execute every time) on Linux machines. I'm not sure if the same configuration is currently possible in Windows though I don't imagine it would be terribly difficult to add if it's not.

**Comment by K-O-K** [comment]
Hi @PetieM, Thanks for you reply,

I don't have a 
> terminal config section under domains

So, I don't know where to put `"linux": "cd / \nclear\n",`.

Could you please elaborate a little further about this section? or maybe point me in the direction of some other issue or documentation where I can learn more about it.

Thanks again!

**Comment by AntonAndreevichMoroz** [comment]
> Hi @PetieM, Thanks for you reply,
> 
> I don't have a
> 
> > terminal config section under domains
> 
> So, I don't know where to put `"linux": "cd / \nclear\n",`.
> 
> Could you please elaborate a little further about this section? or maybe point me in the direction of some other issue or documentation where I can learn more about it.
> 
> Thanks again!

https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json here is the complete config schema.  there you can find the terminal and the launchCommand subsection in the domain section

**Comment by PetieM** [comment]
You can also find it in the advanced sample config at node_modules/meshcentral/sample-config-advanced.json.

**Comment by K-O-K** [comment]
Thanks, @PetieM  and @AntonAndreevichMoroz,

I got it working with Linux Machines adding this configuration in the `"domains":` section of the config.json file:
```
"terminal": {
	"linuxshell": "any",
	"launchCommand": {
		"linux": "cd /\nclear\n",
		"_darwin": "clear\necho \"Hello MacOS\"\n",
		"_freebsd": "clear\necho \"Hello FreeBSD\"\n"
	}
}
```

> I'm not sure if the same configuration is currently possible in Windows though I don't imagine it would be terribly difficult to add if it's not.

Anyone knows if it's possible to do this with Windows Machines Terminal Sessions? If it's not, hopefully gets added!

**Comment by K-O-K** [comment]
Hi @Ylianst, maybe you can take a look at thins to see if something could be done about setting a starting path for Windows Terminal Sessions.

Thanks!

**Comment by si458** [comment]
closing as stale, this wont be implemented sorry
