### ISSUE TITLE
Search by computer name

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3260]
Until the recent big update of the search bar, the search immediately searched for both the name and the real name of the computer. Now the real name is searched only if the display is switched to real names. Is it possible to revert the old behavior so that the default happens over two names?

**Comment by Ylianst** [comment]
Just added this. So not to confuse people that have lots of devices and need an exact match, you will need to add this line in the domain section of the config.json:

```
"DeviceSearchBarServerAndClientName": true,
```

This will be in the next release, MeshCentral v0.9.47.

**Comment by Ylianst** [comment]
MeshCentral v0.9.47 is published.

**Comment by AntonAndreevichMoroz** [comment]
And that works too. Thanks.
