### ISSUE TITLE
Mac OS clone problem

### ISSUE THREAD

**Issue by Electricity2015** [Ylianst/MeshCentral#3261]
Hi, 
After cloning i see both laptops as one pc in meshcentral.
What to do?
Thanks!

**Comment by VINISHVV** [comment]
Please install the new agent on both PC.

**Comment by Electricity2015** [comment]
I don't have fizical access.
How can i do it remote on MAC OS?

**Comment by Ylianst** [comment]
The  MeshAgent has an anti-cloning feature that looks at the MAC address of the computer. If all of them are different, the MeshAgent should re-generate a new certificate and show up as a different computer. You can also delete the "meshagent.db" file and restart the agent to force creating a new computer.

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.20 and also use node 18 or above,
if issue persists after this, please reply back
