### ISSUE TITLE
Windows Security Center

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#3263]
Hi,
first thank you for your work!
I have read about Windows Security Center in the blog.
How can I turn on this option? I could not find anything in Docu.
Thanks!

**Comment by Ylianst** [comment]
It's always turned on. For Windows devices that have the Windows Security Center, you should see it here.

![image](https://user-images.githubusercontent.com/1319013/140795773-ca8906f5-6392-4dc1-a82b-c0d495185e43.png)

**Comment by johann8** [comment]
I only have Windows Server. 
Probably the server versions of Windows are not supported. 
That is why I do not see this.

![grafik](https://user-images.githubusercontent.com/13717874/140799095-9e5f58d4-cbec-4365-be83-05f9f6c82d2b.png)

**Comment by Ylianst** [comment]
That is correct. Windows Server does not include Windows Security Center.
