### ISSUE TITLE
Feature Request: Pre-configured Remote Input

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3264]
We would like to see the ability to add preconfigured most frequently used inputs to the remote input. I see it this way. In the configuration, we write the name and the text that will be transmitted.

```
  "domains": {
    "": {
      "PreconfiguredRemoteInput": [
        {
          "name": "Name1",
          "value": "https://help.mycompany.com/"
        },
        {
          "name": "Name2",
          "value": "Any text"
        },
        {
          "name": "Name3",
          "value": "Default welcome text"
        }
     ]
  }
```

And then when you right-click on "Remote Input" options are shown.  And when this option is selected, the remote input is sent to the remote machine without an additional query window.
![image](https://user-images.githubusercontent.com/51225180/140797338-4b9f8a38-87be-418c-820f-baeccda5847f.png)

**Comment by Ylianst** [comment]
This is an interesting request. Working on it now.

**Comment by Ylianst** [comment]
The feature is done exactly as required. Use \r in the configuration for carriage return key. This will be in MeshCentral v0.9.47. Working in publishing it now.

![MC2-PreDefinedStrings](https://user-images.githubusercontent.com/1319013/140812412-b35c39d2-f2f8-4734-ba1a-04f124783b80.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.47 is published.

**Comment by AntonAndreevichMoroz** [comment]
Oh, how fast. Thanks for what you are doing. Everything works exactly as intended.

**Comment by K-O-K** [comment]
Hi @Ylianst ,

I was looking at [https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json) about this new feature and I don't understand the `"protocol"` part:

![image](https://user-images.githubusercontent.com/25281984/140860430-58e6e0f2-9799-409f-b07e-b08c6fb3ea39.png)

Could you please clarify that for me a bit?

Thanks!

**Comment by Ylianst** [comment]
Good catch! My mistake, it should be "value", not "protocol". I will fix it now.

**Comment by Ylianst** [comment]
Ok, fixed it.

**Comment by Ylianst** [comment]
FYI, Made an improvement on this. Each user can now configure their own strings in addition to the server defined ones.

![FD9S7YiVUAElRuN](https://user-images.githubusercontent.com/1319013/141594614-f391815b-3113-476b-a4f0-1aeeeddf4309.png)

**Comment by K-O-K** [comment]
This is awesome!! I thought about something like this when I read this post a few day back but I thought it was too much trouble so I didn't asked.

One of the use cases I'm thinking is: per user Windows Servers Login Credentials, after sending Alt - Crtl - Del, right click to type the saved password there..

Thanks Ylian!
