### ISSUE TITLE
Meshcentral installation

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3265]
Hi Yilian,

How to deploy mesh central on windows server 2019 to use on the internet as wan mode via domain name not locally, is there any certificate needed to deploy?

**Comment by Ylianst** [comment]
Your question is not clear, are you talking about a TLS certificate for the web site?

To install MeshCentral, you can take a look at the Installation and the User's Guides located on the [top right of the page here](https://meshcentral.com/info/downloads.html).

Also, there are videos that can help:

- [MeshCentral Installation](https://www.youtube.com/watch?v=GsQbWZmRRAU).

In 2 days I have a new video on [Let's Encrypt](https://www.youtube.com/watch?v=a4F1ayu7XWo) that can help if your looking to get a free TLS certificate.

**Comment by sysadmin-us** [comment]
@Ylianst  I want to install mesh central in a wan mode on the windows server and want to access the server through the internet not locally.

**Comment by K-O-K** [comment]
Hi @sysadmin-us ,

Please watch that video and the other videos in the MeshCentral YouTube Channel, they are really helpful and help you understand the different modes of operations and how you setup the MeshCentral server.

_Hint: You need to change the configuration via the config.json file. You can take a look at this link for a more comprehensive list of options available:_ [https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json)

**Comment by Ylianst** [comment]
I have a [YouTube video on LAN, WAN and Hybrid modes here](https://www.youtube.com/watch?v=gx5Fh3pQOns).

For WAN mode, set a name for your server and set "wanonly":true in the settings section of the config.json:

```
"settings": {
  "cert": "name.sample.com",
  "wanonly": true
}
```
