### ISSUE TITLE
Problems with AutoBackup and with MeshCentral Update

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3266]
Hi,

I think I've discovered two problems that almost cost me my whole MeshCentral installation.

1- The autobackup feature should exclude the Backup folder specified in the config.json file:
    I activated this options in the config.json file: 

```
			"autoBackup": {
			"mongoDumpPath": "/usr/bin/mongodump",
			"backupIntervalHours": 12,
			"keepLastDaysBackup": 15,
			"zipPassword": "MySecretPassword123",
			"backupPath": "/home/ec2-user/meshcentral-data/Backups/"
```

Came back a few hours later to find a a full disk ( it was like 8GB free when I letf it), I grew up the volume, extended the partition without giving it too much thought. Some hours after that I tried to update MeshCentral to the last available version from the GUI and the process failed badly, deleting somethings and leaving a broken installation because the Disk was full again. I tried to recover from a backup, but all of them were corrupted. Thankfully I had a snapshot so I was finally able to recover from there.

I then realized my mistake, since my BackupPath was inside the meshcentral-data folder, the backup process was in a kind of loop where it was saving in the ZIP what was already backup and so on.

2- The update needs to check the disk space available before it starts the backup process to avoid something like that from happening.

Thanks!

**Comment by Ylianst** [comment]
Oh wow, that is not something I would have ever tried. I will add checks for this.

**Comment by Ylianst** [comment]
Just pushed in a fix for your first issue. Will now display this error:

![image](https://user-images.githubusercontent.com/1319013/140885445-b6232492-2d8f-436b-b776-e22a5e917051.png)

**Comment by K-O-K** [comment]
Thanks Ylian, awesome response time as always.

Couple of thoughts, I think that it should still make the backup but excluding the folder from the backup. In the case its too much trouble to make it that way, I think that the warning should be an annoying notification popup, so it's visible from wherever you are in the GUI and it doesn't go away until it's fixed.

Another issue related to Backups is that I had a few days without backups now.. after checking everything for a couple of days, I discovered by guessing, because it didn't showed up in a log or anywhere I could tell, that it was the filesystem permissions of the path I was giving in the config.json file. I think this should be logged in mesherrors.txt or some place else.

Thanks Again!

**Comment by Ylianst** [comment]
All good suggestions.

**Comment by si458** [comment]
backups should now all be working correctly, plz try the latest version and if issue still happens plz reply back
