### ISSUE TITLE
MaxInvalidLogin - IP is not blocked

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#3268]
Hey,
what am I doing wrong? Under "settins" section I have set the following:

```
"MaxInvalidLogin": {
   "time": 3,
   "count": 3,
   "coolofftime": 10
},
```

In the log file I see this:
```
Nov 10 15:19:45 meshcentral https[150]: Accepted password for ksahnjuk from 188.63.xx.113 port 46788
Nov 10 15:19:59 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 46890
Nov 10 15:20:7 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 46902
Nov 10 15:20:17 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 46968
Nov 10 15:20:28 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 47012
Nov 10 15:20:37 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 47028
Nov 10 15:20:46 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 47028
Nov 10 15:20:55 meshcentral https[150]: Failed password for ksahnjuk from 188.63.xx.113 port 47130
```

But the IP is not blocked.
I have the version 0.9.47. Fail2ban works. 
Thank you very much for your help!

**Comment by Ylianst** [comment]
Taking a look at this now.

**Comment by Ylianst** [comment]
Your right, thanks for reporting this. Will be fixed in MeshCentral v0.9.48.

**Comment by Ylianst** [comment]
As a side note, you can use the "badlogins" command in the server console to see the status of invalid logins.

![image](https://user-images.githubusercontent.com/1319013/141176281-8bcef6d3-b289-44da-929f-ec9504716882.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.48 is out, let me know if it works.

**Comment by johann8** [comment]
Hey,
I just built a docker image with Meshcentral version 0.9.49 and updated containers. Now the IP block works and on the console I can also see badlogins attempts with the IP .

Thanks a lot for the quick fix!

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back the closing the issue.
