### ISSUE TITLE
Mesh Central failing to start after upgrade to 0.9.48

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#3270]
Just upgraded to 0.9.48 and get hit with the following:

MeshCentral HTTP redirection server running on port 80.
Error: Command failed: "mongodump" --uri="mongodb://127.0.0.1:27017/meshcentral" --archive="nul"
'"mongodump"' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"mongodump" --uri="mongodb://127.0.0.1:27017/meshcentral" --archive="nul"'
}
WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed.
MeshCentral v0.9.48, WAN mode.
ERR: C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751
                if ((typeof obj.config.settings.autobackup.backuppath == 'string') && (obj.path.normalize(obj.config.settings.autobackup.backuppath).startsWith(obj.path.normalize(obj.datapath)))) {
                                                           ^

TypeError: Cannot read property 'backuppath' of undefined
    at AsyncWrap.<anonymous> (C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751:60)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14)
Error: Command failed: C:\Program Files\nodejs\node.exe C:\Program Files\meshcentral\node_modules\meshcentral --launch 11096
C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751
                if ((typeof obj.config.settings.autobackup.backuppath == 'string') && (obj.path.normalize(obj.config.settings.autobackup.backuppath).startsWith(obj.path.normalize(obj.datapath)))) {
                                                           ^

TypeError: Cannot read property 'backuppath' of undefined
    at AsyncWrap.<anonymous> (C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751:60)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Program Files\\nodejs\\node.exe C:\\Program Files\\meshcentral\\node_modules\\meshcentral --launch 11096'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...

mesherrors.txt shows the following:

C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751
                if ((typeof obj.config.settings.autobackup.backuppath == 'string') && (obj.path.normalize(obj.config.settings.autobackup.backuppath).startsWith(obj.path.normalize(obj.datapath)))) {
                                                           ^

TypeError: Cannot read property 'backuppath' of undefined
    at AsyncWrap.<anonymous> (C:\Program Files\meshcentral\node_modules\meshcentral\meshcentral.js:1751:60)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14)

Looks like it's related to the autobackup path. How do I get this to stop?

**Comment by Ylianst** [comment]
Oh dear. I have not changed that part of the code in a while and my server that uses MongoDB updated correctly. I will investigate ASAP.

**Comment by Ylianst** [comment]
Is it possible you ran out of disk space? Run:

```
npm cache clean --force
```

That should clear a lot of space.

**Comment by asasin114** [comment]
It seems I got it fixed by installing the MongoDB Tools and setting up the mongodump.exe parameters which I haven't had until now. Crisis averted! Whew!

**Comment by Ylianst** [comment]
Oh good! I am going to test this case again to make sure the server survives. Thanks for reporting back, that would have kept me up tonight.

**Comment by asasin114** [comment]
Not sure why I didn't catch it before I posted the issue... Too much time trying to fix a dead directory server, SharePoint server and Sage server DB I guess... :P

As always, thank you for the blazing fast replies. The support here is what keeps me around along with this incredibly solid product!

**Comment by Ylianst** [comment]
Just put in a fix for this and publishing v0.9.49 right now, this could happen to others.
