### ISSUE TITLE
port map file

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#3272]
Hi,
Is it possible to automatically load the port maps file when starting Router?
That would be very helpful.

Thank you

**Comment by Ylianst** [comment]
Yes. To save mappings, you can click the 3 bars and select "Save Mappings..."

![image](https://user-images.githubusercontent.com/1319013/141349896-76d769a1-8fd6-46b3-ac45-0390516fdca1.png)

You load them back, you can associate the ".mcrouter" file type to MeshCentral Router so when you click on the file it will automatically open and have the mappings. You can also drag & drop the .mcrouter file into MeshCentral Router.

Let me know if that works.

**Comment by johann8** [comment]
Thank you very much for the quick reply. 
Yes, that has always worked. This way you always have to log in to the router. If you start the router from the website, then you do not have to log in. But the port mappings are not there. 
I thought, there is a solution when calling router via web page, the port mappings file is loaded automatically. So you save the login at the router.

**Comment by Ylianst** [comment]
If you edit the .mcrouter file with a text editor, you will see something like this:

```
{
  "hostname": "central.mesh.meshcentral.com",
  "username": "admin",
  "certhash": "024034CF687324E64A41CE2A17467BCDE70FB2AE2F1C97EDDE0B6C1764096D18077FBE64FBA129510959C5BB81DBA09B",
  "mappings":[
    {
      "nodeName": "GL-AR750",
      "name": "WebPage",
      "meshId": "mesh//7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c",
      "nodeId": "node//HLZYZn3@8Jv1zURGCpFE41QtGqY6w2mW1wiitB1tRMjFFfq@HgpSfjm8wsO9PsAo",
      "appId": 1,
      "protocol": 1,
      "localPort": 49356,
      "remotePort": 80
    }
  ]
}
```

You can manually add the password like this:

```
{
  "hostname": "central.mesh.meshcentral.com",
  "username": "admin",
  "password": "mypassword",
  "certhash": "024034CF687324E64A41CE2A17467BCDE70FB2AE2F1C97EDDE0B6C1764096D18077FBE64FBA129510959C5BB81DBA09B",
  "mappings":[
    {
      "nodeName": "GL-AR750",
      "name": "WebPage",
      "meshId": "mesh//7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c",
      "nodeId": "node//HLZYZn3@8Jv1zURGCpFE41QtGqY6w2mW1wiitB1tRMjFFfq@HgpSfjm8wsO9PsAo",
      "appId": 1,
      "protocol": 1,
      "localPort": 49356,
      "remotePort": 80
    }
  ]
}
```

When, when you double click on your .mcrouter file, it will open MeshCentral Router and auto-login. Let me know if that works for you.

**Comment by johann8** [comment]
Perfect! It works! Thanks a lot!
