### ISSUE TITLE
Idle / Active indicator

### ISSUE THREAD

**Issue by Matt-CyberGuy** [Ylianst/MeshCentral#3277]
Hi,

This is a request from one of our clients that uses our portal to occasional manage his office's systems. But is there a way to show an indicator or know if a system is active, or how long it's been idle? I think he's trying to track down a bug in a software suite his office uses, but it only seems to occur after a certain amount of idle time.

-Matt

**Comment by Ylianst** [comment]
Hi. If you mean "Active" as in, the agent is connected. You can see the device light up and there are lines showing the last 7 days of connection. If you hover over the bars, you can see the exact time.

![image](https://user-images.githubusercontent.com/1319013/141589671-a24293c9-a9dd-4161-8eca-1d7b673cb75f.png)

If active means someone logged in? Os CPU state? Or someone moving the mouse/keyboard? - Thanks.

**Comment by matt-cylanda** [comment]
Sorry, I should've been more specific. What they are looking for is if the user is active, or if the system has been sitting idle with no movement of the mouse or keyboard.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ylianst** [comment]
Ok, so mouse and keyboard activity.

**Comment by matt-cylanda** [comment]
Yes, basically

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
