### ISSUE TITLE
MeshCommander remote desktop disconnection - try RLE8

### ISSUE THREAD

**Issue by mrt595** [Ylianst/MeshCentral#3279]
Trying to remote desktop into a new Dell Optiplex 7090 I get the following error:

"KVM disconnection, they may indicate that Intel AMT is unable to capture the display (Try RLE8 encoding), or unsupported GPU."

I tried RLE8, no joy.  No addon GPU, just the built-in.  Tried it with no monitor, tried it with an old VGA, no difference.  Tried restarting to BIOS and connecting.  Still no joy.

This machine is physically connected to an AD network, but not yet joined.  This is standard practice for us.  vPRO is configured and the device is shipped to its destination and connected to the local LAN.  After it picks up an IP address the rest of the configuration is done via vPRO RD.

See attached log file.

[meshlog.txt](https://github.com/Ylianst/MeshCentral/files/7539716/meshlog.txt)

**Comment by Ylianst** [comment]
Looking at the log, MeshCommander does everything ok and the device closes the connection suddenly.

```
--- AUTHENTICATION PART
REDIR-CONNECTED
REDIR-DSEND(8): 100100004B564D52
REDIR-RECV(13): 1100000001000F005701000000
REDIR-DSEND(9): 130000000000000000
REDIR-RECV(10): 14000000000100000004
REDIR-SEND(41): 1300000004200000000561646D696E0000132F5265646972656374696F6E5365727669636500000000
REDIR-RECV(87): 14010000044E000000274469676573743A463837463546394334363746443233423745373533393034354332323142383120773832344357753041674141414141414C70616C6C4A487662786A6B4461386B0461757468
REDIR-SEND(188): 1300000004B30000000561646D696E274469676573743A463837463546394334363746443233423745373533393034354332323142383120773832344357753041674141414141414C70616C6C4A487662786A6B4461386B132F5265646972656374696F6E536572766963652033363966373738663432646231663965323631346164313863623466313163350830303030303030322039323163623232383432393161306638306231363930366237383133396131660461757468
REDIR-RECV(9): 140000000400000000
REDIR-DSEND(8): 4000000000000000
REDIR-RECV(8): 4100000000000000

--- VNC / RBF PART
REDIR-RECV(12): 524642203030342E3030300A           <---- RFB 004.000
REDIR-SEND(12): 524642203030332E3030380A           <---- RFB 003.008
REDIR-RECV(3): 020180                                                 <---- Security
REDIR-SEND(1): 01                                                         <---- Return no security since we are already authenticate
REDIR-RECV(4): 00000000                                              <---- Got the OK, everything is file
REDIR-SEND(1): 01                                                         <---- Indicate we want to share the desktop
REDIR-CLOSED                                                               <--- Intel AMT suddenly closes.
```

Nothing MeshCommander could do. Is you device Intel AMT or Intel Standard Manageability? Intel SM does not support KVM. The other option is that this computer has a CPU that does not support KVM. In any case, this platform does have some issue that completely prevent KVM from working.

**Comment by mrt595** [comment]
It's AMT with a Core i5-10505, and KVM is supported and turned on.  I have verified this.

I am going to try resetting vPro and, if that fails, open a ticket with Dell.

**Comment by Ylianst** [comment]
Do let me know what happens and also feel free to point Dell to the analysis above if you open a ticket with them.

**Comment by mrt595** [comment]
Will do.  They said that they were going to replace the motherboard and CPU as I can't even access BIOS via KVM.  But I just got a notice that the parts are delayed and I don't have an ETA yet on when they will be available.  I will let you know what happens after the swap.

**Comment by mrt595** [comment]
Dell replaced the CPU - no joy.

Then they replaced the motherboard not once, not twice, but three times before they got one that actually worked.  I don't mean one that fixed the issue (although the last one did), I mean one that would even let the system POST.

So far, that seems to have fixed the issue.  It's been 4 days without issue.
