### ISSUE TITLE
Feature Request - Agent for android box

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#3280]
The agent app for regular android cellphone is awesome even if it has lmited access, however would it also be possible to install it on android boxes , where normally there is no camera to use to scan the qr code? Thanks.

**Comment by Ylianst** [comment]
If the device has no camera, select "Manual Server Setup" in the Android agent and paste the link from the QR code that starts with "mc://".

![image](https://user-images.githubusercontent.com/1319013/141867338-103538eb-8833-4e3e-ba9e-914839fbdfe2.png)

You can get the link by going to the MeshCentral web site and right click on the QR code and saving the link.

Once the MeshAgent is installed on the Android device, you can also navigate to the web page on the device and click on the "mc://" link, that should bring up MeshCentral Agent and set it up.

Let me know if that works.

**Comment by RJ087** [comment]
I just plugged a webcam into mine and scanned the QR code.

**Comment by lexisman** [comment]
> I just plugged a webcam into mine and scanned the QR code.

Can you share what brand of webcam are you using? Thanks.

**Comment by RJ087** [comment]
its a older Microsoft webcam and its several years old, Its just what i had at the time and it worked.

My android tv box is 3-4 years old with the Amlogic S905 board.

**Comment by lexisman** [comment]
@Ylianst , I am still trying to figure out how to do it since android box normally has no app to copy and paste, I tried to just type the link into the app, but its too long that I tries 2x and still I am making a mistake during typing. I will try it again maybe using the suggested app to copy and paste the link.

**Comment by Ylianst** [comment]
Once the mesh agent in installed, browse to your MeshCentral server, login and tap on the QR code from within the browser on the Android device, that should open the mc:// link and get the server setup.

Usually cut & paste on Android involves pushing and holding over text, but I am sure that changes from device to device.

**Comment by Meloman-zz** [comment]
How can we modify the mc://[server-address],1234abcd... ? Because I have got mc://meshcentral,1234abcd...
