### ISSUE TITLE
AutoBackup with AWS MariaDB RDS

### ISSUE THREAD

**Issue by K-O-K** [Ylianst/MeshCentral#3283]
Hi,

I recently migrated the database from MongoDB to an AWS MariaDB RDS, the migration process worked as expected with the exception of the historic data that wasn't included in the export, I guess that behavior is normal.

The issue I'm facing is with the DB dump due to a limitation on the RDS user permissions:

```
>autobackup

Starting auto-backup...

Auto-backup completed without MySQL/MariaDB database: Error: Command failed: "mysqldump" --user='MARIADB-USER' --password='MySecretPassword' -h RDS-ENDPOINT.rds.amazonaws.com -P 3306 DBName --result-file="/my/backup/path/mysqldump-2021-11-17-15-26.sql" 

mysqldump: Got error: 1044: "Access denied for user 'MARIADB-USER'@'XX.XXX.XXX.%' to database 'DBName'" when using LOCK TABLES

```
 But there's a [workaround](https://stackoverflow.com/questions/19571021/rights-needed-to-flush-and-lock-tables-in-rds-mysql-db):
to pass the  `--single-transaction`  parameter to the mysqldump command. 

if I do that in the Linux command line it creates the dumpfile without any problems.

I'm not a DB expert by any means, so I'm not sure of the implications of doing the Dump with that additional parameter, I just know it works  for me in the sense that it creates the .sql file, and for a MariaDB RDS I don't see any other alternative... 

So I'm thinking that there could be an additional option in the Settings section of MeshCentral config.json file inside `"mariaDB":{ ... }` ... something like `"awsrds": true,` (false by default) where if the parameter is set to true, the AutoBackup will pass the `--single-transaction` to the dump command line process.

Also, I suppose that this warning is due to that same thing since the mysqldump do exist:

![image](https://user-images.githubusercontent.com/25281984/142281022-3cbd976a-a340-49b9-9fd4-f281d69eee90.png)

Thanks!

**Comment by nzalev** [comment]
The error message is generic. It will be used regardless of the type of failure.

I am not too familiar with AWS RDS, but I took a look at the aws RDS docs, and they include --single-transaction for their DB dumps. I think your suggestion on adding a config options it a good one. I will put in a pull request for this before the end of this weekend, if not sooner.

**Comment by K-O-K** [comment]
Thanks Noah!

I thought this was a limitation only in MariaDB RDS.
Looking at the stackoverflow post it seems like this permission limitation applies to MySQL RDS too, so might be a good idea to add the option to both, MariaDB and MySQL ( "mariaDB": { ... }, and my "mySQL": { ... }, ) or maybe even some general option, in the config.json Settings section that applies in this case of MariaDB and MySQL and in the future to modify the behavior for  different RDS engines (DocumentDB, Aurora, PostgreSQL, etc..).

Thanks again!

**Comment by nzalev** [comment]
I have updated it such that it applies to MySQL as well - the mysqldump option exists for both.

As for the rest, currently, the only supported DBs are MongoDB, MariaDB and MySQL. There hasn't been any indication in the issues that MongoDB needs anything extra for when running on AWS. For now, it is specific to MariaDB and MySQL.

**Comment by nzalev** [comment]
@K-O-K The MariaDB `awsrds` option will be in Meshcentral v0.9.52. The basic config looks like

```json
    "mariadb": { 
      "host": "hostname",
      "user": "user", 
      "port": 3306,
      "password": "password",
      "awsrds": true
    },
```

FYI, since you are using AWS, I am assuming your DB is on a different host than Meshcentral. If this is the case, you should include SSL options if you haven't already. 

The following are the docs from AWS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MariaDB.html#MariaDB.Concepts.SSLSupport

I have added SSL config options for both MariaDB and MySQL. You can find the options in the config schema: https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json


AWS links to their certificates on this page: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Comment by K-O-K** [comment]
Thanks @nzalev 

I was waiting for the 0.9.52 version to be released to try this.

I can confirm this is working properly!

The Server warning message it's gone and when I run the `autobackup` console command it says:
```
> autobackup
Starting auto-backup...
Auto-backup completed.
```

Also, I see the difference in size of the autobackup:
![image](https://user-images.githubusercontent.com/25281984/142957596-049d9f11-10e8-4992-bc37-60d0beb8914b.png)

About the SSL option, In the RDS Parameter group I have all this values for ssl_cipher, so I don't know what to choose:
![image](https://user-images.githubusercontent.com/25281984/142958173-f25d4a1c-ac14-4c6e-936c-076fd0319082.png)

Maybe you could guide me a bit in what cipher should I choose.

Thanks again!

**Comment by nzalev** [comment]
I am glad to hear that it is working.

I am not that familiar with AWS RDS, so I am not sure if you are required to manually set all the parameters. 

However, typically, you don't need to manually set ssl_cipher directly. For example, you can see that the `ssl_cipher` is not set.

<pre>MariaDB [(none)]&gt; show variables like &apos;%ssl%&apos;;
+---------------------+-------------------------------------+
| Variable_name       | Value                               |
+---------------------+-------------------------------------+
| have_openssl        | YES                                 |
| have_ssl            | YES                                 |
| ssl_ca              | /etc/mysql/newcerts/ca.pem          |
| ssl_capath          |                                     |
| ssl_cert            | /etc/mysql/newcerts/server-cert.pem |
| ssl_cipher          |                                     |
| ssl_crl             |                                     |
| ssl_crlpath         |                                     |
| ssl_key             | /etc/mysql/newcerts/server-key.pem  |
| version_ssl_library | OpenSSL 1.1.1f  31 Mar 2020         |
+---------------------+-------------------------------------+
</pre>

However, a cipher will be chosen:
<pre>MariaDB [(none)]&gt; status;
--------------
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:		33
Current database:	
Current user:		meshcentral@localhost
SSL:			Cipher in use is TLS_AES_256_GCM_SHA384
</pre>

From the AWS docs that I could find, it does not mention manually setting anything other than your user to require SSL:
```sql
ALTER USER 'encrypted_user'@'%' REQUIRE SSL;
```

I would check to see if your instance already has SSL configured via
```sql
show variables like '%ssl%';
```

If it does, then you will only need to download the certificate bundle: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

In your meshcentral config, you will need to add the block for ssl:
```json
    "mariadb": { 
      "host": "hostname",
      "user": "user", 
      "port": 3306,
      "password": "password",
      "awsrds": true,
      "ssl": {
          "caCertPath": "/full/path/to/global-bundle.pem"
      }
    },
```

**Comment by K-O-K** [comment]
Hi @nzalev ,

Last night I tried again to enable SSL to connect following those steps, first I checked the SSL parameters in mariaDB with:
`show variables like '%ssl%';`
![image](https://user-images.githubusercontent.com/25281984/143688566-7d1d01d4-734b-40bf-ba2b-e0b484327d16.png)

Then I enabled the MeshCentral MariaDB user to require SSL with: `ALTER USER 'encrypted_user'@'%' REQUIRE SSL;`

I downloaded the .pem certificate bundle from that AWS URL, placed it on my `meshcentral-data` folder.. in the `"mariaDB:"` section of the `config,json` file I stated the certificate path in `"caCertPath:"`

Restarted MeshCentral and got the error: 
![image](https://user-images.githubusercontent.com/25281984/143689138-f0a49de2-85e6-4837-923b-0a1880e99200.png)

The weird part was that I tried to disable the MariaDB configuration by passing ` false` in the `config.json` file and nothing.. it kept saying the same error, I the restore both, the last DB dump and the whole `meshcentral-data` folder with no luck. I even ran the `npm install meshcentral` and it kept saying that error.

I had to start over with MC in a new EC2 instance, I reinstalled node with the dependencies and installed MC, then restored the `meschentral-data` folder and eveything worked properly.

Why was that? I haven't terminated the old MC EC2 Instance yet in case you guys need to check something there.

Thanks!

**Comment by nzalev** [comment]
If you ran `ALTER USER 'encrypted_user'@'%' REQUIRE SSL;` with your meshcentral user (ie, `ALTER USER 'meshcentral_username'@'%' REQUIRE SSL;`), then this tells MariaDB/MySQL to not allow connections for that user unless they are encrypted.

If you remove the SSL config from the meshcentral side, you need to remove the SSL requirement for that user via `ALTER USER 'username'@'%' REQUIRE NONE;` or by simply recreating the user in MariaDB. (you can verify this has worked via `show grants for 'username'@'%';`)



As for the error you see, `Unable to connect to database: Error: retreive connection from pool timeout after 10000ms`: the SQL connector could not connect to the server. If a connection cannot be established, it will be timed out after a time limit and this error is thrown.

This will happen if the ssl configuration is not correct at the meshcentral side or if the sql connector could not verify the certificate presented. If you post your config.json, I will take a look at it (you should redact the password of course). If the global certificate bundle didn't work, you can try the certificate that is specific for your aws region (they are in a table here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html)


---

I have gone ahead and created an AWS RDS MariaDB instance for me to test with. 
I set up the user + database in the following way:
```sql
MariaDB [(none)]> create database meshcentral;
Query OK, 1 row affected (0.028 sec)

MariaDB [(none)]> create user meshcentral@'%' identified by '...' require ssl;
Query OK, 0 rows affected (0.030 sec)

MariaDB [(none)]> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, REFERENCES, DROP, GRANT OPTION ON meshcentral.* to 'meshcentral'@'%';
Query OK, 0 rows affected (0.037 sec)

MariaDB [(none)]> flush privileges;
Query OK, 0 rows affected (0.033 sec)
```

I downloaded the global-bundle.pem file from the aws link. I placed the global-bundle.pem in the meshcentral-data directory (as you did, normally, I keep these in /etc/ssl).

I set my config.json as follows:
```json
  "settings": {
    "mariadb": { 
      "host": "meshcentral-2.cpykhgbiyn5s.ca-central-1.rds.amazonaws.com",
      "user": "meshcentral", 
      "port": 3306,
      "password": "...",
      "awsrds": true,
      "ssl": {
        "caCertPath": "/home/noah/Documents/meshc_testing/meshcentral-data/global-bundle.pem"
      }
    },
```

And I was able to connect without issue.

<pre><font color="#4CE64C"><b>noah@L460</b></font>:<font color="#295FCC"><b>~/Documents/meshc_testing</b></font>$ node node_modules/meshcentral/
MeshCentral HTTP redirection server running on port 1024.
MeshCentral v0.9.55, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on localhost.internal:4433.
Server has no users, next new account will be site administrator.
MeshCentral HTTPS server running on localhost.internal:4430.
^CServer Ctrl-C exit...
</pre>

**Comment by K-O-K** [comment]
Hi @nzalev,

> If you remove the SSL config from the meshcentral side, you need to remove the SSL requirement for that user via `ALTER USER 'username'@'%' REQUIRE NONE;` or by simply recreating the user in MariaDB. (you can verify this has worked via `show grants for 'username'@'%';`)

I forgot to mention it but I did excatly that and the error at MC launch was the same..:

`Error: pool is ending, connection request aborted`

> you can try the certificate that is specific for your aws region

I also tried that part.


At that point I disabled SSL for the DB user and tried to start MC and the pool is ending error was the same. I even restore a dump and `meshcentral-data` folder and it didn't work.

**Comment by nzalev** [comment]
Can you post your config.json along with the result of `show grants for 'your_mesh_username'@'%';`?
