### ISSUE TITLE
AMT one click recovery info

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3285]
Hi, ylian,

what action this option will perform on the intel amt device? 
 
![o1](https://user-images.githubusercontent.com/84929681/142505246-9aeb72dc-0acf-4d0b-92f1-c602f37a7d04.png)

**Comment by Ylianst** [comment]
Hi. You can take a look at this feature in the [Intel AMT Reference Guide here](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Foneclickrecovery.htm). It passes a URL to an ISO image to AMT who then passed along that data to the BIOS during a platform reboot. The BIOS will then attempt to download the .iso image into a RAM drive an boot it.

This is only available on Intel AMT 15 and higher and does sometime similar to IDER but should be much faster as the disk image is downloaded once.
