### ISSUE TITLE
Question: Meshctrl and SSE

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3287]
You wrote earlier that "node meshctrl.js showevents" sends events in sse format.  Is there an external HTTP link that I can connect to to listen for events?  To be able to use ready-made software for listening and responding, they usually all work over the HTTP protocol.

In this regard, I found this general article about SSE in Node.js.  Unfortunately, my knowledge and experience is not enough to understand how difficult it is to implement it. https://www.google.com/amp/s/www.digitalocean.com/community/tutorials/nodejs-server-sent-events-build-realtime-app.amp

I would like to have a URL that will output events in the stream just like meshctrl, which I would specify in my automation program.

**Comment by Ylianst** [comment]
Hi. I am not sure who you are referring to about Server-Sent Events (SSE), MeshCentral does not support this format. However, MeshCentral fully supports websockets and you can get events by connecting an HTTP websocket to `/control.ashx` and get real-time events for your account just like `MeshCtrl.js` does.

In fact, the MeshCentral web site uses the same websocket system for everything. You can open the main page with `?trace=1` as URL argument and open the browser console to see all of the JSON commands that are sent and received.

![image](https://user-images.githubusercontent.com/1319013/142560143-6dd19c5a-357c-42dc-8b63-381827443700.png)

So, you could easily build your own site or your own tools that connects to `/control.ashx` and performs management operations or reads and reacts to events in real time.

If you look at the source code to MeshCtrl.js, you will see, it's opening and authenticating to `/control.ashx` to the server using a websocket and then sending and receiving JSON documents in real-time.

Let me know if that helps.

**Comment by AntonAndreevichMoroz** [comment]
Unfortunately, this is not what I would like.
You said it in this issue #2671 

> After that, you can run "node meshctrl.js showevents" to see events on the MeshCentral server event bus.

I read it again and realized that I misunderstood you. Then the question is, is it possible to implement SSE in MeshCentral? If you say that it might be, then I'll create a separate feature request.

**Comment by Ylianst** [comment]
Why would SSE be of interest? websockets work just fine and since I need to use websocket for remote desktop, terminal, files, TCP relay, RDP, etc. It's easier on my side to have just WebSocket to all of the work.

Are you intending to use some SSE library? Programing language? What would be the benefit of SSE over the current system? - Thanks.

**Comment by Ylianst** [comment]
I looked at the link you sent above to understand SSE and I don't see how this would be any benefit over WebSocket. It's like WebSocket but you can only receive data and can't send any commands and it's not as widely supported a WebSocket. Again, I am confused by the request.

**Comment by AntonAndreevichMoroz** [comment]
To a greater extent, this is due to the extension of the ready-made incents in person personally to work with WebSocket, but there is a ready-made tool for working with SSE. Also, the personal problem of exploration of development skills sufficient to write some "connector". I will close this appeal. I got the answer that I wanted. I will go to study deeper the question, if you need, I will open a new request.

Thank you for your excellent work on a great product.

**Comment by Ylianst** [comment]
Let me know what the ready made tool is for SSE, I can look at building an equivalent one for WebSocket, it should be simple. My most basic problem is that SSE if one-direction and so, does not allows you to query what you want from the server, etc. It seems very limiting.

**Comment by AntonAndreevichMoroz** [comment]
> Let me know what the ready made tool is for SSE, I can look at building an equivalent one for WebSocket, it should be simple. My most basic problem is that SSE if one-direction and so, does not allows you to query what you want from the server, etc. It seems very limiting.

I understand that I cannot ask to understand a third-party product. Moreover, only at my single request, and not a massive request from the community.

But if you are asking, I will provide some information. We are using the N8N automation product. https://n8n.io/
SSE trigger has a humble description https://docs.n8n.io/nodes/n8n-nodes-base.sseTrigger/#node-reference
There is also information on creating your own triggers https://docs.n8n.io/nodes/creating-nodes/create-trigger-node.html#creating-your-first-trigger-node
