### ISSUE TITLE
Feature: Add Share to Desktop Tab

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#3288]
I love the share Desktop feature with a Guest. I use it quite a bit. However I tend to be in a remote desktop session most of the time when I want to share the desktop with an outside guest.

It would be super nice to add the share button under the desktop tab currently its only under the general tab
### Screenshot 1
![image](https://user-images.githubusercontent.com/1812594/142666839-972cc1ef-03de-4fec-bd95-42848698741a.png)

### Screenshot 2 Maybe add it here.
![image](https://user-images.githubusercontent.com/1812594/142667049-aa7624b7-a56f-4339-b3c0-43c1bfd689d1.png)

**Comment by Ylianst** [comment]
Good request. Just added it as an icon, it will be in MeshCentral v0.9.52.

![image](https://user-images.githubusercontent.com/1319013/142675946-c88254a8-fc99-4b85-8fde-d58991efe462.png)

Let me know if that works.

**Comment by johnnyq** [comment]
Fantastic!! Thank You @Ylianst

**Comment by rowds15** [comment]
Hi, I'm on 0.9.52 running as Full Administrator, I'm not seeing the share icon on the desktop. Perhaps i'm missing an option?

**Comment by johnnyq** [comment]
@rowds15 

1. Do you see the share button under the general tab?
2. Clear Your browser cache and try again?

**Comment by rowds15** [comment]
@johnnyq 
1. Yes share button is appearing under general tab.
2. I have 2 different Meshcentral Servers, both do not give me the option of the share button on desktop screen, one in hybrid mode and one in Lan mode.
3. I have tried with 2 different browsers on 3 different computers and still no share icon.

**Comment by VINISHVV** [comment]
@johnnyq - I am also facing the same issue.
In my case, i have activated **minify**. I am able to access the share button after deactivating the same.
I hope you have activated **minify** in your configuration.  Please try to disable the same once.

@Ylianst - Can you please incorporate the same if someone enabled the options "minify": true, in config.js

**Comment by Ylianst** [comment]
Oh right. I will check with minify turned on.

**Comment by Ylianst** [comment]
Just published v0.9.53 with a fix for minification. Also, you can use "?minify=1" or "?minify=0" in the URL to override the server's minification settings. Nice try to see if minification is the problem.

**Comment by rowds15** [comment]
Yes fixed for me. thanks guys

**Comment by VINISHVV** [comment]
Thanks, @Ylianst.

Its working perfectly.

**Comment by Ylianst** [comment]
Thanks. @johnnyq did not confirm, but pretty sure this works. Will close it.
