### ISSUE TITLE
Mesh Central Server Scanning

### ISSUE THREAD

**Issue by wgpjr** [Ylianst/MeshCentral#3289]
I've configured AMT  on my computers via meshcmd agent less and am seeing the mesh central server contact the computers throughout the day on port 16993.  Does the server perform daily checks of AMT on the computers?  If so, is there a way to disable the checks or is this something that's required.

**Comment by Ylianst** [comment]
Yes, in the settings section of the config.json add this:

```
"amtScanner":  false,
"meshScanner": false
```

That will stop the UDP traffic from MeshCentral scanning the devices to see if they are still present. Let me know if that works.

**Comment by Ylianst** [comment]
No replay, closing.
