### ISSUE TITLE
location map bug

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#329]
1. In a particular device when viewing a location, the map cannot be moved. In the general list of devices, the map works fine.
2. determine the location of devices based on ip address. or add an optional geographic address field

**Comment by Ylianst** [comment]
Oh dear. The map is not something I will be fixing anytime soon, it's really super low priority. This is why I turn that feature off my default. I would not mind if someone where to help with work on that feature. In theory, each device can have up to 2 positions (IP, GPS, WIFI and User Specified) with IP address location being by far the least accurate.
