### ISSUE TITLE
Mesh Central Router - SSO Login

### ISSUE THREAD

**Issue by TiaPcom** [Ylianst/MeshCentral#3293]
Hi,
users who have only SSO login via SAML can't logon using mesh router

**Comment by Ylianst** [comment]
You right that can't can't your SSO from MeshCentral Router. However, you can use the "Install..." button to register MeshCentral Router with the "mcrouter://" URL. Then, you can go in the web site, hit the "Router" link and hit "Launch MeshCentral Router". It will launch it and be logged in right away.

![image](https://user-images.githubusercontent.com/1319013/142914054-7922304f-8489-4b06-8d36-7d7cc5485bf5.png)

The other alternative is to create a login token in your account and use that in MeshCentral Router.

![image](https://user-images.githubusercontent.com/1319013/142914201-9a342f0d-73e0-40ff-924d-e80f0ba2ff6c.png)

Hope that helps,
Ylian

**Comment by TiaPcom** [comment]
Hi Ylian, thank you for reply.
we can't login using login token with a user created with SSO
![image](https://user-images.githubusercontent.com/77863847/143249401-2b8af7f5-00a9-4e45-a314-12e01e2c056a.png)

How can we verify SSO user's email address?
Thank you

**Comment by Ylianst** [comment]
I will check this.

**Comment by Ylianst** [comment]
Just pushed a fix for this, will be in MeshCentral v0.9.53. Let me know if it works. If it does, please close this issue.

**Comment by TiaPcom** [comment]
Thank you Ylian! I confirm that works as expected.

**Comment by Ylianst** [comment]
FYI. If you save your mappings in a .mcrouter file, you can edit the file with notepad and add your password in the file (use "password" as key name"). Then, you can associate .mcrouter file type to MeshCentral Router and double click on the .mcrouter. It will open, auto-login and maps the ports all in one step.
