### ISSUE TITLE
manageAllDeviceGroups : Can't directly access related files and folders.

### ISSUE THREAD

**Issue by djarril** [Ylianst/MeshCentral#3294]
Hello !
First, congratulations for this product which is marvelous.
My suggestion : If you can automaticaly manage groups with the option manageAllDeviceGroups, why can't we manage the related files. Either it's a missing functionnality, either another option shoud exist like "manageAllFilesAndFolders".
Sorry if I'm direct or if I missed something.
Thanks again for your job that I find gorgeous.

Best regards,
Denis from France.

**Comment by djarril** [comment]
Hello again !
Same behavior using "user groups". I gave access to a device group for a user group and users inside don't have access to the associated files and folders. 
I would need this to work to store drivers or config files for each device group. Nice option but not simply available actually :(

Best regards,
Denis

**Comment by Ylianst** [comment]
Good request. I had not considered the device group files for user groups and "manageAllDeviceGroups".

**Comment by Ylianst** [comment]
Your absolutely right and I did a fix for this, will be in v0.9.53. Should be published in a few hours. Once out, let me know if it works and close this issue if it's ok.

**Comment by Ylianst** [comment]
v0.9.53 is out :)

**Comment by djarril** [comment]
It works for both ("manageAllDeviceGroups" and "user groups")
Thanks Ylian

Best regards,
Denis
