### ISSUE TITLE
Let'Encrypt : Clarifting the topic (Server's public IP not reachable from itself behind a firewall)

### ISSUE THREAD

**Issue by djarril** [Ylianst/MeshCentral#3296]
Hello,

I use MeshCentral behind a firewall using a virtual public IP associated with the local IP address of the server. 
Badly, the local server can't reach itself with the public IP, The firewall don't permit that.
As MeshCentral asks itself the let's encrypt certificates using the public IP address, it's recovery of those certificates allways fails :(
My solution was to add the public IP address as a secondary IP on the server. It works. I prefer that instead of adding hazardous configuration on the firewall.

Maybe you could : 
- Specify in the documentation that the MeshCentral must be able to connect to itself with the public IP.
- Code the fact thay if the server is unreachable with the public IP address, the program tries to get the certificates from the local IP, if possible :)

Hope it helps.

Sorry for my english and BRAVO for your work on this project :)

Best regards,
Denis

**Comment by Ylianst** [comment]
Hi. I am not sure I understand. Are you using the MeshCentral built-in Let's Encrypt support? If so, that should work even if the server can't connect to it's own public IP address. To use the built-in Let's Encrypt support you need the public port 80 to be routed to MeshCentral's port 80 ([I cover this in this video](https://www.youtube.com/watch?v=a4F1ayu7XWo)), but that should not require MeshCentral to access itself.

If you are using a reverse proxy that is getting the Let's Encrypt certificate and then using "certurl" in the MeshCentral config.json file, then the "certurl" can contain any URL that will get the certificate that agents will see, it's ok in "certurl" to use a private IP address.

**Comment by djarril** [comment]
Ok Ylian, my mistake :)
I didn't found, either understood, the "certurl" entry in the default domain section. I missed it :)
Do I need to put it in each other domain declaration ?

Best regards,
Denis

**Comment by Ylianst** [comment]
Well, it depends if you are using the MeshCentral built-in Let's Encrypt feature or not. I don't know what you setup looks like.

**Comment by Secure-Concept** [comment]
I use the built-in Let's Encrypt feature with few domains.

**Comment by Ylianst** [comment]
Ok, then you should not need "certurl" and it should work even if MeshCentral does not have access to itself. You say you are using a few domains, do domains have their own DNS name? Or they are "/domain" URLs?

If each domain has it's own DNS name and you want Let's Encrypt certificate to include them, you need all domains to point to your server's IP address, have port 80 open and directed to MeshCentral. You should get a single cert that covers all domains.

If there is something I am missing, I may need more details.

**Comment by Secure-Concept** [comment]
Thanks Ylian !

All my domains are with a DNS name which points to the server. The linux server has only MeshCentral installed on (no Apache, Nginx...). No nothing, just a simple configuration from the sample file (with manageCrossDomain, manageAllDeviceGroups and smtp), nothing strange.
But I insist (with huge respect :) ). I created the "Let's Encrypt" configuration which should have work. I checked them with letsdebug. As long as I did not add the public IP address as secondary, using the MeshCentral console commande "leevents", I received the answer ETIMEOUT during the trys. When I added the public IP as secondary address on the server, it worked instantaneously without modifying the config.json file whatever. I just restarted the server.
I was hoping my experience could help other users.

Best regards,
Denis

**Comment by Ylianst** [comment]
Interesting!!! Can you elaborate how your added the public IP address as secondary? You had to enable a second network interface that had the public IP address in your VM?

**Comment by Secure-Concept** [comment]
The operating system is a Debian 10. I added : 

auto eth0:0
iface eth0:0 inet static
    address XX:XX:XX:XX/32

at the end of the file /etc/network/interfaces. This setup add an alias (:0) to the eth0 network interface with the IP I needed.

**Comment by Ylianst** [comment]
This is interesting since I think there was a report of exactly this issue before and I had no idea what was going on. I am going to look at the code to see if there is a self-test and provide an option to disable it.

**Comment by Ylianst** [comment]
Found it, [it's right here in acme-client](https://www.npmjs.com/package/acme-client#internal-challenge-verification). There is indeed a self-test and a way to disable it. Working on that now.

**Comment by Ylianst** [comment]
Just checked in a fix for this, starting with v0.9.53 you can do this:

```
  "letsencrypt": {
    "email": "myemail@myserver.com",
    "names": "myserver.com,customer1.myserver.com",
    "skipChallengeVerification": false,                                          <-------------
    "production": false
  }
```

The new "skipChallengeVerification" option can be set to true to skip the self-test.

Big thank you for this report!

**Comment by Secure-Concept** [comment]
Thanks Ylian !

I'm happy to help :)
Last question : I need to add other domains. Do I put back production to false before ?
I'll check "skipChallengeVerification" in the same time.

Best regards,
Denis

**Comment by Ylianst** [comment]
You don't requirement to put production back to false. You can do it for testing if you like. If you know what you are doing, just change the settings and restart the server. Note that if you make too many requests to Let's Encrypt, they will ban your IP address for a duration, so it's important to be nice when using their production server.

**Comment by Secure-Concept** [comment]
Thanks again :)
I wait for v0.9.53 to check "skipChallengeVerification" to close this issue.
Congratulations for your implication.

**Comment by Ylianst** [comment]
Thanks. I should be publishing it in a few hours.

**Comment by Ylianst** [comment]
v0.9.53 is out :)

**Comment by Secure-Concept** [comment]
Can't check now [https://letsencrypt.status.io/]((https://letsencrypt.status.io/))

**Comment by djarril** [comment]
Hello Ylian !
First : <"skipChallengeVerification": true> works perfectly. Congratulations !
Second : Never put back <"production": false> when it had been set to true because each browser Chrome or Firefox reports a security breach and the site is no more accessible in this state. Put "production" back to true reenable the site. 

I'm glad to have been a tiny part of your nice project. Regarding this, I find some localisations in french not so natural. Do you want me to send you more usuals french translations ?

Best regards,
Denis

**Comment by Ylianst** [comment]
Thanks.

Yes, if you have updates to the French translation, that would be great. The [latest translation file is always here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/translate/translate.json). You can update the file with a pull request on GitHub or just mail me the updates, [my contact info is here](https://www.meshcommander.com/contact-information). Any improvement is greatly appreciated.

**Comment by djarril** [comment]
Thanks Ylian

**Comment by djarril** [comment]
Hello Ylian !
"skipChallengeVerification" does not appear in the "le" report from "My Server Console", but maybe you don't care. Just to report that :)

Best regards,
Denis

**Comment by Ylianst** [comment]
Not a bad idea! Let me add that now.

**Comment by Ylianst** [comment]
Added it, will be in v0.9.55. I will close this issue now, but feel free to create a new issue for any other suggestions.
