### ISSUE TITLE
Suggestion for web page and connect/install app

### ISSUE THREAD

**Issue by JReally** [Ylianst/MeshCentral#3297]
The folks I deal with need everything to be as simple as possible. I've attached some small suggestions to the download web page.

The other suggestions relate to the connect/install application. I'm suggesting that the details be on a separate tab and the instructions are edited to reflect whether it's connect, install or both.  Currently a connect only version mentions install etc
![ConnectWindow](https://user-images.githubusercontent.com/39771712/143312354-02897809-8ebd-4146-a64d-5507c4774886.png)
![NewWebPageWindow](https://user-images.githubusercontent.com/39771712/143312381-9f21a115-ccfb-4f24-88b8-20ebb41320b8.png)
.

**Comment by si458** [comment]
this already sorta exits now in the agentCustomization
![2022-08-24-06-42-40](https://github.com/Ylianst/MeshCentral/assets/765314/bb577eaa-42bd-4b88-a960-a3a3ce156ad6)
you can set the text to explain to a user to click either install for permant setup or connect to temp setup

and same with the web ui, it was changed slightly 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/27deac15-7a64-440a-99b8-204492f95129)
