### ISSUE TITLE
Unable to download mesh settings at:

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#33]
Hi, I try install mesh agent into a ubuntu 18.04 folowing this steps:
1.- wget -q https://FQDN:444/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh
2.- sudo chmod 755 ./meshinstall.sh
3.- sudo ./meshinstall.sh https://FQDN:444 'id_string'
In the last step the following error is shown:
Downloading Mesh agent #6...
Mesh agent downloaded.
Unable to download mesh settings at: https://FQDN:444/meshsettings?id=id_string.
Do I need to open some port in the router for the linux agent?
MeshCentral is listening at 444. 
Thanks

**Comment by jsastriawan** [comment]
Yes, there is a bug here:

file agents/meshinstall-linux.sh

    # If it did not work, try again using http
    if [ $? -eq 0 ]
    then
      wget $url/meshsettings?id=$meshid -q -O /usr/local/mesh/meshagent.msh
    fi

to

    # If it did not work, try again using http
    if [ $? -ne 0 ]
    then
      wget $url/meshsettings?id=$meshid -q -O /usr/local/mesh/meshagent.msh
    fi

Successful wget will return 0. So just change from -eq to -ne will make it work.
Will work with @Ylianst to rectify this after Thanksgiving.
Regards,


Joko

**Comment by edorbike** [comment]
Thanks to you.

**Comment by Ylianst** [comment]
Joko, you are wonderful! Just published MeshCentral v0.2.3-f with your fix.
