### ISSUE TITLE
Alt gets stuck on remote machine after Alt+Tab during remote access

### ISSUE THREAD

**Issue by UnP1u9** [Ylianst/MeshCentral#330]
if i take remote access to a machine and press Alt+tab on my machine, it send Alt Key to the remote machine so if i press any key in remote machine from mesh panel or physically  it behaves like i have pressed Alt key, like if i press F it behaves like Alt+F.

**Comment by wcrlewis** [comment]
This is an ongoing issue.  It is a limitation of the design.  An easy way to correct it is to retake control of the system (give the window focus by clicking in the remote system) and then press CTRL, ALT and/or SHIFT to apply and remove their "on" status.

**Comment by Ylianst** [comment]
I have noticed this too. When connecting to a remote desktop, MeshCentral automatically sends ALT/CTRL/SHIFT UP key to get then unstuck. Maybe I could fix this by holding sending the ALT/CTRL/SHIFT down signal until another key is pressed. Then, I send the down signal just before the other key... I would need to experiment.

I am currently swamped with requests for new features and bug fixes, but certainly something I would want to look into.

**Comment by wcrlewis** [comment]
I am having trouble understanding.  Are you stating a key combination resolves the issue?  The issue I experience is lack of connectivity for video, mouse and keyboard.  'Actions' do function.  In the last two weeks systems often now require half a dozen attempts and some including one I am working with now almost never connects (50+ tries - A restart and immediate connection frequently succeeds).

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.7-h with a fix for this. Starting with this release, if the ALT / SHIFT / CTRL keys are pressed and the browser loses focus, the keys are released. Hopefully this will fix this. If you can test and confirm, that would be appreciated.

**Comment by MailYouLater** [comment]
Works for me.

**Comment by UnP1u9** [comment]
Yep, works like charm.

Thnx
