### ISSUE TITLE
Unable to use Mesh using cloudflare tunnel

### ISSUE THREAD

**Issue by rachakondasai** [Ylianst/MeshCentral#3301]
Hi
i am tried to use the mesh central with cloudflare tunnel to access from remote but get the error too many redirects. Please help to fix the issu
![Screenshot 2021-11-25 234543](https://user-images.githubusercontent.com/94543192/143487270-3f101767-ecc2-46c0-9a11-7119eda7f253.png)
e.

**Comment by Ylianst** [comment]
Hi. Sorry, but not sufficient information to fix this. Want to post your config.json? Please replace any confidential information with "XXXXX".

**Comment by rachakondasai** [comment]
[config.txt](https://github.com/Ylianst/MeshCentral/files/7610231/config.txt)
please find the config file above

**Comment by Ylianst** [comment]
Your config.json contains this:

```
{
   "settings": {
      "lanonly": true, 
      "_minify": true, 
      "webrtc": true
   }, 
   "domains": {
      
   }
}
```

Your server is in LAN mode and has no DNS name. This is certainly not going to work if your trying to use CloudFlare as a reverse proxy. You probably needs to start with the basics and setup a basic server, maybe one with a reverse proxy before going to more complicated setups.
