### ISSUE TITLE
MeshCentralRouterCMD action file help

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3303]
HI @Ylianst ,
Any help providing an example for the action file of meshcentral routerCMD, where the action file contains multiple mapping for different services and multiple mapping for different devices or computers?

I know if we click on the Meshcmd link on each computer page we get that action file to connect to that computer, but do we just combine all the action files of those computers into one action file and place it in the same directory where the routerCMD is?

if combining is the right thing to do, then multiple sections in the array for each device are the same, like server ID, username, password ....etc. do we have to type these info over and over again for each section at the same file ?

Thanks

**Comment by Ylianst** [comment]
MeshCMD does not currently support multiple mappings, however, I will take a look at it. It should not be too difficult to do. Of course MeshCentral Router does support multiple mappings at the same time.

**Comment by smartekIT** [comment]
Thanks for getting back to me so quick, when you say "MeshCMD" in the above, do your refer to MeshCentralRouterCMD or the actual MeshCentral CMD, or it matches both as both are command line tools and they don't currently support multiple mapping while MeshCentral Router which is GUI of course support multiple mapping ?

**Comment by smartekIT** [comment]
what's in my mind, if routerCMD start supporting multiple mapping and we know if can be installed as a Windows Service, then we can produce a custom installer .exe file for each department with the department special mapping ready for distribute to the department users so all will have same settings and not even a single manual mapping done. all automated and pre-done for them.  (department = group).
of course someone might even take things further and think of special dashboard for a group of users in a department where the options of mapping can be configured to produce the final .exe file (routerCMD + department action file + installation settings).

Thanks for the beautiful work you've done @Ylianst , we really appreciate it.

**Comment by Ylianst** [comment]
Ha so, both "MeshCentralRouterCMD" and "MeshCMD" don't support multiple mappings... however, should not be too difficult for me to add. I will work on adding support in "MeshCentralRouterCMD" since that one can be installed as a Windows Service.

**Comment by Ylianst** [comment]
Just updated MeshCentralRouterCmd.exe, will be in the next version of MeshCentral but you can [get the latest copy here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouterCmd.exe). This new version supports multiple mappings at the same time.

The actions.txt file format for multiple mappings is the same as the .mcrouter file that is saved by MeshCentral Router. So, it looks like this:

```
{
  "hostname": "central.mesh.meshcentral.com",
  "username": "admin",
  "certhash": "97EAF674EAB131D3775F12CFA9C978D185A0E9CAAF3A854BF0EB4FF94C2D6C53CA3DC456DA149002804666FBBDAE2FC9",
  "mappings":[
    {
      "nodeName": "RPi-188",
      "name": "Map1",
      "meshId": "mesh//7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c",
      "nodeId": "node//YVLeDkiuGckpkGqPagAVfUpf5$31ABSmPpRF8o6aOBw56oTaZSdfM9bOIyo3LDCp",
      "appId": 5,
      "protocol": 1,
      "localPort": 65101,
      "remotePort": 22
    },
    {
      "nodeName": "Tiny1",
      "name": "Map3",
      "meshId": "mesh//7b4b43cdad850135f36ab31124b52e47c167fba055ce800267a4dc89fe0e581c",
      "nodeId": "node//bsxzGWWC8GvJ5kNJErHsS1@F7Wvlf7CsZI3FKdyOiVsUzguvjfrGY1SR9ZbAR$B7",
      "appId": 1,
      "protocol": 1,
      "localPort": 51063,
      "remoteIP": "127.0.0.1",
      "remotePort": 80
    }
  ]
}
```

Like before, you can add "password" after the "username". One note is that MeshCentral Router saves the hash of the MeshCentral Server's TLS certificate. This certificate may change. I would replace the "certhash" above with the "serverid" normally found in the actions.txt file. "serverid" does not change when you change the TLS cert.

Let me know if this works,
Ylian

**Comment by smartekIT** [comment]
Thank you so much @Ylianst for the great work you've done , I will try it and let you know. I normally use the server ID not the certHash. also I use "Token" when 2FA is enabled on the account. will try them here and see the outcome.

**Comment by smartekIT** [comment]
@Ylianst for RouterCMD.exe what file name it expect in the same directory after you added multiple mapping?
"meshaction.txt" or "meshactions.txt" ? on a single mapping before, it used to look for "meshaction.txt" in the same directory.

**Comment by smartekIT** [comment]
ok just tested it and it's working fine but with the following notes:

remove "certhash" and replace it with the "serverid": <value>
if your account has 2FA enabled then the service will always fail to start without adding "Token": <value>
add "password": <value> after the username in meshaction.txt
the name of our settings file should be: "meshaction.txt"
to use RDP then set "appId": 3
to use TCP then set "protocol": 1
to use UDP then set "protocol": 2

**Comment by smartekIT** [comment]
as you can see from the above that when 2FA is enabled in the account, then each time the service connect/disconnect that "Token": <value> in the "meshaction.txt" needs to be changed and add the new Token.
for now the only way to have working permanently and not affected by service stop/start , is to remove the 2FA from the account used with RouterCMD.

hope that @Ylianst can find a workaround for this by having the RouterCMD bypass the 2FA token requirements so the service can start normally after windows restarts.

**Comment by Ylianst** [comment]
For the 2FA problem, you can solve it by creating a account login token.

![image](https://user-images.githubusercontent.com/1319013/143671386-1b6b77aa-52e6-47c4-b6de-a6d15cd3637e.png)

Use the token as username & password. Account login tokens are only displayed once and can be revoked. Also, when using them to login, you can't change any account settings (email, password, 2FA, etc).

Apologies, your right it's "meshaction.txt", I will fix my comment above. Also, note that MeshCentralRouterCMD.exe does not currently support UDP routing, just TCP. You can specify the application (SCP, SSH...) but since MeshCentralROuterCMD.exe does not launch any of these, that value is ignored.

**Comment by smartekIT** [comment]
Thanks man, you're a champion.
one suggestion before you include it in the next release:
currently when using with --install then the windows service startup mode is Automatic.
it would be better if you make it Automatic Delayed, specially for laptops where wireless is the main internet gateway and the routerCMD service wouldn't start if can't access the internet and login to server. normally wireless adapters taking longer to connect than the fixed ethernet adapters.

**Comment by Ylianst** [comment]
Ok, added a new `--installdelayed` option in next version:

```
MeshCentral Router Command Line Tool.
This tool is used along with a MeshCentral account to map a local TCP port to a remote port on any computer on your MeshCentral account. This action requires many arguments, to avoid specifying them all it's best to download the meshaction.txt file from the web site and place it in the current folder. Example usage:

  (Place meshaction.txt file in current folder)
  MeshCentralRouterCmd.exe --pass myAccountPassword

You can also install and start this tool as a Windows Service:

  MeshCentralRouterCmd.exe --install
  MeshCentralRouterCmd.exe --installdelayed
  MeshCentralRouterCmd.exe --start
  MeshCentralRouterCmd.exe --stop
  MeshCentralRouterCmd.exe --uninstall

When running as a Windows service, the account password must be in the action.txt file.
```

**Comment by Ylianst** [comment]
Will be in v0.9.55, but you can get the [latest version here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouterCmd.exe). Let me know if that works.

**Comment by smartekIT** [comment]
Thanks heaps.
