### ISSUE TITLE
The FILTER field has stopped working properly - Polish

### ISSUE THREAD

**Issue by DevOps-88** [Ylianst/MeshCentral#3304]
Hello

Recently I updated my version of MeshCentrall from version 0.7.22 to 0.9.53 and noticed that the search in the FILTER field stopped working.

For example, if I want to search for a computer by its IP address, I enter ip: 192.168.0.50 and unfortunately after running, nothing happens, even though it is on the list.
Just like I want to search for someone by the tag that I assigned to a specific computer earlier, it also doesn't work, previously I entered the name from the tag in the FILTER field and I immediately had the result.
Yes, if I add a lowercase "t:" and the name of the tag is looking for it, but I didn't have to do it before and it worked too.

Currently I have 200 hosts in my meshcentrall, it can be fixed relatively quickly, I must admit that this FILTER field was very helpful in finding a computer quickly.
It would be useful to have a SEARCH field that would search for the entered information through various data in the mesh.

regards
DevOps-88

**Comment by Ylianst** [comment]
Hi. The filter should certainly work. I just tested it with "ip:" and it worked for me. Can you give an exact example that does not work?

![image](https://user-images.githubusercontent.com/1319013/143622560-361a4762-bfa6-40d8-8c25-c14da31b1697.png)

Are you using minification on your site? What happens when it does not work? Can you check the browser console for any errors? - Thanks

**Comment by Ylianst** [comment]
I do want to mention that if you recently updated MeshCentral, try clearing your browser cache. I am guessing this problem will not happen an hour after the update and updated files will be refreshed. Let me know if that is what happened.

**Comment by DevOps-88** [comment]
Hi,
Thank you for your answer.

I did not minify anything. I checked the console there are no errors. I cleared the entire cache in the browser, it did not help either.
But I seem to have solved the problem. For some time now, my native language "Polish" has appeared in meshcentral and the option was selected in the settings for meshcentral to set the language and time from the browser, so by default it was Polish for me, when I changed the language in the meshcentral settings to English the search started to work.
It seems there is a problem with the interface language.

Below I put two pictures with the interface in Polish and as you can see below, the search does not work.

![mc_filter_1](https://user-images.githubusercontent.com/95072779/143870716-e9ed2fd9-645d-45b0-a41e-66081ed2cd84.jpg)

![mc_filter_2](https://user-images.githubusercontent.com/95072779/143870757-6953a943-579f-4bfb-9d95-5b66848a8bb2.jpg)

After changing the language to English, the filter works.

![mc_filter_3](https://user-images.githubusercontent.com/95072779/143871230-a73a6e92-fa96-4228-8beb-c8fb70c3395a.jpg)

**Comment by Ylianst** [comment]
Ha! It's Polish language issue. Thanks for letting me know, I will look into this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.55 with a fix for this. Let me know if it works and please close this issue if it does. Thanks!

**Comment by DevOps-88** [comment]
So now the search for the IP address works with the Polish language, but I checked the filtering by the user and unfortunately it does not work :)
Can you improve it too?
![mc_filter_4](https://user-images.githubusercontent.com/95072779/144011493-5863aaf6-45ed-45c8-b457-891e56a02ae8.jpg)
![mc_filter_5](https://user-images.githubusercontent.com/95072779/144011501-b7dc8b13-5fb3-451f-b743-45bb4cb7b0e4.jpg)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.56 with a fix for `u:` in Polish. Let me know if that works.

**Comment by DevOps-88** [comment]
Confirming now works, thank you very much for your help.
