### ISSUE TITLE
Feature Request: Add Telnyx as an SMS Provider

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#3306]
I've moved all of my voice and most of my SMS services over to Telnyx as they have been a phenomenal provider for us. They have a pretty great SMS application built with their API and webhooks. Was wondering there's a chance of getting them added as an SMS provider for 2-factor authentication?

I'd be willing to provide access to a number and account with Telnyx for testing if this is a possibility.

Here's a link to their example coding in Node for sending an SMS: https://developers.telnyx.com/docs/v2/messaging/quickstarts/sending-sms-and-mms?lang=node

**Comment by VINISHVV** [comment]
There are so many other providers are available in market. I think this not limited to particular providers we need to configure every sms providers api's.

**Comment by Ylianst** [comment]
Looking at this, it will take me 30 minutes to add... so adding it now.

**Comment by Ylianst** [comment]
MeshCentral v0.9.54 is out with Telnyx support. Once updated, put this in the config.json:

```
  "sms": {
    "provider": "telnyx",
    "apikey": "xxxxx",
    "from": "+1222222222"
  }
```

I did not try to any account, I just tested it until it told me the authentication was not valid due to me using a dummy APIKEY, but it looks like it should work. Let me know if it works for you, I will put an announcement on Twitter about this.

**Comment by Ylianst** [comment]
Got my Twitter/Blog graphic ready...

![MC2-Telnix](https://user-images.githubusercontent.com/1319013/143720370-e09b81be-e4b3-483a-84bc-d1ff47f4402a.png)

**Comment by asasin114** [comment]
Perfect! I'll have it tested and reply back by the end of the day according to CST.

Taylor Bornyk
CTO - Insight Hosting
Direct: 306-500-9150 Office: 306-500-0234
________________________________

**Comment by asasin114** [comment]
Works like a charm! One thing to note for anyone using Telnyx. You need to use the API V2 keys that Telnyx offers. API V1 will throw an authentication error.

**Comment by asasin114** [comment]
Ran into a small problem. While I can send SMS messages from the console, it seems as though 2-factor codes are not sending properly. I just tried with 2 different accounts and am not receiving the codes. Is there something I can do to get you a log showing what's happening? The Server error log is empty.

**Comment by Ylianst** [comment]
Yes, go in the "My Server" / "Trace" tab and enable "Email / SMS" tracing. Then, send the SMS and see if you get any errors in the tracing log.

**Comment by asasin114** [comment]
Oops, ignore me. With Telnyx, you have to submit a number to the API with a full E164 number (+1XXXXXXXXXX). I failed to insert the +1 on a number.
