### ISSUE TITLE
Agent and assistant customizations

### ISSUE THREAD

**Issue by heidnir** [Ylianst/MeshCentral#3307]
Setup a meshcentral server a while ago, works like a charm, except for the agent/assistant customizations. I do apologize if I am posting in the wrong place, but don't know where else to ask. I've had the config.json setup in a bunch of ways, it simply doesn't work. Most likely I'm just doing it wrong, I'm not a coder. I just want to customize the agent and the assistant. I'll post a sample of my config.json, if someone could please advise me. I've been through the samples I could find, but still doesn't work.
//code start//
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name$
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "0.0.0.0",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "name",
      "_title2": "name",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "mstsc": true
     },
  "_agentCustomization": {
    "displayName": "Compagny® Product™",
    "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
    "companyName": "Compagny",
    "serviceName": "compagnyagent",
    "fileName": "compagnyagent"
  },
  "_assistantCustomization": {
    "title": "Compagny® Product™",
    "image": "assistant-logo.png",
    "fileName": "compagny"
   }
  },
},
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
//code end//

Big thumbs up to the designer of mesh btw, really amazing project

**Comment by vitko-bg** [comment]
Your "_agentCustomization" and "_assistantCustomization" are commented out, get rid of underscore in front, make chahges on text within the blocks, restart MC server and you will see the difference.

**Comment by heidnir** [comment]
Thanks for the replay, I've changed my config.json to the following, still no luck:

//code start//
{
    "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.j$
    "__comment1__": "This is a simple configuration file, all values and sections$
    "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for$
    "settings": {
      "cert": "21.12.131.51",
      "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
      "WANonly": true,
      "_LANonly": true,
      "sessionKey": "MyReallySecretPassword1",
      "port": 443,
      "_aliasPort": 443,
      "_redirPort": 80,
      "_redirAliasPort": 80
    },
    "domains": {
      "": {
        "title": "company name",
        "_title2": "company name",
        "_minify": true,
        "_newAccounts": true,
        "_userNameIsEmail": true,
        "mstsc": true
     },
     "agentCustomization": {
      "displayName": "company name",
      "description": "company agent for remote monitoring, management and assistance.",
      "companyName": "company name",
      "serviceName": "ctagent",
      "fileName": "ctagent"
    },
    "assistantCustomization": {
      "title": "company name",
      "image": "assistant-logo.png",
      "fileName": "ctagent"
    }
    }
  },
    "_letsencrypt": {
      "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/$
      "email": "myemail@mydomain.com",
      "names": "myserver.mydomain.com",
      "production": false
    }
  }
  //code end//

**Comment by vitko-bg** [comment]
Same issue had other user, read below:
https://github.com/Ylianst/MeshCentral/issues/2176#issuecomment-762368666

**Comment by heidnir** [comment]
I've changed to the following:

//code start//
{
    "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.j$
    "__comment1__": "This is a simple configuration file, all values and sections$
    "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for$
    "settings": {
      "cert": "21.12.131.51",
      "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
      "WANonly": true,
      "_LANonly": true,
      "sessionKey": "MyReallySecretPassword1",
      "port": 443,
      "_aliasPort": 443,
      "_redirPort": 80,
      "_redirAliasPort": 80
    },
    "domains": {
      "": {
        "title": "company name",
        "_title2": "company name",
        "_minify": true,
        "_newAccounts": true,
        "_userNameIsEmail": true,
        "mstsc": true
      "agentCustomization": {
      "displayName": "company name",
      "description": "company agent for remote monitoring, management and assistance.",
      "companyName": "company name",
      "serviceName": "ctagent",
      "fileName": "ctagent"
      }
     "assistantCustomization": {
      "title": "company name",
      "image": "assistant-logo.png",
      "fileName": "ctagent"
    }
}
},
//code end//

Doesn't work, keep getting parse error.

**Comment by vitko-bg** [comment]
Try this:
{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.js",
	"comment1": "This is a simple configuration file, all values and sections",
	"comment2": "See node_modules/meshcentral/sample-config-advanced.json for",
	"settings": {
		"cert": "21.12.131.51",
		"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
		"WANonly": true,
		"_LANonly": true,
		"sessionKey": "MyReallySecretPassword1",
		"port": 443,
		"_aliasPort": 443,
		"_redirPort": 80,
		"_redirAliasPort": 80
	},
	"domains": {
		"": {
			"title": "company name",
			"_title2": "company name",
			"_minify": true,
			"_newAccounts": true,
			"_userNameIsEmail": true,
			"mstsc": true,
			"agentCustomization": {
				"displayName": "company name",
				"description": "company agent for remote monitoring, management and assistance.",
				"companyName": "company name",
				"serviceName": "ctagent",
				"fileName": "ctagent"
			},
			"assistantCustomization": {
				"title": "company name",
				"image": "assistant-logo.png",
				"fileName": "ctagent"
			}
		}
	},

**Comment by heidnir** [comment]
Changed my config.json to exactly the above, still doesnt work. This is very weird I don't understand what I'm missing.

I've verified the above code too, getting parse error on line 37.

My basic config file works though:
///code start//

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.j$
  "__comment1__": "This is a simple configuration file, all values and sections$
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for$
  "settings": {
    "cert": "213.172.131.151",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "Computer Teck",
      "_title2": "Computer Teck",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "mstsc": true
   }
},
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/$
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

///code end///

But when I add the customizations, it just does not work.

It must be something silly that we are missing

**Comment by heidnir** [comment]
Something is really strange. I've changed m config back to the following, this is my entire config.json:

///code start///
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.j$
  "__comment1__": "This is a simple configuration file, all values and sections$
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for$
  "settings": {
    "cert": "21.17.11.151",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "CTeck",
      "_title2": "CTeck",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "mstsc": true
   }
},
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/$
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
///code stop///

I've been using it like this for a few days, without any issues. Now, after restarting I get errors:

mesh@mesh:~/meshcentral-data$ node ./node_modules/meshcentral
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/mesh/meshcentral-data/node_modules/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
mesh@mesh:~/meshcentral-data$


The server doesn't start by itself anymore, I tried starting it manually with above command and got those errors. Wondering if I should reinstall the entire system rather

**Comment by vitko-bg** [comment]
> The server doesn't start by itself anymore, I tried starting it manually with above command and got those errors. Wondering if I should reinstall the entire system rather

If you do not have anything to loose - feel free to reinstall it and start from scratch.
Make sure you are adding extras to config.json in correct way.

**Comment by heidnir** [comment]
To help other people in the future maybe, here's my working config.json:

///code start///
{
	"schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.js",
	"comment1": "This is a simple configuration file, all values and sections",
	"comment2": "See node_modules/meshcentral/sample-config-advanced.json for",
	"settings": {
		"cert": "23.17.13.158",
		"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
		"WANonly": true,
		"_LANonly": true,
		"sessionKey": "MyReallySecretPassword1",
		"port": 443,
		"_aliasPort": 443,
		"_redirPort": 80,
		"_redirAliasPort": 80
	},
	"domains": {
		"": {
			"title": "company name",
			"_title2": "company name",
			"_minify": true,
			"_newAccounts": true,
			"_userNameIsEmail": true,
			"mstsc": true,
			"agentCustomization": {
				"displayName": "company name",
				"description": "company name agent for remote assistance.",
				"companyName": "company name",
				"serviceName": "agentname",
				"fileName": "agentname"
			},
			"assistantCustomization": {
				"title": "company name",
				"image": "ctlogo.png",
				"fileName": "agentname"
			}
		},
		"_letsencrypt": {
			"__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/",
			"email": "myemail@mydomain.com",
			"names": "myserver.mydomain.com",
			"production": false
		}
	}
}
///code end///

Thanks vitko-bg for your help, appreciate it.

**Comment by vitko-bg** [comment]
Great news!
Feel free to close the issue as you resolved it :)

**Comment by Ylianst** [comment]
Thank you @vitko-bg!!!
