### ISSUE TITLE
How to get MeshCentralV2 and others questions 

### ISSUE THREAD

**Issue by ecureuilfourbe** [Ylianst/MeshCentral#3308]
Hey,

I've followed the meshcentral installation guide, but still my meshcentral is not the V2, I can't for exemple generate the QR-code for mobile devices, maybe i'm missing something.

some info:
meshcentral is installed on a ubuntu 20.04 desktop using VirtualBox 6.1 on Win10
node version:
       - v10.19.0
npm version:
       - v8.1.4
some Warnings:

![npm](https://user-images.githubusercontent.com/36704066/143859853-223a68c9-3f28-43de-b68d-dcc71f1abe1e.png)
-------------------------------------------------------------------

How to download files from remote to host, again in 2021 ?
I know there is already a topic about that but I just wanted to know if this is possible or not, it would be helpful for my support team to be able to get data in order to change old PCs (and by DATA, i mean the users folder directly)

-------------------------------------------------------------------

Is mesh central suitable for big infra ? ~1500 computers.

-------------------------------------------------------------------

How does meshcentral work for session with multi-users (eg: We connect to a Windows Server for telework, PC -> WS ->remote desktop), do we take control of the server or do we have access to the  "login page" (before conection to Remote Desktop) of the WinServer ?

------------------------------------------------------------------
I hope i'm not bothering you with multiple questions in 1 post
Thanks

**Comment by Ylianst** [comment]
Hi. The MeshCentral you are using is the "v2" version. Over 5 years ago, there was an old version based on ASP.net/IIS/MSSQL that is obsolete and I don't talk about anymore. I used to put "v2" on documentation to differentiate it from the old version. These days, I don't put v2 anymore and just call it MeshCentral as the old version does not exist anymore.

For Android devices, the QR code will only show up when your server is in WAN mode or Hybrid Mode. That is, your server needs to be setup with a known DNS name that Android devices can connect back to. In LAN mode, Android is not supported. I have a [video on LAN/WAN mode here](https://www.youtube.com/watch?v=gx5Fh3pQOns).

You are using a newer Node v10 with an older NPM version, this is not good. You should update NPM for sure or just update both NodeJS and NPM to better versions. 

I am not sure I understand the question about downloading files from old PC's. MeshAgent should work on Windows 8 and higher, but not sure that answers your question.

Yes, MeshCentral is suitable for large deployments, but you should use it with MongoDB or at lease, not the built-in NeDB database. Please use a professional database for production environments. https://meshcentral.com uses a AWS t3.large instance with 2 vCPU's and 8G RAM and has about 10k agents connected to it.

For connecting to multi-user servers: If you use the built-in MeshCentral remote desktop feature, it will by default connect to the local desktop of a remote machine. If many RDP sessions are running on a remote computer, MeshCentral will ask what RDP session you want to remote into. MeshCentral can't create new sessions. This said, MeshCentral does have Web-RDP support (add `"mstsc": true` in settings section to activate this) and will allow RDP session from the MeshCentral web site.

Hope this helps,
Ylian

**Comment by ecureuilfourbe** [comment]
Everything is clear thanks, just one thing, when i'm talking about "get data in order to change old PCs", i mean upgrading all of our Win7 to Win10 and we need to extract the user folder from the "old" computer to the new one, I was wondering if this was possible with meshcentral but apparently, it's not possible

**Comment by Ylianst** [comment]
Glad it was helpful.

You can upload or download files using the MeshCentral "Files" tab, you can also remotely ZIP lots of files which is useful if you need to ZIP an entire folder before downloading it. Additionally, you can perform automated file upload/download using MeshCtrl.js, this is a command line tool that comes with MeshCentral.
