### ISSUE TITLE
Removing two-factor authentication remember cookies

### ISSUE THREAD

**Issue by com-guy** [Ylianst/MeshCentral#3309]
After enabling two factor authentication and during the logon process, there is a check box on the screen where the OTP is entered to remember the device/browser for 30 days.  I can find no way to disable this.  Am I missing something, or can I request this as a feature?

**Comment by Ylianst** [comment]
For all config.json options, take a look at the [schema here](https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json). There is an [option here](https://github.com/Ylianst/MeshCentral/blob/a2ce9b85733c47443b1037f44ba1cbba41861795/meshcentral-config-schema.json#L425) to set the 2FA cookie timeout or disable it.

So, add this line in the domain section of the config.json:

```
"twoFactorCookieDurationDays": 0
```

That should disable it. Let me know if it works and close this issue if it does. Thanks.

**Comment by Ylianst** [comment]
Fixed poorly worded title.

**Comment by Ylianst** [comment]
No response in 7 days, closing.

**Comment by com-guy** [comment]
Thanks for the reply.  I got extremely busy and this issue went to the back burner...
Adding that to the Domains section did make it work the way I prefer.
