### ISSUE TITLE
Feature Request: Recordings on demand for mesh user training

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#3313]
Guys, not sure if this already possible. 

I would like to be able to click the record button to record a session....then have that go to the "recordings" section..... 

Except, I'd like to be able to have a section that is visible to other mesh users, and be able to rename the recordings.

Use Case:
All of our helpdesk techs use Mesh for remote support.  Sometimes, a senior tech might perform a task that, say a junior tech doesn't know how to do. 

For example.  a person can create a new user in a system.  They press the record button, record the demonstration, it's saved to "My FIles\Recordings", but make that visible to other techs\users.

Then be able to rename that recording "User creation in system"

Now, a user only has to go to the video section and watch the recording on how to perform that task again....but without having to bother the senior tech for help.  Is this possible?  It would be essentially a "video knowledgebase".

This would be a huge feature for all of our team!

Thanks as always

Shane- Southeastern Tech

**Comment by si458** [comment]
one way around this is the following
enable the sessionrecording
do your session,
then go into the recordings tab, and click the DOWNLOAD icon next to the session you want
rename ur file locally (keep the `mcrec` file extension),
store the file on a server or something,
then tell ur staff to visit `https://SERVERURL/player.htm` and then can click `open file` button,
select the file, then click play!

**Comment by si458** [comment]
also in theory, if you set `localSessionRecording: true` under `domains` in config.json,
you will get a camcorder button in the bottom right, and when clicked it starts recording the session in your browser,
then when you finish, click it again, and it will download a mcrec file,
which you can save anywhere,
and when you want to play it back, load up `https://MESHCENTRALSERVERURL/player.htm` and open the file
![image](https://github.com/Ylianst/MeshCentral/assets/765314/8218f3ff-da9c-43a3-bd4d-30b992d58808)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/98944d76-49db-4440-aca8-a84e2d9c6d82)
