### ISSUE TITLE
On Linux, server starts in LAN mode instead of Hybrid (LAN + WAN) after a new DNS domain is added (Let's Encrypt support)

### ISSUE THREAD

**Issue by djarril** [Ylianst/MeshCentral#3314]
Hello,

After adding a domain using the DNS mode (with Let's Encrypt) At the first start, the LAN mode us used.
I need to relaunch it to get back to the Hybrid (LAN + WAN) mode.

Best regards,
Denis

NodeJS : v12.22.7
MeshCentral :  v0.9.55
Linux : Debian 10

> leevents
12/1/2021 5:45:29 PM - Getting certs from local store (Production)
12/1/2021 5:45:29 PM - Reading certificate files
12/1/2021 5:45:29 PM - Setting LE cert for default domain.
12/1/2021 5:45:29 PM - Setting LE cert for domain ---.
12/1/2021 5:45:29 PM - Setting LE cert for domain -----.
12/1/2021 5:45:29 PM - Setting LE cert for domain ----.
12/1/2021 5:45:29 PM - Setting LE cert for domain ---.
12/1/2021 5:45:34 PM - Certificate has 89 day(s) left.
12/1/2021 5:45:34 PM - Certificate is ok.

root@meshcentral:~# service meshcentral restart
root@meshcentral:~# service meshcentral status
? meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-12-01 17:43:57 CET; 11s ago
 Main PID: 52867 (node)
    Tasks: 29 (limit: 958)
   Memory: 517.4M
   CGroup: /system.slice/meshcentral.service
           +-52867 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral
           +-52879 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral --launch 52867
           +-52895 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshaccelerator.js

Dec 01 17:43:57 meshcentral systemd[1]: Started MeshCentral Server.
Dec 01 17:44:01 meshcentral node[52867]: MeshCentral HTTP redirection server running on port 80.
Dec 01 17:44:01 meshcentral node[52867]: Generating certificates, may take a few minutes...
Dec 01 17:44:01 meshcentral node[52867]: Generating HTTPS certificate for aot...
Dec 01 17:44:03 meshcentral node[52867]: WARNING: Add "cert" value to settings in config.json before using Let's Encrypt.
Dec 01 17:44:03 meshcentral node[52867]: MeshCentral v0.9.55, LAN mode, Production mode.
Dec 01 17:44:05 meshcentral node[52867]: WARNING: SMTP server has limited use in LAN mode.
Dec 01 17:44:05 meshcentral node[52867]: Server aot has no users, next new account will be site administrator.
Dec 01 17:44:05 meshcentral node[52867]: MeshCentral HTTPS server running on port 3443, alias port 3443.
Dec 01 17:44:05 meshcentral node[52867]: SMTP mail server -------.-----------.-- working as expected.
root@meshcentral:~# service meshcentral restart
root@meshcentral:~# service meshcentral status
? meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-12-01 17:45:00 CET; 9s ago
 Main PID: 52924 (node)
    Tasks: 36 (limit: 958)
   Memory: 508.8M
   CGroup: /system.slice/meshcentral.service
           +-52924 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral
           +-52935 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral --launch 52924
           +-52946 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshaccelerator.js
           +-52953 /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshaccelerator.js

Dec 01 17:45:00 meshcentral systemd[1]: Started MeshCentral Server.
Dec 01 17:45:04 meshcentral node[52924]: MeshCentral HTTP redirection server running on port 80.
Dec 01 17:45:04 meshcentral node[52924]: MeshCentral v0.9.55, Hybrid (LAN + WAN) mode, Production mode.
Dec 01 17:45:06 meshcentral node[52924]: MeshCentral Intel(R) AMT server running on --.--------------.---:4433.
Dec 01 17:45:06 meshcentral node[52924]: Server aot has no users, next new account will be site administrator.
Dec 01 17:45:06 meshcentral node[52924]: MeshCentral HTTPS server running on --.--------------.---:3443, alias port 3443.
Dec 01 17:45:07 meshcentral node[52924]: SMTP mail server -------.-----------.-- working as expected.

**Comment by Ylianst** [comment]
I have not seen this before. Looking at this line:

```
Generating certificates, may take a few minutes...
```

Looks like it could not fine it's certificates in `meshcentral-data` and generated new ones. There is a config.json, but it seems the the `settings` section may have been ignored. I guess one possible issue would the access rights to `meshcentral-data` files, but not sure.

Can you send your config.json and put XXXX any any confidential parts? I would need to try to replicate this.

**Comment by djarril** [comment]
[config.txt](https://github.com/Ylianst/MeshCentral/files/7637226/config.txt)

The rights on the files are available for root.
Service installed with the -install option : 
--------------------------------------------------------------------------------------------------------
root@meshcentral:/opt/meshcentral/meshcentral-data# cat /etc/systemd/system/meshcentral.service
[Unit]
Description=MeshCentral Server

[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshcentral
WorkingDirectory=/root/.meshcentral
Environment=NODE_ENV=production
User=root
Group=root
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service

[Install]
WantedBy=multi-user.target
--------------------------------------------------------------------------------------------------------

Files should have the good rights !
--------------------------------------------------------------------------------------------------------
root@meshcentral:/opt/meshcentral/meshcentral-data# ls -la
total 6056
drwxr-xr-x 3 root root    4096 Dec  1 18:18 .
drwxr-xr-x 6 root root    4096 Dec  1 16:43 ..
-rw-r--r-- 1 root root    2498 Nov 22 15:24 agentserver-cert-private.key
-rw-r--r-- 1 root root    1538 Nov 22 15:24 agentserver-cert-public.crt
-rw-r--r-- 1 root root    2653 Dec  1 22:20 config.json
drwxr-xr-x 2 root root    4096 Nov 24 16:54 letsencrypt-certs
-rw-r--r-- 1 root root  158292 Dec  1 22:14 meshcentral.db
-rw-r--r-- 1 root root 2256518 Dec  1 22:28 meshcentral-events.db
-rw-r--r-- 1 root root   90608 Dec  1 21:51 meshcentral-power.db
-rw-r--r-- 1 root root  589308 Dec  1 22:28 meshcentral-stats.db
-rw-r--r-- 1 root root    1706 Nov 24 15:29 mpsserver-cert-private.key
-rw-r--r-- 1 root root    1504 Nov 24 15:29 mpsserver-cert-public.crt
-rw-r--r-- 1 root root    2494 Nov 22 15:24 root-cert-private.key
-rw-r--r-- 1 root root    1566 Nov 22 15:24 root-cert-public.crt
-rw-r--r-- 1 root root     216 Dec  1 18:18 serverstate.txt
-rw-r--r-- 1 root root 3001635 Nov 22 23:03 translate.json
-rw-r--r-- 1 root root    2498 Dec  1 17:44 webserver-aot-cert-private.key
-rw-r--r-- 1 root root    1686 Dec  1 17:44 webserver-aot-cert-public.crt
-rw-r--r-- 1 root root    2494 Nov 23 01:44 webserver-atc-cert-private.key
-rw-r--r-- 1 root root    1686 Nov 23 01:44 webserver-atc-cert-public.crt
-rw-r--r-- 1 root root    2498 Nov 22 15:24 webserver-cert-private.key
-rw-r--r-- 1 root root    1650 Nov 22 15:24 webserver-cert-public.crt
-rw-r--r-- 1 root root    2498 Dec  1 16:43 webserver-ophl-cert-private.key
-rw-r--r-- 1 root root    1698 Dec  1 16:43 webserver-ophl-cert-public.crt
-rw-r--r-- 1 root root    2494 Nov 26 12:49 webserver-splash-cert-private.key
-rw-r--r-- 1 root root    1720 Nov 26 12:49 webserver-splash-cert-public.crt
--------------------------------------------------------------------------------------------------------

**Comment by djarril** [comment]
Sorry for the page layout. Just copy and paste from Linux :(

**Comment by Ylianst** [comment]
No problem, just fixed it. If you can look at #3315 and fix the `agentConfig` section that is not correct, let me know if that improves things.
