### ISSUE TITLE
Agent not installing on Windows 11 Insider Preview

### ISSUE THREAD

**Issue by IonicEcko** [Ylianst/MeshCentral#3316]
Am having an issue where, on 2 machines on the latest Dev Beta of Windows 11 the client will not install. Running the installer as admin has a command prompt flash briefly but it disappears and nothing is installed.

I realize the Dev Beta is just that and things may not work with it, but am a little stumped where to look for issues.

Is there a log somewhere I can look into?

MeshCentral version: 0.9.55

**Comment by krayon007** [comment]
Did you try with the release version of Win 11? I have the agent installed on two Windows 11 machines I setup a few weeks ago.

Which install method did you try to use?

**Comment by IonicEcko** [comment]
I just tried to run the EXE as an admin.

I've just run the installer with the -install command and everything works so it would seem to be an issue with the GUI.

Happy to close this if its not worth looking into, but may be an issue coming down the pipeline?

**Comment by krayon007** [comment]
You can leave it open for now. My Win11 machines I also installed from the command line. I can take a look to see what's going on.

**Comment by krayon007** [comment]
I just tried the GUI installer on my Windows 11 machines, and they seem to work fine. 
When you used the GUI installer, did it create anything in Program FIles? Did it copy any files?

It's wierd that the command line installer worked and the GUI didn't, becuase all the GUI does, is spawn a child process and run the command line installer.

**Comment by krayon007** [comment]
Did you AV by chance delete/block the install?

**Comment by IonicEcko** [comment]
I've just tested again, current release version is fine. Insider preview (Dev channel) is still broken.

Only AV software on it is Defender and its not showing any action taken.

**Comment by krayon007** [comment]
Interesting. I'll try to build a dev channel VM and do some testing.

**Comment by Ylianst** [comment]
I am going to close this one since it's not reasonable for us to test on early Windows dev builds that many have many issues. Also, not mentioning in the original report that this was a Windows dev build is not cool.
