### ISSUE TITLE
Last Access Date in My Users Tab only reflects Last Access of the Website

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#3319]
I actually look at this feature to see when accounts are going stagnant and lock them accordingly. I allow other clients to access certain machines they own but if they aren't using the functionality, I lock it down for lots of good reasons. 

I went in to check today to find I have a user I know uses it on nearly a daily basis, but their date was the day we setup their account, not the last time they used their account. 

This user only uses MeshRouter to RDP to their host, which leads me to believe that Last Access date is only the last time they hit the website which they will likely never do again. Or only in the case of needing a password reset. 

Could the date reflect the last time any activity has occurred with the user as long as the user was authenticated?

**Comment by Ylianst** [comment]
Your right. If I recall correctly, the database updates that value only on user login on the main web site, so it does not represent the user's real usage of the site. I will fix this.

**Comment by Ylianst** [comment]
Checked in a fix for this. In addition to keeping the last login time and the creation time of the account, I now keep the last access time. Last access time is updated when a user session is connected or disconnected and when a relay (desktop, terminal, file) session is setup.

To keep load off the server, if the access time is not going to move forward more than 5 minutes, the update is not done. So, rapidly starting and stopping a remote desktop session will not cause the users last access to update unless it's 5 minute from the last update.

The "Last Access" in column in "My Users" will now show the new last access value, but still how last login for users that have not logged in with the new server.

**Comment by githubbiswb** [comment]
Awesome, that sounds awesome. I will update when my upstream container updates and confirm the fix, although I have never had you steer me wrong before. Thank you for all of your hard work

**Comment by Ylianst** [comment]
Thanks, always good to have someone verify the work... I can always miss something.

**Comment by githubbiswb** [comment]
I checked it, but it didn't seem to modify the date. I had a test user, I brought through meshrouter and connected to their desktop, but the date didn't change.

**Comment by githubbiswb** [comment]
@Ylianst I am still showing the date not updating, this is also a user who isn't assigned any groups, just a device it can get to, not sure if that would matter

**Comment by githubbiswb** [comment]
@Ylianst I still am seeing a stale date on the last user logged in. I have a user I saw yesterday logged in and was working for a while, and there last logged in date was 11/18/2021 
![S95LahqGia](https://user-images.githubusercontent.com/51446227/163817301-ab32a9c7-8962-4b6d-81ff-87644df131fe.png)

**Comment by dinger1986** [comment]
Looks fine to me now @si458 can close
