### ISSUE TITLE
Feature Request: Set temporarily a remote computer or group to not goto sleep for x amount of time

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#332]
It would be super awesome to have an option in the interface to set a remote computer or group to not goto sleep for a time specified and after that time has expired then revert back to the normal power profile. We sometimes do remote maintenance at night usually weekly or monthly depending and it would be a amazing to have this option. Thanks to you and Intel for providing such a great tool! Keep up the great work!!

**Comment by Ylianst** [comment]
Hi and thank you. Bryan would have to look into this and add a support for this in the agent. Are you are asking for Windows / Linux / MacOS? I imagine the power control of various operating systems are all very different, I can't imagine this is going to be easy.

**Comment by Ylianst** [comment]
FYI. We are swamped with feature requests. We will see what Bryan can do about this one.

**Comment by dinger1986** [comment]
this can be done with a script @si458 I think its a very small use case

**Comment by si458** [comment]
this is more of a remote management feature than a remote support feature
please check out [tacticalrmm](https://github.com/amidaware/tacticalrmm)
