### ISSUE TITLE
cannot create user if ldap authentication is enable

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3321]
Hello,
when i enable ldap authentication, i cannot create new users.
If I turn off ldap authentication, I can create users.
I am using version 0.9.55 of MeshCentral
Can you help me
thank you

**Comment by pascal-chag** [comment]
The following message is displayed:
New Account: Permission refused

**Comment by Ylianst** [comment]
Are you talking about this button? When you get "Permission refused", what did you do?

In general, when you run MeshCentral with LDAP, you no longer create users in MeshCentral. Instead, you create users in your LDAP directory and then they can login to MeshCentral. So, if you can explain your use case? You want LDAP users and MeshCentral local users are the same time? - Thanks

![image](https://user-images.githubusercontent.com/1319013/144725028-9841af56-8eec-473a-97d8-dba3f1113bfb.png)

**Comment by pascal-chag** [comment]
thank you for your reply.
Yes that's exactly this button I'm talking about.
ok, I thought it was necessary to create the account in MeshCentral before trying to identify myself with.

My use case:
I created a first non-administrator account named testinfo6 with Partial permissions. I don't remember if I created this account before connecting MeshCentral to my ldap directory, but probably so.
This testinfo6 account exists in my ldpa directory.
I then configured MeshCentral so that the password is verified on the ldpa directory.
I entered the directory password for this account and it worked well.
I added some rights / restrictions on this account, everything is ok.
I added google two-factor authentication for this account, everything is ok.

Still from my computer, I then tried to connect with a new account named testinfo7 which is present in my directory, but does not exist in MeshCentral.
I enter the directory password, and to my surprise a token is requested.
I have seen ldap requests pass between the MeshCentral server and my ldpa directory (samba4).
The network captures on the ldap directory indicate a BindRequest sucess with the testinfo7 account.

Before going any further, I connect to the MeshCentral console with an Administrator account, and I see that the testinfo6 account is renamed / replaced by testinfo7 even though I did not enter the token.
In the list of events on the MeshCentral server, a message indicates that the account name has changed.
The userId of this message is the same as that of the messages which indicate that the user testinfo6 is correctly identified.
Still from my computer, I tried to log in with the testinfo7 account from a browser never used with testinfo6 believing that there was a cookie that could keep my identity, but the same thing happened.

That's why I tried to create the testinfo7 account directly in MeshCentral, with the button you indicate and I got the message: 'New Account: Permission refused'

How do I create and test this new account from my computer?
Thank you

**Comment by pascal-chag** [comment]
I also tried from another computer with the testinfo7 account, the same thing happened again.
I also tried with the testinfo5 account, again the same thing.
each time the user testinfo6 is renamed

**Comment by pascal-chag** [comment]
For other users of my ldap directory, it works fine, another user appears in the MeshCentral console without the original user (testinfo6) being renamed. I cannot identify what is causing the renaming of the testinfo6 account for some accounts in my directory.

**Comment by Ylianst** [comment]
Hi. If you go to "My Users" tab and click on a user with the problem, look for "User Identifier". It may be that you have many LDAP accounts that have the same identifier, so MeshCentral will think it is the same user. When you login, the identifier is the same so MeshCentral will update information about the account.

![image](https://user-images.githubusercontent.com/1319013/144814038-9db817ce-1e7b-40fe-9d43-a13bba42eae0.png)

You may able to use the following options in config.json to fix the problem:

```
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "objectSid",
```

Let me know if that helps.

**Comment by pascal-chag** [comment]
Hello,
I'm already using the parameter
"ldapUserBinaryKey": "objectSid".
I replaced "ldapUserName": "cn", with "ldapUserName": "displayName".
When my user is renamed, it keeps the same user identifier.

![2021-12-06 09_47_43-MeshCentral GH-MSM](https://user-images.githubusercontent.com/95504809/144837708-8c9166bc-ae37-4c31-a302-102eb4d1a47b.png)

![2021-12-06 09_52_09-MeshCentral GH-MSM](https://user-images.githubusercontent.com/95504809/144837688-9f80ef49-2843-48f4-b14e-ab60179cfb2a.png)

I looked in my ldap directory, my 2 users testinfo6 and testinfo7 have different objectSid.

![2021-12-06 09_57_47-ad-mgmt chag gihsm fr (CHAG_Administrator)  samba-admin](https://user-images.githubusercontent.com/95504809/144837799-5be19b12-63a1-4861-af6b-00033c10da54.png)

![2021-12-06 09_56_33-ad-mgmt chag gihsm fr (CHAG_Administrator)  samba-admin](https://user-images.githubusercontent.com/95504809/144837750-8626d4ac-3322-4ad8-91b8-cd5e12c3cd6f.png)

I will try by removing user testinfo6 from meshcentral.

Thank you for your help

**Comment by pascal-chag** [comment]
It's the same when I remove the user from MechCentral.

**Comment by Ylianst** [comment]
So, obviously, the user is renamed because the identifier is the same. The identifier 01050000... must come from somewhere. You will need to find where that value comes from and fix the LDAP accounts or use a different value as the account unique identifier.

**Comment by pascal-chag** [comment]
I cannot find where this identifier comes from, which remains the same with the testinfo6 and testinfo7 accounts in my ldap directory.

When I deleted the unique account in MeshCentral and logged in again with the testinfo6 ldap account, the account appeared in MeshCentral with the same id as before deletion (user // 010500000000000515000000fd2d14fd6bc14737fdfdfd120000).
How is the User Identifier generated in MeshCentral? Does it depend on the objectSid or objectGUID attributes of the ldap directory account?

Maybe the account was not deleted from the MeshCentral database but only hidden?
How to do a real deletion?

**Comment by babaymaster** [comment]
same problem, different users have same id.
i change attribute to -       "ldapUserBinaryKey": "objectGUID"
Problem resolved.

**Comment by si458** [comment]
you cannot create users in meshcentral when you use LDAP, you must create them inside your AD/LDAP instead

**Comment by christoph-wijns** [comment]
> you cannot create users in meshcentral when you use LDAP, you must create them inside your AD/LDAP instead

Is still the case ?
