### ISSUE TITLE
unable to connect to server if i add another domain in letsencrypt

### ISSUE THREAD

**Issue by nagainfotech** [Ylianst/MeshCentral#3322]
![image](https://user-images.githubusercontent.com/70787590/144708021-6e64b91a-d8d6-4bac-8575-c4b5baced2f0.png)

For letsencrypt if i just have my domain which is remote.nagainfotech.com then it works fine but as soon as i add another domain even my domain doesnt connect.

 "names": "remote.nagainfotech.com,remote.thebeautybrowparlour.com.au",

Please advise what is wrong here?

**Comment by nagainfotech** [comment]
[NITconfig.txt](https://github.com/Ylianst/MeshCentral/files/7653841/NITconfig.txt)
Please see attached my config file

**Comment by nzalev** [comment]
I haven't been able to reproduce this. I set my config as close to yours as possible: 
I set the following for letsencrypt:
```json
  "letsencrypt": {
    "email": "ttsadmin@nzalev.ca",
    "names": "tts.zalev.ca,tts.nzalev.ca",
    "production": true
  }
```
I added a second domain with dns set to `tts.nzalev.ca`, the same way you have a second domain with the dns entry set as the second item in letsencrypt's names. I also took all the domain options that you have in the config file you gave, and set the cert option in settings as the first item from le names. However, it pulls a new certificate without issue.

Can you describe what you mean by "even my domain doesnt connect"? Do you mean that it will not pull a new certificate for your primary domain, or something else like you cannot connect to your server?

You should try running the server interactively to see if there are any errors produced. To do this, you can go to the location of meshcentral in a command prompt/shell and run `node node_modules/meshcentral --debug cert`

**Comment by Ylianst** [comment]
I cleaned up the config.json to remove all ignored lines (below) and it looks ok to me. I have the same questions as @nzalev, also, in `meshcentral-data`, look for `mesherrors.txt`. If there are any errors in that file, please send the errors here. Thanks.

```
{
  "settings": {
    "cert": "remote.xxx.com",
    "mongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "port": 443,
    "manageCrossDomain": [ "user//santosh" ],
    "watchDog": {
      "interval": 100,
      "timeout": 400
    }
  },
  "domains": {
    "": {
      "siteStyle": 2,
      "title": "Naga Info Tech",
      "title2": "Remote Server",
      "titlePicture": "NIT4MC.png",
      "loginPicture": "NIT4MC.png",
      "minify": true,
      "PreconfiguredRemoteInput": [
        {
          "name": "CompagnyUrl",
          "value": "https://help.mycompany.com/"
        },
        {
          "name": "Any Text",
          "value": "Any text\r"
        },
        {
          "name": "Welcome",
          "value": "Default welcome text"
        }
      ],
      "myServer": {
        "Backup": false,
        "Restore": false,
        "Upgrade": false,
        "ErrorLog": false,
        "Console": false,
        "Trace": false
      },
      "userConsentFlags": {
        "desktopnotify": true,
        "terminalnotify": true,
        "filenotify": true,
        "desktopprompt": true,
        "terminalprompt": true,
        "fileprompt": true,
        "desktopprivacybar": true
      }
    },
    "TBBP": {
      "dns": "remote.xxxx.com.au",
      "title": "TBBP",
      "title2": "RemoteServer",
    }
  },
  "letsencrypt": {
    "email": "santosh@xxx.com",
    "names": "remote.xxx.com",
    "production": true
  }
}
```

**Comment by nagainfotech** [comment]
Hi Nzalev and Ylian, thanks for getting back to me.

I went through my settings again and now i can connect to my domain.
what was happening before was when i added second domain in "names" section for letsencrypt i was loosing my certificate but for some reason its ok now.
Now when i go to the second domain to login to meshcentral i have to type https:// in front and then it complains about certificate not valid and not secure.


![image](https://user-images.githubusercontent.com/70787590/144728160-4995a3fb-a120-4611-99ee-9a1022e73e95.png)

**Comment by nzalev** [comment]
The browser complains that the certificate is not valid, because it is a self signed certificate generated by meshcentral.
![Screenshot from 2021-12-04 18-57-29](https://user-images.githubusercontent.com/63608819/144728378-edf23032-ed32-4d28-a597-c3912ae11813.png)

Again, you should run meshcentral interactively via `node node_modules/meshcentral --debug cert` to see what is going on.

**Comment by nagainfotech** [comment]
![image](https://user-images.githubusercontent.com/70787590/144728816-bb4657d0-6d7d-4838-a2e9-92ea9cbfc070.png)

**Comment by nzalev** [comment]
I am guessing you did not shut down your meshcentral instance before running it interactively? You cannot have more than one process running bound to the same port, and LE requires port 80.

If port 80 is bound by another instance of meshcentral, it must be shut down first. If it bound by a different process, then that is the source of your problem.

**Comment by nagainfotech** [comment]
OK i stopped the MC server and ran it again, please see below:

^CServer Ctrl-C exit...
santosh@remote:~$
santosh@remote:~$ sudo systemctl status meshcentral.service
[sudo] password for santosh:
● meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor p>
     Active: active (running) since Sat 2021-12-04 22:47:27 AEDT; 23h ago
   Main PID: 523 (node)
      Tasks: 22 (limit: 2344)
     Memory: 330.2M
     CGroup: /system.slice/meshcentral.service
             ├─523 /usr/bin/node /home/santosh/node_modules/meshcentral
             └─591 /usr/bin/node /home/santosh/node_modules/meshcentral --launc>

Dec 04 22:47:27 remote systemd[1]: Started MeshCentral Server.
Dec 04 22:47:31 remote node[523]: MeshCentral HTTP redirection server running o>
Dec 04 22:47:32 remote node[523]: MeshCentral v0.9.56, WAN mode, Production mod>
Dec 04 22:47:33 remote node[523]: MeshCentral Intel(R) AMT server running on re>
Dec 04 22:47:33 remote node[523]: Server tbbp has no users, next new account wi>
Dec 04 22:47:33 remote node[523]: MeshCentral HTTPS server running on remote.na>
lines 1-16/16 (END)
● meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-12-04 22:47:27 AEDT; 23h ago
   Main PID: 523 (node)
      Tasks: 22 (limit: 2344)
     Memory: 330.2M
     CGroup: /system.slice/meshcentral.service
             ├─523 /usr/bin/node /home/santosh/node_modules/meshcentral
             └─591 /usr/bin/node /home/santosh/node_modules/meshcentral --launch 523

Dec 04 22:47:27 remote systemd[1]: Started MeshCentral Server.
Dec 04 22:47:31 remote node[523]: MeshCentral HTTP redirection server running on port 80.
Dec 04 22:47:32 remote node[523]: MeshCentral v0.9.56, WAN mode, Production mode.
Dec 04 22:47:33 remote node[523]: MeshCentral Intel(R) AMT server running on remote.nagainfotech.com:4433.
Dec 04 22:47:33 remote node[523]: Server tbbp has no users, next new account will be site administrator.
Dec 04 22:47:33 remote node[523]: MeshCentral HTTPS server running on remote.nagainfotech.com:443.
~
~
~
~
~
~
~

santosh@remote:~$ sudo systemctl stop meshcentral.service
santosh@remote:~$
santosh@remote:~$
santosh@remote:~$ node node_modules/meshcentral --debug cert
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Production)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.9.56, WAN mode.
MeshCentral Intel(R) AMT server running on remote.nagainfotech.com:4433.
MeshCentral HTTPS server running on remote.nagainfotech.com:443.
CERT: LE: Certificate has 70 day(s) left.
CERT: LE: Missing name "remote.thebeautybrowparlour.com.au".
CERT: LE: Asking for new certificate because of missing names.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Failed to obtain certificate: Fetching http://remote.thebeautybrowparlour.com.au/.well-known/acme-challenge/_gDWvCxiV73mU67purJPyTABGhwvxMIeGadsn6uGTss: Timeout during connect (likely firewall problem)

santosh@remote:~$ sudo systemctl status meshcentral.service
[sudo] password for santosh:
● meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor p>
     Active: active (running) since Sat 2021-12-04 22:47:27 AEDT; 23h ago
   Main PID: 523 (node)
      Tasks: 22 (limit: 2344)
     Memory: 330.2M
     CGroup: /system.slice/meshcentral.service
             ├─523 /usr/bin/node /home/santosh/node_modules/meshcentral
             └─591 /usr/bin/node /home/santosh/node_modules/meshcentral --launc>

Dec 04 22:47:27 remote systemd[1]: Started MeshCentral Server.
Dec 04 22:47:31 remote node[523]: MeshCentral HTTP redirection server running o>
Dec 04 22:47:32 remote node[523]: MeshCentral v0.9.56, WAN mode, Production mod>
Dec 04 22:47:33 remote node[523]: MeshCentral Intel(R) AMT server running on re>
Dec 04 22:47:33 remote node[523]: Server tbbp has no users, next new account wi>
Dec 04 22:47:33 remote node[523]: MeshCentral HTTPS server running on remote.na>
lines 1-16/16 (END)
● meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-12-04 22:47:27 AEDT; 23h ago
   Main PID: 523 (node)
      Tasks: 22 (limit: 2344)
     Memory: 330.2M
     CGroup: /system.slice/meshcentral.service
             ├─523 /usr/bin/node /home/santosh/node_modules/meshcentral
             └─591 /usr/bin/node /home/santosh/node_modules/meshcentral --launch 523

Dec 04 22:47:27 remote systemd[1]: Started MeshCentral Server.
Dec 04 22:47:31 remote node[523]: MeshCentral HTTP redirection server running on port 80.
Dec 04 22:47:32 remote node[523]: MeshCentral v0.9.56, WAN mode, Production mode.
Dec 04 22:47:33 remote node[523]: MeshCentral Intel(R) AMT server running on remote.nagainfotech.com:4433.
Dec 04 22:47:33 remote node[523]: Server tbbp has no users, next new account will be site administrator.
Dec 04 22:47:33 remote node[523]: MeshCentral HTTPS server running on remote.nagainfotech.com:443.
~
~
~
~
~
~
~

santosh@remote:~$ sudo systemctl stop meshcentral.service
santosh@remote:~$
santosh@remote:~$
santosh@remote:~$ node node_modules/meshcentral --debug cert
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Production)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.9.56, WAN mode.
MeshCentral Intel(R) AMT server running on remote.nagainfotech.com:4433.
MeshCentral HTTPS server running on remote.nagainfotech.com:443.
CERT: LE: Certificate has 70 day(s) left.
CERT: LE: Missing name "remote.thebeautybrowparlour.com.au".
CERT: LE: Asking for new certificate because of missing names.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Failed to obtain certificate: Fetching http://remote.thebeautybrowparlour.com.au/.well-known/acme-challenge/_gDWvCxiV73mU67purJPyTABGhwvxMIeGadsn6uGTss: Timeout during connect (likely firewall problem)


what is the cause for this? how can i add the LE

**Comment by nagainfotech** [comment]
Did online SSL check to find that the certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. 
https://www.sslshopper.com/ssl-checker.html#hostname=https://remote.thebeautybrowparlour.com.au/

how do i install chain certificate in meshcentral?

**Comment by nzalev** [comment]
The certificate chains are not the issue here. 

<pre><b>~</b></font>$ telnet remote.thebeautybrowparlour.com.au <b>80</b>
Trying 45.124.53.150...
<b>telnet: Unable to connect to remote host: Connection timed out</b><br>
<font color="#4CE64C"><b>~</b></font>$ telnet remote.thebeautybrowparlour.com.au <b>443</b>
Trying 45.124.53.150...
Connected to remote.thebeautybrowparlour.com.au.
Escape character is &apos;^]&apos;.
^]
telnet&gt; Connection closed.
<font color="#4CE64C"><b>~</b></font>$ 
</pre>

Your web server does not appear to be accessible on port 80. If your server cannot be reached on port 80, you cannot obtain a certificate from Lets Encrypt.

If you are running meshcentral behind a NAT firewall, be sure to forward port 80. Similarly, if you are using any kind of proxy, it needs to forward port 80. If the server is VPS, many VPS providers have their own firewall you can configure in their dashboard.

**Comment by nagainfotech** [comment]
Hi Noah,
mine is a  vps. i am sure port 80 should be open otherwise how is
remote.nagainfotech.com able to connect.
is there a way we can check in ubuntu server

Kind Regards,
Santosh T
NagaInfoTech <http://www.nagainfotech.com>

**Comment by nagainfotech** [comment]
i have just allowed port 80 as well but still cant see certificate coming
through.



Kind Regards,
Santosh T
NagaInfoTech <http://www.nagainfotech.com>

**Comment by nagainfotech** [comment]
all good tested it now and is working fine
thanks for your help guys
please close the ticket
Kind Regards,
Santosh T
NagaInfoTech <http://www.nagainfotech.com>
