### ISSUE TITLE
combine agent and assistant as 1 install and provide msi file for windows AD deployment

### ISSUE THREAD

**Issue by lcslouis** [Ylianst/MeshCentral#3324]
Hello I need a combined agent and assistant. and a msi file for windows AD based deployments.

also I would also like to personalize both the agent and the assistant as follows

Custom agent name.
Custom Assitant name.
Custom Agent Logo
Custom Agent configuration such as Agent Select and tray options. 

If there is a way to this already please point me in the direction to do this. 

Also are there any Help Desk software or other chat plugins that I can integrate? 

I have just discovered MeshCentral But I have been using commerical RMM tools for a while. 

also on the remote control in the browser is there anyway to have application / tech client that can be used instead of the web browser in remote control. 

I know there is VNC and RDP but in most cases the remote control in the browser which lets the user maintain control and lets a tech control at the same time is critical.

**Comment by Ylianst** [comment]
Hi. Lots here. For agent customization, add these lines to the domain section of the config.json. You don't need to put all of these values but these are interesting ones.

```
      "desktopPrivacyBarText": "Privacy bar: {0} ({1})",
      "consentMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) requesting remote desktop access. Grant access?",
        "Terminal": "{0} ({1}) requesting remote terminal access. Grant access?",
        "Files": "{0} ({1}) requesting remote files access. Grant access?"
      },
      "notificationMessages": {
        "Title": "MeshCentral",
        "Desktop": "{0} ({1}) started a remote desktop session.",
        "Terminal": "{0} ({1}) started a remote terminal session.",
        "Files": "{0} ({1}) started a remote files session."
      },
      "agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      },
      "assistantCustomization": {
        "title": "Compagny® Product™",
        "image": "assistant-logo.png",
        "fileName": "compagny"
      },
      "androidCustomization": {
        "title": "Compagny® Product™",
        "subtitle": "Product Subtitle™",
        "image": "assistant-logo.png"
      },
```

Also, for server branding, you can look at [my video on that topic here](https://www.youtube.com/watch?v=Hg4CnrkFUzU). There is no way to change the agent icon right now, but you can wrap it in a MSI and run "meshagent.exe --fullinstall" to install from the command line.

MeshCentral has a built-in chat system called MeshMessenger, just hit the "chat" button and it should open a browser window on the remote side.

For remote desktop, you can download "MeshCentral Router" for Windows from your server and use that to login. Once connected, you can right click on any device and select "Remote Desktop" to see the desktop without using a browser. You can see a [demonstration of MeshCentral Router here](https://www.youtube.com/watch?v=BubeVRmbCRM).

**Comment by ManZosh** [comment]
@Ylianst Hi Ylian, building on the above here.. what is the proper way to deploy the MeshCentral agent across many computers within a standard Active Directory environment, - _without_ using 3rd party deployment tools? My SysAdmins have been racking their heads the last 2 days trying deploy this successfully! There isn't an MSI (_any reason why not?_) and wrapping the meshagent64.exe in with MSIwrapper doesn't install it properly, even with using your `--fullinstall` argument. We've also reviewed all your documentation and haven't found anything regarding an on-ramp to successfully deploy the endpoint agent.

**Comment by dinger1986** [comment]
Deploy using powershell, or bat, most deployment tools support both.

@si458 can close

**Comment by si458** [comment]
you can use 'Advanced installer' for this
customise exes in meshcentral,
download them, 
add them into advanced installer
then tell advanced installer to put the exes into temp folder or program files etc,
then run the 'meshagent.exe -fullinstall' command to silent install it
