### ISSUE TITLE
Question about Let's Encrypt : Can we use a star domain in "names"

### ISSUE THREAD

**Issue by Secure-Concept** [Ylianst/MeshCentral#3326]
Hello,

Is it possible to use a star for multiple DNS domains in the "letencrypt" section ?
No change in the domain section using the "dns:" urls I presume.

```
  "letsencrypt": {
    "email": "X@X.X",
    "names": "*.X.X",
    "skipChallengeVerification": true,
    "production": true
  }

**Comment by nzalev** [comment]
The only parsing done with the names is to split on commas, so a `*` would be sent to LE as a string. It would not have any special meaning to meshcentral.

The `*` is used for wildcard domains. The LE module performs an HTTP-01 challenge, but Lets Encrypt only supports wildcard domains using DNS-01 challenges.

**Comment by Ylianst** [comment]
@nzalev Is completely correct, * domains are not supported with the MeshCentral built-in Let's Encrypt support.

One option is to put MeshCentral behind a reverse proxy and have the reverse proxy perform TLS offload and get the Let's Encrypt certificate, you can do anything supported by the reverse proxy including * certs.

**Comment by Secure-Concept** [comment]
Thanks !
