### ISSUE TITLE
Websocket error when behind Cloudflare proxy

### ISSUE THREAD

**Issue by santo74** [Ylianst/MeshCentral#3327]
I set up MeshCentral on an Ubuntu 20.04 LTS server and everything is working fine, including let's encrypt.

However, when I enable the proxy (orange cloud) in Cloudflare for the subdomain where MeshCentral is running, then I get the following error message after login:

![image](https://user-images.githubusercontent.com/7080464/144807683-02ec20db-6340-4acb-aae3-3a9fbc3d7378.png)

When I disable the proxy again, everything is back to normal.
I experimented with the SSL settings in Cloudflare ("full" vs "strict"), but that doesn't make any difference.

FYI: I have several other websocket-enabled applications running behind Cloudflare (other domains) without any issues.

Btw, I would like to take this opportunity to thank you so much for this wonderful software!

**Comment by Ylianst** [comment]
I don't have a lot of experience with CloudFlare, but I did try it and it worked for me. Can you open the browser console and see if there are any errors showing? Here is my console for FireFox.

![image](https://user-images.githubusercontent.com/1319013/144811523-ed0bb238-5159-4da9-8b3e-d6da617be9c2.png)

Also (if possible) can you go in "My Server" / "Trace" tab, enable "Web Server Requests" tracing and in a different browser, try to access thru Cloudflare.

![image](https://user-images.githubusercontent.com/1319013/144811972-28dd7044-ccb8-41b0-9dd0-99cf147efef1.png)

In both cases, look for access to "control.ashx". See if it's being requested.

Thanks,
Ylian

**Comment by santo74** [comment]
In the browser console I don't see anything special. There are no errors and the request to control.ashx is performed correctly as far as I can see.

![image](https://user-images.githubusercontent.com/7080464/144821752-c0196336-bfc5-4c89-b2b5-39e8c3670077.png)

I managed to set up port forwarding in order to access the server tracing while triggering a normal login via Cloudflare and this is the result:

![image](https://user-images.githubusercontent.com/7080464/144821976-656afedf-aa9d-42b6-b375-b18da13a0592.png)

Guy

**Comment by drnikcuk** [comment]
I am having the same problem, but without cloudflare in the mix !

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
