### ISSUE TITLE
MeshCMD Linux 

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#333]
Invalid url for download meshcmd linux

**Comment by Ylianst** [comment]
More details needed. Can you send the URL or screen shot of the web page that you are using to download MeshCMD? [Download here works](https://www.meshcommander.com/meshcommander/meshcmd).

**Comment by Ilia1** [comment]
I meant loading from Meshcentral
![Снимок экрана от 2019-07-03 09-11-14](https://user-images.githubusercontent.com/16576224/60562934-060fa800-9d73-11e9-924d-91aad2297a7f.png)
when choosing Linux is still downloaded exe file

**Comment by Ylianst** [comment]
Your right, it always downloads the same MeshCMD for Windows, the drop down box does not work. I am going to fix this now for the next release.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.7-d with a fix for this. Please check and close this issue if it's ok.

**Comment by Ilia1** [comment]
Now the link is correct. Thank!

**Comment by pavanagrawal123** [comment]
Not sure if this is published on meshcentral.com but the issue seems to be that the download switches after changing the selection in the dropdown box. I.e. if you chose the platform twice, it works fine.
