### ISSUE TITLE
Compiled Build not find setting files Name Issues or something

### ISSUE THREAD

**Issue by Andy-Edge-Max** [Ylianst/MeshCentral#3330]
Hello I try get meshagent run on ubunt full not core it runs must it does not seem detect .msh file is any spefic format name or anything it needs?

**Comment by Ylianst** [comment]
Hi. The `meshagent.msh` file is just a text file, you can copy it from another computer that is in the same device group. If you need a trick to get the .msh file, you can add `?debug=1` to the URL and click "Add Agent", there will be an extra link to download it.

![image](https://user-images.githubusercontent.com/1319013/144997206-26521fbf-f678-4c25-b41d-2b271c79c385.png)

**Comment by Andy-Edge-Max** [comment]
I have try make the file the compile build from source does not seem to find

**Comment by Andy-Edge-Max** [comment]
Thank you did not know could add client that way works great!!!

**Comment by Ylianst** [comment]
The MeshAgent source code is here: [https://github.com/Ylianst/MeshAgent](https://github.com/Ylianst/MeshAgent)

**Comment by Andy-Edge-Max** [comment]
Thanks I try used compile version it never seem to find setting file for some reason but grab it  precompile from mesh server work great
