### ISSUE TITLE
Avoid disable two-factor authentication

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3331]
In order to secure access to the MeshCentral application, is it possible to force the users of a group to use two-factor authentication?
Avoid disable two-factor authentication.
Prevent some users from disabling two-factor authentication.

**Comment by pascal-chag** [comment]
I found with the parameter passwordRequirements / force2factor.
But how do you force the use of a physical key all the time?
How to turn off two-factor authentication with Google Authenticator?

**Comment by Ylianst** [comment]
In the `PasswordRequirements` section, you can force two-factor and disable some forms of two factor authentication, with `email2factor`, `sms2factor`, `push2factor`. I don't have an option to remove the Google OTP, but could add that. Would that work? Backup codes would still be enabled, you always need a second 2FA configured.

```
      "PasswordRequirements": {
        "_min": 8,
        "max": 64,
        "_upper": 1,
        "_lower": 1,
        "_numeric": 1,
        "_nonalpha": 1,
        "_reset": 10,
        "_hint": true,
        "_force2factor": true,
        "_email2factor": true,
        "_sms2factor": true,
        "_push2factor": false,
        "_oldPasswordBan": 5,
        "_banCommonPasswords": true,
        "_skip2factor": "127.0.0.1,192.168.2.0/24",
        "_loginTokens": true,
        "_twoFactorTimeout": 2,
        "_autofido2fa": false
      }
```

**Comment by pascal-chag** [comment]
yes it would work
Thanks

**Comment by Ylianst** [comment]
Just published MeshCentral v0.9.59 with an new option to disable OTP 2FA. Not sure why you want to do that, but it's available now.

```
      "PasswordRequirements": {
        "_min": 8,
        "max": 64,
        "_upper": 1,
        "_lower": 1,
        "_numeric": 1,
        "_nonalpha": 1,
        "_reset": 10,
        "_hint": true,
        "_force2factor": true,
        "_email2factor": true,
        "_sms2factor": true,
        "_push2factor": false,
        "otp2factor": false,                                 <-----
        "_oldPasswordBan": 5,
        "_banCommonPasswords": true,
        "_skip2factor": "127.0.0.1,192.168.2.0/24",
        "_loginTokens": true,
        "_twoFactorTimeout": 2,
        "_autofido2fa": false
      }
```

**Comment by pascal-chag** [comment]
I think I misspoke.
What I wanted was to force certain users (those belonging to a group) to use two-factor authentication with only the physical security key.
So I would like to have an option to disable two-factor authentication by Google Authenticator.

To increase the level of security, we would like to have options at the level of each group allowing to activate / deactivate certain two-factor authentication.
In our specific case, we want users in the 'DPISupport' group to be forced to use only a physical security key, and that the backup codes be managed by the MeshCentral administrator.
If a user of the 'DPISupport' group has forgotten or lost his physical key, he asks the MeshCentral administrator for a temporary code to be able to use MeshCentral for the day, for example.

Thank you

**Comment by Ylianst** [comment]
Arg. This is not a good request. The main problem is that should not have a different account security policy for some accounts. Like, 2FA for some and not for others. This is bad security. Attackers will go after all accounts.

Also, having administrator have access to 2FA backup codes is a bad idea from a security perspective. An administrator can reset an account 2FA, but should not be able to get the account's 2FA codes. You are also changing you request significantly from the original request above.

Maybe you should use a SAML or OAuth security portal and put that in front of MeshCental? Or require everyone use hardware keys?
