### ISSUE TITLE
no tabs webrdp

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3334]
![изображение](https://user-images.githubusercontent.com/95762246/145231312-32cf606e-279b-4e99-bf56-cbb47a40d57e.png)

latest version 0.9.58

**Comment by nzalev** [comment]
You must set `"mstsc": true` in your domain section of config.json.

```json
  "domains": {
    "": {
      "mstsc": true,
      "title": "MyServer",
      ...
    }
  },

**Comment by gosteras** [comment]
all ok. Thanks

**Comment by gosteras** [comment]
all ok. Thanks
