### ISSUE TITLE
On my Customer Domain I am Administrator, can i see my devices and groups added to domain by other user?

### ISSUE THREAD

**Issue by nagainfotech** [Ylianst/MeshCentral#3335]
Hi
I have customer domain and have created a manager account to my customer and admin account to myself.
Manager has created few groups and started adding devices. But when i login to the domain i cant see them.

Manager account login:
![image](https://user-images.githubusercontent.com/70787590/145314421-b189a73b-5a46-47b0-9b69-20356d84429f.png)

My Admin login to same domain:

![image](https://user-images.githubusercontent.com/70787590/145314470-350b13e1-ca4b-4e24-b0e3-2d376ef15a5e.png)

Am i missing something or is groups and devices are only individual based if so is there a way we can share the groups and devices in it for all users of the domain?

**Comment by Ylianst** [comment]
Normally, when you create a device group, the creator is the only user that can see the device group and devices within it. The creator needs to click on a device group and add users with access rights. Only then will other users see the device group.

This said, there is a trick. If you are administrator and want to see all device groups for all users in a domain, you can add the following line to the domain section of the config.json:

```
"manageAllDeviceGroups": [ "user\domain\admin" ]
```

Put the account identifier and restart the server. That account needs to have full admin rights on the server and with this line, will see all device groups.

Let me know if that helps.

**Comment by nagainfotech** [comment]
Hi Ylian,

is this the way to put it in json file

[image: image.png]

Kind Regards,
Santosh T
NagaInfoTech <http://www.nagainfotech.com>

**Comment by nagainfotech** [comment]
![image](https://user-images.githubusercontent.com/70787590/145330199-bde9b26e-dc8a-4614-9d40-144d6d1673fd.png)

**Comment by nagainfotech** [comment]
do i need to leave [ "user\domain\admin" ] as it is or update as per above screenshot, which is not working?

**Comment by Ylianst** [comment]
Apologies, change it to:

```
"manageAllDeviceGroups": [ "user\\admin" ]
```
You have to type "user\" + the domain identifier + "\" + account identifier.

Since you are in the default domain, the userid will be "user\\admin"

**Comment by nzalev** [comment]
@Ylianst 

I believe if it is in the domain section, it should be only the username.

If in the domains section, it will append the username to `user/domain/`
```javascript
      for (i in obj.config.domains) {
          if (Array.isArray(obj.config.domains[i].managealldevicegroups)) {
              for (var j in obj.config.domains[i].managealldevicegroups) {
                  if (typeof obj.config.domains[i].managealldevicegroups[j] == 'string') {
                      const u = 'user/' + i + '/' + obj.config.domains[i].managealldevicegroups[j];
                      if (obj.config.settings.managealldevicegroups.indexOf(u) == -1) { 
                          obj.config.settings.managealldevicegroups.push(u); }
                  }
              }
          }
      }
```

If you use the key `user//name`, you will end up with `[ 'user/domain/user//name' ]`

**Comment by nagainfotech** [comment]
hi nzalev
what should i use and should it be under domains or under Customer1 section?

**Comment by nagainfotech** [comment]
i put it under both but still cant see devices of other user under me as admin

**Comment by nzalev** [comment]
I see from your screenshot, the domain you're talking about is `TBBP`. If this is the domain you want give your user all device groups, then you should not include the config option in the default domain (`""`).

Here is an example setup. Give the user administrator permissions. Notice the user had 0 device groups.
![Screenshot from 2021-12-08 23-37-51](https://user-images.githubusercontent.com/63608819/145335492-62cf47f0-1fbc-44cd-9484-8684c958fc06.png)

Under that specific domain (TBBP in your example), "testdomain" in my example, add the `manageAllDeviceGroups` setting with just the username. See below.


```json
  "domains": {
    "": {
      "mstsc": true,
      "trustedcert": true
    },
    "testdomain": {
      "dns": "testdomain.localhost",
      "manageAllDeviceGroups": [ "noah" ]
    }
  },
```

Now when logged in with that user, it will have access to all device groups.
![Screenshot from 2021-12-08 23-41-25](https://user-images.githubusercontent.com/63608819/145335804-06c47c09-9ba3-476b-ba2f-f3699600b466.png)

**Comment by nagainfotech** [comment]
awesome thanks a lot for your help nzalev.

**Comment by nagainfotech** [comment]
one more question once i have all devices in system is there a way i can export report on device info like hardware info and what software each device has etc?

**Comment by nzalev** [comment]
This is already covered in https://github.com/Ylianst/MeshCentral/issues/2054 and https://github.com/Ylianst/MeshCentral/issues/2472

Select all -> group action -> export device information
![Screenshot from 2021-12-08 23-53-38](https://user-images.githubusercontent.com/63608819/145336844-4c1b4f2f-48c2-453a-b135-52e507683968.png)

Check include device details, then click the link to the format you want.
![Screenshot from 2021-12-08 23-53-49](https://user-images.githubusercontent.com/63608819/145336936-c76a3d63-1b89-42d2-ac80-731af0b33303.png)

**Comment by nagainfotech** [comment]
thank you verymuch

**Comment by Ylianst** [comment]
@nzalev OMG, nicely done! I did not do well answering this one.
