### ISSUE TITLE
Feature Request: enable copy/paste on console recordings

### ISSUE THREAD

**Issue by pentafive** [Ylianst/MeshCentral#3336]
I'm a die hard copy/paste user. The fact that MeshCentral supports copy/paste across the terminal is really great!

Is there a way to do this on the recording and playback? 

Here's my inspiration: https://github.com/asciinema/asciinema

Thanks!
-JD

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Ok, new version of the player will use XTerm to play back the terminal session. It will also size the terminal correct now.

![image](https://user-images.githubusercontent.com/1319013/145904224-840f1ca8-b4e8-4b45-b582-6b658f3d1e1b.png)

This will be in MeshCentral v0.9.60

**Comment by pentafive** [comment]
Confirmed working in MeshCentral 0.9.61. Thanks for the quick turn around!
