### ISSUE TITLE
Issue: meshcentral webserver crashes on recording playback via stream

### ISSUE THREAD

**Issue by pentafive** [Ylianst/MeshCentral#3337]
Verison: MeshCentral v0.9.58, WAN mode.
OS: Linux ip-xxx-xxx-xxx-xxx.ec2.internal 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
AMI: amzn2-ami-hvm-2.0.20211001.1-x86_64-gp2
Instance size: t3.medium

When I goto the recordings tab, click play recording and then the server crashes. The MeshCentral Session Playing loads but wants to 
be provided a playback file. When I return to MeshCentral it wants me to login. So I checked the server and found the following in mesherrors.txt

```
-------- 12/9/2021, 6:46:52 AM ---- 0.9.58 --------

internal/fs/utils.js:355
  throw new ERR_INVALID_OPT_VALUE('flags', flags);
  ^

TypeError [ERR_INVALID_OPT_VALUE]: The value "function (err, fd) {
                    if (err == null) {
                        // When data is received from the web socket
                        ws.on('message', function (msg) {
                            if (typeof msg != 'string') return;
                            var command;
                            try { command = JSON.parse(msg); } catch (e) { return; }
                            if ((command == null) || (typeof command.action != 'string')) return;
                            switch (command.action) {
                                case 'get': {
                                    const buffer = Buffer.alloc(8 + command.size);
                                    //buffer.writeUInt32BE((command.ptr >> 32), 0);
                                    buffer.writeUInt32BE((command.ptr & 0xFFFFFFFF), 4);
                                    obj.fs.read(fd, buffer, 8, command.size, command.ptr, function (err, bytesRead, buffer) { if (bytesRead > (buffer.length - 8)) { buffer = buffer.slice(0, bytesRead + 8); } ws.send(buffer); });
                                    break;
                                }
                            }
                        });

                        // If error, do nothing
                        ws.on('error', function (err) { try { ws.close(); } catch (ex) { } obj.fs.close(fd, function (err) { }); });

                        // If the web socket is closed
                        ws.on('close', function (req) { try { ws.close(); } catch (ex) { } obj.fs.close(fd, function (err) { }); });

                        ws.send(JSON.stringify({ "action": "info", "name": req.query.file, "size": stats.size }));
                    } else {
                        try { ws.close(); } catch (ex) { }
                    }
                }" is invalid for option "flags"
    at stringToFlags (internal/fs/utils.js:355:9)
    at Object.open (fs.js:410:23)
    at /home/ec2-user/node_modules/meshcentral/webserver.js:3513:24
    at FSReqWrap.oncomplete (fs.js:155:5)
```

Additional info:

- Here is a sample of the URL it provides (edited for privacy): 
    https://mechcentral.super.high.tech.url/player.htm?stream=relaysession-2021-12-09-06-45-06-username-hostname-l4hqd7idfia.mcrec
- I did check that the file is present.
- I was able to download the file using the MeshCentral GUI and then play it back using the downloaded file in the player.
- The recordings are from terminal sessions.

Please let me know if there's any further info needed.

Thanks!
-JD

**Comment by Ylianst** [comment]
Thanks for reporting this! I should be able to fix this, but just in case, what version of NodeJS you are using?

**Comment by Ylianst** [comment]
For my own reference, I am [not opening the file correctly at this line](https://github.com/Ylianst/MeshCentral/blob/db3659d665eac2898341dcdadc067f7038e73f9b/webserver.js#L3514).

**Comment by Ylianst** [comment]
Just fixed it, NodeJS 10.x would have this problem, but NodeJS 16.x would not. The fix makes it work on both. This will be in MeshCentral v0.9.60 when it's next published.

**Comment by pentafive** [comment]
Confirmed fixed using Node.js v17.3.0 and MeshCentral v0.9.61. I was on Node.js v10.15.1 but upgraded it with MeshCentral at the same time.
