### ISSUE TITLE
token not valid

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#3338]
Hi , this morning , i'm no able anymore to login into meshcentral server , after inserting login and password as usual i need to enter the 2FA token but everytime i get token not valid.
please let me know , is urgent

**Comment by VINISHVV** [comment]
Not sure, I think this is related to server time mismatch,

**Comment by nzalev** [comment]
I'm not able to reproduce it - authenticator is working fine for me on the latest version.

However, you say it is urgent, so I think the best option is to simply reset the account rather than figuring out why it's happening.

You should navigate to where meshcentral is installed on its server and run
```
node node_modules/meshcentral --listuserids
```
Copy the id of the user exactly. User IDs are of the form `user//username` or `user/domain/username`.   Then run the following command to reset the account and remove 2FA:
```
node node_modules/meshcentral/ --resetaccount "user/mydomain/noah"  --pass "abc123"
```

If you are not using any domains (you are on the default domain), then it will look like
```
node node_modules/meshcentral/ --resetaccount "user//noah"  --pass "abc123"
```

**Comment by Ylianst** [comment]
Are you talking about your own server? Or meshcentral.com? Also is the token for Google Authenticator One-Time-Password?

For the token to work, your phone (or device) and the server must have matching time in UTC format. So, if you server is not in the right time-zone or clock not set correctly, the token will not work. This is a common problem.

Normally, you should always have a backup 2FA, like a USB key or one of 10 backup codes. If you don't have that and can't login, create a new account and you will need to SSH into your server and promote the new account to full server administrator. You can do this by stopping the server and type:

```
node meshcentral --help
MeshCentral v0.9.58, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcommander.com/meshcentral2

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --nedbtodb                        Transfer all NeDB records into current database.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.
```

You can use the `--resetaccount [userid]` to clear your 2FA to `--adminaccount [userid]` to promote an account to administrator. This is how you recover from lost administrator account. Let me know if that helps.

**Comment by tradexsrl** [comment]
hi , i'm talking about my own server , the authenticator is Authy for IOS
i have checked and i don't know why but our 2 pdc windows 2012 AD are 1,5 minutes in advance but all resources on the network have the same time...so i suspect the authy app generate a token that for my server is already expired or is in the future...anyway with the 2FA backup code i was able to login and then i disable the 2FA for the admin until i'll found why the network clock is not the same as my iphone for example

**Comment by Ylianst** [comment]
Makes sense, OTP requires server and service to be synced at about the same UTC time.

**Comment by tradexsrl** [comment]
ok i solved the time on the server , and i reenabled the 2FA but at logon it never ask it....
as you can see the 2FA is enabled:
![immagine](https://user-images.githubusercontent.com/62424179/146772690-0da8a7aa-1c10-4fbf-a108-09854d06c819.png)

**Comment by nzalev** [comment]
Have you tried in an incognito browser window? If that works, then it is likely the browser's cookie.

**Comment by tradexsrl** [comment]
thank's , cleared the cookies and now it ask me for token...anyway i think is a little bug because some days ago i entered the token and setup do not ask me for 30 days , then i got time problem and i managed to disable the 2FA , then i solved the problem and reenabled the 2FA...in my opinion is not correct that it continue to read the cookies setup in the previous token because in this case i will leave open a door for a possible attack if my pc get compromise
