### ISSUE TITLE
MeshAgent periodically disconnecting on Windows 10

### ISSUE THREAD

**Issue by akirillenko** [Ylianst/MeshCentral#3339]
Hello.
Thank you for a great application!
I have an issue with Windows 10 agents.
MeshAgent 0.2.1.3 x86, MeshCentral 0.9.55 (issue is not linked with this particular version and was noticed a few months ago)
Remote desktop sessions randomly disconnecting without any errors, and it seems that disconnects occur almost simultaneously across all active remote connections, even from different users to different computers.
MeshAgent is running as windows background service (installation is performed with -fullinstall flag)

What we have tried:
* Changing meshcentral server config to webRTC=true, no effect.
* Inspecting meshctrl.js showevents output when disconnect event occurs: two "nodeconnect" events with { ... "conn": 0, "pwr": 0 ... } and { ... "conn": 1, "pwr": 1 ... } after or before relay event "closed desktop session".
* Launching meshagent in console mode: when disconnect occurs, agent closes without errors, but such event adds an entry into windows event log:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-12-01T14:18:39.6453142Z" /> 
  <EventRecordID>4665</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>n1348</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>MeshAgent.exe</Data> 
  <Data>0.2.1.3</Data> 
  <Data>612d4568</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>015efcf0</Data> 
  <Data>2b64</Data> 
  <Data>01d7e6b5fc40840d</Data> 
  <Data>C:\Program Files (x86)\Mesh Agent\MeshAgent.exe</Data> 
  <Data>unknown</Data> 
  <Data>839a7c2b-353b-433c-96e9-5fcd8c6515e4</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
  
It seems that crash happens every 30 minutes, but sometimes a few crashes occur with 1-2 minutes interval.
  
![изображение](https://user-images.githubusercontent.com/95846157/145365990-39b1734e-4c20-4c42-bb84-3fa45a975ffa.png)

Thank you for your help.

**Comment by VINISHVV** [comment]
@akirillenko - Can you try deactivating Antivirus for a few hours and confirm whether this issue persists / not.

**Comment by Ylianst** [comment]
The 64bit MeshAgent does seem to be better with anti-virus than the 32bit version.

**Comment by akirillenko** [comment]
Thank you for the response!

Digged a little bit into interactions with antivirus and meshagent.
AV software: Dr.Web

All our computers belong to the same domain. Some of the settings propagate via GPO. 
We had tried to add meshagent.exe to the av exception list, but apparently this was not enough.

Sometimes disconnect happened when a new executable was launched on a computer via remote connection.
Guaranteed disconnect after the next sequence: boot PC, connect via meshcentral, log in with user credentials.
With 32-bit meshagent changing ANY antivirus settings caused agent application to crash and restart with the same "Application Error 1000" entry in the Windows Event Log. 

It seems that crash occurs on any Dr.Web action in the system.

Replacing 32-bit agent with 64-bit worked: now i can change AV settings without disconnection.
I have tested login/logout sequence - issue is gone for now.

Now i need to make a proper test on our company computers with Windows Event log inspection.
I can report the results on Monday.

Thank you.

**Comment by akirillenko** [comment]
Update:
I have tested 64-bit meshagent on ~300 computers in company network.
All the connections are stable now!

BTW, while installing 64-bit agent on PC with Windows 7 64-bit, fatal exception is popping up, but it seems that this error does nothing - agent is working properly without any issues.

![win7-err64](https://user-images.githubusercontent.com/95846157/145768259-ce1c2061-8a7c-4e1e-93cd-fd24d737cbe6.jpg)

Thank you for your help.
