### ISSUE TITLE
antivirus blocking the screen 

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3343]
Hello !! antivirus kasperksky block desktop.

what to do 

![изображение](https://user-images.githubusercontent.com/95762246/145558714-f1733b64-69c0-4791-a86b-ad96db169328.png)

Thanks

**Comment by vitko-bg** [comment]
Add meshagent to AV exceptions

**Comment by gosteras** [comment]
does not help, self-defense works

**Comment by gosteras** [comment]
Disable it only and then it works, but it's not safe

**Comment by vitko-bg** [comment]
I had same issue with Avast, check other issues you may find some info. BTW, I not tested it again with Avast, just got rid of the Avast :)

**Comment by Ylianst** [comment]
Sadly, there is nothing much we can do about this. If you are using the 32bit version of the MeshAgent, try the 64bit version. Otherwise, you need to add an exception or ask Avast to handle the agent differently.
