### ISSUE TITLE
Enhancements to MeshCentral Assistant guest sharing

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3347]
Hello,

I find the MeshAssistant software great for internal use.
Would it be possible to add an assistant for external uses, to offer the possibility to external people to temporarily access a computer?

We use many software / applications in our healthcare facility.
Not all of these applications are managed by IT.
The support of these applications is done by external companies.
Our facility's IT department has no expertise in this software.

Often, external support needs to have access to the screen of the computer on which the application is installed to assist the person using the software or to change a setting.
We do not want software like TeamViewer to be used.
We also want this assistant to be able to be used by only a few trusted people.
We already have a solution with VNC and Apache Guacamole but we want to remove VNC from our computers.

Here is my use case:
A biologist makes a phone call to technical support for his problematic application. This support is provided by a company external to our establishment.
The biologist wants the tech support person to be able to see and act on the computer screen.
This biologist can launch the "External Assistant" from any computer.
This biologist is part of a MeshCentral user group authorized to provide "external assistance".
When the External Assistant is launched, a username and password are requested.
The biologist enters its Active Directory identifier (we connected MeshCentral on the ldap of our Active Directory), if the identifiers are correct, biology can enter the email address of the person who will provide assistance from outside of our establishment.
The biologist enters the maximum period of validity of the link.
Several validity periods are offered, these periods are configured at the level of the computer group to which the "External Assistant" belongs or at the level of the group to which the MeshCentral user (the biologist) belongs.
The biologist validates, an email is sent with the link to connect to the computer.
The person who will provide the assistance clicks on the link in the email.
A page with a temporary code to enter is displayed.
At the same time, an automatically generated temporary code is displayed on the external assistant.
The biologist gives this temporary code by telephone to the person who will perform the support.
The code is entered, the external support person can see the computer screen and act on this computer if authorized.
Confirmation access can be requested from the biologist.
The biologist can end the assistance at any time.

The external assistant would allow certain people in our establishment to provide external, temporary, secure access on their own, without requiring the IT department.
An Assistant like this would be really really great.

**Comment by Ylianst** [comment]
Take a look at #3230 and see if that would work for you. When enabled, MeshCentral Assistant can create a guest sharing link on it's own that can be sent to someone that need to provide support.

![image](https://user-images.githubusercontent.com/1319013/145728959-dae868b1-09ea-4121-b83c-ef0ad9bfe265.png)

It's not exactly your usage but let me know.

I also want to mention that MeshCentral Assistant should work both internally and externally depending on how your server is setup. Then someone needs help, they should be able to launch assistant, type a quick note and have Assistant connect to the server. The external support person should see the computer popup on a "external support" device group, when trying to connect, using consent will show. User can accept and get support.

**Comment by pascal-chag** [comment]
great, the assistant in self guest sharing mode works well.
I would like to add some additional security so that this option can only be used by a few trusted people. 
And also be able to regulate the duration of the sharing by the administrator.

**Comment by Ylianst** [comment]
I can add an option to limit the duration... but I am not sure how to allow only for a few trusted people since this option can be used without any login. If you have ideas on that, let me know.

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.9.60, you can specify in the domain section of the config.json:

```
      "AgentSelfGuestSharing": {
        "expire": 5
      }
```

The `expire` value is the number of minutes you want the MeshCentral Assistant self-sharing to expire.

**Comment by pascal-chag** [comment]
Thanks,

Perhaps with an option by group of devices asking that the shares done by yourself from the Assistant of this group requires that the users be authenticated (authenticated in MeshCentral). Users should also have access to this group.

![2021-12-14 12_46_58-MeshCentral GH-MSM](https://user-images.githubusercontent.com/95504809/145994522-e997bfb7-c2ca-4af8-bed0-2844bd79bac8.png)

On the Assistant side : 

![2021-12-14 13_02_20-Window](https://user-images.githubusercontent.com/95504809/145995103-35b2f231-5787-472d-bca5-77282949a037.png)

A login and password is required
![2021-12-14 13_05_57-Routeur MeshCentral](https://user-images.githubusercontent.com/95504809/145995221-5b6e17e5-5ff5-452b-b082-5fdbff44c754.png)
juste before the guest sharing settings screen

![2021-12-14 13_07_51-Guest Sharing](https://user-images.githubusercontent.com/95504809/145995584-02745808-c25e-4bba-a225-29c8c6de49a5.png)

**Comment by gianlucaromito** [comment]
Hi to all, does some one use this function and tell me if it is working? I've the latest release 1.0.1 installed but for me it does not work.

**Comment by gianlucaromito** [comment]
I am one step forward. We use for authentication SAML. and in the config I've this line too:
"unknownUserRootRedirect":"https://mesh.xxx.iyy/auth-saml",
Having this line it prevents the option from showing up.
Now if I try it stays forewer on "setup"
![image](https://user-images.githubusercontent.com/27236107/161507423-83061517-b2af-49cd-90f8-8f1bf257009a.png)

**Comment by si458** [comment]
closing as this was implemented
