### ISSUE TITLE
Execute cmd command as logged in user

### ISSUE THREAD

**Issue by gtmsew** [Ylianst/MeshCentral#3349]
Not an issue just a question, is there an issue to execute the cmd command on Windows machines using the logged-in user rights, not the system?

**Comment by krayon007** [comment]
Are you talking about in terms of the terminal tab? If so, you can right click on the connect button, and click user. That will launch the command prompt as the logged in user.

**Comment by krayon007** [comment]
But in general, it is not an issue. There are two ways we currently do it. One is to use an impersonation token, the other is to use the task scheduler. The former results in a process owned by local system running with user permissions. The latter results is a process that is actually owned by the logged in user.

**Comment by Ylianst** [comment]
Note that you can select one or more devices, press "Group Actions...", select "Run Commands". You can then type a command like "Notepad.exe" and opt to run it as current user. It will pop-up on the user's desktop.

![image](https://user-images.githubusercontent.com/1319013/145729239-b65d4e41-8a27-4c37-b6f7-d1d337ec1730.png)
