### ISSUE TITLE
Server Warnings: mongodump

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#3351]
on v 0.9.59.

Under My Server, I see this "Server Warnings. 
WARNING: Unable to find mongodump, MongoDB database auto-backup will not be performed."

What can I do to fix this?

**Comment by nzalev** [comment]
This indicates meshcentral cannot find the mongodump executable.

You will need to add the autobackup section to your config.json to tell meshcentral the file path to mongodump.exe.

```json
  "settings": {
    "tlsOffload": "127.0.0.1",
    "mongoDb": "mongodb://127.0.0.1:27017/",
    "AutoBackup": {
      "mongodumppath": "C:\\Program Files\\MongoDB\\Server\\4.4\\bin\\mongodump.exe"
    },
    ...
```

Assuming that you are using Windows, ensure that you have mongodump.exe installed. Find it's full path _on your machine_, and specify the path in `mongodumppath`. You _must_ use double backslashes in the config file.


There are also a variety of other issues with this exact warning: https://github.com/Ylianst/MeshCentral/issues/2791, https://github.com/Ylianst/MeshCentral/issues/2491, https://github.com/Ylianst/MeshCentral/issues/2242, https://github.com/Ylianst/MeshCentral/issues/2945

**Comment by FATeknollogee** [comment]
Thanks for the info @nzalev 
I'm running Fedora, I'll take a look at the links you posted.

**Comment by FATeknollogee** [comment]
It seems like I don't have mongodump installed:

```
# which mongodump
/usr/bin/which: no mongodump in `(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by nzalev** [comment]
If you are running linux, generally, the next advice I give so to run `which mongodump` to check if it is installed, so I am glad you beat me to it.

I believe there is an RPM available. On linux, you don't need to include include the `autobackup` section of the config or `mongodumppath`, as long as the binary is within the `$PATH` variable for the user running meshcentral.

**Comment by FATeknollogee** [comment]
> If you are running linux, generally, the next advice I give so to run `which mongodump` to check if it is installed, so I am glad you beat me to it.
> 
> I believe there is an RPM available. On linux, you don't need to include include the `autobackup` section of the config or `mongodumppath`, as long as the binary is within the `$PATH` variable for the user running meshcentral.

Thank you.
