### ISSUE TITLE
IP Address column shows last IP instead of current.

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3354]
Hi. Just recently realized that IP Address column in list view does not show correct information. One of the employees got his reinstalled in the office laptop and took it to the other one, as soon as connected to internet - it showed the local IP which was in the main office. However, not sure if that make sense here are steps to recreate:
1. Install and run agent on some laptop on some network (let say network "one" with range 192.168.5.X).
2. Address column on MC server will show let say 192.168.5.81 (MC Server is in hybrid mode)
3. power off the laptop and take it to other place, or mobile hotspot
4. As soon as it come online - Address field in list view on MC still show 192.168.5.81
5. When click on device itself and go to Details tab, IP is different :)
6. Disconnect laptop from hotspot and connect to 3rd different network
7. Address on MC server in list view will be the address from the 2nd connected network.
8. And so on :)

Outcome - looks like Address field in list view on MC shows the last connected address instead of current IP address.
In my case for WAN agents - current IP: 86.X.X.X, Address on MC is: 33.X.X.X, disconnected from 86.X.X.X and connected to 74.x.x.x on MC shows 86.x.x.x

MC server: 0.9.55 (LAN+WAN)
OS: Ubuntu Jessie
Agent OS: Windows 10 x64

**Comment by leuvi** [comment]
I have the same question

**Comment by nzalev** [comment]
I can look into this, but I won't be able to start until next week.

**Comment by vitko-bg** [comment]
That would be great. Thanks.

**Comment by vitko-bg** [comment]
@nzalev - sorry for bothering you, is there any update on this, as we are using this constantly and now we have to make sure from the details tab to see current IP address of the laptops.

**Comment by nzalev** [comment]
You need not worry about bothering me. I had taken a break over the holidays. I will look at this tomorrow.

**Comment by nzalev** [comment]
Short update:

I am trying to do this locally on my LAN.

```
root@bakery:~# ip -4 a show enp3s0
2: enp3s0: ...
    inet 192.168.1.110/24
```
![Screenshot from 2022-01-05 18-08-39](https://user-images.githubusercontent.com/63608819/148302789-fec22c11-01df-4677-8048-0bcebddd533b.png)

I then changed the IP of the host and reconnected the agent:
```
root@bakery:~# ip addr add 192.168.1.111/24 dev enp3s0
root@bakery:~# ip addr del 192.168.1.110/24 dev enp3s0
```
![Screenshot from 2022-01-05 18-10-15](https://user-images.githubusercontent.com/63608819/148302854-dd25e601-8859-4fb1-af22-e27b9c3eb741.png)

So it appears to be working as intended on the LAN. 

The only way I can test on the WAN right now is by switching between mobile hotspot and wifi, so it will take me longer to test. I am going to take a look at the code first, but there is a lot that goes on between a web request from the agent and displaying the info in the browser.

**Comment by nzalev** [comment]
I found that if you let the agent stop and start again between switching networks, it won't have any issues.

I was able to replicate it by connecting to my test server over a mobile hotspot, disconnecting the network without stopping the agent, waiting a bit, and reconnecting over the wifi. Now, details tab and column view IP addresses disagree.

**Comment by vitko-bg** [comment]
Thanks @nzalev - once new version is out will make proper test also to make sure it is working as expected.
BTW, I had issues with the IP also lets say when laptop is connected to some network and when closing the lid widnows goes to sleep mode. Once lid is opened - obviously laptop physically is on different place and different network - the IP stays from previous network/location.
Hope your fix will work. Thanks again.

**Comment by nzalev** [comment]
@vitko-bg The latest meshcentral update contains the fix. It should work in both cases, but please let me know.

**Comment by vitko-bg** [comment]
Updated to the latest today, was no chance to test it so it will be later on. Will update accordingly

**Comment by vitko-bg** [comment]
@nzalev the issue is closed by @Ylianst but to be honest looks like it is fixed, but on a half only.
Details view column Address working as expected - all is amazing, connect, disconnect, change networks, etc - all is fine.
In Device -> Details -> Last agent address - value never changes, even if device going offline - does not reflect on Last IP address field.
I may be wrong - but in my opinion in Device -> Details -> Last agent address and Details view -> Address column have be same, i.e. show current Public IP address of agent when device is online and show the same last address when device is disconnected or offline. When connected to new network with new Public IP both values to change at the same time.
What do you think?

**Comment by vitko-bg** [comment]
P.S - After MC restart IP in Device -> Details -> Last agent address changed to the last address I was using laptop.
Will spend more time and will update again.

**Comment by nzalev** [comment]
> nzalev the issue is closed by Ylianst but to be honest looks like it is fixed

The issue was closed automatically because it's linked to the pull request

> Details view column Address working as expected - all is amazing, connect, disconnect, change networks, etc - all is fine.

That's good - so the fix worked as expected.

> In Device -> Details -> Last agent address - value never changes, even if device going offline - does not reflect on Last IP address field. I may be wrong - but in my opinion in Device -> Details -> Last agent address and Details view -> Address column have be same

This should be the case. As I mentioned previously though, these values come from separate events - so the fix for column view won't affect the details page.

> P.S - After MC restart IP in Device -> Details -> Last agent address changed to the last address I was using laptop.
Will spend more time and will update again.

Please, let me know - if the behaviour is not right, you should start a new issue with steps on how to reproduce it, and I will look at it.

**Comment by vitko-bg** [comment]
Hi @nzalev,
all work fine with just small issue, which is not a big deal - in Device -> Details -> Last agent address change occurs only on device disconnection, which is still OK, as if agent is offline the IP address in the filed will show the last public IP it was connected from. And on device connection - it will show current Public IP.
Thanks for the fix - it helps a lot in my case.
