### ISSUE TITLE
Server URL local

### ISSUE THREAD

**Issue by stefan6dev** [Ylianst/MeshCentral#3358]
Hi,

we try add a batch of new windows server via the installer.

In the Agent Install Wizard show all time Server URL "local", and the Server come not up.

What configuration option set this URL?

**Comment by Ylianst** [comment]
The server URL is "local" because you server is in LAN mode. You need to specify a server name link this:

```
{
  "settings": {
    "cert": "server.example.com"
  }
}
```

I have a [video on LAN, WAN and Hybrid modes here](https://www.youtube.com/watch?v=gx5Fh3pQOns).
