### ISSUE TITLE
Weblink NAT

### ISSUE THREAD

**Issue by Ajilis** [Ylianst/MeshCentral#3360]
HI all

Thanx Ylianst for all is job and time.

I ask the question, but i think its not physicaly possible ;)

The QUESTION:
Is there a way to generate a weblink through meshcentral ie: https://ip_server/xxxxxxxxx

That can route IP traffic through the agent on an other IP of the local LAN without meshrouter APP ? :)

**Comment by Ylianst** [comment]
I have done this in the past with MeshCentral v1 but it did not work well. If you are accessing a web site using https://ip_server/xxxxxxxxx and the web site expects to be accessed from / many of the links in the site will not load and the site will not work. If you site was made to never access the root level `/abc` then it would work, but that is not often the case.

**Comment by Ajilis** [comment]
OK thanx for your answer Ylianst
and if we specialized a custom PORT to handle this kind of requests ?

the purpose is to try to do something like that:   https://www.gl-inet.com/solutions/astrorelay/

That's already possible with meshrouter app and we use it in a large scale.

**Comment by Ylianst** [comment]
Yes, a custom port on the server would work.

**Comment by Ylianst** [comment]
I just watched the AstroRelay video and indeed, they assign a port to each service. There may be a MeshCentral plug-in that does exactly this, but I don't support plug-ins. This said, I could add this feature in the future.
