### ISSUE TITLE
CTRL+W warning

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#3362]
Hi,

As a keybord shortcut lover, I use CTRL+W to close a browser tab.

However, if I'm remotely working on a PC, and want to close a tab on that remote PC using CTRL+W, then it closes my meshcentral-remote-desktop-tab!

Can it be made that closing a meshcentral tab issues a warning "are you sure to close this tab", so I can cancel my stupid CTRL+W action?

**Comment by drnikcuk** [comment]
+1 ! i have the same issue daily.

**Comment by AntonAndreevichMoroz** [comment]
Yes, I also happen to close a tab by mistake when I try to search for text in nano Linux. But it seems to me that this key combination is intercepted by the system before the MeshCentral code can see it. Therefore, confirmation must be configured at the browser or system level. I don't think this is possible at the code level of the Mesh application.

**Comment by JSuenram** [comment]
You can add this 4 code-lines in default.handlebars until my Pull-Request is accepted or at least "optimized".

`        window.addEventListener('beforeunload', function (e) {
            e.preventDefault();
            e.returnValue = '';
        });`

Just put this at the very end of the file:

`
        // Quick fix for #3362 - Request Confirmation if MeshCentral-Browser-Tab is closed. - Maybe needs an option per User or Config.JSON-Setting
        window.addEventListener('beforeunload', function (e) {
            e.preventDefault();
            e.returnValue = '';
        });
    
    </script>
</body>
</html>`

**Comment by jdvmanen** [comment]
:-) MeshCentral doesn't boot after this edit in config.json...

**Comment by JSuenram** [comment]
Not in config.json. In default.handlebars you need to add this....

**Comment by JSuenram** [comment]
Has been implemented in latest 0.9.83 please confirm and close.
Thank you!

**Comment by si458** [comment]
Fixed
