### ISSUE TITLE
No terminal when local 

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3364]
Hi 
Id add a new group without agent to connect with ssh 
but when i add server 
![image](https://user-images.githubusercontent.com/32361668/146363640-fdb7d6d8-0413-4a10-b898-548078e3d995.png)
As you can see no terminal prompted

**Comment by gaalos** [comment]
well... 
I found it after watching config 
Need to add "ssh": true, in domain config

**Comment by Ylianst** [comment]
SSH support requires MeshCentral install additional modules, so SSH is not enabled by default.
