### ISSUE TITLE
Remotely managing Windows computers

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#3367]
No issue's with MC.

When the pc is asleep, the MC agent is also asleep therefore you can't "manage" the pc.

Do you set the Power option to high performance so the pc can't go to sleep?

What are other people doing?

**Comment by AntonAndreevichMoroz** [comment]
It is possible to use WoL when supporting a network card and motherboard

**Comment by Ylianst** [comment]
MeshCentral supports both WoL and Intel AMT Wake for remotely waking up a PC. For WoL, MeshCentral will command all of the agents in the same device group to send WoL packets on their attached networks. So, if you have a network with 5 agents and 4 are sleeping, the 5th can be used to wake the other 4.

If you have Intel AMT, then that can keep a connection to the server even when the computer is sleeping (some conditions apply) and so, you can wake the PC even from sleep on it's own.

Let me know if that helps.
