### ISSUE TITLE
Question: 3rd party RMM tools

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#3368]
No issues with MC.

@Ylianst Did you publish a link of 3rd party commercial RMM tools that "integrated" MC?
I seem to remember a link or topic but can't find it.

**Comment by AntonAndreevichMoroz** [comment]
Is that what you mean? https://github.com/wh1te909/tacticalrmm

**Comment by FATeknollogee** [comment]
Yes, are there others like Tactical?

**Comment by Ylianst** [comment]
I don't know of any other tools that integrate MeshCentral except TacticalRMM.
