### ISSUE TITLE
meshcmd download messes up in Chrome, ... sometimes

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#337]
I read #333 and thought I'd test it.  It seems to work fine in Firefox, but in Chrome I got ... strange results.

I'm not sure how things were in pre-0.3.7-d versions, but with a fresh install using the default config, accessing it via `localhost`, I _usually_ can't download the meshcmd binary (for any listed platform), or meshaction.txt file using the links in the screen @Ilia1 was having issues with.
![Screenshot from issue #333](https://user-images.githubusercontent.com/16576224/60562934-060fa800-9d73-11e9-924d-91aad2297a7f.png)

It's really weird, but in Chrome, if I've recently added, edited, or deleted a Device Group, or _sometimes_ if I do other things that one wouldn't expect to affect anything, like opening and closing (with the `x` at the top right) the Download MeshCmd screen, or viewing the properties of a Device Group, I'm no longer offered the meshcmd binary or meshaction.txt file when I click the link, but rather a "meshagents" file and _almost_ every time it appears to do _nothing_ when I clilck save, but _sometimes_ the `meshagents` file shows up in the list of downloads as a "Canceled" download, and _sometimes_ it appears in the list saying "Failed - Bad certificate". (Note: Again, this is on localhost, using the automatically created, known to be not-valid certificate that claims to be issued to 'un-configured'.)  If I refresh the page and try again, I can download the files normally again.

Interestingly, opening chrome://downloads, and clicking "retry" (on the "Cancelled" "meshagents" files) fails similarly to clicking the links to begin with, but if I click the url that it says it was trying to download (`https://localhost/meshagents?meshcmd=<number>` or `https://localhost/meshagents?meshaction=generic`) it downloads the appropriate meshcmd binary or meshaction.txt file just fine.

I find this really strange.

Version details:
Windows 10 Home Version 1803 (OS Build 17134.829)
Node version 10.15.3, NPM version 6.4.1 (portable version downloaded from [here](https://github.com/jgonyea/nodejs-portable/releases/tag/10.15.3))
MeshCentral v0.3.7-d installed via `npm install meshcentral`, run via `node node_modules\meshcentral\meshcentral.js`
chrome://version reports "75.0.3770.100 (Official Build) (64-bit) (cohort: Stable)"

**Comment by MailYouLater** [comment]
... OK, maybe I was wrong about when it happens.  ... It seems like I can reproduce it just by ... just waiting for several seconds before trying to click the links.

**Comment by Ylianst** [comment]
!??!?!? I am in Chrome now trying a bunch of things. I do tend to use FireFox as my primary browser, so sometimes I miss a problem on Chrome... trying to figure this out now.

**Comment by Ylianst** [comment]
There are some weird things going on. After playing around with that dialog box for a while and doing lots of downloads, the left bar stops sizing correctly. I also got it to stop downloading. Weird. I just noticed the minified version of web page is not minimized correctly, I am going to fix that and try the minified version.

![MC2-Error](https://user-images.githubusercontent.com/1319013/60633397-5ad91000-9dbf-11e9-9ae2-223d53b7bcd5.png)

**Comment by Ylianst** [comment]
One hint. I got Chrome to say "bad cert" on each download at one point. I also don't see the same problem on my cloud servers that have correct TLS certificates. I wonder if "localhost" and the self-signed cert + downloads combine to cause this problem.

**Comment by Ylianst** [comment]
FYI. I got no idea how to go about fixing this. I will need to do more research or maybe an upcoming Chrome update could magically fix this - not sure.

**Comment by D4V3M0NK** [comment]
Ylian,
How can we help? Are you looking for developers / testers?

**Comment by JSuenram** [comment]
@MailYouLater 
This is not happening in newer version any more.
Please confirm and close.

**Comment by dinger1986** [comment]
@si458 seems to be working fine see last comment
