### ISSUE TITLE
Adding additional keyboard combo's to the "Send" menu

### ISSUE THREAD

**Issue by BillThyCat** [Ylianst/MeshCentral#3371]
Would like to be able to add additional combo-keys to the drop down list for the "Send" option in the lower left corner of the desktop screen.  We have a developer who uses these combo keys to fire off batches and he is unable to send them thru because his local windows machines traps them and doesn't pass them thru to mesh.

Is there an easy way to add these in the code? or does it take the developer to be able to add these.

Thanks,

BTC

**Comment by AntonAndreevichMoroz** [comment]
Right click on them and select "Configure". A window will open in which you can customize keyboard shortcuts. Each user can do this for himself.
![image](https://user-images.githubusercontent.com/51225180/146562812-a8edbad1-5ad2-4923-ada6-63d207bf0a70.png)

**Comment by AntonAndreevichMoroz** [comment]
![image](https://user-images.githubusercontent.com/51225180/146563370-c69a0909-7cc1-4506-a8d3-84ad354f45bd.png)

**Comment by BillThyCat** [comment]
Your a genius!

I keep forgetting to try right clicking things.  I've found several hidden menus before, just didn't think to try it on this.

It appears the developer was mapping keys from the numeric keypad, but he did say he could use other keys, so I'll have him switch to something that appears on the available list of keys and verify it works.

Thanks!

**Comment by Ylianst** [comment]
I do have a YouTube video on [12 MeshCentral Tips & Tricks](https://www.youtube.com/watch?v=CmAG6cT1Yv8) that goes into some of these :)
