### ISSUE TITLE
Weird PC: Unexpected device showing up on my MeshCentral server

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3372]
Hey ! Today I saw that strange PCs appeared. I did not throw the link to anyone. 

![изображение](https://user-images.githubusercontent.com/95762246/146579438-1d99b532-fd7f-484d-a976-0bd876f38e7e.png)

**Comment by Ylianst** [comment]
(Fixed poor quality title)

This is normal. What likely happened is that an anti-virus vendor downloaded your MeshAgent.exe and ran it in a virtual machine sandbox to text what the executable will do. The device will show up for a few minutes and disconnect. Others have reported this. Just delete the device. I don't think there is anything I can do to fix this, it's normal operation of anti-virus vendors.

Hope that helps,
Ylian
