### ISSUE TITLE
Take control display only ? Why ?

### ISSUE THREAD

**Issue by GeorgesDick** [Ylianst/MeshCentral#3373]
Since one or two weeks, when I try to "take control" over a PC, I can see his screen, send commands using the menu on the bottom-right ("Alt + Ctrl + Suppr", "Win", etc.), send text ("Type" button): every interaction works (even the chat, lock screen, etc.), but the mouse and my keyboard are not "captured".
I checked every settings I could find, but none changed this strange behavior.

**Comment by krayon007** [comment]
I assume the "Remote Control" checkbox is checked? What server version are you running, and what client OS and version is the machine you are trying to control, running?

**Comment by GeorgesDick** [comment]
I think the checkbox is checked (I didn't change anything, and it used to work).
My server version is 0.9.55
The machine I'm trying to control is running Windows 10 : 
![image](https://user-images.githubusercontent.com/576271/146754090-7493a700-5736-432a-8033-da6a7d4c80cc.png)


Here's a screenshot of my functionalities (I MeshCentral in french) : 
![image](https://user-images.githubusercontent.com/576271/146753474-2e191ef7-6819-4eb2-9a75-d053564aeac8.png)

**Comment by Ylianst** [comment]
Can you check that the "Input" checkbox is checked? Red circle below.

![image](https://user-images.githubusercontent.com/1319013/146849087-252885b6-8fc1-46d6-80c0-e95d30fa6d4d.png)

**Comment by GeorgesDick** [comment]
Can't believe it was that simple. And why somebody unchecked this checkbox?
Thank you for your help, and sorry for such a stupid question!

**Comment by Ylianst** [comment]
I did make the checkbox text red when unchecked because this situation happened before. Glad we could help.
