### ISSUE TITLE
Unable to connect MeshCommander 0.9.1 to MeshCentral 9.0.60.

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3374]
Unable to connect MeshCommander 0.9.1 to MeshCentral 9.0.60.
TCP packets are visible between the client and the server at the time of connection but nothing happens afterwards

![2021-12-20 15_08_31-Window](https://user-images.githubusercontent.com/95504809/146779830-b5b7835b-a666-48d6-bee2-28df92d967e1.png)

Hybrid (LAN + WAN) mode, Production mode
I don't know how to provide more logs

We replaced the web certificate generated by MeshCentral with a certificate generated for ourselves.

**Comment by Ylianst** [comment]
I just tested it and it worked for me.

![image](https://user-images.githubusercontent.com/1319013/147712344-28da2a18-9b84-4f2c-b134-c1249c6a88ec.png)

Make sure the "Certificate Hash" is empty so that you get a prompt to check the certificate.

**Comment by Ylianst** [comment]
I just tested it with 2FA token from Google Authenticator app and that worked to. I am updating the "MeshCentral Connect" dialog box now since it has an old message.

**Comment by Ylianst** [comment]
Ok, just fixed the MeshCentral connection dialog box text in MeshCentral v0.9.2.

**Comment by Ylianst** [comment]
If your server is public and if you want to send me a dummy account with server information in private, use [my contact info here](https://www.meshcommander.com/contact-information). I can try to connect to your server and debug the issue. Otherwise, not sure what else I can do.

**Comment by pascal-chag** [comment]
I handed over the original web certificate which had been replaced by one generated by ourselves.
It works now.
Our certificate should not be secure enough.
is not a bug
A message may be missing indicating that the certificate is not secure enough 
I close the issue
