### ISSUE TITLE
Failed to obtain certificate: connect ETIMEDOUT on Windows 10 

### ISSUE THREAD

**Issue by RobertAlonso** [Ylianst/MeshCentral#3376]
I have read everything you have posted and made multiple changes to the config.json file and keep getting the ETIMEDOUT error message. My domain is registered and pointing to a static IP. Checking letsdebug.net gives a response that all is OK. Checking the ports from the Windows 10 machine using the grc.com (ShieldsUp) tool shows that port 80 and 443 are open. IIS is disabled and nothing else is grabbing those ports.

My config,json file is as follows:

```
{
   "settings": {
	  "cert": "mesh.myundiscloseddomain.com",
	  "port": 443,
   	  "redirPort": 80,
	  "ignoreagenthashcheck": true,
	  "syslog": "meshcentral",
      "syslogjson": "meshcentral-json",
      "syslog": true,
      "syslogjson": true,
      "plugins": {
        "enabled": true
	    }
   }, 
    "domains": {
	"": {
	    }     
   },
   "letsencrypt": {
		"email": "robert@myemaildomain.com",
		"names": "mesh.myundiscloseddomain.com",
		"production": false
	}
}
```

Any help is greatly appreciated.

**Comment by nzalev** [comment]
Add `"skipChallengeVerification": true,`to your letsencrypt config:

```json
"letsencrypt": {
  "email": "robert@myemaildomain.com",
  "names": "mesh.myundiscloseddomain.com",
  "skipChallengeVerification": true,
  "production": false
}
```

**Comment by RobertAlonso** [comment]
That did the trick. It is magic!

Thank you so much for your help with this great product.

Robert
