### ISSUE TITLE
Mesh Agent & AMT support on Chrome OS 

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3378]
Is the mesh agent fully supported on chrome os if yes then how to install that and also want to know if AMT provisioning is supported on Chrome OS or not via mesh central?

**Comment by Ylianst** [comment]
The best option for ChromeOS is to install the [MeshCentral Android agent](https://play.google.com/store/apps/details?id=com.meshcentral.agent2&hl=en_US&gl=US). You can also install the Linux agent in Chrome OS if you are in developer mode, but this is not typical.

**Comment by krayon007** [comment]
If you wanted to install the Linux agent under Chrome os, you can refer to the readme located here:

**Comment by sysadmin-us** [comment]
@Ylianst But how to install the MeshCentral Android agent on ChromeOS, it is giving the option to scan the QR code, how to scan this QR code from Chromebook?

**Comment by Ylianst** [comment]
The Android agent gives you the option to enter the paring URL. You can hover over the QR code and copy the paring link...

![image](https://user-images.githubusercontent.com/1319013/147712208-3b0ade96-7920-4e9b-97c9-e2c61ab61365.png)

Then, paste it into the Android agent. You can also open the web page on the Android device and click on the QR code. The Android agent is registered to handle any "mc://" URL and so, it will open and offer to pair to that server.

Let me know if that helps.

**Comment by si458** [comment]
@oniw if you share your config.json we might be able to work out why its not connecting

**Comment by oniw** [comment]
@si458

**Comment by oniw** [comment]
@si458 Hi Simon, here is the config.json

{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "mc.mydomain.com",
    "TrustedProxy": "172.20.1.101", #behind nginx reverse proxy
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "mysessionkey",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": true
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": false,
      "NewAccounts": false,
      "localSessionRecording": true,
      "_userNameIsEmail": true,
      "certUrl": "https://mc.mydomain.com:443",
      "allowedOrigin": false
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
