### ISSUE TITLE
ERROR: WSMAN call failed: Error #400

### ISSUE THREAD

**Issue by MRodrigoF** [Ylianst/MeshCentral#3379]
Hello when trying to add a new PC to meshcentral and running the cira_setup-mescript script in meshcommander 0.9.1 I get the following error:

```
Script Started
Policies removed successfully
Adding root certificate ...
Management Presence Server (MPS) successfully added
Found matching (primary) mps: Intel (r) AMT: Management Presence Server 0
Setting policy ...
Policy added successfully
SUCCESS: Remote Access user interfaces set to: BIOS & OS Enabed
Parsing block parameters
Setting Environment Detection
ERROR: WSMAN call failed: Error # 400
Script Completed
```

I am new to this, the PC appears to me in meshcentral, but it does not activate CIRA and it does not show the information of the equipment.
![image](https://user-images.githubusercontent.com/96563502/147196455-91135712-1fe7-4ef6-b2b2-4885247a37d6.png)

Can you help me? Is it necessary to add any additional information
![2021-12-23_001119](https://user-images.githubusercontent.com/96563502/147196518-b4fee3fe-549e-42f9-9701-7ea1f49ac939.png)
?

**Comment by Ylianst** [comment]
New versions of MeshCentral don't have the CIRA setup script anymore. Instead, the support for configuring CIRA is built-in. You can take a [look at this video](https://www.youtube.com/watch?v=naWKE3rT6e8) and use the "amtconfig" command in the agent console to check what is going on.

**Comment by MRodrigoF** [comment]
Hello Ylian I do not have the latest version of Meshcentral installed. I am attaching an image of the version we have installed
![image](https://user-images.githubusercontent.com/96563502/147289485-94cd3025-90a6-4a3e-aec8-07d24402544f.png)
Meanwhile I am reviewing the command and video that you indicate
