### ISSUE TITLE
ВНИМАНИЕ: MeshCentral SSH support requires NodeJS 11 or higher.

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3380]
ВНИМАНИЕ: MeshCentral SSH support requires NodeJS 11 or higher.

What to do ?

**Comment by nzalev** [comment]
Meshcentral has a minimum required NodeJS version of 10 to function - but some features require higher versions to use.

You can use the `versions` command in the server console to find which version of NodeJS meshcentral is running with.
![Screenshot from 2021-12-23 07-24-54](https://user-images.githubusercontent.com/63608819/147240538-c4c9bab5-d68d-4a05-9fd6-70c2637e038a.png)

**Comment by gosteras** [comment]
how this do in docker-compose  ?
