### ISSUE TITLE
WebRTC not working

### ISSUE THREAD

**Issue by albertomna** [Ylianst/MeshCentral#3381]
Hey Guys, thanks for this awesome sotfware.
I have a question about WebRTC and  how its works.
I have seen that when i messagging with a device in LAN, the webcam and mic icons appears.
But, when i try to connect with a PC in WAN, the icons doesn't appear.
So, i have checked in config.json if the `webRTC:true` is set and it's ok.
I have checked the webrtc config and i have the STUN mozilla and google.
I have opened for a try all the port.
My Mesh is under reverse proxy, and i have done this following the @Ylianst guide about it.

So, i miss something? THanks again

**Comment by Ylianst** [comment]
There are two usages of WebRTC in MeshCentral.

Remote desktop & files: For this usage, the current MeshAgent has a bug in WebRTC and so, WebRTC is disabled. The next agent will fix this just after the holidays. When you put `webrtc: true` this should enable this usage.

MeshCentral Messenger: Separately, WebRTC used in messenger should always be enabled. The browsers will automatically try to connect using WebRTC and if they can, the audio/video icons will show up. WebRTC is UDP based, so it needs to find it's way thru routers. If one side is using a HTTP proxy, that will certainly block it. At some point, I need to add the option to add a TURN server in MeshCentral to allow WebRTC when HTTP proxies or some NAT types are on the network.

**Comment by albertomna** [comment]
Yes, the question is that my Reverse is under a NAT and so i think i need a TURN Server also. I have tried to add a Turn server in config.json but seems not work... so i am waiting for this update..thanks @Ylianst for the answer!

**Comment by Ylianst** [comment]
I have been researching this. I would like to add a TURN server to MeshCentral, one option is [`node-turn`](https://www.npmjs.com/package/node-turn) but it does not support TCP/TLS relays, just UDP to UDP. I can't find any other NodeJS turn server.

Another option is [coturn](https://github.com/coturn/coturn). You would need to install it separately from MeshCentral and then give the settings and credentials to MeshCentral to use it. This would not be ideal as it would be more work for administrators to setup and more opportunities for mistakes. Also, if I had TURN built-in, I would do settings logging and account for the data transferred and who is responsible for it.

Still looking... the crazy option would be to build my own TURN server in MeshCentral, I have done it in the past in C#.

**Comment by albertomna** [comment]
Dear @Ylianst,
I have already installed the coturn server on the Reverse Proxy. I have tried to set this to config.json but i didn't understand the credential that i must set in MeshCentral. So, i have set all the coturn settings (the default settings without any secret and on the port 3478) and i have write this to config.json (under WebRTC config turn:domainname:3478), but not working.
I think is useful for an administrator see also the WAN device and this functionality seems to be good for me.

**Comment by Ylianst** [comment]
Ha. In the settings section of the config.json, add this:

```
    "webrtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" },
        {
            "urls": "turn:my-turn-server.mycompany.com:19403",
            "username": "optional-username",
            "credentials": "auth-token"
        }
      ]
    }
```

This information will be passed directly to the browser and should work. Let me know if it does.

**Comment by albertomna** [comment]
Dear @Ylianst  thanks for your work.  I have set my TURN server with the port 19403 (and not 3478) enable lt-cred-mech, set a username e password and add to config.json your indications. Now, works everything!Thanks again for the support!

**Comment by Ylianst** [comment]
Nice! Thanks for reporting back!
