### ISSUE TITLE
Windows Installer never completes.  Hangs on Installing MeshCentral service

### ISSUE THREAD

**Issue by frosterrj** [Ylianst/MeshCentral#3382]
Installer used was MeshCentralInstaller-2.11.exe

Win 11 host, updated prior to install:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎12/‎2/‎2021
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0

Removed old attempted installation using the 'uninstall' option on installer and manually removed Node.

Ran installer using admin console with -log  attached
[log.txt](https://github.com/Ylianst/MeshCentral/files/7781561/log.txt)

The installing service window has never closed down.   I noticed that the log shows service creation and start, but looking at services.msc showed that it was created but not actually started.  I started it manually and attempted to get to https://localhost and got timeout.  Tried same on external host using the ip for the host I tried to install on and got same timeout.

Would like to get this running on this windows machine but so far has proven impossible.

thanks,
R

**Comment by dinger1986** [comment]
@si458 I beleive this installs fine now

**Comment by si458** [comment]
this has just been fixed now https://github.com/Ylianst/MeshCentralInstaller/commit/c277e19c675177da2840a8c243a9285460b687d9,
please use the new installer from meshcentral website
duplicate also of #6331
