### ISSUE TITLE
I cannot understand how it turns out to turn on the computer remotely if it is turned off. ? 

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3383]
I cannot understand how it turns out to turn on the computer remotely if it is turned off. ? 

 explain   me, 
Thank you

**Comment by jsastriawan** [comment]
There are several ways. Wake on LAN method: sending a specially crafted packet to send wake up command to computer ethernet. This requires WoL is enabled on NIC and BIOS. Using Intel AMT API to wake up system remotely: this requires Intel AMT enabled and activated system and in cloud environment, AMT CIRA is required.

I hope I am answering your question.

**Comment by gosteras** [comment]
thanks
