### ISSUE TITLE
"Intel®AMT" tab inaccessible

### ISSUE THREAD

**Issue by e-a-m** [Ylianst/MeshCentral#3384]
Hello and congrats for this great software!
Just a question: I set up a personal MeshCentral server with MPS and Nginx proxy (following the official user guide) and it works good so far.
In my groups, I have AMT computers that I set up in CIRA mode with ACM under the group tab (setup.bin) and the configuration worked like a charm.
The thing is: while I can connect to AMT under the "Desktop" and "Terminal" tabs, the "Intel®AMT" tab is empty with the following message from my web browser:

> Firefox Can’t Open This Page
>
> To protect your security, _meshcentral.server.domain.name_ will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

I also tried with `"AllowFraming": true`, but it not works...

Here is my config.json file:
```
{
  "settings": {
    "Cert": "meshcentral.server.domain.name",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AgentPong": 300,
    "TlsOffload": "127.0.0.1",
    "MpsPort": 44330,
    "MpsAliasPort": 4433,
    "MpsTlsOffload": true
  },
  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443/"
    }
  }
}
```

**Comment by Ylianst** [comment]
Interesting, I will check this.

**Comment by Ylianst** [comment]
This is not happening on my servers and I am going to take a guess that you have a reverse proxy that is adding extra security headers in the HTTP response. Can you open the browser console and look at the "Content-Security-Policy" or "X-Frame-Options" header? It should look like this image.

![image](https://user-images.githubusercontent.com/1319013/147712067-15849c95-2aa6-4545-a21a-c93e87e66cf7.png)

I am guessing the reverse proxy is adding headers that disallow embedding.

**Comment by e-a-m** [comment]
Oops, sorry, that's my fault!
I secured my Nginx server with the help of [Cipherlist](https://cipherlist.eu/) and forgot that the config file contains the `add_header  X-Frame-Options  DENY;` directive.
Thanks a lot for pointing me in the right direction!
