### ISSUE TITLE
Meshcentral with remote computer on Wifi

### ISSUE THREAD

**Issue by DnDNero** [Ylianst/MeshCentral#3386]
Hi there,

I am looking into using Meshcentral to manage some machine with Intel AMT activate but using WIFI. Will Meshcentral' power management option work with AMT enable machine that use separate wifi card.

**Comment by jsastriawan** [comment]
AMT over wifi only work with certain wifi card certified for each particular generation. The quickest check to see if AMT over wifi will work is to use MeshCommander to see if you can see AMT WiFi network setting. Oh btw currently only Windows is working because Linux WiFi driver and NetworkManager are not cooperating with CSME WiFi driver yet.

**Comment by DnDNero** [comment]
This might be a stupid question. When i connected to a PC via meshcommander (on LAN - cable), if isee AMT WiFI network setting then AMT should work when i switch over to wifi. Correct ?

**Comment by jsastriawan** [comment]
There is no stupid question. AMT WiFi coexistence with host is quite tricky sometimes. First you need to add your WiFi access point to that wifi configuration to allow CSME to take over WiFi when OS is not functioning. Then it should work. Please also make sure you install Intel WiFi driver and Intel LMS package. It should work. You can detach the ethernet and then try connecting to that device using the IP address acquired by WiFi interface. Good luck.

**Comment by DnDNero** [comment]
Thank you so much for you instruction. 

Im trying to test with a local machine first before trying to go to WAN mode and test with remote machine on WIFI network. Im having problem with adding AMT cert to the server. Right now I can connect to the local (V-LAN) machine with mesh agent and AMT configuration is done automatically by the mesh agent (some machine i tested with can activate ACM and some stuck with CCM). 

Given that info I have 2 questions:

1. Do I need AMT intel cert to activate ACM with local machine or the cert is only needed for remote machine (WAN mode)
2. What is the process of adding cert to the server and configure amt on the local machine ? If you can point me to some resource it would be great.

**Comment by dinger1986** [comment]
@si458 stale

**Comment by jsastriawan** [comment]
You should open new issue on AMT activation. But anyway I will answer:
1. For host-based activation, it will require AMT activation certificate matching the domain supplied by DHCP Option 15.
2. Please look at Open AMT Cloud Toolkit project - a close relative to this project. It has an AMT activation component and newer remote provisioning client can activate locally and also can manage Wi-Fi profile too.

**Comment by dinger1986** [comment]
Does this need added to the docs?

**Comment by si458** [comment]
@silversword411 can you add the AMT info above to the docs somewhere please?
just explain amt needs certificate for full features and wifi can be used if supported!
