### ISSUE TITLE
Notifications keep on coming [fixed]

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3388]
I just updated yesterday from like 40 versions ago.

Now I receive notifications for all groups and they are not set.
Tried to enable and disable, still the popup in the top right corner and in the windows task bar.

While typing this I found the notifications setting in my profile. disable the notifications there did the trick.
Did this behaviour change?

**Comment by Ylianst** [comment]
Yes, the behavior did change. Now the connect/disconnect notification setting in the account will event for all devices.

![image](https://user-images.githubusercontent.com/1319013/147785078-4b54c6dd-5823-47d3-8867-60982de86754.png)
