### ISSUE TITLE
get S/N of system on mesh

### ISSUE THREAD

**Issue by UnP1u9** [Ylianst/MeshCentral#339]
Hi, 

can we also get system S/N on mesh server just live username and IP.

**Comment by Ylianst** [comment]
Hi. Can you explain how to get this serial number? or, can you point to an example of some other software that can get this serial number? - Thanks.

**Comment by UnP1u9** [comment]
Hi, I meant the Computer S/N we get from command "WMIC BIOS GET SERIALNUMBER" from cmd and some other command from linux.

Just thought would be good for assets checking.

**Comment by Ylianst** [comment]
Thanks for the example command. Yes, this would be interesting. I will check with Bryan (author of the mesh agent) for this.

**Comment by UnP1u9** [comment]
and can we make some arrangement so that we get a URL like "remote.mes:888\laptopserialnumber" 

so that i can integrate it with my asset management tool where it show a icon in front of asset which brings me to the above link (by taking laptopserialnumber from my asset tool) and ask for creds and take remote access.

and also any way to integrate password with any different app like my asset management so that i can authenticate it from there. , node is lil new to me 😅

**Comment by Ylianst** [comment]
I just tried "WMIC BIOS GET SERIALNUMBER" on two of my systems, both Intel vPro machines and the serial number returned is empty. I don't think this command gives a reliable response and so, would not work on most machines. A quick look online shows that this field is often not set.

I like this idea, but I need a reliable machine identifier that works on both Windows and Linux. If you can find a reliable way to get a device identifier, I will look at it.

**Comment by UnP1u9** [comment]
These S/N only works with laptops and we need it for same only, no idea about vPro machines.

**Comment by UnP1u9** [comment]
sudo dmidecode -s system-serial-number 

this work fine for most linux machines (laptop only)

**Comment by Ylianst** [comment]
Thanks for the Linux command, I will give it a try.

**Comment by Ylianst** [comment]
Will need Bryan to take a quick look at this, somehow the serial number is not in the SMBIOS tables, but it should be present.

**Comment by UnP1u9** [comment]
Checked a bit and found that serial number can be misplaced if motherboard is changed or replaced and serial no. not fixed by technician(same happened to me too once) or may be they were not added at the first place😕.

**Comment by Ylianst** [comment]
Once implemented, the MeshAgent will send the latest serial number of that computer to the server when the agent starts up, so it should stay current in MeshCentral. Of course if it's not updated in your other software, it will not match anymore.

**Comment by UnP1u9** [comment]
Yep, thnx a lot.

**Comment by MRCode010101** [comment]
Maybe these will work;

Windows:

(get-wmiobject -Class win32_bios | select SerialNumber).SerialNumber

Mac:
ioreg -l | grep IOPlatformSerialNumber

**Comment by ghplw** [comment]
Serial number is a great start but maybe this could be expanded to having a whole hardware tab. I've seen some RMM agents that pull down a really great list that shows firmware versions of drives, models and serial numbers on RAM etc. This information could later be used with a reporting function to search for particular hardware combinations which is obviously very useful if an admin suspects a particular combination is causing an issue.

**Comment by Ylianst** [comment]
Agreed. Bryan just started adding MeshAgent code to fetch a bunch of that data. I will be working over the next week to add server support for this and be able to download reports. Bryan's work is made difficult because he need to get that information consistently from different operating systems.

**Comment by krayon007** [comment]
The way I have it structured now, is that I return an object that has a set of fields that are correlated on Mac, Linux, and Windows. (The field names and values will be identical, regardless which OS is installed on the hardware)

The object will also have a 'linux', 'windows', and 'macos' field that will contain OS specific fields that I was able to fetch.

**Comment by SomeGuru** [comment]
This looks resolved in latest builds can you verify @UnP1u9? If so can you close this issue with your answer?

**Comment by UnP1u9** [comment]
Thanks All, this looks amazing
