### ISSUE TITLE
Feature Request: Text Notifications & Notification Groups

### ISSUE THREAD

**Issue by UFOTyler** [Ylianst/MeshCentral#3390]
Hey Mesh Team,

I've been setting up more monitoring functionality for my clients and there servers, I've setup email notifications and now have messaging setup with Telnyx. Some features I think would be great additions would to allow connect/disconnect notifications over text messaging similar to email notification options for groups/devices. 

Also notifications for user groups instead of a per user bases. Example would be if I want a text and/or email when a server disconnects sent to team of people. Even if we can choose one of the already implemented user groups in mesh to receive the notification. As of now if I setup a notification for a server its only setup for my user.

These would be awesome for our workflow and add a ton of functionality.

Thanks!

**Comment by si458** [comment]
what text messaging company do you use?
the is a few other notifiction methods built in already now
https://ylianst.github.io/MeshCentral/messaging/

**Comment by si458** [comment]
closing as stale, please reopen if you let us know what sms providers you want to add for notifications
