### ISSUE TITLE
Documentation of Postgres

### ISSUE THREAD

**Issue by Yamacore** [Ylianst/MeshCentral#3398]
Hello there,

we are currently using 0.9.61 and try to migrate to a postgresql.
(https://meshcentral2.blogspot.com/2021/11/meshcentral-postgresql-streaming-pre.html)
it seems that its not possible to define the database it should write to right now:

this configuration works:
```
    "postgres": {
      "user": "someuser",
      "password": "somepass",
      "port": 5432,
      "host": "localhost"
    },
```

while this one doesnt:

```
    "postgres": {
      "database: "somedb",
      "user": "someuser",
      "password": "somepass",
      "port": 5432,
      "host": "localhost"
    },
```

is there any official documentation to this as all sample files just got mongo/default n some documentations reach up to mysql/mariadb but no postgres yet.

Greets Yama

**Comment by Ylianst** [comment]
Looking at the MeshCentral code, if "database" is not specified, the default value should be "meshcentral". So, having this configuration:

```
    "postgres": {
      "user": "someuser",
      "password": "somepass",
      "port": 5432,
      "host": "localhost"
    },
```

Should be the same as this one:

```
    "postgres": {
      "database": "meshcentral",
      "user": "someuser",
      "password": "somepass",
      "port": 5432,
      "host": "localhost"
    },
```

If this is not the case, let me know, I will investigate.

**Comment by Yamacore** [comment]
thanks, it works this way
