### ISSUE TITLE
Question/Feature request:   Support/docs for using SQL Server as DB backend

### ISSUE THREAD

**Issue by frosterrj** [Ylianst/MeshCentral#3399]
Left a post on MC Reddit:

Happen to have the linux version running on the same machine as Meshcentral so I would be pretty convenient to have the MC db there instead of the nedb I am currently using.

**Comment by nzalev** [comment]
MS SQL Server is not currently supported, and there is no existing code in Meshcentral to work with TSQL.

The current DB options are MongoDB, MariaDB/MySQL, and Ylian just recently added Postgres.

**Comment by frosterrj** [comment]
ok.  thanks.
