### ISSUE TITLE
No Desktop tab on Ubuntu 18.04.1 LTS 64Bits

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#34]
After install client agent on ubuntu 18.04.1 64bits deskttop tab was missing.

![mesh_ubuntu](https://user-images.githubusercontent.com/45072744/49136253-658f6c00-f2e9-11e8-8a16-cbb8324281df.jpg)

**Comment by Ylianst** [comment]
Currently, Remote desktop does not work on Ubuntu 18.04, however Bryan is working on a fix today and in the next few days. Older versions of Ubuntu should not have this problem.

**Comment by Ylianst** [comment]
Correction, seems like all Linux machines got their desktop tab removed... working on fix now.

**Comment by Ylianst** [comment]
Just published a patch to fix this, MeshCentral v0.2.3-j.

**Comment by edorbike** [comment]
Ok, thanks
