### ISSUE TITLE
Linux RC Commands Ignored/Missing

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshCentral#3400]
I was wondering. I have some custom commands I execute in my profile rc files on a few linux systems I remote into so I get an immediate status update and banner title of the system when I connect. But when I remote in with MeshCentral I only receive a prompt.

I did see another thread somewhere about how MeshCentral runs a few commands (including clear) when it connects. Is there a simple way to add to this list of commands that's persistent through upgrades?

**Comment by Ylianst** [comment]
Hi. Yes. First, try right clicking on the terminal "Connect" button and select the other options. They may be what you want.

![image](https://user-images.githubusercontent.com/1319013/147993650-a3139c52-cfb3-497e-84af-b6dc386d5a87.png)

If that does not work, you can indeed have MeshCentral type in commands on each terminal connection. It's configured in the config.json, so it will be persistent through upgrades.

In the "domains" section of the config.json, you can add something like this:

```
      "terminal": {
        "launchCommand": {
          "linux": "clear\necho \"Hello Linux\"\n",
          "darwin": "clear\necho \"Hello MacOS\"\n",
          "freebsd": "clear\necho \"Hello FreeBSD\"\n"
        }
      }
```

Let me know if that works.

**Comment by krayon007** [comment]
To add to this, I think the option that should work for you, is login shell. That will run all the profile stuff just as if you actually logged in from ssh.

**Comment by honestlai** [comment]
This worked perfectly!! Thank you. I actually just made the linux command area blank, which solved my problem.

Thanks again!!
