### ISSUE TITLE
Request: External IP Filter List

### ISSUE THREAD

**Issue by Matt-CyberGuy** [Ylianst/MeshCentral#3401]
Happy New Years MC team, you guys are the best!

Got a quick, hopefully not difficult request. Our list of filtered IPs is growing more and more, and is difficult to interpret. Would it be possible to have the IP filter options reference a file  with the list of IPs?

Added bonus would be if the IPs in the file could be listed in a way with a description of who the IP belongs to that would be ignored by MeshCentral.

**Comment by Ylianst** [comment]
Good idea, working on it now.

**Comment by Ylianst** [comment]
With the next version of MeshCentral, you can now do this in the config.json:

```
    "userAllowedIp": "file:userallowedips.txt",
    "userBlockedIp": "file:userblockedips.txt",
    "agentAllowedIp": "file:agentallowedips.txt"
```

You put `file:` followed by a file name that is in `meshcentral-data`. The file can look like this:

```
# My list of blocked IP's
185.101.70.0/24
185.46.85.0/24
37.9.44.0/24
37.9.45.0/24
5.189.205.0/24
5.189.206.0/24
5.189.207.0/24
5.62.153.0/24
5.62.156.0/24
5.62.158.0/24

# One more list
5.8.44.0/24
5.8.45.0/24
5.8.46.0/24
79.110.28.0/24
79.110.31.0/24
91.204.14.0/24
95.181.218.0/24
95.85.81.0/24
```

All the lines that start with a number or `:` will be used, everything else is ignored. So, you can put comments anyway you like, but probably best to start then with a `#` or something to make it clear.

**Comment by asasin114** [comment]
Could I make one addition to this request? Could you make it so the allowed list accepts fqdn's? This would be super helpful for scenarios where a site has a WAN address issued by DHCP and is using Dynamic DNS services.

**Comment by Ylianst** [comment]
I am not sure why FQDN would be useful, mostly users and agents don't have FQDN's assigned to them and you can't specify a range of IP addresses using FQDN. These lists are for allowing or blocking IP addresses ranges that do not typically have FQDN's assigned to them. Unless I am missing something, not sure FQDN would be useful.

Also, if you block a FQDN instead of an IP address, someone can change the FQDN record and keep attacking?

**Comment by rapi3** [comment]
I want to filter login IP so I added my LAN network IP 192.168.1.0/24 to userallowedips.txt and I can't log in from LAN any more: Unauthorized
Latest version 0.9.91
I also use: ?key=xxx

Any ideas ?

**Comment by jsinoy** [comment]
Hi Ylianst ,

I am a big fan of meshcentral and it does really work well . I have tried the the solution above to filter ip address but unfortunately it doesn't work for me . 

when my config.json looks like this , it works fine ,
"agentAllowedIP": "23.23.23.23",

however when my config.json looks like this , it doesn't work.
"agentAllowedIP": "file":agentallowedips.txt",

Note : agentallowedips.txt file is under meshcentral-data .

**Comment by si458** [comment]
@silversword411 any chance you could add this to the docs in your free time?
also update the manifest as it still shows only an string or array

**Comment by silversword411** [comment]
> add this to the docs in your free time?

What exactly are you referring to? A writeup on how to block by IP?

**Comment by si458** [comment]
> > add this to the docs in your free time?
> 
> @si458 What exactly are you referring to? A writeup on how to block by IP?
> 

Yes sorry basically this step in the docs somewhere

https://github.com/Ylianst/MeshCentral/issues/3401#issuecomment-1004461183

**Comment by silversword411** [comment]
Actually, it's already there <https://ylianst.github.io/MeshCentral/meshcentral/#server-ip-filtering>

**Comment by si458** [comment]
> Actually, it's already there https://ylianst.github.io/MeshCentral/meshcentral/#server-ip-filtering

thanks but i was talking about the fact you can use the `file:banedips.txt` value to load the ips from a text file

**Comment by silversword411** [comment]
Last posting said there was a problem with multiple IPs in the file, one per line.

I haven't tested, does it work for you?

**Comment by si458** [comment]
> Last posting said there was a problem with multiple IPs in the file, one per line.
> 
> I haven't tested, does it work for you?

Works fine for me also same for @Ylianst 
https://github.com/Ylianst/MeshCentral/issues/4321#issuecomment-1198565119

**Comment by jsinoy** [comment]
Unfortunately, it really doesn't work to me . Not sure if i have misconfigured anything
Server version 1.0.63 running on linux on AWS (ec2) instance.

it works if my config.json looks like this;
"agentAllowedIp": "1.1.1.1,2.2.2.2,3.3.3.3"

however if i change it to this : it wont work anymore, agents are all offline and unreachable.
"agentAllowedIp": "file:agent_allowed_ips.txt"

**Comment by silversword411** [comment]
> Works fine for me also same

Can you give some screenshots of the text files, and config?

**Comment by CPINetworks** [comment]
> I am not sure why FQDN would be useful, mostly users and agents don't have FQDN's assigned to them and you can't specify a range of IP addresses using FQDN. These lists are for allowing or blocking IP addresses ranges that do not typically have FQDN's assigned to them. Unless I am missing something, not sure FQDN would be useful.
> 
> Also, if you block a FQDN instead of an IP address, someone can change the FQDN record and keep attacking?

Allowing FQDN would allow us to white list tech's home IP's using DDNS. We do not have static IP's everywhere we wish to login from.

**Comment by jsinoy** [comment]
> > Works fine for me also same
> 
> Can you give some screenshots of the text files, and config?
![mc_ipfilter_settings](https://user-images.githubusercontent.com/109936671/186876482-ebd6634f-a10a-48bd-8b95-15e0a0576e75.png)

**Comment by jsinoy** [comment]
![mc_ipfilter_settings](https://user-images.githubusercontent.com/109936671/186876534-e4c14901-7998-4b02-8a19-9cd2f83fc974.png)

When I add a single line in agentallowedips.txt file , it works , but when i add multiple lines of ip , it wont work anymore .

**Comment by silversword411** [comment]
I'm guessing the 122. is your test IP...what happens when you put it on the 2nd line?

Does it go from working to not working? Do you have to restart meshcentral for this to take effect, or is it live like the hosts file in windows?

**Comment by Matt-CyberGuy** [comment]
I know this is a slightly separate question, but once the multi-line IP filtering is solved for, can commented out lines be present in this file?

We have a pretty long list of IPs, would love to be able to label them.

**Comment by Matt-CyberGuy** [comment]
oops, my bad... i just scrolled back thru the thread and saw it's supposed to be possible.

**Comment by Matt-CyberGuy** [comment]
I decided to try this out last night on a fresh install. It seems external lists are not working for me, even if I only have 1 ip.

**Comment by silversword411** [comment]
https://ylianst.github.io/MeshCentral/meshcentral/#server-ip-filtering

**Comment by jsinoy** [comment]
> I'm guessing the 122. is your test IP...what happens when you put it on the 2nd line?
> 
> Does it go from working to not working? Do you have to restart meshcentral for this to take effect, or is it live like the hosts file in windows?

Yes it works fine in a single line only like 1.1.1.1 in the txt file . However when i add multiple line , it wont work anymore. Restarted server few times as well.
 
It works whenagentallowedips.txt content like this;
1.1.1.1

But it wont work when agentallowedips.txt content like this;
1.1.1.1
2.2.2..2

also tried this
1.1.1.1/24
2.2.2.2/24

Maybe i have missed something ?

**Comment by jsinoy** [comment]
Hi Everyone,

I have tested in a new installed meshcentral-server in a windows machine , and ip filter in a text file is successful,  I am not sure why it is not working in ec2-instance in AWS running linux .  maybe i have missed something ?

**Comment by silversword411** [comment]
@jsinoy So it was a 
Linux server: doesn't work
Windows server: works

for IP's in files problem?

**Comment by jsinoy** [comment]
> @jsinoy So it was a Linux server: doesn't work Windows server: works
> 
> for IP's in files problem?

Yes , list of IP's in a text file .  on a newly installed meshcentral-server on windows it is working , however on ec2-instance in AWS (linux) it doesn't work . im not sure maybe i have misconfigured something .

**Comment by Matt-CyberGuy** [comment]
Just revisited this, currently within linux this is still not functioning. I just spun up a brand new server. Once I change the ip filtering to a file, regardless of how many entries, it does not work.

For context, I'm also running this within a docker container behind nginx.

**Comment by si458** [comment]
@Matt-CyberGuy where are you storing the file?
can u share a quick snippet of your config.json?
and can u share a snippet of your file for example?

**Comment by Matt-CyberGuy** [comment]
> @Matt-CyberGuy where are you storing the file? can u share a quick snippet of your config.json? and can u share a snippet of your file for example?

Below is my config.json. I've been slowly building it from scratch pulling from the config of an old instance I plan on retiring
The disabled allowedips.txt is located within the data directory with the config.json file.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "remote.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "",
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": "npmplus",
    "noagentupdate": true,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "RelayDNS":[
        "1.rt.ITCompany.com",
        "2.rt.ITCompany.com",
        "3.rt.ITCompany.com"
        ],
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": 24,
      "keepLastDaysBackup": "30",
      "zippassword": ""
    }
  },
  "domains": {
        "": {
    "title": "ITCompany",
    "title2": "<br/>Cybersecurity | LAN | Data<h2>Remote Monitoring Portal</h2>",
    "welcomeText": "Please enter your email and given password above.<br/>If you are experiencing difficulty connecting to endpoints, need to add/remove users or systems, <br/>or you would like to have your password reset, please contact us at <a href='mailto:sos@ITCompany.com'>SoS@ITCompany.com</a>.",
    "titlePicture": "logo.png",
    "Footer": "<a target=_blank href='https://ITCompany.com'>ITCompany</a>",
    "mstsc": true,
    "agentCustomization": {
        "displayName": "ITCompany Remote Service",
        "description": "ITCompany Remote Service for remote monitoring, management and assistance.",
        "companyName": "ITCompany",
        "serviceName": "ITCompany Remote Service",
        "fileName": "ITCompanyRemote",
        "image": "agent-logo.png"
    },
    "agentFileInfo": {
        "icon":  "ITCompany-Remote.ico",
        "fileDescription": "ITCompany Remote Service for remote monitoring, management and assistance.",
        "legalCopyright":  "ITCompany Remote Agent (c)",
        "originalFilename":  "ITCompanyRemote.exe",
        "productName": "ITCompany Remote Service"
    },
    "altMessenging": {
        "name": "Video Chat",
        "url": "https://meet.ITCompany.com/{0}"
    },
    "terminal": {
        "launchCommand": {
        "linux": ""
        }
    },
    "authStrategies": {        
        "azure": {
            "newAccounts": true,
            "clientid": "",
            "clientsecret": "",
            "tenantid": ""
        },
        "google": {
            "newAccounts": true,
            "clientid": "",
            "clientsecret": ""
        }
    },
    "welcomePicture": "wallpaper.jpg",
    "welcomePictureFullScreen": true,
    "loginPicture": "welcome-logo.png",
    "minify": false,
    "NewAccounts": "true",
    "ManageAllDeviceGroups":["~azure:user@domain.com"],    
    "userNameIsEmail": true,
    "PasswordRequirements": { 
      "min": 8,
      "max": 64,
      "upper": 1,
      "lower": 1,
      "numeric": 1,
      "nonalpha": 1,
      "hint": true,
      "reset": 90,
      "force2factor": true
    },
    "_userAllowedIP": "file:allowedips.txt",
    "_userAllowedIP": "1.2.3.4",
    "certUrl": "https://remote.domain.com:443"
        }
  },
  "smtp": {
    "host": "smtp-relay.ITCompany.com",
    "port": 587,
    "from": "No-Reply | ITCompany Remote Portal <no-reply@ITCompany.com>",
    "user": "ITCompanygroup@gmail.com",
    "pass": "",
    "tls": false
},
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": true
  }
}

```

**Comment by si458** [comment]
you have `_userAllowedIP` uncommented so its being ignored,
you need to remove the underscore `_` and restart meshcentral

**Comment by Matt-CyberGuy** [comment]
> you have `_userAllowedIP` uncommented so its being ignored, you need to remove the underscore `_` and restart meshcentral

I'm aware, I had to disable it since I was not able to get in.

**Comment by si458** [comment]
ok strange one to try,
create the text file on a windows computer using notepad,
upload that file to your linux machine,
then restart meshcentral

the code shows 
`try { lines = obj.fs.readFileSync(obj.path.join(obj.datapath, arg.substring(5))).toString().split('\r\n').join('\r').split('\r'); } catch (ex) { }
`
so it loads the file from inside the `meshcentral-config` file
but also splits each line at the end with the windows return characters!
so its possibly a windows/linix line character issue!

**Comment by Matt-CyberGuy** [comment]
Oh that's awesome, I just finished trying every combination of making and loading the txt file from windows via my Mac... of course before seeing your response, so none of it worked :P

**Comment by si458** [comment]
ok commit done! https://github.com/Ylianst/MeshCentral/commit/df91c90d33525214291aea2217d8220e5977bb1b
you can test in 15mins when the `master` docker image is built!

**Comment by Matt-CyberGuy** [comment]
This is awesome... I'm such a nerd :P
I just changed my docker image source to  ghcr.io/ylianst/meshcentral:master
It's working for me now, and as far as I can tell, it doesn't matter what OS you make the list in.

**Comment by si458** [comment]
Glad it's fixed for you! 
Fixed the not loading a file properly 
Then fixed the separating each line if windows/linux!
