### ISSUE TITLE
Feature Request: Mobile view for shared links

### ISSUE THREAD

**Issue by jokrug** [Ylianst/MeshCentral#3402]
We use MeshCentral for a while now and it is a great and very usefull software.
What we miss is a mobile view for shared links, like it alredy exists for the desktop.
I would like to give our employees a link to view their desktop and only their desktop on their mobile devices.
I guess that would mean to strip down the ./views/default-mobile.handlebars to a sharing-mobile.handlebars.

**Comment by Ylianst** [comment]
Just to be clear, your not looking to manage sharing links from the mobile site... rather, you want to give out a sharing link and if it's accessed from a mobile browser, you want to mobile user interface for it.

**Comment by Ylianst** [comment]
Started work on mobile version of the sharing page. Lots more to do.

![image](https://user-images.githubusercontent.com/1319013/148140004-95fbe7d4-3121-4e72-8fa0-968e042f8f7e.png)

**Comment by Ylianst** [comment]
I am 6 hours into this... I almost got the remote desktop mobile viewer working.

![image](https://user-images.githubusercontent.com/1319013/148167461-d29cd8c6-8584-4ee4-b5b2-f2d679e9b75d.png)

**Comment by jokrug** [comment]
Hello Ylian, never in my life I've seen such a fast reaction on a feature request. Great. Thnaks.

I alredy tried it and it works as expected. That's exactly what we've been missing. We can send a link to our employees now and just by clicking the link they can access their desktops from the mobile fone. Great.

Just one minor thing: How can we scroll in applications on the desktop? For example we have a large Word document and want to scroll down in Word. Swiping just moves the viewport on the desktop. 

Another idea came to mid: Would it be possible, that the meshagent creates or gets the link? A small program could create a QR code from the link and display it on the desktop of the employee. He takes a foto with his mobile fone and that's it. I can't think of an easier way to set up access. That would be genious. Even TeamViewer could not beat that (-;
And I can't see that it's more insecure than displaying a user id and password, like TeamViewer does.

**Comment by Ylianst** [comment]
Thanks. Released MeshCentral v0.9.64 with the new completed web page for mobile devices.

![MC2-GuestMobileSharing](https://user-images.githubusercontent.com/1319013/148284373-a7757658-7f3a-4825-90ec-d29e2031b94a.png)

I will have to look at scrolling, not sure how I can get that working.

**Comment by jokrug** [comment]
Ideas for scolling: I frequently use RemoteRipple, which is a VNC client for Android. They solve the problem by displaying a movable scrollbar above the screen. 
![Screenshot_20220106-071802_Remote_Ripple](https://user-images.githubusercontent.com/6226168/148337994-630480f7-b971-4ad6-9817-a10ed997c68a.jpg)

You could also equip the existing mouse control with a third status "scroll wheel". When it is active, a swipe would not move the viewport, but execute a scroll. That should work good an is probably not too hard to implement...
