### ISSUE TITLE
How to update MeshCentral

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3403]
Hi. 

 what are do ? Is not updated
![изображение](https://user-images.githubusercontent.com/95762246/148085949-c85aacec-efdd-4daf-89f4-1baf57f97058.png)

**Comment by vitko-bg** [comment]
A bit strange question
0.9.63 came out today as I know, just tick the second option and update to the latest version.
Have you done this already?

**Comment by Ylianst** [comment]
Right, click the version you want and click "ok".

![image](https://user-images.githubusercontent.com/1319013/148109463-060e60d2-5f53-4f6a-8cb2-407f709f107a.png)

**Comment by gosteras** [comment]
I do this, but after reboot it still does not update

**Comment by Ylianst** [comment]
No reboot required. Web site should drop and come back in 10 to 30 seconds. If it does not work, do:

```
npm install meshcentral
```

Over the existing installation to update manually.

**Comment by gosteras** [comment]
![изображение](https://user-images.githubusercontent.com/95762246/148200293-76b2edcf-9d12-4940-aedb-5db565737f93.png)

**Comment by vitko-bg** [comment]
What NPM version you are using?

**Comment by gosteras** [comment]
8.3.0

**Comment by nzalev** [comment]
Are you using docker?

**Comment by gosteras** [comment]
nginx-proxy manager docker-compose.   Meshcentral no

**Comment by gosteras** [comment]
i willed reinstall meshcentral. Became normal . Issuse closed 

 all thanks

**Comment by edjayz** [comment]
after the update i have a warning
ATTENTION: Failed to sign agent MeshService.exe: Error: Too few bytes to read ASN.1 value.
ATTENTION: Failed to sign agent MeshService64.exe: Error: Too few bytes to read ASN.1 value.

![image](https://user-images.githubusercontent.com/348511/175376967-31c0fc8c-29bf-40f9-99a4-872f72543e17.png)

**Comment by compumatter** [comment]
You may get a 502 Gateway error after updating if your node version needs to be updated to the version Mesh Central is relying on.  
Ran:  journalctl -u meshcentral -n 50
Revealed:  MeshCentral requires Node v16 or above, current version is v14.21.3.

Updated Node and things went well.

nvm install 18
Downloading and installing node v18.20.8...
Downloading https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.xz...
#################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v18.20.8 (npm v10.8.2)
nvm use 18
