### ISSUE TITLE
Question - are there updated docs on using MySQL/Postgres SQL?

### ISSUE THREAD

**Issue by frosterrj** [Ylianst/MeshCentral#3404]
And is there a migration path from the neDB?  In particular, if I installed using the 'more secure' method, what is the setup requirements.  I am not finding what I would expect in the install docs.

If this exists, please point me in the right direction.

thanks,
R

**Comment by Ylianst** [comment]
Hi. Yes, you can export the basic data using:

```
node node_modules/meshcentral --dbexport bob.json
```

Then, change the database setting you want into config.json, and re-import using:

```
node node_modules/meshcentral --dbexport bob.json
```

I have a [video on this topic here](https://www.youtube.com/watch?v=iPtaaXMdDfY). You can find the same instructions in section 8.1 of the [MeshCentral User's Guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf).

**Comment by frosterrj** [comment]
Thanks.  Getting unrecognized mysql option

sudo node node_modules/meshcentral --dbimport meshnedbexport.json
WARNING: Unrecognized configuration option "mysql".
Imported 19 objects(s) from meshnedbexport.json.

So I don't seem to have the completely correct json.conf?  No docs reference how to place mysql or postrgres so this was my best guess.

{
  "settings": {
    "maintenanceMode": true,
    "lanonly": true,
    "_minify": true
  },
    "mysql": {
    "host": "localhost",
    "user": "admin",
    "port": 3306,
    "password": "thepass",
    "database": "meshcentral"
               }
}

**Comment by Ylianst** [comment]
Thank you for reporting back. For your JSON, you can clean it up like this to make it look better.

```
{
  "settings":
  {
    "maintenanceMode": true,
    "lanonly": true,
    "_minify": true,  
    "mysql":
    {
      "host": "localhost",
      "user": "admin",
      "port": 3306,
      "password": "thepass",
      "database": "meshcentral"
    }
  }
}
```

**Comment by nzalev** [comment]
With respect to `ER_NOT_SUPPORTED_AUTH_MODE`, this has been a long standing issue with the nodejs MySQL connector - it does not support MySql 8 authentication (https://github.com/mysqljs/mysql/issues/2002). This has been the case for more than 3 years now.

You can update your user to use the older authentication:
```sql
ALTER USER 'meshcentral'@'localhost'
  IDENTIFIED WITH mysql_native_password
      BY 'password';
```

**Comment by frosterrj** [comment]
This is the solution for the DB import.  After updating the mysql password all objects look to be imported.

robert@ubuntu-shuttle:/opt/meshcentral$ sudo node node_modules/meshcentral --dbimport meshnedbexport.json
Imported 19 objects(s) from meshnedbexport.json.

I have renamed the nedb files with an _ to make sure they aren't used.
Once I restart with maintenance mode: false
and go to login I get the 'server under maintenance' page so looks to me like its not able to connect to the mysql db to run mescentral??

current config is:
{
  "settings": 
      {
    "maintenanceMode": false,
    "lanonly": true,
    "minify": true,
    "mysql": {
    "host": "localhost",
    "user": "admin",
    "port": 3306,
    "password": "the pw",
    "database": "meshcentral"
                  }
        }
}

**Comment by nzalev** [comment]
The web server does not check if maintenance mode is true/false, it simply checks if it is not null. You need to remove the `maintenanceMode` key entirely.

PS, I designed it such that if the server is unable to connect to MySQL, it will bail out completely and shut down - so if it is serving pages, then the DB is likely not an issue.

**Comment by frosterrj** [comment]
OK.  removed from config, restarted service, web page looks normal on login.
I do see a new row in the events table in mysql with correct timestamp so I think this is solved.
I can successfully remote into my hosts from Meshcentral.

"id","time","domain","action","nodeid","userid","doc"
22,"2022-01-05 10:14:27","",login,,user//meshadmin,"{""ip"": ""192.168.x.x"", ""ids"": [""*"", ""server-users"", ""user//meshadmin""], ""msg"": ""Account login"", ""time"": ""2022-01-05T18:14:26.783Z"", ""etype"": ""user"", ""msgid"": 107, 

Thanks,
R
