### ISSUE TITLE
I can't access from some ip's

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#3405]
hello. I am trying to enter from a site and I get this message. I have already tried from a desktop computer and I get the same thing. is there any ip blocking?
![Screenshot_2022-01-04-14-54-26-368_com android chrome](https://user-images.githubusercontent.com/26174637/148116241-863e8e6d-bb76-4d09-86fd-1dcdf626d7ce.jpg)

**Comment by Ylianst** [comment]
Not sure what is going on. It looks like websocket connections are getting blocked. If you are using a reverse proxy, you need to configure it to allow websockets.

**Comment by mrkacg1** [comment]
![image](https://user-images.githubusercontent.com/26174637/148437154-db5e8ed9-5b9b-46cd-9d1b-602e919dd272.png)
It only happens with a specific network. I can access from other networks without problems.

**Comment by Ylianst** [comment]
If this is still happening, try adding this line to the settings section of the config.json:

```
"cookieIpCheck": "none"
```

**Comment by mrkacg1** [comment]
the problem continues: Cannot connect to web socket, click to reconnect.
