### ISSUE TITLE
Feature request: more detailed device information

### ISSUE THREAD

**Issue by herwig-** [Ylianst/MeshCentral#3409]
It would be really nice to not only see the historic online time of the devices but also the average CPU load, RAM usage, HDD utilisation, Network,. ...
Data like from check-mk-raw ... It would make sense to provide an plugin where data can be written to and this data would be stored on the server like the data of the availability ...
warnings based on e.g. Disk utilisation or with historic data information about % disk left per week - with an estimation about how long the disk wiould take to be full... with warnings, ...
also interesting SMART data of the HDDs - will they fail anytime soon?

**Comment by Ylianst** [comment]
Good requests, indeed more data gathering including SMART would be great.  I do want to mention that for memory, CPU and temperature sensors, you can go in the "Details" tab and hit the small graph icon to see the values in near real-time.

![image](https://user-images.githubusercontent.com/1319013/148323410-1c5ceaa3-d05d-4675-97e9-15d5af791658.png)

This sure if that is what you where looking for with these values, but I did want to mention it.

**Comment by rodrigolzd** [comment]
seems this is related to https://github.com/Ylianst/MeshCentral/issues/83

**Comment by openncomp** [comment]
Are you sure that it is worth loading a lightweight application for remote control of monitoring functions?
To do this, you can use the simplest Zabbix.
