### ISSUE TITLE
Agent not connecting to Meshcentral that behind Nginx Proxy Manager 

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#3414]
Hi Everyone, I'm new to Meshcentral. I had successfully setup Meshcentral and Nginx Proxy Manager and am able to connect to Meshcentral server but the agent is not able to connect to it. Cmd show that the web certificate is loaded. I'm just don't know and have no idea which part is wrong. 

I also had turned on the HTTP to HTTPS automatic setting in my domain. As I mentioned, it works when I type my domain (mydomain.com for example) in the browser, and I can access my meshcentral from outside world and the certificate also looks good. I'm using Cloudflare. Reason using Nginx Proxy Manager because we still have other web server and easier for us to manage.

-10.1.1.10 is my Nginx Proxy Manager 
-10.1.1.5 is my Meshcentral server

This is the meshcentral config.json
  "settings": {
    "cert": "mydomain.com",
    "port": 9005,
    "aliasPort": 9005,
	"AgentPong": 300,
	"TlsOffload": "10.1.1.10"
  },
  "domains": {
    "": {
	  "certUrl": "https://mydomain.com:443/",
      }
    }
  },

This is my Nginx Proxy Manager configuration
![image](https://user-images.githubusercontent.com/95070936/148410863-d5454a7a-e40b-412b-8e30-77215d2c88aa.png)
![image](https://user-images.githubusercontent.com/95070936/148411111-ca5455fc-8afb-4d00-8dae-f6cd9acbd58f.png)
![image](https://user-images.githubusercontent.com/95070936/148411498-1e1373ff-cf31-4906-a5e1-5ab9657acfa6.png)

**Comment by nzalev** [comment]
I see that you're forwarding something to meshcentral on port 5900. Is that meant to be 9005?

**Comment by ONBET** [comment]
> I see that you're forwarding something to meshcentral on port 5900. Is that meant to be 9005?

Yes. It meant to be 9005, sorry the pic is wrong

**Comment by ONBET** [comment]
For this I had set it "certUrl": "https:/10.1.1.10:443/" to point to my Nginx Proxy Manager instead, set it to https://mydomain.com:443/ is wrong I think

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/148490345-545fc18a-aa62-4982-b8ea-12f21d038d1e.png)

**Comment by nzalev** [comment]
You are missing a slash in your cert url. It is of the form `https://`, not a single slash.

`certURL` tells meshcentral to get the certificate from the given URL by establishing a TLS connection. Your meshcentral server is running on port 9005. Is there anything running on port 443? Does it use the same certificate as port 9005? If they are different, you should be doing `https://10.1.1.10:9005`.

**Comment by ONBET** [comment]
Yes I get it work now because of the certURL issue. "certUrl": "https://mydomain.com:443/", is correct but my "aliasPort": 9005 is wrong. aliasPort need to set 443 that my agent acceess my domain from outside. Now everything works but the agent IP is not correct.

I had set x forward in NPM but no luck it not works.



![image](https://user-images.githubusercontent.com/95070936/148492668-05fd19d8-f078-44b6-8674-6dacab7fdbd3.png)

Instead of using code 
# Allows websockets over HTTPS.
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_set_header Host $host;


 I just simply turn the Websockets Support on
![image](https://user-images.githubusercontent.com/95070936/148492689-b05dbaf3-46d3-48a4-9d30-6a4a16f78204.png)

**Comment by nzalev** [comment]
What is the agent IP showing? It is possible that your `X-Forwarded-For` header is not being applied, or the IP address in `TlsOffload` does not match the IP of the connecting interface from the reverse proxy.

**Comment by ONBET** [comment]
The agent IP is my Nginx Proxy Manager IP. If I put "tlsoffload" : "my Nginx Proxy Manager IP" , then my page straight away
![image](https://user-images.githubusercontent.com/95070936/148496845-eb73c0fd-ec6e-4c00-af07-5e02bb0d0e7c.png)

**Comment by ONBET** [comment]
The X-Forwarded-For, am I set it properly in Nginx Proxy Manager?

**Comment by ONBET** [comment]
If I set correctly, the agent IP address that I'm getting will be their public internet IP or their computer IP?

**Comment by nzalev** [comment]
The IP address displayed in the Address column of My Devices is the public IP from which the request came.

Network interfaces and their assigned IPs can be found by clicking the device, under the Details tab.

**Comment by ONBET** [comment]
Ok. I think the IP address is not important because once I set WAN only mode, it disappear. So whenever I need to check the PC ip address I just need to check in their NIC. Thank you @nzalev for answering my question.
