### ISSUE TITLE
No notification when an IP is blocked

### ISSUE THREAD

**Issue by elpibedeoro** [Ylianst/MeshCentral#3419]
Hi Ylian,

First of all, Happy New Year to you and all the community.

My fist issue of the year: a known IP has been blocked because of bad password. That's ok but I was expected to have a notification in MC2 v.0.9.65.

In the Event's tab, I can find the "Invalid user login attempt".
In the Console's tab, when I type "badlogins" it show me like in the picture as below:

![badlogin](https://user-images.githubusercontent.com/76168733/148527725-a23a25a5-967f-4dad-abe3-67ee6c32e7f5.png)

Is it normal that I don't get any notification and that I cannot find any blocked IP address in the console ?

Thank you!

**Comment by Ylianst** [comment]
Weird, you should see the blocked IP address when typing the "badlogins" command, I need to check this. I am working on testing the new MeshAgent, so holding new server fixes until that is done and released.

**Comment by si458** [comment]
you get events listed in 'My Events' for the user with the failed attempts
OR
an admin can see all the 'failed logins' in the 'My Events' tab

also the `badlogins` command in the 'My Server' console tab, not shows the IP address of the failed attempts (or rather the /24 ip range)
```
> badlogins
Max is 10 bad login(s) in 10 minute(s).
79.77.XXX.* - 1 record
```
