### ISSUE TITLE
hide not working with logintoken

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#342]
example
https://10.0.45.214/?login=LOGINTOKEN=&node=NODE&viewmode=12&hide=31
is showing the entire page instead of just terminal:
![logintoken](https://user-images.githubusercontent.com/7434746/60763820-dd1c3b00-a030-11e9-9e61-81002790fbb1.PNG)

same thing using username/password instead of login token is working however:

https://10.0.45.214/?user=USERNAME&pass=PASSWORD&node=NODE&viewmode=12&hide=31

![userpass](https://user-images.githubusercontent.com/7434746/60763826-eefdde00-a030-11e9-90a2-364d125b2073.PNG)

**Comment by Ylianst** [comment]
Your right, the new CSS broke this feature... looking at it now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.7-i with a fix for this. Let me know if it works for you.

![MC2-Embed](https://user-images.githubusercontent.com/1319013/60773727-67f74700-a0be-11e9-9286-d85fb957147a.png)

**Comment by wh1te909** [comment]
working great! thanks!
