### ISSUE TITLE
release note

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3420]
Hello,
Are there release note files indicating what new features are available and the bugs fixed in each MeshCentral version?
Thanks

**Comment by rodrigolzd** [comment]
So far the best way to see what has changed is this link:

https://github.com/Ylianst/MeshCentral/commits/master

**Comment by vithusel** [comment]
Release notes can only really be provided if for every release of the application it was uploaded to github as a release. 
Although it might be possible to make a scraper that could automatically add all the commit titles between releases as they are all named Version 0.*.** 

@Ylianst would I be ok to submit a PR to add this to the My Server page. I can potentially get it to check the server version and latest version and provide a list of commits between them.

**Comment by Ylianst** [comment]
I would certainly accept such a PR. Best to start by generating a different web page for release notes. Would be interesting.

**Comment by JSuenram** [comment]
@pascal-chag 
If your question is answered, pls close.
Thank you!

**Comment by si458** [comment]
with every new release the is notes to all the commits that was added!
