### ISSUE TITLE
When using docker, agent does not connect to server.

### ISSUE THREAD

**Issue by frakman1** [Ylianst/MeshCentral#3423]
I am using the docker-compose/Dockerfiles in this project.
I just want to run meshcentral server locally with no internet accessible hostname and no reverse proxy configs.
So I used my local LAN IP address as the hostname in `docker-composeyml`. (I also used IP:8086 with no luck)
```
- HOSTNAME=192.168.86.145     #your hostname
```
I built the image locally using:
```
docker build -t meshcentral .
```

and therefore used this in the docker-compose.yml:
```
image: meshcentral:latest
```

The image builds fine, `docker-compose up` works and I am able to access the server on my local IP address at `https://192.168.86.145:8086`

The problem is that when I select the option to install an agent on Linux, the script does not include the port number 8086 in the template:
![image](https://user-images.githubusercontent.com/5826484/148627602-7d1bc4a2-d842-47e7-adfb-afff4ff00369.png)

So when I tweaked it to include the port number and changed the `meshinstall.sh` script to add `-k` to all the curl commands (because of untrusted certificate errors), I finally got the `meshagent` to install on my Pi but it never showed up as a device on the meshcentral server. I wish there was a way for me to troubleshoot what the agent is doing and what it's trying to connect to and what errors (if any) it is seeing.

`meshagent` appears to be running and I don't see errors in `journalctl` or `syslog` or `systemctl status`

Is there a way to get meshcentral to run locally this way via docker without a FQDN/hostname/reverse-proxy setup?

**Comment by xpufx** [comment]
I am using docker too and installing the agent on Windows. I set the https port on the docker container so that it would actually be same as the exposed port - just in case. I can see the correct wss url inside MeshAgent.msh file and also on the agent gui. I hit connect, no errors. But host never shows up on the mesh server web gui.

**Comment by si458** [comment]
you are possibly using an old dockerfile from a community repo and not one we provided
please look at the offical new docker readme https://github.com/Ylianst/MeshCentral/blob/master/docker/readme.md
