### ISSUE TITLE
ERROR: Unable to write to mesherrors.txt.

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#343]
Hi
On my server status (# systemctl status  meshcentral.service) I get this error.
"ERROR: Unable to write to mesherrors.txt"
In my install folder I don't have mesherrors.txt file.
I use Increased Security Installation from p 6.8 manual.

**Comment by Ylianst** [comment]
Thanks for reporting this, I will need to add a way to specify an alternative path to "mesherror.txt" so that MeshCentral can write it in a place it has permission to do so. One workaround would be to create a "mesherror.txt" in the "meshcentral-data" folder and change the permissions to "666" so to grant write access to that file.

**Comment by motapek** [comment]
Hi
I created a mesherror.txt file in meshcentral-data folder, change permission to 666 and user and group to meshcentral.
/opt/meshcentral/meshcentral-data# ls -all
dr-xr-xr-- 4 meshcentral meshcentral 4096 Jul  8 23:01 .
dr-xr-xr-- 5 meshcentral meshcentral 4096 Jul  8 09:16 ..
-r-xr-xr-- 1 meshcentral meshcentral 2498 Apr 24 22:42 agentserver-cert-private.key
-r-xr-xr-- 1 meshcentral meshcentral 1534 Apr 24 22:42 agentserver-cert-public.crt
-r-xr-xr-- 1 meshcentral meshcentral  860 Apr 26 00:32 config.json
-r-xr-xr-- 1 meshcentral meshcentral 3301 Apr 24 23:00 config.json_old
dr-xr-xr-- 7 meshcentral meshcentral 4096 Apr 24 23:19 letsencrypt
dr-xr-xr-- 2 meshcentral meshcentral 4096 Apr 26 02:14 mail-templates
-r-xr-xr-- 1 meshcentral meshcentral  600 Apr 24 23:05 meshcentral-events.db
-r-xr-xr-- 1 meshcentral meshcentral  582 Apr 24 23:05 meshcentral-power.db
-r-xr-xr-- 1 meshcentral meshcentral    0 Apr 24 23:03 meshcentral-smbios.db
-r-xr-xr-- 1 meshcentral meshcentral  142 Apr 24 23:05 meshcentral-stats.db
-r-xr-xr-- 1 meshcentral meshcentral  865 Apr 24 23:05 meshcentral.db
-rw-rw-rw- 1 meshcentral meshcentral    0 Jul  8 23:01 mesherror.txt

After restart mesh service status is this same.
"ERROR: Unable to write to mesherrors.txt."

**Comment by motapek** [comment]
I found.
That was bad filename.
That should be mesherrors.txt - not mesherror.txt ("s" on the end)
Now is is OK.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.7-k with a new "MeshErrorLogPath" option in "settings" of config.json. You can now do:

`"MeshErrorLogPath": "c:\\tmp",`

It will put the "mesherrors.txt" in that path. However, doing it by changing the mode to 666 is also perfectly good.
