### ISSUE TITLE
esxi support

### ISSUE THREAD

**Issue by leleb** [Ylianst/MeshCentral#3430]
Hi, I have read ( here: https://meshcentral2.rssing.com/chan-8632712/all_p4.html#c8632712a66?zx=813 )
that agent could be installed in esxi host. That would be a great feature.
Tried all x86-64 binary agents but none worked.
I have vmware esxi 6.7.0 update 3. 
Is it really possible? Please some tips. Thanks

**Comment by Ylianst** [comment]
Should work, ESXI runs a very limited Linux as it's host. This said, I have not tried it recently. What error message do you get?

**Comment by leleb** [comment]
downloaded binary agents:
ID
6	Linux x86-64	
18	Linux Poky x86-64
20	Linux x86-64 NoKVM
30	FreeBSD x86-64
37	OpenBSD x86-64

done chmod and the .msh is there. Here it is the shell output:

[root@EGOESX:~] chmod 755 EgonetAgent6
[root@EGOESX:~] chmod 755 EgonetAgent18
[root@EGOESX:~] chmod 755 EgonetAgent20
[root@EGOESX:~] chmod 755 EgonetAgent30
[root@EGOESX:~] chmod 755 EgonetAgent37
[root@EGOESX:~] ls *.msh
meshagent.msh
[root@EGOESX:~] ./EgonetAgent6

[2022-01-10 03:40:12 PM] [] microstack/ILibParsers.c:2818 (0,0) ** Microstack Thread STUCK **
./EgonetAgent6() [0x4a075a]
./EgonetAgent6() [0x4cdcb3]
/lib64/libc.so.6(__libc_start_main+0xed) [0x27734b097d]
./EgonetAgent6() [0x40dbb1]
[root@EGOESX:~] ./EgonetAgent18
-sh: ./EgonetAgent18: not found
[root@EGOESX:~] ./EgonetAgent20

[2022-01-10 03:40:35 PM] [] microstack/ILibParsers.c:2818 (0,0) ** Microstack Thread STUCK **
./EgonetAgent20() [0x49f4aa]
./EgonetAgent20() [0x4c72a3]
/lib64/libc.so.6(__libc_start_main+0xed) [0x82cc26097d]
./EgonetAgent20() [0x40c901]
[root@EGOESX:~] ./EgonetAgent30
-sh: ./EgonetAgent30: not found
[root@EGOESX:~] ./EgonetAgent37
-sh: ./EgonetAgent37: not found
[root@EGOESX:~]

**Comment by krayon007** [comment]
I setup an ESXi environment and reproduced the issue. It turns out that ESXi is not Linux based, so the binaries are not compatible. I'll have to try to build it specifically for ESXi. It might take some time, as there seems to be very little documentation on the ESXi dev environment

**Comment by Ylianst** [comment]
Arg. Looks like a new agent built will be required.

**Comment by vithusel** [comment]
I thought of a really good use case for Meshcentral agent for ESXI. 
Terminal is the obvious one. But Meshcentral Router would mean no need to use VPN's to be able to access the WebUI of the server. Could be a lot more secure (unless you have setup a very secure VPN into your network). I've currently got about 7 ESXI servers on my network and would love to be able to decommission my VPN server to make the entire network a hell of a lot more secure.

**Comment by silversword411** [comment]
> But Meshcentral Router would mean no need to use VPN

Welcome to the world of routing :) 

You know you can do the meshcentral routing thing with just SSHv2 right? Then the next step is no-firewall configuration port forwarding/pinholing. You're on the path to SDN (Software Defined Network)...aka non-public auto-initializing VPNs aka Zerotier, nebula etc.

**Comment by vithusel** [comment]
> > But Meshcentral Router would mean no need to use VPN
> 
> Welcome to the world of routing :) 
> 
> You know you can do the meshcentral routing thing with just SSHv2 right? Then the next step is no-firewall configuration port forwarding/pinholing. You're on the path to SDN (Software Defined Network)...aka non-public auto-initializing VPNs aka Zerotier, nebula etc. 

Ohh. I shall have a look into this! Thank you!

**Comment by si458** [comment]
closing as stale
