### ISSUE TITLE
URL Share Desktop Share: Security Request

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#3431]
Man, you guys just keep making this better and better. I LOVE this added feature. Being able to allow a vendor temporary access to a system to troubleshoot something via a URL is really great!

One thing I thought of though that was a bit scary. The default time/expiration, at least on our instance is **Unlimited**. Is there a way in the config to either disable Unlimited, or set the default options for this feature?

![image](https://user-images.githubusercontent.com/65490814/148702402-fea5b60c-b204-4529-bafa-8652ea12ff86.png)

**Comment by Ylianst** [comment]
Ok, just added it, will be in MeshCentral v0.9.67. Put this in the domain section of the config.json:

```
      "GuestDeviceSharing": {
        "maxSessionTime": 30
      }
```

This will limit how long a remote desktop session to the guest can be in minutes.

**Comment by matt-cylanda** [comment]
Hmm...

I went ahead and made the change, I put in 1440 for 24 hours as the default. The expiration now shows up as 1 minute for the default... which is fine, the main thing I wanted to avoid was accidental "Unlimited" sharing

**Comment by Ylianst** [comment]
Yes, the max session time set to 1440 will remove all options that are more than 24h long. Is that not what you wanted? You want something else to select the default value?

**Comment by openncomp** [comment]
Now I also tried to set up a temporary link, set 30 minutes and also got 1 minute by default, but I couldn't choose more than 30 minutes.
It seems to me that the author of the issue meant something completely different.
For example, we set 60 minutes in the settings, and when creating a temporary link, the default time is set to 60 minutes, and not as usual - infinite. But from the list we could choose other options, including infinitely.
This behavior would be more logical for me, although limiting the maximum time is also a great idea!

**Comment by matt-cylanda** [comment]
> Now I also tried to set up a temporary link, set 30 minutes and also got 1 minute by default, but I couldn't choose more than 30 minutes. It seems to me that the author of the issue meant something completely different. For example, we set 60 minutes in the settings, and when creating a temporary link, the default time is set to 60 minutes, and not as usual - infinite. But from the list we could choose other options, including infinitely. This behavior would be more logical for me, although limiting the maximum time is also a great idea!

Ya, that's basically what I was looking for. Mostly didn't want 'infinite' as default, but also wanted to be able to choose other values and have maybe 4 hours set as the default.
