### ISSUE TITLE
service meshcentral  not start  in Centos 8

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3433]
Hi !!! Help me 

Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-10 21:36:21 +10; 5s ago
  Process: 25540 ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral (code=exited, status=203/EXEC)
 Main PID: 25540 (code=exited, status=203/EXEC)

янв 10 21:36:21 localhost.localdomain systemd[1]: meshcentral.service: Main process exited, code=exited, status=203/EXEC
янв 10 21:36:21 localhost.localdomain systemd[1]: meshcentral.service: Failed with result 'exit-code'.
[root@localhost system]#

**Comment by nzalev** [comment]
Try running meshcentral interactively.
```
cd /opt/meshcentral
node node_modules/meshcentral
```

The result should contain the reason it fails to start.

**Comment by gosteras** [comment]
> node node_modules/meshcentral

this ok.    Service  not worked

**Comment by nzalev** [comment]
You can change `ExecStart` from 
```/usr/bin/node /opt/meshcentral/node_modules/meshcentral```
to 
```/usr/bin/node /opt/meshcentral/node_modules/meshcentral >> /opt/meshcentral/servicelog.txt 2>&1```

**Comment by gosteras** [comment]
no create file

**Comment by nzalev** [comment]
It probably isn't starting node then. Can you give the output of running `which node`?

**Comment by gosteras** [comment]
> It probably isn't starting node then. Can you give the output of running `which node`?

 Oh  :)      **/root/.nvm/versions/node/v16.13.1/bin/node**

Thanks

**Comment by southeasterntech** [comment]
I'm having this same problem it seems... the service doesn't work, but it's fine if we run manually... what was the fix?
Shane

**Comment by nzalev** [comment]
@southeasterntech 
In this case, the systemd unit file contained
```
ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral
```
but the node executable was located at
```
/root/.nvm/versions/node/v16.13.1/bin/node
```

You can find the location of your node executable by running `which node`. The systemd unit file is generally located at `/etc/systemd/system/meshcentral.service`. Make sure your executable path matches the actual file locations.
