### ISSUE TITLE
(Question) Meshcentral agent without proxy

### ISSUE THREAD

**Issue by DevOps-88** [Ylianst/MeshCentral#3434]
Hello

Is it possible to configure the meshcentral agent so that it does not use the proxy server settings that have been configured in Windows? I mean system settings.
Can the agent itself bypass the proxy server and connect directly to the meshcentral server?

Regards.

**Comment by Ylianst** [comment]
The MeshAgent will try to connect both with and without the proxy. It will try one and try the other. So, if you have a proxy but it should not be used, the agent should still connect. Let me know if that works.

**Comment by DevOps-88** [comment]
Thank you for the quick reply.

I understand, but let's assume that in windows I have to leave the proxy server for other uses and I would like to force the agent to connect without using the proxy server. If it is possible ?

**Comment by krayon007** [comment]
One way to do that would be to edit the msh file, by adding:
`ignoreProxyFile=1`
After restarting the agent, this will cause it to ignore proxy settings
The agent should be able connect with or without the proxy on its own, so it shouldn't be necessary. But this is how you would force it.

**Comment by DevOps-88** [comment]
Thanks for the hint, I added this parameter to the indicated file and it worked as expected.
The question is whether it is possible to configure the agent before installation so that by default this parameter "ignoreProxyFile=1" was added to the .msh file?

**Comment by PrplHaz4** [comment]
> Thanks for the hint, I added this parameter to the indicated file and it worked as expected. The question is whether it is possible to configure the agent before installation so that by default this parameter "ignoreProxyFile=1" was added to the .msh file?

I beleive you can set this in the AgentConfig section of config.json to have it propagate down to the .msh:

```json
 "domains": {
    "": {
      ...
      "agentConfig": [
        "ignoreProxyFile=1"
      ]
    }
  },
```

**Comment by Ylianst** [comment]
@PrplHaz4 is 100% correct :)

**Comment by DevOps-88** [comment]
Thanks for your help, I tested the settings and it worked as it should.

I have one more thread similar to this only for Meshcentral Asisstant. Does this application also check the connection itself through a proxy server or without a proxy server?
Because after my tests it appears that this is not the case and if I had a defined system proxy in the system, the application tried to connect through this proxy and the assistant did not report to me on the server.

I don't know, maybe this is a topic on a separate topic?
