### ISSUE TITLE
Admin mode for Assistant ?

### ISSUE THREAD

**Issue by CSW2000** [Ylianst/MeshCentral#3435]
Is it possible to add a new wizard ( Assistant ) with administrator rights?
Or a switchable admin mode ?
Since it seems to be reserved for the agent and thus a constant connection and unnecessary data traffic arises. 
The agent may be great for Sever but not for the standard user 😐   

Thanks for the Meshcentral Tool

**Comment by Ylianst** [comment]
Hi. I am not sure what the request is. Are you talking about having MeshCentral running as administrator on the remote machine?

Note that MeshCentral Assistant is code signed and so, in order for this software not to be abused, it must remain user initiated or have user consent always enabled.

**Comment by CSW2000** [comment]
Hello Thanks for the reply
My question was if there is a way if an assistant is used by the customer instead of the agent, 
That the customer does not always have to confirm the admin queries Windows ( execution prevention ) always , 
as well as to use the terminal or power shell as an admin, as is the case with the installed agent. 
But since I maintain almost no servers but only end users, the agent installation is usually not an option for me.
I want the customer not always online, and still have the full rights at the meeting.
 
I myself host the Meshcentral 2 server on a Raspberry4B 8GB with MariaDB. 
 
Greetings from Bavaria , Germany

**Comment by Ylianst** [comment]
Because MeshCentral Assistant is code signed, it must have users confirm remote management. This is so it can't be abused and rejected by AntiVirus vendors. So, no, MeshCentral Assistant user consent will not be removed.

However, you can use the MeshAgent in interactive mode. Select "Interactive only" when you download the agent and let me know if that works for you.

![image](https://user-images.githubusercontent.com/1319013/148845485-af4c7a9c-98c8-4d56-a8ef-d72aa3ee0fb6.png)

**Comment by CSW2000** [comment]
Thank you 
I am already aware of the Interactive Agent.
Only for consumer support, the assistant is the better solution, as it is graphically better for the customer and I can provide the tool with its own desktop icon.
Too bad I thought you can equip an assistant with admin right.

![ws](https://user-images.githubusercontent.com/56474379/148932123-29daa1a2-77e0-42b3-ad52-9d15a84a0d08.PNG)

With the agent, however, there is also the problem that the software is offered for installation without a signature. However, my server has a valid web address and a certificate.
This is not very trustworthy with the customer. 
 
   This wizard with admin rights or switchable admin rights would be supper
 
![asist](https://user-images.githubusercontent.com/56474379/148932160-6475ae26-7f3d-4655-9ab7-8355a8dc9fba.PNG)

I would like to support you with a donation.

Greetings from Bavaria / Germany

**Comment by Ylianst** [comment]
No donations needed, but thank you.

This is a problem with remote management agents. If they are too powerful and I sign it, I get in trouble because people don't use the agent for good. So, I can only sign a less powerful Assistant and required user consent.

If you like, you can get your own code signing certificate and sign the agent in "node_modules/meshcentral/agents", look for:

```
MeshService-signed.exe
MeshService64-signed.exe
```

You need to re-sign them with your own certificate.

For the agent, we got a better user consent dialog and hopefully the next agent, we want to make a better installation dialog box with company image on it. It will look a lot better than the current one.

**Comment by CSW2000** [comment]
Halo thanks for the support 
Unfortunately, I am not a programmer and implementing all this is very hard for me 
I downloaded the EXE files as indicated above from my Linux Raspberry on which my domain is also linked to a folder of my Windows PC.
I found the following post in your Github : https://github.com/Ylianst/MeshCentral/issues/1622
It says how to do this on a Windows. 
With this command line: 

"C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool" sign /sha1 fc7dbce2b19c0a62bba32ca246fa22260bb86333 /fd sha384 /du "https://meshcommander.com" /d "MeshCentral Remote Management Agent." /t "http://timestamp.comodoca.com/authenticode" "MeshService-signed.exe"

The sign Tool I have installed on Windows 

But how do I do this in Linux on the Raspbery?
And where can I get the sha1 code?
There is a manual or Youtube video where you can go into more detail about the necessary parameters. 
<img width="778" alt="sign" src="https://user-images.githubusercontent.com/56474379/149141100-0f8c66ba-c5a4-495d-ac49-05a93fb56d30.PNG">

Greetings from Bavaria / Germany
Roland W.

**Comment by Ylianst** [comment]
You can only sign Windows executables on a Windows device. Once signed, you can copy it back to your Raspberry Pi server in the `node_modules/meshcentral/agents` folder and that will work. I will note that you need a certificate capable of code signing. You can't use a TLS certificate, even one from Let's Encript will not work.

Once signed, your users will no longer get the warning when installing the agent on Windows.

**Comment by CSW2000** [comment]
Hello
Thanks for the information 
But where can I get the TLS certificates?  Is my certificate that I have certified the MeshCentral server from my provider? 
Maybe you can show this in more detail in your video on January 19th, how to certify such an agent and what is needed for everything.
I can't go on like that now.
Please close
Best regards - Roland W.

**Comment by Ylianst** [comment]
So, there are two different types of certificate, TLS certificate for your web server, you can get that free from Let's Encrypt, [I have a video on this here](https://www.youtube.com/watch?v=a4F1ayu7XWo). For code signing certificate, this is more complicated, you see to find a provider online and this is not free.

Ok, I will close, thank you.

**Comment by CSW2000** [comment]
Thank You  My sert is from a Provider in DE
