### ISSUE TITLE
Event Tab - Log session disconnections by administrators

### ISSUE THREAD

**Issue by Otsegox** [Ylianst/MeshCentral#3437]
The ability to kick/disconnect someone from a station is great. It can be used for all sorts of purposes.

I noticed today, that the kick is not logged on the events tab for either the user that was kicked, or the station.  I just checked, and the kicker also has no record of that event.

I don't currently have an issue with this, but if you get a bad actor on your team, they could really reek havoc on the team. 

Could this get logged to the events tab on the station?

**Comment by Ylianst** [comment]
Good idea, updated the title that was not great.

**Comment by Ylianst** [comment]
Just added the new log entries, will be in MeshCentral v0.9.67.

![MC2-SessionDisconnectLog](https://user-images.githubusercontent.com/1319013/148866685-bffb9316-192b-4762-af5b-6ddcc933ef77.png)

**Comment by Otsegox** [comment]
Yup! Just installed it on my test box, and tried it. Looks great!

Thank you!
