### ISSUE TITLE
TLS Not Working (However Lets Encrypt shows OK)

### ISSUE THREAD

**Issue by matthiscock** [Ylianst/MeshCentral#3441]
![chrome_d8257wxKEK](https://user-images.githubusercontent.com/5795004/148906322-a8f81fe2-b45a-4de1-9f42-ec4bf2d08c41.png)

Slightly strange one which I can see a post or comment about.
I have a fully debugged domain (checked with LE debug)
Setup Mesh Central in a normal way, on a windows box.

As you can see from the screenshot, LE is showing all ok, however the browser (tried from multi computers) is showing insecure (aka the certificate is not being used)

Could you point me in the right direction?

Thanks

**Comment by Otsegox** [comment]
Are you using the FWDN to access the webpage?  eg  mesh.yourdomain.com ?

**Comment by matthiscock** [comment]
Yes, its in the screenshot

help.senses.co.uk

Lets Encrypt Debug also comes back on that domain.

**Comment by Ylianst** [comment]
@nzalev is correct, this is the fix:

```
  "letsencrypt": {
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": true                                   <----------------------
  }
```

**Comment by matthiscock** [comment]
Thanks you

Changed to true
Restarted mesh central

Still coming up insecure

Is there an additional wait period?

Apologies if i missed this in the documentation!!!

**Comment by matthiscock** [comment]
Yes, it just took a while.
Thank you for your help

Happy to contrinute to docs to help others, but its in PDF so not sure i can!

**Comment by nzalev** [comment]
I think most likely, that's just chrome's cache. Chrome caches certificates as well, so you will not always see the updated certificate (sometimes I've found even in incognito). Usually, I will check using `openssl s_client`.

**Comment by arduin0guru** [comment]
I had the same problem . Even after changing to ""production": true " , no go. 
The only way it started working was by adding the following line to "letsencrypt" 
"rsaKeySize": 3072,
Was giving error after changing "production": true " I was getting error "Invalid origin in HTTP request, click to reconnect."  after login . Wasted 2 days to find out a small glitch!!!!!!!!
Good Luck
