### ISSUE TITLE
Agents access from Internet

### ISSUE THREAD

**Issue by capitangiaco** [Ylianst/MeshCentral#3442]
Hi all

I separated the AgentPort from the console Port, to block the access to the console from the Internet.

```
    "port": 443,
    "AgentPort": 14444,
    "AgentAliasPort": 14444,
```

In the Firewall I redirect the port 443 (just for testing) and 14444, but Meshcentral respond only on the 443 (ERR_CONNECTION_RESET in the browser)
(all is working in LAN, I can connect to the https://console and agents can connect via the 14444 port)

**Comment by Ylianst** [comment]
Hi. First, you don't need to specify `AgentAliasPort` unless it's a different port from the `AgentPort`. Should not do anything in your case, but not needed.

You can use a browser to navigate to `https://yourserver:14444`. You will get a warning of an invalid TLS cert, but that is ok. Passed the warning, you should get a white page. If that works internally, try again externally. If it does not work, there is a problem with your port mapping.

Also, your going to have to put your server in WAN or Hybrid mode with a `cert` entry in the config.json. If not, your agents will multicast on the local network to find the server, that will not work outside your network. [I have a video on this here](https://www.youtube.com/watch?v=gx5Fh3pQOns).
