### ISSUE TITLE
Missing translation in MeshAgent user consent

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3443]
at asking permissions to remote acces the computer

![Screenshot_15](https://user-images.githubusercontent.com/58996467/149012087-0898f8b2-25c6-4be9-9784-c3866edc5431.jpg)

**Comment by Ylianst** [comment]
Good catch!

**Comment by Ylianst** [comment]
Added the new strings in the agent .msh file, but agent use of the strings will require a Windows agent update.

**Comment by krayon007** [comment]
We're working on a better solution, as the .msh solution doesn't work for already installed agents. The solution shouldn't require an agent update, just a server update.

**Comment by petervanv** [comment]
can't wait, but as i said, low priority

**Comment by Ylianst** [comment]
It's being worked on. Added a system to provide translation strings to the agent, something we did not have.

**Comment by si458** [comment]
in theory this has been fixed now 👍
