### ISSUE TITLE
Devices still very slow to reconnect after server reboot

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#345]
I just updated my server to 0.3.7-I and also restarted it as there were also some Windows Updates (Server 2019).  I thought this had been resolved a few updates ago- but I'm still seeing the issue where most devices are very slow to reconnect to the server after a reboot.  So far the server has been up and running for 10 minutes and only 16 devices out of nearly 400 have reconnected.  I see one or two pop up every so often.  
Is there anything I need to change in the config that was part of the previous update that was meant to resolve this?

**Comment by PathfinderNetworks** [comment]
Seems like once it crossed the 15 minute mark the majority of them all started connecting.

**Comment by Ylianst** [comment]
How long was the server down before it was turned back on? A typical update is very fast for me (15 seconds). Also, is there anything in front of the server that would rate limit the number of new TCP connections?

**Comment by PathfinderNetworks** [comment]
The server was down for less than 2 minutes (probably closer to about 1 minute as it's a VM that is running on a high power host with SSD storage).  I'm running Untangle as the router/firewall but I don't believe it limits new incoming TCP connections.  I normally don't reboot the server itself unless there are Windows Updates involved.  If I just do a MeshCentral update without rebooting the server then all the devices connect immediately after MeshCentral restarts.

**Comment by Ylianst** [comment]
I did see this behavior on one of my servers. Could it be that when I shutdown the server for an update, some agents don't get the TCP close message and think they still are connected until the TCP timeout? Another option is that the retry timer is not reset to zero once the agent connects. I need to test some theories.

**Comment by dinger1986** [comment]
@si458 dont think this is an issue anymore plus for a very old version
