### ISSUE TITLE
File editor does not support UTF-8

### ISSUE THREAD

**Issue by sheshko-as** [Ylianst/MeshCentral#3450]
Hi! I use MeshCentral with Russian language. When editing files in which there is a Russian language, it shows scribbles. Editor doesn't support UTF-8? Tried with multiple systems: Linux, macOS, Windows
![Снимок](https://user-images.githubusercontent.com/97667637/149307397-67a53be9-b68d-458c-a1a1-b722b0ff669b.JPG)

**Comment by SEsternO** [comment]
I can confirm, exactly the same behavior for me in text editor using russian localization on the server and agents. Server version 0.9.68, tried with Win7/10/srv2012 and Ubuntu 20.04 agents. 
![изображение](https://user-images.githubusercontent.com/8999994/149430705-2c70e323-f875-46d6-80e3-1756f3f98776.png)

**Comment by Ylianst** [comment]
Correct, I see the same problem. Looking into it now.

**Comment by Ylianst** [comment]
Got a fix for this, will be in MeshCentral v0.9.69.

![image](https://user-images.githubusercontent.com/1319013/149441632-d91e33d8-6456-4e5a-b44f-ff794ba3c388.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.70 is out with this fix included, let me know if it works for you.

**Comment by sheshko-as** [comment]
Works! Fine! good luck with your project, it's great.
