### ISSUE TITLE
File Editor Deletes the file on Linux Server when saving on 0.9.68

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#3451]
I now have seen two cases on two separate Linux servers, running version 0.9.68 where upon saving a file in the text editor the file simply vanishes.  It's no longer present in terminal, and it can no longer be seen in the file editor.

One of the servers was Ubuntu server 18.04.  The other was also a Linux server, but unsure on the version just now.

Thanks!

**Comment by Ylianst** [comment]
Your right. I need to work on this!

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.9.69.

**Comment by Ylianst** [comment]
MeshCentral v0.9.69 is out with this fix.

**Comment by Ylianst** [comment]
MeshCentral v0.9.70 is out with this fix included, let me know if it works for you.

**Comment by openncomp** [comment]
I also encountered this problem in version 0.9.68.
After updating to 0.9.71, the problem disappeared, files are edited and not deleted when saving, thank you!

**Comment by southeasterntech** [comment]
I can confirm this is fixed!  Thanks all!
