### ISSUE TITLE
RDP Not Working

### ISSUE THREAD

**Issue by matthiscock** [Ylianst/MeshCentral#3453]
Ive been getting up to speed with MeshCentral 2

ITs installed on a Win Computer, on a FQDN inc SSL.

On another computer, ive got Mesh Router installed, logged in. All is well.
Click righting on a agent, remote desktop option works fine, just like it does on the web gui of mesh central.

However when trying to setup a RDP it hangs on 'Configuring Remote Connection'

Opening mesh router with the debug flag, give me this log.
Looks like the connect was open for 3 seconds and then closed.

Can anyone point me in a direction?
```

13:33:PM.3700: WebSocket: WebSocketClient-SEND-Binary-Len:19
13:33:PM.3730: WebSocket: Websocket got string data, len = 323
ServerData-{"action":"event","event":{"etype":"relay","action":"relaylog","domain":"","userid":"user//matt","username":"matt","msgid":13,"msgArgs":["5257419226804847","192.168.0.1","146.200.65.15"],"msg":"Started relay session "5257419226804847" from 192.168.0.1 to 146.200.65.15","protocol":null,"time":"2022-01-12T13:33:30.986Z"}}
13:33:PM.4189: WebSocket: Websocket got string data, len = 232
ServerData-{"action":"event","event":{"etype":"node","action":"devicesessions","nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","domain":"","sessions":{"kvm":{"user//matt":1},"tcp":{"user//matt":1}},"nolog":1}}
13:33:PM.9568: WebSocket: Websocket got string data, len = 444
ServerData-{"action":"event","event":{"etype":"relay","action":"relaylog","domain":"","userid":"user//matt","username":"matt","msgid":11,"msgArgs":["23wxftdys9c","192.168.0.1","146.200.65.15",29],"msg":"Ended desktop session "23wxftdys9c" from 192.168.0.1 to 146.200.65.15, 29 second(s)","protocol":2,"nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","bytesin":182732,"bytesout":179750,"time":"2022-01-12T13:33:33.571Z"}}
13:33:PM.9895: WebSocket: Websocket got string data, len = 209
ServerData-{"action":"event","event":{"etype":"node","action":"devicesessions","nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","domain":"","sessions":{"tcp":{"user//matt":1}},"nolog":1}}
13:33:PM.8492: WebSocket: Websocket got string data, len = 394
ServerData-{"action":"event","event":{"etype":"relay","action":"relaylog","domain":"","userid":"user//matt","username":"matt","msgid":15,"msgArgs":["h1y9mwn9i3g","192.168.0.1","146.200.65.15"],"msg":"Started desktop session "h1y9mwn9i3g" from 192.168.0.1 to 146.200.65.15","protocol":2,"nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","time":"2022-01-12T13:33:34.465Z"}}
13:33:PM.8863: WebSocket: Websocket got string data, len = 232
ServerData-{"action":"event","event":{"etype":"node","action":"devicesessions","nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","domain":"","sessions":{"tcp":{"user//matt":1},"kvm":{"user//matt":1}},"nolog":1}}
13:33:PM.9565: WebSocket: Websocket got string data, len = 401
ServerData-{"action":"event","event":{"etype":"node","action":"agentlog","nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","domain":"","msg":"Started remote desktop without notification (192.168.0.1)","msgid":36,"remoteaddr":"192.168.0.1","userid":"user//matt","username":"matt","sessionid":"user//matt/6544031773e314a92da50492fa36faf33f38f1fe","time":"2022-01-12T13:33:34.573Z"}}
13:33:PM.8448: WebSocket: Websocket got string data, len = 440
ServerData-{"action":"event","event":{"etype":"relay","action":"relaylog","domain":"","userid":"user//matt","username":"matt","msgid":11,"msgArgs":["h1y9mwn9i3g","192.168.0.1","146.200.65.15",3],"msg":"Ended desktop session "h1y9mwn9i3g" from 192.168.0.1 to 146.200.65.15, 3 second(s)","protocol":2,"nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","bytesin":59899,"bytesout":57661,"time":"2022-01-12T13:33:38.459Z"}}
13:33:PM.8991: WebSocket: Websocket got string data, len = 209
ServerData-{"action":"event","event":{"etype":"node","action":"devicesessions","nodeid":"node//nt$yvFmmF@BtiClI8s4RXzsNIMomtnhzXZZiZGWe4OCqytuf5zW4w5r9d4VjNSRi","domain":"","sessions":{"tcp":{"user//matt":1}},"nolog":1}}
```

**Comment by Ylianst** [comment]
It's not clear from your question, but if you are using the web based RDP client that is included in MeshCentral, it does not support the latest RDP authentication system so you have to turn on the legacy system on the remote computer.

I use [node-rdpjs-2](https://www.npmjs.com/package/node-rdpjs-2) for the RDP web client and it's not been updated in 2 years and does not support TLS. At some point, I may look at adding that in.

Let me know if that was the issue.

**Comment by matthiscock** [comment]
Hi Yilanst

Thanks for your reply

Perhaps I was not clear, apologies for that
So ive done a step by step screengrab which will hopefully explain better the issue im hacing....


![4bEU9oYWEN](https://user-images.githubusercontent.com/5795004/149504747-46f372dc-3b4c-4daa-b479-cfc7b7b562ad.png)

Press the RDP button (With Router installed previously and setup)

![Qfrr4KvVW5](https://user-images.githubusercontent.com/5795004/149504778-b46cd0d7-c927-4c78-b7ac-f83725c9b8ad.png)

Press the connect button to start a RDP

![aJtzf7blti](https://user-images.githubusercontent.com/5795004/149504849-73a9998f-7ab9-4ddd-a103-86d145b95b04.png)

Confirm all OK

![GAaagvlM6Y](https://user-images.githubusercontent.com/5795004/149504865-e85e385f-4aa8-4e83-843f-ae0f737132f8.png)

Stuck on this....

**Comment by Ylianst** [comment]
It looks like it can't connect to the remote RDP port. It's not going to be possible for me to debug your situation, but RDP could be disabled on the remote computer or something is blocking it.

**Comment by matthiscock** [comment]
Your correct and my apologies for missing it.
I swear I hit the toggle in Windows 11, but must be going mad

Happy to report works exceptionally well - I would also say this feature is massively under documented and exposed!!!
All the be3nifits for RDP sessions with none of the exposure (security of opening the port), hassle (port forwarding) and degraded session quality (RDP matches your computers setup, not you adapting the host)

If there is appetite id happy make a tutorial for this, but not sure where it would go on your site

**Comment by PrplHaz4** [comment]
> 
> If there is appetite id happy make a tutorial for this, but not sure where it would go on your site

I think it'd be useful to see common use cases with implementation examples - it's a bit of work to dig through the PDFs and get all aspects of a single use case.  It may be a good excuse to start utilizing the repo wiki for stuff like this.

@Ylianst For lack of a more holistic approach at this point maybe a section for "Tutorials", "Examples" or "Use Cases" could be added for this sort of content?
