### ISSUE TITLE
--Resetaccount not clearing 2 factor

### ISSUE THREAD

**Issue by UFOTyler** [Ylianst/MeshCentral#3455]
I recently enabled minimum password requirements in the config.json, this caused a forced password change for users. When a user that had 2 factor enabled tried resetting at the login screen it would crash the page. This seems to be a bug in its self, but to get around it I logged in to reset the users password and clear the 2 factor. But when they try to login it still asks for 2 factor.

So then I SSH'd in to the server, stopped it, and used: 

```
sudo node node_modules/meshcentral --resetaccount user//testuser --domain Default --pass Password123
```

It returns "Done." but when I enter those credentials it still asks for a token. From my understanding both attempts should've cleared 2 factor. 

We are using mongodb if that makes a difference. other subdomain servers that didn't have anyone using 2 factor seemed to be able to login and add two factor. I don't know why it asked for password change from certain users and not others, but it seemed to break something with resetting the accounts.

I was able to successfully get in by adding phone numbers to the accounts then choosing the phone symbol for the 2 factor code. then change the password inside the accounts. So as of now I got everyone up and running but it took some trial and error.

Thanks.

**Comment by Ylianst** [comment]
Thanks for the report. Checking this now.

Also, for the "crash the page" problem, if you can go in "meshcentral-data" and look for "mesherrors.txt" and send back any errors in that file, I will take a look at it.

**Comment by Ylianst** [comment]
I noticed the SMS and Device Push 2FA where not cleared when using `--resetaccount` so I just put in a fix for that. I will also note that `--resetaccount` is a last resort and requires that the server be reset when that command is done.

Hopefully that does the trick.

**Comment by Ylianst** [comment]
MeshCentral v0.9.69 is out with this fix.

**Comment by UFOTyler** [comment]
Hey Ylian, sorry for the delay.

I checked the mesherrors.txt, and this error seems to be relevant to the issue:

-------- 1/13/2022, 9:05:25 PM ---- 0.9.62 --------

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'wildleek'
Require stack:
- /home/mesh/meshcentral/node_modules/meshcentral/webserver.js
- /home/mesh/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.obj.checkOldUserPasswords (/home/mesh/meshcentral/node_modules/meshcentral/webserver.js:2241:13)
    at /home/mesh/meshcentral/node_modules/meshcentral/webserver.js:1483:21
    at /home/mesh/meshcentral/node_modules/meshcentral/webserver.js:686:36
    at AsyncWrap.<anonymous> (/home/mesh/meshcentral/node_modules/meshcentral/pass.js:31:88)
    at AsyncWrap.wrap.ondone (internal/crypto/pbkdf2.js:37:48) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mesh/meshcentral/node_modules/meshcentral/webserver.js',
    '/home/mesh/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}


It shows up pretty often after I was trying the Passwordrequirements setting.

I still have issues with implementing the below settings into my config:

      "passwordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 0,
        "reset": 90,
        "force2factor": true,
        "skip2factor": "127.0.0.1",
        "oldPasswordBan": 0,
        "banCommonPasswords": true,
        "twoFactorTimeout": 300


I set the "oldPasswordBan": to 0 to see if it was causing issues for people trying to set there password back after the server was forcing them to change it. I had it at 5 and it still was crashing the webpage  and saying server disconnected. Also I had multiple instances of the page up with different users and when it crashed during password reset it crashed everyone's page. One thing to note is we are using MongoDB and I don't recall having this issue with my other server running the built in NetDB. I'm struggling to keep trying different solutions since it keeps forcing password changes for users when I implement the "PasswordRequirements": settings. I don't want to keep hindering users while troubleshooting so hopefully the error I posted leads in the right direction and the issue can be replicated on your end.

As always thanks for the time and effort you put into this project.

-Tyler

**Comment by UFOTyler** [comment]
Should I create a separate issue for this? Thanks.
