### ISSUE TITLE
Default Settings for Desktop Connection.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3456]
Hi,
is it possible to enable "Clipboard-Sync" by default on connection?
Also is it possible to send current local Clipboard to Remote without paste it in the "Send" Windows first?
Cause for Logon to Windows Remote we use Password-Manager and copy Password from there.
Pasting it in the Type-Window first makes Password viewable for a short time. This is not really "secure"...

![image](https://user-images.githubusercontent.com/68963439/149464636-10936a2f-2620-4fd9-abdd-984702e23d58.png)

**Comment by Ylianst** [comment]
Hi. In Chrome, you can go in the desktop settings and check "Automatic Clipboard", that should have the browser poll for clipboard changes and automatically send them to the remote computer.

![image](https://user-images.githubusercontent.com/1319013/149569290-fee50fb8-23c7-4b68-beca-8dad2493f75e.png)

As for sending and receiving the clipboard, you can use the two buttons below:

![image](https://user-images.githubusercontent.com/1319013/149569518-85c658fc-9f0e-4a58-b3f7-7b44ef97701e.png)

Let me know if that helps.

**Comment by JSuenram** [comment]
Helps only partially as you can not send paste clipboard on logon-screens.
So you still need to "type" the password which is in local Clipboard from Password-Manager....

**Comment by Ylianst** [comment]
I am not sure I understand the request. What is needed?

**Comment by JSuenram** [comment]
> I am not sure I understand the request. What is needed?

Ok, I will try.

Consider you use a Password-Manager in a Company for all Admin-Accounts and so on.
Now you need to Logon Remote to a Server with an account. Windows Logon-Screen does not allow to paste clipboard data on logon-screen. So you need to send the Keyboard Keystrokes which can be done already. However when you paste the password in that window from your local clipboard, the password is viewable to the user. This is not ideal. es its just a short time, but if you use a password-manager you want to have your password not shown on screen.

ScreenConnect does it like this:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/68963439/149577037-6d7ead11-08d3-45f0-8ef5-c670d6882546.png">
You just send the Key Strokes without a "temporary" paste-window to the target Remote-Session.

More or less it is primary to save time and secondary to keep you password invisible on screen the whole time.
In Offices with multiple Desks you don't want to allow people to peek on your screen when you paste the password which gets shown in clear-text in the "Remote-Keyboard-Window"...

<img width="605" alt="image" src="https://user-images.githubusercontent.com/68963439/149577539-a654a48e-a2a3-46d8-b943-6b12ca4e13b0.png">

**Comment by dinger1986** [comment]
I think this is done @si458

**Comment by si458** [comment]
sadly you cant copy/paste on the login window for security
but you can use the type feature! which will send what you enter to rhe remote device when you are clicked in an input box
i know its not the best for security but its better than nothing
