### ISSUE TITLE
Web-RDP not working when local (no agent)

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3458]
Create local groupe (no agent)
add windows host (RDP)
![image](https://user-images.githubusercontent.com/32361668/149551951-eba7b97e-f04c-4f41-9f6d-3c71bbe12022.png)
click on the device
![image](https://user-images.githubusercontent.com/32361668/149552055-75e98a4e-a395-4d61-bebd-c13a0735f98b.png)
On the toolbar there is no rdp ect ?

**Comment by Ylianst** [comment]
This is normal, the tool bar is for MeshCentral Remote Desktop, not for RDP. For RDP you will need put the following line in the settings section of you config.json:

```
"mstsc": true,
```

Then, restart your server and use the "Web-RDP" link at the bottom. Note that "Web-RDP" only works with legacy authentication. Let me know if that helps.

![image](https://user-images.githubusercontent.com/1319013/149568324-c859f4c6-99b1-4bed-a197-48b9b8ad55f9.png)

**Comment by gaalos** [comment]
Hi,
Yes i got web-rdp available !! but when i try to log the page is refresh and no log output
![image](https://user-images.githubusercontent.com/32361668/149921529-a05ad69b-19d2-48a3-9732-50ceb0851630.png)

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
closing as stale
