### ISSUE TITLE
Clipboard-Sync does not work at all in Safari and partially in Brave on MacOS.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3459]
Maybe just a Browser-Limitation, but other Remote-Control-Software can do this.
Clipboard does not get send or received in Safari and also Auto-Clipboard-Feature does not work.

In MacOS with BraveBrowser you can only "Send" Clipboard but not receive. Also in AutoMode not.
And every time you send ClipBoard there is a CMD-Window launching on Remote-System, bit confusing.....

**Comment by krayon007** [comment]
What OS are you running on the remote system?

**Comment by JSuenram** [comment]
Windows Server 2012/2012R2/2016/2019/2022 all the same behavior....

**Comment by si458** [comment]
closing as stale,
also auto-clipbaord only works with CHROME/EDGE,
so please try the latest version 1.1.20 and also use node 18 or above,
if issue persists after this, please reply back
