### ISSUE TITLE
Web-RDP and Web-SSH configuration.

### ISSUE THREAD

**Issue by psoft-pt** [Ylianst/MeshCentral#3461]
I had the mstsc configuration but i cant get **Web-RDP or Web-SSH** in connection options of the machines.
Only have RDP and Web-VNC.
I'm using latest version on Windows Server 2019. I'm new to Mesh Central.
**How can we configure this options?**

![imagem](https://user-images.githubusercontent.com/44953713/149599316-24eac31d-42ec-46a7-aa66-c52d190f0ee2.png)

![imagem](https://user-images.githubusercontent.com/44953713/149599398-deb09456-7736-4ec0-bada-f65b13c59a1c.png)

**Comment by gosteras** [comment]
you need these lines vensti here

   "domains": {
     "": {
     "_title": "MyServer",
     "_title2": "Servername",
     mstsc: true,
     "ssh": true
     minify: true

**Comment by psoft-pt** [comment]
Solved, but RDP is too slow in refreshing screen.
