### ISSUE TITLE
MeshCentral Service Crash

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3462]
MeshCentral v0.9.68

MC-Server is in Crashloop. Service Status Linux says:
     CGroup: /system.slice/meshcentral.service
             ├─12166 /usr/bin/node /etc/meshcentral/node_modules/meshcentral/meshcentral
             └─12302 /usr/bin/node /etc/meshcentral/node_modules/meshcentral/meshcentral --launch 12166

Jan 15 09:27:17 MESH node[12166]:   cmd: '/usr/bin/node /etc/meshcentral/node_modules/meshcentral/meshcentral --launch 12166'
Jan 15 09:27:17 MESH node[12166]: }
Jan 15 09:27:17 MESH node[12166]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...

mesherror.txt
-------- 15.1.2022, 09:28:20 ---- 0.9.68 --------

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fc99a7700e8 node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]
 2: 0x7fc99a6ac01a  [/lib/x86_64-linux-gnu/libnode.so.72]
 3: 0x7fc99a91dcf2 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.72]
 4: 0x7fc99a91df9f v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.72]
 5: 0x7fc99aab6c15  [/lib/x86_64-linux-gnu/libnode.so.72]
 6: 0x7fc99aac696d v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.72]
 7: 0x7fc99aac7616 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.72]
 8: 0x7fc99aac979c v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.72]
 9: 0x7fc99aac9804 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.72]
10: 0x7fc99aa8fc0d v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.72]
11: 0x7fc99aa981bf v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/lib/x86_64-linux-gnu/libnode.so.72]
12: 0x7fc99ae573c6 v8::internal::IncrementalStringBuilder::Extend() [/lib/x86_64-linux-gnu/libnode.so.72]
13: 0x7fc99abb2b2a v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/lib/x86_64-linux-gnu/libnode.so.72]
14: 0x7fc99abb4bb8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.72]
15: 0x7fc99abb8656 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.72]
16: 0x7fc99abb9fe8 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.72]
17: 0x7fc99abba06c v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/lib/x86_64-linux-gnu/libnode.so.72]
18: 0x7fc99a9bea02 v8::internal::Builtin_JsonStringify(int, unsigned long*, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.72]
19: 0x7fc99b381819  [/lib/x86_64-linux-gnu/libnode.so.72]

Maybe this is just an Out Of Memory issue? We will try to add more Memory to the VM...

**Comment by gosteras** [comment]
1. How much memory is on your VM? 
2.How many users do you have online?

**Comment by JSuenram** [comment]
> 1. How much memory is on your VM?
>    2.How many users do you have online?

Well, VM had 2GB with Debian11 and local DB.... we doubled to 4GB and now it is running....
About 250Agents and 3 or 4 users....
I guess, it was just an OOM....

**Comment by gosteras** [comment]
P.S. 
 manual installer meshcentral 
![изображение](https://user-images.githubusercontent.com/95762246/149620260-581d1533-d6d6-4cdb-9369-fd079248bbac.png)

**Comment by JSuenram** [comment]
> P.S.
> manual installer meshcentral
> ![изображение](https://user-images.githubusercontent.com/95762246/149620260-581d1533-d6d6-4cdb-9369-fd079248bbac.png)

Yeah I know. Thank you... wer are in process of checking which Database we want to use... Mongo,Post,mysql....
any suggestion which is fastest for MeshCentral?

**Comment by gosteras** [comment]
mongo is the best option, but needs more memory

**Comment by Ylianst** [comment]
MongoDB Community Edition is free and works very well, no money needed.
