### ISSUE TITLE
Intel@AMT not showing in MeshCentral

### ISSUE THREAD

**Issue by langsdorff** [Ylianst/MeshCentral#3465]
Hi,
after installing MeshCentral and installing the agent on the same machine I am not seeing the AMT tab. And of course I can not make an AMT connection. To a windows 10 computer on the same network AMT is working (HW connected Desktop).  With MeshCommander I am able to connect to the Debian machine.
Debian machine with MeshCentral and Agent:
![debian](https://user-images.githubusercontent.com/17204528/149636942-916f0bfb-5042-497d-b9a2-1bc393c5d892.png)
![debian2](https://user-images.githubusercontent.com/17204528/149637129-426d9417-99a8-403d-ad0e-39de0bb04d7f.png)

tvl@hp800:~$ sudo meshcmd amtinfo
[sudo] Passwort für tvl:
DHCP error, timeout
Intel AMT v11.8.90, activated in Admin Control Mode (ACM).
Wired Enabled, Static, xx:xx:xx:xx:xx:xx, 192.168.10.46
Connection Status: Direct, CIRA: Disconnected.
tvl@hp800:~$ sudo meshcmd amtversions
BIOS Version = N01 Ver. 02.54
Flash = 11.8.90
Netstack = 11.8.90
AMTApps = 11.8.90
AMT = 11.8.90
Sku = 16392 (AMT, Corporate)
VendorID = 8086
Build Number = 3987
Recovery Version = 11.8.90
Recovery Build Num = 3987
Legacy Mode = False

Win 10 an same MeshCentral:
![win10](https://user-images.githubusercontent.com/17204528/149636957-5ee868d4-f39a-4ea3-a166-235a982df14f.png)

I think some AMT settings needs to be changed, but I have no clue. I am wondering about the DHCP error, because I use a manual IP in the AMT settings. Can somebody help me?
Thanx

**Comment by PathfinderNetworks** [comment]
All of my Intel AMT devices no longer function as well.  I'm all but certain it is due to this issue: https://github.com/Ylianst/MeshCentral/issues/3436

**Comment by JSuenram** [comment]
Today we had an issue. Intel AMT capable system with CIRA is no longer showing in Devices. It was there until turned off for some hours. It suddenly disappeared... turning it back on by power button resolved the issue. (Agent is also installed)

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
