### ISSUE TITLE
Unable to install required modules as non-root in Docker

### ISSUE THREAD

**Issue by joeldeteves** [Ylianst/MeshCentral#3466]
Hello,

I have MeshCentral working in Docker however the container is running as root, which per best practice is not recommended for security reasons: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md

I am trying to get the container to run as non-root instead, however whenever I set the container to run as the `node` user, MeshCentral fails to launch with the following error:

```
Installing archiver@4.0.2...
ERROR: Unable to install required module "archiver@4.0.2". MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. To manualy install this module try:

   cd "/home/node/app"
   npm install archiver@4.0.2
   node node_modules/meshcentral
```

I have tried everything from running `chown node:node` on the /home/node/ dir to placing global dependencies in the `/home/node/.npm-global` directory (even though I assume the dependencies are being installed locally).

Here is the dockerfile:
```
FROM node:14-alpine

ENV TACTICAL_DIR /opt/tactical

WORKDIR /home/node/app

RUN apk add --no-cache bash

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

COPY api/tacticalrmm/tacticalrmm/settings.py /tmp/settings.py

RUN grep -o 'MESH_VER.*' /tmp/settings.py | cut -d'"' -f 2 > /tmp/MESH_VER && \
    npm install meshcentral@$(cat /tmp/MESH_VER)

COPY docker/containers/tactical-meshcentral/entrypoint.sh /
RUN chmod +x /entrypoint.sh

EXPOSE 8080 4443

USER node

ENTRYPOINT [ "/entrypoint.sh" ]
```

And here is the start command from the entrypoint script:
```
# start mesh
node node_modules/meshcentral
``` 

Again, the container works fine as `root` but this presents a security risk.

I would appreciate any help you can provide on what permission is missing / how to troubleshoot this issue.

Thank you,

**Comment by nzalev** [comment]
When meshcentral attempts to install modules, it simply runs `npm install --no-optional moduleName` in its working directory (in this case, more specifically `npm install --no-optional archiver@4.0.2`)

If you run the command as the node user, within the same working directory, npm will output the underlying reason it is failing.

**Comment by joeldeteves** [comment]
Thank you @nzalev, I tried running manually and here is the output:
```
bash-5.1$ id
uid=1000(node) gid=1000(node) groups=1000(node)
bash-5.1$ npm install --no-optional archiver@4.0.2
npm WARN checkPermissions Missing write access to /home/node/app/node_modules
npm WARN enoent ENOENT: no such file or directory, open '/home/node/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/node/app/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/node/app/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/home/node/app/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/node/app/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-01-16T16_39_47_099Z-debug.log
```

I am looking into why I am unable to install this module as a standard user.

**Comment by nzalev** [comment]
NPM tells you what permissions are missing: `checkPermissions Missing write access to /home/node/app/node_modules`

Try 
```bash
chown -R 1000:1000 /home/node/app
chmod 770 /home/node/app/node_modules/
chmod 770 /home/node/app/
```

**Comment by joeldeteves** [comment]
Thank you @nzalev, the simple solution for me was to run
```
chown -R node:node /home/node
```
There was need for me to do chmod as the correct read/write permissions for owner are already set by the container, but your solution is still correct.

Thank you
