### ISSUE TITLE
Hardening the agent interface, similar to loginKey

### ISSUE THREAD

**Issue by radiowavesurfer** [Ylianst/MeshCentral#3468]
Hi. 

As discussed in my post on the subreddit, I'm requesting a security hardening feature which can be applied to the agent interface, (similar I think to the way loginKey can be used on the web interface), that would allow a proxy server (e.g. nginx) to reject any requests from clients where the requested URL does not contain a specific key.

This would tend to prevent unauthorized clients from communicating with the MeshCentral server - desirable when the agent interface is exposed to an untrusted network.

No doubt there are many ways this could be implemented - my guess is that the simplest approach might be to use the key as part of the URL's path, so that instead of the agent getting `/agent.ashx` it would instead get `/foo/agent.ashx` - where `foo` is the value of the key.

The proxy server could then be configured to only forward requests for the location `/foo/`.

If the feature is implemented this way, we'd need to know whether the MeshCentral server expects the proxy to forward matching requests through with the `/foo` path prefix still in place, or whether the proxy should remove the `/foo` prefix from forwarded requests.

Thanks.

**Comment by Ylianst** [comment]
Agreed, I will be adding this.

**Comment by Ylianst** [comment]
I just checked it into GitHub and will be with MeshCentral v0.9.70. You need to add this line to the `domain` section of the config.json:

```
"agentKey": [ "abc", "123" ]
```

Once set, you will need to manually edit the `meshagent.msh` file of the agent add the `?key=xxx` like this:

```
MeshServer=wss://central.mesh.meshcentral.com:443/agent.ashx?key=abc
```

If not added, the agent will not be able to connect.

Once published, let me know if that works.

**Comment by Ylianst** [comment]
MeshCentral v0.9.70 is out with this feature included. Let me know if it works for you.

**Comment by radiowavesurfer** [comment]
Thanks for implementing this. Sadly not much success so far.

I used the updater in the web ui to bring the server to 0.9.71, and used grep to ensure that the source files on the server do contain the agentKey code fragments from the commit.

I configured agentKey in the server config, in the domains section with an array of one key.
```
  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443/",
      "agentKey": ["foobar"],
	  ...
    }
  }
```

I modified the URL of one of my agents to include the key.
`MeshServer=wss://....../agent.ashx?key=foobar`

I then restarted MeshCentral, and restarted the agent. (At this stage, I had made no alterations to nginx, so it was forwarding every request.)

I logged into the web UI, and checked that the agent was connected - it was - great. However, I also saw that an agent on another computer (where I hadn't modified the URL to include the key) had _also_ successfully reconnected. So this seemed odd, but I kept going.

I then altered the nginx config so that only requests containing a particular key would be forwarded.
```
location / {
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-Host $host:$server_port;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;

	if ($args ~ key=foobar) {
		proxy_pass http://127.0.0.1:1234$request_uri;
        break;
    }

    return 404;
}
```

After reloading nginx config, and restarting MeshCentral (to force the agents to reconnect), now the only agent that was connected was the one where I had configured the key. Fine.

But when I now try to use MeshCentral to connect to that computer (e.g. desktop, terminal, etc), the agent tries to get `meshrelay.ashx` from the server, but isn't including the key among the URL parameters, so of course nginx is rejecting it with a 404.

Given what I noted earlier about how, when nginx wasn't enforcing the presence of the key, the MeshCentral server was still happy to accept connections from agents without any key, it feels like the new functionality is just not activating, somehow.

Grateful for any suggestions.

**Comment by Ylianst** [comment]
The line of code that blocks agents that don't have the key in MeshCentral [is here](https://github.com/Ylianst/MeshCentral/blob/e1fe584ba7541aae60cfaad25ab1376c9084b9e6/webserver.js#L6311). It's in the webserver.js file, make sure you have this line.

As for other URL's the agent will access, 'meshrelay.ashx' is a URL accessed by both browser and agent to create a tunnel between the two. It uses it's own random session key to pair the two websocket connections together. I could add the `key=` to that one, but not sure how you would not block the browser too?

**Comment by nzalev** [comment]
@radiowavesurfer Are you using an agent only port?

**Comment by radiowavesurfer** [comment]
Hi all. I think we're getting somewhere.

But first, to recap on my goal here: I'm intending to deploy MeshCentral such that only the agent interface will be exposed to the internet, and the web UI interface will only be accessible from the LAN.

To this end, I'm using config settings to run the agent interface on a separate port, and with a different DNS alias than the web UI interface. Each interface is then accessed via a different nginx proxy, so I can have different rules on one proxy than the other (i.e. enforce the use of agentKey on the agent interface).

Back to the specific issues I described in my last post. The first was that, with the use of agentKey enabled in MeshCentral and in one agent, and with nginx configured to simply pass all requests through, I was seeing that agents from other computers (that I hadn't yet given the agentKey to) were still able to connect.

Looking at webserver.js, it seems that there's a separate code path for handling agent connections when agent interface port is being run separate to web UI port, and this isn't performing the same check for a valid agentKey. It's around line 6338.

(Now actually, this isn't of great importance to me, since my goal is to have nginx enforce the presence of the agentKey anyway - but it does explain the puzzling thing that I was seeing yesterday.)

The more important issue is around allowing the agent to access meshrelay.ashx. Regarding your point about not blocking the browser, nginx's logs are telling me that the browser is getting meshrelay.ashx from the web interface, not from the agent interface, so using nginx to enforce the presence of the agentKey solely on the agent interface shouldn't cause the browser to be blocked.

To validate this idea, I've configured nginx to enforce the agentKey on the agent interface, and then added an exemption such that the agent with one particular IP address will be able to access meshrelay.ashx without the agentKey. With that setup, I've successfully been able to connect from my browser to the desktop and terminal of that agent.

So I think that if we can make it so that nginx will permit the agent to access meshrelay.ashx by means of having the agentKey included in its URL, rather than by means of having a specially-exempted IP address, then we'd be good to go.

Thanks.

And, @nzalev, your comment popped up just as I was typing all of this - having read this far you'll already know that the answer is: yes. :)

**Comment by Ylianst** [comment]
On the topic of the agent post not having the agent key check, @nzalev [fixed it here](https://github.com/Ylianst/MeshCentral/commit/4d80499d8f264454751f2cb4f42a52d1b32a1c92). That fix is part of MeshCentral v0.9.72.

Indeed, having NGINX and MeshCentral both enforce the agent key is excellent.

**Comment by radiowavesurfer** [comment]
Hi all. Can this be re-opened?

I should have summarized after my wall-of-text comment - the part of the issue that @nzalev has fixed, while much appreciated, is not actually what I'm blocked on.

I'm asking for the agent key to be included in the URL when the agent gets meshrelay.ashx.

Based on the testing I've done, I'm satisfied that this will allow a configuration where nginx will reject **all** requests from unauthorized clients, and without blocking the browser.

Thanks.

**Comment by jvandenbroek** [comment]
As @radiowavesurfer said, the agent doesn't include the specified key on the MeshServer line for access to meshrelay.ashx. This would really help a lot in securing the server.

**Comment by inpertuts** [comment]
Hi all,

I also vote for the agent key is to be included in the URL when the agent gets meshrelay.ashx 
As long as this is done we add an additional `if ($args` for each agent

```
location / {

    set $propa 0;

    if ($args ~ key=theAgendKey) {
        set $propa 1;
    }

    # agent1
    if ($args ~ nodeid=node//nodeidOfAgent1) {
        set $propa 1;
    }

    # agent2
    if ($args ~ nodeid=node//nodeidOfAgent2) {
        set $propa 1;
    }
    
    ...

    # All other
    if ($propa = 0) {
        return 404;
    }

    proxy_pass ...
}
```
