### ISSUE TITLE
Several users connect to the desktop

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#347]
When several users connect to the same device, the connection is lost for a few seconds. If at the same time it is impossible to hook up users, then make at least notice that already has an active connection.

**Comment by MailYouLater** [comment]
It would be really nice if multiple people could view, but only one have input control, but I'm not sure about the implementation details, so I don't know if this is feasible or not.

**Comment by Ylianst** [comment]
Having multiple people view the same desktop should work, if not, please let us know what OS/Disto/version you are using so we can try to replicate the problem. The initial bug report is too vague.

As for multiple users and passing control, certainly possible and would have to be filed as a separate issue. But given I am completely swamped with feature requests, not sure when I would get to it.

**Comment by treicadani** [comment]
The problem i found with multiple users connected to the same Desktop (with multiple screens and running Windows 10) is that if any of us change the screen from all screens to any other, for the other person starts to flicker from screen 1 to all screens very fast.

Also the screen 1 doesn't do nothing when selected, and when screen 2 is selected it shows screen 1, and all screens option works ok. I think there is a open ticket for the second issue.

**Comment by si458** [comment]
@treicadani you should look at desktop multiplexer (2023) - https://www.youtube.com/watch?v=r0IfzuZgf3s
