### ISSUE TITLE
MeshCtrl - Event Disconnect and Session-Duration

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3472]
With MESHCTRL we can use "show events" which prints all occurring events on screen until you press ctrl-c.
We are searching for a way to display/filter Remote-Sessions which get disconnected/finished and have printed Servername, not just nodeid and User and Date/Duration of the session. We want to put this data in our Helpdesk-Systems Database.
It would be enough if meshctrl just drops this data into txt-files.

We tried to get it direct from database but it is encrypted there.

Can this be archived? And how?

**Comment by JSuenram** [comment]
So far "meshctrl show events --filter relaylog" gives us all data, except Agent-Name and group name, which is just the "coded" nodeid.
And the process runs forever. How to dump this on demand to a Log-File? Or is there an alternative way to get this data from Database?

**Comment by Ylianst** [comment]
If you have a developer that know how to code NodeJS, it's easy to take the meshctrl.js show event feature and make it do anything you like. There is a place in the code where you get event and you can look for the events you want and start doing anything you like with them.

You can always pipe the output of meshctrl.js into a file like this:

```
node meshctrl.js showevents > logfile.txt
```

Of course, putting the event directly from the database is the best. If you use NeDB, there is a "meshcentral-events.db" file that will have all the events. If you use MongoDB or another database, there is a collection or table just for events. Nice thing to MongoDB is that you can query for just the events you want.

Let me know if that helps.

**Comment by JSuenram** [comment]
Thanks, but we have no developers over here.... so we have to wait until someone needs or developes comparable feature that we can adapt....
