### ISSUE TITLE
UTF-8 file editing is now working in 0.9.71, but every other encoding does not

### ISSUE THREAD

**Issue by SEsternO** [Ylianst/MeshCentral#3473]
Referencing https://github.com/Ylianst/MeshCentral/issues/3450

It seems like decoding every file with utf8 (as I saw in https://github.com/Ylianst/MeshCentral/commit/c226363717883cb06b1de85a954542671f7d622f) breaks the ability to view and edit files in other encodings. For example, trying to open a file with CP1251, CP866 or ANSI encodings just returns the blank editing window.
It wasn't an issue in the older versions since I used to open hwinfo text reports, which have CP1251 encoding. Seems like more universal and maybe a little bit more complex solution is needed.
Thank you.

**Comment by Ylianst** [comment]
Ok, working on this one now!

**Comment by Ylianst** [comment]
In v0.9.72, I added a new encoding button you can toggle between "RAW" and "UTF-8", let me know if that fixes it.

![image](https://user-images.githubusercontent.com/1319013/150225737-59023a4f-903b-4e3d-a323-3ad2a91c1f52.png)

**Comment by Ylianst** [comment]
MeshCentral v0.9.72 is out.

**Comment by SEsternO** [comment]
@Ylianst huge thank you for your work! A button really does fix the issue with the ability to view encoding other than UTF-8. It doesn't, however, fixes how characters other than english show in other encodings. But hey, there's so many encodings and languages exist, you can't have 'em all, and even if you can, I can imagine how much harder it can be to implement. Besides, seeing UTF-8 as a world industry standart, I mark it as "not a big deal" and closing the ticket.
Thanks again!
