### ISSUE TITLE
Agent connection and disconnection

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#3475]
Hi , i have the latest version of meshcentral and i see in the list of the device agent that connect and disconnect frequently on the same pc.
i have setup exception on AV to avoid everything on c:\programmi\mesh agent\
please let me know.

**Comment by Ylianst** [comment]
Try adding this line to the settings section of the config.json:

```
"agentping": 60
```

This will cause artificial traffic to the agent every 60 seconds. See if that fixes it. "agentping" will cause the server to "ping" the agent and get a "pong" response from the agent. If that works, replace it with:

```
"agentpong": 120
```

That will send traffic to the agent every 2 minutes, but will not have the agent respond back.

The goal is to keep the connections going while creating as little traffic as possible.

Let me know if that works.

**Comment by tradexsrl** [comment]
ok i'll try because i think this problem is related to problem users report to me that every 5 minutes or less , when connected to rdp via meshcmd , gest disconnected....and the reconnection attempt is not done automatically , they need to reopen meshcmd which in turn launch meshaction.txt and then reopen the rdp session

**Comment by tradexsrl** [comment]
i have inserted the "agentping": 60 here:
  "settings": {
      "cert": "xxxxxxxxxxxxxxxxxx",
      "redirport": 80,
      "SessionTime": 30,	  
      "wanonly": true, 
      "_minify": true, 
      "selfupdate": true, 
      "clickonce": true,
      "AllowHighQualityDesktop": true, 
      "webrtc": true,
      "agentping": 60	
  
but i see client connect and disconnect (icon from blu became grey and viceversa) every few minutes

**Comment by tradexsrl** [comment]
seems that client affected are windows 7 professional 32 bit version 7601 with agent 
![immagine](https://user-images.githubusercontent.com/62424179/149913619-f7755da5-cbf1-4b5b-a6c3-aff7a9fa0601.png)

the other strange is if i look into details of the same device i get instead this:
![immagine](https://user-images.githubusercontent.com/62424179/149913843-c65cbdb0-3835-4318-949c-4cb4e8b1dc7e.png)

**Comment by VINISHVV** [comment]
@tradexsrl - are you using symantec AV?

**Comment by tradexsrl** [comment]
Yes but on client I setup exception on the mesh agent folder

**Comment by openncomp** [comment]
Also faced with this problem. By brute force, I found out that the problem disappeared if I set:
```
"AgentPing": 55,
"AgentPong": 55,
"BrowserPing": 55,
"BrowserPong": 55,
```
But I'm not sure exactly what all the values are needed.
If you set the values equal to or greater than 60, the problem repeats.

**Comment by gosteras** [comment]
i am use 
  "AgentPing": 50,
"AgentPong": 50,

try reinstalling the agent

**Comment by VINISHVV** [comment]
> Yes but on client I setup exception on the mesh agent folder

This issue is related to Symantec. For 32bit meshagent with Windows 7 Symantec installed system will stop/crash meshagent service in every 5 Minute. You can see corresponding logs in event logger.

I have raised a false positive report to Symantec team but its not resolved till now.

Please refer the replay from symantec team [here](https://github.com/Ylianst/MeshCentral/issues/3046#issuecomment-904626042)

@ylianst can you check it once

**Comment by tradexsrl** [comment]
> Also faced with this problem. By brute force, I found out that the problem disappeared if I set:
> 
> ```
> "AgentPing": 55,
> "AgentPong": 55,
> "BrowserPing": 55,
> "BrowserPong": 55,
> ```
> 
> But I'm not sure exactly what all the values are needed. If you set the values equal to or greater than 60, the problem repeats.

with all 4 parameters setup meshcentral server doesn't work at all

**Comment by tradexsrl** [comment]
> i am use "AgentPing": 50, "AgentPong": 50,
> 
> try reinstalling the agent

with the two paramaters setup meshcentral server doesn't work at all , i need to place only the firs one

**Comment by gosteras** [comment]
show your config

**Comment by openncomp** [comment]
> with all 4 parameters setup meshcentral server doesn't work at all

This is very strange, we checked on several installations of MeshCentral server, and they worked.

**Comment by tradexsrl** [comment]
> show your config
this is the config:
{
   "settings": {
      "cert": "xxxxxxxx.com",
      "redirport": 80,
      "SessionTime": 30,	  
      "wanonly": true, 
      "_minify": true, 
      "selfupdate": true, 
      "clickonce": true,
      "AllowHighQualityDesktop": true, 
      "webrtc": true,
      "AgentPing": 50      
   }, 
   "domains": {
      "": {
         "footer": "\u003ca href=\"http://www.xxxx.com\"\u003ewww.xxxxx.com\u003c/a\u003e",
		 "UserQuota": 1048760000,
		 "MeshQuota": 1048760000,
		 "UserSessionIdleTimeout": 25
      }
   }, 
   "smtp": {
      "host": "xxxxxxxxx", 
      "port": 25, 
      "from": "xxxxx@xxxx.com", 
      "user": "yyyyyy@xxxx.com", 
      "pass": "1234", 
      "tls": false
   },
   "letsencrypt": {
      "email": "xxxxxx@xxxxx.com",
      "names": "zzzzzzzzzzzzz.com",
      "rsaKeySize": 3072,
      "production": true
   }
}

if i add after 50 a comma and i add a new line with:
"AgentPong": 55,
"BrowserPing": 55,
"BrowserPong": 55
i get the webserver interface of meshcentral server down

**Comment by openncomp** [comment]
> > show your config
> > this is the config:
> > {
> > "settings": {
> > "cert": "xxxxxxxx.com",
> > "redirport": 80,
> > "SessionTime": 30,
> > "wanonly": true,
> > "_minify": true,
> > "selfupdate": true,
> > "clickonce": true,
> > "AllowHighQualityDesktop": true,
> > "webrtc": true,
> > "AgentPing": 50
> > },
> > "domains": {
> > "": {
> > "footer": "\u003ca href="[http://www.xxxx.com\"\u003ewww.xxxxx.com\u003c/a\u003e](http://www.xxxx.com%5C%22%5Cu003ewww.xxxxx.com%5Cu003c/a%5Cu003e)",
> > "UserQuota": 1048760000,
> > "MeshQuota": 1048760000,
> > "UserSessionIdleTimeout": 25
> > }
> > },
> > "smtp": {
> > "host": "xxxxxxxxx",
> > "port": 25,
> > "from": "[xxxxx@xxxx.com](mailto:xxxxx@xxxx.com)",
> > "user": "[yyyyyy@xxxx.com](mailto:yyyyyy@xxxx.com)",
> > "pass": "1234",
> > "tls": false
> > },
> > "letsencrypt": {
> > "email": "[xxxxxx@xxxxx.com](mailto:xxxxxx@xxxxx.com)",
> > "names": "zzzzzzzzzzzzz.com",
> > "rsaKeySize": 3072,
> > "production": true
> > }
> > }
> 
> if i add after 50 a comma and i add a new line with: "AgentPong": 55, "BrowserPing": 55, "BrowserPong": 55 i get the webserver interface of meshcentral server down

You have a syntax problem.
If you write settings at the end of the "settings" section, then after the last parameter, the "," sign is not needed.

**Comment by zaromarco** [comment]
i know...my config.json was:
"settings": {
"cert": "xxxxxxxx.com",
"redirport": 80,
"SessionTime": 30,
"wanonly": true,
"_minify": true,
"selfupdate": true,
"clickonce": true,
"AllowHighQualityDesktop": true,
"webrtc": true,
"AgentPing": 50,
"AgentPong": 55,
"BrowserPing": 55,
"BrowserPong": 55
},

**Comment by tradexsrl** [comment]
Hi , is there any news? any other test i can make?

**Comment by tradexsrl** [comment]
Hi @Ylianst , are there any news on this issue ?

**Comment by kennyparsons** [comment]
I'm experiencing this issue as well. `"agentPing": 60` did not help the disconnect and reconnect. 

This did work, though:
```json
"AgentPing": 55,
"AgentPong": 55,
"BrowserPing": 55,
"BrowserPong": 55
```

Thanks @openncomp. And Thanks @Ylianst for this amazing software!

**Comment by tradexsrl** [comment]
tried the same whitout any luck , i get connection and disconnection as before....

**Comment by a1ad** [comment]
We got the same problem. (behind pfSense HAProxy). When i set:

"AgentPing": 15,
"AgentPong": 15,
"BrowserPing": 15,
"BrowserPong": 15

... Everything is working like expected...not a great sollution i guess but at least we geot a stable connection.

**Comment by tradexsrl** [comment]
tried but i have the same problem...

**Comment by mikeleblank** [comment]
I comment my solution, comment the line _AgentPing

Solved, I kept AngetPong for the disconnection

**Comment by silversword411** [comment]
This means there are devices that are artificially shortening and killing sessions early. 

I've seen this happening in VPN devices, things going thru mobile networks do this as well, probably done to minimize open session states that the cell tower has to track. Would cause load on their radios.

Look in the setting of haproxy or others, see if you can find a max tcp/udp session time and adjust.

Using ping pong is just forcing the session to stay open using frequent packets that refresh the TCP session expiry.

**Comment by mikeleblank** [comment]
> This means there are devices that are artificially shortening and killing sessions early.
> 
> I've seen this happening in VPN devices, things going thru mobile networks do this as well, probably done to minimize open session states that the cell tower has to track. Would cause load on their radios.
> 
> Look in the setting of haproxy or others, see if you can find a max tcp/udp session time and adjust.
> 
> Using ping pong is just forcing the session to stay open using frequent packets that refresh the TCP session expiry.

Reviewing the readme about NGINX, my problem was in the NGINX PROXY timeout

        # MeshCentral uses long standing web socket connections, set longer timeouts.
        proxy_send_timeout 330s;
        proxy_read_timeout 330s;
