### ISSUE TITLE
Upload own Icons for Devices?

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3477]
We have these gorgeous Icons in MeshCentral.
But sometimes we want to sort it a bit more out... Servers, NAS, Desktops, Towers.... 
Maybe the possibility to upload own icons? Or where to place them so they are shown in the Icon-List?

![image](https://user-images.githubusercontent.com/68963439/149953835-a37a783b-bbe7-4d08-8daa-060ba1711bb6.png)

**Comment by Ylianst** [comment]
There is no way to add custom icons now, but this is a good feature request... only I am completely swamped with requests right now.

**Comment by si458** [comment]
this is now possible,
simply create the folder `meshcentral-web` then inside it another folder called `public`
then inside `public` copy the whole folder `node_modules/meshcentral/public/images` to the `public` folder
then edit your icons inside the new `meshcentral-web/public/images/` folder, 
then restart meshcentral, and meshcentral will now use those icons!
