### ISSUE TITLE
Feature Request: Email to admin when node is power down

### ISSUE THREAD

**Issue by itcuibap03** [Ylianst/MeshCentral#348]
Feature Request: Email to admin when node is power down

**Comment by Ylianst** [comment]
This is a good request, but apologies in advance, I am swamped with feature requests and this will take time for me to get to.

**Comment by si458** [comment]
this feature exists now in 2023
you enable the `smtp` section in `config.json`
then under your groups, select notifications and then tick 'device disconnections' for messaging
