### ISSUE TITLE
Feature request: add tag(some type of present UUID) into agent installer

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#3480]
I'm having a hard time locating/distinguishing newly installed agents.  They are all labeled the same computer name and have dynamic IP's.  Is there anyway to link an installer with a device once installed?  The ID can not be preset(from my understanding), and tags are made post install. Am I missing a step?

**Comment by Ylianst** [comment]
Hi. Yes, there is already a feature like this. In the same folder as the `meshagent.exe`, create a text file called `meshagent.tag`. It can't contain more than 1k of data and the agent will forward that data to the server.

For example if I create a file with "This is a test" using notepad, restart the agent and it will look like this:

![image](https://user-images.githubusercontent.com/1319013/150033260-c19b3c2b-f7d1-470c-bdc4-13be4c357c3e.png)

You can also search for agent tags. Put `atag:<search>` and only devices that match will show up.

![image](https://user-images.githubusercontent.com/1319013/150033443-8ac9651b-5d5b-4e7e-8c85-5ee39e35a00d.png)

Let me know if that helps.

**Comment by kpetrow** [comment]
How do you generate a meshagent.tag file on the remote machine? Could this be part of the installer?  I guess i could wrap meshagent.exe in  NSIS installer or some type of self extracting zip?  Thanks love the software

**Comment by Ylianst** [comment]
It's really up to you to create that file on installation. You can run `meshagent.exe -help` to see the options available. You can run `meshagent.exe -fullinstall` to install it within another script.

I am not sure what your trying to do, so I am giving you options. Another option is to look in the Windows registry here:

```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Open Source\Mesh Agent
```

The Windows agent will save a bunch of information when it first runs...

![image](https://user-images.githubusercontent.com/1319013/150208747-24479e11-610a-498f-b24c-6cfd0d61b834.png)

You can use that to help pair the agent with your usage.

**Comment by kpetrow** [comment]
I ended up throwing the agent in an installer and having it called by batch to set the meshagent.tag file.  Just thinking it might be useful to have the tag file be set by the meshagent.exe sort of like how it set groups.  Thanks again

**Comment by Ylianst** [comment]
What would a .tag file setup by the meshagent.exe contain? The tag file is specifically designed to allow usage specific data, like asset tags, etc.

**Comment by kpetrow** [comment]
We have 250+ sites(now organized as device groups) with 5-20 remote pieces of equipment per site that we need to be able to have a wrench turner guy install the software on.  I want to be able to have install/operator/maintenance tech go to website select their site and machine name that they are on, and click download button. That mesh agent installer will need to associate that box with known records for that computer.  The remote computer uses cell cards with dynamic IP address, so IP association won't work. The computers are flashed so they all have the same computer name.  Having 20 machines come online associated with a site but not knowing which computer is which wont work.  I can go into more detail on our infrastructure if needed/wanted.    It just seems to be basic that I want to call this mesh agent "MyComputer1" and have the installer assign that mesh agent that name(all the mesh agents come back with same computer name due to flash imaging).  With VNC repeater we were able to assign the Node ID's.
