### ISSUE TITLE
Unable to connect websocket

### ISSUE THREAD

**Issue by GauchoEsq** [Ylianst/MeshCentral#3481]
I’m visiting Brazil and using a cellular USB stick to get internet through Vivo. I can get to my Mesh login screen and authenticate, but it immediately jumps to Unable to Connect Websocket. The site has a LetsEncrypt certificate installed. I get a positive result if I go to websocketstest.com. 

If I connect through ExpressVPN then everything works fine. I’m running the latest version of Mesh. Is there any other diagnostic that I can run that might shed some light on this? Thank you!

**Comment by Ylianst** [comment]
This is interesting. [Looking online, it seems like this is not uncommon](https://social.msdn.microsoft.com/Forums/en-US/bb0e2891-e5d7-46e0-8ead-db5879fd285a/websocket-cannot-connect-when-using-mobile-data). People are reporting that websockets do not work over some cellular networks. Weird!

If anyone has any hints or things we could change to make connections work, I would be very interested.

**Comment by JSuenram** [comment]
Most Cell-Providers use ipv6 for their clients nowadays and do some sort of weird super-duper-Carrier-Grade-NAT to reach ipv4. 
Often they also "scan" your traffic. Both can make problems with Websockets.... User VPN is your best choice...

**Comment by GauchoEsq** [comment]
I'm not sure if this is worthy of another ticket, but in an attempt to alleviate this issue I enabled IPv6 on the virtual machine and assigned it an address. After creating an AAAA record, users on IPv6 can login to Mesh but the RDP link with the Mesh Router returns an invalid credentials error. If they connect with IPv4 then it works fine.

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
