### ISSUE TITLE
signing with code signing certificate

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3482]
Hi,
I have my own standard code signing certificate which I use to sign all agents, the issue is, on every update then I have to download all agents, sign then with signing tool then reupload them back to server. is there anyway we could implement the signing process in the server so it does that automatically using our own signing certificate? maybe like including the signing settings in the config.json for example:
<pre>
"signingCode": {
     "certificate": certificate.pfx,
     "password": xxxxxx,
     "encryption": 256
}
</pre>

**Comment by Ylianst** [comment]
The main problem is that MeshCentral is built to run on Linux and code signing is for Windows. Does your MeshCentral server happen to be running on Windows? If so, I guess I could call the Microsoft signing tool and do it.

**Comment by smartekIT** [comment]
no I'm running my server on ubuntu and to sign those agents i download them to my windows 10 machine then sign them using signtool.exe from windows kit. I though maybe linux has an alternative signtool to be able to do the same thing!!! if not maybe someone tried to use the linux package "Wine" to be able to run windows kit signtool.exe.

**Comment by JSuenram** [comment]
Maybe you can script some batch in Windows which calls sftp or scp to the server, downloads the Files, Sign them and upload them again. 

And if you want to fully automate, use Taskscheduler to do this.
Maybe the script can also check if files are already signed and just resign when an updated file is found?

Just an idea....

**Comment by Ylianst** [comment]
Ok, starting with MeshCentral v0.9.72, you can create a folder `meshcentral-data/agents` and put your signed agents into that folder. Just use the exact same name as files in 'node_modules/meshcentral/agents'.

MeshCentral will grab the agents binaries in `meshcentral-data/agents` first if present. So, you can sign then once and put them there. You can update as you like after. From time to time, you may want to update the agent, but that does not happen often.

**Comment by smartekIT** [comment]
Thanks heaps, will try that. at least now we don't have to resign each time server get updated unless new agents / router get released.

**Comment by jacotec** [comment]
@smartekIT Have a look at my #3571 .
Just saw your thread, I had the same problem and solved it using jsign in Linux. Maybe it helps you.

**Comment by smartekIT** [comment]
thanks heaps @jacotec , this helps a lot. i will move to your thread but can you please update the script with the new signed agent location mentioned by @Ylianst ? Thanks
also how about assistant, router and routercmd? i guess we need to sign those too.

**Comment by smartekIT** [comment]
@Ylianst hope you can come up with a brilliant idea now like always about signing with a built-in feature like accessing from the interface or having the signing steps part of the actual update process when option are met like:
- config.json has values and settings records for signing.

<pre>
"signingCode": {
     "certificate": meshcentral-data/certificate.pfx,
     "password": xxxxxx,
     "encryption": 256
}
</pre>

- certificate is found in the path included in signing settings in config.json and password for the cert too.
- the update released is included updated agent, router, assistant or routerCMD .... etc.
- the folder meshcentral-data/agents is there.
thanks heaps.

**Comment by smartekIT** [comment]
currently when i sign in windows using the Ms signTool, i use my certificate in .cer format which was exported from the .pfx file with no password required to go easy in scripts without having to enter my private password in plain text in any script.

**Comment by jacotec** [comment]
> thanks heaps @jacotec , this helps a lot. i will move to your thread but can you please update the script with the new signed agent location mentioned by @Ylianst ? Thanks also how about assistant, router and routercmd? i guess we need to sign those too.

@smartekIT I've updated the script in my thread to use /meshcentral-data/agents now.
Router and Assistant should already have an official signature from Ylian.

**Comment by JSuenram** [comment]
@smartekIT 
If your question is answered, please close.
Thank you!
