### ISSUE TITLE
Feature-Request Search by Group, Tag, etc etc

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3486]
Currently when in Host-View you can only search by Hostname. You can sort by Group or Group-Tag but not search for all Clients in all Group with Tag "Server" or Tag "Client". 

In a large Server/Client-List it might be useful to search by Tags, which could be Departments or whatever...

**Comment by openncomp** [comment]
I would just like to add that the web interface has the ability to sort by tags and group tags.
But if you sort in such a way that you cannot select all devices with a certain tag, as happens with the standard sorting by group, where you can right-click on the group and select "Select All".
It would be nice to implement this in addition to the search.

**Comment by Ylianst** [comment]
In the search box, try one of the following:

```
user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t: xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any
```

Let me know if that works.

**Comment by openncomp** [comment]
> In the search box, try one of the following:
> 
> ```
> user:xxx or u:xxx
> ip:xxx
> group:xxx or g:xxx
> tag:xxx or t: xxx
> atag:xxx or a:xxx
> os:xxx
> amt:xxx
> desc:xxx
> wsc:ok
> wsc:noav
> wsc:noupdate
> wsc:nofirewall
> wsc:any
> ```
> 
> You can also use 'and' and 'or' like:
> 
> ```
> group:mygroup and mycomputer
> ```
> 
> Let me know if that works.

It was really very easy )
Only one thing, there is no search for all ip addresses of the agent.
For example, when the server is running in WAN-only mode, all clients of the same group can have one IP address from the Internet, for example 1.2.3.4.
Is it possible to search for internal IP addresses that are displayed in the properties of the agent's network interfaces, for example 192.168.0.100.

**Comment by JSuenram** [comment]
> In the search box, try one of the following:
> 
> ```
> user:xxx or u:xxx
> ip:xxx
> group:xxx or g:xxx
> tag:xxx or t: xxx
> atag:xxx or a:xxx
> os:xxx
> amt:xxx
> desc:xxx
> wsc:ok
> wsc:noav
> wsc:noupdate
> wsc:nofirewall
> wsc:any
> ```
> 
> You can also use 'and' and 'or' like:
> 
> ```
> group:mygroup and mycomputer
> ```
> 
> Let me know if that works.

t:xxx does work but tag:xxx currently does not....

**Comment by Ylianst** [comment]
The problem is probably internalization, "tag:" may be translated in a different language, check the translation to see what it's currently set to.

**Comment by JSuenram** [comment]
> The problem is probably internalization, "tag:" may be translated in a different language, check the translation to see what it's currently set to.

Yep, got it.
<img width="396" alt="image" src="https://user-images.githubusercontent.com/68963439/150573350-0d1f5825-71e6-4b4a-89c6-aaa323b2c777.png">

Will correct translation as this word in German means "label". Tag is tag even here in Germany... ;-)
Will commit soon....
