### ISSUE TITLE
Agent Details No longer available after upgrade from 9.67 to 9.71

### ISSUE THREAD

**Issue by The-Real-Admin-Guy** [Ylianst/MeshCentral#3488]
All hardware configuration is now just a white page in all agent information details page...

**Comment by krayon007** [comment]
What OS is the agent running?

**Comment by The-Real-Admin-Guy** [comment]
all the Agents returned funny in the web page.  I just patched the server, and restarted and now all data is visible again.
I'm running from the web on Linux....   
It's all good now false alarm!

I'll be scanning logs until I get to the bottom of it but the issues seems related to Ubuntu.
