### ISSUE TITLE
terminal not working for some clients (flashing cursor on connect)

### ISSUE THREAD

**Issue by kevinh-csalabs** [Ylianst/MeshCentral#3489]
On the most recent server version I'm having trouble with some clients. Connecting to the terminal says connected but nothing ever loads. Console shows:
```
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: Error in Query in method 'onTunnelData()'
```

Clearing core and reuploading core doesn't help.
setting minify: false doesn't help.
setting webrtc false doesn't help
forcing agent update doesn't help

```
agent info:
{
  "openssl": "1.1.1l",
  "duktape": "v2.6.0",
  "commitDate": "2022-01-07T03:09:37.000Z",
  "commitHash": "22744773169b32a8b7c4382dba41a897b5c2d63c",
  "compileTime": "11:25:19, Jan  7 2022"
}
```

Any suggestions?

**Comment by Ylianst** [comment]
What version of the MeshCentral server are you running? and what OS is the remote system running?

**Comment by kevinh-csalabs** [comment]
server version is: 0.9.71. It was previously working on 0.9.5x

Device is Windows 10 Enterprise - 2009 [19044]

I've checked another device that was Windows Professional 19044 on the same network and it was ok, so not sure that it is build specific.

**Comment by krayon007** [comment]
In the console tab, if you type `osinfo` what does it say for ConPTY?

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
