### ISSUE TITLE
Guest Sharing Link + Consent

### ISSUE THREAD

**Issue by Cerothen** [Ylianst/MeshCentral#3492]
I have greatly been enjoying the use of MeshCentral and its a core part of my Family Support Strategy.

A few weeks ago a tweet came out indicating agents now support a new access prompt request.
https://twitter.com/MeshCentral/status/1479627583251648512

Since that time guest sharing links that also require consent have not been working properly. A guest sharing link will indicate that it is awaiting consent however no prompt ever appears on the agent machine. As consent can't be provided it doesn't allow the sharing link to permit access (pending approval). For now I have been able to use the non-consent version with success however it would be nice to have the bug resolved whenever is convenient.

Thanks!

**Comment by Ylianst** [comment]
What version of the server are you running? I just tested user consent on a guest sharing link and it worked for me. Any way to replicate your issue would be appreciated. Thanks.

**Comment by Cerothen** [comment]
Version 0.9.72

To confirm the consent link popup works properly when requesting consent from a logged in user, just not the sharing link.

I am not sure what you need specifically from me to replicate the issue but it does occur on 3 different instances. They all have basically the same configuration which I will put below:

```
{
	"settings": {
		"Cert": "mesh.HOSTNAME.TLD",
		"IgnoreAgentHashCheck": false,
		"Port": 443,
		"RedirPort": 80,
		"TlsOffload": true,
		"TrustedProxy": "192.168.10.11",
		"Minify": true,
		"Compression": true,
		"WsCompression": true,
		"AgentWsCompression": true,
		"agentPong": 45,
		"browserPong": 45,
		"_agentPing": 45,
		"_browserPing": 45,
		"_WANOnly": true,
		"WebRTC": false,
		"AllowFraming": true,
		"AllowLoginToken": true,
		"exactports": true,
		"SelfUpdate": true,
		"desktopmultiplexor": true,
		"SessionKey":"<<REDACTED>>",
		"mqtt": {
			"auth": {
				"keyid": "Key1",
				"key": "<<REDACTED>>"
			}
		},
		"plugins": {
			"enabled": true
		}
	},
	"domains": {
		"": {
			"SiteStyle":2,
			"Title": "MESHCENTRAL",
			"Title2": "Mesh Central",
			"CertUrl": "https://mesh.HOSTNAME.TLD:443/",
			"newAccounts": 0,
			"agentInviteCodes": true,
			"mstsc": true,
			"ssh": true,
			"welcomePicture": "switzerland.jpg",
			"welcomePictureFullScreen": true,
			"_end": true
		}
	},
	"smtp": {
		"host": "192.168.10.16",
		"port": 25,
		"from": "do_not_reply+meshcentral@HOSTNAME.TLD",
		"tls": false
	}
}
```

I can look into providing the logs should that help but I need to verify and remove any private info.

**Comment by Ylianst** [comment]
There is probably something in the guest sharing name, account name, account image, account real name or something else that is causing the issue... but I can't replicate it.

**Comment by Cerothen** [comment]
Is there anything else I can provide to make troubleshooting easier?

The device name is one word all caps
account name is one word all lowercase
there is no account image that did the initial share, adding an image does not change anything
The account real name was unset, setting it to a full name two words proper case did not help.

The agent logs did not contain any interesting data, I couldnt find a server log. I did not parse any of the DB files for more info. The server indicates no error logs.

**Comment by Ylianst** [comment]
I just found the likely issue and fixed it. The fix will be in MeshCentral v0.9.74. Once published, let me know if it works and close this issue if it does.

**Comment by Cerothen** [comment]
Thanks Ylianst I can confirm that your changes resolved the issue.

Your dedication to this project is outstanding and it really is one of my favorite software solution that I use almost daily.

**Comment by Ylianst** [comment]
Thank you!!
