### ISSUE TITLE
[Request] predefined commands on 'run command' 

### ISSUE THREAD

**Issue by tiagogbarbosa** [Ylianst/MeshCentral#3493]
Hello,

Is possible to add list of predefined commands on the run commands?
or edit/add the 'device actions' [preferred] ?

Ty

**Comment by JSuenram** [comment]
There is already a request for a toolbox [https://github.com/Ylianst/MeshCentral/issues/3471](url)
Might be a good place to also have some "predefined" command-blocks which can then just selected from a menu.
Maybe this can be merged into the feature-request....

**Comment by si458** [comment]
this is alread sort of implemented now,
when you click `run commands` you
1. type in command to run manually run
2. select to upload a file (the file can be a `.txt` file containing a list of commands to run
3. upload a file to your `files` area, then when `run command` you can select that file to run from your files!
