### ISSUE TITLE
ZLIB is not defined.  SRC zlib.js before zlib-adler32.js

### ISSUE THREAD

**Issue by junleus** [Ylianst/MeshCentral#3497]
Random happened at morning and systemctl restart meshcentral working again.

![image](https://user-images.githubusercontent.com/37057723/150382603-aa8bc341-fbc8-479d-9dc0-8dad70924406.png)
![image](https://user-images.githubusercontent.com/37057723/150382643-b71af6c3-f56c-4fca-a9dc-48d39e0b7ecc.png)

**Comment by Ylianst** [comment]
Looks like the server is not responding to any requests. Do you have a reverse proxy or anything that would block the requests?

**Comment by junleus** [comment]
yes, I put a nginx as frontend

`proxy_send_timeout 330s;
 proxy_read_timeout 330s;
 location / {
 proxy_pass http://127.0.0.1:4430/;
 proxy_http_version 1.1;
 # Allows websockets over HTTPS.
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_set_header Host $host;
 # Inform MeshCentral about the real host, port and protocol
 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;

 }
`

**Comment by Ylianst** [comment]
So, the problem is not ZLIB, the problem is that all the files in the screen above can't be loaded. Check your setup and fix that issue.
