### ISSUE TITLE
Alternative to PuTTY (MeshRouter)

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#350]
MeshCentral Server : 0.3.7-p
MeshCentral Router : v.1.0.7083

Is it possible to use an alternative to PuTTY as an SSH client within MeshRouter?

I've tried adding the application as "Custom", with a TCP port 22, but after adding it into the Router entries, Open is greyed out. I also don't see a way to edit the entries so I have to delete it to try again but at no point does the application prompt me for the path to the "Custom" application?

**Comment by D4V3M0NK** [comment]
FYI : The idea would be to try and get SecureCRT working as an SSH client, instead of PuTTY. 
Additionally, for a custom application, I'd really like to see if I can get MySQL Workbench routing through MC as well which is currently configured through an SSH connection as well, so there's two potential custom applications that I would like to use here. 

Finally, I think there should also be a "Description" section for adding new maps so that there can be (as in the case I describe here) some determinations between potentially very similar setups.

**Comment by D4V3M0NK** [comment]
Following up on this, I do now see the intermediate screen that asks for the path to PuTTY (you have to configure the entry as a PuTTY entry, rather than a "Custom"), so I can replace the assumed path to putty in favor of the SecureCRT one ... it doesn't work at the moment (SecureCRT responds with Hostname lookup failed: host not found) ... 

Am I to assume that MCR uses something like "putty.exe localhost:portNumber" to redirect putty to use the port set up by MCR, which ultimately redirects through to MC and then the final host:22?

**Comment by Ylianst** [comment]
I can add support for SecureCRT if you like? I need to look up the command line arguments for SecureCRT so that when you hit connect, I can launch SecureCRT and have it connect to 127.0.0.1:port. I can look at doing this.

**Comment by Ylianst** [comment]
By the way, I am absolutely swamped with work and I am getting too many feature requests, I can't possibly handle them all in a timely matter. This is the problem with success I guess. This one is fairly small request, but just want to apologize for the closing as many bug requests as I would like.

**Comment by D4V3M0NK** [comment]
I've been keeping an eye on how many new requests are coming in and I do feel for you Ylian ... please, take your time, PuTTY is working and working very well too, so assigning this low priority is absolutely the right thing to do.  Do I need to send a case of beer north to you and the team? Would that help?

**Comment by Ylianst** [comment]
I appreciate the email. I am doing MeshCentral and MeshCommander, both are very successful. Now MeshCMD (A Intel AMT command line tool) is also getting lots of attention. Each of these projects is a full time job on it's own.

In any case, SecureCRT should be really easy to add. Sometimes I do these just to close the simple issues.

**Comment by D4V3M0NK** [comment]
Ok, the penny's just dropped...

Within MCR, if you set a "Custom" application, MCR opens up the port immediately allowing you to connect via that port to your remote client's port set up in the map. I did not realize this. I've just tested it using a "Custom" application pointing to port 22 on my remote client, attempted to connect via PuTTY connecting to the local port: it works just fine!

When I try to perform the same action within SecureCRT, I get a remote system refused the connection but that could be a setting within SecureCRT that I need to ask their team about, correct?

Damn I'm slow sometimes...

**Comment by D4V3M0NK** [comment]
And I've just tested MySQL Workbench connecting to my remote client, through MCR.  I don't feel as if my request for adding SecureCRT is a valid issue, or even request so I'm going to close this issue. I will do ask Van Dyke for assistance in how to set up a connection using a local proxy and take it from there. Apologies...

**Comment by Ylianst** [comment]
I did not know about SecureCRT, it's a paid app with a 30 day trial. If you want to give me the executable name and command line arguments to launch it and connect, I can easily add it to MeshCentral Router. Something like:

`SeruceCRT.exe -connect {host}:{port}`

I could add it in a few minutes.
