### ISSUE TITLE
GUI Requests: Alphabetical Menu's, and Notification Clear Location

### ISSUE THREAD

**Issue by matt-cylanda** [Ylianst/MeshCentral#3500]
Thanks again for all the work and improvements in this project. Really love this platform.

I'm hoping these requests are easy ones to implement. Would it be possible to organize the various menus alphabetically?

![image](https://user-images.githubusercontent.com/65490814/150454135-26ccf2aa-0028-4cd6-8566-3147f77e462d.png)

One of my tech's was arguing with me that an action I was asking him to run wasn't present on his screen. In the end, it just turned out he couldn't find it because he couldn't find it in the list. I couldn't really blame him since I've had a hard time on occasion as well.

For the notification clear function. I have a lot of systems I monitor and like to get notified, but when on occasion the notification gets really long, it's a bit cumbersome to have to scroll to the bottom of the giant list to clear it.

**Comment by JSuenram** [comment]
Hi, yes I think sorting Alphabetical might be better here, but this has to be language-dependent.
Will try to look into it, but guess @Ylianst might be faster. I am still trying to understand the code. ;-)

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Will be in v0.9.73.

![image](https://user-images.githubusercontent.com/1319013/150570362-413847f2-6671-4be8-ba13-3e01a3f48d42.png)
