### ISSUE TITLE
Assitent Translate User conssent Message ?

### ISSUE THREAD

**Issue by CSW2000** [Ylianst/MeshCentral#3510]
Hello
1. How can I translate user consent from wizards? ( Assistant )
        In the agent this works with "consentMessages".. Desktop … Terminal .... in config.json.
        But how do I do this with the assistant?
2. And how does it work with "Auto accept all requests for next 5 minutes" line
3. And where can I set the time 5 minutes is usually very short to really help.
Greeting from Bavaria / Germany
Roland W. 
 

![userconsens PNG](https://user-images.githubusercontent.com/56474379/150631963-b4713f5f-03d2-4d73-ba1c-1119d26ef89f.jpg)

**Comment by JSuenram** [comment]
Translation is here I guess.
https://github.com/Ylianst/MeshCentral/blob/master/agents/modules_meshcore/coretranslations.json
I can add needed German translations and commit.

**Comment by CSW2000** [comment]
Thanks it was a fast service now
But what happens after update of Meshcentral2, is my translation gone? – I hope not 
Since the change is made outside the config.json.

Roland W.

**Comment by JSuenram** [comment]
> Thanks it was a fast service now But what happens after update of Meshcentral2, is my translation gone? – I hope not Since the change is made outside the config.json.
> 
> Roland W.
> 
> Hier ist die Deutsche Übersetzung für den DE Teil coretranslations.json [coretranslations.json.txt](https://github.com/Ylianst/MeshCentral/files/7918939/coretranslations.json.txt)

Well I already made a translation and "committed" it. If it will accepted by @Ylianst it will be in the Mainbranch and in all future Updates.

German: Ich habe die Änderung bereits eingereicht damit sie auch bei Updates nicht mehr überschrieben wird. Allerdings habe ich etwas anders übersetzt....

**Comment by CSW2000** [comment]
Have the German translation as above in the text in the "node_modules/meshcentral/agents/modules_meshcore/coretranslations.json"
Built-in – Saved and Restarted Meshcentral2, but the User Consent wizard window is in English.

**Comment by JSuenram** [comment]
> Have the German translation as above in the text in the "node_modules/meshcentral/agents/modules_meshcore/coretranslations.json"
> Built-in – Saved and Restarted Meshcentral2, but the User Consent wizard window is in English.

Sure, it will change when the Assistant is recompiled with an Update. This might be 0.9.73 or a later Version.
You have to wait until there is a new release with the changes committed or compile the whole thing on your own.

**Comment by CSW2000** [comment]
Thank You for your work.
Please Close it
Roland.W

**Comment by JSuenram** [comment]
> Thank You for your work.
> Please Close it
> Roland.W
You're welcome. You can close yourself or @Ylianst. I am not allowed to....
