### ISSUE TITLE
Feature Update: Prevent Uninstalling Mesh Agent

### ISSUE THREAD

**Issue by alialpsln** [Ylianst/MeshCentral#3511]
Hello, 

It's really useful to hide "meshAgent" in add/remove program list. I would like to prevent users from uninstalling the agent without knowledge of IT manager. May be a password protection can be a solution.

Thank you.

**Comment by JSuenram** [comment]
If users have the rights to uninstall/install Software then remove those rights. For daily work this should not be needed.

**Comment by openncomp** [comment]
I also think this feature would be very useful. It would be a long time to describe examples of its application, but there are cases when a user who cannot be restricted does something that he does not know himself.

**Comment by alibenzes** [comment]
> Hello,
> 
> It's really useful to hide "meshAgent" in add/remove program list. I would like to prevent users from uninstalling the agent without knowledge of IT manager. May be a password protection can be a solution.
> 
> Thank you.

Dear Ylian and @alialpsln

If the agent cannot be deleted or just removed by console Admin just like in Antiviruses, that would be perfect.

Regards

**Comment by nzalev** [comment]
> If users have the rights to uninstall/install Software then remove those rights. For daily work this should not be needed.

Agreed. Windows already has built into it policy options to prevent users from uninstalling software. 

The meshagent already gets tagged as malware by AV providers. I think adding fuel to the fire is not such a great idea.

**Comment by Ylianst** [comment]
This idea has been raised before and @nzalev is correct. If you have administrator rights for a computer, you can the rights to remove a Windows service no matter what we do. Also, it's not our intention to try to make the MeshAgent difficult to remove as it should not be installed on unauthorized computers in the first place.

Anyway, no plans to implement any protection against agent removal if a user has Windows/Linux rights to remove it.
