### ISSUE TITLE
Translated mails are still wrong language

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3513]
Server version: 0.9.72

i see in the folders, all translated files for notification, reset mail etc. but when i use one, i get the English version, and not the set language as from the browser.

![image](https://user-images.githubusercontent.com/58996467/150641614-9ffa25cb-75ca-45a2-b97a-c73e2afadf1a.png)
clicking on the reset link in the page, calls the good translation page
![image](https://user-images.githubusercontent.com/58996467/150641754-3375635c-c050-4c2f-9519-4444670db5a6.png)

**Comment by JSuenram** [comment]
Same here. Maybe MC Server is using localization settings from server for E-Mail....

**Comment by Ylianst** [comment]
Your right. The problem [is here](https://github.com/Ylianst/MeshCentral/blob/7fe87663143f5995214d7bb15769f19f06813fda/meshmail.js#L682). The device notification email is set to always be 'en-us'. Looking into it now.

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.9.73.

**Comment by petervanv** [comment]
I'll wait for the release, cant it be possible to set the language in the profile, so it is coonected to that user.
And to be complete, it is also at the other mailings from meshcentral, account reset, etc.

**Comment by Ylianst** [comment]
The problem is that if the language is set to the browser's default, then there is no language set in the user's profile. So, I now record the last language sent to the user into the user's profile.

Other emails like account reset are done while the users is on the web page, so I know what language to use.

In any case, test v0.9.73 and let me know if it's ok.

**Comment by petervanv** [comment]
Confirmed fix at the notification mail for connecting/disconnecting devices, hoping for the other fixes in the mail, closing

reopen if necessary
