### ISSUE TITLE
Send Message - Box has Yes/No buttons - Confused average person

### ISSUE THREAD

**Issue by soapster** [Ylianst/MeshCentral#3515]
When you send a message to a computer, the message box has both a Yes and a No button.
Is there a reason for this?  There is no feedback returned to the person that sent the message, that I know of. 
Is this intentional?  I sent a message to someone on their computer, and they called me to ask me if I sent it to them. It was clearly from me, and they were waiting for a message. The yes or no options confused them.
![2022-01-22 11_52_54-My Mesh Home](https://user-images.githubusercontent.com/8184435/150648284-bc05cb8d-adbe-4be2-b814-527c151319c9.jpg)

**Comment by Ylianst** [comment]
100% agreed and Bryan is already planning to fix this. Now that the agent is capable of displaying more sophisticated user interfaces on Windows, he can fix this easily. The first fancy UI for the MeshAgent was the user consent dialog. Now, this message box should get the same improvements with account image.

**Comment by soapster** [comment]
Excellent! Please put at the bottom of your massive pile of changes, though. There's literally zero priority.

**Comment by soapster** [comment]
![19-41 -24](https://user-images.githubusercontent.com/8184435/182494900-d73021b9-2c76-4a91-9ea9-a16c269bdcc2.jpg)

Looks like the recent changes has resolved this concern.  Closing!   THANKS BRYAN!
