### ISSUE TITLE
(Low priority) Missing translations

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3516]
scanning the logs, i found som missing translations.
![translation fix](https://user-images.githubusercontent.com/58996467/150680734-c4a564b7-5cd1-4a36-9c4c-1cb63b235463.jpg)

![translation fix 2](https://user-images.githubusercontent.com/58996467/150680803-39f1f103-4f83-48ff-baf8-d27990574f5e.jpg)

**Comment by JSuenram** [comment]
If you provide the correct translations for your language, Netherland I guess? We can add them in the translations-file.

**Comment by petervanv** [comment]
@JSuenram i know, im always supply the translations in dutch, see my pr about translations ;-)

**Comment by Ylianst** [comment]
Thank you @petervanv for reporting this, working on it now.

**Comment by Ylianst** [comment]
MeshCentral v0.9.73 is out :)

**Comment by JSuenram** [comment]
> MeshCentral v0.9.73 is out :)

And updating now..... ;-)

**Comment by petervanv** [comment]
Confirmed fix, closing

**Comment by Ylianst** [comment]
Thanks for reporting back and closing!
