### ISSUE TITLE
Added agent logo support -- not working

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3523]
HI,
I just created agent-logo.png file (square shape with 200x200 pxl size). i uploaded the file to my meshcentral-data folder and i added your provided code to my config.json file under agent customaization:
"image": agent-logo.png,

but unfortunately it doesn't work! when downloading the agent still not showing any logo there.
note that my agent name is branded changed from the default one.

**Comment by Ylianst** [comment]
This is for an upcoming agent that has no be released yet. Hopefully you will see this in a few weeks.
