### ISSUE TITLE
(Low priorty) Missing translations

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3526]
After reviewing some old, non closed issues i found an other missing translated string.
Its partly in dutch and the other part is not to bee found in the json file.
![translation fix 3](https://user-images.githubusercontent.com/58996467/150760881-a7293f54-351e-4662-b52b-a06cd68f6f17.jpg)

connected to: #1215

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.9.74.

**Comment by petervanv** [comment]
Confirmed fix, thx @Ylianst for fixing
