### ISSUE TITLE
(un)Translated mails

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3527]
Meshcentral version: 0.9.73
browser used: Google chrome latest

At the point from sending mails, in the right language, i got an tracing started at the mails, it shows it loads the language files, 
nl-nl and us-en, but the recieved language in the mail is EN, and not NL

I think the detection technik in meshcentral is failing in google chrome !?

some confusing here what is going wrong after te selection of the template
also tracing shows some untranslated strings too :-)
![translation fix 4](https://user-images.githubusercontent.com/58996467/150770856-621f6dc2-f131-4287-9fb2-46bb2cb306d5.jpg)

related to: #3526

In reaction at the top issue, i tested with firefox also, it shows the mail in dutch, as it supposed to do, the trace log is also slightly different.

![translation fix 5](https://user-images.githubusercontent.com/58996467/150773773-68cc466b-cdc5-46a1-ac2d-b0676c83766c.jpg)

In reaction at the top issue, i tested with MS edged also, it shows the mail in dutch, as it supposed to do, the trace log is also slightly different.

![translation fix 6](https://user-images.githubusercontent.com/58996467/150774843-e03125b8-4b27-44c4-aa62-7731da2a55ba.jpg)

A test with the device notification shows this trace (with chrome as browser) this said, chrome can detect the correct language
![translation fix 7](https://user-images.githubusercontent.com/58996467/150777705-cb7c2003-b194-4ab3-9312-fdeb22dfee16.jpg)

**Comment by Ylianst** [comment]
Thanks for reporting this, just put in a fix and will be in MeshCentral v0.9.74.

**Comment by petervanv** [comment]
Confirmed fix, thx @Ylianst for fixing this
