### ISSUE TITLE
Security feature request - support personnel only use pre-defined machines 

### ISSUE THREAD

**Issue by getut** [Ylianst/MeshCentral#3528]
I would like to request a feature that provides a way to ensure that support users are only providing support from company owned equipment... i.e. using the device that is hitting the meshcentral server as a security factor.

But this also would be that this setting would have to unchangeable by the support personnel and must be pre-configured in the user account for pre-registered devices they are allowed to connect from.

This is a very important security measure that ensures some semblance of a known security state for any device that is connecting to meshcentral. It also is necessary for any place that is part of PCI security compliance. Any machine that is allowed access to PCI environments must be  in scope for security audits. This feature request would help ensure that usage of the system would only be done from machines that are verified secure as part of PCI audits.

**Comment by silversword411** [comment]
How would you even be able to identify "company owned equipment"?

**Comment by Ylianst** [comment]
Same question. This request does not specify any details on how this should work.

**Comment by Ylianst** [comment]
Your not describing anything that is possible or can be implemented. UUID's are not a secure way to authenticate a client device. If you can point to any technology that does this in the marketplace, that would be great.

**Comment by getut** [comment]
I'm sorry, I'm not a developer so not even sure what marketplace you are talking about. But how about machine certificate that has to be loaded in advance?

**Comment by nzalev** [comment]
Part of the issue is that meshcentral is accessed through the browser. There is no local client to send this information.

The only information the webserver can know about the client is what the browser tells it. It is essentially limited to this: https://webkay.robinlinus.com/

**Comment by JSuenram** [comment]
In my opinion this request is not to be solved by MeshCentral. This is more the job for some sort of security solution which manages devices and creates some sort of encrypted tunnel where you are only allowed to connect to MS when you are inside this tunnel. And this can be deployed together with TPM or other unique identification. So only "known" systems can use it.

**Comment by getut** [comment]
I understand that it is not a great security feature and I think this would need to be used in combination with normal 2 factor auth. I see this more as a refusal to allow remote manipulation of devices after the support user got signed in with normal 2 factor. In other words even if they have both pieces of 2 factor working, if they are making the connection from a new machine, the machine either needs to be enrolled or it will be denied access to the remote devices.

**Comment by nzalev** [comment]
>In other words even if they have both pieces of 2 factor working, if they are making the connection from a new machine, the machine either needs to be enrolled or it will be denied access to the remote devices.

Meshcentral knows a lot about agent-controlled devices because there is a local client installed (the agent) providing meshcentral with details about that device.

Meshcentral can know very little about the device used to sign into the web interface, because the only information it can get is what the user's browser provides.

<br>
There are lots of traditional ways to limit user access to a web resource. For example, some companies will run an intranet web service, which requires users to use a VPN to access. In this scenario, user access can be controlled through the VPN client. I would suggest looking into a more traditional, well established, method of controlling user access.

**Comment by Ylianst** [comment]
100% agree with @nzalev and @JSuenram. Also, agree with @silversword411: How would you even be able to identify "company owned equipment"?

In any case, this request is clearly outside the scope of MeshCentral. Unless there is anything else, probably need to close this one.
