### ISSUE TITLE
Housekeeping: Clean up old Issues where people never reported back?

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3529]
Just a question.
Issue-List is getting pretty long, but many of them are fixed long ago.
Can someone be assigned as an operator, to clean up issues and problems which are already fixed?

I case... yes I would do that, if I am allowed to....

**Comment by silversword411** [comment]
Agreed, if you have flagged something as confirm and close and no response in a week just close it. 

If you need help with doing that you can grant my account the permission and I'll try and do cleanup.

**Comment by Ylianst** [comment]
Apparently there are bots that do this automatically... certainly something I need to look into. I rather give the job to a bot if possible.

**Comment by JSuenram** [comment]
> Apparently there are bots that do this automatically... certainly something I need to look into. I rather give the job to a bot if possible. If anyone has any suggestions for a good one, let me know.

https://github.com/actions/stale look promising...

**Comment by Ylianst** [comment]
Agreed, this looks promising. I really wish I could answer and fix all requests, but there are too many. I feel like I also need an "apologies bot".

**Comment by si458** [comment]
been working my way through then, including fixing bugs and adding enhancements!
