### ISSUE TITLE
Desktop for Linux

### ISSUE THREAD

**Issue by gvsurenderreddy** [Ylianst/MeshCentral#353]
hello sir 
I'm very happy with the project windows desktop can be seen for mac its just black screen when i click on desktop but for linux for my disappointment there is no desktop can you please enable desktop solution for linux too .We have more than 500 PC running right now on Puppy linux with Teamviewer.Please condider as serious project sir.Thanks for you support and Great project

**Comment by Ylianst** [comment]
Hi. For MacOS we can't capture the login screen and so, getting a black screen is expected in this case. This is a limitation of MacOS that we can't seem to get around.

For Puppy Linux, can you be more precise as to what version you are using. Even better, pointing to the exact ISO download that you are using? - Thanks.

**Comment by gvsurenderreddy** [comment]
UbuntuLTS14.04  and UbuntuLTS16.04 32bit

**Comment by krayon007** [comment]
Are you able to verify if it works if you uninstall teamviewer? I setup a Bionic Puppy VM, and so far the KVM works correctly. I know a few months ago, another user posted that KVM didn't work on linux if TeamViewer was installed. It turned out that TeamViewer modified the display driver settings such that when the mesh agent queried the primary display device, the OS gave it TeamViewer's virtual display device, which is why the screen at the time as black, becuase it was scraping a virtual display, rather than the actual display.

**Comment by gvsurenderreddy** [comment]
Sir only Command line is working it doesn't show up Desktop option like in MAC or windows
![Snip20190718_1](https://user-images.githubusercontent.com/14979881/61476803-75101200-a9ab-11e9-97d8-2c5ef93c4fad.png)
![Snip20190718_2](https://user-images.githubusercontent.com/14979881/61476837-8527f180-a9ab-11e9-91e7-0ea0d79bc6c1.png)

If accès for GRPhic is very good option for linux can u do it please

**Comment by krayon007** [comment]
If you click on the puppy client, and click on the console tab, and type info and hit enter, what does it say for 'capabilities' and 'X11 Support'?

**Comment by gvsurenderreddy** [comment]
Do you want me to Install X11

**Comment by krayon007** [comment]
As a side note, we do not utilize a custom video driver for KVM, we instead rely on fetching the video buffer from the xserver. This means if you don't use X , the KVM tab will not show up, as we would have no way to remote the desktop.

**Comment by krayon007** [comment]
What's interesting, is that the default configuration for Bionic Puppy, when I set it up, was using xorg

**Comment by gvsurenderreddy** [comment]
Hello sir X support is there .We are using Teamviewer and anydesk.
![Snip20190725_1](https://user-images.githubusercontent.com/14979881/61870139-fceda300-aefa-11e9-8a70-e1f90820811d.png)

**Comment by krayon007** [comment]
I setup a xenial pup 7.5 system, and everything runs as expected. Can you type 'info' in the console tab of the agent, and tell my what it says for X11 support? (TeamViewer does not use X for remote desktop).

The only reason the KVM tab would be missing, would be if it cant' find libX11, libXtst, or libXext. (Or if the server was configured to not allow KVM)

If it shows up as 'false', then I can send you a few other commands to try, to see if we can figure out why it's reporting as false...

**Comment by gvsurenderreddy** [comment]
Sir KVM should be installed on Meshcental2 server ? I have installed Qemu-gui on Puppy linux 
![Snip20190727_1](https://user-images.githubusercontent.com/14979881/61996620-b98a6480-b0b3-11e9-916a-5c51cabfb450.png)

When I type info on puppy Linux there is no command found

**Comment by gvsurenderreddy** [comment]
Sir can we add VNC server installed on Puppy linux can this is accessed with Meshcental agent installed on Puppylinux and See the desktop of Puppylinux on MeshCenteral Server please.

**Comment by krayon007** [comment]
I meant type 'info' on the console tab when you click the agent on the web browser, not in the actual client console.

**Comment by gvsurenderreddy** [comment]
Hello sir 
Please find the output for the command info
> info
Current Core: MeshCore v6.
Agent Time: 2019-07-29 20:15:05.208+08:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 14.
Server URL: wss://remote.voizn.com:443/agent.ashx.
Built-in LMS: Disabled.
OS: xenialpup 7.0.4.
Modules: amt-lme, amt-manage, amt-mei, amt-scanner, amt-wsman-duk, amt-wsman, amt-xml, amt, linux-dbus, monitor-border, power-monitor, smbios, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
lastMeInfo: null.
X11 support: false.

**Comment by krayon007** [comment]
@gvsurenderreddy can you run the following commands from an elevated console, and tell me the results:

ldconfig -p | grep libX11.so
ldconfig -p | grep libXext.so
ldconfig -p | grep libXtst.so
ps -ax | grep X

**Comment by gvsurenderreddy** [comment]
ps -ax | grep X
 5818 tty4     S<sl+   2:06 /usr/lib/xorg/Xorg :0 -br -nolisten tcp
 5976 tty1     S      0:00 /usr/local/apps/ROX-Filer/ROX-Filer -p /root/Choices/ROX-Filer/PuppyPin
13661 pts/0    S+     0:00 grep X

**Comment by krayon007** [comment]
what about the results for:
ldconfig -p | grep libX11.so
ldconfig -p | grep libXext.so
ldconfig -p | grep libXtst.so

**Comment by gvsurenderreddy** [comment]
Sir DOGpuppy We have installed and GOT Desktop but its too slow and most of the time its blank screen any Help can you suggest please
info result
> info
Current Core: MeshCore v6.
Agent Time: 2019-08-18 18:24:11.917+00:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 15.
Server URL: wss://remote.voizn.com:443/agent.ashx.
OS: Ubuntu 14.04.4 LTS.
Modules: amt-lme, amt-manage, amt-mei, amt-scanner, amt-wsman-duk, amt-wsman, amt-xml, amt, linux-dbus, monitor-border, power-monitor, smbios, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
lastMeInfo: null.
X11 support: true.

![Snip20190818_2](https://user-images.githubusercontent.com/14979881/63228652-9155d780-c213-11e9-8a71-0f93a31b9a52.png)


![Snip20190818_1](https://user-images.githubusercontent.com/14979881/63228630-55227700-c213-11e9-8a21-12b87fdd69be.png)

**Comment by si458** [comment]
this is supported in 2023 as standard if your desktop is running X
just make sure you have `WaylandEnable=false` set and uncommented inside `/etc/gdm3/custom.conf`
