### ISSUE TITLE
?hide parameter not working on /invite page

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#3531]
Hi, following up on https://github.com/Ylianst/MeshCentral/issues/744#issuecomment-568107169 - I want to hide header and footer on the invitation code-entry page, but it does not work. Is this intentional?

Thanks!

**Comment by Ylianst** [comment]
The hide feature was never implemented on these web pages, just added it in. Will be in MeshCentral v0.9.74.

![image](https://user-images.githubusercontent.com/1319013/150899109-34acb824-6528-424e-943e-e0450fe4e36c.png)

**Comment by mwllgr** [comment]
It works. Thank you for the quick implementation!
