### ISSUE TITLE
Request to change one translation entry into two

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#3532]
There is translation entry "Type" that is used in two places:
Here My devices \ Device \ Desktop \ :
![Zrzut ekranu (521)](https://user-images.githubusercontent.com/5872054/150962159-6c94fafe-0242-4183-8e67-fbf3b7421ad3.png)
  
And here at My devices \ Device \ Share \ :
![Zrzut ekranu (522)](https://user-images.githubusercontent.com/5872054/150962437-2bfdbe79-26c3-40eb-9434-90e07c75d326.png)

Locations:
default-mobile.handlebars->11->122
default-mobile.handlebars->11->623
default.handlebars->39->1026
default.handlebars->39->1241
default.handlebars->39->1747
default.handlebars->39->1807
default.handlebars->39->1897
default.handlebars->39->2695
default.handlebars->39->431
default.handlebars->container->column_l->p11->deskarea0->deskarea4->3
sharing.handlebars->p11->deskarea0->deskarea4->3

The problem is, while in English it is the same word for both typing data, and choosing type of something, in Polish for example, we use two different words (typ for type of something, and wprowadzanie for typing text into). I think it may be similar for other languages.
So i request for forking that one entry into two.

**Comment by JSuenram** [comment]
Yes, also here in German this is not done with a single "word"....
+1

**Comment by Ylianst** [comment]
Ok, working on this one now.

**Comment by Ylianst** [comment]
Hopefully fixed. Look for this line in translate.json:

```
"en": "[KeyboardTyping]|Type",
```

You only need to translate the part after the |. Let me know if this works.

**Comment by nicrame** [comment]
Should be fine now. Thank You!
