### ISSUE TITLE
Loging with Chrome type browsers

### ISSUE THREAD

**Issue by panenka** [Ylianst/MeshCentral#3534]
I'm using MeshCentral long time and I still have problems on loging with all Chrome type browsers (Chrome, Edge, Vivaldi). After log on, main screen is shown on short time and after that text and link has been shown - You can not connect to the Web Socket, click to reconnect. (translated from Czech language).
Whe I try the same with Firefox browser, there is no problem.
Now I have version 0.9.73.

**Comment by Ylianst** [comment]
I can't replicate the issue. Are you using a reverse proxy in front of MeshCentral? If so, there may be HTTP security headers the reverse proxy is adding that is causing this issue. You have to open the developer console in Chrome and report back any errors you see.

**Comment by panenka** [comment]
I found 5 times error in console and one warning
Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self'".
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

**Comment by Ylianst** [comment]
I will take a guess that the font one is due to a Chome plug-in you have. The 'interest-cohort' once can probably be ignored.

**Comment by panenka** [comment]
Ok tried on anonymous without any extension. Still not working, Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

**Comment by panenka** [comment]
When I am very quick, there is possible to choose Logout.
Found solution. When I try ip address instead of name (only name or FQDN), I could login without problems.
