### ISSUE TITLE
What happens if CertURL is used and the LetsEncrypt cert of the Proxy is updated?

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3536]
Hi,

first of all I found this great project much too late :-) It's awesome! Thanks for that!

I'm running the MeshCentral Server behind a HAProxy which also takes care about the LetsEncrypt certificates. Needed a bit to figure out why agents are not connecting, but then I found the CertURL parameter is neccessary.

That works now, but rose a question: The Letsencrypt certificate is automatically renewed by the proxy after 75 days to keep it valid. How will MeshCentral handle this? Is the action to get the cert hash from the proxy via CertURL being performed periodically, or do I need to restart MeshCentral every night via CRON to have it updating its needed hash in case the proxy has updated the LetsEncrypt certificate?

**Comment by Ylianst** [comment]
MeshCentral should handle this instantly. I think I talk about that [in this video](https://www.youtube.com/watch?v=YSmiLyKSX2I). Basically, a MeshAgent will connect and report to the server what Let's Encrypt cert it's saw then connecting. MeshCentral will notice this is not the normal value and get the CertURL at that point. If the new cert at CertURL is the same one the agent reported, the agent authentication continues and everything is ok.

So, there is no polling of CertURL. MeshCentral will load it once at startup and reload it when agents report a different cert.

There is a limit on how many times CertURL fetching is done, so if agents have lots of man-in-the-middle attacks, CertURL is not requested like crazy.

Hope that helps,
Ylian

**Comment by jacotec** [comment]
Thanks for the fast answer, that sounds good!
