### ISSUE TITLE
IP Address block in meshcentral?

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3538]
@Ylianst Can I know how to block the IP address in mesh central, I am getting some invalid login attempts on the server from known ip so need to block that IP address, thanks

**Comment by Ylianst** [comment]
Sure, in the settings section of the config.json, add this:

```
    "userBlockedIP": "192.168.0.100,192.168.1.200"
```

You can also block a range like this:

```
    "userBlockedIP": "192.168.0.100,192.168.1.0/24"
```

Once set, restart the server. Let me know if that works.

**Comment by JSuenram** [comment]
@sysadmin-us 
If your question is answered, please close.
Thank you!

**Comment by dinger1986** [comment]
@si458 can close
