### ISSUE TITLE
Content-Security-Policy (CSP) on MeshCentral tutorial website blocks YouTube embeds

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#3541]
On the website [MeshCentral tutorial website](https://meshcentral.com/info/tutorials.html), no YouTube tutorials are displayed because the Content-Security-Policy for this page is
```
frame-src 'self' mcrouter:
```
instead of
```
frame-src 'self' mcrouter: https://www.youtube.com
```

**Comment by Ylianst** [comment]
DOH!!!

**Comment by Ylianst** [comment]
Fixed: https://meshcentral.com/info/tutorials.html

However, the tutorials on that page are older than the [MeshCentral YouTube channel](https://www.youtube.com/c/MeshCentral).
