### ISSUE TITLE
[Features Request] Add some links to the contextual menu and add function and permission management in user groups

### ISSUE THREAD

**Issue by jamgrorg** [Ylianst/MeshCentral#3544]
Hey @Ylianst, thx for your work! This software is awesome but we want to make it greatest.

Can you add possibility to add Web-VNC, Web-SSH and Web-RDP links to the contextual menu on main screen or/and add possibility to open Remote Desktop, Remote Terminal and Remote Files not just in internal tabs but in separete browser tab?

Allso can you add possibility to manage permissions and functions not just for separate users but for user groups? It's not so easy to manage multiple users with different right policies if you can't add them to the group and set rigts and functions to this group. Or I miss something and there's such option?

**Comment by jamgrorg** [comment]
And is there any official changelog for new releases?

**Comment by Ylianst** [comment]
For user groups, it's already there, go in "My Users" and "Groups" tab.

![image](https://user-images.githubusercontent.com/1319013/151217176-34362181-9376-41d0-8359-484075a10658.png)

For change log, the best it to look at the [GitHub commit log here](https://github.com/Ylianst/MeshCentral/commits/master).

I can look into adding the context menus.

**Comment by jamgrorg** [comment]
Yeah you're right it's there but there's no opportunity to set privileges and functions to the group.

![3](https://user-images.githubusercontent.com/2796027/151301264-ddfa8d85-9093-4552-97ef-3bb11c795058.png)

Like in users section.
![2](https://user-images.githubusercontent.com/2796027/151301356-74b28ef0-6866-49c2-af13-ef22e86d8d92.png)
![Screenshot_1](https://user-images.githubusercontent.com/2796027/151301361-e4083616-8862-45c9-9a44-de1ce02cf37a.png)
Sorry for Russian language on screenshots, I think you got what I mean.

**Comment by jamgrorg** [comment]
Oh it's my bad sorry I've just realised that this functionality is present in device group management section. It's not so comfort for me but anyway it's there.

**Comment by Ylianst** [comment]
Ok, added extra context menus. Will be in MeshCentral v0.9.75.

![MC2-WebContextMenus](https://user-images.githubusercontent.com/1319013/151312241-17a987c3-6c24-4d46-afbf-2ce3575bb221.png)

**Comment by jamgrorg** [comment]
Ok, thx. Will wait for update!

**Comment by jamgrorg** [comment]
Hi @Ylianst, I've just install the update and it seems like links are messed up.
When I've enable web-vnc it shows web-rdp in contextual menu and when I've enable web-rdp its shows web-vnc.

![1](https://user-images.githubusercontent.com/2796027/151747807-f18430db-b4a1-481b-b228-5e235c4e441f.png)
![3](https://user-images.githubusercontent.com/2796027/151747843-365a5fd5-ddea-47a5-aac5-c70693ef4354.png)
![2](https://user-images.githubusercontent.com/2796027/151747824-97f8bfd5-68d7-46dc-99e8-26a48f5eda5e.png)

![4](https://user-images.githubusercontent.com/2796027/151747868-c82625ee-a76a-444c-9e52-226042c236e2.png)
![6](https://user-images.githubusercontent.com/2796027/151747876-327d28a9-bb99-4064-a9c4-92c0f8f47620.png)
![5](https://user-images.githubusercontent.com/2796027/151747886-f1d776ed-4690-4656-8a59-4e2c47a2d6da.png)

**Comment by jamgrorg** [comment]
@Ylianst can u chek it please?

**Comment by Ylianst** [comment]
Sorry for the delay, fixed it. Will be in v1.0.11.

**Comment by jamgrorg** [comment]
> Sorry for the delay, fixed it. Will be in v1.0.11.

Yap, now it seems to work fine, thx!
