### ISSUE TITLE
Feature Request: ESXi console/remote terminal access to guests

### ISSUE THREAD

**Issue by getut** [Ylianst/MeshCentral#3546]
I have searched the github and found a recent request to add ESXi which looks like a request to be able to connect to the ESXi host at a command line level. This is not that.

It would be very nice to be able to connect and control VM's on an ESXi host from MeshCentral using the built in remote terminal protocol. This would also enable the ability to remotely control older OS's that are running in the vmware instance like XP and Windows 2003 that are running in VM's because of legacy requirements. 

If this cannot be handled directly using vmware protocols, an alternative would be to offer vnc connections to those vms using the esxi built in vnc offering.... each vm can be shared via vnc protocol with some enablement requirements on the esxi side. Also, this is not vnc installed in teh guest os, but a vnc connection provided by the host esxi itself. 

Having VM's that cannot have agents added directly would still be very nice to see in a single pane of glass.

**Comment by JSuenram** [comment]
And maybe ProxmoxVE(noVNC,SPICE),HyperV(some kind of RDP) and so on.
Yes. Would be really nice... but I guess at the moment the task list with todos is as long as it was never before....
But from me....
+1

**Comment by si458** [comment]
closing as stale, but also vmware no longer support esxi due to broadcom purchase
