### ISSUE TITLE
Development Quest: default.handlebar

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3547]
Maybe it's just me, but the default.handlebar is really a huge file with a real massive amount of code.
There are many many functions. When I was young it was normal to split or move functions and other subs into separate files and include them while loaded. Is this possible in node.js and does it make sense in this case to split default.handlebar in some smaller files to make it easier to follow development?

Or maybe my development UI ist just junk and makes it impossible to detect the code. (I am using Visual Studio Code for this.)

Any suggestions?

**Comment by Ylianst** [comment]
My general view on this is that at some point, a proper framework like ReactJS should be used. I am not familiar with any frameworks, but there is nothing stopping MeshCentral from having many different web user interfaces. So, the current one would be a legacy one and a new better one would be built using modern a framework.

**Comment by JSuenram** [comment]
Will look into this and make some suggestions.... some day... in a far far....
