### ISSUE TITLE
MeshCMD amtinfo is reporting incorrect network information

### ISSUE THREAD

**Issue by matt-primrose** [Ylianst/MeshCentral#355]
I noticed that MeshCMD amtinfo command is reporting incorrect network interface information.  It is assuming that mestate.net0 is always going to be the wired interface and mestate.net1 is always going to be the wireless interface.  On my Lenovo T570 this doesn't appear to be the case.  I console.log the interfaces that are returned with 'require('os').networkInterfaces() in MeshCMD and this is what I'm seeing.
![image](https://user-images.githubusercontent.com/47540908/61228112-7820af00-a6da-11e9-9ebf-ee962e0badd3.png)

Looking for valid IP addresses, checking status, and type might be better?

**Comment by matt-primrose** [comment]
After some additional snooping around, I'm now thinking the issue may be in the amtMei.getLanInterfaceSettings() function.  When I console.log the results of this functions (against 0 and 1), here are the results.  As you can see, the second call doesn't match up to any valid wireless adapters.
![image](https://user-images.githubusercontent.com/47540908/61230779-95a44780-a6df-11e9-9896-e30f8612e96a.png)

**Comment by krayon007** [comment]
I'll do some digging, but I vaguely remember a while ago, then when the wireless configuration was disabled by AMT, the data I got regarding that interface was junk, until I enabled it. This was a while ago tho, so I'll see if I can run some tests

**Comment by si458** [comment]
is this still an issue?

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
