### ISSUE TITLE
File transfer should be improved

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3550]
While remote desktop works like a charm, file transfer could get a bit more love in my opinion.

Compared to Teamviewer or Anydesk it's quite complicated to download a complete folder with many files from the remote PC (unless I've not overseen something). The only way is to click on every single file to save it in the browser.

So, a "total commander view" like in Teamviewer would be helpful. Or drag-and-drop from the "files" window which also covers whole folders. While I can drag files from an Explorer window into the "files" tab of the remote session, dragging files of the remote PC out of the files tab and into an Explorer window on my computer does not work.

Also I see that the file transfer is incredible slow. The MC server runs on a server in a datacenter with 1GBit/s connection. I'm connected here with 100/40 MBit. Uploading a 3MB file to "MyFiles" of the server is just a fraction of a second. Uploading the same 3MB file to a remote computer via "Files" takes around 30 seconds! And the remote PC is in the same office at the same 100/40 internet connection.

As we very often need to transfer files to and from remote computers this is a showstopper right not to replace Teamviewer.

Edit: I found that the issue with file transfer speed is related to WebRTC. I'll open a separate issue for this

**Comment by Ylianst** [comment]
I have not looked at other software, but for downloading all files in a folder, you can hit the "Select All" button followed by "Zip" and have the remote agent compress all the file. You can then download that zip.

![image](https://user-images.githubusercontent.com/1319013/151319089-7298c5d5-55da-4b65-b545-90b306901ad1.png)

The "Files" panel does support drag & drop in, but not out. I think drag & drop out is only supported in Chome, I would have to check how they do it.

Your feedback on file transfer with WebRTC will be interesting, I have not tried tried to do performance tests.

**Comment by jacotec** [comment]
In Teamviewer it looks like this:

![image](https://user-images.githubusercontent.com/3321655/151330173-08ad7042-1087-47bd-b024-b61dcbe782c8.png)

I'd not say to copy other designs, but this is very convenient. You can select multiple files and folders on each side and then hit "Send" or "Receive" to transfer them right from one side to the other.

Especially the ability to also browse the full dirs on the controlling computer without the need to do an "official browser download" is convenient.

Regarding the WebRTC issue I've opened #3551 . 50 seconds vs. 8 seconds for the same 2.8MB file ;-)

**Comment by Ylianst** [comment]
Your asking for something that is not possible within a web browser since a browser do not have access to the local file system. However, native applications can do this and MeshCentral Router does exactly this.

![image](https://user-images.githubusercontent.com/1319013/151397053-d1766830-2368-420f-b050-0af226e26a76.png)

Let me know if this works.

**Comment by jacotec** [comment]
Thanks, I'll try that tomorrow!

**Comment by jacotec** [comment]
@Ylianst The router application is exactly what I was looking for in this term. This is a great project! :-)
It really needs more attention, I was searching so often for something like that.
