### ISSUE TITLE
File transfer much slower with WebRTC active

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3551]
I noticed that files transfers have been very slow even with a sufficient connection. Investigating this issue I finally found that this happens once WebRTC is active.

Scenario:
MC server running as a VM on my root server in a datacenter with 1GBit/s connection.
Both, controlling PC and remote PC in the office with a 100MBit down / 40MBit up connection.

File transfer of a 2.8MB test PDF with "WebRTC: true":

https://user-images.githubusercontent.com/3321655/151328606-4235d158-af2b-43e5-97cb-41cbc2dad799.mp4

Transfer of the same file with "WebRTC:false":

https://user-images.githubusercontent.com/3321655/151327789-4916958c-abd6-4972-8ca2-3983a1a67fc0.mp4

I would either expect the transfer to be much faster with WebRTC (Direct Machine-to-Machine in the same LAN) or at least having the same performance if file transfer is not using the direct connection and always uses the server as relay.

But with WebRTC enabled on the server it's significantly slower which even comes more into account with much bigger files.

But we see 50 seconds vs. 4 seconds for a 2.8MB file (which is a showstopper for WebRTC).

**Comment by JSuenram** [comment]
Did you check if you have some AV-Software with traffic-intercept running?
Some of these redirect traffic to their datacenter or slow WEBRTC-Traffic down to near zero.

**Comment by jacotec** [comment]
> Did you check if you have some AV-Software with traffic-intercept running?
> Some of these redirect traffic to their datacenter or slow WEBRTC-Traffic down to near zero.

Nope, nothing running like this (like Bitdefender VPN etc.). Also other WebRTC applications on the same machines works fine and fast.

**Comment by JSuenram** [comment]
Maybe collect a trace in the Browser when using WebRTC. It is possible to view the socket-traffic and get an idea what is happening when WebRTC is established. Maybe @Ylianst can help.

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
