### ISSUE TITLE
MeshAgent Remote Control MAC only primary screen shown.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3552]
Just testing remote control of MacOS-Cients. (Monterey 12.1 not tested with older Versions)

Only one display is transferred to the remote session and there is no way to swap from remote-client. 
I believe it is always the display where Menu and Dock are assigned to.
![image](https://user-images.githubusercontent.com/68963439/151331556-75cacec6-1f2a-4d47-b9a0-b5b1a408c581.png)

**Comment by dinger1986** [comment]
@JSuenram is this still an issue? I am sure I have seen dual screen now on macs

**Comment by JSuenram** [comment]
> @JSuenram is this still an issue? I am sure I have seen dual screen now on macs

As I am unable to allow "view" to remote clients at all under current MacOS, I can not say.... 
Even completly removing the agent from control and allowing it again, never leads to a viewable screen. Just Background-Image is shown....

![image](https://github.com/Ylianst/MeshCentral/assets/68963439/96887644-6643-41ab-81c7-075f767825e1)

**Comment by si458** [comment]
duplicate of #3773
