### ISSUE TITLE
Add "Restart Agent" to "Actions" menu

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3553]
During all my tests it happened from time to time that the Agent service on a remote machine got into a bad state, so that I could not see the Desktop or transfer files.

In this state, I still could press the "Werkzeuge" (Toolbox) button in remote Desktop, look for the MeshAgent service and restart the service remotely which always fixes the issue.

It would be convenient to have a "Restart Agent" entry in the "Actions" menu for these cases.

I did not try this with an Agent which is not installed but running "on the fly" and uninstalled (Remote Support Module). But it'll be useful if this could also be restarted via the "Actions" menu in case one of these Agents became wacky. Most customers prefer running things which must not be installed.

**Comment by krayon007** [comment]
You can type `service restart` on the console tab, in the meantime.

**Comment by Ylianst** [comment]
I rather fix the agent than add debug options to work around issues. Do you have any information we could use to replicate the agent problem?

**Comment by jacotec** [comment]
> I rather fix the agent than add debug options to work around issues. Do you have any information we could use to replicate the agent problem?

Unfortunately not. Agent got in that state several times with no reproducible actions.

Last time it was while zipping a dir with 280MB files for a test. But that was working after service restart.

As soon as I see any trace I'll report.

**Comment by Ylianst** [comment]
Oh, interesting. The agent should not get into a weird state.

**Comment by jacotec** [comment]
If that happens, Remote Desktop and Files will always  connect but not work. But I can list the services on the remote PC and restart MeshAgent. So it's partially still working.

**Comment by krayon007** [comment]
Interesting. Looks like the tunnels are getting in a wierd state. Those other commands just use the control channel but files and desktop will connect a websocket tunnel.

**Comment by jacotec** [comment]
@Ylianst @krayon007 If there is anything I can do to help you if I find an agent in this state, please let me know!

**Comment by si458** [comment]
you can restart the service by using the 'tools' button then going into services, finding your service, then clicking it and clicking restart
OR
you can use the command 'service restart' in the console tab
OR
you can go into the console tab, then click 'agent action' then try clicking 'Hard disconnect agent' which should disconnect it and then let it reconnect, rather than physically restarting the service
