### ISSUE TITLE
Finding specific MeshCentral Agent in trace using Mesh Identifier

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#3555]
Is there a way when you use the Trace (or console) to monitor for an individual Mesh agent?

See this

![2022-01-27_095454 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/151385412-08823bc2-c34e-440f-a602-9f5ccf7bf346.png)

Why can't I see the 0D3FE52068298E20BDD Mesh Identifier. It shows as 
`node//HERYrLAaI$v9uEpWHDBw76mn8kohHHwALdKjVe@zoGD2S8$QiGwyCIE8MaZ6MPPI"` instead. 

In this example it's a quiet server, but if I do this on a busy server it's hard to find an individual agent for troubleshooting.

**Comment by silversword411** [comment]
...unless I completely misunderstand what the Mesh Identifier is used for, and there's a different/better way for debugging connectivity issues :)

**Comment by Ylianst** [comment]
When doing debugging on my development server, I use this line in the settings section to block all agent connections except the agent I want:

```
    "agentAllowedIp": [ "192.168.2.147" ],
```

Of course, this is just for debugging.

More to your question, the device group identifier is used only when the agent connects for the first time. MeshCentral will place the new device in that device group. Of course after that, you can move to device to a different device group. So, the device group identifier in the .msh of the agent is not always reflective of what device group the device is in right now.

Let me know what you need to debug. There is no way to filter tracing on nodeid or device group id right now, but could be added if needed.

**Comment by silversword411** [comment]
If the mesh identifier in the client is unique per machine, it would be nice if that showed in the trace. 

Should I leave this issue open for that enhancement request?

**Comment by silversword411** [comment]
Note to future self. mesh agent ID and trace ID...you have to base64 translate. Would be nice to have both use same format
