### ISSUE TITLE
Feature Request: More strict and granular 2 factor options

### ISSUE THREAD

**Issue by getut** [Ylianst/MeshCentral#3561]
I think maybe there are some major holes in 2 factor that need to be filled. It seems like 2 factor auth devices need to be enrolled and assigned by centralized admin rather than users. In it's current state there is nothing to prevent a user from buying their own 10 pack of FIDO2 devices and plugging in them in a leaving one in every device they might potentially use. This really defeats a large portion of the reason for having them.

Also, it seems like there needs to be a way to enforce 2 factor at a group level. I asked a reddit question and got support on getting forced2factor enabled (Thank You!), but in many instances there would need to be a way to disable or enable 2 factor auth differently depending on group. For example, in our usage model we have local, direct employees that would preferably have only a SINGLE fido key pre-enrolled and assigned to them by IT (preferably wireless so that it doesn't tempt them to connect to the laptop and leave it there) . While remote, contracted support personnel via a company with very high turnover is allowed to use email 2 factor. But both groups are restricted to only that single type of 2 factor and when hardware is involved, have it enrolled and assigned centrally.

**Comment by Ylianst** [comment]
Hi. First, in addition to the `forced2factor` setting, you can also use `skip2factor` like this:

```
        "force2factor": true,
        "skip2factor": "127.0.0.1,192.168.2.0/24"
```

So, for internal devices, you can skip 2FA if you like. I will also note it's not generally possible to setup 2FA on behalf of users. They have to setup the second factor is such a way that no-one else could. Even buying a 10 pack of FIDO keys does greatly increase the security of the account since it's a proof of knowledge (password) plus a proof of possession (FIDO2). If you get a key stolen, you can always revoke it on the site. Hackers would need to get a key and guess the password which is difficult and the attack can't scale.

I am also a bit skeptical about having different 2FA policies for different users. Hackers will not discriminate when trying to hack an account, this is generally an equal opportunity event. Everyone is equally at risk. I am not sure why some users would get a pass on a security, seems organizations would stick to a single high bar everyone would need to meet.

Your asking for a lot of work and I am not super sure it would be worth the effort. I do have an alternative however. MeshCentral supports OAuth and SAML logins. So, you can use your own login portal in front of MeshCentral and get the benefit of central account management of your users across many applications. I have a video on how to [setup JumpCloud here](https://www.youtube.com/watch?v=LABuP_dWUO8). The great thing about this is that you get to setup 2FA and account security thru the login portal you prefer.

Let me know if that works for you.

**Comment by getut** [comment]
I can only speak to our usage model here, but I would guess there are plenty more orgs that would be in this scenario. When we get this rolled out, we will have approximately 20 users in our org with fairly high or complete access to the machines and a fair number of people who are remote workers who will have complete access to machines behind our corporate firewall. For those 20 it is my hope to centrally assign them a single hardware token that should never be left in the PC. If it is lost or stolen they would then be FORCED to contact IT to shut down the old one and provision them a new one. Having access to a single token would also limit their ability to leave it in a machine somewhere where both the machine and key would likely be stolen together as a group. I think users will eventually figure out that they can buy more tokens themselves and enroll them themselves and just have them stuck permanently in every device they use where if the device is stolen the bad guys have the token also.

As for group access, we are in a situation where we have a remote support group who has severely curtailed privileges and low pay, inexperience and thus very high turnover. They are also half a continent away. They will have limited access to a subset of our machines but none behind the corporate firewall. Only satellite sites that we pay them to help with 24/7/365 remote user support. The realities of it is that they would not accept the overhead of us forcing them to use and manage hardware tokens for over 400 workers that cycle in and out over 3 work shifts, weekends and holidays to get 24/7/365 coverage. To allow them access, email 2 factor is the only real choice. If we have no granularity with the groups, then it forces us to enable email 2 factor for everyone.

Obviously this isn't a deal breaker, but is exactly the reasons that I put it in as a feature request or future enhancement to cover these types of scenarios.

**Comment by getut** [comment]
Thinking about the centralized management a little more, it may can be handled with a little tweaking almost completely on the interface side by setting a max number of hardware keys that can be registered and then locking out the ability to add more or even to remove the existing one unless an admin unlocks/opens the interface. But in our situation, that still wouldn't help much unless we were able to set those settings per user group instead of across the entire server. Otherwise if a user lost a hardware key, they would likely just switch over to email2factor without even notifying IT if it had to be enabled to support another group such as the remote support example.

**Comment by Ylianst** [comment]
If you want me to add a "maxfidokeys" setting, I can do that. I need to translate your use case into reasonable implementation.

In general, I think you should really look into a centralized login portal for all you employees using SAML or OAuth. Employees should be able to login once and use their credentials to access many other services than MeshCentral. Like Azure domain, JumpCloud... These are products that specialize in account management and authentication.

**Comment by getut** [comment]
For my contracted remote support team we have no single authentication source in common other than the remote control tools themselves. Plus we are not delegating any ability to that team to add their own user accounts, so tying in their authentication system to ours would not help.  Maxfido keys would help us only in the situation where we have the ability to make the remote support team use email2factor only with no other options available, and direct employees able to use fido keys with no other option available.

As for your max fido keys, even if you don't see it feasible to do the "per group" configuration of available 2 factors types, is it possible to do the max fido keys with one additional setting?

In addition to max fido keys, have a toggle available to admin level that locks or unlocks the table that stores those fido keys. If we had the ability to limit it to 1 only, but could then also lock the table to its current state. It would give us control over when keys are added or removed.

**Comment by getut** [comment]
After even more thought on this, I think the learn mode may be a workable solution all by itself if it could extend to all 2 factor methods instead of just FIDO. I had requested the ability to set one group to email2factor only and another to a single FIDO device only... but if the "learn mode" affected everything, not just FIDO, the end result could be tailored to fit both needs.

Basically unless the admin has opened up learn mode briefly, accept no changes to any form of 2 factor enablement or disablement and the system could be used in a way that meets all of those needs.

**Comment by getut** [comment]
As requested, a cleanup of what we'd like to see based on the above:

2 new code items would be needed:
1) A checkbox that works at the entire server level that either locks or unlocks the 2 factor options in whatever state they are currently in making no change possible. If a user has a single FIDO 2 hardware device, they will not be able to enroll any other device, nor will they be able to enable any other form of 2 factor auth.
2) A config option to disable the backup codes and the nag message that goes with them

These will used to have the end result of making users use a single FIDO token, that if lost requires IT to get involved to open it back up so that a new token can be enabled. This will help IT be aware of any potential security issues from lost accounts or lost FIDO2 devices.

**Comment by Ylianst** [comment]
I forgot to mention it, but I added and released a 2FA lock in the last version of MeshCentral. In the "PasswordRequirements" section that is in the domain section of the config.json, you can add this:

```
      "PasswordRequirements": {
        "min": 8,
        "max": 64,
        "upper": 1,
        "lower": 1,
        "lock2factor": true                         <----
      }
```

The `lock2factor` will indicate the initial state of the 2FA lock when you start the server. By default it's self to `false` and 2FA setup is not locked. Now, you can go in the server console and use the `2falock` command to check the state and lock/unlock 2FA setup.

![image](https://user-images.githubusercontent.com/1319013/152588849-7d85e920-8092-45d9-8dc3-75b791e6f956.png)

Let me know if this works.

**Comment by getut** [comment]
This looks good so far. Closing. Will add a new request for disabling the nag screen if only a single 2 factor type is implemented.
