### ISSUE TITLE
mouse disabled with Mesh Assistant after some double click

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3564]
I'm using MeshCentral Assistant with Consent (Permanent Login App) and without MeshCentral Agent.
After obtaining the user's consent, if I do some double clicks with the left button (while moving the mouse), the left button click seems to do a right click.
Immediately the mouse no longer acts on the remote computer.
The mouse no longer acts on the local computer either.
You have to do a CRTL+ALT+SUP or click on one of the icons located next to the time for another application to appear in the foreground. Then the mouse becomes operational again.

This all happens with the latest version of the helper (with the -help option) and remote PCs on Window 10.
can you help me?

TightVNC is also installed on remote computers
I will do some tests by removing TightVNC on Monday

**Comment by pascal-chag** [comment]
this seems to only happen with double left clicks on the desktop

**Comment by Ylianst** [comment]
I see the same problem, working on it now.

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.9.76.

**Comment by pascal-chag** [comment]
it works perfectly.
Thanks for the quick fix
