### ISSUE TITLE
Featured Request - More information in My Device Tab

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#3566]
Hi Everyone,

Its possible enable a another columns into My Device Tab, like:

- CPU Usage
- RAM Usage
- Disk Usage

Regards,

**Comment by Ylianst** [comment]
You can get CPU, RAM and Temperatures in the details tab by hitting the graph icon on the top right.

![image](https://user-images.githubusercontent.com/1319013/151647614-87843c59-45fa-4231-9e08-0c282f2b4a48.png)

I do need to add disk usage. to the details tab, that would be a really nice addition.

The problem with CPU/RAM usage in the "My Devices" tab is that for some, this tab contains 1000's of computers and displaying real-time data like CPU/RAM would not work well. So, not sure how to arrange this.

**Comment by FrankSanabria** [comment]
I understand... maybe limit devices, for example, only can show in realtime 100 devices in "My Device Tap",  (Need filter first, maybe using group filter G:mygroup)

**Comment by lexisman** [comment]
I noticed that the temperature is also shown, is there anything that I should enabled in the server so that the temperature will also show? I do not see it under details in any of my agents, either it is windows or linux. Thanks.
