### ISSUE TITLE
Include RAM & Storage information in Export Device details

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3568]
@Ylianst - Thanks for incorporating all the requests and we appreciate your hard work behind this sweet project.

The device Details tab contains the RAM and Storage details, But i am managing more than 9K devices throgh Meshcentral and difficult to check them one by one. Can you include the same in the export button too ?

**Comment by jamgrorg** [comment]
+1

**Comment by VINISHVV** [comment]
@Ylianst - Can you check it once ?
