### ISSUE TITLE
MeshCentral Assistant Screen quality

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3569]
The screen display quality is worse with the MeshCentral Assistant than with the MeshCentral Agent.
Even if the quality and the refresh rate are at the maximum of the 2 coasts
![Mesh_Assistant_VS_Agent](https://user-images.githubusercontent.com/95504809/151780679-9f4558b6-3d89-4fb2-b820-ee9d0a4e3313.png)
.

**Comment by JSuenram** [comment]
Did you configure 
"AllowHighQualityDesktop": true
in config.json-Domain-Section?

Maybe the Assistant is ignoring some quality-settings....

**Comment by pascal-chag** [comment]
I just tried it, it doesn't change anything.
Thanks anyway.

**Comment by Ylianst** [comment]
I can confirm, seems like MeshCentral Assistant is ignoring the quality setting. Working on a fix now.

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v0.9.76.

**Comment by pascal-chag** [comment]
it works perfectly.
Thanks for the quick fix
