### ISSUE TITLE
BUG: Flickering Cursor on Remote Clients Desktop

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#357]
Our clients have been reporting a flickering cursor when we remote in to their Windows 10 Desktops. We were able to replicate the issue with a windows 10 laptop here at the office.

**Comment by Ylianst** [comment]
I am not sure we can do anything about this as the cursor is removed when we take a screenshot of the desktop. However, if other remote desktop tools have found a way to not flicker, maybe we can do the same. This is one request for Bryan.

**Comment by UnP1u9** [comment]
Hi, there is a tool anydesk, same issue is not seen there.

https://anydesk.com/en/downloads

**Comment by johnnyq** [comment]
Also check out remotely it is opensource and similar to meshcentral, it does not display the same issue

[](https://remotely.lucency.co/)

**Comment by rjt** [comment]
Happens on Win7 clients as well.

**Comment by vitko-bg** [comment]
Jumping and flickering cursor happens to me also.
MeshCentral server: 0.5.1-a (also on older versions)
Meshagent installed on: Win 10 Pro x64 1909 on VM on Hyper-V
Steps to recreate:
1. RDP to client computer (let's say working from home on a VM)
2. Login to same computer via Meshcentral - Desktop.
3. On RDP session cursor on moves jumping and flickering and does not know where it is :)
4. Disconnect MeshCentral Desktop session - all cursor movements are fine on RDP session.

**Comment by ryanblenis** [comment]
While this is being revived, I also see this issue. Interestingly the latest issue was a user called back after disconnecting and said the mouse was still flickering. Reconnecting and disconnecting still did not solve the issue. Restarting the MeshAgent service did fix the issue. (Win 10 Pro 1903 x64). No RDP'ing involved in the process.

**Comment by canove** [comment]
Same here. 

It only occurs when someone is using computer through RDP, and I connect to same RDP tunnel. Both in Windows 10 and Windows 7 agents

**Comment by vitko-bg** [comment]
Same for me. Client is Windows 10 x64 with no RDP, direct connection via Agent. From long time ago wanted to report this, but now looks like it is not only me who have this problem..... 
Please fix this...

**Comment by afabozzi** [comment]
I am experiencing the same issue.  I noticed if you adjust the frame rate it will blink faster or slower depending on the selection.  Would be nice if it did not blink but thought I would mention my findings.

**Comment by vitko-bg** [comment]
MC version 0.6.5 running on Debian
Agent OS: Windows 10 Pro x64
Agbent version: Latest with MC version
Mouse pointer on client PC is still flickering when operator is connected ........

**Comment by kkfl** [comment]
Is there any update on this blinking cursor issue?

**Comment by vitko-bg** [comment]
@Ylianst - looks like this issue is still ongoing for more that a year.
Can someone look at it please?
Thanks.

**Comment by krayon007** [comment]
> @Ylianst - looks like this issue is still ongoing for more that a year.
> Can someone look at it please?
> Thanks.

I understand it's been over a year, but this particular issue cannot be resolved without doing a complete rewrite of the feature to use a different capturing API. This will take time, as there are other higher priority items at the moment. But I am working on it.

**Comment by johnnyq** [comment]
@krayon007 We know you are and we appreciate your hard work =]

**Comment by krayon007** [comment]
The other aspect that is slowing it down, is that the MSDN documentation of the API is pretty terrible, so I'm having to piecemeal the samples together to get it to work in the agent's environment.

**Comment by vitko-bg** [comment]
Thanks :) Appreciate all your hard work.

**Comment by si458** [comment]
PLEASE FOLLOW #3663 FOR UPDATES
