### ISSUE TITLE
Mouse emulation in remote desktop on iPad

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3572]
I'm a big fan of the mouse emulation in the iPad's Remote Desktop app.

In this mode you can move the mouse of the remote machine by swiping your finger over the display. This allows much finer control than "trying to hit that small button with your finger".

Tap means left mouse click, two-finger-tap means right mouse click.

I'm curious if that would be possible in MC as well?

**Comment by jacotec** [comment]
@JSuenram The browser does :-)
In Guacamole I can set the mouse mode in a way that I can move the mouse pointer around by swiping with my finger over the display of my iPad or iPhone ... in the normal Safari browser.

**Comment by JSuenram** [comment]
> @JSuenram The browser does :-)
> In Guacamole I can set the mouse mode in a way that I can move the mouse pointer around by swiping with my finger over the display of my iPad or iPhone ... in the normal Safari browser.

Ah ok. Didn't know that Safari can do this. I will have a look, if it is just some client-script to tell the Browser to offer/use it....
@Ylianst pls assign me....

**Comment by si458** [comment]
Duplicate https://github.com/Ylianst/MeshCentral/issues/3816 https://github.com/Ylianst/MeshCentral/issues/1393
