### ISSUE TITLE
[Bug] Zipping files with cyrillic symbols in file names

### ISSUE THREAD

**Issue by SEsternO** [Ylianst/MeshCentral#3573]
Issue with using compressing functionality in Files tab.

- zipping files with russian (and probably other non-UTF8) file names causes file names to become unrecognizable.
- zipping catalogs with russian names makes zip files unable to open at all in built-in windows zip viewer (still can open them with 7-zip).

![изображение](https://user-images.githubusercontent.com/8999994/151937311-ad3dfca4-95b8-4d56-8f9b-06e7a89ad372.png)

Server 0.9.76.

**Comment by krayon007** [comment]
Was the zip generated by a windows agent or a Linux agent?

**Comment by SEsternO** [comment]
@krayon007 it was generated with windows agent, but as I saw your reply I tried it on linux agent, and file names are still unrecognizable.

**Comment by krayon007** [comment]
Ok I fixed this, it will be in the next agent update. I just needed to set a flag in the bitmask to indicate UTF8 encoded filenames.

**Comment by Ylianst** [comment]
This will be in an upcoming version of MeshCentral that has new agents. Not sure when it's going to be, but hopefully next week.

**Comment by SEsternO** [comment]
Just tested it in 0.9.81 with agent _Feb 12 2022 1547156988_, and the issue seems to be fixed. 
Thank you very much!
