### ISSUE TITLE
[Enhancement] Split links for "altmessenging" to use JWT Authentication for Jitsi

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3575]
Do you see a way to optional "split" the altmessaging link for the local and the remote side?

The background is:
As I don't want to have my Jitsi server world open, I'm using JWT auth. So my side should open the room with the JWT token, which authenticates me and gives me moderator rights.
But the remote side, once working again, should not know the token and should open the room without it (as it's already opened by me).

Something like:

```
      "altmessenging": {
        "name": "Jitsi",
        "localurl": "https://jitsi.myserver.de/Support-{0}?jwt=eyJhbxxxxx...",
        "remoteurl": "https://jitsi.myserver.de/Support-{0}"
      },

```

**Comment by Ylianst** [comment]
Good request, working on it now.

**Comment by Ylianst** [comment]
Ok, will be in MeshCentral v0.9.77. Looks like this:

```
      "altmessenging": {
        "name": "Jitsi",
        "url": "https://meet.jit.si/myserver-{0}",
        "localurl": "https://meet.jit.si/local-myserver-{0}"
      }
```

If only `url` is specified, that url is opened on both side. If `localurl` is present, that one is local, and `url` is remote. Hope that works.

**Comment by jacotec** [comment]
Awesome! :-)
I'll test as soon as it's out ... need to check why #3574 is happening first (BTW, on two different servers)

**Comment by jacotec** [comment]
@Ylianst Works nearly like a charm, but it's a kind of wacky and the whole altmessaging has a bug ... and the bad thing is: I have no clue how to "grab" it.

During tests, sometimes the button(s) did not work at all (so neither a remote nor a local action when clicking). JSON is correct, server is restarted every time.

When the buttons did not work and I had the "localurl" line present, I needed to remote the "localurl" line to get the button going again. Currently I'm in a state where it does not work anymore when I just remove the localurl line. It's completely crazy and I have no idea right now how to further debug or reproduce it.

In the non-working state, clicking the button gives that error in the browser console:

```
       Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at altDeviceChat (VM4543:7411)
    at HTMLInputElement.onclick (?viewmode=10&gotonode=01eDw1oLbGL8XVgIqpYSfpXcIk9D3RnflFq3MupqNb2cpYgh@wME3IHdI2Qo6upu:1)
altDeviceChat @ VM4543:7411
onclick @ ?viewmode=10&gotonode=01eDw1oLbGL8XVgIqpYSfpXcIk9D3RnflFq3MupqNb2cpYgh@wME3IHdI2Qo6upu:1

```

This error was caught in the state, where I would *need* to add a "localurl" to get it going, but I had removed the localurl. Config of altmessenging is this in this state:

```
      "altmessenging": {
        "name": "Jitsi",
        "url": "https://jitsi.myserver.de/Support-{0}"
      }

```

Once I change it to this, the button works and the error is gone:

```
      "altmessenging": {
        "name": "Jitsi",
        "url": "https://jitsi.myserver.de/Support-{0}",
        "localurl": "https://jitsi.myserver.de/Support-{0}"
      }

```

When I remove the "localurl" again and restart the server, the error is back.

Looks like something is stored somewhere outside the config.json which survives service restarts and causes this strange state.

**Comment by Ylianst** [comment]
Arg! I need to check this tomorrow.

**Comment by Ylianst** [comment]
Put in a fix for this, will be in MeshCentral v0.9.78.

**Comment by jacotec** [comment]
@Ylianst I'm sorry to say, but .... nope.

The browser error is gone, therefore localurl is ignored and the standard url always opens on both sides.

Test config:

```
      "altmessenging": [
        {
          "name": "Cloud Public",
          "url": "https://cloud.myserver.de/s/Ry6zxxxxxxxxxxx",
          "localurl": "https://google.de"
        },
        {
          "name": "Cloud Upload",
          "url": "https://cloud.myserver.de/s/Dc4xxxxxxxxxxxx",
          "localurl": "https://google.de"
        }
      ]
```

This should open the cloud link on the remote and Google on the local. But always the normal "url" is opened on both sides, including local.

BTW: As you need to touch this again, one thing: It would be great if

`"localurl": ""`

would suppress opening anything on the local side. Background: In remote support we often need to open a cloud link in the browser on the other side to download some internal tools. It would be great to have this on a button, but without opening the window also locally (as we only need it on the remote side).
I guess it's only a very small change (maybe it already works ...) ;-)

**Comment by Ylianst** [comment]
Oh, good idea. Adding support for `"localurl": ""` now.

**Comment by Ylianst** [comment]
Added it, will be in MeshCentral v0.9.79.

**Comment by jacotec** [comment]
@Ylianst Awesome! Did you find the issue as well?

**Comment by Ylianst** [comment]
Yes, but please text it and make sure it works.

**Comment by jacotec** [comment]
@Ylianst I've updated to 0.9.79 and unfortunately "localurl" is still fully ignored. Same issue as described 5 posts above.

**Comment by jacotec** [comment]
@Ylianst Just want to ask if you plan to fix this at some point? ;-)

**Comment by dinger1986** [comment]
@si458 i believe this has been fixed

**Comment by si458** [comment]
closing as stale and was fixed, please reply if still having issues
