### ISSUE TITLE
Feature request: Add Ctrl+Alt+Del and keyboard in mobile desktop mode

### ISSUE THREAD

**Issue by callimmak** [Ylianst/MeshCentral#358]
Hi.
Good work and thankd for this. 

Can you insert the command keys like ctrl+alt+canc and visualize the keyboard when i open the remote desktop from mobile phone or Tablet? 

Thanks

**Comment by Ylianst** [comment]
What is the "canc" key? I am not familiar with this key sequence.

**Comment by callimmak** [comment]
I'm sorry, canc is del. 
Ctrl+alt+del for unlock the rdp session.

Thanks

**Comment by MailYouLater** [comment]
| Desktop | ![image](https://user-images.githubusercontent.com/1279475/61554752-8d674780-aa12-11e9-95bc-947650dcf666.png) |
| - | - |
| **Mobile** | ![image](https://user-images.githubusercontent.com/1279475/61554710-6d378880-aa12-11e9-9491-8d99dba88a1e.png) |

**Comment by Ylianst** [comment]
Oh! I see, you just want to same on the mobile app... hold on! working on it!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.8-f with a early alpha super experimental soft keyboard support. I also added the ctrl-alt-del button.

**Comment by MailYouLater** [comment]
Can you add the other key sender portion too? For keyboard shortcuts and keys that most phone keyboards don't have. (e.g. <kbd>Tab</kbd>)

**Comment by Ylianst** [comment]
Ok. I am running out of space on the screen when looking at the web application on a mobile phone... lets see what I can do.

**Comment by Ylianst** [comment]
Ok, I replaced the "CtrlAltDel" button with a "Special" button that has a drop down with lots of keys including CTRL-ALT-DEL. Will be in the next published version.

![MC2-Mobile-Keys](https://user-images.githubusercontent.com/1319013/61737918-0aa9f980-ad3e-11e9-9caf-a9607069ce7e.png)

**Comment by MailYouLater** [comment]
Great!  To be honest, I think including <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd> in the drop-down of key combos is the way to go for the desktop interface too, I mean realistically it's a key combo, just like the rest.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-k with the special keys in the mobile app. Also improved [user permission editing in device groups](https://twitter.com/MeshCentral/status/1153766800703676417).

Interesting suggestion. I just made that change and merged "Ctrl-Alt-Del" in the desktop app and removed the separate button. It will be in the next rev.

**Comment by MailYouLater** [comment]
I'm not certain "Special" is the right term for this, as it doesn't really inform the user that it's for keyboard combos, but I can vouch that the functionality of it works perfect for me, both in desktop and mobile views.

**Comment by Ylianst** [comment]
Agreed that "Special" is not right. Any suggestions? I will accept any reasonable alternative.

**Comment by MailYouLater** [comment]
I've been thinking about this, and to be accurate it should be something like "Keyboard Shortcuts", "Key Combinations" or "Send Keys", but it could be shortened (since screen real estate is in short supply on mobile) to "Key Combos" or just "Keys", but while "Keys" conveys the meaning, and is short... you're already using "Keys" for the experimental keyboard input (which doesn't work right for me, but that's a different issue).  Maybe that should be renamed to "Keyboard" or "Input" or ... something.

**Comment by Ylianst** [comment]
Ok, I will make another attempt at this next time I can.

**Comment by MailYouLater** [comment]
What would you think of tackling both functions at once by implementing a full keyboard in web technologies like [this "JSVirtualKeyboard" from Microsoft](https://support.microsoft.com/en-us/help/2555357/how-to-build-a-virtual-keyboard-in-an-html-page) or [this Virtual Keyboard implemented in jQuery, maintained by mottie](https://mottie.github.io/Keyboard/)?

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-v with changes to the remote desktop buttons. I freed up space by replacing the "toast" button with the notification icon like a new on the desktop version. Gave me more space to use proper button names. Hope this works.

![x](https://user-images.githubusercontent.com/1319013/62094243-460e6180-b231-11e9-89a0-783b8a63f90d.png)

**Comment by Ylianst** [comment]
In response to @MailYouLater, I am not going to use a HTML keyboard since mobile devices have a functioning one if already configured to the user's preference. Best stick with that.

**Comment by MailYouLater** [comment]
Honestly, I hate how most mobile PC remote control systems don't supply their own keyboard and only allow using whatever soft keyboard your device has installed.  Obviously, if you can provide a functioning input that uses the main keyboard, that's great, but there are so many things that just don't work the same on a mobile keyboard, and a real PC keyboard.

[This keyboard](https://user-images.githubusercontent.com/1279475/62168290-0485c100-b2da-11e9-95ef-c7a5224daae9.png) may be fine for texting with your friends, a PC power user loses _so much_ functionality when they try to control a computer with it, seriously, how am I supposed to push <kbd>Tab</kbd>, or <kbd>Alt</kbd>+<kbd>Print Screen</kbd>, or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd>.  Even if all of the things you can do with a real PC keyboard were to be added to the "Special Keys" list, that would still not be preferable, as then we'd have a _huge_ list to go through, when it could be as simple as importing [these](https://mottie.github.io/Keyboard/docs/layouts3.html), tweaking them to match their physical counterparts, and letting people use that if they like.

Anyway, I suppose this issue it done, and should probably be closed, but it just seems like an HTML keyboard would be a really nice addition for later.

**Comment by Ylianst** [comment]
Going to close this issue. However, if a new feature is requested, please open a new issue. I could look at an HTML keyboard for special keys, but given the current work load, it will take a long time to get to.
