### ISSUE TITLE
fork and build

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3583]
Hi,
is there any guide for how to build on github after fork for the server and other components, e.g. assistant, agents or and router ?
or do we have to clone locally, then build there? what tools to use?

**Comment by Ylianst** [comment]
There are no guides for that. For MeshAgent, MeshCentral Assistant, MeshCentral Router: you build them and put the binary in the /agents folder of MeshCentral. We currently use Visual Studio 2015 with NodeJS add-on for everything.

**Comment by JSuenram** [comment]
> Hi,
> is there any guide for how to build on github after fork for the server and other components, e.g. assistant, agents or and router ?
> or do we have to clone locally, then build there? what tools to use?

Use Visual Studio 2015 (free Version is enough) add node.js and clone the GIT. It just works with local debugging and so on after that....

For small changes I also use Visual Studio Code on MAC, which also works and can run/debug the hole Server-Part.

**Comment by smartekIT** [comment]
thanks heaps guys.

**Comment by JSuenram** [comment]
> thanks heaps guys.

If your question is answered, please close issue here. 

Thank you....
