### ISSUE TITLE
Docker image has an old version of Node

### ISSUE THREAD

**Issue by poiNt3D** [Ylianst/MeshCentral#3586]
Some features of MeshCentral require newer version of Node.
Right now provided docker image (einar/meshcentral) has 10.19.10, which is very old and no longer supported.
I've connected to my container and tried to update it, but after installing current LTS, MeshCentral has failed to run.

**Comment by rallisf1** [comment]
I am using uldiseihenbergs/meshcentral, it's kinda slow on updates (once per month) but I just did a pull request to latest 0.9.77 on which I also switched to current node LTS (16) as it was on 14, which still works tbh.

**Comment by poiNt3D** [comment]
> I am using uldiseihenbergs/meshcentral, it's kinda slow on updates (once per month) but I just did a pull request to latest 0.9.77 on which I also switched to current node LTS (16) as it was on 14, which still works tbh.

Unfortunately, it's not actually a drop-in replacement. I have my infrastructure already configured and changing the image causes some new problems with existing Nginx configuration. Maybe i'll consider switching in the future, but it's too much pain to redo everything step-by-step.

**Comment by Ylianst** [comment]
There is currently no official Docker image for MeshCentral. At some point, I may work on one, but for now, you have to contact the author of the docker image your using to get any changes done.

**Comment by rallisf1** [comment]
> 
> Unfortunately, it's not actually a drop-in replacement. I have my infrastructure already configured and changing the image causes some new problems with existing Nginx configuration. Maybe i'll consider switching in the future, but it's too much pain to redo everything step-by-step.

As long as you have the same port mappings and copy your config and theme overrides to the new volume it should work by just stopping one container and starting the other and if not you can always switch back literally in seconds.

**Comment by poiNt3D** [comment]
> There is currently no official Docker image for MeshCentral. At some point, I may work on one, but for now, you have to contact the author of the docker image your using to get any changes done.

Oh, sorry, i didn't know. My thought was, if it's mentioned in the repo's compose file - it's official. Thanks for you feedback, and awesome software, of course!
