### ISSUE TITLE
redirect LoginPage -> SSO  "/" -> "/auth/saml"

### ISSUE THREAD

**Issue by theoneandonly-vector** [Ylianst/MeshCentral#3588]
can we redirect the root -dir  "/" -> "/auth/saml" without using a reverse-proxy?

**Comment by Ylianst** [comment]
Yes, take a look at [this setting](https://github.com/Ylianst/MeshCentral/blob/2e4288cda0e9921b8a6b44779f034d7e97833c29/meshcentral-config-schema.json#L302). In the domain section of the config.json, add this:

```
"unknownUserRootRedirect": "https://mysso.sample.com/"
```

If a user that is not already logged in goes to the root of the MeshCentral server site, they get redirected to the specified URL. It's used exactly for your usage. Let me know if it works.

**Comment by theoneandonly-vector** [comment]
thx :)
