### ISSUE TITLE
Is there any scope to use IntelAMT technology and wake on LAN as part of the tool?

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3593]
Dear @Ylianst ,

1) Is there any scope to use IntelAMT technology and wake on LAN as part of the tool?
2) Whether number of sessions to same machine is configurable? This helps to avoid load on the agent since multiple session may lead to high CPU.
3) Have we tried port forwarding option to use for device access using RDP/Telnet/SSH, etc.
4) Do we have on-demand link generation so that specific user can be given access of end machine on-demand for shorter duration?
5) Do we have SSO enabled in the tool including SAML/O-auth?

**Comment by JSuenram** [comment]
I am not sure if I understand all your Questions cause this is readable in the Docs and in several Videos. You should just habe a look.

Anyway:
1. Yes
2. For Windows the Agent is really not a CPU-Problem even with 2 or 3 Users on the same Session. Never tested with more.
3. Works
4. Sure absolutely
5. As far as I know, this is possible but has to be answered by someone else how knows this.

**Comment by Ylianst** [comment]
All exactly right.

1. When you go on a device and hit the "Action" button and select "Wake up", MeshCentral will use both WOL packets from the server and other agents, and/or Intel AMT wake if available. So yes, it's implemented now and should work.
2. If by number of sessions, your talking about remote desktop sessions... you can turn on the desktop multiplexor. This will have a single remote desktop session at the agent and the server will "split" the the session to all the viewers. [Look at this video for details](https://www.youtube.com/watch?v=r0IfzuZgf3s).
3. Yes, [check out this video](https://www.youtube.com/watch?v=BubeVRmbCRM).
4. Yes, [check out this video](https://www.youtube.com/watch?v=qHJuXwiV-XU).
5. Yes, [for example, this video](https://www.youtube.com/watch?v=LABuP_dWUO8).
