### ISSUE TITLE
Kaspersky feedback regarding warning classification - open for discussion

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3594]
@Ylianst @krayon007 
I've reported false positives for the agent to Avast, Sophos and Kaspersky to get the warnings solved. Avast and Sophos confirmed that the agent is not malicious and that it would be removed from the list, Kaspersky always issue a warning that the agent is classified as "not-a-virus: remote agent" which might distract users/customers ("Yellow" alert).

Asking them why Teamviewer and Anydesk does not receive such a warning they answered:

> MeshCentral allows to create pre-configured installer of MeshAgent. To gain control on victims machines, an attacker just need to convince target user to download and execute it. So, we detect Agent service as not-a-virus:RemoteAdmin to warn users about potential attack.
> 
> TeamViewer and AnyDesk software don't provide such features and usually attackers use patched versions of these software, which we also detect.
> 

This sounds pretty reasonable to me. I've asked them what kind of behavior they would expect and provided two ideas I have to get a bit more security for the end user:

> Dear ******,
> 
> thank you for your explanation. That sounds reasonable to me. Although TeamViewer Host does pretty much the same.
> 
> I would like to give feedback to the project so they can get around this issue in a next version of the agent.
> 
> What behavior or additional actions would you / Kaspersky expect to not tag it with the warning? Thoughts on my side:
> 
> •	An additional warning / message before the first connection to the server that, with the connection, the named server will gain remote control over the PC running the agent. The user must confirm this before connecting.
> 
> •	or: The agent creates a random PIN/Password which the remote user must pass to the controlling guy for the very first connection. The controlling party must enter this PIN/Password they got from the customer to unlock the agent for being connected (this is a bit the "Teamviewer way")
> 
> Your feedback is highly appreciated!

In many cases the assistant does it which has a very high security, but limited capabilities. So the agent definitely has its needs also for remote support.

I open my ideas above open for discussion. It would not harm to have a second confirmation level from the user side for the very first connection to the server once a machine/agent wants to connect the first time. Like a popup with a random PIN/password generated at the agent which must be passed to the server (together with some explicit explanation that by passing this PIN/Password the operator on the named server will have full control etc.). When the server wants to connect, this PIN/password must be known and entered by the operator, and the server will pass it to the agent. Once this matches, the agent is "unlocked" for this server and can be connected any time from then.

This method gives a very high security level as the client must actively communicate the password to the (known) operator before the agent is unlocked. The other way of an additional warning popup which must be confirmed is more or less "just another annoying click on 'yes'" for the user and far not that secure.

I think with a bit more "end unser confirmation" the repuation of the MeshCentral agent can raise massively.

**Comment by JSuenram** [comment]
Maybe we should close all "it is detected as Malware/PUA" etc etc issues and open a thread in "Discussion" about this, where the why, how and maybe prevention can be discussed...

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
closing as agreed, all AV ones will point to a discussion going forward, me thinks
