### ISSUE TITLE
Enable Discussions? 

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3598]
Just a question if it might be an idea to enable the Discussion-Module in GIT for MeshCentral.
Many topics are not really "issue" related but more questions about how does this or that work or about configuration or usage.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/68963439/152421946-66a47303-c9b8-459d-9421-ff57c2b08f6b.png">

Oh and btw. can I self assign Issues or is this a special "right" I need?

**Comment by Ylianst** [comment]
I did not know about this feature, just enabled it!

**Comment by JSuenram** [comment]
> I did not know about this feature, just enabled it!

Nice! I will try to have an eye on it, so people get there feedback fast and hope to not bother you to much.... ;-)

**Comment by rapi3** [comment]
Super.
Now it is time to move "old issues" there if possible.

**Comment by silversword411** [comment]
I'm happy to help tag issues and move stuff between issues/discussions just need the permissions for it :)
