### ISSUE TITLE
Desktop Shadowing

### ISSUE THREAD

**Issue by imposhster** [Ylianst/MeshCentral#36]
Not able to "shadow" the console/RDP user that is logged into the endpoint that you are attempting to connect to. For supporting endpoints/users this is critical.

**Comment by Ylianst** [comment]
I am ignorant on this topic, what is "shadow" in this context? Like, remote control without keyboard/mouse input? Let me know what is precisely needed. Thanks.

**Comment by imposhster** [comment]
Sorry for being vague @Ylianst . The idea is to be able to interact with the currently logged in user... similar to what LogMeIn, Teamviewer, Splashtop, etc. are doing.

Remote Desktop Protocol calls this shadowing: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shadow


So when I remote to a computer I'd like to see what the user that is logged in is doing, and be able to control their session as well.

**Comment by jsastriawan** [comment]
This is what Desktop is doing now. Whatever is displayed on the screen is what remote viewer can see. The way MeshCentral does remote desktop is that the MeshAgent takes screenshot, chops and compresses into small JPEG tiles and sends them to browser either throuh websocket relay or through WebRTC channel if can be established. So in theory, that is similar to shadowing.

Regards,


Joko

**Comment by Ylianst** [comment]
Ha yes, we are not starting a different remote session when doing remote desktop, just looking at the local session the user is using.

**Comment by imposhster** [comment]
Ah Yes, I looked again (i was testing while RDP'd to a session) and it does appear to grab the console session. That works wonderful. I will file a new "issue" to add support for selecting specific Session IDs to remote into. This issue can be closed.
