### ISSUE TITLE
Feature Request: Start a new process

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#360]
Add a new feature to allow to start a new process from the Desktop > Tools menu, at the moment i can only kill the process, but on the machines that run without explorer.exe i would like to be able to start it from the tools menu, without the need to run WIN+R on the machine.

**Comment by Ylianst** [comment]
Good request.

**Comment by MailYouLater** [comment]
It would also be nice if we could launch a process with a console command. e.g. `exec C:\Start.exe`

**Comment by Ylianst** [comment]
I will consult with Bryan on this. Right now, you can click the "globe icon" on the bottom right, enter "notepad" for Windows systems and notepad will run. It will run the app under the same permissions as the MeshAgent which may not be ok.

![MC2-OpenProcess](https://user-images.githubusercontent.com/1319013/61672003-c4518d80-ac9e-11e9-9e50-bb6a27b4c21d.png)

**Comment by MailYouLater** [comment]
OK... apparently that also works via the `openurl` console command. This certainly works, but I don't really like how it's basically hidden in a function that doesn't seem related.
I'd either separate it out, into it's own functionality, or I'd change the icon to something that indicates launching something, as opposed to the web, and I'd change the console command name to something like `exec`, `open`, or `launch`, and have the built-in help (when you run the command without any parameters) say something about accepting file paths, and web URLs.

**Comment by krayon007** [comment]
This should be pretty straightforward to add... You can already accomplish the 'exec' thing you mentioned by doing an eval with the child_process module..... But we can certainly add a console command to simplify it, so you don't need to eval a bunch of JS code...

**Comment by si458** [comment]
this feature now exists again sort of,
click the play button on the bottom right hand side,
![image](https://github.com/Ylianst/MeshCentral/assets/765314/0d91efbc-437d-4103-9b0d-74ddf9a7b35d)
you can specify if you want cmd or powershell
also specify to run as logged in user or the system agent user
specify command in text box or upload file,
then click run, and check the console tab for output run from the command
![image](https://github.com/Ylianst/MeshCentral/assets/765314/79a41903-2279-4430-8502-0354d744412e)
