### ISSUE TITLE
Disable the mobile page

### ISSUE THREAD

**Issue by theoneandonly-vector** [Ylianst/MeshCentral#3603]
I would like to disable the mobile-version of the admin page. is this possible smh?
the idea would be to have the same layout/look on all devices.

**Comment by Ylianst** [comment]
Sure, I just added a new option for this. You can put this line in the domain section of the config.json:

```
"mobileSite": false,
```

It will start working with MeshCentral v0.9.78. Once published, let me know if it works.

**Comment by theoneandonly-vector** [comment]
works :)
