### ISSUE TITLE
adding info the sysinfo results?

### ISSUE THREAD

**Issue by aktxyz** [Ylianst/MeshCentral#3604]
What is the best way to add some additional info to sysinfo? it looks like the meshcore.js code that handles sysinfo actually references some javascript that is embedded into the actual agent executable

https://github.com/Ylianst/MeshCentral/blob/45517db7dd92e60948c510c4336a10c5f997611d/agents/meshcore.js#L1663

**Comment by krayon007** [comment]
You can grab the JS file from the modules folder in the agent repo. After you make your changes, you have a few options:
1. Put the file in the same folder as the agent
2. Put the file on the server in the modules_meshcore folder, and the server will send it to the agent
3. I can show you how to use the clipboard module to compress the file to update the Polyfills.c file in the agent. 

Whatever option you choose, the agent will always use the one with the latest file-time.

**Comment by Ylianst** [comment]
So, yes, `require('identifiers')` is built into the agent executable. However, you can grab the implementation over override it with you own using different ways Bryan describes.

**Comment by aktxyz** [comment]
1. tried this and works great
2. tried this and works great also (after a rabbit hole where I was in the meshcmd folder by mistake !)
3. sounds really neat actually, but will play around with #2 for a while :)

thanks again !

**Comment by aktxyz** [comment]
I got some fresh data back via wmi (last boot time) ! 

One more question, what is the difference between these functions in meshcore.js ...  processConsoleCommand() and handleServerCommand(), many of the commands have case statements inside both of those functions.

**Comment by aktxyz** [comment]
this is so fun, I can now type "watchcpu" and get this in my console ...

```
cpu] 006% ######
[cpu] 012% ############
[cpu] 009% #########
[cpu] 004% ####
[cpu] 008% ########
[cpu] 004% ####
[cpu] 005% #####
[cpu] 011% ###########
```

**Comment by Ylianst** [comment]
Good question.

- `processConsoleCommand()` processes user typed commands that are entered in the agent "Console" tab. You get a command and arguments as text and return text back as output.

- `handleServerCommand()` this is to handle commands coming from the server. These command can come from "meshagent.js" or other parts of the server code. For these commands, we get a JSON as input and often return a JSON as output back to the server.

Often, we start by adding code as a console command to try it out. Once it works, we integrate the command with the server.

**Comment by Ylianst** [comment]
@aktxyz Looks great!!!
