### ISSUE TITLE
Disable "Reset Account" option?

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#3605]
Maybe I'm just missing it but I've looked through the config and schema and don't see this listed. Is it possible to disable the Reset Account link on the login page and if not, can such an option be added? I'm all for account recovery on less important systems but I'd prefer to not have that backdoor available on this particular system and instead reset forgotten passwords for users myself (especially since in the worst-case where my own account is locked out, I can reset it from the server directly). Thanks in advance!

Edit: I’m realizing that wasn’t phrased exactly as I intended. To clarify, I’m looking for a way to completely disable the account recovery feature (without disabling SMTP entirely), not just to hide the link on the login screen.

**Comment by JSuenram** [comment]
Sorry, can you post a Screenshot? I am a little bit confused cause my Testsetup and even our Live-System does not have this option shown on Login-Screen.... Just to clarify where I disabled it.....

**Comment by Ylianst** [comment]
I think this is the option that needs to be removed.

![image](https://user-images.githubusercontent.com/1319013/152493026-5fdbf28b-62cc-4710-b9ac-f3e93dc943f7.png)

**Comment by JSuenram** [comment]
Ok.... this does not exist on our local setup. That made me a bit confused...
Maybe I disabled it or it not shown when using LDAP? But even on my development-system with a local basic setup, this is not shown by default!?

<img width="408" alt="image" src="https://user-images.githubusercontent.com/68963439/152508564-189c7123-78aa-412c-af5d-1498cf263b0d.png">

**Comment by Ylianst** [comment]
The "Reset Account" option is only shown if you have a email server configured and your not using SSPI/LDAP authentication.

**Comment by Ylianst** [comment]
Just added in the code for this. In the PasswordRequirements section, that is in the domain section of the config.json, add this line:

```
      "PasswordRequirements": {
        "min": 8,
        "max": 64,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "allowAccountReset": false              <-------------
      }
```

This will work starting with MeshCentral v0.9.79 when it's next released.

**Comment by PetieM** [comment]
Seems to be working perfectly! Manually re-showing the link via inspect element and entering an email results in a "Not Found" which is exactly what I wanted to see. Thank you for the quick turnaround on this!
