### ISSUE TITLE
EVENTS Table no Session-Code when using Desktop-Multiplex-Mode

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3606]
Hi,
we are using data from the Events-Table to gather information about Remote-Sessions and how long they last for later usage in accounting.

Desktop, Terminal and File-Transfer all have a unique session ID in Json.MSG \"some code\".
When we enable DesktopMultiplex the msg.fiels has just "Started desktop multiplex session" or "Closed desktop multiplex session" without any code in MSG.

As we have only limited database fields in the target system for import we compare by time and sessionID if the event has already imported. 

This causes trouble if we use Multiplex-Sessions. 

So question: Is it possible that Multiplex-Sessions also get an Unique Code in the Events-Database?

**Comment by Ylianst** [comment]
OK, added it. Will be in MeshCentral v0.9.79.

![image](https://user-images.githubusercontent.com/1319013/152562769-c4fcf7a0-7427-4593-bb9f-a19a0939a3ca.png)

Let me know if that works.

**Comment by JSuenram** [comment]
I checked the change and it is working.
Small change in our code was needed. Other sessions write ",20 seconds(s)" while Multiplex writes "after 20 seconds(s)" in Event-Table but that is easy captured with RegEx. So I will close this! Thank you!
