### ISSUE TITLE
Sending invitation email when creating a new user

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#3611]
Hi,

When I create a new user, no invitation email is sent and the field "send invitation email" is grayed out. Where can I set that the invitation email is sent. Meshcentral version is 0.9.78
Thank you

**Comment by Ylianst** [comment]
Fixed bad title.

**Comment by VINISHVV** [comment]
@johann8

Please tick mark email verified option then only the 'send invitation email' gets activated

**Comment by Ylianst** [comment]
Right. Check both "Force password reset on next login" and "Email is verified" to enable the invitation option.

![image](https://user-images.githubusercontent.com/1319013/152862157-adcba771-d8ce-4431-82fe-cc2c3357f9af.png)

Let us know if that works.

**Comment by petervanv** [comment]
It would be nice if the new user verifies the mail, so it confirms the email, and after 30 minutes it should be inactive it not confirmed.

**Comment by Ylianst** [comment]
Just put in a fix for adding `?key=xxx` to the user invitation email. For other requests, please open other issues.

**Comment by johann8** [comment]
Build new docker image, it works!
Thank You!
