### ISSUE TITLE
Intel AMT configuration lost after SSD removal

### ISSUE THREAD

**Issue by sysadmin-us** [Ylianst/MeshCentral#3612]
AMT Device was configured in ACM mode with an agent, After removing the SSD from the AMT machine, AMT configuration was lost and not reflecting on the server. Can you tell me the reason is AMT depends on hardware based component SSD or HDD after provisioning? @Ylianst

**Comment by Ylianst** [comment]
Fixed bad (low quality) title.

**Comment by Ylianst** [comment]
Intel AMT does not depends on SSD or HDD and so, removing such components should be reset Intel AMT.

**Comment by sysadmin-us** [comment]
> Intel AMT does not depends on SSD or HDD and so, removing such components will NOT reset Intel AMT.

Thanks for the prompt response. Just need clarification that the device under discussion is Intel NUC11TNKi5 and that should also retain the settings on removal of SSD/HDD ?

**Comment by Ylianst** [comment]
Yes. Intel AMT does not store any information on SSD/HDD. Also, Intel AMT has no way to communicate with storage devices. All Intel AMT configuration is kept in platform flash.

**Comment by JSuenram** [comment]
@sysadmin-us 
If your questions is answered please close.
Thank you!
