### ISSUE TITLE
Include RAM & Storage information in Export Device details

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3616]
@Ylianst - Thanks for incorporating all the requests and we appreciate your hard work behind this sweet project.

The device Details tab contains the RAM and Storage details, But i am managing more than 9K devices throgh Meshcentral and difficult to check them one by one. Can you include the same in the export button too?

**Comment by Ylianst** [comment]
I imagine you are talking about exporting in CSV format. The problem with that format is that there is no flexibility if a computer has many storage devices, you have to put everything in one column. I can add a column for the total RAM, but not sure for storage.

The best is to export the device details in JSON format, then you have lots of details on all the devices. I would recommend using that format if possible.

**Comment by Ylianst** [comment]
Ok, added total memory:

![image](https://user-images.githubusercontent.com/1319013/153064477-0a69b8a7-49ab-408d-b858-7f4457854759.png)

Let me know if that works. For storage, use JSON or let me know the exact format you want.

**Comment by VINISHVV** [comment]
@Ylianst 
Thanks, The Json option is pretty powerful !!
