### ISSUE TITLE
config Parameter to disable Dark-Mode for all users

### ISSUE THREAD

**Issue by theoneandonly-vector** [Ylianst/MeshCentral#3618]
I would like to have a config-paramter to disable dark-mode for everyone.

**Comment by Ylianst** [comment]
Oh gosh. Ok, working on this now.

**Comment by Ylianst** [comment]
This will be in MeshCentral v0.9.80, in the domain section of the config.json, add:

```
"nightmode": 1
```

The values are 0 = User can select (this is the default), 1 = Force night mode, 2 = Force day mode.

**Comment by JSuenram** [comment]
@theoneandonly-vector 
I can confirm this is fixed. Pls close....

**Comment by theoneandonly-vector** [comment]
yes, it works 👍
