### ISSUE TITLE
Linux terminal stalls when attempting to "su" to someone else

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#362]
When accessing Linux using MC, you connect as root which makes sense considering the manner in which it's installed, but it would be great if we could then login as an alternative user. As soon as I connect, I've tried connecting as another user, but the terminal seems to stall when I run:
`su -s /bin/bash anotherUser`

(anotherUser is a valid user)

**Comment by krayon007** [comment]
If you click on one of your puppy clients, and click on console, and type 'info' and enter, what does it display?

**Comment by krayon007** [comment]
Specifically, I'm insterested in what it shows under 'X11 Support', if it says true or false. As well as what it says under 'capabilities'

**Comment by krayon007** [comment]
I tried it on various systems over here, it looks like it actually is working, it just seems the bash profile isn't processed, so that you lose the terminal prompt. However it seems it still accepts inputs, and shows the appropriate outputs... Can you verify if this is still true for you? I'll look into seeing why the terminal prompt is lost.

**Comment by Ylianst** [comment]
Would it be possible the command prompt environment variable is not set? In that case, the prompt is empty but the shell still work.

**Comment by UnP1u9** [comment]
Hi, shell works fine but Bash Prompt seems to be missing and also cant other shortcuts like CTRL+L and can't tab to finish commands.

command prompt environment variable is fine as i it works fine if we login to it physically.

**Comment by D4V3M0NK** [comment]
You're right ... it does appear that it's just the prompt that's missing...
![TerminalNoPrompt](https://user-images.githubusercontent.com/7572742/61548510-b7187280-aa02-11e9-8f17-a67c0f932d7c.png)

**Comment by Floche87** [comment]
Same issue for me.
Moreover command "cd" don't work in root. I have the message : bash: cd: « HOME » not defined

**Comment by krayon007** [comment]
cd to any folder doesn't work, or cd to ~ doesn't work?

**Comment by D4V3M0NK** [comment]
For me, using Ubuntu, all "cd" commands work just fine, you just don't see the prompt.

```
su -s /bin/bash myOtherUser

cd /var/www
ls -l (shows Apache document root)

cd ~
pwd (shows myOtherUser's home folder)
```


Obviously - this assumes that myOtherUser has a home folder defined (see /etc/passwd)

**Comment by krayon007** [comment]
instead of using the command: 
su -s /bin/bash myOtherUser

use the command:
su -c '/bin/bash -i' myOtherUser

It will display an ioctl error, but otherwise it seems to work correctly

**Comment by D4V3M0NK** [comment]
I totally agree, everything appears normal with the interactive switch.  I will wait to ensure that @Floche87 sees the same results before closing this, thanks for the hint Bryan.

Can I suggest that this is included within the documentation as I would imagine most users wouldn't think of invoking substitute user with the command switch, that command being to run bash in interactive mode?

**Comment by Ylianst** [comment]
I wonder where in the documentation would be the best place to put this... Looking into the User Guide now.

**Comment by Ylianst** [comment]
Ok, added an new "Annex 2: Tips & Tricks" with this in it. I will add more stuff like this in this section. Next time I update the document online, it will be there.

**Comment by Floche87** [comment]
@D4V3M0NK The command "su -c ..." is ok for me.
@krayon007 'cd /pathtofolder' and 'cd ~' work. But the  home folder isn't accessible with 'cd'. In a terminal it is ok.

**Comment by D4V3M0NK** [comment]
@Floche87 how are you attempting to access the home folder? I always use `cd ~` which you state works for you?  Are you using something like `cd $HOME`? (which also works for me)

**Comment by Floche87** [comment]
Yes.
On debian 'cd' (like cd ~) access the home folder

**Comment by D4V3M0NK** [comment]
@Floche87 ... I've just installed Buster on my VM environment and "cd" works for me as expected.  You're correct in that you still don't see the prompt (which I believe @krayon007 is working on) but the command itself works in my environment.  What version of Debian are you using?

**Comment by Floche87** [comment]
I use Stretch and Buster. Both have the same issue.
It is not fresh install.

**Comment by krayon007** [comment]
So, is using the -c and -i switch not resolving the issue for you?

**Comment by D4V3M0NK** [comment]
@krayon007 it is for me, but not for @Floche87

**Comment by krayon007** [comment]
@Floche87 , are you able to see the prompt with the -c and -i switch, just $HOME is not working, or are you not able to do either?

Also, is "cd ~" going to the same folder that you expect $HOME is supposed to be mapped to?
Also, which linux distro are you running? I'll setup the same distro, and see if I can't dig into this...

**Comment by Floche87** [comment]
@krayon007, with -c/-i switch,  i see the prompt and all is ok . "cd ~" and "cd" access my $HOME.
When i directly use the terminal of meshcentral (without su command), "cd ~" is ok but "cd" not.
Maybe is it another issue ?

**Comment by krayon007** [comment]
This thread is quite old, but this issue is actually fixed correctly with the latest version of the server. The underlying issue, was an issue with interactive mode on the terminal, because bash didn't like how I was redirecting stderr, so went into non-interactive mode if you did an su. This is now fixed with the current server, so you can use su like you normally would, and don't need to use the -i option on bash.

**Comment by D4V3M0NK** [comment]
Wonderful - thanks Bryan!
