### ISSUE TITLE
Any recommended fine-tuning settings on Meshcentral such as hearbeat to keep the session alive for longer duration, compression, framerate changes, etc.

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3620]
Dear @Ylianst ,
Any recommended fine-tuning settings on Meshcentral such as heartbeat to keep the session alive for longer duration, compression, framerate changes, etc.

**Comment by JSuenram** [comment]
Hi,
you should open a Topic unter Discussions for this as it is not an issue at all.
![image](https://user-images.githubusercontent.com/68963439/153202664-c1fddae5-cd41-4bf4-98c8-d87afa14adfc.png)

Please close here... Thank you...

**Comment by mdshoaibumer** [comment]
Sure thanks
