### ISSUE TITLE
Keyboard Entry in a VMWare Workstation guest running on the remote is not possible

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3621]
On my Windows 10 PC I have some VMWare Workstation VM's running, especially for some testing etc.

Controlling my PC via MC remote desktop works fine, and when I want to work in the VMWare window all mouse actions are working. But all the keyboard is doing nothing once I'm in the VMWare window and want to enter something into the VM guest.

Works fine with Teamviewer to my W10 PC, so it's not a general issue with my host PC or VMWare.

**Comment by axelandy** [comment]
Enabling remote keyboard map fixes this. ![remote_keyboard_map](https://user-images.githubusercontent.com/55218587/153436157-9c64b0e8-6a06-441c-a6c0-2dea7c020358.png)

**Comment by jacotec** [comment]
@axelandy That did it! Thanks! :-)
