### ISSUE TITLE
Two Factor Backup Codes Prompt

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#3632]
Since 0.9.79, I've been getting a notification to add two factor backup codes every time I log in (or even refresh the page). I have 2FA configured via an authenticator app and have backup codes generated (the site even shows a check next to the backup codes option) so I'm assuming it's just an issue in the logic triggering that notification.

As a test, I tried completely removing and re-adding my authenticator but the same behavior persists after doing so.

**Comment by JSuenram** [comment]
Mh, I have also enabled E-Mail-Authentication for 2FA and there is no such notification.
Can you try if you enable Email Authentication if that issue also exists?
![image](https://user-images.githubusercontent.com/68963439/153701484-ecc03615-90c5-4486-9aa4-d4dba39e6070.png)

You need to set Email-Config in your config.json to use it.

 "smtp": {
           "host": "smtp_server.domain.suffix",
           "port": 587,
           "from": "sender@donmain.suffix",
           "user": "username_if_needed",
           "pass": "password_if_needed:",
           "tls": false
  }

**Comment by PetieM** [comment]
That would most likely stop the errant notification (as you would have two authentication methods at that point) but it's still a bug in the sense that with one authentication method and backup codes, I shouldn't be getting that message.

**Comment by JSuenram** [comment]
> That would most likely stop the errant notification (as I would have two authentication methods at that point) but it's still a bug in the sense that with one authentication method and backup codes, I shouldn't be getting that message.

Absolutely, it's just for confirming where to look in the code which is responsible for 2FA Logik. There where some small changes lately in the 2FA-Code and I beliebe we can make it easier to point out where the code might need a slight fix.

**Comment by PetieM** [comment]
Fair enough. I just tested with both email and authenticator enabled (both with and without backup codes for good measure) and did not see that notification.

**Comment by JSuenram** [comment]
> Fair enough. I just tested with both email and authenticator enabled (both with and without backup codes for good measure) and did not see that notification.

Thanks, I believe this will make it easy for @Ylianst to fix this in one of the next updates.
If I have some spare time today I might also look into it..... I don't think its a big problem at all....

**Comment by PetieM** [comment]
Doesn't seem like it should be terribly difficult. Thanks for looking at it and let me know if you need anything else from my end.

**Comment by Ylianst** [comment]
v0.9.80 is out. This bug had to be fixed, it happens only when forcing 2FA but super annoying. Thanks for reporting it.

**Comment by PetieM** [comment]
Confirming that this is resolved in v0.9.80. Thanks for the quick fix!
