### ISSUE TITLE
Desktop interface buttons are dark on dark

### ISSUE THREAD

**Issue by masonh** [Ylianst/MeshCentral#3633]
The small buttons at the bottom-right of the Desktop page for a device are still black when the dark interface theme is selected, making them very difficult to see.

```html
<div class="toright2">
<!-- ... -->
<span id="DeskChatButton" class="deskarea" title="Open chat window to this computer"><img src="images/icon-chat.png" onclick="deviceChat(event)" style="padding-top:2px" width="16" height="16"></span>
<!-- ... -->
</div>
```
version: 0.9.79

![image](https://user-images.githubusercontent.com/1444864/153703203-6b19b8ca-339a-47a3-b032-b71340944d39.png)

**Comment by JSuenram** [comment]
@Ylianst if you are busy, you can assign that to me and I will take care of it....

**Comment by Ylianst** [comment]
I just put in a fix for this. However, I do appreciate all of the help I can get! Any issue you want to work on, please mention it and go for it. That would be great.

![image](https://user-images.githubusercontent.com/1319013/153728345-6d7a117f-cf22-4bab-9db5-19c9b00f2e30.png)

**Comment by masonh** [comment]
I just updated and it looks fantastic!
