### ISSUE TITLE
2 high severity vulnerabilities NPM

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#3638]
![image](https://user-images.githubusercontent.com/95070936/153806269-c4536aff-8a94-4c5e-9319-cc907152a8c7.png)

What is the problem ?

**Comment by VINISHVV** [comment]
Can you mention the Node version currently used, If it's an older version then please upgrade once and let us know this issue still persist?

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/153810237-347abbc0-fe4e-4525-94ab-4d7ad14edeca.png)


@VINISHVV Version 8.1.3

**Comment by jamgrorg** [comment]
@ONBET
This morning I had the same problem. I couldn't update meshcentral neither through web interface nore throught cli. Just update nodejs to the latest 17 version and it's all become vell.

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/153817987-cf0954ab-e60b-47e1-bdfd-139e86f869a7.png)

@jamgrorg I tried install latest 17 version, still same

**Comment by jamgrorg** [comment]
@ONBET interesting, my npm was updated during nodejs update. It was version 8.1.2 and now it's 8.4.1. Try to update it too.

**Comment by ONBET** [comment]
@jamgrorg I'm using Alpine Linux for meshcentral and the current latest version is 8.1.2 :(

**Comment by JSuenram** [comment]
> @jamgrorg I'm using Alpine Linux for meshcentral and the current latest version is 8.1.2 :(

Maybe you can add another Repository and install/update NPM from there?

**Comment by Ylianst** [comment]
I will be looking into this tomorrow, hopefully this will be an easy fix.

**Comment by Ylianst** [comment]
I just put in a fix for this and released MeshCentral v0.9.83. Let me know if that works._

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/153986690-8a710a5f-52cd-43d3-8dd1-5a6c9ad41ce6.png)

It works  ! Thank you @Ylianst
