### ISSUE TITLE
Resize New Privacy Bar Menu

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3639]
@Ylianst 

The latest "Privacy Bar" size is too big, is it possible to reduce the length of privacy bar ?

**Comment by JSuenram** [comment]
Can you post a Screen please?

**Comment by VINISHVV** [comment]
@JSuenram 

Please refer below screenshot.

![Uploading image.png…]()

**Comment by JSuenram** [comment]
Ok I understand, but please consider that when other languages or multiple users are connected to the session, the text might be much longer.
So there needs to be enough space to display all Information in Consent-Bar.

I would suggest to add an option like many other apps have.
A pin/unpin-Button where you can hide the bar and only show it when Mouse-Cursor touches the top of screen....

**Comment by Ylianst** [comment]
So, the real issue is that the privacy bar is too wide, not to big?

**Comment by VINISHVV** [comment]
> So, the real issue is that the privacy bar is too wide, not to big?

Yes, It's too wide only. 

Due to this, we are facing some difficulty to select multiple browser tabs in agent PC.

**Comment by krayon007** [comment]
I'll start by making a configurable option to set scaling factor. (I automatically adjust the width based on the display DPI). But I will also look into adding the ability to hide/pin the privacy bar. It probably won't have an animation or anything, it will just snap in/out, if that's ok.

**Comment by VINISHVV** [comment]
> I'll start by making a configurable option to set scaling factor. (I automatically adjust the width based on the display DPI). But I will also look into adding the ability to hide/pin the privacy bar. It probably won't have an animation or anything, it will just snap in/out, if that's ok.

Thanks @krayon007 - this is okay for us.

**Comment by krayon007** [comment]
I got pinning/hiding implemented.. There is now a pin, so that the privacy bar is pinned by default. Unpinning, will allow the bar to hide after a few seconds... Hovering the mouse over the sliver of the bar remaining, will cause it to pop back out for a few seconds or until you pin it. This will be in an upcoming agent update.

**Comment by VINISHVV** [comment]
@Ylianst / @krayon007 - Thanks, Its working fine.
