### ISSUE TITLE
Server stats graph looks like time went backward

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#364]
The actual data points are all in the right order, but the line connecting them goes past later data points and comes back, which makes it look like time was stopped, went backward, and then continued forward again.
!["Last week" graph showing "Users"](https://user-images.githubusercontent.com/1279475/61558125-04084300-aa1b-11e9-8999-9d49ae46ac2d.png)
!["Last day" graph showing "Users"](https://user-images.githubusercontent.com/1279475/61558180-2e5a0080-aa1b-11e9-9afe-e21182a880f5.png)

**Comment by Ylianst** [comment]
Oh... wow! Never saw this before. Looks like using a curve to fit the points is not a good idea.

**Comment by MailYouLater** [comment]
I kind of like the curve, but it needs to not allow going backwards on the time axis ... unless you're planning to add actual time travel. :wink:

**Comment by Ylianst** [comment]
Ok, I will try direct lines on the next published revision. However, if there is another solution, I am certainly open to it. I use [charts.js](https://www.chartjs.org).

![MC2-Graph](https://user-images.githubusercontent.com/1319013/61671773-e7c80880-ac9d-11e9-9d3e-55873f46acaf.png)

**Comment by Ylianst** [comment]
MeshCentral v0.3.8-j has the new line graph, hopefully this will solve it.

**Comment by MailYouLater** [comment]
As much as that does fix the problem, I'll miss the curvy lines.

@Ylianst: I'm closing this, since the issue is fixed, but I'm hoping we can bring back the curves later with a little adjustment to make them not pretend they're time travellers.

**Comment by MailYouLater** [comment]
Nevermind, I'm opening this back up because I figured out how to have curves without time travel. [Set the cubic interpolation mode to monotone](https://www.chartjs.org/docs/latest/charts/line.html#cubicinterpolationmode). This "ensures local extremums (if any) stay at input data points" so the line between each data point and the next will be curved, but won't go beyond the data points it's between.

Note: https://github.com/Ylianst/MeshCentral/blob/b9121dcd7b585aa7555bd871559628e499f64983/views/default.handlebars#L8076 should be removed, since line tension will be ignored with when using monotone cubic interpolation mode.

**Comment by Ylianst** [comment]
This is the right answer. Fixing it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-m with this fix. Looks good.

![MC2-StatsScreen](https://user-images.githubusercontent.com/1319013/61751187-5075ba80-ad5c-11e9-9d54-0bf0840bfb3c.png)
