### ISSUE TITLE
Update picture on the download page to reflect the new Agent GUI

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3640]
The explaining picture on the download page for the agents should be updated to use the new GUI design of the Agent:

![image](https://user-images.githubusercontent.com/3321655/153840008-fde92218-9722-4420-bdb4-96bfd00f9b5e.png)

**Comment by JSuenram** [comment]
I will take care of it when I have the new Agent tested....
@Ylianst Please assign me....

**Comment by JSuenram** [comment]
> I will take care of it when I have the new Agent tested....
> @Ylianst Please assign me....

I think I will have to make this dynamic as the new Agent allows Customizing of Text and logo and later also background and font color....

May take a day or two....

**Comment by Ylianst** [comment]
Can't wait to see what you come up with. Do try to keep it simple.

**Comment by VINISHVV** [comment]
@JSuenram - The new winagent.png image does not show uninstall button. Can you check it once.

**Comment by JSuenram** [comment]
> @JSuenram - The new winagent.png image does not show uninstall button. Can you check it once.

Cause you only have that button if the Agent is already installed. If there is no agent then there is no button.... 
![image](https://user-images.githubusercontent.com/68963439/154026065-d10251af-67be-4393-82ff-6a924e643efa.png)

**Comment by JSuenram** [comment]
Pull-Request for Custom-Image is send. #3649

**Comment by JSuenram** [comment]
@jacotec Please verify and close, should be in next update....

**Comment by Ylianst** [comment]
Good job @JSuenram, will be in MeshCentral v0.9.84

**Comment by jacotec** [comment]
Thanks @JSuenram!
