### ISSUE TITLE
FeatureRequest: New Agent should honor color and picture-settings.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3642]
Currently the newer Agent is always Blue and always shows the default MeshCentral-Logo.
Maybe it should honor the settings which are configured on the MeshServer?
Like Logo, Color etc. 

Just an Idea to keep it in a Corporate-Design which the User might already know or expect?

**Comment by CSW2000** [comment]
What i must write in config.json for my company logo ? for the new Agent 02_2022
![New Agent -Logo](https://user-images.githubusercontent.com/56474379/153914357-eaa4ee45-d896-4f3d-b348-09997bc751bd.PNG)
Roland W.  - Meshcentral on Raspi 4

**Comment by VINISHVV** [comment]
Please refer below image.

![FLgfyTJUUAIcNKE](https://user-images.githubusercontent.com/65057910/153917070-72f2d780-c9aa-4d45-96c0-e2622a62438f.png)

**Comment by Ylianst** [comment]
Text color and background color are not options right now, but Bryan can work on this. I think it would be a good idea.

**Comment by Ylianst** [comment]
I got word from Bryan that he is already working on background and text color customization for the next agent release.

**Comment by krayon007** [comment]
> @VINISHVV Thank you , i have found my problem , my Logo was to big ... 210 X 210 :- | Now it is working fine.

Are you saying when you used a logo that was too big, it didn't work? It should auto scale to fit correctly...

But I did update the agent to support configuring the background and foreground colors... That will be in an upcoming agent update.

**Comment by si458** [comment]
this should now be possible,
you can change the `backgrounColour,forgroundColor,image,installText` under `agentCustomization` under `domains` in config.json
![image](https://github.com/Ylianst/MeshCentral/assets/765314/9fb2538a-8861-4711-bb3a-d3f6627bdcfa)
