### ISSUE TITLE
MeshAgent OS X Uninstall

### ISSUE THREAD

**Issue by wcrlewis** [Ylianst/MeshCentral#365]
There does not appear to be an uninstaller or application listed in OS X Mojave.  Can someone detail how the agent is removed?  Any assistance is appreciate.  Apologies if this is not the forum for this issue.

**Comment by Ylianst** [comment]
Hi. We need to document this better. Download the MacOS mesh agent installed, right click on it and hit "open" and double click on the uninstall script. Let me know if that works for you.

**Comment by hunter-nl** [comment]
Almost correct: right click on MeshAgent.mpkg and "Show Package Contents" and double click on Uninstall.command file
