### ISSUE TITLE
No Devices showing for one user.

### ISSUE THREAD

**Issue by timcanty** [Ylianst/MeshCentral#3650]
One of our users, suddenly can't see any devices in my devices view.

He had been changing the grouping view etc, and then no devices would show, and whatever buttons he pressies he can't get it back working. 

Chrome is returning "Uncaught TypeError: Cannont read properties of undefined (reading 'name')"

We are currently running: v0.9.79, any suggestions on what the issue/fix to get his view working again?

Screenshot of the issue here.
![image](https://user-images.githubusercontent.com/32928117/154061105-ac78eb70-8296-429b-a280-bd02c729cac9.png)

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by timcanty** [comment]
Can confirm this has fixed the issue, thank you.
