### ISSUE TITLE
Feature Request: Maximum remote time & Inventory report

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#3651]
Hi,

I would like to know if there is an option to set maximum remote time for the PC. 

My guy used to remote multiple PC at the same time and forgot to disconnect the remote session then just left the browser remain open and went back home thus resulting large recording file size. 

Also, is that possible to generate inventory report(cpu, ram, hard disk, ethernet and etc) by group   ?

**Comment by Ylianst** [comment]
For maximum time, this may not the exactly what you want, but try adding this line to the domain section of the config.json:

```
"usersessionidletimeout": 30
```

This will automatically logout a user that was idle for 30 minutes.

For inventory report, you can click the header of a device group and hit "select all", then go in group action and select "Export device information"

![image](https://user-images.githubusercontent.com/1319013/154133006-1ce5290f-9540-4934-a5a2-c6e85772cb3a.png)

Let me know if that works.

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/154202337-09c846b4-5fef-46ef-8887-82ad94589f72.png)

Both works but the inventory report looks shabby. Wish it can be improve with more inventory detail.

**Comment by Ylianst** [comment]
There is a checkbox for ask for added details when 

![image](https://user-images.githubusercontent.com/1319013/154236395-e6c3f4e3-db38-42f8-9b48-efa5016c6e95.png)

Also, the CSV format is not a good format to download device details. JSON gets you a LOT more information if you can parse that format.

**Comment by ONBET** [comment]
Thanks @Ylianst  

Just notice that there is option to tick Include device details
