### ISSUE TITLE
Use real name in agent message box

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3654]
Hi,

With the new agent message, that is an improvement, but what i do not like, it is using the logon name from the user.
It would be nice if the real name is used when filled in, so people can see who is sending them an message

![message real name](https://user-images.githubusercontent.com/58996467/154126802-bf2a287e-c302-467a-aed9-1ec0dcd9ea97.jpg)

**Comment by krayon007** [comment]
This change will only require a server update, so should be easy to do...

**Comment by Ylianst** [comment]
Working on it now.

**Comment by petervanv** [comment]
Confirmed fix
