### ISSUE TITLE
Mobile site 'full screen' special keys button not working

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#3658]
I'm noticing that, at least on Android (I have no Apple devices to test with) the keyboard macro button is no longer working in the Full Screen view on the mobile website.  Clicking the button does change it's state (meaning the left/right carrot switches position) but it never pops the macro keys menu.  This is preventing me from sending a Ctrl-Alt-Del command to log in to devices. 
The keyboard button (last button on the list) does cause the phone keyboard to pop up and text entry is allowed.   The left/right mouse button is also still functioning correctly.  
Just appears to be an issue with the macro button.  I am on version 0.9.83 but can't say for certain when this trouble started (I only use the mobile site once or twice per week).  Definitely would have been a fairly recent issue though.

**Comment by PathfinderNetworks** [comment]
I wanted to bump this as it appears it wasn't noticed when I first reported the issue.  On the mobile 'Full Screen' view the special keys button no longer does anything.  Which means I cannot send a Ctrl-Alt-Del to any of my devices.  Here is a video of what I'm speaking about

https://user-images.githubusercontent.com/48607498/156438407-11b38f6d-1e0c-4dbc-a594-54b757e2e290.mp4

**Comment by vitko-bg** [comment]
I am joining to this request, even did not realized it has stopped working and when, but @PathfinderNetworks you are right, same issue here.

**Comment by kj7ice** [comment]
I am experiencing this same issue on Apple iOS devices as well. Screen size does not appear to be a factor since both my iPhone mini and my iPad (10" screen) do not display the shortcut keys/macro buttons. Unfortunately I do not know exactly which release this issue started because I only upgrade about once a month; it was last working for me in MeshCentral version 0.9.72. I first encountered this issue with version 0.9.81, and the issue remains after installing version 0.9.95 today.

**Comment by PathfinderNetworks** [comment]
I wonder if this issue is dependent on the phone OS version or maybe browser being used?  I am using a Galaxy S21+ with Android 12 and Google Chrome for the browser.

**Comment by Ylianst** [comment]
Ok, looking at this, I was able to replicate the issue on one of my servers... working on a fix now. If you add `&mobile=1` in the URL, you can show the mobile site on a desktop browser and and error shows in the browser console.

![image](https://user-images.githubusercontent.com/1319013/157314798-6417e1b6-6f2c-476c-9c56-0a0f689e3db6.png)

**Comment by PathfinderNetworks** [comment]
Excellent!  I don't often use the mobile site but, when I do need it, it's pretty critical.  Thanks!

**Comment by Ylianst** [comment]
Agreed! Found the root cause, fixing it now.

**Comment by Ylianst** [comment]
Fixed it, will be in v0.9.96 later today.

**Comment by PathfinderNetworks** [comment]
Just updated to 0.9.96 and the issue is fixed. 
Thank you!

**Comment by kj7ice** [comment]
Good to know about testing the mobile site on a desktop, and thank you for the fix @Ylianst! Working for me in the new version as well.
