### ISSUE TITLE
Bug: MeshCentral Router Links with Local Port Specified Only Work On Device General Page

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#3659]
Continuation of [#2617](https://github.com/Ylianst/MeshCentral/issues/2617), opened a new issue since that one was a feature request and it's technically been added. (Thanks again for that!)

Specifying the local port for router links works from the device General page, but not from the router links column on the My Devices main page. I had a peek at the links using the console in Chrome and the local port argument is definitely not present for the latter, so I'm thinking (hoping) it's a simple fix.

![Untitled-1](https://user-images.githubusercontent.com/42086791/154171502-56f31373-8a0f-4aa6-882c-60e29b0436c8.png)

**Comment by Ylianst** [comment]
Working on it now.

**Comment by Ylianst** [comment]
Fixed, will be in MeshCentral v0.9.85.

**Comment by MatinatorX** [comment]
Thank you! I will confirm and close as soon as it's available!

**Comment by Ylianst** [comment]
Excellent. Yes, double checking the work is always a good idea.

**Comment by MatinatorX** [comment]
Forgot to come back and close this, works great! Thanks again!
