### ISSUE TITLE
Can't find "add Mobile Agent in my devices"

### ISSUE THREAD

**Issue by geekdomotique** [Ylianst/MeshCentral#3660]
Hello Ylianst, 
First, thank you for your great work!
I've just setup and try to update meshcentral on a windows 10 computer, but i cant find the "add Mobile Agent in my devices" in the list... Have u got an idea?
![Capturemc](https://user-images.githubusercontent.com/66777265/154232607-3a36c7c9-8893-4b88-ba30-abfb15b8585b.PNG)

**Comment by Ylianst** [comment]
Yes, you can only add the mobile device if your MeshCentral server is in WAN mode or Hybrid mode. The Android agent does not work in LAN mode. You need to have a well know DNS name for your server. Take a look at the [video on LAN/WAN/Hybrid mode here](https://www.youtube.com/watch?v=gx5Fh3pQOns) for details.

**Comment by geekdomotique** [comment]
Thank u for your answer
