### ISSUE TITLE
Viewing Meshcentral web connection on a mobile phone - no keyboard

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#3661]
Can we get an onscreen keyboard when we are logging on to MeshCentral with a browser on a mobile phone

Connects fine, I just can't type username password etc to log in

**Comment by PathfinderNetworks** [comment]
The mobile website does already have this option. You just have to click the Full Screen button when you are connected to a device. Then you'll see 5 buttons appear on the right side.  The bottom most button will 'pop' the phone keyboard up so you can enter data.

**Comment by Ylianst** [comment]
Exactly. This is what you should see. Can you confirm your pressing the keyboard round button on the image below and nothing happens? - Thanks.

![image](https://user-images.githubusercontent.com/1319013/154390666-77dc8662-75ce-4044-80bb-cb38fc96d69a.png)

**Comment by si458** [comment]
closing as stale but also pls follow what @Ylianst explained above
