### ISSUE TITLE
auto-update don't work anymore

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#3666]
when I "check server version" : current version is correct, but "stable" and "latest" is "unknown" ...

**Comment by jamgrorg** [comment]
@Nothing2Do what version r u on? Try to update manually with npm install.

**Comment by Nothing2Do** [comment]
0.9.83, I run "npm up node_modules/meshcentral" (it seem nothing happens), manual start ("sudo node ~/node_modules/meshcentral"), long upgrade to 0.9.84 (I don't know why), and, now, it seem to work (I've restarted using systemctl). Thaks anyway !
