### ISSUE TITLE
AMT CCM ME v14.1.53 Fails

### ISSUE THREAD

**Issue by wgpjr** [Ylianst/MeshCentral#3676]
New devices with Intel ME v14.1.53 are failing to provision in CCM mode.  

Mesh Central Group is configured for
Type: Intel® AMT only, no agent
Intel® AMT:	Simple Client Control Mode (CCM)

Using meshcmd for intel AMT Setup
meshcmd amtconfig --url "myserver" --id "Id Info"

result:
Setting up MEI...
Starting Intel AMT configuration...
Started APF tunnel...
Checking Intel AMT state...
Failed to get Intel AMT state.

Machine does get added to mesh central but no AMT Configuration takes place

AMTInfo Results
meshcmd.exe Amtinfo
Intel ME v14.1.53, pre-provisioning state.
Wired Enabled, DHCP, 00:00:00:00:00:00
Connection Status: Unknown, CIRA: Disconnected.

**Comment by wgpjr** [comment]
I'm still experiencing issues provision v14.1.53.  Is there a known issue for this?

Thanks

**Comment by wgpjr** [comment]
Any update or suggestions for this?

**Comment by si458** [comment]
closing as stale,
please try updating to the latest version 1.1.21 and using node 18 or above.
if issue still persists, please reply back
