### ISSUE TITLE
LOG-Bug: Eventlog behaves different when using Web-SSH or WEB-RDP or Multiplex...

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#3679]
Normal Remote Session writes in log:

```
0:31:24 - [User] → [CL-DC-03](https://mesh-url/?viewmode=3#) → Started desktop multiplex session "qxs2jan9ww"
```

and on end

```
11:21:06 - USER → CL-DC-03 → Left the desktop multiplex session "qxs2jan9ww" after 2981 second(s).
```

So you have a session-code to get start and end. WEB-SSH and WEB-RDP don't have these logs.

You can see some sort of "Relay-Session" Logged without ID and you get "Left" with Seconds..... but it is hard to combine them, belonging to each other....

Is there a fix possible?

**Comment by Ylianst** [comment]
Good observation.

**Comment by Ylianst** [comment]
Ok, added a fix for this. Let me know if it works for you. Will be in MeshCentral v0.9.86.

![image](https://user-images.githubusercontent.com/1319013/155199787-dfd601d5-e100-4701-a951-4917c4cbe51c.png)

**Comment by JSuenram** [comment]
Yes, works as expected! Perfect! Thank you for this quick fix.
