### ISSUE TITLE
Question: MeshCentral installed on a distributed VM

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#368]
I make a virtual machine available to my customers - it's a "base" image which I then remote into and set up according to their requirements - but of course, I need remote access before I can do that ... _if only I knew of a great remote access solution to install upon it..._

If I install MC2 onto that base image and then make that MC2 enabled base image the one available to my customers to download, what is likely to happen when 5 people download it and bring it up into their environment? 

- will I get 5 connections on my MC2 server, each an individual machine, or 
- will I get 1 connection (with some sort of contention, I'm sure)?

I appreciate I can install MC2 on the base image once it's been downloaded, but in order to do that, I have to have remote access, or set up some sort of deployment mechanism (which I'm not adverse to, just thinking a little out of the box here)

**Comment by Ylianst** [comment]
The MeshAgent has a "anti-cloning" system. The agent stores the list of network interface MAC addresses into the meshagent.db file. On each start, it compares the stored MAC list, if they are all different, the agent will reset it's certificate an connect to the server as a new device. So, if you VM's all have different MAC's, it should work fine.

Another solution is to remove the meshagent.db file just before creating your master image. In that case, each agent will generate a new identity on start. As long as the meshagent.msh file is present with the server information, you should be ok.

**Comment by D4V3M0NK** [comment]
Works perfectly, at least in VMware Workstation which I believe assigns independent MAC addresses upon importing, so no need to fiddle with removing database files. MC2 comes to the rescue again.  Thanks Ylian.
