### ISSUE TITLE
(Enhancement) Persistence for users previous view settings.

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#3683]
When a user sets a view on a device, those settings don't remain after a disconnect or reconnect. Having a check box to accept and save those settings would be awesome to users not having to do the "Mouse marathon" as per some reddit users comments.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Can you provide steps to reproduce the problem. I click on the view on the top right, logout and log back in and I am still int he same view.

![image](https://user-images.githubusercontent.com/1319013/155189520-c62eb066-9d85-4e12-a2ea-a15bdd2025f4.png)

Maybe I am missing something?

**Comment by SomeGuru** [comment]
Hi Ylian,

Persistence of per unit graphics setting setup previously. Finding that each time same user logs on, they have to reapply the changes to view that was previously set by the upper right buttons and the expand arrows. This has to take place each time on each machine... A persistence setting would be nice to keep the settings until a reinstall of the agent was done, then its back to reset visual settings.

SomeGuru

**Comment by si458** [comment]
in theory this is now added, as it stores users states in the db and the browsers localstorage and then restores it to the localstorage when they next login,
but its only the per user and not per device per user

**Comment by SomeGuru** [comment]
I am more looking at the perspective of a connection disconnect on very weak internet devices. (Northern Bay Area - Ocean houses - VRBO) where the cellular network is semi weak to null. This inturn makes the connection like a 1.5mbps connection. This in turn causes lots of disconnects and reconnection takes time to reset the three icons back to previous working state... 

![image](https://github.com/Ylianst/MeshCentral/assets/48393851/0ac2b2c9-89bc-40eb-9bb2-3828c2e1c059)
![image](https://github.com/Ylianst/MeshCentral/assets/48393851/7872aacf-2c27-45c5-9db5-8592ade9ed8c)
![image](https://github.com/Ylianst/MeshCentral/assets/48393851/6c075129-b7fc-444c-be2e-21f7bcee5928)

What I am thinking is a way for the user to click to save layout between sessions... or something similar as not to have to reset the view each time... Because as I state it takes a bit initially for it to draw the screen from a slower remote connection... Also this would save the multiple clicks needed to make the good connection systems screens the way they should be.

SomeGuru
