### ISSUE TITLE
client connection to 2 server

### ISSUE THREAD

**Issue by leleb** [Ylianst/MeshCentral#3685]
have installed 2 agents from 2 different meshcentral server in the same windows client.
(binary name of the agents provided by the 2 server is customized
so their installation appears as 2 different program and 2 services running),
after updating one of the server to 0.9.84 (which updates the agents) the client did not connect any more.
Could still connect from the second server, download and install the updated agent from first server
then connection worked again 

is there a correct way to share a client among two servers?

**Comment by Ylianst** [comment]
By default, you can't install two MeshCentral agents on the same client unless at least one of the two agents is customized with it's own service name. On the domain section of the config.json, add this section:

```
      "agentCustomization": {
        "displayName": "Compagny® Product",
        "description": "Compagny® Product agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      }
```

The "servicename" is the important one here. It will allow you to set a name that is different from the default and when, two agents can be installed. They will also be installed in different paths and updated separately by their own server.

Let me know if that works.
