### ISSUE TITLE
MeshCentral Gateway IP in audit log.

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3686]
Dear @Ylianst ,
We have installed a MeshCentral Server in windows machine and around 1000 Mesh Agents have installed , All things working fine , until i checked audit log. Here only gateway IP is printing instead of the Source IP( From where meshagent session taken) and Destination IP( Where MeshAgent is installed). Kindly help me in resolving this issue. I want to check from which machine remote or file transfer was taken. 172.16.141.19 is the gateway IP.

.

**Comment by Ylianst** [comment]
Your MeshCentral server is behind a reverse proxy, you can watch this video on installing [MeshCentral behind NGINX](https://www.youtube.com/watch?v=YSmiLyKSX2I&t=670s), but the same applies to any reverse proxy.

You will need your reverse proxy to add the "X-Forward-For" header in requests to MeshCentral, and you need to add one of these two lines in the "settings" section of the config.json:

```
"tlsoffload": "172.16.141.19"
```

or 

```
"trustedproxy": "172.16.141.19"
```

Use the first if you are not expecting MeshCentral to perform TLS, the second if MeshCentral must do TLS. Let me know if that helps.

**Comment by mdshoaibumer** [comment]
Dear @Ylianst ,

We have not configured any proxy its just a gateway IP. Please help in resolving this issue as we are highly dependent on audit log

**Comment by Ylianst** [comment]
What software is your gateway running?
