### ISSUE TITLE
Column resize not shown properly with latest meshagent

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3687]
In latest meshagent a windows resize has been fixed - which is amazing, but column resize is still invisible, please fix if that is possible.
Thanks.

Attaching the screenshot on how it should be.
![image](https://user-images.githubusercontent.com/59362521/155142186-95927007-45f8-4da4-abf2-0421242cc06f.png)

**Comment by Ylianst** [comment]
I just took a look at this, MeshAgent is sending the server mouse cursor value 0 and should be sending value 16 for "col-resize". Bryan will likely need to look into this one.

**Comment by vitko-bg** [comment]
this has been fixed. checked and tested on latest MC 1.1.16, Agent 09.12.2022
