### ISSUE TITLE
Screen Resolution Issue when connecting via "Console"

### ISSUE THREAD

**Issue by boydspace** [Ylianst/MeshCentral#3689]
Greetings! This is a difficult issue to describe, so I'll do my best.

I have MeshCentral installed and working on multiple devices, but one of my PCs that it is installed on acts...funny...when I try to connect to it. When I click "connect", the resolution is so small that I cannot see what I am doing, nor am I able to adjust the resolution on said PC. If I connect via RDP first, and then click "connect", I am presented with two options:

1. Active, RDP-Tcp#0 - DOMAIN\user
2. Connected, Console

The RDP gives me the correct resolution, but the Console option is super tiny, 320x320

I am at a loss at what the problem is, but I believe it has something to do with the hardware on the PC. I don't know what to do to adjust this. Any help would be greatly appreciated!

<a href="https://ibb.co/fQHdd2x"><img src="https://i.ibb.co/XVtxxbC/connectscreen.png" alt="connectscreen" border="0"></a>
<a href="https://ibb.co/C526G7M"><img src="https://i.ibb.co/DDpY2C8/Screenshot-2022-02-22-103346.png" alt="Screenshot-2022-02-22-103346" border="0"></a>

**Comment by vithusel** [comment]
To confirm. Do you have a monitor plugged into that machine? 

Also is there a active RDP session on that machine as well?

**Comment by boydspace** [comment]
> 

Yes sir! There is a monitor. Here's the info on the graphics card as well as the monitor:

Radeon RX 580

Dell S2817Q (DP4k60)

I've updated all of the drivers, made sure Windows was completely updated, etc.

Yes, I did an RDP session so as to be able to see my screen. Sorry, I didn't finish my train of thought:
I have the open RDP  session so as to use the computer remotely as  I cannot see anything through MeshCentral. When I come to the MeshCentral connection, if I choose the RDP session to connect to, I can see the screen just fine, but I have to always do an RDP session first and then I can choose the RDP session through MeshCentral.

Sorry if I am not making sense! Let me know if I need to provide any other information.

**Comment by vithusel** [comment]
> > 
> 
> Yes sir! There is a monitor. Here's the info on the graphics card as well as the monitor:
> 
> Radeon RX 580
> 
> Dell S2817Q (DP4k60)
> 
> I've updated all of the drivers, made sure Windows was completely updated, etc.
> 
> Yes, I did an RDP session so as to be able to see my screen. Sorry, I didn't finish my train of thought: I have the open RDP session so as to use the computer remotely as I cannot see anything through MeshCentral. When I come to the MeshCentral connection, if I choose the RDP session to connect to, I can see the screen just fine, but I have to always do an RDP session first and then I can choose the RDP session through MeshCentral.
> 
> Sorry if I am not making sense! Let me know if I need to provide any other information.

Just one other question. 
When you connect to the machine in console mode. What happens to the display on the physical monitor? Does the resolution of the monitor also change during the remote session?

**Comment by boydspace** [comment]
> > > 
> > 
> > 
> > Yes sir! There is a monitor. Here's the info on the graphics card as well as the monitor:
> > Radeon RX 580
> > Dell S2817Q (DP4k60)
> > I've updated all of the drivers, made sure Windows was completely updated, etc.
> > Yes, I did an RDP session so as to be able to see my screen. Sorry, I didn't finish my train of thought: I have the open RDP session so as to use the computer remotely as I cannot see anything through MeshCentral. When I come to the MeshCentral connection, if I choose the RDP session to connect to, I can see the screen just fine, but I have to always do an RDP session first and then I can choose the RDP session through MeshCentral.
> > Sorry if I am not making sense! Let me know if I need to provide any other information.
> 
> Just one other question. When you connect to the machine in console mode. What happens to the display on the physical monitor? Does the resolution of the monitor also change during the remote session?

My apologies for not responding sooner.

When I connect in console mode, the resolution becomes smaller on the monitor attached as well.

**Comment by OutbackMatt** [comment]
You can often right click on a remote desktop and change the resolution being displayed

**Comment by boydspace** [comment]
> You can often right click on a remote desktop and change the resolution being displayed

Issue is that it is so small that I can’t do anything. When I log in and try to right click, the menu falls off the screen. If I try to get to the window any other way, the window does not permit me to scroll down to the location of the resolution location. I’ll try it and send more screenshots.

**Comment by troymroberts** [comment]
Is there any way to increase the resolution when the system being managed is a VM, so has no monitor attached?

**Comment by si458** [comment]
closing as stale,
please update to latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back

**Comment by razdavidovich** [comment]
After upgrading to the latest version, the screen is stretched instead of showing in the actual resolution like before.

![image](https://github.com/Ylianst/MeshCentral/assets/1929135/a246600a-8f45-4cf8-9cc6-119c84e54b6f)

Any advise?

**Comment by si458** [comment]
@razdavidovich you can click the little arrow at the top right to adjust the display 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/437d2fd6-a312-4fed-a887-047076d369f9)
