### ISSUE TITLE
[POWERSHELL] Force Update

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#369]
I just saw that you guys have updated this to have support for powershell. However i npm updated and checked that it was on the latest version and it hasnt worked?

Do i need to force update the meshagents? If so how can i?

Thanks

**Comment by Ylianst** [comment]
You are fast. Published MeshCentral v0.3.8-n with power shell support. For Windows computers, right click on the terminal "Connect" button and select "PowerShell connect" or hold shift and click Connect.

![MC2-PowerShell](https://user-images.githubusercontent.com/1319013/61838432-10870400-ae3e-11e9-9b7c-0797e6784b45.png)

**Comment by theredkoala21** [comment]
OH excellent. Yes i saw the context menu somewhere in the code but didnt see it popup on the main page.
+ didnt see a Tab for powershell. But yes the right click button is perfect. 
Thanks

**Comment by theredkoala21** [comment]
Excellent work. Tested on a few systems and it runs quite well.
Thanks again for your hard work on this project. We as users do not say thanks enough!
