### ISSUE TITLE
[Feature request] Generate token for other user (as admin)

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3690]
Hi 
It could be useful to be able to generate a token for a user.

I'm admin, i create use with somes writes.

Instead of giving a user and a password, I generate a token to give temporary access using the profile created

It's the same feature whe you generate token for yourself, but do it for user 

![image](https://user-images.githubusercontent.com/32361668/155175518-b40a2443-652b-43b6-8fd2-01da911720e7.png)

Best regards

**Comment by Ylianst** [comment]
You can use MeshCtrl.js to create login tokens. You would use MeshCtrl.js to login to the account you want to create the token for and create/remove the tokens you want.

![image](https://user-images.githubusercontent.com/1319013/155186008-340cfc71-4e1f-4a83-ad68-7af6a6c9fe65.png)

Your suggesting a "generate token" link, but it's not clear to me how you would manage outstanding tokens by just adding a link like this.
