### ISSUE TITLE
User Consent Timeout to force Allow (MeshAgent)

### ISSUE THREAD

**Issue by bbrendon** [Ylianst/MeshCentral#3692]
This is asking for an option on the server (config.json?) to set a timeout period that will auto-accept consent if the user does not click allow or deny within a specified time period.

**Comment by Ylianst** [comment]
Looks like the user consent timeout is currently set to 30 seconds, I can add an option on the server to change this.

**Comment by bbrendon** [comment]
Yes, that is my understanding as well.

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Just checked in more user consent options:

**Comment by bbrendon** [comment]
@krayon007  Did you get around to adding this to the agent? I tried this feature today by adding `autoAcceptOnTimeout` and it didn't work.

**Comment by krayon007** [comment]
I did implement it. I think the server config isn't connected to the agent yet tho. That should be easy to add, will only require a server update. I'll take a look at it tomorrow.

**Comment by krayon007** [comment]
I just tested `autoAcceptOnTimeout` with the current server, and it looks to work correctly already. Let me see which npm version it is in.

**Comment by Ylianst** [comment]
`consentAutoAccept` does not exist as a config.json option.

**Comment by bbrendon** [comment]
@Ylianst I didn't think so but I was getting desperate :)

I just updated to 1.0.0 and tried again.

**Comment by bbrendon** [comment]
I just tested this again on a newer version and it worked.

**Comment by silversword411** [comment]
Turns out there's a file dedicated to MeshCentral configuration options, just added it to the docs for indexing :)

https://github.com/Ylianst/MeshCentral/pull/4088/commits/a9dc9b41d8f2ece0e2c18203c4e0e13afd7db6d6
