### ISSUE TITLE
Feature Request: Meshcentral Assistant specific invites

### ISSUE THREAD

**Issue by Brodur** [Ylianst/MeshCentral#3694]
My goal is this: I want to be able to invite a user to download the MeshCentral assistant for my instance. As it stands right now, invites send the full agent. I'd like a way to specify either at the device group level, or in the invite screen, to use the Assistant software. The goal would be both invite links, and invite emails, would have the ability to link directly to the MeshCentral Assistant download, as opposed to the agent download.

The use case is such: I have a device group "Assistant Sessions" that I use for one-off support, and I'd rather for both my sake and the end user's sake, that they don't install the unattended agent on their machine.

Another idea would be to set a device group to only allow assistant connections? Not sure how you would specifically want to implement it, but that's what comes to mind for me as that's how I have things structured.

Yet another idea would be an implementation similar to QuickAssist or Screenconnect, where one party has to enter a code on the webpage to proceed with downloading/accessing. In my mind it could go as such - create an invite to an assistant session generates a code, and then you sent the user to mesh.example.com/assistant or something and have them enter it there.

Thank you for all of your work on this, I've been exploring the features as of late and it is a wonderful piece of software.

**Comment by Ylianst** [comment]
Assistant Only invitation is a good idea as for the invitation code feature, it's already present, but not active by default.

![image](https://user-images.githubusercontent.com/1319013/155419749-37299284-3161-44d9-b8ff-b4fec3db6ef3.png)

Let me know if that part works for you.

**Comment by Brodur** [comment]
Yes, the agentInviteCodes does indeed work as intended. The code generation/setting is admittedly a little bit clunky compared to products I've used previously, but it is serviceable.

So same idea there though, the ability to create an assistant only invite/group that can be downloaded with the agentInviteCode would fulfill the usecase.

**Comment by Ylianst** [comment]
I am working on the MeshCentral Assistant page now... hold on.

**Comment by Ylianst** [comment]
Still doing some testing, but this is what it will look like.

![image](https://user-images.githubusercontent.com/1319013/155432094-e9fb0188-8957-4654-9113-0815e9cae2f8.png)

**Comment by Ylianst** [comment]
Ok, check in. Will be in MeshCentral v0.9.88.

For web page customization, alongside "meshcentral-data" create a folder called "meshcentral-web", create a "views" folder in it and copy the file "node_modules/meshcentral/views/agentinvite.handlebars" into it. That copy will be served instead of the default one, you can customize as you want.

**Comment by Brodur** [comment]
> Still doing some testing, but this is what it will look like.
> 
> ![image](https://user-images.githubusercontent.com/1319013/155432094-e9fb0188-8957-4654-9113-0815e9cae2f8.png)

Looks great. Many thanks!

> Ok, check in. Will be in MeshCentral v0.9.88.
> 
> For web page customization, alongside "meshcentral-data" create a folder called "meshcentral-web", create a "views" folder in it and copy the file "node_modules/meshcentral/views/agentinvite.handlebars" into it. That copy will be served instead of the default one, you can customize as you want.

Right on, I'll take a look at the view. Thanks.

**Comment by Brodur** [comment]
I'm assuming this is the case, but I figured I'd confirm - when using email invite method this will work as well? 

If so, I think we can consider this complete.

**Comment by silversword411** [comment]
Adding to docs: https://github.com/Ylianst/MeshCentral/pull/3702

**Comment by Brodur** [comment]
@Ylianst It looks like the email invite form uses different inputs, and as such doesn't have the new assistant only option (I just updated to 0.9.89 last night to test).
![image](https://user-images.githubusercontent.com/49418324/155754007-7b6e303d-e371-4a9d-bf64-6f952f4b6bd2.png)
![image](https://user-images.githubusercontent.com/49418324/155754041-67d96795-97e2-4a6f-8af6-045c02bc55d2.png)

**Comment by Ylianst** [comment]
That will be more work since it will require a change to the email templates.

**Comment by Ylianst** [comment]
Ok, added it. Will be in MeshCentral v0.9.90.

**Comment by Brodur** [comment]
> Ok, added it. Will be in MeshCentral v0.9.90.

Right on, many thanks.

**Comment by Brodur** [comment]
Confirmed working as intended on 0.9.91.
