### ISSUE TITLE
active session info suggestion

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3695]
HI,
I have tokens enabled in an account, when users using that token to connect to an agent I can check that connection info by clicking on the blue active session icon where I can see who is connecting by identifying the token name. but currently it shows the account name who owns that token but not the token name itself. I believe it's better if it shows the token name instead. see the screenshots:

![connection info 2](https://user-images.githubusercontent.com/70715469/155427835-476410a9-1258-44cb-b1a0-192701be1b46.PNG)

![connection info](https://user-images.githubusercontent.com/70715469/155427875-5f89f685-d3d0-4e7a-9f25-6bba5b9b8808.PNG)

**Comment by smartekIT** [comment]
so if you have more than one Token on an account, then it's hard to determine which Token that session uses as it's currently showing the name of the user account but nothing related to Token Name or Token Username itself.

**Comment by Ylianst** [comment]
Login tokens should not be given to other users, they are intended to be used as an alternative way to login to your account. You can use guest sharing links if you want to share devices with other users and guest sharing links will have the name of the guest show up in the sessions list when you click on the blue dot.

**Comment by smartekIT** [comment]
theoretically I agree with you about sharing, but technically this was the only solution we had when allowing people to connect using Meshcentral Router CMD and I believe you suggested this on me when we were talking about how to configure Meshcentral RouterCMD config file so we don't have to put user plain passwords also because it wouldn't work when 2FA in place there and also not giving main account access to my RouterCMD users.  check here your earlier suggestion regarding RouterCMD   here: [https://github.com/Ylianst/MeshCentral/issues/3303#issuecomment-980513915](url)

**Comment by Ylianst** [comment]
If you are creating a token on your account and giving it to someone else, that is really bad. No matter if it's MeshCMD, Router or any other tool.

Now, you going to ask that login tokens need to be auditable in the event log and everywhere just like a different user. That is not something I am going to do.

Users should use their own account or you can create new "Bot" accounts for this purpose. That way, the bot accounts show up correctly in the event log and everywhere else.

Hope that makes sense.

**Comment by smartekIT** [comment]
That's fine, if I'm the only one using these Tokens, I think we better know which Token session rather than the account name. because even for using for myself only i still have to use the Tokens with RouterCMD to bypass the 2FA issue as there is no way I can apply the 2FA when using RouterCMD configured by meshaction file.
at least we leave it display whatever it's currently showing in the session info but adding the session Token Name or Token Username as an extra info.

sorry if I'm sounds too pushy, if you don't agree with my idea then it's ok and I'm really happy and thankful to you for what we have and what great software you gave us.

Thanks @Ylianst
