### ISSUE TITLE
MeshCentral-Router.exe save quality settings per connection

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#3696]
Hi,

we use mostly the MeshCentral-Router.exe and it is really annoying to set up every time the connection properties. It is possible to store the settings for this connection? Or at least change the default settings?

![grafik](https://user-images.githubusercontent.com/86785137/155484908-8312bef4-d529-4c07-8dd2-52d92a0c309d.png)

For the file transfer her "remembers" the last folders that we are in - so to store the conncetion/quality settings also seems not so a big deal for me ;-)

Thanks a lot for the work!

**Comment by Ylianst** [comment]
Agreed, this is a bug... working on it now.

**Comment by Ylianst** [comment]
Added fix for this, will be in MeshCentral v0.9.90.

![MC2-RouterImprovements](https://user-images.githubusercontent.com/1319013/155617734-75af0f00-3cad-49b2-ab52-61e4ad454632.png)

**Comment by OutbackMatt** [comment]
I would love to be able to save 'mappings' so that when a user logs in, the mappings are already there.

**Comment by Ylianst** [comment]
You can do that already. In the mappings tab, click the 3 bars and you can save the mappings.

![image](https://user-images.githubusercontent.com/1319013/155677449-549027b0-5d6d-4d57-9b47-a8037098ca07.png)

It will save a .mcrouter file, you can associate the file extension with MeshCentral Router so when you open the .mcrouter file, it will open MeshCentral Router and load the mappings. You can also run "MeshCentralRouter.exe mymappings.mcrouter". Lastly, you can edit the .mcrouter file and add your "password" to it so when you click on it, it will auto-login.

Let me know if that works.

**Comment by schanir** [comment]
Hi,

now in the Version 0.9.91 he store/remember the last connection settings. That great! Thanks a lot.

But he remembers only the last settings and use this for all other connection. So when I have two conncetions one with high speed (LAN) and one with low speed (WAN) ... the I have still this problem to set every time the compession settings... 
It would be very helpful to save this settings for each connection. In the way at first time he use the default settings. When I change the settings he save it and use it next time on this connection. So that I can have different settings for different PC/connections. Each conncetion can have its own settings. 

Bye

**Comment by OutbackMatt** [comment]
Works well thanks

I can save the .mcrouter file to the desktop, and the user can double click on it
