### ISSUE TITLE
MeshCentral-Router auto reconnect

### ISSUE THREAD

**Issue by schanir** [Ylianst/MeshCentral#3698]
Hi again,

it would be very helpful to have an auto-reconnect feature. So times the connection get los and I must press the connection button again (when i notice it). On some PCs it is very often - so it is very annoying to press fequently the connection button...

For me the way is this:
- at start (or then I press "connect") the software opens the connection and if this is successful it makes auto reconnect if the conncetion drops
- when I press "diconnect" he closes the connection (and stop trying to connect)

This would be very nice to have in the RemoteDesktop and in the RemoteFiles programms.

Thanks again!
Bye

**Comment by Ylianst** [comment]
Added support for this, will be in MeshCentral v0.9.90.

![MC2-RouterImprovements](https://user-images.githubusercontent.com/1319013/155617617-35a9974b-078b-40f1-8d9c-5284fdc5860e.png)

**Comment by schanir** [comment]
Hi,

in the version 0.9.91 the reconnect functions is there. I try it on a Win7 system. I make a reboot. After the PC has new started the connection was established but I get only a black image. When I press "disconnect" an wait some seconds and press "connect" then comes the correct image.

Bye
