### ISSUE TITLE
Feature Request: Add Powershell Script Repository and Script Autorun

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#370]
It would be great if we could have a powershell script repository and the ability to automatically upload and run those scripts with execution policy bypass mode on individual windows nodes and groups.

I know this is a big request that is far from trivial to implement but it would make MC infinitely more powerful and efficient especially when needing to perform a task on hundreds of computers.

**Comment by Ylianst** [comment]
This is a big request. FYI. Bryan just added PowerShell support in the Terminal, see #369.

**Comment by openmoto** [comment]
Hi @Ylianst,
Any chance you could look into [Powershell Universal Automation](https://github.com/ironmansoftware/universal-automation)?

It's fairly new but if some kind of integration would be doable, it might be beneficial to users on both sides. Not sure exactly how that would happen but having a small computer (something like raspberry pi) per site won't be too bad especially if the Universal Automation tool is storing credentials for running tasks.. API can be integrated in MeshCenrtal or straight up access the web interface through MeshCentral?

**Comment by penguinthingie** [comment]
Isn't this solved by the plugins platform by @ryanblenis ?

https://github.com/ryanblenis/MeshCentral-ScriptTask

**Comment by openmoto** [comment]
Wow!
Ok, I totally missed that one.
Just having a look. 
Thanks @penguinthingie

**Comment by si458** [comment]
this can already sort of be done now,
you upload your scripts (ps1 files) to the 'My Files', and put them into a group or ur files
then click a device then click RUN then select 'powershell', select 'run as agent' and select 'commands from files on server'
afterwards select you file and click OK, and it will run all the commands in the ps1 file on the remote device

**Comment by silversword411** [comment]
Can we use this same my files as a toolbox equivalent?

Have a folder in there called "Toolbox"
Then in desktop have something that loads toolbox, and when you select something it downloads that to the agent into a configurable folder and executes it?

**Comment by si458** [comment]
@silversword411 not that I'm aware of? The run command only runs the script commands in the background as the system user and the output of the script gets spitted out into the Console Tab of that device

Also using the option run as user doesn't work on Windows, only Linux, it will always run as the system user for now, the is another issue opened about this which I have looked into
