### ISSUE TITLE
Incorrect key mapping for UK keyboard

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#3701]
Hi,
Been using meshcentral for a while now, but recently I've noticed that the hash-key (#) on my keyboard is incorrectly mapped to the single-quote (') key. All other keys in the surrounding are ok. I am using Meshcentral 0.9.89 with my Windows region set to United Kingdom and a UK keyborad. (the one with a £ sign on the number 3 key)

Thanks.
Billy

**Comment by billymoox** [comment]
Hi,
Sorry but I don't know. How do I find out.
For some more background info, the mesh server is installed in a standalone debian server and I am remotingfrom offsite into a windows 2008 server which is offsite too.

**Comment by Ylianst** [comment]
Hi. In the remote desktop tab, hit the settings buttons and check "Use Remote Key Map" let us know what you see with the # key with and without this options selected. Thanks.

![image](https://user-images.githubusercontent.com/1319013/155584519-f29d8140-3cc1-4cc6-b276-3faa32b599db.png)

**Comment by billymoox** [comment]
Hi,
I've tried both checked and unchecked the "Use Remote Key Map", the result is the same. I've also made sure both of the machines are set to UK keyboard.
The keycode for the hash-key on my keyboard is 35 and the single-quote key is 39. Using https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_key_keycode. The code for the hash-key changed to 92 if I switch to US keyboard.


Billy

    On Thursday, 24 February 2022, 18:24:39 GMT, Ylian Saint-Hilaire ***@***.***> wrote:  
 
 


Hi. In the remote desktop tab, hit the settings buttons and check "Use Remote Key Map" let us know what you see with the # key with and without this options selected. Thanks.



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ylianst** [comment]
Ok, is that the only key causing an issue? I am going to go fix it, but want to fix all problem keys at once when I get into the code. - Thanks.

**Comment by billymoox** [comment]
Hi,I've tested all the keys on my keyboard. Apart from those two keys, there is another one located at the top row, next to the number 1 key. I don't know how to describe it, so I've attached any picture of it.Thanks for your quick response.BillyOn 24 Feb 2022 20:57, Ylian Saint-Hilaire ***@***.***> wrote:
Ok, is that the only key causing an issue? I am going to go fix it, but want to fix all problem keys at once when I get into the code. - Thanks.

**Comment by vitko-bg** [comment]
> I've attached any picture of it
Please add attachment, no attachment is visible

**Comment by billymoox** [comment]
On Thursday, 24 February 2022, 21:37:11 GMT, vitko-bg ***@***.***> wrote:  
 
 



I've attached any picture of it
Please add attachment, no attachment is visible


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ylianst** [comment]
Still not visible. Go to the GitHub page and add the picture there.

**Comment by billymoox** [comment]
![keyboard](https://user-images.githubusercontent.com/40301062/155627622-09ea15b3-9ea2-4269-aecc-39548f9c8f2f.jpg)

**Comment by OutbackMatt** [comment]
What about these keys - they don't work for me when I am trying to navigate typed documents

<img width="616" alt="image" src="https://user-images.githubusercontent.com/7231493/155653860-c6084426-3d98-4a89-92b3-34820ea9ca40.png">

**Comment by Ylianst** [comment]
MeshCentral v0.9.92 was published with (hopefully) improvements on this. Let me know if it works.

**Comment by billymoox** [comment]
Hi,
I've checked all the keys on my laptop, which is set to UK, with the remoting server swap between UK and US. All keys are mapped correctly. Thanks for your continue good work.
Billy

    On Monday, 28 February 2022, 21:14:17 GMT, Ylian Saint-Hilaire ***@***.***> wrote:  
 
 


MeshCentral v0.9.92 was published with (hopefully) improvements on this. Let me know if it works.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
