### ISSUE TITLE
Do Device IDs change? 

### ISSUE THREAD

**Issue by wrongecho** [Ylianst/MeshCentral#3703]
Hey there,

I understand that each device added to mesh central has a device ID computed from the device certificate. I was wondering if this ID is liable to change through the lifetime of a device?

I'm looking to build an "api" (read: wrapper around meshctrl.js) to sync device data from mesh central and would like something we can tie / hard link a device to. The name/rname could work but the device ID seems like a safer bet, presuming it doesn't change after each update? I'd also love to hear any suggestions you have around this. 

Thanks for your time!

**Comment by Ylianst** [comment]
Hi. The device id (also called nodeid in the source code) does not change when the server or agents are updated. The only time they would change is if the agent is uninstalled/reinstalled on the client device or...

If all networks MAC addresses change on the device (this is for anti-cloning, if you backup and image multiple computers with the same OS image, this will prevent many devices having the same nodeid).

If a device changes it's nodeid, it will show up as a new device in the user interface. Also, the nodeid is used as the primary key in the MeshCentral database to identify a device.

Hope that helps,
Ylian

**Comment by wrongecho** [comment]
Appreciate the quick reply. 
Perfect, thanks for the info! :)
