### ISSUE TITLE
LDAP to Windows Domain

### ISSUE THREAD

**Issue by JTrotta** [Ylianst/MeshCentral#3709]
Hello. I'm trying ti use LDAP.
MeshCentral installed on Linux, LDAP is Windows AD.

```
    "auth": "ldap",
      "ldapUserName": "displayName",
      "ldapUserKey": "samaccountname",
      "ldapOptions": {
        "url": "ldap://x.x.x.x:389",
        "bindDN": "CN=Administrator,OU=DOMAIN,CN=Users,DC=domain,DC=local",
        "bindCredentials": "password",
        "searchBase": "DC=domain,DC=local",
        "searchFilter": "(samaccountname={{username}})"
      }, 
```

But always get Login Error.
Where can I get logs to check errors?

**Comment by Ylianst** [comment]
I am not an an expert in LDAP and have never really setup an LDAP instance. MeshCentral makes use of [ldapauth-fork](https://www.npmjs.com/package/ldapauth-fork), so you can look at the options they have.

**Comment by JTrotta** [comment]
I did it, with no success. I'l try it again and again, adn let you know

**Comment by sieuwe** [comment]
@JTrotta 
Did you try without the port number?
That works for us, somehow ldapauth-fork doesn't like the port being specified.

This is our config:
"auth": "ldap",
"ldapUserName": "sAMAccountName",
"ldapUserKey": "sAMAccountName",
"ldapOptions":
      {
          "url": "ldap://x.x.x",
          "bindDN": "CN=Administrator,OU=DOMAIN,CN=Users,DC=domain,DC=local",
          "bindCredentials": "password",
          "searchBase": "DC=domain,DC=local",
          "searchFilter": "(sAMAccountName={{username}})",
          }

**Comment by JTrotta** [comment]
I did it, but without port nothing happens on widows neigther connection nor errors.
