### ISSUE TITLE
[WIN+R] Run / Windows Button

### ISSUE THREAD

**Issue by theredkoala21** [Ylianst/MeshCentral#371]
Is there any way we can add Win+R or any other windows button + combo's whilst using MeshCentral Desktop view?

Can JS hook the keyboard as required?

**Comment by Ylianst** [comment]
Is Win+R not already in the keys drop-down box? You select it and hit "Send". Pretty sure the browser can't intercept that key combo. However, I am open to suggestions.

![MC2-WinR](https://user-images.githubusercontent.com/1319013/61838969-999f3a80-ae40-11e9-944d-bc06293fcea1.png)

**Comment by theredkoala21** [comment]
Yes, that button is there.  However I think i have become accustom to Teamviewer/VNC keyboard hooking.

I did do a quick google of the subject before i posted, and wasnt able to find a solution. I guess this one goes in the cant be completed box.
Thanks

**Comment by Ylianst** [comment]
Ok. If there is a solution, I am open to it. I think this is going to be one of the limitations of running in a browser.

**Comment by theredkoala21** [comment]
Yes, sorry i wasnt saying that you guys cant complete it because of some reason. I understood that it was a limitation of the browser and it was unable to capture the Win Key, therefore out of your hands.
