### ISSUE TITLE
Unable to connect to websocket after upgrade

### ISSUE THREAD

**Issue by gadgetusaf** [Ylianst/MeshCentral#3710]
HI, 
I recently upgrade to the latest version of MeshCentral and contuniue to have the error Unable to connect web socket,click to reconnect. I have confirmed that the nginx reverse proxy has the needed config to pass websocket traffic.

**Comment by Ylianst** [comment]
Just for kicks, add this line to the "settings" sections of your config.json, restart you server and see if it fixes it:

```
"cookieipcheck": false
```

If that does not work, stop your server and run it manually like this:

```
node node_modules/meshcentral --debug web,webrequest,cookie
```

Wait for things to stabilize then try to login and send back any errors you see.

Thanks,
Ylian

**Comment by gadgetusaf** [comment]
Fixed for safari and still an issue in chrome. Ill chalk it up to a browser glitch. I did reset chrom too and that is still an issue.

**Comment by Ylianst** [comment]
Open the browser console and report back on any errors you see.

**Comment by gadgetusaf** [comment]
```Errors when loading the page:
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`
FQDN:1 [DOM] Multiple forms should be contained in their own form elements; break up complex forms into ones that represent a single action: (More info: https://goo.gl/9p2vKq) `

After trying to log on
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
commander.htm:1 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
6[DOM] Password field is not contained in a form: (More info: <URL>) 
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"d2password1" type=​"password" autocomplete=​"off" style=​"float:​right;​width:​200px" onkeyup=​"updateAccountDialog()​">​
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"d2password2" type=​"password" autocomplete=​"off" style=​"float:​right;​width:​200px" onkeyup=​"updateAccountDialog()​">​
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"c13" type=​"password" autocomplete=​"off" style=​"float:​right;​width:​220px">​
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"c28" type=​"password" style=​"float:​right;​width:​200px" maxlength=​"63" onkeyup=​"updateWifiDialog()​" title=​"Length between 8 and 63 characters">​
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"c29" type=​"password" style=​"float:​right;​width:​200px" maxlength=​"63" onkeyup=​"updateWifiDialog()​" title=​"Length between 8 and 63 characters">​
commander.htm:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"d24rsepass" maxlength=​"32" style=​"float:​right;​width:​100%">​```

Console Issues header:
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
Mark cross-site cookies as Secure to allow setting them in cross-site contexts

**Comment by bjoerrrrn** [comment]
I have a similar issue: After upgrading to 0.9.99 I couldn't log on with Azure Logon. It reloads the logon page. 
With a local user I can log in, but after a few seconds I get the Error Page "Web-Socket can not be connected" (German translation retranslated, sorry).

I have no errors or info messages in the Console in Chrome based Browsers. I have no errors in Traefik2 (Reverse Proxy) or in the meshcentral logs.  

None of the above seems to be an issue with Firefox. In Firefox, it works flawlessly. 

I reverted to 0.9.95, but the error persist - even when reverting. Is this a problem with the recent Chrome Update?

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.21 and use node 18 or above
if issue persists then please reply back
