### ISSUE TITLE
Feature Request: recording shared desktop session in background.

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#3716]
It would be very helpful if shared desktop sessions (Devices -> device icon -> Share button) could be recorded, so later i could check what have gone wrong for example to fix something, or just to check what have been done (for security reasons too).

**Comment by si458** [comment]
this is now possible, by using the `sessionRecording` section under `domains`
![image](https://github.com/Ylianst/MeshCentral/assets/765314/3acfaa5a-5113-40c1-baea-a950f10139b6)
