### ISSUE TITLE
Docker Error: Cannot find module meshcentral.js

### ISSUE THREAD

**Issue by GenuineJakob** [Ylianst/MeshCentral#3721]
Hi, I am trying to install MeshCentral inside Docker.
Unfortunately, I am only a beginner with docker and I have no idea how to get the npm version from inside a container.
For me this seems like an issue with your provided image:

```
`internal/modules/cjs/loader.js:905
������
  throw err;
  ^

Error: Cannot find module '/meshcentral/node_modules/meshcentral/meshcentral.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`
```

Raspberry Pi 4
Raspberry Pi OS 11 (bullseye) 64-bit
uldiseihenbergs/meshcentral:latest
I get the same error from gurucomputing/meshcentral-docker, if I build my own ARMv8 image.

**Comment by Ylianst** [comment]
When running MeshCentral, always run it from the folder above `node_modules`. So do this:

```
node node_modules/meshcentral
```

Do not do this:

```
cd node_modules/meshcentral
node meshcentral
```

Just a guess, but let me know if that works.

**Comment by GenuineJakob** [comment]
Thanks for your reply. The starting procedure of MeshCentral is included in the provided image. I can't change the commands that install and run the program. If I would do that, I have to create my own docker image. Maybe uldiseihenbergs can give some advise.

**Comment by silversword411** [comment]
> When running MeshCentral, always run it from the folder above `node_modules`. So do this:

What goes wrong when you do that?

**Comment by GenuineJakob** [comment]
The `node run` command is given in the docker/startup.sh script which is located inside this repository. Someone with more docker experience created it. I will try to change the commands in it, but it would be nice if someone with more docker knowledge than me could do this.

**Comment by GenuineJakob** [comment]
Hi, if I change the startup script from `node node_modules/meshcentral` to `node ./node_modules/meshcentral` it works perfectly fine.
