### ISSUE TITLE
Feature Request: all user login events 

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#3722]
I would like to request all generate report for all user login time & date. 

Existing report feature only allow to generate remote session & traffic usage

**Comment by Ylianst** [comment]
Sure, working on it now.

**Comment by Ylianst** [comment]
Added support for user login reports, will be in v0.9.94. Once published let me know if it works.

![MC2-LoginReports](https://user-images.githubusercontent.com/1319013/156266346-90ae9907-c1d3-4ffe-98e5-6f3bcc2f4656.png)

**Comment by ONBET** [comment]
@Ylianst Hi, 

Sorry I was in Covid quarantine last week. 

I just tested and yes it is working perfectly!

**Comment by ONBET** [comment]
![image](https://user-images.githubusercontent.com/95070936/157580819-6469c54a-ac76-4181-ad2d-e01a7fa8d94f.png)


I have question on the 2nd Factory report because it show None. 

We had enforce 2nd Factory login, every time our users login to meshcentral they will need to key in their 2nd Factory password so no way to bypass it, I'm curious why is it showing None

**Comment by ONBET** [comment]
Is this a bug ? 

> ![image](https://user-images.githubusercontent.com/95070936/157580819-6469c54a-ac76-4181-ad2d-e01a7fa8d94f.png)
> 
> I have question on the 2nd Factory report because it show None.
> 
> We had enforce 2nd Factory login, every time our users login to meshcentral they will need to key in their 2nd Factory password so no way to bypass it, I'm curious why is it showing None

Is this a bug ?

**Comment by Ylianst** [comment]
@ONBET Can you provide any more information on what 2FA the user is using? It's probably a log issue, but I need to be able to replicate the issue.

@kevinh-csalabs Good point, I have not looked into this for SSO. Let me check now.

**Comment by Ylianst** [comment]
Ok, putting in a fix for this. Will be in MeshCentral v0.9.99.

![image](https://user-images.githubusercontent.com/1319013/158479887-d534087d-aefa-4193-b439-8760f9767c77.png)

**Comment by kevinh-csalabs** [comment]
Awesome, thanks!

You're running out of numbers for that 0.x scheme. Time to move up a version and open a sparkling beverage to celebrate?

**Comment by ONBET** [comment]
We enforced google authenticator as 2fa for all users. It seems working fine now, no more "None". Thank you very much@Ylianst
Nice work and very appreciate 🙏
