### ISSUE TITLE
Terminal input not working correctly on mobile site

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#3724]
Hello,

when using the mobile app for Firefox on Android, typing something in the terminal tab in MeshCentral doesn't really work. Sometimes, tapping on a letter doesn't work or duplicates the previous one. It can be pretty hard to really type something as long as it's that way.

Requesting the desktop site does seem to help, but only a bit.

Here's a video of the bug: [https://www.dateien.at/s/aLsooAHT2JtKkR5](https://www.dateien.at/s/aLsooAHT2JtKkR5)

Firefox version: 97.2.0 (Build date 2022-02-17)
Android version: 11
MeshCentral version: 0.9.90

**Comment by AntonAndreevichMoroz** [comment]
I also encountered this yesterday.  Usually I don’t use it so often from a mobile phone, so I can’t say when this problem appeared.  Chrome browser and Android 11
![Screenshot_20220302_070429](https://user-images.githubusercontent.com/51225180/156293069-93175d69-f8c6-45d1-a444-560ed95f16c7.jpg)

**Comment by vitko-bg** [comment]
As an additional info: when using backspace to delete wrong/duplicated letter, have to click on backspace many times to be able to remove the last character, just does not work properly for me also.

**Comment by Ylianst** [comment]
This is a problem with XTerm.js which is used by MeshCentral, there is a bug for this here: [https://github.com/xtermjs/xterm.js/issues/3600](https://github.com/xtermjs/xterm.js/issues/3600). Not sure what I can do about it, the predictive text input of Android is messing up terminal input.

**Comment by mwllgr** [comment]
Interesting. Maybe adding `type="password"` or `autocomplete="off"` would do the trick for now? I read that it could help somewhere but messes with accessibility tools (e.g. screen readers).

**Comment by leleb** [comment]
Observed that pressing backspace after every character (except blank space) helps

**Comment by mwllgr** [comment]
The issue is fixed in v5.0.0 of xterm.js! An update seems to be necessary on @Ylianst's side - see https://github.com/xtermjs/xterm.js/releases/tag/5.0.0 for the full changelog.

**Comment by Ylianst** [comment]
Oh, thanks for noticing this. I just updated xterm in MeshCentral and it will be in v1.0.87

**Comment by dinger1986** [comment]
@si458 fixed can close
