### ISSUE TITLE
MeshCentral as a bastion

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3725]
I would like to use MeshCentral as a bastion.
But maybe another open-source product might suit me...

For a PC added 'manually' in MeshCentral without an agent:
Would it be possible to configure the RDP, VNC, SSH connections so that the video recording is started automatically?

Another point, is it possible to remove admin-saved RDP web credentials from a manually added PC that doesn't have an agent?

Would it be possible to set a retention period for video recordings rather than a number of stored videos?

thank you

**Comment by gaalos** [comment]
Hi 
To use it like real bastion Saving credential inside the user profile insted of host might be usefull
 [https://github.com/Ylianst/MeshCentral/issues/3366](url)
