### ISSUE TITLE
"autoAcceptOnTimeout": true is not working

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3726]
Latest Agent on Windows 10
MC server 0.9.92
Debian Jessie

On connection to a computer "autoAcceptOnTimeout": true option still denies connection after 30 sec "consentTimeout": 30

**Comment by Ylianst** [comment]
This feature is not implemented in the agent yet. A new agent update is required. Once updated, it will work. Bryan has been working on this.

**Comment by vitko-bg** [comment]
Understood. Thanks.
