### ISSUE TITLE
Relay connections appeared after last update

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3727]
Please see attachment:
![image](https://user-images.githubusercontent.com/59362521/156375707-5f3bdbad-8159-4ee5-a440-ea527a54527d.png)

I never had any relay connections before.
Is this normal?

**Comment by Ylianst** [comment]
Displaying relay session count is normal, but you should have seen this in prior versions. You can click on the "Relay Sessions" text above to toggle hiding that data if you like.

FYI. There are the state for MeshCentral.com and it's not running the latest update.

![image](https://user-images.githubusercontent.com/1319013/156417091-ae845b9e-e868-4b6c-b2b2-43b313bcd904.png)

**Comment by vitko-bg** [comment]
I am just wondering what caused those relay sessions to appear suddenly? Never had them before, unless using MeshRouter.
Could you please explain what are Relay Sessions count for? Thanks

**Comment by Ylianst** [comment]
Relay sessions are generally used when the MeshCentral server is forwarding data between a user (browser or MeshCentral Router) and a computer (agent). So, each time you start a remote desktop/files/terminal/SSH/VNC... you start a relay session.

Your graph is showing that you have many constantly open relay sessions now that you did not have before. Like, someone keeping many browser tabs open with a remote desktop session. One option I have seen is someone discovered that you can see many desktops at once and decided to keep this page open all the time. This will create one remote session per desktop.

![image](https://user-images.githubusercontent.com/1319013/156419320-852c6843-c413-46d7-ab0d-659ee7a5d439.png)

**Comment by vitko-bg** [comment]
Got that. Thanks for the explanation. So it is normal. However still have to find why never had Relay Sessions before. Possibly nothing to worry about.
