### ISSUE TITLE
AMT TLS only - CIRA TLS connection error

### ISSUE THREAD

**Issue by GenuineJakob** [Ylianst/MeshCentral#3728]
Hi, I have my first AMT device configured and everything works fine.

However, when I change Security Settings --> Remote TLS security from `Server-auth, non-TLS allowed` to `Server-auth TLS only`, I can't access Remote Desktop anymore. If I press start, the screen stays black and the button displays setup.

In the trace is a `CIRA TLS connection error` when I initiated the Remote Desktop session.
Can someone please advise me how to gather more information/logs?

Intel® ME:	Activated ACM, v11.8.86, TLS
Connectivity:	Intel® AMT CIRA
<img width="335" alt="trace" src="https://user-images.githubusercontent.com/37959554/156424512-e3af57b9-bcc2-473e-93f4-96526a200da9.png">
<img width="1384" alt="Screenshot 2022-03-02 at 19 26 10" src="https://user-images.githubusercontent.com/37959554/156424770-ce8f4813-3922-4541-b641-ff78141f5ca7.png">

**Comment by jsastriawan** [comment]
Please allow non-TLS. TLS inside CIRA or Double TLS is currently disabled. CIRA itself is already using TLS connection. See webserver.js line 4188.

**Comment by GenuineJakob** [comment]
Oh wow, thanks for your quick reply! Is it best to leave it at the default `Server-auth, non-TLS allowed` or should I disable it?
