### ISSUE TITLE
Help Needed - Prevent URLs in app from appending :4430

### ISSUE THREAD

**Issue by StarWhiz** [Ylianst/MeshCentral#3731]
Hi,

I have an issue where the app keeps appending :4430 to the end of it's URLs which is causes my agents to be unable to connect.

For example if my server url is https://meshcentral.example.com.... anything the app does such as link to chat or wget... the url that appears is https://meshcentral.example.com:4430 instead. 

This also causes my agents to connect to the wrong url with wss://meshcentral.example.com:4430/agent.ashx instead of just wss://meshcentral.example.com/agent.ashx

I'm using caddy reverse proxy so just using https://meshcentral.example.com will direct to the correct meshcentral container port. There is no need to append :4430 for me. 

I want the app to stop appending :PORT at the end of all URLs how do I do that?

config.json
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.example.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 4430,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": true,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true"
  },
  "domains": {
    "": {
      "title": "MeshCentral",
      "NewAccounts": false,
      "certUrl": "https://example.com:443"
    }
  }
}
```

Caddyfile
```
meshcentral.example.com {
        reverse_proxy meshcentral:4430 {
                header_up Host {http.reverse_proxy.upstream.hostport}
                header_up X-Real-IP {http.request.remote}
                header_up X-Forwarded-For {http.request.remote}
        }
}
```

**Comment by Ylianst** [comment]
This is exactly what `aliasport` is for. Just change this line:

```
  "_aliasPort": 443,
```

To this:

```
  "aliasPort": 443,
```

This will un-comment the line. `port` indicates what port MeshCentral should listen to, `aliasport` indicates what port MeshCentral is actually running on.

**Comment by StarWhiz** [comment]
Thank you @Ylianst you are my savior! I did not know _ means comment. Now I do! sorry rookie mistake!

**Comment by Ylianst** [comment]
You can look [at this video for help on this topic.](https://www.youtube.com/watch?v=31mxfH4y1SY). Also in your config.json, this is bad:

```
    "AllowFraming": "false",
    "WebRTC": "true"
```

The quotes indicate a string value of "false", this is not what you want... change to this:

```
    "AllowFraming": false,
    "WebRTC": true
```

**Comment by StarWhiz** [comment]
thank you! Crap didn't know I missed these syntax problems as well!
