### ISSUE TITLE
Feature Request: Redirect Unauthorized static page

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#3732]
Hi, Maybe can add this functionality:

I did config the "userAllowedIP"  with specific public IP, when I access from unauthorized IP, meshcentral show a plain text message like "Unauthorized". Maybe, can doing a configuration option like this video: https://www.youtube.com/watch?v=qDKwNyHX3SY

For example add this option: "ipUnaunthorizedRedirect": "URL",

Regards

**Comment by Ylianst** [comment]
Yes, this feature is already present. At 9:48 in the video you link, I (try) to demonstrate this exact feature. Add this line:

```
"ipBlockedUserRedirect": "https://sample.com"
```

Note that you can use the line both in the "settings" section and in the "domain" section. If you use it in the settings section, it will work for users blocked by settings in the settings section. Use it in the domain section for users that are blocked by settings in the domain section. Let me know if that works.

**Comment by FrankSanabria** [comment]
Hey Ylianst, GREAT!!, in settings section work.

**Comment by Ylianst** [comment]
Nice, if this is ok, can you close this issue? Thanks.
