### ISSUE TITLE
Serve different agent executable per domain

### ISSUE THREAD

**Issue by rallisf1** [Ylianst/MeshCentral#3736]
At the moment you can customize the appearence, filename, service name, ports etc of the agent per domain, but if you want to code sign and dns lock the agent it will only work for 1 DNS domain.

Adding an "agentSource" option in the domain properties where you declare the signed agent filename for this particular domain and then have meshcentral serve that from meshcentral-data (if the value isn't empty) should solve this. Also add a warning for when "agentSource" has a value but the file is not accessible instead of downloading the default agent.

P.S. Inspired by: https://www.youtube.com/watch?v=HZj9igSn-sY

**Comment by Ylianst** [comment]
Just checked in this feature. This will be in MeshCentral v0.9.96. In "meshcentral-data", you can create the folders "agents", "agents-domainid1", "agents-domainid2" and you the agent binaries in them.
