### ISSUE TITLE
Duplicate logging

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3738]
Hi,
recently i looked op the user logons at the report settings, and i did notice duplicate logons, in the report, only at windows and android 11 at the in combination with google chrome, on edge and firefox it went perfectly, just one line of logging

Meshcentral version: 0.9.95 @ ubuntu server 20.4.4 LTS

![duplicate logging](https://user-images.githubusercontent.com/58996467/156895339-4bf7cf36-5461-4b6e-83d9-4bb0e901b722.jpg)
![duplicate logging - 1](https://user-images.githubusercontent.com/58996467/156895340-31d11f45-16cf-4cc1-bfbb-a8c1b20dcbe8.jpg)
.

**Comment by Ylianst** [comment]
Your right! I see the same thing when using the Chrome browser, but not with FireFox. Looking into it now.

**Comment by Ylianst** [comment]
Wow, Chrome makes the request twice:

![image](https://user-images.githubusercontent.com/1319013/156896213-616d071a-4696-4951-8936-e6f7e65e5376.png)

**Comment by Ylianst** [comment]
Put in a fix for this, will be in v0.9.96.

**Comment by petervanv** [comment]
Confirmed fix, thx
