### ISSUE TITLE
Keyboard combinations: "CMD" for Mac missing

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3740]
I'm struggeling remote controlling a MacBook. The Dock is configured to be hidden at the bottom, moving the mouse downwards shows the dock on the machine.

Unfortunately MeshCentral does not allow me to move the mouse more downwards than the screen border, so that method does not work to get the dock active.

There is a key combination in MacOS which does the same: CMD+Alt+D

Unfortunately I can't configure CMD combinations in MC:

<img width="451" alt="2022-03-06_19-07-14" src="https://user-images.githubusercontent.com/3321655/156936027-735e0cf7-d977-455e-9b45-094481cfd338.png">

Using "Win" instead of "CMD" here does not do this job.

So I have no way to start programs using the dock on the remote Mac right now.

Is there any workaround?

**Comment by krayon007** [comment]
Oh, interesting. I'll see if I can figure out how to get the dock to pop back up

**Comment by krayon007** [comment]
I think it's related to how I'm doing input injection on macos. I noticed the mouse input injection does not trigger hover events on macos, like it does on windows and Linux.

**Comment by jacotec** [comment]
OK ... do you have any ideas for possible solutions?

**Comment by si458** [comment]
this works as expected now, just tried it with my old macbook pro 2012
WIN+C - copy - CMD+C
WIN+V - paste - CMD+V
