### ISSUE TITLE
Battery status missing.

### ISSUE THREAD

**Issue by storbild** [Ylianst/MeshCentral#3741]
I just noticed that the battery symbol is missing on the device icons. I know it was there before. Is it a bug or could I have disabled it somewhere by mistake?

Edit:  Actually, I can se it if I login with a mobile device, But I want to see it in desktop view as well.

**Comment by Ylianst** [comment]
I see the battery indicator correctly on my test server, can you open the browser console and see if there are any errors shown?

![image](https://user-images.githubusercontent.com/1319013/157186420-51d19580-9668-4aa9-a534-337f35e374a4.png)

**Comment by si458** [comment]
closing as stale and all seems to be working perfectly fine now
