### ISSUE TITLE
Increase Token Time

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3742]
Hi.
It's possible to give access with token more than 4 days ? 

Thx

**Comment by gaalos** [comment]
@petervanv thx for your reply. I mean without be unlimitedsorry ^^

**Comment by Ylianst** [comment]
How many days do you want?

**Comment by gaalos** [comment]
@Ylianst  for exemple 7 days(1week) 
Is there a variable or it's "hard" coded 

Best regards

**Comment by Ylianst** [comment]
The options are coded in the web page, I just added a new "7 days" option, will be in MeshCentral v0.9.96.

**Comment by gaalos** [comment]
@Ylianst  Thx for your update.
maybe it could be interesting to add in the config an extra-token-days json array
Best regards

**Comment by Ylianst** [comment]
v0.9.96 is out. If you want something different, please create a new issue - Thanks!
