### ISSUE TITLE
Using Gmail inside MeshCentral ending 30 may 2022

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#3744]
I recieved an mail from gmail, because i am using there smtp server to send mail from my server. It is based on hte username/password to send the mail. That will be ende from 30 may 2022. Is it possisble to build in an oauth to send mail from the meshcentral server witch will be accepted by google ?

![image](https://user-images.githubusercontent.com/58996467/157107567-45600213-a8bb-4df9-b347-3ec13760ad8c.png)

**Comment by Ylianst** [comment]
I see what I have to do, for my own notes, [the instructions are here](https://nodemailer.com/smtp/oauth2/).

**Comment by Ylianst** [comment]
For my own notes, found one more [help guide here](https://alexb72.medium.com/how-to-send-emails-using-a-nodemailer-gmail-and-oauth2-fe19d66451f9).

**Comment by Ylianst** [comment]
Just check-in support for Gmail OAuth, this will be in MeshCentral v0.9.98. Once updated, you can configure your "smtp" section like this:

```
  "smtp": {
    "from": "xxxxx@gmail.com",
    "auth": {
      "clientid": "xxxxxxxxx-xxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
      "clientsecret": "xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "refreshtoken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  }
```

You will need [to follow these instructions](https://alexb72.medium.com/how-to-send-emails-using-a-nodemailer-gmail-and-oauth2-fe19d66451f9) to get the `clientid`, `clietnsecret` and `refreshtoken`. Once filled in, if you run the server manually you should see this:

![image](https://user-images.githubusercontent.com/1319013/157737659-7b2fccfc-e0a3-4212-a3c7-cf3117d468ec.png)

I will likely make a YouTube video to cover how to set this up in the future.

Once published, let me know if it works.

**Comment by petervanv** [comment]
wow, tried to understand the instructions url, but its hard to get, need some time to get it working

**Comment by Ylianst** [comment]
I will need to make a video on this. If your not familiar with Google Developer Console, this is a bit crazy.

**Comment by PrplHaz4** [comment]
good excuse to switch to a dedicated mail host - sparkpost still has a decent volume free test tier...

**Comment by Ylianst** [comment]
I have to make a correction to the image I posted on Twitter about this feature, int he config.json file, the "smtp" section does not go in the "settings" section. This is the corrected image.

![MC2-GmailOAuth](https://user-images.githubusercontent.com/1319013/158849238-b60873e2-0564-402a-8f29-ee0fa8124bd3.png)

**Comment by petervanv** [comment]
Was left open untill instructional video was released

**Comment by dashrender** [comment]
Any luck with a video yet?  I'm having issues with the instructions to get Gmail working with this.

**Comment by silversword411** [comment]
Enable 2fa on Gmail account, create app password and use that in creds

**Comment by bravery-only** [comment]
Where should I get these three values and replace them?

 "clientid": "xxxxxxxxx-xxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
      "clientsecret": "xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "refreshtoken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
