### ISSUE TITLE
Accent in first name for double authentication

### ISSUE THREAD

**Issue by titrax35** [Ylianst/MeshCentral#3745]
Hello,
I have activate the double authentication and for people who have an accent in is name (example: "Hervé"), there is no barcode to flash, we need to copy the created link and paste it in other website which generated the code.

**Comment by Ylianst** [comment]
You are right, looking into this now.

![image](https://user-images.githubusercontent.com/1319013/157318004-36a748a4-a130-45aa-9f11-a4e7743977b5.png)

**Comment by Ylianst** [comment]
Fixed, will be in v0.9.96.

**Comment by titrax35** [comment]
Thanks

**Comment by Ylianst** [comment]
v0.9.96 is out, let me know if it works and close this issue if it does.
