### ISSUE TITLE
Windows meshcentral service won't stop

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#3746]
I have three occasions now where I need to restart the Windows MeshCentral Service on Windows Server OS, and the service won't shut down properly, and I've had to restart the entire server to get the service back to a usable state

Any Ideas?

(restarting the services is intended to bring the mesh agent back on line. I am connecting via general RDP or Teamviewer to restart the service. Ideally it would be better if the mesh agent just didn't go off-line in the first place)

**Comment by krayon007** [comment]
Which mesh Central server version are you running? And which windows server os are you running? Are you only seeing this version on windows server?

**Comment by OutbackMatt** [comment]
> Which mesh Central server version are you running? And which windows server os are you running? Are you only seeing this version on windows server?

Always Latest (updates daily)
Some Server 2008R2, some Server 2012R2, and a Server2016

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.21 and use node 18 or above
if issue persists then please reply back
