### ISSUE TITLE
Full screen button and exit from full screen are on opposite sides

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3749]
Actually this is something I wanted to report from long time ago, it is a bit strange to have buttons for full screen and exit from full screen on opposite sides. Could you please relocate exit from full screen button to the top right corner - same location on the screen as the full screen button.

Location of full screen is fine (top right corner):
![image](https://user-images.githubusercontent.com/59362521/157468389-497e8626-4690-4a35-9743-d72ab2ea0dd4.png)

Exit of full screen can be let's say here, last button on the row:
![image](https://user-images.githubusercontent.com/59362521/157469435-b8384163-9604-4bdb-9821-76656a6324fb.png)

Thanks.

**Comment by Ylianst** [comment]
Interesting, working on it now.

**Comment by vitko-bg** [comment]
Thx

**Comment by vitko-bg** [comment]
Closed by mistake, but believe it will be fixed. Thanks again :)

**Comment by Ylianst** [comment]
![image](https://user-images.githubusercontent.com/1319013/157495056-afa7f2fc-c8f2-483c-bea8-cdcc77e4c690.png)

Changed the button, will be in v0.9.98

**Comment by vitko-bg** [comment]
Was not sure if have to reopen this issue or open another one, so opened #3819.
Hope that is ok.
Otherwise on Desktop tab all is fine!
Thanks.
