### ISSUE TITLE
 "Unable to connect to web socket" in v0.9.96

### ISSUE THREAD

**Issue by ClickLeft** [Ylianst/MeshCentral#3750]
Hi all, just updated as usual per the web interface to the latest version (I believe it was 0.9.99.) Suddenly, I'm seeing all my systems appear for a second after logging in then the "Unable to connect to web socket" error appears. Subsequent connections result in ERR_CONNECTION_REFUSED from the browser (Chrome)

No configuration has changed and I was previously running 0.9.95 without issue.

Here's a copy of mesherrors.txt:
https://p223.p4.n0.cdn.getcloudapp.com/items/z8uLvq5W/79ac62c9-7c7c-4a43-a235-c4e203c2b3c2.txt?v=d7ca8dc99c503fb498888c848ec3bfa3

**Comment by Ylianst** [comment]
This has been fixed already, update to v0.9.97 and it should solve it.

**Comment by Ylianst** [comment]
Just corrected the title.

**Comment by ClickLeft** [comment]
Thanks! I'm not sure how to update without the web interface. I haven't run into this before. Is there a link to the executable I need to replace?

**Comment by Ylianst** [comment]
You would normally need to do a manual update, but one way to go is to add this line to the "settings" section of the config.json:

```
    "agentAllowedIp": "1.2.3.4"
```

This will block all agents from connecting and the server will not crash anymore. Then, update using the web interface and once updated, remove the line and restart the server. Let me know if that works.

**Comment by ClickLeft** [comment]
Ah, duh, should have just unplugged the LAN cable. Fixed. Thank you!!!
