### ISSUE TITLE
Feature Request: Add config option that disables allowing the save of credentials 

### ISSUE THREAD

**Issue by Brian-Chow** [Ylianst/MeshCentral#3751]
Request: A blanket disallow of saving credentials would be a great first step.  Ideally, we would be able to specify tags or groups of computers that are not allowed to have credentials saved for them, but a single toggle for the entire site would also be satisfactory.

Scenario: A contractor, or even a senior employee who has legitimate access to a system in Mesh Central, connects frequently and feels like saving their credentials so they don't have to enter them again, despite best efforts at convincing them NOT to do that.  They then close a web-rdp session by simply closing the browser window.  

Result: the next person to attempt a web-rdp session to that system is then able to use system credentials and are connected as the contractor/senior employee to that system.  

Disabling the ability to save credentials eliminates the entire scenario and allows enforcing identity policies, while also increasing the difficulty of lateral movements via mesh central in the off chance that they somehow gained unauthorized access to mesh central.

**Comment by Ylianst** [comment]
Ok, working on this now.

**Comment by Ylianst** [comment]
Added it. In the domain section of the config.json, add this line:

```
"allowSavingDeviceCredentials": false
```

This will remove the "Remember" option and not allow use of any existing credentials.

**Comment by Brian-Chow** [comment]
> Added it, will be in MeshCentral v0.9.99. In the domain section of the config.json, add this line:
> 
> ```
> "allowSavingDeviceCredentials": false
> ```
> 
> This will remove the "Remember" option and not allow use of any existing credentials.

Thanks, I will give it a run as soon as 0.9.99 drops.  It's much appreciated!

**Comment by Ylianst** [comment]
Uploading it now, should be live in a few minutes.

**Comment by Brian-Chow** [comment]
I can confirm that this working for me.  Thank you!
