### ISSUE TITLE
Ask some questions about the config.json file

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#3752]
Dear All:

Ask some questions about the config.json file.
We refer to the sample_config_advanced.json file. Some options of 'myserver' cannot be displayed, including 'backup and restore' .
In addition, can the map function be turned on?
About "SMTP": we haven't set up the email function successfully, and there is no more detailed guidance document?

Thanks so mch!
Billy dudu

**Comment by VINISHVV** [comment]
@billydu1980 

The backup/restore option visibility depends on the Database you are using. This option is used for default Nedb only.
I hope you are using a different Database like MongoDB/Mysql etc.....

To enable SMTP please add the below commands in config.js. This will mainly be used for Email authentication ( 2F ), Resetting user passwords, sending new user credentials through Email, Invite agents, etc...


 "smtp": {
    "host": "**smtp.gmail.com**",
    "port": **587**,
    "from": "your email id",
    "user": "your email id",
    "pass": "your email pass",
    "tls": false
  },

**Comment by Ylianst** [comment]
If you are having issues with the config.json, [I have a video here](https://www.youtube.com/watch?v=31mxfH4y1SY) on syntax and how to check that the config.json is correct.
