### ISSUE TITLE
keyboard language and uac problem 

### ISSUE THREAD

**Issue by golg3** [Ylianst/MeshCentral#3756]
1. I use a Turkish keyboard and after connecting to the computer I support, the letter "i" is written on the keyboard instead of the letter "ı".
2. When installing or deleting a program on the computer I support, the user name and password screen opens, and my connection is disconnected. 

We enjoy using your program, thank you for sharing it with us.

**Comment by vitko-bg** [comment]
In regards to 1. - please try the following [https://github.com/Ylianst/MeshCentral/issues/3701#issuecomment-1050136070]
about 2. - not sure. Have you installed MeshAgent as Administrator? Which MC server and agent versions you are running?

**Comment by golg3** [comment]
1. I chose use remote keyboard map but it didn't work. 
2. 0.9.89 version

**Comment by krayon007** [comment]
Is the agent running as a background service, or was it launched interactively by the user?

**Comment by golg3** [comment]
> Is the agent running as a background service, or was it launched interactively by the user?

it works in the background, i connect with user confirmation
