### ISSUE TITLE
Feature Request: Clipboard usefull function needed

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#376]
Hi Ylianst,
I am using dwservice.net remote support system. There is a function for set clipboard. When i click to set clipboard and paste the value it apply and paste it if a browser is open or notepad is open automatically commit the paste value. the function is really usefull and userfriendly.
I am using meshcentral on windows servers and clients. if you can develop this function to meshcentral it will be very nice.
Thanks

**Comment by Ylianst** [comment]
Hi. There is a clipboard button at the bottom of the remote desktop screen. I have not used dwserver.net, so if there is a better way, please let me know.

![MC2-clipboard](https://user-images.githubusercontent.com/1319013/61850231-9d46b780-ae68-11e9-8de0-1cf60f832c73.png)

**Comment by senolkehya** [comment]
Hi Ylianst,
the product is hosted on https://dwservice.net
In 1st screen shot i click set clipboard button.  After i paste the value to window i click paste. In my case for example google chrome is opened and cursor is in url address.
It paste the value to url after i click paste buton.
Can you please do this function when i click set clipboard in meshcentral can it paste the value to client?


![1](https://user-images.githubusercontent.com/39443706/61868886-0b2fc500-aee3-11e9-93c2-319204cf71b5.JPG)
![2](https://user-images.githubusercontent.com/39443706/61868917-1aaf0e00-aee3-11e9-8757-f390847ff48d.JPG)

**Comment by Ylianst** [comment]
Ok, so if I understand correctly, this is not really a clipboard feature. This is like "remote type". The is, you enter something in the dialog box and when you hit ok, that string will be "typed" into the remote window? Is this correct?

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-s with new remote typing feature. Take a look at the "Type" key on the bottom of the remote desktop and let me know if that works.

![MC2-RemoteTyping](https://user-images.githubusercontent.com/1319013/62013425-45999c00-b147-11e9-904a-d11c7bbaa4d6.png)

**Comment by senolkehya** [comment]
Hi Ylianst,
The type function is really good. But the disadvantage of this feature only US keyboard is supported. When i use special characters such as ! @ it apply different characters.
Is it possible to use Turkish Q keyboard in this feature?

**Comment by Ylianst** [comment]
Right, so this is a current limitation. I talked to Bryan about this, it looks like we could support any keyboard, but it requires some work on the MeshAgent to support this. it may take a while.

**Comment by ghplw** [comment]
This is fantastic, Very useful when a bug is causing things to disappear fast and you need to type something really fast.

Any chance of a DuckyScript input mode?

**Comment by Ylianst** [comment]
What is DuckyScript? I found a few hits on DuckDuckGo. Looks like a simple script to perform input, but if there is an exact syntax you need, can you provide a URL to a sample? Thanks.

**Comment by ghplw** [comment]
I will open a new feature request but the author or yourself will need to close this one as I can only comment.

**Comment by Ylianst** [comment]
Thanks. I will keep this one open as I want to improve remote typing to support non-US English keyboards.

**Comment by Ylianst** [comment]
Ok, closing this one as we have a clipboard feature. Please open a new issue if needed.
