### ISSUE TITLE
<enter> don't valid the OTP anymore

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#3760]
I'm on mc 0.9.98 (the latest), and, when I need to enter my OTP, 6 digits, "enter" and it don't work. I'm forced to click on "connexion" (french, connect in english, I suppose). Is this a new feature ? ;-) (and I've tested on the "stable" version 0.9.52, and it's working properly)

**Comment by Ylianst** [comment]
Oh! I don't even have to check, I know your right. Working on fixing that now!

**Comment by Ylianst** [comment]
Fixed it, will be in MeshCentral v0.9.99 when it's published.

**Comment by Nothing2Do** [comment]
thanks, I'm on 0.99 ! happy
