### ISSUE TITLE
HTTP Redirect is Redirecting HTTP on Other Ports

### ISSUE THREAD

**Issue by sw684** [Ylianst/MeshCentral#3763]
I have HTTP redirect enabled over to HTTPS for meshcentral from port 80 over to 443. I have an Apache web server setup for HTTP only using port 8000, I would think that the redirect server would only redirect port 80, but it is is also redirecting my port 8000 server to HTTPS.

**Comment by Ylianst** [comment]
I am not sure what you are configuring to perform the redirection. Is MeshCentral performing the redirection or Apache? Maybe you can include your config.json file to see what is going on. Please replace any personal or secret data with "xxxxxx" when posting your config.json. Thanks.

**Comment by sw684** [comment]
The redirect server is hosted by meshcentral, its redirecting my port 8000 http server hosted by apache...
Here is my config:
`{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "ema.lkitties.cf",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "suparezu@gmail.com",
    "names": "ema.lkitties.cf",
    "production": true
  }
}
`

**Comment by sw684** [comment]
does meshcentral's default port redirect server only modify traffic on port 80 or all http based services?

**Comment by si458** [comment]
meshcentral only listens on the ports you specify and if you dont specify anything the default 80/443
so the must be an issue with your apache OR your browser is doing redirects for you
i know my firefox sometimes even tho i right http://mysite.com:8181 it will try connecting to https://mysite.com:8181
