### ISSUE TITLE
Add option to run a shell script after MC update via web

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3768]
I have written a shell script to update MC and after that to codesign my windows agents right on my MC server. So in case of an update I just need to run my script and all is done. But I still need to SSH into my server for that every time.

On the other side there is the easy option to trigger an update of MeshCentral as admin right from the web UI in the server section. Much more easy but with the downside that the agents are not codesigned (I even do not know it the agents have received an update or not).

Some proposals here:

- A config option to run a custom shell script after an update was performed would be great. In this case you can make the update easily via web interface and MC will trigger the custom script to codesign the agents if there is any (or whatever other actions someone wants to perform after an update). Maybe with the additional option to run the script only when agents have beed updated.
- A notification if the agents are about to update or have been updated for those people who need to codesign them externally (i.e. when they need an USB key for that). That saves people from walking through Github each time to check if agents have received an update

**Comment by Ylianst** [comment]
Running a script on update is a good idea, I can add that in.

For agent change notification, note that you can create a folder called `meshcentral-data/agents` and place your agent binary files into that folder. Use the same names as agents in `node_modules/meshcentral/agents'. MeshCentral will use the agents in the `meshcentral-data/agents` first so, you can sign your agents and not have to worry about updating anymore.

One thing I can do is put a server warning when the agent in your custom agent folder are different from the default ones. You can then resign the agent on your own time.

Let me know if that would work for you.

**Comment by jacotec** [comment]
@Ylianst I already have my agents in `/meshcentral-data/agents`, but of course I want to benefit from updated agents ;-)

A server warning when the versions are different would be fine for me and will also help people who need to do manual actions to codesign their clients.

But when you automate your codesigning with a script the ability to run a script after updating would be nice though.

**Comment by smartekIT** [comment]
having an option to run script after update would be mush appreciated, I already have my own script to resign on linux using JSIGN but of course i have to run it manually after each update. if we can automate that would be perfect.

**Comment by Ylianst** [comment]
Ok, just added these:

```
  "settings": {
    "RunOnServerStarted": "c:\\tmp\\mcstart.bat",
    "RunOnServerUpdated": "c:\\tmp\\mcupdate.bat",
    "RunOnServerError": "c:\\tmp\\mcerror.bat"
  }
```

In all cases, the batch file or executable will be called when the server version as first argument. So %1 on Windows and $1 on Linux will be "1.0.0" or whatever the version is.

This will be in MeshCentral v1.0.0, but for the "RunOnServerUpdated" to work, you will need to restart the server manually once then it will get called when updating to "1.0.1".

**Comment by smartekIT** [comment]
wow. thank you so much. now I can have it all automated. the most important for me is:
<code>"RunOnServerUpdated": "/home/node/meshcentral/sign.sh",</code>

**Comment by jacotec** [comment]
Closing, because it worked perfect with the update 1.00 --> 1.01 ;-)

Thank you @Ylianst for implementing. BTW: Did you also implement the banner when the agent version is not up to date anymore (For the guys using hardware signating)
