### ISSUE TITLE
Router: "Doubled" Enter key

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshCentral#3771]
I was using a Windows Batch file (so a DOS box) which expects user inputs. Connected with the router, after entering the first parameter and "Enter", the second parameter was skipped and the third input is active - as if the "Enter" key would be submitted twice (second input got "just" the Enter which i never gave). It was impossible to run that script using the Router.

Using the remote Desktop via Browser worked fine.

**Comment by Ylianst** [comment]
I need a way to replicate the issue, can you send suggestion on this or screen shot? thanks.

**Comment by Martin900t** [comment]
I get this too. On a remote Win 10 desktop connecting through the router if I run a batch file that maps a drive:
net use V: \\server\backup /persistent:no
pause
I am prompted to enter the user name, but when I press Enter, the Enter key is sent twice, making it impossible to type the password, ie the prompt shows for the password but Enter is sent before I can type the password.
The double Enter also presents itself if I'm typing in notepad.
If I go to Settings and select Use Remote Keyboard Map I have no problem with the batch file or typing. I'm actually using the same model keyboard at local and remote computers so I don't know why that fixes it.
It would be great if Use Remote Keyboard Map were the default.

**Comment by jacotec** [comment]
It's happening that often that I'm forced to use the browser instead of the router for remote support ...

**Comment by jacotec** [comment]
@Martin900t Same here. I really love the router and it's so sad that it does not have full features (and Desktop feature) on MacOS. But this issue fully kills remote desktop use for me with it

**Comment by Martin900t** [comment]
The Use Remote Keyboard Map in router session settings doesn't help?

**Comment by jacotec** [comment]
I'm pretty sure I've double checked this without success, but I'll retest again

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
