### ISSUE TITLE
Chat as an independent option, without "connecting" to desktop?

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#3772]
![image](https://user-images.githubusercontent.com/45638572/158640412-965b6272-3267-493f-831b-50c7319c0b69.png)

Guys, 
When we want to initiate a connection to a client computer, it would nice to initiate a chat with them, without connecting to their desktop.  We then ask if it's "OK to connect?", and they say yes\no.  Then we connect and see their desktop.  Some people don't care much, but it would be nice to request a connection without intruding on their privacy.  I know we have assistant for this, but we have hundreds of computers not using the assistant at present and it would be nice to just request a chat only without seeing what they are doing .

Thanks
Shane

**Comment by Ylianst** [comment]
Interesting, that can be done!

**Comment by Ylianst** [comment]
Note that you can request a chat right now without connecting to the desktop by pressing the "Chat" button in the General tab.

![image](https://user-images.githubusercontent.com/1319013/158688046-4cfb219d-3c67-4a3a-8dd9-34dfbc97d6af.png)

Let me know if that works and if that changes your request.

**Comment by Ylianst** [comment]
Oh, also, the chat icon on the remote desktop works, even if you are not connected to remote desktop (same for the other icons present there). Let me know if that works for you.

![image](https://user-images.githubusercontent.com/1319013/158692084-246ece27-1eaa-4429-8485-a4a785ea2daa.png)

**Comment by southeasterntech** [comment]
Fair enough, that works perfectly.  Thought I had to connect to use the chat.  Disregard this then!  Closing.  Thanks as always!
