### ISSUE TITLE
User "Antivirus" logged into computers

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3774]
![изображение](https://user-images.githubusercontent.com/95762246/158773171-53da342b-6321-4d33-b3d8-1f7585ca0c5c.png)
how it works ? antivirus installed everywhere

**Comment by Ylianst** [comment]
Oh wow. Unless this is a mistake, you have a user called "Antivirus" that is logging in to your devices. What anti-virus are you using?

**Comment by gosteras** [comment]
> Oh wow. Unless this is a mistake, you have a user called "Antivirus" that is logging in to your devices. What anti-virus are you using?

No, no, they are different computers. I meant that somewhere it shows that there is an antivirus and somewhere it doesn’t

**Comment by PathfinderNetworks** [comment]
The 'Active User' line only appears if a user is currently logged in to the device. If the device is at a logon screen then the 'Active User' line will not appear (since there is no user currently logged in). 
Hopefully that makes sense. That is the expected behavior.
