### ISSUE TITLE
SSL certificate is correct in the mesh console, but is not applied in the URL

### ISSUE THREAD

**Issue by btsign** [Ylianst/MeshCentral#3776]
Hello,

I have run into an issue with setting up SSL for MeshCentral, I did everything by the guide. 

**config.json**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "DSconnect.dsignage.net",
    "WANonly": true,
    "_sessionKey": "MlkfjbnlsdjkhbflhjsdfdR*&G$**RBnwiuf*#@&*$&RG#",
    "port": 443,
    "selfupdate": false,
    "minifycore": false,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "WebRTC": true,
    "WsCompression": true,
    "AllowHighQualityDesktop": true,
    "AgentCoreDump": true,
    "ClickOnce": false,
    "_UserAllowedIP" : "127.0.0.1,::1,192.168.0.100"
  },
  "domains": {
    "": {
      "title": "DSignage",
      "title2": "Manage Devices",
      "_minify": true,
      "mstsc": true,
      "ssh": true,		
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "_agentCustomization": {
	"displayName": "DSMesh",
	"description": "MeshAgent for DSconnect.dsignage.net",
	"companyName": "DSignage",
	"serviceName": "TheDudes",
	"fileName": "DSmeshAgent"
      }	
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "email@email.net",
    "names": "DSconnect.dsignage.net",
    "production": false
  }
}
```

**console**
```
> le
{
    "configOk": true,
    "leDomains": [
        "DSconnect.dsignage.net"
    ],
    "challenges": {},
    "production": false,
    "webServer": true,
    "certPath": "/home/ec2-user/meshcentral-data/letsencrypt-certs",
    "skipChallengeVerification": false,
    "cert": "Present",
    "daysLeft": 87
}

> leevents
3/18/2022 4:13:44 PM - Getting certs from local store (Staging)
3/18/2022 4:13:44 PM - Reading certificate files
3/18/2022 4:13:49 PM - Certificate has 87 day(s) left.
3/18/2022 4:13:49 PM - Certificate is ok.
3/18/2022 6:18:23 PM - Certificate has 87 day(s) left.
3/18/2022 6:18:23 PM - Certificate is ok.
```

meshcenteral is using webserver-cert-public.crt even when I delete it, it still uses it hiddenly until I restart the AWS meshcentral server.

**Comment by gosteras** [comment]
"production":  true

**Comment by btsign** [comment]
From guide it should have replaced the certificate while the production is false, just that it wouldn’t be secure. My cert is still the default that expires in 2049. I also tested it with turning production to true, makes no difference. Used fresh installation of browser to open meshcentral, this is really confusing, I was able to follow the guide to a t other then the final result being a default cert. Can you give me some kinda direction that I should look into to troubleshoot this?

**Comment by Ylianst** [comment]
Your config.json and "le" command look ok. Note that you don't need to use the following two lines unless your using a different port:

```
    "aliasPort": 443,
    "redirAliasPort": 80,
```

So these can be removed. You can also remove "ClickOnce" since that feature was removed long ago. Using "production": false is the correct thing to do.

I don't see anything wrong. What version of MeshCentral are you using?

**Comment by btsign** [comment]
MeshCentral server version 0.9.99

I do get this one error in the server error log, could it be causing the problem?
ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.

**Comment by Ylianst** [comment]
This error:

```
ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
```

Is causing me to think that you are running MeshCentral twice. In that case, you would have a first instance of MeshCentral grabbing port 4433 and the second one will not be able to get that port. That would also mess up the TLS certificates as one instance would grab port 80 and use the Let's Encrypt certificate, the second instance would then not be able to grab 80 and fall back to using default certs.

In that scenario, you connect to port 443 and happen to connect to the second instance of MeshCentral that is using the default.

Check your processes to see if your starting up two instances on the same server?

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.21 and use node 18 or above
if issue persists then please reply back
