### ISSUE TITLE
Mesh Central is disconnecting agents

### ISSUE THREAD

**Issue by chuytheadmin** [Ylianst/MeshCentral#3777]
Mesh central keeps disconnecting various agents. I need to restart the computer or mesh agent service through PDQ for it to come back online. Any ideas on how to resolve this?

Mesh Server Version: 0.9.95

**Comment by Ylianst** [comment]
Add this line in the "settings" section of the config.json:

```
"agentping": 30
```

This should cause extra traffic to each agent every 30 second. See if it fixes it, if it does, try:

```
"agentpong": 30
```

If that still works try increasing the time to 60 and 120 seconds so you generate less traffic.
