### ISSUE TITLE
Autobackup config issue (Windows)

### ISSUE THREAD

**Issue by robuk123** [Ylianst/MeshCentral#3781]
Hi,
Firstly this software is awesome and I love that mostly, it just works. Thank you.
I have however ran into a small issue.
Migrated DB to MongoDB on Windows and getting error on Server page 

> WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed

I have set the following in the config.json which I thought may fix the issue: (taken from advanced config example)

`"AutoBackup": {
      "mongoDumpPath": "I:\\MongoDB\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 14
  }`

I have tried AutoBackup with various capitalisation also. The config examples has it written as autoBackup. No matter which I try I get:

> WARNING: Unrecognized configuration option "autobackup".
>WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed.

Any help appreciated :)

Many thanks

**Comment by robuk123** [comment]
Bit more testing, so I have added the path to mongoDB/mongodump to Windows and can run the command manually from a command prompt which creates an archive file. 

Running from Meshcentral console returns:

> Starting auto-backup...

> Auto-backup completed without mongodb database: Error: Command failed: "mongodump" -- 
 uri="mongodb://127.0.0.1:27017/meshcentral" --archive="I:\MeshCentral\meshcentral-backup\mongodump-2022-03-21-13-32.archive"
>'"mongodump"' is not recognized as an internal or external command, operable program or batch file.

**Comment by PathfinderNetworks** [comment]
Are you certain mongodump is located at "I:\\MongoDB\\bin\\mongodump.exe"?  The error is stating it can't locate mongodump.exe at that location.  In my case, for example, it is at "C:\\Program Files\\MongoDB\\Server\\4.4\\bin\\mongodump.exe"
Also, you will likely want to add the "backupPath" variable so you can specify where the backups should go (unless you are OK with them going to I:\MeshCentral\meshcentral-backup).

**Comment by PathfinderNetworks** [comment]
Can you post your full config.json (with any sensitive data, such as IP addresses, credentials, etc obfuscated)?
You want to make sure the "autoBackup" entries are nested under the "settings" section.

Like this example:
{
   "settings": {
   	  "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",   
	  "MongoDbBulkOperations": true,
      "RedirPort": 80, 
      "cert": "mesh.yourdomain.com", 
      "wanonly": true, 
      "selfupdate": false,
	  "desktopmultiplexor": true,
	  "WsCompression": true,
	  "AgentWsCompression": true,
	  "PublicPushNotifications": true,
	  "autoBackup": {
		"mongodumppath": ""I:\\MongoDB\\bin\\mongodump.exe",	  
		"backupIntervalHours": 24,
		"keepLastDaysBackup": 15,
		"backupPath": "I:\\whereyouwantthemtogo\Mesh Backups"
		}
   }, 

Edit out the backuppath entry if you don't want to change the location.  Pay particular attention to where the commas (,) go/don't go.

**Comment by robuk123** [comment]
Parrish,

I didn't have it nested under settings, thank you. I had become a bit blind to it after trying various alterations. Tested and all working now, thank you.

**Comment by PathfinderNetworks** [comment]
I've made the same mistake many times myself. ;-)
After a while it's hard to see what might be wrong, especially if you have a comma missing or in the wrong place, etc.  Glad to be able to help!
