### ISSUE TITLE
Desktop Connection Shows Setup...

### ISSUE THREAD

**Issue by montydepaola** [Ylianst/MeshCentral#3782]
After a recent update to the server to 0.9.99 and an update to the clients I can no longer attach to the desktops of system on the local network.

When I select connect I can either get the text "Setup..." next to the Connect Button
Or if I am lucky sometimes I will get two options such as...
Connected, Console
Active, RDP-Tcp#0 - JWRMESH/Username
Before when I selected the active session I would see the user desktop and could interact with it , now when I select the active session I go straight to the log in screen.
Both of these issues are only happening on the local network .

Very simple config file but I have not changed it in a very long time.
```
 {
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "myserver.mydomain.com",
    "port": 443,
    "redirPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "plugins": { "enabled": true }
  },
  "domains": {
	"": {
	"title": "JWR Mesh",
    "NewAccounts": "false",
    "mstsc": true,
    "CertUrl": "https://192.168.1.245:443"
	}
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
	"production": false
  }
}
```

**Comment by si458** [comment]
closing as stale, please update to the latest version 1.1.20 and if ur still having issues please reply
