### ISSUE TITLE
Issues activating AMT on Lenovo T410s

### ISSUE THREAD

**Issue by archont00** [Ylianst/MeshCentral#3783]
Hi,

I am not able to activate Intel AMT on t410s with MeshCentral:

- Automatic activation with MeshCentral did not work (client's host OS was Ubuntu 20.04)
- So I enabled AMT manually (BIOS + initial setup) and I can log in with user names & passwords at http://10.11.13.43:16992/ so long as the computer is off/suspended/running Windows 7 Enterprise. When booted to Ubuntu 20.04, the intel AMT web page is not accessible. I can remotely manage the computer via AMT web page (power on, power cycle). My hardware does not seem to support CIRA (there are no "Internet Options" next to "Network Settings").
- With both Ubuntu and Win7 and running MeshAgent:
  - MeshCentral shows "Intel ME: Activated, v6.1.10, Trying Credentials"
  - I can see "HW Connect" in Desktop tab, but it does not do anything.
  - I can see Intel AMT tab and menu, but connection does not work.

***Some more info***
With Ubuntu 20.04, the console `amt ...` commands fail - `AMT is not activated`.
With Windows 7 the console `amt ...` commands produce some output.
MeshCentral is running in Hybrid mode.

*(I have modified MAC addresses, UUID, and MeshCentral URL)*

```
> amt
{
  core-ver: 1
  OsHostname: "T410s-win"
  Flags: 4
  MeiVersion: "6.0.0.39684"
  Versions: {
    Flash: "6.1.10"
    Netstack: "6.1.10"
    AMTApps: "6.1.10"
    AMT: "6.1.10"
    Sku: "24584"
    VendorID: "8086"
    Build Number: "1052"
    Recovery Version: "6.1.10"
    Recovery Build Num: "1052"
    Legacy Mode: "False"
    undefined: [null]
  }
  UUID: "c0c9b0d7-1857-e011-92f6-deleted on purpose"
  ProvisioningMode: 1
  ProvisioningState: 2
  net0: {
    enabled: 1
    dhcpEnabled: 1
    dhcpMode: "ACTIVE"
    mac: "XX:XX:XX:XX:XX:XX"
    address: "0.0.0.0"
  }
  net1: {
    enabled: 1
    dhcpEnabled: 1
    dhcpMode: "PASSIVE"
    mac: "XX:XX:XX:XX:XX:XX"
    address: "43.13.11.10"
  }
}
```
```
> amtevents
No events.
> amtconfig
> amtevents on
Intel AMT configuration events live view enabled.
{}
{}
{}
{}
```
```
> info
Current Core: Feb 21 2022, 2908578550
Agent Time: 2022-03-21 18:22:44.699+01:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://meshcentral.mydomain.net:443/agent.ashx.
Built-in LMS: Disabled.
OS: Microsoft Windows 7 Enterprise  - 7601.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner, win-console, win-info, win-securitycenter, win-terminal, win-virtual-terminal, routeplus, scripttask.
Server Connection: true, State: 1.
```
P.S. Connecting to https://meshcentral.mydomain.net:4433/ fails due to certificate issues raised by my browser "NET::ERR_CERT_AUTHORITY_INVALID" (not trusted issuer "MeshCentralRoot-f75c3a"). Otherwise, the standard port 443 is behind nginx proxy (with Let's Encrypt certificate).

Any hints how to proceed further?

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
