### ISSUE TITLE
Quick question on updates?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#3784]
Hi After updating to meshcentral 0.9.99

the automatic clipboard feature it seems that i cannot find it not sure if i need to enable something on the config of the server? 

![image](https://user-images.githubusercontent.com/13953629/159376343-8ce47214-88aa-44c0-b238-84fd9b065b7c.png)

and the npm audit not sure why its not working

```
root@remote:~# npm audit meshcentral-data/
npm ERR! Invalid audit subcommand: `meshcentral-data/`
npm ERR!
npm ERR! Usage:
npm ERR!
npm ERR! npm audit [--json] [--production]
npm ERR! npm audit fix [--force|--package-lock-only|--dry-run|--production|--only=(dev|prod)]

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-21T22_56_02_879Z-debug.log

```

Thank you

**Comment by Ylianst** [comment]
The auto-clipboard feature only works on some browsers. Notably it works with Chrome and not with FireFox. Let me know if that is what you see.

As for "npm audit", not sure why your trying to audit the meshcentral-data folder, here is no code in that folder.

**Comment by killmasta93** [comment]
thanks for the reply, the auto-clipboard shows on chrome, but it seems that the copy and paste to the client works fine but from the client back to me does not let me paste or copy 

as for the npm audit that would only apply every time i update meshcentral?

Thank you
