### ISSUE TITLE
Restrict Login Token creation

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3787]
Hi Ylian,

Currently, any user can able to create Login Token. Can you restrict the same from admin only / selected users only?

**Comment by Ylianst** [comment]
Just added this, will be in v1.0.1. In the domain section of the config.json, add a "PasswordRequirements" section and in it, you can set "loginTokens" to false to deny all users, or set a list of user identifiers. For example:

```
      "PasswordRequirements": {
        "loginTokens": [ "admin", "admin2" ]
      }
```

Or use the full user identifier also works:

```
      "PasswordRequirements": {
        "loginTokens": [ "user\\admin", "user\\admin2" ]
      }
```

Once published, let me know if it works.

**Comment by smartekIT** [comment]
if hosting on Linux shouldn't be the following ? or it doesn't matter ? Thanks
<pre>
     "PasswordRequirements": {
        "loginTokens": [ "user//admin", "user//admin2" ]
      }
</pre>

**Comment by Ylianst** [comment]
You right, the correct syntax is `user//admin' on all platforms. A user id is `user/domain/identifier`, the default domain is empty so for users on the default domain, it's `user//identifier`. I messed up my / and \.

**Comment by VINISHVV** [comment]
@Ylianst - Thanks.
Its working fine.
