### ISSUE TITLE
localisation of the "<URL>/agentinvite&c=<HASH>" URL

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#3788]
I wonder, can I enable localisation on agentinvite (my customer don't speak english, obviously, they're french) ? if so, can you say me how ? if no, can I help you with this (given the fact that every meshcentral's page is localised !). 
thanks

**Comment by Ylianst** [comment]
The /agentinvite page should be automatically localized based on the user's browser settings. If that is not happening, it's a bug. I will have to test this.

**Comment by Ylianst** [comment]
The "agentinvite" page language is auto-selected based on browser information, but I did notice that if the browser language is "fr-ca" for example without providing "fr" as a acceptable language, the page would show up in English. I fixed this, will be in v1.0.1.

![image](https://user-images.githubusercontent.com/1319013/160011841-61cdb0c0-4f2c-47af-8b2b-33a948722e25.png)

If you see something different I did not catch, let me know.
