### ISSUE TITLE
Agent error install

### ISSUE THREAD

**Issue by gesandovalr** [Ylianst/MeshCentral#3791]
Hi I'm trying to install the agent on a Windows Server 2012 R2 std the agent I get this error.

[2022-03-22 05:37:47 PM] [E00D0B58B943DA56] ..\microscript\ILibDuktape_ScriptContainer.c:1635 (0,0) uncaught: 'cannot re
ad property \x27split\x27 of null'

I don't know what could cause this.

**Comment by krayon007** [comment]
What server version of Mesh Central are you using? And which install method are you using?

**Comment by jsaltzman** [comment]
I am running into the same issue. I am running the most up to date docker container: typhonragewind/meshcentral. I am not sure how to check version otherwise. When I click add agent and download the windows agent (32 and 64 bit), I get the same error.

**Comment by krayon007** [comment]
I'll test a fresh install on Server 2012 R2 and see what I can find out

**Comment by gesandovalr** [comment]
> What server version of Mesh Central are you using? And which install method are you using?

Sorry for not mention this earlier it's windows server 2012 R2.
Agent Version 0.2.1.3 64 Bits.

**Comment by krayon007** [comment]
For the downloaded agent, what does it report if you run the command:
`MeshAgent -info`

I tried with the current server, on both Windows Server 2012 and Server 2012 R2, and could not reproduce the installation error.

**Comment by jsaltzman** [comment]
![image](https://user-images.githubusercontent.com/2000982/160177280-00ede565-9e90-46c4-a401-f5bdbffadf08.png)

**Comment by arduin0guru** [comment]
Update windows and check .

**Comment by si458** [comment]
This fixes the issue

```
net stop winmgmt /y
   Winmgmt /resetrepository
   winmgmt /verifyrepository
```

**Comment by idanvn** [comment]
try to install it like that
.\meshagent64-MikeOrto.exe -install 
on PowerShell

**Comment by si458** [comment]
@idanvn
using `-install` will setup the exe from wherever the exe is currently located
using `-fullinstall` will copy the exe to `Program Files` and setup from there
