### ISSUE TITLE
Is Meshcentral Firebase still working?

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3794]
for some how I never got a successful push notification 2FA.
I enabled the public push notification in the config.
i enabled the push notification 2FA in my account.
i installed the app on my phone and it's recognised in my account and in the devices group.
i can receive push messages from the server on the mobile app fine, but not the 2FA push notifications going through meshcentral.com and it's Firebase ?
basically I've done all the steps mentioned here: https://github.com/Ylianst/MeshCentral/issues/2495

is it my IP maybe blocker by your server or my firewall blocking traffic to meshcentral.com ? but i receive updates fine and all my settings working fine. i even checked my config.js online based on your schema and recommendations and all good. I'm out of options. any help please?

do we have to set our own Firebase account, and can we? how to implement after having firebase account?

here what I have in the console:
<pre>
> relays
No relays.
> firebase
{
  "mode": "Relay",
  "sent": 0,
  "sendError": 0,
  "received": 0,
  "receivedNoRoute": 0,
  "receivedBadArgs": 0
}
</pre>

![image](https://user-images.githubusercontent.com/70715469/159894375-04e64f3a-d2bc-44a0-9e14-7c4ef08c95da.png)

**Comment by VINISHVV** [comment]
@smartekIT - Can you try remove push notification from your profile and add it once again.

I hope this will resolve the issue.

**Comment by smartekIT** [comment]
already did that, i even removed my phone from the whole server then re-added it again but no hope.
every things works except any action related to 2FA and meshcentral.com firebase.

for example i can send messages to my phone, also i can connect to it and view it fine.

**Comment by VINISHVV** [comment]
Are you accessing your server using local IP ( https://localhost  or https://192.168.X.X ).

If you are trying with local IP then it will not work. If we use the domain name then its works fine.

**Comment by smartekIT** [comment]
accessing with fully working domain and it's hosted on fully qualified subdomain with Let's encrypt certificate.
unless the firebase to work need to open special port for outbounds.

**Comment by smartekIT** [comment]
how about integrate our own firebase account, would that work. or to be able to do that we need to be the owner of the Android App ?

**Comment by Ylianst** [comment]
Public push notifications thru MeshCentral.com should work. I will test it again and see if there are any issues.

**Comment by Ylianst** [comment]
I just tested public Firebase push notifications and it works for me. I just added this line in the "settings" section of the config.json:

```
"PublicPushNotifications": true
```

Also, make sure your server can connect to meshcentral.com. You can test the system by going to a Android phone that is not connected, hitting the "Message" button and sending a message. The "firebase" command should show a message sent and the message should display on your phone even if the MeshAgent agent is not currently being used.

![image](https://user-images.githubusercontent.com/1319013/160007571-72eda9f3-7751-4e94-9631-cb9157d6326f.png)

Let me know if this works.

**Comment by smartekIT** [comment]
@Ylianst thanks for looking into this, but i already have this in my settings:
<code>"PublicPushNotifications": true</code>
and i already tested my phone with messages and i can receive messages on my phone normally, but not the firebase 2FA notifications.
whenever i try that i get the connection error, look at the screenshot i posted earlier.
any idea? much appreciated.

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/160020221-4e86d565-a981-4b55-8c8f-026935590855.png)

sending messages fine, but no 2FA
![image](https://user-images.githubusercontent.com/70715469/160020331-ded257fb-f6ac-4e6c-95c3-adc33712fbbe.png)

**Comment by Ylianst** [comment]
Oh! I see now. The login page is trying to make a websocket connection to the server and that is not working. This is not an Android or Firebase issue, this is your browser's page not connecting to the server. Can you open the browser console and look for any errors? Do you have a firewall or reverse proxy blocking some URL's?

**Comment by smartekIT** [comment]
i do have Fail2ban firewall installed on the server, also the whole server is running behind Nginx Proxy Manager where the Nginx Proxy Manager taking care of the LE certificate and http/https forwarding.
but strangely all other services working fine, the Nginx working very well with the settings i have in MC.

**Comment by smartekIT** [comment]
this is the error i have in the browser console:
<pre>
Refused to connect to 'wss://remote.example.com:444/2fahold.ashx?c=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' because it violates the following Content Security Policy directive: "connect-src 'self' *.openstreetmap.org wss://remote.example.com".

startup @ (index):526
</pre>

**Comment by smartekIT** [comment]
of course in the above I changed my domain name to example.com and I replaced any sensitive data to XXXXX to hide only here.

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/160024829-6484a734-2e87-4a5e-a39b-84c4a0ca4f94.png)

**Comment by Ylianst** [comment]
Ok, now we are getting somewhere. Your running on port 444 and it's causing the issue. Let me work on that.

**Comment by smartekIT** [comment]
> Ok, now we are getting somewhere. Your running on port 444 and it's causing the issue. Let me work on that.

Thanks heaps

**Comment by Ylianst** [comment]
What browser are you using? Looks like it may be browser specific - but still very much a bug.

**Comment by smartekIT** [comment]
the screenshot was taken from MS Edge, but the same with Chrome. i haven't tried Firefox though but will do if you need me to.

**Comment by Ylianst** [comment]
Or... are you using a reverse proxy with MeshCentral on port 444 and "aliasPort":443 ??

**Comment by Ylianst** [comment]
Can you send over any port/alias/agentport/aliasagentport settings you have in your config.json?

**Comment by smartekIT** [comment]
<pre>
    "port": 444,
    "_portBind": "127.0.0.1",
    "aliasPort": 444,
    "redirPort": 82,
    "_redirPortBind": "127.0.0.1",
    "redirAliasPort": 80,
</pre>

when i browse to the server, i just go https://remote.example.com
as you can see without entering any ports in the url, then the Nginx Proxy Manager forward all the requests on that domain to port 444 using https protocol.

in the cert part of my config.js i have:
<pre>
"cert": "remote.example.com",
</pre>

also i have the following in my config.js :
<pre>
    "_tlsOffload": "127.0.0.1,::1",
    "trustedProxy": "127.0.0.1,::1,172.0.0.0/8",
    "mpsPort": 4433,
    "_mpsPortBind": "127.0.0.1",
    "mpsAliasPort": 4433,
    "mpsAliasHost": "mps.example.com",
    "_mpsTlsOffload": true,
</pre>

**Comment by Ylianst** [comment]
Oh! So, if externally MeshCentral is using port 443, you should have:

```
    "port": 444,
    "aliasPort": 443
```

That says, bind on 444 but assume your running on 443. It don't know how your current config can work for agents unless you also made port 444 public for agents to connect to?

Change the alias port and let me know if it fixes it.

**Comment by smartekIT** [comment]
Port 444 is open for public so agents can see it externally and MC
listening on that port for agents.

Everything is working fine this for the last 12 months since I installed it
on this server.

**Comment by smartekIT** [comment]
if i change alias port to 443, wouldn't that stop my agents, or meshRouterCmd from working?

**Comment by smartekIT** [comment]
Confirming that after I changed the alias port to 443, it's working now.
but how about other services I have, wouldn't that affect other communications? e.g. agents, router, RouterCMD ..etc

**Comment by Ylianst** [comment]
Other software should work just fine. The question for me is how could the agent have worked before? By saying `"aliasport": 444` you where telling agents to connect to external port 444. So, I expect you have your external port 444 mapped to 444 of the MeshCentral server. Now that you have this fix, newly installed agents will use port 443 to connect to the server, but always installed ones will use 444.

**Comment by smartekIT** [comment]
> Other software should work just fine. The question for me is how could the agent have worked before? By saying `"aliasport": 444` you where telling agents to connect to external port 444. So, I expect you have your external port 444 mapped to 444 of the MeshCentral server. Now that you have this fix, newly installed agents will use port 443 to connect to the server, but always installed ones will use 444.

yes you're right, in front of Meshcentral server i have port 444 forwarded to Meshcentral server on port 444.
in the config.js i had:
port: 444
portalias: 444

and all my agents connects to the url with port 444 part of the url.
now after i changed the alias port to 443,
i noticed any new agent generated link is the domain address without including :444 in it.
but to have the existing agents still connecting to server, then i need to keep the port forwarding of 444 in front the server.
i think i should keep this port forwarding enable until i push a re-install to all my existing agents so they can connect on the new url which doesn't include port in them.

existing agents url: wss://remote.example.com:444/
new agents url: wss//remote.example.com/

@Ylianst we learn a lot from your videos published on youtube. i think we need a special video explaining just how the ports work, port, portalias, redirPort, redirPortAlias ...etc
and what the difference, and how to manage these ports on existing servers where Nginx Proxy Manager and ports like 80 and 443 is in use and can't be dedicated to MC.

Thanks heaps bro.
