### ISSUE TITLE
Web SSH not appearing even with "ssh": true, indicated in domains

### ISSUE THREAD

**Issue by jsaltzman** [Ylianst/MeshCentral#3799]
I am having issues with the webssh feature. It is not appearing for my local device that I added. My config is below.
```

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mesh.####.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "####",
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "MyServer",
      "title2": "Servername",
      "minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "ssh": true,
      "mstsc": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "####@gmail.com",
    "names": "mesh.####.com",
    "production": false
  }
}
```

**Comment by Ylianst** [comment]
What version of NodeJS are you using? You can type `info` in the server console and look for "nodeVersion"

![image](https://user-images.githubusercontent.com/1319013/160021937-56544188-a75c-4d41-aed2-66f8ee846944.png)

SSH will only work with NodeJS v11 and higher.

**Comment by jsaltzman** [comment]
I ran node --version in the docker container and it indicated its version 17.7.2.

**Comment by Ylianst** [comment]
Ok, next, when you add the local device, do you select Linux or MacOS?

![image](https://user-images.githubusercontent.com/1319013/160022687-d9ee8297-0a30-49f7-bcd8-2fb63804fd19.png)

**Comment by jsaltzman** [comment]
Linux:

![image](https://user-images.githubusercontent.com/2000982/160022790-c74be9b8-d129-4b85-aef1-6335be2d0c90.png)

**Comment by Ylianst** [comment]
Go in the source code of your web page, search for "features2"

```
        var debugLevel = parseInt('');
        var features = parseInt('152205472');
        var features2 = parseInt('4262603');         <------------
        var sessionTime = parseInt('60');
        var sessionRefreshTimer = null;
```

Tell me what number you see in pasrseInt();

**Comment by jsaltzman** [comment]
var features2 = parseInt('786561');

**Comment by Ylianst** [comment]
So, 786561 are these bits:

```
1100 0000 0000 1000 0001‬
```

However, if the SSH feature is enabled, you should have this bit:

```
0000 0000 0010 0000 0000‬
```

So, the server is saying SSH is disabled... but your config.json has it enabled. The only way this should be possible is if you are running NodeJS v10.

Can you run "info" on the server console and send back what you see?

**Comment by jsaltzman** [comment]
See here:
![image](https://user-images.githubusercontent.com/2000982/160029190-e773c23c-264b-4480-9379-ac647f98572f.png)

**Comment by si458** [comment]
Plz try latest version 1.1.20 and reopen if issue still persists
