### ISSUE TITLE
Add Support for Windows Session Selection for Desktop

### ISSUE THREAD

**Issue by imposhster** [Ylianst/MeshCentral#38]
When supporting environments where there are multiple users logged into a single device (servers and terminal services sessions) It would be useful to be able to select the session ID based on ID and/or username that I would like to shadow using Desktop.

**Comment by jsastriawan** [comment]
MeshCentral 2 has TCP tunnelling capabilities. User could use MeshCmd to create tunnels to any TCP port at device through MeshAgent connection.

For this shadowing, I think it will be easily achievable using native MSRDP application tunneled through MeshAgent tunnel relay.

MeshCmd can do this or you can try my mc2router application. 
https://github.com/jsastriawan/mc2router

Let me know if this help.
Regards,


Joko

**Comment by Ylianst** [comment]
The original port was about something different. I will check with Bryan, I think it may be possible. I think we have a way to enumerate users currently logged into the system and should be able to use that information to select the session. I really need to install Windows server and start doing more testing on this topic. Probably something that will come later as was are a bit swamped with more critical bugs right now.

**Comment by openmoto** [comment]
I'm also interested in this feature..
Thanks

**Comment by Ylianst** [comment]
I did check with Bryan ([krayon007](/krayon007)) and he will be looking into this one. As a way of introduction, Bryan is focused on the MeshCentral2 agent while I do the server/webapp. Right now we remote desktop "zero", the physically attached one, but should be able to switch.

**Comment by IntExCZ** [comment]
Yes, I'm interested too.
Thank you

**Comment by Ilia1** [comment]
have you seen this project https://github.com/sshtools/rdp2vnc? This may help in solving the issue.

**Comment by krayon007** [comment]
We have code to select the session already, we just need to retool the ux and the ipc to the child process to pass the session ID.

**Comment by Ilia1** [comment]
WOW, you did it! 🥇 
but when there are many users, the session selection list does not scroll. Fix please.

**Comment by Ylianst** [comment]
Can you open a new issue about the session selection list not scrolling? This is an old thread and will close it. This way, I can track issues correctly. Thanks.
