### ISSUE TITLE
a lot of memory meshagent

### ISSUE THREAD

**Issue by DEFALTtttttt** [Ylianst/MeshCentral#3800]
There was a problem when logging into the server, I see that the computer is turned off, but in fact it is turned on and the meshagent works, but consumes a lot of memory. Only by ending the process through the task manager does it restart and appear on the server as enable
![Screenshot_3](https://user-images.githubusercontent.com/102130048/160083817-b4f559af-dd1e-4657-8730-df5ddb4f5c69.png)
![Screenshot_4](https://user-images.githubusercontent.com/102130048/160083845-aa1e9f87-e36b-47a8-8d85-bfae15c7cf3b.png)
d
And this problem is observed on many PC.

**Comment by krayon007** [comment]
What OS version are you observing this on? What Mesh Central version are you running?

**Comment by DEFALTtttttt** [comment]
> What OS version are you observing this on? What Mesh Central version are you running?

OS Windows 10 Pro - 21H2/19044
MeshCentral - 0.9.99

**Comment by Ylianst** [comment]
Are you running MeshCentral with any plugin's?

**Comment by Ylianst** [comment]
Oh good. We like it when it's standard. Plug'ins are not in our control. If you see an agent that uses a lot of RAM, can you run "fdsnapshot" in the agent console and send back what you see? Should look something like this:

![image](https://user-images.githubusercontent.com/1319013/160178668-6155f861-289d-412d-8490-8eb8150cffa6.png)

**Comment by DEFALTtttttt** [comment]
> Oh good. We like it when it's standard. Plug'ins are not in our control. If you see an agent that uses a lot of RAM, can you run "fdsnapshot" in the agent console and send back what you see? Should look something like this:
> 
> ![image](https://user-images.githubusercontent.com/1319013/160178668-6155f861-289d-412d-8490-8eb8150cffa6.png)

The problem is that the computer at this moment shows that it is turned off, so I cannot start the console at this moment. Even though the computer is on.

**Comment by DEFALTtttttt** [comment]
> Oh good. We like it when it's standard. Plug'ins are not in our control. If you see an agent that uses a lot of RAM, can you run "fdsnapshot" in the agent console and send back what you see? Should look something like this:
> 
> ![image](https://user-images.githubusercontent.com/1319013/160178668-6155f861-289d-412d-8490-8eb8150cffa6.png)

![image](https://user-images.githubusercontent.com/102130048/160986393-4f6be5f7-fb03-4e63-9d74-9a62891734bd.png)

**Comment by DEFALTtttttt** [comment]
again 
![image](https://user-images.githubusercontent.com/102130048/160988516-54f125f5-05ff-40dd-9c18-8beff3c83a95.png)
![image](https://user-images.githubusercontent.com/102130048/160988541-4c8051d4-64c4-4427-9d86-71087f211d89.png)

the agent consumes a lot of memory, shows that the computer is turned off, in fact it is turned on
