### ISSUE TITLE
Blank Screen after use Translator

### ISSUE THREAD

**Issue by KBCACheia** [Ylianst/MeshCentral#3801]
Hi, as the title says, i have used the Translator to fix some parts of PT-BR translation and add some new parts, but after  i click "Save to Server" and "Translate Server" buttons., the server didn't restart as the pop up said it would and the server do not updated the words translated. So, i did a manual restart, but then, i got a blank screen:

![mesh-pt-br](https://user-images.githubusercontent.com/5051443/160127005-a7eadae2-5062-4510-95af-f9a6efec4afb.PNG)

So, i putted `?lang=en` after the url to force english and everything worked fine:

![mesh-en](https://user-images.githubusercontent.com/5051443/160127363-4bc72dc2-a688-44ee-b146-4eb87777aeed.PNG)

Then i downloaded the translate.json from github trying to bring back everything to original, but it no work. By now, i am using the server in english.

I have send the updated translate.json to Ylian email, i feat it was something in the json, but after i download the github version and the problema persist, i don't know.

Thanks.

**Comment by Ylianst** [comment]
On the blank page, you can open the browser console and look at the error. This happens often if the translation is not right and, for example, there are incorrect "quotes" or incorrect / or \ in translation strings.

To fix this, you can create a temporary folder and run `npm install meshcentral`, then take the files from `node_modules\meshcentral\views\translations` and copy them in your server at the same path. That will fix the problem.

**Comment by KBCACheia** [comment]
Hum, i got it. I have sent to your e-mail the translation file. Please check the file fix it, its updated and all new entry is translated.

Today i updated the server and everything is fine again.
