### ISSUE TITLE
Insert new fields in export user List 

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3802]
Dear Ylian,

Can you please include below New fields in user export options.

Permissions / User role  ( Administrator / Manager / User / user* / Partial )
Last Access
Status ( Active/Locked)

**Comment by Ylianst** [comment]
Ok, working on this now.

**Comment by Ylianst** [comment]
Just added these:

![image](https://user-images.githubusercontent.com/1319013/160472131-993ce80a-69e1-4180-ab82-603c0080c2a1.png)

Let me know if this works. It will be in v1.0.2.

The last access is already present (sort of), called "lastlogin".

**Comment by VINISHVV** [comment]
Dear Ylian,

Thanks, Its seems the report having some issues.

For me all the admin users are showing Locked =1. But actually the users are active/unlocked status.

Also if possible add the user roles like ( Administrator / Manager / User / user* / Partial )

**Comment by dinger1986** [comment]
@si458 this has gone stale

**Comment by si458** [comment]
closing as indeed stale, if still having this issue, please let us know
