### ISSUE TITLE
NGNIX Config Required

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#3803]
Hi All,

Please share the working NGNIX configuration & Mesh central configuration file for windows.

**Comment by Ylianst** [comment]
See section 16 of the [MeshCentral User's Guide.](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf) Let me know if that works. I also have a [YouTube video here](https://www.youtube.com/watch?v=YSmiLyKSX2I).

**Comment by Mfinadmin** [comment]
Thanks @Ylianst
