### ISSUE TITLE
Web-RTC connected: black screen

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#3806]
Both machines on the LAN.

MC v1.0.1

Web-RTC say connected but I get a black screen.
There is mouse movement on the remote pc.
![mc_blank](https://user-images.githubusercontent.com/47568278/160293065-fac85e71-a189-41a9-800c-399be948cffd.png)
![mc2_os](https://user-images.githubusercontent.com/47568278/160293066-5d7da460-22a8-4ad7-9f6e-92e73e7a7f49.png)

**Comment by Ylianst** [comment]
Can you disconnect, click "Settings" and change to a very low quality setting, like 5% and try again? Let me know if the quality setting makes a difference.

**Comment by krayon007** [comment]
Which browser are you using? Is it Chrome? There is a known issue right now with Chrome... A recent Chrome update broke WebRTC for that browser. I haven't root caused that one yet, but I verified it still works on Edge and Firefox.

**Comment by FATeknollogee** [comment]
> Can you disconnect, click "Settings" and change to a very low quality setting, like 5% and try again? Let me know if the quality setting makes a difference.

5% setting did not make a difference.

**Comment by FATeknollogee** [comment]
> Which browser are you using? Is it Chrome? There is a known issue right now with Chrome... A recent Chrome update broke WebRTC for that browser. I haven't root caused that one yet, but I verified it still works on Edge and Firefox.

Firefox works, thanks!

**Comment by lexisman** [comment]
Same here, however when I downgraded back to the stable version of meshcentral, chrome, opera works, no issue.

**Comment by krayon007** [comment]
> Same here, however when I downgraded back to the stable version of meshcentral, chrome, opera works, no issue.

Are you sure? I just downgraded to stable, and still see the same issue with WebRTC on chrome. Sometimes it shows black screen, sometimes it doesn't, but in both cases, the screen doesn't refresh.

**Comment by lexisman** [comment]
Sorry I thought if I replied through email it will also be reflected here. Anyways, yes it works pefectly in both windows 10 and linux desktop. After I downgraded to stable version, I can connect to the windows desktop and linux desktop gui and control the remote desktop from Vancouver to Montreal. I control the remote desktop to edit a video.

**Comment by bartjackbakker** [comment]
since a few day's we have the same issue on edge. Still trouble shutting it.

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.21 and use node 18 or above
if issue persists then please reply back
