### ISSUE TITLE
Generic OpenID Connect Support

### ISSUE THREAD

**Issue by mstrhakr** [Ylianst/MeshCentral#3808]
We have SAML and a few others but OIDC seems to be an exception. Is this something we can get or maybe its possible already and I've just missed it? I could use some help.

**Comment by Ylianst** [comment]
If I am not mistaking, AZURE uses OpenID and it's documented in section 26.3 of the [User Guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf). However, you right that I don't have a generic OpenID connect. Is there a specific service your looking to work with? I would need a reference service to test with.

**Comment by mstrhakr** [comment]
I will open a new issue with that request and some more specifics, thank you.
