### ISSUE TITLE
7 days power statistics doesn't show а PCs reboots

### ISSUE THREAD

**Issue by jamgrorg** [Ylianst/MeshCentral#3809]
Hi there. I've noticed that 7 days power statistics doesn't show a PCs reboots. I think that it happens cos the rebooting time is too short and agent seems can't register it. What can be done to make it show it?
![image](https://user-images.githubusercontent.com/2796027/160359240-11229501-2e8d-4174-b35c-03b1f11088e4.png)
There was 2 reboots at that time period.

**Comment by Ylianst** [comment]
Ha yes. If a computer disconnects from MeshCentral and reconnects within 5 minutes, MeshCentral will not log it in the power log. I did this because with a large number of devices, the power log would get really big, especially with devices on WIFI that have intermittent connectivity.
