### ISSUE TITLE
Notification settings behaviour

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#381]
When notifications are set disabled in user account properties and in one or more device groups enabled notifications, I expect no notifications at all. I still receive notifications from the groups where it has been enabled.
When notifications are set enabled in user account properties and in some device groups enabled, I expect only notifications for the device groups where it has been set enabled. Not also notifications where it has been set disabled in device groups.
I think this behaviour is a bug.

**Comment by Ylianst** [comment]
Your analysis is correct. I will fix this.

**Comment by Ylianst** [comment]
Behavior changed in MeshCentral v0.3.8-p. Feedback appreciated.

**Comment by hunter-nl** [comment]
Yes, fixed. Thank you so much!
