### ISSUE TITLE
web-rdp clipboard not work

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#3810]
web-rdp clipboard not work.  

will this possibility be implemented?

**Comment by gosteras** [comment]
OK thanks

**Comment by Ahmet-Kaplan** [comment]
Someone was added clipboard feature : https://github.com/wfridy/node-rdpjs/commit/5d5f4d3895d7dd631683cf50ea1ed412c11f3ef1

**Comment by Ylianst** [comment]
OH WOW!!! OK, I will be adding that!!!

**Comment by Ylianst** [comment]
Good find! I just did a first pass at adding RDP clipboard support and it worked. Will be in next release.

**Comment by si458** [comment]
added here - https://github.com/Ylianst/MeshCentral/commit/9986567cf03caf4040a162acb14b7128daa77198 https://github.com/Ylianst/MeshCentral/commit/b01078bf5590c949e9cdd1a7739f595c8f2f4aaa
