### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by timcanty** [Ylianst/MeshCentral#3812]
Having an odd issue when i try to update meshcentral from 0.9.99 to 1.0.1,

(Which is the same producure i've gone through all the other times)

sudo systemctl stop meshcentral.service
sudo npm install meshcentral
sudo systemctl start meshcentral.service

no errors are displayed, but when i go back to check the server version in the interface, its still showing 0.9.99

have tried renaming the node_modules, and making it download them again, but still it stays as 0.9.99

Any suggestions what else to try to make it update? assuming this isn't a bug in the version number change?

**Comment by Ylianst** [comment]
Try explicitly specifying the version:

```
sudo systemctl stop meshcentral.service
sudo npm install meshcentral@1.0.1
sudo systemctl start meshcentral.service
```

Let me know if that works.

**Comment by timcanty** [comment]
yeah that force it to update.
Thanks for the advice

**Comment by OutbackMatt** [comment]
I found that the auto update didn't work for the same version jump, but a manual update through the admin GUI worked fine
I remember having / seeing issues reported with a previous version major numbering change, but I can't find the relevant 'issue'
