### ISSUE TITLE
How to modify the name of the client ?

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#3817]
Hi , i don't remember or i'm not able anymore to revert back to the default the name of the client , i'll try to explain:
some months ago i modified the name of the client adding Tamara in the name , like this:
![immagine](https://user-images.githubusercontent.com/62424179/160552276-718ea3aa-fe86-412d-af79-41d56a7f3238.png)
Now if i click to edit it and i clear the name , the ok button became gray :
![immagine](https://user-images.githubusercontent.com/62424179/160552517-5f1190f8-ab01-4099-a03f-492ca5d0271b.png)
how can i solve the problem?

**Comment by nicrame** [comment]
You can't leave it empty. By default it just copy hostname (Nome del sistema operativo) to be name.

**Comment by tradexsrl** [comment]
mmm strange look at this one:
![immagine](https://user-images.githubusercontent.com/62424179/160582457-b19a0fba-7702-46d0-888e-a424c3c0f2dd.png)
there is no way to add or modify the name...and in this case i have never added a name like in the previous example

**Comment by tradexsrl** [comment]
it seems from a version the way it manage the name are changed

**Comment by tradexsrl** [comment]
and if you look in the case of Tamara , there is error in "nome del sistema operativo" which in english will be translated to operative system name...but instead of the OS name i get the PC name
Tamara's pc is a windows 7 OS

**Comment by tradexsrl** [comment]
i think @Ylianst should take a look

**Comment by tradexsrl** [comment]
Forgot to mention mesh central is v1.0.0

**Comment by Ylianst** [comment]
Hi. So, it's working as expected. When a computer first joins, the operating system name is also the name of the device on the server. Also, if the device server name is the same as the operating system name, the operating system name is not displayed. So, just change the name of the device back to the operating system name, you can cut & paste like this:

![image](https://user-images.githubusercontent.com/1319013/160756739-3534caee-a4df-4953-b232-8254591de827.png)

After that, the "Operating System Name" will not show.

If you always want the server name to be the operating system name, you can go in the device group, in feature and sync the name like this:

![image](https://user-images.githubusercontent.com/1319013/160756895-093fa3c0-0df6-4bd7-a302-7760c6ca7ff5.png)

The next time the device connects, it will sync the name. Let me know if this works.

**Comment by tradexsrl** [comment]
yes found the where it was the problem...i remember a feature of sync server device name but i was not able to find it...i click on that group and found it was missing the check on sync server name
because the group name is not underlined i was not immediately think it can be click to show the group property.
