### ISSUE TITLE
Terminal - Full screen button and exit from full screen are on opposite sides

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#3819]
On desktop tab it has been fixed in #3749, can be done the same for Terminal tab please?

Thanks.

**Comment by Ylianst** [comment]
Oh right. That makes sense... working on it now.

**Comment by Ylianst** [comment]
Fixed! Good suggestion. Will be in v1.0.2.

**Comment by vitko-bg** [comment]
Thanks. Once 1.0.2 is out will check :)
