### ISSUE TITLE
AgentSelfGuestSharing

### ISSUE THREAD

**Issue by gianlucaromito** [Ylianst/MeshCentral#3821]
Hello.
I cannot get the function in object to work:
In config json I put this:

```
  "domains": {
    "": {
      "AgentSelfGuestSharing": true,
```

I use SAML to login to the meshcentral (I don't know it this is relevant)

The expected result is to have the mesh central Assistant offer the option to have a sharing link.
Unfortunatelly this is what I get:

![immagine](https://user-images.githubusercontent.com/27236107/160633772-d24d1950-4c89-4182-aea6-a9c55b49c76a.png)

What is the missing part?
Thank you for any info!

Gianluca

**Comment by si458** [comment]
it appears after looking at the source code, its only possible if you run the mesh central assistant as the agent
and not running the assistant as an attachment to the meshagent thats running as a service!

**Comment by si458** [comment]
im going to close this as this is a meshcentral assistant issue and not a meshcentral issue
please can you re-open an issue in the correct repo - https://github.com/Ylianst/MeshCentralAssistant
