### ISSUE TITLE
Cannot display Account security options 

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#3822]
Hello,

I just installed version 1.0.1 of MeshCentral.
I can't find the Account security settings on each user's configuration.
It worked well in version 0.9.76

![2022-03-29 16_44_07-Window](https://user-images.githubusercontent.com/95504809/160642382-be2f3fc8-8ec4-48f0-bb24-9887b91c37b7.png)

**Comment by Ylianst** [comment]
When first installing MeshCentral, your server will be in "LAN mode". In this mode, you can only manage other computers on the local network. You have to provide your server with a fixed DNS name to switch to "Hybrid" or "WAN" mode. In these modes, you get more security features including the ones you point out.

I have a [video on LAN, WAN and Hybrid modes here](https://www.youtube.com/watch?v=gx5Fh3pQOns).

**Comment by pascal-chag** [comment]
ok 

Thanks
