### ISSUE TITLE
customUI missing events bug

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#3823]
Hi @Ylianst,
hope you doing well mate. I know you very busy nowadays, but when you have a chance can you please have a look at this:
when using CustomUI in the config.js. all GUI working as expected regarding buttons and dialogs. BUT when filling the dialog fields and clicking OK, only the "logmsg" data value get recorded to the events . so it doesn't record any of the following:
 NodeID, Device Name, dialog text title or dialog text area or dialog droplist chosen option.

also it logged that "logmsg" event under the User events tab but not under the device events tab.

here is my JSON:
<pre>
  "domains": {
    "": {
      "customui": {
        "devicesBarButtons": {
          "exec1": {
            "name": "Execute1",
            "action": "event",
            "logmsg": "Button 1 pressed"
          },
          "exec2": {
            "name": "Execute2",
            "selection": "one",
            "action": "event",
            "logmsg": "Button 2 pressed"
          },
          "exec3": {
            "name": "Execute3",
            "selection": "many",
            "action": "dialog:dialog1"
          }
        },
        "deviceButtons": {
          "exec4": {
            "name": "Execute4",
            "action": "dialog:dialog1"
          }
        },
        "desktopButtons": {
          "exec5": {
            "name": "Execute5",
            "action": "dialog:dialog1"
          }
        },
        "terminalButtons": {
          "exec6": {
            "name": "Execute6",
            "action": "dialog:dialog1"
          }
        },
        "filesButtons": {
          "exec7": {
            "name": "Execute7",
            "action": "dialog:dialog1"
          }
        },
        "dialogs": {
          "dialog1": {
            "logmsg": "Dialog 1 filled",  # ONLY THIS VALUE GET LOGGED IN THE USER EVENTS WHEN USE BUTTON Execute5 ABOVE
            "title": "This is the title",       # NOT RECORDED
            "text": "This is some test",    # NOT RECORDED
            "buttons": 3,
            "elements": {
              "test1": {
                "name": "Sample1",
                "type": "text"                    # NOT RECORDED
              },
              "test2": {
                "_name": "Sample2",
                "type": "textarea"             # NOT RECORDED
              },
              "test3": {
                "name": "Sample2",
                "type": "droplist",
                "options": {
                  "1": "Option1",               # NOT RECORDED
                  "2": "Option2",               # NOT RECORDED
                  "3": "Option3",               # NOT RECORDED
                  "4": "Option4"                # NOT RECORDED
                }
              }
            }
          }
        }
      }
    }
  }
</pre>

I'm using version 1.0.1

**Comment by Ylianst** [comment]
Wow, using some advanced features! I just tested it and the full event looks like this:

```
{
  action: 'uicustomevent',
  section: 'dialogs',
  element: 'dialog1',
  src: {
    section: 'desktopbuttons',
    element: 'exec5',
    selectedDevices: [
      'node//G2YkhUovikndme9JPOkW97px7t3t@$CknFzvZgcEASw8sEZ7mlo8tlGi1JKDH4hZ'
    ]
  },
  values: { test1: 'ttt', test2: 'uuu', test3: '4' },
  logmsg: 'Dialog 1 filled'
}
```

However, the web page is not displaying the "src" and "values" sections when you click on the event. The original idea what they you would run this as administrator:

```
node meshctrl.js ShowEvents
```

You can see events from the server and when you see a custom UI event, you can immediately react to it by performing some task. I did not really intend for someone to look at the even log for details. But, if needed, I could fix that. This was originally built so that a different process would monitor MeshCentral events and perform these extra tasks.

**Comment by smartekIT** [comment]
thanks, yes please if you can allow us to view that within meshcentral GUI would be great.

Thanks champion.
