### ISSUE TITLE
Dark theme CSS issue for plugin screen

### ISSUE THREAD

**Issue by thinkbig1979** [Ylianst/MeshCentral#3825]
Hi there, 

I've found this issue where selecting the dark theme causes issues on a plugin page (ScriptTask plugin). 
Not sure if it's a ticket for here of for the creator of the plugin, but figured I'd flag it here, as I think the CSS probably is part of the MeshCentral code. The image below shows a screenshot of the exact same view with light and dark modes implemented, and speaks for itself.

![image](https://user-images.githubusercontent.com/18327273/160829878-6646986f-8497-4dbe-a164-1891b797cbc8.png)

**Comment by si458** [comment]
this is an issue with whatever plugin you are using
you need to ask the plugin developer to implement the darkmode css styling to its plugin
