### ISSUE TITLE
Issues with "orphanAgentUser"

### ISSUE THREAD

**Issue by mstrhakr** [Ylianst/MeshCentral#3828]
Hey again,
I'm getting some weird things after scrapping the database on my test server, the test server has valid Let's Encrypt certs through an nginx reverse proxy setup that was all working smoothly prior to the db wipe. The issue is the with the "orphanAgentUser" option set up the agents are not rejoining into the new database as I though they would. What is weirder is that the cert hash reported on startup is exactly the same as the agent reported cert hash, as shown below. Any idea whats going on here?
```
SHA384 cert hash: f0698a0419c10afbd54451264c0a30c5ec38e82fc3552d7fb0093a81ea74979f7fca0ecbd171add7ffa87912b10d16b1
Agent bad web cert hash (Agent:f0698a0419 != Server:aea93551a3 or 693e6b2238), holding connection (xxx.xxx.xxx.xxx:34058).
Agent reported web cert hash:f0698a0419c10afbd54451264c0a30c5ec38e82fc3552d7fb0093a81ea74979f7fca0ecbd171add7ffa87912b10d16b1.
```
As always I can provide any additional detail or logs if needed.

**Comment by mstrhakr** [comment]
Okay so I figured this out but would still love to get some clarification from you about why.
Basically In the domain I added the hostname to the main domain field where it wasn't there previously.
```
  "domains": {
    "mesh.example.com": {
```
-VS-
```
  "domains": {
    "": {
```
I was just testing out a bunch of stuff and forgot about that change, what is that field used for normally. In all the configs its blank so I'm assuming I just should have left it that way.

**Comment by Ylianst** [comment]
Ha yes, in the config.json, you can have many domains like this:

```
  "settings": {
    "cert": "mesh.example.com"
  },
  "domains": {
    "": {
       (default domain config here)
    },
    "customer1": {
       (customer1 domain config here)
    },
    "customer2": {
      "dns": "customer2.example.com"
    }
  }
```

In the example above, you will have:

```
https://mesh.example.com -> The default domain
https://mesh.example.com/customer1 -> Customer1 domain
https://customer2.example.com -> Customer2 domain
```

The domain identifier (customer1 or customer2) will impact how all of the objects for that domain are saved in the database.

You should not put the domain name as domain identifier. Let me know if that helps.

**Comment by mstrhakr** [comment]
Yes I appreciate that clarification, it makes sense why it wouldn't connect now thank you.
