### ISSUE TITLE
Customize the title of a remote message

### ISSUE THREAD

**Issue by DEFALTtttttt** [Ylianst/MeshCentral#3829]
![image](https://user-images.githubusercontent.com/102130048/161029542-308161cc-31ff-48af-bdac-300f20360fa5.png)
is it possible to change the name on top when displaying a message? Change to yours

**Comment by vitko-bg** [comment]
It works fine on my side. Looks like it is related to customization of chat
post your config.json please.

**Comment by Ylianst** [comment]
Fixed poorly worded issue title

**Comment by Ylianst** [comment]
Remote message feature will display the title of your server. For example, this:

```
  "domains": {
    "": {
      "title": "My'Serv\"er"
    }
  }
```

![image](https://user-images.githubusercontent.com/1319013/161154556-16265940-185c-4c18-aef8-666f1abcb9b0.png)

Displays this:

![image](https://user-images.githubusercontent.com/1319013/161154580-ac9d5b6c-1c74-4c0b-88c4-2bd4da9311c6.png)
