### ISSUE TITLE
Changing view and sorting does not change view. Also location map issue

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#383]
When I change one of these items (also sorting):
![image](https://user-images.githubusercontent.com/5203309/61992710-faf22400-b061-11e9-938b-0cb2aadc8554.png)
The view does not change. I need to manually reload the webpage to see the change.
This happens in Safari browser. In Chrome It is working fine, but there are no location map option. Also location option at device page is not there.
Does it not work correctly due recent change of "location map"?
MeshCentral v0.3.8-p

**Comment by Ylianst** [comment]
Thanks for reporting. I have not tested the map options in a long time. I will take a look at this.

**Comment by Ylianst** [comment]
Your right. Fixed it. Will be in MeshCentral v0.3.8-r when I publish it later today.

**Comment by Ylianst** [comment]
Now on MeshCentral v0.3.8-s which should include this fix.

**Comment by hunter-nl** [comment]
Not fixed. Still the same situation. In Safari switching between the different views not working. (view not reloaded)
Also sorting not changed when you choose different sorting.
In Chrome it is working, but there location view icon is not there ->
![image](https://user-images.githubusercontent.com/5203309/62041258-805d0c00-b1fb-11e9-9b21-25c38e50c831.png)

**Comment by Ylianst** [comment]
To get the location view, you need to add:

`"GeoLocation": true`

to the domain section of config.json. By default it's false now, it's been like this for a few months. I will have to check this on Safari.

**Comment by hunter-nl** [comment]
I have GeoLocation set to False. Then I can still see Location map view icon and at device details a location link. This happens only in Safari. In other browsers it is not visible.
When I set it to True, then I see the location icon/link in all browsers.
Beside to the location issue in Safari. When changing to other view options or the sorting option, the view does not getting updated to the new selected option. I have to do manually a refresh webpage to see the new view/sort in Safari browser. Other browsers the view gets updated automatically.

**Comment by Ylianst** [comment]
I tested on Safari 12.1.2 and I don't see any issues. If you can post any errors you see in the Safari JavaScript Console and your Safari version and OS version, that would be great. Thanks.

![Screen Shot 2019-07-30 at 5 31 56 AM](https://user-images.githubusercontent.com/1319013/62130008-e80f6780-b28c-11e9-8c89-288db8bb4c32.jpg)

**Comment by hunter-nl** [comment]
Fixed with 0.3.8-w :-)

**Comment by Ylianst** [comment]
Perfect thanks.
