### ISSUE TITLE
Remote desktop fails on login, KVM child process exits. When upgrade 0.9.95 to 1.0.1

### ISSUE THREAD

**Issue by Belvedus2** [Ylianst/MeshCentral#3830]
Hi,

A few days ago, I upgraded our Meshcentral Server from 0.9.95 to 1.0.1 . 
Everything works after the upgrade except for Ubuntu client. 
In desktop tab, when Ubuntu is on the login screen, Mesh print (in yellow) "_KVM child process has unexpectedly exited_" and stay with a black screen.
When Ubuntu is logged in, Mesh work with no problem.

Our problem is on Ubuntu 18.04 and 20.04, Fresh Install or Update.
It's only happened when we use gdm3, no problem with lightdm.
I disabled Wayland.

I checked old issus for the problem : #602 and #1323 .

I tried some command for logging : 

```
/usr/local/mesh/meshagent -exec "console.log(require('user-sessions').gdmUid);process.exit();"
130 
./meshagent -exec "console.log(require('monitor-info').getXInfo(130));process.exit();"  
{ tty: tty1, xauthority: /run/user/130/gdm/Xauthority -background none -noreset -keeptty -verbose 7 -core, display: :0, exportEnv: function exportEnv() { [ecmascript code] }, xdm: xorg }
```

I add --slaveKvmLog=1 to the exec path. _/tmp/slave_ file :
```
SLAVE/KVM CoreDumps DISABLED
Checking $DISPLAY
ENV[DISPLAY] = 0
Before kvm_init(0).
kvm_init(0) called
XAUTHORITY is /run/user/130/gdm/Xauthority -background none -noreset -keeptty -verbose 7 -core
DisplayString is :0
XOpenDisplay(:0) failed, using XAUTHORITY: /run/user/130/gdm/Xauthority -background none -noreset -keeptty -verbose 7 -core
```

I enable Debug in gdm3 and syslog show that : 
```
Mar 31 13:55:13 pc-alfa systemd[1]: Started Session c18 of user gdm.
Mar 31 13:55:13 pc-alfa /usr/lib/gdm3/gdm-x-session[6998]: gnome-session-binary[6998]: DEBUG(+): GsmSystemd: received logind signal: SessionNew
Mar 31 13:55:13 pc-alfa /usr/lib/gdm3/gdm-x-session[6998]: gnome-session-binary[6998]: DEBUG(+): GsmSystemd: ignoring SessionNew signal
Mar 31 13:55:13 pc-alfa gnome-session-binary[6998]: DEBUG(+): GsmSystemd: received logind signal: SessionNew
Mar 31 13:55:13 pc-alfa gnome-session-binary[6998]: DEBUG(+): GsmSystemd: ignoring SessionNew signal
Mar 31 13:55:13 pc-alfa systemd[1]: session-c18.scope: Succeeded.
Mar 31 13:55:13 pc-alfa /usr/lib/gdm3/gdm-x-session[6998]: gnome-session-binary[6998]: DEBUG(+): GsmSystemd: received logind signal: SessionRemoved
Mar 31 13:55:13 pc-alfa /usr/lib/gdm3/gdm-x-session[6998]: gnome-session-binary[6998]: DEBUG(+): GsmSystemd: ignoring SessionRemoved signal
Mar 31 13:55:13 pc-alfa gnome-session-binary[6998]: DEBUG(+): GsmSystemd: received logind signal: SessionRemoved
Mar 31 13:55:13 pc-alfa gnome-session-binary[6998]: DEBUG(+): GsmSystemd: ignoring SessionRemoved signal
```

Sorry for my poor English.

**Comment by krayon007** [comment]
While it's on the login screen, can you open the terminal tab, click connect. Then type the command:

`loginctl`

And what does it show?

**Comment by Belvedus2** [comment]
```
root@pc-alfa:/usr/local/mesh_services/meshagent# loginctl
SESSION UID USER SEAT  TTY 
    c10 130 gdm  seat0 tty1

1 sessions listed.
```

**Comment by krayon007** [comment]
I think I see the issue. Let me write a test script to reproduce it, and fix it. It will require an agent update most likely. But it should be a small fix.

**Comment by krayon007** [comment]
ok I found/fixed the issue, it will be in the next agent update. We'll have to update the linux agents anyways, because earlier I fixed a bug I found that was caused by Ubuntu 20 having a different regex parsing behavior from Ubuntu 18 and older. (Basically Ubuntu 20 removed support for an optional parameter that was implemented in older releases)

**Comment by Belvedus2** [comment]
Thank you very much.
We'll wait for your update.

**Comment by Belvedus2** [comment]
I tried the 1.0.2 update. It's working !!

Thank You very Much !
