### ISSUE TITLE
Google authenticator addition hangs at loading forever

### ISSUE THREAD

**Issue by getut** [Ylianst/MeshCentral#3831]
I first noticed this with version 1.0 but it also is doing it with 1.0.1. Any attempt to add Google Authenticator generates the normal popup but it hangs at loading forever. I searched this and saw an older issue similar back in 2019, but given the age of that post, that has likely been solved and a similar or same cause has happened again.

Edit: forgot to mention, this is on an installation that has previously been able to add Google authenticator 2 factor with no changes to the config since the last successful GA addition. It is running on Ubuntu 22.04 beta.

**Comment by Ylianst** [comment]
I can't reproduce this issue, I click and see this dialog box right away.

![image](https://user-images.githubusercontent.com/1319013/161152144-9ecd486c-b36c-460d-95a0-861f9dde8b45.png)

Can you open the browser console and see if there are any errors? Are you using plugins? Non-english language?

**Comment by getut** [comment]
On a refresh of the "My Account" page the console shows 2 instances of "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'. Nothing additional pops in errors or otherwise after that when I click on the Manage authenticator app link. The popup comes up and says loading, but no additional errors or info in console.

**Comment by getut** [comment]
Oh.. missed a few of your questions... This is English language, tried on Firefox on Ubuntu with plugins and on a fresh install of chrome on Ubuntu without plugins all with same result.

**Comment by getut** [comment]
Is there a better place to ask for support on this? At this point based on your response, it doesn't appear to be a bug, so is likely something with my installation. How to get support for it? I've done the browser console thing and nothing evident is being reported or I am doing that wrong.

**Comment by Ylianst** [comment]
It's difficult to fix when I can't replicate the issue. If your server is on the Internet and your willing to do this, create a dummy account for me and send it over, my [contact information is here](https://www.meshcommander.com/contact-information). No need to any server rights. I will test this feature on your server and see what data I can get. - Thanks.

**Comment by getut** [comment]
Thanks!
I just sent you an invitation via our meshcentral instance.

**Comment by Ylianst** [comment]
Thanks. I just checked out your server and did some improvements. Starting with v1.0.4, it will show the exact error that occurred instead of hanging. Next, I can't tell exactly what is going on, but looking at the code, one of these is causing the problem:

- domain.passwordrequirements.lock2factor is true.
- domain.passwordrequirements.backupcode2factor is false.
- The account is logged in using a login token.
- domain.passwordrequirements.otp2factor is false.
- The account is locked.
- OTPLib can't be loaded.

Can you check the domain section of your config.json and see if any of the "passwordrequirements" could be an issue? Otherwise, you will know for sure when I release v1.0.4 and you update to that.

**Comment by Ylianst** [comment]
if you like, send me an email and I will send you back a better title logo for your server.

**Comment by getut** [comment]
Thanks,
It appears that it is the backupcode2factor being false breaks Google
authenticator. After disabling that line it started working again.

I will update the github with that issue.

**Comment by getut** [comment]
Circling back on this one. It is showing in github that this is marked
resolved, but my question is that if backupccode2factor is turned off, it
shouldn't also be disabling Google Authenticator from functioning so I
don't think this one is resolved.

**Comment by getut** [comment]
I didn't think about the possibility that you receive a ton of these. Mine
will be from CRG Connect and the server is the one at
meshcentral.classicburgers.com when you see the invitation.

Thanks again.
Robert (Getut)

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
dont seem to have this issue anymore so must be fixed
