### ISSUE TITLE
Terminal Failure (Connecting the screen flashes and the agent is off for about 5 seconds)

### ISSUE THREAD

**Issue by alanpereiracoelho** [Ylianst/MeshCentral#3834]
TITLE: Falha no Terminal (Conectar a tela da um piscada e agente fica off por uns 5 segundos)

Boa noite, primeiramente parabéns pelo projeto estou apaixonado em poder usar essa ferramenta fabulosa. Estava tudo muito bem ate a atualização 1.0.0. Já removi os agentes instalei novamente e ainda assim permanece, detalhe não são todas as maquinas que acontece isso, tenho algumas que funcionam e algumas que simplesmente da essa falha. Quando conectar terminal a tela da um piscada e agente fica off por uns 5 segundos) e volta! Demais acesso como área de trabalho normal.

ENGLISH:
Good evening, firstly congratulations on the project, I am passionate about being able to use this fabulous tool.  Everything was fine until update 1.0.0.  I have already removed the agents and installed them again and it still remains, detail not all machines have this happen, I have some that work and some that simply give this failure.  When connecting the terminal, the screen flashes and goes off for about 5 seconds) and comes back on!  Too much access as a normal desktop.

**Comment by si458** [comment]
closing as stale
