### ISSUE TITLE
npm package not working as expected. 

### ISSUE THREAD

**Issue by gabriel19971029** [Ylianst/MeshCentral#3837]
I was following step by step the guide on how to install MeshCentral and it's not working as expected. After entering the install command this is what I get.
<code>$ npm install meshcentral</code>

<code>added 51 packages, and audited 249 packages in 3m</code>

<code>9 packages are looking for funding</code>
  <code>run `npm fund` for details</code>

<code>found 0 vulnerabilities</code>

Which is okay, but later the command <code>node ./node_modules/meshcentral</code> it doesn't worked so I tried <code>ls</code>, and it appears to be an empty folder, also visiting the folder through the GUI it seems to be empty. So I'm unable to proceed with the installation. <br> 
The command <code>node ./node_modules/meshcentral</code> returns the following error message: <code>internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/«userfolder»/mc/node_modules/meshcentral'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}</code> 

<br>
Any idea why does this happen? Because the installation command returns that 51 packages were added yet the folder it's empty and the rest of the commands don't work.

Thanks you in advance. I appreciate the help. This software it's awesome.

**Comment by Ylianst** [comment]
I just tried `npm install meshcentral` and it worked for me. What version of NodeJS are you using? Version 10.x is now the minimum supported, much older versions of MeshCentral could support v6.x

If that is not the problem, clear the `node_modules` folder and try `npm install meshcentral@1.0.1` so to specify the exact version you want.

**Comment by gabriel19971029** [comment]
Omg that was a fast response. I got Node v14.19.1. And I tried what you said and still getting the same result. I'm sorry i really don't want to bother. Does this ever happened before? What could generate this?
![meshissue](https://user-images.githubusercontent.com/76955628/161428756-1740c4bb-a462-40ae-b00a-f6818098ee4b.png)

**Comment by Ylianst** [comment]
It's like it's not downloading or installing MeshCentral at all. No need to run `node node_modules/meshcentral`, your folder is likely completely empty.

Looking online, [I found this](https://stackoverflow.com/questions/39843072/npm-install-installs-but-node-modules-is-empty).

You could try clearing the npm cache: `npm cache clean --force`

**Comment by gabriel19971029** [comment]
Nevermind, it was way more stupid than that. I forgot the command <code>npm init</code> it wasn't going to work without that.  *faceplam* Sorry for wasting your time, thanks a lot for the help!
