### ISSUE TITLE
Fedora 34 meshagent 1.0.1 yellow KVM chil process has unexpectedly exited

### ISSUE THREAD

**Issue by guerby** [Ylianst/MeshCentral#3838]
Hi,

At GDM login screen using X (WaylandEnable=False in /etc/gdm/custom.conf daemon section) on a fedora 34 (up to date) when I try to connect to desktop I get  a yellow KVM child process has unexpectedly exited with mescentral 1.0.1

root         737  0.0  0.1  26536 14316 ?        Ssl  14:28   0:00 /usr/local/mesh_services/meshagent/meshagent --installedByUser=0
gdm         2104  0.0  0.0      0     0 ?        Z    14:32   0:00  \_ [meshagent] <defunct>

**Comment by guerby** [comment]
Note: I did not check what version I had before upgrading to 1.0.1 but connect to desktop on gdm login screen was working, so this is a regression.

**Comment by guerby** [comment]
Same issue with Fedora Core 35, unable to get the gdm login screen (WaylandEnable=False)

If (using my hypervisor) I log in as a user then meshagent picks up the desktop without issue (both with FC34 and FC35) so this is a gdm only issue.

**Comment by krayon007** [comment]
This was fixed a few days ago. It will be in the next update which should be very soon. It was caused by a bug in a regex that I used to work around some Ubuntu 20 issues

**Comment by krayon007** [comment]
> Note: I did not check what version I had before upgrading to 1.0.1 but connect to desktop on gdm login screen was working, so this is a regression.

Try with v1.0.2, and let me know if this fixes the issue for you.

**Comment by guerby** [comment]
1.0.2 works for me, thanks again!
