### ISSUE TITLE
Parsing error for database name for mongodb (ReplicaSet)

### ISSUE THREAD

**Issue by lwilmen** [Ylianst/MeshCentral#384]
Currently I'm trying to migrate to a high availability setup, and have setup a HA MongoDb replicaSet, following the guidance as per db.js contained within the meshcentral module: 

> Just run with --mongodb [connectionstring], where the connection string is documented here: https://docs.mongodb.com/manual/reference/connection-string/

MongoDb JSON configuration as follows: 

```json
    "MongoDb": "mongodb://mongodb-1.as-rss-01.server.com:27017,mongodb-1.as-rss-02.server.com:27017,mongodb-1.oc-rss-01.server.com:27017/meshcentral?replicaSet=rs0",
    "mongodbcol": "meshcentral",
```

Let's start the database import...

```bash
$ node meshcentral --mongodb mongodb://mongodb-1.as-rss-01.server.com:27017,mongodb-1.as-rss-02.server.com:27017,mongodb-1.oc-rss-01.server.com:27017/meshcentral?replicaSet=rs0 --mongodbcol meshcentral --dbimport
```

Oops, we're met with the following error:

```raw
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
{ Error: Command failed: /usr/bin/node /home/deployer/meshcentral/node_modules/meshcentral --mongodb mongodb://mongodb-1.as-rss-01.server.com:27017,mongodb-1.as-rss-02.server.com:27017,mongodb-1.oc-rss-01.server.com:27017/meshcentral?replicaSet=rs0 --mongodbcol meshcentral --dbimport --launch 7616
the options [useNewUrlParser] is not supported

/home/deployer/meshcentral/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^
MongoError: database names cannot contain the character '.'
    at Function.MongoError.create (/home/deployer/meshcentral/node_modules/mongodb-core/lib/error.js:31:11)
    at validateDatabaseName (/home/deployer/meshcentral/node_modules/mongodb/lib/db.js:1686:70)
    at new Db (/home/deployer/meshcentral/node_modules/mongodb/lib/db.js:156:3)
    at Db.db (/home/deployer/meshcentral/node_modules/mongodb/lib/db.js:1208:12)
    at /home/deployer/meshcentral/node_modules/meshcentral/db.js:220:31
    at connectCallback (/home/deployer/meshcentral/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /home/deployer/meshcentral/node_modules/mongodb/lib/mongo_client.js:430:11
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:198:15)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /home/deployer/meshcentral/node_modules/meshcentral --mongodb mongodb://mongodb-1.as-rss-01.server.com:27017,mongodb-1.as-rss-02.server.com:27017,mongodb-1.oc-rss-01.server.com:27017/meshcentral?replicaSet=rs0 --mongodbcol meshcentral --dbimport --launch 7616' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...
```

Further debugging seems to split the problems into two:

1. The URI decoder for the JSON settings seems to mistakenly confuse what the actual database name is (meshcentral) for something that has the character '.' This seems to be the periods from the subsequent FQDNs that constitute the replicaset. Removal of the additional replicas will allow a successful creation of the database on one of the servers, which is subsequently replicated by MongoDb, however when failing the primary server, Meshcentral does not switch over to the new primary server, and subsequently ceases to function.
2. The URI decoder (I'm unsure if it's from the command line or from the config.json), is mistakenly including the parameters passed in on the URI as part of the database name:

```raw
rs0:SECONDARY> show dbs
admin                       0.000GB
config                      0.000GB
local                       0.000GB
meshcentral?replicaSet=rs0  0.000GB
```
I've been watching this project and the work done here is great. Keep up the good work!

**Comment by Ylianst** [comment]
Nice catch. I have never tried using a MongoDB ReplicaSet and this certainly must be supported. I will take a look at this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-u with a fix for this. You should be able to do:

```
    "MongoDb": "mongodb://mongodb-1.as-rss-01.server.com:27017,mongodb-1.as-rss-02.server.com:27017,mongodb-1.oc-rss-01.server.com:27017/?replicaSet=rs0",
    "MongoDbName": "meshcentral",
```

The MongoDbName will default to "meshcentral". Also, I don't suggest using "mongodbcol" anymore as MeshCentral now creates many collections in the database. Let me know if it works.

**Comment by lwilmen** [comment]
Just tested v0.3.8-v. High availability with replicaSet is confirmed to be working as expected. No command line parsing errors for the database name (though it's no longer explicitly set, as per your guidance, with the default MongoDbName). Tested with 3 nodes in the replicaSet, and failover worked seamlessly.  Great work!

**Comment by Ylianst** [comment]
Thanks. MongoDB makes it easy.
