### ISSUE TITLE
How to change root from / to /subdir

### ISSUE THREAD

**Issue by adnion** [Ylianst/MeshCentral#3845]
MeshCentral works fine when hosted on **"example.com"** or "**meshcentral.example.com**".

Is there a config option to host meshcentral on a subdirectory like "**example.com/subdir**"?

After login I get "_unable to connect web socket_" because requests go to "**example.com/control.ashx**" instead of "**example.com/subdir/control.ashx**". 

I already tried the options "**rootRedirect**" and "**"redirects**".

**Comment by Ylianst** [comment]
Yes. In the config.json, you can have many domains like this:

```
  "settings": {
    "cert": "mesh.example.com"
  },
  "domains": {
    "": {
       (default domain config here)
    },
    "customer1": {
       (customer1 domain config here)
    },
    "customer2": {
      "dns": "customer2.example.com"
      (customer2 domain config here)
    }
  }

In the example above, you will have:

```
https://mesh.example.com -> The default domain
https://mesh.example.com/customer1 -> Customer1 domain
https://customer2.example.com -> Customer2 domain
```

The domain identifier (customer1 or customer2) will impact how all of the objects for that domain are saved in the database.

In your case, your probably looking for the "Customer1" example.

Let me know if this works.

**Comment by adnion** [comment]
I replaced **""** with "**subdir**" and it just works. Awesome work, thanks!

**Comment by PrplHaz4** [comment]
> Yes. In the config.json, you can have many domains like this:
> 
> ```
>   "settings": {
>     "cert": "mesh.example.com"
>   },
>   "domains": {
>     "": {
>        (default domain config here)
>     },
>     "customer1": {
>        (customer1 domain config here)
>     },
>     "customer2": {
>       "dns": "customer2.example.com"
>       (customer2 domain config here)
>     }
>   }
> ```
> 
> In the example above, you will have:
> 
> ```
> https://mesh.example.com -> The default domain
> https://mesh.example.com/customer1 -> Customer1 domain
> https://customer2.example.com -> Customer2 domain
> ```
> 
> The domain identifier (customer1 or customer2) will impact how all of the objects for that domain are saved in the database.
> 
> In your case, your probably looking for the "Customer1" example.
> 
> Let me know if this works.

We need an add to docs tag. Great post.
