### ISSUE TITLE
Question - Remote desktop connection - View only mode

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3849]
Hi,

When connecting remote desktop for a machine, the user should be able to decide whether they want to connect with keyboard and mouse control or only for viewing purpose.

I can see the checkbox option at the bottom "Input". But is it possible to enable/disable it automatically through some parameter in URL?

**Comment by Ylianst** [comment]
Note that there is a user permission to force a user into view-only mode of the devices that you don't want them to interact with. This is probably not what you want.

Your asking for a URL option that you set the starting values of the "Input" box? So, if I put something like "desktopinput=0", the input box would start out not checking?

I want to make sure to be very clear as to what you are asking.

**Comment by knkumar93** [comment]
Hi @Ylianst , Thanks for the response.

The ask here is, I do not want to change the user permission each time. The user may want to connect some session with user input, some session without user input as spectator. So each time changing permission for that user may be hard task. Instead, user will be given with permission, however the user can decide whether they want to connect with control mode or view-only mode.

**Comment by si458** [comment]
as @Ylianst explained, the feature already sorta exists in the web ui but not in the URL at the moment,
before the staff clicks connect, they can UNTICK the INPUT box at the bottom which switches to view only mode
then if the staff want to control the remote device they can TICK the INPUT box at the bottom and away they go!
hope this helps!

**Comment by knkumar93** [comment]
I found an alternate in below link. It creates sharable link with view only or full control access for specific device. This solves my use case at this moment.

[https://github.com/Ylianst/MeshCentral/issues/2172](https://github.com/Ylianst/MeshCentral/issues/2172)

With this, I am closing this thread.
