### ISSUE TITLE
Feature Request: shift + home / shift + end buttons does not select the line/word.

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#385]
Hi Ylianst,
When i connect Desktop if i make the combination shift + home or shift + end the cursor does not select the line/word.
For example when i try ctrl + home or ctrl + end it works.
Is it possible to develop shift + home and shift + end functions?
Thanks

**Comment by Ylianst** [comment]
I will check when I get a chance.

**Comment by MailYouLater** [comment]
This is a duplicate of #169.

**Comment by dinger1986** [comment]
@si458 duplicate please close
