### ISSUE TITLE
Intel ACM Activation fail - No trusted DNS suffix reported

### ISSUE THREAD

**Issue by prononext** [Ylianst/MeshCentral#3852]
When trying to activate Intel ACM via Ethernet on Remote host the Server Tracing shows the following logs and the agent is not connecting. They are already many posts and videos like this but not one is explaining how to generate the Intel ACM certificate and integrate it in detail.  As I understand there is no need to buy a DigiCert or else to get ACM connected, but how to get it working exactly?

**Server Tracing on Agent ACM Script with MeshCTR.**

```
mps	CIRA websocket closed, mesh//XXXXXXXXXXXXXXX, node//XXXXXXXXXXXXXXXXXXXXXXX
mpscmd	<-- REQUEST_SUCCESS, 16992
mpscmd	--> GLOBAL_REQUEST, tcpip-forward, CLIENT:16992
mpscmd	<-- JSON_CONTROL, close
amt	CLIENT, Remove device, node//XXXXXXXXXXXXXXXXXX, 2, 38
mpscmd	<-- JSON_CONTROL, console
amt	CLIENT, No opportunity for ACM activation: No trusted DNS suffix reported
amt	CLIENT, Attempt Initial Contact, CIRA-LMS
mpscmd	<-- JSON_CONTROL, console
amt	CLIENT, Checking Intel AMT state...
amt	Start Management, node/xxxxxxxxxx
mpscmd	<-- SERVICE_ACCEPT, pfwd@amt.intel.com
mpscmd	--> SERVICE_REQUEST, pfwd@amt.intel.com
mpscmd	<-- USERAUTH_SUCCESS
mpscmd	--> USERAUTH_REQUEST user=xxxxxxxxxxxx, service=pfwd@amt.intel.com, method=password, password=xxxxxxxxxxx
mpscmd	<-- SERVICE_ACCEPT, auth@amt.intel.com
mpscmd	--> SERVICE_REQUEST, auth@amt.intel.com
mpscmd	--> PROTOCOLVERSION, 1, 0, xxxxxxxxxx
mpscmd	--> JSON_CONTROL, meiState
mpscmd	--> JSON_CONTROL, connType
mps	New CIRA websocket connection
```

Server: 1.0.2
System: Ubuntu 20.04
DB: MongoDB
Mode: WAN only on FQDN

**Comment by Ylianst** [comment]
Can you provide the command line you are using to get the server trace? You mention "Agent ACM Script with MeshCTR", not sure what that is. Is that the MeshAgent? MeshCMD? MeshCtrl? What "Script"?

To perform Intel AMT ACM activation, you do that a few different ways:

 - You can go in MEBx and manually activate Intel AMT into ACM. You enter in a new username and password and give there to MeshCentral.
 - You can have MeshCentral create a file called "setup.bin" and place it on a USB key, you can then connect the USB key to the AMT computer reboot and when prompted enter "Y". This will load your MeshCentral Server's root certificate into AMT as a trusted root certificate and set a random trusted FQDN. Once booted into the OS, you can use MeshCMD or the MeshAgent to connect to MeshCentral. MeshCentral will detect your computer has it's own root cert and FQDN and perform ACM activation.
 - You can  buy a ACM activation certificate (A TLS web site certificate will not do, it must be specifically for AMT). That certificate will have your company FQDN in it (like "sample.com"). You need to configure MeshCentral with that certificate and connect the AMT computer on the Wired Ethernet port (Wireless will not work) to a DHCP server that has "sample.com" as option 15. MeshCentral should detect the situation and configure to ACM.

Hope that helps.

**Comment by prononext** [comment]
I mean the MeshCMD of course, together with the agentless AMT Setup which is given out on the group type "Intel® AMT only, no agent"
![image](https://user-images.githubusercontent.com/24569958/162337601-43c5ea76-2f67-4b46-a97f-b43634103400.png)

As I understand you right the only way to activate a client with ACM without physically being on the machine is to buy a ACM Activation certificate and add it to the MeshCentral Config?

So either: 

- buy a certificate if you want **remote** ACM activation,
- edit the MEBx **locally** to activate with username and password or
- create a USB drive with the setup.bin created in MeshCentral and **locally** edit the Clients Root Certificate. 

_Thank you very much for this beautiful software and your energy you are putting in supporting it!_

**Comment by Ylianst** [comment]
Your correct. If you want to active Intel AMT into ACM, you need to buy a Intel AMT activation certificate (A HTTPS certificate will not do) AND you need the wired port of AMT to be connected to a DHCP server that shows the local network (option 15) with the value of your certificate common name. Connecting the wireless network interface of AMT to a DHCP server like this will NOT work.

**Comment by prononext** [comment]
Perfect, thank you for the detailed clarification.
