### ISSUE TITLE
Manage email authentication spelling mistake

### ISSUE THREAD

**Issue by Gipolabs** [Ylianst/MeshCentral#3853]
Hi,

Just noticed a spelling mistake under "My Account" > "Manage email authentication". The I and T have been swapped in "Enable email two-factor authentica**it**on.
![image](https://user-images.githubusercontent.com/93565752/162372850-f29d158c-bc54-4e93-a72d-0c7cd45382ae.png)

**Comment by Ylianst** [comment]
Thanks for reporting this. It's fixed, will be in v1.0.3.
