### ISSUE TITLE
Open user account details not working in Safari

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#386]
In Safari browser: When I click on a user line at the users view, then nothing happens.
In Chrome it just working fine and shows the user account details page.
MC version 0.3.8-s

**Comment by Ylianst** [comment]
Interesting, I will take a look at this.

**Comment by Ylianst** [comment]
I just tested on Safari 12.1.2 (13607.3.10) on MacOS High Sierra 10.13.6 and I don't see any issues. Can you open the JavaScript console in Safari and post any errors along with your Safari and OS version. Thanks.

**Comment by hunter-nl** [comment]
With version 0.3.8-v it is working again. Is it possible javascript file was not updated in browser cache?
BTW. I'm using OSX 10.14.5, Safari 12.1.1 (14607.2.6.1.1)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.8-w with various fixes for problems with the device list view. I will close this one, if you get more issues with Safari, please send over any JavaScript console output.
