### ISSUE TITLE
ESET Endpoint Sercurity" antivirus reports me an Unwanted Application with a "CoinMiner_AGen.D"

### ISSUE THREAD

**Issue by CSW2000** [Ylianst/MeshCentral#3862]
This morning my "ESET Endpoint Sercurity" antivirus reports me an Unwanted Application with a "CoinMiner_AGen.D"
09.04.2022 09:24:14; real-time file protection;file; C:\Program Files\CSW\remote maintenanceXY\FernwartungXY_Agent.update.exe_unzipped;a variant of Win64/CoinMiner_AGen.D potentially unwanted application;retain; NT AUTHORITY\SYSTEM; Event when the application creates a new file: C:\Program Files\CSW\fernwartungxy.de\Fernwartungxy_Agent.exe (AFA19291A8E0439018C86FE9AA8BF1F5A284DCF9).; FB4D8E6A78A4DF7956BEB41E4480C5F2A5D72D65;09.04.2022 09:23:12
Why do you search for Bitcoin with the agents?

**Comment by krayon007** [comment]
The agent is open sourced, and the full is available [here](https://github.com/Ylianst/MeshAgent). There is no bitcoin miner in the agent. Your AV is reporting a false positive.

**Comment by CSW2000** [comment]
Thanks for the feedback, I think so too.
a few minutes later that is also said to be included in the Acronis system. :-) , ESET was probably a little overzealous.
Greetings from Germany - Roland W.

**Comment by Ylianst** [comment]
Issue also reported here #3864, and on [Reddit here](https://www.reddit.com/r/MeshCentral/comments/tzx7ok/win64coinminer_agend/).
