### ISSUE TITLE
Changed from WAN only to Hybrid mode, and cannot see local device groups.

### ISSUE THREAD

**Issue by Schtoopid** [Ylianst/MeshCentral#3863]
I originally started in WAN mode, I changed to Hybrid mode in order to test AMT.
I cannot see any local groups I create.
They show up in My account as full administrator, but not on the My Devices.
This happens with local groups, and AMT groups.

Any idea how to mitigate? Can I export config recreate and import it without loss of existing devices?

**Comment by Ylianst** [comment]
Starting with the easy stuff, make sure your sorted by "Groups" in order to see all device groups including empty ones at the bottom.

![image](https://user-images.githubusercontent.com/1319013/162586508-97c3436f-04d6-4f9c-8f7e-f7f71fa8648c.png)

In WAN mode, you should not be able to create local groups, so I imagine you switched to Hybrid mode and then created the device group. If the group is empty, change your sorting option and you should see it. Let me know if that worked.

**Comment by Schtoopid** [comment]
No change.
Tried an uninstall and re-install. Still the same.
I'm thinking if I can add something manually to a local group it might work. Can you suggest how I could manually add a local agent?

**Comment by Schtoopid** [comment]
![image](https://user-images.githubusercontent.com/40545973/162589341-ba157f87-28d1-4638-8a1f-8b8088e7a39d.png)

**Comment by Schtoopid** [comment]
![image](https://user-images.githubusercontent.com/40545973/162590889-fc2bf596-6cb2-4eba-8d2c-dc4c5a5e6934.png)

**Comment by Ylianst** [comment]
Can you type "info" in the server console and report back when you see?

![image](https://user-images.githubusercontent.com/1319013/162590903-564a2e20-8fd4-4a9c-8022-6196ed9c87bb.png)

**Comment by Schtoopid** [comment]
![image](https://user-images.githubusercontent.com/40545973/162595401-e04408dc-ebf7-4b85-bdcf-0e47fb7c6ef8.png)

**Comment by Schtoopid** [comment]
Opened in Chrome instead of Brave and it worked.
Not sure what in Brave is stopping it.
I was sure I checked Edge and it didn't work, but it's working now.
I'm not sure if you want to look into Brave browser not working or not.
Close if you wish.

**Comment by Ylianst** [comment]
In Brave, open the developer console and see if there are any errors? If you see any, please post a screen shot back. That would help a lot.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
