### ISSUE TITLE
Force Remove Plugin

### ISSUE THREAD

**Issue by prononext** [Ylianst/MeshCentral#3865]
Is there any way to forcefully remove a plugin which does not dissapear from Plugins Tab, when the plugin remove functionality is not working and the plugin is still in the plugins list?

Deleting the plugin code from meshcentral-data/plugins does not do it somehow.

**Comment by smartekIT** [comment]
in the past i had the same as even after removing the plugins file from meshcentral-data folder but they were still in the mongodb so i had to clean them up from the database as well, check this response here might help you:
https://github.com/Ylianst/MeshCentral/issues/2789#issuecomment-863858736

**Comment by prononext** [comment]
This problem I had with 4 Plugins so far. I guess implementing that as a function, so that the plugin Database entries get removed by GUI action is the way to go. ryanblenis has a nice plugin which has this function and is working nicely. Maybe worthy to integrate to standard Meshcentral....?

https://github.com/ryanblenis/MeshCentral-DevTools
![image](https://user-images.githubusercontent.com/24569958/162635014-cfa855d2-aeda-4ddd-9d94-1c8bd56dd778.png)
