### ISSUE TITLE
Remote Desktop black screen after Windows boots

### ISSUE THREAD

**Issue by sleepmaster91** [Ylianst/MeshCentral#3866]
Remote Desktop works fine in pre-windows environment but once Windows is booted if I try the remote desktop all I get is a black screen

![image](https://user-images.githubusercontent.com/103353220/162606407-f73ec50b-b0c5-42d0-8c49-895c95318494.png)

**Comment by si458** [comment]
this is something to do with meshcommander and not meshcentral
closing as not relevent, please repoen here instead https://github.com/Ylianst/MeshCommander
