### ISSUE TITLE
Meshcentral firewall entries

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3869]
I have a server running Microsoft Windows Server 2012 R2 Foundation - 9600 with the 64bit agent installed.
This server has had an issue with the firewall, I was unable to open the windows defender firewall console, it was hanging on a windows called "Expand"
I was able to solve this issue with updates.

The mesh agent issue is that the agent will do the "Checking firewall for previous installation" and it hangs there forever.
I can now only use the agent in Run mode.
As I'm now able to see the firewall again and I have thousands (27231) of firewall entries from meshcentral, like below.
the agent is still hanging, but this could be due to the extreme amount of entries...

![image](https://user-images.githubusercontent.com/55733884/162693038-c167053f-cc6c-43b7-840f-a606fa591b55.png)

I'm now trying to delete them, but this should not have happend in the first place, seems like a bug to me with this many entries.
The agent issue started after a meshcentral update (with the new agent) and there was only a short time as I found the agent offline quickly. I did try a couple of times until I found the firewall issue, but not thousand of times.

Can there be a check or timeout for this? 
Mainly to avoid the agent being stuck and not coming back only.

This seems related to https://github.com/Ylianst/MeshCentral/issues/3596 so could also be that the entries were already there.

**Comment by vitko-bg** [comment]
Just checked and can see it is same here, ports are shown and are same ports multiple times:

![image](https://user-images.githubusercontent.com/59362521/162731768-9108355c-4236-43f9-88d3-d815a4de01f3.png)

**Comment by PathfinderNetworks** [comment]
Unfortunately, I have seen this exact same issue on Windows 10 computers as well.  No idea what causes it but it is a huge issue as it causes a massive performance issue with the device it's happening on.  Deleting the entries through the firewall GUI takes DAYS to complete.  But I did find you can use PowerShell to delete the rules much, much faster. Although it can still take hours to complete. This command will do it. But you'll have to issue the command for each named rule.
 remove-netfirewallrule -DisplayName "Mesh Agent management (TCP)"  (just change the service name in quotes for each entry as necessary).  Also be sure to run PowerShell as admin.

**Comment by Ylianst** [comment]
This is a bug in the old agent and I think Bryan fixed it... however, I will let him confirm. The agent will not create these entries anymore, but old entries do remain.

**Comment by krayon007** [comment]
I'm trying to find a better way to fetch/delete the rules. Currently it has to enumerate all the rules, because it calls getRules on the InetFirewallPolicy object. This is why it is rather slow with a large number of rules.

**Comment by NiceGuyIT** [comment]
I reported the original duplicate firewall rules issue and just posted a [PowerShell script](https://github.com/Ylianst/MeshCentral/issues/3596#issuecomment-1096681065) to delete duplicate rules. I ran this as a script in [Tactical RMM](https://github.com/amidaware/tacticalrmm) for the affected agents. This is a manual "run if affected" script for affected agents.

**Comment by Allowee** [comment]
After deleting the old rules the agent did update correctly. 
This was a rare event, probably also related to the firewall console not opening..

Since the original bug in https://github.com/Ylianst/MeshCentral/issues/3596 is solved I think it would be best to close this

**Comment by Ylianst** [comment]
Yes, the firewall rule is only needed for WebRTC to operate which is an optional feature. The agent will work fine without any rules at all. I am hoping for a quick fix from Bryan on this, manual cleaning should not be needed.
