### ISSUE TITLE
feature request: create new desktop

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#387]
Create a connection to the new desktop, so that the computer user can continue to work, and at this time make settings on another desktop. Windows 10 has native support for multiple desktops (also linux)

**Comment by Ylianst** [comment]
This is one for Bryan. Seems like a big effort.

**Comment by Ylianst** [comment]
I chatted with Bryan on this. On Windows 10, you can't just create a new desktop, it would logout the local screen since most Windows 10 are a single user license. In theory this would be possible on Windows Server, but probably not something we are going to do.

**Comment by krayon007** [comment]
Well, not logout, it would lock the primary desktop. This is how RDP behaves... You remote into a virtual desktop, and the actual desktop gets locked.

**Comment by theredkoala21** [comment]
I think @Ilia1 is referring to windows 10 "task view". Where you can create a virtual-ish desktop. But it is simple a window hider lol. All of your comments above still apply.

https://support.microsoft.com/en-au/help/4028538/windows-10-multiple-desktops

**Comment by ghplw** [comment]
I think even if you managed to pull this off, Microsoft would soon find a way to stop it as this would make a very cheap terminal server where no security is required between users.

**Comment by Ilia1** [comment]
that seems to be exactly what i meant http://virtualmonitor.github.io/ but it only supports windows 7.


> 
> 
> I think even if you managed to pull this off, Microsoft would soon find a way to stop it as this would make a very cheap terminal server where no security is required between users.

https://github.com/stascorp/rdpwrap have already found a way to make a terminal server, but there is already a violation of the license agreement.

**Comment by Ylianst** [comment]
Going to close this as there is no plans to do something like this now. If there is a specific solution that would work, feel free to re-open.

**Comment by Ilia1** [comment]
https://spacedesk.net/ there is such a solution. Supported by modern versions of Windows. The second monitor appears only when a connection is created. Can you add support for this program?

**Comment by Ilia1** [comment]
http://www.eithermouse.com/ and this multimouse feature
