### ISSUE TITLE
bad web certificate 

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#3877]
Hi 

im using bad mesh central on a windows sever with nignx proxy manger in docker and keep getting bad web certificate  im unsure of what i need to fix 

i have taken to ssl certificate from mesh central and put them into my nignx proxy manger and that still not working
![Screenshot 2022-04-12 at 23 09 09](https://user-images.githubusercontent.com/23058718/163063084-231dc466-be5a-454e-b9f1-26d850fd7663.png)
![Screenshot 2022-04-12 at 23 08 55](https://user-images.githubusercontent.com/23058718/163063104-365db38e-1fdb-4090-b9da-9e0685884eab.png)

**Comment by Ylianst** [comment]
If using NGINX performing TLS in from of MeshCentral you need to use `CertURL` option. You can look [at this video](https://www.youtube.com/watch?v=YSmiLyKSX2I) for how this is done. You can also look at section 16 of the [MeshCentral User's Guide](https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf). There is a sample NGINX and MeshCentral configuration.

Let me know if this helps,
Ylian

**Comment by kylelliott** [comment]
all fixed
