### ISSUE TITLE
Errors in log after last update

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3879]
I have updated meshcentral today, mainly to install a new ssl certificate and noticed some errors in the logfile.
I tried a service restart first, but that did not seem to work and than a full meshcentral version update.

Also not sure why it would repeat the AMT port error multiple times

> 
> -------- 4/13/2022, 10:16:09 AM ---- 1.0.1 --------
> 
> ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
> 
> -------- 4/13/2022, 10:16:20 AM ---- 1.0.1 --------
> 
> ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
> 
> -------- 4/13/2022, 10:17:27 AM ---- 1.0.1 --------
> 
> events.js:287
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EPERM: operation not permitted, watch
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
> Emitted 'error' event on FSWatcher instance at:
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
>   errno: -4048,
>   syscall: 'watch',
>   code: 'EPERM',
>   filename: null
> }
> 
> 
> -------- 4/13/2022, 10:17:27 AM ---- 1.0.1 --------
> 
> events.js:287
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EPERM: operation not permitted, watch
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
> Emitted 'error' event on FSWatcher instance at:
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
>   errno: -4048,
>   syscall: 'watch',
>   code: 'EPERM',
>   filename: null
> }
> 
> 
> -------- 4/13/2022, 10:17:33 AM ---- 1.0.5 --------
> 
> C:\Program Files\Open Source\MeshCentral\node_modules\@yetzt\nedb\lib\datastore.js:77
>     if (err) { throw err; }
>                ^
> 
> [Error: ENOENT: no such file or directory, open 'C:\Program Files\Open Source\MeshCentral\meshcentral-data\meshcentral-power.db~'] {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\Program Files\\Open Source\\MeshCentral\\meshcentral-data\\meshcentral-power.db~'
> }
> 
> 
> -------- 4/13/2022, 10:17:35 AM ---- 1.0.5 --------
> 
> ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
> 
> -------- 4/13/2022, 10:17:40 AM ---- 1.0.5 --------
> 
> ERROR: MeshCentral Intel(R) AMT server port 4433 is not available.
>

**Comment by Ylianst** [comment]
Looks like you are running two MeshCentral instances at the same time. In that case, one will take port 4433 and the other will complain that the port is not available. Same probably goes for the file that can't be open. Check that you only run one MeshCentral in the background.

**Comment by Allowee** [comment]
Ahh that makes sense... had 3 instances running for some reason.
