### ISSUE TITLE
Type feature changing characters

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#388]
I'm trying out the new Type feature this evening and found a bug.  
I'm typing in a URL to a device that uses a specific port.  
So I'm typing in a command like this:  https://mydevice:8081
But when that text is sent to the remote device it is typed as https://mydevice:*)*!

So it appears it's seeing the :8081 part of the text as ASCII or something along those lines.  If I use the clipboard feature it works correctly.

**Comment by Ylianst** [comment]
Your right. I will fix this tomorrow.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-w with a fix for this. In the future Bryan may add a way to support non US-English keyboard, but for now this should fix numeric chars.

**Comment by PathfinderNetworks** [comment]
Hi Ylian, I just updated my server and tested this. I can confirm it is working correctly now.  Thanks!
