### ISSUE TITLE
MeshCentral Assistant Freezing

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#3883]
I was excited to try Mesh Assistant today for the first time, as it is a vital component of our vision.  It was easy to setup (no security blocking) but when I accessed the remote desktop, after opening the first application I couldn't click on anything else.  Eventually, the entire computer froze - even for the remote user.

This was tested on 2 separate remote computers in 2 separate locations, with identical results.  Has anyone else experienced this, and is there a workaround?  I desperately need to use Mesh Assistant!

Thanks!
TD

**Comment by Ylianst** [comment]
I will give MeshCentral Assistant a try again tomorrow, but with many of these issues, I need as much information as you can provide so I can replicate the issue. What version of MeshCentral are you running? What OS is Assistant running on? etc.

**Comment by trentdavis** [comment]
My Mesh Central Server version is 0.9.52.  I just realized that there's a new version, so I'll upgrade and test again.
Both remote computers were laptops and running Windows 10.  One was part of a domain and the other was standalone.  Let me know if you need any other details.

**Comment by trentdavis** [comment]
Just upgraded and tested again and problem solved!!!

Thanks so much!

**Comment by Ylianst** [comment]
Good thanks. Yes, I solved that long ago, the issue had to do with how I handled some display sizes.

**Comment by trentdavis** [comment]
One final question:  I notice that with Mesh Assistant Windows Defender or Anti-Virus doesn't complain.  Is there any way to get this for Mesh Agent also?

**Comment by Ylianst** [comment]
It's not. The MeshAgent does not require user consent and so, it's being used to do evil things. As a result, it's detected as dangerous by AV vendors.
