### ISSUE TITLE
General Tab Request: Last Reboot & Last Activity

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#3885]
Would it be possible to include last reboot and activity (keyboard / mouse interaction) on the general tab? Both would be useful for remote support with last reboot letting us easily see how long a system has been up (and when a user is lying about restarting their computer four times this morning already…) and last activity letting us know when a user is idle so we can connect without interrupting them. Both should be fairly trivial in Windows with last reboot date and time being displayed directly in the output of systeminfo (and probably in an API call - GetTickCount/GetTickCount64?) and last activity being available via the GetLastInputInfo API call. Mac and Linux seemingly have built-in options as well (uptime -s for last reboot though I’m less sure about activity on either platform).

Neither is terribly urgent but I feel like both would make good eventual additions. As always, thank you for your continued work on this!

**Comment by si458** [comment]
a work around is to go into the console tab then type `sysinfo`
you will get a big long json but inside it under `hardware` then `windows` then `osinfo` is `LastBootUpTime`

also in theory you can use `meshctrl.js` and automate looking up device IDs then running the `sysinfo` query and getting the JSON info

to get the Last Activity time would be very tricky and require edits to the Agent Software itself

**Comment by si458** [comment]
added a PR for you
it will show the last boot up time for windows devices under Details (Operating System)
as this information was already passed from the agent, just wasnt being shown in the web ui

**Comment by PetieM** [comment]
Nice, that's perfect. Thanks!

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/3660764e-dc33-4448-bfbf-de3bda5d3756)
