### ISSUE TITLE
User Prompt Timeout

### ISSUE THREAD

**Issue by mdshoaibumer** [Ylianst/MeshCentral#3888]
Dear @Ylianst 
Do we have any option to set the time out for the user prompt when we request remote access in Mesh Central?

**Comment by Ylianst** [comment]
Yes, in the domain section of the config.json, add this:

```
{
  "settings": {
  },
  "domains": {
    "consentMessages": {
      "consentTimeout" : 30,
      "autoAcceptOnTimeout": true
    }
  }
}
```

The default for "consentTimeout" is 30 seconds, and default for "autoAcceptOnTimeout" is false. Let me know if that helps.
