### ISSUE TITLE
My own MeshCentral instance is down

### ISSUE THREAD

**Issue by Niki-29** [Ylianst/MeshCentral#3889]
Good Morning,
i`d been trying to access to the mesh central remote accesssince Friday but is still seems like the server is down, I would like your help to solve this problem please to tell if i can do something or is really something on the server.
 
Regards.

**Comment by dinger1986** [comment]
what do you mean by down?

**Comment by Niki-29** [comment]
It show like this, with a time out

**Comment by Niki-29** [comment]
<img width="357" alt="screen" src="https://user-images.githubusercontent.com/70537026/163837882-7c13c4d6-5adb-47f6-8324-a83d3a34f785.png">

**Comment by dinger1986** [comment]
can you give some details about your server setup?

**Comment by Niki-29** [comment]
well i just configure our pcs on the platform to access from mesh and CIRA from this link https://mps2.qx.intraway.com/

**Comment by dinger1986** [comment]
and is https://mps2.qx.intraway.com/ your own hosted meshcentral server?

**Comment by Niki-29** [comment]
yes

**Comment by dinger1986** [comment]
ok, so I will loop back to my previous question.....can you give some details about your server setup?
What the server is, where its hosted, how you installed etc etc

**Comment by dinger1986** [comment]
presumably the mesh server isnt running but I cant point you in the direction of troubleshooting steps without knowing what its installled on etc

**Comment by Niki-29** [comment]
sorry, i don´t have that information, i just install the mesh.exe in the pcs an then came up to the meshcentral platform in thta link, i can search for that information if you need butt is really and urgent situation

**Comment by dinger1986** [comment]
who setup the server for you in the first place? You will need server access to get this sorted

**Comment by Niki-29** [comment]
<img width="561" alt="img" src="https://user-images.githubusercontent.com/70537026/163846829-96832e0d-9bb0-4449-b949-f6af87b90031.png">

**Comment by Niki-29** [comment]
is this usefull?

**Comment by dinger1986** [comment]
Well you need access to the server first of all

**Comment by dinger1986** [comment]
Yes, I found that earlier as the dns name resolves to it.

Did you install this yourself?

**Comment by Niki-29** [comment]
no, but the person who did it is no longer in the company

**Comment by dinger1986** [comment]
Do you work for intraway? The ip is aws

**Comment by Niki-29** [comment]
yes, that´s right

**Comment by dinger1986** [comment]
What's right? 

Mate not being funny, trying to help you here, need to give me as much info as you can so I can help.

**Comment by Niki-29** [comment]
i mean, yes i work for intraway and the server is a instance on aws

**Comment by Niki-29** [comment]
and i´m searching in our documentation to give you more information but it´s seems that nobody got it clear or completely

**Comment by dinger1986** [comment]
Ok so first of all you want to get into that aws account.

From the look of it a fairly big company, seems crazy they don't have it all documented etc.

**Comment by Niki-29** [comment]
is documented but by parts, i can access to the instance in aws, can i search for something or do something that can give you a clue ?

**Comment by dinger1986** [comment]
Can you tell me what version of linux is on it?

Can you get ssh access?

**Comment by Ylianst** [comment]
It's really out of scope of this GitHub to answer questions about a server instance going down. A server administrator needs to be able to run their own server instances properly. If the outage is due to a issue with the MeshCentral software or if https://meshcentral.com is down, please report it. But please don't report that your own instance is down without more info.
