### ISSUE TITLE
Feature Request: Schedule Domain Change

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#389]
Every now and then we have a business that will rebrand and will want to change the domains they use and eventually drop the old ones.

It would be good if we could tell the agent that from X date and time the server's domain name will change but also leave the secondary agent pointing to the old server in case something goes wrong.

I think this is low priority and you may already have a better method of achieving this but I wanted to bring it up anyway.

**Comment by Ylianst** [comment]
This is an interesting request. Right now, you can just direct both the old and new domains to the same IP address and MeshCentral should work just fine as long as you have the "Server Agent Certificate" to authenticate with incoming agent connections. The key problem is getting rid of the old domain.

Currently pretty busy, but certainly a request to keep in mind.

**Comment by dinger1986** [comment]
this is easily accomplished with a new vps spun up with a new meshserver, can use [my script](https://github.com/techahold/Meshcentral-Installer) to install on a new server and migrate agents across as they come online using a task scheduled on mesh using a plugin like https://github.com/ryanblenis/MeshCentral-ScriptTask 

@si458 please close
