### ISSUE TITLE
Intel AMT - Issue with static IP address

### ISSUE THREAD

**Issue by panenka** [Ylianst/MeshCentral#3890]
I'm using static IP address of the iAMT many years. I'm trying to change this to something more compatible with Mesh central and MeshAgent. I have different versions of iAMT, up to 15.x.
When I change IP address of iAMT on computer, which has 15.x version, to the same ip address as the address of PC, when the computer is power off, iAMT (ping, 16992 page,...) doesn't respond, when is on, iAMT is responding. When IP addresses are different, iAMT responds regardless of state of PC and is possible to power on PC when is off and so on. Where I'm wrong. Thanks

**Comment by Ylianst** [comment]
This looks like a Intel AMT specific issue, not something MeshCentral can do anything about. Probably best to ask this on a Intel AMT forum. It would be interesting to see if Environment Detection is active on your AMT device, if that is the case, changing from DHCP to Static will impact port accessibility.
