### ISSUE TITLE
Help with adding new functionality

### ISSUE THREAD

**Issue by DEFALTtttttt** [Ylianst/MeshCentral#3892]
how you can add functionality so that you can hear the sound from the microphone and the computer to which it is connected on your side.
And is it also possible to do something so that you can display the camera window that is connected to the remote computer?

like how it's done anydesk 
![image](https://user-images.githubusercontent.com/102130048/163971714-add09ffb-a1fb-434a-ba8e-a2a7558df99e.png)

**Comment by Ylianst** [comment]
The title "adding functionality" is not an acceptable title for an issue. Please change it to a correct title that describe the issue. Also, you start with "how you can add functionality...", are you asking for this feature? or are you asking how someone would add this feature to MeshCentral? If you are a developer, I would certainly welcome help adding sure a feature.

**Comment by DEFALTtttttt** [comment]
> The title "adding functionality" is not an acceptable title for an issue. Please change it to a correct title that describe the issue. Also, you start with "how you can add functionality...", are you asking for this feature? or are you asking how someone would add this feature to MeshCentral? If you are a developer, I would certainly welcome help adding sure a feature.

I ask the question, is it possible to add such functionality? I'm not a developer, I just wanted to know how to do this.

**Comment by Ylianst** [comment]
Ha. Yes, it's possible to add this functionality.

**Comment by DEFALTtttttt** [comment]
> Ha. Yes, it's possible to add this functionality.


it is difficult? is it possible to help with the code? Or is there already a solution?

**Comment by Ylianst** [comment]
it is difficult? - It is difficult, you need to capture the audio on the remote platform and stream it to the browser for playback.
is it possible to help with the code? - Yes, MeshCentral like other GItHub projects are open source and accept contributions.
Or is there already a solution? - Not one the is in MeshCentral now.
