### ISSUE TITLE
Linking from external systems to Meshcentral

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#3894]
Hey Yilan,

I have a number of other systems that track hosts via hostname, and wondered if it's possible to 'link' into Meshcentral and search by hostname.  As I understand it now, each external system will have to have access to the mesh node id in order to provide that direct link.

e.g. Would it be possible to support:

- `https://mesh/?viewmode=10&devicename=my_device_name`

or support accepting URL encoded search fields on the my device page?

Thanks!

**Comment by Ylianst** [comment]
So, the device's name is not a unique identifier, but if that is not a problem for you, I can add support for it. It will go to any device with the specified name?

**Comment by Ylianst** [comment]
Ok, I just added it, in v1.0.11 you will be able to do this:

```
https://central.mesh.meshcentral.com/?gotodevicename=Central&viewmode=10
```

Works on the mobile app too:

```
https://central.mesh.meshcentral.com/?gotodevicename=Central&viewmode=10&mobile=1
```

Once released, let me know if it works.

**Comment by Ylianst** [comment]
v1.0.11 is out.

**Comment by cgb** [comment]
Hey Yilian, I fire off a wishful request before sleep, wake up and find it's done.  Incredible!

I've updated my instance and tested the feature out successfully.  Thank you for the quick turn around...!
