### ISSUE TITLE
remote pc keep going offline 

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#3896]
i have just add the certurl and now everything is working but now be pcs keep going offline then back online have  tired add these 

```
"AgentPing": 55,
"AgentPong": 55,
"BrowserPing": 55,
"BrowserPong": 55,
```

but it when i add and then restart mesh central it doesnt come back up till i remove these setting

**Comment by Ylianst** [comment]
Can you post your entire config.json file with these settings included? Please put XXXX on any private information.

I am guessing your adding these lines in a way that makes the JSON file invalid. I have [a video on that topic there](https://www.youtube.com/watch?v=31mxfH4y1SY).
