### ISSUE TITLE
Adding HTTP/HTTPS on the device page

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#3899]
Thanks for this new Device Group feature, Ylian and team!
This isn't an issue but a request (and absolutely not an urgent one by any means).  Is it possible to add HTTP/HTTPS type 'devices' to the Device Group?  I'd like to be able to add devices that are managed via a web GUI (think printers, access points, etc) to the device groups. Granted, because it's a HTTP device, it won't be an 'active' connection.  But more of a shortcut to pull up the web management page.  Right now I do this via the Mesh Router.  That works well- but is not always convenient to go through all the steps to create a relay connection. 
Also, the list for choosing the device to be used as the relay can be very difficult to sort through since it just lists all the device names but without being sorted by device group. I don't know a good option to resolve that though.  Maybe something where you have a drop down for the device group and, once you pick a device group, another drop down will be present where you can choose the device within that group?

**Comment by Ylianst** [comment]
Try adding this to the domain section of the config.json:

```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "port": 443,
        ]
      },
```

This will create MeshCentral Router HTTP and HTTPS links at the bottom of the device "General" tab. One click will invoke MeshCentral Router and open the browser to the web page. Let me know if that works, I may add it as a default.

**Comment by PathfinderNetworks** [comment]
I will try adding that in the next day or two and let you know.  I'm just finishing up my work for the day (or rather morning!). Thanks for the very speed response though!  You must work the kind of hours I tend to work....

**Comment by OutbackMatt** [comment]
> This will create MeshCentral Router HTTP and HTTPS links at the bottom of the device "General" tab. One click will invoke MeshCentral Router and open the browser to the web page. Let me know if that works, I may add it as a default.

I had to change the code slightly (remove comma after port 443, and add next line  a curly close brace) for MeshCentral to read the config.json to load, but this doesn't seem to have any affect on my system at all. I can't see any new links.

`      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "port": 443
          }
        ]
      },`

**Comment by OutbackMatt** [comment]
Maybe I was looking in the wrong place, or maybe something changed but I can now see the 'http' and 'https' links on the **device** >> general tab - works well

(perhaps I was looking on the device group >> 'general' tab)

**Comment by masscream** [comment]
I've added this directly into the domain's section, but still no luck...

```
"domains": {
    "": {
      "_title": "Servername 1",
      "_title2": "Servername 2",
      "_minify": true,
      "newAccounts": false,
      "userNameIsEmail": false,
      "deviceMeshRouterLinks": { "rdp": true, "ssh": true, "scp": true, "extralinks": [ { "name": "HTTP", "protocol": "http", "port": 80 }, { "name": "HTTPS", "protocol": "https", "port": 443 } ] }
```

**Comment by masscream** [comment]
Actually, I'm not sure, what is wrong, but it isn't working at all. I verified my JSON file to be syntax-error free... updated to the latest version 1.0.85 but the links don't wanna appear at all. Is there something wrong with my config, please?

![Screenshot_2022-09-26_11-21-54](https://user-images.githubusercontent.com/11753248/192242452-80be31d5-c997-410d-add0-37a3cf40ad3e.png)

![Screenshot_2022-09-26_11-23-11](https://user-images.githubusercontent.com/11753248/192242481-abf8a998-a75a-462d-bf42-5f0c1ec80317.png)

**Comment by si458** [comment]
> Actually, I'm not sure, what is wrong, but it isn't working at all. I verified my JSON file to be syntax-error free... updated to the latest version 1.0.85 but the links don't wanna appear at all. Is there something wrong with my config, please?
> 
> ![Screenshot_2022-09-26_11-21-54](https://user-images.githubusercontent.com/11753248/192242452-80be31d5-c997-410d-add0-37a3cf40ad3e.png)
> 
> ![Screenshot_2022-09-26_11-23-11](https://user-images.githubusercontent.com/11753248/192242481-abf8a998-a75a-462d-bf42-5f0c1ec80317.png)
> 

The http and https links only appear when you enable web relay on the server!
https://ylianst.github.io/MeshCentral/meshcentral/#web-relay-using-dns-names-and-multiple-web-relays
Watch the 2 videos here to help you set it up

**Comment by masscream** [comment]
Thank you. That helped for this problem.
