### ISSUE TITLE
Regression: npm  meshcentral@0.3.8-p fails to white screen on IE 11

### ISSUE THREAD

**Issue by reidjr** [Ylianst/MeshCentral#390]
Following succesful login, browser displays white/blank screen.

Bisected and this error came in on the npm version above, and persists on the latest version. ( meshcentral@0.3.8-v at time of writting)

Works ok on chrome browser

**Comment by Ylianst** [comment]
Can you open the IE JavaScript console and post here anything you see? Thanks.

**Comment by reidjr** [comment]
``

**Comment by reidjr** [comment]
``DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

File: ************

HTML1300: Navigation occurred.

File: login

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

File: ************

SCRIPT1046: Multiple definitions of a property not allowed in strict mode

File: ************, Line: 6101, Column: 504

 

 

************==Domain name/server name

**Comment by Ylianst** [comment]
The error "SCRIPT1046: Multiple definitions of a property not allowed in strict mode" is interesting however, you blanked out the name of the file, so I have no idea what I need to fix. Can you click on this file and post the code that is about the problem line? Thanks.

**Comment by reidjr** [comment]
Hi,

I wasn't trying to make your job harder, but the filename on th econsole was the FQDN of my server !

When accessed from the Lan its:

SCRIPT1046: Multiple definitions of a property not allowed in strict mode
192.168.1.18 (6101,504)

which on the debugger is :

       var loclist = {'af':'Afrikaans','sq':'Albanian','ar':'Arabic (Standard)','ar-dz':'Arabic (Algeria)','ar-bh':'Arabic (Bahrain)','ar-eg': ……………………..

So I assume it was the recent change to  views/default.handlebars  in https://github.com/Ylianst/MeshCentral/commit/1694e522947a9a13704df610ff04096d9c0fdffd

hope that helps.

**Comment by Ylianst** [comment]
That helps a lot! Thanks. I will take a look at this.

**Comment by Ylianst** [comment]
Thanks. Found the issues, will have this in the next update tomorrow.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-z with a fix for this. Let me know if it works for you.

**Comment by reidjr** [comment]
v0.3.9-b

Works For Me :-)
Thanks
