### ISSUE TITLE
Problem connecting to windows machines by WinSCP

### ISSUE THREAD

**Issue by jamgrorg** [Ylianst/MeshCentral#3900]
Hi @Ylianst, I've noticed a problem with WinSCP protocol after one of the latest updates. Don't know wich exactly but I think it's 1.0.0. I can't connect to windows machine by WinSCP (connecting to linux works well) It seems like WinSCP not accepting any user and password intup.
Here're some logs:
1. WinSCP connecting log
<img width="684" alt="Screenshot_4" src="https://user-images.githubusercontent.com/2796027/164166331-c6a1d45e-f09e-4e0a-a8e9-3a090dcf7694.png">

3. MeshCentral connecting log through WinSCP
<img width="699" alt="Screenshot_5" src="https://user-images.githubusercontent.com/2796027/164166124-7577f4c4-cdb5-4d94-8e64-9b52a517fe04.png">

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
