### ISSUE TITLE
Vnc option

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#3901]
how do you setup/active novnc

**Comment by Ylianst** [comment]
It comes built-in to MeshCentral and enabled by default. Will show up for Linux and MacOS devices.

![image](https://user-images.githubusercontent.com/1319013/164322424-b27bf765-b209-4c1c-9986-c7f7e0765376.png)

**Comment by kylelliott** [comment]
but it doesnt seem to work tho just keeep loading and doesnt connect

**Comment by Ylianst** [comment]
Do you have a VNC server on the remote computer?

**Comment by kylelliott** [comment]
no

**Comment by kylelliott** [comment]
what about RDP

**Comment by Ylianst** [comment]
You can enable RDP by adding this line in the domain section of the config.json:

```
"mstsc": true
```

You need to restart the server and it will cause now modules to be downloaded. RDP support in MeshCentral currently uses legacy authentication, so you need to enable it on the remote system. I am working on adding NLA support.

![image](https://user-images.githubusercontent.com/1319013/164354408-fd5a74f1-7758-4d3f-b1ef-d3e0b240e9e4.png)

**Comment by Ylianst** [comment]
FYI. Built-in RDP now supports NLA, no need to disable NLA anymore.
