### ISSUE TITLE
New options are not showing even after upgrade

### ISSUE THREAD

**Issue by dani717** [Ylianst/MeshCentral#3902]
Hi, after upgrading to 1.0.11
I do not see the relay features when I click on "Add new group."

Any help with this, I appreciate it.

Here is my info 

<html>
<body>

 
--
 
> info{     "meshVersion": "v1.0.11",     "nodeVersion": "v11.10.1",     "runMode": "LAN mode",     "productionMode": false,     "database": "NeDB",     "platform": "win32",     "arch": "x64",     "pid": 3236,     "uptime": 241.046,     "cpuUsage": {         "user": 24578000,         "system": 2312000     },     "memoryUsage": {         "rss": 96460800,         "heapTotal": 58146816,         "heapUsed": 52401000,         "external": 65698339     },     "warnings": [],     "allDevGroupManagers": [] }

</body>
</html>

**Comment by dani717** [comment]
![image](https://user-images.githubusercontent.com/2160171/164365552-6ddaf4be-af1d-4934-a487-bb225aa755f7.png)

**Comment by Ylianst** [comment]
Your server is in "LAN mode". In this mode, you should be able to select "Local Devices, no agent".

If you want to use the relay feature, you need a server in WAN or Hybrid mode. I have a [video on these modes here](https://www.youtube.com/watch?v=gx5Fh3pQOns).

Let me know if that helps.

**Comment by dani717** [comment]
Thank you for the reply,

I changed it to WAN restarted the server, but I still do not see the relay options

> info
{
    "meshVersion": "v1.0.11",
    "nodeVersion": "v11.10.1",
    "runMode": "WAN mode",
    "productionMode": false,
    "database": "NeDB",
    "platform": "win32",
    "arch": "x64",
    "pid": 2364,
    "uptime": 71.625,
    "cpuUsage": {
        "user": 19593000,
        "system": 2734000
    },
    "memoryUsage": {
        "rss": 113995776,
        "heapTotal": 76234752,
        "heapUsed": 61377456,
        "external": 64758705
    },
    "warnings": [],
    "allDevGroupManagers": []
}

![image](https://user-images.githubusercontent.com/2160171/164737879-9859bc6f-5360-46c4-9541-1549fa4a4c05.png)

**Comment by Ylianst** [comment]
What options do you see?

![image](https://user-images.githubusercontent.com/1319013/164840581-2b45e38d-d8c2-4adf-bc18-96caa421a716.png)

**Comment by dani717** [comment]
Sorry I didn,t check the drop-down after changing the mode, it is showing now thank you so much this can be closed
![image](https://user-images.githubusercontent.com/2160171/164858237-eadf84d7-db12-42c7-974b-a80973cd0dea.png)

**Comment by Ylianst** [comment]
Thanks for reporting back. I will close, but since you created the issue, you can close it yourself.
