### ISSUE TITLE
Unable to parse config.json

### ISSUE THREAD

**Issue by Zed08w** [Ylianst/MeshCentral#3903]
Hello and thank you so much for this software

I am running ubuntu server 20.04
npm version 8.7.0

I had my server running for 2 months with no issues. After testing I decided to add some more users, before this I wanted to have forced password and 2fa.

my config.json before
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove >
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "my.domain.com",
    "_WANonly": true,
    "_sessionKey": "MlkfjbnlsdjkhbR*&G$**RBnwiuf*#@&*$&RG#",
    "port": 443,
    "selfupdate": true,
    "_minifycore": false,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "WebRTC": false,
    "WsCompression": true,
    "_AllowHighQualityDesktop": true,
    "_AgentCoreDump": true,
    "_ClickOnce": false,
    "_UserAllowedIP" : "127.0.0.1,::1,192.168.0.100"
  },
  "domains": {
    "": {
      "title": "rd",
      "_title2": "Manage Devices",
      "_minify": true,
      "_mstsc": true,
      "_ssh": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "my@email.com
    "names": "my.domain.com",
    "production": true
  }
}
```

I tried to add the below with no luck, when trying to run messhcentral it kept saying "ERROR: Unable to parse /home/ubuntu/meshcentral/meshcentral-data/config.json."

This error happens when I try to run the below command in the ~/meshcentral folder
node node_modules/meshcentral --cert my.domain.com --install
ERROR: Unable to parse /home/ubuntu/meshcentral/meshcentral-data/config.json.

```
  },
      "passwordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "reset": 90,
        "force2factor": true,
        "skip2factor": "127.0.0.1,192.168.2.0/24",
        "oldPasswordBan": 5,
        "banCommonPasswords": false,
        "twoFactorTimeout": 300

```
after trying to add and revert back to original config.json it keeps giving the same error even with the original config.json that had been working for 2 months

node node_modules/meshcentral --cert my.domain.com --install
ERROR: Unable to parse /home/ubuntu/meshcentral/meshcentral-data/config.json.

I cannot run my service now, is there something I can do to get it back up and running?

Any help is much appreciated and thank you again for the service
Will

**Comment by Ylianst** [comment]
I have a [video on this exact topic here](https://www.youtube.com/watch?v=31mxfH4y1SY). You can use the JSON parser from [DuckDuckGo here](https://duckduckgo.com/?t=ffab&q=json+lint&ia=answer). Cut & paste your config.json into the text box and hit "Validate JSON". It will tell you exactly where the error is.

In your case I get this result:

![image](https://user-images.githubusercontent.com/1319013/164380566-21934d8d-18df-484e-9edc-cf8c0fc96d7a.png)

After removing the two "__commentX__" lines I get this:

![image](https://user-images.githubusercontent.com/1319013/164380823-21fe4bea-c7d6-4ea8-b73b-05e4633313c5.png)

The problem is this line:

```
"email": "my@email.com
```

Should look like this:

```
"email": "my@email.com",
```

Let me know if that helps.

**Comment by Zed08w** [comment]
I just found your post going to https://duckduckgo.com/?t=ffab&q=json+lint&ia=answer to check json files

i editied my real info out for github

I had messed up the json file on line 2 and ended with a > somehow.

Thank you for your help Ylian
