### ISSUE TITLE
Letsencrypt test-... permission denied

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#391]
Hi
I have this error in log file.
Error: EACCES: permission denied, open '/opt/meshcentral/meshcentral-data/letsencrypt/webroot/test-.....

This occurred after the auto renewal certificate action.

My config:
 "letsencrypt": {
      "email": "xx@xxxx.pl",
      "names": "xxxx.xxxx.pl",
      "rsaKeySize": 3072,
      "production": true
   }

I use:
6.8 Increased Security Installation

Permision to file:
-r-xr-xr-- 1 meshcentral meshcentral   83 Apr 24 23:19 test-.....

I can't renew certyficate.

**Comment by Ylianst** [comment]
Well, this is a expected as the server can't write in the "meshcentral-data" folder, so the update will fail. You can do:

`chmod 777 /opt/meshcentral/meshcentral-data/letsencrypt`

To make the "letsencrypt" folder writable. Otherwise, you will need to find a different way to update the MeshCentral certificate. I will add this as a note in the documentation.

**Comment by Ylianst** [comment]
Just did a silent update of the MeshCentral Installation Guide to cover this topic. I did not change the document version number, but it's online now.

![x2](https://user-images.githubusercontent.com/1319013/62163393-19a92280-b2cf-11e9-9d38-36322abc2491.png)

**Comment by motapek** [comment]
> 
> 
> Well, this is a expected as the server can't write in the "meshcentral-data" folder, so the update will fail. You can do:
> 
> `chmod 775 /opt/meshcentral/meshcentral-data/letsencrypt`
> 
> To make the "letsencrypt" folder writable. Otherwise, you will need to find a different way to update the MeshCentral certificate. I will add this as a note in the documentation.

777 or 755 like in

**Comment by motapek** [comment]
Hi
775 like in post or 755 like in doc - I think that 755 but ?
I see that this same problem is with meshcentral-files. I can't upload files without changing permissions.

**Comment by motapek** [comment]
For me after changing permissions letsencrypt working fine.
For chmod -R 755 /opt/meshcentral/meshcentral-files uploading files working fine

**Comment by Ylianst** [comment]
Oh thanks for that tip. I just fixed the install Guide again for people to "chmod -R 755" the "meshcentral-files" folder. Also added "-R" to Let's Encrypt folder just in case they already have files in that folder.
