### ISSUE TITLE
No sure if this is a feature or config change

### ISSUE THREAD

**Issue by dani717** [Ylianst/MeshCentral#3911]
Hello Team,

Is it possible to add HTTP or HTTPS with IP and Port from the drop-down just like web rpd and web ssh
I use a mesh router to access other devices that use HTTPS such as ESXi and I thought maybe it would be possible now that we have a relay option. I might be wrong :)
![image](https://user-images.githubusercontent.com/2160171/164860572-52718774-c3e8-42a7-b9d0-5a90ab44e184.png)

Thanks

**Comment by Ylianst** [comment]
Try adding this to the domain section of the config.json:

```
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "HTTP",
            "protocol": "http",
            "port": 80
          },
          {
            "name": "HTTPS",
            "protocol": "https",
            "port": 443,
        ]
      },
```

This will create MeshCentral Router HTTP and HTTPS links at the bottom of the device "General" tab. One click will invoke MeshCentral Router and open the browser to the web page. Let me know if that works, I may add it as a default.

**Comment by dani717** [comment]
Hi Ylian,

Thank you for providing this config. This works, but I think I didn't explain my request correctly; I thought the new feature might bypass using the mesh router since we are now using a relay agent on the website. 

In our scenario, we are unable to use meshrouter due to company policies but we can use the mesh central web server and agents. If the relay option works just like mesh router where we can add Esxi or other web management devices, it will be a great option.

Thank you for this awesome product.
Dani

**Comment by Ylianst** [comment]
I see. The relay feature allows the MeshCentral server to access new devices by using existing agents as relays, it does not change anything on the user side. If you are looking to access HTTP/HTTPS web pages without MeshCentral Router, I could work on this but it would require that MeshCentral have an additional HTTPS port (like port 444). I could sent a cookie to the browser and open a new browser window to the HTTPS/444 port and all requests would be redirected to the target. Using this system, you can't open many web site in the same browser at the same time (one cookie and one port 444 at any given time) but it would work without a router.

**Comment by dani717** [comment]
This will be a nice addition to managing other web-based apps without a VPN connection using the relay option on the web.
Another way: If possible, in the future to allow only specific apps on a machine or through the relay option.
**For example** A chrome application is shared from a server or local machine and the end-user only sees chrome when they connect to meshcental. (Like thin client solution) The benefit of this would be using a secure HTTPS connection even if internal apps are not secure or don,t have a valid certificate. 

I feel like the second option will be best since you already have a lot of features such as a web application to connect, recording, sharing guest links, etc which can be used.

Regards,
Dani

**Comment by b8two** [comment]
hi @dani717,

I think your first request is to have Mesh Agent behave as a proxy for HTTP/S pages. i.e. the Agent will make the HTTP request and then act as the http/s server to share it back to the user. There are many open source software that perform this kind of function, Apache webserver can be configured as a reverse proxy for example.

@Ylianst is suggesting a Mesh Agent port mapping for the HTTP/S page similar to how the Mesh Router performs this function.

@dani717 The second option you proposed is App sharing, similar to remote desktop but limited to an application window/s, This would require the Mesh Agent to focus on the App only (perhaps run as User 0 and perform background app rendering I assume) which is different to Capturing full screen/s. Citrix has ways to do this for multiple users, so it is possible. However to support multiple users, the server machine must be logged in different profiles to do this securely.

**Comment by dinger1986** [comment]
@si458 not likely to be implemented

**Comment by si458** [comment]
correct this wont be implemented,
if you want http/https access, just add the device as a standard linux device then do as @Ylianst explains above and add extra links in for relaying in meshcentralrouter
OR
use the web relay feature thats now built in
