### ISSUE TITLE
Server Stats traffic to high?

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#3915]
I just found the Traffic stats but then I noticed it is a bit high.
running meshcentral 1.0.5 on windows server.

50MB and 650MB for a terminal session? maybe these should be bytes?
For desktop it even says 87500MB for 5 minutes of use.

checking the files and agent stats it seems fine (registered 13k for a 10k excel file)

![image](https://user-images.githubusercontent.com/55733884/165101193-449617c9-37fa-4218-93bd-c89722cbadd0.png)

**Comment by folosleg** [comment]
Same issue here. Some non-real traffic stats are displayed for Desktop sessions.
MC 1.0.98
Ubuntu 20.04 LTS
node v16.18
behind HAProxy as SSL offload reverse proxy

any idea? how can I be any help to debug this issue?

![BCtiELVIto](https://user-images.githubusercontent.com/80481320/201974581-995345d9-e852-4834-ac0f-b2ae3e334a11.png)

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back

**Comment by edlins** [comment]
This sure looks like a cumulative total, not an interval total.  One remote desktop connected, left overnight.  I don't really care unless it eventually causes some overflow error or performance issue.
<img width="1845" height="912" alt="Image" src="https://github.com/user-attachments/assets/33efe922-17b5-4655-a4c9-f616f10c6020" />

EC2 monitoring shows actual network out (spikes are hourly db backup uploads).
<img width="1715" height="657" alt="Image" src="https://github.com/user-attachments/assets/79de5824-6f95-46d3-97ac-e849759cc02f" />

node 16
meshcentral 1.1.44
