### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#3916]
getting black screen when remoting in at home but at work it works prefect

**Comment by krayon007** [comment]
Does it say it's connecting with webrtc? I know there is currently an issue with chrome, but I haven't root caused the issue with the recent chromium update that broke webrtc.

**Comment by poiNt3D** [comment]
Sometimes black screen appears when you connect to Windows machine with locked screen after unlocking it. Reconnecting helps in this case.

**Comment by krayon007** [comment]
I just fixed a webrtc interop issue with Chrome and Edge, that caused a black screen. This will be in the next agent update.
