### ISSUE TITLE
Agent Download Filename

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#392]
Currently when you download an agent for a group you can choose from the 32 or 64 bit version. It would be good if the prefilled filename that saves reflected which version you download.

**Comment by Ylianst** [comment]
Yes, I can do this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.8-y with Windows agent filename now "MeshAgent32-GroupName.exe" or "MeshAgent64-GroupName.exe". Let me know if that works.

**Comment by ghplw** [comment]
Thankyou, works well :)
