### ISSUE TITLE
Mesh agent domain migration

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3920]
Hi,

Initially we have rolled out mesh agents span across multiple location, under single default domain (with each location devices separated with different device group). Now there is a need to migrate them to the different mesh central domain configuration (each domain systems will be maintained by different set of users). Any guideline to achieve this without updating or reinstalling anything in mesh agent side?

**Comment by Ylianst** [comment]
There is no system to auto-migrate agents between domains. What you can do is get the meshagent.msh file for the new domain, remotely copy that file over the old meshagent.msh and remotely restart the agent service. It is a manual process, but I am sure would could automate it.

If you add ?debug=1 to the URL and hit "Add Agent", you can download the meshagent.msh right from the site.

![image](https://user-images.githubusercontent.com/1319013/165802174-7e004b83-53dd-4fc5-879e-2f50ab82cba2.png)

Let me know if this helps.

**Comment by knkumar93** [comment]
Thanks, this should help for now. 

Closing this.
