### ISSUE TITLE
High memory usage from agent

### ISSUE THREAD

**Issue by baclaeys** [Ylianst/MeshCentral#3922]
I'm not sure if this is a bug, but I thought I would report it.  The server version is 1.0.5.  The agent is running on Windows Server 2019, and the mesh agent has been using up to 1gb of memory.  After the agent is restarted it will go back down.  Any thought on why this may be happening?  I usually update to the "Latest Version".

**Comment by Ylianst** [comment]
Are you using any plugins?

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
