### ISSUE TITLE
Route all trafic of one agent pc through another agent.

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#3925]
Dear Ylianst,

In meshcentral router we have the facility to route the trafic of particular IP through another agnet using relay map.

We are handling few servers those doesn't have any other external internet access. Only those systems are communicated with meshcentral servers and internal systems.

Is it possible to route all traffic of one PC through another system ( currently port based relay map is avail ) also is there any options to connect a domain through the relay mapping?.

**Comment by PathfinderNetworks** [comment]
It should already be able to do this. Or has that changed?  I know, at least with version 1, you could install an agent on a device that had no Internet access and it would communicate through any other Mesh agent in the same subnet/LAN.  Hence the name- 'Mesh'Central (it created a mesh network in other words).  To be honest, I haven't tried that in a very long time though- definitely not since moving to version 2.

**Comment by Mfinadmin** [comment]
@PathfinderNetworks - I am asking the facility reroute entire traffic of One PC through another agent not for (specified IP / Domain).

**Comment by VINISHVV** [comment]
> It should already be able to do this. Or has that changed? I know, at least with version 1, you could install an agent on a device that had no Internet access and it would communicate through any other Mesh agent in the same subnet/LAN. Hence the name- 'Mesh'Central (it created a mesh network in other words). To be honest, I haven't tried that in a very long time though- definitely not since moving to version 2.

@PathfinderNetworks - Agent to agent communication is not available in meshcentral 2. May be its due to security issues or many open port communications etc.....

Here i need to route all traffic of one system through another agent using meshcentral router. Currently port based and ip based relay is available. Is there any work around for manage all communication through an agent?

**Comment by silversword411** [comment]
I haven't looked...but when specifying port...it doesn't accept a range? 
`1-65535` would effectively forward all traffic 😉

**Comment by VINISHVV** [comment]
> I haven't looked...but when specifying port...it doesn't accept a range? `1-65535` would effectively forward all traffic 😉

Option to specify port range is not available

**Comment by Ylianst** [comment]
If this issue not solved with the recent addition of local device groups that can be configured to work thru a agent relay? [Blog post here](https://meshcentral2.blogspot.com/2022/04/meshcentral-device-groups-with-relay.html). You would be able to setup a single agent in a remote network and manage all the devices you want.
