### ISSUE TITLE
Getting 404 error while click on webrdp

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#3927]
Dear Ylianst,

I am getting 404 - Page not found error while click on the Web-RDP button.

I am using latest MC version - 1.0.15 & Node 18.0.0

![image](https://user-images.githubusercontent.com/80849522/166194233-c52b865c-077b-454c-a45b-568ccc260b80.png)

**Comment by cbrand-ludlums** [comment]
I'm getting the same, MC v1.0.15 and node v17.9.0, This is what I've got in my config.json.  The router RDP link works, but not the web rdp, just gets the 404 page with a url like `server.com/mstsc.html?ws=hash`


```
      "minify": true,
      "_mstsc": true,
      "novnc": false,
      "ssh": false,
      "_deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": false,
        "scp": false,
```

**Comment by smartekIT** [comment]
you can downgrade your Node to v16.15.0. here is how I did it to downgrade from Node v17.8.0 to v16.15.0:
https://github.com/Ylianst/MeshCentral/issues/3924#issuecomment-1115056278

**Comment by VINISHVV** [comment]
> you can downgrade your Node to v16.15.0. here is how I did it to downgrade from Node v17.8.0 to v16.15.0: [#3924 (comment)](https://github.com/Ylianst/MeshCentral/issues/3924#issuecomment-1115056278)

downgrade is not a good solution.

**Comment by smartekIT** [comment]
> > you can downgrade your Node to v16.15.0. here is how I did it to downgrade from Node v17.8.0 to v16.15.0: [#3924 (comment)](https://github.com/Ylianst/MeshCentral/issues/3924#issuecomment-1115056278)
> 
> downgrade is not a good solution.

for people running Node v17.9.0 wouldn't be much different if they downgrade to v17.8.0 but at least they know MC v1.0.15 is working on v17.8.0 if they can't go back to v16.15.0.

I'm not an expert but speaking from my last day experience, tried it in v16.15.0 and was working, then v17.8.0 and got it working too but must be MC v1.0.15 not v1.0.13 nor v1.0.14 as they don't.

**Comment by VINISHVV** [comment]
> > > you can downgrade your Node to v16.15.0. here is how I did it to downgrade from Node v17.8.0 to v16.15.0: [#3924 (comment)](https://github.com/Ylianst/MeshCentral/issues/3924#issuecomment-1115056278)
> > 
> > 
> > downgrade is not a good solution.
> 
> for people running Node v17.9.0 wouldn't be much different if they downgrade to v17.8.0 but at least they know MC v1.0.15 is working on v17.8.0 if they can't go back to v16.15.0.
> 
> I'm not an expert but speaking from my last day experience, tried it in v16.15.0 and was working, then v17.8.0 and got it working too but must be MC v1.0.15 not v1.0.13 nor v1.0.14 as they don't.

Lets wait for @Ylianst findings in this case

**Comment by Ylianst** [comment]
Ha! Thanks for reporting this, I just made a fix, it will be in v1.0.16.

Also, don't downgrade your NodeJS, it's super important the MeshCentral be able to run perfectly on all v17.x.x versions. Do report any issues. in this case, it's not a NodeJS related issue.

You can work around this for now be adding this line in the domain section of the config.json:

```
"mstsc": true,
```

If you have this:

```
"_mstsc": true,
```

Remove the _ and restart the server.

**Comment by cbrand-ludlums** [comment]
That worked for me.  Removing the underscore and having "mstsc": true, in the domain section worked.   Weird, I could have sworn I had tried that in my testing to see if I could get it working.  Thanks @Ylianst

**Comment by Mfinadmin** [comment]
@Ylian - Thanks this issue is resolved.
