### ISSUE TITLE
Keycloak SSO SAML with Meshcentral

### ISSUE THREAD

**Issue by sean-sullivan1** [Ylianst/MeshCentral#3929]
I am having some difficulty implementing Keycloak with MeshCentral. I've successfully gotten Keycloak to work with BookStack today, but MeshCentral is proving to be more difficult.

I've attached a screenshot of my Keycloak SAML client config and the config.json that i'm using with MeshCentral. The config.json does get parsed correctly. I'm mainly having an issue with the redirects to MeshCentral. If anyone could help I would greatly appreciate it. I've also looked around on reddit and in this github and can't find any full config unfortunately. I am using MeshCentral in a docker container if that makes any difference.

config.json

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": "10.0.0.2",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "AllowHighQualityDesktop": true
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://mydomain.com:443",
      "authStrategies": {
        "saml": {
          "__callbackurl": "https://auth.mydomain.com/auth-saml-callback",
          "NewAccounts": true,
          "entitiyid": "meshcentral",
          "idpurl": "https://auth.mydomain.com/auth/realms/general/protocol/saml/clients/meshcentral",
          "cert": "keycloak.pem"
        }
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}
```

![Screenshot 2022-05-02 at 19-16-34 Keycloak Admin Console](https://user-images.githubusercontent.com/46687337/166341626-eb93efce-4485-4f74-8131-0891f46c5b0b.png)

**Comment by Ylianst** [comment]
I have never tried Keycloak. At first glance, your setting look good. I don't need any issues. Can you run MeshCentral like this:

```
node node_modules/meshcentral --debug web
```

Then, try to login using SAML and see if any error of warnings show up on the console? - Thanks.

**Comment by sean-sullivan1** [comment]
@Ylianst Thank you for your response!
So I am running this in a docker and not really sure if it can be started with debug through the console. But I did enable tracing and logged it with a local MeshCentral account and then tried SSO with Keycloak through a private browser.

The only debug log I get for type WEB in the trace is: handleRootRequestLogin()
There are no further WEB types that get generated during the SSO process. Also when I do try the SSO I get a 502 Bad Gateway.
![Screenshot 2022-05-03 084238](https://user-images.githubusercontent.com/46687337/166455078-365d0d5d-9831-4fe5-99a0-a56f8036e4de.png)

![Screenshot 2022-05-03 084458](https://user-images.githubusercontent.com/46687337/166455219-4b6d3242-f4d6-44c3-b2c4-5af6fc2a2f9e.png)

**Comment by Ylianst** [comment]
Ha. Bad gateway is an error that happens when the reverse proxy can't route the connection. There are many causes of this, but you need to look at your reverse proxy logs to see what is going on.

**Comment by sean-sullivan1** [comment]
@Ylianst 
Good call I should have realized that. So I ended up having to increase some nginx proxy buffer settings.
Specifically, (*note I am using linuxserver.io swag reverse proxy)
In proxy.conf change `proxy_buffers 32 4k;` to `proxy_buffers 4 128k;`.
In my keycloak site-conf (virtual host file) change or add `proxy_buffer_size 128k;` AFTER ALL INCLUDE STATEMENTS.

Now I am getting redirected to meshcentral, but i'm getting a 404 error. I'm probably redirecting to the wrong location.

`404 Error /auth-saml-callback?SAMLResponse=zVhZk6LKEv4rHc5jh8MqizHdcVkUUREVRfHlBBTFToEsov76i3bbR%2Fv0zJn7cCPmjcrKyvrqy6wks36Udprk%2FSUs8wyV8OmYJqjsX4UvnbpA%2Fcwuw7KP7BSW%2FQr0DUGb9snveD8vsioDWdK5W%2FLrFXZZwqIKM9R5kmFZhci%2BDF46QVXlZR%2FDWv3ge1nWSRIebPS9giDA7LoKuhfTXWAniWODuPOkyi8dVf7LJjzapWi86%2FRgr0sD2%2BvanM12aZIgSBb2egTptsqtQaiisrJR9dIhcZLs4r0uTq9wok%2FzfYr6TlHUrvNkwqK8ommRdl5%2FXLbsX9cWrzd8Fyxf4cMKaCdpifkQwcJOfmD3i3%2B88WtUdlWXjyMpc%2BGTaSc1%2FDVv5VW7b9QAwLLsYK9vOzwa7Qs3dt%2F88duueGeTYQmC4Fm7SxKe16WZHtnlPQ90geMRJM4Azuap32OT%2FH%2By6Zah3zdCv42durhF60X4Fkat3aZpvjfU96zwMRLHcQznsVbrovKtc7ceuirysneBZKMMhW2EhedrTGqwCjL3SUj8rAirIP2JcQIj8IvxLjy2RBE0%2BnZxziPE3zaF0zec3TQr4LeitLtlYJM95sPoEnqwgAjAp%2FVSfel8%2B123vS9fFTYqvaxIy8%2BCf4X3QCNEB5hkOXS75e2UHxB%2F3%2BTX5GFfI5VDv80Y%2FyOXLVPfPjH4Zud6516pVYqskmRLenza7onzaJ%2FxGZNPJHCAkJL0ZIkFhlxPegv15R3X%2FfJ30YdPboJ%2FBNdHKLytCxrk4Yq%2Bb3BllVXSkFY1C%2BWiHJEL3ClQuJzVftZz0FFYwq1GMkuF0XMun7j1ouqNVAeLhqtSL%2FkJQ%2BmoSBdRkDzr03w%2FU2V34KYr4WiXc3%2FLOHsLbQqJMZ51aVkyezYI9SzAxOZc5kYyrTCKxqohSLdT2ZQLOdk1U5qQlELxDlt4YHUcX65NNk2TgRQE%2B1XRM9kanx790ZETFEYRVsmzok8z4DZhJQqVtdwfk%2BfnfFBjwi5ZM0rPD%2BJ4RywKZ1s6HE2vkslGsup0p8SKulN3umUcInkpVkRvuNXOjbg3CzoaHsS8yYpcWNBGgMD66OwrTzwxQLHEhjgcrDTSB2ttwdJYwEQiN2TdOdyempeXO%2Frv2H5zwQSe7hzSjmZtRnyVZi9OlsVtMgPx%2B%2Brb1Jvitofzsl3Zd0Ppkja9NlVU8FVTVSlbSZJgxZLoK0KwieVTJMxEP94HcajwDS4Ki3IoyMJaW6rNQLBkc7GQZSEJHZIvALUMLLJsRgGYaZHazFbCSVutz9p5cN5cZOe%2FZTN5fd5Ev7bj%2B4NQE3BFMvaKoTqUvBi0%2B68FgVZFuREu8xMhU1uZFDeckA69sjn5x7mjRIY1TCqO3vPNwjtA3jwOTgXT28fYuFbmDFrWddZsDtRamq%2BoEjseVTvYeGQPD6KxJWarJDnqq3FAZocZA3Wqmpa6VJvbNUXmo0oxUikZHqfGMIcO3gxEfhofELsaHZueywwUglyNN%2BvKXGXtL3xiclN9DWiD1pU5Cy3iUMYDPfY5i6EaLwtWmMpHm%2FE62egxTwg8p%2B%2BajREI%2BaxC49qvyQBuOSZ2edoj0tmhdienhjqth%2FF5PwtlchDtRxzjTzae2pwdIk2flbSKKkE4BnYE9UaXcNxch7ksEhH0%2BLhYWyndMjewCY5NLHqhS8J%2BEPO74amcY7w3bojp0HYXJ0J3PcHXREEYNPLCGk%2BynRocwExYDKbiQpBb7kVBZSlAnPjDvtHjbDnx2TycOVPDhKT6PK975mZiOlswSByW5E0i2%2BRrU%2BMrHFl6NkIyvyDI3SGbgGgeMLvVKkpGBLce0qO5k895KgSAiFdr97maMT32FGMr1pXWDr5b6yxHm0UzrrYnIHuzwLIcEShgiYYmv0ncHfJDfIghH03UKnK3Jp4hjK%2BgxaVIzCbk%2FDhchoqAr9W9njEzI3LcIKFR2hPz5Jke9IR4W1rMWFKcjb6NjcmSj6lk6I3UiVMrBF2XZKyO4jClDudUTgtJAbY0GiAq2TfyeCErGr0LCl6YsrlPacPi2VjZvcY8WOQ0obian%2FLZOQrgRjuqzn5jGEhzeBDa2JgTeDcw9tzt5n%2B%2Bnnfiu0vc3vD7zLA0hE8SLXPrpK2qcm0ujIMtq2mZtiKPGZ6KO8fTJwcwGLHUwQRLbf9c2%2Fn85ATRc97m7n2Lvo3JCOfZOQcMJTMRX7uqddoI9qC3A6v4ZLn76RmiqGINVvaLxCRm%2FH7JLuPcz5fAwAN7m%2FJtFHlGb9p7xo8c0LcwECs3PpnJ1FwzIwWdEk86JyN9UMvtxlQ6c9ixKOfqXNErbsSoa%2Bw0t4jQHJtRPncXc09OwTDOFpOVszs52bTKtgmm5yMPjvhd5LDIKMsZl4g7jYksnw9UJsD0TErQSdNIfpcfgryw2IWgWZuMikrZr2ZDU90vGteiELabEMq4FjRVVCpP7230QRvrk2A83yxBIWNYG3Mz47hBa61aoe3fefpG8xvpg2PbfUBUvQoLQXzX%2BJDd%2FrT3rsI%2BORN7zPOf%2FgXvFahROxEE1fvokuhV%2BWnYlhl29fNymfhOXCWh2%2FWuqn2Y2mEiuG5xqcZfS2ij%2FzzWse8169sGj3tLGfLCi5VLof5Wz%2Fy6Ugdp34F2AYvOzw1dwvtpllU60gvBq2DxuTTv0X2KeC%2FNlxCEeQgv9fv%2F2HjdGo%2BvIHyaesfaarjhZbq8wBNhSyD8qm24YfvlGfAPvVvHU7vhpfJqe9eqCMEbjIeZ18vJQHvWvxuJj6lP4wcj2Cf0H2arAF2aLpi2Np%2Buw99oLY02TlorKnLh8aUDIMUSJAW6rgf4tm11nS7HAKfLMDzH0LjD2AzR70PKAZCnuS5kqFaLw8kuh7eqeI9wXdfGGQKyH5Z%2FShvxAOT%2BFO3ZKnisvhBJSdsctlXt6y%2F7R9AHF71WXKMyb0PKC6H7QekX1r6Ye5B90HqDVLXucOoK%2FnTi6XK%2FXjrLLIGd6%2Fe%2F3eQr8Hb1RXq7y06rBzqfTV%2BTyntzeSx%2F2mZstakBgjYddD50w39X7obXkAEt6la%2FX53y9hTHsn%2BJP%2BR3XlMb2T7s2gBkNaq6SYji8sbUA8A%2FCnXmeS1S%2BJd9faT48%2FEeQth08yLzwgT%2B%2BWgfY%2BLPx1un9l%2BXP0jbp7%2B9qPz5kF3o2XVSdYs2n5Tdu8bwS%2BCfpP8Q3GUt7PF57uP17vbk%2Bvpf&RelayState=https%3A%2F%2Fmesh.mydomain.com%2Fauth-saml-callback&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=j27OFA5gBgT9zxIa2qHcH8exlSnj4EdfIMyZae9QYD0JrFMp%2FqUKdgUT5jvrg9zt6KOcmiAmSoClDwLx9%2FXJVBHpQTkmWCah9b6zQD8XuDjHU4JX0knSVGCfm8PtOSEbTmNcBV2CJ%2BDsmURSeuisJ2ck1cX6qYHG12bj8HDwt0yvPvWgKaRSMx3NcvDrU7wRBRF1i2EgPlgQLGYNCUM2cu6OqdotGyyLLZ%2BHAieOY4Gq%2BtMvjEdb5spw2VJhoFOUKIX3N90eKtVEBsHw9WutXn5grNYSCEehtD8X0%2BRBebTVIzkfqRykCfidPGmhVJRXbbqp5hcAX3mmWcNEI4SpQw%3D%3D`

I have also modified my keycloak saml client config just a bit, changed Valid Redirect URIs from https://mesh.mydomain.com/auth-saml-callback to https://mesh.mydomain.com/*
![Screenshot 2022-05-03 at 22-00-44 Keycloak Admin Console](https://user-images.githubusercontent.com/46687337/166614024-fa4d0d06-485f-4ca0-b757-9f2c6ce7133a.png)

**Comment by sean-sullivan1** [comment]
So i've been working with ListenLinda_Listen on Reddit and he lead me though his setup for Keycloak. It works now you have to have the following setting to get SAML to work with Keycloak.

MeshCentral config.json
![Screenshot 2022-05-04 120734](https://user-images.githubusercontent.com/46687337/166724068-cc38dccb-be36-455b-82a6-15d384b5749a.png)


Keycloak SAML Client Config
![Screenshot 2022-05-04 at 12-05-03 Keycloak Admin Console](https://user-images.githubusercontent.com/46687337/166723526-98bcb537-2503-4a94-9f63-d1f846cd8ef2.png)

**Comment by sean-sullivan1** [comment]
Update, keycloak changed something earlier this week. You may need to remove the /auth part of the IDP Initiated SSO URL in the meshcentral config.

**Comment by pggsadmin** [comment]
@sean-sullivan1 

I tried to integrate Meshcentral with keycloak saml.
When I click on the SSO login button in Meshcentral login page I am getting 404 error. 

The redirect page seems Meshcentral.com/auth-saml


Can you help by sharing your config file by replacing your actual domain name with Meshcentralurl and keycloak urls

**Comment by sean-sullivan1** [comment]
@pggsadmin Recently there was an issue with the NPM package passport that prevented saml auth from keycloak from working. This github [link](https://github.com/Ylianst/MeshCentral/issues/4034) may be able to provide some insight. If you still have trouble please reach out again here and we can figure out what the issue is.

My current IDP url is as follows: https://SUB.MYDOMAIN.COM/realms/general/protocol/saml/clients/meshcentral

**Comment by pggsadmin** [comment]
Dear @sean-sullivan1 

Thanks for prompt replay.

I tried the same method, now I am getting an SSO login button in Meshcentral login page. If I click the button then it's redirect only to mydomain.com/auth-saml only. Also can you share your keycloack config by replace domain name with mesh url and SSO url ?

**Comment by sean-sullivan1** [comment]
@pggsadmin 
![Screenshot 2022-05-30 at 23-19-55 Keycloak Admin Console](https://user-images.githubusercontent.com/46687337/171086364-2cebd61a-be7b-4514-86b7-301649809bbd.png)

**Comment by pggsadmin** [comment]
@sean-sullivan1 

I am getting below certificate related error while login meshcenral through SAML auth.

Can you please guide me to fix this issue ?.

![image](https://user-images.githubusercontent.com/82675244/171322485-e03f5a64-506b-4297-9979-f44990550c5e.png)

**Comment by sean-sullivan1** [comment]
@pggsadmin
Have you placed your keycloak.pem file in the correct location? You have to download the .pem file and place it in the same directory as the config.json for meshcentral. This allows meshcentral to trust keycloak.

**Comment by pggsadmin** [comment]
Dear @sean-sullivan1  - I have placed the certificate in meshcentral data. I think i have placed wrong certificate.
Can you suggest how we can export the .pem certificate.

**Comment by sean-sullivan1** [comment]
Copy the text that appears when you click this button in keycloak.
![Screenshot 2022-06-01 001905](https://user-images.githubusercontent.com/46687337/171326808-e8857392-c275-45c2-8cc2-5e36c30c3156.png)
This is the RSA256 pem contents. You will create a text document with vi/nano named keycloak.pem and place this in the same directory as config.json for meshcentral-data.

**Comment by pggsadmin** [comment]
@sean-sullivan1 
Thank you... 
Finally i got access through keycloak.

Is there any configuration to allow users to view particular meshcentral group / user access ?

**Comment by pggsadmin** [comment]
Can you suggest how we can permit the permissions in meshcentral

**Comment by sean-sullivan1** [comment]
Each saml user should only have the permissions/device group access they need to do their job. New saml accounts will not by default have any access to a device group it must be granted by another account with permission to do so.

**Comment by pggsadmin** [comment]
Thank you so much.

**Comment by sean-sullivan1** [comment]
@pggsadmin Final note make sure that local admin user has a substantial length password. I'd suggest as long as you can make it, mine is 64characters long.

**Comment by minster586** [comment]
would me nice to edit and set this up in the web UI and use the "https://FQDN/keycloak/realms/master/protocol/saml/descriptor" or "https://FWDN/keycloak/realms/master/.well-known/openid-configuration" as editing cuz I cant find anything
