### ISSUE TITLE
Web-SSH disconnecting session on it's own! States "Session Expired" when attempting to reconnect without re-opening the browser window.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3932]
Okay so this issue is pretty simple to explain. I have noticed that the Web-SSH is disconnecting the browser session even with activity in the ssh session. Not sure if there is a way to fix this or not but when I run long install scripts and the session dies in the middle of the install, the entire install is messed up because the script also dies with the ssh session. I would like this to attempt to reconnect the ssh session before closing the connection when I'm not clicking on the disconnect button.

MC Version: 1.0.14

In the Console tab of the machine this happened with:
``uncaughtException1: Error: timers.onElapsed() callback handler on '()'  => waitExit() already in progress``

Image of the Console tab under the inspect element option in the Firefox v99.0.1 web Browser. Note that this is there even before I click on connect to start the Web-SSH session. I suspect that this error results in the session being disconnected:
<img width="1820" alt="Untitled" src="https://user-images.githubusercontent.com/46533576/166399878-737e6d28-68e4-437a-b926-6e99723f03a6.png">

No sure what else I can provide at the moment. Please let me know if there is something else that I can provide to help

**Comment by Ylianst** [comment]
I am working now on integrating RDP support into the "Desktop" tab and as a result of this, changing the way the connection authentication works. That may fix it and improve RDP support a bunch.

**Comment by Ylianst** [comment]
FYI. Early screenshot of RDP connection from the "Desktop" tab. I just got it working a few hours back.

![image](https://user-images.githubusercontent.com/1319013/166407556-da5bccf4-0217-444b-81b9-3dc4372ffd79.png)

**Comment by LPJon** [comment]
I'm curious, is this also possible to do with Web-SSH and Web-VNC? If so this would be much better than web links on the general tab.

**Comment by Ylianst** [comment]
Web-VNC would take some work but SSH is certainly possible since it's already merged into the terminal tab for local devices, I have to make it available to agent devices too which should not be too much work.

**Comment by LPJon** [comment]
That would be really nice also!

**Comment by Ylianst** [comment]
Now the RDP is integrated, I am going to close this issue. At some point, I am going to remove the "Web-RDP" link as the same RDP client is now built-in. For other integrations, do file new issues for these. If RDP still disconnects using the built-in RDP client, so file an issue. Thanks.

**Comment by LPJon** [comment]
@Ylianst I'm a little confused. This issue was related to Web-**SSH** not Web-RDP. Why is it being closed as there wasn't an issue with Web-RDP for me.
