### ISSUE TITLE
meshctrl.js deviceinfo wont show agent tag

### ISSUE THREAD

**Issue by tiagogbarbosa** [Ylianst/MeshCentral#3935]
Hello

is possible to agent tag be show on deviceinfo?
Ty

**Comment by Ylianst** [comment]
Working on this now.

**Comment by tiagogbarbosa** [comment]
Not working for me :
![chrome_MTLg0t3Pah](https://user-images.githubusercontent.com/8936001/167036846-9f01e8e8-9029-4e3c-a36d-7308835a6606.png)
![hTYJjmk91i](https://user-images.githubusercontent.com/8936001/167036852-8022dc3d-90e0-4448-adcb-4ebfac3db791.png)
![image](https://user-images.githubusercontent.com/8936001/167036994-935376fa-011a-4932-91ba-1cebc2d81a25.png)

Any idea?

**Comment by Ylianst** [comment]
Oh, your asking about the agent tag... I will add it.

**Comment by tiagogbarbosa** [comment]
Yes.. Sorry for not specify

![image](https://user-images.githubusercontent.com/8936001/167043708-52c43f66-1007-4023-8c53-23b81cd832d6.png)
![image](https://user-images.githubusercontent.com/8936001/167043924-4a663298-c242-4315-9b08-799aad8f4d91.png)

With console.log the agent tag return, but not on regular output
Sorry I don't know js enough to "fix" this :/

**Comment by tiagogbarbosa** [comment]
Got it working, but waiting for your better fix :)
Ty

**Comment by tiagogbarbosa** [comment]
![image](https://user-images.githubusercontent.com/8936001/167044163-c4f68c61-590b-4110-9379-fe786f5948e8.png)
![image](https://user-images.githubusercontent.com/8936001/167044191-c922c209-0a5c-4f18-9fce-25f030a5c9b8.png)

**Comment by Ylianst** [comment]
Just checked it a fix for this. I see you have the same. The update will be in MeshCentral v1.0.18, but you can just get the latest [meshctrl.js](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshctrl.js) here.

I see you can code a little. Please don't hesitate to propose improvements!

![image](https://user-images.githubusercontent.com/1319013/167044804-1874b06f-fd7d-46de-903f-6c917c9389c3.png)

**Comment by tiagogbarbosa** [comment]
Ty! Just a little thing, you forgot the "console.log(node)" without comment

**Comment by Ylianst** [comment]
Doh! Thanks! Just removed it.
