### ISSUE TITLE
Feature Request: List the 2 latest versions of the server to upgrade to 

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#3936]
Sometimes I wish I could choose to update to the second to last version as a precaution. Right now the only options available are the stable and current release.  I prefer to wait a little when something new comes up just to make sure I avoid the bleeding edge, and right now I have no option but to upgrade to the latest regardless of the time frame it was released 

Also, there is no formal change log listed in the interface, could we at least a link in the upgrade dialog box to the github commits? 

https://github.com/Ylianst/MeshCentral/commits/master

**Comment by si458** [comment]
if you have set it up with `npm install meshcentral` you can just stop meshcentral then install a certain version with `npm install meshcentral@1.1.10` for example as the latest is `1.1.11` at the moment

**Comment by rodrigolzd** [comment]
I dont think this is completed at all. thee is no such option in the webinterface. i have not used the command line to update meshcentral at all I think. 

Also the change log issue was not addressed here at the closing remarks.

**Comment by si458** [comment]
you can get changelog information from here - https://github.com/Ylianst/MeshCentral/releases
