### ISSUE TITLE
Agents stop showing active and i have to re-install agent to reconnect them

### ISSUE THREAD

**Issue by thrimurthula** [Ylianst/MeshCentral#3937]
Hi
i have installed meshcentral agent on several computers in a group and they start working for a while and then stop showing as active. I then i have to use teamviewer or go to onsite physically and re-install the agent from downloads folder which activates it again.
why does it do this and how to make it permanent active agent
![image](https://user-images.githubusercontent.com/101698466/166695012-b4be79e8-249d-4f4f-89d0-c80c64945c68.png)

**Comment by rodrigolzd** [comment]
Do you have an antivirus active? have you added meshagent to the whitelist?

**Comment by PathfinderNetworks** [comment]
Like rodrigolzd mentioned, this is likely the result of the antivirus on the computer detecting MeshAgent.exe as a virus and removing it (or just removing the MeshAgent Windows service).

**Comment by thrimurthula** [comment]
thanks guys i will look into it
Kind Regards,
Santosh

**Comment by Ylianst** [comment]
@rodrigolzd and @PathfinderNetworks answers make sense to me. If you are doing remote support and don't need a background agent, you can take a look at MeshCentral Assistant.
