### ISSUE TITLE
Feature Request: Resource Manager

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#394]
Hi Ylianst,
Can you develop a resource manager like below?
What are th usefull functions. 
1- I can stop or start service. 
2- I can kill the task
3- I can see the resources (cpu, memory, disk etc.)
If you can imagine other functions it will be great.
Thanks

![resource_manager](https://user-images.githubusercontent.com/39443706/62220909-7e40ac00-b3b9-11e9-9d8a-4d203dbf4bbd.JPG)

**Comment by Ylianst** [comment]
Good request. Bryan added support in the upcoming MeshAgent to pull a lot of this information. It's then going to be my job to display it all.

**Comment by theredkoala21** [comment]
+CPU usage if possible 😁

**Comment by Ylianst** [comment]
FYI. Just published MeshCentral v0.3.8-y with a new "Services" tab in the Remote Desktop "Tools". This is along side the existing processes tab and you can click on a service to start/stop it. You can already kill a process in the desktop tools.

![MC2-Services](https://user-images.githubusercontent.com/1319013/62256248-68c98300-b3b5-11e9-99c3-dd28bfe8d059.png)

**Comment by PathfinderNetworks** [comment]
This new service start/stop feature is hugely helpful!

**Comment by Ylianst** [comment]
Thanks. More coming, but I am glad this is getting some appreciation & usage.

**Comment by johnnyq** [comment]
This feature would be fantastic +1

**Comment by openmoto** [comment]
Could you possibly also add Startup Type on the existing services tab?
Being able to filter by startup type or view only specific startup type would be great.
Currently, you're unable to tell which auto start services are stopped.

**Comment by OutbackMatt** [comment]
To add to this existing feature request

If the tools window could side by side with a desktop that doesn't reach the edge of the display window would be grerat.

If the processes could show which user is running them would be awesome please (Windows processes on a server with multiple users logged on)

**Comment by si458** [comment]
services view with stop/start/restart feature is already working
process list with kill ability and showing which user is already working
resource view is possible by going to take details tab and then clicking the graph icon and wait for a seconds
