### ISSUE TITLE
Question: RDP new session 

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#3941]
Based on the blog and I quote" The most important difference is that an RDP connection creates a new desktop session on the remote computer instead of taking control of an existing session.". Does it mean that when a connection through RDP Connect tab is establish, both the local and the remote user can work together without interferring each other? Thanks.

**Comment by PathfinderNetworks** [comment]
I would think that is only true of Server OS's.  Desktop OS's, by design, only allow one desktop session at a time (be that a local login or via RDP).  Granted, there are third party 'hacks' and apps to get around that limitation on desktop OSs.
