### ISSUE TITLE
WebRDP- Button not showing in 32bit Mesh agent installed PC's

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#3942]
Dear Ylian,

The new webRDP button not showing for 32bit agents.

![image](https://user-images.githubusercontent.com/80849522/167074901-169827e6-bc53-4e2d-9f76-d666331575b4.png)

For 64bit Meshagent installed PC's its showing.

![image](https://user-images.githubusercontent.com/80849522/167075008-c21bc4b4-f562-40da-867b-5863d3b0f332.png)

**Comment by Ylianst** [comment]
Thanks for reporting this. Working on this now, should be an easy fix.

**Comment by Ylianst** [comment]
Fixed it. Will be in v1.0.19.

**Comment by Mfinadmin** [comment]
Thanks @Ylianst for your quick fix.
