### ISSUE TITLE
android  Server Pairing Link

### ISSUE THREAD

**Issue by Marlonsmart** [Ylianst/MeshCentral#3944]
Hi, I did not find a Mobile device QR code when adding android Mobile phone agent in version 1.0.18. When I select Manual Server Setup option on the Mobile terminal, it prompts me to input Server Pairing Link. May I ask how to fill in this Link?

**Comment by Ylianst** [comment]
Click "Add Agent" on your device group and select "Mobile Device". You will only see the "Mobile Device" option if your server is in WAN or Hybrid mode. The Android agent does not support LAN mode.

![image](https://user-images.githubusercontent.com/1319013/167169157-28ce83fc-4691-47b9-b2ad-bb69242a68c8.png)

**Comment by Marlonsmart** [comment]
Thank you very much for your reply. I will try to run it in WAN.



***@***.***
 
From: Ylian Saint-Hilaire
Date: 2022-05-06 23:58
To: Ylianst/MeshCentral
CC: Marlonsmart; Author
Subject: Re: [Ylianst/MeshCentral] android Server Pairing Link (Issue #3944)
Click "Add Agent" on your device group and select "Mobile Device". You will only see the "Mobile Device" option if your server is in WAN or Hybrid mode. The Android agent does not support LAN mode.
