### ISSUE TITLE
RDP access control

### ISSUE THREAD

**Issue by Mfinadmin** [Ylianst/MeshCentral#3946]
Dear Ylian,

We have few users those having the Remote view only permitted in Mesh central. 

But those users are able to control the system through New RDP session ( Mouse click working fine, Typing restricted ).

Is it possible to restrict the RDP access for selected users based on the access permissions defined in Mesh central.

**Comment by Ylianst** [comment]
Oh! Good point. I will add that tomorrow. That is a security issue for sure.

**Comment by Ylianst** [comment]
I fixed this, it's in MeshCentral v1.0.19 that I just published. Let me know if it works. The "View Only" mode is enforced on the server, so, can't be bypassed even if you change the web page.

**Comment by Mfinadmin** [comment]
@Ylianst 
Thanks its working fine.
