### ISSUE TITLE
minor improvement: list view of relay group devices could show more details in the columns

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#3949]
Hi,
I like this new relay group feature of mesh central.

I have noticed when in list view, that "local" and "realyed" devices do not have entries for "Links", "Address", "Connectivity".

"Agent Type" is indicated by the (Windows / Linux / macOS) selected profile.
I thought the "Address" would be the "Hostname" and "Connectivity" would be "local" or the Agent used.

I'd assume that "Links" would be the default set (Windows / Linux / macOS)
Can the "Links" be customised within the user interface?

**Comment by Ylianst** [comment]
Just did a bunch of fixed for this. Will be in MeshCentral v1.0.23. Let me know if you like it.

**Comment by b8two** [comment]
Looks good.
