### ISSUE TITLE
Increase ssh timeout

### ISSUE THREAD

**Issue by gaalos** [Ylianst/MeshCentral#3953]
Hi when i'm using ssh. I got timeout when i'm idle, the ssh session is closed (not from server) 
Where is the parameters for increase terminal time out ?

Best regards

**Comment by Ylianst** [comment]
Idle for how long? With the latest versions of MeshCentral, try adding this to the "settings" section of the config.json:

```
"agentpong": 120
```

This will send data thru the SSH session at a minimum every 2 minutes (120 seconds). You can lower this value if needed. Let me know if that works.

**Comment by gaalos** [comment]
Hi, 
The session is killed in 5 min idle 
I set agentpong to 30 and still not working.
I'm behind nginx reverse proxy and i found 
proxy_send_timeout 330s
proxy_read_timeout 330s
330s looks like 5 min 
I increase it i'll try it.

**Comment by Ylianst** [comment]
Oh nice! What did you increase it to?

In very old document, I would recommand this:

```
proxy_send_timeout 999999s
proxy_read_timeout 999999s
```

Turns out, this is bad and NGINX will leak memory. So, keep the time somewhat reasonable.
