### ISSUE TITLE
Missing auth syslog info

### ISSUE THREAD

**Issue by optikkore** [Ylianst/MeshCentral#3954]
Is there anyway to get this string

meshcentral-auth[13087]: Accepted password for $USER$ from $IP_ADDRESS$ port $PORT$

 pushed to the tcp syslog as well currently only get 

meshcentral-auth[13087]: Account login.

**Comment by Ylianst** [comment]
Take a look at #1157 and let me know if that works for you.

**Comment by optikkore** [comment]
I have tried everything from that post short of debugging the js, one note is that it creates the authlog file but it is empty and no matter what I try I just do not get that message to go the tcpsyslog

**Comment by optikkore** [comment]
@Ylianst  I don't know if its a hack or a fix but I changed[ line 1274 of webserver.js](https://github.com/Ylianst/MeshCentral/blob/master/webserver.js#L1274)  to

`const loginEvent = { etype: 'user', userid: user._id, username: user.name, account: obj.CloneSafeUser(user), action: 'login', msgid: 107, msgArgs: [req.clientIp, ua.browserStr, ua.osStr], msg: 'Acount login ' + user.name + ' from ' + req.clientIp + ' port ' + req.connection.remotePort, domain: domain.id, ip: req.clientIp, userAgent: req.headers['user-agent'] };`

and I now get the details with the message to the tcpsyslog

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Indeed, I just made a fix for this. Will be in v1.0.20 shortly.

**Comment by optikkore** [comment]
@Ylianst Thank you for your hard work
