### ISSUE TITLE
Google SMTP Relay

### ISSUE THREAD

**Issue by optikkore** [Ylianst/MeshCentral#3955]
please add support to pass name from smtp settings to nodemailer for google-smtp relay with no authentication to work

```
 "smtp": {
    "name": "mydomain.com",
    "host": "smtp-relay.gmail.com",
    "port": 587,
    "verifyemail":  false,
    "from": "nobody@mydomain.com",
    "_user": "",
    "_pass": "",
    "tls": false,
    "tlsstrict": false,
    "tlscertcheck": false
  }
```

had to modify meshmail.js line 47 to

```
var options = {name: obj.config.smtp.name, host: obj.config.smtp.host, secure: (obj.config.smtp.tls == true), tls: {} };
```

in order for google's smtp relay to play nice or maybe we are doing something wrong

**Comment by rapi3** [comment]
Will be nice to support any smtp relays, forwarder... I have a Postfix forwarder installed on firewall that forward all emails to Postfix server and Meshcentral it is unable to start if I try to config to use this... SMTP Port 25, TLS/SSL, no authentication...

**Comment by Ylianst** [comment]
Good request. I just added "name" support like you did and also added it to the config.json schema. Will be in v1.0.20. Let me know if that works.

**Comment by optikkore** [comment]
@Ylianst Thank you again for all your hard work
