### ISSUE TITLE
Possible bug in meshctrl.js using --loginkey [hex]

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#3956]
Hi,

In master branch meshctrl.js file line number 1132 has below line of code.

> if (ckey != 80) { ckey = null; loginCookie = args.loginkey; }

It suppose to be below one. 

> if (ckey.length != 80) { ckey = null; loginCookie = args.loginkey; }

In my local, I have faced this issue in older version, however in master version also I can see similar code. Is it a bug? If so, I hope this post helps to fix. Please correct me if my understanding is wrong.

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
That is most definitely a bug! Thank you for reporting that. Your fix is correct and it's going to be in v1.0.20 that will be published shortly.
