### ISSUE TITLE
Uninvited hosts showing in Mesh Central

### ISSUE THREAD

**Issue by circlecomputers** [Ylianst/MeshCentral#3957]
Hi

This morning I noted 4 new hosts in one of my Mesh Central groups that I have not installed. The source IPs original from Google Cloud Platform and 2 locations in the US.

As a precaution I have locked down access to to the Mesh Central UI to a single source IP and would not like to dig a little deeper into how they were created as no Agent Installs should be open on the web and they should have expired even if they were retrieved from a client PC.

I'm concerned as I am aware that there have been some security issues with NPM recently and that may be a source of problems.

I think my first step is to look at the point at which the rogue device first made contact with Mesh Central and then look forward at the flow of requests. Can you point me toward relevant logs.

I'd also be interested in implementing something like CrowdSec into the deployment to limit access from known rogue IP addresses. Any experience from the group on this from would be welcome.

Thanks

Gary

**Comment by krayon007** [comment]
I remember a while ago someone mentioned that some AV software will upload the binary and try to run it in a sandbox to analyze behavior. These instances could show up on your server.

**Comment by circlecomputers** [comment]
Hi, That's an interesting idea. I upgraded to the latest version so this could be the case as we have a couple of hosts on the affected group that have hosts that use sandboxing AV.

I'll see if I can reproduce.

**Comment by Ylianst** [comment]
This has been reporting many times before. AV vendors will run your agent executable in a VM to see what it does. Since your server information is embedded into the agent executable, this happen. It's normal, nothing much we can do about it. The AV VM will connect for a few minutes and disconnect.

**Comment by haxmachine** [comment]
I have seen this happen before and I believe Ylianst is correct AV vendors cause this.
But is there a way to add and expiry to the agent installation so it no longer valid after a period or after installation the installer is deleted?
Just an idea :)

**Comment by circlecomputers** [comment]
I believe the installation packages have a lifetime so in theory the risk is short lived. 

This also, probably, answers why my installation kit indicated it was no longer valid the fist time, it had been uploaded an run. Second time it was known and was allowed to run.

An option where new devices go into a pending state and required approval from the MeshCentral UI would be a welcome feature.
