### ISSUE TITLE
Node showing connected long after being offline

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#3959]
Hey Yilan,

I've seen this sporadically in the past and my fix has been to just restart the meshcentral service.  However, I did some controlled testing and confirmed an endpoint that becomes network isolated (I shut the switch port down), remains online for approx 5+ minutes (I'm seeing around 15-16 minutes) before showing as disconnected ('last seen' in gui).

My current settings related to ping/ping/idle are:
```
    "browserPing": 30,
    "browserPong": 30,
    "agentPing": 30,
    "agentPong": 30,
    "agentIdleTimeout": 60,
```

Runing latest version 1.0.19.  I've read the comments at 
https://www.reddit.com/r/MeshCentral/comments/p5dnsk/agent_showing_powered_despite_powered_off_for/
and tried refreshing the browser during the isolation but it continues to report connected.

Event log for my testing/isolation is:
```
- 2022-05-11 00:21:06 - shut port
- 2022-05-11 00:22:05 - still connected
- 2022-05-11 00:35:45 - still connected
- 2022-05-11 00:37:00 - offline
```

When the node changes to disconnected, Meshcentral logs the syslog event:

```json
May 11 00:36:49 meshcentral meshcentral-json[99161]:
  {
    "action": "nodeconnect",
    "meshid": "mesh//XXX",
    "nodeid": "node//YYY",
    "domain": "",
    "conn": 0,
    "pwr": 0,
    "nolog": 1,
    "nopeers": 1
  }
```

And the nodes last seen changes to
```
Last seen: 5/11/2022, 12:36:54 AM
```

Can this offline detection be improved?  Happy to do further testing, I can easily reproduce.

Thanks!

**Comment by cgb** [comment]
Hey Yilan, let me know if you need any further testing/collection, my reproduce case is a test machine nearby so I can do it whenever..

**Comment by cgb** [comment]
Hey @Ylianst , any ideas what might be going on here?  Anything in the server configuration we can tweak?

**Comment by si458** [comment]
1.0.19 is an old version, the latest is 1.0.43 (due today)
please can you try updating the server and removing
```
    "browserPing": 30,
    "browserPong": 30,
    "agentPing": 30,
    "agentPong": 30,
    "agentIdleTimeout": 60,
``` 
from your `config.json` and see how it behaves?

**Comment by silversword411** [comment]
Staying online for 5mins, then going offline sounds like you might have dupe agents hitting the server as well, do you clone configs across machines?

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.21 and use node 18 or above,
if issues persist, please reply back
