### ISSUE TITLE
Separate checkbox for saving SSH key password

### ISSUE THREAD

**Issue by poiNt3D** [Ylianst/MeshCentral#3960]
Hello. 
SSH terminal feature is very convenient, but i noticed that when you choose to save credentials, they are stored as a plain text within meshcentral db. 
Maybe i am overreacting, but this tingles my paranoia. 
If you don't save the creds, it is a tedious task to upload a SSH key every time.
Would be great if there was an option to save encrypted ssh key, but the encryption password would be asked upon connecting.
Or some other solution possible?

**Comment by Ylianst** [comment]
Two things on this, first, backup your database and add this line to the settings section of the config.json:

```
"dbRecordsEncryptKey": "mySecret"
```

This will selectively encrypt portions of the database with the secret you specify (it hashes the secret string and uses the hash as a key). I need to check if the SSH/RDP secret is part of the encryption.

Second, if your talking about a SSH session that uses certificate authentication, your suggestion is a good one. I will work on that now.

**Comment by Ylianst** [comment]
I just added database record encryption for SSH/RDP credentials. Starting with the next version, if you look in the database, you should see something like this:

```
{
  "type": "node",
  "_id": "node//izGm2Ja9RJwXIO6k6qLCNdKC$DNsqSiscW5qZNRz6l2TNM@PB6TB$2$4RofA2Jnw",
  "meshid": "mesh//1QzgoRSJkomJL826t9ci1znuRuxg5GePSyK1b8xhrsLHbty$KHJkNIZXsYzG2qLQ",
  "mtype": 3,
  "icon": 1,
  "name": "Router",
  "host": "192.168.2.1",
  "domain": "",
  "agent": {
    "id": 6,
    "caps": 0
  },
  "_CRYPT": "KLk7+YzEX4hoRhbv3cB3BbbKO5l+qGr5R6XXVJnaxg1lVh9XrsalRdYbKJRFsL4ecYTItZxucCtdEH5E"
}
```

The "_CRYPT" part encrypts the sensitive data. In this case, the RDP and SSH credentials. I already had support for this for the Intel AMT credentials.

**Comment by Ylianst** [comment]
Working on remembering the certificate but not the password now.

**Comment by Ylianst** [comment]
Took all day to do this, but it's checked in. Will be with v1.0.20.

![MC2-SSH-Key-Storage](https://user-images.githubusercontent.com/1319013/167755717-bc1e06f7-4dcb-42eb-8540-bc4c68ae7e0c.png)

**Comment by poiNt3D** [comment]
You are a rocket!
