### ISSUE TITLE
"Type" button does not work correctly with remote desktop guest sharing

### ISSUE THREAD

**Issue by Jayddee23** [Ylianst/MeshCentral#3961]
Hello,
My colleagues are "full administrators" like me but they can't do certain things.
For example, after creating a user for a provider, they go to his account in "my users" to add a device (their server) but the combos of group and device choices are empty.
Do you have an idea? Is this a bug?

Another thing, when I connect to a device via a shared link, when I want to send a url, multiline text or accents via the "type" button all special characters are replaced or removed.
example : 
":" becomes "£"
"/" becomes ":"
line breaks become "&"
accented characters are removed.
While in direct without going through the share no problem.

Thanks in advance,
Sincerely,

**Comment by Ylianst** [comment]
Hi. These should be entered as separate issues. For the first issue, your not giving me sufficient information to replicate the issue. If you can open a new issue and provide screen shots, that would be great. I don't want to start guessing what is going on.

For the second one, I will look at this now.

**Comment by Ylianst** [comment]
Fixed the "type" button on guest sharing sessions, will be in MeshCentral v1.0.21.

**Comment by Jayddee23** [comment]
thank you for your feedback and for the correction in v1.0.21.
I will make you screenshots for the other problem and open a new topic
