### ISSUE TITLE
Feature Request: Custom MeshCentral Router Applications

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#3964]
Another "in my dreams" feature request, written here before I forget.

It would be very useful in a lot of cases to be able specify custom applications in MeshCentral Router that can work like the existing ones (PuTTY, WinSCP etc.) already do.

The idea would be to provide a protocol name and a constructed path to an executable or file that may include the local port and loopback address as variables (I use $P and $L in the below example). This could then be launched with the "Open" button in MeshCentral Router or automatically when a Router link specifying that protocol is clicked.

For example, you could have a protocol called "mobassh" which launches an SSH session in MobaXTerm. A constructed path might look like this:

```
C:\Program Files (x86)\Mobatek\MobaXterm\MobaXterm.exe -exec "ssh -P $P $L"
```

Ideally, the path could be any file and the variables would be optional. This way, it could also work with scripts. The burden would be on the user to make sure the constructed path is correct. If the MeshCentral Router program gets a link that refers to a protocol it has no custom entry for, it should show an error such as "Protocol not defined." or just ignore it. Configuration for these custom entries would be with the other settings in the registry at HKCU\SOFTWARE\Open Source\MeshCentral Router so that there is a way to automatically add them. A way to do this via the GUI (probably in the settings window) would make the feature easier to use for most users, for example those who just want to use alternate SSH or RDP apps or add a protocol/app fitting only their person use case.

(On a side note, I really need to write a tutorial on how to wrap MeshCentral Router inside an NSIS installer that includes branding, settings, etc. Would that be useful? If so, where would be the best place to put it? I see there's a Wiki tab above...)

**Comment by Ylianst** [comment]
Working on this now :)

**Comment by Ylianst** [comment]
Ok, this will be in MeshCentral v1.0.21. Let me know if it works.

![MC2-RouterCustomApps1](https://user-images.githubusercontent.com/1319013/168188192-e11467cd-d1a2-4fb8-8a1c-3212e60033e1.png)

![MC2-RouterCustomApps2](https://user-images.githubusercontent.com/1319013/168188204-c4067a03-35d5-4396-a148-d3a1d5aa3498.png)

![MC2-RouterCustomApps3](https://user-images.githubusercontent.com/1319013/168188206-e2078fb2-75ee-4e98-8837-60635f4a7221.png)

**Comment by Ylianst** [comment]
v1.0.21 is out.

**Comment by MatinatorX** [comment]
Thank you so much for your this and your hard work in general. Given the mountain of requests I did not expect any action on this for a long time if at all. I'm going to test it out immediately and report back. This is going to save a lot of users an incredible amount of time.

You really need to tell us what model of keyboard you use that can survive such immense productivity without melting into a puddle of goo.

**Comment by MatinatorX** [comment]
Alright, so I just tested it out and when I point it to an executable, it does indeed launch it as expected. It also works when I point it to a another type of file by manually editing the path, but this can't be done through the file selector as it's confined to only show executables for some reason.

What I can't seem to do is get any application arguments at all to work. This is just regular application arguments - I haven't tried %L or %P yet.  I have tried to format them both as a command line argument (which tests fine in cmd) and as a shortcut with arguments (which tests fine with an actual shortcut) but whenever arguments are present, the app is not launched. I tested it with apps that will throw an error if a bad command is passed, and it doesn't get that far.

Not sure if it's something I'm doing wrong or if a special format is needed. I didn't see any examples with arguments in the screenshots above.

**Comment by Ylianst** [comment]
%N is a great idea. I also just realized that if there is a space in the path/executable name, MeshCentral Router will mess that up. I need to take another go at this.

Thanks for the comment on the keyboard, I guess I must have soft programmer hands not to destroy it :)

**Comment by Ylianst** [comment]
Just pushed a new signed [MeshCentral Router in Git here](https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe). Can you download it a give it a try? The file executable and arguments are now separated any you opt to select any file type in the file path selector.

**Comment by MatinatorX** [comment]
Just tested it, works awesome now! Thanks so much!
