### ISSUE TITLE
problem of rights by group

### ISSUE THREAD

**Issue by Jayddee23** [Ylianst/MeshCentral#3966]
Hello,
As agreed after more research on my side I found the cause of my problem and made you screenshots.
First of all, my user "test.mesh" is full administrator and is in the "admins" group.
![image](https://user-images.githubusercontent.com/101196731/168005890-6c875d46-7623-4959-b3f8-967d5ebb08e5.png)

This group "admins" has full rights on the device group "CH".
![image](https://user-images.githubusercontent.com/101196731/168006121-c4a107bc-c29d-4012-b82a-d214f59f73e4.png)

It therefore correctly sees the devices in the "CH" group
![image](https://user-images.githubusercontent.com/101196731/168006249-0fae660e-3267-42d7-a9a0-462cebeeb1b8.png)

If I go to a user (1) to add a device (2) I don't see any devices (3) even though I am part of the "admins" group which has full rights on "CH".
![image](https://user-images.githubusercontent.com/101196731/168006444-43a6a383-25ee-4c99-8d1a-434b99013335.png)

On the other hand on I add directly the user on my group "CH" without passing by a group, I also see them to add them to my users
![image](https://user-images.githubusercontent.com/101196731/168006953-beb98b4e-24f2-437c-a6a1-df070624b9d1.png)
![image](https://user-images.githubusercontent.com/101196731/168006988-25dafe15-dff8-4c76-8167-d9dd366dc175.png)

good day, good luck.
Sincerely,

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20 then try again, if issue still happens please reply back
