### ISSUE TITLE
Feature Request:  Web-SSH/SFTP Integrated into the Terminal/Files Tab for Linux Agents

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3969]
So it would be really nice to be able to access the Web-SSH feature from the "Terminal" tab on linux agents just like the recent integration for Web-RDP. We frequently have to use the Web-SSH tool because the console terminal is protected on some linux virtualization platforms we use. The normal terminal "connect" button does not work on these machines because of this. Being able to start an ssh session right from the terminal tab would be great!

**Comment by Ylianst** [comment]
Just published v1.0.22 with this feature included. Working on graphics now.

**Comment by Ylianst** [comment]
Here is what is looks like, let me know if you see any issues.

![MC2-SSH-SFTP-Integration-Desktop](https://user-images.githubusercontent.com/1319013/168393454-c9664c49-5163-47df-9a42-8cc4d1d24ab5.png)

![MC2-SSH-SFTP-Integration-Mobile](https://user-images.githubusercontent.com/1319013/168393462-f385bba9-40ce-4fcf-8658-f7658fc3cb8c.png)

**Comment by LPJon** [comment]
@Ylianst Initial Test works perfectly. Will close this request and if I run into anything I will create a new issue. This is GREAT! Thank you for your hard work. 

I did notice an artifact in the SFTP window. Not sure if it's related to your integration yet or not. See the image below
<img width="305" alt="Untitled" src="https://user-images.githubusercontent.com/46533576/168393986-83c5e852-d163-4d1a-b716-6c16913692c0.png">
