### ISSUE TITLE
Update Doc: systemd unit file & port permissions capability

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#397]
When Linux kernel gets upgraded you can loose the port permissions. Then when starting the service MeshCentral complains about port 80 not available.
In documentation stated the commands:
```
whereis node
node: /home/ec2-user/.nvm/versions/node/v8.11.3/bin/node
sudo setcap cap_net_bind_service=+ep /home/ec2-user/.nvm/versions/node/v8.11.3/bin/node
```
This only works for current kernel.

When using systemd you can add the permission capability into the unit file:
```
[Unit]
Description=MeshCentral Server

[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /home/default/node_modules/meshcentral WorkingDirectory=/home/
Environment=NODE_ENV=production
User=default
Group=default
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
Capabilities=cap_net_bind_service+ep
SecureBits=keep-caps

[Install]
WantedBy=multi-user.target
```
Where **default** should be replaced with the account MeshCentral is going to run.

**Comment by Ylianst** [comment]
Oh! Nice! Fixing the documents now!!!

**Comment by Ylianst** [comment]
[MeshCentral Install Guide v0.0.8](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.8.pdf) is out with your fix. Let me know if this works.

**Comment by hunter-nl** [comment]
Looks good! 👍

**Comment by hunter-nl** [comment]
Due recent systemd and kernel updates in CentOS 7 (and most likely also in other distributions), the capabilities permissions does not work anymore.

Replace the lines
```
# Set port permissions capability
Capabilities=cap_net_bind_service+ep
SecureBits=keep-caps
```
with
```
# Set port permissions capability
SecureBits=keep-caps
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
```
to fix this again.

**Comment by SomeBoredDude** [comment]
> ```
> # Set port permissions capability
> SecureBits=keep-caps
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> AmbientCapabilities=CAP_NET_BIND_SERVICE
> ```

I can confirm this works for CentOS 8

**Comment by palmersu** [comment]
I also needed to add those lines to the service file.  I am on Ubuntu 18.04.3

It was exiting with code status=213/SECUREBITS
and I was getting the errors:
meshcentral.service: Failed to set process secure bits: Operation not permitted
meshcentral.service: Failed at step SECUREBITS spawning /usr/bin/node: Operation not permitted

Added these (as the others have mentioned):
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
