### ISSUE TITLE
Not working correctly on long custom domain name (not use DNS)

### ISSUE THREAD

**Issue by generalworksinc** [Ylianst/MeshCentral#3973]
Hi.

I've found this great project, and I'm just starting use multi domains.

I've three domains available and have tested them.

・default domain ""
・short domain "a-b"
・long domain  "a39c9148-9b9b-4a83-9e72-5767d99309440a7acffe-2546-4cc4-8ce2-ad0cefa56c32"

(site urls are 
 "http://ec2-xx-xxx-xxx-xx.ap-northeast-1.compute.amazonaws.com/" ,
 "http://ec2-xx-xxx-xxx-xx.ap-northeast-1.compute.amazonaws.com/a-b" ,
  "http://ec2-xx-xxx-xxx-xx.ap-northeast-1.compute.amazonaws.com/a39c9148-9b9b-4a83-9e72-5767d99309440a7acffe-2546-4cc4-8ce2-ad0cefa56c32" . )

Everything is fine on default, and short domain site, but some features do not work correctly on long domain site.

1. "Delete Agent ->  Cannot delete on long domain site. (when press the button, nothing happens.. added agent correctry.)
2. "Create invite link" -> but on custom domain site, not display link and any log.
↓ not display "invite link".
![invite_2](https://user-images.githubusercontent.com/12643025/168224374-c26d288d-7e09-426f-ad9c-45ca68b93922.JPG)

↓when running correct 
![invite_1](https://user-images.githubusercontent.com/12643025/168224999-f70dc3e6-0335-4a65-9173-e92e2eb16b57.JPG)

there is no javascript console error, and network error( I can't find on chrome by dev tool).
There may be more, but I'll just report what I find.

Is there a limit length of domain name?

Detailed settings are as follows. 

・Nginx, and meshCentral server is installed same server.
    Certificates are created by OpenSSL.

・meshcentral-data/config.json 
```

  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443/"
    },
    "a-b": {
      "certUrl": "https://127.0.0.1:443/"
    }
    "a39c9148-9b9b-4a83-9e72-5767d99309440a7acffe-2546-4cc4-8ce2-ad0cefa56c32": {
      "certUrl": "https://127.0.0.1:443/"
    }
  }
}
```

**Comment by Ylianst** [comment]
This is not something I expected. There is a limit to the domain name, it's 64 characters. I just added a check for this. I also noticed that at 64 characters long, some places in the code don't check the correct length for some data, I just fixed that. Will be in MeshCentral v1.0.22.

**Comment by generalworksinc** [comment]
@Ylianst 
Thank you for your quick response! I'll check on fixed version.
