### ISSUE TITLE
Issue With "Files" Tab standard connect button. Shows connected but no file list

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#3975]
This issue appears between MeshCentral Versions 1.0.20 (Working) to 1.0.22 (Not Working). The new SFTP integration works perfectly however now the standard connect does not.

This Linux box is based on CentOS  Version 8.2 LTS. It did previously work so it should be a code issue. See Picture Below:
<img width="568" alt="Untitled2" src="https://user-images.githubusercontent.com/46533576/168395084-9edfc019-1582-471c-aa82-065493512fab.png">

**Comment by LPJon** [comment]
@Ylianst This seems to be related specifically to the Linux virtualizaton platform (XCP-ng) I  mentioned earlier. The new integration allows for a work file and ssh terminal so I'm going to close this issue in favor of this is OS specific and not to MeshCentral. 

Other tested linux OS's are working fine.

**Comment by Ylianst** [comment]
Can you open the browser's console and send back any errors you see?

**Comment by Ylianst** [comment]
Oh ok. Thanks for reporting.

**Comment by LPJon** [comment]
No problem....even more strange is that is just began functioning correctly any way.

**Comment by LPJon** [comment]
@Ylianst  Ok...I identified this issue. It is related to the artifact I found in issue #3969 . That file was name with an unusual name "0???" and this caused that artifact.  After removing that file there was no longer an issue. Image below shows then error in the browser console: 
<img width="1828" alt="Untitled3" src="https://user-images.githubusercontent.com/46533576/168398258-69a82cae-6729-43fc-9689-a0e85b1db27e.png">

**Comment by Ylianst** [comment]
I need to make this issue happen on my computers. Could would do "ls" in Linux and send a screen shot of the odd file. I want to replicate that file name on my servers. Thanks.

**Comment by LPJon** [comment]
@Ylianst I already gave you the exact file name. it's `0???` The file was a zero length file so no data was in it. and It was in the `/` directory (ROOT)

**Comment by Ylianst** [comment]
Ok, If that is exactly what show up when you do `ls` I am going to have to try other things. I need to know the exact special character numbers that are in the file name. A literal file names "0???" will work fine (image below), the issue here is that there are non-visible characters in that file name causing the problem, I need to know the exact values of the characters.

![image](https://user-images.githubusercontent.com/1319013/168450812-eb47e35c-c98c-4c6a-a5a2-5e4e2a0efcfc.png)

**Comment by LPJon** [comment]
I see.....Well in that case this might just be an edge case then. I didn't create that file and I'm not sure what did. To add to the problem, I have already deleted it without moving it instead. I just know that was exactly what I saw, but if they were special characters that `ls` couldn't read I have no Idea what they were. Any idea what characters that `ls` would display that with?

**Comment by LPJon** [comment]
Ok....I'm now closing this. Sorry for making you chase ghosts. 

This is directly related to the filesystem and permissions on certain files and certain characters that may be in the file names. This is not a bug. This is a file that was in correctly created and could not be searched or written to and it caused this error.

Still it might be worth having the directory listing overlook such files or folders with a timeout. Otherwise no file and directory list is presented. To do that I need to be able to help you reproduce this and I don't know how to do that. 

For anyone that runs into this issue in the future....just delete or rename the offending file or folder. That should get this working again.
