### ISSUE TITLE
Invite Codes

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#3978]
Hi,

I have enabled the "LoginKey" option. When activating "agentInviteCodes" option, a wrong link is displayed:
`https://mc.mydomain.de/invite`

Must be:
`https://mc.mydomain.de/invite?key=MyKey22`

**Comment by Ylianst** [comment]
Ok, looking at this one now.

**Comment by Ylianst** [comment]
Fixed, will be in MeshCentral v1.0.23.

![image](https://user-images.githubusercontent.com/1319013/168702655-7b1cf2dc-db00-4776-bc01-a17beec9b765.png)

**Comment by johann8** [comment]
Hi Ylianst,

Thank you very match. It works now!!!
