### ISSUE TITLE
Existing LetsEncrypt: how to reuse certs properly?

### ISSUE THREAD

**Issue by greenais** [Ylianst/MeshCentral#3980]
I installed  MeshCentral on machine with existing Lets Encrypt setup, which means that certificates successfully renew and are stored in corresponding /etc/letsencrypt directory, there are:
 _cert.pem  chain.pem  fullchain.pem  privkey.pem_
As it was advised somewhere in the Net (I can't remember exact place, but it definitely was related to MeshCentral) I
 
1) replaced autogenerated certs in /meshcentral-data as follows:
_cert.pem_  =>  webserver-cert-public.crt
_privkey.pem_  =>  webserver-cert-private.key

2) edited "cert" and "WANonly" properties in config.json accordingly

3) after MeshCentral server restart all tested browsers show no invalid TLS connection anymore, everything looks fine + I can see and manage added Windows hosts with agents or Assistants (Linux hosts don't work for me yet).

The question is:
should something be done also to other autogenerated cert files in  /meshcentral-data? 
I mean these:

agentserver-cert-public.crt
agentserver-cert-private.key  
mpsserver-cert-public.crt
mpsserver-cert-private.key
root-cert-private.key
root-cert-public.crt

**Comment by Ylianst** [comment]
Hi. So, you probably know this already but MeshCentral has built-in Let's Encrypt support so that it will automatically get and renew your certificate, this said, your cert replacement works just fine.

For the other certificate, do not change them. The `root-cert` is a private root for your server, it's used to sign the `mpsserver` and `agentserver` certs. The `mpsserver` cert is used to authenticate your server to Intel AMT devices (if you use that feature), more importantly `agentserver` cert is used to authenticate incoming agent connections. If you loose that cert, agent will no longer be able to connect to your server and you will need to re-install all agents.

So, please keep a off-site backup of the `meshcentral-data` folder, these private certificate identify your server in a unique way.

Let me know if that helps.

**Comment by greenais** [comment]
@Ylianst, thank you for the prompt reply!


> Hi. So, you probably know this already but MeshCentral has built-in Let's Encrypt support so that it will automatically get and renew your certificate, this said, your cert replacement works just fine.
>
Yes, I know it, and instrustions are quite comprehensive, but they aim to setup where MeshCentral is first and (probably) only LetsEncrypt consumer. In my case I added MeshCentral to existing setup where LetsEncrypt already serve Apache2 and other primary services, that's why this question is about reusing. 
In my usecase MeshCentral will be occasional solution for family/friends support only and I plan to fire up MeshCentral server rarely (I hope)) and only in need.
 
> For the other certificate, do not change them.
>
Crystal clear, thank you again!
 
Primarily this clarification question was sourced by curl error in meshinstall script generated for "Invite" route for Linux:
curl claimed that cert is wrong and rejected to download agent itself from untrusted source, I had to edit meshinstall script adding --insecure to curl options, otherwise script was stucking in countless retries.

**Comment by Ylianst** [comment]
Oh good. Apologies, it's difficult to know what level of understanding people have about Let's Encrypt and certs. If you are using a cert for many uses, another option is to use a reverse proxy like NGINX and have NGINX perform the TLS and own the cert. In that case, MeshCentral receives non-TLS connections and does not need a TLS cert anymore. [I have a video on this here](https://www.youtube.com/watch?v=YSmiLyKSX2I).

**Comment by greenais** [comment]
Yes, I was considering to use my existing Apache2 server as TLS reverse proxy (as it already is doing this job for my home Nextcloud and other apps) but this part of UserManual confused me:
`If possible, port 443 should be configured with a legitimate trusted certificate and the public part
of the certificate named as “webserver-cert-public.crt” must be placed inside of “meshcentral-
data” folder of the server. When the server is executed in tlsoffload mode, only the public part of
the web certificate is used by the server.`
I mean requirement of 
`must be placed inside of “meshcentral-data”` 
which means that anyway I have to provide some script that will actualize live cert in meshcentral-data after LetsEncrypt update. Am I wrong?  Does mentioned "CertUrl" setting in domains section do that job instead?

_BTW, in UserManual all properties names are capitalized (probably due to autocorrection in Word) - like "AliasPort" when in config.json I see "aliasPort", perhaps it doesn't matter, just in case.._

**Comment by Ylianst** [comment]
If you use this line in the settings section of the config.json:

```
"tlsoffload": true
```

Then, MeshCentral will not perform TLS on port 443 and instead assume that TLS is perform in front of it my a reverse proxy. In that case, no need to configure any TLS cert in MeshCentral... but, as indicated in the video, you need to use "certurl" so that MeshCentral can see what certificate is being used, and you probably want to use:

```
"tlsoffload": "1.2.3.4"
```

Where 1.2.3.4 is the internal IP address of the reverse proxy. It's all explained in the video.

**Comment by greenais** [comment]
For me it was quite a bit hard to recognize text on screens in video so I went through UserManual (which, again, is very detailed, thank you).
Similar to other apps I use with Apache2 as TLS reverse-proxy I created dedicated to MeshCentral site in apache config:

```
<IfModule mod_ssl.c>
	<IfModule mod_proxy.c>
		<VirtualHost *:555>
			ServerName domain.org
			ProxyRequests     Off
			ProxyPreserveHost  On
			<Proxy *>
				AddDefaultCharset off
				Order deny,allow
				Allow from all
			</Proxy>
			ProxyPass / http://localhost:5553/
			ProxyPassReverse / http://localhost:5553/
			ProxyVia         on
			SSLCertificateFile /etc/letsencrypt/live/domain.org/fullchain.pem
			SSLCertificateKeyFile /etc/letsencrypt/live/domain.org/privkey.pem
			Include /etc/letsencrypt/options-ssl-apache.conf
		</VirtualHost>
	</IfModule>
</IfModule>
```

with corresponding settings in  config.json

```
"settings": {
    "cert": "domain.org",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 5553,
    "tlsOffload": "127.0.0.1",
    "aliasPort": 555,
  },
"domains": {
"": {
  "certUrl": "https://127.0.0.1:555/",
  "minify": true,
  "newAccounts": false,
}
```

(both are running on same machine). But when I start  MeshCentral I've got error of loading cert from certUrl:

`Failed to load web certificate at: "https://127.0.0.1:555/", host: "domain.org"`

As well tried to point certUrl to other apache sites ports (definitely working right now as TLS reverse-proxy), which use same sistem-wide LE certificate, but result is the same - "Failed to load web certificate".

"Direct" setup where  MeshCentral  does TLS-job  itself (without tlsOffload) works just fine, so definitely I have backup solution in case we can't find what stops MeshCentral from getting cert from apache, thank you.

**Comment by Ylianst** [comment]
Taking a quick look at this, your settings should work. You may want to try:

```
"certUrl": "https://domain.org:555/",
```

Remember that just about any URL that will get the external cert that agent will also see is ok. In your case, Apache may not be bound to 127.0.0.1. You can test this with a browser, just any URL that works in the browser and gets the cert the agent will see is ok.

**Comment by greenais** [comment]
Finally it worked! 
MeshCentral got cert even from 127.0.0.1. It was my _very stupid_ error - I forgot to add 555 to apache's ports.conf(

I was successfully able to login to web interface but got unexpected:
`Unable to connect web socket,click to reconnect.`

Should I look into headers configuration described for NGINX and convert them to apache directives?
Or the root of this issue is somewhere else?

I promise to contribute by writing apache's howto for TLS offloading once we sort this out. 
And thank you again for your support!

**Comment by greenais** [comment]
I figured out how to deal with sockets under TLS in apache, so everything works now like a charm.
Here is HOWTO for TLS offloading and reusing existing LetsEncrypt certificates with apache:

Assumptions:
- both - apache2 and MeshCentral - servers run on same machine
- yourdomain.org is what you SSL certs were created for
- you don't need  


1) add to /etc/apache2/ports.conf inbound port which you will use for incoming agents/browsers connections (555 in my case)

```
<IfModule ssl_module>
        Listen 0.0.0.0:555
</IfModule>
<IfModule mod_gnutls.c>
        Listen 0.0.0.0:555
</IfModule>

```


2) create in /etc/apache2/sites-available config file dedicated for MeshCentral TLS offloading (I used name mesh_ssl.conf)

```
<IfModule mod_ssl.c>
<IfModule mod_proxy.c>
    <VirtualHost *:555>

        ServerName yourdomain.org
        ServerAdmin admin@server

        ErrorLog ${APACHE_LOG_DIR}/mesh_error.log
        CustomLog ${APACHE_LOG_DIR}/mesh_access.log combined

        SSLEngine on

        <IfModule mod_headers.c>
            Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        </IfModule>

        ProxyRequests     Off
        ProxyPreserveHost  On

        <Proxy *>
            AddDefaultCharset off
            Order deny,allow
            Allow from all
        </Proxy>


        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:5553/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:5553/$1 [P,L]

        ProxyPass / http://localhost:5553/
        ProxyPassReverse / http://localhost:5553/

        ProxyVia         on

        BrowserMatch  "MSIE [2-6]"nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0

        SSLCertificateFile /etc/letsencrypt/live/yourdomain.org/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.org/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
    </VirtualHost>
</IfModule>
</IfModule>
```


3) test your new configuration file for errors
`# apachectl -t`


4) if Ok, enable and apply your new config
`# a2ensite mesh_ssl && systemctl apache2 reload`


5) make sure port 555 of your machine is accessible for incoming connections (check port forwarding on your router etc)


6) modify accordingly your config.json in /meshcentral-data

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "yourdomain.org",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 5553,
    "tlsOffload": "127.0.0.1",
    "aliasPort": 555,
    "mpsPort": 5554,
    "redirPort": 5556,
    "_exactPorts": true,
    "_minify": 1,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "certUrl": "127.0.0.1:555",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true
    }
  }
}
```


7) restart your MeshCentral server
