### ISSUE TITLE
Multi domains (dns name) and reverse proxy

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3983]
I set up my first additional domain. Used DNS name. I also use NGINX as a reverse proxy, which was configured according to the documentation. After starting MeshCentral, it sees that it has a new domain, you can create users in it. However, I can't get into it. The login page is rendered from the default domain.
Here are my configs. What am I doing wrong?
NGINX

```
server {
        listen 443 ssl;
        server_name remote.company.ru;
        include /etc/nginx/vhosts-includes/*.conf;

        proxy_send_timeout 330s;
        proxy_read_timeout 330s;

        location / {
                proxy_pass http://10.10.1.208:4430/;
                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;

                proxy_set_header CF-Connecting-IP $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
       }

    ssl_certificate /etc/letsencrypt/live/remote.company.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/remote.company.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

MC config
```
    "lampaneva": {
      "title": "Remote Access System",
      "minify": true,
      "ignoreAgentHashCheck": true,
      "newAccounts": false,
      "hide": 5,
      "agentNoProxy": false,
      "novnc": false,
      "mstsc": false,
      "ssh": false,
      "dns": "remote.company.ru",
      "CertUrl": "https://remote.company.ru/",
      "agentCustomization": {
        "displayName": "Remote Access System",
        "description": "Remote Access System",
        "companyName": "LLC Company",
        "serviceName": "RASagent",
        "fileName": "compagnyagentfile"
      },
      "limits": {
         "maxDevices": 3,
         "maxUserAccounts": 3,
         "maxSingleUserSessions": 2
      },
      "userSessionIdleTimeout": 60
    }
```

**Comment by AntonAndreevichMoroz** [comment]
Я так же вижу в трассеровке MeshCentral, что заголовки до него доходят так как ожидается.
```
/login

{"connection":"upgrade","host":"remote.company.ru","cf-connecting-ip":"46.39.255.244","x-forwarded-host":"remote.company.ru:443","x-forwarded-for":"46.39.255.244","x-forwarded-proto":"https","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"ru"}
```

**Comment by AntonAndreevichMoroz** [comment]
Greetings, @Ylianst.  Are there any ideas on what to check?  Why might MeshCentral not accept the secondary domain when rendering web pages?

**Comment by AntonAndreevichMoroz** [comment]
I also tested without using a proxy server. By setting the DNS names to the local addresses of MeshCentral itself. Same situation. It turns out that MeshCentral does not accept the settings of the additional domain when rendering pages. Is this a bug or did I make a mistake in the settings somewhere?

@Ylianst I also tested without using the dns parameter. Under the link https://defaultdomain/newdomain, page rendering and settings work out. But they do not work out when using a full-fledged domain name through the dns parameter.

I have already reviewed your video about the multi-domain mode of operation several times. And I can’t understand why, when using the dns parameter, the mesh does not correctly perceive the settings.

**Comment by openncomp** [comment]
I could help with the description of the multi-domain setup, but it's difficult to do it in a language other than my native language - Russian.
I have an MC2 server configured and it works fine with different domains.

Part of the configuration responsible for the multi-domain: config.json
```

  "settings": {
    "tlsOffload": "172.22.22.10", #My Nginx Proxy Manager server in local net
    "cert": "main.domain.ru", #My main domain
    "WANonly": true,
    "manageCrossDomain": [ "user//myuser" ], #My crossdomain user
    "orphanAgentUser": "myuser",
    "port": 80,
    "aliasPort": 443,
    "redirPort": 800,
    "redirAliasPort": 80,
    "trustedProxy": "172.22.22.10", #My Nginx Proxy Manager server in local net
  },
  "domains": {
#My main domain (empty, but in Nginx Proxy Manager is main.domain.ru)
    "": {
	  "certUrl": "https://172.22.22.10", #My Nginx Proxy Manager server in local net
    },
#My second domain (in Nginx Proxy Manager is temp.domain.ru)
    "temp": {
      "dns": "temp.domain.ru",
	  "certUrl": "https://172.22.22.10", #My Nginx Proxy Manager server in local net
    }
  }
```
Proxy hosts are configured in Nginx Proxy Manager:
1)
https://main.domain.ru --> http://local.ip.MC2:80
WebSockets support is enabled
2)
https://temp.domain.ru --> http://local.ip.MC2:80
WebSockets support is enabled

After that, the user "myuser" can manage users for both domains. This is done from under the web interface of the main domain.
After creating a user for the second domain, you can log in under it at https://temp.domain.ru

I hope that the translator handled the translation well ))

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above.
if issue still persists, please reply back
