### ISSUE TITLE
Request to update docs with MeshCentral native commands

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#3987]
@Ylianst Can you look at:
https://ylianst.github.io/MeshCentral/meshcentral/debugging/#server-logging-it-all

Specifically these codeblocks:
```
mkdir /meshcentral/meshcentral-logs/
chown tactical:tactical logs
ln -s ../meshcentral-logs/log.txt /meshcentral/meshcentral-data/log.txt
```
and 
```
-rw-rw-r-- 1 tactical tactical   2593 Feb  2 12:22 auth.log
-rw-r--r-- 1 tactical tactical 147593 Feb  2 12:31 log.txt
-rw-rw-r-- 1 tactical tactical    381 Feb  2 12:02 mesherrors.txt
```

These are specifically for use with the MeshCentral that's part of Tactical RMM. Can you customize this so that it'd work with native MeshCentral paths/users etc (or if you have a better method of debugging that'd be great)

**Comment by Ylianst** [comment]
Not sure I understand your request. Looking at the list your provided, I see:

Old:
```
obj.fs.writeSync(obj.xxLogFile, new Date().toLocaleTimeString() + ' - ' + source + ': ' + Array.prototype.slice.call(...args).join('') + '\r\n');
```

New:
```
obj.fs.writeSync(obj.xxLogFile, new Date().toLocaleTimeString() + ' - ' + source + ': ' + args.join(' ') + '\r\n');
```

But the old does not match what is in the code now.

If you have a suggested code change, I will gladly take it :)

**Comment by silversword411** [comment]
No, this info was provided by a tactical rmm user, from several months back...so it's customized information specifically for a tactical rmm installation on how to debug mesh information

I'd like to get these howto instructions customized so that a standard mesh user could use/follow them....and if it's a new format for getting log information, want to make sure it's right.

**Comment by Ylianst** [comment]
Thank you for your pull requests! Very much appreciated.

I must be a completely dummy today, I don't understand the request still. You can the instructions "customized"? Customized how?

**Comment by silversword411** [comment]
The request in the issue...is basically: I'm dumb, and have no idea how many different ways there are to debug both Meshcentral agent and server. You're know all there is to know about meshcentral.

Are the instructions in that debug complete? Are the other tricks you could share on how to debug both meshcentral server and agent? Other tricks you could put into these instructions for clueless people like me on how to find errors for reporting back when issues encountered. I don't know what else to put in that document, just trying to flesh it out! :)

Debuggin might be a good topic to cover in an upcoming youtube video (though there already is a video with the `trace=1` stuff, I think that was the websocket one?)

**Comment by silversword411** [comment]
...and if there's nothing else to add to debugging (no extra secrets to share) we can also just close this issue as done! :)
