### ISSUE TITLE
Question: MeshCentralRoute.exe Location, Possible to Replace?

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#3988]
Wondering where the executable is located since I'd like to replace the download with our custom installer, so that when downloading off the site or when given the "this version is out of date" prompt to get the latest version it grabs the custom installer instead.

I imagine it would get wiped out during updates, but that's fine - keeps me motivated to keep our installer up to date with the latest version. 😉

**Comment by Ylianst** [comment]
There is no installation location for MeshCentral Router, you just download it and put it where you want. The self-update should update "in-place".

When running it, the "Install..." button will show up if the registry for .mcrouter is not set or set to a path that does not match the currently running MeshCentral Router location.

![image](https://user-images.githubusercontent.com/1319013/168673978-048d9a88-ee66-4850-92d0-5a4423fd3c39.png)

Let me know if that helps.

**Comment by MatinatorX** [comment]
Sorry, I meant the location on the server where it's stored for download. My installer takes care of where it's stored on the local computer.

**Comment by Ylianst** [comment]
Oh! Go it. I have a way to place custom agents now. Let me check now and get back to you.

**Comment by MatinatorX** [comment]
Great, thanks! I was hoping it would be as easy as replacing MeshCentralRouter.exe on the server with my own installer (named the same), I just don't know where it's stored. When my installer executable inevitably gets replaced after an update, I'll just update my installer and put it back.

**Comment by Ylianst** [comment]
I will release MeshCentral v1.0.23 later today. Once updated, create a `meshcentral-data/agents' folder and place your 'MeshCentralRouter.exe` in that folder and reset the server. MeshCentral will use the copy in the `meshcentral-data` first.

The same is already supported for all the agents, so you can put a custom agent in that folder, but the new version will also do this for Router and Assistant.

**Comment by MatinatorX** [comment]
Fantastic, thanks so much! Will close this issue as soon as I can test.
