### ISSUE TITLE
Agent Connection Issue: Fortinet SSL Deep Inspection

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#3989]
Possibly related to [#2618](https://github.com/Ylianst/MeshCentral/issues/2618).

Ran into a similar problem today, agent would not connect for love nor money. Firewall on the local computer was off and IT swore up and down they were not blocking any websites. I could ping and browse the server website, but I noticed on some browsers I was getting an invalid certificate error. At that point I tried connecting with MeshCentral Router and was presented with this:

![Untitled](https://user-images.githubusercontent.com/42086791/168676833-436dd8d8-a05a-4a99-9233-2402804e0a64.png)

After some research, it turns out Fortinet has an option called "SSL Deep Inspection" which replaces certificates with their own to be able to inspect the traffic in a sort of MitM approach. This site has the feature enabled. MeshCentral correctly identifies this as a possible security breach and prevents the agent from connecting. As far as I can tell, the feature is mostly meant to be able to monitor HTTPS traffic so organizations can use Fortinet devices to if employees are browsing Facebook during work hours.

I can likely convince the IT of this site to whitelist our domain, but I was wondering if there was a better way, for example an option to have MeshCentral trust Fortinet certificates as long as the Subject CN matches the correct domain. I have no idea if this would introduce other security risks but I feel like we are going to see more of this going forward, including from other "security" providers.

**Comment by Ylianst** [comment]
Your Fortinet is acting like a "man-in-the-middle" attacker and MeshCentral is specifically designed to block this sort of attack. The dumb way to fix this is to add this line in the settings section of the config.json:

```
"ignoreAgentHashCheck": true
```

Of course, this is bad because now, anyone can man-in-the-middle the agent-to-server connection.

The next best thing is to use "certurl" in the domain section of the config.json like this:

```
"certurl": "https://myservercert.com"
```

The URL must point to a place where MeshCentral can load the trusted TLS cert. In that case, as long as agents report seeing the same certificate as "certurl", the server will accept the connection.

Let me know  if this works.

**Comment by MatinatorX** [comment]
Thanks for the answer. Unfortunately it's a customer site where Fortinet is causing trouble, so unless I'm misunderstanding something, I don't think CertUrl would help unless the Fortinet issue was server-side and we could provide the certificate it's using. If we tell MeshCentral and the agents to use a certificate at a different URL using CertUrl, Fortinet is just going to replace that one too when the agent on site looks at the new URL.

I don't really see a good way to get around it besides asking their IT department to whitelist our domain from SSL Deep Inspection. Let me know if I got the above wrong, either way will close this issue shortly.

**Comment by Ylianst** [comment]
You got it exactly right, "certurl" is only a solution if your doing the certificate replacing server side. Hold on, maybe I can do something...

**Comment by Ylianst** [comment]
Ha yes, try this line in the settings section of the config.json:

```
"ignoreagenthashcheck": [ "192.168.2.191", "192.168.2.136" ],
```

The server will ignore a man-in-the-middle attack when the agent connecting is coming from one of the IP addresses in the list. This is certainly still bad, but at least not all your connections will have poor security.

**Comment by MatinatorX** [comment]
This worked great, thanks! The site has a static public IP address so I just used that and everything is working. Definitely not ideal, but I would consider the security risk quite low in this case. Cheers!
