### ISSUE TITLE
Bug: Top Bar Interface Log Viewing Issue

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#399]
When you are in the Top Bar interface and looking at the event log for a user or device, the 2nd row of tabs is half covered up.

I'm using Firefox 68.0.1. I haven't tested on any other browsers.

**Comment by Ylianst** [comment]
Thanks for the report. I will fix this tomorrow.

**Comment by Ylianst** [comment]
Again, thanks for reporting this. Published MeshCentral v0.3.9-d with a fix. Let me know if it works for you.

**Comment by ghplw** [comment]
Thankyou it is fixed.
