### ISSUE TITLE
Feature Request: Ability to Set View Mode and Hide Items on Mobile

### ISSUE THREAD

**Issue by jrodriguez142514-dev** [Ylianst/MeshCentral#3993]
On desktop site, I can change view mode to 11 and also add &hide=31 to hide everything.

On mobile site, it won't let these settings work.  I looked at the code and I believe it wasn't implemented in the mobile version.

I need this to setup a bookmark on end user device that will go straight to remote desktop view and hide everything to maximize screen space.  I realize there is a full screen button for something like this.  However, I want the user to not see the general tab or any other 'panels'.  

A very limited version with just desktop remote control.  No other panels, footer, top bar, or tools.

**Comment by si458** [comment]
you cant really HIDE panels in the mobile view because you are limited to the size of the screen

so the best way is to goto the url `https://SERVERDNSHERE/?viewmode=10&gotonode=LONGMESHIDSTRINGHERE&panel=1`
this will take you directly the the devices `Desktop` tab where they can click connect
