### ISSUE TITLE
Feature Request: Store SSH Key with User

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#3995]
I just started messing around with the newly integrated SSH connect option from the terminal tab (nice when I want to connect as a different user directly rather than changing once I'm connected through the default terminal as root - I'm curious what others are using this for outside of edge cases where for some reason, the local console is disabled) but I'm not loving having to re-specify the key and password for each machine when they share a key. Would it be possible to instead store a key/password combo with my user account and then select it when choosing to save login credentials for an SSH connection? So basically, the goal would still be to specify a username and key when connecting via SSH but with the ability to use a key saved to my user account (selectable via dropdown, perhaps?) and save the username and reference to that stored key if choosing to save credentials for future use.

Also, semi-related, but is there a reason it's looking for OpenSSH formatted keys specifically? I feel like a standard RSA key should work out of the box as well but I had to convert mine before it would accept it.

Thanks as always!

**Comment by Ylianst** [comment]
This is going to be my work item today. Hopefully the design I have in mind to do this will work.

For OpenSSH format, I have no preference. Add an new issue and let me know what steps or software you use the generate the key pair. I can look into it.

**Comment by Ylianst** [comment]
Storage of SSH/RDP credentials will be per account starting with MeshCentral v1.0.24.

**Comment by Ylianst** [comment]
MeshCentral v1.0.24 has been released.

![MC2-PerAccountSshRdp](https://user-images.githubusercontent.com/1319013/169134262-d69a06d5-2f38-48a4-a3a7-016f00e80f8b.png)

**Comment by PetieM** [comment]
So, this appears to be working as implemented and is great for security but wasn't exactly what I was referring to. I was hoping for the option to save a key and password to your account rather than to an individual device so I could then use that same saved key/password across multiple devices that share it.

**Comment by rinseaid** [comment]
@Ylianst - I believe this change impacted the ability to save credentials from SSO user accounts (or, at least, SAML). The user has the option of remembering both the key and the password, but it doesn't actually save. I was running 1.0.89 with SAML SSO login when I noticed this issue. After seeing this thread, I did a fresh install of 1.0.23, downgraded passport to 0.5.3, and my SAML SSO user is now able to save credentials.

**Comment by nathanaelries** [comment]
Can we add the ability to allow administrators to set the account's saved RDP password? This way, multiple users can have RDP access under the same credentials, but will not know what the password is. Once their access is revoked, they will not be able to log back in or leak the password.

**Comment by dinger1986** [comment]
@si458 stale can close

**Comment by si458** [comment]
closing as feature was implemented
