### ISSUE TITLE
Change the agent installation directory

### ISSUE THREAD

**Issue by Marlonsmart** [Ylianst/MeshCentral#3998]
Hi, I would like to consult about the installation of Agent. The default installation path of Agent in Windows operating system is C:\Program Files\Mesh Agent. Can we manually configure the installation path?

**Comment by Ylianst** [comment]
Exactly this. Use agent customization settings in the config.json. It will have the agent install in your own company folder name, have the agent file name you want and you can add you own logo, etc.

Let me know if that works.

**Comment by Marlonsmart** [comment]
Thank you very much for your reply. I tried to modify the agentCustomization configuration item in the meshcentral-config-schema. json configuration file, but it was the same as before. There is another question, I wonder if it is feasible to put the installation path in another drive letter, the default is in the C drive directory.

**Comment by JSuenram** [comment]
> Thank you very much for your reply. I tried to modify the agentCustomization configuration item in the meshcentral-config-schema. json configuration file, but it was the same as before. There is another question, I wonder if it is feasible to put the installation path in another drive letter, the default is in the C drive directory.

Existing Installation will not change. Please post your config-file. Another drive is currently not possible.

**Comment by Ylianst** [comment]
The installation path is the Windows "Program Files" folder and the name if the folder within "Program Files" can be customized in the config.json using the agent customization section. You can't customize beyond this because every client machine will be different and so, no every machine will have a different drive.

If you want to install at a custom location, run `meshagent.exe -?`, you will get this:

```
Mesh Agent available switches:
  run               Start as a console agent.
  connect           Start as a temporary console agent.
  start             Start the service.
  restart           Restart the service.
  stop              Stop the service.
  state             Display the running state of the service.
  -signcheck        Perform self - check.
  -install          Install the service from this location.
  -uninstall        Remove the service from this location.
  -nodeid                       Return the current agent identifier.
  -resetnodeid      Reset the NodeID next time the service is started.
  -fulluninstall    Stop agent and clean up the program files location.
  -fullinstall      Copy agent into program files, install and launch.

                    The following switches can be specified after -fullinstall:

     --WebProxy="http://proxyhost:port"      Specify an HTTPS proxy.
     --agentName="alternate name"            Specify an alternate name to be provided by the agent.
```

Note the `-install` will install the agent at it's current location. So, copy the agent to where you want to install it and run it with `-install`. If you use `-fullinstall` it will copy itself to the `Program Files` folder.

Hope that helps.

**Comment by Marlonsmart** [comment]
This is my meshcentral-config-schema.json configuration file.
          "agentCustomization": {
            "displayName": "meshtest - QuickSupport Agent",
			"description": "meshtest - QuickSupport Agent background service",
			"companyName": "edgetest - Agent",
			"serviceName": "edgetest - Agent",
			"image": "welcome.png",
			"fileName": "edgetest-Agent"
            },

**Comment by JSuenram** [comment]
> This is my meshcentral-config-schema.json configuration file.
> "agentCustomization": {
> "displayName": "meshtest - QuickSupport Agent",
> "description": "meshtest - QuickSupport Agent background service",
> "companyName": "edgetest - Agent",
> "serviceName": "edgetest - Agent",
> "image": "welcome.png",
> "fileName": "edgetest-Agent"
> },

And it does not work? Please post complete config.json except confidential data. Maybe there is a typo.
Did you put Agent-Customization in Domain-Section or somewhere else?
