### ISSUE TITLE
createLoginToken through meshctrl.js does not output login password

### ISSUE THREAD

**Issue by pzeinlinger** [Ylianst/MeshCentral#3999]
Using
```
node meshctrl.js --url ws://localhost:4430 --loginkeyfile key.txt --loginuser XXX logintokens --add test --json
```
the output is 
```
[
  {
    name: 'test',
    tokenUser: '~t:lMKp0nQKv5iTjwJz',
    created: 1652785533166,
    expire: 0
  }
]
```

I would expect the output to include a tokenPass key.

**Comment by silversword411** [comment]
You're using software integration token, not user token:

https://ylianst.github.io/MeshCentral/meshcentral/tokens/

**Comment by Ylianst** [comment]
Looking into this one now.

**Comment by Ylianst** [comment]
You right, fixing it now. Will look like this:

![image](https://user-images.githubusercontent.com/1319013/169147640-05e91356-6a6d-41e1-a426-5c6daa1228a2.png)

**Comment by Ylianst** [comment]
Fixed. Will be in v1.0.25 but you don't need to wait for the release, just update your MeshCtrl.js with the [latest one on GitHub here](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshctrl.js). Let me know if that works.

**Comment by pzeinlinger** [comment]
Thank you! This issue is fixed and I'll go ahead and close this.
