### ISSUE TITLE
Deleted device keeps reappearing. 

### ISSUE THREAD

**Issue by GauchoEsq** [Ylianst/MeshCentral#4001]
Running 1.0.23, though this probably began occurring on 1.0.20. I deleted a device about a week ago that reappeared several days later under a different group. I have deleted it several times and it keeps coming back. This was a virtual machine that I destroyed so I know it no longer exists. It will show as connected for about 5 minutes a few times a day, but the terminal, desktop, and files tabs are missing. There is no operating system in the details or network information. Anything I can do to kill this thing forever?

**Comment by silversword411** [comment]
That means the agent is still on that machine and checking in. 

You deleting an agent in the meshcentral admin console just removes it's information and historical data. If it hits the server again, it'll reappear.

**Comment by silversword411** [comment]
You're noticing it reappear...does it show as online, or offline?

What's it's connection history?

**Comment by GauchoEsq** [comment]
Well, I definitely owe Mesh an apology. It looks like someone imaged the virtual machine on another computer and restored it to a physical machine. I reuploaded the core and to my amazement I was able to remote into a machine I deleted!

**Comment by silversword411** [comment]
I suspected something along those lines ;)

**Comment by silversword411** [comment]
...there's some code in mesh to try and de-duplicate imaged agents, it's not perfect though. If you keep seeing it...probably more than one image out there
