### ISSUE TITLE
Feature Request: Support Other Key Formats for SSH

### ISSUE THREAD

**Issue by PetieM** [Ylianst/MeshCentral#4002]
In reference to #3995, I think the error checking on an uploaded key file is currently a bit too strict. I used `ssh-keygen -t rsa -b 4096 -C username` and specified a password when generating my key. This key begins with the following lines:

````
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
````

Currently, it's being rejected and I believe it's because it's looking for `-----BEGIN OPENSSH PRIVATE KEY-----` specifically. I converted my RSA key to OPENSSH using `ssh-keygen -p -f /path/to/rsa_kay` and it works fine but my existing RSA key also works fine connecting directly from the terminal. So, can we open up support for other standard key types (at least those that you can generate with `ssh-keygen`)? Thanks!

**Comment by Ylianst** [comment]
Just added RSA PEM support, will be in MeshCentral v1.0.28.

**Comment by PetieM** [comment]
This now appears to be working as expected with a standard RSA key. I haven't tested with other key types but it solves the issue for me at least. Thanks!
