### ISSUE TITLE
Feature Request: list of software inventory in report

### ISSUE THREAD

**Issue by ONBET** [Ylianst/MeshCentral#4006]
Current computer details only show basic information, it would be great if it can display list of software as well that installed in the computer

**Comment by JSuenram** [comment]
This is more something for an RMM like https://github.com/amidaware/tacticalrmm
MESH is after all--- remote control ans support and does this very well.

**Comment by si458** [comment]
added installedapps to console for windows - https://github.com/Ylianst/MeshCentral/commit/12c3e4ee53a6a8a4108e9a7946d6df60dcd7a280
