### ISSUE TITLE
Feature Request: implement on the terminal tab "powershell connect"

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#4007]
Hi,

Would it be possible to implement on the terminal tab "powershell connect". Similar to the desktop tab "RDP connect". I work almost exclusively with powershell, so I first start cmd and only then enter powershell. This can save a lot of time. Or is it possible to set this already now? 

Thanks a lot!

**Comment by Ylianst** [comment]
Right click on the terminal "Connect" button and let me know if that works for you.

![image](https://user-images.githubusercontent.com/1319013/168978606-0e7e6a67-7105-446b-830c-bea19081cddc.png)

**Comment by johann8** [comment]
It works!
Thank yo very match!
