### ISSUE TITLE
Meshcentral Router 2FA remember for 30 days option is causing issues

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4009]
some how meshcentral router acts strange. I have 2FA enabled for my account. when I connect through Meshcentral Router it prompts for 2FA and also it shows the option to remember the device for the next 30 days. If I type the 2FA code without a check in that box, I get connected fine. But if I tick the box to remember the device for the next 30 days, then it bypass the login screen but I can't see any devices in the list. just blank. and also the whole software just freezes and i can't click on anything but end task it from task manager.
using the latest meshcentral with the latest meshcentral router.

**Comment by smartekIT** [comment]
this doesn't happen on the webpage 2FA login, as i tick the box to remember for the next 30 days and it works fine. so i guess the issue only happen in the router software.

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/169064666-0883f69d-0be0-4238-bc98-1bb211b35add.png)

**Comment by Ylianst** [comment]
I just gave it a try and can't replicate this issue. Something like this has been reported before and each time, I can't make it happen myself. If you have a public server and this happens, can you create a dummy empty account (no need for any computers in the account) and send me the server name and account info? [My contact info is here](https://www.meshcommander.com/contact-information).

There is probably some settings or situation I don't know about that causes this.

**Comment by smartekIT** [comment]
Hi @Ylianst ,
I already sent the login details to your gmail address.

Thanks

**Comment by smartekIT** [comment]
i have updated your account with permission to use router, have you checked last email?

Thanks

**Comment by smartekIT** [comment]
in a further troubleshooting i managed to narrow the issue to get to the cause of the freeze.
I logged in to the server using chrome
I saved the cookie value used by chrome for the server address.
started regedit, going into HKEY_CURRENT_USER\SOFTWARE\Open Source\MeshCentral Router
I created a String Value called: TwoFactorCookie
and for the value I pasted the cookie key value I copied earlier from the browser. saved and exit regedit.
now opening the Meshcentral Router and login, it logs in fine and doesn't even ask for the 2FA because anyway that cookie key I inserted in the registry is valid for 30 days.

so what I think happen when we tick the box for remembering the cookie for the next 30 days on the Router 2FA prompt, it actually freezes because it fails to create that TwoFactorCookie registry key and instead of error it just freeze and hung unresponsive.

You the expert here, so you can investigate further. my server login i sent you still active so you can try it.
Thanks heaps.

**Comment by Ylianst** [comment]
Thanks! Looking into this now. This is excellent information. I tried MeshCentral Router again with your server and it always works for me, your theory is having me look at the code differently.

**Comment by Ylianst** [comment]
In the next version of MeshCentral Router, if this still happens, run it with `-debug` and make it lock up. You should see a `debug.log` file, it should show this:

![image](https://user-images.githubusercontent.com/1319013/169921508-207acdba-f8ab-40d9-b0dd-eb7cdbf7c172.png)

**Comment by smartekIT** [comment]
Hi @Ylianst , i just tried the latest version and it's still doing the same thing.
looking at the debug, it shows strange order of info. clearly can see that : got String Data    then: Send string Data ....

really strange and also it never shows: Saving 2FA cookie

<pre>
09:55:AM.4460: WebSocket: Websocket got string data, len = 288
ServerData-{"action":"authcookie","cookie":"aCPQ7R$z2nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=","rcookie":"VfM6HXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX2S@YYc="}
Requesting 2FA cookie
sendCommand: {"action":"twoFactorCookie"}
09:55:AM.4700: WebSocket: WebSocketClient-SEND-String: {"action":"twoFactorCookie"}

</pre>

![image](https://user-images.githubusercontent.com/70715469/169924235-945b6c60-198b-4302-bd33-87209dcaff6b.png)

**Comment by Ylianst** [comment]
I got one more version on GitHub. After looking at the code, the self-update system was not enabled after normal login but enabled after 2FA, so it's possible it's the self-update system that is not working. With the latest version, you can run with `-noupdate` to force no self-update and there are options in the settings menu to enable/disable self-update. Hopefully that will fix it.

**Comment by smartekIT** [comment]
Hi, I tried the current version comes with MC 1.0.27 with -noupdate option but still doing the same thing.
by the way. the same app on the same computer if i connect it to another MC server i have which is running 1.0.11 and it works fine. so I believe it might be something to do with MC server after v1.0.11 which causing the Router not getting what expected regarding cookie.

**Comment by smartekIT** [comment]
closing this ticket, issue still exist but no fix.

**Comment by brahunafisk** [comment]
Did you ever find a fix?  I have the same issue on a brand-new install

**Comment by smartekIT** [comment]
> Did you ever find a fix? I have the same issue on a brand-new install

sorry didn't find a fix for this. been a long time so I just closed the ticket for clean up.
