### ISSUE TITLE
public/images/login folder discrepancy

### ISSUE THREAD

**Issue by lordofbikes** [Ylianst/MeshCentral#4010]
There are two [`public/images/login`](https://github.com/Ylianst/MeshCentral/tree/master/public/images) folder, one with lower case [`l`](https://github.com/Ylianst/MeshCentral/tree/master/public/images/login) and one with upper case [`L`](https://github.com/Ylianst/MeshCentral/tree/master/public/images/Login).

```
public/images/Login/github32.png
public/images/Login/github64.png
public/images/Login/google32.png
public/images/Login/google64.png
public/images/Login/oidc32.png
public/images/Login/oidc64.png
public/images/Login/twitter32.png
public/images/Login/twitter64.png
```
and
```
public/images/login/2fa-key-48.png
public/images/login/2fa-key-96.png
public/images/login/2fa-mail-48.png
public/images/login/2fa-mail-96.png
public/images/login/2fa-push-48.png
public/images/login/2fa-push-96.png
public/images/login/2fa-sms-48.png
public/images/login/2fa-sms-96.png
public/images/login/azure32.png
public/images/login/azure64.png
public/images/login/back.png
public/images/login/file48.png
public/images/login/generic32.png
public/images/login/generic64.png
public/images/login/intel32.png
public/images/login/intel64.png
public/images/login/jumpcloud32.png
public/images/login/jumpcloud64.png
public/images/login/push-150.png
public/images/login/push-300.png
public/images/login/reddit32.png
public/images/login/reddit64.png
```

While these are two different locations on case sensitive systems, this leads to irritations on Windows, which is case insensitive. On Windows it is only one folder containing all above listed image files.

This is irritating for `git` GUI software, e.g. [TortoiseGit](https://tortoisegit.org/), which marks a fresh clone as modified. The cause is, depending on the `login` folder notation, that one set of files is handled as renamed. Seems that `git` for Windows handle the repo correct from its shell.
While this can be declared as a `TortoiseGit` issue, it can be still irritating for developers and I'd change this to avoid any further issues.

I assume that `login` is the correct location and `Login` was created accidentally.
But I don't have the oversight yet to decide this or if moving `Login` files to `login` creates any other issues.
If somebody can check this and give advice I'd be happy to create a pull request.

**Comment by Ylianst** [comment]
Oh, I have never seen this before. It should all be lower case.

**Comment by Ylianst** [comment]
Thanks for reporting this, just fixed it in GitHub.

**Comment by lordofbikes** [comment]
No problem, looks good now!
