### ISSUE TITLE
Limit MC access via WAN / Allow via Nextcloud embedded page

### ISSUE THREAD

**Issue by edgeofthex** [Ylianst/MeshCentral#4011]
the below is copied from a post I made on reddit on 5-18-2022:
![image](https://user-images.githubusercontent.com/52288117/169114145-e17c4007-ed27-4528-a73d-2cbe2c0b6318.png)

and a subsequent reply: 
![image](https://user-images.githubusercontent.com/52288117/169112419-49615c0a-61b6-4c7d-8d43-fb2aa3954e00.png)

The solution proposed by ylianst would be perfect for my use case.

**Comment by Ylianst** [comment]
Can you send over the HTTP headers you see when making a MeshCentral request from within a NextCloud frame? Open the browser developer tools and in network, you should see all the requests. Pick any file, like a .PNG from MeshCentral, grab the request header and copy them over here. Thanks.

**Comment by edgeofthex** [comment]
Request header follows: 
GET /devicefile.ashx?c=7XksMYkoPzBrqbMr2ZTHcPcXcyLuhGF7SCAUQcmuoaUhLM@KyHppyPW2xGtsCmrcDj2c$PGhh1KG8hi@tPYO5B87qdonw8DGe9Kgt86qRJSOnntLNXmQjWZXdqGAvaPaPrM4eJgMokiv8ZmgcH44&m=dpfeBwKWxr1oH2fEsVa6ueRqaIFgqCDsPNzlHP7ZgT3iN8e2nwJNC4BmisXWTsKY&n=vgSKS8NeH2SfCjxh7RPOVJpEyfI5gPv$7Lpqwuizhaarm0zzcQiq6LYiTJxoQHFi&f=home%2Fmarkrobinson%2Fkim.svg HTTP/1.1
Host: 
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: twofactor=
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: iframe
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Sec-Fetch-User: ?1

**Comment by Ylianst** [comment]
Well, I could block web page loading unless this line is present.

```
Sec-Fetch-Dest: iframe
```

Would that be ok?

**Comment by edgeofthex** [comment]
I think so. I presume there would be an accompanying configuration parameter in config.json?

**Comment by Ylianst** [comment]
Right, it would be an option in the config.json. I ask if it's ok because this is not strictly secure. Anyone could fake this HTTP header if they wanted to, it's just a roadblock and not a secure one.

I real security solution would have the NextCloud server place a secure cookie in the browser or have MeshCentral decode the NextCloud cookie.

**Comment by edgeofthex** [comment]
I think it is a incremental solution that will work for me at this point.

**Comment by edgeofthex** [comment]
I'm afraid I don't understand http well enough to estimate what effort it would take to make your suggestion happen.

**Comment by Ylianst** [comment]
Putting the filter in place is easy, I will do that. Beyond that, probably your dealing with encrypted cookies and you to modify one or both servers and probably not something I will do.

**Comment by edgeofthex** [comment]
That did not work. In fact, my page embedded in nextcloud quit working (502 Bad Gateway), and the direct url is still working.

**Comment by Ylianst** [comment]
Sorry, typo. I meant to say, it will be released in v1.0.25.

**Comment by LPJon** [comment]
@edgeofthex I would sure like to know how you did this. This is something I would be very much interested in setting up. Is there any chance you developed an installable plugin/app?
