### ISSUE TITLE
noauth-2b error

### ISSUE THREAD

**Issue by james-sinton** [Ylianst/MeshCentral#4014]
I have keep getting an issue when connecting to devices with Meshcentral. The error is 

{"action":"close","cause":"noauth","msg":"noauth-2b"}

This error seems to come and go. One moment every device I connect to will throw this error and then as if by magic the error goes away. I haven't managed to find an error message in the server side logs.

I'll quickly describe my config:

Mesh central version: 0.9.52
Ubuntu 20.04
Jumpcloud Single Sign on
Running on an EC2 instance: t4g.small 
total devices connected 10

Any help would be greatly appreciated.

<img width="1368" alt="Screenshot 2022-05-19 at 11 44 33" src="https://user-images.githubusercontent.com/39915034/169276344-03cd73c3-e2f2-45d8-b09b-3f9da5ec0649.png">

**Comment by Ylianst** [comment]
I was looking into this until I saw your using v0.9.52. This is an old version and this issue has been fixed already. Update to latest and it should not happen anymore.

**Comment by james-sinton** [comment]
Thank you for the response. It does seem to be fixed in the new version.
