### ISSUE TITLE
BUG - Can't download file from "Files" tab when the filename has an "&" in it.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4015]
This is pretty straight forward. When trying to download a file from the "Files" tab on Windows based agents with an `&` in the filename, the link is unresponsive. After removing only the `&` the file is immediately downloadable.

**Comment by Ylianst** [comment]
Your right. Thanks for reporting this. I like these bug reports, easy to reproduce.

**Comment by Ylianst** [comment]
Working on this now.

**Comment by Ylianst** [comment]
Fixed, will be in MeshCentral v1.0.25.

**Comment by LPJon** [comment]
This works! Thanks again for all the hard work!
