### ISSUE TITLE
HAProxy / Opnsense - Agents reconnecting

### ISSUE THREAD

**Issue by ninanoe** [Ylianst/MeshCentral#4018]
I thought I got haproxy with meshcentral working.   did the tlsoffload and certUrl thing.   The website is working behind HAProxy,  but after some time I saw a lot of agents disconnecting and reconnecting.     
When I did a TRACE,  it was more then 100 messages per second !     agentstats createMeshAgentCount was in the +100000 

Changed my Install back to NAT port forward and all is fine and normal again.  

So i'm missing a parameter in my config.    Or my HAProxy  needs something not default for meshcentral ? 
Also tried with the  agentPing and agentPong,   but no change.  

The pdf is mentioning HAProxy  but looks pritty default to me,   

config parts HAproxy on opnsense:

```
defaults
    log     global
    option redispatch -1
    timeout client 30s
    timeout connect 30s
    timeout server 30s
    retries 3
    default-server init-addr last,libc

# Backend: MESH_BACK ()
backend MESH_BACK
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    http-reuse safe
    server MESH02 10.0.2.232:4430 
```

Here is my config meshcentral

```
{
   "settings": {
      "cert": "mesh.domain.com", 
      "clickonce": true, 
      "wanonly": true,
      "Port": 4430,
      "AliasPort": 443,
      "TlsOffLoad": true,
      "_maintenanceMode": true,
      "mongoDb": "mongodb://admin:******@10.0.1.193:27017",
      "mongoDbName": "meshcentral",
      "_mongoDbChangeStream": true,
      "mongoDbBulkOperations": true,
      "_webrtc": true, 
      "agentPing": 55,
      "agentPong": 55,
      "autobackup": {
         "backupIntervalHours": 6, 
         "keepLastDaysBackup": 20,
	 "mongoDumpPath": "C:\\meshcentral\\mongodbtools\\mongodump.exe",
         "backupPath": "C:\\meshcentral\\meshcentral-backup"
      },
      "plugins": { "enabled": true }
   }, 
   "domains": {
      "": {       
	 "mstsc": true,
	 "userSessionIdleTimeout": 60,
         "title2": "", 
         "titlepicture": "domain2020_mesh.png",
	 "welcomePicture": "domain_back.jpg",
	 "welcomePictureFullScreen": true,
	 "certUrl": "https://10.255.255.1",
	 "agentCustomization": {
           "displayName": "Domain MeshCentral Agent",
           "image": "assistant-logo.png"
         },
	 "agentCustomization": {
           "serviceName": "Mesh",
	   "image": "agent-logo.png"
         },
         "assistantCustomization": {
           "title": "Domain Support",
           "image": "assistant-logo.png",
           "filename": "DomainSupport"
         },
         "sessionrecording": {
            "filepath": "C:\\meshcentral\\meshcentral-recordings", 
            "protocols": [1, 
            2, 
            100, 
            101]
         }
      }
   },
   "smtp": {
        "host": "relay.domain.net", 
        "port": 25,
        "from": "admin@domain.net"
   }
}
```

**Comment by Ylianst** [comment]
Taking a quick look. Agents will connect and keep a long standing websocket connection that can last hours, days or months. Your reverse proxy configuration have a `30s` connection timeout. This should force the agents reconnect every 30 seconds. Change this time out to `330s`, as indicated in the MeshCentral configuration. If that still causes reconnections, try adding this line to the settings section of the config.json:

```
"agentpong": 300
```

Let me know if that works.

**Comment by ninanoe** [comment]
Hi Ylian, thank you,   Turns out  there is a backend  30s  and frontend 30s,    changed that to 300s and now its working,    My tracing logs are not flooded anymore and agents stay connected.  

But now I have a new issue :)    

HTTPHEADERS: GET, /agent.ashx/.websocket, {"host":"mesh.domain.net","upgrade":"websocket","connection":"Upgrade","sec-websocket-key":"+soeZdst567Sn0qCgb8bwi==","sec-websocket-version":"13","x-forwarded-for":"84.xxx.xxx.xxx"}
