### ISSUE TITLE
Desktop tab not present for new windows machine

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#4019]
I had a client download my customised MeshAgent from my website, and when installed, after usual Avast Antivirus hassles, the mesh agent connects, and I can access files, and console and terminal, but there is no desktop

All I know is that this is a windows machine, I think Windows 10 Professional

What is interesting is that WebVNC, and WebRDP show as options (although don't connect), and using RDP through Meshrouter also doesn't connect. Seems to get stuck trying to negotiate protocols.

**Comment by silversword411** [comment]
Disable/uninstall avast. If it works then, you know who to blame.

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
this happens from time to time ive noticed, a way to fix it is
1. go to console tab of the device
2. click `agent action` and select `clear the core`
3. wait 10 seconds
4. click `agent action` again and select `upload default core`
5. wait 10 seconds
6. tabs/data reappears
