### ISSUE TITLE
Most Linux agents stuck after update

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#402]
After updating MeshCentral from version 0.3.6-n to version 0.3.9-c most of the agents on CentOS 6 (strange, why not everyone?) are seen as active, but there is no way to use the Terminal and Files tabs (servers without a GUI, therefore Desktop tab is missing). When you click Connect, it writes Setup... and after a short time Disconnected.
According to tcpdump all fine. Every time you try to connect, the Console tab writes ERROR:
```
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
> info
Current Core: MeshCore v6.
Agent Time: 2019-08-04 08: 20: 17.954 + 03: 00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 14.
Server URL: wss://mesh.company.com:443/agent.ashx.
Modules: amt-lme, amt-manage, amt-mei, amt-scanner, amt-wsman-duk, amt-wsman, amt-xml, amt, linux-dbus, monitor-border, power-monitor, smbios, wifi- scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
lastMeInfo: null.
X11 support: false.
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
ERROR: {}
```
Clear the core followed by Upload default server core does not help, only restarting Meshagent on all servers helped.

Before MeshCentral updates were successful.
Servers in different data centers in different countries, while in one rack there can be two identical servers: on one Meshagent worked immediately after an update, on the other - only after a restart.
It seems that the MeshCentral has some kind of limit on the number of agents being updated at the same time, some of them managed to be updated, who didn’t have time - did they hang?

**Comment by Ylianst** [comment]
This is bad. Bryan will need to take a look at this.

**Comment by krayon007** [comment]
Can you post the contents of the following file?
 /etc/init/meshagent.conf

What's interesting is the the linux agent didnt' change from 0.3.6-n to version 0.3.9-c, only the windows agent did... I want to make sure you have the correct service definition, because I had updated that a while back, but that isn't part of the auto-update mechanism.  The old service definition didn't correctly specify auto restart on crash.

Also, are you saying you are only seeing this problem on CentOS 6 machines that don't have a desktop? My  CentOS 6 machine has a desktop, and seems to work correctly, but I can create a test setup of one that doesn't have a desktop to check the behavior, if that's the setup you have for CentOS 6.

**Comment by krayon007** [comment]
By the way, do you have user-consent enabled?

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-f with user consent fixes. If you happen to have user consent prompts, this update will make it work correctly. Thanks to Bryan for this fix. Not sure if it's related to this issue, but it very well could be.

**Comment by TitovLab** [comment]
/etc/init/meshagent.conf:
```
[tek@lin1 ~]$ cat /etc/init/meshagent.conf
start on runlevel [2345]
stop on runlevel [016]

respawn

chdir /usr/local/mesh
exec /usr/local/mesh/meshagent
```
But everything indicates that the problem is not in init script, because after the MeshCentral update agents was online, wrote errors on the "Console" tab and responded to commands in "Console" tab, but all the rest of the functionality stopped working until restarting meshagent, which was successfully performed using the init script "restart meshagent".
Each time we try to connect a new line "ERROR: {}" added on "Console" tab.

User-consent disabled.
Selinux in permissive mode.

The strangest thing is that some of the servers were correctly updated, some of them stopped working until the agent restarted. No pattern was found.
Of the 10 servers, five were updated successfully, and five recovered only after the agent restarted.
It is also very strange that "Clear the core" followed by "Upload default server core" does not help, only restarting meshagent helped.

**Comment by krayon007** [comment]
Very strange indeed. It looks like the control channel was still active, but the agent was unable to establish any new tunnels. I'll have to try to coerce my test machines to reproduce this. I have a few ideas that I'll test. In addition, I'll add a "restart" command that you can type into the agent console, to force restart the agent in case of emergency.

**Comment by dinger1986** [comment]
appears to be fixed, not an issues I have seen @si458

**Comment by si458** [comment]
closing as stale issue, but also seems to be fixed now
