### ISSUE TITLE
MeshRouter RDP connections take 'console' session on a Terminal Server (Remote Desktop Server)

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#4020]
I'm using MeshRouter like a VPN

Setting up users, with TFA, and saving a mapping for RDP to a particular Remote Desktop Server (what used to be called Terminal Server)

The user always seem to connect to the console session

**Comment by Ylianst** [comment]
MeshCentral has no control over this. MeshCentral will port map a TCP port from your local machine to a remote machine, but beyond this, the RDP client and server take over. Not sure there is anything MeshCentral could do to change the connection type when MeshCentral Router is used.

**Comment by OutbackMatt** [comment]
Normal RDP to the same machine gets a normal Remote desktop session (not a console session), using port 3389 directly, or port forwarded from another port at the internet router.

There is a /console switch that can be used for Remote desktop connections where you specifically wanted to connect to the console. I thought that Meshrouter may have used that mistakenly.

When using MeshAgent to connect to 'Desktop', we can choose which session desktop we connect to, which is awesome for support purposes

**Comment by Ylianst** [comment]
Ha! ok. I can look into this.

**Comment by Ylianst** [comment]
Ok, looking into this. If using MeshCentral Router, it's just a TCP tunnel and I don't change anything within the RDP session which is encrypted. So, my original point stands. If using the built-in web-based RDP client, then maybe I could do something, but not if your routing your own RDP client connection using MeshCentral Router.
