### ISSUE TITLE
Raspberry Pi Clipboard Issue

### ISSUE THREAD

**Issue by naoca-au** [Ylianst/MeshCentral#4021]
Hi, 

Just having an issue where the clipboard is not passing through to raspberry pi devices. I have enabled the automatic clipboard. Works on windows device ok - there is a small delay for it to be passed through, but Raspberry pi devices refuse to do it. 

Thanks in advance.

**Comment by krayon007** [comment]
Do you have xclip installed?

**Comment by naoca-au** [comment]
> Do you have xclip installed?

Thanks for that - we just installed Xclip on the target Pi and that seems to have solved the issue
