### ISSUE TITLE
Enhancement request - "toggle background" glyph

### ISSUE THREAD

**Issue by mschubeck-redux** [Ylianst/MeshCentral#4025]
I think this would be minor to implement:
On an agent-controlled machine and when working through the "Desktop" WebRTC control, and the remote machine's background is toggled "off" (the toggle is enabled), it would be nice to have the glyph change to show that the toggle is enabled.  Ideally, it would be similar to the way the multi-monitor display shows which monitor or mode is enabled when selected, or the way that the text changes color for the "Input" control when it is selected.

**Comment by si458** [comment]
**wallpaper visible:**
![Screenshot 2023-11-11 021012](https://github.com/Ylianst/MeshCentral/assets/765314/79cad264-2a89-4076-90b4-bde59e5d8f75)
![Screenshot 2023-11-11 021626](https://github.com/Ylianst/MeshCentral/assets/765314/c68dfd2c-46d8-45e5-82a3-448bce711c55)
**wallpaper removed:**
![Screenshot 2023-11-11 020958](https://github.com/Ylianst/MeshCentral/assets/765314/da989d22-6585-40dc-aa02-aa621e47fce4)
![Screenshot 2023-11-11 021637](https://github.com/Ylianst/MeshCentral/assets/765314/9359aeef-322f-467a-abb2-72b611e8416e)

**Comment by si458** [comment]
all done! dont forget to donate 🙏  https://github.com/sponsors/si458
