### ISSUE TITLE
Agent Reinstall after change to Agentcustomization

### ISSUE THREAD

**Issue by Speedg33k** [Ylianst/MeshCentral#4026]
Hi Ylian, 
First I would like to say, I am really enjoying MeshCentral, it is a very well thought out project. Thank you sincerely for your efforts.

I made some changes to agentcustomization and it is working perfectly with new agents. Existing agents are a bit more challenging, and I feel like I am missing something.

Is there a way to uninstall the existing agent and reinstall the updated agent en masse? I tried updateagent and that installed the new service but left the old one.

This process works... Console agentupdate, then find the duplicate and uninstall, then delete the disconnected node.  It feels clunky, and I feel like I am doing it wrong.
Any suggestions ?

Thanks again for a wonderful product,

-Brian

**Comment by VINISHVV** [comment]
Currently no option available.

You need to install new agent in bulk by upload new agent in desired location and run agent name -fullinstall

It will create duplicate system in your server. Once its completed run below command in bulk

C:\program files\meshagent\meshagent.exe -fulluninstall


This is not an acurate solution but temporarily you need to do similar kind of jobs to achieve this.

I think some task related to similar request is open and @ylianst will do this once the other jobs finished.

**Comment by Ylianst** [comment]
The customization of the agent is done in the "meshagent.msh" file. On one of the new agents, grab that file and you can copy it over older agent's "meshagent.msh" to update it. Then, restart the agent and you will get the new branding. Updating the agent will not change the branding, but updating the .msh file and restarting the agent will.

Hope that helps.

**Comment by krayon007** [comment]
Just to clarify, updating the msh and restarting will update the customizations with exception of service name and location. Those are set at installation time
