### ISSUE TITLE
urgent latest router is locked to meshcentral.com

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4028]
weather we sign it with our cert and lock it to our server or not, it doesn't replace the lock url. router showing this error as it's locked to meshcentral.com. I haven't checked the Assistant but I assume it's the same.

![image](https://user-images.githubusercontent.com/70715469/169640369-1d0c77da-29bd-4dc9-93f9-472e14391786.png)

**Comment by Ylianst** [comment]
WORKING ON IT!

**Comment by Ylianst** [comment]
The problem was only with MeshCentral Router, I left in debug code that hard locked the executable so I could text the locking system. Update coming in a few minutes.

**Comment by Ylianst** [comment]
MeshCentral v1.0.26 is out with the fix for this. Lets for reporting it. Let me know if it works.

**Comment by smartekIT** [comment]
thanks @Ylianst , I will update and check it. by any chance have you had a look at https://github.com/Ylianst/MeshCentral/issues/4009
I already update your permissions on my server so you can test the Router.

Thanks

**Comment by smartekIT** [comment]
@Ylianst I can confirm the Certificate Lock issue is now resolved. Thanks
