### ISSUE TITLE
Files contextual menu for user notification connection 

### ISSUE THREAD

**Issue by PandCall** [Ylianst/MeshCentral#4032]
Hi,
Could you add a contextual menu on right click like for the 
desktop / Connect/ Ask Consent + Bar, etc but for Terminal and Files to be able to inform the user that we are connecting.
Regards

**Comment by PandCall** [comment]
Wonderful, fabulous, really greet job and really listens to us when we have problems or ideas.
Regards

**Comment by PandCall** [comment]
Thanks for the update
Two points to correct for the next release

I would like to be able to have the option to warn without asking for consent, as in Desktop.
Only privacy bar.

The translation of these new functions are not yet available, but this is only cosmetic, it will happen later when the part of the choices will be finalized.

Regards

**Comment by dinger1986** [comment]
@si458 implemented can be closed
