### ISSUE TITLE
Cannot load MeshCentral Router Mappings

### ISSUE THREAD

**Issue by pascal-chag** [Ylianst/MeshCentral#4033]
I cannot load a mapping that I just saved with MeshCentral Router.
The mapping does not appear in the list.

is it possible to start meshCentral router in debug mode?

**Comment by pascal-chag** [comment]
MeshCentral 1.0.26

**Comment by OutbackMatt** [comment]
Double click the saved file that you created, and (if router is installed) the router will open with that configuration

Opening the router won't load the saved file

**Comment by pascal-chag** [comment]
it does not work.
when I double click on the saved file and choose the MeshCentralRouter.exe application, the application launches but the configuration does not load.

**Comment by pascal-chag** [comment]
it worked fine with meshCentral Router version 1.8.8096

**Comment by Ylianst** [comment]
The mapping file is a text file, just rename it to `.txt` to look at it. You can can cut & paste the file here or send me the file, my [contact is here](https://www.meshcommander.com/contact-information). I will look at it. Just saying it does not load will not allow the problem to be fixed.

**Comment by Ylianst** [comment]
Thank you! Just put in a fix for this. Will be in MeshCentral v1.0.28, but you can download the latest [MeshCentral Router from GitHub here](https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe) with the fix. Go to the link and hit "Download", the executable is signed.
