### ISSUE TITLE
featue request: configurable number of rows to display in My Users view

### ISSUE THREAD

**Issue by getut** [Ylianst/MeshCentral#4037]
There is a problem with the My Users screen when you have lots of users. Once it gets to a certain point it starts bumping users off screen with a message that says use search.  Searching is very difficult or time consuming if you don't know which accounts have slid off the view. It would be much more helpful is that view had a configurable setting for how many lines to scroll through, like 100, 200 etc.

![view](https://user-images.githubusercontent.com/1457587/170045883-ff5e5ad6-1d34-4bb0-bbde-48b87a794041.jpg)
.

**Comment by Ylianst** [comment]
Let me know if this helps.

![image](https://user-images.githubusercontent.com/1319013/170087469-876e367b-91af-4fc3-bc37-7cb1a1399f87.png)
