### ISSUE TITLE
Calculation of CPU usage wrong on Linux

### ISSUE THREAD

**Issue by wdlut** [Ylianst/MeshCentral#4039]
The calculation of the CPU usage under Linux is not correct. 
If you let your Linux machine run for a while and then open the view Details->CPU and memory usage, the graph will not show the current CPU usage. It shows a constant value instead.
I found the code in sysinfo.js function linux_cpuUtilization(). There you use the system file /proc/stat, add all types of CPU usage, divide it by the idle value and make a percentage from the result.
The problem is, the values in /proc/stat are summed up values in jiffies since system start. What you get is the average CPU usage since system start. 
We need to save the current jiffies in /proc/stat and use the difference between the current values and the saved values to calculate the CPU usage in the intervall between now and the last call of linux_cpuUtilization().

This would be my function:
...
```
var cpuLastIdle = [];
var cpuLastSum = [];

function linux_cpuUtilization()
{
    var ret = { cpus: [] };
    var info = require('fs').readFileSync('/proc/stat');
    var lines = info.toString().split('\n');
    var columns;
    var x, y;
    var cpuNo = 0;
    var currSum, currIdle, utilization;
    for (var i in lines)
    {
        columns = lines[i].split(' ');
        if (!columns[0].startsWith('cpu')) { break; }

        x = 0, currSum = 0;
        while (columns[++x] == '');
        for (y = x; y < columns.length; ++y) { currSum += parseInt(columns[y]); }
        currIdle = parseInt(columns[3 + x]);

        var diffIdle = currIdle - cpuLastIdle[cpuNo];
        var diffSum  = currSum  - cpuLastSum[cpuNo];

        utilization = (100 - ((diffIdle / diffSum) * 100)); 

        cpuLastSum[cpuNo]  = currSum;
        cpuLastIdle[cpuNo] = currIdle;

        if (!ret.total)
        {
            ret.total = utilization;
        }
        else
        {
            ret.cpus.push(utilization);
        }
        ++cpuNo;
    }

    var p = new promise(function (res, rej) { this._res = res; this._rej = rej; });
    p._res(ret);
    return (p);
}
```
...

The code works, but I don't know where to put it. I'm confuesed: I found the file sysinfo.js three times: MeshCentral/agents/modules_meshcmd, MeshCentral/agents/modules_meshcore and MeshAgent/modules.
Which one is actually used? Why do we have the same code three times? Which one must be changed?

Furthermore I noticed that the meshagent starts to consume memory after a minute or so in the CPU usage view.  Every call of the function linux_cpuUtilization() seems to consume about 30k of memory. I'm not sure, if it has to do with our special setup, or if it is a general problem. Please have an eye on the memory usage under Linux.

**Comment by Ylianst** [comment]
Thanks. Included the code. Will be in MeshCentral v1.0.28. I switch this issue to a bug for Bryan to look at why the calls consume 30k of memory.

**Comment by wdlut** [comment]
I checked the latest version. The fix works perfect. Thanks.
