### ISSUE TITLE
Text broken on Tools menu

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#404]
I am always thankful for your good software.
I found Japanese, Korean text broken on Tools menu like below image.

<img width="301" alt="text-broken-1" src="https://user-images.githubusercontent.com/3539914/62539931-578ae580-b891-11e9-92a0-48f227d21166.PNG">
<img width="300" alt="text-broken-2" src="https://user-images.githubusercontent.com/3539914/62539934-5954a900-b891-11e9-824f-6b7f484f6ada.PNG">

**Comment by Ylianst** [comment]
Thanks for the report. Yes, this needs to be fixed. Bryan will look into it.

**Comment by hchkim** [comment]
Thank you for kindness support :)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.9-o with a fix for this. Let me know if it works for you.

![MC2-NonAscii](https://user-images.githubusercontent.com/1319013/62812229-a0bd7e00-bab9-11e9-90b8-66a432d20d11.png)

**Comment by Ylianst** [comment]
Closing this one as I am pretty sure this is fixed. If there is a problem, please feel free to re-open.
