### ISSUE TITLE
pkcs7-modified forge not found

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4049]
when running the latest code from github (not via npm) it will not start because its missing a module
even though the file is indeed located where it needs to be?
```
PS C:\Users\sas_2\Documents\Developer\meshcentral> node node_modules/meshcentral --cert mytestmachine.com
MeshCentral HTTP redirection server running on port 80.
Generating certificates, may take a few minutes...
Generating root certificate...
Generating HTTPS certificate...
Generating MeshAgent certificate...
Generating code signing certificate...
Generating Intel AMT MPS certificate...
MeshCentral v1.0.28, Hybrid (LAN + WAN) mode.
ERR: node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './node_modules/node-forge/lib/forge'
Require stack:
- C:\Users\sas_2\Documents\Developer\meshcentral\node_modules\meshcentral\pkcs7-modified.js
- C:\Users\sas_2\Documents\Developer\meshcentral\node_modules\meshcentral\authenticode.js
- C:\Users\sas_2\Documents\Developer\meshcentral\node_modules\meshcentral\meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\sas_2\Documents\Developer\meshcentral\node_modules\meshcentral\pkcs7-modified.js:19:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\sas_2\\Documents\\Developer\\meshcentral\\node_modules\\meshcentral\\pkcs7-modified.js',
    'C:\\Users\\sas_2\\Documents\\Developer\\meshcentral\\node_modules\\meshcentral\\authenticode.js',
    'C:\\Users\\sas_2\\Documents\\Developer\\meshcentral\\node_modules\\meshcentral\\meshcentral.js'
  ]
}
```

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by si458** [comment]
> Looking into this now.

thank you for this.
 just curious about the new self-signing the exes,
will we have the ability to give it our own certificate/password for it to sign?
also is it done on the fly or on system startup?

**Comment by Ylianst** [comment]
On code signing, yes and yes. By default, it will code sign the agent using a new generated code signing certificate issued by the self-signed root cert your server, but you will be able to set any certificate of your own and MeshCentral will use that cert instead to sign the agent. Signing is all done on-the-fly. A cached signed copy is kept in "meshcentral-data/signedagents" and check on startup, if needed, the agent is re-signed.

I will also have the option to "lock" the agent to your server. This was a previously announced feature, but now it will be automated. Once signed, the agent executable can't connect to any other server but yours.

Once this is released, the next step it to look into dynamically changing the executables resources so that we can customize the agent's properties strings to tailor them to the server, maybe even change the agent's icon. This is all possible now since the server is capable of signing the agent.

**Comment by Ylianst** [comment]
Reading your question again... agent signing is done as server startup, not on-the-fly as you download it. Signing is a RSA operating and involved quite a bit of CPU which could lead to a denial-of-service attack if it was done on each download.

**Comment by si458** [comment]
@Ylianst brilliant thank you can't wait for the new release and a YouTube video in the future haha

**Comment by Ylianst** [comment]
Ha yes, I am recording YouTube videos tonight :) I just fixed it, can you try it and verify it works now? Thanks.

**Comment by smartekIT** [comment]
HI, currently I sign all my agents and router and assistant using [JSign](https://github.com/ebourg/jsign). of course after I had to install JSign on the same server. this all done automatically upon server update (thanks @Ylianst ) for the option to be able to run a custom script upon server update.

my script will sign exe files with the server lock option, then will copy them all signed to "**meshcentral-data/agents**" folder.

my question, can the new implementation feature affect on my script ability of signing my agents or the folder's location? specially that as per your previous instruction to put the signed .exes in "**meshcentral-data/agents**" , now I see that this new feature will look into "**meshcentral-data/signedagents**" as you just mentioned.

Thanks

**Comment by Ylianst** [comment]
The new feature does not affect your script at all. If an agent is in the `meshcentral-data/agents` folder, it is taken first and no server signing is done.

Only if no agent is in `meshcentral-data/agents` folder will get server sign an agent and place it in `meshcentral-data/signedagents`.

Hope that helps.

**Comment by si458** [comment]
@Ylianst yep that works a treat now, even code-signs differently with with name as `mytestmachine.com-04dc08`
shame my norton keeps deleting the file still every time i download it even though it has a different code-sign certificate on
(we have a paid code-sign certificate thankfully which works 99% of the time)

**Comment by Ylianst** [comment]
When it comes to AV, changing the agent's resource strings to customize them to the server should make a big difference.

**Comment by si458** [comment]
@Ylianst im havent fully customising the exe yet with name etc from the `config.json`, so changing those few bits might help i suppose

**Comment by Ylianst** [comment]
Agent customization is done in the .msh file right now, which is not part of the agent executable, so, it will not change anything on the AV front.

**Comment by Ylianst** [comment]
@smartekIT One thing to note is that if we start changing the agent's resource strings and icon in the future prior to code signing, your script will obviously not do this. That is ok, I will continue to make `meshcentral-data/agents` higher priority going forward, but you will also have the option to use your own code signing cert in MeshCentral if you like.

**Comment by smartekIT** [comment]
> The new feature does not affect your script at all. If an agent is in the `meshcentral-data/agents` folder, it is taken first and no server signing is done. Hope that helps.

thanks it's fully clear now. such a legend.

**Comment by Ylianst** [comment]
Closing since this is fixed.
