### ISSUE TITLE
Empty services tab

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#405]
MeshCentral 0.3.9-h, empty services tab:
![image](https://user-images.githubusercontent.com/11898568/62608746-1a623a00-b909-11e9-8d9b-07c1cb0d61a7.png)
Tested on Windows Server 2019 and Windows 10.

**Comment by Ylianst** [comment]
Interesting, thanks for the report. Bryan will need to look at this.

**Comment by Ylianst** [comment]
Can you go in the agent "console" tab and type "listservices" and let me know if that works? - Thanks.

![x](https://user-images.githubusercontent.com/1319013/62658935-dbd77a00-b91e-11e9-8c49-15335d9bbe51.png)

**Comment by TitovLab** [comment]
MeshCentral v0.3.9-k.
"listservices" command works fine (excent non-English characters), Services tab is empty.

**Comment by Ylianst** [comment]
MeshCentral v0.3.9-p now supports non-English characters. You can try again with the new MeshCentral and see if it works now? Thanks.

**Comment by TitovLab** [comment]
MeshCentral v0.3.9-p works fine.
All services displayed, start/stop/restart also work.
Thank you!
