### ISSUE TITLE
Mesh agent not seen

### ISSUE THREAD

**Issue by DEFALTtttttt** [Ylianst/MeshCentral#4050]
Hi. after rebooting the computer or abruptly turning it off, the service agent starts, but on the server side it shows that it is turned off until you manually stop and start the service.
![image](https://user-images.githubusercontent.com/102130048/170918486-07aea698-f3df-4c3a-bad3-11df90b4f441.png)
![image](https://user-images.githubusercontent.com/102130048/170918660-0b54e03b-a9bf-4095-a802-f75fcaf49c3b.png)
![image](https://user-images.githubusercontent.com/102130048/170918704-ecbd0772-dbd2-478f-8156-216cfdc043db.png)

**Comment by krayon007** [comment]
What server version are you running?

**Comment by DEFALTtttttt** [comment]
> What server version are you running?

![image](https://user-images.githubusercontent.com/102130048/170939301-ae8be37a-4a4d-481c-a953-ea87c2ea4276.png)

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above.
if issue still persists, please reply back
