### ISSUE TITLE
Feature Request: TLS Client Authentication to a Reverse Proxy

### ISSUE THREAD

**Issue by vidarne** [Ylianst/MeshCentral#4052]
I have a Feature Request Autenticating to a Reverse Proxy

MeschCentral Agent/MeschCentral Router has not any options for autenticate whit TLS client certificate.
what about an option when running "split port" that agents/routers can autenticate whit a uploaded certificate/self signed TLS user certificate? 

As it is now one can only use TLS user certificate for autenticating when connecting to the https:// webinterface and that works greate, if a client/user dont have the right certificate the Proxy server will not allow the client to talk to the backen/meschcentral server.
The agents needs to be then split in to a different port where the proxy server dont check for TLS certificate. 

So if there become an option for Agents/Routers to use TLS user certificate i think that will improve securety allot.

**Comment by Ylianst** [comment]
I think this is a very good request and does harden the MeshCentral server a lot without creating a big problem for users. You can issue them a certificate and they get access to the server at the TLS layer which is great. I am thinking of adding this feature as part of the base MeshCentral along with adding it to MeshCentral Router.

**Comment by Ylianst** [comment]
MeshCentral Router in MeshCentral v1.0.33 will have the option to select a client authentication certificate.

![image](https://user-images.githubusercontent.com/1319013/172041326-a90dcd51-2c9c-451a-bf96-0fc8c113673e.png)

Once released, do let me know if it works for you.

**Comment by Ylianst** [comment]
Published with MeshCentral v1.0.33

**Comment by vidarne** [comment]
MeshCentral Router works greate with the new relase v1.0.33 and client certificate,  if i try connect and not providing a valid certificate i am getting the error "unable to connect" and with a valid certificate i connect as intended. 
Thanks for the fast responde to the request about TLS authentication.

With oute certificate
![image](https://user-images.githubusercontent.com/78825157/172252233-ba472ccf-b13c-49e2-8523-2e7af146ab07.png)

Whit a valid certificate 

![image](https://user-images.githubusercontent.com/78825157/172252659-7b9d7a5c-1a85-429a-8974-59fadcefd060.png)

![image](https://user-images.githubusercontent.com/78825157/172252959-a48cb9ca-41e0-41fc-b448-da86c80c8550.png)
