### ISSUE TITLE
MeshCentral Agent doesn't install/has limited functionality on Raspberry Pi 4

### ISSUE THREAD

**Issue by Vista2003** [Ylianst/MeshCentral#4053]
Hi,

I was attempting to the agent on my Pi 4 but it either doesn't install or has limited functionality. Using the install script provided by the website returns this error in the command line:
```
root@raspberrypi4:/home/pi# (wget "https://[DOMAIN]/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || wget "https://[DOMAIN]/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo -E ./meshinstall.sh https://[DOMAIN] 'h6fwpKRhaZ4GhGcaGdDYeHuJtRQFi$KKjAkS1t$E2E@nmUrWfiGO$LLMPuI7hvPh' || ./meshinstall.sh https://[DOMAIN] 'h6fwpKRhaZ4GhGcaGdDYeHuJtRQFi$KKjAkS1t$E2E@nmUrWfiGO$LLMPuI7hvPh'
--2022-05-29 20:11:33--  https://[DOMAIN]/meshagents?script=1
Resolving [DOMAIN] ([DOMAIN])... [IP]
Connecting to [DOMAIN] ([DOMAIN])|[IP]|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5466 (5.3K) [application/octet-stream]
Saving to: ‘./meshinstall.sh’

./meshinstall.sh    100%[===================>]   5.34K  --.-KB/s    in 0s      

2022-05-29 20:11:33 (40.1 MB/s) - ‘./meshinstall.sh’ saved [5466/5466]

Downloading agent #26...
--2022-05-29 20:11:33--  https://[DOMAIN]/meshagents?id=26
Resolving [DOMAIN] ([DOMAIN])... [IP]
Connecting to [DOMAIN] ([DOMAIN])|[IP]|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3227888 (3.1M) [application/octet-stream]
Saving to: ‘./meshagent’

./meshagent         100%[===================>]   3.08M  --.-KB/s    in 0.1s    

2022-05-29 20:11:33 (20.6 MB/s) - ‘./meshagent’ saved [3227888/3227888]

Agent downloaded.
--2022-05-29 20:11:33--  https://[DOMAIN]/meshsettings?id=h6fwpKRhaZ4GhGcaGdDYeHuJtRQFi$KKjAkS1t$E2E@nmUrWfiGO$LLMPuI7hvPh
Resolving [DOMAIN] ([DOMAIN])... [IP]
Connecting to [DOMAIN] ([DOMAIN])|[IP]|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24744 (24K) [application/octet-stream]
Saving to: ‘./meshagent.msh’

./meshagent.msh     100%[===================>]  24.16K  --.-KB/s    in 0.001s  

2022-05-29 20:11:33 (30.2 MB/s) - ‘./meshagent.msh’ saved [24744/24744]

./meshinstall.sh: line 174: ./meshagent: No such file or directory
Downloading agent #26...
--2022-05-29 20:11:33--  https://[DOMAIN]/meshagents?id=26
Resolving [DOMAIN] ([DOMAIN])... [IP]
Connecting to [DOMAIN] ([DOMAIN])|[IP]|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3227888 (3.1M) [application/octet-stream]
Saving to: ‘./meshagent’

./meshagent         100%[===================>]   3.08M  20.2MB/s    in 0.2s    

2022-05-29 20:11:33 (20.2 MB/s) - ‘./meshagent’ saved [3227888/3227888]

Agent downloaded.
--2022-05-29 20:11:33--  https://[DOMAIN]/meshsettings?id=h6fwpKRhaZ4GhGcaGdDYeHuJtRQFi$KKjAkS1t$E2E@nmUrWfiGO$LLMPuI7hvPh
Resolving [DOMAIN] ([DOMAIN])... [IP]
Connecting to [DOMAIN] ([DOMAIN])|[IP]|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24744 (24K) [application/octet-stream]
Saving to: ‘./meshagent.msh’

./meshagent.msh     100%[===================>]  24.16K  --.-KB/s    in 0.001s  

2022-05-29 20:11:33 (23.6 MB/s) - ‘./meshagent.msh’ saved [24744/24744]

./meshinstall.sh: line 174: ./meshagent: No such file or directory
root@raspberrypi4:/home/pi# ./meshagent -install
bash: ./meshagent: No such file or directory
```
Installing the ARM-HF Pi binaries would work and the agent does connect to the server however, this then introduces a new problem where I have limited functionality.

![image](https://user-images.githubusercontent.com/55105920/171054451-64123a5b-4bf9-468f-b332-621c0b7a3baf.png)
Options for the Pi 4

![image](https://user-images.githubusercontent.com/55105920/171054482-abd283bb-340a-40d9-b717-5cba0b294286.png)
Options for the Pi 3+

As you can see, I'm missing the terminal and remote desktop funtionality of the agent when using a Pi 4. 

The agent seems to also fail to identify anything about the Pi 4 as well.
![image](https://user-images.githubusercontent.com/55105920/171054677-c1a3b0be-9769-4e59-89cf-aecc5e1cb646.png)

**Comment by Vista2003** [comment]
Should clarify, this is using the default Raspberry Pi OS based on Debian 10

**Comment by krayon007** [comment]
If you click clear core, the upload default core, does it do anything? Or if you clear the core, then click upload recovery core.

**Comment by Vista2003** [comment]
> If you click clear core, the upload default core, does it do anything? Or if you clear the core, then click upload recovery core.

Hi, I'm quite new to MeshCentral, where are these buttons?

**Comment by krayon007** [comment]
On the web interface, there should be a console tab. In the console tab, there is drop-down to clear the agent core, and upload a few different cores.

**Comment by Vista2003** [comment]
Hi, thanks for the message. Clicking those buttons doesn't seem to do anything

**Comment by krayon007** [comment]
Does anything happen if you type the following command in the console tab?

`help`

**Comment by Vista2003** [comment]
Update: I've "fixed" it by using the 32bit version of Raspberry Pi OS, rather than the 64 Bit version of it

**Comment by razdavidovich** [comment]
Has anyone found a solution for this?
I am having the same issue with a few devices. almost all the devices are registering correctly, so far I have 2 that does not...
They are both 32bit versions of RPI with 2GB of memory.

**Comment by si458** [comment]
> Has anyone found a solution for this?
> I am having the same issue with a few devices. almost all the devices are registering correctly, so far I have 2 that does not...
> They are both 32bit versions of RPI with 2GB of memory.

What's the error you are getting? Im running 1 3b+ 32bit, rpi 4 64bit and even a zero w arm32 with no problems

**Comment by razdavidovich** [comment]
> > Has anyone found a solution for this?
> > I am having the same issue with a few devices. almost all the devices are registering correctly, so far I have 2 that does not...
> > They are both 32bit versions of RPI with 2GB of memory.
> 
> What's the error you are getting? Im running 1 3b+ 32bit, rpi 4 64bit and even a zero w arm32 with no problems

./meshinstall.sh: line 174: ./meshagent: No such file or directory
I got it figured out by deleting all the downloaded files, updating the pi to the latest software and **reboot the pi**
Run the installer after the reboot and it worked like a charm...

**Comment by si458** [comment]
@razdavidovich sounded to me like it just couldnt download the file for some reason, but glad u got it sorted 👍

**Comment by WitekioPhil** [comment]
I am getting the same error.

```HTTP request sent, awaiting response... 200 OK
Length: 28112 (27K) [application/octet-stream]
Saving to: ‘./meshagent.msh’

./meshagent.msh               100%[=================================================>]  27.45K  --.-KB/s    in 0.004s

2023-07-25 17:25:05 (6.33 MB/s) - ‘./meshagent.msh’ saved [28112/28112]

./meshinstall.sh: line 174: ./meshagent: No such file or directory ```

RPi 4B
Latest Raspberry Pi 32-bit OS, programmed fresh today.
All packages up to date.

Have tried deleting the downloaded files and rebooting without any impact - exact same failure.

Seeing this on three identical systems.

Any ideas? Has anyone done this successfully recently?

**Comment by si458** [comment]
@WitekioPhil it seems like it isnt downloading the files correct
whats the full output of you running the command frm the web panel?

**Comment by WitekioPhil** [comment]
> @WitekioPhil it seems like it isnt downloading the files correct whats the full output of you running the command frm the web panel?

Thanks for your quick reply.

You can see the file was downloaded to 100% in the log I shared. It certainly isn't empty given the output of the cat command when run against this binary. The meshinstall.sh script runs fine (apart from the aforementioned error!), doesn't seem to be corrupted etc.

Full log below, server details and hash ID redacted.

![image](https://github.com/Ylianst/MeshCentral/assets/78737454/0e00f63c-7c3d-47e5-90ff-16893de243d5)

P.S. asking people to publicly post logs that include the public IP address and hash ID of their MeshCentral server is a bad idea IMHO, it's enough info for anyone to add a device to that server!

**Comment by si458** [comment]
try these few suggestions:

can you try making a blank directory, going into it and running the script again?

ive also spotted it says 'Must be root to install or uninstall the agent'
try going into root mode first then running the command `sudo su -` then `run the long command`

**Comment by WitekioPhil** [comment]
Thanks for the suggestions, no change on the result I'm afraid:

Made a directory (/home/<USER>/mesh). Ran install script from that folder, same error.

In same folder, but prefixing command with `sudo su`: same error.

Running the exact same script on a Ubuntu 22.04 VM: prompts for password at necessary point (i.e. no `sudo su` required), and agent installed successfully on first attempt and visible on server.

**Comment by si458** [comment]
no no actually go into a root session using `sudo su - ` 
THEN
when in root `root@raspberrypi:~ $` actually run the long command

**Comment by si458** [comment]
@WitekioPhil after checking over the `meshinstall.sh` on my server
i think the install script is detecting the wrong OS for ur pi
i noticed in your screenshot `downloading agent #26`
`#26` is assigned `$machineid` in the script which gets called in function `DownloadAgent`
`DownloadAgent` is ony called once in the script after it has detected what your `$machinetype` is
and found
```
if [ $machinetype == 'aarch64' ]
then
  # RaspberryPi 3B+ running Ubuntu 64 (aarch64)
  machineid=26
fi
```
`$machinetype` is set here `machinetype=$( uname -m )`

please can you run `uname -m` in your commandline and let me have the output?
as i believe you are indeed running the 64bit version of raspbian OS and not the 32bit version
https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit

**Comment by WitekioPhil** [comment]
> no no actually go into a root session using `sudo su - ` THEN when in root `root@raspberrypi:~ $` actually run the long command

Yes, that's exactly what I did.

**Comment by si458** [comment]
@WitekioPhil please ready my previous comment - https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1650261867

please can you run uname -m in your commandline and let me have the output?
can you also run uname -a and let me have the output

**Comment by WitekioPhil** [comment]
> @WitekioPhil after checking over the `meshinstall.sh` on my server i think the install script is detecting the wrong OS for ur pi i noticed in your screenshot `downloading agent #26` `#26` is assigned `$machineid` in the script which gets called in function `DownloadAgent` `DownloadAgent` is only called once in the script after it has detected what your `$machinetype` is and i found
> 
> ```
> if [ $machinetype == 'aarch64' ]
> then
>   # RaspberryPi 3B+ running Ubuntu 64 (aarch64)
>   machineid=26
> fi
> ```
> 
> `$machinetype` is set here `machinetype=$( uname -m )`
> 
> please can you run `uname -m` in your commandline and let me have the output?
> 
> can you also run `uname -a` and let me have the output
> 
> as i believe you are indeed running the 64bit version of raspbian OS and not the 32bit version https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit

The meshagent binary the script downloaded is 64-bit, same as the OS:

![image](https://github.com/Ylianst/MeshCentral/assets/78737454/93be1c8e-a84b-4c05-a7b4-91735510e18f)

**Comment by si458** [comment]
@WitekioPhil yes the is potentially an issue with 64bit OS of ARM,
you need to install the 32bit version of raspbian OS instead!

https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1150691402

**Comment by WitekioPhil** [comment]
> @WitekioPhil yes the is potentially an issue with 64bit OS of ARM, you need to install the 32bit version of raspbian OS instead!
> 
> [#4053 (comment)](https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1150691402)

Do you know if there's any plan to fix this properly?

Re-imaging all three of these RPi's wasn't top of my bucket list for today.... 

Are you sure it works on 32-bit?

**Comment by WitekioPhil** [comment]
@si458 thanks, tried on a 4th Pi 4 that already had 32-bit OS, worked perfectly.

This is frustrating, as there was a genuine reason for using the 64-bit OS: community testing of various projects shows a 48% performance improvement on average.

**Comment by WitekioPhil** [comment]
A further note: I downloaded the Raspberry Pi Imager fresh today as part of the above, and selected the default option, which states it's a 32-bit OS. Clearly this is incorrect, as the resulting systems were 64-bit.

Therefore, you might get more users running into this issue as they'll think they installed the 32-bit OS, but the RPi Imager installed 64-bit instead!

**Comment by si458** [comment]
hmmm thats weird just tried a complete fresh install of `Raspberry Pi OS Lite (64-bit)` on my Pi Zero 2 W and it worked straight away? first try?
```
simon@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
simon@raspberrypi:~ $ uname -m
aarch64
simon@raspberrypi:~ $ (wget "https://meshcentral.myserver.com/meshagents?script=1" -O ./meshinstall.sh || wget "https://meshcentral.myserver.com/meshagents?script=1" --no-proxy -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo -E ./meshinstall.sh https://meshcentral.myserver.com 'VERYLONGSTRINGHERE' || ./meshinstall.sh https://meshcentral.myserver.com 'VERYLONGSTRINGHERE'
--2023-07-25 19:46:46--  https://meshcentral.myserver.com/meshagents?script=1
Resolving meshcentral.myserver.com (meshcentral.myserver.com)... 1.2.3.4
Connecting to meshcentral.myserver.com (meshcentral.myserver.com)|1.2.3.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5466 (5.3K) [application/octet-stream]
Saving to: ‘./meshinstall.sh’

./meshinstall.sh                                     100%[===================================================================================================================>]   5.34K  --.-KB/s    in 0s

2023-07-25 19:46:46 (29.2 MB/s) - ‘./meshinstall.sh’ saved [5466/5466]

Downloading agent #26...
--2023-07-25 19:46:47--  https://meshcentral.myserver.com/meshagents?id=26
Resolving meshcentral.myserver.com (meshcentral.myserver.com)... 1.2.3.4
Connecting to meshcentral.myserver.com (meshcentral.myserver.com)|1.2.3.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3256688 (3.1M) [application/octet-stream]
Saving to: ‘./meshagent’

./meshagent                                          100%[===================================================================================================================>]   3.11M  3.76MB/s    in 0.8s

2023-07-25 19:46:48 (3.76 MB/s) - ‘./meshagent’ saved [3256688/3256688]

Agent downloaded.
--2023-07-25 19:46:48--  https://meshcentral.myserver.com/meshsettings?id=VERYLONGSTRINGHERE
Resolving meshcentral.myserver.com (meshcentral.myserver.com)... 1.2.3.4
Connecting to meshcentral.myserver.com (meshcentral.myserver.com)|1.2.3.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57675 (56K) [application/octet-stream]
Saving to: ‘./meshagent.msh’

./meshagent.msh                                      100%[===================================================================================================================>]  56.32K  --.-KB/s    in 0.03s

2023-07-25 19:46:48 (2.05 MB/s) - ‘./meshagent.msh’ saved [57675/57675]

...Checking for previous installation of "meshagent" [NONE]
...Installing service [DONE]
   -> Starting service... [OK]
simon@raspberrypi:~ $
```

**Comment by WitekioPhil** [comment]
@si458 - as per my previous [comment ](https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1650362385), there is something wrong with v1.7.5 of the RPi Imager tool since I selected 32-bit and got 64-bit.

Recommend you check what you actually have!

**Comment by WitekioPhil** [comment]
@si458 was that a fresh install of the RPi imager tool? (Or did you program your SD card using a different tool?)

I installed the imager fresh this afternoon, on a system without any cached images etc.

Currently can't explain why I got 64-bit after choosing 32-bit.

**Comment by si458** [comment]
@WitekioPhil yes it was using pi image 1.7.5, just trying re-image now on my 3b and 4,
have selected the 32bit os thats first on the list
awaiting results

**Comment by WitekioPhil** [comment]
@si458 thanks for checking. I'm trying the 64-bit lite image now on a 4b.

**Comment by WitekioPhil** [comment]
@si458 just installed cleanly on same RPi4 that was failing before. This time using 64-bit lite OS.

The arch of the system and binary are reported identically to my previous [comment](https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1650330232), yet this time it works. Keen to know how you got on with the 32-bit option that's first on the list in the RPi Imager...

**Comment by si458** [comment]
https://lindevs.com/check-whether-raspberry-pi-os-is-32-bit-or-64-bit

Note: `uname -m` command can be used to determine if Linux kernel is 32-bit or 64-bit. A 32-bit OS can use a 32-bit or 64-bit kernel. After Linux kernel update to 6.1 on Raspberry Pi OS, the 64-bit Linux kernel is used by default, even on the 32-bit OS. In that case, uname -m returning aarch64 instead of armv7l.

**Comment by WitekioPhil** [comment]
@si458 yeah, I was aware of that.

The bit I can't explain:

Failing system, having selected first choice in the list shown by the Raspberry Pi Imager (32-bit desktop):
![image](https://github.com/Ylianst/MeshCentral/assets/78737454/93be1c8e-a84b-4c05-a7b4-91735510e18f)

Working system, having selected 64-bit lite OS in the Raspberry Pi Imager:
![image](https://github.com/Ylianst/MeshCentral/assets/78737454/a32d2f33-d0c3-45b0-a5cf-b36b2cd5a0f4)

I can't see any differences here to explain why one failed and the other worked....

What did you get for the above commands on your RPi 4 using 32-bit image as mentioned [here](https://github.com/Ylianst/MeshCentral/issues/4053#issuecomment-1650372602)?

**Comment by si458** [comment]
whats the output for `getconf LONG_BIT` of the 2 systems?

**Comment by WitekioPhil** [comment]
32 on failing, 64 on working.

Thanks for your help with this.

I think the takeaway right now is: potential incompatibilities with default 32-bit image provided by 1.7.5 version of RPI Imager as of time of writing.

**Comment by si458** [comment]
> I think the takeaway right now is: potential incompatibilities with default 32-bit image provided by 1.7.5 version of RPI Imager as of time of writing.

i dont think this is true as ive just tried it here and it works no problem?

flash sd card with default 32bit option (i have settings set in the settings menu for wifi, user, etc),
plug in pi,
connect over ssh,
run command, no issues at all?

**Comment by WitekioPhil** [comment]
@si458 thanks for confirming!

Looking at the meshinstall.sh script, it's clearly not currently compatible with how the current 32-bit default RPi OS is configured.

We need this [line](https://github.com/Ylianst/MeshCentral/blob/05aeb8a2440840e5e9d7953820de84ff4a5bbc6a/agents/meshinstall-linux.sh#L85) to also be included near this [line](https://github.com/Ylianst/MeshCentral/blob/05aeb8a2440840e5e9d7953820de84ff4a5bbc6a/agents/meshinstall-linux.sh#L113).

Will see about raising a PR this later this week unless you get there first!

**Comment by si458** [comment]
@WitekioPhil i was about to submit this exact PR but it doesnt fix the issue

just discovered the is already open issues about this problem

you need to change the pi from 64bit kernel to 32bit kernel if using 32bit os

**Comment by ryny24** [comment]
I've been driving myself crazy with the same exact issues in this thread. Non-binary install errors out. Binary install has limited functionality, can't even do 'info' in console.

My install appears to be 64-bit (aarch64) even though I installed 32 bit OS desktop.

**Comment by ryny24** [comment]
Wow, that was an easy fix.   So, I found [this thread](https://raspberrypi.stackexchange.com/questions/143287/i-installed-raspbian-32-bit-but-arch-writes-aarch64) that confirms 32 bit OS has a 64 bit kernel.

> The switch to running a 64-bit kernel by default on Pi 4 is intentional. We believe it gives a better experience with few drawbacks.

After flashing Rasperry Pi OS 32 bit, add "**arm_64bit=0**" to the bottom of config.txt.

Now after boot, you should get a 32 bit kernel

```
pi@raspberry:~ $ uname -m
armv7l
```

Now, I can do the non-binary MeshCentral install and all functionality is there. Thank you!!!!!

**Comment by si458** [comment]
@ryny24 it is silly personally why raspberry pi decided in there wisdom, that a 32bit OS should use a 64bit kernel?
I don't believe any others like ubuntu or even archlinux do this! It's only raspbian OS

**Comment by si458** [comment]
im just wondering if people are still having this issue?

ive just done a complete FRESH install of raspbian bookworm 64bit on both my pi 3b+ and my pi4,
and its now installing perfectly fine? i even checked the config.txt and `arm_64bit=1` was set by default?
only issue is you MUST switch from wayland to x11 with raspi-config to get the Desktop tab to work/show

my mesh agent is showing as 'Linux ARM 64 bit (glibc/2.24 NOKVM)'
