### ISSUE TITLE
Feature request: Add computer name / display name on connection details when running the agent from install folder

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#4054]
Its a minor thing, but in some cases I found the agent was installed and running, but didnt find the agent on the server list, even by searching for the system name I got from the windows system properties. So I would like to see in the screen that comes up when I run the already installed agent to show the name of the computer on the server, perhaps the edited name instead of the OS name. but overall, this would be nice in such awkward situations. I Think the agent could query the server for such info. I dont know if it would case any security concern

There are several information already there execept for the machine name.  If at least the actual system name is there it saves us from having find it elsewhere and it would not need to query the server.

![image](https://user-images.githubusercontent.com/4949495/171059089-e4683e83-3ea3-4081-b13e-ea6a25ddee7a.png)

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b16c6a3b-c5ec-45e7-bcfc-4a4c0bdc781b)
