### ISSUE TITLE
Feature Request: Add New Group for agentless SSH Connections

### ISSUE THREAD

**Issue by FrankSanabria** [Ylianst/MeshCentral#4056]
Hi,

Maybe is possible create a group that allow create connections through SSH in WAN mode.

Regards

**Comment by Ylianst** [comment]
Well, that would mean that the target SSH port is open on the Internet. I guess I could add an option to allow local device groups to be created in WAN mode, would that be ok?

**Comment by FrankSanabria** [comment]
> Well, that would mean that the target SSH port is open on the Internet. I guess I could add an option to allow local device groups to be created in WAN mode, would that be ok?

Yes please, SSH Support throught internet conection is more easy for manage remote computer without Agent installation where sites o customer for compliance not authorize another software installation.

**Comment by si458** [comment]
you can enable `LAN+WAN` mode together
by making sure `wanonly` and `lanonly` is EITHER commented out like `_wanonly _lanonly` OR set them both as false
then create a local device group, then set the ip as an external ip
also make sure you enable `ssh:true` inside your `domain` in config.json and you will get web ssh access!
