### ISSUE TITLE
Transition an existing meshcentral DB from NeDB  no user transfer

### ISSUE THREAD

**Issue by arduin0guru** [Ylianst/MeshCentral#4059]
I am running Meshcentral 1.0.28 with NeDB works without any problem.
when i am importing data to Mongodb , User setting doesn't transfer. At 1st time login screen all users are invalid and i have to create new user to login and all other settings related users are missing..
I check meshcentral.db.json after exporting , All user data is there.

```
node meshcentral --dbexport 
node meshcentral --mongodb mongodb://127.0.0.1:27017/meshcentral --dbimport
```

Command i used to import..
Also i notice all other settings are missing too like ssl cert..
Any clue why ???
![MongoDB](https://user-images.githubusercontent.com/18668814/171323906-b1f3f64c-a1f0-46b4-b788-e73ceca291b2.jpg)

**Comment by Ylianst** [comment]
Hi. To correctly export and import the database, first make sure the server is working correctly with NeDB, stop the server and type this:

```
node meshcentral --dbexport bob.json
```

When, make changes to the config.json to make MongoDB work. Once that is done, type this:

```
node meshcentral --dbimport bob.json
```

That will import your data into MongoDB.

You can find documentation [on this here](https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/meshcentral/index.md#database-import), I also have a [YouTube video here](https://www.youtube.com/watch?v=iPtaaXMdDfY).

Hope that helps.

**Comment by Ylianst** [comment]
This command:

```
node meshcentral --dbimport dbexport.json
```

Will import to the currently setup database. So, if you setup the config.json to using MongoDB, then this will import into MongoDB.

**Comment by arduin0guru** [comment]
node meshcentral --mongodb mongodb://127.0.0.1:27017/meshcentral --dbimport /dbexport.json

This command will work ??

**Comment by arduin0guru** [comment]
Here is screenshot of data import in mongodb
![MCDbExp](https://user-images.githubusercontent.com/18668814/171326155-c9c80351-0276-411c-8da2-3f019ad43a0a.jpg)

**Comment by arduin0guru** [comment]
Finally its working. Here is command that worked.
MeshCentral\node_modules\meshcentral>node meshcentral --mongodb mongodb://127.0.0.1:27017/meshcentral --dbimport /meshcentral/dbexport.json

Must be in "MeshCentral\node_modules\meshcentral" dir..
Define path of json file to import "/meshcentral/dbexport.json"

Thanks alot for help.....

![FinalMCMongo](https://user-images.githubusercontent.com/18668814/171334906-9f6c073e-3f73-4af6-b498-8afb8822bafd.jpg)
