### ISSUE TITLE
Copy IP adresses and MAC to clipboard

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#406]
It will be extremelly useful to add copy to clipboard buttons in Network Interfaces dialog:
![image](https://user-images.githubusercontent.com/11898568/62610558-9611b600-b90c-11e9-9d60-11b9cf2986fb.png)

**Comment by Ylianst** [comment]
Easy one. Published MeshCentral v0.3.9-i with this added. If it works, please close this issue. Thanks.

![x](https://user-images.githubusercontent.com/1319013/62646800-f819ed80-b903-11e9-8258-38fa19561a7f.png)

**Comment by Ylianst** [comment]
FYI. Next version will have a "copy" icon next to the DNS suffix.

**Comment by TitovLab** [comment]
It works and helps a lot!
Thank you!
