### ISSUE TITLE
MeshAgent download does not set correct MeshServer URL in meshagent.ashx

### ISSUE THREAD

**Issue by reddn** [Ylianst/MeshCentral#4060]
I upgraded from a previous version to current version of 1.0.28.  

Each MeshAgent properly installs but leaves "MeshServer=local" instead of updating with the proper url, which was apart of the command line of meshinstall.sh 

This occurred on 3 installs on linux that I did.  Both using the rebuilt binary and the self built version using meshinstall.sh

**Comment by jamgrorg** [comment]
> I upgraded from a previous version to current version of 1.0.28.  
> 
> Each MeshAgent properly installs but leaves "MeshServer=local" instead of updating with the proper url, which was apart of the command line of meshinstall.sh 
> 
> This occurred on 3 installs on linux that I did.  Both using the rebuilt binary and the self built version using meshinstall.sh
> 
> 

Yap, I can confirm that. I've got this issue to.

**Comment by reddn** [comment]
properly setting up the config.json file under the 'cert' key works.  Maybe I'll add a warning when accessing the interface by a FQDN when the settings.cert value does not match
