### ISSUE TITLE
Ran prebuilt binary on ARM HF Raspberry Pi results in "Language: c is not translated." install failure

### ISSUE THREAD

**Issue by reddn** [Ylianst/MeshCentral#4061]
Pre-built binary does not work.

Installing using the meshinstall.sh made the install work correctly

**Comment by krayon007** [comment]
Does it work if you run the prebuilt binary but add the parameter? (I can't remember if it's a single dash or double dash)

`-lang=en_us`

**Comment by reddn** [comment]
Yep, that was it... 

I think I found where if it was null, it defaulted to 'en' instead of 'en_us'.  

I started a pull request where i changed the default to en_us also added a bit more detail of how to fix the problem by giving the example like you listed.  

Here is the original https://github.com/Ylianst/MeshCentral/blob/f295d2f780776c0144fddfac6e92fdd6c636ae69/agents/meshinstall-linux.js#L48

Here is the pull request https://github.com/Ylianst/MeshCentral/pull/4063

Thank you for your response.  

Issue closed.

**Comment by reddn** [comment]
So, I think I tracked it down.  the "require('util-language').current" must return something strange.  But I can not find what and where this mysterious package is.  Although there are a bunch of split and join calls, I'm guessing it is returning 'c' instead of defaulting to 'en'.  

I created a bandaid where if the length of the util-language.current was less than 2, to make the language 'en' (en-us is not needed).  I did not propose this as a PR, but I did PR a comment adding to use the '-lang=en' which will make the install work.

**Comment by reddn** [comment]
new PR.. this is a permeant fix.  Basically the util-langauge.current returns the process.env.LANG variable, which defaults to "C" and instead of 'null' when not set.    The PR defaults the langauge to en when it see's "C". 

https://github.com/Ylianst/MeshCentral/pull/4079

**Comment by reddn** [comment]
PR committed. 

Although I think any unrecognized language setting should default to 'en'.  This exact issue is closed.
