### ISSUE TITLE
Modify behavior on slow connections?

### ISSUE THREAD

**Issue by BillBardon** [Ylianst/MeshCentral#4064]
I have the misfortune of using MeshCentral on a throttled mobile connection today. I have quality set at 5% and frame rate at very slow. It still takes about 2 minutes for a remote desktop to respond and repaint after say, a mouse click, or typing a few characters. While I wait, I see every pointer movement, screen scroll, or  animated graphic sloooowly dance around the screen, until finally, it catches up with my 2-minute-ago self and I can do the next thing.

Would it be possible, when a slow connection is detected, to throw away all the intermediate frames and just jump to the last? I don't really need to see a page down happen one block at a time. If this could be done, it would make a dramatic difference for users on slow connections.

**Comment by si458** [comment]
i believe when you change the quality, you have to disconnect and reconnect
i tried this the other day, changed from 40% to 10% expecting a picture quality change to be terrible (as expected) but nothing happened?
i then disconnected and reconnected and it refreshed to the rubbish quality (as expected)
