### ISSUE TITLE
ClamAV on windows

### ISSUE THREAD

**Issue by initialcomms** [Ylianst/MeshCentral#4068]
Good Evening,

Ive had this error come up on my windows clam av>
![Capture](https://user-images.githubusercontent.com/65313387/171507961-ada01dd4-2bc6-4bce-bd55-827381cb6cd7.JPG)

Any ideas why it cant get access?

Thankyou

**Comment by Ylianst** [comment]
Look like a `Can't open file` error for a file within the `meshcentral-files` folder. I am going to guess your running MeshCentral as a background windows service as a "SYSTEM" user. In that case, users placing files in the "My Files" folder will have their files uploaded to the server in "meshcentral-files" with "SYSTEM" as the owner.

Your anti-virus does not have rights to read these files. You can run is "As Administrator..." and see if it fixes it.

**Comment by initialcomms** [comment]
Thanks for such a quick reply, i thought i can trust clamav and you.

Sorry to disturb you, thought of using twitter but thought this is more suitable.

**Comment by Ylianst** [comment]
GitHub is my favorite place to answer questions for sure.
