### ISSUE TITLE
SSH connect fails

### ISSUE THREAD

**Issue by MrManor** [Ylianst/MeshCentral#4072]
We have updated Meshcentral to try out the new SSH feature, which we are very excited about. But nothing seems to happen when we select the SSH bottom. 

I try to connect to some Centos hosts. They have selinux enabled and a hardened ssh setup, so that is most likely part of the problem. But there is no sign in any logs I can think of, that could indicate where the agent hits a roadblock. There is no indication of any ssh activity on the log webpage of MeshCentral. 

As I am very new to Mechcentral I am a bit lost on how to debug this.

**Comment by K-O-K** [comment]
Hi,

Did you tried the `"ssh": true` parameter in the domain section?

Other thing to take into account is that you must have at least v11 of node.js installed, check it with `node -v`

Lastly, in you MeshCentral Server, you could try to install the ssh2 module:  `npm install ssh2`

**Comment by MrManor** [comment]
@K-O-K you are absolutely right. I overlooked that I had to include ssh in the conf file.

I'd like to suggest that the SSH buttom is only visible, when ssh is enabled.

**Comment by Ylianst** [comment]
I took a quick look and I can't get the SSH button to show up when SSH is not enabled in the config.json. Was is showing up with the agent device group? Or agent-less? I would be interesting in replicating this.

**Comment by Ylianst** [comment]
Oh, I see it now. Working on a fix for that!

**Comment by Ylianst** [comment]
Just added a fix, will be in MeshCentral v1.0.34.

**Comment by timgjr** [comment]
> Just added a fix, will be in MeshCentral v1.0.34.

Quick note: I'm running 1.0.36 now, and while SSH is no longer visible if not enabled, I'm still seeing SFTP .. confused me when I tried to use and it didn't work until I read this thread and enabled SSH.. :)

Works great btw!
