### ISSUE TITLE
SSH option not available

### ISSUE THREAD

**Issue by aislerad** [Ylianst/MeshCentral#4074]
Not seeing the ssh option when I go into terminal section is this something I need to enable through the json config? Is this option only available for linux machines?

**Comment by Ylianst** [comment]
Yes, you need to add `"ssh": true` in the domain section of the config.json. 

```
  "ssh": true
```

When restarting the server, extra modules will be installed to support SSH. Also, NodeJS v11 and higher is required.

**Comment by aislerad** [comment]
Ylian,

I have added it into the config file but I'm still not seeing the ssh option in the terminal section.

***@***.***
***@***.***

**Comment by aislerad** [comment]
Added the section into the json.config but I'm still not seeing the option available under terminals.

![image](https://user-images.githubusercontent.com/105459613/171770437-934f2441-9fb8-4a19-9f34-00b80d255229.png)

![image](https://user-images.githubusercontent.com/105459613/171770493-4b422ea1-d1e4-4733-bd45-c9e85fbb1c7d.png)

**Comment by aislerad** [comment]
I do see the web-ssh option now but still not seeing it in the terminlas section.

**Comment by si458** [comment]
Plz try latest version 1.1.20, and reopen if ur still having issues
