### ISSUE TITLE
[Q] Possible to set devicename from client?

### ISSUE THREAD

**Issue by tiagogbarbosa** [Ylianst/MeshCentral#4075]
Is possible to set the device name from the client?
Like the file "meshagent.tag"?

Offline clients wont show TAGS in meshctrl.js... It shows 'undefined'

**Comment by tiagogbarbosa** [comment]
My bad. I was looking at node.tag...
The correct is node.agent.tag

**Comment by Ylianst** [comment]
Indeed it's possible. I have a video about agent tags, and in that video I talk about [advanced agent tags here](https://youtu.be/KPMtzzLWoK0?t=312).
