### ISSUE TITLE
Date of last connection of agent

### ISSUE THREAD

**Issue by Floche87** [Ylianst/MeshCentral#408]
Dear Ylianst,
Since approximatively 15 days, i no longer have the date of last connection in the "detailled view" of each computer.
When agent connected it is ok.
See screenshots
Thx

![Screenshot_20190807_180436](https://user-images.githubusercontent.com/51901584/62638903-b3f80e80-b93e-11e9-8df3-c308acbf9027.png)
![Screenshot_20190807_180749](https://user-images.githubusercontent.com/51901584/62638904-b3f80e80-b93e-11e9-8a68-436ac138e216.png)

**Comment by Ylianst** [comment]
That is weird, I see the last connected time on my server. I need to investigate this.

**Comment by Ylianst** [comment]
Can you click on the device's "Interfaces" link at the bottom of the device page and tell me if you see the last agent connected time? Thanks.

![x](https://user-images.githubusercontent.com/1319013/62647106-ad4ca580-b904-11e9-92f7-0fb6809b2355.png)

**Comment by Floche87** [comment]
In "Network Interfaces" it is ok.
![Screenshot_20190808_090759](https://user-images.githubusercontent.com/51901584/62682359-45599600-b9bc-11e9-9af3-fd4f7e471310.png)


I installed meshcentrak 0.3.9-k and I tested with firefox and chromium : same issue
Is there a server cache in Meshcentral ?
Thx

**Comment by Ylianst** [comment]
Well, "last agent connection" is not showing up for you. It would be interesting to see if the database has this data or not, but not something that is easy to figure out.

**Comment by ghplw** [comment]
Works okay for me as well but I currently only have Windows devices added where as both of the devices in Floche87s, examples appear to be Linux.

**Comment by Floche87** [comment]
@Ylianst if you explain me, i can try to see in my database. 
@ghplw at this time i have only computers under Debian. All have the same issue.

**Comment by Floche87** [comment]
I solved issue.
My nginx adds a content security policy (CSP headers) in sent pages which is too strict.
If i delete the rule, all is ok.
But security is less.
I will create a specific ticket about that.
