### ISSUE TITLE
BUG -  Server Crash when "Remember Credentials" is checked for "SFTP Connect" Button

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4080]
This is pretty straight forward. I can  connect just fine when using the "SFTP Connect" button on a Linux machine and NOT saving the credentials. 

If I check the "Remember Credentials" checkbox Meshcentral Server crashes and restarts automatically with the following in the server error log:

```
-------- 6/4/2022, 11:01:02 PM ---- 1.0.32 --------

TypeError: Cannot convert undefined or null to object
    at /opt/meshcentral/node_modules/meshcentral/apprelays.js:1165:25
    at /opt/meshcentral/node_modules/meshcentral/db.js:1584:29
    at /opt/meshcentral/node_modules/mongodb/lib/utils.js:530:9
    at /opt/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:244:32
    at /opt/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:484:55
    at /opt/meshcentral/node_modules/mongodb/lib/utils.js:530:9
    at /opt/meshcentral/node_modules/mongodb/lib/sessions.js:136:24
    at Object.maybePromise (/opt/meshcentral/node_modules/mongodb/lib/utils.js:516:5)
    at ClientSession.endSession (/opt/meshcentral/node_modules/mongodb/lib/sessions.js:133:24)
    at cleanupCursor (/opt/meshcentral/node_modules/mongodb/lib/cursor/abstract_cursor.js:530:32)
```

Thanks

**Comment by LPJon** [comment]
Here is an image with a little more info at the console"

<img width="597" alt="Untitled" src="https://user-images.githubusercontent.com/46533576/172034759-91ee6904-96f2-4344-982e-c597d7706e31.png">

**Comment by LPJon** [comment]
Also this was on Meshcentral versions 1.0.28 to 1.0.32 having the same issue

**Comment by Ylianst** [comment]
Thanks for reporting this and the detailed logs, I will fix this ASAP.

**Comment by Ylianst** [comment]
Just checked in a fix for this. Releasing MeshCentral v1.0.33 in a few minutes.

**Comment by Ylianst** [comment]
MeshCentral v1.0.33 released.

**Comment by LPJon** [comment]
Sorry took so long to get back to you on this. This is now working! Thanks again for all the hard work!
