### ISSUE TITLE
MeshCentral Assistant asking for update

### ISSUE THREAD

**Issue by kostyun** [Ylianst/MeshCentral#4082]
MeshCentral 1.0.33
On each run assistant asks to update if I click update then file with .update.exe extension created with same version of Assistant
File version of Assistant is 0.1.0.1
Looks like MeshCentral didn't update Assistant on server

**Comment by si458** [comment]
can you please try updating the server to 1.0.45 now as the exes have all been updated, and see if this issue still happens?
