### ISSUE TITLE
Recovery from backup fail with errors.

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#4085]
I'm trying to move MeshCentral to a new server.
I want it to run as user (not root).
The OS is Debian 11 with:
$ npm -v
7.5.2
$ nodejs -v
v12.22.5

npm and nodejs installed from default packages (by apt).

What i've done:
1 - Backup using MeshCentral GUI (archive is saved)
2 - install and start MeshCentral on new user using:
mkdir mesh
cd mesh/
npm install mesh
node ./node_modules/mesh
3 - Login with new account on new MC instance.
4 - Use recovery function and saved file.
The result in shell looks like that:

> /mesh$ node ./node_modules/meshcentral
WARNING: Agent hash checking is being skipped, this is unsafe.
MeshCentral v1.0.33, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on example.com:4433.
MeshCentral HTTPS server running on example.com:8081.
SMTP mail server mailserver.com working as expected.
Updating settings folder...
ERR: /home/user/mesh/node_modules/meshcentral/meshcentral.js:2047
                                    directory = obj.getConfigFilePath(directory)
                                              ^

> TypeError: Assignment to constant variable.
    at /home/user/mesh/node_modules/meshcentral/meshcentral.js:2047:47
    at /home/user/mesh/node_modules/yauzl/index.js:575:7
    at /home/user/meshl/node_modules/yauzl/index.js:631:5
    at /home/user/mesh/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
WARNING: Agent hash checking is being skipped, this is unsafe.
MeshCentral v1.0.33, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on example.com:4433.
MeshCentral HTTPS server running on example.com:8081.
SMTP mail server some.mailserver.com failed: {"code":"EAUTH","response":"535 5.7.8 Error: authentication failed: ","responseCode":535,"command":"AUTH PLAIN"}

After login there are no old users, groups or anything at all (only new created user is working). Only top left logo has changed from the previous installation.

**Comment by nicrame** [comment]
I've already done what You suggested on production box and it's working great.
Now i'm just testing that at VM.
Results:
[...]$ mkdir mesh
nicram@debian11:~$ mkdir mesh
nicram@debian11:~$ cd mesh/
nicram@debian11:~/mesh$ npm install meshcentral

added 145 packages, and audited 146 packages in 8s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
nicram@debian11:~/mesh$ node ./node_modules/meshcentral
Installing otplib@10.2.3...
MeshCentral HTTP redirection server running on port 1024.
Generating certificates, may take a few minutes...
Generating root certificate...
Generating HTTPS certificate...
Generating MeshAgent certificate...
Generating code signing certificate...
Generating Intel AMT MPS certificate...
MeshCentral v1.0.34, LAN mode.
Code signed agent MeshService.exe.
Code signed agent MeshService64.exe.
Server has no users, next new account will be site administrator.

WARNING: MeshCentral is running without permissions to use ports below 1025.
         Use setcap to grant access to lower ports, or read installation guide.

   sudo setcap 'cap_net_bind_service=+ep' `which node`

WARNING: Server running without permissions to use ports below 1025.
MeshCentral HTTPS server running on port 1025.
**--- this is moment when i click restore from backup file ----**
Updating settings folder...
Installing nodemailer...
WARNING: Agent hash checking is being skipped, this is unsafe.
Generating certificates, may take a few minutes...
Generating HTTPS certificate...
MeshCentral v1.0.34, Hybrid (LAN + WAN) mode.
ERR: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'nodemailer'
Require stack:
- /home/nicram/mesh/node_modules/meshcentral/meshmail.js
- /home/nicram/mesh/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.module.exports.CreateMeshMail (/home/nicram/mesh/node_modules/meshcentral/meshmail.js:46:28)
    at AsyncWrap.<anonymous> (/home/nicram/mesh/node_modules/meshcentral/meshcentral.js:1681:63)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nicram/mesh/node_modules/meshcentral/meshmail.js',
    '/home/nicram/mesh/node_modules/meshcentral/meshcentral.js'
  ]
}
Error: Command failed: /usr/bin/node /home/nicram/mesh/node_modules/meshcentral --launch 732
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'nodemailer'
Require stack:
- /home/nicram/mesh/node_modules/meshcentral/meshmail.js
- /home/nicram/mesh/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.module.exports.CreateMeshMail (/home/nicram/mesh/node_modules/meshcentral/meshmail.js:46:28)
    at AsyncWrap.<anonymous> (/home/nicram/mesh/node_modules/meshcentral/meshcentral.js:1681:63)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nicram/mesh/node_modules/meshcentral/meshmail.js',
    '/home/nicram/mesh/node_modules/meshcentral/meshcentral.js'
  ]
}

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/node /home/nicram/mesh/node_modules/meshcentral --launch 732'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
WARNING: Agent hash checking is being skipped, this is unsafe.
MeshCentral v1.0.34, Hybrid (LAN + WAN) mode.
MeshCentral Intel(R) AMT server running on mesh.itos.pl:4433.

WARNING: MeshCentral is running without permissions to use ports below 1025.
         Use setcap to grant access to lower ports, or read installation guide.

   sudo setcap 'cap_net_bind_service=+ep' `which node`
WARNING: Server running without permissions to use ports below 1025.
MeshCentral HTTPS server running on mesh.itos.pl:1024.
SMTP mail server localhost failed: {"errno":"ECONNREFUSED","code":"ESOCKET","syscall":"connect","address":"127.0.0.1","port":587,"command":"CONN"}

But the **files are restored correctly and after restart everything is working as expected**.

**Comment by dinger1986** [comment]
@si458 fixed can close
