### ISSUE TITLE
Bi directional clipboard support

### ISSUE THREAD

**Issue by Goldmaster** [Ylianst/MeshCentral#4087]
Hi there,

it can be quite annoying at times having to click to send or receive copied text content between both machines and so have to click to send or receive the clipboard. Why isn't there an option for bi-directional clipboard support? From what I have looked up, it's due to a security reason, so in that case, why isn't there an option in Firefox, to allow clipboard access? maybe some form of a firefox addon could be used to sync the clipboard between the remote device and the device is accessing. I did try the RDP option and even with the automatic clipboard enabled, no difference was made.

any ideas of when this would be fixed, please?

**Comment by Goldmaster** [comment]
Hi there, to solution is to simply got to `about:config` in firefox and then type `dom.events.asyncClipboard.dataTransfer`.

There should be the only option at the top, then just toggle so it says `true`

close and then reopen Firefox and browse to mesh central.

you should be able to copy and paste without issue.

**Comment by vstour** [comment]
That option does exist. If you click on "Settings" in the Desktop panel, you can see it:
![image](https://user-images.githubusercontent.com/106902044/173210595-0bddd143-9572-47f4-858c-5cbacba38885.png)

**Comment by yomono** [comment]
That option does exist:
![image](https://user-images.githubusercontent.com/31445936/173210666-92e36d23-39ff-4992-839b-c6f0a409df24.png)

**Comment by Catsrules** [comment]
> That option does exist: ![image](https://user-images.githubusercontent.com/31445936/173210666-92e36d23-39ff-4992-839b-c6f0a409df24.png)

It doesn't look like it works when using Firefox. 

I have that option when using Chrome but on Firefox Automatic Clipboard doesn't exist. 

The only way I can send clipboard text to the remote computer is with the Clipboard button at the bottom.

**Comment by calas80** [comment]
> > That option does exist: ![image](https://user-images.githubusercontent.com/31445936/173210666-92e36d23-39ff-4992-839b-c6f0a409df24.png)
> 
> It doesn't look like it works when using Firefox.
> 
> I have that option when using Chrome but on Firefox Automatic Clipboard option doesn't exist.
> 
> The only way I can send clipboard text to the remote computer is with the Clipboard button at the bottom.




 got to `about:config` in firefox and then type 

`dom.events.asyncClipboard.dataTransfer` and `dom.events.asyncClipboard.readText`

 then just toggle so it says true

**Comment by stefandbt** [comment]
Hi therem,

same issue here with Firefox and Chrome: No clipboard sync possible, even the box "Automatic Clipboard" is checked. 

Any Ideas? 

Server Version 1.1.14
Agent Version: 02-12-2022

**Comment by silversword411** [comment]
There's other issues that go over this and why with some workarounds. Search for them

**Comment by stefandbt** [comment]
Thanks for your comment Mr Silversword411. That's what I already did! But none of these "workarounds" did it for me.

The workarounds I have found:
* #4042: (where you also comented)
* #4087: Checked Firefox settings: see above: ok 

All other tickets refer to fixed bugs. Could you point me to the "workarounds" you are talking about?

**Comment by yomono** [comment]
Is your server using HTTPS with a valid certificate? I'm almost sure that they won't allow clipboard if there is no valid certificate

**Comment by stefandbt** [comment]
Hi,
  

  
The server is using HTTPS wirh a valid let‘s encrypt cert
  
  
  
Gruß  
Stefan
  
  
  
  

  
  
>

**Comment by albotroz** [comment]
I (actually Firefox user) tried it once on a test basis via the Edge browser and the bidirectional clipboard does not work.

It is possible to copy something from the clipboard in the remote computer, but not the other way around (when I copied text from remote computer and want to paste it in client-computer).

**Comment by si458** [comment]
im going to close this for the moment,
currently its implemented as intended for edge and chrome when you enable 'auto clipboard' under the 'settings' button
HOWEVER firefox is a law into its own, so doesnt work correctly

**Comment by mikeleblank** [comment]
Does this option currently work?
I checked it in Chrome and it only asked for permissions from the browser but it didn't work.

**Comment by yomono** [comment]
At least in Firefox, it's working just fine for me.. I checked about:config and these are the ones I edited apparently:
dom.events.asyncClipboard.clipboardItem
dom.events.asyncClipboard.readText	
dom.events.testing.asyncClipboard

**Comment by mikeleblank** [comment]
@yomono in the last version work on chrome yeaaah!

**Comment by silversword411** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

Requires secure context.

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

I think when you change that about:config   setting now any website you come across can snarf your clipboard.

Lots of good info in that clipboard...hope you don't leave the wrong web page open in the background with that code running.

**Comment by W1BTR** [comment]
This is still one-direction for me on chrome. Copying on the local machine sends it to the remote client, but copying on the remote client does not send it back. Valid https session. Has never worked on any meshcentral install for me.

**Comment by W1BTR** [comment]
Following up on this, this is still an issue on all browsers for me. Tried brave, tried firefox with the settings suggested. Tried edge, tried chrome. No matter what settings I get I cant get it to work. Chrome at least will send clipboard to the client, but not back.

This is the biggest flaw this has and keeps us going back to Supremo or Anydesk.

**Comment by cristianadrielbraun** [comment]
Honestly it always worked for me.. since day 1. But I still find it more reliable (or maybe it's just placebo) to click on the clipboard icons at the bar.. not ideal but switching back to another solution like anydesk JUST because you need to do an extra click seems... excessive

**Comment by W1BTR** [comment]
We need to have both installed for compliance anyway (telecom stuff), but since the other tools we use just do it, it's not the need to click the extra button as much as the extra time to go back and click the button when pasting doesnt work because we forgot it's broken on Meshcentral, or worse when we dont realize and paste an old value.

**Comment by si458** [comment]
@W1BTR random idea, use chrome/edge, click connect in remote tab, then press into full screen mode button top right,
Does the clipboard work both ways?

**Comment by ThomasW2005** [comment]
For us on Chrome it works bidirectionally, but in firefox only from client -> Browser, not from Browser -> client, very weird, it seems for everyone else it is the opposite.
Valid and trusted HTTPS certificate
