### ISSUE TITLE
Feature Request: add Scroll bar or folded menu to pre-typed menu

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4089]
HI @Ylianst,
by any chance can you make the pre-defined tying menu with a scroll function, as we have more than 30 pre-defined commands always comes handy to pre-type them during desktop session. also can the terminal Tab have the same pre-defined option available?

Thanks

![image](https://user-images.githubusercontent.com/70715469/172503748-822cf82e-1227-4ae5-a088-440b3d21e0d9.png)

**Comment by smartekIT** [comment]
Hi @Ylianst , Sorry to bother you about this, but I was hoping you look into this as it's been a long time. If it's a hard thing to do I can understand. Thanks heaps.

**Comment by Ylianst** [comment]
Working on it.

**Comment by Ylianst** [comment]
Ok, added scroll bar. Let me know if it's ok. Will be in MeshCentral v1.0.48.

![image](https://user-images.githubusercontent.com/1319013/177709870-6a5e55b5-0356-4207-b141-9e8d8a0b015d.png)

**Comment by smartekIT** [comment]
Thanks champion
