### ISSUE TITLE
Most agents windows stuck black screen terminal

### ISSUE THREAD

**Issue by itcuibap03** [Ylianst/MeshCentral#409]
After update Version 0.3.9-k
Almost agent of windows (64bit version) stuck when connect via terminal & Powershell

(Connected but display black screen)
![image](https://user-images.githubusercontent.com/16290386/62669258-2efe0b00-b9b9-11e9-9984-09b332458127.png)

**Comment by Ylianst** [comment]
This is not good. I am not seeing this on my servers however, the latest MeshCentral server updates have come with updates to the MeshAgent. I suspect that when a MeshAgent update occurs, this sort of thing seems to happen. Can you confirm that is the agent is restarted, it starts working correctly?

**Comment by itcuibap03** [comment]
I confirmed not working when agent restart or -fullunsinstall and -fullinstall agent

I'm reinstall new server and same result (Terminal & Powershell)

Button restart cannot appear as you tweet on twitter
![image](https://user-images.githubusercontent.com/16290386/62675007-2c0e1500-b9cf-11e9-8479-4482c1cfbac3.png)


Thank you MeshCentral - Best Solution replace Teamviewer / Netsupport

**Comment by Ylianst** [comment]
Your right! I am not seeing the restart button on 0.3.9-k. I will fix this today.

For the terminal, Bryan and I are not seeing this issue, but I will test some more.

**Comment by Ylianst** [comment]
FYI. Published MeshCentral v0.3.9-l with the "restart" button fixed.

**Comment by Ylianst** [comment]
Bryan just made me realize that if you open two Terminal sessions from different browsers on Windows, the second one will be black. This is because the agent does not support two terminal sessions on Windows. We need to display a message to make it clear this is what is happening.

**Comment by itcuibap03** [comment]
Thank you Ylianst

Button Restart is working 0.3.9.5
Powershell & Terminal is not working, one session from windows 
Here is console error
![image](https://user-images.githubusercontent.com/16290386/62743067-34b42900-ba6b-11e9-9d78-9d5288fd0991.png)

Module Win-Terminal, Win Info not found

**Comment by krayon007** [comment]
If it says win-info is not found, that means the server configuration is probably messed up. win-info.js is supposed to be packaged up with the meshcore.js file before being sent to the agent. If I were to venture a guess, I'm thinking Ylian forgot to minify this file, as I remember he said that the server will prefer to use the minified modules. I'm sure @Ylianst  will pipe up....

**Comment by Ylianst** [comment]
At the agent console, can you type "info" and send back the result? Any modules that start "win-" are not loaded on non-windows machines. I just fixed a problem with "sysinfo" on Linux that incorrectly used "win-info". Maybe I can track down the rest.

**Comment by itcuibap03** [comment]
Here is agent console 
![image](https://user-images.githubusercontent.com/16290386/62813718-88d80f80-bb36-11e9-959e-5b205ecf21ab.png)

**Comment by itcuibap03** [comment]
Windows 10 , 64 bit but info display platform 32

**Comment by krayon007** [comment]
That line in the console is the output of process.platform. That will show win32 for all windows platforms. The output of os.arch() will show x64 for 64 bit Windows.

**Comment by itcuibap03** [comment]
Got it. Thank you Bryan

**Comment by itcuibap03** [comment]
Fixed with verson 0.3.9-q
But powershell auto disconnect after 3s~5s, terminal is ok

**Comment by Ylianst** [comment]
Thanks. We will take a look at PowerShell.

**Comment by krayon007** [comment]
@itcuibap03 what build number of Windows 10 are you running?

**Comment by itcuibap03** [comment]
@krayon007 Hi Bryan
All Windows Computer : 64bit 

Microsoft Windows [Version 10.0.17763.615] ==> Auto Disconnect
Microsoft Windows [Version 10.0.17134.829] ==> Auto Disconnect

Microsoft Windows [Version 6.1.7601] - Windows 7 ==> OK
Microsoft Windows [Version 6.3.9600] - Server ==> OK

**Comment by JSDA123** [comment]
My experience, in case it helps:  I'm a new user (and fan) of MeshCentral starting with beta 2, so using the latest agent from the start, no updates.

Black screen on:  Windows7, Windows Server 2012 R2, Ubuntu 18.04

Works perfectly:  Windows 10 Pro

**Comment by krayon007** [comment]
For that Ubuntu 18.04 case, do you have user consent enabled? That XAUTHORITY/DISPLAY thing, looks like it's trying to determine what settings to use to connect to the Xorg server, but that is not possible on 18.04 if no users are logged in.  

I'll double check to make sure the user consent error shows up correctly on terminal, I did most of the testing for that with KVM.

**Comment by JSDA123** [comment]
User consent is disabled.  And yes, the black screen only happens when no users are logged in, otherwise works as expected. 

I can also see the desktop when the lock screen is active, as long as a user is logged in. That satisfies most use cases (except a server) and is very useful.  Thanks for this great project.

**Comment by mrflaunted** [comment]
Running an agentless meshcentral environment via NPM and we are seeing the same black screen issue when we attempt to connect from the desktop tab or when directly connected via the intel AMT tab.

I am able to move the mouse around and send keyboard commands.

I have upgraded to the latest 0.4.0-k

User consent is disabled.

**Comment by CCWTech** [comment]
We are having the same black screen issues. Any fixes yet?

**Comment by krayon007** [comment]
Can you describe your problem scenario? This thread took a lot of detours along the way... More precisely, what server version are you running, what build of windows are you running, and what are the steps to reproduce? (And do you have user consent enabled, and are any users currently logged in)

**Comment by CCWTech** [comment]
> After update Version 0.3.9-k
> Almost agent of windows (64bit version) stuck when connect via terminal & Powershell
> 
> (Connected but display black screen)
> ![image](https://user-images.githubusercontent.com/16290386/62669258-2efe0b00-b9b9-11e9-9984-09b332458127.png)

Same thing as mentioned here. Let me check server version. I'm on Ubuntu and going into a Server 2019 Std machine, but also issues with remoting into Windows 10.

**Comment by CCWTech** [comment]
0.5.1-k is what we are on.

**Comment by krayon007** [comment]
If you type osinfo in the console tab, what does it say about ConPTY status?

**Comment by CCWTech** [comment]
"Yes"

**Comment by krayon007** [comment]
Does the user-shell exhibit the same problem, or just the admin-shell? And what is the full install path of your agent? I ask, because I use the windows task scheduler to spawn the child process for the terminal. I found that on Windows 7, the task scheduler misparsed the path if there were spaces in it, so I fixed that. I haven't tested for other special characters, so was curious what your full install path is, since that is the path I give to the Windows Task Scheduler.

**Comment by scottalanmiller** [comment]
> We are having the same black screen issues. Any fixes yet?

We've not had this issue for the past year.  The issue of THIS thread was resolved.  If a new issue has cropped up, this thread is the wrong place to report it.

**Comment by scottalanmiller** [comment]
> Does the user-shell exhibit the same problem, or just the admin-shell? And what is the full install path of your agent? I ask, because I use the windows task scheduler to spawn the child process for the terminal. I found that on Windows 7, the task scheduler misparsed the path if there were spaces in it, so I fixed that. I haven't tested for other special characters, so was curious what your full install path is, since that is the path I give to the Windows Task Scheduler.

We are on the same server.  All installs are the default path, it's never modified.  We're trying to find one of the machines having an issue.  So far it hasn't been reproduced so I'm not sure if it is happening or just a momentary issue the other day.  It never happened broadly.  If we see it crop up, we'll open a new thread with details.

**Comment by dinger1986** [comment]
appears to be fixed as per above comments @si458

**Comment by si458** [comment]
closing as stale but also seems to be fixed as no reported issues recently 2023
