### ISSUE TITLE
Feature Request: Use Markdown to render rich text formatting in node notes.

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#4091]
Hi Ylianst,

When on the General Tab on my FHD Screen, there is a big empty space between the " Group / OS Name" table on the left and the icon on the right. I thought it would be nice to have the "Notes" displayed there scrollable and read only. Keep the "Notes" button to edit the contents.

Additionally it would be nice to use Markdown (or similar) to render rich text formatting in node notes.

If possible, it would be nice to be able to add in some Mesh Central specific syntax to create custom MeshCentral Router links similar to the RDP, HTTP, HTTPS links but can be custom.  Something like {Protocol}://{meshID}:{port}/ e.g. the standard HTTP link equivilent http://{meshID}:80/

I think this would help for those people that have some devices with custom port apps that don't apply to all machines in mesh central.

**Comment by silversword411** [comment]
> If possible, it would be nice to be able to add in some Mesh Central specific syntax to create custom MeshCentral Router links similar to the RDP, HTTP, HTTPS links but can be custom. Something like {Protocol}://{meshID}:{port}/ e.g. the standard HTTP link equivilent http://{meshID}:80/

Isn't that what meshCmd is all about?
https://ylianst.github.io/MeshCentral/meshcmd/#meshcentral-tcp-port-mapping

**Comment by b8two** [comment]
@silversword411 
In a way, I was refering more to how **deviceMeshRouterLinks** feature that applies system wide;
https://github.com/Ylianst/MeshCentral/issues/3911
to have more of a single device customization.

meshCmd is a console app that creates port maps.
MeshRouter is a nice GUI app that also creates port maps and has linked calls with Mesh Central web GUI 

deviceMeshRouterLinks  feature allows additional Web GUI links to be shown on the Mesh central web to configure MeshRouter.

Above was a suggestion of extending this.

**Comment by si458** [comment]
this was added recently in a PR, should already be available in latest release, if not next release,
you can enable it using `showNotesPanel: true` listed under your domain,
sorry its not markdown language, but text notes is good!

**Comment by si458** [comment]
i am just reopening this as i was looking into the markdown feature
is this still required, as ive experimented with [markedjs](https://github.com/markedjs/marked) and achieved this!
![image](https://github.com/user-attachments/assets/abc19bff-d9ff-441e-9074-b87ab553d098)
![image](https://github.com/user-attachments/assets/5d78f17b-0120-4935-9750-b66b24bad07a)

**Comment by b8two** [comment]
I've just enabled showNotesPanel: true in my config and it works as expected.

I would like the mark up as some devices I look after have URLs to access, this will allow them to be listed and linked.

**Comment by si458** [comment]
@b8two thats ok im looking into it now as this is exactally what https://github.com/Ylianst/MeshCentral/issues/6332 wanted!

**Comment by si458** [comment]
this ok? the textbox is scrollable!
![image](https://github.com/user-attachments/assets/4bfcd2ec-6efe-439e-804e-5019d41074d6)

**Comment by si458** [comment]
added for you!
will be in latest docker developer build or github builds for testing
`ghcr.io/ylianst/meshcentral:master` or `npm install Ylianst/MeshCentral` (remember no translations in npm build)
or wait until next release

**Comment by b8two** [comment]
Excellent,  My deployment is in Docker, so I'll try to update with the next release that is tied in with image: Typhonragewind/meshcentral-docker

**Comment by si458** [comment]
you really should be using the offical docker image as its practially identical `ghcr.io/ylianst/meshcentral`
and you can even test the development builds with `master` tag

**Comment by b8two** [comment]
@si458 I've updated my docker to the official image. I don't think I found the image back in April when I was converting across from a native install to docker.

Also, one minor update to this mark up, can the links open to a new tab / window?

**Comment by si458** [comment]
Sorry for the delay, erm. I'm not sure I'll have to check this?

**Comment by si458** [comment]
@b8two ok so the standard markdown url links DONT use `_blank` to open links in a new page
if you wanted this feature, we would have to integrate a render to open links in a new page
im also not sure if this should be standard or not?

**Comment by si458** [comment]
@b8two better late than never! https://github.com/Ylianst/MeshCentral/commit/fc83211e907215dd32352d2a591ee6f0874890dd
the notes links will now open in a new tab instead!
