### ISSUE TITLE
Error upgrading from 1.0.33 to 1.0.34

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#4097]
Running with nginx/1.21.6 as reverse proxy

Starting self upgrade to: 1.0.34
node[880]: Update completed...
node[880]: Cleaning NPM cache...
node[880]: MeshCentral HTTP redirection server running on port 800.
node[880]: MeshCentral v1.0.34, Hybrid (LAN + WAN) mode, Production mode.
node[880]: MeshCentral Intel(R) AMT server running on example.com:44330, alias port 4433.
node[880]: MeshCentral HTTP server running on port 4430, alias port 443.
node[880]: Loaded web certificate from "https://127.0.0.1:443/", host: "example.com"
node[880]:  SHA384 cert hash: xxxxx
node[880]:  SHA384 key hash: xxxxx
node[880]: ERR: TypeError: parent.crypto.randomInt is not a function
node[880]:    at getRenderArgs (/meshcentral/node_modules/meshcentral/webserver.js:7701:116)
node[880]:    at handleRootRequestLogin (/meshcentral/node_modules/meshcentral/webserver.js:3045:13)
node[880]:    at handleRootRequestEx (/meshcentral/node_modules/meshcentral/webserver.js:2901:13)
node[880]:    at handleRootRequest (/meshcentral/node_modules/meshcentral/webserver.js:2604:13)
node[880]:    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5)
node[880]:    at next (/meshcentral/node_modules/express/lib/router/route.js:137:13)
node[880]:    at Route.dispatch (/meshcentral/node_modules/express/lib/router/route.js:112:3)
node[880]:    at Layer.handle [as handle_request] (/meshcentral/node_modules/express/lib/router/layer.js:95:5)
node[880]:    at /meshcentral/node_modules/express/lib/router/index.js:281:22
node[880]:    at Function.process_params (/meshcentral/node_modules/express/lib/router/index.js:335:12)

**Comment by rowds15** [comment]
After reading the issue #4084 
I needed to add the "webPageLengthRandomization": false, in the config and then was able to update.

**Comment by rebootcs** [comment]
Same issue - Are you saying the fix was to change this line -    // To mitigate any possible BREACH attack, we generate a random length string here.
        xargs.randomlength = (args.webpagelengthrandomization !== false) ? parent.crypto.randomBytes(parent.crypto.randomInt(0, 256)).toString('base64') : '';

**Comment by rebootcs** [comment]
That upgrade error is fully noted in the log as:
TypeError: parent.crypto.randomInt is not a function
    at getRenderArgs (/root/meshcentral/node_modules/meshcentral/webserver.js:7701:116)
    at handleRootRequestLogin (/root/meshcentral/node_modules/meshcentral/webserver.js:3045:13)
    at handleRootRequestEx (/root/meshcentral/node_modules/meshcentral/webserver.js:2901:13)
    at handleRootRequest (/root/meshcentral/node_modules/meshcentral/webserver.js:2604:13)
    at Layer.handle [as handle_request] (/root/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /root/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/meshcentral/node_modules/express/lib/router/index.js:335:12)

**Comment by rowds15** [comment]
the workaround is to put "webPageLengthRandomization": false, in the settings section of the config

**Comment by rebootcs** [comment]
Confirmed - working.

**Comment by openncomp** [comment]
Strange, I have updated normally without changing the config.
Updated from version 1.0.33 to 1.0.34.

After the update, I added the line to the config:
"webPageLengthRandomization": true
MC2 server also works for Nginx proxy.

Do I understand correctly that "webPageLengthRandomization": false - disables randomization and for better security the value should be "true"?

**Comment by nikitauchaev** [comment]
Unfortunately, adding an option "webPageLengthRandomization": false, to the config did not help me

After the update from version 1.0.2 to version 1.0.34 errors in mesherrors.txt


/opt/meshcentral/node_modules/meshcentral/authenticode.js:198
            obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24);
                                                           ^

TypeError: optinalHeader.readBigUInt64LE is not a function
    at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:198:60)
    at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:1061:13)
    at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2905:68)
    at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13)
    at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21
    at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43)
    at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35)
    at Server.<anonymous> (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13)
    at Object.onceWrapper (events.js:286:20)

**Comment by nikitauchaev** [comment]
I have already tried to install node from the official repository, the last available branch
But at the start of the application, there was a complaint in the log about the absence of libnode64. Installing this package, in the process of resolving dependencies, removed the latest version of the node and the problem returned.

**Comment by jimmyjblake** [comment]
> Unfortunately, adding an option "webPageLengthRandomization": false, to the config did not help me
> 
> After the update from version 1.0.2 to version 1.0.34 errors in mesherrors.txt
> 
> /opt/meshcentral/node_modules/meshcentral/authenticode.js:198 obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24); ^
> 
> TypeError: optinalHeader.readBigUInt64LE is not a function at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:198:60) at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:1061:13) at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2905:68) at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13) at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17) at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21 at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43) at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35) at Server. (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13) at Object.onceWrapper (events.js:286:20)

My installation is erroring at the same place too.  If it helps any, I'm using Ubuntu 20.04 on AWS, and auto updates are enabled for both the Ubuntu/apt side and for Mesh Central.

**Comment by setupinf** [comment]
I have 2 installations, one updated without error, the other had the error and was solved by adding "webPageLengthRandomization": false
Really strange.

**Comment by nicrame** [comment]
Try to upgrade Your nodejs version. I think v12 is the minimum You need.

**Comment by abjoseph** [comment]
Confirmed, upgrading my nodejs version from 10.x to 12.x fixed the error without needing to set "webPageLengthRandomization": false. I had applied this workaround yesterday after trying to upgrade from 1.0.1 to 1.0.34

**Comment by warlord1312** [comment]
> Unfortunately, adding an option "webPageLengthRandomization": false, to the config did not help me
> 
> After the update from version 1.0.2 to version 1.0.34 errors in mesherrors.txt
> 
> /opt/meshcentral/node_modules/meshcentral/authenticode.js:198 obj.header.peWindows.imageBase = optinalHeader.readBigUInt64LE(24); ^
> 
> TypeError: optinalHeader.readBigUInt64LE is not a function at openFile (/opt/meshcentral/node_modules/meshcentral/authenticode.js:198:60) at Object.createAuthenticodeHandler (/opt/meshcentral/node_modules/meshcentral/authenticode.js:1061:13) at Object.CreateMeshCentralServer.obj.updateMeshAgentsTable (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:2905:68) at Object.CreateMeshCentralServer.obj.StartEx4 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1620:13) at Object.CreateMeshCentralServer.obj.StartEx3 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1568:17) at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:1480:21 at Object.obj.GetMeshServerCertificate (/opt/meshcentral/node_modules/meshcentral/certoperations.js:986:43) at CreateMeshCentralServer.obj.StartEx2 (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:1477:35) at Server. (/opt/meshcentral/node_modules/meshcentral/redirserver.js:143:13) at Object.onceWrapper (events.js:286:20)

Same for me.

**Comment by OutbackMatt** [comment]
> Try to upgrade Your nodejs version. I think v12 is the minimum You need.

Thanks - solved for me

**Comment by granad2002** [comment]
I am on the latest nodejs version, but the problem is still there.

**Comment by Ylianst** [comment]
Just published v1.0.36 with a fix for this. Also, a workaround it to add:

```
"webPageLengthRandomization": false
```

In the settings section of the config.json. You can then update and remove that line.

**Comment by Ylianst** [comment]
Apologies for everyone, I should have tested this on older NodeJS.

**Comment by rowds15** [comment]
I can confirm that i was running node js version 12.18.3, updated to v1.0.36 and with and without "webPageLengthRandomization": false now working

**Comment by saschawj** [comment]
had 12.18.3 and it wasn't working .. upgraded to v16.15 and it now doesn't even start..
