### ISSUE TITLE
Copy\Paste to and from client

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#41]
Need to be able to copy text to and from the client for executing large commands remotely

**Comment by dmccracken-livewire** [comment]
I agree

**Comment by rodrigo-hissam** [comment]
Implementing copy/paste for the desktop tab like you have done for the terminal tab would be super useful indeed.

**Comment by jcam7044** [comment]
I agree as well.

**Comment by whalehub** [comment]
@Ylianst Are there any plans on implementing this feature?

**Comment by krayon007** [comment]
I'm actually testing this feature now. Working on getting it working on Linux, so we can release support for windows and Linux at the same time.

**Comment by krayon007** [comment]
I got it working tested for Windows and Linux... I pushed the agent changes to GIT, and gave Ylian the necessary changes for the webapp to use it... Should be released soon...

**Comment by whalehub** [comment]
@krayon007 Awesome work! Can you push this in an update @Ylianst?

**Comment by krayon007** [comment]
By the way, on Linux, I put a 60 second timeout on the clipboard object, because unlike windows, Linux doesn't copy any memory to hold the clipboard contents, so I put a 60 second timeout on the clipboard object before I dereference it, so if you need to paste the same contents again after 60 seconds, you'll need to "resend" the clipboard from the browser. Windows doesn't have this issue, because the OS copies the clipboard contents.

**Comment by Ylianst** [comment]
Working on it.

**Comment by Ylianst** [comment]
Just published @MeshCentral v0.3.0-m with clipboard transfer support for Windows and Linux. Large and very difficult work done by [Bryan](https://github.com/krayon007) to get this working on so many platforms. Linux is especially difficult. No MacOS support yet. Testing and feedback appreciated.

![MC2-Clipboard2](https://user-images.githubusercontent.com/1319013/54462811-3bde4180-472e-11e9-8203-f416f42475d2.png)

**Comment by whalehub** [comment]
@Ylianst @krayon007 Thanks for your hard work!

**Comment by Ylianst** [comment]
Thanks. I am going to close this one. Please open a new issue if anything comes up.
