### ISSUE TITLE
Invite link for Macos / safari : wrong extension / file type.

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#410]
Hi, just tested mac os support : 

On 2 macs (mine high sierra other unknown but recent).. Meshcentral 0.3.9-k

using safari to DL via invite link : get a file named meshagent.dms. MacOs canot open this file.

Using safari with direct link "add agent" : dl a meshagent.mpkg, crtl click opens installer. ok

Using chrome : via invite link got a text file, meshagent no extension.

chrome via add agent : zip file OK with installer mpkg ok.

Voilà...

**Comment by Ylianst** [comment]
Thanks for the report, I will look into this.

**Comment by tranbert** [comment]
Fine... 

Btw, thank's for the job, I'm switching from logmein rescue / itarian-comodo one and its a real pleasure to work with MeshCentral...!

**Comment by Ylianst** [comment]
Thanks for reporting this. Published MeshCentral v0.3.9-l with a fix for this. Let me know if this works for you.

**Comment by tranbert** [comment]
Safari invitation  ok mpkg downloaded

Chrome invitation : ok zip downloaded, mpkg inside.

OK for me. 0.3.9-m

**Comment by Ylianst** [comment]
Thanks!
