### ISSUE TITLE
TypeError: parent.crypto.randomInt is not a function

### ISSUE THREAD

**Issue by bharms1981** [Ylianst/MeshCentral#4102]
Just this morning i tried to get onto mesh and I am getting the error: 
TypeError: parent.crypto.randomInt is not a function at multiple locations in node_modules/meshcentral/webserver.js 
AWS EC2 server. 
I'm having issues updating node on ec2. Do you know commands to type to update to node v14?

**Comment by si458** [comment]
@bharms1981 if ubuntu or debian try this
https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

**Comment by bharms1981** [comment]
Just FYI. I've switched to node v14.19.3 and I still get the same error.

**Comment by Ylianst** [comment]
Just published v1.0.36 with a fix for this. Also, a workaround it to add:

```
"webPageLengthRandomization": false
```

In the settings section of the config.json. You can then update and remove that line.

**Comment by saschawj** [comment]
It fixed it initially then seems to reload and create the same error again on my system. never get to log in to do a update.

**Comment by granad2002** [comment]
For everyone that has the same problem as me when updating node doesn't solve the problem: I had more than one node installed on my system and meshcentral never used the updated node but another node which wasn't updated.

So, take a look which node your meshcentral is using...

**Comment by m0unds** [comment]
Bumping my MC server (running Ubuntu LTS 20.04) to the current Node LTS version (16) fixed the issue without using the config workaround.
