### ISSUE TITLE
Comparing meshcentral-config-schema.json and sample-config-advanced.json

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#4104]
Trying to clean stuff up a bit and make sure there aren't missing things. I did do some rearranging of items in the `sample-config-advanced.json` in this commit:

https://github.com/silversword411/MeshCentral/commit/357c96eba444a4450f9af24051c42f87705f9255

Here's some things I found. I can't find these items in ` meshcentral-config-schema.json` can you add them as appropriate?

```
exactPorts
```

`amtManager` doesn't seem to line up? Should there be other info as well?

For now I'm going to stop at: `"_allowHighQualityDesktop":` in the `sample-config-advanced.json` as I might be doing work for nothing.

**Comment by Ylianst** [comment]
This is wonderful, thank you so much for working on that. I did not intend to have `sample-config-advanced.json` be a complete config, just a really advanced one... but making it more complete is certainly welcome.

**Comment by silversword411** [comment]
I'll keep going then! :)

Really just trying to make sure items that might be useful aren't missed.

**Comment by Ylianst** [comment]
Thank you. As one could imagine, I am overwhelmed with requests, so any help is appreciated and your doing wonderful. I worked a full day yesterday and then started again at 9pm until 6am on breaking apart Windows executable (The authenticode-js resource improvement). Seeing you and others help out motivates me a lot. Thanks.
