### ISSUE TITLE
Feature Request : Cursor synchronization

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshCentral#411]
It is the issue duplicated with #28 . But it can't solved, so I want to reopen it. 
Both local side and remote side(Mesh Agent) are windows. The local cursor and remote mouse cursor can not be synchronized. For example, if you place the mouse at the end to resize the remote window, the mouse cursor will not change, making it difficult to resize the window. 

![image](https://user-images.githubusercontent.com/3539914/62700407-cb0d2e00-ba1c-11e9-9736-2ef4351cb32d.png)

**Comment by Ylianst** [comment]
Yes, this is a good ask. Bryan needs to be able to send to the remove desktop viewer the current cursor, if the can be done, it would be wonderful.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-a with cursor synchronization for Windows. This is thanks to Bryan (@krayon007) who did a lot of work to get this done, it's 100% this work and code. Bryan is working on getting the same on Linux.

**Comment by hchkim** [comment]
Thank you very much. I'll check it. :)

**Comment by krayon007** [comment]
MeshCEntral v0.4.1-f has been published, which adds Mouse cursor synchronization to Linux and FreeBSD in addition to Windows.

**Comment by Ylianst** [comment]
Bryan is amazing! Getting the mouse cursor feature to work on so many Linux distributions is great. Makes the remote desktop so much better to use.

![MC2-MouseCursor2](https://user-images.githubusercontent.com/1319013/65547529-7c352e00-dece-11e9-9a99-48cbb889d461.png)

**Comment by Ylianst** [comment]
Going to close this one as the feature is done. Please open an issue if there are any issues with this.
