### ISSUE TITLE
Move MC to new server failing: agent connected with invalid domain/mesh

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#4110]
I'm trying to move MeshCentral to a new server.
I've tried various versions of meshcentral-data folders, same result.
I have an older version of the data folder from Feb 22 & that works.

What bone-headed thing am I doing wrong?

The OS is Ubuntu 20.04 with MongoDB:
$ npm -v
8.11.0
$ nodejs -v
v18.3.0

>> Jun 10 15:12:03 mc2 node[4740]: Agent connected with invalid domain/mesh, holding connection

**Comment by FATeknollogee** [comment]
What’s the proper step to move MongoDB from Server A to Server B since the video doesn’t quite touch on that?

Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by VINISHVV** [comment]
@FATeknollogee

Please run below command to restore the mongodb backup/archive

mongorestore --archive=mongodump-2021-09-10-16-43.archive

**Comment by FATeknollogee** [comment]
Ok, I managed to fix most of my self-inflicted problems, since the old server was on an old os - Fedora 29.

I downgraded MC to `npm install meshcentral@1.0.33`
I also installed mongodump `mongodump --archive=backup.archive`

I restored the archive on the new server.

I have a new problem: I can only connect to the new server by IP addr not by name, browser complains about "Your connection is not private" & "Certificate is not valid"

**Comment by FATeknollogee** [comment]
I'm going to try this [https://github.com/Ylianst/MeshCentral/issues/2600#issuecomment-834998793](url)

**Comment by FATeknollogee** [comment]
After trying #2600 (prev post), I still can't connect via FQDN:

NET::ERR_CERT_AUTHORITY_INVALID
Certificate not valid

**Comment by FATeknollogee** [comment]
Any ideas why connect via FQDN is failing (vs IP address working)?

**Comment by LPJon** [comment]
Okay, are you using a load balancer?
