### ISSUE TITLE
Public Server Verify Email

### ISSUE THREAD

**Issue by aeolius** [Ylianst/MeshCentral#4112]
Public Server Verify Email is not sending any verification email.

**Comment by OutbackMatt** [comment]
What are your smtp server settings??

**Comment by Ylianst** [comment]
By public server you mean https://meshcentral.com? If so, I will check on that when I get back on Monday.

**Comment by xsfecho** [comment]
I have the same problem on the public server

**Comment by marcosmas28** [comment]
Hi, I have the same problem. I don't receive the verification email from the public server (https://meshcentral.com).

**Comment by Ylianst** [comment]
Ok, switched to "[meshcentral@yahoo.com](mailto:meshcentral@yahoo.com)" as the mail box for MeshCentral.com, let me know if it works.

**Comment by marcosmas28** [comment]
Almost an hour waiting for the verification email but nothing yet...

**Comment by xsfecho** [comment]
Waited for 10 minutes and did not receive the checked trash can

**Comment by Ylianst** [comment]
Yahoo just killed my email account and I can see why. People have been enabling device connection notification and causing MeshCentral to send out lots of emails. I need to disable device notifications on the public server and re-enable this feature.

**Comment by Ylianst** [comment]
Ok, the public server's email should be back up and working again.

**Comment by si458** [comment]
this is fixed and the issue can be closed

**Comment by dinger1986** [comment]
@si458 can close
