### ISSUE TITLE
Documenting meshcentral commandline arguments 

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#4116]
I noticed you use a commandline to launch meshcentral of `user admin`
https://youtu.be/alknFiojQPM?t=74

Trying to find that in the docs, all I see about meshcentral commandline is:

https://github.com/silversword411/MeshCentral/blob/master/docs/docs/meshcentral/index.md#running-state-less

I think this is your help printout which is missing much of the other items:
https://github.com/Ylianst/MeshCentral/blob/4e02fd1629646499da03a0b6adc7aef21d3174c9/meshcentral.js#L146

...and it looks like you're checking for all possible valid parameters here:
https://github.com/Ylianst/MeshCentral/blob/4e02fd1629646499da03a0b6adc7aef21d3174c9/meshcentral.js#L140

All valid items kind of looks like all the items in the json config file. 

I was going to try and write up some better consistent information, but maybe you might be better at doing that?

**Comment by Ylianst** [comment]
Indeed, MeshCentral has a lot of command line options and they are not all documented. The current `--help` shows the essential ones (shown below), but I have a lot I use for development and debugging that I don't know if they are that useful to everyone.

In general, doing `--option value` is the same as adding `"option": value` in the settings section of the config.json. So, there are just too many command line options to list. If you think I am missing any essential ones, I am certainly welcoming any changes.

```
MeshCentral v1.0.36, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcommander.com/meshcentral2

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --nedbtodb                        Transfer all NeDB records into current database.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.
```

**Comment by silversword411** [comment]
I guess we can start here

https://github.com/Ylianst/MeshCentral/commit/10fc9ba2bc71ca634203b5fd06cb8337dcf3edb2

but I would like to document all options and what they do. More information is always better :)

I'll probably just use this as the master list: https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json
