### ISSUE TITLE
Backup using WebDAV throws an error, if directory not exists

### ISSUE THREAD

**Issue by wdlut** [Ylianst/MeshCentral#4118]
I'm running the latest version of MeshCentral fom github.

The auto-backup feature is configured to use WebDAV as backup device.
When the upload folder "folderName" from the WebDAV configuration not exists, I get the error message:
> autobackup
Starting auto-backup...
Auto-backup completed.
Attempting WebDAV upload...
WebDAV (createDirectory) error: TypeError: Cannot read property 'statusText' of undefined

on the MeshCentral server console and the backup is not uploaded.
The upload folder on the WebDAV drive has been created and the second call of "autobackup" on the MeshCentral server console is sucessfull.

The code is in db.js:2425. The variable _a_ is undefined. I'm a newbie to Java. Could it be, that the resolve function of the promise client.createDirectory() does not have a parameter...

**Comment by si458** [comment]
plz can you follow the bug template in the future as you are missing information that is required for us to help you

**nodejs version**
**meshcentral version**
**server operating system**
