### ISSUE TITLE
BUG - When trying to sign exe's with authenticode.js I get an error stating the certificate and/or key could not be read!

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4119]
**Describe the bug**
When I try to use the certs and key.pem file you talk about in your video tutorial [here](https://www.youtube.com/watch?v=qMAestNgCwc) I get the error from your authenticode.js stating the certificate and/or key could not be read. 

**To Reproduce**
1. Generate your Cert chain and private key files from a .PFX file using openssl on Windows 10
2. Use Openssl to remove the passphrase from your key file and converting it to RSA format
3. Combine the private key certificate and your public certifiicates with the chain into a single .pem file in the format you specified begining with your public certificate, your private key, and then your chain.
4. copy the new cert and key.pem file to your Meshcentral Server instance. Then run your standard sign command with authenticode.js
5. Now you get the error, authenticode.js then generates a test cert and key then finishes with a self-signed cert (Not what we want).

**Expected behavior**
Should fail the signing completely in this type of failure. Should be able to read the .pem file without issues because his is a standard format pem file created with Openssl.

**Screenshots**
Don't have any at the moment. 

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: XCP-ng
 - Network: LAN/WAN Hybrid Mode with Reverse Proxy and SSL Offloading
 - Version: 1.0.36
 - Node: 12.20.0
 - Browser: Firefox

**Additional Context**
I initially went hunting this down because when I attempted to use the "agentsigningcert.pem" in meshcentral-data I lost my already signed agents as well. This is because in the `agents` folder I still had files named with the`-signed.exe`.  It is now required NOT to have that in order for it to work. For example the file name should be `MeshService64.exe` and NOT `MeshService64-signed.exe`. This change caused some confusion for me because I didn't find it documented and a clue about it was in your tutorial video referenced above where you copied files from the `signedagents` folder to the `agents` folder without adding the `-signed` to the files.

I really want to use this autosign feature to reduce my maintenance load of this server and it just does it for me when I run the upgrades. I also talked with my cert resellers tech on how to get this formatting correct and bring his 25+ years expertise to bear on this and he was stumped. So I'm not sure if I'm doing something wrong or if this is an actual bug.

**Comment by si458** [comment]
i ran into this issue too,
my private key was generated on windows with use `BEGIN PRIVATE KEY` and openssl needs `BEGIN RSA PRIVATE KEY`
you can convert your private key to rsa private key using `openssl rsa -in server.key -out server_new.key`

**Comment by LPJon** [comment]
@Ylianst Just to add an additional note here. I didn't actually need to convert the private key. All I had to do was add the `RSA` to the tags in the `.key` file and everything worked fine. That is why I suggested adding the consideration for the
`-----BEGIN PRIVATE KEY-----` tag lines.

**Comment by LPJon** [comment]
Related to this issue [#2](https://github.com/Ylianst/Authenticode-JS/issues/2) of authenticode.js
