### ISSUE TITLE
Feature Request - Authenticode.js Timestamping

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4121]
It would be awesome if when an `agentsigningcert.pem` is given in the `meshcentral-data` folder that when MeshCentral server signs the agents it also signed a timestamp with it. From what I understand from KSign (My Cert Reseller) time-stamping is free. It also protects the agents up to that point in time so if a code signing cert expires the agent's signed with it prior to the expiration are still good to use (And valid). Is this something you think you could integrate?

**Comment by Ylianst** [comment]
Yes! I am 100% working on this. After a realized it's required since it allows the OS to verify an executable after the signing certificate expired, I am making this a priority. I am out for the next two days, but later this week and this weekend, I am full on with this. Agreed, the service is free.

**Comment by Ylianst** [comment]
Quick note to say that I just check it the initial work on getting time stamping working. I built the request and sent it to the server correctly at the given URL, I then get a correct signed response back. I now need to merge that signature and certificates back into the executable. So far so good.

**Comment by Ylianst** [comment]
I added support for time stamping into Authenticode.js last night and it seems to work ok. MeshCentral v1.0.37 will automatically time stamp when signing an agent. I will release the new version today, will be interesting to get feedback on it.

**Comment by LPJon** [comment]
This is working! I now have signed and timestamped agents. However, with the `"_agentSignLock": true,` set in the config.json I am not seeing the lock when running `MeshService.exe -info` on the agent executable. Is this related or should I start a new issue?

**Comment by LPJon** [comment]
Closing this issue in favor of already open issue #4129
