### ISSUE TITLE
Feature: Enable Web based SSH/RDP in local and local relay devices

### ISSUE THREAD

**Issue by OvrAp3x** [Ylianst/MeshCentral#4123]
Like the title says, would be great if this could be done with just the webinterface, without the need to have meshrouter installed. Ie when using from android tablet etc.

Re-use the new feature for ssh/rdp that has been added to devices with agents for this local devices and local devices using a relay.

**Comment by Ylianst** [comment]
If that not already implemented? Local device groups support SSH and RDP and you can create a local device group with an agent relay. I have a [video on this here](https://www.youtube.com/watch?v=TtW5-g6SeZQ).

To enable SSH support, add this line to the domain section of your config.json:

```
      "ssh": true
```

This will cause MeshCentral to install extra modules when the server is next reset to support SSH.

**Comment by OvrAp3x** [comment]
Ah, that was what I was missing! Thank you @Ylianst helpfull as always :-)

**Comment by silversword411** [comment]
Added to docs 

https://github.com/Ylianst/MeshCentral/pull/4140/commits/1608e67ebc8cd4d33750b727464a906b657fb4a0
