### ISSUE TITLE
Feature Request: Right click on disconnect, option to lock/logout

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#4126]
I know there is an option to lock on disconnect in the settings menu, but I would like to see it as a right click option on the disconnect button as well, so it would be a "On demand" setting instead of always on/off. I think both options are valid. specially when working on windows servers its always nice to have that "always on" option 

Found a similar open issue and I think it can be closed considering the option in the settings menu. Link below

https://github.com/Ylianst/MeshCentral/issues/2990

**Comment by folosleg** [comment]
Right click on Disconnect with the option to Disconnect and Lock / Disconnect is there.
It's odd if you don't have it, I'm not aware of a setting in config.json related to this functionality. Try updating to the latest version maybe.
![image](https://user-images.githubusercontent.com/80481320/186659327-6f222aa3-e297-4ca8-84da-40afb13b9a41.png)
