### ISSUE TITLE
Question: meshcentral-data - correct folder structure

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#4127]
New Ubuntu 20.04 install:
```
/opt/meshcentral/meshcentral-data/letsencrypt
/opt/meshcentral/meshcentral-data/signedagents
```

My "old" Fedora 29: - I'm copying these files to the new install:
```
/opt/meshcentral/meshcentral-data/letsencrypt-certs
/opt/meshcentral/meshcentral-data/letsencrypt-old
/opt/meshcentral/meshcentral-data/letsencrypt3
/opt/meshcentral/meshcentral-data/letsencrypt3-staging
/opt/meshcentral/meshcentral-data/signedagents
```

p. 24 of the install guide says : `sudo chmod 755 –R /opt/meshcentral/meshcentral-data/letsencrypt`
I can't run this command after "mongorestore" the backup.archive

Which is the valid solution?

**Comment by Ylianst** [comment]
As MeshCentral evolved, the directory structure evolved. The modern MeshCentral only uses these folders:

```
/opt/meshcentral/meshcentral-data/letsencrypt-certs
/opt/meshcentral/meshcentral-data/signedagents
```

The older folders above are no longer used. So, the install guide is not correct. The correct command is:

```
sudo chmod 755 -R /opt/meshcentral/meshcentral-data/letsencrypt-certs
```

Let me know if this works.

**Comment by FATeknollogee** [comment]
Thanks for clarifying. Still getting the following error
```
Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)....
```

**Comment by FATeknollogee** [comment]
This command worked:
`sudo chmod 755 -R /opt/meshcentral/meshcentral-data/letsencrypt-certs`

**Comment by FATeknollogee** [comment]
On the new Ubuntu 20.04 install, with the default file structure:
```
/opt/meshcentral/meshcentral-data/letsencrypt
/opt/meshcentral/meshcentral-data/signedagents
```
This following command works:
`sudo -u meshcentral node ./node_modules/meshcentral`

**Comment by FATeknollogee** [comment]
It's all fixed.
I made a new `config.json` using `sample-config-advanced.json` as a template
