### ISSUE TITLE
Authenticode-signed agents using wrong domain for agentSignLock URL

### ISSUE THREAD

**Issue by kj7ice** [Ylianst/MeshCentral#4129]
**My Environment**
My MeshCentral instance (latest version 1.0.36) operates under a subdomain (sub.domain.tld). I have a wildcard certificate (*.domain.tld) that I use for my MeshCentral instance. I replaced webserver-cert-public.crt and webserver-cert-private.key with my wildcard certificate. The "cert" setting in my config.json is set to sub.domain.tld. All of my customizations are configured under the default domain.

**The Problem**
When I enable the "agentSignLock" setting, the Authenticode-signed executable is incorrectly locked to domain.tld rather than sub.domain.tld which prevents freshly installed agents from connecting. Both the meshagent.msh file and the output of `meshagent.exe -info` have the incorrect URL.

Looking at [this line of meshcentral.js](https://github.com/Ylianst/MeshCentral/blob/297deb927d88ac166bde6e4a4298eeb524353866/meshcentral.js#L2868) where the sign URL is constructed, I see that the "dns" value for the domain is used if set, otherwise the (web?) server certificate's common name is used. This would explain why the executable is locked to domain.tld because domain.tld is the common name of my wildcard certificate.

I can't set the "dns" value in config.json because I am using the default domain. A workaround might be for me to configure MeshCentral to get a certificate from Let's Encrypt for sub.domain.tld, but I prefer to use my wildcard certificate.

I also saw this post which describes similar symptoms due to the "agentAliasDNS" value not being considered for the sign URL https://www.reddit.com/r/MeshCentral/comments/vd5mah/agentsignlock_am_i_stupid_or_is_it_broken/

Of note: the Authenticode signing certificate has the correct sub.domain.tld in the certificate's name for my environment (the name looks similar to sub.domain.tld-a1b2c3).

**Potential Solution**
May I suggest that the domain for the sign URL be evaluated in this order (or something similar)?
1. The "dns" value for the domain.
2. The "agentAliasDNS" setting in config.json.
3. The "cert" setting in config.json.
4. The common name of the server certificate.

I apologize that I don't have a development environment setup for MeshCentral in order to submit a patch/pull request myself! Thank you to Ylian and the team, as always, for such an amazing project!

**Comment by Ylianst** [comment]
Hi and thank you for the detailed bug report. That is very high quality.

I added a fix for "agentAliasDNS" and this will be in MeshCentral v1.0.37. I will release it today.

In the new version, the URL evaluation order is:

1. The "agentAliasDNS" setting in config.json.
2. The "dns" value for the domain.
3. The "cert" setting in config.json.

If needed, I could add a "agentAliasDNS" in the domain section of the config.json that would be even higher priority. In my thinking, alias settings always take precedence.

One thing I do not understand about your configuration, is that the "cert" setting in the "settings" section of your config.json should be set to "sub.domain.tld". If I did the code right, MeshCentral should detect that your wildcard certificate covers this sub name and should accept it as correct. If I did not understand something or if that does not work, let me know.

Once MeshCentral v1.0.37, you can use "agentAliasDNS" to fix your issue, but the best would be to set "cert" to "sub.domain.tld".

Ylian

**Comment by LPJon** [comment]
@Ylianst I'm not getting a signlock at all.  I have a sub.domain.tld and it is correctly specified in the config.json in the "cert" setting. This is on the latest MC Version 1.0.37

**Comment by kj7ice** [comment]
@Ylianst thank you so much! I updated today and my issue is fixed in the latest version.

Yes, the "cert" setting in my config.json is correctly set to sub.domain.tld, and sub.domain.tld was used as the subject/common name of the Authenticode certificate, but the agent was still locked to the primary domain.tld for some reason. This is fixed and works as expected now, so thank you again!

I did not have to configure the "agentAliasDNS" setting in my environment since the agents are now sign locked to the domain specified in the "cert" setting.

**Comment by kj7ice** [comment]
@LPJon in my settings.json I have `"agentSignLock": true,` without the underscore (_) and it's locking the agents for me. I saw in #4121 that the underscore was included in your declaration and I wonder if that could be the cause?

**Comment by LPJon** [comment]
I have the underscore removed that was just a copy and past from the advanced-config file here on github.

**Comment by LPJon** [comment]
@Ylianst @kj7ice I should also note that im speaking about the autosign feature.

**Comment by kj7ice** [comment]
@LPJon I don't know if this is necessary, but each time I changed Authenticode-related settings while investigating this bug (and also when testing the fix) I would delete the .exe files in the meshcentral-data/signedagents/ directory and restart MeshCentral. This forces the agents to be re-signed at startup by the autosign features. I wonder if that would help to resolve the issue you're experiencing? Beyond that I can't think of anything else to try and maybe Ylian has some more ideas.

**Comment by LPJon** [comment]
@kj7ice Okay so I just tried that and still no dice. How are you checking the agent lock to be sure it's locked? Is it the with `-info` flag when starting the executable?

**Comment by LPJon** [comment]
Okay, I'm just going to open another issue. This didn't work for me before either so I need to figure out why and this issue isn't the place to do it.

**Comment by Ylianst** [comment]
Nice communication here. I will close this one and continue on #4143.
