### ISSUE TITLE
Backspace not working in Terminal on latest Windows versions.

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#413]
In the terminal neither the backspace key and backspace button seem to be operational. Tested using Agent on windows 10 and meshcentral.com

**Comment by krayon007** [comment]
What language and keyboard layout are you using on the local and remote side?

**Comment by datapharmer** [comment]
Standard US English on both the local and agent side

**Comment by Ylianst** [comment]
I see the same problem, looking into it.

**Comment by Ylianst** [comment]
It looks like the 32bit Windows agent has this problem, but not the 64bit version. Can anyone else confirm this is the case for them? Thanks.

**Comment by datapharmer** [comment]
We're actually seeing this on the 64bit version.

**Comment by krayon007** [comment]
You are referring to the agent binary, not the OS, correct? (ie: if you click on the agent in the browser, under "Mesh Agent", it says, "Windows 64bit service"?

I have not been able to reproduce this issue with the 64 bit agents on 64 bit windows, only with 32 bit agents on 64 bit windows.  Which build of Windows 10 are you using?

**Comment by Ylianst** [comment]
Ok, new theory. There is a version of Windows that breaks the backspace. When you enter the terminal, can you check which version of Windows shows up?

```
Microsoft Windows [Version 10.0.17763.503] - Does not backspace.
Microsoft Windows [Version 10.0.17627.1000] - Works
Microsoft Windows [Version 10.0.17134.885] - Works
```

**Comment by datapharmer** [comment]
The version is Microsoft Windows [Version 10.0.17763.615] so looks like it may be all or most 10.0.17763.x builds. Confirmed backspace works in command prompt when run locally on the computer.

**Comment by Ylianst** [comment]
Just to confirm, it seems that the backspace does work, but it does not show on the screen. It's a display problem, not an input one. If you can confirm the same, would be appreciated.

If you type "ab<backspace><enter>" you get an error that "a" is not found (not "ab").

**Comment by datapharmer** [comment]
Good catch. I can confirm that is indeed the case.

**Comment by Ylianst** [comment]
Thanks. Bryan will need to look at this. It's going to be a big problem as more people update to the latest Windows version.

**Comment by MailYouLater** [comment]
I've been seeing this for quite a while and just hadn't got around to reporting it because, while annoying, it doesn't break anything. It sure would be nice if it was fixed though.

**Comment by MailYouLater** [comment]
Also, `CLS` doesn't work right (moves the cursor and command output back to the top, but doesn't clear anything from the screen), <kbd>Shift</kbd>+<kbd>Tab</kbd> is treated the same as <kbd>Tab</kbd>, and the arrow keys seem to clear the contents (but not the display) of the current line and produce `[A`, `[B`, `[C` & `[D` instead of <kbd>↑</kbd> & <kbd>↓</kbd> going back and forth through the command history and <kbd>←</kbd> & <kbd>→</kbd> moving the cursor to allow you to edit a part of the current command other than the very end.

**Comment by MailYouLater** [comment]
Any chance of an update on this?

**Comment by dinger1986** [comment]
tested working fine for me @si458

**Comment by si458** [comment]
closing as stale but also seems to be fixed as no reported issues recently 2023
