### ISSUE TITLE
Agent Branding Issue

### ISSUE THREAD

**Issue by lukewchris** [Ylianst/MeshCentral#4130]
Hi Ylian,

As reported on YT comments, if I set the "Company Name" the Title bar of the agent installer changes as expected. However, I have "prompt for user consent" enabled and when users are prompted for confirmation to allow screen share, for example, the Title bar still shows "MeshCentral". Is it possible to pull through and use the Company Name defined in config.json instead? 

Thanks again

**Comment by si458** [comment]
closing this as stale,
please try the latest version 1.1.20 and use node 18 or above and try again,
if your issue still persists, then please reply back
