### ISSUE TITLE
Question: Google Drive backup - how to setup?

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#4132]
Question:

Looking for `instructions for dummies` on setting up Google drive backup?

**Comment by silversword411** [comment]
If you get it working, write something up and we'll get it in the [docs](https://ylianst.github.io/MeshCentral/)

**Comment by FATeknollogee** [comment]
I got it working & took some screenshots.
It isn't 100% complete.
Would you still like to see it?

**Comment by silversword411** [comment]
Nice, here you go!
https://github.com/Ylianst/MeshCentral/pull/4140
