### ISSUE TITLE
meshcmd.exe AmtInfo UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4135]
**Describe the bug**
trying to check AMT infomation and activate it

**To Reproduce**
```
c:\Intel>meshcmd64.exe AmtInfo
*** UNCAUGHT EXCEPTION: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'heci.session' threw an exception: TypeError: cannot read property 'EHBC' of null in method 'H()' ***
```

**Expected behavior**
output information about AMT

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Alpine
 - Virtualization: Docker
 - Network: Lan/WAN, Traefik SSL
 - Version: 1.0.36
 - Node: 
 - Browser: Firefox

**Remote Device (please complete the following information):**
 - Device: Dell Optiplex 790
 - OS: Windows 10
 - Version: 21H2
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
i have installed the Intel Management - https://www.dell.com/support/home/en-uk/drivers/driversdetails?driverid=mpgy4&oscode=w864&productcode=optiplex-790
all drivers installed fine and i can access `http://localhost:16992` with my password which i setup from the webui no problem

**Comment by raghu-mp** [comment]
I having the same issue on a HP 8300 SFF with Debian. Running ./meshcmd amtconfig --url wss: completes and the client shows up on meshcentral under the AMT device group with **Intel® AMT | Activated CCM, v8.1.0, TLS**. But it is missing all the info and can't connect to it. 

Running  ./meshcmd amtinfo
*** UNCAUGHT EXCEPTION: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'heci.session' threw an exception: TypeError: cannot read property 'EHBC' of null in method '_amtOnData()' ***

**Comment by si458** [comment]
Just tried a dell optiplex 990 which shows `Activated ACM, v7.1.91, TLS` but still cant get circa to activate and i get the same error as above
any suggestions @Ylianst ?

**Comment by si458** [comment]
new meshcmd will need to be build and released but bug has been fixed now!
