### ISSUE TITLE
LDAP does not query by group

### ISSUE THREAD

**Issue by xanpri** [Ylianst/MeshCentral#4138]
I'm trying to configure ldap to use groups. But group authentication is not working.
I use Open LDAP to authenticate Linux systems and workstations.

Here's the configuration I'm using:

    "ldapOptions": {
        "url": "URL",
        "bindDN": "USERBIND",
        "bindCredentials": "SUPERPASS",
        "searchBase": "ou=test,dc=DC,dc=DC,dc=br",
        "searchFilter": "(&(objectClass=posixAccount)(uid={{username}}))",
        "groupSearchBase": "ou=test,dc=DC,dc=DC,dc=br",
        "groupSearchFilter": "(&(objectClass=posixAccount)(cn=group1)(memberUid={{username}}))",
        "tlsOptions": { "rejectUnauthorized": false }
		},
		
		
Group1 data for groupSearchFilter search:

  dn: cn=group1,ou=test,dc=DC,dc=DC,dc=br
  cn: group1
  gidNumber: 11111
  objectClass: top
  objectClass: posixGroup
  memberUid: user1
  memberUid: user2
  memberUid: user3

What could I be doing wrong in the group consultation?

**Comment by wdlut** [comment]
Hierarchically structured groups are problematic. 
In our case, users are in groups of departments and some department groups are member of the group "Mesh" and thus allowed to log-in to MeshCentral. It was not possible to filter for this nested group with groupSearchBase and gropuSearchFilter.
This worked:
...
        "searchFilter": "(&(sAMAccountName={{username}})(memberOf:1.2.840.113556.1.4.1941:=cn=Mesh,OU=Administration,DC=mydomain,DC=com))",
...

1.2.840.113556.1.4.1941 is the OID for LDAP_MATCHING_RULE_IN_CHAIN and LDAP_MATCHING_RULE_TRANSITIVE_EVAL
https://ldapwiki.com/wiki/1.2.840.113556.1.4.1941

I'm not an LDAP expert and cannot explain this solution in detail, but i know, that it works.
Maybe this helps.

**Comment by xanpri** [comment]
Thanks.

My openldap does not use memberof and the user registration has no link with the groups.
That's why my need to make the query by the groupSearchFilter.
