### ISSUE TITLE
Ubuntu 22.04 Black screen when connecting to desktop

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshCentral#4142]
**Describe the bug**
The issue looks to be a repeat of this:
https://github.com/Ylianst/MeshCentral/issues/37
In the latest version of Ubuntu, connecting to the host system shows a black screen for the desktop. All other remote functions seem to be working properly

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04 LTS
 - Node: [e.g. 18.3.0]
 - Browser: Chrome

**Comment by si458** [comment]
the issue is because Ubuntu 22 switches Wayland to true as default and it needs to be false for X11

https://askubuntu.com/a/1413490

**Comment by quentinDupont** [comment]
Any news to fix this ? Or we should absolutely make the chaneg for X11 ? Thank you :)

**Comment by istr404** [comment]
Hello,
after uncommenting the line about wayland and rebooting, desktop connection is OK, but the problem remains as far as web-vnc is concerned.

**Comment by computer-logix** [comment]
Some of my Ubuntu desktops won't display either even though it says connected.    22.04LTS as well and they all have Wayland disabled and have been restarted.
