### ISSUE TITLE
Question - MeshCentral "agentSignLock" not working when "agentsigningcert.pem" is used.

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4143]
**Describe the bug**
The MeshService.exe and MeshService64.exe are being signed and timestamped as expected. However, I can't get them locked using the `agentSignLock` setting in the config.json. I can sign them manually with the lock on windows or with authenticode.js. It's just not locking it automatically?

**To Reproduce**
1. Make sure to remove the `signedagents` folder and all of it's contents.
2. Enable the `agentSignLock` option in the config.json.
3. Add the correctly formatted `agentsigningcert.pem` to the `meshcentral-data` folder
4. Restart MeshCentral Server and then check the newly signed executables in the `signedagents` folder with `authenticode.js info --exe <filename>`
5. You won't find the `Signature Attributes:` section as needed to have the lock

**Expected behavior**
When `agentSignLock` is set to true and an `agentsigningcert.pem` is present the agent should show information in the `Signature Attributes:` and also be locked to the MeshCentral Instance.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: XCP-ng
 - Network: LAN/WAN, reverse proxy
 - Version: 1.0.38
 - Node: 16.15.1 (lts)
 - Browser: FireFox (Latest)

**Additional context**
None

Is there anything I'm missing in required steps get agents locked automatically?

**Comment by Ylianst** [comment]
Ok, checking this now.

**Comment by Ylianst** [comment]
I can't replicate the issue, but one interesting point of your report is that you do not see any `Signature Attributes:` at all. Even without a lock, MeshCentral should sign with attributes, for example on my developer server, it looks like this:

![image](https://user-images.githubusercontent.com/1319013/174465735-42a4b803-1e5a-4452-adfe-a92e9e50afc6.png)

I imagine you are saying that the executable is in fact signed and time stamped by MeshCentral using your certificate. If this is true, there should always be some signing attributes, locked or not. Weird. I am reviewing the code now to see if I can dig up anything.

**Comment by Ylianst** [comment]
Next version will have warnings on the console and in the "My Server" tab if the agent can't the signed.

![image](https://user-images.githubusercontent.com/1319013/174466214-2cfe0114-745e-49b5-a392-956a5978dd81.png)

**Comment by Ylianst** [comment]
If running in the console, code signing of the agent should look like this:

![image](https://user-images.githubusercontent.com/1319013/174466576-0f41a4b8-9f64-428d-a62e-82786eabe226.png)

In the next version of MeshCentral v1.0.39, you will be able to add `--debug main` and see the code signing parameters used:

![image](https://user-images.githubusercontent.com/1319013/174466632-308b6a41-1232-490c-ac61-0dc954be6432.png)

**Comment by Ylianst** [comment]
I can't find anything else, I will need another hint as to what is going on.

**Comment by LPJon** [comment]
I will use the debug at the next version. Hopefully that will shed some light on things.  So far everything you have posted im seeing except the attributes. I should note too that the server is configured for a sub-domain only and the domain.tld is a completely different web site. Could that that be an issue?

**Comment by Ylianst** [comment]
This subdomain should not be an issue. In the next version, if you add `--debug main`, you will see `MAIN: Code signing agents with arguments: ` and it will indicate the description (desc), the URL (url) and time server (time) that will be used for the signature.

I guess one issue could be an unsupported character in the string or something... I am lost as to why you get no signing attributes at all.

**Comment by LPJon** [comment]
Here is a screen shot of the `info` from the authentecode.js.
<img width="739" alt="Untitled" src="https://user-images.githubusercontent.com/46533576/174497607-2601eec4-5d43-41ec-9443-c174c941a465.png">
I have a funny feeling that it may be related to an unsupported or unprotected character/s at the command-line. We will see I guess. I will post back when 1.0.39 is released with a screenshot.

**Comment by LPJon** [comment]
@Ylianst Okay....so suddenly now with MeshCentral 1.0.39 the agents are being signed and locked as expected. Have no reason why it just suddenly worked. I could post screen shots but all you are going to see it what is expected now. This is very odd. Here are some server error code that was left after the upgrade though:
```
-------- 6/21/2022, 2:52:58 PM ---- 1.0.39 --------

Error: Cannot find module 'mongodb'
Require stack:
- /opt/meshcentral/node_modules/meshcentral/db.js
- /opt/meshcentral/node_modules/meshcentral/meshcentral.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.module.exports.CreateDB (/opt/meshcentral/node_modules/meshcentral/db.js:733:9)
    at Object.CreateMeshCentralServer.obj.StartEx (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:803:28)
    at Object.CreateMeshCentralServer.obj.Start (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:433:66)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:3754:24
    at InstallModules (/opt/meshcentral/node_modules/meshcentral/meshcentral.js:3543:121)
    at /opt/meshcentral/node_modules/meshcentral/meshcentral.js:3565:9
    at ChildProcess.exithandler (node:child_process:390:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/meshcentral/node_modules/meshcentral/db.js',
    '/opt/meshcentral/node_modules/meshcentral/meshcentral.js'
  ]
}
```
Maybe this had something to do with it? I should note that the service did restart and come back online. I just wonder if there wasn't something wrong with the mongodb module since I'm seeing other issues related to it here on github.

**Comment by LPJon** [comment]
You made perfect sense. However, I'm positive that I didn't do that. Either way this issue magically resolved itself so I'm gonna close it. Thanks for everything you do. I will reopen this issue if it comes back. My fingers are crossed that it doesn't.
