### ISSUE TITLE
Account recovery emails are not getting sent

### ISSUE THREAD

**Issue by bkgoodman** [Ylianst/MeshCentral#4149]
I created a new account - quickly forgot my password. Tried a few times to reset password and am not getting the emails. I *did* check spam, etc.

Please note that account verification emails ARE working for me (both before and after the reset attempts - as I subsequently created a new account after failing to get the reset email, and got the verification quickly)

GREAT tool - thanks!

**Comment by Ylianst** [comment]
FYI. I just checked my outbound email folder and saw that an email with you GitHub handle was sent at 9:25am PST. So, it does look like it's working on my end.

**Comment by bkgoodman** [comment]
Was this a RECOVERY email, or the VERIFICATION email? I asked for several recoveries. Never got one. Got at least two verificaitons.

**Comment by si458** [comment]
this is fixed for the public server,i created an account the other day and all seems ok, this issue can be closed

**Comment by bkgoodman** [comment]
@si458 This but was _specific_ to _password recovery_ emails - _not_ account creation emails. The later worked when the former did not. I just tried another _recovery_ and have not gotten the email yet - but someone needs to confirm receipt of a _password recovery_ email before closing. (I'll let you know if I get mine!)

**Comment by si458** [comment]
@bkgoodman ive just tried it now and yes i just got my account recovery email, no problems

just clicked `reset account` typed in email, got email, clicked link in email, then got my new password

whats your domain for the email? could your provider be blocking the incoming emails?

**Comment by bkgoodman** [comment]
I don't have this problem with any other mail - and I get the "new account" emails without issue. I did the same `account reset` procedure. `bradgoodman.com` is my email domain. It's not in spam or anything. I waited 3 days - still no email!

**Comment by bkgoodman** [comment]
I was just having a conversation with a collegue of mine about Meshcentral. His immediate response was "I tried to use it, but I forgot my password and then **never got the recovery email**". He used his dell.com email. So more proof this is a persistent and wider-spread problem...

**Comment by si458** [comment]
closing this as completed as meshcentral.com public server was shut down,
please move to the self-hosted version
