### ISSUE TITLE
MeshCore Recovery

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#4150]
I don't know that this is related to upgrading to version 1.0.38. But I didn't notice this happening until I did so. 
I installed two Windows 10 devices yesterday with an agent that was generated right before the install and under 1.0.38.
I can see both devices but both are using 'MeshCore Recovery' for the agent. As such I can not access these devices. 
Anyone know why this would be happening?  Is there any way to push the full agent to these devices?  I've tried using the Agent Action button under the console and chose 'Upload default server core' but that made no difference.  
Obviously I need to make sure this doesn't happen with any other new devices.  
Also, when creating the agent, I can see that it is being signed with the self signed cert and is time stamped.  So that part is working correctly.  Just no idea why it is generating the agent using the recovery core?

**Comment by krayon007** [comment]
When it's running the recovery core, is the console tab responsive at all? Does 'help' work? 

Normally the only time the server uploads the recovery core to the agent, is if it's trying to update the agent from an old version of the agent.

Do you know what server version your were upgrading FROM, when going to 1.0.38?

**Comment by PathfinderNetworks** [comment]
Thanks Bryan, sorry about the delay in responding. I had to wait until I was able to get logged in at the same time as one of these users was also using their device.  I just checked- yes, the Help command under the Console does respond for these devices that are using the Recovery Core.  It comes back with this:
`> help
Available commands are: agentupdate, agentupdateex, dbkeys, dbget, dbset, dbcompact, eval, netinfo, osinfo, setdebug, versions.`

**Comment by PathfinderNetworks** [comment]
If I send a versions command I get this: 
` "openssl": "1.1.0f",
  "duktape": "v2.3.0",
  "meshAgent": "2019-06-14T22:11:40.000Z"`

**Comment by krayon007** [comment]
Wow that's an ancient agent. But thanks to your versions result, I can test that version of the agent and see if I can get it to update correctly...

**Comment by PathfinderNetworks** [comment]
Any idea why it would have installed that version?  I used the 'Add Agent' link to generate the agent installer right before I performed the install on those devices.

**Comment by krayon007** [comment]
I'm looking into testing updating from the specific agent version returned in your result above... As far as why that version was installed... The server just sends whatever agent it has in it's agents folder... If you can go to your server, and copy the MeshService64.exe to a windows machine, (or just run it locally if your server is Windows), and run the agent with the following parameter:

`MeshService64 -info`

and it should return the same information contained in the `versions` console command, so you can verify what version your server is serving...

**Comment by krayon007** [comment]
I found the problem that caused the update itself to fail when updating from server version `v0.3.6-n`, which is the version that your agent appears to be from. There were some interop issues with the recovery core with that version of the agent, so I added a fix, so that it will update correctly.  When you update from that version, it will report an update failure, and report that it will retry with a different mechanism to fetch the update, which will succeed. The updated recovery core will be in the next version of the server.

As far as why the agent that was installed on your "new" install being from v0.3.6-n is a different matter.

**Comment by PathfinderNetworks** [comment]
Excellent!  Once that version is released I will upgrade to it and let you know the results. I installed Mesh on another new device (from a different device group) and didn't see the same issues.  So not sure what was going on with that particular install on that day.

**Comment by PathfinderNetworks** [comment]
I just updated to 1.0.43.  Within seconds of the MeshCentral server coming back up I noticed one of these devices that had the MeshCore Recovery agent had updated to the current version of the agent. The other device doesn't happen to be on at the moment.  But it looks like this change has resolved this particular issue.
Thank you!
