### ISSUE TITLE
Be able to reset and get a new loginTokenKey

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#4153]
If the token gets out, need to have a way to generate a new software token (what this is): `node meshcentral --loginTokenKey`

I think there can only be one loginTokenKey? Assuming that, I'd think the command needed would be:
`node meshcentral --resetloginTokenKey`

Which would delete the old key, and replace it with a newly generated one?

Is there a way to view login sessions, and tell which are user based vs loginTokenKey Based?

Related to: https://github.com/Ylianst/MeshCentral/issues/3923

**Comment by Ylianst** [comment]
I am so overloaded with work, it's crazy. This is certainly something I want to work on.

**Comment by silversword411** [comment]
> so overloaded with work

Completely understand, so am I :)

Wanted to just clarify and close the old one.

**Comment by BillBardon** [comment]
I had this script running on my server every morning. It changes the key and restarts the meshcentral server. The bit at the end is optional. Put this in the mesh user's crontab and run as often as you like.

```
#!/bin/bash

# mesh runs as bill
if [ "$(whoami)" != "bill" ]; then
        echo "Script must be run as user: bill"
        exit 199
fi

cd

newkey=$(pwgen -A -n -B 20 1)

sed -i -e "s/\(\"loginKey\": \"\)\([a-zA-Z0-9]*\)\(\",\)/\1$newkey\3/" meshcentral-data/config.json

pkill -f node_modules/meshcentral && node ./node_modules/meshcentral > stdout.txt 2> stderr.txt &

# trick here is to monitor for this string in Zabbix and send alert
logger -t SedNewKey $newkey

```
When I began using loginTokenKey, I distinctly remember it being an array, and you could have multiple values. Don't have time to look at the code right now.

**Comment by silversword411** [comment]
Thanks! I'll have to do some testing, looks like we'll need to do some script tweaking on bill ;)

**Comment by si458** [comment]
a user can delete its key from the web ui, are you talking about an admin being able to delete a login key of a user?

**Comment by silversword411** [comment]
I think they're referring to the software key, which you can't reset or change.

So once leaked it's gone and unchangeable

**Comment by si458** [comment]
this already exists funnily enough!
just discovered it after i was wrote `resetLoginTokenKey` and was about to upload haha
`node node_modules/meshcentral --loginTokenKey --loginTokenGen`
```
simon@testmc:~/meshcentral/MeshCentral$ node . --loginTokenKey
2fd1b8ec90b3b1591a7ffa3317b1a41ac00ee4d99efdacc6f3f5c2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
simon@testmc:~/meshcentral/MeshCentral$ node . --loginTokenKey --loginTokenGen
4937396bac930b5723585dde2be7f3f77435b182867280dfa3dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
simon@testmc:~/meshcentral/MeshCentral$ node . --loginTokenKey --loginTokenGen
6b958f480f1c5bc1f3bafb1071367ba9eb9c6cd6b0e109e71edcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
simon@testmc:~/meshcentral/MeshCentral$ 
```
