### ISSUE TITLE
Messages are not sent to the remote device

### ISSUE THREAD

**Issue by openncomp** [Ylianst/MeshCentral#4155]
**Describe the bug**
Messages are not sent to remote Windows clients on the General tab, as well as when clicking on the bell icon and on the Desktop tab.

**To Reproduce**
1. Click on any Windows device
2. In the General tab that opens, click the Message button
3. A message entry window will open
4. After entering the text and pressing "OK", the window with the sent message will not be displayed on the remote device

**Expected behavior**
It is expected that a message window will open on the remote device, as it happens when sending a message from the group actions menu.

**Screenshots**
![1-1](https://user-images.githubusercontent.com/92163803/175031849-2041d4d5-154c-4ee2-8f72-03f6fc857b41.png)
![2-1](https://user-images.githubusercontent.com/92163803/175031917-203071d2-6fba-403d-9681-98d6cc9f3946.png)
![3-1](https://user-images.githubusercontent.com/92163803/175031921-9fc9db2e-1d74-48e9-a43e-7fca5e3237d9.png)
![4-1](https://user-images.githubusercontent.com/92163803/175031933-45ac4c99-6775-47c6-b607-9b6f83e902ce.png)
![5-1](https://user-images.githubusercontent.com/92163803/175031941-488198e5-f0e4-46f5-9f31-2deece5b9ed1.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Network: WAN mode, Nginx Proxy
 - Version: 1.0.39
 - Node: v14.19.3
 - Browser: Mozilla Firefox, Google Chrome

**Remote Device (please complete the following information):**
 - Device: desktop PC, notebook
 - OS: Windows 7,8,10
 - Current Core Version (if known): Mar 25 2022, 905338671

**Additional context**
There is an observation that messages are also not sent from the context menu "Group Action" until the "Title" field is filled in, which must be filled in manually.

I searched in "config.json" for the setting responsible for this field, but could not find it.
Apparently, messages from the General tab are not sent precisely because there is no "Title" field.

Another remark.
Notifications that pop up on a remote device when connected have a setting in "config.json":
```
"consent Messages": {
   "Title": "Support"
},
"notification Messages": {
   "Title": "Support"
}
```
But this setting does not affect the sending of messages.

**Comment by openncomp** [comment]
Updated Ubuntu from 18.04 to 20.04, NodeJS from 14.19.3 to 18.4.0.
The situation has not changed.

**Comment by openncomp** [comment]
Yes, of course.

**Comment by openncomp** [comment]
I just don't understand, is this a problem only for me or is it just that few people use sending messages in this way?

**Comment by openncomp** [comment]
There are no entries in the error log at the same time.
I also ran MeshCentral with the --debug key, there is a lot of information there, but I didn't see any explicit data by mistake.

**Comment by Ylianst** [comment]
I am testing this now. Note that in the config.json, the correct config is:

```
"consentMessages": {
   "Title": "Support"
},
"notificationMessages": {
   "Title": "Support"
}
```

There is no space in "consentMessages" and "notificationMessages". However, testing is now, it does not seem to work. Looking into why now.

**Comment by Ylianst** [comment]
After playing with settings for a while, I think I guessed what your issue is. You put this line in the domain section of the config.json file:

```
"title": ""
```

The MeshAgent does not support displaying message boxes with empty titles and by setting an empty title no box is showing up. I just put in a fix so that "MeshCentral" would be the default string when this happens.

I am guessing you did this because you have a "titlePicture" at the top of the page. Try using these settings:

```
      "title": "My Server Title String",
      "title1": "Title1",
      "title2": "Title2",
      "titlePicture": "title.png",
```

Always set the domain "title" to the name of your server, it will show up at lots of places. let me know if that works.

**Comment by openncomp** [comment]
> After playing with settings for a while, I think I guessed what your issue is. You put this line in the domain section of the config.json file:
> 
> ```
> "title": ""
> ```
> 
> The MeshAgent does not support displaying message boxes with empty titles and by setting an empty title no box is showing up. I just put in a fix so that "MeshCentral" would be the default string when this happens.
> 
> I am guessing you did this because you have a "titlePicture" at the top of the page. Try using these settings:
> 
> ```
> "title": "My Server Title String",
> "title1": "Title1",
> "title2": "Title2",
> "titlePicture": "title.png",
> ```
> 
> Always set the domain "title" to the name of your server, it will show up at lots of places. let me know if that works.

Of course, thank you very much!
How convenient it is now!
It worked:
"title": "My Server Title String",
