### ISSUE TITLE
Question on User Permissions

### ISSUE THREAD

**Issue by aislerad** [Ylianst/MeshCentral#4159]
Does anyone know what permission I need to grant to be able to see Intel AMT Reset, Intel AMT Power on, Intel AMT Power off. I am trying to setup a user group for new users and I don't get those Intel options when I go into the actions section. Currently it looks like that picture below even though AMT is connected. I can see the option on the admin account.

![image](https://user-images.githubusercontent.com/105459613/175179895-5efdacf7-5a90-45be-a7aa-d357aec9b956.png)

**Comment by aislerad** [comment]
Yes it is but what I think it actually does is kill AMT which I probably don't want my users doing anyway I'm in the middle of testing it now cause when I hit the Intel AMT Power off button on my test box AMT is not connected anymore.

**Comment by Ylianst** [comment]
Looks like unless your full administrator on the device, you don't get Intel AMT power operations. This is not right, you should be able to get them with "Wake" and "Reset/Off" rights. Working on fixing that now.

**Comment by aislerad** [comment]
Awesome thanks for looking into this.

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in v1.0.41. You can grant only "Wake" or "Reset/Off" rights and see them as a user:

![image](https://user-images.githubusercontent.com/1319013/175381141-8f260ae1-9a61-49e6-bf4b-bb6b854c1ca6.png)

Once released, let me know if it works for you.

**Comment by dinger1986** [comment]
@si458 fixed can close
