### ISSUE TITLE
Unable to type in remote session using Router

### ISSUE THREAD

**Issue by eagle856** [Ylianst/MeshCentral#4165]
As the title says, if I initiate a remote session to a Windows 10 computer using MeshCentral Router, I'm unable to type anything (including login credentials). Everything works fine using the web version. I've tried setting the option to use remote  keyboard map (in Router and the web version), but it had no affect. Any help would be greatly appreciated!

_Originally posted by @eagle856 in https://github.com/Ylianst/MeshCentral/discussions/4164_

**Comment by Ylianst** [comment]
Uncheck these two items and let me know if it fixes it. After playing around for a bit, i noticed these will stop the keyboard from working, I forget why they are even there now.

![image](https://user-images.githubusercontent.com/1319013/175367083-a8d7c7c9-db23-4506-978a-9fb8c6b60c2d.png)

**Comment by eagle856** [comment]
Thank you sir! That did the trick!

Can you please take a look at this please: https://github.com/Ylianst/MeshCentral/discussions/4156
