### ISSUE TITLE
Failed to sign agent

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#4168]
hello after update TO 1.0.40 I have the following error
WARNING: Failed to sign agent MeshService64.exe: Error: connect ETIMEDOUT 91.199.212.79:80
WARNING: Failed to sign agent MeshService.exe: Error: connect ETIMEDOUT 91.199.212.79:80
 as the server is in a private network.
The proxy is set for npm and in / etc / profile
I have a centos8 stream
 Due to limitations it is not possible for me to perform nat meshcentral.
You have a solution thank you very much

**Comment by Ylianst** [comment]
Ok, I will add proxy support for agent time stamping. You can still your your server like this but as a workaround, add this line in the "settings" section of the config.json:

```
"AgentTimeStampServer": false
```

This will remove time stamping and agent signing should work.

**Comment by paolor1965** [comment]
thanks it works and the server starts immediately but after a while systemctl status gives me the following info
at amtcert_linkCertPrivateKey (/srv/meshcentral/node_modules/meshcentral/amtmanager.js:3021:26)
    at Object.<anonymous> (/srv/meshcentral/node_modules/meshcentral/amtmanager.js:2303:13)
     at Object.<anonymous> (/srv/meshcentral/node_modules/meshcentral/amt/amt.js:149:186)
     at _EnumStartSink (/srv/meshcentral/node_modules/meshcentral/amt/amt.js:96:39)
     at /srv/meshcentral/node_modules/meshcentral/amt/amt.js:87:136
    at Array.<anonymous> (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman.js:51:17)
     at Object.CreateWsmanComm.obj.gotNextMessages (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:514:55)
    at Object.CreateWsmanComm.obj.xxProcessHttpResponse (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:444:17)
    at Socket.CreateWsmanComm.obj.xxOnSocketData (/srv/meshcentral/node_modules/meshcentral/amt/amt-wsman-comm.js:416:25)
    at Socket.emit (node:events:520:28)

**Comment by Ylianst** [comment]
This is an unrelated error, can you post the full error? Looks like the first line is missing.

**Comment by paolor1965** [comment]
I had updated node 14 to 16. I rebooted the operating system and the error disappeared
thanks

**Comment by Ylianst** [comment]
I also put in a possible fix for "amtcert_linkCertPrivateKey".

**Comment by paolor1965** [comment]
I set the "agentTimeStampProxy" directive: "http://proxy.unige.it:8080",  ( i have used also IP) on a backup meshcentral server

WARNING: Failed to sign agent "MeshService.exe": Unable to parse response.
Jun 24 12:46:34 messhcentral2_backup.amm.balbi.unige.it node [202250]: WARNING: Failed to sign agent "MeshService64.exe": Unable to parse response.

if I comment on the directive
n 24 14:05:10 messhcentral2_backup.amm.balbi.unige.it node[202724]: MeshCentral v1.0.41, Hybrid (LAN + WAN) mode, Production mode.
Jun 24 14:07:22 messhcentral2_backup.amm.balbi.unige.it node[202724]: WARNING: Failed to sign agent "MeshService64.exe": Error: connect ETIMEDOUT 91.199.212.79:80
Jun 24 14:07:22 messhcentral2_backup.amm.balbi.unige.it node[202724]: WARNING: Failed to sign agent "MeshService.exe": Error: connect ETIMEDOUT 91.199.212.79:80

**Comment by paolor1965** [comment]
I have another server on the public network and doing several tests by removing and replacing the proxy I get this error
 WARNING: Failed to sign agent "MeshService.exe": Error: Too few bytes to read ASN.1 value.
Jun 24 14:32:37 130-251-190-120 node [2160121]: WARNING: Failed to sign agent "MeshService64.exe": Error: Too few bytes to read ASN.1 value.
I have either downgraded to stable and then or upgraded to the latest, even removing node_modules
