### ISSUE TITLE
Feature Request: Manual DNS for Agent

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#417]
I can imagine a few situations where a system could be using a broken or misconfigured DNS server.

Could we have the option for the agent to have it's own DNS settings rather than the DNS configured on the host system?

**Comment by krayon007** [comment]
When you say it's own, are you talking about configuring a different dns server than what was provided by DHCP, or do you mean something like where you write entries into a hosts file, to o erride specific DNS entries?

**Comment by ghplw** [comment]
Different DNS server.

For example I would like to set it to use the Cloudflare DNS servers, 1.1.1.1 and 1.0.0.1 and more specifically the agent would need to do all it's resolution internally if it doesn't already.

An example use case would be last year when I had a heap of brand new Dell Latitudes that would bluescreen on fresh Windows 10 installations but not straight away, within a week or so of installation and then afterwards DNS resolution would be completely broken.

Another more common issue is in a Windows Active Directory environment where the client PCs are forced to use the server for resolution. If the server goes down they still have internet but no DNS available.

**Comment by krayon007** [comment]
So you are asking for the Agent to use a separately configured DNS server from the rest of the OS? (As opposed to the agent being able to reconfigure the OS to talk to a different DNS server?)

**Comment by ghplw** [comment]
Yes

**Comment by Ylianst** [comment]
I will point out that the MeshAgent currently stores the last resolved IP address that successfully connected to the server and uses that IP address as a backup is DNS resolution fails. So, once a agent connects once, having a broken DNS should not stop the agent from connecting again.

Making the agent using a separate DNS server is likely a bunch of work as I imagine we would need to send a DNS query from the agent, so, building a DNS client in the agent. Given our stored IP system and the complexity of a DNS client, I propose not doing this.

However, feedback on this welcome.

**Comment by ghplw** [comment]
I agree, this is a much simpler idea which should take care of the problem in most situations.
