### ISSUE TITLE
No "Desktop" tab for new Ubuntu 22 Desktop Install

### ISSUE THREAD

**Issue by bkgoodman** [Ylianst/MeshCentral#4170]
Brand new Ubuntu 22 Desktop installation. Added Meshagent - not getting any "Desktop" tab in Meshcentral. (All other functionality appears normal)

I had installed Ubuntu 20 and Ubuntu 22 Server recently on this same hardware - manually added "Ubuntu Desktop" - and had no problem with Desktop showing up. But now with my new (what I hoped to be my "final" install 2/ Ubuntu 22 Desktop - "Desktop" tab does not show up.

I have tried rebooting (twice) and clearing/reloading the "core" to no avail. Desktop GUI is working fine on local monitor.

Please advise how to further debug

**Comment by si458** [comment]
**plz can you follow the template in the future to help us diagnose issues faster like your current setup**

after creating a test VM with vmware workstation of ubuntu 22.04,
i can install the agent no problem via command line,
and i even get the desktop tab being shown, but when you click connect, all i get is a black screen
meshcentral 1.0.40

**Comment by bkgoodman** [comment]
There is NO "black screen". No "Desktop" tab whatsoever.

**Comment by krayon007** [comment]
If you go to the console tab, and type `info`, what does it say under x11 support?

**Comment by si458** [comment]
> If you go to the console tab, and type `info`, what does it say under x11 support?

yes
```
> info
Current Core: Apr 4 2022, 4221406369
Agent Time: 2022-06-24 17:53:47.295+01:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 15.
Server URL: wss://meshcentral.mefoo.com:443/agent.ashx.
OS: Ubuntu 22.04 LTS.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, linux-dhcp, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: true.
```

**Comment by bkgoodman** [comment]
When I went into Console, before doing anything it immediately said:  
  
`uncaughtException1: Error: timers.onElapsed() callback handler on '()' => waitExit() already in progress`  
  
So I rebooted the box. It came up within about 2 minustes, but MeshCentral still said it was offline. I waited some more - then eventually checked `jounalctl` and `systemctl` and it said that `meshagent` was running. Not knowing what to do, I did `systemctl restart meshagent` and it _immediately_ came to life on MeshCentral GUI.  
  
But - Still no "Desktop" tab. Console info was then as follows:

```
> info
Current Core: Jan 7 2022, 3236819516
Agent Time: 2022-06-24 14:25:08.486-04:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 14.
Server URL: wss://meshcentral.com:443/agent.ashx.
OS: Ubuntu 22.04 LTS.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, linux-dhcp, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: false.
```

**Comment by si458** [comment]
@bkgoodman can you try this please as it fixes the black screen on my side
https://github.com/Ylianst/MeshCentral/issues/4142#issuecomment-1165845314

**Comment by bkgoodman** [comment]
1.  I have done `agentupdate` a couple times from the console - it still only appears to put this same version (above) on here. How can I update? (Remember, this was a _brand new_ install from 2 days ago!)  
     
2.  I had Ubuntu "Automatic Login" enabled. On a whim, I went into `/etc/gdm3/custom.conf` and disabled it. "X11 support" now shows "true", and "Desktop" now shows up, but when I try to connect, after a few seconds it says "KVM Child Process has unexpectedly existed".   
     
3.  I also trying turning "Wayland" support on and off for GUI long X support - but the above problem keeps happening.  
     
4.  I still have the odd problem of needing to manually restart `MeshAgent` after each reboot for it to appear in MeshCentral.  
      
    Thanks for your help!

**Comment by si458** [comment]
> 1. I have done `agentupdate` a couple times from the console - it still only appears to put this same version (above) on here. How can I update? (Remember, this was a _brand new_ install from 2 days ago!)


can you check your server is running the latest version anyways please (just to rule this out)?
go into the `My Server` tab, then console and run `info` should get output like this
```
> info
{
    "meshVersion": "v1.0.41",
    "nodeVersion": "v18.4.0",
    "runMode": "Hybrid (LAN + WAN) mode",
    "productionMode": true,
    "database": "NeDB",
    "platform": "linux",
    "arch": "x64",
    "pid": 31,
    "uptime": 45497.389097972,
    "cpuUsage": {
        "user": 89053323,
        "system": 25093253
    },
    "memoryUsage": {
        "rss": 155389952,
        "heapTotal": 68313088,
        "heapUsed": 61727064,
        "external": 31346900,
        "arrayBuffers": 30544844
    },
    "warnings": [],
    "allDevGroupManagers": []
}
```

>     2. I had Ubuntu "Automatic Login" enabled. On a whim, I went into `/etc/gdm3/custom.conf` and disabled it. "X11 support" now shows "true", and "Desktop" now shows up, but when I try to connect, after a few seconds it says "KVM Child Process has unexpectedly existed".

this might be related to the old agent thats installed on the client device (we need to check server side first),

>     3. I also trying turning "Wayland" support on and off for GUI login X support - but the above problem keeps happening.

sadly i believe you need `WaylandEnable=false` set in `/etc/gdm3/custom.conf`
i think @krayon007 might have to look into the wayland issue

>     4. I still have the odd problem of needing to manually restart `MeshAgent` after each reboot for it to appear in MeshCentral.
>        Thanks for your help!

again this might be related to the old agent thats installed on the client device (we need to check server side first) then update the agent

**Comment by bkgoodman** [comment]
Oh, server? I am using public server. I have no "My Server" tab.

**Comment by si458** [comment]
> Oh, server? I am using public server. I have no "My Server" tab.

ah right ok, just set myself an account up and tried it myself,
it installs the agent from jan 2022 rather than the latest in apr 2022
HOWEVER i can still connect to my ubuntu 22 machine with no issues so long as the `WaylandEnable=false`

is the ubuntu machine physical or VM? ive found old posts/issues about this problem and some say its nvidia related
and some say you need to update to the latest agent (which isnt possible if your using the public server)
https://www.reddit.com/r/MeshCentral/comments/pjtj6p/kvm_child_process_has_unexpectedly_exited_error/
https://github.com/Ylianst/MeshCentral/issues/602

**Comment by bkgoodman** [comment]
Physical machine. Intel only (no NVIDIA). (Same physical machine that worked before).  
  
But....there is one _more_ difference. I brought this machine home and am using a VGA cable (was DP at work)? The i915 drivers are indicating is "knows" it's using VGA. 

I don't have a DP->HDMI cable (which is why I'm using VGA) - but I'll see if I can find one - and if it will make a difference?????

**Comment by LPJon** [comment]
Hey everyone. I ran into this problem here a while back. This is related to Ubuntu and the way they handle x sessions. There is no desktop tab because the agent can't detect an x session in Ubuntu. This is because an x session is not started now until a user actually logs in and stays logged in. A work around for this is to install Ubuntu without a desktop GUI and then manually install the desktop you want after or to setup a user to automatically login at boot. Hope this helps!

**Comment by bkgoodman** [comment]
Thanks! That DOES explain why my previous cases where I installed desktop after that fact works - but I DID enable auto-login (now) and when doing so was when I got no desktop or tab (it was when I disabled auto login which was when the desktop TAB came back - but got that KVM error.)

**Comment by si458** [comment]
@LPJon this isn't the case for me
I have automatic login disabled and when i restart the desktop and sit at the login prompt I can connect into the desktop no issues at all
But again In my case the issue was the stupid wayland being enabled and needed disabling otherwise you get a black screen

**Comment by LPJon** [comment]
@si458 Yeah that was the other one I forgot about was wayland. As far as @bkgoodman goes he needs to get X11 support going and then he should be good but as he stated above he's getting the `"KVM Child Process has unexpectedly existed"` error which is related to the auto-login issue. When you  enabled auto-login again I assume you did perform a reboot then test? As a side note, if you allow the user to logout after login or lock after login you will get the KVM error.

**Comment by LPJon** [comment]
I went and dug up what settings I had to configure to get this working. So you need to edit the `custom.conf` file located at `/etc/gdm3/custom.conf` with the following:

```
...
[daemon]
# Uncoment the line below to force the login screen to use Xorg
WaylandEnable=false  <--------

# Enabling automatic login
#  AutomaticLoginEnable = true
#  AutomaticLogin = user1

# Enabling timed login
#  TimedLoginEnable = true
#  TimedLogin = user1
#  TimedLoginDelay = 10

AllowRoot=true

AutomaticLoginEnable=True  <--------------
AutomaticLogin=<user to auto login> <------------
...
```

Then reboot the system and test.

Note: if you need the whole file contents I can list it here for you.

**Comment by bkgoodman** [comment]
@LPJon I used those settings - and it appears to work!  
  
(I _am_ still having the issue where on bootup agent is running, but does not connect until I manually _restart_ the agent - but that's a different issue.) **Should I open a separate bug??**

I think it was a matter of getting all 3 of those things configured properly - at the same time! Thanks all!

**Comment by si458** [comment]
@bkgoodman if you can open another issue that would be great

Is it OK to also assume you can close this issue as its fixed?

We can track the Ubuntu 22.04 black screen issue with the other issues that's already open

**Comment by bkgoodman** [comment]
Closing, per above...
