### ISSUE TITLE
Feature Request: HTTP relaying in browser

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4172]
**Is your feature request related to a problem? Please describe.**
we monitor several freepbx servers using meshcentral,
its annoying having to load up meshcentralrouter, to then relay port 80 over to my localhost:8080
to then open up my browser to then visit `localhost:8080` to then access the web ui

**Describe the solution you'd like**
it would be amazing if you can relay ports using the meshcentral web ui
E.G: `https://myserver.com/httprelay/(NODEID)/(PORT)`
then the meshcentral server would talk to the remote host on that port asked but then forward you all the http traffic

**Describe alternatives you've considered**
having to open up meshcentralrouter to do port relay,
we have several chromebooks in the office (which are faster and quicker) but sadly cant run meshcentralrouter

**Additional context**
this would only be designed for HTTP !? i understand raw TCP wouldnt work

**Comment by veitw** [comment]
I second this feature. This corresponds to a feature I suggested in a comment to one of @Ylianst 's YouTube videos.

**Comment by LPJon** [comment]
I would also use this a lot. Would also be nice to relay HTTPS as well. Same here, we manage firewalls and freepbx systems as well and this would make management a lot easier and versatile for access to their web UI's. Might even let us hide them from the local network as well.

**Comment by Ylianst** [comment]
Working on it. Nice to see this feature is so requested. The way I am going to do this is to allow you to open a new "Web Relay" port on your MeshCentral server, like port 453. When the browser hits that port, the request is redirected to the target device. I will be setting a cookie in the browser to know what target the user selected.

A lot of web sites will not work properly when the root path changes, so accessing `http://192.168.0.1/...` will work, but accessing `https://meshcentral.com/webrelay/nodeid/port/...` to the same site will break the site. So, the idea is to keep the root path correct with `https://meshcentral.com:453/...`. Having a different web server on a different port also allows me to set different security headers for the relay site.

Anyway, I got a good start on it, this is going to be a may-day project.

**Comment by si458** [comment]
@Ylianst this is perfectly fine no rush! Can't wait to test the feature!

**Comment by Ylianst** [comment]
The first version will have a single port, but I am add more and/or support the long URL's that may break sites using the same code. It's going to be lots of work to support HTTP chunking, large files, web sockets... so, I will take it a bit at a time.

**Comment by LPJon** [comment]
@Ylianst Please be sure to allow subdomains exclusively. Remember not all setups use the `domain.tld` scheme. In such as my case the `domain.tld` is a completely different website so it would only be accessible by `https://sub.domain.tld:453/webrelay/nodeid/port/...`. I depend on the sub domain being able to handle the requests instead of the main domain.

**Comment by Ylianst** [comment]
@LPJon Not sure I completely understand, but regardless of that DNS name or IP address you are using to access MeshCentral, you will be able to use that DNS/IP to access the web relay port and remotely access the web page of devices. So, both will work:

```
https://domain.tld:453/
https://sub.domain.tld:453/
```

Again, I can make this sort of the URL perform the relay:

```
https://sub.domain.tld:453/webrelay/nodeid/port/...
```

But many web sites will break when when doing this.

**Comment by LPJon** [comment]
I know plenty of older ones will break. Ones that depend on the URI probably will too. Will that connection be secured with a cookie so that only a registered user can use the connection?

**Comment by Ylianst** [comment]
Good question, yes, the web relay port is TLS secured and authenticated using the session cookie regardless of what web site you access (HTTP or HTTPS on the remove side). Also, if the remote device sends you a cookie, MeshCentral will keep it during the session and send it back when you make any requests, so the cookies of the remove device don't flow over your the browser.

**Comment by Ylianst** [comment]
Almost ready to release this, however WebSocket relay is not yet supported and I can do better on performance.

**Comment by Ylianst** [comment]
Quick update: I am hoping to release MeshCentral v1.0.42 later today with the first version of the new web relay system, so far it looks pretty good and I working on websocket support which is the last thing I am going to do for this initial version. There is plenty more to do, like adding compression support to web socket, etc. But this should work for a first version.

**Comment by Ylianst** [comment]
Ha! Just as I saw your first edit, I made the exact same fix in GitHub. Let me know what you think!

**Comment by Ylianst** [comment]
Doh. I noticed that the way I handle cookies is not correct, I am going to have to do a bunch of fixing around that.

**Comment by si458** [comment]
> Doh. I noticed that the way I handle cookies is not correct, I am going to have to do a bunch of fixing around that.

another server runs mailenable, which redirects http to https
so HTTP doesnt work as expected (diverts to https://127.0.0.1 for some weird reason rather than https://[the ip or sitename])
but HTTPS shows the login correctly!
BUT when i login its the same thing as the openmediavault, it requests a login.php file gets 200, goes to anotherpage.php, then shows session times out please re-login, its not handling cookies correctly i believe

**Comment by Ylianst** [comment]
MeshCentral v1.0.43 is out.

**Comment by smartekIT** [comment]
> EDIT: @vtacquet suggested we could have an option to allow us to specify which TCP port we want relaying!

That would be great to be able to specify the relay port.

**Comment by Ylianst** [comment]
Added a way to change the HTTP and HTTPS ports, will be in v1.0.44.

![MC2-HttpAltPorts](https://user-images.githubusercontent.com/1319013/176830692-61e187ab-01cd-4901-af48-e72bdc922050.png)

**Comment by Ylianst** [comment]
@si458 For web site that redirect from HTTP to HTTPS, I am not sure there is anything I can do to fix this. When you first hit the web redirection port, your browser is set with a cookie that indicates the target device, port and if it's TLS or not. After that, each request you make is forwarded using these settings. When the site redirects to HTTPS, for MeshCentral, it's just a jump to a different URL path, but I don't know there is a switch to TLS or what the HTTPS port is, so I keep redirecting in HTTP and try to get the new path which does not work. There is no good solution.

**Comment by si458** [comment]
@ylianst that's the issue tho, freepbx isn't doing any redirects from http to https?

It would normally forward from http://myip to http://myip/admin/

But for some reason meshcentral is redirecting from https to http even though I selected http?

Is the a debug option you can make so I can try figure out what's going on?

**Comment by si458** [comment]
@Ylianst nearly there with the new alt port relay but hit a HUGE bug
```
2022-07-01T06:35:06.114483640Z ERR: /opt/meshcentral/meshcentral/apprelays.js:641
2022-07-01T06:35:06.114516697Z             if (header.connection.toLowerCase() == 'upgrade') {
2022-07-01T06:35:06.114526157Z                                   ^
2022-07-01T06:35:06.114534065Z 
2022-07-01T06:35:06.114541324Z TypeError: Cannot read properties of undefined (reading 'toLowerCase')
2022-07-01T06:35:06.114548886Z     at processHttpResponse (/opt/meshcentral/meshcentral/apprelays.js:641:35)
2022-07-01T06:35:06.114556337Z     at processHttpData (/opt/meshcentral/meshcentral/apprelays.js:490:17)
2022-07-01T06:35:06.114563709Z     at processRawHttpData (/opt/meshcentral/meshcentral/apprelays.js:443:13)
2022-07-01T06:35:06.114571088Z     at WebSocket.<anonymous> (/opt/meshcentral/meshcentral/apprelays.js:420:21)
2022-07-01T06:35:06.114578966Z     at WebSocket.emit (node:events:537:28)
2022-07-01T06:35:06.114586363Z     at Receiver.receiverOnMessage (/opt/meshcentral/meshcentral/node_modules/ws/lib/websocket.js:720:20)
2022-07-01T06:35:06.114594210Z     at Receiver.emit (node:events:537:28)
2022-07-01T06:35:06.114601542Z     at Receiver.dataMessage (/opt/meshcentral/meshcentral/node_modules/ws/lib/receiver.js:405:14)
2022-07-01T06:35:06.114609123Z     at Receiver.getData (/opt/meshcentral/meshcentral/node_modules/ws/lib/receiver.js:346:17)
2022-07-01T06:35:06.114616649Z     at Receiver.startLoop (/opt/meshcentral/meshcentral/node_modules/ws/lib/receiver.js:133:22)
2022-07-01T06:35:06.114624219Z 
2022-07-01T06:35:06.114631327Z Node.js v18.4.0
2022-07-01T06:35:06.175745126Z Error: Command failed: /usr/local/bin/node /opt/meshcentral/meshcentral/meshcentral --launch 7
```

also when i set a port i expected it to automatically open the web page in a new window, instead i had to click the HTTP option again for it to open the window?

**Comment by Ylianst** [comment]
Just put in a fix for the two server exceptions you got.

EDIT4: Once you set the HTTP or HTTPS alternate port, the new port is set for this device. You can then hit the HTTP port link and it will keep using the alternate port until you right click and set it back. Maybe I should do something different.

I will need to check on the other issues, I am sure as I try to debug more web sites, I will find more edge cases.

**Comment by si458** [comment]
> EDIT4: Once you set the HTTP or HTTPS alternate port, the new port is set for this device. You can then hit the HTTP port link and it will keep using the alternate port until you right click and set it back. Maybe I should do something different.

the issue i have is openmediavault uses 80 for web panel but then port 9000 for its portainer (docker)

so i would have to open http port 80 first to openmediavault, but then go bk into the panel right click, set alt port 9000 to then click http to open portainer? its very long winded!

it also doesnt help its remembering the port between open/close of the browser, i open portainer port 9000, close browser
reopen browser, click http it loads portainer but im expecting it to load http port 80 to gui for openmediavault

**Comment by si458** [comment]
> Just put in a fix for the two server exceptions you got.

im still getting the same error as before even with the fix?
```
2022-07-01T09:38:55.373448745Z TypeError: Cannot read properties of null (reading 'connection')
2022-07-01T09:38:55.373505609Z     at processHttpResponse (/opt/meshcentral/meshcentral/apprelays.js:641:32)
2022-07-01T09:38:55.373515057Z     at processHttpData (/opt/meshcentral/meshcentral/apprelays.js:496:21)
2022-07-01T09:38:55.373523022Z     at TLSSocket.<anonymous> (/opt/meshcentral/meshcentral/apprelays.js:411:66)
2022-07-01T09:38:55.373531133Z     at TLSSocket.emit (node:events:537:28)
2022-07-01T09:38:55.373538538Z     at addChunk (node:internal/streams/readable:324:12)
2022-07-01T09:38:55.373546018Z     at readableAddChunk (node:internal/streams/readable:293:11)
2022-07-01T09:38:55.373553867Z     at Readable.push (node:internal/streams/readable:234:10)
2022-07-01T09:38:55.373561370Z     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
2022-07-01T09:38:55.373568940Z     at Duplex.ondata (node:internal/js_stream_socket:77:22)
2022-07-01T09:38:55.373576511Z     at Duplex.emit (node:events:537:28)
```

**Comment by smartekIT** [comment]
how about the settings in config.json specially after you implemented the port change features, should stay the same?
<pre>
{
  "settings": {
    "port": 443,
    "RelayPort": 453
  }
}
</pre>

**Comment by si458** [comment]
> how about the settings in config.json specially after you implemented the port change features, should stay the same?
> <pre>
> {
>   "settings": {
>     "port": 443,
>     "RelayPort": 453
>   }
> }
> </pre>

I'm not sure i understand what you mean?
You need to set the relayport to use the new relay feature

**Comment by smartekIT** [comment]
Sorry I think I got confused. Now understand that port in the config.json
is a port on the server.

**Comment by mwllgr** [comment]
Just wondering: Can I use this without having to open another port by reverse proxying it onto a subdomain via nginx?

**Comment by si458** [comment]
> Just wondering: Can I use this without having to open another port by reverse proxying it onto a subdomain via nginx? Or would that maybe mess up something with cookies etc.?

Sadly I believe its only another port at the moment, 
But I'm sure @ylianst could look into using a domain instead of a port to link into the existing default port

**Comment by Ylianst** [comment]
Oh, using a different DNS name with the reverse proxy is an interesting idea! I had not considered this. Open a new issue asking for this, I can work on it. It will also solve any issues with people not being able to access non-80/443 ports from their networks.

**Comment by Ylianst** [comment]
MeshCentral v1.0.45 will how the alternate port in the link if it's not default.

![image](https://user-images.githubusercontent.com/1319013/176972308-fd99203f-6dbf-41bb-9525-384f7f613291.png)

**Comment by si458** [comment]
ok i will close this issue as the relay does work!
but it cant seem to do multiple relays at the moment, so ill create a new feature request for this

**Comment by barart** [comment]
How to use this with nginx proxy manager? I have my mesh configured like this on nginxpm:

mesh.mydomain.com -> myserverhostname.mydomain.com:5000

So, when i click on the https link it send me to: mesh.mydomain.com:453 (do not exists)

If i manually change the url on the opened tab to myserverhostname.mydomain.com:453/xxxxxallmoretextxxxxxx it open a blank website not the website in expecting 

Im stucked on this... what else do I need to do?

**Comment by barart** [comment]
Ok, i figured it out, the clue is to add a stream on nginx proxy manager... in case somebody has the same configuration as me:

1) Open your desired relay port on config.json (453)
2) Add the same port on your host docker container or any other port that you want but pointing to the meshcentral container port that you added on your config.json (453:453)
3) On nginx proxy manager add a STREAM from your config.json relay port to your host and docker port (453 -> yourmeshdomain.tld or yourmesh.yourdomain.tld)
4) Same as step 2 but now for your nginx proxy manager container, expose/add your port (453:453)
And your are done
Extra step only for those that are behind a router/firewall dont forget to open the port

**Comment by 12nick12** [comment]
It'd be great to have multiple http/s relay ports, I know we can set them, but it'd be nice to be able to have more than the one.

**Comment by barart** [comment]
> It'd be great to have multiple http/s relay ports, I know we can set them, but it'd be nice to be able to have more than the one.

+1 on this, that would be great to keep them saved too so you dont have to add them every time you login to meshcentral, something like this:

https/8080 https/8081 http/8079 and so on, maybe add a short name on the alternate port like https/web1:8080.. or a section with all the relayports
