### ISSUE TITLE
WebRTC black screen remote video

### ISSUE THREAD

**Issue by Vladislavlr** [Ylianst/MeshCentral#4173]
Hello. A use next config for create room 
  peer = new Peer(room_id)

  new Peer({iceServers: [
      {urls: 'stun:stun.l.google.com:19302'},
      {
        url: 'turn:numb.viagenie.ca',
        credential: 'muazkh',
        username: 'webrtc@live.com',
      },
    ],})
They say to solve the problem you need to specify a STUN server / But where now to enter the room_id ?

**Comment by silversword411** [comment]
I see docs talk about stun some, maybe that is of use?

https://ylianst.github.io/MeshCentral/design/#browser-to-agent-relay-and-webrtc

**Comment by Vladislavlr** [comment]
@silversword411 maybe you can example code?

**Comment by si458** [comment]
i dont think this is in relation to meshcentral so closing stale issue
