### ISSUE TITLE
100% quality not available

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#4175]
I updated to latest version
![image](https://user-images.githubusercontent.com/18248938/175553954-9ab6d073-629b-4009-beac-b2541eb7706f.png)

And was hoping to have quality 100% as shown in this thread

[loseless quality](https://github.com/Ylianst/MeshCentral/issues/3697)

but no go
![image](https://user-images.githubusercontent.com/18248938/175554248-3b88da1f-50d6-4438-8a17-e44ab9dff68c.png)

I added the setting to config.json too

![image](https://user-images.githubusercontent.com/18248938/175554340-5d709bc3-2dec-4960-912e-29c7c0d066ab.png)

Thank You!

**Comment by si458** [comment]
**plz can you follow the template for support in the future**

what remote device are you running/connecting to?
are you using the WebUI or meshcentralrouter?
allowhighqualitydesktop is already set to true from the word go
https://github.com/Ylianst/MeshCentral/blob/726ce8bdddbfd06c3e423c65cfbdf70718cabcf4/meshcentral-config-schema.json#L137

**Comment by kpetrow** [comment]
> what remote device are you running/connecting to?
a computer on a remote network.  I have scripted the "add agent" button, but for this test i manual downloaded the "add agent"

are you using the WebUI or meshcentralrouter?
WebUI
![image](https://user-images.githubusercontent.com/18248938/175559704-c8fba54c-af18-436a-ab57-0316c8b934df.png)

**Comment by si458** [comment]
@kpetrow ok i can verify i also dont see the 100% option here either so im not 100% sure why?
HOWEVER if i use the MeshCentral Router, and click options, the is a 100% option there and that looks to do the treatm
can you please try the router and let us know if that works correctly for you?

**Comment by kpetrow** [comment]
@si458 I have never used the router.  I just installed it but not sure where to go from there.  Watching youtube vids now....

**Comment by kpetrow** [comment]
everything looks correct on the router.  I just need 100% view on the web interface.  Can that be done?  

Specifically i need to generate remote url using DeviceSharing and have it set to 100.  Can i just do this in sharing.handlebars
`        var desktopsettings = { encoding: 2, showfocus: false, showmouse: true, showcad: true, quality: **100**, scaling: 1024, framerate: 100, localkeymap: false };
`

**Comment by bkgoodman** [comment]
I to have only ever been able to get 60% on any machine (Linux or Windows - endpoints and Web GUI). I assumed this was a deliberate limitation of the Public MeshCentral server? (Maybe not?)

**Comment by silversword411** [comment]
> 60% on any machine

This defaults to higher quality

https://github.com/Ylianst/MeshCentral/blob/571a0f1c2d5807d6e3fb9b8c98c7a5c339acf54b/meshcentral-config-schema.json#L137

**Comment by openncomp** [comment]
How strange, I also don't have a 100% quality choice in the web interface.
MC v1.0.41
![screen](https://user-images.githubusercontent.com/92163803/175814549-c3dfc466-be63-4f0b-9224-b8bc2ffb9935.gif)

**Comment by si458** [comment]
the qualities are hard coded,
can people try my PR #4181 please?

**Comment by Ylianst** [comment]
@si458 Added the 100% quality in a PR and I accepted it. JPEG does not have a loss-less mode, so there is no such thing as 100% quality, but that's ok, I am willing to give this a try.
