### ISSUE TITLE
7 Day Power State

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#4177]
![Screenshot 2022-06-25 at 09 28 52](https://user-images.githubusercontent.com/23058718/175765340-bbe3c5c2-0924-41e2-b138-6a2c9d04b74a.png)
this is what im getting at at the moment

**Comment by silversword411** [comment]
Is that a question, or a statement?

**Comment by kylelliott** [comment]
question why is like this for

**Comment by vitko-bg** [comment]
Like what? Please clarify.
Like this, in a rows, in strange color, is what?

**Comment by vitko-bg** [comment]
If @Ylianst will see the post, will close it immediately. Just an advise to provide at least a bit more info.

**Comment by petervanv** [comment]
> ![Screenshot 2022-06-25 at 09 28 52](https://user-images.githubusercontent.com/23058718/175765340-bbe3c5c2-0924-41e2-b138-6a2c9d04b74a.png) this is what im getting at at the moment

![image](https://user-images.githubusercontent.com/58996467/175829835-df0e7cfe-6b59-4406-9c7c-d60c612c4671.png)

1. Black color: device is powered om
2. purple color: device is in sleep state
3. blue/green color : device is connected trough amt/cira, but not powered on
4. grey color: device is powered off

so your power state screenshot shows the device is powerd on al long time.

Hope this clarified your question.

**Comment by si458** [comment]
> > ![Screenshot 2022-06-25 at 09 28 52](https://user-images.githubusercontent.com/23058718/175765340-bbe3c5c2-0924-41e2-b138-6a2c9d04b74a.png) this is what im getting at at the moment
> 
> ![image](https://user-images.githubusercontent.com/58996467/175829835-df0e7cfe-6b59-4406-9c7c-d60c612c4671.png)
> 
>     1. Black color: device is powered om
> 
>     2. purple color: device is in sleep state
> 
>     3. blue/green color : device is connected trough amt/cira, but not powered on
> 
>     4. grey color: device is powered off
> 
> 
> so your power state screenshot shows the device is powerd on al long time.
> 
> Hope this clarified your question.

plz can you do a PR to add this to the docs!
this was indeed very helpful!
i dont use AMT and didnt realise it actually changes colour haha

**Comment by silversword411** [comment]
I only see black on my instance, but I don't have any AMT deployed atm. Probably why :)

**Comment by petervanv** [comment]
> I only see black on my instance, but I don't have any AMT deployed atm. Probably why :)

The black and grey color is also for clients (nodes) without Intel AMT ! it just show its state off the node, not off Intel AMT

**Comment by si458** [comment]
added to docs - https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#7-day-power-state
