### ISSUE TITLE
Feature Request: Server Info

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#418]
On the My Server tab I would like to see a Server Info section with the server's basic configuration displayed.

It should show the current settings for all the options in the installer (just display what the current settings are, doesn't need to be able to change them) as well as the current version and uptime.

If possible also including host details and a button to download or copy to clipboard would assist in gathering relevant information when troubleshooting server issues.

**Comment by Ylianst** [comment]
This is a good idea. I am a bit busy (or crazy busy), but this is a good request.

**Comment by b8two** [comment]
It would be good to also have RAM and Disk Space usage.

**Comment by Ylianst** [comment]
This feature is really in demand (including RAM and Disk Usage). You can type "sysinfo" and "cpuinfo" in the agent console now to see the information the agents pulls. I need to add server support for this.

**Comment by billydu1980** [comment]
On the server Info section, maybe show server FRU info(manufacturer、product-name ) is good idear. In Linux host OS, call dmidecode command output info.

**Comment by si458** [comment]
the `my server` tab now shows memory and cpu usage
