### ISSUE TITLE
Meshrouter does not work for users who have individual devices assigned to them but not that device's group

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshCentral#4188]
**Describe the bug**
Meshrouter has no devices listed in the devices tab for most users and I haven't been able to find the difference. 

EDIT: As I worked with si458 we found the bug can be summariezed better as this

If a user has permissions to a single device it wipes out their ability no matter their permissions to see ANY devices in MeshCentral Router

**To Reproduce**
Open MeshRouter with valid credeintals, and the devices tab is empty. But not for all users, one of my admins still has everything another has nothing

**Expected behavior**
Devices being listed in MeshRouter

**Server Software (please complete the following information):**
 - OS: Alpine
 - Virtualization: Docker
 -  - Network: WAN/Reverse Proxy NGINX for SSL
 - Version: 1.0.41
 - Node: Don't know
 - Browser: N/A

**Remote Device (please complete the following information):**
 - Device: All
 - OS: All
 - Version: All
 - Current Core Version (if known): All

**Additional context**
Happy to do more testing to try to find a pattern. Devices all show if you log in on the web interface. But MeshRouter is totally blank

**Comment by si458** [comment]
have you tried downloading the latest version that was updated 22 days ago?
https://github.com/Ylianst/MeshCentral/raw/master/agents/MeshCentralRouter.exe

also what OS are you running the router on? mac/windows?

**Comment by githubbiswb** [comment]
I am using the MeshCentral Router that is a part of the updated install of meshcentral and tried that one as well, same results, but I would expect that download to be the one included from the server

Windows is running MeshCentral Router

Again, some users are just fine, others are not, so it doesn't seem to be a software issue with the router, but instead a server setting keeping users from seeing what they need to see

**Comment by si458** [comment]
what features are you assigning to the user?
aalso what features for groups or devices?
im just trialing here and i cannot get it to misbehave and not show any device, it always shows devices?

**Comment by githubbiswb** [comment]
Yep, makes sense. Users have full administrator privileges and see nothing

Another user has full administrator privileges and sees everything

Another user has limited privileges, Control (No Terminal, No Files, No AMT) and sees nothing while being assinged to a specific group and specific device

Another user has limited privileges,  Control (No Terminal, No Files, No AMT) and sees everything when assigned to a specific group

**Comment by si458** [comment]
can you take a screenshot of the user screen - showing the email, name, features, groups, etc from the web ui?
the user with limited control to specific group thats not showing anything
(blank sensitive stuff if needs be)

**Comment by githubbiswb** [comment]
![0zsbHCaMwX](https://user-images.githubusercontent.com/51446227/176191492-fb0cfabd-e137-419d-a54d-1cdf9c14cc4d.png)

**Comment by githubbiswb** [comment]
Sorry, and also the users can all see what they need to see and should see in the web gui interface too, so they do have permissions that I can verify do work, its just they don't seem to work with MeshCentral Router

**Comment by githubbiswb** [comment]
I can't seem to make it write a log, I do have it in C:\Program Files\Mesh Agent\MeshRouter.exe and am running it as a normal user, so maybe it can't write that log there? But then I ran it as an Admin and that also didn't generate a log file

**Comment by githubbiswb** [comment]
I also tried it from a temp location that I do have write access as a normal user, and nothing, you clearly got logs so I would say those would be the ones I trust since I can't seem to generate them

**Comment by githubbiswb** [comment]
Ah,  yep that makes sense and a good work around

The one I have implemented is moving the device off to a group all by itself and giving the user permissions to that group that only has the one device. I only state this for anyone that might come behind and want to work around this issue while its resolved.

**Comment by kj7ice** [comment]
I am experiencing this exact issue as well for users only with permission to a single device, and the error in my debug log matches what was posted earlier. My MeshCentral server version is 1.0.38.

**Comment by si458** [comment]
> I am experiencing this exact issue as well for users only with permission to a single device, and the error in my debug log matches what was posted earlier. My MeshCentral server version is 1.0.38.

It's present the in the latest version too 1.0.41
It's a bug with meshcentralrouter I believe not the server side
Follow the issue here https://github.com/Ylianst/MeshCentralRouter/issues/46

**Comment by Ylianst** [comment]
I just put in a fix for this and seems to work. This was broken since the new UI. Will be in MeshCentral 1.0.45 which I will publish shortly.

**Comment by si458** [comment]
this has indeed been fixed in 1.0.45, i can confirm here using installing new 1.0.45 and downloading new meshcentralrouter.exe from the web ui and using that, fixes the issue!
this issue can be closed now

**Comment by githubbiswb** [comment]
Confirming and closing here as well, thank you everyone for all of your hard work!
