### ISSUE TITLE
google authenticator code expiring too fast

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#419]
Hi Ylian,
I've enabled Google Authenticator for my user account, now I have over 700 machine inside meshcentral, it's mandatory.
It's working pretty good, but I've noticed I have to insert token in page textbox very fast after ID is changed on app, or it's rejected. 
I think meshcentral timeout is faster than GA app...

Hope this helps

Cheers

Merlinweb

**Comment by Ylianst** [comment]
Looking at the code (webserver.js line 571), I set the OTP time window to +/- 2 minutes, which is pretty a pretty big window. 5 codes are probably valid at any given time. The main problem is the your server (or phone) don't have the right time. Set your clocks and let me know if that fixes it. Maybe using NTP on the server would help.

**Comment by Ylianst** [comment]
Going to close this one as I think setting the time on the server correctly should solve this. Please re-open if needed.
