### ISSUE TITLE
Feature request: "Just customise (and sign) agent binaries and exit" command line feature

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#4190]
**Is your feature request related to a problem? Please describe.**
Currently we use a dedicated firewalled machine that downloads the agent executables from the MC server before an update is applied, then locally sign them and upload them back to the MC server, replacing the original files and recalculate the hashes (for the future we are planning to replace it with using the meshcental-data/agents/ directory instead). 

Unfortunately this process does not work with the new agent customisation feature, and this presumably applies to any other situation where it is not acceptable to allow MC to access the code signing (sub) CA privkey.

**Describe the solution you'd like**
It would be great to have MC include a separate command or add a command line parameter that simply performs the binary customisation and/or signing, and then exits with an exit code indicating success resp. failure.

With such a feature, one could either perform the binary customisation and/or signing directly from the offline CA machine with a copy of MC (maybe in a container), or perform the binary customisation directly on the MC machine before the binaries are being downloaded to the (sub) CA machine for signing.

**Additional context**
This refers to [my comment on the binary customisation video on YouTube](https://www.youtube.com/watch?v=xYtk85Bmc8Q&lc=UgwFNRogNJE3V6e8KI54AaABAg).

**Comment by Ylianst** [comment]
MeshCentral comes with authenticode.js, you can run it like this:

```
node node_modules/meshcentral/authenticode-js
```

It should give you this text:

```
MeshCentral Authenticode Tool.
Usage:
  node authenticode.js [command] [options]
Commands:
  info: Show information about an executable.
          --exe [file]             Required executable to view information.
          --json                   Show information in JSON format.
  sign: Sign an executable.
          --exe [file]             Required executable to sign.
          --out [file]             Resulting signed executable.
          --pem [pemfile]          Certificate & private key to sign the executable with.
          --desc [description]     Description string to embbed into signature.
          --url [url]              URL to embbed into signature.
          --hash [method]          Default is SHA384, possible value: MD5, SHA224, SHA256, SHA384 or SHA512.
          --time [url]             The time signing server URL.
          --proxy [url]            The HTTP proxy to use to contact the time signing server, must start with http://
  unsign: Remove the signature from the executable.
          --exe [file]             Required executable to un-sign.
          --out [file]             Resulting executable with signature removed.
  createcert: Create a code signging self-signed certificate and key.
          --out [pemfile]          Required certificate file to create.
          --cn [value]             Required certificate common name.
          --country [value]        Certificate country name.
          --state [value]          Certificate state name.
          --locality [value]       Certificate locality name.
          --org [value]            Certificate organization name.
          --ou [value]             Certificate organization unit name.
          --serial [value]         Certificate serial number.
  timestamp: Add a signed timestamp to an already signed executable.
          --exe [file]             Required executable to sign.
          --out [file]             Resulting signed executable.
          --time [url]             The time signing server URL.
          --proxy [url]            The HTTP proxy to use to contact the time signing server, must start with http://

Note that certificate PEM files must first have the signing certificate,
followed by all certificates that form the trust chain.

When doing sign/unsign, you can also change resource properties of the generated file.

          --filedescription [value]
          --fileversion [value]
          --internalname [value]
          --legalcopyright [value]
          --originalfilename [value]
          --productname [value]
          --productversion [value]
```

You can use this to sign an agent. For example:

```
node node_modules/meshcentral/authenticode-js sign --exe "/tmp/MeshService.exe" --filedescription "description"
```

If you only want to change the resource properties without signing, use `unsign`:


```
node node_modules/meshcentral/authenticode-js sign --exe "/tmp/MeshService.exe" --filedescription "description"
```

In testing it, there was a bug with `unsign` when you want to change resources and I just fixed it. It will be in MeshCentral v1.0.43. I am going to update the standalone [Authenticode-JS](https://www.npmjs.com/package/authenticode-js) now with that fix.

Let us know if that works.

**Comment by veitw** [comment]
@si458, @Ylianst: Thanks to both of you.

Using authenticode-js directly seems to work great.
