### ISSUE TITLE
Scheduled Task and/or scripts.

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4191]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I like to have my computers reboot daily around 2am. It would be nice to have this done within this software, like a daily task.

**Comment by veitw** [comment]
@meh324: You might be interested in the [ScriptTask plugin](https://github.com/ryanblenis/MeshCentral-ScriptTask) by @ryanblenis, which implements this exact feature (and a bunch of others, too).

**Comment by veitw** [comment]
@meh324: Yeah, that installation instructions are somewhat short.

1. Enable plugins in the configuration and restart MC as described.
2. Log into MC as full administrator.
3. Go my `My Server` -> `Plugins`, hit the `Download plugin` button.
4. A dialog opens requesting an URL, put in: `https://github.com/ryanblenis/MeshCentral-ScriptTask`
5. The plugins pops up in the plugin list below the download button, you can now configure and enable/disable it.

**Comment by veitw** [comment]
@meh324: You put the `plugins` section inside the `domain` -> `""` section, but it belongs in the `settings` section, as it changes the global behaviour of the server, not of a single domain.

For details on the configuration file format, refer to the config schema: https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json

**Comment by veitw** [comment]
@meh324: Glad to help you. :)
