### ISSUE TITLE
1.0.42 WebUI glitch

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#4192]
Since update to 1.0.42 there seems to be an UI glitch on bottom right of Desktop-View....
<img width="254" alt="image" src="https://user-images.githubusercontent.com/68963439/176515144-80f33a29-74a5-401d-9f7c-98ef2ee59857.png">

**Comment by JSuenram** [comment]
> I imagine this is the German translation that is the issue?

I guess it is just a missing < or something. Busy, so I am sorry, can not look in source by myself....

**Comment by Ylianst** [comment]
Will be fixed in MeshCentral v1.0.43 that I will release later today.

**Comment by Ylianst** [comment]
v1.0.43 is out.
