### ISSUE TITLE
User Action Log not logging events in meshcentral.com

### ISSUE THREAD

**Issue by datapharmer** [Ylianst/MeshCentral#420]
It seems the feature for #375 is not working on meshcentral.com. If I connect to the desktop etc. the event is not recorded.

**Comment by Ylianst** [comment]
Your correct, MeshCentral.com runs a older version of MeshCentral (currently 0.3.7-w). I will look into updating it soon.

**Comment by Ylianst** [comment]
FYI. Just updated MeshCentral.com to current version v0.4.1-m. All latest features should now be available.
