### ISSUE TITLE
notification of new release...

### ISSUE THREAD

**Issue by hs6666** [Ylianst/MeshCentral#4200]
Hi,

I'm "watching" for new releases on this github page, but not getting any email notifications of new releases ....

Which is the best way to get an email when any new release is made avaialble please so that i can update?

Thanks

**Comment by silversword411** [comment]
Need to find some docs to show @Ylianst so he can start using

https://github.com/Ylianst/MeshCentral/releases :)

**Comment by silversword411** [comment]
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by hs6666** [comment]
Personally for me, i find github emails invaluable, i use it for over 20 different github projects, I just tick the "security alerts" and "releases" only for all of them.

Missing some security update can become a serious headache, especially with meshcentral due to its scope and the increasing concerns over bad actors trying to use supply chain attacks, esecially with sprawling interconnection within npm packages......

Would be impossible to regularily check all the github projects i use individually

Meshcentral is a brilliant package and for now I'll bookmark the meshcentral twitter page :)

**Comment by Ylianst** [comment]
@silversword411 I just read your link on GitHub releases, first time I hear about this, very interesting. I will give it a try. The problem is that I make too many releases (sometimes multiple a week) and don't look forward to putting even more work on myself. But, I will try it and see where it goes.

**Comment by hs6666** [comment]
> @silversword411 I just read your link on GitHub releases, first time I hear about this, very interesting. I will give it a try. The problem is that I make too many releases (sometimes multiple a week) and don't look forward to putting even more work on myself. But, I will try it and see where it goes.

Personally I'd be quite happy with a release only being posted on the very rare unlikely case of a major security update (log4j type), resulting in an email notification to update....

**Comment by si458** [comment]
@Ylianst you could give this github action a try - https://github.com/marketplace/actions/automatic-github-release
it automatically creates a release every time the `package.json` version changes

**Comment by hs6666** [comment]
> @silversword411 I just read your link on GitHub releases, first time I hear about this, very interesting. I will give it a try. The problem is that I make too many releases (sometimes multiple a week) and don't look forward to putting even more work on myself. But, I will try it and see where it goes.

Personally I'd be quite happy with a release only being posted on the very rare unlikely case of a major security update (log4j type), resulting in an email notification to update....

**Comment by silversword411** [comment]
You definitely do a lot of releases. Just put the bigger ones in there.

**Comment by si458** [comment]
> You definitely do a lot of releases. Just put the bigger ones in there.
> 
> Just do 1.x not 1.x.x

i think my pr #4205 should help with automatic releases now,
but few steps must be followed first before merge!

**Comment by Ylianst** [comment]
Just created a sample release and pulled #4205.

**Comment by si458** [comment]
> Just created a sample release and pulled #4205.

Perfect worked a treat for 1.0.44!

You can now delete the releases you made saying `meshcentral_v1.0.44` and `meshcentral_v1.0.45` and just leave the single `1.0.44`

Now everytime you change the version in the `package.json` it will make a new release and include a copy of the commits in the notes!

It will always label the releases and tags as `x.x.x` without the meshcentral in the name 

We just need to stick to making the commit names like `added section to readme.md` rather than `updated readme.md` otherwise we don't no what changed exactly

**Comment by si458** [comment]
OMG 1.0.45 worked a treat for a release! Hope this helps @hs6666

**Comment by Ylianst** [comment]
Oh wow, this is great!!!! Even if I edit the description of the release afterwards, having this be automated as a starting point is absolutely wonderful.

**Comment by si458** [comment]
> 

its a very good starting point for users to help with changelogs, this issue can be closed now then :)

**Comment by hs6666** [comment]
Thank you for this, it's a biggie for me!

Everytime i install meshagent on a client I think my attack surface has just increased if my server ever gets compromised

Closing issue...

Harry

PS Next step... install crowsdsec and a bouncer on my meshcentral server... https://www.crowdsec.net/pricing for another layer of security

**Comment by Ylianst** [comment]
Can you open a new issue and request CrowdSec support? This could be interesting.
