### ISSUE TITLE
Import Userlist.json

### ISSUE THREAD

**Issue by drock850** [Ylianst/MeshCentral#4203]
I see how to export and import but not how to edit the json file.
If I wanted to do mass import of users, how would I edit the userlist.json file.

I have tried copying a user and pasting changing name and email and saving but when I import I get an error.

Can anyone explain or help guide me on this please thanks in advance.

**Comment by si458** [comment]
the import must be in JSON format.
you click the the import batch blue icon next to the export icon in the My Users tab,
you must use the format it shows on the screen and in JSON format
![Screenshot 2022-06-30 182017](https://user-images.githubusercontent.com/765314/176739366-745e9e0e-a653-4582-b0d9-78be6959ea87.png)

**Comment by drock850** [comment]
Thank you. I see that. But when I export my current list and then add users using that format it gives me an error.

**Comment by drock850** [comment]
Eureka. That would make more sense.
I was including the content from the exported Json file. 

So for example for one user this would work.

[
  {
    "user": "USER1","pass": "password1", "email": "abc@xyz.com" },
    "user": "USER1","pass": "password1", "resetNextLogin": true }
  }
]

Or could you make it one line.

[
  {
 "user": "USER1","pass": "password1", "email": "abc@xyz.com","resetNextLogin": true }
  }
]
