### ISSUE TITLE
Feature Request: HTTP relaying via subdomain

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#4210]
Following up on https://github.com/Ylianst/MeshCentral/issues/4172#issuecomment-1172740927

I think it should be possible to use another (sub-)domain for the new HTTP relaying feature. This would also make it possible for users in restricted networks (e.g. when only ports 80/443 are allowed) to use the feature.

Personally, I'd use nginx as a reverse proxy to use this feature. I have not tested to just point a reverse proxy to the new port.

Example:
Right now it's something like https://meshcentral.example.com:457 - with the new feature it should be possible to use https://relay.meshcentral.example.com or similar.

**Comment by Ylianst** [comment]
I like this idea. It allows you to not have to open a new port. Also, some networks are limited in what ports they can access due to HTTP proxy policies, this would get around that policy limitation.

**Comment by Ylianst** [comment]
I made some progress on this, I will need to get websockets working with the web relay DNS.

**Comment by Ylianst** [comment]
Ok, got it working. With MeshCentral v1.0.46, you will be able to add this line in the `settings` section of the config.json:

```
"relayDns": "relay.myserver.com"
```

**Comment by Ylianst** [comment]
MeshCentral v1.0.46 is out with this feature. Let me know if it works.

![MC2-WebRelayDNS](https://user-images.githubusercontent.com/1319013/177395769-a66154c9-e032-4a6a-97ab-2d558aa9a4f4.png)

**Comment by Ylianst** [comment]
Your right, let me fix that.

**Comment by vtacquet** [comment]
I also use a Traefik proxy in front, when using the RelayDns and proxying it to the same meshcentral port I get a "Not Found" page when clicking a HTTP or HTTPS link on a device (with version 1.0.48), as you can see the relay url has no subdirectory or filename, it just redirects to https://relay.something.com and is missing the control-redirect.ashx?... stuff as seen before in previous versions.

![CleanShot 2022-07-07 at 10 52 16](https://user-images.githubusercontent.com/5128967/177733237-1b8eb47c-e017-496a-a223-86ea97df25e2.png)

traefik router
![CleanShot 2022-07-07 at 10 54 18](https://user-images.githubusercontent.com/5128967/177733774-6c53e3f1-dc2a-43cf-b364-133edc1e1c9b.png)

traefik service
![CleanShot 2022-07-07 at 10 52 58](https://user-images.githubusercontent.com/5128967/177733528-b73c099e-1511-4d2a-82f5-f660222f4fd1.png)

mesh central config
![CleanShot 2022-07-07 at 10 55 15](https://user-images.githubusercontent.com/5128967/177733898-c59c0380-f1de-476f-8f62-9355ee82b074.png)

**Comment by si458** [comment]
im noticing the exact same thing with traefik but i dont use yaml i just docker labels instead
```
    labels:
      - traefik.enable=true
      - traefik.http.routers.meshcentral.rule=Host(`meshcentral.myserver.com`) || Host(`relay.meshcentral.myserver.com`)
      - traefik.http.services.meshcentral.loadbalancer.server.scheme=https
      - traefik.http.services.meshcentral.loadbalancer.server.port=443
```
traefik is showing as its hitting the container too but the container is returning 404?
```
217.14.1.1 - - [07/Jul/2022:11:32:08 +0100] "GET /control-redirect.ashx?n=node//uR0y36sTYRCEcL5BY@A1DPU4gaj8Sl44TUssE1aCb4i@WlDvVzq$hfk30S@l@Ynx&p=80&appid=1 HTTP/2.0" 302 46 "-" "-" 28077 "websecure-meshcentral@docker" "https://172.20.0.5:443" 4ms
217.14.1.1 - - [07/Jul/2022:11:32:09 +0100] "GET / HTTP/2.0" 404 9 "-" "-" 28078 "websecure-meshcentral@docker" "https://172.20.0.5:443" 2ms
```

**Comment by mwllgr** [comment]
Works for me now. Thanks guys!
