### ISSUE TITLE
Meshcentral not loading in iFrame in Chrome or Edge | Missing SameSite Attribute on Cookie

### ISSUE THREAD

**Issue by fsteltenkamp** [Ylianst/MeshCentral#4211]
Meshcentral fails to load in an iFrame on Chromium based Browsers.
I have tested this in: Chrome, Edge, Brave
Firefox works as expected.

I'm using the following HTML to log in without using the generated login token, since i couldn't get that to work.
Maybe getting the login token to work will resolve the issue, i don't know.
```html
<form method="POST" action="{{$frameUrl}}?viewmode=1&hide=13" target="rc_iframe" name="form_iframe_load" id="form_iframe_load">
    <input type="hidden" name="action" value="login"/>
    <input type="hidden" name="username" value="{{$user->meshcentral_username}}"/>
    <input type="hidden" name="password" value="{{$user->meshcentral_password}}"/>
    <input type="hidden" name="urlargs" value=""/>
</form>
<iframe class="iframeResize" name="rc_iframe" width="100%"></iframe>
```
On the browsers mentioned i can see the menu for a short second, then the iFrame displays the message "Web-Socket could not be connected, click to reconnect." (Translated from german)

The browser displays the following message:
![Screenshot 2022-07-02 133223](https://user-images.githubusercontent.com/80000261/176999083-897673e9-3874-4df1-96e8-ecdda4167f42.png)

This led me to believe that the cookie is not being set correctly by meshcentral.
Maybe it is and im doing something wrong, If so please tell me what i have to do :)

**config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongoDbBulkOperations": true,
    "cert": "mc.....",
    "WANonly": true,
    "LANonly": false,
    "sessionKey": ".....",
    "allowLoginToken": true,
    "allowFraming": true,
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "plugins": {
        "enabled": true
    }
  },
  "domains": {
    "": {
      "title": "Meshcentral",
      "title2": "SRV1",
      "deviceMeshRouterLinks": {
        "rdp":true,
        "ssh":true,
        "scp":true
      },
      "_minify": true,
      "_newAccounts": false,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "....",
    "names": "....",
    "production": true
  }
}
```

**Comment by si458** [comment]
i did a PR in version 1.0.49 which fixes the missing sitesame for the cookie, you can now set it in your config.json
`"sessionSameSite": { "type": "string", "default": "lax", "enum": ["strict", "lax", "none"] }`

**Comment by fsteltenkamp** [comment]
This works perfectly, thank you so much for the quick implementation!

**Comment by myintune365** [comment]
Thanks for the steps here, so I eventually got this working with:
 "settings": {
    "AllowFraming": true,
    "sessionSameSite": "none"
}

But obviously this isn't very secure, is it possible to limit iframes to specific hosts / urls?
