### ISSUE TITLE
Where's the backup gui?

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#4212]
I feel like I'm missing something simple. 

I was playing with this in the json

```
      "myServer": {
        "Backup": false,
        "Restore": false,
        "Upgrade": false,
        "ErrorLog": false,
        "Console": false,
        "Trace": false
      },
```

But Backup and Restore (which is true by default, and I made sure it was true), I can't see anything relating to it anywhere. 

![2022-07-02_084409 - backup and restore](https://user-images.githubusercontent.com/13395348/177001308-2e382520-690a-47ec-afe1-6ebe38e3d623.png)

**Comment by si458** [comment]
ssimilar issue to #4195
they did a fresh install and dthe options where missing but never happens here?

**Comment by silversword411** [comment]
Ok, so it's supposed to be under "Server actions". So sounds like bug...lets try and find all possible items that could be under there :)

**Comment by si458** [comment]
what sorta setup are you running `config.json` if possible?
as ive download a fresh copy of the git repo, `npm install` then ran `node .` and logged in and its showing the options?

**Comment by silversword411** [comment]
```json
{
  "settings": {
    "Cert": "<snip>",
    "MongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
    "WANonly": true,
    "Minify": 1,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "_AgentPing": 60,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "TlsOffload": "127.0.0.1",
    "agentCoreDump": false,
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": true,
    "PublicPushNotifications": true,
    "MaxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 30
    }
  },
  "domains": {
    "": {
      "Title": "<snip>",
      "NewAccounts": false,
      "CertUrl": "https://<snip>:443/",
      "GeoLocation": true,
      "CookieIpCheck": false,
      "mstsc": true,
      "_myServer": {
        "Backup": true,
        "Restore": true,
        "Upgrade": true,
        "ErrorLog": true,
        "Console": true,
        "Trace": false
      },
      "altmessenging": {
        "name": "Jitsi",
        "url": "https://meet.jit.si/myserver-{0}"
      },
      "SessionRecording": {
        "onlySelectedUsers": true,
        "onlySelectedUserGroups": true,
        "onlySelectedDeviceGroups": true,
        "index": true,
        "maxRecordings": 16,
        "protocols": [
          1,
          2,
          200
        ]
      }
    }
  }
}
```

Only 2-3 non-standard for a TRMM install. Jitsi, high quality desktop, session recording I believe.

**Comment by si458** [comment]
`_myServer` should be `myServer`

any variable beginning with an underscore `_` in the name is ignored, so all the variable under `myServer` are being ignored

**Comment by silversword411** [comment]
> `_myServer` should be `myServer`
> 
> any variable beginning with an underscore `_` in the name is ignored, so all the variable under `myServer` are being ignored

Yeah, default is true on everything though. That was just there for testing, and I had commented it back out again instead of deleting

**Comment by Ylianst** [comment]
Hi. The UI backup and restore option are only capable of creating and restoring a ZIP of the "meshcentral-data" folder and could not backup the database. So, they are now only available when using NeDB as your database. I removed them since it gave a false impression that a full backup had been done when it was not.

For MongoDB, the auto-backup will also backup the MongoDB database.  For other database options (MySQL, MariaDB and PostGreSQL) the auto-backup will just include meshcentral-data and not the database.

Let me know if that makes sense, I can update the schema to make this clear.

**Comment by Ylianst** [comment]
Ok, updated the schema. Let me know if that works or if anything else needs to be done.

**Comment by silversword411** [comment]
> So, they are now only available when using NeDB as your database

That'd explain what I'm seeing perfectly. 

I'd say just put that backup only works on neDB backed instances. I'll update the places appropriate I can find and PR it.

**Comment by Ylianst** [comment]
@silversword411 Thank you so much! I don't think your the first to ask about this.

**Comment by silversword411** [comment]
I guess that'd also apply to the Google drive backup stuff?

**Comment by si458** [comment]
ahh the NeDB, that explains why its showing here on my side and not over there,
because im just running it without an external DB!

**Comment by Ylianst** [comment]
@silversword411 This does not apply to Google Drive backup. When using NeDB or MongoDB, the background backup system will include a dump of the database prior to ZIP compression. Then, the ZIP is uploaded to Google Drive. So, at least with MongoDB, Google Drive should work.

**Comment by Ylianst** [comment]
I am going to close this since the original question was answered. If there are any backup issues, please open a new issue.
