### ISSUE TITLE
Tracing Agent Error Counters

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#4213]
**Is your feature request related to a problem? Please describe.**
Trying to track down Agent Errors eg Invalid signatures

![2022-07-02_084958 - mesh agent errors](https://user-images.githubusercontent.com/13395348/177001525-2cc1feb0-1da9-4b89-816d-c99ed5492f57.png)

**Describe the solution you'd like**
Clicking on an error category would give you a log with date/time/relevant data/and most importantly agent identifiers (name/IP etc) so you know where to start looking.

I'm trying to write up better "finding and fixing" errors for the docs. Right now, there's no Step 1, step 2 etc kind of process for tracking down these kinds of issues.

**Comment by si458** [comment]
ive been having the same problem, i had a random agent bad signature and i couldnt work out which agent it was?

**Comment by si458** [comment]
`agentstats` and `agentissues` commands from inside the Console Tab of the My Server Tab should help you!
```
12/26/2023, 4:02:29 PM, 79.77.xxx.xxx:49728, duplicateAgent
12/27/2023, 5:26:47 PM, 80.168.xxx.xxx:33859, duplicateAgent
12/27/2023, 7:56:51 PM, 79.77.xxx.xxx:51667, duplicateAgent
12/28/2023, 10:02:40 AM, 62.255.xxx.xxx:49730, duplicateAgent
12/28/2023, 2:45:53 PM, 62.255.xxx.xxx:49724, duplicateAgent
12/28/2023, 2:48:06 PM, 62.255.xxx.xxx:49894, duplicateAgent
12/28/2023, 2:59:13 PM, 62.255.xxx.xxx:49730, duplicateAgent
12/28/2023, 3:19:22 PM, 62.255.xxx.xxx:49728, duplicateAgent
12/28/2023, 3:29:18 PM, 62.255.xxx.xxx:49724, duplicateAgent
12/28/2023, 3:37:30 PM, 62.255.xxx.xxx:49733, duplicateAgent
```
