### ISSUE TITLE
Disable SSH/SFTP integration buttons

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#4214]
**Is your feature request related to a problem? Please describe.**
It is possible to disable the SSH/SFTP integration buttons.
If I leave the option, `"ssh": true,` so that it is possible to use an agentless group for direct connection, the SSH/SFTP buttons are shown on linux devices that have an agent.
But if I disable the option `"ssh": true,` I lose the agentless group functionality for direct access, but even when changing the option to ""ssh": false," the SFTP integration button on agent devices keeps showing up.

![image](https://user-images.githubusercontent.com/18504593/177004947-44cdeac0-6451-4923-9181-4294007b761f.png)

**Comment by silversword411** [comment]
` "scp": { "type": "boolean", "default": true, "description": "Display a SCP link in the device tab when supported." },`
from the json seems relevant

**Comment by si458** [comment]
> ` "scp": { "type": "boolean", "default": true, "description": "Display a SCP link in the device tab when supported." },` from the json seems relevant

i believe this option relates to the SCP link thats next to the SSH, WEB-RDP, WEB-VNC, Interfaces, etc links on the General Tab

**Comment by Ylianst** [comment]
I get it, it's not that useful and confusing to have SSH/SFTP support in devices that are supported by agents.

**Comment by PetieM** [comment]
> I get it, it's not that useful and confusing to have SSH/SFTP support in devices that are supported by agents.

I disagree here, actually. I use SSH on a couple of my agent-installed devices to quickly connect with an alternate user (e.g. the pi user on my Raspberry Pi) since the default terminal always drops you into a root shell.

**Comment by fernandogobah** [comment]
around here we have the habit of always trying to use what is embedded in the agent, and even because it is only through it that the sessions are recorded (our security and auditing habit).  To use a specific user as you mentioned either by doing a "su - user" or by right clicking on the connect button and using the "login shell" option.  We only use the ssh function for devices that do not support agents, such as routers, switches and others.

**Comment by fernandogobah** [comment]
> ` "scp": { "type": "boolean", "default": true, "description": "Display a SCP link in the device tab when supported." },` from the json seems relevant

Not applicable

**Comment by PetieM** [comment]
I’m aware su - user is an option and I’m not against adding a configurable option for removing these buttons on agent-controlled devices but I am against removing them outright as I still think there’s merit in having a quick SSH connection configured with a different user instead of having to connect as root and then change user from there. I don’t see the harm in leaving that as an option since it’s already there, even if it isn’t commonly used.

**Comment by Ylianst** [comment]
Working on this now. I will add an option to remove these buttons for devices with agents, it's just a option. Default will still to have buttons enabled.

**Comment by Ylianst** [comment]
Just added it, will be in MeshCentral v1.0.47. You will need to add this to the domain section of the config.json:

```
      "files": {
        "sftpConnect": false
      },
      "terminal": {
        "sshConnect": false,
      }
```

Once published, let me know if it works.

**Comment by Ylianst** [comment]
Closing since this seems to be done. Open a new issue if needed.
