### ISSUE TITLE
launching meshcentralrouter shows double groups

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4219]
**Describe the bug**
if you launch meshcentralrouter from the webui via the button,
it auto logins in the app correctly but then shows all the groups doubled?

**To Reproduce**
1. launch meshcentralrouter button on web ui
2. opens up meshcentralrouter
3. all groups are doubled?

**Expected behavior**
no double groups?

**Screenshots**
![Screenshot 2022-07-03 190645](https://user-images.githubusercontent.com/765314/177052042-28d9707a-013f-4176-a850-fc78a7b8af9c.png)

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] Docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Hybrid Mode, Traefik Reverse Proxy
 - Version: [e.g. 1.0.43] 1.0.45
 - Node: [e.g. 18.4.0] 18.4.0
 - Browser: [e.g. Google Chrome] Firefox

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] N/A
 - OS: [e.g. Windows 10] N/A
 - Version: [e.g. 21H2] N/A
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] N/A

**Additional context**
if you open meshcentralrouter manually and login, you dont get double groups!
you only get double groups if you launch meshcentralrouter from the web ui via the button

**Your config.json file**
N/A

**Comment by Ylianst** [comment]
Yep! just replicated it! Looking into it now.

![image](https://user-images.githubusercontent.com/1319013/177075197-f595a934-6cbb-4592-ade2-8f25ed8202a0.png)

**Comment by Ylianst** [comment]
Just put in a fix for this. It will be in MeshCentral v1.0.46.

**Comment by si458** [comment]
yep fixed indeed!
however every time i open meshcentralrouter now it seems to show all the group uncollapsed?
and the window screen now seems huge?

**Comment by Ylianst** [comment]
I am going to add an option to default to collapsed or uncollapsed.

**Comment by Ylianst** [comment]
Added new setting, will be in MeshCentral v1.0.49.

![MC2-MeshCentralRouterCollapseGroups](https://user-images.githubusercontent.com/1319013/177845390-a40f50dd-dc37-4bd5-ac65-10cd6a0d827f.png)

**Comment by si458** [comment]
thank you works a treat!
