### ISSUE TITLE
AV Status Missing

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#422]
AV Status was previously working but is now missing.

I'm on 0.3.9.p but I'm not quite sure which version it went missing in.

**Comment by ghplw** [comment]
typing av in the console returns
**Command returned an exception error: Module: win-info (NOT FOUND)**

**Comment by krayon007** [comment]
@Ylianst  I wonder why modules keep disappearing from the server. I wonder if this is related to the self-update... It seems a file was there previously, got nuked, but didn't get updated?

**Comment by Ylianst** [comment]
This is related to #424. Minification of the meshcore modules is broken. Working on it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-q with a fix for this. Check it out and let me know if it works.

**Comment by tranbert** [comment]
Working... And terminal + other OK too.

**Comment by Ylianst** [comment]
Thanks. I will close this one since I am pretty sure it's fixed. Please re-open if needed.
