### ISSUE TITLE
Feature Request: Change name of root CA used for agent signing

### ISSUE THREAD

**Issue by mwllgr** [Ylianst/MeshCentral#4221]
It's basically all in the title. I think it would be a nice pro to be able to change the _MeshCentralRoot_ (as seen in https://github.com/Ylianst/MeshCentral/blob/25c805d7eabb9bbe223f527a46669edeae72b7ff/certoperations.js#L1009) to something user-provided via the config.json.

**Comment by Ylianst** [comment]
Ok, I can do that, but it will require that all certificates be reset.

**Comment by Ylianst** [comment]
Added it, will be in MeshCentral v1.0.47.

**Comment by mwllgr** [comment]
Works as expected. Thanks!
