### ISSUE TITLE
Web-relay does not work on my server

### ISSUE THREAD

**Issue by lergolas** [Ylianst/MeshCentral#4222]
I'm very excited about this new feature but I can't get it to work on my server.
I can't find the configuration problem.

Describe the bug:

Accessing from any browser shows an ssl error: "ERR_SSL_PROTOCOL_ERROR"
The server is behind a reverse proxy configured with nginx forwarding port 443 to 8443.
I use Letsencrypt https certificates.
I have configured the relay port in the config.json file and opened port 453 on the router to the server.

To Reproduce:

I click on the http or https link of the server I want to access through the web (in this case, two Open Media Vault NAS) and the browser shows me the SSL error.

Server Software:

```
OS: Ubuntu 18.04
Network: Hybrid Mode, Nginx Reverse Proxy
Version: 1.0.45
Node: 12.22.1
Browser: Google Chrome
```

Remote Device:

```
Device: NAS OMV
OS: Debian 9
```

Your config.json file:

```
{
  "settings": {
    "Cert": "mcva.duckdns.org",
    "WsCompression": true,
    "AgentWsCompression": true,
    "PublicPushNotifications": true,
    "Minify": true,
    "Compression": true,
    "Port": 8443,
    "RelayPort": 453,
    "AliasPort": 443,
    "WebRTC": true,
    "TlsOffload": "192.168.10.32",
  },
  "domains": {
    "": {
      "Title": "MCVA",
      "Title2": "by lergolas",
      "CertUrl": "https://mcva.duckdns.org:443/",
      "ssh": true,
      "mstsc": true,
      "GeoLocation": true,
    },
  },
}
```

Serverstate.txt file:

```
time=1656932294739
state=running
server-pid=51257
server-parent-pid=115672
redirect-port=80
mps-port=4433
mps-name=mcva.duckdns.org
http-relay-port=453
http-relay-aliasport=443
http-port=8443
http-aliasport=443
```

**Comment by Ylianst** [comment]
For your setup to work, your reverse proxy should be forwarding external port 453 to internal port 453 and performing TLS when doing it. MeshCentral will be listening on port 453 and will NOT be doing TLS.

The error you see is likely that NGINX is trying to perform a HTTPS connection to internal port 453, or the browser is trying to perform HTTPS to 453 and getting a HTTP response. So, this error will be displayed.

I just added `relayAliasPort` support in the next version of MeshCentral in case you want to forward the external port to a different internal port.

**Comment by lergolas** [comment]
I have forwarded the port from the proxy and now it works fine.

I have a problem with one of the servers when accessing: meshcentral crash when I do the relay. I think there is another issue with the same problem, so I'll post it there.

Thank you very much for everything, you do a fantastic job.
