### ISSUE TITLE
sfc/scannow not working on some computers "Windows Resource Protection could not start the repair service."

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4223]
Some of my computers I can use sfc/scannow with the admin terminal, others I have to use the command prompt over remote desktop. It give the error "Windows Resource Protection could not start the repair service.". So I google the error and followed the instructions to fix it with the trusted installer with no luck. Like I said it works if I physically remote desktop to the computer and pull up command prompt. 
3 of my machines run the command successfully and 3 of my computers give the error. 

**To Reproduce**
1. Select Computer
2. Click on Terminal
3. Click connect
4. enter command sfc/scannow

**Expected behavior**
Run sfc scan.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Installed without docker
 - Network: Directly connected with static ip.
 - Version: 1.0.45
 - Node: 12.22.9
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Laptops
 - OS: Windows 11
 - Version: 21H2/22000
 - Current Core Version (if known): Apr 4 2022, 1043365905

The only edit to the config is to change the name.

**Comment by si458** [comment]
If you right click on the connect button in the terminal tab you will get more options like `admin powershell`

Try using one of those and see if you still get the same error

**Comment by si458** [comment]
> Admin Powershell gives the same error. 

What about any of the other options? I think the is 3 of them, sorry im afk at mo

**Comment by The-Real-Admin-Guy** [comment]
SFC sometimes gets intermittent locked down during "Informal unscheduled background updates", one of Windows features that made me loose a rather significant amount of patience responding to clients loss of productivity, some far beyond frustration, including data loss...

Microsoft does that, no warning, nothing just freeze the unit until its done.

Either that or you have malware, causing serious corruption affecting SFC ...
I would physically download https://docs.microsoft.com/en-us/microsoft-365/security/intelligence/safety-scanner-download?view=o365-worldwide scan then do sfc again looking for physical corruption.

I cant see the agent causing SFC to fail...

**Comment by si458** [comment]
glad its working!
sorry i didnt catch the throught sooner, im isolating so brains cabbaged and been sleep most of the week
