### ISSUE TITLE
MC Server in Hybrid Mode Behind Nginx Reverse Proxy & LAN Agents Cannot Connect

### ISSUE THREAD

**Issue by kismetgerald** [Ylianst/MeshCentral#4224]
**Hi Folks,**

Hope you're all doing well.  Happy Independence Day to those of you in the US.  

I'm very new to MeshCentral and I'm in love with it already.  My environment is comprised of a Debian 11 Server running MC v1.0.45 with the latest versions of Node (v12.22.12) and NPM (v7.5.2).  My MC instance sits behind an Nginx Proxy Manager instance and I have configured the config.json file in accordance with the installation manual and my WAN agents are able to successfully connect, as am I able to access the web UI externally.  However, my LAN clients are not able to connect when using an agent.  The only way I've been able to manage any LAN devices is to use the no-agent method, but I don't want to use that as my first choice.

I've tried changing my internal DNS record to point the hostname to the Nginx Proxy in hopes that it will cause the agents on the LAN to hit the proxy and trigger the same behavior as the external agents when they hit the proxy.  Obviously, I'm missing or not understanding something.  So I would appreciate it very much if someone can help me out here.

Below is my current config file and a couple of screenshots of my Nginx Proxy Manager configuration for this host:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "remote.mydomain.net",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TlsOffload": "192.168.2.10"
  },
  "domains": {
    "": {
      "title": "MeshCentral Controller",
      "title2": "WGSDAC-SV-MESH01",
      "minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "certUrl": "https://192.168.2.10:443/"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

![Snap 2022-07-04 at 21 22 45](https://user-images.githubusercontent.com/14914151/177232059-7f31cf31-15be-424d-9107-81f691c12269.png)

![Snap 2022-07-04 at 21 27 18](https://user-images.githubusercontent.com/14914151/177232068-af9fe2ce-c96f-49cd-8a5c-94b4d32d0cad.png)

![Snap 2022-07-04 at 21 28 27](https://user-images.githubusercontent.com/14914151/177232076-80cab468-9d42-4436-9787-3e154ff5143c.png)

**Comment by LPJon** [comment]
Have you added your domain to the Firewall and pointed it to your LAN MeshCentral Server IP? You need your LAN clients to know the LAN IP of your MeshCentral Server....they CAN'T use your Public Internet IP. You will need a firewall that can support this. If you don't have one then you have to choose between WAN or LAN mode. Hybrid mode requires a more complex setup. Open Source firewalls that support this are ones like [PFSense](https://www.pfsense.org/download/) or [OPNsense.](https://opnsense.org/download/) but they have a learning curve to learn how to setup. Some high end retail residential firewalls support this but each one varies. You may  need to lookup the firewall you  have and see if you already have the ability to setup a DNS Override for you local LAN.

**Comment by LPJon** [comment]
In that case, if you are using "Unbound" and have set the "A" record override be sure the override is working by testing a ping to your MeshCentral domain name from one of the machines on your LAN. In the ping output you should see your LAN IP instead of your Internet IP. If you are seeing your internet IP it means one of two things. Either unbound is not working correctly (Unfortunately this happens with OPNsense) or the machine has the public IP stored in its DNS cache (Windows Only, Linux does not do this).

Unbound has issues with sub-domain overrides when a primary domain with the same name is already specified. So be sure to only use the "host overrides" section and remove anything related from the "Domain Overrides" section.

**Comment by kismetgerald** [comment]
@LPJon So, the strangest thing happened.  I went to update the DNS A record to point to the MC server instead of the Nginx Reverse Proxy, and to my astonishment, the host I'd tried to add yesterday was showing online and connected to MC.  So without doing any thing else, I proceed to add a second host, then a third, and so on.  I'm pleased to say that all my WAN and LAN agents are now connecting.

Can't explain what happened other than perhaps a delay of some sort, or perhaps a local DNS cache on the Windows machines (_mind you I didn't try any of the Linux hosts until today, so can't really say if they were having the same problem or not_).  So as it stands now, my issue is resolved - though not entirely sure how.

Thanks to all of you for chiming in to help.  Really appreciate it.

**Comment by LPJon** [comment]
Glad you got this resolved.

**Comment by LPJon** [comment]
As a tip....the time frame suggests that the DNS cache was updated on the Windows Machines. So your setup was correct you just needed to flush the cache on the Windows Computers. For future Reference you can do this with the command
`ipconfig /flushdns` from the command-line of any Windows Machine

**Comment by kismetgerald** [comment]
Yeah, I know. I'd already done that, which is why I was astonished that it started working all of a sudden.  Thanks for the top though.
