### ISSUE TITLE
Windows Background only agent not working

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#423]
Windows Background only agent not working. With the recent agent upgrade(s) the background only agent shows connected status, but desktop, terminal, files and console operations will not connect to the agent.
The interactive agent type is working fine.
Additionally, some of the background only agents "lost connection" in the MeshCentral after a few minutes. I've reinstalled it with new downloaded agent. Does not help.

**Comment by krayon007** [comment]
If you type any commands on the console tab, does the agent respond? It sounds like the control channel is established, but the tunnels are failing. If this is the case, I'll have some things for you to try...

**Comment by hunter-nl** [comment]
Agent does not respond on console commands

**Comment by krayon007** [comment]
If you restart the service from the service manager, does it behave correctly, or is the behavior the same?

**Comment by hunter-nl** [comment]
Same behavior

**Comment by krayon007** [comment]
@Ylianst  any ideas? Sounds like the issue you saw when you changed changed the binary of the buffer, but before you applied the fix. Looks like the control channel is connecting, but the agent is not authenticating. Strangely it's only happening in service mode, not console mode? I'm not able to reproduce this issue. Is alt running the latest npm build, and does that match your test server?

**Comment by krayon007** [comment]
Are all your agents behaving like this or only some of them? What version of Windows is running on the ones that failed? Is it running Windows Server? If it is, it may not have updated correctly from the "bad AV" version.

**Comment by hunter-nl** [comment]
Some of the windows agents. The bad agents running on windows server 2012-2016.
Agents running on windows 10 are functioning.
What do you mean with bad av version? How can I verify this? I’ve uninstalled the agent and downloaded from latest MeshCentral server version and installed version. Still same behavior.

**Comment by krayon007** [comment]
One of the previous updates, had a bug, that caused the agent to deadlock on Windows Server, when it tried to fetch the AV status. That build also happened to have deadlock detection disabled, so it could not recover. If you try to Stop/Start/Restart the service, the service won't respond. Likewise, if you tried to re-install the service, I think under the covers the installation failed, because the file was locked... The only remedy was to reboot the server or manually kill the process... Then when the agent starts up again, it would auto-update correctly.

**Comment by hunter-nl** [comment]
But when I uninstall it and all the files in program files\mesh agent folder are gone and do a new install of the new agent installer then I still get the same behavior.
Reinstall steps: Stopping the service is hanging, just killed it. Service disabled. Reboot. Uninstall. Reboot. Install agent.

**Comment by krayon007** [comment]
Ok, that's different then. When I get back to a computer, I'll look at a windows server setup, and see if I can reproduce it...

**Comment by Ylianst** [comment]
Can you update to 0.3.9-q and try again? that version has a big fix in the agent software. The "background only" agent is really the same except that it show different buttons in the install box.

**Comment by hunter-nl** [comment]
Still the same issue. I've reinstalled the agent with agent install package from 0.3.9-q.
Stopping service is hanging. And when MeshCentral thinks it has a connection. The Desktop, files, terminal and console does still not work.

**Comment by hunter-nl** [comment]
After upgrade to 0.4.0-g, seems to be solved.
