### ISSUE TITLE
Sophos detects as 'Generic ML PUA'

### ISSUE THREAD

**Issue by shadyslim2018** [Ylianst/MeshCentral#4235]
Sophos antivirus detects the agent as 'Generic ML PUA'
```
 PUA cleaned up: 'Generic ML PUA' at 'C:\Program Files\Mesh Agent\MeshAgent.exe''
```

**Comment by si458** [comment]
Sadly this is expected as the software had been miss used by hackers in the past so some av detect it as bad

Only thing you can do to help is buy a code sign certificate and apply it to the agent to help tell the av that it is indeed safe and your agent software (we do this with Norton)

**Comment by PathfinderNetworks** [comment]
You'll also want to submit it as a false detection to Sophos.  I have to regularly do this with Avast.  Also, if you can create an exception/exclusion policy for the agent in your Sophos policies that will (or should) help.
