### ISSUE TITLE
Feature Request: Increase Access Log Retention / auto report generation 

### ISSUE THREAD

**Issue by SchmalzTech** [Ylianst/MeshCentral#4238]
Great work so far! I have been transitioning from an expensive commercial product and running Meshcentral for a while, and I rely on reports for job tracking and verification of my time logging. I went to pull session reports and could only go back 30 days.

It would be great to have this extended so I could generate a report for the last 3 months or more, as I sometimes don't think to pull the report until 30+ days have passed. I was going to dig into this myself to attempt to see how it works, but I haven't had time.

Alternatively (or additionally,) it would be great to be able to ship a weekly or monthly session report automatically via email.

Are the old session logs stored somewhere retrievable, like in a rotated log archive?

**Comment by Ylianst** [comment]
Sorry for the delay. Yes, you can set the retention time in the config.json like this:

```
{
  "settings": {
    "DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    }
  }
}
```

There are 3 types of records.

- "events" are the more common, they cover everything users and devices do.
- "powerevents" are the color bars you see at the bottom of a device's "General" tab.
- "statsevents" are the server usage data you see in the "My Server / Stats" tab.

The retention values are in seconds, and the values I put above are the default ones. Feel free to increase these a lot. It's best to use a good database when running MeshCentral in production (not NeDB), that is more important when you have lots of records in the database.

As you probably already know, there are reports in the "My Events / Reports" tab here:

![image](https://user-images.githubusercontent.com/1319013/179636411-20754777-7445-431e-a18f-b5af9b285d20.png)

Sending an automated report by email is something I can do. Can you open a new issue and provide as much detail as possible as to what exactly you would like. - Thanks.
