### ISSUE TITLE
windows agents terminal broken

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#424]
on 0.3.9-p. Not sure what version I upgraded from but was probably 15 releases behind
agent console is full of these errors

`uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: Module: win-terminal (NOT FOUND) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'unpipe' of undefined in method '()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: Module: win-terminal (NOT FOUND) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'unpipe' of undefined in method '()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: Module: win-terminal (NOT FOUND) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'unpipe' of undefined in method '()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: Module: win-terminal (NOT FOUND) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'write' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'unpipe' of undefined in method '()'`

**Comment by Ylianst** [comment]
Working on it. I found the issue, the minified version of the meshcore.js is broken.

A temporary fix is to rename the "modules_meshcore_min" folder to "xmodules_meshcore_min" and restart the server. That folder is in "node_modules/meshcentral/agents". This will force the server to use the non-minified version and terminal will work.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-q with a fix for this.

**Comment by wh1te909** [comment]
awesome, working! thanks!
