### ISSUE TITLE
Web-Relay - not found

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#4240]
**Describe the bug**
I set up a new webrelay function, but when I try to open it, it gives Not Found

**Screenshots**
![image](https://user-images.githubusercontent.com/51225180/177984174-615d5bf3-1024-45cf-b77e-76f18da2b679.png)

**Server Software (please complete the following information):**
 - OS: Debian 10
 - Virtualization: no, npm install
 - Network: Hybrid, reverse proxy NGINX, tls offload on Nginx
 - Version: 1.0.48
 - Node: v16.14.1
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: VM
 - OS: Debian
 - Version: 10
 - Current Core Version (if known): Apr 4 2022, 2198572183

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "rm.company.ru",
    "relayDNS": "relay.rm.company.ru",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
    "relayPort": 453,
    "relayAliasPort": 443,
    "browserPing": 60,
    "browserPong": 30,
    "AgentPong": 30,
    "manageAllDeviceGroups": [ "user//admin" ],
    "manageCrossDomain": [ "user//admin" ],
    "tlsOffload": "192.168.XXX.XXX",
    "trustedProxy": "192.168.XXX.XXX",
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": true,
    "desktopMultiplex": true,
    "allowHighQualityDesktop": true,
  },
  "domains": {
    "": {
      "_siteStyle":  1,
      "title": "Remote Access System",
      "title2": "B2B Cluster",
      "minify": true,
      "newAccounts": false,
      "hide": 5,
      "agentNoProxy": false,
      "novnc": true,
      "mstsc": true,
      "ssh": true,
      "CertUrl": "https://rm.company.ru:443/",
      "AutoRemoveInactiveDevices": 45,
      "myServer": {
        "Backup": true,
        "Restore": true,
        "Upgrade": true,
        "ErrorLog": true,
        "Console": true,
        "Trace": true
      },
      "unknownUserRootRedirect": "https://rm.company.ru/auth-azure",
      "DeviceSearchBarServerAndClientName": true,
      "authStrategies": {
        "azure": {
          "callbackurl": "https://rm.company.ru/auth-azure-callback",
          "newAccountsRights": [ "nonewgroups", "notools" ],
          "newAccounts": true,
          "clientid": "XXXXXXX",
          "clientsecret": "XXXXXXX",
          "tenantid": "XXXXX"
        },
      },
      "deviceMeshRouterLinks": {
        "rdp": true,
        "ssh": true,
        "scp": true,
        "extralinks": [
          {
            "name": "MCRDesk",
            "protocol": "mcrdesktop"
          },
          {
            "name": "MCRFiles",
            "protocol": "mcrfiles"
          },
          {
            "name": "PVE",
            "protocol": "https",
            "port": 8006,
            "filter": [ "tag:PVE" ]
          },
          {
            "name": "PVEBKP",
            "protocol": "https",
            "port": 8007,
            "filter": [ "tag:PVEBKP" ]
          },
          {
            "name": "Winbox",
            "protocol": "custom",
            "port": 8291,
            "filter": [ "tag:MIKROTIK" ]
          }
        ]
      },
      "userSessionIdleTimeout": 60,
      "terminal": {
        "_linuxshell": "login",
        "launchCommand": {
          "linux": "su -\n",
          "_darwin": "clear\necho \"Hello MacOS\"\n",
          "_freebsd": "clear\necho \"Hello FreeBSD\"\n"
        }
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

NGINX config
```
server {
        listen 443 ssl;
        server_name rm.company.ru relay.rm.company.ru;

        proxy_send_timeout 330s;
        proxy_read_timeout 330s;

        location / {
                proxy_pass http://10.10.1.208:443/;
                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-NginX-Proxy true;
       }

    ssl_certificate /etc/letsencrypt/live/rm.company.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rm.company.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

**Comment by si458** [comment]
we are already aware of this
https://github.com/Ylianst/MeshCentral/issues/4210#issuecomment-1177375607
basically the cookie wasnt being shared between the subdomains,
so have pushed a PR which was merged, just waiting for a new build to be released!
for an imediate fix, clone the git repo and run from there or build from latest git commit which included the cookie fix

**Comment by Ylianst** [comment]
MeshCentral v1.0.49 was just published. Can you update and try again?

**Comment by mwllgr** [comment]
It's working for me now! Had the same error with an nginx reverse proxy.

**Comment by Ylianst** [comment]
Nice! Big thank you to @si458 for that fix.

**Comment by si458** [comment]
fully works for 1.0.49 this issue can be closed now

**Comment by PathfinderNetworks** [comment]
I just updated to 1.0.49 and am still getting this 'Not found' error.  I am not using a reverse proxy.  I do have it configured to use the relayDNS option and have the host name configured at my name server and pointing correctly.  Although I do notice that the LetsEncrypt certificate for my primary MeshCentral server page is being applied to the host name I have set up for the relayDNS. This means the site is showing as using an invalid certificate.  I have no idea if that's what is still causing the 'Not found' error though.

**Comment by si458** [comment]
> I just updated to 1.0.49 and am still getting this 'Not found' error. I am not using a reverse proxy. I do have it configured to use the relayDNS option and have the host name configured at my name server and pointing correctly. Although I do notice that the LetsEncrypt certificate for my primary MeshCentral server page is being applied to the host name I have set up for the relayDNS. This means the site is showing as using an invalid certificate. I have no idea if that's what is still causing the 'Not found' error though.

try the following:

log out of meshcentral, then clear your cookies! (or try private browsing)
its an issue i found, because of the change from main domain to subdomain cookies, both types where existing on the client which was confusing the server

i also believe it sounds like your SSL is invalid or wrong? both your domain and relaydomain should be different!
also your relaydomain should be a subdomain of your main domain (e.g. relay.mc.mydomain.com and mc.mydomain.com)

**Comment by PathfinderNetworks** [comment]
I will try from a different device that has never logged in to my MeshCentral server in a bit (just to fully troubleshoot the cookie possibility).  
For my domains, my primary MeshCentral domain is mesh.exampledomain.com.  The relay is relay.exampledomain.com.

**Comment by si458** [comment]
>For my domains, my primary MeshCentral domain is mesh.exampledomain.com. The relay is relay.exampledomain.com.
THAT WONT WORK!
it must be subdomain of your primary meshcentral domain! (e.g. mesh.exampledomain.com and relay.mesh.exampledomain.com)

**Comment by Ylianst** [comment]
I am getting "not found" errors, myself... looking into it now. It likely has to do with browser security settings since I don't see the session cookie pass over from the main site to the relay site correctly.

**Comment by Ylianst** [comment]
Ok, I am going to have to do so rework on this.

**Comment by Ylianst** [comment]
Placing a "domain" in the sessionOptions is going to cause a bunch of issues for people running MeshCentral servers with multiple domains and multiple DNS names. So, I can't really use that as a solution. I am going to work on an alternative. I need to call into the relay server with an encrypted cookie in the URL and get started that way. So, will be working on that.

I also noticed that I would something get the main session cookie on the relay server, but when I try to set the cookie, I get two cookies with the same "xid" name instead of changing the original one which messes up everything. So, I got rid is the "session.rid" and using "session.x" instead. Anyway... I got a few more hours on this and it should work on all situations.

**Comment by si458** [comment]
@Ylianst my PR previously fixed the issue of the relaying between the relaydomain and the main domain,
it set the cookie as a subdomain cookie so the relay feature worked
it just sadly didnt work for people like @PathfinderNetworks who uses different domains rather than subdomains,
also latest commit https://github.com/Ylianst/MeshCentral/commit/9dac8b780793781c4d0d421a2c89fee6899e9fc1 seems to revert the cookie back to a standard domain cookie rather than a subdomain one?
is the more improvements to come?

**Comment by Ylianst** [comment]
Your exactly right on the problem and I just fixed it in MeshCentral v1.0.50. I am back to not having a domain for cookies and use other tricks to generate cookies in a different DNS domain if needed.

**Comment by PathfinderNetworks** [comment]
I just updated to 1.0.50 and it's working correctly now. Thank you!  This is a pretty impressive new feature!
But, one question, I did ask this in the discussion area but not sure if it was noticed.  How do we add a device (such as a router or printer) that doesn't utilize an agent?  I've created a device group with the 'No agent devices relayed thru agent' option and chose a device on that particular network I want to relay through. That part is no problem. However, when I go to add a device to that group, I don't seem to have the correct options to add a local device?  Here is what I am seeing:
![device](https://user-images.githubusercontent.com/48607498/178127447-628ebc0d-7116-4458-8447-a4d618e3f7ea.jpg)
Shouldn't there be other options under Type?

**Comment by PathfinderNetworks** [comment]
Also, along with adding a non-agent device that we want to access through this relay service- it would be superb if we could just add those types of devices to an existing device group (meaning that we don't have to create a separate 'local device group' just for those devices.  My reasoning is that I already have a large number of device groups.  I use the device groups to track my customers.  Meaning I have a device group for each customer and all of their devices are placed within that device group specific to that customer.  I'd prefer to have all of their devices in that existing group- just to make my MeshCentral interface cleaner and easier for me to find that customers device.  Hopefully that makes sense.  That request is definitely not urgent by any means.

**Comment by Ylianst** [comment]
For the first one on "Add local device" and the type... the "Type" will just indicate to MeshCentral was services to offer on the web page. If you select "Windows (RDP)" you will see the desktop tab with the RDP option show up for that device. If you select the other option, it will offer SSH on the terminal tab, and SCP on the File tab. That is all. Regardless of what you select, the "HTTP" and "HTTPS" links will be on the device page. I could improve this in the future where you would select exactly was services you want offered for a given device.

**Comment by timgjr** [comment]
Ylainst, a thought maybe for the second point. Don't change device groups, just add different device sorting options/views and allow us to set our preferred default viewing type. Example is by customer, location, and/or device type (swtich, IoT, Server, terminal, etc). Just leave device group alone. Really I think all we need is a few more options when it comes to sorting our device lists.

**Comment by Serenfo** [comment]
> I'm having the same `Not found` error in using a very similar nginx/mesh config on centos 7 with meshcentral 1.0.51. Tried clearing cookies and a completely different browser.
> 
> I've set the relayDNS url to relay.mesh.example.com , my main mesh url is mesh.example.com. Also have extended my letsencrypt cert with the domain relay.mesh.example.com.
> 
> Any tips on how to debug this further ?

Me too with this error on meshcentral trace

{"library":"SSL routines","function":"ssl3_get_record","reason":"wrong version number","code":"ERR_SSL_WRONG_VERSION_NUMBER"}

**Comment by Ylianst** [comment]
For the web relay "not found" issues. If they are still happening, can you open a new issue and indicate if you are using DNS web relay or port web relay and give me sufficient details to replicate the issue? - Thanks.

For the device group stuff, this needs to be a new topic. One option you have now is that you can set one or more tags for each device like this:

![image](https://user-images.githubusercontent.com/1319013/179635331-ec868358-ae51-4374-bfca-7d75f0fc31bd.png)

You can then group by device tags:

![image](https://user-images.githubusercontent.com/1319013/179635368-aed96735-8e45-426a-89e4-aef9a7ffe56e.png)

I am going to close this one, please open new issues as needed.
