### ISSUE TITLE
Upgrade to 1.0.49 Unable to connect web socket, click to reconnect.

### ISSUE THREAD

**Issue by ClickLeft** [Ylianst/MeshCentral#4242]
I just upgraded from 1.0.48 to 1.0.49. No other changes made. Now I'm getting this error after logging on: "Unable to connect web socket, click to reconnect."

**To Reproduce**
1. Lot into MechCentral
2. Error "Unable to connect web socket, click to reconnect." appears
3. If you click to reconnect, it takes you back to the login screen.

![ce1bd645-1946-4caf-8484-6062c88ce033 1](https://user-images.githubusercontent.com/68623760/178116079-23aba4f4-9d32-4fef-811f-a34b0fe088ba.jpeg)

**Expected behavior**
You would normally see the list of systems after logging in.

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Virtualization: N/A
 - Version: 1.0.49
 - Node: 16.16.0
 - Browser: Google Chrome 103.0.5060.114 64-bit

**Remote Device (please complete the following information):**
 - Device: Laptop / Desktop
 - LAN/WAN
 - OS: Windows 10
 - Version: 21H2

Config.json

```
{
  "settings": {
    "cert": "mesh.XXXXX.com",
    "_minify": true,
	"AllowHighQualityDesktop": true
  },
"letsencrypt": {
 "email": "XXX@XXXX.com",
 "names": "mesh.XXXX.com,
 "rsaKeySize": 3072,
 "production": true,
 "desktopMultiplex": true
}
}
```

**Comment by Fefo60** [comment]
Try clearing cookies
It worked for me

**Comment by si458** [comment]
@ClickLeft yes you need to clear your cookies sorry!

Because we changed from single domain cookies to subdomain cookies

And sadly the old single domain cookie is still left behind and the server gets confused because the client sends two cookies instead of one!?

**Comment by I2700I** [comment]
Interestingly enough, the issue does not reproduce in FF and Safari, is it a chromium-only case? Chrome and Edge fail the same way.

**Comment by si458** [comment]
Very weird? Happened to me with firefox, but it's simple to fix thankfully!

**Comment by uzmanager2** [comment]
Hello .

I confirm the bug. The problem appears on Chrome and Firefox when trying to access by IP address, not by hostname.

**Comment by si458** [comment]
> Hello .
> 
> I confirm the bug. The problem appears on Chrome and Firefox when trying to access by IP address, not by hostname.

Just simply clear your cookies and away it goes, it's not a bug!

**Comment by uzmanager2** [comment]
I tried logging in with clear cookies but that didn't solve the problem. When accessing through the hostname - the problem does not appear.

**Comment by si458** [comment]
@uzmanager2 oh yeh crap, accessing via an ip address isn't going to work because of the subdomain cookie!

So sorry about this! I never through about ip access!?
 
I'll see if I can do a PR to fix this if it's ip based for the moment 

As i believe @Ylianst is working on rewriting the web relay for cookies!

But for now it is required to access via a domain name!

**Comment by Ylianst** [comment]
I removed the domain for the cookie as that is not going to work well for many people. I am almost done on the improved version with the fix.

**Comment by Ylianst** [comment]
Just put in the fix, working on releasing now.

**Comment by Ylianst** [comment]
MeshCentral v1.0.50 is published. Cookies and web relay should both work.

**Comment by openncomp** [comment]
Now it works! Thank you very much!

**Comment by uzmanager2** [comment]
It works! Thank you very much!

**Comment by ClickLeft** [comment]
> MeshCentral v1.0.50 is published. Cookies and web relay should both work.

Wow, that was quick! I Installed the update, but now the "MeshCentral" service doesn't start at all.

**Comment by Ylianst** [comment]
@ClickLeft Can you provide any hints as to what is going on? Your OS, NodeJS version, any errors in "meshcentral-data/mesherrors.txt"? Can you start MeshCentral manually and see if anything shows up? - Thanks.

**Comment by ClickLeft** [comment]
> @ClickLeft Can you provide any hints as to what is going on? Your OS, NodeJS version, any errors in "meshcentral-data/mesherrors.txt"? Can you start MeshCentral manually and see if anything shows up? - Thanks.

AH, If I run it manually via **node meshcentral** it works! It's like the service needs to be reinstalled. I tried reinstalling everything, but it didn't work.

**Comment by Ylianst** [comment]
If you run `node node_modules/meshcentral --help` you should see this:

```
MeshCentral v1.0.50, remote computer management web portal.
This software is open source under Apache 2.0 license.
Details at: https://www.meshcentral.com

Run as a background service
   --install/uninstall               Install MeshCentral as a background service.
   --start/stop/restart              Control MeshCentral background service.

Run standalone, console application
   --user [username]                 Always login as [username] if account exists.
   --port [number]                   Web server port number.
   --redirport [number]              Creates an additional HTTP server to redirect users to the HTTPS server.
   --exactports                      Server must run with correct ports or exit.
   --noagentupdate                   Server will not update mesh agent native binaries.
   --nedbtodb                        Transfer all NeDB records into current database.
   --listuserids                     Show a list of a user identifiers in the database.
   --cert [name], (country), (org)   Create a web server certificate with [name] server name.
                                     country and organization can optionally be set.

Server recovery commands, use only when MeshCentral is offline.
   --createaccount [userid]          Create a new user account.
   --resetaccount [userid]           Unlock an account, disable 2FA and set a new account password.
   --adminaccount [userid]           Promote account to site administrator.
```

You can try:

```
node node_modules/meshcentral --uninstall
node node_modules/meshcentral --install
```

**Comment by ClickLeft** [comment]
@Ylianst Thank you, you're amazing! That worked and both issues are resolved.

**Comment by tavoweb** [comment]
tactical@debian:~$ node node_modules/meshcentral --help
node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module '/home/tactical/node_modules/meshcentral'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.19.1
