### ISSUE TITLE
The ability to edit files in the "My files" section

### ISSUE THREAD

**Issue by openncomp** [Ylianst/MeshCentral#4243]
Greetings, I know that you are busy with more important tasks right now, so I'll just leave it here, maybe you will have the opportunity to implement it in the future.
---
**Is your feature request related to a problem? Please describe.**
The file editing button is missing in the local storage "My files", as when connecting to the files of a remote client.

**Describe the solution you'd like**
Add the ability to edit files in the local storage "My files" as when connecting to the files of a remote client.

**Describe alternatives you've considered**
The ability to edit files on a remote client.

**Additional context**
Screenshot of the local file storage, where there is no edit button for the selected file:
![изображение](https://user-images.githubusercontent.com/92163803/178268264-0ed8f1f6-ef64-411b-88e1-2327f2ff474e.png)

A screenshot of the connection to a remote device, where there is a button for editing the selected file:
![Screenshot_20220711_155425](https://user-images.githubusercontent.com/92163803/178269116-2004bb33-c2cf-4b1d-a335-4ba9324bc3ee.png)

**Comment by Ylianst** [comment]
Just added this, will be in MeshCentral v1.0.53 once it's published.

![MC2-MyFilesEdit](https://user-images.githubusercontent.com/1319013/178891377-0dce959d-e2ac-4749-a0aa-8d888d3f6e5b.png)

**Comment by openncomp** [comment]
Thank you very much! It's much more convenient this way!

**Comment by Ylianst** [comment]
Nice! Thanks for confirming & closing.
