### ISSUE TITLE
https://nodejs.org/en/blog/vulnerability/july-2022-security-releases/

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#4245]
Is node.js already up2date on MeshCentral or is there something we need to do?

**Comment by Ylianst** [comment]
MeshCentral does not update NodeJS for you, you need to do this yourself. You can see what version of NodeJS you are running now by typing:

```
  node -v
```

You can also see this by things `info` in the MeshCentral server console like this:

![image](https://user-images.githubusercontent.com/1319013/178330653-8b31f0a9-c456-40b3-ad5b-11d95881fd8c.png)

Hope that helps.
