### ISSUE TITLE
Desktop: Black screen trying to connect

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#425]
Hi,
I was wondering if someone could assist me currently installed meshcentral2 on ubuntu 18.04, and connected on client terminal, it appears on the webGUI when I try to connect to desktop, terminal, or files shows black screen to connect. See pictures. Any ideas to trouble shoot this?
Thank you

![Screenshot from 2019-08-06 13-09-29](https://user-images.githubusercontent.com/13953629/62828081-210bde00-bba3-11e9-9975-8761af4cbcdd.png)

**Comment by Ylianst** [comment]
Duplicate of #424. I am working on fixing this. Look at #424 for a workaround.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-q with fixed to the MeshAgent. Can you try again and see if it does the same? Thanks.

**Comment by killmasta93** [comment]
Thank you so much i updated reinstalled the agent and started to work thank you again
