### ISSUE TITLE
recording - webm convert button missing

### ISSUE THREAD

**Issue by bbrendon** [Ylianst/MeshCentral#4255]
**Describe the bug**
When I open player.htm and open a recording file for playback, the convert to webm button is not there. I'm using all US computers.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/6364477/178567719-0f564185-dc78-48a1-8408-bc08df2062d4.png">

 **Expected behavior**
the "convert to webm" button to be there on the top right.
 
**Server Software (please complete the following information):**
 - OS: debian
 - Virtualization: no docker.
 - Network: connected to internet via NAT.
 - Version: 1.0.43
 - Node: unsure.
 - Browser:  tried edge and safari.

**Comment by Ylianst** [comment]
The convert button is only available in the Chrome Browser since that is the only browser that offers the WEBM encoder. Not sure there is anything I can do to make this work on other browsers.

**Comment by bbrendon** [comment]
@Ylianst  edge is chromium, correct? does that qualify?

**Comment by Ylianst** [comment]
I just took a look at this again, I make use of `webm-writer.js` located [here](https://github.com/thenickdude/webm-writer-js). From their site:

```
Compatibility

Because this code relies on browser support for encoding a Canvas as a WebP image (using toDataURL()), it is presently only supported in Google Chrome, or a similar environment like Electron. It will throw an exception on other browsers or on vanilla Node.
```

So, I guess it's only Google Chrome for now.

**Comment by bbrendon** [comment]
Strange. Thanks for the excellent clarificatioN!
