### ISSUE TITLE
Mesh Agent Memory Leak

### ISSUE THREAD

**Issue by punacoder** [Ylianst/MeshCentral#4258]
I am currently using the latest build of Mesh Central, and am still seeing memory leaks on the Mesh agent on my Windows Servers.  Is there a fix for this?  I see mentions of turning off the Plugin's option (which I do not have turned on).

**Comment by Ylianst** [comment]
Can you provide some numbers on the leak? Indeed, there was a specific plug-in that would store lots of data in the MeshAgent database and cause issues. However, except for that plug-in, the agent should not leak.

**Comment by punacoder** [comment]
Starts at 27Mb  and now it is 300Mb

**Comment by punacoder** [comment]
Btw..why r there 2 instances in memory for the Meshagent?

**Comment by si458** [comment]
Can you please provide a bit more about your setup? _Follow the new bug report template_

Server os, meshcentral version, wan mode proxy etc

**Comment by Ylianst** [comment]
There should be one instance running, but when you open a agent KVM session, a second instance will show up. The first instance is managed by the Windows service manager. The second instance will run under the logged in user account. If you don't have a KVM session running, there are rare cases where a second agent could be running, but this is not typical.

**Comment by punacoder** [comment]
Did the latest fix for Windows Handle memory leak fix this issue?  If so, what release was this applied to?

**Comment by punacoder** [comment]
Host server: Ubuntu 20.0.4
Docker image: Meshcentral release: 1.0.60

Issue: Multiple Windows based hosts (Windows Server 2016, Windows 10 Pro, Windows Server 2008) with Meshcentral agent installed will show Meshagent showing > 1GB (worst case > 5GB) of allocated memory.  After ending the task with task manager the agent will creep up to that level after about 2 weeks.

**Comment by krayon007** [comment]
Ylian hasn't posted the agent update yet. Soon tho.

**Comment by punacoder** [comment]
Thank you...just did a reset on all clients...was at 29MB initially...2 hours later already at 70MB.

**Comment by punacoder** [comment]
krayon007,
Any update on the new agent to fix this issue?

**Comment by punacoder** [comment]
![image](https://user-images.githubusercontent.com/109180582/184745437-f0b93070-ccea-4b49-91f0-feef5a78a8bc.png)
Here is the latest task manager info on the agent after about a week.

**Comment by krayon007** [comment]
Yes, I fixed a whole bunch of leaks. I'm tracking one right now that isnt a leak per se, as the GC collects it, but only during a mark and sweep, which occurs infrequently. I'm working on a fix for it now. This is the last gating issue for release.

**Comment by punacoder** [comment]
Thank you.  I am surprised there are not more users complaining about the issue.  It's crashed a couple of my windows application servers, due to memory low conditions.

**Comment by punacoder** [comment]
Any update?

**Comment by si458** [comment]
> Any update?

the has been a new update 1.0.75 which including a new agent and possibly the memory leak fix
give it a try `agentupdate` from the device console tab

**Comment by ouddorp** [comment]
Installed a meshcentral server on Amazon AWS, Debian 11, MC version 1.0.93(started with 1.0.85) in Pm2,  behind an AWS application load balancer. Works fine, but the client is leaking memory on Windows server 2019 and windows 10 pro (version19043). On windows 2019 memory usage is growing pretty fast, about 300-500Mb a day. on windows 10 less. only 20-30Mb a day. The AWS application load balancer has an idle timeout of 60 seconds. changed agentpong and browserpong in config.json into 50 seconds and changed plugins enabled into false.  Any suggestions what i can try?

**Comment by markhuynh** [comment]
I'm seeing the same memory leak issue on windows server 2019. I upgraded to windows server 2022 and still the same issue. After the upgrade, I removed the agent and added again, but the memory leak is still there. I have to kill the agent every two weeks or so to reduce memory footprint.

**Comment by r4lix** [comment]
> @markhuynh i do it with a small powershell script which is running daily on the scheduler. Restart the agent when it's using more than 100Mb ram. $mesha = Get-Process "MeshAgent" $mem=$mesha.PrivateMemorySize/1024/1024 write-host $mem if ($mem -gt 100) { write-host "Restart MeshAgent, Memory usage > 100Mb" restart-service -name "Mesh Agent" -force } else { write-host "MeshAgent memory usage is fine." }

i need to do same thing for my linux servers

**Comment by ouddorp** [comment]
It looks like it's working fine now. The agentPong value is really important. I had it twice in my config.json file somehow. the first one with 300 seconds and the second with 50 seconds. So the first one of 300 seconds was actually active and since the AWS load balancer has a timeout of 60 seconds it results in memory issues of the agent. i think it's smart to have an agent restart script on the scheduler as a precaution anyway.

**Comment by ouddorp** [comment]
Updated example of a Powershell script for restarting the mesh agent service. When there are active desktop connections there there are more than one mesh agent process running. the example is with write-hosts on the console, but in production i write it with a function to a log file
$MeshService = "Mesh Agent"
$MeshProcess = "MeshAgent"
$MeshServiceStatus = Get-Service -Name $MeshService -ErrorAction SilentlyContinue  
if ($MeshServiceStatus){
    write-host "Mesh Agent service exists"
    if ($MeshServiceStatus.Status -eq "running"){
        $MeshProcessStatus = Get-Process $MeshProcess 
        foreach ($process in $MeshProcessStatus) {
            $mem=$process.PrivateMemorySize/1024/1024
            write-host $mem
            if ($mem -gt 50) {
                write-host "Restart MeshAgent, Memory usage > 50Mb"
                try{
                    Restart-Service -Name $MeshService -ErrorAction 'Stop'
                }
                catch {
                    write-host "failed to restart service Mesh Agent" 
                }
            }
            else {
                write-host "MeshAgent memory usage is fine."
            }
        }
    }
    else{
        write-host "Mesh Agent is not running"
    }
}
else{
    write-host "Mesh Agent doesn't exists"
}

**Comment by Vista2003** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/55105920/90a52194-5e09-47b0-a4fc-2187d312136d)
From one of my Windows Server 2019 DC, seems to top out at just under 2GB

**Comment by ouddorp** [comment]
On my hosts (200+) the problem is almost gone with setting the agent pong value in the json file to a value lower than the timeout of the webserver / load balancer. I only see the problem on servers  where internet is down, but with a script like the above mentioned script the problem is under control.

**Comment by silversword411** [comment]
I wonder if it's a leak in the retry/connection timeout and re-establish of the session.

**Comment by ouddorp** [comment]
> I wonder if it's a leak in the retry/connection timeout and re-establish of the session.
yes i think there is a leak in the retry mechanism.  I recommend a daily script.  MC is besides the memory leak perfect. Currently we have 454 agents running. we have around 5 agents a day with memory usage greater than 50Mb. We know that because I've changed above mentioned script with an email log function.

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back

**Comment by r4yzs** [comment]
Hello, I have the same problem with all my agent (windows and debian).

```● meshagent.service - meshagent background service
     Loaded: loaded (/lib/systemd/system/meshagent.service; bad; preset: enabled)
     Active: active (running) since Wed 2024-02-14 23:11:12 CET; 3 days ago
   Main PID: 392 (meshagent)
      Tasks: 1 (limit: 76903)
     Memory: 840.6M
        CPU: 18min 43.536s
     CGroup: /system.slice/meshagent.service
             └─392 /usr/local/mesh_services/meshagent/meshagent --installedByUser=0

févr. 14 23:11:12 WEB systemd[1]: Started meshagent.service - meshagent background service.
```
and after a reboot (it's a LXC) : 

```● meshagent.service - meshagent background service
     Loaded: loaded (/lib/systemd/system/meshagent.service; bad; preset: enabled)
     Active: active (running) since Sun 2024-02-18 10:44:08 CET; 17s ago
   Main PID: 278554 (meshagent)
      Tasks: 1 (limit: 76903)
     Memory: 6.5M
        CPU: 510ms
     CGroup: /system.slice/meshagent.service
             └─278554 /usr/local/mesh_services/meshagent/meshagent --installedByUser=0

févr. 18 10:44:08 WEB systemd[1]: Stopped meshagent.service - meshagent background service.
févr. 18 10:44:08 WEB systemd[1]: meshagent.service: Consumed 18min 46.184s CPU time.
févr. 18 10:44:08 WEB systemd[1]: Started meshagent.service - meshagent background service.
root@WEB:~#
```

**Comment by rawGH** [comment]
Latest version (1.1.38)
Windows Agent Background Service using 300MB of RAM after 48 hours of running. Is restart script the only solution?

**Comment by rawGH** [comment]
> [@rawGH](https://github.com/rawGH) have u tried the new meshagents and see if you still have the same problem?

I'm not sure if I follow. Which new meshagents? I tried the ones that come with the latest version of MeshCentral, afaik the binaries are from dec 2022.

Reading through the thread I adjusted the Pong to 30s and am running the service restart script daily in scheduler. Should work, but hoping there are new memory-leak-free MeshAgents I missed. :)

**Comment by si458** [comment]
@rawGH new test agents are included in latest releases and available for people to test #6162 
steps below to test

1. backup the `*.exe` from inside `node_modules/meshcentral/agents/` (or rename to something else)
2. move the new test agents from `node_modules/meshcentral/test_agents/` to `node_modules/meshcentral/agents/`
3. stop meshcentral
4. **IMPORTANT: DISABLE AUTO AGENT UPDATE OTHERWISE ALL AGENTS WILL GET AUTO UPDATED!!!**
set `"noAgentUpdate": 1` inside of `settings` in your `config.json`
5. start meshcentral
6. **IMPORTANT: LET MESHCENTRAL RESIGN/RECUSTOMISE THE SINGLE FILE!**
7. **skip this step if you dont code-sign yourself** 
copy the new signed agent from inside `signed-agents` located inside of `meshcentral-data` to your machine,
code-sign the exe however you want/do it,
put the new code-signed exe back into `agents` replacing the old `*.exe`
(backing up the old code-signed version of yours first),
restart meshcentral
8. pick a device and go into its `Console` tab and run `agentupdate`
9. you should see the device go offline and then back online, and in theory the date/version will of changed!
you can verify this in the Console tab, it showing the version number (top right) or typing `info`

you can also them download the new meshagent from the 'addagent' tab after you do the steps above 
and it should work on 24h2 machines for install/run now as the agents dont require wmic anymore

**Comment by ouddorp** [comment]
We only experience high memory usage issues with clients who have a poor internet connection. We have approximately 640 MC client installations on Windows PCs and Raspberry Pi devices. We already had a daily script that performs checks on those Windows PCs. I added a section to the script that restarts the agent if memory usage exceeds 50 MB. When a client is restarted, a log email is sent. We receive about 3 to 15 emails per day, most of which come from the same group of PCs. The latest version is only installed on a few PCs, so I’m not sure if it resolves the problem yet.

**Comment by rawGH** [comment]
@si458 A few small hickups but managed to follow instructions. 

versions
{
  "openssl": "1.1.1s",
  "duktape": "v2.6.0",
  "commitDate": "2024-11-06T15:59:56.000Z",
  "commitHash": "39a927f25ed232ddd826ff6ea716e674a2f9aef7",
  "compileTime": "19:09:13, Nov 25 2024"
}

Hopefully memory leak problems solved, thank you for your time.

@ouddorp With the new agents? On the original (old) ones I had a couple of machines on the same LAN as MeshCentral with substantial memory leaks (150mb/day -ish).

**Comment by si458** [comment]
@rawGH what hiccups did u have?
Was it my instructions? 😱

**Comment by si458** [comment]
@ouddorp that's an interesting finding you have!
Can u share ur script at all?
I've still yet to replicate a machine that has high memory usage
What OS do most of the machines that restart the service run? Also their OS version?

**Comment by rawGH** [comment]
@si458 No man, you're fine. I skimmed the instructions, had to do some (fake) magic in docker, also moved all *.exe files instead of copy. All my faults.

**Comment by ouddorp** [comment]
Most of them are windows 11 23H2 and 24H2 and a few windows 10 IOT. I'll share my scripts tomorrow.

**Comment by ouddorp** [comment]
I'm using a powershell script to check for high memory usages of a process. Functions in a separate file, it's a bit specific for our setup, so the email part is pretty useless :
`function restarthighmemservice {
	<#
	.SYNOPSIS
		Monitors memory usage of a service and restarts it if the memory usage exceeds a specified limit.

	.DESCRIPTION
		The `restarthighmemservice` function checks the memory usage of a specific service and, if the memory usage exceeds the specified threshold, it restarts the service.
		If configured, it also sends an alert email upon restart. The function logs all important steps and outcomes.

	.PARAMETER ServiceName
		The name of the service to be monitored and restarted if needed.

	.PARAMETER ServiceProcess
		The process name associated with the service being monitored.

	.PARAMETER MaxMemUsage
		The maximum memory usage threshold (in MB) that triggers a service restart.

	.PARAMETER mail
		Optional. Indicates if an alert email should be sent when the service is restarted. Default is `$true`.

	.EXAMPLE
		restarthighmemservice -ServiceName "MyService" -ServiceProcess "MyProcess" -MaxMemUsage 500 -mail $true
		
		This example monitors "MyService" and restarts it if the memory usage of "MyProcess" exceeds 500 MB. An alert email is sent upon restart.
	#>
	param(
		[string]$ServiceName, 
		[string]$ServiceProcess, 
		[int]$MaxMemUsage, 
		[bool]$mail = $true
	)
	$ServiceStatus = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue  
	if ($ServiceStatus){
    	log -string "$ServiceName service exists" -file $logPath
    	if ($ServiceStatus.Status -eq "running"){
        	$ProcessStatus = Get-Process $ServiceProcess 
        	foreach ($process in $ProcessStatus) {
            	$mem=$process.ws/1024/1024
            	log -string $mem -file $logPath
            	if ($mem -gt $MaxMemUsage) {
                	log -string "Restart $ServiceProcess, Memory usage > $MaxMemUsage" -file $logPath
                	try{
                    	Restart-Service -Name $ServiceName -ErrorAction 'Stop'
						if ($mail){
							EmailAlert -alertaddress $alertemail -subjecttext "$ServiceName restarted" -alerttext "$ServiceName Restarted because of high memory usage: $mem Mb"
						}
						Start-Sleep -Seconds 5 #because of too fast multiple times restarting in case of testing with an active desktop session
            		}
                	catch {
                    	log -string "failed to restart service $ServiceName" -file $logPath 
                	}
            	}
            	else {
                	log -string "$ServiceName memory usage is fine." -file $logPath
            	}
        	}
    	}
    	else{
        	log -string "$ServiceName is not running" -file $logPath
    	}
	}
	else{
    	log -string "$ServiceName doesn't exists" -file $logPath
	}
}

function log {
	<#
	.SYNOPSIS
		Logs a given message to a specified file.

	.DESCRIPTION
		The `log` function writes a given string message to a specified log file.
		It attempts to create or open the file before appending the message.

	.PARAMETER string
		The message that will be logged.

	.PARAMETER file
		The path to the log file where the message should be recorded.

	.EXAMPLE
		log -string "This is a test message." -file "C:\Logs\mylog.txt"
		
		This example logs the message "This is a test message." to the file at "C:\Logs\mylog.txt".

	.NOTES
		Errors are silently caught in the catch block, meaning no errors will be displayed in case of failure.
	#>
	param( 
		$string, 
		$file
	)  
	Try {
		[IO.File]::OpenWrite($file).close()
		Add-Content -Path $file -Value $string
		$string
	}
	Catch {}
}

function EmailAlert
{
	<#
	.SYNOPSIS
		Sends an alert email to the specified address.

	.DESCRIPTION
		The `EmailAlert` function sends an alert email using a predefined URL structure to either the local or a remote mail server.
		The subject and message content are URL-encoded to ensure proper formatting.

	.PARAMETER alertaddress
		The email address to which the alert will be sent.

	.PARAMETER subjecttext
		The subject of the email to be sent.

	.PARAMETER alerttext
		The body text of the email.

	.EXAMPLE
		EmailAlert -alertaddress "test@test.nl" -subjecttext "This is a test" -alerttext "Test email body"
		
		This example sends an email with the specified subject and body to "test@test.nl".
	#>
	# Usage EmailAlert -alertaddress "test@test.nl" (or variable $alertemail) -subjecttext "Dit is een test" -alerttext "test body"
	param(
		$alertaddress, 
		$subjecttext, 
		$alerttext
	)
	$hostname = hostname

	# URL encode the subject and alert text to ensure they are properly formatted for the web request
	$SubjectTextToEncode = [System.Web.HttpUtility]::UrlEncode($subjecttext)
	$AlertTextToEncode = [System.Web.HttpUtility]::UrlEncode($alerttext)

	 # Construct the mail server URLs with the encoded subject and alert text
	$mailurlsrv = "http://127.0.0.1/save?type=mail&userid=&subject=$hostname+$SubjectTextToEncode&message=$AlertTextToEncode&toaddress=email_$alertaddress"
	$mailurlother = "http://192.168.14.1/save?type=mail&userid=&subject=$hostname+$SubjectTextToEncode&message=$AlertTextToEncode&toaddress=email_$alertaddress"
	Try {
		# Decide which mail server to use based on the hostname
        # If the hostname contains "SRV", use the local mail server URL
		if ("$hostname" -Match "SRV"){
			$Response = Invoke-WebRequest -URI $mailurlsrv -UseBasicParsing
		}
		# Otherwise, use the remote mail server URL
		else {
			$Response = Invoke-WebRequest -URI $mailurlother -UseBasicParsing
		}
		# Check the response status code to confirm if the request was successful
		$StatusCode = $Response.StatusCode
        if ($StatusCode -eq 200) {
            log -string "Sent AlertMail with subject $subjecttext" -file $logPath
        }
	}
	Catch {
		log -string "Failed to send alert email" -file $logPath
	}	
}
`

The actual code in the main powershell script is only one line:
`# Restart Mesh Agent because of a memory leak
restarthighmemservice -Servicename "Mesh Agent" -ServiceProcess "MeshAgent" -MaxMemusage 50
`

**Comment by ouddorp** [comment]
> Most of them are windows 11 23H2 and 24H2 and a few windows 10 IOT. I'll share my scripts tomorrow.

We updated all 618 agents to the latest version (with the WMIC fix). We still have the same problem with the servers that have an unstable internet connection, but thanks to the memory check and restart script, we are not experiencing any issues. Of course, it would be nice if we could solve the problem. 😉

**Comment by si458** [comment]
@ouddorp i have been able to kinda replicate the memory leak using a linux machine but not a windows machine yet
if you shutdown/turn off ur meshcentral server, start up ur linux machine with the meshagent installed,
wait a few hours, you will see the memory has increased from like 33MB to 330MB, so like 10times!
so indeed i believe the lead is due to unstable internet connections and meshcentral servers going offline etc
so it does need investigating, i just havent been able to fully identify where its happening yet, just HOW its happening

**Comment by uiosun** [comment]
> [@ouddorp](https://github.com/ouddorp) i have been able to kinda replicate the memory leak using a linux machine but not a windows machine yet我已经在 Linux 机器上大致复现了内存泄漏，但在 Windows 机器上还没有成功。 if you shutdown/turn off ur meshcentral server, start up ur linux machine with the meshagent installed,如果你关闭/关闭你的 MeshCentral 服务器，启动安装了 meshagent 的 Linux 机器， wait a few hours, you will see the memory has increased from like 33MB to 330MB, so like 10times!等待几个小时，你会发现内存从大约 33MB 增加到 330MB，大约增加了 10 倍！ so indeed i believe the lead is due to unstable internet connections and meshcentral servers going offline etc所以我认为确实是因为不稳定的互联网连接和 MeshCentral 服务器离线等原因导致的 so it does need investigating, i just havent been able to fully identify where its happening yet, just HOW its happening所以这确实需要调查，我只是还没有完全确定它发生在哪里，只是不知道它是如何发生的

I use MeshCentral more than ten days, the max memory client use is 1.7G (find warning in a windows system tip), and I have a dozen client (and the internet connect is very instability), each client has 300+ ~ 800+M memory use.
﻿
If I want help anybody -- want to fix the bug, What can I upload log or other information to github? how to find them file?
