### ISSUE TITLE
meshcentralrouter sending double key presses in remote desktop

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4267]
**Describe the bug**
meshcentralrouter keeps sending double keys when i use remote desktop

**To Reproduce**
1. connect to a device
2. type website address into bar
3. press backspace
4. its double pressed it?

**Expected behavior**
only to send one key press rather than 2?

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] Docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] WAN, Traefik Reverse Proxy, Offload TLS
 - Version: [e.g. 1.0.43] 1.0.52
 - Node: [e.g. 18.4.0] 18.5.0
 - Browser: [e.g. Google Chrome] MeshCentralRouter

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Computer
 - OS: [e.g. Windows 10] Windows 10
 - Version: [e.g. 21H2] 21H2
 - Current Core Version (if known): Mar 25 2022, 4023832042

**Additional context**

**Your config.json file**
N/A

**Comment by folosleg** [comment]
double press only happens for backspace, but sure is happening for me as well
MC v1.0.52
Router v1.8.8223
Agent Core: Mar 25 2022, 2889969207 (Win64bit service)

**Comment by Ylianst** [comment]
Your right, I see the same thing on backspace... investigating this now.

**Comment by Ylianst** [comment]
MeshCentral v1.0.53 is out.

**Comment by folosleg** [comment]
Almost... Generally the bug is fixed, but for some odd reason on the Windows login screen, tha password field still behaves the same with double backspace.

**Comment by si458** [comment]
@folosleg you are indeed correct, while the bug is fixed for using windows, while the remote computer is on the lock screen the password prompt is still backspacing twice?

**Comment by folosleg** [comment]
MS Windows and its mysterious ways... 😕

**Comment by Ylianst** [comment]
Wow, your right, I see the same!

**Comment by Ylianst** [comment]
Put in a fix for this. Will be in MeshCentral v1.0.54.

**Comment by si458** [comment]
bingo! thanks @Ylianst downloaded exe from the git repo directly and it works a treat now!

**Comment by Ylianst** [comment]
Nice! Thanks for confirming.
