### ISSUE TITLE
Disabling backup codes also disables authenticator app

### ISSUE THREAD

**Issue by ph4xo** [Ylianst/MeshCentral#4268]
Hi all,

I'm in the middle of brining up our new MeshCentral server and was playing with the different 2FA setting in the `config.json` file. My goal is to **allow the authenticator app** but **disable the backup codes**. Unfortunately this is not possible because authenticator app is also disabled when backup codes are disabled.

1. For better visibility of the bug, add a security key under **My Account**.
2. Make sure that both option **Manage authenticator app** and **Manage backup codes** are available
3. Set `backupcode2factor` to `false `in `config.json` and restart MeshCentral
4. Go to **My Account** and **Manage backup codes** is gone
5. Clicking on **Manage authenticator app** brings up the Message "_Backup codes are locked_"

For my understanding, disabling **backup codes** should not interfere with **authenticator app** 

**"backupcode2factor": true**
1. ![image](https://user-images.githubusercontent.com/109282108/178964884-cb8073e2-dd6d-4dc7-95a4-9dad621671ff.png)
2. ![image](https://user-images.githubusercontent.com/109282108/178965217-bb687e3d-7d2a-4085-b3d6-d2f47720c7a5.png)
3. ![image](https://user-images.githubusercontent.com/109282108/178965341-73c1e1f7-5d51-46d8-9ded-571f142e9dd0.png)

**"backupcode2factor": false**
1. ![image](https://user-images.githubusercontent.com/109282108/178965565-919f31dd-16a1-4f11-be50-f32df60fc68c.png)
2. ![image](https://user-images.githubusercontent.com/109282108/178965633-e56c3d31-588e-451f-ba6f-80fb347a1eab.png)

Cheers,
Timo

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Your right. Fixed in MeshCentral v1.0.53 when I publish it later today.

**Comment by Ylianst** [comment]
MeshCentral v1.0.53 is out.

**Comment by ph4xo** [comment]
What can I say, you are a machine. 😊 Works like expected now.
