### ISSUE TITLE
Error reading or writing history file '...\PSReadLine\ConsoleHost_history.txt': Access to the path '...\PSReadLine\ConsoleHost_history.txt' is denied.

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4270]
**Describe the bug**

when using the admin powershell, after running the first command you get this error
```
Error reading or writing history file 'C:\windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt': Access to the path 'C:\windows\syste
m32\config\systemprofile\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt' is denied.
```

but also its not remembering the history of commands being run

**To Reproduce**
1. open up terminal
2. right click and click 'Admin powershell'
3. run any powershell/cmd command e.g `net stats workstation`

**Expected behavior**
not show this error, also remember powershell history?

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] Docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] WAN, Traefik Proxy, Offload TLS
 - Version: [e.g. 1.0.43] 1.0.51
 - Node: [e.g. 18.4.0] 18.5.0
 - Browser: [e.g. Google Chrome] Firefox

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Computer
 - OS: [e.g. Windows 10] Windows 10
 - Version: [e.g. 21H2] 21H2
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
N/A

**Comment by Ylianst** [comment]
Looks like one for Bryan who works on the agent.

**Comment by CityguyUSA** [comment]
Looks like Bryan's not interested.
