### ISSUE TITLE
Web-RDP is working only for default site

### ISSUE THREAD

**Issue by ph4xo** [Ylianst/MeshCentral#4271]
Hi all together,

I'm struggling with a problem for a week now and hopefully someone can help me or give feedback if it ist working for other MeshCentral users. At the moment it seems to be a bug for me.

We have a MeshCentral server with one default site which is only used for some quick support and can be accessed by different departments. There are also two additional sites for two different subsidiaries to which all computers are connected for internal IT support only. We are using `dns `setting for both sites for using a FQDN. Unfortunately, Web-RDP is working only on the default domain. When using Web-RDP for the other "subsites", I just see "**Setup**" on the webpage, hanging for around 30 seconds and then getting a "**Disconnected**". The main site works fine and Web-RDP connects nearly immediately.

![image](https://user-images.githubusercontent.com/109282108/179027328-b8173f4e-720b-4f02-853d-f7b31508077e.png)

The most interesting part is, when using MeshCentral-Router, everything works like a charm. No problems using RDP protocol, no matter if client is local or connected via agent only.

I made a trace for both situations and I can see, that the using the default website, the RDP Relay websocket opens and Web-RDP is established:

> "17:41:09","dispatch","DispatchEvent, *,node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU,user//username,mesh//2zo0nmfX8jvr2eaNzptgNLc6$5Udxv5H$vDDq6J4xResAr2lT2hO7ukmVRoXrJUL"
> "17:41:09","dispatch","DispatchEvent, node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU,*,mesh//2zo0nmfX8jvr2eaNzptgNLc6$5Udxv5H$vDDq6J4xResAr2lT2hO7ukmVRoXrJUL,ugrp//5HiPK7mBxJILjYB9rdxpC8$1P@Cz@Yz71RUQeCNDmoqafk@5us2oJ4G2p17hRfrv"
> "17:41:09","dispatch","DispatchEvent, *,user//username"
> **"17:41:09","relay","Relay connected: 5452189336708162 (x.x.x.x --> x.x.x.x)"**
> **"17:41:09","cookie","Decoded AESGCM cookie: {"ruserid":"user//username","time":1657813269000,"dtime":366}"**
> **"17:41:09","webrequest","(x.x.x.x) /meshrelay.ashx/.websocket?id=5452189336708162&rauth=4d7nIoXNRnpwnrFzdMTamGiirU0n%40tmxoeFbqbmgraijzhfrD6U4V48OFMrK8VE%40ZARlFbf7oghbgTi%24OAnUVW%24yVRA7qx8q9aaw8g7VPQ=="**
> "17:41:09","httpheaders","GET, /meshrelay.ashx/.websocket?id=5452189336708162&rauth=4d7nIoXNRnpwnrFzdMTamGiirU0n%40tmxoeFbqbmgraijzhfrD6U4V48OFMrK8VE%40ZARlFbf7oghbgTi%24OAnUVW%24yVRA7qx8q9aaw8g7VPQ==, [object Object]"
> **"17:41:09","relay","Relay holding: 5452189336708162 (x.x.x.x) Authenticated"**
> **"17:41:09","relay","Relay: Sending agent tunnel command: {"nodeid":"node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU","action":"msg","type":"tunnel","value":"*/meshrelay.ashx?id=5452189336708162&rauth=4d7nIoXNRnpwnrFzdMTamGiirU0n@tmxoeFbqbmgraijzhfrD6U4V48OFMrK8VE@ZARlFbf7oghbgTi$OAnUVW$yVRA7qx8q9aaw8g7VPQ==","tcpport":3389,"soptions":{"consentTimeout":10,"consentAutoAccept":true},"userid":"user//username"}"**
> "17:41:09","cookie","Encoded AESGCM cookie: {"ruserid":"user//username","time":1657813269}"
> **"17:41:09","relay","RDP: Relay websocket open"**
> "17:41:09","cookie","Decoded AESGCM cookie: {"userid":"user//username","domainid":"","nodeid":"node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU","tcpport":3389,"time":1657813269000,"dtime":129}"
> "17:41:09","webrequest","(x.x.x.x) /meshrelay.ashx/.websocket?p=10&auth=nVYKVnSl2bzCgNSboNGe7DXU6RbsCk1y5BnZKhTIu8A1ih7F@4Fjn2Tkawlhw5reZ9dzmBleNUydc@8HoWjoaaSX3Pp2fliLTW10q2fhL2PQ@gWSSdXV5bjJ5OkbUccRZLVobMx9LASxAiMHbXteZX5IQO6M6pMj32TowuCyseSf0M5EOO6W4cHN$2y7V5Hy7nirunWOGPG4PTWQ6weTY48Ew3iYQB20QscVAilt3Q0pj$OSH$cNM77FNF8P"
> "17:41:09","httpheaders","GET, /meshrelay.ashx/.websocket?p=10&auth=nVYKVnSl2bzCgNSboNGe7DXU6RbsCk1y5BnZKhTIu8A1ih7F@4Fjn2Tkawlhw5reZ9dzmBleNUydc@8HoWjoaaSX3Pp2fliLTW10q2fhL2PQ@gWSSdXV5bjJ5OkbUccRZLVobMx9LASxAiMHbXteZX5IQO6M6pMj32TowuCyseSf0M5EOO6W4cHN$2y7V5Hy7nirunWOGPG4PTWQ6weTY48Ew3iYQB20QscVAilt3Q0pj$OSH$cNM77FNF8P, [object Object]"
> "17:41:09","relay","RDP: Connection websocket to ws://localhost:80/meshrelay.ashx?p=10&auth=nVYKVnSl2bzCgNSboNGe7DXU6RbsCk1y5BnZKhTIu8A1ih7F@4Fjn2Tkawlhw5reZ9dzmBleNUydc@8HoWjoaaSX3Pp2fliLTW10q2fhL2PQ@gWSSdXV5bjJ5OkbUccRZLVobMx9LASxAiMHbXteZX5IQO6M6pMj32TowuCyseSf0M5EOO6W4cHN$2y7V5Hy7nirunWOGPG4PTWQ6weTY48Ew3iYQB20QscVAilt3Q0pj$OSH$cNM77FNF8P"
> "17:41:09","relay","RDP: Starting RDP client on loopback port 34667"
> "17:41:09","cookie","Encoded AESGCM cookie: {"userid":"user//username","domainid":"","nodeid":"node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU","tcpport":3389,"time":1657813269}"
> "17:41:09","relay","RDP: Request for RDP relay (x.x.x.x)"
> "17:41:09","webrequest","(x.x.x.x) /mstscrelay.ashx/.websocket"
> "17:41:09","httpheaders","GET, /mstscrelay.ashx/.websocket, [object Object]"
> "17:41:05","dispatch","DispatchEvent, *"

Using one of the other sites, I can see that the Relay sockets opens, nothing further happens and than get closed after 30 seconds.

> "17:42:58","dispatch","DispatchEvent, node//PbSykeCCU8fQJ4rH6dsf49G42Xwim4QIZnh2pDR95H8Gq0vIRcyIzJ8mR5PVtYtU,*,mesh//2zo0nmfX8jvr2eaNzptgNLc6$5Udxv5H$vDDq6J4xResAr2lT2hO7ukmVRoXrJUL,ugrp//5HiPK7mBxJILjYB9rdxpC8$1P@Cz@Yz71RUQeCNDmoqafk@5us2oJ4G2p17hRfrv"
> "17:42:58","dispatch","DispatchEvent, node/XXX/w9ZvkyRbrc8tgPOL1pCPSWXIpd3ylvgEXZUPRUIAb1pdDgUClkXSczMGqlqHQf0q,*,mesh/XXX/ChqKe4A8BnmalIOY411rc9Q1HyTY1$ohB$P2JADMbuW60758SunFDOZnZZpU47Bo,ugrp/XXX/MIS74ASt9moOKaxYrM6@ZgxHnxaczH3tWNVkoeXFpvFiL9L71t$6h9dAiivxW5BE"
> "17:42:58","dispatch","DispatchEvent, node/mkm/DhrFvTx6neDtvzD3kXWZOucVlGcS7xXB3n0vthRHC36mObLurVoJlBcS73rwyjJo,*,mesh/mkm/AgBTKjBFxe8kRV@feaEHQwaEn1Y2fAp@GaeEWvPW7XmlNFzRQew4dD0n8AIsXUoO,ugrp/mkm/MbX8dXgqimtYtgHIm680HfjIChTe3plC6HK0EK4IYVu6zi4yroqRqerNoDuixj1E"
> **"17:42:52","relay","RDP: Relay websocket closed"**
> **"17:42:22","relay","RDP: Relay websocket open"**
> "17:42:22","relay","Relay: Soft disconnect (x.x.x.x)"
> "17:42:22","cookie","Decoded AESGCM cookie: {"userid":"user/XXX/username","domainid":"XXX","nodeid":"node/XXX/w9ZvkyRbrc8tgPOL1pCPSWXIpd3ylvgEXZUPRUIAb1pdDgUClkXSczMGqlqHQf0q","tcpport":3389,"time":1657813342000,"dtime":631}"
> "17:42:22","webrequest","(x.x.x.x) /meshrelay.ashx/.websocket?p=10&auth=9FN$HNIKhd91etBOx0lYt9KfhC9Z2VQPR0GqWTpG2PgbsdLp$QpjVdTOfNn3s$rJug5E6f0HjMpk@8tPJRzM@rtXRExwbzZYD7qcAPWMyK17AP2Vyf0@x3tOwTFK9gyV6m6fOXkJrn73vb9pxsNAIODZn8TLp@OeZg9ja1bFeMJtKOpgUND8Kerd@RDwVuJfaeTYea4hUNDYZ0GWEyh5fxDgv8$XZQV0OK6eXYGlaq3rRKrAoUptG5Z79m9cXa4hiy9Zo4Dg"
> "17:42:22","httpheaders","GET, /meshrelay.ashx/.websocket?p=10&auth=9FN$HNIKhd91etBOx0lYt9KfhC9Z2VQPR0GqWTpG2PgbsdLp$QpjVdTOfNn3s$rJug5E6f0HjMpk@8tPJRzM@rtXRExwbzZYD7qcAPWMyK17AP2Vyf0@x3tOwTFK9gyV6m6fOXkJrn73vb9pxsNAIODZn8TLp@OeZg9ja1bFeMJtKOpgUND8Kerd@RDwVuJfaeTYea4hUNDYZ0GWEyh5fxDgv8$XZQV0OK6eXYGlaq3rRKrAoUptG5Z79m9cXa4hiy9Zo4Dg, [object Object]"
> "17:42:22","relay","RDP: Connection websocket to ws://localhost:80/meshrelay.ashx?p=10&auth=9FN$HNIKhd91etBOx0lYt9KfhC9Z2VQPR0GqWTpG2PgbsdLp$QpjVdTOfNn3s$rJug5E6f0HjMpk@8tPJRzM@rtXRExwbzZYD7qcAPWMyK17AP2Vyf0@x3tOwTFK9gyV6m6fOXkJrn73vb9pxsNAIODZn8TLp@OeZg9ja1bFeMJtKOpgUND8Kerd@RDwVuJfaeTYea4hUNDYZ0GWEyh5fxDgv8$XZQV0OK6eXYGlaq3rRKrAoUptG5Z79m9cXa4hiy9Zo4Dg"
> "17:42:22","relay","RDP: Starting RDP client on loopback port 34727"
> "17:42:22","cookie","Encoded AESGCM cookie: {"userid":"user/XXX/username","domainid":"XXX","nodeid":"node/XXX/w9ZvkyRbrc8tgPOL1pCPSWXIpd3ylvgEXZUPRUIAb1pdDgUClkXSczMGqlqHQf0q","tcpport":3389,"time":1657813342}"
> "17:42:22","relay","RDP: Request for RDP relay (x.x.x.x)"
> "17:42:22","webrequest","(x.x.x.x) /mstscrelay.ashx/.websocket"
> "17:42:22","httpheaders","GET, /mstscrelay.ashx/.websocket, [object Object]"

Is anyone successfully using Web-RDP for a sub site with `dns `setting?

Cheers,
Timo

**Comment by si458** [comment]
_please can you follow the bug report template in the future as you are missing key variables to help us debug your problem_

What version of the server are you running?
What is your setup? Os, node, wan/lan mode?
What's the clients os, version, agent core version

**Comment by Ylianst** [comment]
I am going to try to replicate this now.

**Comment by Ylianst** [comment]
I think I replicated it... I need to figure out what is going on. This is a complex flow, could take a while.

**Comment by Ylianst** [comment]
MeshCentral v1.0.53 is out, let me know if that fixes it.

**Comment by ph4xo** [comment]
> _please can you follow the bug report template in the future as you are missing key variables to help us debug your problem_
> 
> What version of the server are you running? What is your setup? Os, node, wan/lan mode? What's the clients os, version, agent core version

Sorry about that, I will follow the report next time.


> MeshCentral v1.0.53 is out, let me know if that fixes it.

It is fixed, thank you very much. That was unbelievable fast!
