### ISSUE TITLE
network interfaces view hides copy button

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4275]
**Describe the bug**
when you click the `interfaces` option it shows the network interfaces and all its IP addresses
but when you scroll or hover over the copy buttons,
the stupid scroll bar is blocking access to them

**To Reproduce**
1. click `interfaces`
2. hover over a copy icon

**Expected behavior**
able to click the copy button, without the scrollbar intefering

**Screenshots**
![Screenshot 2022-07-15 100333](https://user-images.githubusercontent.com/765314/179194111-705f179b-6628-4e02-af82-d45215195d54.png)
![Screenshot 2022-07-15 100359](https://user-images.githubusercontent.com/765314/179194145-1831575f-be8b-450b-995f-b3f483d1ffef.png)

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] Docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] WAN, Traefik Proxy, TLS Offload
 - Version: [e.g. 1.0.43] 1.0.53
 - Node: [e.g. 18.4.0] 18.5.0
 - Browser: [e.g. Google Chrome] Firefox 102

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Server
 - OS: [e.g. Windows 10] Windows Server 2012 R2
 - Version: [e.g. 21H2] N/A
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
i could copy the information from the `details` tab instead but the is no copy icons on the `details` tab

**Your config.json file**
N/A

**Comment by Ylianst** [comment]
Interesting, I don't see this on my browsers with my OS... Edge:

![image](https://user-images.githubusercontent.com/1319013/179237760-9d109a62-6448-4415-9d99-a0fbaeb66cb7.png)

FireFox:

![image](https://user-images.githubusercontent.com/1319013/179237814-6aa25438-5767-4ade-a93e-ee6adcce006f.png)

Chrome:

![image](https://user-images.githubusercontent.com/1319013/179237866-8fc6816c-3eb4-4da1-9824-b4b41c10113e.png)

This must be an OS thing with the type of Scroll bar used.

**Comment by si458** [comment]
@Ylianst yeh just tried it here and its fine with Edge and Chrome, but not Firefox (my primary browser)

**Comment by PetieM** [comment]
I'm seeing this in all browsers on my Mac. It's related to scroll bar rendering - I have it set to show them only when scrolling which overlays them on the content when you scroll as in si458's screenshots (though for me at least, the buttons become clickable if you just wait for the scroll bar to fade first). If I set it to always show scroll bars, they behave as shown in Ylianst's screenshots.

**Comment by Ylianst** [comment]
Ok, I am seeing this issue on FireFox with Windows 11.

![scroll](https://user-images.githubusercontent.com/1319013/179630429-1214ad5f-451e-41c6-97ac-ecb4af01b3b9.png)

Let me see what I can do.

**Comment by Ylianst** [comment]
Not sure what I can do about this. If I change the Windows 11 setting to "Always Show Scrollbars", it works ok in FireFox, but I am not sure I have a way in HTML to override this when scroll bars are not shown.

**Comment by PetieM** [comment]
That sounds consistent with the behavior I was seeing. Just letting the scroll bar fade away seems to work fine on my end but if you wanted to fix it from the server side, the only way I can think of that would work would be to add right padding equal to the width of the scroll bar which would, in theory, push the buttons out of the path of the bar (at the cost of looking a little odd). Personally, I think it’s fine as is but figured I’d throw in a possible solution for once!

**Comment by Ylianst** [comment]
Another alternative is to put the "copy" icon left of the text instead of right, but it would not look as nice. I will hold off until @si458 gives some opinion of this.

**Comment by NiceGuyIT** [comment]
You could create a [UserStyle](UserStyles.world) and add the padding using an extension like Stylus. The red color is to see the padding.

```text
/* ==UserStyle==
@name           MeshCentral
@namespace      https://github.com/Ylianst/MeshCentral
@version        1.0.0
@description    MeshCentral UI changes
@author         You
==/UserStyle== */

@-moz-document domain("mesh.example.com") {
    #d2netinfo .dialogText {
        padding-right: 1.0em;
        background-color: red;
    }
}
```
