### ISSUE TITLE
ldapUserRealName empty

### ISSUE THREAD

**Issue by ph4xo** [Ylianst/MeshCentral#4276]
I already mentioned this in the following issue but thought it would be the best to open a new ticket.

#https://github.com/Ylianst/MeshCentral/issues/1776#issuecomment-1184503945

I'm currently struggling with `ldapUserRealName`. Whatever I try, the real name is never populated with any information. I tried `"ldapUserRealName": "displayName"` and also `"ldapUserRealName": "name"` but it is still empty. `ldapUserEmail `and the rest is working like a charm.

**Server Software:**
 - OS: Ubuntu Linux 20.04.4
 - Version: 1.0.53
 - Node: v10.19.0

**config.json file**
```
      "auth": "ldap",
      "ldapUserName": "sAMAccountName",
      "ldapUserKey": "sAMAccountName",
      "ldapUserEmail": "mail",
      "ldapUserRealName": "displayName",
      "ldapOptions": {
        "url": "ldap://domain.local:389",
        "bindDN": "CN=LDAP,OU=Service Accounts,OU=Users,OU=Corp,DC=domain,DC=local",
        "bindCredentials": "************",
        "searchBase": "OU=Corp,DC=domain,DC=local",
        "searchFilter": "(&(objectCategory=Person)(sAMAccountName={{username}}))"
      },
```

**Comment by ph4xo** [comment]
Just checked the code in webserver.js and had a look at the ldap section starting line 442. There is no code for `domain.ldapuserrealname`.

**Comment by Ylianst** [comment]
Your right. Looking into this now.

**Comment by Ylianst** [comment]
Starting with MeshCentral v1.0.54, you can add this line in the domain section of the config.json:

```
  "ldapSaveUserToFile": "C:\\temp\\ldapuser.txt"
```

This will save the LDAP user object to this file when a user logs in. Should be helpful for debugging LDAP stuff.

**Comment by Ylianst** [comment]
MeshCentral v1.0.54 is out, so, you can update, and use "ldapSaveUserToFile" instead of changing the code.

**Comment by ph4xo** [comment]
Thank you very much. I have saved the data to a file and already sent you an email.

**Comment by Ylianst** [comment]
Ok, this issue will be fixed in MeshCentral v1.0.55.

**Comment by ph4xo** [comment]
It works perfectly! All attributes are synced with the MeshCentral account, no need to update anything manually. Than you very much for this great work!

**Comment by Ylianst** [comment]
After this work, I recorded a YouTube video on MeshCentral LDAP integration. It will be on YouTube in the coming weeks.
