### ISSUE TITLE
2 New remote desktop commands

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#428]
Hi Ylian, 

I know you are very busy and i wanted to add 2 new commands for remote desktop that allows me to move windows from a screen out of focus to another and they are WIN+LEFT and WIN+RIGHT.

Here is the complete code i made, if you would like to add them in Meshcentral by default and not required for me to add them each time i update meshcentral.

In default.handlebars

    // In <select id="deskkeys">
    <option value=10>Win+Left</option>
    <option value=11>Win+Right</option>

    //And in deskSendKeys function
    else  if (ks == 10) { // WIN-LEFT
        if (desktop.contype == 2) {
             desktop.m.sendkey([[0xffe7,1],[0xff51,1],[0xff51,0],[0xffe7,0]]); // Intel AMT: Meta-left down, Left arrow press, Left arrow release, Meta-left release
        } else {
            desktop.m.SendKeyMsgKC([[desktop.m.KeyAction.EXDOWN,0x5B],[desktop.m.KeyAction.DOWN,37],[desktop.m.KeyAction.UP,37],[desktop.m.KeyAction.EXUP,0x5B]]);
       }
    } else if (ks == 11) { // WIN-RIGHT
        if (desktop.contype == 2) {
            desktop.m.sendkey([[0xffe7,1],[0xff53,1],[0xff53,0],[0xffe7,0]]); // Intel AMT: Meta-left down, Right arrow press, Right arrow release, Meta-left release
        } else {
            desktop.m.SendKeyMsgKC([[desktop.m.KeyAction.EXDOWN,0x5B],[desktop.m.KeyAction.DOWN,39],[desktop.m.KeyAction.UP,39],[desktop.m.KeyAction.EXUP,0x5B]]);
        }
    }

Thanks

**Comment by Ylianst** [comment]
Sure, I will add it tomorrow. Your making my life easy too, thank you.

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-r with your added special keys. Let me know if that works.

**Comment by treicadani** [comment]
They works as intended, Many thanks!
