### ISSUE TITLE
Intel AMT CIRA is not seen on drop down selection Menu

### ISSUE THREAD

**Issue by wiseobs** [Ylianst/MeshCentral#4280]
Hello
I am new at using Mesh Central. I am stuck as the CIRA selection is not shown on the connectivity drop down box, and this is the connection mode I require.
I have verified the server is running in Hybrid mode, and "cert" is active with a domain name.
Perhaps it is the settings in the AMT itself?
Can any help me to fix this issue?

Thank you
Adrien Richardson

**Comment by Ylianst** [comment]
Can you send a screen shot of the drop down box your are talking about?

**Comment by wiseobs** [comment]
![image](https://user-images.githubusercontent.com/109459589/179419749-dd969111-175c-4d56-a82a-0034dd6236bc.png)
Hello Ylian This is the screen shot
Merci !
Adrien

**Comment by Ylianst** [comment]
Looking at the code, there are 2 conditions that would cause the CIRA option to not be shown.

1 - The server is in LAN mode. You can check for sure by typing the "info" command in the "My Server / Console" tab like this:

![image](https://user-images.githubusercontent.com/1319013/179625702-cb4842b6-5493-40d1-8623-71714516ba87.png)

2 - The MPS port is set to zero. If you add this line in the setting section of the config.json:

```
"mpsport": 0
```

The server that will listen for incoming CIRA connections will be disabled and so, CIRA is not activate for your server. You could also have that port busy. By default port 4433 is used and if your running two instances of MeshCentral, the second instance will not be able to get port 4433. You can check the MPS port for sure by opening "meshcentral-data/serverstate.txt", it should look like this:

![image](https://user-images.githubusercontent.com/1319013/179626102-c5c15992-72df-484b-8bfb-ab43bad36118.png)

Note the "mps-port" should be set to a non-zero value.

Let me know if this helps.

**Comment by wiseobs** [comment]
I attach the screen shots. I Still cant get CIRA to appear. The MPS port is definitely not Zero.
As this is a test setup before deployment, I wonder if I should completely start from fresh?. If so, would you have  recommended steps? Thank you for your assistance. 

![No CIRA](https://user-images.githubusercontent.com/109459589/179695818-ecf082e5-4c04-496c-bc89-4a35bd2157f5.jpg)

**Comment by wiseobs** [comment]
I uninstalled, and reinstalled everything. I do now see CIRA, so that is good, but now have a port issue. MS is not running.

![Port 4433](https://user-images.githubusercontent.com/109459589/179772027-08de0b3a-7ffd-4747-8c6d-7176b6f6905e.jpg)

**Comment by Ylianst** [comment]
I see your getting a "port 4433 is not available" error. As indicated, this is because someone else is using this port, very likely another instance of MeshCentral. You can also see that your server bound to ports 81/444. So, MeshCentral could not get port 80/443 and got the next available ones.

In general the problem is that you are running two MeshCentral instances at the same time. Probably one as a background Windows Service and one in the command line. Which ever instance can grab port 4433 will have a running MPS and CIRA should work, but the second instance will not have port 4433 and CIRA will not work and so, no CIRA option.

Hope that helps.

**Comment by dinger1986** [comment]
@si458 can close @silversword411 has already done docs
