### ISSUE TITLE
disconnection mail notification wrong italian template

### ISSUE THREAD

**Issue by leleb** [Ylianst/MeshCentral#4282]
![Immagine 2022-07-18 011025](https://user-images.githubusercontent.com/1241802/179428563-4d03d180-a873-4d1d-afd5-9e60f20780ff.jpg)
 the disconnection mail template for italian has a translated placeholder thus is not replaced with disconnected device name.

**Comment by si458** [comment]
can you possible try my fix change manually?
1. change based on my commit - https://github.com/si458/MeshCentral/commit/071d0bba8591f0782b0aecb293a13951312d1cd1
2. re-run the translate convert
3. restart meshcentral
4. see if this fixes it?

**Comment by Ylianst** [comment]
Thanks for reporting this. I just put in a fix for this, will be in MeshCentral v1.0.54. I found the same and other issues for other languages too.

**Comment by Ylianst** [comment]
MeshCentral v1.0.54 is out, should be fixed.

**Comment by leleb** [comment]
fix works fine thanks
