### ISSUE TITLE
Mobile terminal wont accept Enter key

### ISSUE THREAD

**Issue by diogo24m** [Ylianst/MeshCentral#4294]
Hello,

There's a bug on the terminal on mobile that doesn't accept the Enter key. Everything else is working fine.

 - Phone: Xiaomi Mi 9 SE
 - OS: Android 11 (MIUI 12.5.1)
 - Browser: Tested on Brave and Google Chrome

**Comment by si458** [comment]
this seems to work as expected, please update to the latest version 1.1.20
