### ISSUE TITLE
Web relay to a remote URL with port number

### ISSUE THREAD

**Issue by bodycount28** [Ylianst/MeshCentral#4297]
I maybe missing something simple...  I've successfully configured web relay through a reverse proxy, however is it possible to configure a web relay device to get to a URL that uses a port number?

Using Portainer as an example:  By default to access it locally it uses http://<local_IP>:9000.  I tried appending the port in the hostname field but it didn't like it.

If so, how is it configured?

**Comment by Ylianst** [comment]
Ha yes, you can do it. In the device's general tab, right click on the "HTTP" or "HTTPS" link and check the port to 9000. Once done, hit the link and it should work.

![image](https://user-images.githubusercontent.com/1319013/180069910-16c36f4a-42d5-41da-90f4-4daeed45d15f.png)

Let me know if that works.

**Comment by bodycount28** [comment]
Bah, knew it was something simple!  Thanks for the quick response and confirmed it's working.   Please close...

**Comment by Ylianst** [comment]
Nice. Grad I could help.
