### ISSUE TITLE
IP and Username Logged in.

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#43]
Add username logged in, and IP of remote machine in various views to be able to see if someone is logged in and where.  Useful when X Person says "i'm logged in upstairs"  we can search for their username and know which machine they are using.  Blank if nobody logged in

**Comment by Ylianst** [comment]
This is a good idea. We have the list of logged in users on each computer, so we just need to display that information. As for the IP address, I need to do a bit more work to get that information to the web page. No sure when I will get this done, but will get around to it.

**Comment by brejn** [comment]
+1 for username on list
That's basically only feature that i'm missing for this to be perfect.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.0-l with improved device list. You now see the devices public ip address and currently logged in users for each device. Not documented, but you can type "user:bob", "ip:192.168." or "group:mycomputer" in the search box now to filter what you want.

![MC2-ListView](https://user-images.githubusercontent.com/1319013/54458739-f3b92200-4721-11e9-97d8-5e364ef9d56a.png)

Hopefully, now it's perfection :)

**Comment by Ylianst** [comment]
Closing this issue since this is done. Feel free to open a new issue if needed.
