### ISSUE TITLE
Issues with embedding

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshCentral#430]
Hey there,

i recently discovered some issues while embedding MeshCentral into my website.
I know this worked a couple of months ago as i tried it there and now when i want to implement this into production, it doesn't seem to work anymore.

Following issues:
- it seems to ignore the "viewmode" option in the url. No matter how i set this, it ends up on the "devices" page
- when providing a "node" option in the url, i end up on the "devices" page as well but im not even seeing my online devices. when i don't provide a "node" option in the url, i see the online devices.

Can you please have a look into this. To me it looks like "viewmode" is broken

**Comment by Ylianst** [comment]
Oh, that is not good. Checking now.

**Comment by Ylianst** [comment]
Your right. I will have an update this afternoon with a fix for this.

**Comment by marco-vogt** [comment]
Perfect, thank you. I will test it after your update

**Comment by Ylianst** [comment]
Published MeshCentral v0.3.9-v with a fix for this. Let me know if it works for you.

**Comment by marco-vogt** [comment]
Ok, i can test it tomorrow and let you know. Thanks

**Comment by marco-vogt** [comment]
Works like a charm again, thanks!
