### ISSUE TITLE
Letsencrypt rejecting SHA-1 cert requests starting September 15, 2022

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#4300]
**Describe the bug**
i have received a mail from letsencrypt...

**To Reproduce**
mail:
Our records show that the software you use to get Let's Encrypt certificates sends Certificate Signing Requests (CSRs) that use the SHA-1 hash algorithm. SHA-1 has been deprecated by NIST since 2011. Let's Encrypt is now fully removing support for this hash in CSRs, as of September 15, 2022: https://community.letsencrypt.org/t/rejecting-sha-1-csrs-and-validation-using-tls-1-0-1-1-urls/175144.

We estimate that this change will affect 1.18% of certificate issuances, including yours. Here are your affected hostnames:

Hostnames:

"my hostname for meshcentral server"

To fix this problem, most likely you need to update your software to the latest version. In particular, if you are using node-acme-client, you need to update to at least version 4.2.4.
https://community.letsencrypt.org/t/questions-about-tls-1-0-1-1-deprecation-for-acme-requests/176106 

-----------------------

meshcentral is up to date - node js also... 

hope you have an input what i have make wrong ;-)

thanks a lot and best regards to all

**Comment by Ylianst** [comment]
Interesting! Looking into this.

**Comment by Ylianst** [comment]
Information about this here: https://github.com/publishlab/node-acme-client/issues/59

**Comment by Ylianst** [comment]
It looks like this is going to be a problem for anyone that installed MeshCentral a year ago or more and got the older 'acme-client' installed. I need to work on detecting the older version and forcing and update of this library.

**Comment by Ylianst** [comment]
Ok, MeshCentral v1.0.57 will have a fix for this.

**Comment by wvt-adm** [comment]
thanks a lot for your real great work - your fix seems to be working! thanks a lot

**Comment by si458** [comment]
> thanks a lot for your real great work - your fix seems to be working! thanks a lot

please can you close the issue if its fixed now👍

**Comment by Ylianst** [comment]
Closing since there are many issues on this topic. I just published v1.0.59 which is looking good for me and should have the fix for Let's Encrypt.
