### ISSUE TITLE
letsencrypt change

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#4303]
Hi , i have received this email from letsencrypt:
Our records show that the software you use to get Let's Encrypt certificates sends Certificate Signing Requests (CSRs) that use the SHA-1 hash algorithm. SHA-1 has been deprecated by NIST since 2011. Let's Encrypt is now fully removing support for this hash in CSRs, as of September 15, 2022: https://community.letsencrypt.org/t/rejecting-sha-1-csrs-and-validation-using-tls-1-0-1-1-urls/175144.

We estimate that this change will affect 1.18% of certificate issuances, including yours. Here are your affected hostnames:

Hostnames:

xxxxxxxxxx

To fix this problem, most likely you need to update your software to the latest version. In particular, if you are using node-acme-client, you need to update to at least version 4.2.4.
https://community.letsencrypt.org/t/questions-about-tls-1-0-1-1-deprecation-for-acme-requests/176106 

Please let me know

**Comment by si458** [comment]
duplicate #4300

**Comment by tradexsrl** [comment]
thank's

**Comment by Ylianst** [comment]
MeshCentral v1.0.59 that was just published should fix this. Thanks for the report, much appreciated.

**Comment by tradexsrl** [comment]
thank's , installed v 1.0.60 , i'll know on october when there will be the cert renovation
