### ISSUE TITLE
LetsEncrypt issue and version 57

### ISSUE THREAD

**Issue by JReally** [Ylianst/MeshCentral#4305]
I too received the warning message about the issue.

I updated from version 56 to 57 but then found I could not connect

I tried renewing the certificate but still could not connect so rolled back MeshCentral to version 50 (the latest image that I had on file). I will explore further but that's the current state for my setup

My installation server is a RaspberryPi  if that has any importance to the issue.

JR

**Comment by vgajicic** [comment]
Our server is generating bunch of errors on 1.0.57 version that we updated 3 hrs ago.
 /home/###/node_modules/meshcentral/webserver.js:983
        const sec = parent.decryptSessionData(req.session.e);
You are able to log in and kick you out after 15 sec than go offline. 10 sec goes back online. was working fine prior updating to 1.0.57. Running on prem linux 4GB ram/ 4Core Cpu

**Comment by si458** [comment]
@gvs-v your issue is if a user is using a hardware key, please can you follow this issue #4307

@JReally _please can you follow the bug template in the future to help us replicate your issue_
what is your config.json? what is your server os, node version? what is your network setup?

**Comment by Ylianst** [comment]
I just published v1.0.58 with the `webserver.js:983` fix. I am on the road now, but managed to publish on NPM and working on pushing it on GitHub when I can.

**Comment by gvs-v** [comment]
> I just published v1.0.58 with the `webserver.js:983` fix. I am on the road now, but managed to publish on NPM and working on pushing it on GitHub when I can.

I just updated it and after the update server never came back online.. Restoring from backups.

**Comment by Ylianst** [comment]
I just rolled back "latest" to v1.0.56. I am going to figure out what is going on.

**Comment by gvs-v** [comment]
Thank you very much Ylian.

**Comment by Ylianst** [comment]
Just published v1.0.59, in that version `acme-client` should update to latest and everything should be ok.

**Comment by JReally** [comment]
version 59 worked for me 

thanks,
  JR

**Comment by Ylianst** [comment]
Thank you! Reporting then things work is super nice.
