### ISSUE TITLE
Error when trying to login after 1.0.57 upgrade

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#4307]
**Describe the bug**
I upgraded to 1.0.57 from 1.0.56.  I was able to log in from my main device that had the MFA token set to remember. However, from any device where I need to enter the MFA code, I am unable to log in.  The page simply errors out with a ERR_EMPTY_RESPONSE message . 
**To Reproduce**
1. Go to the meshcentral logon page
2. Enter the username and password
3. The page will then error out when it should be presenting the MFA entry screen. 

**Expected behavior**
It should present the MFA code entry dialog.

**Server Software (please complete the following information):**
 - OS: Windows Server 2022
 - Network: WAN, with no reverse proxy
 - Version: 1.0.57
 - Node: 18.3.0
 - Browser: Any browser

**Additional context**
Here is the error being logged in mesherrors.txt"
`-------- 7/22/2022, 3:56:56 PM ---- 1.0.57 --------

c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:983
        const sec = parent.decryptSessionData(req.session.e);
                                                          ^

TypeError: Cannot read properties of null (reading 'e')
    at getHardwareKeyChallenge (c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:983:59)
    at handleRootRequestEx (c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:2895:25)
    at Timeout._onTimeout (c:\Program Files\MeshCentral\node_modules\meshcentral\webserver.js:1154:56)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.3.0
`

**Comment by PathfinderNetworks** [comment]
To make matters worse, I tried to roll back to 1.0.56 and the error is still present even after restoring the entire meshcentral-data folder from the 1.0.56 backup.

**Comment by PathfinderNetworks** [comment]
Thankfully, as a temporary work around, I was able to disable the authenticator app from the one device that I could still log in to MeshCentral with.  With the authenticator app disabled I was then able to log in from other devices.  It's very possible this bug was created in 1.0.56 as I'm not certain I attempted to log in from any other devices after upgrading to 1.0.56.

**Comment by si458** [comment]
related @PathfinderNetworks the was a commit done for 1.0.57 which fixed this type of issue https://github.com/Ylianst/MeshCentral/commit/4db8ff39466698ec8169d903f5242ffec2132a97
but i have a feeling it was for users WITHOUT MFA, and sadly you are using users with MFA,
so i think @Ylianst just needs to copy and paste as such further up the code to fix this issue, unless u wanna try and submit a PR?

**Comment by decacis** [comment]
The issue seems to be minor (just a typo). The PR I submitted (#4308) fixes it by adding the missing equals sign.

**Comment by Ylianst** [comment]
Ok, I just roll back latest to v1.0.56. I am on the road and need to figure out what is going on.

**Comment by Ylianst** [comment]
I just looked at v1.0.58 and it looks like it's ok. The issue may be that if you are using Let's Encrypt and have an older version of `acme-client` and MeshCentral tries to update it and can't, your going to run into issues. It's just speculation on my part.

**Comment by decacis** [comment]
When trying to install meshcentral@1.0.58 from npm like this:

`npm install meshcentral@1.0.58`

It gives this error:
`
$ npm install meshcentral@1.0.58
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN ec2-user No description
npm WARN ec2-user No repository field.
npm WARN ec2-user No README data
npm WARN ec2-user No license field.

npm ERR! path /home/ec2-user/node_modules/meshcentral/bin/meshcentral
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ec2-user/node_modules/meshcentral/bin/meshcentral'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2022-07-23T03_15_59_057Z-debug.log
`

It doesn't happen with 1.0.57, it only outputs this:
`$ npm install meshcentral@1.0.57
npm WARN saveError ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ec2-user/package.json'
npm WARN ec2-user No description
npm WARN ec2-user No repository field.
npm WARN ec2-user No README data
npm WARN ec2-user No license field.
`

And it starts just fine (with the typo still present, of course)

**Comment by Ylianst** [comment]
Ha thank you!!! Looking into it now. That is outstanding information.

**Comment by Ylianst** [comment]
Thank you @decacis. Indeed, the v1.0.58 NPM package did not have the `/node_modules/meshcentral/bin` folder, I just added that folder to Github so this issue should not happen again.

**Comment by decacis** [comment]
@Ylianst Awesome! Glad I could help.

**Comment by PathfinderNetworks** [comment]
Once the updated 1.0.58 is published I'll update to it and re-activate the authenticator app.  I'll close this out if it works correctly.  Right now, however, the only available option is 1.0.56.

**Comment by Ylianst** [comment]
Just published v1.0.59 and updated by test server with it, looking good for me including 2FA.

**Comment by PathfinderNetworks** [comment]
I just updated to 1.0.59. This has resolved the issue with the site crashing with the authenticator app enabled.  
Thank you!
