### ISSUE TITLE
Active Sessions

### ISSUE THREAD

**Issue by gtmsew** [Ylianst/MeshCentral#4309]
Is there a way to limit the user active session number to x number?

**Comment by Ylianst** [comment]
Yes, in the domain section of the config.json, add this:

```
      "limits": {
        "_maxDevices": 100,
        "_maxUserAccounts": 100,
        "_maxUserSessions": 100,
        "_maxAgentSessions": 100,
        "maxSingleUserSessions": 10
      }
```

I think `maxSingleUserSessions` is the one your looking for.

**Comment by gtmsew** [comment]
hi @Ylianst 
thx for the reply, but it looks like maxSingleUserSessions counts every session. I did not specify the details I should in my question; sorry for that.

I'm looking for a parameter that will limit the active sessions to the PCs, e.g., user can only connect to 4 PCs at a time (but can open more tabs, and share the PC connection to a few people)
Is that possible?

**Comment by dinger1986** [comment]
@si458 stale

**Comment by si458** [comment]
sadly this isnt possible at the moment, so will close for now
