### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Fefo60** [Ylianst/MeshCentral#4311]
Current version bigger than Latest

![image](https://user-images.githubusercontent.com/103059358/180613350-0ce6233c-a209-4d0c-b48e-9f86b5046a47.png)

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Network: WAN
 - Version: 1.0.57
 - Browser: Google Chrome

**Comment by si458** [comment]
this is related to https://github.com/Ylianst/MeshCentral/issues/4307#issuecomment-1193043594
@Ylianst pushed out the new 1.0.58 version to npm then realised the was a bug so had to roll back
so i believe he just needs to re-publish the update then change the latest to 1.0.58

**Comment by Ylianst** [comment]
@si458 Exactly.

I just published v1.0.59 and updated my test server and it seems to work well, including 2FA. I am on the road until wednesday so keeping MeshCentral changes to a minimum, but this version is looking good.
