### ISSUE TITLE
Language cannot be changed after update (v1.0.59)

### ISSUE THREAD

**Issue by FelixCZ** [Ylianst/MeshCentral#4312]
After last update to v1.0.59 language cannot be changed. If I try to change to another language it stays set to english. I try change also via url ?lang=cs, but no effect...

    "meshVersion": "v1.0.59",
    "nodeVersion": "v18.3.0",
    "platform": "linux",
    "arch": "x64",

Thank you.

**Comment by si458** [comment]
**PLEASE CAN YOU FOLLOW THE BUG TEMPLATE IN THE FUTURE AS IT INCLUDES CRITICAL INFORMATIOK TO HELP WITH YOUR ISSUE**
How are you running meshcentral? Docker image, directly from npm?
What's your os?
what's your browser?

**Comment by FelixCZ** [comment]
Run: Directly from NPM.
OS: Ubuntu 20.04.4 LTS
Tested on: Chrome, MS Edge
Previous version: v1.0.55

**Comment by si458** [comment]
how are you changing the language? as ive just tried it here and no issues?
open up meshcentral, open `my account`, click `Localization Settings`, change language, click ok, refresh webpage

**Comment by si458** [comment]
oh dear the translations folder is missing on the latest npm 1.0.59!
https://unpkg.com/browse/meshcentral@1.0.59/views/

to fix this do the following:
1. stop meshcentral
2. `cd (MESHCENTRAL FOLDER)`
3. `cd translate`
4. `node translate.js extractall` (if you get a node module is missing then re-run command again)
5. `node translate.js translate`
6. **WAIT (HAVE A BREW)**
7. start meshcentral
8. try again

@Ylianst is away at the moment and im sure once he is stationary he should be able to re-upload the 1.0.59 to npm

**Comment by Ylianst** [comment]
Published v1.0.60 with the fix. Apologies for this, totally my fault.

**Comment by Ylianst** [comment]
Should be fixed. Closing.
