### ISSUE TITLE
Localisation issue after update

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#4314]
**Describe the bug**
After the update from 1.0.56 to 1.0.59 localisation of the language is not accepted any more by the browser.
Standanrd is use browser default, also swichting to another language does not resolve the issue

**To Reproduce**

**Expected behavior**
precenting the provided language by the browser detection

**Screenshots**
![language issue 1 0 59](https://user-images.githubusercontent.com/58996467/180646499-e142899a-185a-4b84-ab41-ea228254c1c5.jpg)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: -------
 - Network: hybrid lan/wan
 - Version: 1.0.59
 - Node: 16.16.0
 - Browser: Google Chrome & Edge & FireFox

**Remote Device (please complete the following information):**
 does not apply
**Additional context**

**Your config.json file**
does not apply
```

**Comment by si458** [comment]
This is linked to #4312, its a duplicate issue
The is a bug with the release of 1.0.59 on nom
Please can you close this issue and follow the other one

**Comment by Ylianst** [comment]
v1.0.60 just published with a fix for this. Apologies.

**Comment by petervanv** [comment]
No problem, your always fixing fast.
Confirmed fix Thx @Ylianst
