### ISSUE TITLE
Desktop > Settings missing when in full-screen Full Screen mode.

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#4326]
Near the right end of the top bar in the Desktop tab, there are an "Actions" button and a "Settings" button.  Above that, and a bit further to the right, there is a "Full Screen" button.  If you <kbd>Shift</kbd>+Click on the "Full Screen" button the "Settings" button disappears.  The "Actions" button is still present, but to get to the "Remote Desktop Settings" dialog from the full screen version of Full Screen mode, you have to exit Full Screen mode to get the "Settings" button to appear again.

|| Screenshot |
| - | - |
| Default view:<br>("Settings" button present) | ![image](https://user-images.githubusercontent.com/1279475/180719756-7a19cd79-0d98-4cff-b99e-8b4f567402fb.png)
Click (w/o Shift) Full Screen:<br>("Settings" button still present) | ![image](https://user-images.githubusercontent.com/1279475/180720736-069b94ff-d3a2-452b-9709-bc49b1f72b0e.png)
Shift+Click Full Screen: <br>("Settings" button is missing) | ![image](https://user-images.githubusercontent.com/1279475/180720598-5e07a239-bea1-456a-b7a3-4b5c8cb576c4.png) |

Please make the "Settings" button visible in the full screen version of Full Screen mode.

This has been a long-standing issue that I've just been too lazy to report till now because I could work around it in my own personal use, but I'm beginning to have actual end-users using a MeshCentral instance I administer, and this has already caused confusion for them.

I'm on MeshCentral v1.0.60 at the moment.

**Comment by Ylianst** [comment]
You are right, working on this now.

**Comment by Ylianst** [comment]
Fixed, will be in v1.0.61.

**Comment by MailYouLater** [comment]
Much better.  Thank you.  🎉
