### ISSUE TITLE
If LDAP Userkey is set to "uid" no new accounts can login / be created 

### ISSUE THREAD

**Issue by hiimmazl** [Ylianst/MeshCentral#4328]
### Describe the bug

```json
 "domains": {
    "": {
      "newAccounts": true,
      "userNameIsEmail": true,
      "ssh": true,
      "auth": "ldap",
      "ldapUserName": "displayName",
      "newAccountsRights": [ "nonewgroups", "notools" ],
      "ldapUserKey": "uid",
      "ldapOptions": {
        "url": "XXX",
        "bindDN": "XXX",
        "bindCredentials": "XXX",
        "searchBase": "DC=XXX,DC=XXX",
        "searchFilter": "(&(mail={{username}})(memberOf:1.2.840.113556.1.4.1941:=CN=XXX,OU=XXX,OU=XXX,DC=XXX,DC=XXX))"
      },
```

### Steps to reproduce the behavior:

As 10 Users were created in the system, new users are not able to login anymore and no new accounts will be created for them. As I change the ldapUserKey to "objectSID" the login and account creation is working again, but all old users have their old permissions and everything reset.

### Server Software (please complete the following information):

OS: Windows Server 2019

Virtualization: Virtual Machine on Hyper-V

Version: [e.g. 1.0.54]

Database: MongoDB

**Comment by Ylianst** [comment]
FYI. I have a upcoming YouTube video on setting up MeshCentral with LDAP that should help.
