### ISSUE TITLE
action=login / action=tokenlogin

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#4329]
I've tryed to log'in with OTP enabled. and, it don't work ... I spend hours trying to correct my mistake. finally, I look in "meshcentral.db" and the last column (the one named "otpsecret") of my {"type":"user"} to compare with the secret in "google authenticator" (my phone is rooted, so I'm god there !). and the secret in my phone isn't even base32 !!! mistake found !!! but, when the system ask the OTP code while setup'ing, it work. you should stock it wrong'ly

**Comment by Ylianst** [comment]
I am not sure I understand this. It does not really matter in what format MeshCentral stores the OTP password, as long as it generates the correct 6 digit codes. Are you saying that the codes work but you still want MeshCentral storing the secret in Base32? Or are you saying that the 6 digit codes don't work for you?

Not that most people who have issues with Google Authentication and OTP codes is dues to their server not being set to the correct UTC time. Make sure your server has as accurate a clock as possible.

**Comment by Nothing2Do** [comment]
you stock it like it fit you but, when you pass it to google authenticator (with a QR code), you should pass it base32 encoded : https://github.com/google/google-authenticator/wiki/Key-Uri-Format .
As a result, my authenticator use a different value as secret than the one stored in the server (even if it's his QRcode). So, it can't work ...

I've spend hour trying to set my time accordingly (ntp and stuff) to try to resolve my problem !

**Comment by Ylianst** [comment]
oh!! ok. I am traveling now, but I will check this again.

**Comment by Nothing2Do** [comment]
it work correctly if i'm back to the "stable" version. So, I can wait !

**Comment by Nothing2Do** [comment]
it work correctly if i'm back to the "stable" version. So, I can wait !

**Comment by Nothing2Do** [comment]
in "stable", i look into "meshcentral.db", "my" line ("type":"user") and there is no more "otpsecret" : perhaps the bug come from here, I try to help ...

**Comment by Ylianst** [comment]
Ok, looking into this one now.

**Comment by Ylianst** [comment]
I can't replicate this issue. When MeshCentral gives you the OTP secret, it is indeed Base32 encoded, you see it here:

![image](https://user-images.githubusercontent.com/1319013/181627428-e076a38e-db7d-49dc-a6a5-5a3cf90d5334.png)

This is the same value that is stored in "otpsecret":

```
"otpsecret":"I5EGY6RZKYVTK42CKBYGGRKFJIZHEYTD"
```

If you are using NeDB and looking at MeshCentral.db, NeDB will just append updated records, so you need to look at the last record for your user in the file. If you add/remove OTP many times, you will get many identical records and every 24h, MeshCentral will tell NeDB to "compact" the file and just keep the up-to-date records.

So add Google Authenticator and look at the bottom of the meshcentral.db file to find "otpsecret".

I can't replicate your issue and Google Authenticator works correctly for me. I would check that your server UTC time is correct.

**Comment by Nothing2Do** [comment]
I've dive deeper into "google authenticator", and the "shared secret" is now encrypted. I can't read it anymore, even with my phone rooted... I've made a mistake. Sorry for that. 
But I've a site with OTP enabled (on a server, elsewhere) and it work correctly. so, it can't be my UTC time !

**Comment by Nothing2Do** [comment]
issue resolved ... I've use the shell to upgrade ("npm install meshcentral@1.0.62") and it works, it should be somewhere in the update process.

**Comment by Nothing2Do** [comment]
the last post was a mistake, i've forget to re-launch MC ...
I've searched a lot and, after a lot of "npm install meshcentral@?.?.?". my problem happen between 1.0.52 and 1.0.53 (perhaps it help you find the reason it's non working). Before 1.0.53, OTP ,hardware key, push and mail work correctly.

**Comment by Nothing2Do** [comment]
Can you help me by learning howto debug "my" problem ? I've followed this ("https://ylianst.github.io/MeshCentral/meshcentral/debugging/") to debug, But nothing out of the ordinary in my debug path ("meshErrorLogPath": "/meshcentral/meshcentral-logs/",). there are "auth.log", "mesherror.txt" and "stderr.txt" .

**Comment by Nothing2Do** [comment]
this is in my log, with v1.0.63
11:42:03 AM - web: checkUserOneTimePassword()
11:42:03 AM - web: checkUserOneTimePassword: fail (2).
11:42:03 AM - web: handleLoginRequest: 2FA token required
and, with v1.0.0
11:55:34 AM - web: checkUserOneTimePassword()
11:55:34 AM - web: checkUserOneTimePassword: success (hardware).
11:55:34 AM - web: handleLoginRequest: successful 2FA login
How can I get more info ?

**Comment by Nothing2Do** [comment]
I've given up ... reinstall from scratch and restore the sav file (apparently, database was corrupted). all is good now !

**Comment by Ylianst** [comment]
If you use MeshCentral in production, I recommend using MongoDB or another enterprise class database. The built-in NeDB is not great. I also recently added SQLite support in MeshCentral and may, down the road, switch the default database to SQLite.
