### ISSUE TITLE
Feature request: Ability to disable colors

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#433]
Hi Ylian,

Would be nice to have a feature to set the remote sessions black'n white only to run smoother on slow connections (Something like logmein has), i personally think this would improve the remote session speed by quite a bit if you're looking to fix something fast without a pretty picture.

See e.g. below

PS: I am aware you'll be on holiday, have a great time!

![image](https://user-images.githubusercontent.com/16573983/63171441-7dec1600-c033-11e9-874b-9d1d42b21ad3.png)

**Comment by MailYouLater** [comment]
It might also be nice to have other degraded color schemes as well, e.g. 256 color.

**Comment by Ylianst** [comment]
This is a good ask. As you probably already know, in "Settings..." you can change the JPEG quality and the scaling factor. Because we encode in JPEG, I don't expect removing color information to make a huge difference, but I think it's certainly something we can offer.

**Comment by MailYouLater** [comment]
If you find that it doesn't make a notable difference then other degraded color schemes might not be worth it, but the original request for greyscale would still be nice.

Thanks Ylianst.

**Comment by dinger1986** [comment]
this hasnt been added and doubt it will be @si458

**Comment by si458** [comment]
im going to close this, as this would require a backend change in the meshagent which is a big job!
so sadly wont be added
