### ISSUE TITLE
Numlock on remote

### ISSUE THREAD

**Issue by TXBorn1911** [Ylianst/MeshCentral#4332]
Currently when remoting into a desktop while using a laptop without a numeric keypad, the clients numlock will go off. This is most likely expected behavior as I have experienced it with other solutions. Is it possible to stop this behavior as it causes issues when they try to login and such while I am connected.

**Comment by si458** [comment]
ive just checked this, 
if the remote device has NUM LOCK ON, and ur local device has no num lock (small 13" laptop say like mine)
the remote device still has NUM LOCK ON while u are remotely controlling it!
