### ISSUE TITLE
Web Page Timeout with CrowdSec Integration

### ISSUE THREAD

**Issue by Dryskol19** [Ylianst/MeshCentral#4334]
I recently followed the guide for configuring the crowdsec integration on YouTube. Running MeshCentral on a Windows 10 Professional PC. Other than image customization and Let's Encrypt pretty standard setup, no proxy. I installed the CrowdSec windows client. Tested their express Windows Firewall Bouncer and confirmed that works. Attempting to install the bouncer for MeshCentral and place the settings into the config.json. Restart Mesh Central service and the page returns took too long to respond. If I remove the crowdsec config all is well. Just confirming I didn't mistype or misconfigure something. Image attached showing bouncer not active post add and crowdsec config in json.
![Config](https://user-images.githubusercontent.com/103533456/181590662-9204e2a1-0729-4299-8cc5-2c8435bba39a.JPG)

**Comment by Ylianst** [comment]
Your configuration looks ok (you could fixed the indentation a bit, but that does not matter). Something like:

```
"crowdsec": {
    "url": "http://localhost:8080",
    "apikey": "xxxxxxxxxxxxxx",
    "fallbackremediation": "bypass"
}
```

One thing I would check, open a browser and go to "http://localhost:8080" and check if you are really getting an empty web page. If CrowdSec is not running on that port, that would be a problem. When I go to 8080, I get this:

![image](https://user-images.githubusercontent.com/1319013/181594388-56d0d31e-06c3-4ba9-bb2f-e27175761f32.png)

One more thing you can do it type `cscli config show`, I get this:

![image](https://user-images.githubusercontent.com/1319013/181594652-ff94161d-8050-42d6-a313-df5834f463cd.png)

You can see the `Listen URL`, check that it correct.

**Comment by Dryskol19** [comment]
Checked both. Fixed the indentation just for good measure. localhost gives me a blank page and my config reads exactly like yours. Same result. Very odd. I'm gonna omit CrowdSec for now to get back online but if I can offer any other data for research I can gladly do so
![Page Error](https://user-images.githubusercontent.com/103533456/181610341-6a0360fc-bc88-4854-aa34-c72e7b0e6ab9.JPG)
![Blank](https://user-images.githubusercontent.com/103533456/181610345-d3ac2ae5-d13b-4c92-863d-fa51fa2f8656.JPG)
![Output](https://user-images.githubusercontent.com/103533456/181610347-a87ed37b-f5f2-4014-b28c-73471ba7b9ba.JPG)
.

**Comment by Ylianst** [comment]
Instead of `localhost` try `127.0.0.1`. I mention this because `localhost` may resolve to `::1` which is the IPv6 loopback address. CrowdSec is clearly only listening on IPv4 loopback.

**Comment by Dryskol19** [comment]
Implemented and restarted, same result unfortunately. I've attached a blocked out full config.json for reference. I have IvP6 disabled on my nic (I have no need at the moment)
![Config Update](https://user-images.githubusercontent.com/103533456/181616499-3bba49df-7cac-4734-ac48-088a730f4f98.JPG)
.

**Comment by Ylianst** [comment]
Oh, your config.json is not valid. Launching MeshCentral with the config will cause it to fail to parse the config.json file. I have a video on [this topic here](https://www.youtube.com/watch?v=31mxfH4y1SY). You can run your config.json in a JSON parser like [this one from DuckDuckGo](https://duckduckgo.com/?t=ffab&q=json+lint&ia=answer).

Your missing a comma after the "webPageLengthRandomization" line. The DuckDuckGo parser will also clean up your indentation.

**Comment by Dryskol19** [comment]
Stellar content and advice as always. Cleaned up and validated my .json. Then MeshCentral service failed to start. Ended up copying data folder, uninstall and reinstall. Placed everything back to include new CrowdSec verbage and all is in place and running. Thank you much for all you do!
