### ISSUE TITLE
Web relay not working

### ISSUE THREAD

**Issue by MDanihy** [Ylianst/MeshCentral#4335]
Config file below, I used the same port as in the tutorial, I have the same port forwarded through my router to the MeshCentral server.  HTTP and HTTPs options do not show for any of my devices.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "relayPort": 453
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by Ylianst** [comment]
The configuration file looks good. When you click on "HTTP" or "HTTPS" it will probably open a new tab. What do you see in the new tab? Do you see a blank page? It's loading? or see `not found`? Thanks.

**Comment by MDanihy** [comment]
HTTP and HTTPs do not even show.



On Jul 28, 2022, at 4:49 PM, Ylian Saint-Hilaire ***@***.******@***.***>> wrote:



The configuration file looks good. When you click on "HTTP" or "HTTPS" it will probably open a new tab. What do you see in the new tab? Do you see a blank page? It's loading? or see not found? Thanks.

**Comment by MDanihy** [comment]
In that area, this is the only thing that shows.
Interfaces MeshCmd SSH SCP Web-VNC Web-RDP

**Comment by Ylianst** [comment]
Oh, sorry. Your right, I did not read your issue correctly. Looking into this now.

**Comment by MDanihy** [comment]
I am running version 1.0.36 if that helps, I can go to the latest and see if that helps.

**Comment by Ylianst** [comment]
I was just about to ask what version you are running. Looking at my Twiiter account, "web relay" was added [starting with v1.0.42](https://twitter.com/MeshCentral/status/1541956160810385409), but many fixes have been made since. So, not seeing "HTTP" and "HTTPS" is expected on your version.

**Comment by MDanihy** [comment]
I upgraded to the latest and it still doesn't show, I would think just having that relayPort option would cause it to show.

**Comment by Ylianst** [comment]
I am going to test with your exact config.json, let me check what I see.

**Comment by Ylianst** [comment]
I am seeing it on my version. Can you type "info" in the server console and confirm you have the correct version?

![image](https://user-images.githubusercontent.com/1319013/181638095-9a46615b-eba9-49b4-b201-0d19d9b49838.png)

**Comment by MDanihy** [comment]
{
    "meshVersion": "v1.0.36",
    "nodeVersion": "v10.24.0",
    "runMode": "Hybrid (LAN + WAN) mode",
    "productionMode": true,
    "database": "NeDB",
    "platform": "linux",
    "arch": "arm",
    "pid": 624,
    "uptime": 177.314,
    "cpuUsage": {
        "user": 24400181,
        "system": 1305526
    },
    "memoryUsage": {
        "rss": 142180352,
        "heapTotal": 45830144,
        "heapUsed": 41686364,
        "external": 31445471
    },
    "warnings": [],
    "allDevGroupManagers": []
}

**Comment by MDanihy** [comment]
Wow, it never upgraded

**Comment by MDanihy** [comment]
OK, new issue then.  It isn't upgrading, I'll have to look into that now.  Thanks for the assist.
