### ISSUE TITLE
upgraded to 0.4.0-b , lost the web GUI

### ISSUE THREAD

**Issue by mschubeck** [Ylianst/MeshCentral#434]
I just upgraded from 0.3.6-r on Windows Server to 0.4.0-b to fix Let's Encrypt and I get nothing in the web console now.  Is anyone else seeing a problem on this version?

**Comment by MailYouLater** [comment]
What do you mean when you say "the web console"?
Do you mean [the server console](https://user-images.githubusercontent.com/1279475/63188037-3bb3dc00-c015-11e9-9d2f-9da55e46a7ff.png)? or [the agent console](https://user-images.githubusercontent.com/1279475/63188212-a533ea80-c015-11e9-97ca-72b36d8d6bcf.png)? or [the terminal](https://user-images.githubusercontent.com/1279475/63188671-d06b0980-c016-11e9-9cd8-2c19eea2170e.png)? or something else?

**Comment by mschubeck** [comment]
Sorry, none of the above. It's just 404 errors when navigating to the entire website that allows access to the server. When navigating directly to http://server I get nothing, however when I navigate directly using SSL to https://server the FAVICON loads but nothing else.

I already rolled the server back to the previous version, but I can test again on Monday. I stayed on 0.3.6-r for so long because the agents were stable on that version, even though there were other bugs I didn't report - 1) Let's Encrypt stopped updating, and 2) when using remote desktop, and the remote computer is using the Edge browser for something, you cannot type into the remote Edge browser.

This was the first chance I had to do an upgrade to see if those bugs were fixed before I submitted any bug reports, but then the update must not have completed properly (although it said it did). Just to be safe, I downloaded the newest 2.0 installer from meshcentral.com and used that for the updating. I didn't have much time to troubleshoot the 0.4.0-b installation so I was forced to rollback to the last working version.

Even though I couldn't connect to the server via web GUI, I did notice that the remote agents updated to the newest version because I saw them all go back to the previous version when I rolled the server back to 0.3.6-r.  Sorry for my brevity and bad explanations, I'm in the middle of multiple time-sensitive projects at the moment.  I'll try to explain better on Monday if you don't understand what I mean about the various things I mentioned.

**Comment by Ylianst** [comment]
Ok. The new 404 page is clearly causing problems for a lot of people. Edit /node_modules/meshcentral/webserver.js and remove the 5 following lines and restart the server. That should fix it.

// Handle 404 error
obj.app.use(function (req, res, next) {
var domain = getDomain(req);
res.status(404).render(obj.path.join(obj.parent.webViewsPath, isMobileBrowser(req) ? 'error404-mobile' : 'error404'), { title: domain.title, title2: domain.title2 });
})

**Comment by mschubeck** [comment]
No dice, I did the update again and then removed those lines (near the bottom of webserver.js) and still nothing.
![image](https://user-images.githubusercontent.com/48728727/63266985-1e724e00-c25f-11e9-89f9-05b6f4d48b1b.png)
This is on the server itself.

**Comment by mschubeck** [comment]
Ok, the problem seems to be that only the following folders are created during both a fresh install and an upgrade to 0.4.0-b:
![image](https://user-images.githubusercontent.com/48728727/63269360-0cdf7500-c264-11e9-827d-d25dd870a818.png)
When I copy the other folders from a previous version into the node_modules folder, the web GUI is restored.  Therefore, my problem is that the web server was missing the needed files to run.  However, the larger version is that the installer(?) isn't updating or installing all necessary files/folders.

I'm going to give this a few days and see if Let's Encrypt is fixed and if the Edge browser/typing issue is fixed, and if not I'll open new bug reports for those.  I'm down to 10 days on my LE cert, so I may have to manually renew it and worry about the module later.

**Comment by mschubeck** [comment]
Missing folders:
![image](https://user-images.githubusercontent.com/48728727/63270163-9e031b80-c265-11e9-8ffd-d5ed999d5380.png)

**Comment by jsastriawan** [comment]
Try removing package-lock.json, backup node_modules and remove and then manually call npm install meshcentral. It should pull the latest dependencies.

**Comment by Ylianst** [comment]
This is a good suggestion, you can always backup your "node_modules" folder before doing an update and put it back if needed. I sometimes rename it to something else like "node_modules_old" and do a fresh "npm install meshcentral".

For current v0.4.0-b, when I do "npm install meshcentral" I get 142 folders in "node_modules". Once you start MeshCentral, the server will install additional modules based on what your server needs (MongoDB, Windows-nodes...). So you should end up with a bunch more.

If you run MeshCentral with reduced rights under Windows, the server will not be able to install the additional packages. So you will need to run MeshCentral manually once to get these installed and then run again with reduced privileges. Let us know if this is your situation,

Lastly, you can look in "meshcentral-data/mesherrors.txt" for any server errors. If you see some, you can post them here. I also recommend to run the server manually using "node node_modules/meshcentral" to see what is going on. If you run as a Windows Server or SystemD, you don't get as much visibility into server startup issues.

Hope it helps,
Ylian (who is still on vacation)
