### ISSUE TITLE
UAC Popup Screen

### ISSUE THREAD

**Issue by danielmourademelo** [Ylianst/MeshCentral#4341]
Screen goes black when UAC appears to put admin permissions
This error occurs when the user runs the meshgent interactively.

My suggestion is to put on the desktop tab of the meshcentral server a login button as admin then the meshgent on the user's computer will close and open in admin elevation.

**Comment by JSuenram** [comment]
Duplicate. Issue is already known...
https://github.com/Ylianst/MeshCentral/issues/1616
https://github.com/Ylianst/MeshCentral/issues/1885
https://github.com/Ylianst/MeshCentral/issues/2196
https://github.com/Ylianst/MeshCentral/issues/2677

**Comment by si458** [comment]
duplicate closing
