### ISSUE TITLE
Feature Request: Web relay links for mobile site.

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#4342]
Have been using the new web relay feature for a little while now and it's been awesome not needing the MeshCentral Router for HTTP/HTTPS. Very useful feature.

However, today I was browsing on my phone and noticed the web links do not appear for the mobile site. This makes some sense, since MeshCentral Router links are useless on mobile and share the same placement... but web relay links should work just fine. Any chance we can get them added to the mobile site?

**Comment by Ylianst** [comment]
Working on this now!

**Comment by Ylianst** [comment]
Just added it, will be in MeshCentral v1.0.61. I will probably publish it later today.

![MC2-MobileSite-WebRelay](https://user-images.githubusercontent.com/1319013/181826021-b10f3372-87bc-4f4c-b241-b95cdcc381d8.png)

**Comment by MatinatorX** [comment]
Awesome, thanks Ylianst! Will test and close this issue as soon as v1.0.61 is published.

**Comment by Ylianst** [comment]
Thanks. You can close once you tested the new feature and it works ok.

**Comment by MatinatorX** [comment]
Just updated and tested, works perfectly. Thanks again!

**Comment by silversword411** [comment]
This needs more fleshing out, but a start
https://github.com/Ylianst/MeshCentral/commit/9d1773630448177ee1db2a04b1bea15b46e3300f
