### ISSUE TITLE
Unable to double click on mobile version in browser

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4344]
**Describe the bug**
I can't seem to double click a folder to go into it when using meshcentral on my mobile device

**To Reproduce**
1. Open meshcentral in a browser on mobile phone
2. Connect to a remote computer
3. Try double taping a folder

**Expected behavior**
Double clicks to work

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] hybrid, traefik reverse proxy, ssl offload 
 - Version: [e.g. 1.0.43] 1.0.61
 - Node: [e.g. 18.4.0] 16.16.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Samsung galaxy Z Fold 3
 - OS: [e.g. Ubuntu] android 12
 - Network: [e.g. Local to Meshcentral, Remote over WAN] Remote over wan
 - Browser: [e.g. Google Chrome] Firefox 103.1.0
 - MeshCentralRouter Version: [if applicable] n/a

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] computer
 - OS: [e.g. Windows 10 21H2] Windows 10 21h2 32bit
 - Network: [e.g. Local to Meshcentral, Remote over WAN] Remote over wan
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Current Core: Apr 4 2022, 117752849

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by PathfinderNetworks** [comment]
I don't think it is possible to perform a double-click on mobile devices.  Typically it is done using a long-press action.  In my case, for Mesh, I just set the mouse action to right-click on tap then click on the folder. That opens the context menu on the remote side. Then I switch the mouse action back to left-click and then click on the Open option.  
The other option is maybe a double-click action could be added to the mouse actions selection?  But a long-press would be the best (in my mind) if possible.

**Comment by si458** [comment]
closing in favour of other issues https://github.com/Ylianst/MeshCentral/issues/5295
https://github.com/Ylianst/MeshCentral/issues/3816
https://github.com/Ylianst/MeshCentral/issues/3146
