### ISSUE TITLE
Add 2 step login is not an option

### ISSUE THREAD

**Issue by reidjr** [Ylianst/MeshCentral#435]
I am running meshcentral latest npm on a raspberry Pi

Under the account section I have :

```
Account security

Manage authenticator app
Manage security keys
```
but not Add or delete 2 step login. 
Selecting "Manage authenticator app" opens a window, that remains forever on " loading...."
What am I missing ?

**Comment by Ylianst** [comment]
If it says "Loading..." and gets stuck, it's a bug. What version of nodejs are you running? (type "node -v" to check). I am on vacation until Wednesday, but will take a look at it.

Also, if you go in "My Server" tab, there is a option to look at the server error log, click there are report any errors if present.

**Comment by reidjr** [comment]
Enjoy your vacation, this is not urgent :-)
node -v :  v8.16.0
And 
"Server has no error log"
? Permissions problem ?

**Comment by reidjr** [comment]
Ok, after installing the windows version of meshcentral on a test machine to see if it had the same "bug" and playing with it, I found the bug ( or perhaps user error). 

So back on my raspberry pi 

Having meshcentral set up with in LAN Only mode, and no FQDN, then the authenticator options are not displayed.
Having meshcentral set up in LAN Only mode, with a  FQDN, then the authenticator options are displayed, but hang at "Loading........"
Having meshcentral set up in Hybrid mode ( I assume that is default when neither WAN only or LAN only is included in config.json), and a FQDN, then the authenticator options are displayed, and seem to work as expected. ( however I have never seen the options to ADD or Remove 2 factor authentication)

My use case is Meshcentral server on a LAN with all the Target machines running meshagents or hardware KVM AMT servers on the same LAN. So I thought LAN only mode appropriate. 
The meshcentral server is usually accessed over the internet from a remote browser client. So the server to Agent is LAN only but the server has a FQDN and named certificates.

So I dont know if this is a bug, or just an edge/user error use case that needs a " this only works in Hybrid/WAN mode" comment.
Apreciate all your hard work on this awsome software.

**Comment by Ylianst** [comment]
Thank you for the report. I will get this fixed when back from vacation. 2 factor authentication does need an FQDN set on the server. If not, these options should not show up. It seems I need to fix a few issues here because if the FQDN is set, even if in LAN mode, 2 factor auth should still show up and work.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.0-f with a fix for 2FA in LAN mode. Let me know if it fixes it for you.

**Comment by reidjr** [comment]
Tested with v0.4.0-g works for me. 

Thank you.


[A neat feature comes to mind, totally unnecessary :-)  is 2FA for WAN login but straight in on the LAN. On the LAN you have theoretically  physical security, its the WAN you really need  2FA for]

**Comment by Ylianst** [comment]
The idea of using a USB key for direct login is not crazy at all, in fact it's a usage of FIDO2. Typically you would use your FIDO2 key + a PIN since you want proof of possession + proof of knowledge. I will close this issue, but certainly something I may explore down the road.

**Comment by time1234** [comment]
These information is really helpful.
