### ISSUE TITLE
RDP disconnect after some seconds from login

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#4352]
**Describe the bug**
Wen connecting using Web-RDP function: UI is shown, login completes and afert some seconds it disconnects.

**To Reproduce**
Simply connect to a remote or local server using web-rdp. I've tried many managed servers and the behavior is the same after the last update of meshcentral 1.0.62

**Expected behavior**
I expect the connection to be stable online so that I can operate on the server, like it was before I had ver. 1.0.58, if I remember coorectly)

**Screenshots**
Not applicable

**Server Software (please complete the following information):**
 - OS: Windows Server 2012
 - Virtualization: Hyper-V
 - Network: LAN
 - Version: 1.0.62
 - Node: 16.15.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 (updated)
 - Network: local to meshcentral
 - Browser: Google Chrome ver. 103.0.5060.134 64bit
 - MeshCentralRouter Version: not involved

**Remote Device (please complete the following information):**
 - Device: Server
 - OS: Windows Server 2016 or newer
 - Network: remote
 - Current Core Version (if known): Mar 25 2022, 1659876711

**Additional context**
 No more to say

**Your config.json file**
```
{
	"settings": {
		"Cert": "CENSURED",
		"Port": CENSURED (non standard),
		"RedirPort": 81,
		"_minify": true
	},
	"smtp": {
		"host": "CENSURED",
		"port": 25,
		"from": "CENSURED",
		"tls": false,
		"tlscertcheck": false,
		"tlsstrict": false
	},
	"domains": {
		"": {
			"assistantCustomization": {
				"title": "CENSURED",
				"image": "CENSURED",
				"filename": "CENSURED"
			}
		}
	}
}
```

**Comment by si458** [comment]
I've noticed this same behaviour thinking about it? Since updating to
1.0.60 actually?

**Comment by energywave** [comment]
I cannot say from wich version exactly as I'm coming from 1.0.58, if I remember correctly. So that could be any version in between. But this is seriously impacting accessing remote servers :(

**Comment by dxdemetriou** [comment]
Confirmed. Tried to go back in 1.0.48, still happens when there is no screen update. For example, I have a cmd in "dir /w/a/s" evcerything is ok (except of the lag), and when I stopped it then disconnects in some seconds.

**Comment by robclay** [comment]
Same thing happening here.  This happened for me after updating to 1.0.61 over the weekend, and 1.062 today hoping that was the fix!

**Comment by Ylianst** [comment]
Oh! I am seeing the same problem! Working on this now. I will release a fix for this ASAP once I get to the bottom of this.

**Comment by dxdemetriou** [comment]
> Confirmed. Tried to go back in 1.0.48, still happens when there is no screen update. For example, I have a cmd in "dir /w/a/s" evcerything is ok (except of the lag), and when I stopped it then disconnects in some seconds.

edit: I'm not sure about versions, I forgot the service restart. On previous versions I cannot get the RDP connection at all which I remember that it worked before, like as the Microsoft's antivirus or some update is preventing it.

**Comment by Ylianst** [comment]
Ok, the problem is Bryan [commit here](https://github.com/Ylianst/MeshCentral/commit/f628c57eea0178ba5b2b50a3146493797c3b0b8d). I am reversing it and publishing a new version now!! Thank you for reporting this.

**Comment by energywave** [comment]
Thank YOU for having fixed this so fast!!! You're my personal hero...

**Comment by energywave** [comment]
Ok, just updated to 1.0.63 and I confirm the issue is now fixed. Closing the issue, good work (as always) Ylian!

**Comment by Ylianst** [comment]
MeshCentral v1.0.63 is out with a fix for this.

**Comment by Ylianst** [comment]
Oh wow, you are SO FAST!

**Comment by robclay** [comment]
Working! Thanks!!
