### ISSUE TITLE
meshcentral not pushed to dockerhub

### ISSUE THREAD

**Issue by herwig-** [Ylianst/MeshCentral#4353]
**The docker-image is not visible on dockerhub**
First of all, Thx for your great Work!

I use MeshCentral with a docker-compose file. However I cannot find the official (your) version on dockerhub. I can see that your workflow `https://github.com/Ylianst/MeshCentral/blob/master/.github/workflows/docker.yml` is here and that the action is successfully executed, however I cannot see the docker-image or the user `ylianst` on dockerhub.

Based on your last Action, your lasest image should be less than a day old 
![grafik](https://user-images.githubusercontent.com/741471/182260347-795414ea-6945-4b82-b260-5e7c23ea52f3.png)

If I search on dockerhub, the newest I find is not from you ...
![grafik](https://user-images.githubusercontent.com/741471/182260388-79dc64d0-4aa1-422b-9d5c-ac8ec58cbd99.png)

Is there a problem with the authentication or is this image private? -> is it on purpose that the image is not public?

thx

**Comment by si458** [comment]
Currently we only publish the docker builds to github at the moment

This is due to the docker hub requirements (monthly updates and pulls otherwise u lose the package) and rate limits for free customers where as github has none at all

https://github.com/Ylianst/MeshCentral/pkgs/container/meshcentral

I hope this helps!

**Comment by herwig-** [comment]
this is perfectly fine.
May I suggest, that you add a comment to the sample docker-compose files in `https://github.com/Ylianst/MeshCentral/tree/master/docker`

two lines like:
```

...
    image: meshcentral
    #to use the official docker-image on github, uncomment the following line instead of the above
    #image: ghcr.io/ylianst/meshcentral:latest
...
```

afterwards, I think this issue can be closed.

again thx for your great work all together!

**Comment by si458** [comment]
Great idea! Send a pr and @Ylianst will merge it

**Comment by herwig-** [comment]
done, #4354

**Comment by si458** [comment]
brilliant thanks @herwig- ! it helps others out :)
