### ISSUE TITLE
Can't reveal windows taskbar when set to autohide

### ISSUE THREAD

**Issue by omriasta** [Ylianst/MeshCentral#4356]
**Describe the bug**
When a windows client computer has the taskbar set to autohide, usually hovering the mouse at the bottom of the screen will reveal the taskbar however this does not work when remote controlling from meshcentral. Placing the mouse cursor at the bottom of the screen does not cause the taskbar to appear. At this time as a workaround, I am "sending" the windows key to reveal the taskbar.
**To Reproduce**
1. Go to remote control a windows desktop that has taskbar set to autohide
2. Click on the bottom of the screen to try and cause the taskbar to pop up

**Expected behavior**
Placing the cursor at the bottom of the screen of the client computer should cause the taskbar to appear
**Screenshots**
See attached screenshot with the setting to autohide taskbar as well as the cursor at the bottom of the screen which doesn't cause the taskbar to appear.
![Screenshot from 2022-08-02 09-08-00](https://user-images.githubusercontent.com/11823048/182383281-03fff177-c83f-4018-a4f3-b1aa91e17a5e.png)

**Server Software (please complete the following information):**
 - OS: Amazon Linux 2
 - Virtualization: [e.g. Docker]
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.0.43] 1.0.60
 - Node: [e.g. 18.4.0] 16.16.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome] Google Chrome
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop and Tablet
 - OS: [e.g. Windows 10 21H2] Windows 10 as well as Windows 11
 - Network: [e.g. Local to Meshcentral, Remote over WAN] Remote over WAN
 - Current Core Version (if known):Current Core: Mar 25 2022, 1851657594

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by silversword411** [comment]
I'm not sure this is a mesh problem. 

Windows uses speed as well as location to "show" a hidden taskbar. So with the "right" mouse moving you can get it to show...it's just tricky because mesh is usually in a browser (have you tried full-screen <F11>) mode?

Really, you're hiding the taskbar because your remote resolution is low. Increase it, make your life easier.

I guess you could run a script that would adjust the reg key that does hide/show on mesh connecting...but really?

**Comment by omriasta** [comment]
It's actually set by the user, not me because they use certain software that displays at full screen and the taskbar hides certain buttons..... it's odd as this works fine with teamviewer and other remote software...just meshcentral doesn't seem to pick up on this...

**Comment by si458** [comment]
ive just tried this myself with 1.0.63 and i have no issues?
task bar shown, then into setting and hide it,
mouse over the bottom and it gets shown?

**Comment by si458** [comment]
found a work around for you to try - help from this link
https://winbuzzer.com/2021/03/19/how-to-hide-or-unhide-the-taskbar-in-windows-10-auto-hide-xcxwbt/

1. open up a `User Shell` in terminal (terminal tab then right click connect)
2. RUN TO TURN OFF AUTO-HIDE
`powershell -command "&{$p='HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3';$v=(Get-ItemProperty -Path $p).Settings;$v[8]=2;&Set-ItemProperty -Path $p -Name Settings -Value $v;&Stop-Process -f -ProcessName explorer}"`
3. connect to computer and use with taskbar visible
4. once finished go back to terminal tab
5. RUN TO TURN ON AUTO-HIDE
`powershell -command "&{$p='HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3';$v=(Get-ItemProperty -Path $p).Settings;$v[8]=3;&Set-ItemProperty -Path $p -Name Settings -Value $v;&Stop-Process -f -ProcessName explorer}"`

**Comment by krayon007** [comment]
It would be interesting if I could add a configurable setting to set/reset autohide on connect/disconnect, if it was set.

**Comment by si458** [comment]
> It would be interesting if I could add a configurable setting to set/reset autohide on connect/disconnect, if it was set.

That would be amazing!

In theory u could use the powershell script above to enable/disable the task bar on the agent side
Then @Ylianst could add an option to enable/disable the taskbar in the ui

**Comment by omriasta** [comment]
Thanks everyone...seems like quite a few suggestions but I think I'll just stick with sending the Win key to get access to the taskbar..for me it just seems faster and easier unless this is irking some of the other people here.

**Comment by krayon007** [comment]
Sometimes I think it's an artifact of the viewport resolution and mouse rectangle. I actually have the same problem with VMware when running windowed. I'm not able to get the taskbar and/or rdp bar to unhide, and that's when I'm sitting at the physical host machine.

**Comment by silversword411** [comment]
> Win key

or <ctrl>+<esc> :)

**Comment by si458** [comment]
you can use the new `taskbar` commands in the console tab now
```
> taskbar
Proper usage: taskbar HIDE|SHOW [TSID]
> taskbar hide
Changing TaskBar AutoHide status. Please wait...
Current Status of TaskBar AutoHide: true
> taskbar show
Changing TaskBar AutoHide status. Please wait...
Current Status of TaskBar AutoHide: false
```
