### ISSUE TITLE
Colors in terminal when using SSH

### ISSUE THREAD

**Issue by poiNt3D** [Ylianst/MeshCentral#4357]
**Is your feature request related to a problem? Please describe.**
Right now colors in terminal work only when connected through MeshAgent

**Describe the solution you'd like**
Color support in the integrated SSH client

**Describe alternatives you've considered**
Maybe i'm doing something wrong? Can anyone confirm this problem? Thanks.

**Comment by Ylianst** [comment]
The SSH terminal does support color. The issue is going to be the terminal configuration of the shell. Try typing this:

```
ls -al --color /tmp
```

Screen of SSH with color:

![image](https://user-images.githubusercontent.com/1319013/182495785-7c0fb068-3697-48da-8e35-0ac8a9533346.png)
