### ISSUE TITLE
MEBX - activate network access - USB provisioning 

### ISSUE THREAD

**Issue by aRafeymasood** [Ylianst/MeshCentral#4359]
I am trying to actiavate AMT on a few hundred computers - keen to use ACM mode.
Had used setup.bin Manager to create a setup.bin file for our fleet - it does enable AMT and set the password.
However, in MeshCentral the devices show up as having - Intel ME: Unknown Version & State

![image](https://user-images.githubusercontent.com/47164919/182528853-4bc49066-8ad3-4190-b190-e07ee5f74ea3.png)

When I go back to the MEBX and enable "active network access" - all works fine - KVM and Intel AMT tab shows.

I had searched and could not find an option that will allow me to include it during provisioning using the setup.bin file so it activates network access.
Presently, have to setup MEBX settings individually on the computers.
By default the option is disabled in Dell and will be really useful if someone can assist please.

**Comment by Ylianst** [comment]
Hi. Are you using a device group with a MeshAgent? Or Intel AMT only (no MeshAgent)?

The setup.bin file of MeshCentral will not put Intel AMT into ACM, instead, it will set a trusted FQDN and trusted hash. Once set, the meshagent or `meshcmd amtconfig` should detect that Intel AMT has the trusted values and perform secure activation into ACM. This is more secure since MeshCentral performs the activation, not the USB key.

Let me know what you are using. Thanks.

**Comment by nandox5** [comment]
When i use the setup.bin i get a message about AMT already being provisioned and it fails. Even though the machine is not in a provisioned or active state... any ideas?

**Comment by nandox5** [comment]
Also, any solutions for wireless ACM method? our laptops don't have ethernet ports

**Comment by aRafeymasood** [comment]
Thanks Yilanst, I was able to follow your instruction and get it working.

I was using AMT only (no MeshAgent) - changed it to "Managed using a software agent" > used the setup.bin via USB. Installed the Agent and it activated in ACM :)
Just curious, as most of the computers are non-persistent machines (lab computers) > the agent does activate the ACM but after restart it gets removed - wondering if that might cause some issues in future? Can install agent as part of a Windows image so it stays installed.

**Comment by Ylianst** [comment]
"restart it gets removed" - as in the agent is no longer there? This could be an anti-virus thing. Check if the agent folder is still there. Is it's just the executable that is missing?
