### ISSUE TITLE
Windows Firewall Settings

### ISSUE THREAD

**Issue by desmodromisk** [Ylianst/MeshCentral#436]

**Comment by desmodromisk** [comment]
Meshcentral not working if Windows defender is activated !

**Comment by krayon007** [comment]
Are you referring to the server side of the agent side?

**Comment by desmodromisk** [comment]
Yes sorry from the server side.
I am not so technical but i can see that windows defender blocks all outgoing and incoming
traffic to the server. When disabled all works as a charm. Any advice on what to generate
rules for would be great from you pros.

**Comment by Ylianst** [comment]
If you need to open incoming ports in the Windows firewall, follow the instructions here: https://www.windowscentral.com/how-open-port-windows-firewall. When typing in the TCP port numbers, type "80, 443, 4433". That should open these 3 ports.

When back from vacation tomorrow, I will look at adding a firewall rule to the MeshCentral Windows Installer.

**Comment by Ylianst** [comment]
I just updated the [MeshCentral Windows Installer](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralInstaller-2.0.exe) and [MeshCentral Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf). The new installer will automatically add firewall rules on Windows and the new Install Guide is updated to show how to add/edit the rules. Hopefully this will close this issue.

![MC2-WinFirewall](https://user-images.githubusercontent.com/1319013/63613270-3b778b80-c595-11e9-882e-42a27e7393d2.png)
