### ISSUE TITLE
lets encrypt certificate can not be installed on Azure VM

### ISSUE THREAD

**Issue by joostrinkes01** [Ylianst/MeshCentral#4361]
Hello,

I have a azure windows VM running Mesh central. This is working fne. The system has a FQDN, and a public IP. Now i want to add a certificate.
I have updated the config.json as follow:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "fqdn-name",
    "port": 443,
     "redirPort": 80
      },
  "domains": {
    "": {
      "title": "MeshCentral",
      "title2": "Server1"    
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "email@gmail.com",
    "names": "fqdn-name",
	"skipChallengeVerification": false,
	"rsaKeySize": 3072,
    "production": false
  }
}
```

Ad i see if a do a leeveetns:
```
> le
{
    "configOk": true,
    "leDomains": [
        "mesh-dn-test.westeurope.cloudapp.azure.com"
    ],
    "challenges": {},
    "production": false,
    "webServer": true,
    "certPath": "C:\\Program Files\\Open Source\\MeshCentral\\meshcentral-data\\letsencrypt-certs",
    "skipChallengeVerification": false,
    "cert": "None"
}
> leevents
8/3/2022 1:04:52 PM - Getting certs from local store (Staging)
8/3/2022 1:04:52 PM - No certificate files found
8/3/2022 1:04:57 PM - Got no certificates, asking for one now.
8/3/2022 1:04:57 PM - Generating private key...
8/3/2022 1:04:57 PM - Setting up ACME client...
8/3/2022 1:04:57 PM - Creating certificate request...
8/3/2022 1:04:58 PM - Requesting certificate from Let's Encrypt...
8/3/2022 1:05:01 PM - Succesful response to challenge.
8/3/2022 1:05:02 PM - Succesful response to challenge.
8/3/2022 1:05:02 PM - Succesful response to challenge.
8/3/2022 1:05:02 PM - Succesful response to challenge.
8/3/2022 1:05:04 PM - Got certificate.
```

but then it stops.

Is tier something i do wrong?

thanks!

**Comment by Ylianst** [comment]
Hi. Everything looks ok and your configuration looks great. You should see these two files:

```
meshcentral-data/letsencrypt-certs/staging.crt
meshcentral-data/letsencrypt-certs/staging.key
```

Also, when you navigate to your server with a browser, you can click on the TLS padlock and it should show that your server is using a staging certificate. If that all looks good, change this line:

```
"production": true
```

Then, restart your server and you should get a real, trusted certificate within a minute or two.

Let me know if that works.

**Comment by joostrinkes01** [comment]
Hello Ylianst,

I have the 2 files in the directory. I am sing the latest version of MeshCentral. But if i click the padlock, i still see the self signed certificate. It does not look like it is processed. If i do a LE or LEcheck, i also see the self signed certificate.
I think the system should somehow apply the certificate, but it is not doing that.

Please let me know if their is anything i can do to clarify the issue, or to check someting.

thanks

**Comment by Ylianst** [comment]
I am looking in the code to see if I can find why it's not working for you. For reference, this is what my test server looks like:

![image](https://user-images.githubusercontent.com/1319013/182930940-66aceb78-af38-43d2-b2a8-be36cbe46053.png)

**Comment by Ylianst** [comment]
If I double click on the "staging.crt" file, I can see the staging certificate. In my case, it looks like this:

![image](https://user-images.githubusercontent.com/1319013/182931813-9513b9a9-1960-4aae-8131-663944472491.png)

**Comment by joostrinkes01** [comment]
![cert-staging](https://user-images.githubusercontent.com/110546967/183087654-4f18dafb-a106-4c35-a253-1912f00a617a.PNG)

**Comment by Ylianst** [comment]
It looks good. Can you make sure your server is set to the correct UTC time? I ask because if it's not set, MeshCentral with get the certificate and immediately think it's not valid and not use it.

Also, just to make sure, I would also add a right for read/write to "Everyone" for the `meshcentral-data\letsencrypt-certs` folder, just to make sure the server can read and overwrite the files in that folder.

**Comment by joostrinkes01** [comment]
So i changed the time setting to my region, i deleted all files from cert directory, gave the rights on that directory to everybody, restarted Mesh and all works fine! Thanks for the help.
