### ISSUE TITLE
Issue with Serverside Screen Recording

### ISSUE THREAD

**Issue by punacoder** [Ylianst/MeshCentral#4363]
Setup Serverside ScreenRecording in config.json file, but after processing a recording, I cannot review the recordings in "My User recordings".  When going to the tab I see a "loading" message (see attachment).
Currently using release 1.0.60 (Docker release)
Here is a snippet of my config.json file:
 ```
 "domains": {
	"": {
           "_title": "MyServer",
           "_title2": "Servername",
           "_minify": true,
           "mstsc": true,
           "NewAccounts": "false",
           "_userNameIsEmail": true,
           "certUrl": "https://10.50.10.123:443",
           "sessionRecording": {
               "_onlySelectedUsers": true,
               "_onlySelectedUserGroups": true,
               "onlySelectedDeviceGroups": true,
               "filepath": "/home/user1/meshcentral/meshcentral/meshcentral-recordings",
               "index": true,
               "maxRecordings": 50,
               "_maxRecordingDays": 15,
               "maxRecordingSizeMegabytes": 100,
               "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection, 200 = Messenger",
               "protocols": [ 1, 2, 101 ]
          } 
      }
  },
```
![2022-08-03 11_01_13-MeshCentral](https://user-images.githubusercontent.com/109180582/182712316-3648a68f-73b8-4d53-8c01-7126d572f915.png)

**Comment by Ylianst** [comment]
Interesting. Can you open the browser console and see if there are any errors?

On my test server, I see this:

![image](https://user-images.githubusercontent.com/1319013/182713950-0c1ebffe-28bf-4c44-abaa-d3239992ea32.png)

Hopefully there is an error in the browser console that will guide me to how to fix this.

**Comment by punacoder** [comment]
![image](https://user-images.githubusercontent.com/109180582/182715179-1b064404-d961-4566-bf88-a6caa5d60cd9.png)

Here you go!

**Comment by punacoder** [comment]
Yliant,
I changed the filepath to:  "/opt" and it worked.  There must be permission issues with that original path.  Are there any prerequisites for the folder specified?  Does it have specific ownership and write permissions?

**Comment by Ylianst** [comment]
Oh good. Glad you found it. I need to do something about that so it displays an error message indicating the problem.

Yes, for recordings, whatever account MeshCentral is running under needs read/write access to the recordings path. The default path is `meshcentral-recordings` just next to `meshcentral-data`, but maybe that did not have the right permissions.

**Comment by punacoder** [comment]
Thank you.

**Comment by Ylianst** [comment]
v1.0.64 will show a better error message.

![image](https://user-images.githubusercontent.com/1319013/182924697-be89098d-2572-4224-bea2-272bed52b17c.png)
