### ISSUE TITLE
Suddenly run command is not working

### ISSUE THREAD

**Issue by sufailDesk** [Ylianst/MeshCentral#4364]
Run commands (2): ipconfig
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: child_process.execFile(): Could not exec [C:\WINDOWS\system32\cmd.exe] in method 'handleServerCommand()'

**Comment by Ylianst** [comment]
I just tested like this and it worked for me:

![image](https://user-images.githubusercontent.com/1319013/182915282-4a0354be-56dc-40a0-97aa-1b5a8cdeb8e2.png)

**Comment by sufailDesk** [comment]
Yeah, It works. The issue was that I passed wrong 'runsAsUser', 2 instead of 0. 0 was perfect when testing agent and collector in the same machine. Thanks for quick reply.
