### ISSUE TITLE
relayDNS just produces a Not Found message

### ISSUE THREAD

**Issue by BillBardon** [Ylianst/MeshCentral#4366]
Created a device group with "No agent devices relayed thru agent", having a relay device that I know is on. Added a copier at its known IP address. 

When I click its HTTPS link, it redirects to my relayDNS domain, but just says "Not found."

Here is part of my config.json. It contains other settings, but these are all the ones related to relay and ports. No other port settings are enabled. (Ignore the last comma, there are more lines in the full config.)

```
  "settings": {
    "WANonly": true,
    "Minify": 1,
    "SessionTime": 720,
    "port": 443,
    "relayDNS": [ "tun0.ca-access.computassist.com","tun1.ca-access.computassist.com","tun2.ca-access.computassist.com","tun3.ca-acc
    "redirPort": 80,
    "exactPorts": "true",
  }

```

Here are my DNS records as queried from the MeshCentral server itself. Everything matches.

```
bill@access:~$ dig ca-access.computassist.com +short
167.99.123.56
bill@access:~$ dig tun0.ca-access.computassist.com +short
167.99.123.56
bill@access:~$ dig tun1.ca-access.computassist.com +short
167.99.123.56
bill@access:~$ dig tun2.ca-access.computassist.com +short
167.99.123.56
bill@access:~$ dig tun3.ca-access.computassist.com +short
167.99.123.56
```

**Comment by si458** [comment]
Can the agent you have selected ping the device by its ip address and browse to it and accessible on https://(ip) ?
Config looks ok, daft one too, you have defo restarted the server and does it show the relayed name on the startup logs?

**Comment by BillBardon** [comment]
Using the same relay PC, the same addresses in the RoutePlus plugin does work. I know, so what am I complaining about? Well, the new IoT groups on the main MeshCentral server page are just quicker and easier to use.

**Comment by Ylianst** [comment]
Unrelated to this, but do change this line:

```
"exactPorts": "true",
```

To this:

```
"exactPorts": true,
```

Since one is a string true and the other is really true.

**Comment by Ylianst** [comment]
Everything looks ok. The config.json is correct with the correct "RelayDNS". So, it should work.

Can you go in "My Server" / "Tracing" tab and enable tracing for "Cookie Encoder", "Web Server Requests" and "Web Socket Relay" and then this ok and hit "HTTP" or "HTTPS" link using a different browser tab. It should look like this:

![image](https://user-images.githubusercontent.com/1319013/182916429-caccb800-20a9-42df-8c5d-5896ae8f1962.png)

You can hit the "Clear" button before hitting the "HTTP" link just to get a clean trace. Take a screen shot and post it. Feel free to blank any private information.

Thanks.

**Comment by BillBardon** [comment]
I promise I changed nothing since posting the issue earlier, but I followed your steps, and it worked. So I decided to check all of my relayed devices. It worked for a few (I didn't keep track, but I'm going to guess 3) and then I started getting the Not found page.
I recall from your video that MC keeps the relay open for a while. I am probably just running out of relay domains?

![Screenshot_20220804_141721](https://user-images.githubusercontent.com/13840867/182936927-906a3096-bf95-468b-98fd-b9b39a128afc.png)

**Comment by Ylianst** [comment]
This is interesting you mention that. When I deployed relay DNS on my test server and I think on MeshCentral.com, it took a while to start to work. At first I figured something was really wrong, but after a few minutes it just worked. This is really odd and now that you are reporting it... I will keep looking into this.

**Comment by si458** [comment]
> This is interesting you mention that. When I deployed relay DNS on my test server and I think on MeshCentral.com, it took a while to start to work. At first I figured something was really wrong, but after a few minutes it just worked. This is really odd and now that you are reporting it... I will keep looking into this.

I have noticed recently this same similar issue to what you have described now that I think about?

When I click http the first time takes a long time to load the page but once it's loaded I then close it and open another http to the device again or a different device and suddenly it speeds up?

When I inspect my network request in the dev console in Firefox the tracing shows about 5-10 seconds of blocked time then 100ms of dns, network and requests,

I noticed this when loading my freepbx Web panel, it seems to site and wait on loading images or favicons before proceeding any further (this does sit on about 6-8 tcp requests the MC panel shows if that helps?)

**Comment by jsinoy** [comment]
I am having a similar issue . The one thing i noticed was after few seconds  of inactivity the web page will turned to "Not Found" . I have 5 relayDNS configured , and i am testing this issue to a single device.

**Comment by jsinoy** [comment]
Relay websocket closed ? 
![image](https://user-images.githubusercontent.com/109936671/199659830-13351730-e49a-49a7-a642-bbf091eb4534.png)

**Comment by si458** [comment]
closing as stale, but also this problem still persists today and sadly cannot be fixed correctly,
sadly the web-relay isnt perfect, like i can access some home broadband routers web ui's, but not others,
i also for example cant access our ricoh printers web ui's at all!
but i can access openmediavault web ui or my pikvm without any problems
