### ISSUE TITLE
allow playback for local screen recordings

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4367]
**Is your feature request related to a problem? Please describe.**
i randomly decided to do a local screen recording the other day, after finishing, it then downloaded the file,
but i had no way of playing it back,
but after enabling the server side screen recording i could then access the player feature

**Describe the solution you'd like**
allow access to the player feature for local recordings you have downloaded without server side recording turned on

**Describe alternatives you've considered**
none

**Additional context**

**Comment by Ylianst** [comment]
It's crazy hidden and I need to do better on this, but right click the camera icon and hit "Open Player...".

![image](https://user-images.githubusercontent.com/1319013/182938717-8676f8cd-55e7-42f1-91de-f7f21896d049.png)

Let me know if that works.

**Comment by si458** [comment]
Oh yeh it's there haha thanks!

I should always remember to right click everything to see if the is a hidden context menu haha
