### ISSUE TITLE
Mesh agent 1.0.0.0 crashes when clicking on chat option

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#4370]
In mesh central 1.0.0 version when clicking on chat option in Windows machine, mesh agent is getting crashed.

I couldn't reproduce the same problem in my local setup, mesh agent is successfully launch chat window (in default browser) and able to perform chat. But in one of the production instance facing this issue. I have mailed the core dump to @Ylianst mail ID (ylianst@gmail.com) with subject: "Mesh Agent 1.0.0 crashes on click of chat window"

Please let me know if any more information required in this regard.

**Comment by si458** [comment]
**PLEASE CAN YOU FOLLOW THE BUG REPORT TEMPLATE IN THE FUTURE TO HELP WITH YOUR ISSUE**

have you tried upgrading to the latest version 1.0.63 and seeing if this still happens?

**Comment by Ylianst** [comment]
@knkumar93 I got your email. Thank you. You gave me the dump file which is outstanding, I will take a look at it now. We have a new MeshAgent almost ready to go with a bunch of improvements and fixes, so, it's possible the new agent will have a fix for this. The current agent for example leaks memory each time it runs a shell command on Windows, that is fixed along with WebRTC and more.

**Comment by knkumar93** [comment]
Hi @Ylianst, thanks for the response. I will wait further update on the version in which it is getting fixed.

**Comment by knkumar93** [comment]
After upgrading to latest mesh central version 1.0.78, this problem is solved.
