### ISSUE TITLE
How to beautify Powershell/command prompt responses into a proper JSON without any backslashes or newline?

### ISSUE THREAD

**Issue by sufailDesk** [Ylianst/MeshCentral#4371]
Example: I'm trying to run `systeminfo` (Powershell) in my agent's machine and pass the response into a new custom api. Is there any quick way for this? To achieve this I tried: Listen to webscoket so that it has provided a type: console, value: {systeminfo_data} in it.
But the responses is having many /r/n and backslashes. Even if I remove the /r/n I'm unable to pick certain substance from this.

**Comment by nandox5** [comment]
You would need to parse it. 

Convert to CSV first with `systeminfo /fo CSV`

then parse the CSV to JSON using a CSV to JSON utility. There are multiple out there.

**Comment by sufailDesk** [comment]
I've tried to parse it even before with the commands like `Get-ComputerInfo | ConvertTo-Json` , `systeminfo | ConvertTo-Json`. The responses are in a proper json format when it comes in powershell/cmd. The problem is, when we are trying to pass that data into an api from the websocket it has many unwanted `/r/n` and `"/ /"`. How we could beautify that in a json format?

**Comment by NiceGuyIT** [comment]
Piping output directly to `ConvertTo-Json` _might_ include output that you don't want. For example, information about the host, PowerShell version, command, etc. I found it useful to create an array of `[PSCustomObject]`, convert to JSON and base64 encode it for transmitting over the wire (i.e. API). Base64 encoding bypasses the issue of escaping with backslash to embed JSON in JSON, which seems to be your problem. This example gets the first 5 services that are running, selects specific properties, converts to JSON and base64 encodes it.

```PowerShell
# Command to run on the agent
$services = Get-Service | ? {$_.Status -eq "Running"} | Select-Object Name, DisplayName, Status -First 5
[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($(ConvertTo-Json $services)))
```

A full example using the TRMM API is on the TRMM Discord: <https://discord.com/channels/736478043522072608/888474369544847430/1004797323714510888>.

**Comment by sufailDesk** [comment]
In Discord, I get the message "You find yourself in a strange place. You don't have access to any text channels, or there are none in this server"

**Comment by NiceGuyIT** [comment]
Just a guess, have you tried joining the TRMM Discord server?
<https://docs.tacticalrmm.com/#discusscollaborate-and-get-helpsupport>

**Comment by silversword411** [comment]
Join the discord group first: https://discord.gg/upGTkWp

**Comment by sufailDesk** [comment]
It works. Thanks a lot
