### ISSUE TITLE
Curated  community plugins list in the documentation

### ISSUE THREAD

**Issue by c4ffein** [Ylianst/MeshCentral#4373]
I needed to be able to execute scheduled scripts on my agents. I found the solution through this plugin : https://github.com/ryanblenis/MeshCentral-ScriptTask

But I took some time to find it. Could we have a curated list of community plugins somewhere? That could maybe help people get the solutions they need faster.

Otherwise maybe there could just be a link to https://github.com/topics/meshcentral-plugin somewhere?

**Comment by silversword411** [comment]
I'll see what I can do.

So far docs were just about converting the PDFs to mkdocs

I've been filling in issue info as it comes up, but it's still missing faq, troubleshooting, and 3rd party resource links.

I'll see what I can do, if you get any more links to plugins post them. There's one GitHub user that has done several plugins, already know about his stuff.

Thx

**Comment by c4ffein** [comment]
Thanks for checking my issue! I didn't find any plugin except those from the GitHub topic, and didn't even check how the MeshCentral doc was made.
Also, I never used mkdoc, I imagine you'll use one of the plugins available to generate the PDFs, but just in case, I made https://github.com/c4ffein/txt2pdf forking another project some time ago (based on WeasyPrint as mkdocs-with-pdf for example), in case you have some custom needs for your pdf generation you can just make some issues and I'll make it compatible with mkdocs with the needed features

But maybe as the fact that MeshCentral having a plugin system enables so much more use-cases, it could also just be written in the README? For exemple between the "Design and Architecture Guide" and "New Searchable Documentation" paragraphs in the Documentation section, we could have:

A list of available [plugins](https://ylianst.github.io/MeshCentral/meshcentral/plugins/) can be found at the [meshcentral-plugin GitHub Topic](https://github.com/topics/meshcentral-plugin).

Just a suggestion for the README ofc, I'm far less sure about it

**Comment by Ylianst** [comment]
I don't mind having a plug-in list, but just note that I don't support them also, I can't really fix any issues on MeshCentral if plug-ins are installed since I don't test with plugin's. I have been wanting to merge all existing plugins into MeshCentral, the script-task one is probably the first one I need to merge in. This way, the feature would be properly tested and supported.

**Comment by c4ffein** [comment]
Is it ok for you if I do these 2 PR?
- one with an note in the README about the availability of plugins and a link to the documentation
- one with both the curated list, a link to the GitHub topic and a note about what you just wrote in that documentation (plugins being untested and some of them probably ending merged to the project)

**Comment by silversword411** [comment]
https://ylianst.github.io/MeshCentral/meshcentral/plugins/
