### ISSUE TITLE
Server Console `dbstats` command `[object Object]` instead of stats

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#4376]
The `dbstats` command in the server console doesn't appear to function as expected.  Instead of showing any actual stats it shows `[object Object]`.  This is true both of environments using MongoDB (getting real world use) and of local test environments using NeDB.  Running `node node_modules/meshcentral --dbstats` on these systems works as expected.  I also did some regression testing to see if it worked properly in a previous version and it looks like 1.0.32 broke it for me.

|  | MongoDB | NeDB |
| - | - | - |
| v1.0.31 | ![image](https://user-images.githubusercontent.com/1279475/182993752-4e6e9926-4868-49e5-9cbd-05cf21e87023.png) | ![image](https://user-images.githubusercontent.com/1279475/182994044-5cb95b29-9a9e-420f-b1d6-e6be4efbbb3e.png) |
| v1.0.32 | ![image](https://user-images.githubusercontent.com/1279475/183313487-0f7e1a5d-4a4f-4a19-ab83-205990d68f8a.png) | ![image](https://user-images.githubusercontent.com/1279475/182994634-4e29984a-aea1-4131-a07e-c063f3d4f57b.png) |

Currently on v1.0.63, but not including screenshots of that as they would be the same as the 1.0.32 screenshots.

**Comment by Ylianst** [comment]
For my own use. MeshCentral v1.0.63

PostgreSQL:

![image](https://user-images.githubusercontent.com/1319013/183484679-eddb1a82-a77f-46c8-954e-6d7b27a8fa1e.png)

MySQL:

![image](https://user-images.githubusercontent.com/1319013/183484858-9e2a9860-a935-4dae-bbf4-5ba528e4b891.png)

NeDB:

![image](https://user-images.githubusercontent.com/1319013/183484941-35e7a019-c281-42b5-a3f3-41305962a10d.png)

MongoDB:

![image](https://user-images.githubusercontent.com/1319013/183485273-005c5f39-ef7e-474d-b232-33fc65449ce2.png)

**Comment by Ylianst** [comment]
Your right, thank you for this report. Working on a fix now.

**Comment by si458** [comment]
Could my issue here with the same json object be related?
https://github.com/Ylianst/MeshCentral/issues/4369#issuecomment-1206792947

**Comment by Ylianst** [comment]
@si458 It's unrelated.

I just push a fix for this.

NeDB:

![image](https://user-images.githubusercontent.com/1319013/183488907-172a7f2f-5403-43ba-a2c4-d499f0b0661f.png)

MongoDB:

![image](https://user-images.githubusercontent.com/1319013/183489023-80f32e35-af5c-4ec3-b2ee-12848ff4ddba.png)

Will be in MeshCentral v1.0.64

**Comment by MailYouLater** [comment]
Confirmed.  `dbstats` server console command works for me in both NeDB and MongoDB deployments with v1.0.64, I'll push it to the production server now.  Thanks.  😸
