### ISSUE TITLE
Unable to update server - Installer indicates 'Unable to get available version'

### ISSUE THREAD

**Issue by dmccracken-livewire** [Ylianst/MeshCentral#4379]
When trying to run MeshCentralInstaller-2.11 to update Mesh, I get an error that indicates 'Unable to get available version (#2).
We're currently at 0.8.28 on Windows 2016 DataCenter.
Any idea?
I also tried doing a server self-update from MeshCentral, but that doesn't do anything (and never has worked from day 1).

**Comment by Ylianst** [comment]
Generally the problem is that MeshCentral can't find the `npm` tool and so, can't run it to see if there is a new version. You can fix this by setting the path to `npm` in the config.json like this:

```
{
  "settings": {
    "npmPath": "c:\\npm.exe",
    "npmProxy": "http://1.2.3.4:80"
  }
}
```

The problem could also be that you need a proxy, the configuration line to that is above.

You can also manually update. Just stop your server and so this:

```
mv node_modules node_modules_bak
npm install meshcentral
node node_modules/meshcentral
```

Then wait for all optional modules to install, then once the server starts hit ctrl-c and start up the server again. You can also use the following to help you start/stop the server:

```
node node_modules/meshcentral --install
node node_modules/meshcentral --uninstall
node node_modules/meshcentral --start
node node_modules/meshcentral --stop
```

Let me know if this helps.

**Comment by dmccracken-livewire** [comment]
Thanks Ylian.  I ended up having to uninstall everything and install an updated version of node.js.
After doing a complete new install and copying the original data files into the new install, the service won't start.
I'm seeing this error:
Child process [2820 - C:\Program Files\nodejs\node.exe  --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined] finished with 1

**Comment by dmccracken-livewire** [comment]
Found this in the error log:
Error: Cannot find module 'C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js'

The entire lib directory was missing under node-windows, so I copied that from my backup.  The service appears to be working now.
Any idea why that wouldn't have installed?

**Comment by Ylianst** [comment]
It's difficult to come up with a theory of what happened, but I will note that when running MeshCentral, you should always run like from the path that is parent to `node_modules`, so you do this:

```
cd C:\Program Files\Open Source\MeshCentral
node node_modules\meshcentral
```

You do NOT do this:

```
cd C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral
node meshcentral
```

The problem with the second command is that NPM may install missing modules are the incorrect location.

Also, in general I recommend not using the MeshCentral MSI Installer and just install manually unless you are very much scared of the command prompt. Anyone that knows about bit about the shell should install MeshCentral like this:

```
mkdir c:\meshcentral
cd c:\meshcentral
npm install meshcentral
node node_modules\meshcentral
(ctrl-c when done installing optional modules)
node node_modules\meshcentral --install
```

This way, just have a lot more control over what is going on. Just my opinion, the MSI installer basically does the same thing and installs NodeJS for you.

**Comment by dinger1986** [comment]
@si458 can close
