### ISSUE TITLE
Agent does not stay online

### ISSUE THREAD

**Issue by eightoftwelve** [Ylianst/MeshCentral#438]
The agent appears to work perfectly for x64 and linux clients.  I am running server version 0.3.9-y and the client for my only Windows 7 x32 (I am not sure if it is a Windows 7 or x32 client issue) does not stay onlline.  We also have screenconnect (from ConnectWise) installed and it works perfectly.  Sometimes if we connect via screenconnect and log in, mesh will auto start working, other times we need to restart the mesh client,  Happy to provide any logs required to address issue.  Enjoy your holidays and love the product.

Scotty

**Comment by killmasta93** [comment]
do you have NGINX as your fontend? do you have the stay alive option on NGINX

**Comment by eightoftwelve** [comment]
NGINX?  Yes I do!! (So I can run MESH and SOPHOS at the same time).  good pickup.  I will investigate stay alive option.  This does only affect the x32 client?

**Comment by eightoftwelve** [comment]
Is this what you mean?

ssl_session_timeout 999999s;

I do not currently have it in but simple to add.

**Comment by killmasta93** [comment]
this is my nginx conf
http {
# MeshCentral uses long standing web socket connections, set long timeouts.
proxy_send_timeout 999999s;
proxy_read_timeout 999999s;
# HTTP server. In this example, we use a wildcard as server name.
server {
listen 80;
server_name remote.tirescue.com;
location / {
proxy_pass http://127.0.0.1:800/;
proxy_http_version 1.1;
# Inform MeshCentral about the real host, port and protocol
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
}
# HTTPS server. In this example, we use a wildcard as server name.
server {
listen 443 ssl;
server_name remote.tirescue.com;
# We can use the MeshCentral generated certificate & key
ssl_certificate /etc/letsencrypt/live/remote.mydomain.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/remote.mydomain.com/privkey.pem;
ssl_session_cache shared:WEBSSL:10m;
ssl_session_timeout 999999s;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;

location / {
proxy_pass http://127.0.0.1:4430/;
proxy_http_version 1.1;
#Allows websockets over HTTPS.
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
# Inform MeshCentral about the real host, port and protocol
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
}
}

**Comment by eightoftwelve** [comment]
Thanks.  I am away with work for a couple of days.  I can easily make the changes but it will take time to confirm they have fixed it.  

However, I would bet money that you nailed the problem.

Thanks.  Scotty

**Comment by MailYouLater** [comment]
@killmasta93: You should put your config in a code block to make it easier to read. (Proper indentation helps to make it easier to read too.)

    http {
    
        #
        MeshCentral uses long standing web socket connections, set long timeouts.
        proxy_send_timeout 999999 s;
        proxy_read_timeout 999999 s;
    
        #
        HTTP server.In this example, we use a wildcard as server name.
        server {
            listen 80;
            server_name remote.tirescue.com;
            location / {
                proxy_pass http: //127.0.0.1:800/;
                    proxy_http_version 1.1;
    
                Inform MeshCentral about the real host,
                port and protocol
                proxy_set_header X - Forwarded - Host $host: $server_port;
                proxy_set_header X - Forwarded - For $proxy_add_x_forwarded_for;
                proxy_set_header X - Forwarded - Proto $scheme;
            }
        }
    
        #
        HTTPS server.In this example, we use a wildcard as server name.
        server {
            listen 443 ssl;
            server_name remote.tirescue.com;
    
            #
            We can use the MeshCentral generated certificate & key
            ssl_certificate / etc / letsencrypt / live / remote.mydomain.com / fullchain.pem;
            ssl_certificate_key / etc / letsencrypt / live / remote.mydomain.com / privkey.pem;
            ssl_session_cache shared: WEBSSL: 10 m;
            ssl_session_timeout 999999 s;
            ssl_ciphers HIGH: !aNULL: !MD5;
            ssl_prefer_server_ciphers on;
    
            location / {
                proxy_pass http: //127.0.0.1:4430/;
                    proxy_http_version 1.1;#Allows websockets over HTTPS.
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
    
                #Inform MeshCentral about the real host,
                port and protocol
                proxy_set_header X - Forwarded - Host $host: $server_port;
                proxy_set_header X - Forwarded - For $proxy_add_x_forwarded_for;
                proxy_set_header X - Forwarded - Proto $scheme;
            }
        }
    }

**Comment by killmasta93** [comment]
sorry i did it in a rush to help him out ill normally put it on pastebin wont happen again

**Comment by eightoftwelve** [comment]
This does appear to be fixed (with the nginx proxy changes).  Thanks.
