### ISSUE TITLE
Agents cannot connect to server

### ISSUE THREAD

**Issue by jdhenshall** [Ylianst/MeshCentral#4380]
Hello, I am new to MeshCentral and I mostly followed AwesomeOpenSource's guide to installing MeshCentral on Docker. I got the server set up, and configured. I am accessing through NginX PM. I have it at a domain I own my.domain.com and my private IP is 10.0.0.x:8086. I can go to my.domain.com both on my LAN and outside my LAN and connect to the WebUI. However, when I attempt to add a device, my agents cannot seem to connect. I've tried Windows, Linux, and my Android phone.

On Windows, when I go to CMD and type the "meshagent.exe run", I get output similar to:

```
Connecting to: wss://my.domain.com:443/agent.ashx
Mesh Server Connection Error [1044]
AutoRetry Connect in 3432 milliseconds
```
When I type my.domain.com:443 in my browser, it connects me to the WebUI

On Linux, I SSH into the device I wanted to add, and ran the command it presents. The device is a Raspberry Pi. It seemed to exectute the command fine, but it never popped up in WebUI.

On Android, the server presents the QR code for registration. The Android phone will "connect" to it, but it gets stuck on `Authenticating `and then times out. I tried both from my WLAN and using LTE (outside network) and neither works.

Not sure if its a routing/proxy issue or something else I'm missing. I did confirm the server is running in hybrid mode. 

As a troubleshooting step, I manually opened the MSH file in Notepad, and changed:

`MeshServer=wss://my.domain.com:443/agent.ashx`

to

`MeshServer=wss://10.0.0.x:8086/agent.ashx`

and it appeared in my console. So I don't know why the browser seems to work find the server but not the agent.

**Comment by si458** [comment]
I'm having a similar issue at the moment where after a number of hours (random) I can't add agents or connect to devies either?
Random one can u try restarting the meshcentral server when the device won't connect and see if it then adds it? As that seems to fix it for me

**Comment by jdhenshall** [comment]
I have tried restarting the container a few times to see if that would help. I did not.

Here are the first few lines from the `info` command on the MeshCentral console:

```
    "meshVersion": "v1.0.63",
    "nodeVersion": "v10.19.0",
    "runMode": "Hybrid (LAN + WAN) mode",
    "productionMode": true,
    "database": "NeDB",
    "platform": "linux",
    "arch": "x64",
```

Here is my config.json from the `data `folder, I don't recall really editing this on setup (made initials changes through docker-compose yaml file). I did not set the _sessionKey in Settings, or the titles in domains, I assume those are defaults/placeholders.

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "my.domain.com",
    "_WANonly": true,
    "_LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true"
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://10.0.0.x:443"
      }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by jdhenshall** [comment]
AND... I solved my own issue because I cannot read:

certURL still had my private IP instead of my domain. I changed that to my.domain.com and everything worked. Sorry to bug you guys! Need to read documentation a little more closely. I'm new to JSON and homelab stuff!

**Comment by si458** [comment]
Glad u sorted it! I was going to say u need to update ur node version as 10 is old, so it needs to be the latest LTS 16.16 at least haha

**Comment by deajan** [comment]
Also had lots of agent connection errors, eg:
```Connecting to: wss://meshcentral.exmple.tld:443/agent.ashx
Mesh Server Connection Error [1128]
AutoRetry Connect in 2057 milliseconds
Connecting to: wss://meshcentral.exmple.tld:443/agent.ashx
Mesh Server Connection Error [1240]
AutoRetry Connect in 3597 milliseconds
Connecting to: wss://meshcentral.exmple.tld:443/agent.ashx
Mesh Server Connection Error [1248]
AutoRetry Connect in 6938 milliseconds
```

My meshcentral server was behind Haproxy with a useragent filter.
Since meshagent doesn't send any user agent, it just got silent dropped.

So if you're having a special reverse proxy config, you might as well check it ;)
