### ISSUE TITLE
Mesh not using redirport and port is http

### ISSUE THREAD

**Issue by kennyparsons** [Ylianst/MeshCentral#4381]
**Describe the bug**
I have mesh configured to run behind nginx. Nginx is handling my tls certificates. However, I am trying to get mesh to run on HTTPS (using it's own self-signed certs) as an added layer of protection. I am only able to run as non-root, no sudo. So I set the redirect port to a higher port number (in this case 11757). Alias port is still 443. Port is 11795. I can access mesh via my public IP:11795, but it's http, not https. 

config.json:
```json
{
  "settings": {
    "AliasPort": 443,
    "Cert": "mesh.mydomain.tld",
    "Port": 11795,
    "RedirPort": "11757",
    "TLSOffload": [ "100.87.39.55", "127.0.0.1", "::1" ],
    "trustedProxy": [ "100.87.39.55", "127.0.0.1", "::1" ],
    "webRTC": false,
    "wsCompressoin": true,
    "AgentPing": 55,
    "AgentPong": 55,
    "BrowserPing": 55,
    "BrowserPong": 55
  },
  "domains": {
    "": {
      "certUrl": "mesh.mydomain.tld:443",
      "newAccounts": 0
    }
  }
}
```

**Expected behavior**
When accessing `http://IP:11757`, I should get redirected to `https://IP:11795`. However, I can only access via `http://IP:11795`.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 10
 - Virtualization: None
 - Network: nginx on a vps, reverse proxying to the ip of my mesh vps. 
 - Version: 1.0
 - Node: 16.14.0

**Comment by kennyparsons** [comment]
Note, as of right now, I am not using nginx. I'm just trying to access the UI with the public IP first. Then I'll introduce nginx, knowing it should be able to access it.

**Comment by Ylianst** [comment]
Ha, I see the problem, you can't use both these lines at the same time:

```
    "TLSOffload": [ "100.87.39.55", "127.0.0.1", "::1" ],
    "trustedProxy": [ "100.87.39.55", "127.0.0.1", "::1" ],
```

Remove the `TLSOffload` line and you should get exactly what you want.

When you specify `TLSOffload`, MeshCentral assumes that TLS is going to be done in front of MeshCentral and so, TLS is removed from the HTTPS port. Note that even with TLS removed, the main port stills sends HTTP headers consistent with TLS still being performed, just not by MeshCentral.

`TrustedProxy` will indicate that source IP addresses are ok to consider the `x-forward-for` HTTP header, but it does not have the same effect of removing TLS as `tlsoffload` has.

As for your port numbers and aliasing, all looks good.

**Comment by kennyparsons** [comment]
Ah, wonderful. Related question: My hosts all show the incorrect hostname. They show the ip of the reverse proxy server. Is that related to my trusted proxy line?
Here is my nginx config:
```nginx
# configuration file /etc/nginx/conf.d/host/mesh.mydomain.tld.conf:
#mesh
server {
        listen                  80;
        server_name             mesh.mydomain.tld;
        return                  301 https://mesh.mydomain.tld$request_uri;
}

server {
        listen                  443 ssl http2;
        server_name             mesh.mydomain.tld;

        access_log              /var/log/nginx/sites.access.log vcombined;
        error_log               /var/log/nginx/mesh.mydomain.tld.error.log warn;

        # TRUNC all my ssl and general configs

        location / {
            proxy_pass      http://100.82.108.111:7450;

            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        X-Forwarded-Port $server_port;

            proxy_set_header        X-Original-URL "";
            proxy_set_header        X-Rewrite-URL "";
            proxy_set_header        X-Forwarded-Server "";
            proxy_set_header        X-Forwarded-Host "";
            proxy_set_header        X-Host "";

            proxy_hide_header       X-Powered-By;
            proxy_hide_header       X-AspNetMvc-Version;
            proxy_hide_header       X-AspNet-Version;
            proxy_hide_header       X-Drupal-Cache;
            proxy_hide_header       X-Runtime;

            proxy_http_version      1.1;
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection "upgrade";
        }
}
```

**Comment by Ylianst** [comment]
In your case, you probably don't intend to manage devices on your local network using MeshCentral LAN capabilities (where MeshCentral directly connects to devices on the same LAN as the server). In the settings section of the config.json, add this line:

```
"wanonly": true
```

This will put your server in WAN mode and "hostname" for all devices will no longer show up. [I have a video on LAN/WAN mode here](https://www.youtube.com/watch?v=gx5Fh3pQOns) in case you want to know more on this.

**Comment by kennyparsons** [comment]
You're a wizard, harry. Thank you!
