### ISSUE TITLE
Cira time out while starting my laptop 

### ISSUE THREAD

**Issue by Hobbiesworld** [Ylianst/MeshCentral#4385]
**Describe the bug**when ever I start my laptop it shows cira time out every time I open it 

**To Reproduce**

**Expected behavior**

**Screenshots**
![16604825152924387919916454978370](https://user-images.githubusercontent.com/111059407/184538492-d058976d-bc8b-4047-83d4-a1e67d3fc067.jpg)
![16604825760736297621744227565370](https://user-images.githubusercontent.com/111059407/184538540-4a2aa1a1-ceba-4e58-932f-373b4d4c29d2.jpg)
![16604826371097648823817615314712](https://user-images.githubusercontent.com/111059407/184538573-7726b096-c4b0-4c83-bbb6-b851c876c94c.jpg)

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Virtualization: [e.g. Docker]
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]hp elitebook 8440
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
