### ISSUE TITLE
Screen Blanking on remote desktop

### ISSUE THREAD

**Issue by evilexecutable** [Ylianst/MeshCentral#4392]
**Is your feature request related to a problem? Please describe.**
There are certain times throughout my IT career, where being able to blank a screen during a remote control session is useful for privacy purposes. This is also especially useful now as I am currently managing over 800 digital advertisement screens around the country, and being able to do maintenance on this screens without the general public seeing, is very useful. We currently use LogMeIn for this purpose on Windows machines, but we'd eventually like to move away.

**Describe the solution you'd like**
Being able to optionally blank the monitor of a machine during a remote desktop session and block user input.

**Describe alternatives you've considered**
We currently use LogMeIn to serve this purpose for Windows Machines.

**Comment by dinger1986** [comment]
Same as #416
