### ISSUE TITLE
Question - Why is agent executable not being signed with new icon file?

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshCentral#4396]
**Describe the bug**
I can't get the windows agents to be signed with the icon file setup in the "agentFileInfo" setting in config.json

**To Reproduce**
1. Set the "agentFileInfo" setting in the config.json with required fields
2. Delete all files in the "meshcentral-data/signedagents" folder
3. Copy your .ico file to the "meshcentral-data" folder. (Icon size is 48x48 pixels
4. restart the Meshcentral Service
5. Download the agent and see the icon has not changed on the newly signed executables in the signedagents folder.

**Expected behavior**
The settings change as specified in the config.json

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: XCP-ng
 - Network: LAN,WAN hybrid with reverse proxy
 - Version: MC v1.0.65
 - Node: 16.15.1

**Client Device (please complete the following information):**
N/A

**Remote Device (please complete the following information):**
N/A

**Additional context**
I'm trying for now to change only the agent executables Icon after downloaded. I have not tested other fields. 

**Your config.json file**
This file has been checked for validity by jsonlint-php. Only showing the relevent setting section. This is under the "domains" default section of the config.json
```
...
      "agentFileInfo": {
        "properties": {
          "icon": "LaptopPitstop.ico"
        }
      },
...
```

**Comment by PathfinderNetworks** [comment]
I just upgraded to 1.0.65 and added the icon setting to my agentfileinfo section as well as dropped my .ico file in the meshcentra-data folder.  I restarted MeshCentral to create new signed agents (I already have a code signing cert and sign my agents).  My icon file is now embedded in the executable.  I verified that by viewing the embedded icon data using an icon viewer app (BeCyIconGrabber in this case).  
I do notice that, unfortunately, the installer icon itself is still the old MeshCentral icon.  I'd like to see the installer icon also be updated with this custom icon.  
Maybe that's what you were expecting to see?
![mesh_icon](https://user-images.githubusercontent.com/48607498/184469797-eb748548-f897-42a0-a1bf-1da898f6e39d.JPG)

**Comment by si458** [comment]
I believe its a windows explorer cache issue?

I had this issue when changing the info and icon a few years ago when j built my own editor using resource hacker for nodejs

Try this link and see if it helps

https://www.howtogeek.com/232779/how-to-rebuild-a-broken-icon-cache-in-windows-10/

**Comment by PathfinderNetworks** [comment]
Ha, you are right!  When I viewed the signed agents from a different PC not only was the icon file embedded in the agent but the agent installer did actually have the custom icon presented on the exe.  Nice!

**Comment by si458** [comment]
> I believe its a windows explorer cache issue?
> 
> I had this issue when changing the info and icon a few years ago when i built my own editor using resource hacker for nodejs
> 
> Try this link and see if it helps
> 
> https://www.howtogeek.com/232779/how-to-rebuild-a-broken-icon-cache-in-windows-10/
> 

Please can you add this to the faq? @silversword411 it will help others in future for icon changing

**Comment by Ylianst** [comment]
I have had the Windows icon cache be a problem during the entire development of this feature. Windows File Explorer would never show me the right icon. I never tried to clear the cache, but probably something I will need to do.

**Comment by Ylianst** [comment]
To answer the original question from @LPJon, the exact section in the config.json is this:

```
      "agentFileInfo": {
        "icon": "MeshServer1.ico",
        "filedescription": "sample_filedescription",
        "fileversion": "0.1.2.3",
        "internalname": "sample_internalname",
        "legalcopyright": "sample_legalcopyright",
        "originalfilename": "sample_originalfilename",
        "productname": "sample_productname",
        "productversion": "v0.1.2.3"
      },
```

You need to place this in the domain section of the config.json.

In your config.json you have this:

```
      "agentFileInfo": {
        "properties": {                           <---- Not right
          "icon": "LaptopPitstop.ico"
        }
      },
```

You probably tool this sample from the schema file, but instead look at the "sample-config-advanced.json" [located here](https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json).

**Comment by LPJon** [comment]
@Ylianst You are right! I tooled the wrong file. Very sorry....i played with this for 3 hours and just couldn't figure it out. @si458 You are also right and thank you for posting an article on how to fix the icon caching issue. That is very annoying...I wonder why windows would do that.

**Comment by Ylianst** [comment]
Windows caches icon to boost speed. It's a good idea until it does not work right.
