### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by kylelliott** [Ylianst/MeshCentral#4397]
Hi 

keep getting black screen when trying to connect to any of my oc

**Comment by lexisman** [comment]
What version of Meshcentral are you using, OS of remote PC's?

**Comment by PathfinderNetworks** [comment]
If you have WebRTC enabled that could possibly be the cause.  Do you notice if the connection to these devices showing a black screen says 'WebRTC'?

**Comment by kylelliott** [comment]
Hi 
WebRTC is coming up on all pc that i have connected to MC

**Comment by kylelliott** [comment]
> Hi WebRTC is coming up on all pc that i have connected to MC @PathfinderNetworks

**Comment by PathfinderNetworks** [comment]
As a test, I would disable WebRTC in your config.json.  All you would need to do is remove the "WebRTC": true,
line from the settings section then restart MeshCentral.  
I had the same issue with WebRTC on most of my devices.  It would connect but just show a black screen.  But the mouse and other input was actually being sent to the remote device.
