### ISSUE TITLE
RDP on reverse proxies

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#44]
Need RDP to work on reverse proxy

**Comment by Ylianst** [comment]
In the latest MeshCentral 0.2.4-c, I made fixes to the ClickOnce application to make it work with reverse proxies and ECDSA certificates. Note that the ClickOnce application does not currently support HTTP proxies.

Can you update MeshCentral and try again? - Thanks.

**Comment by Ylianst** [comment]
Looks like ClickOnce with reverse-proxies is working well. There is also a problem with the connecting dropping that I hope I fixed in yesterday's release. I will close this one, if the RDP connection keeps dropping, please open another issue for that.
