### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by LavinCompae** [Ylianst/MeshCentral#4407]
Hello,

I have tested the installation on an isolated computer to check its usefulness and once satisfied I have decided to install it on the server.

Once installed by ssh the program following the steps in the tutorial, on my linux ubuntu server and added the local ip address in the mongodb.

The systemctl status of mongo and mesh tell me that everything is ok.

When I connect via a browser to the ip address two things can happen;
by http it doesn't arrive and chrome tells me: ERR_CONNECTION_TIMED_OUT
by https after confirming that I trust the web it remains blank and nothing else appears.

At this point I don't know what else to do.

Would you be so kind as to offer me your help?

Thank you
![status mesh 2](https://user-images.githubusercontent.com/111420536/185107368-0b589282-5472-4039-8ba1-4544448e936f.jpg)
.

**Comment by Ylianst** [comment]
Hi. Can you post your config.json file and place XXXXXXXXXXXX for any confidential information?

Also, your server shows it's setup in LAN mode and trying to do Let's Encrypt? That is probably not right.

**Comment by LavinCompae** [comment]
Thank you for your response.

I am attaching the config.json file below
[config.zip](https://github.com/Ylianst/MeshCentral/files/9371356/config.zip)
[Uploading config.zip…]()

as far as I can understand in the file the LAN and WAN mode are enabled. 
If it is necessary to disable Let's Encrypt, please let me know how to do it.

Thanks again!

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
