### ISSUE TITLE
Windows agent bitmap logo

### ISSUE THREAD

**Issue by Matt-CyberGuy** [Ylianst/MeshCentral#4410]
**Describe your issue**
I saw an addition for adding support for changing the windows agent bitmap logo. Was wondering if there is documentation somewhere on utilizing this feature.

https://github.com/Ylianst/MeshCentral/actions/runs/2843717189/workflow

**Comment by si458** [comment]
@silversword411 I believe this is for you haha

**Comment by PathfinderNetworks** [comment]
Ylian's blog has graphics for what settings you'll need to add to config.json, etc to make this work.  But that's the only 'documentation' that I know about.  That said, it was all I needed to make it work. 
https://meshcentral2.blogspot.com/2022/08/meshcentral-agent-icon-batch-agent.html

**Comment by PathfinderNetworks** [comment]
Also, it has to be a .ico file (I took a high-res PNG of my logo and converted that to a .ico file using an online tool).  That file is then placed in the meshcentral-data folder and is referenced by the "icon" settings you add to your config.json.

**Comment by Ylianst** [comment]
[In this blog](https://meshcentral2.blogspot.com/2022/02/meshcentral-new-windows-agents.html), you can see how to change the agent dialog box image and installation text.

![image](https://user-images.githubusercontent.com/1319013/185559551-7fb0efdc-ed51-40f7-8fb5-1f19c20f5301.png)
