### ISSUE TITLE
Web relay guest sharing

### ISSUE THREAD

**Issue by folosleg** [Ylianst/MeshCentral#4413]
How about being able to share web relays with guest, just like sharing desktop, files or terminal...
If it's technically possible, I believe would be a great addition to this already very handy feature!
Cheers

**Comment by Ylianst** [comment]
Coming up in MeshCentral v1.0.73.

![MC2-WebRelayGuestSharing](https://user-images.githubusercontent.com/1319013/186821027-903411b6-fa58-4448-b1e6-202b71dfc7e6.png)

**Comment by Ylianst** [comment]
MeshCentral v1.0.73 just got published.

**Comment by folosleg** [comment]
This is just amazing!
Again, thank you very much all your effort developing this awesome project!
