### ISSUE TITLE
Allow password resets when public registration is disabled

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#442]
I've done a cursory search for "password reset" in the issues on this repository and saw that you are supposed to be able to click "reset account" to initiate a password reset somewhere, but I can't seem to find that option on my MeshCentral login page or in the settings. My assumption is that this feature is only available when you have public registration enabled in your `config.json` file (i.e. if you have `newAccounts` set to 1).

Since I am offering MeshCentral as a SaaS product, it would be very useful if customers could initiate a password reset for their own users (i.e. on their separate https://meshcentral.example.com/customer1 domain) even when public registration has been disabled.

Would it be possible to add a configuration option to the domain section of the `config.json` file so that the password reset feature could be enabled on a per-domain basis?

**Comment by Ylianst** [comment]
The option should be available when a mail server (SMTP server) is setup in the config.json. You can use a gmail account for this if you like. Once setup, it should show up. For example, if you go to the [MeshCentral.com](https://meshcentral.com/) login page, you see it under the login button. Let me know if you have SMTP setup and still don't see it.

**Comment by whalehub** [comment]
@Ylianst I can confirm setting up SMTP in my `config.json` made the option appear on my login page. I encountered an issue with setting up SMTP itself, but I'll open a new issue for that.
