### ISSUE TITLE
new run commands only shows half the reply

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4422]
**Describe the bug**
the new run commands feature is only showing half the reply in the console window?

**To Reproduce**
1. go to a device
2. click run
3. Windows Command Prompt, Run As Agent, Commands from text box, `net stats workstation`
4. click ok
5. (expected a pop up with the reply? BUT then realised you have to go into console tab first)
6. reply shown in console is only half their?

**Expected behavior**
the reply in the console tab to be full not half their?

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Alpine
 - Virtualization: [e.g. Docker] Docker
 - Network: hybrid, Traefik reverse proxy, TLSoffload, 
 - Version: [e.g. 1.0.43] 1.0.70
 - Node: [e.g. 18.4.0] 16.16.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Windows 11 Home
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] Firefox 103.0.2
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Computer
 - OS: [e.g. Windows 10 21H2] Windows 10 21H2
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Current Core: Mar 25 2022, 834195334

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by Ylianst** [comment]
Arg. The run command feature does not currently support getting results back... but I will be adding that. The agent console may show some stuff, but that is only for debugging.

**Comment by si458** [comment]
oh ok i was expecting it to show me a reply,
it would indeed be handy to show a reply, because for example meshcentral doesnt show me the uptime of a computer,
where as `net stats workstation` at the command line i see exactually when the computer switched on
(issues with customers saying ive restarted the computer when infact they havent at all)

**Comment by PTR-inc** [comment]
The 'know when it has restarted' question is interesting, as I also frequently need to know this. As the pc's often reboot too fast to be reflected in the power state bars, it would maybe be an interesting enhancement for the power state to reflect reboot/service restarts event as a green/red stripes in the power state bars.

**Comment by si458** [comment]
for some reason when `on data` its not sending the text to the console and missing data?
so if we just join the data together then sends at the end, its all there?
