### ISSUE TITLE
Wake On Lan - smarter?

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4424]
I know about the wake up command on each device, my question is "Is it possible to make the Wake On Lan be sent out over all connected agents. Since mac addresses are unique, I would thing this would be possible. My issue is my mesh central server is on its own network and my agents access it over Wan so I can't use the Wake on lan feature.

**Comment by Ylianst** [comment]
Yes When you select "wake" for a device, all of your connected devices in the same device group will be sending the wake-on-lan magic packet. This is the only command in MeshCentral where a command causes the other devices to do something.

If you have 10 devices in an office and 9 are sleeping. As long as one is connected to MeshCentral, you should be able to wake all the other ones.

Hope that makes sense. If you have Intel AMT active, MeshCentral will also use the connection to Intel AMT to wake the device.
