### ISSUE TITLE
undefined in method 'handleServerCommand()'

### ISSUE THREAD

**Issue by q16marvin** [Ylianst/MeshCentral#4431]
Hi,

i have a client, everything works... but when i try to connect to Desktop it not work and in "Console" i see this message:

uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: Error calling WTSQuerySessionInformationW: undefined in method 'handleServerCommand()'

![grafik](https://user-images.githubusercontent.com/19844709/185880905-3ffae4db-3d16-42ac-8fbb-035f752dc5fa.png)

it seems only if someone is logged in in windows ... 

**Server Software (please complete the following information):**
 - OS: ubuntu
 - Virtualization: proxmox
 - Network: hybrid
 - Version: 1.0.71
 - Node: 14.20.0

**Client Device (please complete the following information):**
 - Device: Client
 - OS: WIN10
 - Network: HYBRID
 - Browser: Firefox
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: Client
 - OS: WIN10
 - Network: HYBRID
 - Current Core Version (if known): Mar 25 2022, 3863795360

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
