### ISSUE TITLE
MeshCentral Server starts but Mongo does not after upgrade to "Jammy"

### ISSUE THREAD

**Issue by frankmcc** [Ylianst/MeshCentral#4433]
After running a "do-release-upgrade" on our Ubuntu 20.04 server with a working installation of MeshCentral using MongoDB, the upgrade completed successfully but the web page did not load.  I checked to see if the MeshCentral service was running and it was, with no indication of an error.  Checking syslog, I found that we are getting a connection refused when trying to access Mongodb.

I tried various things to get MongoDB running but nothing seems to work

I ran "node ./node_modules/meshcentral and experienced this:
node ./node_modules/meshcentral
Installing mongodb@4.1.0...
Unable to connect to database: MongoServerSelectionError: connect ECONNREFUSED 0.0.0.0:27017

even after updating the config.json to use 127.0.0.1:27017 I get the same error:
node ./node_modules/meshcentral
Unable to connect to database: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

from config.json:
"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",

Am I missing something here?  Has anyone else experienced this?

**Comment by frankmcc** [comment]
sudo tail -f /var/log/sysog reveals that MeshCentral keeps trying, non-stop:

Aug 22 12:27:19 [servername] systemd[1]: Started MeshCentral Server.
Aug 22 12:27:50 [servername] node[6926]: Unable to connect to database: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
Aug 22 12:27:50 [servername] systemd[1]: meshcentral.service: Deactivated successfully.
Aug 22 12:27:50 [servername] systemd[1]: meshcentral.service: Consumed 1.979s CPU time.
Aug 22 12:28:01 [servername] systemd[1]: meshcentral.service: Scheduled restart job, restart counter is at 6.
Aug 22 12:28:01 [servername] systemd[1]: Stopped MeshCentral Server.
Aug 22 12:28:01 [servername] systemd[1]: meshcentral.service: Consumed 1.979s CPU time.
Aug 22 12:28:01 [servername] systemd[1]: Started MeshCentral Server.

**Comment by PTR-inc** [comment]
Mongodb isn't officially supported yet on 22.04. If you want to get it working again, check https://www.mongodb.com/community/forums/t/installing-mongodb-over-ubuntu-22-04/159931/29. Maybe missing libssl1.1 after the upgrade

**Comment by Ylianst** [comment]
This does not seem to be a MeshCentral issue. It looks like MeshCentral can't connect to the MongoDB because MongoDB is not running. Let me know if I am missing anything.

**Comment by frankmcc** [comment]
@PTR-inc - Thanks,  I've reverted the server back to 20.04 and will move away from MongoDB, since they do not seem interested in updating.  It just seems like a bad Idea to install libssl1.1 when libssl3 is installed.

**Comment by frankmcc** [comment]
Are there any guides to move MeshCentral from MongoDB to MariaDB?
