### ISSUE TITLE
open new tab (duplicate tab)

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4434]
**Is your feature request related to a problem? Please describe.**
i want to control multiple devices at once its annoying having to remember
to right click the tab to then click duplicate tab for another tab to open to then control another device

**Describe the solution you'd like**
an icon or link maybe next to `Welcome admin, Logout` that i can click and it automatically opens a new tab with meshcentral again

**Describe alternatives you've considered**
having to remember to right click the tab and click 'Duplicate Tab' for it to open another tab

**Additional context**
maybe if you first connect to a device, then you go to another device and click connect. it opens a new tab and connects?

**Comment by Ylianst** [comment]
Try holding the `shift` key and clicking on a device or on a device tab and let me know if that works for you.

**Comment by si458** [comment]
that works a treat thanks!
not sure if its a bug or not tho, but when the new tab page opens, its missing the left hand side panel?

**Comment by Ylianst** [comment]
It's not a bug, the idea was that you are focusing on that device only. However, I can change the behavior if needed. It's just the additional `&hide=` argument in the URL.

**Comment by si458** [comment]
> It's not a bug, the idea was that you are focusing on that device only. However, I can change the behavior if needed. It's just the additional `&hide=` argument in the URL.

No it's OK thank you!
It's actually helpful as it makes the screen bigger haha
