### ISSUE TITLE
Missing version-info on EXE -installer

### ISSUE THREAD

**Issue by lurendrejer** [Ylianst/MeshCentral#4436]
Hi.

Our install-management tool (Ninite) uses version numbers when deploying software, the EXE-agent doesn't add version information to the registry.

![image](https://user-images.githubusercontent.com/30922656/186195719-73bf27c6-d76f-42ec-b7e0-f2b9cda33bee.png)

Screenshot of a working application with 'proper version information'
![image](https://user-images.githubusercontent.com/30922656/186196958-a329e499-f948-4d49-aa79-6b12cf6b93d2.png)

**Comment by Ylianst** [comment]
Interesting. Yes, the agent does need to fill in the registry with this information, that would be useful.

**Comment by lurendrejer** [comment]
Thank you.

A quick-fix if others are having the same 'problem'

![image](https://user-images.githubusercontent.com/30922656/186380055-e8c3b983-b84c-4717-9618-19a3cd04b461.png)

**Comment by lurendrejer** [comment]
A patch is already in place - thank you very much.

**Comment by Ylianst** [comment]
Looks like Bryan added [this fix](https://github.com/Ylianst/MeshAgent/commit/4d1dc7a08244d71ff2838955797dcf59eddd3fe1) to the MeshAgent yesterday. It will be released with the next MeshAgent. I am working on testing the new version today.

**Comment by lurendrejer** [comment]
Superb - i'm looking forward to being able to download the latest version

**Comment by lurendrejer** [comment]
Working!
