### ISSUE TITLE
Feature request: Filter/Search Clients by Ip address

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#444]
Hi,
If we can filter/search clients via IP address it will be really good function. Can you add this feature?

**Comment by Ylianst** [comment]
In the devices screen, type "ip:1.2.3.4" to search for an IP address. Let me know if that works for you.

![MC2-IpSearch](https://user-images.githubusercontent.com/1319013/63608506-0d407e80-c58a-11e9-83be-8ccd15e04098.png)

**Comment by PathfinderNetworks** [comment]
I just tried this on my server after updating to 0.4.0-g.  It's not working correctly.  I verified the IP address of a device (and the device is active and online). But, when I search for ip:192.168.34.26 (which is the IP address of that device) it finds nothing.  Thing is, as I type the partial address it will find some devices that match.  Such as if I type in ip:192 it will find about 11 devices.  Even so, I know there are easily more than 100 more devices (probably 200) that have an IP address starting with 192.

**Comment by Ylianst** [comment]
Your correct, I will take a look at this again and see what I am matching against. The network information data that includes all of the IP addresses a given device has is only loaded up when you click on a device "Interfaces" link on the device page. I don't load this information for all devices at the start, so I can't match on that.

A I would need to load up a bunch more information of each device, or make a server-side query for devices that match that IP. Not going to be simple, but will check.

**Comment by senolkehya** [comment]
Hi,
When I search from wan ip addresses it is working correctly.  My all devices are on internet side. I don't use lan ip addresses. The function is good for me.
Thanks.

**Comment by mrflaunted** [comment]
The ip: search does not work for me. I only have LAN machines.

**Comment by si458** [comment]
works fine in 2023
using the search box enter `ip:THEIPTOLOOKFOR` e.g `ip:192.168.123.99`
