### ISSUE TITLE
Web relay - support different ports than 80 and 443 on the target device

### ISSUE THREAD

**Issue by herwig-** [Ylianst/MeshCentral#4445]
**Is your feature request related to a problem? Please describe.**
Most of my services run web-servers on different ports than 80 or 443. (due to docker, ...)
In the meshcentral router, I could define a different port to forward and this worked.
In the web-realy feature, only Ports 80 and 443 are accessable
e.g. Home Assistant runs on port 8123 by default ...
![grafik](https://user-images.githubusercontent.com/741471/186544624-f2096a7e-a02a-412d-9c64-3b4c7b803e8d.png)

**Describe the solution you'd like**
I would want to have the option to modify the Ports (and if possible also the ip-Addresses) that the links here show to:
![grafik](https://user-images.githubusercontent.com/741471/186544210-58bd9160-1621-4855-8dfe-f5d52c308f74.png)

**Describe alternatives you've considered**
If you enable modifiaction of port and ip address, it is possible to no longer use the extra device group which is accessable through the relay agent -> as it would be possible to edit the services in the relay agent itself.
The device group for the relay agent is only necessary if other access/information of the device is processed e.g. snmp ( but I believe this would be out of scope of meshcentral)

**Additional context**
thx for your great work!

**Comment by folosleg** [comment]
If you **right click** on either HTTP or HTTPS, you can change the port!
It's even remembered, as you can see on the screenshot HTTP is over port 3001:

![image](https://user-images.githubusercontent.com/80481320/186545982-992b1d1b-a337-4d68-8da7-e4b89bc8374d.png)

**Comment by herwig-** [comment]
thanks, I didn't know this function. (sorry, only became aware of this function through the videos) This however does not solve the problem yet, as you still only provide one HTTP and one HTTPS connection.
I believe there are many cases, where users run a number of docker images on a single pc with a number of different ports for http and https.

I would still prefere the option to have a "service list" on the device where the agent is installed where `ip-Address`, `port` and `service name` can be configured.

**Comment by Ylianst** [comment]
So, you want to be able to configure per device various HTTP/HTTPS links? Since that would be a new request. Close this one, open a new one and indicate exactly what the request is.

**Comment by herwig-** [comment]
thx, I will do so
