### ISSUE TITLE
meshservice-signed and meshservice64-signed

### ISSUE THREAD

**Issue by raystek** [Ylianst/MeshCentral#4446]
Inside the node_modules/meshcentral/agents folder, I have the MeshCmd-signed.exe and MeshCmd64-signed.exe, but not the meshservice-signed and meshservice64-signed. How do I get the self-signed agents binaries?

**Comment by Ylianst** [comment]
I no longer sign the agents. My signature was from un-trusted self-signed cert anyway, so it had little value. As of a few months back, MeshCentral has it's own agent signing system. MeshCentral will generate it's own code signing certificate, it will be the following two files in `meshcentral-data`:

```
codesign-cert-public.crt
codesign-cert-private.key
```

Then, MeshCentral will sign the agent (both 32 and 64bit) and place them in the `meshcentral-data/signedagents` folder. So, that is where you will find them.

Note that as a result of this change, you can now customize the agent icon and version information in the config.json. MeshCentral will apply the agent customization to the binary prior to signing it.

Hope that helps.
Ylian

**Comment by raystek** [comment]
closing
