### ISSUE TITLE
Sectigo AMT Cert - config.json ignoring AmtAcmActivation?

### ISSUE THREAD

**Issue by aRafeymasood** [Ylianst/MeshCentral#4454]
We have got a Sectigo AMT certificate that we are planning to use in order to active our machines in ACM. DHCP Option 15 is already active. 
Sectigo provided the certificate in .cer file. I had imported that in IIS and then exported the .pfx file with a password.
However, after setting up config.json it does not appear to pick the cert when I restart Meshcentral. 
Upon running amtacm command, it only shows the * root certificate and not the one from Sectigo.

![image](https://user-images.githubusercontent.com/47164919/186801539-a6ca4b60-f494-4587-b471-f47d4cdf1284.png)

The config looks like below, maybe I have made a dumb mistake in the config somewhere. Any help is much appreciated.

```
  "settings": {
    "cert": "domain.com.au",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
	"MongoDBBulkOperations" : true,
    "AgentTimeStampServer": false,
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
	"autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe"
    }
  },
 "domains": {
    "": {
      "_title": "",
      "_title2": "Intel® Active Mamagement Technology\n",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
	  "AmtAcmActivation": {
				"log": "amtactivation.log",
				"certpfx": "Sectigo.pfx",
				"certpfxpass": "password",
	  "agentCustomization": {
		  "displayName": "AMT Agent",
		  "description": "IT uses this agent for remote monitoring, management and assistance",
		  "_companyName": "",
		  "_serviceName": "",
		  "fileName": "amtAgent",
		  "image": "logo.png",
		  "_installText": "",
		  "_foregroundColor": "",
		  "backgroundColor": "139,0,0"
		}
	  }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

 - OS: Server 2019
 - Network: HyBrid Mode
 - Version: 1.0.72

**Comment by Ylianst** [comment]
Ran the config.json thru a lint tool to make it look better.

```
{
  "settings": {
    "cert": "domain.com.au",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "MongoDBBulkOperations": true,
    "AgentTimeStampServer": false,
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe"
    }
  },
  "domains": {
    "": {
      "_title": "",
      "_title2": "Intel® Active Mamagement Technology\n",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "AmtAcmActivation": {
        "log": "amtactivation.log",
        "certpfx": "Sectigo.pfx",
        "certpfxpass": "password",
        "agentCustomization": {
          "displayName": "AMT Agent",
          "description": "IT uses this agent for remote monitoring, management and assistance",
          "_companyName": "",
          "_serviceName": "",
          "fileName": "amtAgent",
          "image": "logo.png",
          "_installText": "",
          "_foregroundColor": "",
          "backgroundColor": "139,0,0"
        }
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by aRafeymasood** [comment]
Cheers, that fixed the issue. Was hoping if might be able to assist a bit with ACM activation please.

The certificate shows up in MeshCentral as Activation Certificate 1.
I had then created a new Device Group with software agent > set Intel AMT to Simple ACM, however it is activating only in CCM mode
When I ran the amtinfo on the node > it does show the DNS Suffix "domain.com" - my Sectigo cert is for "meshcentral.domain.com"

I tried creating another group with "AMT only" type > ran the meshcmd amtconfig command on the node > it again activates in CCM
ran amtstats on the server and it shows 1 out off 1 device provisioned
Node is running AMT v14.1

**Comment by Ylianst** [comment]
Add the line `"strictCommonName": false` like I did below, restart the server and let me know if there is any difference.

```
{
  "settings": {
    "cert": "domain.com.au",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "MongoDBBulkOperations": true,
    "AgentTimeStampServer": false,
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\bin\\mongodump.exe"
    }
  },
  "domains": {
    "": {
      "_title": "",
      "_title2": "Intel® Active Mamagement Technology\n",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "AmtAcmActivation": {
        "log": "amtactivation.log",
        "strictCommonName": false,
        "certs": {
          "MySectigoCert": {
            "certpfx": "Sectigo.pfx",
            "certpfxpass": "password"
          }
        }
      },
      "agentCustomization": {
        "displayName": "AMT Agent",
        "description": "IT uses this agent for remote monitoring, management and assistance",
        "_companyName": "",
        "_serviceName": "",
        "fileName": "amtAgent",
        "image": "logo.png",
        "_installText": "",
        "_foregroundColor": "",
        "backgroundColor": "139,0,0"
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by aRafeymasood** [comment]
Thanks Ylianst, unfortunately that did not work.
I think I am making a dumb mistake somewhere with the certs. 
Checked the thumbprint of the cert and the AMT SHA1 in Meshcentral upong running amtacm > matches the Sectigo (AAA) and not the thumbprint for Sectigo_vPro_cert
![image](https://user-images.githubusercontent.com/47164919/186836751-1d3de785-8c62-4766-88b0-f779ac025f21.png)

Sectigo had provided a .cer file which I had converted to a p7b and then imported to certlm. I later exported the cert as a .pbx which I had provided to config.json

**Comment by Ylianst** [comment]
For the thumbprint, MeshCentral will show the hash of the root of the cert chain, the the hash of the leaf cert. You can use `meshcmd amthashes` to see that root hashes your Intel AMT will trust.

![image](https://user-images.githubusercontent.com/1319013/186970895-82cbb901-78bf-4922-a6e5-17ae0bca6bda.png)

![image](https://user-images.githubusercontent.com/1319013/186970717-2a5c3130-2a4c-4d09-b077-a4ec906cb810.png)

To debug the ACM activation, go in the agent console tab and type `amtconfig`. This will force the server to re-sync with the Intel AMT. It will also show real-time feedback and any error messages.

![image](https://user-images.githubusercontent.com/1319013/186971442-3c96e470-5007-4456-a528-0c9d79b2568b.png)

**Comment by aRafeymasood** [comment]
Thanks Ylianst for the quick response again. 
Running amtacm does show that the cert is loaded correctly. 
I had the cert requested for **intelamt.student.ad.domain.com** - which is where meshcentral is running. (I think this is where my problem lies)

![server certificate](https://user-images.githubusercontent.com/47164919/187099379-17071c06-a824-4e36-8dfe-a742fc90440f.png)

When I run the **amconfig** command, I am getting "No opportunity for ACM activation: No matching ACM activation certificate for student.ad.domain.com
![amtconfig](https://user-images.githubusercontent.com/47164919/187099408-1bdaf0a1-a526-4f7a-81e9-56a80a842a00.png)

Should I get the certificate for student.ad.domain.com and not intelamt.student.ad.domain.com?
I am keen to create a guide for ACM activation using DHCP 15 and activation cert [once I get mine working :)] as the information regarding this process is a bit difficult to find. Thanks

**Comment by aRafeymasood** [comment]
Cheers, Thanks Ylianst. 
Requesting a new certificate with [student.ad.domain.com](https://student.ad.domain.com/) did the trick like you said on Reddit. 
thanks heaps for all the help again :)
