### ISSUE TITLE
Webrelay - fails when using Alternate port

### ISSUE THREAD

**Issue by RadioSTech** [Ylianst/MeshCentral#4456]
Using Meshcentral version 1.0.73 on a fully updated ubuntu server with dnsrelay setup.

Added a "No agent device relayed thru agent" category and added a couple of web relay devices.

If I use the standard port (80 and 443) on the devices - then everything works as it should (every time).
If I choose to use a "Alternate port" on one of the devices (eg http and 9090) then I get a blank page with the text "Not Found".
In the trace I get the following information (tracing everything under "Core Server"):

10:33:25 - COOKIE: ERR: Bad AESSHA cookie due to exception: Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
10:33:25 - COOKIE: ERR: Bad cookie due to timeout
10:32:45 - DISPATCH: DispatchEvent, ["*"]

After I get this fault the web relay stops working for the devices using standard port that was working earlier and the following is in the trace:

10:42:48 - COOKIE: ERR: Bad AESSHA cookie due to exception: Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
10:42:48 - COOKIE: ERR: Bad cookie due to timeout
10:42:45 - DISPATCH: DispatchEvent, ["*"]

A reboot of the server and the web relay works once more for standard ports until I try to use a "Alternate Port" again.

**Comment by Ylianst** [comment]
Ok. I think I know what is going on. I will work on a fix for this.

**Comment by Ylianst** [comment]
MeshCentral v1.0.76 released with fixes to web relay. One bad bug is that if you loaded the MeshCentral web site and waited 2 minutes, web relay links would stop working. This fixes this and many other issues.

**Comment by RadioSTech** [comment]
Thanks - this is working for me now!
