### ISSUE TITLE
Login refused due to MeshCentral "updating" to v0.0.6

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#446]
I put in my credentials but login is refused.
I also have 2FA enabled.
I'm the only user.

How to fix?

**Comment by Ylianst** [comment]
Many more details are needed. Are you using your own server or the public MeshCentral.com server? What server version are you using? What mode (LAN/WAN/Hybrid) is the server in? Do other accounts work and it's just the account with 2FA? Did you just update your server?

**Comment by FATeknollogee** [comment]
Using my own server.
WAN mode.
I only have one account setup with 2FA, it has worked for the last 3+ months.
Server is set to auto update.

**Comment by FATeknollogee** [comment]
What's the cmd to find the version number?

**Comment by Ylianst** [comment]
You can find the MeshCentral server version number in the "package.json" file in the /node_modules/meshcentral folder.

What 2FA are you using? Google Authentication app? USB key? If you use a USB key, you need to connect to the server using the correct server name in the URL. So, you can't use https://localhost to access your server even if you are local. USB keys have anti-phishing system.

You can also run MeshCentral like this:

`node ./node_modules/meshcentral --user admin`

Replace "admin" with your user name. In this mode, the server will always be logged in as your account, so you can go remove 2FA if you like.

I will release a new version of the MeshCentral server will debug system in a few hours. If you update you will be able to see the problem.

**Comment by FATeknollogee** [comment]
/opt/meshcentral/node_modules/package.json is empty.

2FA is Authy

**Comment by Ylianst** [comment]
Check: /opt/meshcentral/node_modules/meshcentral/package.json

**Comment by FATeknollogee** [comment]
discard my last "empty" comment

**Comment by FATeknollogee** [comment]
meshcentral version 0.0.6

**Comment by Ylianst** [comment]
Oh. Easy fix. You have an old version. This is because of a NPM problem, just update it.

```
cd /opt/meshcentral
mv node_modules node_modules_bad
npm install meshcentral
```

**Comment by FATeknollogee** [comment]
Shouldn't auto-update have taken care of keeping me up to date?

**Comment by Ylianst** [comment]
Yes, auto-update should work, but for a few hours NPM has no versions of "meshcentral" tagged with "latest" and so, it started serving the first version ever instead. Sorry about that, you got unlucky and updated at the wrong time. Hopefully this will not happen again.

On a separate note: I don't really recommend enabling auto-update because it is better to be present when an update occurs just in case something goes bad. This said, if you keep it on and get issues, please keep posting them. I very much appreciate seeing that problems people are seeing.

**Comment by FATeknollogee** [comment]
@Ylianst Thank you sir...you d man.
It works.
I'll keep the auto update on unless you'd rather I turn it off?

**Comment by Ylianst** [comment]
Oh good. Thanks for the report. You can keep auto-update on and it should be ok. If it's a critical server, then turn auto-update off and backup "node_modules" before each manual update. This way, you can go back to a working "node_modules" if needed.
