### ISSUE TITLE
Embedding options Iframe issue

### ISSUE THREAD

**Issue by rajatheynetech** [Ylianst/MeshCentral#4461]
I'm trying to bring meshcentral device remote desktop to my react project using an iframe. But the react throws an error.

"Refused to display 'https://192.168.0.120/' in a frame because it set 'X-Frame-Options' to 'sameorigin'"

<img width="1434" alt="Screenshot 2022-08-26 at 3 56 53 PM" src="https://user-images.githubusercontent.com/67583922/187123662-e68016c6-f1e9-462d-871f-8e99b5d7bfca.png">

URL Given: https://192.168.0.120?login=xxxxxx&node=UkSNlz7t...2Sve6Srl6FltDd&viewmode=11&hide=15

**Comment by Ylianst** [comment]
In the settings section of the config.json, add the following line:

```
"allowframing": true
```

That should fix it.

**Comment by rajatheynetech** [comment]
Thank you! The iframe issue has been fixed. but showing unable to connect message on the iframe. The same URL in the browser works like a charm.
<img width="1290" alt="Screenshot 2022-08-29 at 2 25 05 PM" src="https://user-images.githubusercontent.com/67583922/187164755-765691f6-03a5-43b4-8d2c-13d7e773aab8.png">
