### ISSUE TITLE
Is Intel vPro Certificate required for OOB

### ISSUE THREAD

**Issue by SurrounDTech** [Ylianst/MeshCentral#4462]
Hi Ylianst

A while back I setup a MeshCentral environment and purchased the the Intel vPro certificate from GoDaddy and added the certificates to the config.json file and everything work correctly. At that time I asked a couple of questions here https://github.com/Ylianst/MeshCentral/issues/2320. In point 2 of your reply I take it that you only need the Intel vPro certificate if you plan to use the automatic activation ACM via option 15? I am in the process of setting up a new Mesh environment in a new domain which at the moment will only activate ACM via USB. If we are only using the USB to activate do I still require the Intel vPro certificate? Is it best practise to purchase the Intel vPro certificate anyhow?  If in the future we would like to begin using the automatic activation could I purchase one then and add it to the config.json? Thanks for your help

The config.json amtacmactiviation section without the certificate would look something like below?

```
"amtAcmActivation": {
        "log": "amtactivation.log",
        "strictCommonName": false,
        "_certs": {
          "mycertname": {
            "certfiles": [
              "amtacm-leafcert.crt",
              "amtacm-intermediate1.crt",
              "amtacm-intermediate2.crt",
              "amtacm-rootcert.crt"
            ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
```

**Comment by Ylianst** [comment]
Your correct that you do not need am Intel AMT activation certificate unless you want to activate Intel AMT into ACM mode using DHCP option 15 & the Intel AMT wired NIC (This technique does not work on platforms that are wifi only).

- In point 2 of your reply I take it that you only need the Intel vPro certificate if you plan to use the automatic activation ACM via option 15?

That is correct.

- If we are only using the USB to activate do I still require the Intel vPro certificate?

No, you do not need a Intel AMT activation certificate to do USB activation.

- If in the future we would like to begin using the automatic activation could I purchase one then and add it to the config.json? 

Yes, at any time in the future you can always add a Intel AMT activation certificate to the config.json, it's exactly the section you have highlighted.

Hope that helps.

**Comment by SurrounDTech** [comment]
Thank Ylianst, yep that answers my question and as always I appreciate your quick reply.
