### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by jdvmanen** [Ylianst/MeshCentral#4465]
Hi,

Since a few weeks, the MeshCentral doesn't update any more.

![image](https://user-images.githubusercontent.com/68591647/187287831-c670359e-1e56-4e99-b909-0c4723afab81.png)

I'f i run the update manually, it restarts the service (it is gone for about 30 seconds) and after that, it comes back with the same version installed.

I cleared the fault logging, and ran the update again. But no logging is added for the installation. 

Please can you help me what I can do to update, or to gather more information to make this issue complete?

-----
Output of diverse console  commands:
> info
{
    "meshVersion": "v1.0.34",
    "nodeVersion": "v18.8.0",
    "runMode": "WAN mode",
    "productionMode": true,
    "database": "NeDB",
    "platform": "linux",
    "arch": "x64",
    "pid": 7671,
    "uptime": 323.886503679,
    "cpuUsage": {
        "user": 11142475,
        "system": 1500390
    },
    "memoryUsage": {
        "rss": 178311168,
        "heapTotal": 62849024,
        "heapUsed": 60442680,
        "external": 30167821,
        "arrayBuffers": 29340858
    },
    "warnings": [],
    "allDevGroupManagers": []
}

> versions
{
    "node": "18.8.0",
    "v8": "10.2.154.13-node.11",
    "uv": "1.43.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "108",
    "nghttp2": "1.47.0",
    "napi": "8",
    "llhttp": "6.0.7",
    "openssl": "3.0.5+quic",
    "cldr": "41.0",
    "icu": "71.1",
    "tz": "2022a",
    "unicode": "14.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
}

> updatecheck
Checking server update...
current: 1.0.34
latest: 1.0.75
stable: 1.0.0
> showpaths
Parent:     /
Data:       /meshcentral-data
Files:      /meshcentral-files
Backup:     /meshcentral-backup
Record:     /meshcentral-recordings
WebPublic:  /node_modules/meshcentral/public
WebViews:   /node_modules/meshcentral/views

**Comment by Ylianst** [comment]
You can try a manual update an see what happens. Login to your Linux machine using SSH and navigate to the folder above "node_modules", then type:

```
node node_modules/meshcentral --stop
mv node_modules node_modules_back
npm install meshcentral
node node_modules/meshcentral
  (wait for any optional modules to install, check that server runs ok and hit ctrl-c)
node node_modules/meshcentral --start
```

Also, always have an offsite backup of `meshcentral-data`. If the manual update works, we can look into why it does not work from within MeshCentral.

**Comment by jdvmanen** [comment]
Hi Ylianst,

Thanks for the reply. I did what you asked me, but the third command (npm install meshcentral) returns an error:

```
root@vps454628:/# npm install meshcentral
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-30T05_56_34_740Z-debug-0.log
```
[2022-08-30T05_56_34_740Z-debug-0.log](https://github.com/Ylianst/MeshCentral/files/9450061/2022-08-30T05_56_34_740Z-debug-0.log)

Attached the log file.

**Comment by Ylianst** [comment]
I am not an expert on NPM, but [here is a good thread on this issue](https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for). I have not encountered it myself, not sure there is anything I can do to help solve this in MeshCentral.

**Comment by jdvmanen** [comment]
And if I completely reset the Linux installation, can I simply restore de meshcentral-data folder from the backup to be back in business again?

 

BR, (Thanks for the quick support!)

 

Dirk

 

Van: Ylian Saint-Hilaire ***@***.***> 
Verzonden: dinsdag 30 augustus 2022 10:12
Aan: Ylianst/MeshCentral ***@***.***>
CC: Dirk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Ylianst/MeshCentral] Update fails (Issue #4465)

 

I am not an expert on NPM, but here is a good thread on this issue <https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for> . I have not encountered it myself, not sure there is anything I can do to help solve this in MeshCentral.

**Comment by jdvmanen** [comment]
I've found the restore procedure in the perfect manual!  Thanks!

**Comment by Ylianst** [comment]
Nice. Thanks for reporting back and yes, if your using NeDB (the default database), all you need is a backup of "meshcentral-data" to restore your server. If you are using another database (MongoDB, MariaDB, MySQL, PostgreSQL) you need both a backup of "meshcentral-data" and you database.
