### ISSUE TITLE
new august 2022 linux agent shows wrong compile time

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4466]
**Describe the bug**
i have installed the new 1.0.75 update and then issued `agentupdate` on our linux servers
but the info tab shows the new update core correctly but the details tab shows the old compile time ?
```
> info
Current Core: Aug 29 2022, 3941939866
Agent Time: 2022-08-29 22:29:58.670+01:00.
User Rights: 0xffffffff.
Platform: linux.
Capabilities: 14.
Server URL: wss://meshcentral.myserver.com:443/agent.ashx.
OS: Virtuozzo release 7.5.3.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, linux-dhcp, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner.
Server Connection: true, State: 1.
X11 support: false.
```
```
Compile time 04/04/2022 10:22:18
```

**To Reproduce**
1. update to 1.0.75
2. issue `agentupdate` manually (i have `noagentupdate: 1` set)
3. info on the console shows new agent correctly, but details tab shows old compile time?

**Expected behavior**
for it to match the current core time+date

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] NONE
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Direct Hybrid mode, LetsEncrypt
 - Version: [e.g. 1.0.43] 1.0.75
 - Node: [e.g. 18.4.0] 16.17.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Windows 11 Home
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] Firefox
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Server
 - OS: [e.g. Windows 10 21H2] Virtuozzo 7 (Centos 7 based)
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Aug 29 2022, 3941939866

**Additional context**

**Your config.json file**
```
N/A
```

**Comment by Ylianst** [comment]
Arg. My Linux compiler machine must have the wrong time. Thanks for pointing that out.

**Comment by Ylianst** [comment]
Odd, my Linux compiling computer had the right time. Will check what is going on.

**Comment by krayon007** [comment]
What does it say if you type `versions` in the console tab?

**Comment by Ylianst** [comment]
I think there is a misunderstanding. When typing `info` you see the remote computer's current time. This has nothing to do with the agent version. To look at the agent version, type `versions` or run the `meshagent.exe --info`.

![image](https://user-images.githubusercontent.com/1319013/187327772-4dc5e6a0-baf6-4881-a057-9cf152202b81.png)

Looking at this, it all looks correct to me.

**Comment by Ylianst** [comment]
Raspberry Pi.

![image](https://user-images.githubusercontent.com/1319013/187327966-e6d4dcae-f142-453e-bcf9-bdf4df2eac43.png)

Linux x86-64.

![image](https://user-images.githubusercontent.com/1319013/187328037-5fea5bad-55d6-44f5-a92f-730c7316b26e.png)

All looks good.

**Comment by si458** [comment]
sorry for my delay (nite time here)
```
> versions
{
  "openssl": "1.1.1q",
  "duktape": "v2.6.0",
  "commitDate": "2022-08-25T07:17:18.000Z",
  "commitHash": "f221183413f39aba155c75dbb85ff72777fc8244",
  "compileTime": "10:49:00, Aug 29 2022"
}
```
![Screenshot 2022-08-30 103900](https://user-images.githubusercontent.com/765314/187404212-91b6e37a-58e6-4508-b203-dd68db2b970a.png)
you can see the compile time in versions is correct, but its wrong whern you select the `Details` tab

**Comment by Ylianst** [comment]
Oh. Got it. I will take a look at this.

**Comment by Ylianst** [comment]
Ok, I see the same issue on my Linux agent, looking into it.

![image](https://user-images.githubusercontent.com/1319013/187551094-4cbfd804-62da-4832-a376-76d0bc0dcd2b.png)

**Comment by Ylianst** [comment]
I just put in a fix for this. The entire details tab was not updating at all on Linux causing the old values to be shown.

**Comment by si458** [comment]
thanks @Ylianst the fix worked a treat, its now showing the correct date and time, closing issue...
