### ISSUE TITLE
web relay stopped working 1.0.75

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4467]
**Describe the bug**
the web relay use to work but has now stopped working in 1.0.75 for some reason,
i just keep getting a 404 `not found` error now

**To Reproduce**
1. select HTTP on a device in the web ui

**Expected behavior**
the web relay to work?

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] NA
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Direct, Hybrid, LetsEncrypt
 - Version: [e.g. 1.0.43] 1.0.75
 - Node: [e.g. 18.4.0] 16.17.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Windows 11 Home
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] Firefox
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Server
 - OS: [e.g. Windows 10 21H2] Debian 11 (openmediavault)
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): Aug 29 2022, 3941939866

**Additional context**
```
Aug 29 21:53:36 meshcentral systemd[1]: Started MeshCentral Server.
Aug 29 21:53:41 meshcentral node[66044]: MeshCentral HTTP redirection server running on port 80.
Aug 29 21:53:41 meshcentral node[66044]: MeshCentral v1.0.75, Hybrid (LAN + WAN) mode, Production mode.
Aug 29 21:53:42 meshcentral node[66044]: Code signed agent MeshService64.exe.
Aug 29 21:53:43 meshcentral node[66044]: Code signed agent MeshService.exe.
Aug 29 21:53:44 meshcentral node[66044]: MeshCentral Intel(R) AMT server running on meshcentral.mycompany.com:4433.
Aug 29 21:53:44 meshcentral node[66044]: MeshCentral HTTPS server running on meshcentral.mycompany.com:443.
Aug 29 21:53:44 meshcentral node[66044]: MeshCentral HTTPS relay server running on relay.meshcentral.mycompany.com:443.
```

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.mycompany.com",
    "port": 443,
    "noAgentUpdate": 1,
    "redirPort": 80,
    "AgentPong": 300,
    "authLog": "authlog.log",
    "relayDNS": "relay.meshcentral.mycompany.com",
    "autoBackup": {
      "backupIntervalHours": 1,
      "keepLastDaysBackup": 7,
      "backupPath": "meshcentral-backup"
    }
  },
  "domains": {
    "": {
      "title": "mycompany",
      "agentCustomization": {
        "companyName": "mycompany Ltd",
        "image": "128x128.png"
      },
      "assistantCustomization": {
        "image": "128x128.png"
      },
      "androidCustomization": {
        "image": "128x128.png"
      }
    }
  },
  "letsencrypt": {
    "email": "simon@mycompany.com",
    "names": "meshcentral.mycompany.com,relay.meshcentral.mycompany.com",
    "skipChallengeVerification": false,
    "production": true
  }
}

```

**Comment by Ylianst** [comment]
Weird. I can't think of what could cause this. Will do some testing.

**Comment by si458** [comment]
#4456 my issue seems to be the same as here after i enabled the trace and watched it

**Comment by si458** [comment]
@Ylianst ok weird?
i closed my browser, reopened it and then tried again and suddenly started working again?
i will leave issue open for 24 hours before closing in case i get the issue again

**Comment by Ylianst** [comment]
Ohh. I have an idea now as to what is going on. `COOKIE: ERR: Bad cookie due to timeout` - Of course. If you start a relay and use it for a while, it will start doing that because I am not refreshing the cookies on the relay (!!!). Ok, i will work on fixing this now.

**Comment by Ylianst** [comment]
Ok, working on this one now.

**Comment by Ylianst** [comment]
MeshCentral v1.0.76 released with fixes to web relay. One bad bug is that if you loaded the MeshCentral web site and waited 2 minutes, web relay links would stop working. This fixes this and many other issues.

**Comment by si458** [comment]
that fixed the cookie issue thanks!
