### ISSUE TITLE
Update process finish with no errors but that's not correct

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4471]
HI,
When starting the update, it finish normal. but looking at the system it shows it still running 1.0.73 and actually not updating.
I even check the console tab in the server settings and it also showing that it's version still 1.0.73.

checked the server files, couldn't find and errors been reported !!!

![image](https://user-images.githubusercontent.com/70715469/187590935-e9b05aa2-a6d2-4065-800b-bf96342cc185.png)

**Comment by smartekIT** [comment]
<pre>
 info
{
    "meshVersion": "v1.0.73",
    "nodeVersion": "v17.8.0",
    "runMode": "Hybrid (LAN + WAN) mode",
    "productionMode": true,
    "database": "MongoDB",
    "dbChangeStream": false,
    "dbBulkOperations": true,
    "plugins": [
        "devtools",
        "scripttask"
    ],
    "platform": "linux",
    "arch": "x64",
    "pid": 97351,
    "uptime": 268.29836472,
    "cpuUsage": {
        "user": 13579447,
        "system": 1549669
    },
    "memoryUsage": {
        "rss": 198602752,
        "heapTotal": 81076224,
        "heapUsed": 77905352,
        "external": 65969728,
        "arrayBuffers": 47960948
    },
    "warnings": [],
    "allDevGroupManagers": [
        "user//admin"
    ]
}
</pre>

**Comment by smartekIT** [comment]
I had to re-install meshcentral through SSH pointing to the latest version 1.0.76 which worked for me.

**Comment by si458** [comment]
> so I had to go again and do the terminal reinstall option by renaming the folder node_modules_OLD then npm install meshcentral@1.0.77

i think this might your problem, you are telling node to install a certain version and save it to `package.json`
i just upgraded my server this morning from 1.0.76 to 1.0.77 using the web ui no problems,
only different is i installed it originally the week using `npm install meshcentral`

whats the content of your `package.json`

**Comment by smartekIT** [comment]
I had to do it again using the terminal, so the json would be on 1.0.78
but i don't think what you mention is accurate, because in the past (around version 1.0.5) had to do a downgrade and i remember i used the same command by specifying the MC version in the install command, then after that was all good doing the update through the UI.
but for 1.0.76-1.0.78 it's not happening. must be something else in the code.
based on @Ylianst advise before, you can specify the version of MC in the install command and that shouldn't affect on the future update process using the UI specially if needed to downgrade for some reason at anytime.

**Comment by smartekIT** [comment]
the problem is I'm already on the latest version after I updated through SSH. but I will try it upon the next release update.

**Comment by smartekIT** [comment]
Hi @Ylianst , I did exactly what you suggested. still the same behaviour. server goes for update process and restarts, but when back. it still on the same version.

**Comment by si458** [comment]
> Hi @Ylianst , I did exactly what you suggested. still the same behaviour. server goes for update process and restarts, but when back. it still on the same version. 

Question,

how do u start meshcentral on server startup?

do u run node as a different user compared with the user u use to manually upgrade from command line?
,
What's the permission of the node_modules folder? `ls -lah` might help

I'm thinking it's a permissions problem now

**Comment by smartekIT** [comment]
regarding the files and folders permissions and structures, it has never changed on the server. MC runs as a service enabled in the background.
drwxr-xr-x 203 root root  12K Sep  3 17:12 node_modules

**Comment by smartekIT** [comment]
if it's a permission issue, then we would be able to collect error log. but this all issue happens with no errors at all.

**Comment by si458** [comment]
> regarding the files and folders permissions and structures, it has never changed on the server. MC runs as a service enabled in the background.
> drwxr-xr-x 203 root root  12K Sep  3 17:12 node_modules

What about this output `ps aux | grep meshcentral` ? Just want to check it's defo running as root?

**Comment by si458** [comment]
> if it's a permission issue, then we would be able to collect error log. but this all issue happens with no errors at all.

Not necessarily, it might be just totally ignoring the errors all together and just restarting meshcentral thinking it's updated when it hasnt

**Comment by smartekIT** [comment]
wait a second, I think I fixed it. @Ylianst I'm really sure you need to look into this as a bug.
since v1.0.73 the only changed on the server, I decided to change the server icons, so I created <code>meshcentral-web/public/images/</code> folder and put all the replacement icons there. all the icons working fine and the GUI looks good exactly how i wanted it.

because of that folder I couldn't update from GUI. 
now I renamed  <code>meshcentral-web/public/images/</code>  to
<code>meshcentral-web/public_OLD/</code>

tried to update from the GUI, all working fine.

**Comment by si458** [comment]
@smartekIT that's weird? As I don't think the icons/images has anything at all to do with the upgrade process? But maybe it does?

**Comment by smartekIT** [comment]
I know it's wired. try it your self. create these folders structures and make sure your put a complete icon sets there. I can upload that folder with it's icons with the exact naming so you guys can try it your self.

**Comment by smartekIT** [comment]
the weird thing is that the server running fine and the look of the GUI is reflecting the new icons sets with not a single problem. only the update strange behaviour. That's mad.

**Comment by smartekIT** [comment]
inside <code>meshcentral-web/public/images/</code> there is also another folder called <code>webp</code> and has some webp icons as well.

**Comment by smartekIT** [comment]
I have a feeling that this <code>webp</code> folder is the one was causing all of that. will test it again on the next release by renaming this folder only before the update process.

**Comment by si458** [comment]
@smartekIT question, why are u copying the whole images folder?
https://ylianst.github.io/MeshCentral/meshcentral/#branding-terms-of-use
the docs show you only need to copy a few files to a different folder and not to `meshcentral-web` for customization?

**Comment by smartekIT** [comment]
who said I'm copying any of the existing images?!
I'm including my images which I want to include in the GUI, and it must be with that folder structure I have otherwise it will never be included or seen by meshcentral.
<code>meshcentral-web/public/images/</code>
and
<code>meshcentral-web/public/images/webp/</code>

**Comment by si458** [comment]
> 



> who said I'm copying any of the existing images?! I'm including my images which I want to include in the GUI, and it must be with that folder structure I have, otherwise it will never be included or seen by meshcentral. `meshcentral-web/public/images/` and `meshcentral-web/public/images/webp/`

sorry to of sounded snotty, wasnt ment to be, do you have any docs/links to say you need to put the pictures in that folder?
all docs ive found say u put them into `meshcentral-data` ?

**Comment by smartekIT** [comment]
No you are fine mate, you don't need to be sorry. we are helping each other here.
@Ylianst  has said that in his YT video and I followed him step by step. It's even in the code (now i can't record which file) but it's been coded in one of the JS files to look if that folder exists then it will overwrite what's in <code>node_module/meshcentral/public/images</code>
also you can do that for:
<code>node_module/meshcentral/views/</code> which I do too by having:
<code>meshcentral-web/views/</code>

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/188276717-184e314b-7964-454b-80c9-992986196191.png)

**Comment by si458** [comment]
> No you are fine mate, you don't need to be sorry. we are helping each other here. @Ylianst has said that in his YT video and I followed him step by step. It's even in the code (now i can't record which file) but it's been coded in one of the JS files to look if that folder exists then it will overwrite what's in `node_module/meshcentral/public/images` also you can do that for: `node_module/meshcentral/views/` which I do too by having: `meshcentral-web/views/`

@silversword411 very intresting read, never realised you could copy+paste files for customization,
the docs at https://ylianst.github.io/MeshCentral/meshcentral/#branding-terms-of-use only shows logos,
can you maybe add this information to the docs for others? picture above could be included!

@smartekIT thats an amazing layout! oh wow brilliant!

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/188276822-0fefd1e2-931a-4c0d-9288-e5a1946e1660.png)

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/188276873-ff297db5-1a25-48e4-8ea4-5876c767a6e9.png)

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/188276934-003c4643-0986-4fca-81f8-84c04a7d539b.png)

**Comment by smartekIT** [comment]
![image](https://user-images.githubusercontent.com/70715469/188277000-6d22162a-7b4c-44fd-8a39-d111aceb05d4.png)

**Comment by smartekIT** [comment]
all what you need to do is:
create <code>meshcentral-web/views/</code>  put any file you need to overwrite the original located in:
<code>node_module/meshcentral/views/</code>

create <code>meshcentral-web/public/</code> put any file you need to overwrite the original located in:
<code>node_module/meshcentral/public/</code>
e.g. <code>node_module/meshcentral/public/images/</code>

<code>meshcentral-web/</code> should be in the same directory where you have the folder <code>meshcentral-data/</code>

**Comment by smartekIT** [comment]
guys you need to watch this video:
https://youtu.be/UOIjWnsxsN8

**Comment by smartekIT** [comment]
but guy, it's very important to strict to the original icons sizes before you upload yours, otherwise it won't work.
here a screenshot of the files i uploaded so far, and each has an exact dimension like the original it replaces.

![image](https://user-images.githubusercontent.com/70715469/188278238-cd54f54f-250b-4313-83ba-dfa4e91eb83c.png)

**Comment by smartekIT** [comment]
here is all my set of icons, it's nice and simple.
https://mega.nz/file/n2hREKyA#SpMNUlPZyEGtb_ijLxEDx9zAq6u3R_rtOu33CTBc4aI
