### ISSUE TITLE
MongoDB encryption

### ISSUE THREAD

**Issue by SurrounDTech** [Ylianst/MeshCentral#4472]
Hi,

I am setting up a new environment and using MongoDB for the first time (previously used the default NeDB for a small set of devices). I would like to make sure when using MongoDB that all information is encrypted where possible. My understanding is that the dbEncryptKey is only for NeDB? Is that the case for dbRecordsEncryptKey and dbRecordsDecryptKey or are they required when using MongoDB? Thanks for your help.

 - OS: Windows Server 2019
 - Mesh Version: v1.0.76
 - Node Version: v17.17.0
 - Mongo DB 6.0.1 Community

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment__": "This is a sample configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "cert": "mesh.domain.com",
    "_SQLite3": true,
    "_acebase": { "_sponsor": true },
    "mongoDb": "mongodb://127.0.0.1:27017",
    "mongoDbName": "meshcentral",
    "_mongoDbChangeStream": true,
    "_mongoDbBulkOperations": true,
    "_WANonly": true,
    "_LANonly": true,
    "_maintenanceMode": true,
    "_certificatePrivateKeyPassword": [ "password1", "password2" ],
    "_sessionTime": 60,
    "_sessionKey": "MyReallySecretPassword1",
    "_sessionSameSite": "strict",
    "_dbEncryptKey": "SecretKey",
    "dbRecordsEncryptKey": "SecretKey",
    "dbRecordsDecryptKey": "SecretKey",
    "__dbExpire": "Amount of time to keep various events in the database, in seconds. Below are the default values.",
    "_dbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    },
}
```

**Comment by Ylianst** [comment]
FYI. Fixed the config.json schema to add descriptions for 'dbEncryptKey', 'dbRecordsEncryptKey' and 'dbRecordsDecryptKey'.

**Comment by SurrounDTech** [comment]
Thanks for your clarification

**Comment by Ylianst** [comment]
So, no, once records in the DB are partly encrypted, if you remove the `dbRecordsEncryptKey` and `dbRecordsDecryptKey` keys, MeshCentral will no longer be able to read any of the encrypted data. This will result is devices with no AMT credentials, RDP/SSH/SFTP credentials will be lost, etc.

Note that if you only use `dbRecordsDecryptKey`, you will be able to read all of the records but MeshCentral write the records back un-encrypted. So then, you can do this:

```
node node_modules\meshcentral --dbexport bob.json
node node_modules\meshcentral --dbimport bob.json
```

This will export and re-import all of the data and you will have a DB will all un-encrypted records. After that, you can remove `dbRecordsDecryptKey` and be back to no-encryption at all.

Ok, hopefully that made sense.

**Comment by smartekIT** [comment]
Thanks heaps. now it makes sense.
so we can remove the Encrypt option but leaving the Decrypt option so we can export as un-encrypted data.
after that we remove the decrypt option and then we import data.
