### ISSUE TITLE
Content Security Policy: The page's settings blocked the loading of a resource ("default-src") web relay

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4474]
**Describe the bug**
after the update to 1.0.76 portainer being web relayed is no longer loading any fonts or icons
i can see in the web console error of firefox the following
```
Content Security Policy: The page's settings blocked the loading of a resource at data:font/woff2;base64,d09GMgABAAAAASvAA… ("default-src").
Content Security Policy: The page's settings blocked the loading of a resource at data:font/ttf;base64,AAEAAAAPAIAAAwBwRkZ… ("default-src"). 
Content Security Policy: The page's settings blocked the loading of a resource at data:application/vnd.ms-fontobject;base6… ("default-src"). 
downloadable font: font load failed (font-family: "Montserrat" style:normal weight:400 stretch:100 src index:1): content blocked source: data:font/woff;base64,d09GRgABAAAAAGB4ABMAAAAAqsQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcZvm6XUdERUYAAAHEAAAAHgAAAC … 
downloadable font: font load failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1): content blocked source: data:font/woff2;base64,d09GMgABAAAAAEZsAA8AAAAAsVwAAEYJAAECTQAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGiAGYACMcggEEQgKgqkkgeVlATYCJAOGd … 
downloadable font: font load failed (font-family: "Font Awesome 5 Brands" style:normal weight:400 stretch:100 src index:1): content blocked source: data:font/woff2;base64,d09GMgABAAAAASvAAA0AAAACC2AAAStmAUuGJAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGh4GYACLehEICoe7PIXtIgE2AiQDjiwLh …
```

**To Reproduce**
1. update to 1.0.76
2. port relay 9000
3. access port 9000
4. page is displayed without any icons/fonts

**Expected behavior**
icons/fonts to be shown

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] N/A
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Hybrid, Lets Encrypt, Direct
 - Version: [e.g. 1.0.43] 1.0.76
 - Node: [e.g. 18.4.0] 16.17.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Windows 11 Home
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] Firefox
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Server
 - OS: [e.g. Windows 10 21H2] Debian 11
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Aug 29 2022, 294730201

**Additional context**

**Your config.json file**
```
N/A
```

**Comment by Ylianst** [comment]
I just reverted `Content-Security-Policy` to the old value. I did some testing using Home Assistant as the web site yesterday and trying to find the best `Content-Security-Policy` value. I may try removing it completely and see if that improves things.

**Comment by Ylianst** [comment]
FYI. I got a priority request to add device paging support to handle servers with lots of devices. As soon as that is done, I will release the new version with this included.

**Comment by si458** [comment]
> FYI. I got a priority request to add device paging support to handle servers with lots of devices. As soon as that is done, I will release the new version with this included. Should be later today.

No rush! Always happy to wait :)

**Comment by Ylianst** [comment]
I am finishing up device paging support in the mobile app now and will publish.

**Comment by si458** [comment]
thanks all working again with 1.0.77!
