### ISSUE TITLE
What Domain Name is used in MEBx when using Public Server.?

### ISSUE THREAD

**Issue by wiseobs** [Ylianst/MeshCentral#4481]
Hello
A simple Question..
What Computer Domain Name is used in MEBx knowing I will be using using MeshCentral Public Server.? Or is it left blank as there is no local server?
Thank you
Adrien Richardson

**Comment by Ylianst** [comment]
In general, the computer domain name is not used by the public server, so any value is ok. If you are settings up a "Intel AMT only, no agent" device group, the MEBx computer name and domain name may be used to fill in the starting name that will show up on the MeshCentral user interface, but you can change that on the web site to any name you like.

Hope that helps.

**Comment by wiseobs** [comment]
PERFECT !! Thank you so much !!

Adrien
