### ISSUE TITLE
Errors showing in terminal after update version from 1.0.74 to latest 1.0.78

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#4483]
The below modules are repeatedly installing every time we start the server.

node-windows@0.1.4
mongodb@4.1.0...

Also it showing below error in the  GUI and Terminal.

WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed.

Screenshot.

![image](https://user-images.githubusercontent.com/65057910/188067076-4bdbba35-1bdb-4a9f-a922-3be3dbe17c29.png)

This issue is persist in below MC versions.
 1.0.78 
 1.0.77
 1.0.76
 1.0.75

 1.0.74 working fine....

**Comment by Ylianst** [comment]
Hi. To fix the two `WARNING: Failed to sign...`, try adding this line to the `settings` section:

```
"agentTimeStampServer": false
```

For the "Unable to find mongodump.exe", this is because "mongodump.exe" is not part of the MongoDB installation anymore, there is a separate .MSI installation now, [you can get it here](https://www.mongodb.com/try/download/database-tools). If you already have this installed but MeshCentral can't find it, add this to the `settings` section:

```
    "autoBackup": {
      "mongoDumpPath": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongodump.exe"
    }
```

Put the right path for your server and it should work.

For `installing node-windows and mongodb`, let me know what version of NodeJS you have, I will try to see if I can make the problem happen, but one solution is to install them manually by typing this:

```
npm install --no-package-lock --no-optional node-windows@0.1.4
npm install --no-package-lock --no-optional mongodb@4.1.0
```

You can see if there are any errors and check if it works after this. Hope this helps.

**Comment by VINISHVV** [comment]
Dear Ylian,

Please find the below version info.

> VERSIONS
{
    "node": "18.0.0",
    "v8": "10.1.124.8-node.13",
    "uv": "1.43.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "108",
    "nghttp2": "1.47.0",
    "napi": "8",
    "llhttp": "6.0.4",
    "openssl": "3.0.2+quic",
    "cldr": "41.0",
    "icu": "71.1",
    "tz": "2022a",
    "unicode": "14.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
}

**Comment by Ylianst** [comment]
This path is the same as my path: "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe".

Before putting the path and after on this screen:

![image](https://user-images.githubusercontent.com/1319013/188086793-85cc1da5-c420-4385-8e06-0febc162d58a.png)

My config.json:

```
{
  "settings": {
    "cert": "central.mesh.meshcentral.com",
    "MongoDb": "mongodb://127.0.0.1:27017/?replicaSet=rs0",
    "MongoDbName": "meshcentral",
    "MongoDbChangeStream": true,
    "MongoDbBulkOperations": true,
    "autoBackup": { "mongoDumpPath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe" },
    "Port": 443,
    "_desktopMultiplex": true,
    "RedirPort": 80,
    "_RelayPort": 888,
    "RelayDns": [ "relay1.mesh.meshcentral.com", "relay2.mesh.meshcentral.com", "relay3.mesh.meshcentral.com" ],
    "WebRTC": true,
    "SessionKey": "MyReallySecretPassword"
  },
  "domains": {
    "": {
      "title": "MeshCentral"
    }
  }
}
```

Not sure I can explain the problem. Is mongodump.exe at this path in your server? If you updated to a new version, the path may have changed.

**Comment by VINISHVV** [comment]
Dear Ylian,

Now resolved the agent sign issues and Database error.

Actually the mongodump.exe is working fine, The issue is related to the storage location mentioned in my auto backup settings( "backupPath": "E:\\M-ACCESS BACKUPS").  actually the backup location is not active due to storage unmount. 
But i feel insuch cases we need to display a message like auto backup location not found / some thing better.

**Comment by Ylianst** [comment]
Oh! Thank you for reporting the storage location problem, I will look into fixing that.

**Comment by Ylianst** [comment]
Ok, next version of MeshCentral will have a better error message for this case:

![image](https://user-images.githubusercontent.com/1319013/188238199-aef0f5a1-3ca9-4399-8880-6996f43a0b88.png)

**Comment by VINISHVV** [comment]
Thanks @Ylianst.
