### ISSUE TITLE
agentFileInfo not working with manually signed agents (meshcentral-data/agents)

### ISSUE THREAD

**Issue by kiroubel-girma** [Ylianst/MeshCentral#4488]
**Describe the bug**
I manually sign _MeshService64.exe_ (and _MeshService.exe_) and place copies under `meshcentral-data/agents` folder.
When I download the agent, file icon and details are not present.

If I don't sign but simply copy unsigned agents into the  `meshcentral-data/agents` folder, downloaded file is the original unsigned (no digital signature).

It works if `meshcentral-data/agents` folder is empty, but digital signature is the server one, which I can't use. 

**To Reproduce**
1. Copy  _MeshService64.exe_, _MeshService.exe_ from `node_modules/meshcentral/agents` into  `meshcentral-data/agents`.
2. Copy icon file _agent.ico_  into `meshcentral-data` folder.
3. Add **agentFileInfo** section to your _config.json_ file:
```
"agentFileInfo": {
        "icon": "agent.ico",
        "filedescription": "Mesh Agent"
      },
```
4. Restart meshcentral
5. Logon and download agent from a device group.
6. Check file properties of downloaded agent

**Expected behavior**
Agent file icon and description changes.

**Server Software**
 - OS: Ubuntu 22.04
 - Virtualization: no
 - Network: WAN only on a Linode VPS
 - Version: 1.0.78
 - Node: 16.17.0

**Comment by smartekIT** [comment]
You have to let the server sign them first using the built-in Authenticode which will apply the icon and file info prior signing them then it will drop the output to <code>meshcentral-data/signedagents</code>
after all of the above, if you wish to use your own signing tool and certificate, then you should take the files in <code>meshcentral-data/signedagents</code> sign them then paste them in <code>meshcentral-data/agents</code>

after doing that, when you click to download agent, then the one in <code>meshcentral-data/agents</code> will be used and it should have all your customization.

**Comment by kiroubel-girma** [comment]
I had always used the files from `node_modules/meshcentral/agents` following Ylian's youtube video instructions.
But I see now that file/icon customization happens when server restarts and signs the executables.
