### ISSUE TITLE
Assistant email notifications 

### ISSUE THREAD

**Issue by risturiz** [Ylianst/MeshCentral#4489]
Hi, any chance to have email notifications when someone request help with Meshcentral Assistant?

Thanks!

**Comment by Ylianst** [comment]
Just added support for this, will be in MeshCentral v1.0.79.

![MC2-HelpRequestEmail](https://user-images.githubusercontent.com/1319013/188247805-1a265378-dd4c-416e-8151-77ce6d25dd26.png)

Once published, please test and and let me know if it works.

**Comment by skipton1** [comment]
This works perfectly for me, thanks

**Comment by silversword411** [comment]
https://github.com/Ylianst/MeshCentral/commit/5e07d0e84dc09b45a867c3515caba4938725f2aa
