### ISSUE TITLE
Filter or search based on Public IP address

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#4495]
WAN installation
I'd like to be able to search for public IP addresses (or hostname) in the main 'my devices' tab

I have a generic meshagent on my website that I get users to download and deploy (without a mesh account).
This is shown in 'My Devices' under the generic group name, and I move the device to the appropriate group manually.

**Comment by Ylianst** [comment]
Here are the search filters you can use:

```
user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t:xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any
```

let me know if these work.

**Comment by Ylianst** [comment]
Given #4501, seems like you did not close this one.
