### ISSUE TITLE
Erro keyboard from mobile

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#4498]
**Describe the bug**
When using the mobile version, and accessing the linux terminal or windows prompt, the keyboard behavior does not behave as expected. If you execute any command and press "enter" the keyboard minimizes, operating as if it were the tab function.

**To Reproduce**
1. Go to 'website mescentral from smartphone'
2. Click on 'Any Device'
3. Click on 'Terminal'
4. type any command and hit enter

**Expected behavior**
The expected that the enter validates what was typed for the command to be executed.

**Server Software (please complete the following information):**
 - OS: Amazon Linux 2
 - Virtualization: no
 - Network: WAN
 - Version: 1.0.81
 - Node: v17.1.0

**Client Device (please complete the following information):**
 - Device: Smartphone
 - OS: Android 13
 - Network: Local to Meshcentral
 - Browser: Google Chrome/Edge
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Debian 11 / Windows 11
 - Network: Local to Meshcentral
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Comment by si458** [comment]
this doesnt appear to happen anymore? can you try the latest version 1.1.20? close if resolved
