### ISSUE TITLE
MeshAgent Crashing on Asus Tinkerboard, (TinkerOS) (ARM)

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#45]

**Comment by Ylianst** [comment]
It does seem like on the Asus Tinkerboard, trying to get random values using OpenSSL causes a segmentation fault. We tried various versions of OpenSSL (1.1.0-a, 1.1.1-a and the one built-into the OS) and they all cause this problem. We are trying to find a work around but this seems like a bad problem with this board.

**Comment by Ylianst** [comment]
Made no progress on this, so I ordered myself a TinkerBoard. Should get it in 8 to 10 days.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.5-j that fixes this finally! It took a long time time find the problem. Turns out, trying to get SMBios tables on these devices is a really bad idea.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.5-o with a full fix for this issue. Also, the agent will start fast on all platforms.
