### ISSUE TITLE
Search by IP address in devices list

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#4501]
I'd like to be able to search my devices by IP address

I have a generic mesh agent on my website which can be downloaded by anyone, and when run the device ends up in a generic group
I move to known clients where appropriate, and normally use public IP address ( or Hostname on the General tab)

It would be nice to be able to search by this public IP address

**Comment by Ylianst** [comment]
The filter box has the following options, let me know if this works:

```
user:xxx or u:xxx
ip:xxx
group:xxx or g:xxx
tag:xxx or t:xxx
atag:xxx or a:xxx
os:xxx
amt:xxx
desc:xxx
wsc:ok
wsc:noav
wsc:noupdate
wsc:nofirewall
wsc:any
```

**Comment by OutbackMatt** [comment]
excellent thanks
