### ISSUE TITLE
low res image switch when another user connects to PC preview

### ISSUE THREAD

**Issue by drlight17** [Ylianst/MeshCentral#4509]
**Describe the bug**
low resolution of PC console when another meshcentral user connects to the same PC console in preview mode

**To Reproduce**
1. Connect to MeshCentral with two different users (the same from different session has no issues)
2. The first user connects to selected PC
3. The second user goes to My devices (screens view type) and clicks on selected PC (which is using by the first user) to show it's preview 
4. The first user will immediately see the degraded low res image

**Expected behavior**
quality of image must not change

**Screenshots**
![image](https://user-images.githubusercontent.com/37434652/188566770-f08f5593-761d-486a-9a6d-c14c28fd4afa.png)
![image](https://user-images.githubusercontent.com/37434652/188566669-6ac721e8-d55b-4833-b239-50252250728c.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Virtualization: LXC container
 - Network: LAN/WAN hybrid mode
 - Version: 1.0.78
 - Node: 12.22.9

**Comment by Ylianst** [comment]
The MeshAgent has only one "screen grabber" so you can have multiple users fighting for what resolution the grabber should be using. however, add this line in the "settings" section of the config.json:

```
"desktopMultiplex": true,
```

This will have the server read the remote desktop stream and "split-it", [I have a video about this here](https://www.youtube.com/watch?v=r0IfzuZgf3s). This will solve your problem.

**Comment by drlight17** [comment]
> The MeshAgent has only one "screen grabber" so you can have multiple users fighting for what resolution the grabber should be using. however, add this line in the "settings" section of the config.json:
> 
> ```
> "desktopMultiplex": true
> ```
> 
> This will have the server read the remote desktop stream and "split-it", [I have a video about this here](https://www.youtube.com/watch?v=r0IfzuZgf3s). This will solve your problem.

Oh, sorry, I missed this. Thank you!
