### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#4510]
I was just having a browse through the User's Guide and noticed its quite a bit out of date. 

Is there any plans on updating this soon? 

I was looking at the one here 
https://meshcentral.com/info/docs/MeshCentral2UserGuide.pdf

There have been a lot of new features over the last 2 years and with my terrible memory i cannot remember what half of them were 

Kind Regards,

Vit

**Comment by silversword411** [comment]
The pdfs are old. This is the latest info:

https://ylianst.github.io/MeshCentral/

They're built from https://github.com/Ylianst/MeshCentral/tree/master/docs/docs

If you see something you can improve, please PR updates there.

**Comment by Ylianst** [comment]
Indeed, I have not updates the PDF documents in a long time, @silversword411 link is more up to date. I am going on vacation for 6 weeks now, but later this year I need to look into this more. Probably move over to [https://ylianst.github.io/MeshCentral/](https://ylianst.github.io/MeshCentral/).
