### ISSUE TITLE
wrong file version tag

### ISSUE THREAD

**Issue by titrax35** [Ylianst/MeshCentral#4512]
**Describe the bug**
We use version 1.0.18 of meshcentral and now, when I create a executable file, the file version is : 0.0.0.0

**To Reproduce**
1. Go to a group of computer
2. Click on 'Add agent'
4. Right click on the exe file and go to properties an details

**Screenshots**

![image](https://user-images.githubusercontent.com/50879104/188656170-6d74a654-a8e8-49af-befb-efee18abca99.png)

**Server Software (please complete the following information):**
 - OS: debian 10.11
 - Virtualization: no
 - Version: 1.0.18

**Comment by Ylianst** [comment]
Now that MeshCentral customizes and signs the agent, you can set that value to anything you like. Put this in the domain section of the config.json:

```
      "agentFileInfo": {
        "filedescription": "sample_filedescription",
        "fileversion": "0.1.2.3",
        "internalname": "sample_internalname",
        "legalcopyright": "sample_legalcopyright",
        "originalfilename": "sample_originalfilename",
        "productname": "sample_productname",
        "productversion": "v0.1.2.3"
      }
```

That will customize the fields.

**Comment by titrax35** [comment]
Thanks, this work fine.
