### ISSUE TITLE
Add bios serial number

### ISSUE THREAD

**Issue by phorcys420** [Ylianst/MeshCentral#4513]
**Is your feature request related to a problem? Please describe.**
I would like to be able to get the BIOS' serial number from MeshCentral.

**Describe the solution you'd like**
I would like a "Serial number" field under the "BIOS" category in an agent's details.

**Describe alternatives you've considered**
I have considered using the motherboard's serial number, but OEMs usually ask for the BIOS one (especially for warranty/RMA requests).

**Additional context**
Some OEMs (e.g Lenovo) set the motherboard's serial number equal to the BIOS one, but some don't (e.g HP).
The serial number i'm reffering to can be found using the following WMIC query : ``wmic bios get serialnumber``

Here is what I would be talking about (sorry for the french, but I think you see where I'm going at) ("Numéro de série" = "Serial number") :
![image](https://user-images.githubusercontent.com/57866459/188666082-932b34b0-b4f0-4de8-966b-5022e6f7fb33.png)

**Comment by phorcys420** [comment]
whoops

**Comment by si458** [comment]
@phorcys420 PR for you there, but its only windows devices for now
as when i try setting `bios_serial` for linux on my proxmox vm,
it sets `product_serial` instead so im not sure if thats right or not?
