### ISSUE TITLE
meshcentral.js Assignment to constant variable

### ISSUE THREAD

**Issue by KlyuevM** [Ylianst/MeshCentral#4519]
Error in meshcentral.js
line 2458
  const state = obj.peerConnectivityByNode[serverid][nodeid];

With this line server peers not working, error:
TypeError: Assignment to constant variable.
Error: Command failed: /usr/local/bin/node /home/klyuev_m/node_modules/meshcentral --launch 8943
/home/klyuev_m/node_modules/meshcentral/meshcentral.js:2465
                obj.peerConnectivityByNode[serverid][nodeid] = state = { connectivity: connectType, meshid: meshid };
----------------------------------------------------------- ^

I think, it should be
  var state = obj.peerConnectivityByNode[serverid][nodeid];

**Comment by Ylianst** [comment]
Should be fixed in just released v1.0.85.
