### ISSUE TITLE
Issue adding purchased SSL cert to MeshCentral server

### ISSUE THREAD

**Issue by kfear27** [Ylianst/MeshCentral#452]
I've purchased an SSL cert for my MeshCentral server and replaced the webserver-cert-public.crt and webserver-cert-public.key with the new, however the cert is still throwing errors as invalid.

How do I have the server use the new SSL certs?

Thanks

**Comment by GRIFFCOMMca** [comment]
I assumued it was a copy / paste, so am interesting to see how this works as i also need to purchase one

**Comment by kfear27** [comment]
Hi, I cleared all of the crt files and keys and let the server regenerate the self assigned, I then added the purchased one again and seems to have worked this time. Strange, however thanks for the response!
