### ISSUE TITLE
record memory usage

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#4525]
Is there a way to record memory usage on a remote machine while not connected.  The current graph only shows 100 seconds and doesn't seem to store anywhere

**Comment by silversword411** [comment]
Sounds like you need an RMM
https://github.com/amidaware/tacticalrmm

**Comment by si458** [comment]
> > Sounds like you need an RMM https://github.com/amidaware/tacticalrmm
> 
> Can of worms i was really hoping not to open.
> 
> Is there anything built into current mesh central for long term montioring of memory. We think we have a memory leak but can not reproduce in house.

sadly not, meshcentral is really only for remote support, not remote monitoring, so indeed an RMM is needed in your case

**Comment by VINISHVV** [comment]
Tactical RMM is good, but it doesn't support the integration of existing meshcentral with customized agents. I have opened a case for the same but sadly its still pending
