### ISSUE TITLE
Change port in ssh connection

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#4526]
Hello all,

I have some devices in "no agent" group, but for reasons of security port "22" is blocked
when I changed port to "2234" and try to connect with my ssh-key I see error: "Authentication Error"
my config.json:

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "relayPort": 453
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "mstsc": true,
      "ssh": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

![image](https://user-images.githubusercontent.com/113111597/189123035-2da9e0fd-ae50-4187-89b4-9df105544dba.png)

**Comment by silversword411** [comment]
You understand all those json keys starting with an underscore _

Are ignored right?

**Comment by dinger1986** [comment]
> Hello all,
> 
> I have some devices in "no agent" group, but for reasons of security port "22" is blocked when I changed port to "2234" and try to connect with my ssh-key I see error: "Authentication Error" my config.json:

Have you tried it without an key? as in on a machine that doesnt have a key setup. Also is that the key thats on the machine? does it work with putty?

**Comment by mstrhakr** [comment]
> You understand all those json keys starting with an underscore _
> 
> Are ignored right?

Here is the full config MeshCentral is seeing.

```json
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "relayPort": 453
  },
  "domains": {
    "": {
      "mstsc": true,
      "ssh": true
    }
  }
}
```

With that said, it seems fine. Check the most recent logs to see if you can get any more information as to what went wrong, otherwise I would run MeshCentral with a `"debug": true` under settings in the config file to get some deeper information as to what's happening besides, Authentication Error.

**Comment by Seimavi** [comment]
> > You understand all those json keys starting with an underscore _
> > Are ignored right?
> 
> Here is the full config MeshCentral is seeing.
> 
> ```json
> {
>   "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
>   "settings": {
>     "relayPort": 453
>   },
>   "domains": {
>     "": {
>       "mstsc": true,
>       "ssh": true
>     }
>   }
> }
> ```
> 
> With that said, it seems fine. Check the most recent logs to see if you can get any more information as to what went wrong, otherwise I would run MeshCentral with a `"debug": true` under settings in the config file to get some deeper information as to what's happening besides, Authentication Error.

thank you for answer, I did it 
I see "admin" in the log, but I don't understand why it's "admin" when I try to connect as "vasyl.pashko"

WEBREQUEST: (192.168.7.80) /agent.ashx/.websocket
AGENT: New agent at 192.168.7.80:54713
AGENT: Verified agent connection to rQfHgkKvEOoUE0v17o3QHUFt@2bV1FixfpiswpiaajNGziQgZKWRiLYYrRk5jtLc (192.168.7.80:54713).
DISPATCH: DispatchEvent [
  'node//rQfHgkKvEOoUE0v17o3QHUFt@2bV1FixfpiswpiaajNGziQgZKWRiLYYrRk5jtLc',
  '*',
  'mesh//qLI5@RcZl2QehttJMrYcBD0AkoOL6kc0FIVzKYtgbgDxhQoiNyF1Xz8E@LTH05lg'
]
DISPATCH: DispatchEvent [
  'node//rQfHgkKvEOoUE0v17o3QHUFt@2bV1FixfpiswpiaajNGziQgZKWRiLYYrRk5jtLc',
  '*',
  'mesh//qLI5@RcZl2QehttJMrYcBD0AkoOL6kc0FIVzKYtgbgDxhQoiNyF1Xz8E@LTH05lg'
]
COOKIE: Encoded AESGCM cookie: {"userid":"user//admin","domainid":"","nodeid":"node//C7hIvgWaU7a4Hfd4wXAXO1j24vXKoE9ULCtEMrPlsp5rHX0TzKpZd7Ers@zIE0JT","tcpport":2234,"lc":1,"time":1662708703}
RELAY: SSH: Connection websocket to wss://localhost:443/localrelay.ashx?p=11&auth=RBB69a8eeQR7d1E8uqF41mKunDMTcuBXizfmvaTRFoqeKYvGm154gjB9ohq57DZ8wuVm78ts8MEBqU36pvGX3ag06Ui$o@KJbw$fCD6zOL4H4T9ONubxCvObv7J$XgeNPebyWiOSe1QNk2yohSMsMDm2gsQ2qlu7mx33c@Fi9k79LCaJTo3XIv1$V3xBxp@5rWy3sUcn8$KVe1i3CZ5Zr9umWBRjxfxJJzoXysqSwD8E6JXHVrtuIWAKmvo=
HTTPHEADERS: GET /localrelay.ashx/.websocket?p=11&auth=RBB69a8eeQR7d1E8uqF41mKunDMTcuBXizfmvaTRFoqeKYvGm154gjB9ohq57DZ8wuVm78ts8MEBqU36pvGX3ag06Ui$o@KJbw$fCD6zOL4H4T9ONubxCvObv7J$XgeNPebyWiOSe1QNk2yohSMsMDm2gsQ2qlu7mx33c@Fi9k79LCaJTo3XIv1$V3xBxp@5rWy3sUcn8$KVe1i3CZ5Zr9umWBRjxfxJJzoXysqSwD8E6JXHVrtuIWAKmvo= {
  'sec-websocket-version': '13',
  'sec-websocket-key': 'IkK3dnWZC2nLJtdMfB/T5A==',
  connection: 'Upgrade',
  upgrade: 'websocket',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
  host: 'localhost:443'
}
WEBREQUEST: (127.0.0.1) /localrelay.ashx/.websocket?p=11&auth=RBB69a8eeQR7d1E8uqF41mKunDMTcuBXizfmvaTRFoqeKYvGm154gjB9ohq57DZ8wuVm78ts8MEBqU36pvGX3ag06Ui$o@KJbw$fCD6zOL4H4T9ONubxCvObv7J$XgeNPebyWiOSe1QNk2yohSMsMDm2gsQ2qlu7mx33c@Fi9k79LCaJTo3XIv1$V3xBxp@5rWy3sUcn8$KVe1i3CZ5Zr9umWBRjxfxJJzoXysqSwD8E6JXHVrtuIWAKmvo=
COOKIE: Decoded AESGCM cookie: {"userid":"user//admin","domainid":"","nodeid":"node//C7hIvgWaU7a4Hfd4wXAXO1j24vXKoE9ULCtEMrPlsp5rHX0TzKpZd7Ers@zIE0JT","tcpport":2234,"lc":1,"time":1662708703000,"dtime":130}
RELAY: SSH: Relay websocket open
DISPATCH: DispatchEvent [
  '*',
  'user//admin',
  'mesh//Bue$l@29KAv2adPTiGqHHRup8FeBmUnXVQ3QssazP1rDOcKHpTRKDmsS$pphDsxs',
  'node//C7hIvgWaU7a4Hfd4wXAXO1j24vXKoE9ULCtEMrPlsp5rHX0TzKpZd7Ers@zIE0JT'
]
RELAY: LocalRelay: Soft disconnect
DISPATCH: DispatchEvent [ '*', 'user//admin' ]
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: '192.168.7.3',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'VP72a3CgSN0si4HMduaUaA==',
  'sec-websocket-version': '13'

**Comment by mstrhakr** [comment]
Well the admin bit is referencing your MeshCentral user, but I'm not sure how this feature is meant to work and I don't see any logs related to the actual SSH connection attempt.
You may have to wait for someone else to help you but I'll try to look into this more in the meantime to see if I can find out how it's meant to work.

**Comment by mstrhakr** [comment]
Ok I just saw this part
```
COOKIE: Decoded AESGCM cookie: {"userid":"user//admin","domainid":"","nodeid":"node//C7hIvgWaU7a4Hfd4wXAXO1j24vXKoE9ULCtEMrPlsp5rHX0TzKpZd7Ers@zIE0JT","tcpport":2234,"lc":1,"time":1662708703000,"dtime":130}
RELAY: SSH: Relay websocket open
DISPATCH: DispatchEvent [
  '*',
  'user//admin',
  'mesh//Bue$l@29KAv2adPTiGqHHRup8FeBmUnXVQ3QssazP1rDOcKHpTRKDmsS$pphDsxs',
  'node//C7hIvgWaU7a4Hfd4wXAXO1j24vXKoE9ULCtEMrPlsp5rHX0TzKpZd7Ers@zIE0JT'
]
RELAY: LocalRelay: Soft disconnect
```
First is connects to the right port: `"tcpport":2234`
Then opening the relay: `RELAY: SSH: Relay websocket open`
Then it's disconnecting: `RELAY: LocalRelay: Soft disconnect`

It seems like whatever error you're getting is happening behind the scenes and not being reported to the logs.

I'll keep digging to see if I can figure out how this is supposed to work.

**Comment by mstrhakr** [comment]
> > Hello all,
> > 
> > I have some devices in "no agent" group, but for reasons of security port "22" is blocked when I changed port to "2234" and try to connect with my ssh-key I see error: "Authentication Error" my config.json:
> 
> Have you tried it without an key? as in on a machine that doesnt have a key setup. Also is that the key thats on the machine? does it work with putty?

Also this is fair, have you confirmed that this key/client combo works outside MeshCentral?

If you have then I have more digging to do still lol.

**Comment by Seimavi** [comment]
Hi @mstrhakr  
It is very interesting situation, beacause my key works via powel shell, when I write something like "ssh -p 2234 user@ip" but this key doesn't work in meshcentral.

I ask my friend that he used him key and it works.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
