### ISSUE TITLE
Scroll To Top in the lists pages

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#4529]
Hi,
It would be nice to have Scroll-To-Top Flash sort of button in the pages with lists, like devices, groups. .. etc.

Thanks

**Comment by si458** [comment]
not pretty but functional!

![image](https://github.com/Ylianst/MeshCentral/assets/765314/b82c666d-c8a6-451e-a9f4-43d7653e66cb)

![image](https://github.com/Ylianst/MeshCentral/assets/765314/bc90e387-9d17-492f-9fba-08cd152b7a4e)

**Comment by Ylianst** [comment]
For now, I added a new option in domain section of the config.json:

{
  "scrollToTop": true
}

By default it's false since most people will likely not need this.
