### ISSUE TITLE
Midnight Commander (mc) support

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#453]
Hello.

When i try to run mc (linux), it is running, but i cannot move the cursor, and that means there is no way how to navigate. Sometimes it is a very useful tool. Can you support it?
Thanks

**Comment by pczolee** [comment]
Thanks, if I can help to do anything (test etc) let me know.

**Comment by axelandy** [comment]
Midnight Commander works when launched using `TERM=ansi  mc`
The Serial-over LAN Terminal doesn't seem to send any codes for the Page Up, Page Down, Home, and/or End keys though.   It would be nice if it did.

**Comment by pczolee** [comment]
Thanks. Yes, works better, but still not perfect. But for example with TERM=linux the Page Up, Page Down etc working, but there are a few character problem. And the mcedit hangs :( with both.

**Comment by GusevVictor** [comment]
Please fix that problem or switch to another terminal. :) Program is very nice but terminal no.
