### ISSUE TITLE
OOM then click devicepowerevents.ashx link

### ISSUE THREAD

**Issue by alex-eri** [Ylianst/MeshCentral#4532]
**Describe the bug**
Then i click download icon near power statistics server become ureachable for 10 minutes (even ssh not work).

4 agents conected. Using internal database.

**Server Software (please complete the following information):**
 - OS: Debian 11 
 - Virtualization: kvm
 - Network: ssl ofload on nginx
 - Version: v1.0.72
 - Node: v12.22.12

**Client Device (please complete the following information):**
 - Device: PC
 - OS: Archlinux 
 - Network: Remote
 - Browser: Google Chrome
 - MeshCentralRouter Version: no

**Remote Device (please complete the following information):**
 - Device: Raspberry 3B
 - OS: Raspbian 11
 - Network: lte modem
 - Current Core Version (if known):  Apr 4 2022, 597287619

**Your config.json file**
```
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "lic.*****.**",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "******",
    "port": 444,
    "aliasPort": 443,
    "redirPort": 81,
    "redirAliasPort": 80,
    "TlsOffload": "127.0.0.1",
    "relayPort": 453,
    "relayAliasPort": 454
  },
  "domains": {
    "": {
      "title": "* management server",
      "_title2": "* management server",
      "_minify": true,
      "newAccounts": true,
      "userNameIsEmail": true,
      "certUrl": "https://127.0.0.1:443/"
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "sa@eri.su",
    "names": "lic.******.**",
    "production": true
  }
}
```

**Comment by si458** [comment]
closing as stale,
please try again with the latest version 1.1.20 and use node 18 or above,
if the issue still persists, please reply back
