### ISSUE TITLE
Abnormal computer names in groups.

### ISSUE THREAD

**Issue by uzmanager2** [Ylianst/MeshCentral#4533]
Hello .

We have a MeshCentral server deployed. Created groups for different computers.
Unknown computers not from our network began to appear in groups. 
Only one non-standard port is open outside for connecting agents using the AgentAliasPort directive.
AgentAliasPort: 34266

Only this one port is forwarded outside.
It is very strange .
It looks like this - see the screenshot.

<img width="1119" alt="MeshAgent" src="https://user-images.githubusercontent.com/46650350/189317124-a810503f-d15c-49ab-a406-9df94b2c8e2f.PNG">

The agent is distributed only within our internal network - automatically.
Nobody shared links to the agent.

**Comment by dinger1986** [comment]
Looks to me like these are sandboxed agents from an AV, presumably they have never been online?

**Comment by si458** [comment]
https://ylianst.github.io/MeshCentral/faq/ might be help

**Comment by uzmanager2** [comment]
Thank you for information .
