### ISSUE TITLE
server rights for user groups and specific account functions

### ISSUE THREAD

**Issue by drlight17** [Ylianst/MeshCentral#4534]
Hello!
I didn't find any way to turn off user server rights on some specific functions, not all account controls. For example, to turn off only change email, change password and delete account functions and leave the others.
And also, I didn't find any way to assign server rights on a group of users, not just specific user. Or for all users of server by default.
For now I hide all these functions for all users by using css, but I don't like this method
Are there any way to do mentioned things?

**Comment by dinger1986** [comment]
you mean in `My Account`?

**Comment by drlight17** [comment]
> you mean in `My Account`?

Yes

**Comment by dinger1986** [comment]
I cant see anything in https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json which would do this, feel free to take a look as well, if not it would be worth closing this and filling in a feature request following the template

**Comment by drlight17** [comment]
I've looked through this config and didnt't see anything too. Ok, I will.
