### ISSUE TITLE
Input not working in Edge browser on remote client's desktop

### ISSUE THREAD

**Issue by mschubeck** [Ylianst/MeshCentral#454]
If connected to remote client desktop and they are using the Edge browser, keyboard input does not work within the browser.  The address bar is accessible, but any dialog boxes or forms on the webpage don't render any keyboard input.  Sending clipboard text does work, provided the "Paste" context menu is enabled, but <Ctrl>+V does not.  It appears that this is the only place that keyboard text isn't working... works fine in other browsers and applications (Notepad, Word, Excel, Outlook, etc.).

This hasn't worked for several versions, and not sure how far back is goes but it's been many weeks.  I'm just now opening a bug report after updating to 0.4.0-b and it's still present.

**Comment by krayon007** [comment]
What version of the Edge browser are you using?
I'm using 42.17134.1.0 and input seems to be working well.

**Comment by PathfinderNetworks** [comment]
44.18362.267.0. The version in Win 10 release 1903.  Looks like your version, 42.17134.1.0 is a couple releases behind what is current. That version is from April of 2018 (so Win 10 release 1803).  But I'm fairly sure (but not 100% certain) I saw this in at least version 44.17763.

**Comment by krayon007** [comment]
Ok, I was putting together some new OS test images, so I'll make sure to test Edge...

**Comment by PathfinderNetworks** [comment]
Just wanted to follow up on this one to see if any progress has been made?  I was working in a few machines this evening and noticed I still couldn't type within an Edge window.

**Comment by PathfinderNetworks** [comment]
I know this is an old issue but did want to give an update to it.  The new Chromium based version of Microsoft Edge does not have this issue.  As soon as you update to this new version the text entry works correctly when remoted in via MeshCentral.

**Comment by si458** [comment]
closing as edge is now chrome based and all works correctly
