### ISSUE TITLE
Agent installation type

### ISSUE THREAD

**Issue by salmanelalhi** [Ylianst/MeshCentral#4541]
**Describe the bug**
After enabling invite codes as super admin, I set an invite code and select the installation type to be "Background only". However, when logged in as another admin user the invite code popup shows the installation type as "Interactive only". Seems only a cosmetic bug as the .exe downloaded is of the correct type i.e. "Background only" as intended by the super admin.

**To Reproduce**
As described above

**Expected behavior**
The invite code popup should show the same installation type as selected while enabling invite codes.

**Screenshots**

![Invite-super-admin](https://user-images.githubusercontent.com/15675632/189598289-b794f065-7181-4255-a1b2-9115541e80ae.PNG)

![Invite-another-admin](https://user-images.githubusercontent.com/15675632/189598608-a7893ab0-58eb-406d-bbca-7b3f4f4ed880.PNG)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: n/a
 - Network: WAN
 - Version: 1.0.85
 - Node: 18.8.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
oh wow yep can confirm this bug! 
will look into it soon

**Comment by si458** [comment]
all fixed! will be available in docker `master` image and `npm install Ylianst/MeshCentral` develop builds in 15mins
