### ISSUE TITLE
Remote Input Lock - Button only appears if I connect directly

### ISSUE THREAD

**Issue by KommunistGangsta** [Ylianst/MeshCentral#4542]
**Describe the bug**
Hello, there is a slight bug (i think it's a bug and not intended), is that when I'm in "My Devices", and with Desktop Views (Grid with all desktop connected), when I click the device, and open its Desktop remote, the "Remote Input Lock" button does not show.
For it to appear, you must Disconnect your session, and Connect again, and now that button will show up.
It's nothing critical, but a bit annoying, since most of my users won't stop overriding my remote, so this functionality to lock Inputs is awesome, but Reconnecting and Connecting is kind of annoying.

**To Reproduce**
1. Go to 'My Devices', use 'Desktops' view.
2. You can use 'Connect All', or simply connect a single device, with a left-click on it's square.
3. Click on the Device Name (or right click and open Desktop), and open the device Desktop
4. Now that you open, you will see that the Remote Input Lock button is missing.
5. click 'Disconnect' and then click 'Connect' (basically reconnect with a new session)
6. Voilá, the Remote Input Lock button now shows up (bottom right corner).

**Expected behavior**
I expect the button to be visible, when I open the remote desktop from the 'My Devices' view.
Seems counter-logic to have missing buttons, when a session is opened through that view.

**Screenshots**
![image](https://user-images.githubusercontent.com/98977577/189619755-f7e27583-b7a7-436c-8592-504f170bfc03.png)

![image](https://user-images.githubusercontent.com/98977577/189619803-a8ae5585-eb4e-44e4-8268-46f00a57e414.png)

![image](https://user-images.githubusercontent.com/98977577/189619869-59f447a2-ecde-429b-a5ef-0071b6b004cb.png)

After 'Disconnect' and 'Connect' (reconnecting)
![image](https://user-images.githubusercontent.com/98977577/189619913-726dfd87-989d-4af6-9fa0-efd9850d6c25.png)

**Server Software (please complete the following information):**
 - OS: Windows Server 2016
 - Virtualization: Hyper-V
 - Network: WAN
 - Version: 1.0.85
 - Node: 12.16.2

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 21H2
 - Network: Local Network to Meshcentral
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 21H2
 - Network: Local Network to Meshcentral
 - Browser: Google Chrome
 - Current Core Version (if known): Aug 25 2022, 1360394467

**Your config.json file**
```
{
   "settings": {
      "_minify": true, 
      "cert": "srvmeshcentral.xxxxxxx.local", 
      "minify": true
   }, 
   "domains": {
      "": {
         "title": "SCML", 
         "newaccounts": false
      }
   }
}
```

**Comment by si458** [comment]
oh yeh how weird i see it too!
will look at it soon

**Comment by si458** [comment]
all fixed! better late then ever!
will be available in docker `master` image and `npm install Ylianst/MeshCentral` develop in about 15mins
