### ISSUE TITLE
not update 

### ISSUE THREAD

**Issue by gosteras** [Ylianst/MeshCentral#4544]
![изображение](https://user-images.githubusercontent.com/95762246/189664622-afc3bf8c-4f6e-4a9f-b376-781676666596.png)

not update

**Comment by dinger1986** [comment]
can you explain better? what you are trying to do etc

**Comment by gosteras** [comment]
I check the checkbox to update, but it does not update

**Comment by si458** [comment]
**Please can you fill out the bug report template in the future to help us help you easier**

What is your `config.json`?

What is your node js version?

What is your operating system?

**Comment by PathfinderNetworks** [comment]
You can manually update MeshCentral by logging in to your server and running this command at an elevated prompt and at the root of your MeshCentral installation folder :
`npm install meshcentral`

**Comment by gosteras** [comment]
![изображение](https://user-images.githubusercontent.com/95762246/189826301-6a9ef492-96f0-4379-9bab-486c3cdf6df5.png)

**Comment by gosteras** [comment]
all ok. thanks
