### ISSUE TITLE
"Show only own events" not as expected

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#4547]
Looks like "Show only own events" is not working correctly.

![image](https://user-images.githubusercontent.com/59362521/189705740-121cdcbb-128d-4e81-8f25-89d99d284858.png)

Option to show own events only is ON:
![image](https://user-images.githubusercontent.com/59362521/189706323-a09ea81a-166c-4baf-9578-7fd472bcf15c.png)

Steps to reproduce:
Using admin account created "testtest" account, assigned rights for the devices and logged in to MC using "testtest" account

On the events tab appearing my original administrator name "LetsSaysSomethingSpecial" and changes made to testtest account.

Expectation:
Events created and/or triggered by "testtest" account to appear on the events tab, not those ones from the administrator account?

MC version: 1.0.85 - currently latest
Running on Debian Jessie
Node: 10.16.2

**Comment by vitko-bg** [comment]
Any update on this?

**Comment by vitko-bg** [comment]
Any update please? @Ylianst can you help with this issue please? Thanks.

**Comment by vitko-bg** [comment]
Any update on this issue please?
The issue still persist in v.1.1.15

**Comment by si458** [comment]
this is correct, because you see your own events, but you also see any 'admin events' that an admin account did to your account!
this is sort of a security feature, as an admin account, could change ur permission to say view other devices you shouldnt be able to see? and you could then check/verify WHEN this happened as it could be a hack attack!

**Comment by vitko-bg** [comment]
Well ..... @si458 try to see it from my point of view and you will understand.
I am not quite agree with your statement, as this is opposite to security feature. Because to stay secure I am using login name which is "SomethingSecret", not Admin, not Administrator -  and in this case users can see my login name and all what needs to be guessed is password. So in my eyes it is completely opposite to security feature. 
May this then will be an option in server configuration to choose if admin events should be visible from users side or not.
"Show only own events" should show only users events, not done by Admin or anyone else.

**Comment by vitko-bg** [comment]
Ideally would like "Show only own events" to show only users events, not events done by someone else. Hope this can be achieved. Will leave you or @Ylianst to decide.

**Comment by vitko-bg** [comment]
Just checking if any update on this issue? Thanks.

**Comment by si458** [comment]
no because this isnt a bug, but a feature request,
because generally you WOULD want to see if an admin changed anything on ur account.
so im going to close this for now and follow #6136 for updates
