### ISSUE TITLE
Changes in config.json are ignored

### ISSUE THREAD

**Issue by VenoushCZ** [Ylianst/MeshCentral#4551]
Hi,

I am running Windows installation via MSI.

I tried to modify the title. The config.json looks like this now:

```
{
  "settings": {
    "cert": "xxx.xxx.xxx",
    "_minify": true
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_newAccounts": true
	}
  }
}
```

I restart the service. The domains portion is being ignored. The title stays default "MeshCentral"

Please do you have any idea why it is happening?

Thank you

VCZ

**Comment by si458** [comment]
Anything in json which starts with an underscore is ignored,

so simply remove the underscore

E.g `_title` to `title`

**Comment by VenoushCZ** [comment]
Silly me, thank you :-)
