### ISSUE TITLE
SMTP reset password

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#457]
Hi,
I just wanted to help if someone has had the same issue as it does not show the reset password  on the user manual says if Note that if a user performs a password recovery using email, the 2-step authentication is then
turned off and will need to be turned on again.
To test that theory i wanted to reset the password but i could not find the option to reset the password. 
To follow the steps this is what i did
apt install npm

npm install nodemailer

then in the config remove the _ from the smtp and configure the lines

      "smtp": {
        "host": "mail.mydomain.com",
       "port": 587,
       "from": "myemail@mydomain.com",
       "user": "myusernameofemail",
       "pass": "mypasswordl",
       "tls": true
     }
    }

and restart the server 

Hope this helps

**Comment by killmasta93** [comment]
Thanks for the reply, yes your right the 2FA needs to stay even after reset password but lets say im the admin, and i have a user does not have admin rights but has 2FA and his phone gets stolen and lets say he didnt take a photo of the codes or lets say worst case scenario he changed the codes or something like that. Shouldn't the admin have full control even when 2FA is enabled?

**Comment by Ylianst** [comment]
If you are administrator, you can clear 2FA for a user account. Go in "My Users" tab, then click on a user and hit "Change Password". Leave the new password fields blank so you don't change it, but select "Remove all 2nd factor auth". That should do it.

![x](https://user-images.githubusercontent.com/1319013/65015055-4cd26000-d8d5-11e9-9230-25f9245f4a92.png)
