### ISSUE TITLE
Duplicating Computers

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#4576]
I created a new MeshCentral instance. Customised the agent to give it a new service name etc 

I've found on the new portal the computers are duplicating and somehow the original client is also connecting to the new server. 

Running uninstall agent throws this message. 

> uninstallagent
Command returned an exception error: systemd Service (undefined) NOT FOUND
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: systemd Service (undefined) NOT FOUND in method 'handleServerCommand()'

Is there any way i can manually remove the client completely from the computers / servers. 

Connecting between the two different duplicates in terminal view takes me to two different folder paths. 

root@erpnext-production:/usr/local/mesh_services/meshagent#

and 

root@erpnext-production:/usr/local/mesh_services/"redacted" Services/"Redacted"ServicesAgent#

The clients are installed on Ubuntu 22.04 servers.

**Comment by dxdemetriou** [comment]
I have used this command:
````sudo /usr/local/mesh_services/meshagent/remotefrederick/meshagent -fulluninstall````

Through MeshCentral server, uninstalling agent not seems possible for Linux and macOS, and so I have used this command on testing

**Comment by vithusel** [comment]
Got it to work. 

Thank you for all your help guys! 

Teaches me to change service configs mid install haha
