### ISSUE TITLE
Remove sub domain

### ISSUE THREAD

**Issue by raystek** [Ylianst/MeshCentral#4578]
From post #3440, there is the --removesubdomain command. 

node node_modules/meshcentral --removesubdomain mydomain

I ran this command and got  js errors. Basically the error says: "TypeError: obj.file.remove is not a function..."

**Comment by si458** [comment]
this works as intended here, no errors (1.1.11)
```
simon@testmc:~/meshcentral/MeshCentral$ node meshcentral.js --removesubdomain billybob
Done.
```
