### ISSUE TITLE
Export and Import DB 

### ISSUE THREAD

**Issue by ppz8206** [Ylianst/MeshCentral#4579]
Hi Ylianst
First I need to say thank you for your great job with meshcentral, is a super nice tool that I want to use 100 % of the time.

I am trying to export my DB from NeDB to mongo, doing the steps on your video and wiki
![Export - Import](https://user-images.githubusercontent.com/58489253/191884537-e645dd41-6331-4dc6-942b-e2002b1f4498.jpg)

but for some reason when I start the server again after importing the DB and changing the config.json give me some errors. 
![Running server](https://user-images.githubusercontent.com/58489253/191884561-21fa8c5b-dfed-4f6e-9eb5-a043ccc87006.jpg)

When I list the databases at mongo shows me meshcentral with 0.000GB 
![DB 0 Gb](https://user-images.githubusercontent.com/58489253/191884585-27d61b6a-815d-4f4c-aa1c-730b00704e3e.jpg)

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: [HyperV]
 - Network: LAN, ssl offload,
 - Version: 1.0.43
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: windows 11
 - Network: Local to Meshcentral and Remote over WAN
 - Browser:  Google Chrome
 
*Your config.json file**
```

  "_$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "cert": "meshcentral.americancare.net",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "MeshCentral",
      "title2": "American Care - IT Department",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "support@americancare.net",
    "names": "meshcentral.americancare.net",
    "production": true
  }
}

```

**Comment by nzalev** [comment]
With only 81 objects, it is not strange that MongoDB would report 0.000B. That is normal. To test if the import actually worked or not, you want to pull records from mongo.

For example, the db `groceries` still shows 0.000B despite containing documents:
```
> show databases
admin        0.000GB
canmsgs      0.134GB
config       0.000GB
groceries    0.000GB
local        0.000GB
meshcentral  0.001GB
> use groceries
switched to db groceries
> db.groceries.find()
{ "_id" : ObjectId("62b0d0dd974908485486e229"), "item" : "Butter", "cost" : 6.69, "category" : "Dairy", "date" : ISODate("2022-06-07T00:00:00Z") }
{ "_id" : ObjectId("62b0d0dd974908485486e22a"), "item" : "Pizza", "cost" : 5.79, "category" : "Frozen", "date" : ISODate("2022-06-07T00:00:00Z") }
{ "_id" : ObjectId("62b0d0dd974908485486e22b"), "item" : "Cheese", "cost" : 5.79, "category" : "Dairy", "date" : ISODate("2022-06-07T00:00:00Z") }
...
```

You also don't need to specify the collection in your config, especially if you've just set it to meshcentral, which is the default. You will also want to simplify your connection string.
```
  "settings": {
    "mongodb": "mongodb://127.0.0.1:27017/",
    "cert": "meshcentral.americancare.net",
```

Your screenshot does not contan the entire error. You can find the full stack trace in the file `meshcentral-data/mesherrors.txt`.

You can also run meshcentral interactively via `node node_modules/meshcentral`, and it should print the error to your terminal.

In either case, you will need to post the error here.

**Comment by si458** [comment]
closing as stale,
please use latest version and if still having issues then please reply back 👍
