### ISSUE TITLE
MeshCentral webgui crashes

### ISSUE THREAD

**Issue by eightoftwelve** [Ylianst/MeshCentral#458]
I have accidentally deleted the server log file after I found the issue.  I *should* be able to replicate the problem as I have backups just before the crash.

It appears the file meshcentral-smbios.db got too big (over a gig) and then crashed with "meshcentral Error: Cannot create a string longer than 0x3fffffe7 characters".  The file appears to have constantly grown.  I think I was using version 0.3.9-j at the time.  I have replaced the file meshcentral-smbios.db with a fresh one (from a new install).  Now running 0.4.0-k.  File does not "appear" to be growing.  Not sure of the impact of replacing the file, but all seems to work now.

I have several backups showing the file constantly growing and was 350mb last week.  File seems a constant 594k at this stage.  If you want the specific message, I can restore to a temporary computer and replicate the error at will.

This may be a fixed issue.

**Comment by Ylianst** [comment]
Interesting, thanks for reporting this. If you just delete the meshcentral-smbios.db file, there is no consequence. You can restart the server and it will start collecting SMBIOS data again. I will certainly be looking into what would cause a huge string to be sent to the server and add guards on the server to no save strings that are unreasonably long.

**Comment by dinger1986** [comment]
really old, stale @si458

**Comment by si458** [comment]
closing as stale but also seems to be fixed as no reported issues recently 2023
