### ISSUE TITLE
Silent install for Mac and Linux binary

### ISSUE THREAD

**Issue by cfsnate** [Ylianst/MeshCentral#4582]
Does not appear you can do a silent install when using the Mac or Linux binary

mpkg silent install on mac works but has code signing issues

**Comment by krayon007** [comment]
Is the request for something like a `-silent` option on the binary installer so that it does not output anything to stdout, and just returns a status code on failure?

**Comment by cfsnate** [comment]
Yes, when installing using the binary, users get a popup window asking to Install or Cancel,

See ss

![image](https://user-images.githubusercontent.com/72530590/192107399-ab2666a8-66b1-40e4-ab57-e5030ed37487.png)

**Comment by krayon007** [comment]
You should be able to run that binary from the command line like this:

`./meshagent -install`

It will still output status to stdout, but it doesn't require any user input

**Comment by dinger1986** [comment]
On the Mac it shows up user prompts, not tested on linux gui but I know @cfsnate did, he can maybe provide screenshots?

**Comment by krayon007** [comment]
I'll take a look. It could be possible I didn't enable text mode on Mac like I did Linux, because Linux it was added later for headless system.. it should be easy to enable.

**Comment by bionemesis** [comment]
Yes, a fully silent installer for macOS would be excellent, cheers!

**Comment by krayon007** [comment]
I found the issue and fixed it. Silent install was added later, so the platform check for it never included macOS... In order for this to work, you'll either have to put the updated `meshinstall-linux.js` file into your agents folder, or wait for Ylian to update the server when he gets back.

**Comment by krayon007** [comment]
This should be fixed in MeshCentral v1.0.86. Can you verify that this works for you?

**Comment by krayon007** [comment]
Sorry, a little premature. The fix should be in v1.0.88.

**Comment by cfsnate** [comment]
Confirmed fixed in 1.0.90

**Comment by dinger1986** [comment]
@si458 this is fixed
