### ISSUE TITLE
[Question] Is there a way to make a donation?

### ISSUE THREAD

**Issue by DillFrescott** [Ylianst/MeshCentral#4587]
I'd love to donate a bit to this project as I really like it! Is there an appropriate place for this?

**Comment by jsastriawan** [comment]
I don't think this project will accept donations. We have our day job at the company so the company sponsors this project. However, your contributions to documentation, features and helping out other users will be highly appreciated. I am just a minor contributor here but I believe Ylian and Bryan are sharing the same opinion.

**Comment by DillFrescott** [comment]
Okay! Thank you so much for the info! I will close this issue now as its been answered!
