### ISSUE TITLE
sensors data eg temperature

### ISSUE THREAD

**Issue by babbahotep** [Ylianst/MeshCentral#459]
Hi,

is it possible to retrieve sensors data eg cpu / hdd temp data through mesh commander / mesh central ?

**Comment by Ylianst** [comment]
So, Intel AMT does not expose fan / voltage / temp sensors. So, not going to show up in MeshCommander. If there is a OS API, we could add it to the agent in MeshCentral at some point.

**Comment by GRIFFCOMMca** [comment]
Windows exposes a lot of hardware info both in SNMP and WMI, not sure how much linux exposes with regards hardware details.
