### ISSUE TITLE
Ldap auth user strange

### ISSUE THREAD

**Issue by Christ010101** [Ylianst/MeshCentral#4590]
Hi,
conncetion with ldap it's ok

I have a problem with 2 user. User connection A and ok is info too. I connect with user B the info also its correct, but when I do F5 on user B I have the info of A.

In the admin console in users the name changes depending on who is connected A or B.

**Comment by sieuwe** [comment]
We had the same issue.
Do you use the following in the config?
"ldapUserName": "sAMAccountName",
"ldapUserKey": "sAMAccountName",

**Comment by sieuwe** [comment]
I would change this part:
"ldapUserName": "sAMAccountName",
And add
"ldapUserKey": "sAMAccountName",
On our part his works without user getting another users' account.

**Comment by Christ010101** [comment]
it's ok thank's ;)
