### ISSUE TITLE
Connected, Glass

### ISSUE THREAD

**Issue by jsinoy** [Ylianst/MeshCentral#4591]
Hi everyone ,

May I know what does this means ? Connected, Glass
![github](https://user-images.githubusercontent.com/109936671/192957615-ddc9cc1e-314a-4680-85cc-fca40c614389.png)

**Comment by silversword411** [comment]
First guess...I'd say it thinks that's a google glass android device

https://github.com/Ylianst/MeshCentral/blob/9bf2e211ab85a29be0bbb03ff404184da02ed57c/ua-parser.js#L587

**Comment by PathfinderNetworks** [comment]
This is typically what you see when you connect to a device that has multiple desktop sessions currently active- such as a Remote Desktop Services server.  It allows you to choose which currently active desktop session you would like to connect to.

**Comment by jsinoy** [comment]
Thank you guys .

**Comment by si458** [comment]
can this be re-opened?
ive just come into work today and noticed the exact same thing?
we dont have any google glass devices?
this computer we always connect to, and is not showing multiple `connected, glass` entries which is weird?
```
> info
Current Core: Aug 25 2022, 1851446608
Agent Time: 2022-10-19 10:31:35.124+01:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://meshcentral.myserver.com:443/agent.ashx.
Built-in LMS: Connecting...
OS: Microsoft Windows 10 Home - 21H2/19044.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner, win-console, win-info, win-securitycenter, win-terminal, win-virtual-terminal, win-volumes.
Server Connection: true, State: 1.
```
