### ISSUE TITLE
Let's Encrypt - Failed to obtain certificate

### ISSUE THREAD

**Issue by michaelsage** [Ylianst/MeshCentral#4595]
Hi

I am new to mesh central, I have a server up and running and I am trying to configure let's encrypt. I think I have followed all the instructions correctly, but I am unable to get a certificate.

Looking at the leevents output from the terminal I get the following:

`30/09/2022 09:54:54 - Getting certs from local store (Staging)
30/09/2022 09:54:54 - No certificate files found
30/09/2022 09:55:00 - Got no certificates, asking for one now.
30/09/2022 09:55:00 - Generating private key...
30/09/2022 09:55:00 - Setting up ACME client...
30/09/2022 09:55:00 - Creating certificate request...
30/09/2022 09:55:00 - Requesting certificate from Let's Encrypt...
30/09/2022 09:58:39 - Failed to obtain certificate: certificate has expired`

There is nothing in the letsencrypt-certs folder.

My lets encrypt element of the config.json looks like this: (the formatting is correct)

`  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@domain",
    "names": "meshcentral.domain.com",
    "production": false
},`

Any ideas please?

**Comment by dinger1986** [comment]
is this a new VPS? On Linux or Windows? 

You can always try my install script if that helps but its for linux? just need to point port 80 and 443 to your server and it does the rest.
https://github.com/techahold/Meshcentral-Installer

**Comment by michaelsage** [comment]
It's a virtual machine, it's ubuntu 18.04 fresh install.

Other than Let's Encrypt the install is working well, so I don't really want to reinstall the server (yet...)

**Comment by dinger1986** [comment]
you might have an issue due to it being 18.04, is it gully up to date? It might be worth trying upgrading to 22.04

**Comment by michaelsage** [comment]
I'm so sorry. It is an ubuntu 20.04 server, not 18.04.

**Comment by dinger1986** [comment]
ah ok. did you do the troubleshooting on this page? https://ylianst.github.io/MeshCentral/meshcentral/SSLnletsencrypt/

**Comment by michaelsage** [comment]
Yeah, I used that to set it up. I don't really understand which certificate has expired, is it something baked into the code somewhere perhaps?

**Comment by dinger1986** [comment]
yeah I dont either, my only thought is its something to do with letsencrypt certificates for getting certificates.

Did you test it using letsdebug?

**Comment by michaelsage** [comment]
Yup, came back all ok

**Comment by michaelsage** [comment]
Ok, found the issue. The hostname in the hosts file wasn't the FQDN. Updated that and saved. Restarted and it's got the certificate!

**Comment by dinger1986** [comment]
amazing well done
