### ISSUE TITLE
Notes button notify existing info

### ISSUE THREAD

**Issue by Fefo60** [Ylianst/MeshCentral#4596]
It's possible to change the color of notes button when the field is not empty ? (like an alert reminder)

![image](https://user-images.githubusercontent.com/103059358/193358585-2d8e8eb8-3d38-4f33-95f2-6b62d5122cc9.png)

**Comment by si458** [comment]
the was a PR done recently which shows the notes panel in the web ui which might now be useful!
https://github.com/Ylianst/MeshCentral/pull/5543
