### ISSUE TITLE
meshcmd : Invalid username/password

### ISSUE THREAD

**Issue by champix** [Ylianst/MeshCentral#4597]
**Describe the bug**
I'm trying to use meshcmd (on a linux machine) with username and password specified in meshaction.txt
I am getting the message "Invalid username/password".

This happens only if my password contains special characters (eg. gÀGÊZEsAÉxÀfS)

When i set my password to standard ASCII characters, everything works just fine.

MeshCentral server is installed on a linux machine
Impacted versions :  1.0 - 1.0.85

**To Reproduce**
* Create a meshcentral user with a strong password with special characters
* Download meshcmd and meshaction.txt from the web interface
* Edit meshaction.txt with correct username and password
* run meshcmd
```

**Comment by si458** [comment]
closing stale issue,
please try updating to the latest version 1.1.20 and use node 18 or above and try again!
if your issue still persists, then please reply back
