### ISSUE TITLE
Can I find out the url address of the remotely connected desktop?

### ISSUE THREAD

**Issue by payon** [Ylianst/MeshCentral#46]
Is it possible to jump from a Web browser to a specific url address on a remotely supported desktop?

**Comment by Ylianst** [comment]
Not sure I understand this request. Are you asking if you can have a URL that goes directly into a sub-page of MeshCentral to a specific computer and panel? For example, you want to give a URL to a friend that would go directly into remote desktop of a specific computer?

**Comment by payon** [comment]
you want to give a URL to a friend that would go directly into remote desktop of a specific computer?Yes. I want to proceed with this.

**Comment by jsastriawan** [comment]
See http://www.google.com/url?q=http%3A%2F%2Finfo.meshcentral.com%2Fdownloads%2FMeshCentral2%2FMeshCentral2UserGuide-0.1.8.pdf&sa=D&sntz=1&usg=AFQjCNHjZ8pVBrejT5_aZl7H3xK6g1bfbQ

Chapter 13 discusses about login token. This is a way to impersonate a user via token. Additionally you can also read about how to use node,  viewmode and hide url parameters at embedding discussion.
Regards,


Joko

**Comment by payon** [comment]
> See http://www.google.com/url?q=http%3A%2F%2Finfo.meshcentral.com%2Fdownloads%2FMeshCentral2%2FMeshCentral2UserGuide-0.1.8.pdf&sa=D&sntz=1&usg=AFQjCNHjZ8pVBrejT5_aZl7H3xK6g1bfbQ
> 
> Chapter 13 discusses about login token. This is a way to impersonate a user via token. Additionally you can also read about how to use node, viewmode and hide url parameters at embedding discussion.
> Regards,
> 
> Joko

Thank you....

**Comment by Ylianst** [comment]
Joko is correct, this is the API for opening the web page directly to a device. Please try it. If this API is not complete or has a problem, please open a new issue. Thanks.
