### ISSUE TITLE
Client power state shows powered on even when shut down

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#460]
Hi, we are using a reverse proxy (from ticket https://github.com/Ylianst/MeshCentral/issues/317), i notice when i shut a client down it goes grey to show its not online, when its then powered on again the "7 Day Power State" just shows a black bar continues even during the times it was shut down.... 

So the power state seems to indicate its always been online, but the icon is grey so MeshCentral knows its off.

Does this have anything to do with the connection timeout in the Reverse Proxy?

**Comment by Ylianst** [comment]
Thanks for the report. Next to the "7 Day Power State", there is a download icon. If you see this happening again, take a screen shot of the power bars and download the power events file and send them over, I will take a look at this.

**Comment by GRIFFCOMMca** [comment]
![state](https://user-images.githubusercontent.com/54428902/63900861-230dd380-c9d0-11e9-94ec-b72bfb89b50a.JPG)

This machine was shutdown last night and powered on about about 1pm today

**Comment by GRIFFCOMMca** [comment]
UPDATE
Can see its offline, but doesnt seem to have updated the Power State Bar.

We are seeing other issues which appear to be related, some desktops will not "connect", they show as online, its almost like what ever MeshCentral is seeing is cached info that isnt live, we need to restart the Apache server (which is the Proxy) to then be able to connect to the PC / server.

Apache and Mesh Central are running on Wi
![state 2](https://user-images.githubusercontent.com/54428902/63902097-ada50180-c9d5-11e9-999f-235c32eb9532.JPG)
ndows 7 Pro

**Comment by pczolee** [comment]
The same problem is here, without proxy. I think the whole "7 Day Power State" would better if there will be colors (for example, green when on, red when off).

**Comment by vitko-bg** [comment]
Looks like this issue is the oldest in regards to power state.
However, there are 2 additional that looks like can be closed as are duplicates - but please check the info I have posted in one of them( #808 )
Two duplicates of this issue are #808 and #705

**Comment by vitko-bg** [comment]
Last seen and powered on until current time...... Strange - Agent is offline and it still shows that device is powered on.... Is there any explanation about this, please. Thanks.
![image](https://user-images.githubusercontent.com/59362521/74676633-532f7580-51ae-11ea-8afc-d349d6554426.png)

**Comment by vitko-bg** [comment]
Difference in Last Seen time and mouse hover over the power bar:
![image](https://user-images.githubusercontent.com/59362521/81208242-a69fab80-8fc6-11ea-818b-6f8bc2173f7c.png)

**Comment by si458** [comment]
you can use the `agentping` and `agentpong` values in `config.json` to allow meshcentral to check if the agent is online or not
and if no reply then its offline
https://github.com/Ylianst/MeshCentral/blob/dd279d3ea268a82efad78e60c0e36d10c9f54764/meshcentral-config-schema.json#L467-L476
