### ISSUE TITLE
Out of date node.js causes issue when following Install Guide for Ubuntu: express-handlebars doesn't install

### ISSUE THREAD

**Issue by JoeShabadu2000** [Ylianst/MeshCentral#4602]
I was having an issue installing MeshCentral on an Ubuntu 20.04 installation on a Microsoft Azure VM, which I have since figured out, but I wanted to make a post in case others have this problem because it took me some time to get sorted. Might be something to update in the documentation, assuming this happens for others.

The instructions in the [install guide](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf) for Ubuntu NodeJS are:

```
sudo add-apt-repository universe
sudo apt update
sudo apt install nodejs -y
sudo apt install npm -y
```

When I do that in Ubuntu 20.04, running `node -v` to get the version gives me v10.19.0. The current branch is v18.x so this is pretty far out of date.

Later, when running `npm install meshcentral` I receive an error:

```
npm WARN notsup Unsupported engine for express-handlebars@5.3.5: wanted: {"node":">=v10.24.1"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: express-handlebars@5.3.5
```
As you can see, the express-handlebars package will not install with the version of node included in the default Ubuntu repo.

Updating node.js to a more recent version prior to installing MeshCentral seems to fix this issue, and express-handlebars installs properly. To get on the 18.x branch of node, just run the following command before installing nodejs:

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
```
So, the full installation code block should be:
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo add-apt-repository universe
sudo apt update
sudo apt install nodejs -y
sudo apt install npm -y
```
I checked on Ubuntu 18.04 (the version referenced in the install guide) and the version of node.js there is even further behind (8.x) and gives all sorts of errors when you run `npm install meshcentral`.

As I said earlier, this may be something to add to the documentation next time it gets updated. Or at least this post is here if someone comes searching for the error message later.

**Comment by si458** [comment]
we have updated a few scripts recently to use node 18
we are in the process of moving everything to at least node 18
