### ISSUE TITLE
Meshcentral play guest recordings

### ISSUE THREAD

**Issue by map7** [Ylianst/MeshCentral#4603]
I'm running Meshcentral 1.0.85 on debian and I've configured recordings and tested it with terminal and desktop as my user and it works.

When I allow guest access to one of my computers I would also like to record sessions and view for security auditing purposes. I can see that the recordings have taken place in the filepath but they are not listed in my recordings list (and my user is an Administrator), also if I download one of the mcrec files created by the guest and play them in the player they don't work. It doesn't even seem to load.

**To Reproduce**
1. Enable recordings in config and restart MeshCentral2 server
2. Allow guest access to a computer
3. Access the computer with the guest URL and use the Terminal
4. Download the mcrec file
5. Login as my admin account
6. Load mcrec file in player.htm and test = fail.

**Expected behavior**
I expected as Admin I could watch any recorded session on my computers.

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: Installed in a VM hosted solution (no containers used)
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: 1.0.85
 - Node: 14.18.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Debian 10 64bit
 - Network: Remote over WAN
 - Browser: Firefox Dev 102

**Remote Device (please complete the following information):**
 - Device: VM
 - OS: Debian 7 32bit
 - Network: Remote over WAN

**Your config.json file**
```
  "domains": {
	  "": {
	    "certUrl": "support.dtcorp.com.au",
	    "_title": "MyServer",
	    "_title2": "Servername",
	    "TitlePicture": "meshcentral.png",
	    "_minify": true,
	    "_newAccounts": true,
	    "_userNameIsEmail": true,
      "SessionRecording": {
        "filepath": "/home/map7/meshcentral-recordings/",
        "protocols": [ 1, 2, 5 ]
      }
	  }
```

**Comment by sistemmsn** [comment]
hello, how are you, notice that it does not work when you record in terminal mode both in windows and linux, but on the desktop if I am using version 1.1.2 and in node 18.1.2

**Comment by si458** [comment]
possibly related to #5256
