### ISSUE TITLE
Improvment logon on multiple clients

### ISSUE THREAD

**Issue by gally11** [Ylianst/MeshCentral#4604]
Hi, 

I love Meshcentral, it's a real benefic for us in our IT service.

I just have a function who isn't exist in Meshcentral but I used with another software , it's maybe a possible improvment: https://veyon.io/en/

The function is the possibility to logon on all selected computers with the same account, exemple connect the administrator account on all computers of a computer room.

If this option could be add on Meshcentral, it's very an excellente idea ;)

Thanks Ylian for all that you do, Mesh is great !

Guillaume
IT tech in a french college.

**Comment by Otsegox** [comment]
I asked for the same thing, recently. 
https://github.com/Ylianst/MeshCentral/issues/3557

**Comment by nounours460** [comment]
Sorry, I look for "Improvment" only in opened issues.

**Comment by Otsegox** [comment]
Don't me. It shows them it isn't only me! I just wanted to share.

**Comment by si458** [comment]
duplicate of #3557
