### ISSUE TITLE
Agent can't handle multiple viewers

### ISSUE THREAD

**Issue by Otsegox** [Ylianst/MeshCentral#4605]
**Describe your issue**
When multiple agents connect to the same client computer, often the agent will become unresponsive. 3+ people connected to 1 agent/PC

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Network: LAN / Hybrid
 - Version: 1.0.85 But issue exists in earlier versions, too
 - Node: 16.17.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows
 - Network: LAN
 - Browser: Chrome

**Remote Device (please complete the following information):**
 - Device: VMWare guest (and others but for this purpose, the VM)
 - OS: Windows 10 21H1
 - Network: Local LAN
 - Current Core Version (if known): Aug 25 2022, 1360394467

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "MongoDb": "mongodb://localhost:27017/meshcentral",
    "cert": "mesh.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "dbExpire": {
        "events": 7890000,
        "powerevents": 864000,
        "statsevents": 7890000
        },
    "_port": 443,
    "webrtc": false,
    "AgentSignLock": true,
    "AllowHighQualityDesktop": true,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_DesktopMultiplex": true,
    "_redirAliasPort": 80,
    "autoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 14,
      "zipPassword": "SuperDuperPassword",
      "googleDrive": {
        "folderName": "MeshCentral-Backups",
        "maxFiles": 14
      }
    }
  },
  "domains": {
    "": {
      "title": "Title",
      "title2": "Remote Support",
      "mstsc": true,
      "ssh": true,
      "_minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true
    }
  },
  "_smtp": {
    "host": "10.1.1.1",
    "port": 25,
    "from": "email@domain.com"
  }
}

```

**Comment by PTR-inc** [comment]
You could try to enable the desktopmultiplex option, you have it disabled now, remove the underscore:
"_DesktopMultiplex": true, > "DesktopMultiplex": true,

This is specifically for multiview performance

**Comment by Otsegox** [comment]
@PTR-inc  Yeah, I could. We did have it enabled at one point, but disabled... I forget why. I should note my config when I do that... I know it has some side-effects. I'll have to watch Ylian's video on it, again.

**Comment by si458** [comment]
`DesktopMultiplex` is what you need as it helps with server load and client load too
