### ISSUE TITLE
MeshRouter install cmd line option?

### ISSUE THREAD

**Issue by gezusk** [Ylianst/MeshCentral#4613]
I'm wanting to push out MeshRouter. It doesn't appear to have a command line option for installing, or maybe I haven't discovered it yet. Is there one?

**Comment by Ylianst** [comment]
Hi. No, MeshCentral Router is a stand alone executable. There is no installation for it and so, no installation switches. If you need something specific added, do open a new issue and let me know exactly what you would like.
