### ISSUE TITLE
Edit the login page

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4616]
I use Windows Server 2016. How to edit the specified places according to the photo?
how to edit title site and login page?
![1](https://user-images.githubusercontent.com/42680639/194756132-528b8e4d-4a5e-48dc-bc7b-fece72f94358.jpg)
![2](https://user-images.githubusercontent.com/42680639/194756137-f3607095-d967-415b-b037-1dedaec0cd84.jpg)

**Comment by si458** [comment]
You change the title under the domain settings in your config.json (remove the underscore first) https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json#L17

As for the bottom I don't believe you can customise it?

**Comment by bravery-only** [comment]
I installed MeshCentral in Windows Server 2016. How to edit it? Which path and which file?

**Comment by si458** [comment]
> I installed MeshCentral in Windows Server 2016. How to edit it? Which path and which file?

Depends on how you installed it?
You are looking for the `config.json` file which is normally inside your data folder

**Comment by bravery-only** [comment]
thank you my friend.fixed

**Comment by si458** [comment]
> thank you my friend.fixed

Brilliant

Please close the issue if resolved

**Comment by bravery-only** [comment]
According to the photo, how can you remove the root certificate and the team & privacy in footer?

**Comment by si458** [comment]
> According to the photo, how can you remove the root certificate and the team & privacy in footer?

It currently isn't possible

https://github.com/Ylianst/MeshCentral/blob/master/views/login.handlebars#L287-L293

**Comment by bravery-only** [comment]
I deleted it, but the footer was not deleted from my site

**Comment by si458** [comment]
> I deleted it, but the footer was not deleted from my site

maybe try removing the lines from the `login2.handlebars` file instead?
https://github.com/Ylianst/MeshCentral/blob/master/views/login2.handlebars#L343-L350

make sure you restart meshcentral after you have edited the files

**Comment by bravery-only** [comment]
Thank you my friend. It is solved. Can I contact you on Telegram or...?

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/issues/new/choose - i use discord

**Comment by Ylianst** [comment]
Closing this. @bravery-only in the future, please close issues once solved.

**Comment by bravery-only** [comment]
> https://github.com/Ylianst/MeshCentral/issues/new/choose - i use discord

In the new update, I will remove these errors, but the Root Certificate Terms & Privacy will not be removed. Have the lines changed?!
