### ISSUE TITLE
cant run agent gui microscript error

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4617]
**Describe the bug**
every time i download the exe and run it expecting a GUI i get a flash of a black window then vanishes?
BUT after running it manually in the command line i get
```
[2022-10-10 02:28:07 PM] [C809BAB1F0B988F1] ..\microscript\ILibDuktape_ScriptContainer.c:1667 (0,0) uncaught: 'cannot read property \x27split\x27 of null'
```

**To Reproduce**
1. download exe
2. run exe

**Expected behavior**
expected a GUI to open

**Screenshots**
N/A

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] N/A
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] LAN?WAN, Direct, SSL Lets Encrypt
 - Version: [e.g. 1.0.43] 1.0.85
 - Node: [e.g. 18.4.0] 16.17.1

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] N/A
 - OS: [e.g. Ubuntu] N/A
 - Network: [e.g. Local to Meshcentral, Remote over WAN] N/A
 - Browser: [e.g. Google Chrome] N/A
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Windows 10 21H2] Windows 10 Home - 21H2
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
i am able to run the setup fine from the command line using `meshagent64-rbs.exe -fullinstall`
but its then showing in the web UI as `Windows 10 Home - 21H2/19044 [WMI ERROR] `
not sure why its showing WMI ERROR ?

**Your config.json file**
```
N/A
```

**Comment by si458** [comment]
ok not sure what happened but i think it was an issue with the laptop itself?
i couldnt install any windows updates either, so i re-ran the mediacreationtool and re-installed (repaired really as it kept everything)
then suddenly its working now and also isnt showing the `[WMI ERROR]` in the web ui either now too?

**Comment by krayon007** [comment]
You can refer to [this thread](https://github.com/Ylianst/MeshAgent/issues/121) on the agent repo... There was an issue someone found where if their Window's System WMI Repository became corrupt it caused similar errors, and caused a bunch of things to fail... That thread detailed how to fix the wmi repository. I suspect this is the issue you were facing.

**Comment by si458** [comment]
@krayon007 thanks I didn't see that issue as mine was a different error but weirdly enough maybe the same problem causing
