### ISSUE TITLE
add agentcustomization & agentFileInfo in config.json And error when restart meshcentral

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4618]
![Screenshot_1](https://user-images.githubusercontent.com/42680639/194955338-1c0a7388-4123-4977-9c68-9f51038a8701.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/42680639/194955407-38ab2bd1-9abd-4ee9-a674-449debaa9037.jpg)
I did the wrong way of placing the codes. How to do it correctly?

**Comment by si458** [comment]
You missed a comma after the `}` after agentcustomization

**Comment by si458** [comment]
Also try https://jsonlint.com/ to help validate and correct your json correctly

**Comment by bravery-only** [comment]
Thank you my best friend.fixed
