### ISSUE TITLE
AMT v16.0.15 - Failed to set ACM certificate chain (ERR/4)

### ISSUE THREAD

**Issue by aRafeymasood** [Ylianst/MeshCentral#4619]
I have been having great success with activating AMT in ACM using the AMT cert. 
Running MeshCentral v1.0.85 in Hybrid (LAN + WAN) mode.

However, we recently tried the model Dell 7400 AIO which is running AMT version 16.0.15.
When trying to activate in ACM we are getting the error > **Failed to set ACM certificate chain (ERR/4)**

![image](https://user-images.githubusercontent.com/47164919/194969536-37081f71-db68-43ee-bc00-d3ac0f1b6ea1.png)

![info](https://user-images.githubusercontent.com/47164919/194969468-85c082fb-1226-440a-ba2d-067472167b95.PNG)

![amtverions](https://user-images.githubusercontent.com/47164919/194969480-8177a39e-4ca5-4338-897f-2e8c9b84479c.PNG)

We are able to activate in ACM using the AMT certificate on other models just fine but running version of ME lower than v16.
Had tried updating the BIOS on the 7400 AIO to the latest version and tried a couple of PCs of the same model. The error appears to be the same. 
Thinking it might have to do the BIOS or ME version?

**Comment by CornHead764** [comment]
Did you ever get this to work? We are running into the same error with the same AMT version on Dell Optiplex 7000 series.

**Comment by aRafeymasood** [comment]
No, unfortunately it has not resolved. Have been keeping MeshCentral up-to-date hoping that a new release might fix it. 

It appears from our testing that the ME version that is included in October BIOS update breaks the remote provisioning. If we activate via certificate with ME version below October 2022, it activates through the license just fine. Once it is updated to the latest ME, remote provisioning stops working. 
Strangely, if I provision these devices through MEBx - then I can send commands like Wakeup etc through MeshCentral but cannot HW remote. MeshCommander can on the other hand HW remote these PCs.

**Comment by aRafeymasood** [comment]
After your reply, I looked at #4803 and checked the BIOS updates again. 
Dell had released a new BIOS update on Nov 10 - 2022.
Tried that BIOS update, it updated the ME like you said from 16.0.15 to 16.1.25
Now it is working as designed, can provision devices through cert and HW remote works as well. 

thanks heaps for this. I had been checking the GitHub almost religiously and the solutio was in the BIOS update :)

**Comment by silversword411** [comment]
Is amt upgradeable for any version to current? Is there a good article to read on the topic?

**Comment by aRafeymasood** [comment]
Amt has been around since 2006. Roughly every year intel has been releasing a revision update. So presently amt is upto ver 16. If you have a device that was bought in 2020 it might come with ver 14 ME. You can only upgrade ME within the same revision. Like you can go 14.5 14.6 etc but not 16.1 etc. These updates are delivered through the BIOS. I'll see if I can find some good documentation on this. Unfortunately it's one bit that intel has not done a good job. If it was not for Ylianst and other people like him, I don't think a lot of people would have heard of AMT or how to implement it. A shame they are no longer with Intel

**Comment by silversword411** [comment]
Yeah, I figured it was locked into limited levels of upgrade. When I've looked at the vpro hardware during purchase research it's usually been $200-400 of extra cost to get the hardware and the hardware sales side to justify the cost has definitely been lacking.

I wonder if a subscription to https://www.wwt.com/ would give enough access to hardware of all the different versions for him to continue testing
