### ISSUE TITLE
Feature Request : Group name shown when in device view

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#462]
On selecting a single device to look at, there are 5 tabs (General, Desktop, Terminal, Files, Events, Console), it would be good to have the device group appended to the end such as the below:

Desktop - test-PC (group name)

It would also be good to have this in the Web Explorer TAB (<title>) location.

**Comment by Ylianst** [comment]
Good request. Should not be to difficult to add.

Note that I have been traveling last week, sick in bad this week and back to traveling next week. Apologies for slow responses and update over the past two weeks. Once I am back from this next trip, we hopefully will get back on a good release cadence.

**Comment by GRIFFCOMMca** [comment]
Cool, take it easy....

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.0-p with the device group name in the "My Device" view (picture below). Not sure what you mean by "Web Explorer TAB (<title>) location", if you can send a screen of this, I will look at making that change.

![x](https://user-images.githubusercontent.com/1319013/64912792-028c8b80-d6e9-11e9-92bc-defcdcbd8441.png)

**Comment by GRIFFCOMMca** [comment]
Hi, working my end...

The <title></title> HTML command controls what in the Exploirer "tab", see image
![2019-09-14 Mesh Central](https://user-images.githubusercontent.com/54428902/64913255-97ec4780-d70a-11e9-805e-b9d40d5e2bce.PNG)

**Comment by Ylianst** [comment]
Ok, published v0.4.0-r with the device group name in the title. Let me know if that works.

**Comment by Ylianst** [comment]
One more fix in MeshCentral v0.4.0-s for this. Use v0.4.0-s for testing.

**Comment by GRIFFCOMMca** [comment]
Confirmed working (up to version u now)

**Comment by Ylianst** [comment]
Nice. Thanks for checking! Closing this one.
