### ISSUE TITLE
Log in to all Windows computers at once

### ISSUE THREAD

**Issue by CoodyCZ** [Ylianst/MeshCentral#4620]
Hi, my question is simple and easy.

I have searched in older issues and have nothing found, then i write this new issue.

Is there any way, to log in all computers at once? (Windows 10, 11).  I'm using MeshCentral in LAN mode, without LDAP, only clear Mesh, and Agents. I have a small room with 31 pcs, and it is for me little bit lengthy to log in each computer separately.

Thanks for reply.

**Comment by si458** [comment]
this isnt possible as meshcentral is only a remote control software, so it will show whats on the screen, etc...

**Comment by silversword411** [comment]
Yes it's possible. Top right icon for the view modes. One is connect all

**Comment by CoodyCZ** [comment]
I may be mistaken, and perhaps it's not applicable in the case of Meschcentral, but I'll mention the tool Veyon (I no longer use it, but it was capable of this).

[https://docs.veyon.io/en/latest/admin/platform-notes.html#user-login](url)

I'm not a developer; it just occurred to me whether it could be used (in some way) in MeshCentral. What I'm more interested in is whether it's even possible.

**Comment by si458** [comment]
> Yes it's possible. Top right icon for the view modes. One is connect all

That's to view the computers, from what has been asked they want to login to each computer with a user while viewing the computer
