### ISSUE TITLE
invite HTTP url doesnt redirect to HTTPS

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4622]
**Describe the bug**
when i visit `http://meshcentral.myserver.com/invite` i was expecting the invite page, instead i get a 404 error

**To Reproduce**
1. enable invite codes
2. set invite code
3. visit `http://meshcentral.myserver.com/invite`

**Expected behavior**
when visiting the invite url in HTTP i expected it to divert to HTTPS but it displays HTTP 404 instead

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] N/A
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Hybrid, Lets Encrypt, Direct
 - Version: [e.g. 1.0.43] 1.0.85
 - Node: [e.g. 18.4.0] 16.17.1

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Windows 11 Pro
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] ANY
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
```
simon@mybillybob:~$ curl http://meshcentral.myserver.com/invite -v
*   Trying 217.1.1.1:80...
* Connected to meshcentral.myserver.com (217.1.1.1) port 80 (#0)
> GET /invite HTTP/1.1
> Host: meshcentral.myserver.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< strict-transport-security: max-age=60000; includeSubDomains
< Referrer-Policy: no-referrer
< x-frame-options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none'
< Content-Type: text/html; charset=utf-8
< Content-Length: 145
< Date: Tue, 11 Oct 2022 08:45:33 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /invite</pre>
</body>
</html>
* Connection #0 to host meshcentral.myserver.com left intact
```

**Your config.json file**
```
N/A
```

**Comment by OutbackMatt** [comment]
What Web Server software are you using?
Nginx or Apache2 or ....

That's where you need to set redirects to to HTTPS

**Comment by si458** [comment]
> What Web Server software are you using? Nginx or Apache2 or ....
> 
> That's where you need to set redirects to to HTTPS

im using it directly so the is not web server, meshcentral running on port 80 and 443

**Comment by Ylianst** [comment]
Oh. Good bug, working on it now.

**Comment by Ylianst** [comment]
Confirmed, I see the same issue. Working on it.

**Comment by Ylianst** [comment]
Ok, easy fix. Thank you for reporting this. Will be in v1.0.90.

**Comment by si458** [comment]
Bingo thanks
