### ISSUE TITLE
how to active free https for my server?

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4623]
Activating SSL for free
 I use Windows Server. How to activate free SSL for Mesh Central?

**Comment by dinger1986** [comment]
It's on the docs, need to enable in the json file.

https://ylianst.github.io/MeshCentral/meshcentral/SSLnletsencrypt/

**Comment by bravery-only** [comment]
I did it, but it still doesn't work and notsecure
![1](https://user-images.githubusercontent.com/42680639/195086321-0b4eb06e-f532-4732-bd4b-d91702c09e86.jpg)
![2](https://user-images.githubusercontent.com/42680639/195086334-c59b07ba-c36b-4d62-b613-5735b19ec154.jpg)

**Comment by bravery-only** [comment]
I did it, but it still doesn't work and show notsecure 
![1](https://user-images.githubusercontent.com/42680639/195087658-0f90ab29-50c5-429e-b495-f3db8302c7c9.jpg)
![2](https://user-images.githubusercontent.com/42680639/195087669-2c551b6a-c2bb-420c-aaaf-297b03b6a70c.jpg)

**Comment by si458** [comment]
> I did it, but it still doesn't work and show notsecure ![1](https://user-images.githubusercontent.com/42680639/195087658-0f90ab29-50c5-429e-b495-f3db8302c7c9.jpg) ![2](https://user-images.githubusercontent.com/42680639/195087669-2c551b6a-c2bb-420c-aaaf-297b03b6a70c.jpg)

based on your previous comment (which you deleted but was emailed to everyone) 
the `names` showed an IP address, it needs to be a DNS name which gets resolved to the IP address in question

**Comment by bravery-only** [comment]
Which DNS? Can you solve it for me? I couldn't do it

**Comment by bravery-only** [comment]
Which DNS? Can you solve it for me? I couldn't do it

**Comment by dinger1986** [comment]
Please read the documents.

It needs a dns name not an IP address.

**Comment by bravery-only** [comment]
I use Windows Server and I only have an IP address

**Comment by OutbackMatt** [comment]
You can't get a Lets Encrypt certificate for an IP address, only for a FQDN (Fully Qualified Domain Name)
You will need to buy a domain name to use lets Encrypt certificates (or any SSL certificate)

**Comment by Ylianst** [comment]
I am going to close this issue since it's probably solved. MeshCentral will not setup a DNS name for your server for you. You need to setup that part yourself by buying a DNS name and pointing that name to your server. You can use [https://www.duckdns.org/](https://www.duckdns.org/) to get a free one. After that, I have a [YouTube video on Let's Encrypt,](https://www.youtube.com/watch?v=a4F1ayu7XWo) maybe that will help.
