### ISSUE TITLE
"Installing" at every boot 

### ISSUE THREAD

**Issue by beefliver** [Ylianst/MeshCentral#4624]
Hi group

I need this solution to work on an internal network with no internet access.

c:\meshcentral is where I have MC installed. 

node node_modules\meshcentral
"Installing node-windows@0.1.4" 

Is there a way to prevent it from trying to install every time I boot up? I was under the impression that all files can be stored locally. Also, I installed MongoDB and I get this error as well when I am offline

_"installing mongodb@4.9.1...
ERROR: Unable to install required module "mongodb@4.9.1". MeshCentral may not have access to npm, or npm may not have sufficient rights to load the new module. To manually install this module try: (lists the npm install command)_

Directory:
C:\MeshCentral
C:\MongoDB
C:\Data\db

EDIT: To clarify, it does work successfully when connected online

**Comment by dinger1986** [comment]
did you manually try and install the module?

**Comment by dinger1986** [comment]
do you have that folder? if so then yeah, mongodb would be the name

**Comment by beefliver** [comment]
yes, I have that folder 

c:\meshcentral\node-modules\mongodb

>etc
>lib
>src
etc etc

**Comment by beefliver** [comment]
Okay, I think I found the issue that may have been causing it.

So, when I go online and install the module by running:
node node_modules\meshcentral

it installs and after, it shows "1 critical severity vulnerability"

I then run "npm audit fix --force" which then installs node-windows@1.0.0-beat.8 which then seems like it breaks it. So, I reinstalled it and did NOT run the audit fix.

**Comment by beefliver** [comment]
How can I verify if it's running on the MongoDB?

I do get the warning that it's unable to find mongodump.exe

**Comment by dinger1986** [comment]
should be able by going to "My Server" -> "Console" and type info and hit enter, to should show MongoDB next to Database

**Comment by beefliver** [comment]
Thank you!

**Comment by Ylianst** [comment]
Is this issue done?

Note that the "info" command looks like this. Here I am running PostgreSQL.

![image](https://user-images.githubusercontent.com/1319013/197655851-e4209418-669e-4823-bd7e-ba9b99b38bfa.png)

For "unable to find mongodump.exe", starting with MongoDB 3.8 (I can't remember exactly) the MongoDB Tools come as a separate package. So you need to install the [MongoDB Tools](https://www.mongodb.com/try/download/database-tools). If still not found by MeshCentral, you can set the path like this:

```
{
  "settings": {
    "autoBackup": { "mongoDumpPath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe" }
  }
}
```

MongoDump is needed to create an automatic daily backup on your database in the `meshcentral-backups` folder. If you don't want to do this, just put:

```
{
  "settings": {
    "autoBackup": false
  }
}
```

That should turn off the feature.

Hope this helps.

**Comment by beefliver** [comment]
Hi Ylian,

This issue has been resolved, thank you for the follow-up!
ᐧ
