### ISSUE TITLE
Change login page URL name

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4625]
I want to change the login page to the desired address? How can it be done?

default address  10.12.14.15     my custom address: 10.12.14.15/myserver/

**Comment by dinger1986** [comment]
Have you read the docs?

https://ylianst.github.io/MeshCentral/

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf

They are pretty comprehensive.

**Comment by bravery-only** [comment]
I read. I use Windows Server. Which file should I edit to change the site address?

**Comment by dinger1986** [comment]
It's the same file on every platform, most commonly used file for meshcentral options. 

It's all in the docs and a simple read will help you find that same with your previous 2 questions 😃. 

That's why so much time has been taken on producing the docs.

**Comment by PathfinderNetworks** [comment]
No matter which platform is used, all of the configuration settings are always contained in config.json. That is the only file that needs to be edited.

**Comment by OutbackMatt** [comment]
Honestly, I find an answer of RTFM without following up with a link to the specific part of the manual where that is detailed as being really arrogant, and one of the problems with open source software

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf
Top of page numbered 10, but actually page14, section 7.2

The file needing editing is always the 'config.json' file 

and @bravery-only this is all covered in the docs

**Comment by bravery-only** [comment]
I want to create a custom address for the login page. I don't want to enter the login page with the default page: 10.11.12.14/login
I want to login with this new page, for example: 10.11.12.14/myserverlogin

**Comment by si458** [comment]
> I want to create a custom address for the login page. I don't want to enter the login page with the default page: 10.11.12.14/login I want to login with this new page, for example: 10.11.12.14/myserverlogin

you cant do this as its hard coded

**Comment by Ylianst** [comment]
I am back from vacation later today, I will make "/login" an option so you can change it.

**Comment by bravery-only** [comment]
> I am back from vacation later today, I will make "/login" an option so you can change it. I will need to do a bunch of catching up on other things, but this seems like a simple ask.

Did you put that option to change the login page?
