### ISSUE TITLE
Error When Check Update

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4628]
![UpdateError](https://user-images.githubusercontent.com/42680639/195339576-ff3b407f-1f3a-4392-af2c-d5ad3ee6b5f5.jpg)
When I click on update in Windows Server, this error appears

**Comment by OutbackMatt** [comment]
You haven't installed NPM or NODE correctly
Check the PATH variable, and update to include the paths used to install NPM and NODE
