### ISSUE TITLE
Transfer Clients from Public Server to Private server

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4629]
I set up a private server, but I have clients on the public server. Is it possible to transfer them to the private server without reinstalling the agent?

**Comment by dinger1986** [comment]
something like this ran from the console tab should do it, test it on one machine you can access easily first

```
powershell Invoke-WebRequest "your mesh download url" -Outfile meshagent.exe
start meshagent.exe
```

**Comment by Ylianst** [comment]
Oh wow, this is a good answer. Indeed the best way to switch the agent's server is to change the agent and/or update the "meshagent.msh" file with the one of the new server. Personally, I would just copy the new "meshagent.msh" over the old one and restart the agent, but using powershell like this is very nice.

**Comment by dinger1986** [comment]
Thanks, the command was slightly wrong though 😂

**Comment by dinger1986** [comment]
@si458 this is fixed
