### ISSUE TITLE
"meshcore.min.js"execute command report 'TypeError: undefined not callable' issue

### ISSUE THREAD

**Issue by tristincui** [Ylianst/MeshCentral#463]
Hello. I add the code of meshcore.min.js to watch the npm version, but always report the 'TypeError: undefined not callale' i. To add special command, Can i use "require('child_process').exec " to execute the linux command? Or how do i execute special linux command?
 `case 'npm':
                    var str;
                    var exec = require('child_process').exec;
                    exec('npm -v', function (error, stdout, stderr){
                        console.log('stdout: ', stdout)
                    });
                    response = JSON.stringify({ name: str });
                    break;`

**Comment by Ylianst** [comment]
I will take a look next time I can.

Note that with traveling and me being sick this week, releases have been slow. Apologies to everyone about this. Hope to get back to a good release cadence fast this next trip.

**Comment by Ylianst** [comment]
By the way, if you remove the "meshcore.min.js" file, MeshCentral will automatically start using "meshcore.js" next time your restart the server. So, probably best to do this and start changing the non-minified version.

**Comment by Ylianst** [comment]
I just looked into this and this code makes to sense at all:

```
var str;
var exec = require('child_process').exec;
exec('npm -v', function (error, stdout, stderr) {
    console.log('stdout: ', stdout);
});
response = JSON.stringify({ name: str });
```

This, this JavaScript is not running in node, rather it's running in Duktape and so, the methods to launch a process are different. I will check with Bryan on Monday on how to best do an invocation like this.

**Comment by krayon007** [comment]
Right now, the only method for child_process that I Implemented in the agent is, 'execFile'

**Comment by Ylianst** [comment]
I tries doing something like this, but it did not work correctly.

```
var child = require('child_process').execFile('C:\\Program Files\\nodejs\\node.exe', ['-v']);
child.stdout.str = '';
child.stdout.on('data', function (chunk) { this.str += chunk.toString(); });
child.waitExit();
response = 'Response: ' + child.stdout.str;
```

**Comment by krayon007** [comment]
The first param should be the exe name, the second parsm should be -v, so like:

['node.exe', '-v']

**Comment by Ylianst** [comment]
Yes! That worked.

```
case 'npm': {
  var child = require('child_process').execFile('C:\\Program Files\\nodejs\\node.exe', ['node.exe', '-v']);
  child.stdout.str = '';
  child.stdout.on('data', function (chunk) { this.str += chunk.toString(); });
  child.waitExit();
  response = 'Response: ' + child.stdout.str;
  break;
}
```

**Comment by Ylianst** [comment]
Ok, will close this one as the solution seems to work. Feel free to re-open if needed.
