### ISSUE TITLE
No access to hosts files 

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4631]
![Hosts](https://user-images.githubusercontent.com/42680639/195456635-475ed715-62c0-4fe9-b05d-ce3cd76bb086.jpg)
In Windows 7 32-bit, access to hosts files is not allowed!

**Comment by bravery-only** [comment]
etc>hosts

**Comment by OutbackMatt** [comment]
This has nothing to do with MeshCentral
I would download a program called 'Notepad ++' 
(also known as 'Notepad Plus Plus')

You can access and change the hosts file in Windows with that program in Administrator mode

You need to change the hosts files on all client machines, but why not just use the LAN IP address (yes no security, but so what, it is on your LAN)

**Comment by bravery-only** [comment]
I know this. I mean to access the hosts files in the client. I cannot access the client hosts files. Ets folder is not displayed. While this file exists in the client

**Comment by krayon007** [comment]
Are you only having this issue on Windows 7 32 bit? It works on your other windows machines?

**Comment by bravery-only** [comment]
Only for Windows 7 32 bit.

**Comment by krayon007** [comment]
Is the agent 32 bit, but the OS 64 bit? I found if you run the 32 bit agent on 64 bit windows, an issue that arises, is that when it enumerates "Windows\System32\Drivers", it is actually enumerating "Windows\SysWow64\System32\Drivers", which does not have an "etc" folder. If this is your issue, I have to think about how to fix this... I found that I can still access it if I accessed the path directly, it was the enumeration that missed it, becuase of the folder redirection.

**Comment by krayon007** [comment]
I think I can fix it, if I add a "sysnative" folder under windows if it detects a 32 bit agent running in 64 bit windows

**Comment by bravery-only** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/42680639/195643811-68e90cf8-5a1a-47d6-82bc-fe5e159cc9bb.jpg)
According to the picture, Windows is 32-bit and the agent is 32-bit

**Comment by krayon007** [comment]
![win7_1](https://user-images.githubusercontent.com/29240564/195700118-2fd72faf-f897-4bd7-be04-046a877f37d6.png)

![win7_2](https://user-images.githubusercontent.com/29240564/195700139-53c3bbcb-ba97-40e0-a054-cb34b60b5313.png)

Actually, you need to go to the details page to see if the platform is 32 bit or 64 bit. The general tab doesn't differentiate the OS between 32 and 64 bit.
