### ISSUE TITLE
Multi-device desktop view

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#464]
This may need to be an enhancement- not sure.  I'm wanting to view multiple desktops at the same time using the Desktop view. While I can choose the devices I want to see from that view and connect to them the issue is that the quality of the image is incredibly poor. So poor that it's impossible to see anything on each device.  It's as though the resolution for each image is extremely low- like 320x200 or something crazy.  I have the size set to Large but that makes no difference (the resolution seems to stay the same just now it's larger).  
Here's a screen grab of what I mean.  
![mesh](https://user-images.githubusercontent.com/48607498/64059402-e259ba00-cb89-11e9-9656-2cfe022a68c1.JPG)
Speaking of viewing multiple devices at once- it would also be nice if it were possible to 'pop out' a remote session so that we could more easily connect to multiple other devices. I can do it now but I need to open a new browser tab and log in to the Mesh site for each device. It's not a huge nuisance needing to do that but it could be streamlined.

**Comment by PathfinderNetworks** [comment]
Also, in that multi-device view I mention about- it would be awesome if, in addition to the resolution of the images being a usable quality, I could double click (or click a button, etc) and immediately jump to a full size window for that device.  Hope that makes sense.

**Comment by senolkehya** [comment]
Hi,
Now i am opening multiple tabs on chrome and i can use. If Ylianst can develope this function it will be really good. It will be usefull function. If needed examples and screenshots I can give suggestions from other open source web based remote tools.

**Comment by Ylianst** [comment]
Hi. So, in multi-view mode, you can click "Settings" and select the quality and scaling factor for the devices. By default, it's a thumbnail view (25% scaling, 20% quality), but you should be able to set it to what you need.

If you click on the little title bar with the device icon and name, it should immediately open that device for remote desktop control. Shift-clicking the device title bar will open a new tab for that device, but I just noticed that it does not go to remote desktop, this is bad.

If you can check all this and confirm you see the same behavior and comment back what you need changed, that would be great. I am traveling now, will be back with regular updates September 12th.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian, what you described does work and is what I needed to get the image quality up to a usable state.  I didn't notice that Settings option before.  

Thanks!
