### ISSUE TITLE
Windows Server 2012 R2 Powershell

### ISSUE THREAD

**Issue by shadyslim2018** [Ylianst/MeshCentral#4640]
agent version: Commit: 2022-Aug-25 00:17:18:0700
Server version : 1.0.85

Server is on installed on Manjaro Gnome 42.5 Kernel version 6.0.0-1

On Windows Server 2012 R2, the remote desktop works fine, but the Command Prompt and Powershell are unusable. See the attached image 
![Screenshot from 2022-10-15 16-04-01](https://user-images.githubusercontent.com/38296004/195993575-9825e272-ce19-4b41-908f-075553fb3a0c.png)

I type 'mesh' and the output is :

![Screenshot from 2022-10-15 16-04-26](https://user-images.githubusercontent.com/38296004/195993603-3ca8f8ef-dd15-4593-8435-7ddf5c4a4a6d.png)

I'm using WAN connection, I have access to other servers above Server 2012 R2, also have access to Windows 10, and they're all working fine. I only have access to one Windows Server 2012 R2

**Comment by si458** [comment]
Please refer to https://github.com/Ylianst/MeshCentral/issues/4435. duplicate
fix is delete `modules_meshcore_min` folder OR pull from git repo directly which has my PR fix included https://github.com/Ylianst/MeshCentral/pull/4594

**Comment by shadyslim2018** [comment]
> Please refer to #4435. duplicate fix is delete `modules_meshcore_min` folder OR pull from git repo directly which has my PR fix included #4594

Excellent, stopped the service and moved modules_meshcore_min to a different location, then started the service and now everything seems to be working fine.

**Comment by shadyslim2018** [comment]
There is still a problem with the terminal, even after modify win-terminal.min.js  `return Buffer.from("[" + t.join(";") + e)` to  `return Buffer.from("\x1B[" + t.join(";") + e)`

When I press the arrow keys and del key, random characters show up on the screen.

**Comment by krayon007** [comment]
> There is still a problem with the terminal, even after modify win-terminal.min.js `return Buffer.from("[" + t.join(";") + e)` to `return Buffer.from("\x1B[" + t.join(";") + e)`
> 
> When I press the arrow keys and del key, random characters show up on the screen.
> 
> P.S.
> 
> I also changed `if (obj.args.minifycore === 0) obj.args.minifycore = false;` to `if (obj.args.minifycore == null) obj.args.minifycore = false;` and it didn't make difference.

After the modification, do the control characters only show when you press the arrow key, or do the control characters always show up?

**Comment by shadyslim2018** [comment]
When I press the arrow keys or del key, backspace is fine. These are the characters that show up.

[3~ DEL
[A  UP
[B DOWN
[C  RIGHT
[D  LEFT

**Comment by si458** [comment]
> When I press the arrow keys or del key, backspace is fine. These are the characters that show up.
> 
> [3~ DEL [A UP [B DOWN [C RIGHT [D LEFT

@krayon007 i can confirm same here sadly
@shadyslim2018 can you close this issue and then paste your issue now with the keys in https://github.com/Ylianst/MeshCentral/issues/4435 to help us keep track

**Comment by shadyslim2018** [comment]
Done
