### ISSUE TITLE
Running MeshCentral Sate-less with MariaDB

### ISSUE THREAD

**Issue by aRafeymasood** [Ylianst/MeshCentral#4645]
I was trying to run Meshcentral state-less so the certificates and the config files are stored in the databased with encryption
The following commands worked to put the configs/certs into the database as per documentation

```
node ./node_modules/meshcentral --dbpushconfigfiles * --configkey mypassword
```

However, I am running MariaDB and could not figure out the equivalent command for MariaDB. The below is available in the doco for MongoDB

```
node ./node_modules/meshcentral --loadconfigfromdb mypassword --mongodb "mongodb://127.0.0.1:27017/meshcentral"
```

Moreover, I tried setting up a test server with MongoDB > used the same commands above and it does what it is designed to do except that when I tried to run it as a service - it fails

```
node ./node_modules/meshcentral --loadconfigfromdb mypassword --mongodb "mongodb://127.0.0.1:27017/meshcentral --install"
```

Once the service starts - it creates new certificates and config files and cannot load the config from the server.

**Comment by Ylianst** [comment]
Hi. Sorry for the delay. First, note that passing command line switches is the same as putting a value in the "Settings" section of the config.json. So:

```
node ./node_modules/meshcentral --mongodb "mongodb://127.0.0.1:27017/meshcentral"
```

Is the same as placing this value in your config.json file:

```
{
  "settings": {
    "mongodb": "mongodb://127.0.0.1:27017/meshcentral"
  }
}
```

So, you can configure MariaDB in the config.json as you want and run this:

```
node ./node_modules/meshcentral --dbpushconfigfiles *
```

Then to start the server, run:

```
node ./node_modules/meshcentral --loadconfigfromdb mypassword
```

Of course the issue here is that your going to have a minimal config.json to connect to the database to get the rest of the config.json.

I am going to give this a try myself just for kicks, will report back.

**Comment by Ylianst** [comment]
Ok, I just did some testing and put fixes for the state-less server stuff. Fixes will be in v1.0.90.

I tried with PostgreSQL, but it's the same code for MariaDB. I setup the config.json with the DB settings, then loaded the configuration like this:

```
node ./node_modules/meshcentral --dbpushconfigfiles * --configkey mypassword
```

I then switched the config.json to this. With only the database stuff:

```
{
  "settings": {
    "Postgres": {
      "user": "postgres",
      "password": "tools",
      "port": 5432,
      "host": "localhost"
    }
  }
}
```

I then run the server like this:

```
node meshcentral --loadconfigfromdb mypassword
```

Now, you still need this mini config.json to get the database to connect. Let me know if that is a problem.

**Comment by Ylianst** [comment]
Another option is to use this mini config.json:

```
{
  "settings": {
    "LoadConfigFromDB": "mypassword",
    "Postgres": {
      "user": "postgres",
      "password": "tools",
      "port": 5432,
      "host": "localhost"
    }
  }
}
```

In this case, you don't need any command line switches.

**Comment by aRafeymasood** [comment]
Thanks heaps for this, will test and report back soon.

**Comment by aRafeymasood** [comment]
Tried and it works as advised. Thanks heaps again

Had to provide database name as well. 
`{
  "settings": {
    "LoadConfigFromDB": "myPassword",
    "MariaDB": {
      "user": "admin",
      "password": "myPassword",
      "port": 3306,
      "host": "localhost",
	  "database": "MyDbName"
    }
  }
}`
