### ISSUE TITLE
Auto add non-admin users to all device groups

### ISSUE THREAD

**Issue by krzysztofakc** [Ylianst/MeshCentral#4646]
I've noticed that ManageAllDeviceGroups works only for full admins. 

Is it possible to grant access to all device groups for every non-admin user?

I know you can add users to a group and then add device groups to a user group, but our company used TeamViewer so far and they had different group for every client.

I can make everyone a full admin but I don't want to do that.

-client1_group
---client1pc
---client1pc
---client1pc
---client1pc
---client1pc
---client1pc

-client2_group
---client2pc
---client2pc
---client2pc
---client2pc
---client2pc
---client2pc

and so on

**Comment by silversword411** [comment]
There's no such thing as sub-groups. Just groups. Assign permissions accordingly. 

There's already an open issue for better groups, please close this as dupe

https://github.com/Ylianst/MeshCentral/issues/4269

**Comment by krzysztofakc** [comment]
I already resolved it with assigning tags to clients and then sorting by group-tag.

Waiting for subgroups though
