### ISSUE TITLE
How to Change Automatically Agent 32bit to Agent 64bit?

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4647]
How to remotely remove the 32-bit Agent and install the 64-bit version?

**Comment by Ylianst** [comment]
Hi. Yes, you need to remove the old agent and install the new one. I will say that I don't think there is much or any noticeable differences between the 32 and 64 bit agents on Windows except the installation path. So, I don't think installing the 32 bit agent on a 64 bit computer is not going to be an issue.

**Comment by bravery-only** [comment]
Can this be done without the user noticing? Through the server

**Comment by Ylianst** [comment]
Not really. Again, I don't think updating this would offer much value, but if you did it, the default install path is different.

**Comment by vithusel** [comment]
Somewhat of a silly question. Could a user install the 64bit agent whilst the 32bit one is still installed? Then flip to the 64bit install and uninstall the 32bit version? (just in case someone else wants to do this in future and finds this issue)

**Comment by dinger1986** [comment]
No, unless you change the agent name etc in config.json

**Comment by Ylianst** [comment]
It's not possible to install the 32bit and 64bit agent at the same time since they both have the same "service name". The service name is a unique identifier for a service and two can't have the same name. So, trying to install the second agent should indicate that the agent is already installed.

**Comment by Ylianst** [comment]
I will close this once since it seems answered, but feel free to open new issues with questions as needed.
