### ISSUE TITLE
Not showing email notification in my server

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4648]
Meshcentral

![Meshcentral](https://user-images.githubusercontent.com/42680639/196946309-3fa9373f-6dd0-4e85-97d1-c54740dfa282.jpg)

My Server
![My Server](https://user-images.githubusercontent.com/42680639/196946316-95948985-f9ac-4aa2-9f98-4a0f1fe4be3b.jpg)
 

How can I activate the email notification?

**Comment by bravery-only** [comment]
I Enabled SMTP and this page is shown when I login. I do not receive an email for confirmation,.
Help me @Ylianst 

![2](https://user-images.githubusercontent.com/42680639/197065153-4b8ef98a-e42b-4399-ba53-f0e444b63b97.jpg)
![1](https://user-images.githubusercontent.com/42680639/197065146-ecbb2756-3178-4670-baba-acea1576924b.jpg)

**Comment by vithusel** [comment]
Are you connecting to your own personal server or using a provider? (365, google)

**Comment by bravery-only** [comment]
> own personal server

 personal server

**Comment by bravery-only** [comment]
I use Windows Server

**Comment by vithusel** [comment]
Sorry i meant for your SMTP. 

Are you connecting to a hosted service such as Gmail or Outlook or are you hosting your own email server? 

Can you send a copy of your SMTP settings (Hide anything personal)

**Comment by bravery-only** [comment]
"smtp": {
            "host": "smtp.gmail.com", 
            "port": 465, 
            "from": "my email@gmail.com", 
            "user": "my email@gmail.com", 
            "pass": "xxxxxxxxxxxxxxxxxxxxxxx", 
            "_verifyEmail": false, 
            "tls": true
         }, 

The interesting thing is that when I add this code, after restarting Mesh Central, this code (  "verifyEmail": false,)is deleted!!

**Comment by PathfinderNetworks** [comment]
Gmail requires OAuth to send email through their SMTP servers.  I can't recall if Ylian has built in any functionality to support that?

**Comment by vithusel** [comment]
You can use App Passwords with gmail which circumvents the need for Oauth. 

Look at the below link to generate a App password. 

https://www.febooti.com/products/automation-workshop/tutorials/enable-google-app-passwords-for-smtp.html

or 

https://support.google.com/mail/answer/185833?hl=en-GB

**Comment by bravery-only** [comment]
I got App Passwords . Do you have a sample syntax for this?

**Comment by bravery-only** [comment]
I activated the email, but when the agent is Coneccted & Disconnected, the notification is received very late. Or email is not received!

**Comment by bravery-only** [comment]
It takes 5 minutes to receive the email. How to change its time? Which file should I edit?

**Comment by bravery-only** [comment]
It takes 5 minutes to receive the email. How to change its time? Which file should I edit?

**Comment by vithusel** [comment]
Thats odd. Meshcentral sends the email immediately. 

@Ylianst any chance the server keeps trying to send an email or does it push to smtp once then quit? 

If so then gmail is the likely culprit here

**Comment by bravery-only** [comment]
When I send an email from here, it is received immediately.
![Email](https://user-images.githubusercontent.com/42680639/197336250-4cff943b-2430-4b8d-8db3-084be0915abd.jpg)


 But when connecting and disconnecting the agent, it takes time - 4-5 minutes!!!

**Comment by bravery-only** [comment]
I saw the video of the email server. Here, the time to send the email when the device is connected is said to be 5 minutes. Then it can be said to be one minute. Where can I set this time?
![Mail Server](https://user-images.githubusercontent.com/42680639/197340112-8abd729f-d12a-4f37-9811-e22e41abc5be.jpg)
Thank you
@Ylianst

**Comment by bravery-only** [comment]
In the training video, you talk about starting the timer. The timer is on 5 minutes. How can I reduce the timer time? Which file should I edit?@Ylianst

**Comment by bravery-only** [comment]
After a few hours I was able to find the timer and changed the email receiving time to 6 seconds

**Comment by brahunafisk** [comment]
> After a few hours I was able to find the timer and changed the email receiving time to 6 seconds

Where did you find this at?  I've been looking everywhere.

**Comment by silversword411** [comment]
> Where did you find this at? I've been looking everywhere.

Well start with the video https://youtu.be/-L0-xjbWZJI?t=881

You know there's a help command `emailnotifications` to show you the notification queue, so look for that. 

You'll see it's calling `deviceNotifications`

Looks like it's in meshmail.js

Trying to match this online with my local vscode copy (all the above searching is done locally in vscode because github search sucks)

and while I'm trying to find the code online to send a link

https://github.com/Ylianst/MeshCentral/blob/master/meshmail.js#L29

Looks like there's a recent change to the file...look at what Santa is bringing you for Christmas

https://github.com/Ylianst/MeshCentral/commit/7002ce1ea29e1bcc30321deacba0941c186d55d8
