### ISSUE TITLE
Add notification in Telegram

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4650]
Is it possible to add this feature? It would be great to receive notifications in the Telegram bot

**Comment by Ylianst** [comment]
I just researched doing notifications from MeshCentral into Telegram and indeed, there are libraries to do this. Looks very interesting. [For example this one](https://www.npmjs.com/package/telegram). So, this is not a feature currently, but seems like something I can do.

**Comment by bravery-only** [comment]
> I just researched doing notifications from MeshCentral into Telegram and indeed, there are libraries to do this. Looks very interesting. [For example this one](https://www.npmjs.com/package/telegram). So, this is not a feature currently, but seems like something I can do.

Of course, the method of this example is in the form of a mobile number. But please add the API Key method that can receive the notification in the Telegram bot.

**Comment by Ylianst** [comment]
I just did a first pass at enabling Telegram. I am currently using the phone method, I need to look API key. If you have any hints where I need to look, please let me know. I currently got MeshCentral sending messages from the server console, but working on adding support for users to be able to register their user handles.

**Comment by vithusel** [comment]
This requires the creation of a telegram bot. But seems like the logical way of sending messages. Instead of having to login to telegram as a user/number 

https://levelup.gitconnected.com/six-easy-steps-to-create-a-telegram-bot-from-a-google-spreadsheet-b62008d2b81f

**Comment by Ylianst** [comment]
So far, I made good progress on using messaging features and adding it as a authentication factor. I still have to work on getting Telegram setup with phone or bot.

![MC2-Telegram1](https://user-images.githubusercontent.com/1319013/197361277-a271ac6f-79a4-4535-abd5-eb61940110d0.png)
![MC2-Telegram2](https://user-images.githubusercontent.com/1319013/197361281-d973111c-8e60-42e6-a76b-f3549fccb224.png)
![MC2-Telegram3](https://user-images.githubusercontent.com/1319013/197361283-dde95f43-2d45-4bf3-8b10-8a72e07bbf54.png)
![MC2-Telegram4](https://user-images.githubusercontent.com/1319013/197361285-02c6a427-c670-4fd2-80a4-56d8647a3189.png)

**Comment by bravery-only** [comment]
> So far, I made good progress on using messaging features and adding it as a authentication factor. I still have to work on getting Telegram setup with phone or bot.
> 
> ![MC2-Telegram1](https://user-images.githubusercontent.com/1319013/197361277-a271ac6f-79a4-4535-abd5-eb61940110d0.png) ![MC2-Telegram2](https://user-images.githubusercontent.com/1319013/197361281-d973111c-8e60-42e6-a76b-f3549fccb224.png) ![MC2-Telegram3](https://user-images.githubusercontent.com/1319013/197361283-dde95f43-2d45-4bf3-8b10-8a72e07bbf54.png) ![MC2-Telegram4](https://user-images.githubusercontent.com/1319013/197361285-02c6a427-c670-4fd2-80a4-56d8647a3189.png)

I am very happy. You are great @Ylianst

**Comment by Ylianst** [comment]
Just got the Telegram setup using the phone done in MeshCentral. Use "--setuptelegram" and it will run you thru the right steps. I need to look at the bot technique next.

![MC2-Telegram5](https://user-images.githubusercontent.com/1319013/197365370-5eae9521-2c62-47c5-8baf-9267aade1735.png)

**Comment by bravery-only** [comment]
Is the notification of connecting and disconnecting the device also displayed in the Telegram bot? Or are you notified only for not logging in?

**Comment by bravery-only** [comment]
I could not install it. I am using Windows Server. Can you give me more advice?

![Telegram](https://user-images.githubusercontent.com/42680639/197392603-10916767-cf0d-4f1d-8299-beebd29f980d.jpg)

**Comment by si458** [comment]
> I could not install it. I am using Windows Server. Can you give me more advice?
> 
> ![Telegram](https://user-images.githubusercontent.com/42680639/197392603-10916767-cf0d-4f1d-8299-beebd29f980d.jpg)
> 
> 

It's only been pushed to github not released on npm yet
You have to wait for the next release

**Comment by Ylianst** [comment]
@si458 As usual you beat me to it. Yes, I was just about to say the same thing. This was not released yet. However, I just released v1.0.86 that has this feature so you can update and give it a try. Once setup, MeshCentral will only send the same messages that are sent with SMS which is not a lot (Account verification, 2FA and admin sent messages). However, if it works, I will add the option to have more notifications (device connect/disconnect, help requests, etc).

I do want to add help requests to SMS anyway.

For the `node node_modules/meshcentral -- setuptelegram` command, you need to run this in the MeshCentral folder, the one that had `meshcentral-data` and `node_modules` in it.

I am going to work on documenting this Telegram feature now.

**Comment by bravery-only** [comment]
Telegram is blocked in our country!! Is it possible to add the proxy function to the source?
Thank you, @Ylianst

**Comment by Ylianst** [comment]
You would need to be much more specific as to what you mean by "proxy function".

Note that I just added support for Discord, look here #4651. That will be in MeshCentral v1.0.91.

**Comment by bravery-only** [comment]
> You would need to be much more specific as to what you mean by "proxy function".
> 
> Note that I just added support for Discord, look here #4651. That will be in MeshCentral v1.0.91.

Thank you. Please add the agent disconnection and connection notification

**Comment by Ylianst** [comment]
Just added Telegram proxy support, take a look at #4697 for details. This will be in MeshCentral v1.0.95.

**Comment by panenka** [comment]
I got lost too. I have been made steps till Login As Bot, in step Login As User shows that Telegram is configured, but there is no Messaging section on any user. So I don't know how to use configured Telegram notification.
