### ISSUE TITLE
Notifications in discord (webhooks)

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#4651]
**Is your feature request related to a problem? Please describe.**

A lot of chat services allow the use of webhooks to send messages. I think a lot of users use services such as slack & discord on a regular basis.

**Describe the solution you'd like**

Integration of setting up webhook api's so ee can define what server to push webhooks to. Allows users to have a pick of where to send notifications. 

**Describe alternatives you've considered**

None

**Additional context**

Services such as uptimerobot and amp gaming server allow for use for webhook api's to send notifications. The login process for discord and slack are also quite secure. Could be a decent consideration for future integration

**Comment by Ylianst** [comment]
I am working on adding support for Telegram now and coded it so other services can be supported later like Signal Messenger and Discord.

**Comment by Ylianst** [comment]
I just added Discord support in MeshCentral, it will be published with v1.0.91. To help with setup, I added a section on [Discord here](https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/messaging/index.md).

![MC2-Discord1](https://user-images.githubusercontent.com/1319013/198361262-be528755-db0b-46e6-939b-8bf467226234.png)

![MC2-Discord2](https://user-images.githubusercontent.com/1319013/198361275-8f617047-a543-4e39-bb65-e2fb6cd33525.png)

You can also do 2FA with Discord notifications just like it's possible with Telegram. You can setup a MeshCentral server with both Discord and Telegram, but users can only register with a single service.

**Comment by JSuenram** [comment]
@Ylianst Maybe you can do the same for MS Teams, which also has Webhooks?

**Comment by vithusel** [comment]
Awesome! Ill get my instance updated tonight and setup. Ill close this issue once ive confirmed its working 🙂

**Comment by Ylianst** [comment]
@vithusel Thanks. Always good to get confirmation that these things work for other people. It's a lot of work to build so, also nice to know it's being used.

@JSuenram For Microsoft Teams, there is a issue open for that (#4655). No need to mention it here. Note that right now, MeshCentral sends notifications only, it does not receive anything so, webhooks are not used.

**Comment by vithusel** [comment]
> @vithusel Thanks. Always good to get confirmation that these things work for other people. It's a lot of work to build so, also nice to know it's being used.
> 
> @JSuenram For Microsoft Teams, there is a issue open for that (#4655). No need to mention it here. Note that right now, MeshCentral sends notifications only, it does not receive anything so, webhooks are not used.

You are a absolute legend. 

Tested and working fully. There is something thats not included in the documentation. 

Privleged Gateway Intents permissions is needed for the bot on Discord if not you get errors
![image](https://user-images.githubusercontent.com/31311292/198746203-88da5148-76bb-4b3a-9946-700109170663.png)

This is the error message you get when its not enabled. 

/home/meshcentraluser/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250
        throw new DiscordjsError(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/meshcentraluser/node_modules/discord.js/src/client/websocket/WebSocketManag>
    at async Client.login (/home/meshcentraluser/node_modules/discord.js/src/client/Client.js:232:7) {
  code: 'DisallowedIntents'
}

**Comment by Ylianst** [comment]
Thank you! I just [updated the documentation](https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/messaging/index.md) and used your perfectly framed screen shot. Much appreciated.
