### ISSUE TITLE
Win+Left and Win+Right are opposite.

### ISSUE THREAD

**Issue by southeasterntech** [Ylianst/MeshCentral#4657]
**Describe the bug**
When using the Win+Right, it located the window on the Left.... and Win+Left, Right.  This should be reversed

**To Reproduce**
1. Go to Lower Left corner
2. Click on Win+Left or Win+Right and it does the opposite of what it should

![image](https://user-images.githubusercontent.com/45638572/197526215-fe2d47ea-15ba-4300-be83-f71ace625081.png)

**Expected behavior**
Win+Left should locate window left, and right right

**Screenshots**

**Server Software (please complete the following information):**
 - 1.0.86
**Client Device (please complete the following information):**
 - Windows 10

**Remote Device (please complete the following information):**
 - Device: Windows 10, GEKTek mini PC
 - 
 - Network:Wifi

**Additional context**

**Comment by si458** [comment]
im not experiencing this issue here?
can you do a mini video or screenshots shwoing this issue?
what web browser are you using?

**Comment by southeasterntech** [comment]
So? seriously I?ve been seeing this for months. But today I try to go record it. Yep. Doesn?t do it. I don?t know. I?ll try again tomorrow. Delete this if I can?t produce the video.  Just dumb. Thanks 
 
      Thanks,
       
       Shane D. Lewis
       Southeastern Technical
       678-807-6156
       www.setechnical.net
           
         On Oct 24, 2022, at 10:37 AM, Simon Smith ***@***.***> wrote:
  
  
    ? im not experiencing this issue here?
   can you do a mini video or screenshots shwoing this issue?
   what web browser are you using? ?

**Comment by Ylianst** [comment]
I just tried it and I don't see the problem. Goes in the right direction. I will note that if the windows is already on the right and you send a `win + right` again, it will switch to being on the left.

**Comment by southeasterntech** [comment]
Ah? wonder if that?s what I was seeing.  Ok. Will try again tmw. Thanks for the response and sorry for the possible false alarm


   Thanks,
    
    Shane D. Lewis
    Southeastern Technical
    678-807-6156
    www.setechnical.net
       
    On Oct 24, 2022, at 6:42 PM, Ylian Saint-Hilaire ***@***.***> wrote:
 
 
 ? I just tried it and I don't see the problem. Goes in the right direction. I will note that if the windows is already on the right and you send a win + right again, it will switch to being on the left. ?
