### ISSUE TITLE
Raspberry Pi OS Lite (Legacy) Won't Connect With Static IP

### ISSUE THREAD

**Issue by UFOTyler** [Ylianst/MeshCentral#4658]
I use Raspberry Pi 4's as SBC's (Session Border Controllers) for VoIP phone installations using 3CX. I install Meshcentral in order to SSH into them for maintenance reasons, or as relays for remote support. I haven't deployed a new one in some time, but recently I did and when I set a static IP in the "dhcpcd.conf" file, upon reboot the Pi will not connect back to the Meshcentral Server. As soon as I set it to DHCP (comment out the lines) , it connects backup after reboot. 3cx only supports the older Debian Buster Raspberry Pi OS, so that's why I use that version. I've tested with both the Lite version and the full GUI version.

1. install Raspberry Pi OS (Legacy) with Raspberry Pi Imager
2. Install meshcentral with Linux command
3. set static IP in /etc/dhcpcd.conf
4. Reboot

Example of what to put at the end of the conf file for static IP

interface [INTERFACE]
static_routers=[ROUTER IP]
static domain_name_servers=[DNS IP]
static ip_address=[STATIC IP ADDRESS YOU WANT]/24

Server:
 - OS: Ubuntu
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]
 
 Client
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: Remote over WAN]

Remote Device:
 - Device: Raspberry Pi 4
 - OS: Raspberry Pi OS Lite (Legacy Buster)
 - Network: Remote over WAN]
 - Current Core Version: 429339336

**Comment by si458** [comment]
i believe you might have a miss config in dhcpcd.conf - https://www.makeuseof.com/raspberry-pi-set-static-ip/

`static_routers=[ROUTER IP]` should be `static routers=[ROUTER IP]`

**Comment by UFOTyler** [comment]
Oh my, you would be correct. That's what I get for copy and pasting from a note I made years ago.  I totally glanced over that when I was searching for solutions. Thank you. Problem seems to be solved.
