### ISSUE TITLE
MacOS agent stopped working after latest 13.0 update.

### ISSUE THREAD

**Issue by meh324** [Ylianst/MeshCentral#4664]
Upgraded my Macbook pro today to 13.0 and the agent no longer works. They changed a lot might be limiting the service. Anyone else having this issue?

**Comment by krayon007** [comment]
Interesting. I'll look into upgrading my macos to 13 and see if I can find out anything.

**Comment by iribarrenjg** [comment]
+1, after reinstalling it works but after a restart it stops working. Would assume something to do with starting the service. Need more time to diagnose.

**Comment by PetieM** [comment]
Seeing this same behavior on my freshly updated copy of 13. I plan to wipe and do a clean install and will update if that changes anything but I anticipate it will likely turn out the same.

**Comment by si458** [comment]
DUPLICATE #4822 CHECK THERE FOR SOLUTION
