### ISSUE TITLE
Custom client-side endpoint name.

### ISSUE THREAD

**Issue by krzysztofakc** [Ylianst/MeshCentral#4666]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem.

**Describe the solution you'd like**
Similar to TeamViewer, (ref. #4654) I propose a solution that when installing MeshAgent on the target device, it will be possible to assign a custom hostname that will not ever change.

Currently, when changing permissions for a service or manually changing a group, when MeshAgent reconnects to the server, the computer changes its name to the hostname.

I see two additional possibilities:

1. When changed server-side, the assigned name for the device will be saved "live" with Agent Update. Let's say, 5 min after the name change on the server, agent update kicks in, which causes the agent to always broadcast our custom name.

2. The name will be able to be given during the installation of the Agent and will remain so until it is changed server-side.

![image](https://user-images.githubusercontent.com/116161489/197713274-d4bf24b4-614c-4344-9889-7645606cdcf4.png)

**Comment by si458** [comment]
you can already create custom names for devices using the web panel rather than when you install the agent
you install the agent then the device shows up in the web panel,
then select the device in the webpanel with its hostname (of the device itself) 
then click the pencil next to the hostname at the top, 
then you can pick whatever name you want!

**Comment by krzysztofakc** [comment]
Similar to TeamViewer, (ref. https://github.com/Ylianst/MeshCentral/issues/4654) I propose a solution that when installing MeshAgent on the target device, it will be possible to assign a **custom hostname that will not ever change**, ex. name is based on HWID that's stored in database.

**Comment by silversword411** [comment]
You also have naming capabilities using the .msh file I believe. 
`agentName`
https://github.com/silversword411/MeshAgent
