### ISSUE TITLE
Shared WebRelay session cookie revocation.

### ISSUE THREAD

**Issue by SEsternO** [Ylianst/MeshCentral#4667]
I don't know if it's a bug or not, but right now after revoking the shared web relay, only sharing link is revoked, and not a cookie it saves in the browser for the relay domain. It means that even after the revocation of shared web relay the external user still has access to this relay through the saved and still active session cookie until the user closes the browser. This potentially restricts MeshCentral users to prevent malicious actions from an external user before it's too late for example.

Is it possible to revoke a cookie on the server side when revoking a web relay link?
Thanks.

**Comment by Ylianst** [comment]
That is a bug. Looking into it now.

**Comment by Ylianst** [comment]
Ok, fixed the guest web relay session revocation. Effect should not be immediate. Well be in v1.0.90.

**Comment by SEsternO** [comment]
Updated to 1.0.90, now it works like it should. Thank you very much!
