### ISSUE TITLE
ssh connected but i get black screen in the mesh terminal

### ISSUE THREAD

**Issue by Souheib-khiter** [Ylianst/MeshCentral#4668]
**Describe the bug**
i can connect in ssh but i get a black screen for SFTP no problème i'm in the version 1.0.0.89

![image](https://user-images.githubusercontent.com/73985086/197772135-cbfb3c9d-6bfa-4fc7-83de-a450991024b8.png)

![image](https://user-images.githubusercontent.com/73985086/197772258-48ee8c4b-8cfd-4372-a79e-f83c81310d13.png)

**Comment by si458** [comment]
**please can you follow the bug report template in the future as it helps us debug stuff quickly**
what is you `config.json` content?
what browser?
whats the remote device?

are you using minify at all?

**Comment by Souheib-khiter** [comment]
hello 
it was workging fine before

this issue is with all browser (chrom and firfeox)

the remote device its a centos server and when i tray to connect in ssh from the terminal of mesh it working fine 

 

My config.json fille

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral.sitiv.lan",
"mongoDb": "mongodb://meshcentral.sitiv.lan:27017",
    "mongoDbName": "meshcentral",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "MyReallySecretPassword1",
"authLog": "/var/log/mesh.log",
"port": 4430,
"aliasPort": 443,
"redirPort": 800,
"log": "main,web,webrequest,cert",
"syslog": "meshcentral",
"browserPing": 30,
"browserPong": 30,
"agentPing": 30,
"agentPong": 30,
"AllowHighQualityDesktop": true,
"SelfUpdate": true,
    "syslogjson": "meshcentral-json",
    "syslog": true,
    "syslogjson": true,
    "MpsPort": 0,
"TlsOffload": "127.0.0.1",
"_redirAliasPort": 999,
"localdiscovery": {
    "name": "mechcentral",
    "info": "YOUUPI"
}


  },

"smtp": {
 "host": "z8.atel.fr",
 "port": 587,
 "from": "meshcentral-donotreply@sitiv.fr",
 "user": "envoimail-gi@sitiv.fr",
 "pass": "FQzkTU5ImvcxFfFX9c0X",
 "_tls": true,
 "_tlsstrict": false
 },


  "domains": {
    "": {
      "title": "SITIV",
  "certUrl": "https://meshcentral.sitiv.lan:443/",
    "Footer": "SITIV2",
      "title2": "INFRA",
      "minify": true,
 "Backup": true,
 "__Restore": true,
 "__Upgrade": true,
 "__ErrorLog": true,
 "__Trace": true,
 "__Console": true,
 "_newAccounts": true,
 "agentInviteCodes": true,
 "allowFraming": true,
 "_userNameIsEmail": true,
 "novnc": true,
 "ssh": true,
 "rdp": true,
 "WebRTC": true,
 "mstsc": true,
 "allowLoginToken": true,
  "sessionrecording": {
            "onlySelectedUsers": true,
                "onlySelectedDeviceGroups": true,
        "filepath": "/opt/meshcentral/meshcentral-recordings",
        "index": true,
        "maxRecordings": 100,
        "maxRecordingSizeMegabytes": 100,
                "protocols": [ 1, 2, 100, 101, 200 ]
      }

    }

  },


  "__letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
     "__nochecks": true,
"__email": "mohamed.sabhi@al-enterprise.com",
    "__names": "mechcentralALCATEL",
"__rsaKeySize": 3072,
"__production": false
  }


}

**Comment by si458** [comment]
Can you try changing `minify` from `true` to `false` then restart meshcentral and try again?

**Comment by Souheib-khiter** [comment]
hello,

i did it nothing happened the same issue

**Comment by Ylianst** [comment]
Working on it! I see this issue.

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in v1.0.90. I also deleted previous messages as it seems a config.json was posted with confidential data it it. @Souheib-khiter, please be careful and never post your config.json to anyone. If you did post password and private data, please change your passwords rights away.

**Comment by Ylianst** [comment]
v1.0.90 is out, let me know if it works.

**Comment by Souheib-khiter** [comment]
Hello 

The issue resolved thanks for your intervention

about my config.json i chenged all confidentiels elements before posted it 

Thank you
