### ISSUE TITLE
Feature Request: Ability to login with your email address as well

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#467]
This would make login much easier as most people remember their email address. So they can login with their username or email address

**Comment by davscot** [comment]
Hi Johnnyq,

This is already possible, although you can either login with username OR login with email address, both cannot be active.

Setting for this is found in the config.json file. I'm not in front of my computer at the moment however If your stuck I can reference the exect setting you need to enable a little later on.

David.

**Comment by johnnyq** [comment]
thank you @davscot I do see the option now

**Comment by Ylianst** [comment]
Will close this issue since we have the "UserNameIsEmail" option for this. Feel free to offer feedback on this options if anything does not work.
