### ISSUE TITLE
Adding more OS update information

### ISSUE THREAD

**Issue by vithusel** [Ylianst/MeshCentral#4674]
**Is your feature request related to a problem? Please describe.**
Improved update notification across more operating systems

**Describe the solution you'd like**
This has to be broken down slightly. 

Windows - See the number of updates pending with a breakdown of normal, optional and critical. 

Linux - A visual indicator of pending updates (like we currently do for windows machines)

**Describe alternatives you've considered**

**Additional context**
Speaking solely from my perspective. It would be of great benefit for admins to be able to see if their machines / client machines have critical updates pending. Although Meshcentral wouldn't need the feature of being able to apply updates it gives admins a chance to action unsecure machines prior to a potential security event. 

With operating systems like Ubuntu. Its able to report to us in the MOTD about pending updates and how many there are. When connecting via Meshcentral by default we do not see this. I know the way Meshcentral connects to servers via SSH differs to ,as a example, connecting via Putty with local accounts. So being able to view this in the machines dashboard would be helpful. Im not sure however if there is a easy way to pull that information from linux OS's

**Comment by krayon007** [comment]
Is there a standard way to pull the update information on Linux? Any kind of telemetry is good telemetry. I just have to look up how to fetch this information. I'm guessing it's going to be distro specific.

**Comment by vithusel** [comment]
> Is there a standard way to pull the update information on Linux? Any kind of telemetry is good telemetry. I just have to look up how to fetch this information. I'm guessing it's going to be distro specific.

Its almost certainly going to be distro specific. However when it comes to linux. Supporting debian as a minimum would be a plus. Most users who use cent os and redhat distros already have a system in place to manage updates.

**Comment by si458** [comment]
> > Is there a standard way to pull the update information on Linux? Any kind of telemetry is good telemetry. I just have to look up how to fetch this information. I'm guessing it's going to be distro specific.
> 
> Its almost certainly going to be distro specific. However when it comes to linux. Supporting debian as a minimum would be a plus. Most users who use cent os and redhat distros already have a system in place to manage updates.

I disagree with that statement, we have a few freepbx/plesk system which are centos based and all we have is email notifications to say updates available, the upgrades still have to be done manually...

**Comment by si458** [comment]
closing as we wont be integrating this feature
