### ISSUE TITLE
Integration(notification/MFA) with XMPP client

### ISSUE THREAD

**Issue by maccn** [Ylianst/MeshCentral#4679]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem.

**Describe the solution you'd like**
It's good see the integration with Telegram & Discord recently implemented. It'll be great if XMPP client integration also can be supported.
XMPP is an mature open standard IM protocol for many years. Many great open source XMPP server software are used for self hosted instance messaging solution. e.g., [ejabberd](https://www.ejabberd.im/). And many good open source XMPP client also. e.g., [conversations](https://conversations.im/)
Thanks for your consideration.

**Describe alternatives you've considered**
it seems there're quite some nodejs lib can support XMPP protocol already.

**Additional context**
n/a

**Comment by Ylianst** [comment]
I just got a small sample working, so, integrating XMPP support into MeshCentral now.

**Comment by maccn** [comment]
Wow, so fast~ Much appreciated. 👍

**Comment by Ylianst** [comment]
Ok, added it in. This will be in MeshCentral v1.0.92.

![MC2-XMPP1](https://user-images.githubusercontent.com/1319013/198718063-44106289-d843-41a7-a75d-6b12dd854939.png)
