### ISSUE TITLE
Security Enhancement : Content Security Policy

### ISSUE THREAD

**Issue by Floche87** [Ylianst/MeshCentral#468]
I use MC over internet. That's why security is very important for me.

When i add this strict content security policies (add_header Content-Security-Policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';";) to my nginx, MC doesn't work as expected.
![Screenshot_20190902_114947](https://user-images.githubusercontent.com/51901584/64106454-7e491880-cd78-11e9-8a6d-79a02aa73e9d.png)

I must add multiple 'unsafe-inline' in the directive but it is less secure

Is it possible to change MC for integrate strict content security policy  ?

Thx

**Comment by Floche87** [comment]
I use same http headers in my configuration of nginx and all works good.
For session cookies, i don't have noticed issues for the moment.
a great thank for you

**Comment by Allowee** [comment]
Just an heads-up:

I tried to use mesh on my older linux laptop at home yesterday and got the "because it violates the following Content Security Policy directive: “connect-src 'self'”" error.
This is because the old browser does not allow the https to ws protocol switch.

more info: https://github.com/Fyrd/caniuse/issues/5052

**Comment by Ylianst** [comment]
Oh! Thanks for the head-up... that is... ugly. Working on it now.

**Comment by Ylianst** [comment]
MeshCentral v0.4.1-g is now live with a fix for the "heads up". Let me know if it works.

**Comment by Ylianst** [comment]
I am going to close this issue since the new HTTP headers seems to work as expected. Please re-open or file a new issue if needed.

**Comment by Allowee** [comment]
Checked this morning, this is fixed.
Thank you
