### ISSUE TITLE
The system in which the agent is installed ،shows off

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4680]
Is it possible that after some time a system has been installed in that agent, it will be turned off. After a few months, it will turn on and we will not have access to it?

**Comment by Ylianst** [comment]
Generally not. Once an agent is installed, it should stay installed and show online even after many months. The exception of course is if the user or anti-virus software removes the agent.

**Comment by bravery-only** [comment]
Which antiviruses remove the agent?
I know that East Internet does not remove

**Comment by vithusel** [comment]
> Which antiviruses remove the agent? I know that East Internet does not remove

I can only give a rather vague answer to this. 
The current set of Antiviruses that might block Meshcentral's agent might not be the same in a few weeks much less a few months. Different AV's will flash the agent as a virus or backdoor for different reasons. Your best bet is to whitelist the client on your antivirus. Either by setting a folder exception or filename. I wouldnt do the agent hash as if you update your server the client will also auto update. Thus changing the hash of the agent.

**Comment by silversword411** [comment]
> Which antiviruses remove the agent?
> I know that East Internet does not remove 

Which av have you seen to remove it?

**Comment by OutbackMatt** [comment]
I see Avast remove the agent, even if exceptions are set

**Comment by silversword411** [comment]
Yes, Avast is terrible. Stop using it, or get support to fix it
