### ISSUE TITLE
Crowdsec bouncer - Ban login after multiple failed logins - doesn't work

### ISSUE THREAD

**Issue by NickBootOne** [Ylianst/MeshCentral#4683]
**Describe the bug**
MeshCentral Crowdsec bouncer doesn't send a Ban for IP-address after multiple failed logins.

**To Reproduce**
Crowdsec Docker with Crowdsec bouncer in place within Mesh Central
Multiple times to login

**Expected behavior**
I'd expect that the bouncer will ban that IP address for like 4 hours

**Server Software (please complete the following information):**
 - OS: unRAID
 - Virtualization: Docker
 - Network: WAN Cloudflare
 - Version: 1.0.85

**Comment by NickBootOne** [comment]
Ah yes thank you very much, this was the last thing I was searching for, and thought it was possible with Crowdsec.
Thanks for all the hard work @Ylianst !!

**Comment by a1ad** [comment]
Hi @Ylianst it would still be very nice if the community can create a meshcentral crowdsec parser based on a log file. It would be nice to have all my services protected through one single system (crowdsec).

**Comment by a1ad** [comment]
fyi: [crowdsec parser](https://github.com/crowdsecurity/hub/pull/653) is available now.
