### ISSUE TITLE
How to configure session recording for users or devices groups

### ISSUE THREAD

**Issue by NickBootOne** [Ylianst/MeshCentral#4684]
**Describe your issue**
When adding session recording like below under domains nothing is showing up within the device groups
        
"sessionRecording": {
            "onlySelectedDeviceGroups": true,
            "index": true,
            "maxRecordings": 16,
            "maxRecordingSizeMegabytes": 100,
            "protocols": [1,2,200] 

**Screenshots**
![image](https://user-images.githubusercontent.com/59101602/198651096-b3b4d523-233a-4ecd-b297-9425c921a69b.png)

![image](https://user-images.githubusercontent.com/59101602/198652030-3817a796-9938-4807-82d0-87ea7541a9fd.png)

**Server Software (please complete the following information):**
 - OS: unRAID
 - Virtualization: Docker
 - Network: WAN Cloudflare
 - Version: 1.0.85

**Comment by NickBootOne** [comment]
Thank you @Ylianst this worked !
Also used the JSON Lint tool, this is indeed a better view after the fix !

**Comment by si458** [comment]
@martinbruckner77 you have every single `onlySelected*` set as `false`
so in its eyes its disabled and off
you need to either remove those options OR enable at least one of them

**Comment by martinbruckner77** [comment]
Thank you, you are absolutely right :)
