### ISSUE TITLE
Change the agent desktop background

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4686]
Is it possible to add this feature to change the background image of the agent's desktop?

**Comment by si458** [comment]
Can you please explain a use-case for this?

You generally only remove the wallpaper when you connect tobmake the remote support quicker and then put it back when you disconnect?

**Comment by Ylianst** [comment]
Try this button on the bottom right. It will toggle the remote desktop background. This can be used to speed up remote desktop.

![image](https://user-images.githubusercontent.com/1319013/198719845-1a1f9ea2-5e37-4095-a9d0-3e5af5e02d7e.png)

**Comment by bravery-only** [comment]
I mean to change the background image of the desktop screen with another image

**Comment by si458** [comment]
@Ylianst I believe the question was can he change the wallpaper, not toggle it off and on

**Comment by mwllgr** [comment]
You could use a Powershell script for that - at least if it's a static image, couldn't you?

**Comment by krayon007** [comment]
The wallpaper toggle code uses [this internally ](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa) 

I could add a helper method or a console command where you can specify an image file?

**Comment by bravery-only** [comment]
It would be great if you could send me a code to change the desktop background, but be sure to include this feature in Mesh Central.

**Comment by krayon007** [comment]
With server version 1.0.96, there is a console command `deskbackground`, which lets you get/set the windows desktop background image path.

**Comment by bravery-only** [comment]
I changed the background in Windows 7, but in Windows 10 it gives this error:
Command returned an exception error: child_process.execFile(): Could not exec [C:\Program Files\meshagent.exe]

**Comment by krayon007** [comment]
Does it give that error when fetching the desktop too, or only when setting it?

**Comment by bravery-only** [comment]
> Does it give that error when fetching the desktop too, or only when setting it?

only when setting it

**Comment by si458** [comment]
ive just tested this, and the feature works on windows 10 and 11
`deskbackground` -> returns the file path of the current image
`deskbackground c:\mystuff\mypic.jpg` -> set a new image

**Comment by si458** [comment]
update meshcore to show this as an option https://github.com/Ylianst/MeshCentral/commit/d9262f7c9da03881fd25c363f717f452d06e117d
