### ISSUE TITLE
Odd behavior with connected devices

### ISSUE THREAD

**Issue by bryanmcniel** [Ylianst/MeshCentral#4687]
Hi, I have been getting acquainted with MeshCentral for a couple months now and have noticed an odd behavior. It's possible that it may be my setup but wanted to ask before I tore it down and started over.

When viewing the My Devices page, all the connected machines show up as they should. Occasionally one or two will "wink off" or appear offline for about 10 seconds, then reappear as online again. If I am connected at the time, the remote machine is unresponsive until it reconnects. This happens to most all the machines and it occurs randomly. Also, when connected to one of these machines and performing a file transfer, It will only transfer about 15 or 20meg and then disconnect, corrupting the download (or upload).

Running version 1.0.56 on ubuntu 20.04. MeshCentral is sitting behind an Nginx reverse proxy. I am thinking the reverse proxy might be the cause of this behavior but wanted to get other peoples' input before doing anything drastic to an otherwise (sort of) running server. 

All agents are installed on Windows servers.

Any insight would be appreciated.

**Comment by vithusel** [comment]
Its almost certainly your reverse proxy. They tend to have a default connection Timeout. 

I use Haproxy myself and found it caused a few issue. Is there any particular reason your using a reverse proxy? Multiple servers running on port 80 or 443? If so you can set a custom agent communication port in the config which can bypass your reverse proxy.

**Comment by silversword411** [comment]
Definitely reverse proxy issues. Contact me for paid support.
