### ISSUE TITLE
Pushover notification support

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#4691]
**Is your feature request related to a problem? Please describe.**
Staff keep switching a certain computer off when they shouldnt

**Describe the solution you'd like**
I would like pushover support to notify me when a certain computer turned off/goes offline

**Describe alternatives you've considered**
N/A

**Additional context**
Pushover support could also be used for the login authentication token 2step stuff

https://pushover.net/api#messages

**Comment by Ylianst** [comment]
Pushover looks nice and simple. I will give it a try!

**Comment by Ylianst** [comment]
Added it, will be in MeshCentral v1.0.94.

**Comment by Ylianst** [comment]
The number of messaging integrations is getting large. I never expected having list when I started.

![MC2-CallMeBot2](https://user-images.githubusercontent.com/1319013/198896555-4e951006-627f-4d5a-a523-c1b3017a7cdd.png)

**Comment by Ylianst** [comment]
Pushover setup...

![MC2-Pushover2](https://user-images.githubusercontent.com/1319013/198897498-fc01f079-0323-4de2-b7c1-a08ba60e631b.png)

**Comment by Ylianst** [comment]
Added [Pushover documentation](https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/messaging/index.md#pushover-setup).

**Comment by si458** [comment]
Thanks but 1.0.94 wasn't published to npm

**Comment by Ylianst** [comment]
Oh. Thanks for reporting that. I must have messed up. I will be publishing v1.0.95 in a bit.

**Comment by mschubeck-redux** [comment]
@si458 I must be missing a new feature somewhere... where can offline alerts be configured?

**Comment by si458** [comment]
> @si458 I must be missing a new feature somewhere... where can offline alerts be configured?

this status change has only just been pushed to git recently https://github.com/Ylianst/MeshCentral/commit/1a6e78efeda27053e08d438012d7008e9e467233 so it wasnt added into 1.0.95 release, i think its going to be in 1.0.96 now

**Comment by mschubeck-redux** [comment]
awesome, thanks for sharing!

**Comment by Ylianst** [comment]
Indeed. Help requests and device state changes will be in v1.0.96 and will look like this:

![image](https://user-images.githubusercontent.com/1319013/199556549-98559b70-323b-4346-9883-e97d1fedeb77.png)

**Comment by si458** [comment]
thanks @Ylianst ive set it up and i got the verify code, BUT im not getting any notifications of devices going offline?
ive ticked the 'device disconnections' under notifications for every group i have
i then shut down a computer and no notification even after 15mins?
