### ISSUE TITLE
AMT provisioning without USB

### ISSUE THREAD

**Issue by GenuineJakob** [Ylianst/MeshCentral#4693]
**Describe your issue**
Hi, do you know if it is possible (without buying a 130€/year certificate) to get ACM working if the machine can't provision from USB? What would be the correct way to do this?

- Created a device group with "Intel AMT"
- "Full unprovision" of network access in the AMT settings on the device.
- Acquire Meshcentrals public key
- Enter hash into AMT device
- ?

**Client Device (please complete the following information):**
 - Device: [Gigabyte W480 Vision D]
 - Network: [WAN]

**Comment by Ylianst** [comment]
Hi. For Intel AMT ACM activation, there are only 3 ways:

 - Use MEBx to manually activate Intel AMT into ACM.
 - Use USB to setup trusted root + trusted FQDN. Server can use it's own certificate to activate.
 - Plug to Ethernet, have a DHCP with a known name and buy certificate with the name.

So, without buying a certificate or using USB you are left with only the manual MEBx way. I will note that ACM is difficult on purpose since it's a powerful feature and you can't just allow anyone to activate it. The other option is to use CCM which is easy to activate but has limitations of course.

Hope that helps.

**Comment by Ylianst** [comment]
Oh, first the first option you want to enable Intel AMT networking in MEBx and then give the admin password you used for that computer to MeshCentral. You don't generally type in the hash/fqdn manually, that takes a long time and they are removing the option to even do that in the latest versions of MEBx.

If you going to use the same admin password for lots of computers (which is not recommended for security), if you set that same password as the Intel AMT policy password in MeshCentral, MeshCentral will see the machine is already in ACM and will try the policy password to see if it works. If it does, it will use that and get things setup. There is also a way to provide a bunch of Intel AMT admin passwords to MeshCentral and MeshCentral will try them all to see if on works. If you need info on that, let me know.

**Comment by GenuineJakob** [comment]
<img width="556" alt="Screenshot 2022-11-01 at 20 43 44" src="https://user-images.githubusercontent.com/37959554/199324346-cc748627-5885-478b-b89c-3546d33a6dbc.png">
What I have tried so far is using meshcmd to configure the connection to Meshcentral. I gave Meshcentrals the admin credentials but the device is still in CCM. If I go into MEBx it says that with the current provisioning method ACM can't be activated. That's why I thought that I manually have to enter the hashes and configure the connection from MEBx.

It would be nice if you can go into further detail, what settings I have to configure in the MEBx.

**Comment by Ylianst** [comment]
Oh. I see. If the device is already in CCM, you may need to take it out of CCM using MeshCMD or go in MEBx and reset Intel AMT ("Full Unprovision"). Then, you should be able to go in MEBx and enable network access. Looks like this:

![image](https://user-images.githubusercontent.com/1319013/199345301-4790b238-8209-4662-a425-2048382cf025.png)

I have a video on [activating Intel AMT here](https://www.youtube.com/watch?v=mhq0bsWJEOw). In the video I use MeshCommander, but you can give the admin password to MeshCentral and it will also work.

**Comment by GenuineJakob** [comment]
~~Ok, but how can I add the device to MeshCentral? All devices I provisioned in the past via USB or meshcmd initialised the connection to the WAN MeshCentral server themself. I see the "import" button located in the AMT group. But the devices are not reachable via their FQDN (example "testmachine.localdomain").~~

What I have done so far:
- Reset AMT
- Changed password from admin to something secure
- Activated AMT
- Configured a hostname and fqdn
- Activated Network access
- Set user consent to none

How do I connect this machine to a WAN MeshCentral server?
A: Run the setup command (meshcmd amtconfig) with meshcmd.

Thank you for your time, I somehow messed up during my initial configuration and ended up in CCM.
Everything works now as expected.
