### ISSUE TITLE
Notifications in Zulip

### ISSUE THREAD

**Issue by cgb** [Ylianst/MeshCentral#4694]
**Describe the solution you'd like**
Hey Yilan, while you are a on a notification implementation frenzy, would you consider adding Zulip messaging support for notifications?  It's my self-hosted messaging platform of choice... :)

Welcome back and hope you had a good break!

**Comment by Ylianst** [comment]
Looks like there is a [client on NPM for it](https://www.npmjs.com/package/zulip).

**Comment by Ylianst** [comment]
Thanks. I just checked in support for Zulip but did not test it against a real server. Configuration is like this:

```
{
  "messaging": {
    email: "your-bot@zulip.com",
    api_key: "your_32_character_api_key"
  }
}
```

Will be in MeshCentral v1.0.95. Let me know if it works.

**Comment by Ylianst** [comment]
Latest messaging integrations:

![MC2-Messaging2](https://user-images.githubusercontent.com/1319013/199330367-cb747e04-3bdd-4cf4-bedd-312aa69ff25a.png)

**Comment by cgb** [comment]
Hey Yilan, thank you, it works perfectly for 2FA.  I submitted a small pull request to fix a typo in documentation

Looks like you are extending messaging support to include other kinds of notifications so looking forward to testing out.

Thanks again!
