### ISSUE TITLE
Multiple viewing sessions on the same host with multiple RDP sessions ?

### ISSUE THREAD

**Issue by NickBootOne** [Ylianst/MeshCentral#4695]
**Describe your issue**
When connecting to a active RDP session I can view the user I've connected to.
But when someone else connects to a different RDP session they connect to the same first connected viewing connecting.

So is it possible to activate multiple viewing connections to different RDP sessions ?

All RDP sessions are on the same host.

**Screenshots**
![image](https://user-images.githubusercontent.com/59101602/199244777-f4fca1bf-6d65-4991-b384-999e8914029f.png)

**Server Software (please complete the following information):**
 - OS: Windows Server 2019
 - Network: local
 - Version: 1.0.93

**Comment by Yogesh1190** [comment]
@NickBootOne Is there any solution for this scenario ?

**Comment by si458** [comment]
the way to do this is
1. click `connect` then pick the first rdp session
2. HOLD THE SHIFT KEY while clicking the remote tab in meshcentral ui
3. it will open up another tab, then click `connect` and select the second RDP session
