### ISSUE TITLE
Feature Request: Allow the agent to specify a name & description

### ISSUE THREAD

**Issue by deajan** [Ylianst/MeshCentral#470]
Hello,

Just found your project and gave it a quick try :)
I'm loving it so far, and might have a meshcentral test server installed soon.

So far so good, here's a feature that could be useful I think;

When using the agent as quick support or even as service, the computername is transferred as agent name to the server.
It would be nice to be able to override the computername, and perhaps add a description, so quick support sessions would become easy to identify.

Best regards.

**Comment by MailYouLater** [comment]
This could be useful for during agent installation too. If I know I'm going to want the device I'm installing the agent on to have a specific name (if that name is not what it's going to default to) it would be nice to set the name during installation and not have to find it in the device list and rename it later.
This could be especially useful during an initial deployment at a new location, where you're installing the agent on a bunch of computers at around the same time, and they may or may not already have meaningful computer names.

**Comment by deajan** [comment]
Exactly my thoughts too :)
Mass installations could use a parameter like `meshagent --name=WHATYOUWANT --description="AYBABTU"` ontop of a GUI option to set those for example.

**Comment by krayon007** [comment]
This should be easy to do. I can add as a DB setting, so you'll be able to specify it in the msh file. I'll take a look at it when I get in the office on Monday.

**Comment by Ylianst** [comment]
So yes, this is a good request. Bryan and I will be adding the feature so that you can specify the initial device name and description from the agent site.

**Comment by si458** [comment]
this feature exists in 2023
select a device and you have 'description' and 'tags' and even 'device name'
