### ISSUE TITLE
Option to shutdown all computers using CRON

### ISSUE THREAD

**Issue by CoodyCZ** [Ylianst/MeshCentral#4711]
Hi! I have a feature request, i know that is possible to set auto shutdown in each computer, but is there any way to implement function that allows shuting down all computers over agent, in selected time?

(sorry for bad english)

CoodyCZ

**Comment by dinger1986** [comment]
Maybe you need an RMM to run scheduled tasks etc? TacticalRMM is very capable otherwise you could use https://github.com/ryanblenis/MeshCentral-ScriptTask, I know that scripts are going to be more native in Mesh but maybe not as feature rich

**Comment by CoodyCZ** [comment]
Nice plugin! I will try it! ... But in another case, is there any option to  send a command to meshcentral server, that will shutdown all online compupters (by cron)?

**Comment by Ylianst** [comment]
If you want to perform operations on MeshCentral from a shell or script, try "meshctrl.js". [I have a video on this here](https://www.youtube.com/watch?v=p_jdtYJyuBQ). I also have [older documentation here](https://meshcentral.com/info/docs/MeshCtrlUsersGuide.pdf) that should get you started. Once you run it, you will see there is plenty you can script.

**Comment by CoodyCZ** [comment]
> Maybe you need an RMM to run scheduled tasks etc? TacticalRMM is very capable otherwise you could use https://github.com/ryanblenis/MeshCentral-ScriptTask, I know that scripts are going to be more native in Mesh but maybe not as feature rich

@dinger1986 great plugin! Tested on latest MeshCentral 1.0.96 - wokring properly! All selected PCs shutting down at selected time, period! Thank you!
