### ISSUE TITLE
dbExpire - latest update 1.0.96 - not clearing log

### ISSUE THREAD

**Issue by CoodyCZ** [Ylianst/MeshCentral#4717]
In version 1.0.96 when i'am using this function  in settings section:

 "dbExpire": {
      "events": 60,
      "powerevents": 60,
      "statsevents": 60
    }

The log is not cleared after interval. Nothing happends after F5 or CTRL+R in browser.

**Comment by ericmoon** [comment]
Are you able to verify that it is reading any of your config file?   I've updated to 1.0.96, and my instance isn't using db, but it doesn't seem to be reading any of my config.json file.

**Comment by CoodyCZ** [comment]
@ericmoon yes, i can confirm that it reads my config.json, i changed the _title and the new title is loaded

**Comment by ericmoon** [comment]
@CoodyCZ  Looks like 1.0.97 was just released to fix an issue with the config.json reading.

**Comment by CoodyCZ** [comment]
@ericmoon  @Ylianst  1.0.97 working properly! Thanks thanks thanks!
