### ISSUE TITLE
Config and DB problem after 1.0.96 update (starting as fresh install)

### ISSUE THREAD

**Issue by yomono** [Ylianst/MeshCentral#4719]
hello.
After updating to the last version, I lost access to my instance.
After digging a little more, I realized the monogodb is not being recognized. Meshcentral is creating a local database. Naturally is not recognizing any previous user or device, so is like a fresh install.
How can I rollback to v1.0.95 in the meantime?

**Comment by ericmoon** [comment]
1.0.97 fix my config issue.  upgrade and you should be good to go.

**Comment by yomono** [comment]
It worked, indeed. Thanks!
