### ISSUE TITLE
Some group actions are not working

### ISSUE THREAD

**Issue by mrflaunted** [Ylianst/MeshCentral#472]
If I have a few machines checked off and attempt to delete them or move them to a different mesh, that works. However, if I attempt to power down, reset or power up via the group actions button, nothing happens. The Actions button on the General tab does not work either, however, if I connect to a machine via the Intel AMT tab and send the command, it works without issue. 

I am currently running the latest MeshCentral server version 0.4.0-k. It is an agentless environment running via NPM. Intel AMT versions range from 9.x to 11.x.

**Comment by dinger1986** [comment]
WOL works fine anyway with mesh so maybe close? Maybe neds added to docs @si458

**Comment by si458** [comment]
Closing as wake up now works with wol and amt, have tested it myself
