### ISSUE TITLE
Repository descrition drops error on forking

### ISSUE THREAD

**Issue by lordofbikes** [Ylianst/MeshCentral#4724]
**Describe the bug**
This is about forking the main repository.
After some research I was able to fork, but the description length is an obstacle in this process, which not everybody may break down.

**To Reproduce**
1. Go to 'https://github.com/Ylianst/MeshCentral'
2. Click on 'Fork'
3. Leave settings untouched
4. Click on 'Create fork'

**Expected behavior**
A fork of https://github.com/Ylianst/MeshCentral is created in my own GitHub account.

**Screenshots**
A error message appear: 'Description cannot be more than 350 characters'
The fork process is abandoned, no fork created.

**Additional context**
A quick search listed different description length over time. It seems to be 100 and then 255 and probably more than 350 in past. But obviously now the limit is 350.

There is a related discussion on GitHub Community https://github.com/orgs/community/discussions/35743, posted recently, so this may have changed only lately.

The workaround comes from this discussion. On step 3, change the default description, which is the origin MeshCentral description, to be less than 350 characters. This allows to create the fork, but with a diverged repository description.

I suggest to adjust the repository description to less than 350 characters to eliminate this obstacle.
The additional content is cut-off, not shown in the repository, so this information is lost anyhow.
Eventually the extra content can be moved to README.md.

**Comment by si458** [comment]
this should be a simple for @Ylianst to fix
currently it shows 
```
This is a full computer management web site. With MeshCentral, you can run your own web server and it to remotely manage and control computers on a local network or anywhere on the internet. Once you get the server started, will create a mesh (a group of computers) and then download and install a mesh agent on each computer you want to manage. A… 
```

it is indeed way to long, just needs shrinking down

**Comment by Ylianst** [comment]
Make the description a lot smaller, let me know if that works.

**Comment by lordofbikes** [comment]
Works fine now, many thanks!
