### ISSUE TITLE
Impossible to log in using SAML - 404

### ISSUE THREAD

**Issue by phorcys420** [Ylianst/MeshCentral#4725]
**Describe the bug**
I cannot log in using SAML authentication since the ``/auth-saml-callback`` route 404s.

**To Reproduce**
1. Go to the login page
2. Click on the SAML authentication button
3. Authenticate with your provider
4. Provider redirects you to https://meshcentral.domain.tld/auth-saml-callback
5. Page 404s

**Expected behavior**
SAML redirect does not 404 and logs me in.

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Network: LAN+WAN, Caddy reverse proxy + ssl offload
 - Version: 1.0.97
 - Node: v10.19.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over WAN
 - Browser: Google Chrome]

**Screenshots**
![image](https://user-images.githubusercontent.com/57866459/200417262-e3e3eff0-aee9-4fc7-9d68-262e863de356.png)

**Additional context**
My auth provider is Authentik and as far as the authentication process goes, everything seems fine.
No errors in the MeshCentral output.
Removing ``callbackurl`` does not change anything.

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.domain.tld",                         
    "WANonly": true,
    "LANonly": true,
    "sessionKey": "jeff",                      
    "port": 80,
    "aliasPort": 443,
    "redirPort": 800,
    "AgentPong": 300,
    "TLSOffload": true,
    "SelfUpdate": true, 
    "AllowFraming": false,
    "mongodb": "mongodb://mongodb:27017/mesh",
    "mongodbcol": "mesh",
    "WebRTC": false
  },
  "domains": {
    "": {
      "title": "jeff",
      "minify": true,
      "NewAccounts": false,
      "certUrl": "https://meshcentral.domain.tld",
      "authStrategies": {
        "saml": {
          "callbackurl": "https://meshcentral.domain.tld/auth-saml-callback",
          "entityid": "authentik",
          "idpurl": "https://sso.domain.tld/application/saml/meshcentral/sso/binding/init",
          "cert": "saml.pem"
        }
      }
    }
  }
}
```

**Comment by phorcys420** [comment]
I figured it out by having a look at MeshCentral's source
Authentik's default setting is to use "Redirect" as a "Service Provider Binding", where MeshCentral only accepts "POST".
https://github.com/Ylianst/MeshCentral/blob/5b06fefdae75207b703ba9388d6c6e73ce8dedc2/webserver.js#L6647

I think this should be documented so that other people don't have the same issue.

**Comment by silversword411** [comment]
> this should be documented

Not quite following what should be documented. can you give a suggestion and I'll PR it
