### ISSUE TITLE
Add VNC agent

### ISSUE THREAD

**Issue by sieuwe** [Ylianst/MeshCentral#4734]
We are running version 1.0.95.
We have a device running an HMI in production which doesn't work with the MeshAgent that well.
When the MeshAgent is installed, the HMI crashes every hour.
We have a vnc server running on that machine, but it is the only one we don't have in MeshCentral and this is confusing for our end users.
Is it possible to add this device as an agent in MeshCentral with the VNC server?

**Comment by si458** [comment]
do you have a device at the site which has agent installed?
if you do try the following:
1. create an 'No agent devices relayed thru agent' group and select the relayed device as the remote device which has the agent installed
2. then add the device using its ip address to the group (select linux vnc as the type)
3. you should then have the option 'Web-VNC' which SHOULD do the trick for you!?

**Comment by sieuwe** [comment]
Yes that worked, I couldn't find it in the manual.
Thanks for the quick reply.
