### ISSUE TITLE
MeshCentral Router Ask Consent window title change, Agent process name change

### ISSUE THREAD

**Issue by yusha** [Ylianst/MeshCentral#4741]
Hello @Ylianst 

First off all, Amazing work done on MeshCentral, way to go.

I have two questions and they are regarding Rebranding of MeshCentral using config.json file.

1. Is there any way to change the title of MeshCentral Router's Ask Consent window from config.json? This appears on the client side when requesting Ask Consent using MeshCentral Router. Screenshot:

![1-Ask-Consent](https://user-images.githubusercontent.com/473559/200976331-b2d83541-0c10-45ac-9bf1-56f783d2cc31.jpg)

2. Is it possible to change the MeshCentral Agent's process name from config.json? Screenshot: 

![2-Background-Service-Agent](https://user-images.githubusercontent.com/473559/200975399-8a7ee85a-6f13-4e16-931d-3820ea02d8ee.jpg)

So far, I have been using these configs in the config.json file:

```
{ "settings": {
  },
  "domains": {
    "": {
      "Title": "Company MeshCentral",
      "agentCustomization": {
        "displayName": "MyCompany Agent",
        "description": "Allows MyCompany to provide full service remote support to this computer.",
        "companyName": "MyCompany IT",
        "serviceName": "MyCompany Remote Support Agent",
        "fileName": "MyCompanyAgent"
      }
    }
  }
}
```

Thank you,
Yusha

**Comment by si458** [comment]
in theory your config is correct?
```
 "agentCustomization": {
 	"displayName": {
 		"type": "string",
 		"default": "MeshCentral Agent",
 		"description": "The name of the agent as displayed to the user."
 	},
 	"description": {
 		"type": "string",
 		"default": "Mesh Agent background service",
 		"description": "The description of the agent as displayed to the user."
 	},
 	"companyName": {
 		"type": "string",
 		"default": "Mesh Agent",
 		"description": "This will be used as the path to install the agent, by default this is 'Mesh Agent' in Windows and 'meshagent' in other OS's."
 	},
 	"serviceName": {
 		"type": "string",
 		"default": "Mesh Agent",
 		"description": "The name of the background service, by default this is 'Mesh Agent' in Windows and 'meshagent' in other OS's but should be set to an all lower case, no space string."
 	},
 	"installText": {
 		"type": "string",
 		"default": null,
 		"description": "Text string to show in the agent installation dialog box."
 	},
 	"image": {
 		"type": "string",
 		"default": null,
 		"description": "The filename of a image file in .png format located in meshcentral-data to display in the MeshCentral Agent installation dialog, image should be square and from 64x64 to 200x200."
 	},
 	"fileName": {
 		"type": "string",
 		"default": "meshagent",
 		"description": "The agent filename."
 	},
 	"foregroundColor": {
 		"type": "string",
 		"default": null,
 		"description": "Foreground text color, valid values are RBG in format 0,0,0 to 255,255,255 or format #000000 to #FFFFFF."
 	},
 	"backgroundColor": {
 		"type": "string",
 		"default": null,
 		"description": "Background color, valid values are RBG in format 0,0,0 to 255,255,255 or format #000000 to #FFFFFF."
 	}
 }
```

you do need to uninstall any meshagent versions you have installed, then re-download and install the agent on each remote device tho after you have done any customization

**Comment by yusha** [comment]
Hello @si458 and @Ylianst 

The questions I have asked, they are currently not available in the config option. I asked, if it's possible to have these two options there. When you change the service name it doesn't change  MeshCentral Agent's process name in Task manager as shown in #2 Screenshot. For the #1 issue here, there's no options either to change the Mesh Router's title as shown in the screenshot.

**Comment by jobrien2001** [comment]
I can confirm this is the case for number 1 with the agent 

Also as well for number 2 with the assistant... If you click the arrow to show child process the service name is correct, but not the parent.
