### ISSUE TITLE
Feature Request: My events limitation to the user

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#475]
Hello.

Now, in the user's my events list contain all the events (made to a client which have on the user's list). I'd like to see just the events made by the user. Can you made it configurable (by admin), what events can show to the user, and what not?

For example, now if there is a group, which have a pc, and there is an user which have rights to this group, but no admin rights. If the admin connecting to the pc, than on the user's my event's list have contain that he admin connected. I don't want to see this, just the event's made by the user, who logged in.

Thanks

**Comment by pczolee** [comment]
Thank you!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.0-x with a new "Show Only Self Events" in the device group permissions. It will limit events the user can see to only device generated events and events they generate themselves. Let me know if that works.

![x](https://user-images.githubusercontent.com/1319013/65271166-748e1780-dad1-11e9-9711-a278fe427a1c.png)

**Comment by MailYouLater** [comment]
I would recommend "Show Only Own Events" instead of "Show Only Self Events".

**Comment by Ylianst** [comment]
Agreed, made the change. It will be in the next release.

FYI. Bryan and I have been testing the new MeshAgent. It's a big update so, I am going a lot of testing and we are fixing all sorts of things in it.

**Comment by pczolee** [comment]
Hi Ylianst. Thank you so much!

**Comment by Ylianst** [comment]
Updated screen in current version. I will close this issue, please re-open if needed.

![MC2-ShowOnlyOwnEvents](https://user-images.githubusercontent.com/1319013/65349554-8d153500-db98-11e9-9b7c-c8cc7d61be06.png)
