### ISSUE TITLE
Add Device idle timer

### ISSUE THREAD

**Issue by bradyrf** [Ylianst/MeshCentral#4750]
**Is your feature request related to a problem? Please describe.** Unable to connect to customers without interrupting work.
I would like the ability to know when a computer is idle or not actively being used by a customer so that I can start work when it is more convenient  and less interruptive to the customer. 

**Describe the solution you'd like**
Add an Idle time indicator that starts when there is no keyboard or mouse activity.
Example:
![meshcentral](https://user-images.githubusercontent.com/88627993/201355030-daafc637-0d9c-4cf1-b53f-940ad08c9091.png)

**Describe alternatives you've considered**
Calling users and asking if it is a convenient time to work on their computer.

**Additional context**

**Comment by bradyrf** [comment]
I have asked for a similar solution to this on reddit by having a small preview of the screen like connectwise control provides and Ylian said he felt this was too intrusive. Other users in the post suggested a screen idle timer would be a good compromise so that is what I am submitting.

**Comment by silversword411** [comment]
An idle time indicator is one of my most used things in screenconnect so you know when you can use the computer to do your IT work or not. 

Of note, screenconnect's small preview does have options:
How often it updates (default 15mins)
You can set a blurryness setting so you can't read words
You can enable or disable the feature
SC has an "update now" link which can be disabled
That preview helps me regularly. I've frequently seen the "reset PC" screen as the last screen on there...so I know someone reset the computer, and it's never coming back so I have to call to find out what happened/stolen computers etc. 

As of right now meshcentral if you want to creep it doesn't show any indication when you connect especially when you make sure input is not checked before clicking connect button so having an auto-updating preview doesn't improve privacy at all.

**Comment by si458** [comment]
Duplicate #1851
