### ISSUE TITLE
removal of device nodes using meshctrl

### ISSUE THREAD

**Issue by Takeiteasyeh** [Ylianst/MeshCentral#4753]
I have not found a way to actually remove a device through meshctrl.js after issuing an uninstall command and have not found another workaround other than doing it from inside the meshcentral ui.

Can this be added to meshctrl?

**Comment by Ylianst** [comment]
Your right. I had not noticed this, working on adding that now.

**Comment by Ylianst** [comment]
Added "removedevice" to meshctrl.js, will be in MeshCentral v1.0.98.

**Comment by tiagogbarbosa** [comment]
Sorry to reopen, but im trying to remove all offline from one group, but i think meshctrl is waiting for uninstall, because removedevice return 'ok' but dont remove the device from group/meshcentral

**Comment by si458** [comment]
> Sorry to reopen, but im trying to remove all offline from one group, but i think meshctrl is waiting for uninstall, because removedevice return 'ok' but dont remove the device from group/meshcentral

whats the command/exmaple you are using?

**Comment by tiagogbarbosa** [comment]
/srv/meshc/node_modules/meshcentral/meshctrl.js --url wss://mesh.xxxxxxx:443 RemoveDevice --loginuser xxxxxxxxx --loginpass xxxxxxxxx --id 'Y9UVQggLEoMSEpB2pmvY@EKoe7iYnXVYUVLwSuySVup3AOMSaHZyjGQlJFK5DnNi'

return "ok"

**Comment by si458** [comment]
> /srv/meshc/node_modules/meshcentral/meshctrl.js --url wss://mesh.xxxxxxx:443 RemoveDevice --loginuser xxxxxxxxx --loginpass xxxxxxxxx --id 'Y9UVQggLEoMSEpB2pmvY@EKoe7iYnXVYUVLwSuySVup3AOMSaHZyjGQlJFK5DnNi'
> 
> return "ok"

are you running the command from the meshcentral server itself or remotely?

**Comment by tiagogbarbosa** [comment]
it self, i think the command is correct, because i can listdevices and any other command, but, removedevice wont remove, just return ok

**Comment by si458** [comment]
never used the meshctrl but yeh just tried it and its the same here! 
it doesnt remove a computer thats inactive i specify
weird?

**Comment by si458** [comment]
@tiagogbarbosa foiund the bug for you! doing a PR soon to fix for you

WORKAROUND: if using the normal domain send `--id` as `node//IDGOESHERE` if using a subdomain use `node/DOMAINHERE/IDGOESHERE`

**Comment by tiagogbarbosa** [comment]
Ty!!!

*closed
