### ISSUE TITLE
Using MySQL causes AMT only devices to stop working

### ISSUE THREAD

**Issue by ringram74** [Ylianst/MeshCentral#4755]
**Describe the bug**
Running MeshCentral 1.0.97 in a docker container (this may be true without docker, as well, but I haven't tested that), configured to allow logins using LDAP (probably not part of the problem, but part of my config) and with MySQL configured as the database, when a device is added, it doesn't appear to even try to connect to the device and verify its AMT status.

**To Reproduce**
1. Install meshcentral 1.0.97 with npm per the installation instructions
2. Create config.json with mysql section to connect to your mysql database.
3. Start meshcentral.
4. Log in to meshcentral.
5. Create a new "Intel AMT only, no agent" group.
6. Add a device to the group.

**Expected behavior**
The expected behavior is that the new device will be probed and if the device is reachable and has AMT enabled, the device icon will turn blue and an "Intel AMT" tab will appear on the device page with a connect option. Also, if logging is enabled, there should be logs something like this:

```
9:33:47 PM - amt: Start Management, node//g2W2crMFjejbQ$oN30QfuNPEQlRf9MkOo@@o7NyE00LggUB5VPx2@Rt1NDUdVXcn, 3
9:33:47 PM - amt: myamthost, Checking Intel AMT state...
9:33:47 PM - amt: myamthost, Attempt Initial Contact, Local
9:33:47 PM - amt: myamthost, Attempt Initial Local Contact, 3, myamthost-mgmt.epic.com
9:33:47 PM - amt: myamthost, Direct-Connect, TLS, myamthost-mgmt.epic.com, admin
```

**Server Software (please complete the following information):**
 - OS: Ubuntu 18.04 LTS, Ubuntu 20.04 LTS
 - Virtualization: Docker
 - Network: LAN only, no additional special network configuration
 - Version: 1.0.97
 - Node: 19.0.1

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 
 - Network: Local to Meshcentral
 - Browser: Google Chrome, MS Edge, Firefox

**Remote Device (please complete the following information):**
 - Device: Dell Precision 3930
 - OS: Windows (not running an agent, AMT only)
 - Network: Local to Meshcentral
 

**Additional context**
The log messages after a device is added with MySQL as the database running MeshCentral 1.0.97 look like this:
```
9:22:41 PM - dispatch: DispatchEvent, *
9:26:27 PM - dispatch: DispatchEvent, *
```

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "no2FactorAuth": true,
    "LANonly": true,
    "meshErrorLogPath": "/opt/meshcentral/meshcentral-logs/",
    "authLog": "/opt/meshcentral/meshcentral-logs/auth.log",
    "log": [
        "cookie",
        "dispatch",
        "main",
        "peer",
        "web",
        "webrequest",
        "relay",
        "webrelaydata",
        "webrelay",
        "mps",
        "mpscmd",
        "swarm",
        "swarmcmd",
        "agentupdate",
        "agent",
        "cert",
        "db",
        "email",
        "amt",
        "httpheaders",
        "websocket"
    ],
    "mysql": {
      "host": "my.mysql.host",
      "user": "meshcentral",
      "password": "thepassword"
    }
  },
  "domains": {
    "": {
      "title": "MeshCentral",
      "auth": "ldap",
      "ldapOptions": {
        "url": "ldaps://mydomain.com:636",
        "tlsOptions": { "rejectUnauthorized": false },
        "bindDN": "ldapuser@mydomain.com",
        "bindCredentials": "ldappassword",
        "searchBase": "dc=mydomain,dc=com",
        "searchFilter": "(sAMAccountName={{username}})",
        "reconnect": true
      },
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "objectSid",
      "ldapUserEmail": "mail",
      "ldapUserRealname": "{{{givenName}}} {{{sn}}}",
      "ldapUserGroups": "memberOf"
    }
  }
}
```

**Comment by si458** [comment]
closing this as stale,
please try the latest version 1.1.20 and use node 18 or above and try again,
if your issue still persists, then please reply back
