### ISSUE TITLE
Web proxy

### ISSUE THREAD

**Issue by 12nick12** [Ylianst/MeshCentral#4761]
**Is your feature request related to a problem? Please describe.**
Like the VNC/RDP/SSH Relay thru agent, but for http/s traffic. Useful for web admin on routers. 

**Describe alternatives you've considered**
You could use the mesh router. This works, bit it'd be nice to be able to have it all on the web. 

**Additional context**
Thanks for your work. MC is awesome.

**Comment by Ylianst** [comment]
Hi. Take a look at the MeshCentral "Web Relay" feature. There is a [basic video here](https://www.youtube.com/watch?v=GU7MQjkPSd8) and a [more advanced way to set it up here](https://www.youtube.com/watch?v=INOvsHXNOKY). The [blog on the introduction of web relay is here](https://meshcentral2.blogspot.com/2022/07/meshcentral-web-relay-per-account-ssh.html).

MeshCentral Router will always work a bit better for some sites, but MeshCentral web relay should allow you to access HTTP/HTTPS sites thru the MeshAgent without using MeshCentral Router.

**Comment by 12nick12** [comment]
Thank you, I was unaware of this. Is this safe to be public? Also is there anything else I need to add to harden security other than `RelayDNS`? 

Also is there a better way to add a `HTTP/S` only device other than adding them as a `Linux VNC/SSH` device?

**Comment by 12nick12** [comment]
Also can I have more than 3 web relay URLs?

**Comment by troymroberts** [comment]
> Hi. Take a look at the MeshCentral "Web Relay" feature. There is a [basic video here](https://www.youtube.com/watch?v=GU7MQjkPSd8) and a [more advanced way to set it up here](https://www.youtube.com/watch?v=INOvsHXNOKY). The [blog on the introduction of web relay is here](https://meshcentral2.blogspot.com/2022/07/meshcentral-web-relay-per-account-ssh.html).
> 
> MeshCentral Router will always work a bit better for some sites, but MeshCentral web relay should allow you to access HTTP/HTTPS sites thru the MeshAgent without using MeshCentral Router.

How would i go about connecting to a device that uses a non-standard port. E.g. a PBX with port 8089?

**Comment by troymroberts** [comment]
> > Hi. Take a look at the MeshCentral "Web Relay" feature. There is a [basic video here](https://www.youtube.com/watch?v=GU7MQjkPSd8) and a [more advanced way to set it up here](https://www.youtube.com/watch?v=INOvsHXNOKY). The [blog on the introduction of web relay is here](https://meshcentral2.blogspot.com/2022/07/meshcentral-web-relay-per-account-ssh.html).
> > MeshCentral Router will always work a bit better for some sites, but MeshCentral web relay should allow you to access HTTP/HTTPS sites thru the MeshAgent without using MeshCentral Router.
> 
> How would i go about connecting to a device that uses a non-standard port. E.g. a PBX with port 8089?

Ok So i figured out how to change the port and it's one step forward one step back.

I can get to the login page of the PBX but when i click login i don't get any further.

**Comment by 12nick12** [comment]
> > Hi. Take a look at the MeshCentral "Web Relay" feature. There is a [basic video here](https://www.youtube.com/watch?v=GU7MQjkPSd8) and a [more advanced way to set it up here](https://www.youtube.com/watch?v=INOvsHXNOKY). The [blog on the introduction of web relay is here](https://meshcentral2.blogspot.com/2022/07/meshcentral-web-relay-per-account-ssh.html).
> > MeshCentral Router will always work a bit better for some sites, but MeshCentral web relay should allow you to access HTTP/HTTPS sites thru the MeshAgent without using MeshCentral Router.
> 
> How would i go about connecting to a device that uses a non-standard port. E.g. a PBX with port 8089?

I'm not sure about your newest comment, but to access non standard ports you right click on http/s and input the port. 
https://user-images.githubusercontent.com/1319013/176830692-61e187ab-01cd-4901-af48-e72bdc922050.png
