### ISSUE TITLE
Traefik RP: Upload files on some devices does not work

### ISSUE THREAD

**Issue by johann8** [Ylianst/MeshCentral#4762]
**Describe your issue**
A clear and concise description of what your issue is.

Traefik RP: Upload files on some devices does not work.
I had some time yesterday to investigate a bit more the problem I described here https://github.com/Ylianst/MeshCentral/discussions/4661. Before that I took the same device over and over again to test if uploading files works. And I have assumed until yesterday that it is due to traefik configuration. Yesterday I noticed that upload works perfectly fine on some devices, but not on the others. On all Debian devices, for example, the upload works. On no Rocky/Oracle Linux device does upload work. On most Windows 2019 Server and Windows 10/11 devices, upload works. On Windows Server 2016/2012R2 it does not work. The funny thing is that even though the devices are on the same network, uploading files does not work on some devices. I could not see any correlations. The routers are almost identical on all networks and are configured the same.
On all devices where the upload does not work, the browser console displays the message: 

`WebRTC: ICE failed, add a STUN server and see about:webrtc for more details .`

How can I debug the problem?
PS. Sorry for my english

**Server Software (please complete the following information):**
 - OS: RockyLinux 8
 - Virtualization: Docker
 - Network: WAN, traefik reverse proxy
 - Version: 1.0.97
 - Node: 18.5.0

**Client Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 11
 - Network: Remote over WAN
 - Browser: Mozilla Firefox

**Remote Device (please complete the following information):**
 - Device: Server, Laptops, Desktop PC
 - OS: Debian, Rocky/Oracle Linux, Windows 10/11, Windows Server 2019/2016/2012
 - Network: Remote over WAN
 - Current Core Version: Windows Aug 25 2022, 241527007; Linux Aug 29 2022, 3684156261

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mc.mydomain.de",
    "WANonly": true,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "AgentPong": 60,
    "_BrowserPing": 60,
    "BrowserPong": 60,
    "TLSOffload": "traefik",
    "TrustedProxy": ["traefik", "172.26.1.0/24"],
    "WebRTC": true,
    "WebRtcConfig": {
       "iceServers": [
         { "urls": "stun.stun.l.google.com:19302" },
         { "urls": "stun:stun.gmx.de:3478" },
         { "urls": "stun:stun.1und1.de:3478" }
      ]
    },
    "AllowHighQualityDesktop": true,
    "desktopMultiplex": true,
    "DesktopMultiplexor": true
  },
  "domains": {
        "": {
    "title": "REMOTE SUPPORT PORTAL",
    "title2": "WG",
    "minify": true,
    "NewAccounts": "false",
    },
    "agentConfig": [ "webSocketMaskOverride=1" ],
    "certUrl": "https://mc.mydomain.de:443",
    "agentInviteCodes": true
  }
}
```
about:webrtc
![grafik](https://user-images.githubusercontent.com/13717874/201878469-820450e4-5e97-4a69-81e6-ce4dff703bac.png)

![grafik](https://user-images.githubusercontent.com/13717874/201879026-f1279e2f-0d1c-4b82-a6dc-f45b02274f9a.png)

![grafik](https://user-images.githubusercontent.com/13717874/201879681-6ca5b0c1-6040-4234-be37-68ac07c23bf5.png)

**Comment by NiceGuyIT** [comment]
Your issue is the same as #4907. Websocket compression does not work with Traefik. Only `AgentWsCompression` is required to be false to fix your problem, but you can disable the others and set compression in Traefik.

Disable compression in MeshCentral.
```json
{
	"settings": {
		"Compression": false,
		"WsCompression": false,
		"AgentWsCompression": false,
	}
}
```

Enable compression in Traefik by following the docs to [enable compression](https://doc.traefik.io/traefik/middlewares/http/compress/) in your environment.

Lastly, WebRTC has better performance than websockets, and if enabled overrides websockets. If you don't specify the `iceServers`, defaults will be used.
```json
{
	"settings": {
		"WebRTC": true,
		"webrtcConfig": {
		  "iceServers": [
			{ "urls": "stun:stun.services.mozilla.com" },
			{ "urls": "stun:stun.l.google.com:19302" }
		  ]
		},
	}
}
```

**Comment by johann8** [comment]
Hi,
I have now tested on the test machine. Traefik compression turned on and websockets compression turned off in meshcentral. It actually works fine now. Thanks for the great tip!
