### ISSUE TITLE
HW Connect not working with AMT v16.1.25

### ISSUE THREAD

**Issue by gabecz** [Ylianst/MeshCentral#4765]
On our Dell SFFs arrived with BIOS v1.3.62, and Intel AMT v16.0.15 which with Intel AMT HW Connect worked fine, however after the Dells updated themselves to Intel AMT v16.1.25 HW Connect won’t work anymore. We still can connect and get / set info on the IntelAMT tab, but none of the HW Connect options work anymore aka we can’t access the BIOS remotely, neither can we PXE boot them anymore. Is this a known issue with the new Intel ME & Mesh (?) or something that you’re currently working on, or we have an extra step to take to make HW Connect work again? I even went to the server room and fully unprovisioned one of the desktops and set it up again from scratch, but no luck. Reinstalled the agent downloading a fresh copy also did not help.

**Comment by jsastriawan** [comment]
Are you able to check if KVM works using MeshCommander desktop version? There is some difference in the way digest authentication is performed on meshcommander desktop version and Meshcentral AMT credential interceptor.js. Updated AMT firmware may require 8bytes NC value. I sent PR on this yesterday.

**Comment by si458** [comment]
closing as stale, please update to the latest version 1.1.20 which has a few AMT fixes, and make sure to use node 18 or above,
if your issue still happens, plz reply
