### ISSUE TITLE
Intel AMT Power Off action doesn't work if connected to the KVM

### ISSUE THREAD

**Issue by jirijanata** [Ylianst/MeshCentral#4768]
Hello everyone, first of all, thank you for all your amazing work. I just found, that Intel AMT Power Off doesn't work, if someone is connected to the KVM. All other actions, like Intel AMT Reset and Reset to BIOS are working fine. I know, it's not a big problem, but maybe it can be fixed in the future.

**AMT Version**: Activated ACM, v11.8.92, TLS, CIRA
**MeshCentral**: 1.0.98

Device Group - Intel AMT only, no agent - some Computer - Desktop - Actions
> Intel AMT Reset - performPowerAction, 10
> Intel AMT Power Off - performPowerAction, 8 - doesn't work - nothing will happen.
> Intel AMT Reset to BIOS - performPowerAction, 12
> Inter AMT Power on to BIOS - performPowerAction, 11
> Intel AMT Power on - performPowerAction, 2

I can see the action 8 in the trace, but nothing happens. The problem is/was that I was also connected to KVM to check, what happens.

I also tried RealVNC (it has an Intel AMT mode), and from that app Power Off is working just fine, but it will first disconnect the KVM session.

I tried also to capture the Power Off communication between RealVNC and Intel AMT and RealVNC is doing this:
POST RequestStateChange 32768
POST RequestPowerStateChange 8
POST RequestStateChange 32771

**Expected behavior:**
If you will go to the `General - Actions - Intel® AMT Power off` or `Desktop - Actions - Intel® AMT Power off` or `Intel®AMT - Power Actions ... - Power down` than should be there some check in the background, that if a KVM session to this specific computer is connected, than this session will be disconnected before the RequestPowerStateChange 8 will be sent.

On the General and Desktop tab will pop up a confirmation window - this can be changed to something like this:
`Perform Intel® AMT power off? KVM sessions to this computer will be disconnected.`

**Comment by jsastriawan** [comment]
It is a well known behaviour.
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/intelamtpowerstatetransitions.htm

If there is a redirection session (either KVM, SOL or Storage), those actions involving hard power reset will not work. Redirection session must be terminated to first.

**Comment by crass** [comment]
Can AMT be queried for active redirection sessions and the user notified? Like have a string of red text in the power state change modal saying that certain power transitions are invalid while active redirection sessions exist. Maybe as a first step just always have that text.

**Comment by crass** [comment]
So there are 3 places that I've found where the power state can be transitioned from within a device in "My Devices":

1. Intel AMT tab -> System Status -> Power link
2. Intel AMT tab -> System Status -> "Power Actions" button
3. General tab -> "Actions" button

The first two seem to take equivalent code paths. There is a red warning label saying "Some power actions may result in data loss and may disconnect the desktop, terminal or disk redirection sessions." Based on the documentation given here, this seems wrong or at best misleading. Its not that the sessions will get disconnected, its that connected sessions prevent the action from happening.

The third has less options for power transition and no warning.

I'd suggest that the first two have a more correct warning and the last have the same warning added.

**Comment by si458** [comment]
ive added a warning to the 'Intel AMT power off command for you', so will close this issue https://github.com/Ylianst/MeshCentral/commit/227b4c68e76b5ed04fbb75a51dd9d340316106f8
![image](https://github.com/Ylianst/MeshCentral/assets/765314/60de23f4-4f82-41f8-8247-971fc8c6ed1b)

also with intel amt 9 or above, the is an extra command called 'Soft-off' `12 (Power Off - Soft Graceful)`
this basically send a signal to the OS that it is shutting down (like pressing the power button) and it still lets me watch the OS shutting down
i have verified this with my intel amt 12 computer and that works a treat but my amt 7 doesnt have this feature!
i could look at adding this but please open a new enhancement request if this is needed
