### ISSUE TITLE
Error calling WTSEnumerateSessionsA: 5 in method 'handleServerCommand()' (update 1.0.98)

### ISSUE THREAD

**Issue by krzysztofakc** [Ylianst/MeshCentral#4769]
**Describe the bug**

Can't connect to endpoint by web stream using latest update. Terminal and file transfer works fine.

> info
Current Core: Aug 25 2022, 143332014
Agent Time: 2022-11-16 13:44:54.026+01:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Built-in LMS: Disabled.
OS: Microsoft Windows 10 Home - 21H1/19043.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner, win-console, win-deskutils, win-info, win-securitycenter, win-terminal, win-virtual-terminal, win-volumes.
Server Connection: true, State: 1.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
