### ISSUE TITLE
Help with Session Recordings

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#477]
I have a problem with meshcentral, I am trying to configure the tool to record the remote access session. Could you help me or send me step by step?

Thank you very much in advance.

**Comment by pczolee** [comment]
Well, this is the sample config:
_"_SessionRecording": {
        "_filepath": "C:\\temp",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
      }_

But for me in linux with this:
      _"SessionRecording": {
        "filepath": "/home/meshcentral/recordings/",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 5 ]
      }_

The meshcentral not working:

_# /usr/bin/node /home/meshcentral/node_modules/meshcentral
ERROR: Unable to parse /home/meshcentral/meshcentral-data/config.json._

I'm in 0.4.0-k version.

**Comment by pczolee** [comment]
Unfortunately I can do anything, the  problem is the same.
_(ERROR: Unable to parse /home/meshcentral/meshcentral-data/config.json.)_

Here is the related part of my config:

_"domains": {
    "": {
      "Title": "Meshcentral",
      "Title2": "Servername",
      "_TitlePicture": "title-sample.png",
      "_UserQuota": 1048576,
      "_MeshQuota": 248576,
      "_NewAccounts": true,
      "_UserNameIsEmail": true,
      "_NewAccountEmailDomains": [ "sample.com" ],
      "_NewAccountsRights": [ "nonewgroups", "notools" ],
      "Footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
      "_CertUrl": "https://192.168.2.106:443/",
      "_PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true },
      "_AgentNoProxy": true,
      "_GeoLocation": true,
      "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
      "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
      "_AgentAllowedIP": "192.168.0.100/24",
      "_AgentBlockedIP": "127.0.0.1,::1",
      "___UserSessionIdleTimeout__" : "Number of user idle minutes before auto-disconnect",
      "_UserSessionIdleTimeout" : 30,
      "__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
      "_UserConsentFlags" : 7,
      "_Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      },
      "_AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
      "_Redirects": {
        "meshcommander": "https://www.meshcommander.com/"
      },
      "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
      "_httpheaders": { "Strict-Transport-Security": "max-age=360000" },
      "_agentConfig": [ "webSocketMaskOverride=1" ]
      "SessionRecording": {
        "filepath": "/home/meshcentral/recordings/",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 5 ]
      }
    },
    "customer1": {_


If I delete the following lines (so without sessionrec) there is no problem:
      _"SessionRecording": {
        "filepath": "/home/meshcentral/recordings/",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 5 ]
      }_

**Comment by MailYouLater** [comment]
@pczolee: The line `"_agentConfig": [ "webSocketMaskOverride=1" ]` needs to end with a comma.

**Comment by pczolee** [comment]
> @pczolee: The line `"_agentConfig": [ "webSocketMaskOverride=1" ]` needs to end with a comma.

Thanks. That was the problem! The sample had no comma... Now it is working! Where is the player?

**Comment by geanferrani123** [comment]
Friends, i can converter the record for other extension?

**Comment by geanferrani123** [comment]
Friends, i got it enable for recording session, but unfortunately i could not player record with /player.htm, how do i enable /player.htm?

**Comment by Ylianst** [comment]
The player is a static web page, so [you can use this one](https://alt.meshcentral.com/player.htm). However, if you update your MeshCentral server, you should have the player page. It should always be enabled.

Go in "node_modules\meshcentral\public" and see if you have the "player.htm" file.

**Comment by geanferrani123** [comment]
Friends, to upload the recording to a network shared directory on a windows server, will I need to install samba inside my meshcentral server? (is running on ubuntu server)

**Comment by Ylianst** [comment]
Well, you can specify the path to save the recording files in config.json, so you could use a shared directory or a script that copies the files periodically.

**Comment by Ylianst** [comment]
FYI. Just did a silent update of MeshCommander v0.7.8 with added session recording player as an additional tab. It will play MeshCentral recordings.

![x](https://user-images.githubusercontent.com/1319013/64915247-bdcc1900-d717-11e9-949e-dcc844dea28a.png)

**Comment by Ylianst** [comment]
Ok, will close this issue. If there are any problems or suggestions for sessions recordings, please make sure to file another issue.

**Comment by singalok** [comment]
I tried version 10.1.10 with terminal recording,but its not working. I have tried both option to drag the file into the player as well as tried to open the file for play in the player. I see below error in browser console.

![Capture](https://github.com/Ylianst/MeshCentral/assets/48016040/bceb1566-653b-48c3-bfbf-adbb336e719a)

**Comment by si458** [comment]
Hi, im not sure where you are getting that version number from, but the latest version is 1.1.16,
can you try updating and see if this helps?
as i can see line 1112 in the player.html is indeed the `writeUtf8` function, but it should only be called if your player supports `writeUtf8`

**Comment by singalok** [comment]
Ok, i will try the latest version and see if that works for me. I was having trouble installing node version 11 in my linux environment  and thats why i went to a lower version which is compatible with the older version of node. But I will try to see if I overcome my node version issue and install the latest version.Will let you know the result.

**Comment by si458** [comment]
Sadly u will need a newer node version 12 =>
so it's best to update now!

**Comment by singalok** [comment]
Ok,yes I now have the latest version of npm and node. I will try and see how it goes.Just need to do some configurations.

Thanks for your quick reply. Will let you know if I face the same issue.

**Comment by singalok** [comment]
Hi Again, the latest version worked perfectly fine . Thanks.
