### ISSUE TITLE
I  start MeshCentral with http access, but the MeshCentral Agent cannot connect

### ISSUE THREAD

**Issue by yylstudy** [Ylianst/MeshCentral#4774]
**Describe your issue**
I want to start MeshCentral via http access, but the MeshCentral Agent cannot connect，The access to the MeshCentral Web page is normal. 
![image](https://user-images.githubusercontent.com/26402953/202342724-2a57d7d8-954d-4f3f-8923-8b5640fddd4b.png)

The device group is added successfully, but the client device cannot see the MeshCentral Web after installing the MeshCentral Agent，I think it's the following reason，Server Url was wss://，but port 443 of the MeshCentral  server is http
![image](https://user-images.githubusercontent.com/26402953/202342146-a7f63476-5bcf-4939-871a-4908844f931b.png)
How to configure the server URL to be ws://

**Screenshots**

**Server Software (please complete the following information):**
 - OS: centos7
 - Version: [e.g. 1.0.98]

**Client Device (please complete the following information):**
 - OS: centos7
 - Browser: Chrome

**Remote Device (please complete the following information):**
 - OS: Windows 10 

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_sessionKey": "MyReallySecretPassword1",
    "MongoDb": "mongodb://xxx:27017/meshcentral",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 300,
    "allowLoginToken": true,
    "allowFraming": true,
    "NoTls": true,
    "TlsOffload": true
  },
  "domains": {
    "": {
      "Title": "",
      "Title2": "",
      "TitlePicture": "",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

```
Please help me to see what the reason is. Thank you。

**Comment by silversword411** [comment]
You want to install a remote access tool with root level access without encrypting traffic???

**Comment by si458** [comment]
meshcentral REQUIRES HTTPS use and WSS
it will not work with HTTP and WS sorry
