### ISSUE TITLE
How can I change MeshCentral management access link?

### ISSUE THREAD

**Issue by MohammadAhmadiAfrapoli** [Ylianst/MeshCentral#4778]
Hi
I installed MeshCentral on my server and after installation the server link has a port 444 on the end of link.
The link is something like the : https://subdomain.domain.com:444
The default port 443 is reserved for another app(plesk).
How can I change port 444 ?
If plesk remove from my server, does Mesh Central and its agents will work?

**Comment by MohammadAhmadiAfrapoli** [comment]
> _DISCLAIMER_ I'm not speaking for the developers, just giving my own experience.
> 
> It is a bad idea to have MeshCentral bound to port 444. Even if it can be done logistically, port 444 is typically blocked by various firewalls and communication routes on networks while port 443 is nearly always open for general SSL traffic. That would make its features spotty, at best.
> 
> If you're using Plesk simply to access and control just the one server on which it's installed, then I would advise moving that to port 444 instead of MeshCentral. But if you're using that Plesk installation to manage multiple devices, then my advice is to spin up another VM dedicated to MeshCentral instead.

Thanks a lot

**Comment by phorcys420** [comment]
You should look into setting up a reverse-proxy like nginx so you can assign MeshCentral to a subdomain and Plesk to another one.

**Comment by MohammadAhmadiAfrapoli** [comment]
👍🙏

**Comment by si458** [comment]
closing as you will need to use a reverse proxy to divert mc.domain.com to subdomain.domain.com:444
