### ISSUE TITLE
Instructions for Changing Domain

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#478]
Is it possible to manually repoint the agents to a new domain and if so could you please provide some instructions?

**Comment by Ylianst** [comment]
Good questions. You can change the TLS certificate and the agent will still connect. For example, you need to update Let's Encrypt certificate every 60 days. The way the agent authenticates the server is explained in the [MeshCentral Design & Architecture Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2DesignArchitecture.pdf).

Quick summary: The "ServerID" is the hash of the "agentserver-cert-public.crt" certificate in your "meshcentral-data" folder. This is the certificate that can't change. Changing the TLS cert is ok, the agent makes a secondary check to authenticate the "agentserver". Hope this helps.

![AgentCertCheck](https://user-images.githubusercontent.com/1319013/64875354-caf6e400-d601-11e9-93b6-b10a6a5c2aa3.png)

**Comment by MailYouLater** [comment]
Oh... So then the `ServerID` is pinned to a cert other than the cert web browsers verify against, and it doesn't change when moving a server from one domain to another, even if it's a new domain that your old TLS cert wasn't valid for. ... Interesting.

OK, I'm going to stop, 'cause I think I've taken this issue off-topic long enough.  Sorry.

**Comment by Ylianst** [comment]
Exactly. You got it. No need to be sorry, this was a super interesting question. I will close this issue since I think we have gone in depth on this topic. However, feel free to re-open if needed.
