### ISSUE TITLE
Intel AMT 11 TLS 1.1 wont connect

### ISSUE THREAD

**Issue by thermionic** [Ylianst/MeshCentral#4782]
**Describe your issue**

Writing this more to record it than anything else.

Unable to connect to MeshCentral on Ubuntu 20.04 with AMT 11.8.55.3510 or older, which from https://www.intel.co.uk/content/www/uk/en/support/articles/000038773/technologies/intel-active-management-technology-intel-amt.html looked like it might be the TLS version.

I tested with `openssl s_client -connect MeshCentralHost:4433 -tls1_1` and got no response (testing with tls1_2 got a response).

After finding https://meshcentral-community.com/doku.php?id=howto:installation:manual:ubuntu:2004 which did not work, also found https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level which had the key part of 
`MinProtocol = TLSv1.2`
Which I extrapolated from and changed to 
`MinProtocol = TLSv1.1`

With the change in place `openssl s_client -connect MeshCentralHost:4433 -tls1_1` connects, and the HP Z420 I was testing with has automatically connected.

I do not know yet why, but it also enabled TLS 1.

Instructions for Ubuntu 20.04

Edit /etc/ssl/openssl.cnf

At the top of the file add
`openssl_conf = tls1_1_conf`

At the bottom of the file add
```
[ tls1_1_conf ]
ssl_conf = ssl_sect
[ ssl_sect ]
system_default = system_default_sect
[ system_default_sect ]
MinProtocol = TLSv1.1
CipherString = DEFAULT:@SECLEVEL=1
```

Restart MeshCentral

If I get the time I will edit https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/install/install2.md but the document is huge and IMHO should be split up into several documents at least at the base OS level.

**Comment by silversword411** [comment]
Yeah the first big push on docs was just getting the pdf into markdown which I did.

Still needs hours of cleanup, spell checking, formatting etc.

There's been new pages added...but before you consider splitting stuff..reading the entire doc to get an idea what's there would be a good idea. I've done that, and it's difficult to figure out where/how to cut down the biggest pages into more manageable parts. And if/when you do there is going to re-title leveling, and other stuff.

I've been percolating on it, but haven't found a path yet.

**Comment by thermionic** [comment]
@silversword411 starting from PDF is always "fun"

Agreed, it will need a lot of work to split up, but but the benefits are huge, each doc becomes manageable, which then make it simpler for people to do a PR instead of posting "updates", the Ubuntiu 20.04 can start off as a copy of the 18:04 and then be updated etc.

I've spent the past few weeks looking at it, and then finding something else to do...

As a first "draft" of splitting it up, I'll probably drop it into my internal xwiki (copy and paste with pictures, much simpler than playing with markdown) see how many pages I end up with, and then see how I get on converting to markdown (probably very badly...)

**Comment by gitwittidbit** [comment]
So, do I understand it correctly, that the TLS version is no longer an issue? 
Because I can't connect to my AMT 11 machine (I don't have any AMT 12 that I could try for comparison).
And I thought the TLS version was the problem. I updated MC to 1.27 but still can't connect (timeout).
Is there an error log I could check to find what the problem is? (In the MC server log, I only find an error about "Cannot find module nodemailer" but nothing else...)

**Comment by si458** [comment]
@gitwittidbit share ur config.json but also ur setup,
Is it an amt only group, meshagent with amt, ccm or acm? Etc...
