### ISSUE TITLE
docker image for v 1.0.98 failed to build

### ISSUE THREAD

**Issue by sharifm-informatica** [Ylianst/MeshCentral#4793]
docker image for v 1.0.98 failed to build on this repo on GitHub
https://github.com/Ylianst/MeshCentral/actions/runs/3466800445

Also triggering update from within a running v 1.0.97 server restarts the server without updating, but might be a separate issue.

**Comment by si458** [comment]
Yes we are aware of 1.0.98 release due to a change to include arm64
We need to wait for the next release to fingers crossed work correctly

**Comment by sharifm-informatica** [comment]
Is the fix in already, or is troubleshooting still required? How can I help?

**Comment by Ylianst** [comment]
Working on a release now!

**Comment by Ylianst** [comment]
Ok, v1.0.99 is out. Let me know if it works.

**Comment by si458** [comment]
1.0.99 build worked a treat including arm64, please can u try?

**Comment by sharifm-informatica** [comment]
v1.0.99 builds and runs fine. Container running in Kubernetes wonderfully. Amd64 tested and working.
Thank you so much
