### ISSUE TITLE
Auto download Assistant / bypass Assistant Landing Page for permanent invite link

### ISSUE THREAD

**Issue by joeldeteves** [Ylianst/MeshCentral#4799]
**Is your feature request related to a problem? Please describe.**
We have a button on our ticket portal to allow the user to launch a quick assist session. When we used TeamViewer, we were able to simply have the user click the link and it would auto download the QuickAssist application. With MeshCentral, it requires the user to go to the Mesh Central Assistant page and then click a second download link. We would like to have an option to have this page auto start the download for the Mesh Assistant.

**Describe the solution you'd like**
Please add an option to have the invite link auto download the Assistant when a user lands on the page

**Describe alternatives you've considered**
I tried copying the download link directly and setting the button to that however each time it gets downloaded that download link changes (it seems to be generated on the fly, resulting in an 'unauthorized' the second time it gets used).

**Additional context**
We want this page to auto launch the download:
![image](https://user-images.githubusercontent.com/33190570/203153103-8254a9c7-07f9-416c-b97e-4cc984156b40.png)

**Comment by si458** [comment]
The way I currently do it is you manually download the assistant using the add agent link,
then host the exe on a website somewhere and then link the user to the exe,
Then the user downloads the assiatant exe and run the application

**Comment by joeldeteves** [comment]
Thanks @si458 I didn't know if it was a good idea to re-use the same agent.

Where is the option to choose 'Always connected'? I don't see it anywhere when I go to create the link (latest version of Mesh).

Also, side note: How do I delete the existing invite links I've already created?
