### ISSUE TITLE
Create .MSI installer to mass deploy with Windows Group Policy Software Installation

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#480]
I would love to see Mesh create a MSI that can be deployed via Group policy.

So easy to just put the path to the MSI file and let it auto install.

We have over 1,700 computers we could deploy it to.

**Comment by Ylianst** [comment]
Hi. When you download the MeshAgent for Windows, you can run "meshagent.exe -fullinstall" to install the agent without using the install dialog box. You can also do "meshagent.exe -help" to list the command line options. This should not be difficult to build into a .msi installer. We are not going to do this for you, but it should be easy. Let me know if that helps.

**Comment by geanferrani123** [comment]
Hello guys.

It is possible to perform silent install of agent on windows machines?

**Comment by CCWTech** [comment]
> Hi. When you download the MeshAgent for Windows, you can run "meshagent.exe -fullinstall" to install the agent without using the install dialog box. You can also do "meshagent.exe -help" to list the command line options. This should not be difficult to build into a .msi installer. We are not going to do this for you, but it should be easy. Let me know if that helps.

If we did put it into an MSI would it be a silent intsall to the user?

**Comment by Ylianst** [comment]
Right now you can silent install the agent by copying the agent and running "meshagent.exe -fullinstall" on a computer as administrator. If you do an MSI, there are command line options typically allow silent install by MSI, but you would need to test this. Certainly you would need to run the command as administrator.

**Comment by geanferrani123** [comment]
> No momento, você pode instalar o agente silenciosamente, copiando-o e executando "meshagent.exe -fullinstall" em um computador como administrador. Se você faz um MSI, normalmente há opções de linha de comando que permitem a instalação silenciosa pelo MSI, mas você precisaria testar isso. Certamente você precisaria executar o comando como administrador.
When you talk about copy and execute, are you saying to accomplish this through a batch script?

**Comment by geanferrani123** [comment]
> No momento, você pode instalar o agente silenciosamente, copiando-o e executando "meshagent.exe -fullinstall" em um computador como administrador. Se você faz um MSI, normalmente há opções de linha de comando que permitem a instalação silenciosa pelo MSI, mas você precisaria testar isso. Certamente você precisaria executar o comando como administrador.


When you talk about copy and execute, are you saying to accomplish this through a batch script?

**Comment by MailYouLater** [comment]
What @Ylianst is trying to say is that a silent install already exists if after downloading `meshagent.exe` you run it from an administrative command prompt as `meshagent.exe -fullinstall`, and that you can create your own `.msi` file that will include the `meshagent.exe` file, ask for Administrator privileges, and execute `meshagent.exe -fullinstall`.

If you do decide to create your own `.msi` installer, I would recommend that you try using [WiX](https://wixtoolset.org) to make it.

**Comment by Ylianst** [comment]
Ok, will close this one. If there are more questions, feel free to re-open.
