### ISSUE TITLE
Web Relay Page Not Found Error 404

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#4800]
**Describe your issue**
I enabled the web relay feature, however when I click the http or https links it opens a new tab on the browser but 404 page does not exist.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.
 - Virtualization: [e.g. Docker]
 - Network: WAN, nginx reverse proxy, letsencrypt, ssl offload
 -  MC Version: 1.098
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu, Windows
 - Network: Local to MC, Remote over WAN
 - Browser: Google Chrome, Opera
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu, Windows 10
 - Network: Local to Meshcentral, Remote over WAN
 - Current Core Version (if known): for Ubuntu PC: Aug 29 2022, 2464792450, for Windows PC:Aug 25 2022, 143332014

**Your config.json file**
```
"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user'>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "888888.888888.88",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "DbRecordsEncryptKey": "PasswordisMine",
    "sessionKey": "SecretPassword1",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "AgentPong": 300,
    "TlsOffload": "127.0.0.1",
    "MpsPort": 44330,
    "MpsAliasPort": 4433,
    "MpsTlsOffload": true,
    "AllowFraming": true,
    "ClickOnce": true,
    "DesktopMultiplex": true,
    "RelayPort": 453,
    "RelayAliasPort": 443,
    "Amtmanager": true,
    "_WebRTC": true
  },

  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443",
      "title": "MC",
      "title2": "evoMC",
      "minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "TitlePicture": "title-mycompagny.png"
    }
  },

  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "8888888@gmail.com",
    "names": "888888.8888888.88",
    "rsaKeySize": 3072,
    "production": true
  }
}
```
     
Ngingx config:

```
server {
    if ($host = 888888.88888888.88) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


 listen 80;
 server_name 888888.88888888.88;
 location / {
 proxy_pass http://127.0.0.1:800/;
 proxy_http_version 1.1;

 # Inform MeshCentral about the real host, port and protocol
 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 }

}
 
 server {
 listen 443 ssl;
 server_name 888888.88888888.88;

 # MeshCentral uses long standing web socket connections, set longer timeouts.
 proxy_send_timeout 330s;
 proxy_read_timeout 330s;
    ssl_certificate /etc/letsencrypt/live/888888.8888888.88/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/central.evoiphone.ca/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
 
location / {
 proxy_pass http://127.0.0.1:4430/;
 proxy_http_version 1.1;


 # Allows websockets over HTTPS.
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
 proxy_set_header Host $host;
 # Inform MeshCentral about the real host, port and protocol
 proxy_set_header X-Forwarded-Host $host:$server_port;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-NginX-Proxy true;
 }

}
```

Question: Do I need to add another block for the web relay in the nginx configuration?
Thanks.

**Comment by Ylianst** [comment]
Arg. So, looking to the config.json, I see this:

```
    "Port": 4430,
    "AliasPort": 443,
    "RelayPort": 453,
    "RelayAliasPort": 443,
```

You put the main and relay ports on different port numbers but then alias them both to 443. This is not allowed. The main port and the relay port must be different externally. So for example:

```
    "Port": 4430,
    "AliasPort": 443,
    "RelayPort": 453
```

Then open port 443 and 453 to be visible externally. 

If you can't open another port externally, then @jirijanata has the correct solution by settings up web relay using DNS names.

Let me know if that helps.

**Comment by lexisman** [comment]
> Ylian recommends to use Web relay using DNS names. It's much more flexible from my point of view.
> 
> And yes, you have to reconfigure NGINX (but I don't use NGINX, so I can't help you with that).
> 
> https://www.youtube.com/watch?v=INOvsHXNOKY
> 
> FYI: your domain is still visible under NGINX config.

Thanks.

**Comment by lexisman** [comment]
> Arg. So, looking to the config.json, I see this:
> 
> ```
>     "Port": 4430,
>     "AliasPort": 443,
>     "RelayPort": 453,
>     "RelayAliasPort": 443,
> ```
> 
> You put the main and relay ports on different port numbers but then alias them both to 443. This is not allowed. The main port and the relay port must be different externally. So for example:
> 
> ```
>     "Port": 4430,
>     "AliasPort": 443,
>     "RelayPort": 453
> ```
> 
> Then open port 443 and 453 to be visible externally.
> 
> If you can't open another port externally, then @jirijanata has the correct solution by settings up web relay using DNS names.
> 
> Let me know if that helps.

Thank you for the clarification.
