### ISSUE TITLE
Messaging Button missing

### ISSUE THREAD

**Issue by itelo24** [Ylianst/MeshCentral#4804]
Hello everyone,
I have problems with activating the messaging function.
I have adapted the config.json but no button appears to set it up in the user profile.
What am I doing wrong ? Do I have to adjust other files?
Many Thanks.

**Comment by VINISHVV** [comment]
Please post your config.js by masking/removing the private data/credentials

**Comment by itelo24** [comment]
{
   "settings": {
      "wanonly": true, 
      "_minify": true, 
      "minify": true, 
      "clickonce": true, 
      "webrtc": true, 
	  "redirport": 80, 
      "SET NODE_ENV": "production",
	  "AllowLoginToken": true,
	  "AllowFraming": true,
	  "Compression": true,

	  "plugins": {
	     "enabled": true
	           },
	  "RelayDNS": [
		"relay..de",
	        "relay1..de",
	  	"relay2..de",
	 	"relay3..de",
	  	"relay4..de"
			],
      "cert": ".de"
	 }, 
   "domains": {
      "": {
		"Title": "Fernwartung",
		"TitlePicture": "Seite01.png",
		"_loginPicture": "logo2021-33.png",
		"welcomePicture": "Seite01.png",
		"welcomePictureFullScreen": false,
		"siteStyle": 2,
		"agentCustomization": {
			"displayName": "",
			"companyName": "",
			"image": "server.jpg"
		},
     "mstsc": true,
	 "NewAccounts": true,
	 "Footer": "<a href='https://.com' target='_blank'></a> | <a href='https://.com' target='_blank'></a> | <a href='https://.com' target='_blank'></a>",
	 "ClickOnce": true
	 },
		"messaging": {
		    "callmebot": true
		}
   }, 

	



   "smtp": {
      "host": "xx", 
      "port": 465, 
      "from": "xx", 
      "user": "xx", 
      "pass": "xx", 
      "tls": true
     
   }, 
   "letsencrypt": {
      "email": "xx", 
      "names": "xx", 
      "rsaKeySize": 3072, 
      "production": true
   }

}

**Comment by itelo24** [comment]
Problem Solved
