### ISSUE TITLE
 change remote connection notification message

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#481]
Hello guys, good morning!

I would like to change the remote connection notification message, how do i make this change?

**Comment by Ylianst** [comment]
Hi. Not sure what you want to change in notifications, but in the "My Account" there are two options you can use to enable and change notifications. Let me know if this helps.

![notifications](https://user-images.githubusercontent.com/1319013/64874178-5f137c00-d5ff-11e9-9e07-0fe7268b305c.png)

**Comment by geanferrani123** [comment]
Hello Friend, how are you?

It doens't help me, I need modify the message that appears to the user, look:

![image](https://user-images.githubusercontent.com/55212206/64875157-dc041d00-d622-11e9-866b-55f556a99d0d.png)

I want to change text to another message in my language

**Comment by Ylianst** [comment]
Oh. You can go in "node_modules/meshcentral/agents". Delete "meshcore.min.js" and edit "meshcore.js". Search "Grant access?" and change the message. Then save the file and restart the server.

Let me know if that helps.

**Comment by geanferrani123** [comment]
One minute, i will test

**Comment by geanferrani123** [comment]
Ylianst, it worked

**Comment by Ylianst** [comment]
Nice. note that you will need to make this change again each time you update MeshCentral. If the change improves the existing message for everyone, feel free to propose a change. I will close this issue.

**Comment by hchkim** [comment]
Hi, Ylianst

I would like to change the above phrase to Japanese or Korean. If I change it to English, it works fine. But when I change it to Japanese or Korean, I got a meshcore error, so the Desktop menu is not shown? Is there a way to solve it?
