### ISSUE TITLE
Unable to parse time-stamp response: Error: Too few bytes to parse DER

### ISSUE THREAD

**Issue by Herby12** [Ylianst/MeshCentral#4817]
Hello,

After a fresh install, in the default config.json file, I just added the line `agentTimeStampProxy": "http://a.b-c.d:3128/"` and when I start the server I have the following errors: 
`WARNING: Failed to sign "MeshService.exe": Unable to parse time-stamp response: Error: Too few bytes to parse DER.`
`WARNING: Failed to sign "MeshService64.exe": Unable to parse time-stamp response: Error: Too few bytes to parse DER.`
`WARNING: Failed to sign "MeshCmd64.exe": Unable to parse time-stamp response: Error: Too few bytes to parse DER.`
`WARNING: Failed to sign "MeshCmd.exe": Unable to parse time-stamp response: Error: Too few bytes to parse DER.`

**Server Software:**
 - OS: Debian 11.5
 - Network: LAN/WAN, reverse proxy
 - Version: 1.1.0
 - Node: V19.1.0

Thanks you

**Comment by Ylianst** [comment]
You can turn off time stamping completely with:

```
"agentTimeStampServer": false
```

Otherwise, it does not seem like it's capable of reaching out to the time stamping server. This is not a big deal unless your using a real code signing certificate from a trusted CA, in that case it would be important to get time stamping to work.

**Comment by Herby12** [comment]
I added 
`"agentTimeStampServer": false`

And got now :
`WARNING: Failed to sign "MeshCmd64.exe": Error: connect ETIMEDOUT 91.199.212.79:80`
`WARNING: Failed to sign "MeshCmd.exe": Error: connect ETIMEDOUT 91.199.212.79:80`
`WARNING: Failed to sign "MeshService64.exe": Error: connect ETIMEDOUT 91.199.212.79:80`
`WARNING: Failed to sign "MeshService.exe": Error: connect ETIMEDOUT 91.199.212.79:80`

If I'm not mistaken, i can just safely ignore this ?

**Comment by Ylianst** [comment]
You can safely ignore, but I will check this again since it should not try to connect when set to false.

**Comment by Herby12** [comment]
Ok, Thanks you !

**Comment by Ylianst** [comment]
I just took a look at this again and when adding this line to the "settings" section of the config.json:

```
"agentTimeStampServer": false
```

I can't get MeshCentral to try to make a connection to the timestamp server. If you can provide your entire config.json (but do XXXXX any private info) maybe I can replicate the issue.

**Comment by Herby12** [comment]
That my config.json : 

> {
   "$schema":"http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
   "settings":{
      "MongoDb":"mongodb://127.0.0.1:27017/meshcentral",
      "Cert":"XXX.fr",
      "TlsOffload":"127.0.0.1",
      "_WANonly":true,
      "_LANonly":true,
      "port":4430,
      "aliasPort":443,
      "_redirPort":800,
      "_redirAliasPort":443,
      "authlog":"/opt/meshcentral/meshcentral-data/auth.log",
      "MaxInvalidLogin":{
         "time":3,
         "count":5,
         "coolofftime":60,
         "agentTimeStampProxy":false
      }
   },
   "domains":{
      "":{
         "title":"mesh",
         "_title2":"Servername",
         "_certURL":"https://127.0.0.1:443/",
         "_minify":true,
         "TitlePicture":"bandeau.png",
         "welcomePicture":"logo_Blanc-01.png",
         "_loginPicture":"",
         "_welcometext":"",
         "newAccounts":false,
         "_userNameIsEmail":true,
         "certUrl":"other.server.fr",
         "PasswordRequirements":{
            "min":12,
            "max":128,
            "upper":0,
            "lower":1,
            "numeric":3,
            "nonalpha":3,
            "reset":90,
            "oldPasswordBan":5
         },
         "UserSessionIdleTimeout":20,
         "SessionTime":30,
         "smtp":{
            "host":"XXX",
            "port":25,
            "from":"XXX",
            "tls":false
         }
      }
   }
}
