### ISSUE TITLE
IP devices and reverse proxy

### ISSUE THREAD

**Issue by r4yzs** [Ylianst/MeshCentral#4818]
Hello,

I'm using meshcentral with a reverse proxy.

I use my domain-name to my local IP:443.

My config : 

`
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignor>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mesh.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "agentInviteCodes": true,
      "certUrl": "mesh.domain.com",
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
`

My problem is that all devices have the same IP (my reverse proxy IP).

I use hybrid mode (WAN + LAN), how configure it to have all devices IP ?

Thanks you

**Comment by vithusel** [comment]
I opted to change the Agent connection port to a random one so that i always get the real IP. If you cannot do that it really depends on what you are using as a reverse proxy. I believe there is support for certain types of reverse proxy. 

To make it simpler. To be able to pass source IP from the proxy to the MeshCentral instance you need Proxy Protocol which lets Meshcentral know that there is a proxy in front of it and will process the headers accordingly.

**Comment by r4yzs** [comment]
> I opted to change the Agent connection port to a random one so that i always get the real IP. If you cannot do that it really depends on what you are using as a reverse proxy. I believe there is support for certain types of reverse proxy.
> 
> To make it simpler. To be able to pass source IP from the proxy to the MeshCentral instance you need Proxy Protocol which lets Meshcentral know that there is a proxy in front of it and will process the headers accordingly.

How do you change the agent port to one random ?

**Comment by cgb** [comment]
Hey there, can you try tlsOffload:

https://meshcentral-community.com/doku.php?id=reference:config#tlsoffload
> When true, indicates that a TLS offloader is in front of the MeshCentral server. More typically, set this to the IP address of the reverse proxy or TLS offloader so that IP forwarding headers will be trusted. For example: 127.0.0.1,192.168.1.100

Let us know how it goes...

**Comment by r4yzs** [comment]
> Hey there, can you try tlsOffload:
> 
> https://meshcentral-community.com/doku.php?id=reference:config#tlsoffload
> 
> > When true, indicates that a TLS offloader is in front of the MeshCentral server. More typically, set this to the IP address of the reverse proxy or TLS offloader so that IP forwarding headers will be trusted. For example: 127.0.0.1,192.168.1.100
> 
> Let us know how it goes...

@cgb When I add tlsOffload on my config with "127.0.0.1" or my reverse proxy IP I can't have accès to my web page.

I have add forwarded-for on my reverse proxy.

![image](https://user-images.githubusercontent.com/105233959/204759681-fed6de63-68f0-4dd5-bcf7-874d2a63f93a.png)

My config : `{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with unders>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced exampl>
  "settings": {
    "cert": "mesh.gribiere.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "xxx",
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "_tlsOffload": "127.0.0.1"
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "agentInviteCodes": true,
      "certUrl": "https://mesh.gribiere.com:443/",
      "_userNameIsEmail": true`

My reverse proxy name : mesh.gribiere.com

My config on my NAS : 

![image](https://user-images.githubusercontent.com/105233959/204760308-f2861094-a102-401a-8043-e8130c1f5d89.png)

I think that I have a bad config, can you see ?

Thanks you

**Comment by cgb** [comment]
Hey again,

So I didn't know enough about this, so I had to look things up :) 

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

As I now understand it, tlsOffload does two things:

- Disabled TLS on the mesh server (because a frontend reverse proxy is doing it)
  - From MeshCentral2Userguide.pdf
    ```
    With this configuration, MeshCentral will be using port 4430 instead of port 443,
    but because “TlsOffload” is set, TLS will not be performed on port 4430.
    ```
- Trusts the headers like X-Forwarded-For from the listed IP:
  - From the same PDF:
    ```
    By setting "TlsOffload" to "127.0.0.1", MeshCentral is told to trust these headers
    when requests come from"127.0.0.1".
    ```

It sounds like you reverse proxy is communicating to Mesh using TLS, and with tlsOffload enabled, it breaks.  I found issue #532 which introduces an option ```TrustedProxy``` which can be used instead of tlsOffload to trust the headers while keeping TLS enabled.  Hopefully that is what is going wrong in your testing.

Let me know how you go :)

**Comment by r4yzs** [comment]
> Hey again,
> 
> So I didn't know enough about this, so I had to look things up :)
> 
> https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf
> 
> As I now understand it, tlsOffload does two things:
> 
>     * Disabled TLS on the mesh server (because a frontend reverse proxy is doing it)
>       
>       * From MeshCentral2Userguide.pdf
>         ```
>         With this configuration, MeshCentral will be using port 4430 instead of port 443,
>         but because “TlsOffload” is set, TLS will not be performed on port 4430.
>         ```
> 
>     * Trusts the headers like X-Forwarded-For from the listed IP:
>       
>       * From the same PDF:
>         ```
>         By setting "TlsOffload" to "127.0.0.1", MeshCentral is told to trust these headers
>         when requests come from"127.0.0.1".
>         ```
> 
> 
> It sounds like you reverse proxy is communicating to Mesh using TLS, and with tlsOffload enabled, it breaks. I found issue #532 which introduces an option `TrustedProxy` which can be used instead of tlsOffload to trust the headers while keeping TLS enabled. Hopefully that is what is going wrong in your testing.
> 
> Let me know how you go :)

@cgb 

![image](https://user-images.githubusercontent.com/105233959/204821528-7e2f83d8-adc2-4f3a-be6b-20fd2e05037a.png)

I have access with TrustedProxy but always one IP for all devices.

Do you think that I have a bad config ?

**Comment by cgb** [comment]
> I have access with TrustedProxy but always one IP for all devices.
> 
> Do you think that I have a bad config ?

Just wondering, is 127.0.0.1 the source-IP of traffic from your reverse proxy?  If you run nginx on another host (or container/VM), then it needs to be the IP that host.

You could confirm with a tcpdump on the Mesh server:
```
tcpdump -nni any port 443
```

And see what IP the packets come in with from the reverse proxy.

**Comment by r4yzs** [comment]
Ok, with a personal router all works perfectly.

Thanks
