### ISSUE TITLE
 enable user chat

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#482]
How do I enable remote user chat? Is it possible to also chat small on the same remote access page?

**Comment by Ylianst** [comment]
Hi. The chat icon is in the bottom right of the desktop tab. When you click this icon it will try to open a web page on the remote machine and on the management side to chat.

![chat](https://user-images.githubusercontent.com/1319013/64873770-a9e0c400-d5fe-11e9-9bbd-b38755c2edbb.png)

**Comment by geanferrani123** [comment]
hello Ylianst, how are you?

No friend, my question is related to this particular screen, look please:

![image](https://user-images.githubusercontent.com/55212206/64874751-0c978700-d622-11e9-9f9b-10257f87b003.png)

in my remote host don't none chat screen

**Comment by Ylianst** [comment]
This can happen if the remote computer can't open the browser or the remote computer's browser can't connect to the server. Look at the remote desktop and see what is going on with the remote system.

**Comment by geanferrani123** [comment]
nothing happens

**Comment by Ylianst** [comment]
What is the OS and OS version of the remote machine?

**Comment by geanferrani123** [comment]
The remote computer is running Windows 7 and the machine I'm accessing the system is Windows 10. The Meshcentral server is installed on an Ubuntu server 18.04.

**Comment by geanferrani123** [comment]
For now I'm in the testing and study phase of the tool, but I will need this feature when applying it in production.

**Comment by MailYouLater** [comment]
FYI, this was discussed in another ticket, and a workaround is to copy the URL from the page that opens on your computer, then use the remote desktop feature to open a browser, and paste the URL in their browser, so that you're both on the same page.

**Comment by geanferrani123** [comment]
Hello guys.

Ylianst, can you help me?

**Comment by killmasta93** [comment]
> FYI, this was discussed in another ticket, and a workaround is to copy the URL from the page that opens on your computer, then use the remote desktop feature to open a browser, and paste the URL in their browser, so that you're both on the same page.

yep hes right you can copy the URL of the chat but you have to do it quick if not it closes

**Comment by geanferrani123** [comment]
Right, but must other option, so i need to know the Ylianst. I belive as much as the tool is open source, the goal is to get as close to a tool as possible.

**Comment by Ylianst** [comment]
Bryan is working on a new version of the MeshAgent that may fix things like this. Worked all day on it and it's not really to be published yet, but hopefully when it gets release, it will open the chat window correctly on the remote computer.

**Comment by geanferrani123** [comment]
> Bryan está trabalhando em uma nova versão do MeshAgent que pode corrigir coisas assim. Trabalhou o dia inteiro e ainda não foi publicado, mas espero que, quando for lançado, abra a janela de bate-papo corretamente no computador remoto.

I understand, have any predictions?

**Comment by MailYouLater** [comment]
@killmasta93: I've never had it close on me.  And even if it did, after you copied the URL to paste on the remote computer, you can also paste it again on your own computer to re-open it.

**Comment by killmasta93** [comment]
@MailYouLater i guess then its me very odd on the chat log it shows closed then open then closed but i dont mind much im so happy with this software its really the most amazing thing ever

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-a with all new MeshAgents. When you click on the chat icon, the chat browser window should show up on the remote side. Once updated to the new version, let us know if this is fixed or not. Thanks.

**Comment by geanferrani123** [comment]
Friend, I would like to update just the agent directory or the whole system? Can I upgrade via npm install meshcentral?

**Comment by killmasta93** [comment]
@Ylianst so i updated today, worked great just few things, for internet explorer 9 and below it says connecting trying to find user. I was wondering if maybe instead of internet explorer could always open chrome?

**Comment by Ylianst** [comment]
Yes, you can update using "npm install meshcentral". Just stop the server, do "npm install meshcentral" and start the server again.

For IE9, if there is a problem, please open a new issue. I will take a look at it. MeshCentral should work with IE9.

**Comment by geanferrani123** [comment]
Ylianst, você saberia me dizer se quando eu fizer a atualização se minhas personalizações serão mantidas?

**Comment by geanferrani123** [comment]
Ylianst, could you tell me if when I upgrade if my customizations will be kept?

**Comment by killmasta93** [comment]
@geanferrani123  yes you keep your customization i updated mine all is working well

**Comment by geanferrani123** [comment]
Okay, I'll go back with a result.

**Comment by geanferrani123** [comment]
Friends, my updates have not been kept, but before upgrading I backed up and restored the relevant files, the update apparently solved my problem, thanks a lot

**Comment by Ylianst** [comment]
I few days back, MeshCentral fixed the chat feature. The browser on the remote computer was opening in the system user instead of the currently logged in user. This is fixed and should make the chat feature work fine.

For customization, please open a different issue. I am going to close this issue since I am pretty sure it's fixed now and it's getting a bit out of topic.

**Comment by emersonnpe** [comment]
Dear, my greetings.

Has there been any progress since then? I am currently using version 1.0.0 and I have the following problem:

Opens a browser tab for me and the remote machine, but only displays a message saying it is waiting for the user.

**Comment by MailYouLater** [comment]
@emersonnpe This issue is closed, and also, your problem is different from what was being discussed here.  Please open a [New Issue](new) and include all pertinent details for both (local & remote) computers.  OS (edition, version, build), Browser (version).
