### ISSUE TITLE
MacOS 13: Screen Recording access permission does not work with MacOS Agent

### ISSUE THREAD

**Issue by superbam** [Ylianst/MeshCentral#4824]
MeshCentral 1.1.0, MacOS 13.0.1 on M1 Pro, using MacOS agent (mesh agent_osx64).  Attempting to use desktop results in a prompt to allow Screen Recording even with permissions already granting.  Attempting to grant permissions does not allow desktop to function.  
The universal OSX Mesh agent does not have this issue but currently has an issue with disappearing after a reboot.
![MeshAgent Screen Recording Permissions](https://user-images.githubusercontent.com/37909595/204659570-2d9f5cc0-0b8e-4d23-9f3c-0c58f0a937dc.jpg)
![MeshAgent Screen Recording Prompt](https://user-images.githubusercontent.com/37909595/204659583-a3f2ec2a-a2b3-4575-b753-f7a70f937ccc.jpg)
![MeshAgent Desktop view](https://user-images.githubusercontent.com/37909595/204659588-47bf8d50-cc2a-4280-80ce-93cf34b4e5cd.jpg)

**Comment by bbrendon** [comment]
This feel like a duplicate issue that has a documented  work around.  Did you install using the pkg file? If so, try installing a different way and then try screen recording.
