### ISSUE TITLE
equal user id ldap AD users issue with similar objectSids

### ISSUE THREAD

**Issue by drlight17** [Ylianst/MeshCentral#4825]
**Describe the bug**
When using AD to authenticate users there is a some kind of bug/feature with the generated user id in Meshcentral. Two different ldap users with like similar but not fully equal objectSid become one entity in Meshcentral with the same user id.

**To Reproduce**
Don't actually know, how to reproduce as AD generates objectSid automatically.

**Expected behavior**
There must be two different users with different user ids in Meshcentral.

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Virtualization: LXC container
 - Network: nothing particular
 - Version: 1.1.0
 - Node: v12.22.9

**Additional context**
User1 hex objectSid:
010500000000000515000000c3d62c521aedc0613cad8ce08**7**040000
User2 hex objectSid:
010500000000000515000000c3d62c521aedc0613cad8ce08**b**040000
(differece is one **bold** symbol)
User1 objectSid:
S-1-5-21-1378670275-1640033562-3767315772-1159
User 2 objectSid:
S-1-5-21-1378670275-1640033562-3767315772-1163
User1 and User2 same id in meshcentral:
user//010500000000000515000000fdfd2c521afdfd613cfdfdfdfd040000

**Your config.json file**
Nothing special, ldap part:
```
{
      "auth": "ldap",
      "ldapUserName": "sAMAccountName",
      "ldapUserBinaryKey": "objectSid",
      "ldapUserEmail": "mail",
      "ldapUserRealname": "cn",
      "ldapUserPhoneNumber": "telephoneNumber",
      "ldapUserImage": "jpegPhoto",
      "ldapUserGroups": "memberOf",
      "ldapSyncWithUserGroups": true,
      "_ldapSyncWithUserGroups": { "filter": [ "CN=Enterprise Admins" ] },
      "ldapOptions": {
       "url": "ldaps://***:636",
       "bindDN": "***",
       "bindCredentials": "***",
       "searchBase": "***",
       "searchFilter": "***",
       "groupSearchBase": "***",
}
```

**Comment by drlight17** [comment]
I've done some investigation. It seems like there is some bug in base64 to hex convertion while creating user id base on objectSid. 
Just tested this conversion (base64 to hex) in the first googled online converter and it converts "QUAAAAAAAUVAAAAw9YsUhrtwGE8rYzghwQAAA==" into "010500000000000515000000c3d62c521aedc0613cad8ce087040000", but Meshcentral converts it into "010500000000000515000000fdfd2c521afdfd613cfdfdfdfd040000".
What are these "fd"s in this sequence?
If I change ldapUserBinaryKey value to text based attribute (sAMAccountName for example) Meshcentral produces proper conversion result like "a.karpov" into "792e73616d6f696c6f76" and "user//792e73616d6f696c6f76" as user id.

**Comment by si458** [comment]
in theory setting `"ldapUserBinaryKey": "objectGUID"` should fix this issue
