### ISSUE TITLE
Web Relay - website not on a standard http port 80 or https port 443

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#4827]
I am wondering if the web relay feature would work if the remote website on a remote device is not on a standard port 80 or 443. As an example, let say I have a remote PC/Linux connected to a router, the router can be accessed  not on a standard port 443/80, but on a different customize port, let say port 8081. Is there a way to accessed that router using the web relay, and if there is how can I attached the port 8081? Thank you.

**Comment by si458** [comment]
Yes, just right click the http button and select alternative port

Then set the custom port and click save/ok

Then click the http link again and it will web relay using the specified port rather than 80/443
