### ISSUE TITLE
import machines

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#483]
Friends, good afternoon.

Is there any way to import machines from my active directory?

**Comment by Ylianst** [comment]
Hi. Generally, for a device to show up on MeshCentreal, you need to install the MeshAgent, so you can't just "import" machines. There is one exception to this if you are using an Intel AMT agent-less device group, that we can look at a way of importing machines if you have a list of Intel AMT devices and credentials.

Does this help?

**Comment by geanferrani123** [comment]
Regarding the agent, it helps, but can I do some sort of Active Directory integration to import my machines or access the system with my Active Directory user?

**Comment by Ylianst** [comment]
For MeshCentral active directory integration, take a look at #502. You have to add "auth":"sspi" in the domain section of config.json and must be running MeshCentral on a Windows computer that is joined to the domain.
