### ISSUE TITLE
autoRemoveInactiveDevices not work

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#4831]
**Describe the bug**
The function autoRemoveInactiveDevices in section "domains" not work.

**Expected behavior**
Should delete every device that is offline for more than 31 days:

      "autoRemoveInactiveDevices": {
        "expire": 31
      },

**Server Software (please complete the following information):**
 - OS: Amazon Linux 2
 - Virtualization: N/A
 - Network: WAN
 - Version: 1.1.0
 - Node: 17.1.0

**Comment by si458** [comment]
Duplicate #4847
