### ISSUE TITLE
Install MeshCentral behind Nginx and Acme on Docker

### ISSUE THREAD

**Issue by cl-consulting** [Ylianst/MeshCentral#4832]
**Describe your issue**
Install Meshcentral on a VPS inside an existing Docker system with Nginx and Acme (certificate) already running as a reverse proxy

**Server Software (please complete the following information):**
 - OS: Debian11 on a VPS
 - Virtualization: Docker with existing Nginx and Acme for Letsencrypt certificate

Hello,
I have generated a certificate with nginx-acme for a new sub-domain : mc.xxxxx.com (in fact a wildcart certificate), all is ok at this point.
I tried to use your Docker image with the recommended environnement and after running docker-compose, stop the container and edit the config.json and the nginx.conf but without success.  
I see in the /data volume that some certificate has been generated but we can't access the MeshCentral web interface.
In the User Manual, the explanation are for a normal installation, not for Docker.
I thing that the problem is coming from the first initialisation, config.json is not existing, so it's not possible to modify it and after docker build, we can't modify config.json because the certificates are generated.
So I suppose that we need ajustment in the .env file to obtain the right config after the docker build.
I'm not a big specialist on Docker so may be the problem is easy to solve !
Regards.

**Comment by sharifm-informatica** [comment]
Suggest to start with a config.json already in the data volume with your nginx and cert settings already adjusted to your needs. The startup script will recognize your config.json and not reinitialize a new one. It will use the one you have created manually. Let me know if you have a different need.

**Comment by tecnicosya** [comment]
> Suggest to start with a config.json already in the data volume with your nginx and cert settings already adjusted to your needs. The startup script will recognize your config.json and not reinitialize a new one. It will use the one you have created manually. Let me know if you have a different need.

how can I set the certificate for my subdomain on Meshcentral?
I use Plesk and Lets Encrypt and the certificate is auto update every 90 days. I want to use the certifcates generated by plesk.

**Comment by dinger1986** [comment]
Is this still an issue? Just need to automate it somehow but that's not really for anything to do with mesh @si458 I would close

**Comment by si458** [comment]
i would check new documentation - https://ylianst.github.io/MeshCentral/
closing as stale
