### ISSUE TITLE
MeshCentral - NPM Passport 0.6.0 Break Fix - Mesh reinstalls 0.5.3

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#4833]
Hi Ylian,

To reproduce this issue, simply running the updated npm install -g passport causes infinite loop of reinstallation of Passport 0.5.3 when running server. This breaks some of passport login aspects. 

Expectation: would be for Passport 0.6.x to be acceptable and allow server to run without reinstallation back to 0.5.3.
 - OS: [Ubuntu]
 - Virtualization: [Xen]
 - Network: [Corp/Cloud]
 - Version: [20.04]
 - Node: [18.12.1]

**config.json file**
Redacted for security reasons.

Thanks,
SomeGuru

**Comment by hcaldicott** [comment]
I am also suffering from this issue, making me unable to utilise AzureAD SSO. @Ylianst any chance this is something that can be prioritised to some degree?

**Comment by si458** [comment]
We have a similar issue with archiver and node-windows packages

What version should it be installing?
Do you know if 0.6.0 works?
I'll do a PR :)

**Comment by si458** [comment]
We have a similar issue with archiver and node-windows packages

What version should it be installing?
Do you know if 0.6.0 works?
I'll do a PR :)

**Comment by si458** [comment]
@SomeGuru the is a BUG with 0.6.0 of passport
https://github.com/Ylianst/MeshCentral/blob/b1d2d1aea96c5de48be210e89961347cb6b8b72b/meshcentral.js#L3979
we need to patch the application before doing an upgrade to 0.6.0
what authstrategies are you using? as i dont use any but can experiment

**Comment by hcaldicott** [comment]
Not sure if @SomeGuru is still active based on the age of this bug, however, the authstrategy I'm seeing this in is AzureAD. 

Effectively, MeshCentral works great until I enable the AAD authstrategy. I reboot the instance, NPM kicks off and tries to install passport@0.5.3, and just loops over and over and never actually boots up. I've tried a few manual workarounds like manually installing 0.5.3 from NPM, but nothing really seems to get it going properly.

Cheers

**Comment by si458** [comment]
thanks @hcaldicott i found the patch from funnily enough the same issue @Ylianst posted on the passport repo!
ill do a PR soon!

**Comment by SomeGuru** [comment]
Hi,

Still active, yes Azure AD, had my administrator write a SAML/AAD conversion which allowed for SAML to pass the token properly. i asked for a copy, but due to security reasons he wouldn't share them with me. 

SomeGuru

**Comment by si458** [comment]
Hi @SomeGuru PR done for you!
they seems to of removed the regenerate and save functions in passport for some reason?
so you have to create temp ones, and its seems to work here with github auth no problems
so im guessing azure would work fine too!
