### ISSUE TITLE
Is it meshcentral-backup or meshcentral-backups (possible inconsistency)

### ISSUE THREAD

**Issue by sharifm-informatica** [Ylianst/MeshCentral#4838]
https://github.com/Ylianst/MeshCentral/blob/2d40878408fe132949ff776c44313f792ca8292c/meshcentral.js#L89-L101

Several location in the code and the Dockerfile and docker-compose example refer to `meshcentral-backup` in other locations the default is `meshcentral-backups` is this a possible inconsistency or are they both required and are different?

If both are correct, which one should we use in which situation?
Regards and respect

**Comment by Ylianst** [comment]
Oh yes, you are 100% rights. The correct name is `meshcentral-backups`. I just push in a fix for this, will be in v1.1.1. Thanks for reporting it.

**Comment by stavros-k** [comment]
This can be closed now I guess :)

**Comment by sharifm-informatica** [comment]
Tested in docker and Kubernetes deployments. All ok.  Many thanks.
Closing
