### ISSUE TITLE
Sub-groups in group management + multiple groups share between diff. acc.

### ISSUE THREAD

**Issue by Marcomdv** [Ylianst/MeshCentral#4840]
Hi,
I'm deploying the software for multiple costumers i think that the possibility to create sub-goups under the main group would be great, so people can assign devices also on named offices.
For example   
Group 1 (costumer X)
                      Production
                                    Client x,y,z
                      Office
                                    Client q,r,d

Another feature that i didn't found, but this maybe it's me that i'm missing something, is the chance of copy all the "common groups" between accounts in a faster way than copying one by one.
For example if i have to share my groups with my colleague making remote assistence with me i need to copy one by one all goups and give permissions on every group.
I didn't find a way for  copy multiple groups between account in a single time.

**Comment by silversword411** [comment]
Duplicate https://github.com/Ylianst/MeshCentral/issues/1258

**Comment by si458** [comment]
plz follow #1258
