### ISSUE TITLE
Intel AMT not detected

### ISSUE THREAD

**Issue by KSebion** [Ylianst/MeshCentral#4841]
**Describe your issue**
I've been trying to get a machine activated into ACM using setup.bin. I might be missing something obvious.
I fully unprovisioned AMT on the machine.
I installed setup.bin.
I installed meshagent64.
Running amtconfig in the console results in: Intel AMT not detected.

**meshcmd.exe amtinfo**
```
Intel SM v11.8.92, pre-provisioning state.
Wired Enabled, DHCP, D8:9E:F3:34:A4:5F
Trusted DNS suffix: rootcert.meshcentral.com
Connection Status: Unknown, CIRA: Disconnected.
```
**meshcmd.exe amtconfig --url wss://172.22.1.71 --id Group1**
```
Setting up MEI...
Starting Intel AMT configuration...
Started APF tunnel...
```
**meshcmd.exe amtinfo**
```
Intel SM v11.8.92, pre-provisioning state.
Wired Enabled, DHCP, D8:9E:F3:34:A4:5F
Trusted DNS suffix: rootcert.meshcentral.com
Connection Status: Unknown, CIRA: Disconnected.
```

**Server Software (please complete the following information):**
 - OS: grml64-small_2021.07
 - Virtualization: Windows 10 Hyper-V
 - Network: LAN
 - Version: v1.1.0
 - Node: v12.21.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 22H2
 - Network: Local to Meshcentral
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 22H2
 - Network: Local to Meshcentral
 - Current Core Version (if known): Nov 19 2022, 143332014

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by jsastriawan** [comment]
Your system is Intel Standard Manageability. Looking at the firmware version, it is 6th or 7th generation core.

Intel Standard Manageability does not have CIRA feature. So if it does not connect through CIRA connection is normal.

**Comment by KSebion** [comment]
How do I do the agent soft disconnect?

**Comment by KSebion** [comment]
Nevermind, found it. I'll let you know if there is still no change after 30 minutes.

**Comment by KSebion** [comment]
Seems like provisioning still isn't completed. Even after the agent soft disconnect.

**Comment by dinger1986** [comment]
AMT @si458
