### ISSUE TITLE
Problem of automatic deletion of inactive posts

### ISSUE THREAD

**Issue by Jayddee23** [Ylianst/MeshCentral#4847]
Hello,

I have configured my CH group by checking the box "Automatically delete inactive devices" with a time of 30 days.
Despite everything I still have inactive items that go back to 30/04/2021, how can I explain this?
Would I have a configuration problem in my json file?
I am attaching captures and my configuration.
My server is in 1.1.0

![2022-12-12 11_55_33-CH-Abbeville MeshCentral](https://user-images.githubusercontent.com/101196731/207029522-9e16e4b2-3924-45fc-b091-66be512ff31e.png)

![2022-12-12 11_54_21-CH-Abbeville MeshCentral](https://user-images.githubusercontent.com/101196731/207029555-b4bbcda9-ca7d-4410-8741-b329328b81a0.png)

![image](https://user-images.githubusercontent.com/101196731/207030466-6ea66012-e9ad-46cb-a0fb-8c765157c80c.png)

Thank you,

**Comment by VINISHVV** [comment]
can you try restarting the server / running the below command from the mesh central server console?

removeinactivedevices showremoved

**Comment by Jayddee23** [comment]
I just restarted and updated my windows server, I restarted the mesh server and ran the command I had already tried after seeing it in other posts but it doesn't return anything.
When the command "removeinactivedevices showall", it only returns posts under 30 days as it should be the case.

**Comment by fernandogobah** [comment]
I opened an issue with the same problem #4831

**Comment by fernandogobah** [comment]
The only difference it includes in the config

 "autoRemoveInactiveDevices": {
    "expire": 31
  },

**Comment by si458** [comment]
@fernandogobah the setting `autoRemoveInactiveDevices` should be an integer like `"autoRemoveInactiveDevices":31` and listed under the `domains` section in `config.json`

**Comment by si458** [comment]
@Jayddee23 do you still have this issue?

**Comment by Jayddee23** [comment]
Hello,
I just applied the setting and restarted my Mesh server.
It's much better overall, but about forty workstations out of about 950 are still present.
For example, here I have a duplicate server:
![image](https://github.com/Ylianst/MeshCentral/assets/101196731/1c92321f-6b67-4ad9-84c9-fdd3767223ce)
Do I need to place a special command to force purging?
Thank you

**Comment by si458** [comment]
@Jayddee23 are u still using the same config.json as above OR did u add in the extra option as my above comment for @fernandogobah in ur config.json?
Also is the duplicate devices only in a single group or multiple groups?

**Comment by Jayddee23** [comment]
In several groups.
Here is my JSON file
![image](https://github.com/Ylianst/MeshCentral/assets/101196731/e158219f-0b40-445b-953e-f7166640ccad)
Let me know if there's anything superfluous or incoherent.

**Comment by Jayddee23** [comment]
The setting wasn't in place everywhere, I've just checked it on other groups like the server group.
No change.
Should I restart the server?

**Comment by si458** [comment]
> The setting wasn't in place everywhere, I've just checked it on other groups like the server group.
> No change.
> Should I restart the server?

Try restarting
My idea. If it's set in config.json it should apply on all groups regardless of the group settings
But if u don't have it in config.json then u should set it per group, if that makes sense?

**Comment by Jayddee23** [comment]
With a little patience, the json + checkbox combo on the group works perfectly.
No need to restart.
This time the purge works.
Thanks again for your time.

**Comment by si458** [comment]
great glad we could help!
