### ISSUE TITLE
Default Authentication Method

### ISSUE THREAD

**Issue by koolsb** [Ylianst/MeshCentral#4848]
**Is your feature request related to a problem? Please describe.**
I have MeshCentral setup using OAUTH and users are able to login by clicking the oauth button under the local sign in box. I have no local users and I would like to automatically redirect to the OIDC login in this case (or SAML/google/twitter/etc).

**Describe the solution you'd like**
A config key that allows you to specify the default authentication method for a domain. If this key is specified, the local authentication will be hidden, and when a non authenticated user visits the mesh central login page they are automatically directed to the specified login method without having to click anything.

**Describe alternatives you've considered**
No alternative to my knowledge.

**Additional context**
n/a

**Comment by maxlieb** [comment]
Upvoting this!
I have exactly one local user which I configured when installing meshcentral.
I would like to keep the option to login with it, but by default redirect to the saml login.

**Comment by joeldeteves** [comment]
You can do this using `unknownUserRootRedirect` in your **config.json** file. Simply point it to the callback URL et voila, any users who aren't already logged in will be passed directly to the SSO authentication.

**Comment by koolsb** [comment]
Thanks, worked great!
