### ISSUE TITLE
Open desktop in new window

### ISSUE THREAD

**Issue by IntExCZ** [Ylianst/MeshCentral#485]
Maybe I am wrong but I haven't found the option to open remote desktop in own new window. This is very useful when you are administering more machines at once and you have them separated  to own browser windows.

Thank you :-)

Jan

**Comment by Ylianst** [comment]
You can do it by right clicking on a device in the "My Devices" tab, then hold "shift" and click on "Desktop".

**Comment by IntExCZ** [comment]
Thank you, I have just tried it, but it does not act very well.
I need to login again and if I press the fullscreen button, the desktop will not resize to the whole browser window. (tested in Chrome 76.8.38)

**Comment by Ylianst** [comment]
For the login in again problem, can you update to the latest version of MeshCentral and try again? This is probably due to something I fixed recently. I just checked the full browser on Firefox and Chrome and works for me, so this is odd.

As a side note: If you host "Shift" and hit the full screen button, it will go into full screen mode, not just full browser.

**Comment by IntExCZ** [comment]
I have updated MeshCentral to the latest NPM version (0.4.0-w) and the problem with resizing still presist (same Chrome version as before).
![image](https://user-images.githubusercontent.com/55029847/64985767-eabe2e80-d8c5-11e9-9c52-b987eacba8ee.png)

**Comment by IntExCZ** [comment]
With fullscreen too (shift pressed when cliking on resize icon).
![image](https://user-images.githubusercontent.com/55029847/64986031-818aeb00-d8c6-11e9-981f-0ba42654996d.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-q with a fix for this and improvements to the "shift-click" feature. Let me know if it works for you.

**Comment by openmoto** [comment]
Works great for me!
Server:Ubuntu 18.08
Client: Windows 10

**Comment by Ylianst** [comment]
Thanks. Closing this one as I am pretty sure it's fixed. Please re-open if needed.
