### ISSUE TITLE
Can i change the server URL in the agent?

### ISSUE THREAD

**Issue by zefutoff** [Ylianst/MeshCentral#4850]
Hi, I would like to know if it is possible to change the agent URL? 

Because in my case, I have a public ip that I would like to use (and not the local address of the server)

Thank You!

**Comment by K-O-K** [comment]
Hi,

I'd recommend you use a FQDN instead of IP's.. having that would make this one super easy, just updating the DNS.

You could try [this](https://github.com/Ylianst/MeshCentral/issues/478) and/or [this](https://github.com/Ylianst/MeshCentral/issues/847) with a mix of [this](https://github.com/Ylianst/MeshCentral/issues/4629) for automating the task and accomplish what you need, and maybe change the current IP address to a FQDN. 

KOK

**Comment by silversword411** [comment]
If it was me I'd just create a whole new mesh with custom agent paths and install fresh.

**Comment by K-O-K** [comment]
Maybe you could try to update the agents by executing the `agentupdate` command from console tab.

**Comment by zefutoff** [comment]
> Maybe you could try to update the agents by executing the `agentupdate` command from console tab.

I tried to do "agent update" but it still doesn't work... When I put local in the "server url" field of the MeshAgent.msh file, it works again.

I am attaching a screenshot of the problem I am having when trying to take remote control.

![Capture d’écran 2022-12-14 140343](https://user-images.githubusercontent.com/57273156/207603767-e08c04a4-9f1e-4f17-ab8e-02c6b2c80233.png)

**Comment by K-O-K** [comment]
Please post your config.json file.. remember to clear all sensitive data.

**Comment by zefutoff** [comment]
> Please post your config.json file.. remember to clear all sensitive data.

My configuration :

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80
  },
  "domains": {
    "": {
      "title": "mad",
      "title2": "srv-mad",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by Argayle** [comment]
Hello i try to install mesh yesterday on Debian 11.
I download the agent but it didn't have any server URL.
I can't find any information on you tube videos or web site to explain how to configure that thing.
here ma config.json : 

{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are i>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "srv-Mesh",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "_WebRTC": false,
    "_ClickOnce": false,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
