### ISSUE TITLE
User Forum

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#486]
Found this during the week and really like what I see. This is VERY fast software.

I have few enhancement ideas that I'd like to bounce around, and couple of small bugs that I 'd like to point out.

I can't find a user forum yet for this product, is that something that you'd consider. I can help maintain it if you like.

Enhancement ideas
- giving a user, single computer, remote access only. I'd like the 'desktop' to automatically open in full screen and then connect for this user. (ie I want to give a single user access to a single machine - their own machine, without clicking or opening or connecting, just when they log on, automatically opening their desktop)
- printer access to a local printer when you are connected to a remote machine
- a better notification that there is a remote connection in place, perhaps like the RDP blue connection bar at the top of screen, or the Teamviewer 'hover' notification area than can be minimised or moved
- for new users to be forced to install TFA via GoogleAuthenticator or similar (TFA works fine if you set it up, but I can't see that I can force it)
- blank screen (although I see a few requests for that already)
- switch off remote input for duration of connection
- One of connect ONLY (as opposed to install) as a separate executable. This I could put on my website as a single use 'click and allow me (support) to connect', perhaps even with an ID number as some of the AnywhereConnect apps do
- better text chat with users sited at the remote computer - including logging

Some small bugs that I've noted
- user names can't have a space in them. That's OK, but it needs to be detailed in the create new user panel.
- once a new user is created there is a window about number files or something that I can't read as it is formatted badly

there will be more bits and pieces, I'm still playing with the rdp component and looking at what the router does. Very interesting stuff, some really cool tools here.
Well done

**Comment by Ylianst** [comment]
Hi and thanks. All good suggestions. There is no official forum yet, I have posted at various places including [this place](https://www.mangolassi.it/topic/18607/comparing-meshcentral-2-to-screenconnect/). If you do have a forum on a public server, please let me know. I will try to participate.

A few notes:

- "a better notification that there is a remote connection in place". Just want to confirm that you have looked at the "User Consent" options in the device group. Right now we have a short notification (toast) on connection and we can ask the user for permission. I do agree that we need something better.

- "for new users to be forced to install TFA". Yes, we have that. In the domain settings of config.json, try the "force2factor":
`"PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true }`

- "switch off remote input for duration of connection". We have a "Input" checkbox at the bottom of the "Desktop" tab, but maybe you intended to say the remote computer could stop input?

- "One of connect ONLY (as opposed to install) as a separate executable". When you click "Add Agent" you can select "Interactive Only". In that case, the executable you downloads will only have the "Connect" button and no "Install/Uninstall".

- "better text chat with users sited at the remote computer" - We have a chat, but hopefully the new version of the Agent will make it work better. No logging now, that is a good request.

- "user names can't have a space in them. That's OK, but it needs to be detailed in the create new user panel." - Good request

- "once a new user is created there is a window about number files or something that I can't read as it is formatted badly" - Not sure what this is. If you have a screenshot, please post it.

**Comment by OutbackMatt** [comment]
It's really just about me looking around better...Impressive. Thanks for the tips - already onto it.

I'll post a screen shot of the new user

**Comment by OutbackMatt** [comment]
Screen shot of 'Server permissions'  which is access when going to the 'user' link (far right) of the list of users 

Top line shows as
Server files, <>>>>>>k Max, blank for default

**Comment by OutbackMatt** [comment]
Changing to the password requirements listed in your post stops me from adding new users
I can't send welcome email asking them to log on and change password

I'll investigate...

**Comment by GRIFFCOMMca** [comment]
I just created a Reddit forum called MeshCentral, i have noticed a few of the more "open" projects have forums on there.....

I am the moderator (as i created it), so we can see how that goes if you like...

https://www.reddit.com/r/MeshCentral/new/

**Comment by krayon007** [comment]
Sweet, I just joined...

**Comment by GRIFFCOMMca** [comment]
cool

**Comment by Ylianst** [comment]
I started participating in the [MeshCentral Reddit forum](https://www.reddit.com/r/MeshCentral/). It's really cool that we have a Reddit forum! I will be adding links to is in my documentation and on the web sites this week.
