### ISSUE TITLE
Icon problem in Messenger

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4860]
My Png Icon is Trasparent background, but in the agent, when I send a message, the background is black!!
![Messanger](https://user-images.githubusercontent.com/42680639/208135129-81e512b8-4301-4b6d-a19f-e443c03b2fe4.png)

**Comment by si458** [comment]
You need the latest version 1.1.1 I believe 

The was an issue with transparency

**Comment by bravery-only** [comment]
I am using version 1.1.1. This problem that I mentioned #4829 has been solved, but there is a problem with the icon in Messenger.

**Comment by jobrien2001** [comment]
its not just on messenger, it has to do with the user's avatar. upload any transparent png and you get a black background in a lot of places...  webui, and agent consent. maybe others 

![image](https://user-images.githubusercontent.com/12868319/208213741-6d7ebccd-fdb7-47ac-9aa4-7af29cb089de.png)

**Comment by bravery-only** [comment]
> My Png Icon is Trasparent background, but in the agent, when I send a message, the background is black!! ![Messanger](https://user-images.githubusercontent.com/42680639/208135129-81e512b8-4301-4b6d-a19f-e443c03b2fe4.png)

The icon problem is not in version 1.1.2, it still exists and has not been solved

**Comment by si458** [comment]
this is happening because the image is being uploaded in JPEG even tho you upload say a PNG, so its adding a black background
PR in next release OR change the single line and reupload ur pic to fix it!
