### ISSUE TITLE
Icons on device details page part-covered by left-hand toolbar

### ISSUE THREAD

**Issue by EDIflyer** [Ylianst/MeshCentral#4862]
**Describe the bug**
When on the details page for a device the icons down the left are partially covered by the menu bar (See screenshot)

**To Reproduce**
1. Use MeshCentral in default layout mode
2. Note not an issue if change to menu across the top

**Expected behavior**
Icons to be shifted to the right so they're not covered by the menu bar

**Screenshots**
![image](https://user-images.githubusercontent.com/13610277/208312586-23577094-c8e3-4f65-a33b-68a11288bc43.png)

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Network: WAN
 - Version: 1.1.1
 - Node: 18.12.1

**Client Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10 or Windows 11
 - Network: Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10 22H2
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 143332014

**Additional context**
Nil

**Your config.json file**
Standard (so have left default below, I only changed server name)
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by mbsouth** [comment]
This isn´t a bug! 
This behavior is exactly how it is implemented in source code (HTML).

**Comment by EDIflyer** [comment]
Doesn't the source code need changed then? I don't understand why you'd want the icons partially covered like this?

**Comment by si458** [comment]
![20230104_204908.jpg](https://user-images.githubusercontent.com/765314/210647209-ff31f87e-d587-43ef-bbab-5bb019d63135.jpg)
It's meant to be like that as it's the style

**Comment by EDIflyer** [comment]
I don't understand though, every other page doesn't have anything 'underneath' the menu apart from this one. Given you can't hide the menu (unless you move it to the top) then why is it overlying the icons like this?

![image](https://user-images.githubusercontent.com/13610277/210648769-d785fb98-2749-42ad-919d-720e72cebcb0.png)
![image](https://user-images.githubusercontent.com/13610277/210648771-837626a8-9fe9-472b-a06f-87a9e1a651ad.png)
![image](https://user-images.githubusercontent.com/13610277/210648777-06047f65-18b3-469c-8ac7-bad75111017e.png)
![image](https://user-images.githubusercontent.com/13610277/210648782-91a7b5cc-b8a6-4625-8b95-a5ea8f13101e.png)
![image](https://user-images.githubusercontent.com/13610277/210648785-96164219-8543-4714-b8c5-4c37d1897f55.png)

**Comment by si458** [comment]
I think this is just an OCD thing as it's been like this for years...

If its bugging you submit a PR with the fix and I'm sure @Ylianst will accept it

**Comment by EDIflyer** [comment]
OK at least it's confirmed that others are seeing it too. I'll try and look at the code and work out how to fix later.

**Comment by EDIflyer** [comment]
Thanks @si458 :)

**Comment by si458** [comment]
i meant to close it as wontfix sorry,
the icons have been this way for years and the is no reason to change them,
you can actually customise them yourself,
i will find docs/link and post back on HOW to do it yourself

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/issues/5496#issuecomment-1801943353
https://github.com/Ylianst/MeshCentral/issues/5496#issuecomment-1801961393

**Comment by EDIflyer** [comment]
Ah OK, no problem - as mentioned it just seemed to stick out compared to the other pages but it's not a biggie.  If it annoys me more I'll eventually look at customising (although don't have an issue with the icons themselves, just the alignment) but have a few other things keeping me too busy just now anyway.  Thanks though 🙂

**Comment by si458** [comment]
the icons are actually cut off themselves if you check the PNG, i have no idea why @Ylianst did it this way but he did haha
and if you check the website url in the other issue, there example.zip actually replaces those icons for you so you could see how they look!
