### ISSUE TITLE
Connection to MeshAgent gets stuck on "Setup..." for some windows 10 computers

### ISSUE THREAD

**Issue by tttov** [Ylianst/MeshCentral#4868]
I cant work out a pattern, some Windows 10 agents work 100% and some have an issue where they show up in meshcentral but when I try to connect for desktop, terminal or file its gets stuck saying "setup..." and never connects.
If I restart the agent it wont show up again in meshcentral until I reboot the computer (that the agent is installed on)

This is a new install of meshcentral in WAN mode. 

I am not really sure how to troubleshoot this issue. Any advise is appreciated.
Thank you

**Comment by si458** [comment]
**Plz can u follow the bug report template in the future**

What is your config.json?

**Comment by tttov** [comment]
sure, sorry

Here is the config.json

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "xxx.xxx.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "xxxx",
      "_title2": "xxxxx",
      "_minify": true,
      "_newAccounts": true,
      "userallowedip" : "x.x.x.x,x.x.x.x",
      "_userNameIsEmail": true,
      "agentFileInfo": {
        "icon": "xxxx.ico",
        "filedescription": "xxxxxx",
        "fileversion": "0.1.2.3",
        "internalname": "internalname",
        "legalcopyright": "xxxxx",
        "originalfilename": "sample_originalfilename",
        "productname": "xxxxxxx",
        "productversion": "v0.1.2.3"
      },
      "agentCustomization": {
        "displayName": "xxxxx",
        "description": "xxxxxx® Agent™ agent for remote monitoring, management and assistance.",
        "companyName": "xxxxx",
        "serviceName": "xxxxx",
        "image": "xxxxxx.png",
        "fileName": "xxxxxx",
        "backgroundColor": "#182856",
        "installText": "xxxxxxx."
      }

    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "xx@xxxxxxx.com",
    "names": "xxxxx.xxxx.com",
    "production": true
  }
}

**Comment by PathfinderNetworks** [comment]
Most likely it's an antivirus issue on those endpoints.  What antivirus is running on those devices?  I'm betting it is killing the MeshAgent service/executable.

**Comment by tttov** [comment]
maybe. But the antivirus on these endpoints is just the standard windows 10 defender.

**Comment by silversword411** [comment]
On server enable trace | agent

Restart mesh service on client.

If the service doesn't start you have a local/av problem.

If you don't see it hitting the server you have a networking problem.

Paid support: www.ineedhelpwithtech.com

**Comment by tttov** [comment]
so if I restart the mesh service on the client
I see the following on the server trace.
I am not sure why the web cert hash is bad or how to resolve
![Screenshot 2022-12-22 041119](https://user-images.githubusercontent.com/121102220/209100051-eeaad111-28f0-42c0-b854-b8b422184669.jpg)

**Comment by tttov** [comment]
Then if I restart the computer I see this in the server trace.
![Screenshot 2022-12-22 041644](https://user-images.githubusercontent.com/121102220/209100941-1276f102-5a86-46eb-87fe-ed0d96c03b1e.jpg)
The agent is online in the server after the restart, but when I click on connect in terminal (for example) it just gets stuck saying "setup..."
![Screenshot 2022-12-22 042053](https://user-images.githubusercontent.com/121102220/209101411-c8f4cf13-c5bc-433d-90a4-8e2aeb0d0fc9.jpg)

**Comment by silversword411** [comment]
Bad web cert...something is messing with your certs going between agent and server. Proxies / av?

**Comment by tttov** [comment]
Awesome. That was the exact issue. Thank you so much!

**Comment by tttov** [comment]
It was a web content filter btw

**Comment by rsacramento365** [comment]
> It was a web content filter btw

Hi ttov
could you tell me exactly which web content filter was the problem, because I think I have the same problem

Thank

**Comment by silversword411** [comment]
> web content filter

This was in his network and not part of mesh. If you don't know what's in your network doing filtering that's your first step. 

Please stop duplicate message posting.
