### ISSUE TITLE
Direct url with user and pass parameters skips 2FA token in the login page

### ISSUE THREAD

**Issue by emo44** [Ylianst/MeshCentral#4870]
A user with 2FA Google authenticator activated and a url of the type:
https://mymeshcentral-server/?user=theusername&pass=theuserpass
can be used to bypass 2FA

Isn't this wrong?Shouldn't it give an error and show something like invalid, incorrect or unspecified token?

the url shouldn't be this?

https://mymeshcentral-server/?user=theusername&pass=theuserpass&token=googletoken

In this way, it would be very easy for third-party php applications that want to embed meshcentral in an iframe and use the direct url with the google 2fa token, specifying an extremely short validation time, preventing its subsequent use and generate a new 2fa token next login. This would increase security with this type of access.

Thank's in advance

**Comment by jirijanata** [comment]
Hello, I tried the URL you mentoined, but in my setup nothing happens. The login this way doesn't work for me in my configuration. Which version do you use?

**Comment by emo44** [comment]
> Hello, I tried the URL you mentoined, but in my setup nothing happens. The login this way doesn't work for me in my configuration. Which version do you use?

Hi, this is my info console output:
> info
{
    "meshVersion": "v1.1.0",
    "nodeVersion": "v14.21.2",
    "runMode": "WAN mode",
    "productionMode": false,
    "database": "NeDB",
    "platform": "win32",
    "arch": "x64",
    "pid": 15276,
    "uptime": 253401.4938082,
    "cpuUsage": {
        "user": 223937000,
        "system": 28468000
    },
    "memoryUsage": {
        "rss": 120053760,
        "heapTotal": 63078400,
        "heapUsed": 58862264,
        "external": 31978703,
        "arrayBuffers": 30316264
    },
    "warnings": [],
    "allDevGroupManagers": []
}

**Comment by germanbravouy** [comment]
i tested this today and adding params user and pass bypasses 2fa requirement

**Comment by jirijanata** [comment]
Can you please give us the whole URL? Of course with some dummy URL instead of your normal URL. Are there any specific characters in your password?

I suppose, that you use latest MeshCentral version, right?

With which database? 2FA is TOTP or NTFY or something else?

**Comment by germanbravouy** [comment]
Of course
URL: URL_MESHCENTRAL/?user=administrator&pass=Something
The password has numbers, letter, upper, lowercase, and specials (i think it doesn't matter)

Version: 1.1.6
Database: NeDB
2FA: TOTP and recovery codes

Use case: Im not logged in, so if i go to URL_MESHCENTRAL/login it shows me the login form (user and pass required), if I complete it then it shows me the OTP form, i send the code and I login succesfully. Then i logout and go to:
URL_MESHCENTRAL/?user=myuser&pass=mypass and no login form is shown, i get instantly logged as the user of the "user" param. Of course the pass parameter has to be the correct password.

**Comment by si458** [comment]
@germanbravouy this is because you have already completed the OTP code, so it remembers it so you dont haver to enter it next time round!
have you tried doing the login in the url in private mode/incognito mode?

**Comment by germanbravouy** [comment]
@si458 i didnt mark the remember option for 5 minutes, and i also tested it in incognito mode and it is bypassing 2fa requirement as well.

**Comment by germanbravouy** [comment]
In that case i think it is good to add bug tag and try to fix this as it is a critical impact vulnerability please

**Comment by si458** [comment]
found the issue but not sure how to fix it?
https://github.com/Ylianst/MeshCentral/blob/master/webserver.js#L2813-L2829

**Comment by jirijanata** [comment]
I can also confirm, that it happens - if you encode your Password with w3encoder and special characters get changed to %20 etc. than you can login this way.

https://www.w3schools.com/tags/ref_urlencode.ASP

Two Factor was, I think, introduced at first in the version 1.0.44 (relased on the 1. July 2022). The URL authentication code was introduced in February 2020 and changed in August 2022. 

@Ylianst - this fix should have quite high priority, if possible. Can you check my code if possible? I have not much experience with JS. Thanks!

I also tried to fix it - please try it with your servers, if possible. I tested it and the fix works fine. URL Authentication - no login possible for accounts with 2FA enabled.
https://github.com/Ylianst/MeshCentral/pull/5229

**Comment by germanbravouy** [comment]
Hi @Ylianst any update on this fix please?

Thanks a lot

**Comment by si458** [comment]
Sadly development is on hold
https://github.com/Ylianst/MeshCentral/discussions/4795
So the PR will get approved as and when

**Comment by germanbravouy** [comment]
The issue can be closed, the PR has been merged i think

**Comment by germanbravouy** [comment]
I checked that a new version needs to be released in npm please, as we use the nodejs installation method

**Comment by si458** [comment]
yes i need version needs to be release but again wait for @Ylianst  to do it in his own time
OR
`npm install https://github.com/Ylianst/MeshCentral` if you live on the edge!

**Comment by NiceGuyIT** [comment]
> `npm install https://github.com/Ylianst/MeshCentral` if you live on the edge!

That's similar to [Deno's syntax][] for remote imports. I briefly looked into using Deno to run Mesh but there were too many errors.

[Deno's syntax]: https://deno.land/manual@v1.35.2/basics/modules#faq
