### ISSUE TITLE
Add the possibility of remote input from the clipboard for guest links.

### ISSUE THREAD

**Issue by openncomp** [Ylianst/MeshCentral#4876]
**Is your feature request related to a problem? Please describe.**
There is no possibility to work with the clipboard

**Describe the solution you'd like**
When connected to the desktop of a remote client, it is possible to work with the clipboard.
If I make a guest link (share) to the device, then there is no such possibility.

**Additional context**
Screenshot of the remote Desktop connection window via the Mesh Server interface:
![1](https://user-images.githubusercontent.com/92163803/209342080-7f14575f-8182-4673-b7a0-e40efb3c9cb4.png)

Screenshot of connecting to the desktop via a shared link:
![2](https://user-images.githubusercontent.com/92163803/209342111-14ec0029-8820-4143-b096-4d15e19a057f.png)

**Comment by openncomp** [comment]
Hello everyone.
I understand that now only the community has to develop the project, but still, can someone tell me how difficult it is to implement this functionality?
Perhaps someone can do it?

**Comment by si458** [comment]
sadly this isnt possible because the clipboard feature uses the `control.ashx` websocket which gets created by a user when they login
and only the `meshrelay.ashx` websocket gets created when you use the sharing url because you dont need to login
