### ISSUE TITLE
Question about meshcentral Assistant

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#4878]
Hi
I was wondering if its possible while clicking the on .exe to open the popup request for help instead of hiding in the taskbar?

sometimes we have some users cant find it 

Thank you

**Comment by si458** [comment]
You should be able to use the installation type of 'application, connect on
user request'

This will launch the app, and then a connect button for the user to click
to connect to meshcentral then another button saying 'request help' which
should do the trick

Or to avoid the two button click and only show a request help button use
the 'application, always connected' type
