### ISSUE TITLE
upgrade to 0.4.0w stops all remote computers show up

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#488]
Upgraded to 0.4.0w, upgrade was ok, however every PC i have the Mesh Central running as a service are showing as offline, checking the PC shows the service is running, however the service needs restarting then it shows as online in the portal.

I have many PCs some i cant visit, only remote access.. so need to pray there is a power outage to restart it...

We are using Apache reverse proxy, does this have anything to do with TCP timeout?  i notice some of the PCs that were showing up after the service restart have vanished again.

Any ideas?_

**Comment by Ylianst** [comment]
Hi. This should certainly not happen. A few things to look at:

- In "My Server" tab, go in "Console" sub-tab and type "agentstats". Post these counters.

Also,

- In the "My Server" tab, look for any "Agent Error Counters".
- Again in "My Server" tab, and "Trace" sub-tab, enable "web" and "webrequest" and see if agents are showing up.

Ylian

**Comment by GRIFFCOMMca** [comment]
My Server > Console > agentstats 👍 > agentstats
createMeshAgentCount: 11
agentClose: 7
agentBinaryUpdate: 0
coreIsStableCount: 11
verifiedAgentConnectionCount: 11
clearingCoreCount: 0
updatingCoreCount: 0
recoveryCoreIsStableCount: 0
meshDoesNotExistCount: 0
invalidPkcsSignatureCount: 0
invalidRsaSignatureCount: 0
invalidJsonCount: 0
unknownAgentActionCount: 0
agentBadWebCertHashCount: 0
agentBadSignature1Count: 0
agentBadSignature2Count: 0
agentMaxSessionHoldCount: 0
invalidDomainMeshCount: 0
invalidMeshTypeCount: 0
invalidDomainMesh2Count: 0
invalidMeshType2Count: 0
duplicateAgentCount: 3
maxDomainDevicesReached: 0

**Comment by GRIFFCOMMca** [comment]
Well this is ironic, most all appear to be back online now... !!!

**Comment by GRIFFCOMMca** [comment]
well, they all just started showing up again, so i have no idea why they did this for about 4 hours
![2019-09-17-meshcentralcounters2](https://user-images.githubusercontent.com/54428902/65016090-45b94b00-d8f1-11e9-8374-5c6dccdec064.PNG)
... !!!

**Comment by Ylianst** [comment]
if you upgraded from an older version of MeshCentral, the agent would have no limit on how high the re-connection back off timer could go. Now it's max'ed at 5 minutes. I am going to close this, but if you see this going forward on any future updates, please re-open.

**Comment by GRIFFCOMMca** [comment]
Its doing it again..... before i upgraded to 0.4.1-b, the server real high CPU usage, appears the Apache server had an issue, so restart it, nothing is checking in now (WebGui works).

I assume it will fix itself again, however has to be something doing this.
![2019-09-20 meshcentral stats](https://user-images.githubusercontent.com/54428902/65365513-fd977280-dbe7-11e9-9205-d30ea8493c44.JPG)
