### ISSUE TITLE
Passthrough loginKey and custom admin port when authenticating with SAML

### ISSUE THREAD

**Issue by cnb-mcrum** [Ylianst/MeshCentral#4883]
I have meshcentral working with default ports 80 and 443.  I am using SAML through AzureAD to authenticate the admin users.  

When I try to enable a loginKey and/or a custom web port for the admin interface I am not able to finish logging in using SAML auth.  

The SAML authentication works but I am redirected back to the bare URL of my admin page.  I can edit the resulting URL in the browser address bar to add the loginKey and/or web port and I am able to use meshcentral normally.

I have tried changing the "Reply URL (Assertion Consumer Service URL)" and "Relay State" URLs in AzureAD but that did not make a difference.

During my testing I was able to use both the loginKey and custom web port when using local authentication.

**Comment by si458** [comment]
i have fixed the loginkey issue with external authentication.
you can use the `master` docker image or `npm install Ylianst/MeshCentral` for our develop builds in about 15 mins
