### ISSUE TITLE
Errors found due to localization

### ISSUE THREAD

**Issue by amba404** [Ylianst/MeshCentral#4888]
**Describe the bug**
[In localized view]
When remote client requests help from Assistant, it is impossible to cancel the request from dashboard. Only client can do that.

**To Reproduce**
1. Change default browser language to any of {de|fr|it|es|ru|pl ...}, not of {en|bs|hi|ja} and logon into MC board (or change yout locale settings on MyAccout page, of course :) ).
2. Request for Help from any Assistant.
3. Click on Help icon on requested machine and then click Dismiss (actually what you see in your localization)
4. Window is closed, and request help doesnt cancel.

**Expected behavior**
A cancel help request.

I suppose, it happens because localization made "too much". In localized views (default-*) it was translated command parameter of function closeDeviceHelpRequest. In [en] or [ja] version the right text is 
        function closeDeviceHelpRequest(appid, nodeid) {
            setDialogMode(0);
            meshserver.send({ action: 'msg', type: 'localapp', nodeid: decodeURIComponent(nodeid), appid: decodeURIComponent(appid), value: { cmd: "**cancelhelp**" } });
        }
In many other localized views cmd is not "cancelhelp", but translated analog.

It can be listed "right" and "wrong" default*.handlebars something like that:
root@mc:/opt/meshc/node_modules/meshcentral/views/translations# find default*.* -print | xargs grep -il "cancelhelp" (right)
root@mc:/opt/meshc/node_modules/meshcentral/views/translations# find default*.* -print | xargs grep -iL "cancelhelp" (wrong)

And "wrong" list is much more. 

It is possible that excessive localization affected other server calls via meshserver.send (and maybe other server calls, and may be other views). But I do not know how to check it.

Maybe make some kind of list of correct server calls from the [en] version, and consistently check for the presence of these calls in translated views...  

 
```

**Comment by si458** [comment]
fixed, only 2 years late thank you 👍
