### ISSUE TITLE
Install Meshcentral On Host

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4889]
Can Mesh Central be installed on the host (cpanel-direct admin)?

**Comment by mschubeck-redux** [comment]
Do you mean installing the agent on the server machine?  If so, I did it on a Windows host without issue.

**Comment by bravery-only** [comment]
I have installed it on the Windows server. I want to install it on the shared host that I bought

**Comment by silversword411** [comment]
cpanel isn't going to support node apps

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
cpanel do support nodejs applications, but from the looks of docs, its a nightmare to setup!
https://docs.cpanel.net/knowledge-base/web-services/how-to-install-a-node.js-application/ - HAVE FUN!
closing...
