### ISSUE TITLE
A bug in changing the network

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4890]
When I add an agent in Mesh Central, I change its name, and if there are two network cards in that agent and it connects to another Internet, the same agent is added to Mesh Central again!!!
I tested on several systems and there is a problem in all of them. If there are two network cards, connect with each network card and a new agent will be created!

**Comment by bravery-only** [comment]
![HxeL3rrMni](https://user-images.githubusercontent.com/42680639/210136771-e914a466-fb2f-4a3e-b1c1-56f20ee8867f.png)

**Comment by silversword411** [comment]
Lots of discussion on the topic here
https://github.com/Ylianst/MeshCentral/issues/2013
