### ISSUE TITLE
Agent offline

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4893]
After some time, I saw that an agent has gone offline, agent log:

`
[2022-12-11 02:51:52 PM] [2884DC5FBB29E37D] ..\microstack\ILibParsers.c:10978 (0,0) SelfUpdate -> Current Version: 650667126c2df73961de2f478ec6b0923fb17dcd
[2022-12-11 02:51:52 PM] [2884DC5FBB29E37D] ..\microstack\ILibParsers.c:10978 (0,0) SelfUpdate -> Updating and restarting service...`
I have this problem on several systems and after a while the agent goes offline automatically. If the agent service is in start mode!

**Comment by OutbackMatt** [comment]
Is this on machines that 'Sleep'
I can often 'wake' them using the 'Action' button

**Comment by bravery-only** [comment]
No. The system is turned on, but the agent shows that it is off. I had to go and install a 32-bit agent. This problem often occurs with the 64-bit agent.

**Comment by mschubeck-redux** [comment]
I get this every so often.  I haven't been able to pinpoint exactly when and why, but it does happen on occasion.  The agent shows that it's installed and the service running on the client computer, but just isn't checking in with the server.  Stopping and restarting the service does not make the agent appear online, and only reinstalling the agent seems to work.

**Comment by bravery-only** [comment]
> I get this every so often. I haven't been able to pinpoint exactly when and why, but it does happen on occasion. The agent shows that it's installed and the service running on the client computer, but just isn't checking in with the server. Stopping and restarting the service does not make the agent appear online, and only reinstalling the agent seems to work.
Exactly right. I have the same problem with some systems

**Comment by bravery-only** [comment]
> I get this every so often. I haven't been able to pinpoint exactly when and why, but it does happen on occasion. The agent shows that it's installed and the service running on the client computer, but just isn't checking in with the server. Stopping and restarting the service does not make the agent appear online, and only reinstalling the agent seems to work.

Exactly right. I have the same problem with some systems

**Comment by silversword411** [comment]
> Stopping and restarting the service does not make the agent appear online, and only reinstalling the agent seems to work.

Next time restart the meshcentral server. 

There's some code about duplicate agents, that a fluttering connection I think can trigger. It has been discussed EXTENSIVELY here https://github.com/Ylianst/MeshCentral/issues/2831

**Comment by m0unds** [comment]
I've had this happen with some regularity for the last 6 months or so. I'm not sure what's causing it, and I haven't seen anything obvious in logs or anything.

What I ended up doing was saving a copy of the current (at install) agent in a folder in the disk root when provisioning the agent, so I can provide instruction to attempt a reinstall after trying the low-hanging fruit (service restarts, etc). This doesn't work for all use cases, of course, but it's helped me with machines in super remote areas and spotty connectivity.

**Comment by mbsouth** [comment]
@bravery-only 

> I saw that an agent has gone offline

Do you mean that the agent is really offline i.e. not reachable via console?
Or is the service not started (remote site)? Have you tried to restart the service via console: `service restart`

**Comment by bravery-only** [comment]
> @bravery-only
> 
> > I saw that an agent has gone offline
> 
> Do you mean that the agent is really offline i.e. not reachable via console? Or is the service not started (remote site)? Have you tried to restart the service via console: `service restart`

The agent is really offline.  And the strange thing is that there is an agent start service in the client, but the agent is offline in the server!!!

**Comment by mschubeck-redux** [comment]
@mbsouth I suspect that this is the exact same scenario referred to by @bravery-only 
> Do you mean that the agent is really offline i.e. not reachable via console?

The agent is really offline and not reachable from the server via the console. 

> Or is the service not started (remote site)?

The service is started and running successfully on the remote machine at the remote site (occasionally even at the local site).  

> Have you tried to restart the service via console: `service restart`

The console says "Agent is offline" and won't accept any commands.

**Comment by mschubeck-redux** [comment]
Incidentally, I don't look at this as if it's necessarily a Mesh Agent problem.  I've used in production at least a dozen paid RMM platforms over the past 20 years, and probably 5-10 "free" RMMs as well, and every one of them has occasional issues with agents where they stop reporting in for one reason or another.  The difference between them all is the _frequency_ of the problem, and I don't see Mesh Central as being worse than any of the others.

I've been testing MeshCentral for nearly 10 years now myself, going back to the original version before 2.0, and it's been a wonderful project with lots of promise.  They seemed to jump on the HTML5 console and development before the other players did.  I'm not sure why Intel decided to kill the program because it seems to be the best all-around system for both AMT and agent connection.  It is precisely the reason why ALL of our hardware purchases made in the past 8 years have been with the Intel platform, and with AMT/vPro both installed and enabled.  That's approx. 1000 endpoints total across Dell, HP & Lenovo brands that were influenced directly by @Ylianst and MC.

**Comment by silversword411** [comment]
> It is precisely the reason why ALL of our hardware purchases made in the past 8 years have been with the Intel platform, and with AMT/vPro both installed and enabled. That's approx. 1000 endpoints total across Dell, HP & Lenovo brands that were influenced directly by @Ylianst and MC.

Unfortunately that's not something the bean counters can measure so they don't know what kind of effect it has. :(

**Comment by mschubeck-redux** [comment]
@silversword411 Agreed.  And just because I incorporated that into my required features doesn't mean that most others did also.  But I think Intel shoulders the blame if it wasn't widely accepted... they could have/should have demystified its (AMT's) capabilities many years ago.

**Comment by silversword411** [comment]
> they could have/should have demystified its (AMT's) capabilities many years ago

Yeah, they've definitely been terrible at marketing AMT and "selling" it.

**Comment by bravery-only** [comment]
After all the research, I came to this conclusion:
Some systems that have a 64-bit agent have problems with this version of Windows and they go offline after a while:
Microsoft Windows 10 Enterprise - 18363
In Windows 10 or 11, after installing the new update from Microsoft, the agent went offline!
All agents are 64-bit!

**Comment by bravery-only** [comment]
Some agents who were offline for weeks, the systems were restarted, and the agents came online after weeks!

**Comment by dinger1986** [comment]
Sounds like this is resolved, I seem to remember similar behaviour @si458

**Comment by si458** [comment]
going to close this as it seems fixed but for future use, please use `"noAgentUpdate": 1` under `settings` in `config.json`
this will prevent the agents auto-updating, and you can manually update then all using the group actions or `agentupdate` in the devices Console Tab
