### ISSUE TITLE
ChromeOS/ChromeBooks Support

### ISSUE THREAD

**Issue by blaine07** [Ylianst/MeshCentral#4897]
Pardon my idiocracy:

On every Chromebook I have tried to install agent on says “device isn’t supported” the the play store. 

What exact type of Chromebooks/ChromeOS devices are supported? 

(loving MeshCentral; just lack needing to figure out Chromebook support because sadly we have a lot in field…)

**Comment by si458** [comment]
the is NO support for chromebooks i believe
the only support is to use chrome to control other devices
i do think however if you can unlock the bootloader and get into the terminal with root access,
you might be able to install the agent but ive never tried it

**Comment by si458** [comment]
also the other thing i can think of is IF you ROOT the chromebook,
you could get to the linux shell where you could run the mesh install command
this might work?
