### ISSUE TITLE
All clients offline

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#49]
All win7 clients offline after update server version to 0.2.4-h. Windows 10 clients are online.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.4-l that fixed this. Our new Windows Terminal code that was intended to make the terminal work better caused the agent to lockup on older Windows OS versions. I reversed the change for now.

**Comment by edorbike** [comment]
MeshCentral v0.2.4-I installed, reboot server and client machine but it's still offline.

**Comment by Ylianst** [comment]
So sorry about that. Just published MeshCentral v0.2.4-m with a much better fix for Windows7. Try it again and see if it works. I will also work on a small executable to cause an easy agent reset to un-jam existing agents.

**Comment by edorbike** [comment]
Issue fixed running "meshreset.exe remove" and intalling agent again.
Thanks
