### ISSUE TITLE
Reporting Dubt

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#490]
Hello Guys,

I have a question, i can create custom reports? How do i create?

**Comment by jsastriawan** [comment]
Hi,

Currently there is no modular way to develop reporting tools however you can always customize Meshcentral 2 by overriding the web components and saving it on meshcentral-web. See meshcentral.js line 79-80.

**Comment by Ylianst** [comment]
Can you describe what type of reports would would be looking for? - Thanks.

**Comment by Ylianst** [comment]
I am going to close this issue since the request is too vague. If you have a detailed suggestion, please open a new issue and explain exactly what is needed. Thanks.
