### ISSUE TITLE
injecting custom.css

### ISSUE THREAD

**Issue by DeAlexPesh** [Ylianst/MeshCentral#4903]
hi.
can I change style of this app with custom.css without clone style.css?
```
1. create file /opt/meshcentral/meshcentral-web/public/styles/custom.css
2. inject <link rel="stylesheet" href="styles/custom.css">
```
I tried make this with nginx sub_filter, but on proxy_pass https://.... is not work(
thx

**Comment by DeAlexPesh** [comment]
> If you want to do this client-side, you can use the [Stylus](https://github.com/openstyles/stylus) extension to modify CSS on any webpage.

![image](https://user-images.githubusercontent.com/16735261/211718604-9ea004b9-b07a-49ec-9f7a-1a3356c09c50.png)

**Comment by si458** [comment]
you cant inject files but you can use a workaround
create a folder next to `meshcentral-data` called `meshcentral-web`,
then inside it create another one called `public`,
then inside that create one called `styles`
then inside that folder, copy from `node_modules/meshcentral/public/styles/style.css` to it,
then open it and custom it how you want,
once finished, restart meshcentral and all your styling will be applied!
