### ISSUE TITLE
Update an agent

### ISSUE THREAD

**Issue by jeremiecorso2** [Ylianst/MeshCentral#4905]
Hello, we have a lot of windows domains and to optimize time saving, I am deploying in GPO. I found a script "https://github.com/Ylianst/MeshCentral/issues/1601" for installing the agent if the folder does not exist.

my question is, what are the different variables when running an agent (-fullinstall -resetnodeid -uninstall -update) because I would like to update agents that are connected to an old meshcentral server.

**Comment by jeremiecorso2** [comment]
Mesh Agent available switches:
  run               Start as a console agent.
  connect           Start as a temporary console agent.
  start             Start the service.
  restart           Restart the service.
  stop              Stop the service.
  state             Display the running state of the service.
  -signcheck        Perform self - check.
  -install          Install the service from this location.
  -uninstall        Remove the service from this location.
  -nodeid           Return the current agent identifier.
  -info             Return agent version information.
  -resetnodeid      Reset the NodeID next time the service is started.
  -fulluninstall    Stop agent and clean up the program files location.
  -fullinstall      Copy agent into program files, install and launch.

**Comment by jeremiecorso2** [comment]
Too bad there is no Update command

**Comment by si458** [comment]
> Too bad there is no Update command

Go into the console tab of a device, then type 'help', the is loads of extra commands there

The main one is 'agentupdate' which pulls a copy of the latest exe from your meshcentral then installs it and restarts the agent
