### ISSUE TITLE
Meshcentral to linux not charge to rebrandig meshcentral-web

### ISSUE THREAD

**Issue by soluopen** [Ylianst/MeshCentral#4912]
Hello, how are you? I'm trying to customize the interface of meshcentral in linux with a personal one

but in linux installations you copy or create the folder in the meshcentral installation
in my case in /opt/meshcentral
there I have created a meshcentral-web folder along with the rest within them as shown in the branding video
 and the interface does not load

We have to do something?

**Comment by sistemmsn** [comment]
Hello, how about the development of the interface, it is not from Ylian, it is from a third party that provided its source, I was also trying to apply the confirmation but without any success, I want to assume that it is a specific version, oh, the one who provided the source omitted something

![image](https://user-images.githubusercontent.com/38023703/212148036-656105a3-6af9-4d28-9e57-9034e40cc3a5.png)

**Comment by dinger1986** [comment]
Is this still needed?

**Comment by si458** [comment]
stale so closing
