### ISSUE TITLE
Group - Recommend Cleanup

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#4913]
```Problem:```
Users/G-Admins make shell groups, and then once completed they delete or move the assets to other groups or remove from the server leaving behind a shell, well over time when a user is required to be added to a group, but is added to 36 like named groups it can take quite a while to find the proper group (example: Group Named: Test). 

I'm tired of wading through tons of empty year or longer old groups by the hundreds and not getting to the right group because of all the dead shells in the pursuit.  

```Recommended``` list of group shells that are over a year old with nothing in them for that duration, and or a server side option to clean such and do so automatically based on a server administrator duration of time unused the group would get deleted.

Attempted to remove groups, but it was long time just to remove ```"Test"``` group based on looking into each group for creation dates and last used information.

This could help in the administration and auditing perspective for those that run fairly larger instances of MeshCentral. I would say my operations are rather small in comparison to some others on here, but my server I support has counsel that hands out the group admin level to a lot of owners of projects/products/client farms.

Thanks,
SomeGuru

**Comment by dinger1986** [comment]
Why not just share the computer directly with the users or whoever?

**Comment by SomeGuru** [comment]
Hi Dinger1986,

Not sure I fully understand your comment here, but trying to explain to these project managers that keep making new groups, and then the shells are left to wade through has become a challenge... I am looking for an easier way to sluff off the groups that don't get reused, as the number of systems they are working with make it worth them having group creation access. They onboard so many clients that my head spun when I was supporting making the groups for them... I never slept because of the onboarding process... But now when they ask me to join a group called ```Test``` I get lost looking through each one.

The request here is to have a server side method to ID stale groups (over a year or Server admin defined period of time) and recommend for deletion to clean up the DB and general MeshCentral server software side of things. 

SomeGuru

**Comment by SomeGuru** [comment]
@si458 can you close this as aged not implemented. Won't be needed as I have seen other enhancements that do very similar housekeeping tasks to this. 

Thanks,
-SomeGuru
