### ISSUE TITLE
Can't store SSH credentials

### ISSUE THREAD

**Issue by slax81** [Ylianst/MeshCentral#4917]
**Describe the bug**
When I check to store username, key and/or key password for agentless SSH connection (Web-SSH) and SCP files, it looks like the app os not storing it. It shows on the main device description screen that they are stored (SSH-User+Key+Pass), but when I click to connect again I don't have the option to use the stored key like here:
https://github.com/Ylianst/MeshCentral/issues/3960#issuecomment-1123106727

**To Reproduce**
Check store credentials box before connecting to SSH

**Expected behavior**
Expected the app to store the SSH connection info and key for each next session

**Screenshots**
![screenshot-meshcentral la1-k8s-cluster102 webprovise cloud_4443-2023 01 16-14_32_10](https://user-images.githubusercontent.com/48626129/212690586-b4dd325e-05d2-4672-97fa-8c32325b5bb9.png)

**Server Software (please complete the following information):**
 - Virtualization: kubernetes

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Fedora
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: VM
 - OS: Ubuntu
 - Network: Local to Meshcentral
 - Current Core Version:
 - {
    "meshVersion": "v1.1.2",
    "nodeVersion": "v19.3.0",
    "runMode": "LAN mode",
    "productionMode": false,
    "database": "NeDB",
    "platform": "linux",
    "arch": "x64",
    "pid": 63,
    "uptime": 4823.130106806,
    "cpuUsage": {
        "user": 11565321,
        "system": 1531664
    },
    "memoryUsage": {
        "rss": 122642432,
        "heapTotal": 53952512,
        "heapUsed": 51620416,
        "external": 51337863,
        "arrayBuffers": 33081770
    },
    "warnings": [],
    "allDevGroupManagers": []
}

**Your config.json file**
```
{
  "settings": {},
  "domaindefaults": {
    "userNameIsEmail": true,
    "allowSavingDeviceCredentials": true,
    "title": "XXXXXX",
    "footer": "XXXXXXXXX",
    "newAccounts": true
  },
  "domains": {
    "": {
      "title": "XXXXXXX",
      "title2": "XXXXX",
      "_minify": true,
      "newAccounts": true,
      "userNameIsEmail": true,
      "allowSavingDeviceCredentials": true,
      "mstsc": true,
      "ssh": true
    }
  }
}
```

**Comment by slax81** [comment]
Also when I log out and log in again the label  Credentials: SSH-User+Key+Pass on the main device description screen is gone

**Comment by slax81** [comment]
Please let me know where can I look for a potential fix @Ylianst. Also, I can upload files from the MyFiles section, and that works ok.

![image](https://user-images.githubusercontent.com/48626129/212970963-fe639536-3012-4de0-8367-4a31988c8aed.png)

This is db export.

```
/meshcentral $ node ./node_modules/meshcentral/meshcentral.js --showall
[
  {
    "_id": "DatabaseIdentifier",
    "value": "f95a683cf1705c557b85faa2cb3dbd4217493e95052f983179d299731213196cbd7ec6e42eded37c3c26d86feda894f7"
  },
  {
    "_id": "InvitationLinkEncryptionKey",
    "key": "62d07010271addcfe1032f5c345e9e4511d880c8928ce88caf4de39ed94c71f6c31d3de1a67b61b7675c62ac29de9ef77889432564faeb0e9511bbe08b3db0760d30a4e1b62398ad907f3a25d8a1603c",
    "time": 1673636274166
  },
  {
    "_id": "LastAutoBackupTime",
    "value": 1673900247940
  },
  {
    "_id": "LoginCookieEncryptionKey",
    "key": "964e56d0c31f1a7ccf313b4356aa1b346580c77ad57cc09e1544869a5048a70c97b408feff05be1f18a040e173dfb0da662bfb65454b2ddc7af4d115e5631531651d787c16ac95357ccb16ddd6fa64d3",
    "time": 1673636274164
  },
  {
    "_id": "SchemaVersion",
    "value": 2
  },
  {
    "_id": "dbconfig",
    "version": 1,
    "amtWsEventSecret": "b67789dfb482d34654eeed8ac9b75e125ddb8634bde5594ef19bcb9023b5a0c7"
  },
  {
    "type": "mesh",
    "_id": "mesh//Zqx2lkAt4WuKmFJ7vyuPY0oRfAI2zQH@SGwVodUvyV$CJnqXLNSb8zLLVK8RLdy2",
    "name": "Devhosts",
    "mtype": 3,
    "desc": "Developer remote machines",
    "domain": "",
    "links": {
      "user//sys@se%2Enet": {
        "name": "sys@se.net",
        "rights": 4294967295
      }
    },
    "creation": 1673636548577,
    "creatorid": "user//sys@se.net",
    "creatorname": "sys@se.net"
  },
  {
    "type": "node",
    "_id": "node//xIyAOfhvbUdVuUYafDXTsmCGR5nOHCm4gtJkqoGEHR1eB5EcUkSib5z71ZnC$$E9",
    "meshid": "mesh//Zqx2lkAt4WuKmFJ7vyuPY0oRfAI2zQH@SGwVodUvyV$CJnqXLNSb8zLLVK8RLdy2",
    "mtype": 3,
    "icon": 1,
    "name": "XXXXXXXXXXXXX",
    "host": "10.2.15.12",
    "domain": "",
    "agent": {
      "id": 6,
      "caps": 0
    },
    "tags": [
      "Devhost",
      "Linux",
      "VM"
    ]
  },
  {
    "type": "user",
    "_id": "user//sys@se.net",
    "name": "sys@se.net",
    "email": "sys@se.net",
    "creation": 1673636526,
    "login": 1673944223,
    "access": 1673944223,
    "domain": "",
    "siteadmin": 4294967295,
    "salt": "ahkNmIc/mDu0ndO1nPqEmc7J7Yi0YXKNwsRkBly8cq7ZOwgSTmMZVhoYCgYjtG8ZVuMPSoLb2go8zEFODODtVNSh19ZSd0XrYcTeUwRa3VbCDvo9OmAtQMPMAUzsvVvVTdhTFrW9u7nZTmHVj19SJ8XmiZkizn4HnyfGnmyipAg=",
    "hash": "CfmyZtoDboCeq6H/3lJfuC3uCSxmUwDMam0lD5xxuxYu17wMMUT/PilwaFTiszF+p6iInfXKF1bqpeZGEFglp4DwSnRH+UzTC48z3tpQcxPmKQI1pQeoblnS16qnvxqz1R8p8h5fZ47EngzchneR6Pp3aE0K8U0cmRDEgBPsNkM=",
    "links": {
      "mesh//Zqx2lkAt4WuKmFJ7vyuPY0oRfAI2zQH@SGwVodUvyV%24CJnqXLNSb8zLLVK8RLdy2": {
        "rights": 4294967295
      }
    },
    "pastlogin": 1673871510,
    "notify": {
      "node//xIyAOfhvbUdVuUYafDXTsmCGR5nOHCm4gtJkqoGEHR1eB5EcUkSib5z71ZnC$$E9": 6
    }
  },
  {
    "_id": "wsuser//sys@se.net",
    "state": "{\"deviceView\":\"1\",\"nightMode\":\"0\",\"sort\":\"0\",\"viewsize\":\"1\"}"
  }
]
```

**Comment by wpdevteam** [comment]
I am seeing the same issue. Any advancement on this? It makes Web-SSH unusable.

**Comment by si458** [comment]
im not seeing this issue anymore (1.1.11)
on first connect select 'user+key'
enter username
select ur key
enter password (if you have one set on the key but default is no password)
tick both 'remember user & key' AND 'remember password'
logs in no issues
then logout and log back in, connects with remembered details
