### ISSUE TITLE
Documentation for installing Meshcentral with backup

### ISSUE THREAD

**Issue by quentinDupont** [Ylianst/MeshCentral#4918]
Hello !

After my server died without warning, I had to re-install Meshcentral on a new Ubuntu 20.04 and had to restore datas from my backup.
It went very smoothly - as always with Meshcentral thank youuu <3 - but I could have used a little help to be sure what to do.
To help other people (or me in the future), here are the differents steps.
I don't know where to put them, so I open this issue :) 

- Installing requirements
  - nodejs, npm, mongodb (be careful, it's not fully compatible for Ubuntu 22.04)
  - enable service mongodb
  - setting port permissions sudo setcap cap_net_bind_service=+ep /usr/bin/node
- Installing Meshcentral
  - npm install meshcentral
  - launching it cert with node ./node_modules/meshcentral --cert distance.grap.coop (not sur it's useful)
- Get our backup : meshcentral-data folder, and mongodump-xxxx.archive
- Replace the actual meshcentral-data with your backup (it will handle your LestEncrypt cert also)
- Restore mongodb : mongorestore --archive=mongodump-xxxx.archive
- Set the service sudo nano /etc/systemd/system/meshcentral.service (see doc for example)
- Enable and start meshcentral.service

:tada:

**Comment by si458** [comment]
the docs for meshcentral are here - https://ylianst.github.io/MeshCentral/
the page in question you need is - https://ylianst.github.io/MeshCentral/install/install2/
you can edit that page here - https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/install/install2.md
edit the md, test it, then submit a PR and im sure @Ylianst will accept the docs request,
you can add a section about backups at the bottom of the page maybe?

**Comment by quentinDupont** [comment]
Thanks for all theses links !
Here is my PR : https://github.com/Ylianst/MeshCentral/pull/4936 and so i can close this issue
