### ISSUE TITLE
Execution of update and upgrade

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#492]
Hello Guys, How are you?
I am trying to upgrade within meshcentral but I am having problems, when I complete the upgrade access is only done when I restart the server service. Also my devices are fading and appearing from the main connection screen, could you help me?

**Comment by jsastriawan** [comment]
Agent on each machine may take time to self update and reconnect. You can always debug Meshcentral 2 using --debug flag to see any event such as agent connect or disconnect. In some cases, it takes 1 hour to get agents reconnected again.

**Comment by geanferrani123** [comment]
my biggest problem is to access the server, what I said about the hosts are an additional

**Comment by Ylianst** [comment]
Are you running your server on Windows? What version of NodeJS are you using? Also, if you can describe the steps you do today to perform an update, that would be great. Thanks.

**Comment by geanferrani123** [comment]
i am running on Ubuntu Server, the steps were as follows:

![image](https://user-images.githubusercontent.com/55212206/65178822-fd547700-da2f-11e9-9cae-d082ff062957.png)


See if you can understand it, it's in my native language

**Comment by Ylianst** [comment]
For correct installation on Ubuntu, follow the [MeshCentral Installer's Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf), section 6.

With the information given, it's going to be difficult to try to solve the problem. If the self-update system does not work, you can:

- Stop the MeshCentral service.
- Run "npm install meshcentral"
- Start the MeshCentral server again.

So, you get a manual update. Hope it helps.
