### ISSUE TITLE
MeshCentral with HAproxy on different hosts.

### ISSUE THREAD

**Issue by artem33region** [Ylianst/MeshCentral#4921]
I am install MeshCentral docker in LAN and i already have HAproxy in DMzone, i'm trying to setup haproxy how referents guide "https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf", but it doesn't work.
How i understand, in guide MeshCentral and Haproxy install on same host...

How can i setup my haproxy in my case?

![изображение](https://user-images.githubusercontent.com/34236345/212886088-f0086f3d-12de-4c7a-bc32-4cd8027d03ce.png)

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain.com",
    "MongoDb": "mongodb://db_user:syper_pass@LAN_IP:27017/DataBase",
    "dbRecordsEncryptKey": "syper_key",
    "WANonly": true,
    "LANonly": false,
    "sessionKey": "syper_key",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "redirAliasPort": 0,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false"
  },
  "domains": {
      "": {
        "title": "",
        "title2": "",
        "titlepicture": "title.png",
        "auth": "ldap",
        "ldapUserName": "sAMAccountName",
        "ldapUserKey": "sAMAccountName",
        "ldapOptions": {
          "url": "ldap://IP_server",
          "bindDN": "CN=username,CN=Users,DC=domain,DC=com",
          "bindCredentials": "syper_cred",
          "searchBase": "DC=domain,DC=com",
          "searchFilter": "(sAMAccountName={{username}})"
        },
        "ldapSyncWithUserGroups": true,
        "ldapUserGroups": "memberOf",
        "ldapUserRequiredGroupMembership": [ "" ],
        "_loginkey": "mysecret",
        "agentCustomization": {
          "displayName": "Remote agent",
          "description": "Agent for remote management",
          "companyName": "Company",
          "serviceName": "meshcentral",
          "fileName": "meshcentral",
          "image": "agent-logo.png"
        }
      }
  },
}
```

**Comment by artem33region** [comment]
Who can help me? I want to use meshcentral from LAN without haproxy. Haproxy only for internet agents.

**Comment by si458** [comment]
you have `"WANonly": true` this should be `"WANonly": false` give that a shot

**Comment by thermionic** [comment]
so if meshcentra works for WAN connected hosts, but does not work for LAN, I would guess that LAN DNS is pointing to the DMZ address, or that you are doing TLS offloading on HAProxy, and do not have a valid cert in meshcentral

**Comment by Brodur** [comment]
MeshCentral and HAProxy can be installed on separate hosts. I've had a working installation running for some time. I found the tacticalRMM project to have some useful documentation for this usecase: https://docs.tacticalrmm.com/unsupported_proxies/#haproxy-config

**Comment by dinger1986** [comment]
Is this still an issue?
