### ISSUE TITLE
Ifram and logintoken question

### ISSUE THREAD

**Issue by CnGzBear** [Ylianst/MeshCentral#4922]
Thank you very much for providing such a good source code, I now have a few questions to consult 

1: After I embed iframe, when the business website is in the development environment (localhost), iframe can be displayed. When it is published to the production environment(internet), ifram cannot be displayed, and the data is transferred to the client. However, the style of display of all div is none. 
2: I want to use logintokenkey to generate logintoken by myself. After reading the previous issues, I know that I need to implement encodeCookie method by myself. I use java ,Is there an instance of java?
3: I would like to ask, the logintoken generated by oneself has a time-limitation problem, is it one-time?  regenerated by the service website every time?
4: Is there any detailed description of the object of  encodeCookie parameter. There's u,a,e,ruserid,nodeidand so on . In what scenarios, what values should be given.

Thanks for your reply.

**Comment by YiuTerran** [comment]
```java
    public String genIframeLink(String nodeId, int tab) {
        String token = encode(conf.getLoginKey(), "admin", 3);
        //ignore prefix `node//`
        nodeId = nodeId.substring(6);
        UriComponentsBuilder builder = UriComponentsBuilder.newInstance();
        return builder.scheme("https").host(conf.getHost()).queryParam("login", token)
                .queryParam("viewmode", tab)
                .queryParam("hide", HIDE)
                .queryParam("node", nodeId)
                .build().encode().toUriString();
    }

    @SneakyThrows
    private String encode(String key, String user, int action) {
        byte[] keyBytes = hexStringToByteArray(key);
        byte[] key1 = new byte[48];
        System.arraycopy(keyBytes, 0, key1, 0, 48);
        byte[] key2 = new byte[32];
        System.arraycopy(keyBytes, 48, key2, 0, 32);
        String msg = String.format("{\"a\":%d, \"u\":\"%s\",\"time\":%d}", action, user,
                Instant.now().getEpochSecond());
        SecureRandom random = new SecureRandom();
        byte[] iv = new byte[16];
        random.nextBytes(iv);

        //sha
        SHA3Digest sha3Digest = new SHA3Digest(384);
        sha3Digest.update(key1, 0, key1.length);
        byte[] digest = new byte[sha3Digest.getDigestSize()];
        sha3Digest.doFinal(digest, 0);
        byte[] msgBytes = append(digest, msg.getBytes(StandardCharsets.UTF_8));

        //aes
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        SecretKeySpec secretKeySpec = new SecretKeySpec(key2, "AES");
        IvParameterSpec ivParameterSpec = new IvParameterSpec(iv);
        cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, ivParameterSpec);
        int n = 16 - (msgBytes.length % 16);
        byte pad = (byte) n;
        byte[] paddedMsgBytes = append(msgBytes, new byte[]{pad});
        byte[] encryptedBytes = cipher.doFinal(paddedMsgBytes);

        byte[] output = append(iv, encryptedBytes);
        return Base64.getEncoder().encodeToString(output)
                .replace("+", "@")
                .replace("/", "$");
    }

    private byte[] hexStringToByteArray(String hexString) {
        int length = hexString.length();
        byte[] bytes = new byte[length / 2];
        for (int i = 0; i < length; i += 2) {
            bytes[i / 2] = (byte) ((Character.digit(hexString.charAt(i), 16) << 4)
                    + Character.digit(hexString.charAt(i + 1), 16));
        }
        return bytes;
    }

    private byte[] append(byte[] a, byte[] b) {
        byte[] result = new byte[a.length + b.length];
        System.arraycopy(a, 0, result, 0, a.length);
        System.arraycopy(b, 0, result, a.length, b.length);
        return result;
    }
```

**Comment by CnGzBear** [comment]
thanks very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 上午9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ylianst/MeshCentral] Ifram and logintoken question (Issue #4922)





     public String genIframeLink(String nodeId, int tab) {         String token = encode(conf.getLoginKey(), "admin", 3);         //ignore prefix `node//`         nodeId = nodeId.substring(6);         UriComponentsBuilder builder = UriComponentsBuilder.newInstance();         return builder.scheme("https").host(conf.getHost()).queryParam("login", token)                 .queryParam("viewmode", tab)                 .queryParam("hide", HIDE)                 .queryParam("node", nodeId)                 .build().encode().toUriString();     }     @SneakyThrows     private String encode(String key, String user, int action) {         byte[] keyBytes = hexStringToByteArray(key);         byte[] key1 = new byte[48];         System.arraycopy(keyBytes, 0, key1, 0, 48);         byte[] key2 = new byte[32];         System.arraycopy(keyBytes, 48, key2, 0, 32);         String msg = String.format("{\"a\":%d, \"u\":\"%s\",\"time\":%d}", action, user,                 Instant.now().getEpochSecond());         SecureRandom random = new SecureRandom();         byte[] iv = new byte[16];         random.nextBytes(iv);         //sha         SHA3Digest sha3Digest = new SHA3Digest(384);         sha3Digest.update(key1, 0, key1.length);         byte[] digest = new byte[sha3Digest.getDigestSize()];         sha3Digest.doFinal(digest, 0);         byte[] msgBytes = append(digest, msg.getBytes(StandardCharsets.UTF_8));         //aes         Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");         SecretKeySpec secretKeySpec = new SecretKeySpec(key2, "AES");         IvParameterSpec ivParameterSpec = new IvParameterSpec(iv);         cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, ivParameterSpec);         int n = 16 - (msgBytes.length % 16);         byte pad = (byte) n;         byte[] paddedMsgBytes = append(msgBytes, new byte[]{pad});         byte[] encryptedBytes = cipher.doFinal(paddedMsgBytes);         byte[] output = append(iv, encryptedBytes);         return Base64.getEncoder().encodeToString(output)                 .replace("+", "@")                 .replace("/", "$");     }     private byte[] hexStringToByteArray(String hexString) {         int length = hexString.length();         byte[] bytes = new byte[length / 2];         for (int i = 0; i < length; i += 2) {             bytes[i / 2] = (byte) ((Character.digit(hexString.charAt(i), 16) << 4)                     + Character.digit(hexString.charAt(i + 1), 16));         }         return bytes;     }     private byte[] append(byte[] a, byte[] b) {         byte[] result = new byte[a.length + b.length];         System.arraycopy(a, 0, result, 0, a.length);         System.arraycopy(b, 0, result, a.length, b.length);         return result;     }

**Comment by YiuTerran** [comment]
Hello, I just update my code above. After test a lot, now it works.

**Comment by dinger1986** [comment]
@si458 can close
