### ISSUE TITLE
MeshCentral behind Proxy

### ISSUE THREAD

**Issue by adispy** [Ylianst/MeshCentral#4929]
Hi,
I have installed MeshCentral on one of my Windows Servers with the WAN option, configured the proper rules on my UTM9 proxy (with websocket enabled) then log in.
Until now everything works but once I install an agent on a computer, that agent does not report, nothing pops-up in the console.

Do I need to change some configuration files?

Thanks,

**Comment by si458** [comment]
please can you share your `config.json` (hide secret stuff obvs)

**Comment by adispy** [comment]
Here you go

`{
  "settings": {
    "cert": "MY PUBLIC FQDN",
    "wanonly": true,
    "_minify": true
  }
}
`

**Comment by si458** [comment]
> Here you go. I did not changed anything from the default.
> 
> { "settings": { "cert": "MY PUBLIC FQDN", "wanonly": true, "_minify": true } }

that seems very short? the sample one shows different
https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json

**Comment by adispy** [comment]
This is all I have, fresh install.
Should I replace it with the one in the example?

**Comment by adispy** [comment]
By putting the sample config in my own and off course modify it based on my FQDN, the MeshCentral server does not work anymore.

**Comment by dinger1986** [comment]
Is this still an issue?

**Comment by adispy** [comment]
No. I have installed MeshCentral server on Docker and everything works out great.

Thanks,
