### ISSUE TITLE
Acesso remoto em outras subredes

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#493]
Guys, good morning!

How do I configure meshcentral to access other subnets? I have a segmented network (local A with one range, local B with another ip range), is this possible?

**Comment by jsastriawan** [comment]
First of all, you need to put Meshcentral 2 on subnet accessible from subnet A and subnet B (this should work for WAN mode). Second, if you want to do LAN only deployment, you need to put all those subnet to be transparently accessible to each other/no NAT.

**Comment by geanferrani123** [comment]
88/5000
Both as lans communicate, and an installation was done in lan, how can I solve?

**Comment by jsastriawan** [comment]
Please read through: http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

Especially chapter 7 on server configuration file. The reliable way is to set "cert" to the FQDN of your Meshcentral 2 server and make sure the other machines can resolve this FQDN to IP and the other machines can connect to this IP.

For different method of installation, please also see: http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf

**Comment by geanferrani123** [comment]
> Leia: http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf
> 
> Especialmente o capítulo 7 do arquivo de configuração do servidor. A maneira confiável é definir "cert" no FQDN do servidor Meshcentral 2 e garantir que as outras máquinas possam resolver esse FQDN para IP e as outras máquinas possam se conectar a esse IP.
> 
> Para diferentes métodos de instalação, consulte também: http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide.pdf

I do not understand, can I better explain how to perform a configuration?

**Comment by geanferrani123** [comment]
I was able to enable hybrid mode, started like this:

![image](https://user-images.githubusercontent.com/55212206/65161751-7cd14e80-da0e-11e9-94f1-735ec20ed6fc.png)

**Comment by geanferrani123** [comment]
I managed to switch to hybrid mode lucky via linux and it didn't work, I did a test on a windows machine and it worked, how do i configure linux hybrid so this functionality works?

**Comment by geanferrani123** [comment]
Friends, as I mentioned above, I was able to switch to hybrid mode but still can't access the way in question, what is left to do?

![image](https://user-images.githubusercontent.com/55212206/65185171-5d9de580-da3d-11e9-8bbe-8c4770e69df9.png)

**Comment by Ylianst** [comment]
Hi. So, you are running MeshCentral on port 81 and 444. This is a little odd. It could be ok, but if you want to do that, set the ports explicitly in the config.json:

```
{
  "settings": {
    "Port": 444,
    "RedirPort": 81
  }
}
```

Then restart the server and re-install the MeshAgent. When you install the MeshAgent, open the "meshagent.msh" with a text editor.

```
MeshName=MyGroup
MeshType=2
MeshID=0xXXXXXXXXX
ServerID=XXXXXXXXXX
MeshServer=wss://teste.net.sefaz.es.gov:444/agent.ashx
```

Make sure the "MeshServer" line is not set to "local", but instead points to the correct URL for your server and make sure the port is correct. Hope it helps.

**Comment by Ylianst** [comment]
Closing this one since no added comments. Please re-open if needed.
