### ISSUE TITLE
Problem with the port in Mesh Central

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4931]
I did not install anything other than Mesh Central on my server. But although Mesh Central is running on port 443, it shows port 444 in cmd.
Photos of the config
![aqGbc7xCEw](https://user-images.githubusercontent.com/42680639/213889969-0ec895cd-a247-40fa-ac5d-5f6149587db0.png)
![mstsc_43f7d8JYDi](https://user-images.githubusercontent.com/42680639/213889971-cc5a25f0-adc6-497d-ad12-0fea7e8f3168.png)
 file and CMD

**Comment by si458** [comment]
It believes the port is already in use so it moves up one port number and uses that if its available

Also Intel amt is saying the same thing, it's port isn't available as it's in use

Use tcpview from sysinternals and see what's using port 443

**Comment by bravery-only** [comment]
tcpview 
![mstsc_Ik3c1cGVZs](https://user-images.githubusercontent.com/42680639/213903539-33544a96-ba3b-4ad6-98f0-5c5795f229eb.png)

**Comment by si458** [comment]
> tcpview 
> ![mstsc_Ik3c1cGVZs](https://user-images.githubusercontent.com/42680639/213903539-33544a96-ba3b-4ad6-98f0-5c5795f229eb.png)
> 

So it says node.exe is running and using the port
So make sure meshcentral isn't running as a service,
Restart server,
Check if its still running node.exe,
If so then you should be able to double click the line and it should show u the process command and what it is, then maybe kill it from task manager

**Comment by bravery-only** [comment]
My Mesh Central is working and the only problem is that when I run Mesh Central with CMD, it goes to port 444. Now the agents are also working and there are no problems.
If I stop the Mesh Central service, the agents will be disconnected
I restarted the Mesh Central service, the problem was solved, but if I run it with CMD, Mesh Central goes to port 444, but the site runs with 443!

**Comment by si458** [comment]
That's because u are running 2 instances!
You must run either the meshcentral service OR meshcentral via cmd line
You can't run both at the same time

**Comment by bravery-only** [comment]
So, should I stop the Mesh Central service from the service? and run it with CMD
Which method is stable?
Central mesh service or running with CMD?

**Comment by si458** [comment]
> So, should I stop the Mesh Central service from the service? and run it with CMD
> Which method is stable?
> Central mesh service or running with CMD?

Well the service starts in the background when you start your server up
Where as
Cmd must be run manually everytime u start your server up

Service is best but no logs in a black window for example

**Comment by bravery-only** [comment]
Thank you my friend
