### ISSUE TITLE
config.json file ignored - new installation - help

### ISSUE THREAD

**Issue by compumatter** [Ylianst/MeshCentral#4937]
**Describe the bug**
I cannot change ports.  I cannot use LDAP.  Only functionality appears to be the default configuration supplied during installation.

**To Reproduce**
Install (not as sudo) npm install meshcentral
Modify the config.json file to change the port to any other port than the 81 / 444 default.

**Expected behavior**
When I start meshcentral using node meshcentral --debug web,webrequests I would expect to see that the port has been modified.

However, it continues to say 
```
MeshCentral HTTP redirection server running on port 81.
MeshCentral v1.1.2, LAN mode.
MeshCentral HTTPS server running on port 444.
```
**Screenshots**
I have tried editing config.json normally and just changing the ports to 3000/3443 but it still defaulted to 81/444

In this screen shot I have purposely modified the config.json file to be completely false and set specific log files to capture errors.
However it continues to start normally on default ports and generating no errors.
![image](https://user-images.githubusercontent.com/121611/214746913-5f5cde54-ce1e-4587-b324-b4d596209676.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: Bare Metal
 - Network: Reverse Proxy through NGINX but also same issue via browser IP
 - Version:  fresh installed 2023.01.25 (cannot figure out how to get version of Meshcentral)
 - Node: 14.21.2

**Client Device (please complete the following information):**
 - Device: Lenovo ThinkStation 
 - OS: Windows 10 64 Pro
 - Network: Local to Meshcentral over LAN
 - Browser: Chrome / Firefox both
 - MeshCentralRouter Version: NA

**Additional context**
I have created a video in case it can be of value 
* https://www.youtube.com/watch?v=qBukV7QuK9Q

**Your config.json file**
This is my starting config.json file.  Though I have tried modifying the ports to different numbers, they were always ignored.
```
{
    "settings": {
      "Cert": "smvirtual.biz",
      "Port": 444,
      "AliasPort": 443,
      "RedirPort": 81,
      "AgentPong": 300,
      "TlsOffload": "127.0.0.1"
    },
    "domains": {
      "": {
            "certUrl": "https://desktops.smvirtual.biz:443/"
      }
    }
  }
  
```
I have also tried using your example config.json file with minor adjustments and the same end result of it being ignored
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "smvirtual.biz",
    "WANonly": true,
    "LANonly": true,
    "port": 446,
    "aliasPort": 443,
    "redirPort": 88,
    "redirAliasPort": 80
  },
  "domains": {
    "": {
      "certUrl": "https://desktops.smvirtual.biz:443",
      "title": "MyServer",
      "title2": "Servername",
      "minify": true,
      "newAccounts": true,
      "userNameIsEmail": true
    }
  }
}
```

**Comment by honestlai** [comment]
I've stood up mesh a half dozen times or more without issue... but always using docker with nginx proxy manager. It's a much easier and faster way to do. From watching your video, you look comfortable in linux, I'd recommend going the docker route.

**Comment by si458** [comment]
You have put the `config.json` in the wrong location

It shouldn't be inside the `node_modules`

It should be inside `meshcentral-data`

https://ylianst.github.io/MeshCentral/install/install2/

**Comment by compumatter** [comment]
Thank you @si458  that is indeed the correct answer.

I saw the sample.config.json file in the node_modules/meshcentral/ directory and that led me astray.   It seems there should be clear warnings about that within a readme somewhere but that said, you solved that issue.
