### ISSUE TITLE
Mesh Agent is not signed when downloading it from a browser

### ISSUE THREAD

**Issue by aleksgtn** [Ylianst/MeshCentral#4938]
**Describe the bug**
I can't figure out if this is a bug or something I've missed...
The freshly installed server (with it's own self-signed certificates) automatically signs agents in the `~/meshcentral-data/signedagents` folder (_MeshCmd.exe_ & _MeshService.exe_, x86 and x64, without '_-signed_' suffix however), but when downloading an agent via the web interface (_Group → Add Agent → Download 32/64bit version of agent_), the executable (_meshagentXX-Group.exe_) isn't signed. 
Downloaded _meshcmd.exe_ is OK, signed.

**To Reproduce**
1. Install prerequisites and MeshCentral Server in a Proxmox container (using 'Ubuntu 18.04 Installation' guide).
2. First MeshCentral launch and Ctrl+C to stop the server.
3. Changing config.json file according to needs.
4. Restart the MeshCentral, make sure that executables in _~/meshcentral-data/signedagents_ catalog are signed.
5. Trying to download agents via web-interface.

**Expected behavior**
When downloading an agent via the web interface (_Group → Add Agent → Download 32/64bit version of agent_), the downloaded executable (_meshagentXX-Group.exe_) is signed.

**Server Software:**
 - OS: Debian 11
 - Virtualization: LXC-container in Proxmox VE 6.3-4
 - Network: LAN (no reverse proxies, or smth. else)
 - Version: 1.1.2
 - Node: 12.22.12

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 Professional x64 (version 22H2)
 - Network: LAN
 - Browser: Microsoft Edge

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guid>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "mesh.somedomain.loc",
    "rootCertCommonName": "mesh.somedomain.loc",
    "WANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "mpsPort": 0,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "_agentSignLock": true,
    "amtManager": false,
    "amtScanner": false,
    "meshScanner": false,
    "WebRTC": true
  },
  "domains": {
    "": {
      "title": "MeshCentral Remote Access",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": false,
      "auth": "ldap",
      "ldapUserName": "displayName",
      "ldapUserBinaryKey": "sAMAccountName",
      "ldapUserEmail": "mail",
      "ldapUserImage": "thumbnailPhoto",
      "ldapUserGroups": "memberOf",
      "ldapUserRequiredGroupMembership": [ "LDAP groups information here" ],
      "ldapSiteAdminGroups": [ "LDAP groups information here" ],
      "ldapSyncWithUserGroups": {
        "filter": [ "LDAP groups information here" ]
        },
      "ldapOptions": {
        "url": "ldap://192.168.xxx.xxx:389",
        "bindDN": "LDAP bind account here",
        "bindCredentials": "Password here",
        "searchBase": "Search base here",
        "searchFilter": "(sAMAccountName={{username}})"
      }
    }
  },
...        
```

**Comment by PathfinderNetworks** [comment]
When I get a chance I'll take a closer look at your config.json to see what, if anything, needs to be changed.
But, for now, here is a YouTube video Ylian produced discussing this option.  Wasn't sure if you had viewed the video yet?       
https://www.youtube.com/watch?v=qMAestNgCwc

**Comment by aleksgtn** [comment]
> When I get a chance I'll take a closer look at your config.json to see what, if anything, needs to be changed. But, for now, here is a YouTube video Ylian produced discussing this option. Wasn't sure if you had viewed the video yet? https://www.youtube.com/watch?v=qMAestNgCwc

@PathfinderNetworks thank you for the link provided. I watched this video earlier, several times, and the basic functionality doesn't work properly in my case:
MeshCentral server generates self-signed certs (ok) → Agents are automatically signed by self-generated code-signing cert in _/meshcentral-data/signedagents_ folder (ok) → Agent is not signed when downloading it from a web-console.

Looks like MeshService-executables from _/node_modules/meshcentral/agents_ catalog are used instead of _/meshcentral-data/signedagents_ ones for some reason.

**Comment by PathfinderNetworks** [comment]
I think, if I remember correctly, you probably just need to delete (or maybe just rename for now) the /agents folder.  Also, can you confirm the path to each of the folders you mention? You shouldn't have an agents folder under /meshcentral.  It should only be under /meshcentral/meshcentral-data
For example, under my /meshcentral folder I only have these folders listed.  I am running under Windows Server 2022 though (not Linux):
meshcentral-data
meshcentral-files
node_modules
WinService

I believe, if the 'agents' folder exists MeshCentral will use that before the 'signedagents' folder.

**Comment by aleksgtn** [comment]
> I think, if I remember correctly, you probably just need to delete (or maybe just rename for now) the /agents folder. Also, can you confirm the path to each of the folders you mention? You shouldn't have an agents folder under /meshcentral. It should only be under /meshcentral/meshcentral-data For example, under my /meshcentral folder I only have these folders listed. I am running under Windows Server 2022 though (not Linux): meshcentral-data meshcentral-files node_modules WinService

Content of my MeshCentral instance catalog:
/meshcentral-backups
/meshcentral-data
/meshcentral-files
/node_modules

> I believe, if the 'agents' folder exists MeshCentral will use that before the 'signedagents' folder. Edit: Also forgot to mention- if you make a change such as renaming that Agents folder, you will want to stop and restart MeshCentral.

By default, /agents folder is not present in /meshcentral-data catalog and I didn't create it manually.

**Comment by dinger1986** [comment]
@si458 is code signing still on by default? I didn't think it was

**Comment by PZan** [comment]
Was this actually ever solver, @aleksgtn? I'm running a similar setup as yours and I'm seeing pretty much the same behavior as you have described.

**Comment by si458** [comment]
@PZan can you share what problem ur having and also what your config.json looks like, we might be able to help :)

**Comment by PZan** [comment]
Absolutely, I just figured I'd try hitting up OP. Do you want me to start a new thread, considering this ones been closed for over a year :)?

**Comment by si458** [comment]
@PZan plz! dont forget to follow the 🐛 report template!
