### ISSUE TITLE
My Wildcard SSL Cert is not being used by Meshcentral

### ISSUE THREAD

**Issue by compumatter** [Ylianst/MeshCentral#4940]
**Describe the bug**
I have a wildcard cert on the domain I am using for Meshcentral's login page.
However, when I start Meshcentral via node, I see it is generating its own certs.   It seems it should be using my cert instead of generating something new.

Though the video does not show this, I have tried inserting the cert in this area:
```
  "settings": {
    "cert": "desktops.smvirtual.biz",
```
However Meshcentral still generates a cert on its own.

**To Reproduce**
Edit the config.json file
Insert 
```
  "settings": {
    "cert": "desktops.smvirtual.biz",
```
Cert is created without regard to my inserting it in the config.json file

**Expected behavior**
I expected it would not need to create its own certs.

**Screenshots**
I have created a video to make the problem more clear:
* https://www.youtube.com/watch?v=XCbnDZjdokw

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: None
 - Network: WAN and LAN, reverse proxy through NGINX
 - Version: latest installed on 202.01.26
 - Node: v14.21.2

**Additional context**

**Your config.json file**
```
{
    "settings": {
      "Cert": "desktops.smvirtual.biz",
      "Port": 444,
      "AliasPort": 443,
      "RedirPort": 80,
      "AgentPong": 300,
      "TlsOffload": "127.0.0.1"
    },
}
```

**Comment by si458** [comment]
Try watching some of his YouTube videos which might help you

***@***.***

The software generates its own self signed SSL incase you don't have one,
and generates certificates which are used for encryption of AMT and other
stuff so they shouldn't be deleted on every run!?

Also try reading the news docs which might also help

https://ylianst.github.io/MeshCentral/
