### ISSUE TITLE
All new machines which I am adding is not persisting into NeDB

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#495]
1 - All new machines which I am adding is not persisting into NeDB.
2-  When new machines are connecting with the MeshCentral, I rename that machines with another custom name, but it also reset to default system name whenever I restart or update the MeshCentral.

**Comment by Ylianst** [comment]
Will look into it. What version of NodeJS are you using?

**Comment by Ylianst** [comment]
Just tested NeDB and it everything is fine for me. However, can you go in your device group and check in "Features" that the "Sync server device name to hostname" is not selected? This would cause the behavior you see.

![x](https://user-images.githubusercontent.com/1319013/65347849-be8c0180-db94-11e9-831b-bc36c006cd5e.png)

**Comment by MailYouLater** [comment]
Also, are you clicking "Install / Update" or "Connect" when you run the agent?
![image](https://user-images.githubusercontent.com/1279475/65350146-e5006b80-db99-11e9-9330-d3bad9404969.png)

If you're just clicking "Connect", then that PC won't be added to the database, when it disconnects it'll be removed from the list, and when you run the agent again, it'll go back to the default name.

**Comment by AnjaniKumar15** [comment]
> Also, are you clicking "Install / Update" or "Connect" when you run the agent?
> ![image](https://user-images.githubusercontent.com/1279475/65350146-e5006b80-db99-11e9-9330-d3bad9404969.png)
> 
> If you're just clicking "Connect", then that PC won't be added to the database, when it disconnects it'll be removed from the list, and when you run the agent again, it'll go back to the default name.

Our all machines are on Ubuntu OS

**Comment by AnjaniKumar15** [comment]
> Just tested NeDB and it everything is fine for me. However, can you go in your device group and check in "Features" that the "Sync server device name to hostname" is not selected? This would cause the behavior you see.
> 
> ![x](https://user-images.githubusercontent.com/1319013/65347849-be8c0180-db94-11e9-831b-bc36c006cd5e.png)

When I checked this option, then after this I am not able to rename the device name. Icon of rename option disappear.

![image](https://user-images.githubusercontent.com/14121807/65369077-6c1b1580-dc66-11e9-9f64-f5d23af101d8.png)
![image](https://user-images.githubusercontent.com/14121807/65369116-efd50200-dc66-11e9-8c0b-0094d94d7d28.png)

1- My all client machine are on Ubuntu OS. 
2- This issue started coming after last 2 -3 recent updates, earlier it was fine.

**Comment by AnjaniKumar15** [comment]
> Will look into it. What version of NodeJS are you using?

Node v10.15.3

**Comment by darryl-h** [comment]
@AnjaniKumar15 I've been testing some things today, with my installation, I install as a non root user, and for some reason the internal DB had it's permissions set to my current user (root) and I was getting permissions errors in the mesherrors.txt file within the data directory, might be worth a shot if you see anything odd (permissions wise) with the internal DB, or if you have a mesherrors.txt file with any errors.

**Comment by AnjaniKumar15** [comment]
Its resolved now
