### ISSUE TITLE
Meshcentral router rdp issue

### ISSUE THREAD

**Issue by MarcTechFuture** [Ylianst/MeshCentral#4953]
Hi,

First time posting, not sure if right place to ask a quastion.

I have an issue with Meshcental Router. I am able to connect to a pc with "Remote Desktop" option. Issue is when choosing RDP in drop down menu, it opens up Remote Desktop Connection app but the is no IP and port number for the computer. 

If I use Router on onother PC and try to connect to a pc with RDP option I have the local host pc IP and a port number automaticaly.

Thank for you help

**Comment by MarcTechFuture** [comment]
Does anyone have a clue on why this is hapenning? Any suggestions?

Thank you

**Comment by MarcTechFuture** [comment]
Here is a pic of what I mean, maybe sonone will know what the issue is.

Thanks
![Meshcentral router issue](https://user-images.githubusercontent.com/124291959/217548963-12242c8a-a1a7-4818-a476-2ad0a626e7b7.png)

**Comment by OutbackMatt** [comment]
I never get that, and I use router >> RDP a lot

I always get a localhost IP address and a port number

Is there anything in the drop down list for 'computer', does it change if you run Router 'as administrator'.?

**Comment by MarcTechFuture** [comment]
Any thoughts?

Thanks

**Comment by MarcTechFuture** [comment]
Can anybody give me a clue?

**Comment by OutbackMatt** [comment]
> This only happens on 1 system,

I think that is your answer
What is different about that one system?

**Comment by MarcTechFuture** [comment]
There' s nothing differente on the system, it had been working fine for at least 1 year and suddenly started doing this.Thank you 
-------- Message d'origine --------De : Matt Gilchrist ***@***.***> Date : 2023-02-22  16 h 44  (GMT-05:00) À : Ylianst/MeshCentral ***@***.***> Cc : MarcTechFuture ***@***.***>, Author ***@***.***> Objet : Re: [Ylianst/MeshCentral] Meshcentral router rdp issue (Issue #4953) 

This only happens on 1 system,

I think that is your answer
What is different about that one system?

**Comment by dinger1986** [comment]
Need much more info and following the template @si458

**Comment by si458** [comment]
try the latest version thats been released https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe
