### ISSUE TITLE
Fail Seesion Recording File

### ISSUE THREAD

**Issue by dongbokshin** [Ylianst/MeshCentral#4955]
I saved the file by pressing the session recording button on the screen. 
However, the video did not play on the player. 
A few hours later, saving and playing the file again worked normally.
Why does the same program work normally over time?

![image](https://user-images.githubusercontent.com/124327198/216500231-936c97cc-ba3c-42fe-a3db-943a716331a2.png)

** Server
 - OS: CentOS 7
 - Network: LAN/WAN
 - Version: 1.1.2
 - Node: v16.18.1

**Client Device 
 - Device: Laptop, PC
 - OS: Windows 10
 - Network:  Local to Meshcentral, Remote over WAN
 - Browser: Google Chrome, Microsft Edge
 - MeshCentralRouter Version: none
 - 

**config.json file
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```
Sample Files
[Downloads.zip](https://github.com/Ylianst/MeshCentral/files/10575150/Downloads.zip)

**Comment by si458** [comment]
Closing as stale 
Please try updating to the latest version 1.1.20 and use node 18 or above.
If ur issue still persists, please reply back
