### ISSUE TITLE
Unable to use MFA with version 1.1.0 or 1.1.2

### ISSUE THREAD

**Issue by cantlep** [Ylianst/MeshCentral#4959]
**Describe the bug**
Unable to use with hardware token (yubikey) or software TOTP app to authenticate users

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Manage Authenticator App or Manage Security Keys'
3. Add to authenticator App using barcode and try to validate current token code
4. Error Produced:  2-step login activation failed. Clear the secret from the application and try again. You only have a few minutes to enter the proper code

I should also add, previously configured accounts with MFA stopped working 2 upgrades ago (from what I can tell).

You can actually add the Yubikey (something that didn't work in earlier versions), but it won't accept it on login and produces the same error as soft tokens.

**Expected behavior**
MFA should be set up and allow logins.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. RHEL 8.7]
 - Virtualization: [None]
 - Network: [Mesh running in WAN mode. Not behind proxy.]
 - Version: [1.1.2 and 1.1.0 both have the same issue]
 - Node: [10.24.0]

**Client Device (please complete the following information):**
 - Device: [Desktop]
 - OS: [MacOS]
 - Network: [Remote over WAN]
 - Browser: [Safari]

**Additional context**
A previous user that was configured (and working) with MFA but now not, shows the following errors:
Date Time "Invalid 2FA"

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain",
    "WANonly": true,
    "sessionKey": "ItsaBIGSecretisntit"
  },
  "domains": {
    "": {
      "title": "Meshcentral",
      "_minify": true,
      "_newAccounts": true,
      "_welcomeText": "testing",
      "TitlePicture": "mesh_logo.png",
      "loginPicture": "mesh_logo.png",
      "loginfooter": "Blah 2022.",
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "email": "user@domain",
    "names": "mesh.domain",
    "production": true
  }
}

```

**Comment by Brodur** [comment]
Hey cantlep,

I've run into this problem before in different applications, where the root cause ended up being a large enough time differential between the server and the client that the TOTP codes were not valid on the server.

I'd recommend checking that your server and client times are aligned. 

Regards,

**Comment by cantlep** [comment]
@Brodur I am an idiot. Thank you very much. The time was out by longer than the token code is valid for. Problem solved.

**Comment by Brodur** [comment]
No worries, glad that fixed it!
