### ISSUE TITLE
MeshCtrl incorrectly always uses "admin" as the login name

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#496]
**Problem Description:** When the first created user's name is not "admin" the login attempt may fail for meshctrl. Additionally, after this failure you may be unable to login to the web portal with an error in mesherrors.txt which appears to implicate IPv6. After disabling IPv6, using the same user name and password on the web portal results in a successful administrative login, additionally, trying to create users in the web portal in this condition results in a popup telling me it can't find the user I'm trying to create (Sorry, I neglected to collect the exact message here, but can if it's important)

**Replication Steps:**
1) Install Mesh Central (v0.4.0-y) on Ubuntu 18.04.2
2) Login to the web portal and create the first user with the name "root"
3) Attempt to login with with meshctrl
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl ListDevices --loginuser root --loginpass password517
4) Observe error in console
Invalid login.
5) Attempt to verify login credentials on web portal via local IP
This page isn’t working
192.168.1.104 didn’t send any data.
ERR_EMPTY_RESPONSE
6) Disable IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1
7) verify login credentials on web portal via local IP
8) Observe you are able to login

**NOTE:** If I create the first user with the name "admin" everything works as expected.
1) Install Mesh Central (v0.4.0-y) on Ubuntu 18.04.2
2) Login to the web portal and create the first user with the name "admin"
3) Login with with meshctrl
/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl ListDevices --loginuser admin --loginpass password517
4) Observe the successful output

**Config.json**
{
  "settings": {
    "LANonly": true,
    "Port": 443,
    "RedirPort": 80,
    "AllowFraming": true,
    "AllowLoginToken": true
  },
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
      "UserQuota": 1048576,
      "MeshQuota": 248576,
      "NewAccounts" : true,
      "Footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>"
    }
  }
}

**Failed Web Login**
After receiving the error "Invalid login." I am now no longer able to login to the web portal to verify my credentials and I get the following error in mesherrors.txt (I was obviously able to login before to create the user)

I'm not sure if this is related, or just unlucky. Based on the error message ::ffff: it seemed to be related to ipv6, so on a whim, I disabled it using sysctl -w net.ipv6.conf.all.disable_ipv6=1, and I am able to login again.

-------- 9/20/2019, 3:16:32 PM ---- 0.4.0-y --------

/opt/meshcentral/node_modules/meshcentral/webserver.js:3713
    function cleanRemoteAddr(addr) { if (addr.startsWith('::ffff:')) { return addr.substring(7); } else { return addr; } }
                                              ^
TypeError: Cannot read property 'startsWith' of undefined
    at cleanRemoteAddr (/opt/meshcentral/node_modules/meshcentral/webserver.js:3713:47)
    at completeLoginRequest (/opt/meshcentral/node_modules/meshcentral/webserver.js:740:26)
    at /opt/meshcentral/node_modules/meshcentral/webserver.js:677:17
    at /opt/meshcentral/node_modules/meshcentral/webserver.js:415:36
    at PBKDF2.ondone (/opt/meshcentral/node_modules/meshcentral/pass.js:31:88)

**Comment by darryl-h** [comment]
sorry about the formatting, it was not my intent to have those commands in larger fonts.

**Comment by Ylianst** [comment]
Working on it! What version of NodeJS are you using?

**Comment by Ylianst** [comment]
Published MeshCentral 0.4.0-z with a fix for this, let me know if it work.

**Comment by darryl-h** [comment]
Thanks for the quick reply, and great work on this project and all the great documentation.

I'm running Node version: v8.10.0 (node -v)

The network disconnection does not appear to happen, but the meshctrl still fails with **invalid login**

**Example:**
_/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl ServerInfo --loginuser root --loginpass password517_
Invalid login.

If I roll back the state of the VM before the appending of the user with the "root" username, then create the account with admin, it works as expected:

_/usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl ServerInfo --loginuser admin --loginpass password517_

name: un-configured
mpsname: un-configured
mpsport: 4433
port: 443
emailcheck: false
domainauth: false
tlshash: 61A84D2D8F9D401794958F3E04387F1A827704C4550E5EE072B5C2C8B0B41F590F221444F72B5A25A81AA8BD63434B55
https: true
redirport: 80

Perhaps I did the upgrade incorrectly? 

**Upgrade Method:**
_cd /opt/meshcentral
npm install meshcentral_

**Which results in:**
/opt/meshcentral
└─┬ meshcentral@0.4.0-z
  └─┬ express-handlebars@3.1.0
    └── handlebars@4.2.1

npm WARN enoent ENOENT: no such file or directory, open '/opt/meshcentral/package.json'
npm WARN meshcentral No description
npm WARN meshcentral No repository field.
npm WARN meshcentral No README data
npm WARN meshcentral No license field.

Also, running internal DB, not Mongo at the moment, not sure if that is relevant in this situation.

**Comment by darryl-h** [comment]
I also tested this against the admin username "tester" and it also results in the same **failed login** error message, therefore, it's not specific to the username "root" (Which I thought maybe it could be because root has an account on the system, so I tested against an account that does not exist on the system)

**Comment by Ylianst** [comment]
Ok. I will be working on this issue. Just to be clear you can login using the web page, but not with "meshctrl"?

Thank you for the detailed description, this is very useful!

**Comment by darryl-h** [comment]
> Ok. I will be working on this issue. Just to be clear you can login using the web page, but not with "meshctrl"?
This is correct. As per http://info.meshcentral.com/downloads/MeshCentral2/MeshCtrlUsersGuide-0.0.1.pdf#page=5 meshctrl and the web portal should use the same credentials. This is how I ran into the IPv6 issue while trying to ensure that I was using valid credentials before filing this report.

**Comment by Ylianst** [comment]
I found the issue. MeshCtrl is always using it's default "admin" username even when you specify --loginuser [username]. This is not right, I have a fix that I will release shortly. This does not affect the MeshCentral server at all.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-a with a fix for this. This is also a big release, all new MeshAgents on all platforms.

**Comment by darryl-h** [comment]
You sir are a gentleman and a scholar. Issue has been resolved. Thank you!

_/opt/meshcentral# /usr/bin/node /opt/meshcentral/node_modules/meshcentral/meshctrl ServerInfo --loginuser root --loginpass password517_

name: un-configured
mpsname: un-configured
mpsport: 4433
port: 443
emailcheck: false
domainauth: false
tlshash: FA316506AB28CF53689CE995E7408549AB3DE97AC46F6B5F12C0451B0FB13435D25ACA39108C4E8F58BB3B5D9BC07EDE
https: true
redirport: 80
