### ISSUE TITLE
Add Telegram Support to Callmebot

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#4960]
No matter how hard I tried, I couldn't connect the telegram to Call Maybot in Mesh Central. Can you help me?
![vmware_xKaSul0FVo](https://user-images.githubusercontent.com/42680639/216725105-0e7d467d-d6ca-4bbb-9515-2eb0c43a4393.png)
![vmware_y4qPrW2ghK](https://user-images.githubusercontent.com/42680639/216725110-5a348e90-a041-478d-b4aa-e57723fda0be.png)

**Comment by silversword411** [comment]
Aren't you in a geolocation that is blocked/sanctioned?

**Comment by bravery-only** [comment]
callmebot is not blocked here

**Comment by si458** [comment]
PR in the works for you! 
had to make a few changes too as the callmebot url thats displayed for telegram is http instead of https!
