### ISSUE TITLE
How to deactivate user account creation?

### ISSUE THREAD

**Issue by maeries** [Ylianst/MeshCentral#4965]
**Describe your issue**
I plan to make my install accessible over the internet. Currently when someone visits the webinterface there is a link to create an account. Can I remove that to not everyone on the internet can create an account in my install? 

**Server Software:**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Network: Caddy2 reverse proxy
 - Version: 1.1.4

**Comment by si458** [comment]
you need to set `newAccounts` to false inside your `config.json` but in theory its already false from the word go
https://github.com/Ylianst/MeshCentral/blob/d9481c4537d3973bf227ec27d9093d50b49c2586/meshcentral-config-schema.json#L353
please can you share your `config.json` contents (hiding any secret info)

**Comment by OutbackMatt** [comment]
Is set true for me too, but is commented out with a leading underscore

**Comment by skyblaster** [comment]
I just encountered this issue, and the default ENV variables would be why.
https://github.com/Ylianst/MeshCentral/tree/master/docker

`ALLOW_NEW_ACCOUNTS=true`
