### ISSUE TITLE
Intel Hardware KVM / Terminal

### ISSUE THREAD

**Issue by srivera42** [Ylianst/MeshCentral#4969]
I have a MeshCentral server running on a Windows box. I am able to successfully activate my machines into ACM mode and am able to connect via an agentless group. My problem is that When I RDP using HW Connect, I have Keyboard and Mouse, but the video is black. I thought this might be due to a headless unit issue, but the problem persists with my laptop tester as well.

Another problem I have which I'm not sure is related, but popped up around the same time is that when I click 'terminal' on the machines. That screen is black as well with no input box.

![image](https://user-images.githubusercontent.com/116387345/217357422-2693a456-06fb-4272-b151-dc0271316cea.png)
![image](https://user-images.githubusercontent.com/116387345/217357579-daf5d90e-5227-4a32-960a-082e9d7608b3.png)

**Server Software (please complete the following information):**
 - OS: Windows Server 2022
 - MC Version: 1.1.4
 
**Remote Device (please complete the following information):**
 - Device: Lenovo ThinqCentre
 - OS: Windows10
 - Network: Local to Meshcentral, ACM over Ethernet
 - Current Core Version (if known): NA

**Your config.json file**
{
"domains":
    {
    "":
        {
        "_minify": true,
        "_newAccounts": true,
        "_userNameIsEmail": true,
        "AmtAcmActivation":
            {
            "certs":
                {
                "myamtcert":
                    {
                    "certpfx": "VproSSL.pfx",
                    "certpfxpass": "FakePassword1"
                    }
                },
            "log": "amtactivation.log"
            },
        "authStrategies":
            {
            "azure":
                {
                "clientid": "Nunya",
                "clientsecret": "Nunya",
                "newAccounts": true,
                "tenanted": "Nunya"
                }
            },
        "environmentDetection":
            [
            "vpro.domain.com"
            ],
        "loginPicture": "Logo.png",
        "title": "Vpro.domain",
        "title2": "Domain",
        "titlePicture": "Logo.png"
        }
    },
"settings":{
    "AutoBackup":{
        "mysqlDumpPath": "C:\\Program Files\\MariaDB 10.9\\bin\\mysqldump.exe",
        "backupIntervalHours": 24
        },
    "amtProvisioningServer":{
    "devicegroup": "mesh//devicegrouphash",
    "ip": "xx.xxx.xxx.xx",
    "newMebxPassword": "FakePassword1!",
    "port": "9971",
    "trustedFqdn": "domain.com"
},
    "MariaDB":{
        "database": "meshcentral",
        "host": "127.0.0.1",
        "password": "Nunya2",
        "port": "27017",
        "user": "MeshUser"
        },
    "MpsAliasHost": "vpro.domain.com",
    "MpsPort": 4433,
    "port": 443,
    "portBind": "xx.xxx.xx.xx",
    "cert": "vpro.domain.com",
    "_aliasPort": 443,
    "MpsAliasPort": 44330,
    "_MpsPortBind": "xx.xxx.xxx.xx",
    "_redirAliasPort": 80,
    "redirPort": 80,
    "_redirPortBind": "0.0.0.0"
    }
}

**Comment by srivera42** [comment]
![image](https://user-images.githubusercontent.com/116387345/217575175-504a75b3-b360-4e32-bd48-22b46fdfd6bc.png)

**Comment by thermionic** [comment]
HW Remote Desktop is not RDP.

To have the HW renote desktop, the "client" needs to be using the "onboard" Intel Gfx for primary output, and the "display" needs to be active, which means on a "modern" computer either laptop (possibnly with the lid up), or a HDMI/DisplayPort (or mini variants etc.) "dummy monitor" attached.

I've not used the HW Connect Terminal, but would guess that unless the OS supports a serial console there would be no response.

**Comment by srivera42** [comment]
The onboard INTEL GFX card is the only card available on my test machines.

**Comment by b8two** [comment]
Regarding the "HW Connect Terminal" if you run linux and enable serial console in GRUB to the iAMT Serial port, you will have a command prompt.

**Comment by srivera42** [comment]
the desktop being black was due to laptop screen being down.

**Comment by si458** [comment]
@srivera42 plz close this issue if it's been resolved!
