### ISSUE TITLE
Can I assign more memory to CPU and Storage for the Mesh Central Server on Windows?

### ISSUE THREAD

**Issue by FaridChaime** [Ylianst/MeshCentral#4972]
Hello Community,

Hope you are doing well!

I kindly ask you to let me know if I can assign more memory to CPU and Storage for Mesh Central Server on Windows

![1](https://user-images.githubusercontent.com/124844666/217680171-3d61d73d-ab39-4648-97e1-8fdf16ef3b2f.png)

**Server Software (please complete the following information):**
 - OS: Windows 10 Version 22H2 build SO 19045.2546
 - Virtualization: No
 - Node: 18.14.0
 
Thank you!

**Comment by PathfinderNetworks** [comment]
Not sure what you are asking?  The hardware resources that MeshCentral will use is entirely dependent on what the operating system has available.  If your server (be it a physical server or a virtual server) only has 16GB of RAM (for example) then all that MeshCentral will be able to utilize is what is available of that 16GB.  Same goes for storage.  It can only use what is physically available.   But, as far as RAM and CPU resources, MeshCentral uses very little of both but will scale up automatically as needed (at least up to the point where there is physically no more resources available).
