### ISSUE TITLE
Meshcentral - Only LAN RDP works (Video Attached)

### ISSUE THREAD

**Issue by compumatter** [Ylianst/MeshCentral#4973]
**Describe your issue**
I am not sure where the problem is.  I can connect to any Windows Pro with their embedded RDP just fine.  However I cannot use the Agent install method and external RDP also fails.   

I suspect it's something inside or not inside my config.json file but am new enough to have no idea of what it is.

Thanks in advance for your thoughts.  

The config.json file I am using is shown here https://compumatter.com/test/config.json

**Screenshots**
I have created a video to make the problem and my procedures more obvious 

https://www.youtube.com/watch?v=nOX8JfP2wTs

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: None
 - Network: LAN/WAN reverse proxy NGINX, cloudflare DNS]
 - Version: 1.1.3
 - Node:  19.1.0

**Client Device (please complete the following information):**
 - Device: Multiple tested - please see video
 - OS: Windows / Apple
 - Network: Local to Meshcentral AND Remote over WAN
 - Browser: Chrome and Firefox tested
 - MeshCentralRouter Version: Not using

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: e.g. Windows 10 22H2
 - Network:  Remote over WAN

**Your config.json file**
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "settings": {
          "type": "object",
          "properties": {
                  "debug": true,
                  "cert": "compumatter.biz",
                  "Port": 444,
                  "AliasPort": 443,
                  "keepCerts": {
                          "type": "boolean",
                          "default": false,
                          "description": "Force MeshCentral to use the HTTPS and MPS certificates even if the name does not match the expected DNS value."
                  },
                  "mariaDB": {
                          "type": "object",
                          "description": "Add this section to connect MeshCentral to a MariaDB database instance.",
                          "properties": {
                                  "host": "192.168.9.5",
                                  "user": "meshcentral",
                                  "port": 3306,
                                  "password": "xxxxxxx",
                                  "database": "meshcentral"
                          }
                  },
                  "tlsOffload": "127.0.0.1,192.168.9.5"
          }
  },
  "domaindefaults": {
                  "siteStyle": 2,
                  "_titlehtml": "",
                  "title": "RemoteMatter",
                  "title2": "SM",
                  "titlePicture": "heading-logo.png",
                  "loginPicture": "login-logo.png",
                  "_welcomePicture": "My Server",
                  "footer": "My Server",
                  "loginFooter": "My Server",
                  "hide": "My Server"
  },
  "domains": {
          "": {
                  "title": "RemoteMatter",
                  "auth": "ldap",
                  "_ldapUserName": "{{cn}}",
                  "_ldapUserBinaryKey": "objectSid",
                  "_ldapUserEmail": "mail",
                  "_ldapUserRealname": "{{{givenName}}} {{{sn}}}",
                  "_ldapUserPhoneNumber": "telephoneNumber",
                  "_ldapUserImage": "thumbnailPhoto",
                  "ldapSaveUserToFile": "/SM_DATA/mesh_central/ldapuser-save.txt",
                  "ldapUserGroups": "memberOf",
                  "ldapUserRequiredGroupMembership": ["CN={{samba_domain_administrator_username}},CN=Builtin,xxxxxxxxxxxxxxxnotdisclosed-butldapworksfinexxxxxxxxxxxxxxxx"],
                  "ldapOptions": {
                          "url": "ldap://192.168.9.5:389/",
                          "tlsOptions": {
                                  "rejectUnauthorized": false
                          },
                          "bindDN": "cn=Administrator,cn=users,xxxxxxxxxxxxxxxxx",
                          "bindCredentials": "xxxxxxx",
                          "searchBase": "cn=users,xxxxxxxxxxxxxxxxxxx",
                          "searchFilter": "(name={{username}})",
                          "reconnect": true
                  }
          }
  }
}

```

**Comment by OutbackMatt** [comment]
have you forwarded port 443 or port 444 from your modem/router to your MeshCentral Server

If you host other websites you may also need to set a reverse proxy from that server to your MeshCentral Server

**Comment by compumatter** [comment]
Hello and thanks for your thoughts Matt,

I have forwarded 443 from the router to the server.  I host many SSL sites on this server.

As for the reverse proxy, this is the NGINX code for doing this.  That part seems to work well as https://desktops.compumatter.biz comes up just fine in your / my browser window.

The reverse proxy from ngnix is in place with this code:
`server {
    listen 80;
    server_name desktops.compumatter.biz;
    return 301 https://$server_name$request_uri;
    # Inform MeshCentral about the real host, port and protocol
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

server {
  listen 443 ssl;
  server_name desktops.compumatter.biz;

  # MeshCentral uses long standing web socket connections, set longer timeouts.
  proxy_send_timeout 330s;
  proxy_read_timeout 330s;

  include sm-snippets/wildcard_ssl_certs;

 location / {
   proxy_pass https://127.0.0.1:444/;
   proxy_http_version 1.1;

   # Allows websockets over HTTPS.
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_set_header Host $host;

   # Inform MeshCentral about the real host, port and protocol
   proxy_set_header X-Forwarded-Host $host:$server_port;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
 }
}
`

**Comment by OutbackMatt** [comment]
Does your SSL certificate also cover 127.0.0.1 ??

Mine looks similar  

I don't have the proxy_set commands in the port 80 setup, just the redirect, and I have a FQDN rather than 127.0.0.1 in the port 443.

My FQDN is like "https://mesh.example.com:444/"

I use LetsEncrypt certs not self-signed ones, but I'm not sure that matters

**Comment by compumatter** [comment]
This has been resolved.  
The largest single issue was in the nginx configuration file.

This line should have been **http**, not https
```
 location / {
   proxy_pass https://127.0.0.1:444/;
````

**Comment by compumatter** [comment]
This has been resolved.  
The largest single issue was in the nginx configuration file.

This line should have been **http**, not https
```
 location / {
   proxy_pass https://127.0.0.1:444/;
````
