### ISSUE TITLE
Add authentication failed logs

### ISSUE THREAD

**Issue by a1ad** [Ylianst/MeshCentral#4978]
When we can get access to authentication logs we can write a Crowdsec parsers for it.

I know there is a build in brute force tool. But it would be nice to have it integrated with Crowdsec since you already implemented a [bouncer](https://github.com/Ylianst/MeshCentral/issues/4683). With a parser we can give some data back to the Crowdsec community.

What we would like to have in the log:
- src IP address
- failed username
- timestamp

Example log:
``` 2022-02-14 18:01:07.092 Warn Server: AUTH-ERROR: 1.1.1.1 - Invalid username or password entered. for user "test" ```

**Comment by si458** [comment]
This already partly exists

https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json#L167

**Comment by a1ad** [comment]
where did you find that log file? (i am on docker)

**Comment by a1ad** [comment]
perfect, thanks @si458
