### ISSUE TITLE
Meshcentral issue

### ISSUE THREAD

**Issue by MarcTechFuture** [Ylianst/MeshCentral#4979]
Hi,
Does anyone know of a group or forum or website where I can get help with a small issue with MeshCentral.

Thank you
Marc

**Comment by PathfinderNetworks** [comment]
You are at it.  You can use the Discussions tab here to ask questions.

**Comment by MarcTechFuture** [comment]
Well the reason I ask, is because I posted a question on an issue I am having about 8 tp 10 says ago and I got no answer at all.Technologie FutureMarc Meunier819-246-0922Sent from my Samsung Galaxy smartphone.
-------- Message d'origine --------De : Parrish Reinoehl ***@***.***> Date : 2023-02-13  13 h 08  (GMT-05:00) À : Ylianst/MeshCentral ***@***.***> Cc : MarcTechFuture ***@***.***>, Author ***@***.***> Objet : Re: [Ylianst/MeshCentral] Meshcentral issue (Issue #4979) 
You are at it.  You can use the Discussions tab here to ask questions.

**Comment by PathfinderNetworks** [comment]
Hmm, did you ask in the Discussions area or post it as an issue?  Do you have a link to the question?

**Comment by MarcTechFuture** [comment]
Hi,

This is my original question I posted. Link is 
https://github.com/Ylianst/MeshCentral/issues/4953

Thank you



Marc Meunier
tel: 819-246-0922
fax: 819-663-0111
***@***.***
www.techfuture.ca


------ Original Message ------
From "Parrish Reinoehl" ***@***.***>
To "Ylianst/MeshCentral" ***@***.***>
Cc "MarcTechFuture" ***@***.***>; "Author" 
***@***.***>
Date 2/13/2023 1:15:19 PM
Subject Re: [Ylianst/MeshCentral] Meshcentral issue (Issue #4979)

**Comment by dinger1986** [comment]
@si458 can close
