### ISSUE TITLE
Ability to make LDAP Group Sync with MeshCentral Administrators Group

### ISSUE THREAD

**Issue by compumatter** [Ylianst/MeshCentral#4986]
**Is your feature request related to a problem? Please describe.**
At present, so far as I can tell the only way to make an LDAP user an administrator within MeshCentral [is the very manual process described on this page](https://github.com/Ylianst/MeshCentral/issues/2042). 
**Describe the solution you'd like**
I am installing via Ansible.  We are using LDAP group members as a way to access MeshCentral and that is working fine.  For instance those who are part of the remote-desktop group will be able to login.  

However that just makes them a regular user.  We need a way to place them in a group like remote-desktop-admin that would sync with MeshCentral's administrator group immediately upon logging in.

**Additional context**
Is such a feature already available and perhaps I just haven't found it, or is this manual approach the only way at this point in time: https://github.com/Ylianst/MeshCentral/issues/2042

What sayeth the group?

**Comment by bluray91** [comment]
Hello !

Yes the feature is actually available, you'll find your responses in this video from Ylian : 
https://www.youtube.com/watch?v=_POULGboaCw&t=308s

**Comment by compumatter** [comment]
@bluray91 though that video is a wealth of information, it did not have the nugget I needed.

This entry into the config.json file does the trick.

"LDAPSiteAdminGroups": [ "CN=youradminusergroup,CN=Users,DC=yourdomain,DC=ext" ],

**Comment by dinger1986** [comment]
@si458 can close
