### ISSUE TITLE
Code sign question on linux server?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#4988]
**Describe your issue**
Hi i was wondering if someone could shed some light, Currently bought a code sign certificate and i have meshcentral working on a linux server, I was looking at the guide https://www.youtube.com/watch?v=HZj9igSn-sY
How would i do this process on a linux machine or would i need to copy the .exe to the windows and do it from there?

Thank you

**Comment by dinger1986** [comment]
@si458 i think needs done on windows?

**Comment by si458** [comment]
you can try something like jsign - https://www.ssl.com/how-to/microsoft-authenticode-code-signing-in-linux-with-jsign/

basically let meshcentral codesign the exe itself FIRST to inside the `signedagents` folder
then copy the exes from `signedagents` to `agents` (staying inside the `meshcentral-data` folder)
then codesign the exes in `agents` then restart your meshcentral, and meshcentral will use the agents inside `agents` for you

remember, every time the agent exes gets updated, you need to re-copy the files, re-codesign etc ...
