### ISSUE TITLE
MeshCentral v0.4.1-a does not appear to honor the MongoDB connection string in config.json

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#499]
**Problem Description:** MeshCentral v0.4.1-a does not appear to honor the MongoDB connection string in config.json as defined in source code

**Replication Steps**
1) Install MongoDB 4.2 in Ubuntu 18x on a separate server
2) Create administrator user (Has access to all the things)
3) Create MeshCentral database
4) Create MeshCentral database admin (only has access to single DB)
5) Add authorization: 'enabled' to MongoDB config
6) Add bindIp: 0.0.0.0 to allow connections from outside 127.0.0.1
7) SSH into MeshCentral server
8) Test the username and password combination
  mongo -u meshadmin -p REDACTED 192.168.1.183/meshcentral
  MongoDB shell version v3.6.3
  connecting to: mongodb://192.168.1.183:27017/meshcentral
  MongoDB server version: 4.2.0
  WARNING: shell and server versions do not match
  >
  bye
9) Observe on line https://github.com/Ylianst/MeshCentral/blob/5375cab3df65e509f5a0504c2185b9fe13cb83cc/meshcentral.js on line 119 we see "Must specify: --mongodb [connectionstring] \r\nSee https://docs.mongodb.com/manual/reference/connection-string/ for MongoDB connection string"
10) Add connection string to config.json as per http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.8.pdf page 19
    "MongoDb": "mongodb://meshadmin:REDACTED@192.168.1.183:27017/meshcentral",
    "WANonly": true,
11) Restart service
12) Observe the service restarting forever
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Sat 2019-09-21 13:16:55 UTC; 2s ago
  Process: 24164 ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral (code=exited, status=0/SUCCESS)
 Main PID: 24164 (code=exited, status=0/SUCCESS)
And later:
 ● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-09-21 13:17:20 UTC; 2s ago
 Main PID: 24276 (node)
    Tasks: 17 (limit: 1110)
   CGroup: /system.slice/meshcentral.service
           ├─24276 /usr/bin/node /opt/meshcentral/node_modules/meshcentral
           ├─24296 /bin/sh -c npm install --no-optional --save mongojs
           └─24299 npm

Sep 21 13:17:20 MeshCentral systemd[1]: meshcentral.service: Scheduled restart job, restart counter is at 58.
Sep 21 13:17:20 MeshCentral systemd[1]: Stopped MeshCentral Server.
Sep 21 13:17:20 MeshCentral systemd[1]: Started MeshCentral Server.
Sep 21 13:17:21 MeshCentral node[24276]: Installing mongodb...

**TROUBLESHOOTING:**
- Tested connection manually, appears to work (credentials look good)
- added x ahead of MongoDb, no change in behaviour, and minimal change to output (mongojs vs mongodb)
  "xMongoDb": "mongodb://meshadmin:REDACTED@192.168.1.183:27017/meshcentral",
    Sep 21 13:17:21 MeshCentral node[24276]: Installing mongojs...
- No error log created in data directory
- Removed credentials, allowed remote connection, same issue
  the command 'mongo 192.168.1.183/meshcentral' works and I'm logged in as the administrator user (recieve warning from mongoDB about what a bad idea this is)
- Tried specifying a database that does not exist, as per http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.8.pdf on page 17, there is no instruction to create the database (use meshcentral), same error

**Important Information:**
- As soon as I installed MongoDB on the local system, it then appears to work??
  sudo apt install mongodb -y
- Observe the config.json still has the old information
  "MongoDb": "mongodb://meshadmin:REDACTED@192.168.1.183:27017/meshcentral",
- In the status output of the service we see 
  Sep 21 13:31:18 MeshCentral systemd[1]: Started An object/document-oriented database.
  and the service works as expected
- Change the string to anything
  "MongoDb": "i am awesome",
- Restart service
- Observe the service still works
- Did NOT test with xMongoDB

**Comment by Ylianst** [comment]
Oh dear. As a result of #494, I added "useUnifiedTopology: true" in "node_modules/meshcentral/db.js" file. This would have caused the issue. Can you try this. Edit the "db.js" file and at line 209, change:

`require('mongodb').MongoClient.connect(parent.args.mongodb, { useNewUrlParser: true, useUnifiedTopology: true }, function (err, client) {`

to:

`require('mongodb').MongoClient.connect(parent.args.mongodb, { useNewUrlParser: true }, function (err, client) {`

Restart the server and see if that works.

**Comment by darryl-h** [comment]
It doesn't look like that fixed it, do note that this has never worked (IE: I've been using the internal db up until this point)

### Changes to node_modules/meshcentral/db.js
```javascript
 require('mongodb').MongoClient.connect(parent.args.mongodb, { useNewUrlParser: true }, function (err, client) {
```

### Testing Credentials
```
mongo -u meshadmin -p REDACTED 192.168.1.183/meshcentral
MongoDB shell version v3.6.3
connecting to: mongodb://192.168.1.183:27017/meshcentral
MongoDB server version: 4.2.0
WARNING: shell and server versions do not match
>
bye
```
## Testing with mongodb
### config.json file
"MongoDb": "mongodb://meshadmin:REDACTED@192.168.1.183:27017/meshcentral",

### results in
```
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor pres
   Active: active (running) since Sat 2019-09-21 18:21:59 UTC; 2s ago
 Main PID: 1426 (node)
    Tasks: 17 (limit: 1110)
   CGroup: /system.slice/meshcentral.service
           ├─1426 /usr/bin/node /opt/meshcentral/node_modules/meshcentral
           ├─1445 /bin/sh -c npm install --no-optional --save mongodb
           └─1449 npm

Sep 21 18:21:59 MeshCentral systemd[1]: Started MeshCentral Server.
Sep 21 18:22:00 MeshCentral node[1426]: Installing mongodb...
```
shortly after

```
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-09-21 18:22:28 UTC; 1s ago
 Main PID: 1550 (node)
    Tasks: 17 (limit: 1110)
   CGroup: /system.slice/meshcentral.service
           ├─1550 /usr/bin/node /opt/meshcentral/node_modules/meshcentral
           ├─1571 /bin/sh -c npm install --no-optional --save mongodb
           └─1574 npm

Sep 21 18:22:28 MeshCentral systemd[1]: meshcentral.service: Service hold-off time over, scheduling restart.
Sep 21 18:22:28 MeshCentral systemd[1]: meshcentral.service: Scheduled restart job, restart counter is at 14.
Sep 21 18:22:28 MeshCentral systemd[1]: Stopped MeshCentral Server.
Sep 21 18:22:28 MeshCentral systemd[1]: Started MeshCentral Server.
Sep 21 18:22:29 MeshCentral node[1550]: Installing mongodb...
```
then
```
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Sat 2019-09-21 18:22:47 UTC; 1s ago
  Process: 1609 ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral (code=exited, status=0/SUCCESS)
 Main PID: 1609 (code=exited, status=0/SUCCESS)
```

## Testing with xmongodb
### config.json file
"xMongoDb": "mongodb://meshadmin:REDACTED@192.168.1.183:27017/meshcentral",

### results in
```
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor pres
   Active: active (running) since Sat 2019-09-21 18:18:00 UTC; 4s ago
 Main PID: 913 (node)
    Tasks: 17 (limit: 1110)
   CGroup: /system.slice/meshcentral.service
           ├─913 /usr/bin/node /opt/meshcentral/node_modules/meshcentral
           ├─939 /bin/sh -c npm install --no-optional --save mongojs
           └─942 npm

Sep 21 18:18:00 MeshCentral systemd[1]: Started MeshCentral Server.
Sep 21 18:18:01 MeshCentral node[913]: Installing mongojs...
```
soon after:
```
● meshcentral.service - MeshCentral Server
   Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor pres
   Active: activating (auto-restart) since Sat 2019-09-21 18:18:20 UTC; 8s ago
  Process: 987 ExecStart=/usr/bin/node /opt/meshcentral/node_modules/meshcentral
 Main PID: 987 (code=exited, status=0/SUCCESS)
```

**Comment by darryl-h** [comment]
## Update
I left it cycling for a few hours, and came back to try in debug mode, all of a sudden, it's working now. I'm going to discard this whole environment (MeshCentral and remote MongoDB) and rebuild and re-test to ensure it's not something I did.

### Output of debug mode
_/usr/bin/node  /opt/meshcentral/node_modules/meshcentral --debug_
MAIN: Core module windows-amt is 342099 bytes.
MAIN: Core module linux-amt is 318135 bytes.
MAIN: Core module linux-noamt is 225792 bytes.
MAIN: Core module windows-recovery is 44289 bytes.
MAIN: Core module linux-recovery is 26030 bytes.
MAIN: Core module windows-agentrecovery is 24624 bytes.
MAIN: Core module linux-agentrecovery is 6365 bytes.
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.4.1-a, LAN mode.
DISPATCH: DispatchEvent [ '*' ]
MAIN: Server started
Server has no users, next new account will be site administrator.
Server customer1 has no users, next new account will be site administrator.
Server customer2 has no users, next new account will be site administrator.
MeshCentral HTTPS server running on port 443.
WEBREQUEST: /
WEB: handleRootRequestLogin()
WEBREQUEST: /scripts/common-0.0.1.js
WEBREQUEST: /styles/style.css
WEBREQUEST: /scripts/u2f-api.js
WEBREQUEST: /welcome.jpg
WEBREQUEST: /logo.png
^CServer Ctrl-C exit...

### Verify MongoDB server
I created a new devicegroup called "testdarryl" from within the MeshCentral UI, then from the 
Mesh Central server, I'm able to issue "mongo -u meshadmin -p REDACTED 192.168.1.183/meshcentral" to connect to the Mongo instance, and I'm able to verify that the object exists as expected and demonstrated below.

 _db.meshcentral.find();_
<...snip...>
{ "_id" : "mesh//QOhNCYlbop@QXoxkEVDg8dW4aaJi8vo8HphWN8G7gSO$1MltibrNkiTmb3ZARVWw", "desc" : "", "domain" : "", "links" : { "user//root" : { "name" : "root", "rights" : 4294967295 } }, "mtype" : "2", "name" : "**testdarryl**", "type" : "mesh" }

Based on the fact that the web portal works now, and the correct remote DB is being updated, I might have done something incorrect somewhere, will try and debug this more. If your still working on this, you can hold off until I update with more data if you like, hopefully I mistyped something.

**Comment by darryl-h** [comment]
Unable to replicate this behaviour. **I'm chalking this up to user error.** 

Retested in clean environment on 0.4.0-y, v0.4.1-a, v0.4.1-b, and I'm now unable to replicate the behaviour in any version. This works as expected with a remote MongoDB database, and confirmed that those changes are making it into the DB by creating a device group, and verifying the name with db.meshcentral.find();
