### ISSUE TITLE
Can use the POST method when calling the shared page?

### ISSUE THREAD

**Issue by dongbokshin** [Ylianst/MeshCentral#4990]
We generate a shared URL and deliver it to the user.
To prevent users from passing URLs to other users, we want to hide parameter values using the POST method when calling shared URLs.
Can call pages be implemented in a POST method?

![image](https://user-images.githubusercontent.com/124327198/220054609-a6b2234c-96a8-4da5-af83-b97f9be86a15.png)

**Comment by PetieM** [comment]
That's not possible as a POST still requires data which you would somehow still need to supply to the user for them to enter into a form to arrive at the same screen in the end. If you went that way, the URL would not contain the machine's ID but you'd be giving the end user that ID regardless.

**Comment by si458** [comment]
no this isnt possible as @PetieM mensioned, ad how would you POST data to a url without the end user visiting a website or something and inputting data?
