### ISSUE TITLE
Changing user rights

### ISSUE THREAD

**Issue by laboiteajb** [Ylianst/MeshCentral#4992]
Good morning,

I want to modify the user rights on a group of machines
I want to remove the right to add a new agent in group "A" but authorize the movement of machine from group "B" to "A"
I would also like to remove the rights to create guest links on group "A"

THANKS

version : 1.1.4

**Comment by dinger1986** [comment]
Is this a feature request?

**Comment by si458** [comment]
CLOSING AS STALE AND MAKES NO SENSE?
