### ISSUE TITLE
Meshcentral + Plugins

### ISSUE THREAD

**Issue by tyl0re** [Ylianst/MeshCentral#4995]
**Describe the bug**
When installing a plugin i get an error "Plugin Error" - "Value is not defined"

**Server Software (please complete the following information):**
 - OS: Debian Bulseeye
 Version: [e.g. 1.1.4]

 - Browser:Chrome&Firefox
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Debian
 - Network: Lan

**Comment by OutbackMatt** [comment]
Which plugin are you installing?

**Comment by ryanblenis** [comment]
What database are you using? Which plugin are you installing? What MC version are you on?
