### ISSUE TITLE
Agent bad web cert hash/Agent reported web cert

### ISSUE THREAD

**Issue by artem33region** [Ylianst/MeshCentral#4997]
After change web cert on meshcentral, external agents (behind Haproxy) can't connect to meshcentral.

Logs:
Agent bad web cert hash (Agent:ec3g9f456e != Server:cdf634d4c0 or b51adfgaec1), holding connection (IP:35190).
Agent reported web cert hash:ec859f436ea742d5gy8add4dd533455fb8d6a3cfc00a38821e935c9318c801fdd3834fsa3401d62b98b7760101262e77.

When i paste "IgnoreAgentHashCheck": true they are can connect, but it is not secure.

I'm using meshcentral 1.1.2 version.

I'm using wildcard certificate.

**Comment by si458** [comment]
**plz follow the bug template as it has required information to help debug your issue**
whats your config.json?
do you use a proxy in front of meshcentral?
did you restart meshcentral after the certificate change?

**Comment by artem33region** [comment]
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain.ru",
    "MongoDb": "mongodb://meshcentral:Superpassword@IP:27017/meshcentral",
    "dbRecordsEncryptKey": "superpassword",
    "WANonly": true,
    "LANonly": false,
    "sessionKey": "supersessionkey",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "redirAliasPort": 0,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false",
    "_IgnoreAgentHashCheck": true
  },
  "domains": {
      "": {
        "title": "",
        "title2": "",
        "titlepicture": "title-Company.png",
        "auth": "ldap",
        "ldapUserName": "sAMAccountName",
        "ldapUserKey": "sAMAccountName",
        "ldapOptions": {
          "url": "ldap://domain.local",
          "bindDN": "CN=user,CN=Users,DC=domain,DC=local",
          "bindCredentials": "Surerpassword",
          "searchBase": "DC=domain,DC=local",
          "searchFilter": "(sAMAccountName={{username}})"
        },
        "ldapSyncWithUserGroups": true,
        "ldapUserGroups": "memberOf",
        "ldapUserRequiredGroupMembership": [ "CN=meshcentral,OU=MeshCentral,OU=Users,OU=Company,DC=domain,DC=local" ],
        "_loginkey": "Company",
        "_certUrl": "https://mesh.domain.ru/",
        "agentCustomization": {
          "displayName": "Remote agent",
          "description": "Agent for remote management",
          "companyName": "Company",
          "serviceName": "meshcentral",
          "fileName": "meshcentral",
          "image": "agent-logo.png"
        }
      }
  },
  "_letsencrypt": {                 
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }          
}  
```

**Comment by silversword411** [comment]
I'd say the probability is high that your HAProxy config is the problem.

**Comment by artem33region** [comment]
I didn't change the Haproxy config, I just replaced the certificate.

**Comment by silversword411** [comment]
> I just replaced the certificate.

In both places?

**Comment by artem33region** [comment]
Yes.

**Comment by NiceGuyIT** [comment]
I find [cfssl-certinfo][] useful to troubleshoot these types of issues. You can download a binary from their releases page.

First start off by querying the domain as the agents would see it. Pay attention to the "sans" and "subject" keys. The "serial_number" will uniquely identify that certificate.
```bash
cfssl-certinfo -domain mesh.example.tld > cert-agents.json
```

Edit your hosts file to point the domain to your HAProxy and run the command again. You should get identical output and the serial number should match.
```bash
cfssl-certinfo -domain mesh.example.tld > cert-haproxy.json
```

Now edit your hosts file to point the domain to your MeshCentral install. You'll probably get a different certificate and the serial number will be different. What does the "sans" and "subject" keys say? This is where the cert mismatch error is coming from.
```bash
cfssl-certinfo -domain mesh.example.tld > cert-meshcentral.json
```

Your [CertUrl] is commented out and is most likely the cause of your problem. Per the docs:
> Load the TLS certificate for this domain from this https url. For example “https://127.0.0.1:123”. This option is useful when used along with the “TlsOffload” option. When MeshCentral is not doing any TLS but has a reverse-proxy or TLS offload device doing this work in front of the server, you can use this to have MeshCentral load the certificate from the server in front of MeshCentral.
>
> This is needed because when agents connect, they need to be told that the certificate they saw upon connecting is the correct one. Using this, MeshCentral will know what certificate the agents are expected to see.

[cfssl-certinfo]: https://github.com/cloudflare/cfssl

[CertUrl]: https://ylianst.github.io/MeshCentral/meshcentral/#domains

**Comment by artem33region** [comment]
I found the problem!
On Haproxy i use fullchain cert, on mesh only last cert...
Thanks all!

**Comment by mattague** [comment]
Im using HAProxy and running into this as well. Could you clarify what you mean by this? I had to reinstall MeshCentral, and hadn't changed anything about my HAProxy setup, so I think I am missing something in my setup of MeshCentral.

**Comment by mattague** [comment]
For posterity:

in your config.json, under domains make sure you set your `"certUrl"` as referenced [here](https://ylianst.github.io/MeshCentral/meshcentral/#server-certificate) to whatever your full domain is externally. This allows meshcentral to view the external certificat the agents are seeing and validate its the same one.

**Comment by dinger1986** [comment]
@si458 can close

**Comment by Jhonfare77** [comment]
Efectivamente la solución es colocar "CertUrl": "https://proxy-addres:prxoy-port"
