### ISSUE TITLE
User ejecting 

### ISSUE THREAD

**Issue by bluray91** [Ylianst/MeshCentral#4999]
Hello,

First of all, I'd like to thank you all for your contribution on this very awesome tool. I'm having a blast on it. I'm simply amazed by it and how well it has been done. Can't stress it enough.

I'm using meshcentral v1.1.0 and everything is working quite well.
I'll gladly help on the community as I'm getting a bit more experienced on the software. hope this community will arise!

I do have 2 questions though :
I can't seem to grasp 2 things about consentment : 

- Can the user eject the administrator from the remote session ?
- Is there a way to make appear a notification -> For the user <- when a session has ended ? (Just so the user don't become paranoiac, as nothing is indicating when a session is on or not [at least that I could find] )

Again, thanks a lot for your help !

**Comment by mikep345678** [comment]
I'd like to see those two pieces as well! If this isn't currently possible, how do we add a feature request?

What I'd like is to be able to set that the user "X"ing out of the DesktopPrivacyBar would disconnect the session and prompt a user-side notification of disconnection. Pie-in-the-sky addition to that would be a "Stop Sharing" button on the DesktopPrivacyBar (like ChromeRemoteDesktop offers)!


Mike

**Comment by dinger1986** [comment]
Both are supported

If you need to comply with GDPR regulations and ensure employee rights legislation is complied with, you can make sure that users receive a popup to inform them so they are aware when your techs log in and connect to their machine. You can enable a banner that shows when a remote connection is established.

Remote background a machine then go to mesh.EXAMPLE.COM
Click on My Account
Click on the device group you want to enable notifications or accept connection etc
Next to User Consent click edit (the wee pencil)
Features
You can also change features by ticking whatever boxes you want in there (Features: Sync server device name to hostname, Automatically remove inactive devices, Notify/Prompt for Consent/Connection Toolbar settings).
Features
Ok your way out

If the end user closes the bar it will kick you out

@si458 can close
