### ISSUE TITLE
Always have Npm WARM DEPCATED Graceful-fs@3.0..11 on first install

### ISSUE THREAD

**Issue by LinkPhoenix** [Ylianst/MeshCentral#5]
whenever I install via NPM meshcentral I always have this error that I do not see in the video

`
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and futur versions of node.js
`

Is this normal?

The problem resolves with an "npm update" after installation

**Comment by Ylianst** [comment]
Hi. I noticed this but have not investigated it yet. One of the modules that MeshCentral uses needs to update to this new modules. For now it's ok, it will work fine. I will investigate when I can.

Ylian
________________________________

**Comment by LinkPhoenix** [comment]
Hi.

thank you for the answer, so we can know where the problem comes from. From memory it's 3 or 4 modules that update themselves. I Check it tomorrow.

**Comment by LinkPhoenix** [comment]
The message after "npm update" is

```
+ cookie-signature@1.1.0
+ immediate@3.2.3
+ lie@3.2.0
+ binary-search-tree@0.2.6
added 6 packages and updated 4 packages in 1.366s

```

**Comment by Ylianst** [comment]
This problem should be long gone as I updated the dependencies of MeshCentral. Please re-open if you see this again.
