### ISSUE TITLE
folders transfer

### ISSUE THREAD

**Issue by payon** [Ylianst/MeshCentral#50]
1. Can I transfer folders from a remote desktop?

2. Is it possible to paste the copy from the admin screen onto the remote desktop screen?

**Comment by Ylianst** [comment]
I certainly need to add batch file transfers. Should not be a problem when uploading to the remote machine. I don't know about folder download however, would need to zip the folder on the remote side before download.

**Comment by Ylianst** [comment]
Will check at some point for remote clipboard support.

**Comment by whalehub** [comment]
@Ylianst Any update on this?

**Comment by krayon007** [comment]
I'm working on getting the agent to tar the folder. There are some other bugs I got distracted with before finishing this. But support will be coming...

**Comment by Ylianst** [comment]
Closing as this is a duplicate of #323
