### ISSUE TITLE
Meshcentral router issue

### ISSUE THREAD

**Issue by MarcTechFuture** [Ylianst/MeshCentral#5000]
Hi,

I am trying my question here because no one seems to read my question.  https://github.com/Ylianst/MeshCentral/issues/4953

Issue is nothing shows up. No Ip add not port

![Meshcentral router issue](https://user-images.githubusercontent.com/124291959/220714574-f8743714-9a3b-4019-a1de-41deb161ecf3.png)

Thanks

**Comment by PathfinderNetworks** [comment]
Sorry,
I hadn't really had a chance to respond until now- been super busy with customer projects.  
Unfortunately I don't know what would be causing that.  On my end, when going through the same steps, it populates the Computer: field with the home address of the computer I'm on (in other words 127.0.0.1:17150).  The port number will be random though, so 17150 is just what I happened to see in the test.  
What version of MeshCentral Router do you have?  The properties for mine show it is as being 1.8.8332.12691
Also, is your user account a full admin account on the PC you are running this on?  I don't know if that could be it or not- but I wonder if the MeshCentral Router app doesn't have the access rights to populate the RDP tool when it pops it open?

**Comment by si458** [comment]
try the latest version thats been released https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshCentralRouter.exe
