### ISSUE TITLE
Intel AMT Unprovisioning/Unconfigure

### ISSUE THREAD

**Issue by aislerad** [Ylianst/MeshCentral#5001]
Is there a way thru Mesh central to unprovision or unconfigure machines remotely. I no how to unprovison the machine if I was next to it but I have a test box that is in a different location and I don't currently no the password so I'm unable to unconfigure it thru acuwizard tool. If anyone has any suggestions or tips to get it unprovsioned remotely without the password please let me know.

**Comment by dinger1986** [comment]
AMT is difficult without access to numerous AMT devices which isn't possible anymore for the project @si458 can close

**Comment by si458** [comment]
you can upload the meshcmd.exe to the device using files, then run the command in terminal
`meshcmd.exe AmtDeactivate` to deactivate the CCM mode
OR
`meshcmd.exe AmtAcmDeactivate --user admin --pass AMTPASSWORDHERE --type full` to deactivate the ACM mode

remember ACM deactivate DOESNT RESET THE MBEX PASSWORD TO FACTORY `admin`!
