### ISSUE TITLE
Access MEBX Thru Mesh Central

### ISSUE THREAD

**Issue by aislerad** [Ylianst/MeshCentral#5002]
Is it possible to get to the MEBX thru Mesh Central with the agent? Currently only way to get to it is by hitting CTRL +P which requires you to be in front of the machine. Can you add an option to boot to MEBX?

**Comment by jsastriawan** [comment]
It is not possible. MEBx is (must be) disabled from remote access whether AMT is activated or not. This is for security reason.

**Comment by si458** [comment]
closing as @jsastriawan is correct, this isnt possible, even intel say themselves, you cant access the MEBx using AMT remotely
