### ISSUE TITLE
Ark Server manager displays only white screen

### ISSUE THREAD

**Issue by lizardkng** [Ylianst/MeshCentral#5006]
So when I remote into a W10 machine at home, everything seems to work great, but the Ark Server manager" application doesn't display correctly. I am not a programmer so I can't offer any advice as to why it might be happening, but it's just a white screen, acting like it's not responding. But tooltip bubbles do pop up when your mouse is over the right location on the screen, and you can click the buttons that exist there, you just can't see them.

In this screenshot, my mouse is over the "Open Server Logs" button and it would work if I clicked it, but as you can see the entire screen is white. It's the only app I've found that does this.

![Untitled](https://user-images.githubusercontent.com/80914453/221319735-40765631-a6b7-4e4d-910a-65c6d18c3d84.png)

**Comment by silversword411** [comment]
Probably direct drawing to hardware (monitor) with ActiveX or something for performance.

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.20, and use node 18 or above,
if issue still persists, please reply back and let us know
