### ISSUE TITLE
Documentation : Consider moving windows installation of MongoDB from MeshCentral2UserGuide into MeshCentral2InstallGuide

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#501]
**Problem Description:** Within the current Install Guide http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf , there is no method to install MongoDB in windows like there is for other platforms. 

You may wish to consider moving the windows installation of MongoDB from MeshCentral2UserGuide into MeshCentral2InstallGuide with the other installations of MongoDB in each respective platform so it's all in one place. 

I feel like the MongoDB (and Database Import) are the only two items in the user guide that a user would not really manage (Although, it's certainly helpful to know!)

**Comment by si458** [comment]
we have all new docs here https://ylianst.github.io/MeshCentral/install/install2/
