### ISSUE TITLE
Keyboard not working when use MeshCentral Router

### ISSUE THREAD

**Issue by rbellagamba** [Ylianst/MeshCentral#5010]
Hello.
I installed meshcentral on cloud vm.
Within the browser, I don't have any problems, I can connect to all my computers with success.

But when I try to connect with MeshCentral router with desktop function, the keyboard doesn't work (the mouse works correctly).
I tried to update the meshcentral to the last version, but there aren't changes.

Do you have any ideas of this problems?

Any help is appreciated.

Thanks very much.

**Comment by CapriPL** [comment]
Hi.

I am a new MeshCentral user, thank you for a very good project.
MC Router is a very convenient application, but the problem with the keyboard not working in desktop mode forces me to connect via the web browser panel.
Is there a chance to remove the bug that 'rbellagamba' wrote about?

Regards, G.
