### ISSUE TITLE
Corrupted .mcrec desktop recording

### ISSUE THREAD

**Issue by leleb** [Ylianst/MeshCentral#5019]
HI,
I have downloaded a desktop recording .mcrec file but could not play in the player (when opening or drag-drop nothing happens)
I opened it with an hex editor to compare differences with a good recorded file.
Header of the file looks similar but the tail is missing the indexing information.
The bad  file ends with: {"indexInterval"
while the good one as a indexing data following.
I tried to merge the two file unsuccessfully.
Is there a possibility to recover the video? Are there specifications for the format of the file (header, data format) ?
Thanks

**Comment by leleb** [comment]
I succeded viewing the file: I overwrited header and added tail from a good recording.
Unfortunately indexing is completely wrong, play time is negative, can't advance using the scroll bar

**Comment by si458** [comment]
it might be the is an issue with your machine running meshcentral and indexing, have u tried turning off indexing?
it might also have been indexing while u downloaded the file so the the file was incomplete

**Comment by si458** [comment]
so i have just discovered this bug while trying to fix the sessionrecording bug,
i cant always replicate the issue 100% of the time, its more like 30% of the time it happens, but its still a bug!
