### ISSUE TITLE
active directory integration

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#502]
Friends, good afternoon!

How do I configure meshcentral to perform active directory integration in the authentication part of the tool? It's possible?

Can I also apply permissions per active directory group if possible?

The screen I need to know this doubt is the one attached.

![image](https://user-images.githubusercontent.com/55212206/65444735-0e71ff00-de07-11e9-9fc8-41902ba616a9.png)

**Comment by Ylianst** [comment]
You will need to install MeshCentral on a Windows machine that is part of your domain, when run MeshCentral with "auth":"sspi" in the domain section of config.json. Once this is done, you will no longer see a login screen. Users will directly login to the server. There are no active directory group permissions yet. Try it and let me know if it works.

```
{
  "settings": {
    "Port": 443,
    "RedirPort": 80
  },
  "domains": {
    "": {
      "Title": "MyServer",
      "Title2": "Servername",
      "auth": "sspi"
    }
  }
}
```

**Comment by geanferrani123** [comment]
in linux da to do?

**Comment by geanferrani123** [comment]
in linux is it possible to do?

**Comment by geanferrani123** [comment]
> You will need to install MeshCentral on a Windows machine that is part of your domain, when run MeshCentral with "auth":"sspi" in the domain section of config.json. Once this is done, you will no longer see a login screen. Users will directly login to the server. There are no active directory group permissions yet. Try it and let me know if it works.
> 
> ```
> {
>   "settings": {
>     "Port": 443,
>     "RedirPort": 80
>   },
>   "domains": {
>     "": {
>       "Title": "MyServer",
>       "Title2": "Servername",
>       "auth": "sspi"
>     }
>   }
> }
> ```
he accessed but with basic access, can you change that?

![image](https://user-images.githubusercontent.com/55212206/65449535-91985280-de11-11e9-861f-dc89efc63042.png)

**Comment by Ylianst** [comment]
No, right now domain controller support is only supported on Windows servers.

**Comment by geanferrani123** [comment]
Right, but how to access the admin interface? See in print, does not appear as user settings, how to change it?

**Comment by Ylianst** [comment]
Oh. Normally the first one to login is the administrator. But you can also do:

`node node_modules/meshcentral --user admin`

When use the admin to go in "My Users" tab and grant your domain user full admin rights. Then, you go back and run the server normally. Hope it helps.

**Comment by geanferrani123** [comment]
Unfortunately on windows this command does not work. Do you have any plans to develop a well-structured integration with active directory?

**Comment by Ylianst** [comment]
Yes, this works on Windows. You can also remove "auth":"sspi" and restart the server. Then, login as administrator and set your domain account to full privileges. Then, put "auth":"sspi" again and restart. MeshCentral has good support for active directory now, just does not use AD groups yet.
