### ISSUE TITLE
File explorer requests

### ISSUE THREAD

**Issue by Allowee** [Ylianst/MeshCentral#503]
I have a few requests/nice to have for the files section:

When using the file explorer I had a hard time matching the files with their file dates.
Would it be possible to implement alternating colors for the files list.

Overwrite/delete notification dialog?

A file viewer/editor would also be handy

mass download for selected files (without zip function) #323

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-e with a new mouse hover gray line in the "My Files" tab. Hopefully that will help without the alternating colors that would not look great. Let me know what you think.

![x](https://user-images.githubusercontent.com/1319013/65536138-ae876100-deb7-11e9-96dd-adfc901ebd95.png)

"Delete" already has a confirmation dialog box, I could do one for overwrite.

Mass downloads is not something browsers support, but you can zip/tar and that is still something we need to add.

**Comment by darryl-h** [comment]
+1 vote for multiple file downloads, I like the idea of zipping/tar before and sending as single file.

**Comment by MailYouLater** [comment]
FYI, a `.tar` file can be gzipped (to create `.tar.gz`/`.tgz` file) on the fly, which would decrease the size of the file and the network traffic required to transmit it.
Also, it would be nice if we could choose to use `.zip` or `.tar`/`.tgz`, as many people prefer zip on Windows and tar/tgz on Linux, but others pick one format for use on both platforms, and if you use 7-Zip to create the archive, having a `.7z` option would be really nice too.

A `.dmg` option would be really nice for Mac users too, but I'm not sure how feasible that is for non-Mac agents, as creating a `.dmg` under other OSes doesn't seem to be supported by any Free/Open Source software I could find.  I doubt it would be too difficult to add for agents running on Mac though.

**Comment by Ylianst** [comment]
So, that is all nice but the MeshAgent will need to do the tag/zip/gz/dmg work on the remote side and I want to limit the size of the agent as much as possible. Also, the agent will have to perform this on-the-fly and you want to send the same as they are read, so .tar or .tar/gz would work (but we don't have a gzip in the agent right now).

Bryan will decide on this, but probably start with .tar first.

**Comment by Allowee** [comment]
Awesome the new hover helps a lot!

For the multi download, maybe calling p13downloadfile() for the selected files would be a possibility?

**Comment by MailYouLater** [comment]
So there were multiple requests in the OP.  This comment is basically to re-thread the above statements to update the status of each.

---

- >>> When using the file explorer I had a hard time matching the files with their file dates.
  >>> Would it be possible to implement alternating colors for the files list.
  >>
  >> Published MeshCentral v0.4.1-e with a new mouse hover gray line in the "My Files" tab. Hopefully that will help without the alternating colors that would not look great. Let me know what you think.
  >
  > Awesome the new hover helps a lot!
  
  While an option to show alternating colors might still be a nice addition, it sounds like the currently implemented hover color improved the usability of the file transfer screen to the satisfaction of the requester, so for the purpose of this issue, we can count this part as done.

- > mass download for selected files (without zip function) #323
  
  There's been a bit of discussion here about it, but realistically, mass file download without making them all one file (zip/tar/etc.) is not going to happen until/unless browsers add support for it, which doesn't seem likely in the near future, and even then, it may still not be feasible, also mass download in an archive already has a ticket of its own: #323, where Bryan/krayon007 has stated that he's working on it, and any more discussion regarding it should go there.  
(Sorry for not taking my comments about it there sooner.)

---
  
### So the remaining parts that this ticket still covers are:

- >> Overwrite/delete notification dialog?
  >
  > "Delete" already has a confirmation dialog box, I could do one for overwrite.
  
  When selecting files to delete, and pressing the Delete brings up this
  ![Delete 2 selected items? OK/Cancel](https://user-images.githubusercontent.com/1279475/65717496-576bc280-e056-11e9-9583-f1ffa9442ca1.png)
  However, when uploading a file (either by drag & drop, or by clicking the Upload button and browsing for the file) there is _no_ confirmation dialog whatsoever if a file with the same name already exists in the folder.  This is very dangerous, please fix.

- > A file viewer/editor would also be handy
  
  I have also wished I could view a 'preview' of a text file without having to save it to a file on my local disk, then open that.  This would be a _very_ welcome user experience improvement.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-l with new "View" button in device "My Files" tab. Let me know if that works.

![MC2-DeviceShowFile](https://user-images.githubusercontent.com/1319013/65728180-074d2a00-e06f-11e9-96b5-bc89e95c7448.png)

**Comment by MailYouLater** [comment]
Awesome, that helps a lot.

Perhaps the user experience could be improved a little.  For instance, it would be nice if the width of the preview could expand a bit more, perhaps depending on the width of the window?

Thanks.

**Comment by Ylianst** [comment]
Agreed. I will take a look at making it wider.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-m. The file viewer is now a text file editor and added the warning prompt when files will be overwritten. Feedback appreciated.

![MC2-FileEditor](https://user-images.githubusercontent.com/1319013/65794617-64071e00-e11d-11e9-97cd-9e241c7ee881.png)

**Comment by MailYouLater** [comment]
Awesome. I'll have to try it soon.

**Comment by dinger1986** [comment]
pretty sure this has all be implemented in some way @si458

**Comment by si458** [comment]
all implemented
