### ISSUE TITLE
Windows 10 Treating Agent As Virus

### ISSUE THREAD

**Issue by compumatter** [Ylianst/MeshCentral#5031]
**Describe your issue**
Downloaded the Windows 64 Background and Interactive as a test on a windows machine on our Internal network.

Can't install the agent on a Windows 10 client.  Any ideas of why this would be?  

Gets one of two errors:
**Screenshots**
![image](https://user-images.githubusercontent.com/121611/223635425-f0bf3e51-f68d-4d08-be77-445e39dd3240.png)
![image](https://user-images.githubusercontent.com/121611/223635533-4a96cbdd-ddb4-4df6-80a1-d9ada4f12188.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: None
 - Network: Hybrid Mode NGINX
 - Version: 1.14
 - Node: 19.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 Pro
 - Network: LAN / Internal
 - Browser: Chrome
 - MeshCentralRouter Version: N/A

**Comment by dinger1986** [comment]
Is it showing as code signed?

**Comment by si458** [comment]
This is standard practice at the moment because bad people have used the software in the past for taking control of machines

If you code-sign the exe it should help with antivirus software knowing its not a virus

Beat thing to do is submit the exe to your antivirus software company and tell them its a false positive with proof

**Comment by PathfinderNetworks** [comment]
The only way I was able to get around this was to buy a code signing certificate and sign my agents with my own certificate.  I also had to brand the agent as well as submit the signed and branded agent to my primary Antivirus vendor (Avast) to have them whitelist it.

**Comment by compumatter** [comment]
Thank you @PathfinderNetworks  and @si458 .  This is the road I am currently going down.   Signed up today for the code signing.   A new road for me.  That should get it past a lot of flagging and flogging ;-)  Hopefully anti-virus software will be more accepting or yes, I'll be going through each of their submission processes.

**Comment by PathfinderNetworks** [comment]
Mine is a Sectigo code signing cert that I bought from ssl2buy.com.  At the time it was the least costly option I could find.  Still may be.

**Comment by si458** [comment]
We bought ours from https://comodosslstore.com/uk/codesigning.aspx

£180 for 3 years

**Comment by AnnaShipman1986** [comment]
> Mine is a Sectigo code signing cert that I bought from ssl2buy.com. At the time it was the least costly option I could find. Still may be.

Yes Sectigo code signing cert is indeed a good option! I got my sectigo code signing certificate from SignMyCode.com at [$44.99/per year](https://signmycode.com/sectigo-code-signing).

**Comment by dinger1986** [comment]
@si458 can close
