### ISSUE TITLE
Client popup on disconnection

### ISSUE THREAD

**Issue by andreapx** [Ylianst/MeshCentral#5032]
**Is your feature request related to a problem? Please describe.**
When I connect to some clients asking for consent, they don't know if I disconnect or not

**Describe the solution you'd like**
When (after connecting asking consent) I disconnect from a client, on that client should popup a message saying that I disconnected

**Describe alternatives you've considered**
I don't see any alternative.

**Additional context**
N/A

**Comment by MrVinyla** [comment]
and it would be good if it showed how long the session lasted

**Comment by si458** [comment]
you can right click on the connect button and use 'ask for concent + bar'
this will ask for consent and show a bar at the top when you are connected
then when you disconnect the bar vanishes

**Comment by andreapx** [comment]
> you can right click on the connect button and use 'ask for concent + bar' this will ask for consent and show a bar at the top when you are connected then when you disconnect the bar vanishes

Oh, that's what the bar is! Thanks!!!
