### ISSUE TITLE
Question about multi-domain

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#5039]
**Describe your issue**
I am trying to setup multi-domain configuration in a production environment. Is there a guideline to add/modify domain setting without down time?

Here is what I am trying to achieve. I want to add a new domain, which now requires service down time. Once domain is created, I need to add a device group and I want to make that as default group for mesh central users. I am doing it by adding `newAccountsUserGroups` value under config.json, which again requires a down time to take effect.

**Screenshots**
N/A

**Server Software (please complete the following information):**
 - OS: Windows
 - Virtualization: No
 - Network: WAN
 - Version: 1.1.0
 - Node: 18.13.0
**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "myserver.mydomain.com",
    "WANonly": true,
    "LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
	"": {
		"siteStyle": 1,
		"title": "MyRemote",
		"title2": "Remote Control",
		"minify": true,
		"newAccounts": true,
		"welcomeText": "MyRemote Remote control Management Integration Tool",
		"welcomePicture": "mainwelcome.jpg"
	},
	"domain1": {
		"siteStyle": 1,
		"title": "D1",
		"title2": "Remote Control",
		"minify": true,
		"newAccounts": true,
		"newAccountsUserGroups": ["ugrp//mnxgBzTaOm06PS3NhP3zxXLMwXQ9u4z511k8Eb887$DjQO78PL1Ych3oqbZ08lIV"],
		"welcomeText": "D1 Remote control Management Integration Tool",
		"welcomePicture": "mainwelcome.jpg"
	}
  }
}
```

**Comment by si458** [comment]
No

I believe you have to restart the meshcentral server every time because you have edited the config.json

https://www.youtube.com/watch?v=eqInqM9olXA - video explaining multiple domains/accounts

**Comment by knkumar93** [comment]
OK Thanks for confirming @si458
