### ISSUE TITLE
Identify Recordings

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#504]
Dear, good afternoon!

Is there any way to more objectively discover a specific session that has been recorded? Example:

Today there were 20 hits, but I want to find out the time that attendant X connected on the machine of user Y to perform remote answering.

Is there a way to configure the system to generate this type of ID when recording the session?

**Comment by Ylianst** [comment]
So, within each .mcrec near the start, there is JSON text with a bunch of metadata about the recording. I can change the file name if you like, or I could make it so you could drag & drop a bunch of files and see all their metadata at once?

**Comment by geanferrani123** [comment]
Ylianst

I think if the name of the recording file itself contains the name of the machine that was accessed it would be better because I saw that when we opened it inside the player.htm da to see the user who connected.

Could you do something about it?

**Comment by geanferrani123** [comment]
Friend, can you help me?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-h with the user name and device name in the filename. Let me know if that works.

**Comment by geanferrani123** [comment]
Thank you, I will test and return to you. Please keep this topic open until my return.

**Comment by geanferrani123** [comment]
Friend, worked perfectly, thank you!

**Comment by Ylianst** [comment]
Perfect, closing this one.
