### ISSUE TITLE
Forcing of MFA not working.

### ISSUE THREAD

**Issue by joostrinkes** [Ylianst/MeshCentral#5047]
We have a Mesh central server running on a Azure VM. We want to force our users to use MFA. At the moment the users can do so, but it is not forced.
To force it we have added :
"domains": {
    "": {
      "title": "MeshCentral",
      "title2": "Server1",
	  "passwordRequirements": {
	"lock2factor": "true",
     "force2factor": "true"
	 }
	}

To the config file, but still the MFA is not forced.
Is their more config required? Or should the MFA work with these settings?

thanks

**Comment by si458** [comment]
`lock2factor` prevents any changes to 2FA, and `force2factor` Requires that all accounts setup 2FA
so they sorta contradict each other and cancel each other out
you should only need `force2factor`
