### ISSUE TITLE
The SSH Command is missing from Terminal 

### ISSUE THREAD

**Issue by TeomPython** [Ylianst/MeshCentral#5048]
**Describe your issue**
This is a new install of Mesh Central Version 1.1.4. I have installed the mesh central agent on the Ubuntu 20.04 its server and working for desktop and terminal. However, in terminal I do not see the option for SSH command and HW connect next to Connect button. I want to use the SSH cert authentication option and serial SSH option. Am I missing key and value in config.json file? Is so, what are the keys and value? Thank you.  

**Screenshots**
![SSH Command is missing from Terminal 1 of 2](https://user-images.githubusercontent.com/20643370/226080558-1ea934ff-1a4e-4aec-a464-a4fc2487fb57.png)
![SSH Command is missing from Terminal 2 of 2](https://user-images.githubusercontent.com/20643370/226080565-b91932e5-fb21-4a12-83d7-00be95c5cc87.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Bare Metal
 - Network: LAN
 - Version of Mesh Central: 1.1.4
 - Node: v19.7.0

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
You have to set `"ssh": true` under your domains section in config.json
