### ISSUE TITLE
Agent becoming duplicated over time

### ISSUE THREAD

**Issue by llambkin** [Ylianst/MeshCentral#5049]
Hello All,

I have a particular agent that keeps getting duplicated, and the previous agent goes dark. Can someone please tell me if this is a bug or how I might go about solving this issue?

Attached is an image of the issue, the PC in question is CCTV-PC, I have renamed it to Print-Hall-PC a few times, then it goes dark, then reconnects and calls itself CCTV-PC again. It wouldn't be such an issue if we didn't need to identify which CCTV PC we need to remote support.
![image](https://user-images.githubusercontent.com/3177909/226087546-d77b5495-1537-4b8b-8ac3-8fe460ab8a91.png)

**Comment by si458** [comment]
I have this problem weirdly with my laptop

The issue seems to be when i connect my vpn using wireguard or connect a Bluetooth device

Then the mac addresses of my network devices changes

So when i restart the mesh agent, it checks the mac addresses, realises they are different and generates a new id for my laptop then adds the device again to meshcentral

Hope this helps...

**Comment by si458** [comment]
@silversword411 is the only explanation I have found so fair, 

If I correct to my vpn, a network device is created/added, then when my laptop goes to sleepy and wake up the vpn is still connected as expected (its wireguard udp) but then a duplicate device appears

**Comment by silversword411** [comment]
@si458 pretty sure wireguard installs its own adapter that has a Mac address that doesn't change. 

I'm wondering it's the quick disconnect/reconnect from a different source IP that might be causing the event

**Comment by si458** [comment]
> @si458 pretty sure wireguard installs its own adapter that has a Mac address that doesn't change. 
> 
> I'm wondering it's the quick disconnect/reconnect from a different source IP that might be causing the event

Not in my case, as my laptop is pretty much always at home and it happens when I'm at home and the mac address defo changes when u activate/deactivate the wireguard

**Comment by silversword411** [comment]
Just going thru the thought process.

How does the agent identify itself to the server. Private key in msh file right?

So is the msh file changing?

What would cause the msh to regenerate a key.

Is it dupe agent code sensing?

**Comment by bravery-only** [comment]
agent duplicating ....
 log :

[2023-03-19 10:06:02 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Could not find suitable CngProvider
[2023-03-19 10:06:02 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Error opening Microsoft Certificate Store
[2023-03-19 10:06:02 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Info: No certificate was found in db
[2023-04-12 05:34:46 AM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:2776 (0,0) FATAL EXCEPTION @ [FuncAddr: 0x00000000770ba515 / BaseAddr: 0x000000013f7c0160 / Delta: 3362806859]
    [RtlFreeHeap]

[2023-04-16 10:29:29 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Could not find suitable CngProvider
[2023-04-16 10:29:29 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Error opening Microsoft Certificate Store
[2023-04-16 10:29:29 PM] [535E0BEFA8B7C0FE] ..\microstack\ILibParsers.c:10978 (0,0) Info: No certificate was found in db

**Comment by silversword411** [comment]
> agent duplicating ....
> log :

These are agent logs? How are you getting these? Like this? https://ylianst.github.io/MeshCentral/meshcentral/debugging/#meshagent

**Comment by bravery-only** [comment]
Inside this file in the agent installation path:

![Uploading 202304191528.png…]()

**Comment by trmdi** [comment]
Today I realize that after upgrading my Windows 2 times, 2 duplicated entries were added.

**Comment by silversword411** [comment]
> upgrading my Windows

Technically, windows feature updates are full reinstalls of windows.

Probably need to see what causes mesh to Regen it's system signature (probably part of imaging/cloning reduplication)

**Comment by dinger1986** [comment]
This is fairly normal and needed for resilience when cloning etc @si458 can close

**Comment by trmdi** [comment]
Recently, the bug doesn't seem to be happening anymore.

**Comment by si458** [comment]
This can be fixed by adding `skipmaccheck=1` to your `meshagent.msh` file on the remote agent!

**Comment by trmdi** [comment]
Is there any way to "fix" it from the server side?

**Comment by si458** [comment]
Yes and no
You can add the value into `agentConfig` under `domains` in `config.json` BUT this will only apply to new installs/setups!?
So you have to manually edit the `.msh` file on each machine and add the value in urself afterwards.
I think you would have to open an enhancement issue for us to look into pushing this value into the `.msh` value afterwards
Also u must restart the meshagent after u add the value too
