### ISSUE TITLE
0.4.1-f - Autocompletion is not working

### ISSUE THREAD

**Issue by iamslan** [Ylianst/MeshCentral#505]
Hi @Ylianst 

It's been some versions that autocompletion is failing while trying to add user rights to a group.

Here is the error log:
Uncaught TypeError: Cannot read property 'length' of null
    at p20validateAddMeshUserDialog ((index):7179)
    at HTMLInputElement.onkeyup (VM261 :1)

Thanks a lot for this awesome product we use daily with 100+ devices!

Best,
William

**Comment by Ylianst** [comment]
Thanks for the report, I am looking into this now.

**Comment by Ylianst** [comment]
Your right. Will be fixed in MeshCentral v0.4.1-g when published later today.

**Comment by Ylianst** [comment]
MeshCentral v0.4.1-g is now live!

**Comment by iamslan** [comment]
Works perfectly!
