### ISSUE TITLE
Please add Agent Tag in My Devices Settings menu

### ISSUE THREAD

**Issue by siliconhippy** [Ylianst/MeshCentral#5052]
Currently you have to click on a particular device in My Devices to go to the device page and see whether there is an agent tag.

Much more efficient would be to have the Agent Tag(s) listed for each device ( if assigned one) in the My Devices page, via adding the Agent Tag menu to Settings gear icon to tip right corner.

This will save a lot of time with  an increasing number of devices !

Agent Tag is acquired by Meshcentral server from the meshagent.tag file in the meshagent client installed on each device. This agent tag can be input by user via script ( my developer has done already) and of course can be manually edited by admin.

See #5034 .

Edit 3/23/23 Agent Tag official YouTube video.
At 4.55min is the exact feature that by implication of author was planned!
https://m.youtube.com/watch?v=KPMtzzLWoK0&t=297s

**Comment by si458** [comment]
![Screenshot 2023-10-19 230750](https://github.com/Ylianst/MeshCentral/assets/765314/f3310f58-65c5-4b71-b750-c4dc53c3ae81)
is this ok?

**Comment by siliconhippy** [comment]
Simon,

Looks cool.
I know your very small team is busy with this great project so really appreciate 🙏.

I installed my private Meshcentral server in my Lightsail AWS instance (after the public server was taken off line) using the simple instructions on the Meshcentral downloads page.

So how can I now update the server? Or is there a module I can download and install for this feature?

**Comment by si458** [comment]
@siliconhippy the PR hasnt been merged yet, so the feature wont be included until the next update!
but basically, you go into the 'My Server' tab and click 'Check server version'
from there it will tell u what version you are on and if the is any updates, including letting you update 👍

**Comment by siliconhippy** [comment]
Ok. Please see my #1 clarification.
