### ISSUE TITLE
The uninstall script for Linux invites is wrong

### ISSUE THREAD

**Issue by lboclboc** [Ylianst/MeshCentral#5054]
**Describe the bug**
When inviting a Linux user, the page that shows how to uninstall is lacking information. The uninstall command fails.

**To Reproduce**
1. Click on invite
2. Select only Linux invite
3. The link that gets created shows the uninstall command to be (in the end of the text): sudo ./meshinstall.sh uninstall
4. meshinstall.sh then says: URI and/or device group identifier have not been specified, must be passed in as arguments.

**Expected behavior**
The agent should be cleanly uninstalled

**Screenshots**
Error message: URI and/or device group identifier have not been specified, must be passed in as arguments.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: kubernetes
 - Network: LAN
 - Version: 1.1.4
 - Node: v18.14.0

**Client Device (please complete the following information):**
 - Device: 
 - OS: Ubuntu-20.04
 - Network: LAN
 - Browser: Chrome

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu-20.04
 - Network: LAN
 - Current Core Version (if known): Current Core: Nov 21 2022, 26907999

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.xyz-domain",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "agentPortTls": false,
    "_mpsTlsOffload": true,
    "ExactPorts": true,
    "TLSOffload": false,
    "_SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false"
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "NewAccounts": "true",
      "_userNameIsEmail": true,
      "certUrl": "https://true:443"
    }
  }
}
```

**Comment by InnovoDeveloper** [comment]
Has there been any progress on this issue?  I am experiencing the same thing on AWS Linux 2

**Comment by silversword411** [comment]
No, and unless you hire someone to help you there won't be.

https://github.com/Ylianst/MeshCentral/discussions/4795
