### ISSUE TITLE
Remote desktop - Ask permission screen keeps loading

### ISSUE THREAD

**Issue by JoachimVeulemans** [Ylianst/MeshCentral#5056]
**Describe the bug**
Taking remote control of the desktop without permission is working without issues. When an agent requires permission, the permission window keeps loading. Sometimes the popup window at the client stays white, blue, or fully loaded but does not respond to mouse clicks. Sometimes there is no popup at all. I have this issue on multiple W10 & W11 machines. I believe this is a recent bug. I can not find any errors in the Agent log file.

**To Reproduce**
1. Go to a Windows agent with permission from the user required
2. Click on 'Desktop"
3. Click on 'Connect'

**Expected behavior**
The permission screen should be shown correctly and the buttons should be clickable:
![image](https://user-images.githubusercontent.com/32447944/227148459-a54631d5-36ab-417a-8972-734376785c25.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/32447944/227147291-d1960ee8-a76a-47d0-b058-e57a4703e2e7.png)
![image](https://user-images.githubusercontent.com/32447944/227147355-47147acc-7247-4191-bb6a-2ed33884f635.png)
![image](https://user-images.githubusercontent.com/32447944/227147440-51c34070-5c1e-4dca-8fa1-acfceba71cb0.png)
Loading cursor is always present:
![image](https://user-images.githubusercontent.com/32447944/227147763-0b64c4c2-69ab-4c24-a14f-38d682975fa6.png)

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Network: WAN + reverse proxy
 - Version: 1.1.2
 - Node:

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 22H2
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 3593025475

**Your config.json file**
Config from Tactical RMM is used.

**Comment by si458** [comment]
If you haven't changed anything at all and it's been fine for months, then this strikes me as a windows update bug.
Have u done any updates recently? 
Can u uninstall the updates and see if the issue is still there?
Maybe uninstall/reinstall the agent?

**Comment by JoachimVeulemans** [comment]
I have reinstalled the agent. I am still having the same issue.

I have found an agent running Windows 10 21H2. The permission popup is working here and the agent can click accept.
So the problem is introduced in 22H2.

What are the next steps to resolve this problem?

**Comment by si458** [comment]
Have u done any windows updates recently? 
Can u uninstall the updates and see if the issue is still there?
As I'm reading online, the latest march 2023 update is causing a lot of problems

**Comment by JoachimVeulemans** [comment]
I have uninstalled KB5023706 but I am still seeing the same problem, It now works 1 out of 15 times which is not great.

**Comment by JoachimVeulemans** [comment]
Found out why this was happening. When adding an exception to our Sentinel One antivirus, the problem went away. Nothing to do with Mesh Central itself.

Thanks for the help
