### ISSUE TITLE
Port is defaulting to http:82 & https:446

### ISSUE THREAD

**Issue by mrflaunted** [Ylianst/MeshCentral#506]
When I launch meshcentral the port is no longer defaulting to 443, even if i specify that specific port with "--port 443".  Is there something that may have been changed that would force the port to default differently?

The only config i have adjusted is to enable\disable SMTP

https://imgur.com/a/20IFCb8

**Comment by Ylianst** [comment]
Hi. MeshCentral will use the next available port. So, ports 80, 81, 443, 444, 445 are all busy on your computer. It's likely you are running the MeshCentral server multiple time at the same time. You should stop the server and go in processes and remove any running instances.

Hope it helps,
Ylian

**Comment by mrflaunted** [comment]
confirmed fixed, sorry for wasting your time!

**Comment by Ylianst** [comment]
No worries. Thanks for closing.

**Comment by MailYouLater** [comment]
For future reference, if it hadn't been another instance of MeshCentral running on those ports: To find out what is listening on a port, open an administrative command prompt, and execute `netstat -ano | find /I "Listening"`.  You'll get output like this.

      TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       64200
      TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       64200
      TCP    192.168.0.5:8080       0.0.0.0:0              LISTENING       18364
      TCP    127.0.0.1:81           0.0.0.0:0              LISTENING       1012
      TCP    [::]:80                [::]:0                 LISTENING       64200
      TCP    [::]:443               [::]:0                 LISTENING       64200

Find the line(s) where the second column ends with the a colon followed by the port you're looking for (i.e. `:443`) and look at the number at the end of the line. This is the "Process ID".
Open Task manager, switch to the "Details" tab, find the process that corresponds with that Process ID. (You can click the "PID" label at the top to sort by Process ID).  This is the program that's listening on that port.  If you're not sure where it is, you can right-click that process, and click "Open file location" to find it.
