### ISSUE TITLE
Random server disconnects in web and black screen on remote desktop 

### ISSUE THREAD

**Issue by jonny190** [Ylianst/MeshCentral#5060]
**Describe the bug**
Not 100% on the cause but remote desktop connects with black screen and i keet getting the webpage refreshing with "Server disconnected"

**To Reproduce**
1. Go to 'Device'
2. Click on 'Desktop'
3. Click on 'connect'

**Expected behavior**
Connect and show the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/8059327/227721518-385cea11-1993-475e-86fd-f9227f81d986.png)
.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization:  Docker
 - Network: LA & /WAN, behind HA proxy on pfsesne
 - Version: 1.1.4 also tried 1.1.0

**Client Device (please complete the following information):**
 - Device: Desktops
 - OS: Windows
 - Network: Local to Meshcentral and Remote over WAN]
 - Browser: Google Chrome]

**Remote Device (please complete the following information):**
 - Device: Desktops
 - OS: Windows 10 21H2 and 11
 - Network:  Local to Meshcentral and Remote over WAN]
 - Current Core Version (if known):  Nov 19 2022, 143332014

**Additional context**
Was working initially with 2 test devices now I have 10 its stopped 

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.*DOMAINNAMEHERE.TLD",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "SuperSecretPassword",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": "192.168.4.254",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true"
  },
  "domains": {
        "": {
        "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "false",
        "_userNameIsEmail": true,
    "certUrl": "https://192.168.4.254:443"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}

```

**Comment by SomeGuru** [comment]
@jonny190,

In your config.json you show "_minify": true, have you attempted with removal of this setting from the config completely? Also adding these two lines might help your overall blank screens from happening as often. 

```
    "settings": {
        "cleanNpmCacheOnUpdate": true,
        "AllowHighQualityDesktop": true,
        "desktopMultiplex": true,
        "AllowFraming": "false"
    },
    "domains": {
          "": {
                  "_title": "MyServer",
    "_title2": "Servername",
    "NewAccounts": "false",
             "_userNameIsEmail": true,
    "certUrl": "https://192.168.4.254:443"
        }
  },
```
**_Notice_**, I **removed** two things from the config, WebRTC ```settings``` as this can cause browser to handle the display calls. Also the minify ```domains``` as it has been causing a drop in visual display.

I added npmCleanUp for freeing up resources during your updates, and then I added AllowHighQualityDesktop to improve your desktop experience (slight up tick in the requirements from server side, but negligible if you are self hosting on metal).  The last thing I added was desktopMultiplex which will allow more improvements also.

Give these a try and let me know if you see improved results.

-SomeGuru

**Comment by jonny190** [comment]
@SomeGuru ,

Thanks for the reply, I've set the above suggestions, restarted the docker container to apply them but it seems like there has been no change in the way the system is reacting, showing black screens on desktop and the occasional server disconnects on the web UI 

Any further suggestions or traces/logs that could help? 

Thanks,
Jonny

**Comment by SomeGuru** [comment]
After doing above settings, I goto console and dump the agent core and then reapply it with full core afterwards and that helps... I did notice as of two days ago I also am seeing a small up tick in my systems showing black screens also... However I am not sure any code changes have been done by mesh team that would have the effect we are seeing... 

-SomeGuru

**Comment by jonny190** [comment]
Not sure on the commands for that, i can see coredump listed in the wiki but nothing about reapplying, Strange that the server shows "Server has no error log"  makes me wonder if it could be the reverse proxy sat in front of it however it was working initially and no config has changed. 

I have seen the docker maintainer change the latest build and the 1.1.4 build of his container (https://hub.docker.com/r/typhonragewind/meshcentral/tags) however he has not changed the version number in the tag, just updated and re-published under 1.1.4 

Thanks,
Jonny

**Comment by LPJon** [comment]
There have been issues with proxies in the past. You may be simply having issues with websocket connections between your clients and the proxy. However, this can also be related to windows screen switching. Have you tried RDP or terminal or files and checked if they have the same issues?

**Comment by SomeGuru** [comment]
Also remove the WebRTC as that can cause blackscreen on occasion when behind firewalls.

-SomeGuru

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
Try the least official docker image 1.1.20 and report bk is issues still
