### ISSUE TITLE
Agent not connecting with cloudflare

### ISSUE THREAD

**Issue by dherlein** [Ylianst/MeshCentral#5061]
I have MC proxied through cloudflare in Full (Strict) with letsencrypt on the MC Server.

I have set "trustedProxy": "CloudFlare",

When I add "certUrl" : "https://hostname.domain.com:433" to the config and check the server console for "agentissues" I get BadWebCertHash

But if I add "ignoreAgentHashCheck": true, to the config, the agents can connect.

What am I missing that it isn't working with certUrl?

Thanks!!

**Comment by dinger1986** [comment]
You probably need to copy the cert from cloudflare

**Comment by dinger1986** [comment]
You probably need to copy the cert from cloudflare

**Comment by dherlein** [comment]
Isn't that what setting the certUrl is supposed to do? load the cert from that URL?

**Comment by dinger1986** [comment]
Well what cert are you using? Do you have it defined elsewhere?

**Comment by dherlein** [comment]
I'm using lets encrypt for the cert on the MC server but since I'm proxying through CF, the public facing cert is coming from them

So I have Lets encrypt defined and then I have the certurl set to the same domain (which should grab the public facing cert from cloudflare)

**Comment by dinger1986** [comment]
I'm sure you need to remove letsencrypt config.

I haven't done it myself but read something about this before

**Comment by dherlein** [comment]
so if you want to use CF, the backend traffic has to be unencrypted?

Seems like you should be able to put a cert on MC and then use full encryption between CF and the MC server.

maybe I'm misunderstanding something

**Comment by dinger1986** [comment]
Well no!

As you said yourself surely the cert url pulls the cert so why would you also assign another cert?

It's the same as any other proxy. If no one else has replied later on I'll check my configs on another proxy.

**Comment by dherlein** [comment]
I wonder if there's a way to separate the gui from the agent in that case. because all I really need is for the agent to honor the CF cert

**Comment by dherlein** [comment]
so even after removing lets encrypt entirely but leaving the certUrl defined, The agent still cannot connect and fails with BadWebCertHash

**Comment by si458** [comment]
plz can you share your WHOLE `config.json` ? blanking any secret stuff obvs

**Comment by dherlein** [comment]
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "cert": "SUB.DOMAIN.COM",
    "WANonly": true,
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "ExactPorts": true,
    "trustedProxy": "CloudFlare",
    "certUrl": "https://SUB.DOMAIN.COM:443",
    "autoBackup": {
      "backupPath": "/opt/REDACTED",
      "backupIntervalHours": 48,
      "keepLastDaysBackup": 4,
      "zipPassword": "REDACTED",
      "googleDrive": {
         "maxFiles": 14
         }
      }
  },
  "domains": {
    "": {
      "title": "Device Management",
      "TitlePicture": "logo.png",
      "newAccounts": false,
      "userNameIsEmail": true,
      "minify": true,
      "siteStyle": 2,
      "ManageAllDeviceGroups": [ "REDACTED","REDACTED" ],
      "welcomeText": "Please log in to continue",
      "passwordRequirements": {
         "min": 12,
         "upper": 1,
         "lower": 1,
         "numeric": 1,
         "reset": 150,
         "email2factor": false,
         "sms2factor": false,
         "force2factor": true,
         "allowaccountreset": false
      },
      "agentCustomization": {
         "displayName": "Connect",
         "description": "Remote Connection Agent",
         "installText": "Click Connect for 1-time connection or Install for persistent connection",
         "image": "agentlogo.png",
         "fileName": "Connect",
         "foregroundColor": "#FFFFFF",
         "backgroundColor": "#154B75"
      },
      "assistantCustomization": {
         "title": "Remote Assistant",
         "image": "agentlogo.png",
         "fileName": "Assist"
      }
    }
  }
 }

**Comment by si458** [comment]
**please format it on the future for easy readability - jsonformatter.org**
```
{
   "$schema":"https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
   "comment1":"This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
   "comment2":"See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
   "settings":{
      "MongoDb":"mongodb://127.0.0.1:27017/meshcentral",
      "cert":"SUB.DOMAIN.COM",
      "WANonly":true,
      "port":443,
      "_aliasPort":443,
      "redirPort":80,
      "_redirAliasPort":80,
      "ExactPorts":true,
      "trustedProxy":"CloudFlare",
      "certUrl":"https://SUB.DOMAIN.COM:443",
      "autoBackup":{
         "backupPath":"/opt/REDACTED",
         "backupIntervalHours":48,
         "keepLastDaysBackup":4,
         "zipPassword":"REDACTED",
         "googleDrive":{
            "maxFiles":14
         }
      }
   },
   "domains":{
      "":{
         "title":"Device Management",
         "TitlePicture":"logo.png",
         "newAccounts":false,
         "userNameIsEmail":true,
         "minify":true,
         "siteStyle":2,
         "ManageAllDeviceGroups":[
            "REDACTED",
            "REDACTED"
         ],
         "welcomeText":"Please log in to continue",
         "passwordRequirements":{
            "min":12,
            "upper":1,
            "lower":1,
            "numeric":1,
            "reset":150,
            "email2factor":false,
            "sms2factor":false,
            "force2factor":true,
            "allowaccountreset":false
         },
         "agentCustomization":{
            "displayName":"Connect",
            "description":"Remote Connection Agent",
            "installText":"Click Connect for 1-time connection or Install for persistent connection",
            "image":"agentlogo.png",
            "fileName":"Connect",
            "foregroundColor":"#FFFFFF",
            "backgroundColor":"#154B75"
         },
         "assistantCustomization":{
            "title":"Remote Assistant",
            "image":"agentlogo.png",
            "fileName":"Assist"
         }
      }
   }
}
```

**Comment by si458** [comment]
have you tried this - https://github.com/Ylianst/MeshCentral/issues/4411#issuecomment-1220398462 ?

**Comment by dherlein** [comment]
yeah. you'll see the trustedproxy in the config.
I realized I put the certurl under settings when it should have been under domains so I moved that.
I then tried it with and without the 443 again and the same issue and symptoms are still there

**Comment by si458** [comment]
only other thing i can suggest is try removing `"WANonly":true` and restart meshcentral and see if it works?
i dont use cloudflare sadly so im outta suggestions

**Comment by dherlein** [comment]
yeah unfortunately its a cloud install so WANonly has to be there.

Thanks for the effort!

**Comment by si458** [comment]
> yeah unfortunately its a cloud install so WANonly has to be there.

the setting wont have any effect in the cloud, i use mine in "the cloud" but i use direct access rather than cloudflare

**Comment by dherlein** [comment]
I just tried removing it and no change

**Comment by dherlein** [comment]
After much headbanging, I figured it out.

the hostname of the os was the same as the fqdn that I was hosting MC at and the VPS did not handle the hairpin properly so certurl was not retrieving the certificate.

Thanks all for the help
