### ISSUE TITLE
Need help to migrate database to PostgreSQL

### ISSUE THREAD

**Issue by nodminger** [Ylianst/MeshCentral#5063]
Hi, I want to migrate from default(NeDB) to PostgreSQL? I used the following commands
**node node_modules/meshcentral --dbexport** and then **node node_modules/meshcentral --dbimport**
But nothing was imported in my database. I think I am missing something. 

**This is my config file.**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "localhost",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "properties":{
        "postgres": {
          "properties": {
            "host": "localhost",
            "user": "postgres",
            "port": 5432,
            "password": "pass",
            "database": "meshcentral"
          }
        }
     }
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
	  "newAccounts": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

Output for import and export command
```
vboxuser@Ubuntu:~/Desktop/mc$ sudo node node_modules/meshcentral --dbexport
Exported 36 objects(s) to /home/vboxuser/Desktop/mc/meshcentral-data/meshcentral.db.json.
vboxuser@Ubuntu:~/Desktop/mc$ sudo node node_modules/meshcentral --dbimport
Imported 36 objects(s) from /home/vboxuser/Desktop/mc/meshcentral-data/meshcentral.db.json.
vboxuser@Ubuntu:~/Desktop/mc$ 
```

**Comment by dinger1986** [comment]
Is your database created? Does the user have full permission on it? Is the database called "meshcentral"?

**Comment by nzalev** [comment]
Just confirming,

When you perform the db export, is postgres set in your config? The export and import commands use the config.json file, the same as the server does.

You should double check that postgres is not in your config when you export the database objects - ensure you are exporting from nedb and not postgres. (ie, remove postgres before exporting)

Then before you import the db json file, put postgres back into the config.json file.

**Comment by nodminger** [comment]
> Is your database created? Does the user have full permission on it? Is the database called "meshcentral"?

Yes, the user has all privileges. Initially, I manually created the 'meshcentral' database and attempted to import, but it did not work. I then tried importing again after adding **database: meshcentral** to the config.json file, but it still did not work.

**Comment by nodminger** [comment]
> Just confirming,
> 
> When you perform the db export, is postgres set in your config? The export and import commands use the config.json file, the same as the server does.
> 
> You should double check that postgres is not in your config when you export the database objects - ensure you are exporting from nedb and not postgres. (ie, remove postgres before exporting)
> 
> Then before you import the db json file, put postgres back into the config.json file.

No, Postgres was not in the config.json when I tried to export. After exporting from NeDB I checked the JSON file. It had all the data. Then I added Postgres to the config.json and tried to import. I am not getting any error but still all the tables are missing.

Default config.json file
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "localhost",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
	  "newAccounts": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```
Exporting db from NeDB
![image](https://user-images.githubusercontent.com/128209987/228405627-1012a43b-47d6-4193-9802-d14ec586ddfe.png)

config.json after adding postgres
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "localhost",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "properties":{
        "postgres": {
          "properties": {
            "host": "localhost",
            "user": "postgres",
            "port": 5432,
            "password": "pass",
            "database": "meshcentral"
          }
        }
     }
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
	  "newAccounts": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

Importing db to Postgres
![image](https://user-images.githubusercontent.com/128209987/228405927-4755d84c-7914-4821-acec-4a2531ce1829.png)

Meshcentral Database
![image](https://user-images.githubusercontent.com/128209987/228406051-a20e8158-0094-47d2-aaf3-0e51345edf63.png)

**Comment by nzalev** [comment]
I read your config.json more closely.

I assume perhaps your have taken this out of the config schema? `postgres` should not be embedded within `properties`.  Similarly, the properties (keys) of postgres should not be inside a property named `properties`.

```json
  "settings": {
    "cert": "localhost",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 444,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "postgres": {
      "host": "localhost",
      "user": "postgres",
      "port": 5432,
      "password": "pass"
    }
  },
```

**Comment by nodminger** [comment]
I'm sorry for the silly error. Now database has been migrated and meshcentral is working fine but I got this error while migrating to Postgres.
![image](https://user-images.githubusercontent.com/128209987/228410093-f13d4021-3da8-4aca-8172-67d1a0ffd45a.png)

**Comment by nzalev** [comment]
This error will get produced if the DB has been partially created (db exists, but no tables)

Technically a minor bug, but should not appear again now that the tables have been created.

```js
            Datastore.connect();
            if (err == null) {
                // Create the tables and indexes
                postgreSqlCreateTables(func);
            } else {
                // Database already existed, perform a test query to see if the main table is present
                sqlDbQuery('SELECT doc FROM main WHERE id = $1', ['DatabaseIdentifier'], function (err, docs) {
                    // If not present, create the tables and indexes
                    if (err == null) { setupFunctions(func); } else { postgreSqlCreateTables(func); } 
                });
            }
```

**Comment by nodminger** [comment]
Thank you very much for your response. I now understand the process. Is there any documentation available on the database structure to help me better understand them? I have looked through the [Meshcentral documentation](https://ylianst.github.io/MeshCentral/design/), but I could not find anything related to the structure of the database.

**Comment by nzalev** [comment]
The internal structure of the database is not documented.

The MySQL/MariaDB/Postgres schemas are very simple though, because they are adapted from the object store designs used with NeDB / MongoDB. 

The main table contains a variety of different entries comprised of a unique ID, a type identifier, and a json document. It is not a relational design.

**Comment by nodminger** [comment]
Alright, I will look into it. Thank you very much for your assistance.
