### ISSUE TITLE
Add option for custom OIDC image

### ISSUE THREAD

**Issue by YodaDaCoda** [Ylianst/MeshCentral#5066]
**Is your feature request related to a problem? Please describe.**
I have set up OIDC with Authelia as the provider, and _love_ the functionality. However, I would like the ability to replace the OpenID Connect logo with Authelia's logo.

**Describe the solution you'd like**
I'd like the ability to specify a path to a custom logo image under the `oidc` key in the config, and have Meshcentral use that image in place of the OpenID Connect logo on the sign-in page.

**Describe alternatives you've considered**
I don't think there really are alternatives per se - other than live with the OIDC logo.

**Additional context**

![image](https://user-images.githubusercontent.com/365349/228694601-02d75ef9-66a5-47e1-a1e7-18d859d191d4.png)

**Comment by mstrhakr** [comment]
You can do this now I'm pretty sure, just replace the oidc32.png under MeshCentral\public\images\login with whatever image you would prefer.

**Comment by si458** [comment]
@mstrhakr a better way is to create a folder `meshcentral-web` next to `meshcentral-data` then inside create `public` then inside that create `images` then inside that create `login`

Then inside `login` create ur image `oidc32.png` then restart meshcentral

The `meshcentral-web\public` folder will overwrite anything inside the `public` folder but also last over upgrades!

**Comment by mstrhakr** [comment]
Thanks, I knew there was a right way to do that.
