### ISSUE TITLE
Meshcentral Autohide privacy bar

### ISSUE THREAD

**Issue by jsinoy** [Ylianst/MeshCentral#5069]
Hello guys, how can i set the privacy toolbar to autohide as default ?  Also is there a way a notification to the user when the remote technician is already disconnected from the remote session ?  As of now we are hesitant to display the privacy bar as it will block the url page when navigating to a browser . IF theres a way we ca auto hide this by default or set a setting that would be very helpful

Cheers,

**Comment by jsinoy** [comment]
I have tried to modify the meshcore.js . Is this correct ? I seems not working, sorry i am not to familiar with programming

`                            switch (args['_'][0].toUpperCase()) {
                                case 'PINNED':
                                    require('notifybar-desktop').DefaultPinned = false;
                                    response = "privacybar default pinned state is: PINNED";
                                    break;
                                case 'UNPINNED':
                                    require('notifybar-desktop').DefaultPinned = true;
                                    response = "privacybar default pinned state is: UNPINNED";
                                    break;
                                default:
                                    response = "INVALID parameter: " + args['_'][0].toUpperCase();
                                    break;
`

**Comment by jsinoy** [comment]
switch (args['_'][0].toUpperCase()) {
                                case 'PINNED':
                                    require('notifybar-desktop').DefaultPinned = false;
                                    response = "privacybar default pinned state is: PINNED";
                                    break;
                                case 'UNPINNED':
                                    require('notifybar-desktop').DefaultPinned = true;
                                    response = "privacybar default pinned state is: UNPINNED";
                                    break;
                                default:
                                    response = "INVALID parameter: " + args['_'][0].toUpperCase();
                                    break;

**Comment by si458** [comment]
By default, there should be no privacy bar shown?

It's only visible if you right-click on the connect button and select privacy bar

OR

You select a group of computers (or single computer) and enable the privacy bar to be shown

You can slide the privacy bar along out the way, but you can't hide it after it's shown sadly

What is your current `config.json` hide secret data obvs

**Comment by dinger1986** [comment]
Just disable it in your user settings.

To to account then notifications

**Comment by jsinoy** [comment]
I have set this to default so that the user would know there is a remote session, If i disable the "show connection toolbar" , the user would now know if im still connected . Or any possible alternative that would notify the user if the remote technician is disconnected ?

![image](https://user-images.githubusercontent.com/109936671/229089219-9edbe12b-4f15-492a-85df-105180d51aea.png)

**Comment by dinger1986** [comment]
No, there's no alert to say someone's disconnected.

You can unpin the bar at the top.

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
you can click the PIN on the title bar to hide it and hover to show it again
BUT 
you can also go into the `Console` tab before you connect and run `privacybar` and it will reply what the default is,
either pinned or unpinned
then you can change the default to what you prefer `privacybar pinned` or `privacybar unpinned`
