### ISSUE TITLE
Ubuntu 18 agent machine showing disconnected after few time

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#507]
I have installed the mesh agent on Ubuntu 18. After few time (hour/minute) it started showing offline and I am not able to take desktop on remote. When we restart the machine physically Its again connected for a while. But same thing happen again and again..  This issue also prominent on that machine where network is slow each ping is taking >1sec

**Comment by Ylianst** [comment]
Can you look in the /usr/local/mesh folder and see if a "meshagent.log" file is present? If so, can you send it over. Thanks.

**Comment by krayon007** [comment]
What's the network topology? Is there a proxy?

**Comment by krayon007** [comment]
If you modify the .msh file in the /usr/local/mesh folder, and add the following line:
controlChannelDebug=1

This will enable connection logging in the agent, so that it will write a log for anything connection related...

You'll need to restart the agent for the changes to take effect, which on Ubuntu 18, is:
sudo systemctl restart meshagent

**Comment by AnjaniKumar15** [comment]
[meshagent .log](https://github.com/Ylianst/MeshCentral/files/3661064/meshagent.log)
I have restarted the Ubuntu 18 agent machine and quickly change in .msh and added controlChannelDebug=1 flag which started generating the logs in log file. After few minutes it again went offline then I have restarted again and downloaded the log file.
As I have read the log file I observed that the MeshAgent tried only 2 times to connect with MeshCentral server and after that it went offline. When I have restarted again then Its tried to reconnect and then connection attempt successful. Kindly check the log and suggest how to rectify this issue. 
***This machine is connected with unstable internet connection (I am using mobile SIM network which is not delivering stable connection in that area where agent machine installed)**

**Comment by AnjaniKumar15** [comment]
I think its not resolved yet. For Slow connection Meshagent going offline repeatedly. Is there any way to increase the Meshagent polling attempt?

**Comment by AnjaniKumar15** [comment]
I have installed teamviewer on remote machines and I am able to take remote using TeamViewer. But on MeshCentral its showing offline. When I restart the MeshAgent service then again Its showing online for few moment after that it will again goes offline on MeshCentral.

**Comment by dinger1986** [comment]
really old and old distro can close @si458
