### ISSUE TITLE
Need help regarding terminal and file system protocol

### ISSUE THREAD

**Issue by nodminger** [Ylianst/MeshCentral#5071]
Hello, I've been using Meshcentral for some time now and I'm curious about the protocols it uses for Terminal access and accessing the file system. I tried to look it up online and found two different pieces of information: one source says Meshcentral uses SSH, while another suggests it uses WebRTC. Could you please clarify which protocol Meshcentral actually uses for these purposes?

**Comment by nodminger** [comment]
Thank you very much for the thorough explanation. I now understand that WebSocket is primarily utilized for establishing connections between server-agent and browser-agent through the server. WebSocket is a communication protocol, right? Also, in order to achieve Terminal access, File System access, and Direct Remote Monitoring (not Web-RDP or Web-VNC), is there a specific protocol or technology that needs to be used along with WebSocket?

**Comment by nzalev** [comment]
Websocket is a protocol. MeshCentral implements a custom protocol for communication between the server and the agent that is sent over WebSocket (and also between browser and server).

The agent itself does almost all of the heavily lifting in terms of terminal, file system, and remote control. The protocol is mainly to exchange commands/instructions, deliver inputs, and carry data.

**Comment by nodminger** [comment]
I watched a YouTube video where it was mentioned that WebRTC is disabled by default. If I enable WebRTC, communication between the agent and the browser will change from WebSocket to WebRTC. This means that operations such as accessing the terminal and remote desktop can be done through both WebSocket and WebRTC. Am I correct?

**Comment by nzalev** [comment]
WebRTC support is disabled by default. It has to be enabled in the config.json file.

The WebRTC implementation is custom built in the agent. It negotiates the WebRTC channel over websockets, using the MeshCentral server as a relay, eliminating the need for STUN/TURN.

**Comment by nodminger** [comment]
Thank you for the information. I now understand how it works.
