### ISSUE TITLE
 meshcommander remote desktop black screen 

### ISSUE THREAD

**Issue by beau76** [Ylianst/MeshCentral#5074]
hi I am using meshcommander0.96  on window 11
The remote pc is amt vpro hp 800 g2 i7-6700 windows 10 pro no monitor 
 if I click remote desktop I just get a black screen any ideas?

**Comment by silversword411** [comment]
Video cards without something connected don't generate a display that can be captured by mesh. Laptop, screen needs to be open (or disable turning monitor off when closing lid. 
On desktop, use one of these https://www.amazon.com/Headless-Emulator-Headless-1920x1080-Generation-60Hz%EF%BC%89-3Pack/dp/B06XSY9THQ

**Comment by beau76** [comment]
Hi silversword411 that works great for os desktops is there a trick to see the bios screen?

> Video cards without something connected don't generate a display that can be captured by mesh. Laptop, screen needs to be open (or disable turning monitor off when closing lid). On desktop, use one of these https://www.amazon.com/Headless-Emulator-Headless-1920x1080-Generation-60Hz%EF%BC%89-3Pack/dp/B06XSY9THQ
