### ISSUE TITLE
Does Meshcentral work with DietPi x86 and ARM?

### ISSUE THREAD

**Issue by siliconhippy** [Ylianst/MeshCentral#5077]
The title is self explanatory!

1. So does anyone know if the Debian distro https://dietpi.com/
 works with Meshcentral as do other OSes?

DietPi is for both x86 and for select ARM devices, and uses the armbian.com kernels for many these ARM devices listed prominently on their site ( very friendly to navigate.)

3. If yes, any experiences you might want to describe? 🙂

**Comment by si458** [comment]
the meshagent has arm64 versions and arm32 versions, so should work no problems
as for x86 thats just a standard linux install

**Comment by siliconhippy** [comment]
Yes meshagent works on DietPi x86_64 ! 🙂
