### ISSUE TITLE
WelcomePicture tag not working

### ISSUE THREAD

**Issue by penguinthingie** [Ylianst/MeshCentral#508]
Hi Guys,

It seems somewhere within the 4.0 chain, the  "WelcomePicture" variable found on the configuration file, stopped passing on specified .jpg file to be served in place of the default "Welcome.jpg" picture. Has something changed on where this should be placed or is it a bug?

Thanks!

**Comment by Ylianst** [comment]
I will look into this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-i with a fix for this. Let me know if it works for you.

**Comment by penguinthingie** [comment]
Hi @Ylianst , updated it just now under 4.1-m and the issue still persists. Incase i am doing something wrong, I have the variable value set to a filename which is in the same folder as "meshcentral-data", it was working before. Please let me know if you need any additional specific information. Thanks!

**Comment by Ylianst** [comment]
Just to make sure, I have something like this as my config.json:

```
{
  "settings": {
    "Port": 4430,
    "RedirPort": 800
  },
  "domains": {
    "": {
      "title": "MyServer",
      "title2": "Test",
      "welcomePicture": "mainwelcome.jpg",
    }
  }
}
```

Then I have a "mainwelcome.jpg" file in the "meshcentral-data" folder. Make sure the file capitalization is correct if you are on a Linux server. Can you confirm everything looks right? It works on my server, so, not sure.

**Comment by penguinthingie** [comment]
Weird.. not sure if it was a file perms issue, everything looked fine like you have on yours, the only thing i changed is modifying the file perms from 644 to 664 and restarted the service on a new browser, and its all working fine now.. i don't see why "owner" perm would fix it but its possible it was the cached issue as well.. so please consider this resolved! Thank you for your help!

**Comment by Ylianst** [comment]
HTTP caching for static documents is currently set to 1 hour. So, that was probably the issue. Forcing a browser refresh would have solve the issue (if caching was the problem).
