### ISSUE TITLE
MeshCommander cannot connect to AMT

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [Ylianst/MeshCentral#5081]
**Describe your issue**
Hello,

I have configured MEBx via manual setup and enabled AMT.

So, I know the user and the password.

I can connect to the WebUI via https://ip_address:16993

MeshCommander can detect the device via scan, but when I try to connect, the connection timesout.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Microsoft Windows Server 2019 Standard
 - Virtualization: None
 - Network: Wired LAN
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: Dell Precision 3660
 - OS: Microsoft Windows Pro 10
 - Network: Wired LAN
 - Browser: Chrome
 - MeshCentralRouter Version: N/A trying to connect to on-board AMT

**Comment by ZENAdmin-Ops** [comment]
Hello,

Just wanted to add some additional info.

I note in your MeshCommander tutorial video, that when configuring TLS, the device starts out in non-TLS mode before configuring the certificate and enabling TLS.

In trying to troubleshoot this system, I downloaded some Intel tool onto the PC that said that AMT was already in TLS-mode (as shipped). I'm not sure if this might be the reason that MeshCommander is unable to connect.

**Comment by si458** [comment]
Please can this issue be added in the correct repo as its nothing to do with meshcentral

https://github.com/Ylianst/MeshCommander

**Comment by ZENAdmin-Ops** [comment]
Sorry, my bad.

If this is a hassle to move, I'll close and create a new question in the repo

**Comment by ZENAdmin-Ops** [comment]
Raised in the wrong area.
