### ISSUE TITLE
I have added the session recording feature and I would like to make notes on my recordings. can someone help???

### ISSUE THREAD

**Issue by AbdulAlfallah** [Ylianst/MeshCentral#5082]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SomeGuru** [comment]
Is this on public server like MeshCentral.com or private server? Details are missing to best know what impact should be.

-SomeGuru

**Comment by si458** [comment]
no this feature isnt possible,
you cannot apply notes to a session recording

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
this feature wont be implemented, but a work around is to do your session and record it,
then you can use the 'log event' button to make ur notes and it will save in the database as an event for you to look back on
