### ISSUE TITLE
SSH Connect accees to devices via meshctrl.js 

### ISSUE THREAD

**Issue by KDima23** [Ylianst/MeshCentral#5083]
Currently only way is to use Mesh Central graphical interface SSH Connect.
Is it possible to establish ssh session with the device thru meshctrl.js  with the agent?

**Comment by SomeGuru** [comment]
Try MeshRouter for the ssh tunnel call... 

-SomeGuru

**Comment by si458** [comment]
it currently isnt possible to ssh with meshctrl.js as the idea of meshctrl.js is to control meshcentral and not the remote device
