### ISSUE TITLE
Amazon Linux 2 quick start installation scripts not available; connection to info.meshcentral.com times out

### ISSUE THREAD

**Issue by dga71** [Ylianst/MeshCentral#5085]
Connection to info.meshcentral.com times out - therefore mc-aws-linux2.sh and mc-aws-linux2-mongo.sh are not available.

https://meshcentral-community.com/doku.php?id=howto:installation:quickstart is useless

**Comment by si458** [comment]
meshcentral-community.com is a community website and nothing to do with the repo
you need to speak to them about updating/changing links
the `info.meshcentral.com` goes to AWS where as `meshcentral.com` goes to Azure

**Comment by Ylianst** [comment]
Ok, I just enabled the following links:

[http://meshcentral.com/info/scripts/mc-aws-linux2.sh](http://meshcentral.com/info/scripts/mc-aws-linux2.sh)
[http://meshcentral.com/info/scripts/mc-aws-linux2-mongo.sh](http://meshcentral.com/info/scripts/mc-aws-linux2-mongo.sh)
[http://meshcentral.com/info/scripts/mc-azure-ubuntu1804.sh](http://meshcentral.com/info/scripts/mc-azure-ubuntu1804.sh)
[http://meshcentral.com/info/tools/MeshCentralInstaller.exe](http://meshcentral.com/info/tools/MeshCentralInstaller.exe)

I tried to edit the community page, but got an error back. If someone can fix the links, that would be great.

**Comment by X1Aaron** [comment]
@Ylianst links are broken again 😞

**Comment by si458** [comment]
> @Ylianst links are broken again 😞

the website got shutdown and was moved to github - https://github.com/Ylianst/MeshCentral/discussions/5290
however the is loads of assets missing! so if you have copies of them anywhere,
please upload them and we can re-upload them to github repo! - https://github.com/Ylianst/MeshCentralSite

**Comment by X1Aaron** [comment]
> EDIT: also what links are you refering too?

http://info.meshcentral.com/scripts/mc-aws-linux2.sh

**Comment by si458** [comment]
> http://meshcentral.com/info/scripts/mc-aws-linux2.sh

oops, it should be http://meshcentral.com/scripts/mc-aws-linux2.sh

**Comment by X1Aaron** [comment]
Thank you!!

**Comment by si458** [comment]
sadly the meshcentral-community.com website isnt ours, its some random persons and nobody can get access to edit the website

**Comment by X1Aaron** [comment]
Right I understand that. The always get links from meshcentral.com for security.

**Comment by si458** [comment]
links have been updated at ylianst.github.io/meshCentral/ and meshcentral.com
