### ISSUE TITLE
[ Feature Request ] - [ Windows ] - Skip the user consent desktop prompt if no user is logged into the PC

### ISSUE THREAD

**Issue by vagner-dias** [Ylianst/MeshCentral#5086]
**Is your feature request related to a problem? Please describe.**
When the desktop prompt is set but no user is logged on the windows machine, there is no way to accept the prompt.

**Describe the solution you'd like**
Skip the prompt on the client side if no one is logged

**Describe alternatives you've considered**
Ocasionally when there is no one logged in the target pc, I have to disable the user consent prompt at the group level so that I can connect to it.

**Comment by si458** [comment]
Right click on the connect button in the desktop tab
You get more options
Hope this helps!

**Comment by vagner-dias** [comment]
> Right click on the connect button in the desktop tab You get more options Hope this helps!

Oh, Great!

I wasn't aware of this feature!

Thanks!

**Comment by si458** [comment]
General rule, right click everything... the is always hidden menus/buttons :)

**Comment by knkumar93** [comment]
Any way to disable this right click behavior? This is technically overriding the configured consent behavior.
