### ISSUE TITLE
Optional notification bar on the remote device when a remote sessions is active.

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#509]
Ylianst, good afternoon!

I have raised some topics I would like to suggest to know if it is possible to implement, can you help me?

Look:
-> Remote user should know if technician is still connected or not, and which technician or which technicians are connected.

My suggestion would be something similar to the print below visible to the user, this flag highlighted in red

![image_mY](https://user-images.githubusercontent.com/55212206/65714798-32854880-e072-11e9-9a0c-a01c61356e42.png)

-> Chat interaction must notify the user.
In this case, every time either the technician sends a chat message to the user or the user sends the technician, displaying some kind of notification, preferably displaying a browser notification to the user, if it already exists could explain how I enable?

-> Option for the user to disconnect the technician.
Allow remote user to override remote technician access.

Can you help me with the above topics?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.1-j with browser notification support in MeshMessenger. Let me know if that works.

![MC2-MessengerNotify](https://user-images.githubusercontent.com/1319013/65721481-00b6b680-e05f-11e9-96c6-1c40639cbb89.png)

**Comment by geanferrani123** [comment]
Ok, I'll test, what about the other topics?

**Comment by Ylianst** [comment]
The two other ones are MeshAgent features. Bryan will have to work on these.

**Comment by geanferrani123** [comment]
Perfect, I'll test this one that you returned to me. About others, do you think you will be able to implement these suggestions?

**Comment by geanferrani123** [comment]
Ylianst, sorry, i don't enabled, can you help me?

**Comment by geanferrani123** [comment]
I couldn't enable it, can you help me?

**Comment by MailYouLater** [comment]
Regarding the request for the remote computer to display that someone's connected. I agree this should be an available option, it would be nice if it was still an option to not have it display.

**Comment by Ylianst** [comment]
Yes, this will be an option in the "User Consent" section of a device group once it's implemented. This is not an easy thing to implement, especially on Windows/Linux/MacOS/FreeBSD. Bryan will need a bunch of time.

**Comment by geanferrani123** [comment]
Ylianst, about the information that the technician or technicians are connected, to be something quick would suddenly have to put in 1 minute that the technician or technicians are connected?

In case, this notification here, see below:

![image](https://user-images.githubusercontent.com/55212206/65781258-afbbc680-e121-11e9-8391-50df10bb2d6a.png)

Would you also like to put this same kind of notification to be displayed when the technician leaves the remote connection? It displays the notification for when it connects but does not display for when it disconnects.

**Comment by MailYouLater** [comment]
@geanferrani123: I don't like the idea of having a repeating balloon / popup notification, that would get really annoying really quick, but a constant display similar to the image in the first post would be great, as long as it's optional.

**Comment by geanferrani123** [comment]
I see, it really would be great, but at least as long as you implement this first print function, would you be able to customize it this way or send me a file with this function and guide me where I insert it until you release this enhancement? Still on the first print, did you put a method for the user to bring down the technician's access along with the image I demonstrated in the first print?

**Comment by MailYouLater** [comment]
As Ylianst said earlier:
> The two other ones are MeshAgent features. Bryan will have to work on these.

So any ETA would probably come from Bryan (a.k.a. @krayon007). But it might be a while, cause I haven't seen any commits that look related to this in the [Mesh Agent repo](/Ylianst/MeshAgent) yet.

**Comment by krayon007** [comment]
I'm working on it now. I ran into a snafoo with the windows message pump for the toolbar I created, so I gotta fix that first. But I think I know the issue, so I just have to fix the plumbing.

**Comment by PathfinderNetworks** [comment]
Please make sure that these notification features purely optional.  Many of us do not want nor need that to be showing up for specific reasons.  Some of my customers monitor their employees desktop usage at random times and don't want the employees knowing it- for example.  Ideally this would all be something that can be enabled (or disabled) system wide- such as in config.json or something like that.

**Comment by Ylianst** [comment]
@PathfinderNetworks  Yes, it will be completely optional. It will be a new option in the device group user consent options along with a setting in config.json to require it domain-wide if you want this.

**Comment by geanferrani123** [comment]
> @ PathfinderNetworks Sim, será completamente opcional. Será uma nova opção nas opções de consentimento do usuário do grupo de dispositivos, juntamente com uma configuração no config.json, para exigi-la em todo o domínio, se você desejar.

It would be wonderful if it were that way, so I will be waiting for bryan's return with the improvement.

**Comment by geanferrani123** [comment]
> @ PathfinderNetworks Sim, será completamente opcional. Será uma nova opção nas opções de consentimento do usuário do grupo de dispositivos, juntamente com uma configuração no config.json, para exigi-la em todo o domínio, se você desejar.

It would be wonderful if this customization is optional, so I will be waiting for the return of bryan with the improvement.

**Comment by geanferrani123** [comment]
Right, I'll be waiting

**Comment by geanferrani123** [comment]
@krayon007 are you getting good results?

**Comment by penguinthingie** [comment]
> @krayon007 are you getting good results?

@geanferrani123 Maybe it's just me but you seem to be requesting for many changes to be made like you are paying for this open source project? Please respect the hard work these guys are doing and hold your horses a bit before requesting results right away. 

Apologies for the rudeness.

**Comment by geanferrani123** [comment]
@penguinthingie Dear colleague, by no means, I don't want to give this impression, I just asked with curiosity, its placement was totally unnecessary. To those responsible, if I passed this feeling, I am sorry for that, this was not and will not be my intention.
