### ISSUE TITLE
OTP secret should be able to be highlighted for copying to the clipboard

### ISSUE THREAD

**Issue by christianschneider89** [Ylianst/MeshCentral#5091]
It would be nice if we could highlight the secret for OTP in this message for copying into the clipboard:
![image](https://user-images.githubusercontent.com/15085873/232813298-f8488f0c-70d8-44c0-bd6f-04f6fdcbaa86.png)

At the moment we cannot highlight the secret and cannot copy it into the clipboard.
The background: When I set up OTP in KeePassXC for example, there is a field where I can insert/paste the secret.

**Comment by si458** [comment]
done a work around 👍 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/047e9062-9787-4023-9985-ad58e7c918cc)
