### ISSUE TITLE
Fail to install agent in w7 64bits

### ISSUE THREAD

**Issue by pieer3991** [Ylianst/MeshCentral#5094]
Al instalar en windows 7 de 64bits arroja el siguiente error:

![image](https://user-images.githubusercontent.com/74231602/233433950-4abdb81b-76ed-4ca1-be8b-c0348d990467.png)

Firma con problemas:
  Nombre del evento de problema:	BEX64
  Nombre de la aplicación:	meshagent64-AGENCIAGUADALUPESUR.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	639396c1
  Nombre del módulo con errores:	StackHash_1dc2
  Versión del módulo con errores:	0.0.0.0
  Marca de tiempo del módulo con errores:	00000000
  Desplazamiento de excepción:	0000000000000000
  Código de excepción:	c0000005
  Datos de excepción:	0000000000000008
  Versión del sistema operativo:	6.1.7601.2.1.0.256.48
  Id. de configuración regional:	10250
  Información adicional 1:	1dc2
  Información adicional 2:	1dc22fb1de37d348f27e54dbb5278e7d
  Información adicional 3:	cbc5
  Información adicional 4:	cbc5ec6970b2af35927ad67117ca57e2

**Comment by si458** [comment]
ENGLISH:
```
When installing on Windows 7 64-bit, it throws the following error: 

Firm with problems:
Problem Event Name: BEX64
Application name: meshagent64-AGENCIAGUADALUPESUR.exe
App version: 0.0.0.0
Application timestamp: 639396c1
Faulting module name: StackHash_1dc2
Faulting module version: 0.0.0.0
Failed module timestamp: 00000000
Exception Offset: 0000000000000000
Exception Code: c0000005
Exception data: 0000000000000008
OS version: 6.1.7601.2.1.0.256.48
Locale ID: 10250
Additional info 1: 1dc2
Additional Information 2: 1dc22fb1de37d348f27e54dbb5278e7d
Additional info 3: cbc5
Additional Information 4: cbc5ec6970b2af35927ad67117ca57e2 
```

**Comment by si458** [comment]
is the computer up to date with all its drivers and software?
does it have service pack 1 installed?

**Comment by pieer3991** [comment]
Yes, have SP1

**Comment by pieer3991** [comment]
Yes, have SP1

**Comment by pieer3991** [comment]
In w7 32bits dont have problem.

**Comment by pieer3991** [comment]
UnhandledExceptionEventSink: System.MissingMethodException: Method not found: 'System.Security.Cryptography.RSA System.Security.Cryptography.RSA.Create(Int32)'.
   at MeshAssistant.MeshCentralAgent.LoadAgentCertificate()
   at MeshAssistant.MeshCentralAgent..ctor(MainForm parent, String mshstr, String softwareName, String selfExecutableHashHex, Boolean debug)
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)

**Comment by pieer3991** [comment]
> is the computer up to date with all its drivers and software? does it have service pack 1 installed?

Yes. look this:

**Comment by VINISHVV** [comment]
@pieer3991
We are also face this issues. I think its related to the. Net framework version issue ( Dome time we need to install both 86&64 bit framework ).

You can skip this dependency and install the agent using below command.

Open cmd
Goto the meshagent available /downloaded folder
meshagent64.exe --fullinstall

**Comment by dinger1986** [comment]
Seems there's a fix so can close @si458

**Comment by ahdung** [comment]
Same issue for `meshagent32-wan.exe`. I can use parameter `-fullinstall` to complete installation successfully, and work, but still can't run it by shell execution way like double click.

**Comment by si458** [comment]
closing as workaround for older OS, if you cant run the installer and get the GUI, simply use the command line
`meshagent-mygroup.exe -fullinstall`
