### ISSUE TITLE
Amazon Linux quick install fails to start

### ISSUE THREAD

**Issue by PipingRockIT-cj** [Ylianst/MeshCentral#5096]
I have a new EC2 instance running Amazon Linux 2 and ran the quick install script, however it is failing to start with a 203 status. I checked the service and it was configured to run from /home/ec2-user, which was not where the program installed. It ended up installing under /root. I updated the service to the correct path but it still fails to start with the same error. Any ideas?

**Comment by SomeGuru** [comment]
Rebuild instance again, then run Install without root access and see what results from that... seems to happen a good mount of times its ran as sudo scriptname and it then runs in root not user space. 

-SomeGuru

**Comment by dinger1986** [comment]
@si458 looks to be resolved

**Comment by si458** [comment]
The ec2 script has been updated on the new docs, so plz try the script if needs be
