### ISSUE TITLE
Obtain node id prior to install

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#5098]
Is it possible to obtain the node ID prior to install? possibly when creating the installer using this command:

`NODE meshctrl.js AgentDownload   --type 4 `

**Comment by si458** [comment]
No I believe

The nodeid is generated as part of the install process and when the device first registers with the server

**Comment by si458** [comment]
I'm not 100% sure, you would have to try it and see what happens
Maybe try blocking the computer from accessing the network and run it?

**Comment by dinger1986** [comment]
@si458 we can test and document?

**Comment by si458** [comment]
the command `meshagent --nodeid` will return the nodeid it used to assign with the server, it is hex encoded
look at my code example for help nodeid
