### ISSUE TITLE
The problem of installing Mesh Central in Windows Server 2016

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#5100]
I had Mesh Central installed in Windows Server 2016. I wanted to update to version 1.1.5, but it was not updated. I had to reinstall Windows Server. Now these errors are coming. Can anyone help?
![202304220206](https://user-images.githubusercontent.com/42680639/233775661-43a69f64-28bb-4a9c-9e26-1ebc67666627.png)
![202304221245](https://user-images.githubusercontent.com/42680639/233775669-f9215d51-634e-47f8-8bf5-a1f8d85e929d.png)

**Comment by SomeGuru** [comment]
Honestly looks like user permission issue on Windows Server 2016 and the directory its in. Secondly did you reinstall NodeJS after rebuild of the server? Wondering for a friend.

-SomeGuru

**Comment by dinger1986** [comment]
@bravery-only did this get resolved?

**Comment by si458** [comment]
this is now fixed with a new installer update https://meshcentral.com/tools/MeshCentralInstaller.exe
it now installs node 18, uses dotnet 4.8 and unstall only required
