### ISSUE TITLE
Hide the "Sharing desktop with: <name>" at the top of the screen

### ISSUE THREAD

**Issue by JohnB17** [Ylianst/MeshCentral#5102]
**Is your feature request related to a problem? Please describe.**
The window at the top that says "Sharing desktop with: <name>" is always in the way, and it's annoying to keep moving it.

**Describe the solution you'd like**
One of these will work for me:
- Hide button on the window
- A config file that can be configured to hide it
- Have it disappear after a few seconds

**Describe alternatives you've considered**
Chrome Remote Desktop, but my organization blocks it so it's not an option.

**Comment by si458** [comment]
this message box only appears if you right click connect and select 'privacy prompt' 
OR you have the privacy prompt enabled for your group of computers

by default you wont see this box

**Comment by si458** [comment]
please can you share your `config.json` (blank secrets if you set any)

**Comment by dinger1986** [comment]
How did you install it?

Can you share a redacted config.json?

**Comment by JohnB17** [comment]
Where is the config.json? Also, I installed by emailing myself a Windows installer and installed it when I got home.

**Comment by dinger1986** [comment]
Your talking about the client install.

Whats your server installed on?

config.json is in the meshcentral-data folder in the server

**Comment by JohnB17** [comment]
I am using the public server on meshcentral.com

**Comment by si458** [comment]
oh.... the public server has restrictions set in place, so you cannot disable the banner, its required sadly sorry

**Comment by dinger1986** [comment]
Not sadly!! It's very necessary

**Comment by silversword411** [comment]
Gotta wonder just how much that's used in malware campaigns. All remote control software is abused by ah013s

**Comment by si458** [comment]
Please can you close this issue as the meshcentral.com public server is now closed
