### ISSUE TITLE
NPM package vulnerabilities found

### ISSUE THREAD

**Issue by Stephan-Ru** [Ylianst/MeshCentral#5106]
Hey Developer,

 

We tried to download this npm-module over our Nexus Repository Manager and the Nexus IQ Server let us know there are Cricitcal CVE warnings in the Cross-Dependencies. Is it possible for you to look into that and to update the dependencies and make a new release with safe assets?

mfg

![Sonatype](https://user-images.githubusercontent.com/131956952/234806100-c914ab0b-6430-416a-b938-e715b391df28.png)

**Comment by jammsen** [comment]
+1
We have the same problem and would live to use this

**Comment by si458** [comment]
download repo, update the package.json, `npm install`, run server check all is ok, then submit a PR

**Comment by jammsen** [comment]
@si458 So what you mean is basically to fix it themself and create a Pull-Request, right?

There might be 2 problems with that #1 @Ylianst might not accept that PR and #2 @Stephan-Ru might not be programmer and doesnt know how to do that.

**Comment by si458** [comment]
@jammsen yes that is correct as sadly @Ylianst only works on this part time now, but will accept PRs if they are correct and fix issues

**Comment by si458** [comment]
@Stephan-Ru can you explain the npm vulnerabilities abit more? as i cant find any info on any of the pic details?

**Comment by jammsen** [comment]
@si458 i have send you an email to the mail addy in your profile with details.

**Comment by jammsen** [comment]
@si458 from what ive seen you closed the PR, do you have some infos on the context please?

**Comment by si458** [comment]
@jammsen basically you can update chart.js to 2.9.4 but then some charts/graphs work and others dont
im abit snowed under at moment to fix it, so when i find time next week ill have a look at it again 👍

**Comment by jammsen** [comment]
Do you have any idea if the the vulnerabilities are fixed with the latest releease 1.1.6 from 9 days ago? @si458

**Comment by si458** [comment]
@jammsen no sadly it wasnt, i will try and have a look again in my freetime
(i should really do a buymeacoffee to help support the repo!)

**Comment by jammsen** [comment]
Thats a bit sad to hear

**Comment by si458** [comment]
@Stephan-Ru chart.js and ua-parser-js was updated so this should no longer be an issue for yourself :)
