### ISSUE TITLE
Help finding codes relating to My Devices/Desktop view

### ISSUE THREAD

**Issue by neuralnermal** [Ylianst/MeshCentral#5111]
Hello, I'm trying to make adjustments to My Devices/ Desktop layout. But cannot seem to locate the codes relating to this.

![image](https://user-images.githubusercontent.com/132416432/235819076-f6c5b828-61a7-41ad-97a7-94665cfc95db.png)

I'm trying to see if I can adjust the layout to match how devices are located in a classroom. So a user can see which student is on which computer.

Thanks.

**Comment by si458** [comment]
the views are hard coded, you can switch the view by using the 4 icons in the top right hand corner of your snapshot
you can then also use the drop downs underneath to change the size of icons and sort order

**Comment by neuralnermal** [comment]
Thanks for the answer, it seems I would require more advanced understanding than I initially hoped.

So the scenario I was thinking about was that in the school computer lab, teachers could use Meshcentral to view students' progress and help out the ones who are struggling. 
Since students will change from class to class, I imagine it would be easier if I could change the layout of devices on the My Devices page, so that teachers can visually connect which computer is used by who.

If this is hard to change, would there be a way for students to edit the Device name on Meshcentral from their computer? Like a pseudo login page?

**Comment by si458** [comment]
No

But if u wanted like an overview layout,

Login to meshcentral,
Check which computers you want to view,
Then select 4 squares icon (3rd button along)
Then click connect all

It then does like a layout view of showing all the computers on your screen

Then when you need to control one of them just click the computers name and it diverts I to the control page for you

Hope this helps!
