### ISSUE TITLE
Disconnected after around 30 seconds

### ISSUE THREAD

**Issue by tootai** [Ylianst/MeshCentral#5114]
**Describe the bug**
While connected to a client using graphical UI (Windows, Mac or Linux) I get disconnected after around 20~30 seconds even while working on the PC.

**To Reproduce**
1. Connect to client
2. work on the computer
3. get disconnect. Tabs Desktop and Terminal disappears but client is still showed as connected.
4. to reconnect, go to console => agent action => clean kernel (option #2) => agent action (again) => force agent to disconnect (option #4479 
5. Agent will reconnect after few seconds and I can again use the PC for the next 20~30 seconds. 

**Expected behavior**
Stay connected

**Server Software (please complete the following information):**
 - OS: Debian11
 - Virtualization: kvm
 - Network: LAN+NAT
 - Version: 1.1.5
 - Node: 3.0.0.1

**Client Device (please complete the following information):**
 - Device: laptop, MBA
 - OS: Ubuntu
 - Network: LAN Local to Meshcentral, Remote over WAN
 - Browser: firefox
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: laptops, MBP, server
 - OS: Ubuntu 22.04 Mac OS Montery & Ventura
 - Network: Remote over WAN
 - Current Core Version (if known): 26907999 (Ubuntu) 3628780815 (Windows)

**Additional context**

**Your config.json file**
```
{                                                                                                                                                     [6/1977]
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in
 front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "support.tic.TLD",
    "_WANonly": true,                                                                                                                                         
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 80,
    "_redirPort": 8000,
    "_redirAliasPort": 81,
    "TlsOffload": "127.0.0.1,::1"
  },
  "domains": {
    "": {
      "title": "TOOTAi",
      "title2": "support.tic.TLD",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "certUrl": "https://support.tic.TLD:443/"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "tech@domain",
    "names": "support.tic.TLD",
    "rsaKeysize": 3072,
    "production": false
  }
}
```

**Comment by tootai** [comment]
Again. Could it be a FW issue ? I'm using Sophos UTM 9 (v715-3) since ages, no problem at all for all services running on servers behind the FW, which is the case for the mesahagent server.

**Comment by tootai** [comment]
Well. I tried with another MacOS Ventura sharing Android phone in 4G: no problem, connection stable. Well, problem seems connected to special kind of connection, which ?

**Comment by Souheib-khiter** [comment]
i have the same issue ! any solutions?

**Comment by si458** [comment]
a simple fix to try is set `agentPong: 22` under `settings` in ur `config.json`
This will send a ping to the remote device every 22 seconds to keep it alive
You might need to set 22 lower but it's a case of trial and error
