### ISSUE TITLE
Old xterm functions breaking Terminal Display/Viewing

### ISSUE THREAD

**Issue by Chris2381231** [Ylianst/MeshCentral#5115]
Our Terminal Display has not been working from versions 1.0.6.3 to version 1.1.1

For some reason the old xterm functions that were removed in 1.0.87 ([d99755f](https://github.com/Ylianst/MeshCentral/commit/d99755f22343762868afbe99e846e3fa34804816)) are still being used after we've upgraded to version 1.1.1

- function tunnelUpdate(data) { if (typeof data == 'string') { xterm.writeUtf8(data); } else { xterm.writeUtf8(new Uint8Array(data)); } }

Additional xterm fixes were made in 1.1.1 ([4e24783](https://github.com/Ylianst/MeshCentral/commit/4e24783662f9a795e66279fc818cccd13b800fcc)) / ([f85f6f2](https://github.com/Ylianst/MeshCentral/commit/f85f6f29d356e85dd106e9902809b0be313f5f8f))

I've been unable to find any further fixes or issues raised besides #4979, which hasn't had any updates.

Is this something that is expected to be fixed in one of the later updates, or will something need to be manually corrected on our end if one of the files/cfgs is potentially bugged or corrupted?

Thanks
![image](https://user-images.githubusercontent.com/131842967/236400192-3d4a1a28-eaaa-495d-8e33-ad2e93c4510c.png)
![image](https://user-images.githubusercontent.com/131842967/236402709-9dae187a-da9c-463e-a669-ebdf17befd52.png)
![image](https://user-images.githubusercontent.com/131842967/236403151-b4a8dd4e-0bc3-4d27-9a9a-8b0a0bf8b5c8.png)

**Comment by si458** [comment]
have you tried the latest as the screenshot shows? 1.1.5?

**Comment by Chris2381231** [comment]
> have you tried the latest version as the screenshot shows? 1.1.5?

Hi Simon,

We've updated to version 1.1.5 but the old xterm functions pre-1.0.87 are still being used (same as above screenshots).

Thanks

**Comment by Chris2381231** [comment]
Customisations made in the meshcentral-web folder were breaking the interface as these were not being updated (and using old functions).

Corrected on our end by renaming folder/using defaults.
