### ISSUE TITLE
Installation in Windows

### ISSUE THREAD

**Issue by navidrezanr** [Ylianst/MeshCentral#5118]
Hello,
I want to install meshcentral on a windows server.
I installed node js and the version is : v18.16.0
Also I make a directory and install meschcentral with : 
npm install meshcentral
command in command prompt.
After the installation when I use this command : 
node node_modules/meshcentral

the out put is this :
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\MESHCENTRAL-ROOT\node_modules\meshcentral'
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:920:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m
[90m    at node:internal/main/run_main_module:23:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

Node.js v18.16.0
If you can tell me what is wrong I would appreciate it.

**Comment by navidrezanr** [comment]
@si458 : Yes I do that exactly as it was told in documentation

**Comment by si458** [comment]
Which documentation did u follow?

**Comment by navidrezanr** [comment]
@si458 :
https://meshcentral-community.com/doku.php?id=howto:installation:manual:windows
I used this doc, I get one step ahead. I installed it correctly and now when I want to login, after creating admin user , I got only a white page without anything in it.

**Comment by navidrezanr** [comment]
@si458 : that was bacasue of usinf IE, I test with chrome and everything is now good to go.

**Comment by si458** [comment]
Ah, IE the pain of all problems...
The first thing i always do when I install Windows server is to install edge straight away and set it as the default browser! Haha

**Comment by dinger1986** [comment]
@si458 can close
