### ISSUE TITLE
Translation MeshCentral

### ISSUE THREAD

**Issue by Raito00** [Ylianst/MeshCentral#5119]
Hello!

Where i can find ResourceTranslator? Because all links on github or meshcentral wiki are broken.

**Comment by petervanv** [comment]
i searched in my archive, and i found an version of that software
[ResourceTranslator.zip](https://github.com/Ylianst/MeshCentral/files/11568973/ResourceTranslator.zip)

greetings Peter

**Comment by si458** [comment]
it has been added back to the meshcentral.com website https://meshcentral.com/downloads.html
