### ISSUE TITLE
ERR: TypeError: req.flash is not a function using OpenID Connect (oidc)

### ISSUE THREAD

**Issue by KDima23** [Ylianst/MeshCentral#5120]
**Describe the bug**
I setup MeshCentral with OICD Auth0 using the config below.

I got TypeError: req.flash is not a function error message after i clicked Continue  on the Auth0 page.

**To Reproduce**
1. Go to ' MeshCentral login page'
2. Click on 'login via OpenID connect'
3. See error

**Expected behavior**
I expected to log in to MeshCentral via OICD Auth0

**Screenshots**
TypeError: req.flash is not a function
    at allFailed (/meshcentral/node_modules/passport/lib/middleware/authenticate.js:134:15)
    at attempt (/meshcentral/node_modules/passport/lib/middleware/authenticate.js:183:28)
    at Strategy.strategy.fail (/meshcentral/node_modules/passport/lib/middleware/authenticate.js:305:9)
    at restored (/meshcentral/node_modules/@mstrhakr/passport-openidconnect/lib/strategy.js:125:21)
    at SessionStore.verify (/meshcentral/node_modules/@mstrhakr/passport-openidconnect/lib/state/session.js:72:11)
    at Strategy.authenticate (/meshcentral/node_modules/@mstrhakr/passport-openidconnect/lib/strategy.js:280:24)
    at attempt (/meshcentral/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/meshcentral/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at /meshcentral/node_modules/meshcentral/webserver.js:6646:120
    at Layer.handle [as handle_request] (/meshcentral/node_modules/meshcentral/node_modules/express/lib/router/layer.js:95:5)

**Server Software:**
 - OS: [Amazon Linux 2 AMI]
 - Virtualization: [none]
 - Network: [LAN/WAN]
 - Version: [1.1.5]
 - Node: [e.g. 16.20.0]

**Client Device:**
 - Device: [Laptop]
 - OS: [Windows 11 ]
 - Network: [Remote over WAN]
 - Browser: [Firefox]
 - MeshCentralRouter Version: [-]

**Remote Device (please complete the following information):**
 - Device: [PC]
 - OS: [Linux]
 - Network: [Remote over WAN]

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
      "authStrategies": {
        "saml": {
          "__callbackurl": "https://server/auth-saml-callback",
          "NewAccounts": true,
          "entityid": "urn:test.auth0.com",
          "idpurl": "https://test.auth0.com/samlp",
          "cert": "test.pem"
        },
        "oidc":{
          "_authorizationURL": "https://test.auth0.com/authorize",
          "callbackURL": "https://server/oidc-callback",
          "clientid": "test",
          "clientsecret": "test",
          "issuer": "https://test.auth0.com",
          "__tokenURL": "https://test.auth0.com/oauth/token",
          "__userInfoURL": "https://test.auth0.com/userinfo",
          "newAccounts": true
        }
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
this has been fixed already, we forgot to include flash for express, 
try updating to the latest version
