### ISSUE TITLE
MC on WindowsServer Lets Encrypt

### ISSUE THREAD

**Issue by mortonolsen** [Ylianst/MeshCentral#5123]
Hey folks, 

I´m really happy to have set up a little MC Server on a Windows Computer.
 I used the Windows installer for laziness reasons. It is reachable via Port 80 and Port 443.

I wanted to use Let´s Encrypt to establish secure connections to the server.
When I add the letsencrypt part to my config the server will not be reachable after reboot.

Without the Lets Encrypt part it works fine.

What am I doing wrong?

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Virtualization: nope
 

** config.json file**
```


{
  "settings": {
    "cert": "mydomain.org",
    "_minify": true
  }


  "_letsencrypt": {
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
try adding `"skipChallengeVerification": true`, to the `letsencrypt` section,, 
then restart meshcentral, then wait about 2 mins,
do you have a `letsencrypt-certs` folder in `meshcentral-data` ?
whats the output in the console window?

**Comment by mortonolsen** [comment]
Thanks for the quick response.

I have no Le folder in meshcentral -data
I can reach the server without the Le section in my config, do you still think it is hairpin issue?

Might this all by caused by the Windows installer?
Ylian suggested to use the terminal/cmd instead of the windows installer...

**Comment by mortonolsen** [comment]
Sorry, just checked it was a json problem. json lint helped me to fix it.
Now I have a lets encrypt folder in meshcentral data, but it is empty and i still have no sll certificate...

**Comment by si458** [comment]
It takes about 2-3 mins to get the certificates and then restarts meshcentral itself so just hang fire

**Comment by mortonolsen** [comment]
thanks

**Comment by mortonolsen** [comment]
Works like a charm, it was a json mistake. So any idiot who thinks like me, he knows how to configure in json, double check on jsonlint,

Thanks for your support

**Comment by si458** [comment]
glad its sorted, please close this issue
