### ISSUE TITLE
Unable to set network adapter to bind to

### ISSUE THREAD

**Issue by hjgode** [Ylianst/MeshCentral#5124]
I install MeshCentral on a Windows 10 machine with two network adapters: 192.168.0.152 and 192.168.2.153.
When I start MeshCentral, it always binds to second IP but generates a cert for the first IP.

How can i Specify which network card/address MeshCentral will bind, or, better, can I run two instances for MeshCentral with different IPs?

I am working in LAN only. No internet public IP.

**Comment by si458** [comment]
you set `portBind` and `redirPortBind` in your settings.json
https://github.com/Ylianst/MeshCentral/blob/3dd469f1a02276eeb58226df41e08a3f5311c76d/meshcentral-config-schema.json#L97
https://github.com/Ylianst/MeshCentral/blob/3dd469f1a02276eeb58226df41e08a3f5311c76d/meshcentral-config-schema.json#L100

**Comment by hjgode** [comment]
Sorry, has been overseen in the long list of settings.

What about running two instances on the same windows PC?

**Comment by si458** [comment]
> Sorry, has been overseen in the long list of settings.
> 
> What about running two instances on the same windows PC?

Still possible just set ur ips and make sure the ports are different from each other is they are hotting going to use the same ip!

**Comment by hjgode** [comment]
OK, I can run two instances on my two network cards using separate directories for MeshCentral

Thanks for the help

Josef
