### ISSUE TITLE
Feature Request : Would it be possible to have Mesh Central Agent aliases that would allow the agent to exist in N number of device groups?

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#513]
**Use Case:** The way we use Mesh Central, we have a hierarchy where the device groups are named with the network name, however, there could be a time when the networks are connected, and thus, the agent can only live in one group, which means the other network group appears to be missing an agent.

**Workaround:** For us, we are using the group name as a network alias, which is a bit confusing at times. (certainly not impossible to manage, it would just nice to have agent aliases for a more programmatic approach to this.)

It would be nice to be able to have the same mesh central agent appear in two (or more) different groups to allow for our very specific nomenclature. Maybe something like the way you have "change group" but an option to "alias to another group". and that object would remain in the database until such time as symlinks = 0 or something?

It would be very nice if this were also (or only, I'm fine with that) implemented in meshctrl

**Comment by Ylianst** [comment]
Well. When a device connects, MeshCentral needs to have a clear set of policies that will apply to the device. Having the device in many groups makes this really confusing. This said, you can apply "tags" to a device and then sort devices by tags in the devices view. Let me know if that works for you.

![x](https://user-images.githubusercontent.com/1319013/65795390-01168680-e11f-11e9-83e8-9b65c57b32d9.png)

**Comment by darryl-h** [comment]
Is there a way to search for the tags? Otherwise, that might not be so good, but certainly open to a better workflow.

**Hierarchy**

https://meshcentral.com/customer1
--> NetworkNameOne (DeviceGroup)
  --> Null
--> NetworkNameTwo (DeviceGroup)
  --> Endpoint1 (Device)

**Use Case:** Once a customer adds a network to their environment, this will trigger a device group to be created in MeshCentral. If these networks are able to be reachable, then we only need 1 endpoint, let's say it's in NetworkNameTwo. We have a separate group that would then need to find Endpoint1, so they can connect to NetworkNameOne, but, when they go in that device group, they do not see a device. 

**Workaround:** Right now, what I do is name the device group "NetworkNameOne & NetworkNametwo" which is fine, until the customer has many networks all connected. If we could create aliases, then it might look something like this:

https://meshcentral.com/customer1
--> NetworkNameOne (DeviceGroup)
  --> Endpoint1 (DeviceAlias)
--> NetworkNameTwo (DeviceGroup)
  --> Endpoint1 (Device-Real)

Alternately, if these are BOTH aliases, and the real object is in the backend, that also works, because the result to the user is the same (User is able to find endpoint in both device groups)

https://meshcentral.com/customer1
--> NetworkNameOne (DeviceGroup)
  --> Endpoint1 (DeviceAlias1)
--> NetworkNameTwo (DeviceGroup)
  --> Endpoint1 (DeviceAlias2)
[Backend Object, which both aliases refer to]

**Comment by darryl-h** [comment]
Can totally search for tags in the filter, tested, works. Closing this request. 

Will simply add service networks to the tags in CSV.
