### ISSUE TITLE
Meshcommander Remote KMV stop working on DELL Optiplex 7000 SFF 

### ISSUE THREAD

**Issue by NeroICM** [Ylianst/MeshCentral#5135]
**Describe the bug**

- Remote KVM session screen freeze
- Restart mesh commander -> connect -> KVM black screen -> mouse and keyboard feed still work on remote PC
- Restart remote PC fix the issue. Issue come back after a while
- Issue usually happen while camera streaming. 
- Issue only occurring with this particular DELL PC model. previous gen does not have the same issue

**Remote System info**
 - OS: Win 10 LTSC
 - PC model: DELL Optiplex 7000 SFF
 - BIOS version: 1.12.5 (latest)
 - CPU: Intel Core 12th gen i7-12700
 - Intel ME: 16.1.25
 - Screen attached through DP port. 

run .\nw.exe -debug -redirtrace -logfile:log.txt

Result attached below

Mesh commander version 0.9.6
[log.txt](https://github.com/Ylianst/MeshCentral/files/11505055/log.txt)

I strongly suspect this PC model is the culprit. If you can make sense of the log file and let me know if theres anything I can try please let me know.

**Comment by si458** [comment]
This has nothing to do with meshcentral.
Please close and reopen in the correct repo
https://github.com/Ylianst/meshcommander
