### ISSUE TITLE
agentAliasDNS not working

### ISSUE THREAD

**Issue by davscot** [Ylianst/MeshCentral#5136]
**Describe the bug**
I have specified an agent domain under agentAliasDNS in config.json however when starting MeshCentral the domain used for certificate is displayed instead.

**To Reproduce**
Below is MeshCentral service log *(I have changed with dummy data)*.

After starting MeshCentral, logging into the webpage and downloading end point device setup file; the domain specified within is pointing to meshcentral.mydomain.com rather than agent.mydomain.com.

May 18 15:53:13 mesh node[6291]: MeshCentral v1.1.5, WAN mode, Production mode.
May 18 15:53:22 mesh node[6291]: MeshCentral Intel(R) AMT server running on **mps.mydomain.com**:1234, alias port 5678.
May 18 15:53:22 mesh node[6291]: MeshCentral HTTPS server running on **meshcentral.mydomain.com**:443.
May 18 15:53:22 mesh node[6291]: MeshCentral HTTPS agent-only server running on **meshcentral.mydomain.com**:91011.

**Expected behavior**
I expect agent DNS alias to be used for agents if defined in config.json file

**Server Software:**
 - OS: Almalinux 9.1 x64
 - Virtualization: VM running on Proxmox hypervisor
 - Network: x1 network interface, no proxy just simple port forward.
 - Version: v1.1.5
 - Node: v16.18.1

**config.json file** This is a cut down version of the file for troubleshooting purposes, which has been updated with dummy data
```
{
  "settings": {
    "cert": "meshcentral.mydomain.com",
    "WANonly": true,
    "port": 443,
    "agentPort": 91011,
    "agentAliasDNS": "agent.mydomain.com",
    "agentPortTls": true,
    "mpsPort": 1234,
"mpsAliasPort": 5678,
    "mpsAliasHost": "mps.mydomain.com",
    "mpsHighSecurity": true,
}
}


```

**Comment by thieneret** [comment]
Same here.

MeshCentral v1.1.15, WAN mode, Production mode.
MeshCentral HTTPS server running on web.mydomain.com:443, alias port 443.
MeshCentral HTTPS agent-only server running on web.mydomain.com:12345, alias port 12345.

OS: Debian 12
Virtualization: LXC on Proxmox hypervisor
Network: x1 interface
Version: v.1.1.15
Node: v18.13.0

config.json
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "cert": "web.mydomain.com",
    "WANonly": true,
    "port": 443,
    "aliasPort": 443,
    "agentAliasDNS": "agent.mydomain.com",
    "agentPort": 12345,
    "agentAliasPort": 12345
  },
  "domains": {
    "": {
      "nightMode": 1,
      "newAccounts": false,
      "passwordRequirements": {
         "force2factor": true
      }
    }
  }
}
```

**Comment by si458** [comment]
just looking at this, its just a display bug in the command line
the server signs your agent files with the dns name u specify, and the agents use it
should be simply enough to fix!
