### ISSUE TITLE
Server peering / single MongoDB replicaset? 

### ISSUE THREAD

**Issue by robrechtmatthys** [Ylianst/MeshCentral#5138]
Hello everyone. I have a maybe stupid question. I want to use server peering with a single mongodb, is this possible?

So i have 1 MongoDB database on a different server than my Meshcentral servers
I have two meshcentral servers connecting to the same MongoDB, that works amazing. My two meshcentrals server are behind a HAproxy, with a loadbalancer. Also this works amazing, but when i create a agent on server1, the agent is not on server2. How do i fix this? 

I think it's with "server peering" but how do i enable server peering on only one MongoDB database? 

I need help asap because this is for a school project and i'm working on this problem for more than a week. Please help! Thankyou so!

**Comment by si458** [comment]
If I remember you have to make sure the secret key is the same on both server
And make sure the configs are both the same too!
I think @Ylianst made a YouTube video about it, have u checked there?

**Comment by robrechtmatthys** [comment]
> If I remember you have to make sure the sessionkey is the same on both server
> 
> And make sure the configs are both the same too!
> 
> I think @Ylianst made a YouTube video about it, have u checked there?
> 
> You also have to use sticky sessions in haproxy too
> 
> https://youtu.be/wH4DuYkXN1w
> 
> https://youtu.be/c95yykWPiGw
> 
> https://youtu.be/j8xIRGScju0

Thankyou so much for responding, i am aware of these things. But my question is: do i need server peering in order to have a agent connect to both servers? (so if one goes down that the other can also connect to the agent). 
Because if i need server peering i also need mongodb replica set turned on en changestream on, but i have only one mongodb, so a replicaset doesnt sound good? sorry for my english.

**Comment by robrechtmatthys** [comment]
My MongDB database was corrupt, i reinstalled mongodb and now everything works as fine. Except for one issue: i can't connect to the agent with server2, only with server1. I think here comes server peering?

**Comment by si458** [comment]
Related #5373
