### ISSUE TITLE
What do I need to do to get SSL working properly?

### ISSUE THREAD

**Issue by ITCMD** [Ylianst/MeshCentral#5139]
Hi there!

I've worked with linux servers a good bit but mostly apache stuff with certbot for SSL.

I just installed meshcentral on a cloud server. First off, impressive software. Great work folks. However, I noticed that https does not have a valid certificate. I thought I read somewhere that meshcentral manages LetsEncrypt automatically.

I did originally launch it with the ip address as the --cert parameter for initial testing, but later ran it with --cert mydomain.com and --install, which is what I'm running now. Perhaps it attempted to gen a cert from there instead?

<img width="282" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/32961763/0f014c79-198c-43cb-a370-6da61f30fca7">
<img width="433" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/32961763/3b276ff2-7e31-4b78-8caa-91e3a4957fd2">

Here's the log output (replaced my domain with mydomain.com):
```
May 18 14:49:32 tactical-rmm systemd[1]: Started MeshCentral Server.
May 18 14:49:34 tactical-rmm node[13878]: MeshCentral HTTP redirection server running on port 80.
May 18 14:49:34 tactical-rmm node[13878]: MeshCentral v1.1.5, Hybrid (LAN + WAN) mode, Production mode.
May 18 14:49:36 tactical-rmm node[13878]: MeshCentral Intel(R) AMT server running on meshcentral.mydomain.com:4433.
May 18 14:49:36 tactical-rmm node[13878]: MeshCentral HTTPS server running on meshcentral.mydomain.com:443.
```

What procedure can I use to get it working properly?

**Comment by si458** [comment]
You can use letsencrypt to setup ssl

https://youtu.be/a4F1ayu7XWo

**Comment by dinger1986** [comment]
Your mesh isn't going to work properly if you installed it using tactical rmms installer it might not be working as mongod isn't for arm if you are still going that route....

**Comment by dinger1986** [comment]
No, look at the snippet showing the username....same guy opened a ticket on trmms GitHub yesterday.

**Comment by ITCMD** [comment]
I did not use the tactical rmms installer. What you're seeing is the hostname

**Comment by dinger1986** [comment]
no worries, was just to flag it up incase thats what you were trying :)

**Comment by dinger1986** [comment]
I actually wrote an install script for meshcentral which also enables ssl via letsencrypt, https://github.com/techahold/Meshcentral-Installer but its not for arm, although could be easily modified, dont know if that helps at all?

If nto watch the video and make sure you have port 80 open

**Comment by ITCMD** [comment]
I followed that video and it's working great! I saw the video briefly but figured that was outdated and was using a reverse proxy. Thanks again for all the help, I'm thrilled with this software!
