### ISSUE TITLE
MeshCentral .net 4.7 install?

### ISSUE THREAD

**Issue by cyttek** [Ylianst/MeshCentral#5142]
Hello in windows server 2019 offline, there is no possibility to install meshCentral because Windows Server 2019 does not allow net.3.5 to be installed offline, there is any way to run mesh Central with .net 4.7?

thanks

**Comment by si458** [comment]
https://support.solarwinds.com/SuccessCenter/s/article/Install-NET-3-5-on-Windows-Server-2019?language=en_US
you should be able to install 3.5 offline is you have the iso handy

**Comment by cyttek** [comment]
im talking about mesh central server

**Comment by si458** [comment]
> im talking about mesh central server

you should still be able to install 3.5 offline using the link above and have the ISO handy (or download free trial from microsoft)

**Comment by dinger1986** [comment]
This can probably be closed @si458
