### ISSUE TITLE
Inactivity timeout when in Files

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#515]
`(MC2 v0.4.1-l)`
I've been connected to my remote server and had selected Files (so as to transfer files to the server). Then realized that I needed to do something beforehand which took me about 10 - 15 mins to complete. My inactivity timeout is set to 5 mins. When I come back into MC2, I'm still (apparently) connected to and viewing the Files on my remote server. When I attempt to transfer files to it, it doesn't work (assuming that the timeout had prevented me from doing so). Reconnecting to the remote server, file transfer works as expected.

Therefore I think it's just a very minor, _almost sub-subterranean_ bug that doesn't show the user that they've timed out and been disconnected from the server.  I've checked a couple of times and noted that the status bar within the Files section still shows me as "Connected" to that remote server.

IMHO to address this

1. A splash screen over the existing display showing the remote files stating "TIMED OUT" (or something similar)
1. Redirect that window as a whole, back to the main MC2 login screen, considering that the inactivity timeout doesn't just relate to the connected remote server, but also to MC2 as well (probably the easiest to achieve (?) and consistent with the rest of the application as a whole)

Aside: FWIW MC2 is completely changing the manner in which we're able to support our clients. The ease of installation and use combined with the multiple options for getting a remote server added to the MC2 server is nothing less than exceptional. Ylian and team, thank you once again for such a truly workflow-altering solution.

**Comment by Ylianst** [comment]
Thanks for the timeout report, I will take a look at it.

Also, thank you for the FWIW, it's very much appreciated. I will make sure to forward the comment to my management.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-n with a fix for this. The web socket session of the web application staying connected way longer than the session timeout and so, you are connected without a valid server session cookie. This is not a problem normally because the web application requests a new cookie at periodic intervals, but I was not using that new cookie. Fixed that, should work now.

**Comment by D4V3M0NK** [comment]
Lovely jubbly, works like a charm. Thank you sir.
