### ISSUE TITLE
Allow to change the display language on the mobile web UI

### ISSUE THREAD

**Issue by trmdi** [Ylianst/MeshCentral#5154]
On some browsers like Samsung Internet on Android, the user can't set the preferred languages so the language is wrong in some locales. So it would be great if the web UI let the user change it.

**Comment by si458** [comment]
please can you change the title to say `mobile web ui`
also #5156 should fix it for u

**Comment by trmdi** [comment]
> please can you change the title to say `mobile web ui` also #5156 should fix it for u

Why is it limited to the mobile ui? Shouldn't it also be applied to the desktop? I know Firefox, Chrome... have the Preferred language setting, but it could be useful for some browser that we are not aware?

**Comment by trmdi** [comment]
@si458 
Is your patch above let the user change the language on the login page?

**Comment by si458** [comment]
> It would be better if we can change it on the login page. Just a suggestion.

please can you close this issue then as my PR was merged to fix the mobile UI
then open a new issue (use feature request) with the suggestion to change language on login 👍 (keeps things nice n tidy)

**Comment by trmdi** [comment]
Since I don't know how to test your patch, I will let @Ylianst close the issue if he feels ok with it.

**Comment by ChiHnLeong** [comment]
https://you_url/?lang=en

**Comment by si458** [comment]
@ChiHnLeong you are correct! You can change the UI language via the URL
