### ISSUE TITLE
Remote Desktop Blank Screen

### ISSUE THREAD

**Issue by lyyiheang** [Ylianst/MeshCentral#5163]
We have remote Pc running agent and we able to remote desktop on it properly but once user load up lockdownbrowser.exe software screen got blank with mouse controllable.(issue occurred after very few second)
https://github.com/Ylianst/MeshCentral/assets/35592350/4e14764d-af9c-4f73-bd4e-17e37006df5d

**Server Software (please complete the following information):**
 - OS: Windows Server 2016
 - Virtualization: VMWare
 - Network: WAN under CloudFlare
 - Version: latest
 - Node: latest

**Client Device (please complete the following information):**
 - Device: Windows 11
 - OS: Windows
 - Network: Over WAN
 - Browser: Firefox
 - MeshCentralRouter Version: latest

**Your config.json file**
```
{
 Only Agent Naming is configured
}

**Comment by dinger1986** [comment]
@si458 can close
