### ISSUE TITLE
Removing mesh agent by  Eset antivirus

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#5164]
Three or four days ago, the antivirus eset has applied an update that even if we change the name of the mesh agent service, it detects the virus and deletes the file!

**Comment by dinger1986** [comment]
youll need to add exclusions. It wont be doing it by name it will be the signature of the file itll pick up

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
closing as agreed, all AV ones will point to a discussion going forward, me thinks
