### ISSUE TITLE
Custom installation path for Mesh Agent

### ISSUE THREAD

**Issue by lyyiheang** [Ylianst/MeshCentral#5165]
We would like to get Mesh Agent to be install to another path which will be hidden path.

Note: as attached screenshot
![image](https://github.com/Ylianst/MeshCentral/assets/35592350/49585df1-7bb7-490a-bc68-c89a38956a38)
**Server Software (please complete the following information):**
 - OS: Windows Server 2016
 - Virtualization: VM
 - Network: Hybrid
 - Version: latest
 - Node: latest

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Network: Hybrid
 - Browser: Firefox
 - MeshCentralRouter Version: No MeshCentral Router

**Comment by si458** [comment]
Currently when you customise your application name it will install it into `c:\program files\(company name)\(app name)`

To install elsewhere I believe it has to be done manually with ur own sorta installer sadly

**Comment by lyyiheang** [comment]
> Currently when you customise your application name it will install it into `c:\program files\(company name)\(app name)`
> 
> To install elsewhere I believe it has to be done manually with ur own sorta installer sadly

Dear Team,

I see someone has Mesh Agent which automatically install to C:// location without manually. So is there anywhere else to do?

**Comment by dinger1986** [comment]
Same answer, check the config.json https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json

I don't see anyway to customise that location.

I think they are making a custom installer which has a password and installs to c:

**Comment by dinger1986** [comment]
@si458 can close

**Comment by si458** [comment]
in theory you can use a different folder, but you would have to create your own installer/setup
```
PS C:\Users\ASUS\Downloads\wtf123> .\myremoteagent64-myothergroup.exe -h
Mesh Agent available switches:
  run               Start as a console agent.
  connect           Start as a temporary console agent.
  start             Start the service.
  restart           Restart the service.
  stop              Stop the service.
  state             Display the running state of the service.
  -signcheck        Perform self - check.
  -install          Install the service from this location.
  -uninstall        Remove the service from this location.
  -nodeid           Return the current agent identifier.
  -info             Return agent version information.
  -resetnodeid      Reset the NodeID next time the service is started.
  -fulluninstall    Stop agent and clean up the program files location.
  -fullinstall      Copy agent into program files, install and launch.

                    The following switches can be specified after -fullinstall:

     --WebProxy="http://proxyhost:port"      Specify an HTTPS proxy.
     --agentName="alternate name"            Specify an alternate name to be provided by the agent.
```

so you can put the setup exe into say `C:\myprogramhere`
then run `C:\myprogramhere\myremoteagent64-myothergroup.exe -install` as an administrator/command line
