### ISSUE TITLE
Add Password Once Install Mesh Agent

### ISSUE THREAD

**Issue by lyyiheang** [Ylianst/MeshCentral#5166]
I see someone can put the password when installing Mesh Agent but i cannot figure out how to do it. So i would like to seek everyone support to check if we can do it

Note: as attached screenshot
image

![image](https://github.com/Ylianst/MeshCentral/assets/35592350/6a06cfe3-d49c-4ff9-95c6-cfca40e95495)
Server Software (please complete the following information):

OS: Windows Server 2016
Virtualization: VM
Network: Hybrid
Version: latest
Node: latest
Client Device (please complete the following information):

Device: Laptop
OS: Windows 11
Network: Hybrid
Browser: Firefox
MeshCentralRouter Version: No MeshCentral Router

**Comment by si458** [comment]
This isn't possible so I'm not sure where you have got this screenshot from? Or how you  achieved it either?

**Comment by dinger1986** [comment]
#655 and #3511 cover this.

https://windowsreport.com/password-lock-exe-files/#:~:text=KakaExeLock%20–%20Password%20Protect%20Program%20This%20is%20an,is%20put%20in%20will%20the%20file%20be%20opened

Would maybe help somewhere if you just want a password preventing someone using your installer without your prior permission

**Comment by lyyiheang** [comment]
Dear Team,

File was generated via Mesh Central Web by someone and pass it to me. I confirmed that file is not modified with another 3rd party tool for password. So i would like to see if anyone else able to archive this?

**Comment by dinger1986** [comment]
It's not something I have seen or heard of, here is the sample config.json and I don't see it on here either https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json.

I suggest asking whoever showed you it how they did it and maybe report back.

**Comment by dinger1986** [comment]
@si458 you can probably close this as well
