### ISSUE TITLE
Can meshctrl.js run commands in a similar way to ssh?

### ISSUE THREAD

**Issue by karictu** [Ylianst/MeshCentral#5169]
I have several tasks automated using SSH where one command is issued and it blocks until it is complete.  Ex:  ssh <user>@<remotemachine> dostuff.exe.

Is there a way to do this via meshctrl.js that has the same behavior of  running a single command, returning stdout, and blocking until the command is completed?

From what I can see, meshctrl.js runcommand will not block and meshctrl.js shell is strictly interactive and does not take a command.  Am I missing something?

**Comment by si458** [comment]
RELATED/DUPLICATE #5203
