### ISSUE TITLE
MeshCMD AMTACM is activating as CCM on MeshCentral2 (0.4.1-m)

### ISSUE THREAD

**Issue by spyram** [Ylianst/MeshCentral#517]
Hi everyone,

I'm trying to use AMTACM command but it ends up with a CCM activation instead :(

"Intel AMT CCM Activation success."

I'm using a custom generated certificate for server side AMT service. Meshcentral loads the certificate and makes available the ACM profile in the group so I assume Its being parsed correctly.

The clients are only setup with a custom admin password,

The group is setup like "Simple Admin Control Mode (ACM)"
I running the command like Meshcentral "Activation" button instructs
meshcmd amtacm --url wss://<myserver.fqdn>/amtactivate?id= --serverhttpshash

but I'm getting this on amtactivation.log...
{"time":"2019-09-30T16:21:20.518Z","action":"ccmactivate","domain":"","amtUuid":"","amtRealm":"Digest:2B300000000000000000000000000000","user":"admin","password":"","ipport":":62718","meshid":"mesh//"}
{"time":"2019-09-30T16:21:20.999Z","action":"ccmactivate-success","domain":"","amtUuid":"","ipport":":62718","meshid":"mesh//"}

It looks like the request is being made as a CCM instead of a ACM.

One thing I'm still unable to do is to add my certificate root certificate thumbprint to AMT hashes.

Any ideas?

I'm also unable to get more output from meshcmd command. Do we have any verbose option? or dump to some log file?

**Comment by jsastriawan** [comment]
First of all, AMT ACM requires AMT activation certificate for the domain where the machine to be activated resides. This certificate must be added into Meshcentral config.json.  Second, a profile must be configured at Meshcentral 2. Third, the machine must also receive domain through DHCP option 15 via its AMT supported LAN port.

Probably @matt-primrose could document further.

**Comment by spyram** [comment]
Hi,
Thank you so much  for the fast reply,

- AMT ACM requires AMT activation certificate: **Checked** :) I have one with the OU option instead of the OID value _A well known string in the OU field. The string is “Intel(R) AMT Setup Certificate”._
- a profile must be configured at Meshcentral 2: If by profile you mean a AMT Policy attached to the group, than its done (Simple Admin Control Mode (ACM) then **Checked** :) If its another profile (like the ones from SCS then I have no idea where to create one and attach it to the group (no mention on config.json to profiles, user manual nor in the https://meshcentral2.blogspot.com/2019/06/meshcentral2-intel-amt-acmccm.html page)
- the machine must also receive domain through DHCP option 15: **Checked** :)

I'm still struggling with addin the hash from my custom certificate to AMT, but some verbose output from meshcmd would be great to further troubleshoot.

**Comment by jsastriawan** [comment]
See sample-config.json.

AmtAcmActivation": {

"log": "amtactivation.log",
"certs": {
"mycertname": {
"certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
"keyfile": "amtacm-leafcert.key"
}
}

It seems you have to split the certificate into certificate chains and private key. 

If you look at AMT activation certificate, those are the typical structure. I.e. leaf certificates to root certificate and one private key to sign the hash. 

@matt-primrose has a nice little utility to split certs.

https://github.com/matt-primrose/amt-rcs/blob/master/certificateManager.js

**Comment by spyram** [comment]
Hi,

Thanks,

I'm using this setup...

`     "AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "myvprocert": {
            "certfiles": [ "pe-public.cer", "pe-intermediate.cer", "pe-root.cer" ],
            "keyfile": "pe-private.key"
          }
        }`

And I spited and converted my Certificates using OpenSSL.
I'm assuming that, since the Certificates are parsed by MeshCentral that they are validated.

Also, its strange that If I'm requesting ACM on the command line that its going for a CCM activation. If there is some type of issue with the certificate chain or DHCP option 15, or whatever, it should return an error with a description. Or have a verbose mode.

**Comment by jsastriawan** [comment]
Ok, 

Certificate parsing probably failed silently.

Let's try different configuration format.
See (https://github.com/Ylianst/MeshCentral/blob/master/certoperations.js#L88)

`"AmtAcmActivation":  { 
     "log": "amtactivation.log", 
     "certpfx":  "amt-cert.pfx", 
     "certpfxpass": "5up3r53Cr3t" 
} '

Replace the above certpfx and certpfxpass accordingly and also please make sure the PFX file is in meshcentral-data. I suspected the way you converted the PFX to .cer and .key is not done correctly. The .cer and .key files should be in PEM format. https://www.sslshopper.com/ssl-converter.html

By supplying PFX file, hopefully Meshcentral 2 converts it to the right format.
Let me know if it works. 
Regards,


Joko Sastriawan

**Comment by spyram** [comment]
This is the output from the client... (I've removed the identifying pieces of my env).

D:\Configurator>meshcmd.exe amtinfo
Intel AMT v11.8.60, pre-provisioning state.
Wired Enabled, DHCP, 48:2A:E3:3B:53:2F
Wireless Disabled, DHCP, 00:00:00:00:00:00
DNS suffix: mydomain.fqdn.

D:\Configurator>meshcmd amtacm --url wss://<myserverFQDN>/amtactivate?id=ScrambledText --serverhttpshash 301F16C1435EBAB4BBD1726DBA8EA71F647FD84247DA65E50A03B380E397C28BECBF706D2ABC4F7B3323FA4810998432 
Starting Intel AMT activation attempt...
Setting up MEI...
Setting up LME...
FQDN:   mydomain.fqdn
UUID:   095d3fcc-1f8d-11b2-a85c-f20ef601f051
Realm:  Digest:2B300000000000000000000000000000
Nonce:  kZSGocc124oCF/UaevRNRED45jQ=
Connecting to wss://<myserverFQDN>/amtactivate?id=ScrambledText
Connected, requesting activation...
Intel AMT CCM activation success.

**Comment by jsastriawan** [comment]
Oh hold on, 

Did you order the right AMT activation certificate? AMT activation requires signing from authorized provider.
See: https://www.intel.com/content/www/us/en/support/articles/000026592/technologies.html
Second video.

So basically Intel has put several authorized root certificate signing authority in the AMT firmware (such as Comodo, Entrust, GoDaddy and DigiCert). This enable 3rd party authority to verify domain ownership and to sign AMT activation certificate. 
In order to activate AMT via this method, you need to purchase certificate for AMT activation in your domain. 

Regards,

Joko

**Comment by spyram** [comment]
Thanks, I know ;)
I have a custom certificate generated by MS ADCS services complying with the requirements stated in this doc page 21...
http://info.meshcentral.com/downloads/ActivePlatformManagementDemystified/APMD-Chapter17.pdf

And I added the Root CA thumbprint to the Hashes in the MEBx BIOS Interface manually...

> Self-provided | These hashes are based on your own root certification authority. In this case, you issue the necessary certificate from your own certification authority. You can use this method for evaluation of the Remote Configuration feature in a lab environment before you purchase a commercial certificate from a certificate provider.The hash that you must add to the Intel AMT firmware is displayed at the Thumbprint field of the trusted root CA certificate.These hashes can be added to the Intel AMT firmware by an OEM (on your request) or you can flash the firmware yourself. You can also enter the hash into the MEBx manually, through the Setup and Configuration > TLS PKI > Manage Certificate Hashes menu.


But even if the certificate is the issue, It doesn't make sense that AMTACM ends up with a CCM activation instead of providing an error.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.1-o with support for Intel Standard Manageability and some improvements to MeshCmd for activation. When you update to the new MeshCentral, you will need to re-download/update MeshCmd too.

So, I wrote the activation code in MeshCentral to do CCM if ACM is not possible, the new version of MeshCentral/MeshCmd. The new version will display an message saying that ACM was not possible and it's going to CCM. This said, I am willing to create a new server switch to toggle the CCM backoff if you like. Also, even in CCM, you can try ACM activation again if you like.

One more hidden feature: When you cut & paste the MeshCmd command line for ACM activation from MeshCentral, you can replace "meshcmd amtacm ..." with "meshcmd amtdiscovery ...". The "amtdiscovery" command will just add your computer to the Device Group without changing it's activation state. So, if you are already activated, run that to just add it.

Below is the new MeshCmd with the CCM warning...
![MeshCmd-AcmActivate](https://user-images.githubusercontent.com/1319013/66006048-2cbca800-e462-11e9-9ddd-30c7eb355952.png)

If you do "amtinfo" and the computer is not activated, MeshCmd will display the trusted FQDN, this is useful to make sure it matches your certificate.
![MeshCmd-AmtInfo](https://user-images.githubusercontent.com/1319013/66006060-3a722d80-e462-11e9-85a8-85ae54ec53b4.png)

Below, screenshot of "amtdiscovery". It will cause this computer to show up on the server.
![MeshCmd-AmtDiscover](https://user-images.githubusercontent.com/1319013/66006113-6e4d5300-e462-11e9-96f9-6670655e6204.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-p with @jsastriawan patch. I also added "AmtScan" command to MeshCmd which is kinda nice. Feedback appreciated.

![MeshCmd-AcmScan](https://user-images.githubusercontent.com/1319013/66008836-ff292c00-e46c-11e9-8b3a-7308593acfb0.png)

**Comment by spyram** [comment]
Hi,
Thanks for this update. Now I finally get the:
"Server: No matching ACM certificates, activating CCM instead."

Now, my Root certificate CA thumbprint hash is in the MEBx Hashes (its a SHA1 and not a SHA256 like the others) and I would assume that the OU=Intel(R) AMT Setup Certificate and the OID for Server Authentication should be enough for AMT Activation. Note that I'm also using it on the https part of the server and that Google Chrome validates the certificate with no problem (including SAN names and ciphers).

So I'm guessing I should have all the required configurations for using a custom AMT activation certificate.

How can one tell if the Server certificate is the issue (and what the issue is) or if the Server hash in the Client MEBx is the one not found or with problems?

**Comment by dinger1986** [comment]
AMT @si458

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
