### ISSUE TITLE
Ntfy credential for self-hosted server

### ISSUE THREAD

**Issue by dico-hubnc** [Ylianst/MeshCentral#5170]
Hello,

I'm self-hosting NTFY server, I added 'host' in my config.json but how to specify username/password ?

 - OS: RaspberryOs - Debian 11
 - Network: Hybrid
 - Version: 1.1.5

I also tried adding 'authorization' fields with encoded credential without success : 

"messaging": {
    "ntfy": {
      "host": "https://push.domain.com",
      "authorization": "Basic ZGlxxxxxxx==",
      "userurl": "https://push.domain.com/userhelp"
    }
  }

Regards,
Dico

**Comment by si458** [comment]
currently we only support sending to an ntfy custom server without authentication, 
would you like a user/pass options being added?
im guessing you use this method for authentication?
https://docs.ntfy.sh/config/#example-private-instance

**Comment by lonepie** [comment]
that's the setup I use (private instance). Preferably the implementation would work with user+pass or access token.
