### ISSUE TITLE
MeshCentral 1.1.5 LetsEncrypt certificate with CertUrl problem

### ISSUE THREAD

**Issue by doziteh** [Ylianst/MeshCentral#5171]
LetsEncrypt Certificates not pulled from Apache correctly

Have installed MeshCentral 1.1.0 with LetsEncrypt certs pulled via CertUrl without problem
Meanwhile updated MeshCentral to 1.1.5 - no problems
After renewal of LE certificates Apache 2.4.6 uses them correctly but Meshcentral HTTPS is broken 
(still using old certificate so browser gives date error for certificates)...
Tried restarting meshcentral service (using it as service) without any change - still error.
After some investigation deleted  webserver-cert-private.key and webserver-cert-public.crt
meshcentral service restart, generates new certificates but this ones are complitly broken....
Problem eventually solved with manually coping certificates from LE dir and converting them to key and crt
with openssl and some text editing...
Took a look at certoperations.js but this is beyond my expertise...

**Expected behavior**
Certificates should automatically pulled from web server

**Screenshots**
N/A

**Server Software (please complete the following information):**
 - OS: Centos 7
 - Virtualization: NO
 - Network: WAN
 - Version: 1.1.5
 - Node: 16.18.1

**Client Device (please complete the following information):**
 - Device: any
 - OS: Win, Linux
 - Network: WA
 - Browser: Chrome, Firefox, Opera...
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: any
 - OS: Win 7, 10
 - Network: WAN
 - Current Core Version (if known): 

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "erp.xxx.yy",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "erp",
      "title2": "erp.xxx.yy",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "CertUrl": "https://erp.xxx.yy"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "erp.hidrosanitas.rs",
    "production": false
  }
}

**Comment by dinger1986** [comment]
Does production not need set to true @si458 

Also you mention Apache pills it fine, are you running a proxy?

**Comment by si458** [comment]
from the looks of this you are using apache as a reverse proxy
you should set `tlsOffload` to `IP OF APACHE` under `settings` in `config.json`
this tells meshcentral to NOT do any TLS stuff like cert stuff and let apache handle it instead
