### ISSUE TITLE
Connecting to session through browser 

### ISSUE THREAD

**Issue by MotherRussia00** [Ylianst/MeshCentral#5173]
Hello, I have a technical support website and I'm trying to enable end users to grant permission for us to control their computers from our site remotely. So, I need a button or something similar on the website that users can click on. They will then receive a warning message, and if they click "Yes," the session connection will either start or connect to my server.

Server Software:
 - OS: Ubuntu 22.04
 - Virtualization: None
 - Network: For now Lan but I have access to make it public 
 - Version: 1.1.5
 - Node: v12.22.9

Client Device 
 - Device: Laptop
 - OS: Windows
 - Network: Local
 - Browser: Chrome

Remote Device:
May be different

Config.json
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are i>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "***",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "***",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}


```

**Comment by si458** [comment]
you are looking for meshassistant instead of meshagent,

you can download the exe from your webpanel (when you click add device in a group)
you download this exe somewhere, and upload to somewhere,
the end user then downloads and runs the exe, 
then they give u access (or if you selected 'always connected', then it will autoconnect to the server and you connect to them BUT THEY GIVE U ACCESS FIRST)

👍

**Comment by MotherRussia00** [comment]
So I have this kind of panel 
![image](https://github.com/Ylianst/MeshCentral/assets/39841955/1dfcb17b-563b-45c0-878a-e3e59e417463)
and I'm clicking for example at the NonPermanent Users on the add one and then I have this kind of a window
![image](https://github.com/Ylianst/MeshCentral/assets/39841955/2b13c550-8c43-4950-95db-4ba76f675989)
and I can't understand where can I download not an agent but an assistant

**Comment by si458** [comment]
You click the select box saying 'windows' and it will show other options including 'mesh assistant'

**Comment by MotherRussia00** [comment]
Yes, I think I found the solution. Thank you very much for your help
