### ISSUE TITLE
Allow to change the language on the login page

### ISSUE THREAD

**Issue by trmdi** [Ylianst/MeshCentral#5174]
Currently the user can change it only after he logged in.
So it would be better if we can change it on the login page, on both mobile and desktop.

**Comment by ChiHnLeong** [comment]
https://you_url/login?lang=en

**Comment by trmdi** [comment]
> https://you_url/login?lang=en

It may work, but it's not a good UI/UX.

**Comment by tomsik-radek** [comment]
Sadly it's not, because MC picks default language from your browser/OS locale. If your users are going to MC with a link, set the ?lang link. Or teach them the word for "username" "password" or "login"

**Comment by si458** [comment]
this ok for you? sorry for delay
![image](https://github.com/Ylianst/MeshCentral/assets/765314/ffea4f44-de74-469e-9398-18383f1ab0d5)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/3c814e5c-351b-4167-a171-125b3379c010)

**Comment by trmdi** [comment]
That looks like an option to the login form. I would like it to be placed at the bottom of the page, near the CGU link.

**Comment by si458** [comment]
Can u plz draw an example of where it should be then in meshcentral?
As it's going to be hard I think to put it near the bottom because the bottom is only a footer, which might contain other text!?

**Comment by si458** [comment]
what about this instead? (ignore the welcome text i was testing where stuff was being placed)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/c3c45347-e5c6-451c-9f34-d4f68132fcb7)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b14899cc-4d71-4fba-b1bf-3271b7ce3467)

**Comment by trmdi** [comment]
Can we use just an icon like this page? https://dictionary.cambridge.org/
It should still placed at the bottom of the page. Anyways, I don't think it need to be as attractive as the login form.

**Comment by si458** [comment]
thats too much hassle im afraid,
im just in process of adding a config.json option in under your domain section, so you can either
top=shows under login bit
bottom=shows at bottom
false=hide completely (default)

**Comment by si458** [comment]
all done! `showLanguageSelect` can be set to either `bottom` or `top` under your `domains` section in your `config.json`
and it will show at top or bottom, or if you dont specify it, hide it 👍
