### ISSUE TITLE
Não Carrega o site

### ISSUE THREAD

**Issue by LucianoCM7** [Ylianst/MeshCentral#5177]
Amigos, bom dia...

Eu faço todo o processo de instalação normalmente segundo a documentação, mais poucas horas depois o site não carrega com a aplicação. Já é a terceira vez que eu recrio a minha VPS e acontece a mesma coisa. Eu acesso normal a minha máquina e horas depois o site fica fora... nem carrega a página.

Alguém já passou por esse problema?

Só estou conseguindo instalar o serviço pelo IP do meu servidor VPS e não pelo nome do meu domínio. Eu estou seguindo as orientações do video abaixo:

https://www.youtube.com/watch?v=T8LllCqCRG0

Friends, good morning...

I do the whole installation process normally according to the documentation, but a few hours later the site does not load with the application. It's already the third time I recreate my VPS and the same thing happens. I access my machine normally and hours later the site is off... it doesn't even load the page.

Has anyone experienced this problem?

I'm only able to install the service by the IP of my VPS server and not by my domain name. I'm following the instructions in the video below:

https://www.youtube.com/watch?v=T8LllCqCRG0

**Comment by si458** [comment]
try following the docs instead to set it up - https://ylianst.github.io/MeshCentral/install/
