### ISSUE TITLE
How to configure the serveur URL for windows agent ?

### ISSUE THREAD

**Issue by Argayle** [Ylianst/MeshCentral#5185]
Hello i try to install mesh yesterday on Debian 11.
i manage to access the web configuration of the server, create a group et download the agent.
But it didn't have any server URL.

I can't find any information on you tube videos or web site to explain how to configure that thing.
here ma config.json :

{
"$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
"comment1": "This is a simple configuration file, all values and sections that start with underscore (_) are i>
"comment2": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
"settings": {
"cert": "srv-Mesh",
"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
"WANonly": true,
"_LANonly": false,
"_sessionKey": "MyReallySecretPassword1",
"_port": 443,
"_AllowLoginToken": true,
"_AllowFraming": true,
"_WebRTC": false,
"_ClickOnce": false,
"_aliasPort": 443,
"_redirPort": 80,
"_redirAliasPort": 80
},
"domains": {
"": {
"_title": "MyServer",
"_title2": "Servername",
"_minify": true,
"_newAccounts": true,
"_userNameIsEmail": true
}
},
"_letsencrypt": {
"comment": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
"email": "[myemail@mydomain.com](mailto:myemail@mydomain.com)",
"names": "myserver.mydomain.com",
"production": false
}
}

Also, if i understand correctly, Mesh give us contorl of remote computer, but is there a way to alert the user that someone try to access his computer (something like anydesk, the user can allow ou decline the remote access) ?

**Comment by japi** [comment]
Please set a valid DNS/FQDN Name (like "meshcentral.yourdomain.com") in the "cert" variable.
It should match the one in the letsencrypt section in the "names" variable.
To enable automatic generation of the certificate, please enable the letsencrypt section by removing the underscore before "_letsencrypt".
Also change email and names and test if the letsencrypt-test-certificate can be generated.
If successful, change "production" from false to true.

There are 3 options to alert the user:
- A dialog the user has to confirm (includes a picture and the name of the connecting person)
- A bar at the top of the screen, with some text like "Sharing screen with <User Name>"
- A Windows Notification

Each option can be enabled separately for each device, but none of them has to be enabled. (you could not use MeshCentral to manage servers, if a confirmation dialogue was enforced)

**Comment by Argayle** [comment]
i was able to modify the server url, it work thank you.
However i don't see how we can enable on of the three option you mentionned to alert our users 
i work for public administration and there are rules i need to respect, one of them being : user has to accept (or give himself the information to) the remote control

**Comment by Argayle** [comment]
I found it it the meantime
thank you !
