### ISSUE TITLE
Incorrect Power State shown / inconsistent power state

### ISSUE THREAD

**Issue by rjblake** [Ylianst/MeshCentral#5187]
I have 2x identical machines. If I power them on the same way, one machine shows the status as 'Powered', the other as 'Soft-off'. However, they are both powered on and operational. If I go to the IntelAMT tab of the machine showing status as 'Soft-off', the System Status 'Power' status shows it as 'Power on'. It seems that there is no way to refresh the status on the 'My Devices' tab in MeshCentral. If I restart the MeshCentral server, the correct power status is shown.

**Comment by silversword411** [comment]
Aren't computers fun?

I've seen two identical make/models behave differently when they were loading from the same image.
