### ISSUE TITLE
Cannot connect my agents with dockerized MeshCentral

### ISSUE THREAD

**Issue by sherbmeister** [Ylianst/MeshCentral#5188]
**Describe your issue**
 I just installed Mesh Central on docker through portainer. Set it up as 444 for 443 and 8086 for 80, then proceeded to open 444 and 8086 on my router for that specific IP that runs docker. I can connect to the web GUI just fine and add stuff but I can't seem to be able to add machines with the agent. One thing I noticed is when I try to install the linux agent on one of my debian VMs, I see that it is trying to connect to the domain following an internal docker local ip:444 (and I think a cloudflare IP as well) so that would give it a timeout.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Network: LAN/WAN, docker, SSL, cloudflare
 - Version: 1.1.5
 - Node: 12.22.12

**Client Device (please complete the following information):**
 - Device: Windows Server 2012 VM, Debian VM, My personal Windows PC
 - OS: Windows 11, Windows S 2012, Debian, Docker
 - Network: LAN & WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Your config.json file**
```
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshctrl.mypersonaldomain.org",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "aliasPort": 444,
    "redirPort": 80,
    "redirAliasPort": 8086,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "",
    "WebRTC": ""
  },
  "domains": {
        "": {
        "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "",
        "_userNameIsEmail": true,
    "certUrl": "https://:"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}
```

**Comment by sherbmeister** [comment]
Marked as closed as no one is replying.

**Comment by FelpsDevilla** [comment]
I have the same problem, you managed solve?

**Comment by si458** [comment]
@FelpsDevilla you need to share your config.json so we understand what u have to explain how to fix ur issue
