### ISSUE TITLE
Mesh Commander remote desktop unable to connect NUC12WSKv5 ME v16.1.25

### ISSUE THREAD

**Issue by bleomycin** [Ylianst/MeshCentral#5197]
Mesh Commander is unable to connect to the remote desktop of my NUC12WSKv5 with ME v16.1.25. The error thrown is  "KVM disconnection, this may indicate that Intel AMT is unable to capture the display (Try RLE8 encoding), or unsupported GPU." 

I've tested every Image Encoding setting one by one with the same result. I've launched with nw.exe -debug -norefresh and nothing shows in the debug window. Most other functions of Mesh Commander seem to be functioning fine, just not remote desktop. 

debug log file attached.

Thanks for any help!

[log.txt](https://github.com/Ylianst/MeshCentral/files/11773505/log.txt)

**Comment by si458** [comment]
this is the meshcentral repo, and not the meshcommander repo
please open your issue in the correct repo https://github.com/Ylianst/MeshCommander
also please close this issue, thank you 👍
