### ISSUE TITLE
Certificate hash mismatch after upgrading to latest version

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#52]
My Windows 10 client is showing as offline in MeshCentral after I upgraded to the latest version. The log shows that there's suddenly a certificate mismatch between the agent and the server even though the certificate hasn't changed. I have reinstalled the MeshAgent and MeshCentral server from scratch but the error always shows up in the logs again.

**Comment by Ylianst** [comment]
Just published MeshCentral 0.2.4-n with ECDSA support back in the Windows agent. In addition, I added a new server setting called "IgnoreAgentHashCheck". So, add "IgnoreAgentHashCheck: true" to your config.json, update the server. Wait for all agents to be updated and remove that option.

```
{
  "settings": {
    "Port": 443,
    "IgnoreAgentHashCheck": true
  }
}
```

Seems you got your wish for the hash ignore option after all.

**Comment by whalehub** [comment]
@Ylianst I can confirm that the issue has been fixed with v0.2.4-n. While the option to ignore the hash exists now, I'm probably not going to use it since MeshCentral has full ECDSA support once again.

**Comment by whalehub** [comment]
@Ylianst This issue has unfortunately appeared again after a recent update.

**Comment by Ylianst** [comment]
Looking into this right away. I assume you are still using ECDSA certs on the reverse-proxy? The latest update added TPM support in the agent for certificate hardening. I really wanted to do this change as early as possible before people mass deploy MeshCentral. Can you confirm that placing the following line temporary fixes the issue?

`"IgnoreAgentHashCheck": true`

Thanks,
Ylian

**Comment by Ylianst** [comment]
I just tested with a ECDSA cert on NGINX and it worked for me and testing on NodeJS v6.0.0 and v10.15.0. If you have any more details with latest update (server log error?) anything at all would be appreciated. Existing machines should not change, only new installations on Windows will use TPM if present.

**Comment by whalehub** [comment]
@Ylianst Turns out it was the result of a misconfiguration in my setup. It's working fine now.

**Comment by Ylianst** [comment]
Oh thanks. I was worried because of all the changes made in the last two days. At some point, I would like the server to auto-refetch the certificate hash of the reverse proxy if agents start failing the hash test. That way, if the cert on the proxy changes, MeshCentral can automatically fix itself.
