### ISSUE TITLE
CIRA: Opening AMT remote desktop in integrated MeshCommander crashes AMT (0.4.1-m)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#520]
Hello!

I stumbled across an odd behaviour that seems to crash the ME:

I have some machines in ACM-provisioned CIRA mode.
Opening AMT is quite slow compared to AMT mode but both MeshCentral's HW desktop feature as well as the MeshCommander in MeshCentral's AMT tab work. But when I try to connect the remote desktop of the integrated MeshCommander in AMT tab, the remote desktop is partially drawn and then it is stuck. Reconnecting to remote desktop does not work, neither in MeshCentral's desktop tab nor in the AMT tab.
As soon as the integrated MeshCommander tries to refresh some data (red bar), it will get stuck, too. Reconnecting to AMT will result in timeout errors popping up either immediately or after some AMT menu items have already shown up.
After a while, MeshCentral loses the CIRA connection (only "Agent, Powered" is shown instead of "Agent, CIRA, Powered"), also the AMT ports remain are closed.

My way to revive ME/CIRA is to shut down the machine and pull the power for some seconds. After repowering the machine, CIRA connects to MeshCentral and works again.
The machines tested are vPro-enabled HP EliteDesk 800 G4 DM with i5-8500 and HP EliteDesk 800 G5 Mini with i5-9500, both running AMT 12.0.39.

Best regards,
// Veit

**Comment by Ylianst** [comment]
Hi. Can you explain this part "Opening AMT is quite slow compared to AMT mode"?

It seems like this is a Intel AMT firmware problem, can you check if a BIOS update is available for your computer?

**Comment by veitw** [comment]
Hi @Ylianst,

> Can you explain this part "Opening AMT is quite slow compared to AMT mode"?

using CIRA is simply much slower than using AMT directly for me, which I thought (you mentioned that in one of your videos about CIRA) is usual as a result of using TLS with CIRA instead of unencrypted connection with AMT.

Example:
Hitting Connect in the "Intel AMT" tab on machines that I have not connected to for a while and waiting for full sync (red progress bar disappears). Both machines are directly attached to the same network by wire.
AMT: 29 seconds
CIRA: 67 seconds

This is best noticeable when using the hardware remote console, where I regard the CIRA connection takes about 10 times longer than plain AMT to transfer and draw the full desktop.

> It seems like this is a Intel AMT firmware problem, can you check if a BIOS update is available for your computer?

The machines mentioned have the latest firmware installed that HP offers.

What makes me think this might be a MC problem is that using "Desktop" -> "HW Connect" does **not** crash the ME, but using "Intel AMT" -> "Connect" -> "Remote Console" -> "Connect" does (setting the same image encoding).

Best regards,
// Veit

**Comment by yorickvP** [comment]
Hi! I'm also noticing this. The first Remote Desktop session works, but it's not possible to reconnect. Attempting to connect again gives a [corrupted image like this](https://pub.yori.cc/s/GNZytT4dKOaC_200702160757.png). The third one stops working, and trying to get into the intel amt screen gives a Timeout Error for a few minutes.

**Comment by dinger1986** [comment]
AMT again @si458

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
