### ISSUE TITLE
How to install Beta v2 version?

### ISSUE THREAD

**Issue by marcosnegrisoli** [Ylianst/MeshCentral#5200]
How do I install version 2 beta?

I do the installation that is in the documentation, it installs the latest version. I tried to see it in npm, but apparently the package is not there.

Thanks.

**Comment by marcosnegrisoli** [comment]
In this video: https://www.youtube.com/watch?v=LSiWuu71k_U&t=67s

+- minute 3:00.

Now that I noticed that it's a very old video :/

**Comment by si458** [comment]
ah right, yes thats an old video,
it use to be called meshcentral2 but then changed to meshcentral and started from v1 andgoing up to v1.1.6 (last week)
please can you close this issue if your are happy 👍

**Comment by marcosnegrisoli** [comment]
For some reason only tech gods know, I figured this beta version was the one with support for webrtc lol.

Thank you very much for your support.

**Comment by si458** [comment]
> For some reason only tech gods know, I figured this beta version was the one with support for webrtc lol.
> 
> Thank you very much for your support.

webrtc is already supported in the latest version 1.1.6
you can check out the youtube channel for loads of helpful video
https://www.youtube.com/@MeshCentral/videos
cant remember which video shows webrtc tho haha
