### ISSUE TITLE
Remote Desktop on Mac OS X is not working when the path to meshagent contains a '&'

### ISSUE THREAD

**Issue by toronar** [Ylianst/MeshCentral#5205]
When the path to the meshagent binary on OS X contains a '&' in any part, remote desktop will close immidiately upon connecting.

**To Reproduce**
1. Go to Desktop from an OS X client
2. Click on Connect
3. it connects but immidiately disconnects again
4. the event log in meshcentral for that device shows "Remote Desktop Connection forcefully close by local user"
5. the culprit is companyName in config.json which contains the '&'
6. after I renamed the path on the client device from /usr/local/mesh_services/<companyName with &>/<filename-agent> to /usr/local/mesh_services/companyName-without&/<filename-agent> and updated the plist accordingly it works flawlessly

**Expected behavior**
It should work even when '&' is contained inside the path to meshagent on OS X.

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: none
 - Network: LAN
 - Version: 1.1.0
 - Node: v12.22.12

**Client Device (please complete the following information):**
 - Device: Mac Mini M2
 - OS: Mac OS X 13.4 (Ventura)
 - Network: LAN
 - Browser: Safari
 - MeshCentralRouter Version: not used

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 21H2
 - Network: LAN
 - Current Core Version (if known): Nov 19 2022, 143332014

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.js                                                                    on",
  "__comment1__": "This is a simple configuration file, all values and sections                                                                     that start with underscore (_) are ignored. Edit a section and remove the _ in f                                                                    ront of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for                                                                     a more advanced example.",
  "settings": {
    "cert": "meshcentral.<redacted>.local",
    "WANonly": true,
    "_LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "agentTimeStampProxy": "http://proxy.<redacted>.de:8080"
  },
  "domains": {
    "": {
      "title": "Meshcentral <redacted>",
      "title2": "meshcentral.<redacted>.local",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "altMessenging": [
        {
          "name": "Jitsi",
          "url": "https://meet.<redacted>.de/myserver-{0}",
          "localurl": "https://meet.<redacted>.de/myserver-local-{0}",
          "type": "device"
        },
        {
          "name": "Jitsi",
          "url": "https://meet.<redacted>.de/myserver-{0}-{1}-{2}-{3}",
          "localurl": "https://meet.<redacted>.de/myserver-local-{0}-{1}-{2}-{3                                                                    }",
          "type": "user"
        }
      ],
      "agentCustomization": {
        "displayName": "<redacted> Remoteagent",
        "description": "<redacted> Remoteagent for remote monitoring, managemen                                                                    t and assistance.",
        "companyName": "<redacted>GMBH & CO KG",
        "serviceName": "<redacted>-agent",
        "fileName": "<redacted>-agent"
      }
    }
  },
 
  "smtp": {
    "host": "mail.<redacted>.de",
    "port": 25,
    "from": "meshcentral@<redacted>.de",
    "tls": false,
    "tlscertcheck": false,
    "tlsstrict": false
  }
}
```

**Comment by si458** [comment]
Plz can u try the pkg in the new release of 1.1.22
