### ISSUE TITLE
Discord Messaging No Longer Functions With New Username Format

### ISSUE THREAD

**Issue by anthonyb800** [Ylianst/MeshCentral#5207]
**Describe the bug**
Discord messaging no longer functions with new Discord username format (no #numbers at the end of username)

**To Reproduce**
1. If you have Discord messaging previously setup, it will fail to send a DM to you with an auth code.
2. If you do not have Discord messaging setup and have the new username format (no #xxxx at the end), it will not allow you to setup messaging in MeshCentral. It depends on those 4 numbers it seems.

**Expected behavior**
Be able to enter the new Discord username format without the 4 numbers at the end to be able to setup messaging.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Network: Cloudflare
 - Version: 1.1.6
 - Node: 18.16.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Network: WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Comment by si458** [comment]
Development is at a standstill at the moment 

If you can fix the issue yourself and submit a pr, that would be amazing!

Other than that, the community member will have a look in their free time for you

**Comment by si458** [comment]
just going to look at this for you,
just to clairfy, (example)
my user is `abc#123` i would use `abc#123` IF i havent converted to the new username without numbers
but my new user could be `xyz` without numbers,
if my user was `abc#123` and i converted it to `abc` would i still look up my old user `abc#123` or the new user `abc` 
?

**Comment by anthonyb800** [comment]
> just going to look at this for you, just to clairfy, (example) my user is `abc#123` i would use `abc#123` IF i havent converted to the new username without numbers my new user could be `xyz` without numbers, so i would search for `xyz` but if my user was `abc#123` and i converted it to `abc` could i still look up my old user `abc#123` or do i use the new user `abc` ?

Thanks! I would love to look into this but lack of knowledge is preventing me from finding anything useful. My understanding is that once you convert to the new username format, the old one will redirect to you for friend requests, but that is all. They are not tied together in any other way as far as I know.

So, if my username was `abc#123` and now it is `xyz` - someone could send a friend request to `abc#123` and it would redirect it to `xyz`. But it seems the same doesn't go for messaging.

In MeshCentral, it will allow you to input your new username without the # numbers at the end, but when trying to get it to send a message, it will fail. If you put your old username, like `abc#123` - it will also fail to send a message. So that tells me there is no message redirect happening with the old>new usernames. I'm sure something changed on Discord's side for how usernames are formatted for sending messages via a bot, but I don't know what exactly has changed.

**Comment by anthonyb800** [comment]
> @anthonyb800 I've been able to fix the verify ur discord, Just need to fix the sending message to your discord now It just sends u a direct message doesn't it? It doesn't post to a channel in ur server?

That's great news. And yes correct, it sends you a direct message with the code.

**Comment by si458** [comment]
all fixed @anthonyb800
planning to release once a month now so will be merged with other bug fixes next month!

**Comment by anthonyb800** [comment]
> all fixed @anthonyb800 planning to release once a month now so will be merged with other bug fixes next month!
> 
> NOTE: as a work around for the moment, you can in theory use `USERNAME#0` if you have migrated to username only

Wow thanks! Had no idea the #0 would work as a workaround, but it works just fine. Really appreciate you looking into this.
