### ISSUE TITLE
In "top bar interface" mode, opening a single device node does not update top bar (0.4.1-p)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#521]
When MC runs in top bar interface mode and one opens a device in a new tab (left-clicking on a device holding shift), the top bar in the new tab should show the device's "General", "Desktop", "Terminal", ... tabs. Instead the upper top bar's items are shown ("My Devices", "My Account", ...) and one is unable to switch to the device's desktop etc.

When in fixed width interface mode, the device's top bar is correctly show but the upper top bar showing "My Devices", "My Account", ...) remains (which I suppose is unintended).

In the default left bar interface mode, everything looks reasonable in new device tabs.

**Comment by Ylianst** [comment]
Oh. Thanks for reporting that. Yes, I see the problem.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-q with a fix for this. I also fixed a bunch of related things with browser tabs. One bug I noticed is that if you open a separate tab and to remote desktop and full screen, it would not show up right. That is also fixed. Can you test and make sure it works for you? Thanks.

**Comment by veitw** [comment]
Hi @Ylianst,
I just updated to 0.4.1-r and the problem is solved for both top bar view and fixed width view.
Thank you very much. :)
Best Regards,
// Veit
