### ISSUE TITLE
Custom Service and Company Name per Device Group

### ISSUE THREAD

**Issue by prononext** [Ylianst/MeshCentral#5211]
Is there any interest on having a custom service name and company name per device group?

I guess most times a service provider does not use the multi domain feature to manage clients as it is a hassle to switch between domains and there is no real centralized view over several clients, therefor most use groups to manage clients inside a MeshCentral service provider instance. 

It would be really nice if there would be a possibility to specify the companyName and serviceName inside a Device group.
It should be a extra permission as this setting is quite sensitive but the goal would be that for instance on a windows machine when the companyName is "Example Inc" and the  serviceName would be "support-agent" the service would be installed on:

C://Program Files/Example Inc/support-agent.exe

Let me know what you think about that and have a great day.

**Comment by Ylianst** [comment]
That is not possible, but you can set a different custom service name and company name for different MeshCentral domains. I have a video on how to [setup domains here](https://www.youtube.com/watch?v=eqInqM9olXA). Then, for each domain you can put different logos, policies, agent service names and more. Each domain will have it's own set of users.
