### ISSUE TITLE
Bugs in Desktop Monitoring

### ISSUE THREAD

**Issue by wizarddev038** [Ylianst/MeshCentral#5213]
Hello, Ylian. I worked on Meshcentral recently and found some interesting issue.

When I change "Scaling" section in settings of desktop, the screen is sometimes cut and I can't see the bottom part of the screen. Could you give some guidelines of how to fix it? My OS is windows 10 and I'm using console mode agent.

Here are the screenshots of what I was doing.
![Screenshot_3](https://github.com/Ylianst/MeshCentral/assets/129702384/5de7dfe6-1b18-4a07-ac1a-e2cab1f5ef8d)
![Screenshot_4](https://github.com/Ylianst/MeshCentral/assets/129702384/2d44c180-f788-4599-9214-00f9bfa2df76)
![Screenshot_5](https://github.com/Ylianst/MeshCentral/assets/129702384/364b68d7-e046-4362-b1bb-c4a22b26b182)
![Screenshot_6](https://github.com/Ylianst/MeshCentral/assets/129702384/1c68ad99-f2f4-4180-8648-4f4f45ade37a)

Regards

**Comment by si458** [comment]
when you say 'console mode agent' do you mean you are clicking 'connect' or the 'rdp connect' ?
i think when you change the scaling, you need to 'disconnect' and then 'reconnect' for it to rescale correctly

**Comment by wizarddev038** [comment]
Could you do it automatically so that it can be comfortable to change scale?

**Comment by wizarddev038** [comment]
I found the reason. It is made because of JPEG compression and canvas size. I changed SCALED_WIDTH of agent and solved the problem.

**Comment by jirijanata** [comment]
Can you please close your bug report, if you found some workaround?

You can also write here detailed solution for other users. Thanks!

**Comment by wizarddev038** [comment]
Can I pull my project?

**Comment by jirijanata** [comment]
Of course. The merge take usually a few days, because Ylian is not working full time on MeshCentral anymore.

**Comment by wizarddev038** [comment]
I once sent pr to Ylian on Meshagent and it's still pending. I'd be grateful if you take care of it. Thank you.
I'll send pr in a few days.
