### ISSUE TITLE
Problem with mouse cursor blinking when remote controlling desktop

### ISSUE THREAD

**Issue by wizarddev038** [Ylianst/MeshCentral#5215]
Hello, everyone. Thank you very much for creating such an amazing remote control system. I've been using it for about 2 months now and I'm really thrilled about the project.

Recently I discovered mouse cursor blinking error in the project. I studied the project and found out that agent was using CAPTUREBLT option when capturing the desktop. This was the cause of the mouse blink and I solved the problem by deleting this option.

I hope my solution would be helpful to all our users. Regards

**Comment by si458** [comment]
This issue already exists 

https://github.com/Ylianst/MeshCentral/issues/3663

Please can you close this issue and follow in the other issue

Also post ur findings as I don't believe they found the issue in the old issue

**Comment by wizarddev038** [comment]
Sorry, Simon.
