### ISSUE TITLE
Agent Error - When sharing device when closing the toolbar does not disconnect the shared desktop

### ISSUE THREAD

**Issue by xanpri** [Ylianst/MeshCentral#5216]
In device sharing, using the device sharing link, on the client side, when he closes the toolbar, remote access to the shared desktop does not disconnect and that way whoever is doing the remote access continues to view the remote desktop without the customer is aware that their desktop is still shared. This is happening on both Windows and Linux client OS.

The expire time is working, when the time is up it disables sharing.

I was able to verify that even the stable version of MeshCentral 1.0.0 is working correctly and that from the stable version 1.1.0 this functionality stopped working.

Error Console Agent: 
<html>
<body>

uncaughtException1: Error: child_process.subProcess.exit():  => EventEmitter.emit(): Event dispatch for 'exit' on 'childProcess.subProcess' threw an exception: EventEmitter.emit(): Event dispatch for 'close' on 'unknown' threw an exception: ReferenceError: identifier 'state' undefined in method '()' in method '()'

<br class="Apple-interchange-newline">
</body>
</html>

Share:
![image](https://github.com/Ylianst/MeshCentral/assets/73598277/a59106c6-ce9a-41af-9a72-e240fafc8f22)

Link:
![image](https://github.com/Ylianst/MeshCentral/assets/73598277/6c9dc210-b4ee-4beb-9748-8e5fb056f5c2)

Close Toobar:
![image](https://github.com/Ylianst/MeshCentral/assets/73598277/d3c37275-38c9-4996-ae2c-3e0eb2b7e697)

Link share device still working without disconnecting:
![image](https://github.com/Ylianst/MeshCentral/assets/73598277/34e2cbe2-974a-44f2-8b86-f67edbcfff53)

**Comment by si458** [comment]
this isnt specific to the remote sharing option
i have noticed this too during normal use
sometimes i connect with the toolbar to let the users know im connected,
but then if i remotely click the X button in the toolbar, i stay connected?
i think its a bug in agent software

i found that sometimes if i click the X remotely this happens, BUT if i ask the user to click the X it then disconnects

**Comment by xanpri** [comment]
@si458 

I found that this behavior is also occurring.

And it's the same error in the agent's cosole:

uncaughtException1: Error: child_process.subProcess.exit(): => EventEmitter.emit(): Event dispatch for 'exit' on 'childProcess.subProcess' threw an exception: EventEmitter.emit(): Event dispatch for 'close' on 'unknown' threw an exception: ReferenceError: identifier 'state' undefined in method '()' in method '()'
