### ISSUE TITLE
Tablet don`t show keyboard options

### ISSUE THREAD

**Issue by pperboz** [Ylianst/MeshCentral#5217]
**Describe the bug**
When I open meshcentral from a tablet device, going full screen doesn't give me keyboard and mouse options

**To Reproduce**
switch to full screen on mobile and tablet

**Expected behavior**
I expect to have a keyboard options to write when i use a tablet 

**Screenshots**
This is the keyboard menu that don't aprears on tablet
![Imagen de WhatsApp 2023-06-28 a las 23 36 12](https://github.com/Ylianst/MeshCentral/assets/37489543/89d9b691-cfea-4f4e-a452-7318a9ee5c94)

The tablet on full screen don't show keyboard menu. It's like the desktop environment
![IMG_20230629_010956](https://github.com/Ylianst/MeshCentral/assets/37489543/495e6fe5-5ab2-417c-9b05-3ec7d06597af)

**Comment by si458** [comment]
we need to see a screenshot of your tablet screen,
you also click the keyboard icon to make the keyboard appear?

**Comment by pperboz** [comment]
Hi. Here you can see the difference tablet vs mobile. It's like the tablet is working on desktop mode. 

![Screenshot_20230629_010459_Chrome](https://github.com/Ylianst/MeshCentral/assets/37489543/750d3c88-40a2-4d7e-8a87-7bc1fdbcc6d2)
![IMG_20230629_010357](https://github.com/Ylianst/MeshCentral/assets/37489543/32b8fdcb-102a-4c2a-979a-8b408f3c91c7)

**Comment by si458** [comment]
What tablet are you using?
What's the browser?

**Comment by pperboz** [comment]
On full screen the mobile give me the keyboard and mouse menú. But the tablet don't show anything, like the desktop. 

Mobile full screen
![Screenshot_20230629_010929_Chrome](https://github.com/Ylianst/MeshCentral/assets/37489543/6a0472ec-bc92-49f5-bf5b-1ac4846731a6)

Tablet full screen
![IMG_20230629_010956](https://github.com/Ylianst/MeshCentral/assets/37489543/40f997f8-b9b0-4923-bdc5-242390b2831d)


Can I force mobile mode??? I have tried to downgrade the tablet resolution but don't solve the problem.

**Comment by pperboz** [comment]
Lenovo tab 3.

I'm trying chrome and android-kiosk browser

**Comment by pperboz** [comment]
Solved!!!!

I have changed the user agent and works fine!!!

![IMG_20230629_013919](https://github.com/Ylianst/MeshCentral/assets/37489543/59da82d4-cab9-4bd6-9d04-8f6e781c8227)

**Comment by pperboz** [comment]
As we say in spain. "Mi gozo en un pozo"

The keyboard menu apears, the keyboard opened when i press, but dont write!!!!!
