### ISSUE TITLE
Auto backups with NeDB

### ISSUE THREAD

**Issue by Typhonragewind** [Ylianst/MeshCentral#5218]
Quick question, are autobackups supposed to work with NeDB usage? because no matter what configuration I've tried, i can't get it to auto save any files in the designated location.

**Comment by Ylianst** [comment]
NeDB places it's database files in the "meshcentral-data" folder and by default, MeshCentral should backup that folder to "meshcentral-backups" everyday. So, if you see a daily `meshcentral-autobackup-2023-xx-xx-xx-xx.zip` file in "meshcentral-backups" and the zip file includes "meshcentral.db", you should be fine.

**Comment by dinger1986** [comment]
@si458 can close fix has been done

**Comment by si458** [comment]
can confirm autobackups for nedb all work fine now in 2023
