### ISSUE TITLE
Agent certificate issue with Own Certificate 

### ISSUE THREAD

**Issue by qsayeed** [Ylianst/MeshCentral#5221]
Hello,

We have our own certificate. So replaced the below existing Meshcentral certificate with our own.

- agentserver-cert-private.key
- agentserver-cert-public.crt
- webserver-cert-private.key
- webserver-cert-public.crt

Note: Here both crt file are same, only the name changed. and same with key.

By these change, certificate error on meshcentral site has fixed. But while installing agent on Linux machine... it gives below certificate warning.

_WARNING: The certificate of ‘rdm.XYZ.com’ is not trusted.
WARNING: The certificate of ‘rdm.XYZ.com’ doesn't have a known issuer._

Can anyone tell me ... what I did wrong.. and how to fix it

**My config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment__": "This is a sample configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "cert": "rdm.XYZ.com",
    "mongoDb": "mongodb://127.0.0.1:27017",
    "mongoDbName": "meshcentral",
    "_mongoDbChangeStream": true,
    "WANonly": false,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_sessionSameSite": "strict",
    "_certificatePrivateKeyPassword": [ "password1", "password2" ],
    "_dbEncryptKey": "MyReallySecretPassword2",
    "_dbRecordsEncryptKey": "MyReallySecretPassword",
    "_dbRecordsDecryptKey": "MyReallySecretPassword",
    "__dbExpire": "Amount of time to keep various events in the database, in seconds. Below are the default values.",
    "_dbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    },
    "port": 443,
      ........
}
```

**Comment by si458** [comment]
what type of certificate is it?
is it a web certificate or code signing?
if its a web certificate, you only needed to replace `webserver-cert-private.key` and webserver-cert-public.crt` and make sure `cert` in `config.json` matches the certificate

**Comment by qsayeed** [comment]
Oh, It was web certificate and by mistake I replaced both webserver and agent with this.

1. Does replacing agent certificate is the reason of that warning?
2. Is there any way to regenerate the agent certificate as I lost the original.

Thanks @si458 for quick response.

**Comment by OutbackMatt** [comment]
If this was a self signed cert, I'd trash and start again.
You will need your Linux machine to accept the self signed cert.

If this was a purchased cert, download what you need from the supplier

**Comment by qsayeed** [comment]
Deleted the agent certs and restarted the meshcentral. It has generated the agents certs. Thats works fine.

But when I tried to install the agent using below command, 

_(wget "https://rdm.XYZ.com/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || wget "https://rdm.XYZ.com/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo -E ./meshinstall.sh https://rdm.XYZ.com '9FFJLpTBR7tcyTRD8DLk@VcJ1OtiOS2xAZT7TlqVXPQ11gnBW4gicpvV@7x6y6@x' || ./meshinstall.sh https://rdm.XYZ.com '9FFJLpTBR7tcyTRD8DLk@VcJ1OtiOS2xAZT7TlqVXPQ11gnBW4gicpvV@7x6y6@x'_

it again gave me same warning:

_WARNING: The certificate of ‘rdm.XYZ.com’ is not trusted.
WARNING: The certificate of ‘rdm.XYZ.com’ doesn't have a known issuer._

Is there any further steps to be followed?

Note: The webserver certs is not a self signed certs.

**Comment by si458** [comment]
Just try running the command from a new empty folder as it might be using the original binary and config it downloaded previously

**Comment by qsayeed** [comment]
Created new folder on Desktop and ran the one wget command... here is the output

**pi@ADIGURRPI03:~/Desktop/qt $** _wget "https://rdm.XYZ/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh_
--2023-07-04 15:49:56--  https://rdm.XYZ.com/meshagents?script=1
Resolving rdm.XYZ.com (rdm.XYZ.com)... 10.xx.xx.xx
Connecting to rdm.XYZ.com (rdm.XYZ.com)|10.xx.xx.xx|:443... connected.
WARNING: The certificate of ‘rdm.XYZ.com’ is not trusted.
WARNING: The certificate of ‘rdm.XYZ.com’ doesn't have a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 5466 (5.3K) [application/octet-stream]
Saving to: ‘./meshinstall.sh’

./meshinstall.sh    100%[===================>]   5.34K  --.-KB/s    in 0s      

2023-07-04 15:49:57 (62.5 MB/s) - ‘./meshinstall.sh’ saved [5466/5466]

**Comment by si458** [comment]
That warning means the https web server certificate is incorrect/selfsigned
Can you visit the url in ur webbrowser?
Do you get a certificate warning?

**Comment by qsayeed** [comment]
1. When I open _https://rdm.XYZ_, in Chromium. It says **Certificate is valid** with below certificate information 

Issued By:
  Common Name (CN)	Entrust Certification Authority - L1K
  Organisation (O)	Entrust, Inc.
  Organisational Unit (OU)	See www.entrust.net/legal-terms

Validity Period:
  Issued On	Monday, 3 April 2023 at 11:53:45
  Expires On	Friday, 3 May 2024 at 11:53:45

2. And when I hit _https://rdm.XYZ/meshagents?script=1_, It says **Your connection to this site is not secure**

**Comment by si458** [comment]
Weird? Can you do a `curl -v MESHAGENT URL` and show us the output? It might be redirecting wrong

**Comment by qsayeed** [comment]
Here is the output:

**pi@ADIGURRPI03:~/Desktop/qt $ curl -v https://rdm.XYZ.com/meshagents?script=1**
*   Trying 10.xx.xx.xx...
* Connected to rdm.XYZ.com (10.xx.xx.xx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by si458** [comment]
what about output from just `curl -v https://rdm.XYZ.com/` ?

**Comment by qsayeed** [comment]
It looks like same:

**pi@ADIGURRPI03:~/Desktop/qt $ curl -v https://rdm.XYZ.com/**
*   Trying 10.xx.xx.xx:443...
* Connected to rdm.XYZ.com (10.xx.xx.xx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by si458** [comment]
this means the HTTPS certificate hasnt been applied correctly OR curl certificates are out of date
your `webserver-cert-private.key` should be like
```
-----BEGIN RSA PRIVATE KEY-----
LOADSOFVERYLONGRANDOMSTRINGS
-----END RSA PRIVATE KEY-----
```
and your `webserver-cert-public.crt` should look like
```
-----BEGIN CERTIFICATE-----
LOADSOFVERYLONGRANDOMSTRINGS
-----END CERTIFICATE-----
```
if your web browser can goto the login page with no issues/warning then the certificate is ok and its curl thats the issue
what is the OS you are using to install the agent on?
check you have the latest `ca-certificate` installed on the computer you are trying to install meshagent on
you can also try adding the CA certificate (not ur certificate but the company u got the certificate from)
after your certificate in `webserver-cert-public.crt`

**Comment by qsayeed** [comment]
**webserver-cert-private.key** content is same as you mentioned.

But **webserver-cert-public.crt** looks like below:


```
Bag Attributes
    localKeyID: 01 00 00 00 
    friendlyName: rdm.XYZ.com
subject=/C=DE/ST=Bayern/L=Herzogenaurach/O=adidas AG/CN=rdm.XYZ.com
issuer=/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
-----BEGIN CERTIFICATE-----
LOADSOFVERYLONGRANDOMSTRINGS
-----END CERTIFICATE-----
```

**Comment by si458** [comment]
so you need to remove 
```
Bag Attributes
    localKeyID: 01 00 00 00 
    friendlyName: rdm.XYZ.com
subject=/C=DE/ST=Bayern/L=Herzogenaurach/O=adidas AG/CN=rdm.XYZ.com
issuer=/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
```
it should only contain the the certificate section as mensioned above
once you have removed the extra stuff that isnt needed, restarted meshcentral wait 1min and away you should go :)

**Comment by qsayeed** [comment]
The only things which worked by now is downloading Entrust root and intermediate certificates from https://www.entrust.com/resources/certificate-solutions/tools/root-certificate-downloads on the device. And then including certs path in wget, Like:

wget "https://rdm.XYZ.com/meshagents?script=1" --ca-directory=~/Desktop/entrust_certs

Will check further how to install this certificate on RPI, to avoid path option in wget command.
