### ISSUE TITLE
Black Screen KVM 

### ISSUE THREAD

**Issue by ryanatigd** [Ylianst/MeshCentral#5225]
Describe your issue
My issue is when you issue a send a Reset operations to Intel amt device , when the device restarts the device can't be accessed via mesh central for kvm. It still works for our remote management software. Any way to troubleshoot this or any possible fixes.

Server Software 
 - OS: Ubuntu
 - Network:  LAN/WAN, reverse proxy, cira
 - Version: "v1.1.6"
 - Node: "v12.22.9"

Client Device 
 - Device: Dell Desktop
 - OS: Windows 10/11
 - Network:  Local to Meshcentral
 - Browser: Chrome , firefox, edge 

Remote Device 
- Device: Laptop/desktops
 - OS: Windows 10/11
 - Network:  Remote over WAN
 
**Your config.json file**
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "tvcmcs.igd.au",
    "certurl": "https://tvcmcs.igd.au/cert.pem",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "webRTC": false
},
  "domains": {
    "tvcmcs.igd.au": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "passwordRequirements": {
        "force2factor": true
      }
   }
},
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "support@igd.com.au",
    "names": "tvcmcs.igd.au",
    "production": true
   }
}

**Comment by si458** [comment]
have u checked if ubuntu is using wayland?
if so you need to disable it as its not fully supported yet
https://help.realvnc.com/hc/en-us/articles/4417193011857-How-do-I-disable-Wayland-to-use-RealVNC-Connect-#which-linux-distributions-use-wayland--0-1

**Comment by si458** [comment]
closing as stale,
please update to the latest version 1.1.21 and use node 18 or above,
if issue persists, please reply back
