### ISSUE TITLE
Site "not secure" in Google Chrome with valid certificate

### ISSUE THREAD

**Issue by bcnx** [Ylianst/MeshCentral#5232]
Hi,

My Meshcentral install has a valid and official certificate (verified with SSL tools)

![Selection_226](https://github.com/Ylianst/MeshCentral/assets/7941528/8ca827c2-c4dc-4b87-8c68-66856115f595)

Firefox or Brave do not have this problem.

 - OS: Debian 11
 - Virtualization: no
 - Network: WAN
 - Version: v1.1.6
 - Node: v20.4.0

 - Device: laptop
 - OS: Linux Mint
 - Network: Remote over WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "cert": "meshcentral.bnt.solutions",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment]
Have u tried CTRL+F5? Shows verified/valid here OK?

**Comment by bcnx** [comment]
Hi, yes,tried CTRL-F5. Do you use Google Chrome? My version is a bit out-f-date, that could be the issue.

**Comment by si458** [comment]
Tried both chrome and Firefox on android, works fine, maybe try updating ur chrome and ca-certificate on the os

**Comment by bcnx** [comment]
I added an intermediate record named webserver-cert-chain1.crt where I put the CA-bundle in, but that does not help. I will update Chrome and try again. Thanks for testing, if you have no problem, there probably is no problem.

**Comment by bcnx** [comment]
Hi, it was fixed by updating Chrome.
