### ISSUE TITLE
Send notification to agent when consent value changes & add consent value to Agent Invite Mail

### ISSUE THREAD

**Issue by rallisf1** [Ylianst/MeshCentral#5234]
**Is your feature request related to a problem? Please describe.**
I have started providing IT support to random folks with MeshCentral and I get asked a lot about what kind of access I have to their devices and how they can keep their privacy intact. Obviously my word doesn't mean much to people I just met and you can't expect anyone to go through the documentation, let alone the source code, to figure it out themselves (Although I could be using an unsafe private repo for all they know).

**Describe the solution you'd like**

1. Add `[[[CONSENTVALUES]]]` to the [agent invite mail](https://github.com/Ylianst/MeshCentral/blob/53e2c5cf69d3704004f50213808124c045d402df/meshmail.js#L332C9-L332C28) and [template](https://github.com/Ylianst/MeshCentral/blob/53e2c5cf69d3704004f50213808124c045d402df/emails/mesh-invite.html)
2. Send a notification to the agent whenever a consent value affecting his device changes

P.S. I will likely implement this myself just leaving it here for reference.

**Comment by si458** [comment]
This is more of a remote management feature
Please look at Tacticalrmm instead
