### ISSUE TITLE
No systemd script created on Debian 12 or Ubuntu 22.04

### ISSUE THREAD

**Issue by bcnx** [Ylianst/MeshCentral#5236]
Hi,

using the agent script on systemd script is added to the system. Running the agent manually works, but there seems no mechanism to start it up automatically. Some internet posts point to meshagent.service but I don't have this file. I have no log installation files either. Not sure where to look. The install file successfully identifies the system as a systemd one.

Thanks!

**Server Software (please complete the following information):**
 - OS: Devian 11
 - Virtualization:
 - Network: WAN
 - Version: latest 
 - Node: 20.4.0

**Client Device (please complete the following information):**
 - Device: laptop
 - OS: Linux Mint 21
 - Network: Remote over WAN
 - Browser: Chrome

**Remote Device (please complete the following information):**
 - Device: different servers
 - OS: Debian 12 and Ubuntu 20.04 LTS
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Comment by si458** [comment]
how did you install the agent software?
did you download the binary Installer file or did you use the install script?
the install script will automatically install the systemd file it needs for start up
where as i believe the binary installer file is just the application to run to allow access to the computer you have to do your own aut-startup file etc

**Comment by bcnx** [comment]
I used the install script starting with "(wget)". It did not install any systemd files and I also cannot find this in meshinstall.sh . There seems to be no code there that creates a systemd service script. 
I tried this on 3 servers. Not sure where it goes wrong.

**Comment by si458** [comment]
have u customised the agent at all in `config.json`?
if you have you might not be looking for `meshagent.service` it might be called something else like `supportagent.service`
if you try running the whole command in a empty folder, does it download files?
whats the output from running the command? (hide the server/long string for privacy)

**Comment by bcnx** [comment]
Yes, the agent has been fully configured in config.json. I did use a company name with a single quote in the name, I hope that is not a problem. A binary is created like this:

/usr/local/mesh_services/Bits '$'\'''n Tricks/BitsnTricksRemoteSupportAgent/bntagent

When I launch that one, the agent is added in Meshcentral and I can remote control it.

It downloads 3 files: 
`-rwxr-xr-x 1 root root 3749328 Jul  6 01:23 meshagent
-rw-r--r-- 1 root root   29605 Jul 11 22:18 meshagent.msh
-rwxr-xr-x 1 root root    5466 Jul 11 22:18 meshinstall.sh

The installer shows these last lines:

`...Checking for previous installation of "BitsnTricksRemoteSupportAgent" [FOUND: /usr/local/mesh_services/Bits 'n Tricks/BitsnTricksRemoteSupportAgent/bntagent]
   -> Uninstalling previous installation... [DONE]
   -> Checking for secondary agent... [NONE]
...Installing service [DONE]
   -> Starting service... [OK]
`

`

**Comment by si458** [comment]
the issue is the special characters in the name!
try changing your company/product name to not include special characters ` ! " £ $ % ^ & * ( ) @ ' # } { / ? > < ~ `
then let it rebuild the agent, redownload the new agent then try again

**Comment by si458** [comment]
the was another issue in the past that might be open/closed with the same issue and the is currently no way to fix it because of systemd phasing the characters

**Comment by bcnx** [comment]
OK, cheers, removing the single quotes has fixed it. I copied the agent info to all my domains, so nothing basically worked. It seems OK now, thanks for the suggestion,

BC

**Comment by si458** [comment]
> I copied the agent info to all my domains, so nothing basically worked. It seems OK now

glad its sorted! i would recommend just editing the `config.json` to fix the naming, restart meshcentral to rebuild the agent, then use the new url install links from the web ui

**Comment by bcnx** [comment]
yes, that was how I just tested,

BC

**Comment by si458** [comment]
plz close this issue if your issue is resolved 👍

**Comment by bcnx** [comment]
done.
