### ISSUE TITLE
2 factor authentication with multi-tenant setup

### ISSUE THREAD

**Issue by bcnx** [Ylianst/MeshCentral#5238]
Hi,

I have a multi-tenant setup using subfolders, for instance:

meshcentral.example.com/client1
meshcentral.example.com/client2
meshcentral.example.com/client3
...

While adding QR codes for each instance, they all have the same name. I also use the same username for each instance. When I change the username in the Google Authenticator app, it gets changed for each instance. So there is no real option for me to discern one account from the other. Is changing the username the only option?

Cheers,

BC

**Comment by si458** [comment]
Subfolders are not supported in meshcentral !!!

You must use subdomains and set them in your `config.json`

http://company1.meshserver.com
http://company2.meshserver.com
etc...

**Comment by bcnx** [comment]
From the documentation on https://ylianst.github.io/MeshCentral/meshcentral/ , I see that multi-tenancy config happens like this:

`In the domains section, you can set options for the default domain ("") in addition to creating new domains to establish a multi-tenancy server. For standard configuration, the root domain and other domains will be accessible like this:

https://servername:8080/ <- default domain

https://servername:8080/customer1 <- customer1 domain

https://servername:8080/customer2 <- customer2 domain`

So I'm not sure why this would not be supported?

**Comment by si458** [comment]
Subfolders are not supported in meshcentral !!!
please provide a link to where you see this

You must use subdomains and set them in your config.json

http://company1.meshserver.com/
http://company2.meshserver.com/
etc...

**Comment by bcnx** [comment]
That is highly unfortunate and will force me to do my setup completely again. Some clients already received their QR code. Also, my certificate is not usable anymore and a wildcard certificate will be needed. 

It is surprising to me though that everything still works in the so called unsupported way. I wonder if I will need to change config.json or not. To my understanding it should work as is.

BC

**Comment by si458** [comment]
i dont use multi-tenant sadly so i cant be sure
but from past posts ive read, subfolders where not supported and it needs to be dns name based
but i could be mistaken (ill hold my hands up!)
the is a video about subdomain support tho - https://www.youtube.com/watch?v=eqInqM9olXA

**Comment by bcnx** [comment]
I will look at the video. It would be good that someone "official" could chime in to confirm the correct info. The video is 1 year old, so I cannot do any estimations on the actuality.

**Comment by si458** [comment]
i stand corrected then!
forgive my ignorance!
so your issue with 2 factor and multi-tenant, still stands

**Comment by bcnx** [comment]
I think the conclusion is then that both ways are supported, with pros and cons. My biggest con then is the naming in the Authenticator app. But maybe there are apps with more configuration options.

**Comment by si458** [comment]
i use bitwarden,
login on website, save user+pass, then use mobile app to edit the entry just created and add 2fa by scanning the qr code, and save
it all types it in and copy+paste the 2fa code hehe

**Comment by bcnx** [comment]
Copy/paste? you then use MeshCentral on your smarthpone??

BC

**Comment by si458** [comment]
going to look at this again over the weekend, can you share your `config.json` (hide secret stuff)
what app are u using for the 2fa? did you want each instance to show the name of the company or the server?

**Comment by si458** [comment]
currently it generates the following format
`otpauth://totp/SERVERDOMAINHERE:USERNAME?secret=LONGSECRETHERE&issuer=SERVERDOMAINHERE` which is correct
so the only thing we can change really is the SERVERDOMAINHERE to maybe SERVERDOMAINHERE/SUBDOMAIN ?
ill have to try for you
https://github.com/google/google-authenticator/wiki/Key-Uri-Format
https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html

**Comment by si458** [comment]
bump @bcnx would my above post be ok for ur setup?

**Comment by si458** [comment]
bump @bcnx would my above post be ok for ur setup?

**Comment by si458** [comment]
added / fixed 2024
