### ISSUE TITLE
Simple agent question - Scheduled restart

### ISSUE THREAD

**Issue by Otsegox** [Ylianst/MeshCentral#5239]
We have noticed that the agent tends to just stop reporting its power status, and sometimes not connect to the server.
I would like to have the agent restart itself, lets say once a week.   We have been using the following script to force it, but its a paint o manually do.  Would like it to just restart itself, to stay nice and fresh.

```
:Start
cls
@echo off

REM ------------------------------
REM [ Restart Mesh Agent Service ]
REM ------------------------------

Set /P "Computer=Enter the Computer Name: "

winrs -r:%Computer% "taskkill /f /im meshagent.exe && net start "mesh agent""

Goto End

:End
```

**Comment by si458** [comment]
if its windows create a script to stop then start the service and create a windows task for it
https://support.pelco.com/s/article/Configure-a-Windows-service-to-restart-on-a-schedule-using-Task-Scheduler-1538586706677?language=en_US

**Comment by Otsegox** [comment]
> if its windows create a script to stop then start the service and create a windows task for it https://support.pelco.com/s/article/Configure-a-Windows-service-to-restart-on-a-schedule-using-Task-Scheduler-1538586706677?language=en_US OR save ur script you have somewhere then call it from a task scheduled

The thing is, I have roughly 300 agents. Haven't figured out an automated way to "push" a scheduled task to that many machines. I was just hoping for something built-in. If it doesn't exist, I understand.

**Comment by si458** [comment]
if the agents are in domain network and u have control over them then you can use powershell and psexec to remotely run the powershell add schedule task remotely
https://www.makeuseof.com/windows-powershell-scheduled-task/
