### ISSUE TITLE
Chrome Autofills Filter Constantly

### ISSUE THREAD

**Issue by DovieW** [Ylianst/MeshCentral#5241]
Chrome is constantly autofilling the filter field in the My Devices tab. It fills it with my username.

**Server Software (please complete the following information):**
 - OS: Linux Mint
 - Virtualization: Docker
 - Network: WAN, Reverse Proxy
 - Version: 1.1.6
 - Node: 

I labeled this a question since I don't know if this is a bug or feature request. There is no way in Chrome to disable autofill it seems.

**Comment by si458** [comment]
the isnt much you can do, as we already set the `autocomplete=off` so chrome should honer it
but i have the issue with bitwarden too from time to time
https://github.com/Ylianst/MeshCentral/blob/master/views/default.handlebars#L317

**Comment by DovieW** [comment]
right i figured.
I'm going to start using this [greasyfork script](https://greasyfork.org/en/scripts/470834-meshcentral-prevent-filter-autocomplete) to see if new-password will work better than off. I'll report here if it works.

**Comment by DovieW** [comment]
It didn't work. This is really quite annoying, I have to speed run clicking on the machine before the filter is autofilled.

**Comment by DovieW** [comment]
I've created bookmarks to my must used machines

**Comment by DovieW** [comment]
just realized i can fill the filter with my own text to stop it. duh
