### ISSUE TITLE
Connect Button is missing and cant see Desktop, Terminal and Files menu.

### ISSUE THREAD

**Issue by thrimurthula** [Ylianst/MeshCentral#5244]
My Ubuntu phyiscal machine doesnt have a montior connected to it and i cant connect to it
as i cant see the connect button as there is no Desktop, Terminal and Files menu.

In /etc/gdm3/custom.conf file:
In addition to WaylandEnable=false which was already there
I also added the following underneath it:
DefaultSession=gnome-xorg.desktop

 - OS: [Ubuntu 20.04]
 - Virtualization: VPS server in cloud
 
**Remote Device (please complete the following information):**
 - Device: Physical Machine Dell R340
 - OS:[Ubuntu 20.04]
 - Browser: [Google Chrome]

**Comment by si458** [comment]
you can try clearing the core and re-uploading it
goto the device, then to console tab
click agent action, select 'clear the core'
wait 10 seconds,
then clock agent action again, select 'upload default core'

see if the tabs re-appear
