### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by Ronnyhe96** [Ylianst/MeshCentral#5247]
It takes a long time to see a newly configured device in windows and linux.
It does not appear to download mobile agent.
And I also can't see the screen of linux,ubuntu,fedora devices.

**Comment by si458** [comment]
duplicate of #3211 #2998

**Comment by Ronnyhe96** [comment]
Thanks!

**Comment by si458** [comment]
plz close the issue if it has been fixed 👍
