### ISSUE TITLE
Wasted Whole of my Day. Unclear Quick Start Documentaion

### ISSUE THREAD

**Issue by afzl-wtu** [Ylianst/MeshCentral#5249]
After Wasting 24 hours. I finally understand variables name in config.json, starting with "_" does not work unless remove underscore from their start. What a shame.

**Comment by NiceGuyIT** [comment]
I just ran through the quick start instructions and ran these commands.

```bash
mkdir /tmp/mesh
cd /tmp/mesh
npm install meshcentral
node node_modules/meshcentral
```

The [sample-config.json][] in the repo is used as the `meshcentral-data/config.json` as shown below. It's clear to me attributes starting with an underscore are comments and ignored. Please explain how this can be improved.

```json
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

[sample-config.json]: https://github.com/Ylianst/MeshCentral/blob/master/sample-config.json

**Comment by si458** [comment]
This is actually listed on the docs website

https://ylianst.github.io/MeshCentral/meshcentral/faq/#faq

Try also looking at the website for extra help with stuff

https://ylianst.github.io/MeshCentral/

Also, check out the YouTube videos

https://www.youtube.com/meshcentral/

**Comment by afzl-wtu** [comment]
> This is actually listed on the docs website
> 
> https://ylianst.github.io/MeshCentral/meshcentral/faq/#faq
> 
> Try also looking at the website for extra help with stuff
> 
> https://ylianst.github.io/MeshCentral/
> 
> Also, check out the YouTube videos
> 
> https://www.youtube.com/meshcentral/

You are right but for quick start it should be on config.json file in commented form.
