### ISSUE TITLE
Multi-Download/ZIP Capability in My Files

### ISSUE THREAD

**Issue by MatinatorX** [Ylianst/MeshCentral#525]
Hi Yilan,

Would it be possible to add a feature to easily download multiple files at a time within the "my files" area? Perhaps a server-size utility that adds them to a ZIP that's then downloaded?

**Comment by Ylianst** [comment]
Good request. It's been asked before, for example in #503. This is a popular request. Bryan built .tar encoder in the agent I could use to pack files. I also have a problem with downloads of very large files and want to fix that at the same time.

This said, I have a lot going on right now. Not sure when I will get to it.

**Comment by dinger1986** [comment]
another duplicate of soemthing covered @si458
