### ISSUE TITLE
Can't connect to meshcentral-server running in Docker

### ISSUE THREAD

**Issue by pluim003** [Ylianst/MeshCentral#5250]
**Describe your issue**
Set up Meshcentral with a .env-file and a docker-compose.yaml-file but when I want to connect through local-ip:8087 (a portnumber I could use) I get that the connection is being reinitialised. I also created a domain to connect to through nginx proxy manager, which automatically downloaded letsencrypt-certificates, but when connecting through https://mc.mydomain.com I get a 502 and my  nginx-log says:

2023/07/18 17:55:54 [error] 10760#10760: *3005 upstream prematurely closed connection while reading response header from upstream, client: 1.3.2.1, server: mc.domain.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.0.10:8087/favicon.ico", host: "mc.domain.com", referrer: "https://mc.domain.com/"

Where the client-ip-addres 1.3.2.1 is my original ip-addres (at home) and mc.domain.com is the domain put in nginx (ok, with another name but for security reasons I changed that to this in this post.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 64bit Bookworm on Raspberry Pi4
 - Virtualization: Docker
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] nginx
 - Version: [e.g. 1.0.43] actually I don't know. Using the latest when grabbed through the dockercompose-file.
 - Node: [e.g. 18.4.0] Unknown

**Client Device (please complete the following information):**
 - Device: laptop
 - OS:  Windows 11 trying to connect to meshcentral
 - Network: [e.g. Local to Meshcentral, Remote over WAN] both
 - Browser: [e.g. Google Chrome] firefox
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 -NA

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "mc.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": true,
      "NewAccounts": true,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "_certUrl": "my.reverse.proxy"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
}
```

Wondering if when using nginx which automatically grabs new certificates that the letsencrypt-part is still required.

It must be something simple, but can't figure it out.

My nginx.conf-file which was created through the proxy manager

```
# ------------------------------------------------------------
# mc.domain.com
# ------------------------------------------------------------


server {
  set $forward_scheme http;
  set $server         "10.0.0.10";
  set $port           8087;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;


  server_name mc.domain.com;


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-41/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-41/privkey.pem;




# Asset Caching
  include conf.d/include/assets.conf;




  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000; preload" always;





    # Force SSL
    include conf.d/include/force-ssl.conf;




proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


  access_log /data/logs/proxy-host-17_access.log proxy;
  error_log /data/logs/proxy-host-17_error.log warn;







  location / {





  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000; preload" always;






    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;


    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
````

I have a bunch of other docker-containers which require webaccess running and they run fine and can be nicely connected.
Was trying to implement meshcentral to get rid of teamviewer.

Any help would be appreciated. Thanx in advance.

**Comment by si458** [comment]
The nginx logs clearly show the problem

`upstream: "http://10.0.0.10:8087/favicon.ico"`

Where as your config.json shows port 443

You need to configure ngix to connect to the backend on port 443 over ssl and not http

**Comment by pluim003** [comment]
I'll take a look but that wouldn't make sense as I use my nginx to forward to all kinds of portnumbers and not using 80 or 443. That would probably mean that the config.json isn't correctly generated when running a docker-compose up -d I guess. Maybe in config.json I should put 8087 as port then as redirect.

A bit later: this didn't work unfortunately. The tip to redirect nginx to https to my port 8087 did the trick and locally it's also working by entering https://10.0.0.10:8087. Thanx.
