### ISSUE TITLE
Setup.bin with Static IP

### ISSUE THREAD

**Issue by prjcarr** [Ylianst/MeshCentral#5254]
Just wondering if you can provide any guidance on the USB creation setting a static IP in AMT. I have no dhcp on the network.

I can see how to disable dhcp, but I cannot get the ipv4 config correct. Is there a format for IP, mask, gateway and DNS?

Thanks

**Comment by si458** [comment]
all the setup.bin file does is add the certificate, set dns name, and roaming details for intel AMT.
it doesnt touch your DHCP/static ip settings in AMT
if your network has no DHCP, you need to apply the srtup.bin
then go into the MEBx, then into network and change dhcp to static, and set a static ip and restart

**Comment by si458** [comment]
https://www.intel.com/content/www/us/en/docs/active-management-technology/developer-guide/2021/profile-creation-usb-key-multi-use.html
if you look at the pics, the is no way to set an IP address for multi-use, only single-user
