### ISSUE TITLE
SSH session recordings are broken (error in dev console on attempting to play)

### ISSUE THREAD

**Issue by galdwd** [Ylianst/MeshCentral#5256]
**Describe the bug**
Playback for SSH session recordings are broken seemingly due to removed methods in upstream XTerm.js library (See https://github.com/xtermjs/xterm.js/pull/3947 where the specific function highlighted as erroring out in my screenshot has been removed in v5).

**To Reproduce**
1. Enable Session Recordings for SSH
2. Play around in an SSH session on a machine connected to MeshCentral
3. Go to view the recording
4. Click the play button on the player

**Expected behavior**
The recording of the session should play and I should be able to view my SSH activity for that session

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/20269744/2b3d1fb0-3359-42a2-9cba-8a960ac31c3b)

**Server Software:**
 - OS: Debian 11
 - Virtualization: None
 - Network: WAN,reverse proxy,ssl offload
 - Version: 1.1.16
 - Node: v14.21.3 (for testing purposes, I was on the latest version of the 18 branch when I first ran into the issue, attempted downgrading to see if that would work, it did not)

**Client Device:**
 - Device: Desktop
 - OS: Artix Linux - Kernel 6.4.2
 - Network: Remote over WAN
 - Browser: Firefox 115.0.2 (64-bit)

**Remote Device:**
 - Device: VM
 - OS: Debian 11
 - Network: Remote over WAN
 - Current Core Version (if known): Nov 21 2022, 2311185014

**Your config.json file (stars applied to conceal info)**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "my.reverseproxy.domain",
    "WANonly": true,
    "sessionKey": null,
    "port": 8080,
    "portBind": "100.10.10.10",
    "aliasPort": 443,
    "redirPort": 0,
    "agentPort": 8443,
    "agentPortBind": "100.10.10.10",
    "agentPortTLS": false,
    "webRTC": false,
    "orphanAgentUser": "admin",
    "wsCompression": true,
    "webPush": {
	"email": "*****"
    },
    "desktopMultiplex": true,
    "tlsOffload": true,
    "trustedProxy": "100.10.10.9",
    "webrtcConfig": {
	"iceServers": null
    }
  },
  "domains": {
    "": {
      "title": "Organization",
      "title2": "MeshCentral",
      "minify": true,
      "newAccounts": true,
      "newAccountsPass": "*****",
      "newAccountEmailDomains": ["*****"],
      "userNameIsEmail": true,
      "rootRedirect": "/login",
      "maxDeviceView": 50,
      "ipkvm": true,
      "deviceMeshRouterLinks": {
	  "extralinks": [
		{
			"name":"Test",
			"protocol":"http",
			"port": 9999
		}
	  ]
      },
      "certUrl": "https://my.reverseproxy.domain",
      "passwordRequirements": {},
      "auth": null,
      "ldapUserKey": null,
      "ldapUserBinaryKey": "objectSid",
      "ldapUserName": "displayName",
      "ldapUserEmail": "mail",
      "ldapUserRealName": "name",
      "ldapUserPhoneNumber": "telephoneNumber",
      "ldapUserImage": "thumbnailPhoto",
      "ldapUserGroups": "memberOf",
      "ldapSyncWithUserGroups": false,
      "ldapSiteAdminGroups": null,
      "ldapUserRequiredGroupMembership": null,
      "ldapOptions": {},
      "mstsc": true,
      "ssh": true,
      "redirects": {},
      "agentConfig": [],
      "assistantConfig": [],
      "sessionRecording": {
	"onlySelectedUsers": false,
	"onlySelectedUserGroups": false,
	"onlySelectedDeviceGroups": false,
	"index": true,
	"protocols": [1,2,5,100,101,200]
      },
      "showPasswordLogin": true
    }
  },
  "smtp": {
    "host":"*****",
    "port":425,
    "from":"noreply@*****",
    "user":"*****",
    "pass":"*****",
    "tls":false
  },
  "messaging":{}
}
```

**Comment by si458** [comment]
sorry for delay, fix in PR for you 👍 
we upgraded all the others to use the new write function instead of writeutf8
but missed the player and xterm!
