### ISSUE TITLE
Mobile Website refresh issue on IOS.

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#5259]
**Describe the bug**
When running the mobile site as a web app on iOS (safari), and the connection switches from wifi to data, data to wifi, or if you lose network connection and regain it, the web app needs to be closed and reopened to start working again. It does not help to disconnect, go back to main page, or exit the connection and try to reconnect. The web app must be closed and reopened.

**To Reproduce**
Using safari, click “Add To Home Screen”
Use the web app to connect
Turn off network radios (wifi,data)
Turn on again and try to use web app 

**Expected behavior**
I expect the web app to automatically reconnect without having to close it and reopen it. (Even a refresh button would be nice)

**Server Software (please complete the following information):**
 - OS: FreeBSd
 - Virtualization: FreeBSD jail
 - Network: Hybrid
 - Version: 1.1.6
 - Node: 18

**Client Device
 - Device: iPhone
 - OS: iOS 17
 - Network: Local mostly, VPN into network
 - Browser: Safari
 - MeshCentralRouter Version: N/A
 - 
**Remote Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10
 - Network: Same as above
 - Current Core Version (if known): Dec 9 2022, [2577413753]

My config file has only been changed to use my own domain.
**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
In theory, when the webpage notices a connection error, 

it should come up with a big message saying something like 'reconnect here as network disconnected' same as desktop versions

Does this not happen?

**Comment by tschettervictor** [comment]
It happens occasionally. 

The issue happens when I have a Remote Desktop session open. Forgot to add that.

**Comment by si458** [comment]
Weird? Just tried it here and it does show the 'disconnected reconnect' message?
But I am using Firefox on android
Have u tried it in just safari rather than the webapp version?

**Comment by tschettervictor** [comment]
Update:

It still seems to act weird.

When transitioning from wifi to data or vice versa, this bug still happens and I am forced to reload the entire page and/or webapp.
