### ISSUE TITLE
Request: Opening devices in new tabs using middle click 

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#526]
I'd like to request the following enhancement:

It would be great to be able to open devices in new tabs as described [here](https://github.com/Ylianst/MeshCentral/issues/485#issuecomment-531514375) by @Ylianst, but by using a middle click instead of holding down shift when left-clicking.
This would make MC work more consistent with regular web applications as it imitates browsers' middle click behaviour for hyperlinks.

It would be even better if the focus could remain on the current tab, so one may middle-click multiple devices in a row before switching to the devices' tabs.
If this is not possible, selecting multiple devices in the list and then either shift-clicking or middle-clicking could open all selected devices in tabs.

**Comment by Ylianst** [comment]
Interesting! I did some experimenting this morning and I am having problems getting the middle button event. I will keep investigating this.

**Comment by veitw** [comment]
If it does not work, maybe we can add "Open devices in new tabs" it to Group Actions?

Or even better: Maybe get rid of the Group Actions button and put the Group Actions into the context menu as a seperate group once multiple devices are selected.

**Comment by si458** [comment]
closing as old and laptops dont have a middle click event sadly

**Comment by veitw** [comment]
Sorry, but this is nothing but wrong. Laptops have middle click since about ever:

On modern clickpads using three finger click. 

And on older devices middle button emulation by pressing left and right button resp. left and right click area simultaneously, just like with two-button mice without scroll wheel in the 1990s.

**Comment by si458** [comment]
Hmm, I will reopen and investigate but last time I looked/tried, I just couldn't get the middle click evens to detect no matter what I tried!

**Comment by si458** [comment]
i have got it working with the side icons and the 'desktop,files,events' tabs
but i cant get it working on the devices list themselves
this is because the div is scrollable,
so when you middle click a device, the browser thinks you want to start scrolling and shows the scrolling icon,
groan... unless u have any suggestions?
