### ISSUE TITLE
Is there any option available to disable the agent connected disconnected popup near logout button?

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshCentral#5268]
**Describe your issue**
![image](https://github.com/Ylianst/MeshCentral/assets/10217409/1a6aff96-b717-420e-bc87-3680fa5152fd)
In above image, when more endpoints available, that popup keep on appearing and it becomes difficult to use the options available behind that popup, any way or setting to disable this popup?.

**Server Software (please complete the following information):**
 - OS: Windows
 - Virtualization: No
 - Network: LAN/Wan
 - Version: v1.1.0
 - Node: 18.16.1

**Comment by damium** [comment]
The agent group has notification settings. They are default off.

**Comment by knkumar93** [comment]
Device group notification settings are already off. not enabled anything.

**Comment by si458** [comment]
Check ur user setting
By clicking ur user name at the top right `Welcome USERNAME` and click notification settings

Also if u are using the public meshcentral.com (which is being shutdown btw) 
I believe this is enabled by default and cannot be removed

**Comment by knkumar93** [comment]
Verified user notification settings, there also nothing enabled. It is on-premise setup and it is Administrator user.
Yesterday upgraded this setup from very old version v0.6.28 to v1.1.0. After that noticing this behavior.

**Comment by si458** [comment]
Can you share your `config.json`? (Star secret stuff)

**Comment by knkumar93** [comment]
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "myserver.mydomain.com",
    "mongodb": "mongodb://127.0.0.1:27017",
    "mongodbname": "meshcentral",
	"mongodbcol": "meshcentral",
	"mongoDBDatabse": "meshcentral",       
	"port": 443,
    "browserPong": 60,
    "agentPong": 60,
    "agentPing":60,    
	"CookieIpCheck": false,
    "redirPort": 81,
    "redirAliasPort": 81,
	"ignoreAgentHashCheck": true,
	"DbExpire": {
      "events": 864000,
      "powerevents": 864000,
      "statsevents": 864000
    },
	"MpsPort":0,
	"allowLoginToken": true,
	"allowFraming": true,
	"AgentPing": 180,
	"AgentPong": 180
  },
  "domains": {
    "": {
      "title": "Remote Admin",
      "title2": "Remote Control",            
	  "welcomeText": "Remote Admin",
      "welcomePicture": "mainwelcome.jpg",	  
	  "consentMessages": {
        "title": "Remote Admin Request",
        "desktop": "{0} requesting remote desktop access. Grant access?",
        "terminal": "{0} requesting remote terminal access. Grant access?",
        "files": "{0} requesting remote files access. Grant access?"
      },
	   "notificationMessages": {
        "title": "Remote Admin Request",
        "desktop": "{0} started a remote desktop session.",
        "terminal": "{0} started a remote terminal session.",
        "files": "{0} started a remote files session."
      },
	  "autoRemoveInactiveDevices": 7,
	"mstsc": false,
	"newAccounts": true
    }
  }
}
```

**Comment by si458** [comment]
I have a feeling because you set `notificationMessages` section, the notifications are enabled by default

If you check the scheme.json `notificationMessages` shows false

**Comment by knkumar93** [comment]
I believe `notificationMessages` section is meant for end machine notification message as [per doc](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json).

`This section is user to customize user notifications when a remote desktop, terminal or file session is connected to a remote system.`

Unsure, if this is related, I shall verify by disabling this, but this section was available in older version as well. But I afraid, disabling this option may give different notification to end users.

**Comment by si458** [comment]
You are correct as it should only be the saying of notifications and not enabling the notifications so it might be a bug?

**Comment by knkumar93** [comment]
Could be a bug, or I am missing some config, not sure.

As of now as work around, I have removed below div tag from /views/default.handlebars to avoid this.

`<div id=notificationCount`

**Comment by si458** [comment]
sadly i cannot replicate your issue,
the only way the notification pop up happens here,

is if a group of devices has 'device connections' or 'device disconnections' under 'web page notifications' set under 'notifications' for the group
OR
you have again 'device connections' or 'device disconnections' set under your 'notification settings' for a user

**Comment by knkumar93** [comment]
Closing this one. Now I got a chance to go through each device group available in my setup and found that couple of device groups are enabled with device connect, disconnect notifications. After disabling the issue is resolved. My bad, I should have checked it clearly at the beginning.
