### ISSUE TITLE
PI KVM

### ISSUE THREAD

**Issue by archef2000** [Ylianst/MeshCentral#5269]
**Is your feature request related to a problem? Please describe.**
I have a PI KVM v3 and i would like if i could install MeshAgent on it to control the computer plugged in to it.

**Describe the solution you'd like**
Install MeshAgent on the PI KVM which would need read-only support and control it via the pikvm API.

**Describe alternatives you've considered**
MeshRouter with VNC (not all functions)

**Additional context**
The MeshAgent would need to detect that it is run on a PI KVM trough (ENV, file structure) and then call the local api/socket instead of emulating the keyboard/mouse and display the CSI stream. I would really like to help but i am not skilled in C and i don't know which part can be in JS.

**Comment by si458** [comment]
You can install the meshagent directly onto pikvm running arch
You just need to edit `/boot/config.txt` and replace `ro` with `rw` 
Then install meshagent and it works a treat!
It's what I do at the moment
Install the meshagent in rw mode enabled all the time
Then setup vnc
Then use the web-vnc via meshcentral :)

**Comment by si458** [comment]
You can install the meshagent directly onto pikvm running arch
You just need to edit `/boot/config.txt` and replace `ro` with `rw` 
Then install meshagent and it works a treat!
It's what I do at the moment
Install the meshagent in rw mode enabled all the time
Then setup vnc
Then use the web-vnc via meshcentral :)

**Comment by si458** [comment]
I think this is too much hassle and a big job! 
all development is on hold at the moment anyways sadly unless u can look at the meshagent repo and figure it out urself

**Comment by mjpcomp** [comment]
I just did a setup on my PiKVMs, please check the latest post on this issue for the instructions:
https://github.com/Ylianst/MeshCentral/issues/2515#issuecomment-1670370757

**Comment by si458** [comment]
> I just did a setup on my PiKVMs, please check the latest post on this issue for the instructions:
> https://github.com/Ylianst/MeshCentral/issues/2515#issuecomment-1670370757

@mjpcomp seems a lot of work...

All I did was enter `rw` mode as root, change `ro` to `rw` in `/boot/cmdline.txt, restart, then run the installer script

Also gives u full read/write access to the pikvm now too for future things

**Comment by mjpcomp** [comment]
> > I just did a setup on my PiKVMs, please check the latest post on this issue for the instructions:
> > [#2515 (comment)](https://github.com/Ylianst/MeshCentral/issues/2515#issuecomment-1670370757)
> 
> @mjpcomp seems a lot of work...
> 
> All I did was enter `rw` mode as root, change `ro` to `rw` in `/boot/cmdline.txt, restart, then run the installer script
> 
> Also gives u full read/write access to the pikvm now too for future things

I usually have to work on various appliance type devices, and like to get the mesh agent working under the RO mode of the appliance..

Also, I just read that the initial request in this ticket wasn't to use MeshCentral agent on the PiKVM to monitor the PiKVM, but, pass-through to the device it's controlling... That does seem a little like it will take some custom code work on the PiKVM-side of things in order to pass the video to a socket that the Mesh agent (also custom) would read...

I think in the case of @archef2000 's actual request, it might definitely take some work, or, use an alternative method (use TailScale on the PiKVM and then you can connect to the PiKVM via TailScale tunnel to the device connected to it).

**Comment by si458** [comment]
@mjpcomp or setup meshcentral, setup vnc on the pikvm, then the use vnc-html 😉

**Comment by archef2000** [comment]
The question is why meshcentral has to have rw permissions ?

**Comment by si458** [comment]
@mjpcomp all agent code is here https://github.com/Ylianst/MeshAgent if u want to look

**Comment by mjpcomp** [comment]
> @mjpcomp all agent code is here https://github.com/Ylianst/MeshAgent if u want to look

I can see a few write instances to the database post initial fire up, the biggest seems to be this:
![image](https://github.com/Ylianst/MeshCentral/assets/7637082/4379fd9a-3cc4-42d5-ab4f-a93e81e3ab1e)

So, if you disable core updates and any agent updates, it seems like a read only db should work (as most calls to the db are for Gets, but, this is just a quick glance at what ends up being stored in there.. Didn't look at the code reading/checking the DB or write-access to it... I'm guessing it's there in the initialization of it.

**Comment by archef2000** [comment]
so the db is the only file that needs rw and there is a parameter so this would just need to be enabled by default when pi kvm is detected currently trying some methods.

**Comment by archef2000** [comment]
how can i set it to read only

**Comment by si458** [comment]
> how can i set it to read only

I don't believe you can as it does checks etc and needs to write stuff to the drive like the meshcore.js

**Comment by archef2000** [comment]
Is meshcore.js only written on install or also updated?

**Comment by si458** [comment]
> Is meshcore.js only written on install or also updated?

I believe its written on install as its provided by the msehcentral server but it can also be updated remotely too

Hence, the options on the Web ui to clear the core and update the core, etc...

**Comment by archef2000** [comment]
Maybe it could be integrated like the IP KVM via an external agent? I would like to implement it. Or mybe disable the options of remote updating the core remotly if it is installed on the PI-kvm/detects a ro file system? Would you may reopen the issue?

**Comment by si458** [comment]
If u install the agent on the rpi itself in rw mode, u can then use the https relay feature to relay the whole Web ui of pikvm (This is how I currently do it)

You can also enable vnc access in pikvm, and use the web-vnc for control support

You can also use the local group relay feature, so set another device as the meshagent, then add the device via its ip address and use the https relay/web-vnc features again

We won't integrate it natively sorry

**Comment by si458** [comment]
You can prevent the agent from updating using `noAgentUpdate: 1` in config.json
Then install the agent on the pikvm in read/write mode, then set `noUpdateCoreModule=1` in your meshagent.msh file on the pikvm,
And then restart
This will stop the agent updating the meshcore.js BUT any fixes we push in new releases, won't apply! Beware!

**Comment by archef2000** [comment]
Ok. Maybe I am going to make an extra app for the PI-kvm to have full functionality. Can the meshcentral agent define actions that the UI presents to the user or are they predefined on the server side?

**Comment by si458** [comment]
No... 
But meshcentral does have a plugin section but ive never used it and @Ylianst has always said they are not officially supported! So use at own risk

**Comment by archef2000** [comment]
What do you mean by plugin? Server/client side? I would just make a seperate agent that connects to the server as an agent.

**Comment by si458** [comment]
https://ylianst.github.io/MeshCentral/meshcentral/plugins/
Both inside the meshcentral web interface (server side)
And it being able to push the JS file to the remote agents for things (client side)

**Comment by archef2000** [comment]
Can it override complete functionality of the agent?

**Comment by si458** [comment]
> Can it override complete functionality of the agent?

No idea, never used the plugins, because they are not officially supported and can be buggy, 
Just give it a try and see what happens!

**Comment by archef2000** [comment]
Ok thanks for the help. Will see what works.

**Comment by archef2000** [comment]
I don't see the "meshagent.db" file managed by the [meshcore](https://github.com/Ylianst/MeshCentral/blob/master/agents/meshcore.js) so I also can't alter the behavior of it with a plugin module for the agent right?
