### ISSUE TITLE
Words misconfigured by accents

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#527]
Ylianst, good morning!

Is it possible to customize the system to accept accents like ç, ~, among others, in the fields highlighted in the print below? I realized that in much of the system he already accepts, so far I noticed that only those fields that could not help me?

NOTE: It is in my native language, if you want I can send a print in English

![image](https://user-images.githubusercontent.com/55212206/66212590-93290c80-e694-11e9-9a7e-92022f99b564.png)

**Comment by Ylianst** [comment]
This is a good report, thanks. We will look at it. I think this is an agent issue, so Bryan will need to fix (I think).

**Comment by si458** [comment]
meshcentral has translations now so i think this is fixed?
closing as old issue, if this still happens please do reply and let us know
