### ISSUE TITLE
Mesh Agent "Privacy Bar" fails to show if using apostrophe in real name

### ISSUE THREAD

**Issue by QuiteBored** [Ylianst/MeshCentral#5270]
**Describe the bug**
In the config.json for the server the "desktopPrivacyBarText" specifies "Privacy bar: {0}, {1}" as the example.
Using only the Mesh Agent installed on the guest system and any text with {0} in it results in no privacy bar being produced.

All other consent requests or user notifications work fine and show the name of the user logged into Mesh Central server providing support.
The Mesh Assistant by itself also provides a privacy bar using specified text showing the user name using {0}.

If the Mesh Assistant is used in Monitor Only mode it relies on the Agent to provide the text for the privacy bar and the bar fails to show.

**To Reproduce**
No specific steps, all combinations of installation and config tried, the bar doesn't appear when using just the agent, or the assistant in monitor only mode, and the text uses {0}.

**Expected behavior**
The privacy bar to appear showing the name of the user logged onto Mesh Central that launched the connection, as it does when using Mesh Assistant in any mode other than monitor only and as it does for notifications or content messages which work normally.

**Server Software (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Network: LAN/WAN
 - Version: 1.1.6
 - Node: 18.17.0

**Client Device (please complete the following information):**
 - Device: PC's and Servers
 - OS:  Windows 10 Pro 22H2
 - Network: Local wired
 - Browser: Chrome and Edge

**Remote Device (please complete the following information):**
 - Device: PC's and Servers, virtual and physical
 - OS: , Windows 10, Server 2019, Server 2012 R2
 - Network: Local to Meshcentral and Remote over WAN
 - Current Core: Dec 9 2022, 2577413753

**Your config.json file**
```
{
  "settings": {
    "cert": "REMOVED",
	"AllowHighQualityDesktop": true,
        "SelfUpdate": true,
	"UserAllowedIP": "REMOVED"
   },
   "domains": {
	   "": {
		"title": "REMOVED",
		"userNameIsEmail": true,
		"loginKey": "REMOVED",
		"PasswordRequirements": {
			"min": 12,
			"max": 64,
			"upper": 1,
			"lower": 1,
			"numeric": 1,
			"nonalpha": 1,
			"force2factor": true,
			"email2factor": true,
			"sms2factor": true,
			"push2factor": true,
			"otp2factor": true,
			"oldPasswordBan": 10,
			"banCommonPasswords": true,
			"allowaccountreset": true
		},
		"MaxInvalidLogin": {
			"time": 10,
			"count": 5,
			"coolofftime": 10
		},
		"consentMessages": {
			"title": "REMOVED",
			"desktop": "{0} is requesting remote desktop access, this message will be shown for 30 seconds and then automatically denied. Allow access?",
			"terminal": "{0} is requesting remote terminal access, this message will be shown for 30 seconds and then automatically denied. Allow access?",
			"files": "{0} is requesting remote files , this message will be shown for 30 seconds and then automatically denied. Allow access?",
			"consentTimeout": 30,
			"autoAcceptOnTimeout": false
		},
		"notificationMessages": {
        "title": "REMOVED",
        "desktop": "{0} started a remote desktop session.",
        "terminal": "{0} started a remote terminal session.",
        "files": "{0} started a remote files session."
        },
		"userConsentFlags": {
			"desktopnotify": true,
			"desktopprivacybar": true
		},
		"desktopPrivacyBarText": "We are providing remote support, the desktop is currently shared.",
		"agentCustomization": {
			"displayName": "REMOVED",
			"description": "REMOVED",
			"companyName": "REMOVED",
			"serviceName": "REMOVED",
			"filename": "REMOVED"
			}
		}
	},
	"smtp": {
       "host": "REMOVED",
       "port": 25,
       "from": "REMOVED",
       "tls": false,
	}
}

**Comment by QuiteBored** [comment]
I've managed to pin this down further and the {0} is being resolved correctly by the agent in the Privacy Bar text, the problem is with an apostrophe in the "Real name" of the user which only affects the Privacy Bar and stops it appearing.

I have an Irish surname that starts with O' and the Privacy bar fails to launch when using the agent directly or the Assistant if connected to the agent.

All other dialogues for the agent, and the assistant when it isn't linked to the installed agent, work fine and display my "Real Name" with the apostrophe, eg: "Firstname O'Surname". So the code for those dialogues is happy with the spelling.

The Privacy bar appears correctly if I remove the apostrophe, eg: "Firstname OSurname".

Annoyingly and somewhat amusing too, if I use \' so my "Real name" in my user settings is "Firstname O\'Surname" the Privacy Bar does display it as "Firstname O'Surname" properly, but then all the other dialogues display "Firstname O\'Surname" !!

Hopefully this is an easy fix?

Thanks,
QB

**Comment by si458** [comment]
i can confirm, if your Real Name has an `'` in it, then the bars dont show? weird?
i tried to debug this and it is passing the Real Name correctly,
but for some reason, windows is just ignoring the `'` for some reason?

**Comment by si458** [comment]
fixed for you! 
was very simple (had a brain wave while on the loo haha, `bet i just need to escapre the apostrophes?`)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/c1def5b0-f2b2-4bed-963e-c8a370399633)

**Comment by QuiteBored** [comment]
Thank you so much, you guys put so much effort into Mesh, I hope you continue.

Do I just need to download the latest meshcore.js file pending inclusion in the next major update? I realise this is a newly implemented fix.

Thanks again si458.

**Comment by si458** [comment]
yes you can either
stop meshcentral, then copy over the `meshcore.js` from the master repo to `agents` folder, then start meshcentral again
OR
hang fire 15ish mins, and a new docker `master` image will be built you can use to test!

**Comment by QuiteBored** [comment]
Hi Simon,

I pulled the repo and copied over files, works like a charm.

I feel free to speak and to say a big THANK YOU on behalf of all Mesh admins and users called O'Reilly, O'Donnell, O'Malley, etc, and so forth, and any other people with an apostrophe in their "realname",
We can now use our proper names for all of Mesh where the company demands the "Privacy Bar". :)

It might seem like a small thing but decades of payment services and websites not handling it is a pain, thank you for putting in the time and supporting the MeshCentral project, it's an awesome and powerful product and I hope it stays alive for a long time.

Thanks again,
QuiteBored.
