### ISSUE TITLE
BUG: No Text on Mobile SSH Terminal

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#5272]
**Describe your issue**
Is anyone having the issue where no text will show when accessing ssh on the mobile site? Terminal on Desktop still works.

**Comment by tschettervictor** [comment]
Could anyone direct me to the part of code that handles this? 
Maybe there is something that could be spotted as the fix.

**Comment by si458** [comment]
sadly you are missing critical information that we need to help try and debug your issue (please provide this in the future)
**meshcentral version**
**remote computer os**
**client device + browser**

**Comment by tschettervictor** [comment]
So sorry, here you go.

MeshCentral Verion = 1.1.9
Remote Computer OS = FreeBSD 13
Client Device = iPhone/iOS17.0 Safari Browser

It is a Local SSH Connection using keys.
It works fine on the desktop version of the site, but not the mobile.

**Comment by si458** [comment]
when you say `local ssh connection using keys` you mean `local devices with no agent` group?
if thats the case, check the meshcentral server can SSH to the remote device no problem
BUT i dont think meshcentral works with local devices and ssh keys?
i think it might be better to install the meshagent using the install script and a `managed group with agent`

**Comment by tschettervictor** [comment]
Yes. I created a local devices only group. The added an SSH connection and added my private key. 

The server can SSH no problem. It works while on my desktop. Text shows up and I'm using it as my main SSH manager.

But on the mobile site, text does not show when connecting.

It might not be possible to install the agent, because the system I'm SSHing into is TrueNAS, which doesn't really allow modifications outside of the WebGUI. It is an appliance software.

**Comment by si458** [comment]
sorry ive just tried it myself here i dont use local groups (my mesh is in the cloud (well our datacenter haha) )
i dont get a terminal window on the desktop version or the mobile version? so i dont think its possibe with local groups
do you have a screenshot of what you see?
what is you config.json like? (hide senstive stuff)

im sure it should also be possible to install the meshagent on freebsd as the script says `linux/bsd`
you just need to install packages first as it says underneath it, and use a managed with agent group instead

**Comment by tschettervictor** [comment]
This is my config.json

`{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 8443,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "BrowserPong": 60,
    "AgentPong": 60,
    "AgentTimeStampServer": false,
    "TLSOffload": "192.168.1.140",
    "_trustedProxy": "192.168.1.140"
  },
  "domains": {
    "": {
      "title": "Myname",
      "title2": "Myothername",
      "userSessionIdleTimeout": 999,
      "certUrl": "https://mydomain.com",
      "ssh": true,
      "minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}`

This is what i see when trying on the mobile site...
<img width="1365" alt="Screenshot 2023-08-12 at 4 48 29 PM" src="https://github.com/Ylianst/MeshCentral/assets/85497460/3dc34a50-cdd2-40e0-b889-a1c781c1144e">

And this is what i see normally on the desktop site.
<img width="1364" alt="Screenshot 2023-08-12 at 4 49 02 PM" src="https://github.com/Ylianst/MeshCentral/assets/85497460/73b153c8-801e-4560-b7f6-2fff4aeb8a08">

**Comment by si458** [comment]
ok i think the must be a bug? (can u change the title to `BUG:`)
just tried it here (after i fixed the scheme cuz i couldnt find the ssh option u had listed)
and im seeing the same, desktop asks for user/pass then logins and shows stuff
BUT try mobile, asks for user/pass then sits with blinking cursor?
ill have a proper look in my free time for you 👍

**Comment by si458** [comment]
PR fix for you #5282 👍

**Comment by tschettervictor** [comment]
Thanks you!

**Comment by tschettervictor** [comment]
So I just tried to copy that into my server. Same issue.

Anything else I could try?

**Comment by si458** [comment]
what do you mean you copied it into your server?
the PR hasnt been merged yet and a new release hasnt happened yet either?

**Comment by tschettervictor** [comment]
Deleting the `default-mobile-min.handlebars` seems to have done the trick. 

I tried with `minify` true and false

**Comment by tschettervictor** [comment]
UPDATE:

I installed the latest version 1.1.10 and have found that `minify` must be set to false, or the text doesn't show. I don't think i need minify so it works for me. Thanks again.

**Comment by si458** [comment]
yes @tschettervictor ive just looked at the minified code that gets included on release and it doesnt appear to include the fix?
so ive ask @Ylianst how the minify is done as ive never enabled it

**Comment by tschettervictor** [comment]
There is also another bug. Backspace does not register on the mobile site.

maybe I should create another bug report?

**Comment by si458** [comment]
> There is also another bug. Backspace does not register on the mobile site.
> 
> maybe I should create another bug report?

No it's OK I confirm backspace doesn't work either,
must have missed something, I will investigate later for you

**Comment by tschettervictor** [comment]
Update?

**Comment by si458** [comment]
sorry havent had chance to look, will look when i get chance, slipped the net

**Comment by si458** [comment]
Notes: @Ylianst, i have found the bug, for some reason when you send the backspace key, it is sending the bytes in 2 commands instead of 1 according to the websocket?
it should send as `~[SQUAREBINARYICON]` but instead its sending `~` in one command then `[SQUAREBINARYICON]` right afterwards in another command and not together like the desktop version?
i cant seem to track down where it sends the key commands! but still looking into it

**Comment by tschettervictor** [comment]
Bump. Would really like to see this fixed.

**Comment by si458** [comment]
@tschettervictor sorry for delay, forgot about this bug!
just spend hours debugging and the fix was so simple!
PR done, will merge into master soon!

**Comment by tschettervictor** [comment]
This does appear to be fixed in 1.1.14

One issure though is that the screen will pop to the top when pressing backspace and not on full screen.
Steps to replicate are
1. Click an ssh connection, then click terminal, then click connect
2. Click backspace and it will jump to the top

If i open full screen, it works properly

**Comment by si458** [comment]
> This does appear to be fixed in 1.1.14
> 
> One issure though is that the screen will pop to the top when pressing backspace and not on full screen. Steps to replicate are
> 
>     1. Click an ssh connection, then click terminal, then click connect
> 
>     2. Click backspace and it will jump to the top
> 
> 
> If i open full screen, it works properly

I cannot replicate this issue on my fold 3?
What os/browser are you using?

**Comment by tschettervictor** [comment]
iOS 17, safari

**Comment by si458** [comment]
> iOS 17, safari

oh poo, the one device i dont have! dam you apple!
ill try get my Docker-OSX working again, and get ios emulator working!

**Comment by tschettervictor** [comment]
Thanks for taking the time!

**Comment by tschettervictor** [comment]
@si458 The annoying backspace issue is present again in version 1.1.23 of meshcentral.

Open an SSH (local) connection, type some characters and try deleting them with backspace. The screen keeps jumping to the top.

**Comment by si458** [comment]
I have a Mac and an iPhone 7 this time round!
Will have a look when i get chance
