### ISSUE TITLE
Getting clipboard from macOS Ventura truncates last 2 characters

### ISSUE THREAD

**Issue by NiceGuyIT** [Ylianst/MeshCentral#5273]
**Describe the bug**
When copying the clipboard from macOS Ventura, the last 2 characters are not copied. This happens when clicking on the clipboard icon in the lower right corner, and when using the "Get Clipboard" functionality. The "Set Clipboard" works and does not truncate the contents. This happens only for macOS, possibly with Ventura.

**To Reproduce**
1. Connect to a computer running macOS. I'm using Ventura and can't test a previous version.
2. On the physical Mac, copy some text. Paste it to verify the copied text is complete.
3. In MeshCentral, click on the clipboard icon in the lower right corner and then paste the contents into an editor. Notice the last two characters are missing.
4. In MeshCentral, click on the Clipboard icon in the lower left corner and "Get Clipboard". Notice the last two characters are missing.

**Expected behavior**
I expect the contents of the clipboard to be transferred in its entirety.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa)
 - Virtualization: nspawn
 - Network: WAN
 - Version: v1.1.6
 - Node: v16.17.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Linux openSUSE 15.4
 - Network: WAN
 - Browser: Firefox 115.0.1
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Apple M1 laptop
 - OS: Ventura 13.5
 - Network: WAN
 - Current Core Version (if known): Aug 22 2022, 1306247125

**Additional context**
I have only tested macOS Ventura. I don't know if this affects previous macOS versions.

**Your config.json file**
```
{
  "settings": {
    "Cert": "mesh.a8n.tools",
    "WANonly": true,
    "Minify": 1,
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 0,
	"_agentPort": 4443,
	"_agentAliasPort": 4443,
	"_agentNoProxy": true,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "_AgentPing": 60,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "TlsOffload": "172.30.0.119",
    "_TlsOffload": "127.0.0.1",
	"trustedProxy": "172.30.0.119",
	"_trustedProxy": "127.0.0.1",
    "agentCoreDump": false,
    "syslog": "meshcentral",
    "syslogauth": "meshcentral-auth",
    "syslogjson": "meshcentral-json",
    "meshErrorLogPath": "/meshcentral/logs/",
    "authLog": "/meshcentral/logs/auth.log",
	"log": [
		"cookie",
		"dispatch",
		"main",
		"peer",
		"web",
		"webrequest",
		"relay",
		"webrelaydata",
		"webrelay",
		"mps",
		"mpscmd",
		"swarm",
		"swarmcmd",
		"agentupdate",
		"agent",
		"cert",
		"db",
		"email",
		"amt",
		"httpheaders",
		"websocket"
	],
    "Compression": false,
    "WsCompression": false,
    "AgentWsCompression": false,
    "WebRTC": true,
    "webrtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    },
    "MaxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 30
    },
    "postgres": {
      "database": "meshcentral",
      "user": "****",
      "password": "****",
      "port": "5432",
      "host": "localhost",
	  "ssl": {
        "rejectUnauthorized": "true"
      }
	}
  },
  "domains": {
    "": {
      "Title": "Tactical RMM",
      "Title2": "Tactical RMM",
      "NewAccounts": false,
      "CertUrl": "https://mesh.a8n.tools:443/",
      "agentConfig": [
        "webSocketMaskOverride=1"
      ],
      "GeoLocation": true,
      "CookieIpCheck": false,
      "mstsc": true,
      "agentInviteCodes": true
    }
  }
}
```

**Comment by compumatter** [comment]
I can second this issue - I experience this identical behavior in my Ventura 13.4.1

**Comment by si458** [comment]
If anybody would like to donate a Mac/virtual machine with the os on, I'll happy have a look

I'm not a Full blown Mac developer but gotta start somewhere haha

**Comment by si458** [comment]
just been given an old macbook pro 2012 running 10.15.7 and its the same? 
how weird?
ill have to look into it for you if i can work out the mac agent

**Comment by si458** [comment]
so ive found the bug, it was caused by this commit in message-box.js in the agent
https://github.com/Ylianst/MeshAgent/commit/fd59b52e89374daf13522f0dd9f5e7d70eabe0ea

@krayon007 was removing the last 2 strings for some reason?
