### ISSUE TITLE
Unable to uninstall meshagent

### ISSUE THREAD

**Issue by KonVei82** [Ylianst/MeshCentral#5274]
Everything was working great until we decided to change our domain, as a result we had to issue new agents for all the PC since all the agents were pointing to the old domain.

The issue is that we are unable to uninstall meshagents on a 8.1x64 PC, we are getting a very odd error:

[2023-08-07 09:20:14 AM] [AD262CB981431433] ..\microstack\ILibParsers.c:2776 (0,0) FATAL EXCEPTION @ [FuncAddr: 0x00007ff648230a4d / BaseAddr: 0x00007ff648270160 / Delta: 259859]

The message repeats itself each time we try to uninstall the agent, we tried uninstalling via the windows add/remove programs and are getting same issue.

We tried updating to agent via the the Update option on the new client but it doesnt make any difference.

Let me know if u need more details.

Thanx in adavance.

**Comment by KonVei82** [comment]
Just some additional info, tried to uninstall same agent on a different Windows 8.1 x64 and got exactly the same issue, it is a completely different machine.

Same agent on a windows 10 x64 is uninstalling perfectly fine.

There must be something with the uninstall script and Windows 8.1 x64 that does not work.

**Comment by si458** [comment]
This is more a meshagent issue than a meshcentral issue
Please can you open an issue at https://github.com/Ylianst/MeshAgent and close this one

**Comment by KonVei82** [comment]
Sure will do, thanx for pointing it out.
