### ISSUE TITLE
Update ua-parser-js and chart-js - critical CVEs

### ISSUE THREAD

**Issue by jammsen** [Ylianst/MeshCentral#5275]
**Describe the bug**
Hello @Ylianst the dependencies or cross-deps have major CVE reports, please update the deps and release a "clean" version. Current Version is 1.1.8.

**To Reproduce**
Do a SBOM scan on this package via Sonatype Nexus

**Expected behavior**
Removal of CVEs through updating assets

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/2270806/6f56e0a0-906b-4ee9-bb3c-8cb77b73f1fb)

**Comment by jammsen** [comment]
Here is another screenshot for this.
![image](https://github.com/Ylianst/MeshCentral/assets/2270806/a8c08b2f-72bb-4127-8ae7-5d76b2b09130)

**Comment by jammsen** [comment]
#5106 has the same problem since months

**Comment by si458** [comment]
Development is on hold! If you can upgrade the assets urself manually and confirm all is good I'm sure @Ylianst will accept a PR

Last time I looked at the jthe post, upgrading the graphs by increasing the nukber didnt work so it wasn't straight forward

**Comment by jammsen** [comment]
What does "Development is on hold!" mean in reality?

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/discussions/4795

**Comment by si458** [comment]
Sadly, as i commented on ur other post from the other month
When I tried copying and pasting the latest chart-js, everything fell flat on its face
So the must be stuff that is different or changed in new releases so I'll have to look when I get chance
I'm only a community member and look after meshcentral as I use it everyday for myself

**Comment by si458** [comment]
@jammsen does ur test show which version of ua-parser-js is needed to PASS the test?
as the is a latest ua-parser-js 0.7.35 from April 2023?
so in theory the ua-parser.js file in the root of meshcentral in node_modules could be replaced with a built version in there repo?
https://github.com/faisalman/ua-parser-js/blob/0.7.x/dist/ua-parser.min.js

**Comment by si458** [comment]
@jammsen #5276 should fix ua-parser-js for you
ill look into chart-js another tine👍

**Comment by jammsen** [comment]
@si458 thanks 
ua-parser-js was sadly the lower cve one 😃 
charts.js is in public/scripts/charts.js from what i can see and from v2.7.2 to v4.3.3 ( https://github.com/chartjs/Chart.js/releases is a major jump ) there will be surely some breaking changes. But mabye you can try this version, there was in the 2.X version one release where there was no critical cve in there, maybe that doesnt break all of the stuff?

![image](https://github.com/Ylianst/MeshCentral/assets/2270806/177c0c13-b2cf-48f4-82dc-f6bcfc02673e)

**Comment by jammsen** [comment]
Really hope that helps *fingers crossed*

**Comment by si458** [comment]
ill look into it again tomorrow when im stationary at my desk,
i tried upgrading to the 2.9.4 if i remember last time but stuff stopped working,
and BTW love the 'activate windows' watermark 😆

**Comment by jammsen** [comment]
"BTW love the 'activate windows' watermark 😆" 
Yeah .... well ..... what can i say, Windows is weird with virtual machines where the motherboard id is sometimes changed, i have almost given up on always changing it 😎

**Comment by jammsen** [comment]
> @jammsen does ur test show which version of ua-parser-js is needed to PASS the test? as the is a latest ua-parser-js 0.7.35 from April 2023? so in theory the ua-parser.js file in the root of meshcentral in node_modules could be replaced with a built version in there repo? https://github.com/faisalman/ua-parser-js/blob/0.7.x/dist/ua-parser.min.js

I did not see your question here, do you still need input on that?

**Comment by si458** [comment]
@jammsen plz can u verify the latest release is ok with ua-parser-js now?
im still looking into chart-js for you 👍

**Comment by jammsen** [comment]
@si458 
![image](https://github.com/Ylianst/MeshCentral/assets/2270806/ee9257ae-34c7-4c57-9499-b94b888b806b)
Came down, better than before

**Comment by si458** [comment]
That screenshot shows version 1.0.35?
The latest is 1.1.9?

**Comment by jammsen** [comment]
"plz can u verify the latest release is ok with ua-parser-js now?"
That screenshot is for ua-parser.js, before to after, i thought thats what you wanted to know, sorry.

Do you have Discord by any chance to make communication easier?

**Comment by si458** [comment]
same as github/email

**Comment by Ylianst** [comment]
#5276 was released with the latest MeshCentral. Let me know if this fixes it or more is needed.

**Comment by jammsen** [comment]
@Ylianst ua-parser-js was fixed the above CVEs 5 and 7 were fixed, now its only chart.js left the  CVE9 the big one.

**Comment by si458** [comment]
#5293 should update chart.js to 4.33 for you!
we lost the pretty shadows around the doughnuts but ill look at fixing them in the future if people want it back

**Comment by jammsen** [comment]
@Ylianst Do you have an eta when do you have time to review this?
I would like to security scan the next release.
