### ISSUE TITLE
Mobile Site

### ISSUE THREAD

**Issue by rmicha9682** [Ylianst/MeshCentral#528]
Running latest 0.4.1-r release and the mobile site doesn't seem to work.  I try connecting to agents and nothing happens.  Testing from Android with Chrome browser.  Everything works properly from standard site with regular browser.

**Comment by Ylianst** [comment]
I will take a look at this.

**Comment by Ylianst** [comment]
Fixed it, will be in the next release.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-s with a fix for this. Let me know if it works.

**Comment by rmicha9682** [comment]
That did the trick!  Thank you.

**Comment by Ylianst** [comment]
Perfect!
