### ISSUE TITLE
RaspberryPI: ./meshinstall.sh: line 174: ./meshagent: No such file or directory

### ISSUE THREAD

**Issue by ronenb75** [Ylianst/MeshCentral#5284]
Trying to install the agent on my **Raspberry Pi 4 Model B Rev 1.1** running **Raspbian GNU/Linux 11 (bullseye)** after I upgraded to **1.1.9** and I'm getting the error:
`./meshinstall.sh: line 174: ./meshagent: No such file or directory`

Checking the directory in:
```
# ll mesh*
-rwxr-xr-x 1 root root 3.2M Oct 26  1985 meshagent
-rw-r--r-- 1 root root  29K Aug 13 21:45 meshagent.msh
-rwxr-xr-x 1 root root 5.4K Aug 13 21:45 meshinstall.sh
```

However, the file is 64bit rather then 32bit:
```
# file meshagent
meshagent: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, stripped
```

I believe that's the problem.

**To Reproduce**
Generate the agent text for Linux/BSD and run on Rpi

**Expected behavior**
The installation will succeed.

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Virtualization: None
 - Network: WAN
 - Version: 1.1.9 (freshly updated, worked well in 1.1.0)
 - Node: 6.14.4

**Client Device (please complete the following information):**
 - Device: RaspberryPI 4
 - OS: Raspbian GNU/Linux 11 (bullseye): `Linux xxxxx 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - Network: Remote over WAN

**Comment by si458** [comment]
POSSIBLE DUPLICATE ISSUE https://github.com/Ylianst/MeshCentral/issues/5108

FIX IS HERE - https://github.com/Ylianst/MeshAgent/pull/187#issuecomment-1650466953

**Comment by dinger1986** [comment]
@si458 fix was merged

**Comment by si458** [comment]
correct fix was merged, but no new agent releases yet recently, so keeping open until new agent releases
