### ISSUE TITLE
Is remote-input supported in for Android devices?

### ISSUE THREAD

**Issue by qiao-tw** [Ylianst/MeshCentral#5287]
Hi,

I want to use the remote desktop to control Android devices. However, I saw @Ylianst 's post [here](https://github.com/Ylianst/MeshCentral/issues/2372#issuecomment-798958812).

I'd like to know -- does it still holds true that the remote-desktop feature is view-only for Android devices?

Thank you.

**Comment by jsastriawan** [comment]
It is Android API restrictions. You cannot even capture the screen now unless the agent has certain privileges and running as foreground task if I am not mistaken.

**Comment by qiao-tw** [comment]
@jsastriawan Thanks for answering. I tested with the Android emulator (running Android 12) a few days ago before the public server shut down, and viewing the Android screen is still OK. I'm not sure whether the later version will not allow screen sharing as you mentioned.

**Comment by jsastriawan** [comment]
Android emulator may have very relaxed permissions since it is used for development purpose. So screen record permission may not be required to work. Real Android device since Android 10 should impose this restriction.

**Comment by si458** [comment]
currently you can watch an android device but not control it,
tested on my z fold 3 android 13

**Comment by Ylianst** [comment]
So yes, the restriction still holds true. You can remotely capture the screen if user permission is granted, but there is no way to control sadly. It may be possible to inject input if your device is "rooted", but this is not typical and not supported.

**Comment by qiao-tw** [comment]
@Ylianst Thanks for the confirmation! Since I have complete Android system source code of all my devices, therefore there's no such limitations in my case. Is the remote-input feature also disabled in the MeshCentral frontend (the administration website) and server-side for Android devices? Thank you.

**Comment by silversword411** [comment]
> You can remotely capture the screen if user permission is granted, but there is no way to control sadly

It's hit or miss, but there must be some API that you can use because I can do it from screenconnect/TeamViewer... occasionally. Usually Samsung devices, so maybe it's something Samsung allows.

**Comment by schklom** [comment]
@Ylianst I have tried Rustdesk, and it does support remote input, provided that the user gives the required Accessibility permission. That permission allows to give Rustdesk full control of the device to "View and control screen" and "View and perform actions".

Is it still impossible for Meshcentral-Agent to support this too?

**Comment by nobodyspecial** [comment]
> [@Ylianst](https://github.com/Ylianst) I have tried Rustdesk, and it supports remote input on Android, provided that the user gives the required Accessibility permission. That permission allows to give Rustdesk full control of the device to "View and control screen" and "View and perform actions".
> 
> Similarly, https://f-droid.org/packages/net.christianbeier.droidvnc_ng ([github](https://github.com/bk138/droidVNC-NG)) allows to fully control an Android phone remotely, via VNC.
> 
> Both allow this without root, by requiring an Accessibility permission.
> 
> I don't know a lot about Android, but felt that this may be able to help here.

I second this. There are a bunch of apps that allow remote control on Android. There is no reason why MC cannot have that.

**Comment by rui-alves** [comment]
This would help a lot of people… isn’t anyone interested in trying to implement it?
