### ISSUE TITLE
How to test MeshCentralAgent for Android in local network environment (LAN mode)?

### ISSUE THREAD

**Issue by qiao-tw** [Ylianst/MeshCentral#5288]
**Describe your issue**
Hi,

I'm testing MeshCentralAgent on Android. However, when I set up my local MeshCentral server, it by default ran under "LAN mode", and it does not allow me to add Android devices under LAN mode.

I already change the ```_LANonly``` to ```false``` in ```config.json```, but it won't work.

Please tell me how to switch to WAN mode, or enable adding Android devices under LAN mode.

Thanks.

**Server Software (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Network: LAN
 - Version: 1.1.9
 - Node: 20.3.0

**Client Device (please complete the following information):**
 - Device: MacBook pro
 - OS: macOS Ventura 13.4
 - Network: LAN
 - Browser: Google Chrome

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment]
plz stop opening issues for each question, use discussions instead

anything in your json which has an `_` in front of it is ignored
https://ylianst.github.io/MeshCentral/meshcentral/faq/#json-config-files

also try reading some docs here - https://ylianst.github.io/MeshCentral/meshcentral/

and watching some youtube videos here for help - https://www.youtube.com/meshcentral

**Comment by qiao-tw** [comment]
Hi @si458 ,

I apologize for doing this. I'm new to this awesome project and not familiar with the rules.
Thanks for the reminder and hints. I'll do the homework before asking questions in the future.

**Comment by Ylianst** [comment]
In LAN only mode, the device has to multicast on the network to find the server. The Android agent can't do that. You can to be in WAN or Hybrid mode and your server must have a DNS name or static IP address set.
