### ISSUE TITLE
Feature Request : Consider making force2factor (2FA) better enforced

### ISSUE THREAD

**Issue by darryl-h** [Ylianst/MeshCentral#529]
Was testing 2FA today and found the following issue, I also understand this looks like a non trivial effort.

**Server Version:** v0.4.1-n

**Use Case:** User forgets to enable 2FA (yes, I know terrible!), because they don't set 2FA like they should, they also set an insecure password (test123) and that password is compromised either from something like a brute force attack, a phishing attack or some other method, (the password being insecure just makes the attack easier, if it is secure, it might just take longer to brute force) whereby a bad actor logs into the mesh central server and impersonates the authorized user with just the username and password. When the bad actor tries and manage a device, they get the popup that they require 2FA. The smart hacker thinks, no problem! and happily add's 2FA to his own device, now locking out the authorized user, and granting access to run havoc in the agent.

**Expected Results:** One method could be that if force2factor is set to true, on next login, have the user prompted to setup 2FA. Additionally, the user should not be able to disable 2FA (even with email recovery) when force2factor is set to true. If an authorized user has in fact lost 2FA, and force2factor  is true, they would contact an admin who can disable, and reset (force 2FA on next login). 

If the admin user looses 2FA, and there is a "NewAccountEmailDomains": set, then it would e-mail them with a one time login key, which would again force 2FA and a password change on next successful login for the root user.

**Comment by Ylianst** [comment]
So, right now if force2factor is true, the user can't do much until two-factor is enabled. I also added a warning a week back that if you have a single second factor enabled it will warn you that you need to setup a second-second factor. Having 2 USB keys, or 1 USB key + GoogleAuth or GoogleAuth + BackupCodes (or any combo is ok).

It would be a bunch of work to ask to setup 2 factor on next login in a separate screen, but I can lock what the user can do until a second factor is setup. I would hope that is sufficient.

If you loose the 2nd factor, right now you need to contact the admin. But since I now have a warning telling you to setup 2 two-factors, I am hoping this is going to be less of an issue. Sending an email to recover a lost 2nd factor is not good practice, I can only do that to recover the password.

I think the current system with block until 2 factor setup + warn if you only have one 2nd factor seems ok. All this said, feedback appreciated.

Ylian

**Comment by darryl-h** [comment]
The main concern for us is that the current implementation isn't so effective if the user forgot to enable, neglected to enable or disabled 2FA. In these conditions the would be attacker can simply enable 2FA on an arbitrary device which somewhat makes 2FA ineffective for these corner cases.

A second minor concern is the option name is called "enforce" but the user can then disable 2FA (which seems to be against the password policy for the domain, not sure if you agree) 

As a work around, if there was some kind of report from meshctrl that listed users that had never set 2FA, as well as those users to have it actively disabled after enabling it for a specific domain (or, all domains), we can then work with those users to enable it, that might also work, but does require manual intervention, and may not to scale well in larger environments. 

I did observe the warnings about the backup, but to be honest, I didn't spend too much time investigating it, but will look at it more in detail next week. (Just tried clicking on the message, there was no response, moved on)

As always, thanks for all your hard work.

**Comment by darryl-h** [comment]
For us, I have worked around this issue by creating a Mongo script that will report users who do not have 2FA enabled. For our use case, we add our employee's to multiple domains at once, and, until the employee actually sets 2FA to a device under their control for each domain, their account can be used as an attack vector, and we are needed a report so we knew could identify who the users are, so as to have the condition corrected.

Here is the mongo command:
```
use meshcentral
db.meshcentral.find( { type: "user","otpsecret":null }, { login: 1, email: 1 } )
```

Which will return something like this:
```
DomainA,user1,user1@domain.com,1573600493
DomainB,user2,user2@domain.com,1573616872
```

@Ylianst  You may close this ticket at this time. 

I know you have many other more important bugs to address, so if you feel these are intresting and have the time:
**Feature request**, if we could get this report from meshctrl that would be ideal. 
**Stretch Feature Request** What about an option somewhere (per domain?) which would send an e-mail alert to the offending user to tell them to enable 2FA on this domain

As always, thanks for all your hard work!

**Comment by darryl-h** [comment]
It looks like the 2FA report has been added in PR https://github.com/Ylianst/MeshCentral/issues/659, I'll go ahead and close this request and open a new if required. 

As always, thanks for all the hard work!
