### ISSUE TITLE
Meshcentral public login is gone ???

### ISSUE THREAD

**Issue by acasadoalonso** [Ylianst/MeshCentral#5291]
What happened with the public server .... I guess that is gone, however may someone confirm that ???
https://meshcentral.com/login 

![image](https://github.com/Ylianst/MeshCentral/assets/8141927/ddcef5ec-96cb-48ee-a5dc-67de7a6f5924)

**Comment by si458** [comment]
it has been officially shut down - https://github.com/Ylianst/MeshCentral/discussions/5290

https://github.com/Ylianst/MeshCentral/discussions/4795

https://github.com/Ylianst/MeshCentral/discussions/4795

**Comment by acasadoalonso** [comment]
ThanksI am truly sorry, it was a great service, however I understand the reasons behind.AC/.Sent from my iPadOn 17 Aug 2023, at 11:49, Simon Smith ***@***.***> wrote:﻿
it has been officially shut down - #5290
#4795
#4795

**Comment by Vista2003** [comment]
Hi @acasadoalonso 

Please close the ticket by visiting this page on GitHub, this ticket is currently still open.
