### ISSUE TITLE
Need to download recording file

### ISSUE THREAD

**Issue by zaladhaval** [Ylianst/MeshCentral#5292]
I have recording file name, which I have fetched from recording events from postgresSql , now I want to download the file from different server by 

https://{{domain-name}}/recordings.ashx?file=relaysession-2023-08-16-12-31-30-a-DESKTOP-3E9VHAN-0ka4696gys.mcrec

but is shows unauthorised error , I have tried  giving login token in URL like

https://{{domain-name}}/recordings.ashx?file=relaysession-2023-08-16-12-31-30-a-DESKTOP-3E9VHAN-0ka4696gys.mcrec&login={{token}}

but it dose not work .
So how can I download the file through api call

And I want to convert .mcrec file to .mp4 is it possible ?

**Comment by si458** [comment]
sadly this isnt possible, as the url `recordings.ashx` checks if you are logged in first before letting you continue and fail if you arent

it doesnt support passing any login information either, so the only thing you can do is
1. login first
2. copy/save your cookie
3. then visit the url with cookie attached
4. it will then download ur recording
