### ISSUE TITLE
Meshcentral with cloudflare

### ISSUE THREAD

**Issue by Rasha2206** [Ylianst/MeshCentral#5298]
**Describe your issue*
I am using Meshcentral with docker. I have the container running and everything works fine internally, but when I wanted to reverse proxy in cloudflare, it is giving me a 502 bad gateway error.  I tried to use the following in the config.json file but it did not work:

“trustedproxy”: “cloudflare”,

do I need to put the config.json file in the docker container?

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Virtualization: [e.g. Docker]
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.0.43]
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: [e.g. Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by PrplHaz4** [comment]
With the cloudflare proxy your clients are not seeing the same TLS certificate they did when they first connected (they see the CF proxy cert instead).  There are a number of similar issues here with more info if you need it.  There isn't a solid solution yet, just workarounds - mainly turning the proxy off and changing back to dns only.

**Comment by Rasha2206** [comment]
I am trying to create a tunnel to access meshcentral publicly and it keep telling me 502 bad gateway. do I need to change anything in the config.json file and upload the file to docker?

**Comment by Rasha2206** [comment]
figured out the issue it was the certificate selection in cloudflare and I had to look at the log in docker to set the port to the port in the container log in order for the tunneling to work in cloudflare.

**Comment by si458** [comment]
please close this issue if your issue has been resolved 👍
