### ISSUE TITLE
Add internal IP Address Column to details view of "My Devices"

### ISSUE THREAD

**Issue by jjoelc** [Ylianst/MeshCentral#5305]
**Is your feature request related to a problem? Please describe.**
We quite often need to find a client by their IP Address. Inside of a LAN setup, the "Agent IP Address" shows this information, but in a WAN setup, the Agent IP Address shows the public IP, and not the client IP. Currently the only way to see the client's IP address (vs the agent's public IP Address) is to click on the client, then go to the details tab. 

**Describe the solution you'd like**
2 parts:
 - Allow a column "Internal IP Address(es)" to be show in the "My Devices" details view. This should be the IP address assigned to Ethernet or WiFi adapter of the client.
 - Additional filter prefix (or enhancement of existing "ip:" prefix) to search/filter by known internal IP Address

**Describe alternatives you've considered**
Not much in MeshCentral ...

**Additional context**
![image](https://github.com/Ylianst/MeshCentral/assets/4069621/ee4271da-c0f7-49c3-a7a1-64ceee928a0f)

**Comment by si458** [comment]
this would be very difficult to achive
because 1 device could have multiple ip addresses so you would end up listing all the ip addresses, and how would you know which is ur primary one?

one way around at the moment, is click a device, then click 'interfaces' under the power chart and this will show a summary of the ip addresses

**Comment by jjoelc** [comment]
I do understand the issue with displaying multiple IP Addresses in the details view. 

How about just expanding the behavior of the "ip:" filter to search all of the IPs assigned to the clients?

**Comment by si458** [comment]
I've never tried the search expressions before? I'll have a look at it when I can :)

**Comment by si458** [comment]
Duplicate #3720
