### ISSUE TITLE
Mesh Central web socket relay only connects after multiple tries

### ISSUE THREAD

**Issue by frogweh** [Ylianst/MeshCentral#5309]
I am currently using NPM (Nginx Proxy Manager) in front of my mesh central server. Everything is working, but when I attempt to connect to one of my agents, sometimes it works first try and other times it takes a couple tries. I traced the web relay and http requests from the server to get some additional information but I have no idea what is causing this. Any help would be greatly appreciated.

I'm running both NPM and mesh central in docker containers on Unraid V6.12.3
I'm using NPM as the reverse proxy utilizing an edge certificate from Cloudflare and I offloaded TLS to the NPM instance

It seems to happen on any client device regardless of OS, age, hardware, etc.

Mesh central server version is: 1.1.10

NPM version is: 2.10.4

here is my config.json file:

{

  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "subdomain.domain.com",
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "EvenIfYouStealThisIllJustMakeANewOne:P",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 50,
    "TLSOffload": "127.0.0.1,(internal ip for npm container),::1",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "npmProxy": "http://(internal IP for npm container):81",
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": "",
      "keepLastDaysBackup": "",
      "zippassword": ""
    }
  },
  "domains": {
        "": {
        "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "false",
        "_userNameIsEmail": true,
    "certUrl": "https://domain.com:443"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  }
}

in NPM's advanced tab I have the following additional parameters:

real_ip_header CF-Connecting-IP;
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

Here is the information from the trace:

8:03:52 AM	relay	Relay disconnect: cjnmti5280i ((Agent WAN IP) --> (Server WAN IP))
8:03:50 AM	relay	Relay connected: cjnmti5280i ((Server WAN IP) --> (Agent WAN IP))

8:03:50 AM	httpheaders	GET, /meshrelay.ashx/.websocket?p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ%40iODtoIy4vJOHMAL1YWmw8&id=cjnmti5280i&rauth=vQ%24nDK77BWdQ3yWr1DiYbPT6TuvgzHGq5JNaQZTyjgGFSxwS336UcijuiQdo7IPC3KQg%40NyomYmGS1fBmJkgYupQVuAwKXuK27YAeKHTXQHj7rlnaT7R%24A==, [object Object]

8:03:50 AM	relay	Relay holding: cjnmti5280i ((Agent WAN IP)) Authenticated

8:03:50 AM	httpheaders	GET, /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ@iODtoIy4vJOHMAL1YWmw8&id=cjnmti5280i&auth=kzX6rlnHUx$5zNbbmmBfFPnqv2ls47gYFp3irsG@0O0eoxljQ051ajL$lmTV4TRwaXfLcbqtFm7pP8pNnB2zBEZ$FksPeS8Gi5VmXuCKM2nPpQkWOn8YBhv3xI4aPeL@N@3uZVMbfZ80zg==, [object Object]

8:03:49 AM	relay	Relay disconnect: h66olvcylnn ((Server WAN IP) --> (Agent WAN IP))
8:03:49 AM	relay	Relay connected: h66olvcylnn ((Server WAN IP) --> (Agent WAN IP))

8:03:49 AM	httpheaders	GET, /meshrelay.ashx/.websocket?p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ%40iODtoIy4vJOHMAL1YWmw8&id=h66olvcylnn&rauth=vQ%24nDK77BWdQ3yWr1DiYbPT6TuvgzHGq5JNaQZTyjgGFSxwS336UcijuiQdo7IPC3KQg%40NyomYmGS1fBmJkgYupQVuAwKXuK27YAeKHTXQHj7rlnaT7R%24A==, [object Object]

8:03:49 AM	relay	Relay holding: h66olvcylnn ((Agent WAN IP)) Authenticated

8:03:49 AM	httpheaders	GET, /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ@iODtoIy4vJOHMAL1YWmw8&id=h66olvcylnn&auth=kzX6rlnHUx$5zNbbmmBfFPnqv2ls47gYFp3irsG@0O0eoxljQ051ajL$lmTV4TRwaXfLcbqtFm7pP8pNnB2zBEZ$FksPeS8Gi5VmXuCKM2nPpQkWOn8YBhv3xI4aPeL@N@3uZVMbfZ80zg==, [object Object]

8:03:39 AM	relay	Relay disconnect: 5dttdsjq3oi ((Agent WAN IP))
8:03:37 AM	relay	Relay holding: ggymzihzlkr ((Agent WAN IP)) Authenticated

8:03:37 AM	httpheaders	GET, /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ@iODtoIy4vJOHMAL1YWmw8&id=ggymzihzlkr&auth=kzX6rlnHUx$5zNbbmmBfFPnqv2ls47gYFp3irsG@0O0eoxljQ051ajL$lmTV4TRwaXfLcbqtFm7pP8pNnB2zBEZ$FksPeS8Gi5VmXuCKM2nPpQkWOn8YBhv3xI4aPeL@N@3uZVMbfZ80zg==, [object Object]

8:03:37 AM	relay	Relay disconnect: ggymzihzlkr ((Server WAN IP))
8:03:37 AM	relay	Relay holding: ggymzihzlkr ((Server WAN IP)) 

8:03:37 AM	httpheaders	GET, /meshrelay.ashx/.websocket?p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ%40iODtoIy4vJOHMAL1YWmw8&id=ggymzihzlkr&rauth=vQ%24nDK77BWdQ3yWr1DiYbPT6TuvgzHGq5JNaQZTyjgGFSxwS336UcijuiQdo7IPC3KQg%40NyomYmGS1fBmJkgYupQVuAwKXuK27YAeKHTXQHj7rlnaT7R%24A==, [object Object]

8:03:36 AM	relay	Relay disconnect: hcxd68eosm ((Server WAN IP) --> (Agent WAN IP))
8:03:36 AM	relay	Relay connected: hcxd68eosm ((Server WAN IP) --> (Agent WAN IP))

8:03:36 AM	httpheaders	GET, /meshrelay.ashx/.websocket?p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ%40iODtoIy4vJOHMAL1YWmw8&id=hcxd68eosm&rauth=vQ%24nDK77BWdQ3yWr1DiYbPT6TuvgzHGq5JNaQZTyjgGFSxwS336UcijuiQdo7IPC3KQg%40NyomYmGS1fBmJkgYupQVuAwKXuK27YAeKHTXQHj7rlnaT7R%24A==, [object Object]

8:03:36 AM	relay	Relay holding: hcxd68eosm ((Agent WAN IP)) Authenticated

8:03:36 AM	httpheaders	GET, /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ@iODtoIy4vJOHMAL1YWmw8&id=hcxd68eosm&auth=kzX6rlnHUx$5zNbbmmBfFPnqv2ls47gYFp3irsG@0O0eoxljQ051ajL$lmTV4TRwaXfLcbqtFm7pP8pNnB2zBEZ$FksPeS8Gi5VmXuCKM2nPpQkWOn8YBhv3xI4aPeL@N@3uZVMbfZ80zg==, [object Object]

8:03:35 AM	relay	Relay disconnect: 3nwftqsef17 ((Server WAN IP) --> (Agent WAN IP))
8:03:35 AM	relay	Relay connected: 3nwftqsef17 ((Server WAN IP) --> (Agent WAN IP))

8:03:35 AM	httpheaders	GET, /meshrelay.ashx/.websocket?p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ%40iODtoIy4vJOHMAL1YWmw8&id=3nwftqsef17&rauth=vQ%24nDK77BWdQ3yWr1DiYbPT6TuvgzHGq5JNaQZTyjgGFSxwS336UcijuiQdo7IPC3KQg%40NyomYmGS1fBmJkgYupQVuAwKXuK27YAeKHTXQHj7rlnaT7R%24A==, [object Object]

8:03:35 AM	relay	Relay holding: 3nwftqsef17 ((Agent WAN IP)) Authenticated

8:03:35 AM	httpheaders	GET, /meshrelay.ashx/.websocket?browser=1&p=2&nodeid=node//FIJmFpPeSwqzXyIwBeIPACDVzVx0ES4YdCRZ4tPyvQ@iODtoIy4vJOHMAL1YWmw8&id=3nwftqsef17&auth=kzX6rlnHUx$5zNbbmmBfFPnqv2ls47gYFp3irsG@0O0eoxljQ051ajL$lmTV4TRwaXfLcbqtFm7pP8pNnB2zBEZ$FksPeS8Gi5VmXuCKM2nPpQkWOn8YBhv3xI4aPeL@N@3uZVMbfZ80zg==, [object Object]

**Comment by NiceGuyIT** [comment]
Related to or same as [#5302](https://github.com/Ylianst/MeshCentral/issues/5302): Cannot connect reliably using terminal or VNC connect button - shows disconnect immediately

**Comment by si458** [comment]
related to #5302 please can you close this issue @frogweh and follow the other issue
