### ISSUE TITLE
ntfy and --resetaccount

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#5310]
Hello, long time, no see !
I've tryed to implement ntfy as 2 factor (as anything else I've tried don't work), and it don't work (as expected) but when I use "node ~/node_modules/meshcentral --cert `<DNS>` --domain `<DNS>` --pass `'<PW>'` --resetaccount `user//<ID>`" (stopped before and relaunched after), it still ask for a ntfy second factor.

Usually, "node --resetaccount" disable 2 factor and it don't disable ntfy ...
version used 1.1.10

**Comment by Nothing2Do** [comment]
sidenote, access can be restored if you disable "messaging"  in your config.json (and use "_messaging"). but, anyway, it's a bug

**Comment by si458** [comment]
just going to look into this for you, please can you share your `config.json` (hide sensitive stuff obvs)

**Comment by si458** [comment]
i have been able to get it to work no problems here but it was a learning curve!?
```
  "messaging": {
    "ntfy": true
  }
```
1. login with an account without messaging setup
2. click your username at the top right hand side
3. click `manage messaging`
4. select ntfy and enter your topic you have created
5. you will be sent a verification code, enter it and click ok
6. then logout
7. now try logging back in
8. you will be greaeted with a box saying 'TOKEN' IGNORE THIS AND CLICK THE BLUE BUBBLE ICON BELOW IT
9. it will then send you a code, enter the code into a new box that appears
10. you are now logged in!

**Comment by si458** [comment]
the other issue is ntfy isnt a 2fa factor, its a messaging factor!
so i dont think `--resetaccount` will work, maybe `--resetaccount` needs to also remove the messaging factors?

**Comment by Nothing2Do** [comment]
I'm sorry for the waiting time. ntfy isn't 2fa, but anyway, it ask for a second factor using the ntfy icon (https://<DNS>/images/login/2fa-messaging-48.png) with the mail icon too (I suppose I can add some other 2fa).
my config.json, 
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "help.nothing2do.fr,hell.nothing2do.fr",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 442,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "compression": true,
    "wscompression": true,
    "agentwscompression": true,
    "minify": true,
    "webRTC": true,
    "selfUpdate": false,
    "welcomeText": "Welcome to my doorstep (heaven/hell/life) !",
    "_welcomePicture": "mainwelcome.jpg",
    "_welcomePictureFullScreen": false,
    "meshMessengerTitle": "MeshMessenger",
    "_meshMessengerPicture": "messenger.png",
    "userNameIsEmail": true,
    "publicPushNotifications": true,
    "AllowLoginToken": true,
    "webPush": { "email": "mc@nothing2do.fr" },
    "_agentPort" : 1234,
    "manageCrossDomain":[ "user//mc@nothing2do.fr" ],
    "manageAllDeviceGroups": [ "user//mc@nothing2do.fr" ],
    "manageCrossDomain": [ "user//mc@nothing2do.fr" ],
    "orphanAgentUser": "lost",
    "CookieEncoding":"hex",
    "maxinvalid2fa": {
       "time" : 3,
       "count" : 3,
       "coolofftime" : 10
    },
   "meshErrorLogPath": "/home/gaby/meshcentral-logs/",
   "authLog": "/home/gaby/meshcentral-logs/auth.log",
   "log": [
        "cookie",
        "dispatch",
        "main",
        "peer",
        "web",
        "webrequest",
        "relay",
        "webrelaydata",
        "webrelay",
        "mps",
        "mpscmd",
        "swarm",
        "swarmcmd",
        "agentupdate",
        "agent",
        "cert",
        "db",
        "email",
        "amt",
        "httpheaders",
        "websocket"
    ]

   },
  "domains": {
    "": {
      "title": "Nothing2do.fr's throne",
      "title2": "Heaven's door",
      "loginfooter": "Soyez indulgent, je ne suis qu'un petit serveur privé ...",
      "footer": "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. GANDHI",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "agentInviteCodes" : true,
      "consentMessages": {
        "title": "MeshCentral",
        "desktop": "{0} requesting remote desktop access. Grant access?",
        "terminal": "{0} requesting remote terminal access. Grant access?",
        "files": "{0} requesting remote files access. Grant access?"
      },
      "notificationMessages": {
        "title": "MeshCentral",
        "desktop": "{0} started a remote desktop session.",
        "terminal": "{0} started a remote terminal session.",
        "files": "{0} started a remote files session."
      },
      "agentCustomization": {
        "displayName": "Nothing2do.fr® Product™",
        "description": "Nothing2do.fr® agent based on meshagent.",
        "companyName": "FwF",
        "serviceName": "helper",
        "fileName": "agent"
      }
    },
    "hell": {
      "title": "l'enfer de nothing2do.fr",
      "title2" : "Helheim",
      "loginfooter": "Soyez indulgent, je ne suis qu'un petit serveur privé (même en viking) ...",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "dns": "hell.nothing2do.fr"
    },
    "heaven": {
      "title": "le paradis de Nothing2Do.fr",
      "title2": "Vahlalla",
      "loginfooter": "Soyez indulgent, je ne suis qu'un petit serveur privé ...",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "meshcentral@nothing2do.fr",
    "names": "help.nothing2do.fr",
    "production": true
  },
  "smtp": {
	"host": "smtp.xxx.xxx",
	"port": 465,
	"from": "xxx",
	"user": "xxx",
	"pass": "xxx",
        "tls": true
  }
}

**Comment by si458** [comment]
@Nothing2Do yeh it seems when you first login it asks for your 2fa code, but ntfy, pushover, email, etc ISNT 2fa,~
its messaging, so you have to click on whichever icon button underneath to then get another prompt which then sends your 2fa

i fixed the `--resetaccount` with messaging for you #5331

but also maybe we could see if the user has a 2fa setup (HWKEY or TOTP code)
then if not, check if they have a messaging setup,
if they have messaging setup but no 2fa then just go straight to the relevant messaging 2fa screen and do the code etc,
saves messing around clicking the extra button and getting confused why it asks for a code but you never get one?

**Comment by Nothing2Do** [comment]
it isn't a second factor but it give you a way to prove that you own an other device. Isn't it the very definition of a second factor ? your password being the first factor (something you know), and the 2 factor, being something you have (ntfy handle to be precise, pushover for your phone, email for your mail account, etc ...)

**Comment by si458** [comment]
> it isn't a second factor but it give you a way to prove that you own an other device. Isn't it the very definition of a second factor ? your password being the first factor (something you know), and the second factor, being something you have (ntfy handle to be precise, pushover for your phone, email for your mail account, etc ...)

I think the way its setup at the moment is ok as you can use the messaging as 2fa,
The messaging also provides a way to alert you of events like devices on and off

**Comment by Nothing2Do** [comment]
thanks for the push request. see you soon !
