### ISSUE TITLE
Closing the Privacy Bar doesn't close the remote

### ISSUE THREAD

**Issue by metal12345** [Ylianst/MeshCentral#5315]
**Describe the bug**
When pressing the "X" on the privacy bar, the remote access is not ended, and the privacy bar closes.
This only happens when "Prompt for Consent" is on. 

**Expected behavior**
Users need to know whether they are being remotely controlled.

**Server Software (please complete the following information):**
 - OS: Agnostic
 - Version: [e.g. 1.1.10]

**Comment by si458** [comment]
The is already multiple issues about this, please follow those and close this issue

#5316

**Comment by metal12345** [comment]
Ah, my previous search came up empty. Closed.
