### ISSUE TITLE
ERROR: MeshCentral failed with critical error

### ISSUE THREAD

**Issue by KDima23** [Ylianst/MeshCentral#5316]
**Describe the bug**

Meshcenral failed to start after meshcentral update from 1.1.5 to 1.1.10
Error: Command failed: /home/user/.nvm/versions/node/v16.20.0/bin/node /home/user/meshcentral/node_modules/meshcentral
/home/user/meshcentral/node_modules/meshcentral/certoperations.js:293
                acmconfig.hashAlgorithm = r.certs[0].md.algorithm;

Potentially due to below commit
https://github.com/Ylianst/MeshCentral/pull/5243/commits/43c16d02f9c5538c1dbc9459eaeff5a4a250d8bd

**Expected behavior**
We expect to start meshcentral.

**Server Software (please complete the following information):**
 - OS: [Amazon Linux 2]
 - Virtualization: [none]
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: [e.g. 1.1.10]
 - Node: [e.g. 16.20.0]

**Comment by si458** [comment]
have you tried the latest LTS version 18?

**Comment by KDima23** [comment]
Yes I tried.
node version: v18.17.1
os: Ubuntu 20.04.6 LTS

The same issue
Looks like there are somewhere bug in meshcentral/node_modules/meshcentral/certoperations.js
By this commit https://github.com/Ylianst/MeshCentral/commit/43c16d02f9c5538c1dbc9459eaeff5a4a250d8bd
below line was added a few months ago
acmconfig.hashAlgorithm = r.certs[0].md.algorithm;

 r.certs[0].md.algorithm always null
 
![image](https://github.com/Ylianst/MeshCentral/assets/33837241/a6052c4b-869e-472f-b156-cdd434fe5a07)

**Comment by si458** [comment]
Please can you follow the bug template in the future as it has stuff we need to help you

Please can u share ur config.json
How are u doing the ssl? Ur own cert, let's encrypt, cloudflare proxies?

**Comment by KDima23** [comment]
**Describe the bug**
Meshcenral failed to start after meshcentral update from 1.1.5 to 1.1.10

**To Reproduce**
Steps to reproduce the behavior:
1. update meshcentral to meshcentral 1.1.10 version
2. start meshcentral '....'
4. See error

**Expected behavior**
 We expect to start meshcentral.

**Screenshots**
![264250269-a6052c4b-869e-472f-b156-cdd434fe5a07](https://github.com/Ylianst/MeshCentral/assets/33837241/8e70a56f-6717-44cb-999e-885f8abf9e15)


**Server Software (please complete the following information):**
 - OS: [Ubuntu]
 - Virtualization: [N/A]
 - Network: [WAN, aws load balancer, ssl offload]
 - Version: [1.1.10]
 - Node: [18.4.0]

**Client Device (please complete the following information):**
 - Device: [PC]
 - OS: [Ubuntu]
 - Network: [Remote over WAN]
 - Browser: [e.g. Google Chrome]


**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**
Add any other context about the problem here.

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "provisionserver.example.com",
    "WANonly": true,
    "LANonly": false,
    "_sessionKey": "MyReallySecretPassword1",
    "mariaDB": {
      "host": "MeshCentralRDShost",
      "user": "MeshCentralRDSuser",
      "port": 3306,
      "password": "MeshCentralRDSpassword",
      "_connectionLimit": "number",
      "database": "meshcentralrdsdb",
      "awsrds": true
    },
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "nightMode": 0,
    "tlsOffload": true,
    "_mpsTlsOffload": true,
    "maxInvalidLogin": {
      "time": 10,
      "count": 10,
      "coolofftime": 10
      },
    "rootCertCommonName": "example Root CA",
    "mpshighsecurity": true,
    "allowLoginToken": true,
    "authLog": "meshcentral-data/auth.log"
  },
  "domains": {
    "": {
      "title": "example MeshCentral",
      "_title2": "Servername",
      "_minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "amtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-vprocert.crt", "rootCA.crt" ],
            "keyfile": "amtacm-vprocert.key"
          }
        }
      },
      "ssh": true,
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```
 if you comment out the line 265 in certoperations.js, does it then start ok? , yes it works 
 What is the purpose of 265 line ?
 Why we need this  algorithm?

**Comment by si458** [comment]
i ment in the future follow the bug template when you first post an issue but thats for updating with your config etc! 👍 
im guessing you use the Intel AMT and i dont use it so i have no clue as to what it does?
but if it works with the line commented out, ill do a PR to ignore it if its null,
unless @Ylianst can explain if its important?
