### ISSUE TITLE
ubuntu boot sequence start meshcentral before network. fixed with systemd

### ISSUE THREAD

**Issue by Nothing2Do** [Ylianst/MeshCentral#5317]
On Ubuntu, the certificate won't be created (and some weird permission) because the network isn't up when meshcentral try to make one.
solution : the first meshcentral.service (the one created when we install mescentral with : "node ~/node_modules/meshcentral --install") should include : 
"[Unit]
Description=description
Wants=network-online.target  <-------------- this line is important
After=network-online.target  <--------------- and this one too 
[Service]
... ". And everything work like a charm, even with ubuntu (don't laugh at me, almost every body start here !)

**Comment by si458** [comment]
have you tried doing these steps and seeing if it works?
https://ylianst.github.io/MeshCentral/install/install2/#automatically-starting-the-server

**Comment by si458** [comment]
ok thanks ill look at doing a PR for you as to be honest why would you start meshcentral without network 😆

**Comment by si458** [comment]
#5318 done for you 👍

**Comment by Nothing2Do** [comment]
Something has changed within systemd, and the "want" line can be commented to avoid an unnecessary error in log ...

**Comment by si458** [comment]
> Something has changed within systemd, and the "want" line can be commented (or, even, deleted) to avoid an unnecessary error in log ...

whats the OS/Version you are using?

**Comment by Nothing2Do** [comment]
I use : $ cat /etc/os-release
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
[...]
basically, it's debian with modified deb source ...

**Comment by Nothing2Do** [comment]
I use : $ cat /etc/os-release
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
[...]
basically, it's debian with modified deb source ... and mesh v1.1.10
