### ISSUE TITLE
Evaluate X-Forwarded-For header without TLS offloading

### ISSUE THREAD

**Issue by FelR** [Ylianst/MeshCentral#532]
When running a reverse proxy and mesh central server on different hosts I'd like to encrypt the traffic between the hosts using ssl. If I enable TLS offloading, the mesh central server won't accept encrypted traffic; if I disable TLS offloading, the mesh central server won't evaluate the X-Forwarded-For header and therefore show wrong IP addresses. Please provide a setting to evaluate the header despite using tls encryption.

**Comment by Ylianst** [comment]
This is a good request and should not be difficult to add. I will get this added soon, probably today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-w with a fix for this. In config.json add:

```
{
  "settings": {
    "Port": 4430,
    "TrustedProxy": "127.0.0.1"
  }
}
```

TrustedProxy can be true to accept X-Forwarded-For from anyone, or set the IP address to only accept X-Forwarded-For from that address. Can you please test and make sure it work? Thanks.

**Comment by FelR** [comment]
Thank you for the fast implementation. Works like a charm.

**Comment by Ylianst** [comment]
Nice!! Thanks for checking that. Happy to help.
