### ISSUE TITLE
Cannot Fully Connect to Agents

### ISSUE THREAD

**Issue by AlphaIrri** [Ylianst/MeshCentral#5320]
**Describe your issue**
I have MeshCentral in a docker container on unRaid. I am using NGINX PM for reverse proxy and CloudFlare for proxied DNS records.
I can connect to my MeshCentral dashboard without issue on LAN and WAN. I started having issues with the agents in the last few weeks after having this setup for a year. I'll click Connect and it'll go to Connecting... Setup... Disconnected. Sometimes it will hang on "Setup...". I can't actually establish connection to any of the agents even if they show as online.

I've tried ignoreAgentHashCheck and that did not help.
The dashboard is showing a Let'sEncrypt SSL instead of my CloudFlare SSL that is in NGINX PM.

**Docker: MeshCentral**
 - Name: meshcentral
 - Network: nginx
 - app IP: 172.18.0.3:443/TCP | host IP: 192.168.1.226:8086

**Docker: NGINX PM**
 - Name: NginxProxyManager
 - Network: nginx
 - app IP: 172.18.0.2:4443/TCP | host IP: 192.168.1.226:18443
 - app IP: 172.18.0.2:8080/TCP | host IP: 192.168.1.226:1880
 - app IP: 172.18.0.2:8181/TCP | host IP: 192.168.1.226:18181

<img width="364" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/6099192/721ee4b8-2f37-471d-a2ae-902ea3640d62)">
<img width="364" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/6099192/8a62d4b8-7220-466e-84f3-f929be035ddf)">
<img width="364" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/6099192/d0296c30-a669-4b5a-ad89-01ba6bc3b9e2">

**Port Forwards**
 - Port: 443 | Dest Port/IP: 192.168.1.226:18443
 - Port: 80 | Dest Port/IP: 192.168.1.226:1880

**Server Software (please complete the following information):**
 - OS: unRaid
 - Virtualization: Docker
 - Network: LAN/WAN, reverse proxy, cloudflare, cloudflare ssl
 - Version: 1.1.10
 - Node: v18.17.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10/11
 - Network: Local to Meshcentral, Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: 

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10/11
 - Network: Local to Meshcentral, Remote over WAN
 - Current Core Version (if known): 

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "sub.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "sessionkey",
    "port": 443,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "_TLSOffload": "192.168.1.226",
	"TLSOffload": "172.18.0.2",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
	"ignoreAgentHashCheck": true,
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": "",
      "keepLastDaysBackup": "",
      "zippassword": ""
    }
  },
  "domains": {
        "": {
        "_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "false",
        "_userNameIsEmail": true,
    "certUrl": "https://sub.domain.com:443"
        }
  }
}
```

**Comment by hiddenpcmaster** [comment]
Following...

**Comment by si458** [comment]
#5302 duplicate issue please close and follow other issue

**Comment by AlphaIrri** [comment]
Thank you for the link to other issue. Will follow there.
