### ISSUE TITLE
User & Installation guide missing

### ISSUE THREAD

**Issue by RichardBurt65** [Ylianst/MeshCentral#5324]
The URL for the user and installation guides are giving a 404 error. 

Have they gone completely?

**Comment by si458** [comment]
No, they are still there as @Ylianst moved the site from azure to github, just in a different folder!

https://github.com/Ylianst/MeshCentralSite/tree/main/docs

I will do a PR to rename the links in the readme later for others!

**Comment by si458** [comment]
Links fixed - https://meshcentral.com/downloads.html
Links Fixed - https://github.com/Ylianst/MeshCentral
