### ISSUE TITLE
Multiple Monitors buttons sometimes not showing

### ISSUE THREAD

**Issue by cullorblind** [Ylianst/MeshCentral#5339]
**Describe the bug**
A minor bug, but still a small annoyance for some of our users.
Multiple Display buttons not showing on first load when connected from one of the "Desktops" views.
This one seemed a bit intermittent, but I think I finally found a way to reliably reproduce the problem.

**To Reproduce**
1. Login (or refresh the browser)
2. Click on one of the two 'Desktops' view buttons at the top right
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/0dd95f3d-e0b1-4e5c-9d97-293fdcacddfa)
3. Click 'Connect All' or Click a single desktop to connect.
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/3dd1a87a-e964-48fa-a756-18f2fec69a04)
4. Click the Desktop name to bring that desktop up
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/d14fedb6-77d4-450d-9b41-da4df613a518)
5. See that multiple monitors buttons are missing.
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/9f640061-8a33-4339-b69e-c753e9cb5d2b)
Additionally, you can get them to show up by clicking Disconnect and Connect.
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/553da62b-83cb-4f2e-8bf9-1fc9d6d546c7)
Also tested with Google Oauth users and local users.

**Expected behavior**
Multi monitor buttons should show on first load.

**Server Software:**
 - OS: Digital Ocean Rocky Linux 8.5
 - Virtualization: None
 - Network: WAN
 - Version: 8.5
 - Node: 10.24.0 installed via RPM
 - Auth: Google Oauth2 and local

**Client Device:**
 - Device: Tried from multiple desktops running Windows 10
 - OS: Windows 10 Pro 22H2
 - Network: Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: n/a

**Remote Device:**
 - Devices: HP Elitedesk 800 G1 / Dell Optiplex 7060
 - OS: Windows 10 Pro 22H2
 - Network: Remote over WAN
 - Current Core Version: Current Core: Dec 9 2022, 2577413753

**Additional context**
Freshly installed server within the last few days.

**Your config.json file**
Obscured keys/secrets/some domains here and at'd email to hopefully prevent email address scraping on github.
```
[root@minion-rockylinux-s-2vcpu-4gb-intel-nyc3-01 meshcentral]# cat meshcentral-data/config.json
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a se
ction and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral.awbb.net",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "************************************************************",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "AW Broadband",
      "title2": "MeshCentral",
      "_minify": true,
      "ManageAllDeviceGroups": [ "*********" ],
      "newAccounts": false,
      "agentInviteCodes": true,
      "_userNameIsEmail": true,
      "authStrategies": {
        "google": {
          "_callbackurl": "https://meshcentral.awbb.net/auth-google-callback",
          "newAccounts": true,
          "_newAccountsUserGroups": [ "ugrp//xxxxxxxxxxxxxxxxx" ],
          "clientid": "************************************.apps.googleusercontent.com",
          "clientsecret": "******************************"
        }
      }
    },
    "adair": {
      "dns": "******.********.net",
      "title": "Adair",
      "title2": "MeshCentral",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    },
    "prwn": {
      "dns": "meshcentral.prwn.net",
      "title": "PRWN",
      "title2": "MeshCentral",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "email": "admin***at***awbb.net",
    "names": "meshcentral.awbb.net,******.********.net,meshcentral.prwn.net",
    "skipChallengeVerification": true,
    "production": true
  }
}
```

**Comment by si458** [comment]
Thanks for the detailed report!

I can confirm the same issue on my mobile (I use desktop view on my fold 3)

The exact steps you gave cause the issue

so I'm guessing when u connect on the small view,
it believes u have 1 monitor (as u wouldn't want to see all your monitors)
Then when you go into the normal desktop view, it's not checking if u have multiple monitors until u disconnect/reconnect!

Will have a look when I get a chance for you!

**Comment by si458** [comment]
so turns out much easier than i throught! 
after a long night and alot of tea, fix was so simple for you!
patch in the works

**Comment by silversword411** [comment]
... gotta love those missing char bugs.

There was one in TRMM that was there over a year before I started wondering why it didn't work on iOS but worked everywhere else. Because it was missing the trailing / on paths of course.
