### ISSUE TITLE
Bug: Opening chat with users requires "Full Server Administrator" permission (0.4.1-v)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#534]
To be able to open a chat with a user, one needs to have Full Administrator rights for server management, otherwise the chat tab opens only for the MC user, but not on the client being managed. Even "Full Administrator" permissions for the managed machine's mesh do not suffice.

In my opinion, chat should be a separate permission to be given to users on mesh/group level, and lack of this permission should remove or grey-out/inactivate the chat button in the Desktop tab.

**Comment by Ylianst** [comment]
This is not good. I will to look into this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.2-p with a fix for this. Let me know if it works. For now, device chat is tied to the device group "Remote Control" permission. I could consider a separate permission if needed.

**Comment by Ylianst** [comment]
FYI. Just patched [meshcentral.com](https://meshcentral.com) with v0.4.2-p to get this fix.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.2-r with a new "Chat & Notify" device group permission as you originally asked. This should close this issue. Let me know if it works.

![MC2-ChatAndNotify](https://user-images.githubusercontent.com/1319013/66957440-1ba39780-f01b-11e9-8139-64acfc2157b5.png)

**Comment by veitw** [comment]
Works great for me, thank you very much. :)
