### ISSUE TITLE
How to disable - Consent & Notification bar when SHARE THE DEVICE WITH GUEST (L3 Support)

### ISSUE THREAD

**Issue by somesh1968** [Ylianst/MeshCentral#5341]
**Describe your issue**
Self Hosted MeshCentral.
Service desk take control of user desktop and does troubleshooting. Sometime they SHARE THE DEVICE WITH GUEST which is L3 support. When L3 support access end use desktop the Privacy Bar Shows on end user computer. How can i disable it?

**Screenshots**
NA

**Server Software (please complete the following information):**
 - OS: Windows
 - Virtualization: NA
 - Network: LAN/WAN
 - Version: Latest
 - Node: Latest

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over WAN]
 - Browser: Google Chrome
 - MeshCentralRouter Version: NA

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over WAN]
 - Browser: Google Chrome
 - MeshCentralRouter Version: NA

**Your config.json file**
```
{
   "settings": {
      "cert": "DOMAIN", 
      "minify": true, 
      "port": 443, 
      "aliasport": 444, 
      "redirport": 80, 
      "rediraliasport": 80, 
      "relayport": 453, 
      "relayaliasport": 463
   }, 
   "domains": {
      "": {
         "title": "Help", 
         "agentcustomization": {
            "displayName": "-----------------", 
            "description": "-----------------", 
            "companyName": "-----------------", 
            "serviceName": "-----------------", 
            "image": "agent-logo.png", 
            "fileName": "--------"
         }, 
         "agentfileinfo": {
            "icon": "agent.ico", 
            "filedescription": "-----------------", 
            "fileversion": "0.1.2.3", 
            "internalname": "-----------------", 
            "legalcopyright": "-----------------", 
            "originalfilename": "------------.exe", 
            "productname": "-----------------", 
            "productversion": "v0.1.2.3"
         }, 
         "_guestdevicesharing": true, 
         "_agentselfguestsharing": {
            "expire": 120
         }, 
         "_consentmessages": {
            "title": "NA", 
            "desktop": "{0} . GA", 
            "terminal": "{0} . GA", 
            "files": "{0} . GA", 
            "consentTimeout": 30, 
            "autoAcceptOnTimeout": true
         }, 
         "_notificationmessages": {
            "title": "NA", 
            "desktop": "{0} y.", 
            "terminal": "{0} y.", 
            "files": "{0} y."
         }, 
         "userconsentflags": {
            "desktopnotify": false, 
            "terminalnotify": false, 
            "filenotify": false, 
            "desktopprompt": false, 
            "terminalprompt": false, 
            "fileprompt": false, 
            "desktopprivacybar": false
         }, 
         "_urlswitching": false, 
         "_desktopprivacybartext": "Pbar: {0}, {1}", 
         "_limits": {
            "_maxDevices": 100, 
            "_maxUserAccounts": 100, 
            "_maxUserSessions": 100, 
            "_maxAgentSessions": 100, 
            "_maxSingleUserSessions": 10
         }
      }
   }, 
   "letsencrypt": {
      "email": "-----------------", 
      "domains": "-----------------", 
      "production": true
   }
}
```

**Comment by si458** [comment]
you currently cant if i remember as its built in to let the end device know that a person is connected (a guest)

as you only options you have is 'notify' or 'prompt for consent'

would you like another few options in the drop down to say 'no notify' and 'no consent' ?

**Comment by somesh1968** [comment]
Many time there L3 are 3'rd party who don't have access to MeshCentral. 
Does this mean that notification bar can't be disabled?

**Comment by si458** [comment]
> Many time there L3 are 3'rd party who don't have access to MeshCentral. Does this mean that notification bar can't be disabled?

@somesh1968 sadly its hard coded with the 2 options at the moment,
and would need sometime to do a bit of rework to get the other options

**Comment by somesh1968** [comment]
> > Many time there L3 are 3'rd party who don't have access to MeshCentral. Does this mean that notification bar can't be disabled?
> 
> @somesh1968 sadly its hard coded with the 2 options at the moment, and would need sometime to do a bit of rework to get the other options

If possible, Can you refer me to file and section where this option can be customized.

**Comment by silversword411** [comment]
https://docs.tacticalrmm.com/tipsntricks/#enable-remote-control-options

**Comment by tomsik-radek** [comment]
I guess you could bypass those prompts completely by using a background only agent? But I personally (on the IT side) don't like that techs could take over a logged in desktop without the persons knowledge
