### ISSUE TITLE
Find Users?

### ISSUE THREAD

**Issue by tyl0re** [Ylianst/MeshCentral#5344]
**Is your feature request related to a problem? Please describe.**
Normally i communicate  with User, on my Devices I can see the "Login User" of the PC, but i cant search for a User.

**Describe the solution you'd like**
it woud be good to have another butten "Search in" "User,Ip,Name"

**Describe alternatives you've considered**
I could also work if the List is loaded Completely so an Search in Website would work

**Comment by si458** [comment]
in the search box at the top you can enter `u:USERNAMEHERE`
same with IP address `ip:IPHERE`

i must do a guide for the search box as the is loads of shortcuts

**Comment by tyl0re** [comment]
Tahnks close
