### ISSUE TITLE
Bug: "Send keys" function missing for clients in agentless meshes/groups (0.4.1-v)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#535]
In the Desktop tab of managed clients in AMT-only meshes, the "Send" button and corresponding drop down for key (combination) selection) is missing. As this is shown in both the Desktop tab of agent-managed clients and in the integrated MeshCommander in the Intel AMT tab, I assume this is a bug.

It would be great to be able to send combination such as Ctrl+Alt+Del to an agent-less managed client without the need to dive into its Intel AMT tab and wait for the Remote Desktop item to show up.

**Comment by Ylianst** [comment]
You right! Published MeshCentral v0.4.1-w with a fix for this. Let me know if it works.

**Comment by veitw** [comment]
> You right! Published MeshCentral v0.4.1-w with a fix for this. Let me know if it works.

Works like a charm, thank you very much for great software and support. :)
