### ISSUE TITLE
Change Password LDAP Integration Crash

### ISSUE THREAD

**Issue by lleal99B** [Ylianst/MeshCentral#5358]
**Describe the bug**
We are setting up the LDAP integration and testing any use that our "creative" users may find.
After setting up the LDAP integration and test the automatic group creation, etc. All working as expected we found that if a user tries to change the password with the My Account options and click OK after filling the passwords fields the service crashes.

**To Reproduce**
1. Set up the LDAP integration 
2. Login with a LDAP user 
3. Setup the Auth Application and type the token
4. Log off
5. Log on and type the token again
6. Go to My Account
7. Select change password
8. Type the current LDAP password and a new password
9. Click OK
10. The service crashes and after restart the users can log in again.

**Expected behavior**
The change password option must do nothing or even better not be shown.

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: None
 - Network: LAN/WAN, traefik reverse proxy
 - Version: 1.1.11
 - Node: ?

**Client Device (please complete the following information):**
 - Device: HP Laptop
 - OS: Windows 11
 - Network: WAN
 - Browser: Edge
 - MeshCentralRouter Version: NA

**Remote Device (please complete the following information):**
 - Device: QEMU VM
 - OS: Windows 11
 - Network: LAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Comment by si458** [comment]
i dont think you should be able to change ur password as its linked via LDAP ?
can you share ur config.json u used for testing?

**Comment by lleal99B** [comment]
Hi,

Thank you for your answer.

Yes, we don't want the Active Directory password to be changed through MeshCentral LDAP integration. We have secured channels to do that task. The issue is the option is available in My Account tab and a user may try to change it's password with that option. If the dialog do nothing there's no problem but trying to do it crashes the service.

The files contains:
- MyAccount tab picture
- Debug information when the crash happens
- Configuration file (users, passwords, groups, and domains edited but I think it makes sense)

[mesh-central error.txt](https://github.com/Ylianst/MeshCentral/files/12652365/mesh-central.error.txt)
![MeshCentralMyAccount](https://github.com/Ylianst/MeshCentral/assets/67063129/1a3a3e94-4f9a-4822-b1f6-7770e39517f1)

[config.txt](https://github.com/Ylianst/MeshCentral/files/12652707/config.txt)

**Comment by lleal99B** [comment]
Update: Tomorrow I'll try to place an impossible password policy, like min 10, max 10, 3 upper, 3 lower, 3 numeric and 3 nonalpha something like that. But if the change password option is hidden or doesn't crash the server or something wrong in my config much better.

**Comment by si458** [comment]
You can see here it already shows the password section IF `domainauth==false` and hides otherwise

https://github.com/Ylianst/MeshCentral/blob/04a71800fa4ce94fb75ac480a4562498d17b8fbf/views/default.handlebars#L2149

And it's setting domainauth to true if it's set to `sspi` 
https://github.com/Ylianst/MeshCentral/blob/04a71800fa4ce94fb75ac480a4562498d17b8fbf/meshuser.js#L550

So we might need to juggle the code to disable the change password if it's ldap too

**Comment by lleal99B** [comment]
I just try the impossible password workaround and it works (min 10, max 10, 3 upper, 3 lower, 3 numeric and 3 nonalpha). Right now, is enough, but not showing the option could be better, I´m already hearing some user complaining because they can change the password in MeshCentral even when they have a specific platform for Active Directory passwords. Thank you for your answers.

**Comment by lleal99B** [comment]
Ok, thanks! Because it´s a production system I can do tests only in no working hours. I was waiting for today afternoon. But if it is not necessary, much better. Also, changing the code of production systems needs some paperwork...

**Comment by si458** [comment]
@lleal99B to be honest i test on my production all the time as i only look after about 80 computers,
but only need to connect to them once in a blue moon (i live on the edge ya no haha)

**Comment by si458** [comment]
temp fix for you @lleal99B 👍 
it will simply just return false now and not attempt to change the password
its exactually the same as the change email!

**Comment by lleal99B** [comment]
Hi @si458, thank you so much for your answer. I´m sorry about the late reply, very busy. It seems to be the solution. Unfortunately, I cannot modify the code in the production server (anyway node undo the changes in production). I hope it will be merged in the next release.
Thank you so much for your help. Best regards.
