### ISSUE TITLE
MeshCentral Assistant - Remove devices automaticallz after disconnected

### ISSUE THREAD

**Issue by tomsik-radek** [Ylianst/MeshCentral#5359]
**Describe your issue**
When you use MeshAgent in Connect mode and the other side disconnects, the device immediately disappears from the web UI. However, when you disconnect from MeshAgent session, the device still remains in the WebUI. Is there a way to automatically remove it apart from the 1 day autoremoval in config.json?

MeshAgent looks like a nice TeamViewer replacement, if I can get this autoremoval working (so it doesn't clutter our group with "dead" devices)

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization: Docker typhonragewind/meshcentral:mongodb-1.1.10
 - Network: WAN mode, Nginx Proxy Manager 
 - Version: 1.1.11

**Client Device (please complete the following information):**
- MeshCentral WebUI

**Remote Device (please complete the following information):**
 - Device:  Laptop
 - OS: Windows 10
 - Network: WAN

**Your config.json file**
```
{

{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.domain.tld",
    "WANonly": true,
    "port": 443,
    "redirPort": 80,
    "AgentPong": 300,
    "TLSOffload": "127.0.0.1",
    "_ignoreAgentHashCheck": true,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "mongodb": "mongodb://mongodb:27017/mesh",
    "mongodbcol": "mesh",
    "WebRTC": "false"
  },
  "domains": {
        "": {
          "siteStyle": 2,
          "title": "Mesh Central",
          "_title2": "title",
          "newAccounts": false,
          "certUrl": "https://meshcentral.domain.tld:443",
          "loginfooter": "This is a private server.",
          "twoFactorCookieDurationDays": 90,
          "nightMode": 0,
          "mobileSite": true,
      }
  }
}

```

**Comment by si458** [comment]
If you click the group name, then click the pencil next to features, you can enable auto remove

I have a group setup which I use just for meshcentral assistant, then when people connect it adds the device to this group, and when the device closes the connection, the computer is auto removed!

The is no feature to auto-delete after so long, it's autodelete after the device disconnects

**Comment by tomsik-radek** [comment]
> If you click the group name, then click the pencil next to features, you can enable auto remove
> 
> I have a group setup which I use just for meshcentral assistant, then when people connect it adds the device to this group, and when the device closes the connection, the computer is auto removed!
> 
> ~The is no feature to auto-delete after so long, it's autodelete after the device disconnects~
> 
> Edit: the is also the feature to autoremove after so long under the features too
> 
> Remember it's per group too!

"remove devices on disconnect"

Yes, this is exactly what I wanted. Perfect, very much thank you!
