### ISSUE TITLE
Recording Session not working

### ISSUE THREAD

**Issue by lukgit17** [Ylianst/MeshCentral#5368]
Recording tab not appear in My Users tab and not mcrec files are recorded in destination folder on server when desktop connection is initiated. MeshCentral are installed in Ubuntu server as docker container using image from ghcr.io/gurucomputing/meshcentral-docker:latest . Version of app server is last version 1.1.11 .
SessionRecording was setup in config.json file as below : 

**Your config.json file**
```
  "sessionRecording": {
    "filepath": "/home/safiradmin/recordings",
    "index": true,
    "maxRecordings": 100,
    "protocols": [ 1, 2 ]
  }

**Comment by si458** [comment]
Please can you share ur docker config?

Also have u tried the official docker image?
https://github.com/Ylianst/MeshCentral/pkgs/container/meshcentral

Also what is the docker logs when the container starts?

**Comment by lukgit17** [comment]
I forget to mention that mcrec record are working when I press button after desktop connection was initiated. I want session recording to running automatically when desktop connection was initiated for specific users.
Below is docker-compose.yaml content : 

version: '2'
# This is example 2 from the documentation
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - ./container-data/meshcentral-data:/meshcentral/meshcentral-data
      - ./container-data/meshcentral-files:/meshcentral/meshcentral-files
      - ./container-data/meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGODB_URL=mongodb://meshcentral-db:27017
      - MONGODB_NAME=meshcentral
      - DB_ENCRYPT_KEY=${DB_ENCRYPT_KEY}
      - AGENT_PORT=4443
    ports:
      - 4444:443
      - 4443:4443
    networks:
      - meshcentral-nw
  meshcentral-db:
    container_name: meshcentral-db
    image: mongo:latest
    restart: "always"
    volumes:
      - ./container-data/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 27017:27017
    networks:
      - meshcentral-nw

networks:
  meshcentral-nw:

**Comment by si458** [comment]
For starters you havent mapped ya folder correctly in docker
Because every time u restart/update the container, it will wipe ur recordings
You need to map the filepath": "/home/safiradmin/recordings" in your docker-compose correctly

Also the reason the recording in the browser works is because that's a local recording which is done in the browser so it will always work

You are trying to get the server to do the recording instead for you

**Comment by lukgit17** [comment]
Sorry, You are right. I was careless in fact is docker image.
But now this warning appear :
**WARNING: Unrecognized configuration option "sessionrecording".**

In config.json modified settings as below : 
  **"sessionRecording": {
    "filepath": "/home/",
    "index": true,
    "maxRecordings": 1000,
    "protocols": [ 1, 2, 5 ]
  }**

**Home** path exist in docker image.
And in docker-compose.yaml add next map folder : 
**- ./container-data/meshcentral-recordings:/home**

**Comment by lukgit17** [comment]
I found issue. Option **sessionRecording** must be moved inside of **domains** option.

**Comment by tomsik-radek** [comment]
> I found issue. Option **sessionRecording** must be moved inside of **domains** option.

Close the ticket please?
