### ISSUE TITLE
Links to Android app doesn't work

### ISSUE THREAD

**Issue by SlavikCA** [Ylianst/MeshCentral#5375]
**Describe the bug**
All links to Android app are broken or not working

**To Reproduce**
I installed mesh to my server. Via Docker.
Works great with Windows and MacOs systems.
But when I open invitations to Android devices, there are 2 problems:

A) BROKEN LINK
1. Open REMOTE AGENT INSTALLATION
2. Click on 'Android APK Download', which leads to https://info.meshcentral.com/downloads/MeshCentral2/meshcentral-agent.apk
3. Error: info.meshcentral.com’s DNS address could not be found

B) Outdated app in Play Store
1. Open REMOTE AGENT INSTALLATION
2. Click on 'Google Play Store', which leads to https://play.google.com/store/apps/details?id=com.meshcentral.agent2
3. Error: This app isn't available for your device because it was made for an older version of Android.

**Server Software:**
 - OS: Synology
 - Virtualization: Docker
 - Network: LAN, exposed to WAN via reverse proxy via Traefik
 - Version: 1.1.10

**Client Device:**
 - Device: Pixel 6
 - OS: Android 13
 - Network: same LAN, as the server

**Comment by si458** [comment]
can u expand on A-Step 1 where so you get this screen/link from?
ive changed all sorts of links in docs etc but possibly missed the Web UI

Also Step B is sadly out of my hands as @Ylianst would need to update the app as its his account!

**Comment by si458** [comment]
once PR fixed for website, ill PR a fix for web ui! https://github.com/Ylianst/MeshCentralSite/pull/2
