### ISSUE TITLE
MeshCentral crashes when i do an amtconfig from a host with a IPv6 mapped IP

### ISSUE THREAD

**Issue by revellion** [Ylianst/MeshCentral#5378]
**Describe the bug**
When i perform a /meshcmd amtconfig run from an Intel AMT client towards MeshCentral, it just stops at "Started APF Tunnel", then the MeshCentral server crashes and restarts (running in container). Also noteworhty is that i run MeshCentral behind TLSOffload/NGINX.

**To Reproduce**
1. Run meshcmd amtconfig
2. Crash

**Expected behavior**
The AMT is confgured and ready to use

**Screenshots**
The logs in mesherrors comes below. 
```
-------- 9/26/2023, 11:57:44 AM ---- 1.1.11 --------

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: getHostByAddr EINVAL 2001:9b1:xxxx:xxxx:4ce4:951f:663b:cd62
    at ResolverBase.getHostByAddr (node:internal/dns/callback_resolver:74:20)
    at /opt/meshcentral/meshcentral/mpsserver.js:736:48
    at /opt/meshcentral/meshcentral/db.js:2223:29
    at /opt/meshcentral/meshcentral/node_modules/mongodb/lib/utils.js:349:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'getHostByAddr',
  hostname: '2001:9b1:xxxx:xxxx:4ce4:951f:663b:cd62'
}
```

Node.js v18.17.1

parts of the IPv6 address is xxxx:xxxx in this paste as a redact.

**Server Software (please complete the following information):**
 - OS: ArchLinux Host
 - Virtualization: Docker
 - Network: LAN, TLS Offload NGINX, IPv4+IPv6 Dual-Stack
 - Version: 1.1.11 (latest)
 - Node: 18.17.1

**Client Device (please complete the following information):**
 - Device: Lenovo Laptop
 - OS: ArchLinux
 - Network: Local to Meshcentral
 - Browser: Chromium

**Additional context**
I've tried just for some testing to run just the dns.reverse function in a NodeJS instance on my local PC (Node 20.7.0). And it doesn't throw a EINVAL on the same data as the NodeJS in the container. Maybe NodeJS in the container is too old to support IPv6 properly?

**Comment by si458** [comment]
are you using an IPV6 ONLY network OR are you using multi-stack ipv4+ipv6?

the line its crashing on is 
`require('dns').reverse(socket.remoteAddr, function (err, hostnames) { })`

however https://nodejs.org/docs/latest-v18.x/api/dns.html#dnsreverseip-callback shows it supports ipv6 in node 18

whats the DNS settings on your meshcentral server?

ive just created `test.js` inside a meshcentral container with the following code
`require('dns').reverse("2606:4700:4700::1111", function (err, hostnames) { console.log(hostnames); });`
then ran `node test.js` and i get the same error, and it only reverse dns looked up cloudflare 1.1.1.1

**Comment by revellion** [comment]
I've just tested to attach to the container and done apk del nodejs npm and apk add nodejs-current which pulls in 20.x.

re-ran Amtconfig and the application didn't crash, now it fails further down the line at 
Getting ready for ACM activation...
Unable to perform signature.


.

And For the information requested. i'm running both IPv4+IPv6 dual-stack concurrently with global addresses on v6.

The DNS setting on the container host points at my local DNS cache on my router. I've tested to enabled IPv6 through the whole container to see if that resolved the issues aswell. But it persisted, so the dns.resolve handling seems to be the culprit.

It wasn't completly trivial to implement IPv6 in the container, had to edit dockers config and the compose file + argument to mongodb to have --ipv6 in it. I have'nt tested restoring the IPv6 functionality after updating the nodejs though...

**Comment by Ylianst** [comment]
I just put in a fix for that the server would not crash when doing a reverse loop up on IPv6 when it's not supported. The reverse lookup is just used to find a better name for the device, if it does not work, it will use the IP address as the name.

However, not a fix for the "Unable to perform signature." problem.
