### ISSUE TITLE
Install agent 32 bits for windows

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#538]
Hello Ylianst, all right?

I am trying to install 32bit agent for windows but it is not working, can you help me?

**Comment by Ylianst** [comment]
Can you explain what is not working? Any details appreciated. Also, what version of Windows are you using? (We don't support XP / Vista).

**Comment by geanferrani123** [comment]
I am running agent installer on windows 7 and windows 10 machines, and none of them worked. Nothing works, I have to install, it signals that installed but when I go to the list of machines in meshcentral, the machine itself does not install. I also take the opportunity to inform you that the installation was the same on Windows Server 2008, 2012 and 2016 machines.

**Comment by PathfinderNetworks** [comment]
Is your antivirus removing or stopping the MeshCentral agent?   There was an issue not too long ago where some antivirus apps were flagging it as malware- especially the 32bit version.

**Comment by MailYouLater** [comment]
So ... you're saying you were able to fix your own issue? Meaning this ticket can be closed, right?

Were you trying to run it with the `notls` config option enabled? or were you trying to run the server on a machine that didn't have an SSL library (e.g. OpenSSL) installed? or was your issue something else?

**Comment by geanferrani123** [comment]
> So ... you're saying you were able to fix your own issue? Meaning this ticket can be closed, right?
> 
> Were you trying to run it with the `notls` config option enabled? or were you trying to run the server on a machine that didn't have an SSL library (e.g. OpenSSL) installed? or was your issue something else?

sorry but this has nothing to do with my problem, i said i solved the part of my antivirus block by installing SSL, my problem is that when generating 32 bit agent i cannot install on 32 bit machines. I also used to say that Agent 64 does not work correctly on windows server systems.

**Comment by MailYouLater** [comment]
Are you getting an error? Can you post a log or a screenshot?

**Comment by geanferrani123** [comment]
Friends, i'm not getting any erro, simply the machine doesn't show up in meshcentral

**Comment by krayon007** [comment]
If you go into the windows service manager, does the service show up there, and show as running?

**Comment by geanferrani123** [comment]
> If you go into the windows service manager, does the service show up there, and show as running?

Yes

**Comment by MailYouLater** [comment]
If you go to the folder where it's installed (Usually `C:\Program Files\Mesh Agent`) is there a `.log` file next to the `.exe` and `.msh`? If so, can you post the contents of it? and the `.msh` file too?

**Comment by krayon007** [comment]
Another thing you can do that will help, is to stop the service in service manager, then open an elevated command prompt, and navigate to the folder where the binary is. (Usually program files/mesh or something similar)

And run the command:
Meshagent run

This will run the agent in console mode, which will show a bunch of connection related messages on the screen. I suspect there is something going on with proxy detection...

**Comment by geanferrani123** [comment]
> Outra coisa que você pode fazer para ajudar é interromper o serviço no gerenciador de serviços, abrir um prompt de comando elevado e navegar até a pasta onde está o binário. (Geralmente, programa arquivos / malha ou algo semelhante)
> 
> E execute o comando: 
> Meshagent run
> 
> Isso executará o agente no modo do console, que mostrará várias mensagens relacionadas à conexão na tela. Eu suspeito que há algo acontecendo com a detecção de proxy ...

Hello friends, good morning!

Bryan, I don't think it's a proxy, because if not the 64-bit agent would also have a problem, but give me a minute I'll perform the test that the friend above asked you to better view.

**Comment by krayon007** [comment]
Which Service Pack is your Windows 7 machine?

**Comment by geanferrani123** [comment]
I tested on one with service pack 1 and one without service pack

**Comment by krayon007** [comment]
Is your machine behind a proxy tho?

**Comment by geanferrani123** [comment]
Yes, however all machines are running on LAN, including meshcentral server. Proxy is not taking any action on meshcentral, otherwise all machines would be in trouble.

**Comment by krayon007** [comment]
Hmmm... I'm trying to reproduce the scenario. I have a Windows 7 SP1 machine, and the only anomaly I found was that it wasn't using a proxy when it should have been, but otherwise it connected correctly, and everything seemed to work.

The output you showed earlier suggests that it is having connection related issues. Is your server referenced in the .msh file directly by IP address, or is it shown as 'local', meaning the agent needs to find it?

**Comment by geanferrani123** [comment]
Bryan, he is referenced by name. This machine I sent you the print is one that has no service pack 1. I don't know what it can be

**Comment by si458** [comment]
closing as you can install the agent on any windows 7 32bit os so long as they are all up to date with latest servivce packs and updates and you have the latest .net framework 4.8 installed
