### ISSUE TITLE
can we put LLMs into this?

### ISSUE THREAD

**Issue by archywillhe** [Ylianst/MeshCentral#5395]
can this be integrated with AutoGPT? any tips on where to start?

**Comment by nroach44** [comment]
Why?

**Comment by Ylianst** [comment]
LOL. I am sure we could. Would it be to assist the administrator or the users?

**Comment by Ylianst** [comment]
I will close this, probably best to the discussion section.

**Comment by archywillhe** [comment]
yeah; or we can put this into LLM too: https://github.com/trholding/llama2.c

> Would it be to assist the administrator or the users?

I think it will be a different use case: like being able to automated perform tasks in remote computer (giving more realiable results than vs puppeteer js)
