### ISSUE TITLE
New Feature Suggestion- Ability to Blank Screen on Client

### ISSUE THREAD

**Issue by dmccracken-livewire** [Ylianst/MeshCentral#54]
It would be helpful to have the ability to blank out the client screen on demand in case you don't want anyone near the client machine to see what you are doing (from a security perspective).

**Comment by jsastriawan** [comment]
Hi Kevin,

Yes that feature is available on AMT KVM. I could work on it and send the patch to Ylian for integration.

For MeshAgent based KVM, that could be difficult. Some manageability vendor actually use custom DPMS driver to blank out the screen.

**Comment by kevinlee-heycoins** [comment]
> Hi Kevin,
> 
> Yes that feature is available on AMT KVM. I could work on it and send the patch to Ylian for integration.
> 
> For MeshAgent based KVM, that could be difficult. Some manageability vendor actually use custom DPMS driver to blank out the screen.

I think AMT KVM is good for now. MeshAgent KVM is a nice to have further in the future. 

Yes I am currently using a second manageability software for the screen blanking feature (they do use their own driver), in conjunction with MeshCentral. With the implementation of the screen blanking feature, I would be able to fully move to MeshCentral as the sole manageability system.

Thank you very much.

**Comment by jsastriawan** [comment]
Kevin,

Additional caveat although you have AMT system, not all OEM enable Firmware Screen Blanking feature when they stitched the firmware.

Regards,



Joko

**Comment by kevinlee-heycoins** [comment]
> Kevin,
> 
> Additional caveat although you have AMT system, not all OEM enable Firmware Screen Blanking feature when they stitched the firmware.
> 
> Regards,
> 
> Joko

Yes I did realise this. Thankfully Intel told me this and I managed to get my OEM to give me the stitched version of the firmware. I have tested with MeshCommander and it works great.

**Comment by Ylianst** [comment]
Yes, with Intel AMT hardware KVM it's possible to blank the local screen if you have the right firmware. For the Mesh Agent, I don't think it's possible. Blanking the screen in software would also blank the agent's screen grabber. I am going to close this issue because it's not possible on MeshCentral, but if there are any ideas on how to do this, please re-open.

**Comment by ghplw** [comment]
RealVNC has this feature and TightVNC used to have this feature but it works by using power management features to turn of the screen so it is hardware dependent. I can't think of any hardware I have out there that wouldn't support this so it would be a nice feature to have.

Some other programs achieve this by installing a custom driver. I'm not sure how they work but maybe it could be a a dummy monitor and the agent tells the computer to switch all output to that dummy monitor and then switches it back again on disconnect or when the agent senses that the connection has been lost?
