### ISSUE TITLE
Let's Encrypt on Windows installation

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#540]
I can not get Let's encrypt certificate on Win installation, running latest version. Subfolder is not created. I also can not find any LOG files what is wrong

**Comment by asasin114** [comment]
Make sure your config.json file has the correct syntax. You'll have to restart the Mesh Central service as well for the settings to take effect. Below is what I used on Windows and it works like a charm.  

 "letsencrypt": {
      "email": "someone@example.com",
      "names": "hostname.domain.com",	  
      "rsaKeySize": 3072, 
      "production": true
   }

**Comment by alesribic73** [comment]
I have exactly the same settings, and it does not work. I always restart service when i change config.json

**Comment by asasin114** [comment]
Are port 80, 443, and 4433 opened to the outside world?

**Comment by alesribic73** [comment]
Yes. Except 4433 whic i dont use. Also https://letsdebug.net/ shows green.

**Comment by asasin114** [comment]
What version of Windows are you running and what type of install (Windows Installer or NPM)?

**Comment by alesribic73** [comment]
Im running server 2012 R2 with windows installer.

**Comment by Ylianst** [comment]
- I always recommend using "production": false at first to make sure everything works well. If you make to many tests with "production": true, you may get rate limited. Please try non-production first.
- Make sure port 80 is accessible from the Internet. Let's Encrypt will try to contact your server on port 80.
- Try this site: [https://letsdebug.net/](https://letsdebug.net/) it will make sure your DNS is setup correctly and report any issues.

**Comment by PathfinderNetworks** [comment]
I had this trouble when I first was setting up MeshCentral2 (which was earlier this year).  In my case the issue was due to the version of Node I had on my Server 2019 box was an older version.  As soon as I upgraded to the current version then LetsEncrypt worked correctly.  Look at the meshserrors.txt file and see what errors it's throwing.   For me I was seeing these errors.  
[WARN] rsa-compat: Your version of node does not have crypto.generateKeyPair()
[WARN] rsa-compat: Please update to node >= v10.12 or 'npm install ursa'
[WARN] rsa-compat: Using node-forge as a fallback, but it may be unacceptably slow.
[ERROR] rsa-compat: could not generate a private key.
None of crypto.generateKeyPair, ursa, nor node-forge are present
ERROR: Let's encrypt error:  TypeError: Cannot read property 'publicKeyJwk' of undefined
    at Object.RSA.thumbprint 

Again, that was back in March. But still good to make sure your version of Node is current.

**Comment by wvt-adm** [comment]
good morning at all
i have setup mc on a standalone windows 2019 server - but the zertificate wont install/work - i put in the details that i know :-)
config: (autobackup wont work!)
{
   "settings": {
		"cert": "fws.mydomain.ch", 
		"wanonly": true, 
		"_minify": true, 
		"selfupdate": true,
		"Port": 443,
		"RedirPort": 80
   },
    "letsencrypt": {
		"email": "fws@mydomain.ch",
		"names": "fws.mydomain.ch",
		"rsaKeySize": 3072,
		"production": false
  },
    "domains": {
		"": {
         "title": "fws.mydomain.ch", 
         "footer": "by mydomain 2019",
		 "geolocation": true
		 }
   }, 
    "_AutoBackup": {
		"backupIntervalHours": 24,
		"keepLastDaysBackup": 10,
		"zipPassword": "mypassword",
		"backupPath": "E:\\BACKUP"
    },
   "smtp": {
		"host": "192.168.10.2", 
		"port": 25, 
		"from": "fws@mydomain.ch", 
		"user": "fws@mydomain.ch", 
		"pass": "mypassword",
		"tlscertcheck": false,
		"tls": false
	  
   }
}
------
cmd:
C:\Program Files\MeshCentral\node_modules>node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.4.1-v, WAN mode.
Attempting to get Let's Encrypt certificate, may take a few minutes...
MeshCentral Intel(R) AMT server running on fws.mydomain.ch:4433.
MeshCentral HTTPS server running on fws.mydomain.ch:443.
SMTP mail server 192.168.10.2 working as expected.
----
mesherrors
-------- 2019-10-8 11:01:00 ---- 0.4.1-v --------

[acme-v2] handled(?) rejection as errback:
Error: connect ETIMEDOUT 62.2.193.24:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
ERROR: Let's encrypt error:  { Error: connect ETIMEDOUT myip:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'myip',
  port: 80 }

----
have you any idea why this wont work?

thanks a lot and best regards

am

**Comment by alesribic73** [comment]
@Ylianst I have tried production:false and production:true. Both ports are visible from outside and letsdebug.net is green. I did not get LetsEncrypt subfolder no mater what i do.

@PathfinderNetworks i dont have meshserrors.txt anywhere. I have the latest version of node.js

@wvt-adm i could not find any error log files?!

**Comment by alesribic73** [comment]
@Ylianst Finally i got subfoler LetsEncrypt with files.  My mistake was that LetsEncrypt settings inside config.json was a part of settings, but it should be standalone section. Now i got also mesherrors.txt which says:
-------- 10/8/2019, 10:54:50 PM ---- 0.4.1-x --------

Error: connect ETIMEDOUT 89.212.251.52:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14)
ERROR: Let's encrypt error:  Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xxx.xxx.xxx.xxx',
  port: 80
}

So still no certificate...

**Comment by alesribic73** [comment]
I finaly fix it! @wvt-adm i have the same error as you.

My server is behind CISCO router, which does not alow loopback connections. So when MeshCentral2 starts it trys to connect to DNS of it self. It means to WAN IP of MC2. Becauce of CISCO settings this kind of connection is not alowed. 

Put a line in "hosts" file like: 127.0.0.1 yourdns like in config.json

Happy using!

**Comment by Ylianst** [comment]
Wow! Thanks for that explanation. That makes sense but I never ran into that issue. I am going to close this issue, but feel free to re-open if needed.
