### ISSUE TITLE
Android agent pulled from the Play Store

### ISSUE THREAD

**Issue by tomsik-radek** [Ylianst/MeshCentral#5404]
https://play.google.com/store/apps/details?id=com.meshcentral.agent2&hl=en&gl=US

I get a ```We're sorry, the requested URL was not found on this server.``` message. Did the Android agent get pulled?

**Comment by si458** [comment]
It appears its been pulled/vanished from uk store too
I'll ask @Ylianst when he's available to look into it
For now you can use the app version from the download page
https://meshcentral.com/downloads.html

**Comment by si458** [comment]
reply from @Ylianst - Google is mandating new versions of the android SDK. I need to work on that.
you will just have to hang fire for the moment

**Comment by Ylianst** [comment]
FYI. I compiled the Android agent to the latest SDK yesterday and working on getting it back on the play store. It will take at least a few days, but hopefully it will be there soon. Once I solve all the issues, I will update the Android Agent repo with the latest code.

**Comment by tomsik-radek** [comment]
Much appreciated. Just curious, why isn't the agent itself downloadable from the Mesh instance? Versions? I think you should distribute apk just like you do Agents for other versions.

**Comment by si458** [comment]
> Much appreciated. Just curious, why isn't the agent itself downloadable from the Mesh instance? Versions? I think you should distribute apk just like you do Agents for other versions.

good idea! once @Ylianst makes the new apks available, ill look at adding it to the UI as an option as well as a link to the play store!

**Comment by tomsik-radek** [comment]
> > Much appreciated. Just curious, why isn't the agent itself downloadable from the Mesh instance? Versions? I think you should distribute apk just like you do Agents for other versions.
> 
> good idea! once @Ylianst makes the new apks available, ill look at adding it to the UI as an option as well as a link to the play store!
> 
> @tomsik-radek can u open a enhancement issue for this please? (just reminds me) also we will close this issue once the apps back on the play store

#5438 done

**Comment by Ylianst** [comment]
Working on it. There are now Play Store requirements, but slowly working thru them.

**Comment by Ylianst** [comment]
Still working on this... more Play Store requirements... I needed to add a privacy policy link to the MeshCentral.com web site and get that approved.

**Comment by si458** [comment]
i believe the app is now back on the play store as i can see it in UK here
