### ISSUE TITLE
The Agent update did not arrive on my server

### ISSUE THREAD

**Issue by MBudkin** [Ylianst/MeshCentral#5405]
Good afternoon
I installed update 1.1.12 with the hope of eliminating the flickering arrow. MeshCentral itself has been updated, but the Agent displays the latest update Dec 9 2022. I tried to force update the Agent via the console, but nothing changed.
Is this how it should be or am I doing something wrong? Or has the Agent update not been updated yet?

**Comment by si458** [comment]
The is no new agent update, only update to the code which gets pushes to the agents automatically or as u did view the force update command

So the version it shows will still be from 2022

**Comment by MBudkin** [comment]
@si458 
Understood. At what point should the needle flicker stop? In other MeshCentral updates?

**Comment by NiceGuyIT** [comment]
It looks like MeshAgent releases are based on tags and a [new tag](https://github.com/Ylianst/MeshAgent/tags) hasn't been created.

On the MeshCentral side, all agents are in `agents/` and verified with [hashagents.json](https://github.com/Ylianst/MeshCentral/blob/master/agents/hashagents.json). What is the release process to build a new MeshAgent and add it to the MeshCentral repo?

**Comment by si458** [comment]
@MBudkin @Ylianst has merged all the bug fixes in the meshagent repo, but couldnt build the agents correctly, so he didnt include any new agent update sadly this time round

@NiceGuyIT you are correct, @Ylianst would create a new tag in the meshagent repo if the was a new version
and the update process is simply, download the meshagent repo, build (using the `makeall / makefile` scripts), then copy all files over to your agents folder including the hashagents.json and restart meshcentral
