### ISSUE TITLE
Updated by itself to 1.1.13?

### ISSUE THREAD

**Issue by dxdemetriou** [Ylianst/MeshCentral#5407]
Hello, I just tried on two MeshCentral instances I have on Linux, and without making anything seems that's already updated to 1.1.13. Is there any config option that I missed? The problem now is that I don't have any snapshot for troubleshooting. I'm attaching the logs from 2 servers in which happened about the same time today.

[1_2023-10-09T13_43_36_292Z-debug-0.log](https://github.com/Ylianst/MeshCentral/files/12846928/1_2023-10-09T13_43_36_292Z-debug-0.log)
[1_2023-10-09T13_43_12_538Z-debug-0.log](https://github.com/Ylianst/MeshCentral/files/12846929/1_2023-10-09T13_43_12_538Z-debug-0.log)
[2_2023-10-09T13_16_10_196Z-debug-0.log](https://github.com/Ylianst/MeshCentral/files/12846930/2_2023-10-09T13_16_10_196Z-debug-0.log)
[2_2023-10-09T13_15_34_694Z-debug-0.log](https://github.com/Ylianst/MeshCentral/files/12846931/2_2023-10-09T13_15_34_694Z-debug-0.log)

**Comment by si458** [comment]
the server can automatically update itself every day after mightnight but you have to enable the setting
https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json#L442-L446

the was an update to 1.1.12 this morning, but sadly @Ylianst overwrite the `packages.json` file by accident which installed old packages, so he released an emergency update to 1.1.13 which fixed the `pakages.json` file!

so if u updated thinking it should of gone to 1.1.12, it might of jumped to 1.1.13 instead but they are identical code wise expect for the required packages!

**Comment by si458** [comment]
sorry closed by accident

**Comment by Socra69** [comment]
In opt/meshcentral/meshcentral-data/config.json, you have a variable marked "SelfUpdate": true, you can set to to "false"

**Comment by SomeGuru** [comment]
@dxdemetriou 
Even though sometimes the _tagout is done, the result of the true/false may still be accidentally incorporated. I would tagout "_selfUpdate":false just to make sure it is fully disabled, or remove completely from your config.json file.

SomeGuru

**Comment by Ylianst** [comment]
Ok, this was a critical bug and I just released MeshCentral v1.1.14 with a fix for this. NPM has changed it's behavior over the years and the latest NPM will update MeshCentral to the latest version when MeshCentral tried to install any missing modules. MeshCentral v1.1.14 fixes this by completely changing how new modules are installed.

As a result, you may get auto-updated to v1.1.14 due to prior issue, but once there, it should no happen again. Let me know if anyone sees anything not right.
