### ISSUE TITLE
Public files with download link

### ISSUE THREAD

**Issue by WesleyjanLacerda** [Ylianst/MeshCentral#5408]
Hello, a question about the settings, I saw that in the "my files" files, in the "public" folder it is possible to upload the files and copy the download link, it is possible to configure this same option to copy the download link, on other networks ?

![image](https://github.com/Ylianst/MeshCentral/assets/74305459/992debc6-1709-4eb4-8460-25f2a9efca39)

![image](https://github.com/Ylianst/MeshCentral/assets/74305459/07fff59d-f139-465e-ba7e-5cb4817804d4)

So that the files are actually public with a download link option

**Comment by si458** [comment]
NO
the public folder under 'My Files' is for you to share files with the general public (read access only)
the other folders are all private to your user or to your group etc

**Comment by tomsik-radek** [comment]
> NO the public folder under 'My Files' is for you to share files with the general public (read access only) the other folders are all private to your user or to your group etc

A small suggestion, maybe we should start closing tickets? I know it sounds corporate but still, it doesn't look good when others see 1.4k issues open.

**Comment by si458** [comment]
@tomsik-radek im working my way through them one by one,
even adding features etc, but very hard when your a one man band with 0 hours a day spare 👍

**Comment by tomsik-radek** [comment]
I know that feeling all too well. I assume github doesn't have "close any issues with age over 1 year" thing?

**Comment by si458** [comment]
> I know that feeling all too well. I assume github doesn't have "close any issues with age over 1 year" thing?

it does,  its called [Stale](https://github.com/actions/stale) and uses the github actions, i just havent gotten round to setting it up yet, baby steps 👣
