### ISSUE TITLE
Terminal - Auto Disconnect after 30-40s in Meshcentral

### ISSUE THREAD

**Issue by Socra69** [Ylianst/MeshCentral#5413]
**Describe the bug**
When attempting to connect to a Linux/Windows machine using the Terminal > Connect button, after approximately 60 seconds, we are automatically disconnected without apparent reason. This issue appeared with the new update 1.1.13.

**To Reproduce**
1. Click on a machine (Linux/Windows).
2. Click on 'Terminal.'
3. Scroll to 'Connect.'
4. Once connected, wait for approximately 60 seconds, and you will be automatically disconnected from the machine. It is impossible to work under these conditions.

**Expected behavior**
When attempting to connect to a Linux/Windows machine using the Terminal > Connect button, after approximately 60 seconds, we are automatically disconnected without apparent reason. This issue appeared with the new update 1.1.13.

**Client Device (please complete the following information):**
- Device: Windows 11
- Web Browser: Chrome

**Remote Device (please complete the following information):**
- Device: Linux (Debian)/Windows/Any VM

**Additional context**
Since the new update 1.1.13.

**Comment by Souheib-khiter** [comment]
i have the same issue

**Comment by si458** [comment]
are you using any proxies like cloudflare? missing key info from the bug remote for the meshcentral server

**Comment by Socra69** [comment]
No, we are not using any proxy like Cloudflare. We have just executed 'npm update' and 'apt-get upgrade' to see if there is any difference because the 1.1.13 update changed the dependency.

**Comment by Socra69** [comment]
Well after 60 secondes, we got the same issue, we still disconnect automatically

**Comment by si458** [comment]
we did a load of package updates, but all seems to working fine here?
does it effect only terminal? have u tried desktop mode?

**Comment by Souheib-khiter** [comment]
For both desktop and teminal

**Comment by Socra69** [comment]
affect terminal linux and rdp windows mode, the two

**Comment by si458** [comment]
cant seem to replicate? ive had a terminal window open for 3 mins now?
if you used npm to install, try stopping the node process completely, delete the whole node_modules folder (backup first!),
then reinstall with `npm install meshcentral` then start the node process and see what happens?

**Comment by Socra69** [comment]
We just make what did you say, but after exactly 2 min, the session on terminal auto disconnect

**Comment by Socra69** [comment]
Exactly after 00:02:00 auto disconect session

**Comment by Socra69** [comment]
Okay, I've identified the issue. The problem was in the 'config.json' file. The variable 'agentPong' was initially set to 120, but I'm not sure what it does. However, I've edited it to 1200, and now we are not experiencing auto-disconnections. So, you can go ahead and close the issue

**Comment by Socra69** [comment]
Issue fixed, thank's anyway for the support

**Comment by si458** [comment]
`agentPong` is basically the meshcentral server sending the remote agent a `PING` every defined seconds and if it doesnt get a `PONG` reply back, it then disconnects sessions for that remote agent
by default this is disabled (unless you have defined a value like you have) as the websockets should handle the ping/pong themselves rather than the manual ping/pong being done which is what happens when you set the `agentPong`

**Comment by silversword411** [comment]
Sounds like a sketchy connection between server and agent.
