### ISSUE TITLE
Missing desktop icon in webUI

### ISSUE THREAD

**Issue by Vista2003** [Ylianst/MeshCentral#5414]
**Describe the bug**
Desktop icon in the general section of the device view is missing/broken

**To Reproduce**
1. Click on a device with the desktop icon

**Expected behavior**
For the desktop icon to show like the other icons.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/55105920/6f61575c-87fd-40ce-8a16-47bdc1d9de26)

**Server Software (please complete the following information):**
 - OS: Raspberry Pi OS
 - Virtualization: None
 - Network: Nginx Proxy Manager
 - Version: 1.1.13
 - Node: v19.9.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 22H2 x64
 - Network: Remote over the WAN
 - Browser: Brave [Version 1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)](https://brave.com/latest/)
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 22H2 x64 and Server 2019
 - Network: Remote over the WAN
 - Current Core Version (if known): Current Core: Dec 9 2022, 1032341640

**Comment by si458** [comment]
weird?
if you right click on the image and say 'open image in new tab' does it open in the new tab ok?
whats the url it shows?
daft one, have u tried CTRL+F5 or SHIFT+F5 or private mode (incognito) ?

**Comment by Vista2003** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/55105920/eebaea17-875f-462d-bb76-a02d70ec2249)
Forcing a refresh does nothing nor does using private mode.

Accessing the file locally shows this
![image](https://github.com/Ylianst/MeshCentral/assets/55105920/01e625eb-9d8a-4790-827a-1e90e808da84)

Other icons are not affected and the desktop icon in the My Devices few is present.

**Comment by si458** [comment]
you are using a proxy so i would expect it to be a proxy issue
the 2nd pic which is local access, whats your config.json?
as it should be diverting to https not http

**Comment by Vista2003** [comment]
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "******",
    "_tlsoffload": "10.0.2.11",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "selfupdate": true,
    "AgentPong": 300,
    "_redirAliasPort": 80,
    "trustedProxy": "10.0.2.11, CloudFlare",
    "MpsPort": 4433,
    "MpsAliasPort": 4433,
    "MpsTlsOffload": false
  },
  "domains": {
    "": {
      "certurl": "******",
      "title": "****** Remote Access",
      "title2": "Powered by MeshCentral",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  },
  "smtp": {
    "host": "******",
    "port": 465,
    "from": "******",
    "user": "******",
    "pass": "******",
    "tls": true
 }
}
```

Using https to connect to the image file does work
![image](https://github.com/Ylianst/MeshCentral/assets/55105920/0a177ad6-42e3-4398-8cf4-b4563cc954af)


The proxy is connecting to the server using HTTPS.

**Comment by Vista2003** [comment]
Looking at Proxy side, I forgot to turn on HTTP/2 and HSTS. After doing that the icon has returned.

**Comment by si458** [comment]
@Vista2003 dont worry, its a mad day today with issues! glad its sorted 👍
