### ISSUE TITLE
addusergrouptodevicegroup for MeshCtrl

### ISSUE THREAD

**Issue by DataSparJoe** [Ylianst/MeshCentral#5418]
**Is your feature request related to a problem? Please describe.**
I am currently using MeshCtrl to manage Device Groups for an application, and it would be useful if I could add my "admins" User Group to new Device Groups created by the application. From the research I've done, this seems to only be possible in the MeshCentral UI.

**Describe the solution you'd like**
Would it be possible to add a new command to MeshCtrl called addusergrouptodevicegroup which would allow you to add a User Group to a Device Group the same way you can do in the UI?

**Describe alternatives you've considered**
I could work around this for now by just adding the members of my admins group individually, but it would be easier to manage in the long term as admins are added and removed.

**Comment by si458** [comment]
just quickly looked at the source code, this is already sorta in i think?
i would have to have a look tomorrow for you
```
case 'addtousergroup': {
                var ugrpid = args.groupid;
                if ((args.domain != null) && (userid.indexOf('/') < 0)) { ugrpid = 'ugrp/' + args.domain + '/' + ugrpid; }
 // Add a device group to a user group
                var rights = 0;
                if (args.rights != null) { rights = parseInt(args.rights); }
                if (args.meshid != null) {
                    var meshid = args.meshid;
                    if ((args.domain != null) && (userid.indexOf('/') < 0)) { meshid = 'mesh/' + args.domain + '/' + meshid; }
                    ws.send(JSON.stringify({ action: 'addmeshuser', meshid: meshid, userid: ugrpid, meshadmin: rights, responseid: 'meshctrl' }));
                    break;
                }
}
```

**Comment by DataSparJoe** [comment]
Ah, fair enough. I hadn't caught this. I'll give your suggestion a try and see if it works.

**Comment by si458** [comment]
closing as stale
