### ISSUE TITLE
Notification Text Change

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#542]
Ylianst, good morning!

Constantly when I am trying to change the user notification message there in the meshcore.js file, the system is removing remote desktop connection options, command prompt and files, could it help me? Here's an example of the message I'm trying to put for both, it would look something like the following text:

As per your support request, we request access to your workstation for service.
Give remote control to technician %VARIABLE WHICH DOES TECHNICIAN NAME%?

My impression is that the code is blocked for this change, meaning that the variable field only works that way

**Comment by Ylianst** [comment]
Hi. I don't understand you request. Are you saying that you are changing meshcore.js but when you update the server, the change is removed? Or saying that you make the change and it's not working?

When you make the change, make sure to remove the "meshcore.min.js" file and restart the server.

I don't understand "Give remote control to technician %VARIABLE WHICH DOES TECHNICIAN NAME%?" and "My impression is that the code is blocked for this change, meaning that the variable field only works that way". Can you give more details? - Thanks.

**Comment by geanferrani123** [comment]
Hello Ylianst, Good Morning!

please can close the topic in question, i was putting accents and a key called ç (default key for brazilian keyboards) and so the text was not being fixed.

My question I was trying to explain is that when I send a remote access request to the user, a message is displayed and then the question whether or not the user wants to accept remote access is the message that appears to the user who was trying change to another way and was kind of disabling the remote access functionality.

Thank you very much for your attention, I already managed to solve it in another way, but if you still want me to explain to you for more documentation let me know that I'll explain to you anyway.
