### ISSUE TITLE
MeshAgent Related

### ISSUE THREAD

**Issue by mctchirag** [Ylianst/MeshCentral#5425]
One thing i would like to do is when you download and install the Meshagent on remote computer
, it would not show up in the Control Panel uninstall list

How to achieve this task

**Comment by si458** [comment]
this isnt possible, you have to use the windows registry manually urself,
https://www.makeuseof.com/hide-installed-programs-windows-10/ - Hide Individual Programs in Control Panel Using Registry Editor
just tried the link above and works a treat

**Comment by mctchirag** [comment]
Thank you for your Reply.. but this is Possible in Meshagent .
Ylianst has mentioned it in one reply but how to do he dint mentioned

so i want to know that

**Comment by si458** [comment]
from my recollection, this ISNT possible, but i could be mistaken? unless u can point me to the post/reply he says its possible

**Comment by mctchirag** [comment]
![Reply By YLianst](https://github.com/Ylianst/MeshCentral/assets/91785305/c5a5f782-c4b2-4c04-80fe-cce5735e2968)
see his Reply

https://github.com/Ylianst/MeshCentral/issues/655

**Comment by mctchirag** [comment]
> from my recollection, this ISNT possible from within meshagent itself, but i could be mistaken? unless u can point me to the post/reply he says its possible

https://github.com/Ylianst/MeshCentral/issues/655

![Reply By YLianst](https://github.com/Ylianst/MeshCentral/assets/91785305/5caa4dad-80b4-48d1-a3f0-5963c8e8d97b)

**Comment by si458** [comment]
if you read it, it says **we could add is** and **we could also** and this hasnt happened, so it would need to be implemented

**Comment by mctchirag** [comment]
Hello when we share the remote session with another user then the user is getting blue bar on the top that your machine is shared
how we can hide that. Please help me

**Comment by dinger1986** [comment]
Mesh isn't built to be hidden etc, if it is that's going to start being a problem with AV producers even having the flag to make it hidden.
