### ISSUE TITLE
Distribute Android agent with the server

### ISSUE THREAD

**Issue by tomsik-radek** [Ylianst/MeshCentral#5438]
#5404 
Please distribute the Android agent with the server so it can be downloaded independently of Google Play Store.

**Comment by si458** [comment]
![Screenshot 2023-10-18 173651](https://github.com/Ylianst/MeshCentral/assets/765314/bfc6a5f3-6509-40a0-afc6-e78c744b2f38)

**Comment by tomsik-radek** [comment]
Yes, this is great. But while we are at it, what about a share link for that apk? Or better yet, a QR share link.

**Comment by si458** [comment]
![Screenshot 2023-10-18 185535](https://github.com/Ylianst/MeshCentral/assets/765314/49161aec-77d4-49e2-ade8-2123631dbc73)
made it abit nicer with proper logos!
also you juct click the blue download icon next to APK and thats ur share link!

**Comment by tomsik-radek** [comment]
The Google Play logo is much better, yes!

**Comment by si458** [comment]
Just twigged what u meant before,
I need to do the agentinvite page too!
Back to draft goes the PR...

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/ebec7492-1745-4810-b488-4687b706d3cf)
and done!
