### ISSUE TITLE
Feature Request: Add display time control to Device Notification Message Box

### ISSUE THREAD

**Issue by jvantslot** [Ylianst/MeshCentral#5441]
The Device Notification message box should have a display time control to show the message for longer than just a few minutes.

If the message box could be configured to:

- Display the message for XX minutes.
- Display the message box until the user acknowledges or closes the message

This would be useful to display messages that linger for longer in cases where there might not be a person at the workstation for longer amounts of time.

This feature would be super handy.

**Comment by si458** [comment]
this is already partely implemented
if you broadcast a message to a user, you have the option to display the notification for x seconds
i think it just needs to be implemented for notifcations about devices and help requests
would you want the option of 'x seconds' to be set by the user? and if not set then its permanently displayed until they close/remove the notification?

**Comment by si458** [comment]
has been added to 1.1.18
