### ISSUE TITLE
"allowLoginToken" does not work

### ISSUE THREAD

**Issue by Jayddee23** [Ylianst/MeshCentral#5442]
**Describe the bug**
I don't want my users to be able to use a login token.
Therefore, I wanted to use the "allowLoginToken" parameter and set it to "False" but this doesn't change anything, I can still create and use the login token.
Could you please tell me how to solve my problem?
Thank you for your help.

**Server Software (please complete the following information):**
 - OS: Windows
 - Virtualization: VMWare
 - Network: LAN/WAN
 - Version: 1.1.13

**Client Device (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome

**Your config.json file**
```
"settings": {
    "cert": "**********",
    "port": 443,
    "_BrowserPing": 120,
    "BrowserPong": 120,
    "_AgentPing": 120,
    "AgentPong": 120,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
	  "desktopMultiplex": true,
    "allowLoginToken": false
  },
```

**Comment by si458** [comment]
Weird? The default is already `false` so the option should be hidden?
Think defo a bug, will look into it for you

**Comment by Jayddee23** [comment]
I hadn't even noticed that it was set to "False" by default.
I also tried to play with the "loginTokens" parameter to get around this and authorize only certain people, but it was always present for everyone.

**Comment by si458** [comment]
so it appears the option is switched on and off by features2 `QV('accountCreateLoginTokenSpan', features2 & 0x00000080);`

but i dont understand how the hex values work? `0x00000080`

as i can see here that `features2` adds in the permission for logintokins but as a different server variable?

```
if ((typeof domain.passwordrequirements != 'object') || ((domain.passwordrequirements.logintokens !== false) && ((Array.isArray(domain.passwordrequirements.logintokens) == false) || (domain.passwordrequirements.logintokens.indexOf(user._id) >= 0)))) { features2 += 0x00000080; } // Indicates login tokens are allowed
```

**Comment by si458** [comment]
OHHH just read the schema correctly

`loginTokens - Allows users to create alternative username/passwords for their account. Set to false to disallow all users, or set to a userid array to only allow some users.`

you need to set below instead of `allowLoginToken`

```
passwordRequirements: {
    loginTokens: false
}
```

**Comment by Jayddee23** [comment]
perfect, it works thanks.

In parallel, following the various other modifications, when I restart my server, it spams the line "AGENT WSERR: RangeError: Invalid WebSocket frame: MASK must be set".
Any idea where this might be coming from?

**Comment by si458** [comment]
> perfect, it works thanks.
> 
> In parallel, following the various other modifications, when I restart my server, it spams the line "AGENT WSERR: RangeError: Invalid WebSocket frame: MASK must be set". Any idea where this might be coming from?

open a seperate issue if you may so we dont get mixed up

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/commit/c9b47edc75b138836fadb470a7fd8c1d258b3d9d
