### ISSUE TITLE
Check server version shows Unknown

### ISSUE THREAD

**Issue by vhuet-laps** [Ylianst/MeshCentral#5447]
**Describe the bug**
Check server version shows Unknown for Stable Version and Latest Version. Current Version shows true value.

**To Reproduce**
Updated MeshCentral from 1.1.10 to 1.1.13 through self-update

**Expected behavior**
Check server version should show 1.1.X for Stable Version and 1.1.13 for Latest Version. See screenshot below.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/148365221/5d8ac641-fe02-48f2-a650-65ac2b08b8f9)

**Server Software (please complete the following information):**
 - OS: Rocky Linux
 - Virtualization: AWS EC2
 - Network: WAN only, behind CloudFlare
 - Version: 1.1.13
 - Node: 16.20.2

**Client Device (please complete the following information):**
Doesn’t apply

**Remote Device (please complete the following information):**
Doesn’t apply

**Additional context**
It's not a web browser cache issue.

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "myserver.mydomain.com",
    "WANonly": true,
    "port": 443,
    "redirPort": 80,
    "trustedproxy": "CloudFlare",
    "mySQL": {
	"host": "mysqldatabase.rds.amazonaws.com",
	"user": "mysqluser",
	"password": "mysqlpassword",
	"database": "meshcentral",
	"awsrds": true
    }
  },
  "domains": {
    "": {
      "title": "MYDOMAIN.COM",
      "title2": "Remote Assistance Service",
      "newAccounts": false,
      "_userNameIsEmail": true,
      "certurl": "https://myserver.mydomain.com"
    }
  }
}



```

**Comment by si458** [comment]
seems to work perfectly fine here ?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b78db33b-360d-4ebb-a1fe-5fc36433fff7)
all the app does it run `npm dist-tag ls meshcentral`
can you run this command from your meshcentral folder and get any output?

**Comment by PetieM** [comment]
I remember having this problem early on. Set npmPath in your config file (e.g. `"npmPath": "/usr/local/bin/npm",`) and see if that helps. It fixed it for me at least.

**Comment by vhuet-laps** [comment]
Thanks PetieM! Issue is resolved
