### ISSUE TITLE
show human readable sizes in files

### ISSUE THREAD

**Issue by RobertD1985** [Ylianst/MeshCentral#5451]
First of all, I want to thank you for this app!
My suggestion is related to Remote File Manager. Is it possible for the size of the files to appear in MB or GB? Even if I were a math genius, I still have to sit with a computer to calculate millions of bytes and convert them into MB. It would be useful for those who use the function.

**Comment by si458** [comment]
would you like the files sizes to be shown as `128bytes 128megabytes 128gigabytes etc`
or 
would you like a dropdown box next to `sort by name` and then you can pick what you want all files to show as?

**Comment by RobertD1985** [comment]
How is it easier to configure on the server? 
The first option seems close to a windows explorer, which would be the best.

**Comment by si458** [comment]
> How is it easier to configure on the server? The first option seems close to a windows explorer, which would be the best.

i can cheat and use - https://gist.github.com/lanqy/5193417?permalink_comment_id=3164749 which converts for me,
but i wasnt sure if users wants to PICK which size they wanted rather than it just displaying the size for them?

**Comment by RobertD1985** [comment]
Dropdown box is a good idea to make everyone happy. So everyone could choose to see the size of the files as they want. But for that is more work to do. This "cheat" would also be ok for me if I knew what code to use and where to put it.

**Comment by si458** [comment]
@RobertD1985 OOO idea!
drop down box saying 'Auto', 'Bytes', 'MegaBytes' etc...
then default is Auto which converts from bytes to human readble,
then you can change it to show certain values like a video folder you would wanna see GBs not bytes but pictures might be MBs not Bytes !

**Comment by RobertD1985** [comment]
It would be perfect! But how can it be done?

**Comment by si458** [comment]
@RobertD1985 any good?
![Screenshot 2023-10-19 184904](https://github.com/Ylianst/MeshCentral/assets/765314/7486238f-1252-40d2-8bfc-1089a4c6d3d4)
![Screenshot 2023-10-19 184750](https://github.com/Ylianst/MeshCentral/assets/765314/685b6f7b-84bf-4900-bba4-3cc387028843)
![Screenshot 2023-10-19 184830](https://github.com/Ylianst/MeshCentral/assets/765314/4afddeb4-366e-4941-b74a-d70d64bc1af4)
![Screenshot 2023-10-19 184825](https://github.com/Ylianst/MeshCentral/assets/765314/62e83165-e2c3-44dc-8d84-7de826dd97ae)
![Screenshot 2023-10-19 184837](https://github.com/Ylianst/MeshCentral/assets/765314/22d6565f-631d-4dad-90f2-4ee2dbfa636d)
![Screenshot 2023-10-19 184849](https://github.com/Ylianst/MeshCentral/assets/765314/a754a8b2-ba3e-4192-b3f2-b92c84cfb6f4)

**Comment by RobertD1985** [comment]
@si458 It's perfect!!

**Comment by si458** [comment]
im using 1024 and not 1000, but 1024 is what windows uses so lets go with that

**Comment by RobertD1985** [comment]
We use the Web version and router on laptops. The server is installed on a Windows server, I hope it won't be a problem

**Comment by si458** [comment]
@RobertD1985 no the PR is only for desktop web ui, it just wont apply if you use the web ui on your mobile phone!

**Comment by RobertD1985** [comment]
Is not an impediment, those who want to see the function on the phone can use "Desktop site" from the phone browser. On the phone, I think that most of them use it for emergency remote assistance

**Comment by si458** [comment]
PR done! i made 1 final change so instead of it showing 'Kilobytes' and 'Megabytes' etc in the files, it now shows 'KB', 'MB', etc...
much nicer! give it a try if you wanted `npm install https://github.com/Ylianst/MeshCentral#display-file-sizes`

**Comment by RobertD1985** [comment]
@si458 
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/Ylianst/MeshCentral.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by si458** [comment]
@RobertD1985 oh sorry! try `npm install Ylianst/MeshCentral#display-file-sizes`

**Comment by RobertD1985** [comment]
The server is off but still get this error
c:\Meshcentral>npm install Ylianst/MeshCentral#display-file-sizes
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Ylianst/MeshCentral.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by si458** [comment]
@RobertD1985 erm... try `npm cache clean --force` then `npm install Ylianst/MeshCentral#display-file-sizes` ?

**Comment by RobertD1985** [comment]
I downloaded the file and put it manually in the view folder in meshcentral. It works perfectly! Thank you very much!!

**Comment by si458** [comment]
> I downloaded the file and put it manually in the view folder in meshcentral. It works perfectly! Thank you very much!!

no worries glad it works! gotta love npm being funny at times!
any screenshots you can share would be amazing! so i can update docs 👍

**Comment by RobertD1985** [comment]
![WEB](https://github.com/Ylianst/MeshCentral/assets/147500092/ce80c783-ec58-4ddd-b954-89013f1b97a8)
![WEB1](https://github.com/Ylianst/MeshCentral/assets/147500092/ea623fa0-1e6d-40d1-8c27-1b89bcd22f47)
![WEB2](https://github.com/Ylianst/MeshCentral/assets/147500092/248a4b05-24e5-4a9c-b24c-3ea378462247)

**Comment by si458** [comment]
thank you @RobertD1985! only so i can update docs with this feature/screenshots when next release happens!

**Comment by RobertD1985** [comment]
Thank you @si458 for all of this!!
