### ISSUE TITLE
ERROR: Unable to parse /home/administrator/meshcentral-data/config.json.

### ISSUE THREAD

**Issue by dgcortespr** [Ylianst/MeshCentral#5453]
Hi, I'm attempting to start a Mesh Central I edited config.json and file fails with error: ERROR: Unable to parse /home/administrator/meshcentral-data/config.json.

{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "mongoDb": "mongodb://127.0.0.1:27017", 
    "mongoDbName": "meshcentral",
    "_WANonly": true,
    "_cert": "myserver.mydomain.com",
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "_WebRTC": false,
    "_ClickOnce": false,
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}

**Comment by si458** [comment]
use https://jsonlint.com/ to validate your json file by copy and pasting the contents 
```
Error: Parse error on line 19:
..._ClickOnce": false,},"domains": {"": 
----------------------^
Expecting 'STRING', got '}'
```
you have an extra comma after `_ClickOnce` which needs to be removed

**Comment by dgcortespr** [comment]
Thanks for your help.
