### ISSUE TITLE
Bug: Multiline notifications not displayed (at least on Windows) (0.4.1-w)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#546]
When sending a notification containing newlines, it is not displayed on the managed client. It shows up in the client's Events tab, but seems to be ignored by the agent.

So far I noticed this on Windows 10 clients. If required I may test this on macOS and Linux clients, too.

**Comment by Ylianst** [comment]
I just tried it and you right. I could chat with Bryan to see if the agent can support multi-line, but I don't think Win10 Toast messages support them. I can change the notification to a single line if that is ok?

**Comment by veitw** [comment]
> I can change the notification to a single line if that is ok?

We are happy with any kind of notification that does not get lost. :)

In my opinion if this is a Windows toast problem, the Windows agent shall just s/\r?\n/ /g, but if it affects the agents of all OS, I would (also) change the multiline textarea form to a singleline input form, so the MC user does not even get the impression that multiline notifications are supported.

**Comment by Ylianst** [comment]
Ok. I will talk to Bryan tomorrow and see what needs to be fixed for this.

**Comment by Ylianst** [comment]
Fixed it. Multi-line messages will work in Windows as expected. It will be in MeshCentral v0.4.1-y when it's released later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-y with a fix for this. Let me know if it work for you.

**Comment by veitw** [comment]
Multiline notifications now work for me now on Windows.

The macOS and Linux agents do not seem to support notifications at all (till now), so I did not test those.

Thank you very much!

**Comment by Ylianst** [comment]
Nice thanks for the report.
