### ISSUE TITLE
Update to 1.1.14 Breaks

### ISSUE THREAD

**Issue by tyl0re** [Ylianst/MeshCentral#5463]
I Updated to 1.1.10 to 1.1.14
Meshcentral Breaks, a new start gets

 meshcentral.service - MeshCentral Server
     Loaded: loaded (/etc/systemd/system/meshcentral.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-10-23 10:29:30 CEST; 5min ago
   Main PID: 424 (node)
      Tasks: 11 (limit: 4654)
     Memory: 572.5M
        CPU: 28.142s
     CGroup: /system.slice/meshcentral.service
             └─424 /usr/bin/node /home/meshcentral/node_modules/meshcentral

Oct 23 10:35:04 mib517meshcentral node[424]:     at ChildProcess.exithandler (child_process.js:308:12)
Oct 23 10:35:04 mib517meshcentral node[424]:     at ChildProcess.emit (events.js:326:22)
Oct 23 10:35:04 mib517meshcentral node[424]:     at maybeClose (internal/child_process.js:1022:16)
Oct 23 10:35:04 mib517meshcentral node[424]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
Oct 23 10:35:04 mib517meshcentral node[424]:   killed: false,
Oct 23 10:35:04 mib517meshcentral node[424]:   code: 1,
Oct 23 10:35:04 mib517meshcentral node[424]:   signal: null,
Oct 23 10:35:04 mib517meshcentral node[424]:   cmd: '/usr/bin/node /home/meshcentral/node_modules/meshcentral --launch 424'
Oct 23 10:35:04 mib517meshcentral node[424]: }
Oct 23 10:35:04 mib517meshcentral node[424]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
##################################################################

mesherrors.txt Says:

-------- 10/23/2023, 10:35:30 AM ---- 1.1.14 --------

/home/meshcentral/node_modules/mariadb/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/meshcentral/node_modules/mariadb/lib/lru-prepare-cache.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by si458** [comment]
Somebody else reported the same thing, but what's weird is we didn't change the mariadb module? Only the mysql module? Will investigate

**Comment by si458** [comment]
What node version are u using, also what mariadb version, and OS ?

**Comment by tyl0re** [comment]
OS: Debian GNU/Linux 11.4.0 _Bullseye

Node:
ii  nodejs                             12.22.12~dfsg-1~deb11u4        amd64        evented I/O for V8 javascript - runtime executable
ii  nodejs-doc                         12.22.12~dfsg-1~deb11u4        all          API documentation for Node.js, the javascript platform
ii  npm                                7.5.2+ds-2                     all          package manager for Node.js

Mariadb:
ii  mariadb-client-10.5                1:10.5.19-0+deb11u2            amd64        MariaDB database client binaries
ii  mariadb-client-core-10.5           1:10.5.19-0+deb11u2            amd64        MariaDB database core client binaries
ii  mariadb-common                     1:10.5.19-0+deb11u2            all          MariaDB common configuration files
ii  mariadb-server                     1:10.5.19-0+deb11u2            all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.5                1:10.5.19-0+deb11u2            amd64        MariaDB database server binaries
ii  mariadb-server-core-10.5           1:10.5.19-0+deb11u2            amd64        MariaDB database core server files

**Comment by si458** [comment]
you are running an OLD version of node, you need to upgrade to the latest LTS version
mariadb requires lru-cache which requires node 14 or above
https://www.npmjs.com/package/lru-cache?activeTab=code - check package.json -> require node 14 or above
