### ISSUE TITLE
TypeError: Cannot create property 'amtWsEventSecret' on string

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#5465]
### Discussed in https://github.com/Ylianst/MeshCentral/discussions/5464
```
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
ERR: Ignoring invalid configuration option passed to Connection: secure. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ERR: Ignoring invalid configuration option passed to Connection: secure. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
MeshCentral HTTP redirection server running on port 82.
MeshCentral v1.1.14, WAN mode.
ERR: /home/pi/node_modules/meshcentral/meshcentral.js:1501
if (obj.dbconfig.amtWsEventSecret == null) { obj.crypto.randomBytes(32, function (err, buf) { obj.dbconfig.amtWsEventSecret = buf.toString('hex'); obj.db.Set(obj.dbconfig); }); }
^
TypeError: Cannot create property 'amtWsEventSecret' on string '{"_id":"dbconfig","version":1,"amtWsEventSecret":"c35540a17c955ab8b69da7db3064f40a3d12036521190da92888a4393f1c8e1a"}'
at RandomBytesJob. (/home/pi/node_modules/meshcentral/meshcentral.js:1501:137)
at RandomBytesJob. (node:internal/crypto/random:114:5)
at RandomBytesJob.onJobDone (node:internal/crypto/random:309:3)
```
Node.js v18.17.1

**Comment by si458** [comment]
closed by accident

**Comment by si458** [comment]
i cant seem to replicate this issue?

however @MyUncleSam the `amtWsEventSecret` is used to encrypt AMT stuff, so oversally deleting the line is a BAD IDEA !?
```
var amtpass = obj.crypto.createHash('sha384').update(auth.username.toLowerCase() + ':' + nodeid + ":" + obj.parent.dbconfig.amtWsEventSecret).digest('base64').substring(0, 12).split('/').join('x').split('\\').join('x');
```

@CSW2000 in ur database, what is the row data for `dbconfig` in table `main`? im looking at the column `doc` data ?
```
SELECT * FROM `main` where `id`='dbconfig';
```

**Comment by CSW2000** [comment]
Is the entry in the MariaDB meant? see image
![dbconfig_main](https://github.com/Ylianst/MeshCentral/assets/56474379/c4407bfa-0e78-4039-aaf4-c0d46362d03f)

**Comment by CSW2000** [comment]
Is there a way from Mariadb to "nodb" or standard without a database or a nine installation to (bookworm) Debian 12 and data transfer from the old defective system. Here I have a backup folder with a backup from October 21st, 2023 or older.
I tried this yesterday on an oracle vm but it couldn't be restored, probably because MariaDB was missing.
I don't really care about the data in the database and I can recreate the missing 40 customer connections.
The service times are managed manually and if necessary using an Access database.

**Comment by si458** [comment]
You only convert from nedb to a database not database to nedb, sorry

**Comment by CSW2000** [comment]
After a few attempts to reinstall Meshcentral on a newly installed system, whether under Linux Debian 11 or 12, whether Raspberry Pi 4 or VM or Real Mashines with different node versions, with different Meshentral versions from 0.9 to 1.4, unfortunately I was no longer able to do it to get running.
I watched Ylianst YouTube instructions again after years and did them that way.
After the installation you can no longer find any files in the “mc” directory.
I always get the following message... See image below...
I get the impression that you don't want it to work anymore. ...Were we just the experimental rabbits? Or am I just blind?
![IMG_20231023_221331](https://github.com/Ylianst/MeshCentral/assets/56474379/c7a6d523-0667-4589-ad31-bde6051acf8b)

**Comment by si458** [comment]
What instructions are you following? Please provide links
As I'm having no issues here at all installing? Even a fresh install?

**Comment by CSW2000** [comment]
For example.
In Ylianst's YouTube video https://www.youtube.com/watch?v=cqdPpe84Kv8&t=132s
is a simple destruction to install Meshcentral on PasperryPi. It says you should create a directory mc.
This is always empty after my installation??? Weird, is not it ??

Here are the instructions for installation, they are also very simple, right? and unmistakably - but nothing works here anymore like it did 2 years ago. or are there new instructions? and if so where?

**Comment by si458** [comment]
For starters `sudo apt-get install nodejs npm` will just install an old version of nodejs (10 I think?)

I would recommend you install the sorta official nodejs repo and install the latest lts (18) version if it's debian/ubuntu

https://github.com/nodesource/distributions

Then remove the mc directory `sudo rm -rfv mc` then try the steps above again

**Comment by CSW2000** [comment]
New Insalled Debian 12 on a new SSD on Raspy 4 The Same Problem i am Ready to Day  The Meshcentral will not work.
Yesterday ona VM Mashine it it was runns. What is wrong here Today
![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/d854a7fc-2bea-42b7-97c9-a9543e31de07)
 

Gut Night it is 23:31 in Germany

**Comment by si458** [comment]
That is weird?
It didn't install node 20 for starters because I think u set the version as `20.18` when it should just be a whole number `20`

But besides that it clearly install node 18 (must be default now in repo) so it should of worked? 

what's the contents of package.json?
And what's the output of `npm list` from inside the `mc` folder?

**Comment by CSW2000** [comment]
Hallo guten morgen. 10:00 Uhr in Germany
Nun die Node Version siehe Bild im eletzten post ist 18.13.0 ist bei Debian 12 im nächtlichten Testystem (Bookworm) standard - heir muss ich nicht im Repository herrum basteln.
Nun der inhalt von dem Benutzer "PI"  ist : `pi@meshcentral2:~ $ ls -la
total 36
drwx------ 4 pi   pi   4096 Oct 24 09:39 .
drwxr-xr-x 3 root root 4096 Oct 10 05:39 ..
-rw------- 1 pi   pi    811 Oct 23 23:33 .bash_history
-rw-r--r-- 1 pi   pi    220 Oct 10 05:39 .bash_logout
-rw-r--r-- 1 pi   pi   3523 Oct 10 05:39 .bashrc
drwxr-xr-x 3 pi   pi   4096 Oct 23 23:27 mc
drwxr-xr-x 4 pi   pi   4096 Oct 23 23:26 .npm
-rw-r--r-- 1 pi   pi    807 Oct 10 05:39 .profile
-rw-r--r-- 1 pi   pi      0 Oct 23 23:10 .sudo_as_admin_successful
-rw------- 1 pi   pi     58 Oct 24 09:39 .Xauthority
`
und der Inhalt von ordner mc ist : `pi@meshcentral2:~/mc $ ls -la
total 80
drwxr-xr-x   3 pi pi  4096 Oct 23 23:27 .
drwx------   4 pi pi  4096 Oct 24 09:39 ..
drwxr-xr-x 140 pi pi  4096 Oct 23 23:27 node_modules
-rw-r--r--   1 pi pi    57 Oct 23 23:27 package.json
-rw-r--r--   1 pi pi 63367 Oct 23 23:27 package-lock.json
`
und der inhalt von der datei  package.json?  siehe Bild unten :
![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/78314f5e-661e-40be-a3cd-de3495f5451d)

und npm list im Ordner mc ergiebt : `
pi@meshcentral2:~/mc $ npm list
mc@ /home/pi/mc
└── meshcentral@1.1.14
` and no more ?

**Comment by CSW2000** [comment]
The next attempt to install Meshcentral on another Raspberry with another new SSD, the same error, I get it installed but not running - who can help? Maybe via PM or via remote maintenance - who wants to do this together with me? I'm at the end of my knowledge.
![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/b9f1c055-3d69-4c1f-976f-0421ca11e69f)

**Comment by CSW2000** [comment]
So now i have a runnig new system with Meshentral2 on it.
I did it in a similar way as described [here ](https://meshcentral.com/docs/MeshCentral2InstallGuide.pdf)on page 17.

Meshcentrl Installtion on 2023 With Debian 12(64bit)
____________________________________________________
sudo apt update && sudo apt dist-upgrade
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash
sudo apt-get -y install nodejs
node -v
npm -v
whereis node
node: /usr/bin/node /usr/include/node /usr/share/man/man1/node.1.gz
sudo setcap cap_net_bind_service=+ep /usr/bin/node

sudo su  - Enter
npm -v
npm install -g npm@latest  or npm install -g npm@10.2.1
npm -v
 - r e b o o t   t h e   s y s t e m  -  NOW

npm install meshcentral

node node_modules/meshcentral --wanonly --fastcert

**Comment by si458** [comment]
It might be the `sudo setcap cap_net_bind_service=+ep /usr/bin/node` line that fixed the issue!

As I remember when I ran node as my normal user, meshcentral actually displays this message saying u need to run it to allow ports below than 1024 before u then run node again

**Comment by CSW2000** [comment]
It is also important to update the npm to the latest version before installing Meshcentral
because after the sudo setcap cap_net_bind_service=+ep /usr/bin/node command there is an error message that you should update npm.

So I'm going to install Maria DB and co and try to import the old version. Maybe you have a few tips for me.

![Server Version](https://github.com/Ylianst/MeshCentral/assets/56474379/df30c93d-1a85-4075-bb40-790f5429ad47)

**Comment by si458** [comment]
thanks @CSW2000 we will update the docs in due cause,
BTW the offical docs are here - https://ylianst.github.io/meshCentral/
the PDF install guide is old and outdated!

as for the version number, just click 'Check Server Version' (top one i believe if google translate is correct) and it will show you what version you have installed and any updates waiting

sadly ive never had to import data from an old backup so i really cant help much

our production just used nedb, and my testing machine also uses it,
unless i need to test a database thing, then i use 'nedbtodb' function to import into a blank database

**Comment by CSW2000** [comment]
sorry but the link don´t work https://ylianst.github.io/meshCentral/
It's clear to me about checking the server version, but for the sake of clarity it would be better if you had it like in the picture and you don't have to have it checked for updates first.

Nevertheless, thank you at this point and keep it up.
I hope I don't have to start from scratch - create around 500 customers and redistribute the agents.
I'll start a new post if I get stuck importing.
PS: and not every sentence was from Google Translate - even though I'm almost 60 years old, I can still speak a little bit of English.
Greetings Roland W from Germany - Bavaria

**Comment by si458** [comment]
sorry case sensitive! `MeshCentral` it should of been!

**Comment by MyUncleSam** [comment]
A short question: Did you find something which causes this and could also lead into breaking the docker image?

**Comment by si458** [comment]
> A short question: Did you find something which causes this issue and could also lead into breaking the docker image?

i havent been able to replicate the issue at all? in theory if the values not there, it adds it, so im confused why its calling it if the value is there? but again i cant replicate the issue at all!

**Comment by MyUncleSam** [comment]
> > A short question: Did you find something which causes this issue and could also lead into breaking the docker image?
> 
> i havent been able to replicate the issue at all? in theory if the values not there, it adds it, so im confused why its calling it if the value is there? but again i cant replicate the issue at all!

I cannot promise but I try to replicate it using docker.

**Comment by si458** [comment]
@MyUncleSam plz if you can! 👍

**Comment by CSW2000** [comment]
I'm still getting crazy :-)
As soon as I insert something into the config.json I immediately get Error at module errors again
e.g. this one

`  "agentCustomization": {
        "displayName": "Fernwartung...",
        "description": "Die Fernwartung... von .... ist kostenpflichtig und wird mit XX Euro a Stunde berechnet - Service Tel: 00409....",
        "companyName": "Service .....",
        "serviceName": "fernwartung...",
        "image": "csw_msc.png",
        "installText": "Die Fernwartun...... von ...... und wird mit XX Euro a Stunde berechnet - Service Tel : 0049......",
        "fileName": "FernwartungNM_Agent",
	"foregroundColor": "255,0,0",
	"backgroundColor": "255,255,0"
     },`

The message after starting Meshcentral is then :
`
Error: Cannot find module '/home/pi/meshcentral-data/node_modules/meshcentral'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v18.17.1`

I suspect that the config.json has changed completely. And as soon as I activate the old meshcentral-data folder (initially without a database) it reloads modules and no longer starts.
Now suddenly the 2FA finally works again even when I use the new data folder. There must be an easier way to restore the basic settings. The whole Meshcentral is a tough job.

**Comment by MyUncleSam** [comment]
> @MyUncleSam plz if you can! 👍

I could reproduce it on my first try. So maybe it is just a misconfiguration which is no longer compatible with 1.1.13. But here how to reproduce.

Requirements:
- docker
- running Mariadb server which can be accessed by the docker container - create a new empty database for this test (in my case mariadb 10.5 as docker container)

Workflow:
1. extract the .tar.gz
3. add database host and credentials to config file (I anonymized the url, maybe it needs to be changed too): `meshcentral_test/meshcentral/data/config.json`
4. make sure that the `docker-compose.yaml` file still uses the version `1.1.13` (in the file is the 1.1.14 set, so please change it initial)
5. start the container (`docker compose up`) and create a user - i did not check connections on this test environment but all should work
6. stop the container and remove it using `docker compose down`
7. now change in `docker-compose.yaml` the image to `1.1.14`
8. start the image - errors appear
[meshexample.tar.gz](https://github.com/Ylianst/MeshCentral/files/13127060/meshexample.tar.gz)

If you need help to reproduce it feel free to reach out to me. It could take some moments but I help if possible.

**Comment by CSW2000** [comment]
With version 1.1.14 if I open the config.json with nano and don't change anything in these saves, then restart the Meshcentral server I get this message that the module is missing... If I restart the Raspberry Pi then restart Msehcentral everything is normal .
The program crashed overnight and had to restart the service. The version is not very very unstable... I want my old 1.1.13 back :-(..

I'll recreate it now and show the picture of the console.
![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/c2ada8d4-84c6-4322-aba8-19135481eb8e)

**Comment by StefanCheck24** [comment]
> With version 1.1.14 if I open the config.json with nano and don't change anything in these saves, then restart the Meshcentral server I get this message that the module is missing... If I restart the Raspberry Pi then restart Msehcentral everything is normal . The program crashed overnight and had to restart the service. The version is not very very unstable... I want my old 1.1.13 back :-(..
> 
> I'll recreate it now and show the picture of the console. ![grafik](https://user-images.githubusercontent.com/56474379/277900106-c2ada8d4-84c6-4322-aba8-19135481eb8e.png)

German:
Wenn du willst kann ich versuchen, define Umgebung auf Docker umzuziehen. Dadurch kannst du einfacher Versionen wechseln oder auf einer bleiben. Auch wären damit nicht kompatible Versionen von z.B. Node automatisch behoben. Die alte Umgebung würde dabei nicht geändert werden - sprich es würde zumindest nicht schlimmer werden.

---

English:
If you want I can offer you to try to switch to Docker. With this you can easy switch between versions or pin them. Also stuff like incompatible versionen of e.g. Node should be solved automatically. The old environment would not be touched or changed - so at least it would not make things worse.

**Comment by MyUncleSam** [comment]
> With version 1.1.14 if I open the config.json with nano and don't change anything in these saves, then restart the Meshcentral server I get this message that the module is missing... If I restart the Raspberry Pi then restart Msehcentral everything is normal . The program crashed overnight and had to restart the service. The version is not very very unstable... I want my old 1.1.13 back :-(..
> 
> I'll recreate it now and show the picture of the console. ![grafik](https://user-images.githubusercontent.com/56474379/277900106-c2ada8d4-84c6-4322-aba8-19135481eb8e.png)

German:
Wenn du willst kann ich versuchen, deine Umgebung auf Docker umzuziehen. Dadurch kannst du einfacher Versionen wechseln oder auf einer bleiben. Auch wären damit nicht kompatible Versionen von z.B. Node automatisch behoben. Die alte Umgebung würde dabei nicht geändert werden - sprich es würde zumindest nicht schlimmer werden.

---

English:
If you want I can offer you to try to switch to Docker. With this you can easy switch between versions or pin them. Also stuff like incompatible versionen of e.g. Node should be solved automatically. The old environment would not be touched or changed - so at least it would not make things worse.

**Comment by CSW2000** [comment]
Danke für dein Angebot . aber Docker auf den Raspberry Pi 4  ?  das befürchte ich leistungeinbußen.
Ausserdem habe ich bereits eine Aktuelle Version am Start. Mit dem alten Style. Wenn auch unstabiel,  
Ich muss nur noch irgend wie die mehr als 500 Kunden Agents da rein bringen. - 
So das  die alten Agents sich wieder Verbinden alle anderen Daten sind mir egal.
Mit herstellen der Datenbank über phpmyadmin hat es geklappt nur will Meshagent die nicht lesen.
Wenn sich einer der Programiere mal damit befassen könnt einer der weiß was er da tut, müsste ich nicht tagelang lesen und Basteln.  -- Die Online Videos von Chef hier stimmen ja auch nicht mehr annähernd mit den aktuellen System.
mein andere Lösung besteht darin das ich mir im moment ein Backup von Backup ( FEB-2023) V1.1.4
Und das versuche auf den stand 1.1.13 zu bringen und die fehlenden 30 Agents bekomme ich dann schnell wieder hin.

Goolge Translate in Englisch
Thanks for your offer . but Docker on the Raspberry Pi 4? I fear that there will be a loss of performance.
I also already have a current version available. With the old style. Albeit unstable,
I just have to somehow get the more than 500 customer agents in there. -
So that the old agents connect again, I don't care about any other data.
Creating the database via phpmyadmin worked, but Meshagent doesn't want to read it.
If one of the programmers could deal with it, someone who knows what they're doing, I wouldn't have to spend days reading and tinkering. -- The online videos from Chef here are no longer even remotely consistent with the current system.
My other solution is that I currently have a backup of Backup (FEB-2023) V1.1.4
And I'm trying to bring it up to 1.1.13 and then quickly get the missing 30 agents back.

**Comment by CSW2000** [comment]
Hello, today I took the trouble to gradually renew my cloned backup version 1.1.4
npm install meshcentral@1.1.5 . .6 .7 .8 etc
After version .6 or 7 I had to do 'npm audit fix'
and restart Meshcentral.
Then everything continued normally until version 1.1.11
From version 1.1.12 it is broken with some errors. See picture
back to V1.1.11 .. loads again .. then try to 1.1.13
Also works after `npm audit fix.`
But version 1.1.14 simply never works here.
So back to 1.1.13 And that's good
Auto Udate is always off... That's better!

Maybe the error message will be of some help to you.

![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/b432cf36-e944-4fc8-b731-69739352ee3b)

**Comment by vhuet-laps** [comment]
We are having the same issues as CSW2000 when trying to self-update to 1.1.14 from 1.1.13. We also use MariaDB if it can help to understand the issue.

**Comment by CSW2000** [comment]
@@vhuet-laps

Hello  
-  Edit your config.json   -  selfupdate : false   look at my Picture
- Save config.json
- restart the Computer
- type in console `npm install meshcentral@1.1.13`  or older  - V1.1.13  is good vor me am Raspery PI 4 ist run
- type in console `npm audit fix
- restart Meshcentral `node node_modules/meshcentral --restart`
- and you see with `npm list` what a version are running
 all command are not as SUDO oder SU

good luck from Roland from Germany
 
![grafik](https://github.com/Ylianst/MeshCentral/assets/56474379/1dec2d50-30ad-4af1-8637-9f8433bdd079)

**Comment by MyUncleSam** [comment]
@si458 days ago I wrote an example how to replicate this error using Docker. Were you able to replicate the issue using my documentation? (https://github.com/Ylianst/MeshCentral/issues/5465#issuecomment-1777981444)

**Comment by si458** [comment]
@MyUncleSam thank you, i can replicate,
**but the bug is USER related and not software related !!**
you get this bug IF you use a `mariadb` server with `mysql` settings in `config.json`
`mariadb` users should use `mariadb` instead of `mysql` in the `config.json` !

the mysql package was updated to mysql2 in 1.1.14 to support mysql8 correctly, so i have a feeling its unhappy with mariadb
but if you set `mariadb` instead it downloads the `mariadb` npm package and uses that instead!?

hope this help!!!

**Comment by si458** [comment]
FIXED, SEE ATTACHED PR TO ISSUE !!!
IM SO SORRY ABOUT THIS !!!
I SHOULD OF TESTED MARIADB WITH MYSQL SETTINGS !!!

**Comment by MyUncleSam** [comment]
Thanks for the feedback! I just switched from `mySQL` to `mariadb` inside my `config.json` and it is working now with 1.1.14
So thank you very much for the solution :-)

**Comment by si458** [comment]
@CSW2000 in theory you should be the same, restore an old backup or use old database, then just set `mysql` to `mariadb` and it should just carry on! ive asked @Ylianst to do a release as soon as he can so its fixed for people!
so sorry again for this!

**Comment by vhuet-laps** [comment]
I can confirm that it resolved the issue for us as well. Thanks @si458 and @MyUncleSam

**Comment by si458** [comment]
@vhuet-laps thanks! just embarassed i didnt try the different mysql engines before i upgraded to mysql2 🤦

**Comment by CSW2000** [comment]
> @CSW2000 in theory you should be the same, restore an old backup or use old database, then just set `mysql` to `mariadb` and it should just carry on! ive asked @Ylianst to do a release as soon as he can so its fixed for people! so sorry again for this!

Thanks  
Now it works maridb entry works now fine on my Meshcentral Raspy..
Keep it up you are the best... where do I have to send the donations?
Greetings from Bavaria / Germany... Roland

**Comment by si458** [comment]
Glad it's fixed and sorry about causing the bug in the first place! A new release has been pushed which includes the fix which should fix mariadb servers using mysql settings now!

You can donate on my github page or @Ylianst github page!
https://github.com/sponsors/si458
https://github.com/sponsors/ylianst
