### ISSUE TITLE
Can't see device groups (and their devices) created by other users

### ISSUE THREAD

**Issue by trentdavis** [Ylianst/MeshCentral#5471]
Hello, I've been successfully running a production Mesh Central server since 2019, but I've just discovered something which concerns me:

If another registered user creates a device group - even if that user is not a full admin - I am unable to see that group or the devices in it.  Although I am root admin.  I'm not sure if I'm missing something, or if this is an oversight, but to me, this is an easy way to lose control of your Mesh server.  Imagine not being able to tell exactly how many devices were actually connected and what's going on with each!

I'm hoping that this is something that I have missed, and that the ability to "see everything" is actually there.  

Please let me know!
Thanks!
TD

**Comment by demiurge28** [comment]
add "manageAllDeviceGroups": [ "john" ] to domains to see all groups

  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "manageAllDeviceGroups": [ "john" ]
    }

**Comment by WesleyjanLacerda** [comment]
> adicione "manageAllDeviceGroups": [ "admin_name"] aos domínios para ver todos os grupos
> 
> "domains": { "": { "_title": "MyServer", "_title2": "Servername", "_minify": true, "_newAccounts": true, "_userNameIsEmail": true, "manageAllDeviceGroups": [ "john " ] }

Hello everything is fine ? In this case, I can fill in a list in this array ""manageAllDeviceGroups": [ "john " ]" ... but, putting the email or just the name?

**Comment by demiurge28** [comment]
replace John with your admin name

**Comment by si458** [comment]
closing as stale
