### ISSUE TITLE
Tabbed workspaces

### ISSUE THREAD

**Issue by WesleyjanLacerda** [Ylianst/MeshCentral#5472]
Hello, is it possible to open the "desktop" connection in tabs? 
For example, I have to access several computers at the same time, I wanted to know if there was any way to open each connection in tabs, as is done with "web-rdp", but in my case I cannot use "web-rdp " why the user needs to follow what I'm doing.

![image](https://github.com/Ylianst/MeshCentral/assets/74305459/9961507d-017a-4ee3-a7f3-178474cb0493)

An alternative I saw was to create a "share" with an "unlimited" period to click and open in another tab, but the button is a bit small for quick clicking, and I have to create this share every time I access it.

**Comment by si458** [comment]
If you hold down the shift key while clicking the tabs they will open in new tabs for also!

Also hint, right click everything!!! the is always more hidden options 😉

**Comment by WesleyjanLacerda** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/74305459/273947a3-68f5-4365-bda9-cecb4b33fc34)

Yes yes, there are some commands for using the click, what I was looking for was something more direct like a button, for example teamviewer web when entering the ID to connect it opens in another tab, the "immense/Remotely" also does this, opening in another tab when connecting to the machine.

![image](https://github.com/Ylianst/MeshCentral/assets/74305459/83605495-9586-4417-9ffa-e4cd760dc7ac)

A solution that worked for now was to create links to call the router and access it, but not yet in tabs.

**Comment by si458** [comment]
The is no button, you simply hold shift key and click desktop, this opens the display in a new tab, then u can connect also you can click the fullscreen button, to make it full screen if you want too

**Comment by WesleyjanLacerda** [comment]
Thanks for the tip, I'll use it both ways 

> The is no button, you simply hold shift key and click desktop, this opens the display in a new tab, then u can connect also you can click the fullscreen button, to make it full screen if you want too

Thanks for the tip, I'll use it both ways!
