### ISSUE TITLE
Close Button for connection 

### ISSUE THREAD

**Issue by kugelbit** [Ylianst/MeshCentral#5473]
Hey,

Simple Question:
Is there an possibility to add an connection close button? So the user who is on the other side can close the connection. 

I need a possibility where the user on the other side of the remote connection can cut the connection any time he want. 

This could be an Button on the connection toolbar (see screenshot) Or at in windows-taskbar. 

perhaps i missed some config. In this case am sorry for the question.

Something like this:
![Auswahl_130](https://github.com/Ylianst/MeshCentral/assets/9332616/963bd31d-98c4-4c72-a624-b1c860c2875c)

**Comment by WesleyjanLacerda** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/74305459/a7df2097-b49f-4a86-a568-0a3665afd7c7)

If the user clicks on the "X" button, the connection is no longer closed?

**Comment by kugelbit** [comment]
> If the user clicks on the "X" button, the connection is no longer closed?

This was the case in version 1.1.9  I updated to version 1.1.15  and now the "X" button works as excepted... 

Thank you
