### ISSUE TITLE
RDP Setup... 

### ISSUE THREAD

**Issue by mikeleblank** [Ylianst/MeshCentral#5479]
> **Solution in Node V20.9.0 works correctly**

Hello, I am using meshcentral and I can connect without problems with the agent.

I tried to use the RDP function but it stays in "Setup..." and never loads, after a few minutes it shows "Disconnected"

Test Windows 10 Professional RDP active, Windows Server 2016 RDP active.

MeshCentral V1.1.14 Node v21.0.0 installed on ubuntu server 22.04 VPS + NGINX PROXY

Remove nginx proxy, direct connection doesn't work

![capture](https://github.com/Ylianst/MeshCentral/assets/119367160/212963d7-f263-4b96-93db-016760f3d2d2)

I use an nginx proxy in front of the meshcentral server

Do I need to configure any extra options?

I don't have a direct tunnel, only the meshcentral agent installed

> **Solution in Node V20.9.0 works correctly**

**Comment by si458** [comment]
Have you checked you have rdp (remote desktop) enabled on the windows machine in settings?
As you don't say what os the remote device is your trying to connect to

Also are you using cloudflare? (Stupid question sorry but have to ask as they are having nothing but problems at the Moment)

**Comment by mikeleblank** [comment]
Test Windows 10 Professional RDP active, Windows Server 2016 RDP active.

I use a subdomain with my own server, I do not use cloudflare.

**Comment by mikeleblank** [comment]
> Have you checked you have rdp (remote desktop) enabled on the windows machine in settings? As you don't say what os the remote device is your trying to connect to
> 
> Also are you using cloudflare? (Stupid question sorry but have to ask as they are having nothing but problems at the Moment)

Solution in Node V20.9.0 works correctly

**Comment by si458** [comment]
> Solution in Node V20.9.0 works correctly

so node 21 doesnt work but node 20 does? weird?

**Comment by mikeleblank** [comment]
> > Solution in Node V20.9.0 works correctly
> 
> so node 21 doesnt work but node 20 does? weird?

Exact

Novnc works on v21

Excellent project, how can I support the project?

I have been using it for 1 year and it is an excellent tool

**Comment by si458** [comment]
you can sponsor 

myself https://github.com/sponsors/si458
or
@Ylianst https://github.com/sponsors/ylianst

just investigating if node 21 is having issues for you

**Comment by si458** [comment]
just tried node 21 here and works perfectly fine?

**Comment by mikeleblank** [comment]
> just tried node 21 here and works perfectly fine?

strange, I even tried on a new ct within proxmox in case it was my configuration

**Comment by si458** [comment]
can you roll back to node 20 and use that is that works for RDP connect?

**Comment by mikeleblank** [comment]
> can you roll back to node 20 and use that is that works for RDP connect?

It is working perfectly on node 20

**Comment by si458** [comment]
> > can you roll back to node 20 and use that is that works for RDP connect?
> 
> It is working perfectly on node 20

just stick with node 20 then! as that is the latest LTS version now for 2 years!

**Comment by mikeleblank** [comment]
thanks
