### ISSUE TITLE
centos 5 OpenSSL: error

### ISSUE THREAD

**Issue by lexisman** [Ylianst/MeshCentral#5484]
**Describe your issue**
I am trying to add an agent, Centos5 32bit, I know its a bit old OS, but I can not upgrade to the latest versions since I am running a proprietary software that has not been updated by the provider. The error that I am getting is "OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection."
I'm wondering if there is someone here who have successfully installed the agent and was able to solve this issue. Thanks.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - standalone
 - Network: nginx reverse proxy, Letsencrypt]
 - Version:  1.1.13
 - Node: v16.20.2

**Client Device (please complete the following information):**
 - Device: desktop
 - OS: Centos 5
 - Network:  Remote over WAN
 - Browser:  Google Chrome
 
**Remote Device (please complete the following information):**
 - Device: desktop
 - OS: centos 5
 - Network: Remote over WAN
 - Current Core Version (if known): Nov 21 2022, 2484385032

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "mycentral.mycentral.ca",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "DbRecordsEncryptKey": "MySecretPasswordisMine",
    "sessionKey": "MyReallySecretPassword1",
    "Port": 4430,
    "AliasPort": 443,
    "RedirPort": 800,
    "RedirAliasPort": 80,
    "AgentPong": 300,
    "TlsOffload": "127.0.0.1",
    "MpsPort": 44330,
    "MpsAliasPort": 4433,
    "MpsTlsOffload": true,
    "ClickOnce": true,
    "DesktopMultiplex": true,
    "_RelayPort": 4530,
    "_RelayAliasPort": 453,
    "RelayDns": "mycentral.mycentral.ca",
    "Amtmanager": true,
    "CleanNpmCacheOnUpdate": true,
    "AllowHighQualityDesktop": true,
    "AllowFraming": "true",
    "_WebRTC": true
  },

  "domains": {
    "": {
      "certUrl": "https://127.0.0.1:443",
      "title": "Mycentral Monitoring Systems",
      "title2": "mycentral",
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "TitlePicture": "title-mycompagny.png"
    }
  },

  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "mycentral@gmail.com",
    "names": "mycentral.mycentral.ca",
    "rsaKeySize": 3072,
    "production": true
  }
}

**Comment by si458** [comment]
what version os centos are you running? the latest for version of 5 is 5.11 ?
gunna try get an iso and make a vm to see if i can help

**Comment by si458** [comment]
i dont think centos 5 is going to be supported
a away around is to download the binary installer to your local computer then SFTP it over,
but after you `chmod a+x meshagent` then try `./meshagent`
i just get error after error
```
[root@localhost simon]# ./meshagent
./meshagent: /lib/libc.so.6: version `GLIBC_2.9' not found (required by ./meshagent)
./meshagent: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./meshagent)
./meshagent: /lib/libc.so.6: version `GLIBC_2.11' not found (required by ./meshagent)
```

**Comment by lexisman** [comment]
It's centOS 5.4 version. I will try your suggestion. Thank you..
