### ISSUE TITLE
Feature Request: Hardware power action options in device action menus

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#549]
If AMT/CIRA/ISM is a available for a device, a "hardware wake-up" entry in the device action menus could wake clients that may not be woken up using WoL (off network segment, roaming device, no WoL driver support, ...).
Alternatively, both WoL and hardware power action may be performed if a ME enabled client needs to be woken up.

Also, "Reset" and "Poweroff" as performed by the agent shall be renamed to "Reboot" and "Shutdown" to better match the actions actually performed by the agent, while real "Reset" and "Poweroff" actions performed through AMT/CIRA/ISM may be added if available.

Regarding WoL driver support:
The i219 drivers offered and maintained by Microsoft through Windows Update for WIndows 10 seems to be a lightly crippled Intel driver that does not support enabling WoL on shutdown/standby. This means it requires admins to install and maintain vendor supplied drivers on systems that are otherwise fully covered by Windows Update.

**Comment by Ylianst** [comment]
This is a good request. It's my plan to do this at some point. I need to put a WSMAN stack on the server and work on AMT/CIRA/ISM management operations from the server including power operations. My general view is that MeshCentral should use whatever technique is available to perform the power action, including Intel AMT/ISM.

This said, I am sitting on a mountain of work. Not sure when I can get this done.

**Comment by jsastriawan** [comment]
We have server side WSMan stack that could support AMT direct, CIRA and APF bridge transport.

**Comment by Ylianst** [comment]
You did add that code, but I need to wire it in to do this stuff (and much more). That will be a bunch of work.

**Comment by veitw** [comment]
This feature has been added a while ago. :) Closing this feature request.
