### ISSUE TITLE
GroupMessage and GroupToast actions in 'meshctrl.js' 

### ISSUE THREAD

**Issue by CapriPL** [Ylianst/MeshCentral#5494]
Hello,

It would be nice if 'meshctrl.js' offered GroupMessage and GroupToast actions , i.e. equivalent to 'Group Action / Device notification', but with the possibility of using it in your own scripts. There is often a need to notify all users within a device group.

Regards, Grzegorz.

**Comment by si458** [comment]
Should be simple enough! If the web ui can do a feature, we just copy what the websocket does and put it into meshctrl.js 👍 
Will have a look tomorrow for you!

**Comment by CapriPL** [comment]
Hello,
Thank you for your quick response and interest in the topic.
If possible, it would be ideal to be able to do it like this:
`MeshCtrl GroupMessage --id groupid --msg "message" --title "title"`
Thank you once again.

Regards, Grzegorz.

**Comment by si458** [comment]
just checking this out
the is already these feature built into meshctrl?
```
console.log(winRemoveSingleQuotes("  MeshCtrl DeviceMessage --id 'deviceid' --msg \"message\" --title \"title\""));
console.log(winRemoveSingleQuotes("  MeshCtrl DeviceToast --id 'deviceid' --msg \"message\" --title \"title\""));
```
you can set `deviceid` to the deviceid you want to send too, and to send to multiple, just can the command multiple commands, each time a different id

**Comment by CapriPL** [comment]
I know there are 'DeviceMessage' and 'DeviceToast' commands.
From my point of view, if I want to send a notification to an entire group of devices, I have to find the 'id' of each turned on computer within the group, which is difficult from the script level because I have to parse the result of the 'ListDevices' command.
And I also don't want to have a script where all computer 'id' are hardcoded, another PC in the group means a change in the script.
The 'GroupMessage/GroupToast' command should internally find the 'id' of all computers in the group and send a message, which is a very flexible solution, hence my request.

**Comment by si458** [comment]
Ahh now I get you!
So you want the command to specify a groupid, and it then get all the device ids then send the message/toast to each machine!
Got it!

**Comment by CapriPL** [comment]
That's exactly what I mean.

G.

**Comment by si458** [comment]
ok all added!
```
simon@testmc:~/meshcentral/MeshCentral$ node meshctrl.js help groupmessage
Open a message box on remote devices in a specific device group, Example usages:

  MeshCtrl GroupMessage --id 'devicegroupid' --msg "message"
  MeshCtrl GroupMessage --id 'devicegroupid' --msg "message" --title "title"
  MeshCtrl GroupMessage --id 'devicegroupid' --msg "message" --title "title" --timeout 120000

Required arguments:

  --id '[devicegroupid]'        - The device identifier.
  --msg [message]          - The message to display.

Optional arguments:

  --title [title]          - Messagebox title, default is "MeshCentral".
  --timeout [miliseconds]  - After timeout messagebox vanishes, 0 keeps messagebox open until closed manually, default is 120000 (2 Minutes).
simon@testmc:~/meshcentral/MeshCentral$ node meshctrl.js help grouptoast
Display a toast notification on remote devices in a specific device group, Example usages:

  MeshCtrl GroupToast --id 'devicegroupid' --msg "message"
  MeshCtrl GroupToast --id 'devicegroupid' --msg "message" --title "title"

Required arguments:

  --id '[devicegroupid]'      - The device identifier.
  --msg [message]        - The message to display.

Optional arguments:

  --title [title]        - Toast title, default is "MeshCentral".
```

**Comment by CapriPL** [comment]
Excellent! Thank you very much.

G.

**Comment by si458** [comment]
merged so will be available in next release OR in docker `master` build in about 15mins OR just download the `meshctrl.js` directly from the master branch 👍

**Comment by CapriPL** [comment]
Great news, thank you again 😊

Regards, Grzegorz.
