### ISSUE TITLE
Selecting "Screen View" Not Working on Fedora

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#55]
Environment: Fedora 29 with Cinnamon

Agent installs and works fine.  VIew is fine.  But when I have multiple monitors and try to select one, it shows both in the list, but making the selection does nothing.

We are on the "x" release at this point.

**Comment by wh1te909** [comment]
same problem on windows 10
tried with 2 different win 10 computers with multiple monitors, trying to change between displays does nothing, the multi monitor view is always show and makes it almost impossible to remote control because view is so small

**Comment by krayon007** [comment]
For the Windows 10 issue, which server version are you running? I have 3 monitors on my windows 10 machine, and the the multi monitor view always seems to work. The only issue I noticed, is that if I lock the desktop while on an individual monitor, the view switches to show all the monitors, but the toggle still shows that it is viewing a single monitor. Tho if you select a monitor, it correctly switched the display.

As far as the Fedora issue, I'll have to build a test setup for that, as I don't have a multi-monitor linux system, so I'll get back to you on that one...

**Comment by wh1te909** [comment]
I am always on the latest server version and have been testing with every release. My original issue seems to have been resolved but now another issue.

My home computer is fine, I have 2 monitors running on Nvidia graphics and no issues, switching displays works as intended.

My work computer is running 2 monitors on AMD graphics. When choose Display 1 nothing happens, it remains on dual screen view. When I click Display 2 then Display 1 is shown.

I have been also installing the agent on some of our client's pcs and noticed same behavior. Choosing Display 1 does nothing and choosing Display 2 shows Display 1. Never able to get Display 2 to work.
These computers are all running integrated graphics (Intel 3rd and 4th gen i5's and i7's).

I've tested on some more client's Windows 8.1 computers with dual monitors running the exact same software / hardware stack as the windows 10 pc's and no issues on those all working as intended.

**Comment by krayon007** [comment]
What build of Windows 10 are you running? (ie, when you run a cmd prompt, what is the full version of windows 10 that is reported?)

**Comment by wh1te909** [comment]
Version 1803 (build 17134.523)

**Comment by sorvani** [comment]
Windows 10 would be a different issue IMO.

**Comment by sorvani** [comment]
@Ylianst also on Fedora 29 + Cinnamon.
![image](https://user-images.githubusercontent.com/3302372/52907744-50addf00-322d-11e9-9f68-d0f860cb4b6c.png)
