### ISSUE TITLE
Question: Best web browser for using MC?

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#550]
We noticed (to our surprise) that on our Linux driven admin workstations both the agent and AMT remote desktops are significantly faster in Firefox than in Chromium.
Especially the AMT desktop is awfully slow in Chromium compared to Firefox (I estimate 1:5), while in Firefox AMT remote desktop sessions to local devices are almost as fast as agent+WebRTC.

We have not tried other browsers so far. Are there hints on which browser shall be used for the best user experience?
Maybe special settings to optimise performance for MC?

**Comment by Ylianst** [comment]
Yes - There is certainly something specifically bad about my Hardware KVM viewer code that makes it much slower on Chrome than Firefox. I have to get and decode the image from blob of bits and something I am doing is making Chrome much slower. I need to find a profiler one way and see what is going on.

I don't think it's affecting anything else, it's just the Intel AMT KVM tile decoder JavaScript. You should change this issue to a required to fix it. I would have to research what is going on. If you find other perform issues between Chrome & Firefox, let me know.

**Comment by veitw** [comment]
Our admin workstations usually run everything on Firefox and we use it halfscreen. But as MC does not (yet) offer real fullscreen for remote desktop, we are evaluating alternatives for running just MC maximised in a separate window/browser, also for having separate behaviour for e.g. popups, so e.g. chat windows open up in real popups instead of tabs, and to get rid of control items that are useless in MC but consuming lots of screen space such as address bar.

Our first try was to package it as an Electron app as a simple chromium webview for the website, which worked well but was rotting slow.

Then we installed Chromium to use its "Add to desktop" web app feature, but that was just as slow, so we found it not to be Electron's fault but Chromium's.

Maybe we will just set up a separate Firefox profile for MC, allow popups and hide all the controls that eat up the screen space and run it maximised. We will need to live with the subsequent limitations such as being less portable/packageable to distribute over the admin workstations and interfering with other Firefox instances through the Firefox remote feature.

**Comment by PathfinderNetworks** [comment]
I run it mostly in Microsoft Edge (yeah, I know, LOL).  Works very well in Edge. I also run it in Firefox and IE.

**Comment by Ylianst** [comment]
Just to make it clear, if the Intel AMT Hardware KVM was fast in Chromium, you would be ok? Is there anything else that is slow?

For real full screen, you can hold "shift" and hit the full screen button (red circle). Let me know if this works?

![x](https://user-images.githubusercontent.com/1319013/66440996-e7f8ba00-e9e9-11e9-8a44-cc8bccc4fd24.png)

**Comment by veitw** [comment]
> Just to make it clear, if the Intel AMT Hardware KVM was fast in Chromium, you would be ok? 

Chromium is really not a necessity for us. We are in Germany, this is like Firefox country. Please do not invest time on this just for us, I think there are lots of other issues of significance to be handled. We are just trying to optimise our workflows, and we have other options to draw.

> Is there anything else that is slow?

Agent remote desktop is significantly slower, too. It can easily be noticed when moving a Window up so the desktop background below the window is redrawn. In Chromium we can watch this tile by tile while it is almost instant tile row by tile row in Firefox.

> For real full screen, you can hold "shift" and hit the full screen button (red circle). Let me know if this works?

Oh, it even has a mouse-over tooltip mentioning this. I totally missed that, sorry. Works like a charm. :D

**Comment by veitw** [comment]
This is our first attempt to make MC appear more like a desktop app using a separate Firefox instance instead of Chromium Desktop App or Electron for speed reasons:

![screenshot](https://user-images.githubusercontent.com/16285895/66477677-f05bfe00-ea98-11e9-8e6e-537f9a9637e5.png)

We instructed Firefox to do not use standard window decorations and use its own to not lose precious screen space to any controls, but so far we did not figure out how to show the window title and how to move the window controls (maximise, minimise, close). But as double clicking the title will maximise/restore, minimising can be done through the task dash and Alt+F4 will close the window, we have that going for us.

We also did some dirty Firefox CSS hacks that overload MeshCentral's CSS to free up further vertical space, which is particularly precious for us when using remote desktop.

**Comment by Ylianst** [comment]
One thing you can do is add "?hide=5" at the end of the URL when you access a MeshCentral server. This will hide the header and footer. Not exactly the same, but almost. You made a smaller header.

The ?hide=xxx option takes a number that is a bit mask. 1 hides the header, 4 hides the footer. So 1+4 hides both. You can try 1,2,4,8,16,32... to see what they do. The idea is to allow users to embed MeshCentral within another website. This said, maybe I can add options to make a smaller header and remove the footer.

**Comment by veitw** [comment]
Ah yes, this is nice and it could remove a lot of our CSS hacks, but unfortunately, it is also very buggy so far and in Top Bar Interface mode (which we favour) even unusable.

I created a separate bug issue on this: #559

**Comment by veitw** [comment]
Closing issue as this question has been answered for me, thank you very much!
