### ISSUE TITLE
Meshcentral Service Not working!!!

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#5505]
Mesh Central service is stopped, but my server is working!!!
![20231103-23-51-52](https://github.com/Ylianst/MeshCentral/assets/42680639/7ece7d15-162f-40ba-8323-2f46460e179d)

**Comment by si458** [comment]
This looks like a windows services bug and not a meshcentral bug
As you can see on the left side it's shows stop or restart, so it thinks it's running, 
I would check task manager then details and see if you can find node.exe or meshcentral.exe running

**Comment by bravery-only** [comment]
When I start the Mesh Central service:
![20231104-08-39-41](https://github.com/Ylianst/MeshCentral/assets/42680639/866e7e95-6dda-4c5f-9798-f1f0558eee17)




When I stop the Mesh Central service:
![20231104-08-46-47](https://github.com/Ylianst/MeshCentral/assets/42680639/53bc9340-9dcf-4e8b-957b-c7fb051386f4)


In both cases, my server works without starting Mesh Central!!!

**Comment by si458** [comment]
So it's still running somewhere else, either a command prompt or another service, 

You can use Microsoft sysinternals tool called process explorer (run as admin)
The tool is an advanced task manager, you can see where the file is being from, but also which service(if one) ran it

I would also just restart the whole server and it should sort itself out

**Comment by bravery-only** [comment]
I uninstalled Mesh Central. I use the Meshcentral Installation Tool wizard to install Mesh Central on Windows Server. Do you know another way to install it?

**Comment by si458** [comment]
you can check the docs online or use the advanced setup under the windows section
https://ylianst.github.io/MeshCentral/install/install2/#npm-installation-for-advanced-users
(basically install node js, then follow steps to install where ever you want)

**Comment by bravery-only** [comment]
I Removed Mesh Central and reinstalled it, but the problem was not solved. The Meshcentral service stopped, but Server Mesh Central works and disconnects for 30-45 seconds!!

**Comment by si458** [comment]
I'm not sure then I'm afraid
if ur still getting the same problem, then your server is running meshcentral somewhere located on it
Try restarting your whole server after u have uninstalled meshcentral completely

**Comment by bravery-only** [comment]
![20231104-16-32-37](https://github.com/Ylianst/MeshCentral/assets/42680639/99acbb63-0f4d-4e22-8445-027dbd55944f)

**Comment by si458** [comment]
so it thinks you are running 4 versions of meshcentral ?
one called from meshcentral.exe (which must be the windows service)
and 3 others,
you can click the node.exe and use 'kill process' to stop them running
but also check the 'command line' which will show you whats its running and where its running from

**Comment by bravery-only** [comment]
I stop the meshcentral service again, the server works again!!
![20231104-17-25-16](https://github.com/Ylianst/MeshCentral/assets/42680639/af309860-d439-4291-b0a7-f31754d5937f)

**Comment by CapriPL** [comment]
Your screenshot clearly shows that 'meshcentral.exe' is run by Windows Service Wraper by CloudBees, Inc. and 'node.exe' are its child processes.
If you don't control what services are automatically launched on your computer, none of us will be able to help you.

**Comment by bravery-only** [comment]
I installed only Mesh Central on my Windows server.  Can someone remote desktop my system and help?

**Comment by bravery-only** [comment]
After stopping Mesh Central Service, the server is still working and the processor is like this:

![20231104-23-45-52](https://github.com/Ylianst/MeshCentral/assets/42680639/166d972c-eae5-4780-9f83-9a3b3a325ab4)

**Comment by si458** [comment]
> After stopping Mesh Central Service, the server is still working and the processor is like this:
> 
> ![20231104-23-45-52](https://user-images.githubusercontent.com/42680639/280490442-166d972c-eae5-4780-9f83-9a3b3a325ab4.png)

this looks like a bug then with the meshcentral installer and winsw not closing the node.exe correctly

i would personally, uninstall meshcentral completely, and use the command line version with pm2 instead as explained above

**Comment by bravery-only** [comment]
And another bug is that when I repeatedly send messages, the server automatically disconnects

![20231105-00-08-52](https://github.com/Ylianst/MeshCentral/assets/42680639/6f61f91d-cefc-4f4b-9fdc-cc1c923cf7ba)

![20231105-00-06-00](https://github.com/Ylianst/MeshCentral/assets/42680639/f1cc4c56-5fc9-47f7-b5a6-4c5ad005d181)

**Comment by si458** [comment]
> And another bug is that when I repeatedly send messages, the server automatically disconnects
> 
> ![20231105-00-08-52](https://user-images.githubusercontent.com/42680639/280491264-6f61f91d-cefc-4f4b-9fdc-cc1c923cf7ba.png)
> 
> ![20231105-00-06-00](https://user-images.githubusercontent.com/42680639/280491196-f1cc4c56-5fc9-47f7-b5a6-4c5ad005d181.png)

plz open a seperate issue

**Comment by bravery-only** [comment]
> you can check the docs online or use the advanced setup under the windows section https://ylianst.github.io/MeshCentral/install/install2/#npm-installation-for-advanced-users (basically install node js, then follow steps to install where ever you want)
> 
> EDIT: you can also use PM2 to startup the node automatically https://pm2.keymetrics.io/docs/usage/quick-start/

I want to install the Mesh Central service, this method is with the command line. The command line must be running. How can you install Mesh Central as a service?

**Comment by si458** [comment]
once you have it installed and working on the command line, you can then follow https://github.com/Ylianst/MeshCentral/issues/5401 which helps setting up pm2 on linux (but its basically the same for windows)
