### ISSUE TITLE
Just get a black screen when going to remotely access display. 

### ISSUE THREAD

**Issue by Goldmaster** [Ylianst/MeshCentral#5515]
**Describe the bug**
When I see one of my computers online, I click on the computer, then click connect. It says connected, but all i get is black screen. Later it then says disconnected. I have tried to remotely browse files and even that doesn't seam to show. I do see when the computer is online or not. I used to have no issue until a few weeks ago and its strange why this has now happened. its happening to multiple computers. It does appear there is a connection but just no screen display.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a computer that is online
2. Click on connect
3. wait a bit and the display connected but with a black screen.

**Expected behaviour**
to view a desktop. i had been able to before without issue.

**Screenshots**
https://ibb.co/3rpKCXQ

**Server Software (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Network: LAN using ngx reverse proxy, Cloudflare Argo SSL full strict,
 - Version: 1.1.15
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: unraid vm
 - OS: Windows 11
 - Network: Remote over WAN
 - Browser: Firefox
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: desktop
 - OS: windows 10
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 200256441

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "true",
    "publicPushNotifications": "true"
  },
  "domains": {
	"": {
	"_title": "MyServer",
    "_title2": "Servername",
    "_minify": true,
    "NewAccounts": "true",
	"_userNameIsEmail": true,
    "certUrl": "https://domain.com:443"
	}
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
	"production": false
  }
}

**Comment by si458** [comment]
YOU ARE USING CLOUDFLARE `Network: LAN using ngx reverse proxy, Cloudflare Argo SSL full strict,`
CLOUDFLARE ARE HAVING NOTHING BUT PROBLEMS SORRY
PLEASE REFER TO #5302

**Comment by IronBeardKnight** [comment]
> YOU ARE USING CLOUDFLARE `Network: LAN using ngx reverse proxy, Cloudflare Argo SSL full strict,` CLOUDFLARE ARE HAVING NOTHING BUT PROBLEMS SORRY PLEASE REFER TO #5302

I believe that mechcentral may be using an out of date version of the rpc protocol possibly.

I was looking into this doing some packet sniffing and such a few months ago and found it to only be when the rpc packets are getting transferred through  and after checking the errors I was getting it lead me to that. Don't ask me to produce much more than this as I currently don't have much time to spare at the moment but it would be your best place to start instead of blaming Cloudflare and waiting for them to fix something we all know will never get fixed and without the ability to use proxy it creates a security vulnerability exposing your ip directly allowing for direct router brute force bypassing any Cloudflare mitigations.

In this day and age its sooo important to be as secure with layers as much as possible.

**Comment by dinger1986** [comment]
> Don't ask me to produce much more than this as I currently don't have much time to spare at the moment but it would be your best place to start instead of blaming Cloudflare
> 

....it's an opensource community project! It's not backed by a commercial company, why do others need to have time to fix something as a volunteer but they can't ask you for more info? 

Guess your time is much more valuable than others!
