### ISSUE TITLE
Trouble updating server

### ISSUE THREAD

**Issue by Martin900t** [Ylianst/MeshCentral#5516]
Server Software (please complete the following information):
•	OS: Windows Server 2019
•	Virtualization: Hyper-V

I’ve been running and updating MeshCentral without issue since May 2022. After ugrading to 1.1.13 I got a message "WARNING: MeshCentral will require Node v16 or above in the future, your current version is v12.16.2." I stopped the MeshCentral service, downloaded and installed the Node.js 18.18.2 Win installer, and restarted the MeshCentral service. All looks good.

The problem now is that I’ve tried to upgrade to 1.1.14, and then 1.1.15 and it (appears to?) fail. I waited about 10 minutes and check and find that the MeshCentral service is not running. If I try to start it I get Error 1067: The process terminated unexpectedly. After failed upgrades I revert to a checkpoint running 1.1.13.

I originally installed MeshCentral using the Win installer.

Using node -v I get 18.18.2 and npm – v I get 9.8.1. I see there is now Node.js which includes npm 10.0.1 and am planning to try installing that and then the MeshCentral upgrade again when I get a chance.

If anyone knows anything that will help I’d appreciate hearing from you. Can I update from a command line to see where something fails, or a log to check?

```

**Comment by si458** [comment]
ive just tried to replicate it here for you to have a look what happened

you can check the windows event logs for help OR browse to `C:\Program Files\Open Source\MeshCentral\winservice\daemon`
and check out `meshcentral.out.log, meshcentral.err.log, meshcentral.wrapper.log` for help as to what happened!

**Comment by Martin900t** [comment]
Thanks. I'm hoping upgrading Node.js again clears things up but this gives me something to look at if it doesn't.

**Comment by si458** [comment]
so far, ive done the following
stop meshcentral service (check with taskmanager and process explorer)
download node 18 x64 msi, install it (MAKE SURE YOU HAVE TICKED THE INSTALL EXTRA TOOLS FROM CHOCOLATELY!)
start meshcentral service
message goes away! so at least the node upgrade works!
i just cant quite get the upgrade from 1.1.13 to 1.1.15 correct
how did you upgrade? was it from inside the web ui, inside the meshcentralinstaller exe, npm install?

**Comment by Martin900t** [comment]
I was using the web UI.

**Comment by si458** [comment]
cant get the web ui to update correctly?

BUT if i updating using the meshcentralinstaller.exe, it works no problem! so give that a try!

it seems to not install the node-windows correctly from the web ui, which then goofs up the windows service!?

**Comment by Martin900t** [comment]
Nice, thanks. But how do I update with the exe?

**Comment by si458** [comment]
You just run the meshcentralinstaller.exe (you can download it from the website if u deleted it by accident) and click update :)

**Comment by Martin900t** [comment]
Nice, just picked up v 2.11.7849.20089 of the installer. It will be a while before I can give it a go. Thanks so much for helping.

**Comment by si458** [comment]
To be honest the installer should put a copy of the installer inside the program files, for future use, but it doesn't, so u have to download the exe each time or keep the exe somewhere

**Comment by Martin900t** [comment]
The installer did the trick. Thanks again.

**Comment by si458** [comment]
Glad it worked!
Will update docs to say to use the installer to update rather than webui if u used the windows installer!
