### ISSUE TITLE
Avast detecting MeshAgent service as malware

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#552]
So this just happened tonight.  I had mentioned in another thread how Avast wasn't detecting Mesh as malware once it was installed.  But now it seems as though they are.  At least for 32bit installs.
I got this alert tonight from one of my devices.  This particular alert is flagging the Windows service.  Fortunately I had an exception in place for the executable so that Avast didn't act on it.  But it is very concerning that antivirus engines are seeing, once again, Mesh as an infection.   

An Avast Business CloudCare High-Priority Alert Occurred.

Description: The device is infected with a security threat.
Details: 
Threat Description: Win32:Malware-gen
Threat Severity: Infection
Threat Shield: Antivirus
Object Name: SVC: Mesh Agent > C:\Program Files\Mesh Agent\MeshAgent.exe
Virus Action: Do nothing

**Comment by PathfinderNetworks** [comment]
By the way, I did report it to Avast as a false positive- but not sure how much that is going to help.  Fortunately it does appear to be only the 32bit agent, for now.

**Comment by Ylianst** [comment]
I try to run both 32 and 64bit versions of the MeshAgent thru [VirusTotal](https://www.virustotal.com/) first before releasing it. I will have to check again with Bryan and see if we can do something about this.

**Comment by PathfinderNetworks** [comment]
Avast has removed it from their virus definitions.  But that would only impact devices that use Avast for antivirus.  

Hello, 

Thank you for reporting this false positive. 
Our virus specialists have now cleared its reputation in our database.
With URLs this change should be instant, but it might take up to 24 hours with files.
For future reference you might also find the following article to be useful: Avast Clean Guidelines.

Best regards, 

Avast Customer Care

**Comment by wvt-adm** [comment]
now windows 10 professional german detects also the file meshservice-signed.exe as a trojan win32/fuery.c!cl ... screenshots att. but in german ;-)
![trojan1](https://user-images.githubusercontent.com/56296924/66620032-5e124200-ebdf-11e9-9cb3-61da1ee029e3.JPG)
![trojan2](https://user-images.githubusercontent.com/56296924/66620035-5f436f00-ebdf-11e9-8c72-f6a145563a50.JPG)

**Comment by Ylianst** [comment]
Bryan has a new MeshAgent that will be released soon with new features & fixes. Hopefully we will fix this too.

**Comment by Ylianst** [comment]
FYI. Someone submitting the MeshAgent to Symantec for whitelisting and they approved it. Nice work! Much appreciated.

```
Upon further analysis and investigation we have verified your submission and,
as such, the detection(s) for the following file(s) will be removed from our products:

    File name: remote.exe
    MD5: 13E21282EC6F9DEA924B8D2E3AC4C0B6
    SHA256: 5D82DE03BE5A8AD7B8B32670A1B02858C69623DE2D841EA52C5D3F2C01A005D8
    Note: Whitelisting may take up to 24 hours to take effect via Live Update
```

**Comment by whalehub** [comment]
MeshAgent on Windows 10 is displaying a SmartScreen warning with the latest version of MeshCentral for me. It didn't use to do that. Did something about the signing certificate change?

**Comment by krayon007** [comment]
Nothing has changed. Ylian said when he released the agent he tested it on VirusTotal, and it was clean, butbehrnni rescanned the exact same binary it showed up as you posted, when I scanned a few days ago. It seems like it shows as clean when we release, then it gets flagged/tagged  later.. I'm testing a few tricks to see if I can avoid this...

**Comment by D4V3M0NK** [comment]
Just as a note: does the router go through the same process with regards to certificates?  I've a brand new install of Windows 10 and in attempting to install MCR, I get the "unknown publisher" pop-up preventing me from installing.  

Is there a certificate that needs to be installed, or should it be automatic at this point?

**Comment by Ylianst** [comment]
I used to have a certificate but it got revoked (See #251). I now self-sign all the binaries and the public cert is in any MeshCentral installation at /node_modules/meshcentral/agents/codesign.cer. I may go back and get a new certificate at some point, but my plan is to code sign everything except the MeshAgent.exe. If you right-click on the MeshCentral Router and hit properties, you should see it. If you load the "codesign.cer", it should show as ok.

**Comment by infineonnetworks** [comment]
Since for anyone who self-hosts meshcentral, all the binaries that are relevant for each group site would need to be signed differently, would it be relevant for us to buy a code signing certificate from Comodo for instance and are we able to sign the agent binaries then automatically when we send out the installer? 
Not to worries about potentially spending $70/year on a code signing certificate for my company. 
https://comodosslstore.com/code-signing

**Comment by whalehub** [comment]
After upgrading to the latest version of MeshCentral, Kaspersky no longer recognizes MeshAgent as malware.

**Comment by Ylianst** [comment]
For MeshAgent signing, yes, anyone can sign the agent. You go in the /node_modules/meshcentral/agents folder and you will see the "meshservice-signed.exe" versions along with the unsigned versions of the binaries fro both 32 and 64 bit. You can sign the agent, replacing the "-signed" versions with your own signature and restart the server and you should be good to go.

**Comment by dinger1986** [comment]
av issue @si458 suggest closing

**Comment by si458** [comment]
this is always going to happen because bad people do bad things and do the exe gets listed as a vrius
one way around this is to code-sign with a certificate and submit to vendors saying its urs and safe
