### ISSUE TITLE
2 users trying to access the same account

### ISSUE THREAD

**Issue by Noelzu** [Ylianst/MeshCentral#5520]
**Describe the bug**
For some reason the credentinals of my colleague lead to a login attempt on my account, he is then prompted 
to input a security token, using his own 2FA token that he set up for his account doesn't work, 
but using my 2FA token leads to him accessing my account, all while using his own credentinals. My credentials and 2FA, still let me access my own account, but should he remove his own 2FA in his settings, my 2FA gets removed as well and should he setup a new one, then i need his token to login to my account. 
The eventlog of my account also displays his login attempts with an incorrect 2FA token message.
Clicking on his name in this eventlog only leads to my own General page. 
I'm using Google Authenticator while he's using Microsoft Authenticator.
Also when I checked the group tab where I would normally see all the users in my group, he isn't shown there either.
After a bit of testing we also noticed that for some reason we both share the same User Identifier and account Creation Time.

**Screenshots**
![eventlog of my account](https://github.com/Ylianst/MeshCentral/assets/149778788/1b0dd6f4-6501-4564-8b4f-ce13f6dbe279)
![userIdentifier](https://github.com/Ylianst/MeshCentral/assets/149778788/03215b67-133f-43f0-948a-56c7a5c62597)
![userIdentifier2](https://github.com/Ylianst/MeshCentral/assets/149778788/bc9c0320-37d5-4348-9bcd-9e395f8fe09b)
![userlist](https://github.com/Ylianst/MeshCentral/assets/149778788/5c92e339-8093-4418-8c56-8a446267cb60)

**Server Software :**
 - OS: Debian 12 Bookworm
 - Virtualization: vSpher ESXi Hypervisor
 - Network: WAN, Apache Reverse Proxy
 - Version: 1.1.13
 - Node: 18.13.0

**Client Device:**
 - Device: Desktop PC
 - OS: Windows 10 Pro
 - Network: Remote over WAN
 - Browser: Google Chrome (118.0.0.0) (Edge (118.0.2088.76) and Firefox (116.0) also tested with the same result)

**Remote Device:**
 - Device: Desktop PC
 - OS: Windows 10 Pro
 - Network: Remote over WAN

**Comment by si458** [comment]
**you didnt share your `config.json` so we are guessing based on ur screenshot you use LDAP/AD**

this can happen with Windows Active Directory

you should either set `ldapUserkey` or `ldapUserBinaryKey` to a unique LDAP value of the user (check with an AD explorer)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/3a208bf6-063d-438b-ab13-ee47ec088cf5)

**Comment by Noelzu** [comment]
Thank you for the fast response. 
First time we had any real issues with meshcentral, it had been working great so far.

We do indeed use LDAP/AD, if we change the ldapUserBinaryKey now from objectSid
to objectGUID, then do the other users and their setup 2FA still continue working like they do right now?

**Comment by si458** [comment]
erm... im not 100% sure? trial and error?
i would have to create a test environment to try for you, take me a few hours, slow day today

**Comment by Noelzu** [comment]
I would really appreciated it if you could test it for me, I'm sadly not that familiar with meshcentral yet,
If someone who already has experince with that sort of issue sees this post before that please let me know of your experiences.

**Comment by Noelzu** [comment]
Sorry for the request from before but we will be testing it ourselfs, still thank you for the offer.

**Comment by Noelzu** [comment]
Ok we tested setting ldapbinarykey from objectSid to objectGUID, the result was that now we have all the old accounts still existing but the through the new reference to objectGUID new once are created when you try to login with  your credentials. 
That lead to us having to set new 2FAs for everyone using meshcentral and also having to delete the old accounts using the objectSid.

But overall the change so far have worked, nobody has the same UserID or connects to the wrong account.

**Comment by si458** [comment]
Glad it worked! Sorry I only got my vm up n running late last night as was trying to fix a meshcentralinstaller bug.
The only thing u could do/try is setup the 2fa in the AD itself?
I'm not sure if this is possible? Never tried it

**Comment by Noelzu** [comment]
Thank you again very much for your efforts, i asked my superior and he said that as long as it's just basically setting up the 2FA again, it's fine for him.
