### ISSUE TITLE
Force email MFA

### ISSUE THREAD

**Issue by cbaptista** [Ylianst/MeshCentral#5523]
Hi all,
I have two questions
Is it possible to force all users to use at least email token for MFA ?

Is it possible to import existing TOTP tokens to meshcentral?
I already have a solution using smartcards with totp tokens. I have the seed of the token. Can I import them to meshcentral?
Is it possible to load them to the database?

Thanks
Carlos Baptista

**Comment by si458** [comment]
you can use `force2factor` which will let users sign in with user+pass on first login, but then when they try to do something, the web ui will prompt to say they need to setup a 2fa factor first!
you can also enable/disable which 2fa you want end users to use
![image](https://github.com/Ylianst/MeshCentral/assets/765314/9716b0e1-9d3c-4766-8dba-c3774c15180f)

i dont believe its possible to import TOTP tokens, same with the smartcards, im sorry

**Comment by cbaptista** [comment]
Tanks for the quick replay :-)

**Comment by si458** [comment]
please close if all is ok! 👍
