### ISSUE TITLE
Add device group name to search results

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#5536]
**Is your feature request related to a problem? Please describe.**
not a problem, but a nice to have. When you have lots of device groups, at times it is easier to search for the device group rather than the device itself.

**Describe the solution you'd like**
Make the device group name searchable and add it to the results

**Describe alternatives you've considered**
none so far

**Additional context**
![image](https://github.com/Ylianst/MeshCentral/assets/4949495/e9729f95-8e5e-46bd-a22b-93842dd62613)

**Comment by jrf280** [comment]
That functionality already exists, you can do it like this `g:groupName`


[https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#search-or-filter](https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#search-or-filter)

**Comment by rodrigolzd** [comment]
I guess I didnt word it right. I was more focursed on answering the form questions than explaining it properly

Make it part of the search by default without having to resort to visually hidden features. 

I get that it has this function by typing some hidden feature, but there is no way I can make it permanently active right now without the extra sintaxes.

Its just a time saving feature. Much like showing the existing tags on the tagging window.

**Comment by si458** [comment]
@rodrigolzd ahhh that makes more sense!
i have a group called `test` which isnt visbible on screen,
but if i search `test` it just returns the computers containing `test` rather than the group `test` also being listed!

**Comment by jrf280** [comment]
Working on this
