### ISSUE TITLE
Is there an API or command line that allows specific agents to execute commands

### ISSUE THREAD

**Issue by djerryz** [Ylianst/MeshCentral#5537]
Insufficient efficiency in batch operation of agents through web pages,
If there is an API that can be operated by specifying the agent name, it will greatly improve efficiency

**Comment by si458** [comment]
you can use the `meshctrl.js` command to use `RunCommand` against your devices
https://ylianst.github.io/MeshCentral/meshctrl/

**Comment by djerryz** [comment]
> you can use the `meshctrl.js` command to use `RunCommand` against your devices https://ylianst.github.io/MeshCentral/meshctrl/

@si458  for example , i need to execute 'pa -aux |grep xxx' and get the return from specify agent.
i try 'meshctrl runcommand -id xx -run  'pa -aux |grep xxx' but just return OK for me

**Comment by si458** [comment]
@djerryz yeh that doesnt exist at the moment because of the way meshctrl works,
but the is other issue open about it, so follow there for updates! #5203
