### ISSUE TITLE
TCP Syslog feature of MeshCentral requires Python in docker image

### ISSUE THREAD

**Issue by germanbravouy** [Ylianst/MeshCentral#5546]
**Describe the bug**
Hi, i encountered a bug when using meshcentral as a docker instance (deployed in k8s) at least, that is disallowing me from using the "syslogtcp" feature of MeshCentral.

**To Reproduce**
- Deploy MeshCentral in k8s as a docker instance (pod, services, etc) using the image provided here https://github.com/Ylianst/MeshCentral/tree/master/docker
- In config.json, in "settings" add the line "syslogtcp" pointing to the ip:host of the syslog server
- Deploy changes to MeshCentral so it rebuilds and deploy, and meshcentral fails saying the following:
![image](https://github.com/Ylianst/MeshCentral/assets/120838571/81b31bc0-bc1f-4dfa-9835-506d62b8b32f)
- Looking into depth, i deployed the pod without the "syslogtcp" changes and then tried to install the "modern-syslog" and "syslog" node modules manually and i can see the following errors:
![image](https://github.com/Ylianst/MeshCentral/assets/120838571/ab98448a-9b7f-42f1-b86e-12b444f07ec7)

**It seem to be an error associated to the docker instance not having python available, as it is required by node-gyp node module**

**Expected behavior**
Build correctly, and deploy meshcentral correctly.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/120838571/badd950e-43e8-4f0f-b106-b8ec9e809b75)

**Server Software (please complete the following information):**
 - OS: Alpine Linux
 - Virtualization: Docker. k8s in Amazon EKS
 - Network: WAN, reverse proxy, ssl offload
 - Version: 1.1.16
 - Node: 18.18.2

**Your config.json file**
```
{
  ...
  "settings": {
    ...
    "syslog": true,
    "syslogtcp": "service:9000",
    ...
  },
  ...
}
```

**Comment by si458** [comment]
Hi,

yes i am aware of the bug about not being able to install NPM packages correctly (first pic)
this is due to the image being built and created as ROOT and then when you run the container you are running as USER, so USER doesnt have permission to install the npm packages! (a fix is to remove the USER option in your docker-compose/k8s setup and also plz look at #5545 for an update on that issue)
 
as for 'syslogtcp' i think we need to include python into the docker image (which should fix this i think?)
but the size of the container is getting huge at the moment 600MB!!!
so i might look at making seperate docker images, so one includes mongodb, one includes mysql, one includes python (for syslog), etc
would this be ok for you?

**Comment by germanbravouy** [comment]
@si458 yes it would be amazing. For extra information, im using:
- Docker image
- Deployed in Amazon EKS
- Postgres in Amazon RDS (so im not using postgres locally as a pod, im just using postgres services of Amazon RDS)
- Also my instance is connected to Keycloak using SAML
- And the last extra feature is the syslogtcp, which i cant use for the moment because of the user and python reasons

**Comment by germanbravouy** [comment]
After making some changes i could make meshcentral run with syslogtcp enabled.

I had to:
- Modify docker image to execute the following:
`apk --no-cache add python3 make gcc g++`
- Then in config.json i enabled syslog and syslogtcp

**Comment by gogglespisano** [comment]
The NPM issue doesn't seem to be only related to the USER not being ROOT.  I noted in the other bug that it is failing again even with ROOT since 1.1.15.

**Comment by si458** [comment]
> The NPM issue doesn't seem to be only related to the USER not being ROOT. I noted in the other bug that it is failing again even with ROOT since 1.1.15.

you say ur in post `I removed the user: "1003" statement and npm installed the modules and loaded meshcentral.`
but then say it worked once and never again,
im more likely to believe you might of left in the 'user' option when you tried to recreate the container

**Comment by germanbravouy** [comment]
I had deployed meshcentral in EKS with root, never used the USER statement in the docker definition or k8s YAML. The problem was only related to not having python installed in the pod as node-gyp required it. It also required g++ and make and all worked. The only problem im having right now is that the logs sent with "syslogtcp" are shortened in information (they dont inform computers or users involved in events)

For that reason im asking this in this dicussions and issues:
- https://github.com/Ylianst/MeshCentral/discussions/5557
- https://github.com/Ylianst/MeshCentral/issues/2665

**Comment by gogglespisano** [comment]
> > The NPM issue doesn't seem to be only related to the USER not being ROOT. I noted in the other bug that it is failing again even with ROOT since 1.1.15.
> 
> you say ur in post `I removed the user: "1003" statement and npm installed the modules and loaded meshcentral.` but then say it worked once and never again, im more likely to believe you might of left in the 'user' option when you tried to recreate the container

This is what I have in the file that's not loading 1.1.15.and 1.1.16.  It says loading modules... for about 2 minutes and then fails.  Only chaing the image to 1.1.14 it loads in a couple of seconds.

    # user: "1003"

**Comment by germanbravouy** [comment]
Hi @Ylianst @si458 i have a question, is it possible to configure meshcentral so it sends syslog messages to a TCP port (for example using the settings.syslogtcp option) but in JSON format? I only achieved to send only the msg part of the events which is not informational. 

Thanks!

**Comment by si458** [comment]
I'm not 100% sure I'm sorry
I don't use syslog and never have, I'll have to look into the code for you! So bar with me...

**Comment by germanbravouy** [comment]
Thank you @si458. I think this feature is a must have because in environments like EKS, it is good to have the ability to send the event logs to a centralized and external system, and because the syslogtcp by default sends only the "msg" part, it doesnt give any information about the user/host involved in the event, it would be amazing that syslogtcp also sends logs in json format for example

**Comment by PrplHaz4** [comment]
> Thank you @si458. I think this feature is a must have because in environments like EKS, it is good to have the ability to send the event logs to a centralized and external system, and because the syslogtcp by default sends only the "msg" part, it doesnt give any information about the user/host involved in the event, it would be amazing that syslogtcp also sends logs in json format for example

Per my understanding, the syslog format is the de-facto standard for collecting and/or forwarding logs (https://datatracker.ietf.org/doc/html/rfc5424).  Your syslog server (rsyslog, logstash, filebeat, graylog...etc) would ingest it as given then transform and forward to json where you need it.  I run filebeat in a container and it handles shipping syslogs to elastic stack where it is parsed and transformed.

That being said, I'm not sure why the log wouldn't have the host, facility and pid information in it - maybe they need to be set explicitly in the open call.

References:
- https://github.com/Ylianst/MeshCentral/blob/0a01c5d4e4ce871c660ab19bcb0afe8d9d3e5ee4/meshcentral.js#L2200
- https://github.com/strongloop/modern-syslog#openident-option-facility
- https://man7.org/linux/man-pages/man3/syslog.3.html#DESCRIPTION

**Comment by germanbravouy** [comment]
Im shipping logs to elasticsearch using a syslog input from filebeat. It works perfectly, but the logs sent by meshcentral lack of information (the only information sent is the "msg" field from the "events" table, which doesnt show host/user associated to generated event).
I mentioned JSON format because in the documentation of meshcentral it informs that you can send the syslog messages as JSON format (the same format used in the events table, and in this format the event has all the information), but it is only sent to the local syslog messages, not to the TCP socket.

**Comment by germanbravouy** [comment]
Hi @si458 i've been looking through the code of the syslogtcp and syslogjson part but i think the syslogtcp is only meant to sent "msg" part of the events, correct me if im wrong.

**Comment by germanbravouy** [comment]
Hi any update on this please?

**Comment by germanbravouy** [comment]
Hi @si458 could you review the code? Is it possible to implement the auditing feature?
Thanks

**Comment by si458** [comment]
Hi @germanbravouy, im not 100% sure as again ive never used the syslog side of things, so i just dont know?
it will take me some time to understand what it does,
whats the remote syslog software/device you send the logs too?
is it just the built in syslog-ng on localhost:514?
the npm package we use to send information is [syslog ](https://www.npmjs.com/package/syslog)

**Comment by germanbravouy** [comment]
To receive and process the syslog messages i'm sending them using the "syslogtcp" feature of meshcentral where i indicate an ip address and a port number. This IP Address and port number corresponds to an UDP socket of an instance of filebeat, a lightweight message processor that supports multiple inputs, and one of them is the syslog input which can receive a message using syslog protocol (through TCP or UDP) and then dissect this message in a legible JSON message which can be indexed in a search motor like Elasticsearch.

The problem here is, if you look for the events table in the SQL database of meshcentral you can see all events as JSON data, in which one of the key values is the "msg". Well, the syslogtcp feature of Meshcentral is taking this "msg" key-value and is sending only this part of the JSON object of the events table, but if you look there exists more information related to an event like the related to users, computers, ip addresses, etc., involved in those events.

**Comment by germanbravouy** [comment]
To add i inspected the "events" table of the postgres database of MeshCentral and one of those events in the column "doc" where action = "relaylog" describes a events similar to the following:

`{"etype":"relay","action":"relaylog","domain":"","userid":"user//~saml:REDACTED","username":"REDACTED","msgid":11,"msgArgs":["tpnoi3nihv9","192.168.1.1","192.168.1.1",29],"msg":"Ended desktop session \"tpnoi3nihv9\" from 192.168.1.1 to 192.168.1.1, 29 second(s)","protocol":2,"nodeid":"node//id_if_node_redacted","bytesin":135632,"bytesout":133815,"time":"2023-12-27T20:11:00.519Z","ids":["*","user//~saml:REDACTED","node//id_of_node_redacted","mesh//id_of_mesh_redacted"]}`

In the example i obscured some parts with REDACTED that corresponds to the user of mesh involved, ip addresses, node and mesh ids.

**Comment by germanbravouy** [comment]
The thing is the "syslogtcp" is only sending the "msg" key of the whole object in which says:

`Ended desktop session \"tpnoi3nihv9\" from 192.168.1.1 to 192.168.1.1, 29 second(s)`

So for auditing purposes it is very poor

**Comment by si458** [comment]
@germanbravouy ahhh right i understand you now!

so you would like the syslogtcp to send the whole json data thats listed in the events row? and not just the msg being sent !?

i will look at adding an option into config.json so when its set as true,
it will send the WHOLE event over syslogtcp as a json string rather then just the msg part being string!
(this will prevent anybody else in the community expecting it to be string and suddenly its json after they do an update of meshcentral!)

**Comment by germanbravouy** [comment]
Yes @si458 thanks!

And if possible could we translate the "nodeids" and "ids" of the JSON part to the actual computer names in an aditional key-value please?

**Comment by si458** [comment]
ok ive added python3 to docker image for you, just be aware the image increased by 250MB !?
so im going to close this issue now as just clearing up issues thats all
please can you also open a new issue about the changing of json msg, just explain in the enchancement like you have here
link the issue too this one too if you want

**Comment by germanbravouy** [comment]
Hi @si458 there is an already open issue for this problem

https://github.com/Ylianst/MeshCentral/issues/2665

Thanks

**Comment by DaanSelen** [comment]
Looking into replacing the library, to reduce the size of the container by half!
