### ISSUE TITLE
Meshcentral steals video output

### ISSUE THREAD

**Issue by exander77** [Ylianst/MeshCentral#5553]
I have installed xorg, when I startx and .xinitrc loads  chromium-browser, I am now having blank black screen on HDMI output, but I see normal screen when I use meshcentral.

The configuration is trivial enough:
`/etc/systemd/system/getty@tty1.service.d/override.conf` (to autologin tty1):
```
[Service]
Type=simple
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I 38400 linux
```

End of `~/.profile` (to startx on tty1):
```
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  . startx
  logout
fi
```

`~/.xinitrc` (to start chromium):
```
chromium-browser ...
```

**Comment by NiceGuyIT** [comment]
@exander77 You removed the issue template asking for vital information. Nobody can help you if you don't provide it.

@si458 Please close due to insufficient information.

**Comment by si458** [comment]
please follow the bug template as indeed it has vital info we need to help you!
closing as missing info,
please open a fresh one with the information thats required
