### ISSUE TITLE
Add Windows Security Center Status for windows server

### ISSUE THREAD

**Issue by nries-venio** [Ylianst/MeshCentral#5555]
In the current landscape of cybersecurity, staying informed about the status of key security features like antivirus and firewall is critical for effectively managing and securing computer systems. The existing 'win-securitycenter.js' in the MeshCMD AMT system seems to provide valuable insights into antivirus and firewall status, but similar functionality for monitoring the windows security status is lacking in non-AMT meshagents.

This request is to extend the capabilities of MeshAgent to include the monitoring of Antivirus and Firewall status, paralleling the existing functionality for status monitoring in MeshCMD AMT. Specifically, the feature should allow MeshAgent to display the status of the Windows Security Center under the "General" tab, beneath the "Operating System" status. Furthermore, this feature should enable MeshAgent to send notifications to the user or administrator if the Firewall or Antivirus status falls into a "RED Letter" or critical state, indicating a potential security issue or disabled state.

This enhancement would significantly improve the utility of MeshAgent for administrators and users by:

- Providing a quick and accessible overview of essential security features (Antivirus and Firewall) directly from the MeshAgent interface.
- Enabling proactive management of security risks by alerting users or administrators immediately when a potential security issue is detected, allowing for swift action.
- Reducing the need for manual checks and increasing the efficiency of monitoring large numbers of systems.

## Use Case Scenarios:

- An IT administrator managing a fleet of computers can immediately identify and respond to any machine with a disabled or malfunctioning Firewall, ensuring continuous protection against network-based threats.
- Users with less technical expertise can easily verify the health of their system's key security features and receive alerts if action is needed, simplifying security management for non-experts.

## Optional Settings:

- A setting in the MeshAgent configuration to toggle the frequency of these notifications (e.g., immediate, hourly, daily) to accommodate different monitoring needs.
- Option to customize the notification method (e.g., email, SMS, in-app notification) for greater flexibility in how alerts are received.

## Technical Considerations:

- Ensuring compatibility with various Windows versions, given the diverse environments in which MeshAgent is deployed.
- Considering the implementation feasibility on different Windows editions, especially those that may not have certain security features like Windows Security Center.

**Comment by si458** [comment]
This is more of a remote management feature request which meshcentral is not!!!

Meshcentral is a remote support application 

Please check out something like tactiaclrmm

Also note meshcentral already shows the ok or bad status of windows security center stuff in the Web ui, in each device page or now in columns

**Comment by nries-venio** [comment]
I don't think I understand.

According to this https://github.com/Ylianst/MeshCentral/issues/2191

The feature exists in MeshCMD AMT. So why is this not planned for MeshAgent?

I do not see the windows security center in the web UI. Is there a setting in the config.json I need to enable?

**Comment by nries-venio** [comment]
https://www.meshcommander.com/meshcentral2

The website needs to be changed if MeshCentral is no longer an RMM... 

> Connect to your home or office devices from anywhere in the world using MeshCentral, the open source, remote monitoring and management server.

![image](https://github.com/Ylianst/MeshCentral/assets/140186885/0c047f4b-9381-4a8c-8865-660d4824b9fe)

**Comment by nries-venio** [comment]
It's not showing in mine:

![image](https://github.com/Ylianst/MeshCentral/assets/140186885/111b00b7-13cc-4872-8984-256a0e9cc815)

**Comment by si458** [comment]
thats because you are running Windows Server,
Windows server doesnt support the Windows Security Center - https://github.com/Ylianst/MeshCentral/issues/3263#issuecomment-963483829
only Windows 7,8,8.1,10,11 Sadly

**Comment by nries-venio** [comment]
Ah. Stupid Microsoft. Thanks for the guidance!

**Comment by si458** [comment]
> Ah. Stupid Microsoft. Thanks for the guidance!

no worries! sorry if i sounded snotty, i try to be polite!
if you do find a way of getting your antivirus statuses on windows server via commandline, do share!
we can use cmd, powershell, wmi, registry to get information and then parse it!

**Comment by nries-venio** [comment]
This PowerShell command gets a very similar result:
`Get-MpComputerStatus | Select-Object AMServiceEnabled, AntispywareEnabled, AntivirusEnabled, NISEnabled`

![image](https://github.com/Ylianst/MeshCentral/assets/140186885/2f9c5cc5-862a-4c0b-97a9-b2c00810e66b)
```
Run commands (0): Get-MpComputerStatus | Select-Object AMServiceEnabled, AntispywareEnabled, AntivirusEnabled, NISEnabled

AMServiceEnabled AntispywareEnabled AntivirusEnabled NISEnabled
---------------- ------------------ ---------------- ----------
            True               True             True       True


Run commands completed.
```

**Comment by nries-venio** [comment]
And for firewall:
Get-NetFirewallProfile | Select-Object Name, Enabled
![image](https://github.com/Ylianst/MeshCentral/assets/140186885/edfbfd0d-4acf-4a59-9c98-2f285a876f43)

**Comment by si458** [comment]
Get-MpComputerStatus is just Windows Defender if you have it enabled on computers,
like for example my laptop, i have norton installed so defender is turned off, and the communit just returns FALSE for them all
ALSO QUOTE FROM WEBSITE I FOUND:
`It seems that the Get-MpComputerStatus and Get-MpThreatDetection cmdlets, which are part of the Defender module for PowerShell`

**Comment by nries-venio** [comment]
Hmmm. I see. At least the firewall one will work.

Can we do a failover? So if nothing is returned from Windows Security Center, default to checking for windows defender? Then maybe if both the security center AND windows defender comes back false, return 'unknown'? Just spit-balling ideas here!

**Comment by si458** [comment]
yes sure, i will put it on my to-do for you!
the is a bug at mo with windows server and virtual machines, so it might not work straight away

**Comment by si458** [comment]
how does this look?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b5b40b0a-c3be-4461-862c-a80378d06cad)
it will show a section saying Windows Defender IF the machine DOESNT have wsc (so Windows Server) AND the meshcore was able to query the `Get-MpComputerStatus` for details

**Comment by nries-venio** [comment]
Sorry about the delayed response. This looks great!
