### ISSUE TITLE
Unable to connect Meshcentral Agent for android with last apk. Stay on Authenticating

### ISSUE THREAD

**Issue by superleon93** [Ylianst/MeshCentral#5556]
Hi,

Last version of serveur, Apk installed from google play store ...

I have a phone with an old version of the app and it works...

Don't know if it's enought for you :)

**Comment by si458** [comment]
Hi,
yes we are aware of this, sadly when google removed the app (for some unknown reason) #5404
@Ylianst had to rebuild it with the latest SDKs from google, which they was happy with,
but then suddenly broke support connecting to meshcentral!
hes in the process of trying to fix it but taking longer cuz of work etc...
the way around it for the moment is NOT install the google playstore,
but use the APK thats included with meshcentral from the web ui instead
sorry about this!

**Comment by jrf280** [comment]
Hi,

I just made a pull request to fix this.

https://github.com/Ylianst/MeshCentralAndroidAgent/pull/21

**Comment by Ylianst** [comment]
Wow. Thanks to @jrf280. I submitted the new Android application to the Google Play store a few hours ago. Let me know if it works.

**Comment by superleon93** [comment]
WOW !!! It s working !!! Better support than ever ! Thanks Guys for your work !

**Comment by dinger1986** [comment]
If it's working can you close the issues please

**Comment by si458** [comment]
released in UK now here 1.0..18 on play store, all back up and working again! thank you @jrf280
