### ISSUE TITLE
Display Current Windows RDP port

### ISSUE THREAD

**Issue by smartekIT** [Ylianst/MeshCentral#5561]
How about include info about the current set Windows RDP port, so we could use as an alternative port when starting RDP connection?
Currently I get that by passing the following PowerShell command:
<pre>get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\'-name portnumber</pre>

**Comment by smartekIT** [comment]
Also here is a good article about this, which also include commands to change the default port number and add firewall rules for it as well.
[https://www.prajwaldesai.com/change-rdp-port-sccm-powershell-registry/](url)

**Comment by si458** [comment]
where would you display the current port? in deatils tab somewhere? any mock ups?
i could add it into the `sysinfo` command in console tab like i did with the bitlocker key?
also the alternative port is saved server side, so once you set it with right click, it saved, so you dont need to keep changing it

**Comment by si458** [comment]
sorry missed this request, totally slipped my mind/notifications!
just a random throught, what about a seperate console command?
something like 
```
> rdpport
Current RDP Port: 3389
> rdpport 12345
Set RDP Port to 12345 Was Successful, Don't Forget To Restart Your Computer
> rdpport 123456
Set RDP Port to 123456 Was Unsuccessful
```

**Comment by smartekIT** [comment]
Thanks. That good enough for me to remotely set the RDP port. but it's still good idea to show the current RDP Port as a text only under the desktop tab on the top bar to the left of the actions and settings buttons or anywhere in this tab you can fit it. (text only info will do for showing current).

**Comment by si458** [comment]
what about changing the `RDP Connect` button to say `RDP Connect (1234)` if you have set an alternative port?
best of both worlds!
you can see what the port is as YOU have set it by right click,
but also the `rdpport` command will help tell you what the port is!

as this request is a very advanced feature really, i dont really know anyone who changes the RDP ports?

**Comment by smartekIT** [comment]
That's brilliant in addition to the rdpport command for remote set

**Comment by smartekIT** [comment]
by the way after thinking of what I said about creating an extra section under details tab and call it (more info, or extra info or other info) it made me think we could use that section for a brilliant feature like make the section sort of a pre-defined users registry queries which could be configured in the config.json file. like:
<pre>
"title": "reg query command"
example:
"simon": "get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\'-name portnumber"
"simon2": "get-ItemProperty -Path 'HKLM:\System\...etc"
</pre>
which will show the section in the UI like:
simon: 3389
simon2: cool

**Comment by si458** [comment]
yeh seperate request please

**Comment by smartekIT** [comment]
will do. thanks

**Comment by si458** [comment]
done console, just adding the web ui to show the port IF you have entered an alternative port via the right click option!
the showing of the port WONT check/change the remote device, only show what you have set in meshcentral
```
> rdpport
Proper usage: rdpport [get|default|PORTNUMBER]
> rdpport get
Current RDP Port Set To: 3389
> rdpport 12345
RDP Port Set To 12345, Please Dont Forget To Restart Your Computer To Fully Apply
> rdpport 123456
RDP Port Must Be More Than 0 And Less Than 65535
> rdpport default
RDP Port Set To 3389, Please Dont Forget To Restart Your Computer To Fully Apply
```

**Comment by silversword411** [comment]
A cautionary note: Changing the RDP has nothing to do with security.

Here's the 4.6 million servers running RDP publicly on any port today: https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=services.rdp%3D+*

**Comment by silversword411** [comment]
Of which 905K aren't running on port 3389

https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=INCLUDE&q=services%3A+%28service_name%3A+RDP+and+not+port%3A+3389%29&ref=censysgpt

**Comment by si458** [comment]
@smartekIT is the pic above ok? wasnt a bug was my code haha
or do you think maybe `RDP Connect :12345` ?

**Comment by smartekIT** [comment]
@si458 thanks for doing this. the pic looks ok to me.
