### ISSUE TITLE
Can`t send messege to Microsoft Windows 11 Pro - 22H2/22621

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshCentral#5562]
When sending messege to client on windows 11 messege don`t show on client - its only blank window.

**Comment by si458** [comment]
**PLEASE FOLLOW THE BUG REPORT TEMPLATE IN FUTURE OTHERWISE YOUR ISSUE WILL BE CLOSED!**

what version are you using?
whats the agent version?
whet node js are you using?

im not having issues here, when i select my laptop, then click the 'message' button
![image](https://github.com/Ylianst/MeshCentral/assets/765314/e5835e4b-1383-4229-9f59-dbf9c5b76186)

**Comment by NiceGuyIT** [comment]
@wireks Is this the same as Ylianst/MeshAgent#154 that you commented on?

**Comment by wireks** [comment]
i make the same as you now... and look:



![20231117_080025720_iOS](https://github.com/Ylianst/MeshCentral/assets/58087362/83501dda-e49d-4b5b-935d-db498c232ad3)

**Comment by wireks** [comment]
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
  "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
  "WANonly": true,
  "cert": "my.adress.com",
  "_Port": 443,
  "_RedirPort": 80,
  "_AllowLoginToken": true,
  "_AllowFraming": true,
  "_WebRTC": false,
  "_ClickOnce": false,
  "_UserAllowedIP" : "127.0.0.1,::1,192.168.0.100"
 },


"letsencrypt": {
 "email": "email@email.pl",
 "names": "my.adress.com",
 "rsaKeySize": 3072,
 "production": true
  },

  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
}
}

**Comment by si458** [comment]
as a work around, you can use the batch 'device notification' and then select 'alert box'
this will send an old style XP alert box prompt which might be helpful!
this will be available in the next release
