### ISSUE TITLE
Slack Notification Support

### ISSUE THREAD

**Issue by demiurge28** [Ylianst/MeshCentral#5564]
Add slack messaging support to send notification of connected / disconnected devices with optional custom text format for notifications.

**Comment by si458** [comment]
im just playing around with the webhooks,
slack lets you send the webhooks to a channel or directly to you
the problem you have is meshcentral setups up the notifictation as a 2fa
so if you set the webhook to a channel and its public, everyone would see your 2fa code to login!
would this be ok?

**Comment by demiurge28** [comment]
One group will only be using this, so its intended purpose is to be a private channel with select people in it. 

"the problem you have is meshcentral setups up the messaging as a 2fa by default
so if you set the webhook to a channel and its public, everyone would see your 2fa code to login!"

Can you elaborate more on what you mean?

Thank you for the fast reply.

**Comment by si458** [comment]
when you setup a 'messaging method' to get alerts for when devices are down/up/etc...
meshcentral also sets up this method as a 2 factor authentication method!
so when the user nexts logs-in, it will send a message with your 2 factor code to the channel you configured for the webhook
and if the channel is public, then everyone in that channel would see you tried to login but was asked for your 2nd factor code!
VERY BAD!
you would need to turn off use of messaging for 2FA in config.json like below
```
"passwordRequirements": {
    "msg2factor": false
}
```
is this going to be ok?

**Comment by demiurge28** [comment]
It's a requirement 2FA is enabled. I agree very bad. Does anything else get affected by msg2f false beside not sending a code to a slack channel?
