### ISSUE TITLE
Manual Event Separation Button

### ISSUE THREAD

**Issue by Henrique-Batista** [Ylianst/MeshCentral#5573]
**Is your feature request related to a problem? Please describe.**
Hello, thank you very much indeed for this project. I was taking a look at the old Issues, and I saw one that could help (https://github.com/Ylianst/MeshCentral/issues/5321#issuecomment-1793761854). I believe that in the Issue it is requested to separate the manual logs and the automatic logs for each view, which helps when checking situations that occurred and were added to the log manually for registration.

**Describe the solution you'd like**
I've changed the default view of Handlebars to add a new button for the My Events frontend, which when clicked toggles the display of events between all and manual, based on the type of event.
![](https://user-images.githubusercontent.com/55212193/280535277-c91d0d53-07f5-4d66-870e-95d9c1117642.png)
![](https://user-images.githubusercontent.com/55212193/280535312-b0418d35-3311-48e8-b151-7a8d7f37738f.png)
I'll attach my modified default.handlebars to show the changes I made as an example.
[default.zip](https://github.com/Ylianst/MeshCentral/files/13433304/default.zip)
**Describe alternatives you've considered**
I believe it would be a good feature because it would open the door to a better registration of manual demands directly in Meshcentral, which may even help in future integrations that may exist with ticketing applications, such as GLPI.

**Additional context**
I don't have much knowledge about development, but I believe that with help you can improve this code, as it would be a good feature for those who support remotely.

**Comment by Henrique-Batista** [comment]
My Meshcentral version is 1.1.13*

**Comment by si458** [comment]
im just looking into this now for you,
what do you think about this instead? 
<img width="339" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/765314/96c9b9dd-5fc3-4f1c-9ade-3092912bda5a">
im going to implement the filtering into the `events` websocket,
that way it can be extended to 3rd party apps or meshctrl.js!

**Comment by si458** [comment]
PR DONE! adds a filter to`My Events`, `Node Events`, `User Events`
❤️ dont forget to donate or have a look at my amazon wish list! https://www.si458.co.uk/2024/01/05/donation/
