### ISSUE TITLE
When configuring MeshCentral to use a self-hosted ntfy server for notifications, the verification code is not being sent to approve the ntfy client.

### ISSUE THREAD

**Issue by nries-venio** [Ylianst/MeshCentral#5574]
**Steps to reprosduce:**

1. Set up a self-hosted ntfy server (e.g. ntfy.example.com)
2. Configure MeshCentral messaging to use the self-hosted ntfy server:**

```
"messaging": {
  "ntfy": true,
  "ntfy": {
    "host": "ntfy.example.com",
    "userurl": "https://ntfy.example.com/userhelp",
    "authorization": "Bearer <token>",
    "description": "Custom ntfy server"
  }
}
```
3. Attempt to send a test notification in MeshCentral

**Expected Behavior**
A verification code should be sent to the ntfy client to approve the MeshCentral server. Once approved, notifications should work properly.

**Actual Behavior**
The verification code is not sent from the MeshCentral server to the self-hosted ntfy server. Notifications do not work with the self-hosted ntfy server.

**Workaround**
Using the public ntfy.sh host works properly.

**Additional Details**
MeshCentral version: v1.1.16
ntfy server version: v2.8.0

Notifications to and from the self-hosted ntfy server works properly. Including SMTP to and from the self-hosted ntfy server.

**NTFY Server Software (please complete the following information):**
 - OS: AMZN2
 - Virtualization: Docker
 - Network: LAN/WAN, reverse proxy.
 - Version: v2.8.0

**MeshCentral Server Software (please complete the following information):**
 - OS: AMZN2
 - Virtualization: none
 - Network: LAN/WAN
 - Version: 1.1.16
 

** redacted snippet of messaging section from config.json file**
```
"messaging": {

"ntfy": true,

"ntfy": {

"host": "ntfy.<domain>",

"userurl": "https://ntfy./<domain>/userhelp",

"authorization": "Bearer tk_<redacted>",

"description": "Please contact Administrator for access to ntfy.<domain>"

}

},
```

**Comment by si458** [comment]
You have the same issue as in discussions 
Please check there for the answer https://github.com/Ylianst/MeshCentral/discussions/5571#discussioncomment-7629822

**Comment by Raito00** [comment]
I`m also trying setup my custom NTFY server.
And the same problem not receiving messages.

```
"messaging": {
"ntfy": {
"host": "ntfy.<domain>",
"userurl": "https://ntfy./<domain>/userhelp",
"authorization": "Bearer tk_<redacted>",
"description": "custom server ntfy.<domain>"
}
},
``` 

So my custom server is configured only with Access tokens can send messages. Need use "Bearer tk_<redacted>"

Test working command:
```
curl -X POST "https://ntfy.<domain>/userhelp" \
     -H "Authorization: Bearer tk_<redacted>" \
     -d "Message!" \
     -H "Title: Title message" \
     -H "Tags: Extra TAGS!"
``` 
Can be problem Bearer authentication with token?
