### ISSUE TITLE
Meshcentral connected with black screen

### ISSUE THREAD

**Issue by astronyu** [Ylianst/MeshCentral#5575]
**Describe the bug**
Meshcentral now shows as connected but not showing the desktop instead only black screen. I can use the shortcut from desktop/mobile to press Win key etc and remote pc does exactly that and seems everything else works but without the actual screen I can't do much "remoting".

I've tried installing MC server on Synology NAS with a different subdomain and this gives the same problem.

The server is behind Cloudflare tunnel and has been working fine since I first installed in August 2023 until couple weeks ago. Nothing was changed on the config, it just suddenly giving this issue.

**To Reproduce**
1. Go to 'Device'
2. Click on 'Any listed device'
3. It will show as connected
4. Desktop shown as black screen

**Expected behavior**
Expected to see the remote desktop after being connected.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/3217740/c1b342f6-3920-4cc6-81ec-675633e19762)
![image](https://github.com/Ylianst/MeshCentral/assets/3217740/c1cbce43-9d4d-4d8c-9dd0-bafaca1f59b5)

**Server Software (please complete the following information):**
 - OS: Windows
 - Virtualization: Docker
 - Network: LAN+WAN, reverse proxy, cloudflare, ssl offload
 - Version: latest

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows
 - Network: Tried both WAN and LAN
 - Browser: Brave, Google Chrome

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Microsoft Windows 10 Pro - 22H2/19045.
 - Network: Tried both WAN and LAN
 - Current Core Version (if known): Current Core: Dec 9 2022, 4212221034

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "my.server.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "mysecrestpass",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 90,
    "BrowserPong": 120,
    "TLSOffload": true,
	"TLSOffload": "127.0.0.1,192.168.8.2",
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": true,
    "trustedproxy": "Cloudflare"
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": true,
      "NewAccounts": false,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "certUrl": "https://my.server.com"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@domain.com",
    "_names": "my.server.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
cloudflare doesnt work with PROXY DNS OR TUNNELS unless you use NO PROXY DNS MODE sorry about this
(not our fault, we changed nothing, cloudflare broke something)
please refer to https://github.com/Ylianst/MeshCentral/issues/5302
