### ISSUE TITLE
Edit Notes

### ISSUE THREAD

**Issue by rmicha9682** [Ylianst/MeshCentral#558]
Hello,

I have an accounts created and assigned to a group on MC with partial rights.  It has the edit notes permission, but it doesn't seem to allow adding notes or deleting existing notes.  I believe I'm doing everything correctly but they will not stay or delete.

I'm able to add notes and delete when using a full admin account.

**Comment by Ylianst** [comment]
Let me check this now.

**Comment by Ylianst** [comment]
I can't make this happen. You will have to give me the exact steps to make this happen (exact permissions, etc).

**Comment by rmicha9682** [comment]
This is how I am setup.  

I am logging in with the account with Full Administrator rights.  I am going to a device and adding a note to it.  The note saves properly when I press OK.

Then if I log out, and log back on using an account with partial rights: Manage Device Group Computers, Remote Control, Edit Device Notes ...  It can see the notes left from the account with full admin rights, but I cannot add new notes or delete the existing notes.

I updated this morning to the latest revision with the same issue.  Hope that helps.

**Comment by Ylianst** [comment]
Can you give me the exact server and device group permissions of the non-admin account. Again, exact permission for both the server and the device group. Thanks.

**Comment by rmicha9682** [comment]
Hi,

The group itself is setup like:

Name	Test Company #1 
Description	Testing Company	 
Type		Managed using a software agent
Features	Hostname Sync 
User Consent	Always Prompt 
Notifications	None 
Intel® AMT	No Policy

----

It has two users assigned to it.  One that is a full administrator, and one with partial rights.

The partial rights user has the following permissions:

1. Manage Device Group Computers
2. Remote Contral
3. Edit Device Notes

I'm not sure what you mean by Server permissions.  It is running on Ubuntu 18.04 LTS on Vultr.  I'm running as a non-root account.

**Comment by rmicha9682** [comment]
This appears to be just a permissions issue.  I tweaked some of the permissions and now I'm able to edit and delete notes.

**Comment by Ylianst** [comment]
Ha! Thank you for the details. Yes, that was a bug. Just published MeshCentral v0.4.2-k with a fix for this. Let me know if that works.

**Comment by rmicha9682** [comment]
Yes, when I set the permissions back to the previous way the edit notes permission works correctly!

Thanks

**Comment by Ylianst** [comment]
Thanks. I will close this one as I am pretty sure it's fixed. Please re-open if needed.
