### ISSUE TITLE
Wake on Lan Issue with tailscale

### ISSUE THREAD

**Issue by thinkbig1979** [Ylianst/MeshCentral#5581]
I'm having issues with WOL.

My server is in WAN mode and I have 2 clients on a local LAN. When I select the Wake-Up functinon on the offline node, and go to the console of the live node, I see the following:
```bash
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'trim' of [object Function]) in method 'handleServerCommand()'
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
``` 

Working from the agent console on the live node results in the same error:
![image](https://github.com/Ylianst/MeshCentral/assets/18327273/683d4bfb-5d8f-47d5-909a-4d16e8e058e5)

My server is on version `1.1.16`, and I've tested sending WOL packets from the live node terminal to the offline node manually using `etherwake`, which does indeed wake the offline PC up. Both are Linux machines.

**Comment by si458** [comment]
Are both devices in the same network?
As wake on lan will only work if both devices are in the same group and on the same network 
Also one device needs to be online, so the meshcentral can send th wake on lan command to the online device to then send the wol packet to the offline device
Also what is the remote device as the device might not support wol

**Comment by thinkbig1979** [comment]
Hi @si458 

To answer your questions: 
Yes, they are on the same LAN and (IPv4) subnet.
The details tab shows the correct info.
As I mentioned, I can manually send WOL packets from the one to the other, and that does the trick, so the device in question definitely supports WOL. However, trying to wake it from from Meshcentral does not work for some reason.


Hope that helps.

**Comment by si458** [comment]
Stupid question again sorry,
When you run the wakeonlan command in the console tab on the computer that's online/alive 
Whats the command u use? Is it simply `wakeonlan MACADDRESSWITHOUTCOLONS` ?

**Comment by thinkbig1979** [comment]
> Stupid question again sorry, When you run the wakeonlan command in the console tab on the computer that's online/alive Whats the command u use? Is it simply `wakeonlan MACADDRESSWITHOUTCOLONS` ?

Correct. I get the following response:

```bash
> wakeonlan B42E9987DF70
Command returned an exception error: TypeError: undefined not callable (property 'trim' of [object Function])
uncaughtException1: Error: timers.onElapsed() callback handler on 'sendWakeOnLanEx_interval()'  => TypeError: undefined not callable (property 'send' of [object Function])
```

**Comment by si458** [comment]
is the computer thats online you are using to send the wakeonlan command a linux machine?
whats the OS?
does it list interfaces in the Details tab?

**Comment by thinkbig1979** [comment]
Both devices on the LAN are on Linux... Debian 11 to be precise. 
All details of the machine I'm trying to wake up are shown correctly in the Details tab. 
The online device has two interfaces only: eth0 and a Tailscale interface, both interfaces have an IPv4 and an IPv6 address.

**Comment by si458** [comment]
can you share a screenshot of the details tab please? (hide details if needs be)
i think it might be because the interfaces have IPv6 addresses, even tho ur router has it disabled
but just wanna compare, as i still cant replicate this issue, which is weird?

**Comment by thinkbig1979** [comment]
Sure :-)
Here is the online device:
![image](https://github.com/Ylianst/MeshCentral/assets/18327273/8114f92a-3bec-46ae-a823-8b064cde36c9)


And here is the offline device:
![image](https://github.com/Ylianst/MeshCentral/assets/18327273/ad2f1b00-c38d-4bab-bee1-b5dba2e4dd1c)

**Comment by si458** [comment]
oh raspberry pi !!!!??? this might be the issue! let me check...

**Comment by thinkbig1979** [comment]
Yes, it's an old RPi 2 Model B (armv7l)

**Comment by si458** [comment]
ok, i think the issue is the tailscale interface using a special carrier grade private subnet/ip range?
as ive created a dummy interface on my pi and it works
![image](https://github.com/Ylianst/MeshCentral/assets/765314/fdd9fc2d-4a38-401d-936e-b231aa771ff7)
```
> wakeonlan 180373XXXXXX
Sending wake-on-lan on 2 interface(s).
```

**Comment by si458** [comment]
> Interesting. Uninstalled Tailscale and rebooted the Pi. This did the trick. WOL from MeshCentral worked, and no errors. Then re-installed Tailscale and rebooted the Pi again. After reboot checked to see if Tailscale interface was present and active, and then tried WOL from Meshcentral again, and this time it just worked. Puzzling.

thats weird indeed? tailscale might be doing something weird with the interfaces?
are they the same ipv4 and ipv6 addresses after you activated it and send the WOL from the console tab?

**Comment by thinkbig1979** [comment]
The Tailscale interface has the same IPv4 address as before.
The first IPv6 address is the same, the second one is different.
![image](https://github.com/Ylianst/MeshCentral/assets/18327273/4319aa23-1b5a-4e72-b5e4-177da042eda1)

**Comment by si458** [comment]
very weird indeed? im going to close as its resolved/fixed, but keep an eye on it, if happens again, report back plz!

**Comment by thinkbig1979** [comment]
> very weird indeed? im going to close as its resolved/fixed, but keep an eye on it, if happens again, report back plz!

Will do, thanks very much for your help on this!

**Comment by si458** [comment]
no worries! dont forgot to donate/sponsor me to help community projects! - https://www.si458.co.uk/2024/01/05/donation/
