### ISSUE TITLE
Lack of mouse control on agent  running MACos Sonoma 14.1.1

### ISSUE THREAD

**Issue by Tony-Stephens** [Ylianst/MeshCentral#5589]
When connecting to a lan agent running MACos Sonoma 14.1.1 the Mouse is inactive and does not show on screen.
I can connect to another machine running an older version of MACos and everything is fine.

Server is Windows 10 Version 22H2
No Virtualization
Network = Lan
MC Version = 1.1.16
I do not know where to look for the Node ID

**Client Device (please complete the following information):**
Device = Desktop  (MacMini Arm OS
 - OS + MacOS Sonoma 14.1.1
 - Network: Local to MeshCentral
 - Browser: Vivaldi (Chrome variant)

**Comment by si458** [comment]
have you enabled the permissions in the Security & Privacy -> Privacy tabs correctly?
i know the is a bug where its not asking the end user of the device to give permission
![Desktop-Users-MacBook-Pro local-2023-11-29-12-24(2)](https://github.com/Ylianst/MeshCentral/assets/765314/de2821e0-a567-44ab-af80-a12ba705c687)
![Desktop-Users-MacBook-Pro local-2023-11-29-12-24(1)](https://github.com/Ylianst/MeshCentral/assets/765314/f1b32e13-7f66-4ead-9b80-9b4aff1ee261)
![Desktop-Users-MacBook-Pro local-2023-11-29-12-24](https://github.com/Ylianst/MeshCentral/assets/765314/ec280f57-49e5-49d5-8409-f719a45bc093)


have you also checked the 'input' checkbox is ticked under the window?

**Comment by silversword411** [comment]
We need a Mac FAQ in docs about this.

**Comment by si458** [comment]
@silversword411 the patch was already merged into the agent, just need a new agent build and released!
but yes an FAQ of mac control, would be a good idea!
