### ISSUE TITLE
Bugs: Lots of display errors when using ?hide=5 to hide footer/header (0.4.1-y)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#559]
This is a bug report follow-up to #550 regarding the ?hide= parameter as proposed by @Ylianst.

The bugs that I noticed in the first catch are (all in Firefox 69 for ?hide=5):

- hiding header removes the possibility see which user is currently logged in and to log out (this is why we manipulated the header's CSS instead of simply hiding the header)
- in Left Bar Interface mode:
  - in the primary tabs My Devices, My Events, My Files and My Users, hiding the header and/or footer creates a big rectangle of unused space on the bottom of the page of the height of header+footer, so the regained vertical space is unavailable (this is caused by max-height: calc(100vh - n); and/or height: calc(100vh - n); directives where the removed header's/footer's height **is not** substracted from n)
  - in devices' Desktop, Files and Console subtabs, the header's/footer's height **is** substracted from n, but more than actually gained, causing a vertical scroll bar to appear
  - in devices' Events and Intel(R) AMT tabs, the gained height **is not** substracted from n
  - in My Server's Console tab, the header's/footer's height **is** substracted from n, but more than actually gained, causing a vertical scroll bar to appear
  - in My Server's Trace tab, the gained height **is not** substracted from n
- in Top Bar Interface mode
  - in the primary tabs My Devices, My Events, My Files and My Users, the gained height **is not** substracted from n
  - opening a primary tab that uses a secondary tab bar does not show the secondary tab bar, thus device management and server management is practically impossible (as in #521) 
- in Fixed Width Interface mode
  - in the primary tabs My Devices, My Events, My Files and My Users, the gained height **is not** substracted from n
  - in devices' Desktop, Files and Console subtabs, the header's/footer's height **is** substracted from n, but more than actually gained, causing a vertical scroll bar to appear
  - in devices' Events and Intel(R) AMT tabs, the gained height **is not** substracted from n
  - in My Server's Stats tab, the gained height **is not** substracted from n but from the line chart, causing its lower part to be drawn out of the <div>
  - in My Server's Trace tab, the gained height **is not** substracted from n
  - in My Server's Console tab, the header's/footer's height **is** substracted from n, but more than actually gained, causing a vertical scroll bar to appear and controls are out of screen by default

**Comment by Ylianst** [comment]
Thanks for the report... arg... going to be a bunch of work to fix this.

**Comment by si458** [comment]
i believe this is fixed now
