### ISSUE TITLE
PUTTY ERROR ON SSH MIKROTIK

### ISSUE THREAD

**Issue by pieer3991** [Ylianst/MeshCentral#5593]
hello,
I have a problem calling an SSH instance to a Mikrotik device where I get the following error:
![image](https://github.com/Ylianst/MeshCentral/assets/74231602/55282ba2-46f3-4829-8907-13a0475ed5a9)

**Comment by si458** [comment]
have u actually checked u can ssh to ur mikrotik from the remote device first? Before trying to relay with meshcentralrouter?

**Comment by pieer3991** [comment]
> have u actually checked u can ssh to ur mikrotik from the remote device first? Before trying to relay with meshcentralrouter?

Yes, whit Putty
![image](https://github.com/Ylianst/MeshCentral/assets/74231602/ab8d707c-d785-457c-95cc-4bb82f0ef034)

**Comment by silversword411** [comment]
> Have u tried setting a different port other than 22 on the local machine side?

This is going to eliminate something already running on your computer on port 22.

**Comment by si458** [comment]
CLOSING AS STALE
