### ISSUE TITLE
Can not open device when tlsOffload is true

### ISSUE THREAD

**Issue by ahdung** [Ylianst/MeshCentral#5598]
**Describe the bug**
I want MeshCentral work under http, so I configured "tlsOffload" and "trustedProxy". when login, can't open device.

**To Reproduce**
no need.

**Expected behavior**
work fine.

**Screenshots**
![微信截图_20231201110941](https://github.com/Ylianst/MeshCentral/assets/12094247/edf6a02a-51e4-4c92-8901-f1479f5a5453)

**Server Software (please complete the following information):**
 - OS: windows 10 22H2 x64 proworkstation
 - Virtualization: No
 - Network: WAN
 - Version: 1.1.16
 - Node: 14.17.1
 - Browser: Google Chrome

**Your config.json file**
```
{
   "settings": {
      "cert": "***hidden***", 
      "port":6132,
      "redirPort":0,
      "tlsOffload":true,
      "trustedProxy":"***hidden***"
   }
}
```

**Comment by si458** [comment]
the software is designed to use HTTPS, so it wont work with just standalone http
