### ISSUE TITLE
Wrong default value for sessionTime in meshcentral-config-schema.json

### ISSUE THREAD

**Issue by Pinkbyte** [Ylianst/MeshCentral#5599]
**Describe the bug**
meshcentral-config-schema.json claims that if sessionTime is not defined in config file it will be 60 minutes, but in fact, no restrictions are placed on cookie duration (at least according to browser's developer tools in Firefox). Restarting browser even after few hours - and still logged in. 

If sessionTime is defined explicitly in config - it works as expected.

**To Reproduce**
1. Start meshcentral server without sessionTime defined in config
2. Log in
3. Look into cookie information

**Expected behavior**
Either sessionTime should be 60 minutes by default, or misleading documentation should be changed, marking that no default is set.

**Server Software (please complete the following information):**
 - OS: AlmaLinux 8.7
 - Virtualization: Podman (container docker.io/typhonragewind/meshcentral:mongodb-1.1.16)
 - Network: LAN with Nginx as reverse proxy
 - Version: 1.1.16
 - Node: v20.9.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Gentoo Linux
 - Network: Local to Meshcentral
 - Browser: Mozilla Firefox

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.local",
    "WANonly": true,
    "sessionKey": "<hidden>",
    "userSessionIdleTimeout": 60,
    "exactPorts": true,
    "port": 443,
    "redirPort": 80,
    "TLSOffload": true,
    "TrustedProxy": "172.16.0.1,172.16.0.2,172.16.0.3,172.16.0.4,172.16.0.5,172.16.0.6",
    "agentsInRam": true,
    "agentPing": 240,
    "browserPing": 240,
    "agentTimeStampServer": false,
    "agentSingLock": false,
    "manageAllDeviceGroups": [ "user//admin"],
    "SelfUpdate": false,
    "mongoDb": "mongodb://mongo:27017",
    "mongoDbName": "meshcentral"
  },
  "domains": {
    "": {
      "title": "Test",
      "title2": "MeshCentral",
      "NewAccounts": false,
      "newAccountsRights": [ "nonewgroups", "notools" ],
      "passwordRequirements": {
        "allowaccountreset": false,
        "loginTokens": false
      },
      "certUrl": "https://172.16.0.1:443",
      "auth": "ldap",
      "_comment - nested groups are not supported!": "",
      "ldapSiteAdminGroups": [ "CN=admin,CN=Users,DC=test,DC=local" ],
      "ldapUserKey": "sAMAccountName",
      "ldapUserGroups": "memberOf",
      "ldapUserRequiredGroupMembership": [ "CN=admin,CN=Users,DC=test,DC=local" ],
      "ldapOptions": {
        "url": "ldap://test.local:389",
        "bindDN": "CN=meshcentral,CN=Users,DC=test,DC=local",
        "bindCredentials": "<hidden>",
        "searchBase": "DC=test,DC=local",
        "searchFilter": "(sAMAccountName={{username}})",
        "reconnect": true
      }
    }
  }
}
```

**Comment by si458** [comment]
after checking the sourcecode this is what happens (also wanted to check this is what you expected?)

IF you dont set sessiontime in config.json it does indeed set a timeout of 60 minutes
`sessiontime: (args.sessiontime) ? args.sessiontime : 60,`

IF you do set a sessiontime its set the maxage of the clients cookie as expected
`if (obj.args.sessiontime != null) { sessionOptions.maxAge = (obj.args.sessiontime * 60000); } // sessiontime is minutes`

but whats also happening is INSIDE default.handlebars its refreshing ur cookie JUST BEFORE your time is UP in the background IF you STAY on the webpage
`if (sessionTime >= 10) { sessionRefreshTimer = setTimeout(refreshCookieSession, Math.round((sessionTime * 60000) * 0.8)); }`

from my knowledge and a quick google, the `session` cookies thats saved in firefox are stored on the server, so if you close the browser and reopen it within the 60mins (59mins) it will log you bk in as the cookie is still valid!?

was you expecting something different?

**Comment by Pinkbyte** [comment]
I just rechecked with MeshCentral 1.0.16 and clean browser profiles (Firefox, Chrome).

The way it works for me is this:
- if sessionTime is NOT defined in config: logging in into MeshCentral, doing some stuff, then closing tab and browser itself. Reopening browser in ~3 hours, trying to open MeshCentral - i am still logged in!!! (not expected, as sessionTime is 60 minutes by default according to docs and there is nothing that extends this timeout)
- if sessionTime is SET to 60 explicitly in config: logging in into MeshCentral, doing some stuff, then closing tab and browser itself. Reopening browser in ~3 hours, trying to open MeshCentral - it redirects me to login prompt (as expected)

No other sessions(from this user) were opened, just test one.
