### ISSUE TITLE
Bug: Moving CIRA-enabled device to different group/mesh results in loss of CIRA connectivity (0.4.1-y)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#560]
When a CIRA-enabled client is moved to a different group than what CIRA originally was set up for, the CIRA connectivity is lost, at the latest when MeshCentral is restarted.
There is no warning message that tells the user this will happen, neither for moving the client nor for deleting a group with CIRA clients originally associated to it but currently not in that group.
After moving a CIRA client back to the group that CIRA was originally set up for, the connectivity is restored after some seconds.

Steps to reproduce:
1. Set up two groups, foo and bar..
2. Add a device to group foo using the CIRA set-up script for that group.
3. Move device to group bar.
4. Restart MeshCentral.
5. See that CIRA connectivity is NOT coming up again.
6. Delete empty group foo.
7. Realise that there is no possibility to get CIRA connectivity up again (except from backups) as a new group of the same name will have new identifiers.

It would be great if MeshCentral could switch over from per-group CIRA setup to a per-device CIRA setup, preferably using mutual TLS authentication employing MCs own root certificate to sign device keys. As this means individual CIRA setup scripts are required on a per device basis, a function to run CIRA setup script (and CIRA cleanup scripts) directly on devices with AMT or CIRA connectivity, making the CIRA setup complete automatic, would be awesome.

In the meantime, it would be nice to have MeshCentral
1. show the name of the group that CIRA has been set-up for in the CIRA-enabled devices' General tab (so one knows where to move the device back to restore CIRA connectivity)
2. display an additional warning that CIRA connectivity will be lost when trying to move CIRA-enabled devices to a new group until device is moved back
3. show a warning that CIRA connectivity will be lost definitely when trying to delete a group that has CIRA-enabled devices still associated or CIRA-enabled devices are still present in other groups but were set-up for CIRA for this group (e.g. reusing the name/group id from 1.)

**Comment by Ylianst** [comment]
This is certainly not a case I tested for, I need to fix this.

**Comment by MailYouLater** [comment]
So, what's the proper thing to do?

- Warn the user that moving these devices will cause issues.
- Automatically reprovision each device being moved so that it connects to the new device group
- A mix, where you warn that it can cause issues and also offer to reprovision the device(s).

**Comment by Ylianst** [comment]
I need to fix it so it just works. The CIRA connection should follow the device even if it changes groups just like the MeshAgent does.

**Comment by jsastriawan** [comment]
You could send a new cira mescript to the agent to reconfigure cira or you can activate apf tunnel on meshagent to drive server side cira cleanup and setup.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.2-e with a fix for this. CIRA connections should track the device now, even if it changes groups. Let me know if it works.

**Comment by veitw** [comment]
Sorry for the late reply.

Moving CIRA devices between groups no longer breaks CIRA connectivity. I regard this fixed. :)

Thank you very much!
// Veit

**Comment by PetieM** [comment]
I think this bug may have returned. I have a CIRA device that I moved a while back and have been wondering why it's been offline since. I just moved it back to the original group and it immediately reconnected. Moving it to another group kept the device online but after restarting the server, it's offline and seemingly failing its authentication requests now.
