### ISSUE TITLE
Adding native message box way

### ISSUE THREAD

**Issue by ahdung** [Ylianst/MeshCentral#5605]
The current message window is unreliable, content blank, user blank, can't close, freeze etc. like:
![bbb](https://github.com/Ylianst/MeshCentral/assets/12094247/4a057fed-c070-4990-93ac-409b6c12bab4)

The real environment is very complex, Please consider implementations with less or no component dependencies as much as possible.

**Comment by si458** [comment]
go to the Desktop tab, then click the BELL icon on the bottom right hand corner,
enter a message, and it will pop up as a Windows Powershell Notification 👍

**Comment by si458** [comment]
you can send `alert TITlE, CAPTION` from within the console tab of a device,
this will also display a pop up alert notification,might help

**Comment by ahdung** [comment]
@si458 Thank you for your help.

**Comment by si458** [comment]
ok to close this?

**Comment by ahdung** [comment]
@si458 I still asking for adding a native way in here:
![image](https://github.com/Ylianst/MeshCentral/assets/12094247/7902fe76-f6b7-436b-974c-f1ab23f217ff)

**Comment by tomsik-radek** [comment]
> @si458 I still asking for adding a native way in here:
> ![image](https://github.com/Ylianst/MeshCentral/assets/12094247/7902fe76-f6b7-436b-974c-f1ab23f217ff)
> 

Isn't that the toast notification?

**Comment by si458** [comment]
done PR for you! will be released when @Ylianst does a new release in the new year for you!
![image](https://github.com/Ylianst/MeshCentral/assets/765314/e71e4b7a-f315-435a-a477-b8b9c349f74d)

**Comment by ahdung** [comment]
@si458 GREAT, Happy to this, Thank you from the bottom of my heart, best wishes for you.

**Comment by si458** [comment]
dont forget to sponsor me! ❤️ https://github.com/si458 - all links on the left hand side!

**Comment by ahdung** [comment]
@si458 I'm chinese, no credit card, I suggest you activate a Wechat or Alipay payment receiving qrcode.
