### ISSUE TITLE
Question: E-mail contact to discuss security related issues?

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#561]
Hi,

I have discovered something that I regard to be a vulnerability.

Is there an e-mail contact or other means of communication?
Is PGP encryption welcome and where to find/verify the key?

Best regards,
// Veit

**Comment by Ylianst** [comment]
You can mail me at "ylianst at gmail.com". Always interested in any security discussion. I use to have this email address the meshcommander.com web site, but replaced it with the [Reddit forum](https://www.reddit.com/r/MeshCentral/). I don't have a PGP key, would be great to get one. Is there any PGP software that does not integrate with email so I can just cut & paste decrypt/encrypt when I need it? Recommendations welcome.

**Comment by MailYouLater** [comment]
> Is there any PGP software that does not integrate with email so I can just cut & paste decrypt/encrypt when I need it? Recommendations welcome.

I'm not sure, as I don't have a PGP key for this kind of use either, but if you just want an easy way to use PGP for your mail, but only when want to, you could probably use [Mozilla Thunderbird, Portable Edition](https://portableapps.com/apps/internet/thunderbird_portable) with [GPG Plugin Portable
](https://portableapps.com/apps/security/gpg-plugin-portable) as described at https://portableapps.com/support/thunderbird_portable#encryption, and only use it when you get (or want to send) an encrypted email.

**Comment by Ylianst** [comment]
I want to also not that my email address is attached to the GitHub profile. Really no need to ask for it.

**Comment by Ylianst** [comment]
Just added a contact information page on MeshCommander.com with a PGP key. I also added my PGP key to GitHub. In the end, I just used [PGPTool](https://pgptool.github.io/) which is super easy.

**Comment by Ylianst** [comment]
To be complete, here is my PGP key. Same one as the web site. I will close this topic. Anyone is free to post me any security issues or concerns, I will try to address them right away.

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.56

mQMuBF2gC4sRCAClFNvMCCVW3ego3UHBQ6LhSenJfaZYhvn8gaGuemSQxqTI6bla
BTAv3aMtQnvqlSuadMMegb+FO6hnaQMlGvpVA1qpkSzgrPS5HrBD3H33J2Nj3i93
ZpDPpxdI0ehCj6IJPnl0GxGbpKIN8YpJUFl44wv1lMRFI1lgyb+dCoO60irYdNQB
PV85BI+DwPfOBFHunwR78nqMvpvsk9HaeHjEP7oXr952/7EazUowZsMlEfkYnw5S
+tLfpCoY3QWkektpJP40nMJSKQdV2NEuED99doA0X+7P1vsvFFFyMH69dnU2uSay
XCHpkAbntBy0BGmtF1RnTcOMv2V/LPXnlMdvAQCbmLQzNra3r163tcdRY0jSs+pZ
1L3w5tHNj2dzhfpa7wf/SIuds6QTr2LCN6miLoSVCRMMpT7d771b16GwQqWEXzN2
+h7dYqrssHPOa8FSUrPerz0+0eFcbMSm5/L/4KXWXoQthURv8aMP9E0iVoUYaaKB
7U+5vFEZbpoOZyZmTAjXQMSNZCft0azA82Q+G85euyicWtMv48yNVzUhkdh+M2ud
ohkXX2Aor1TqpBJoIeWke7j9D+Bo+lu61zPRx5ed9teUeLJCwqNEjlE+6gre5kxF
PoreAtn59QYcBIpzQEWVMbNFlDAR4jMyqIoKCGfBPiRw2V+kunbzqiGQEglIFfOt
6sTN/+CJh0ei976VDmE0Z1kMN+CNLgIjIw8fl02V9QgAnHcpqtVUxR4dbGOhVDq5
lWv+K75QQlWyXC2k+KboXcaCvH0WZEBACYzO0CfrZ5hP9BSkbj5usSUVGGHwEFAJ
t+/04KVY71fW281Ej5kGNaIKxeKsx6+hMo+UXb5ZM+6fANNNxs1cK95sTH6PjkyB
tsKxLoa3CV2v9mSE5JiKKt74R9nXVo7PXf6DizwAU2l30Lb6y6y0OdXdCCPAG8Ij
FrMgPu5MtjgsO5DnkZfUqDPWHhOgEPyOh3Ho+pvDhNYh5cm2eLQ8g5orzs2FHwbZ
DpAHwCdqrlcpBlKJ4W/MZdf1fg2PjqaTWm7ZFiGr91P0F6kltTLWbVKTjLdS0T+D
L7QnWWxpYW4gU2FpbnQtSGlsYWlyZSA8eWxpYW5zdEBnbWFpbC5jb20+iF4EExEI
AAYFAl2gC4sACgkQg7j/r4DH+kD/3gD+MRedlM53VzOtNOpS6mqDAxj1aWP90HN0
AqO6zuCTyGgBAJlunLFKH8IUetmQOhiohB8HVhdm/q4lKRDV7sHdplDyuMwEXaAL
ixACAJSU/sCV87he4oZUKzg2/IGl3QoDSbTCOd04dE1IjPjjHbi8t9M7Qau55aM8
ypFEsc7zMslL8Fc78EejrKmM3zsB/RU9XWFyrbQwRbaK6OHeEHC2E3AFaG0p09c6
d0kZloHuWyEsm5a/3PpbIM1eP9IESJXWCc+bQQt6DxLKHLmkKMwB/icWMg8uMJlx
aady8TEq7LH5oFVKsglnwuN1nIkecrf77TVkEqTjIxS6TiOup6zOnioFNKLYBAH0
WUnJEYFvx4OIXgQYEQgABgUCXaALiwAKCRCDuP+vgMf6QGFTAQCUj2gGwsFlN0eR
Wowv4eLcc3FwQ+lBElUctKg8vNFb0gD/ZWVWsWwKerNgNnf7RGD9mt8G2CKvdgGG
oZ2hPP2gU9w=
=roW4
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by veitw** [comment]
Hi @Ylianst,

> You can mail me at "ylianst at gmail.com". 

I just decided to ask as I know that MC is somewhat Intel-sponsored and Intel itself explicitly asks for any security related communication to be PGP encrypted, so it could have been be a policy requirement.

> Is there any PGP software that does not integrate with email so I can just cut & paste decrypt/encrypt when I need it? Recommendations welcome.

We use gnupg and some frontends for mail and desktop integration. The Linux desktops and apps usually come with gnupg support integrated, either directly or indirectly via extensions, but for Windows I regard [gpg4win](https://www.gpg4win.org/) a good starting point, as it is open source, uses GnuPG as backend and comes with several tools and extensions for integration:

* Kleopatra for graphical key management
* GPA, an older tool for graphical key management originating from the GNOME desktop, but when I used it the last time on Linux many years ago, it had copy-and-paste features for encrypting/decrypting
* GpgEX for Windows Explorer shell integration (such as right click on a file to encrypt or decrypt)
* GpgOL for Outlook integration (you may skip this)

Also, it is not required to bind a PGP key to an E-Mail address, if you do not want to make it pop up here. You might leave it out or use an alias or even another URI protocol scheme.

I will send you a PGP encrypted text file with my finding later, using the key above.

Best regards,
// Veit
