### ISSUE TITLE
Crashing the server when i do peering 

### ISSUE THREAD

**Issue by KellyDi0te** [Ylianst/MeshCentral#5621]
**Describe the bug**
Whenever i am enabling peering on my server, I get a crash and there's nothing I can think of to resolve the bug. 

**To Reproduce**
1. Enable 'peers' via config.json 
2. Launch the server 
3. Wait approximately 30 seconds
4. The server crashes, then reboot

**Expected behavior**
Peering should work fine since a few updates, after issue #5373 

**Error i get : **
```
Peer sign fail 2
ERR: /opt/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:320
      throw err;
      ^

Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/opt/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at Object.func (/opt/meshcentral/node_modules/meshcentral/multiserver.js:283:32)
    at ChildProcess.<anonymous> (/opt/meshcentral/node_modules/meshcentral/certoperations.js:1361:43)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v20.9.0
Error: Command failed: /usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 849917
/opt/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:320
      throw err;
      ^

Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/opt/meshcentral/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at Object.func (/opt/meshcentral/node_modules/meshcentral/multiserver.js:283:32)
    at ChildProcess.<anonymous> (/opt/meshcentral/node_modules/meshcentral/certoperations.js:1361:43)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v20.9.0

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:526:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/bin/node /opt/meshcentral/node_modules/meshcentral --launch 849917'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Server Software (please complete the following information):**
 - OS: CentOS 8 
 - Virtualization: VMWare
 - Network: LAN
 - Version: 1.1.16
 - Node: 20.9.0

**Client Device (please complete the following information):**
 - Device: WorkStation
 - OS: Windows 10 Pro 22H2 + Ubuntu
 - Network: LAN
 - Browser: Chrome, Edge, Firefox

**Remote Device (please complete the following information):**
 - Device: WorkStation, laptops, RaspberryPi
 - OS: Windows 22H2
 - Network: LAN

**Your config.json file**
```
{
	"$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
	"__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
	"__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
	"settings": {
		"cert": "cert-of-server1",
		"_WANonly": true,
		"_LANonly": true,
		"sessionKey": "MySessionKey",
		"port": 443,
		"_aliasPort": 443,
		"redirPort": 80,
		"_redirAliasPort": 80,
		"mongoDb": "mongodb://ip-of-server1:27017/?replicaSet=meshcentral",
		"mongoDbChangeStream": true,
		"mongoDbBulkOperations": true,
		"mongoDbName": "meshcentral",
		"plugins" : {"enabled":true},
		"_tlsOffload": "127.0.0.1",
		"_agentPong": 300
	},
	"domains": {
		"": {
			"title": "MeshCentral ",
			"_title2": "",
			"_minify": true,
			"newAccounts": false,
			"_certUrl": "http://ip-meshcentralLoadBalancer",
			"_userNameIsEmail": true,
			"_PasswordRequirements": {
				"min": 8,
				"max": 128,
				"upper": 1,
				"lower": 1,
				"numeric": 1,
				"nonalpha": 1
			},
			"auth": "ldap",
			"LDAPSiteAdminGroups": [ "SomeWhere"]:
 {
				"url": "ldap://ip-of-ldap-server:389/",
				"bindDN": "Somewhere else",
								"__comment__": "lien du compte utilisÃƒÂ© pour la requete ldap" ,				 
				"bindCredentials": "my password",
				"searchBase": "Far Far Away", 
								"__comment1__":"va chercher les utilisateurs ici" ,			 
				"searchFilter": "(sAMAccountName={{username}})", 
				"tlsOptions": { "rejectUnauthorized": false },
				"reconnect": true
			},
			"ldapUserName": "name",
			"ldapUserKey": null,
			"ldapUserBinaryKey": "objectSid",
			"ldapUserEmail": "mail",
			"ldapUserRealname": "name",
			"ldapUserPhoneNumber": "telephoneNumber",
			"ldapUserImage": "thumbnailPhoto",
			"_ldapSaveUserToFile": "C:\\tmp\\ldapuser-save.txt",
			"_ldapUserGroups": "memberOf",
			"ldapUserRequiredGroupMembership": ["Some OU "],
			"_ldapSyncWithUserGroups": true
		}
	},
	"smtp": {
		"name":"smtp-server",
		"host":"relais-smtp",  
		"port": 25,
		"from":"meshcentral@my-domain.com",
		"_user":"",
		"_pass":"",
		"tls": false,
		"verifyemail": true,
		"tlscertcheck": false,
		"tlsstrict": false
	},
	"_letsencrypt": {
		"__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
		"email": "myemail@mydomain.com",
		"names": "myserver.mydomain.com",
		"production": false
	},
	"peers": {	
		"serverId": "central1",
		"servers": {
			"central1": {"url": "wss://ip-of-server1:443/"},
			"central2": {"url": "wss://ip-of-server2:443/"},
			"central3": {"url": "wss://ip-of-server3:443/"}
		}
	}
}
```

Regards,

**Comment by schories** [comment]
We did some testing, as we confirm this issue:

- The issue DOES NOT occur with MeshCentral 1.1.15.
- However, MeshCentral 1.1.16 up to MeshCentral 1.1.16 are affected by the above issue.

Hope this helps tracking down the cause.

**Comment by si458** [comment]
@schories weird? we didnt change anything major in 1.1.16? https://github.com/Ylianst/MeshCentral/releases/tag/1.1.16

**Comment by schories** [comment]
@si458 I agree. Let me be more precise:

We tested 1.1.19 - it's affected.
@KellyDi0te named "Version: 1.1.16" in his report. So we
- tested 1.1.15 - it's not affected.
- did not bother testing 1.1.16, 1.1.17 and 1.1.18.

Would be great if @KellyDi0te could kindly check and reply, whether going back to 1.1.15 also fixes/fixed the issue for him.

**Comment by schories** [comment]
Once we added TrustedProxy setting to the *otherwise unchanged* Meshcentral config, the issue also occurs with 1.1.15.

So, I assume you are correct, the issue must be already also within 1.1.15.

Very confusing..

**Comment by KellyDi0te** [comment]
Thank you for the answers @schories. 

As new versions went out, I downgraded progressively to one server but I checked for 1.1.19 and my servers are not crashing anymore. Another thing I did was to go from nginx to HAProxy. 
I think that the problem does not come from MeshCentral but from the proxy settings. 

My problem is solved so I don't know if the ticket should stay open or not.

**Comment by schories** [comment]
Thank you for the kind & quick reply @KellyDi0te! 👍 

We have a highly automated standard design:
- the peering configuration between the 3 meshcentral nodes is direct, no proxy involved
- we use keepalived to switch around an additional VIP for Meshcentral (e.g. meshcentral-cluster.domain.tld); but all 3 servers can also be accessed directly (meshcentral-server01.domain.tld,meshcentral-server02.domain.tld,meshcentral-server03.domain.tld)
- and we use Apache Proxy on each of the 3 hosts to take care of public TLS in front of MeshCentral (which still uses TLS, but self-signed; so Apache is not TLS-offloading in our case, but easing cert-operation for us) - but for https only, not wss

I agree, it sounds like Meshcental expects a true webproxy instead of keepalived switching a VIP around. Although the peering is direct - and not impacted by the VIP. However, the VIP FQDN (e.g. meshcentral-cluster.domain.tld) is configured in config.json under setting as "cert" URL - identically for and on all 3 nodes.

We know that the above design offers no true load-balancing as all requests hit 1 server, the one with the active VIP. For us high availability is most important here, not load - and thus not dealing with multiple haproxies (with keepalived then) in front.

However, we could use haproxy, too. Thus please allow a few questions:

Do you use (a single) haproxy only (e.g. no keepalived)?
Do you use haproxy as TLS-offload (means unencrypted from haproxy to meshcentral)?
Do you proxy everything - means https **and** wss - via haproxy?

Thank you so much!

**Comment by KellyDi0te** [comment]
We have quite the same architecture : 

- I use HAProxy and Keepalived on the 3 servers so when server1 (the main one) goes down, server2 takes the lead. 
- I use a trusted certificate that I deploy via HAProxy on the virtual IP
- Every MeshCentral can be accessed directly via their own DNS name 

Now for the questions : 

**Do you use (a single) haproxy only (e.g. no keepalived)?**
     Answered right above  
**Do you use haproxy as TLS-offload (means unencrypted from haproxy to meshcentral)? **
    I use my HAProxy as a TLS-Offload because they are on the same server 
             "TLSProxy": "127.0.0.1",
             "TLSOffload": "127.0.0.1",
**Do you proxy everything - means https and wss - via haproxy?**
    According to Google, wss port is 443 and 80 so i would say yes. Here's my HA configuration for the frontend : 

```
frontend main
    #Declaration of frontend

    # Listening ports
    bind *:80
    bind *:443 ssl crt /etc/pki/tls/private/my-meshcentral-certificate.pem

    #Using VIP
    mode http

    #Redirecting HTTP to HTTPS
    redirect scheme https if !{ ssl_fc }

    #Used backend 
    default_backend             meshcentral

```

Now the backend configuration : 
```
backend meshcentral
    #Declaration of backend

    #Algorithm of load-balancing
    balance  roundrobin

    # checking if a file is available --> website up
    http-check expect status 200

    #Declaration of backends
#ssl verify none
    server meshcentral1 127.0.0.1:444 check
#ssl verify none
    #server meshcentral2 10.1.2.43:444 check ssl verify none
    #server meshcentral3 10.1.2.220:444 check ssl verify none

    ## Activation of the sticky table to stay on the same server
    stick-table type ip size 1m expire 10m
    stick match src
    stick store-request src


```

Hope this can help !

**Comment by si458** [comment]
not sure if this helps but the is a config we have in the docs for using haproxy?
https://ylianst.github.io/MeshCentral/meshcentral/#haproxy-reverse-proxy-setup
you guys are using WAY advanced stuff, so i wouldnt have a clue where to start haha

**Comment by schories** [comment]
@KellyDi0te  @si458  Thank you for your support, especially the quick and detailed replies. 

While we make changes to our setup and now with having proof, that above configuration is working fine with latest MeshCentral (at the time of writing 1.1.19), I’d like to thank you once again and kindly suggest to close this ticket now.

**Comment by KellyDi0te** [comment]
No problem :) 

Feel free to come back to us via DM if you have any question ! 
I'm closing the ticket.
