### ISSUE TITLE
windows 8.1 Not getting computer details from some agents

### ISSUE THREAD

**Issue by Pinkbyte** [Ylianst/MeshCentral#5623]
**Describe the bug**
Some agents throw exception and details tab for them is incomplete (no data for BIOS, CPU, Motherboard, RAM, Storage devices)

**To Reproduce**
I am not sure what causes this error. Reinstalling the agent does not help either.

**Screenshots**
See attached screenshots for problem

**Server Software (please complete the following information):**
 - OS: AlmaLinux 8.7
 - Virtualization: Docker
 - Network: WAN mode with TLS offload
 - Version: 1.1.16
 - Node: v20.9.0

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Gentoo Linux
 - Network: Remote over WAN
 - Browser: Mozilla Firefox 102

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Microsoft Windows 8.1 Enterprise - 9600
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 1928065373

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "meshcentral.local",
    "WANonly": true,
    "sessionKey": "<hidden>",
    "userSessionIdleTimeout": 60,
    "exactPorts": true,
    "port": 443,
    "redirPort": 80,
    "TLSOffload": true,
    "TrustedProxy": "172.16.0.1,172.16.0.2,172.16.0.3,172.16.0.4,172.16.0.5,172.16.0.6",
    "agentsInRam": true,
    "agentPing": 240,
    "browserPing": 240,
    "agentTimeStampServer": false,
    "agentSingLock": false,
    "manageAllDeviceGroups": [ "user//admin"],
    "SelfUpdate": false,
    "mongoDb": "mongodb://mongo:27017",
    "mongoDbName": "meshcentral"
  },
  "domains": {
    "": {
      "title": "Test",
      "title2": "MeshCentral",
      "NewAccounts": false,
      "newAccountsRights": [ "nonewgroups", "notools" ],
      "passwordRequirements": {
        "allowaccountreset": false,
        "loginTokens": false
      },
      "certUrl": "https://172.16.0.1:443",
      "auth": "ldap",
      "_comment - nested groups are not supported!": "",
      "ldapSiteAdminGroups": [ "CN=admin,CN=Users,DC=test,DC=local" ],
      "ldapUserKey": "sAMAccountName",
      "ldapUserGroups": "memberOf",
      "ldapUserRequiredGroupMembership": [ "CN=admin,CN=Users,DC=test,DC=local" ],
      "ldapOptions": {
        "url": "ldap://test.local:389",
        "bindDN": "CN=meshcentral,CN=Users,DC=test,DC=local",
        "bindCredentials": "<hidden>",
        "searchBase": "DC=test,DC=local",
        "searchFilter": "(sAMAccountName={{username}})",
        "reconnect": true
      }
    }
  }
}
```
![01](https://github.com/Ylianst/MeshCentral/assets/1030422/4580fabb-8f8e-4000-b9f2-d1f1fc922a6c)
![02](https://github.com/Ylianst/MeshCentral/assets/1030422/b4a0368b-c905-45f8-b5b6-d698e168a42c)

**Comment by si458** [comment]
so its failing on the sysinfo i think
can you run the following command (note some might take a min to reply)
`info` `osinfo` `sysinfo`

**Comment by Pinkbyte** [comment]
```
> info
Current Core: Dec 9 2022, 1928065373
Agent Time: 2023-12-12 14:57:36.501+03:00.
User Rights: 0xffffffff.
Platform: win32.
Capabilities: 15.
Server URL: wss://meshcentral.dstu.local:443/agent.ashx.
OS: Майкрософт Windows 8.1 Профессиональная - 9600.
Modules: amt-apfclient, amt-lme, amt-manage, amt-mei, monitor-border, smbios, sysinfo, util-agentlog, wifi-scanner-windows, wifi-scanner, win-console, win-deskutils, win-info, win-securitycenter, win-terminal, win-virtual-terminal, win-volumes.
Server Connection: true, State: 1.
> osinfo
OS: Майкрософт Windows 8.1 Профессиональная - 9600 [ConPTY: NO]
> sysinfo
uncaughtException1: Error: child_process.subProcess.exit():  => EventEmitter.emit(): Event dispatch for 'exit' on 'childProcess.subProcess' threw an exception: TypeError: cannot read property 'split' of undefined in method '()'
```

**Comment by si458** [comment]
so the is an issue with Windows 8.1 and the `getSystemInformation` function,
does this ONLY happen on windows 8.1? OR on other devices like Win 10, Linux, Mac?

**Comment by Pinkbyte** [comment]
I have caught this on 3 devices with Windows 8.1, but not all devices on Windows 8.1 trigger this - some of them are running just fine. Not seeing this error neither with Windows 10 nor Windows 7.

**Comment by si458** [comment]
i will have a look when i get chance,
i no the is a BUG with virtual machines running Windows, so ill have to install Windows 8.1 on a PHYSICAL device to fix this
also note Windows 8.1 is now EOL, so the machines SHOULD be upgraded to 10 ASAP
https://learn.microsoft.com/en-us/lifecycle/products/windows-81

**Comment by Pinkbyte** [comment]
> i will have a look when i get chance, i no the is a BUG with virtual machines running Windows, so ill have to install Windows 8.1 on a PHYSICAL device to fix this

FYI, all machines that i caught this bug are physical

**Comment by si458** [comment]
well found one of the bugs!
the powershell script that runs and gets returns for some DUMB reason, is inserting a blank line in between results?
so its trying to split a BLANK/UNDEFINED!

just trying to find/fix the second bug

**Comment by si458** [comment]
ok so turns out the repeated error is just the volumes being called over n over, so its the same error!
the fix will get rid of these errors and resume the sysinfo for Windows 8.1!

**Comment by si458** [comment]
fix has been merged for you :)
