### ISSUE TITLE
Possible bug with meshctrl.js and downloading files from remote machines.

### ISSUE THREAD

**Issue by MaximusAurelius595** [Ylianst/MeshCentral#5629]
**Describe the bug**
I'm more looking to validate if accurate bug or not so based on my current setup apache2 reverse proxy Meshcentral version 1.1.16 and not sure if there is a place to put beta bugs have not confirmed if issue exists on stable. 

When trying to download a file from a remote Win machine onto a Linux server where mesh central is running. I was seeing a Download complete msg but no actual file downloaded and undefined bytes written. Whereas uploads to the same node works ok.

meshctrl upload --id 'NODEID' --file filename --target 'C:\filedir\'
Connecting...
Waiting for Agent...
Connected.
Uploading...
Upload done, 656 bytes sent.

------

meshctr download --id  'NODEID' --file "c:\filedir\filename.out" --target filename.out
Connecting...
Waiting for Agent...
Connected.
Download completed, undefined bytes written.

**To Reproduce**
meshctr download --id  'NODEID' --file "c:\filedir\filename.out" --target filename.out

**Expected behavior**
The file to download correctly and message to not have an undefined msg.

**Server Software (please complete the following information):**
 - OS: [Ubuntu]
 - Network: [LAN/WAN, reverse proxy.]
 - Version: [1.1.16]
 - Node: [v14.17.1]

**Client Device (please complete the following information):**
 - Device: [PC]
 - OS: [Win10 Pro]
 - Network: [Remote over WAN]
 - MeshCentralRouter Version: []

[FIX / WORKAROUND] 
Quick and dirty workaround solution that worked for me  

In meshctrl.js file around the line 2575 added two extra lines before for variable checkcmd

Added to the line 2575 as an additional check :

 var checkcmd = null;
  try { checkcmd = JSON.parse(rawdata.toString()); } catch (ex) {}
  if ((rawdata.length > 0) && (rawdata[0] != '{') && checkcmd == null) {

Can be cleaned up but figured I would post here in case could be useful or should be looked at. After no issues downloading files text or binary :

 meshctr download --id 'NODEID' --file 'C:\Program Files\Mesh Agent\MeshAgent.exe' --target /opt/meshanalytics/out/MeshAgent.exe
Connecting...
Waiting for Agent...
Connected.
Download started: /opt/meshanalytics/out/MeshAgent.exe
Download completed, 3468712 bytes written.
root@hwsrv-365077:/opt/meshanalytics/out #

**Comment by si458** [comment]
fixed for you!
it should be checking if the first byte in the binary was a string, but the checking value was in binary, doh!

**Comment by MaximusAurelius595** [comment]
Great yea I did not want to modify the existing just added to the code to achieve the same result but thanks!
