### ISSUE TITLE
Meshctrl ListDevices small bug more of a nuisance

### ISSUE THREAD

**Issue by MaximusAurelius595** [Ylianst/MeshCentral#5638]
When using Meshctrl.js I ran into a small bug, although I have not done a deep dive which could be a bigger issue. 

When running (of course I masked nodeid for this)

 meshctrl listdevices

I was getting 

```

id, name, icon, conn, pwr
-------------------------
"SUPERSECRETNODEID", "REMOTEDESKTOP", 1, 0, 0
/opt/node_modules/meshcentral/meshctrl.js:2210
                                    if (settings.xmeshes) { console.log('\r\nDevice group: \"' + settings.xmeshes[i].name.split('\"').join('') + '\"'); }
                                                                                                                     ^
TypeError: Cannot read property 'name' of undefined
    at WebSocket.incoming (/opt/node_modules/meshcentral/meshctrl.js:2210:118)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (/opt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (/opt/node_modules/ws/lib/receiver.js:560:14)
    at Receiver.getData (/opt/node_modules/ws/lib/receiver.js:478:17)
    at Receiver.startLoop (/opt/node_modules/ws/lib/receiver.js:167:22)
    at Receiver._write (/opt/node_modules/ws/lib/receiver.js:93:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
```

I was just wrote in a try catch so it would not stop execution of the command 

```
var info = "";
try{ info = settings.xmeshes[i].name.split('\"').join('') }catch(ex){console.log("Mesh ID Not Found: " + i)}
console.log('\r\nDevice group: \"' + info + '\"'); }
```

now executes ok for me and prints a node issue.

**Comment by si458** [comment]
So is the command showing the first device but not the 2nd?
How many devices should it be listing?

**Comment by MaximusAurelius595** [comment]
so the command itself has many items it shows for me currently 475 remote machines. I have a good amount on there and some time mid way on one node id I get this issue. Not sure if that node id has some issue actually I just noticed I cannot delete the node or group does not show up shows up as "Individual Devices".

**Comment by si458** [comment]
sorry for delay, can you share what the nodeID is?

**Comment by MaximusAurelius595** [comment]
Sorry about the delay was on holiday. So a bit tough to post all info here as it contains private data but I believe this is what your looking for seems like the Device group is blank not sure how that happened maybe there was a group assigned before but was saved blank not edit it on the front end either. 

Mesh ID Not Found: mesh//7UvSZOrTY5lEK63nQDjYtvXUUoV9
^M
Device group: ""
id, name, icon, conn, pwr^M
-------------------------
"Q0eXtPlDyMhPN3N2UUPQe$vOalCFvjkzNPs", "UPOS-REG1", 2, 0, 0

![mesh](https://github.com/Ylianst/MeshCentral/assets/84785450/abcb19e6-d3e7-4bdf-b2af-56ae3e443e00)

Also below where as other devices you can move to a different group this specific one you cannot as seen below. 

![mesh2](https://github.com/Ylianst/MeshCentral/assets/84785450/f7d0d700-25f1-4cc0-bf4b-4f3b558eb4e5)

**Comment by si458** [comment]
is it only a single device you have the missing options? or multiple devices?

i think the meshagent/meshcentral might of got itself in a puddle with the meshid and groups?

best way i can think to fix it, is to connect to the pc, download anydesk, connect to it via anydesk, then uninstall meshagent (remove folder from program files) and then reinstall agent

**Comment by MaximusAurelius595** [comment]
Oh yea on the fix that's a way or just updating the group name I
assume that should fix it either way might be good to see why or how that
happened. Or maybe a way to update the device group which has no name?
Either way I do not think this is something very common. I have not seen
too many people complain about this. Just found it since I was looking at
it. I'm in the process of automating alot of things so I'm using
meshctrl heavily currently. So I thought I would bring it to your attention
in case.

**Comment by si458** [comment]
so did u create the mesh group called 'Individual Devices' OR a blank space? OR without a name?
as you shouldnt be able to do the last 2, and ive checked the first 1 with a space in the name works ok?
is ur user account an ADMIN account on meshcentral with FULL RIGHTS?

**Comment by MaximusAurelius595** [comment]
Yes my account is an admin account honestly not quite aware how it got there I have multiple people with different rights and some are admins since we have so many devices. I can see if I can find a way to replicate. I just noticed the device ended up there.

**Comment by si458** [comment]
are you still having this issue?
have u tried the latest meshctrl.js from 1.1.22 and use node 20?

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again
if your still having this issue,
please reply back and let us know
