### ISSUE TITLE
Meshcentral crash after disconnect session "Error in mcrec.js"

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#5643]
After upgrade to version 1.1.16 the meshcentral begin crash after disconnect session.

If disable record session, works normally

/opt/node_modules/meshcentral/mcrec.js:16
function log2() { if (directRun) { console.log(...arguments); } else { process.send(...arguments); } /*else { if (worker != null) { worker.parentPort.postMessage({ msg: arguments[0] }); } } */ }
                                                                               ^

TypeError: process.send is not a function
    at log2 (/opt/node_modules/meshcentral/mcrec.js:16:80)
    at /opt/node_modules/meshcentral/mcrec.js:68:17
    at /opt/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23)

**Comment by si458** [comment]
Duplicate #5595

**Comment by fernandogobah** [comment]
I'm so sorry.
