### ISSUE TITLE
Black screen Zorin OS 17

### ISSUE THREAD

**Issue by Jadan1213** [Ylianst/MeshCentral#5644]
Trying to install the service on the new release of Zorin OS 17 based on ubuntu 22.04, and all I can get is a black screen with a mouse cursor. The installer works fine, and it shows up in the dashboard. I can connect via terminal and see running processes, but cannot remotely control the device.

**Comment by si458** [comment]
Daft one, just check if it's using waykland or X org
If its waykland you need to disable

https://help.realvnc.com/hc/en-us/articles/4417193011857-How-do-I-disable-Wayland-to-use-RealVNC-Connect-#how-do-i-disable-wayland--0-2

**Comment by Jadan1213** [comment]
> Daft one, just check if it's using wayland or X org If its wakland. You need to disable it and use X org
> 
> https://help.realvnc.com/hc/en-us/articles/4417193011857-How-do-I-disable-Wayland-to-use-RealVNC-Connect-#how-do-i-disable-wayland--0-2

This would explain why it works on Zorin 16.3. Thank you. Is wayland support coming to mesh central?

**Comment by si458** [comment]
I believe it is already partly supported but not fully supported
For the moment, just switch it to X to save the hassle!
