### ISSUE TITLE
Cannot publish Agents API through Cloudflare WAF w/ DNS Proxy

### ISSUE THREAD

**Issue by germanbravouy** [Ylianst/MeshCentral#5647]
**Describe the bug**
I deployed MeshCentral in Amazon EKS (k8s on cloud) and published to different uri's, one for meshcentral administrative web UI, and one for meshcentral agent HTTP API
Using EKS services, im publishing the admin web UI only to the local network, and the agent API to the internet using Cloudflare WAF with DNS proxy enabled.

The first problem (i workarounded using "ignoreAgentHashCheck: true") was that i couldn't connect the meshcentral agents through internet, as for the EKS locally part im publishing the agent API using a specific certificate managed by EKS, and through internet im using the Cloudflare WAF proxied, so it established its own SSL certificate for data decryption, and this was a problem as the two hashes are different, so setting "ignoreAgentHashCheck" to true workarounded the problem (i know it is a flaw).
The second and most important problem is that when using the Cloudflare WAF in DNS mode (so, no WAF protection), all works amazingly. But when enabling Cloudflare WAF, i can connect to the meshcentral agents that are connected through internet and locally. But for internet happens that the agent receives the request for connecting (so the popup shows and the client can accept) and then the client sees the upper bar that indicates im connected, but in the meshcentral admin web UI, i can see im connected but i can only see a dark screen and nothing else (the same behaviour occurs in the terminal connection). I troubleshooted and in the WebSocket that starts when you connect to an agent i can see that only outbound messages are sent, but none inbound message (agent to meshcentral) are received like the binary data.
Im sure the problem is happening because of the WAF Cloudflare, but in the security section of Cloudflare i can't see any blocks being made in the last hour, so it isn't a WAF blocking issue.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/120838571/896a702e-d5d2-48c1-924c-ab59a8fbeda9)

**Server Software (please complete the following information):**
 - Virtualization: Docker, Amazon EKS pod
 - Network: LAN/WAN with EKS ingress and tlsOffload

**Comment by si458** [comment]
CLOUDFLARE ISSUE, PLEASE REFER TO #5302
USING DNS PROXY/TUNNEL WITH CLOUDFLARE NO LONGER SEEMS TO WORK UNLESS U HAVE A PAID SUBSCRIPTION

**Comment by germanbravouy** [comment]
Thanks i just created a ticket in Cloudflare Support as im paying for Cloudflare Pro services

**Comment by si458** [comment]
> Thanks i just created a ticket in Cloudflare Support as im paying for Cloudflare Pro services

plz do chase them! and let everyone know the reply they tell you!
maybe give them the link to #5302 

i have debugged it for months, and its now got better, but still not working,
the agent connects fine now, but the min it tries to send the kvm image now, cloudflare never receives the image which is weird?

**Comment by kevinh-csalabs** [comment]
We've filed ticket Ticket ID: 3077209 as well. Hopefully it gets some traction.

**Comment by germanbravouy** [comment]
Hi just to check, Cloudflare Support is asking me if has been done a test using a version of MeshCentral prior to 1.1.8 with Cloudflare DNS Proxy enabled?

Thanks

**Comment by kevinh-csalabs** [comment]
Yes, we were on the stable version and it was working and then stopped working.
________________________________

**Comment by germanbravouy** [comment]
Thanks @kevinh-csalabs

**Comment by si458** [comment]
you can even a pick version like 1.0.0 if you wanted which is from like last year,
we have made 0 changes to the websocket stuff, and has always been working for YEARS
it just seems that when the agent fires the KVM video (which is actually only a JPEG file), the meshcentral server never gets that picture, so the issue is the middle man (cloudflare, proxing the image)

**Comment by kevinh-csalabs** [comment]
> Thanks i just created a ticket in Cloudflare Support as im paying for Cloudflare Pro services

@germanbravouy do you have a ticket number I can reference in my ticket so they can see that this is a wider issue?

**Comment by germanbravouy** [comment]
Yes @kevinh-csalabs here you have:

3076681

**Comment by honestlai** [comment]
@si458 I saw you created a few branches and updated the websocket version. I'm assuming that didn't help.

**Comment by si458** [comment]
@honestlai, sorry, that was synk, that tried to update it automatically, will test it myself manually when I get chance, but chances are, will make no difference
