### ISSUE TITLE
Allow running scripts from control view

### ISSUE THREAD

**Issue by AddoSolutions** [Ylianst/MeshCentral#5650]
**Is your feature request related to a problem? Please describe.**
It would be very helpful if I could quickly execute scripts from the remote-control interface/"Desktop Tab"of the UI.  Right now I can "Run commands" but I want to run stuff from my script library.

**Describe the solution you'd like**
Allow browse/execute scripts from library.

**Describe alternatives you've considered**
Otherwise you have to go to the list of computers, select the one, and run it there.

**Additional context**
<img width="426" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/3859209/9bbba1dd-339d-49fb-9254-f87b74d86dd9">
<img width="424" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/3859209/a2d0abf1-7d8c-4fd4-be40-016015c3438a">

**Comment by AddoSolutions** [comment]
Derp, you can already do this...
<img width="211" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/3859209/7b779f21-5462-411e-a450-f85e452f24bc">

**Comment by si458** [comment]
this already exists, beat me too it haha!
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b70b0469-c24a-4ff0-a9e8-b550fd3e68aa)
