### ISSUE TITLE
Add tpm version and status to csv export

### ISSUE THREAD

**Issue by germanbravouy** [Ylianst/MeshCentral#5654]
**Is your feature request related to a problem? Please describe.**
I would like to know the status and version of TPM in each computer that is connected to meshcentral. The info the TPM is already available through the Web UI but when you export all computers to CSV, JSON, etc., the TPM data isn't exported

**Describe the solution you'd like**
I would like to have columns dedicated for TPM (version, manufacturer, isEnabled, isActivated, isOwned) in the CSV export.

**Additional context**
In the Web GUI you can see TPM for a specific computer enrolled to meshcentral:
![image](https://github.com/Ylianst/MeshCentral/assets/120838571/76dba8e2-46dc-48f0-ba6d-8eb5bcfdac7b)

**Comment by si458** [comment]
do you want it inside the normal csv OR the 'include device details' report?

**Comment by germanbravouy** [comment]
I think it would be better in the "Include device details"

Yep, it is a important feature to have to validate TPM status for multiple purposes that require TPM enabled and in a specific version. But it is better if it can be exported for massive checking

Thanks a lot for this feature
