### ISSUE TITLE
MeshCentral Assistant: cannot run as admin / elevate to admin

### ISSUE THREAD

**Issue by energywave** [Ylianst/MeshCentral#5658]
**Describe the bug**
When connected to a MeshCentral assistant Windows computer there isn't a way to do actions as Administrator. Even if you launch the exe as administrator you haven't administrator's rights. That's hardly prevents all system helpdesk activities.

**To Reproduce**
1. Run an assistant on a Windows PC
1. Try to install a software that requires admin privileges (you can't...)

**Expected behavior**
A way to elevate privileges as admin like Teamviewer and similar tools do or, at least, the option to directly run the executable as administrator.

**Server Software (please complete the following information):**
 - OS: Windows 2012
 - Virtualization: Hyper-V
 - Network: LAN/WAN (no differences)
 - Version: 1.1.16
 - Node: 16.15.1

**Client Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10
 - Network: Local / WAN (no differences)
 - Browser: Chrome 120.0.6099.130 64bit / Edge 120.0.2210.91 64bit

**Remote Device (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10 / Windows 11 (same behavior)
 - Network: Local / WAN (no differences)
 - Current Core Version (if known): v0.1.8175.21599

**Comment by si458** [comment]
im going to close this as this is a meshcentral assistant issue and not a meshcentral issue
the is already a similar issue open in the correct repo for this for you to look at https://github.com/Ylianst/MeshCentralAssistant/issues/29
