### ISSUE TITLE
Let encrpyt Security Flaw

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#5677]
WRONG:
Let’s Encrypt announced that all certificates verified through a TLS-ALPN-01 challenge and created between October 29, 2021, and 00:48 UTC January 26, 2022, will be revoked starting at 16:00 UTC on January 28, 2022.

CORRECT:
```
Hi,
Please renew your Buypass ACME (Go SSL) certificates issued before December 22, 2023 at 12:00 (CET).
We have identified an issue within our systems so that these certificates do not comply with certificate issuance requirements.
We have corrected the issue, but all still active Buypass ACME (Go SSL) certificates issued before December 22 at 12:00 (CET) must be revoked.
Renew your affected certificates and install them immediately to ensure that your services continue to be available.
Your affected certificates will be revoked on January 8, 2024 after 14:00 (CET).
We apologize for any inconvenience this may cause. If you need support for the renewal, please comment on our ACME Community where our staff and community members will be able to assist.
```

We have force updated all our server certs except the mesh Central server. Is there a way to force update?  Does let encrypt use this authority by default?  Its been a while and we are trying to figure out the settings of this server.  

lecheck says cert still valid. Is there a console command to force update?

Any help would be appreciated.

**Comment by kpetrow** [comment]
I completely fubar'd those dates.  Hold on for correction

**Comment by dinger1986** [comment]
is it not this? https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449 which is 2022?

**Comment by dinger1986** [comment]
looks old news https://community.traefik.io/t/how-to-force-update-lets-encrypt-certificates/13211

**Comment by dinger1986** [comment]
anyway if you delete the certs and restart mesh it should request certs again https://ylianst.github.io/MeshCentral/meshcentral/#lets-encrypt-support

**Comment by kpetrow** [comment]
Hi,

 

Please renew your Buypass ACME (Go SSL) certificates issued before December 22, 2023 at 12:00 (CET).

 

We have identified an issue within our systems so that these certificates do not comply with certificate issuance requirements.

We have corrected the issue, but all still active Buypass ACME (Go SSL) certificates issued before December 22 at 12:00 (CET) must be revoked.

 

Renew your affected certificates and install them immediately to ensure that your services continue to be available.

 

Your affected certificates will be revoked on January 8, 2024 after 14:00 (CET).


We apologize for any inconvenience this may cause. If you need support for the renewal, please comment on our ACME Community where our staff and community members will be able to assist.

**Comment by dinger1986** [comment]
but thats buypass acme not letsencrypt isnt it?

**Comment by kpetrow** [comment]
Yeah nvm. This is a non issue.. Ill closethread

![image](https://github.com/Ylianst/MeshCentral/assets/18248938/65bcb983-a6b1-438a-9498-9a79d81f8fe8)

**Comment by dinger1986** [comment]
yes please close
