### ISSUE TITLE
Intel AMT - ACM Certificate Download Broken by CSP

### ISSUE THREAD

**Issue by PrplHaz4** [Ylianst/MeshCentral#5678]
**Describe the bug**
When clicking the "Download" button on the ACM Certificate page, a console CSP error is thrown 
> Content-Security-Policy: The page’s settings blocked the loading of a resource at blob:https://sub.mydomain.com/6d5df2c9-4e29-44f5-87f0-c07bc8f7ea43 (“frame-src”).

**To Reproduce**
1. Go to Client -> "Intel AMT"
2. Click on "Connect", "Security Settings"
3. Click on Certificate Name (gray box)
4. See CSP error in console, download does not start

**Expected behavior**
Download the ACM Certificate.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/841414/4fbc84e7-555b-4bdf-99f0-2e0b4144b4f0)

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Virtualization: Docker (`uldiseihenbergs/meshcentral:latest`)
 - Network: LAN, Traefik RP
 - Version: 1.1.14
 - Node: 16.20.2

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Network: Local to Meshcentral
 - Browser: FireFox
 - MeshCentralRouter Version: NA

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: ProxMox
 - Network: Local to Meshcentral
 - Current Core Version (if known): AMT

**Additional context**
I assumed this was an issue with my RP but don't have any CSP setting there explicitly for `frame-src`, and it still occurs with all CSP settings removed.

**Comment by si458** [comment]
fixed for you https://github.com/Ylianst/MeshCentral/commit/c248eada4644d3074600ad8abd49bd17095808ac

**Comment by PrplHaz4** [comment]
> fixed for you [c248ead](https://github.com/Ylianst/MeshCentral/commit/c248eada4644d3074600ad8abd49bd17095808ac)

Confirmed this fix works, the certificate is downloaded successfully!  Thank you!!
