### ISSUE TITLE
AMT ACM Auto Activation with setup.bin failing, manual activation with meshcmd partial success

### ISSUE THREAD

**Issue by aggietallboy** [Ylianst/MeshCentral#5679]
Good Morning All!
I've got my MeshCentral instance *almost* there! I'm down to the last steps for getting my Intel AMT devices properly registered.

I'm running my instance in Amazon, with a MongoDB back end.

Security settings should be good:
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/02af199d-4d55-411a-ac7d-72ac8337b6dd)

I can reach the mps server on 4433, but my browser throws an HSTS error instead of displaying the message.

I have my domain specified  for option 15 on DNS.

I have a sectigo certificate installed and referenced in the configuration section.

I got my machine to join using the meshcmd that was presented in the machine group Intel AMT Setup (meshcmd amtconfig -url.....)

Right after it first connected, the buttons for Desktop, Terminal and Intel AMT were active, but when I hit Connect, it just hung on setup:
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/20ba4972-b83c-4a28-90c3-160d77a48fb8)

But now the machine does not have any indication of power/heartbeat, nor does it allow me to connect to the desktop, terminal, nor the Intel AMT tabs -- the connect button is grayed out.

![image](https://github.com/Ylianst/MeshCentral/assets/10222174/41ac89be-32a7-471a-a0d0-0bb711dc811a)

I've tried deleting and re-adding the device, just rerunning meshcmd with the join string and credentials... no luck getting it back and connected again.

Here's my config file (sanitized)
```
{
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "comment1": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
    "comment2": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    "settings": {
        "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
        "ManageCrossDomain": [
            "user//adminuser"
        ],
        "cert": "myserver.mydomain.com",
        "WANonly": true,
        "_LANonly": true,
        "_sessionKey": "SooperSekritSessionKey!",
        "port": 443,
        "_aliasPort": 443,
        "redirPort": 80,
        "_redirAliasPort": 80,
        "webrtc": true,
        "WsCompression": true,
        "AllowHighQualityDesktop": true
    },
    "domains": {
        "": {
            "title": "My MeshCentral",
            "title2": "myserver.mydomain.com",
            "_minify": true,
            "newAccounts": true,
            "userNameIsEmail": true,
            "mstsc": true,
            "ssh": true,
            "AmtAcmActivation": {
                "log": "amtactivation.log",
                "certs": {
                    "MySectigoCert": {
                        "certpfx": "mycert.pfx",
                        "certpfxpass": "mysekret!"
                    }
                }
            },
            "amtManager": {
                "adminAccounts": [
                    {
                        "user": "admin",
                        "pass": "mysekret!"
                    }
                ],
                "environmentDetection": [
                    "mydomain.com"
                ],
                "wifiProfiles": [
                    {
                        "name": "MyHiddenSSID",
                        "ssid": "MyHiddenSSID",
                        "authentication": "wpa2-psk",
                        "encryption": "ccmp-aes",
                        "password": "myssidsekretpass!"
                    }
                ]
            },
            "agentCustomization": {
                "displayName": "AMT Agent",
                "description": "IT uses this agent for remote monitoring, management and assistance",
                "companyName": "MyCompany",
                "_serviceName": "",
                "fileName": "amtAgent",
                "image": "logo.png",
                "_installText": "",
                "_foregroundColor": "",
                "backgroundColor": "139,0,0"
            }
        },
        "testdomain": {
            "dns": "server.testdomain.com",
            "title": "my test server",
            "title2": "server.testdomain.com",
            "_minify": true,
            "_newAccounts": true,
            "_userNameIsEmail": true,
            "mstsc": true,
            "ssh": true
        }
    },
    "letsencrypt": {
        "comment": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
        "email": "[myemail@mydomain.com](mailto:myemail@mydomain.com)",
        "names": "myserver.mydomain.com,myserver.shortdomain.com,myserver.testdomain.com",
        "skipChallengeVerification": true,
        "production": true
    }
}
```

**Comment by aggietallboy** [comment]
Things I've done:
Tested in Chrome and Firefox
Complete CMOS clear, resetting AMT on device to factory setting before applying setup.bin
Rebuild setup.bin for my "standard" password, as well as the factory default.
set DHCP option 15 to myserver.mydomain.com (didn't seem to help -- made the machine join as mymachine.myserver.mydomain.com)

**Comment by aggietallboy** [comment]
Meshcommander 0.96 connects to the device, with the admin credentials, and remote desktop works from within the private network.

**Comment by aggietallboy** [comment]
MeshCommander reports what seems to be correct configuration on the AMT device:
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/14d6f196-339d-4b51-b763-68b67d0286c6)

**Comment by si458** [comment]
i have this similar issue with an old AMT v6(or might be v8) device, it connects and shows activated in meshcentral
but for some reason it just wont enable the connect button as it thinks not connected

one thing you can try is go into the console tab of the device, then try these few commands `amt`, `amtevents` `amtconfig`
and see if you get any errors

**Comment by si458** [comment]
no thats the server console tab!
i meant, pick a device, then click the 'console' tab rather than remote,files,etc, and try the commands there

**Comment by aggietallboy** [comment]
doh, my bad

**Comment by aggietallboy** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/0f33347b-97b0-4d92-a35e-2c4622f12ebc)

no console tab present on the device itself

**Comment by si458** [comment]
do you not have the meshagent installed on that remote device?
is the meshgroup an intel amt only group?
never NOT seem a console tab present before? unless the groups a relay group OR 'Local devices, no agent'

**Comment by aggietallboy** [comment]
From meshcmd on the device:
Connection Status: Direct, CIRA: Disconnected

Going through on Meshcommander to see if I can see anything else.

**Comment by si458** [comment]
`Connection Status: Direct, CIRA: Disconnected` so basically it wont connect to meshcentral for some reason
how is ur group setup in meshcentral? is it a `agent group` `local group` or `amt only` group,
as i think you need to use an `amt only` group IF you want to amt without installing meshagent on the remote device

**Comment by aggietallboy** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/eb63ea17-5f7b-4928-949f-5de479373d30)

It is AMT only.

**Comment by si458** [comment]
what about running the following commands in the server console window, anything similar to below?
```
> amtacm
--- Activation Certificate 1 ---
Name  : *
SHA1  : ab650198bd3cd7e59ae43b6a3032fd859789ed33
SHA256: 4c921b79e8529d064db33f78a165548e3d47d225d3f5f8ad0d58fcc20c255240
> amtmanager
node//mwGqwyhrjwM9GxWct30iabZYDzTHjzIfYcSK6jgc0FkkwX3Eb6c5hDJv2osdXbAO, DESKTOP-1DI17C8
  Connected, CIRA, Polling Power
> amtstats
Total Intel AMT devices: 3
Un-provisionned: undefined
Provisionned: 3
Versions: 
  7.1.91: 1
  12.0.93: 2
```

**Comment by aggietallboy** [comment]
> amtacm
--- Activation Log ---
File  : amtactivation.log
--- Activation Certificate 1 ---
Name  : mydomain.com
SHA1  : d1eb23a46d17d68fd92564c2f1f1601764d8e349
SHA256: d7a7a0fb5d7e2731d771e9484ebcdef71d5f0c3e0a2948782bc83ee0ea699ef4
--- Activation Certificate 2 ---
Name  : *
SHA1  : 39ccd432872638c2fbba79718af0dc4b09813f5d
SHA256: 09900e45047aafd0b7724389a7f7c69ce2842f4e562a8eb9cb2a5d234c9213d2
> amtmanager
No managed Intel AMT devices
> amtstats
Total Intel AMT devices: 1
Un-provisionned: undefined
Provisionned: 1
Versions: 
  11.8.93: 1

**Comment by aggietallboy** [comment]
Thank you much for helping this far!

**Comment by aggietallboy** [comment]
I've since added in the Azure SSO login and SMTP email configs, I wouldn't have expected any changes because of this, but the config.json has changed a little since I posted.

**Comment by aggietallboy** [comment]
Just as another observation.
The setup.bin created for different groups is identical. It just seems to have a "server side" connection.

**Comment by aggietallboy** [comment]
did a little more digging into amtactivation.log, where it also keeps setup.bin info

{"time":"2024-01-09T19:12:57.211Z","action":"setupbin","domain":"","userid":"user//roger","oldmebx":"admin","newmebx":"C1m@3n3rgy","rootname":"MeshCentral","hash":"09900e45047aafd0b7724389a7f7c69ce2842f4e562a8e
b9cb2a5d234c9213d2","dns":"vpro.cima-energy.com"}
{"time":"2024-01-09T19:13:17.913Z","action":"setupbin","domain":"","userid":"user//roger","oldmebx":"C1m@3n3rgy","newmebx":"C1m@3n3rgy","rootname":"MeshCentral","hash":"09900e45047aafd0b7724389a7f7c69ce2842f4e5
62a8eb9cb2a5d234c9213d2","dns":"vpro.cima-energy.com"}
{"time":"2024-01-09T19:15:08.492Z","action":"setupbin","domain":"","userid":"user//admin","oldmebx":"admin","newmebx":"mypassword","rootname":"MeshCentral","hash":"09900e45047aafd0b7724389a7f7c69ce2842f4e562a8e
b9cb2a5d234c9213d2","dns":"myserver.mydomain.com"}

So this is the setup.bin I built to do a "clean" OOB machine, and try to set it to talk here.

The cert that it's pushing seems to be the self-signed, and not the sectigo AMT cert.

Is this expected?  Shouldn't the sectigo cert come into play somewhere here?

**Comment by si458** [comment]
one think you could check is connect to web amt (using meshcommander) then check security settings and see what certificates are listed there on the device itself
also visit ur intel amt port of meshcentral and see what SSL its replying with `https://meshcentral.mydomain.com:4433/` (i use private window in firefox)

**Comment by aggietallboy** [comment]
It seems to be replying with the built-in self-signed cert, and the certs on the device are showing the same pair -- the self-signed root cert and the self-signed leaf.

**Comment by si458** [comment]
well for starters it doesnt like your certificate then possibly?
but personally i would remove all the intel AMT sections from your config.json
and start again but WITHOUT your cert, see if you can get it to connect with its built-in cert
the is some helpful stuff here you could look at - https://ylianst.github.io/MeshCentral/intelamt/
you might also need to add sectigo CA into the mix and check its showing in the intel amt in meshcommander as a trusted ca

**Comment by aggietallboy** [comment]
OK.. also pulled up the setup.bin created by the Meshcentral.
It's super light:
Current MEBx Password -- what I entered
New MEBx Password -- what I entered
PKI DNS Suffix -- this has the myserver.mydomain.com --- this just seems like it's wrong, I would think this should just be mydomain.com, and then the Configuration Server FQDN option should be defined with the myserver.mydomain.com.
User Defined Certificate Addition - SHA256, MeshCentral, and what looks like the hash of the Self-Signed MPS cert.
ME Provision Halt/Active - Stop -- I would think Start would be more appropriate

**Comment by aggietallboy** [comment]
OK... I got it!

https://www.intel.com/content/www/us/en/support/articles/000059019/software/manageability-products.html

So when DHCP option 15 matched the "real" domain "When the endpoint system’s network domain matches the configured CIRA domain, Intel AMT will not start the CIRA connection."

So the heartbeat wouldn't trigger.

I removed option 15 altogether, and lo and behold all is (mostly) working.

![image](https://github.com/Ylianst/MeshCentral/assets/10222174/12a70fb9-3a60-4d87-bfe1-fa702c44eb7d)

HW connect doesn't work here
![image](https://github.com/Ylianst/MeshCentral/assets/10222174/5e7675e6-d356-481a-a69f-14ce620f188f)

But this part works, and the remote desktop works in here.

**Comment by aggietallboy** [comment]
Looks like we can close this one out.. it's the conflicting stuff with dhcp option 15.

I've rebuilt it in Hybrid mode, and I'm working through getting everything reconnected, and the "autojoin" next.
