### ISSUE TITLE
InstallModules() installs all modules, not just missing modules (regression)

### ISSUE THREAD

**Issue by gogglespisano** [Ylianst/MeshCentral#5681]
**Describe the bug**
In translate/translate.js, InstallModules() creates a list of missingModules, but then installs all modules.

In the previous version of this code, the modules in missingModules were installed one by one.

**To Reproduce**
When the docker image is run, additonal libs are installed which weren't in the package.json list.  This issue causes all modules to be installed, not just the missing modules

**Expected behavior**
Only the missing modules should be installed.

**Screenshots**
N/A

**Server Software (please complete the following information):**
Docker Image

**Client Device (please complete the following information):**
N/A

**Remote Device (please complete the following information):**
N/A

**Additional context**
Since all modules are reinstalled, it can take quite a while for MeshCentral to startup.  The npm command has a timeout of 120 seconds, which isn't always enough when all modules are being installed.

mcrec.js uses the previous style of this function.  It should probably be updated to match this newer code once this problem is fixed.

**Comment by gogglespisano** [comment]
meshcentral.js has similar functions, but includes the following comment.

```
// Install all missing modules at once. We will be running "npm install" once, with a full list of all modules we need, no matter if they area already installed or not,
// this is to make sure NPM gives us exactly what we need. Also, we install the meshcentral with current version, so that NPM does not update it - which it will do if obmitted.
```

If all modules need to be installed, then the timeout should be increased to 300000.

There's several inconsitencies between the 3 versions of this code.  Could they be consoidated so only one copy exists?

**Comment by si458** [comment]
this was the original behaviour, it would instalkl missing packages like mysql, postgres, totp, etc...
but it was changed because @Ylianst found a bug, but its still not perfect!
so im trying to find a way around this, or just completely remove it all together, and only install the extra packages that you request, like mysql, totop, pushover, etc...

**Comment by gogglespisano** [comment]
Bug #5684 is the cause of all modules being reinstalled.
