### ISSUE TITLE
Message feature window timeout.

### ISSUE THREAD

**Issue by jfiedlerNS** [Ylianst/MeshCentral#5688]
Loving MeshCentral and feature to leave a window with message on the remote device, however today I found out, that this window has a timeout and closes itself after a few minutes. Is there a way to ensure, that the window stays active, until user closes it manually? This way I have no idea if he seen the message or not which is a shame because it looks a lot better than writing the message in notepad and leaving it open.

**Comment by si458** [comment]
amazing feature request!
it is currently hard coded as 120000,
so i can look at making it configurable when you select the 'notification' icon on the bottom right
`this.messagebox = require('win-dialog').create(this.title, this.message, this.username, { timeout: 120000, b64Image: img.split(',').pop(), background: color_options.background, foreground: color_options.foreground });`

SIDE NOTE: if you use the latest `master` docker image (or git clone from master branch and run), you can actually now send the original alert boxes which have no timeout i believe!

**Comment by jfiedlerNS** [comment]
I would absolutely love if it was configurable - I wouldn't mind if it was burried deep in server config or it could look simillar as broadcast message window between users.
![Snímek obrazovky 2024-01-12 132710](https://github.com/Ylianst/MeshCentral/assets/141926076/91616c28-42dc-482d-b97f-52c3c5f53816)

**Comment by si458** [comment]
oh wow thanks for the hint! 
so code is already in there, just need to copy+paste and change meshctrl to allow this feature!
below look ok? i dont want to allow custom times as that gets complicated, but predefined ones would be ok
![image](https://github.com/Ylianst/MeshCentral/assets/765314/68f2dd9b-7454-47fb-b14d-2022eeabc722)

**Comment by jfiedlerNS** [comment]
I mean yeah, this would be absolutely awesome! IMHO until dismissed should be default or at least having an option to set default through config file would be nice.

**Comment by si458** [comment]
sadly im going to leave it as 2 minutes for backward compatability 
as the way my luck runs, i can guarantee someone will complain 'why does the message-box vanish anymore like it use too' 🤦

**Comment by jfiedlerNS** [comment]
OK, I get that. Even knowing that the message will autoclose in 2 minutes on a first glance is very useful - currently it is not very intuitive.

**Comment by si458** [comment]
a little better designed
![image](https://github.com/Ylianst/MeshCentral/assets/765314/a8039960-c406-40af-9738-a16b2a2a3eb1)

**Comment by jfiedlerNS** [comment]
Looks great! Hoping it will make 1.1.17 release 😄

**Comment by jfiedlerNS** [comment]
Btw I noticed you are using the Device Notification feature - would live this option to apply to the "Message" button in the general tab of the device as well - I found out, that users tend to notice large window with their IT admin picture more than random windows notification that they often close without realizing what it said. Also the notification feature isn't really working for me right now.

**Comment by si458** [comment]
if its not working for some reason, please do open a bug report with all details (**follow the template plz**)

i will have a think about the 'message' button on the general tab,
as really thats just to display a quick message and timeout, not permanent

maybe another button saying 'Notification' which opens up the 'device notifications' panel to allow type/title/timeout/etc ?
again it helps with backwards compatability, so things dont change, but more new features just in different places

**Comment by jfiedlerNS** [comment]
I mean would it be that disruptive to add option to choose how long the window stays open to the message button as well? For example if user leaves their computer and lets me work on some issue they have, I might want to leave some additional info for them and I have no way knowing whether the user will return to their computer in the 2 minute window.

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/6a7c740d-cb40-4353-a8d4-29340f9640d4)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/2cdcf00a-0f12-4144-ba20-1846a893f1d5)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/aab38fc0-f9e1-4fe8-847f-796e08f0db61)

**Comment by jfiedlerNS** [comment]
Amazing! Thank you very much.
