### ISSUE TITLE
https://meshcentral.com/ change desciption or tag or agentid bug

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshCentral#569]
Hi Ylianst,
I have started to use https://meshcentral.com . I have added an agent. I have try to change agent's name or description or tag. When i click Ok button the iste say me Server disconnected, click to reconnect. After, when i try to access to site, the site is unreachable. After 2 minutes i try to log on site i can logged on. The value was changed.
But there is a bug in your site. Every try to save values site say Server disconnected, click to reconnect. Can you fix this bug?
Thanks

**Comment by whalehub** [comment]
This issue has already been fixed in v0.4.2-i (#567), the official website just isn't using the latest version (yet).

**Comment by Ylianst** [comment]
Ok, will just close this one as I am sure it's fixed. If you still see the problem, please re-open.

**Comment by senolkehya** [comment]
Thanks so much. The bug seems fixed.
