### ISSUE TITLE
Something wrong inside meshcentral-config-schema.json

### ISSUE THREAD

**Issue by sammyke007** [Ylianst/MeshCentral#5697]
**Describe the bug**
meshcentral-config-schema.json seems to be off somewhere as using this schema in VScode works in "settings" and eg. "smtp", but not for "domains"

I use this schema:
`  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",`

**To Reproduce**
1. Try to CTRL+space in the "domain" part and it won't tell you about the possible keys or try to hover over a key in the "domain" part and it won't show the description of the keys.

VScode 1.85.1
Windows 11

Working:
<img width="189" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/33524412/aa76d86c-d87e-4cb1-bf98-9ec4b6a9b4d0">

Not working:
<img width="145" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/33524412/afa554d0-4a04-482b-a041-175e05fed4da">

@si458 as requested

**Comment by si458** [comment]
weirdly enough,
create `"domaindefaults": { },` above `"domains": {` 
then CTRL+SPACE inside the brackets, and you get ALL the options?
the `domaindefaults` is so you can apply loads of values to different domains (if you are multi-tentant), 
and all that does is reference whats inside domains?

**Comment by sammyke007** [comment]
<img width="153" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/33524412/b2386f1d-ed64-4387-9df0-c83a36b7fdbc">

Still doesn't work over here...

**Comment by si458** [comment]
who the hell knows with VSCode? 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/59fa5dc1-ac6f-4b14-a0d5-4d27021a1eaa)

**Comment by si458** [comment]
fixed for you 👍 https://github.com/Ylianst/MeshCentral/commit/1295af4677f9a6674dfa9606f146a25fca22c205
should be able to close VScode, reopen, let it read the json schema again as it should be pointing to the master anyways!

**Comment by sammyke007** [comment]
Yes sir, that's OK!

One last small issue:
commented entries are "not allowed":

<img width="167" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/33524412/66af74e3-5c7a-4779-b369-5fa986690934">

**Comment by si458** [comment]
erm ill have to look into that for you!
ive never designed a json schema before, all the new options ive put in, ive just copied n pasted from ones already in there!

**Comment by sammyke007** [comment]
Very strange. I can comment every line without errors, except in the "agentCustomization" part.

**Comment by si458** [comment]
fixed, the was 33 extra additionalProperties listed in different places, so some worked and some didnt...

**Comment by sammyke007** [comment]
FIXED!

**Comment by si458** [comment]
dont forget to donate https://www.si458.co.uk/2024/01/05/donation/ 🙏  ❤️
