### ISSUE TITLE
Windows Client requires AV unload

### ISSUE THREAD

**Issue by bvessey** [Ylianst/MeshCentral#57]
Currently using Trend Micro for our endpoints.  The only way I've been able to get the windows agent to install is to temporarily disable the anti-virus and run the "Interactive Only" installer.  Please advise if there's any additional info that you need.

**Comment by Ylianst** [comment]
Thanks for the report. I will see what I can do about white listing the Mesh Agent.

**Comment by bvessey** [comment]
I'll try to dig a bit further, but it looks like the problem might be related to how the installer creates / registers the service as we can re-enable the AV after install without any issues.  Since we're using the enterprise product with a central management console we could add exceptions as outlined in the link.  I'll try to reproduce the problem scenario and see if there are any logs indicating what's being blocked and why.

**Comment by whalehub** [comment]
@bvessey @Ylianst Did you manage to figure out what's causing the issue?

**Comment by bvessey** [comment]
Sorry, no. The higher-ups here decided to renew our existing commercial solution so I'm no longer testing at work.

**Comment by whalehub** [comment]
@Ylianst I think the issue can be closed now.

**Comment by openmoto** [comment]
Having same issue here with TrendMicro.
On the phone with their support team, will update if we find a fix.

**Comment by openmoto** [comment]
Hi Guys,
This seem to be a firewall issue.

I tried to start the windows service when I noticed it was stopped and I got the error :
"Windows could not start the Mesh Agent background service on Local computer.
 Error 1067: The process terminated unexpectedly."
 
If you right click the service go to Properties then Log On :
 Change from "Local system account + Allow service to interact with desktop"
 To "This account : with credential for local admin"
 Apply > Ok
 
 Right click and start service just works.
 Changing it back to "Local system account + Allow service to interact with desktop" then try to start service fails again.
 
 We disabled trendmicro modules one by one since there is no logs to show what's actually happening..
 After disabling the firewall, the agent service just started by itself.

Will have to deploy on a few computers and see if it works after they're updated with the new settings.

**Comment by openmoto** [comment]
Better fix but not tested yet:

This is for those using Trend Micro Apex One (Office Scan) I did not experience this with Kaspersky Endpoint security.

Under Apex one dashboard. 
Go to Agents > Firewall > Policies >
Under exception , click ADD

Enter name : MeshAgent
Application :Specify application full path C:\Program Files\Mesh Agent\MeshAgent.exe
Action : Allow network traffic
Direction : select both inbound and outbound.
Protocol TCP/UDP
IP address(es) : All IP Addresses

I'll test this as well and update.

**Comment by openmoto** [comment]
Sorry for the long delay.
I had created a public server and sent trendmicro the agent to test with.
Here is the response from their dev team after testing:

> " Apex One firewall feature "AppFilter" is blocking the MeshAgent service from starting where in when the application sent a packet, application filter will pend this packet until finished to calculate the hash of application. 
> 
> Disabling the AppFilter feature will address issue. You will set the following to "OfcPfwAppFilter=0 in [Global Setting] in case that you're using on premise."

For ApexOne as a service, the dev team will have to update this on the back end with your permission.

I don't think the solution they have offered is a good one, disabling a component of your security product to allow an application doesn't seem like a 'safe' fix.
I don't understand why trusting the application isn't sufficient, even with exclusion added.

@Ylianst I think at this point it's safe to close this issue.
Note that this is a Trend Micro **ApexOne** specific issue. I did a trial of trend micro maximum security and Kaspersky Endpoint Security and did not experience this issue.

**Comment by Ylianst** [comment]
Someone just pointed me to [virustotal.com](https://www.virustotal.com) which checks a executable against a lot of different anti-virus products. One interesting result is that the 32bit version of the MeshAgent is marked as bad by many but not all products. However, the 64bit version shows clear by all products. So, the 64bit version of the MeshAgent should be used when possible. In the pictures below, top one is 64bit, bottom one is 32bit. Hope it helps. I will close this I am not sure what else to do. Feel free to re-open if there is something I may fix in this area.

![MC2-V1](https://user-images.githubusercontent.com/1319013/57487514-a78fe700-7265-11e9-95e2-1c32f4b7fbd3.png)

![MC2-V2](https://user-images.githubusercontent.com/1319013/57487519-abbc0480-7265-11e9-90e8-4029632f3a8d.png)
