### ISSUE TITLE
Help to disable a feature.

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#570]
Guys, good morning!

can you help me? I need to disable the "auto" flag in Mesh to prevent my technicians from accidentally clicking and sending requests to the entire computer park, I tried to comment the line of code in the default.heandlebars file but it unconfigured the whole system, can you help me?

**Comment by Ylianst** [comment]
I am not sure I understand the problem. Can you send a screenshot of the feature you need disabled? Thanks.

**Comment by Ylianst** [comment]
Hi. You can try to add style="display:none" in the label. Before:

`<label><input type="checkbox" id="autoConnectDesktopCheckbox" onclick="autoConnectDesktops(event)" title="Automatic connect" />Auto&nbsp;</label>`

After:

`<label style="display:none"><input type="checkbox" id="autoConnectDesktopCheckbox" onclick="autoConnectDesktops(event)" title="Automatic connect" />Auto&nbsp;</label>`

However, this is an interesting point. I am going to add code to remove the "Connect All" and "Auto" controls when there are more than 16 devices on the screen.

One more thing. I notice that you seem to have a Spanish version of MeshCentral. It would be great to have the open source version support many languages. If you can share what tools and techniques you used to translate the web site, it would be appreciated. Thanks.

**Comment by geanferrani123** [comment]
Hello Ylianst, good afternoon!

All right?

Actually not Spanish, this language is Portuguese - Brazilian.

If you need my help for this endeavor I will be glad to collaborate for sure, as this is my native language, I made the modification manually, going file by file doing the translation.

**Comment by geanferrani123** [comment]
On your suggestion, I will test and return to you.

**Comment by geanferrani123** [comment]
Ylianst, taking advantage, may I ask you a question?

I know it has nothing to do with this topic but I wanted to know what's new in this new update that came out .. I tried to learn the commits but could not understand, could you please explain?

**Comment by geanferrani123** [comment]
It worked, thank you very much

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.2-r with a new "Chat & Notify" device group permission as you originally asked. This should close this issue. Let me know if it works for you.

![MC2-ChatAndNotify](https://user-images.githubusercontent.com/1319013/66954800-f4969700-f015-11e9-8b68-cbbe4f7ec58f.png)

**Comment by MailYouLater** [comment]
@Ylianst: I don't see the connection between your last post here, and the rest of the conversation. Was it perhaps intended to go on #534?

**Comment by geanferrani123** [comment]
Very good, i will test and give you an answer.

**Comment by Ylianst** [comment]
@MailYouLater Your right. I posted this in the incorrect issue. I will close this issue. Please respond on #534 about the new chat & notification permission feature.
