### ISSUE TITLE
Quick buttons not working

### ISSUE THREAD

**Issue by VINISHVV** [Ylianst/MeshCentral#5700]
Quick connect buttons are not working in MC-1.1.8

![image](https://github.com/Ylianst/MeshCentral/assets/65057910/b7a7ecdf-5410-44f9-9238-953bdf45805a)

**Comment by si458** [comment]
fixed! sorry about this! missed 1 single onmouseup event!
you can apply the patch manually to default.handlebars (its only 1 word in 2 places)

**Comment by VINISHVV** [comment]
@si458 - Thanks, I think changes required on default-min.handlebars too

**Comment by si458** [comment]
the minify files are built automatically when the npm/docker images are built, they arent built on the fly sadly
but for the moment you can set `"minify": false` under `domains` and restart your server!

**Comment by itpilot** [comment]
sorry for the noob question guys

fixed! sorry about this! missed 1 single onmouseup event! - Ok Great
you can apply the patch manually to default.handlebars (its only 1 word in 2 places)

What IS the Word and what Places in the default.handlebars File?

Any help greatly appreciated

**Comment by si458** [comment]
@itpilot you can check the commit - https://github.com/Ylianst/MeshCentral/commit/757cef3f290f315fcb9189cd398542a02d997dbb

its lines 6329 and 6331, just simply change `onclick` to `onmouseup` inside `node_modules/meshcentral/views/default.handlebars`

i will ask @Ylianst to do another release soon, as i missed up a few other things too 🤦

**Comment by itpilot** [comment]
Thank you, much appreciated
