### ISSUE TITLE
Config setting to disable BitLocker key backup

### ISSUE THREAD

**Issue by Sketch6307** [Ylianst/MeshCentral#5702]
In relation to #5670 , can this feature to back up BitLocker keys please also have a configuration setting added to disable it? We back up recovery keys to AD already, so would rather not duplicate this data in MeshCentral.

Thank you!

**Comment by si458** [comment]
erm i can look into it?
when you run `sysinfo` on the console tab it gets the data there n then
meshcentral doesnt actually store the `sysinfo` data in its database, so in a way the password is never remembered! only shown when u ask for it

**Comment by Sketch6307** [comment]
Ah, never mind then, I think that's fine if it's only retrieved/displayed on demand. Thanks again :)
