### ISSUE TITLE
Copying and pasting files in My Files dont work

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshCentral#5704]
**Describe the bug**

Can`t copy and paste files between My Files folders

**To Reproduce**

1. Go to Myfiles
2. Select a file that you want to copy
3. CLick Copy
4. Go to another folder
5. click Paste
6. Confirm pasting of file

**Expected behavior**

I expect a copy of file

**Comment by si458** [comment]
huh? weird? i see it too? never noticed?
will look when back home

**Comment by si458** [comment]
Fixed 👍 
reverted part of a commit that was pushed a while back https://github.com/Ylianst/MeshCentral/commit/636f801bd7667d4389813eef2b81c6efbe54132d

**Comment by wireks** [comment]
So will be fixed in jest release ?

**Comment by si458** [comment]
Yes next release, unless u want to change the 2 lines that's caused the problem manually for a quick fix :)

**Comment by wireks** [comment]
on 1.1.20 still dont work

**Comment by si458** [comment]
are you sure this is the 'My Files' tab ? as it works fine here no problem?

**Comment by wireks** [comment]
Yes i`m sure. I can send you movie :D

**Comment by si458** [comment]
> Yes i`m sure. I can send you movie :D

plz

**Comment by wireks** [comment]
https://mbitpl0-my.sharepoint.com/:v:/g/personal/mbryll_mb-it_pl/EfU8EZIQxKBLkjZISvfZ4CUBPvd2XWhr4FmcTnIYeG95cQ?e=2hzKQj

**Comment by si458** [comment]
hmm im noticing a few weird issues now with the 'My Files'
i think i fixed a copy+paste bug with 'Files' rather than 'My Files'

**Comment by si458** [comment]
all fixed again! it appears when you have a BLANK devicegroup, the folder doesnt actually exist until you upload/create a folder
in theory it should of created the folder too IF you use the copy/cut+paste!

so fix pushed will be in next release
OR
in the mean time, to fix the issue, just upload something random into the devicegroup, OR create an empty folder,
then you can use the copy/cut+paste as expected!
OR
copy+paste the single line into your `meshuser.js` and restart to temp fix it
