### ISSUE TITLE
Feature Request: Order of groups by name

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#571]
I would imagine that there's UUIDs behind every group that's created and that is what's used to show the groups in the GUI, but would it be possible to order the name of the groups by their name? For example I have about 12 groups at the moment, but there's one group that I want to ensure remains at the top of the list, so I name it "AAA_something" or "000_something" but it remains where it is in the list.

Not a biggie - more of a nicety to be honest.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.2-o with a fix for this. Groups would only re-order correctly after you hit refresh on the web page, now they re-order right away. Also, all empty groups are always placed at the bottom. Let me know if this works.

**Comment by D4V3M0NK** [comment]
Lovely, thanks Ylian.
