### ISSUE TITLE
Agent stop connecting, new Agents don't add to Dashboard.

### ISSUE THREAD

**Issue by JSuenram** [Ylianst/MeshCentral#5711]
**Describe the bug**
Since 1.16 up to 1.19 when we install new Agent, they never show up in the Dashboard.
Some Agents to no longer connect/get online. While about 650 other agents are just fine.

**To Reproduce**
Install Agent and let Service start

**Expected behavior**
Should show up in Dashboard as new/online.

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: LX Container
 - Network: Behind NGINX ReverseProxy
 - Version: 1.1.19
 - Node: 16.6.0]

**Client Device (please complete the following information):**
 - Device: Notebook, VM
 - OS: Windows, other not tested
 - Network: WAN
 - Browser: Google Chrome]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: MAC
 - OS: MACOS
 - Network: WAN
 - Current Core Version (if known): Current Core: Dec 9 2022, 3185282479

**Your config.json file**
```
{
    "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
    "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
    "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    "settings": {
        "cert": "mesh.it-XXX.com",
        "_ignoreAgentHashCheck": true,
        "_WANonly": true,
        "_LANonly": true,
        "sessionKey": "XXX&Co.KG",
        "port": 443,
        "aliasPort": 443,
        "redirPort": 80,
        "redirAliasPort": 80,
        "relayPort": 453,
        "agentsInRam": true,
        "trustedproxy": [
            "10.255.14.1"
        ],
        "_tlsOffload": "10.255.14.1",
        "desktopMultiplex": false,
        "authlog": "/etc/meshcentral/auth.log",
        "plugins": true,
        "WebRTC": false,
        "Compression": true,
        "WsCompression": true,
        "AgentWsCompression": true,
        "AllowLoginToken": true,
        "_AllowFraming": true,
        "CookieIpCheck": false,
        "CookieEncoding": "hex",
        "_noAgentUpdate": "1",
        "autoBackup": {
            "mysqlDumpPath": "/etc/bin"
        },
        "webrtcConfig": {
            "iceServers": [
                {
                    "urls": "stun:stun.services.mozilla.com"
                },
                {
                    "urls": "stun:stun.l.google.com:19302"
                }
            ]
        },
        "mySQL": {
            "host": "10.255.14.101",
            "port": "3306",
            "user": "meshcentral",
            "password": "XXX-XXX-XXX",
            "database": "meshcentral"
        }
    },
    "domains": {
        "": {
            "titlehtml": "",
            "title": "it NGO GmbH & Co. KG - Remotesupport",
            "title2": " - RemoteSupportTool - V 0.01a",
            "titlepicture": "title-mycompany.png",
            "welcomeText": "Willkommen zum Fernwartungs und Webmeetingportal.",
            "welcomePicture": "welcome.png",
            "LoginPicture": "welcome.png",
            "GeoLocation": false,
            "CookieIpCheck": false,
            "x-frame-options": "allow-from *",
            "agentConfig": [
                "skipmaccheck=1"
            ],
            "agentCustomization": {
                "displayName": "itNGO - QuickSupport Agent",
                "description": "itNGO - QuickSupport Agent background service",
                "companyName": "itNGO GmbH & Co. KG",
                "serviceName": "itNGO - Agent",
                "foregroundColor": "#FFFEFE",
                "backgroundColor": "#464646",
                "image": "welcome.png",
                "remoteMouseRender": true,
                "fileName": "itNGO-Agent"
            },
            "userConsentFlags": {
                "desktopnotify": true,
                "terminalnotify": true,
                "desktopprompt": false,
                "terminalprompt": false,
                "desktopprivacybar": true
            },
            "desktopPrivacyBarText": "{1} - ist mit Ihrem System verbunden!",
            "minify": true,
            "_newAccounts": true,
            "_userNameIsEmail": true,
            "AllowHighQualityDesktop": true,
            "CertURL": "https://mesh.it-ngo.com:443",
            "ManageAllDeviceGroups": [
                "J.XXX",
                "U.XXX"
            ],
            "agentInviteCodes": true,
            "AgentSelfGuestSharing": true,
            "mstsc": true,
            "ssh": true,
            "auth": "ldap",
            "ldapUserName": "sAMAccountName",
            "_ldapUserBinaryKey": "objectSid",
            "ldapUserKey": "sAMAccountName",
            "ldapOptions": {
                "url": [
                    "ldaps://RZA-DC01.internet.pc-XXX.info:636",
                    "ldaps://RZB-DC01.internet.pc-XXX.info:636"
                ],
                "bindDN": "CN=QueryLdap,OU=XXX,DC=internet,DC=pc-XXX,DC=info",
                "bindCredentials": "XXX",
                "searchBase": "DC=internet,DC=pc-XXX,DC=info",
                "searchFilter": "(&(sAMAccountName={{username}})(objectClass=organizationalPerson))",
                "tlsOptions": {
                    "rejectUnauthorized": false
                },
                "reconnect": true
            },
            "_altmessenging": {
                "_name": "Ticket",
                "_url": "https://helpdesk.it-XXX.com/index.php?section=bug&sub=edit&init=1&backTo=main"
            },
            "customui": {
                "desktopButtons": {
                    "exec5": {
                        "name": "Leistung erfassen",
                        "action": "dialog:dialog1"
                    }
                },
                "terminalButtons": {
                    "exec6": {
                        "name": "Leistung erfassen",
                        "action": "dialog:dialog1"
                    }
                },
                "dialogs": {
                    "dialog1": {
                        "logmsg": "Leistungsdialog Eingabe",
                        "title": "Schnellerfassung Leistung",
                        "text": "Bitte getane Arbeiten dokumentieren...",
                        "buttons": 1,
                        "elements": {
                            "test1": {
                                "name": "Titel",
                                "type": "text"
                            }
                        }
                    }
                }
            }
        }
    },
    "_letsencrypt": {
        "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
        "email": "support@it-XXX.com",
        "names": "mesh.it-XXX.com",
        "production": false
    },
    "smtp": {
        "host": "XXX",
        "port": 587,
        "from": "XXX",
        "user": "XXX",
        "pass": "XXX",
        "tls": false
    }
}
```

**Comment by si458** [comment]
you say `REMOTE DEVICE: MACOS`,
are you saying ONLY MAC devices, when you run the agent and connect, dont show up in your web ui?
or does this include windows devices?
have you tried restarting your meshcentral server and seeing if they appear when the remote user downloads the exe and clicks connect?

**Comment by JSuenram** [comment]
> you say `REMOTE DEVICE: MACOS`, are you saying ONLY MAC devices, when you run the agent and connect, dont show up in your web ui? or does this include windows devices? have you tried restarting your meshcentral server and seeing if they appear when the remote user downloads the exe and clicks connect?

Sorry to be unclear... no, it does not matter which OS. I can see in Server-Trace "agent" that the Clients Connect.

`Zeit, Quelle, Nachricht
"10:58:57","agent","Soft disconnect 9MNCxSSVlLqPzIhaau@Pn$Orr89ZrlV6cIFQMEeTbH$oH4HJCjsDd5Zt14YDnE8Q (145.253.188.100:15957)"
"10:58:24","agent","Verified agent connection to HhHjvSUIOh9rvdxfSefrjgrY9OCXaS$wnRJxjJJMLTnFIwVAirAtN7aNH8Sg@0Bq (37.138.51.129:40842)."
"10:58:24","agent","New agent at 37.138.51.129:40842"
"10:58:20","agent","Agent disconnect HhHjvSUIOh9rvdxfSefrjgrY9OCXaS$wnRJxjJJMLTnFIwVAirAtN7aNH8Sg@0Bq (37.138.51.129:32224) id=Unknown"`

But never gets "state" Online in Dashboard, or if its a new one gets an entry in Dashboard.

**Comment by si458** [comment]
we havent changed anything to do with the agent connect behaviour? so it must be something to do your reverse proxy maybe?
have you tried updating nodejs to a supported? like 18/20 - https://endoflife.date/nodejs

**Comment by JSuenram** [comment]
What I can say so far, there are no errors about connection in the debug-outout.... starting agent with command "run" gives 

`Control Channel Idle Timeout = 120 seonds
Invalid server signature`

and never shows up in Dashboard, while a working Agent gives this after seconds....

`Connecting to: wss://mesh.it-xxx.com:443/agent.ashx
2024-01-19 11:47:22 AM: Control Channel Idle Timeout = 120 seconds
Connected.
Server verified meshcore... Launching meshcore...`


Already tried with
`    "ignoreAgentHashCheck" : true,`
in Config, but behavior does not change....

**Comment by si458** [comment]
`Invalid server signature` basically means the server signature thats INSIDE the exe DOESNT match the signature that the servere replys with when the agent connects to meshcentral.
you could try copying over a working exe from another device, and running it on the computer that doesnt work?
is that the same thing?
you could also try visting `https://mesh.it-xxx.com` in the web browser on the machine that doesnt work and see what certificate it gives on the remote device?

**Comment by JSuenram** [comment]
Ok, cert in Browser is on working and non working client the same.
Copied an Agent-File from a working client over the non-working. Issue is the same.... does not connect....

**Comment by JSuenram** [comment]
> `Invalid server signature` basically means the server signature thats INSIDE the exe DOESNT match the signature that the meshcentral server replys with when the agent connects to meshcentral. so its the agent thats disconnecting and NOT the server disconnecting it you could try copying over a working exe from another device, and running it on the computer that doesnt work? is that the same thing? you could also try visting `https://mesh.it-xxx.com` in the web browser on the machine that doesnt work and see what certificate it gives on the remote device?

Well... you are right and I am "DUMB".... we have a script which replaced our certs, which I made a mistake in. This lead to putting the wrong KEY-File inside MeshCentral.

This lead to every Agent which was created after last renewal had the wrong Cert-Hash... after replacing the Key-File and redownloading agent, created after Cert-Replace, everything is working again....

**Comment by si458** [comment]
@JSuenram live and learn! automation is meant to make things easier but some how it always bites us in bum! glad its sorted! 👍
