### ISSUE TITLE
MeshCentral Agent Script or Action Scheduler

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#5713]
**Is your feature request related to a problem? Please describe.**
No my request is not related to a problem just a feature I see in enterprise RMM solutions which I would also like for MeshCentral

**Describe the solution you'd like**
The ability to schedule certain tasks (like bash/powershell scripts, system update execution or any predetermined tasks) or be able to set timers for them from the meshcentral server.

**Describe alternatives you've considered**
registering tasks using crontab or systemd timers but this makes the work a lot more, needing to be manually installed on each device, with MeshCentral I could automate this.

**Additional context**
I generally agree with this old Reddit thread: https://www.reddit.com/r/MeshCentral/comments/dbnobb/remote_scriptingscheduling/

**Comment by si458** [comment]
DUPLICATE #5713
