### ISSUE TITLE
Setting agentaliasport doesnt work for the linux agent (it works for windows)

### ISSUE THREAD

**Issue by ektorasdj** [Ylianst/MeshCentral#5719]
Hello and thank you for this fine tool!
I have come across one small and not so important issue. 
When setting agentaliasport to a port number it works ok for the windows agent ( the agent that you download after the change has the correct port on its settings) but the wget command for installing the agent on linux has the aliasport (of the web server) and not the agentaliasport. If i manually change the port on the command before inputting it to the linux machine it works as intended.
As you can understand i have different ports for the webui and the agent to better protect my meshcentral set up.

**Comment by si458** [comment]
Hi, thank you fir reporting this, this is a meshcentral issue not a meshagent as it is the webui is at fault here, will look into this and report back for you

**Comment by si458** [comment]
can u specify/share screenshot of which wget command you are seeing thats invalid?
is it the whole wget command for linux install?
or the wget command for linux binary?

**Comment by si458** [comment]
after checking the code, this is all correct and no bug
the wget command simply downloads the install script from the web server port as expected
the `agentaliasport` and `agentport` are used for the agents to connect to the server for control!
NOT to be used to download the meshagent software, that is done over the standard web port
