### ISSUE TITLE
Embedding the web application using MAC address as device key

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#572]
Hi,

I have a PC monitoring application and i have access to the mac address of the PC, and the PC also exist in Meshcentral and i want from my monitoring app to click a button which opens a popup and establish the remote connection to that PC via MC using mac address not the node id. 

e.g. https://mesh.example.com/mac=MM:MM:MM:SS:SS:SS?...

And to show a login interface in the popup if the user is not logged in with the meshcentral credentials but after auth show only that PC that they selected (i can't use login tokens as meshcentral is installed on a server where users don't have access to generate tokens via comand line);

Is it possible when embedding meshcentral onto another application to identify a node by it's mac address?

Or is there a way to identify a specific PC other than the node id?

I hope i've explained it well.
Thanks

**Comment by Ylianst** [comment]
Interesting, yes, I can probably do this.

**Comment by dinger1986** [comment]
can embed with node id, dont see the need for this @si458 maybe if someone wants to embed they can add this?

**Comment by si458** [comment]
this wont be implemented as you need to use the deviceid im afraid
