### ISSUE TITLE
"CIRA" instead of "AMT" under Connectivity column of My Devices

### ISSUE THREAD

**Issue by RyGuy-NCC1701** [Ylianst/MeshCentral#5722]
**Description**
Under the My Devices page, in the Connectivity column, "CIRA" is appearing instead of "AMT" for many devices using AMT over local network.

**To Reproduce**
Just view the My Devices page and this behavior should be visible under the Connectivity column.

**Expected behavior**
Text should show "Agent + AMT" or "AMT" or just "Agent" depending on configuration choices. (I have several machines without vPro chips, so those just run the software agent, and other machines have been imaged without reinstalling the software agent, so only AMT should show on those, naturally.)

**Screenshots**
Attached a screenshot to show how not all machines records appear to be affected.
![Screenshot 2024-01-22 092025](https://github.com/Ylianst/MeshCentral/assets/157384808/921fd7a0-10d9-4d1a-8365-105ec7e44c1e)

**Server Software (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: [e.g. Docker]
 - Network: LAN
 - Version: 1.1.19
 - Node: 14.17.1

**Client Device (please complete the following information):**
 - Device: Dell Optiplex desktops, a variety of models
 - OS: Windows 11
 - Network: Local to MeshCentral
 - Browser: Microsoft Edge and Google Chrome
 - MeshCentralRouter Version: N/A

**Config.json file**
```
{
   "settings": {
      "cert": "SERVERNAME",
	  "RedirPort": 80,
	  "Port": 443,
      "_minify": true, 
      "clickonce": true, 
      "webrtc": true, 
      "selfupdate": true
   }, 
   "domains": {
      "": {
         "title": "TITLE MAIN", 
         "title2": "MeshCentral",
		 "titlePicture": "LogoBackground.png",
		 "loginPicture": "Company.png",
         "AmtAcmActivation": {
			"log": "amtactivation.log",
			"certs": {
				"SERVERNAME": {
					"certpfx": "FullCert.pfx",
					"certpfxpass": "123456"
					}
				}
			},
         }
	}
}
```

**Comment by si458** [comment]
thanks for reporting! this was caused by https://github.com/Ylianst/MeshCentral/pull/5691 and you can revert this commit if you want
how do you activate your machines?
do you activate them into CCM or ACM?
i dont have a certificate so it might be hard for me to try and fix this but i will try my hardest as i caused it im sorry!

**Comment by RyGuy-NCC1701** [comment]
We activate into ACM with a certificate. As long as the functionality is not impacted I'm in no rush to change this, so I don't think we necessarily need to revert the commit if it's possible to correct it down the road.  It just gave me a scare this morning, lol!  I appreciate you looking into it - most of this stuff is well above my head.

**Comment by si458** [comment]
do the computers show the correct powerstate at all? like soft-off, hibernate, etc?

**Comment by RyGuy-NCC1701** [comment]
I believe so - which part of the interface are you referring to?  I can see the agents and AMT are "connected" and under the device record itself it shows the black bar with context details "powered on since xxxx".

**Comment by si458** [comment]
sorry the General tab when you pick a device, under the BIG icon it will show you 'connected' with like a power state
and also the power graph underneath should show colours or all black etc?

**Comment by RyGuy-NCC1701** [comment]
Ok yeah, I always see the "Connected" info, but I've never seen any power state info there.  The 7-day graph seems to be working - all black on most machines, and colors on the ones that have had some down-time recently.

**Comment by Ylianst** [comment]
Hi. This is not a bug, when you see "AMT" it indicates that MeshCentral is directly communicating to a Intel AMT device on the local network. When you see "CIRA", that stands for "Client Initiated Remote Access" and it's the Intel AMT technology that allows AMT to connect back to a server (in this case your MeshCentral instance) over the Internet.

So, if you see CIRA, that is great new. AMT has it's encrypted tunnel connected to the server and it's keeping that tunnel connected to you can send commands to Intel AMT devices. Sorry for the confusion, CIRA is a term heavily used by Intel folks. THe official name for it was supposed to be "Intel Fast Call for Help", but I don't think that name ever caught on.

Hope that helps,
Ylian

**Comment by RyGuy-NCC1701** [comment]
Yes, I understand what CIRA stands for - but I always understood that it was for tunnelling back to the server for out-of-band machines and I thought it was something discrete I had to activate.  I don't mind if the CIRA tunnel is active for PCs on my local LAN, it just startled me to see most of my devices (but not all) suddenly displaying CIRA where they said AMT before.  The unexpected change caught me off guard, in addition to the fact that many machines continued to show AMT instead.  I thought it might be something going wrong, or some bad actor making changes that I didn't understand, since previously I'd never seen the CIRA label on my devices.  Is there a reason some machines are taking longer to exhibit this change?  And also, is something mechanical/functional actually being changed with the connection to the server?  I don't see any options in a device group configuration to enable or disable new CIRA functionality, and even in groups where I set "CIRA Setup" to "Don't connect to server" they're still showing mostly as CIRA instead of AMT...

**Comment by si458** [comment]
sorry for delay, ive just tested here with a AMT v7 machine, 

ive setup a group as meshagent,
set AMT in group setting with setting 'dont connect with cira'
added device with meshagent,
activated ACM manually from bios (changed pass, set dns suffix to my laptops internal dns name i set with meshcentral)
meshcentral then activated ACM fully for me, and meshcentral is showing Agent+AMT

but it does seem you cant change devices that had cira activated to NOT use cira, without fully de-activating the group then reactivating the group

i will check with @Ylianst if this is correct?

**Comment by si458** [comment]
HUH, the device has just randomly changed to Agent+CIRA, even tho I did ask the group to NOT use connect with cira,
and indeed the intel amt panel shows no CIRA information so i do think i did a boo boo somewhere!

**Comment by si458** [comment]
OK FIXED THE ISSUE I BELIEVE! `// Set power state - connType: 0 = CIRA, 1 = CIRA-Relay, 2 = CIRA-LMS, 3 = LAN`
i had changed the `fetchPowerState` to insert CIRA as the device type as this was expected so it could get the power states of CIRA devices correctly
but it appears the Intel AMT devices that have CONNECT WITHOUT CIRA ALSO calls the same function!?
so we just needed to do a check on what type of connection we use then set the device type accordingly
