### ISSUE TITLE
Show optional notification on desktop/terminal/files disconnect

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#574]
Guys, good morning!

Since I didn't find the first topic I opened, I'm opening this topic with the same subject again.

I would like to suggest some improvements, they are:

- A bar at the top of the screen indicating that the technician is still logged on to the workstation and allowing the user to disconnect the technician, a suggestion is to put a kind of X for the user to click and disconnect the technician, so the user will know whether or not the technician is still connected to the workstation. Here's an example:

![image](https://user-images.githubusercontent.com/55212206/66924319-c2c70580-f000-11e9-8b94-8a8fc180fc8a.png)

- Another suggestion is the possibility for the technician to change remote sessions through "subtabs" within the system itself, without having to open another browser tab for that, I think LogMein has this feature.

- Another suggestion is when the technician disconnects from the machine, a notification similar to the notification below appears to let the user know that the technician has terminated remote access.

![Sem título](https://user-images.githubusercontent.com/55212206/66924987-02dab800-f002-11e9-906b-ecf06c834c4d.png)

**Comment by MailYouLater** [comment]
Please edit your opening post to remove the parts that are already covered in the previous ticket you submitted about them: #509.

**Comment by Ylianst** [comment]
1.The top bar is covered in #509 and is coming with the next version of the MeshAgent. Hopefully in the next few days or next week.
2. Not sure I understand. If you have a screen shot or details on this request, would be appreciated.
3. Yes, I can work on adding that.

**Comment by geanferrani123** [comment]
Regarding topic 2 that I mentioned, unfortunately I don't have it.

Let me try to explain:

As far as I know, if a technician needs to open more than one simultaneous remote connection, he needs to open a new browser tab (Microsoft Edge, Google Chrome, Mozilla Firefox), my suggestion would be as follows:

A kind of signal that allows the technician to click and have direct access to the registered machines so that, within the same browser tab, have 2 or more remote access at the same time.

**Comment by geanferrani123** [comment]
Ylianst taking advantage, is there any way I can talk to you directly? an email or something?

**Comment by geanferrani123** [comment]
Ylianst, is there any way I can talk to you directly? an email or something?

**Comment by Ylianst** [comment]
For issue 2, I get a general idea but would like to know how the user interface would look like. If you have a diagram. Regardless, it's going to be a lot of work to make this happen.

"A kind of signal that allows the technician to click and have direct access to the registered machines so that" - What is the "kind of signal" and what are "registered machines" (all of them)?

For direct contact, I have a [new contact page](https://www.meshcommander.com/contact-information) with a PGP key. However, I prefer GitHub/Reddit as the community can participate in the discussion. Email is great if you find any security issues, etc. I already get a lot of mail of people wanting personalized support, I would be rather use a public platform this this.

**Comment by geanferrani123** [comment]
> Para a edição 2, tenho uma ideia geral, mas gostaria de saber como seria a interface do usuário. Se você tem um diagrama. Independentemente disso, será muito trabalho para fazer isso acontecer.
> 
> "Um tipo de sinal que permite ao técnico clicar e ter acesso direto às máquinas registradas para que" - Qual é o "tipo de sinal" e o que são "máquinas registradas" (todas elas)?
> 
> Para contato direto, tenho uma [nova página de contato](https://www.meshcommander.com/contact-information) com uma chave PGP. No entanto, eu prefiro o GitHub / Reddit, pois a comunidade pode participar da discussão. O e-mail é ótimo se você encontrar algum problema de segurança, etc. Eu já recebo muitas mensagens de pessoas que desejam suporte personalizado; prefiro usar uma plataforma pública para isso.


Hello Ylianst, good morning!

Actually, I would like to ask you more about other things, such as the Information Technology job market there in the United States, among other things.

**Comment by Ylianst** [comment]
Oh. Sorry, I am really not qualified on these topics and already quite busy. I am sure others online can help better and have more time that I have.

**Comment by Ylianst** [comment]
Ok. I am going to make this topic just about the 3rd item. Showing a notification when disconnecting. Please open separate issues for different topics in the future.
