### ISSUE TITLE
MeshMessenger customization 

### ISSUE THREAD

**Issue by aftechro** [Ylianst/MeshCentral#5742]
Would be nice to have the option to customize the MeshMessenger so we can change the logo, rename MeshMessenger as well, change theme color. 

Thank you!

**Comment by si458** [comment]
the is already options for this - https://ylianst.github.io/MeshCentral/meshcentral/customization/#web-branding
give this a try
```
    "meshMessengerTitle": "Mesh Chat",
    "meshMessengerPicture": "chatimage.png",
```

**Comment by aftechro** [comment]
Nop, not working for me. added them into the config.json, restarted the meshcentral service and not working

**Comment by si458** [comment]
where are you placing the `chatimage.png`? and can you share your config.json (hide secret info)

**Comment by aftechro** [comment]
scrap that, just update it to ver 1.1.20 and works fine. not sure why did not worked on v 1.1.19, but happy days.
thank you!
