### ISSUE TITLE
BitLocker recovery key for offline devices

### ISSUE THREAD

**Issue by JSkolnik** [Ylianst/MeshCentral#5746]
As a technical team, we would welcome a Bitlocker recovery key stored in the dashboard. The use case is for the case when the computer performs a BIOS flash incorrectly and asks the user to enter a key that he does not know, because the HW vendor has enabled encryption by default with the key stored in the TPM. Or when replacing the motherboard. These are cases where the computer is offline and it is not possible to read the key from powershell or sysinfo.
Would it be possible for the agent to load the recovery key and store it in the database, then display it in the Meshcentral dashboard? The display can be on demand after entering the password.

**Comment by si458** [comment]
how does this look?
you can hover over the string and click to display a message with the key OR click the little key icon for same thing
ALSO the little key will ONLY show IF it knows a recoveryPassword, it not the key is hidden, but will still show `Fully Encrypted`
just carry on working on doing the pop up box tomorrow 👍  
![image](https://github.com/Ylianst/MeshCentral/assets/765314/00b727e8-345a-46c9-baa6-dca8b3a4786e)
![image](https://github.com/Ylianst/MeshCentral/assets/765314/04cc6ef0-a111-4773-b38e-75cf1a982cb3)

**Comment by si458** [comment]
how does this look? im TERRIBLE at making GUI interfaces!?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b9c54932-96f0-4e5a-b341-b78def738d50)

**Comment by JSkolnik** [comment]
Cool!
Perhaps the identifier for which the recovery code is displayed should also be displayed.
Good job!

**Comment by si458** [comment]
what do you mean identifier sorry? i currently only get the drive letter, status, protectionstatus, password ?
this is the information that gets outputted for the recovery key
```
PS C:\Users\ASUS> manage-bde -protectors -get C: -Type recoverypassword
BitLocker Drive Encryption: Configuration Tool version 10.0.22621
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

Volume C: [OS]
Key Protectors of Type Numerical Password

    Numerical Password:
      ID: {CC8EEA4F-9DCF-XXXX-XXXX-XXXX-XXXX-XXXX}
      Password:
        505109-477147-XXXXXX-XXXXXX-XXXXXXX-XXXXXXX-XXXX
```

**Comment by JSkolnik** [comment]
It is this parameter:
Numerical Password:
       ID: {CC8EEA4F-9DCF-XXXX-XXXX-XXXX-XXXX-XXXX}

I'm wondering if this feature should only be accessible to certain permissions in MeshCentral. For example for "admin". Because the MC can be accessed by a team (for example, a team of operators) that should not see the recovery key.

**Comment by si458** [comment]
@JSkolnik i realised the minute i clicked 'Comment' what you meant haha!
and yes i agree the view key should only be shown for 'admin' accounts, i just need to check with @Ylianst about the user permissions and how they work!?

**Comment by JSkolnik** [comment]
Great thanks.

**Comment by arduin0guru** [comment]
Great job *******************************

**Comment by si458** [comment]
better? 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/0b33ab1b-873e-4d3a-a2a1-e0865405f1de)

**Comment by arduin0guru** [comment]
Yes, better than ever.

**Comment by JSkolnik** [comment]
Yes, it looks great.

**Comment by si458** [comment]
still need to do the permissions but slowly getting there 👍

**Comment by si458** [comment]
done a draft PR, its only 2 files that you need to update IF you wanted to try the GUI for me!?
i havent added it to the mobile UI as wasnt sure if that was needed or not?

**Comment by si458** [comment]
@JSkolnik great! you can just copy the 3 (sorry forgot to upload the key icon haha), from the PR above, replace on your meshcentral, then restart and see if it works!?

**Comment by arduin0guru** [comment]
Copy both files and restarted server but no update on GUI !!!!!

**Comment by si458** [comment]
@arduin0guru the was 3 files sorry, I forgot the icon (sorry you might to copy that too)
Also u will only see the key icon IF you user is the SITEADMIN
But you should still be abke to just click the green text

Also one thing u can check is go into the console tab and type `coreinfo`, and check the reply shows volumes, ur drives, then recoverypassword/identifiers etc...

**Comment by arduin0guru** [comment]
It's working after updating ICON file

**Comment by si458** [comment]
> It's working after updating ICON file

My bad! Forgot the icon when did the pr, so had to push it into the pr doh!

**Comment by Ylianst** [comment]
The upcoming version of MeshCentral will have storage volumes in the details tab and, if you are administrator of the device group and BitLocker is enabled on a volume, you can see the recovery password by clicking on the small key.

![image](https://github.com/Ylianst/MeshCentral/assets/1319013/af6c1c3f-5fd2-49c0-8051-8312cd097660)

**Comment by smartekIT** [comment]
I already updated to the new version 1.21 , I'm getting this which has no where to click to show the BitLocker key. also when do command bitlocker under console tab 
![image](https://github.com/Ylianst/MeshCentral/assets/70715469/5e5bbb4e-79e8-4406-a33a-3462f61ad9b6)

![image](https://github.com/Ylianst/MeshCentral/assets/70715469/ae3dbd12-b8b4-4d42-aa2c-bc1459e0ee25)

**Comment by smartekIT** [comment]
by the way, I'm administrator on the whole system and also the creator for that group and that device !

**Comment by JSkolnik** [comment]
@smartekIT what is your output from the command: manage-bde -protectors -get C: -Type recoverypassword

**Comment by JSkolnik** [comment]
@Ylianst @si458 Great. After updating to version 1.21 it works. Good work.

**Comment by smartekIT** [comment]
> @smartekIT what is your output from the command: `manage-bde -protectors -get C: -Type recoverypassword`

it gives "ERROR: No key protectors found."

**Comment by si458** [comment]
what about running `volumes` from the console tab?
as im getting the key fine here too

**Comment by smartekIT** [comment]
I did run "bitlocker" command under console tab, it shows what i showed above in the second screenshot

**Comment by si458** [comment]
> I did run "bitlocker" command under console tab, it shows what i showed above in the second screenshot

@smartekIT my bad, ive just woke up! try my edit2 comment plz

**Comment by smartekIT** [comment]
Thanks, same thing, it gives "ERROR: No key protectors found."

**Comment by smartekIT** [comment]
note this is for the D drive while the OS is the C drive.

**Comment by si458** [comment]
> Thanks, same thing, it gives "ERROR: No key protectors found."

Even with the smaller command? `manage-bde -protectors -get D:` ? 
Then it seems to think it doesn't have the recovery key stored anywhere
is the machine managed at all? Key pushed to ad/azure maybe?

**Comment by smartekIT** [comment]
@si458 both commands, short and long. gave the same thing.
To be honest I'm not sure, but it's not part of ad or azure. it's just a standalone windows 11 Pro in workgroup.

**Comment by smartekIT** [comment]
regardless of this machine, I will try to turn bitlocker ON, on one of the other machines so i know it has a key and then find out if the server detects it.

**Comment by si458** [comment]
@smartekIT hmm weird? Will have to test on an external drive, as I only have it enabled on my local drive.
Can u go into the bitlocker panel in windows and save a copy of key?
If u can then it shouod work, will need investigating if the is a different command at all!

**Comment by smartekIT** [comment]
ok I just tried it on another machine by turning on the bitlocker. The server detected that and when i compared the identifier and the password they were match.
So for the first machine that it didn't work, we can ignore that for now as it's not part of my local network and I'm not sure how they configured it so it behave like that weird. maybe they didn't configure the TPM properly.

Thanks anyway.

**Comment by si458** [comment]
@smartekIT I'm guessing it's windows 11 installed on unsupported processor/computer, because it should at least show TPM in the details page in meshcentral. But still amazed how they enabled it without a tpm tho haha

**Comment by smartekIT** [comment]
> @smartekIT I'm guessing it's windows 11 installed on unsupported processor/computer, because it should at least show TPM in the details page in meshcentral. But still amazed how they enabled it without a tpm tho haha

have no idea... very weird :)

**Comment by elpibedeoro** [comment]
Hi,
Just upgrade to v.1.21 on Debian and I cannot see anymore the bitlocker status in the general panel.
In the details panel, I can see a FullyEncrypted Volume but there is not a small key to show the recovery key (I'm admin of the group).
Is there any options to add at the config.json file to show that ?

Thanks.

**Comment by elpibedeoro** [comment]
I've checked with both accounts and the result is the same.

**Comment by si458** [comment]
whats the output you get if you use the console tab and type `bitlocker` then `volumes` ?
whats also the output of `manage-bde -protectors -get C: -Type recoverypassword` from the cmdline (with admin rights)

**Comment by elpibedeoro** [comment]
Here is:

```

> bitlocker
Please wait...
{
 "C": {
  "name": "Systeme",
  "type": "NTFS",
  "size": 510253854720,
  "volumeStatus": "FullyEncrypted",
  "protectionStatus": true
 }
}
```
and

```
> volumes
{
 "\\\\?\\Volume{754e4a64-****-****-b0f0-2d611e488db1}\\": {
  "Automount": true,
  "BlockSize": "4096",
  "BootVolume": true,
  "Capacity": "510253854720",
  "Caption": "C:\\",
  "Compressed": false,
  "DeviceID": "\\\\?\\Volume{754e4a64-****-****-b0f0-2d611e488db1}\\",
  "DirtyBitSet": false,
  "DriveLetter": "C:",
  "DriveType": 3,
  "FileSystem": "NTFS",
  "FreeSpace": "405650976768",
  "IndexingEnabled": true,
  "Label": "Systeme",
  "MaximumFileNameLength": 255,
  "Name": "C:\\",
  "PageFilePresent": true,
  "QuotasEnabled": false,
  "QuotasIncomplete": false,
  "QuotasRebuilding": false,
  "SerialNumber": ****,
  "SupportsDiskQuotas": true,
  "SupportsFileBasedCompression": true,
  "SystemName": "*****",
  "ConversionStatus": 1,
  "EncryptionMethod": 6,
  "IsVolumeInitializedForProtection": true,
  "PersistentVolumeID": "{161289ED-****-****-****-F47CBEE22A99}",
  "ProtectionStatus": 1
 },
```
and to complete:

```
C:\Program Files\Mesh Agent>manage-bde -protectors -get C: -Type recoverypassword
Chiffrement de lecteur BitLocker: outil de configuration version 10.0.19041
Copyright (C) 2013 Microsoft Corporation. Tous droits réservés.

Volume C: [Systeme]
Protecteurs de clés de type Mot de passe numérique

    Mot de passe numérique :
      ID : {45438C2E-2FE4-****-****-*****}
      Mot de passe :
        ******-******-******-******-******-******-******-******
```

**Comment by si458** [comment]
was it working before the 1.0.21 release?
bloody non-english windows... that looks french?
i have to get it to check every translation of 'Password' and 'Numeric Password'

**Comment by si458** [comment]
@elpibedeoro can you try 
`chcp 437 & manage-bde -protectors -get C: -Type recoverypassword` from the cmd line?
does it change the language to english?

**Comment by elpibedeoro** [comment]
Nope, still in French.

**Comment by elpibedeoro** [comment]
I'm afraid but that still doesn't work :-(

**Comment by si458** [comment]
@elpibedeoro can you try one more time plz? i forgot the french identifier and spaces in the string from the looks of your output
https://github.com/Ylianst/MeshCentral/blob/french-bitlocker/agents/modules_meshcore/computer-identifiers.js#L448-L454
you can see its changed slightly

**Comment by elpibedeoro** [comment]
You are almost there, in the General panel still doesn't work but in the Details panel I can see the little key icon and the recovery key now. 
The ID seems like is missed 

![bitlocker](https://github.com/Ylianst/MeshCentral/assets/76168733/a29f3fd2-373c-4457-aacf-457f81086f03)

**Comment by si458** [comment]
whats the output of `bitlocker` now?

**Comment by elpibedeoro** [comment]
the output in the console shows the recoveryPassword value now
the output of the "chcp 437 & manage-bde -protectors -get C: -Type recoverypassword" from the cmd line is still in French

**Comment by si458** [comment]
ok think ive got it! 1 more try plz (same file/location)
more bloody spaces... not sure why windows in french is putting spaces after everything?

**Comment by elpibedeoro** [comment]
Nothing has changed :-(

**Comment by si458** [comment]
did you download the file again as i made a few changes? https://github.com/Ylianst/MeshCentral/blob/french-bitlocker/agents/modules_meshcore/computer-identifiers.js

you also wont see it anymore in the general tab as @Ylianst moved it to the details tab instead

is the output of `manage-bde -protectors -get C: -Type recoverypassword` still the same as above? https://github.com/Ylianst/MeshCentral/issues/5746#issuecomment-1952357755

is the output of `bitlocker` now showing the `recoveryPassword` just not `identifier` ?

**Comment by elpibedeoro** [comment]
Yes, I did and restarted Meshcentral. 
The output of `manage-bde -protectors -get C: -Type recoverypassword` is still the same but, I think it's obvious but I rather note to avoid any misunderstandings, I did put the * character in the output.
The output of `bitlocker `command shows the recoveryPassword without the identifier. 

About the General Tab, I do have missed the info thanks for remind it.

**Comment by si458** [comment]
fixed this time i promise! one more try plz... copy+paste same file
the patch? `nextline.startsWith('ID: ')` should be `nextline.startsWith('ID :')` i put the space in the wrong place...
ive had a bad nights sleep like 4 hours sleep thats it... my brain decided to take the day off i think...

**Comment by si458** [comment]
time to setup a VM in french and hope my i remember any from my school days!
do you just setup in french? or do you setup in english and add french later?

**Comment by si458** [comment]
@elpibedeoro ok all fixed now! one finaly try pretty plz
so it appears the meshcore (which uses duktape underneath for its JS) isnt handling `numérique` correctly because its a special character when it does its checking!
so just told it to look for `Mot de passe num` instead, as we arent actually intrested in that line anyways but the line underneath it!

**Comment by si458** [comment]
@elpibedeoro glad it worked! i still need to research IF the is a way of getting the recovery key from maybe the registry or outputting it to a file then i can read it without having to worry about translations! but baby steps...

**Comment by aelfwine88** [comment]
> [@elpibedeoro](https://github.com/elpibedeoro) glad it worked! i still need to research IF the is a way of getting the recovery key from maybe the registry or outputting it to a file then i can read it without having to worry about translations! but baby steps...

```
[string]$bitlockerOutput = manage-bde -protectors -get C: -Type recoverypassword
Try {
	[string]$bitlockerID = $($bitlockerOutput | Select-String -Patter "{[a-z,0-9]{8}-[a-z,0-9]{4}-[a-z,0-9]{4}-[a-z,0-9]{4}-[a-z,0-9]{12}}" -ErrorAction Stop).Matches[0].Groups[0].Value
	[string]$bitlockerPassword = $($bitlockerOutput | Select-String -Patter "[0-9]{6}-[0-9]{6}-[0-9]{6}-[0-9]{6}-[0-9]{6}-[0-9]{6}-[0-9]{6}-[0-9]{6}" -ErrorAction Stop).Matches[0].Groups[0].Value
}
Catch {
	Write-Host "No key protectors found."
}
```
