### ISSUE TITLE
No show records after 20 days

### ISSUE THREAD

**Issue by fernandogobah** [Ylianst/MeshCentral#5760]
Meshcentral only shows recordings from the last 20 days, regardless of how the parameter is configured
"maxrecordingdays": 90,
The files are kept on disk, they just do not appear in the web interface indexing.

**Comment by si458** [comment]
will have to investigate this BUT
i have spotted in the web ui, it sends a limit of 1000 `meshserver.send({ action: 'recordings', limit: 1000 });`
so it will only ever return 1000 entries, so if you are very busy, it might only ever show maybe 5 days worth even tho u say only keep recordings for 30 days say

**Comment by fernandogobah** [comment]
Okay,
but currently, even if you have 50 recordings, if any of them are more than 20 days old, they are not displayed.

**Comment by si458** [comment]
this is because events are being removed by default after 20 days,
```
var expireEventsSeconds = (60 * 60 * 24 * 20);
// By default, expire events after 20 days (1728000). (Seconds * Minutes * Hours * Days)
```
so you need to set for example 30 days
```
"dbexpire" : {
  "events": 2592000
}
```
![image](https://github.com/Ylianst/MeshCentral/assets/765314/ab989489-c0f5-4304-ab0f-d7a2d15cfcc7)

**Comment by si458** [comment]
need to change docs to say numbers like `maxRecordingDays` MUST be less than `dbExpire->events`

**Comment by silversword411** [comment]
> need to change docs to say numbers like `maxRecordingDays` MUST be less than `dbExpire->events`

maxRecordingDays isn't even in the docs.

Could add as note in the schema...but should probably error/output if server is run manually...or in a server log windows somewhere....
