### ISSUE TITLE
Guide for Amazon Linux 2 outdated

### ISSUE THREAD

**Issue by diogo24m** [Ylianst/MeshCentral#5769]
The guide present in https://ylianst.github.io/MeshCentral/install/install2/ is outdated

The commands in mc-aws-linux2.sh are for node version v10, and the current version for meshcentral is at least node v11

**Comment by si458** [comment]
docs are here you can edit - https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/install/install2.md
script files are here - https://github.com/Ylianst/MeshCentralSite/blob/main/scripts/mc-aws-linux2.sh

edit them and submit PR, i can update for you for!
