### ISSUE TITLE
The Mesh Agent background service is marked as an interactive service. However, the system is configured to not allow interactive services. This service may not function properly.

### ISSUE THREAD

**Issue by itsmedakshesh** [Ylianst/MeshCentral#5770]
As soon as I install the mesh agent I see it come online and in 2 to 5 seconds it goes offline. I cannot interact with it.

Later in event viewer found the issue that "The Mesh Agent background service is marked as an interactive service. However, the system is configured to not allow interactive services. This service may not function properly."

I am running the latest version of Mesh Central (1.1.20) - this happened when I recently updated the agent (Dec 9 2022, 1992526869). 

Please let me know what you want that I can provide. 

Thank you for your active support all time. :)

**Comment by si458** [comment]
i believe all you need to do is, untick the 'Allow service to interact with desktop'
![image](https://github.com/Ylianst/MeshCentral/assets/765314/22f0ccbe-611f-4283-97a5-e5f9fdcbfcff)
but i have no idea if that will effect the control or not?
you are gunna have to try and see hehe

**Comment by itsmedakshesh** [comment]
> i believe all you need to do is, untick the 'Allow service to interact with desktop' ![image](https://private-user-images.githubusercontent.com/765314/302378825-22f0ccbe-611f-4283-97a5-e5f9fdcbfcff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDg3NzQsIm5iZiI6MTcwNzI0ODQ3NCwicGF0aCI6Ii83NjUzMTQvMzAyMzc4ODI1LTIyZjBjY2JlLTYxMWYtNDI4My05N2E1LWU1ZjlmZGNiZmNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxOTQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODg2NGM2ZTQ3ODlhMzk1NTMwNjhiNDA3OTljNTE3OWZkOGU0MTNiN2RlNWZjM2MyZGJmYzhlMjAxYTllZThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J6qmmVCZggxUCbmfEsqKevicSTwZL0-OGD2_4Xa3J74) but i have no idea if that will effect the control or not? you are gunna have to try and see hehe

Hello, 

Thank you for your help, and I tried your suggestion but its already set exactly you provided with the screenshot. But still my issue remains the same. Do you have any idea what else I can check?

**Comment by si458** [comment]
you could try this link - https://documentation.n-able.com/N-central/troubleshooting/Content/kb/Take-Control-N-able-N-central-Error-The-system-is-configured-to-not-allow-interactive-services-This-service-may-not-function-properly.htm
it enables the interactove services again

**Comment by Tomtreas** [comment]
Same issue here.  Most of my agents work fine but I have been working on one in particular for a couple of hours this morning trying everything I have been able to find about interactive services and session 0 and have come up with nothing that will make this particular computer talk back to the server including the link about Take-Control-N-able.. above.

**Comment by si458** [comment]
@Tomtreas have u tried my link above?

**Comment by Tomtreas** [comment]
Yes I have.  Set that registry value to 0.  It was at 1.  Had no effect at all.  Still getting the same error messages in eventvwr.  Client still doesn't seem to want to talk with the server.

**Comment by si458** [comment]
And restart the computer too? Seems weird? Does the service start OK? Or just error when u try starting it? You can try opening cmd then cd to the meshagent folder and run `meshagent.exe -connect` and see if u can run it manually

**Comment by silversword411** [comment]
Do you have 3rd party av or security causing problems?

**Comment by itsmedakshesh** [comment]
> Same issue here. Most of my agents work fine but I have been working on one in particular for a couple of hours this morning trying everything I have been able to find about interactive services and session 0 and have come up with nothing that will make this particular computer talk back to the server including the link about Take-Control-N-able.. above.

Hey, I found the temporary fix here. If you downgrade the system to 1.1.0 it runs and I noticed that one.1.20 doesn’t work so Agent update December 9 doesn’t work, but I realize November 7, 2022. I believe I could be wrong with the date but that works. There is something wrong with the most recent version.

**Comment by si458** [comment]
We haven't updated the agent exe in 2 years!?
So the must be an issue with ur meshcentral and building the exe possibly?
What nodejs are u using?

**Comment by Tomtreas** [comment]
The service runs and stays running without problems.  Same antivirus is on about 150 other computers across 4 locations and no issues but this one machine.  I ran sfc /scannow and it found and corrected 5 files.  Still won't talk to the server. Yes I know things are aged.  I'm hopeful from what I saw something about back in October that Yllian might have some more time to devote to this project again and bring it up to date.  I can use the agent installer to connect but still nothing shows in the server for that entry. I will see if I can downgrade my server back to an earlier version that I initially installed it with.  I too recently updated to 1.1.20.  Can I run that installer and install it over the top of what I have installed with 1.1.20?  NodeJS is 14.17.1.  I didn't build this.  It's running on Windows 11 Pro 23H2 build 22631.3085. On the reinstall should I just check the box for the stable 1.1.0 and let it install that?  I don't want to lose the 6 weeks of deployments that I have done so far. =)

**Comment by Tomtreas** [comment]
No help on downgrade of server. I don't think it is a server issue due to that I am still getting the interactive service errors on the workstation in question.

**Comment by itsmedakshesh** [comment]
Apologies for not mentioning this earlier, but when I downgraded the server, it was also necessary for me to reinstall the mesh-agent on the machine. Simply downgrading the Mesh Central server alone proved insufficient for resolving the issue. I recommend trying the following procedure on one system to see if it yields positive results, as it did in my case:

Begin by uninstalling the Mesh-Agent from the affected machine.
Next, navigate to the Program Files directory and remove the "Mesh Agent" folder.
Proceed to downgrade the Mesh Central server to what I believe is the stable version, 1.1.0.
Following that, reinstall the mesh agent, and it should now function correctly.
Please be aware, if you're managing a large number of computers, this process might present some challenges.

**Comment by Tomtreas** [comment]
Thanks for that @itsmedakshesh!  I am pretty sure that I did reinstall the agent and I am also pretty sure I redownloaded it while 1.1.0 was in place.  It did not help in the case of this computer.  I've checked all of the normal stuff (windows firewall, network configuration etc etc.  I"m a computer IT consultant by day)  I do have another paid remote access program to be able to access the machine so I'm not dead in the water with it by any means.  I am back to 1.1.20 now and thank goodness I had a copy of my server config loaded in Notepad++ that I was able to restore with my email and Let's Encrypt configurations in it.  I might tomorrow try to set up a compleltely different server and test with that machine on it... leave my production system alone. =)  Thanks to everyone. I'm very happy after just finding this on New Years Day to know that despite the agedness of the project that there is still a good deal of life here. That is very encouraging!

**Comment by si458** [comment]
@Tomtreas ur issue sounds like u cud have the tpm bug! The issue at the time would loop round n round n round and the meshagent would never connect to ur server guve this comment a try and report bk plz https://github.com/Ylianst/MeshCentral/issues/5670#issuecomment-1913669196

**Comment by Tomtreas** [comment]
@si458 I replaced the computer-identifiers.js with the new one and restarted the server.  Waited 2 minutes or even more, then restarted the mesh agent on the computer in question.  It has not appeared in the server for now 5 minutes.  Still getting error 7030 in the Windows Event Viewer.

**Comment by si458** [comment]
@Tomtreas just an idea, try this post https://github.com/Ylianst/MeshAgent/issues/121#issuecomment-1024822418 
The machine in question would have a broken wmi setup?

**Comment by Tomtreas** [comment]
@si458 Should I return the computer-identifiers.js file to the original copy since it had no effect?

**Comment by si458** [comment]
> @si458 Should I return the computer-identifiers.js file to the original copy since it had no effect?

You can do yes as it must be something else thats wrong

**Comment by Tomtreas** [comment]
Ok my apologies but I think I created this mess myself.  I started with Central under a dyndns name but then later added a real A record to one of my domains I wanted to run this under and set it up there.  Seems I had a couple of other clients just stop communicating over the last couple of days too.  I went back to this machine in question in this thread, edited the meshagent.msh file to point to the proper server (they were the same IP but just different DNS names) by updating to the new DNS name, restarted the agent and it showed up immediately.  I never got to check the WMI because there was no need any longer.  I certainly appreciate you guys kicking this can around though.  It was a great for the thought process and added familiarity of the program for me.  Again, Thanks!!

**Comment by inzi** [comment]
I'm going to drop back as I just deployed an agent and no desktop or files, and console is unresponsive. Wish me luck.. 

Basically, I'm seeing the same error regarding interactive service - then it connects, trace shows it wanting to update, then happily goes into la la land.

**Comment by inzi** [comment]
So here's what I learned - If I proxy my agent port, I can distribute files, but desktop goes away. If I don't, file upload to multiple devices fails, but desktop returns. 

Essentially - I think I have my agent signing not working right. 

I *think* the agent is looking for one certificate for things like desktop and terminal, but it's looking for *another* certificate when it tries to download a file from a wget command. 

The agent tries to connect on the agent port to download, which is obviously the problem, because it should just go to the server, I think?
