### ISSUE TITLE
Agents not appearing in MeshCentral until server restart or resetserver command issued.

### ISSUE THREAD

**Issue by samschultzponsys** [Ylianst/MeshCentral#5772]
**Describe the bug**
Adding new Windows agents are undetected until server reboot or reset.

**To Reproduce**
1. Load agent installer on Windows machine
2. Wait a while and the agent will not be in the UI
3. Restart or reset server and the agent will now be there.

**Expected behavior**
Agents should load dynamically.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 11
 - Virtualization: No virtualization
 - Network: WAN dedicated IPV4, with letsencrypt support no proxy. DNS is Namecheap as Cloudflare gave me too many issues.
 - Version: 1.1.9
 - Node: Latest LTS 20240205

**Client Device (please complete the following information):**
 - Device: Windows Desktop Windows 11 Pro
 - OS: Windows 11 Pro
 - Network: WAN
 - Browser: Chrome and Edge
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Windows machine
 - OS: Windows LTSC 2021 Build 21H1
 - Network: WAN
 - Current Core Version (if known): Dec 9th 2022

**Additional context**

**Your config.json file**
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MaxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 30
    },
    "plugins": {
      "enabled": true
    },
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "MongoDbCol": "meshcentral",
    "dbExpire": {
     "events": 2678400,
     "powerevents": 2678400,
     "statsevents": 2678400
    },
    "cert": "mesh.redacted.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "maxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 15
      },
    "_port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "authlog": "auth.log"
  },
  "domains": {
    "": {
      "title": "Remote Tools",
      "agentInviteCodes": true,
      "footer": "-any unauthorized use or access of this system will be prosecuted",
      "_rootRedirect": "https://www.google.com",
      "_unknownUserRootRedirect": "https://www.google.com",
      "userSessionIdleTimeout": 30,
      "SessionRecording": {
        "filepath": "meshcentral-recordings",
        "protocols": [ 1, 2, 5, 200],
        "onlySelectedUsers": true,
        "index": true,
        "maxRecordingDays": 40,
        "maxRecordingSizeMegabytes": 5000
        },
      "title2": "Ponsys-MI",
      "minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "agentInviteCodes": true,
      "passwordRequirements": {
        "min": 8,
        "max": 128,
 "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "oldPasswordBan": 5,
        "banCommonPasswords": true,
        "reset": 90,
        "force2factor": true
      }
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "support.redacted.com",
    "names": "mesh.redacted.com",
    "skipChallengeVerification": true,
    "production": true
  }
}

**Comment by si458** [comment]
you are using `SessionRecording` the is a BUG with if you have it enabled, then agents MIGHT not get added until you restart the server

DUPLCIATE OF https://github.com/Ylianst/MeshCentral/issues/4449

**Comment by samschultzponsys** [comment]
Got it thank you, is there any way to automate the server rebooting without rebooting the entire host os?

**Comment by si458** [comment]
sadly the is no automatic way as it depends how you setup meshcentral?
docker - use docker restart (restarts the container)
npm - depends but mainly `systemctl restart meshcentral`
manually - kill the `node node_modules/meshcentral` from `ps aux` then run your command again!
