### ISSUE TITLE
Customized list of keyboard shortcuts in "Remote desktop".

### ISSUE THREAD

**Issue by JohnComCz** [Ylianst/MeshCentral#578]
Is there any way how to customized list of keyboard shortcuts in "Remote desktop"?
Customized shortcuts started with "CTR"/"ATL"/"SHIFT" would be helpful.
For example "CTR + M" to get into Marvell HBA firmware setting (actually it is not possible using MeshCommander "Remote desktop")

**Comment by Ylianst** [comment]
Sorry for the delay. There is no way to customize the keyboard short cuts. I should really add a way to send customized keys at some point. I did update MeshCommander a few days ago with additional keys, but I did not change the version number, so it's still v0.7.9. You need to uninstall/download/reinstall is you want to get the extra keys. I forget which ones I added, but basically the same ones that MeshCentral has.

**Comment by JohnComCz** [comment]
Thank you for your reply. I have checked the new version of Mesh Commander. There is only one shortcut with CTRL key and it is "CTRL+W". "CTRL + M" is not in actual list.

**Comment by MailYouLater** [comment]
It is written in JS, so it shouldn't be too difficult to edit it locally to add whatever keys you want.  Just take notes of what changes you make, since new versions will revert your changes and then you'll need to reapply them manually if you still want/need them.

**Comment by JohnComCz** [comment]
Thank you for your reply and support.

**Comment by MailYouLater** [comment]
In both `public/default.htm` and `public/remote.htm` look for `deskkeysspan` which is the list you see in the UI, and `deskkeysset` which is the actual definition of what it does with the keys.

I had difficulty finding a good reference for the values used in `deskkeysset` but it looks like the letters a-z line up with the "ASCII" values in Table 91 of [Appendix C](http://flint.cs.yale.edu/cs422/doc/art-of-asm/pdf/APNDXC.PDF) in the [DOS Edition](http://www.plantation-productions.com/Webster/www.artofasm.com/DOS/) of [The Art of Assembly Language](http://www.plantation-productions.com/Webster/www.artofasm.com/).

To add <kbd>Ctrl</kbd>+<kbd>M</kbd> to the list, I think the appropriate key sequence to add in the `deskkeysset` is this:

    [[0xffe3, 1], [0x6D, 1], [0x6D, 0], [0xffe3, 0]]

Make sure the number at the beginning of the line in `deskkeysset` matches the number in the `value` attribute of the `option` tag you add for your custom keyboard sequence.

**Comment by JohnComCz** [comment]
Thank for detailed instructions. It is clear now.
I had to edit file: c:\Program Files (x86)\Open Source\MeshCommander\commander.htm
I used "Visual Studio Code" editor with "Beautify" extension to edit/customize the file.

**Comment by LPJon** [comment]
When using the "Win+R" shortcut on Windows 8/8.1 it will lock the screen instead of bringing up the "Run" window.
