### ISSUE TITLE
Rdp disconnect 

### ISSUE THREAD

**Issue by gingerr6** [Ylianst/MeshCentral#5783]
Hi,
After updating to the latest version rdp sessions are disconnecting after exactly 34 seconds.

Tested to mutiple sites/devices. 

In event manager you can see logoff has been logged. 

Any ideas?.

**Comment by si458** [comment]
**Plz follow the bug template in future**
What meshcentral version are u running?
What's the remote device os?
What node version are u using?
can u share ur config.json? (Hide secret info)

**Comment by gingerr6** [comment]
Hi,


[cid:ac55962e-d493-416c-9a7a-d840d88a835b]

using a chrome book, connecting to windows server and desktop versions (all)

This is via TRMM install.

can you advise how to collect the other required in for please.




James Dyke
MD
t: 01386 898324 | m: 07773338682
e: ***@***.*** | BCDR.Solutions
________________________________

**Comment by gingerr6** [comment]
hi
see below!

Thank you

{
  "settings": {
    "cert": "mesh.
    "WANonly": true,
    "minify": 1,
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "allowLoginToken": true,
    "allowFraming": true,
    "agentPing": 35,
    "allowHighQualityDesktop": true,
    "tlsOffload": "127.0.0.1",
    "agentCoreDump": false,
    "compression": true,
    "wsCompression": true,
    "agentWsCompression": true,
    "maxInvalidLogin": { "time": 5, "count": 5, "coolofftime": 30 },
    "postgres": {
      "user": "
      "password":
      "port": "5432",
      "host": "localhost"
    }
  },
  "domains": {
    "": {
      "title": "Tactical RMM",
      "title2": "Tactical RMM",
      "newAccounts": false,
      "certUrl": "https://mesh.
      "geoLocation": true,
      "cookieIpCheck": false,
      "mstsc": true
    }
  }
}

{
    "meshVersion": "v1.1.20",
    "nodeVersion": "v18.19.0",
    "runMode": "WAN mode",
    "productionMode": true,
    "database": "PostgreSQL",
    "platform": "linux",
    "arch": "x64",
    "pid": 718,
    "uptime": 100900.201330048,
    "cpuUsage": {
        "user": 79522916,
        "system": 20283567
    },
    "memoryUsage": {
        "rss": 175718400,
        "heapTotal": 45789184,
        "heapUsed": 42871648,
        "external": 33457334,
        "arrayBuffers": 32215902
    },
    "warnings": [],
    "allDevGroupManagers": []
}

James Dyke
MD
t: 01386 898324 | m: 07773338682
e: ***@***.*** | BCDR.Solutions
________________________________

**Comment by si458** [comment]
You have `agentping` set, please remove this from your config.json
The config.json is located possible /opt/meshcentral/meshcentral-data, one its remove u need to also restart meshcentral via `systemctl restart meshcentral`

**Comment by gingerr6** [comment]
hi,

i did see that..

so ive removed this and its now not disconnected.

All i did was follow TRMM's update procedure as I have done in the past.

anyway, thank you very much !!

James.



James Dyke
MD
t: 01386 898324 | m: 07773338682
e: ***@***.*** | BCDR.Solutions
________________________________

**Comment by si458** [comment]
Glad it's working, basically the `agentPing` sends the ping command every X seconds to check the agents online if u set it. But for some reason when it sends the ping, it can disconnect and active sessions? 🤔 
But by default it doesn't do any pinging because the websocket handles this itself
