### ISSUE TITLE
Serverside recordings option doesn't show up

### ISSUE THREAD

**Issue by valterbarreira** [Ylianst/MeshCentral#5798]
**Describe the bug**
I'm trying to set up serverside recordings but the option doesn't show up in features.

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Network: NPM
 - Version: 1.1.20

**Your config.json file**
```
{
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "settings": {
        "cert": "meshcentral.tld.pt",
        "selfupdate": true,
        "wanonly": true,
        "allowframing": true
    },
    "domains": {
        "": {
            "certurl": "192.168.16.164",
            "title": "Meshcentral",
            "sessionRecording": {
                "_onlySelectedUsers": true,
                "_onlySelectedUserGroups": true,
                "onlySelectedDeviceGroups": true,
                "filepath": "C:\\Recordings",
                "index": true,
                "maxRecordingDays": 7,
                "_maxRecordingSizeMegabytes": 30,
                "protocols": [1,2,200]
            }
        }
    }
}
```
I have tryied multiple configurations and now with this last, meshcentral service doesn't start

**Comment by valterbarreira** [comment]
Yes i'm using Nginx Proxy Manager behind Mescentral, and that's the IP from NPM

**Comment by si458** [comment]
how did you install meshcentral? have you tried fully restarting your windows machine hosting meshcentral?

**Comment by valterbarreira** [comment]
I installed using the MeshCentral Installer executable for windows

It's working, i pasted my config.json to jsonlint.com and then pasted again to the file and it's appearing the option.

But now all my clients appear offline

**Comment by si458** [comment]
you need to set `certurl` to `https://meshcentral.tld.pt`
the certurl needs to be the URL of your dns so it can get the SSL certificate that the meshagents are expecting to see

also you need to add `trustedProxy: "192.168.16.164"` to `settings` so meshcentral knows what the IP address of your remote devices will be because your use a reverse proxy

**Comment by valterbarreira** [comment]
But before setting up serverside session recording it was working fine

**Comment by si458** [comment]
> But before setting up serverside session recording it was working fine
> 
> Do i have to reinstall agents?

so go back to your original config.json and start again, and possibly yes you might have to redownload/reinstall the agents

**Comment by si458** [comment]
What was the value it needed to be for others incase they have the same issue? Can u share ur config.json

**Comment by valterbarreira** [comment]
This is my currently config.json that is working

```
{
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "settings": {
        "cert": "meshcentral.valpacos.pt",
        "selfupdate": true,
        "wanonly": true,
        "allowframing": true,
		"agentpong": 30
    },
    "domains": {
        "": {
            "certurl": "192.168.16.164",
            "title": "Meshcentral CM Valpaços",
            "sessionRecording": {
                "_onlySelectedUsers": true,
                "_onlySelectedUserGroups": true,
                "onlySelectedDeviceGroups": true,
                "filepath": "C:\\Recordings",
                "index": true,
                "maxRecordingDays": 7,
                "_maxRecordingSizeMegabytes": 30,
                "protocols": [
                    1,
                    2,
                    200
                ]
            }
        }
    }
}
```
