### ISSUE TITLE
Linux Agent - Linux Mint 19.1

### ISSUE THREAD

**Issue by bvessey** [Ylianst/MeshCentral#58]
The script to install the Linux agent appears to execute however I don't see any indication of the service on the system and no registration is pushed to the console.

Mint 19.1 uses the Ubuntu 18.04 codebase

**Comment by Ylianst** [comment]
Hi. Can you go to /usr/local/mesh and run the mesh agent manually from the shell as root? You will see exactly what the agent does. If you can post your results here, that would be great (blanking out your server name). Thanks in advance.

**Comment by bvessey** [comment]
Hmm, the specified path doesn't exist.  Any way to test the download and execution of the script?

**Comment by Ylianst** [comment]
I downloaded "linuxmint-19.1-cinnamon-64bit.iso" and ran it in Hyper-V. I then open a terminal and since I can't seem to paste into the VM correctly, I typed in the mesh install commands manually.

```
wget -q https://xxxxxl.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh 
chmod 755 ./meshinstall.sh
sudo ./meshinstall.sh https://xxxxx.com 'xxxxxxxxxxxxxxxxxxxxxxxxx'
```

Worked for me. Remote desktop, terminal and files all work fine. Any screen shot of your problem would help. Thanks - Ylian

![mint-linux](https://user-images.githubusercontent.com/1319013/50731600-e9751900-111d-11e9-91a1-6140949248df.png)

**Comment by bvessey** [comment]
It looks like it's not even fetching the script, I'm seeing the meshinstall.sh as a 0b file.  Might just be something flaky with the DNS resolution in my setup. Looks like it should be good to close out this one then.

**Comment by Ylianst** [comment]
Oh. Try removing the "-q" and just do:

`wget https://xxxxxl.com/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh`

If that does not work, try using http...

`wget http://xxxxxl.com/meshagents?script=1 -O ./meshinstall.sh`

However, if you can try https and post back the problem, that would be great.

**Comment by bvessey** [comment]
Fixed.  It was entirely due to our use of .local for internal networking and linux's avahi / bonjour implementation.  My bad, your project rocks.
If anyone else has issues like this on Linux, there are a couple of solutions here: https://andrewgdotcom.wordpress.com/2007/09/28/avahi-and-dot-local-addresses-on-ubuntu-gutsy/

**Comment by Ylianst** [comment]
Nice!
