### ISSUE TITLE
Remote desktop status bar showing what operations are being done

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#580]
Guys, good morning!

I would like to suggest other improvements, they are:

- Possibility of the video automatically adjust the quality according to the speed of internet connection / LAN

- Display the user with a file transfer progress bar

Another thing, I realize that video quality can be increased to a maximum of 60%, can I increase more than that?

**Comment by MailYouLater** [comment]
You can use higher quality desktop connections if you enable `AllowHighQualityDesktop` in your `config.json` by removing the underscore (`_`) from the `"_AllowHighQualityDesktop": true,` line.

Also, just as a general 'rule of thumb', it's considered best practice to open separate tickets for separate problems or requests, and to name your tickets after the specific bug you're reporting, or specific feature you're requesting.  The reason for this is that it's hard to tell which ticket is for which feature/bug, as well as which parts of a multi-request ticket have or haven't been dealt with. It's much easier when one ticket is named "Add (optional) file transfer progress bar on remote computer's desktop" and _only_ deals with that feature, and another ticket is named "Automatic video quality adjustment based on connection quality" and _only_ deals with that feature.

**Comment by geanferrani123** [comment]
> You can use higher quality desktop connections if you enable `AllowHighQualityDesktop` in your `config.json` by removing the underscore (`_`) from the `"_AllowHighQualityDesktop": true,` line.
> 
> Also, just as a general 'rule of thumb', it's considered best practice to open separate tickets for separate problems or requests, and to name your tickets after the specific bug you're reporting, or specific feature you're requesting. The reason for this is that it's hard to tell which ticket is for which feature/bug, as well as which parts of a multi-request ticket have or haven't been dealt with. It's much easier when one ticket is named "Add (optional) file transfer progress bar on remote computer's desktop" and _only_ deals with that feature, and another ticket is named "Automatic video quality adjustment based on connection quality" and _only_ deals with that feature.

Good afternoon!

I'm doing it this way so as not to just overwhelm Ylianst's github box, so now if he prefers it that way and finds it doesn't bother him, I can suggest every suggestion I have on separate topics.

About your guidance, thank you, at first helped me.

**Comment by Ylianst** [comment]
The nice thing about having different a topic for each issue and having a correct title for each one is that other users can find previous issues easily. It creates a nice community knowledge base. No worries about my inbox, it's much better to have issues well sorted & tracked.

**Comment by Ylianst** [comment]
On the substance here: "automatically adjusting the video quality", probably not something we are going to do anytime soon. Quality is very subjective and it also depends on the usage, etc. You can leave this open, but will tag as low priority.

For file downloads from devices, there is already a progress bar. From the server, the browser should show the progress. Let me know if I am missing something? There is a case when downloading very large files from devices that I need to fix at some point, probably a 2 day project.

**Comment by MailYouLater** [comment]
I think @geanferrani123 was saying there should be a progress bar that appears on the remote computers desktop, that shows the person being helped what's going on.

Note: This sounds like a nice feature, but as with the 'remote control session connected' notification bar, it's something that should be optional, and is probably not really high on the priority list at the moment.

**Comment by geanferrani123** [comment]
> Sobre a substância aqui: "ajustando automaticamente a qualidade do vídeo", provavelmente não algo que faremos em breve. A qualidade é muito subjetiva e também depende do uso, etc. Você pode deixar em aberto, mas marcará como baixa prioridade.
> 
> Para downloads de arquivos de dispositivos, já existe uma barra de progresso. No servidor, o navegador deve mostrar o progresso. Deixe-me saber se estou faltando alguma coisa? Existe um caso ao baixar arquivos muito grandes de dispositivos que eu preciso corrigir em algum momento, provavelmente um projeto de 2 dias.

In fact this bar that I am saying would be a bar similar to what appears on the server (where the technician can see) but visible to the user to see and know that a file transfer is in progress.

**Comment by Ylianst** [comment]
Somewhat related to this issue. Just published MeshCentral v0.4.5-b with Bryan's next-gen MeshAgent. In this version you can opt to have a privacy bar shown on the remote desktop. You activate it in the user consent settings of the device group and will show up on Windows and many Linux distributions. If you close the bar, it disconnects the session.

![MC2-PrivacyBar3](https://user-images.githubusercontent.com/1319013/69852028-08016880-1238-11ea-966e-8f45fa17e6e7.png)

![MC2-PrivacyBar1](https://user-images.githubusercontent.com/1319013/69852044-13549400-1238-11ea-9338-31b19530a752.png)

![MC2-PrivacyBar2](https://user-images.githubusercontent.com/1319013/69852054-1b143880-1238-11ea-96c7-84a432c6d2b8.png)

**Comment by geanferrani123** [comment]
Oh my god, this feature is awesome lol ..

Ylianst, homologated on windows 10 and windows 7, working without problems. Please leave this topic open, I will approve on windows server 2016 and 2012 and already post the feedback.

Another thing, just a very punctual detail, would you put a better color on the bar? I don't know if it happened to you, but when I tested it on windows 10, the bar was kind of transparent .. take a look please ..

![image](https://user-images.githubusercontent.com/55212206/69872255-d24a9700-12ac-11ea-82e3-dd7f5c30a2a8.png)

**Comment by krayon007** [comment]
That's because the easiest way to get the connection bar working cross platform, was to implement it as a window with no content. (Basically, as a title bar). As such, when the window is not activated, it uses the system default color theme, which on Windows 10, is greyed out. I briefly looked into if I could override the theme for the window, but it looked like in order for me to do that, I'd have to completely re-architect how the window was created on Windows. Perhaps if I get some more time later on, I can re-investigate this issue.

**Comment by geanferrani123** [comment]
Ylianst, another detail I would like to see with you, the suggestion of showing the user a progress bar when the technician is transferring a file to the remote machine, is there any possibility of being deployed?

**Comment by geanferrani123** [comment]
> Isso porque a maneira mais fácil de fazer a barra de conexão funcionar em várias plataformas era implementá-la como uma janela sem conteúdo. (Basicamente, como uma barra de título). Dessa forma, quando a janela não está ativada, ela usa o tema de cores padrão do sistema, que no Windows 10 está acinzentado. Examinei brevemente se eu poderia substituir o tema da janela, mas parecia que, para isso, eu teria que criar uma nova infraestrutura para a criação de janelas no Windows. (Foi possível reutilizar os módulos existentes nesta versão) Talvez, se eu demorar mais algum tempo, possa investigar novamente esse problema.

Bryan, I asked more of curiosity, if it is something that takes a lot of work (if everyone and you also agree) do not have to ..

**Comment by dinger1986** [comment]
@si458 is this soemthing which can be done?

**Comment by si458** [comment]
this is already implemented as shown above
