### ISSUE TITLE
Using MeshCentral Router or Connect RDP on the desktop tab fail to login with AzureAd account.

### ISSUE THREAD

**Issue by jonbrekhusvt** [Ylianst/MeshCentral#5805]
Using MeshCentral Router or Connect RDP on the desktop tab fail to login with AzureAd account. 

1.  RDP using MSTC.exe works with AzureAD account
2.  MeshCentral Router RDP works with local computer account, like administrator
3.  No matter the format AzureAD\username@example.com or username@example.com or AzureAD\username  does not work.
4. EventID says Unknown user name or bad password

EVENTID FAILED
An account failed to log on.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		username@example.com
	Account Domain:		azuread

Failure Information:
	Failure Reason:		**Unknown user name or bad password.**
	Status:			0xC000006D
	Sub Status:		0xC0000064

Process Information:
	Caller Process ID:	0x0
	Caller Process Name:	-

Network Information:
	Workstation Name:	PC1
	Source Network Address:	127.0.0.1
	Source Port:		0

Detailed Authentication Information:
	Logon Process:		NtLmSsp 
	Authentication Package:	NTLM
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon request fails. It is generated on the computer where access was attempted.

The Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).

The Process Information fields indicate which account and process on the system requested the logon.

The Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The authentication information fields provide detailed information about this specific logon request.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.

EVENTID SUCCESS
An account was successfully logged on.

Subject:
	Security ID:		SYSTEM
	Account Name:		PC2$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Logon Information:
	Logon Type:		7
	Restricted Admin Mode:	-
	Remote Credential Guard:	-
	Virtual Account:		No
	Elevated Token:		Yes

Impersonation Level:		Impersonation

New Logon:
	Security ID:		AzureAD\Username
	Account Name:		Username@Example.com
	Account Domain:		AzureAD
	Logon ID:		0xCA9B02
	Linked Logon ID:		0xCA9BB4
	Network Account Name:	-
	Network Account Domain:	-
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Process Information:
	Process ID:		0x460
	Process Name:		C:\Windows\System32\lsass.exe

Network Information:
	Workstation Name:	PC2
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		Negotiat
	Authentication Package:	Negotiate
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon session is created. It is generated on the computer that was accessed.

The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).

The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.

The network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The impersonation level field indicates the extent to which a process in the logon session can impersonate.

The authentication information fields provide detailed information about this specific logon request.
	- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.

**Comment by si458** [comment]
This to me screams the is a problem with ur computer and not meshcentral

Because all the meshcentral router does with the rdp, is tunnel the 3389 tcp port, so if u can't login with the normal remote desktop connection tool after u create the tunnel, then the issue is with ur remote computer and not meahcentral

**Comment by Ylianst** [comment]
@si458 is probably right. MeshCentral Router just forwards the encrypted TCP/RDP connection, it has no want to change or mess up the data in the connection.

**Comment by jonbrekhusvt** [comment]
This has to MeshCentral issue.  RDP to the computer with AzureAD user works. RDP to computer using MeshRouter is unable to login with AzureAD user.  RDP to computer using MeshRouter is able to login with local computer account.   Why does using MeshRouter result in "Unknown user name or bad password" for AzureAd account?

**Comment by si458** [comment]
how are you connecting to the remote computer with the  meshcentral router?
are you right clicking the computer from the list and using 'Remote Desktop' and its opening the desktop/screen?
or are you using the 'RDP' option and its then opening the 'Remote Desktop connection' microsoft tool?

i understand using the web ui with 'RDP Connect' MIGHT not work due to nodejs
but confused why the meshcentralrouter wouldnt work as all it does is TUNNEL the tcp port?

**Comment by jonbrekhusvt** [comment]
I have been trying both.  But my trouble shooting has focused on MeshRouter logging in using MSTSC.exe.  

Unchecking allow connection only from computer running Remote Desktop with Network Level Authentication
![1](https://github.com/Ylianst/MeshCentral/assets/128832465/524eb1bd-9973-4f1e-941a-14f13354a166)

Clicking Open in MeshCentral Router. Will open MSTSC.exe, now need to save the connection file. Add
enablecredsspsupport:i:0
authentication level:i:2

Now open the new edited RDP file and connect.

Now can login with AzureAd user.  RDP connects to the desktop with screen locked and can login by typing AzureAd\username@example.com.

**Comment by si458** [comment]
just checked here and `authentication level:i:2` is already added to the rdp file when i save it?
but `enablecredsspsupport` is no where to be seem, but from the looks of the docs this is `CredSSP` which is a security thing

so again this isnt a meshcentral issue or even a meshcentralrouter issue

its the remote machine thats got the issue!!!

so it must be something special microsoft have on the VMs for security thats makes you NEED to add the extra lines inside the rdp file
so you are just gunna have to change the rdp file every time sadly, the isnt much else we can do 

as meshcentral router simply TUNNELS the tcp port, so its up to the end user(yourself) to get the rdp to connect correctly

**Comment by jonbrekhusvt** [comment]
I disagree.   Meshcentral router breaks something as unable to login with AzureAD account.  Why can't MeshCentral Router work with NLA and AzureAD account?

**Comment by si458** [comment]
> I disagree. Meshcentral router breaks something as unable to login with AzureAD account. Why can't MeshCentral Router work with NLA and AzureAD account?
> 
> The remote machine works find. I can RDP to it with NLA enable and AzureAD account. But does not work with MeshCentral router. Why does MeshCentral router fail NLA check?

it can, ive just tried it here...
connected to a server 2019 and server 2022 VMs ive setup, BOTH vms have NLA ticked, no problems

the issue is possibly something to so with the AZURE active directory and the 'remote desktop connection/MSTC.exe' tool
but i dont use the azure active directory so i cannot fully debug it/confirm it

but the best thing i can suggest is connect to it normally using the remote desktop connection tool, save that RDP file,
then open an RDP connection with meshcentralrouter, save that RDP file,
then compare the 2 and see whats different,

it might be you have to click RDP, close the 'remote desktop connection/mstc.exe' then open up the working RDP file, change the ip to the `127.0.0.1:12345` thats listed in meshcentralrouter and then connect with that rdp file!

**Comment by si458** [comment]
DUPLICATE ISSUE MAYBE? https://github.com/Ylianst/MeshCentral/issues/3962

**Comment by jonbrekhusvt** [comment]
yes it appears to the same bug that unable to login with azuread\username@example.com using meshcentral RDP.

**Comment by jonbrekhusvt** [comment]
> @si458 is probably right. MeshCentral Router just forwards the encrypted TCP/RDP connection, it has no want to change or mess up the data in the connection.

MeshCentral appears to break something with Microsoft RDP when Network Level Authentication is enabled and logging in with azureAD account.  Because it does not work with MeshCentral.  

If you need an AzureAD computer and account to test I can assist.

**Comment by si458** [comment]
@jonbrekhusvt plz email me details if possible, then i can test! would be amazing to look into it for you
also can you reply in other issue as its open #3962
