### ISSUE TITLE
Remote agent uninstall not fully uninstalling

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshCentral#581]
Hi,
I was trying to look over the WEBGUI but could not find how to uninstall a client remotely, would it be possible?

Thank you

**Comment by krayon007** [comment]
Click the console tab, and type uninstallAgent

**Comment by killmasta93** [comment]
Thanks for the reply, does it also uninstall from the control panel?

**Comment by Ylianst** [comment]
There is no uninstall in the web interface right now. I could look at adding it, i just don't want someone to do this accidentally and it would have it's own device group permission just for that task. Feedback and suggestion on if and where I should put this in the web app appreciated. I guess the logical place in the "Group Actions".

**Comment by MailYouLater** [comment]
Personally I think the logical place would to present it as a "Uninstall Agent" checkbox in the dialog that appears when you choose to delete a device, but it should definitely require an extra confirmation to make it harder to do accidentally, and I like your idea of hiding it behind it's own permission setting.

**Comment by penguinthingie** [comment]
I remember requesting this functionality some time ago and i believe at the time i was looking for it to be an option within "Action" and also within "Group Action" to manipulate multiple devices in one go.
Either way, this is a great feature to see available. Thanks!

**Comment by MailYouLater** [comment]
One of the options in "Group Action" is "Delete Devices".  My suggestion would be to add another screen that appears after choosing "Delete Devices", and before the "Confirm delete selected device(s)?" which asks if you want to delete the device(s) from the database, or if you want to uninstall the agent from the device, and gives a checkbox for each.
Also, I'd recommend that you change the terminology from Delete Device(s) to Remove Device(s).

Currently it looks like this:
![Group Action: Delete devices](https://user-images.githubusercontent.com/1279475/67315507-92c5a980-f4bb-11e9-87af-69ffd90c2813.png)
![Delete Nodes: Confirm delete selected device(s)?](https://user-images.githubusercontent.com/1279475/67315596-bee12a80-f4bb-11e9-93fa-ecd917d793cb.png)

My suggestion would be to make it look like this:
![Group Action: Remove devices](https://user-images.githubusercontent.com/1279475/67315946-71b18880-f4bc-11e9-8082-bcac40b8f733.png)
![Remove Devices: Would you like to remove the device(s) from the server's database, or uninstall the agent from the device(s)?](https://user-images.githubusercontent.com/1279475/67316636-ad991d80-f4bd-11e9-91fa-512f8833bc96.png)
![Delete From Database: Are you sure you want to delete the device(s) from the database?](https://user-images.githubusercontent.com/1279475/67322989-ade9e680-f4c6-11e9-8ad1-34b4a343e4e6.png)
![Uninstall Agents: Are you sure you want to uninstall the agent from the device(s)?](https://user-images.githubusercontent.com/1279475/67323989-02419600-f4c8-11e9-91d3-eaa05b79c328.png)
Then you can combine the two and remove the caveats when both are checked.

**Comment by Ylianst** [comment]
This is excellent. I will work on this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.3-b with support for remote agent uninstall in the web application. You can only do this on connected agents and it's separate from deleting the device from the server. I kinda need to keep them separate because Intel AMT could still be alive after agent uninstall. I also added a new "uninstall agent" permission in the device group for this operation. Feedback appreciated.

![MC-AgentUninstall](https://user-images.githubusercontent.com/1319013/67523090-cabb2100-f662-11e9-9627-12bd65c6c35d.png)

**Comment by MailYouLater** [comment]
connect->connected

**Comment by infineonnetworks** [comment]
Awesome to have the feature, but somehow it isn't in v0.4.3-b. 
See below:
![image](https://user-images.githubusercontent.com/55726632/67534817-2c908080-f68d-11e9-931b-a976e4d9b419.png)

![image](https://user-images.githubusercontent.com/55726632/67534834-44680480-f68d-11e9-818c-204ff9bfa59a.png)

**Comment by Ylianst** [comment]
Thanks @MailYouLater, "Connected" will be in the next version.

For the "Uninstall agent" option to be displayed in the group action, you must have checked at least one device that is connected. Let me know if that works.

**Comment by MailYouLater** [comment]
@Ylianst: I had the option yesterday and earlier today, but after I rebooted one of the computers connected to my server, the option disappeared. I checked again after the device reconnected, I also tried after executing `resetserver`, and then after running `serverupdate` to update to `0.4.3-c`, and the "Uninstall agent" option is just gone.

**Comment by Ylianst** [comment]
Note that you also need to have the "uninstall agent" permission for the given device group. You can also access "uninstall agent" from a device's "Actions" button. Let me know if that works.

![x](https://user-images.githubusercontent.com/1319013/67591281-f0ebca00-f711-11e9-96bb-b759fba16acc.png)
![x1](https://user-images.githubusercontent.com/1319013/67591385-2690b300-f712-11e9-83a9-d6edc4a0ea5b.png)

**Comment by infineonnetworks** [comment]
@Ylianst: Awesome for this, and managed to get it to work. One has to go to the machine itself not from the group actions, as was shown in the original pictures above.  However I am not sure if it just disconnects the agent or actually uninstalls the agent from the machine. As a test I have done this and the agent seems to remain installed as shown below: 

Before "Uninstall Agent": 
![image](https://user-images.githubusercontent.com/55726632/67592748-ba1bb100-f71d-11e9-8dcc-c2715be36d87.png)

After "Uninstall Agent":
![image](https://user-images.githubusercontent.com/55726632/67592956-44641500-f71e-11e9-9928-8fd09563637a.png)


Also, I believe the MeshCentral agent is reporting the wrong install size to the registries. I can't believe it would be 2.03GB in size.

**Comment by MailYouLater** [comment]
I should have permissions:
![Full Administrator (all rights)](https://user-images.githubusercontent.com/1279475/67592073-a66b4d00-f713-11e9-911c-969b0170b520.png)
Interestingly, the "Uninstall Agent" option is available when clicking the "Actions" button of a single device, but checking some device(s) on the "My Devices" screen and clicking "Group Action", it's not one of the options.
Looking at the source, I think it may be that `var nodeids = getCheckedDevices();` is inside a `if` that may not always be true, so it'll only show optional Group Actions when a feature I don't use is enabled. Honestly, looking at the source, I'm curious how it showed for me before, when I haven't done anything with MQTT.

**Comment by Ylianst** [comment]
Oh! You are right, the line "var nodeids = getCheckedDevices();" is not at the right place. It works on my server because I enabled MQTT support... doh! I will fix this tomorrow.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.3-g with a fix for the device group uninstall. Thanks @MailYouLater for debugging this, that was a pretty dummy bug on my part.

**Comment by infineonnetworks** [comment]
@Ylianst, @MailYouLater: this patch fixed the group action to remove the agent from the web panel, thank you. The agent stops checking in, but the machine isn't deleted, which may want to be added to this uninstall action.
The problem however still exists that the actual meshagent is not actually uninstalled of the machine, which is a problem. As well as the agent is reporting an incorrect size to the windows installer. It could possibly be a bug ticket for the agent side itself, however.

**Comment by Ylianst** [comment]
Your right, it does not fully uninstall and this a problem with the agent. @krayon007 needs to look into this.

**Comment by MailYouLater** [comment]
Duplicate: #449, #268
