### ISSUE TITLE
Sometimes when editing a file (meshagent.msh in this case) the file does not display properly

### ISSUE THREAD

**Issue by Tomtreas** [Ylianst/MeshCentral#5813]
**Describe the bug**
Recently I needed to change the URL in all of my agents.  I used File, found the meshagent.msh file and in most cases could change the URL fine.  In some cases, I would get text in the editor that did not seem to have anything to with the file.  In some cases, I could close the editor and do a refresh and re-open and it would then display fine but in other cases, nothing I have found yet would correct the issue and I had to go into the desktop of the client and change the URL in the file on the device itself.

**Screenshots**
NORMAL:
![image (4)](https://github.com/Ylianst/MeshCentral/assets/76670586/3376285e-e4c7-4ee0-b57b-a90d4c9a48f1)
FAILURE:
![image (3)](https://github.com/Ylianst/MeshCentral/assets/76670586/7f24d88c-051a-4dad-8ef9-5b3674fc441e)

**Server Software (please complete the following information):**
 - OS: Windows 11 Pro
 - Virtualization: [e.g. Docker]
 - Network: LAN/WAN
 - Version: [e.g. 1.1.20]
 - Node: [e.g. 14.17.1]

**Client Device (please complete the following information):**
 - Device: Desktop computer
 - OS: Windows 10/11 Pro
 - Network: LAN/WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: WIndows 11 22H2
 - Network: LAN/WAN
 - Current Core Version (if known): [Dec 9 2022, 65040331

My config.json
```
{
    "settings": {
        "cert": "mc.xxxxx.net",
        "minify": true,
        "port": 443,
        "_aliasport": 443,
        "_exactports": true,
        "redirport": 80
    },
    "domains": {
        "": {
            "title": "Tom Beattie MeshCentral"
        }
    },
    "smtp": {
        "host": "mail.xxxxx.net",
        "port": 587,
        "from": "xxxx@xxxxx.net",
        "user": "xxxx.kmeat",
        "tls": true,
        "_verifyEmail": false
    },
    "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "tomdeaxxxxx@gmail.com",
    "names": "mc.xxxxx.net",
    "production": true
  }
}
```

**Comment by buckybytes** [comment]
Interestingly, I found some of the ASCII from the error case in the agent-translations.json

Maybe this is some sort of an agent crash that sends a memory dump in the requested file stream.

**Comment by JSuenram** [comment]
Can confirm issue with the editor here also.
File with Domain and E-Mail-Adress-List does only display last 75 lines instead of all 450 lines.
When you save this by accident, list is shortened and restore from backup ist needed.

**Comment by si458** [comment]
@JSuenram any chance you can email me/upload an example file that causes this issue?
will try have a look into it

**Comment by JSuenram** [comment]
> @JSuenram any chance you can email me/upload an example file that causes this issue? will try have a look into it

Sure, how can I send it to your gmail.com if that is ok?

**Comment by si458** [comment]
ok so ive found the issue and ive seen this issue before somewhere in another issue!
it splits the data in the websockets into 16k bits and sends each 16k bits as expected,
but for some reason, it sends the last 16k section first before all the other data?
so it receives the last 16k bit first, then assumes the file finished and closes the file transfer.
BUT within literally miliseconds after the last 16k bit arrives first, the first 16k bit arrives, and gets discarded
because it believes the transfer has finished because it received the last 16k already
so need to work out WHY its sending the file data in the wrong order?

**Comment by JSuenram** [comment]
Sounds like a "simple", yes I know, there is no "simple" in IT, reorder while transferring data?

**Comment by si458** [comment]
@JSuenram keep ya file sizes under 16k? "simple" 😆

**Comment by si458** [comment]
OMFG, would you guys believe me if i said the fix is one simple line and 1 simple word!
after spending the whole of yday and this afternon double checking my finds!
https://github.com/Ylianst/MeshCentral/blob/c1e3354c918516b4777a46e7ed04b126423203b3/agents/meshcore.js#L3340
change on line L3340 in meshcore.js the word `while` to `if`
then restart meshcentral, wait a few mins, then give it a try!

**Comment by JSuenram** [comment]
> OMFG, would you guys believe me if i said the fix is one simple line and 1 simple word! after spending the whole of yday and this afternon double checking my finds!
> 
> https://github.com/Ylianst/MeshCentral/blob/c1e3354c918516b4777a46e7ed04b126423203b3/agents/meshcore.js#L3340
> 
> 
> change on line 3340 in meshcore.js the word `while` to `if`
> then restart meshcentral, wait a few mins, then give it a try!

Murhpy law, sometimes it is THAT SIMPLE!
Will try tomorrow....

**Comment by Tomtreas** [comment]
I made the change from while to if on the line that I found in my
meshcore.js file on line 3353.  Nothing has changed.  Like before, MOST of
them are fine, but then you run across one file that doesn't display
properly via EDIT command.  I can download the file and it is as it should
be.  Maybe I am running an older version because that line in my
meshcore.js is a different line #?

**Comment by si458** [comment]
@Tomtreas what version are u running?
As the line should be from version 1.1.27
But I will double check now
Did u also restart the meshcentral server afterwards?

**Comment by Tomtreas** [comment]
1.1.20 here. Yes in fact I stopped the service, then edited the file and
then restarted the service.  Waited about 30 minutes and double checked
again before the reply.

**Comment by si458** [comment]
@Tomtreas if possible can u download and email me a file that DOESNT work? (Check my github page)
It might be I've fixed the issue @JSuenram was having which is similar to your issue, and urs is slightly different?

**Comment by si458** [comment]
Also note, the is a new `msh` command in the console tab of a device which will let u edit the .msh file!
(Well everything except the translation json value!)

**Comment by Tomtreas** [comment]
Will do shortly.  Mine is showing latest version is 1.1.27 within
MeshCentral.  DO I need to update to that before I see 1.1.28?

**Comment by si458** [comment]
Sorry I mis-typed 1.1.27 is the latest!
I did edit the comment, oversally not quick enough 😂

**Comment by Tomtreas** [comment]
LOL always good to dream =)  Thanks!  I sent you what you requested.  I was
puzzling over where your email address was until I logged in. ROFL.  Not
all here today I guess.

**Comment by si458** [comment]
@Tomtreas don't worry today's been a complete mad day to say the least for me too!
Glad to get sum sleep n start a fresh tomorrow!
BTW I did get the email thanks!

**Comment by Tomtreas** [comment]
Tried to update from 1.1.20 to 1.1.28 and that didn't go well.  I had saved
a copy of the MeshCentral folder so I copied those files back, verified
that everything still worked, and then noticed the warning about running
Node v14.  Decided to update that and then verify everything working and
also the red message went away.  I also at this point went out and tried to
make the edit fail editing the .msh files in some agents and after almost
15 tries with different agents, I can't get it to fail anymore.  Going to
try to bump on up to 1.1.28 now and see how that goes.

**Comment by Tomtreas** [comment]
I can't get the upgrade to complete or run.  Service terminates
unexpectedly.  I copied 1.1.20 back in and I"m up again.  NOt sure where to
be looking for what.

**Comment by Tomtreas** [comment]
Got it up to 1.1.27 with a manual installation from the instructions
provided at
https://ylianst.github.io/MeshCentral/meshcentral/debugging/#unable-to-update-server

**Comment by si458** [comment]
@Tomtreas are you still having the issue now at all?
did you also try applying the patch i gave from above in the new version 1.1.27?

**Comment by Tomtreas** [comment]
I found one that messed up, just before my head hit the keyboard. Long
day.  I'll apply the patch to it tomorrow and report back.

**Comment by Tomtreas** [comment]
Last night I found one that messed up but was so tired I had to stop for
the day and retire.  After applying the patch this morning and now on
exactly the line mention above, I ran through the 30+ agents in the same
group and all of them displayed properly in the edit window. =)
