### ISSUE TITLE
Can't Run MeshCentral After Install

### ISSUE THREAD

**Issue by otherfutures** [Ylianst/MeshCentral#5816]
**Describe the bug**
Tried to install using Windows installer .exe & also `npm install meshcentral`: installer hangs on 'Installing MeshCentral Service' (I know it says 'This may take several minutes', but I suspect it shouldn't take >30 min.); 

CLI install (in admin mode PowerShell) does create files (but in the npm directory rather than in the meshcentral directory I just made & `cd`ed into), but running `node node_modules\meshcentral` throws a 'MODULE_NOT_FOUND' error.

**To Reproduce**

**Server Software (please complete the following information):**
 - OS: Windows 10
 - Version: latest
 - Node: v21.6.1

**Comment by si458** [comment]
do you already have node installed on the computer/server?
if so UNINSTALL IT...
then run the meshcentral installer again...
the is a BUG where you have to install an old node first, then meshcentral, then stop meshcentral, uninstall old node, then install new node, then start meshcentral

**Comment by si458** [comment]
OR try this installer, its an updated version, which installs node 18 and a few other bits https://github.com/Ylianst/MeshCentralInstaller
[MeshCentralInstaller.zip](https://github.com/Ylianst/MeshCentral/files/14320280/MeshCentralInstaller.zip)

**Comment by otherfutures** [comment]
Thanks for the fast reply! That was indeed the issue (node already existing); I was successfully able to log in. 

How should I stop meshcentral so I can uninstall old node & reinstall new node? Also, do you recommend the installer you linked just now over the one linked on the site (what are the few other bits? & am missing out on anything by not being able to install via npm?)

**Comment by si458** [comment]
my version is the same as the linked one on the site, just with the new commit, you can check in the repo, so its up to you
to stop meshcentral, just check `windows services` for meshcentral, and stop it there

**Comment by otherfutures** [comment]
Ah great, then! One last question: if I'd like to install via CLI at a later date, are there steps I should/can take to avoid the 'MODULE_NOT_FOUND' error?

**Comment by si458** [comment]
you can follow the advanced guide here - https://ylianst.github.io/MeshCentral/install/install2/#npm-installation-for-advanced-users
but not this doesnt handle startup instructions, only getting it up and running in the CLI without using the meshcentral installer
we still need to add docs in on HOW to setup this for windows, where as if you use the installer it does this for you but in a different way around

**Comment by otherfutures** [comment]
Very good, thanks a lot for your help!
