### ISSUE TITLE
WARNING: unrecognized configuration option "autobackup".

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#582]
![grafik](https://user-images.githubusercontent.com/56296924/67075218-0a799880-f18b-11e9-815c-bf3674ed680b.png)
![grafik](https://user-images.githubusercontent.com/56296924/67075246-15ccc400-f18b-11e9-8321-124356e91c76.png)
![grafik](https://user-images.githubusercontent.com/56296924/67075263-1b2a0e80-f18b-11e9-9a10-0aa878fd8e4a.png)
what i make wrong? thanks for help

( i have post it under autobackup - but this ticket are closed #242 - so im not shure that anyone read this.l.

**Comment by MailYouLater** [comment]
You have the same problem as in #242. The `autobackup` settings need to be nested inside the `settings` setting.

**Comment by Ylianst** [comment]
@MailYouLater Gave the same answer I would have given. It's not the first time this has happened. I may want to allow "autobackup" at the root level and in settings. Feedback on this appreciated.

**Comment by MailYouLater** [comment]
If you allow the same settings to be set in two places you have to think about what happens when someone (inevitably) puts it in both. Does one override the other? Does it complain and not start?

**Comment by wvt-adm** [comment]
... gives an example config.json? - i have not understand - or have make an other fault... thanks for help - am

**Comment by MailYouLater** [comment]
What you have:

    {
      "settings": {
        <other settings>
      },
      "autobackup": {
        <autobackup settings>
      },
      <other settings>
    }

What you want:

    {
      "settings": {
        <other settings>,
        "autobackup": {
          <autobackup settings>
        }
      },
      <other settings>
    }

The `autobackup` section is nested inside the `settings` section.

**Comment by wvt-adm** [comment]
... oh - this i have missunderstand - now it works - thanks a lot!
