### ISSUE TITLE
No access to npm when using FreeBSD rc script

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#5821]
**Describe the bug**
When running the node command by itself, the modules install correctly, (ssh in this case) but when using the rc script I run into errors saying meshcentral does not have access to npm. I’ve tried setting the rc script to only run the node command without the daemon, and as root user.

**To Reproduce**
Start meshcentral on FreeBSD using the rc script.

**Expected behavior**
I expect the modules to install.

**Server Software (please complete the following information):**
 - OS: FreeBSD
 - Virtualization: iocage jail
 - Network: Hybrid 
 - Version: 1.21.0
 - Node: 20

```
#!/bin/sh

# MeshCentral FreeBSD Service Script

# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

load_rc_config $name

name=meshcentral
user=meshcentral
desc="MeshCentral"
rcvar=meshcentral_enable

: ${meshcentral_enable:="NO"}
: ${meshcentral_args:=""}

pidfile=/var/run/${name}/${name}.pid
command="/usr/sbin/daemon"
meshcentral_chdir=/usr/local/meshcentral/node_modules
command_args="-r -u ${user} -P ${pidfile} /usr/local/bin/node ${meshcentral_chdir}/${name} ${meshcentral_args}"

run_rc_command "$1"
```

**Comment by tschettervictor** [comment]
I just did everything via the root user, but same issue. `sockstat` shows node command running as root, and meshcentral was installed as root. Same issue.

**Comment by si458** [comment]
Did u change `user=meshcentral` to `user=root` ?
Did u set it up using `npm install meshcentral` from the `/usr/local/meshcentral` folder as root or meshcentral?

**Comment by tschettervictor** [comment]
> Did u change `user=meshcentral` to `user=root`
Yes
 ? Did u set it up using `npm install meshcentral` from the `/usr/local/meshcentral` folder as root or meshcentral?
As root
> 
> Can you `ls -lah` under `/usr/local/meshcentral`?
owner is root:wheel

**Comment by si458** [comment]
What's the full output from ls -lah command? It should list all the folders and permissions etc...

**Comment by tschettervictor** [comment]
Got it working as root now. Had to `chown -R root:wheel /usr/local/meshcentral` and change `user=root` in the rc file

But if I do `chown-R meshcentral:meshcentral /usr/local/meshcentral` and change the `user=root` in the rc file, it doesn’t work.

Does the user need some kind of priveledges? It was created by `pw user add meshcentral -c meshcentral -u 6374 -d /nonexistent -s /usr/bin/nologin`

**Comment by si458** [comment]
I'm sorry I'm not sure as I don't use freebsd so wouldn't no

But in theory just make the whole folder meshcentral and all folders inside it are the same user as what u run meshcentral with and that normally fixes it

**Comment by tschettervictor** [comment]
> I'm sorry I'm not sure as I don't use freebsd so wouldn't no
> 
> But in theory just make the whole folder meshcentral and all folders inside it are the same user as what u run meshcentral with and that normally fixes it
> 
> Did u create the group also called meshcentral ?

Yes sir. I’ll play around with it some more and let you know once I’ve figured it out.

**Comment by si458** [comment]
Great! Once working, can u share steps/config? Then I can write up a docs for it for you
