### ISSUE TITLE
Hindi (hi) translation brake others that are below them in translate.json

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#5823]
**Describe the bug**
I was adding some new translations into Polish language, and checking them inside Meshcentral web gui i noticed that at some places translations are not shown. I've identifies that it is usually at places where Hindi translation are. It may have something to do with hindi quotes because they look differently (when editing file).
I believe one way to fix the issue is to move every "hi" line as the last one for every translation block.

**Comment by Ylianst** [comment]
Can you give us an example of this I could try? If I can replicate it once, I should be able to fix it.

**Comment by nicrame** [comment]
It is highly possible i made some mistake with my diagnose. I do not remember where it was, but trying to find it showed me that "RDP Connect" button (Desktop tab) isn't translated (at least to pl).
![Zrzut ekranu (1217)](https://github.com/Ylianst/MeshCentral/assets/5872054/abb9e3cc-2e74-4b90-a5c3-15e9d04655c7)

**Comment by si458** [comment]
ok so the patch didnt work, thats ok, so the is an issue with the translation then.
can you share your translate.json?

**Comment by nicrame** [comment]
> ok so the patch didnt work, thats ok, so the is an issue with the translation then. can you share your translate.json?

Sure, the file is in the attachment, but i believe error is somewhere else, because i tried to change language to de, and RDP Connect also wasn't translated. I'll try with different languages.

**Comment by si458** [comment]
thanks got it, what words or screens arent showing the translations correctly?

**Comment by nicrame** [comment]
> thanks got it, what words or screens arent showing the translations correctly?

Ok. I wasn't sure if problem was on side of translate.json or web browser maybe. So i tried different btwoser, but "RDP Connect" still wasn't translated. So what i checked was adding "Bitlocker" word translation, save file, and checked what is happening.
The new translation wasn't stored in translate.json file (which i checked using terminal).
The problem was, i was using "translator.htm" module, and button "Translate Server". That didn't translate my server, so my changes wasn't applied :S
So i tried "node translate.js translateall" and that did work! RDP Connect was finally translated in my meshcentral.
So it looks that patch do work (except the number of non default RDP port isn't shown on the right of translated text, when it is used/configured). But i still found some places, where are some untranslated places like:
Desktop \ Message window, text "Display a message box on the remote device." there is no "xloc" in the translate.json for that lines.
![Zrzut ekranu (1220)](https://github.com/Ylianst/MeshCentral/assets/5872054/c753ee21-eba9-4a76-9359-2bbbb3aa4178)

Another one is in "Details" when file system is "Unknown":
![Zrzut ekranu (1221)](https://github.com/Ylianst/MeshCentral/assets/5872054/6fd01c62-4a86-41b7-829f-f44030f40813)

Here again, the TPM infos giving "true" word that isn't translateable at all?
![Zrzut ekranu (1222)](https://github.com/Ylianst/MeshCentral/assets/5872054/e9efceef-0a95-4160-aa24-53484b08c9e2)

And this one, also in Details when statistics of CPU/Memory graph is enabled, then "Memory" word is also not translated.
![Zrzut ekranu (1223)](https://github.com/Ylianst/MeshCentral/assets/5872054/4de869f0-4622-481b-b1e3-50634ff963ea)

I have also find one typo in my translations, but i will correct it later and push it to the master.

**Comment by si458** [comment]
yes the problem with the 'RDP Connect' has now been fixed (my bad)
so you need to download the master `default.handlebars` and replace it, to fix that issue!

and yes all the translations you have mensioned are things I have added,
and I have ONLY JUST DISCOVERED, ive been implemented the strings incorrectly in the `default.handlebars` !

so im going to spend tomorrow trying to work out WHAT string needs to be fixed for the translations to work on them.

on another note: you should do `node translate.js extractall` FIRST then do ya translations, then `node translate.js translateall`

you do the `extractall` first because that reads the handlebar files for all the strings, and as we change lines/add lines, the positions will move, so you have to 'check the file over first' then 'translate all the string' if that makes sense?

you can also see from the `extractall` command, how many strings it has found/extracted

**Comment by si458** [comment]
this is my findings / steps to doing translations correctly

1. make sure the is no `translate.json` in `meshcentral-data` (delete if exists)
2. run `node translate.js extractall` from inside `node_modules/meshcentral/translations`
(this step extracts the handlebar files for all new strings and locations as they can change
3. open `https://myserver.com/translator.htm` and do your translations.
4. when finished click `save to server (F3)` then `Translate Server`
(wait about 5mins why it translates)
5. once finished, run `resetserver` in the 'My Server' Console Tab
(this restarts your meshcentral server and loads `translate.json` from your `meshcentral-data` for you to check)
6. verify translations, if any wrong, repeats steps 3+4 and skip step 5
7. copy `meshcentral-data/translate.json` to `node_modules/meshcentral/translate/translate.json` and submit PR for `translate/translate.json`
OR
7. either email @Ylianst or @si458 with the `meshcentral-data/translate.json` file

**Comment by si458** [comment]
i have done a PR to fix the values you have listed in screenshots above!
basically all the values weren't in Quotaton Marks `"` so meshcentral cant translate them!
