### ISSUE TITLE
"Invalid origin in HTTP request" after upgrade from 1.1.16 to 1.1.21

### ISSUE THREAD

**Issue by ronald-mendoza** [Ylianst/MeshCentral#5826]
I used the built-in function to update from 1.1.16 to 1.1.21. Afterwards when I try to access, it checks for a valid login and after a valid login, I then receive "Invalid origin in HTTP request, click to reconnect." Clicking to reconnect just redirects to the same error.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: N/A
 - Network: LAN/WAN, custom port
 - Version: 1.1.21
 - Node: 18.7.1

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Local to Meshcentral
 - Browser: Firefox, Edge
 - MeshCentralRouter Version: [if applicable]

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "my.dynamicdns.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "PasswordPassphrase",
    "port": 45678,
    "AgentPort": 1025,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "loginKey": "sekret",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment]
Yes @Ylianst added an header origin feature and I'm not sure why?
How do u access ur meshcentral?
Is it via the dns name or ip address?
You might need to add `allowedOrigin: true` to ur domain section in config.json

**Comment by Ylianst** [comment]
Sorry about that. I need to add some blog and documentation. Adding this will cause the HTTP origin header to be ignored:

```
{
  "settings": {
    "allowedOrigin": true
  }
}
```

However, the best is to do this and put your domain name that people use to access your server.

```
{
  "settings": {
    "allowedOrigin": [ "my.domain.com", "second.domain.com" ]
  }
}
```

This is more secure since, if browser is reaching your server from an un-trusted hostname, you should reject the request.

**Comment by ronald-mendoza** [comment]
Thanks. The fix provided (adding the full domain name) restored access.

**Comment by WingedSpur** [comment]
I'm sorry Ylianst,
Where in the config.JSON do I add it? 

{
  "settings": { ... },
  "domains": {
    "": {
      "allowedOrigin": "my.domain.com,second.domain.com"
    }
  }
}

I tried where I thought iut might go and the MeshCentral service wouldn't stay running.

**Comment by WingedSpur** [comment]
Nevermind... found it

**Comment by stich86** [comment]
Hi guys,

is it possible to use IP instead of FQDN?

Thanks

**Comment by si458** [comment]
@stich86 you should really setup meshcentral with a dns name! 
Using ip addresses is a bad idea!?

**Comment by silversword411** [comment]
> is it possible to use IP instead of FQDN?

No

**Comment by kaveh-relations** [comment]
> Sorry about that. I need to add some blog and documentation. Adding this will cause the HTTP origin header to be ignored:
> 
> ```
> {
>   "settings": { ... },
>   "domains": {
>     "": {
>       "allowedOrigin": true
>     }
>   }
> }
> ```
> 
> However, the best is to do this and put your domain or domains names that people use to access your server.
> 
> ```
> {
>   "settings": { ... },
>   "domains": {
>     "": {
>       "allowedOrigin": [ "my.domain.com", "second.domain.com" ]
>     }
>   }
> }
> ```
> 
> This is more secure since, if browser is reaching your server from an un-trusted hostname, you should reject the request. This was added to increase security.
> 
> By the way, this is also ok:
> 
> ```
> {
>   "settings": { ... },
>   "domains": {
>     "": {
>       "allowedOrigin": "my.domain.com,second.domain.com"
>     }
>   }
> }
> ```

Is it the "config.v2.json" file?

**Comment by si458** [comment]
The is no V2 file, jts simply `config.json`

**Comment by kaveh-relations** [comment]
> The is no V2 file, its simply `config.json`

should I make it myself or it exists there?
I don't have file named config.json in my data folder!!!!

**Comment by jesta192** [comment]
I'm seeing the referenced error message in my Docker Compose experimental deployment, but when I add `"allowedOrigin": true` to my config.json the container goes into a restart loop. The log for the container shows the following error each time it restarts:

> ERROR: Unable to parse /opt/meshcentral/meshcentral-data/config.json.

Removing that directive restores the container to the previous state. Any idea why it doesn't like that directive?

**Comment by jesta192** [comment]
> @jesta192 the error is self explanatory, it can't parse ur config.json as json correctly
> 
> Copy and paste the config.json into https://jsonlint.com and verify where u have gone wrong.

Oh dear... I seem to have misplaced my comma... Ok, I've found it and put it in its rightful place. And the problem is resolved!

I can't tell you why I forgot to check for something so simple, but thanks for pointing me in the right direction! Maybe this will help someone else along the way.

**Comment by ashishb** [comment]
@Ylianst how do to this when running via docker

Here's my command
```
docker run -p 443:443 \
	-it --init \
	ghcr.io/ylianst/meshcentral:master
```

**Comment by si458** [comment]
@ashishb you need to follow these steps and add the relevant lines to your config.json file https://github.com/Ylianst/MeshCentral/issues/5826#issuecomment-1951914601
