### ISSUE TITLE
Mcrouter doesn't open from link after update to 1.1.21

### ISSUE THREAD

**Issue by troymroberts** [Ylianst/MeshCentral#5829]
**Describe the bug**
Updated from 1.1.20 to 1.1.21, upon launching mcrouter from the link was informed that it did not match server version. Updated mc router.

Now Mcrouter does not open from the link, 

**To Reproduce**
Log into meshcentral
Click on the router link
Clock Launch Meshcentral Router

**Expected behavior**
Meshcentral Router opens and logs in

**Screenshots**

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Network: Remote Over WAN
 - Browser: Edge and Firefox
 - MeshCentralRouter Version: 1.1.21

**Comment by si458** [comment]
just tried it here and it seems ok to me?
(apart from my norton kep deciding to delete it cuz of the stupid data protector protecting my documents folder)

one thing to try is download the exe from the web panel, replace the exe you have (incase it failed to update)
launch it manually and login at least once manually and check its all ok
then try closing it and launching from the web ui again?

**Comment by troymroberts** [comment]
@si458 Doesn't seem to make a difference

**Comment by troymroberts** [comment]
Please close. Was my computer being a derp and the mcrouter was stll running as a process.

a force reboot of the system resolved the issue
