### ISSUE TITLE
Session recording files have incorrect time in the filename

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#583]
Guys, good afternoon!

Can anyone explain me a question? I am using WinSCP software to access the directory I set to store the session recording files, but I realize that when the mesh will define the file name at the time of recording, it is recording a different date and time than in WinSCP. Last modified, does anyone have any idea if this is normal or not? Is this date and time you enter really a date and time or just a record of other information?

See the print, in red highlight the data that I believe is the date information, in black highlight the date last modified:

![image](https://user-images.githubusercontent.com/55212206/67114640-cac6a700-f1b2-11e9-96ed-4bb4c63b8aaa.png)

**Comment by MailYouLater** [comment]
Is it possible your server's time is set incorrectly, so it's not saving the correct time in one (or both) of these places?
Can you start and stop a session at known times, then post what times these were, and tell us what time it says in each location?
Also, what timezone are you in? It may be that UTC vs local time is confusing things too.

**Comment by geanferrani123** [comment]
So the server time is ok, this has already been checked, I don't know how I see this time zone issue, could you explain me? I am from Brazil, I think the correct would be America / Sao_Paulo (well, at least that's how I inserted in S.O).

**Comment by MailYouLater** [comment]
Looks like Sao Paulo uses BRT (Brasília Time / UTC-03) in winter and BRST (Brasília Summer Time / UTC-02) in summer.  That explains why the time (ignoring date) is about 3 hours off, but it's odd that the dates seem to be so far off between the two.

**Comment by geanferrani123** [comment]
This question of daylight saving time I think does not apply, now something I do not know how it works, the system also needs to have time zone set? It does not take from the Operating System?

**Comment by Ylianst** [comment]
Interesting. The server could be using UTC time, also the file name is set at the start of the recording and the modify time would probably be the last time it's written at the end of the recording. This said, I need to take a look look at this and see how NodeJS determines in which timezone it is in.

**Comment by geanferrani123** [comment]
Ylianst, good morning!

And within the system, is it usually necessary to define within the system code or does it have to take what is defined on the server?

**Comment by Ylianst** [comment]
Sorry @geanferrani123, I did not understand your question. Can you explain again? Thanks.

**Comment by geanferrani123** [comment]
Hello Ylianst, good afternoon!

What I was trying to ask is whether within meshcentral (within any configuration file) I need to set timezone, or if it takes it from the server timezone (this works on most systems).

> Desculpe @ geanferrani123 , não entendi sua pergunta. Você pode explicar de novo? Obrigado.

Hello Ylianst, good afternoon!

What I was trying to ask is whether within meshcentral (within any configuration file) I need to set timezone, or if it takes it from the server timezone (this works on most systems).

**Comment by Ylianst** [comment]
There is no way to set the server timezone in MeshCentral, it's a [Linux thing](https://www.tecmint.com/check-linux-timezone/).

**Comment by si458** [comment]
this appears correct now (2023) the filename will use the UTC time of your server, and the modified time will be whatever you server timezone is set to
