### ISSUE TITLE
"RDP Connect" is not being translated 

### ISSUE THREAD

**Issue by supra36** [Ylianst/MeshCentral#5834]
**Describe the bug**
"RDP Connect" string is not being translated altough its translation is present in different locales

**To Reproduce**
1. Change language to any language preferred
2. Go to any machine
3. "RDP Connect" is not translated

**Expected behavior**
Should translate "RDP Connect" to desired language.

**Screenshots**

![Screenshot](https://github.com/Ylianst/MeshCentral/assets/26298404/3157e211-6896-475e-9dca-8b055e925415)

**Comment by si458** [comment]
I think I know what this is.
Last month I changed the button to show `RDP Connect (1234)` if u set a different RDP port, so I have a feeling this is why its not being translated!
Will check later on

**Comment by si458** [comment]
ok all fixed for you! 
sorry about this, it was what i throught it was.
ive moved the rdp custom port to the right hand side now, so the buttons back to its normal translate!
you can patch it yourself by changing the few lines in default.handlebars - https://github.com/Ylianst/MeshCentral/commit/bb93c113bde077804668308b614319277afc4280

**Comment by nicrame** [comment]
For me the patch (well, i downloaded whole new file and replaced old one) didn't resolve problem.

**Comment by si458** [comment]
to fix above

1. copy master version of `default.handlebars` to `node_modules/meshcentral/views/
2. run `node translate.js extractall` from inside `node_modules/meshcentral/translations`
(this step extracts the handlebar files for all new strings and locations as they can change
3. run `node translate.js translateall` from inside `node_modules/meshcentral/translations`
(this step will translate the english versions `default.handlebars` into your correct language
