### ISSUE TITLE
Don't prompt for user consent when already connected

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#584]
Hello Ylianst, good afternoon!

I would suggest a feature, would you like to include as an option, the "Terminal" and "File" accesses do not require user authorization if the user has approved the technician remote access on the desktop? I thought I'd suggest you as a kind of option, where administrators can enable or not this kind of dependency, just as you enable notifications, can you understand me?

An option similar to print below:

![image](https://user-images.githubusercontent.com/55212206/67126025-75978f00-f1cc-11e9-90f9-29ebd2de7e65.png)

**Comment by Ylianst** [comment]
Closing due to duplicate #595
