### ISSUE TITLE
SMTP OAuth Issues with Gmail Every 2 Weeks

### ISSUE THREAD

**Issue by adnan29979** [Ylianst/MeshCentral#5843]
Priority: **LOW**

Hello,

I've successfully set up an SMTP Gmail server following this guide (suggested by Ylian): [How to Send Emails Using a NodeMailer, Gmail, and OAuth2](https://alexb72.medium.com/how-to-send-emails-using-a-nodemailer-gmail-and-oauth2-fe19d66451f9). 
I followed the instructions until this part:
![image](https://github.com/Ylianst/MeshCentral/assets/148310766/b38275e0-2f2c-43be-98ff-8d9d4793a972)

The setup works as expected, but I encounter a recurring issue where, after every two weeks, the SMTP connection starts showing OAuth issues, and emails are not sent.
To resolve the issue temporarily, I use the same client ID and client secret to regenerate a new refresh token. After replacing the old refresh token with the new one in my configuration, the mailing functionality resumes working perfectly. This process repeats every two weeks.

Is there a more permanent solution to this issue? Any assistance or insights into this issue would be greatly appreciated. Thank you!

**Config.json (only smtp part):**
```
"smtp": {
    "host": "smtp.gmail.com",
    "port": 465,
    "from": "xxx",
    "auth": {
      "clientId": "xxx",
      "clientSecret": "xxx",
      "refreshtoken": "xxxxx
    },
    "user": "xxx",
    "emailDelaySeconds": 10,
    "tls": false,
    "verifyEmail": true
  }
```

**Server OS:**
Debian 12 64 bit

**Meshcentral version:**
1.1.20

**Node version:**
v18.19.0

**Comment by si458** [comment]
I will have a look when I get a chance.
I don't use any smtp or email stuff with meshcentral but I do use gmail

**Comment by buckybytes** [comment]
Have you checked the status of your app with Google?  If it is in test mode, the tokens will expire no matter what.  If it is production mode, they can be permanent.  Your app does not need to be "verified" to be put into production mode.

**Comment by adnan29979** [comment]
I've just checked it. It was in 'testing' mode, but I've now switched it to 'In production' mode. I'll monitor its performance over the next 15-20 days and provide an update (and then hopefully close this issue). Thanks @buckybytes for pointing this out. This was probably the issue in my case.

**Comment by buckybytes** [comment]
I'm personally using app passwords instead of OAuth for my Google Integrations.  I did a little research, and found out that I'll need to get all my apps switched to OAuth, because my app passwords will be revoked whenever I change my Google account password.

Seeing as I'm going through the process anyhow, I'd be happy to create documentation along the way.

Do you think the messaging page is the most appropriate for this?  I'd probably expect this information to be at:

https://ylianst.github.io/MeshCentral/meshcentral/#email-setup

**Comment by si458** [comment]
@buckybytes totally missed that section! nice catch!
maybe you could add it under the Email Setup as like a sub section if that makes sense?
like embedding meshcentral->login token for example
so it would be
Email Setup -> SMTP User/Pass
Email Setup -> SMTP OAUTH
then we can add others to it over time for different SMTP methods for different providers, again if that makes sense?

**Comment by buckybytes** [comment]
@si458 It looks like it'll be easy to do it in a way where it'll be easy to add providers.

I'll probably include a warning about the app password automatically being revoked as well.  That needs to get indexed by search engines in a couple more places.

As far as editing goes, I just PR to the gt-pages branch to make my suggestions, correct?

I hadn't realized there was a centralized place for the documentation until you suggested I edit it.  That'll be a great way to contribute until I get a better feel for the project.  I depend on MeshCentral and its related tools for so many aspects of my business, I'm hoping to be able to contribute someday.  Right now, my coding attempts have been functional, but unconventional at best, outright hacks at worst.  I'm getting there though.

**Comment by si458** [comment]
all the docs are in the `docs/docs` folder in the `master` branch
so to edit the file above edit this - https://github.com/Ylianst/MeshCentral/blob/master/docs/docs/meshcentral/index.md
then when we merge the PR, github actions automatically kicks in and creates the docs in `gt-pages` for us :)

**Comment by adnan29979** [comment]
Heyyy, I'd like to contribute to the docs as well. Is there any aspect of MeshCentral which has not yet been documented where I can contribute? @si458

**Comment by si458** [comment]
@adnan29979 in theory anything with the label `DOCS` in the issues, really needs to go somewhere in the docs or needs updating,
or if anything needs explaining better then plz have a crack at it!
again all docs are in the docs/docs folder and it uses mkdocs to generate them

**Comment by adnan29979** [comment]
Alright. I'm on it.

**Comment by si458** [comment]
@adnan29979 open a new discussion about anything in relation to the docs plz,
we can chat there 👍 
keep this about the SMTP issue

**Comment by adnan29979** [comment]
After changing my "Publishing status" from "Testing" to "In Production", it has been more than 30 days and I do not require updating the refresh token. So the solution to this issue is just to change the status of the project to Production. 
Thanks @buckybytes for the solution. 
Please add this in the Gmail SMTP Documentation update @buckybytes.
