### ISSUE TITLE
Error 502 bad Gateway after upgrade from 1.1.20 to 1.1.21

### ISSUE THREAD

**Issue by tootai** [Ylianst/MeshCentral#5853]
**Describe the bug**
https://mydomain.tld display 502 Bad Gateway error / nginx/1.22.1
after today upgrade of both node and meshcentral

**To Reproduce**
1. try to connect to server

**Expected behavior**
Able to login as it was the case before upgrade this morning

**Server Software (please complete the following information):**
 - OS: Debian12
 - Virtualization: kvm
 - Network: LAN
 - Version: 1.1.21
 - Node: 18.19.0

**Client Device (please complete the following information):**
 - Device: laptop
 - OS: Ubuntu 22.04
 - Network: Local to Meshcentral
 - Browser: Firefox, Google Chrome]
 - MeshCentralRouter Version: [if applicable]

** Other information **
Serveur is nginx, the setup is working since years. If I connect https://mydomain.tld:4430 I can connect, clients are showed but _not_ connected :(
  
**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mydomain.tld",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 4430,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "MyCompany",
      "title2": "Domain Url",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
meshcentral wouldn't return a 502 gateway error, that's an nginx error saying it couldn't connect to meshcentral

you have a few things wrong with your `config.json` under `settings`:

your nginx is doing the reverse proxy so you should set `trustedProxy: 'NGINXIP'` to get your clients ip addresses
also ur nginx is doing the TLS you should also set `tlsOffload: 'NGINXIP'`
also again ur nginx is doing the TLS so you should add `certURL: 'https://mydomain.tld'` under your `domains` section in `config.json`

**Comment by tootai** [comment]
Hi Simon

the certURL was in config.json, my bad at the time I copy the settings. I added the 2 other commands and get meshcentral back to live \o/.

Question now, why was it working well since ages till 1.1.21 w/o those 2 parameters ? 

Big thanks for your support

**Comment by si458** [comment]
Not a clue! The mystery of updates! Haha

**Comment by tootai** [comment]
Will accept your explanation, no choice ;)

**Comment by mcdullmedia** [comment]
I have the same issues on recent versions of meshcentral. 
Turns out the db was corrupted and removing all statistical db allows it to run fine.  But in weeks this problem will exist again.  There is enough disk space and I have no idea on whats the issue.
