### ISSUE TITLE
Non-Admin Users see usernames as ~google:UID for google accounts

### ISSUE THREAD

**Issue by cullorblind** [Ylianst/MeshCentral#5854]
**Describe the bug**
User Authorizations for a non-admin user are showing up as Google UIDs instead of friendly usernames.

**To Reproduce**
1. Login as admin
2. Go to Device and Add google user under User Authorizations
3. Give Remote Control access to user
4. Login as user and go to Device
5. User Authorizations shows user as google ID
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/d99d4355-5216-4f86-a9ca-a54d8d8adc99)

If I give the user "Server Rights / Manage Users", they can then see the usernames.
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/9199784e-f646-4336-9a97-77cdec232cfd)

**Expected behavior**
A user should be able to see who has access or is connected to their devices by name without user admin priviledges.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Rocky Linux 8.5
 - Network: Digitalocean
 - Version: 1.1.21
 - Node: 21.4.0

**Client Device (please complete the following information):**
 - Device: Any desktop running windows
 - OS: Windows
 - Network: Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Any device
 - OS: Windows
 - Network: Remote over WAN
 - Current Core Version (if known): Current Core: Dec 9 2022, 1508625241

**Additional context**
This also shows when a user is looking to see who is connected to the device via the blue connection indicator.  Shown here without and with user admin rights.
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/8dfbfe06-45f0-4fb3-ba80-9f969eb01c5d)
![image](https://github.com/Ylianst/MeshCentral/assets/4873651/7009095d-19b7-4321-8a0f-084d7ed21ed4)

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral.xxxx.net",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "AW",
      "title2": "MeshCentral",
      "ipkvm": true,
      "agentCustomization": {
        "displayName": "AW Support Agent",
        "description": "AW Support Agent for remote monitoring, management, and assistance of company owned equipment.",
        "companyName": "AW",
        "serviceName": "AWAgent",
        "fileName": "AWAgent",
        "image": "awlogo.png",
        "installText": "This is the application for the AW Support Agent.",
        "foregroundColor": "#85C3F7",
        "backgroundColor": "#004387"
      },
      "_minify": true,
      "ManageAllDeviceGroups": [ "awadmin", "masseyd-admin" ],
      "newAccounts": false,
      "agentInviteCodes": true,
      "_userNameIsEmail": true,
      "authStrategies": {
        "google": {
          "_callbackurl": "https://meshcentral.xxxx.net/auth-google-callback",
          "newAccounts": true,
          "_newAccountsUserGroups": [ "ugrp//xxxxxxxxxxxxxxxxx" ],
          "clientid": "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
          "clientsecret": "xxxxxx-xxxxxxxx-xxxxxxxxxxxxxxxxxxx"
        }
      }
    },
    "adair": {
      "dns": "meshadair.xxxx.net",
      "title": "Adair",
      "title2": "MeshCentral",
      "agentInviteCodes": true,
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    },
    "damon": {
      "dns": "meshcentral.yyyy.net",
      "title": "YYYY",
      "title2": "MeshCentral",
      "agentInviteCodes": true,
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "email": "admin@xxxx.net",
    "names": "meshcentral.xxxx.net,meshadair.xxxx.net,meshcentral.yyyy.net",
    "skipChallengeVerification": true,
    "production": true
  },
  "messaging": {
    "ntfy": true,
      "ntfy": {
        "host": "ntfy.sh",
        "userurl": "https://ntfy.sh"
    }
  }
}
```

**Comment by si458** [comment]
daft one, do u have any docs/guides how you setup google auth?
then i can try replicate it and fix it for you 👍

**Comment by cullorblind** [comment]
I created a project on our google workspace https://console.cloud.google.com and added the following info:
This should be pretty close.. It's been a while since I set it up.  I don't remember anything special about it.

Enabled APIs & services:
Nothing changed from defaults

Credentials Page:
Name: Meshcentral
Authorized Javascript origins: https://meshcentral.xxxx.net
Authorized Redirect origins:
        https://meshcentral.xxxx.net,
        https://meshcentral.xxxx.net/auth-google,
        https://meshcentral.xxxx.net/auth-google-callback

OAuth consent screen
User type: Internal

**Comment by si458** [comment]
all fixed for you!
took me a while to figure out the oauth setup with google. **need to do some docs (remind me plz someone)**
bug was because the node devices dont seem to pass the name in the links where as the mesh groups do?
so patched it to pass names over in the links, then it searches everywhere it can to get a name, including ur name haha
