### ISSUE TITLE
Chat and Notify buttons show even tho not ticked in permissions

### ISSUE THREAD

**Issue by exander77** [Ylianst/MeshCentral#5858]
This is more of a question, maybe? Maybe a bug.

If I create a user View Only and doesn't and doesn't tick Chat and Notifications, the user still has Chat and Notifications buttons visible. When I check it, it doesn't seem to change anything. Shouldn't it be No Chat and Notifications if it is enabled by default?

**Comment by exander77** [comment]
@si458 User permissions to device or device group.

**Comment by si458** [comment]
ah right ok yeh got you!
![image](https://github.com/Ylianst/MeshCentral/assets/765314/38a58a10-f859-43b5-a3f6-38ec18d13a37)
and you mean the 'Message' and 'Chat' buttons are still shown on the General tab of the device?
![image](https://github.com/Ylianst/MeshCentral/assets/765314/e7613820-99ae-4092-bed0-38e1854ee3c8)

**Comment by exander77** [comment]
Yes. That's it.

**Comment by si458** [comment]
hmmm ok i think the is a bug, will dig into the permission tomorrow and see if i can follow them

```
if (Q('p20remotecontrol').checked == true) meshadmin += 8;
if (Q('p20chatnotify').checked == true) meshadmin += 16384;

...

if ((meshrights & 8) && ((connectivity & 1) || ((node.pmt == 1) && ((features2 & 2) != 0)))) { x += '<input type=button value="' + "Message" + '" title="' + "Display a text message on the remote device" + '" onclick=deviceMessageFunction() />';  }
if ((meshrights & 8) && (connectivity & 1) || ((node.pmt == 1) && ((features2 & 2) != 0))) { x += '<input type=button value="' + "Chat" + '" title="' + "Open chat window to this computer" + '" onclick=deviceChat(event) />'; }                    
```

**Comment by exander77** [comment]
I looks like a frontend code? But the issue is surely in backend as well as these buttons work (it's not just that they are there). The other issue is also a backend issue, when I display the button, it still doesn't work.

**Comment by si458** [comment]
ive looked into it and a fix is incoming for the displaying of the buttons/icons

basically you cant use the chat/notify features WITHOUT having remote control ticked,
this is because the meshcentral needs to connect/access to the persons desktop to open up there web browser

BUT you can just tick 'no desktop/no files/no terminal' and the person wont have control of the remote device

**Comment by si458** [comment]
commit here with the display fix for you! https://github.com/Ylianst/MeshCentral/commit/3e23741cc8bee4a16c882c5a063a445d53313417 👍
