### ISSUE TITLE
Server Dicsonnected - due to one bad character (^) in package.json file

### ISSUE THREAD

**Issue by wolfie-cz** [Ylianst/MeshCentral#5867]
**Describe the bug**

Since last week (Exact date 19.February) my Meshcentral server is behaving strangely. I cannot connect to WEB GUI, as immediatelly after entering login detail I have message "Server Disconnected".  I completely reinstalled the server sevceral times, but it helped only for couple of minutes. I went bacx from ver 1.21 to stable 1.1.0 but same issue.

I have been using MC last 3 years with the same config, always used to have automatic update, and literally I have not touched the MC server in last 6 months, so I do not think I could be in wrong settings...  I switched the autoupdates off for debugging reasons now. But the disconnected message still appreares, even on Stable version 1.1.0.

When I delete all folders and re-install the server, it runs well for couple of minutes, but after 5 minutes or so the issue is comming back again. And all I can see is "Server disconnected"

Fortunatelly I had a working backup (full installation folder, not only data folder) and by comparing files I realised what is causing the issue  -  after some time the file package.json changes, respective one character "**^**" is added - the line No. 6 (meshcentral) which causes the "disconnection" of the server.

working version of packages.json looks like this:
```

{
  "dependencies": {
    "acme-client": "^4.2.5",
    "archiver": "^5.3.1",
    "loadavg-windows": "1.1.1",
    "meshcentral": "1.1.0",
    "node-windows": "^0.1.4",
    "otplib": "10.2.3"
  }
}

```
but after couple of minutes this file is changed into:

```
{
  "dependencies": {
    "acme-client": "^4.2.5",
    "archiver": "^5.3.1",
    "loadavg-windows": "1.1.1",
    "meshcentral": "^1.1.0",                                 <-- this is the problematic line
    "node-windows": "^0.1.4",
    "otplib": "10.2.3"
  }
}

```

if I delete the "^" sign and restart the meshcentral service, the web gui starts immediatelly, but after couple of minutes it says again "Server Disconnected" and I have to delete ^ again and restart.

I found a workaround, but this is not a solution: Lock the file so that it does not get overwritten with ^ line....

 First I deleted "^" and marked the packages.json as read-only file, but this did not help and despite of read-only attribute, meshcentral was still overwriting the file with "a bad line with ^".
 
So I had to remove write permissions from this file for "system user" and now only Administrator can change it. As Meshcentral is running as a windows service, it does not use Administrator account and therefore now Meshcentral does not have the right to change the paskages.json file and since then I did not have any disconnection...

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Windows 11, lastest updates

 - Network: WAN only
 - Version: [1.1.0]
 - Node: [21.6.1]

**Additional context**

**Your config.json file** (sensitive infomration are replaced by Xs)
```
{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
	"__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
	"settings": {
		"cert": "XXXXXXXX.XXXX.XXX",
		"WANonly": true,
		
		"sessionKey": "XXXXXXXX",
		"port": 443,
		"aliasPort": 8443,
		"selfUpdate": true,
		"webRTC": true,

	},
	"_peers": {
		"serverId": "server1",
		"servers": {
			"server1": {
				"url": "wss://XXXXXXXX.XXXX.XXX:8443/"
			},
			"server2": {
				"url": "wss://XXXXXXXX.XXXX.XXX:8443/"
			}
		}
	},
	"domains": {
		"": {
			"title": "MeshCentral",
			"title2": "MeshCentral Remote",
			"minify": true,
			"_newAccounts": true,
			"_userNameIsEmail": true,
		}
	},
	
	"letsencrypt": {
		"__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
		"email": "XXXXX@XXX.com",
		"names": "XXXXXXXX.XXXX.XXX,XXXXXXXX.XXXX.XXX,XXXXXXXX.XXXX.XXX,XXXXXXXX.XXXX.XXX",
		"production": true
	}
}
```

**Comment by si458** [comment]
this is because of an NPM bug and not a meshcentral bug
to fix the issue remove the `^` as you have done,
set which version you want in `package.json`,
then `npm install` so it installs the correct version,
then set `"selfUpdate": false`,
the `selfUpdate` will auto update meshcentral everytime you start it and on a schedule,
so its best to disable it and then update it from either npm install or the web ui

**Comment by wolfie-cz** [comment]
Hi si458, thank you for you reply 

I went through the steps, and then I run npm install from cmd but after updating to 1.1.21 I have the same issue - Server disconnected,click to reconnect.
But now I cannot make it working with the workaround, as package.json now does not contain ^ on the meshcentral line... 

Now the file is:

```
{
  "dependencies": {
    "acme-client": "^5.3.0",
    "archiver": "^5.3.1",
    "loadavg-windows": "1.1.1",
    "meshcentral": "1.1.21",
    "node-windows": "^1.0.0-beta.8",
    "otplib": "10.2.3"
  }
}

```
I also tried removing three ^ in this file, so file packages.json now does not contain any ^ but it did not help either

When I try to run the MC as program (not service) to see any error, there is no error in the console:

```
node node_modules/meshcentral

MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.1.21, WAN mode.
MeshCentral Intel(R) AMT server running on xxxx.xxx.xxx:3433.
MeshCentral HTTPS server running on xxxx.xxx.xxx:443, alias port 8443.

```

**Comment by si458** [comment]
so its starting correctly, so the is something wrong with the startup service/script.
how did you install it to begin with?
do you have `/etc/systemd/system/meshcentral.service` and can you output its contents?

**Comment by wolfie-cz** [comment]
I run this on Windows 11 PC, not Linux

I do not think that it should be a service issue, MC is acting the same if I start it as service or from cmd, in both cases there is a message server disconnected (ver.1.1.21) if I run it from cmd with command "node node_modules/meshcentral", I just can see that it started and it is listening on the ports, but behaviour is the same.. Server disconnected. If I revert back to 1.1.0, and disable autoupdate (and prevent packages.json from overwriting) only then I can login to the GUI.

**Comment by si458** [comment]
sorry you did say above it was windows,
this is a strange one and seems to me like its getting itself confused or maybe the browser is?
have you tried accessing the site via private browsing/cognito mode?

i no @Ylianst added a security feature `allowedOrigin` so it could also be that?

do you access ur meshcentral via a DNS name?
try adding `allowedOrigin: ['DNSNAMEHERE.COM']` under `settings` in your config.json
then start meshcentral from the command line `node node_modules/meshcentral` (as you do before)
then try accessing ur webpanel again normally and via private mode

**Comment by wolfie-cz** [comment]
I was always trying also from inconginto, just to be sure that cache is not affecting the results. However there is no difference

I somehow cannot make it working with allowed origin settings, unable to parse json.
at https://github.com/Ylianst/MeshCentral/blob/master/meshcentral-config-schema.json I found the syntax but it seems I am unable to apply it. If I just copy and paste it, meshcentral will start (but with same result -disconnected), but if I change it to have my duckdns in it, there is parse error.

	```

		"allowedOrigin": {
            "type": [ "array", "boolean" ],
            "default": false,
            "uniqueItems": true,
            "description": "A list of allowed hostnames for HTTP request origin header. If false, a default list is created, if true, all hostnames are allowed.",
            "items": { xxxxx.duckdns.org
              "type": "string"
            }
          },
		
```

**Comment by si458** [comment]
dont copy+paste the config-schema! 
this is just for information purposes and for visual studio code!
you should of set the allowedOrigin like so
```
{
  "settings": {
    allowedOrigin: ['xxxxx.duckdns.org'],
    ....
  },
  "domains": {
    "": {
      ...
    }
  }
}
111

**Comment by wolfie-cz** [comment]
Well, that is what I did at first, but I was getting parse errors. I already tried following variations:

allowedOrigin: ['xxxxx.duckdns.org'],
allowedOrigin: ['xxxxx.duckdns.org'],
allowedOrigin: [xxxxx.duckdns.org],
allowedOrigin: "xxxxx.duckdns.org",
allowedOrigin: xxxxx.duckdns.org,

and all of them also with "allowedOrigin" 

but every try - error parsing. So as the last resost I tried the manual :) but did not work either

The part of the config is here (but still parsing error)   If I remove allowedOrigin line, it will start but DIsconnected ....: 

```

{
	"$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
	"__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
	"settings": {
		"cert": "XXXXXXXX.XXXX.XXX",
		"WANonly": true,
		"allowedOrigin": ['xxxxx.duckdns.org'],
		"sessionKey": "XXXXXXXX",
		"port": 443,
		"aliasPort": 8443,
		"selfUpdate": true,
		"webRTC": true,

	
```

**Comment by si458** [comment]
weird? try this comment/post - https://github.com/Ylianst/MeshCentral/issues/5826#issuecomment-1951914601

**Comment by wolfie-cz** [comment]
OMG, you have just cracked it!
with the line   "allowedOrigin": "xxxxx.duckdns.org"   under DOMAINS,  MeshCentral server 1.1.21 is working as expected and I can connect to web GUI!

Thank you very much

**Comment by si458** [comment]
no worries, glad its sorted!
@Ylianst added the 'allowedOrigin' due to a security vulnerability!
https://github.com/Ylianst/MeshCentral/security/advisories/GHSA-cp68-qrhr-g9h8
so in reality you need to add this now to every meshcentral instance you have setup and make sure its set to your domain names!
