### ISSUE TITLE
Have meshcmd read the password as command line prompt (stdin)

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#587]
When starting up meshcmd, be able to specify --password and then leave the password blank, allowing the user to enter it in without it being displayed.

Mock up:

![Screenshot from 2019-10-18 20-01-36](https://user-images.githubusercontent.com/7572742/67137048-0fb70180-f1e4-11e9-88ad-a4264c3dfc37.png)

**Comment by Ylianst** [comment]
Oh, that is a good one!

**Comment by Ylianst** [comment]
Come to think of it, Bryan may need to enable this feature. Adding him.

**Comment by MailYouLater** [comment]
Not sure why you'd want to supply the `--password` parameter without a password for this. I would think that it should simply detect that no password has been supplied (e.g. no `--password` parameter at all) and ask for it. It would be really nice if it would ask for a username too, and if you just hit enter without entering a username, then it should use the default username ("admin", I think).

**Comment by krayon007** [comment]
stdin support is already implemented. I can't remember if it echos to stdout tho, I'll have to look into it.

**Comment by MailYouLater** [comment]
Wait, you can enter username/password via stdin? How? I wasn't able to figure out how to do that last time I messed with meshcmd.

**Comment by D4V3M0NK** [comment]
@krayon007 Bryan, I can't get stdin to work.  I'm currently running 0.4.2-u

**Comment by MailYouLater** [comment]
Nevermind me.  I had meshcmd and meshctrl confused.  I took a look at meshcmd, and I can't get it to work at all right now.  When I place a `meshaction.txt` next to `meshcmd.exe` and run `meshcmd --route`, I get this:

    Looking for server...
    
    [2019-10-22 01:08:53 PM] FATAL EXCEPTION [meshcmd_611E986510532851.exe] @ [FuncAddr: 0x00007ff772942b90 / BaseAddr: 0x00007ff7729a96dc / Delta: 420684]

I don't want to high-jack this thread, so I won't go into any more detail here. If there's a way to gather more helpful data (like a core dump) please let me know and I'll open a new issue for this once I have it.

**Comment by dinger1986** [comment]
possibly implemtned @si458

**Comment by si458** [comment]
@dinger1986 now fully implemented 😉 https://github.com/Ylianst/MeshCentral/commit/a3717095e72f7fb1f7ff2699986781bada9bfaae
