### ISSUE TITLE
Feature Request: meshcmd and "meshaction.txt"

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#588]
It would be really beneficial to allow meshcmd to take an argument of a meshaction.txt file, that's not called "meshaction.txt". This would allow a user to retain a list of files and then set up (in my case) routes to remote servers without having to always copy them to a meshaction.txt file.  At the moment I could easily have 100 files all dedicated to individual remote servers, but I have to run a utility that copies one of those files to overwrite meshaction.txt and then launches meshcmd. They'd be like RDP files within Windows.

At the moment:
> ./meshcmd route --password abcdef
looks for meshaction.txt and sets up the (route in this case)

What would be lovely:
> ./meshcmd serverA.txt
looks for serverA.txt which contains everything the meshaction.txt file would contain.

1. ~~Would we still need the "route" action on the command line, considering that within serverA.txt, "action" is already defined as "route"?~~ (removed as answered: see notes below)
1. Along with Issue#587 the files wouldn't need to contain the password definition, making them safer to reside on a disk

**Comment by D4V3M0NK** [comment]
By the way, the penny dropped on me this evening with regards to the power of meshcmd. In prior issues that I've raised, I didn't understand that MCR is (probably?) a GUI version of meshcmd but that meshcmd is a cross platform control.  I knew that MC2 was already assisting me greatly in being able to handle remote systems, but (being a Linux user) I believed that there was a void in not being able to grant Linux users the same power that Windows users have.

I obviously now stand very firmly corrected.

This evening I've been able to connect to my remote servers, using the SSH client that I want to use, as well as setting up MySQL workbench connections to their databases. Please advise the powers that be that this solution far exceeds anything else that's on the market, and permit me to congratulate them (and Ylian, Brian et al) on putting the effort and resources in to make this a truly top notch solution.

**Comment by D4V3M0NK** [comment]
And whilst I'm at it ... would the config file be able to set up multiples connections?
[meshactionMultipleRoutes.txt](https://github.com/Ylianst/MeshCentral/files/3746189/meshactionMultipleRoutes.txt)

**Comment by Ylianst** [comment]
The problem with your issues is that they are too good. Yes, your suggestion to specify a different "meshagent.txt" and many routes support are excellent. By the way, MeshCmd and MeshCentral Router and two different implementations (MeshCmd is not part of MeshCentral Router). Just letting you know because both will have different features, bugs, etc.

**Comment by D4V3M0NK** [comment]
Mate, I see how many issues / feature requests you have to deal with and frequently I hold back a little as I don't want to add to your woes, but - frankly - I love this software and I'm sure I'm only using a fraction of it's capabilities. 

> I just got to get multi-language support and the new meshagent out the door first.

Well, we don't want you getting bored now, do we?  ;o)

**Comment by jsastriawan** [comment]
Dave, Meshcentral routing protocol is actually simple. I have written my own utility based on NW (mc2router) and it has been very useful to tunnel traffic using mesh agent relay.

**Comment by MailYouLater** [comment]
Here's a link, in case anyone wants to check out @jsastriawan's [mc2router project](/jsastriawan/mc2router).

**Comment by baikal** [comment]
There is already support for a different "meshactions.txt" with meshcmd:
`meshcmd route --actionfile anotherfilename.txt `

**Comment by D4V3M0NK** [comment]
@baikal Thank you! I didn't know that was an option (I don't see it in the command line help)

**Comment by D4V3M0NK** [comment]
BTW: the "route" parameter doesn't need to be included when calling meshcmd, it would appear that the "action" setting in the called actionfile is parsed, therefore #1 in the OP has already been addressed.

**Comment by D4V3M0NK** [comment]
I'm going to close this issue as @baikal has answered it.  I will open up another issue regarding setting up multiple routes within a single file

**Comment by slavitch** [comment]
Please reopen this so that --actionfile is properly documented.
