### ISSUE TITLE
suspect machine under my devices... why

### ISSUE THREAD

**Issue by wvt-adm** [Ylianst/MeshCentral#589]
good morning mc team - why i found this two machines in my devices? i have not give out the meshcentral client to any other person - and i have only 20 machines to thest the product... in the log i see only that this two machines have now installed the meshcentral client... no other connections
i see... any idea? thanks a lot am
![suspect](https://user-images.githubusercontent.com/56296924/67194040-a65b0c80-f3f6-11e9-9047-5eec41ec731a.JPG)

**Comment by ryanblenis** [comment]
The 2 IP's listed are from Germany and India. Have you made the installers available via a publicly accessible website (e.g. uploaded to your web site for easier downloading of your agent / Dropbox link, etc.)? The site could have been crawled and a machine could have opened the program, or a user you may have sent the agent to via email could have been compromised.

**Comment by wvt-adm** [comment]
this i found out also - but i know that this machines are not compromised - and the installer i have only... so im really confused whats this is - and in the log i see only that the meshagent has installed on this machines - no connection ect. was establishd... - have mc a detailed log - or only this was i found in the webif? - thanks a lot - am

**Comment by Ylianst** [comment]
A quick note to say that if a rogue agent connects to your server, it does not get any rights on your server. You could do a remote uninstall the agent by typing "uninstallagent" in the agent console as suggested in #581.

**Comment by wvt-adm** [comment]
thanks a lot for your input - this i will make it. am
