### ISSUE TITLE
Add support for Let's Encrypt DNS Challenge

### ISSUE THREAD

**Issue by tmanok** [Ylianst/MeshCentral#5892]
Could we please see a new feature that enables Let's Encrypt DNS Challenges rather than HTTPS challenges? That way MeshCentral would not need to be exposed to the internet and ACME can do its job behind a FW/NAT. 

One of the best ACME implementations I have found is on Proxmox Virtual Environment:
https://pve.proxmox.com/wiki/Certificate_Management

Consider reviewing the documentation when you have time to get a sense of the features available. Perhaps some of it can be ported, though that project is built in RUST and Perl... 

Thanks,

Triston

**Comment by si458** [comment]
we use the `acme-client@4.2.5` npm library which looks like it does support DNS
i think we would just need to work out HOW to do it because we cant automate insertings the DNS records
you as the admin would have to do that manually and it just keep checking for the dns record before carrying on

**Comment by tmanok** [comment]
For further reading, there are seemingly many API implementations: https://github.com/acmesh-official/acme.sh/wiki/dnsapi

Cheers,


Triston

**Comment by dinger1986** [comment]
Use certbot standalone to get the cert then add the cert to your config.json, I can't see any advantage to having that built into meshcentral natively

**Comment by Ylianst** [comment]
So, I looked at doing Let's Encrypt DNS Challenge in the past. With our ACME client, this would have to be a manual process. You would have to edit the DNS records for your provider manually and the problem with that is that MeshCentral would not be able to renew the certificate automatically. It would be a manual process each time.

Now, if there was a easy NodeJS library that would take your DNS providers credentials and auto-edit the DNS records for you, I could consider it. Of course, you would have to give these credentials to MeshCentral and I am not a fan of this from a security perspective.

Note that you can setup MeshCentral behind a reverse-proxy and MeshCentral does not have to have the public facing certificate. MeshCentral will auto-detect when the front facing certificate is updated, etc. So, you can have the front facing reverse proxy get the certificate anyway it wants.

In any case, if there is a NodeJS ACME library that is easy to use and would do it, let me know. Obviously, we should not going to implement all the DNS provider's logins ourselves.

**Comment by dinger1986** [comment]
Like I said certbot can do this form the command line natively and works very easily. Once the cert has been acquired it can be used with mesh. To me makes sense to script that up (I can write a script if that lets you close this)

**Comment by Ylianst** [comment]
Yes, certbot is certainly a great correct and very much supported option.

**Comment by Ylianst** [comment]
I will close this since, certbot is really the way to go.

**Comment by acrolink** [comment]
> add the cert to your config.json

How to do that ? I have tried, but mesh continued to serve its own self generated one.

**Comment by si458** [comment]
@acrolink are u trying to do dns challenge for lets Encrypt as this won't work unless have to use http challenge instead

**Comment by acrolink** [comment]
> @acrolink are u trying to do dns challenge for lets Encrypt as this won't work unless have to use http challenge instead

No, I just asked how to specify custom cert file for Mesh, e.g. the one I can generate by certbot directly.

**Comment by acrolink** [comment]
@si458 The solution is outlined here, it is working:
https://ylianst.github.io/MeshCentral/meshcentral/#nginx-reverse-proxy-setup
