### ISSUE TITLE
[Feature request] Request viewing and control access

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#590]
Hi,

For some users it might be kinda invasive for the administrator just to take control of their system without them knowing.
It would be great with a feature that prompted the user for allowing both viewing and controlling access of their system.

**Comment by penguinthingie** [comment]
![image](https://user-images.githubusercontent.com/51331094/67209637-b5858e80-f3e5-11e9-9b80-4547a663eb14.png)

User consent feature is available within the group the device belongs to. Turn them on as needed.

**Comment by GnaXi** [comment]
Thanks! Had a hard time finding the settings for the device groups :P
