### ISSUE TITLE
DateTime range sharing bug time select

### ISSUE THREAD

**Issue by exander77** [Ylianst/MeshCentral#5902]
I am not sure if this is a feature request or bug request, but the DateTime range flatpickr is pretty bad. I still hadn't figured out how to pick a different stand and end time. So maybe even a bug.

Can We replace it with two standard DateTime pickers?

Also, it shows AM/PM even if not compatible with locales, and I am not sure how to switch between AM/PM, clicking does nothing.

**Comment by si458** [comment]
im not sure what you are talking about?
we dont have any date/time pickers anywhere in meshcentral? (i could be wrong again)
can you share picture?

**Comment by si458** [comment]
seems to work ok here? what language is your UI?

https://github.com/Ylianst/MeshCentral/assets/765314/f7d53aed-1c4d-4322-adf4-0543a54ad183

**Comment by si458** [comment]
HUH just spotted after i uploaded that, its jumping in 5 min intervals?
need to check if it should be that or 1 min intervals?
you can still click the number box tho and type in a digit no problem tho

**Comment by exander77** [comment]
I have cs set, AM/PM does nothing. Maybe it's disabled, but it's, but I can't tell. You also cannot set diffent start and end time. I looked into documentation and think this component does't support this mode.

**Comment by si458** [comment]
well found the bug with the jumping 5 minutes `minuteIncrement` default is 5 minutes!
and that doesnt help if its 10.02 for example, its then jumping to 10.07, not 10.05!?
will look into it as the must be a bug

**Comment by exander77** [comment]
The 5-minute increments doesn't really bug me that much. You can write it by hand. But I haven't found any way how to input different start and end time. There only single time select.

**Comment by exander77** [comment]
The AM/PM looks clickable, it changes color when hovered. But does nothing.

**Comment by si458** [comment]
works fine here in cs? what browser are you using?

https://github.com/Ylianst/MeshCentral/assets/765314/e37f9fe1-1e9c-4015-b670-1985ee3f1c39

**Comment by exander77** [comment]
Firefox on Linux, no extensions.
