### ISSUE TITLE
MeshCentral.com windows download link is broken

### ISSUE THREAD

**Issue by InnerSanctuary** [Ylianst/MeshCentral#5918]
Cannot download the windows installer on the mesh central website.
To download the windows installer linked here:
https://www.meshcommander.com/meshcentral2

The actual link it points to and gives the 404 error is here:
https://meshcentral.com/info/extra/MeshCentral2/MeshCentralInstaller-2.11.exe

**Comment by si458** [comment]
This is now located on https://meshcentral.com/downloads.html page

**Comment by si458** [comment]
Also the meshcommander.com website is no EOL and SHOULD NOT BE USED AT ALL!!!
