### ISSUE TITLE
Installer locks up on "Installing MeshCentral Service"

### ISSUE THREAD

**Issue by InnerSanctuary** [Ylianst/MeshCentral#5919]
**Describe the bug**
Tried to install several times on 2 different machines (windows 10 pro) and both machines lock up at the same point using the windows MSI installer.

It locks up at this window:
"Installing MeshCentral Service..."
"This may take several minutes."

Tried reinstalling using "run as administrator" and still locking up at the same screen.

I also cannot find any install logs.  Can someone point them out to me?

**Comment by InnerSanctuary** [comment]
FYI I found a work around.  Install from the command line to c:\MeshCentral then re-run the MSI for successful service install.

mkdir meshcentral
cd meshcentral
npm install meshcentral
node node_modules/meshcentral

**Comment by si458** [comment]
This is because the is a bug with the meshcentral installer.
You should be using either the msi or npm not both!?
