### ISSUE TITLE
Group Action Export Device Information Missing "BIOS Serial" field

### ISSUE THREAD

**Issue by jwhips** [Ylianst/MeshCentral#5947]
**Describe the bug**
Group Action Export Device Information Missing "BIOS Serial" field

**To Reproduce**
1. Go to 'My Devices'
2. Click on 'Select All' -- > Click 'Group Action' --> Choose the Operation 'Export Device Information' --> _Check off 'Include Device Details'_ ----> Click 'devicelist.csv'
3. Open CSV in favorite open source CSV / Spreadsheet application...
4. See missing field 'BIOS Serial'

**Expected behavior**
More fields please?
 
Is more info necessary?  Thanks for all you do!

**Comment by si458** [comment]
oh yeh nice catch!
will add it in tomorrow for you, then will be in next release!
