### ISSUE TITLE
Ubuntu Remote Issues with Wayland 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#5948]
Hi MeshCentral Team,

So I notice a lot of folks on the MeshCentral Reddit groups and other social media platforms calling out the Wayland with MeshCentral black screen, no screen, X screen. I am wondering if maybe something like that of the [https://github.com/udevbe/greenfield](url) could be having libraries to harness to address the wayland disabling issue. This seems to be the only way to get the system to show, but upon upgrades the person may forget and not run a script/command to disable the wayland. So since Ubuntu is not looking to drop the Wayland feature, we must look at ways to show with the feature enabled long term, or possibly make the MeshCentral code smarter with a detection method and notify the user on disabling the Wayland feature.

[https://www.github.com/udevbe/greenfield](url)
History: [https://wayouttheresoftware.blogspot.com/2023/07/some-history-about-greenfield.html](url)
So can this code help? Ideas? Thoughts? @Ylianst @krayon007 @si458.

-SomeGuru

**Comment by si458** [comment]
This is a duplicate,
The is already issues open about this, https://github.com/Ylianst/MeshCentral/issues/2719
Sadly I'm not a c++ developer so I can't look into it.
So unless somebody can help out and check the meshagent code and work it out for us,
We are stuck with x11 at the moment
