### ISSUE TITLE
Devices duplicating themselves 

### ISSUE THREAD

**Issue by stoehrmark** [Ylianst/MeshCentral#5950]
On my system I have devices that keep duplicating themselves. When I first installed the OS (Linux) on the PCs MeshCentral was installed. I then cloned that OS image to may PCs. I then changed each PC to a new device in mesh central. But now they keep generating new devices? How can i fix this remotely? And thank you for this amazing project!!

![mesh](https://github.com/Ylianst/MeshCentral/assets/24501941/b1e86147-d679-41cd-84e1-bc885836dee3)

**Comment by si458** [comment]
This is not a bug, 
This happens because the ip addresses/mac addresses change on the remote device
The fix is to add `skipmaccheck=1` into your .msh file and restart the meshagent
https://ylianst.github.io/MeshCentral/meshcentral/agents/#agent-msh-options
