### ISSUE TITLE
archiver Error after updating to 1.1.22

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#5952]
**Describe the bug**
Updated to 1.1.22 and the server did not come back up after updating. So I logged in to the server via ssh and stopped the service and ran node node_modules/meshcentral. With luck the server started back up, So I went to the server logs and it shows this error.
```
-------- 3/25/2024, 1:10:58 AM ---- 1.1.22 --------

/home/meh324/node_modules/archiver-utils/node_modules/minimatch/dist/cjs/ast.js:86
    #fillNegs() {
             ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/meh324/node_modules/archiver-utils/node_modules/minimatch/dist/cjs/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/meh324/node_modules/archiver-utils/node_modules/glob/dist/commonjs/index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

Also the server says it "Failed to load web certificate at: "https://server.com, host: "server.com". When I run the le command to check the ssl certificate it says its valid for 72 days. All agents came back online.

**To Reproduce**
1. update to 1.1.22

**Server Software (please complete the following information):**
 - OS: Ubuntu server 22.04
 - Virtualization: none
 - Network: WAN
 - Version: 1.1.22
 - Node: v21.7.1

**Additional context**

Configuration File (removed sensitive information) 
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "cert": "server.com",
    "WANonly": true,
    "port": 443,
    "redirPort": 80
  },
  "domains": {
    "": {
      "certurl": "https://server.com",
      "title": "Server",
      "_newAccounts": false,
      "agentInviteCodes": true,
      "authStrategies": {
        "azure": {
          "newAccounts": true,
          "clientid": "myclientid",
          "clientsecret": "myclientsecret",
          "tenantid": "mytenantid"
        }
      },
      "agentCustomization":{
        "displyName": "server",
        "description": "mydesc",
        "companyName": "server",
        "serviceName": "Agent",
        "fileName": "Agent"
      }
    }
  },
  "letsencrypt": {
    "email": "user@server.com",
    "names": "server.com",
    "production": true
  }
}
```

Service file
```
[Unit]
Description=MeshCentral Server
[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /home/meh324/node_modules/meshcentral
WorkingDirectory=/home/meh324
Environment=NODE_ENV=production
User=meh324
Group=meh324
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
AmbientCapabilities=cap_net_bind_service
[Install]
WantedBy=multi-user.target
```

**Comment by si458** [comment]
this seems to be related to the `archiver` module which @Ylianst updated the other day,
not sure why its crashing, will have to look into it

**Comment by si458** [comment]
@quizhead the error is right there... 
`[Error: EACCES: permission denied, open '/home/quizhead/meshcentral/meshcentral-data/meshcentral-power.db']`

the file meshcentral-power.db ISNT the same as whats inside your meshcentral.service OR whatever user you are using to RUN node with, so make sure they all match

**Comment by si458** [comment]
@quizhead please open an issue in the 'discussions' this thread is about the archiver bug

**Comment by si458** [comment]
@meh324 just looked into this,
it appears `minimatch` which is a dependency for `archiver` now required node 16 or above,
you say you are using node 21 which might be the case when running `node node_modules/meshcentral`
can you check your startup scripts are using the correct node version?

**Comment by ctrlaltca** [comment]
I had the same error on Ubuntu 22.04 (using nodejs 12) and fixed it by installing nodejs version 20.
```
npm install -g n
n lts
node --version
```
I had to edit /etc/systemd/system/meshcentral.service changing /usr/bin/node to the new path /usr/local/bin/node for the new version of nodejs to be picked up.

**Comment by si458** [comment]
@ctrlaltca yes the min requirement for meshcentral was 12 but im guessing the `archiver` now means we need to upgrade it now to 16 at least,
but really people should be using at least the LTS version (20)
