### ISSUE TITLE
Filter /Search for username

### ISSUE THREAD

**Issue by MarkStephan89** [Ylianst/MeshCentral#5958]
Hi, 
first --> Super super super project !!! :)

My question/request: 
It is possible to search/filter for the username? (or better --> all the columns)

//edit: If the device is down, then the (last) username is empty....e.g. a new field "last username"?

Thanks!

**Comment by si458** [comment]
`u:username` https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#search-or-filter
