### ISSUE TITLE
Feature Request: Absolute/Hard URL links for managed devices

### ISSUE THREAD

**Issue by troymroberts** [Ylianst/MeshCentral#5969]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

I am currently writing internal Knowledgebase articles for support staff in my organization with details on specific servers. However, I can't add a link for specific servers to the KB article as meshcentral urls are more dynamic, I guess. Best I can do is do an invite link. But that is less than ideal as these articles are intended for internal users.

So right now, i just have to specify the machine name and instruct staff to find it.

Ideally i would like to be able to generate a URL that would link a meshcentral user back to the specific device being managed so i can hard link them from a KB article. They user would have to login and authenticate with MC as normal but upon login takes them directly to the device page.

**Describe alternatives you've considered**

I have tried generating invite links but they are less than ideal for a few reasons e.g. authentication.

**Additional context**

**Comment by troymroberts** [comment]
> the links are already static `https://meshcentral.mydomain.com/?viewmode=10&gotonode=LONGDEVICEID` -> takes you to general tab `https://meshcentral.mydomain.com/?viewmode=11&gotonode=LONGDEVICEID` -> takes you to remote tab `https://meshcentral.mydomain.com/?viewmode=12&gotonode=LONGDEVICEID` -> takes you to terminal tab `https://meshcentral.mydomain.com/?viewmode=13&gotonode=LONGDEVICEID` -> takes you to files tab `https://meshcentral.mydomain.com/?viewmode=17&gotonode=LONGDEVICEID` -> takes you to general tab
> 
> in theory the deviceid should never change!
> 
> edit: you might see the `viewmode` is the secret to what panel you would like shown!

Weird, it wasn't working on my server and was dumping me to the Device List when I tried this.

As a sanity check i rebooted the server and it's working as expected now

**Comment by si458** [comment]
@troymroberts nothing like a good
![image](https://github.com/Ylianst/MeshCentral/assets/765314/45068589-6714-4532-81c7-f5ec72edccc6)
