### ISSUE TITLE
Unable to find mongodump.exe, MongoDB database auto-backup will not be performed

### ISSUE THREAD

**Issue by clevere12** [Ylianst/MeshCentral#5971]
**Describe the bug**
Mongodump.exe cannot be found

**To Reproduce**
Install Mongodb and Meshcentral.
Restore old meshcentral db with mongodump.exe
Go into Meshcentral
Get the error .. 

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Windows Server 2019
 - Mesh Server vsion: 1.1.22

**Additional context**
Basically did a new install and restored a backup from another server. It was fine. But I noticed an error that mongodump.exe cannot be found, even if the path is correct. Any ideas?

**Your config.json file**
{
   "settings": {
      "cert": "myserver.com",
	  "port": 443,
	  "redirPort": 80,
      "wanonly": true, 
      "_minify": true,
      "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
      "mongodbcol": "meshcentral"
   }, 
   "_autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Server\\7.0\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 10,
      "zipPassword": "ZipperPass",
      "backupPath": "c:\\Meshbackups",
         "maxFiles": 10
      },
   "domains": {
      "": {
         "newaccounts": false
      }
   },
     "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "email": "anemail@mydomain.com",
    "names": "a domains@domain.com",
    "production": true
  }
}

**Comment by Otsegox** [comment]
Just throwing this out there. I do not know for sure, but this being commented out may be the culprit.

"_autoBackup": {

I'm pretty sure that makes it ignore all of the autobackup settings.

**Comment by clevere12** [comment]
Ah, yes agreed.
Removed the comment and now ...

Server Warnings

WARNING: Unrecognized configuration option "autobackup".
WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed

Mongo is still broken and autobackup .. not recognized.

**Comment by Otsegox** [comment]
> Ah, yes agreed. Removed the comment and now ...
> 
> Server Warnings
> 
> WARNING: Unrecognized configuration option "autobackup". WARNING: Unable to find mongodump.exe, MongoDB database auto-backup will not be performed
> 
> Mongo is still broken and autobackup .. not recognized.

I'd say this is a step in the correct direction, at least.  I got nothing else at this time.  My install in on Ubuntu, and I have zero Windows experience with the server.

**Comment by si458** [comment]
`autoBackup` should be INSIDE of `settings` of your `config.json`
https://jsoneditoronline.org/#left=cloud.b4467284bf5c4567982009838b900e0f
(click right arrow in copy to get a tree view on right hand side)

also you should set `mongoDumpPath` inside of `autobackup` to the full path of where mongodump.exe is located

**Comment by si458** [comment]
you can use https://jsonlint.com to verify your json data

you are missing a comma after ` "mongodbcol": "meshcentral"`

also i think your `mongodumppath` needs double `\\` in them
`c:\\Program Files\\MongoDB\\Server\\7.0\\bin\\mongodump.exe`

**Comment by clevere12** [comment]
Thank you kindly! Well butter my biscuits, the comma was killing me .. well that an the wrong placement of autobackup .. Thank you so much for your help!


{
"settings": {
"cert": "mysite.hello.com",
"port": 443,
"redirPort": 80,
"wanonly": true,
"_minify": true,
"mongodb": "mongodb://127.0.0.1:27017/meshcentral",
"mongodbcol": "meshcentral",
"autoBackup": {
"mongoDumpPath": "c:\\Program Files\\MongoDB\\Server\\7.0\\bin\\mongodump.exe",
"backupIntervalHours": 24,
"keepLastDaysBackup": 10,
"zipPassword": "Wonky",
"backupPath": "c:\Meshbackups",
"maxFiles": 10
}
},
"domains": {
"": {
"newaccounts": false
}
},
"letsencrypt": {
"comment": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
"email": "[myemail@company.com](mailto:myemail@company.com)",
"names": "mysite.website.net",
"production": true
}
}

**Comment by clevere12** [comment]
Simon Rocks.

**Comment by NiceGuyIT** [comment]
> Simon Rocks.

@clevere12 Show the :heart: and sponsor Simon :point_right:  <https://github.com/si458> (Links on left hand side)

(If you have already, please ignore this message.)
