### ISSUE TITLE
Don't have authorization to view this page.

### ISSUE THREAD

**Issue by moonbug** [Ylianst/MeshCentral#598]
I installed MeshCentral using npm and Windows Installer v2.1, but both installations shows a blank page in FireFox and it shows, "Access to ip was denied. You don't have authorization to view this page," in Chrome when I access the page from a browser in Windows 10. 
When I add IP:4433, it shows MeshCentral2 MPS server.
Intel® AMT computers should connect here.

**Comment by Ylianst** [comment]
I am going to guess there is a firewall blocking you ports 80 and 443 or you have IIS running grabbing these ports.

**Comment by MailYouLater** [comment]
I'd check if you have a firewall blocking you first, but if it's something else operating on ports 80 and 443 on the same server, then you can find out what is listening on those ports by opening a command prompt window, executing `netstat -ano | find /I "Listening"`. You'll get output like this:

```
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       64200
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       64200
  TCP    192.168.0.5:8080       0.0.0.0:0              LISTENING       18364
  TCP    127.0.0.1:81           0.0.0.0:0              LISTENING       1012
  TCP    [::]:80                [::]:0                 LISTENING       64200
  TCP    [::]:443               [::]:0                 LISTENING       64200
```

Then find the line(s) where the second column ends with the a colon followed by the port you're looking for (i.e. `:443`) and look at the number at the end of the line. This is the "Process ID".
Open Task manager, switch to the "Details" tab, find the process that corresponds with that Process ID. (You can click the "PID" label at the top to sort by Process ID). This is the program that's listening on that port. If you're not sure where it is, you can right-click that process, and click "Open file location" to find it.
