### ISSUE TITLE
Allow to open files, web urls remotely

### ISSUE THREAD

**Issue by trmdi** [Ylianst/MeshCentral#5984]
Sometimes I want to open a file or web url on the agent's screen remotely (not use the mouse to open it on the agent's screen). Currently there is already a button for that but it only displays on the desktop ui, and it can only open web urls, not open files like images, document...

So it would be nice if:
- that button is visible on the mobile ui
- allow to open not only web urls but also files

**Comment by si458** [comment]
done pr for the web url to mobile ui,
looking into the opening of files, in theory i can use the same function that opens the url to open files!
just need to add extra buttons, commands, etc, so be a day of 2 👍

**Comment by si458** [comment]
pr done!
you can now tick a single file/folder in the files tab and click 'open' and it will open that file/folder on the desktop!
you can also run `openfile C:\Users\user\Documents\randomfile.txt` `openfile /Users/user/Documents` in the console tab!

**Comment by trmdi** [comment]
Can we also open web urls from the console?

**Comment by trmdi** [comment]
> p.s: i havent added the open button to the mobile UI, because we have run out of space, so need to think where to put the button or maybe a new hide away draw with the buttons possible?

Maybe make that area horizontally scrollable?

**Comment by si458** [comment]
> Can we also open web urls from the console? Ah nevermind, I see "openurl" in the available cmd list. 👍

That already exists now, `openurl`
