### ISSUE TITLE
Let's Encrypt Name Resolution Issue Preventing Access

### ISSUE THREAD

**Issue by adnan29979** [Ylianst/MeshCentral#5987]
**Describe the issue**
I've been successfully using MeshCentral for a couple of months without any issues, including as recently as yesterday. I have not made any changes to the server configuration. However, today when I attempted to access my MeshCentral instance, I encountered the following warning message and was unable to get to the website:

```
WARNING: Invalid Let's Encrypt names, unable to resolve: my.sub.domain.org
```

**Temporary Workaround**
I discovered that by adding `"nochecks": true` to the Let's Encrypt section of my `config.json`, I am able to bypass this issue and gain access. However, I believe this to be a workaround rather than a permanent solution.

**Expected behavior**
The server should normally resolve the Let's Encrypt names without requiring any temporary workarounds, allowing for regular access to the MeshCentral website.

**Server Environment:**
- MeshCentral version: 1.1.18 (This is a production server. I tend not to update a production application normally)
- Node.js version: v20.11.0
- Operating System: Windows 11
- Any recent changes made to your environment? No

**Additional context**
This issue appeared suddenly without any prior changes or updates to the server. The temporary fix does allow for access, but I'm concerned about the implications of bypassing security checks and would prefer a more stable solution.
**Edit:** I have a public DNS set in my network adapter from the very beginning. `8.8.8.8` and `1.1.1.1`. 

`leevents` output at server console tab:  
> 4/3/2024 11:04:23 AM - Getting certs from local store (Production)   
4/3/2024 11:04:23 AM - Reading certificate files   
4/3/2024 11:04:23 AM - Setting LE cert for default domain.   
4/3/2024 11:04:29 AM - Certificate has 47 day(s) left.   
4/3/2024 11:04:29 AM - Certificate is ok. 

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/148310766/71d7635e-4701-4b7a-84c3-006c78a8600f)
![image](https://github.com/Ylianst/MeshCentral/assets/148310766/45d88cfc-5e89-45ee-8336-2982f6b141d5)

**Your config.json file**
```
	{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "my.sub.domain.org",
    "_TrustedCert": false,
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 8069,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "webrtc": true,
    "selfUpdate": false,
    "MongoDB": "mongodb://localhost:27017/?replicaSet=rs0",
    "MongoDbBulkOperations": true,
    "authlog": "C:\\myFolder\\meshcentral-data\\authlog.log",
    "maxInvalidLogin": {
      "time": 60,
      "count": 3,
      "coolofftime": 60
    },
    "maxInvalid2fa": {
      "time": 60,
      "count": 3,
      "coolofftime": 60
    },
    "_crowdsec": { "fallbackRemediation": "captcha" },
    "AutoBackup": {
      "mongoDumpPath": "C:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe",
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 3,
      "zipPassword": "mypass",
      "_backupPath": "C:\\backups",
      "_googleDrive": {
        "folderName": "MeshCentral-Backups-GDrive",
        "maxFiles": 3
      }
     },
    "ipBlockedUserRedirect": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "_userAllowedIP": "127.0.0.1,192.168.1.0/24",
    "_userBlockedIP": "127.0.0.1,::1,192.168.0.100",
    "agentPing": 25,
    "_browserPing": 45
  },

  "domains": {
    "": {
      "title": "abcd",
      "title2": "abcd",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "newAccountsCaptcha": true,
      "_titlePicture": "Logo2.jpg",
      "welcomePicture": "loginLogo.png",
      "_loginPicture": "Logo1.jpg",
      "_maxDeviceView": 100,
      "passwordRequirements": {
        "_min": 8,
        "_max": 128,
        "_upper": 1,
        "_lower": 1,
        "_numeric": 1,
        "_nonalpha": 1,
        "_reset": 90,
        "force2factor": true,
        "_oldPasswordBan": 5,
        "_banCommonPasswords": false,
        "twoFactorTimeout": 300
      },
      "twoFactorCookieDurationDays": 5,
      "_agentCustomization": {
        "displayName": "Company® Product™",
        "description": "Company® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Company®",
        "serviceName": "companyagent",
        "image": "agent-logo.png",
        "fileName": "compagnyagent"
      },
      "terminal": {
        "_linuxshell": "login",
        "launchCommand": {
          "linux": "clear\nsu pi\ncd\n",
          "_darwin": "clear\necho \"Hello MacOS\"\n",
          "_freebsd": "clear\necho \"Hello FreeBSD\"\n"
        }
      }
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "_nochecks": true,
    "email": "my.email@gmail.com",
    "names": "my.sub.domain.org",
    "skipChallengeVerification": true,
    "production": true
  }
}
```

**Comment by adnan29979** [comment]
Update: I think that certain aspects of my national internet service are currently experiencing downtime. Which is probably why I am facing the above issue.

**Comment by si458** [comment]
Ur issue is very similar to https://github.com/Ylianst/MeshCentral/discussions/5988
Could be a letsencrypt outage?

**Comment by adnan29979** [comment]
Yes, it seems like this issue is similar to #5988. My national telecom provider has announced a maintenance period, and it looks like other web applications are experiencing similar problems. So, it seems the issue is related to a national downtime, not something on my end. For now, I'll run it with `"nochecks": true` and see if the situation resolves itself once the maintenance is completed. I'll keep you updated on any changes.

**Comment by si458** [comment]
@adnan29979 well i was going to reply saying `the is no such value as nochecks?`
but after checking the sourcecode, turns out the is!
it was just missing from the schema file, so have added it!
`If nochecks is "false", MeshCentral won't verify if "email" is valid, has a valid MX record, AND if "names" contain a wildcard, can be resolved by DNS A/AAAA record`

**Comment by adnan29979** [comment]
Yup. I saw it from #5988. It worked perfectly for me. 
IDK how, since it's linked with email. But it worked for me. 
Thanks for adding it to the schema.

**Comment by adnan29979** [comment]
I checked my domain at [Let's Debug](https://letsdebug.net/). These are the results. 
The issue is with my domain provider, who is the national telecom provider whom I mentioned previously is having a downtime. 
![edited](https://github.com/Ylianst/MeshCentral/assets/148310766/9d97f543-c8cc-409b-9e38-765cc3cbff71)

**Comment by adnan29979** [comment]
Good news! The problems with my internet provider are fixed, and I can get into my MeshCentral server without using `"nochecks": true` now. 
Looks like the trouble wasn’t with MeshCentral or my network after all. I'm closing this issue.

**Comment by adnan29979** [comment]
> ![edited](https://private-user-images.githubusercontent.com/148310766/319315362-9d97f543-c8cc-409b-9e38-765cc3cbff71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzE3MzAsIm5iZiI6MTcxMjE3MTQzMCwicGF0aCI6Ii8xNDgzMTA3NjYvMzE5MzE1MzYyLTlkOTdmNTQzLWM4Y2MtNDA5Yi05ZTM4LTc2NWNjM2NiZmY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxOTEwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2YwMmE5MjcwNmZjOWE1OWI2MWYzZjI2YThlNjUxOWU0Y2MzNzYwZTliOGMxNDg5ZmI1ZDFjNTFjY2Y1NTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nPYmwQOs3xXQAE3_9oscyD5o6dz03xPZniM64ndZUQU)

Update: I still see this result from Let's Debug. But somehow my Meshcentral is now running fine without `nochecks`. This might pose a problem when Let's Encrypt tries to get a new certificate after this one is over.

**Comment by adnan29979** [comment]
Update: Test results are now fine from Let's Debug. So it's safe to assume that all maintenance from my national domain provider is complete. 

![Screenshot 2024-04-04 211823](https://github.com/Ylianst/MeshCentral/assets/148310766/0fc82a1a-4196-46ec-9ec4-03935f75e2a5)
