### ISSUE TITLE
Meshservice-signed.exe being detected as Program:Win32/Uwasson.A!ml

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#599]
Hi

I just wanted to highlight that I just performed an update to the latest version on windows, and the following service was detected as a potential threat. Allowing the service is fine and everything works.

![image](https://user-images.githubusercontent.com/51713320/67373952-64f26a80-f578-11e9-96c4-17fef760eef7.png)

**Comment by MailYouLater** [comment]
Please submit and report as false positive via https://www.microsoft.com/en-us/wdsi/filesubmission.

**Comment by Ylianst** [comment]
Thanks for the report. Working on a new agent release for tomorrow, hopefully we can help with this. False positive report also helps a lot.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.3-a with a change around this. The agent that is packaged with the server may still cause a warning, however when you download the agent from the server, MeshCentral will add to the agent executable to make it somewhat unique. This looks like it should minimize the problem. Feedback welcome.

**Comment by MailYouLater** [comment]
I don't know for sure, but theoretically that could be worse, as viruses, trojans, and other malware sometimes use a similar technique to try to hide from antivirus/antimalware solutions, and thus some scanners look for this kind of behavior to heuristically detect viruses that aren't in their signature database.

**Comment by Ylianst** [comment]
Agreed, but after looking at it a little with virustotal.com, it seems like it will be better. This said, any feedback on this appreciated.

**Comment by MailYouLater** [comment]
... Just to verify, @vish84: This is on the MeshCentral server, not one of the computers that connects via the agent. Correct? If so, @Ylianst's change to make the downloaded agent installers slightly unique will have no effect on this.

**Comment by vish84** [comment]
Correct this is on a win server 2016, where meshcentral is hosted

**Comment by Ylianst** [comment]
@MailYouLater is correct. The MeshAgent that is included in the NPM package is un-changed and will still show as problematic, however once you download or get an agent update from the server, the agent should be ok. I will also note that if you delete the "-signed" versions of the MeshAgent and restart the server, the server will use the unsigned version if that is preferable for you. @krayon007 should have a new MeshAgent, hopefully today or tomorrow that may fix the problem in the NPM package. Hope that made sense.

**Comment by MailYouLater** [comment]
Also, it's still a good idea to submit a false positive report if you can.

**Comment by vish84** [comment]
I've just tried again on my test server, and do not see this alert anymore. I run a scan against the file itself and no reports this time.
