### ISSUE TITLE
"7 Day Power State" missing a day

### ISSUE THREAD

**Issue by D4ngerM4us** [Ylianst/MeshCentral#5997]
**Describe the bug**
I've just noticed that the "7 Day Power State" section seems to have 'lost' the 31st March

I haven't noticed days missing before, so wonder if it's just something odd in the date calculations?

**To Reproduce**
1. Go to any device
2. Click on the 'General' tab
3. See error

**Expected behavior**
I'd expect the 31st March to be present, but it is not

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/166226020/04ec73af-cb54-4359-a9e8-c1a4f817fefb)

**Comment by si458** [comment]
the issue is day light savings in the uk here (not sure about elsewhere)
just googling how to fix this.
```
Date Tue Apr 02 2024 00:00:00 GMT+0100 (British Summer Time)
Date Mon Apr 01 2024 00:00:00 GMT+0100 (British Summer Time)
Date Sat Mar 30 2024 23:00:00 GMT+0000 (Greenwich Mean Time)
```

**Comment by si458** [comment]
all fixed! one simple line to update yourself if you fancy in both the `default.handlebars` and `default-mobile.handlebars`
