### ISSUE TITLE
Typos in User Guide 0.1.9 Linux Automatic Start

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#60]
Section 14.2 Linux Automatic Start

It says: " When, create a file
/etc/system/system/meshcentral.service"

But should say: " Then, create a file
/etc/systemd/system/meshcentral.service"

Notice, two typos.  When instead of then.  But more importantly, the path was misspelled, systemD

Otherwise someone not familiar with the system will be confused and it will fail.

**Comment by Ylianst** [comment]
Thanks for the report. I am out for holiday travels for 5 days. I will fix it when I get back.

**Comment by Ylianst** [comment]
Just got back and did a silent fix to the [User's Guider](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.1.9.pdf). Many thanks for pointing this out!
