### ISSUE TITLE
Rapid increase in RAM consumption on the server after normal operation

### ISSUE THREAD

**Issue by sheshko-as** [Ylianst/MeshCentral#6024]
**Describe the bug**
Periodically, maybe once a day, maybe once every three days, RAM consumption starts to rise sharply until it runs out on the server and the meshcentral service restarts via oom-kill

**Screenshots**
![screen](https://github.com/Ylianst/MeshCentral/assets/97667637/b666c74c-1f9d-4a6e-a2e9-b2b8c8be61b0)

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04
 - Virtualization: VPS
 - Network: WAN
 - Version: 1.1.22
 - Node: 20.12.1 

**Client Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Network: Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: 1.8.8795

**Remote Device (please complete the following information):**
 - Device: PC
 - Quantity: 1500 devices
 - OS: Windows 10 Pro - 22H2
 - Network: Remote over WAN
 - Current Core Version (if known): Dec 9 2022, 3840084365

**Your config.json file**
```
{
  "settings": {
    "cert": "XXXXXX",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "MongodbBulkOperations": true,
    "WANonly": true,
    "AllowHighQualityDesktop": false,
    "autoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "XXXXXX",
      "webdav": {
        "url": "XXXXXX",
        "username": "XXXXXX",
        "password": "XXXXXX",
        "folderName": "XXXXXX",
        "maxFiles": 30
      }
    }
  },
  "domains": {
    "": {
      "title": "XXXXXX",
      "title2": "XXXXXX",
      "hide": 5
    }
  },
  "letsencrypt": {
    "email": "XXXXXX@XXXXXX",
    "names": "XXXXXX",
    "production": true
  }
}

```

**Comment by silversword411** [comment]
This is a dupe.
Please search before posting new issue

**Comment by sheshko-as** [comment]
> This is a dupe. Please search before posting new issue

I have searched many times in the search, I have not found anything. Maybe I didn't search well.

**Comment by sheshko-as** [comment]
Data from journalctl:

node[722]: ERR: /root/meshcentral/node_modules/meshcentral/meshuser.js:792
node[722]:                             if ((docs[i].rdp != null) && (docs[i].rdp[obj.user._id] != null)) { docs[i].rdp = 1; } else { delete docs[i].rdp; }
node[722]:                                                                                ^
node[722]: TypeError: Cannot read properties of undefined (reading '_id')
node[722]:     at /root/meshcentral/node_modules/meshcentral/meshuser.js:792:80
node[722]:     at /root/meshcentral/node_modules/meshcentral/db.js:2571:54
node[722]:     at /root/meshcentral/node_modules/mongodb/lib/utils.js:349:28
node[722]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node[722]: Node.js v18.20.2
node[722]: Error: Command failed: /usr/bin/node /root/meshcentral/node_modules/meshcentral --launch 722
node[722]: (node:2384) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
node[722]: (Use `node --trace-warnings ...` to show where the warning was created)
node[722]: /root/meshcentral/node_modules/meshcentral/meshuser.js:792
node[722]:                             if ((docs[i].rdp != null) && (docs[i].rdp[obj.user._id] != null)) { docs[i].rdp = 1; } else { delete docs[i].rdp; }
node[722]:                                                                                ^
node[722]: TypeError: Cannot read properties of undefined (reading '_id')
node[722]:     at /root/meshcentral/node_modules/meshcentral/meshuser.js:792:80
node[722]:     at /root/meshcentral/node_modules/meshcentral/db.js:2571:54
node[722]:     at /root/meshcentral/node_modules/mongodb/lib/utils.js:349:28
node[722]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node[722]: Node.js v18.20.2
node[722]:     at ChildProcess.exithandler (node:child_process:422:12)
node[722]:     at ChildProcess.emit (node:events:529:35)
node[722]:     at maybeClose (node:internal/child_process:1098:16)
node[722]:     at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
node[722]:   code: 1,
node[722]:   killed: false,
node[722]:   signal: null,
node[722]:   cmd: '/usr/bin/node /root/meshcentral/node_modules/meshcentral --launch 722'
node[722]: }
node[722]: ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
node[722]: MeshCentral HTTP redirection server running on port 80.
node[722]: MeshCentral v1.1.23, WAN mode, Production mode.
node[722]: MeshCentral Intel(R) AMT server running on DOMAIN:4433.
node[722]: MeshCentral HTTPS server running on DOMAIN:443.

**Comment by si458** [comment]
@sheshko-as plz open a separate issue for ur bug above, it is unrelated to the ram increase bug

**Comment by sheshko-as** [comment]
ok
