### ISSUE TITLE
req.flash is not a function

### ISSUE THREAD

**Issue by timcanty** [Ylianst/MeshCentral#6028]
**Describe the bug**
Trying to configure Azure single signing on 1.2.2, upon setting some of the config options, i keep receiving an error saying "TypeError: req.flash is not a function"

**To Reproduce**
1. Configure the oidc authStrategie
2. Click on the button to login,
3. Error message shown, and meshcentral crashes

**Expected behavior**

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: No
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: v1.1.22,
 - Node: v20.5.1,

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Local
 - Browser: Google Chrome
 - MeshCentralRouter Version: None

**Additional context**
The error logs:
------- 4/15/2024, 1:16:42 PM ---- 1.1.22 --------

/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:134
          req.flash(type, msg);
              ^

TypeError: req.flash is not a function
    at allFailed (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:134:15)
    at attempt (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:183:28)
    at strategy.fail (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:314:9)
    at /opt/meshcentral/node_modules/openid-client/lib/passport_strategy.js:198:12

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "allowedOrigin": [ "#############" ],
      "userallowedip" : 192.168.1.0/24",
      "PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "allowAccountReset": false, "force2factor": true, "single2factorWarning": false, "oldPasswordBan": 6 },
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "consentMessages": {
        "consentTimeout": 30,
        "autoAcceptOnTimeout": true
      },
 "authStrategies": {
        "oidc": {
           "newAccounts": true,
           "client": {
                "client_id": "#################",
                "client_secret": "#################"
           },
           "custom": {
                "preset": "azure",
                "tenant_id": "#################"
           },
           "groups": {
               "recursive": false,
               "siteadmin": ["Administrators"],
               "revokeAdmin": false,
               "_sync": {
                    "filter": ["Administrators"]
               }
           },
           "callbackURL": "https://#################/auth-oidc-azure-callback"
        }
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
**you havent filled out the bug template correctly**
what nodejs version are you using?
what meshcentral version are you using?

**Comment by timcanty** [comment]
apologies 
Version: v1.1.22,
Node: v20.5.1,

**Comment by si458** [comment]
this was already fixed here https://github.com/Ylianst/MeshCentral/issues/5120
HOWEVER i think with the recent migrate of oidc, i think the package 'connect-flash' has been removed!
checking now...
to fix this simply `cd /opt/meshcentral/` then `npm install connect-flash` then restart meshcentral!

**Comment by si458** [comment]
yep! the `connect-flash` package has been removed by mistake!
PR merge should fix it for you! https://github.com/Ylianst/MeshCentral/commit/1dca9e2235ee0ef87afb6d337abdffb98e0d92ec
simple fix is following:
1. `cd /opt/meshcentral/`
2. `npm install connect-flash`
3. restart meshcentral!
