### ISSUE TITLE
Issue with obtaining config using "meshctl config" 

### ISSUE THREAD

**Issue by geekasso** [Ylianst/MeshCentral#6029]
**Describe the bug**
In a Windows server running MeshCentral I am executing a command ```C:\Program Files\Open Source\MeshCentral>node ./node_modules/meshcentral/meshctrl config --show``` and I am seeing an error ```ERROR: Unable to parse meshcentral-data\config```. 

My folder structure is as follows:
MC is installed in "C:\Program Files\Open Source\MeshCentral"

MeshCtrl.js is located in "C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral". The path of my config.json is "C:\Program Files\Open Source\MeshCentral\meshcentral-data\config.json". It seems that in "performConfigOperations(args)" function, there are several filesystem condition statements and the first one sets the configFile variable, but the path then becomes incorrect, appending the 'meshcentral-data\config.json' to "C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral", resulting in a path that looks like "C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral-data\config.json". If I remove the first 4 conditions, I am able to get the result of the config.json, as expected. 

These are the conditions that need to be removed to get the path to config.json correctly set:

```
    if (fs.existsSync(configFile) == false) { configFile = path.join('meshcentral-data', 'config.json'); }
    if (fs.existsSync(configFile) == false) { configFile = path.join(__dirname, 'config.json'); }
    if (fs.existsSync(configFile) == false) { configFile = path.join(__dirname, 'meshcentral-data', 'config.json'); }
    if (fs.existsSync(configFile) == false) { configFile = path.join(__dirname, '..', 'meshcentral-data', 'config.json'); }
```

**To Reproduce**
1. navigate to meshcentral root directory
2. execute "node ./node_modules/meshcentral/meshctrl config --show"
3. See error

**Expected behavior**

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: N/A
 - Network: WAN
 - Version: 1.1.22
 - Node: 20.12.1

**Comment by geekasso** [comment]
The first condition statement is missing '__dirname'. I changed it to:

```
    if (fs.existsSync(configFile) == false) { configFile = path.join(__dirname,'meshcentral-data', 'config.json'); }
```

Which is similar to the others and now the command returns the config.json

**Comment by si458** [comment]
> The first condition statement is missing '__dirname'. I changed it to:
> 
> ```
>     if (fs.existsSync(configFile) == false) { configFile = path.join(__dirname,'meshcentral-data', 'config.json'); }
> ```
> 
> Which is similar to the others and now the command returns the config.json

you are just duplicating the lines as the exact same line is listed below.

if you change 
`try { config = require(configFile); } catch (e) { console.log('ERROR: Unable to parse ' + configFile + '.'); return null; }`
to
`try { config = JSON.parse(fs.readFileSync(configFile)) } catch (e) { console.log('ERROR: Unable to parse ' + configFile + '.'); return null; }`

it will work, it seems node isnt reading the json file correctly with `require` and needs `readFileSync` with parse instead

**Comment by si458** [comment]
fixed in commit https://github.com/Ylianst/MeshCentral/commit/7b8cf857405d370add2501d0a8c2b440d6f018cd
