### ISSUE TITLE
0.4.3-b No Login After Update

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#603]
Updated from working 0.4.3-a to 0.4.3-b and now while MeshCentral runs, there is no login dialogue.

**Comment by Ylianst** [comment]
Oh dear! If you open the browser console, do you see any errors?

**Comment by scottalanmiller** [comment]
Nope. No errors there.  Have tested Chrome and FF.

**Comment by Ylianst** [comment]
Investigating this now. It's also been reported on [Reddit](https://www.reddit.com/r/MeshCentral/comments/dmj1sy/meshcentralcom_problem/) with [MeshCentral.com](https://MeshCentral.com) that is running 0.4.3-a. i suspect the multi-language feature is causing this.

**Comment by Ylianst** [comment]
Oh, I see the problem. Happens with minify turned on, working on it now.

![x](https://user-images.githubusercontent.com/1319013/67548389-8d807e80-f6b6-11e9-97bd-3d8640ea2407.png)

**Comment by Ylianst** [comment]
Found the problem, will publish a fix in a little bit.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.3-c with a fix for this. Let me know if that works. Thanks for reporting, that was super helpful.

**Comment by scottalanmiller** [comment]
I've got 0.4.3-c deployed, but still have the no login problem.

**Comment by scottalanmiller** [comment]
For the moment, I've set minify to 0 and it comes back.  So we aren't down and anyone else seeing this can get around it in that way, too.

**Comment by Ylianst** [comment]
Excellent. Thanks for reporting!
