### ISSUE TITLE
Websocket requests being throttled/ignored

### ISSUE THREAD

**Issue by geekasso** [Ylianst/MeshCentral#6032]
**Describe the bug**
Hello, it seems my websocket requests to MeshCentral server appear to be throttled. I need to create and delete multiple device groups during certain events. As a test, I am creating 30 groups, though in production there can potentially be hundreds of groups, or more. 

When using meshctrl, I am required to make a request for each devicegroup, which turned out to be "expensive" (~1.5 second per record), so I **implemented a websocket connection** to create all of the groups once websocket is open. This ends up speeding up _tremendously_ (~2 seconds for all records), however out of the 30 groups I am creating, only 18 to 23 actually get created in MeshCentral. If I add sleep for .1 seconds in the loop, all 30 groups are created. 

This leads me to believe there is some sort of throttling, but I am uncertain if it's from MeshCentral and if this is something that can be controlled. 

> I am making the websocket connection server-side from a PHP function, if that matters

**Server Software (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: N/A
 - Network: WAN
 - Version: 1.1.22
 - Node: 20.12.1

**Comment by si458** [comment]
Meshcentral doesn't do any throttling.
This is more than likely ur machine can't handle this many requests.
Also why on earth are u creating/editing stuff every 1 seconds?!

**Comment by geekasso** [comment]
> Meshcentral doesn't do any throttling. This is more than likely ur machine can't handle this many requests. Also why on earth are u creating/editing stuff every 1 seconds?!
> 
Since I am unable to separate by domains (due to service restart), I opted to use groups for logical separation. During provisioning of tenants, I need to create device groups for tenants' customer companies. There can be dozens, hundreds and even more groups. I open a websocket to create all of the groups and the .1s sleep is to remove the rate limiting while I am troubleshooting missing groups.

Is there a better way to mass create groups?

> Edit. You forgot ur config.json as it could be a config issue too

I'm not near the PC now, but I will provide the config.json later today.

**Comment by geekasso** [comment]
Here is my config.json

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "port": 443,
    "redirPort": 80,
    "cert": "{{domain}}",
    "wanonly": true,
    "minify": true,
    "clickonce": true,
    "webrtc": true,
    "allowLoginToken": true,
    "allowFraming": true,
    "selfupdate": true,
    "sessionSameSite": "none"
  },
  "domains": {
    "": {
      "allowaccountreset": false,
      "_userRequiredHttpHeader": {
        "Sec-Fetch-Dest": "iframe"
      },
      "welcomePictureFullScreen": false,
      "siteStyle": 2,
      "title": "Remote Access",
      "title2": "",
      "minify": true,
      "userNameIsEmail": false,
      "hide": 0,
      "allowedOrigin": true,
      "httpHeaders": {
        "Strict-Transport-Security": "max-age=3600",
        "Content-Security-Policy": "frame-ancestors {{domain}}",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "Origin, Content-Type, Accept, Authorization"
      },
      "mstsc": true,
      "geoLocation": true,
      "lockAgentDownload": false,
      "userConsentFlags": {
        "desktopnotify": false,
        "terminalnotify": false,
        "filenotify": false,
        "desktopprompt": false,
        "terminalprompt": false,
        "fileprompt": false,
        "desktopprivacybar": true
      },
      "ipBlockedUserRedirect": "{{domain}}"
    }
  },
  "letsencrypt": {
    "email": "{{email}}",
    "production": true,
    "skipChallengeVerification": false,
    "names": "{{domain}}"
  }
}
```
