### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by desrochers** [Ylianst/MeshCentral#6036]
**Describe the bug**
When using meshctrl.js, I am unable to create a new user if the username is an e-mail address with a specific domain. meshctrl.js appears to become stuck and never finishes execution.

**To Reproduce**
/usr/local/bin/node /root/meshcentral/node_modules/meshcentral/meshctrl.js --url wss://localhost:443/mydomain_125109e6 --loginuser 'mydomain_admin' --loginpass 'myadminpassword' AddUser --user 'user_c1e0f39e@mydomain.com' --pass 'myuserpassword' --email 'username@mydomain.com' --realname 'My User'

**Expected behavior**
I expect the command to finish and produce either a success or failure message.

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Hyper-V
 - Version: Debian GNU/Linux 10 (buster)
 - Node: 18.13.0

**Additional context**
I am able to manually log in to the Mesh Central admin page for the domain and add the user that way.

I am able to add the new user if I change the username to something like user_c1e0f39e@mydomainllc.com

I used to be able to add new usernames ending with @mydomain.com. I did enable Let's Encrypt within the 12 months, and that e-mail address ends with @mydomain.com. I have no idea if this would be relevant, but it's the only other place where @mydomain.com would appear.

**Comment by si458** [comment]
thats a weird one? do you get ANY output at all when you run the command?
does it just keep running? or does it just look like it closes straight away?

**Comment by desrochers** [comment]
It keeps running. I just tried running it again. It's been going for 5 minutes now. There's no output. I will have to CTRL+C to exit, but it never adds the user.

I ended up adding in some of my own logging to meshctrl.js

This is what's being sent to the WebSocket:

{
	"action": "adduser",
	"username": "user_c1e0f39e@mydomain.com",
	"pass": "myuserpassword",
	"responseid": "meshctrl",
	"email": "username@mydomain.com",
	"realname": "My User"
}

I get back serverinfo, userinfo, and then a msg.

{
	"action": "msg",
	"type": "notify",
	"id": 0.5763815495393891,
	"value": "Email address already in use",
	"title": "New Account",
	"userid": "user/mydomain_125109e6/mydomain_admin",
	"username": "mydomain_admin",
	"tag": "ServerNotify"
}

If the serverinfo and userinfo are needed, I can reproduce them.

I'm not sure why it's complaining about the e-mail address already being in use.

**Comment by si458** [comment]
oh dear! a bug indeed!
it should timeout after 60 seconds! the fact it keeps running after 5 mins isnt good!
also intheory it should of caught the end message and then displayed it to tell u it didnt add the user because as it says `email address already in use`

i just tried it here and it appears the email address needs to be unique across all domains!

so user//bob email is bob@bob.com
bob@bob.com cant be used in user/bobsdomain/bob@bob.com!

will look into this tomorrow for you

**Comment by si458** [comment]
ok ive fixed the issue with it not notifying you that `Email address already in use`.
its a backend issue where it was displaying the error in the web ui but i totally forgot about meshctrl !?
but basically the error you are getting is because it wants email address unique.
and this issue https://github.com/Ylianst/MeshCentral/issues/289 i fixed that but it checks emails across ALL DOMAINS,
rather than just the domain in question!
so fixing that now!

**Comment by si458** [comment]
ok question? tagging onto #289.
we shouldnt allow duplicate emails per domain as expected.
but should we allow duplicate emails across ALL domains?
if we did allow then #289 would happen with password resets resetting the wrong domains!?

**Comment by desrochers** [comment]
Awesome, thanks for getting that taken care of. I'll keep an eye out to see how the duplicate e-mail address thing gets handled.

**Comment by si458** [comment]
@desrochers ok ive merged the fix so it now returns the error for you https://github.com/Ylianst/MeshCentral/commit/1747ff755025f2aae96b06d58e5632de4fbd534b
HOWEVER im not sure how to handle the duplicate email addresses?
should meshcentral be checking IF the email address is already in use PER domain OR should it check globally?

**Comment by desrochers** [comment]
Sorry, I am unclear if that question is directed at me. However, it would make sense to me that the e-mail (and username) would be on a per-domain basis. I am not sure if that would present any security issues, as the issue #289 mentioned something about using an e-mail address for password resets. But, I would assume that Mesh Central would use to URL to know which domain to use.

The reason this came about was because I built a simple frontend for managing devices through the web. However, some administrators need to be able to manage several different domains. The frontend uses meshctrl.js to automatically create the account for them. And it uses their e-mail address from my database to create the account.

In my case, if it is absolutely necessary, I can create unique usernames and e-mail addresses on the fly when adding a new user to Mesh.

**Comment by si458** [comment]
i think you can close this issue now, as the `meshctrl.js` has been fixed by me removing the commits https://github.com/Ylianst/MeshCentral/commit/414d9b956105d3e9a2fbaa1c3faf2c15b88c62d2
so it would allow you to create the users!

**Comment by desrochers** [comment]
That's interesting. Looks like usernameisemail: true is a default setting. Was that a new setting that was added in the last year or so? That would explain why it suddenly started giving me problems.

I haven't been able to update my Mesh Central yet but I did look at your code change so I'll assume it's fixed. Thanks!

**Comment by si458** [comment]
No? `usernameisemail: false` is the default?
U got me questioning my insanity now!?
Will have to check config when I get home now!?
Can u share ur config.json at all? (Hide secrets)

**Comment by desrochers** [comment]
I may be misinterpreting it but this is where I say it was set to true:

https://github.com/Ylianst/MeshCentral/blob/414d9b956105d3e9a2fbaa1c3faf2c15b88c62d2/sample-config.json#L21

```json
{
  "__comment__": "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "_settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "MongoDbCol": "meshcentral",
    "Port": 443,
    "AllowLoginToken": true,
    "AllowFraming": true,
    "WebRTC": false,
    "ClickOnce": false
  },
  "settings": {
    "mongodb": "mongodb://10.0.1.71:27017/meshcentral",
    "mongodbcol": "meshcentral",
    "allowFraming": true,
    "allowLoginToken": true,
    "manageCrossDomain": [
      "user//myadmin",
      "user//meshadmin"
    ],
    "WsCompression": true,
    "AllowHighQualityDesktop": true,
    "cert": "ras.mydomain.com",
    "production": true,
    "wanonly": true,
    "port": 443,
    "redirPort": 80
  },
  "letsencrypt": {
    "email": "alerts@mydomain.com",
    "names": "ras.mydomain.com",
    "rsaKeySize": 3072,
    "production": true,
    "_skipChallengeVerification": false
  },
  "domains": {
    "_": {
      "title": "MyServer",
      "title2": "Servername",
      "userQuota": 1048576,
      "meshQuota": 248576,
      "newAccounts": false,
      "footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>"
    },
    "customer1": {
      "_dns": "customer1.myserver.com",
      "title": "Customer1",
      "title2": "TestServer",
      "newAccounts": false,
      "_auth": "sspi",
      "footer": "Test"
    },
    "_info": {
      "_share": "C:\\ExtraWebSite"
    },
    "mytest": {
      "title": "My Test",
      "newAccounts": false
    },
    "domain1_d71d2aeb": {
      "title": "Domain 1",
      "newAccounts": false
    },
    "domain": {
      "title": "My Domain",
      "newAccounts": false
    },
    "domain2_972893d4": {
      "title": "Domain 2",
      "newAccounts": false
    },
    "domain3_e04a6288": {
      "title": "Domain 3",
      "newAccounts": false
    },
    "domain4_07f18058": {
      "title": "Domain 4",
      "newAccounts": false
    },
    "domain5_b6d0a7d5": {
      "title": "Domain 5",
      "newAccounts": false
    },
    "domain6_e8500b18": {
      "title": "Domain 6",
      "newAccounts": false
    },
    "domain7_baf1b70d": {
      "title": "Domain 7",
      "newAccounts": false
    },
    "domain8_9bb49410": {
      "title": "Domain 8,
      "newAccounts": false
    },
    "domain9_695bdaf1": {
      "title": "Domain 9",
      "newAccounts": false
    },
    "domain10_53bf3332": {
      "title": "Domain 10",
      "newAccounts": false
    },
    "domain11_125109e6": {
      "title": "Domain 11",
      "newAccounts": false
    },
    "domain12_cecc0053": {
      "title": "Domain 12",
      "newAccounts": false
    }
  },
  "__domains": {
    "__comment__": "Added to support this project https://github.com/ijustw0rkhere/mesh-materialui",
    "": {
      "hide": 5,
      "nightMode": 1,
      "minify": false
    }
  },
  "_peers": {
    "serverId": "server1",
    "servers": {
      "server1": {
        "url": "wss://192.168.2.133:443/"
      },
      "server2": {
        "url": "wss://192.168.1.106:443/"
      }
    }
  },
  "_smtp": {
    "host": "10.0.1.91",
    "port": 587,
    "from": "ras@mydomain.com",
    "tls": false
  }
```

**Comment by si458** [comment]
Anything with an `_` infront of it is ignore, and the sample-config.json is just a sample, all the raw default values are inside the schema.json file which can be loaded in visual studio code!

**Comment by desrochers** [comment]
Okay, that makes sense. I assume this setting was also disabled for me, but my script uses the e-mail address in both fields, so it's mimicking the behavior of userNameIsEmail: true.

Thanks again for the help!
