### ISSUE TITLE
Can't update from 1.1.21 to 1.1.22 using gui freebsd

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#6040]
**Describe the bug**
Clicking update from the GUI doesn't update the server, with no errors.

**To Reproduce**
Try to update from 1.1.21 to 1.1.22

**Server Software (please complete the following information):**
 - OS: FreeBSD
 - Virtualization:  jail
 - Version: 1.1.21

This seems to have been a problem in the past, although I'm not sure what the fix was.

**Comment by tschettervictor** [comment]
I just did a manual `npm install meshcentral` which worked fine.

**Comment by si458** [comment]
i think the jail locks the node_modules folder down slightly, so the update MIGHT not work correctly, 
so i think the easiest way is the way you have said above `npm install meshcentral@1.1.22`
(stop meshcentral first, then start after npm install)

**Comment by tschettervictor** [comment]
That would make sense if I could see some error logs or something. I have never had issues except for one w when updating from (or to, can’t remember) version 1.1.19

**Comment by tschettervictor** [comment]
Is there any more progress on solving this? Currently still having to do `npm install meshcentral` to update the server.
Just curious...

**Comment by si458** [comment]
Are u still using freebsd? Is it truenas core?

**Comment by tschettervictor** [comment]
> ive just tried this inside of a jail on truenas and it seems to work ok? how did you setup meshcentral to begin with and set the service on start up etc? edit: are you also using a normal user in the jail or the root user?

I installed using root user, but the service runs as the meshcentral user. I do believe it works when run as the root user.

All the folders inside the meshcentral directory are owned by meshcentral, except for the node_modules folder. That is owned by root, but it has meshcentral as the group.

I’ll try changing the ownership completely to meshcentral upon the next update and try that.

**Comment by si458** [comment]
yes that will be the issue!
you must install meshcentral using 1 user AND also run the meshcentral service with the same user!
dont mix users! this messes up the node_modules folder with user permissions etc!
so `npm install meshcentral` MUST be ur meshcentral user,
and the service must also be ur meshcenteal user!

**Comment by si458** [comment]
also can u share ur service to start the meshcentral?
currently the isnt anyway to start the meshcentral for freebsd without manually setting it up
but if you can provide steps how u start/stop/installed the service,
i could add it into the `--install/--uninstall/--start/--stop` etc of meshcentral!

**Comment by tschettervictor** [comment]
I install it using root, but then I `chown -r meshcentral:meshcentral /usr/local/meshcentral` the directories. It wouldn't run otherwise. I maintain a script to install it inside FreeBSD. See the rc script here

https://github.com/tschettervictor/bsd-apps/blob/main/meshcentral/includes/meshcentral

**Comment by si458** [comment]
@tschettervictor i cannot get your script to work no matter what i try?
the daemon creates the pid, but it never actually runs/starts?
`ps` soesnt show it running? any suggestions?

PS: `fetch` should be `fetch -o /usr/local/etc/rc.d/meshcentral URL`
just a little nit pick as it displays this in the output
`/usr/local/etc/rc.d//meshcentral                       522  B 1727 kBps    00s`

**Comment by si458** [comment]
yes i did but it doesnt start?
TrueNAS CORE 13.0-U6.2
jail 13.3 - dhcp (not static ip)

**Comment by tschettervictor** [comment]
> yes i did but it doesnt start? TrueNAS CORE 13.0-U6.2 jail 13.3 - dhcp (not static ip)

See edit above.

**Comment by si458** [comment]
so how do you do that then?
i only have the option 13.3 or 13.4 in the jail
and the host is running 13.0 and when i check truenas updates, the is none!?
![image](https://github.com/user-attachments/assets/ab929883-15f6-4432-a131-9a3e354b106d)

**Comment by si458** [comment]
scratch above im having one of those days!
iso clearly on there website says 13.3 (for people with jail issues, doh!)

**Comment by si458** [comment]
ok so updated my 13 to 13.3,
deleted jail started again,
download script,
just changed `npm install meshcentral` to `npm install meshcentral@1.1.129` to install an old version,
ran the script,
accessed the web ui and created user,
into web ui and check update and click update,
watched ssh session for logs (it prints to the session, bloody stupid)
it restarted no issues with new version?

PS: you can also add log output like below, so it can divert the logs to a text file to watch/debug properly!
`command_args="-r -u ${user} -P ${pidfile} -o /usr/local/meshcentral/meshcentral.log /usr/local/bin/node ${meshcentral_chdir}/${name} ${meshcentral_args}"`

**Comment by tschettervictor** [comment]
Yes I do have to add more logging. I did notice that. 

My install goes all the way back to version 1.20 and before, so there might be some things not functioning correctly.

I’ll reinstall from scratch, as the script allows me to do that with my mount points without any hassle.

**Comment by si458** [comment]
@tschettervictor no worries, i am just in the middle of adding ur `include` file into `meshcentral.js` so u can do it from within meshcentral haha
thank you for the help/pointers tho for it! 👍

**Comment by tschettervictor** [comment]
Hold off a bit, I’m reworking it. I’ll update here once I have the completed rc script.

**Comment by si458** [comment]
i already have it working 👍 
its basically the same code as the linux install,
just one tiny bug, when it starts the service after it sets it all up,
its starts and logs and everything as expected
but the `service meshcentral start` command doesnt exit,
it just keeps running in node haha,
but if you run it normally it exists no problem

**Comment by si458** [comment]
all done! https://github.com/Ylianst/MeshCentral/commit/a1899a719f4eb2dfaef856175dd8d985235f7ab6
it creates the following in `/usr/local/etc/rc.d/meshcentral`
```
root@meshcentral:~/meshcentral # cat /usr/local/etc/rc.d/meshcentral 
#!/bin/sh
# MeshCentral FreeBSD Service Script
# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown
. /etc/rc.subr
name=meshcentral
user=root
rcvar=meshcentral_enable
: ${meshcentral_enable:="NO"}
: ${meshcentral_args:=""}
pidfile=/var/run/meshcentral/meshcentral.pid
command="/usr/sbin/daemon"
meshcentral_chdir="/root/meshcentral"
command_args="-r -u ${user} -P ${pidfile} -S -T meshcentral -m 3 /usr/local/bin/node /root/meshcentral/node_modules/meshcentral ${meshcentral_args}"
load_rc_config $name
run_rc_command "$1"
```
it send the logs to syslog
```
Sep 19 22:30:24 meshcentral meshcentral[14286]: MeshCentral HTTP redirection server running on port 80.
Sep 19 22:30:24 meshcentral meshcentral[14286]: MeshCentral v1.1.29, LAN mode.
Sep 19 22:30:27 meshcentral meshcentral[14286]: Server has no users, next new account will be site administrator.
Sep 19 22:30:27 meshcentral meshcentral[14286]: MeshCentral HTTPS server running on port 443.
```
also set `meshcentral_chdir` to the folder you install meshcentral into
and also sets `user` to whatever user ran the install command!
so in theory you can use a normal user too

**Comment by tschettervictor** [comment]
> i already have it working 👍 its basically the same code as the linux install, just one tiny bug, when it starts the service after it sets it all up, its starts and logs and everything as expected but the `service meshcentral start` command doesnt exit, it just keeps running in node haha, but if you run it normally it exists no problem

I don’t follow. Node is what runs the actual program

**Comment by tschettervictor** [comment]
The below is my completed file. This will work fine with the install script. MeshCentral runs fine using the meshcentral user, as long as the directories are owned by meshcentral. It doesn't have to be run as root.

The only thing that should ever be changed is the "meshcentral_chdir" if you are installing in a different location.

```
#!/bin/sh
#
# MeshCentral FreeBSD Service Script
#
#

# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=meshcentral
desc="MeshCentral Computer Management"
rcvar=meshcentral_enable

load_rc_config $name

: ${meshcentral_enable:="NO"}
: ${meshcentral_args:=""}
: ${meshcentral_chdir:="/usr/local/meshcentral"}
: ${meshcentral_rundir:="/var/run/${name}"}
: ${meshcentral_logdir:="/var/log/${name}"}
: ${meshcentral_pidfile:="${meshcentral_rundir}/${name}.pid"}
: ${meshcentral_logfile:="${meshcentral_logdir}/${name}.log"}

user="meshcentral"
group="meshcentral"
node="/usr/local/bin/node"
command="/usr/sbin/daemon"
command_args="-u ${user} -P ${meshcentral_pidfile} -H -o ${meshcentral_logfile} ${node} node_modules/${name} ${meshcentral_args}"

start_precmd="meshcentral_startprecmd"

meshcentral_startprecmd()
{
    if [ ! -d ${meshcentral_rundir} ]; then
        install -d -o ${user} -g ${group} ${meshcentral_rundir};
    else
        chown -R ${user}:${group} ${meshcentral_rundir};
    fi
    if [ ! -d ${meshcentral_logdir} ]; then
        install -d -o ${user} -g ${group} ${meshcentral_logdir};
    else
        chown -R ${user}:${group} ${meshcentral_logdir};
    fi
}

run_rc_command "$1"

```

**Comment by si458** [comment]
@tschettervictor, thank u for ur code

I have already included a commit previously as explained above, but I will check urs out and see if it's slightly better than mine

But my rc.d file is basically the same, but it's auto filled from within the meshcentral with like node location, where the folder should be, even what user to use

Also, it logs the output to syslog instead of a file

Currently, the linux version outputs the logs to the systemd so through I would do the same

**Comment by tschettervictor** [comment]
Basically mine just makes sure the log and run directories are properly owned, and allows for more customization of the log and run directories themselves.

All you need to do syslog is remove the `-H -o ${meshcentral_logfile}` and instead add `-S -T ${name}`

**Comment by si458** [comment]
@tschettervictor yeh thats exactally what im doing in my code for the syslog!
leave it with me :)

**Comment by tschettervictor** [comment]
```
#!/bin/sh

# MeshCentral FreeBSD Service Script

# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=meshcentral
desc="MeshCentral Computer Management"
rcvar=meshcentral_enable

load_rc_config $name

: ${meshcentral_enable:="NO"}
: ${meshcentral_args:=""}
: ${meshcentral_chdir:="/usr/local/meshcentral"}
: ${meshcentral_daemon_user:="meshcentral"}
: ${meshcentral_daemon_group:="meshcentral"}

pidfile="/var/run/${name}/${name}.pid"
node="/usr/local/bin/node"
command="/usr/sbin/daemon"
command_args="-u ${meshcentral_daemon_user} -P ${pidfile} -H -o /var/log/${name}/${name}.log ${node} node_modules/${name} ${meshcentral_args}"

start_precmd="meshcentral_startprecmd"

meshcentral_startprecmd()
{
    if [ ! -d /var/run/${name} ]; then
        install -d -o ${meshcentral_daemon_user} -g ${meshcentral_daemon_group} /var/run/${name};
    else
        chown -R ${meshcentral_daemon_user}:${meshcentral_daemon_group} /var/run/${name};
    fi
    if [ ! -d /var/log/${name} ]; then
        install -d -o ${meshcentral_daemon_user} -g ${meshcentral_daemon_group} /var/log/${name};
    else
        chown -R ${meshcentral_daemon_user}:${meshcentral_daemon_group} /var/log/${name};
    fi
}

run_rc_command "$1"
```
This will probably be the final copy of the script. There are some issues I'm noticing.

When I run the node command using the meshcentral user manually with "su meshcentral -c" things seem to work ok.
When the rc script is run with the "meshcentral_user=meshcentral" then it doens't want to work

The only way I can run meshcentral without having errors is to have the daemon run it _as_ the meshcentral user by specifying the "-u meshcentral" flag in the daemon args. Every other combo doesn't work. 

The root user works fine, but folks say it's not a good idea to let programs run as root.

Oh and the archiver@7.0.1 package seems broken or something. It shows as installing every time i start the service.

Thoughts?

**Comment by si458** [comment]
Yeh don't worry about the archives bug, the is already an issue open about that, will be fixed in next release

**Comment by tschettervictor** [comment]
This appears to be an issue with the way FreeBSD runs its service scripts. Right now, any time I try to run meshcentral with `su -m meshcentral` it will fail to start because it can’t access npm.
But when I start it with `daemon -u meshcentral` then it starts successfully and is able to install the proper modules. Probably because the actual command is being run by root, but the meshcentral process is run by the meshcentral user itself. 

It works, but it’s not really standard procedure. I even tried changing the permissions on all of the “meshcentral” files and directories to 7777, but that still didn’t work.

**Comment by tschettervictor** [comment]
In any case I'm going to close this as I just ran a fresh install using my script of version 1.1.29, then was able to do an update from the GUI without any issues. And the process is being run by the meshcentral user, albeit through the daemon command.
