### ISSUE TITLE
translate tool is unavailable: URL dead

### ISSUE THREAD

**Issue by v3DJG6GL** [Ylianst/MeshCentral#6041]
**Describe the bug**
I thought about improving german translations which are currently not that good.
But it seems as the here mentioned translating tool is not available anymore:
https://github.com/Ylianst/MeshCentral/blob/master/translate/readme.txt

The linked URL is dead:
 https://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip

Is there a working link somewhere or is there another recommended method to update translations?

**To Reproduce**
1. Go to [github.com/Ylianst/MeshCentral/blob/master/translate/readme.txt](https://github.com/Ylianst/MeshCentral/blob/master/translate/readme.txt)
2. Click on [info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip](https://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip)
3. See error

**Expected behavior**
The translating tool should be downloadable.

**Screenshots**
-

**Server Software (please complete the following information):**
-

**Client Device (please complete the following information):**
-

**Remote Device (please complete the following information):**
-
**Additional context**
-

**Your config.json file**
-

**Comment by si458** [comment]
thanks will update the read me but its now located on the meshcentral website
https://meshcentral.com/downloads.html
https://meshcentral.com/tools/ResourceTranslator.zip
