### ISSUE TITLE
Zoraxy support ( Meshcentral Router debug )

### ISSUE THREAD

**Issue by risturiz** [Ylianst/MeshCentral#6042]
Hi, im testing [Zoraxy](https://github.com/tobychui/zoraxy) reverse proxy with Meshcentral and Web dashboard work but Meshcentral Router don't... Any option to debug this? with ".\MeshCentralRouter.exe -debug" i only got:

```
18:58:PM.4842: WebSocket: Websocket TCP connected, doing TLS...
18:58:PM.5218: WebSocket: Websocket TLS setup, sending HTTP header...
18:58:PM.6219: WebSocket: Websocket got setup upgrade header.
18:58:PM.6219: WebSocket: Websocket got closed fragment.
```

Same config with Nginx Proxy Manager don't have any problem... Thanks!

**Comment by yeungalan** [comment]
Hello, this is the developer from Zoraxy. 

If it's not too much trouble, would you mind sharing the configuration on the Zoraxy side? We would greatly appreciate it, as it would allow us to take a closer look and assist you more effectively. Thank you very much for your cooperation!

**Comment by risturiz** [comment]
Hi, my config is pretty simple ( Meshcentral work from browser Firefox/Chromium):

Zoraxy config:
![Screenshot_20240420_091137](https://github.com/Ylianst/MeshCentral/assets/12375/5108bd55-20b7-408c-bf88-4506c7eff859)

Meshcentral config:
![Screenshot_20240420_092241](https://github.com/Ylianst/MeshCentral/assets/12375/54fedced-0f99-49b5-ab4b-b2b7b89ff135)

Maybe i need some "Custom Headers" with MeshRouter?

Thanks!

**Comment by si458** [comment]
Strange one, do u have port 80 open on ur reverse proxy? Or only 443? As I notice u have disabled the redirport which should be set?

Cam u access the webbui using http://mydomain.com? Or must u use https://mydomain.com

**Comment by risturiz** [comment]
> Strange one, do u have port 80 open on ur reverse proxy? Or only 443? As I notice u have disabled the redirport which should be set?
> 
> Cam u access the webbui using http://mydomain.com? Or must u use https://mydomain.com

I don't have port 80 open... Every connection should be redirected
![Screenshot_20240420_102135](https://github.com/Ylianst/MeshCentral/assets/12375/797cd655-eb3d-481a-91a1-135dec8edbe0)

Like i said, same config with Nginx Proxy Manager works... Only MeshRouter fail to connect ( using some legacy communication? )

**Comment by si458** [comment]
yes sorry the screenshot you show now is self-explanitory, listen on 443 but also listen on port 80 and to http to https!
so in theory i think the proxy is ok?
one thing you can try is running meshcentral in full debug mode and then watch the web traffic and see if the meshcentralrouter talks to meshcentral.
`node node_modules/meshcentral --debug`
if meshcentralrouter isnt talking to meshcentral and meshcentral isnt showing web connections from it, then it will be a reverse proxy issue, im afraid

**Comment by risturiz** [comment]
Didn't know there is `"Debug": true,` for config.json :-)

Here you go... MeshRouter log

![Screenshot_20240420_114303](https://github.com/Ylianst/MeshCentral/assets/12375/8b045c22-df26-4e6b-9fb8-077f84c86cfa)

**Comment by si458** [comment]
Huh? Go-http-client?
That's not meshcentralrouter? As it's written in C not golang

I think zoraxy is doing a header request to check the url is valid then doing the request afterwards.
But the request afterwards is missing all the headers, very weird?

I'll have to set up a new vm and test it myself, see whats happening

Also note, the is no debug in config.json, it's part of the run arguments, but I could be mistaken! Might be missing from the schema.json!

**Comment by yeungalan** [comment]
It looks like something went wrong in Zoraxy's header passing, will take a look

**Comment by si458** [comment]
@yeungalan also the `/control.ashx/.websocket` in our case should be a websocket connection and not a webrequest!

**Comment by yeungalan** [comment]
Thanks! Will take a look as well

@tobychui is the main author of zoraxy and I will let him aware of this as well :)

**Comment by tobychui** [comment]
That is weird, Go-HTTP-Client has been removed from the headers since a few versions ago.
[https://github.com/tobychui/zoraxy/blob/5805fe6ed212942aa20ed12499f6c06b50cabf05/src/mod/dynamicproxy/proxyRequestHandler.go#L100](https://github.com/tobychui/zoraxy/blob/5805fe6ed212942aa20ed12499f6c06b50cabf05/src/mod/dynamicproxy/dpcore/dpcore.go#L278)

```go
//Hide Go-HTTP-Client UA if the client didnt sent us one
if _, ok := header["User-Agent"]; !ok {
	// If the outbound request doesn't have a User-Agent header set,
	// don't send the default Go HTTP client User-Agent.
	header.Set("User-Agent", "")
}
```

and I don't see any issue regarding the logic to identify requests that containing the `Upgrade: websocket` header and from your log, it seems there are no `Zr-Origin-Upgrade` header appended by Zoraxy.

[https://github.com/tobychui/zoraxy/blob/5805fe6ed212942aa20ed12499f6c06b50cabf05/src/mod/dynamicproxy/proxyRequestHandler.go#L100](https://github.com/tobychui/zoraxy/blob/5805fe6ed212942aa20ed12499f6c06b50cabf05/src/mod/dynamicproxy/proxyRequestHandler.go#L100)

```
if r.Header["Upgrade"] != nil && strings.ToLower(r.Header["Upgrade"][0]) == "websocket" {
	//Handle WebSocket request. Forward the custom Upgrade header and rewrite origin
	r.Header.Set("Zr-Origin-Upgrade", "websocket")
	wsRedirectionEndpoint := target.Domain
	if wsRedirectionEndpoint[len(wsRedirectionEndpoint)-1:] != "/" {
		//Append / to the end of the redirection endpoint if not exists
		wsRedirectionEndpoint = wsRedirectionEndpoint + "/"
	}
```


Have you tried updating your Zoraxy to latest version?

**Comment by si458** [comment]
ok so just tagging onto this to remind me and others,
weirdly enough, i just created a quick test, Zoraxy and meshcentral in single compose
i used https://nip.io to create a dns to my server https://192-168-23-222.nip.io
setup meshcentral and its config.json with the cert value in
setup zoraxy by GUESSING the web ui and reading no docs
can access the web ui no problem, can create groups, can even add an agent no problem
but the min i try using meshcentralrouter, it just doesnt work?
very weird?

**Comment by si458** [comment]
ok just looked into it more, we add a custom header which contains our authentication
and meshcentral doesnt see this header which is why it doesnt work
ALSO if i go into the Zoraxy web ui, then http proxy then into custom headers
then add in a complete random custom header say `X-MyHeader -> MyValue` from Zoraxy to Origin
we dont see this custom header being added!
so the clearly is an issue with Zoraxy and this is nothing to do with meshcentral
you will need to speak to the developer of Zoraxy and find out whats going on
im using the latest version of Zoraxy v3.1.4

**Comment by risturiz** [comment]
Thanks for this update!

**Comment by si458** [comment]
@Smiley-k this should be fixed now.
Just use the latest version of meshcentral
And the latest version of Zoraxy and try again :)

**Comment by si458** [comment]
If it's working through nginx but not Zoraxy, then it's a Zoraxy issue, but also remember the dns names must match too

**Comment by risturiz** [comment]
> > Thanks for this update!
> 
> Hi, did you manage to launch?

Hi, Zoraxy worked from the beginning... Only have connection problem with MeshRouter... Actually with last patch MeshRouter works too ( have to test for some months to change NPM on prod ).
