### ISSUE TITLE
Parent Groups with Child Groups.

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6048]
**Is your feature request related to a problem? Please describe.**
It is not related to a technical problem.

**Describe the solution you'd like**
A ability to create parent groups with subsequent child groups, for example I have parent group called 'Company' with child group 'Webhosting'.

**Describe alternatives you've considered**
Having name pre/post-fixes.

**Additional context**
No additional context.

**Comment by si458** [comment]
Duplicate #1258
