### ISSUE TITLE
MeshCommander can't wake up target system via SOL when target system is in modern standby.

### ISSUE THREAD

**Issue by JoshuaSYChang** [Ylianst/MeshCentral#605]
Hi Ylian,

As WebUI support the "Wake from Standby (Connected)" option when target system is in modern standby but MeshCommander v0.7.9 does not have this option to act as WebUI, could you help to add the option for support? Many thanks.

![MS](https://user-images.githubusercontent.com/25002787/67571558-d263ee00-f766-11e9-8d0b-f73d0e964fac.jpg)

Best regards,
Joshua

**Comment by jsastriawan** [comment]
It seems this API requests OS powersaving state change which is not currently being used. I'll take a stab on that but Ylian will be traveling in the next few days.

Regards,


Joko

**Comment by Ylianst** [comment]
This is a good request. @jsastriawan, can you find any documentation on how to do the WSMAN call for you? If you do, I should be able to implement this quickly.

**Comment by Ylianst** [comment]
Never mind, I found it in the documentation. It's a completely different flow. I will start work on it.

![x](https://user-images.githubusercontent.com/1319013/67592062-a23f2f80-f713-11e9-8765-c17370f7ffec.png)

**Comment by jsastriawan** [comment]
You are fast. I was about to answer with the same resources. :smiley:

**Comment by Ylianst** [comment]
Uploaded a new MeshCommander v0.7.9 with OS power state control for Intel AMT 10+. Since I did not change the version number, you need to uninstall/download/install MeshCommander again. I am not sure if this works, Intel AMT accepts the command but it does nothing on my computer probably because the OS does not support it. Would appreciate some testing on this.

![x](https://user-images.githubusercontent.com/1319013/67611785-8b1f3280-f751-11e9-8ba1-19bc2be59671.png)

**Comment by jsastriawan** [comment]
This is LMS assisted operation. In order to get this  to work, LMS will have to handle message emitted by MEI and perform OS power state change operation. Our Microlms does not handle that event yet.

**Comment by Ylianst** [comment]
@jsastriawan That totally makes sense and exactly why it's not working on my computer. Need to work on improving MicroLMS at some point.

**Comment by JoshuaSYChang** [comment]
Hi Ylian.

Thanks for your great support, the new v0.7.9 can work in my side.

Best regards,
Joshua
