### ISSUE TITLE
DNS redirect for "customers"

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#606]
Hi!

I've made a setup like this:
{
        "settings": {
                "port": 443,
                "redirport": 80
        },
        "domains": {
                "": {
                        "title": "Main",
                },
                "sub": {
                        "title": "Sub",
                        "Dns": "sub.domain.tld"
                }
        }
}

When going directly to https://sub.domain.tld it is working fine, but when going to http://sub.domain.tld, it just forwards to the main domain instead.
Is there a way around this issue?

**Comment by Ylianst** [comment]
Oh. This is interesting. I will take a look at this.

**Comment by Ylianst** [comment]
Your right, I see the same problem... working on a fix.

**Comment by Ylianst** [comment]
Thanks for reporting this. Published MeshCentral v0.4.3-f with a fix for this. Update your server and let me know if that works.

**Comment by GnaXi** [comment]
Updated and confirmed.
Issue has been resolved! Thank you for the quick fix! :D
