### ISSUE TITLE
WARNING:Failed to sign agent MeshService.exe: Error: Too few bytes to read ASN.1 value.

### ISSUE THREAD

**Issue by emersonnpe** [Ylianst/MeshCentral#6073]
When running the meshcentral service I encounter this error in the server information tab in the console. Has anyone had this problem and knows how to resolve it?

My version information:

Latest Stable: 1.1.0

![Erro](https://github.com/Ylianst/MeshCentral/assets/75445621/81e484ee-a439-467d-b6d3-e27c97f2b791)

**Comment by si458** [comment]
you are using an old version, please update to 1.1.22
the is a fix included which should solve this

**Comment by emersonnpe** [comment]
When updating to the latest version the problem was fixed.
