### ISSUE TITLE
Chat URL Misspelling

### ISSUE THREAD

**Issue by ihurst1** [Ylianst/MeshCentral#6079]
I recently just installed Mesh Central on a VM to run for our small business.

Everything has been working great since installing but now when trying to initiate chat with a device, the receiving end’s browser is trying to redirect to the correct URL but it has a small misspelling of 3 letters in it. I have check the “config.json”, the and the DNS record, and cannot find it misspelled, plus like I said it was working actually 4hours prior. If I fix the misspelling it brings me to the correct chat window and the chat window is correct on the host's side.

**To Reproduce**
1. Go to the client you wish to access
2. Click on "chat"
3. the window that is opened on the clients browser has the URL misspelled.

**Expected behavior**
Chat window to open.

**Screenshots**

![Screenshot 2024-05-09 154929](https://github.com/Ylianst/MeshCentral/assets/169401605/770cbc1c-995c-4208-90de-4f3996660910)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: DirectOcean
 - Network: LAN/WAN
 - Version: 1.1.0
 - Node: 14.10.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11 Home
 - Network: Remote over WAN
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 Home
 - Network: Remote w/ WAN
 - Current Core Version (if known): unknown

**Your config.json file**
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) a>
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "mesh.alphalandsurveying.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encryp>
    "email": "ihurst@alsm96.com",
    "names": "mesh.alphalandsurveying.com",
    "skipChallengeVerification": true,
    "production": false
  }
}

**Comment by si458** [comment]
You have a few issues here.
You are not running the latest version of meshcentral, latest is 1.1.22
Your nodejs is old and outdated, plz use node 18 or above
Your `cert` value is commented so it will ignore that value, so you should remove the `_`
You aren't using any valid ssl because the letsencrypt section is again commented so remove the `_` from letsencrypt.
Also you have production set to false and it should be true to get a valid ssl cert from letsencrypt
Also the comment,comment1,comment2 etc should be removed as these are just helpful info

**Comment by ihurst1** [comment]
Now it works. Thank you very much.

Thanks,

*Please note my new phone numbers below.*


*Ivan Hurst*
Project Manager, *Alpha Land Surveying NE*

Project Manager*, Alpha Surveying and Mapping FL*

O: 402.380.7216 EXT #3 | D: 402.205.2463 | ***@***.***

www.alphalandsurveying.com

15237 Locust St, Omaha, NE 68116

10024 Palermo Cir, Tampa FL 33619
*This transmission, which may contain confidential information, is for the
intended recipient only.  Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon this information by
persons or entities other than the intended recipient, is prohibited.  If
you received this in error, please contact the sender and delete the
material from your computer and networks.*
