### ISSUE TITLE
ListDevices with --json param and without group ID does not return power state

### ISSUE THREAD

**Issue by geekasso** [Ylianst/MeshCentral#6081]
**Is your feature request related to a problem? Please describe.**
When running "node meshctrl ListDevices --json" (without the group ID), the power state (pwr) is not in the response.

**Describe the solution you'd like**
Include the pwr state in the response

**Comment by si458** [comment]
was going to have a look at this tomorrow,
did you fix the issue or something mis-configured?

**Comment by geekasso** [comment]
I'm thinking pwr does not show when the machines are offline. I see the
key/value pair once the devices are online.

I was expecting pwr to be false if devices were offline.
