### ISSUE TITLE
Question about login token custom time

### ISSUE THREAD

**Issue by dkhan717** [Ylianst/MeshCentral#609]
Hi, is it possible to give access to a specific user for more then 1 hour.

I am using this from document:

"The “userid” is actually a combination of three values - user, domain, and username in a single 
string “user/domain/username”. The example above is using a default domain which is empty 
hence, the userid will be just “user//admin” to request for login token. Domains are only used if 
the server in multi-tenancy mode as discussed in previous chapters.
The resulting hashed base64 encoded blob can be used as a login token for 1 hour"

I am trying to see if I could manually change from 1 hour to let's say 10 hours or 1 month etc. I understand the security risk.

Thank you

**Comment by Ylianst** [comment]
The cookie is indeed time limited, however when you are connected, the browser will request a new cookie every 30 minutes automatically, so this should not be a problem. There is a server setting to make the session disconnect after a set idle timeout (See #260) if you need that. Hope that helps.

**Comment by dkhan717** [comment]
Thank you for the reply, I some what understand after reading from #260 
I wish I could  some how create a token or special link for a given user to access nodes without using a username and password for custom days. 

The reason I want it this way so they don't have to login twice. One to my website second to mehscenral. I use meshcentral for teaching so I can create groups per user then inside my own materials I can point links to "nodes" so they don't have to login. 

To add to my problem I do want to keep username and password, but wanted to create something temporary for little longer to have my students access nodes.

Hope I make any sence :) 

Thank you for all the help

**Comment by Ylianst** [comment]
This makes sense. To do this, the cookie would have to be modified to include not only the time but also what device and permissions would be granted. Just granting a limited cookie without added restrictions would be a security risk. You can only another issue if you like requesting this feature be added and I can work on it. I think it would be useful for many users.

This said, I am traveling a lot in the next 3 weeks, so new features will have to wait a bit.

**Comment by dkhan717** [comment]
Perfect, thank you so much and have a great trip I will wait for this feature meanwhile I will be happy to report any bugs and usage experience with you and other members here.

I think it's one of the best remote tools I have used so far.

Regards

**Comment by Ylianst** [comment]
Ok. I will close this question. If you can open a new issue with a request for that new feature, I will take a look at it then I get back. I am traveling a lot in the next 3 weeks.
