### ISSUE TITLE
Meshcntrl.js filter device by name that is number broken

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#6091]
NODE meshctrl.js ListDevices  [..private stuff...] --json --group xxxxx --filter "1490"

throws
data.nodes[meshid] = parseSearchOrInput(data.nodes[meshid], args.filter.toLowerCase());

resolved by adding to line 2244:
data.nodes[meshid] = parseSearchOrInput(data.nodes[meshid], args.filter.toString().toLowerCase());

tag and atag do not seem to have to the tolowercase issue

**Comment by si458** [comment]
yep can confirm! pushed your fixed thank you! https://github.com/Ylianst/MeshCentral/commit/77d268d064c1a450a3038bd12397b1e25e993dd6
