### ISSUE TITLE
PERFORMED POWER ACTION ERROR

### ISSUE THREAD

**Issue by mtran-88** [Ylianst/MeshCentral#6094]
**Describe the bug**
I am seeing an error on my meshcentral server.  It is a performedpoweraction error.  I will attach an image. 

**To Reproduce**
This happens when I have the server running, and the error just pops up. 

**Expected behavior**
I expect there would be no error! ;)

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/166559124/7661bb0c-91b0-4a8a-bdf7-d7f0a55c7599)

**Server Software (please complete the following information):**
 - OS: Windows 10 Pro-64
 - Virtualization: None
 - Network: Hybrid Mode
 - Version: 1.1.22
 - Node: 21.7.2

**My config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "title": "My MeshCentral Server",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail",
    "names": "meshcentral.mydomain.com",
    "skipChallengeVerification": true,
    "production": true
  }
}

**Comment by si458** [comment]
this isnt an error. its a log message to let you know that somebody has preformed a power action 👍

**Comment by mtran-88** [comment]
Thanks for a quick response!   does that mean that a mesh agent client did a power down manually or lost power???  Is there a way to check which device that is?

**Comment by si458** [comment]
no, it means that an admin or user, preformed a power action like shutdown/restart on a computer
note: this is from the 'actions' button on the general/desktop tabs OR the meshctrl.js,
NOT the physical machine shutting down or restarting by an end user pressing turn off/restart

also the device is basically the nodeid without the `node//` - e.g: `a1b2c3d4e5f6g7h8i9j0`
you can use that in your web browser to see what device it was
`https://meshcentral.myserver.com/?viewmode=10&gotonode=a1b2c3d4e5f6g7h8i9j0`
