### ISSUE TITLE
Linux Agent Install Fails on Solus

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#61]
Linux install script on Solus gives this error...

Mesh agent downloaded.
./meshinstall.sh: line 126: /lib/systemd/system/meshagent.servive: No such file or directory
Failed to enable unit: Unit file meshagent.service does not exist.
Failed to start meshagent.service: Unit meshagent.service not found.
Mesh agent started.

**Comment by jsastriawan** [comment]
I do not have Solus with me but it seems Solus has different systemd structure. The script expect /lib/systemd/system to be there. You could modify that particular line to /etc/systemd instead. Will fire up a Solus vm to test after holiday.

**Comment by scottalanmiller** [comment]
If you guys need a lab for obscure stuff, we have one that we use for testing SodiumSuite that we could make available.

**Comment by Ylianst** [comment]
Interesting. I don't have that OS, but if the OS structure can be determined in the script, that would be great. I am going to need more VM's.

**Comment by Ylianst** [comment]
I can't run Solus-3.9999-Budgie and GNOME in Hyper-V. It indicates "PCI: Fatal: No config space access function found" and stops boot. These images may not be compatible with Hyper-V.

**Comment by scottalanmiller** [comment]
how would you like remote access to our system?  Ours runs on KVM and has no issues :)

**Comment by Ylianst** [comment]
This issue is likely the same as the OpenSuse issue that I fixed. Can you try again to install the agent on Solus? It will probably work now. If so, feel free to close this one. The path "/lib/systemd/system/meshagent.servive" should be "**/usr**/lib/systemd/system/meshagent.servive" on some systems.

**Comment by Ylianst** [comment]
I will close this issue since I think the new Linux agent install script fixes this. Please re-open if needed.
