### ISSUE TITLE
Black space when all key combinations are deleted from the Remote Desktop

### ISSUE THREAD

**Issue by quizhead** [Ylianst/MeshCentral#6102]
**Describe the bug**
In the Desktop windows > at the bottom where you send key combinations, if all is deleted, a blank space will remain.
This blank space cannot be removed even when new combinations are entered.
I've investigated this issue for a few hours and it's very hard to fix but it seems that it involves the brower's cookies.
I'm not sure how I resolved it but I deleted cookies, refreshed the page and the default keys returned but it needs more investigation.

**To Reproduce**
1. Go to Deskop
2. Click on the key combinations
3. Right click > Customize > Delete all of them
4. See that a blank space remains with an option to remove

**Expected behavior**
I understand that a blank space must remain when all keys are deleted.
However it should be possible to delete this space when new combinations are entered.

**Screenshots**
![330817570-e83aa69e-3820-4bed-81d5-5017f14d9ed7](https://github.com/Ylianst/MeshCentral/assets/102313998/307b2583-c1af-44f6-a893-a2ddbb90eeb8)

**Server Software (please complete the following information):**
 - OS: Linux Mint 21.3
 - Network: LAN/WAN
 - Version: 1.1.22
 - Node: 22.2.0

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu, Arch, Windows
 - Network: Remote over WAN
 - Browser: Firefox

**Additional context**

**Your config.json file**
```

{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
"__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "91.65.173.11",
    "selfUpdate": false
  },
  "domains": {
    "": {
	"title": "",
	"_title2": "SimonD",
	"_welcomeText": "Test",
	"_loginPicture":"LoginPic.JPG",
	"welcomePicture": "WelcomePic.JPG",
	"welcomePictureFullScreen": true,
        "mstsc": true,
	"userSessionIdleTimeout": 15
    }
  }
}

```

**Comment by si458** [comment]
i can duplicate this issue, so im just looking into it.
whats annoying is when u delete them all, it saves them into your `localStorage` in the browser as expected.
but then it also syncs the `localStorage` back to meshcentral.
so when you login elsewhere it download the `localStorage` from meshcentral and applies it to your browser.
so all browsers have this issue haha

**Comment by si458** [comment]
fixed the issue with blank values in #6103
just in the process of adding a `Restore Default Keyboard Shortcuts` in case you want the default ones back 👍 
![image](https://github.com/Ylianst/MeshCentral/assets/765314/0d056409-0066-4126-8d93-29c3028cd9c8)

**Comment by quizhead** [comment]
Thank you, should I run the server update command?

**Comment by si458** [comment]
No because we havent done a new release,
you will have to apply the patch manually
OR install the master branch using `npm install Ylianst/MeshCentral`

**Comment by quizhead** [comment]
How can I install manually?
Another question is if I need to remove the Mesh and install the master branch or can I just install the Master without removing the Mesh?

**Comment by si458** [comment]
@quizhead as explained above, U can either

Look at the PR #6103 and manually patch the changed files
OR
Stop meshcentral and run `npm install Ylianst/MeshCentral` and this will install the master branch code (great npm trick for github), then start meshcentral
OR
Use the `master` docker image `ghcr.io/ylianst/meshcentral:master`

**Comment by quizhead** [comment]
I've stopped the service and I tried to run the master and got this error
![Screenshot_2](https://github.com/Ylianst/MeshCentral/assets/102313998/81418e92-ce2b-4e41-b0b3-ca6c31fa90ed)
I also didn't understand how can I patch manually if you can please explain

**Comment by si458** [comment]
**backup everything before hand**
make sure meshcentral is STOPPED first `systemctl stop meshcentral`
then try changing the `dependencies` inside the package.json to look like this
`"meshcentral": "github:Ylianst/MeshCentral"` rather than `"meshcentral": "^1.1.22"`
then do an `npm install`
then start meshcentral again ?
