### ISSUE TITLE
MeshAgent chat bug

### ISSUE THREAD

**Issue by Avessalom608** [Ylianst/MeshCentral#6108]
I have found that if the host has just booted and logged into its Windows account, the RDP connection separates the user and console sessions. For the same reason, the messaging browser window does not pop up.

![image](https://github.com/Ylianst/MeshCentral/assets/40124505/d57b3f52-d2aa-4e91-8c2e-e821c23d7ee4)

The problem is solved by logging the user out of the session through the "Logout" item and re-authorizing.
Windows 10 22H2 and 21H2.

**Comment by si458** [comment]
duplicate - https://github.com/Ylianst/MeshCentral/issues/4372

**Comment by Avessalom608** [comment]
I also noticed that if I completely shut down the user's session via "logout" and re-login, then the console session and the user's session in Mesh will not be separated and therefore chat and notifications will work correctly.
