### ISSUE TITLE
Autobackup Configuration

### ISSUE THREAD

**Issue by dmccracken-livewire** [Ylianst/MeshCentral#611]
Good morning Ylian,

A question…  in your post describing the autobackup feature (https://meshcentral2.blogspot.com/2019/06/meshcentral2-invitation-link-auto.html) the following configurations are displayed.

 	"AutoBackup": {
		"backupInvervalHours": 24,
		"keepLastDaysBackup": 15,
		"zippassword": "test"

For the hours, is your code actually looking for “backupInvervalHours” or is it using the correct spelling of ‘backupIntervalHours”?

**Comment by jsastriawan** [comment]
Dave, it is 'backupIntervalHours'.

Regards,


Joko
