### ISSUE TITLE
Keyboard input not working after sending Ctrl+Alt+Delete in shared link remote session

### ISSUE THREAD

**Issue by JasperE84** [Ylianst/MeshCentral#6120]
**Describe the bug**
Cannot use keyboard text input after clicking the CtrlAltDelete [Send] button in a shared link session.
This only appears to be an issue with shared link sessions. (In this case a desktop+terminal+files share session with expiry set to 48hrs)

**To Reproduce**
1. Go to meshcentral remote session using a shared link
2. Click on the "Send" button next to "Ctrl+Alt+Delete" dropdown control
3. Click any text-input object in the remote session
4. Type something and it won't work
5. Disconnect/Reconnect to remote session using the button top left
6. Text input works again

**Expected behavior**
Able to type using keyboard input after CtrlAltDelete

**Server Software (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Virtualization: Docker
 - Network: WAN
 - Version: 1.1.23
 - Node: Whatever version in latest docker

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Win 11
 - Network: Remote over VPN / WAN FQDN
 - Browser: Both Chrome and Edge (regular installation)

**Remote Device (please complete the following information):**
 - Device: ESX VM
 - OS: Server 2016 standard
 - Network: Local routed subnet
 - Current Core Version (if known): Current Core: Dec 9 2022, 1365889438

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "mongodb://mongodbadmin:REDACT@mongodb:27017",
    "cert": "REDACT.mycomp",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "REDACT",
    "port": 4430,
    "aliasPort": 443,
    "agentAliasPort": 4021,
    "agentAliasDNS": "REDACT-agent.mycomp.eu",
    "redirPort": 800,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TLSOffload": true,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "title": "MySupport",
      "title2": "docker",
      "minify": true,
      "NewAccounts": false,
      "localSessionRecording": false,
      "_userNameIsEmail": true,
      "certUrl": "https://REDACT.mycomp:443",
      "SessionRecording": {
        "onlySelectedDeviceGroups": false,
        "filepath": "/opt/meshcentral/meshcentral-data/session_recordings",
        "index": true,
        "maxRecordingSizeMegabytes": 2048,
        "protocols": [1,2]
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}

```

**Comment by si458** [comment]
huh thats weird just replicated it here
and its only the sharing page that has this bug?
if you use the normal tab/user it works no problem?

also weirdly enough you can use the arrow keys just no characters?
will look into it

**Comment by JasperE84** [comment]
Yeah I believe it did work on the normal logged in user. (I noticed it because I was testing a shared link which I use for a software vendor. They had some problems logging in to our system using the shared link. Which I found weird because I hadn't experienced this issue on my day to day usage for endpoint management)

**Comment by si458** [comment]
all done and fixed! 
its 1 line command that was missing! if you want to patch urself 👍  https://github.com/Ylianst/MeshCentral/commit/abbb0fa9ee8f5b094e02333070b8266d9e7158c3

**Comment by si458** [comment]
For docker just use master instead of v1.1.23 or latest

P.s every time we push a commit to the master branch it auto builds a master image hehe
