### ISSUE TITLE
Backspace scrolls to top on mobile SSH connection

### ISSUE THREAD

**Issue by tschettervictor** [Ylianst/MeshCentral#6122]
**Describe the bug**
Im trying to connect to a local SSH device and do some work on mobile. But whenever i hit backspace, the screen flicks to the top.

**To Reproduce**
Conncet to SSH, type some characters, and hit backspace

**Expected behavior**
I expect backspace to work without moving the screen

**Server Software (please complete the following information):**
 - OS: FreeBSD
 - Virtualization: jails
 - Network: Reverse Proxy hybrid
 - Version: 1.1.23
 - Node: 20

**Client Device (please complete the following information):**
iOS 17 safari browser

**Remote Device (please complete the following information):**
Local SSH device

```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "redacted",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "redacted",
    "sessionTime": 999,
    "port": 8443,
    "_debug": true,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "TlsOffload": "redacted",
    "_trustedProxy": "redacted",
    "MariaDB": {
      "host": "localhost",
      "user": "meshcentral",
      "password": "redacted",
      "database": "meshcentral"
    }
  },
  "domains": {
    "": {
      "title": "redacted",
      "title2": "redacted",
      "certUrl": "https://redacted",
      "ssh": true,
      "mstsc": true,
      "minify": true,
      "_newAccounts": true,
      "userNameIsEmail": true,
      "agentInviteCodes": true
    }
  },
  "smtp": {
    "host": "smtp.gmail.com",
    "port": "465",
    "from": "redacted",
    "user": "redacted",
    "pass": "redacted",
    "tls": true
  }
}
```

**Comment by si458** [comment]
ive just got out my iphone 8 ios 16, and im not getting this bug?
can u do a screen record and share the bug please?

**Comment by tschettervictor** [comment]
It doesn’t happen when you are in full screen mode. It only happens if you open the SSH connection, but don’t go into full screen mode.

**Comment by tschettervictor** [comment]
This issue has come up again. It is happing on full screen as well as no full screen mode.

version 1.1.30

**Comment by si458** [comment]
@tschettervictor what browser/hand held device and remote device?

**Comment by tschettervictor** [comment]
iPhone 13. iOS 18

remote device is a TrueNAS CORE server. Local device group.

**Comment by si458** [comment]
why dont people use old OS or old iphones, then i can use my real hardware, haha
right... stupid emulator testing it is, leave it with me 👍

**Comment by tschettervictor** [comment]
Try it in and old device, might be same issue pops up.

**Comment by si458** [comment]
ok the simulator has the same issues (and some more issues)
will need time to try and fix this.
i cant install xcode 16 on my macbook pro, so i have to use my m1 but ive run out of space 👎 
and i have to remote control the mac mini too, so leave it with me

**Comment by tschettervictor** [comment]
Any progress? It’s still present in the new .33 version. I want to switch to using meshcentral as my main access instead of guacamole but this issue is holding me back.

**Comment by si458** [comment]
Sadly not, but we do have a new beta bootstrap version u could test on ur mobile!
Maybe see if its fixed there, you just add `?sitestyle=3` to the url :)
BTW we are aware the is bugs in the new beta ui, so do report them haha

**Comment by tschettervictor** [comment]
Cool. The big is not present in the new UI looks like.

**Comment by tschettervictor** [comment]
I’m not the biggest fan of the new site. I know it’s new and will have bugs and things to work out, but my personal preference is the old style. 

Up to you guys though, I won’t complain.

Ill close this for the time being.

**Comment by si458** [comment]
@tschettervictor, that's perfectly fine if u don't like the new style! We have fixed loads of bugs already with it, which will be out in 1.1.34, I've still not been able to work out why it does it or how to fix it in the old style?

**Comment by tschettervictor** [comment]
Cool. One bug in particular. Try doing something with a local SSH device. It’s really buggy. Going to fill screen and back again just doesn’t work.
