### ISSUE TITLE
Continuous Logout Loop Issue After Login

### ISSUE THREAD

**Issue by calas80** [Ylianst/MeshCentral#6125]
**Describe the bug**
From one day to the next, I encountered this problem: Whenever anyone tries to log in, after entering their credentials, the disconnection page appears (the same page that appears when you click on "logout"). I have tried dozens of times, but this results in an infinite loop. My MeshCentral is running in an LXC on Proxmox. I tried restoring a backup from a few days ago, and everything works for about an hour, then the problem reappears identically.

Nothing has changed on my server (at least that I am aware of). I have tried both the stable version and the latest version, but the result is the same. I also tried creating a new LXC from scratch and restoring the MeshCentral configuration backup, but the problem still persists. The only unusual thing I've noticed is that the CPU is now much more occupied compared to all the other times I've checked. I don't know what to do.

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Proxmox
 - Network: LAN
 - Version: 1.1.0 and 1.1.23
 - Node: ??

**Comment by si458** [comment]
Ur didn't share ur config.json.
I know the is a current bug with 1.1.23 which the min u login can cause meshcentral to crash over and over.
But the 1.1.0 stable was released last year I believe.

**Comment by calas80** [comment]
> Ur didn't share ur config.json. I know the is a current bug with 1.1.23 which the min u login can cause meshcentral to crash over and over. But the 1.1.0 stable was released last year I believe.


Sorry, I didn't think it was necessary since I haven't modified anything and the problem occurs even with the stable version.

{
   "settings": {
      "cert": “xxxxxxxxxxx”, 
      "port": 443, 
      "redirport": 80, 
      "_minify": true, 
      "selfupdate": true, 
      "allowhighqualitydesktop": true
   }, 
   "domains": {
      "": {
         "title": "Assistenza Remota", 
         "title2": "Computers Service", 
         "welcometext": "A cura di Francesco Calamita", 
         "welcomepicture": "CS.png", 
         "titlepicture": "title.png", 
         "newaccounts": false, 
         "agentcustomization": {
            "displayName": "Computers Service - Assistenza Remota", 
            "description": "Ti offriamo la migliore esperienza di assistenza remota", 
            "companyName": "Computers Service srl", 
            "serviceName": "CS Assistenza Remota", 
            "fileName": "CS - Teleassistenza", 
            "icon": "cs.ico", 
            "image": "CS.png", 
            "installText": "Clicca su INSTALLA per permettere all\u0027operatore di prestarti la migliore assistenza possibile. Oppure clicca su CONNETTI per consentire l\u0027accesso una tantum"
         }, 
         "branding": {
			"icon": "cs.ico"
         }, 

		 "agentfileinfo": {
            "icon": "cs.ico", 
            "filedescription": "Agente per Assistenza Remota", 
            "legalcopyright": "Computers Service srl 2022 - Tutti i diritti riservati", 
            "originalfilename": "Cs Assistenza Remota", 
            "productname": "Cs Assistenza Remota"
         },
         "assistantCustomization": {
            "title": "CsRemote - Richiesta supporto", 
            "image": "CS.png", 
            "filename": "CsRemote Ticket"
         }
   }, 
	"letsencrypt": {
		"email": "info@coserv.it",
		"names": "assistenza.coserv.it",
		"rsaKeySize": 3072,
		"production": false
	  }
      
   }
}

**Comment by calas80** [comment]
> Ur didn't share ur config.json. I know the is a current bug with 1.1.23 which the min u login can cause meshcentral to crash over and over. But the 1.1.0 stable was released last year I believe.

Sorry, I didn't think it was necessary since I haven't modified anything and the problem occurs even with the stable version.

```
{
   "settings": {
      "cert": “xxxxxxxxxxx”, 
      "port": 443, 
      "redirport": 80, 
      "_minify": true, 
      "selfupdate": true, 
      "allowhighqualitydesktop": true
   }, 
   "domains": {
      "": {
         "title": "Assistenza Remota", 
         "title2": "Computers Service", 
         "welcometext": "A cura di Francesco Calamita", 
         "welcomepicture": "CS.png", 
         "titlepicture": "title.png", 
         "newaccounts": false, 
         "agentcustomization": {
            "displayName": "Assistenza Remota", 
            "description": "assistenza remota", 
            "companyName": "Assistenza", 
            "serviceName": "CS Assistenza Remota", 
            "fileName": "CS - Teleassistenza", 
            "icon": "cs.ico", 
            "image": "CS.png", 
            "installText": "Clicca su INSTALLA per permettere all\u0027operatore di prestarti la migliore assistenza possibile. Oppure clicca su CONNETTI per consentire l\u0027accesso una tantum"
         }, 
         "branding": {
			"icon": "cs.ico"
         }, 

		 "agentfileinfo": {
            "icon": "cs.ico", 
            "filedescription": "Agente per Assistenza Remota", 
            "legalcopyright": "Assistenza", 
            "originalfilename": "Assistenza Remota", 
            "productname": "Assistenza Remota"
         },
         "assistantCustomization": {
            "title": "Remote - Richiesta supporto", 
            "image": "CS.png", 
            "filename": "Remote Ticket"
         }
   }, 
	"letsencrypt": {
		"email": "info@cxxx.it",
		"names": "assist.it",
		"rsaKeySize": 3072,
		"production": false
	  }
      
   }
}
```

**Comment by calas80** [comment]
The problem occurs exactly after one hour.

**Comment by si458** [comment]
a few things you can try:
1. `branding` isnt a valid json object for config.json so remove it
2. remove `selfupdate` or set `selfupdate: false` this stops meshcentral checking for updates every hour,
then trying to auto update if a new update is available
4. the is a BUG in the latest 1.1.23 which you might be hitting
https://github.com/Ylianst/MeshCentral/issues/6121
https://github.com/Ylianst/MeshCentral/issues/6118
so the fix is to follow this step to patch the bug https://github.com/Ylianst/MeshCentral/issues/6118#issuecomment-2129107029
OR use the `master` docker image
OR install from the master branch `npm install Ylianst/MeshCentral`

**Comment by si458** [comment]
plz can u also try 1.1.24 as this has [this patch](https://github.com/Ylianst/MeshCentral/issues/6118#issuecomment-2129107029) included

**Comment by calas80** [comment]
> a few things you can try:
> 
> 1. `branding` isnt a valid json object for config.json so remove it
> 2. remove `selfupdate` or set `selfupdate: false` this stops meshcentral checking for updates every hour,
>    then trying to auto update if a new update is available
> 3. the is a BUG in the latest 1.1.23 which you might be hitting
>    [Updated from 1.22 to 1.23 and Now Crashing from meshuser.jsL821 realname #6121](https://github.com/Ylianst/MeshCentral/issues/6121)
>    [ERROR NEW UPDATE 1.1.23 #6118](https://github.com/Ylianst/MeshCentral/issues/6118)
>    so the fix is to follow this step to patch the bug [ERROR NEW UPDATE 1.1.23 #6118 (comment)](https://github.com/Ylianst/MeshCentral/issues/6118#issuecomment-2129107029)
>    OR use the `master` docker image
>    OR install from the master branch `npm install Ylianst/MeshCentral`



> a few things you can try:
> 
> 1. `branding` isnt a valid json object for config.json so remove it
> 2. remove `selfupdate` or set `selfupdate: false` this stops meshcentral checking for updates every hour,
>    then trying to auto update if a new update is available
> 3. the is a BUG in the latest 1.1.23 which you might be hitting
>    [Updated from 1.22 to 1.23 and Now Crashing from meshuser.jsL821 realname #6121](https://github.com/Ylianst/MeshCentral/issues/6121)
>    [ERROR NEW UPDATE 1.1.23 #6118](https://github.com/Ylianst/MeshCentral/issues/6118)
>    so the fix is to follow this step to patch the bug [ERROR NEW UPDATE 1.1.23 #6118 (comment)](https://github.com/Ylianst/MeshCentral/issues/6118#issuecomment-2129107029)
>    OR use the `master` docker image
>    OR install from the master branch `npm install Ylianst/MeshCentral`



The first two points have already solved the problem. Thank you so much, you saved me from a bad situation.
