### ISSUE TITLE
UNABLE TO USE GOOGLE AUTHENTICATOR APP

### ISSUE THREAD

**Issue by mtran-88** [Ylianst/MeshCentral#6138]
**Describe the bug**
When I tried to use the authenticator app, it gave a '2 step login activation failed' error.  I've followed the instructions, but still not able to activate after many tries. 

**To Reproduce**
1. Go to 'manage authenticator app'
2. Click on the link.
3. Load up the google authenticator app on iphone, and scan the QR code.
4. Enter the Token on the google authenticator app into the displayed window on meshcentral. 

**Expected behavior**

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/166559124/2480acff-f8a1-4ab9-862b-47632e8355ea)

**Server Software (please complete the following information):**
 - OS: Windows 10 Pro -64
 - Virtualization: No
 - Network: Hybrid
 - Version: 1.1.22
 - Node:  v21.7.2

**Client Device (please complete the following information):**
 - Device:  NUC
 - OS:  Windows 11 pro-64
 - Network: Local to Meshcentral
 - Browser: Edge
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: NUC
 - OS: Windows 11 iot Enterprise
 - Network: [e.g. Local to Meshcentral, remote over WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

> info{     "meshVersion": "v1.1.22",     "nodeVersion": "v21.7.2",     "runMode": "Hybrid (LAN + WAN) mode",     "productionMode": false,     "database": "NeDB",     "platform": "win32",     "arch": "x64",     "pid": 9884,     "uptime": 579218.0794424,     "cpuUsage": {         "user": 175890000,         "system": 63750000     },     "memoryUsage": {         "rss": 140374016,         "heapTotal": 67346432,         "heapUsed": 63948976,         "external": 33147537,         "arrayBuffers": 30798628     },     "warnings": [],     "allDevGroupManagers": []

**Additional context**

**Your config.json file**
```
 "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
 "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
 "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
 "settings": {
   "cert": "meshcentral.mydomain.com",
   "_WANonly": true,
   "_LANonly": true,
   "_sessionKey": "MyReallySecretPassword1",
   "port": 443,
   "_aliasPort": 443,
   "redirPort": 80,
   "_redirAliasPort": 80
 },
 "domains": {
   "": {
     "title": "MyMeshCentral Server",
     "_title2": "Servername",
     "_minify": true,
     "_newAccounts": true,
     "_userNameIsEmail": true
   }
 },
 "letsencrypt": {
   "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
   "email": "myemail@domain.com",
   "names": "meshcentral.mydomain.com",
   "skipChallengeVerification": true,
   "production": true

**Comment by si458** [comment]
Make sure ur meshcentral server and ur device have the same time/date they need to be within 30seconds of each other

**Comment by PathfinderNetworks** [comment]
My first thought is to check the time and date on the server running MeshCentral (as well as the device you are running the authenticator app on.  The time and date must be the same.

**Comment by mtran-88** [comment]
Awesome guys!  I synced up with my laptop and verify my phone was on the same time.  Delete out of google authenticator app, and rescan to start over the process.  That worked!  Appreciate it guys!
