### ISSUE TITLE
Added DBEncryption - lost a group & devices

### ISSUE THREAD

**Issue by dineshmhrjn** [Ylianst/MeshCentral#6145]
Issue similar to #1714:

In config.json, I added: "DbRecordsEncryptKey": "MyReallySecretPassword"
and then ran:
node node_modules/meshcentral --recordencryptionrecode
It successfully encrypted the data, but groups and devices are not showing. However, in the "My Server" tab, it shows "Device Groups: 1" and data in MongoDB.

MeshCentral version: 1.1.22
Monogdb version : 7.0.9

**Comment by si458** [comment]
You didn't fill out the bug template report correctly.
It has information we need to fix ur issue!

Have u tried restoring an old backup, then upgrading to 1.1.24 and then encrypting?

Did u make sure u Stop meshcentral BEFORE u encrypted the database?

Can u share ur config.json?

Was u using mongodb before u entered the dbencryption?

Wss u using nedb then changed ur config.jsok to use mongodb with dbencryption?

**Comment by dineshmhrjn** [comment]
I did some silly mistake with configuration. It is sorted now. Thank you.

**Comment by si458** [comment]
Care to share with the community/others in case they have the same issue?

**Comment by dineshmhrjn** [comment]
Sure, MongoDB was installed on another VM in Docker. I mounted a new disk for the Docker volume but was not aware that it was in /tmp. So, every time the server (localhost) restarted, all the databases were gone.

**Comment by dineshmhrjn** [comment]
Sure, MongoDB was installed on another VM in Docker. I mounted a new disk for the Docker volume but was not aware that it was in /tmp. So, every time the server (localhost) restarted, all the databases were gone.
