### ISSUE TITLE
display flash errors for external auths like saml or oidc on the login screen 

### ISSUE THREAD

**Issue by xcsdm** [Ylianst/MeshCentral#6154]
**Is your feature request related to a problem? Please describe.**
Seeing the flash errors either on the Login Screen or MeshCentral logs would greatly improve troubleshooting.

**Describe the solution you'd like**
Flash errors would have drastically improved troubleshooting of #6148 and may have lead to fixing withing needing to open an issue.

**Describe alternatives you've considered**
Seeing the errors on the login page, or in the MeshCentral logs.  (docker compose logs, in my case)

**Additional context**
Perhaps including in authlog since that can be enabled and disabled when needed.

**Comment by si458** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/765314/0e60245b-d10f-4e34-b211-34efe953ca7c)

all done! https://github.com/Ylianst/MeshCentral/commit/d7341ab153ba5a4eb9f20a9ef2f8d1cc650f84c3

**Comment by smartekIT** [comment]
after this commit, the login dialog doesn't show up at all. Only the background and header appears without the login fields like what's in the screenshot above!!

**Comment by si458** [comment]
@smartekIT oh dear what did I break!
I'm assuming ur using the master docker image?
Can u share ur config.json?

**Comment by smartekIT** [comment]
Thanks Simon, I'm not using docker but full install on ubuntu server.
Can't check the developer tool now as I have to revert back on these files to a date before this commit to get it show up again.
What I can tell you that I'm using custom background which always work until this commit!

**Comment by si458** [comment]
Hmmm that's weird?
The commit doesn't touch the background at all?
Will have a look tomorrow, do u use any external auth?

**Comment by smartekIT** [comment]
I use normal 2fa app

**Comment by si458** [comment]
@smartekIT, sorry, I meant any external auth in meshcentral, like ldap, azure, google, oauth2, etc..

When u have a min (no rush) can u share ur config.json?

**Comment by smartekIT** [comment]
No, have no external auth like that.

**Comment by smartekIT** [comment]
I use the standard config (minimum no extra options other than what's in
your sample here.)

**Comment by smartekIT** [comment]
will try to re-update it again tomorrow and see if I can get anything from the developer tool

**Comment by smartekIT** [comment]
here is the error from developer tool:
login:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at startup (login:441:36)
    at onload (login:56:134)

**Comment by smartekIT** [comment]
Hi mate, please forgive me. It was Friday night and stupid me I just realized that I only applied the changes to login.handlebars and login2.handlebars files ignoring the rest of other files in the commit.
I just applied the other files changes and it works now. sorry again.

**Comment by si458** [comment]
@smartekIT dont sweat it! we all make mistakes! glad its working :)
