### ISSUE TITLE
Disable 7 Day Power State

### ISSUE THREAD

**Issue by tobias9931** [Ylianst/MeshCentral#6159]
**Is your feature request related to a problem? Please describe.**
We can see the 7 Day Power State for every computer with MeshCentral Agent.
This is indeed sometimes very interesting.
For data privacy reasons, however, this insight should be viewed critically as 
it could be misused to monitor the working hours of employees!

**Describe the solution you'd like**
An extension in the config.json for the MeshCentral Server that can be used to switch off the display of the 7 Day Power State.

**Describe alternatives you've considered**
That it is selectable or adjustable for each device group whether the 7 Day Power State is displayed or not.

**Additional context**

**Comment by si458** [comment]
> thank you very much @si458 I doesn´t found it on https://github.com/Ylianst/MeshCentral/blob/f05eb9a198bed249c2b1a969ce17a41404ef70a6/sample-config-advanced.json

thats because that commit is from 2 years ago, not sure where you got that link from?
use the master link instead https://github.com/Ylianst/MeshCentral/blob/master/sample-config-advanced.json
