### ISSUE TITLE
Plugin update checker / status page

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#616]
Now that MeshCentral supports plugins, it would be nice if the plugin standard included an update URL the server could use to check for updates for a particular plugin. This would be necessary to make my request possible.

I'd like the MeshCentral web UI to have a "Plugins" page in the "Server" section, which can show an admin which plugins are installed on the server, which of those plugins are enabled, and which ones have new versions available.  Including the ability to enable/disable plugins and a one-click update function would be awesome, but (assuming people will actually make & publish MC plugins) even just being able to easily check on one page to see which plugins are out of date will (eventually) be extremely helpful to anyone who uses MeshCentral with plugins.

**Comment by Ylianst** [comment]
Probably one for @ryanblenis to answer. I have not played with plugin's myself and have just made sure that any plugin code does not run or impact anything if a server is deployed without them. I do think that if plugin's start being important, this request is more than reasonable.

**Comment by ryanblenis** [comment]
I've been weighing the options here for the better part of a week in preparation for this and I'm still in the planning phase of everything that needs to be implemented for this interface to be done correctly.

In addition to what you've mentioned, we also need to consider:
- Version compatibility between the plugin/MeshCentral
- The plugin having its own administrative interface (to manage plugin settings and / or provide its own functionality)
- User permissions delegation to the plugin and / or parts thereof

I'm still making my way through seeing how all the parts of MeshCentral all work together to make this happen, but rest assured, it's coming as fast as I can!

**Comment by MailYouLater** [comment]
I'm not too worried about how quickly this feature gets added, I just felt like it needed to be on the roadmap. Glad to hear you're thinking about how all the parts of a plug-in system come together.

Also, as a side-now for the future. If a one-click update function does get added at some point, it would be really nice to be able to bring up a changelog first.

**Comment by Ylianst** [comment]
I do like where this is going. Looking forward to where this goes.

**Comment by geanferrani123** [comment]
Guys, Good Evening!
I would like to know the features that these system plugins bring, where I view the list of plugins, I made a topic questioning this but unfortunately was closed, could anyone explain me?

**Comment by MailYouLater** [comment]
Basically plugins are a way for new features to be added to your MeshCentral server without adding them to MeshCentral for everybody.  For example, you might want this if you need a feature that is too use case specific to deserve being added directly to MeshCentral (e.g. to make MeshCentral work with some proprietary software).  So far, I believe there is only one MeshCentral plugin: [EventLog](/ryanblenis/MeshCentral-EventLog), though hopefully more people will make (and publish) MeshCentral plugins in the future.  For now though, I would only recommend getting involved with the plugin system if you want to write a plugin of your own.

On a separate note, a lot of the issues you open here on GitHub are more discussion type comments which would fit better on another platform.  MeshCentral has it's own section on Reddit which would be perfect for your discussions: https://www.reddit.com/r/MeshCentral/

**Comment by geanferrani123** [comment]
i'm sorry people, Actually most are questions, but I will try to be an active reddit user to exchange ideas about the system as well.

**Comment by MailYouLater** [comment]
Sorry I didn't close this earlier.  This feature was implemented a while ago.  Thanks guys.
