### ISSUE TITLE
MeshCentral ignores meshcentral-web folder

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6168]
**Describe the bug**
MeshCentral ignores meshcentral-web folder -- I have downloaded a custom MeshCentral UI from here: https://github.com/DaanSelen/meshcentral-material.git
But once I move the meshcentral-web with the views and public to the meshcentral root folder, it does not work on a restart.

**To Reproduce**
1. Download and install Meshcentral using npm and move the files to /opt/meshcentral
2. Git clone the custom UI repository
3. Move the meshcentral-web folder to /opt/meshcentral
4. Restart the service
5. No change. It does however create visual bugs. Such as some pop-ups becoming way too large: 
![image](https://github.com/Ylianst/MeshCentral/assets/80752476/9c528202-b1a0-4d3c-982d-72e4ddb0ca6a)
 

**Expected behavior**
In the past, these steps would produce a new looking MeshCentral UI.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/80752476/b701dc0f-f409-42bc-80f9-7c2f2a7e3386)

Web-Page (In Dutch):
![image](https://github.com/Ylianst/MeshCentral/assets/80752476/b307ecde-6c28-4968-83a4-bd1febf0b760)

**Server Software (please complete the following information):**
 - OS: Debian 12 (bookworm)
 - Virtualization: ESXi as hypervisor
 - Network: Default configuration on a private NAT'ed Ipv4 address.
 - Version: 1.1.24
 - Node: `Node.js v18.19.0`

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11 23H2
 - Network: Through VPN directly to the NAT'ed MeshCentral IP.
 - Browser: Brave Browser

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

Thanks in advance.

**Comment by si458** [comment]
also the `default.handlebars` is for ENGLISH
so if you change the page to say french/german/etc, it wont use the version you want so you need to run the translate
1. `cd /opt/meshcentral/node_modules/meshcentral/translate`
2. `node translate.js` -> this will install extra packages and WILL FAIL BUT ITS OK!
3. `node translate.js` -> run it again and this time it should now output info
4. `node translate.js --translate` -> have a brew and wait 5-10mins
5. restart meshcentral
6. refresh ur web ui

**Comment by DaanSelen** [comment]
Yes, it was the language setting which made it not work. Are those set into the handlebars?

**Comment by DaanSelen** [comment]
Excuse my reopening, but the commands regarding the translate.js I get this:
```
celdrith@mesh:/opt/meshcentral/node_modules/meshcentral/translate$ node translate --translate
MeshCentral web site translator
Usage "node translate.js [command] [options]
Possible commands:

  CHECK [files]
    Check will pull string out of a web page and display a report.

  EXTRACT [languagefile] [files]
    Extract strings from web pages and generate a language (.json) file.

  EXTRACTALL (languagefile)
    Extract all MeshCentral strings from web pages and generate the languages.json file.

  TRANSLATE [language] [languagefile] [files]
    Use a language (.json) file to translate web pages to a give language.

  TRANSLATEALL (languagefile) (language code)
    Translate all MeshCentral strings using the languages.json file.

  MINIFY [sourcefile]
    Minify a single file.

  MINIFYDIR [sourcedir] [destinationdir]
    Minify all files in a directory.

  MINIFYALL
    Minify the main MeshCentral english web pages.

  MERGE [sourcefile] [targetfile] [language code]
    Merge a language from a translation file into another translation file.

  TOTEXT [translationfile] [textfile] [language code]
    Save a text for with all strings of a given language.

  FROMTEXT [translationfile] [textfile] [language code]
    Import raw text string as translations for a language code.
```

**Comment by si458** [comment]
DUPLICATE https://github.com/Ylianst/MeshCentral/issues/6022
looking into it soon
