### ISSUE TITLE
Sorting active rdp sessions upon connection

### ISSUE THREAD

**Issue by SMART-ALEX-T** [Ylianst/MeshCentral#6170]
_**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Need to sort active RDP sessions alphabetically when clicking the button to connect to the terminal server. It is not convenient to scroll through the list if there are a large number of sessions.

_**Describe the solution you'd like**
A clear and concise description of what you want to happen._

When I click connect, the list of sessions should be sorted by username - alphabetically. Or there should be a button that allows you to sort this list.

**Comment by si458** [comment]
im assuming your list looks like below and you only want to sort it by the username and not including the hostname?
(can you share example screenshot?)
BEFORE:
```
Connected, Console
Active, RDP-Tcp#0 - ACFTP2022/Administrator
Active, RDP-Tcp#1 - ACFTP2022/User1
Active, RDP-Tcp#2 - ACFTP2022/Fred
Active, RDP-Tcp#3 - ACFTP2022/User2
Active, RDP-Tcp#4 - ACFTP2022/Jones
```
AFTER:
```
Connected, Console
Active, RDP-Tcp#0 - ACFTP2022/Administrator
Active, RDP-Tcp#2 - ACFTP2022/Fred
Active, RDP-Tcp#4 - ACFTP2022/Jones
Active, RDP-Tcp#1 - ACFTP2022/User1
Active, RDP-Tcp#3 - ACFTP2022/User2
```

**Comment by SMART-ALEX-T** [comment]
Yes, that's exactly right

<img width="256" alt="image" src="https://github.com/Ylianst/MeshCentral/assets/172368082/4d03b69c-6a47-4c14-a343-4849aace3107">

**Comment by si458** [comment]
Ok! So I'll do a value u can set inside if your domains section in config.json
So u can say sort by terminal id OR sort my username or none!
As ur screenshot shows both the username and the terminal id as not sorted haha

I'm guessing its listing them by most recent activity first

**Comment by SMART-ALEX-T** [comment]
Thank you, this will be what we need

**Comment by si458** [comment]
ok ive added an option called `userSessionsSort` under the `domains` section of `config.json`
so this will apply to all users in per domain basis!

`Arange the Connect sessions offered when multiple Terminal Sessions are present by 'SessionId', 'StationName' or 'Username' with 'SessionId' as the default sorting criteria.`

**Comment by SMART-ALEX-T** [comment]
Unfortunately, the sessions are not sorted.
![image](https://github.com/Ylianst/MeshCentral/assets/172368082/e1fbb586-99af-4ea3-9ec3-7c7d280a5bf0)
![image](https://github.com/Ylianst/MeshCentral/assets/172368082/1c775a28-82ce-489d-a472-599f5fc5d140)

**Comment by si458** [comment]
i have only just merged it!
so you have to wait for a new release,
OR
stop meshcentral, `npm install Ylianst/MeshCentral`, start meshcentral - NPM
OR
`image: ghcr.io/ylianst/meshcentral:master` DOCKER

**Comment by SMART-ALEX-T** [comment]
Thank you very much! Now everything works. :)

**Comment by si458** [comment]
@SMART-ALEX-T just be aware,
using those install methods above, basically latch onto the LATEST code in the `master` repo, 
so the could be bugs/issues! but if you spot things, do open new issues and report them :) 

p.s. can u share screenshots of it working hehe, would be nice to see its all ok

**Comment by SMART-ALEX-T** [comment]
Certainly)
![image](https://github.com/Ylianst/MeshCentral/assets/172368082/b993d440-62db-42b9-9506-e35a822efa7f)
