### ISSUE TITLE
Remote desktop wallpaper removal

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#618]
Dear, good afternoon!

Is it possible to implement meshcentral to temporarily remove wallpaper from the workstation until the remote session ends? Such action is allowed in programs like LogMein and help to gain remote connection quality.

In other words, the idea would be to have an option called (disable user wallpaper) and when the technician ends remote answering, the wallpaper will return to normal.

**Comment by MailYouLater** [comment]
Personally, while I understand the reason for this feature, I really dislike it in tools such as TeamViewer.  If this feature is added, please make it optional.

**Comment by geanferrani123** [comment]
Yes, it will be important if optional

**Comment by Ylianst** [comment]
@krayon007 will have to look into this as a new agent feature. Once done, I can make it configurable on the server.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.5-b with Bryan's next-gen MeshAgent. Lots of features including this one. If you see a little tree icon on the bottom right of the remote desktop view, you can use it to toggle the remote wallpaper to a solid color. Works on Windows and many Linux distributions. Feedback appreciated.

![MC2-WallPaper](https://user-images.githubusercontent.com/1319013/69851809-772a8d00-1237-11ea-9403-10c331f4cfe0.png)

**Comment by adsgreen** [comment]
Tested on windows server build 14393 (build 1607) and works

**Comment by geanferrani123** [comment]
Oh my god, this feature is awesome lol ..

Ylianst, homologated on windows 10 and windows 7, working without problems. Please leave this topic open, I will approve in windows server 2016 and 2012 and already post the feedback

**Comment by dnutan** [comment]
Sorry to "reopen" this issue. Was wallpaper restore on disconnection implemented? It is easily enough to toggle it by hand but, although not to important, could be neat if automated.
