### ISSUE TITLE
Let's Encrypt reset when settings changes

### ISSUE THREAD

**Issue by GnaXi** [Ylianst/MeshCentral#619]
Hi,

I've setup a server with a couple of separate customer portals, which each have their own DNS.
Example:

```
        "domains": {
                "": {
                        "title": "main",
                },
                "company1": {
                        "title": "company1",
                        "Dns": "meshcentral.company1.tld"
                },
                "company2": {
                        "title": "company2",
                        "Dns": "meshcentral.company2.tld"
                }
        },
```

All 3 instances are working great, however, only company1 is getting a letsencrypt certificate with the following letsencrypt setup:

```
        "letsencrypt": {
                "email": "webmaster@domain.tld",
                "names": "meshcentral.company1.tld,meshcentral.company2.tld",
                "rsaKeySize": 3072,
                "production": true
        }
```

I've also looked into: /meshcentral-data/letsencrypt/live and I'm only seeing meshcentral.company1.tld in there even after a couple of days of waiting.

Does the letencrypt implementation currently only support one DNS address?

**Comment by Ylianst** [comment]
Hi. First, you should also include your default DNS name in the "names" list. So, if you have:

`cert: "myserver.sample.com"`

In the settings, section... then names should be:

`"names": "myserver.sample.com,meshcentral.company1.tld,meshcentral.company2.tld",`

Next, if you just added a new domain to your server, MeshCentral will not currently detect this and renew the certificate with the new names. You can go in "meshcentral-data" and rename the let's encrypt folder and start the server again. This will force the server to get a new cert with your new requirements.

Also, if you are doing testing, please use "production":false so not to get banned from Let's Encrypt. Let me know if that helps.

**Comment by GnaXi** [comment]
Ah! Deleting the letsencrypt folder and restarting the service did the trick.
Just have to remember doing that whenever I add another company to the config file.
Suggestion. Would it be possible for the software to automatically detect when a new dns and company/customer is added, to avoid having to do this manually? :)

**Comment by Ylianst** [comment]
Yes, this is a good feature request. This is my last day coding, I am traveling a lot in the next 3 weeks. When I get back I will take a look at automating this.

**Comment by GnaXi** [comment]
Has some changes been made?
Now, even when deleting the letsencrypt folder, my company1 and company2 are just using the self-signed certificates instead of ones provided by letsencrypt.

**Comment by zaggynl** [comment]
Any update on how to forcibly renew a letsencrypt certificate?
I see the same as GnaXi, if I remove/rename the letsencrypt-data folder and restart the folder a self signed certificate is used.

**Comment by si458** [comment]
i believe this has already been implemented now
```
obj.checkRenewCertificate = function () {
        if (obj.pendingRequest == true) { obj.log("Request for certificate is in process."); return 4; }
        if (obj.certNames == null) {
            obj.log("Got no certificates, asking for one now.");
            obj.requestCertificate();
            return 1;
        } else {
            // Look at the existing certificate to see if we need to renew it
            var daysLeft = Math.floor((obj.certExpire - new Date()) / 86400000);
            obj.log("Certificate has " + daysLeft + " day(s) left.");
            if (daysLeft < 45) {
                obj.log("Asking for new certificate because of expire time.");
                obj.requestCertificate();
                return 2;
            } else {
                var missingDomain = false;
                for (var i in obj.leDomains) {
                    if (obj.parent.certificateOperations.compareCertificateNames(obj.certNames, obj.leDomains[i]) == false) {
                        obj.log("Missing name \"" + obj.leDomains[i] + "\".");
                        missingDomain = true;
                    }
                }
                if (missingDomain) {
                    obj.log("Asking for new certificate because of missing names.");
                    obj.requestCertificate();
                    return 3;
                } else {
                    obj.log("Certificate is ok.");
                }
            }
        }
        return 0;
    }
```
