### ISSUE TITLE
Windows installer "MeshCentralInstaller.exe" don´t work for V 1.1.24

### ISSUE THREAD

**Issue by muepep** [Ylianst/MeshCentral#6193]
We try to install Meshcentral on a Windows system - this works for V 1.1.22.
Since release 1.1.24 the setup stops with "Cant´t find node_modulesfolder, installation failded."
Folder C:\Program Files\Open Source\MeshCentral are created.
The error ocurs even if we install node.js before.

**Comment by si458** [comment]
are you using the latest meshcentralinstaller.exe from the website?

https://meshcentral.com/downloads.html
https://meshcentral.com/tools/MeshCentralInstaller.exe

did it install nodejs ok?

**Comment by muepep** [comment]
Yes we use this actual download of the installer.
Yes node.js are installed V 18.19.0
Same error we install actual node.js V 20.14.0 before we start meshcentrralinstaller
We use windows server 2022

**Comment by muepep** [comment]
same problem if we use windows 10

**Comment by si458** [comment]
hmm yes im seeing sort of the same issue,  it just sits on `Installing MeshCentral Service...`
i can see it install node fine, npm installs fine, installs service fine,
but then doesnt start the service for some reason?
BUT while its stuck on `Installing MeshCentral Service...`
if i go into Windows Services then start the meshcentral service, it carrys on and finishes perfectly fine!?

**Comment by muepep** [comment]
Sorry,
i didn´t reach this point. The MC-Service is in
"C:\Program Files\Open Source\MeshCentral\winservice\daemon\meshcentral.exe"
(seen on a server which run´s 1.1.22)
Trying to install 1.1.24 the folder
C:\Program Files\Open Source\MeshCentral
Remains empty – but is created
Getting this error
***@***.***
Where can i find some log-files of this task ?


Freundliche Grüße

i.A. Jürgen Münch-Peplinski
Dipl.Ing. (FH)
IT-Infrastruktur

***@***.***

RAFI GmbH & Co. KG
Ein Unternehmen der RAFI-Gruppe

Ravensburger Straße 128-134
88276 Berg
Deutschland

T

+49 751 89-6743





***@***.******@***.***>
rafi-group.com<https://protection.retarus.com/v1?u=http%3A%2F%2Fwww.rafi-group.com%2F&c=3ikQ43P&r=32LR2vb0g2VCh9tQHTY5T6&k=7s1&s=4Tr4SnCxSIXE0YcoNeTJbs96ojb50xyGTb3dsfkt7qa>

***@***.***<https://www.linkedin.com/company/rafi-gmbh-&-co-kg/mycompany/?viewAsMember=true>    ***@***.*** <https://www.xing.com/pages/rafi>     ***@***.*** <https://www.youtube.com/channel/UCIM3XfMly0DlfuW3ZSEwN1A>

Kommanditgesellschaft: Sitz Berg, Amtsgericht Ulm, HRA 550059
Komplementärin: RAFI Beteiligungs-GmbH, Sitz Berg, Amtsgericht Ulm HRB 550074
Geschäftsführer: Dr. Lothar Seybold, Dipl.-Kfm. Lothar Arnold

**Comment by si458** [comment]
**HUH? 😕** 
can you share a screenshot of folder and also the error?

have you tried right clicking and running as admin?

also juct try removing the `C:\Program Files\Open Source` folder FIRST before re-running
as i did notice on a test machine of mine, that the `Open Source` folder had weird permissions set
and i couldnt delete it as i didnt OWN the folder which seemed odd?

**Comment by muepep** [comment]
Hi,

sure i run this as admin.
I have done a (unattended) installation of this system before I try to install (same unattended installation I use for the  system which works with 1.1.22) – so I am sure that the folder doesn´t exist before the installation starts
***@***.***

Rights seems to be normal, no problem to delete this folder



Freundliche Grüße

i.A. Jürgen Münch-Peplinski
Dipl.Ing. (FH)
IT-Infrastruktur

***@***.***

RAFI GmbH & Co. KG
Ein Unternehmen der RAFI-Gruppe

Ravensburger Straße 128-134
88276 Berg
Deutschland

T

+49 751 89-6743





***@***.******@***.***>
rafi-group.com<https://protection.retarus.com/v1?u=http%3A%2F%2Fwww.rafi-group.com%2F&c=3ikQ43P&r=32LR2vb0g2VCh9tQHTY5T6&k=7s1&s=4Tr4SnCxSIXE0YcoNeTJbs96ojb50xyGTb3dsfkt7qa>

***@***.***<https://www.linkedin.com/company/rafi-gmbh-&-co-kg/mycompany/?viewAsMember=true>    ***@***.*** <https://www.xing.com/pages/rafi>     ***@***.*** <https://www.youtube.com/channel/UCIM3XfMly0DlfuW3ZSEwN1A>

Kommanditgesellschaft: Sitz Berg, Amtsgericht Ulm, HRA 550059
Komplementärin: RAFI Beteiligungs-GmbH, Sitz Berg, Amtsgericht Ulm HRB 550074
Geschäftsführer: Dr. Lothar Seybold, Dipl.-Kfm. Lothar Arnold

**Comment by si458** [comment]
im not sure what you mean by it works on my 1.1.22 system?
the meshcentralinstaller just installs the latest version every time you run it?
so how have you installed 1.1.22?

**Comment by muepep** [comment]
Sec. screenshot
***@***.***

Access rights
***@***.***

Freundliche Grüße

i.A. Jürgen Münch-Peplinski
Dipl.Ing. (FH)
IT-Infrastruktur

***@***.***

RAFI GmbH & Co. KG
Ein Unternehmen der RAFI-Gruppe

Ravensburger Straße 128-134
88276 Berg
Deutschland

T

+49 751 89-6743





***@***.******@***.***>
rafi-group.com<https://protection.retarus.com/v1?u=http%3A%2F%2Fwww.rafi-group.com%2F&c=3ikQ43P&r=32LR2vb0g2VCh9tQHTY5T6&k=7s1&s=4Tr4SnCxSIXE0YcoNeTJbs96ojb50xyGTb3dsfkt7qa>

***@***.***<https://www.linkedin.com/company/rafi-gmbh-&-co-kg/mycompany/?viewAsMember=true>    ***@***.*** <https://www.xing.com/pages/rafi>     ***@***.*** <https://www.youtube.com/channel/UCIM3XfMly0DlfuW3ZSEwN1A>

Kommanditgesellschaft: Sitz Berg, Amtsgericht Ulm, HRA 550059
Komplementärin: RAFI Beteiligungs-GmbH, Sitz Berg, Amtsgericht Ulm HRB 550074
Geschäftsführer: Dr. Lothar Seybold, Dipl.-Kfm. Lothar Arnold

**Comment by si458** [comment]
@muepep we dont see any screenshots when u send emails,
you need to put them inline of the email
or upload them using github website

**Comment by muepep** [comment]
Screenshots as pdf

**Comment by si458** [comment]
@muepep still no attachments in afraid

**Comment by muepep** [comment]
I installed 1.1.22 few weeks ago


im not sure what you mean by it works on my 1.1.22 system?
the meshcentralinstaller just installs the latest version every time you run it?
so how have you installed 1.1.22?

**Comment by muepep** [comment]
[screenshots.pdf](https://github.com/user-attachments/files/15923467/screenshots.pdf)

**Comment by muepep** [comment]
Sorry, yesterday I running out of time, now it works you get a pdf with screenshots

**Comment by si458** [comment]
can you just try running `node -v` and `npm -v` from your command line and see if it outputs anything?
i think the installer cant find node.exe and npm.exe, they should be set in your environment variables of the system PATH

**Comment by muepep** [comment]
On both systems the path contains
C:\Program Files\nodejs\
Commands returns the version on both systems

node -v
v20.14.0
and
npm -v
10.7.0

**Comment by si458** [comment]
can you just try running the commands directly from a fresh 'command prompt', without cd to any folder?

**Comment by muepep** [comment]
Was done in this way

C:\>npm -v
10.7.0

C:\>node -v
v20.14.0

C:\>

**Comment by muepep** [comment]
Create a .js file and test node like described How to Install Node.js and NPM on Your Windows System (phoenixnap.com)<https://phoenixnap.com/kb/install-node-js-npm-on-windows>

C:\Temp>node test.js
Hello, world!

Works – but no solution for the installer problem

From: Münch-Peplinski, Jürgen
Sent: Freitag, 21. Juni 2024 14:39
To: 'Ylianst/MeshCentral' ***@***.***>
Subject: RE: [Ylianst/MeshCentral] Windows installer "MeshCentralInstaller.exe" don´t work for V 1.1.24 (Issue #6193)

Was done in this way

C:\>npm -v
10.7.0

C:\>node -v
v20.14.0

C:\>

**Comment by si458** [comment]
`if (Directory.Exists(modulesdir.FullName) == false) { displayMessage("Can't find node_modules folder, installation failed.", 2); workerThread = null; return; }`

are you customing where meshcentral gets installed at all?

all it does is run `C:\Program Files\nodejs\npm.cmd install --no-package-lock meshcentral` from the `ServerInstallPath` folder
and that folder defaults to `C:\Program Files\Open Source\MeshCentral`

**Comment by muepep** [comment]
Hi,

No I use the default installer.,
Ok this helps – we have logfiles and a clear error message, I check this with the college form the firewall team.
Do you have any successions ?

npm error code SELF_SIGNED_CERT_IN_CHAIN
npm error errno SELF_SIGNED_CERT_IN_CHAIN
npm error request to https://registry.npmjs.org/meshcentral failed, reason: self-signed certificate in certificate chain
npm error A complete log of this run can be found in: C:\Users\u45730\AppData\Local\npm-cache\_logs\2024-06-24T12_19_01_200Z-debug-0.log

Debug-log

0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using ***@***.***
2 info using ***@***.***
3 silly config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc
4 silly config:load:file:C:\Program Files\nodejs\.npmrc
5 silly config:load:file:C:\Users\u45730\.npmrc
6 silly config:load:file:C:\Users\u45730\AppData\Roaming\npm\etc\npmrc
7 verbose title npm install meshcentral
8 verbose argv "install" "--no-package-lock" "meshcentral"
9 verbose logfile logs-max:10 dir:C:\Users\u45730\AppData\Local\npm-cache\_logs\2024-06-24T12_19_01_200Z-
10 verbose logfile C:\Users\u45730\AppData\Local\npm-cache\_logs\2024-06-24T12_19_01_200Z-debug-0.log
11 silly logfile done cleaning log files
12 silly idealTree buildDeps
13 silly fetch manifest meshcentral@*
14 http fetch GET https://registry.npmjs.org/meshcentral attempt 1 failed with SELF_SIGNED_CERT_IN_CHAIN
15 http fetch GET https://registry.npmjs.org/meshcentral attempt 2 failed with SELF_SIGNED_CERT_IN_CHAIN
16 http fetch GET https://registry.npmjs.org/meshcentral attempt 3 failed with SELF_SIGNED_CERT_IN_CHAIN
17 silly placeDep ROOT meshcentral@ OK for:  want: *
18 verbose type system
19 verbose stack FetchError: request to https://registry.npmjs.org/meshcentral failed, reason: self-signed certificate in certificate chain
19 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
19 verbose stack     at ClientRequest.emit (node:events:519:28)
19 verbose stack     at _destroy (node:_http_client:880:13)
19 verbose stack     at onSocketNT (node:_http_client:900:5)
19 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
20 verbose cwd C:\Program Files\nodejs
21 verbose Windows_NT 10.0.20348
22 verbose node v20.14.0
23 verbose npm  v10.7.0
24 error code SELF_SIGNED_CERT_IN_CHAIN
25 error errno SELF_SIGNED_CERT_IN_CHAIN
26 error request to https://registry.npmjs.org/meshcentral failed, reason: self-signed certificate in certificate chain
27 verbose exit 1
28 verbose code 1
29 silly unfinished npm timer reify 1719231544390
30 silly unfinished npm timer reify:loadTrees 1719231544410
31 error A complete log of this run can be found in: C:\Users\u45730\AppData\Local\npm-cache\_logs\2024-06-24T12_19_01_200Z-debug-0.log




if (Directory.Exists(modulesdir.FullName) == false) { displayMessage("Can't find node_modules folder, installation failed.", 2); workerThread = null; return; }

are you customing where meshcentral gets installed at all?

all it does is run C:\Program Files\nodejs\npm.cmd install --no-package-lock meshcentral from the ServerInstallPath folder
and that folder defaults to C:\Program Files\Open Source\MeshCentral

**Comment by si458** [comment]
the is something wrong with your setup/internet

**attempt 1 failed with SELF_SIGNED_CERT_IN_CHAIN**

**verbose stack FetchError: request to https://registry.npmjs.org/meshcentral failed, reason: self-signed certificate in certificate chain**

try visiting the url `https://registry.npmjs.org/meshcentral` in your browser and see if loads ok,
if its saying self-signed then the is something wrong ur side,
nothing to do with meshcentral im afraid

**Comment by silversword411** [comment]
And don't forget to pay for support services rendered: https://github.com/sponsors/si458

**Comment by si458** [comment]
closing this as stale, plus issue was due to customers firewall/router/proxy
