### ISSUE TITLE
Agent Installs, But Remote Screen Fails on Zorin

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#62]
Zorin Linux

Agent installs just fine.  Remote terminal works.  But remote screen tries to connect and fails.

This is a lab system, if you'd like remote access to it.

**Comment by Ylianst** [comment]
You are right. Just tried Zorin OS 12.4 Core and agent installs and remote desktop connects by stays black. Moving the mouse over the desktop causes a disconnection.

**Comment by krayon007** [comment]
Update is live. Update the server to 0.2.6-f

**Comment by Ylianst** [comment]
I will close this issue since it seems fixed. Please re-open if needed.
