### ISSUE TITLE
Indicate CPU idle status on devices page

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#620]
Hi Meshcentral GitHub Group,

I am wondering if an enhancement can be made to put idle status from the agent or fuel gauge for CPU utilization. More specifically to show system status would allow for scanning to see available units that could process a load.

Here is a photo to help illustrate the request.
![MeshGitIdea](https://user-images.githubusercontent.com/48393851/67818460-8f5b9080-fa6e-11e9-8eb4-7f38575163c6.jpg)

**Comment by Ylianst** [comment]
Interesting. I see where you are going with this. I am out traveling for the next 3 weeks. When I get back, certainly something I can look into.

**Comment by SomeGuru** [comment]
Perfect Thank you for planning to look into this Ylian. 👍 👍

**Comment by jsastriawan** [comment]
I think this is related to telemetry use cases not just idle or busy. Storage, RAM usages and other may he needed. I think we need to look at how to use MQTT broker capabilities to relay telemetry data (not just CPU idle status). If we clogged all capabilities at MeshAgent communication then at some point it will conflict with other requirements such as bandwidth conservative mode.
Regards,


Joko

**Comment by Ylianst** [comment]
We can certainly make these capability configurable. There is certainly going to be a bunch of work to do on telemetry use cases in the next year for MeshCentral. It would be great to get more device data and charts.
