### ISSUE TITLE
Add a theme switcher (CSS) and perhaps an icon switcher?

### ISSUE THREAD

**Issue by marclaporte** [Ylianst/MeshCentral#6202]
**Is your feature request related to a problem? Please describe.**
Different people prefer a different look and feel. More than 1 person has contributed an alternate icon set at https://github.com/Ylianst/MeshCentral/issues/5496 so it would be nice to let MeshCentral admins pick.

**Describe the solution you'd like**
Decide if CSS and icon switcher go together
Make it happen

**Describe alternatives you've considered**
N/A

**Additional context**
Here is a request to make it possible to edit CSS: https://github.com/Ylianst/MeshCentral/issues/3504
Nice idea but for the current task, we just want to pick from a list. And this will make it easier for folks to fork built-in themes, and modify them.

**Comment by marclaporte** [comment]
Here is the plan to move to Bootstrap: https://github.com/Ylianst/MeshCentral/issues/6333

**Comment by si458** [comment]
implemented here
https://github.com/Ylianst/MeshCentral/commit/8e70cd7187a4a94a799ef9e294400f3ff3da3297
https://github.com/Ylianst/MeshCentral/commit/68ac8cf86c3c089e5d051c7c4ff6a23267cbaed0
https://github.com/Ylianst/MeshCentral/commit/1b01b90cd6498a320b016933651abd509216833a
https://github.com/Ylianst/MeshCentral/commit/6a366fe174da6ba1a3e163f5b14a2d9d9b204714
https://github.com/Ylianst/MeshCentral/commit/d9262f7c9da03881fd25c363f717f452d06e117d

**Comment by tomsik-radek** [comment]
> implemented here [8e70cd7](https://github.com/Ylianst/MeshCentral/commit/8e70cd7187a4a94a799ef9e294400f3ff3da3297) [68ac8cf](https://github.com/Ylianst/MeshCentral/commit/68ac8cf86c3c089e5d051c7c4ff6a23267cbaed0) [1b01b90](https://github.com/Ylianst/MeshCentral/commit/1b01b90cd6498a320b016933651abd509216833a) [6a366fe](https://github.com/Ylianst/MeshCentral/commit/6a366fe174da6ba1a3e163f5b14a2d9d9b204714) [d9262f7](https://github.com/Ylianst/MeshCentral/commit/d9262f7c9da03881fd25c363f717f452d06e117d)
> 
> under Account Settings `Switch theme` ![image](https://private-user-images.githubusercontent.com/765314/398401967-614bafaf-6fdd-41af-b1bb-cd7f5714a249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTM2OTgsIm5iZiI6MTczNjE1MzM5OCwicGF0aCI6Ii83NjUzMTQvMzk4NDAxOTY3LTYxNGJhZmFmLTZmZGQtNDFhZi1iMWJiLWNkN2Y1NzE0YTI0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwODQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODNkODc3NGFhOTE3MmJiYTc2ODJlNDRmZTMxZjgyMjNjZDI3MTZjYjJiN2JiM2UwMGViNTdiMzJhZjI0ZGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QXixPmvbt7_-xyJ-IB6uQkzwNgnFjZSCAyRkA8fhuBk) ![image](https://private-user-images.githubusercontent.com/765314/398402176-1f9a239e-6210-4d39-9229-bd5434678cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTM2OTgsIm5iZiI6MTczNjE1MzM5OCwicGF0aCI6Ii83NjUzMTQvMzk4NDAyMTc2LTFmOWEyMzllLTYyMTAtNGQzOS05MjI5LWJkNTQzNDY3OGNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwODQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2MwNGM2OTViMWZkOTY4MzRjNTY3MzFkMGZmMzE0YjcwNjE2NTMwOWM1YWMwZTkyMGRlYmY2MTJjNjhlMWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W9Lm2iatY6wHY_G0HaHDwuU4SybJNr1ELuuYUbaGeME)

Just adding some context, the Theme Switcher is there only if you are already running a Bootstrap theme.
First you need to go to https://your_mesh_instance.tld/?sitestyle=3, then it shows up.
