### ISSUE TITLE
Changing filter category menu refills the value in the filter field

### ISSUE THREAD

**Issue by vgz** [Ylianst/MeshCentral#6206]
**Describe the bug**
If you clear the filter field and change the category (offline, online, all, etc), the filter field is reset to the last text entry. This is occurring on Safari 17.5 on macOS 14.5 and the latest version of Chrome on Win 10.

**To Reproduce**
1. Type something into the filter field.
2. Clear the filter field.
3. Change the category.

The filter field will now have the text that was cleared in step 2.

**Expected behavior**
Changing the category should not have any effect on the content of the filter field.

**Server Software (please complete the following information):**
 - OS: Ubuntu 
 - Network: LAN
 - Version: 1.1.24
 - Node: 16.20.2

**Comment by bytegun** [comment]
Hi, @Ylianst 
I would love to contribute to this open source project.
Cheers!

**Comment by si458** [comment]
OOOO yes i see the same, Safari and Chrome !
will look into it soon

**Comment by si458** [comment]
all fixed in PR!
you can test by copying the changes in the PR to `default.handlebars`
and remember to set `minify: false` and use english translation!

**Comment by vgz** [comment]
Thanks for the prompt response. I copied your changes into our server's default.handlebars and can confirm it fixes the issue. Should I close this issue since you have the open PR to track the issue with the proper fix or leave it open until the PR is merged?

**Comment by si458** [comment]
all done, closed for you 👍 
just wanted confirmation that the fix worked before i merged+closed issue!
dont forget to donate ❤️ https://www.si458.co.uk/2024/01/05/donation/
