### ISSUE TITLE
Show more system information in the details tab

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#621]
Hi Mesh Team,

Wondering if we can get more granular details of the platform that gives details of the drivers installed and revisions?

I like the memory and the other items, however I would really like to know if I have the latest Audio driver, or maybe if I have HT turned on in BIOS for the processor, if VT is turned on, CPU configuration details in depth.

Also I remember at one of the Intel Hackathons that they hosted a tool that did this internally and was developed in India. This would be awesome enhancement to your already awesome MeshCentral Platform.

**Comment by Ylianst** [comment]
I certainly want to do a lot more with the "Details" tab. It's just a matter of hours in a day, but certainly something I would like. Especially highlighting platform features. Again, I am super busy at the moment and traveling a lot in the next 3 weeks, not sure when we will get to this.

**Comment by SomeGuru** [comment]
Duplicate of #620 just additional details to follow the request of additional details.
