### ISSUE TITLE
Device lock for duration feature

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#622]
Hi Mesh Team,

Here is another idea that I am wondering if it could be implemented. Making a system locked for a duration and allowing persons to invite others to that session, and then after a duration of time elapsed the machine would become free again.

I have tried to achieve this by moving systems, but this caused the system to replicate as many after system rebooted itself. I want to avoid moving groups, and keep it in one group and lock the machine and set a time frame would be nice.

**Comment by Ylianst** [comment]
I imagine the idea is to "lock" the device on the server side. it's a good idea but I am really loaded at the moment and traveling for the next 3 weeks. So, not sure when I would get to this.

**Comment by MailYouLater** [comment]
I'm not certain I get this.  Do you mean that you want to lock a specific device so it's only accessible by a specific user? or lock it so it's not accessible at all? or something else?

Also, whichever it is, if it gets implemented, it's important that the Full Admin can bypass these locks if they deem it necessary.

**Comment by Ylianst** [comment]
if I understand correctly, it locks the device to one user. They want to be able to "check out" a computer like a library book. When check, no-one else can perform management operations on it. You are right that site administrators should be able to override.

There was another request for creating a link that would enable someone to access a device to a limited time, I think I will be doing that one first.

**Comment by SomeGuru** [comment]
Ylianst is correct. This is like a Library where the system get locked to the "User/Reader" unless the "Administrators/Librarians" unlock or change the parameters.  

Ylianst, Yes, duration based would caveat this implementation also. This would allow for the campuses that have more than 350 systems in an environment to be more efficient. 💯 🥇 👍 👍
