### ISSUE TITLE
NO managment keys in only LAN Mode  2fa,yubikey

### ISSUE THREAD

**Issue by n1ck-unikat** [Ylianst/MeshCentral#6223]
I installes Meshcentral with only LAN Mode in config.json. I have no option to set a 2fa (yubikey ,etc) under the Users Profil. The Option Managment Keys are not visible .

  Server Software 
 - OS: [Debian 12]
  - Network: [ LAN]
  

   Client Device 
 - Device: [e.g. Laptop]
 - OS: [e.g. Ubuntu]
 - Network: [e.g. Local to Meshcentral, ]
 - Browser: [Firefox]

**Comment by si458** [comment]
the way to fix this is to use a DNS name that gets resolved to your internal IP address
example below
```
{
  "settings": {
    "cert": "meshcentral.internaldomain.com",
    "lanonly": true
  },
  "domains": {
    "": {
      "title": "Internal MeshCentral"
    }
  }
}
```
