### ISSUE TITLE
Decrease memory consumption

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#623]
Guys, good morning!

I have a question regarding the server memory consumption, I noticed that the server is having a high memory consumption, is there anything I can do to decrease the consumption? Before my server was 8 GB, there was a consumption of 4 GB, now that I increased to 12 GB has only 3 GB free.

![image](https://user-images.githubusercontent.com/55212206/67857769-61219380-faf6-11e9-847f-5d871c5030db.png)

**Comment by Ylianst** [comment]
If you go in the "Stats" tab (the second one on your screenshot). you can select "Memory" and it will show a more accurate display of what memory NodeJS is using.

![x](https://user-images.githubusercontent.com/1319013/67883714-cc249780-fb01-11e9-856b-c2bcd0e4244c.png)

You can also go in the server console and type "info" to get exact numbers.

![x4](https://user-images.githubusercontent.com/1319013/67884601-56213000-fb03-11e9-84b1-9eede299176d.png)

All this said, I am not an expert in NodeJS memory use and I would really like to use less memory. If there are ways to do this, feedback appreciated.

**Comment by geanferrani123** [comment]
No problem, I would like to ask another question, Is the screen I sent so less reliable than the ones you sent me?

**Comment by Ylianst** [comment]
Both are accurate, but my screens are just for NodeJS. Your screen is all of the system memory.

**Comment by geanferrani123** [comment]
Understand, right! I believe that due to the number of machines I have in my environment, this also generates this impact that I mention, a fact that is natural, as I am demanding higher system performance.

My friend, if you want to close the topic, thanks again for your help.

**Comment by Ylianst** [comment]
Ok. Closing. But if anyone has ideas as to how MeshCentral can reduce memory use, I would like to get information on this.
