### ISSUE TITLE
Mobile view blank screen

### ISSUE THREAD

**Issue by folosleg** [Ylianst/MeshCentral#6234]
**Describe the bug**
Opening MC from a Samsung A53 Android phone (One UI 6.1, Android 14) login works, but mc shows blank page. Many browsers tested. Other phones working ok within team.

Please let me know, how can I help debugging the problem.

**Screenshots**
![mc_mobile_ui_bug](https://github.com/Ylianst/MeshCentral/assets/80481320/7200ca9a-8647-4de7-8e7c-e5f5b2e9c987)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Linode
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...]
 - Version: 1.1.24
 - Node: 20.15

**Client Device (please complete the following information):**
 - Device: Samsung A53
 - OS: One UI 6.1, Android 14
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Browser: Google Chrome, Firefox, Sansung Browser

**Comment by si458** [comment]
I've got an s24 ultra and no issues at all?
What happens when u click the title?
The big MeshCentral ar the top of the page?

**Comment by folosleg** [comment]
Nothing happens.
Another Samsung A55 5G phone within the team shows the same odd behaviour.
Happy to investigate, just give me a little guidance where to look, if you can

**Comment by si458** [comment]
@folosleg if u download Firefox for android, u can enable the remote debugging via USB, then load ur Firefox on ur PC, then connect to the instance of Firefox on ur Android device and see if the is any errors being displayed in the console?

**Comment by si458** [comment]
@folosleg have u customised any of the handlebar files? Or use meshcentral-web folder for customization?

**Comment by folosleg** [comment]
Finally I did debug the mobile site, cheers for your suggestion. It's probably a bug with the Hungarian translation? A quick remedy is to switch the user language setting from browser default to English.  So nothing to do with Samsung phones :)

Uncaught SyntaxError: missing ) after argument list (at (index):440:52)

line 440: `QH('d2optinfo', format("Telepítse fel a <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" rel="noreferrer noopener" target=_blank>Google Authenticator</a> vagy egy kompatibilis alkalmazást, használja ezt a <a href="{0}" rel="noreferrer noopener" target=_blank>linket</a>, vagy addja meg a lenti titkos kódot. Azután addja meg a jelenlegi 6 számjegyű jelszót a 2-lépcsős bejelentkezés aktiválásához.", message.url) + '<br /><br /><div style=width:100%;text-align:center><tt id=d2optsecret secret="' + message.secret + '" style=font-size:15px>' + secret + '</tt><br /><br />Token: <input type=text autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]*" onkeypress=\"return (event.keyCode == 8) || (event.charCode >= 48 && event.charCode <= 57)\" onkeyup=account_addOtpCheck(event) onkeydown=account_addOtpCheck() maxlength=6 id=d2otpauthinput type=text></div>');`

**Comment by si458** [comment]
ok all fixed, its a translate bug!
so do the following:
1. download the [translate.json](https://github.com/Ylianst/MeshCentral/blob/master/translate/translate.json) file into `translate` folder OR patch it manually from https://github.com/Ylianst/MeshCentral/commit/13b8ca3686386dd13e1dc1b9af9e39efa055173f
2. open cmd/terminal to meshcentral folder
3. `cd translate` -> go into translate folder inside of meshcentral
4. `node translate.js` -> wait it will install packages then fail, THIS IS OK TO FAIL!
5. `node translate.js` -> run again and it should spew out help information, this is again OK
6. `node translate.js translateall translate.json hu` -> translate only Hungarian
7. restart meshcentral 
8. refresh webpage!

**Comment by folosleg** [comment]
you are a legend!
cheers

**Comment by silversword411** [comment]
Don't forget to sponsor
