### ISSUE TITLE
Using Docker Compose leads into an upgrading process even if the internal-upgrade-flag is explicitely deactivated

### ISSUE THREAD

**Issue by n1smithy** [Ylianst/MeshCentral#6238]
**Describe the bug**
I start a new instance/container of meshcentral (with or without using mongodb as database) meshcentral tries to make an upgrade-process which always fails.

**To Reproduce**
Pull the latest docker-image and try to run it (in my case as a docker-compose-container, but not as a daemon to see the errors).

**Expected behavior**
A running meshcentral-container.

**Screenshots**
![Bildschirmfoto EDITED](https://github.com/Ylianst/MeshCentral/assets/140073251/d4917fe8-ce7a-403d-8e29-f148e5fe315a)

**Server Software (please complete the following information):**
 - OS: Arch Linux (hardened)
 - Virtualization: Docker
 - Version: latest Docker image at 2024 July 07 13:00
 - Node: same as version

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "selfUpdate": false,
    "_mongoDb": "mongodb://mongodb:27017/meshcentral",
    "_mongoDb": false,
    "_mongoDbcol": "meshcentral",
    "_mongoDbName": "meshcentral",
    "cert": "[CENSORED]",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "[CENSORED]",
    "_port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "trustedProxy": "[CENSORED]",
    "TLSOffload": "[CENSORED but same as trustedProxy]",
    "SelfUpdate": "false",
    "AllowFraming": "false",
    "WebRTC": "false",
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": 24,
      "keepLastDaysBackup": "",
      "zippassword": ""
    }
  },
  "domains": {
        "": {
        "title": "[CENSORED]",
    	"title2": "[CENSORED]",
	"agentCustomization": {
        	"displayName": "[CENSORED]",
        	"description": "[CENSORED]",
        	"companyName": "[CENSORED]",
        	"serviceName": "[CENSORED]",
        	"fileName": "[CENSORED]",
		"image": "[CENSORED].png",
		"installText": "[CENSORED]",
		"foregroundColor": "#[CENSORED]",
		"backgroundColor": "#[CENSORED]"
    		},
	"assistantCustomization": {
            "description": "[CENSORED]",
            "title": "[CENSORED]",
            "image": "[CENSORED].png",
            "fileName": "[CENSORED]",
	    "foregroundColor": "#[CENSORED]",
	    "backgroundColor": "#[CENSORED]"
	},
    	"_minify": true,
    	"NewAccounts": "false",
        "_userNameIsEmail": true,
    	"certUrl": "https://[CENSORED]:443"
        }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  },
  "smtp": {
	  "host": "[CENSORED]",
	  "port": "[CENSORED]",
	  "from": "noreply@[CENSORED]",
	  "user": "noreply@[CENSORED]",
	  "pass": "[CENSORED]",
	  "tls": true,
	  "tlsstrict": false,
	  "_verifyEMail": false
  }
}

```

**Comment by si458** [comment]
You have selfupdate listed twice.

Also selfupdate should be a boolean.

So make sure you keep the `selfupdate: false` and remove the one which is `selfupdate:"false"`

**Comment by n1smithy** [comment]
WTF?! deleting the entry `SelfUpdate:"false"` leaded to a correct startup – but it pulled an update of the image first, too.
Is the config.json that sensitive for setting quotation marks? didn't exspect that. Thanks a lot!

**Comment by si458** [comment]
the selfupdate has different options.

When it's set to `true`, it will autoupdate to a newer version when u start meshcentral up

If u set to a string like `"1.1.24"` it will autoupdate to that version when u start meshcentral up.

In ur case, it saw a string value of `"false"` and was trying to update to the version `false`, which doesn't exist

**Comment by n1smithy** [comment]
> In ur case, it saw a string value of `"false"` and was trying to update to the version `false`, which doesn't exist

Oh my god, not it makes soooo sense that yesterday there was a string within the error-code "meshcentral@false" … I feed dumb now! :-D Thank you so much. I try to get it to run now behind my reverse proxy now. :-D

**Comment by n1smithy** [comment]
Simon, you are my this-weekend-hero! It's working! And RDP-connection to my hosts works, too! Awesome! Thank you very much – exspecially for giving support on a sunday!
