### ISSUE TITLE
All remote sessions are disconnected when a new user, previously unknown to MeshCentral, logs in to MeshCentral via LDAP

### ISSUE THREAD

**Issue by tobias9931** [Ylianst/MeshCentral#6240]
**Describe the bug**
All remote sessions are disconnected when a new user, previously unknown to MeshCentral, logs in to MeshCentral via LDAP.

**To Reproduce**
1. Log in to MeshCentral with user A and start a remote session.
2. Open a new private browser window or go to another device and log in with user B. User B should never have logged in to MeshCentral before. (Alternatively, delete user B in the MeshCentral dashboard before). 
3. User B is logged in correctly, his user is created at MeshCentral.

At the same time, however, all remote sessions active at that time are suddenly disconnected!

**Expected behavior**
User B should be created, but all remote sessions of other users active at this time should not be disconnected at the same time.

**Screenshots**
![image](https://github.com/Ylianst/MeshCentral/assets/171915243/57989cf6-c398-4489-9b52-ec233cff40c2)

![image](https://github.com/Ylianst/MeshCentral/assets/171915243/8f52044f-b4b8-4a64-ab66-2f380a691f83)

**Server Software (please complete the following information):**
 - OS: Windows Server 2022
 - Version: 1.1.24

**Comment by si458** [comment]
this to me sounds like meshcentrasl is crashing and restarting.
in the my server tab under general, click the show error logs, is the anything listed there?

**Comment by tobias9931** [comment]
[eventslist.csv](https://github.com/user-attachments/files/16125210/eventslist.csv)
[servertrace (1).csv](https://github.com/user-attachments/files/16125211/servertrace.1.csv)

**Comment by tobias9931** [comment]
> this to me sounds like meshcentral is crashing and restarting. in the my server tab under general, click the show error logs, is the anything listed there?

No, there are no errors.
"Server has no error log."

The server and the MeshCentral dashboard are also there the entire time active and there is no disconnection.
Only the active remote connections are all disconnected.

**Comment by tobias9931** [comment]
![image](https://github.com/Ylianst/MeshCentral/assets/171915243/3415dc5e-29bf-4639-9127-33a87b78fcf5)

**Comment by si458** [comment]
**you didnt really follow the bug template as it has info we need to replicate the issue**
can u share ur config.json please?
what nodejs are you using?
how did u install meshcentral? meshcentralinstaller.exe or npm install ?

**Comment by tobias9931** [comment]
Sorry, here it is

{
    "settings": {
        "cert": "meshcentral.company.cloud",
        "Port": 443,
        "RedirPort": 0,
        "agentIdleTimeout": 600,
		"_maintenanceMode": true,
        "webRTC": true,
		"WANonly": true,
        "amtscanner": false
    },
    "domaindefaults": {
        "title": "company",
        "title2": "(ITI)"
    },
    "domains": {
        "": {
            "auth": "LDAP",
            "ldapoptions": {
                "url": [
                    "ldap://server1.company.inhouse:389/",
                    "ldap://server2.company.inhouse:389/"
                ],
                "bindDN": "CN=_Mesh Central,OU=Service_Accounts,DC=company,DC=inhouse",
                "bindCredentials": "SECRET",
                "searchBase": "DC=company,DC=inhouse",
                "searchFilter": "(sAMAccountName={{username}})"
            },
            "ldapsiteadmingroups": "CN=gl_adm_meshcentral,OU=Admin_Groups,OU=Admin_Objects,DC=company,DC=inhouse",
            "ldapuserrequiredgroupmembership": [
                "CN=gl_adm_meshcentral,OU=Admin_Groups,OU=Admin_Objects,DC=company,DC=inhouse",
                "CN=gl_aad_meshcentral_inspection,OU=AAD_Groups,OU=BERG,DC=company,DC=inhouse",
                "CN=gl_aad_meshcentral_office,OU=AAD_Groups,OU=BERG,DC=company,DC=inhouse",
                "CN=gl_aad_meshcentral_production,OU=AAD_Groups,OU=BERG,DC=company,DC=inhouse",
                "CN=gl_aad_meshcentral_external,OU=AAD_Groups,OU=BERG,DC=company,DC=inhouse",
				"CN=gl_aad_meshcentral_special,OU=AAD_Groups,OU=BERG,DC=company,DC=inhouse"
            ],
            "ldapsyncwithusergroups": {
                "filter": [
                    "gl_adm_meshcentral",
                    "gl_aad_meshcentral_inspection",
                    "gl_aad_meshcentral_production",
                    "gl_aad_meshcentral_office",
                    "gl_aad_meshcentral_external",
					"gl_aad_meshcentral_special"
					
                ]
            },
            "consentMessages": {
                "Title": "company Meshcentral",
                "consentTimeout": 60,
                "autoAcceptOnTimeout": false,
                "desktopnotify": true,
                "terminalnotify": true,
                "filenotify": true,
                "desktopprompt": true,
                "terminalprompt": true,
                "fileprompt": true,
                "desktopprivacybar": true
            },
            "agentTag": {
                "ServerName": 0,
                "ServerDesc": 1,
                "ServerTags": 3
            },
			"hidePowerTimeline": true,
            "userSessionIdleTimeout": 120,
			"userSessionsSort": "Username",
            "ldapusername": "sAMAccountName",
			"ldapUserKey": "sAMAccountName",
            "ldapuseremail": "mail",
            "ldapuserrealname": "{{{givenName}}} {{{sn}}}",
            "ldapuserphonenumber": "telephoneNumber",
            "title": "MeshCentral",
            "title2": "company",
            "footer": "ITI",
            "userAllowedIP": "10.112.0.0/16,10.113.64.0/20,10.138.0.0/16,10.124.0.0/16,10.132.0.0/16,10.116.0.0/16,10.14.2.0/24,10.4.107.0/24",
            "autoRemoveInactiveDevices": "5",
			"welcomePictureFullScreen": true,
			"welcomePicture": "company.jpg",
			"agentCustomization": {
                "foregroundColor": "200,0,0",
                "backgroundColor": "230,189,76"
            }
        }
    }
}

Node.js version 18.19.0
On other TEST System Node.js version 20.12.2
Same bug existing.

Installed via meshcentralinstaller.exe

I hope you can reproduce the bug

**Comment by dmikoss** [comment]
Can confirm this issue in my environment. 
Remote session disconnects on "New" LDAP user login first time".

**Comment by dmikoss** [comment]
On turning **OFF** ldapSyncWithUserGroups - problem is gone.

**Comment by si458** [comment]
@dmikoss im just looking at this and i can confirm my finding that
indeed if a NEW user logs in while another user has a relay/control in progress
they get disconnected?
i think its something to do with the users being added to the groups

**Comment by dmikoss** [comment]
> @dmikoss im just looking at this and i can confirm your finding that indeed if a NEW user logs in while another user has a relay/control in progress they get disconnected? i think its something to do with the users being added to the groups

With some experiments, a disconnect happens when creating a **new** user or **changing** a **user group**. The websocket connection closes.

If we create a user but do not create a user group, there are no disconnects.

I tried to find the problem in the source code but with no luck.

**Comment by si458** [comment]
i tried changing a usergroup and nothing happened BUT a new user LOGGING IN caused the issue,
its to do with the usergroups so dont worry ill get it fixed 👍
