### ISSUE TITLE
How can i activte Only 2FA Login for Accounts

### ISSUE THREAD

**Issue by Nomex1337** [Ylianst/MeshCentral#6247]
### Discussed in https://github.com/Ylianst/MeshCentral/discussions/6246

if i try to navigate round the web ui, it displays the warning saying "not possible, plz enable 2fa"

HOWEVER if i i use anything from the group actions list, then its still possible to achive this!

**Comment by si458** [comment]
all fixed in https://github.com/Ylianst/MeshCentral/commit/ee0018e4d108ee0ea0bed158fb1940e00c6f162f 👍
