### ISSUE TITLE
Add some feature of frp.

### ISSUE THREAD

**Issue by YiuTerran** [Ylianst/MeshCentral#6249]
MeshCentral is great and meets my needs for managing remote servers. However, when I connect to remote Linux servers, sometimes I need to access web services on the server (or within its local network). [frp](https://github.com/fatedier/frp) is a good solution to this problem.

MeshCentral could include some basic frp functionality, such as forwarding HTTP ports within the local network. This would satisfy the requirements of configuring many remote software.

**Comment by si458** [comment]
This is already possible.
Add remote device with the meshagent
Then click the http/https links and it will do Web relay to default 80/443 ports, or right click the http/https and specify what ports u want to relay instead 

Also if u use meshcentralrouter, u can portforward any tcp/udp port and even specify a different ip in the remote devices network!

**Comment by YiuTerran** [comment]
oh, thanks. I'll try~
