### ISSUE TITLE
Doubt - System Plugins

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#625]
Guys, good afternoon!

Looking at some topics, I saw some reports about crashes, questions, improvements involving system plugins, I would like to know what these plugins would be, as I enable the option to see the list of available plugins, could someone please explain and help me please ?

**Comment by Ylianst** [comment]
Not sure what the question is. If this is a discussion on future features, you can use [Reddit](https://www.reddit.com/r/MeshCentral/). Closing this.
