### ISSUE TITLE
Connection from mobile device no lock option for Windows machines.

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#6251]
**Describe the bug**
From mobile device no way to lock screen without interacting with the desktop. Win + L does not work, padlock icon is not shown on mobile device. Checked #2169 , #2183, #2545 - all are closed, but issue is there. Padlock is just workaround for Win+L issue which still persist.

**To Reproduce**
Just connect to windows desktop machine from mobile device - Win + L customized key combination is not working, padlock is not displayed at the bottom of the screen

**Expected behavior**
Either to have Win + L working, either to have a padlock icon to be able to use it.

**Server Software:**
 - OS: Ubuntu
 - Virtualization: none
 - Network: WAN
 - Version: 1.1.24
 - Node: 16.20.2

**Client Device :**
 - Device: Android Phone One+
 - OS: 14
 - Network: does not matter

**Remote Device :**
 - Device: All windows machines
 - OS: 10,11,2019,2016
 - Current Core Version : Dec 9 2022, 1807787178

**Comment by si458** [comment]
This isn't a bug but a feature request.

The is no lock button shown in the mobile ui so it just needs adding in :)

**Comment by si458** [comment]
OK, I spoke too soon.
the WIN+L doesn't lock the remote device in the mobile UI, weird?
Will look into it when I have a chance

**Comment by vitko-bg** [comment]
I am using MC since at least 5 years, it was working in very earlier versions, from Mobile and browser, and on a later stage with newest upgrades (before padlock button) it stopped working :) hope that helps. Not sure about the exact versions .....

**Comment by si458** [comment]
WIN+L doesnt work on normal desktop web UI either,
so this might be a windows limitation, 
need to investigate more

**Comment by vitko-bg** [comment]
Hi @si458 . Not sure if that will help, but please check #2183 , looks like @Ylianst removed this function and commented on this removal. I am 100% sure Win + L keyboard shortcut was working fine on earlier versions of MC, desktop and mobile versions - both. Hope that helps.

**Comment by si458** [comment]
ok added lock button to web ui for mobile for you https://github.com/Ylianst/MeshCentral/commit/1d9de2e1447075a7046aa05003bc4bbb4706f63f
give it 15mins and new docker image `master` will be available to test or `npm install Ylianst/MeshCentral`
for some dumb reason, it is indeed sending the key combos WIN+L to remote device and getting them,
its just windows is IGNORING it, no idea why, so just use the button!

**Comment by vitko-bg** [comment]
Confirmed as working, after update a Lock button appeared at the bottom of the screen on mobile device and it is working as it should. Thanks. However - Win + L is still mystery :)
