### ISSUE TITLE
7 Day Power State color change

### ISSUE THREAD

**Issue by acrey1** [Ylianst/MeshCentral#6253]
### Discussed in https://github.com/Ylianst/MeshCentral/discussions/6252

<div type='discussions-op-text'>

<sup>Originally posted by **acrey1** July 12, 2024</sup>
Hi Meshers,

I would like to change the colors for the 7 Day Power State to be a bit more intuitive (e.g. Green [0,128,0] = power ON, Red [255,0,0] = power OFF, Yellow [255,255,0] =  SLEEP etc).

Any ideas how this can be done?</div>

**Comment by si458** [comment]
after checking this, the colors are already in the css file.
the ID values are below
`var powerColorTable = ['pwsTransparent', 'pwsBlack', 'pwsBlue', 'pwsBlue2', 'pwsLightblue', 'pwsBlueviolet', 'pwsDarkgreen', 'pwsLightseagreen', 'pwsLightseagreen2'];`

so...
1. create the folder `meshcentral-web` next to `meshcentral-data`
2. inside `meshcentral-web` create `public`
3. inside `public` create `styles`
4. COPY `style.css` from `node_modules/meshcentral/public/styles/` to `meshcentral-web/public/styles/`
5. edit `style.css` to your hearts content (change the ID values above)
6. restart meshcentral
7. clear cache/refresh web browser
