### ISSUE TITLE
Cira connection shows on wrong devices 

### ISSUE THREAD

**Issue by Vger1** [Ylianst/MeshCentral#6255]
Hi,

My issue is sometimes a device will show a CIRA connection, but this PC is not connected with any cables.  

As a test I set up two groups with a CIRA enabled PC in each group.  
All PCs show correct name, group and CIRA connection is working. 
 I completely disconnect all cables from the PC’s in group one. 
Sometime the PC in group one will show “CIRA, Soft-off” or similar and if I connect to this device via CIRA it is the running PC in group two. 
If I access the device in group 2 it shows the same that CIRA connection

It can happen with different PC’s I have older intel gen 4 running Windows 10 and newer intel gen 12 with Windows 11.

I have tried deleting the group and clearing the AMT om the device and readding.  Once readded this device works normally. 

Is there something I’m setting incorrectly that would cause this issue? 
It looks like a database corruption issue.

In case it was an install issued I have done a clean install on AWS EC2.  I used the following for the install command.

wget https://meshcentral.com/scripts/mc-aws-linux2-mongo.sh
chmod 755 mc-aws-linux2-mongo.sh
./mc-aws-linux2-mongo.sh

I exported the data base for the old AWS instance with
node node_modules/meshcentral --dbimport bob.json

then reimported with
node node_modules/meshcentral --dbexport vger.json

all devices are visible and accessible. 

My config.json

```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "cert": "MYDOMAIN.com",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "RelayDns": [ "relay1.MYDOMAIN.com", "relay2.MYDOMAIN.com", "relay3.MYDOMAIN.com", "relay4.MYDOMAIN.com", "relay5.MYDOMAIN.com", "relay6.MYDOMAIN.com", "relay7.MYDOMAIN.com", "relay8.MYDOMAIN.com" ],
    "desktopMultiplex": true
  },
  "domains": {
    "": {
      "title": "MYDOMAIN",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "MY@Email.com ",
    "names": "MYDOMAIN.com,relay1.MYDOMAIN.com,relay2.MYDOMAIN.com,relay3.MYDOMAIN.com,relay4.MYDOMAIN.com,relay5.MYDOMAIN.com,relay6.MYDOMAIN.com,relay7.MYDOMAIN.com,relay8.MYDOMAIN.com",
    "production": true
  }
}
```
Thanks

**Comment by si458** [comment]
This is indeed a strange one.
I've never heard this happening before?

Sadly intel AMT is not really support anymore because of intel stopped sponsorship

Also I only have a single intel AMT version 7 device, and I have no issues at all with it

So I have no way of testing/fixing ur issue without somebody providing me with/sponsoring me to purchase anything device for testing

**Comment by Vger1** [comment]
Hi Simon,

 

If I was to setup a separate AWS instance with devices attached and gave you access would this help?

 

Kind Regards

 

   Nicholas Kavadis

    Managing Director

 



 

   3052 Princes Highway, Kalimna West, Vic, 3909

   

Postage address:  PO Box 902 Lakes Entrance, Vic, 3909

 

   E:  ***@***.***> ***@***.***                

   W:  <http://www.voyager.net.au/> www.voyager.net.au                                               

   P: +613 5155 2204­­­­­­ 

   M: +61 427799657­­­­­­                                                  

   ABN: 64 431 935 113

**Comment by si458** [comment]
im not too sure because i think i would need physical access to the device because if a device off,
how can i switch it back on?
thank you for the offer tho!

**Comment by b8two** [comment]
@Vger1 Check if your CIRA UUID is  "03000200-0400-0500-0006-000700080009" or if your Motherboard identifiers are duplicated in a similar way.

**Comment by Vger1** [comment]
Hi, yes this looks like the issue.  some of the new industrial PC I received all have the same UUID.  Funny thing is that after I read your message, I started researching how to change the UUID and I found old notes I had on this issue.  seems I had this issue on a couple of intel motherboard with 4770 CPUs.   I will change each device and see what happens.

maybe I should ask for a feature to be added to Meshcentral that looks at all devices in the database to check if any have the same UUID and shows a warning.

**Comment by si458** [comment]
@Vger1 now that is a good idea!

Just a simple command in the serverconsole section, like `duplicateuuids` and then lists devices that all have the same uuids!

Would that work?

**Comment by Vger1** [comment]
That Sounds Good.

**Comment by Vger1** [comment]
Out of interest is there any other mother board identifiers that Cira or the Mesh agent use apart from UUID?

**Comment by si458** [comment]
@Vger1 sorry for the delay,

the AMT simply uses the motherboard UUID for its identification,
and meshcentral then creates a meshid which is generated from that UUID,
but if you delete the device and let amt recreate the device, the meshid will be different because of the way its generated the meshid

we could also do with some documentation here https://ylianst.github.io/MeshCentral/intelamt/
(doc source is here - https://github.com/Ylianst/MeshCentral/tree/master/docs/docs/intelamt)
just simple explaining that the device UUIDs MUST BE UNIQUE
also maybe some steps how to generate them and replace them with examples
