### ISSUE TITLE
Pulling Utilities-sidebar just works fine in one direction

### ISSUE THREAD

**Issue by n1smithy** [Ylianst/MeshCentral#6257]
**Describe the bug**
Being in an remote-desktop-session (agent, didn't test it with RDP) opening the utilities-sidebar (in German: "Werkzeuge") it's nearly impossible to greaten the size of the sidebar, but shrinking it works fine. It's like using a magnet which loses bindings to the metal. And after releasing the mouse-button it's like the button is toggled.

**To Reproduce**
Like discribed above

**Expected behavior**
1. As long as one holds the mouse-button the sidebar should be able to be resized.
2. The mouse-button shouldn't have a toggle-function.

**Server Software (please complete the following information):**
Official Docker-Compose-image

**Client Device (please complete the following information):**
 - PC
 - Arch Linux
 - Network: Remote over WAN behind a hardware-firewall with reverse proxy for MeshCentral
 - Browser: Firefox

**Remote Device (please complete the following information):**
 - Device: iMac running Windows
 - Current Core Version (if known): Dec 9 2022, 2450063421

**Comment by si458** [comment]
i cant replicate the issue there and im using firefox too, see my attached video

https://github.com/user-attachments/assets/12a30eb5-f4af-4ee5-94cb-29864f9822f1

can u share a video recording of what happens?

**Comment by si458** [comment]
what version of meshcentral are u using as u didnt state that in the report, just offical docker image,
yet we have one per release and the master image
also what archlinux version and desktop are you using?
and what firefox version?

**Comment by n1smithy** [comment]
Arch is a rolling release. So no particular version. It's updated sind one or two weeks ago.
Firefox: 127.0.2 (64-Bit), build for Arch Linux (official repos)
Docker-Image: ghcr.io/ylianst/meshcentral:**master**
Chromium: Version 126.0.6478.126 (Official Build) Arch Linux (64-Bit)
Gnome: gnome-desktop 1:44.0-1 (Gnome-Version 46)
Kernel: Linux 6.9.8-arch1-1

**Comment by si458** [comment]
Thanks I'll have a look tomorrow :)

**Comment by n1smithy** [comment]
I have to thank you. :-)

**Comment by si458** [comment]
is this still an issue as i cannot replicate the bug?

**Comment by n1smithy** [comment]
Yes, still exists, but there is a workaround.

**Comment by si458** [comment]
just going to have alook at this again, what arch version are you using now also browser version?
i just noticed in your video, the is an extra icon next to the bar?
whats that icon? as its not visible at all on any other OS/browser?
might be something archlinux related?

**Comment by si458** [comment]
ok i can replicate the bug after taking about 3 hours to install arch linux! (why didnt they create a simple setup script!)
but also i can replicate the bug in firefox on mac!
the bug only happens when you are connected already to a device.
it will then only extend upto the right side of the image and no more
i believe this is how its intended tho so more testing will need to be done

**Comment by si458** [comment]
ok should now be fixed!
patch yourself from this commit https://github.com/Ylianst/MeshCentral/commit/5ff44bbae810e9194765998865440252377190ad
OR wait 15mins and try the new latest `docker` image (remember to pull!)

**Comment by si458** [comment]
just been playing around with moving the image to the side
but i dont think its going to work because you only have a little more extra room :(

https://github.com/user-attachments/assets/80e7adba-0fc2-4e49-8cce-0de399a48d1f

**Comment by n1smithy** [comment]
Updated docker and it works fine now. Thanks a lot!

**Comment by si458** [comment]
@n1smithy glad it works!
Don't forget to donate to keep me active ♥️
https://www.si458.co.uk/2024/01/05/donation/
