### ISSUE TITLE
Broken upgrade using Windows Installer

### ISSUE THREAD

**Issue by plwc** [Ylianst/MeshCentral#626]
I was upgrading from 0.4.1-n (I think) to 0.4.3-s and during the upgrade it displayed some npm errors with something about babel then on the final screen it said the upgrade had failed. I tried running it again but it said the latest version was already installed so I tried a re-install which failed with the same errors.

I installed a later version of node and tried again. I didn't see the original errors but at the end I get:

Exception Error
System.IO.IOException: The file C:\Program Files\Open Source\MeshCentral\winservice\winservice.js already exists.
at System.IO.__Error.WinIOError(Int32 errorCode. String maybeFullPath)
at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite. Boolean checkHost)
at MeshCentralInstaller.MainForm.performInstallation.3()
at MeshCentralInstaller.MainForm.performinstallation()

**Comment by Ylianst** [comment]
Weird.

Option 1. When you login as administrator, you can go to "My Server" tab, click "check for update" and update there if possible. This is the easiest.

Option 2. Stop the MeshCentral service, rename the "C:\Program Files\Open Source\MeshCentral\winservice" folder to "C:\Program Files\Open Source\MeshCentral\winservicex" (rename to any other name) and update again using the Installer. The "winservice" folder will automatically created again. Once it works, delete the "winservicex" folder.

Option 3. Stop the service. Open the command prompt in administrator mode and go to "C:\Program Files\Open Source\MeshCentral". Then, type "npm install meshcentral". When done, start the service again.

Let me know how that goes.

**Comment by plwc** [comment]
The upgrade broke the server completely. Also previous attempts at updating via the web interface had failed, I thought this wasn't possible on Windows?

I ended up rolling back to the snapshot I took before upgrading, updating node first then running the update again and it worked.

**Comment by plwc** [comment]
Closing because I don't think this is an issue anymore.
