### ISSUE TITLE
Language Selector not showing up with "showPasswordLogin" "false"

### ISSUE THREAD

**Issue by m4zl** [Ylianst/MeshCentral#6269]
**Describe the bug**

**To Reproduce**
1. Go to 'Login Page'
2. See error

**Expected behavior**

- With showPasswordLogin = "false" and only SAML login enabled it should still give me the option to select the right language.

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "xxx",
    "WANonly": true,
    "port": 443,
    "aliasPort": 443,
    "agentAliasDNS": "xxx",
    "redirPort": 80,
   "npmproxy": "http://xxx",
   "mongodb": "mongodb://127.0.0.1:27017/meshcentral",
   "mongodbcol": "meshcentral",
   allowHighQualityDesktop": true,
    "autoBackup": {
      "mongoDumpPath": "c:\\Program Files\\MongoDB\\Tools\\100\\bin\\mongodump.exe"
    }
  },
  "domains": {
    "": {
      "title": "xxx",
      "title2": "meshcentral",
	  "titlePicture": "xxx",
	  "loginPicture": "xxx",
	  "welcomePicture": "xxx",
      "minify": true,
      "newAccounts": false,
	  "authStrategies": {
		"saml": {
		"callbackurl": "https://xxx/auth-saml-callback",
		"newAccounts": true,
		"entityid": "xxx",
		"idpurl": "https://xxx",
		"cert": "xxx"
		}
	  },
	  "showLanguageSelect": { 
		"type": "string", 
		"default": "top", 
		"description": "Show Language Selector on Login Page, \"top\" inside Login Box or \"bottom\" at Bottom of Page", 
		"enum": [ null, "top", "bottom" ] },
	  "showPasswordLogin": false,
      "userNameIsEmail": true,
	  "ssh": true,
	  "mstsc": false,
      "_auth": "ldap",
	  "newAccountsRights": [ "nonewgroups", "notools" ],	  
      "myServer": {
        "Backup": true,
        "Restore": true,
        "Upgrade": true,
        "ErrorLog": true,
        "Console": true,
        "Trace": true,
        "Config": true
      },
      "agentCustomization": {
        "_displayName": "xxx",
        "_description": "xxx",
        "_companyName": "xxx",
        "_serviceName": "xxx",
        "image": "xxx",
        "_fileName": "xxx"
      }	  
    }
  }
}
```

**Comment by si458** [comment]
you config is incorrect,
you have just copied the schema file which only just shows you information and is used with visual studio code!
`showLanguageSelect` should be either `top` or `bottom`
but if you specify `top` and use `showPasswordLogin: true` then the language selector will be hidden because the password login is hidden, so its best to use `bottom` for the `showLanguageSelect` and it will show at the bottom instead

**Comment by m4zl** [comment]
> you config is incorrect
> 
> you have just copied information from the schema file and the schema file is meant to be used with visual studio code!
> 
> `showLanguageSelect` should be either `top` or `bottom`
> 
> but if you specify `top` and use `showPasswordLogin: true` then the language selector will be hidden because the password login is hidden,
> 
> so its best to use `bottom` for the `showLanguageSelect` and it will show at the bottom instead

What is incorrect with my config? Everything else is working fine. We just dont use the  `showPasswordLogin: true` as we dont want the manual login. We just use Cisco Duo as the provider and use saml here. That is working correct. Even if i specify `showLanguageSelect` with the `bottom` option - it wont show the language selector.

**Comment by si458** [comment]
you config.json you have listed above
you have specified the schema file rather than just the values (cut your config.json short to explain)
```
{
  "domains": {
    "": {
      "title": "xxx",
      "showLanguageSelect": { 
		"type": "string", 
		"default": "top", 
		"description": "Show Language Selector on Login Page, \"top\" inside Login Box or \"bottom\" at Bottom of Page", 
		"enum": [ null, "top", "bottom" ]
      },
      "showPasswordLogin": false,
      "userNameIsEmail": true,
      "ssh": true
    }
}
```
it should be 
```
{
  "domains": {
    "": {
      "title": "xxx",
      "showLanguageSelect": "bottom",
      "showPasswordLogin": false,
      "userNameIsEmail": true,
      "ssh": true
    }
}

**Comment by m4zl** [comment]
Well, yes you are totally right! I just did not think about it and straight copied it from the schema file. My mistake. Now it is working of course. 

Though a quick question. The language selection wont transfer to the user and is just for the starting screen - right? At least that is what I am seeing here.

Thanks for the quick help.

**Comment by si458** [comment]
By default, it will default to the users' browser language

but if the user changes the language on the login page, it will refresh the login page in that language

then, when they log in, it will use that language for the user.

**Comment by m4zl** [comment]
Yes the default is clear for me. I just right now tested the language selection and used "nl" for it. It refreshed the login paged and showed up correctly. After login with SAML it still showed up in my browsers language after redirection and login.

**Comment by si458** [comment]
> Yes the default is clear for me. I just right now tested the language selection and used "nl" for it. It refreshed the login paged and showed up correctly. After login with SAML it still showed up in my browsers language after redirection and login.

oh FFS! i think i know the issue, because your using an external auth like saml, then its not passing the language value through, so need to fix that,
thank for reporting tho!

one way around for moment
is if you go into the My Account tab, then click `Localization Settings` and set your prefered language.
this is then saved server side (make sure you have 1.1.25 installed as this was fixed about a week ago)
then when you next login, it will auto load that language

**Comment by si458** [comment]
side note: just fixed a bug with the events log showing the incorrect event for changing of your language haha https://github.com/Ylianst/MeshCentral/commit/df6474802d2dd7647cc20957258b8a094bddc05e

**Comment by m4zl** [comment]
> > Yes the default is clear for me. I just right now tested the language selection and used "nl" for it. It refreshed the login paged and showed up correctly. After login with SAML it still showed up in my browsers language after redirection and login.
> 
> oh FFS! i think i know the issue, because your using an external auth like saml, then its not passing the language value through, so need to fix that, thank for reporting tho!
> 
> one way around for moment is if you go into the My Account tab, then click `Localization Settings` and set your prefered language. this is then saved server side (make sure you have 1.1.25 installed as this was fixed about a week ago) then when you next login, it will auto load that language

Thanks for clearing that up! Yeah I already thought about it might not working because of saml. So everything else is now clear for me. Haha just came from my own issue with the config file to a "real" issue with saml + language selection from login page.
