### ISSUE TITLE
Windows Button gets stuck on client

### ISSUE THREAD

**Issue by routerino** [Ylianst/MeshCentral#627]
Issue:
When you click the windows button in the browser, it also clicks the windows button on the client (which is intended). However, because the windows key is a protected key, it then defocuses the browser and the release never gets registered. This causes issues when trying to perform future commands because the client still thinks the windows button is being held down.

Is it possible for the client to auto-release the windows key when it detects the keystroke?

**Comment by MailYouLater** [comment]
You mean when you press the Windows key on the keyboard, right?

**Comment by routerino** [comment]
> 
> 
> You mean when you press the Windows key on the keyboard, right?
> 
> Edit: I'm actually not experiencing this in the latest version. @routerino: What version of MeshCentral are you running? This may have been fixed along with the similar issue with Alt, Ctrl & Shift keys in #330, if not, it's at least similar.

I swear I've experienced this consistently just recently, but I've just gone to recreate the issue and it seems to behave fine.

I'll close for now, I'll reopen if I can consistently recreate the issue on the latest version.
