### ISSUE TITLE
Browsing from mobile browser , on Linux clients , terminal connection does not respect domains config.json linuxshell:login

### ISSUE THREAD

**Issue by b1be** [Ylianst/MeshCentral#6275]
**Describe the bug**
Browsing from mobile browser , on Linux clients , terminal connection does not respect **domains** config.json linuxshell:login

     "terminal": {
       "linuxshell": "login"
     },

always logs in as root.

from desktop browser, it's working as expected.

**To Reproduce**
1. Go to any Linux terminal client
2. Click on terminal / connect
3. See error (connection) - when browsing on mobile / desktop

**Expected behavior**
prompt for login shell, not auto login to root

**Server Software (please complete the following information):**
 - OS: Raspberry (diet-pi)
 - Virtualization: Docker compose / portainer

**Client Device (please complete the following information):**
 - Device: Mobile (Android)
  - Browser: Any

**Remote Device (please complete the following information):**
 - Device: Vps, Raspberry, Dreambox One (stb)
 - OS: Debian x64 / arm64
 - Current Core Version Nov 21 2022, 2807693000

**Your config.json file**
```
  "domains": {
        "": {
        "title": "[redacted]",
        "agentCustomization": {
        "displayName": "[redacted]",
        "description": "[redacted] agent for remote monitoring, management and assistance.",
        "companyName": "[redacted]",
        "serviceName": "[redacted]agent",
        "foregroundColor": "#FFFFFF",
        "backgroundColor": "#003669",
        "fileName": "[redacted]agent"
      },
      "assistantCustomization": {
        "title": "[redacted]",
        "fileName": "[redacted]"
      },
      "androidCustomization": {
        "title": "[redacted]",
        "subtitle": "[redacted]"
      },
     "terminal": {
       "linuxshell": "login"
     },
    "title2": "[redacted]",
    "_minify": true,
    "NewAccounts": "false",
    "_userNameIsEmail": true,
    "_certUrl": "my.reverse.proxy",
    "certUrl": "https://[redacted]"
        }
```

**Comment by si458** [comment]
I will have a look at this tomorrow if I can

but the schema file says for `linuxshell`
`Indicate what terminal options are available when the user clicks the right mouse button on the terminal connect button.`

So in my eyes this would have no effect on the mobile UI as u can't right click? 

But I am confused how u clicking the connect button on the desktop ui does the `login` prompt?

**Comment by b1be** [comment]
![Screen recording 2024-07-24 00 31 27](https://github.com/user-attachments/assets/d75d8f25-8726-4795-a396-b6b4da953205)

this is normal click on desktop, working as expected, not with rightclick, just plain leftclick

on mobile interface, defaults to root login without password input.

**Comment by si458** [comment]
@b1be oh wow, learn something new every day!
Will have a look 2moz when I get a chance.
Might be a little bug in the mobile ui, and maybe the description in the schema is wrong too!

**Comment by si458** [comment]
ok pushed fixed for you! https://github.com/Ylianst/MeshCentral/commit/10b57dcf9ecce95c31af7896175c23746b2a17c2
code was already in there just commented out,
also the schema file had the wrong discription too, it should read
`Indicates the default linux terminal thats used when the user clicks the terminal connect button and disables the right mouse button on the terminal connect button when this is set`

should be ready for testing in 15mins with docker `master` image or `npm install Ylianst/MeshCentral` develop build
