### ISSUE TITLE
 update the meshcentral server

### ISSUE THREAD

**Issue by EagleDotNet** [Ylianst/MeshCentral#6279]
**Describe the bug**
I try to update the meshcentral server through the control panel, but nothing happens, and through the commands this message appears:

```
61f3d22bc94a:~# npm install meshcentral
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 202 packages in 18s

32 packages are looking for funding
  run `npm fund` for details
61f3d22bc94a:~#
```

**Screenshots**
![image](https://github.com/user-attachments/assets/c53da537-789d-40eb-8f79-6599957bbda7)

**Server Software (please complete the following information):**
 - Docker

**Comment by si458** [comment]
you say you are using docker, so you should update the docker way!
**dont use the web panel!**
instead just change your image in your docker-compose OR run command
to the newer version `ghcr.io/ylianst/meshcentral:1.1.27`

**Comment by EagleDotNet** [comment]
> you say you are using docker, so you should update the docker way! **dont use the web panel!** instead just change your image in your docker-compose OR run command to the newer version `ghcr.io/ylianst/meshcentral:1.1.27`

Thank you very much for the quick response and help, I use it
`ghcr.io/ylianst/meshcentral:latest`
But it seems that this does not happen automatically in Docker and I had to re-pull the image again.
Now I have the latest version, thank you very much again

**Comment by EagleDotNet** [comment]
Will I also need to update the mesh agent on all devices? Or will this be done automatically?

**Comment by si458** [comment]
yes the `latest` is just whatever version was latest at the time!
one way to do it is pull the `latest` image which you will see will be new
then compose down and compose up, or container down/remove then recreate :) 

the is no updates to the meshagent at the moment,
if the is updates to the meshcore.js or modules/*.js then they get pushed themselves automatically 👍

**Comment by EagleDotNet** [comment]
I had two problems previously and I don't know if they are included in these updates

https://github.com/Ylianst/MeshCentralRouter/issues/79#issuecomment-2194823154
https://github.com/Ylianst/MeshCentralRouter/issues/77#event-13231087222

**Comment by si458** [comment]
@EagleDotNet, oh poo knew I forgot something!
I was meant to upload the latest meshcentralrouter in with the updates! 
Not to worry! Will attached zip file here 2moz with the latest version for you :)
