### ISSUE TITLE
Security Issue/DOS

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#628]
Opening this for tracking purposes. I've emailed Ylian and Bryan regarding a security issue. I'd have submitted a pull request with a fix but given that Ylian is traveling I didn't want the diff out there too long before a fix was in place. No user data at stake, just denial of service.

**Comment by Ylianst** [comment]
Published MeshCentral 0.4.3-t with a fix for this. Thank you for reporting it. [Meshcentral.com](https://www.meshcentral.com) has also been patched.

**Comment by ryanblenis** [comment]
Confirmed!

**Comment by MailYouLater** [comment]
When I first saw the title of this issue, I was briefly confused because I thought you were saying there was a security issue when running on DOS.  Upon reading the content, I realized you meant Denial Of Service, not Disk Operating System. 😝
