### ISSUE TITLE
AMT activated in ACM. But CIRA: Disconnected

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [Ylianst/MeshCentral#6281]
**Describe the bug**
Hello,

I'm raising this as a bug as I have this issue on 4 devices and have not been able to determine a resolution. And the discussion questions that I have seen have not been responded to.

This could be a bug, or maybe I just need some troubleshooting advice.

I have other AMT devices (and agents) that are Activated and are connecting fine to the MC server. So the MC server is functional - at least to some degree.

**To Reproduce**
1. Have an Intel AMT only group
2. Intel AMT Policy
3. Simple ACM
4. Keep existing password
5. Deactivate CCM
6. CIRA - Connect to server
7. Deploy setup file using meshcmd
8. AMT device appears in group, but IntelAMT tab is diconnected with no option to connect
9. Run meshcmd amtinfo on device.
10. Intel AMT v12.0.93, activated in Admin Control Mode (ACM).
Wired Enabled, Static, E4:54:E8:92:A7:FB, 10.254.242.100
Connection Status: Direct, CIRA: Disconnected.

**Expected behavior**
Expect CIRA to be connected

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Windows 10 Pro
 - Virtualization: Hyper-V VM
 - Network: WANonly
 - Version: 1.1.24
 - Node: 20.15.0

**Client Device (please complete the following information):**
 - Device: OptiPlex 7070
 - OS: Windows 10 Pro
 - Network: [Remote over WAN]
 - Browser: [N/A]
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows 10 21H2]
 - Network: [e.g. Local to Meshcentral, Remote over WAN]
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mc1.zen.net.au",
    "WANonly": true,
	"_LANonly": true,
    "sessionKey": "### have changed ###",
    "_port": 443,
    "aliasPort": 5443,
	"MpsAliasPort": 54433,
    "_redirPort": 80,
    "_redirAliasPort": 80,	
	"mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
	"autoBackup": {
	"mongoDumpPath": "C:/Program Files/MongoDB/Server/7.0/bin/mongodump.exe",
	"backupIntervalHours": 24,
	"keepLastDaysBackup": 10,
	"zipPassword": "#### have changed ####",
	"backupPath": "C:/MeshCentral/meshcentral-backups",
	"maxFiles": 10
	}
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "info@zen.net.au",
    "names": "mc1.zen.net.au",
    "skipChallengeVerification": true,
    "production": false
  }
}
```

**Comment by si458** [comment]
you say `Keep existing password`, 
in the General tab of the device, is the an option saying `invalid credentials` next to the AMT bit at all?
share screenshot of you can?

**Comment by si458** [comment]
people keep reporting this type of issue and sadly i havent been able to replicate the issue?
BUT i only have a single AMT v7 device which works no matter what,
so without hardware to test, i cannot fix the bug (if it is a bug).

a few things you can try:

1. go into the console tab under `My Server` then type `amtpasswords`
then check the device thats listed in there AND the password for the AMT (mebx) is infact in that list.

2. check you can access the AMT web panel on the device itself `https://localhost:16992` or `https://localhost:16993`

3. if you can access the web ui, check you can login with a password listed in `amtpasswords` for that device

4. run meshcentral with amt debug `node node_modules/meshcentral --debug amt`

**Comment by ZENAdmin-Ops** [comment]
Hello,

Have I done the amtpasswords step correctly?
<img width="297" alt="Console_amtpasswords" src="https://github.com/user-attachments/assets/dde2abd6-3970-4375-84b4-332ef10ec9f2">

**Comment by si458** [comment]
@ZENAdmin-Ops erm yes and im not sure why its blank?

**Comment by ZENAdmin-Ops** [comment]
Nothing else has appeared in the console

**Comment by si458** [comment]
@ZENAdmin-Ops can you just try all the other options for me tho please

**Comment by ZENAdmin-Ops** [comment]
I am able to logon to the device using https://localhost:16993

But there are no passwords listed in amtpasswords so I am using the credentials that I know are correct for the device

**Comment by ZENAdmin-Ops** [comment]
For step 4.

Where will the logs / diagnostic info be reported that I will need to submit?

**Comment by si458** [comment]
@ZENAdmin-Ops sorry first stop meshcentral, then rerun it with that command, the logs will show on the screen

you can also go into the web ui, then my server, then trace, click tracing, then enable ALL the intel amt sections,
then it will show any debug stuff in the web ui (dont close the page!)

if you use the web ui, its best to shut down computer, unplug its power, wait say 2 mins, then plug its power back in, switch computer on, then watch the web ui output

if you get no output in either the console or the trace ui, then you might have the amt port 4433 blocked in your firewall

**Comment by ZENAdmin-Ops** [comment]
OK. These systems are going to be in use this evening.

So I will try the tracing tomorrow and report back then.

Ironically I had access to AMT via VNC Plus prior to trying to switch them to MeshCentral. And at the moment AMT access via MeshCentral for these devices is broken.

So, I can't do the remote restart and wait 2 mins.

I'll just try a remote restart tomorrow. Worst case I'll have to go to the office to perform a power-drain, that will be sometime in the next week.

I'd really like to get to the bottom of this. So I'll do whatever testing is needed.

Appreciate your prompt assistance.

**Comment by si458** [comment]
thats ok! in theory you can do the web ui trace now if you wanted while its running, 

go into the web ui, then my server, then trace, click tracing, then enable ALL the intel amt sections,
then it will show any debug stuff in the web ui (dont close the page!)

then watch the logs as you try different things and see what happens,

but what you need to do is really unplug/plug the remove device, that will restart AMT into connecting to your machine,
but if you NEVER see any connections from that device happen when you power cycle it, then something isnt right with the AMT

strange one (side note), can you use the meshcommander application and connect into the device?
if you can then you can check the internet settings tab and see if your meshcentral server dns is listed there,
same with the security settings, check its certificate is listed there

**Comment by ZENAdmin-Ops** [comment]
The server trace doesn't appear to identify the host.

And I have AMT devices that are working as well as 3 or 4 that are stuffed.
<img width="470" alt="Server_Trace" src="https://github.com/user-attachments/assets/01337218-f890-405b-846e-eaaa58ced95b">

**Comment by ZENAdmin-Ops** [comment]
Internet Settings looks correct

I'm using a redirected port.

Can you tell me where I check the Trusted Root certificate?
![Uploading MeshCommader_Internet_Settings.png…]()

**Comment by si458** [comment]
plz can you share a few more screenshots? just trying to compare with mine
System Status, Network Settings, Internet Settings, Security Settings ?

**Comment by si458** [comment]
ive just spotted, it says talking to port 54433, which you have set as your alias port for amt
do you use a reverse proxy server at all?
as the default port should be 4433, and the alias port only tells remote device which port to connect to,
but you havent specified an amt port so its going to use the default 4433 port

**Comment by ZENAdmin-Ops** [comment]
> plz can you share a few more screenshots? just trying to compare with mine System Status, Network Settings, Internet Settings, Security Settings ?

<img width="231" alt="MeshCommander_Network_Settings" src="https://github.com/user-attachments/assets/3e5382e1-f44e-4caf-9068-6f39b8f851f0">
<img width="351" alt="MeshCommander_System_Status" src="https://github.com/user-attachments/assets/604fb246-5abf-4219-b5cf-a420160c7454">
<img width="208" alt="MeshCommander_Security_Settings" src="https://github.com/user-attachments/assets/23824820-c2f5-4705-bea6-545bbd063865">

**Comment by si458** [comment]
the dns suffix for the computer in incorrect!
from my understanding and knowledge, the dns suffix MUST match your meshcentral dns name!?
so you should be able to click the name & domain in network settings, and change the dns suffix

**Comment by ZENAdmin-Ops** [comment]
> ive just spotted, it says talk to port 54433, which you have set as your alias port for amt do you use a reverse proxy server at all? 

No reverse proxy server.

> as the default port should be 4433, and the alias port only tells remote device which port to connect to, but you havent specified an amt port so its going to use the default 4433 port so 54433 != 4433

I don't understand the comment above.

The public AMT port is 54433 which forwards to 4433 on the MeshCentral server.

**Comment by si458** [comment]
> The public AMT port is 54433 which forwards to 4433 on the MeshCentral server.

ah right ok thats fine! so port forwarding 54433 to 4433, thats ok makes sense! my mistake!

**Comment by ZENAdmin-Ops** [comment]
> the dns suffix for the computer in incorrect! from my understanding and knowledge, the dns suffix MUST match your meshcentral dns name!? so you should be able to click the name & domain in network settings, and change the dns suffix

Well I have devices at other client sites that working in MeshCentral and their domain suffix does not match our dns suffix

If all the devices have to match MeshCentral dns suffix that will be a showstopper for us. We will need a work-around

**Comment by si458** [comment]
hmm ok that is weird? and forgive me but i could be mistaken!

in theory you can click the `name & domain`, then change `name sharing` to `dedicated, different from os`,
then set a computer name and your meshcentral dns name in there (`computer1.meshcentral.myserver.com`)
and then click OK/Save, it then WONT effect your windows OS domain as its seperate :)

**Comment by ZENAdmin-Ops** [comment]
> hmm ok that is weird? and forgive me but i could be mistaken!
> 
> in theory you can click the `name & domain`, then change `name sharing` to `dedicated, different from os`, then set a computer name and your meshcentral dns name in there (`computer1.meshcentral.myserver.com`) and then click OK/Save, it then WONT effect your windows OS domain as its seperate :)

So you would suggest that the name should be: bbox4.zen.net.au ?

**Comment by si458** [comment]
> So you would suggest that the name should be: bbox4.zen.net.au ?

no it would need to match the DNS name you use to access meshcentral,
so from the screenshots/config.json something like `comp1.mc1.zen.net.au`

**Comment by ZENAdmin-Ops** [comment]
I've just changed the name to:

bbox4.mc1.zen.net.au

No change in amtinfo
CIRA: Disconnected

Do I need to restart?

**Comment by si458** [comment]
@ZENAdmin-Ops possibly the remote machine yes,
by unplugging/plugging back in,
but maybe just give it chance to connect, as i do know/have seen my AMT can take 5-10mins before it connects back

**Comment by si458** [comment]
@ZENAdmin-Ops what is the output now is you run the `amtinfo` with meshcmd?

**Comment by ZENAdmin-Ops** [comment]
> @ZENAdmin-Ops what is the full output now if you run the `amtinfo` with meshcmd?

I have restarted

C:\ZEN\MeshCentral\ZEN>meshcmd amtinfo
Intel AMT v12.0.93, activated in Admin Control Mode (ACM).
Wired Enabled, Static, E4:54:E8:92:A7:FB, 10.254.242.100
Connection Status: Direct, CIRA: Disconnected.

**Comment by si458** [comment]
ok i am confused because its missing a section which should show the dns suffix?
but at the same time the `amtinfo` command has NEVER worked on my V7 due to a bug
i will try fix my bug here next week, and then have a look at whats going on if i can
im sorry i cant be of much more help, i will ask @Ylianst when i get chance, see if he has any suggestions
as we must be missing something!

**Comment by ZENAdmin-Ops** [comment]
This is from a system that is working.

Later version of AMT.

C:\ZEN\MeshCentral>meshcmd amtinfo
Intel AMT v16.1.30, activated in Admin Control Mode (ACM).
Wired Enabled, DHCP, CC:96:E5:37:4A:7F
DNS suffix: alleanza.local
Connection Status: Outside, CIRA: Connected to mc1.zen.net.au, Periodic.

What determines Connection Status: Outside versus Direct?

**Comment by ZENAdmin-Ops** [comment]
Actually that demonstrates (at least in that instance) that the DNS suffix doesn't need to match the MeshCentral server.

**Comment by si458** [comment]
ok so the dns suffix isnt the problem! thats ok! im still learning all the AMT bits n bob so my mistake!
AMT seems to be registering as `direct` and thinks it has direct access to your meshcentral server rather than registering as OUTSIDE the network and needs to use CIRA.
so are both of the AMT machines (v12 and v16) on the same network OR different networks with like different DNS servers?
one other thing to check is use meshcommander again, go into `Internet Settings` and click `Environment detection` and see what DNS names are listed in the pop up, it should list a RANDOM name

**Comment by ZENAdmin-Ops** [comment]
These systems are on completely different networks.

But the AMT systems that aren't working are all registered as Direct.

So that could be the issue here.

**Comment by si458** [comment]
one other thing to check is use meshcommander again,
go into `Internet Settings` and click `Environment detection` and see what DNS names are listed in the pop up,
it should ONLY list a RANDOM name, is this the case? (screenshot hehe)

**Comment by ZENAdmin-Ops** [comment]
> one other thing to check is use meshcommander again, go into `Internet Settings` and click `Environment detection` and see what DNS names are listed in the pop up, it should ONLY list a RANDOM name, is this the case? (screenshot hehe)

<img width="178" alt="Environment_Detection" src="https://github.com/user-attachments/assets/dcb9de4a-55fd-4bfa-841a-6cdcecbaca1f">

**Comment by si458** [comment]
so the is defo something wrong with the AMT then?
are the IP addresses assigned to the DNS name different from the working ones and non-working ones?
(like internal ip VS external ip?)

**Comment by ZENAdmin-Ops** [comment]
The systems that aren't working.

Are at the same physical site (not the same subnet) as the MeshCentral server.

But they're accessing the MeshCentral server via the same router (so the same network path) as the Outside host.

So, from my perspective they should consider the MeshCentral server to be outside. But perhaps the AMT / MeshCentral logic is "smart enough" to tell the difference.

If that is the case, I'd like to understand the logic, so that I can make it so that these AMT systems will see the MeshCentral server as 'Outside' and not 'Direct'.

**Comment by ZENAdmin-Ops** [comment]
> so the is defo something wrong with the AMT then? are the IP addresses assigned to the DNS name different from the working ones and non-working ones? (like internal ip VS external ip?)

The internal IP's are completely different subnets.

The external IP could be the problem here.

With the Outside systems, they are at a different location so the Public IP address is different.

With the Direct systems, they are at the same site, and the Public IP address is the same.

But in both cases, the same firewall rules are used. So it is the same FQDN:port which then forwards to the same internal IP/ port.

**Comment by si458** [comment]
@ZENAdmin-Ops in theory the `logic` is already set,
you shared the screenshot for `Environment detection` and if you read it, IF the local dns suffix is the same as those listed in the list then it conciders the AMT as LOCAL/DIRECT BUT if they arent the same, its concidered AWAY/OUTSIDE

but for some reason the AMT seems to think it has DIRECT access to your meshcentral server which doesnt make sense? 

one thing you can try is REMOVE/UNCOMMENT `WANonly` from your config.json,
restart meshcentral, let it enter into hybrid mode,
see if the devices suddenly connect!
if they do, the machines seem to think they can talk directly to meshcentral without CIRA support

**Comment by ZENAdmin-Ops** [comment]
> one thing you can try is REMOVE/UNCOMMENT `WANonly` from your config.json, restart meshcentral, let it enter into hybrid mode, see if the devices suddenly connect! if they do, the machines seem to think they can talk directly to meshcentral without CIRA support

Genius.

Two of the systems are now connected!

**Comment by ZENAdmin-Ops** [comment]
But no change to amtinfo

This is from a system now online and working in MeshCentral

C:\ZEN\MeshCentral\ZEN>meshcmd amtinfo
Intel AMT v12.0.93, activated in Admin Control Mode (ACM).
Wired Enabled, Static, E4:54:E8:92:A7:FB, 10.254.242.100
Connection Status: Direct, CIRA: Disconnected.

**Comment by si458** [comment]
@ZENAdmin-Ops glad its almost sorted but wow that is weird !?
it must be the machines are seeing the meshcentral server as LAN rather than WAN for some reason?
AMT is very confusing to understand BUT an amazing technology/idea!

im assuming the amtinfo hasnt changed BECAUSE those machines that arent working can talk directly to meshcentral rather than using the CIRA, only thing i can think off!

i will dig into the meshcmd tho when i get chance as i said before i have a BUG which means it doesnt work on mine at all.

**Comment by ZENAdmin-Ops** [comment]
There are also still two systems whose status hasn't changed, and I can't think what to do to them to get them to connect.

Other than deleting them out of MeshCentral and re-running meshcmd amtconfig

I think there is a bug here.

**Comment by si458** [comment]
> There are also still two systems whose status hasn't changed, and I can't think what to do to them to get them to connect.
> 
> Other than deleting them out of MeshCentral and re-running meshcmd amtconfig
> 
> I think there is a bug here.

i would say WAT about 10-15mins see if they connect themselves, if they dont
then UNPROVISION them using the meshcmd or the mebx,
then reconfig them and see what happens

its all trial and error now!

**Comment by ZENAdmin-Ops** [comment]
When you say UNPROVISION using meshcmd.

Which command?

I used AmtAcmDeactivate on one system and completely lost control of AMT.

I had to go to site to access MEBX directly.

**Comment by si458** [comment]
yes that command! `AmtAcmDeactivate` its very dangerous as it unprovisions the AMT,
it basically removed all certs, details, etc and resets to default the AMT (not the password tho)

**Comment by ZENAdmin-Ops** [comment]
Unprovision is a shitter.

That cannot be done remotely.

**Comment by ZENAdmin-Ops** [comment]
Hello,

As I expected the two unconnected hosts have not connected.

I'd like to try options to tweak the AMT settings to switch the connection from Direct to CIRA.

All the AMT systems that are connecting via CIRA are working smoothly.

When you next are able to speak with @Ylianst if you could ask what options I might be able to try here to get these AMT's to switch to CIRA.

That would be great.

**Comment by ZENAdmin-Ops** [comment]
Hello,

I'm returning to this issue.

A recap. I have computers at 3 sites connected to MeshCentral. Both meshagents and AMT.

MeshAgents work at all 3 sites.

AMT agents only connect from 2 sites.

The 3rd site, the "problem" site. Had the MeshCentral server.

So the troubleshooting above assumed that the issue with the AMT endpoints at the 3rd site was somehow related to the AMT endpoints being "local" to the MeshCentral server.

I have setup a MeshCentral server at another location and performed a backup and restore of the MeshCentral server to that location.

The behaviour is as before.

All the MeshAgents connect.

The AMT agents at two sites connect, but not the 3rd site.

So I want to resuming troubleshooting the AMT endpoints at the 3rd site.

I had deleted the AMT endpoints from the 3rd site in MeshCentral. The endpoints appear in MeshCentral, but they always show as offline / disconnected. As per screenshot.

I also 'reset' AMT on these endpoints. 
- meshcmd amtacmdeactivate
- Then reconfigured AMT via MEBX (i.e. entered IP configuration for LAN)

Here is output from attempt to connect to MeshCentral
C:\ZEN\MeshCentral\ZEN>meshcmd amtconfig --url wss://mc1.zen.net.au:5443/apf.ashx --id  --serverhttpshash
(I have hidden some of the info in case it is sensitive) 
Setting up MEI...
Starting Intel AMT configuration...
Started APF tunnel...
Checking Intel AMT state...
Intel AMT connected.
Performing Commit...
Enabled TLS, holding 10 seconds...
Intel AMT connected.
Added server root certificate.
Created new MPS server.
Created new MPS policy.
Environment detection set.
Enabled redirection features.
Enabled KVM.
Fetching hardware inventory.
Done.

C:\ZEN\MeshCentral\ZEN>meshcmd amtinfo
Intel AMT v12.0.94, activated in Admin Control Mode (ACM).
Wired Enabled, Static, E4:54:E8:92:A7:FB, 10.254.242.100
Connection Status: Direct, CIRA: Disconnected.

This meshcmd amtconfig results in the endpoint appearing in MeshCentral as per the screenshot. But the endpoints are offline and cannot be connected to.

The issue from my perspective here. Is that the "working" AMT endpoints report:
Connection Status: Outside rather than Direct

See example below.

C:\ZEN\MeshCentral>meshcmd amtinfo
Intel AMT v16.1.30, activated in Admin Control Mode (ACM).
Wired Enabled, DHCP, CC:96:E5:37:4A:7F
DNS suffix: alleanza.local
Connection Status: Outside, CIRA: Connected to mc1.zen.net.au, Periodic.

The Connection Status of 'Outside' versus 'Direct' is what led to me thinking that the MeshCentral server being "local" was the issue. However the MeshCentral server is no longer "local" and the behaviour of the AMT agent is unchanged.

Diagnostics
go into the console tab under My Server then type amtpasswords
then check the device thats listed in there AND the password for the AMT (mebx) is infact in that list.

> Nothing appears. Refer screenshot.
<img width="202" alt="amtpasswords" src="https://github.com/user-attachments/assets/18de93ac-2f53-4267-a161-c78ccc231d9f">

check you can access the AMT web panel on the device itself https://localhost:16992 or https://localhost:16993

if you can access the web ui, check you can login with a password listed in amtpasswords for that device

Refer screenshots
<img width="501" alt="AMT_local_endpoint_System_Status" src="https://github.com/user-attachments/assets/26cd68f5-0a7b-45d9-90a7-ac00ead2f49f">
<img width="551" alt="AMT_local_endpoint_Network_Settings" src="https://github.com/user-attachments/assets/7702dcb0-cf3d-4358-8ee1-e307f7d85831">

run meshcentral with amt debug node node_modules/meshcentral --debug amt

The AMT agents that are connecting appear in the console log. The AMT agents that are not connecting (e.g. BBOX4) do not appear in the console log.

<img width="535" alt="AMT endpoints - 3rd site" src="https://github.com/user-attachments/assets/5329507b-89ac-4fe8-89b6-fc1a67f865a0">

**Comment by ZENAdmin-Ops** [comment]
Hello,

Can you advise with amtinfo the difference between Connection Status:

Direct
Outside

**Comment by si458** [comment]
so i just wanted to update this issue for others in the future

**YOU CANT USE A STATIC IP IN INTEL AMT IF YOU ARE USING CIRA**

its not actually CIRAs fault, its actually a feature called `Environment Detection`
this feature detects if your device is at home (connected directly to your meshcentral server) 
OR
the device is remote (offsite away from meshcentral)

its just silly Intel didnt think `hey a user might put a device in a remote location with a static ip address`

links i discovered:

**The Remote Access feature requires that Environment Detection is configured**
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/remoteaccess.htm

**Environment detection does not take place when Intel AMT is configured for Static IP mode**
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/detaileddescription17.htm

**Comment by danielrobbins** [comment]
Wow. Wow. Wow. I suggest you put a large, prominent notice in the very early sections of the MeshCentral User Guide to make sure that users are aware of this limitation. It makes vPro/CIRA totally useless for many edge setups (particularly gateways.) I wasted an entire day because this information was not clearly documented. It's a significant failing of the User Guide that this is not documented clearly and prominently. 99.9999% of MeshCentral users are using CIRA with Intel. This is very important information to document. It doesn't really matter if the CIRA spec technically allows static IP addressing since all devices have a "feature" that disables this.

**Comment by Dritchie3** [comment]
I'm experiencing the same issue and would like to add my data in case it helps narrow down the cause.

## Hardware
- HP EliteDesk 800 G6 SFF
- Intel Core i5-10500
- AMT v14.1.79 (build 2540)
- BIOS: HP S01 Ver. 02.25.00 (latest available, dated 2026-01-08)
- Intel I219-LM AMT NIC

## Server
- Proxmox VE 9.1.1, MeshCentral v1.1.58 in LXC, WAN mode
- Exposed via DuckDNS to public IP, Let's Encrypt cert on 443 (external 8443 due to Deco router hijacking 443)
- MPS port 4433 forwarded correctly, MeshCentralRoot CA in AMT trust store

## Symptom
- `meshcmd amtinfo` shows: `Connection Status: Direct, CIRA: Disconnected`
- `meshcmd amtconfig` completes successfully ("Intel AMT connected with TLS. Done.")
- AMT device appears in MeshCentral UI as "Disconnected" with grayed-out Connect button
- The Intel AMT event log shows ZERO CIRA-related entries — only BIOS boot events
- AMT audit log shows no "Remote Access Policy Set" or "Remote Access Connection Initiated" entries
- AMT is genuinely not even attempting CIRA outbound

## Verified Working
- DNS: `homeamt.duckdns.org` resolves to correct public IP from both LAN and Internet
- Port 4433 reachable from outside (confirmed with `nc -zv`)
- Hairpin NAT works (confirmed via `curl` from LAN to public hostname)
- MPS cert SHA256 hash matches what's configured in AMT exactly
- `MeshCentralRoot-0e827b` confirmed in AMT trust store via MeshCommander
- Environment detection set to unresolvable `notreal.invalid`
- MPS server entry in AMT: `homeamt.duckdns.org:4433`
- Remote Access Policy: Periodic trigger, 10-second interval, TunnelLifetime 0
- AMT provisioning state: Activated, Admin Control Mode (ACM)
- Power policy: Desktop ON in S0, ME Wake in S3, S4-5

## What I've Tried
- Cold boots (full power-off 30s)
- Switched between static IP and DHCP
- Cleared and re-set environment detection domains
- Deleted and recreated MPS configuration
- Replaced MPS cert with MeshCentralRoot-signed cert
- Group policy switched between CCM and ACM with CIRA setup enabled
- Multiple full `amtconfig` runs

## What I Haven't Tried (firmware-level)
- HP BIOS reflash (current version already latest)
- Full AMT unprovision + reprovision via USB key

`amtconfig` output is always:

The "Done" lies — no MPS server is created/updated and no CIRA attempts follow. AMT just sits in Direct/Disconnected forever despite having a valid CIRA policy configured.

Happy to provide additional logs (mpsdebug output, full amtsavestate dump, MeshCommander screenshots) if useful.

**Comment by si458** [comment]
@Dritchie3 it's telling u it won't use cira because meshcentral is talking directly to the machine via AMT `Connection Status: Direct`

Also CIRA doesn't work with static ip addresses set within meshcommander, the machine MUST use DHCP and get an ip address (amt limitation)

What do u have the meshgroup setup as for the AMT? (Click group name and u see the Intel AMT option)

**Comment by Dritchie3** [comment]
Thanks so much for the quick response — switching to DHCP was a huge step forward! AMT immediately went from "Direct/Disconnected" to "Outside/Connecting to homeamt.duckdns.org, Periodic."

For anyone else hitting this thread, what got me to "Connecting" status:
1. AMT must be on DHCP, not static (as you said)
2. Group policy: Simple Admin Control Mode (ACM) with CIRA setup set to "Connect to server"
3. Environment detection set to an unresolvable domain (notreal.invalid)

CIRA is still not fully establishing though — MeshCentral logs show repeated "MPS:Invalid TLS connection from [public_ip]:[port]" entries with source ports cycling through AMT's listening ports (623, 16992, 16993, 16994, 16995). 

I noticed my MPS cert was only sending the leaf certificate, not the full chain. I appended the MeshCentralRoot cert to mpsserver-cert-public.crt and restarted MeshCentral — the chain now properly includes both certs, and I did see one successful APF byte come through right after the restart. But it went back to "Invalid TLS connection" patterns after that.

Setup details:
- Hardware: HP EliteDesk 800 G6 SFF, AMT v14.1.79
- MeshCentral v1.1.58, WAN mode, behind Deco router with port 4433 forwarded
- External cert hash matches AMT's expected hash exactly
- MeshCentralRoot CA verified in AMT trust store via MeshCommander
- Phone on cellular successfully reaches https://homeamt.duckdns.org:4433 and sees the "MeshCentral2 MPS server" message, confirming the external path works

Any thoughts on what would cause AMT to TLS-handshake successfully one moment and fail the next? Happy to provide mpsdebug logs if helpful.

Thanks again for pointing me in the right direction!

**Comment by Dritchie3** [comment]
Update: I made significant progress and have a more specific question now.

Following your DHCP advice and after fixing the cert chain (mpsserver-cert-public.crt only contained the leaf cert — I appended root-cert-public.crt so it now sends both), I'm seeing real CIRA traffic from my AMT in the mpsdebug logs:

May 14 00:48:25 MeshCentral node[457]: MPS <-- (1):0a
May 14 00:55:19 MeshCentral node[457]: MPS <-- (1):0a

These look like APF KEEPALIVE bytes (0x0A) from AMT. But that's all I get — a single keepalive byte, then silence. No APF SERVICE_REQUEST or USERAUTH_REQUEST follows. AMT shows "Connecting" in amtinfo indefinitely, never "Connected," and the device stays grey in MeshCentral.

It feels like AMT establishes TLS, sends a keepalive, then either:
- AMT expects MeshCentral to respond and doesn't get it, OR
- MeshCentral expects AMT to initiate USERAUTH_REQUEST and doesn't get it

Two questions:
1. Should MeshCentral need a cert chain in mpsserver-cert-public.crt, or should the default single-leaf cert work for AMT?
2. What APF messages should I expect right after the AMT keepalive in a healthy CIRA connection?

Hardware/firmware:
- HP EliteDesk 800 G6, AMT v14.1.79 (latest HP BIOS S01 Ver. 02.25.00)
- TLS 1.2 confirmed working via openssl s_client -tls1_2 (ECDHE-RSA-AES256-GCM-SHA384)

**Comment by Dritchie3** [comment]
Quick update with what I've found from mpsdebug logs:

CIRA *is* establishing successfully through to authentication. Here's a decoded exchange from my logs:

1. AMT (or amtconfig running locally — same protocol path) opens TLS to port 4433 ✓
2. APF SERVICE_REQUEST for "auth@amt.intel.com" → SERVICE_ACCEPT ✓
3. APF USERAUTH_REQUEST with username `kUXtTqOzwp6rRKJJ` (16-char truncated group ID), method "password" → USERAUTH_SUCCESS (0x34) ✓
4. GLOBAL_REQUEST tcpip-forward for ports 0x4260 (16992) and 0x4261 (16993) → both acknowledged ✓
5. MeshCentral opens forwarded-tcpip channel to destination `1.2.3.4:16993` ✓
6. AMT replies with CHANNEL_OPEN_CONFIRMATION ✓
7. ~23 seconds later AMT sends CHANNEL_DATA containing TLS Alert: `15 03 00 00 02 02 50` — level 2 (fatal), description 0x50 (internal_error)
8. Channel closes, MeshCentral retries with next channel ID, same result

So the outer CIRA tunnel works, auth works, but every time MeshCentral tunnels an HTTPS connection through to AMT's internal management service (port 16992/16993), AMT's internal TLS handler responds with a fatal "internal_error" alert and the channel closes. This loops indefinitely and amtconfig never returns.

Keepalives (`d0 000000ff` → `d1 000000ff`) flow correctly every ~60s in between, so the tunnel itself is healthy.

I also noticed:
- MeshCentral was previously only sending the leaf cert on port 4433 (mpsserver-cert-public.crt contained only one certificate). I manually appended root-cert-public.crt so the chain now has both leaf and root. This may or may not be related, but the chain is now properly delivered (verified with `openssl s_client -showcerts`).
- The "Invalid TLS connection from [public_ip]:[port]" entries in my mpsdebug log are from AMT-side source ports (623, 664, 16992-16995) cycling — those appear to be AMT's periodic CIRA retry attempts that fail at TLS handshake before reaching APF.

Any thoughts on what would cause AMT's internal management TLS to throw internal_error when MeshCentral tunnels in? Stale TLS state, a missing cert in AMT's store, something MEBx-level?

Thanks again — happy to provide the full mpsdebug log or amtsavestate dump if useful.

**Comment by Dritchie3** [comment]
Update: I wanted to close the loop on this since you helped me get unstuck.

Your DHCP advice was the key breakthrough — AMT immediately went from "Direct/Disconnected" to "Outside/Connecting" after switching from static to DHCP. Thank you for that.

I'm still working through a secondary issue where AMT's internal TLS service on port 16993 returns a fatal internal_error (0x50) when MeshCentral tries to tunnel through CIRA. I did a partial unprovision via MEBx and re-activated in CCM, which cleared the CIRA config but the TLS state appears to still need regeneration.

I now have MeshCommander working again via HTTP and I'm going to try re-enabling TLS and regenerating the AMT cert from there.

For anyone else hitting similar issues, the key lessons so far:
1. AMT MUST use DHCP for CIRA (static IP prevents CIRA from even attempting)
2. mpsserver-cert-public.crt should contain the full chain (leaf + root), not just the leaf
3. Environment detection must be set to an unresolvable domain to force "Outside" status

Thanks again for your help — I'll update this thread if I get CIRA fully working.

**Comment by si458** [comment]
@Dritchie3 you need to do a full-unprovision, dont use partital as it doesnt wipe everything

also step 3, is automatically done by meshcentral is you have the meshagent installed and the device in a meshgroup with amt setup and configured for CIRA
