### ISSUE TITLE
Banco Itaú

### ISSUE THREAD

**Issue by dasilvasp** [Ylianst/MeshCentral#6282]
Problem:
Here in Brazil, some banks, such as Itaú, do not allow customers to access their bank account via APP if any remote access system is in operation. 

**Describe the solution you want**
It would be interesting if the customer had some visual desktop option to turn the Mesch Agent system on or off, without batching or otherwise. 

**Describe the alternatives you considered**
Maybe open the agent itself via icon and have this option, just create a shortcut on the desktop. (admin users only)

**Additional context**
The option to have tickets that another user has included could be integrated into this icon option.

PT-BR

Problema:
Aqui no Brasil, algubs bancos como Itaú, não deixas o cliente acessar sua conta bancária via APP se qualquer sistema de acesso remoto estiver em funcionamento. 

Seria interessante o cliente ter alguma opção desktop visual para ligar ou desligar o sistema Mesch Agent, sem batches ou outros. 

Talvez abrir o próprio agent via icone e ter essa opção, bastaria criar um atalho no desktop. (usuários admin apenas)

A opção de ter tíckets que outro usuário comentou, poderia estar integrada a essa opção do ícone.

**Comment by dasilvasp** [comment]
Great! Thank you very much!

**Comment by si458** [comment]
Do note tho that antiviruses/security software might still find the software exists on the computer even tho the service isn't running, so case of try and see!

**Comment by dasilvasp** [comment]
Yes, what we have done today is to override the antivirus protection and firewall.

Sim, o que temos feito hoje é colocar em excessões da proteção e do firewall do antivírus.
