### ISSUE TITLE
Can`t change user accaunt image.

### ISSUE THREAD

**Issue by Raito00** [Ylianst/MeshCentral#6291]
Hello!
I can`t add user accaunt picture. Choose picture but OK button still greyed out.

![image](https://github.com/user-attachments/assets/9fa3ee68-b6f4-40af-b545-80dfc551f305)

Meshcental Version 1.1.27

**Comment by si458** [comment]
**you havent followed the bug template report, failure to do so in future will close your issue without assistance**
what web browser are you using?
what OS if the browser running on?
whats the browser version?
can you share your config.json?
do you use `minify: true` and tried turning it off or removing the value?

**Comment by Raito00** [comment]
Sorry!
what web browser are you using?
I try chrome, mozilla
what OS if the browser running on?
Windows 11
whats the browser version?
Latest versions
can you share your config.json?
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "Hidden",
	"MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
	"_mongoDbChangeStream": true,
    "mongoDbBulkOperations": true,
    "WANonly": true,
    "_LANonly": true,
    "sessionKey": "Hidden",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
	"mpsAliasPort": 443,
	"mpsAliasHost": "Hidden",
	"_BrowserPing": 50,
	"BrowserPong": 55,
	"AgentPing": 50,
    "_AgentPong": 110,
    "TLSOffload": false,
	"_IgnoreAgentHashCheck": true,
    "SelfUpdate": false,
    "AllowFraming": "false",
	"manageCrossDomain": [ "user//Hidden" ],
	"TrustedProxy": ["1.1.1.1", "10.10.0.50", "10.10.0.1", "cloudflare"],
    "WebRTC": "true"
  },
  "domains": {
    "": {
	  "title": "Hidden",
	  "_title2": "Servername",
      "_minify": true,
	  "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://Hidden:443/",
	  "_maxDeviceView": 30,
	        "httpHeaders": {
        "Strict-Transport-Security": "max-age=2592000",
        "x-frame-options": "SAMEORIGIN",
		"Referrer-Policy": "no-referrer",
		"X-XSS-Protection": "1; mode=block",
		"X-Content-Type-Options": "nosniff",
		"Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline' *.cloudflareinsights.com; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
      },
	  "agentCustomization": {
        "displayName": "Hidden",
        "description": "Hidden",
        "_companyName": "Hidden",
        "_serviceName": "Hidden",
        "fileName": "Hidden",
		"image": "rd-logo.png",
		"installText": "Hidden",
		"image": "rd-logo.png"
		},
	  "passwordRequirements": {
		"min": 8,
		"max": 128,
		"upper": 1,
		"lower": 1,
		"numeric": 1,
		"nonalpha": 1,
		"_reset": 90,
		"force2factor": true,
		"email2factor": true,
		"_skip2factor": "127.0.0.1,192.168.51.0/24",
		"oldPasswordBan": 5,
		"banCommonPasswords": false,
		"twoFactorTimeout": 300
		},
	  "userConsentFlags": {
        "desktopnotify": true,
        "_terminalnotify": true,
        "filenotify": true,
        "desktopprompt": true,
        "_terminalprompt": true,
        "_fileprompt": true,
        "desktopprivacybar": true
      },
	  "consentMessages": {
        "consentTimeout": 15,
        "autoAcceptOnTimeout": true
      },
	  "desktopPrivacyBarText": "Hidden: {0}"
  },
  "serveris": {
	  "title": "Hidden",
	  "_title2": "Servername",
      "_minify": true,
	  "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://Hidden:443/",
	  "_maxDeviceView": 30,
	        "httpHeaders": {
        "Strict-Transport-Security": "max-age=2592000",
        "x-frame-options": "SAMEORIGIN",
		"Referrer-Policy": "no-referrer",
		"X-XSS-Protection": "1; mode=block",
		"X-Content-Type-Options": "nosniff",
		"Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline' *.cloudflareinsights.com; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
      },
	  "agentCustomization": {
        "displayName": "Hidden",
        "description": "Hidden.",
        "_companyName": "Hidden",
        "_serviceName": "Hidden",
        "fileName": "Hidden",
		"image": "rd-logo.png",
		"installText": "Hidden",
		"image": "rd-logo.png"
		},
	  "passwordRequirements": {
		"min": 8,
		"max": 128,
		"upper": 1,
		"lower": 1,
		"numeric": 1,
		"nonalpha": 1,
		"_reset": 90,
		"force2factor": true,
		"email2factor": true,
		"_skip2factor": "127.0.0.1,192.168.51.0/24",
		"oldPasswordBan": 5,
		"banCommonPasswords": false,
		"twoFactorTimeout": 300
		},
	  "userConsentFlags": {
        "desktopnotify": true,
        "_terminalnotify": true,
        "filenotify": true,
        "_desktopprompt": true,
        "_terminalprompt": true,
        "_fileprompt": true,
        "desktopprivacybar": true
      },
	  "_consentMessages": {
        "_consentTimeout": 15,
        "_autoAcceptOnTimeout": true
      },
	  "desktopPrivacyBarText": "Hidden: {0}"
	  }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
        "production": false
  },
  "smtp": {
    "host": "Hidden",
    "port": 465,
    "from": "Hidden,
    "user": "Hidden",
    "pass": "Hidden",
    "tls": true,
    "_verifyEmail": false
  }
}

do you use minify: true and tried turning it off or removing the value?
no - disabled

P.S.
I try change accaunt image also with mobile phone (Iphone) ... the same problem.

**Comment by Raito00** [comment]
Hmmm ... looks like problem is in config: Content-Security-Policy ????

**Comment by si458** [comment]
try commenting out `httpHeaders` section `_httpHeaders`
then restarting meshcentral and try again

i think you setting `Content-Security-Policy` is overlapping with the code

**Comment by si458** [comment]
this is my standard `Content-Security-Policy` which is auto generated by meshcentral

`default-src 'none'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' *.openstreetmap.org wss://mc.myserver.com; img-src 'self' blob: data: *.openstreetmap.org data:; style-src 'self' 'unsafe-inline'; frame-src 'self' blob: mcrouter: https://mc.myserver.com; media-src 'self'; form-action 'self'; manifest-src 'self'`

**Comment by Raito00** [comment]
yes, change - Content-Security-Policy - Now all OK!
Thanks!
