### ISSUE TITLE
Linux Agent Fails on OpenSuse

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#63]
Suse family (Gecko pictures, based on Leap) fails.

![screenshot from 2018-12-22 14-45-13](https://user-images.githubusercontent.com/279397/50378455-39b98a80-05f8-11e9-9abc-ed5b5d322f16.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.5-v with a fix for this. The agent should now install correctly, however the remote desktop feature will not work just like other distros as already reported. This fix should be good to close this specific issue.

**Comment by Ylianst** [comment]
I will close this since I think it's fixed. If there is a problem, please re-open this issue.
