### ISSUE TITLE
New permission

### ISSUE THREAD

**Issue by Raito00** [Ylianst/MeshCentral#6312]
**Is your feature request related to a problem? Please describe.**
Need disable access to Plugins for some user groups

![image](https://github.com/user-attachments/assets/1dd0f053-0a82-4ae4-9e66-5cf741de9e27)

**Describe the solution you'd like**
Add Permission -> No Plugins

![image](https://github.com/user-attachments/assets/48ad522c-cd62-4ee6-b68f-f4068177b6a0)

**Comment by si458** [comment]
Plugins are unofficially supported
even check the new docs
So we won't be adding this feature. I'm sorry
Plus, I'm sure there is already a request open for this type of thing?

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/issues/3872

**Comment by si458** [comment]
Depending on what the plugin is, we could look at officially adding it to meshcentral,
You would need to open a new enhancement request,
Then explain in great detail, why u want it officially integrating, and how u want it integrating
