### ISSUE TITLE
A bouncing account from AD

### ISSUE THREAD

**Issue by Smiley-k** [Ylianst/MeshCentral#6318]
**Describe the bug**
I observe a situation when, after integration with AD, my colleagues, when they create in mesh, do not display their own account, but a random one of another colleague.

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization: VMWare
 - Network: [WAN/NGINX/SSL]
 - Version: [1.1.27]

**Your config.json file**
```
"domains": {
    "": {
      "certUrl": "https://rd.company.com",
      "title": "Company",
      "_footer": "<a href='https://twitter.com/mytwitter'>Twitter</a>",
      "loginfooter": "This is a private server.",
      "_title2": "Servername",
      "AutoRemoveInactiveDevices": 145,
      "_minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "auth": "ldap",
	"ldapUserGroups": "memberOf",
	"ldapUserRequiredGroupMembership": ["CN=mesh,OU=Service,OU=Users,OU=USERS,DC=ad,DC=USERS,DC=lo"],
        "ldapUserPhoneNumber": "telephoneNumber",
	"__ldapSyncWithUserGroups": true,
        "_ldapUserImage": "thumbnailphoto",
	"ldapOptions": {
          "url": "ldap://ad.domain.lo:389/",
          "tlsOptions": { "rejectUnauthorized": false },
          "bindDN": "CN=rd,OU=!Service,OU=USERS,OU=company,DC=ad,DC=company,DC=lo",
          "bindCredentials": "Password",
          "searchBase": "OU=dep,OU=USERS,OU=Company,DC=ad,DC=company,DC=lo",
          "searchFilter": "(sAMAccountName={{username}})",
        "reconnect": true
	}
    }
},
```

**Comment by tobias9931** [comment]
Try to set "ldapuserrealname": "{{{givenName}}} {{{sn}}}",
we had the same issue

**Comment by si458** [comment]
what AD is it you have? openldap or windows?
to make users unique it uses different values from your LDAP, in this order
1. uses `ldapuserbinarykey` value you set in config.json IF its exists in your LDAP
2. uses `ldapuserkey` value you its set in config.json AND IF its exists in your LDAP
3. uses `objectSid` IF (`ldapuserkey` and `ldapuserbinarykey` are not set)
4. uses `objectGUID` IF `objectSid` doesnt exist and (`ldapuserkey` and `ldapuserbinarykey` are not set)
5. uses `name` IF `objectGUID` and `objectSid` dont exist and (`ldapuserkey` and `ldapuserbinarykey` are not set)
6. uses `cn` IF `name` and `objectGUID` and `objectSid` dont exist and (`ldapuserkey` and `ldapuserbinarykey` are not set)
so you need to check the values correctly in your LDAP of each user to make sure they arent the same!

https://github.com/Ylianst/MeshCentral/blob/7caf2aa05de336f19ad2cfee487d563ac78265f4/webserver.js#L465-L486

**Comment by si458** [comment]
you could also try using `"ldapUserBinaryKey": "sAMAccountName"` to make things unique

**Comment by si458** [comment]
@Smiley-k, I'm glad it's sorted! 
The ordering shouldn't matter as it's just json!
But chances are it was the `ldapUserBinaryKey` value u needed to set to something unique, and using `objectguid` fixed it!
