### ISSUE TITLE
RDP MeshRouter certificate error

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#632]
When trying to use the 'RDP' link for a windows computer from EDGE, downlaod runs fin, opens RDP connection, but when I connect I get an error with the title of teh error window being 'MeshRouter'

Error says 'The remote certificate is invalid according to the validation procedure.'

I can't work out what that means

**Comment by dinger1986** [comment]
is this still an issue?

**Comment by si458** [comment]
closing as stale,
please download the latest version 1.1.21 and use node 18 or above,
also download the latest meshcentralrouter too
if issue persists, please reply back
