### ISSUE TITLE
agent installation error prompt in Win7（meshcentral is v1.1.21）

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#6323]
Deal All:

The installation of meshagent in Windows 7 failed, and the version of meshcentral is v1.1.21.  Installation error prompt：

Problem signature:
  Problem Event Name:	BEX
  Application Name:	meshagent32-win7.exe
  Application Version:	0.0.0.0
  Application Timestamp:	639396df
  Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	00000000
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
----------------------------------------------------------------------------------------------------------

I have used an earlier version of meshcentral (before 1.0), meshagent supports running on Windows 7.

Detailed configuration information and logs have been collected and organized into documents.

[details and logs .docx](https://github.com/user-attachments/files/16593357/details.and.logs.docx)

Thanks so much.
Billy

**Comment by si458** [comment]
Windows 7 is unsupprted by Microsoft and unsupported by ourselves 

The only thing u can do is make sure ur meshcentral is up to date which urs isn't as (u are only running 1.1.21 and the latest is 1.1.27)

Make sure the windows 7 machines has ALL updates from Microsoft installed.

Make sure .net framework 4.6/4.7/4.8 is installed and again all updates are installed

**Comment by si458** [comment]
PS: from alot of my googling StackHash_0a9e seems to be related to a graphics card issue
so please make sure you have up to date drivers for the machine installed

**Comment by billydu1980** [comment]
Through troubleshooting, we found that it is not related to the. net 4. x version. 
Before meshCentral 1.0, the agent tool (MeshService. exe) included in the installation package was version 0.2.1.3 and supported on Windows 7 systems;

But after meshCentral 1.10, the version of the agent tool (MeshService. exe) that comes with the installation package shows version 0.0.0.0, the agent downloaded from the meshCentral UI console cannot be installed and run on Windows 7.


Best regards,


Billy Duu

发件人： Simon Smith
发送时间： 2024-08-26 01:04
收件人： Ylianst/MeshCentral
抄送： billydu; Author
主题： Re: [Ylianst/MeshCentral] agent installation error prompt in Win7（meshcentral is v1.1.21） (Issue #6323)
PS: from alot of my googling StackHash_0a9e seems to be related to a graphics card issue
so please make sure you have up to date drivers for the machine installed

**Comment by si458** [comment]
@billydu1980 again sadly Windows 7 is unsupported by Microsoft and unsupported by ourselves due to its age

We cannot guarantee the meshagent will work.

Only thing as explained you can do is make sure everything hardware and software is up to date, including drivers etc

But i still look after a single windows 7 32bit machine and it installed meshagent no problems

**Comment by billydu1980** [comment]
Dear All:

May I ask a question? What ports and protocols need to be opened before connecting between meshagent and meshcentral server; We configured the Mesh Central system in a practical application case, but due to the complexity of network devices and firewall policies, it has not been successfully tested. We need to count which port protocols the meshagent depends on.

Thanks so much for you reply!

Billy Duu


***@***.***
 
发件人： Simon Smith
发送时间： 2024-08-26 17:26
收件人： Ylianst/MeshCentral
抄送： billydu; Mention
主题： Re: [Ylianst/MeshCentral] agent installation error prompt in Win7（meshcentral is v1.1.21） (Issue #6323)
@billydu1980 again sadly Windows 7 is unsupported by Microsoft and unsupported by ourselves due to its age
We cannot guarantee the meshagent will work.
Only thing as explained you can do is make sure everything hardware and software is up to date, including drivers etc
But i still look after a single windows 7 32bit machine and it installed meshagent no problems

**Comment by si458** [comment]
@billydu1980 by default port 80+443+4433 all tcp
And u can customise these ports using `port, aliasport, mpsport` in config.json

**Comment by billydu1980** [comment]
Thanks so much for your reply！

Update the situation:
We noticed that the occupied port changes every time the meshagent service is restarted. The situation we encountered is that due to network security policies, the external communication ports of industrial PCs on site are restricted, allowing only certain ports to communicate externally; Excuse me, can I modify the meshagent.service file to enable meshagent to use a specified port, such as 12345?


As shown below, the local port of meshagent jumps from 35633 to 34923:

# lsof -i -P -n | grep edgeagent
edgeagent 24221   root   13u  IPv4 4486246      0t0  TCP 192.168.1.104:35633->192.168.1.94:443 (ESTABLISHED)
edgeagent 24221   root   16u  IPv4 4477615      0t0  UDP *:37706
# systemctl restart edgeagent

# lsof -i -P -n | grep edgeagent
meshagent  8568   root   13u  IPv4 4577770      0t0  TCP 192.168.1.104:34923->192.168.1.94:443 (ESTABLISHED)
meshagent  8568   root   16u  IPv4 4577039      0t0  UDP *:38134




billy duu


***@***.***
 
发件人： Simon Smith
发送时间： 2024-12-29 19:36
收件人： Ylianst/MeshCentral
抄送： billydu; Mention
主题： Re: [Ylianst/MeshCentral] agent installation error prompt in Win7（meshcentral is v1.1.21） (Issue #6323)
@billydu1980 by default port 80+443+4433 all tcp
And u can customise these ports using port, aliasport, mpsport in config.json
―

**Comment by billydu1980** [comment]
Sorry, please take a look at this screenshot，the local port of meshagent jumps from 50842 to 53292:


# lsof -i -P -n | grep meshagent
meshagent  2436            root   13u  IPv4  50842      0t0  TCP 172.16.66.146:40943->172.16.66.94:443 (ESTABLISHED)
meshagent  2436            root   16u  IPv4  51986      0t0  UDP *:33660

# systemctl restart meshagent.service

# lsof -i -P -n | grep meshagent
meshagent  2807            root   13u  IPv4  53292      0t0  TCP 172.16.66.146:37365->172.16.66.94:443 (ESTABLISHED)
meshagent  2807            root   16u  IPv4  53383      0t0  UDP *:45669

I was trying to modify the/lib/systemd/system/IPCagent.service file by adding -- port=12345 at the end of ExecutStart=/usr/local/mesh_stervices. But it didn't take effect.




***@***.***
 
发件人： ***@***.***
发送时间： 2024-12-30 12:57
收件人： Ylianst/MeshCentral; Ylianst/MeshCentral
抄送： Mention
主题： Re: Re: [Ylianst/MeshCentral] agent installation error prompt in Win7（meshcentral is v1.1.21） (Issue #6323)
Thanks so much for your reply！

Update the situation:
We noticed that the occupied port changes every time the meshagent service is restarted. The situation we encountered is that due to network security policies, the external communication ports of industrial PCs on site are restricted, allowing only certain ports to communicate externally; Excuse me, can I modify the meshagent.service file to enable meshagent to use a specified port, such as 12345?


As shown below, the local port of meshagent jumps from 35633 to 34923:

# lsof -i -P -n | grep edgeagent
edgeagent 24221   root   13u  IPv4 4486246      0t0  TCP 192.168.1.104:35633->192.168.1.94:443 (ESTABLISHED)
edgeagent 24221   root   16u  IPv4 4477615      0t0  UDP *:37706
# systemctl restart edgeagent

# lsof -i -P -n | grep edgeagent
meshagent  8568   root   13u  IPv4 4577770      0t0  TCP 192.168.1.104:34923->192.168.1.94:443 (ESTABLISHED)
meshagent  8568   root   16u  IPv4 4577039      0t0  UDP *:38134




billy duu


***@***.***
 
发件人： Simon Smith
发送时间： 2024-12-29 19:36
收件人： Ylianst/MeshCentral
抄送： billydu; Mention
主题： Re: [Ylianst/MeshCentral] agent installation error prompt in Win7（meshcentral is v1.1.21） (Issue #6323)
@billydu1980 by default port 80+443+4433 all tcp
And u can customise these ports using port, aliasport, mpsport in config.json
―
