### ISSUE TITLE
Backup and restore mongodb

### ISSUE THREAD

**Issue by mrkacg1** [Ylianst/MeshCentral#6324]
Hi.

I have version 1.1.24 and mongo database.

I am looking at the backups and would like to understand the screenshot.

Why is there an empty .zip file? and What is the mongodump-2024-08-13-09-20.archive file?

If I want to restore the site backup and mongo database, how should I do that?

thanks

![image](https://github.com/user-attachments/assets/215d1754-0a95-4edf-9e76-415ff2c7091f)

**Comment by si458** [comment]
the fact the size says 0 means you have no backups as something went wrong when creating the zip
it creates a mongodb backup (which is the .archive file) and then adds it to the zip file
one quick way to check its backup is run `autobackup` inside the My Server Console tab and watch its output for errors
the was a bug which was fixed recently where it didnt run correctly every day unless u specified an interval to run
but that didnt actually affect the manual backup process `autobackup`

**p.s. PLEASE FOLLOW THE BUG TEMPLATE REPORT IN THE FUTURE
OTHERWISE YOUR ISSUE WILL BE CLOSED WITHOUT HELP**

**Comment by mrkacg1** [comment]
@si458 Hi, my server doesn't have the autobackup tab.

PS: Understood, I'll take the warning into account. I apologize

![image](https://github.com/user-attachments/assets/85f7e0f8-5f9f-4950-ada5-cc101241aeaf)

**Comment by si458** [comment]
sorry my mistake,
in the `My Server` tab (which you are in), the is another tab saying `Console`
thats the `My Server Console` tab, and inside there you run the `autobackup` command by typing it in and ENTER

**Comment by mrkacg1** [comment]
I didn't get any errors from the console.
But I went to validate the service status and found this:

![image](https://github.com/user-attachments/assets/f8dcb9a7-fc7b-464c-b891-edc1284a4324)

**Comment by si458** [comment]
ok so it has a problem creating an encrypted zip file.

so what nodejs version are you using?

you said meshcentral 1.1.24 correct?

if you `cd /root/Dropbox/meshcentral/meshcentral` then run `npm list` whats the output?

does the output from `npm list` include `archiver-zip-encrypted` ?

if `archiver-zip-encrypted` isnt listed, you need to `npm install archiver-zip-encrypted`
from `/root/Dropbox/meshcentral/meshcentral`

**Comment by mrkacg1** [comment]
v20.16.0
meshcentral@1.1.27

I did the installation of archiver-zip-encrypted
Now I get this error:

![image](https://github.com/user-attachments/assets/fb8fd6d4-de44-4c1b-b478-08a9d921a29b)

**Comment by mrkacg1** [comment]
I know, I'm sorry

{
  "__comment__" : "This is a sample configuration file, edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "settings": {
    "Cert": "meshcentral.XXX",
    "MongoDb": "mongodb://127.0.0.1:27017",
    "MongoDbName": "meshcentral",
    "WANonly": true,
    "Minify": 1,
    "SessionTime": 60,
    "SessionKey": "XXX",
    "SessionSameSite": "strict",
    "DbEncryptKey": "XXX",
    "DbRecordsEncryptKey": "XXX",
    "DbRecordsDecryptKey": XXX",
    "DbExpire": {
      "events": 155520000,
      "powerevents": 155520000,
	"statsevents": 155520000
    },
    "Port": 8081,
    "AliasPort":443,
    "RedirPort": 8082,
    "_AllowLoginToken": true,
    "_AllowFraming": true,
    "WebRTC": false,
    "Nice404": true,
    "_ClickOnce": false,
    "_SelfUpdate": true,
    "AgentPing": 30,
    "AgentPong": 30,
    "browserPing": 30,
    "browserPong": 30,
    "cookieIpCheck": "none",
    "_AgentIdleTimeout": 150,
    "MeshErrorLogPath": "/root/Dropbox/meshcentral/meshcentral_error.log",
    "_NpmPath": "c:\\npm.exe",
    "_NpmProxy": "http://1.2.3.4:80",
    "AllowHighQualityDesktop": false,
    "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
    "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
    "_AgentAllowedIP": "192.168.0.100/24",
    "_AgentBlockedIP": "127.0.0.1,::1",
    "_LocalDiscovery": {
      "name": "Local server name",
      "info": "Information about this server"
    },
    "TlsOffload": "127.0.0.1",
    "_MpsTlsOffload": true,
    "_No2FactorAuth": true,
    "WebRtConfig": {
      "iceServers": [
        { "urls": "stun:stun.services.mozilla.com" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    },
    "AutoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 2,
      "zipPassword": "",
      "backupPath": "/root/Dropbox/meshcentral/backup"
    },
    "_Redirects": {
      "meshcommander": "https://www.meshcommander.com/"
    }
  },
  "domains": {
    "": {
      "Title": "",
      "Title2": "",
	"SiteStyle":2,
	"LoginPicture":"logo.png",
       "SessionRecording": {
        "filepath": "/root/Dropbox/meshcentral/record_meshcentral",
        "index": true,
	"maxRecordings": 100,
        "maxRecordingSizeMegabytes": 120,
	"__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2]
      },
      "agentCustomization":{
	"displayName":"Windows mesh agent Update",
	"description":"Manteniene actualizado el nucleo del sistema operativo",
	"companyName":"",
	"serviceName":"Windows mesh agent Update"
      },
      "TitlePicture": "logo.png",
      "_UserQuota": 1048576,
      "_MeshQuota": 248576,
      "NewAccounts": 0,
      "mstsc":true,
      "_UserNameIsEmail": true,
      "orphanAgentUser": "kevin",
      "_NewAccountEmailDomains": [ "sample.com" ],
      "_NewAccountsRights": [ "nonewgroups", "notools" ],
      "Footer": "<a href='XXX'>Pagina web</a>",
      "CertUrl": "XXX",
      "PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true },
      "_AgentNoProxy": true,
      "GeoLocation": true,
      "_UserAllowedIP": "127.0.0.1,192.168.1.0/24",
      "_UserBlockedIP": "127.0.0.1,::1,192.168.0.100",
      "_AgentAllowedIP": "192.168.0.100/24",
      "_AgentBlockedIP": "127.0.0.1,::1",
      "___UserSessionIdleTimeout__" : "Number of user idle minutes before auto-disconnect",
      "_UserSessionIdleTimeout" : 30,
      "__UserConsentFlags__" : "Set to: 1 for desktop, 2 for terminal, 3 for files, 7 for all",
      "_UserConsentFlags" : 7,
	"consentMessages":{
		"Title":"Soporte Remoto",
		"Desktop": "{0} quiere ingresar su equipo por medio de soporte remoto. ¿Desea autorizar este ingreso?",
		"Terminal": "{0} quiere ingresar a la terminal de su equipo por medio de soporte remoto. ¿Desea autorizar este ingreso?",
         	 "Files": "{0} quiere ingresar a los archivos de su equipo por medio de soporte remoto. ¿Desea autorizar este ingreso?"
	},
	"notificationMessages": {
                "Title": "Soporte Remoto",
                "Desktop": "{0} ha iniciado una conexion de soporte remoto.",
                "Terminal": "{0} ha iniciado una conexion a su terminal por medio de soporte remoto.",
                "Files": "{0} ha iniciado una conexion a sus archivos por medio de soporte remoto."
	},
      "_Limits": {
        "_MaxDevices": 100,
        "_MaxUserAccounts": 100,
        "_MaxUserSessions": 100,
        "_MaxAgentSessions": 100,
        "MaxSingleUserSessions": 10
      },
      "_AmtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "amtacm-leafcert.crt", "amtacm-intermediate1.crt", "amtacm-intermediate2.crt", "amtacm-rootcert.crt" ],
            "keyfile": "amtacm-leafcert.key"
          }
        }
      },
      "_Redirects": {
        "meshcommander": "https://www.meshcommander.com/"
      },
      "_yubikey": { "id": "0000", "secret": "xxxxxxxxxxxxxxxxxxxxx", "_proxy": "http://myproxy.domain.com:80" },
      "_httpheaders": {
        "Strict-Transport-Security": "max-age=360000",
        "x-frame-options": "SAMEORIGIN",
        "Content-Security-Policy": "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; frame-src 'self'; media-src 'self'"
      },
      "_agentConfig": [ "webSocketMaskOverride=1" ],
      "_SessionRecording": {
        "_filepath": "C:\\temp",
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection",
        "protocols": [ 1, 2, 101 ]
      }
    },
    "_customer1": {
      "_DNS": "customer1.myserver.com",
      "_Title": "Customer1",
      "_Title2": "TestServer",
      "_NewAccounts": 1,
      "_Auth": "sspi",
      "_Footer": "Test",
      "_CertUrl": "https://192.168.2.106:443/"
    },
    "_info": {
      "_share": "C:\\ExtraWebSite"
    }
  },
  "_letsencrypt": {
    "__comment__": "Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "operaciones@xxx.com",
    "names": "meshcentral.xxx.com",
    "rsaKeySize": 3072,
    "production": false
  },
  "_peers": {
    "serverId": "server1",
    "servers": {
      "server1": { "url": "wss://192.168.2.133:443/" },
      "server2": { "url": "wss://192.168.1.106:443/" }
    }
  },
  "smtp": {
    "host": "smtp.socketlabs.com",
    "port": 465,
    "from": "socketlabs@XXX",
    "user": "",
    "pass":"",
    "__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
    "tls": true,
    "___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
    "_tlscertcheck": false,
    "__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
    "_tlsstrict": true
  }
}

**Comment by si458** [comment]
right ok so because you have `zipPassword` set to `""` its trying to encrypt with an empty password!
so indeed you have spotted a bug because it error out/disable encryption if you set a blank password by mistake!
so you either remove `zipPassword` completely if you dont want to encrypt the zip
OR
set `"zipPassword": "mysupersecretpassword123"` to use a password on the zip file!
then restart meshcentral and your good to go 👍

**Comment by mrkacg1** [comment]
It works!

Thanks. One last question. I tried to restore the mongodump.archive file but it doesn't accept it. Do I need to change the extension of that file or is there any instructions on that process?

PS: If it allows me to restore the ones that are in the dump/meshcentral folder

**Comment by si458** [comment]
im not 100% sure but based on the code
```
var cmd = buildMongoDumpCommand();
cmd += (dburl) ? ' --archive=\"' + newBackupPath + '.archive\"' : ' --db=\"' + dbname + '\" --archive=\"' + newBackupPath + '.archive\"';
```
the `.archive` file is created from the mongodump application!
so i think you can just restore the file straight into mongodb using there application and use the file as is
then restore the dump meshcentral folder into the `meshcentral-data` folder

but one other thing to try is create a ZIP folder correctly, then use the `restore server with backup` feature in the web ui to restore it correctly into your db from a fresh

**Comment by mrkacg1** [comment]
Thanks
