### ISSUE TITLE
Lock and Maintenance Screen

### ISSUE THREAD

**Issue by prononext** [Ylianst/MeshCentral#6325]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Having the possibility to block user input is nice on the remote session. It would be really nice, if the admin can configure a overlay or similar, to disable the screen and show a maintenance message full screen with background.
I would imagine a central setting or ENV to specify a full-screen image that shows when activating that privacy mode. 

**Describe alternatives you've considered**
Other tools like Anydesk and Teamviewer have that function to deactivate user screens.
https://support.anydesk.com/knowledge/screen-privacy
https://www.teamviewer.com/en-us/global/support/knowledge-base/teamviewer-classic/security/security-features/teamviewer-black-screen/?

**Additional context**
n/a

**Comment by si458** [comment]
duplicate https://github.com/Ylianst/MeshCentral/issues/416
