### ISSUE TITLE
URL managment.   

### ISSUE THREAD

**Issue by fordcrews** [Ylianst/MeshCentral#6332]
I think it would be great if the ability to store links to url's in each group and ability to ssh to hosts that the agent can't be installed on such as firewalls, SANS, and switches would be great.  To make this like a one stop secure way to get to all your assets.

**Comment by si458** [comment]
currently also the `showNotesPanel` doesnt apply to the group notes, only the device notes
did you want a seperate value like `showNotesPanelInGroups` ?

**Comment by si458** [comment]
also attaching onto this old issue about using markdown in notes! https://github.com/Ylianst/MeshCentral/issues/4091

**Comment by fordcrews** [comment]
I really just wanted to be able to click a link and go there, have something like workfirewall that goes to https://workfirewall:8443,  using either the mesh network, or tailscale/wireguard address.

**Comment by si458** [comment]
Oh, that's not the way meshcentral is designed!
And would be very complex to build into the web ui!
You can already do the web relay which works as explained above.
create a relay group then right click the devices https text and you can specify a different port for that device
So that will kinda help,
You would just need to create a device for each item you want to access

Or

Look into using the meshcentralrouter and that can do port relaying to other devices using a remote agent

**Comment by fordcrews** [comment]
I was really hoping notes could have a function like 

function convertToLink(text) {
    const regex = /(\b(?:http|https):\/\/[^\s]+)|(<([^>]+)>-->(\b(?:http|https):\/\/[^\s]+))/g;

    return text.replace(regex, (match, p1, p2, p3, p4) => {
        if (p1) {
            // If the match is just the URL
            return `<a href="${p1}">${p1}</a>`;
        } else if (p2 && p3 && p4) {
            // If the match is in the format <sitename>-->URL
            return `<a href="${p4}">${p3}</a>`;
        }
    });
} 

called  before being displayed, so if so if notes contained "Check this link: https://server:port" it would make a proper <a href> that could be clicked or if it contained, <Router Admin Page>-->https://server:port you would get a clickable link <Router Admin Page>.

I have a bunch of websites I manage for people, that might have a geoserver, a document management system, print server, webmail server,  all on different ports on same machine.   Would just be nice to be able to organize them in the notes, or  even just allow links maybe on one of the other tabs along with notes.    Wasn't wanting changes in how it worked, just allowing it to store more details about a machine.     Maybe I didn't describe what I was looking for well.

**Comment by si458** [comment]
markdown already does this if you check my recent post https://github.com/Ylianst/MeshCentral/issues/4091#issuecomment-2308937407
also a cheatsheet too https://www.markdownguide.org/cheat-sheet/

it can convert `[printer ssl with custom port](https://192.168.1.123:8182)`
into `<a href="https://192.168.1.123:8182">printer ssl with custom port</a>`

**Comment by fordcrews** [comment]
Duh, somehow I had missed the 
[title](https://www.example.com)
I was expecting just https://address:port to work.

**Comment by si458** [comment]
> Duh, somehow I had missed the 
> `[title](https://www.example.com)`
> I was expecting just `https://address:port` to work. 

Yes currently this doesn't work, BUT I am looking at adding the markdown to notes which means that links will indeed work!
Just need to do some sanitazing of text etc first before I upload and you can test a build :)

**Comment by si458** [comment]
added for you!
will be in latest docker master build or npm builds for testing
`ghcr.io/ylianst/meshcentral:master` or `npm install Ylianst/MeshCentral` (remember no translations in npm build)
or wait until next release

**Comment by b8two** [comment]
Can the default for the links to be open in a new tab/window?
