### ISSUE TITLE
Add support for Bootstrap in MeshCentral, along with a theme switcher

### ISSUE THREAD

**Issue by marclaporte** [Ylianst/MeshCentral#6333]
"Bootstrap (formerly Twitter Bootstrap) is a [free and open-source](https://en.wikipedia.org/wiki/Free_and_open-source) [CSS framework](https://en.wikipedia.org/wiki/CSS_framework) directed at responsive, [mobile-first](https://en.wikipedia.org/wiki/Responsive_web_design#Mobile_first,_unobtrusive_JavaScript,_and_progressive_enhancement) [front-end web development](https://en.wikipedia.org/wiki/Front-end_web_development)."
Source: https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)

We started working to add support for Bootstrap to MeshCentral.

The plan:
- Add Bootstrap support and make it possible to have multiple themes, such as https://github.com/thomaspark/bootswatch
- Encourage capacity for community-contributed themes (documentation, support, etc.)
- Pick an existing Bootstrap theme or create a new one destined to become the new default
- Have a theme picker so users can opt in to the new themes
- The non-Bootstrap themes will go in minimum maintenance mode (so we focus our energies on the future)
- When the community feels it's good enough, a Bootstrap theme will become the new default (and users can still switch back to legacy themes, use their existing custom theme or pick any other Bootstrap theme)
- In a few years, when almost everyone is using the Bootstrap themes, for a major version, we can remove non-Bootstrap themes (We will rediscuss this as a community in a few years)

The code so far: https://github.com/Ndaboom/MeshCentral

**Comment by cfoellmann** [comment]
I am with you.
Time is sparse and I am in no way a node dev but I will support this effort as best as possible

**Comment by kambereBr** [comment]
A few screenshots of the MeshCentral Bootstrap version in progress. I will regularly provide updated screenshots as the work progresses.

Repo: https://github.com/Ndaboom/MeshCentral


![Screenshot 2024-08-28 015029](https://github.com/user-attachments/assets/0654581a-0619-4d34-bd71-2495f66895cc)

![Screenshot 2024-08-28 020054](https://github.com/user-attachments/assets/b31068f0-13f1-4c50-b9ce-3ef97b0dc03d)

![Screenshot 2024-08-28 015227](https://github.com/user-attachments/assets/c4eda650-8e6a-40f5-b38b-9856458e46b2)

![Screenshot 2024-08-28 015312](https://github.com/user-attachments/assets/3b464f5b-7114-4ca3-bcda-4a19b47ae6cd)

![Screenshot 2024-08-28 015927](https://github.com/user-attachments/assets/f35cf6ae-4c48-4c32-8371-0e6e43c21530)

![Screenshot 2024-08-28 015557](https://github.com/user-attachments/assets/7159911e-8e08-459c-9e50-87a67873ad7a)

![Screenshot 2024-08-28 021219](https://github.com/user-attachments/assets/e0af5974-93e9-43ef-b7ee-59f59835a12a)

**Comment by cfoellmann** [comment]
@kambereBr this looks very promising!!

When bootstrap is the foundation it will be far easier to theme.
@si458 Is it possible to split the template files for the UI? I am totally oblivious how the nodejs app uses the templates but these mega files are very hard to handle.

**Comment by si458** [comment]
@cfoellmann The idea at the moment is to have another default.handlebars called default-bootstrap.handlebars

Then, when u specify like ui=1, it will use the new bootstrap ui or ui=0 and use the old one

I do believe the guys are looking at separating the ui into different .handlebar files then people can change certain parts to the hearts content rather than struggling with just a single .handlebar file!

**Comment by marclaporte** [comment]
We are making progress and we will be looking for testers in about 3 weeks.

**Comment by marclaporte** [comment]
Next step is a merge request against master and a documented flag on how to activate.

We will start monthly community meetings so we can discuss this and many other topics.

**Comment by si458** [comment]
New video showing the website is now responsive for mobile devices!

https://github.com/user-attachments/assets/02925489-64fc-4b06-a4aa-e25a162250bf

**Comment by Ndaboom** [comment]
Hello everyone!
I’m super happy to introduce our first Monty MeshCentral Meeting coming this October 31 at 14:00 UTC. You’re all welcome to this community meeting where we will discuss project updates, share ideas, and connect with fellow members. We’re planning to have this meeting every 4th Thursday of each month, so please join us for the first one this October 31, 2024, at 14:00 UTC.

Welcome to all!

Please find more details about this event at the following link:
https://github.com/Ylianst/MeshCentral/wiki/Community-Monthly-Meetings

**Comment by marclaporte** [comment]
@Ndaboom 4th Thursday of October is October 24th

**Comment by criani** [comment]
I recently updated and noted that there are some bootrap packs from bootswatch in /themes. I have been toying with them and would be glad to do testing as needed

**Comment by DCS-KC** [comment]
I have been unable to get the new theme so appear when using Docker. I have followed the instructions from [Testing Bootstrap UI for MeshCentral](https://github.com/Ndaboom/MeshCentral/wiki/Testing-Bootstrap-UI-for-MeshCentral) by accessing my container with a terminal and renaming the necessary view file. When I restart the server I am greeted with the original UI. Am I missing a step somewhere?

**Comment by si458** [comment]
@DCS-KC don't follow those steps they are now old and obsolete 
Simple add `?sitestyle=3` to the url and say hi to the new ui hehe

**Comment by DCS-KC** [comment]
> [@DCS-KC](https://github.com/DCS-KC) don't follow those steps they are now old and obsolete Simple add `?sitestyle=3` to the url and say hi to the new ui hehe

OMG, no way it was that easy... should have asked an hour ago! What would be the best thread to follow for developments?

**Comment by si458** [comment]
@DCS-KC it's already been developed/nearly finished, so test away

 if u find a bug, check closed issues first in case we have already fixed it.

If u can't find an issue, then open a bug report and make sure u follow the template, but also say u use the bootstrap ui

**Comment by DCS-KC** [comment]
@si458 Excellent, thanks!

**Comment by Br0kenSilos** [comment]
How would you apply that if the site is setup with a login key. For example: https://mc.example.com/?key=Hjkeohjfjhdkjhfk34578y

**Comment by si458** [comment]
@Br0kenSilos same as above `https://mc.example.com/?key=a1b2c3d4&sitetyle=3` 
OR
set `sitestyle: 3`under `domains` in your `config.json`

**Comment by Br0kenSilos** [comment]
Ah, great. Thank you sir!  :-)
