### ISSUE TITLE
Editing the meshcore.js File (OPEN WRONG, PLEASE CLOSE TOPIC)

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#634]
Guys, good morning!

I am trying to edit the user interaction texts of the meshcore.js file but the edits are not working, I have already deleted the meshcore.min.js file but it is still not working. Can you help me?

![image](https://user-images.githubusercontent.com/55212206/68208267-95da9280-ffaf-11e9-8707-1ff9e78ff151.png)

![image](https://user-images.githubusercontent.com/55212206/68208310-a854cc00-ffaf-11e9-86b0-c4da414ce9de.png)

**Comment by geanferrani123** [comment]
Sorry, wrongly opened topic, close it please.

**Comment by TotallyNotElite** [comment]
You can close issues yourself. Press the "close issue" button.
