### ISSUE TITLE
No device Show on meshcentral

### ISSUE THREAD

**Issue by sotoloaizamiguel** [Ylianst/MeshCentral#6340]
Hi, I have more that 300 device added to my meshcentral. Today I can't see any device on the groups. Can you help me please?
![Screenshot 2024-08-23 102324](https://github.com/user-attachments/assets/6e5eec16-f853-4593-a5af-5d8518eed2fb)

**Comment by si458** [comment]
**You didn't follow the bug template report, so we can not assist u until you follow it**

Please reply with all the information from the bug report (create a new bug report and copy+paste the text)

**Comment by sotoloaizamiguel** [comment]
**Describe the bug**
Hi, I have more that 300 device added to my meshcentral, It's was work fine yesterday. Today I can't see any device on the groups. I restarted the server, now the meshcentral show a socket error

**Screenshots**
![websocketerror](https://github.com/user-attachments/assets/2292a281-1ed9-4f55-936f-621c88eaec52)


**Server Software (please complete the following information):**
 - OS: Ubuntu Server
 - Network: WAN
 - Version: 20.04.6
 - Node: 22.7.0

**Your config.json file**
```
{
    "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
    "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
    "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
    "settings": {
		"MongoDb": "mongodb://meshcentraluser:pasword@127.0.0.1:27017/meshcentral",
		"DbRecordsDecryptKey": "key",
        "cert": "support.bluetg.com",
        "WANonly": true,
        "_LANonly": true,
        "_sessionKey": "",
		"ipBlockedUserRedirect": "http://bluetg.com/",
        "port": 443,
        "_aliasPort": 443,
        "_redirPort": 80,
        "_redirAliasPort": 80,
		"Compression": true,
        "WsCompression": true,
        "AgentWsCompression": true,
		"DesktopMultiplex": true,
		"_plugins": { "enabled": true },
        "maxInvalidLogin": {
            "time": 5,
            "count": 5,
            "coolofftime": 60
        }
    },
    "domains": {
        "": {
            "titlePicture": "logo-bluetg-horizontal-web-fotter.png",
            "loginPicture": "logo-bluetg-horizontal-web2.png",
            "welcomeText": "A remote solution system",
            "welcomePicture": "17973908.jpg",
            "welcomePictureFullScreen": true,
            "title": "Blue Technology Group",
            "_title2": "Support Portal",
            "_minify": true,
            "newAccounts": false,
            "userNameIsEmail": true,
            "agentInviteCodes": true,
			"userSessionIdleTimeout": 10,
			"geoLocation": true,
			"ipLocation": true,
			"nightMode": 2,
            "authStrategies": {
                "azure": {
                    "newAccounts": true,
                    "clientid": "client_id",
                    "clientsecret": "client_secret",
                    "tenantid": "tenan_id"
                }
            },
            "agentCustomization": {
                "displayName": "Blue Technology Group Remote Agent",
                "description": "Blue Technology Group agent for remote monitoring, management and assistance.",
                "companyName": "Blue Technology Group",
                "serviceName": "Bluetecagent",
                "image": "logo-bluetg-new.png",
                "fileName": "Bluetecagent"
            },
            "agentFileInfo": {
                "icon": "logo-bluetg.ico",
                "filedescription": "Bluetec agent for remote monitoring, management and assistance.",
                "fileversion": "0.1.2.3",
                "internalname": "Bluetecagent",
                "legalcopyright": "© 2024 AO Blue Technology Group",
                "originalfilename": "Bluetecagent",
                "productname": "Bluetecagent",
                "productversion": "v0.1.2.3"
            },
            "assistantCustomization": {
                "title": "Blue Technology Group Assintant",
                "image": "logo-bluetg-horizontal-web3.png",
                "fileName": "Bluetec Assintant"
            },
            "androidCustomization": {
                "title": "Blue Technology Group",
                "subtitle": "Android version",
                "image": "logo-bluetg-horizontal-web3.png"
            },
            "passwordRequirements": {
                "min": 8,
                "max": 128,
                "upper": 1,
                "lower": 1,
                "numeric": 1,
                "nonalpha": 1,
                "reset": 90,
                "force2factor": true,
                "_skip2factor": "127.0.0.1,192.168.2.0/24",
                "oldPasswordBan": 5,
                "banCommonPasswords": false,
                "twoFactorTimeout": 300
            },
            "userConsentFlags": {
                "desktopnotify": true,
                "terminalnotify": false,
                "filenotify": false,
                "desktopprompt": false,
                "terminalprompt": false,
                "fileprompt": false,
                "desktopprivacybar": false
            }
        }
    },
    "letsencrypt": {
        "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
        "email": "support@bluetg.com",
        "names": "support.bluetg.com",
        "skipChallengeVerification": false,
        "production": true
    },
    "smtp": {
        "title": "Bluetec Remote Support Message",
        "host": "smtp.office365.com",
        "port": 587,
        "from": "donotreply@bluetg.com",
        "user": "donotreply@bluetg.com",
        "pass": "paswword",
        "tls": false,
        "_tlsstrict": true,
        "_verifyemail": false,
        "emailDelaySeconds": 300
    },
  "_messaging": {
    "callmebot": true
  }
}

**Comment by si458** [comment]
ok so your config is all correct, nothing jumps out as wrong.
first as your using linux stop meshcentral `systemctl stop meshcentral` 
and then verify nothing is running still `ps aux | grep meshcentral.js`
also check nothing is running on port 80 and 443 `lsof -Pni`
next goto your folder you host your meshcentral from (the folder which contains `meshcentral-data meshcentral-data meshcentral-backups` etc...
then try running it in manually and checking it starts correctly and no errors `node node_modules/meshcentral`
then check the web ui,
if the web ui is still missing node
then stop meshcentral and run with full debug and check again `node node_modules/meshcentral --debug`
NOTE THIS WILL FULL YOUR PAGE WITH LOGS SO PAY CLOSE ATTENSION!
if its STILL missing nodes, then it must be a database issue?
as it wouldnt be showing groups if the thing was completely dead/broken

**Comment by sotoloaizamiguel** [comment]
-When i put ps aux | grep meshcentral.js the server show:
bluetgu+    8696  0.0  0.0   8176   720 pts/0    S+   15:32   0:00 grep --color=auto meshcentral.js

-When i put lsof -Pni, show:
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-n  586 systemd-network   19u  IPv4  20529      0t0  UDP 10.0.0.4:68
systemd-r  588 systemd-resolve   12u  IPv4  20477      0t0  UDP 127.0.0.53:53
systemd-r  588 systemd-resolve   13u  IPv4  20478      0t0  TCP 127.0.0.53:53 (LISTEN)
chronyd    650         _chrony    6u  IPv4  21913      0t0  UDP 127.0.0.1:323
chronyd    650         _chrony    7u  IPv6  21914      0t0  UDP [::1]:323
mongod     654         mongodb   11u  IPv4  26062      0t0  TCP 127.0.0.1:27017 (LISTEN)
sshd       753            root    3u  IPv4  25735      0t0  TCP *:22 (LISTEN)
sshd       753            root    4u  IPv6  25737      0t0  TCP *:22 (LISTEN)
sshd      1356            root    4u  IPv4  29221      0t0  TCP 10.0.0.4:22->199.188.125.69:57620 (ESTABLISHED)
sshd      1364            root    4u  IPv4  29363      0t0  TCP 10.0.0.4:22->199.188.125.69:57622 (ESTABLISHED)
sshd      1469      bluetguser    4u  IPv4  29221      0t0  TCP 10.0.0.4:22->199.188.125.69:57620 (ESTABLISHED)
sshd      1469      bluetguser   10u  IPv6  29514      0t0  TCP [::1]:6010 (LISTEN)
sshd      1469      bluetguser   11u  IPv4  29515      0t0  TCP 127.0.0.1:6010 (LISTEN)
sshd      1566      bluetguser    4u  IPv4  29363      0t0  TCP 10.0.0.4:22->199.188.125.69:57622

- When I put node node_modules/meshcentral on the meshcentral file, show:
ERR: (node:10214) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
MeshCentral HTTP redirection server running on port 80.
MeshCentral v1.1.27, WAN mode.
MeshCentral Intel(R) AMT server running on support.bluetg.com:4433.
MeshCentral HTTPS server running on support.bluetg.com:443.
SMTP mail server smtp.office365.com working as expected.

and the web UI show the same websocket error.
![websocketerror](https://github.com/user-attachments/assets/04eb7306-5556-4e3f-8dff-06826d2c0b60)

When i put node node_modules/meshcentral --debug, the console show:

DB: Connected to MongoDB database...
MAIN: Core module windows-amt is 616883 bytes.
MAIN: Core module linux-amt is 565640 bytes.
MAIN: Core module linux-noamt is 469064 bytes.
MAIN: Core module windows-recovery is 134130 bytes.
MAIN: Core module linux-recovery is 80756 bytes.
MAIN: Core module windows-agentrecovery is 59533 bytes.
MAIN: Core module linux-agentrecovery is 6159 bytes.
MAIN: Core module windows-tiny is 6125 bytes.
MAIN: Core module linux-tiny is 6125 bytes.
MeshCentral HTTP redirection server running on port 80.
AUTHLOG: Server listening on 0.0.0.0 port 80.
CERT: LE: Getting certs from local store (Production)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v1.1.27, WAN mode.
DISPATCH: AddEventDispatch [ 'server-shareremove' ]
DISPATCH: AddEventDispatch [ '*' ]
DISPATCH: DispatchEvent [ '*' ]
MAIN: Server started
MeshCentral Intel(R) AMT server running on support.bluetg.com:4433.
AUTHLOG: Server listening on 0.0.0.0 port 4433.
AUTHLOG: Adding Azure SSO with options: {"clientID":"be7ab375-71fe-4c68-aef9-8bb","clientSecret":"gox8Q~zxLpuL2Puu82LA66.gneQ6qQCwlZ","tenant":"05c40fb0-c28f-4e05-b539-70cda","callbackURL":"/auth-azure-callback"}
AUTHLOG: Setting up authentication strategies login and callback URLs for root domain.
HTTPS: Server listening on 0.0.0.0 port 443.
MeshCentral HTTPS server running on support.bluetg.com:443.
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': '+jxbuvRwlvtb6Z9LmZLUXi==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (108.21.197.61) /agent.ashx/.websocket
AGENT: New agent at 108.21.197.61:61842
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'OOMtMJquC0ONxjkrhz+E1U==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (71.57.222.5) /agent.ashx/.websocket
AGENT: New agent at 71.57.222.5:61705
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'YxeeR8fI68v8i+8haW2TSF==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (71.57.222.5) /agent.ashx/.websocket
AGENT: New agent at 71.57.222.5:54848
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'p5JSg7Xi/VIrbx04SMEPlY==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (108.191.6.34) /agent.ashx/.websocket
AGENT: New agent at 108.191.6.34:57703
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'rw04f1B7NIJljQ7j1UblCX==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (50.172.117.50) /agent.ashx/.websocket
AGENT: New agent at 50.172.117.50:16418
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'JVkjk/4R9Jgfx2QJNMeb0E==',
  'sec-websocket-version': '13'
}
WEBREQUEST: (96.85.227.70) /agent.ashx/.websocket
AGENT: New agent at 96.85.227.70:60473
HTTPHEADERS: GET /agent.ashx/.websocket {
  host: 'support.bluetg.com',
  upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-key': 'ULluoUIgN+K2RbiKshTRA1==',
  'sec-websocket-version': '13'

and many more records.

**Comment by sotoloaizamiguel** [comment]
![websocketerror1](https://github.com/user-attachments/assets/dcb03366-8d3f-4b09-bb05-35e6a61d07d8)

**Comment by sotoloaizamiguel** [comment]
This is the error lo:

-------- 8/23/2024, 3:15:34 AM ---- 1.1.27 --------

(node:1066) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 12:40:50 PM ---- 1.1.27 --------

(node:1082) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 12:43:18 PM ---- 1.1.27 --------

TokenError: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: ad7c7bb7-afdc-4600-9d12-d9536e8b7d00 Correlation ID: be4b9a32-3f25-4710-8bd7-f45478e163c3 Timestamp: 2024-08-23 12:43:18Z
    at OAuth2Strategy.parseErrorResponse (/home/bluetguser/node_modules/passport-oauth2/lib/strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (/home/bluetguser/node_modules/passport-oauth2/lib/strategy.js:420:16)
    at /home/bluetguser/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/bluetguser/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:196:18
    at passBackControl (/home/bluetguser/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/bluetguser/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)


-------- 8/23/2024, 2:09:12 PM ---- 1.1.27 --------

(node:1082) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead


-------- 8/23/2024, 2:15:53 PM ---- 1.1.27 --------

(node:1114) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 2:46:14 PM ---- 1.1.27 --------

(node:3522) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 2:46:57 PM ---- 1.1.27 --------

(node:1112) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 2:48:45 PM ---- 1.1.27 --------

(node:1117) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 2:51:01 PM ---- 1.1.27 --------

(node:2790) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:26:34 PM ---- 1.1.27 --------

(node:6401) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:30:06 PM ---- 1.1.27 --------

(node:7814) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:36:21 PM ---- 1.1.27 --------

(node:10214) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:38:32 PM ---- 1.1.27 --------

(node:11076) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:40:59 PM ---- 1.1.27 --------

(node:12042) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


-------- 8/23/2024, 3:51:30 PM ---- 1.1.27 --------

(node:16025) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by sotoloaizamiguel** [comment]
These node modules should all be bluetecuser owner and group, right?

![Screenshot 2024-08-23 121709](https://github.com/user-attachments/assets/138daee0-bf8e-410e-a950-0748e9c0eeee)

**Comment by si458** [comment]
You should always install meshcentral with a normal user and then run meshcentral with a normal user,
But I don't think this is the issue why u see groups but no devices.
Have u checked ur database and the tables make sure the is data inside it?

**Comment by sotoloaizamiguel** [comment]
I installed again meshcentral, the socket error is gone. But I can't see any device. In the events show the device group and name.
![Screenshot 2024-08-23 141812](https://github.com/user-attachments/assets/ebfd89b7-0e85-440c-b945-f3ba4f410150)

**Comment by si458** [comment]
Have u checked the user permissions?

**Comment by sotoloaizamiguel** [comment]
The database show data inside
![Screenshot 2024-08-23 143350](https://github.com/user-attachments/assets/6e21369c-1656-4b66-b8f2-7446c5c5dec2)

**Comment by sotoloaizamiguel** [comment]
The permissions are ok.

![Screenshot 2024-08-23 143647](https://github.com/user-attachments/assets/359b3734-6f69-46d6-aab0-871801b42bb4)

**Comment by sotoloaizamiguel** [comment]
The system show 333 Agent sesions, and when I press show server configuration link, the system show a server disconnected, click to reconnect message.

![Screenshot 2024-08-23 143847](https://github.com/user-attachments/assets/0b835246-9267-4b67-bd0e-4001ecfcf1ad)

![Screenshot 2024-08-23 143900](https://github.com/user-attachments/assets/78cb6bbd-714b-4af6-a60a-c868144280f0)

**Comment by si458** [comment]
If u click ur user in the user permission bit, does it list all groups etc ok?

**Comment by si458** [comment]
The disconnect message is generally the server crashing and restarting? But I'm sure u showed us the server error log before and didn't show anything?
I'm not 100% sure without physical access to ur server to help, if u want, email me (check my github profile page) and I'll connect in and have a look :)

**Comment by sotoloaizamiguel** [comment]
email sent

**Comment by si458** [comment]
ok so this issue has been resolved https://github.com/Ylianst/MeshCentral/commit/21e196e35c32d65325414bd2702424ffec74c825
it appears mongodb can randomly at times decide data inside its database ISNT UTF-8 even tho it is?
so to avoid this, we set `enableUtf8Validation: false` in the mongodb driver so it can carry on instead of errors out
and returning no data at all
