### ISSUE TITLE
OIDC Client fails to verify JWT token. Internal Server Error

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6345]
**Describe the bug**
The bug is failing to be able to connect using OIDC general connect setup. We've setup a config with the required fields and it does call our second device for authentication, however when returning to meshcentral, the JWT is put into a JSON.parse() function which errors out.

**To Reproduce**
Try to login usin Entrust OpenID Connect.

**Expected behavior**
Log into my account succesfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/066f0f98-d12f-4e70-8841-5f43bbe4a4fe)

I converted the Byte array to a string and printed it: below. But normally the bytecode is passed directly to JSON.parse() function.
```
eyJ4NXQiOiI4ajJuMmMzcmpvM0pzanY3ZkJNckVsbUNlSFkiLCJraWQiOiI3MjE1MTQ5MCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJkc2VsZW5Ac3lzdGVtZWMubmwiLCJhdWQiOiJkYTQ5NTEzYi04YjBlLTRlZmEtYWE0Yi0zMzY3YWQ2ZGM2ZmMiLCJuYW1lIjoiRGFhbiBTZWxlbiIsImlzcyI6Imh0dHBzOi8vc2lzbmwuZGUudHJ1c3RlZGF1dGguY29tL2FwaS9vaWRjIiwiZ2l2ZW5fbmFtZSI6IkRhYW4iLCJmYW1pb... rest of jwt
Aug 28 13:41:02 thoth node[441762]: ERR: SyntaxError: Unexpected token e in JSON at position 0
Aug 28 13:41:02 thoth node[441762]:     at JSON.parse (<anonymous>)
Aug 28 13:41:02 thoth node[441762]:     at Client.userinfo (/opt/meshcentral/app/node_modules/openid-client/lib/client.js:1292:16)
Aug 28 13:41:02 thoth node[441762]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Aug 28 13:41:02 thoth node[441762]:     at async /opt/meshcentral/app/node_modules/openid-client/lib/passport_strategy.js:182:24
```

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: ESXi

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: WIndows
 - Network: Meshcentral over WAN
 - Browser: Brave

**Additional context**

**Your config.json file** relevant info:
```
"authStrategies": {
          "oidc": {
              "issuer": {
                  "issuer": "https://domain.com/api/oidc",
                  "authorization_endpoint": "https://domain.com/api/oidc/authorize",
                  "token_endpoint": "https://domain.com/api/oidc/token",
                  "endsession_endpoint": "https://domain.com/api/oidc/endsession",
                  "jwks_uri": "https://domain.com/api/oidc/jwks"
              },
              "client": {
                  "client_id": "<clientid>",
                  "client_secret": "<cliensecret>",
                  "redirect_uri": "https://remote.domain.com/auth-oidc-callback",
                  "_post_logout_redirect_uri": "https://remote.domain.com/login",
                  "_token_endpoint_auth_method": "client_secret_basic",
                  "_response_types": "authorization_code"
              },
              "custom": {
                  "scope": [ "openid", "profile", "read.EmailAlias" ],
                  "preset": null
              },
              "logouturl": "https://remote.domain.com/logout",
              "newAccounts": false
          }
      }
```

**Comment by si458** [comment]
you didnt specify what verison of meshcentral you are running

**Comment by DaanSelen** [comment]
> you didnt specify what verison of meshcentral you are running or what nodejs version you are using

Excuse me, of course!

![image](https://github.com/user-attachments/assets/5e0b2da9-b142-4088-a9b1-bdffd0874245)
With Node version: v18.19.0

**Comment by si458** [comment]
what is ur oidc provider as im not having issue here?
also have you tried removing the "custom" value incase its that?

**Comment by DaanSelen** [comment]
> what is ur oidc provider as im not having issue here?
> also have you tried removing the "custom" value incase its that?

We use Entrust OIDC

**Comment by si458** [comment]
is this still an issue?
is it possible for you to email myself and let me test with your environment?

**Comment by si458** [comment]
just wanted to update this issue for others in the future
after investigating, you only to do the following:
1. set `issuer`, `client_id` and `client_secret` as normal
2. set the redirect uri in entrust to `https://meshcentral.myserver.com/auth-oidc-callback`
3. change `Authorization Code PKCE Code Challenge` to `S256` in your entrust web ui
4. set the scopes `"openid profile email"` in your entrust web ui
5. you must then ALSO set EITHER A or B (NOT BOTH!)
a. `"userinfo_signed_response_alg": "RS256"` inside of `client` in your config.json
b.  set `userinfo signing algorithm` in the entrust web ui to `NONE`
