### ISSUE TITLE
System can't wake up from modern standby via Custom Power Action of SOL in MeshCommander.

### ISSUE THREAD

**Issue by JoshuaSYChang** [Ylianst/MeshCentral#635]
Hi Ylian,

Need your help to also add the option  "OS Wake from Standby" in Custom Power Action of SOL. Many thanks.

![BITS435887](https://user-images.githubusercontent.com/25002787/68314516-3edcd680-00f1-11ea-86a7-e7ad4bed9fa5.jpg)

Best regards,
Joshua

**Comment by MailYouLater** [comment]
Related: #605
(I'd say possible duplicate, but both issues were opened by the same person, and this one was opened after that one was closed, so either this is a continuation from the point where #605 left off, or there was a regression.)

**Comment by Ylianst** [comment]
This is a correct issue. I added the new feature in the "quick" dialog, but not in the "custom" dialog. I will add that when I get back. I will be back coding Nov 13th, then travel again Nov 18th to 22th. After that, I should be pretty much working on this for the next two months non stop.

**Comment by Ylianst** [comment]
Published [MeshCommander v0.8.0](https://www.meshcommander.com/meshcommander) with a fix for this. Let me know if it works for you.

**Comment by JoshuaSYChang** [comment]
Confirmed MeshCommander v0.8.0 fix. Many thanks.!
