### ISSUE TITLE
Left mouse button not triggering in remote desktop

### ISSUE THREAD

**Issue by ijustw0rkhere** [Ylianst/MeshCentral#6351]
**Describe the bug**
Left mouse button clicks are not recognized in a remote control session when "event.which", within agent-desktop-0.0.2.js, isn't used to detect the mouse button. It falls back to using "event.button", on line 578 of agent-desktop-0.0.2.js, to determine the mouse button, but the logic is faulty. "event.button" returns 0 for a left mouse button click and "else if (event.button)" on line 578 in agent-desktop-0.0.2.js does not return true for a value of 0, therefore ignoring left mouse button clicks.

**To Reproduce**
use "event.button" to determine mouse clicks rather than "event.which"

**Expected behavior**
left mouse buttons are recognized when in a remote desktop session

**Screenshots**
```
if (Action == obj.KeyAction.UP || Action == obj.KeyAction.DOWN) {
    if (event.which) {
        ((event.which == 1) ? (Button = obj.MouseButton.LEFT) : ((event.which == 2) ? (Button = obj.MouseButton.MIDDLE) : (Button = obj.MouseButton.RIGHT)));
    } else if (event.button) { 
        ((event.button == 0) ? (Button = obj.MouseButton.LEFT) : ((event.button == 1) ? (Button = obj.MouseButton.MIDDLE) : (Button = obj.MouseButton.RIGHT)));
    }
}
```

**Additional context**
Attempting to write a custom UI in react and the mouse click event doesn't pass the "which" property. This causes agent-desktop-0.0.2.js to use the mouse click event's "button" property to determine the mouse button, but has flawed logic.

**Comment by si458** [comment]
Indeed it seems `event.which` is deprecated

https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which

So will have a look next week to say use `event.which` but if not there use `event.button` instead

Thanks for spotting!

**Comment by ijustw0rkhere** [comment]
To clarify, that logic does exit but it doesn't trigger on a left mouse button click which returns a 0.

**Comment by ijustw0rkhere** [comment]
No worries, i had implemented my own fix of `if (event.button != null)` in the meantime to get by. 

I've tested your logic of `if (typeof event.button == 'number')` and it works for me as well.

**Comment by si458** [comment]
great! thank you! have pushed my fix https://github.com/Ylianst/MeshCentral/commit/d2e4f12ea3d6d52e49580db227efb475edb9d4a1
i did it of `typeof` just incase `event.button` passes as maybe a string or something else other than a number
this way it makes sure its a number and will work as the docs say it should always be a number anyways
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
