### ISSUE TITLE
MeshCentral Service can no longer be started!!

### ISSUE THREAD

**Issue by tobias9931** [Ylianst/MeshCentral#6352]
**Describe the bug**
After the automatic restart of the Windows Server, the MeshCentral service can no longer be started!
We have not changed anything in MeshCentral.
Please help.

"C:\Program Files\Open Source\MeshCentral\meshcentral-data\mesherrors.txt"

```
-------- 9/1/2024, 10:25:03 PM ---- 1.1.24 --------

node:fs:1688
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat 'C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\agents\MeshCentralAssistant.exe'
    at Object.statSync (node:fs:1688:3)
    at module.exports.hashExecutableFile (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\exeHandler.js:264:79)
    at CreateMeshCentralServer.obj.updateMeshTools (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:2917:32)
    at CreateMeshCentralServer.obj.StartEx4 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1700:13)
    at CreateMeshCentralServer.obj.StartEx3 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1676:17)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1588:21
    at obj.GetMeshServerCertificate (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\certoperations.js:1091:38)
    at CreateMeshCentralServer.obj.StartEx2 (C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1585:35)
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1577:21
    at C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\db.js:2818:25 {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Program Files\\Open Source\\MeshCentral\\node_modules\\meshcentral\\agents\\MeshCentralAssistant.exe'
}

Node.js v18.19.0

```

**Server Software (please complete the following information):**
 - OS: Windows Server 2022
 - Version: 1.1.24
 - Node: 18.19.0

**Comment by si458** [comment]
have you checked if the file
`C:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\agents\MeshCentralAssistant.exe` exists? 
because it thinks it doesnt

you also havent included your config.json (please share)

so im guessing it tried to do an auto upgrade when you restarted your machine and it goofed up
as you are on 1.1.24 and the latest is 1.1.27

**Comment by tobias9931** [comment]
![grafik](https://github.com/user-attachments/assets/299d4815-b39a-4c60-a18c-9a363b502f60)

Yes there ist no MeshCentralAssistant.exe 
But we haven't changed anything here in the last few days.

Is it possible to deactivate the automatic update?
The server VM has no internet connection

**Comment by si458** [comment]
Again u haven't shared ur config.json so it might already be set
But generally it's `selfupdate: false` under settings in config.json

One way to fix it is
1. Stop meshcentral service
2. `cd meshcentralfolder` the root folder containing the meshcentral-data, meahcentral-backups, etc
3. `npm install meshcentral@1.1.24`
4. restart meshcentral service

**Comment by tobias9931** [comment]
I have added the MeshCentralAssistant.exe manually.
But now the service can no longer be started at all:
![grafik](https://github.com/user-attachments/assets/49b4edd4-e610-4e3c-923c-ed59fce785dd)
No new entries are created in the file “C:\Program Files\Open Source\MeshCentral\meshcentral-data\mesherrors.txt”.
![grafik](https://github.com/user-attachments/assets/e025b4b9-d984-4529-b861-16755c5846bf)

I'll give the server an internet connection tomorrow.
Then MeshCentral should update itself automatically or

selfupdate: false was not set

Thank you for your very quick answers

**Comment by si458** [comment]
U haven't followed my steps above!
The is something wrong with ur setup!
So do as I explained above and make sure ur in the root folder of meshcentral when you run it!

**Comment by tobias9931** [comment]
I will try it tomorrow morning because for npm install meshcentral@1.1.24 I also need an internet connection and I currently don't have one on the machine

**Comment by si458** [comment]
> I will try it tomorrow morning because for npm install meshcentral@1.1.24 I also need an internet connection and I currently don't have one on the machine

No worries you can use `npm install meshcentral@1.1.24` to install the same version u had
OR
Use `npm install meshcentral`, and it will install the latest version 1.1.27

**Comment by tobias9931** [comment]
Thank you very much for your support @si458 
Do I have to save the config.json beforehand and will I lose my devices?
Or does this behave like an update?

I'm surprised that he tried to do an update and a few things got broken.
The server should actually be completely isolated and has no internet connection to see that a new version is available.

**Comment by si458** [comment]
> Thank you very much for your support @si458 
> Do I have to save the config.json beforehand and will I lose my devices?
> Or does this behave like an update?
> 
> I'm surprised that he tried to do an update and a few things got broken.
> The server should actually be completely isolated and has no internet connection to see that a new version is available.

No running the `npm install` won't effect any of ur data

If u have already replaced the .exe file
One thing to check is the service logs not meshlogs

Look in meshcentral\winservice\ folder for text files
I can't remember what files are there

**Comment by tobias9931** [comment]
C:\Program Files\Open Source\MeshCentral>npm install meshcentral@1.1.24

up to date, audited 237 packages in 2s

35 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 2 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Program Files\Open Source\MeshCentral>

Doesn't changed anything :(

**Comment by tobias9931** [comment]
C:\Program Files\Open Source\MeshCentral>npm install meshcentral

changed 2 packages, and audited 237 packages in 11s

35 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (1 moderate, 1 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Program Files\Open Source\MeshCentral>

MeshCentralAssistant.exe is now here. But Service don't start anyways

**Comment by tobias9931** [comment]
"C:\Program Files\Open Source\MeshCentral\winservice\daemon\meshcentral.wrapper.log"

2024-09-02 08:15:53 - Starting C:\Program Files\nodejs\node.exe  --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined
2024-09-02 08:15:53 - Started 4960
2024-09-02 08:20:21 - Starting C:\Program Files\nodejs\node.exe  --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined
2024-09-02 08:20:21 - Started 6788
2024-09-02 09:08:36 - Starting C:\Program Files\nodejs\node.exe  --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined
2024-09-02 09:08:36 - Started 2572
2024-09-02 09:10:53 - Starting C:\Program Files\nodejs\node.exe  --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined
2024-09-02 09:10:53 - Started 4412

Looks ok I think

**Comment by si458** [comment]
@tobias9931 what other log files are inside `C:\Program Files\Open Source\MeshCentral\winservice\daemon\`
And there output?

**Comment by tobias9931** [comment]
![image](https://github.com/user-attachments/assets/94035b42-92b2-4867-9b19-3e8f3bccf80b)

**Comment by tobias9931** [comment]
> "C:\Program Files\Open Source\MeshCentral\winservice\daemon\meshcentral.wrapper.log"
> 
> 2024-09-02 08:15:53 - Starting C:\Program Files\nodejs\node.exe --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined 2024-09-02 08:15:53 - Started 4960 2024-09-02 08:20:21 - Starting C:\Program Files\nodejs\node.exe --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined 2024-09-02 08:20:21 - Started 6788 2024-09-02 09:08:36 - Starting C:\Program Files\nodejs\node.exe --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined 2024-09-02 09:08:36 - Started 2572 2024-09-02 09:10:53 - Starting C:\Program Files\nodejs\node.exe --harmony "C:\Program Files\Open Source\MeshCentral\node_modules\node-windows\lib\wrapper.js" --file "C:\Program Files\Open Source\MeshCentral\winservice\winservice.js" --log "MeshCentral wrapper" --grow 0.5 --wait 2 --maxrestarts 3 --abortonerror n --stopparentfirst undefined 2024-09-02 09:10:53 - Started 4412
> 
> Looks ok I think

Cant find an error here

**Comment by tobias9931** [comment]
I could try to perform a restore of the machine.
Before the server restart at the weekend.

**Comment by si458** [comment]
You might need to uninstall the service then install again `node node_modules\meshcentral --uninstall` `--install`

**Comment by tobias9931** [comment]
However, I am still confused as to why the MeshCentralAssistant.exe was suddenly removed.
The server has been running productively for over 3 months and there have never been any problems.

selfupdate: false was not previously in the config.
I have now added it

**Comment by si458** [comment]
It might be it could finally update for a split second, so it took the chance! 
Which then, in turn, goofed things up!
And the service was also broken so normally an uninstall_install of the service fixes the issue
Happened to someone else only the other day
