### ISSUE TITLE
need to update/replace inflight and glob modules?

### ISSUE THREAD

**Issue by silversword411** [Ylianst/MeshCentral#6357]
Are there some issues that need to be checked for inflight and glob modules?

```
Updating meshcentral from 1.1.21 to 1.1.21
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by si458** [comment]
We dont use those module.
Chances are the is other modules that might use them
So see what modules u have installed and then find the ones that use them
And then we can see if we can upgrade/replace them

**Comment by si458** [comment]
inflight:
```
meshcentral@1.1.27 /home/simon/meshcentral/MeshCentral
├─┬ archiver-zip-encrypted@1.0.11
│ └─┬ archiver-utils@2.1.0
│   └─┬ glob@7.2.3
│     └── inflight@1.0.6 deduped
├─┬ express-handlebars@5.3.5
│ └─┬ glob@7.2.3
│   └── inflight@1.0.6
└─┬ minify-js@0.0.4
  └─┬ dir_cache@1.0.3
    └─┬ minify-js@0.0.2
      ├─┬ babel-cli@6.26.0
      │ └─┬ glob@7.2.3
      │   └── inflight@1.0.6 deduped
      ├─┬ grunt-jsdoc-to-markdown@1.2.1
      │ └─┬ jsdoc-to-markdown@1.3.9
      │   ├─┬ dmd@1.4.2
      │   │ └─┬ file-set@1.1.2
      │   │   └─┬ glob@7.2.3
      │   │     └── inflight@1.0.6 deduped
      │   └─┬ jsdoc-parse@1.2.7
      │     └─┬ file-set@0.2.8
      │       └─┬ glob@4.5.3
      │         └── inflight@1.0.6 deduped
      └─┬ grunt@1.6.1
        └─┬ glob@7.1.7
          └── inflight@1.0.6 deduped
```

glob:
```
meshcentral@1.1.27 /home/simon/meshcentral/MeshCentral
├─┬ archiver-zip-encrypted@1.0.11
│ ├─┬ archiver-utils@2.1.0
│ │ └── glob@7.2.3
│ └─┬ zip-stream@4.1.1
│   └─┬ archiver-utils@3.0.4
│     └── glob@7.2.3 deduped
├─┬ archiver@7.0.0
│ └─┬ archiver-utils@5.0.2
│   └── glob@10.4.1
├─┬ express-handlebars@5.3.5
│ └── glob@7.2.3
└─┬ minify-js@0.0.4
  └─┬ dir_cache@1.0.3
    └─┬ minify-js@0.0.2
      ├─┬ babel-cli@6.26.0
      │ └── glob@7.2.3
      ├─┬ grunt-jsdoc-to-markdown@1.2.1
      │ └─┬ jsdoc-to-markdown@1.3.9
      │   ├─┬ dmd@1.4.2
      │   │ └─┬ file-set@1.1.2
      │   │   └── glob@7.2.3
      │   └─┬ jsdoc-parse@1.2.7
      │     └─┬ file-set@0.2.8
      │       └── glob@4.5.3
      └─┬ grunt@1.6.1
        └── glob@7.1.7
```

**Comment by si458** [comment]
`archiver-zip-encrypted` can be upgraded to `2.0.0` which will upgrade `glob` and `inflight`

`archiver` can only go up 1 more to `7.0.1` but its currently safe as glob is already >= 9

`express-handlebars` could be upgraded to `7.1.3` but not `8.x.x` because 8 has a min requirement of node 20!
and we have at least 16 set as our min and i know from posts etc people are still using 18 

`minify-js` can be ignored because its only installed on development machines when doing translate/minify
normal `npm install` methods dont install dev packages unless you ask for it

**Comment by tobias9931** [comment]
> `express-handlebars` could be upgraded to `7.1.3` but not `8.x.x` because 8 has a min requirement of node 20! and we have at least 16 set as our min and i know from posts etc people are still using 18
> 

We are using Node.js v18.19.0 because in MeshCentralInstaller.exe is this version of Node included

**Comment by si458** [comment]
@tobias9931 that's OK :)
The meshcentralinstaller was updated beginning of the year when node 18 was LTS, but now node 20 has become the LTS, but 18 is still supported :)

**Comment by si458** [comment]
1.1.30 released which updated `archiver, archiver-zip-encrypted, body-parser, express`

**Comment by silversword411** [comment]
Might as well close :)

**Comment by si458** [comment]
Was just looking at this, and checking express-handlevars was all working then I can upgrade that package too :)

**Comment by silversword411** [comment]
Oh, there's still one to update: `express-handlevars`

**Comment by si458** [comment]
`express-handlebars` i cant spell haha

**Comment by si458** [comment]
all done :)
