### ISSUE TITLE
editing windows text files in files web ui, generates new lines as linux lines

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentral#6365]
**Describe the bug**
when editing a windows text file in the file UI,
when you save it appears to be saving the new lines as linux new lines?

**To Reproduce**
1. create windows text file using notepad++ (enable `show end of line`)
2. file is created with windows end of lines
3. edit the text file in the web ui of meshcentral,
4. recheck file on windows machine in notepad++
5. end of lines now show as linux new lines instead?

**Expected behavior**
file should be saved as is with new lines intact

**Screenshots**

**Server Software (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 22.04
 - Virtualization: [e.g. Docker] KVM (Proxmox)
 - Network: [e.g. LAN/WAN, reverse proxy, cloudflare, ssl offload, etc...] Hybrid
 - Version: [e.g. 1.0.43] 1.1.27
 - Node: [e.g. 18.4.0] 18.20.3

**Client Device (please complete the following information):**
 - Device: [e.g. Laptop] Laptop
 - OS: [e.g. Ubuntu] Mac OSX
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Browser: [e.g. Google Chrome] Firefox/Chrome/Safari
 - MeshCentralRouter Version: [if applicable] N/A

**Remote Device (please complete the following information):**
 - Device: [e.g. Laptop] Computer
 - OS: [e.g. Windows 10 21H2] Windows 10
 - Network: [e.g. Local to Meshcentral, Remote over WAN] WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`] Dean Chappell

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "_cert": "myserver.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by PathfinderNetworks** [comment]
I just tested this as I'm running MeshCentral on a Windows Server (Server 2022 VM).  Under my Windows Server version it's not changing the end of lines.  When I edit the file directly with Notepad++ it adds a LF.  When I edit that same file in the MeshCentral WEB GUI file editor it also adds a LF when viewing the resulting edit in Notepad++

So must just be something coming from running MeshCentral under Linux?

**Comment by si458** [comment]
If u use normal notepad and write something, then open it inside notepad++ u can see its CR LF

But if u then edit it in the webui. It then saves back to LF

I'm in the process of adding in the option in the Web ui in the edit to let u change the line breaks between windows/mac/linux :)

Our custom software looks for cr lf and when I edit in the ui, it's saving as lf which then goofs up our custom software haha

**Comment by si458** [comment]
When u copy the data into text area it changes \r\n to just \n

Which then in turn when u save the file is using \n instead of the original \r\n

**Comment by PathfinderNetworks** [comment]
You are right, I do see that now.  It removes the carriage return (CR) even under my Windows Server version.

**Comment by si458** [comment]
I was going to get it default to whatever OS the remote device was running originally
OR
If the text file contained \r\n then just use windows

Then, I decided, no, let u the end user pick but default to windows :)

then it will just replace \n with \r\n or \n or \r 

Depending on what u wanted to use!

**Comment by si458** [comment]
all done!  https://github.com/Ylianst/MeshCentral/commit/6fe30b7730fbdb7e4e285d91ec54b8a6fa9c5ce1
![Screenshot 2024-09-08 at 20-12-29 DESKTOP-LTSAD3V - myothergroup - MyRemoteAgent](https://github.com/user-attachments/assets/2e8e203f-b964-47d7-8be0-41678e9aad32)
![Screenshot 2024-09-08 at 20-12-20 DESKTOP-LTSAD3V - myothergroup - MyRemoteAgent](https://github.com/user-attachments/assets/721e388b-d546-4c77-816c-c6347fe7205c)
![Screenshot 2024-09-08 at 20-12-12 DESKTOP-LTSAD3V - myothergroup - MyRemoteAgent](https://github.com/user-attachments/assets/f4159718-e6f0-43f8-b4f6-77477417416e)

you can now specify what line break to use before saving, and it remembers in your browser/session too!
