### ISSUE TITLE
Remove the www from the www.meshcentral.com link on the About section of the readme.md (line 15)

### ISSUE THREAD

**Issue by Catsrules** [Ylianst/MeshCentral#6366]
Super minor issue. 

The about section has https://www.meshcentral.com as a link. When I use that link I get a certificate error. I believe the link should be https://meshcentral.com instead of  https://www.meshcentral.com.

https://github.com/Ylianst/MeshCentral/blob/390991123a566aba8b8c380b952c4e65c009396f/readme.md?plain=1#L15

I have seen a few people online confused thinking the website it down. I am guessing this is partially the reason. 
 
Thanks everyone for an amazing project. 

All of the other links on the readme look to be correct and functional.

**Comment by si458** [comment]
All fixed for you! 
https://github.com/Ylianst/MeshCentral/commit/516a14b4ca289ca1500a7e5d1fd99a19e5cce207
