### ISSUE TITLE
group select via g:group in search box : "connect all " connect all in every group

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#637]
Seems to be a new behavior, don't remember in witch version it started...

1/ filter g:mygroup in tab view
2/  I click  "select all" 
3/ click desktop view : see all these black screen looking at me...
4/ then click "connect all" 

It connects all computers in all group... with a pop-up "are you sure you want tp connect to 122 devices.."

Nope..

server 0.4.3.w on firefox. Same on chrome.

**Comment by Ylianst** [comment]
Oh, good bug report. I am traveling now. Back November 13th and traveling again Nov 18th to 23rd. I will try to take a look at this when I can.

**Comment by si458** [comment]
the steps you give are the intended steps and its how it works here so not sure why its a bug?
