### ISSUE TITLE
Windows Desktop cannot input Chinese

### ISSUE THREAD

**Issue by raultang** [Ylianst/MeshCentral#6373]
**Describe the bug**
I am managing proxmox virtual machine via MeshCentral. 
Windows desktop can not input Chinese with keyboard, tried to change the system input method has not effect. But proxmox web vnc works fine.

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: KVM
 - Network: LAN/WAN, reverse proxy, ssl offload (I tried default https with no ssl and nginx  with ssl offload two environment)
 - Version: 1.1.27
 - Node: v22.6.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: MacOS
 - Network: Local to Meshcentral, Remote over WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
 - Device: Promox VM
 - OS: Windows 10 21H2
 - Network: Local to Meshcentral, Remote over WAN
 - Current Core Version (if known): Current Core: Dec 9 2022, 3451659882

**Your config.json file**
Default config file

Appreciate any advice.

**Comment by raultang** [comment]
ok, Remote Keyboard Map option is the switch.

**Comment by si458** [comment]
Sorry for delay! Totally missed this issue!
Yes under settings is an option saying remote keyboard map, tick this :)
