### ISSUE TITLE
Cant choose different device group when adding device to user after upgrade to version 1.1.29

### ISSUE THREAD

**Issue by demkr** [Ylianst/MeshCentral#6374]
After upgrading to version 1.1.29 I cannot choose (from drop down menu)  different device groups and therefore different device under specific group, when I want to add device within specific user menu. I tried in different browsers and it is the same result. The only group available under drop down menu is last group created.

To reproduce
1. Go to My users > users tab
2. Click on specific user you want to add device to it
3. Under that user menu, click on Add device (the last option)
4. Under device group dropdown menu there is only one device group (i have many of them)

Expected behavior
Under device group, there should be listed all configured device groups. 

Server Software:
 - OS: Ubuntu 22.04.4
 - MeshCentralVersion: 1.1.29
 - Node: 20.10

**Comment by si458** [comment]
i dont have any issues here? 
<img width="425" alt="image" src="https://github.com/user-attachments/assets/662b5916-42eb-4d08-ad88-dd6f69339493">
can you share your config.json?
is your user an admin user?
do you have permission set on your user?

**Comment by demkr** [comment]
This is my screenshot of device group

![image](https://github.com/user-attachments/assets/6c3e8bab-b44f-4de4-8d30-80194c1b595c)

And this is my dropdown menu, when i want to choose device from device group under user settings

![image](https://github.com/user-attachments/assets/86b258d2-3f5a-4794-8017-4413199160e7)

Which part of json config do you need to have.

**Comment by si458** [comment]
thats weird? we havent changed anything code wise for the groups?

you could try rolling back your setup to a different version
1. stop meshcentral `systemctl stop meshcentral`
2. `cd /folder/to/meshcentral`
3. `npm install meshcentral@1.1.25` (im guessing 1.1.25 you dont say what version you was on before the upgrade)
4. start meshcentral `systemctl start meshcentral`

remember BACKUPS BACKUPS BACKUPS!

also all of your config.json is needed to help see if its maybe a config.json issue,
just hide secret things like users/passwords from inside it

**Comment by demkr** [comment]
I noticed that every new group that I made since, It is listed under drop down menu. Is there any way to refresh device groups, or I have to delete them and create again.

**Comment by demkr** [comment]
Hi Simon

I figured out what the problem was. The problem is that only groups that I am the creator of are listed. Not related to the MeshCentral version. When I upgraded my MeshCentral server, I also changed the server access and admin account.

But still. I think if a user has full admin rights, they should have device group visibility when managing a new user, regardless of whether the device group was created by another admin user.

**Comment by si458** [comment]
@demkr this already exists in config.json
manageCrossDomain
manageAllDeviceGroups
![Screenshot_20240917_085053_Firefox](https://github.com/user-attachments/assets/e1c83038-f75b-4fd0-99fb-c0329bfb5f6f)

**Comment by demkr** [comment]
Thank you Simon, but I think this is not what I mean. I don't have problems with managing device groups. I authorize users to access device groups under My Account and User Authorization under specific Device group.

But anyway I tried with your configuration, but without luck. I used syntax as

"manageAllDeviceGroups": [ "user//user1","user//user2" ],

and put this line under Settings and Under domain and still no Device groups have been shown from drop down menu under My Users > user > Add Device if user is not device group creator.

**Comment by si458** [comment]
@demkr if your happy to provide me with access to your hardware/setup
you can email myself and i can have a quick look (email on my github page)

**Comment by si458** [comment]
@demkr thank u, I did email u back, I need access to ur server really as I think it's a database issue sadly

**Comment by demkr** [comment]
It was not a bug it was just my configuration. The problem was in old versions of *.handlebars files. My *.handlebars files were not updated with new releases, because they were in meshcentral-web directory.
