### ISSUE TITLE
icon association according to architecture

### ISSUE THREAD

**Issue by Smiley-k** [Ylianst/MeshCentral#6377]
Please tell me if it is possible to somehow perform an association to the architecture of icons? (for example, if it's windows. server then there will be icon 2, if it is a plan then icon 3 would be applied automatically) this will greatly simplify the work in the interface with objects.

**Comment by si458** [comment]
this is already sorta asked here https://github.com/Ylianst/MeshCentral/issues/1695
basically you want the device icons to show as OS icons or add the OS icons somewhere dont you?

**Comment by si458** [comment]
ok so ill close this issue and follow in https://github.com/Ylianst/MeshCentral/issues/1695 for any updates in the future 👍
