### ISSUE TITLE
Virtual keyboard special characters not working

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#638]
Hi MeshCentral Team,

On Android 9+ the virtual keyboard closes when trying to use the keyboard to do symbols like @!%&^*+×♤₩°~. Any chance a symbol set button could be applied? Preventing password inputs on end point systems.

Thanks,
SomeGuru

**Comment by SomeGuru** [comment]
@Ylianst @si458 

Still an issue that seems to reside in the way Mesh handles the remote keys or even localized keys.

SomeGuru

**Comment by si458** [comment]
im not seeing this issue at all on my Z Fold 3 using firefox?
what browser are you using?
are you using the terminal tab or remote tab?

**Comment by SomeGuru** [comment]
Going to close this issue as its still present, but not a critical stopper. This happened on several browsers. It has to do with password fields and interpretation of them in the display. We have configurations of Windows 10/11, Ubuntu 22.04 - 23.04 with multiple browsers installed. 

-SomeGuru
