### ISSUE TITLE
The Desktop, Terminal, Files session does not close if you switch to another device, the problem is after upgrading to 1.1.29

### ISSUE THREAD

**Issue by sheshko-as** [Ylianst/MeshCentral#6382]
**Describe the bug**
1. Connect to your Desktop, terminal, or files
![1](https://github.com/user-attachments/assets/e6f4b8dd-ec11-43d1-9155-cdb9c49b13d2)
2. Without clicking the Disconnect button, you switch to another computer, the session remains from the previous computer
![2](https://github.com/user-attachments/assets/de517fe4-d82c-4bc0-9769-63b149576bfb)

Server Software (please complete the following information):

OS: Ubuntu 22.04
Virtualization: VPS
RAM: 16Gb
vCPU: 4 core 2,2 Ghz
SSD: 20 Gb
Network: WAN
Version: 1.1.29
Node: 20.x

Client Device (please complete the following information):
Device: PC
OS: Windows 10
Network: Remote over WAN
Browser: Google Chrome, Yandex, Opera GX
MeshCentralRouter Version: 1.8.9021
Remote Device (please complete the following information):

Device: PC
Quantity: 2000+ devices
OS: Windows 10 Pro - 22H2
Network: Remote over WAN
Current Core Version (if known): Dec 9 2022, 3840084365
Your config.json file

**Your config.json file**
```
{
  "settings": {
    "cert": "XXXXXX",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "autoBackup": {
      "backupIntervalHours": 24,
      "keepLastDaysBackup": 30,
      "zipPassword": "XXXXXX",
      "webdav": {
        "url": "XXXXXX",
        "username": "XXXXXX",
        "password": "XXXXXX",
        "folderName": "XXXXXX",
        "maxFiles": 30
      }
    }
  },
  "domains": {
    "": {
      "title": "XXXXXX",
      "title2": "XXXXXX",
      "hide": 5
    }
  },
  "letsencrypt": {
    "email": "XXXXXX@XXXXXX",
    "names": "XXXXXX",
    "production": true
  }
}
```

**Comment by si458** [comment]
Yes I discovered this after we did the release

It's already been fixed here https://github.com/Ylianst/MeshCentral/commit/21206b670ca54afede3f5c45a3c755d6ea146b9d

You can use the `master` docker image and the development version `npm install Ylianst/MeshCentral` 

Or 

Patch it yaself from the commit
