### ISSUE TITLE
Incorrect resolution when connecting

### ISSUE THREAD

**Issue by Pallaroid** [Ylianst/MeshCentral#6394]
**Describe the bug**
I connect normally and then everything is so small. I can't use some windows because they are simply too small. I just want to set a higher resolution. This was otherwise always displayed correctly automatically

**To Reproduce**
1. I connect normally to the Computer

**Expected behavior**
It should be a higher resolution so that I can see much more

**Screenshots**
![Screenshot 2024-09-20 074449](https://github.com/user-attachments/assets/1d1de53b-4b5f-486a-b70d-692635051c08)

Server Software (please complete the following information):

OS: Ubuntu
Virtualization: No
Network: WAN
Version: 1.1.30
Node: ?
Client Device (please complete the following information):

Device: Laptop / Computer
OS: Windows 11 64bit Home
Network: Lan (Reached the target/remote device by WAN)
Browser: ?
Remote Device (please complete the following information):

Device: Computer
OS: Microsoft Windows 11 Pro - 23H2/22631 64Bit
Network: WAN
Current Core Version: Dec 9 2022, 2871199060

**Additional context**

{
"$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
"comment1": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for >",
"comment2": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
"settings": {
"cert": "XXX",
"WANonly": true,
"_LANonly": true,
"_sessionKey": "MyReallySecretPassword1",
"port": 443,
"_aliasPort": 443,
"redirPort": 80,
"_redirAliasPort": 80
},
"domains": {
"": {
"title": "XXX Remote Management",
"footer": "XXX",
"_minify": true,
"_newAccounts": true,
"_userNameIsEmail": true,
"agentCustomization": {
"displayName": "XXX Remote Management",
"description": "XXX Remote Management",
"companyName": "XXX Remote Management",
"serviceName": "XXX",
"fileName": "XXX",
"image": "agent-logo.png",
"icon": "agent_icon.ico",
"installText": "XXX",
"_foregroundColor": "100,54,105",
"backgroundColor": "128,128,128"
}
}
},
"letsencrypt": {
"comment": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
"email": "XXX",
"names": "XXX",
"_skipChallengeVerification": true,
"production": true
},
"smtp": {
"host": "XXX",
"port": XXX,
"from": "XXX",
"user": "XXX",
"pass": "XXX",
"tls": false
}
}

**Comment by si458** [comment]
The remote tab just uses whatever resolution is on ur remote device.

This isn't anything to do with meshcentral

Do u not have a monitor connected to the remote device?

Just go into the windows settings and set a resolution 

As that pic looks like the default 800x600 when no monitor is connected

**Comment by Pallaroid** [comment]
It is not possible to set a resoltion because it is just a remote connection. The device does not have a monitor connected

**Comment by si458** [comment]
If u use the desktop tab and connect button (not rdp)

Just right click the desktop, then into display settings and set the screen resolution

This isn't a meshcentral issue

You need to maybe get a fake hdmi adapter so ur machine thinks the is a display plugged in

**Comment by si458** [comment]
If ur using rdp then it's not possible as it takes the resolution of ur Web browser

**Comment by Pallaroid** [comment]
When changing, I get the message that it is not possible to change the resolution in a remote session. I installed a virtual hdmi adapter. It worked for me. Thank you so much! :)

**Comment by si458** [comment]
@Pallaroid yes u cant change the resolution with an RDP session, but using a virtual hdmi adapter does the trick

**Comment by si458** [comment]
a side note, the was a bug just discovered where using any NON-ENGLISH web ui, the RDP canvas wasnt stretching to your screen correctly,
this has just been fixed here https://github.com/Ylianst/MeshCentral/issues/4701
