### ISSUE TITLE
Update the install documentation?

### ISSUE THREAD

**Issue by DaanSelen** [Ylianst/MeshCentral#6395]
Hi all, I was just wondering if the documentation on installing MeshCentral is still up to date? Following the searchable documentation, I ended up on a 404 page.

![image](https://github.com/user-attachments/assets/f4f26f5c-7aa1-4a3a-9f01-b82c4dfdd67c)
![image](https://github.com/user-attachments/assets/94cf6837-54e9-4e03-83f9-deff1fb02e91)

And following the Raspberry Pi documentation, it advises installing NodeJS version 8, which already gives a deprecation warning.
I just wanted to inform if this is by design.

**Comment by si458** [comment]
It depends where u got the link from to get the 404?
U shouod use the new docs instead https://ylianst.github.io/MeshCentral/
The community can even help us update it!
Check out the docs/docs folder in the git repo
