### ISSUE TITLE
Installing MeshCentral 1.1.30 causes loop for installing archiver@7.0.1

### ISSUE THREAD

**Issue by 4pack** [Ylianst/MeshCentral#6397]
**Describe the bug**
When installing MeshCentral 1.1.30 on Ubuntu 20.04 and NodeJS 20, causes a loop for Missing Module: archiver@7.0.1

NPM reports it as up to date and it is present in node_modules. MeshCentral is configured where it cannot run NPM itself.

MeshCentral 1.1.25 works perfectly fine.

**To Reproduce**
1. Configure MeshCentral to not be able to run NPM itself
2. npm install meshcentral@1.1.30
3. Manually install dependencies that MeshCentral requests
4. MeshCentral loops with Missing Module: archiver@7.0.1

**Expected behavior**
MeshCentral installs/upgrades successfully and detects the dependencies correctly.

**Server Software (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS 
 - Virtualization: LXC
 - Network: LAN/WAN, Traefik
 - Version: 1.1.30
 - Node: v20.17.0

**Client Device (please complete the following information):**
- N/A

**Remote Device (please complete the following information):**
- N/A

**Additional context**

**Your config.json file**
N/A

**Comment by si458** [comment]
Yes, this is because the release of 1.1.30 we forgot to change the package.json version!
We only changed it inside of meshcentral itself!
So a work around is too meshcentral
So a normal `npm install meshcentral`
Then do an `npm install archiver@7.0.1`
Then restart meshcentral

**Comment by 4pack** [comment]
Yeah, that's exactly what I did. It was part of the manual NPM dependency command, but the issue is that MeshCentral doesn't detect that it's actually installed.

![image](https://github.com/user-attachments/assets/f3613f52-280f-4607-a914-05e4f43a5bb6)

**Comment by 4pack** [comment]
And this is after fully deleting node_modules, package.json, and package-lock.json.

**Comment by si458** [comment]
@4pack that seems weird? i dont have that issue here?
whats the `testrun.sh` inside your screenshot? thats nothing we use?

**Comment by 4pack** [comment]
All ./testrun.sh does is checks permissions and runs meshcentral in debug mode.

```
#!/bin/sh

chown -R meshcentral:meshcentral /opt/meshcentral

cd /opt/meshcentral
sudo -u meshcentral NODE_EXTRA_CA_CERTS=/opt/meshcentral/rootca.crt node ./node_modules/meshcentral --debug
```

**Comment by si458** [comment]
are you running `npm install archiver@7.0.1` from within `/opt/meshcentral` also?

**Comment by 4pack** [comment]
Yes I am, and using the testrun script ensures that the file owners are correct.

**Comment by D4V3M0NK** [comment]
Seeing the same thing here ...

**Comment by D4V3M0NK** [comment]
As a follow up to this - I'd like to understand what can be done to revert back to a prior version of MC2. 

For example, I've renamed up my meshcentral-data/files and node_modules folders to *.old and then, with the existing version of node etc, used `npm install meshcentral@1.1.25` to revert back to a prior version. Starting up appears to work without issue, although I do need to register myself as an admin again. Makes sense.

Now that I have a working server, can I stop the service from running, simply rename my *.old folders back to their original names and then start the server again?

**Comment by si458** [comment]
ok ive just checked on my mac,
installing meshcentral and running installs archiver@7.0.1 cuz of the bug
but then stop and start and it tries again to install?
so the might be a bug with something so ill look into it

it doesnt effect anything, its just annoying that every time you stop meshcentral and start it (or restart)
it will attempt to install archiver again 🙄

**Comment by si458** [comment]
ok so to fix the bug,
1. stop meshcentral
2. remove archiver `npm remove archiver` from the root of your folder (`/opt/meshcentral` in some cases)
3. `cd node_modules/meshcentral/`
4. `npm install archiver@7.0.1`
5. start meshcentral

**Comment by si458** [comment]
@D4V3M0NK yeh I'm not sure why it does this, I've even debugged the code step by step watching it compare etc and even tho it goes OK u have 7.0.0 installed let me install 7.0.1, it then install 7.0.1. Then says nope still have 7.0.0 installed
Npm is really weird haha

**Comment by si458** [comment]
this has been fixed already here https://github.com/Ylianst/MeshCentral/commit/5fc3683ebb97ef52a1ed46087f550c22b27014a5
already fixed in the `master` docker image and will be fixed in the next release!
in the mean time the fix is as explained above https://github.com/Ylianst/MeshCentral/issues/6397#issuecomment-2364640540
but its nothing to panic over! it was a simple mistake
