### ISSUE TITLE
MeshAgent crashing on ClearLinux

### ISSUE THREAD

**Issue by nlyaple** [Ylianst/MeshCentral#64]
ClearLinux 4.19.12-674 x86_64, MeshAgent version 0.2.5.d crashes with the following information:

![image](https://user-images.githubusercontent.com/46327777/50607061-c8da6400-0e7c-11e9-953f-33effb2e3372.png)

This occurs on both a VirtualBox VM and a I5 NUC bare hardware install.  I have installed the Cryptography, network-basic, shells, desktop-dev, kernel-lts, ethtool, dev-utils, curl and c-basic bundles.

Any ideas would be greatly appreciated.
Thanks.

**Comment by nlyaple** [comment]
Excellent, Thanks!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.2.5-o with a fix for this. Let me know if it works.

**Comment by nlyaple** [comment]
How can I verify the agent version?  It still crashed but I want to double check the version.

**Comment by whalehub** [comment]
@nlyaple I believe that the server component is the one that was updated, not the agent component. You could still try to reinstall the MeshAgent to see if that resolves the issue.

**Comment by Ylianst** [comment]
Once the server is updated, all connecting agents will also be updated automatically. However, if the agent is in a really bad state, it will not be able to auto-update. This is the case here. It's crashing on start. Just delete the "meshagent.db" file and relaunch the agent. It will take on a new identity on the server, perform the auto-update and should work fine from now on.

You can delete the old device on the server using the "Delete Device" link on the bottom right on the device page.

**Comment by Ylianst** [comment]
I am going to close this one given that I pretty sure the issue reported above is fixed. If there is an old agent that crashes like this, it will not auto-update and so, re-installation of the agent is required.
