### ISSUE TITLE
Add RDP to context menu

### ISSUE THREAD

**Issue by MarkStephan89** [Ylianst/MeshCentral#6401]
hi, 
can you add the RDP option to the context menu?

![image](https://github.com/user-attachments/assets/8a1e0e5b-b6cf-47f8-bf6b-b957a7bf2461)

Thank you :)

**Comment by si458** [comment]
Do u mean for it to load up the desktop tab and click the rdp connect?

As the is already the Web-RDP which loads up the full screen rdp in your web browser

**Comment by MarkStephan89** [comment]
> Do u mean for it to load up the desktop tab and click the rdp connect?
> 
> As the is already the Web-RDP which loads up the full screen rdp in your web browser


I mean these RDP function: 

![image](https://github.com/user-attachments/assets/418a9bd5-27ad-45ee-98ef-754841c35f77)

**Comment by si458** [comment]
oh right! i dont have that link (mac user here)
but thats the link to automatically load up the meshcentralrouter and do its RDP
so its windows browsers only!
will have alook for you, should be easy enough 👍

**Comment by si458** [comment]
all done!
will be in `master` docker image in about 15mins
or the next release!
