### ISSUE TITLE
404 on link to public file

### ISSUE THREAD

**Issue by igorek00** [Ylianst/MeshCentral#6406]
**Describe the bug**
Error 404 when opening a link to a public file.

**To Reproduce**
1. upload file to My files / public 
2. Copy link
3. Pasted into the address bar of the browser
4. Press Enter
5. Got 404

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Debian 12
 - Virtualization: Proxmox CT
 - Network: WAN
 - Version: 1.1.30
 - Node: 18.19.0

**Client Device (please complete the following information):**
 - Device: PC, Phone ....
 - Browser: Firefox

**Additional context**
time, source, message
"18:38:43","webrequest","/login.asp (RedirServer)"
"18:38:41","webrequest","(X.X.X.X) /favicon-303x303.png"
"18:38:41","httpheaders","GET, /favicon-303x303.png, [object Object]"
"18:38:41","webrequest","(X.X.X.X) /images/login/back.png"
"18:38:41","httpheaders","GET, /images/login/back.png, [object Object]"
"18:38:41","webrequest","(X.X.X.X) /styles/style.css"
"18:38:41","httpheaders","GET, /styles/style.css, [object Object]"
"18:38:41","web","404 Error /loginuserfiles/mesh-admin/set.txt?download=1"
"18:38:41","webrequest","(X.X.X.X) /loginuserfiles/mesh-admin/set.txt?download=1"
"18:38:41","httpheaders","GET, /loginuserfiles/mesh-admin/set.txt?download=1, [object Object]"

**Your config.json file**
```
{
  "settings": {
    "_cert": "XXX.XXX.XXX",
    "_minify": false,
    "port": 443,
    "redirport": 80,
    "agentport": 443,
    "_webrtc": false,
    "Wanonly": true,
    "allowlogintoken": false,
    "plugins": {
      "enabled": false
    }
  },
    "domains": {
      "": {
        "Title": "XXXX",
        "newaccounts": false
      }      
    },
  "letsencrypt": {
    "email": "XXX@XXX.XXX",
    "names": "XXX.XXX.XXX",
    "rsaKeySize": 3072,
    "production": true
  }
}
```

**Comment by si458** [comment]
You don't have a cert value set as it's uncommented out `_cert` 

Try removing the comment and restarting and trying again

Also make sure u access ur meshcentral using the dns name u set in cert and letsencrypt

**Comment by igorek00** [comment]
_cert -> cert
restart
dns name, cert and letsencrypt are the same
nothing changed. 404

**Comment by igorek00** [comment]
generated link https://XXXXXX/**login**userfiles/mesh-admin/set.txt?download=1
must be https://XXXXXX/userfiles/mesh-admin/set.txt?download=1

**Comment by si458** [comment]
the bug is because your URL contains `/login`
if you remove this from your URL and then try the copy+paste, it works
will have a look, it will be a javascript bug!

**Comment by si458** [comment]
fixed for you!
will be in `master` docker image in about 15mins

**Comment by si458** [comment]
side note: ive just pushed another fix as this fix then broke public folder sharing for domains not using dns names
https://github.com/Ylianst/MeshCentral/commit/952bcde25f7e36f3c7a50b34e7991c44ae25f844
