### ISSUE TITLE
Feature Request: meshcmd AmtPower to reboot into ide-r

### ISSUE THREAD

**Issue by VietTPham** [Ylianst/MeshCentral#641]
I would like to request meshcmd AmtPower to have the ability to boot into ide-r.
Right now, I am attaching the ISO using meshcmd, and I have to manually open meshcommander to issue a reboot to ide-r to get it going.
I want to eventually use only meshcmd to reimage a computer from the linux command line, or via slack without having to open to meshcommander.
I tried to do wireshark to capture the meshcommander, and send it via ip/wsman but it did not work.
Here is the XML I was able to sniff out from meshcommander 

`<?xml version="1.0" encoding="utf-8"?><Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns="http://www.w3.org/2003/05/soap-envelope" ><Header><a:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/Put</a:Action><a:To>/wsman</a:To><w:ResourceURI>http://intel.com/wbem/wscim/1/amt-schema/1/AMT_BootSettingData</w:ResourceURI><a:MessageID>220</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><w:OperationTimeout>PT60.000S</w:OperationTimeout></Header><Body><r:AMT_BootSettingData xmlns:r="http://intel.com/wbem/wscim/1/amt-schema/1/AMT_BootSettingData"><r:BIOSPause>false</r:BIOSPause><r:BIOSSetup>false</r:BIOSSetup><r:BootMediaIndex>0</r:BootMediaIndex><r:ConfigurationDataReset>false</r:ConfigurationDataReset><r:ElementName>Intel(r) AMT Boot Configuration Settings</r:ElementName><r:EnforceSecureBoot>false</r:EnforceSecureBoot><r:FirmwareVerbosity>0</r:FirmwareVerbosity><r:ForcedProgressEvents>false</r:ForcedProgressEvents><r:IDERBootDevice>1</r:IDERBootDevice><r:InstanceID>Intel(r) AMT:BootSettingData 0</r:InstanceID><r:LockKeyboard>false</r:LockKeyboard><r:LockPowerButton>false</r:LockPowerButton><r:LockResetButton>false</r:LockResetButton><r:LockSleepButton>false</r:LockSleepButton><r:OwningEntity>Intel(r) AMT</r:OwningEntity><r:ReflashBIOS>false</r:ReflashBIOS><r:UseIDER>true</r:UseIDER><r:UseSOL>false</r:UseSOL><r:UseSafeMode>false</r:UseSafeMode><r:UserPasswordBypass>false</r:UserPasswordBypass></r:AMT_BootSettingData></Body></Envelope>`

**Comment by VietTPham** [comment]
Could you also make it reboot to pxeboot while you're at it
below is the xml code I sniff from wireshark when running meshcommander
`<?xml version="1.0" encoding="utf-8"?><Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns="http://www.w3.org/2003/05/soap-envelope" ><Header><a:Action>http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_BootConfigSetting/ChangeBootOrder</a:Action><a:To>/wsman</a:To><w:ResourceURI>http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_BootConfigSetting</w:ResourceURI><a:MessageID>219</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><w:OperationTimeout>PT60S</w:OperationTimeout></Header><Body><r:ChangeBootOrder_INPUT xmlns:r="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_BootConfigSetting"><r:Source><Address xmlns="http://schemas.xmlsoap.org/ws/2004/08/addressing">http://schemas.xmlsoap.org/ws/2004/08/addressing</Address><ReferenceParameters xmlns="http://schemas.xmlsoap.org/ws/2004/08/addressing"><ResourceURI xmlns="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_BootSourceSetting</ResourceURI><SelectorSet xmlns="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd"><Selector Name="InstanceID">Intel(r) AMT: Force PXE Boot</Selector></SelectorSet></ReferenceParameters></r:Source></r:ChangeBootOrder_INPUT></Body></Envelope>`

**Comment by Ylianst** [comment]
Good request. I will look at adding this when I get back.

**Comment by VietTPham** [comment]
Do you have any updates on this?

**Comment by Frank-Steiner** [comment]
Hi,
I'd also be interested on this. Maybe we could also get the boot-into-bios? :)
cu,
Frank

**Comment by si458** [comment]
already implemented in latest release 2024
```
simon@testmc:~/meshcentral$ ./meshcmd help AMTPower
AmtPower will get current pwoer state or send a reboot command to a remote Intel AMT device. Example usage:

  meshcmd amtpower --reset --host 1.2.3.4 --user admin --pass mypassword --tls

Required arguments:

  --host [hostname]      The IP address or DNS name of Intel AMT.
  --pass [password]      The Intel AMT login password.

Optional arguments:

  --reset, --poweron, --poweroff, --powercycle, --sleep, --hibernate
  --user [username]                                    The Intel AMT login username, admin is default.
  --tls                                                Specifies that TLS must be used.
  --bootdevice [pxe|hdd|cd|ider-floppy|ider-cdrom]     Specifies the boot device to use after reset, poweron or powercycle.
  --bootindex [number]                                 Specifies the index of boot device to use.
```
