### ISSUE TITLE
Tab Title Web-VNC

### ISSUE THREAD

**Issue by fuessli** [Ylianst/MeshCentral#6412]
Hi there,

Web VNC opens a new browser tab titled noVNC. If multiple connections are open, you cannot tell which tab belongs to which connection.
Is it possible to add the respective computer name to the tab title?

Thank you in advance

Michael

**Comment by si458** [comment]
all fixed!https://github.com/Ylianst/MeshCentral/commit/b20e51561ae9313247978af22981f0e0e59dec0c
will be in `master` docker builld in 15mins for you to test OR patch ir youself from the commit

the code was already in novnc, but commented out for some reason (no idea why?)
and the PAGE_TITLE value was also missing?
might need to update novnc to 1.5.0 when i get chance too and see what else is missing!

**Comment by si458** [comment]
also note, the title only changes when you CONNECT to a device successfully
by default it always displays just `noVNC`

**Comment by fuessli** [comment]
Hi Simon,

Super! You are faster than fast.
I will test it next week and give you feedback.


Von: Simon Smith ***@***.***>
Gesendet: Sonntag, 29. September 2024 14:41
An: Ylianst/MeshCentral ***@***.***>
Cc: fuessli ***@***.***>; Author ***@***.***>
Betreff: Re: [Ylianst/MeshCentral] Tab Title Web-VNC (Issue #6412)


also note, the title only changes when you CONNECT to a device successfully
by default it always displays just noVNC

**Comment by fuessli** [comment]
I’ve testet ist. Unforttunately there’s an error opening noVNC:

noVNC encountered an error:
SyntaxError: expected expression, got '<'
https://****/novnc/app/ui.js:7:1



Von: Simon Smith ***@***.***>
Gesendet: Sonntag, 29. September 2024 14:41
An: Ylianst/MeshCentral ***@***.***>
Cc: fuessli ***@***.***>; Author ***@***.***>
Betreff: Re: [Ylianst/MeshCentral] Tab Title Web-VNC (Issue #6412)


also note, the title only changes when you CONNECT to a device successfully
by default it always displays just noVNC

**Comment by si458** [comment]
you must not of copied+pasted the `ui.js` file correctly
your error is showing on line 7 (which is a comment tab message)
but if you check the commit https://github.com/Ylianst/MeshCentral/commit/b20e51561ae9313247978af22981f0e0e59dec0c
i only changed from line 20-23 and 1744-1745

**Comment by fuessli** [comment]
Sorry, my mistake. Unfortunately I'm not a programmer, but I can vi. Now it works. Thank you and wish you a nice Sunday


Von: Simon Smith ***@***.***>
Gesendet: Sonntag, 29. September 2024 15:48
An: Ylianst/MeshCentral ***@***.***>
Cc: fuessli ***@***.***>; Author ***@***.***>
Betreff: Re: [Ylianst/MeshCentral] Tab Title Web-VNC (Issue #6412)


you must not of copied+pasted the ui.js file correctly
your error is showing on line 7 (which is a comment tab message)
but if you check the commit b20e515<https://github.com/Ylianst/MeshCentral/commit/b20e51561ae9313247978af22981f0e0e59dec0c>
i only changed from line 20-23 and 1744-1745
