### ISSUE TITLE
Keep record of computer last logged in user in MeshCentral to facilitate identification

### ISSUE THREAD

**Issue by rodrigolzd** [Ylianst/MeshCentral#6421]
**Is your feature request related to a problem? Please describe.**
Whenever a system is online, I can see the current active user, but when the computer disconnects that information is gone, So looking at the offline device, I cant find the last user that was active on that computer. In situations where computers are named ramdonly or numerically, it is harder to find the user you want to help

**Describe the solution you'd like**
Just want an extra line that says the name of the last active user and that information should be kept even when the computer is offline from MeshCentral

**Describe alternatives you've considered**
Maybe keep a list of system users and make it searchable.

**Comment by si458** [comment]
done! https://github.com/Ylianst/MeshCentral/commit/19d0df7e7f025823bf85eb10aa000489e41c01ec
amazingly it already records it and keeps it,
its just the web ui only shows the value IF the device is online and has users,
so just removed the IF device is online 😆 

also added the active users to mobile ui as it wasnt there!
