### ISSUE TITLE
allow filtering computers based on username

### ISSUE THREAD

**Issue by lostence** [Ylianst/MeshCentral#6422]
In the main computer list view, there is a filter/search field.
This works to quickly find a computer, for example.

We have 100s of computers in the list, and usually need to search for a username instead.
This does not work.

We have to CTRL+F in the browser, but as all the lines are not loaded at once, we need to PageDown + Ctrl+F several times, to find the logged-in user we are looking for.

Would it be possible for that search box to filter both computer names and users ?
That would be wonderful

**Comment by si458** [comment]
Already exists :) https://ylianst.github.io/MeshCentral/meshcentral/devicetabs/#search-or-filter

**Comment by lostence** [comment]
Oooh, got to use "u:joe" in the search .. thanks, didn't know!
I feel like it could/should search in all fields without needing to specify "u:" (like for computer names), but i understand if that is not practical when there are many computers.

This is ok for me, now that i know

**Comment by si458** [comment]
In theory `user:xxx` should also work!
