### ISSUE TITLE
Terminal and Files tabs don't appear in the web interface for some Linux agents

### ISSUE THREAD

**Issue by kubamaruszczak** [Ylianst/MeshCentral#6425]
**Describe the bug**
I'm running MeshCentral v1.1.24 instance on t3.micro AWS EC2 instance. I have over a 1000 Linux devices connected as agents to that server. For some devices, even though the Agent is connected, the Terminal and Files tabs are not visible.

![image](https://github.com/user-attachments/assets/7a4b5b50-ff57-4df0-a2d3-08d44f4c2ed2)

However, I can connect to the instance terminal session using `Shell` command executed locally from the MeshCentral server.

`/home/ec2-user/.nvm/versions/node/v18.17.1/bin/node /home/ec2-user/meshcentral/node_modules/meshcentral/meshctrl --loginuser $NAME --loginkey $LoginTokenKey --url ws://localhost:443 Shell --id $ID`

![image](https://github.com/user-attachments/assets/35aa3d57-b520-4b59-bffc-9dc48e792227)

Executing Reset Device Action or restarting meshagent service makes Terminal and Files tabs to appear.

![image](https://github.com/user-attachments/assets/61b44321-068f-47b4-9311-c068ca5e9abc)
![image](https://github.com/user-attachments/assets/368b9c66-094e-4ac9-b5e5-08156644122f)

I don't know if that's relatable but after reset / meshagent service restart Operating System information appears.

![image](https://github.com/user-attachments/assets/9f72142e-068a-4385-95cb-be27b32e2957)

**Expected behavior**
I would expect to be able to connect to the device's terminal session using the web interface, if I can do so via the command line. 

**Server Software:**
 - OS: Amazon Linux 2023
 - Version: [e.g. 1.1.24]
 - Node: [e.g. 18.17.1]

**Remote Device:**
 - Device: Server
 - OS: Linux
 - Network: Remote over WAN
 - Current Core Version: Nov 21 2022, 109652783

**Your config.json file**
```
{
  "settings": {
    "cert": "my.domain.url",
    "WANonly": true,
    "LANonly": false,
    "mariaDB": {
      "host": "MeshCentralDBHost",
      "user": "MeshCentralDBUser",
      "port": 3306,
      "password": "MeshCentralDBPwd",
      "_connectionLimit": "number",
      "database": "meshcentralrdsdb",
      "awsrds": true
    },
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "nightMode": 0,
    "tlsOffload": true,
    "_mpsTlsOffload": true,
    "maxInvalidLogin": {
      "time": 10,
      "count": 10,
      "coolofftime": 10
    },
    "rootCertCommonName": "xxx",
    "mpshighsecurity": true,
    "allowLoginToken": true,
    "authLog": "meshcentral-data/auth.log",
    "userAllowedIP": "10.0.0.0/8",
    "compression": true,
    "desktopMultiple": true,
    "manageAllDeviceGroups": [
      "user//admin"
    ]
  },
  "domains": {
    "": {
      "title": "MeshCentral",
      "_title2": "Servername",
      "_minify": true,
      "newAccounts": false,
      "userNameIsEmail": true,
      "amtAcmActivation": {
        "log": "amtactivation.log",
        "certs": {
          "mycertname": {
            "certfiles": [ "xxx.crt", "XXX.crt" ],
            "keyfile": "xxx.key"
          }
        }
      },
      "ssh": true,
      "certUrl": "my.domain.url",
      "passwordRequirements": {
        "min": 8,
        "max": 128,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "_reset": 90,
        "force2factor": true,
        "_skip2factor": "127.0.0.1,192.168.2.0/24",
        "_oldPasswordBan": 5,
        "_banCommonPasswords": false,
        "twoFactorTimeout": 60
      },
      "twoFactorCookieDurationDays": 1
    }
  }
}
```

**Comment by si458** [comment]
one thing you can try is in the console tab click `agent actions`
then select `clear the core`
then wait about 10 seconds
then `agent actions` again and click `upload default server core`

this sometimes happens where the device cant load the meshcore correctly to begin with and it might be corrupted
so just clearing it and asking it to get the new version sometimes fixes it!

the is also a PR just been done which might fix this issue in the future you could try
https://github.com/Ylianst/MeshCentral/pull/6431

**Comment by kubamaruszczak** [comment]
I will try https://github.com/Ylianst/MeshCentral/pull/6431 and let you know if it helps

**Comment by kubamaruszczak** [comment]
Seems like https://github.com/Ylianst/MeshCentral/pull/6431 solved the issue! Thanks!

**Comment by si458** [comment]
thank @HuFlungDu for discovering the fix ❤️
