### ISSUE TITLE
The Login button is not enabled when the account is filled by the browser

### ISSUE THREAD

**Issue by trmdi** [Ylianst/MeshCentral#6428]
If you save the login info in the browser, the next time you login it will be auto filled but the login button is still disabled.
![image](https://github.com/user-attachments/assets/e0682202-fbd4-4161-9a67-dd07c5057f5b)

**Comment by si458** [comment]
I noticed this when I use my bitwarden
but don't no why it does it?

If u press enter the button that gets enabled 

So I'm guessing it's the prefill isn't registering correctly

**Comment by si458** [comment]
i think ive fixed it but i meant to check what browser/OS you was using as you didnt say!

**Comment by si458** [comment]
fix is here if you wanna patch n try yourself https://github.com/Ylianst/MeshCentral/commit/ec7505987dc83982ed5eeaef7c4cc0230bfc48aa
basically the button is disabled for security and prevent login bots,
so you need to enter a user and password before its enabled
BUT it seems the onchange commands for the password field are too quick,
and when it checks if the is a value in there, the value is blank as the password manager couldnt type it in quick enough
so just putting a 100ms delay in fixes the issue

**Comment by trmdi** [comment]
This setTimeout approach does not work for me. I even try 1000ms delay.
I'm on the latest Edge/Windows 11.
![image](https://github.com/user-attachments/assets/66fa9414-aff6-470c-8c2a-3857982187e3)

**Comment by si458** [comment]
Ok thanks I will test with edge,
As i was tesring with firefox which fixed the issue on my mac and android device 
It's possible that edge is refilling the boxes but not the value option!
So might need to identify what it's actually doing

**Comment by trmdi** [comment]
There is a WON'T FIX issue in Chromium. Maybe we should stop disabling the Submit button and use "required" on the Input fields instead?
https://www.w3schools.com/TAgs/att_input_required.asp
