### ISSUE TITLE
Wrong 'serverUrl' key in meshaction.txt

### ISSUE THREAD

**Issue by debpolaris** [Ylianst/MeshCentral#6436]
**Describe the bug**
If subdomain is set, incorrect 'serverUrl' key is written in MeshAction file when downloading meshaction.txt.
ex) 'meshcentral' is my subdomain.

      {
       "username": "myid",
       "password": "",
       "serverId": "xxxxxxx",
       "serverHttpsHash": "82394723948dsfds",
       "debugLevel": 0,
       "serverUrl": "wss://its.mysite.com:443//meshcentralmeshrelay.ashx"
      }

**Expected behavior**

      {
       "username": "myid",
       "password": "",
       "serverId": "xxxxxxx",
       "serverHttpsHash": "82394723948dsfds",
       "debugLevel": 0,
       "serverUrl": "wss://its.mysite.com:443/meshcentral/meshrelay.ashx"
      }

**To improve**
Change line 5685 in webserver.js 

`if (obj.args.lanonly != true) { meshaction.serverUrl = 'wss://' + obj.getWebServerName(domain, req) + ':' + httpsPort + '/' + ((domain.id == '') ? '' : **('/' + domain.id))** + 'meshrelay.ashx'; }`

to

`if (obj.args.lanonly != true) { meshaction.serverUrl = 'wss://' + obj.getWebServerName(domain, req) + ':' + httpsPort + '/' + ((domain.id == '') ? '' : **(domain.id + '/'))** + 'meshrelay.ashx'; }`

P.S. I'm sorry I don't know how to commit the source...

**Comment by si458** [comment]
all fixed and indeed you was correct! the value was just the wrong way round for some reason?
