### ISSUE TITLE
What is the "HW Connect" button?

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#644]
Guys, good morning!

One question, when the "HW - connect" button is visible next to the connect button, is the remote station intel AMT enabled? I noticed that it is available on the screen bellow for some machines

![image](https://user-images.githubusercontent.com/55212206/68484174-8bbccc00-021b-11ea-80e9-1efe2bd265a7.png)

**Comment by veitw** [comment]
This is correct, "HW Connect" connects to AMT either directly or reverse via CIRA, depending on how AMT and the device in MC is configured.

**Comment by Ylianst** [comment]
That is correct, "HW Connect" is the Intel AMT Hardware KVM connection button and show be displayed when MeshCentral detects that this feature is available.

**Comment by MailYouLater** [comment]
Also, questions like this would be better posted to [Reddit](https://www.reddit.com/r/MeshCentral/) than GitHub.
