### ISSUE TITLE
Devices on "Relay" are not shown in online list

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#6440]
**Is your feature request related to a problem? Please describe.**
Group with devices relayed via other agent are not showing on Online List.

**Describe the solution you'd like**
When select in Filter Online Only devices , group with relayed devices to be shown in this list.

**Describe alternatives you've considered**
No alternatives :) When showing all devices, relayed devices (and group itself) shows as online, but not on the filtered list.

**Additional context**
See screen shots:

Filter online only, does not shows relayed groups:
![image](https://github.com/user-attachments/assets/ef08582a-286f-49d9-b101-96102bde4a41)

Relayed devices shows only when All is selected, while icon for the device shows it as online..
![image](https://github.com/user-attachments/assets/4805343e-81bb-4f3d-addb-c822aa56e90e)

Hope that make sense.

**Comment by si458** [comment]
I do believe this might be a bug!
So will have a look when I get chance 👍

**Comment by si458** [comment]
all done!
you can patch yourself here and test https://github.com/Ylianst/MeshCentral/commit/6d412a7bea63e9cad17cc97ced756f08e6b0e85e

**Comment by vitko-bg** [comment]
Can confirm, after patch all is working as expected. Thanks!
