### ISSUE TITLE
OIDC: unable to get local issuer certificate in docker + FIX

### ISSUE THREAD

**Issue by Daniel-Hillenbrand** [Ylianst/MeshCentral#6444]
If OIDC is used with a self-operated IDP and self-managed certificate infrastructure, the following error is displayed:

`
/opt/meshcentral/node_modules/meshcentral/webserver.js:7406
                let error = new Error('OIDC: Discovery failed.', { cause: err });
                            ^

Error: OIDC: Discovery failed.
    at setupDomainAuthStrategy (/opt/meshcentral/node_modules/meshcentral/webserver.js:7406:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setupAllDomainAuthStrategies (/opt/meshcentral/node_modules/meshcentral/webserver.js:6495:82) {
  [cause]: Error: unable to get local issuer certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
  }
}

Node.js v20.15.0
`

The solution to the problem is to provide Node with the certificate chain:

e.g. in startup.sh
export NODE_EXTRA_CA_CERTS=/opt/meshcentral/meshcentral-data/chain.pem

**Comment by si458** [comment]
**You haven't followed the bug report so we cannot assist/help u until you fill it out**

You are missing critical information like config.json, server os, meshcentral version

**Comment by Daniel-Hillenbrand** [comment]
No information is missing. I have even presented the solution.

The openid-client used within NodeJS does not trust any private certificate infrastructure (own CA). NodeJS as a whole does not. Therefore, there should be a way to pass a certificate chain into the Docker container from the outside.

See it as a feature request.

**Comment by si458** [comment]
Oh shoot! Sorry!

I've had a mad day so I've been quick reading and I've mis-read!

Ur issue was u was getting the discovery failure because u are using like a self-signed certificate!

And u can fix the issue by proving the certificate as an environment variable!

In theory if its the docker image, u can just add the environmental variable directly into ur docker-compose file!
Have u tried that and see if it still works?
Or MUST you add the export line into the startup file?

**Comment by Daniel-Hillenbrand** [comment]
You are absolutely right about the env variable. Thanks for the tip.
Might be something for the documentation. https://ylianst.github.io/MeshCentral/meshcentral/openidConnectStrategy/

**Comment by si458** [comment]
@Daniel-Hillenbrand, indeed, the docs need updating.
PRs welcome! You can edit the docs/docs folder :)
