### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [Ylianst/MeshCentral#6451]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing MeshCentral application as shown [here](https://elest.io/open-source/meshcentral). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, I see that we already have a conversation thread for partnership over **revenue share**, if you wish to discuss more or have any questions just ping me at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by si458** [comment]
PRs welcome! U can edit the docs/docs folder!
It will be the install2 file :)

**Comment by kaiwalyakoparkar** [comment]
> PRs welcome! U can edit the docs/docs folder! It will be the install2 file :)

Oh thanks for the info, I will update the pull request 🙌

**Comment by smartekIT** [comment]
honestly this doesn't look right, trying to advertise for your service within the main system (Meshcentral).
Meshcentral is free and open source, while you trying to make money out of it, well goodluck with that but hijacking the main app to advertise for your service I don't think this looks good or acceptable. there is other services who using meshcentral  part of their service and make money out of it like Tactical RMM but they never tried to be greedy and pushing reference to their system in the Meshcentral.
Keep Mechcentral as it's clean and free open source and not to try abusing it is the key here. so normal people can benefit from it. that's exactly what it was developed for when Ylianst started it along with other developers.
Hope I wasn't too hard but at least this is how I see it.

Thanks

**Comment by PathfinderNetworks** [comment]
I agree with smartekIT.  While I have no trouble with someone creating a revenue model around MeshCentral (such as providing hosting services for it) I do not think we should be putting references to those types of companies within the MeshCentral documentation or other references.  Now if a company such as this wishes to financially support the MeshCentral development efforts in exchange for something along the lines of a 'sponsored by' endorsement (without having any direct say in the direction the development goes) then I'm good with that (not sure about others).  But that's completely different than some sort of official link or reference in the documentation.

**Comment by Br0kenSilos** [comment]
@PathfinderNetworks I agree with this sentiment as well.

**Comment by si458** [comment]
I will let @Ylianst make the final decision, so leave the PR open for the moment

**Comment by smartekIT** [comment]
Hi everyone,
Imagine someone providing hosting for cPanel. Then going to cPanel asking them to reference the hosting company in their guides!! No it doesn't work that way, it should be other way around where the hosting company should reference cPanel at their websites and guides while paying cPanel a fee for using their service as well even in some cases they also will need a permission before they think of putting cPanel logo at the hosting website. and that's completely fair.

**Comment by smartekIT** [comment]
I don't want to be rude but anyway when looking at their profile, they have published the same content and the same wording in more than 45 repository in the last 3 days. so it's clear that all what they aim to is to advertise for their website and business by spreading the word about it. I doubt that Meshcentral will get a penny from them.
they didn't even bother changing their words, it's like if they got it generated in chat GPT. all what they do changing the repo name. doing massive 45 repo in 3 days that tells you something about their goals. (advertising and advertising only).

**Comment by DaanSelen** [comment]
I am curious to the decision of Ylianst.
