### ISSUE TITLE
 bug in Upload mobile mode

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#6460]
When uploading in mobile mode in version 1.1.32, it remains in connecting mode....
![20241018-13-30-04](https://github.com/user-attachments/assets/15cadb42-c157-4e3c-beb2-05ad3300e6e5)

**Comment by si458** [comment]
**You haven't followed the bug template report.
So we cannot assist you until you do.
So please reply back with it completed (or edit ur original issue to include all the info)**

**Comment by bravery-only** [comment]
in Mobile : Click on Upload File and select File .then Clieck ok And Stop in Connectiong....
Server OS : Windows Server 2016
Network : Wan

**Comment by si458** [comment]
@bravery-only **you still havent completed the bug report correctly**
you are missing what node version you are using
whats your config.json look like
whats the remote device you are sending files to
whats the mobile browser.
this is all required for us to help you, so until this is provided we cannot assist you

**Comment by si458** [comment]
duplicate of newer issue #6543
