### ISSUE TITLE
inaccessible sharing link

### ISSUE THREAD

**Issue by Jayddee23** [Ylianst/MeshCentral#6462]
Hello,
I'm experiencing a problem with the sharing links that work internally but no longer work from our vpn.
The changes made were to upgrade the mesh server to version 1.1.32 and to generate an https certificate which we applied to the server.
node is in v17.4
Here's the message returned when I go through our vpn:
![image](https://github.com/user-attachments/assets/91c18ece-c1cd-4369-afe3-83103a0aad08)
An idea
Best regards,

**Comment by si458** [comment]
that isnt an error from meshcentral, that looks like a generic apache error
have you checked if you use a reverse proxy is setup correctly?

**Comment by Jayddee23** [comment]
sorry, here's my configuration :
![image](https://github.com/user-attachments/assets/5e1121a5-333a-4195-98c8-04fc439a4e96)
![image](https://github.com/user-attachments/assets/b7dc5bb5-da27-4825-9e10-dfa147e69f30)
I don't have a reverse proxy, only a dns with an entry to resolve srv-mesh.*** to its ip which I just checked and is correct.
No json configuration changes either following the mesh version upgrade.

**Comment by si458** [comment]
sadly the must be something wrong with your dns records then
because that error being shown is an apache! nothing to do with meshcentral! meshcentral doesnt use apache!
you can check your DNS record by doing `ping mc.mydomain.com`

**Comment by Jayddee23** [comment]
Before, there was just a redirection from port 80 to 443 with a security warning for the certificate.
Since switching to https with our own certificate, we've been accessing mesh via its fqdn name.
What's amazing is that with a web resource on my vpn pointing to the connection page via the address https://fqdn, I can access the page, so it resolves the name correctly. But as soon as I put the sharing address behind it, it doesn't work and I get the error message.

**Comment by si458** [comment]
@Jayddee23 without seeing an example of the url thats working, and url thats NOT working, its hard to say

**Comment by Jayddee23** [comment]
For exemple
https://mesh.mydomain.fr/ 
it's ok
But https://mesh.mydomain.fr/sharing?c=qfoF6gqkrY2P4OSf4b48lItg4UvRqQ5KC3IKZCAUNVAT4a9D57xOGasFt3XGEJdm@HKubDv2@t6R$uCZpYe3kW5NQKCTccwfNzE=
Doesn't work.

**Comment by si458** [comment]
what happens when you visit the sharing url, does it show the picture above saying 'forbidden - ErrorDocument' ?
if it does, this ISNT a meshcentral error message or page. its from apache. (we dont use apache2)
ive checked the source code and we only every use 404 errors (not found) not 403 (forbidden)
so without access to your environment to investigate, i cannot help anymore :(

**Comment by Jayddee23** [comment]
Here is the cause of my problem, sent by our vpn provider.

> A recent Debian security update brings malfunctions to the use of Systancia Gate 8.8 and Systancia Cleanroom 4.5 on Web and SMB resources and applications.
All platforms withApache2 version2.4.62-1~deb12u2 are affected.

We have patched according to their procedure and everything works.
Thanks again for your time.
Best regards,
