### ISSUE TITLE
Meshcentral Assistant Agent Fails to interact with UAC prompt 

### ISSUE THREAD

**Issue by GhostNaix** [Ylianst/MeshCentral#6466]
**Describe the bug**
When given administrator privileges to Meshcentral Assistant, Meshcentral Assistant cannot interact with UAC prompts (Pressing Yes or No), however after the user presses yes the Meshcentral Assistant can interact with the elevated software 

**To Reproduce**
1. Download Meshcentral Agent onto the Remote Device.
2. Run the Meshcentral Agent on the Remote device as Administrator
3. Click on _Connect to desktop_ from the Meshcentral WebUI
4. Run Another app As administrator on the Remote Side
5. See _Unable to Capture display_ error while the UAC prompt is active.

**Expected behavior**
Meshcentral Agent should allow the capability to interact with the UAC prompt. 

**Screenshots**
![ip3HGCgLGx](https://github.com/user-attachments/assets/81d400eb-4951-4cbc-8ce6-97e648780ba5)

**Server Software (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Virtualization: N/A - Bare Metal
 - Network: LAN
 - Version: 1.0.31
 - Node: v22.4.1

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 11
 - Network: Local to Meshcentral
 - Browser: Firefox v131.0.3
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: VMware Virtual Machine
 - OS: Windows 11 23H2 Build 22631
 - Network: Local to Meshcentral
 - Current Core Version (if known): v0.1.8175.21599

**Additional context**
N/A

**Comment by tobias9931** [comment]
I have the same problem.
If I want to run a program as admin, the login screen appears on the client, but on the remote session via MeshCentral I suddenly land on the Windows login screen and no longer see the real session.

**Comment by kiroubel-girma** [comment]
It's not clear from description of bug if remote user is using Agent or Assistant (or both). Assistant is only mentioned in the title.
If it's Assistant,  I think it works as designed. Check description from "invitation link":
`This is not an agent that runs in the background of the managed computer, instead, it's a tool that connects to the server only when requested.`

Meshcentral Assistant is for the remote Windows user requesting help. Meaning the UAC prompt should be handled by the remote user. I don't think it matters if remote user runs the Assistant application as admin (they should not).

The question is: what happens after remote user handles the UAC prompt ?

**Comment by GhostNaix** [comment]
> It's not clear from description of bug if remote user is using Agent or Assistant (or both). Assistant is only mentioned in the title.
> If it's Assistant,  I think it works as designed. Check description from "invitation link":
> `This is not an agent that runs in the background of the managed computer, instead, it's a tool that connects to the server only when requested.`
> 
> Meshcentral Assistant is for the remote Windows user requesting help. Meaning the UAC prompt should be handled by the remote user. I don't think it matters if remote user runs the Assistant application as admin (they should not).
> 
> The question is: what happens after remote user handles the UAC prompt ?

My apologies if it wasn't clear, to clarify, yes the "issue" appears on the Assistant version, I just thought that once the user requests help and I'm already logged in, the Meshcentral Assistant should allow me to handle further UAC prompts for the user. As for what happens after the UAC prompt, I'm able to interact with the elevated application from the remote connection. (It seems quite annoying that every time I run an elevated application or tool, I would require the user to hit Yes for me, would it not?)

**Comment by si458** [comment]
Yes the meshcentral assistant is designed to be run as the user without admin rights, sadly even if u say run as admin for the meshcentral assistant, it doesn't get admin rights because the remote control still only has user permissions so u can't control the uac prompts

If u want like temp access, u can download the meshagent as interactive mode, then click connect, this will run as admin and u can get to the uac prompts!

**Comment by GhostNaix** [comment]
> Yes the meshcentral assistant is designed to be run as the user without admin rights, sadly even if u say run as admin for the meshcentral assistant, it doesn't get admin rights because the remote control still only has user permissions so u can't control the uac prompts
> 
> If u want like temp access, u can download the meshagent as interactive mode, then click connect, this will run as admin and u can get to the uac prompts!

Oh I see. This was by design, strange but understandable nonetheless. Closing Issue then. Thank you, everyone, for your valuable  input.
