### ISSUE TITLE
linux x64 agent not connecting to meshcentral from AMT machine

### ISSUE THREAD

**Issue by reidjr** [Ylianst/MeshCentral#647]
I have a small mesh of a pi3, 2 windows machines, and the problem machine, an intel AMT capable machine, runnning Ubuntu 18.04.
All 4 machines run meshagent, and the first 3 work as expected. I run meshagent on the intel AMT machine for remote desktop, as the hardware KVM desktop is unusably slow. 
Until recently the meshagent and hardware connect have been options for this machine, but in the last few weeks, the meshagent has stopped connecting, The trace tab on meshcentral does not show any activity from the agent, although running the agent from the command line on the Ubuntu machine shows attempting to connect. I am running an up to date meshcentral, and have tried full removal and reinstall of both meshcentral and the meshagent. Anything else I can do to pinpoint the issue ?

**Comment by Ylianst** [comment]
This has probably nothing to do with Intel AMT? It seems the agent is not connecting to the server. I will check with Bryan tomorrow, we have ways to debug what is going on.

**Comment by krayon007** [comment]
What's the network topology between your server and the machine that won't connect?

**Comment by reidjr** [comment]
The topology is pi3 based meshcentral server on same unmanaged GB ethernet switch as the AMT machine.

This may now be a dead issue, as after i shutdown and restarted the amt machine, and repeated the uninstall and reinstall of the mesh agent, it did connect as a new agent instance on the original mesh, and then detected the AMT instance. I now have 2 instances of the same machine in the mesh, 1 AMT only ( original) and the new one with AMT and Agent. It could have been something very local, so perhaps close this issue. Although if there is a fault finding process I might need it in the future !

**Comment by reidjr** [comment]
Closing issue as a reboot fixed it. However separately I have found on Ubuntu 18.04 my meshagent always requires a service restart after server reboot ( different issue)
