### ISSUE TITLE
Implement AddDevice to meshctrl

### ISSUE THREAD

**Issue by lschnetl** [Ylianst/MeshCentral#6473]
**Is your feature request related to a problem? Please describe.**
It seems that we can mostly use the meshctrl application to do most tasks that you would normally do, except to add devices. I don't want to manually add devices every time we have a new one, so it would be great if we can add a device using meshctrl.

Currently you can view, edit and delete devices, but not add

**Describe the solution you'd like**
It would be great if we can add a device using meshctrl. Something like 
`node node_modules/meshcentral/meshctrl.js AddDevice --name <name> --hostname <hostname> --user <admin> --password <password> --tls`

**Describe alternatives you've considered**
So far I have tried to import hosts using the import json function, but it constantly creates duplicates if I don't make sure to remove existing hosts

**Additional context**
N/A

**Comment by si458** [comment]
are you talking about adding devices to the `local groups` or the `intel amt only` groups?

you cant add devices into the `meshagent` group as thats the meshagents appliction job haha

**Comment by lschnetl** [comment]
Intel® AMT only, no agent (don't want to add agents or rely on host)

**Comment by si458** [comment]
thats ok just wanted to clarify as you are indeed correct, you cant add devices using the `meshctrl.js` !
will add it to my to-do list!

**Comment by lschnetl** [comment]
Awesome! Thank you for the quick feedback!

**Comment by si458** [comment]
all done! https://github.com/Ylianst/MeshCentral/commit/141bec559fb291a0f361826d3000851a118e08cb

you need to patch the server side aswell as the meshctrl.js otherwise the meshctrl.js will just hang with no reply

but plz dont forget to donate ❤️  https://www.si458.co.uk/2024/01/05/donation/
