### ISSUE TITLE
User ID duplication on LDAP login

### ISSUE THREAD

**Issue by JairoVV** [Ylianst/MeshCentral#6474]
Hi,

I have seen that there are two users who, when they log in, Meshcentral creates the same user id and overwrites the data of one user over the other in the Database, depending on the last one who logged in. In config.json I have used parameters ldapUserKey and ldapUserBinaryKey with value mail, objectGUID, objectSID but Meshcentral continues assign same user id for both user login. I have delete user from Database and make login again, but the behavior was the same.

I will expect that with parameter ldapUserKey or ldapUserBinaryKey this issue not happen.

Meshcentral is running on Debian 12, with LANonly = false. The version of Mesh is 1.1.32 and Node version is 20.17.0

My config.json is:
```
{
  "settings": {
    "MongoDb": "mongodb://mesh:password@127.0.0.1:27017/meshcentral?authSource=admin",
    "Cert": "mymeshserver.domain.local",
    "_WANonly": true,
    "_LANonly": true,
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
    "UserAllowedIP" : "1IP_range/24"
  },
  "domains": {
    "": {
      "title": "My Mesh Server",
      "title2": "AD authentication",
      "minify": true,
      "loginPicture": "logo_Meshcentral.png",
      "welcomeText": "Meshcentral",
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "_allowlogin": true,
      "auth": "ldap",
      "ldapUserEmail": "mail",
      "ldapOptions": {
        "url": "ldap://myladapserverip",
        "bindDN": "CN=Meshcentral,OU=USERS,DC=domain,DC=local",
        "bindCredentials": "ldapuserpassword",
        "searchBase": "OU=USERS,DC=domain,DC=local",
        "_userobjectclass": "person",
        "searchFilter": "(sAMAccountName={{username}})",
        "_groupFilter": "(&(objectCategory=group)(member={{dn}}))",
        "ldapUserKey": "mail",
        "_ldapUserKey": "objectGUID",
        "ldapUserBinaryKey": "objectSID",
      }
    },
    "Local": {
      "title": "MeshCentral",
      "title2": "Local authentication",
      "minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true,
      "_allowlogin": true,
      "auth": "local"
    }
  }
}
```
Thanks in advance for your efforts and work.

**Comment by si458** [comment]
You have both ldapuserkey and ldapuserbinarykey set
You should have one or the other set.
And as u have ldapuserkey set to mail, this is a bad idea as multiple users can use the same mail address
So it's best toboeep ldapuserbinarykey instead

**Comment by JairoVV** [comment]
Hi,

I tried with:

- only with "ldapUserKey": "mail",
- only with "ldapUserKey": "objectGUID",
- only with "ldapUserBinaryKey": "objectGUID"
- only with "ldapUserBinaryKey": "objectSID"

and the behavior is the same, Meshcentral overwrites the user in Database, updating with the data of the last who logged and using the same user_id.

Thanks in advance

**Comment by si458** [comment]
You need to use something like an ldap explorer and verify all the attributes for users and check what's unique

Similar issue and fix is here https://github.com/Ylianst/MeshCentral/issues/6318#issuecomment-2309895587

**Comment by JairoVV** [comment]
Hi,

I was able to solve the problem with these post. I have deleted the problematic users and relogin after change config.json. Everything is working as expected now. Thanks a lot for your help,

Regards,

**Comment by si458** [comment]
no worries! glad u got it sorted! its all trial and error! and finding the right config setup
