### ISSUE TITLE
Get web relay url via websocket

### ISSUE THREAD

**Issue by YiuTerran** [Ylianst/MeshCentral#6484]
**Is your feature request related to a problem? Please describe.**

Currently, we expose MeshCentral to users through an embedded iframe, and other functions work fine. However, when using the web relay feature, we cannot directly interact to obtain the relay URL via WebSocket; we must directly embed the General Information tab. This exposes too much information to users, while we only need a single link address.

**Describe the solution you'd like**
We can directly send commands to MeshCentral via WebSocket, and it will return a usable link. The browser can then open this link to complete the web relay.

**Describe alternatives you've considered**
Place the web relay-related buttons on a separate webpage instead of combining them with other general information. This way, we can avoid exposing too much information.

**Comment by si458** [comment]
The webrelay works slightly differently

It gives u the url of ur relaydns or ur cert+relayport

But then uses a special unique cookie, which then identifies what service etc u wanted to be relayed

The is no special url as such! It's the cookie that makes it unique,

So we would have to return the url and a cookie for u to set of that makes sense

Would a simple json reply be ok?

**Comment by YiuTerran** [comment]
@si458 JSON data is certainly fine. Our main concern is that we don’t want to expose the entire General Tab to users, as it contains too much information.

**Comment by YiuTerran** [comment]
I believe that directly passing the cookie as a URL parameter to MeshCentral is also feasible.

**Comment by si458** [comment]
@YiuTerran no that's understandable!
I will double check the code next week when i get chance, as the might possibly already a way I'm just not 100% sure

**Comment by si458** [comment]
just started to implement this feature and then realised this already partly exists
you create a `devicesharing` and this will return a url which can be used for web relay
only difference is you can restrict what the `devicesharing` does,
ie who can access it, when, remote desktop, web relay, etc
also creates a link in the web ui so u can see what links are created and u can delete them too
did you wanna try that and see if thats better for you? 
code is inside meshctrl under `devicesharing` 

if its not ideal i can add the `webrelay` to the websocket but it will only return basically the code return thats listed above
a link to a url to do web relay but you will have no record of this

**Comment by YiuTerran** [comment]
Thanks, i will try `devicesharing` tomorrow.

**Comment by YiuTerran** [comment]
It seems `{"action":"createDeviceShareLink"}` does not work for the device group with a relay id. For Normal device, it works good.

**Comment by YiuTerran** [comment]
> if (webRelayDns != '') { servername = webRelayDns; }

If I configured multiple relay domains , how can i get a valid one to use?

**Comment by si458** [comment]
@YiuTerran it does work for relay groups, check out the meshctrl.js for source code, how it creates the websocket data

Also I believe if u have multiple dns set for the relay it just round robins them so if one already in use it moved onto the next then the next then the next etc

**Comment by YiuTerran** [comment]
> Also I believe if u have multiple dns set for the relay it just round robins them so if one already in use it moved onto the next then the next then the next etc

But only meshcentral know which one is in use, I can't get it in my code...

> so did you want me to add the feature in so it returns a url for you over websockets?

Yep! Currently, when configured with multiple relay domains, there is no perfect way to obtain the relay URL. The only solution is to add a new WebSocket interface to achieve this purpose.

**Comment by si458** [comment]
im still bashing my head against the wall with this at the moment so i havent forgotten about it
but for some reason the `rcookie` you get from the `authcookie` doesnt work because its session is empty?

strange one, how do you login over the websocket? user/pass, cookie, loginkey, headers?

**Comment by si458** [comment]
@YiuTerran ok all done! https://github.com/Ylianst/MeshCentral/commit/dbb5b4ba1117528643855ad424b61f777ffd7acf
```
simon@testmc:~/meshcentral/MeshCentral$ node meshctrl.js help WebRelay
Generate a webrelay URL to access a HTTP/HTTPS service on a remote device, Example usages:

  MeshCtrl WebRelay --id 'deviceid' --type http --port 80
  MeshCtrl WebRelay --id 'deviceid' --type https --port 443

Required arguments:

  --id '[deviceid]'     - The device identifier.
  --type [http,https]   - Type of relay from remote device, http or https.

Optional arguments:

  --port [portnumber]   - Set alternative port for http or https, default is 80 for http and 443 for https.
```

websocket request examples
```
HTTP - { action: 'webrelay', nodeid: nodeidhere, port: 80, appid: 1, responseid: 'randomapp' }
HTTPS - { action: 'webrelay', nodeid: nodeidhere, port: 443, appid: 2, responseid: 'randomapp' }
```
websocket reply examples
```
{
	"action": "webrelay",
	"nodeid": "BIGLONGNODEIDHERE",
	"port": 80,
	"appid": 1,
	"responseid": "randomapp",
	"url": "https://mc.mydomain.com:4444/control-redirect.ashx?n=BIGLONGNODEIDHERE&p=80&appid=1&c=BIGLONGCOOKIELINKHERE",
	"result": "OK"
}
```
