### ISSUE TITLE
Ntfy custom server not working

### ISSUE THREAD

**Issue by Raito00** [Ylianst/MeshCentral#6488]
Steps to reprosduce:

Set up a self-hosted ntfy server (e.g. ntfy.example.com)
Configure MeshCentral messaging to use the self-hosted ntfy server:**

```
"messaging": {
  "ntfy": {
    "host": "ntfy.example.com",
    "userurl": "https://ntfy.example.com/userhelp",
    "authorization": "Bearer <token>",
    "description": "Custom ntfy server"
  }
}
``` 

Attempt to send a test notification in MeshCentral
Expected Behavior
A verification code should be sent to the ntfy client to approve the MeshCentral server. Once approved, notifications should work properly.

Actual Behavior
The verification code is not sent from the MeshCentral server to the self-hosted ntfy server. Notifications do not work with the self-hosted ntfy server.

Workaround
Using the public ntfy.sh host works properly.

Additional Details
MeshCentral version: v1.1.32
ntfy server version: v2.8.0

Notifications to and from the self-hosted ntfy server works properly. Including SMTP to and from the self-hosted ntfy server.

NTFY Server Software (please complete the following information):

OS: Ubuntu 22.04
Virtualization: none
Network: LAN/WAN, reverse proxy.
Version: v2.8.0
MeshCentral Server Software (please complete the following information):

OS: Ubuntu 22.04
Virtualization: none
Network: LAN/WAN
Version: 1.1.32
** redacted snippet of messaging section from config.json file**

```
"messaging": {
  "ntfy": {
    "host": "ntfy.example.com",
    "userurl": "https://ntfy.example.com/userhelp",
    "authorization": "Bearer <token>",
    "description": "Custom ntfy server"
  }
},
  "smtp": { .......
``` 
I also tested with:
```
 "authorization": "Basic <base64-user:passw>" 

``` 
The same problem ...

**Comment by Raito00** [comment]
I have my self-hosted nfty setup so only authenticated user can send notifications or with Token. 
@PTR-inc Your Meshcentral config is the same lik my?
I updated ntfy to v2.11.0 - the same problem

**Comment by si458** [comment]
@Raito00 have you verified you can send a message to your topic without meshcentral first?
https://docs.ntfy.sh/config/#example-private-instance

**Comment by Raito00** [comment]
Yes! I`m using my ntfy few years.
My most used command is:
```
curl -X POST "https://ntfy.<mydomain>/MyTopic" \
     -H "Authorization: Bearer tk_<redacted>" \
     -d "Message go here!" \
     -H "Title: Title message go here" \
     -H "Tags: Extra TAGS go here!"
```

**Comment by si458** [comment]
@Raito00, have u ever had ntfy working with meshcentral, or is this the first time setting it up?

U also didn't quite follow the bug template report correctly.

What nodejs version are u using? 

Is the ssl on ur ntfy domain a valid ssl or self signed?

**Comment by Raito00** [comment]
This is first time i try use on Meshcentral.
Node: v22.5.1
Yes, all ok with ssl is valid

P.S.
I can create user for You in my nft for direct testing ...

**Comment by si458** [comment]
> This is first time i try use on Meshcentral.
> Node: v22.5.1
> Yes, all ok with ssl is valid
> 
> P.S.
> I can create user for You in my nft for direct testing ...

Sure, please email me details with link etc, I'll be stationary in 2 hours 🚗

**Comment by si458** [comment]
ok this is all fixed now!
thank you for sending details, what appears to be happening is because you use cloudflare,
cloudflare EXPECTED a `User-Agent` header on EVERY request,
and nodejs just doesnt include you, so you have to set one!
the patch is here if you want to manually patch it yourself! https://github.com/Ylianst/MeshCentral/commit/7928f7fb3039e62ffde71867ec3153a72a305c50
