### ISSUE TITLE
Enhancement Tip - Lock and log off feature on remote user's machine.

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#649]
Guys, good morning!

I would suggest including a flag or button that allows the technician to choose whether he wants to block or log off or not do any of these actions on the user's computer when he disconnects from the remote session, is it possible?

**Comment by krayon007** [comment]
Locking yes. That capability is already there, but as a standalone feature. It should be trivial to add a setting to have it do that on disconnect.

Logging off is more complicated. Not sure if its possible, but if it were, it would complicate things, because on some platforms, KVM is not possible when no users are logged in.

**Comment by MailYouLater** [comment]
@ryanblenis: Perhaps it would be a good idea to add a hook to allow plugins to define an action that occurs when the user disconnects.  This way a plugin could be made that would pop up a 'Would you like to Log off or Lock the remote computer?' to satisfy this request, and #270, and another (or even the same one if it's customizable) could satisfy the request in issue #543.

**Comment by ryanblenis** [comment]
Thanks @MailYouLater, that could indeed be a good hook to have. I've added a hook for "onDesktopDisconnect" in my [development](https://github.com/ryanblenis/MeshCentral/tree/plugin-admin) branch that (should it be accepted when the time comes) will add the availability of that hook to plugins. I've currently got a lot of changes going on there for a GUI plugin interface that isn't quite ready for a pull request.

**Comment by MailYouLater** [comment]
@krayon007: What exactly is disallowed when a user isn't logged in? Screen capture? Input emulation? Both?
How difficult would it be to add a feature that allows the remote user to log in so that the remote KVM function becomes usable?  I'm imagining it where you click connect on the Desktop tab, and it pops up kind of like this:
![Remote Login - Username Password](https://user-images.githubusercontent.com/1279475/68883166-53a70480-06c5-11ea-93db-543e183013b3.png)

**Comment by geanferrani123** [comment]
> @ krayon007 : O que exatamente não é permitido quando um usuário não está logado? Captura de tela? Emulação de entrada? Ambos? 
> Quão difícil seria adicionar um recurso que permita ao usuário remoto efetuar login para que a função KVM remota se torne utilizável? Eu estou imaginando onde você clica em conectar na guia Área de trabalho e aparece assim:
> ![Login Remoto - Nome de Usuário Senha](https://user-images.githubusercontent.com/1279475/68883166-53a70480-06c5-11ea-93db-543e183013b3.png)

MailYouLater, How did you do to enable this feature? Could you explain me?

**Comment by MailYouLater** [comment]
That's just a mockup to show what I imagine it might look like if a remote login feature were added.  There is no remote login feature currently.

**Comment by geanferrani123** [comment]
Guys, if I may say, remote login is not necessary, my suggestion was more so that when it terminates remote access, automatically perform the process of locking or logoff of the computer, but on second thought, it will not be necessary, as it ends up being a pretty useless feature for the tool that is getting wonderfully good.

For my part, you can close this topic.

Thank you all for your attention!

**Comment by MailYouLater** [comment]
It may not be necessary, or even useful for your use case, but it may help people using platforms that don't allow KVM when a user isn't logged in, so I would still like an answer.  @krayon007: How difficult do you think it would be to implement a remote login function to work around the issue on some platforms that KVM is unavailable when no user is logged in?

**Comment by Ylianst** [comment]
I like how the mock up looks very realistic. @krayon007 will need to respond to this. I know on MacOS we can't capture the login screen anymore, not sure about other operating systems.

**Comment by si458** [comment]
this is already partly possible 
if you right click the disconnect button when you are connected,
you will see `Disconnect and Lock`
this will disconnect your remotr control and also lock the users desktop :)
the is no way to logout the user tho at the moment
