### ISSUE TITLE
Bootstrap UI: Filter input field typing shenanigans

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#6498]
Using the bootstrap UI, the My Devices filter input field behaves erroneous in several ways:

* pressing Ctrl+A
  * expected behaviour: all input data is selected
  * actual result: nothing happens

* selecting content and pressing backspace
  * expected behaviour: selected data is deleted
  * actual result: selection is cancelled and last character in input field is deleted and cursor is moved to the end of the input data
  * side note: using delete instead of backspace seems to work as expected on selected data

* selecting content and starting to type
  * expected behaviour: selected content is replaced with content typed
  * actual result: selection is cancelled and new content is appended to the end of the input data, cursor moves to the end of input data

* pressing escape
  * expected behaviour: input field's content is deleted
  * actual result: under certain circumstances, the input data is NOT deleted -- I was not able to figure out yet what these circumstances are

* "delete content" X icon
  * expected behaviour: an X icon is shown which deleted the input field's content
  * actual result: (at least) on Firefox this icon is missing
  * side note: as Firefox does not offer this functionality itself, this feature had been emulated via JavaScript in the previous UI

Environment:
* MeshCentral 1.1.33
* Firefox 131.0.3

**Comment by si458** [comment]
fixed https://github.com/Ylianst/MeshCentral/commit/d44faed29eeecc58aa8363a6df501e831805b98c
