### ISSUE TITLE
meshcentral.db grow quickly

### ISSUE THREAD

**Issue by elkekou** [Ylianst/MeshCentral#6505]
**Describe the bug**
Since 2, 3 days my meshcentral.db grow insane really quickly (2GB in one day) then my meshcentral service die and does not restart until i restore an old backup (db ~20mb). I have made no change from my config since months. Trying to update to  1.1.33 bug still here.

I tried to migrate to sqlite database, but bug still here. It seems table "power" and "ndxpowernodeidtime"  are the table which quickly grow.

Here some information from sqlite between 2 db :

Yesterady evening ~10PM
```
sqlite> SELECT name ,SUM(pgsize)/1024 table_size  FROM "dbstat" GROUP BY name ORDER BY table_size desc;
main|17396
power|880
sqlite_autoindex_main_1|584
ndxtypedomainextra|388
ndxpowernodeidtime|388
ndxextra|328
ndxextraex|76
events|36
ndxeventids|16
eventids|16
sqlite_schema|4
sqlite_autoindex_smbios_1|4
sqlite_autoindex_serverstats_1|4
smbios|4
serverstats|4
plugin|4
ndxsmbiostime|4
ndxsmbiosexpire|4
ndxserverstattime|4
ndxserverstatexpire|4
ndxeventsusername|4
ndxeventstime|4
ndxeventsdomainnodeidtime|4
```

This morning : 

```
sqlite> SELECT name ,SUM(pgsize)/1024 table_size  FROM "dbstat" GROUP BY name ORDER BY table_size desc;
power|33092
main|17452
ndxpowernodeidtime|14332
sqlite_autoindex_main_1|584
ndxtypedomainextra|388
events|356
ndxextra|328
ndxeventids|120
eventids|112
ndxextraex|76
serverstats|68
ndxeventsdomainnodeidtime|52
ndxeventsusername|16
ndxeventstime|12
sqlite_schema|4
sqlite_autoindex_smbios_1|4
sqlite_autoindex_serverstats_1|4
smbios|4
plugin|4
ndxsmbiostime|4
ndxsmbiosexpire|4
ndxserverstattime|4
ndxserverstatexpire|4
```

My installation :
debian 12, with node 18.19, near 1500 agents.

My config file : 
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "SQLite3": true,
    "cert": "help.fqdn...",
    "port": 9000,
    "aliasPort": 443,
    "agentAliasPort": 443,
    "agentPort": 9001,
    "AgentPong": 300,
    "amtScanner": false,
    "agentAliasDNS": "agent.fqdn....",
    "agentTimeStampProxy": "http://proxy:3128",
    "TlsOffload": true,
    "userAllowedIP" : "x.y.z/24.,a.b.c/24",
    "syslog": true,
    "manageAllDeviceGroups": [ "user//..." ]
  },
  "domains": {
    "": {
      "title": "Meshcentral ",
      "certUrl": "file:///opt/meshcentral/meshcentral-data/star.fqdn.crt",
      "auth": "ldap",
      "newAccountsRights": [ "nonewgroups" ],
      "ldapUserName": "uid",
      "ldapOptions": {
        "url": "ldaps://ldapr.fqdn",
        "searchBase": "...",
        "searchFilter": "(uid={{username}})",	      "tlsOptions": { "rejectUnauthorized": false }
      },
  "agentCustomization": {
        "displayName": "XXX - Meshcentral",
        "description": "XXX remote monitoring, management and assistance.",
        "companyName": "XXX ",
        "image": "logo.png"
      }
    }
  },
  "smtp": {
      "host": "127.0.0.1",
      "port": 25,
      "from": "eic-web-envoi@fqdn",
      "tls": false,
      "tlscertcheck": false
  }
}
```

What i've done wrong?

Thank you for helping

**Comment by elkekou** [comment]
Update after 4hour of working hour db grow to 160MB, always same table

```
 SELECT name ,SUM(pgsize)/1024 table_size  FROM "dbstat" GROUP BY name ORDER BY table_size desc;
power|107936
ndxpowernodeidtime|47008
main|17680
events|1424
ndxeventids|600
sqlite_autoindex_main_1|584
eventids|540
ndxtypedomainextra|388
ndxextra|328
ndxeventsdomainnodeidtime|228
serverstats|104
ndxextraex|76
ndxeventsusername|44
ndxeventstime|40
sqlite_schema|4
sqlite_autoindex_smbios_1|4
sqlite_autoindex_serverstats_1|4
smbios|4
plugin|4
ndxsmbiostime|4
ndxsmbiosexpire|4
ndxserverstattime|4
ndxserverstatexpire|4

```

**Comment by si458** [comment]
this isnt really a bug, as sqlite just uses alot of storage and doesnt shrink

if i look at my home-assistant database (which uses sqlite) its 700MB
and the same goes for my sonarr, its 300MB

the was a recent commit done in the main repo which includes a few sqlite maintenance tasks to help keep the size small
https://github.com/Ylianst/MeshCentral/pull/6487

maybe try the master docker image and see over a few days if the recent commit fixes the issue

**Comment by elkekou** [comment]
I fact until now I keep using the default nedb database, but it growing really quickly (2Gib in one day) so I tried SQLite which also grow but it easier for me to find what data grow :).

For installation I already use npm install ... So I don't really know where to look.

**Comment by si458** [comment]
oh sorry ive just realised what you mean
you WAS using nedb (which is the `meshcentral.db` file, and the size was increasing)
then you switched to sqlite (which is the `meshcentral.sqlite` file but the file is also increasing)
2 different files

`ndxpowernodeidtime` is an index table of `power` (`CREATE INDEX ndxpowernodeidtime ON power (nodeid, time)`)
so its the power table thats the issue, have alot of your devices rebooted/restarted over night maybe?
do the graphs for power line seem correct?

**Comment by elkekou** [comment]
Sorry but i don't know where the "graph power line" is. 
How can i know if one or several PC is flapping power on power off?
Can i prevent or customize log of powerstate?

**Comment by elkekou** [comment]
Thanks for pointing me in the right direction, i find all the agents keep disconnecting regularly~ 30/40sec.
I've just realised that we have lowered default timeout  40s globally on our apache reverse proxy.
I've just set it back to 300 on the fqdn dedicated to mesh agents and everything seems fine again.
