### ISSUE TITLE
Bootstrap UI - Missing tooltip when hovering on the Filter's textbox

### ISSUE THREAD

**Issue by dxdemetriou** [Ylianst/MeshCentral#6507]
**Describe the bug**
Actually is missing this part:
````title="Filter: user:xxx or u:xxx ip:xxx group:xxx or g:xxx tag:xxx or t: xxx atag:xxx or a:xxx os:xxx amt:xxx desc:xxx wsc:ok wsc:noav wsc:noupdate wsc:nofirewall wsc:any"````

**To Reproduce**
1. Go to My Devices
2. Hover the mouse on the Filter textbox

**Expected behavior**
Show the tooltip:
Filter: user:xxx or u:xxx ip:xxx group:xxx or g:xxx tag:xxx or t: xxx atag:xxx or a:xxx os:xxx amt:xxx desc:xxx wsc:ok wsc:noav wsc:noupdate wsc:nofirewall wsc:any

**Screenshots**
![image](https://github.com/user-attachments/assets/29a4102a-f8e2-4d78-9e99-f3a7c6ee151d)

**Comment by si458** [comment]
fixed https://github.com/Ylianst/MeshCentral/commit/d44faed29eeecc58aa8363a6df501e831805b98c
