### ISSUE TITLE
With 2FA enabled I cannot connect to meshcentral through meshcommander

### ISSUE THREAD

**Issue by Alessio71** [Ylianst/MeshCentral#651]
With 2FA enabled I cannot connect to meshcentral through meshcommander (Invalid username or password)
Is it normal or am I missing something?
Thank you.
Regards,
Alex

**Comment by Ylianst** [comment]
Oh... that is a good point. I never added support for this. I need to work on it.

**Comment by Ylianst** [comment]
Published MeshCommander v0.8.0 with 2-factor support when connecting to MeshCentral. However, you may need to also update to MeshCentral v0.4.4-c or better for this to work. The 2-factor time codes and backup codes will work, but USB keys will not.

Let me know if it works for you. Thanks.

**Comment by Alessio71** [comment]
Working fine!
Thank you.
Alex
