### ISSUE TITLE
DB issue unable to connect after injecting URL to remote PC

### ISSUE THREAD

**Issue by nexitpl** [Ylianst/MeshCentral#6513]
Hello I have issue, I clicked to input link in one of my client PC and suddenly meshcentral website goes offline and I even pull backup from today morning and still having this error:

it's Docker with 2 images meshcentral_db and meshcentral on mongodb

Logs from meshcentral container:
```
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:22) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Logs from meshcentral_db:
```
ry_store:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],prefetch=(available=true,default=false),"}
t={"$date":"2024-11-08T14:37:13.514+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":514145,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Recovering log 1717 through 1718"}}
t={"$date":"2024-11-08T14:37:13.546+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":546493,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Recovering log 1718 through 1718"}}
t={"$date":"2024-11-08T14:37:13.591+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":591963,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Main recovery loop: starting at 1717/2560 to 1718/256"}}
t={"$date":"2024-11-08T14:37:13.647+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":647500,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Recovering log 1717 through 1718"}}
t={"$date":"2024-11-08T14:37:13.681+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":681303,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Recovering log 1718 through 1718"}}
t={"$date":"2024-11-08T14:37:13.708+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":708882,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"recovery log replay has successfully finished and ran for 195 milliseconds"}}
t={"$date":"2024-11-08T14:37:13.708+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":708975,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Set global recovery timestamp: (0, 0)"}}
t={"$date":"2024-11-08T14:37:13.709+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":709011,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"Set global oldest timestamp: (0, 0)"}}
t={"$date":"2024-11-08T14:37:13.710+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":710623,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"recovery rollback to stable has successfully finished and ran for 1 milliseconds"}}
t={"$date":"2024-11-08T14:37:13.712+00:00"} s=I c=WTCHKPT id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":712192,"thread":"1:0x7fe4a3378680","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 3535710"}}
t={"$date":"2024-11-08T14:37:13.746+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":746058,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"recovery checkpoint has successfully finished and ran for 35 milliseconds"}}
t={"$date":"2024-11-08T14:37:13.746+00:00"} s=I c=WTRECOV id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1731076633,"ts_usec":746123,"thread":"1:0x7fe4a3378680","session_name":"txn-recover","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"recovery was completed successfully and took 232ms, including 195ms for the log replay, 1ms for the rollback to stable, and 35ms for the checkpoint."}}
t={"$date":"2024-11-08T14:37:13.747+00:00"} s=I c=STORAGE id=4795906 ctx=initandlisten msg=WiredTiger opened attr={"durationMillis":745}
t={"$date":"2024-11-08T14:37:13.747+00:00"} s=I c=RECOVERY id=23987 ctx=initandlisten msg=WiredTiger recoveryTimestamp attr={"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}
t={"$date":"2024-11-08T14:37:13.756+00:00"} s=W c=CONTROL id=22120 ctx=initandlisten msg=Access control is not enabled for the database. Read and write access to data and configuration is unrestricted tags=["startupWarnings"]
t={"$date":"2024-11-08T14:37:13.756+00:00"} s=W c=CONTROL id=8640301 ctx=initandlisten msg=For customers running the updated tcmalloc-google memory allocator, we suggest setting the contents of sysfsFile to 'defer+madvise' attr={"sysfsFile":"/sys/kernel/mm/transparent_hugepage/defrag","currentValue":"madvise"} tags=["startupWarnings"]
t={"$date":"2024-11-08T14:37:13.756+00:00"} s=W c=CONTROL id=8640302 ctx=initandlisten msg=We suggest setting the contents of sysfsFile to 0. attr={"sysfsFile":"/sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none","currentValue":511} tags=["startupWarnings"]
t={"$date":"2024-11-08T14:37:13.757+00:00"} s=W c=CONTROL id=8718500 ctx=initandlisten msg=Your system has glibc support for rseq built in, which is not yet supported by tcmalloc-google and has critical performance implications. Please set the environment variable GLIBC_TUNABLES=glibc.pthread.rseq=0 tags=["startupWarnings"]
t={"$date":"2024-11-08T14:37:13.757+00:00"} s=W c=NETWORK id=5123300 ctx=initandlisten msg=vm.max_map_count is too low attr={"currentValue":65530,"recommendedMinimum":2000000,"maxConns":1000000} tags=["startupWarnings"]
t={"$date":"2024-11-08T14:37:13.758+00:00"} s=I c=NETWORK id=4915702 ctx=initandlisten msg=Updated wire specification attr={"oldSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":25},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":25},"outgoing":{"minWireVersion":6,"maxWireVersion":25},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":25},"incomingInternalClient":{"minWireVersion":21,"maxWireVersion":25},"outgoing":{"minWireVersion":21,"maxWireVersion":25},"isInternalClient":true}}
t={"$date":"2024-11-08T14:37:13.758+00:00"} s=I c=REPL id=5853300 ctx=initandlisten msg=current featureCompatibilityVersion value attr={"featureCompatibilityVersion":"7.0","context":"startup"}
t={"$date":"2024-11-08T14:37:13.759+00:00"} s=I c=STORAGE id=5071100 ctx=initandlisten msg=Clearing temp directory
t={"$date":"2024-11-08T14:37:13.769+00:00"} s=I c=CONTROL id=6608200 ctx=initandlisten msg=Initializing cluster server parameters from disk
t={"$date":"2024-11-08T14:37:13.770+00:00"} s=I c=CONTROL id=20536 ctx=initandlisten msg=Flow Control is enabled on this deployment
t={"$date":"2024-11-08T14:37:13.770+00:00"} s=I c=FTDC id=20625 ctx=initandlisten msg=Initializing full-time diagnostic data capture attr={"dataDirectory":"/data/db/diagnostic.data"}
t={"$date":"2024-11-08T14:37:13.772+00:00"} s=I c=REPL id=6015317 ctx=initandlisten msg=Setting new configuration state attr={"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}
t={"$date":"2024-11-08T14:37:13.772+00:00"} s=I c=STORAGE id=22262 ctx=initandlisten msg=Timestamp monitor starting
t={"$date":"2024-11-08T14:37:13.772+00:00"} s=I c=STORAGE id=7333401 ctx=initandlisten msg=Starting the DiskSpaceMonitor
t={"$date":"2024-11-08T14:37:13.772+00:00"} s=I c=NETWORK id=23015 ctx=listener msg=Listening on attr={"address":"/tmp/mongodb-27017.sock"}
t={"$date":"2024-11-08T14:37:13.773+00:00"} s=I c=NETWORK id=23015 ctx=listener msg=Listening on attr={"address":"0.0.0.0:27017"}
t={"$date":"2024-11-08T14:37:13.773+00:00"} s=I c=NETWORK id=23016 ctx=listener msg=Waiting for connections attr={"port":27017,"ssl":"off"}
t={"$date":"2024-11-08T14:37:13.773+00:00"} s=I c=CONTROL id=8423403 ctx=initandlisten msg=mongod startup complete attr={"Summary of time elapsed":{"Startup from clean shutdown?":true,"Statistics":{"Set up periodic runner":"0 ms","Set up online certificate status protocol manager":"0 ms","Transport layer setup":"0 ms","Run initial syncer crash recovery":"0 ms","Create storage engine lock file in the data directory":"0 ms","Get metadata describing storage engine":"0 ms","Validate options in metadata against current startup options":"0 ms","Create storage engine":"746 ms","Write current PID to file":"0 ms","Initialize FCV before rebuilding indexes":"1 ms","Drop abandoned idents and get back indexes that need to be rebuilt or builds that need to be restarted":"1 ms","Rebuild indexes for collections":"0 ms","Load cluster parameters from disk for a standalone":"0 ms","Build user and roles graph":"0 ms","Set up the background thread pool responsible for waiting for opTimes to be majority committed":"0 ms","Start up the replication coordinator":"1 ms","Ensure the change stream collections on startup contain consistent data":"0 ms","Write startup options to the audit log":"0 ms","Start transport layer":"1 ms","_initAndListen total elapsed time":"771 ms"}}}
t={"$date":"2024-11-08T14:37:14.003+00:00"} s=W c=CONTROL id=636300 ctx=ftdc msg=Use of deprecated server parameter name attr={"deprecatedName":"internalQueryCacheSize","canonicalName":"internalQueryCacheMaxEntriesPerCollection"}
t={"$date":"2024-11-08T14:37:14.003+00:00"} s=W c=CONTROL id=636300 ctx=ftdc msg=Use of deprecated server parameter name attr={"deprecatedName":"oplogSamplingLogIntervalSeconds","canonicalName":"collectionSamplingLogIntervalSeconds"}
t={"$date":"2024-11-08T14:37:14.003+00:00"} s=W c=NETWORK id=23803 ctx=ftdc msg=Use of deprecated server parameter 'sslMode', please use 'tlsMode' instead.
t={"$date":"2024-11-08T14:37:14.003+00:00"} s=W c=CONTROL id=636300 ctx=ftdc msg=Use of deprecated server parameter name attr={"deprecatedName":"wiredTigerConcurrentReadTransactions","canonicalName":"storageEngineConcurrentReadTransactions"}
t={"$date":"2024-11-08T14:37:14.003+00:00"} s=W c=CONTROL id=636300 ctx=ftdc msg=Use of deprecated server parameter name attr={"deprecatedName":"wiredTigerConcurrentWriteTransactions","canonicalName":"storageEngineConcurrentWriteTransactions"}
t={"$date":"2024-11-08T14:38:13.757+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1731076693,"ts_usec":757959,"thread":"1:0x7fe494b376c0","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 3535710"}}
t={"$date":"2024-11-08T14:39:13.762+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1731076753,"ts_usec":762247,"thread":"1:0x7fe494b376c0","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 6, snapshot max: 6 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 3535710"}}
t={"$date":"2024-11-08T14:40:13.765+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1731076813,"ts_usec":764991,"thread":"1:0x7fe494b376c0","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 8, snapshot max: 8 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 3535710"}}
```

Please HELP

**Comment by si458** [comment]
It's self-explanatory 

`Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017`

Meshcentral can't connect to your mongodb server

So check what port mongodb is running on as meahcentral thinks u entered the port 27017 as the port number

**Comment by si458** [comment]
Also u didn't follow the bug template correctly 

And u don't say what docker image u are using

**Comment by nexitpl** [comment]
Sorry...

docker image:
[typhonragewind/meshcentral:mongodb-latest]



Everything worked fine until I injected link while in desktop session, now I don't even know why restoring a backup did not work too:


Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017


IP of my container is correct

**Comment by si458** [comment]
Have u checked ur mongodb service is running and port in the container?
`docker ps` should show what port it's using

**Comment by nexitpl** [comment]
meshcentral
8b08aa944f4e   mongo:latest                                "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes             27017/tcp

**Comment by nexitpl** [comment]
docker network inspect meshcentral_default
[
    {
        "Name": "meshcentral_default",
        "Id": "86190b60358624ed47e730d80f544fbd3ecda9a2ef374c61ce3451e9952fde7f",
        "Created": "2024-02-04T22:22:45.695153525+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "6bb5ff40420799e955d7b7670deb51cecf8de5f8e46ee91dc2bed4ed966e8681": {
                "Name": "meshcentral",
                "EndpointID": "52afc884caef4d45c615a09f3061b9b5476e16e009c3318904da335382b263af",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            },
            "8b08aa944f4ece950a31bcdee779e6c6aa1f2603320b6527eaf9d8516602ce52": {
                "Name": "meshcentral_db",
                "EndpointID": "5383f159771fb4eaba20f262e080f16aced14fdbfa5e196f8dd0253fad51b1b3",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "meshcentral",
            "com.docker.compose.version": "2.20.2"
        }
    }

it seems IP is ok

**Comment by si458** [comment]
Sounds daft, physical restart ur docker machine/vm
I've had it in the past docker got confused over stuff and a simple restart of the computer fixed the issue

**Comment by nexitpl** [comment]
restarted the whole server and still:
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Unable to connect to database: MongoServerSelectionError: connect EHOSTUNREACH 172.20.0.2:27017
ERR: (node:22) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ERR: (node:21) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by nexitpl** [comment]
config.json for meshcentral:
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "*************",
    "_sessionKey": "**********",
    "port": 9443,
    "_aliasPort": 9443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 60,
    "tlsOffload": "192.168.2.10",
    "trustedproxy": "********",
    "SelfUpdate": false,
    "AllowFraming": false,
    "mongodb": "mongodb://mongodb:27017/mesh",
    "mongodbcol": "mesh",
    "allowHighQualityDesktop": true,
    "IgnoreAgentHashCheck": true,
    "WebRTC": true,
    "plugins": {
      "enabled": true
    }
  },
  "domains": {
    "rs.nex-it.pl": {
      "_title": "Meshcentral",
      "_title2": " Meshcentral",
      "_minify": true,
      "NewAccounts": false,
      "_userNameIsEmail": true,
      "_certUrl": "https://***********/"
    }
  }
}

**Comment by si458** [comment]
You have ur mongodb set to `mongodb` as the server name
Try changing it to `meshcentral_db` and restarting meshcentral container

**Comment by nexitpl** [comment]
Yes but it was working like that all the time, I have done as you wrote and still got the same issue, even recreated containers with re pull images and still the same, I also checked if there is enough space on VM but it seems ok:
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G  1.5M  1.6G   1% /run
/dev/sda3        40G   30G  8.1G  79% /
tmpfs           3.9G   11M  3.9G   1% /tmp
/dev/sda2        10M  2.2M  7.8M  23% /boot/efi
tmpfs           797M     0  797M   0% /run/user/1000
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/48f978324df1d843e001ccc61a1b07c18a3b7519f32dc1a84144665f8d5953a3/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/81feec4ab27457a1794407bec4f7b46f93f146d19a8ee79dcdf45a25c91e0fc8/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/a3893bf03c4df7369164bd9a07822a1a4f5a59b14d08ac0365dc028f8a5c0d59/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/076cc474142ad8ee1c0c234dd1e61a848b524f94c7622eff2cb94710bade11de/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/1ca3ea533ad7cd6f47f1383e27caa23c4851445b96a59fb55dae5ccf502505de/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/d60ef2cca59a49ecf3f42aa7d0ceca6bb93e0aaa86ee19d5bb117fc5c1b0b210/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/367dc112f07a12ddebdc9eea70c9e43025960991ecaa05763844ea2f7d62a75b/merged
overlay          40G   30G  8.1G  79% /var/lib/docker/overlay2/c5e58923dd6189112e538d9bd954e5e89454d208725f38b038acbb08a11b9c22/merged


I also found something like this in logs of meshcentral_db:
t={"$date":"2024-11-08T15:40:53.481+00:00"} s=I c=CONTROL id=23285 ctx=main msg=Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
t={"$date":"2024-11-08T15:40:53.482+00:00"} s=I c=CONTROL id=5945603 ctx=main msg=Multi threading initialized
t={"$date":"2024-11-08T15:40:53.482+00:00"} s=I c=NETWORK id=4648601 ctx=main msg=Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set at least one of the related parameters attr={"relatedParameters":["tcpFastOpenServer","tcpFastOpenClient","tcpFastOpenQueueSize"]}
t={"$date":"2024-11-08T15:40:53.483+00:00"} s=I c=NETWORK id=4915701 ctx=main msg=Initialized wire specification attr={"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":25},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":25},"outgoing":{"minWireVersion":6,"maxWireVersion":25},"isInternalClient":true}}
t={"$date":"2024-11-08T15:40:53.483+00:00"} s=I c=TENANT_M id=7091600 ctx=main msg=Starting TenantMigrationAccessBlockerRegistry
t={"$date":"2024-11-08T15:40:53.483+00:00"} s=I c=CONTROL id=4615611 ctx=initandlisten msg=MongoDB starting attr={"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"82bfb3b41bd1"}
t={"$date":"2024-11-08T15:40:53.483+00:00"} s=I c=CONTROL id=23403 ctx=initandlisten msg=Build Info attr={"buildInfo":{"version":"8.0.3","gitVersion":"89d97f2744a2b9851ddfb51bdf22f687562d9b06","openSSLVersion":"OpenSSL 3.0.13 30 Jan 2024","modules":[],"allocator":"tcmalloc-google","environment":{"distmod":"ubuntu2404","distarch":"x86_64","target_arch":"x86_64"}}}



maybe something with SSL TLS?

**Comment by nexitpl** [comment]
I also exposed Mongodb port 27017 and telnet to it from Mac  and it connects 

telnet 192.168.2.49 27017
Trying 192.168.2.49...
Connected to photon.
Escape character is '^]'.

**Comment by nexitpl** [comment]
another strange thing is that I event sucessfully connected to mongo with compass:
![image](https://github.com/user-attachments/assets/7f27c755-330e-445e-bfb2-6613841fe69f)

**Comment by si458** [comment]
Glad u got it sorted but to me that's a docker bug haha
And I didn't think u could change mac addresses with docker!
Learn something new every day
