### ISSUE TITLE
Pressing Enter on the login screen no longer works in 1.1.33

### ISSUE THREAD

**Issue by Br0kenSilos** [Ylianst/MeshCentral#6514]
**Describe the bug**
First, THANK YOU for all of the great work you have been doing. I am really happy to see development on MC taking place and I am excited for it's future again.

Normally (on all previous versions), when at the main login screen, I have been able login by auto-fill (from Bitwarden) the login and password and then simply hitting Enter. However, since updating to 1.1.33, this function no longer works and I must mouse over and click  the Login button. Then it will proceed to the next screen where I can use my security key for 2FA. Easy to work around. This is just  more of an annoyance than anything else.

**To Reproduce**
1. Go to to the main login screen
2. Fill in your credentials.
3. Press the "Enter" button (Do not hit the tab button first to select login)
4. Nothing happens.

**Expected behavior**
Pressing Enter should (and has in the past) worked to initiate the login process.

**Screenshots**
Nothing to show really

**Server Software (please complete the following information):**
 - OS: Ubuntu Server 22.04.5
 - Virtualization: Docker (latest)
 - Network: NGINX Proxy Manager
 - Version: 2.11.2
 - Node: What ever is built into the latest docker image for MC

**Client Device (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 Pro / Windows 11 Pro
 - Network: WAN to MC
 - Browser: FireFox ver 132.0, Microsoft Edge ver 130.0.2849.68, OpraGX
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Network: N/A

**Additional context**
I have also tested this without the use of auto-fill and typed in credentials. No difference. I have a friend who has also noticed this behavior on his server as well.

**Comment by si458** [comment]
Duplicate #6498
Already fixed :)

**Comment by Br0kenSilos** [comment]
Ope, sorry. I didn't see the previous issue. Thank you Simon. :-)
