### ISSUE TITLE
badlogins output does not show address of banned IPs

### ISSUE THREAD

**Issue by Br0kenSilos** [Ylianst/MeshCentral#6516]
**Describe the bug**
To be fair, I am not 100% sure this is a bug or not but I think it might be. I have been going through some security checks and wanted to validate that my MC instance would ban an IP on failed login attempts. I currently have my setup set to ban IP's for 60 mins if they attempt 5 or more logins within a 10 minute period. This seems to be working. However, when I go to my MeshCentral server console and type in "badlogins", the output indicates that there is a banned IP and how much time is remaining before unban, but it does not show the IP address or any other info.

**To Reproduce**
1. I use a VPN for this so my real IP is not being used (Dont want to ban myself)
2. Open a browser and go to the login screen for the main site
3. Enter invalid credentials enough tomes to trigger the ban (Until you see a message "IP Address blocked, try again later"
4. ![Screenshot 2024-11-08 124549](https://github.com/user-attachments/assets/71c4f100-0caf-4548-a3c7-888578f4c774)
5. Now in the  UI console screen for the server, type in badlogins and hit enter.

**Expected behavior**
You should (I think) see some kind of indication of what the banned IP address(es) is/are.

**Screenshots**
Instead I see the following:
![image](https://github.com/user-attachments/assets/c6f4f999-a5c6-4202-ab5e-b03675358550)

**Server Software (please complete the following information):**
    OS: Ubuntu Server 22.04.5
    Virtualization: Docker (latest)
    Network: NGINX Proxy Manager
    Version: 2.11.2
    Node: What ever is built into the latest docker image for MC

**Client Device (please complete the following information):**
Device: Desktop
OS: Windows 10 Pro / Windows 11 Pro
Network: WAN to MC
Browser: FireFox ver 132.0, Microsoft Edge ver 130.0.2849.68, OpraGX

**Remote Device (please complete the following information):**
N/A

**Additional context**
While this is my first time trying to use the badlogins commandm I have seen screenshots elsewhere on the web where the command provide addition info that what I am seeing.

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "obscured.mydomain.com",
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyVerySecretKey",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 20,
    "agentAliasDns": "obscured.mydomain.com",
    "TLSOffload": false,
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false",
    "trustedproxy": "nginxproxymanager,172.17.0.3,127.0.0.1,CloudFlare",
    "mpshighsecurity": true,
    "maxInvalidLogin": {
      "time": 10,
      "count": 5,
      "coolofftime": 60
    },
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": "24",
      "zippassword": "SuperSecretPassword"
    }
  },
  "domains": {
    "": {
      "title": "My MC Server",
      "LoginKey": "ObscuredSuperSecretLoginKey",
      "_title2": "myserver",
      "allowhighqualitydesktop": true,
      "minify": false,
      "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://obscured.mydomain.com",
      "passwordRequirements": {
        "min": 16,
        "max": 128,
        "upper": 2,
        "lower": 2,
        "numeric": 2,
        "nonalpha": 2,
        "oldPasswordBan": 25,
        "banCommonPasswords": true,
        "reset": 183
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
So just quickly checked source code on my phone

Amazingly it doesn't show the ip address?

But it is suppose to show records lines
but for some reason ur isn't so might need looking into why?
```
for (var i in parent.badLoginTable) {
                    badLoginCount++;
                    if (typeof parent.badLoginTable[i] == 'number') {
                        cmdData.result += "Cooloff for " + Math.floor((parent.badLoginTable[i] - Date.now()) / 60000) + " minute(s)\r\n";
                    } else {
                        if (parent.badLoginTable[i].length > 1) {
                            cmdData.result += (i + ' - ' + parent.badLoginTable[i].length + " records\r\n");
                        } else {
                            cmdData.result += (i + ' - ' + parent.badLoginTable[i].length + " record\r\n");
                        }
                    }
                }
                if (badLoginCount == 0) { cmdData.result += 'No bad logins.'; }
```

**Comment by si458** [comment]
One thing to try is try doing bad logins from multiple ip addresses within the 10min window
It might show the ip addresses then?

**Comment by Br0kenSilos** [comment]
Ok I ran it through on two different WAN IP's. You can that it is maintaining separate counts. But offers no other information.

![image](https://github.com/user-attachments/assets/46651803-cebb-4613-8f86-e93a07c14c94)

**Comment by si458** [comment]
@Br0kenSilos at least it's 50% helpful!
We blocked someone for x mins,
Im not gunna tell u who it was though 😂

**Comment by Br0kenSilos** [comment]
My friend and I did some additional testing and here is what we have discovered.. It will list the IP address and attempts UNTIL it bans the IP. Then it stops listing the IP address. 

So to do the test below, I went to a new IP and started testing, and ran badlogins after every attempt. Then once I got banned, I went to another IP address and started again.

![image](https://github.com/user-attachments/assets/27cd9a2b-6718-457c-8f67-7d1f61c7dc57)

**Comment by si458** [comment]
@Br0kenSilos thanks for testing!
So in this case it's simply a display issue then as it is recording the ip!
And i think it should say `ip - cooling off...`
So will get that changed!
I might add an option in maybe `badlogins ip`, then it will print an ip on each line so you know what's currently a bad ip
As u can use `badlogins reset` to remove the ip addresses from it's memory

**Comment by si458** [comment]
@Br0kenSilos do you want me to change it to the following:
`IP.IP.IP.X - Cooloff for X mins(s)` <- this ip has been banned
`IP.IP.IP.X - X attempts(s) until Cooloff ban` <- this ip attempted x times but not banned yet

**Comment by Br0kenSilos** [comment]
@si458 Yes, I think that would be great. Thank you Simon.

**Comment by si458** [comment]
done 👍
