### ISSUE TITLE
When I check "No Intel AMT" I get "No file access" flagged instead

### ISSUE THREAD

**Issue by Alessio71** [Ylianst/MeshCentral#652]
When I check "No Intel AMT" in user's device group permissions
![No Intel AMT](https://user-images.githubusercontent.com/24569704/68779803-886b7b00-0635-11ea-941c-45319daf841f.jpg)

at next opening, I find "No File Access" flagged instead
![No File Access](https://user-images.githubusercontent.com/24569704/68779898-b05ade80-0635-11ea-8445-cbf1ebea7a3d.jpg)

Thank you.
Regards,
Alex

**Comment by Alessio71** [comment]
What I was trying to achieve was to prevent to a user to modify the User Consent option, do anybody know how can I do this?
Thank you,
Alex

**Comment by MailYouLater** [comment]
@Ylianst: Not sure which is right, but these are different, and I think that's what's causing this issue.
https://github.com/Ylianst/MeshCentral/blob/45043b20cd1d36effe9f799407efa087ba6e40a4/views/default.handlebars#L7483-L7486
https://github.com/Ylianst/MeshCentral/blob/45043b20cd1d36effe9f799407efa087ba6e40a4/views/default.handlebars#L7577-L7580

**Comment by Ylianst** [comment]
Published 0.4.3-y with a fix for this. Let me know if it works. I also fixed the mobile application that has lots more issues in this area.

FYI: I am back in the office after a very long flights and here for 4 days then then traveling again next week. After that, I should be around for a while.

**Comment by Alessio71** [comment]
I've had an issue with the upgrade process (I'm on windows), after the update the meshcentral doesn't start anymore, I get an error in a variable not recognized. I had to leave the office for an emergency and to rollback the server, I'll try again tomorrow and then will be able post the error.
Thank you

**Comment by Ylianst** [comment]
If you can take a screen shot of the error and post it, that would be great. Thanks.

**Comment by Ylianst** [comment]
Also, check if it's related to #626?

**Comment by Alessio71** [comment]
The problem was related to the start of meshcentral as a service, the update broke the daemon part. I've decided to drop meshcentral on windows and moved to Ubuntu.
I had anyway to modify the meshcentral.service changing line
`Capabilities=cap_net_bind_service+ep`
with
`AmbientCapabilities=CAP_IPC_LOCK`
Everything works now with 0.4.4c
Thanks for everything,
Alex
