### ISSUE TITLE
Webrtc connections

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshCentral#6528]
I have added the appropriate webrtc options in config.json but dont think i am using webrtc.
```
"webRTC": true,
	"webrtcConfig": {
      "iceServers": [
        { "urls": "stun:stun.cloudflare.com:3478" },
        { "urls": "stun:stun.l.google.com:19302" }
      ]
    }
```

How can i tell if the connection is webrtc?

**Comment by kpetrow** [comment]
I think i can confirm that it is not using webrtc from checking chrome://webrtc-internals/ .  Test sites would pull up some info i don not see anything when trying to connect to the machine

**Comment by si458** [comment]
Webrtc only works if the remote device is local to ur device,
Currently, it doesn't work correctly with remote devices behind external firewalls 
But if it works it would show `Connected, WebRTC` after u click connect

**Comment by kpetrow** [comment]
thanks
