### ISSUE TITLE
Improvement suggestion - automatic logout inactivity

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#653]
Guys, good afternoon!

Ylianst, I would like to make the following improvement suggestion:

Deploying a feature, a button, or suddenly a menu within meshcentral that lets administrators report that after some remote access downtime, the system automatically disconnects all remote sessions that a technician has done and forgot to disconnect.

This feature would aim to eliminate the possibility of any technician leaving a remote access open unnecessarily, as it can often happen that someone minimizes or leaves the remote access screen to do something and forget to disconnect.

It's a feature that would add up to another suggestion I made, I don't know if you remember it was the feature of informing via a bar at the top of the remote user's screen (which will also allow the remote user to disconnect the technician) to know if the technician is still connected.

**Comment by penguinthingie** [comment]
This is a good suggestion but should be a switch to enable or disable like most features as there are reasons to leave it on when one is working on servers that require certain prolonged actions and require sessions to stay active.

**Comment by Ylianst** [comment]
Interesting. Yes, I need to look into this. This is a good suggestion.

**Comment by PathfinderNetworks** [comment]
Yep, just like with all other features like this, please make them optional.  For me, I don't operate MeshCentral in any way like geanferrani123 seems to and these options (if they were implemented as not being something we could turn on/off at the MeshCentral server level) would make it very difficult and very frustrating to use.  But, if they are optional (like most have been) then that's acceptable.

**Comment by Ylianst** [comment]
Agreed on the optional thing. Yes, the different type of usages covered by MeshCentral means we have to be careful that the server does not became frustrating for a group of users.

**Comment by si458** [comment]
@geanferrani123 you could try the `browserPing` feature in `config.json`
https://github.com/Ylianst/MeshCentral/blob/dd279d3ea268a82efad78e60c0e36d10c9f54764/meshcentral-config-schema.json#L452-L456

**Comment by si458** [comment]
this has been implemented,
you can set `userSessionIdleTimeout: 10` under `domains` in config.json (this example is 10mins)
then when it gets close to 10mins of the user not doing anything, 
it will display a disconnect/logout warning at the top,
then after 10mins, it will log the user out

![image](https://github.com/Ylianst/MeshCentral/assets/765314/53e261c3-903f-4ed7-a329-a7989a59c0e3)
