### ISSUE TITLE
Unable to install MeshAgent on Server 2025

### ISSUE THREAD

**Issue by CCWTech** [Ylianst/MeshCentral#6540]
**Describe the bug**
I get an error on installing on server 2025

**To Reproduce**
Install on Server2025

**Expected behavior**
Install

**Screenshots**
This is the error text:
[2024-11-17 07:41:30 AM] [AD262CB981431433] ..\microscript\ILibDuktape_ScriptContainer.c:1667 (0,0) uncaught: 'cannot read property \x27split\x27 of null'

**Client Device (please complete the following information):**
 - Device: Tower
 - OS: Server2025
 - Network: N/A
 - Browser: N/A

**Comment by si458** [comment]
Duplicate of this issue and fix is here too https://github.com/Ylianst/MeshCentral/issues/6162#issuecomment-2168031763

Fix is to install the wmic add-on first then install meshagent
OR
try the new agent builds here in the same post

**Comment by CCWTech** [comment]
Will do. Thanks!
