### ISSUE TITLE
You can't upload a file with a mobile phone, but you can do it with a computer!

### ISSUE THREAD

**Issue by bravery-only** [Ylianst/MeshCentral#6543]
**Describe the bug**
When we want to upload a file to the system (agent) with a mobile phone, it is not uploaded according to the image and remains like this.
**To Reproduce**
1. Go to 'Files'
2. Click on 'Upload'
3. Choice File 

**Screenshots**
![377822862-15cadb42-c157-4e3c-beb2-05ad3300e6e5](https://github.com/user-attachments/assets/a9f54ff6-b6f7-4222-89ac-77f7e997498e)

**Server Software (please complete the following information):**
 - OS: [Windows Server 2022]

 - Network: [WAN]
 - Version: [e.g. 1.1.33]
 - Node: [e.g. 20.0]

**Client Device (please complete the following information):**
 - Device: [Laptop & PC]
 - OS: [All win]
 - Network: [Remote over WAN]
 - Browser: [Google Chrome & Firefox & Edge]

**Your config.json file**
```
{
   "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json", 
   "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user\u0027s guide for details.", 
   "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.", 
   "settings": {
      "cert": "MyServer", 
      "wanonly": true, 
      "noagentupdate": 1, 
      "browserpong": 30, 
      "agentpong": 30, 
      "agentping": 30, 
      "_browserping": 30, 
      "_sessionkey": "MyReallySecretPassword1", 
      "port": 443, 
      "_aliasport": 443, 
      "_redirport": 80, 
      "_rediraliasport": 80
   }, 
   "domains": {
      "": {
         "_agentconfig": ["skipmaccheck=1"], 
         "title": "MyMesh", 
         "_title2": "Server", 
         "rootredirect": "https://www.mySite.com", 
         "_minify": true, 
         "_newaccounts": true, 
         "_usernameisemail": true, 
         "_welcometext": "Sample Text on Login Page.", 
         "_welcomepicture": "mainwelcome.jpg", 
         "_welcomepicturefullscreen": false, 
         "_titlepicture": "title-sample.png", 
         "_loginpicture": "title-sample.png", 
         "_meshmessengertitle": "MeshMessenger", 
         "_meshmessengerpicture": "messenger.png", 
         "agentcustomization": {
            "displayName": "MyMesh", 
            "description": "This software Install your system.", 
            "companyName": "Company", 
            "serviceName": "MyMesh", 
            "fileName": "MyMesh", 
            "image": "Update.png", 
            "installText": "Install Mesh Your System..."
         }, 
        
   }, 
   "letsencrypt": {
      "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let\u0027s Encrypt.", 
      "email": "myemail@mydomain.com", 
      "names": "mySite", 
      "skipChallengeVerification": false, 
      "production": true
   }, 
   "smtp": {
      "host": "smtp.gmail.com", 
      "port": 465, 
      "from": "mail@gmail.com", 
      "user": "mail@gmail.com", 
      "pass": "myPass", 
      "tls": true
   }, 
       
}
```

**Comment by si458** [comment]
you already opened an issue previously about this and you didnt respond so we closed the issue #6460

did you fill in the whole bug report correctly above?
as the config.json looks incomplete/very basic/missing information

**Comment by bravery-only** [comment]
I edited the configuration file and put the same server configuration file
The file cannot be uploaded with a mobile phone, but it is done with a computer.

**Comment by si458** [comment]
thank you,

what type of file are you uploading from your mobile phone to the remote device? pic/video/exe ?

what browser and OS is on your mobile phone and are you using?

**Comment by bravery-only** [comment]
Every file I upload stays in connecting mode as shown in the screenshot...
Browser : Firefox , Chrome    
OS : Android
I did not put the url

This problem occurred after the 1.1.32 update. There was no problem before that

**Comment by si458** [comment]
have you tried rolling back then to 1.1.31 and see if it fixes your issue?
1. stop meshcentral
2. cd `/meshcentralfolderhere`
3. `npm install meshcentral@1.1.31`
4. start meshcentral

**Comment by bravery-only** [comment]
I don't want to go back to the previous version. Is there no other solution?

**Comment by si458** [comment]
without confirming if an old version worked, we cant really help, 
because 1.1.32 updates changed 0% to do with file uploads,
so i cant see why 1.1.32 would stop it uploading as your config all looks correct,
so the must be something else blocking it inbetween possibly

**Comment by si458** [comment]
That's because the mobile site and desktop sites are 2 different pages, so ur issue is the mobile page.
But again I need to roll back to a version which it was working so we can check what changed

**Comment by si458** [comment]
ok ive just had 5 mins free to have a look, 
and indeed the is a bug in the mobile web ui, as im getting the same thing here,
im using 1.1.33, so im not sure what it broke but leave it with me and ill look into it

**Comment by si458** [comment]
all fixed! patch is 2 simple lines https://github.com/Ylianst/MeshCentral/commit/d0a51e90e9cf6c2124d73260dafbcf35c455ec49
bug was caused by this commit which was suppose to fix XSS vulnerability  https://github.com/Ylianst/MeshCentral/commit/04c96eb2ff3dcc57f220faf8256a092d25009b2a

**Comment by si458** [comment]
@bravery-only yes, or u can patch the `default-mobile.handlebars` file yourself from the commit and remember to use English hehe

**Comment by bravery-only** [comment]
> @bravery-only yes, or u can patch the `default-mobile.handlebars` file yourself from the commit and remember to use English hehe

thank you My problem is solved
