### ISSUE TITLE
Windows Server 2025 MeshAgent Installation Fails

### ISSUE THREAD

**Issue by nmincone** [Ylianst/MeshCentral#6551]
**Describe the bug**
Unable to install on Windows Server 2025

**To Reproduce**
Meshagent installer launches to black cmd screen then abruptly quits.

**Expected behavior**
Installer dialog never appears

**Screenshots**
N/A

**Server Software (please complete the following information):**
 - OS: Debian Bookworm
 - Virtualization: Docker
 - Network: LAN
 - Version: 1.1.33
 - Node: N/A

**Client Device (please complete the following information):**
 - Device: Proxmox VM
 - OS: Windows 2025 Server
 - Network: LOCAL
 - Browser: N/A
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 - Device: all LAN devices remoteing into Proxmox
 - OS: Windows/Mac OS
 - Network: Remote over LAN
 - Current Core Version (if known): 1.1.33

**Comment by si458** [comment]
duplicate https://github.com/Ylianst/MeshCentral/issues/6457 https://github.com/Ylianst/MeshCentral/issues/6433 https://github.com/Ylianst/MeshCentral/issues/6383

fix is here in this issue - https://github.com/Ylianst/MeshCentral/issues/6162

simply install wmic add on FIRST then install meshagent
OR
try the new agent from within the issue which DOESNT require wmic
(you must upload new agent to your meshcentral)

**Comment by nmincone** [comment]
Apologize, I'll work on my pre-search skills. Thank you!

**Comment by si458** [comment]
@nmincone no worries! we do have a new agent as explained, which i HOPE will be included in the next release,
then from 1.1.34+ it should be fixed when u download a new agent
just waiting for @Ylianst to verify everything first before i push the agent to the main repo!

**Comment by nmincone** [comment]
Appreciate all the work you guys are doing!
