### ISSUE TITLE
Virus Scan on File Transfers?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#656]
Hi Ylian,

Is there a file virus scanner on the file transfers? If so where is the data captured for that? If not does the ClamAv NodeJS look like a viable one? Here is an open source to try.
https://medium.com/@kainikhil/nodejs-file-upload-and-virus-scan-9f23691394f3

Also if there is this feature is there a quarantine location or even better a good solid indicator of captured virused files?

-SomeGuru

**Comment by penguinthingie** [comment]
I am not sure how a virus scan would come into the picture. There are tons of products that are good for just that solution without this product needing to get into the complexities of virus scanning. One more factor we don't need to try to shove into every open source project IMO.

Personally, i just don't want to have the Mesh Agent become bloated to include a scanner on top of it where i would have to worry that my existing anti malware solution within the workstation have to fight with another real time scanner which could also be another factor on slowing down the workstations.

**Comment by PathfinderNetworks** [comment]
I agree with penguinthingie.  I don't believe it's necessary and would just be added complexity.  The antimalware on both sides (the sender and receiver) should be adequate. Besides. if the person using MeshCentral is sending malware infected files to a remote device that's more of a HR/management issue that needs to be dealt with.

**Comment by MailYouLater** [comment]
I think @SomeGuru was probably thinking that the server would scan files when transferring them to/from the agent, which is less unreasonable than adding virus scanning to the agent, but I'm still not sure it's something that should be bundled into MeshCentral.

**Comment by Ylianst** [comment]
I just took a look at the NPM clamscan module and this is very interesting. If you have ClamAV running on your server, you can use this module to have ClamAV scan a file or a stream. This would not be available by default, but I can see that if you have it enabled in config.json, it would install the ClamScan module and use the settings to perform scans on files sent to MeshCentral or in-flight to a device.

No sure when I would get the time to do this... but yes, this would be cool. It's also not too difficult given the ClamScan module seems really nice.

**Comment by SomeGuru** [comment]
Due to there being more issues and this being low priority I am closing this request as this can happen in future if so desired.
