### ISSUE TITLE
Problem with uppercase characters in base path

### ISSUE THREAD

**Issue by zpuskaric** [Ylianst/MeshCentral#6564]
**Bug (or feature) description:**
I decided to put MeshCentral behind nginx reverse proxy and under non-root base path like:

https://myhost.mydomain.org/AaBbCc

in nginx I was passing location:
```
location /AbBcC {
        proxy_pass http://127.0.0.1:4443/AaBbCc
        proxy_http_version 1.1;
        proxy_hide_header content-security-policy;      
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        # Inform MeshCentral about the real host, port and protocol
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```
in MeshCentral config.json i had:
```
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    },
    "AaBbCc": {
      "title": "MC Server",
      "title2": "mine",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": false,
      "certUrl": "https://127.0.0.1:443/"
    }
```
I would get login screen but after logging I would get error 404.

**Steps to reproduce:**

put uppercase characters in base path in nginx config file (in this case AaBbCc)

**Expected behavior:**

To log into Meshcentral domain

**Resolution:**

After some time I noticed that returned URL converted all characters to lowercase and the request would not pass nginx.

After changing all AaBbCc paths to aabbcc in nginx and Meshcentral config files everything would work as expected.

Might help someone saving some time and head scratching.

```

**Comment by zpuskaric** [comment]
Correction:

location /aAbBcC should be location /AaBbCc

**Comment by si458** [comment]
fixed your formatting for you
this is an nginx issue and not a meshcentral issue
you should be using `proxy_pass http://127.0.0.1:4443/` from what im aware
because it will pass `/AaBbCc` to the backend when you visit it anyways

**Comment by si458** [comment]
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
you should end `proxy_pass` with `/`
or remove the `/AaBbCc` completely from the `proxy_pass`
