### ISSUE TITLE
OIDC cannot be used in an offline (docker) environment

### ISSUE THREAD

**Issue by useless-bit** [Ylianst/MeshCentral#6568]
**Describe the bug**
The MeshCentral Docker container is unable to start when OIDC is setup and the container has no access to the internet/NPM repository.

**To Reproduce**
1.    Setup a new docker container following/using the 'docker-compose.yml mongodb' example in the repo
2.    Create a new admin Account
3.    Setup OIDC in the config.json
4.    The container tries to install some libraries and fails

**Expected behavior**
The required library should already be included or installed.

**Log**
```shell
meshcentral  | Installing modules [ 'passport', 'connect-flash', 'openid-client@5.7.1' ]

meshcentral  | ERROR: Unable to install required modules. MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. To manualy install this module try:
meshcentral  | 
meshcentral  |    cd "/opt/meshcentral/meshcentral"
meshcentral  |    npm install --no-audit --no-optional --omit=optional passport connect-flash openid-client@5.7.1
meshcentral  |    node node_modules/meshcentral
meshcentral exited with code 0

```

**Server Software (please complete the following information):**
 - OS: Ubuntu Server 24 LTS
 - Virtualization: Docker (compose)
 - Network: Accessible through reverse proxy
 - Version: 1.1.34

**Additional context**
The VM has no access to the internet, the container is pulled from a private/local Docker registry. When the OIDC part is removed, the container is able to start.

**Your config.json file**
```json
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "mongoDb": "redacted",
    "cert": "redacted",
    "_WANonly": true,
    "_LANonly": false,
    "sessionKey": "redacted",
    "port": 8080,
    "aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80,
    "AgentPong": 300,
    "TlsOffload": "redacted",
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false,
    "agentTimeStampServer": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": true,
      "NewAccounts": false,
      "localSessionRecording": true,
      "_userNameIsEmail": true,
      "certUrl": "redacted",
      "authStrategies": {
                "oidc": {
                    "issuer": "redacted",
                    "clientid": "redacted",
                    "clientsecret": "redacted",
                    "newAccounts": true
                }
            }
    }
  }
}
```

**Comment by si458** [comment]
im not sure of a way around this,
the way meshcentral is setup is to be modular,
so when you run meshcentral it will install modules it needs based on what u want,
so in your case you wanna use oidc, so it installs the oidc modules
if you dont have access to NPM then you really are abit stuck in realtion to the docker image

**Comment by useless-bit** [comment]
Thanks for the reply.
What is the reason for this approach, if you don't mind me asking?

And would it be possible/feasible to create two different containers? 
One with only the base modules (basically the already existing one) and one with all potential modules pre-installed.

**Comment by si458** [comment]
the simple reason is size of the image,
the image is already currently nearly 1GB in size!
if we added more pages it would only increase in size!
you can however build the image yourself,
then you can edit the npm install command to install to install the 3 missing moodules :)

we could look at editing the docker image and it making multiple docker images but this would take some time,
if you wanted this i would recommend you open a new github issue as an enhancement request
then just explain in the issue you want multiple images for the different modules etc!

**Comment by useless-bit** [comment]
I see.
Guess I build my own Image then :)

Thanks for the Infos
