### ISSUE TITLE
IP & MAC information added to details tab

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#657]
Hi Ylian and team,

Could we get MAC address and IP address of systems on the details tab?

-SomeGuru

**Comment by penguinthingie** [comment]
![image](https://user-images.githubusercontent.com/51331094/68975035-2e4af100-07c0-11ea-9270-256aa24da3dc.png)

Or are you asking for an enhancement to take the same details and put it on "Details" as well?

**Comment by Ylianst** [comment]
This is a good idea, I can take a look at this.

**Comment by SomeGuru** [comment]
@penguinthingie,
Yes that is correct, as I am in visioning a single click location that has all active system information... Interfaces is a great start, but its not always something all the users look at or think to reference when sending in logs or information for assistance on their machine. That is why the request is to harbor the data into a system configuration tab.

**Comment by SomeGuru** [comment]
@Ylianst, I think this latest covers the details I was needing as far as MAC and other related with this issue... Can we close this in that regards?

**Comment by ryanblenis** [comment]
One thing before it's closed, but the details of a Mac and Windows machine seem to differ in that a Mac has less info. Not a game changer, but it's good to know the Subnet Mask of a machine in most cases.

Mac:
<img width="1547" alt="Screen Shot 2020-03-13 at 6 15 48 PM" src="https://user-images.githubusercontent.com/1929277/76663326-00e83700-6557-11ea-92fa-d6f4dc88ce93.png">
Windows:
<img width="1546" alt="Screen Shot 2020-03-13 at 6 17 12 PM" src="https://user-images.githubusercontent.com/1929277/76663327-0180cd80-6557-11ea-836b-993fda71c869.png">

**Comment by Ylianst** [comment]
@ryanblenis That would be a request for Bryan. I know getting all this information from different operating systems is difficult.

**Comment by krayon007** [comment]
I updated the agent code to add in some of the missing information, so when the agent update picks it up, the information shown should be consistent.
