### ISSUE TITLE
Postgresql no database name, username wil be used instead of default.

### ISSUE THREAD

**Issue by RoyalPeanut** [Ylianst/MeshCentral#6574]
### **Describe the Bug**  
After updating MeshCentral from version `1.1.30` to `1.1.35`, the application failed to start. The following error was encountered:  database "username" does not exist 
#### Configuration Block Before the Update   
```json
"postgres": {
  "host": "127.0.0.1",
  "user": "username",
  "port": 5432,
  "password": "password"
}  
```
### Sollution
Adding a database field to the configuration resolved the issue:
```json
"postgres": {
  "host": "127.0.0.1",
  "user": "username",
  "database": "meshcentral",
  "port": 5432,
  "password": "password"
}
```  
### Additional Notes
- Previously, the configuration worked without explicitly specifying the database field. However, after the update, this field seems to be required.  
  
"Maybe I am an idiot for not specifying the database field."

**Comment by si458** [comment]
no you are correct, the schema file shows it should default to `meshcentral` if you dont specify one
so BUG, looking into it for you 👍

**Comment by PTR-inc** [comment]
@si458 Shall I look into this? As I already did some work on the db part, save you some time

**Comment by si458** [comment]
@PTR-inc yes plz if u have chance! i couldnt get postgres working in docker haha!

**Comment by PTR-inc** [comment]
Found it, var typo: connectinArgs.Database should be connectinArgs.database #6576

**Comment by si458** [comment]
@RoyalPeanut ok all fixed then! single fix here for you if you wanna patch the file yourself to get up and running!
https://github.com/Ylianst/MeshCentral/commit/f9228ad0eb1dff256f246ffec47233d2e1338f71

**Comment by RoyalPeanut** [comment]
Thanks for the swift fixs👍
