### ISSUE TITLE
Unable to Install Agent - Windows 11 x64 - MC 1.1.35

### ISSUE THREAD

**Issue by jiriteach** [Ylianst/MeshCentral#6577]
Meshcentral Server running 1.1.35 on Ubuntu 24.10 natively.

Fresh Windows 11 installation running on a Dell Optiplex.

Download the agent from Meshcentral. 
Agent is background and interactive for x64 - try and run it and nothing shows. 

Try and run via cmd and I get - 

`
[2024-12-03 04:22:24 PM] [AD262CB981431433] ..\microscript\ILibDuktape_ScriptContainer.c:1667 (0,0) uncaught: 'cannot read property \x27split\x27 of null'
`

Any ideas on how to resolve this?

**Comment by jiriteach** [comment]
Needed WMIC installed :)

**Comment by si458** [comment]
Correct or try using the new agents which are located inside the `test_agents` folder which don't require the wmic being installed first!
