### ISSUE TITLE
Since the 1.1.35 Update the BitLocker recovery key can no longer be displayed

### ISSUE THREAD

**Issue by NilsLeumann** [Ylianst/MeshCentral#6582]
Since the recent 1.1.35 (or 1.1.34, I jumped fron 1.1.33 directly to 1.1.35) the BitLocker recovery Key button is missing on all Windows Agents (Windows 10 and 11)
I'm running MeshCentral on an Ubuntu Server 22.04 Container in Proxmox
<img width="315" alt="Bildschirmfoto 2024-12-04 um 22 56 06" src="https://github.com/user-attachments/assets/93e54ee5-7c0e-4f6b-87d6-b7acb2ff06ec">
Next to "Fully Encrypted" there used to be a blue symbol to show the Bitlocker recovery key
Hope this Bug Report is okay, let me know if you need any further Infos
Thanks for your amazing work on MeshCentral!

**Comment by si458** [comment]
I hate windows and it's stupid wmi

I'll try have a look tomorrow for u and see what's gone on

**Comment by PTR-inc** [comment]
Can confirm it went with 1.1.35, in 1.1.34 the popup arrow is there. Reverting to 1.1.34 gives it back.

**Comment by si458** [comment]
@PTR-inc it will be the bitlocker code inside computer-identifiers.js, it's just not running the code or maybe something else

I just don't have any devices anymore that use bitlocker!

We dont all have fancy computers "Microsoft" that can run Windows 11 officially hehe

**Comment by PTR-inc** [comment]
I'll have a look at it as soon as my flu-ridden brain allows me to

**Comment by PTR-inc** [comment]
Quick check confirms it is indeed commit c41eb72 with computer-identifiers.js

**Comment by si458** [comment]
@PTR-inc I'm in the same boat! Bloody flu season for me, even after having the flu jab to help haha 
Yes that commit was me fixing win7/server2008r2 support, but I'm sure the bitlocker was still working?
Maybe I missed something!

**Comment by PTR-inc** [comment]
Well, that's at least this bug squashed. Now some pills. Bummer the jab didn't help.
