### ISSUE TITLE
Right click context menus overridden by Edge on Win11

### ISSUE THREAD

**Issue by Dukiverse** [Ylianst/MeshCentral#6583]
Only recently upgraded one of my PCs to Win11 and noticed in MeshCentral (latest ver. 1.1.33 to 1.1.35), right clicking to bring up any of the quick-access menus such as the Connect/Disconnect button to ask consent with privacy bar, or disconnect and lock get overridden by the "modern" context menu in Microsoft Edge ver. 131.0.2903.70:

![image](https://github.com/user-attachments/assets/c26ad8ab-c2ef-4885-b423-5ffb8cd8b522)

The same also occurs when trying to right click within a remote desktop session, often requiring you to click off the page to uncover the context menu that opens below it:
![image](https://github.com/user-attachments/assets/de44e9fc-01a0-47b2-b092-e84e1e59eb11)

**Comment by Otsegox** [comment]
I just upgraded to 1.1.35, and I tested this.  No problem for me. Windows 11, and using Edge.  
![image](https://github.com/user-attachments/assets/95c035b5-61a3-4641-937c-59a2338d286d)
But I do have the old right-click menu forced, so I don't have the crappy Windows 11 right-click menu.

**Comment by si458** [comment]
same here, using edge, windows 11, no problems? Version 131.0.2903.70 (Official build) (64-bit)
right click and works perfectly fine?
are u running any plugins or addons maybe in edge?
![image](https://github.com/user-attachments/assets/94055326-cf15-4aeb-b395-7bf45b596f27)
![image](https://github.com/user-attachments/assets/310810ef-2feb-4a76-8280-7f075414741f)

**Comment by vitko-bg** [comment]
Tested on Win 11 23H2 in Edge browser with no issues. Working as expected with no problems. Old right-click menu on Win 11 is not forced, all settings are default.

**Comment by Dukiverse** [comment]
> same here, using edge, windows 11, no problems? Version 131.0.2903.70 (Official build) (64-bit) right click and works perfectly fine? are u running any plugins or addons maybe in edge? ![image](https://private-user-images.githubusercontent.com/765314/392842766-94055326-cf15-4aeb-b395-7bf45b596f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDg1NDQsIm5iZiI6MTczMzUwODI0NCwicGF0aCI6Ii83NjUzMTQvMzkyODQyNzY2LTk0MDU1MzI2LWNmMTUtNGFlYi1iMzk1LTdiZjQ1YjU5NmYyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxODA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDdkOTdiNmQ2YzQyMzc0NWM5NzBkOGQxMzBjMmRlZGI4N2Q3MWQwNGExYjE1ZDdkYmQ2MDIzN2JkMGJiZjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gAR47cXkJWj7cOVowq27iZl_k3yk9LiSxlBxsp5Dw0U) ![image](https://private-user-images.githubusercontent.com/765314/392842645-310810ef-2feb-4a76-8280-7f075414741f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDg1NDQsIm5iZiI6MTczMzUwODI0NCwicGF0aCI6Ii83NjUzMTQvMzkyODQyNjQ1LTMxMDgxMGVmLTJmZWItNGE3Ni04MjgwLTdmMDc1NDE0NzQxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxODA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGRlMjQzYmZkZDQzYzAyOTIxODhjMzA5NzM5MDkwNjkwZTQ2Nzc1ZWJmNWNmNTQ5NTNjMWQ0ZGEwNjBhMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kPrWG6E89XGerJEWI6NY5gCHef4QbMdXA-jeS3TQ2jA)

You got it - I ran Edge with the —disable-extensions flag and it is working fine. So strange because I haven’t gotten any new extensions since Win10 so not sure which is causing but I am going one by one. Thank you - I didn’t even think to check that!
