### ISSUE TITLE
OIDC account get 2FA notification

### ISSUE THREAD

**Issue by svenwanzenried** [Ylianst/MeshCentral#6597]
**Describe the bug**
2FA notification pops up at every login with account provided by oidc

**To Reproduce**
1. Setup Meshcentral with oidc login
2. login as user
3. see notification to enable 2FA

**Expected behavior**
Since oidc accounts are not able to enable 2FA (which is in my case already performed by the Identitiy Provider), the notification should be silienced, even when single2factorwarning is not set to false in config

**Screenshots**
![image](https://github.com/user-attachments/assets/8df14ae8-c127-4f5f-bda2-322430a9965f)

**Server Software (please complete the following information):**
 - OS: Debian
 - Virtualization: Proxmox/Docker
 - Network: LAN/WAN, reverse proxy, ssl offload
 - Version: 1.1.35
 - Node: [e.g. 18.4.0]

**Client Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10 22H2
 - Network: Remote behind reverse proxy
 - Browser: Google Chrome
 - MeshCentralRouter Version: N/A

**Remote Device (please complete the following information):**
 N/A

**Additional context**

**Your config.json file**
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "settings": {
    "cert": "mesh.domain.tld",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "xxx",
    "port": 443,
    "_aliasPort": 443,
    "redirPort": 80,
    "_redirAliasPort": 80,
    "RelayDns": [ "meshrelay1.domain.tld", "meshrelay2.domain.tld" ],
    "AgentPong": 60,
    "BrowserPong": 3,
    "TLSOffload": "nginx-proxy-manager",
    "SelfUpdate": false,
    "AllowFraming": "false",
    "WebRTC": "false",
    "AutoBackup": {
      "backupPath": "/opt/meshcentral/meshcentral-backups",
      "backupInvervalHours": 24,
      "keepLastDaysBackup": "10",
      "zippassword": "xxx"
    },
    "authLog": "/opt/meshcentral/meshcentral-data/auth.log"
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "NewAccounts": "false",
      "_userNameIsEmail": true,
      "certUrl": "https://nginx-proxy-manager:443",
      "authStrategies": {
        "oidc": {
            "issuer": "https://auth.domain.tld",
            "clientid": "xxx",
            "clientsecret": "xxx",
            "NewAccounts": true,
            "groups": {
              "siteadmin": ["admins"],
              "scope": "groups"
            }
        }
      }
    }
  },
  "messaging": {
    "pushover": {
      "token": "xxx"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "_email": "myemail@mydomain.com",
    "_names": "myserver.mydomain.com",
    "production": false
  }
}
```

**Comment by si458** [comment]
your config.json doesnt show `single2factorwarning` being set
you should set it like below
```
{
  "domains": {
    "": {
      "passwordRequirements": {
        "single2factorwarning": false
      }
    }
  }
}

**Comment by svenwanzenried** [comment]
I understand that i could do that.  But I don't want to, since the local users (even if its only the admin) should have 2FA notification enabled. Could i just set it just like this? That would solve my problem.

```
{
  "domains": {
    "": {
      "authStrategies": {
        "oidc": {
          "single2factorwarning": false
        }
      }
    }
  }
}
```

However, the fact that the notification appears even though this account type (oicd) is prevented from enabling 2FA, is a bug IMHO. It's a minor bug, without question, but i thought it was worth bringing to attention.

**Comment by si458** [comment]
> I understand that i could do that. But I don't want to, since the local users (even if its only the admin) should have 2FA notification enabled. Could i just set it like this? That would solve my problem.
> 
> ```
> {
>   "domains": {
>     "": {
>       "authStrategies": {
>         "oidc": {
>           "single2factorwarning": false
>         }
>       }
>     }
>   }
> }
> ```
> 
> However, the fact that the notification appears even though this account type (oicd) is prevented from enabling 2FA, is a bug IMHO. It's a minor bug, without question, but i thought it was worth bringing to attention.

no that wouldnt work because it only works inside the main domain section of the json

altho weirdly enough ive just tested here and i dont get a 2fa notification at all when a new user logs in
i use authentik for my oidc provider for testing, whos ur provider?
is your config.json complete above and not missing info at all?

**Comment by svenwanzenried** [comment]
Thats strange, I use Authelia as IdP.
Yes, the above config is complete. Except the obvious obfuscation of keys etc.

**Comment by si458** [comment]
@svenwanzenried one thing to try is
1. login as admin
2. delete the user from meshcentral,
3. use private browsing and login with the user account
4. new account should be created and fingers crossed no notification

if you get a notification then something is not right with your setup and more investgating would be needed

**Comment by svenwanzenried** [comment]
That did it! Thanks 😊
I have now a new account without notification.

**Comment by si458** [comment]
chances are its a browser cache issue! or a cookie issue!
try clearing ur cookies for your meshcentral domain and trying again if needs be 👍
