### ISSUE TITLE
Install plugins fails

### ISSUE THREAD

**Issue by Belvedus2** [Ylianst/MeshCentral#6600]
**Describe the bug**
Hi,
When i try to install a plugin in mesh, mesh service restart.
After the restart, the plugin is not install.
In error log, i have that : 

```
-------- 11/12/2024 15:06:22 ---- 1.1.35 --------

node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v18.19.0
```

I have try these plugins : ScriptTask, EventLog and DevTools.
I can't know if this issue is due to our company's proxy or to our installation of MeshCentral.

**To Reproduce**
 1 - Add plugins URL to the plugin menu.
 2 - In the drop-down list, choose "Install"
 3 - Click "OK" in popup message.
 4 - *Server disconnection* 
 5 - After 5 to 10 second, the server come back.

**Screenshots**
![image](https://github.com/user-attachments/assets/9b5ce0f3-e5eb-4690-960c-b38a13cc34f9)

**Server Software (please complete the following information):**
 - OS: Windows Server 2022 (sorry, company's rule)
 - Network: LAN
 - Version: 1.1.35
 - Node: 18.19.0

**Comment by si458** [comment]
Plugins are not officially supported, we just provide an interface but no guarantee plugins will work or run
You should contact the the plugin developer and ask them to verify it works with the latest meshcentral version

**Comment by Belvedus2** [comment]
Ok, thank you for the answer.
