### ISSUE TITLE
uac promts get black screen

### ISSUE THREAD

**Issue by Raxiel1987** [Ylianst/MeshCentral#6601]
i know i read in the old discussion about this,
but i need to get the agent works in interactive mode, when i'm facing the uac prompts i have to disconnect and reconnect, this is frustrating because the user in the remote host must accept.
is there a workaround to maybe disable automatically the uac or send "uac interactive" command  when the agent is launched?

**Comment by si458** [comment]
You haven't followed the bug template report, because of this we cannot assist u or even replicate ur environment to check for problems
Please open a new github issues then copy the whole bug template and reply back with the information filled in

**Comment by si458** [comment]
duplicate of #6602
