### ISSUE TITLE
Disable update from web dashboard

### ISSUE THREAD

**Issue by risturiz** [Ylianst/MeshCentral#6608]
Hi, any chance to disable upgrade from dashboard at all?... Its like have more control over upgrades when you use docker.

Thanks!

**Comment by si458** [comment]
Will get it sorted!

**Comment by si458** [comment]
well this is embarassing, this feature already exists 🤣 
```
"domains": {
  "": {
    "myServer": {
      "upgrade": false
    }
  }
}
```

**Comment by risturiz** [comment]
This is great :-) ... Thanks for your fast support
