### ISSUE TITLE
Mesh Central appears to be launching two instances on start

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#661]
Not sure why or how, but it appears that running the systemctl start causes it to launch twice.  

mike@mesh:~$ sudo systemctl stop meshcentral.service

mike@mesh:~$ ps aux | grep mesh

mike      4121  0.0  0.0  14852  1004 pts/0    S+   04:58   0:00 grep --color=auto mesh

mike@mesh:~$ sudo systemctl start meshcentral.service

mike@mesh:~$ ps aux | grep mesh

mike      4126 49.5  3.9 1087828 67852 ?       Ssl  04:58   0:00 /usr/bin/node /home/mike/node_modules/meshcentral

mike      4146  119  4.7 1162556 82600 ?       Sl   04:58   0:01 /usr/bin/node /home/mike/node_modules/meshcentral --launch 4126

mike      4175  0.0  0.0  14852  1072 pts/0    S+   04:58   0:00 grep --color=auto mesh
mike@mesh:~$

**Comment by Ylianst** [comment]
Can you show the content of the "/etc/systemd/system/meshcentral.service" file?

**Comment by Ylianst** [comment]
This is normal. When you start MeshCentral, it will start as a "parent" and launch a child that will do all the actual work. This is done because when MeshCentral performs a self-upgrade or certificate change, it must restart. The child terminates and the parent starts a new child with the updated code and/or settings. Only the child, in this case the process called "meshcentral --launch" will open the ports and start listening for incoming connections. Hope it helps.

**Comment by mikecole79** [comment]
`
mike@mesh:~$ cat /etc/systemd/system/meshcentral.service
[Unit]
Description=MeshCentral Server
[Service]
Type=simple
LimitNOFILE=1000000
ExecStart=/usr/bin/node /home/mike/node_modules/meshcentral
WorkingDirectory=/home/mike
Environment=NODE_ENV=production
User=mike
Group=mike
Restart=always
# Restart service after 10 seconds if node service crashes
RestartSec=10
# Set port permissions capability
SecureBits=keep-caps
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
[Install]
WantedBy=multi-user.target
`

**Comment by mikecole79** [comment]
The issue with node taking up ports 80 and 81 doesn't appear to be a problem any longer after updating to 0.4.4-j, which prompted this ticket in the first place.  I still show 2 processes running, but as you explained, they are the parent and child processes, as expected.  I'll close this.  

Thanks as always for the help!
