### ISSUE TITLE
Unable to get Let's Encrypt certs

### ISSUE THREAD

**Issue by mikecole79** [Ylianst/MeshCentral#662]
Per troubleshooting, found that port 80 and 81 were both being listened to by node, but received this:

mike@mesh:~$ node node_modules/meshcentral --debug cert
MeshCentral HTTP redirection server running on port 81.
CERT: Initializing Let's Encrypt support
CERT: Getting certs from local store
ERROR: Redirection web server must be active on port 80 for Let's Encrypt to work.
MeshCentral v0.4.4-i, WAN mode.
MeshCentral HTTPS server running on mesh.colecomputerservices.com:444.
SMTP mail server smtp.gmail.com working as expected. 

After updating to 0.4.4-j [From Ticket 661](https://github.com/Ylianst/MeshCentral/issues/661) this issue has gone away, however, I am receiving different errors when trying to get the encryption working.  Specifically, a length=0 issue, per below.  

node node_modules/meshcentral --debug cert
MeshCentral HTTP redirection server running on port 80.
CERT: Initializing Let's Encrypt support
CERT: Getting certs from local store
ACME Directory URL: https://acme-staging-v02.api.letsencrypt.org/directory
CERT: error: {"length":0}
CERT: Unable to get certs from local store (Staging)
MeshCentral v0.4.4-j, WAN mode.
MeshCentral Intel(R) AMT server running on mesh.colecomputerservices.com:4433.
MeshCentral HTTPS server running on mesh.colecomputerservices.com:443.
SMTP mail server smtp.gmail.com working as expected.
CERT: Checking certs (Staging)
CERT: error: {"length":0}
CERT: Checks completed (Staging)

Not sure what's happening here.

**Comment by Ylianst** [comment]
Ok, you are the 3rd person to report the same issue, the two others are here #658. I am investigating this now.

**Comment by mikecole79** [comment]
Thank you, I appreciate it.  FYI, your support is absolutely top-notch.
REALLY appreciate the awesome app and support you provide.


[image: Cole Computer Services, LLC] <http://www.colecomputerservices.com/>



*Mike Cole*

*mike@colecomputerservices.com <mike@colecomputerservices.com>*


*253-234-5234http://www.colecomputerservices.com
<http://www.colecomputerservices.com/>*

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.4-k with more Let's Encrypt logging. Can you update, try again and post the results? Thanks.

**Comment by mikecole79** [comment]
Done, posted it on 658.

Thanks!


[image: Cole Computer Services, LLC] <http://www.colecomputerservices.com/>



*Mike Cole*

*mike@colecomputerservices.com <mike@colecomputerservices.com>*


*253-234-5234http://www.colecomputerservices.com
<http://www.colecomputerservices.com/>*

**Comment by Ylianst** [comment]
Just figured out the problem, you need Node v10.12.0 as posted on #658.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.4-n that checked the NodeJS and displays a warning if it's too old and Let's Encrypt needs to be used. I am going to close this issue, feedback welcome on #658.
