### ISSUE TITLE
Lock machine after disconnect

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#663]
Hi
Im looking for a feature to automaticaly lock machine after i disconnect desktop session.

Thanks

**Comment by MailYouLater** [comment]
Duplicate of #270 & #649.

**Comment by Ylianst** [comment]
Seems like a frequently asked feature. I think other commercial solutions have this.

**Comment by alesribic73** [comment]
Not implemented yet? Plans?

**Comment by MailYouLater** [comment]
As [stated](https://github.com/Ylianst/MeshCentral/issues/649#issuecomment-553620783) by ryanblenis in #649, a hook to allow plugins to perform an action when disconnecting from a KVM session is in his fork, and assuming Ylianst accepts his next pull request when he makes it, MeshCentral will support the ability to make a small plugin that adds this ability, or a more complex one that could do more (like asking if you want to lock the computer and/or log a custom event when you disconnect).

**Comment by alesribic73** [comment]
Thanks for clearing this out.

**Comment by alesribic73** [comment]
CLosing
