### ISSUE TITLE
Shared host on two users

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#664]
I would like to know if it is possible that two validated users on the dashboard can access the same host, that is, the same host can be listed for two central users?
Thanks

**Comment by Ylianst** [comment]
Hi. Yes. Once you great a group of devices, you can share that group with other users with all or limited permissions. Click on the group, hit "Add Users" and type a username and select permissions. Hope this answers it.

![x](https://user-images.githubusercontent.com/1319013/69179577-9e0ef380-0ac0-11ea-8ee0-87e4e07c5034.png)

**Comment by edorbike** [comment]
Ok,  perfect.
Thanks
