### ISSUE TITLE
Mac Machine connected to remote console, causes Remote Keys being repeated sometimes & special characters not accepted

### ISSUE THREAD

**Issue by vish84** [Ylianst/MeshCentral#665]
I have a user, whos using a mac. When they connect to a remote console for a machine that is running  ubuntu 14.04 (remnux specifically). The command key on a mac is not being accepted, i.e. so pressing command c, wont do anything on the terminal. The other issue is they are unable to type any special chars. The Keyboard Layout on the User and the remote machine is EN-US

I will try and get a hold of a mac to do some further testing. I know the user has tried from Safari browser, and from a Ubuntu machine running firefox (VM) on there mac, but the same issue occurs.  

From a windows machine this seems to work fine.

Makes me think its something related to the underlying host being used.  Mac is on the latest OS

The repeated keys occurs on some occasions, where on the remote terminal it will repeat the character, seen this occur with e and c

**Comment by vish84** [comment]
Ignore this, the end user was doing something incorrect.

**Comment by MailYouLater** [comment]
@vish84: It would be really nice if you could explain what the end user was doing that was incorrectly and what they should have been doing different so that if someone else comes here because they're experiencing the same issue they will find a solution to their problem.

**Comment by vish84** [comment]
The user had not set the default language on there host to en-us, they had left it to en-gb. They had added the additional keyboard layout but not set it to default. Once this was done, they were able to successfully use the command key and special characters. You also need to ensure the remote keyboard input is set to en-us.

**Comment by MailYouLater** [comment]
Thanks.
Sounds like this is related to #469.
