### ISSUE TITLE
MeshCentral Router for Windows

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#669]
Downloaded this >> http://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe
From this page >> https://software.intel.com/en-us/blogs/2019/03/28/meshcentral2-all-new-meshcentral-router-for-windows

works really well.
I'd like to save 'active port mappings' for a user.

My plan would be to set the user up on the server as a user with a group.
On their other pc (eg home) , download the meshCentralRouter.exe, and run it.
Logging in (using TFA), then they would simply need to click the 'open' button for the machine that they want to RDP to. Ideally the meshcentralrouter settings would be saved and modifiable from the mesh server.

Is that possible currently, or could it be possible?

**Comment by OutbackMatt** [comment]
Thinking a bit more about this...

Local port sometimes can't be accessed as it may be in use.
Local port could be set 'on the fly' from a user customisable range.

This effectively allow a custom app that clients could use to access remote machines with TFA

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-q with improved MeshCentral Router. Feedback appreciated.

![MC2-MeshRouter](https://user-images.githubusercontent.com/1319013/77222200-58b20f80-6b0e-11ea-9f91-7971a9ca3482.png)
