### ISSUE TITLE
Mesh Central Windows Service Stops

### ISSUE THREAD

**Issue by lancek541** [Ylianst/MeshCentral#67]
I have installed MeshCentral on a windows 2012 R2 server.  Everything works except that the meshcentral windows service keeps stopping and I have to manually start the service then after a few minutes it stops.  Has anyone else ran into this issue before?

**Comment by Ylianst** [comment]
Since this issue happened just after the v0.2.5-l release, I am going to assume that was the problem. If it happens again, please reopen this issue.
