### ISSUE TITLE
Windows 10 1903 - Chrome RDP Fails to launch, IE RDP Launches no issue.

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#672]
Hi MeshCentral Team,

I noticed today that if you invoke the RDP button on Chrome it forces you to download, and then the application doesn't run for the user... However if you use the Win10 1903 in box IE the application kicks off the installation. Is this something the can be resolved for Chrome to exhibit like IE does?

Thanks,
SomeGuru

**Comment by PathfinderNetworks** [comment]
I don't believe so.   That function requires a browser that supports Microsoft ClickOnce. It does work in Edge as well.

**Comment by Ylianst** [comment]
@PathfinderNetworks is exactly right. The "RDP" option requires Microsoft ClickOnce which is only natively available on IE, but you can download plug-in's for Chrome and FireFox that will do that.

**Comment by SomeGuru** [comment]
I will have the intern go back and read through, originally she said she didn't see anything referenced to the regards... However good to know... I will get those plugins and try it... :)

**Comment by penguinthingie** [comment]
This is normal of ClickOnce technology from Microsoft. Firefox and Chrome cannot natively execute ClickOnce deployed applications for same reasons Microsoft creates propitiatory codebases. Similar to Java needing a JVM to run and Java Runtime Engines have their own complexities on how they communicate with browsers.

**Comment by SomeGuru** [comment]
wouldn't you know it, my AV seems to block that extension for Chrome. Attempted to install multiple different ones and it comes back that its missing .net 2.0 that doesn't install on Windows 10 1903. So I guess this is mute point. I will close this as it looks to be a limitation in my organization.
