### ISSUE TITLE
Apple phone issues (Not mine)

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#673]
Hi MCAgent Dev,

I found that Apple doesn't have the same ability to get files like that of Android users. It rejects the download. Can this be resolved?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
I don't have an iPhone, but I do have an iPad I can try. Let me know if your using the full desktop web site or the mobile site with reduced features.

**Comment by SomeGuru** [comment]
They attempted on both, apparently they hit this when in mobile, and then flipped over to desktop and still the devices failed to enumerate download. I asked them to log out and back in, and the phone looks to start a file action but doesn't actually start any transfers to them. This may be a limitation with this new IOS version they are all running... Wasn't seen the same way on a previous generation device that was down revved on IOS.

**Comment by MailYouLater** [comment]
Could you please state what version(s) of iOS you're seeing the issue on, and if you have any devices that are transferring the files correctly, what version(s) of iOS are they running?

**Comment by SomeGuru** [comment]
Sorry, just getting back to this, I will reach out and get the IOS version as I am not effected on my Android, but they are on their Apples...

**Comment by SomeGuru** [comment]
Validated to work on Safari and Firefox browsers on IOS 16.5 and 17.0. So only an issue with Chrome on IOS devices. Expected behaviors with CHROME as other RMM does exactly same results.

SomeGuru
