### ISSUE TITLE
Lets Encrypt not renewing

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#674]
I notice that my server has only a week or so before it's LE certificate expires.  Does MC2 automatically set up the renewal (as certbot does on other LE servers that I have) and therefore I don't have to worry about it, or is there something else that I need to be looking at?  Normally they renew within 30 days of expiration...

**Comment by johnnyq** [comment]
Maybe because a7f823ebc37cfba5a4d5427dfb999ddc6579ef80

it looks like greenlock was removed as a dependency maybe accidentally

**Comment by D4V3M0NK** [comment]
Apologies, I should've stated that I'm running 0.4.2.U on the server, so that shouldn't have affected me?

**Comment by Ylianst** [comment]
The GreenLock dependency should be removed as MeshCentral installs GreenLock dynamically when your configure to use it.

MeshCentral should auto-renew the certificate, but we just moved to GreenLock v3 so, if you update your server, you will get a new certificate as we have a completely new Let's Encrypt system in MeshCentral now.

If you want to keep your old server, you can backup and rename the "meshcentral-data/letencrypt" folder and restart the server. It will go fetch a new certificate. Be aware that Let's Encrypt is removing support for the old protocol on December 1st, so you will not be able to renew the cert after that using the older server.

Hope that made sense.
Ylian

**Comment by D4V3M0NK** [comment]
So I've updated my server to the latest and greatest and now I've got a privacy issue with the certificate. The CN looks ok but at this point I'm not too sure what to do.  Can I remove 
![Screenshot from 2019-11-22 12-49-09](https://user-images.githubusercontent.com/7572742/69459486-b54f1a80-0d26-11ea-8082-9c162f356158.png)

**Comment by D4V3M0NK** [comment]
:( and now I can't log in - it states that there's privacy issues, which I have to accept (Chrome) and then I get a message stating that there's an error with being "unable to connect web socket - try again"

**Comment by D4V3M0NK** [comment]
Do I need to manually remove the Greenlock dependency? I didn't do that... but I don't want to move forward too much on this until I hear back from you fine folks!

**Comment by MailYouLater** [comment]
That 'privacy issue' your browser is reporting is because MeshCentral is operating using a self signed certificate.  This is the default configuration, and it reverts to this temporarily if the letsencrypt cert can't be found, then when it gets the new letsencrypt certificate it should automatically switch to it.
If it's still using the self signed cert, then it either hasn't received the letsencrypt cert yet (I hear it can take a while sometimes, but I'm not sure how long to recommend you wait), or something is wrong and it can't get the letsencrypt cert.

Can you go into the folder where your `meshcentral-data` and `node_modules` folders are and run `npm list meshcentral` and `npm list greenlock` to show what versions of each you have installed?

I have a strange feeling that you might still have greenlock v2 but have one of the newer versions of MeshCentral that uses greenlock v3.

**Comment by D4V3M0NK** [comment]
└─┬ meshcentral@0.4.4-r 
  └── meshcentral@0.4.4-r  deduped

**Comment by D4V3M0NK** [comment]
└── greenlock@3.1.5

**Comment by D4V3M0NK** [comment]
Also, at this point I can in fact log into MC2 again ... still getting the license issue, but I can at least see all my systems...

**Comment by johnnyq** [comment]
yes same here as well, when I did an update it broke letsencrypt

**Comment by D4V3M0NK** [comment]
To be honest I can't remember if I installed LE manually outside of MC2, or had MC2 install it automatically. I **think** it was the former...

**Comment by Ylianst** [comment]
Hi. First thing is to update your NodeJS to 10.12 or better. The latest version of MeshCentral will only support fetching a Let's Encrypt certificate with this node version of above. If you run MeshCentral manually, you will see this as a warning, but if you run as a background task, you will not (but I need to fix that).

Also, if you have a TLS certificate with the issuer common name that starts with "MeshCentralRoot-*" then this is the default certificate that MeshCentral generates and uses when it does not yet have a Let's Encrypt certificate.

If you have NodeJS 10.12+ and want to quickly debug this, stop MeshCentral and run is manually using:

`node node_modules/meshcentral --debug cert`

Or, you can edit the config.json and add in the settings section:

`"log": "cert"`

Then, when you restart the server, it will create a log.txt file in "meshcentral-data" with the Let's Encrypt messages. The new certificate will show up in "meshcentral-data/letsencrypt3-staging" and "meshcentral-data/letencrypt3". MeshCentral will first get a staging certificate to make sure everything is ok.

Hope it helps,
Ylian

**Comment by johnnyq** [comment]
Thank you @Ylianst  I rebooted the server it seemed to fix it thanks again

**Comment by D4V3M0NK** [comment]
FYI before I did anything, I have NodeJS 11.12.0 installed.

I stopped MC2 and ran the debug cert command, which seemed to run a number of checks (I have the responses copied if it's helpful?) including what looked like getting a new certificate, then ended up running MC2 in command line mode (ie, didn't return to the prompt until I Ctrl + C out of it). Whilst running in command line mode, the certificate was good for another 3 months, I could log in without issue and all users and systems were present.

I then rebooted the server to ensure all would come back up as expected and it did.

Many thanks for the pointers Ylian!  I'll be closing this issue.

**Comment by D4V3M0NK** [comment]
One thing to note on this - all my router files ("meshaction.txt") that I had downloaded to use locally needed updating since this happened. The server hash is different.

**Comment by MailYouLater** [comment]
@D4V3M0NK: Did you delete any of your `.crt` or `.key` files from your `meshcentral-data` folder?  I'm pretty sure the server hash should only change if the `agentserver-cert-private` files are missing, or if they have to be regenerated because they no longer have a proper chain of authority leading back to the `root-cert` files.

**Comment by D4V3M0NK** [comment]
@MailYouLater no, I didn't delete anything (it's just not in my genes)  I'm not too worried about it, a simple inline sed replacement updated all my files without issue.  I did get to wonder though if it's linked to the LE certificate and, if so, then potentially that'll happen every 90 days for me.  We'll see - nothing overly troubling to deal with on my end.

**Comment by MailYouLater** [comment]
Isn't that server hash supposed to be what the MeshAgents compare with to know if it's OK to connect to the server though? in which case, if it changed, then all of your computers shouldn't be able to connect either.  Maybe I'm looking at it wrong, but if I'm right, this could indicate the presence of a major security issue that just hasn't been brought to light yet, or just a minor bug, not sure.

**Comment by D4V3M0NK** [comment]
@MailYouLater that's what I initially thought (and afraid of), but changing the hash in the files enabled me to connect to the remote machines without issue. Perhaps there's a different hash that's used just for router usage? I'll let @Ylianst chime in on this one...
