### ISSUE TITLE
Implement whitelisting of CIDR ranges

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#68]
It would be awesome if you could add support for CIDR ranges (e.g. 192.168.0.0/24) to the config option **userallowedip**. That way, people would be able to whitelist entire ranges of IP addresses without having to manually specify every single one of them.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.5-r with support for CIDR ranges. For example you can put:
`"UserAllowedIP": "127.0.0.1,192.168.1.0/24"`

**Comment by whalehub** [comment]
@Ylianst Thank you!
