### ISSUE TITLE
Plugin Protocol Support Broken in d3105a4

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#680]
[Linux user shell improvements.](https://github.com/Ylianst/MeshCentral/commit/d3105a468dd53847902b4fbe9b0207708c4ee9d0) commandeered the existing httprequest.protocol 7 (plugin data exchange) for use with User / System mode shells instead. (Refer to line 1574 in meshcore.min.js)

>   } else if (this.httprequest.protocol == 7) { // plugin data exchange

The shell code is higher up in the chain, so this breaks plugins using this data exchange.

**Comment by Ylianst** [comment]
Oops! Sorry about that. I will fix it first thing tomorrow morning when I get to work.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.4-y with a fix for this. Let me know if you see any issues.

**Comment by ryanblenis** [comment]
Fix confirmed! Thanks!
