### ISSUE TITLE
2 pubrelay.info users created after update to 0.44-s

### ISSUE THREAD

**Issue by visualwritings** [Ylianst/MeshCentral#683]
Hi,

We've updated to 0.44-s yesterday, and after the installation we noticed 2 additional users, both using the same @pubrelay.info address. It seems this domain is barely 2 weeks old. The new users weren't created on our testing environment so I kind of doubt they were created by the install itself, but is this something you (or someone else) recognizes? Or do you think someone is trying to misuse our meshcentral installation (or (spam)bot maybe)?

Any thoughts would be appreciated.

**Comment by Ylianst** [comment]
@pubrelay.info is not something I recognize. I just did a quick search for "pubrelay" in the code to make sure, but there is nothing. Make sure that if a server is exposed in the Internet, the "new account" option is not enabled unless you want the public to be able to create accounts on your server (like [meshcentral.com](https://meshcentral.com)).

**Comment by jsastriawan** [comment]
You should never enable creation of new account in production environment without protecting it with "newAccountPass" in your domain. You should add password protection for new account creation in your Meshcentral domain configuration (meshcentral-data/config.json).

**Comment by Ylianst** [comment]
By default, new account creation should be off unless there are no accounts. So, you should be able to create the first account and no other unless you set in the domain section of config.json:

`"NewAccounts": true`

If this does not work, it's a bug.

**Comment by Ylianst** [comment]
Closing this one since I think we are done. Please re-open if there are any added information that would required a change to the code.
