### ISSUE TITLE
'File a Bug' link to the footer? 

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#686]
Would it benefit to have a 'File a Bug' link in the footer, as an option and the person can select this. Before it would take them to a Git or similar it would ask a few Yes and No questions, to make a link choice that would fit going to the MeshCentral community or just generating another form to send directly to the administrators?

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Well... I already have plenty of feature requests and bugs to work on. I would add it if the issues list was smaller, but with 200+ issues right now, not going to do this.

**Comment by SomeGuru** [comment]
Ylian,

I agree this is a low fruit that could be addressed much further down the road... I am just highlighting the fact that if someone is lazy as an administrator that given that link for their users to report issues would be great... However I don't want to see where the dodo admins users send your team unnecessary sightings for non MeshCentral issues that would be setups for their domains.

Thanks,
SomeGuru

**Comment by Ylianst** [comment]
Understood. I like the GitHub community as the bug filings are generally of higher quality. I am going to close this issue, but we can think about this down the road. This said, building an open source RMM probably leads to infinite feature requests.
