### ISSUE TITLE
Terminal scrolling doesn't work

### ISSUE THREAD

**Issue by adsgreen** [Ylianst/MeshCentral#689]
On some agents, when using the terminal tab in mesh central, commands that return long output do not scroll as expected. instead the lines are jumbled up at the bottom of the screen. when this happens you need to use a "cls" command to clear the terminal and continue.

Latest version of mesh 0.4.5.a with windows x64 agent clients.
Clients are windows 10 x64
Server is amazon linux.

I've tried different browsers but no luck. We

**Comment by krayon007** [comment]
I rewrote terminal for windows to use the new ConPTY API, which fixes this issue, as well as others. It is supported on Windows 10/1903 and newer. I have it detect if your platform supports it, and fallsback to the old terminal if it doesn't.

This is why some version of Windows behave different than others, as Microsoft rearchitected the console when implement ConPTY, so the behavior changed, breaking interopability with the old terminal.

The new agents should drop very soon. Doing final testing now...

**Comment by adsgreen** [comment]
Ah ok - that makes sense.
Would you be able to point direction to where the version is checked. We are using windows 10 IoT enterprise and wonder if it’s compatible.
Thanks!

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-b with Bryan's next generation MeshAgent. Lots of new features including the new terminal if you have Windows 10 build 1903 or better. When active, the terminal tool bar will be used and you can scroll back.

![MC2-Win10Terminal](https://user-images.githubusercontent.com/1319013/69851683-1a2ed700-1237-11ea-847c-966c870309de.png)

**Comment by adsgreen** [comment]
Tested on windows v17763 (build 1809) and looks ok.

**Comment by krayon007** [comment]
Cool. I didn't test the build number, instead I just checked to see if the new ConPTY methods are present or not, so it'll use the new APIs if present and fallback to the old terminal if not. I wasn't sure what exact build it was present, so I figured this was the best way, plus this makes it work on other windows versions, such as Server 2019, etc.

**Comment by MailYouLater** [comment]
Checking if the appropriate methods are present is much better than checking what the build number is.  If you checked the build number, there could be versions that should work that don't, and vice versa, just like all the shenanigans that went on in web browsers because websites were checking the UserAgent string to see what version of the page they should serve instead of having the webpage detect features in client side scripting.

**Comment by Ylianst** [comment]
Agreed. Bryan did it correctly 👍

**Comment by Ylianst** [comment]
Closing this one since I am pretty sure this is fixed, at lease for the latest Windows OS's.
