### ISSUE TITLE
Remember a trusted machine using two factor

### ISSUE THREAD

**Issue by digibum** [Ylianst/MeshCentral#691]
We would like to have an option, when loging in with login token to remember current PC as trusted for lets say 30 days? Thank you!

**Comment by alesribic73** [comment]
Maybe an option to whitelist local company IP’s which doesent need 2FA would ba also an option

**Comment by Ylianst** [comment]
Both really good requests.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.5-b with the "Remember this device for 30 days" support. This is only visible when two factor authentication is enabled.

![MC2-TwoFactorRemember](https://user-images.githubusercontent.com/1319013/69849515-c7065580-1231-11ea-9020-ccc3f3fe52db.png)

Not sure I would recommend this, but if you like, you can now configure to skip 2nd factor authentication for a IP or IP range by adding "skip2factor" in the "PasswordRequirements" section that is in the domain section of the config.json.

 ```
     "PasswordRequirements": {
        "min": 8,
        "max": 64,
        "upper": 1,
        "lower": 1,
        "numeric": 1,
        "nonalpha": 1,
        "reset": 10,
        "hint": true,
        "force2factor": true,
        "skip2factor": "127.0.0.1,192.168.2.0/24"
      }
```

MeshCentral v0.4.5-b is the "Thanksgiving Super-Update" with the next generation MeshAgent from Bryan, so it's packed with new features. [Watch Twitter for details](https://twitter.com/meshcentral).

**Comment by alesribic73** [comment]
Im confirming this. Works as it should. Many thanks for fast implementation.

**Comment by digibum** [comment]
@Ylianst you are awesome! Great work. Since you are so fast Il open one more future request =)

**Comment by uldiseihenbergs** [comment]
Hello @Ylianst , a small hiccup with 2FA for me: i checked "remember 30 days" checkbox, but looks like it's not working - it asks again for 2FA code every time. Are there any config i'm missing? no "Passwordrequirements" in my config.json.
