### ISSUE TITLE
MeshCmd detected as trojan

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#692]
https://www.virustotal.com/gui/file/ce50fdd59c57a98370d7b9e07132caee6f006dd668a493a67c42f257a6f34bfe/detection
32 bit version
https://www.virustotal.com/gui/file/4fe32be5af7bbe1df50a3bb0b64fc41567502661a4a042ab28cc23fd337c81fe/detection
64 bit version

**Comment by Ylianst** [comment]
Just released a new version of MeshCentral a few minutes ago. It's a super update will all new agents and meshcmd. Update again and let me know.

**Comment by alesribic73** [comment]
Are all agents updated automaticaly on all groups?

**Comment by Ylianst** [comment]
Yes. When you update the server, all agents also get updated automatically. Note that if you go back to an older server, the agents will also revert back, but try not to do that if possible.

**Comment by alesribic73** [comment]
Great!

**Comment by MailYouLater** [comment]
If you have antivirus software detecting any version of the agent as a virus/trojan/etc., I recommend that you submit it a false positive report to the antivirus vendor so that the similarities between it and later versions of the agent don't cause later versions to look like a virus/trojan/etc.

**Comment by Ylianst** [comment]
Ok, closing this one since we released all new MeshAgent. Please open a new issue if this happen with the new agent.
