### ISSUE TITLE
IE11 browser fail with npm version 0.4.4-t onwards

### ISSUE THREAD

**Issue by reidjr** [Ylianst/MeshCentral#697]
IE11 browser fails to blank screen after login and second authentication screen.
Found by testing versions,  0.4.4-s is last version that is OK. 
Chrome is OK as a browser all versions. 

Debugger on IE11 seems to choke at Line 78 ol.js 

{ue=1===(new MouseEvent("click",{buttons:1})).buttons}
Object doesn't support this action

**Comment by Ylianst** [comment]
Oh dear. Looking into this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-d that fixes the IE11 problems I have noticed and comments out a bunch of code from the web application when geolocation feature is not enabled. Let me know if this works for you.

**Comment by reidjr** [comment]
Great, v0.4.5-e tested and working for me.

**Comment by Ylianst** [comment]
Thanks. Will close this one. Thanks for reporting this.
