### ISSUE TITLE
Device's "Plugins" tab should not be visible if no plugins want to display something in it

### ISSUE THREAD

**Issue by MailYouLater** [Ylianst/MeshCentral#699]
Not all plugins have an interface that you access from the interface of a single device.  If you don't have any plugins that want to show something in the "Plugins" page of an individual device, the tab should be hidden from the devices menu.

![image](https://user-images.githubusercontent.com/1279475/69998917-4fc01280-150c-11ea-95bc-493ee5b6f5e1.png)
![image](https://user-images.githubusercontent.com/1279475/69998989-741bef00-150c-11ea-88ab-5a4700d60b7c.png)
In these images, I don't even have any actual plugins enabled at all (I just have the plugin system enabled but haven't downloaded any plugins), so the Plugin tab will definitely not have any content (yet) and should be hidden until a plugin actually puts something there.

**Comment by Ylianst** [comment]
This is one for @ryanblenis. I agree, that tab should not show unless there is a use for it.

**Comment by ryanblenis** [comment]
Submitted PR (#700) to address this.

**Comment by Ylianst** [comment]
Excellent! Nice and simple fix, I like it. I will have a published version with this tomorrow.

**Comment by MailYouLater** [comment]
I'm surprised at how small the changes necessary to implement this were.  Thanks for getting to this so quick!

**Comment by MailYouLater** [comment]
ACK!  There might be an issue with it.  Will post comments on #700.

**Comment by MailYouLater** [comment]
I can verify that `0.4.5-g` still shows the Plugins tab when needed, but no longer shows it when no plugins use it.
