### ISSUE TITLE
Can't boot with IDE-R

### ISSUE THREAD

**Issue by damonmaria** [Ylianst/MeshCentral#7]
Using MeshCentral 2.0 beta 2 connect using CIRA to an Intel-AMT device

Using the MeshCommander KVM it prodivdes the power option to "Power on to IDE-R", but it then asks for a server URL. I assumed MeshCentral would provide the server so I switched to that.

Using the MeshCentral KVM there are far fewer power options. I'm not even given the option to "Power on". But if I use the "Intel AMT" tab and click on the power status, then choose "Custom action.." I can select "Use IDE-R" and the "IDE-R boot device". However, there's no where I can specify the ISO to use. 

Is this functionality not there yet or am I missing something? 

Thanks for your great work.

**Comment by Ylianst** [comment]
Hi. IDER support is not yet built-into MeshCentral2. Right now, you can download "MeshCommander for IIS, Source & Samples 0.6.0" on http://www.meshcommander.com/meshcommander. In that package you will find a project called "Switchbox", run that on Windows, setup a ISO and you will have a URL to give. This said, I have no done much testing, but it should work ok.

**Comment by damonmaria** [comment]
Great thanks. 

Is it possible to specify this URL when booting to IDE-R in MeshCentral 2 when connected with CIRA? I'm not offered the option like I am with MeshCommander going direct.

**Comment by jonlinper** [comment]
Any other method for IDE-R boot in remote? (until MeshCentral2 supports it).

Thanks @Ylianst for all your work and videos.

**Comment by Ylianst** [comment]
I don't know of any alternatives. If you want to experiment, you can download the MeshCommander source code package and run "SwitchBox" on a WIndows PC. It has a IDER server in it. You then give that URL to MeshCentral to perform IDER. However, it's not a well tested path.

IDER is a bit difficult because you need to use IMRSDK.dll that I can only use on Windows servers. However I will get around it at some point.

**Comment by Ylianst** [comment]
I just released MeshCommander v0.7.1 that can connect to MeshCentral. You can then initiate IDER from MeshCommander and it will work thru CIRA. Demonstration video here: https://www.youtube.com/watch?v=nsqF1uOCJx4

**Comment by jonlinper** [comment]
Awesome, @Ylianst.

**Comment by damonmaria** [comment]
@Ylianst I've finally gotten back into the use case for this but can't see how to connect my MeshCommander to MeshCentral as per the video you linked to above. I also read in the MeshCmd user guide that the web based version of MeshCommander doesn't support IDE-R. 

Is it not possible to use IDE-R except from the Windows MSI installed MeshCommander? If so, are there technical reasons other platforms can't do it? Or has it just not been implemented yet?

**Comment by Ylianst** [comment]
IDE-R is implemented by IMRSDK.dll, a Windows DLL that is provided by Intel in the Intel AMT SDK. Right now, the source of the IDE-R session will need to be a Windows machine. This DLL is also difficult to work with. There is a Linux version in the SDK, but I have not started working with it. Something that would be possible in the future... The best would be to find a way to do it entirely within NodeJS... I need to research this.

**Comment by damonmaria** [comment]
Thanks for the update. Hmmm... I was hoping to automate this. And I primarily work in Node, and exclusively on Linux. So that's a bit suboptimal. Should I open a new issue to track that missing functionality or re-open. this one?
