### ISSUE TITLE
MeshCentral crash on Show server error log

### ISSUE THREAD

**Issue by nicrame** [Ylianst/MeshCentral#70]
When i click on My Server -> "Show server error log" MeshCentral crash and disconnects me.
I'm using newest version: 0.2.5-r

In mesherrors.txt i can find this:
-------- 1/5/2019, 6:14:20 PM ---- 0.2.5-l --------

buffer.js:215
    throw new ERR_INVALID_ARG_TYPE('value', 'not number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must not be of type number. Received type number
    at Function.from (buffer.js:215:11)
    at /mymesh/node_modules/meshcentral/meshcentral.js:1245:83
    at FSReqWrap.oncomplete (fs.js:185:5)

**Comment by Ylianst** [comment]
Oh. Heading to work to fix this now! Will have an update shortly.

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.5-s that should fix this. I also did a bunch of code cleanup and small server speed improvements.

**Comment by nicrame** [comment]
It's working fine now. Thank You.
