### ISSUE TITLE
Upload Files 401 (Unauthorized)

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#706]
Hi, I have problems uploading files to the private groups folder. I have made and assigned permissions chmod –R 755 / opt / meshcentral / meshcentral-files but 401 (Unauthorized) still appears in the google chrome console.

I can create folders but not upload files.

Error: Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by Ylianst** [comment]
Ok, I will check on this.

**Comment by Ylianst** [comment]
Your right, I am seeing the same problem... looking into it now.

**Comment by Ylianst** [comment]
I am not seeing this problem on my servers. Can you confirm the problem is in the "My Files" and the device group folders? It does not happen in "My Files"?

![x](https://user-images.githubusercontent.com/1319013/70174649-30e78a80-168a-11ea-83d4-4fb3ac09937c.png)

**Comment by desarrollocdb** [comment]
Hi, it happens in folders by groups or my files. I can create folders but it doesn't let me upload files. They do not appear there.

**Comment by desarrollocdb** [comment]
I no longer get error 401 but the files are not seen in the folders

**Comment by Ylianst** [comment]
Note that there is a file size quota. Can you try very small files and see if that works? If you try to send a big file that exceeds the quota it will currently ignore it. This is a bug, I need to display an error that the quota is exceed.

**Comment by geanferrani123** [comment]
> Não estou vendo esse problema nos meus servidores. Você pode confirmar que o problema está nas pastas "Meus arquivos" e no grupo de dispositivos? Isso não acontece em "Meus arquivos"?
> 
> ![x](https://user-images.githubusercontent.com/1319013/70174649-30e78a80-168a-11ea-83d4-4fb3ac09937c.png)

Ylianst, good afternoon!

How do I display this spacebar that is in the print you posted?

**Comment by MailYouLater** [comment]
You mean the spaces between words in those links?  The links you circled in that image reflect the names of device groups.  If you want a space there, then you should include a space in the device group's name.

**Comment by Ylianst** [comment]
The "My Files" tab is only available to server administrators or users that have permission to store files on the server. If you have an account on [meshcentral.com](https://meshcentral.com) for example, you will not see this tab.

**Comment by desarrollocdb** [comment]
Hi, it doesn't allow me to upload my 100k files.

**Comment by SomeGuru** [comment]
@desarrollocdb When you did the sudo chmod 755, did you add the user to the folder in groups? I have found that even though I was 755 to the folder that once inside of the meshcentral, I had to turn back around and go back out to the server and set my user by which I execute MeshCentral on, to be owner of the folder to fix the 401 error inside of my MeshCentral server. It has to do with folder ownership I found in my instance...  Now that I have done that add I am able to transfer the files much easier now...

**Comment by desarrollocdb** [comment]
Hi, so I have the permissions currently assigned:

![image](https://user-images.githubusercontent.com/26174637/70453737-43413a00-1a77-11ea-9f36-65e1d126749d.png)

**Comment by desarrollocdb** [comment]
@SomeGuru 
This is how permissions look in the folders

**Comment by geanferrani123** [comment]
> Você quer dizer os espaços entre as palavras nesses links? Os links que você circulou nessa imagem refletem os nomes dos grupos de dispositivos. Se você quiser um espaço lá, inclua um espaço no nome do grupo de dispositivos.

I was talking about this featured part

![image](https://user-images.githubusercontent.com/55212206/71016488-23e88380-20ed-11ea-964b-192ff52837bf.png)

**Comment by desarrollocdb** [comment]
Hello, any update or something that requires review?
