### ISSUE TITLE
Desktop: Apps show frozen when they are not.

### ISSUE THREAD

**Issue by infineonnetworks** [Ylianst/MeshCentral#711]
We have run into a problem with the HTML5 desktop where some Apps like Powershell ISE will show up as frozen and blacked out when using MeshCentral's Desktop feature, when in reality they are not. 

Today we had this problem when accessing a remote Windows 10 machine via the Meshcentral agent and the Powershell ISE (which was running on there) was showing completely blanked out. 
Almost as if it was a render problem for the application, however the rest of the desktop was showing fine.
However since we also utilze Apache Guacamole, i was able to check via a different method to see that it wasn't in fact a locked application, but rather that the HTML5 module for Meshcentral wasn't reflecting properly. I have heard from some of my other co-workers that they have also seen this with other tasks such as settings on Win 2016 servers and Win 10 machines. 

Is there possibly a setting that could be interfering or a bug?

**Comment by Ylianst** [comment]
I have not seen this before. Just to confirm, your just running PowerShell ISE on the desktop and it does not update? I will try the same and see what happens.

I have never tried Guacamole, someone may connect me, but I think that tool does an RDP session to Windows and converts (transcodes) the session into a different protocol. So, I would imagine that anything that works with RDP would also work with Guacamole.

**Comment by infineonnetworks** [comment]
Some more information to add 
Screen with "Mesh Central"
![image](https://user-images.githubusercontent.com/55726632/70459830-3f5ee900-1a72-11ea-8449-772515fdb951.png)

Same screen with Guacamole.
![image](https://user-images.githubusercontent.com/55726632/70459859-4ab21480-1a72-11ea-9e77-dc2c3c20b3ad.png)



As you can see in Mesh Central the App gets blanked out for some reason. It may be something to do with rendering. If you can tell me which file in the code deals with the Capture/Rendering i will take a look and see if i can figure out what may be causing it (no guarantees though).

**Comment by krayon007** [comment]
What version/build of Windows are you running, and what version of Powershell ISE are you running? I've tried this on several different Windows builds, and haven't been able to reproduce this issue. The only time I've seen a similar issue, is if the application was using DirectX to render.

**Comment by MailYouLater** [comment]
Possibly related: [Disable Hardware Acceleration PowerShell ISE (Win 10)](https://www.reddit.com/r/PowerShell/comments/3z63a6/disable_hardware_acceleration_powershell_ise_win/)

**Comment by krayon007** [comment]
I added a new console command 'wpfhwacceleration'. So you can specify ON, OFF, DEFAULT, and STATUS. Ylian is going to push an update. If you can test to see if this resolves your problem...  If you enter the command:

wpfhwacceleration off

on the console tab, it will disable WPF HW Acceleration for the logged in user. If you can test the KVM in this scenario, and see if the Powershell ISE renders correctly, we can look at next steps.

To revert the hwacceleration setting back to the default, you can enter the command:

wpfhwacceleration default

**Comment by Ylianst** [comment]
@MailYouLater Oh, that is interesting.

**Comment by infineonnetworks** [comment]
![image](https://user-images.githubusercontent.com/55726632/70466666-e185cd80-1a80-11ea-81cd-aba0dbc35103.png)

**Comment by infineonnetworks** [comment]
wpfhwacceleration off    still not on agent, thus i am not sure if Meshcentral version is updating properly.

**Comment by Fireshadow3** [comment]
Had the same exact problem, the desktop would work fine, but starting any browser would show up only a blank page, exactly and ONLY on the browser window.

Solved by updating drivers for the graphic card.

**Comment by si458** [comment]
closing as stale,
please try the latest version of meshcentral, and try again,
if your issue still happens,
then please reply back and open the issue again
