### ISSUE TITLE
Help with error logging

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#715]
Guys, good morning!

Today for some reason my meshcentral server had a quick crash, when I went to look at the log, presented this information. Can you help me solve and understand what that would be?

![image](https://user-images.githubusercontent.com/55212206/70443658-6cba8f80-1a90-11ea-8406-20bd2cd0a347.png)

![image](https://user-images.githubusercontent.com/55212206/70443560-44cb2c00-1a90-11ea-95b3-696a9e228cd7.png)

**Comment by Ylianst** [comment]
Hi. You must be recording sessions. I am not quite sure what caused this, your using an older version. I just published MeshCentral 0.4.5-m with improvements in that area to make sure this problem does not happen. Update and let me know if you see this again.

**Comment by MailYouLater** [comment]
@geanferrani123: This error log shows that you were running version 0.4.3-v.  Is this accurate?  Please confirm before you update.

**Comment by Ylianst** [comment]
@MailYouLater Good question, I assumed it's an older version as indicated? The session recording code used has not changed in a while, so I did make some fixes in that area today.
