### ISSUE TITLE
Make Remote Privacy Bar Movable

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#716]
Guys, good morning!

Please, how do I move the remote access bar? I need to translate my text into my language, can you help me?

![image](https://user-images.githubusercontent.com/55212206/70539233-4c0b3c00-1b5b-11ea-8b06-739dee410082.png)

Sorry for posting this question here, I could not post the image on reddit so I am posting my question here too.

**Comment by Ylianst** [comment]
Hi. Right now you can't move the privacy bar, however, Bryan is looking into making it move left-right only on Windows.

What is your language? I can do a machine translation to get started.

**Comment by geanferrani123** [comment]
My language is Portuguese - Brazil, I even sent you the translate.json file of that language via email, remember?

About mobility this would be wonderful, I would even open a topic about it lol ..

**Comment by geanferrani123** [comment]
Ylianst, if you will allow me, I would like to divert the subject from this topic a bit .. please, did you guys understand that black screen phenomenon that I mentioned in previous topics? I had even given you a breakdown of what happens in reddit ...

**Comment by Ylianst** [comment]
Hi. Oh! Sorry, yes, you did send me the Portuguese translation. Once you update MeshCentral, you can set your browser language to Portuguese or you can go in "My Account" and click "Localization Settings" and select "pt - Portuguese". Then, hit "ok" and refresh the page. You should see the Portuguese MeshCentral. Let me know if it works.

![x](https://user-images.githubusercontent.com/1319013/70570774-6a6c3a00-1b51-11ea-86af-a77a232d0cf2.png)

**Comment by krayon007** [comment]
I updated the Windows version to allow moving the connection bar along the X-axis within the displayed monitor region.  It will be included in the next agent update.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-p with Bryan's change to the privacy bar. You can now move it left/right.

**Comment by Ylianst** [comment]
Related to the privacy bar, I just published MeshCentral v0.4.5-r where can set "desktopPrivacyBarText" in the domain section, for example:

```
  "domains": {
    "": {
      "title": "Server Title",
      "desktopPrivacyBarText": "This is a test: {0}"
    }
  }
```

This will be used as the privacy bar text for that domain. The "{0}" is replaced with the comma separated list of user names that have active desktop sessions, but you don't have to include {0} in the string. So you can just set "This desktop is being managed remotely" and that will work.

Feedback appreciated, 
Ylian

**Comment by PathfinderNetworks** [comment]
I just updated and implemented this.  It's working on my end.  This is a good change.  
![privacybar](https://user-images.githubusercontent.com/48607498/70674622-873d6600-1c54-11ea-813d-ec0c0423f14e.JPG)

**Comment by Ylianst** [comment]
I had to pull version v0.4.5-r out because of a bug, but you can keep your config.json file set, I will have that feature back tomorrow.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-s with this feature back in.

**Comment by OutbackMatt** [comment]
This works for me

**Comment by Ylianst** [comment]
Thanks for the report. Closing this as the privacy bar can move left and right.
