### ISSUE TITLE
New Account

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#720]
Trying to create a new account on v.0.4.5-p

I have TFA forced for all users

'OK' button never goes 'selectable' for me (had this before when I used spaces in name, but now trying just a single string of alpha characters, a client's first name = 'Fabienne')
Send Invitation email is dependent on 'force password reset' which doesn't make sense, it should be dependent on 'email is verified'

**Comment by Ylianst** [comment]
Thanks for the report. I will check this tomorrow.

**Comment by Ylianst** [comment]
I made fixes to the "Create Account" dialog box, it will be in MeshCentral 0.4.5-t when I publish it later today.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-t with improvements. Can you re-test and let me know if it works for you? Thanks.

**Comment by OutbackMatt** [comment]
Yes thanks
works as expected
