### ISSUE TITLE
MeshCentral crashes when 2FA token is saved

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#721]
I just updated my server to 0.4.5-r and am noticing it will immediately crash and restart if I try to log in from a browser where I had previously set the 'remember computer for 30 days' option on the 2FA token page.  If I log in from a different browser where I hadn't checked the option then I can log in fine and the server doesn't crash.  I don't know that this error is directly the result of 0.4.5-r (I was a few versions behind).  

Here is what mesherrors.txt is showing.  
-------- 12/11/2019, 8:30:16 PM ---- 0.4.5-r --------

ror: Assignment to constant variable.
    at Object.CreateMeshCentralServer.obj.decodeCookie (c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\meshcentral.js:1862:28)
    at checkUserOneTimePasswordRequired (c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:525:54)
    at c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:677:55
    at c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\webserver.js:421:36
    at AsyncWrap.<anonymous> (c:\Program Files\Open Source\MeshCentral\node_modules\meshcentral\pass.js:31:88)
    at AsyncWrap.wrap.ondone (internal/crypto/pbkdf2.js:37:48)

Also, there is something going on with the logging in 0.4.5-r.  It's adding a large number of extra date and time stamps in between each character.  Here's a screen grab of the partial log showing what I mean. I zoomed out of the log file a bit so I could include more of the time/date stamps.  You can tell that the word 'Error' is being split up, for example.  
![log](https://user-images.githubusercontent.com/48607498/70675165-68d86a00-1c56-11ea-8147-58e573597f2b.JPG)

**Comment by gabolonte** [comment]
I can confirm it happens only in 0.4.5-r because I had been upgrading everyday and had not experienced this bug until now.

I can login with no crashes but only erasing all sites's cookies or from a private browser tab. If I check "remember computer for the next 30 days" then the next time I'll have to login from that browser (because I restarted Meshcentral, for example) the crash occurs

**Comment by Ylianst** [comment]
Pulled v0.4.5-r!!! Thanks for the report. Will fix and republish tomorrow.

**Comment by gabolonte** [comment]
Had to reboot the server after updating but now works perfect
Thank you very much! This project is awesome

**Comment by Ylianst** [comment]
Published v0.4.5-s with the fix for the -r problem. We are back in business with latest features included.
