### ISSUE TITLE
Need support for WCOS (Windows Core OS)

### ISSUE THREAD

**Issue by Arun0711** [Ylianst/MeshCentral#723]
Hi,

Need Support for having mesh on Windows Core OS. as of now the Agent is installed via .exe. in WCOS there is no support to install via .exe. 

Can Mesh work on Wcos version ?

regards
arun

**Comment by Ylianst** [comment]
I have not tried on Windows Core OS, however you should be able to download the meshagent.exe and do:

`meshagent.exe -fullinstall`

That should copy the agent in the program files folder and get itself setup as a Windows service. If you can give it a try, that would be appreciated.

**Comment by MailYouLater** [comment]
I wasn't aware that WCOS was actually available anywhere (yet).  Where did you get WCOS from? and what device are you using it on? or are you requesting this in anticipation of using it in the future, hoping that it will already be supported when you get it?

**Comment by Ylianst** [comment]
I figured the question was about "Windows Server Core", which is Windows without the graphical user interface. I think you can get an instance of that one on AWS. @MailYouLater is right, if this is some other OS, I have certainly not tested it since, I don't have it.

**Comment by Arun0711** [comment]
Yeap for the future purpose. I believe WCOS is getting release very shortly for the Client devices from Microsoft. So at that moment I don’t want to struggle to get this running 😊

Regards
Arun

**Comment by Ylianst** [comment]
Ha well... I have not been following WCOS, I imagine it's going to be a bit like iOS that is pretty locked, but we will see when we get that OS installed.

**Comment by Arun0711** [comment]
hi,

tried installing the same with meshagent.exe -fullinstall but its not working :( 
need to find out some mechanism for installing the same

**Comment by si458** [comment]
closing as we have no way of testing this, but as @Ylianst explained you can use the exe to install from command line if you have no GUI
