### ISSUE TITLE
Multi-connection in one station

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#725]
Guys, good afternoon!

I noticed that after upgrading to 0.4.5-o, meshcentral is unable to keep remote connection of two or more technicians on one station, when this occurs, the agent service stops working, having to manually start next to just one person connect to the remote station.

Can you help me?

**Comment by Ylianst** [comment]
Hi. I just tested with the latest version and I can connect two remote desktop sessions to the same remote computer. Can you give a lot more details on what you are doing, what operating system and versions are involved. Also, if there is a "meshagent.log" file in the remote computer? This will be created when there is an agent crash. Thanks.

**Comment by treicadani** [comment]
Hi Ylian,

For me when more technicians are connected to the same box with multiple screens (Windows 10) the screen switches from 1 screen to all screens and back to 1 screen very fast also when more than 1 screen exists (Windows 10) when selecting screen 1 nothing happens and when selecting screen 2 or 3 shows only screen 1.

**Comment by geanferrani123** [comment]
Hello Ylianst, how are you?

I'm sorry for not having provided these details, I will get this information and already step.

**Comment by geanferrani123** [comment]
> Oi. Acabei de testar com a versão mais recente e posso conectar duas sessões da área de trabalho remota ao mesmo computador remoto. Você pode fornecer muito mais detalhes sobre o que está fazendo, qual sistema operacional e versões estão envolvidas. Além disso, se houver um arquivo "meshagent.log" no computador remoto? Isso será criado quando houver uma falha do agente. Obrigado.

Ylianst, Please see the following meshagent.log information:


[2019-10-16 11:50:51 AM] Microstack STUCK: @ [FuncAddr: 0x1F950B7500000000]
[GetModuleHandleW]
[CreateProcessInternalA]
[CreateProcessA]
[FuncAddr: 0x1A09A83F01000000]
[FuncAddr: 0xA11BA43F01000000]
[FuncAddr: 0x58C8A23F01000000]
[FuncAddr: 0x548AA33F01000000]
[FuncAddr: 0xB143A33F01000000]
[FuncAddr: 0x1BC8A23F01000000]
[FuncAddr: 0x36E2A03F01000000]
[FuncAddr: 0xACCBA23F01000000]
[FuncAddr: 0xB9E2A03F01000000]
[FuncAddr: 0x3047A63F01000000]
[FuncAddr: 0x71D6A73F01000000]
[FuncAddr: 0xDEA3A73F01000000]
[FuncAddr: 0xB87FA03F01000000]
[FuncAddr: 0x1232A93F01000000]
[RegisterServiceCtrlHandlerExA]
[BaseThreadInitThunk]
[RtlUserThreadStart]

[2019-10-17 01:35:18 PM] Microstack STUCK: @ [FuncAddr: 0x1F95E27400000000]
[GetModuleHandleW]
[CreateProcessInternalA]
[CreateProcessA]
[FuncAddr: 0x1A09AE3F01000000]
[FuncAddr: 0xA11BAA3F01000000]
[FuncAddr: 0x58C8A83F01000000]
[FuncAddr: 0x548AA93F01000000]
[FuncAddr: 0xB143A93F01000000]
[FuncAddr: 0x1BC8A83F01000000]
[FuncAddr: 0x36E2A63F01000000]
[FuncAddr: 0xACCBA83F01000000]
[FuncAddr: 0xB9E2A63F01000000]
[FuncAddr: 0x3047AC3F01000000]
[FuncAddr: 0x71D6AD3F01000000]
[FuncAddr: 0xDEA3AD3F01000000]
[FuncAddr: 0xB87FA63F01000000]
[FuncAddr: 0x1232AF3F01000000]
[RegisterServiceCtrlHandlerExA]
[BaseThreadInitThunk]
[RtlUserThreadStart]

[2019-12-10 12:33:49 PM] FATAL EXCEPTION [MeshAgent_6478498241E8A009.exe] @ [FuncAddr: 0x00000000771ea365 / BaseAddr: 0x000000013fddadec / Delta: 3367963271]
    [RtlFreeHeap]

[2019-12-10 03:52:35 PM] FATAL EXCEPTION [MeshAgent_6478498241E8A009.exe] @ [FuncAddr: 0x000000013f234f5e / BaseAddr: 0x000000013f28adec / Delta: 351886]

Both operating systems (technical and remote computer) are windows 10.

**Comment by krayon007** [comment]
Are you able to configure you endpoints to generate a dump file? The easiest way is to add "coreDumpEnabled=1" to the end of the .msh file, without quotes, and restart the agent.

**Comment by geanferrani123** [comment]
Hello Guys, good morning!

I managed to generate the .dmp file, how do I send it to you?

**Comment by MailYouLater** [comment]
If you're not worried about other people having access to it you can attach the file to a comment on this GitHub issue via drag and drop.  If you are concerned about others seeing the information it may have in it, you'll want to send it privately via email.  @Ylianst has posted his email address (and PGP key if you feel the need to encrypt your message and/or file) at https://www.meshcommander.com/contact-information and @krayon007's email address is visible on his GitHub profile at https://github.com/krayon007.
