### ISSUE TITLE
Feature Request: Linux SSH / Terminal working with Centralized User Management

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#727]
This was mentioned in #207 but wondered if there was any thoughts into collaborating with a Centralized User Management system such as FreeIPA for Linux users?  I appreciate that there is LDAP/AD authentication for access into the GUI itself, but once there selecting "Terminal" grants that user root access to the remote system.

I'm working with FreeIPA which (similar to Microsoft Active Directory but for authentication and access) manages all users and accounts centrally and has a client installed on each host that manages whether or not a user has access to those hosts. It would be *wonderful* if MC2 could refer to that system and then initiate connection (GUI > terminal or perhaps even better via Router > meshagent.txt) to that host using a non-root account.

I appreciate that @Ylianst mentioned in #207 that connections to a remote host is undertaken by the user that installed the client (which I have to assume would always be root) and go to thinking if there's any movement away from such a privileged account, to a less-privileged account ...?

**Comment by krayon007** [comment]
On a semi-related note, the terminal shell doesn't need to always be root. If you right click on the connect button, and select login shell, it will spawn the login process, which is what happens when you connect an SSH client, thus requiring the user to supply login credentials, in which case the terminal will load with the rights/profile of the specified user. I think the server has configuration to remove the root shell, but I'm not sure. Of course, this is for linux/bsd/macos only, as there is no login process on windows.

**Comment by D4V3M0NK** [comment]
@krayon007 is this already in place, or is being worked upon? I've just tried this with my production server (0.7.54) and it responded with "Denied" but didn't prompt me for a user, but then (at the moment) I also don't have centralized user management set up (just using local MC2 authentication). Very excited about this feature... :)

**Comment by D4V3M0NK** [comment]
Bryan, I beg your pardon - I selected User shell ... **Login shell** works perfectly!! When did that come about?!!!

Also - within the MC2 server, is it possible to restrict root shell as a permission only assigned to specific users? (More than happy to suggest an enhancement on a different ticket if that's not the case as of right now)

**Comment by krayon007** [comment]
I don't know if you remember but a while back there was an issue with the terminal wasn't handling pipe redirections correctly, which caused su to fail. When I sorted that out, is when I added support for login she'll, as that didn't work correctly until I fixed the redirection issue. It was quite a while ago tho if I remember. I don't think we ever publicized that feature tho.

**Comment by krayon007** [comment]
@Ylianst will have to chime in on the configuration thing for root shell. He's out on vacation at the moment tho, so it might be a delayed response.

**Comment by D4V3M0NK** [comment]
@krayon007 Yes I remember the pipe redirection issue... Nicely done on the different shells though sir, that's a biggie for me :)

I'll add a ticket and let @Ylianst ascertain if it's already been addressed or not.


thanks again Bryan
