### ISSUE TITLE
Error 503 after running Meshcommander script.

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#728]
I updated my AMT to use Meshcommander and I ran the script from my mesh central box, everything looked like it was going well but then I lost connection to it and I got a error 503. I will reboot the box and see if it will come back, great software by the way, I'm really liking the Mesh Central 2!

**Comment by Ylianst** [comment]
Hi. So, if you are running MeshCommander on a local network, connect to a different Intel AMT computer and run the CIRA install script, Intel AMT will go into an "Internet mode" and shut down the Intel AMT ports (16992 to 16995). It will then try to connect to MeshCentral and hopefully that works. You will not be able to connect MeshCommander again from the local network to that machine. You will need to run MeshCommander on the Intel AMT machine itself and connect to "127.0.0.1" and run the cleanup script or go in the "Internet Settings" and clean up the environment detection section. Only then will Intel AMT go back to normal and open it's local network remote management ports.

I know this is a really short explanation of how this works. Let me know if it makes sense.

**Comment by 82280zx** [comment]
I'm trying to install meshcommander on ubuntu 18 but it's not letting me do it =/ I'm getting a rollbackFailedOptional: verb npm-session

**Comment by 82280zx** [comment]
I was able to get meshcommander on it, this worked thank you!
