### ISSUE TITLE
AMT presence detection flaky for NUC5i5MYBE -- timing issue? (v0.4.5-p)

### ISSUE THREAD

**Issue by veitw** [Ylianst/MeshCentral#729]
Hello!

We operate a bunch NUC5i5MYBE that all show the same issue:

When powered off (soft off), MC shows them as offline most of the time. Sometimes they appear as AMT online, almost always all of the NUCs at once, but fall back to AMT offline within a few minutes.

While they appear online in MeshCentral, one can connect to AMT via the devices' AMT tab, but connecting via MeshCommander is always successful. Also accessing via web interface always works.

I noticed that AMT is much slower while the NUC is in soft off, so I suspect a timing issue here, where MC queries for presence but does not wait long enough for the answer.

All NUC5i5MYBE are running AMT 10.0.56 in ACM and employ the latest firmware, MYBDWi5v.86A.0056.2019.1112.1450 with release date 2019-11-12.
The problem existed in earlier firmware/AMT versions, too.

The problem disappears while the devices are powered on.

We also observed this phaenomenon in the past on 29 units HP EliteDesk 800 G2 SFF. All those machines also responded very slowly in AMT while in soft off, and all those machines were shown AMT offline by MC most of the day.
But those devices are out of production now and have already been donated, so we can no longer verify whether the issue persists for this model.

Best regards,
// Veit

**Comment by jsastriawan** [comment]
Please note when the hardware is in low power mode or sleep/soft-off, the overall network is being handled by manageability engine. This is where AMT resides and it has very limited power and capabilities. As a result, the network will run at slower speed because the link between manageability engine and the NIC will be solely through a side band channel only rather than full PCIe speed.

So this behaviour is really normal.

**Comment by krayon007** [comment]
Someone will correct me if I'm wrong, but unless the client is configured for CIRA, it will normally show as offline in MC when soft off unless there is a powered on client somewhere on the local network segment, to bounce the AMT traffic to MC. When configured for CIRA, AMT will connect to the server directly.

**Comment by Ylianst** [comment]
When the computer is off and Intel AMT is sleeping, it takes a network packet to wake AMT which will take a few seconds before AMT is up and the next packet will be get a response. So, maybe I can try to space out the packets better to wake and keep AMT awake. Also, Intel AMT has a timeout to go back to sleep that you can set in MEBx, it's probably a good thing to set that a bit longer.

**Comment by veitw** [comment]
Is this configurable through WSMAN, so I could write a mescript for that?

**Comment by MailYouLater** [comment]
> When the computer is off and Intel AMT is sleeping, it takes a network packet to wake AMT which will take a few seconds before AMT is up and the next packet will be get a response.

What about changing MC to check AMT connectivity twice (a few seconds apart) before reporting that it's disconnected to be certain if AMT is really unreachable or if it was just sleeping?

**Comment by veitw** [comment]
Hi @krayon007,

> Someone will correct me if I'm wrong, but unless the client is configured for CIRA, it will normally show as offline in MC when soft off unless there is a powered on client somewhere on the local network segment, to bounce the AMT traffic to MC. When configured for CIRA, AMT will connect to the server directly.

thanks for that hint, but in this case, the MC server shares an interface with the segment in question. Also all other AMT-enabled devices on that segment do not show this behaviour, all with equal AMT configuration, so I doubt this is the cause.

Best regards,
// Veit

**Comment by si458** [comment]
this should be fixed in the latest 1.1.18 release
i did a fix which fixed the CIRA showing the wrong AMT power state, it would always show `powered UNKNOWN` where as now it shows `powered, soft-off (or hibernating etc...)`
