### ISSUE TITLE
Improvement suggestion - Hotkey -> ALT + TAB

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#730]
Hello friends, good morning!

I would like to suggest implementing the ALT + TAB command in meshcentral and improving WINDOWS key recognition, because what would be the idea:

From the moment the mouse is inside the remote desktop, the technician can use ALT + TAB on his keyboard to switch windows on the remote machine and also when he presses the windows key, can open the windows start menu.

**Comment by Ylianst** [comment]
My understanding is that the browser will not capture the ALT-TAB combination, so, I don't think this is possible. If anyone has different information, let me know.

**Comment by MailYouLater** [comment]
I thought I remembered Rainway having some interesting news a while back relating to this, and I found it! Tada!! 🎉 https://rainway.com/blog/2018/07/27/introducing-native-keyboard-input-for-chrome/

I can't find anywhere online that I can visually see that it's working, but it's apparently a few (Chromium-based) browsers support the `keyboard.lock` API, which should allow you to capture some of these normally uncapturable key combinations.

`keyboard.lock`: [Proposal](https://github.com/jondahlke/system-keyboard-lock/blob/master/EXPLAINER.md), [Discussion](https://discourse.wicg.io/t/proposal-system-keyboard-lock-api/1594), [WICG GitHub repo](https://github.com/WICG/keyboard-lock), [Spec [Draft]](https://wicg.github.io/keyboard-lock/), [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock), [Can I Use](https://caniuse.com/#feat=mdn-api_keyboard_lock), [WPT](https://github.com/web-platform-tests/wpt/tree/master/keyboard-lock) [[Results]](https://wpt.fyi/results/keyboard-lock?label=master&product=chrome-67%5Bstable%5D&product=chrome-68%5Bstable%5D&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=edge%5Bexperimental%5D&product=firefox%5Bstable%5D&product=firefox%5Bexperimental%5D)

**Comment by Ylianst** [comment]
Oh! That is interesting! That would solve exactly this issue.

**Comment by jdvmanen** [comment]
Wow, I'm moving from ConnectWise to this amazing software, and are really really happy with the outstanding software quality. Specially the speed of it is blowing me away!

However, the lack of shortcut transfer to the client devices is making me much much less efficient in my work. I cannot find a 'vote' button for this feature, but I would like to give a +1 for this one!

**Comment by jdvmanen** [comment]
> Oh! That is interesting! That would solve exactly this issue.

@Ylianst your response on the 14th Dec 2019, will that probably reconsider the 'wontfix'  label? And, in my opinion the issue starter talked only about ALT+TAB, but there are many other shortcuts.

**Comment by jdvmanen** [comment]
more info on the function:
https://garykac.github.io/system-keyboard-lock/

**Comment by jdvmanen** [comment]
@Ylianst why is this issue having the tag 'wontfix'? 

The obviuous answer is because it will not be fixed 😁. But maybe my question is than why isn't this considered to be implemented?

**Comment by Ylianst** [comment]
FYI. Starting with MeshCentral v0.7.45, you can now customize keyboard shortcuts.

![MC2-KeyboardShortcuts1](https://user-images.githubusercontent.com/1319013/103989046-f16c5700-5143-11eb-8060-fec641a652f5.png)
