### ISSUE TITLE
Feature Request: Last seen column

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#734]
Hello.

Can we have an "Last seen column" in the my devices page after user, address, connectivity columns?

Thanks

**Comment by ryanblenis** [comment]
Agreed, I think a column would be great for a quick peek.

FYI you can already see this if you click into the device right under the icon on the right.

**Comment by pczolee** [comment]
@ryanbleins
Yes, I know that there is the info if I click on the device, but -as you said- for a quick peek it will be better on the main screen ;)

**Comment by ryanblenis** [comment]
Referencing #737, as they're the same basic concept, though this is a simpler ask, whereas #737 is more feature-rich.

**Comment by si458** [comment]
this already exists, just click the COG and select 'last seen'
![image](https://github.com/Ylianst/MeshCentral/assets/765314/440ea435-1ebc-412e-a831-fbfb2d777fd4)
