### ISSUE TITLE
Suggestion: session recording enable from web interface

### ISSUE THREAD

**Issue by leleb** [Ylianst/MeshCentral#736]
Session recording is usefull but I would like to enable/disable it on demand from gui, not in the config file

**Comment by asasin114** [comment]
It would be extra nice to be able to record from the desktop tab when controlling a device.

**Comment by Ylianst** [comment]
Good suggestion, but I am currently swamped so, not going to be quick. If the user gets to decide when to record, is the suggestion that the recorded files still be stored on the server in a way that only the administrator can access them?

**Comment by asasin114** [comment]
If the admin could decide which users are allowed to record and which users can access recordings then that would be ideal, I think.

**Comment by MailYouLater** [comment]
> If the admin could decide which users are allowed to record and which users can access recordings then that would be ideal, I think.

That would require adding a section to the web interface for accessing the recordings, which sounds great, but is a much bigger project than adding a 'record this session' button, and that's on top of any changes necessary to make session recording able to be turned on/off on the fly.  I really like this idea, but don't expect it to be done particularly soon.

**Comment by leleb** [comment]
I think putting recordings in "My Files" view is good

**Comment by Ylianst** [comment]
Added a way to record a remote desktop session locally a few weeks back.

![EXDsKZ4UcAA_mJH](https://user-images.githubusercontent.com/1319013/81768109-0bf41080-948f-11ea-9991-f1f2b93f63a3.png)

**Comment by si458** [comment]
this feature exists as a locally recording since 2020
