### ISSUE TITLE
Details of entire device group

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#737]
The 'Details' tab for devices is really good info

I'd like to ALSO get a 'Details' tab for a group, summarising the entire group's infrastructure.
Or better, some way to group devices by 'tag' and have a 'Details' tab for that too.

(I'm guessing that's where the 'tag' is headed)

**Comment by ryanblenis** [comment]
Hi @OutbackMatt 

There is already a "tag" function on the device's "General" page, and you can view devices by tag group using the "Sort" pulldown.

What @Ylianst would probably need is a better description of what the "Details" tab you're envisioning would actually have for data available.

Personally, I'd like to see a "column sets" feature for the "list" view in My Devices where any number of collected data (device last seen date/time, boot date/time, IP Address, WAN address, domain/workgroup, current logged in user, last logged in user, etc. --- just an idea if you're meaning something along the lines of that!

Something like the following (from a Kaseya grab, not MeshCentral, but you get the idea):

<img width="1562" alt="Screen Shot 2019-12-16 at 4 13 17 AM" src="https://user-images.githubusercontent.com/1929277/70894313-c7854700-1fba-11ea-8371-f54131e9da15.png">

**Comment by OutbackMatt** [comment]
Column selector is a great idea
I'd like to see the detail about Operating system, RAM, antivirus, motherboard brand and model, BIOS Version  etc on a single page for either a group or a tag. Additional info like when last seen, power state, IP address(es), user etc would all be useful

**Comment by Ylianst** [comment]
I did some work today on a device group summary page... it will take more work, but should be fun to have this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.5-y with a first pass at a summary screen for device groups. A fully customizable way of adjusting and grouping columns would be really nice... going to be a bunch of work but a good idea. For now, this is what I added, values are updated in real-time. I still have to work on improving the page for various browser size, etc.

![MC2-MeshSummary](https://user-images.githubusercontent.com/1319013/71119645-7c705d00-218f-11ea-9507-722969002647.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.5-z with improvements on the summary tab.

![MC2-MeshSummary](https://user-images.githubusercontent.com/1319013/71132335-01696f80-21ac-11ea-8512-6228d63f82da.png)

**Comment by openmoto** [comment]
Great feature! 
I like it so far.
Some thoughts :
1: **Power States** only shows devices powered on, when I turned off one of my windows 10 devices, []Powered 5 to []Powered 4. So the devices that are powered off doesn't count here for me. Wondering if making small changes like below would be beneficial?
![image](https://user-images.githubusercontent.com/36439190/71692696-e1b77700-2d67-11ea-83e7-571be86d0fa5.png)
2: **Agent Types** looks okay as it is, just wondering if it would be more appropriate to use "OS Distribution" in place of Agent Types? 
3: **Connectivity** I don't have any Intel AMT setups, but wondering if "Agent Types" is more appropriate here?
4: About the AV status, what do you think about using Bar charts to show AV status?
Something like this...
![image](https://user-images.githubusercontent.com/36439190/71693930-f0ebf400-2d6a-11ea-89cb-42b7a0b088c8.png)
