### ISSUE TITLE
0.4.5-w : no devices shown in My Devices

### ISSUE THREAD

**Issue by baikal** [Ylianst/MeshCentral#738]
Did upgrade to 0.4.5-w (from 0.4.5-q). All Devices are gone.

When running with --debug, i do see

AGENT: Verified agent connection to ############## (IP:PORT)

so the agents seem to connect.

**Comment by ryanblenis** [comment]
I just upgraded to w (from v) and don't have this issue. Any errors in the server or browser consoles?

**Comment by baikal** [comment]
no errors on server console, no devices using chrome, firefox or ms edge. no errors in chrome F12

**Comment by baikal** [comment]
back to 0.4.5-q (removed node_modules and npm install meshcentral@0.4.5-q). Devices still missing, nodes are listed in meshcentral.db ... oh well

**Comment by Ylianst** [comment]
I suspect that a device must have a name or some information that can't be parsed or is not handled right. Open the browser console, add "?trace=1" to the URL and start the page again. You will see all the messages being sent to the web application. Look for "**RECV** Object { action: "**nodes**", nodes: {…} }".

Open that object and copy the entire content here, or mail me privately if you like. I will test with the same input and see what is going on.

![x](https://user-images.githubusercontent.com/1319013/71041168-3eb2fc00-20dd-11ea-933f-efede2066bbc.png)

**Comment by PathfinderNetworks** [comment]
How long did you wait after upgrading the server?  There are times when I upgrade my server it may take 5-15 minutes for the devices to reconnect.

**Comment by Ylianst** [comment]
Right, I don't think it's a problem of devices not connecting, you can't even see the device group name on the web page so it's  not rendering the HTML correctly. If I get the raw node objects, I should be able to fix it.

**Comment by baikal** [comment]
Thanks @Ylianst  & @PathfinderNetworks.
In fact, the error is somewhere between the keyboard and the chair - turns out that for whatever reason after the upgrade, the [Sort] was on "Tags" ... which does not show anything. Back to "Groups" and everything is fine. 🤦

![image](https://user-images.githubusercontent.com/83393/71063601-4a4e0380-216d-11ea-8789-f16e21ec1652.png)
![image](https://user-images.githubusercontent.com/83393/71063774-c47e8800-216d-11ea-91a1-f8846eb3c9f5.png)

Sorry for the fuzz

**Comment by Ylianst** [comment]
Oh!! Thanks for reporting back. It's still a usability problem since your probably not the only one that ran or will run into this problem. I will add a message to say that no devices where found that match the sort/filter on the page to help with this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.5-y with a fix for this. Let me know if it's ok.

![x1](https://user-images.githubusercontent.com/1319013/71119141-5ac2a600-218e-11ea-882c-55d892e74b4b.png)

**Comment by baikal** [comment]
Updated to 0.4.5-z - and yes, this hint shows up.
Thanks.
