### ISSUE TITLE
Desktop display selection not working 0.45.x

### ISSUE THREAD

**Issue by adsgreen** [Ylianst/MeshCentral#741]
Just updated and noticed that when using desktop control the multi display droplist doesn't action any change.
I have a three screen setup and it's been working fine for a while now but installed 0.45.x and it no longer selects a screen and stays on showing all three displays.
javascript console shows nothing unusual (the script error occurs on a working 0.4.5.i server)
![image](https://user-images.githubusercontent.com/3473682/71071670-ef200f00-2174-11ea-84e0-81fe8662103a.png)

I've tried multiple machines and browsers with the same result.
Everything else looks to be working ok (screen scaling etc).

**Comment by Ylianst** [comment]
This is weird, I just tried it and it works for me. I did make a fix in MeshCentral v0.4.5-y to remove that red "createDataChannel" error on browsers that don't support WebRTC.

**Comment by adsgreen** [comment]
even weirder. it's not fine for me too. Will check to see what happened.
I think the destination PC's might have rebooted after a scheduled update.

**Comment by Ylianst** [comment]
Did you intend to say it's "now fine"? Just checking. Let me know if you see a problem.

**Comment by adsgreen** [comment]
Sorry! forgot that bit!
Yes, it does seem to be fine now. I suspect the reboot must have sorted the clients.
