### ISSUE TITLE
Separate language files and selectable in config.json

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#743]
possibility to set the correct language in the configuration files (config.json) and load the correct language file. and in case of problems being able to leave the language to the standard English language, and then to be able to bypass the incorrect file.

**Comment by Ylianst** [comment]
Right now there are many translations of the web pages, these pages are generated using an automatic tool that takes the "translate.json" and generates the web pages. The server will, by default, serve what the browser prefers the most, but users can override this in the "My Account" --> "Localization Settings".

The server would know really know if a specific web page works or not, it just servers it to the browser that does the work. The server's can't know in advance if a page will work.

This said, if you would like me to add a config.json setting to only support some languages on your server, I can add that. Would that be ok?

**Comment by petervanv** [comment]
If it is possible do that, it would be nice, in the answer you gave you mention the localisation setting, that page was not to be reached any more at that time. (The server did not load any laguage anymore even after changing browser prefert language in the settings of the browser) So if is there is an hardcoded option for language support it would be nice. (could you update the recourcetranslater.zip also with the dutch setting)

**Comment by Ylianst** [comment]
Oh, I see. When the server starts, the scans for available web pages. I understand now, I will default back to English if the page is not present. Working on that now...

**Comment by Ylianst** [comment]
Just updated [ResourceTranslator.zip](http://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip) to add Dutch. Also published MeshCentral v0.4.5-z that will now default to the English web page if a language web page is missing. Let me know if this works for you.

**Comment by petervanv** [comment]
I testted the function, but it doesn't work, when i hit the button translate (after translating files) it processes the file, relogging on blanks out the page. maybee the translation is corrupting important files. i used the ofline aswel athe online translation option. The online translation is still in "ar"

(translation file added created in offline translator)
[translate.zip](https://github.com/Ylianst/MeshCentral/files/3982734/translate.zip)

**Comment by Ylianst** [comment]
Yes, the translation is most likely not right. The usual problem is that the " and ' are not matching or not escaped correctly. When the page is blank, open the browser console and you will usually see an error and at what line, you can click on it and see the problem. I will check your translation now and do the fixes. Will post again when I am done.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-a with your new Dutch translations. Please update and start with the latest translate.json file that is in node_modules/meshcentral/translate/translate.json.

**Comment by petervanv** [comment]
I updated and it looks fine now (missed that \n).

thx for your support
