### ISSUE TITLE
Enhancement Add filter to multi desktop view

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#746]
Just trying some more features of this amazing software.

In the My Devices tab, Multi-desktop view, we have a group by drop down.
Can we get the same list in a 'filter by' drop down.

This way I could just monitor / manager a subset of all computers

**Comment by OutbackMatt** [comment]
Doesn't matter

I see that I can select devices via checkbox on the list screen, then switch to multi-view mode
That is effectively the same thing

**Comment by Ylianst** [comment]
When you say "Filter by", are you talking about the filter text box in red here?

![x](https://user-images.githubusercontent.com/1319013/71314870-af238b00-2405-11ea-8b05-67bea867ec3f.png)

**Comment by OutbackMatt** [comment]
Yes, I was think that could ALSO be on the Multi-desktops view

As an aside, I find that the filter doesn't work very well.
For instance I have a group with 8 computers in it, and when I filter by the first four letters of the group name, I only get five computers shown, some powered some not.

A fix is to additionally tag them with the same name.

**Comment by OutbackMatt** [comment]
ALSO,

Even once selected just a subset, the connect all button wants to connect to ALL devices not just the subset shown on the screen.

I would have use case for connecting to say all Servers that I manage that run a particular piece of third party software, and only them, to manage a required update across this group.

**Comment by Ylianst** [comment]
These are clearly bugs that need their own issue. Connect all should really connect to only the visible computers, this is not good.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-i with a fix for the multi-desktop "Connect All" button. Should only connect to computers that are visible.

Also, for the filter, can you check again with the "OS Name" checked and unchecked?

**Comment by OutbackMatt** [comment]
Both work thanks

checking 'OS Name' re-orders the list in alphabetical order of device name as per the OS, as it should

**Comment by OutbackMatt** [comment]
Edit: Actually sort of works.
I've created a new bug report
