### ISSUE TITLE
Enhancement: Users, device groups and tags

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#747]
I'd like to not only allocate users to device groups, but also the other way around

I'd like to allocate device groups to a user
I'd also like to allocate users to individual devices via tag

**Comment by Ylianst** [comment]
That will be some work but I understand the value. It's would be nice to be able to grant a device to a single user for a while. Right now, you have to create a new device group, move the device to that group and allocate the user to the device group.

**Comment by si458** [comment]
this is now possible, by going into a device group, and clicking 'add user'
![image](https://github.com/Ylianst/MeshCentral/assets/765314/25c87b8e-885e-4c7b-8151-ac4511ab6a51)
