### ISSUE TITLE
Cannot open files from Finder 

### ISSUE THREAD

**Issue by chucklingalong** [Ylianst/MeshCentral#75]
Cannot open files or launch applications in Mac Finder by double clicking.  Can "Select" with single click. 

Currently having to use contextual menu to open files or launch applications.  

Version:   MeshCentral v0.2.5-y 
Node:      v8.12.0
OS:          Ubuntu Server 18.04

MacOS versions tested:   High Sierra and Mojave.

Web Browsers tested:  Firefox 64, Chrome 71, and Edge

**Comment by Ylianst** [comment]
That is not good. Quite busy with lots of bug fixing, but will check on this.

**Comment by krayon007** [comment]
I think I found the issue... Looking into fixing it soon... I found some articles that said unlike Windows and Linux, on MacOS, you can't simulate a double click by merely posting two single click events...

**Comment by krayon007** [comment]
This is fixed in MeshCentral v0.2.6-w

**Comment by Ylianst** [comment]
I am going to close this one as I am pretty sure it's fixed. However, please feel free to reopen if needed.

**Comment by chucklingalong** [comment]
Confirming that it is fixed.
