### ISSUE TITLE
Bug: Check Server Version Option

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#750]
When I go to check the server version starting with 0.4.6-f as far as I can tell I get my current version but the latest version shows as unknown. I've upgraded to 0.4.6-i and the issue persists.

I do have on error in the error log shown below:
-------- 12/21/2019, 8:40:57 PM ---- 0.4.6-i --------

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at Socket. (C:\Program Files\Open Source\MeshCentral\node_modules\mongodb\lib\core\connection\connection.js:340:10)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by Ylianst** [comment]
The operating system if running your MeshCentral server? (OS and version) and also, what NodeJS version are you using?

I have made a few changes in that area in the last few days to make updates work on Windows thru HTTP proxies.

**Comment by asasin114** [comment]
I'm running it on Windows Server 2019 Version 10.0.17763.914 with Node 11.10.1

**Comment by PTR-inc** [comment]
Same here on server 2016/node 13.3.0

**Comment by TotallyNotElite** [comment]
No issues here. Ubuntu Server 18.04.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-j with a fix for this. It only affects Windows instances. To update, you can stop the service, open a command prompt to the parent folder of "node_modules", type "npm install meshcentral" and start the service again. After that, the normal update path should work.

**Comment by asasin114** [comment]
That worked perfectly for me! Thank you!
