### ISSUE TITLE
Missing translation strings & merge strings in to single string

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#752]
I have translated the english into dutch, and found that some english text isn't in the file. so translation is not possible. I have seen some text that is more then once present, but the same as other text. possible to clean up that text?

see enclosed file's (text explanation, zip is translation itself)
[hints.txt](https://github.com/Ylianst/MeshCentral/files/3993020/hints.txt)
[translate.zip](https://github.com/Ylianst/MeshCentral/files/3993022/translate.zip)

**Comment by MailYouLater** [comment]
This is the contents of the [hints.txt](https://github.com/Ylianst/MeshCentral/files/3993020/hints.txt) file, slightly modified to fix formatting where GitHub would mangle it.
> missing strings in the english part:
> 
> features:
> 	1. Remove device on disconnect 
> 	2. Sync server device to hostname
> 
> notifications: 
> 	1. Notification settings must also be turnt on in account settings (missing)
>  	2. translated in the language file, but not displayed device connections / disconctions / desktop and serial events
> 
> Tab summary when selecting an device group
> 
> summary: (not found translation in file)
> 	1. power states (above ring with power states
> 	2. Agent Types
> 
> my account:, sub part
> 	notification settings
> 	1. Display Device Group Name
> 
> my users:
> 	1. Groups
> 	2. select an user, at server rigths click at the righst the user has, it says: server files XXK max, blank for default --> not translated and not to find in english too
> 	3. Day, 7 Day Login State
> 	4. change Password & Delete user
> 
> my server:
> 	1. all information items are missing from the translation (english als not tot be found)
> 	2. cpu load --> not to be found in translation file too
> 	3. the on mouse over event's are ver small, it just not shows all the text about the usage (ring in green color / gray color)
> 
> My device	click at the pictogram (4 sqaures) desktop, then sort en select "tags" the text "no devices with tags found" is also missing in translation file
> 
> ----------------------------------------------------
> Mesh agent on client computer.
> 
> In the mesh agents the language is als in english
> Administrator is requsting kvm acces grand ? --> De externe gruiker vraag toegang tot de computer. Toestaan ?
> Administrator is requsting terminal acces grand ? --> De externe gruiker vraag toegang tot de terminal. Toestaan ?
> Administrator is requsting remote file acces grand ? --> De externe gruiker vraag toegang tot de bestanden. Toestaan ?
> 
> message of sharing in message center is english -->  
> remote desktop sesion	: 	de "username" is gestart met extern computerbeheer
> remote file session	: 	de "username" is gestart met extern bestandstoegang
> remote terminal session	: 	de "username" is gestart met extern terminal toegang
> 
> sharing desktop bar at the top of the screen
> sharing desktop with: "username"; --> Buroblad wordt gedeelt met: "username"
> 
> possible get the language text from the operation system, the choises "yes or no" are already translated in the os system language
> 
> -------------------------------------------------
> 
> hint:
> 
> I see a lot of equal sentences for translation, it is not possible to merge them. example
> 
> 1) Verify email
> Locations:
> default.handlebars-> container-> column_l-> p2-> p2AccountActions-> 3-> verifyEmailId-> 0
> default-mobile.handlebars-> container-> page_content-> column_l-> p3-> p3info-> 1-> p3AccountActions-> 7-> 1-> verifyEmailId-> 0
> 
> 2) Verify Email
> Location:
> default.handlebars-> container-> footer-> 3-> verifyEmailId2

**Comment by Ylianst** [comment]
The translate.zip is not right, I can't read that file correctly. If you can mail me the latest file again, that would be great. The zip if correct, but the .json in the zip is not good. For hints.txt, this is a excellent! I am working on fixing these now!

**Comment by petervanv** [comment]
generating new file, just a few minute's. i'l send it to your email

**Comment by Ylianst** [comment]
Thanks. All the hints you provided are all excellent. I am about to publish a new version with many improvements.

**Comment by Ylianst** [comment]
I have not received your new translations, but I published MeshCentral v0.4.6-m with many improvements based on your hints.txt. I still have work to do, for example the event log is not translatable yet, I need to work on translating agent side strings, etc. The server side web application should be better.

**Comment by petervanv** [comment]
that's weird, I sent the mail to your gmail account, before I opened this thread I had already sent the translate.zip to the gmail account. maybe it has entered the spam folder. I will also send the file in cc to your hotmail, as well as here on github
[translate.zip](https://github.com/Ylianst/MeshCentral/files/3997724/translate.zip)

**Comment by petervanv** [comment]
following earlier missing English lines of text, the email invitation is also in English. I would like to be able to translate this as well as possibly enter content myself, this could make your work easier

**Comment by Ylianst** [comment]
Hi. I accepted your latest pull requests and it is now in MeshCentral v0.4.6-p.

On the web translation page, there are two copies of translate.json: 
```
/node_modules/meshcentral/translate/translate.json
/meshcentral-data/translate.json
```

When you open the web translator page, it will use the "meshcentral-data/translate.json" if it exists, if not, it will use the "/node_modules/meshcentral/translate/translate.json" version. When you save, it will save in "/meshcentral-data/translate.json".

So, when you upgrade to a new MeshCentral, you will not see the latest "translate.json", you will see your copy in "meshcentral-data". The solution right now is to rename or delete the "/meshcentral-data/translate.json" version. I have to work on a better way to merge the translation.json files.
