### ISSUE TITLE
Terminal Access Broken To MacOS Endpoints

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#755]
Checking the commits, it appears MacOS terminal connections fail since commit [3693aff8473ecf7380fad094dbf76fe377f1875a](https://github.com/Ylianst/MeshCentral/commit/3693aff8473ecf7380fad094dbf76fe377f1875a)

Tested with 10.13 (High Sierra)

**Comment by krayon007** [comment]
I fixed this... It will be in the next server release. The pull request linked above, tries to use /usr/bin/script, which exists on MacOS and FreeBSD, but the BSD based version does not support the same featureset as the linux version, so the way it's used to launch terminal is not compatible with MacOS or FreeBSD. So I updated it to only try to use this on linux platforms.

**Comment by ryanblenis** [comment]
Thanks @krayon007 !

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-k with Bryan's fix.

**Comment by ryanblenis** [comment]
Just FYI - confirmed
