### ISSUE TITLE
My Devices move on screen when right click is selected

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#756]
on the my devices screen (full screen 1920 x 1080), when I right click on a computer, the screen refreshes and the icons move, before the right click context menu appears.

Seems to be since v.0.4.6-i, when the modifications for multi-display were made, but this movement happens on the main 'my devices' view.

Thanks for you great work on this project

**Comment by Ylianst** [comment]
I just tried it... Does this only happen when the context menu is shown below the browser window and two scroll bars show up on the right? Like the picture below?

![x](https://user-images.githubusercontent.com/1319013/71383081-a363d000-258f-11ea-9da7-7aa876a4f6f6.png)

**Comment by OutbackMatt** [comment]
Yes exactly that.
Thanks

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-l with a fix for this. Let me know if it works.

**Comment by OutbackMatt** [comment]
Yes thanks

Thanks for your work
