### ISSUE TITLE
Reset password error

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#757]
After request reset password, i did receive an reset mail. It say's: "If you did not initiate this request, please ignore this mail." but if you try to logon with the correct username/password (before reset)
it says you need to change it. so you cannot ignore it.

**Comment by petervanv** [comment]
revision wrong change, it seems that this is due to creating the account. when creating you are forced to change the password.
This is confusing, possibility to adjust this? create an account, where the user is given the option to set the password and thereby confirm the e-mail address instead of in advance?

**Comment by Ylianst** [comment]
Hi. I don't understand the problem. You need to describe step by step how to create the problem and what is expected. For example, when you say "creating the account", I am not sure if this is the administrator in the "My Users" panel, or a user at the login screen. Please explain in more detail, thanks.

**Comment by petervanv** [comment]
the first part of the origina question was based on an misunderstanding.
as an admin i create an account, i need to select 3 options before the account can be created.
username / email /password. --> checkbox need 3 options (force change, verify mail send invitation)
normaly an user needs to verify the mailadres, (not the administrator) in the email you get is you are invited, but where the server url to the mesh server needs to be there's only an "," instead of an www.yoururl.com

**Comment by petervanv** [comment]
![serveradres-2](https://user-images.githubusercontent.com/58996467/71450471-17a29d00-2763-11ea-98ba-1427bd9518d3.jpg)
![serveradres-1](https://user-images.githubusercontent.com/58996467/71450472-17a29d00-2763-11ea-8140-223afcdca1b5.jpg)

**Comment by Ylianst** [comment]
@petervanv, can you send me the following values for your server in config.json int he domain section? "titlehtml", "title", "title1", "title2", "titlePicture" - Thanks.

**Comment by petervanv** [comment]
"_Title": "MyServer",
      "_Title2": "Servername",
      "_TitlePicture": "title-sample.png",

the other are not present (default json confg)

**Comment by Ylianst** [comment]
Ok, I will look into this when I get a chance.

**Comment by petervanv** [comment]
I solved the problem, if you keep the default name of "Meschcentral" and therefore do not change anything in the json settings, the software will mail out the name as "," instead of the name that you can set there. Hint: is it possible to put all settings in the manual so that this can be solved faster?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-s with a fix for this. It will now use "MeshCentral" if no title is specified.

**Comment by petervanv** [comment]
Fixed.
