### ISSUE TITLE
When deleting & creating a user, the user logs are kept accross these operations.

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#758]
after creating a user, and then deleting the user, it will be gone as expected, but creating a new user with the same username (but different email address) gives the history of the previously deleted account. it seems that no unique ID is created for the user. this seems to me not the intention (privacy)

**Comment by Ylianst** [comment]
This is indeed a problem. Would it be ok if I delete all logs for that user upon user creation? This way, you keep the logs when the user is deleted, but not when created again.

**Comment by petervanv** [comment]
that is an solution, and it would offer upon delete to download the userlog. than its an superb solution

**Comment by petervanv** [comment]
The fix is accetable, logs are cleared that is fine, the confirmation dialog is not yet to be translated i saw in the file's (en --) nl/ja/cz/fr hope that is fixed sometime too

**Comment by Ylianst** [comment]
Good point. I just added "node translate.js extractall" to my standard release script, so on each release now the translate.json file should have all the English strings.

**Comment by Ylianst** [comment]
FYI. This is the new feature when creating a new user account.

![MC2-UserCreateClear](https://user-images.githubusercontent.com/1319013/71539053-27e58400-28eb-11ea-81fd-fbcb75429cd9.png)
