### ISSUE TITLE
How and when does the agent update?

### ISSUE THREAD

**Issue by joshabts** [Ylianst/MeshCentral#759]
Do agents self-update or is there something that needs to be done manually on them to update?

**Comment by Ylianst** [comment]
The MeshAgent is updated automatically by the server once the server is updated. It takes just a few seconds to a few minutes to do and is performed the next time an older agent connects to the server.

Someone pointed out that the MeshAgent version number does not change and that is correct, right now the agent version is always 0.2.1 or something like that. This is just me not changing the agent version number. A good way to make sure it's being updated on Windows is to right-click on the exe file, select properties and look at the certificate signature date. Hope it helps.

**Comment by joshabts** [comment]
Ahhh ok, that makes more sense then, I didn't see a way to force an update,
but the agent kept saying the same version, so I was confused of what was
happening.

Thanks for the information!
