### ISSUE TITLE
Add SAML/CAS/LDAP support

### ISSUE THREAD

**Issue by lhaeffele** [Ylianst/MeshCentral#76]
In order to be able to use this software in big companies, it would be good to add SAML or CAS or LDAP support for user authentication.

**Comment by Ylianst** [comment]
MeshCentral has Windows Domain authentication support. When enabled, users don't have to create accounts or login, domain authentication takes care of all of that. You need to install MeshCentral on a Windows server that is on a domain and add "auth":"sspi" in the domain section of config.json like this:

`{
  "settings": {
    "Port": 4430,
  },
  "domains": {
    "": {
      "auth": "sspi",
    }
  }
}`

After you set this, you can clear your database and the first user to hit the site will have administrator rights on the site. If you have other ideas for what support should be added, please let me know.

**Comment by openmoto** [comment]
I haven't tried the Active Directory authentication, but would it automatically recognize domain admins?
I think using (AD/LDAP) Groups to manage access would be good feature..
Thanks

**Comment by Ylianst** [comment]
There is no AD/LDAP group support yet, so no, not yet on the recognize domain admins. I am still working out some things with AD support since I am deploying a MeshCentral server with AD very soon.

**Comment by Ylianst** [comment]
I am going to close this one since MeshCentral does have AD support. You need to add "auth":"sspi" in the domain of config.json. If there are more specific feature requests, please open a new issue. Thanks.
