### ISSUE TITLE
Not displayed history login state

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#760]
![power-state](https://user-images.githubusercontent.com/16576224/71436036-64f41f80-270d-11ea-8868-415e8adc0b03.png)
7 day login state is empty. Version 0.4.5-k, used mongodb

**Comment by Ylianst** [comment]
Ha yes, that is because it was never implemented at all. This just a placeholder for me to implement it at some point. Thanks for noticing :)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-u with the user history removed (it was never implemented). In this version, it's been replaces so you can add/remove device groups and add/remove a user group membership. Note that user groups don't do anything right now.

![MC2-UserPanel](https://user-images.githubusercontent.com/1319013/71605363-256a7080-2b1d-11ea-884a-b86a0c0f2783.png)

**Comment by Ylianst** [comment]
Oh dear... I confused @MailYouLater... feedback appreciated.
