### ISSUE TITLE
Add Raspberry Pi icon

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#764]
I like to have an r-pi icon to choose from

![R-PI](https://user-images.githubusercontent.com/58996467/71516460-68bca900-28a9-11ea-8350-24f52132ff08.png)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-q with Raspberry Pi icon added. I would prefer a clip art type icon and I found a free one, but it was for the Raspberry Pi v1 which is dated. If anyone has a better clip art, I would appreciated suggestions.

![MC2-RaspberryPiIcon2](https://user-images.githubusercontent.com/1319013/71535746-19807380-28bd-11ea-866a-5d51c50eb641.png)

![MC2-RaspberryPiIcon1](https://user-images.githubusercontent.com/1319013/71535750-1d13fa80-28bd-11ea-98e6-3bd5d0cc151f.png)

**Comment by petervanv** [comment]
Fixed, thx for the quick implementation

**Comment by Ylianst** [comment]
MeshCentral v0.4.6-q has a log of changes to user access control in preparation for user groups, if you find any errors with this version, please report them. Thanks.

**Comment by Ylianst** [comment]
I just realized I had not added this new icon to the mobile web site. It will be in MeshCentral v0.4.6-s when I next publish it.
