### ISSUE TITLE
Text position (NL / FR)

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#766]
I saw that some text falls behind the bar when switching, this is the case with multiple languages.
![text_1](https://user-images.githubusercontent.com/58996467/71536188-f54c8300-290c-11ea-947e-618d7427fe3e.jpg)

(edit forgot to remove user info)

**Comment by MailYouLater** [comment]
FYI: Old versions of GitHub posts are still accessible unless you click the 'edited' button, click the old version you wish to remove, then click 'delete'.

**Comment by Ylianst** [comment]
@MailYouLater Thanks for pointing that out, I had no idea.
@petervanv Ok, I will work on something to fix this.

**Comment by Ylianst** [comment]
I did a fix for the next version. For non-English languages, the tool bars will be variable width. This will be in MeshCentral v0.4.6-r when I publish it later.

![MC2-InterFix](https://user-images.githubusercontent.com/1319013/71539416-b7d9fc80-28f0-11ea-95da-0ba9dbc18a49.png)

**Comment by petervanv** [comment]
Fixed, thx
