### ISSUE TITLE
Agent Remote Desktop Quality

### ISSUE THREAD

**Issue by FilGov** [Ylianst/MeshCentral#767]
Cannot set agent remote desktop quality to 100% on MeshCentral.com.

**Comment by Ylianst** [comment]
Hi. If you run your own MeshCentral server, you can add this line to the settings section of config.json to allow users to select high quality.

`"AllowHighQualityDesktop": true`

For [MeshCentral.com](https://www.meshcentral.com), this would increase the amount of traffic on the public server, not something I am going to do. You should setup your own server is you want to do this, it's not expensive to host on AWS, Azure, Google or other providers.
