### ISSUE TITLE
Mesh service crash after deleting / edit a user

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#772]
I deleted myself as user wile logged in as that user, and then i was logged out (seemd logical) but page could not be loaded to main login site

 i looked in an other browser with open administrator account, i noticed i was logged out. i looked at my server i noticed the following error

-------- 2019-12-29 12:39:19 PM ---- 0.4.6-r --------

/usr/bin/node[2471]: ../src/node_crypto.cc:3027:node::crypto::CipherBase::UpdateResult node::crypto::CipherBase::Update(const char*, int, unsigned char**, int*): Assertion `MaybePassAuthTagToOpenSSL()' failed.

-------- 2019-12-29 12:39:20 PM ---- 0.4.6-r --------

 1: 0x8fa050 node::Abort() [/usr/bin/node]
 2: 0x8fa125  [/usr/bin/node]
 3: 0xa126c2  [/usr/bin/node]
 4: 0xa16da7 node::crypto::CipherBase::Update(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/bin/node]

-------- 2019-12-29 12:39:20 PM ---- 0.4.6-r --------

 5: 0xb8e64f  [/usr/bin/node]
 6: 0xb8f1b9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
 7: 0x2804a8b5be1d 

Server: Ubuntu server 18.04 LTS running as virtual at an qnap

![Screenshot_2](https://user-images.githubusercontent.com/58996467/71557382-86bf1080-2a45-11ea-955e-670923e74bf7.jpg)

**Comment by petervanv** [comment]
-------- 2019-12-30 9:37:43 AM ---- 0.4.6-s --------

/usr/bin/node[2922]: ../src/node_crypto.cc:3027:node::crypto::CipherBase::UpdateResult node::crypto::CipherBase::Update(const char*, int, unsigned char**, int*): Assertion `MaybePassAuthTagToOpenSSL()' failed.

again, while deleting myselef as an user, again the server crashed. Now the "deleted"user did not get removed and is still able to login

error log:
-------- 2019-12-30 9:37:43 AM ---- 0.4.6-s --------

 1: 0x8fa050 node::Abort() [/usr/bin/node]
 2: 0x8fa125  [/usr/bin/node]
 3: 0xa126c2  [/usr/bin/node]
 4: 0xa16da7 node::crypto::CipherBase::Update(v8::FunctionCallbackInfo const&) [/usr/bin/node]
 5: 0xb8e64f  [/usr/bin/node]
 6: 0xb8f1b9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
 7: 0x222ce21dbe1d

**Comment by petervanv** [comment]
an other crash after editing an user (locking account)

/home/administrator/node_modules/meshcentral/meshuser.js:965
                        if (obj.user.links == null) return;
                                     ^

TypeError: Cannot read property 'links' of undefined
    at WebSocket.processWebSocketData (/home/administrator/node_modules/meshcentral/meshuser.js:965:38)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/administrator/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/administrator/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/administrator/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/administrator/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/administrator/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-t with fixed for these. Deleting your own account was broken and is now fixed.

**Comment by petervanv** [comment]
confirmed fix
