### ISSUE TITLE
Difference between server admin and device group admin

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#773]
an user with limited rights, confirmed he can't do anything is displayed as an Full administrator.
The display is identical in dutch.

First picture is screenshot from admin account
![Userrights-2](https://user-images.githubusercontent.com/58996467/71575218-74e47880-2aec-11ea-8c16-a336be794b81.jpg)

Second picture is screenshot in the user account
![Userrights-1](https://user-images.githubusercontent.com/58996467/71575389-123fac80-2aed-11ea-9f06-e80739b23fea.jpg)

**Comment by Ylianst** [comment]
This is not a bug. The rights you have on the server and rights you have on a device group are two different things. You can have no rights to manage the server, but full administrative rights on all devices in a group.

I hope this makes sense. If there are improvements to the user interface to make this better, let me know.

**Comment by petervanv** [comment]
oke, thats makes sence, but it would be more clear if you call it in full device group admin instead of full administrator.

**Comment by MailYouLater** [comment]
Perhaps call it "Group Administrator"?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-u with this change. In this version, the user panel is upgraded quite a bit. You can now add/remove device groups and add/remove a user group membership. Note that user groups don't do anything right now.

![MC2-UserPanel](https://user-images.githubusercontent.com/1319013/71605322-d1f82280-2b1c-11ea-9bbc-6c95b359f8ac.png)

**Comment by petervanv** [comment]
fixed, hope there will be an expansion of the funtion "user groups" soon
