### ISSUE TITLE
Question: running meshcmd without pressing Enter

### ISSUE THREAD

**Issue by D4V3M0NK** [Ylianst/MeshCentral#778]
<tl; dr>
Is there a switch to meshcmd that either puts the entire process in the background, or prevents me from pressing Enter if I use the "to background" character "&" ?

< long winded soliloquy >
I have a small bash script that calls meshcmd along with an actionfile and appends the "&" character at the end to place it into a background process so that I don't have a number of terminals running at the same time for connections to remote systems. This works pretty well as, as I'm running the script, it appends all the information to a file so that I can see what connections I have open, to where and under which local port and **somewhat importantly** I get the process of that instance so that I can kill it later when I'm finished with it.

The only slight annoyance is having to press Enter in order to place the script into the background and therefore becomes the root of my question: Is it possible to run meshcmd as a background task without pressing "Enter"?

Along with (effectively) 
`meshcmd --actionfile myfile.txt &`

I've also tried the somewhat exotic
`meshcmd --actionfile myfile.txt </dev/null &>/dev/null &`
which does appear to run without pressing Enter, but doesn't then provide an accurate process ID.

Help me @Ylianst @krayon007  ... you're my only hope...

_[ By the way chaps, Happy New Year to you both and the rest of the excellent MC2 Team! ]_

**Comment by ryanblenis** [comment]
I'm not sure what arguments @Ylianst might recommend for making it run in the background in the way you're looking for, but one thing you may want to look at is the [screen](https://linux.die.net/man/1/screen) command, where you can launch the command, have it run in the background, even name the screen session so you know what's running there, as well as switch to the screen to see any applicable output. It's baked into OSX and (many) *nix by default.

Of course if you're just using meshcmd for port forwards and want to make it a tad easier, I'd recommend my plugin, [RoutePlus](https://github.com/ryanblenis/MeshCentral-RoutePlus). Happy New Year!

**Comment by si458** [comment]
closing as stale, please update to latest version 1.1.20, and use at least node 18 or above, if issue still happens, please reply back
