### ISSUE TITLE
Agent port Different from Web

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#779]
Can i have different web port from agents??

thanks

**Comment by Ylianst** [comment]
The MeshAgents connect on the main HTTPS port of MeshCentral, this is generally port 443.

If you want to know how the connection works and security, [MeshCentral Design & Architecture document](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2DesignArchitecture.pdf) has details on this.
