### ISSUE TITLE
Download files from remote to host

### ISSUE THREAD

**Issue by edorbike** [Ylianst/MeshCentral#78]
Hi, I need download files from remote to host. Is It possible?
I can upload files from host to remote on Files tap but I don´t know how to download.
Thanks

**Comment by Ylianst** [comment]
Hi. You should be able to download by clicking on the file name. Each file name is a download link. If it does not work, let me know.

On Jan 23, 2019 12:26 AM, edorbike <notifications@github.com> wrote:

Hi, I need download files from remote to host. Is It possible?
I can upload files from host to remote on Files tap but I don´t know how to download.
Thanks

**Comment by edorbike** [comment]
It works perfect. How can I download folders?

**Comment by jsastriawan** [comment]
Hi,

If you have SFTP enabled on your host, you could actually tunnel your SFTP client connection through MeshAgent connection using MeshCmd.

See: https://youtu.be/S38mg_BPe-M

If you are want a more comfortable way managing your files with your favourite remote file transfer utility.

Additionally you can also use mc2router that I wrote on my GitHub repo. It uses the same protocol as MeshCmd.
