### ISSUE TITLE
Terminal not echoing on Linux Peppermint 6, Ctrl-C, Ctrl-X not functioning.

### ISSUE THREAD

**Issue by nlyaple** [Ylianst/MeshCentral#781]
Mesh Central agents installed on Linux Peppermint 6, 32 bit stopped echoing characters as they are typed. Control+C, Control+X, etc do not work.  Including using the Control Send button.  This was working prior to upgrading to 0.4.6-u.

Checked our Debian 9, 32 bit systems and the work normally.

**Comment by nlyaple** [comment]
Issuing a 'reset' command corrects the terminal session.

**Comment by JSuenram** [comment]
Any update on this? I have a user who is using DEBIAN 11 and he wants to Remote-Control some clients. Using CTRL on local keyboard does not work. It does from MAC or Windows but not from Debian.

**Comment by krayon007** [comment]
> Any update on this? I have a user who is using DEBIAN 11 and he wants to Remote-Control some clients. Using CTRL on local keyboard does not work. It does from MAC or Windows but not from Debian.

Are you talking about connecting to a remote system running Debian 11, or connecting FROM  a system running Debian 11? I'm not aware of any current issues with terminal on linux distros... Also, which browser are you using?

**Comment by krayon007** [comment]
![image](https://user-images.githubusercontent.com/29240564/151417813-e10c9d7b-1567-450b-958d-950cf3c23a69.png)

I just tested on Peppermint 6, 32 bit, and it seems to work.

**Comment by JSuenram** [comment]
> > Any update on this? I have a user who is using DEBIAN 11 and he wants to Remote-Control some clients. Using CTRL on local keyboard does not work. It does from MAC or Windows but not from Debian.
> 
> Are you talking about connecting to a remote system running Debian 11, or connecting FROM a system running Debian 11? I'm not aware of any current issues with terminal on linux distros... Also, which browser are you using?

I am connecting from Debian 11 to Windows Target.
There open Exploer ans select several files by CTRL+Mousebutton. CTRL is ignored so far.
Used Browser is "Brave" chromium-based.

**Comment by krayon007** [comment]
> > > Any update on this? I have a user who is using DEBIAN 11 and he wants to Remote-Control some clients. Using CTRL on local keyboard does not work. It does from MAC or Windows but not from Debian.
> > 
> > 
> > Are you talking about connecting to a remote system running Debian 11, or connecting FROM a system running Debian 11? I'm not aware of any current issues with terminal on linux distros... Also, which browser are you using?
> 
> I am connecting from Debian 11 to Windows Target. There open Explorer ans select several files by CTRL+Mousebutton. CTRL is ignored so far. Used Browser is "Brave" chromium-based.

I assume you are talking about using desktop remoting, not terminal?

**Comment by JSuenram** [comment]
> > > > Any update on this? I have a user who is using DEBIAN 11 and he wants to Remote-Control some clients. Using CTRL on local keyboard does not work. It does from MAC or Windows but not from Debian.
> > > 
> > > 
> > > Are you talking about connecting to a remote system running Debian 11, or connecting FROM a system running Debian 11? I'm not aware of any current issues with terminal on linux distros... Also, which browser are you using?
> > 
> > 
> > I am connecting from Debian 11 to Windows Target. There open Explorer ans select several files by CTRL+Mousebutton. CTRL is ignored so far. Used Browser is "Brave" chromium-based.
> 
> I assume you are talking about using desktop remoting, not terminal?

Yes, sorry this was not very good explained from my side....

**Comment by krayon007** [comment]
![image](https://user-images.githubusercontent.com/29240564/151419070-62013fd3-bba2-4034-a48b-33b52834c201.png)

Does it make any difference, if you click on settings, before connecting KVM, and select the "Use remote keyboard map"?

**Comment by JSuenram** [comment]
> ![image](https://user-images.githubusercontent.com/29240564/151419070-62013fd3-bba2-4034-a48b-33b52834c201.png)
> 
> Does it make any difference, if you click on settings, before connecting KVM, and select the "Use remote keyboard map"?

No sorry, it does not work regardless if Remote Keyboard Map is enabled or not....

**Comment by si458** [comment]
closing as stale
