### ISSUE TITLE
One Time Password (OTP) Broken Link

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#784]
first: everybody a happy new year en much coding in 2020.

second, when you use the 2step authentication, you can scan the code or click on the link.
that link calls an 404 page: https://yourdomain.url/'%20+%20message.url%20+%20'
this occurs in the english and local language.
![Screenshot_3](https://user-images.githubusercontent.com/58996467/71720157-fa379800-2e20-11ea-874a-f34cb427fb0d.jpg)

**Comment by MailYouLater** [comment]
Interesting.  Using the Inspect Element feature of my browser, I'm seeing this `<a href="' + message.url + '" rel="noreferrer noopener" target="_blank"> this link</a>`, obviously that's not what was intended.  I _think_ it used to work... Did it possibly get broken while enabling multi-lingual support?

**Comment by Ylianst** [comment]
Ha! Nice catch. I messed that up when internationalizing the web pages. The fix will be in the next published version.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-w with a fix for this. Let me know if it works.

**Comment by petervanv** [comment]
nope. thats not working, i get an blank page. see screenshot. (i did aedit the link with the key and my url (privacy)
![Screenshot_4](https://user-images.githubusercontent.com/58996467/71754572-09513100-2e87-11ea-8568-b6c049d4030c.jpg)

**Comment by MailYouLater** [comment]
Looks to my like it would probably work if you actually had some compatible software on your PC.  I don't, so my computer says "unknown protocol", but it opens a page with the same URI as is in the QR code, so unless someone who actually uses this form of 2FA can verify that it is or isn't working, it's working as well as I can verify for you.
![image](https://user-images.githubusercontent.com/1279475/71754803-b18dd800-2e3c-11ea-97b3-6a479b8fdb43.png)

**Comment by Ylianst** [comment]
Right... so that link works on most mobile phones. If you happen to have software that generate time based codes on your PC, that like would probably work. If you did not have this link, it would be difficult to take a picture of the QR code using your own phone. This said, if there is a way to detect or improve presenting this link, I am open to suggestions.

**Comment by petervanv** [comment]
oke, confirmed it is fixed, i checked it on my mobile phone. I diddn't had that software on my pc
