### ISSUE TITLE
Double device groups on android

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#786]
I tested the application on my android phone, i did see all my device's in the device groups.
I scrolled down to the bottum of the screen i notice more groups which where empty.
i t say's no device's. when i click at that name, im taken to what it looks like to be the user groups.

when looking at the same page in "desktop mode" its loaded as it should be.

![Screenshot_20200104-120752](https://user-images.githubusercontent.com/58996467/71764779-76e37880-2eec-11ea-9671-b2bfd4a9ddc5.png)

![Screenshot_20200104-120826](https://user-images.githubusercontent.com/58996467/71764778-76e37880-2eec-11ea-85bd-f2b67707f6d0.png)

**Comment by Ylianst** [comment]
Mobile web application does not support user groups yet and I think that is causing the problem. Note that user groups don't work yet in general, hopefully I will activate them in the next week. I am going to work on adding user group support to the mobile app now...

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.6-x with a fix for the mobile app... Let me know if it works.

![MC2-MobileUserGroups](https://user-images.githubusercontent.com/1319013/71770896-9926c780-2ee7-11ea-8f30-f300148eff92.png)

**Comment by openmoto** [comment]
I tested on my phone and got the same before the update.
Confirmed it's fixed now on version 0.4.6-x

**Comment by petervanv** [comment]
i have tested it and confirmed fixed.
