### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#787]
Hi,

I am on a half with russian translation of MeshCentral .
Tried to translate server to see how it looks like - but did not worked for me.
Shall I fully finish it to be able to test it?

Thanks.

**Comment by petervanv** [comment]
where did you start the translation? in the meshcentral itself ? or with the tool provided or at this website (github)
 witin the translation on meshcentral: click translate server, than save to file and save to server. use laocalisation  pick the language u started to traslate (ar) (nl), u shoud see the translated strings. the other 2 options are create an pull request whithin github, the other option is create an topic with the saved file from the server or translation tool. after the it will be available in the future update.

greets peter

**Comment by Ylianst** [comment]
Hi. First, thank you for working on the Russian translation!!! This is very appreciated. I will gladly accept a partial translations, send me your translate.json file at [my email address](https://www.meshcommander.com/contact-information). I will take a look at it and integrate it.

Peter's instructions are correct (Thank Peter!). You do not need to do a full translation to see the result. A different way to go is to put your translate.json file in /node_modules/meshcentral/translate then go in the /node_modules/meshcentral/translate folder and run:

node translate.js translateall

The first time you do this, you will have to restart the server (so Russian selection will show up). After that, you can change the translate.json and run the command again and hit refresh on the browser to see the results. Hope this helps.

**Comment by vitko-bg** [comment]
Just a quick update - 200 more rows to go ........
@petervanv You said "click translate server, than save to file and save to server" - 1st OK, second also, but where is and how to "save to the server"??? Upload it manually into meshcentral-data?

**Comment by petervanv** [comment]
see picture:
![Screenshot_5a](https://user-images.githubusercontent.com/58996467/71896664-b14f4e80-3154-11ea-8c31-f405aac1003b.jpg)

1. click here, your server is translateted
2. save the translation file to your server (button far left)
3. save the file to your computer, 
3.1mail it to ylianst@gmail.com 
3.2 post it here in an comment, it wil be merged into the new update file.

hope this clears things

**Comment by vitko-bg** [comment]
It is completely clear that I can send it to ylianst@gmail.com - but how a can see it and test it on my server before sending it..... I have tried already with clicking on Translate Server - it does not work - nothing is translated and Russian is not appeared in localisation settings .......

**Comment by vitko-bg** [comment]
That is the result:
![image](https://user-images.githubusercontent.com/59362521/71897731-4e0eed80-314f-11ea-8b23-cbf866857f11.png)

And after couple of minutes:
![image](https://user-images.githubusercontent.com/59362521/71897776-73036080-314f-11ea-9183-08cf2e128cda.png)

**Comment by petervanv** [comment]
after that @Ylianst the file has merged into the master it wil be visible there.
at the localisation you can select the russian language and it should be translateted

**Comment by petervanv** [comment]
i forgot, which string did you select for translating?  if it is en --) select it in the localisation, later on ru is filed with russian language

**Comment by vitko-bg** [comment]
Hmmmmm - went into a problem....
I followed @Ylianst steps "put your translate.json file in /node_modules/meshcentral/translate then go in the /node_modules/meshcentral/translate folder and run: node translate.js translateall and restart"
It worked, finished all translation, BUT as soon as I logged in and changed language to Russian - the all page went white .................
Here is the file: so please validate it if all is OK. Thanks.

[RU_translate.zip](https://github.com/Ylianst/MeshCentral/files/4031746/RU_translate.zip)

BTW - How I can put it back, please advise ......

**Comment by vitko-bg** [comment]
Will it help if I will run "npm install meshcentral" to update version to latest one???
Please advise before I broke the installation completely - as lots of clients are in the DB connecting to my server. Thanks in advance.

**Comment by MailYouLater** [comment]
For the future, it would probably be a good idea to create/test/edit your translations on a separate server, not your main production server, but since you've already done that and are having issues, I do believe running `npm install meshcentral` in the appropriate location _should_ fix the install, but you will most likely lose your translation(s) so make sure you have them backed up somewhere first.

**Comment by vitko-bg** [comment]
"npm install meshcentral" - fixed the problem ...
Did not lost translation file - so if encoding can be fixed during exporting translation - we can have a russian version of MeshCentral

**Comment by vitko-bg** [comment]
All is sorted - but please mark the export translation as a BUG.

I have manually copied translate.json from meshcentral-data folder, and file itself is fine now - not tried translation yet

**Comment by petervanv** [comment]
i had a lot of trouble also, i changed to editing on github direct. nice that its fixed with your server

**Comment by Ylianst** [comment]
Oh wow, so much going on! First, when you do a translation and see the we site is write, this is generally because one of the strings has incorrect quotes or escaping. For example, if you add a "\r\n" at the end of a translated string that should not have that, it will cause the web page to not be correct. You can open the browser console and see where the error is, fix that string and translate again. Generally that will work. If you send me the file and there are problems like this, I will fix them.

I am working on fixing the "Save to file..." now!

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-a with a fix for the "Save to file..." in the translation application. I also try to standardize the JSON format of translate.json so it can be used in GitHub (Items are sorted, etc).

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-b and a updated [Resource Translator tool](info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip). Now, they all save translate.json exactly the same way, with the same order and spacing. So, saving a translate.json and doing a pull request on GitHub should work perfectly.

**Comment by vitko-bg** [comment]
link to https://github.com/Ylianst/MeshCentral/issues/info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip does not work .....

**Comment by petervanv** [comment]
http://info.meshcentral.com/downloads/MeshCentral2/ResourceTranslator.zip this one works

**Comment by Ylianst** [comment]
Arg! I fixed my link above. @vitko-bg apologies for the delay, I just found your emails and working on it now! I would have a new version with your Russian beta translation very soon.

**Comment by Ylianst** [comment]
@vitko-bg Just published MeshCentral v0.4.7-c with your Russian beta translation! I just had to do a few minor fixes to make it work. Let me know if you see any issues.

![MC2-Russian](https://user-images.githubusercontent.com/1319013/72006422-76a4ef00-3204-11ea-8e35-71e9b2beb022.png)

**Comment by vitko-bg** [comment]
Looks like there are some untranslated strings - which are translated in the file, also some of worlds will need to be adjusted/changed. However, will make a report with issues I found and will post it here.
Which translate.json i have to get, to start improving translation:
/node_modules/meshcentral/translate/translate.json
OR
/meshcentral-data/translate.json ?????

**Comment by vitko-bg** [comment]
@Ylianst please let me know if this type of report is suitable for you?
Also - would you like me to upload file here, or would you like me send via e-mail?
Updated RU version:
[translate_ru_20200109.zip](https://github.com/Ylianst/MeshCentral/files/4040759/translate_ru_20200109.zip)
Quick report:
[For_Yulian_20200109.docx](https://github.com/Ylianst/MeshCentral/files/4040767/For_Yulian_20200109.docx)

**Comment by Ylianst** [comment]
Taking a look at this now.

Note that /node_modules/meshcentral/translate/translate.json is the one I publish, so it should be your starting point when you get a MeshCentral update. The version in "meshcentral-data" is your version. When you enter the web translation app, it will load your version if present. So, after I publish a new version, you can remove the one in "meshcentral-data" and it will load the published one.

**Comment by vitko-bg** [comment]
@Ylianst - thanks for explanation. Do not rush with the file I uploaded - looks like I corrected a wrong file. Will make sure which one I am working on.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.4.7-d with your latest translations. You should update to this new version and start with /node_modules/meshcentral/translate/translate.json because it will be the latest one. I have not starting working on the report yet, but will work on that.

**Comment by vitko-bg** [comment]
On mobile version lots of string are still on english....
![untranslated](https://user-images.githubusercontent.com/59362521/73062238-d56c9880-3e93-11ea-9913-04bed951759e.jpg)
Where I can find those strings to translate and update accordingly a russian version?
