### ISSUE TITLE
Mullti-Tab Browser improvement suggestions

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#789]
Using Google Chrome

I open multiple tabs to my mesh, managing multiple simultaneous desktops, but swapping tabs

Some notes

- a filter on one tab is also used on all others
- Notifications need to be cleared for each tab
- If mesh server connection drops out for a micro-second (normal behaviour) the tab doesn't go back to the desktop it was managing, it goes back to main 'My Devices page', albeit with filter applied. The effect of this is if I start a long process, then walk away, when I come back I can't tell which machines I was working on.

**Comment by MailYouLater** [comment]
It would be nice to be able to middle click to open things in a new tab too.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.6-z. In this version, closing a notification in one tab or browser will close the notification on all sessions from the same user. This works even if the other browser is on a different computer.

**Comment by si458** [comment]
as @Ylianst said above and you can also hold the shift key while clikcing tabs and it will open that tab in a new window or tab for you
