### ISSUE TITLE
no desktop tab in windows 2008

### ISSUE THREAD

**Issue by shirst** [Ylianst/MeshCentral#79]
I love the server. I am having some issues with tabs showing on a windows 2008 machine. I was also needing winxp but I read that that's not going to happen. Is there a list of working OSs some where that I'm missing? I have machines ranging from DOS all the way up to current that i work on remotely. Currently I am just starting to test the server and I plan to report as things come up. Thanks in advance, Steve

**Comment by Ylianst** [comment]
If you are running the latest server and are administrator on the server: go on that device's web page, select the "console" tab, click the "Agent Action" button, select "Upload recovery core" and ok. The files and terminal should show up, but let me know if it does. You can also try to update the default core again and see if the desktop show up.

Send back what you did and what you see. I have not tested on a Windows 2008 server, but we maybe I will next week. - Thanks.

**Comment by shirst** [comment]
I just installed the server 3 days ago so I think it’s the latest one and I am admin of it. I tried loading both cores and it didn’t change anything.

**Comment by Ylianst** [comment]
Same comment I will make here as the other issue thread. Bryan tested Windows 2008 server and the agent is not stable on it. We can't install Visual Studio dev tools on that OS, so it's going to be difficult to fix. We may end up not supporting this OS and add some message to this effect.

**Comment by Ylianst** [comment]
So, we are not going to be supporting Windows Server 2008. I try Windows Server 2012r2 is the oldest we support. Will close this issue, however feedback appreciated.
