### ISSUE TITLE
Doubt - meshcentral agent update health

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#792]
Guys, good afternoon!

Would you like to ask a question, how is the meshcentral agent update process done? When I run npm install meshcentral does the server update through the machines already communicating with it, all agents? Or do I need to update agents on the stations I use manually?

I don't know if you remember, I opened two topics here on git, one reporting the black screen that appears at random times on remote desktop connections and the other is meshcentral clients going offline (I identified that is the windows service which is stopping), and both cases may be related to a possible lack of agent upgrades (well, this is just a suspicion, not sure if it would be related or not).

What do you think?

**Comment by geanferrani123** [comment]
Can you help me?

**Comment by Ylianst** [comment]
When you update the MeshCentral server, all gents automatically get updated when they next connect to the server. No need to re-install the agent.

You can take a look to see if the agent is up to date by comparing the files (for 64 bit):

```
Client: C:\Program Files\Mesh Agent\meshagent.exe
Server: /node_modules/meshcentral/agents/MeshService64-signed.exe
```

These two files should be the same. You can right click the executable, go in Properties and look at the digital signature date. They should match. hope that helps.
