### ISSUE TITLE
7 Day Power State missing with linux agents

### ISSUE THREAD

**Issue by pczolee** [Ylianst/MeshCentral#794]
Hello.

I don't know how far (after which update), but now there is no 7 Day Power State usage on the device tab which running Linux. Which have windows those have no problem.

![windows](https://user-images.githubusercontent.com/27812638/71883147-147db880-3136-11ea-9ecd-fa415d996943.jpg)
![linux](https://user-images.githubusercontent.com/27812638/71883148-147db880-3136-11ea-97bd-3c7831f32a48.jpg)

**Comment by vitko-bg** [comment]
Do not want to open another ticket - is there a way 7 Day power state to look like a time bar:
 00:00 | 01:00 |.........| 15:00 | 16:00 | ............... | 23:00 | 24:00 ?

**Comment by Ylianst** [comment]
Interesting, I have not seen this. Can you confirm your running your own server or using meshcentral.com? What browser are you using? Also, can you open the browser console and tell me if you see any errors? In FireFox you open it using (Shift-Ctrl-K), in Chrome (Ctrl-Shift-I).

You should see an extra window like below, send any errors you see. Thanks.

![x](https://user-images.githubusercontent.com/1319013/71929821-4ea78400-314f-11ea-8e38-985e8e726dda.png)

**Comment by MailYouLater** [comment]
Note: If you use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> to open the "DevTools" interface, you may be taken to the "Elements" tab, and have to switch to the "Console" tab to see if there are any messages that would help Ylianst.  If you instead use the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> keyboard shortcut, you go straight to the "Console" tab of the Chrome's "DevTools".  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> also works in Firefox, though it opens a slightly different interface which only shows the browser's console, not any of the other tabs that appear in Firefox's "Developer Tools".

**Comment by pczolee** [comment]
Hello.

I'm using firefox, but the chrome works same, so there is no difference.

Here is what I see in the chrome console:

(index):3119 Error loading plugin handler (TypeError: Cannot read property '_id' of undefined)

common-0.0.1.js:18 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at QH (common-0.0.1.js:18)
    at Object.obj.eventlog.onRemoteEventLogStateChange [as onStateChanged] ((index):1201)
    at Object.CreateAgentRedirect.obj.xxStateChange (agent-redir-ws-0.1.1.js:263)
    at Object.CreateAgentRedirect.obj.Stop (agent-redir-ws-0.1.1.js:285)
    at Object.obj.eventlog.onDeviceRefreshEnd ((index):1224)
    at Object.obj.callHook ((index):1588)
    at gotoDevice ((index):5349)
    at HTMLDivElement.onclick ((index):1)
QH @ common-0.0.1.js:18
obj.eventlog.onRemoteEventLogStateChange @ (index):1201
CreateAgentRedirect.obj.xxStateChange @ agent-redir-ws-0.1.1.js:263
CreateAgentRedirect.obj.Stop @ agent-redir-ws-0.1.1.js:285
obj.eventlog.onDeviceRefreshEnd @ (index):1224
obj.callHook @ (index):1588
gotoDevice @ (index):5349
onclick @ (index):1

common-0.0.1.js:18 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at QH (common-0.0.1.js:18)
    at Object.obj.eventlog.onDeviceRefreshEnd ((index):1225)
    at Object.obj.callHook ((index):1588)
    at gotoDevice ((index):5349)
    at HTMLDivElement.onclick ((index):1)
QH @ common-0.0.1.js:18
obj.eventlog.onDeviceRefreshEnd @ (index):1225
obj.callHook @ (index):1588
gotoDevice @ (index):5349
onclick @ (index):1
3(index):3040 PluginHandler could not event message:  TypeError: Cannot read property 'nodes' of null
    at Object.parent.pluginHandler.scripttask.loadHistory (VM58 pluginadmin.ashx:421)
    at Object.obj.scripttask.historyData ((index):1581)
    at Object.onMessage ((index):3040)
    at WebSocket.MeshServerCreateControl.obj.xxOnMessage (meshcentral.js:51)

**Comment by pczolee** [comment]
I updated to the latest 0.4.7-b, and now it look ok!

**Comment by Ylianst** [comment]
Weird, I did not do anything. Thanks for posting the console error above, that is super useful. A quick look at it shows that "onDeviceRefreshEnd" is being called, that is only called when you have plug-ins and it looks like (at first glance) a plug-in caused the error.

**Comment by Ylianst** [comment]
I think this is a bug for @ryanblenis :)

**Comment by ryanblenis** [comment]
Looking into this!

**Comment by pczolee** [comment]
Well, I use some plugins: Dev Tools, Event log, Routeplus, ScriptTask
I don't know what caused the problem, but now (after the update) it looks good.

**Comment by ryanblenis** [comment]
Hi @pczolee,

Thanks. RoutePlus and EventLog were just updated to clean up some console messages as seen in your above post.

It shouldn't have affected the power timeline, but I tried MeshCentral several versions back and couldn't replicate it- so I'm glad it's fixed now! Thank you.

**Comment by pczolee** [comment]
Hi @ryanblenis.

Thank you. Everything is fine now! The report can be closed!
