### ISSUE TITLE
Missing detail information on Raspberry Pi

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#795]
At some computer details pages it is filled with some info.
my virtual instance ubuntu give's some info, but from my raspberry pi's no details available.
is this normal behavior or is it broken ?

the other devices do provide info but very briefly, it is possible to show more here?

**Comment by Ylianst** [comment]
This is normal, we don't yet have code to get device information from the Raspberry Pi. The details tab will show "No information for this device." for now.

**Comment by petervanv** [comment]
clear !

**Comment by MailYouLater** [comment]
While this is not a bug, I feel it should be left open as a feature request to add the ability to collect and display details for Raspberry Pi devices.

**Comment by Ylianst** [comment]
Agreed. It would be nice to get platform information on Raspberry Pi. I do feel a bit flooded with requests these days, but the translations to other languages from the community is super motivating.

**Comment by petervanv** [comment]
@Ylianst @krayon007 any progress on this issue ?

**Comment by si458** [comment]
@petervanv what details do you require? as it already shows the network interfaces

**Comment by si458** [comment]
ive added a PR to the meshagent as this had to be done there sadly https://github.com/Ylianst/MeshAgent/pull/206
its not the prettiest but it works and adds a few bits of info to begin with

**Comment by si458** [comment]
new PR should fix this for you
![image](https://github.com/Ylianst/MeshCentral/assets/765314/197f15dd-c535-48e7-8b70-a0f8252e0c46)
