### ISSUE TITLE
Problem with Mac Agent working

### ISSUE THREAD

**Issue by motapek** [Ylianst/MeshCentral#797]
Hi.
I have problem with Agent working on Mac (Catalina)
Install process was without problem but computer is not visible on server.
Computers with windows in this same network works properly.
I didn't found any information about it on documentation and Internet.

Any idea ?
Any special security settings ?

I'm not a Mac specialist.:)

**Comment by Ylianst** [comment]
This is a question for Bryan. I am not a MacOS specialist myself.

**Comment by MailYouLater** [comment]
I would recommend that you find the `.msh` file (sorry, I'm not sure where it is on a Mac) and edit it in a text editor, adding a line that says `controlChannelDebug=1`.  I believe this will create a log file the next time you launch the mesh agent, and it'll give you more details which may prove helpful in debugging.

**Comment by ryanblenis** [comment]
The default path on OSX is /usr/local/mesh_services/meshagent, FYI

**Comment by galxy25** [comment]
Having same issue(connecting from local MeshCentral server to the machine it is running on),
fresh MeshCentral install on macOS Catalina
MeshCentral v0.4.7-o, LAN mode.
turned on logging and log messages are 
```
[2020-01-23 10:37:19 AM] Attempting to connect to Server...
[2020-01-23 10:37:19 AM] Attempting to connect to Server...
[2020-01-23 10:37:20 AM] Attempting to connect to Server...
[2020-01-23 10:37:21 AM] Attempting to connect to Server...
[2020-01-23 10:37:23 AM] Attempting to connect to Server...
[2020-01-23 10:37:25 AM] Attempting to connect to Server...
[2020-01-23 10:37:27 AM] Attempting to connect to Server...
[2020-01-23 10:37:30 AM] Attempting to connect to Server...
[2020-01-23 10:37:33 AM] Attempting to connect to Server...
```
Reading through the update log I can see that macOS support was added for Mojave, wondering if the more stringent security settings in Catalina are the issue here; has anyone else successfully connected via agent to mesh central with a Catalina device?

**Comment by krayon007** [comment]
I finally got my macOS Catalina Dev System fixed, so I can give macOS some love again...

**Comment by galxy25** [comment]
Awesome to hear, let me know if I can provide additional information or you need another Catalina device to run development code on to debug things

**Comment by krayon007** [comment]
I got my Catalina machine to connect fine, but my clients are configured in WAN mode... LAN mode uses IP Multicast, so I have to check to make sure LAN mode works correctly on my macOS machines.

**Comment by si458** [comment]
closing as stale,
please download the latest version 1.1.21 and use node 18 or above,
if issue perists, please report back
