### ISSUE TITLE
Problem with MC Translator

### ISSUE THREAD

**Issue by Floche87** [Ylianst/MeshCentral#798]
Hi,
I want to enhance french translation with MC Translator.
My modifications appear in files (./meshcentral-data/translation.json and ./node_modules/meshcentral/views/translations) but not in web pages of MC.

MC runs on debian (buster arm64) with debian packages for npm. 
I don't find anything in logfiles but I have a warning about canvas package when i update MC.

Any ideas ?
Thx

**Comment by MailYouLater** [comment]
First: If you're using MeshCentral in a production environment, I would recommend setting up a separate server for creating/editing/testing your translations in, as certain small mistakes in the translation file can cause the whole user interface to stop showing, which is easily fixable by reinstalling via npm (go to the folder where the `node_modules` folder is and run `npm install meshcentral`), and really only a minor annoyance on a test server, but is very bad on a production server, as it causes downtime.
Second: The way translation currently works in MeshCentral, after writing your translations to the `translate.json` file in `node_modules/meshcentral/translate`, you need to go to the `node_modules\meshcentral\translate` folder and run `node translate.js translateall` for it to actually generate the new `.handlebars` files that the server will actually use.
Third: If translating a new language that doesn't (yet) appear in the language options under your user account settings, you'll need to restart the MeshCentral server before it will see the new translation file(s).

**Comment by Ylianst** [comment]
By the way, I am a french speaker myself from Montreal, Quebec. If you have any improved translate.js file, you can also [send them to me](https://www.meshcommander.com/contact-information). I will integrate them right away.

@MailYouLater is correct. Once you make changes to the translate.json, you need to run the "node translatejs translateall" to re-translate all of the web pages using the new translate.json strings.

**Comment by Floche87** [comment]
@MailYouLater Thank you for the command line.
I used it and didn't have errors.
But i don't see my modifications in MC. I rebooted the machine but no effect.

@Ylianst I'll send you my translate.json file but before i would like see and validate in MC.

**Comment by Ylianst** [comment]
@Floche87 Some hints on this. If you go in "node_modules/meshcentral/translate", you will see a translate.json and translate.js files there. Make sure your improved version of translate.json is here. Then, run:

`node translate.js translateall`

Once done, you should see updated web pages in "node_modules/meshcentral/views/translations". In fact, if you remove all files from the "node_modules/meshcentral/views/translations" folder and run "node translate.js translateall" again, all files should show up again, all re-translated.

Once that is done, login to MeshCentral and you can add "?lang=fr" to the URL to see the French site, or select French in your browser default language, or select it in the internalization settings of "My Account". It should be pretty simple.

If you use the web translator page, it will save your "translate.json" in "meshcentral-data", so you will need to copy it over to "node_modules/meshcentral/views/translations".

Hope that helps,
Ylian

**Comment by Floche87** [comment]
@ylian Just finished to follow your hints and make new tests :
1. MC Translator only : UI is ok but no effect
2. MC Translator to traduct and command line for processing : UI is ko : i have a blank page after login

but both have same effect in files "node_modules/meshcentral/views/translations" : i can find my modifications.

Using "?lang=fr" don't change anything.
Floche
