### ISSUE TITLE
Use port 623 for ASF-RMCP pings although TLS is enabled

### ISSUE THREAD

**Issue by xcabur1** [Ylianst/MeshCentral#799]
During the implementation of our network firewall I noted that MeshCommander use port 623 for ASF-RMCP pings although TLS is enabled. Based on the Intel implementation guide I think MeshCommander should use port 664 for secure ASF-RMCP pings.

https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Fmanageabilityports.htm

**Comment by jsastriawan** [comment]
RMCP ping purpose in Meshcommander is for testing if the device is directly accessible or not. I think this is a great idea if all your devices are TLS enabled and all non TLS services are disabled.

**Comment by Ylianst** [comment]
As @jsastriawan noted, RMCP is a UDP packet that is sent just to see if Intel AMT is present or not. It will cause the green or red color to show up next to the device. RMCP is not required and you can go in the "Help" menu and disable "Scan for presence" to remove this feature. MeshCommander uses port 16992 to 16995 to connect to Intel AMT and perform management operations. Hope that helps.

**Comment by xcabur1** [comment]
I know that RMCP is only used for red/green status requests. From an engineer's point of view, the expected behavior, with TLS enabled, was that all connections (including the status request) are encrypted. Because we only allow encrypted connections, I only allowed the secure ports on the firewall, based on the Intel documentation (HTTPS 16993, KVM 16995, RMCP 664). Afterwards the firewall reported blocked connections for RMCP 623. This was unexpected because 664 was allowed but obviously not used.

**Comment by Ylianst** [comment]
Well, I guess I would try to perform a presence detection by connecting to all the computers using TLS, but that would cause a bunch of traffic. In addition, there is generally an outbound limit on the number of TCP connections that can be outstanding without a connection and/or missed TCP connections/minute to prevent port scanning on TCP.
