### ISSUE TITLE
Make one-click RDP work for Linux clients

### ISSUE THREAD

**Issue by n1trux** [Ylianst/MeshCentral#8]
This is a feature request.

I'd really like to be able to use a one-click RDP session from Linux to manage remote devices.

One may use https://github.com/rdesktop/rdesktop for this and pass the needed credentials via CLI options, but that could be unsafe.

I opened rdesktop/rdesktop#254 asking to implement the `rdp://` URI scheme.

**Comment by jsastriawan** [comment]
Hi,

I think there an RDP if there is Windows. The approach is basically a small application needs run through Click To Run mechanism (may be only reliably supported by Internet Explorer or Edge). This application is then creating a local TCP server to accept RDP client incoming connection. Upon receiving incoming connection, this small application will then initiate websocket tunnel relay with the agent via meshcentral 2. Once the connection  is established, the RDP traffic is then shuffled back and forth through this tunnel.

You can achieve similar behavior using MeshCmd
See: https://www.youtube.com/watch?v=S38mg_BPe-M

Or you can use a tool I wrote based on what Ylian did on MeshCmd but using node-webkit.
https://github.com/jsastriawan/mc2router
 
Let me know if the tool fits your requirements and obviously you could help to enhance this tool to tunnel multiple application traffic is you want.

**Comment by n1trux** [comment]
There's Firefox/Chrome support for the ClickOnce mechanism mentioned in the MeshCentral2 manual.

For Chrome there seems to be [an actively maintained addon](https://chrome.google.com/webstore/detail/clickonce-for-google-chro/kekahkplibinaibelipdcikofmedafmb) which I didn't try. Before the new WebExtensions API there [seemed to be an addon](https://addons.mozilla.org/en-US/firefox/addon/fxclickonce/) to add ClickOnce functionality to Firefox.

Unfortunately this is a Windows-only option so ClickOnce indeed doesn't work with Linux.

Thank you for the link to your tool, it looks great! Sadly it still uses nodejs and I try to keep that off my workstations. Though a "native" tool or at least without much dependencies would be better IMHO, I'm evaluating it within the next few days.

**Comment by Ylianst** [comment]
Hi. Just a note on NodeJS, MeshCentral only requires you install NodeJS on the server. For all the clients, the MeshAgent is written in native C code. The single MeshAgent.exe runs without any requirements.

For the rest, yes, ClickOnce is only Windows. I am working on MeshCmd for Linux that can do port mapping thru the MeshCentral server.

Hope it helps,
Ylian
________________________________

**Comment by matt-primrose** [comment]
With MeshCentral 2 v0.3.0-t port mapping local TCP ports to remote computer ports running the agent is now supported.  So mapping port 3389 would allow a fast RDP remote desktop session, for example.  Here is a video of Ylian showing this new feature: [https://www.youtube.com/watch?v=0bQplPSWB4k](https://www.youtube.com/watch?v=0bQplPSWB4k)

**Comment by Ylianst** [comment]
I will close this issue since MeshCMD supports port maps on Linux. However, feel free to open another issue if there are problems or feature requests around this.
