### ISSUE TITLE
MeshAgent does not connect to Mesh

### ISSUE THREAD

**Issue by rhopesdi** [Ylianst/MeshCentral#80]
Hi there,

I installed MeshCentral2 and MeshAgent on two windows virtual PCs.   The meshagent, once it installs, never shows up in the list of devices in my device group.   I can't find any troubleshooting steps for meshagent.   What next steps should I take?

**Comment by rhopesdi** [comment]
Many thanks!

**Comment by mhdrdin78** [comment]
Hi ,

I am also having same problem. Run from command line it just hang. not connected.
![image](https://user-images.githubusercontent.com/47171634/51965340-342b4c00-24a4-11e9-9c7d-9334f705d2e9.png)

this agent on Server 2008.

other server in same network with 2008 r2 and above working.  Does meshagent not support server 2008?

**Comment by Ylianst** [comment]
Bryan tested Windows Server 2008 and indeed, the agent is not working right. It's going to be difficult to fix as none of the latest Visual Studio development tools want to install on that OS. I am thinking we may end up displaying an error that this OS is not supported unless we find some crazy way to make it work.

**Comment by Ylianst** [comment]
I will close this issue since we are not going to support older none supported Windows versions.

**Comment by Ylianst** [comment]
I will close this issue since we are not going to support older none supported Windows versions.
