### ISSUE TITLE
Besides 'execFile', is 'spawn', 'fork', and 'exec' also supported by the agent javascript runtime?

### ISSUE THREAD

**Issue by steuck13** [Ylianst/MeshCentral#801]
Greetings

I was tinkering with the agent default core file and noticed a few [calls](https://github.com/Ylianst/MeshCentral/blob/efd936315d15ef85165156d28e2f69c201fee5f5/agents/meshcore.min.js#L1173) to execFile and I wondered if other calls to create a child process were also supported.

Ty

**Comment by Ylianst** [comment]
Right now, only "execFile" is implemented. Note that we use [DukTape](https://duktape.org/) on the agent and implemented all our own system calls, so the calls don't match what is offered in a browser or NodeJS. Bryan just makes it look about the same as NodeJS when possible. If you want sample code that can run on the MeshAgent, look in the [MeshAgent GitHub modules folder](https://github.com/Ylianst/MeshAgent/tree/master/modules).

**Comment by steuck13** [comment]
Thank you.
