### ISSUE TITLE
Console Linux ps entry names truncated

### ISSUE THREAD

**Issue by nlyaple** [Ylianst/MeshCentral#803]
The entry name is not long enough to distinguish two processes with similar names, I.e.:

482, /opt/xxxxxxxxx/s, root
483, /opt/xxxxxxxxx/s, root

The operation is using the Console tab in MeshCentral and type the 'ps' command in the agent command window.

**Comment by Ylianst** [comment]
Is this like the screen below? What do you want us to do? I do not understand the request.

![x](https://user-images.githubusercontent.com/1319013/72022560-a1536f80-3225-11ea-9f13-2c10871f22d2.png)

**Comment by nlyaple** [comment]
Hi,
   
  
  
        Sorry, Yes it is the screen below. The process name looks like it is set to a maximum of 15 characters.  It would be useful to expand it to at least 30 or so.   
   
  
  
   Thanks,
   
  
  
   Nelson
   
  
  
   
    On January 8, 2020 2:46 PM Ylian Saint-Hilaire <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Is this like the screen below? What do you want us to do? I do not understand the request.

**Comment by Ylianst** [comment]
Ok, I see the problem "processManager.getProcesses()" only returns a part of the name. I will need Bryan to fix this.

**Comment by nlyaple** [comment]
Hi,
   
  
  
       Can I ask a question on a different subject?  We have a case where the Console commands (ps, type, ls, etc.) work but we cannot use the Terminal or Files at this site.  Any ideas why?
   
  
  
   Thanks,
   
  
  
   Nelson
   
  
  
   
    On January 8, 2020 4:13 PM Ylian Saint-Hilaire <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Ok, I see the problem "processManager.getProcesses()" only returns a part of the name. I will need Bryan to fix this.

**Comment by Ylianst** [comment]
Does the problem of Terminal/Files not working look like #806? Do you see "Error{}" in the console? - Thanks.

**Comment by nlyaple** [comment]
Hi,
   
  
  
       It looks similar but in our case when we connect via an LTE modem, everything works normally. When we connect via the clients network only the console works. I haven't seen the Error {} message in the console. This is a new site install where we access the internet through the clients IT supported network.  Do you think they could be blocking websocket tunnel?
   
  
  
   Nelson
   
  
  
   
    On January 9, 2020 1:16 PM Ylian Saint-Hilaire <notifications@github.com> wrote:
   
   
    
   
   
    
   
   Does the problem of Terminal/Files not working look like #806? Do you see "Error{}" in the console? - Thanks.

**Comment by krayon007** [comment]
I fixed the ps thing, so it works correctly now... I also fixed it so usernames will get populated on all platforms now, instead of just linux. It will be in the next agent update.

**Comment by nlyaple** [comment]
Hi,
   
  
  
        Some more info on the issue we are seeing.  It appears that we have a bad DNS entry in the configuration.  The Console can connect but that's it.  Is there any troubleshooting steps you can recommend to try?
   
  
  
   Thanks,
   
  
  
   Nelson
   
  
  
   
    On January 9, 2020 1:29 PM nels@nelsony.com nels@nelsony.com <nels@nelsony.com> wrote:
   
   
    
   
   
    
   
   
    Hi, 
    
   
   
        It looks similar but in our case when we connect via an LTE modem, everything works normally. When we connect via the clients network only the console works. I haven't seen the Error {} message in the console. This is a new site install where we access the internet through the clients IT supported network.  Do you think they could be blocking websocket tunnel? 
    
   
   
    Nelson 
    
   
   
    
     On January 9, 2020 1:16 PM Ylian Saint-Hilaire <notifications@github.com> wrote:
    
    
     
    
    
     
    
    Does the problem of Terminal/Files not working look like #806? Do you see "Error{}" in the console? - Thanks.

**Comment by Ylianst** [comment]
For the bad DNS making the console work but Desktop/Terminal/Files not work, it's problem #806 and Bryan has a fix for this that will be included with the release of the next MeshAgent. It's important that new agents are tested well and I am traveling this coming week, so it will be released after I am back.

**Comment by nlyaple** [comment]
Good morning,
   
  
  
        Before I logged this as an issue in GitHub, I wanted to know if you have seen this already.  The device is a Linux box running Peppermint 6 32bit.
   
  
  
   
  
  
   
    uncaughtException1: Error: => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: cannot write property [Symbol hidden '?_Agent_SocketJustCreated'] of 'DNS[ec2-34-210-241-218.us-west-2...' in method 'handleServerCommand()'
   
   
    uncaughtException1: Error: => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: cannot write property [Symbol hidden '?_Agent_SocketJustCreated'] of 'DNS[ec2-34-210-241-218.us-west-2...' in method 'handleServerCommand()'
   
   
    
   
   
    I cannot connect to the device via Terminal or Files tab.  I can only access it via the Console tab.  Please let me know if you need anymore details.
    
   
   
    Thanks,
    
   
   
    Nelson

**Comment by si458** [comment]
indeed `ps` if fixed in newer version 2023
