### ISSUE TITLE
Tools imporvement suggestion

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#804]
'Tools' is really excellent. I really love how I can access that without connecting to the desktop first.

Some suggestions for improvement.
When screen view is set to 'fit to display' mode, and the tools section is opened, can the fit to screen be moved slightly to the left, so that  the display and the tools can both be accessed at once in full view.

Also, if we can get the 'user' for each of the  processes, that would help me work out which process to trash if needed.

The ability to start, stop or restart services from tools would also be awesome.

**Comment by Ylianst** [comment]
Can you send a screenshot of "Fit to display" and this suggestion. Seems easy to do, but I don't understand the request.

Showing users for processes is a good idea, I think there was a problem with the agent having a hard time getting the user for each process on Windows or Linux, I would have to check.

**Comment by OutbackMatt** [comment]
This is normal view

![image](https://user-images.githubusercontent.com/7231493/72024942-79feb000-32c2-11ea-8151-1b4d05edfae7.png)


When I show the tools box, a portion of the screen on the right hand side is covered over
![image](https://user-images.githubusercontent.com/7231493/72024988-9dc1f600-32c2-11ea-8d02-b2094c678ab7.png)

For some non-wide screen monitors I can see the whole screen
![image](https://user-images.githubusercontent.com/7231493/72025079-c21dd280-32c2-11ea-8ca1-4c9678499bc1.png)

I'd like to see full screen + tools, where both will fit please

**Comment by Ylianst** [comment]
Oh!! I see. Of course, that makes sense.

**Comment by si458** [comment]
incoming, you can resize the tools bar 👍 
![Untitled video-resize](https://github.com/Ylianst/MeshCentral/assets/765314/b8f51d64-0719-4eba-8f2b-bc6eefc87370)
