### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by yavuzyz** [Ylianst/MeshCentral#807]
![image](https://user-images.githubusercontent.com/47879824/72147396-17331480-33a7-11ea-8476-145a2fc061b7.png

Hi .
Https://mescentral.com consolda Terminal operation does not work.

**Comment by krayon007** [comment]
What OS is your agent running? What server version are you using?

**Comment by Ylianst** [comment]
This is really low quality issue.

What operating system is the remote system? And version?
What browser are you using? And version?
Does the “Files” work but “Terminal” does now?

I am going to close this issue, please open a new one and provide more information. Thanks.

**Comment by yavuzyz** [comment]
First of all, thank you for your interest.
Linux Fedora 15.
Mesh Agent Version: 2019-11-26 20: 17: 01.000-03: 00

Note: it worked until two days ago.

Yavuz.


________________________________
Gönderen: Bryan Roe <notifications@github.com>
Gönderildi: 10 Ocak 2020 Cuma 15:34
Kime: Ylianst/MeshCentral <MeshCentral@noreply.github.com>
Bilgi: yavuzyz <yavuzyz@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [Ylianst/MeshCentral] Terminal (#807)


What OS is your agent running? What server version are you using?
