### ISSUE TITLE
On plugin tab missed back button

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#809]
![Снимок экрана от 2020-01-10 17-28-43](https://user-images.githubusercontent.com/16576224/72153571-2e3a2c80-33d0-11ea-935b-884ba93869f6.png)

**Comment by ryanblenis** [comment]
Hi @Ilia1,

The plugins tab on a device does not generally have a "back" button (unless it is part of the plugins own navigation). You can simply just click on another tab for the device to go elsewhere.

The back button is generally seen on the My Server -> Plugins -> <Plugin> Pages as a way to get back to the installed plugin list.

**Comment by ryanblenis** [comment]
Thanks @Ylianst, but where would the clicking the back button actually go when you're within the device -> Plugins page?

**Comment by MailYouLater** [comment]
@ryanblenis: I think @Ilia1 & @Ylianst mean the 'back' button which goes back to the device list.
![image](https://user-images.githubusercontent.com/1279475/72186140-624e2700-33a9-11ea-8b08-6ff94f7ef431.png)

On a separate note, but also about the UI of the Device > Plugins tab, I feel like the look and position of the tabs which represent different plugins (circled below) should be merged with and use the same visual style as the rest of the tabs in the MeshCentral interface (location noted by partial outline below other tabs).
![image](https://user-images.githubusercontent.com/1279475/72186428-194aa280-33aa-11ea-864b-f3130137094f.png)

**Comment by ryanblenis** [comment]
Huh, would you look at that... I don't think I ever noticed there was a back button on all those pages. I just instinctively clicked the "My Devices" header to get back when I wanted to!

@MailYouLater - you're excellent at explaining things!
As for the Plugin tabs visual styles: Originally I was going to, but the inner-workings of the template accommodated up to 2 rows of navigation and (being early in my contributions to the project) I had no idea at that time how receptive @Ylianst is to pull requests, so I tried not to make too many changes to the default template. 

@Ylianst - open to your thoughts on this change, but also want to keep in mind that (at some point) there could be more plugins than the spacing allows and a we'll need to accommodate for a scrolling list (or perhaps even more simple to implement and expand, a select box with the available plugins list).

@Ylianst please feel free to add the back button to that page

**Comment by Ylianst** [comment]
I added the back button to the plugin tab, it will be in the next published release (MeshCentral v0.4.7-i when it comes out). It was an easy addition.

As for anything else in the plug-in tab, I am a bit swamped with requests and rather delegate to @ryanblenis ownership of the features and presentation within the tab. So far, you it's been really excellent and the plugin are really useful.

**Comment by ryanblenis** [comment]
Thanks! I have no problem with that. @MailYouLater, while I would like the look of a third row of installed plugins, there will come a time that the plugin tabs exceed the space the navigation can provide. Do you think a select dropdown would be an effective compromise? I'm open to ideas here and you seem great with usability and user experience issues. Thanks!

**Comment by Ylianst** [comment]
FYI. I do think the device tab bar (General, Desktop, Terminal, Files...) is at capacity, especially in some other non-English languages. So, I agree that a different UI trick will need to be used.

**Comment by Ilia1** [comment]
Thanks for fix!

**Comment by MailYouLater** [comment]
I'll open a separate issue regarding the UI inconsistency I brought up.
