### ISSUE TITLE
Add optional 2FA auth

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#81]
It would be cool if you could add optional TOTP-based 2FA auth to MeshCentral.

**Comment by Ylianst** [comment]
I think added this 10 days ago, see [this blog post about it](https://meshcentral2.blogspot.com/2019/01/meshcentral2-two-step-authentication.html). Basically, you can use Google Authenticator or a similar app to login. However, if you had a different idea, please let me know.

**Comment by whalehub** [comment]
@Ylianst You are correct, this is exactly what I was looking for. Thank you!
