### ISSUE TITLE
NL - language update

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#810]
Update dutch language (typo's and corrections)

[NL_01-11-2020-translate.zip](https://github.com/Ylianst/MeshCentral/files/4049486/NL_01-11-2020-translate.zip)

**Comment by Ylianst** [comment]
Thanks. I am traveling this week, but will go back to work tomorrow to make a release with this new translations. Thank you so much!

**Comment by petervanv** [comment]
i saw the update, happy traveling

**Comment by Ylianst** [comment]
Wow! You are super fast. I was just looking in the issues list to respond to this and could not find it until I looked in the "Closed" issues. Thank you so much for updating the translation. Much appreciated.
