### ISSUE TITLE
Onmouseover  event

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#811]
In server status, the onmouse over event is not completely visible, possibility to auto enlarge area so all is visible?

![Screenshot_6](https://user-images.githubusercontent.com/58996467/72207064-41fb9680-3495-11ea-9c78-127ad7f56ea2.jpg)

**Comment by Ylianst** [comment]
Your right, it does not look good. I am traveling next week and this is low priority, but a valid issue.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-j where I removed the chart.js hover. I can't make the hover work within the small canvas, so this hopefully solves this.

**Comment by petervanv** [comment]
simple but fine solution !
