### ISSUE TITLE
Update using non standard version numbering

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#813]
When I manually perform an update  to meshserver, if the minor version goes up one digit, ie from 0.4.5-a to 0.4.6-a then I need to manually install with the version number

sudo npm install meshcentral@0.4.7-h

This is on Ubuntu 18.04 and may be because of the permissions that I've set
If just updating to a new 'letter', ie from 0.4.7-a to 0.4.7-h then it just works with the standard install

sudo npm install meshcentral

**Comment by OutbackMatt** [comment]
Also, when I update I ALWAYS get these warnings - without operational impact

npm WARN meshcentral No description
npm WARN meshcentral No repository field.
npm WARN meshcentral No license field.

**Comment by Ylianst** [comment]
Oh... this is interesting. I may need to change my versions, I think @MailYouLater had mentioned before that using 1.2.3-a versions is not good. I need to look into this. I have also never figured out how to remove the 3 warnings... I have tried in the past. Any help from the community on this would be welcome. I have put in these fields (I think).

**Comment by asasin114** [comment]
Not 100% sure on the description and license fields but it looks like the package.json file in node_modules\meshcentral has a misspelled url. See example below:
Current:
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Ylianst/MeshCentral.git"
  },

Fix:
"repository": {
  "type": "git",
  "url": "git://github.com/Ylianst/MeshCentral.git"
}

Here's where I found the fix: https://exceptionshub.com/npm-warn-package-json-no-repository-field.html

**Comment by OutbackMatt** [comment]
I think that the '.git' at the end of the URL is also not required

**Comment by MailYouLater** [comment]
> Also, when I update I ALWAYS get these warnings - without operational impact
> 
> npm WARN meshcentral No description
> npm WARN meshcentral No repository field.
> npm WARN meshcentral No license field.

This is because we're installing meshcentral as if it were a dependency to an npm package that we're building, not downloading meshcentral's repo to where npm will treat it as the package itself.  The difference being that when we run `npm install meshcentral` we install meshcentral in `<current directory>\node_modules\meshcentral` thus meshcentral's `package.json` is at `<current directory>\node_modules\meshcentral\package.json` and we don't have a `package.json` at `<current directory>\package.json`, which is where npm is looking for this information.

**Comment by OutbackMatt** [comment]
Just reporting that update this morning only went from v0.4.7-l to v0.4.7-z, and not to the v0.4.8- group

install meshcentral@0.4.8-a upgrades to that version, then a version less update  goes through until 0.4.8-b

**Comment by si458** [comment]
the version numbering has been fixed now
