### ISSUE TITLE
RedirPort not reset if commented out

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#814]
In my json.config

I did have redirport set to port 81, but I now handle that redirection at my (reverse proxy) Apache web server 

I have commented out the RedirPort in my json.config by pre-pending an underscore to that line, but when I start MeshServer I get that Redirport is in use 

This has no impact that I can tell.

**Comment by Ylianst** [comment]
If you comment out the redirection port, it will default to 80. If you want to turn it off completely, set it to zero, as in:

`"RedirPort":0`

Let me know if that works.

**Comment by OutbackMatt** [comment]
Commenting the RedirPort out left it as port 81 (what I had earlier set)

Setting redirPort to 0 turned off the redirPort, Thanks.


Thanks for your continued work on the project.

**Comment by MailYouLater** [comment]
Without a RedirPort setting, it'll default to 80 as Ylianst said, but unless you have set it to only use exact ports it will see that Apache is already listening on port 80 and it will bump the port number up one (to port 81) and try again, if something is already listening on that port to, then it will bump it up one more port until it finds one that is open.
