### ISSUE TITLE
Can't see any type symbol in terminal when connect from mesh to ubuntu 14.04

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#815]
Hello. This is nice software! 

Can you help with problem, please?

Step to reply problem:

1. Create group of device (version of meshcentral is 0.4.7-i)
2. Install linux client to ubuntu 14.04
3. Connect to linux machine by terminal

After that you will see very strange...

for example:

after login I just command `ls` but I don't see ls but if I hit Enter I can see result of ls command. With df and any other command I have the same problem.

I use edge and firefox esr 68 browser with the same result

![изображение](https://user-images.githubusercontent.com/7081357/72216533-424a6f00-3533-11ea-8ad5-59855775fbb1.png)

**Comment by GusevVictor** [comment]
There is no problem with ubuntu 18.04 terminal.

**Comment by Ylianst** [comment]
Good report. I am traveling next week, but will need to check this.

**Comment by krayon007** [comment]
I just root caused this to a previous pull request where the linux terminal tries to use 'script' or 'python' if available to do an interactive terminal. I found on my Ubuntu 14 system, script is present, but when used, it no longer echos input to the screen. It works if I force 'script' to not be used on this platform. I'll see if I can find a better way to detect proper support.

**Comment by GusevVictor** [comment]
> 
> 
> I just root caused this to a previous pull request where the linux terminal tries to use 'script' or 'python' if available to do an interactive terminal. I found on my Ubuntu 14 system, script is present, but when used, it no longer echos input to the screen. It works if I force 'script' to not be used on this platform. I'll see if I can find a better way to detect proper support.

Wow... Thank a lot for your time. Is here any workarround for end user untill you will fix that? I think you can switch to xterm.js because there still other problems. For example: mc (Midnight Commander), htop - does not work at all.

**Comment by si458** [comment]
closing as stale
but please try the latest version 1.1.24
