### ISSUE TITLE
terminal do not support any lang except english

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#816]
Dear all, I use: 0.4.7-i version of meshcentral. I have linux servers with folder on my native lang (in my case it is Russian (utf8-ru, cp1251 and so on). If I have any folder with name contain my native lang into remote linux system, there is big big problem. I can't type any symbol in my language in terminal at all. Because of this I can't change dir to my folder or use Tab. Please, please, please fix that.

**Comment by Ylianst** [comment]
Good report, I will take a look at this. I am traveling next week, but this is something that needs to be working.

**Comment by GusevVictor** [comment]
Enjoy you trip! I'll glad if you can fix that. 

Best regards

**Comment by krayon007** [comment]
Just fixed this. Will be doing more testing, so this will be released in an upcoming update, when Ylian returns from his travels.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-k with Bryan's fix. Let us know if it works.

**Comment by GusevVictor** [comment]
> 
> 
> Published MeshCentral v0.4.7-k with Bryan's fix. Let us know if it works.

Not work. 

v0.4.7-L

It looks like a hell... :( Please switch to xterm.js.  
When I connect to ubuntu 14.04 from windows clt (firefox), if I have En keyboard lang I can type text but when I switch to Russian lang nothing apper and when I have switch to En lang again I cant type any text more. I need to reconnect every time when I switch keyboard lang.

**Comment by Ylianst** [comment]
Using xterm is not a bad idea. I just spent the last few hours working on a prototype. This said, it does not look like it's going to fix the keyboard since xterm only does the rendering. This said, there is an early screen. Once I polish this, I should be able to release it and get feedback on it.

![MC2-XTerm](https://user-images.githubusercontent.com/1319013/73015226-7c87fc00-3dd0-11ea-938a-b55f16768505.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-p with XTerm.js support built-in, let me know if this new terminal works for you. Turns out, XTerm.js also handles all the keys, so hopefully all languages should work.

![MC2-XTerm](https://user-images.githubusercontent.com/1319013/73033433-d6032180-3df6-11ea-9079-f8238854e895.png)

**Comment by GusevVictor** [comment]
> 
> 
> Published MeshCentral v0.4.7-p with XTerm.js support built-in, let me know if this new terminal works for you. Turns out, XTerm.js also handles all the keys, so hopefully all languages should work.
> 
> ![MC2-XTerm](https://user-images.githubusercontent.com/1319013/73033433-d6032180-3df6-11ea-9079-f8238854e895.png)

WOW... it looks like a very very good attempt to fix many many bugs but this is not works as expected again on ubuntu 14.04.

xterm.js very fast!

There is new bugs. I will create new ticket for it.

So, the main problem not fixed. I mean lang problem... That is very strange problem.

Step to reproduce:

Windows client (firefox ESR)
1. Upgrade to 0.4.7-s
2. Open xterm.js (connect to ubuntu 14.04.2)
3. Switch lang to RU
4. The first symbol will be print as **:** and delete line prompt.
5. Please see a screen shot, the first command was **mkdir eng**, the second was **mkdir rus** (but want to type rus in russian Русский)

![изображение](https://user-images.githubusercontent.com/7081357/73049524-ee724b00-3e8d-11ea-9cb9-601e6a8334c0.png)

**There is no problem with lang in classic terminal and xterm.js when I connect to ubuntu 18.04 server.**

![изображение](https://user-images.githubusercontent.com/7081357/73049891-072f3080-3e8f-11ea-8099-d78e9b172a5c.png)

Please fix xterm.js and classic shell works on ubuntu 14 and any other old distr.
