### ISSUE TITLE
Please add VNC support like it is in Apache guacamole

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#819]
Dear all, it will be very very good to add support vnc client.

I have mobile windows CE 5.0 terminals. How can I connect to it with mesh?

I use apache guacamole for this now but I want to swith from apache guacamole to mesh. :)

Thank a lot, best regards.

**Comment by Ylianst** [comment]
Thanks. I looked at Guacamole a little in the past, I think it's a RDP-to-VNC converter. Are you using the Windows CE 5.0 terminals to access MeshCentral, or you want to run the MeshAgent on WinCE? Currently the MeshAgent does not support WinCE.

**Comment by GusevVictor** [comment]
> 
> 
> Thanks. I looked at Guacamole a little in the past, I think it's a RDP-to-VNC converter. Are you using the Windows CE 5.0 terminals to access MeshCentral, or you want to run the MeshAgent on WinCE? Currently the MeshAgent does not support WinCE.

Please see Guacamole it is very very good project with open code. They have GOOD ssh terminals and normal VNC client. I think you can copy paste some ideas or code. 

So, I need to open VNC session from mesh. I just system administrator, and time from time our stuff call me with question about 'bla-bla', I open my Apache Guacamole add my win CE ip + add VNC pass and just open remote desktop in apache. It will be **very VERY very good** if you grab ssh and vnc parts from guacamole.

**Comment by GRIFFCOMMca** [comment]
I looked at this project many years ago, its Linux only (no Windows support).  With all the security issues VNC might not be a bad thing for Mesh, however there appears to be more than once VNC protocol, as most hardware will work with TightVNC but not the genuine RealVNC.....

Since getting Mesh we have moved away from VNC and the proxies like the one listed here...

**Comment by GusevVictor** [comment]
VNC is bad, but it works on very old device. I don't have a chouse if I have an old device (WinXP/WinCE). I working in manufacture and we use very old software and hardware... It is a normal for manufactory.

**Comment by GRIFFCOMMca** [comment]
> VNC is bad, but it works on very old device. I don't have a chouse if I have an old device (WinXP/WinCE). I working in manufacture and we use very old software and hardware... It is a normal for manufactory.

I suppose they could write a CE client.... for XP though... if you have RDP active on the client then you could yse another Mesh client as a router to the old XP using RDP.

So you would RDP to your local PC, that has a Mesh router installed that takes that 3389 request, pushes it to the Mesh server that then pushes it to the Mesh client that then RDP for you to the XP box, result is a seemless RDP client access using Mesh and its Router capabilities.

**Comment by MailYouLater** [comment]
I wonder how difficult it would be to make VNC detection and use work similar to how AMT is treated.  i.e. You can scan the network for discoverable devices (with VNC you may need to be able to manually set what port number meshcentral expects it to be on, as many people don't like leaving VNC on the default port) and add the devices you want, and they show up with "VNC" as the/an available connection type, and/or a device that already appears with AMT/Agent connection could also have VNC detected if present similar to how a device with the agent will also show AMT presense if it is detected.

**Comment by MailYouLater** [comment]
In case these help at all, VNC uses the "RFB" protocol: https://en.wikipedia.org/wiki/RFB_protocol https://tools.ietf.org/html/rfc6143

**Comment by GRIFFCOMMca** [comment]
> In case these help at all, VNC uses the "RFB" protocol: https://en.wikipedia.org/wiki/RFB_protocol https://tools.ietf.org/html/rfc6143

This is possible, however Mesh was designed for clients to "ring home", so what you explain is possible, but likely outside of the scope of the whole point of Mesh (which is a ring home design), there by negating the need of routing.

Mesh has "plugins" so maybe thats a route that should be taken with this, a plugin that scans networks for the protocol you want then pushes it entries in to the portal, problem with this is its just using Mesh as a host portal as its not a native client to Mesh, nor even using the access protocol, so this appears to be just using Mesh as a hosting method and thats it.

**Comment by MailYouLater** [comment]
Unless you set up CIRA, AMT doesn't 'ring home' either.

**Comment by GRIFFCOMMca** [comment]
Is it possible to have VNC to ring home?

Both of the above have to be setup by there design, VNC was designed to be installed and waiting for something to connect to it, so it appears was never designed to "ring home" unlike AMT

**Comment by MailYouLater** [comment]
> Is it possible to have VNC to ring home?

Sort of, not in the same way that CIRA and the mesh agent do, but you can do a 'reverse connection' with at least some VNC server/client configurations.  However you seem to be making some assumptions that I don't believe are correct.  There's no reason whatsoever to force VNC to use port 443 in any way (unless you just _want_ it to), and VNC really isn't a good protocol for use over the internet (it's generally not considered to be secure enough) so anyone using VNC in a business environment is likely doing so within a LAN, where the 'ring home' paradigm isn't required.  In fact MeshCentral is already fully capable of using AMT without any kind of 'ring home' paradigm, as it sends out RCMP pings over the LAN to see if AMT devices (without CIRA) are present, and AMT (again, without CIRA) can be scanned for and added to the device list.  In fact, MeshCentral can even use the agent on a remote device to send the RCMP pings to detect AMT devices on the LAN that device is on, and can connect via AMT (again, without CIRA, so no 'ring home') to remotely manage a device by passing the AMT traffic through a device that has the agent running on it.

**Comment by ryanblenis** [comment]
Wait, can a mesh agent already route from a local instance to another network instance without an agent installed? E.g. <Mesh User> <-> <Internet> <- | <Firewall> | <- <Mesh Agent> -> <Non-Mesh Agent Device> ? Thus connecting the Mesh User to the Non-Mesh Agent device?

**Comment by GRIFFCOMMca** [comment]
With my very limited use of it, yes it can, you are effectually able to use the Mesh client like you are running the software on it.  So running RDP on that mesh agent to connect over to the XP machine, however you are actually doing it on your local PC.

The Router (which is software, however i have also seen a plugin which i have never used), you configure to listed on a certain port (3389 in this case), then select the Mesh Agent machine you want to use a proxy, then the target IP address as seen by that Mesh agent PC.

So 127.0.0.1:3389 will then push that RDP session to the Mesh server via the router software, then out to the Mesh agent which is told to connect to a certain IP address on port 3389 and route the traffic back.

We have used it in certain locations when something local cant be routed outside the LAN that has a Mesh agent on

**Comment by ryanblenis** [comment]
Haha, I wrote the RoutePlus plugin, so you'd think I'd know that, but I didn't play around with much of the options outside the plugins intended automatic routing based on user/agent login (because at that point it just used what the mesh agent had built into it)! I'll have to look into that more.

**Comment by jsastriawan** [comment]
You could use MeshAgent tunnel capability to relay to neighbor service. I implemented that on my mc2router.

**Comment by TotallyNotElite** [comment]
@Ylianst you can probably close this now.

**Comment by Ylianst** [comment]
Your right, thanks for pointing that out.
