### ISSUE TITLE
Allow more granular access

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#820]
It is like #164 but more **complex**

**For example:**

We have a remote non good skill programmer and we don't want to allow him to access desktop our user without confirmation from a user. And we have a normal sysadmin which can do anyting when some user have dinner. - **I suppose there is no possible to achive this in current permission model.** I happy user of 0.4.7-i meshcentral. I think this is possible to fix it.  

Thank a lot.

**Comment by Ylianst** [comment]
I will start by adding #164 first, but this is a good ask. Some users can only take control of a system with remote user consent, that should be useful.

**Comment by OutbackMatt** [comment]
Different users can have different permissions to groups. User consent (confirmation) is set by group

The issue that you face is that a computer can only be in a single group at a time.
Your more experienced user could simply move a computer from one group to another that they have access to, that doesn't require user confirmation, to do what they need and then move it back.

The less experienced user wouldn't get access to the group that allows connections without confirmation

**Comment by GusevVictor** [comment]
> The issue that you face is that a computer can only be in a single group at a time.

Yes. :-( 

> Your more experienced user could simply move a computer from one group to another that they have access to, that doesn't require user confirmation, to do what they need and then move it back.

Yes. This is only solution for now... I think you agree with me that is not a good wokrarround.

**Comment by GusevVictor** [comment]
> 
> 
> I will start by adding #164 first, but this is a good ask. Some users can only take control of a system with remote user consent, that should be useful.

Yes it absolutely need for real life working. This is more complex situation because of this I have cretate this issue. Thank a lot for you attention I hope you will add this possibility soon.

**Comment by iviamandi** [comment]
You could add for each device group control for User Consent permisions to users and user groups, same way it is with Server Rights, in User Authorization section.
That could resolve granular access as needed.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.1-p with per-user and per-device consent settings. Let me know if this works :)

![MC2-AdvancedUserConsent](https://user-images.githubusercontent.com/1319013/79080440-bbd83180-7cc9-11ea-9074-5e717f0ebf8d.png)

**Comment by OutbackMatt** [comment]
Yes I like this much better thanks

**Comment by iviamandi** [comment]
Thanks, It's working great as I tested.
Consent settings for a user are a sum of permissions checked for the device group and for that user, correct?
A more flexible variant to use as the final consent permissions for a user could be as follow: if a user has defined a set of consent permissions, use that, if not, if user is part of an user group and user group has defined a set of consent permissions, use that, else use device group set of consent permissions.
So it would be possible to define the most restricted rules for consent at device group level, you could relax some consent rules for a certain user group and you could relax even more consent rules for a certain user.
It would be great if you could implement consent permissions at user group level too.
Thanks again, you're awesome.

**Comment by Ylianst** [comment]
So, access rights are the sum of device group, user group and device. If consent it not the sum, that would be super confusing. An alternative would be to have a flag on the user could indicate that it's user consent settings override any other.
