### ISSUE TITLE
collection count is deprecated 

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#821]
```
`-------- 1/11/2020, 11:37:38 PM ---- 0.4.7-i --------

(node:18743) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead`
```
node version 12.13
meshcentral version 0.4.7-i

**Comment by ryanblenis** [comment]
Hi @Ilia1 ,

I noticed from a previous issue you posted that you're using plugins. 

I just want to make sure you're using the latest version of your plugins. An update was made in EventLog in version 0.0.20 for exactly this issue.

Thanks!

**Comment by Ilia1** [comment]
@ryanblenis Yes you are right. Updated eventlog plugin to latest version.
