### ISSUE TITLE
 UserAllowedIP doesn't work aftert  update to 0.4.7-j 

### ISSUE THREAD

**Issue by paolor1965** [Ylianst/MeshCentral#822]
Hi, I'm Paolo from University of Genoa
After updating to version 0.4.7-j, the UserAllowedIP function, if enabled, blocks all the IP addresses, not considering the list entered.
In the previous version (0.4.7-i) this function did not present this problem.

Thank you very much for the realization of this really useful and unique sw

Paolo

**Comment by veitw** [comment]
I second the presence of this problem.

**Comment by veitw** [comment]
I had to downgrade to 0.4.7-f, as 0.4.7-{h..i} (-g is not available for installation) had the same problem for me.

**Comment by Ylianst** [comment]
Oh dear! I will check the code and get back to you!

**Comment by Ylianst** [comment]
I think I see the problem, if you are running MeshCentral from the command line using:

node meshcentral --UserAllowedIP 1.2.3.4

I will need to fix that. For now, you can add "UserAllowedIP":"1.2.3.4" in the settings section or domain section of config.json. I will fix the as soon as I can.

**Comment by veitw** [comment]
For me, the problem occurs when using UserAllowedIP in the config.json.

**Comment by paolor1965** [comment]
for me too the problem occurs in the config.json file

**Comment by veitw** [comment]
Hi @paolor1965,

I analyzed the issue and found the problem.

I will issue a patch which will fix this issue as pull request for @Ylianst later this day, but there is also a simple workaround you might want to use until a new release is available:

Edit your config.json and translate all global comma separated IP strings you use (UserAllowedIP, UserBlockedIP, AgentAllowedIP and AgentBlockedIP) to arrays, for example let

`  "UserAllowedIP": "127.0.0.1,10.0.0.0/8",`

become

`  "UserAllowedIP": [ "127.0.0.1", "10.0.0.0/8" ],`

After this change, MeshCentral 0.4.7-h and newer should work again as expected.

Best regards,
// Veit

**Comment by paolor1965** [comment]
Hi  veitw thank you very much. pending the update, I change the syntax in the config.json file

**Comment by veitw** [comment]
Hi @paolor1965,

alternatively, you might apply my patch from #833, it fixes this issue and another one affecting domain-based IP filter, too.

Best regards,
// Veit

**Comment by paolor1965** [comment]
Thanks again.
Best regards.
Paolo

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-k with the fix for this.
