### ISSUE TITLE
Feature request: WireGuard VPN

### ISSUE THREAD

**Issue by mareking** [Ylianst/MeshCentral#823]
Tunneling support has already been asked for and debated in e.g. #128 or #819.

Hereby I would like to ask for WireGuard support :-)
I'd love to see a MeshAgent binary that comes with an integrated WireGuard client. If possible with the later pre-configured to automatically establish a connection to a WireGuard server which operates in the same network as the MeshCentral server. I've tested and frequently used a setting where the connection via WireGuard (also alternatively OpenVPN) was established separately by the native Wireguard client. Offering this "double feature" in "a single one-two mouse-clicks package" would be of great help to me.

In fact this could I think become a great alternative to Teamviewer QuickSupport: Simply sending someone a pre-configured binary or a link to it would enable me to establish a connection with less experienced users easily.

PS. One might also use well-established OpenVPN but since OpenVPN is much more complex and "bulky" I would go with Wireguard first.

**Comment by Ylianst** [comment]
I have not looked into this yet, but at first read, it seems like quite a big lift to do this.

**Comment by MailYouLater** [comment]
Sounds to me like something that would be better as a plugin, and you may find that you can already script up a solution using a separate WireGaurd client and the [ScriptTask](https://github.com/ryanblenis/MeshCentral-ScriptTask) plugin.

**Comment by si458** [comment]
i dont believe this feature will ever be implemented,
work around:
install wireguard on the remote device,
setup a wireguard tunnel to connect somewhere,
then route your meshcentral IP address over the wireguard interface
set the interface in windows services to autostart on startup
