### ISSUE TITLE
Translator error

### ISSUE THREAD

**Issue by desarrollocdb** [Ylianst/MeshCentral#828]
Hi, I was checking the translator.htm page but when I open this error

![Selección_002](https://user-images.githubusercontent.com/26174637/72301507-f54ec180-3634-11ea-9541-809967916b34.png)

**Comment by Ylianst** [comment]
Oh dear. One of the following files is probably not right:

meshcentral-data/translate.json
node_modules/meshcentral/translate/translate.json

If the first one does not exists, it will take the second one. You can open with a text editor and take a look, use a [JSON lint like this one](https://duckduckgo.com/?q=JSON+lint&t=ffnt&ia=answer), or send over the file and I can look at it.

**Comment by vitko-bg** [comment]
You have to be logged in to meshcentral, so session have to keep your credentials.
Open new tab - login to meshcentral - refresh current tab and error will disappear.

**Comment by desarrollocdb** [comment]
Hello, I have solved it with the credentials problem.

Thank you
