### ISSUE TITLE
Untranslatable strings in MeshCmd download dialog.

### ISSUE THREAD

**Issue by p-bo** [Ylianst/MeshCentral#829]
As pictured in screenshot, there is only dialog title translatable.
Strings in window itself cannot be found with search in built in translator tool.
Namely:
- long sentence below window title
- Operating System (it is actually present and translated in strings, but not used there in dialog)
- Action File
- Win32 executable
Would it be possible to add (or use already present) these strings to translation template please?

Thanks and have a nice day 

![untranslatable_meshcmd_download_dialog](https://user-images.githubusercontent.com/12208593/72334758-27583600-36be-11ea-85db-076d25028626.png)

**Comment by p-bo** [comment]
P.S.: MeshCentral v0.4.7-j

**Comment by p-bo** [comment]
P.P.S.: "Win64 executable" string too

**Comment by Ylianst** [comment]
Sorry for the delay, when I get back to work, I will fix this.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-k with a fix for this, let me know if it works.

**Comment by Ylianst** [comment]
Pretty sure I fixed this. Please re-open if needed.
