### ISSUE TITLE
Feature Request: SMART Status and other requests

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#83]
I think it would be great if the software included SMART Hard Drive Status in the agent, that way we can determine if any of the hosts have predictive hard drive failure. 

A couple of other features.

- A Dashboard with alerts from monitored hosts (long high CPU Usage, Low Disk Space, virus detected)
- A location History via IP Address to track mobile users especially useful if a device gets stolen. 
- Application Management (Apps that are installed on the computer also when they were installed and last accessed and possibly the ability o remove them.)
- OS Updates installed and when they were installed
- Grab more info if possible such as Serial Number, Make, model, cpu, ram.

I guess all this would make this tool an RMM tool. I don't know if there are already plans for these things, but I figure id give my feature requests. Thanks the software has been a big help so far...

**Comment by johnnyq** [comment]
Also it would be great to Set Windows System Group Policies through the interface

**Comment by jsastriawan** [comment]
Hi @johnnyq, have you look at meshcore.js and the modules? MeshAgent has an FFI like features which enables reuse of functions defined in native dlls.

**Comment by Ylianst** [comment]
All good suggestions. Bryan always added reading the CPU local and Memory usage in the Mesh Agent, I am far behind on building all of the features on the server & web application. I have not looked into SMART yet, something I may investigate at some point. This said, focus is on stability and security right now... hope I can start adding features like this soon.

**Comment by djsakisd** [comment]
+1 for this. Also the cpu and memory monitoring will be a very nice adition

**Comment by SomeGuru** [comment]
Most if not all of this is in current release of the server released now no?

**Comment by JSuenram** [comment]
@Ylianst 
Is this still on the list for upcoming enhancements? Else close it?

**Comment by johnnyq** [comment]
Technically this can be closed as MeshCentral focuses on remote access and not Remote Monitoring and Management of Devices. An RMM tool such as the Free and Opensource TacticalRMM or paid Non Free Or Non Opensource NinjaRMM etc should be used instead paired with MeshCentral for Remote Access

**Comment by johnnyq** [comment]
I will close this as we have opensource tools that can handle this now.

**Comment by SomeGuru** [comment]
Still would be a nice to have from perspective of users requested on large scale deployments.
