### ISSUE TITLE
MeshRouter What am i doing wrong

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentral#831]
When i run MeshRouter i'm able to login but the Add Relay Map and the Add Map buttons are greyed out, am i doing something wrong?
![image](https://user-images.githubusercontent.com/47992409/72385355-701df680-3773-11ea-8877-177dfeef4cc7.png)

**Comment by PathfinderNetworks** [comment]
That is very odd.  I just tried it and it's working correctly for me.  I wonder, do you have administrator rights on the device you are trying to run this on?  I don't know if that makes any difference or not.  Maybe try running it as administrator and see what happens?

**Comment by rowds15** [comment]
yes i'm running as administrator and i've tried several different computers with the same result.

**Comment by OutbackMatt** [comment]
Did you select your OWN mesh server on the login page, and not use the default 'meshcentral.com'

**Comment by rowds15** [comment]
yes own server and i'm logging in with 1st user created when installed, being Administrator

**Comment by rowds15** [comment]
I have just created a new user with administrator privileges and it seems to work

**Comment by baikal** [comment]
maybe related: I noticed that i makes a difference if a user is a direct 'Full Device Group Administrator' or is member of a user group which is 'Full Device Group Administrator' (indirect):

* direct: MeshCentralRouter allows adding Relay Maps, and they do work
* indirect: MeshCentralRouter allows adding Relay Maps, but they do **not** work (no connection possible through the local port, no 'relay session' entries on the users events tab)

meshcentral 0.4.7-i and 0.4.7-j, own instance, user has has 2FA (authenticator app) which do work.

**Comment by baikal** [comment]
btw: which 'Device Group Rights' are needed for the routing? It seems that at least 'Remote Control' is needed, although restricted to 'View Only', 'No Terminal', 'No Files', 'No AMT' still works.

Is that documented somewhere - or shouldn't there be another right like 'Use for Routing' ?

**Comment by Ylianst** [comment]
Interesting thread, I need to look into this because at the very least, the MeshCentral Router should indicate that you don't have the permissions required and indicate what permissions are needed. I am traveling back now, when back to work next week I will take a look at this (I will have lots of catching up to do).

**Comment by si458** [comment]
closing as stale,
please download the latest version 1.1.21 and use node 18 or above,
also download the latest version of meshcentralrouter too,
if issue perists, please report back
