### ISSUE TITLE
[INFO] Planning upgrade

### ISSUE THREAD

**Issue by merlinweb** [Ylianst/MeshCentral#832]
Hi,
I am planning to update my meshcentral server, installed on a VM with winserver 2016, from version 0.3.9-b
It's a big jump....
A snapshot and offsite server backup are ok to have possibility to revert, just in case ?
Clients will be affected and won't roll back to previous version or I will be able to take a step back ?
I have about 1300 clients connected and about 10 operators, I am just a little worried something could be wrong and irreversible... :-)

thanks a lot for help

Merlinweb

**Comment by marco-vogt** [comment]
Also interested in this. Im not sure on which version my server is running right now but i think the last time i upgraded was ~3 months ago.

id like to upgrade but im a little worried about the agents. is there any version which is "safe" to upgrade to?

**Comment by merlinweb** [comment]
> Also interested in this. Im not sure on which version my server is running right now but i think the last time i upgraded was ~3 months ago.
> 
> id like to upgrade but im a little worried about the agents. is there any version which is "safe" to upgrade to?

Try this to check version:

![image](https://user-images.githubusercontent.com/48550288/72504749-bab87500-383e-11ea-8afa-571257c66fce.png)

**Comment by penguinthingie** [comment]
A snapshot would be just fine. You can actually do something much more simpler. Backup the node_modules folder and then click on the check server version and select the "check and click" option to let the system auto update. If the new version has issues after you log back in, simply delete the node_modules folder and restore the version you took the copy of and that should bring you right back to the stable version you had prior to the upgrade.

**Comment by marco-vogt** [comment]
Thanks. Im not too afraid on the server-side because, as you said, a backup of the node_modules folder will do.

Im more afraid of the agents. Last time i updated, my agents failed to update on their own and didnt come online anymore. I had to replace all the agents manually and i really want to make sure this wont happen again.

**Comment by treicadani** [comment]
The best way to test is to setup a test environment with the version 0.3.9-b and an agent on an local machine / vm and then try to upgrade the environment to the latest version to see the effects it could have in your production env.

**Comment by Ylianst** [comment]
Hi. Sorry for the delay, I was traveling and heading back home now. So, in general, I don't expect any problem just upgrading from 0.3.9-b. I have a similar experience when updating [meshcentral.com](https://www.meshcentral.com), I don't update it often and so, make big jumps each time I update.

Of course, make sure to backup "meshcentral-data" and "node_modules" and backup the database if you are using MongoDB. If you want to have more confidence, you could setup a test network and try it first. Having a backup RMM would also be a good choice. We do have a recovery system in the works and never deployed it. All this said, the update should work just fine. It will take a few minutes once the new server is running to update all agents.

**Comment by MailYouLater** [comment]
> Thanks. Im not too afraid on the server-side because, as you said, a backup of the node_modules folder will do.
> 
> Im more afraid of the agents. Last time i updated, my agents failed to update on their own and didnt come online anymore. I had to replace all the agents manually and i really want to make sure this wont happen again.

The agents automatically update themselves the first time they connect after the server has been updated.  There used to be an issue where the agents would take a long time (sometimes many hours) to reconnect after an update, but this was fixed a number of versions back by adding a maximum length for the agent to wait before it tries to connect again.  I wonder if this is the issue you had when you updated before?

**Comment by merlinweb** [comment]
another situation.., If I execute a server update, wait for client alignement, but for some reasons I want to revert to my previous configuration, what happens to updated clients?
I will lost connection with updated clients, or they will be still alive ?

**Comment by MailYouLater** [comment]
I'm pretty sure they will 'update' (revert) back to the agent that the 'new' (old) server version expects.

**Comment by krayon007** [comment]
That is correct. Whatever server version you run, it will verify the hash of the agent that is reported, and try to update it to the version the comes with the server... So if you revert the server, it will also revert the agent as well.
