### ISSUE TITLE
In agentinvite.handlebars variables not replaced with values

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#836]
Hi!
IMHO agentinvite.handlebars contains errors, the command for Linux is displayed in the browser:
(wget https://mesh.company.net/meshagents?script=1 --no-check-certificate -O ./meshinstall.sh || wget https: // "+ **servername + portStr + domainUrl** +" meshagents? script = 1 --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo ./meshinstall.sh https://mesh.company.net 'HaSh @ HaSh @ HaSh '
It seems that in the second wget command variables are not replaced with values.

**Comment by Ylianst** [comment]
Your right, published MeshCentral v0.4.7-k with a fix. Let me know if it works.

**Comment by TitovLab** [comment]
Thanks. It works.
