### ISSUE TITLE
Request: Email Alerting, Agent Connected/Disconnected

### ISSUE THREAD

**Issue by dmacf10** [Ylianst/MeshCentral#839]
Would love to see email alerting for agent connect/disconnect. This would make MeshCentral invaluable for MSP's and anyone who needs to be aware of server up/down status 24/7.  The web notifications work great as-is but for times when all techs are off-site, email alerts would be extremely useful.

**Comment by Ylianst** [comment]
Good request. I am a bit swamped with requests, but certainly something that would not be difficult and would be useful.

**Comment by jsastriawan** [comment]
I think this could be implemented as third party software. If a user is connected to control.ashx websocket, those events will be delivered automatically. It is a matter of bridging those events to other subsystem (trouble ticket or alerting system).

**Comment by Ylianst** [comment]
Maybe, but since MeshCentral is already configured to the SMTP email server, it's just easier to have this built-in.

**Comment by dmacf10** [comment]
Thanks for the response. I hope this is a feature that you will have time to add at some point in the future. I really think many MSPs could benefit from this type of alerting for their on-prem equipment.

**Comment by diogo24m** [comment]
Is this feature already available?

**Comment by Ajilis** [comment]
I think purpose is to use general SMTP setting; and the feature should consist of a thick in general / or group to use web notification or mail notification.

**Comment by si458** [comment]
this feature exists now,
you setup SMTP inside your `config.json` then you can enable the 'notifications' per group and per device
![image](https://github.com/Ylianst/MeshCentral/assets/765314/b281539a-27f8-4d3e-a7c8-11747e778bd7)
