### ISSUE TITLE
Interface Binding Problem (CentOS)

### ISSUE THREAD

**Issue by nhalstead** [Ylianst/MeshCentral#840]
So I have gotten a brand new install of CentOS 7 and a fresh `npm install` of MeshCentral and I've got it running but for some reason it keeps binding to the localhost interface.

When testing a few things such as changing the binding ports I still get the same results.
I've also tried the command `sudo setcap cap_net_bind_service=+ep ....` with the same results.

I've also switched to using iptables and I've opened the ports.

I'm missing something but I don't know what it is, it showing that its listening to localhost ipv6 but no other interface or ip protocol. If you have any ideas what I could be missing I'll give it a shot. Below are some screenshots of what its got in the environment so far.

Open Ports related to Node:
![image](https://user-images.githubusercontent.com/5577816/72674487-3c79ef80-3a45-11ea-87c9-6bb79195e976.png)

Running Service Log:
![image](https://user-images.githubusercontent.com/5577816/72674500-5fa49f00-3a45-11ea-8bf1-dd6431bd51b1.png)

Running VM's Interfaces:
![image](https://user-images.githubusercontent.com/5577816/72674563-61bb2d80-3a46-11ea-9016-dfcf46af4ad9.png)

Ping results to show that it is getting communications from another machine:
![image](https://user-images.githubusercontent.com/5577816/72674531-efe2e400-3a45-11ea-83f1-99e68da88597.png)

Thanks, Noah

**Comment by nhalstead** [comment]
I've also have made no changes to the config files, everything is still to its defaults, a user has not even been created yet.

**Comment by TitovLab** [comment]
Maybe something has already taken port 8443 on 10.0.5.21? Or maybe it's selinux security?

**Comment by ryanblenis** [comment]
Have you taken a look at #397 regarding the setcap command and documentation updates for CentOS / systemd?
