### ISSUE TITLE
v0.4.7.k, mouse and keyboard input not working on any remote machines

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#841]
Hi, not sure when this version was released, was working on Friday, mine updates every night so if this is a new version, its broken.

Send Ctrl+Alt+Del works, but thats the only thing that does....

Not sure of the agent version... !

**Comment by Ylianst** [comment]
Arg! I know what is happening. I reverted back to v0.4.7-j for now.

**Comment by GRIFFCOMMca** [comment]
How long to fix, i dont like rolling servers back...

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.7-l with all of the fixes for -k and with keyboard/mouse fixes. I am still out until Tuesday, tomorrow is a holiday in the US (Martin Luther King Jr. day).

**Comment by petervanv** [comment]
works for me !

**Comment by GRIFFCOMMca** [comment]
0.4.7.L works for me

**Comment by OutbackMatt** [comment]
Works for me too, thanks

**Comment by circlecomputers** [comment]
I'm updated to 0.4.7-L but still experiencing the same issue, Is there anything additional I need to do such as reinstalled the MeshAgent?

**Comment by Ylianst** [comment]
Make sure you check the "Input" checkbox at the bottom of the remote desktop screen. If not checked, no mouse/keyboard input is sent. Let me know if that fixes it.

**Comment by circlecomputers** [comment]
Many thanks Ylinanst, good, call I had fiddled with that checkbox when the issue first occurred and had left it unchecked.

**Comment by Ylianst** [comment]
Nice. You not the first one to run into this case, I just changed the "Input" to turn red when not checked, I want to see if that helps draw attention to this control. This will be in the next published version.

![MC2-DesktopInputRed](https://user-images.githubusercontent.com/1319013/72920726-c1dbf900-3cfe-11ea-8d23-ef48e796b9ec.png)

**Comment by Ylianst** [comment]
Ok, will close this issue. If someone wants to comment on the red input thing, please open a new issue. Thanks.
