### ISSUE TITLE
Terminal stop work on CentOS 6 after update

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#844]
Updated MeshCentral from 0.4.3-t to 0.4.7-j
After that the terminal in all MeshAgent running CentOS 6 stopped working. When connected in a second commands appear and are immediately disconnect.
There are no errors in the OS logs.
Filmed on video, when trying to connect via the terminal to CentOS 6, MeshCentral manages to show:
```
script: invalid option -- '-'
usage: script [-a] [-f] [-q] [-t] [file]
```
CentOS 7 is working.

**Comment by krayon007** [comment]
Are you running a modified meshcore.js? 
The current meshcore.js, calls linux-gnome-helpers, to check script version. (But the current linux agent doesn't have that method, so it will always return false)
Your error shows it is running script, which should never happen.

The updated binary will actually check script version, and set it to false if it's < 2.25, (which it is on CentOS 6), but the current binary will always set it to false, so it should never use 'script' at all with the current version of meshcore.js.

**Comment by krayon007** [comment]
I see what's going on... 0.4.7-j is a reverted version, which is missing the fix... Please update to 0.4.7-l

**Comment by krayon007** [comment]
(I verified that 0.4.7-l terminal works correctly on my Cent OS 5_11 machine, which should behave the same as CentOS 6.

**Comment by TitovLab** [comment]
0.4.7-l terminal works on CentOS 6, thank you!

**Comment by TotallyNotElite** [comment]
@krayon007 just to clarify, this isn't exclusive to gnome and X sessions right?

**Comment by krayon007** [comment]
No, I should probably rename the module. It's where I put a bunch of Linux helper stuff, it just happened that the first ones were gnome related, which is why it's named gnome-helpers.
