### ISSUE TITLE
0.4.7-I - Selecting display doesn't work reliably and other weird issues

### ISSUE THREAD

**Issue by knk90** [Ylianst/MeshCentral#845]
I only noticed this at 0.4.7-I but it may have been present prior.
Users with 2-3 displays, switching between displays doesn't work.  

Display 1 will show just display 1 usually, however displays 2 and 3 cannot be viewed independently and do nothing when selected.  They remain on the same view that was previously selected (Display 1 or all).

Users with 2 displays seem to be more reliable, but still suffer from this issue from time to time.

Also - sometimes 3 displays are detected as 2 and a disconnect and reconnect shows all 3 again.

Thankyou

**Comment by krayon007** [comment]
What OS is your client running? And do you have TeamViewer installed? I happen to have 3 displays on my main machine... I know on Linux Teamviewer installs a custom video driver, which seems to interfere with display selection, becuase when I ask the X for display n, it gives me the teamviewer virtual display... Not sure if Windows does that too, but I don't have team viewer on my machines...

Can you go to the device manager, and see what it says you have installed for display drivers?
Also, run this command from the command prompt:

MeshAgent -exec "require('monitor-info').getInfo().then(function(d){console.log(JSON.stringify(d,null,1));});"

That should display an array of JSON object showing the client rectangles for each display. For example, on my system, it shows:

MeshAgent -exec "require('monitor-info').getInfo().then(function(d){console.log(JSON.stringify(d,null,1));});"                      
[                                                                               
 {                                                                              
  "left": -2560,                                                                
  "top": 0,                                                                     
  "right": 0,                                                                   
  "bottom": 1440                                                                
 },                                                                             
 {                                                                              
  "left": 0,                                                                    
  "top": 0,                                                                     
  "right": 3840,                                                                
  "bottom": 2160                                                                
 },                                                                             
 {                                                                              
  "left": 3840,                                                                 
  "top": 0,                                                                     
  "right": 6400,                                                                
  "bottom": 1440                                                                
 }                                                                              
]             

The way KVM works, is that I give the rectangle to the OS to scrape the desktop, as the OS maintains one giant buffer of all the displays merged together.

**Comment by grumpystrayan** [comment]
These don't have teamviewer installed but they do have SimpleHelp on them.  I've confirmed this same behavior on 2 Windows 10 Desktops.

Can I obtain the information you're looking for from a log or similar?  Running it from meshcentral's terminal and SimpleHelp's terminal doesn't work and I can't interrupt the users for this.

![image](https://user-images.githubusercontent.com/60167430/72868032-eeab0300-3d34-11ea-9a88-6a4df8db4e2c.png)

**Comment by grumpystrayan** [comment]
Actually I managed to get  it to run in userspace without interrupting the user with SimpleHelp.

Output:
```
[
 {
  "left": 3840,
  "top": 14,
  "right": 6576,
  "bottom": 1838
 },
 {
  "left": 0,
  "top": 0,
  "right": 1920,
  "bottom": 1080
 },
 {
  "left": 1920,
  "top": 0,
  "right": 3840,
  "bottom": 1080
 }
]
```

**Comment by OutbackMatt** [comment]
FWIW
I have four displays (2 by landscape and 2 by portrait) on my Windows 10 Professional machine with Teamviewer installed
displays wok correctly in MeshCentral for me using 0.4.7-l

**Comment by krayon007** [comment]
@grumpystrayan , on your browser,  add "?debug=1" at the end of your server url without the quotes. This will turn on debugging on the webview. Then if you hit F12  on the browser, it will show the debug console. When you connect the KVM while this view is showing, it will shows some pertinent information about the KVM stream. I'm interested in the resolution of the merged desktop... On my system it shows up like the following... In my case you can see the last CMD7 it receives before the first CMD3 is:

CMD7 at X=8960 Y=2160
ScreenSize: 8960 x 2160

The three rectangles you got from the command I gave you earlier, should fit inside this merged bitmap.

![screen](https://user-images.githubusercontent.com/29240564/72919977-3c0b7e00-3cfd-11ea-8721-3f93cc3ebdf6.png)

**Comment by grumpystrayan** [comment]
@krayon007  I'll probably have to do this Monday.  Out with clients all day today and the machines in question aren't on this early in the morning unfortunately.

Will provide an update  as soon as I can.

**Comment by grumpystrayan** [comment]
Finally got this information.
![image](https://user-images.githubusercontent.com/60167430/73214754-e58fbb00-41a6-11ea-95b3-7178d3c796f5.png)

**Comment by si458** [comment]
closing as stale.
please try the latest version 1.1.21 and node 18 or above,
if issue still persists, please reply back
