### ISSUE TITLE
Change mesh client ip

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#847]
hello, i have setup to my clients static ip to look my meshcentral, i want to change static ip to my meshcentral , is there anyway to update my clients with my new static? or i have to go each one and change it?

thanks

**Comment by OutbackMatt** [comment]
Did you use IP address and not FQDN? (Fully Qualified Domain Name, ie mesh.example.com)
Perhaps you change to an FQDN before you actually change your IP address and then simply update your DNS records for the FQDN when you change your IP address.

**Comment by coolwormgit** [comment]
Exactly what i want to do now! i want to change the static ip to my domain name!! but i have too many clients ... its not easy to change everyone!

**Comment by ryanblenis** [comment]
@coolwormgit , I know you use a couple of my plugins, so might I suggest using ScriptTask to replace the old value with the new value in the file, then restart the MeshAgent service?

**Comment by Ylianst** [comment]
Currently, there is no automated way to do this. If you look at each MeshAgent, there is a MeshAgent.msh file that is located next to the MeshAgent (in program files/meshagent or /usr/local/mesh). You can edit it to a common editor, here is an example:

```
MeshName=Lab-Computers
MeshType=2
MeshID=0xEDBE1BE3771D69DF39...
ServerID=D99362D5ED8BAEA8BF9E7...
MeshServer=wss://devbox.mesh.meshcentral.com:443/agent.ashx
ignoreProxyFile=1
webSocketMaskOverride=1
coreDumpEnabled=1
```

You will need to change the MeshServer= URL and restart the agent. One way to do this quickly is to upload a new .msh file to each computer using the "Files" tab (you can drag & drop the new meshagent.msh) and use the "Tools" button in the Remote Desktop tab to restart the agent.

Once you update the current agents to a DNS name, it will be much better for any future changes to the server. Hope that helps. If this needs to be automated in the future, I could consider it, but it's not a priority and has security implications.

**Comment by MailYouLater** [comment]
I think @ryanblenis' idea is good.  I would suggest writing a script (to make the change to the `.msh` and restart the `Mesh Agent` service) that you can use the [ScriptTask](https://github.com/ryanblenis/MeshCentral-ScriptTask) plugin to run, then (after testing on a a small group of machines) run the script on all your devices.

**Comment by coolwormgit** [comment]
thanks guys , im going to try ryanblenis script for start...

**Comment by Ylianst** [comment]
Let me know how the script goes, this could be a "Best Known Method" for doing this, I am sure many others will need it.

**Comment by Ylianst** [comment]
I am going to close this one, but feel free to re-open if needed.
