### ISSUE TITLE
Keyboard Translation

### ISSUE THREAD

**Issue by circlecomputers** [Ylianst/MeshCentral#850]
Hi
I've noted that the keyboard translation on the desktop access appears to be US rather that respecting the local of the client system. For example as a UK English keyboard user I have to type ¬ (top left) to enter an @ symbol. 

This can get kinda tricky when typing passwords on a remote system!

Regards

Gary

**Comment by MailYouLater** [comment]
Related: #469

**Comment by Ylianst** [comment]
MeshCentral v0.6.93 was published with correct keyboard handling on Windows. Bryan is working on doing the same for other platforms (Linux, macOS, FreeBSD). Let us know if it works.

![MC-MultiKeyboards](https://user-images.githubusercontent.com/1319013/99596354-f7975000-29aa-11eb-8c64-c3e07ca0b2f5.png)
