### ISSUE TITLE
Upgraded to 0.4.7-m, now Windows boxes with the 32bit mesh client have no Desktop Files or Terminal tabs

### ISSUE THREAD

**Issue by mattburris** [Ylianst/MeshCentral#851]
I've upgraded to 0.4.7-m.  Windows PC that were connected with the 64bit clients are fine, but any Windows PCs that have the 32bit meshcentral client installed are not showing the tabs for Desktop, Files, or Terminal.

When I go into the Console, I can successfully "clear the core", and then "upload recovery core" to bring back the Terminal and Files tabs.

But when I try to "Upload default server core", I get an error in the console: 
"uncaughtException2: win-bcd on a 64 bit Platform can only be accessed from a 64 bit process"

Restarting the PCs or the Mesh Agent on those PCs does not resolve the issue.  Any suggestions?

**Comment by mattburris** [comment]
If I load the recovery core, I can upload the 64bit MeshAgent installer via files, and then I can "-fullinstall" it via Terminal, and it will allow me Desktop access again, but it seems like there should be a more automatic fix for this.

**Comment by Ylianst** [comment]
My gosh your fast! Published MeshCentral v0.4.7-o with the fix :)

**Comment by Ylianst** [comment]
Correction, versions "m" and "n" had this issue, so, you did not need to be lucky. Version "m" was online for a while. In any case, should be fixed now.

**Comment by mattburris** [comment]
Thank you for the fix, and thank you so very much for all of your hard work and effort... truly awesome!
