### ISSUE TITLE
Missing uninstall instructions for MeshAgent on macOS

### ISSUE THREAD

**Issue by ghost** [Ylianst/MeshCentral#852]
When you click "Add Agent" on a Device Group in MeshCentral, a new window pops up with a drop-down menu that provides instructions for installing and uninstalling MeshAgent on the supported platforms. The problem is that there is no drop-down menu for uninstalling the agent on macOS, only one for installing it. I wasn't able to find uninstall instructions for macOS anywhere in MeshCentral.

![vivaldi_2020-01-23_05-15-33](https://user-images.githubusercontent.com/44198148/72956296-804f5a80-3d9f-11ea-8c01-7bdc7d961c02.png)

![vivaldi_2020-01-23_05-17-33](https://user-images.githubusercontent.com/44198148/72956339-abd24500-3d9f-11ea-9850-93cc0729b3ef.png)

The Group Action "Uninstall Agent" works for uninstalling an agent on macOS, but since uninstall instructions are provided for the other supported platforms, I think they should be provided for macOS as well.

This issue was originally reported in #365, but the documentation is still the same today.

**Comment by Ylianst** [comment]
Good request.

**Comment by si458** [comment]
PR DONE! 
dont forgot to donate ❤️ or have a look at my amazon wish list! https://www.si458.co.uk/2024/01/05/donation/
