### ISSUE TITLE
Add quotation marks around URLs in Linux/BSD install/uninstall instructions

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#853]
When you copy the install/uninstall command for Linux/BSD from the "Add Agent" window and execute it on a FreeBSD host, the command fails with the error `wget: No match`. Adding quotation marks around the URLs in the install/uninstall command allows the agent installation/uninstallation to finish successfully.

This problem was originally reported in https://github.com/Ylianst/MeshCentral/issues/108#issuecomment-524159933 but I forgot to make a separate issue about it after closing #108.

**Comment by krayon007** [comment]
I'll take a look at it in the morning. I remember seeing the other comment, but I couldn't reproduce it on my freebsd system. I'll check to see if it was using wget or curl, I can't remember what the script looks like...

**Comment by whalehub** [comment]
@krayon007 I opened a pull request to fix the problem in case you are able to reproduce it on your end.

**Comment by Ylianst** [comment]
Thanks for the pull request! That is wonderful and you changed at all the correct places. I will have Bryan test the fix because he has many VM's to test on.

**Comment by Ylianst** [comment]
Published in MeshCentral v0.4.7-p.
