### ISSUE TITLE
Explore the option of integrating STF into MeshCentral

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#854]
[STF](https://github.com/openstf/stf) is an open-source software for controlling Android devices from a browser without root. Just like MeshCentral, it's written in JavaScript.

I'm not a programmer, so I don't how how feasible or time-consuming it would be to integrate it into MeshCentral, but I think it's something that's at least worth looking into.

**Comment by Ylianst** [comment]
Taking a look at STF, this may not be what you expect. It controls the Android device using the ADB interface over the USB connector. You would need to connect your Android device to MeshCentral thru a different device and a USB connector. I don't think it would be that useful for general management.

**Comment by whalehub** [comment]
@Ylianst You're right, I thought this software would allow you to control an Android device over the Internet without a physical USB connection to another device.

**Comment by ryanblenis** [comment]
Interestingly, Tasker just [mentioned](https://www.xda-developers.com/tasker-5-9-2-beta-run-adb-shell-commands-without-tethered-pc/) the beta they're releasing that allows Tasker to run ADB commands without root and without being connected to a PC. Not entirely sure how the interface works, but if Google doesn't shut down whatever method they're using for this I suppose it could be possible- but I'd give it some time and see how it works out for them before putting any development effort into it. But it would certainly open up a few doors if it is viable!

**Comment by Ilia1** [comment]
@ryanblenis It seems that such code is used to enable adb. (I could be wrong) 
https://github.com/TinkLabs/QA-ADB/blob/master/app/src/main/java/com/tinklabs/handyadb/ADBReceiver.java#L29
