### ISSUE TITLE
Error: Log Event [button]

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshCentral#856]
When I want to add a device event the server drops the following error message;

-------- 1/23/2020, 8:14:04 PM ---- 0.4.7-c --------

/var/www/html/*.*.*/node_modules/*central/*user.js:2846
                        var targets = ['*', 'server-users', user._id, nodes[0].*id];
                                                                      ^

ReferenceError: nodes is not defined
    at /var/www/html/*.*.*/node_modules/*central/*user.js:2846:71
    at /var/www/html/*.*.*/node_modules/*central/webserver.js:3932:45
    at /var/www/html/*.*.*/node_modules/*central/db.js:808:71
    at newArguments. (/var/www/html/*.*.*/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/var/www/html/*.*.*/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/var/www/html/*.*.*/node_modules/nedb/lib/cursor.js:126:19)
    at /var/www/html/*.*.*/node_modules/nedb/lib/cursor.js:193:12
    at /var/www/html/*.*.*/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/var/www/html/*.*.*/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /var/www/html/*.*.*/node_modules/nedb/lib/datastore.js:323:11

**Comment by Ylianst** [comment]
Working on this now...

**Comment by Ylianst** [comment]
Good catch! Published MeshCentral v0.4.7-q with a fix for this. Let me know if it works.

**Comment by Ylianst** [comment]
Going to close this one since I am pretty sure I fixed it. Please re-open if needed.
