### ISSUE TITLE
Confusing UX after using device page URL 

### ISSUE THREAD

**Issue by da-vid** [Ylianst/MeshCentral#857]
When I use the new device page URL that can be copied from the device page, I expect to be able to do some stuff on the specific device but then also be able to navigate back to a view of all my devices.  If I click on "My Devices", my view is still filtered to the one device, and as best I can tell, the only way to go back to a full view of all devices is to delete the node query string in the address bar.

(Glad to see this URL feature added, btw!)

**Comment by Ylianst** [comment]
Oh! Your right. I don't even have to test it, I know what is going on. I will fix.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-p with a fix for this. The URL is different now, it will be "gotonode=xxxx" so you need to get a new URL. Let me know if it works.

**Comment by da-vid** [comment]
Works much better now, thanks!  

This is getting nitpicky, but if possible, I'd consider clearing the query string whenever navigating away?  Or maybe even upon first load?  The string remains in the address bar indefinitely, and while I understand this is a single page app, it'd be reasonable for a user to assume they could copy and paste it, for example after they've navigated to another device to produce a link to that device.

**Comment by Ylianst** [comment]
Humm... let me see what I can do.

**Comment by MailYouLater** [comment]
Honestly, I feel like the string in the URL bar should change as you navigate around so that you could copy & paste the URL, refresh the page, or even set a bookmark to come back to later, and end up in exactly the same spot you were in before.

**Comment by ryanblenis** [comment]
window.location.hash = 'node=<nodeid>/viewmode=10' might be of use here.

You can have a change function on clicks that finds the relative element to update, and a builder function to output the full string.

You can then just reference the window.location.hash value to rebuild where the user was if the direct link was called.

**Comment by Ylianst** [comment]
Oh my gosh... I just discovered window.history.replaceState()!!! Published MeshCentral v0.4.7-r, the URL now tracks the page and it's wonderful! I got rid of the little icon to copy the device link, you don't need that anymore, just grab the URL. Also, I made it so when the server is reset, everyone goes back to the old page. Feedback appreciated.

**Comment by Ylianst** [comment]
FYI. I got a few more things to fix, if you are looking at a specific user, the link is not right. Working on it now.

**Comment by MailYouLater** [comment]
I was just coming back to recommend using `history.pushState()` and/or `history.replaceState()`.  `pushState` keeps previous urls in the history so you can hit the browser's back button to go back to them, using `replaceState` replaces the current history item so where the browser's back button goes won't be updated.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-s with URL tracking completed, it's a lot nicer than before. I can hit refresh and it goes back to the right page. I am using `history.replaceState()` now, I think that is the right one for this usage.

**Comment by Ylianst** [comment]
FYI. [Posted this on Twitter](https://twitter.com/MeshCentral/status/1220517835870392320).

![MC2-URLTrack](https://user-images.githubusercontent.com/1319013/73037865-5cbefb00-3e05-11ea-95f4-f67e0ddbf139.png)

**Comment by ryanblenis** [comment]
Nice! I suppose I can go vault my LastPage plugin now!

**Comment by da-vid** [comment]
This is great.  I think using history.pushState() everywhere would overall make the whole site work more like a normal website.  But that's getting to a matter of personal preference.  

Thanks, Ylian!
