### ISSUE TITLE
[Web terminal] Setup commands shown in history again

### ISSUE THREAD

**Issue by TotallyNotElite** [Ylianst/MeshCentral#858]
This commit makes commands show in the history again:
https://github.com/Ylianst/MeshCentral/commit/2f37cd882eda74e96db5851b547726c1694ae5f2#diff-3044689b05c5b025849a81e6b6548a47R1217-R1219

The space in front of commands is required in order to hide it from the history.

Additionally, the clear command is not necessary, since it will be executed by the web gui after setting the terminal size (edit: may be necessary for xterm.js):
https://github.com/Ylianst/MeshCentral/commit/2f37cd882eda74e96db5851b547726c1694ae5f2#diff-3044689b05c5b025849a81e6b6548a47R1219

**Comment by Ylianst** [comment]
Ha! That is why there is a space. I will fix it back this morning. Thanks for the report. Yes, I need a "clear" with XTerm.

**Comment by TotallyNotElite** [comment]
Fixed.
