### ISSUE TITLE
[xterm.js 0.4.7-s] scaling problem

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#859]
Step to reproduce:

- use Windows as client (firefox ESR 68)
- upgrade to v 0.4.7-s
- connect to any linux host by xterm.js
- just see screens

![изображение](https://user-images.githubusercontent.com/7081357/73050529-3c3c8280-3e91-11ea-9fbe-df293a54dd55.png)

![изображение](https://user-images.githubusercontent.com/7081357/73050557-4b233500-3e91-11ea-9247-4c16b78bc616.png)

THE GOOD NEWS: MC **WORKS** in xterm.js. YES! YES YES

**Comment by TotallyNotElite** [comment]
Do you mind explaining how you got to that screen? I'll try fixing the issue if I can find out how to get there..

**Comment by GusevVictor** [comment]
> 
> 
> Do you mind explaining how you got to that screen? I'll try fixing the issue if I can find out how to get there..

Just open and noting else please see:

![изображение](https://user-images.githubusercontent.com/7081357/73051383-ac4c0800-3e93-11ea-9cb2-9a1e5b7aeba6.png)

type mc (for example):

![изображение](https://user-images.githubusercontent.com/7081357/73051482-e5847800-3e93-11ea-9c8b-5f5d96764b8c.png)

see result
![изображение](https://user-images.githubusercontent.com/7081357/73051580-01881980-3e94-11ea-92c3-6676a00ac5da.png)

**I don't resize window.**

**Comment by TotallyNotElite** [comment]
Yes I see the problem. MC doesn't send stty resize commands to set the amount of rows and columns. I'm not sure how one would go about dynamically resizing the terminal without spamming the terminal with stty commands.

**Comment by GusevVictor** [comment]
There is not only to mc problem, top, htop 

![изображение](https://user-images.githubusercontent.com/7081357/73052639-a572c480-3e96-11ea-9eda-01fab7cb2bda.png)

![изображение](https://user-images.githubusercontent.com/7081357/73052709-cf2beb80-3e96-11ea-8169-abfa3cf5d23b.png)

WOW bash eat 100% CPU... Hm... Very strange.

**Comment by GusevVictor** [comment]
Wow...

![изображение](https://user-images.githubusercontent.com/7081357/73053285-66457300-3e98-11ea-8603-763f95f97786.png)

**Comment by TotallyNotElite** [comment]
I have a fix, I'll implement it when I have time (20 minutes maybe?)

**Comment by TotallyNotElite** [comment]
Ok I was going to implement this:
https://github.com/copy/v86/issues/172#issuecomment-397017560

But this significantly slows down running of commands. My second thought is making the agent send a signal to the terminal client.

**Comment by GusevVictor** [comment]
Wow..! How I can to test it? I need just wite for a new release of mesh? :)

**Comment by Ylianst** [comment]
I know about this problem, I just started working with XTerm yesterday morning and released it in the afternoon, so not everything is well yet. I was going to fix this by sending a signal to the terminal (not by using stty), it will take a while to fix.

**Comment by TotallyNotElite** [comment]
@Ylianst that was how I was going to do it, I can do that for you if you want. How would you like me to send the data/identifier to send the signal? Just send it over the existing connection?

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-t that will now set the right terminal size at the start and send the resize events to the agent. Bryan is working on getting the agent to resize the terminal now, you can search for 'termsize' in meshcore.js for the "TODO" lines.

We have an agreement that when sending data on the websockets, "binary" type is data and "string" data type is control. So we can easily multiplex the terminal and control data.

**Comment by TotallyNotElite** [comment]
@Ylianst Well dammit I'm basically done doing this myself...

**Comment by Ylianst** [comment]
If you have code for the 'termsize' in meshcore.js for the "TODO" lines, we would like that. Bryan and I are stumped as to how to reside the terminal once it's running.
