### ISSUE TITLE
Thumbnail view quality ....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#861]
Just tried a thumbnail view and look like the is some kind of quality issue ....
When switching to thumbnail view - quality is fine for a second. and after that becoming very low quality.
![multi2](https://user-images.githubusercontent.com/59362521/73063052-ca1a6c80-3e95-11ea-8e83-fd7e097ece30.jpg)

And after a second picture is very low quality .....
![multi1](https://user-images.githubusercontent.com/59362521/73063095-e1595a00-3e95-11ea-83c6-01a84acf6f5f.jpg)

**Comment by Ylianst** [comment]
When looking at multiple devices at once, look for the "Settings" button. There, you can adjust the quality of the thumbnail. By default it's pretty low because you don't want to get too much data from each device, however you can change that. Let me know if that helps.

**Comment by Ylianst** [comment]
Going to close this one since you can change the thumbnail quality using the "settings" button. Please re-open if needed.

![x](https://user-images.githubusercontent.com/1319013/73139941-3dec7e80-4028-11ea-94b4-31f43b43220e.png)
