### ISSUE TITLE
[Feature request] - Show a warning when the PC is controlled by multiple users

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#862]
Hi Ylian,

I would like to request to show a warning message if a PC is already controlled by another user.

As at the moment there is no way to know if the machine is already controlled by someone else and if i set to view the display 1 and another user changes the display to 2, meshcentral freaks out and starts to switch between display 1 and display 2 very fast.

Or maybe a session control on the agent.

Many thanks

**Comment by Ylianst** [comment]
Good request, I am a bit swamped right now, so not sure when I will get to this.

**Comment by si458** [comment]
this feature already kinda exists
when a session is in progress, it shows a blue arrow over the listings
also when you connect in the desktop tab, it now shows 'Connected, X sessions' if multiple connections are in progress
