### ISSUE TITLE
Greenlock version problem

### ISSUE THREAD

**Issue by alesribic73** [Ylianst/MeshCentral#866]
I have upgraded to the latest version of MeshCentral. It installs Greenlock 4.04. As known, it does have issues with creating certificates.

Im using windows installation so i need help downgrading greenlock to 3.1.5 as someone tested and it works.

Thanks

**Comment by Ylianst** [comment]
Oh. Now that I think about it, the Windows Installer was not modified to install GreenLock 3.1.5! (Arg). As a temporary fix:

- Stop the MeshCentral server in Service Manager.
- In a command prompt, go to C:\Program Files\Open Source\MeshCentral.
- Rename "node_modules" to "node_modules_bak".
- type "npm install meshcentral"
- type "node node_modules/meshcentral"
- Server will install all the right modules...
- Wait for the server to run, then CTRL-C and start the server again using service manager.

Hope this helps,
Ylian

**Comment by MailYouLater** [comment]
Couldn't you just go to `C:\Program Files\Open Source\MeshCentral` and run `npm install greenlock@3`?

**Comment by Ylianst** [comment]
That may work, better yet `npm install greenlock@3.1.5`

**Comment by Ylianst** [comment]
I just updated MeshCentral Installer, now version 2.3. It will request GreenLock@3.1.5.

I took a quick look at GreenLock v4 and it's going to require more work, the web site with the migration guide is down.

**Comment by MailYouLater** [comment]
Here's a link to the [Greenlock v4 Migrating Guide](https://git.rootprojects.org/root/greenlock.js/src/branch/master/MIGRATION_GUIDE.md#migrating-guide)

**Comment by alesribic73** [comment]
Hi

I can confirm, that installing - reinstaling with 2.3 Windows installer fixes the problem.  Let's Encrypt is updated correctly.

Thanks for patch.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.7-v that works with GreenLockv3 and GreenLockv4. Note that if you update from v3 to v4, it looks like you will get a new set of certificates.

**Comment by Ylianst** [comment]
Ok, closing this one since Let's Encrypt v3 and v4 should now work. I am running one of my servers on v4 and looks ok. Please re-open if needed.
