### ISSUE TITLE
Mikrotik OS Support

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#875]
hello, is it possible to support Mikrotik OS agent??

**Comment by penguinthingie** [comment]
Mikrotik does not run the typical Linux/Unix implementation but rather a very customized version of Busybox with limited native interpreters and binaries. Doubtful but hopefully the experts can confirm.

**Comment by krayon007** [comment]
@coolwormgit are you referring to RouterOS, or something different?

**Comment by krayon007** [comment]
I took a look at RouterOS, and from the few minutes I spent on the command line, this doesn't look like something that we would be able to easily support, as it seems most all the infrastructure that we use on our linux agent will not work in this environment.

**Comment by Ylianst** [comment]
Looks like RouterOS is really old and required a license. It's unlikely we are going to support this, but if someone does a pull request for it, of course that would be nice. I will want to note that is you have a MeshCentral server you can do:

`https://mesh.domain.com/meshagents`

It will display a list of a MeshAgent binaries for x86/ARM/MIPS... you can download and try the agents to see if one works on your device. This said, it's not something we are going to start working on.
