### ISSUE TITLE
RDP port request

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#876]
hello, because i use a lot of MS RDP is it possible to add inside the agent a text box for rdp port?
this way i can change the default 3389... to any of mine that i use.

something like the picture perhaps...
 
![mesh](https://user-images.githubusercontent.com/10504401/73161838-1ca59400-40f5-11ea-9cca-07b828f4877e.jpg)

**Comment by Ylianst** [comment]
Just to check, once the default RDP port is changed, you expect the "RDP" link at the bottom of the device page to make use of that port?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-a with an option to specify an alternative port. It does not save the port, but let me know if that works.

![MC2-RdpAltPort](https://user-images.githubusercontent.com/1319013/73218489-eaa12b80-410e-11ea-9683-d742ccb71024.png)

**Comment by coolwormgit** [comment]
yes its for the rdp on the bottom, sorry but i cant find where i can give the alternative port ...

**Comment by Ylianst** [comment]
You need to update your server and right click on the "RDP link as shown above.

**Comment by rowds15** [comment]
Getting error running app
PLATFORM VERSION INFO
	Windows 			: 10.0.18362.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3752.0 built by: NET48REL1
	clr.dll 			: 4.8.4075.0 built by: NET48REL1LAST
	dfdll.dll 			: 4.8.3752.0 built by: NET48REL1
	dfshim.dll 			: 10.0.18362.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/UserXX/Downloads/MeshMiniRouter.application

IDENTITIES
	Deployment Identity		: MeshMiniRouter.application, Version=2.0.0.29, Culture=neutral, PublicKeyToken=2e8c763d6917d840, processorArchitecture=msil

APPLICATION SUMMARY
	* Online only application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [28/01/2020 11:49:00 AM] : Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application has started.
	* [28/01/2020 11:49:00 AM] : Processing of deployment manifest has successfully completed.
	* [28/01/2020 11:49:00 AM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [28/01/2020 11:49:00 AM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by Ylianst** [comment]
Is this the first time your try the RDP link, or is this new when you used an alternate port?

**Comment by rowds15** [comment]
First time using this feature (I didn't know this was there) and using the default port on Windows 10
and Windows 7 gives me a different error
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3761.0 built by: NET48REL1
	clr.dll 			: 4.8.4110.0 built by: NET48REL1LAST_B
	dfdll.dll 			: 4.8.3761.0 built by: NET48REL1
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/Users/UserXX/Downloads/MeshMiniRouter.application

IDENTITIES
	Deployment Identity		: MeshMiniRouter.application, Version=2.0.0.29, Culture=neutral, PublicKeyToken=2e8c763d6917d840, processorArchitecture=msil

APPLICATION SUMMARY
	* Online only application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/Users/UserXX/Downloads/Application Files/MeshMiniRouter_2_0_0_29/MeshMiniRouter.exe.manifest did not succeed.
		+ Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
		+ Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
		+ Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [28/01/2020 2:16:34 PM] : Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application has started.
	* [28/01/2020 2:16:34 PM] : Processing of deployment manifest has successfully completed.
	* [28/01/2020 2:16:34 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [28/01/2020 2:16:34 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/Users/UserXX/Downloads/Application Files/MeshMiniRouter_2_0_0_29/MeshMiniRouter.exe.manifest did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.DirectoryNotFoundException
		- Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by coolwormgit** [comment]
oups! sorry my mobile doesnt show the pictures! you are awesome!!!! alternative port is working perfect!!!! can we save the port for each clients??? Thanks

**Comment by coolwormgit** [comment]
> First time using this feature (I didn't know this was there) and using the default port on Windows 10
> and Windows 7 gives me a different error
> PLATFORM VERSION INFO
> Windows : 6.1.7601.65536 (Win32NT)
> Common Language Runtime : 4.0.30319.42000
> System.Deployment.dll : 4.8.3761.0 built by: NET48REL1
> clr.dll : 4.8.4110.0 built by: NET48REL1LAST_B
> dfdll.dll : 4.8.3761.0 built by: NET48REL1
> dfshim.dll : 4.0.41209.0 (Main.041209-0000)
> 
> SOURCES
> Deployment url : file:///C:/Users/UserXX/Downloads/MeshMiniRouter.application
> 
> IDENTITIES
> Deployment Identity : MeshMiniRouter.application, Version=2.0.0.29, Culture=neutral, PublicKeyToken=2e8c763d6917d840, processorArchitecture=msil
> 
> APPLICATION SUMMARY
> * Online only application.
> * Trust url parameter is set.
> ERROR SUMMARY
> Below is a summary of the errors, details of these errors are listed later in the log.
> * Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application resulted in exception. Following failure messages were detected:
> + Downloading file:///C:/Users/UserXX/Downloads/Application Files/MeshMiniRouter_2_0_0_29/MeshMiniRouter.exe.manifest did not succeed.
> + Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> + Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> + Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> 
> COMPONENT STORE TRANSACTION FAILURE SUMMARY
> No transaction error was detected.
> 
> WARNINGS
> There were no warnings during this operation.
> 
> OPERATION PROGRESS STATUS
> * [28/01/2020 2:16:34 PM] : Activation of C:\Users\UserXX\Downloads\MeshMiniRouter.application has started.
> * [28/01/2020 2:16:34 PM] : Processing of deployment manifest has successfully completed.
> * [28/01/2020 2:16:34 PM] : Installation of the application has started.
> 
> ERROR DETAILS
> Following errors were detected during this operation.
> * [28/01/2020 2:16:34 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
> - Downloading file:///C:/Users/UserXX/Downloads/Application Files/MeshMiniRouter_2_0_0_29/MeshMiniRouter.exe.manifest did not succeed.
> - Source: System.Deployment
> - Stack trace:
> at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
> at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
> at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
> at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
> at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
> at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
> at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
> at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
> --- Inner Exception ---
> System.Net.WebException
> - Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> - Source: System
> - Stack trace:
> at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
> at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> --- Inner Exception ---
> System.Net.WebException
> - Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> - Source: System
> - Stack trace:
> at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
> at System.Net.FileWebRequest.GetResponseCallback(Object state)
> --- Inner Exception ---
> System.IO.DirectoryNotFoundException
> - Could not find a part of the path 'C:\Users\UserXX\Downloads\Application Files\MeshMiniRouter_2_0_0_29\MeshMiniRouter.exe.manifest'.
> - Source: mscorlib
> - Stack trace:
> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
> at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
> at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
> at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
> 
> COMPONENT STORE TRANSACTION DETAILS
> No transaction information is available.

have you installed extension for your browser?

you need this for chrome: 
https://chrome.google.com/webstore/detail/clickonce-for-google-chro/kekahkplibinaibelipdcikofmedafmb

and i use this for firefox:
https://addons.mozilla.org/en-US/firefox/addon/breez-clickonce/

**Comment by Ylianst** [comment]
As an alternative, you can on my the "My Devices" page and click on "Router" to download the Windows MeshCentral Router tool. It's pretty easy to use and does not need any browser support. Let me know if you try this and if it works or not.

![MC2-WinRouter](https://user-images.githubusercontent.com/1319013/73291262-aec0a180-41b4-11ea-9a35-1f4f5666da9b.png)

**Comment by coolwormgit** [comment]
i already tried it but is not so good if you have 15 users for support.. this way if one user create the rdp port is accessible from others... its going to be super if i can save it! thanks

**Comment by rowds15** [comment]
> 
> 
> As an alternative, you can on my the "My Devices" page and click on "Router" to download the Windows MeshCentral Router tool. It's pretty easy to use and does not need any browser support. Let me know if you try this and if it works or not.
> 
> ![MC2-WinRouter](https://user-images.githubusercontent.com/1319013/73291262-aec0a180-41b4-11ea-9a35-1f4f5666da9b.png)

Hi Ylian,
I have already got a bug open for the mesh central router "MeshRouter What am i doing wrong #831" could it be something in my environment?

**Comment by Ylianst** [comment]
Are you behind an HTTP proxy? if so, how is it configured on your system?

**Comment by rowds15** [comment]
Yes it's a transparent proxy. 
My Meshcentral server is on an internal intranet and i have all the local subnets excluded from the transparent proxy. I have a machine on the same subnet with proxy disabled and i still get the same error.

**Comment by coolwormgit** [comment]
Hey ylianst, can been fixed to keep the port?? thanks

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-i, it now saves the alternative RDP port on the server. Let me know if that works.

![MC2-AltPort](https://user-images.githubusercontent.com/1319013/74689697-ff626380-5190-11ea-8d87-6346773a1514.png)

**Comment by coolwormgit** [comment]
Its working Perfect!!!!! thanks!! you save the day!
