### ISSUE TITLE
Wrong / incorrect link .....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#877]
Just a quick one - when clicking on My Devices and then at the bottom "Router" it shows download dialog for MeshCentralRouter.exe, as it should be. But when you select device and then click at the bottom on the link Router - it shows MeshCMD download box. ......
Sorry for opening new issue - just wanted to let you know.

**Comment by Ylianst** [comment]
Well, this is normal but your right that naming both "Router" is not great... One is the "MeshCentral Router" that is Windows only, the other one is MeshCMD which runs on both Windows and Linux. I will have to think about this one.

**Comment by si458** [comment]
this has been fixed already in 2023
