### ISSUE TITLE
Add optional user confirmation prompt in settings

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#88]
Commercial remote control programs like LogMeIn, TeamViewer or Bomgar have the option to require a user to confirm a prompt before remote control can be assumed by the host (e.g. "XYZ wants to connect to your machine. Press OK to grant them permission."). It would be neat if this could be added as an **optional** setting in MeshCentral.

**Comment by jsastriawan** [comment]
Yeah, this is required for PCI DSS compliance and privacy regulations. AMT side has User Consent which provides pin via firmware. 

I guess we can do this via server generated pin then sent to user desktop via bubble notification. If user consent is required, desktop must ask for PIN that matches the other side.

Ylian and I had discussed this long time ago but I haven't had a chance to write some code on it.

**Comment by whalehub** [comment]
@jsastriawan It should be optional though so that people who want the unattended access function of TeamViewer can still use it here.

**Comment by Ylianst** [comment]
Yes, that is certainly something that needs to be done. I think we are adding features and fixing bugs at a good pace, but need more time to get it done. Help from jsastriawan on this would be appreciated.

**Comment by krayon007** [comment]
I actually had a prototype demo of this feature a few weeks ago. I was just waiting on a configuration setting to be implemented, before I merged this functionality in, so that the feature can be enabled/disabled.

**Comment by whalehub** [comment]
@krayon007 @Ylianst Is there any ETA on when this feature will be merged in?

**Comment by Ylianst** [comment]
Lots of people are asking for this feature. I think I will take a look at it next week.

**Comment by PaverNet** [comment]
When'll you planning add this feature to project? 
It's very useful feature.

**Comment by rightvision** [comment]
Maybe for the first step it would be great to have at least a notifcation on the remote system when connecting to the desktop. The function deviceToastFunction() is already there...

**Comment by sorvani** [comment]
> Maybe for the first step it would be great to have at least a notifcation on the remote system when connecting to the desktop

That should be separate feature request, it has nothign to do with consent. But also one I want.

**Comment by motapek** [comment]
Now we can set user notification when agent is connecting (bravo !!) but what with the user confirmation? Has anything new happened in this matter? I think that is very important feature. I'm waiting patiently but some news can help wait :)

**Comment by Ylianst** [comment]
This is one for Bryan. The agent needs to be able to popup a dialog box in the currently logged in user context for both Windows and Linux and get user feedback. Once the agent can do that, it will be added. I do want to poll people on what do to when no user is present? Feedback appreciated.

**Comment by TitovLab** [comment]
In one product it was made like this:
1. The option of such a notification/confirmation can be enabled or disabled.
2. Sets the time (30 seconds by default) for the user to give his answer.
3. If the answer is not received during this time - the connection is allowed. (by default)
4. If there is no user or the desktop is locked, the connection is allowed without any confirmation (by default).
All parameters can be set on the server side before creating an agent distribution kit.

**Comment by UnP1u9** [comment]
It's very useful feature. hoping to be implemented soon.

**Comment by Patriciawa** [comment]
Indeed a very useful feature.

**Comment by UnP1u9** [comment]
**Hi,

what about starting a web page just like a chat window but with a yes or no conformation with a 30 sec timer and only connect if users give yes as a response or don't click any within 30 sec.**

_this setting can be optional just like the notification setting._

and can you make some setting where we can disable chat button and others as some time user can miss click .

![image](https://user-images.githubusercontent.com/19772335/57910614-57d3a000-78a3-11e9-84c0-da1be839abf2.png)

**Comment by krayon007** [comment]
I'm working on this feature as we speak. It should be ready for primetime very soon. The component I'm using to display the user consent dialog box on Linux now has a dependency on Gnome. Hopefully that is ok. (I'm using Zenity for the dialog boxes). I tried using X directly, but that turned out to be extremely difficult to do without any dependencies on specific Windowing Managers. So I scrapped that and went with Zenity, which should be part of the standard GNome installation.

Windows and Linux support will come first, as I still have to write the code to popup a dialog box on Mac OS.

**Comment by sorvani** [comment]
I disagree that consent should default to allow if no answer in X seconds. 

But as long as consent required is controlled by group and that there is also a setting to not allow if no answer, this is great

**Comment by krayon007** [comment]
I'll be able to support both GNome and KDE, as I found I can use kdialog on KDE systems

**Comment by UnP1u9** [comment]
I can see the user prompt option in the setting in latest update but they have no effect right now, is there anything i am missing 😅

**Comment by krayon007** [comment]
No, I was doing internal testing with my agent builds. It'll be ready soon. I have it working on Linux and Windows. Working on MacOS at the moment...

**Comment by matt-primrose** [comment]
Giving this a small bump to see how this is progressing.

**Comment by UnP1u9** [comment]
Any possible was you can deploy windows and Linux only for now, Mac can be added later once you are done with that.

**Comment by krayon007** [comment]
It's actually already been deployed :) it should work on all three platforms.

**Comment by UnP1u9** [comment]
ohk Nice, will check asap. ;)

**Comment by UnP1u9** [comment]
Yep, works like charm, however prompt doesn't come on top particularly and might get missed due to time limit, any way to fix both

**Comment by krayon007** [comment]
The time limit is configurable, but I don't think Ylian exposed that setting yet. As far as the dialog being on top, I'll see if I can address that. Which platform were you seeing that issue?

**Comment by UnP1u9** [comment]
on windows, it gets behind the chrome and disappears after time limit.

**Comment by UnP1u9** [comment]
HI,

Was you able to check this, just won't be able to use this until fixed 😁

**Comment by whalehub** [comment]
@krayon007 @UnP1u9 Any update on making the prompt appear on top of all other applications in Windows?

**Comment by Ylianst** [comment]
I think Bryan fixed this. I think it's already released in the current version, if not it will be in the next agent release, probably tomorrow.

**Comment by whalehub** [comment]
@UnP1u9 Can you check if the issue has been resolved in the latest version?

**Comment by whalehub** [comment]
@Ylianst Thanks!
