### ISSUE TITLE
Dependencies being installed every time meshcentral is run

### ISSUE THREAD

**Issue by wh1te909** [Ylianst/MeshCentral#882]
Every since 0.4.7-x, every time meshcentral is run, the extra dependencies are being installed even if they are already installed. 

Here's one example when generating login token

Before 0.4.7-x:
![mesh2](https://user-images.githubusercontent.com/7434746/73303902-18987580-41cc-11ea-80d9-16fee8536b11.PNG)

After 0.4.7-x:
![mesh1](https://user-images.githubusercontent.com/7434746/73303917-1fbf8380-41cc-11ea-91cd-34259f2f8df3.PNG)

**Comment by Ylianst** [comment]
What version of NodeJS are you running? Type `node -v` to see the version. Thanks.

**Comment by wh1te909** [comment]
node 12.14.1 on ubuntu 18.04

**Comment by Ylianst** [comment]
Can you try this:

- Go in /meshcentral (the folder above node_modules).
- Type `node node_modules/meshcentral` to run the server.

Do this a few times and let me know if the problem happens again. Thanks.

**Comment by wh1te909** [comment]
Yep that fixed it, not happening anymore after running that command once from the root directory. Thanks!

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-f with a fix for this. There should not longer be any issues regardless of where you run MeshCentral from.

**Comment by wh1te909** [comment]
Hmm tried now with a fresh install of latest version, completely new directory, still happening.
If I manually edit package.json and add mongo and otplib as dependencies, no longer happens.

![mesh3](https://user-images.githubusercontent.com/7434746/73413414-7c03cf80-42c0-11ea-9ba8-e33186bbd5e7.PNG)

**Comment by Ylianst** [comment]
Oh! You just gave me the solution! I will fix this tomorrow.

**Comment by Ylianst** [comment]
MeshCentral v0.4.8-g should fix this. Let me know if it works for you.

**Comment by wh1te909** [comment]
Yep it's working thank you!
