### ISSUE TITLE
Spanish translation please check it...

### ISSUE THREAD

**Issue by solrac901** [Ylianst/MeshCentral#883]
I use the tool to add the Spanish language to the json.
[translate.zip](https://github.com/Ylianst/MeshCentral/files/4124511/translate.zip)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-e with your Spanish translations. I did some corrections to many strings, so if you can start with the new translate.json file for any fixes, that would be great. Also, I want to post this on Twitter, if I can use a name to give credit, let me know.

![MC2-Spanish](https://user-images.githubusercontent.com/1319013/73310825-e261f280-41d9-11ea-9305-645d381ba7d2.png)

**Comment by solrac901** [comment]
Will be great just change the flag im feom mexico

[image: image.png]

**Comment by solrac901** [comment]
Will be great just change the flag :) im from Mexico
I forgot it, i'm @solrac901 in twitter
Regards.

**Comment by Ylianst** [comment]
Fixed! Sorry about that! Posting now on Twitter...

**Comment by Ylianst** [comment]
[Posted it](https://twitter.com/MeshCentral/status/1222288978474176512). Thank you!

**Comment by desarrollocdb** [comment]
Hi, I have installed the recent version to activate the Spanish language. {0} appears on the homepage. How can it be solved?

![image](https://user-images.githubusercontent.com/26174637/74150914-f1cd3c80-4bd8-11ea-94bb-480b9f7d7181.png)

**Comment by MailYouLater** [comment]
The ` {0}.` at the end of the "es" line should be removed to match the "en" line: https://github.com/Ylianst/MeshCentral/blob/d1ddf2aa8f4997b66d18a88f5141c9b45ae20bf1/translate/translate.json#L19237-L19238
