### ISSUE TITLE
MongoDB periodic database backup error

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#885]
I'm running MeshCentral v0.4.7-z on NodeJS v13.7.0 together with MongoDB v4.2.2 on Debian 10.

MeshCentral tries to perform a database backup every 24h. This process fails on my machine with the following error message:

```
Jan 28 21:11:41 debian node[7295]: ERROR: Unable to perform database backup: Error: Command failed: "mongodump" --db "meshcentral" --archive="/opt/meshcentral/meshcentral-backup/mongodump-2020-01-28-21-11.archive"
Jan 28 21:11:41 debian node[7295]: 2020-01-28T21:11:41.318+0100        Failed: error creating intents to dump: error getting collections for database `meshcentral`: (Unauthorized) command listCollections requires authentication
```

The credentials for my MongoDB database are supplied to MeshCentral in my `config.json` file (see below) and during regular operation, it is able connect to, read from and write to the database just fine.

`    "MongoDb": "mongodb://meshcentral:<redacted>@127.0.0.1:27017/meshcentral"`

Based on the error message, it looks like MeshCentral doesn't use the credentials from the `config.json` file to authenticate with the database for the backup operation.

**Comment by whalehub** [comment]
After having a look at the [official documentation](https://docs.mongodb.com/manual/reference/program/mongodump/) for `mongodump`, it looks like the command that MeshCentral issues to initiate the backup is missing the `--uri` flag (see [here](https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-mongodump-uri) for details).

**Comment by whalehub** [comment]
After having a look at the [official documentation](https://docs.mongodb.com/manual/reference/program/mongodump/) for `mongodump`, it looks like the command that MeshCentral issues to initiate the database backup is missing the `--uri` flag (see [here](https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-mongodump-uri) for details).

**Comment by whalehub** [comment]
I think this issue is related to what @darryl-h reported in #717.

**Comment by Ylianst** [comment]
Yes, your right. Adding --url="", will be fixed in next publish version.
