### ISSUE TITLE
Add visible error messages to Account Creation page

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#886]
If a user tries to sign up on a MeshCentral instance with a username and/or an e-mail address that is already taken, the Account Creation page is silently refreshed with no information about why the sign-up process failed.

I think it would be good if MeshCentral instead output an error message like "This username is already taken." or "This e-mail address is already taken." in these instances.

**Comment by whalehub** [comment]
I noticed that this is already implemented on the website of the [official MeshCentral instance](https://meshcentral.com/), but it doesn't seem to be implemented in the latest self-hosted version (v0.4.8-e).

![vivaldi_2020-01-29_10-35-48](https://user-images.githubusercontent.com/44198148/73344704-1e9d5d80-4283-11ea-9c7b-e9c77c145a47.png)

**Comment by ryanblenis** [comment]
Probably best to have a generic "A user with that information already exists, Forgot Password?" type link so emails or usernames in use are not known (in the event someone is trying to guess the information).

**Comment by Ylianst** [comment]
It should be always implemented, [MeshCentral.com](https://meshcentral.com/) runs the exact same code. I just tested it on my developer machine and and I see the message. When you type an invalid username/password, do you also not see an error message?

**Comment by whalehub** [comment]
@Ylianst @ryanblenis I found the cause of the issue. I'm using a custom `login.handlebars` file in the `meshcentral-web` folder and haven't updated it since August 2019, The default `login.handlebars` file in the `node_modules/meshcentral/views` folder already includes this change.
