### ISSUE TITLE
Device Groups of deleted accounts are temporarily displayed on admin's "My Devices" page

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#887]
I'm running MeshCentral v0.4.8-e on NodeJS v13.7.0 and noticed that when a user deletes their account while I'm logged into the admin account and on the "My Devices" page, their Device Groups are displayed among mine until I refresh the page. 

• **Prior to the removal of a user account**

![vivaldi_2020-01-29_10-40-04](https://user-images.githubusercontent.com/44198148/73345211-f4986b00-4283-11ea-8657-5c23a2d161e1.png)

• **Right after the removal of a user account**

![vivaldi_2020-01-29_10-40-24](https://user-images.githubusercontent.com/44198148/73345218-f82bf200-4283-11ea-8d30-06b54849f7fb.png)

I did another test where I had a device connected to the user's Device Group at the time of the account deletion and luckily the device doesn't show up on the admin's My Devices page. Instead, the group is displayed as empty like it is on the second screenshot.

**Comment by Ylianst** [comment]
Nice catch :) I don't think I would have found myself in a long time.

**Comment by Ylianst** [comment]
Fixed committed for next release.

**Comment by Ylianst** [comment]
FYI. MeshCentral v0.4.8-g has the fix for this. Let me know if it works.

**Comment by whalehub** [comment]
@Ylianst I can confirm that the issue is fixed in the latest version.
