### ISSUE TITLE
"Forgot username/password" option missing on login page with "Minify" config option set to "1"

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#890]
I'm running MeshCentral v0.4.8-e on NodeJS v13.7.0.

If I set the config option `Minify` in my `config.json` file to `1`, the "Forgot username/password" option disappears from my login page.

![waterfox_2020-01-29_21-16-06](https://user-images.githubusercontent.com/44198148/73393951-ec204e80-42dc-11ea-8532-48781c36cb92.png)

If I set the config option `Minify` back to `0` and restart MeshCentral, the option shows up on the login page again.

![waterfox_2020-01-29_21-00-03](https://user-images.githubusercontent.com/44198148/73393994-04906900-42dd-11ea-8afe-96340da68e31.png)

**Comment by petervanv** [comment]
Same in Dutch
![Minify-1](https://user-images.githubusercontent.com/58996467/73396465-b5006c00-42e1-11ea-8f11-82684373ed52.jpg)

![Minify-0](https://user-images.githubusercontent.com/58996467/73396466-b5990280-42e1-11ea-8cb6-14e6cb5e1b42.jpg)

**Comment by Ylianst** [comment]
Oh! Thank you for reporting this. Working on it.

**Comment by Ylianst** [comment]
Ok, will be fixed in next published release.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-f with a fix for this. Let me know if it works.

**Comment by whalehub** [comment]
@Ylianst I can confirm that the issue is fixed in MeshCentral v0.4.8-f.

**Comment by jfp2** [comment]
I have the latest version running on Linux 2 AWS instance, and I don't get the "Forgot password" login with Minify off, 0 or 1.

**Comment by petervanv** [comment]
is this setting in your config.json ?     "Minify": 0,
you can change the value in to 1 if its not there (section settings) you can at that.
 another posibilty is that is disabled looks like this     "_Minify": 0,   when you remove the underscore it should work

**Comment by whalehub** [comment]
@jfp2 I believe you need to specify an SMTP server in your `config.json` file for the "Forgot password" option to show up on the login screen.

**Comment by jfp2** [comment]
SMTP was not enabled -- thanks. BUT, now I have a new problem. I checked the SMTP server authentication protocol, and it's using TLS 1.2. I've tried every  combination of TLS conf.json settings and the server won't load. Note, I tested connectivity with other another tool.

  "smtp": {
    "host": "smtp.ionos.com",
    "port": 587,
    "pass": "XXXXXXX",
    "user": "info@end-support.com",
    "from": "info@end-support.com",
    "__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
    "tls": true,
    "___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
    "_tlscertcheck": false,
    "__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
    "_tlsstrict": true
  }

Thanks!

**Comment by whalehub** [comment]
@jfp2 I'm not sure I understand what the issue is. Your mail server does not support TLS 1.2?

**Comment by jfp2** [comment]
Thank you for helping. It does support TLS 1,2, but no amount of configuration changes seem to make a difference. Again, I've successfully tested it with online SMTP testers.

**Comment by whalehub** [comment]
@jfp2 What's the error message that MeshCentral is outputting?

**Comment by jfp2** [comment]
the server just doesn't come up in the a browser. If I disable the entire SMTP section (_smtp)the welcome page comes up. Where do I find the conf.json error log?

thanks

**Comment by whalehub** [comment]
@jfp2 There should be a file called `MeshErrors.txt` in the same folder. Are you running it on Windows or Linux?

**Comment by jfp2** [comment]
Linux

**Comment by whalehub** [comment]
@jfp2 In that case, you should also be able to see the startup errors in `stdout` if you manually run it with `node meshcentral` in the installation folder or via `systemctl status meshcentral` if you have it running as a systemd service.

**Comment by jfp2** [comment]
Okay strange. I use (sudo systemctl start meshcentral.services) to start MeshControl and when I do, it fails to load the site due to the SMTP issue. However, if I manually start MeshCentral with "node meshcentral" the page loads BUT any attempt to send email from Meshcentral fails with the following:

[ec2-user@ip-172-31-50-51 node_modules]$ node meshcentral
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.5.4, WAN mode.
MeshCentral Intel(R) AMT server running on un-configured:4433.
MeshCentral HTTPS server running on www.end-support.com:443.
SMTP mail server smtp.ionos.com failed: {"code":"ETIMEDOUT","command":"CONN"}
SMTP server failed: {"code":"ETIMEDOUT","command":"CONN"}

The settings:
 "smtp": {
    "host": "smtp.ionos.com",
    "port": 25,
    "from": "support@end-support.com",
    "user": "support@end-support.com",
    "pass": "REDACTED",
    "tls": false,
    "__tls__": "When 'tls' is set to true, TLS is used immidiatly when connecting. For SMTP servers that use TLSSTART, set this to 'false' and TLS will still be used.",
    "_tls": false,
    "___tlscertcheck__": "When set to false, the TLS certificate of the SMTP server is not checked.",
    "_tlscertcheck": false,
    "__tlsstrict__": "When set to true, TLS cypher setup is more limited, SSLv2 and SSLv3 are not allowed.",
    "_tlsstrict": true

**Comment by whalehub** [comment]
@jfp2 You can try it with the following cleaned up SMTP config section:

```
   "smtp": {
   "host": "smtp.ionos.com",
   "port": 587,
   "from": "support@end-support.com",
   "user": "support@end-support.com",
   "pass": "REDACTED",
   "tls": false
  },
```
If you continue to receive the same error message using that config, I would test if the MeshCentral host is able to reach your mail server with `ping smtp.ionos.com` and `traceroute smtp.ionos.com`.

**Comment by jfp2** [comment]
Sorry but nada. I can telnet into the SMTP server and send e-mails, so nothing blocking. I even tried using Base64 formatted username and password. The node meshcentral does bring the server up, but it kicks back SMTP timeout errors when I try to send from MeshCentral.

**Comment by jfp2** [comment]
Strange...I had used 465 before and it didn't work,but PRESTO now all is working.

THANK YOU....stay safe

**Comment by whalehub** [comment]
@jfp2 You're welcome. 👍
