### ISSUE TITLE
Enabling the config option "TitlePicture" causes the config options "Title" and "Title2" to be ignored

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#891]
I'm running MeshCentral v0.4.8-e on NodeJS v13.7.0.

I've been using a custom `login.handlebars` file in my `meshcentral-web` folder together with the config options `TitlePicture`, `Title` and `Title2` since around August 2019 with no issues.

I deleted my `meshcentral-web` folder earlier today to try out the updated default `login.handlebars` file and noticed that the text I set in the `Title` and `Title2` config options in my `config.json` file no longer shows up on my MeshCentral page.

After experimenting with the config options for a bit, I found out that removing the `TitlePicture` config option makes the text show up on my page again.

This is what the top left corner of my page looks like with the `TitlePicture` option enabled and a .png file that has "Test" written on it.

![waterfox_2020-01-29_21-44-21](https://user-images.githubusercontent.com/44198148/73396392-8edacc00-42e1-11ea-8743-e8d386f78488.png)

This is what it looks like with the `TitlePicture` option removed.

![waterfox_2020-01-29_21-53-15](https://user-images.githubusercontent.com/44198148/73396496-cc3f5980-42e1-11ea-9a73-97ad1e3a3c08.png)

**Edit:** You can view my old `login.handlebars` file [here](https://hastebin.datahoarder.dev/JSnTjq.xml) and my old `login-min.handlebars` file [here](https://hastebin.datahoarder.dev/Ndqbuz.xml).

**Comment by whalehub** [comment]
You can view my old `login.handlebars` file [here](https://hastebin.datahoarder.dev/JSnTjq.xml) and my old `login-min.handlebars` file [here](https://hastebin.datahoarder.dev/Ndqbuz.xml).

**Comment by Ylianst** [comment]
Try `"title1":"MyServer"`.

The problem with the old system is that you would want to set a picture, but have the real title of the web page set to a real string. So, now you set title to the name of our company, and use "title1" and "title2" to set the large title text. You can also use "titlehtml" to write custom HTML in the title bar.

      "_titlehtml": "<div style=\"height:66px;color:#c8c8c8;padding-left:14px;padding-top:8px;font-size:46px;font-family:Arial,Helvetica,sans-serif;font-weight:bold\">This is a test</div>",
      "title": "MyServer",
      "title1": "MyServer",
      "title2": "ABC",
      "titlePicture": "title-test.png",

In testing this again, I did find a bug that "title2" did not show up right in some cases, will be fixed in the next published version. Hope it helps.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-f with a fix for "Title2".

**Comment by whalehub** [comment]
@Ylianst I can confirm that it works again in MeshCentral v0.4.8-f with the new config options.

The [MeshCentral User Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.6.pdf) should be updated with this information.
