### ISSUE TITLE
Notifications not working as expected

### ISSUE THREAD

**Issue by olivier37520** [Ylianst/MeshCentral#893]
notifications are not working if char ' is in text.
notification's text : i'll take control at 2pm <= notification won't display
notification's text : i\\'ll take control at 2pm <= notification is displayed but need to escape ' char

**Comment by vitko-bg** [comment]
Where exactly you are using this notification  option?

**Comment by olivier37520** [comment]
device nodification on Desktop tab

**Comment by Ylianst** [comment]
Good catch. It's an agent problem, Bryan is working on it.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-h with the fix. Let me know if it works for you.

**Comment by olivier37520** [comment]
ok, fixed
