### ISSUE TITLE
Mobile version Keyboard issues.... 

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#894]
When MeshCentral is on russian and connectiin to win10 with PIN locked, no option to show keyboard and to enter that PIN
![Screenshot_20200131_110022](https://user-images.githubusercontent.com/59362521/73534709-a9b05c00-4419-11ea-81cc-6e88b18a8e99.jpg)

When changing language to English, button is there, but when trying to type PIN in, K/B just disappears and can't login
![Screenshot_20200131_105937](https://user-images.githubusercontent.com/59362521/73534728-b8970e80-4419-11ea-9246-09229a770cac.jpg)

![Screenshot_20200131_110125](https://user-images.githubusercontent.com/59362521/73534642-8685ac80-4419-11ea-9439-6d29abce1470.jpg)

**Comment by desarrollocdb** [comment]
Tengo un problema parecido, al intentar escribir desde la aplicación móvil Android, el teclado se esconde. @Ylianst

**Comment by ryanblenis** [comment]
I believe this problem is fixed with the latest mobile updates, and this can be closed.

**Comment by si458** [comment]
thie has been fixed, 1.1.20, new mobile UI, where you can go full screen and open keyboard

**Comment by mrkacg1** [comment]
Hello, when trying to type in the terminal and then clicking enter, the keyboard is hidden from a mobile.

**Comment by si458** [comment]
are you using the latest version 1.1.20?
what mobile OS are you using?
what browser?
whats the remote device/OS you are controlling?

**Comment by mrkacg1** [comment]
Yes, yesterday I installed the version on the server.I use Android and Chrome browser.I'm trying to access the Windows terminal.--Gracias. Quedo atento a sus comentarios, ¡Saludos!. ---- El sáb., 03 feb. 2024 08:21:14 -0500  ***@***.*** escribió  ----
are you using the latest version 1.1.20?
what mobile OS are you using?
what browser?
whats the remote device/OS you are controlling?

**Comment by si458** [comment]
what android version are you uring?
just tried it here on my Z fold 3 (android 14) with chrome, and i dont get the keyboard vanishing?
only issue i have is it doesnt scroll down properly, so it looks like im typing blank text until i scroll down the screen and see its actually typed
i also dont have any of these issues if i use firefox on android at all, both the keyboard and the text not scrolling down

**Comment by mrkacg1** [comment]
Android one - 14In the terminal, the enter does not appear to be able to send the command.--Gracias. Quedo atento a sus comentarios, ¡Saludos!. ---- El sáb., 03 feb. 2024 08:45:42 -0500  ***@***.*** escribió  ----
