### ISSUE TITLE
Admin PowerShell Gone in Terminal

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#895]
0.4.8-g

There are four choices when you right click on the connect button.  The second one, Admin PowerShell isn't working now.  It goes to Admin CMD the same as the top option.  User PowerShell is still working.

**Comment by krayon007** [comment]
I think I know what's going on. I'll take a look at it when I get in the office.

**Comment by krayon007** [comment]
Ok, I fixed it. I had to copy/paste (and modify) the user terminal for the admin terminal, to work around a bug in the Window ConPTY API. In doing so, I forgot to update the protocol number check for Powershell, so it was never going to match admin powershell (was looking for user powershell)...

Ylian will push the meshcore change when he gets in...

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-h with the fix. Let me know if it works.

**Comment by scottalanmiller** [comment]
Can confirm.  All good now, thanks.
