### ISSUE TITLE
Clipboard Not Grabbing Full Text

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#897]
Using the "get clipboard" function it used to get the full contents of what we had in the remote clipboard.  Now it is only grabbing some of it, like the first couple of words.

0.4.8-g

**Comment by krayon007** [comment]
Which OS is your target machine?

**Comment by krayon007** [comment]
Nevermind, I figured it out. I fixed the issue. It was caused because on Windows, the old ANSI Clipboard didn't need a length field, but when I switched it to UTF8, it became a requirement, but it was never set. The fix needs an agent update, so I'll have Ylian push an update when he gets in.

**Comment by SomeGuru** [comment]
copy same result as @scottalanmiller issue... Awaiting the drop to resolve the issue.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-h with the fix. Let me know if it works.

**Comment by SomeGuru** [comment]
Confirmed working from my end... Three servers updated and no longer showing the issue reported. Thx
