### ISSUE TITLE
Account Creation: Name should be UserName

### ISSUE THREAD

**Issue by scottalanmiller** [Ylianst/MeshCentral#898]
When creating a new user, it asks for Name, but it means "User Name".  This is confusing to new users when they try to put a full name in there, with spaces.  Just needs the label adjusted.

**Comment by Ylianst** [comment]
Fixed it, will be in the next published version.

**Comment by Ylianst** [comment]
Published in MeshCentral v0.4.8-h. Let me know if I fixed it.

**Comment by scottalanmiller** [comment]
Sure did, thanks.
