### ISSUE TITLE
My Files upload not working on Linux server

### ISSUE THREAD

**Issue by olivier37520** [Ylianst/MeshCentral#899]
I was trying to understand why i can create folder but can't upload any files, and of course with a silent fail.

In fact fs.rename gives an error "EXDEV: cross-device link not permitted, rename".
You can use mv lib instead fs in webserver.js function handleUploadFile.

I see this error only on linux based server using tmpfs for /tmp.

**Comment by Ylianst** [comment]
Hi. What is "mv lib"?  Are you talking around line 2267 of webserver.js? If you any be more specific about the error and what needs to be changed, that would be most appreciated. Thanks.

**Comment by olivier37520** [comment]
working solution, line 2264 to 2266 need to be replaced by this code an adding mv to package.json
feel free to rename errors vars

```
obj.fs.rename(file.path, fpath, function (error_rename) {
                                if(error_rename && error_rename.code==='EXDEV'){
                                        const mv = require('mv');
                                        mv(error_rename.path, error_rename.dest, function(error_mv){
                                                if(error_mv) console.log(error_mv);
                                                else obj.parent.DispatchEvent([user._id], obj, 'updatefiles'); // Fire an event causing this user to update this files
                                        });
                                } else obj.parent.DispatchEvent([user._id], obj, 'updatefiles'); // Fire an event causing this user to update this files
                            });
```

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-i with a fix for this. Let me know if it works. I want to keep the MeshCentral dependency list as low as possible, so after looking at the "mv" code, I just did a filecopy+unlink if the EXDEV error occurs. Looks to work for me, but let me know.

**Comment by olivier37520** [comment]
not working, silent fail + meshcentral reload. 
i'm doing some debug

**Comment by olivier37520** [comment]
ReferenceError: fs is not defined at meshcentral/webserver.js:2268:50

**Comment by olivier37520** [comment]
work fine after update fs.copyFile to obj.common.copyFile

**Comment by Ylianst** [comment]
Oh! My mistake, I will fix that.

**Comment by Ylianst** [comment]
Should be fixed now. Just published MeshCentral v0.4.8-l but its was fixed a few versions ago. Let me know if it works.

**Comment by olivier37520** [comment]
ok, fixed for me

**Comment by Ylianst** [comment]
Thanks!
