### ISSUE TITLE
Runtime records for the device entire life cycle

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#90]
In MechCentral-> device-> general section, which can only show whether the 7 Day Power State, Can Mongo database save all the Power State, so that we may evaluate the life cycle of the device and the history of downtime.
We are planning to manage the industrial PC in every corner of the factory with MeshCentral.

Thanks so much.
billy du

**Comment by Ylianst** [comment]
Interesting. Currently the database keeps 30 days of general events and 10 days of power events. To get started, I will make this configurable and make a power log and event log export feature. Would this be ok?

**Comment by Ylianst** [comment]
Just published MeshCentral 0.2.8-v with improved database optimizations. Now all events and power events are in their own MongoDB collections. You can also set the expiration time. By default, i currently expire events after 20 days and power events after 10 days. However, this is now configurable. On the config.json file, do this:

```
{
  "settings": {
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "DbExpire": { "events": 1728000, "powerevents": 864000 },
    "Port": 443
  }
}
```

"DbExpire" has two sub values, that are the number of seconds to expire records. Just set this to a very large number (zero value is not allowed right now). After that, you will have all the power events in the "power" collection of MongoDB.

Hope it helps - Ylian

**Comment by billydu1980** [comment]
Dear Ylianst, thanks for your extra effort, I have started testing the latest version and have successfully tried to access the mongodb database, calling power and events tables, for simple data analysis and lifecycle presentation.

Best regards,
Billy du

**Comment by billydu1980** [comment]
Dear Ylianst, thanks for your extra effort, I have started testing the latest version and have successfully tried to access the mongodb database, calling power and events tables, for simple data analysis and lifecycle presentation.

Best regards,
Billy du
