### ISSUE TITLE
Question: How many LDAP servers can you align the server?

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#900]
Hi Yilian,

I am wondering can a multi-company user access be done... meaning can LDAP from companies that share access...

So you are Company A and running server in a secured DC
I am now in Company B and want to share my LDAP list to the server for my employees to get access
A friend of mine  from Company A is now part of Company C and wants his employees LDAP on your server... How can multiple LDAPs be done or is there an easier way to do this user access controlling to the regards?

-SomeGuru

**Comment by Ylianst** [comment]
I don't use LDAP at much, so I got no knowledge on this.

**Comment by Ylianst** [comment]
Going to close this one since I don't expect any answers on this. If you do have details and a pull request for something like this in the future, please open a new issue.
