### ISSUE TITLE
Add ability to play back session recordings without downloading them locally

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#902]
The way MeshCentral's Session Player currently works is that you need to download the .mcrec file from your server via SFTP or a similar protocol and drag & drop it into your browser.

It would be convenient, especially for larger files (>1GB), if MeshCentral could play back the recordings directly from the server, e.g. as a new tab in MeshCentral which is only accessible from the admin account.

This could potentially also be controlled via an optional role/permission so that users could view their own recordings from the MeshCentral GUI without requiring SFTP access to the server.

Thoughts?

**Comment by Ylianst** [comment]
This is a good ask and certainly something that could be built. No sure when I will get a chance to do this. I would also like to show and filter the recordings within a nice user interface.

**Comment by MailYouLater** [comment]
Related: #736

**Comment by Ylianst** [comment]
FYI. Published MeshCentral v0.4.9-e with an auto-indexing mode. Starting with this version, you can put `"index" : true` in the "SessionRecording" section of the config.json like this:

```
      "SessionRecording": {
        "filepath": "C:\\temp",
        "index": true,
        "protocols": [ 1, 2, 100, 101 ]
      }
```

When set to true, the remote desktop recording files will be indexed every 10 seconds, so that when you play them back you can skip to any point in the file at 10 second intervals. I wanted to do this before working on streaming the file since I want to be able to seek thru the file while streaming it.

Testing on this feature would be appreciated. I expect in the future I will index the recordings by default.

**Comment by whalehub** [comment]
@Ylianst I upgraded to MeshCentral v0.4.9-e earlier today and enabled the index option in my `config.json` file to test this feature. I don't have a desktop to test that part of it right now, but it doesn't seem to work for terminal recordings (yet). I can see the progress bar with the seconds at the bottom, but I can't skip forwards or backwards in the terminal recording.

**Comment by Ylianst** [comment]
Right, it only works for remote desktop. Does not work yet for Intel AMT KVM or terminal. I am going to have to great creative to make this work with the terminal.

**Comment by MailYouLater** [comment]
Does the indexing occur while recording, opening, or playing the file?

**Comment by Ylianst** [comment]
Right now, the indexing occurs after saving the file. MeshCentral will re-open the file and run thru it and append the index at the end of the file and close it again. Indexing is done in a separate process from the main MeshCentral server, so if it crashes and runs into issue, it's not going to stop the main server.

Also, there is a "mcrec.js" file in the MeshCentral folder you can run manually as a command line tool to index an existing .mcrec file. This is that I use for my development tests.

**Comment by MailYouLater** [comment]
Thanks.

**Comment by whalehub** [comment]
This feature was recently added to MeshCentral.
