### ISSUE TITLE
Logout Control Missing

### ISSUE THREAD

**Issue by johnczer** [Ylianst/MeshCentral#904]
I have not been keeping up with Meshcentral for a while but thought I would start looking at this again. I noticed on the latest version 4.8-i there is no option to log out of the portal (logout control).

**Comment by petervanv** [comment]
The logout button; see arrow
![Screenshot_7](https://user-images.githubusercontent.com/58996467/73615855-4b979a80-460c-11ea-8ba3-ccff62be3a39.jpg)

**Comment by Ylianst** [comment]
Also, if you run the server with `--user admin` or `--nousers` or setup the server with domain authentication, there will not be a logout button. Let us know if this is your case.

**Comment by johnczer** [comment]
I had originally updated from another previous 0.4.x version and that was the result I got.  I started new install at 0.3.9 version and installed 0.4.8-i over top and the logout is back where I expected to find it, in the upper right. We're good, thanks
