### ISSUE TITLE
Limited Input vs Remote View Only in device group permissions

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#905]
What is the difference between `Remote View Only` and `Limited Input Only` in the permissions to a group of devices?
It seems that this is the same thing and only one of them works?

**Comment by Ylianst** [comment]
'Remote View Only' will not allow user input at all.
'Limited Input Only' will only allow basic input keys, a to z, space, enter and numbers.

I was asked to add `Limited Input Only` because by someone that was managing kiosk devices and wanted to present anything like ctrl-alt-del, etc.

Hope that helps.

**Comment by TitovLab** [comment]
Yes, that helps.
Thank you!

**Comment by mohamadmilad1** [comment]
After installing and running MeshCentral locally, I have been using its remote features. However, I have two questions:

    I want to connect to clients in a "view-only" remote mode at times, where even if I move my mouse, it won’t appear on the client’s desktop, and they won’t notice my presence. How can I achieve this?

    I haven’t been able to use MeshCentral for remote connections, similar to AnyDesk, to access systems that are not on the same network and are often located in various parts of the world.

**Comment by si458** [comment]
>     I want to connect to clients in a "view-only" remote mode at times, where even if I move my mouse, it won’t appear on the client’s desktop, and they won’t notice my presence. How can I achieve this?

You simple untick the box at the bottom that says Input, this is basically a view only mode


>     I haven’t been able to use MeshCentral for remote connections, similar to AnyDesk, to access systems that are not on the same network and are often located in various parts of the world.

You need a dns name, then u set it in `cert` in your config.json and restart meshcentral. This turns it into hybrid mode then u make sure to port forward 80/443 in ur router to ur meshcentral ip
