### ISSUE TITLE
Device group administrator does not see all events

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#906]
The device group administrator does not see other people's events on the device events tab.
At the same time, they are displayed in the `My Events` section.

**Comment by Ylianst** [comment]
Checking this now...

**Comment by Ylianst** [comment]
Fixed it, will be in the next published version.

**Comment by Ylianst** [comment]
Fixed in MeshCentral v0.4.8-l, let me know if it works.

**Comment by TitovLab** [comment]
It works. Thanks!
