### ISSUE TITLE
Stuck key when switching windows with COMMAND-TAB

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#907]
Steps to recreate:

1) Install `meshagent` on linux and connect to it via meshcentral in chrome
2) Install onboard: `sudo apt-get install onboard`
3) Run onboard: `onboard`
4) Hold the `COMMAND` button (key in onboard window should highlight)
5) While holding `COMMAND`, press and release `TAB` to shift focus out of your mesh browser
6) While holding `COMMAND`, press and release `TAB` to shift focus back into the browser
7) Release `COMMAND` (key in onboard window remains highlighted)
8) Press the `e` key (file explorer pops up as though `COMMAND` were still being held)
9) Press and release `COMMAND` (key in onboard de-highlights after release)
10) Close the file explorer window
11) Press the `e` key again (file explorer does NOT pop up)

To see the keyboard events in X11 in realtime you can run `xev`.  Thanks, and apologies if this is a dup but this stuff is pretty transparent on linux so maybe that's a good env to test on.

**Comment by MailYouLater** [comment]
Related: #330
I don't think this is a duplicate, but it seems to be the same issue, but for a different modifier key.

**Comment by Ylianst** [comment]
I will take a look at this tomorrow, but I want to say thank you for posting such a detailed bug report.

**Comment by edlins** [comment]
Hello.  My name's Scott and I'm a test dev.  And I use mesh quite a bit.  Thank you for your work on this project - it's really quite impressive.  I will probably have some feature requests at some point but I'll stick to bugs for now.

**Comment by canove** [comment]
It happens when we press "WIN + R", to run a commando on Windows machines. The "run" screen pops up on my local computer, and when I go back to Mesh remote session, WIN key is still pressed (explorer opens if I press "e"). 

Thanks for the detailed reporting!

**Comment by Ylianst** [comment]
I think what is going on is that some keys combinations will cause the local browser lose focus. For example with ALT-TAB to switch apps. The sequence is [ALT-Down] [TAB-Down] when the browser looses focus that the [TAB-Up] [ALT-Up] are not sent to the remote device and ALT and TAB keys get stuck.

My plan is to keep a list of keys that are "pressed down" and when the browser losses focus, the web page would send all the "up" keys to get everything unstuck. There is code already present to do this, but it does not seem to work. I can make this happen pretty easily on my developer machine.

**Comment by MailYouLater** [comment]
I thought you fixed <kbd>Alt</kbd>, <kbd>Ctrl</kbd> and <kbd>Shift</kbd> in #330 and would just need to make it watch for <kbd>Command</kbd> and <kbd>Win</kbd> too.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.8-t, I removed the old code for <kbd>Alt</kbd>, <kbd>Ctrl</kbd> and <kbd>Shift</kbd> and now monitor "pressed" state for all keys. When the browser goes out of focus, all pressed keys are now released. Let me know if this works.

**Comment by canove** [comment]
It works! Thanks for the great job.
