### ISSUE TITLE
Upgrade from shell doesn't work as expected (Increased Security Installation)

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#908]
Hi all, I have setup mesh by MeshCentral2 Installer’s Guide (Version 0.0.9
August 23rd, 2019 Ylian Saint-Hilaire)

page 23 says me:
![изображение](https://user-images.githubusercontent.com/7081357/73733585-4ee66f80-474d-11ea-8121-8395f42a68c8.png)

I try to upgrade as describe on this page but there is no new version of mesh downloaded and installed. Please see screen below:

![изображение](https://user-images.githubusercontent.com/7081357/73734008-01b6cd80-474e-11ea-94c0-bc5484d7213f.png)

Will be glad for any help!
Best regards

**Comment by whalehub** [comment]
@GusevVictor I believe the documentation is incorrect in this case. You need to run `npm install meshcentral` to upgrade MeshCentral, not simply `npm install`.

**Comment by GusevVictor** [comment]
> 
> 
> @GusevVictor I believe the documentation is incorrect in this case. You need to run `npm install meshcentral` to upgrade MeshCentral, not simply `npm install`.

Oh... I have type `npm update`  it look like ok. Is it correct too? :)

**Comment by whalehub** [comment]
@GusevVictor Yes, `npm update` is also ok.

**Comment by MailYouLater** [comment]
While correcting this in the docs, I'd also recommend to fix these:

> ... so that the “meshcentral” account gets read-only access _to_ the files.

> To make this work, you will <s>make</s> _need_ to make ...

**Comment by Ylianst** [comment]
Updating docs now... Thanks @MailYouLater for the extras :)

**Comment by Ylianst** [comment]
Just did a silent update of the [MeshCentral Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf) with these fixes. Let me know if that works.

**Comment by GusevVictor** [comment]
> 
> 
> Just did a silent update of the [MeshCentral Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf) with these fixes. Let me know if that works.

Hi! :) If I'm not stupid the pdf don't contain any fix yet... :( The old and new pdf have the same md5 hash summ.

**Comment by whalehub** [comment]
@GusevVictor You probably need to clear your browser cache. I can see the updated version on my end.

**Comment by GusevVictor** [comment]
> 
> 
> @GusevVictor You probably need to clear your browser cache. I can see the updated version on my end.

OK. It looks like OK! Thank. Close. :)

**Comment by MailYouLater** [comment]
I'd blame server caching.  I'm getting the new version at http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2InstallGuide-0.0.9.pdf, however, the following comment from #830 still hasn't been addressed:
> >    Page 23 in the PDF states to use "sudo cd /opt/meshcentral" - "cd" doesn't like "sudo" (this is the first time the "cd" command is used on this page, a few lines down it's listed without "sudo")
> 
> Ha yes, that needs to be fixed. When I get home, I will update the docs. Thanks for pointing that out.
