### ISSUE TITLE
Strange log error

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#909]
after rebooting my server i got this error in the log file

OS: Ubuntu Server 18.04.4 LTS
Mesh version: 0.4.8-m
NodeJS: V10.18.1
NPM: 6.13.4

-------- 2020-2-4 10:17:19 ---- 0.4.8-m --------

(node:20137) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

-------- 2020-2-4 10:17:19 ---- 0.4.8-m --------

(node:20137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------- 2020-2-4 10:17:23 ---- 0.4.8-m --------

(node:20137) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
(node:20137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by petervanv** [comment]
anyone ?

**Comment by baikal** [comment]
i do have these as well (in syslog and on the web interface under "show server error log"). same ip address : **34.208.62.34**

node v10.19.0, npm 6.13.4, ubuntu 18.04

```
-------- 2/9/2020, 10:53:17 PM ---- 0.4.8-u --------

(node:3604) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)


-------- 2/9/2020, 10:53:17 PM ---- 0.4.8-u --------

(node:3604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
(node:3604) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:3604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)


-------- 2/10/2020, 12:27:32 AM ---- 0.4.8-u --------

(node:3604) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)



```

**Comment by MailYouLater** [comment]
IDK if this helps at all, but a reverse DNS lookup shows that that IP address is an Amazon AWS server.

**Comment by petervanv** [comment]
i don't have any service running there, strange is in my error log

**Comment by baikal** [comment]
I do not have any service running on AWS. my meshcentral is on a Azure machine - and has shows the same IP in the logs.
I have letsencrypt activated (and working), could that be related?

**Comment by petervanv** [comment]
i dont think its related to let's encrypt, (?) i'm running it since december last year and suddenly this error occurred

**Comment by baikal** [comment]
after updating greenlock to 4.0.4 (was 3.1.5), the error is still there, but formatted differently:

```
-------- 2/23/2020, 9:12:51 PM ---- 0.4.9-k --------

error adding maintainer to support notices:


-------- 2/23/2020, 9:12:51 PM ---- 0.4.9-k --------

{ Error: connect ETIMEDOUT 34.208.62.34:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '34.208.62.34',
  port: 443 }
```

and after some digging, the error *error adding maintainer to support notices* seems to originate from `node_modules/@root/acme/maintainers.js`, calling `https://api.rootprojects.org/api/...` URLs. 

And api.rootprojects.org resolves to the ip **34.208.62.34** !

**Comment by petervanv** [comment]
as you did , i upgrade also to greenlock version 4.04, my errors are gone, only an notification:  FAKE "CERTIFICATES (for testing) only "

**Comment by baikal** [comment]
yes, you're right: when running meshcentral regularly (`systemctl start meshcentral.service`) these "ETIMEDOUT 34.208.62.34:443" errors are gone (instead once per start "FAKE CERTIFICATES .."). But when running meshcentral in debug mode (`node node_modules/meshcentral --debug`) these "ETIMEDOUT 34.208.62.34:443" errors still do show up.

Having no clue what this `node_modules/@root/acme/maintainers.js` is for, just that api.rootprojects.org (34.208.62.34) is not reachable, at least not from any of my machines.

**Comment by petervanv** [comment]
because of the greenlock depreciation, I close this topic.

**Comment by Ylianst** [comment]
Thanks. I am super happy with the acme-client and looks like upgrades are going well.
