### ISSUE TITLE
Updated Russian translation and feedback

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#911]
Updated Russian translation In the attachment [translate.zip](https://github.com/Ylianst/MeshCentral/files/4155308/translate.zip).
A few bug reports and feedback:
1. `player.htm` ignores the translation. Even adding `?lang=ru` to the URL does not help
2. In `agentinvite` there is no way to translate `for` and page title:
![image](https://user-images.githubusercontent.com/11898568/73776720-56336a80-4799-11ea-85a5-1c914ea72273.png)
3. In the future, in `translator.htm` the function show only records without translation will help
4. No need to translate `group: ip: tag: g: t:` filters in `default.handlebars`, otherwise they do not work
5. The translations do not work in 0.4.8-m when using customizations, but there is a separate entry for this #837

**Comment by Ylianst** [comment]
Thanks you for the translations and bug reports, working on it now.

**Comment by Ylianst** [comment]
FYI. I got almost everything fixed up except #837 that I am working on now. For `group: ip: tag: g: t:`, I made them work correctly even when translated. Working on your point 3 and 5 now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-n will (I hope) all these fixes made. For 3, I added a new option on the translation web page.

![MC2-TransEmptyOnly](https://user-images.githubusercontent.com/1319013/73801387-1ce60500-476f-11ea-909d-5ac82b44cc70.png)

**Comment by TitovLab** [comment]
WOW, you are very fast!
1. `player.htm` now use translations
2. `agentinvite` show white blank page now (English also), browser show error:
`Uncaught ReferenceError: format is not defined at agentinvite?c=hash:145`
Line 145: `QH('groupname', format("Remote Agent Installation for {0}", groupName));`
3. `Show No Translations Only` already come in handy. How fast the future comes!
4. `group: ip: tag: g: t:` works like a charm even if translated.

**Comment by Ylianst** [comment]
Oh, thanks for the report. Will work on a fix for number 2.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-q with a fix for the agentinvite not working. Thanks for reporting that.

**Comment by TitovLab** [comment]
Flag `--translate` does not work, all information about that updated in #837 
`agentinvite` now working OK, thanks!
Updated Russian translation: [translate.zip](https://github.com/Ylianst/MeshCentral/files/4166300/translate.zip)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-r with updated Russian translations. Thanks.

**Comment by Ylianst** [comment]
MeshCentral v0.4.8-s should fix #837. Let me know if it works. Do close this issue if you think it's resolved.

**Comment by TitovLab** [comment]
Thank you!
