### ISSUE TITLE
Changing permissions for device group need page refresh in about 90% of cases

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#914]
Changing permissions for device group need page refresh in about 90% of cases.
How to reproduce:
1. Go to `My Account`
2. Select any device group
3. Select any user or group, check or clear `Remote View Only` flag (or any other)
4. Open again same user or group, in about 90% of cases flag not cleared/checked until page refresh in browser
Google Chrome 79.0.3945.130 on Windows 10.

**Comment by Ylianst** [comment]
Nice catch & report!! Thank you! Published MeshCentral v0.4.8-z with a fix for this. Let me know if it works.

**Comment by Ylianst** [comment]
I will close this one since I am pretty sure it's fixed. Please re-open if needed.
