### ISSUE TITLE
Blocked ip

### ISSUE THREAD

**Issue by geanferrani123** [Ylianst/MeshCentral#915]
Guys, good afternoon!

I am currently having some difficulties with login at meshcentral. Some users when accessing the mesh, are receiving the message "ip blocked ..." what can it be? Can you help me? I did not perform any configuration in config.json about blocked ip range.

**Comment by Ylianst** [comment]
Try adding this line to the settings section of config.json:

`"CookieIpCheck": false`

Let me know if that fixes it. Your users may be accessing your server using different public IP addresses.

**Comment by MailYouLater** [comment]
If you're seeing this message while trying to log in, I think you may have exceeded the number of allowed login attempts within a certain period of time.
![image](https://user-images.githubusercontent.com/1279475/73898980-09ef3580-4840-11ea-8a92-15f72400ef3f.png)
This feature was requested in issue #640, and can be customized if desired.

**Comment by geanferrani123** [comment]
> Try adding this line to the settings section of config.json:
> 
> `"CookieIpCheck": false`
> 
> Let me know if that fixes it. Your users may be accessing your server using different public IP addresses.

Hello Ylianst, good morning!

Anywhere in config.json?

**Comment by Ylianst** [comment]
`"CookieIpCheck": false` goes in the "settings" section on config.json. However, @MailYouLater has an even better theory and mine. Go in "My Server" and "Console" tab and type "badlogins", lets us know what you see.

![x](https://user-images.githubusercontent.com/1319013/73964505-2a160780-48c7-11ea-8319-eb966576e44a.png)

**Comment by geanferrani123** [comment]
At the moment it looks like this:

![image](https://user-images.githubusercontent.com/55212206/74032310-6d897800-4992-11ea-852f-f61fa331c568.png)

**Comment by MailYouLater** [comment]
I would venture a guess that you weren't experiencing the issue when that screenshot was taken.  I'd recommend that you try running that command again immediately after someone has received the 'blocked ip' notification, and I have a feeling it will look more like this:
![image](https://user-images.githubusercontent.com/1279475/74061699-72095d00-49a1-11ea-8e7a-7d1cdd98ba7f.png)

**Comment by MailYouLater** [comment]
@Ylianst: I am noticing an oddity about this feature.  Each time I enter incorrect login information in Firefox, the bad logins counter goes up by 1, however each time doing so in Chrome seems to increase the counter by 2.  This cuts the actual number of times that someone can try to log in in half if they're using Chrome.  Any idea why?  Can this be fixed/mitigated?

**Comment by Ylianst** [comment]
@MailYouLater Oh, interesting find! I till have to look into this.

**Comment by Ylianst** [comment]
@MailYouLater I just tested Chrome on two MeshCentral servers and I only see one bad login on each attempt. Let me know if you see this consistently, I can't make it happen on my servers.

**Comment by Ylianst** [comment]
@geanferrani123 Take a look at #945. I just added a way to log successful and failed authentication events. You should update to MeshCentral v0.4.9-g and enable this feature. You can then see exactly what is going on. Let me know if this helps.

![MC2-AuthLog](https://user-images.githubusercontent.com/1319013/74679361-7f2d0580-5172-11ea-9891-6ba7a602932a.png)

**Comment by GusevVictor** [comment]
```
> badlogins
Max is 10 bad login(s) in 10 minute(s), 10 minute(s) cooloff.
192.168.*.* - 3 records
```
Dear all how to reset ip?

**Comment by Ylianst** [comment]
The "badlogins" table will clean up on it's own after 10 minutes. I can add a reset command it you like, but that is not something that should be needed.

**Comment by GusevVictor** [comment]
> 
> 
> The "badlogins" table will clean up on it's own after 10 minutes. I can add a reset command it you like, but that is not something that should be needed.

Yes, please add an reset command. Some stupid users block all subnet from time to time :-D I know about I can add a network to white list but there is not good in my situation because I use chain of proxy...

**Comment by Ylianst** [comment]
Added `badlogins reset` to latest version of MeshCentral. Let me know if that works.

![x](https://user-images.githubusercontent.com/1319013/78415938-efd09a00-75d9-11ea-81b4-8ec7109b4bdb.png)

**Comment by GusevVictor** [comment]
> 
> 
> Added `badlogins reset` to latest version of MeshCentral. Let me know if that works.
> 
I will test it after upgrade. I'm on a production now (covid-2019) so I can't to test. Thank a lot!
