### ISSUE TITLE
bad encoding in a csv files (My events and may be other places...)

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#917]
Hi!

Step to reproduce:

login to 0.4.8-m version
Create a group with a **Cyrlic name**
Go to **My events**
See the screen (it looks like OK):

![изображение](https://user-images.githubusercontent.com/7081357/73883589-44bf9080-4875-11ea-8ab0-8260f70f1e18.png)

Export to csv and see a bad name...

![изображение](https://user-images.githubusercontent.com/7081357/73883765-923bfd80-4875-11ea-81d1-1832021bd349.png)

Thank a lot if you fix that.

Best regards. **Thank for you work to us!**

**Comment by Ylianst** [comment]
This looks like an Excel issue, the .csv file is UTF8 encoded and by default, Excel does not seem to open a file this way. [Look here for solutions](https://stackoverflow.com/questions/4221176/excel-to-csv-with-utf8-encoding). Let me know if that works, I don't think I can easily save a file in "Big-Endian UNICODE".

**Comment by GusevVictor** [comment]
Works! Thank you again and again!
