### ISSUE TITLE
Wrong time in a csv export of Events

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#918]
Hi!

Step to reproduce:

login to 0.4.8-m version
Go to My events
See the screen (it looks like OK) - it has a my local time (and I have setup a correct time zone on a linux server which runs mesh server):

![изображение](https://user-images.githubusercontent.com/7081357/73884509-117e0100-4877-11ea-986a-6283bf70c47d.png)

Export it to csv and you will see **-3 hours** (UTC in fact) from my time (Europe/Moscow ):

![изображение](https://user-images.githubusercontent.com/7081357/73884619-5b66e700-4877-11ea-9079-66f910079b74.png)

It looks like a feature but I think this is not good in compare to web interface shows a correct time.

**Comment by Ylianst** [comment]
Not really related, but published MeshCentral v0.4.8-q with the JSON formatting looking better. It's in the same dialog box as the CSV mentioned above.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-s, the csv file should have both UTC and Local time. Let me know if that works.

**Comment by GusevVictor** [comment]
> 
> 
> Published MeshCentral v0.4.8-s, the csv file should have both UTC and Local time. Let me know if that works.

THANK! It WORKS! I think you are God.
