### ISSUE TITLE
Search by ip

### ISSUE THREAD

**Issue by sdlopexvidri** [Ylianst/MeshCentral#92]
Hi, thanks for this awesom software, previusly I was using VNC for remote support, and i connect to clients by ip address, beacause is easier for the user look for an number. can I search host by ip address like VNC? or can you stamp the host name on a small icon on the tray? Thanks a lot

**Comment by sdlopexvidri** [comment]
Hi, I find another way, can you tell me how to set "tag=hostname" always?

**Comment by jsastriawan** [comment]
Adding hostname to search space is possible by modifying function at default.handlebars onSearchInputChanged().

**Comment by sdlopexvidri** [comment]
Hi, I found the function but i don't can make it work may you help me with this function? I'm modifying this:

        function onSearchInputChanged() {
            var x = Q('SearchInput').value.toLowerCase().trim(); putstore("search", x);
            if (x == '') {
                for (var d in nodes) { nodes[d].v = true; }
            } else {
                try {
                    var rs = x.split(/\s+/).join('|'), rx = new RegExp(rs); // In some cases (like +), this can throw an exception.
                    for (var d in nodes) {
                        nodes[d].v = (rx.test(nodes[d].name.toLowerCase())) || (nodes[d].rnamel != null && rx.test(nodes[d].rnamel.toLowerCase()));
                        if ((nodes[d].v == false) && nodes[d].name) {
                            for (var s in nodes[d].tags) {
                                if (rx.test(nodes[d].tags[s].toLowerCase())) {
                                    nodes[d].v = true;
                                    break;
                                } else {
                                    nodes[d].v = false;

**Comment by sdlopexvidri** [comment]
HI, jsastriawan Thanks a lot I found and solve my problem. thanks

**Comment by sdlopexvidri** [comment]
Hello, jsastriawan, I update to 0.2.9p, This reversed the changes I made in default.handlebars, I did them again but it never worked again, can you tell me if there is any change in the hostname variable?

**Comment by jsastriawan** [comment]
Here is my modification that I tested on my instance. See: https://github.com/Ylianst/MeshCentral/blob/master/views/default.handlebars#L2702 

`
nodes[d].v = (rx.test(nodes[d].name.toLowerCase())) || (nodes[d].rnamel != null && rx.test(nodes[d].rnamel.toLowerCase()) || (nodes[d].host !=null && rx.test(nodes[d].host.toLowerCase())));
`

@Ylianst, are you able to accommodate this into the code? I believe this is very relevant for subnet-based filtering.

**Comment by sdlopexvidri** [comment]
I would be very grateful if you could apply this type of filter to the program

**Comment by Ylianst** [comment]
FYI. In the latest MeshCentral v0.3.0-n, you can now type "ip:192.168.2.3" in the filter box to filter devices that use that IP address when connecting to the server. Feedback on this appreciated.

![MC2-IPFilter](https://user-images.githubusercontent.com/1319013/54466899-4a812480-473f-11e9-9230-3c9c7b32f029.png)

**Comment by sdlopexvidri** [comment]
Thank Ylianst this is very useful for me
