### ISSUE TITLE
Chat certificate

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#921]
I have a FQDN with a lets encrypt certificate

connecting to the web gui of my mesh uses my certificate
connections via mesh port uses my certificate

Chat connections seem to use  a self signed certificate from meshcentral server
![image](https://user-images.githubusercontent.com/7231493/73918740-e98dac80-490d-11ea-8810-277d22c39413.png)

**Comment by Ylianst** [comment]
Without showing us your domain name, can you give me an example of the URL for the WebGUI, MeshPort and Chat? Are they all for the same DNS name and port?

**Comment by OutbackMatt** [comment]
hmmm
Thanks for the hint.

When I add port 433 as 'AliasPort' in json.config  it works fine
(I reverse proxy through my Apache server wss on port 433)
