### ISSUE TITLE
Agent problem

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#922]
Hello,
every 2-3 days the same server with the same ip appears as new.... i run Meshcentral in Windows
why is that?
![123](https://user-images.githubusercontent.com/10504401/73927719-93ebdc80-48da-11ea-80f2-1cd8bc5722e0.jpg)

thanks

**Comment by vitko-bg** [comment]
There is a open ticket for this issue: #774

**Comment by coolwormgit** [comment]
ok thanks!!!
