### ISSUE TITLE
Server Version Unknown

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#923]
This morning check for new Server version i get :
![123](https://user-images.githubusercontent.com/10504401/73927889-e200e000-48da-11ea-8728-5e53e2e51a6f.jpg)

I have Windows Meshcentral

thanks

**Comment by PathfinderNetworks** [comment]
I upgraded to 0.4.8-q from 0.4.8-e last evening and am seeing this same thing.

**Comment by Ylianst** [comment]
Oh dear. Working on it now. @PathfinderNetworks are you also on Windows?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-r with a fix for this, seems it was only a problem on Windows. Let me know if it works.

**Comment by coolwormgit** [comment]
i still get unknown version.. how to update with fix??

**Comment by Ylianst** [comment]
Just in case it's not obvious, if you run into this problem and can't update using the easy method anymore, you need to perform a manual update.

- Stop the MeshCentral service.
- Go in the folder above "node_modules" with a command shell. On windows it's "C:\program file\open source\meshcentral".
- Type `npm install meshcentral`, wait until done.
- Start the MeshCentral service again.

Once you get the new update, the easy web based update should work again. Feedback appreciated.

**Comment by coolwormgit** [comment]
i just downloaded meshagent  installer and selected update.. :)

**Comment by Ylianst** [comment]
ha yes, using the MeshCentral Windows Installer to update the server also works.

**Comment by PathfinderNetworks** [comment]
Hi Ylian,
Yes, I am running it on Windows (Server 2019).  The 0.4.8-s update did resolve this.  Thanks!

**Comment by Ylianst** [comment]
Excellent. From now on, NodeJS and NPM don't need to be in the "PATH" for MeshCentral to check and upgrade anymore, this is especially useful on Linux, but could also be of benefit on Windows on some cases.
