### ISSUE TITLE
Tag Management and CSV Export of Selection

### ISSUE THREAD

**Issue by ghplw** [Ylianst/MeshCentral#926]
Can we please have:

- A tag managment area where we can see, create, rename and delete any tag.
- Ability to add tags to selected devices via the Group Action button.
- Ability to export a list of selected devices to a CSV via the Group Action button.

Example Usage:

I create tags for the sites, postcodes and states for all of my customers. A customer calls up and reports that there is no internet. I want to see if the outage is affecting a larger area or site and so I filter by one of the location tags I have set, select all the results then export to a CSV.

I then check to see if all the devices in that area are showing as offline at the time of the report and I should be able to get an idea of when they went offline by the Last Seen time.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.8-w with new device export feature in "Group Action". Can you give it a try and let me know your feedback.

![MC-DeviceExport](https://user-images.githubusercontent.com/1319013/74191873-4688ab80-4c09-11ea-832a-75515f7b5fd2.png)

**Comment by desarrollocdb** [comment]
It does not work for me.

CSV is blank

**Comment by Ylianst** [comment]
Your right. CSV device export works on the English web page, but not in the Spanish one. Looking at this now.

**Comment by Ylianst** [comment]
Thanks for reporting this. I just fixed it and it will be in MeshCentral v0.5.38 when it is published.

**Comment by openmoto** [comment]
Looks great.
Thanks for the new feature, works for me here v0.5.37 (English).
Any plans of adding more information on the exported data? 
Something like CPU, Hard disk and Ram information as well as AV status.

Thanks

**Comment by frankmcc** [comment]
Perhaps we can have a listing of existing tags, perhaps in a drop down list or other method.  It would be nice to keep tags consistent among the entire team.

**Comment by tiikej** [comment]
Is possible to generate computer reports with tags.
This will be very helpful to create customer statistics.
Can you add this feature.

P.S. I tried generate various report but all was be without tags.

**Comment by si458** [comment]
@tiikej are you talking about the csv export in `device information export` or the `reports` tab under `My Events` ?

**Comment by tiikej** [comment]
I'm talking about the csv export in device information export.

**Comment by si458** [comment]
all done, PR for you 👍
