### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by treicadani** [Ylianst/MeshCentral#928]
Hi Ylian,

After i've upgraded to 0.4.8-f when i connect to desktop, terminal or files i keep getting disconnected after 60 seconds while i'm in the middle of doing work and not inactive using a Windows 10 Pro PC, however using a linux PC it doesn't timeout.

The only trace i get back is : 13:56:05 - RELAY: Relay disconnect: xxxxxxxxxxx (IP FROM --> IP TO)

UPDATE: The timeouts seem to only happen in Chrome for windows. using Edge will not timeout the connection.

Our users need to be connected for long sessions and not be disconnected after 60 seconds.

And can we add as standard WIN + D keys combinations? To show the desktop.

Many thanks

**Comment by si458** [comment]
closing as stale and possibly fixed now
