### ISSUE TITLE
Unable to parse config.json on Ubuntu 18.04

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshCentral#93]
After updating to the newest version, im unable to start MeshCentral on Ubuntu 18.04. Im getting "Unable to parse config.json".

When i roll back to 0.2.7-p, everything works fine again.

Steps to reproduce:
- fresh install of MeshCentral on Ubuntu 18.04
- node meshcentral --cert mydomain.com
- server is starting fine
- quit MeshCentral
- start MeshCentral again
- Unable to parse config.json, doesnt start
- roll back to 0.2.7-p
- works fine again

**Comment by Ylianst** [comment]
Published MeshCentral v0.2.8-a just now to fix this. My sample config.json file was not correct. Thanks for reporting it. Please check and close if fixed.

**Comment by marco-vogt** [comment]
Fixed, thank you!
