### ISSUE TITLE
Wake-up does not work anymore ....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentral#930]
Not sure from which version exactly( i think from 0.4.8-m) device wake-up stopped working for me.
Was using it every day couple of times a day - and suddenly it has stopped working....
Will double check it tonight as it is very important for me .....

**Comment by MailYouLater** [comment]
It's working for me in v0.4.8-t.
Note: That feature uses the other devices in the same device group to send a Wake On LAN to the specified computer.  This may not be your issue, but if there are no computers in the same device group that are also on the same LAN, it won't be able to function.

**Comment by vitko-bg** [comment]
@MailYouLater You are right - that was it! There are 2 computers only and 1 of them was off for last couple of days. Now all looks fine. Have not tested it again - anyway need both PCs up and running.
