### ISSUE TITLE
Remote Firefox go to first tab from time to time

### ISSUE THREAD

**Issue by GusevVictor** [Ylianst/MeshCentral#931]
Step to repeat:

- login to 0.4.8-s from Windows 10 + Firefox 68 ESR
- Connect to Windows 10 clt
- Open Firefox 68 ESR (on a remote side) 
- Open 2...n tabs
- Work in not first tab
- After some work you will move to first tab

There is another bugs... For example, when you long work with eclipse you will strange bug from time to time - like open dialog about exit from eclipse.

The problem with firefox repeats on many workstation.

Thank a lot for you interes to this problem.

**Comment by Ylianst** [comment]
What is "Windows 10 ctl"?

So, you open many tabs on the remote machine using FireFox, do work on the second time and suddenly the first tab gets selected on the remote machine? How long do you have to "work" to see this problem?

**Comment by MailYouLater** [comment]
"Windows 10 clt" is probably supposed to mean "Windows 10 client".

**Comment by GusevVictor** [comment]
> 
> 
> "Windows 10 clt" is probably supposed to mean "Windows 10 client".

Yep :)

**Comment by GusevVictor** [comment]
> So, you open many tabs on the remote machine using FireFox, do work on the second time and suddenly the first tab gets selected on the remote machine? How long do you have to "work" to see this problem?

Yes. Just open two or more tabs. Active work beetwen **5-30 minutes** and you will switch to a first tab. When we have tested mesh my collegs tell me about that... It was very strange for me. I have tested it by myself with the same result.

**Comment by GusevVictor** [comment]
Hi! The problem still here. Will be nice to have any news. I'm sure there is problem not with Firefox only.

Please rename the topic from Girefox to Firefox for best search result. Thank.

**Comment by MailYouLater** [comment]
@GusevVictor: You should be able to edit the title yourself.

**Comment by si458** [comment]
closing as stale,
please try the latest version 1.1.24
