### ISSUE TITLE
IDER/Storage Redirection source entries reversed

### ISSUE THREAD

**Issue by ndroftheline** [Ylianst/MeshCentral#932]
Windows 10 client, running current binary release of MeshCommander. Connect to computer, click IDER button. Under "Storage Redirection" dialog box, in the Source dropdown: 
- selecting "ISO from file, IMG from drive" presents a drive picker for ISO and a file picker for IMG. 
- Selecting "ISO from drive, IMG from file" presents a file picker for ISO and a drive picker for IMG. 

These options are backwards. "ISO from file..." should present a file picker for ISO, not a drive picker. "ISO from drive..." should present a drive picker for drive to map, not a file picker.

**Comment by Ylianst** [comment]
Your right, fixing this now...

**Comment by Ylianst** [comment]
Just uploaded a new MeshCommander v0.8.0 with a fix for this. I did not update the version number, so you need to uninstall/download/install again. Let me know if this works.

**Comment by Ylianst** [comment]
Closing this as I am pretty sure I fixed this. Please re-open if needed.
