### ISSUE TITLE
mc2 add agentless , nothing happens

### ISSUE THREAD

**Issue by bob454522** [Ylianst/MeshCentral#933]
Hi,  ive installed mc2 0.4.8-u on a win7 64 box -

I have 2x Dell Optiplex 7060 boxes that both support AMT (and its fully configured, i can access the dell units at http://IP:16992/ )

**in mc2 when i create a "agent-less" group, then click "add one"  and fill in the details (using an IP address for both "Device Name" and "Hostname") , then click OK ,  nothing at all happens**

I have tried this on several different browsers, and on browsers on different win machines (same result always).
I have tried enabling all the Tracing options (MyServer->Trace), and while ofcouse I see output when im loading the page, when i click the OK button to add a agent less device,  nothing shows up in the traces (and ofcouse no device is added).
I have also tried putting in totally bogus info and clicking OK (expecting an error or something)- nothing.

_Its as if my input in not being sent from browser to mc2 web server, when i press OK on adding a device._  Any ideas?  
(or is no output / trace normal, even when mc2 cant connect to a AMT box for any reason)

thanks

**Comment by jsastriawan** [comment]
If you are in WAN only mode, this will happen. To ensure it also recognize LAN, add Wanonly to false in config.json. See user guide on the options you can set.

**Comment by bob454522** [comment]
that was the issue, thanks for fast reply!

while most machines i admin are over a constant VPN, i wanted the flexibility if needed to use WAN/pubIP one day, thus why i chose WAN.  But now changing it to Hybrid, fixed issue.  very cool!  thanks
