### ISSUE TITLE
auto update not working

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#94]
Even though auto update is set to true in my config.json file, I'm still having to update manually.
![mc2](https://user-images.githubusercontent.com/47568278/52647790-345f1a80-2e9a-11e9-9e6d-e10287c04fc4.png)

**Comment by whalehub** [comment]
As far as I know, the auto updater runs at midnight, not the moment a new update is released.

**Comment by FATeknollogee** [comment]
I've had auto update enabled for a few days.

**Comment by FATeknollogee** [comment]
23 hours later, looks like auto update did not "update"
![2019-02-13_07-14](https://user-images.githubusercontent.com/47568278/52721733-2c1ce300-2f5f-11e9-8139-ba1dd66526ac.png)

**Comment by FATeknollogee** [comment]
This is now working as it should.
