### ISSUE TITLE
psoutXXXXXXXXXXXXX.txt files in Mesh Agent folder on a client computer

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#940]
On a windows machine, with MeshAgent installed, I often see a few 0 byte files of the form

psoutxxxxxxxxx.txt

in the folder C:\Program Files\Mesh Agent\

On one machine I just found 1316 such files, most 0 bytes, with 8 files with some content, as large as 26 Kb. 9 files in total, size is 40.5 KB.

Contents of one file
`[{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803880211)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803880211)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803880211)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803854071)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803854071)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803854071)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853846)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853846)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853846)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853610)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853610)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853610)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853381)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853381)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853381)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853168)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853168)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803853168)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852949)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852949)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852949)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852737)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852737)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852737)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852514)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852514)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852514)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852287)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852287)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852287)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852068)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852068)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803852068)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851851)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851851)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851850)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851629)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851629)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851629)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851414)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851414)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851414)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851193)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851193)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803851193)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850974)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850974)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850974)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850755)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850755)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850755)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850537)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850537)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850537)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850318)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850318)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850318)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850107)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850107)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803850107)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849886)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849886)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849886)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849661)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849661)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849661)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849445)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849445)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849445)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849229)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849229)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849229)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849003)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849003)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803849003)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848783)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848783)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848783)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848565)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848565)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848565)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848360)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848360)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848360)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848140)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848140)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580803848140)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793818009)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793818009)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793818009)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793817843)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular logical range.","Id":258},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793817843)\/","ProviderName":"Win32k","Message":"A pointer device reported a bad angular physical range.","Id":257},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580793817843)\/","ProviderName":"Win32k","Message":"A pointer device did not report a valid unit of angular measurement.","Id":265},{"LogName":"System","Level":2,"TimeCreated":"\/Date(1580757570683)\/","ProviderName":"Service Control Manager","Message":"The Mesh Agent background service service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.","Id":7031},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580750099426)\/","ProviderName":"Microsoft-Windows-Time-Service","Message":"NtpClient was unable to set a manual peer to use as a time source because of duplicate error on \u00270.pool.ntp.org\u0027. The same time source \u00272.pool.ntp.org\u0027 has been either specified as manual peer in NtpServer or selected as domain peer.  NtpClient will try again in 960 minutes and double the reattempt interval thereafter. The error was: The entry already exists. (0x800706E0)","Id":135},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580731770273)\/","ProviderName":"disk","Message":"An error was detected on device \\Device\\Harddisk3\\DR130 during a paging operation.","Id":51},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580731770273)\/","ProviderName":"disk","Message":"An error was detected on device \\Device\\Harddisk3\\DR130 during a paging operation.","Id":51},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580731770273)\/","ProviderName":"disk","Message":"An error was detected on device \\Device\\Harddisk3\\DR130 during a paging operation.","Id":51},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580731770273)\/","ProviderName":"disk","Message":"An error was detected on device \\Device\\Harddisk3\\DR130 during a paging operation.","Id":51},{"LogName":"System","Level":3,"TimeCreated":"\/Date(1580731770271)\/","ProviderName":"disk","Message":"An error was detected on device \\Device\\Harddisk3\\DR130 during a paging operation.","Id":51}]`
It's like these are 'events'...

This machine has external drives attached and removed every day

**Comment by OutbackMatt** [comment]
I've simply deleted these files, really just mentioning that there are MANY of them

**Comment by MailYouLater** [comment]
I've been very curious about these, as I've seen them on a few machines too.  I haven't bothered trying to figure anything out yet, but I'd really like to know what they are and why they're there.

**Comment by Ylianst** [comment]
Bryan must have left debugging code in that agent. Thanks for reporting.

**Comment by MailYouLater** [comment]
Oh, I've enabled some of the debugging options by adding lines to the `.msh` files on some of my computers while trying to troubleshoot for other issues, and I don't think I've turned them all off again on all of my computers.  I don't know if the ones that have these files on them are the same ones that I've enabled debugging options on or not.  Either way, any chance you could explain what they are?

**Comment by krayon007** [comment]
That doesn't look like a log message that the agent would've generated, as I don't recognize that format. All the agent logs would end in a .log or .jlog, and would be a CRLF delineated file with a timestamp in square brackets on each line.

psoutxxxx.txt sounds kind of like powershell... By any chance are you running PS scripts, that could be generating logs?

**Comment by ryanblenis** [comment]
Jumping in here. The psoutXXXX files are files used by my EventLog plugin. No need for Ylian or Brian to spend any time looking at this!

**Comment by MailYouLater** [comment]
Oh, ... OK. @ryanblenis, could _you_ explain what they're for and why they're there then?

**Comment by ryanblenis** [comment]
They're temporarily where the event logs are stored (in JSON format) before the agent ships them up to the server (hence why @OutbackMatt's attached file has event logs in it - might want to run a DFT on that HDD!)

**Comment by Ylianst** [comment]
Oh good! I am happy you jumped in. I was puzzled as to what could be going on.

**Comment by ryanblenis** [comment]
Released version 0.0.22 of EventLog to better track and cleanup these temp files. It doesn't clean up existing files, but if anyone needs something to do this I can certainly implement it, otherwise a `del psout*.txt` from cmd should get them all

**Comment by OutbackMatt** [comment]
I get these errors each time I try an enable the log files

It may be permissions at my end
I do have LICENCE owned by 'mesh|mesh' with 0644 permissions, I've also tried 0755 and got same errors

Thanks for your work

```
ERR: events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/etc/meshcentral/meshcentral-data/plugins/eventlog/LICENSE'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:734:7)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
ERROR: Unable to write to mesherrors.txt.
{ Error: Command failed: /usr/bin/node /etc/meshcentral/node_modules/meshcentral --launch 9070
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/etc/meshcentral/meshcentral-data/plugins/eventlog/LICENSE'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:734:7)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:203:15)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/usr/bin/node /etc/meshcentral/node_modules/meshcentral --launch 9070' }
ERROR: MeshCentral failed with critical error, check MeshErrors.txt. Restarting in 5 seconds...

```

**Comment by ryanblenis** [comment]
Hi @OutbackMatt 

What log files are you attempting to enable here? 

And when do you see this error, when trying to update the EventLog plugin?

**Comment by OutbackMatt** [comment]
I've had to disable the plugin

when I enable it, my mesh server crashes every few seconds
starts as soon as I 'refresh agent cores'

**Comment by ryanblenis** [comment]
Hi @OutbackMatt 

Sorry to hear that. 

1. Is that with EventLog 0.0.22 or previous? 

2. Which log files were you attempting to enable and by what means?

3. Are there different errors with the crashing you mentioned in your last post versus the previously supplied error logs? If so, were you attempting to upgrade the plugin when the original errors occurred?

I can't seem to repeat it. Given the separate user I assume this is a "secure" install per the MeshCentral documentation? What OS is the server running on? Is SELinux enabled?

**Comment by OutbackMatt** [comment]
I was on 0.0.21, trying to upgrade cause the crash.
I honestly can't remember what logging I had enabled.

I was running on 0.0.21, then I tried to upgrade to 0.0.22 and then I've had to disable. My options now are to 'install' or 'delete'

**Comment by ryanblenis** [comment]
From the errors being permission related it appears to be environmental rather than plugin or MeshCentral, but without answers to some of those questions I can't replicate it. Anything you can offer by way of my previous questions would be helpful.
