### ISSUE TITLE
Files >> Edit

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#941]
Just noticed that if I go to a machine and select files> then a file and then > edit
That the contents are remembered and not refreshed

ie I want to modify multiple files of the same name, in this case C;\program files\mesh agent\Meshagent.msh, where I want to remove the port from the meshserver line (so that default port 443 is used) 

I open the file on one machine > edit fine
Open same file on second machine and contents of first machine file is shown (with port already removed)

**Comment by MailYouLater** [comment]
Sounds similar to the issues that had to be fixed in the later comments of #719.  This may be a regression.

**Comment by Ylianst** [comment]
Oh dear. I will look at this tomorrow.

**Comment by Ylianst** [comment]
I see the same problem... working on it now.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-a with a fix for this. Let me know if it works.

**Comment by OutbackMatt** [comment]
Now I can't seem to save the changes made in the edit

**Comment by Ylianst** [comment]
!!!

**Comment by Ylianst** [comment]
Just tested it on FireFox and Chrome and the save works for me. Obviously, the MeshAgent must have sufficient rights to write the file. Is the remote machine Windows or Linux?

**Comment by OutbackMatt** [comment]
Just did some more testing, and Waterfox (Firefox offshoot) and Chrome work
Edge doesn't

My workstation is a Windows 10 Pro machine, my MeshServer is in Ubuntu 18.06 
Remote machines are a mix of Windows 7, 10, Server 2012R2 and Server 2016 mostly

**Comment by Ylianst** [comment]
Ha! Thanks. That helps a lot. I will test with Edge.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-d with a fix for IE and other older browsers. Let me know if that works.

**Comment by OutbackMatt** [comment]
Edge works fine thanks
