### ISSUE TITLE
Session Player URL path returns 404: Not Found

### ISSUE THREAD

**Issue by whalehub** [Ylianst/MeshCentral#942]
I upgraded from MeshCentral v0.4.8-e to v0.4.9-a earlier today and noticed that when I visit the /player.htm path on my domain, the browser returns a 404: Not Found page instead of the expected Session Player. The same path worked fine prior to the upgrade.

**Comment by Ylianst** [comment]
I did change how the player is served to make translatable to different languages and made it a .handlebar since I am working on better integration. Weird... Can you enable "WebRequest" tracing and request the player.htm and let me know what you see?

![x](https://user-images.githubusercontent.com/1319013/74274926-c9703b80-4cc7-11ea-8281-e956319f9f0b.png)

**Comment by Ylianst** [comment]
By the way, I am working on having the player be able to "seek" anywhere inside a .mcrec file now. It requires that the .mcrec file be "indexed" by making a run thru the file and setting up time stamps, etc. Once that is done, the player should be able to move anywhere thru the file.

**Comment by MailYouLater** [comment]
Looks like an issue with the redirect from http to https.

**Comment by Ylianst** [comment]
Oh right... there is no redirection from HTTP. I can add it.

**Comment by olivier37520** [comment]
Same for me after updating from 0.4.8-e to 0.4.9-a, 
server tracking doesn't show anything relevant.
![Capture du 2020-02-11 22-32-26](https://user-images.githubusercontent.com/6954741/74281472-ce140e80-4d1e-11ea-906f-d348d4200f39.png)
and the page produced is just this
![Capture du 2020-02-11 22-33-24](https://user-images.githubusercontent.com/6954741/74281603-07e51500-4d1f-11ea-8ba1-1a16e6e32ba8.png)
I'm using meshcentral with nginx, and https.

**Comment by Ylianst** [comment]
Are you using a "meshcentral-web" folder?

**Comment by olivier37520** [comment]
no, just default install

**Comment by Ylianst** [comment]
Thanks. I will investigate.

**Comment by olivier37520** [comment]
the bug is in webserver.js line 2091 
`if ((domain == null) || (domain.redirects == null)) { res.sendStatus(404); return; }`
domain.redirects is undefined and the function returns a simple 404 status error

**Comment by Ylianst** [comment]
Thanks you. It's so much better when I get the answer :) Published MeshCentral v0.4.9-c with the fix.

**Comment by whalehub** [comment]
I can confirm that the problem has been fixed in the latest version.

**Comment by whalehub** [comment]
@Ylianst I can confirm that the problem has been fixed in the latest version.
