### ISSUE TITLE
Edit files - suggestions

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#943]
Love being able to edit files and run commands remotely while a workstation is in use, and not interrupting the regular user.

Love it, love it, love it.

If I could make a wish list for some improvements
#1 a right click context option to edit, rather then needing to select the file, then the edit button.

#2 Text files and batch files look fine, but xml files display the names not the special characters.
Left hand side MeshCentral Edit = right hand side same file downloaded and viewed in Notepad++

I imagine that php files and js files look similar.

The colours aren't that important to me, but the 'name for symbols' rather than symbols is a pain to read
![image](https://user-images.githubusercontent.com/7231493/74303692-73be9080-4da6-11ea-9120-c54631a2fb68.png)

**Comment by MailYouLater** [comment]
> 1. a right click context option to edit, rather then needing to select the file, then the edit button.

Another option would be to add an 'edit' link next to the download link on supported (less than 200k) files.
> 2. ... xml files display the names not the special characters.
> ... the 'name for symbols' rather than symbols is a pain to read

Displaying `<` and `>` as html entities is definitely not intentional. That's definitely a bug.

**Comment by Ylianst** [comment]
Yes, that is a bug. I will also look at making edit easier.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-e that fixes the < and > problem, let me know if it works.

**Comment by OutbackMatt** [comment]
Yes thanks -works as expected

**Comment by Ylianst** [comment]
I just added a right click context menu for files in the device "Files" tab. You can select "Rename", "Edit" and "Delete". Let me know if that works. It's in MeshCentral v0.4.9-f.

**Comment by MailYouLater** [comment]
Works for me.

**Comment by OutbackMatt** [comment]
Works for me too
