### ISSUE TITLE
MeshAgent uncaught exception error - version 0.4.9-d

### ISSUE THREAD

**Issue by nlyaple** [Ylianst/MeshCentral#946]
The device is a Linux box running Peppermint 6 32bit.  I cannot connect to the device via Terminal or Files tab.  I can only access it via the Console tab.  When attempting to connect the Terminal, the following appears in the Console window:

uncaughtException1: Error: => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: cannot write property [Symbol hidden '?_Agent_SocketJustCreated'] of 'DNS[-xx-xxx-xxx-xxx.us...' in method 'handleServerCommand()'

Please let me know if you need anymore details.

**Comment by nlyaple** [comment]
I also tried clearing the core, reloading the default core and clearing the core and trying the recovery core.  It did not make a difference.  The trace shows Relay holding - Authenticated and Relay disconnect messages only.

**Comment by krayon007** [comment]
What's your server configuration, WAN, LAN, or Hybrid?
On my WAN mode setup, with Peppermint 6 32-bit, it seems to work fine. Based on your error, it looks like something going on with the DNS screwing up for the tunnel sessions. I'll test the other modes, and see if it's related... Are you only seeing this on Peppermint 6-32bit?

**Comment by nlyaple** [comment]
Hi Bryan,
   
  
  
       This is one site in Iowa that is fairly remote.  It is managed by an outside IT group so I don't know how it is configured but it looks like we are having DNS failures.  Our REST API cannot communicate and it uses a URL. Our other sites are working normally.  The server configuration is WAN only. The console command are working.  Let em know if there is anything you would like me to try.
   
  
  
   Thanks,
   
  
  
   Nelson
   
  
  
   
    On February 13, 2020 5:37 PM Bryan Roe <notifications@github.com> wrote:
   
   
    
   
   
    
   
   What's your server configuration, WAN, LAN, or Hybrid?On my WAN mode setup, with Peppermint 6 32-bit, it seems to work fine. Based on your error, it looks like something going on with the DNS screwing up for the tunnel sessions. I'll test the other modes, and see if it's related... Are you only seeing this on Peppermint 6-32bit?

**Comment by krayon007** [comment]
OK, I fixed the uncaught exception. However, this error case is only triggered if the DNS resolve fails. So while the exception will be fixed, you still won't be able to connect to files/terminal/kvm, becuase the hostname resolve failed.

Does your hostname really start with: -xx-xxx-xxx-xxx.us ? That seems peculiar....

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-m that has Bryan's all new MeshAgents for all platforms and includes the exception handling for this. However, if the DNS name is not correct, the agent will still not connect, but the agent should behave better now. Let me know if that works.
