### ISSUE TITLE
Adding ACM to (Sub-) Domains

### ISSUE THREAD

**Issue by FKuypers** [Ylianst/MeshCentral#949]
Hi,

I got AmtACMActivation working for my default domain. I now created another Domain in the "Domain" section of the config.json.

Unfortunatelly I can only select "CCM" in this subdomain. In general I would like to use another certificate in this domain anyway with a different trusted suffix to be added in the ME.

Where and how would I enter additional certificates to enable ACM in a seperate domain?

Thanks,

Frank

**Comment by Ylianst** [comment]
I never tested that, but this is a good request. I will work on it.

**Comment by Ylianst** [comment]
I took a quick look at this and it works for me. Can you take a look at your config.json and make sure you have a "AmtAcmActivation" section in both your domains? (example below) It's ok if you replicate the same "AmtAcmActivation" settings for both domains and use the same certificates for both, but you will need to add a "AmtAcmActivation" to each domain you want to use Intel AMT activation for. Let me know if this works.

```
{
  "settings": {
    "port": 443
  },
  "domains": {
    "": {
      "AmtAcmActivation": { ... }
    },
    "customer1": {
      "AmtAcmActivation": { ... }
    }
  }
}
```

**Comment by FKuypers** [comment]
I tried this before, I do get an error:
ERROR: Unable to parse /home/default/meshcentral-data/config.json.

I basically added it after the _CertUrl in the subdomain section:
```
      "_CertUrl": "https://192.168.2.106:443/"
      "AmtAcmActivation": {
        "log": "demoamtactivation.log",
        "certs": {
          "": {
            "certfiles": [ "AMT_imu-lab.crt", "pve_root.crt" ],
            "keyfile": "AMT_imu-lab.key"
          }
	
        }

```
Frank

**Comment by Ylianst** [comment]
Nice! Thanks for the report.
