### ISSUE TITLE
Agent support for Server 2008 R2

### ISSUE THREAD

**Issue by FATeknollogee** [Ylianst/MeshCentral#95]
Agent is installed on Server 2008 R2 but server does not show in MC console?
I assume this os is supported?

**Comment by krayon007** [comment]
Which version of Server 2008 R2 you have installed? I just tested with Server 2008 R2 Standard, and it seems to work fine...

Can you run the agent in console mode, to see if there is any pertinent information showing? I'm guessing it simply cannot reach the server for whatever reason...

**Comment by FATeknollogee** [comment]
Server 2008 R2 Standard also.
Let me check in console mode.

**Comment by FATeknollogee** [comment]
Agent is running
![mcagent](https://user-images.githubusercontent.com/47568278/52662407-fae9d780-2eb8-11e9-81e1-a44248ac746f.png)

**Comment by FATeknollogee** [comment]
![2019-02-12_15-20](https://user-images.githubusercontent.com/47568278/52674865-bc184980-2ed9-11e9-8db2-806749b52994.png)

**Comment by krayon007** [comment]
By any chance is there supposed to be a proxy configured between your agent and your server? Or are you using a reverse proxy on your server by Traefik?

**Comment by FATeknollogee** [comment]
No proxy is used.

**Comment by krayon007** [comment]
Does it hang there indefinitely? (ie, does it report a connection error after about 15-20 seconds?)

**Comment by FATeknollogee** [comment]
It just hangs, never reports a connection error.

**Comment by krayon007** [comment]
Ok, I will add some debug instrumentation to the agent, and make it so you can flip it on or off with a db key... Ylian thinks the agent is connecting, but failing during the handshake with the server. The current agent, will only display a message after the authentication completes...

I'll let you know when the instrumentation is ready, so you can give it a whirl, to see if we can figure out what is failing...

**Comment by krayon007** [comment]
Ok, while adding the instrumentation, I noticed that if the websocket connects, the first thing that it does, it write a message indicating what the idle timeout is:

2019-02-14 02:30:52 PM: Control Channel Idle Timeout = 120 seconds

Based on this, that means your agent isn't actually able to connect to the server. By any chance are you able to get a wireshark trace or something, to see what is happening? Perhaps a TLS handshake error or something....

**Comment by FATeknollogee** [comment]
Ok, let me install the agent on another 2008R2 host & see if that’ll connect.

^ sent from the world famous iPhone XS max ^

**Comment by Ylianst** [comment]
I am going to close this issue since we don't plan to support older versions of Windows. If there is a specific request around help, please don't hesitate to re-open or file a new issue.
