### ISSUE TITLE
2FA Needed Every Server Restart?

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshCentral#953]
Hi @Ylianst ,

It seems that even though I check "remember this device for 30 days", if I update or restart MeshCentral I need to re-enter my 2FA key after every restart.

I'm not sure if this is intended functionality or not (if so, please let me know, otherwise I think the 30 days should be honored between reboots).

In trying to pin the issue down, it appears the 2FA cookie check returns the error:

`COOKIE: ERR: Bad AESGCM cookie due to exception: Error: Unsupported state or unable to authenticate data`

being thrown by line ~2081 of meshcentral.js:

`const o = JSON.parse(decipher.update(cookie.slice(28), 'binary', 'utf8') + decipher.final('utf8'));`

by the decipher.final() call.

More details by adding an err.stack call to the catch where this is caught:

```
COOKIE: ERR: Bad AESGCM cookie due to exception: Error: Unsupported state or unable to authenticate dataError: Unsupported state or unable to authenticate data
    at Decipheriv.final (crypto.js:183:26)
    at Object.CreateMeshCentralServer.obj.decodeCookieAESGCM (/home/mc/meshcentral/node_modules/meshcentral/meshcentral.js:2081:97)
    at Object.CreateMeshCentralServer.obj.decodeCookie (/home/mc/meshcentral/node_modules/meshcentral/meshcentral.js:2042:21)
    at checkUserOneTimePasswordRequired (/home/mc/meshcentral/node_modules/meshcentral/webserver.js:537:54)
    at /home/mc/meshcentral/node_modules/meshcentral/webserver.js:689:55
    at /home/mc/meshcentral/node_modules/meshcentral/webserver.js:432:36
    at PBKDF2.ondone (/home/mc/meshcentral/node_modules/meshcentral/pass.js:31:88)
```

Using:
MeshCentral v0.4.9-i, 2FA - Google Authenticator

Also noting that the `twofactor` cookie is indeed available via Chrome inspection tools prior to logging in.

UPDATE for those with the same issue:

Digging into the code, I noticed the decode key was `null` while decoding the cookie (and encoding) which lead me to find reference to the `allowlogintoken` config.json setting. After adding this to the config, the 2FA "Remember" function worked as expected between MeshCentral restarts.

So I guess my questions are these for future users who run into this issue:
1. Is the "Remember Device" function supposed to work between restarts / updates?
2. What is the intended functionality of the allowlogintoken setting in the config.json (both on its own, and in relation to 2FA "Remember Me" functionality?

Thank you!

**Comment by ryanblenis** [comment]
Ok, so I checked the updated documentation (glad it's added to the repo now) which says the following about AllowLoginToken:

`
By default is set to ‘false’. If set to ‘true’, the server allows login tokens to be used in the URL as a replacement for user login. This is useful along with “allowFraming” option to embed MeshCentral features into another website.
`

which tells me this should not be intended behavior, and that the 2FA being forgotten between reboots without this setting may be a bug. Thoughts welcome. Thank you.

**Comment by Ylianst** [comment]
By default, the session encryption key is created at random when the server starts, so older cookies will no longer work. This is not just 2FA, you need to login again even without 2FA. Add this line to the "settings" section of config.json:

`"SessionKey": "MyReallySecretPassword"`

Make sure to use a really big and random string, feel free to use a random generator. Fun fact about this value, you need to set it if your going to use MeshCentral server peering as one server's cookie needs to be decoded by the other servers. Let me know if this works.

**Comment by ryanblenis** [comment]
Hi @Ylianst,

Yes, adding the session key also fixes the problem.

And I understand needing to re-login after a restart, but not the 2FA token not being remembered (unless of course the cookie is encrypted with a unique session key each time the server starts as you say).

If this is the case then I believe there would still be a bug to fix, because I could also solve it by only adding allowlogintoken: true to the config, then I would also not be re-prompted for a 2FA token after a restart. Otherwise that means the sessionkey option is implied when allowlogintoken is enabled, correct?

**Comment by Ylianst** [comment]
Ha, your right. Fixing that now. 2FA should work even if "allowlogintoken" is not set to true.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.9-j with a fix for this. No need to "allowlogintoken" anymore.

**Comment by ryanblenis** [comment]
Just wanted to clarify, as your last message might be construed to imply that allowlogintoken is (erroneously) required to allow 2FA "Remember" functionality.

Carification:
 2FA's "Remember this device for 30 days" function works correctly if *either* of the following are true:

- allowlogintoken is set
- sessionkey is set

It does *not* work when both allowlogintoken and sessionkey are unset

**Comment by ryanblenis** [comment]
Confirmed that this now works as expected. Thank you as always!
