### ISSUE TITLE
MeshCentral crashes after disconnecting client with recording on

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#957]
I started an session with an pc, with recording on, when i disconnect the remote session my meshcentral server crashst, in the logfile the following error is recorded

---------------------------------------------------------------------------------------------------
/home/administrator/node_modules/meshcentral/certoperations.js:857
            program.processMessage({ action: operation, data: data, tag: tag, func: func });
                    ^

TypeError: program.processMessage is not a function
    at Object.obj.acceleratorPerformOperation (/home/administrator/node_modules/meshcentral/certoperations.js:857:21)
    at recordingEntry.ws (/home/administrator/node_modules/meshcentral/meshrelay.js:340:112)
    at /home/administrator/node_modules/meshcentral/meshrelay.js:394:82
    at FSReqCallback.wrapper [as oncomplete] (fs.js:517:5)

**Comment by Ylianst** [comment]
Oh dear! Good find. I am on vacation until mid next week, I will fix that when I get back. For now, you may need to disable indexing with :

```
"sessionrecording": {
  "index" : false
}
```

**Comment by petervanv** [comment]
i already did that so, happy vacation

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-q with a fix for this. The problem only happened on single CPU servers and would happen on all recordings. Let me know if it works for you.

**Comment by petervanv** [comment]
Hey ylian,

Unfortunately not, this error im getting now, with the recording en index on:
-------- 2020-3-3 11:29:52 ---- 0.4.9-r --------

internal/buffer.js:72
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:72:9)
    at Buffer.readIntBE (internal/buffer.js:431:3)
    at /home/administrator/node_modules/meshcentral/mcrec.js:260:22
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by Ylianst** [comment]
Ha! Thanks for reporting this! Going to investigate.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-u with a bunch of fixes about remote desktop indexing and playback. This fix the out of range error and more. Let me know if is works.

**Comment by petervanv** [comment]
hey ylian,
it is still crashing. the error is:
-------- 2020-3-4 19:52:47 ---- 0.4.9-u --------

internal/buffer.js:72
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:72:9)
    at Buffer.readUIntBE (internal/buffer.js:259:3)
    at /home/administrator/node_modules/meshcentral/mcrec.js:269:22
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by Ylianst** [comment]
Ok, will have one more fix for this in 0.4.9-z when I published it.

**Comment by petervanv** [comment]
I tried the latest update, it is working right now. (0.5.0-D) Confirmed Fix

Thx for your great software and support
