### ISSUE TITLE
Improvments: Consider use of SPICE and/or noVNC UI

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#958]
Hi,

I've been using MeshCentral and ProxMox a lot recently and noticed xTerm and [SPICE](https://spice-space.org/) perform very well in ProxMox. I have now see that xTerm is being used in Mesh (If it hadn't been done already, I was going to suggest this also). 
Would you consider intergrating [SPICE](https://spice-space.org/) into Mesh Central?
I've noticed very good performance for screen updates. It also has provisions for USB device mapping. Since it's Typical usage is from a driver level, a suggestion I read online was to use a mirror driver, hence something along the lines of [Mirage Driver](http://www.demoforge.com/dfmirage.htm). Just an idea if you didn't know of SPICE.

I would like to see a "Full Screen Mode" using Mesh where I don't have web browser bars and "mesh" control bars top and bottom". Yes I know I can use the router option to go directly to the machine.
I'm unsure if you are using the [noVNC](https://novnc.com/info.html) for MeshCentral if not, you may want to see how the noVNC User Interface Controls for sending custom key strokes are intergrated.

**Comment by marclaporte** [comment]
noVNC was added recently:
https://github.com/Ylianst/MeshCentral/commit/b93410844d5a2dfdf2b8886d34567330ca940a3d

**Comment by si458** [comment]
the use of spice wont be supported as spice is more of a VM protocol,
and as @marclaporte explained, novnc was added so if the remote device has VNC enabled, you can connect using it
