### ISSUE TITLE
How I can clear older events log using Meshcentral

### ISSUE THREAD

**Issue by AnjaniKumar15** [Ylianst/MeshCentral#959]

**Comment by Ylianst** [comment]
Try adding this to the settings section of the config.json:

```
    "DbExpire": {
      "events": 1728000,
      "powerevents": 864000,
      "statsevents": 2592000
    }
```

Above are the default values, they indicate in seconds how long to keep events. You can set the values you want. Once you change the config.json, reset the server. Let me know if that helps.
