### ISSUE TITLE
WebRTC freezing issue

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshCentral#96]
Im sure this problem is already known, as i saw other people are having the same issue. I didnt see an issue here for this yet, so i thought i open one.

When WebRTC is enabled, id say in about 50% of the cases when clicking "connect" on the desktop tab, the first image of the remote desktop is loaded and then it just freezes. i have click disconnect and connect again, sometimes multiple times until it works.

WebRTC is still very experimental in MC as i understood, so i guess this issue is not of priority but i still wanted to let you know about this.

**Comment by krayon007** [comment]
Which browser and what version are you using?

**Comment by marco-vogt** [comment]
Firefox 65.0.1 (64-Bit). I think i had the same issue on chrome as well but im not 100% sure and i cant check right now.

**Comment by Ylianst** [comment]
WebRTC support is different between Chrome and FireFox and changes from version to version making the job of fixing WebRTC for the latest browser a constant issue. I really want WebRTC to work since it allows a lot better server scaling and remote desktop speed.

**Comment by Ylianst** [comment]
Latest version of Chrome just seemed to have fixed the WebRTC large data fragment issue! So, WebRTC now works for me on both Chrome and FireFox. This said, if you can please test again and see if it works.

**Comment by Ylianst** [comment]
Closing this one as I am pretty sure it's been fixed long ago. Please open a new issue if WebRTC has problems.
