### ISSUE TITLE
bug : right click on list view or desktop view don't work, ok on column view

### ISSUE THREAD

**Issue by tranbert** [Ylianst/MeshCentral#961]
tested on firefox & brave

server 0.4.9.k

**Comment by Ylianst** [comment]
Oh yes... that is a bug. I cleaned up the right click context menu system in the latest releases, but failed to test the other views. I am on vacation until mid next week, I will fix this when I get back.

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-m with a fix for this. Let me know if it works.

**Comment by tranbert** [comment]
Yep ! Working.

Thank's

**Comment by Ylianst** [comment]
Nice. Thanks for confirming.
