### ISSUE TITLE
Question: stable releases?

### ISSUE THREAD

**Issue by edlins** [Ylianst/MeshCentral#963]
Is there any guidance on what version to upgrade to?  I see that we don't really have a choice of version from within the UI but I could choose the version via npm:
`npm view meshcentral versions`
and
`npm install meshcentral@<version>`

Is it always best to pick the latest, or are any releases considered more stable than others?  And is UI upgrading better/worse more/less stable than `npm` upgrading?  Thanks!!

**Comment by Ylianst** [comment]
There is currently no guidance for what version to upgrade to, just update to the latest one. This said, I may in the future tag some versions as "stable" in NPM. Also, the web interface and Windows Installer both call "npm install" in the background, so they should be exactly equivalent to doing it manually. There should be no benefits to using one technique over another.

Hope that helps.

**Comment by edlins** [comment]
Thank you!
