### ISSUE TITLE
Hide site for nginx

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#964]
Hi. I use meshcentral in combination with lets encrypt. You need to hide the site so that it would not be visible during normal surfing. Help me please.

**Comment by Ylianst** [comment]
Try adding the following line to the domain section of config.json:

`"loginkey":"mysecret"`

Once done, restart the server and try to access it, you will notice it will no longer work. When accessing your server, you will then need to add `?key=mysecret` to the URL. Let me know if this works.

**Comment by vyacheslav25** [comment]
Yes. It works. Thank you very much. Your project is very cool. Allows us system administrators to live better.

If it’s not difficult for you, then one more question.
When starting a macbook, the agent is not always monitored, sometimes you need to write in the terminal sudo launchctl stop mesh agent, sudo launchctl start meshagent.

Also, can I somehow remove the inscription 404 with the meshcentral shell?
I don’t want to understand that the site is meshcentral. Since this will allow an attacker to try to hack the site.

Thanks again.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.9-l with 404 page now hidden when "loginkey" is used, let me know if that fixes it.
