### ISSUE TITLE
MeshCentral Router Improvements

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#966]
Right now someone needs to understand networking and port forwarding to make use of this very usefull tool.
A user friendly version where once logged in, it displays a page like "My Devices" in the web GUI with icons for Desktop (RDP/VNC), terminal, etc with an option to create (and store on the server) Custom Maps that can be created with exisintg port mapping dialogue. (i.e. http maps) The ports will only be mapped/opened when the user first clicks on them and removed when the user loggs out.
It would also be Nice to have an option when creating the port Map to specify the application to use to open the new Map.  I.e. use TerraTerm or specfically Chrome.

It would be more like an App version of Mesh Central, where it uses the local apps for direct connection.

**Comment by OutbackMatt** [comment]
some other ideas
https://github.com/Ylianst/MeshCentralRouter/issues/1
https://github.com/Ylianst/MeshCentral/issues/669

**Comment by Ylianst** [comment]
Agree with this, the MeshCentral Router is really powerful and giving it a more usable user interface would make it even more useful.

**Comment by Ylianst** [comment]
Improved MeshCentral Router included in MeshCentral v0.5.0-q. Feedback appreciated.

![MC2-MeshRouter](https://user-images.githubusercontent.com/1319013/77222281-19d08980-6b0f-11ea-8f2f-2dcc6d0a583c.png)

**Comment by OutbackMatt** [comment]
really great 

Can the search also include search by tag, or group
Can the device names also include group name (I work with medical centres, and they all have a 'Reception1' and 'Reception 2' etc. It would help me to determine which is which

Can I get a count of active computers that are visible
Can I have a checkbox that removes the 'offline' ones, and have that view as the default

When sessions dropped I have to log in again(including TFA), unlike the meshCentral main web page which seems to use a session cookie, so when dropped, it just logs back on where it left off

I couldn't get http or https to work, so I'm not sure what they are meant to do

It would also be great if we could somehow save user credentials for RDP for EACH meshagent

**Comment by Ylianst** [comment]
All good requests. For HTTP and HTTPS, you need the remote computer to have a web server for this to work. I am guessing most computers you manage don't have that so, the browser will open but connection to remote 80/443 will fail. Hope that makes sense.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-u with small improvements with MeshCentral Router. There is a new menu you can use to show device group names, hide offline devices and adjust sorting.

![MC2-MeshRouter4](https://user-images.githubusercontent.com/1319013/77608454-7c909f00-6eda-11ea-8624-5db371faf822.png)

**Comment by Tomatoschewps** [comment]
Hi Ylianst,
We've see the last update for fast listing of agents on MesCentral Router and it's really fast ! Thanks :)
For us (me and somes of my collegues) an improvement that we hope to see one day is the abilitie to store Mappings on server side to share it between multiples (ldap) users. I see it has been asked here so ... +1 ^^

**Comment by b8two** [comment]
Hi Ylianst,

I really appriciate your taking on my suggestion.

- One minor improvement with the Search box, can you add a delay into the filter of half to one second?

With my installation, I have about 170 connected clients and big group of offline clients also. 
The instant search after pressing one letter takes about 10 seconds to then filter, where if it had waited for me to complete my text entry it responds much faster (As seen by pasting in what I want to search for).

- When Creating a manual Map, can the app remember the previous Device Group and Relay Device /Device when creating the 2nd Map, etc. (i.e. Current Session only). 

- Also it would be Awsome to be able to have custom mappings (perhaps configured via the web) to over ride the default 80,443,3389 options. 
i.e. I have a couple of devices I can't install mesh on but can access via a mesh connected device but I need to remember all the IP details, etc. (perhaps allow up to 4 custom maps (Label, Application,IP(127.0.0.1 or custom) ), with the first 3 being the default 80,443,3389 and the GUI automatically adjusts the button size between the 80/443 size to the RDP size. Perhaps the Use of Custom Maps could be via User Device Permissions enabled box.

**Comment by b8two** [comment]
Most possibilities are covered here;
[MeshCentral - RDP improvements & clipboard, Router Custom Apps,](https://meshcentral2.blogspot.com/2022/05/meshcentral-rdp-improvements-clipboard.html)
