### ISSUE TITLE
Suggestion: A clear way to identify which Windows 10 Version is deployed on the details page

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentral#967]
The Details page for Windows 10 indicates the Version build number but it's not as clear to know which release it is. 
The website: [ChangeWindows.org](https://changewindows.org/build/19564/pc) allows you to see all details of the build version. 
It would be nice to know the Release Verison like 1809  (Typically YYMM) of the version to know if the version is still supported
Perhaps have a link Icon at the end of the windows version to open a new tab to see more details from [ChangeWindows.org](https://changewindows.org/build/19564/pc)

**Comment by MailYouLater** [comment]
You can check the Windows Edition and Release ID in the registry:

    REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ProductName
    REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseID

Output:

    HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
        ProductName    REG_SZ    Windows 10 Home
    
    HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
        ReleaseID    REG_SZ    1909

**Comment by krayon007** [comment]
Thanks for the tip, I'll add that to the metadata passed to the server

**Comment by Ylianst** [comment]
Agreed, this would be great to have on the details page. Will work on this with Bryan in the coming weeks.

**Comment by krayon007** [comment]
Ok, I got this tested and added in the agent. It will be included in the next agent update. I made it so it checks if those reg keys exist (and are accessible), and if so, will use those, falling back to the old way if it doesn't work.

I found that older versions of windows such as Windows 7 and Server 2008 don't have those reg keys, but newer versions of windows like Server 2019 and Windows 10, have them... So I tested it on a couple different versions of windows to test. The field will get populated like this (on my machine anyways):

Windows 10 Pro - 1903 [Version 10.0.18362.657]

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.9-m with Bryan's improved OS information. This version of MeshCentral has Bryan's all new MeshAgents on all platforms, so all agents will auto-update and once they reconnect, you should see the new information. Let us know how it works for you.

![x](https://user-images.githubusercontent.com/1319013/75496181-4dd3e700-5975-11ea-980b-9c483ab1f7c1.png)

**Comment by MailYouLater** [comment]
Looks good on the General tab, but I think @b8two's original request to have it shown on the Details page should also be implemented, as the Details page should be _more_ detailed than the General page, not less detailed.

**Comment by Ylianst** [comment]
Working on it now :)

**Comment by Ylianst** [comment]
Just published MeshCentral v0.4.9-r with a better looking device details page. Feedback appreciated.

![MC2-DeviceDetails](https://user-images.githubusercontent.com/1319013/75730195-087b2680-5ca1-11ea-801f-53c6fadc5ae2.png)

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-s with network interfaces on the details page.

![MC2-DeviceDetails](https://user-images.githubusercontent.com/1319013/75815403-323b5880-5d48-11ea-816e-04a6a31ce999.png)

**Comment by ryanblenis** [comment]
Nice add, as @MailYouLater mentioned with the details page being more detailed, adding the connection gateway/IP (the "Address" on the "List" view page) which shows the agents public IP address would be a good add as well.

**Comment by petervanv** [comment]
nice additions, love it ;-)

**Comment by Ylianst** [comment]
@ryanblenis Hold my sugar free root beer... I can add that.

**Comment by Ylianst** [comment]
MeshCentral v0.4.9-t with agent information.

![MC2-DeviceDetails](https://user-images.githubusercontent.com/1319013/75823440-a11fae00-5d56-11ea-9c91-66043d70452f.png)
