### ISSUE TITLE
Server performBackup() exception

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentral#969]
I seem to get a couple of these each week. Doesn't seem to impact on the server's ability to run.

TypeError: Assignment to constant variable.
    at Timeout.obj.performBackup [as _onTimeout] (/etc/meshcentral/node_modules/meshcentral/db.js:1240:34)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by Ylianst** [comment]
Thanks for reporting this. I will take a look at this when I get back from vacation.

**Comment by Ylianst** [comment]
Fixed this one, will be in the next published version, MeshCentral v0.4.9-p, when I publish it later today.

**Comment by Ylianst** [comment]
MeshCentral v0.4.9-p got published (in fact I am at MeshCentral v0.4.9-p now). Let me know if it fixes this. Thanks.

**Comment by OutbackMatt** [comment]
Now I'm getting this backup error, each time that the backup runs

ERROR: Unable to perform database backup: Error: spawn /bin/sh EACCES

**Comment by si458** [comment]
closing as stale,
if you still have this issue,
please update to the latest version of meshcentral and try again
if your still having issues then please reply back
