### ISSUE TITLE
2 way communication between users and nodes

### ISSUE THREAD

**Issue by bengchet** [Ylianst/MeshCentral#97]
I have questions on how to do 2 way communication between nodes?

I have studied the use of websockets (meshuser) to do a few things like get all nodes, meshes as a user. And from the code I can see it is also capable of sending messages to specific node. I plan to develop an application on the node to receive and process these incoming messages. Is there anyway to do it or any documentation or reference I can look for?

Is it possible for my application to send message on behalf of meshagent and I can retrieve the message as meshuser? or can one node send the message directly to another node?

Thanks.

**Comment by jsastriawan** [comment]
Hi @bengchet, for communication between two nodes, it really depends on the network topology. However it may be possible to be brokered by some service leveraging MeshCentral 2 transport. there is a tunneling capability built in MeshCentral 2 that enable any TCP port forwarding. Have a look at mc2router utility in my GitHub repositories. You can create a tunnel to node for SSH, SFTP, RDP or any other traffic. You can create an app that connects to two different tunnels to two nodes and then shuffles data between those two tunnels.

Does this scheme work for you?

**Comment by bengchet** [comment]
Hi, 

Thanks for the reply.
In fact I have an existing application which built entirely in meshcentral v1. And I am looking for a solution similiar to messenger from meshcentral v1. Just wonder if meshmessenger v1.9x is compatible with meshcentral v2?

**Comment by jsastriawan** [comment]
Beng Chet,

MeshCentral 2 has different architecture. MeshMessenger API is no longer in MC2. Anyway, you can always use authenticated MeshCentral tunnel to talk to other node. However ability to tunnel to any node and talk to local service on each node is a better way of coordinating a group of service across device groups. If you want further discussion, please ping me through internal email or IM or talk to Maulik or Kana.

**Comment by Ylianst** [comment]
Right. MeshCentral2 is completely different from MeshCentral1. Pretty much a complete re-write. There is no agent-to-agent peering in MeshCentral2 right now and no plan for it anytime soon. If you want to have agents communicate between each other in MeshCentral2 you likely have to go thru the server.

There is no API documentation for this stuff, but of jsastriwan can help break the code open.

**Comment by bengchet** [comment]
Hi, I have given a look on https://github.com/jsastriawan/mc2router and I have used mqtt as traffic for  tunneling for the application. Thanks.
