### ISSUE TITLE
Synology Nas (question)

### ISSUE THREAD

**Issue by coolwormgit** [Ylianst/MeshCentral#973]
Hello, i successful manage to install meshcentral server on synology nas, my problem is when i start it from command line with "node meshcentral" the server starts as Lan mode and i can use for internal lan, how can i execute mesh as hybrid in linux command line??
thanks

**Comment by jsastriawan** [comment]
You should add --cert FQDN or for permanent setting you should consider using config.json. There are some documents you could find to properly configure Meshcentral. See the readme.md of this repository.

**Comment by coolwormgit** [comment]
ok, do i have to point when i execute meshcentral where the config is?? i made changes to config.json but still use the defaults options

**Comment by jsastriawan** [comment]
I assume config.json is in meshcentral-data folder. Meshcentral uses that location for config.json.

If you look at config.json in that folder, most variable names start with underscore (e.g. _Cert..etc). You should remove '_' to use those variables.

**Comment by coolwormgit** [comment]
ok , for some reason the config file it was in node_modules folder! copied to data folder and its working! thanks!!

**Comment by coolwormgit** [comment]
im running the server on port 38000 but when i use winscp or rdp the clickonce searching my.domain without port... is anyway to fix this?

thanks

**Comment by coolwormgit** [comment]
ok found it! thanks
