### ISSUE TITLE
GreenLock is not auto-updating

### ISSUE THREAD

**Issue by asasin114** [Ylianst/MeshCentral#978]
When I restart my MeshCentral server I get the following cluster of errors right after the service starts up and then I get a handful of the third error throughout the day. I can't quite tell what it's complaining about. Anyone have any ideas?

-------- 2/27/2020, 8:32:16 AM ---- 0.4.9-k --------

(node:7564) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT ipaddress:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)

-------- 2/27/2020, 8:32:16 AM ---- 0.4.9-k --------

(node:7564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------- 2/27/2020, 8:32:17 AM ---- 0.4.9-k --------

(node:7564) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT ipaddress:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
(node:7564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by petervanv** [comment]
#909 looks like the same issue, try to update greenlock, that was working in my case

**Comment by asasin114** [comment]
Could be but I'm using Windows Server, my bad for not saying anything. Can I manually upgrade GreenLock on Windows?

**Comment by petervanv** [comment]
https://docs.npmjs.com/try-the-latest-stable-version-of-npm (how to page) there seems to been automated tool too

**Comment by asasin114** [comment]
@petervanv So I'm updating NPM not Greenlock itself?

**Comment by petervanv** [comment]
https://www.npmjs.com/package/greenlock

**Comment by asasin114** [comment]
Looks like that may have fixed it. I'll keep an eye on it for a few days and see what happens.

**Comment by Ylianst** [comment]
Oh dear. I need to start pinning the GreenLock version, @TotallyNotElite made a pull request a long time back that will be of use here.

**Comment by Ylianst** [comment]
In MeshCentral v0.4.9-u, I now force GreenLock v4.0.4 to be installed if any other version is installed. That should cause everyone to have constant results.

**Comment by asasin114** [comment]
Looking good to me!

**Comment by Ylianst** [comment]
In the latest MeshCentral v0.5.0-e, there is no more GreenLock, it's acme-client now. When updating, it will take a minute or two for the new library to request a new Let's Encrypt certificate and start the server again.
