### ISSUE TITLE
Windows Server : Unrecognized configuration option "plugins".

### ISSUE THREAD

**Issue by openmoto** [Ylianst/MeshCentral#979]
Hi @Ylianst ,
Are plugins supported on windows server?
I've just added 
`   "plugins": {
     "enabled": true
	},`
To my json file and restarted and I'm getting an error;

Server Warnings:
WARNING: Unrecognized configuration option "plugins".

Server:
Windows Server 2012 R2 , 64bit
MeshCentral Version 0.0.9-k

**Comment by ryanblenis** [comment]
Hi @openmoto,

You'll want to make sure that exists under the "settings" key. If you added it to the end of the file it may not be in the right place.

**Comment by openmoto** [comment]
I think it's inserted correctly.
Here's what the json looks like.
![image](https://user-images.githubusercontent.com/36439190/75482987-15c3a880-5963-11ea-97c6-9cc94f5bc6ac.png)

**Comment by ryanblenis** [comment]
Hi @openmoto,

In your screenshot the "plugins" key exists adjacent to the settings, not within it. Move the plugins directive to exist inside the settings key and it should work.

**Comment by openmoto** [comment]
Got it!
![image](https://user-images.githubusercontent.com/36439190/75486677-317e7d00-596a-11ea-9171-1ff8aa0d7be2.png)

Thanks!!
