### ISSUE TITLE
Error message from MeshAgent after server update

### ISSUE THREAD

**Issue by billymoox** [Ylianst/MeshCentral#98]
After the server is updated to 0.2.8-f, the following error message is shown in the console tab for each remote device. The MeshCore is v6.

"uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: Duktape_GetBuffer(): Unknown parameter in method 'handleServerCommand()'"

**Comment by krayon007** [comment]
This was already fixed a few days ago, but the last server update didn't include the agent update. This will be released soon.

**Comment by Ylianst** [comment]
Should be fixed now on all Windows and Linux versions except MacOS.

**Comment by Ylianst** [comment]
Closing this one as I am pretty sure it's fixed.
