### ISSUE TITLE
2 suggestions on system account security

### ISSUE THREAD

**Issue by billydu1980** [Ylianst/MeshCentral#982]
Dear Ylianst and your team:

Can you help to add a few lines of code to implement some security policies for user accounts in MeshCentral Console.

a) The system has the function of account password change reminder, and the reminder and expiration period can be set to 1-90 days.

b) Within 3 minutes, the system account password is input incorrectly 5 times, and the account is disabled for 10 minutes.

Thanks so much.
Billy Du

**Comment by Ylianst** [comment]
Hi. You can take a look at the sample-config.json for ideas on how to configure MeshCentral. In the domain section of the config.json, you can add this:

`"PasswordRequirements": { "min": 8, "max": 128, "upper": 1, "lower": 1, "numeric": 1, "nonalpha": 1, "reset": 90, "force2factor": true, "skip2factor": "127.0.0.1,192.168.2.0/24" }`

This will adjust password requirements. In your case, I think this will do:

`"PasswordRequirements": { "reset": 90 }`

For invalid logins, try this in the "settings" section of config.json. The default is 10 passwords in 10 minutes with a 10 minute cooloff like this:

`"MaxInvalidLogin": { "time": 10, "count": 10, "coolofftime": 10 }`

So, even if you don't configure anything, you get the line above. However in your case try this:

`"MaxInvalidLogin": { "time": 3, "count": 5, "coolofftime": 10 }`

This should allow 5 attempts in 3 minutes. Note that this is for any account username, not just one account name. Let me know if that works for you.

**Comment by billydu1980** [comment]
The test went well, no problem. 
Thanks so much.

Billy Du
