### ISSUE TITLE
Disable Remote Desktop, Files and Terminal

### ISSUE THREAD

**Issue by vyacheslav25** [Ylianst/MeshCentral#983]
Hello again. You need to turn off the ability to watch people in Meshcentral, and the Files Terminal is desired.
We use MeshCentral to administer the power of computers and laptops. And we do not want to have access to personal files and actions of employees.
Thanks for the support in past questions.

**Comment by Ylianst** [comment]
Ok, I can work look into this.

**Comment by trenton92** [comment]
It would be nice to implement this. I would be very happy if you implement this. We use lenovo with amt support and your server and we really like the remote desktop functions, they are faster and smoother amt, but the user is not notified when the connection arrives, maybe it’s worth making some window from above, as in rdp.
I agree in support of this request.
Thank you very much for your work.

**Comment by krayon007** [comment]
That feature already exists. If you enable the connection notification bar in the setup, then when you connect a remote desktop, a nonremovable notification bar will appear on the display.

**Comment by trenton92** [comment]
Please help me find her, checked everything, did not find her.

**Comment by MailYouLater** [comment]
![image](https://user-images.githubusercontent.com/1279475/75824538-86e6cf80-5d58-11ea-9d64-8be019112125.png)

**Comment by si458** [comment]
This is now possible with permissions
You can set per user what access they have to different devices or different groups, like remote access but no files access l,
Even the user must show notification to end device when they connect
