### ISSUE TITLE
The Desktop tab for my Debian Buster client is missing

### ISSUE THREAD

**Issue by jradxl** [Ylianst/MeshCentral#984]
I have Debian Buster 10 Mate 1.20.4 installed on a small PC, with kernel  5.4.0-0.bpo.2-amd64
But the Desktop tab is missing.
As it happens, I can make a direct connection to the PC with Xrdp and there is no problem with showing the desktop.
I have followed the comments in another Issue posted here as to reinstalling the agent, via MeshCentral Console and via the PC's command line but this does not bring it back.
(My Ubuntu 19.10 and Window 10 machines are fine by the way)
I've not been able to find any logging files, nor any option for this in config.json
if you can tell me how to turn on logging, or more troubleshooting steps, I'll see if I can find issue.

**Comment by jradxl** [comment]
OK, I've got a bit more info....
'sendcaps 15' does bring up the Desktop tab...
If I have a Xorg sesssion running in the client with display :0 I then get the Lightdm login in page.
.
If I have disabled the default session, with
```
[LightDM]
start-default-seat=false
```
And I connect with Xrdp giving a display ":10" then that session is shown in Meshcentral also after 'sendcaps 15' is issued

Needless to say, this is a headless PC, but running Xorg MATE
I normally run with the :0 session off as there is little point. Teamviewer and Anydesk only give a 1024x768 resolution in this case so I've stopped using them!

So, the X redirect is working, but there is a reason the Agent doesn't inform the Host, on Debian.
Perhaps you can advise.

**Comment by jradxl** [comment]
I've done some more experimentation with a different Debian machine running Stretch...
1. I wonder whether MeshCentral is expecting the Gnome Desktop to be installed?
This PC originally had only Mate desktop installed (1.20 from backports), and exhibited the same issues as I reported above.. I installed Gnome from backports, and the Desktop tab now appears to be present. I'm not clear whether MeshCentral will "remember" some of the settings I've tried when logging in - if so, then I'm see the Desktop tab from my use of SendCaps 15, and not the fact I've installed Gnome!

2. The test above was done with a dummy display HDMI plug from Amazon, and setting start-default-seat=true so a default desktop on Display :0 is started. This appears to work fine, with the Display tab offering a Lightdm login page where I can select a default desktop, and once logged in allowing me to change resolutions. (Without the dummy plug, only a 1024x768 screen is offered

3. So, is MeshCentral only designed to work with PCs with real displays (or dummy plugs), and not like Xrdp or x2go, where where a virtual desktop is created?

**Comment by Ylianst** [comment]
If you got in the device "Console" tab and type `info`, it will show `X11 support: true.` if the MeshAgent detected X11. It will then add the "caps" flag to enable remote desktop. In addition, the MeshAgent is intended to remote the physical display, not launch a new virtual display. We could add support for virtual displays in the future, but for now, a dummy plug is a good solution.

Bryan who works on the agent will probably have more knowledge on this.

**Comment by si458** [comment]
closing as stale,
but also note you MUST change from waykland to X11 for the remote tab to display and work correctly
https://github.com/Ylianst/MeshAgent?tab=readme-ov-file#special-note-about-kvm-support-on-linux
