### ISSUE TITLE
Windows 10 IoT Core Support

### ISSUE THREAD

**Issue by bhartman-livewire** [Ylianst/MeshCentral#985]
I'm having some trouble getting a mesh agent installed on a Raspberry Pi 3B that's loaded with Windows 10 IoT Core.
As you know, the Pi has an ARM processor so the x86 and x64 exes will not run.
Therefore, I downloaded the meshinstall.sh file but cannot seem to run the shell script in Windows PowerShell:
`meshinstall.sh https://meshserver.myserver.net 'bZaYrCKaWbHlqoCZ2UnPoYQ9XXXXXXXXXXXXXXXXXXXXX'`

**Comment by Ylianst** [comment]
You can get a list of the MeshAgents that we compile by adding /meshagents at the end of the MeshCentral URL, for [example here](https://meshcentral.com/meshagents). We don't currently compile a MeshAgent for Windows 10 IoT Core on ARM. I guess we could try to compile one for it if there is a lot of request for it.
