### ISSUE TITLE
certoperations.acceleratorPerformOperation

### ISSUE THREAD

**Issue by sangrae** [Ylianst/MeshCentral#987]
const program = require('path').join(__dirname, 'meshaccelerator.js');
...
857: program.processMessage({ action: operation, data: data, tag: tag, func: func }); 
program is string.

**Comment by Ylianst** [comment]
What version of NodeJS are you using?

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-q with a fix for this.

**Comment by sangrae** [comment]
This issue has been fixed. By the way, the following problem occurred.

Error:
 [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6.

mcrec.js:260
 r.time = buf.readUIntBE(8, 8); (in readNextBlock)

readUIntBE byteLength maybe 6.

**Comment by Ylianst** [comment]
Published MeshCentral v0.5.0-d with fixes to session recording & indexing. Should work now (hopefully).
