### ISSUE TITLE
agent 32 bit clear core

### ISSUE THREAD

**Issue by Ilia1** [Ylianst/MeshCentral#989]
Plugins EventLog and ScriptTask are installed, maybe one of them. I open the device with 32 bit agent, only the event tabs, details, console and plugins are available. I load the core by default - all tabs appear, I can connect to the desktop. After a while, the kernel clears and again the tabs are inaccessible. There is a log in the agent folder.
[MeshAgent.log](https://github.com/Ylianst/MeshCentral/files/4279456/MeshAgent.log)

**Comment by krayon007** [comment]
Does this issue only occur when those plugins are installed? (And only on the 32 bit agent, not the 64 bit agent?) Based on the messages in the log, the javascript runtime is stuck in an infinite loop or a blocking operation.  I"ll try to run some tests when I get back in the office.

**Comment by ryanblenis** [comment]
Also interested to know if that happens only with those plugins installed / running.

FYI you can disable the plugins directive in the config.json (by preceding the key name with a `_`) and restart meshcentral to run without plugins momentarily. No plugin data will be lost.

**Comment by rowds15** [comment]
Hi I seem to be having the same issue. only on the 32bit version. and i don't have the plugins directive in my config at all. I am able to fix by uploading the default server core. but after a while it reverts back to the reported bug

**Comment by Ylianst** [comment]
I am seeing the same thing on 32bit Windows Agent. This will bad. I will be working on this as soon as I get the new Let's Encrypt code out the door.

**Comment by canove** [comment]
Same here with 32bit clients. Btw, where I can find these plugin your talking about??

**Comment by ryanblenis** [comment]
Hi @canove,

I typically announce plugins on the projects [subreddit](http://reddit.com/r/meshcentral)

But here are links to a few I've created:
https://github.com/ryanblenis/MeshCentral-Sample
https://github.com/ryanblenis/MeshCentral-ScriptTask
https://github.com/ryanblenis/MeshCentral-RoutePlus
https://github.com/ryanblenis/MeshCentral-EventLog
https://github.com/ryanblenis/MeshCentral-DevTools

I know there is at least one other plugin developer, but I don't know that they've released their first project yet. The plugin system was implemented a short time ago, so we're just getting the ball rolling with them!

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-y with a fix for this. The 32bit "meshservice-signed.exe" agent was actually not signed. The server would see the agent connect and because it's an older agent, would tell the agent to clear the core in preparation for an update that would not work. Let me know if this fixes it.

**Comment by rowds15** [comment]
Hi Ylian, so far so good. I have checked some of my 32bit clients and they are working as expected.

**Comment by Ylianst** [comment]
@rowds15 Thanks for reporting back. I will keep this open a few more days in case there are more reports on this.

**Comment by Ilia1** [comment]
Yes it works. Thanks for the fix.
