### ISSUE TITLE
Show tooltip to enable KVM/SOL features (like in MeshCommander)

### ISSUE THREAD

**Issue by gertvdijk** [Ylianst/MeshCentral#99]
Steps to reproduce:

1. If not disabled already (it is disabled by default on my Dell Latitude) - _disable_ the KVM and SOL features in the AMT menu "Active Features":
  ![features-list2](https://user-images.githubusercontent.com/1550527/52815602-642b3f80-309f-11e9-8459-0f5248d4f21f.png)
1. Go to the Desktop tab.
1. Hit "HW Connect"
1. Find yourself wondering why it can't connect.
   ![not-connecting](https://user-images.githubusercontent.com/1550527/52815777-cf751180-309f-11e9-877a-9a21eb57893b.png)
   *You're going over all those options like user consent, start fiddling with wsmancli and whatnot.*
1. Open MeshCommander (not MeshCentral) and configure the host there.
1. Open the Desktop of the host there.
1. Find yourself a nice popup that you have to enable KVM first!
   ![tooltip-to-enable](https://user-images.githubusercontent.com/1550527/52815793-e0be1e00-309f-11e9-8869-4bfd340fdbe2.png)
1. Hit the button/popup. All works now also in MeshCentral.

This setting could also be controlled in MeshCentral (as in first step, just to be able to reproduce), but I was totally unaware of this, being a first time user.

As I was unaware those settings could be controlled in the AMT settings, I have been wondering for hours why my remote desktop control wasn't working in MeshCommander. Also the user manual does not mention this.

**Comment by jsastriawan** [comment]
Hi,

This is the default setting of AMT after manual provision.  The status of whether features are enabled or not is accessible via WSMAN.

Tooltip may be possible however if AMT credential is not set for MeshCentral, I believe it there is no way to probe if KVM and Redirection are enabled.

**Comment by gertvdijk** [comment]
@jsastriawan I'm not sure I understand...

* Once can request and change the current status perfectly fine on the AMT tab as I indicated.
* *My system's* default setting after manual provisioning is that this is disabled. Just tried an unprovision/reprovision and it's off again (Dell Latitude E7470), even though MEBx shows KVM feature is enabled, it isn't until I flip the bit in MeshCentral.

**Comment by jsastriawan** [comment]
Gert,

MeshCentral at the moment has not use AMT API outside Intel AMT/MeshCommander panel yet. The AMT status reported by device status page of mechcentral is reported by MeshAgent and it is obtained through AMT Management Engine Interface driver. There will some significant effort to add that capability. Not sure if that is the current priority at the moment.

Regards,


Joko

**Comment by gertvdijk** [comment]
Okay, I understand it is significant effort for a little UX improvement then.

<sup>I find your explanation around different APIs rather peculiar, because all the web app is doing from the browser perspective is talking to MeshCentral over websockets it seems.</sup>

**Comment by jsastriawan** [comment]
Gert,

MeshCommander runs in iframe. It has some flexibility to have AMT WSMAN stack in itself. We could theoretically add the same stack but I think it would be great to get all the data from backend and the AMT stack is executed at the backend. It will be lighter on the frontend side.

**Comment by Ylianst** [comment]
Sorry for the delay, I was busy this week but things are getting back to normal. This is not something I will fix short term, but it is an issue. Once I get a Intel AMT WSMAN stack running in the server, I will be collecting that sort of data and will be able to display the warnings. The HW KVM viewer in MeshCentral also needs better integration with WSMAN for multi-display selection, power actions and more. It's certainly a limitation of the current viewer.

One thing I can do is enable the desktop and terminal tabs in MeshCommander within the "Intel AMT" tab. It's a bit weird to have two AMT remote desktops viewers in two tabs, but that is possible short terms (flip of a switch) if that would be useful.

**Comment by gertvdijk** [comment]
Thanks for your response :)

If it would be hard to make it as nice as MeshCommander, I'd suggest picking some lower hanging fruit instead:
* Highlight the *disabled* features prominently in the AMT tab. I would have spotted a bold-red font or a separate row "Disabled Features" in that table.
* Mention it in the manual, KVM is a separate AMT feature that could be disabled and can be enabled in the AMT tab.
