### ISSUE TITLE
Updated language file Dutch (little fr) 0.4.9-S

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#990]
My local was showing blank spaces but online translate.json did not show that locations, so translated i translated it by your tool.
 
UPDATED FILE versieon 0.4.9-S 
[translate.zip](https://github.com/Ylianst/MeshCentral/files/4283576/translate.zip)

**Comment by Ylianst** [comment]
Thanks! Adding this now, will be in next published version.

**Comment by Ylianst** [comment]
Hi. So, the file you sent me is not valid in various ways. It's not valid JSON, not UTF-8 encoded and not ordered using the standard order. What tool did you use? Not sure I can include it.

**Comment by petervanv** [comment]
its edit with your tool, strange thing normaly i edit the file online on github, but the strings could not be found it the translate.jsong on github

**Comment by Ylianst** [comment]
"its edit with your tool"... Can you specify what tool you are using? Thanks.

**Comment by petervanv** [comment]
ResourceTranslator
