### ISSUE TITLE
Multi Display Problem with Latest versions.

### ISSUE THREAD

**Issue by 82280zx** [Ylianst/MeshCentral#991]
I used to be able to select Display 1 or Display 2 so I could see it better in fullscreen, now when I select them using firefox nothing happens.

**Comment by Ylianst** [comment]
Just tested this and it works for me. You going to have to report a lot more details, what OS is the remote agent, what version of the server, that browser, does it fail only on firefox and not on other, etc. Please file again with way more details.

**Comment by 82280zx** [comment]
Firefox V73.0.1 (64-bit), Mesh Central Server Version 0.4.9-u, Windows 10 Version 1903, Tried it with Google Chrome version 80.0.3987.132 64-Bit, Latest Client Version (reinstalled from Mesh Central Server to be sure), Internet Explorer Version 11.657.18362.0 , Tried it on my work computer and my laptop both, any options I select on display mode doesn't change / update the display to single display.
