### ISSUE TITLE
Agent source code?

### ISSUE THREAD

**Issue by stevesobol** [Ylianst/MeshCentral#992]
There is probably a simple answer to this question, that I am missing:

I'd like to customize the agents (the Windows agent right now, maybe other platforms later) to include my branding and remove some of the information that end-users won't care about. I'm looking at eventually deploying this as a replacement for Connectwise Control, which works well but is not extensible and not anywhere as customizable as it should be.

So where is the source code for the agents? I see a bunch of .exe files and ZIP files committed to the repo, but I'm not sure where the source is.

I can work with C++, C#, Swift, or Java...  Just not sure what to customize. 

Thank you :)

**Comment by krayon007** [comment]
https://github.com/Ylianst/MeshAgent

**Comment by krayon007** [comment]
Most of the exposed functionality of the agent, is via the meshcore.js javascript file the server sends to the agent. You should be able to accomplish most of what you need without having to modify any of the actual agent source code. For the most part, the agent binary is just a runtime container that connects a control channel to meshcentral. The actual work that the agent does, is performed by the javascript that gets send to the agent by the server.

**Comment by stevesobol** [comment]
What I'd like to do is customize... I guess it's the installer. I'd like to change the UI with the Connect/Install-Update/Uninstall buttons. So you're saying I can do this without having to modify the source? That would be awesome.

**Comment by ryanblenis** [comment]
Are you looking to customize that screen? If so, it appears to be in /MeshService/MeshService.rc and /MeshService/MeshService64.rc.

 Or are you just trying to get a silent install?
meshagent.exe -fullinstall will get you a silent install.

**Comment by Ylianst** [comment]
You can run the MeshAgent with command line arguments such as `MeshAgent.exe -help` or `MeshAgent.exe -fullinstall`. One idea would be to wrap the MeshAgent within another installer with a different user interface.

**Comment by stevesobol** [comment]
Yes. That's exactly what I'm trying to do, customize that screen.  I'm looking at MeshService.rc and that appears to be what I was looking for. But I think it might be a lot easier to wrap `MeshAgent.exe` within another installer. That's what I'll do.

Thank you for your help!
