### ISSUE TITLE
Is it possible to connect to a Windows agent using an RDP console session?

### ISSUE THREAD

**Issue by stevesobol** [Ylianst/MeshCentral#993]
It looks like MeshCentral uses RDP to control Windows devices. But if I'm working with a client and need to see exactly what he or she is seeing, I can't. If I connect using MeshCentral, the local user gets booted. Can I connect to the console? I believe this is doable using the standard Windows RDP client if I pass the /console commandline option to it.

I mean, I could use VNC, but VNC is clunky, very slow, and extremely insecure. And I don't know if MeshCentral even has the option to use VNC to connect to a PC running Windows.

Thanks :)

**Comment by krayon007** [comment]
I"m not understanding the scenario. MeshCentral does not use RDP to connect to the agent, and by default connects to the console session when you use KVM. Are your clients connected to the system on an RDP session, and you are trying to access the RDP session with KVM? If so, we added support for specifying specific sessions to connect to. I'd have to consult @Ylianst  to see how it was implemented in the web interface.

**Comment by stevesobol** [comment]
RDP is great for remote access. It's very performant, unlike insanely verbose protocols like RFB (and I actually got paid to make some modifications to a Java VNC client once, so I'm more familiar with RFB than I want to admit... yuck)

But here's my scenario.

I am an IT support provider and I do a lot of my work remotely.

ConnectWise Control (which I use), AnyDesk (which I also use) and NoMachine (which I've used in the past) provide a way to see what the end user is doing, while they're doing it. That is, ultimately, what I need.

And honestly, I'm probably misunderstanding how MeshCentral works. :) Should I be able to do what I want to do? 

I've never heard the acronym KVM used in reference to remote control. Virtualization, yes, but not remote control or remote access. So I'm geniunely confused :)

**Comment by ryanblenis** [comment]
FYI KVM is Keyboard, Video, Mouse in this context- and fairly standard in the industry.
While you CAN make an RDP connection from the "General" tab of the device, selecting the "Desktop" tab will get you a "shared" desktop with the user.

**Comment by krayon007** [comment]
@stevesobol , can you go to the console tab, and type the command "activeusers" without the quotes, and hit enter, and report back what you see?

Normally, remote control should work as you describe. The only scenario I've seen it not work that way, is if the terminal services IDs do not match. By default, remote control will enumerate the TSID's, and connect to the one associated with the physical console. But if we start here, I can at least see what TSID's are currently on your client system, and what the metadata is with each one, then we can go from there.

**Comment by stevesobol** [comment]
```json
[
 {
  "tsid": "4",
  "type": "Console",
  "user": (the user I'm logged in as),
  "domain": (my server's hostname)
 }
]
```

**Comment by alesribic73** [comment]
When you select machine in MC2 you have a small blue links below. One is RDP. Use IE!!! After you click RDP it opens a kind of router and RDP session opens just like if you have direct RDP. Works fine

**Comment by krayon007** [comment]
Can you try the command "users" on the console tab, without quotes?

**Comment by OutbackMatt** [comment]
> ...if I'm working with a client and need to see exactly what he or she is seeing, I can't. If I connect using MeshCentral, the local user gets booted. 

I think MeshCentral by default takes over the console session of a RDC (Terminal Services) server. You will boot (or take over) the local user if there is one.
 
I haven't seen how to take over other sessions (but I'd love to) from the server. I can see a list of these users

What I normally do is take over the machine (via MeshCentral) that the remote user is physically sited at, and then see their  RDP connection to the RDC server

**Comment by krayon007** [comment]
If you hold the shift key while you click on connect, it should show a context menu allowing you to select a specific session. (This menu will only show, if there is more than one session)

**Comment by unguzov** [comment]
Great functionality! Maybe it will be more user-friendly if "shift-click" is used by default when more than one RDP sessions are active on the remote computer?

**Comment by krayon007** [comment]
That's the plan. It was only behind s keyboard shortcut so we could polish the ux later.

**Comment by Ylianst** [comment]
Latest versions of MeshCentral now always display the list of sessions when more than one is present. You can shift-click "connect" to skip the selection and go directly to the main console.

**Comment by stevesobol** [comment]
So... ladies and gentlemen... I can't believe I made this mistake. I really can't.

My total misunderstanding of how MeshCentral works was based on an erroneous assumption that RDP was ALREADY being used. And THAT was based on the fact that if someone else is logged on via RDP and I connect via KVM with MeshCentral, they get disconnected.

But the same thing would happen if I was physically sitting in front of the keyboard and logging in. If someone else is connected via RDP, they get disconnected when I log in locally.

I am SO sorry. I've done Windows support since the days of Win95. Longer than I've been a developer. And I should have remembered this.

**Comment by Ylianst** [comment]
Thanks for the response. Right, MeshCentral does not use RDP when using the "Desktop" tab in the web page. We use our own protocol that is a bit like VNC.
