### ISSUE TITLE
update from 0.4.9-v to 0.4.9-w error

### ISSUE THREAD

**Issue by petervanv** [Ylianst/MeshCentral#996]
when i try to update from version 0.4.9-v to version 0.4.9-w server restarts, but did not install version -w.

when i use  npm install meshcentral@0.4.9-w it displays the following error. 
![update 0 4 9-w](https://user-images.githubusercontent.com/58996467/76023110-cd8b2400-5f28-11ea-8a24-63620b6d2120.jpg)

**Comment by petervanv** [comment]
[2020-03-05T20_28_01_064Z-debug.log](https://github.com/Ylianst/MeshCentral/files/4295041/2020-03-05T20_28_01_064Z-debug.log)
logging from the install 0.4.9-w

**Comment by Ylianst** [comment]
Oh!!!! Working on it now!!!

**Comment by Ylianst** [comment]
Publishing new version now!

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.9-y with a fix. There was dependencies in the package.json that should not have been present.

**Comment by Ylianst** [comment]
Let me know if this works for you.

**Comment by petervanv** [comment]
its fixed, installing version 0.4.9-Y now
