### ISSUE TITLE
Configure Wake Alarms

### ISSUE THREAD

**Issue by dll22** [Ylianst/MeshCentral#997]
How do I configure Wake Alarms to turn on equipment at 08:00 am five days a week?

**Comment by Ylianst** [comment]
There is no way to do this right now on the web site. You could take a look at "meshctrl.js", it's a command line tool that is included in the MeshCentral folder (node_modules/meshcentral/meshctrl.js) that can be used to perform management operations on MeshCentral. I could add power actions to that tool and you can invoke it when you want.

**Comment by dll22** [comment]
Ok, thnaks by the return and I will assess the reported condition.
