### ISSUE TITLE
Add User on Device Group with rule "No Desktop"

### ISSUE THREAD

**Issue by trenton92** [Ylianst/MeshCentral#998]
Add the ability to turn off the remote desktop, if possible.
If you remove Remote, then you can’t control the power, but I need the user to be able to only turn off computers
Thanks again for the feedback
![image](https://user-images.githubusercontent.com/61736438/76083493-72077780-5fb6-11ea-844c-1ef123a07dd2.png)

**Comment by Ylianst** [comment]
Good request. Published MeshCentral v0.4.9-z with added support for this. Let me know if it works.

![x](https://user-images.githubusercontent.com/1319013/76127018-7da66e80-5fb5-11ea-81e8-1bfddd9fd325.png)
