### ISSUE TITLE
RDP - USB Redirection Failure

### ISSUE THREAD

**Issue by SomeGuru** [Ylianst/MeshCentral#999]
Hi Ylianst and Team,

So within my environment at work we enable RemoteFX USB Redirection access on our platforms. This does work really well even within the corporate environments we work with outside of our company... However when doing the RDP over meshcentral it seems that that redirection is some how mutex'd and that means that the redirection makes the device not available on the local or remote side even though it has enumerated perfectly fine. Have you got some answers around this?

Configurations effected:
Windows 10, Windows Server 2016, USB external hard drive that was RemoteFX USB Redirected from machines without failure over localized RDP session.

To enable the RemoteFX USB Redirection do so via GPEDIT.MSC and then drilling down this path:
Local Computer Policy>Computer Configuration>Administrative Templates>Windows Components>Remote Desktop Services>Remote Desktop Connection Client>RemoteFX USB Device Redirection> Allow RDP Redirection of other supported RemoteFX USB devices from this computer>enabled.

**Comment by krayon007** [comment]
So just to clarify, are you establishing a port redirection on meshcentral, and using a Microsoft RDP client to connect thru the tunnel?

**Comment by Ylianst** [comment]
If you are using port redirection to perform RDP, at this point I don't think USB redirection in RDP is a MeshCentral problem. Not sure what we could do to fix this.
